### ISSUE TITLE
Would you add sequences' accession ID information to the lineages.metadata.csv?

### ISSUE THREAD

**Issue by godtao2** [cov-lineages/pango-designation#100]
Hi,
I want to build a phylogenetic tree according to your lineages.metadata.csv, which was hosted in pangoLEARN. Accession ID information is necessary for me. However, in the latest version (2021-05-27),  lineages.metadata.csv was no longer hosted. I found the file in the pango-designation repository, but it only provides strain names and lineages information. Would you provide the file which also contains accession ID information? Or just add this information as a new column in the file?
Thanks for your help!

**Comment by aineniamh** [comment]
Hi @godtao2, we have that file with accession ID also in this repo: https://github.com/cov-lineages/pango-designation/blob/master/lineages.metadata.csv
It's slightly out of date, but will have it integrated into updates soon.

**Comment by godtao2** [comment]
> Hi @godtao2, we have that file with accession ID also in this repo: https://github.com/cov-lineages/pango-designation/blob/master/lineages.metadata.csv
> It's slightly out of date, but will have it integrated into updates soon.

OK. Thanks for your help!
