### ISSUE TITLE
BA.5.1+C29614T sublineage with Orf1a:K1407M and S:346T (55 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1000]
I open this issue to monitor one more lineage carrying S:346T.
i tracked it initially in #865 as many others now designated

It is a BA.5.1 sublineage defined by 
C29614T
then Orf1a:K1407M (A4485T)
and S:R346T (22599C)

![Schermata 2022-08-28 alle 01 59 14](https://user-images.githubusercontent.com/87669813/187051933-bab12086-7a12-45f0-9679-8c711573ce76.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37e3a_aaf320.json?branchLabel=aa%20mutations&label=nuc%20mutations:A4485T

Nr of sequences : 32 on Usher , 32 on Gisaid (Query:NSP3_K589M,Spike_R346T)
First sequence: 
hCoV-19/Portugal/PT38291/2022  EPI_ISL_13761503 collected on 23/06/22
Countries: mainly Portugal, Belgium and  Usa
Sequences:
EPI_ISL_13885924
EPI_ISL_14493526
EPI_ISL_14336621
EPI_ISL_14439978
EPI_ISL_14396115
EPI_ISL_14467890
EPI_ISL_14520206
EPI_ISL_14097088
EPI_ISL_14487333
EPI_ISL_14352905
EPI_ISL_14584668
EPI_ISL_13892561
EPI_ISL_13834843
EPI_ISL_14298068
EPI_ISL_14280957
EPI_ISL_14299092
EPI_ISL_13956471
EPI_ISL_14623986
EPI_ISL_14262569
EPI_ISL_14609549
EPI_ISL_14530906
EPI_ISL_14236441
EPI_ISL_13761496
EPI_ISL_14236426
EPI_ISL_14504021
EPI_ISL_13761503
EPI_ISL_14408324
EPI_ISL_14501159
EPI_ISL_14263676
EPI_ISL_14476698

CovSpectrum overview : https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1a%3AK1407M%2CS%3A346T&nextcladePangoLineage=BA.5.1*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

**Comment by corneliusroemer** [comment]
Come on, you just designated this so you could get issue 1000 😛  🎉

**Comment by FedeGueli** [comment]
ahaha @corneliusroemer ;)

**Comment by FedeGueli** [comment]
10 more sequences uploaded in the last 3 days:  2 from Belgium,2 from Portugal , 4 from Usa , 1 from Germany and Canada


EPI_ISL_14684769
EPI_ISL_14696902
EPI_ISL_14699282 & EPI_ISL_14699335 from Portugal share N:R413L
EPI_ISL_14713656
EPI_ISL_14713668
EPI_ISL_14723046
EPI_ISL_14723056 ( from Belgium with two additional S2 mutations:S:765C and S:902I)
EPI_ISL_14734270

**Comment by FedeGueli** [comment]
3 more sequences ( 1 from France , 2 from Canada)

**Comment by FedeGueli** [comment]
2 more sequences: 1 from  California, Usa (with additional S:Spike G1124V) and 1 from  Denmark

**Comment by FedeGueli** [comment]
3 more sequences one from NYC the other to from Washington, Usa

**Comment by corneliusroemer** [comment]
Given the relevant S:346T mutation and continued growth I do think this is worth designating now.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.1.20 with 30 newly designated sequences, and 3 updated designations from BA.5.1. Defining mutation G22599C (S:R346T) (which follows A4485T (ORF1a:K1407M)).
