### ISSUE TITLE
BA.5.2 sublineage with Orf1a:T2152I, S:W64L, S:K444M (29 sequences Denmark, Pakistan, Canada, New Zealand, Germany,Netherlands,Uk, Portugal,Switzerland)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1002]
Here i want to propose a sublineage of BA.5.2, just twelve sequences (but from 4 continents) carrying three mutations ( 2 in the Spike protein) known to confer some growth advantage i think it is better to be monitored publicly.

Lineage: BA.5.2 + 12310A + Orf1b:T1050N + C27513T + C27012T + T16617C + G29422T +Orf1a:T2152I (C6720T), S:W64L (G21753T), S:K444M (A22893T) 

It Likely emerged in Pakistan and this could be confirmed by a sequence uploaded today  from Pakistan (EPI_ISL_14683901) collected on 12/082022:
![Schermata 2022-08-28 alle 16 30 50](https://user-images.githubusercontent.com/87669813/187079219-64fd818a-b3a6-4319-804b-0366907c2a71.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a9e9_b77060.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C6720T,G21753T,A22893T,G29422T

Nr of sequences : 12 with Gisaid query (NSP3_T1334I,Spike_K444M,Spike_W64L)
Country: Pakistan, Denmark , Canada , New Zealand
Covspectrum query :10 Sequences
 https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AW64L%2CS%3A444M%2COrf1b%3A1050N%2COrf1a%3AT2152I&nextcladePangoLineage=BA.5.2*

List of sequences:
EPI_ISL_14152149
EPI_ISL_14152150
EPI_ISL_14162362
EPI_ISL_14391178
EPI_ISL_14392990
EPI_ISL_14393113
EPI_ISL_14433044
EPI_ISL_14602418
EPI_ISL_14613173
EPI_ISL_14619689
EPI_ISL_14635117
EPI_ISL_14683901

**Comment by FedeGueli** [comment]
One more sequence from Germany (a bronchoalveolar fluid lavage sample ): EPI_ISL_14696982

**Comment by FedeGueli** [comment]
Two new sequences from Canada : 

EPI_ISL_14714210
EPI_ISL_14714018

with collection between 15 and 19 of August.

**Comment by FedeGueli** [comment]
One more sequence one more country : Netherlands . 

EPI_ISL_14717141

**Comment by FedeGueli** [comment]
Two new sequences very recently collected 
in Denmark 
EPI_ISL_14772717 
2022-08-25
and Pakistan:
EPI_ISL_14774620 
2022-08-27
this last one from Pakistan has an additional spike mutation S:N188Y

**Comment by corneliusroemer** [comment]
Clear epi link and growth - should be designated. Thanks @FedeGueli.

@InfrPopGen @aq-sun

**Comment by FedeGueli** [comment]
Wait @corneliusroemer i am not sure this is a sublineage of BA.5.2.7 : 
the 16 sequences of this lineage on covspectrum have  G21753T, C6720T, G29422T, T16617C mutations not shared with  BA.5.2.7
![Schermata 2022-09-02 alle 23 25 04](https://user-images.githubusercontent.com/87669813/188237388-49d1b3ac-de52-4fae-9b3c-99d67ee284ed.png)

and they are missing : C17958T,T2058C that is present in 100% of BA.5.2.7 outside this lineage proposed here.
![Schermata 2022-09-02 alle 23 24 40](https://user-images.githubusercontent.com/87669813/188237355-d4a722d9-3d90-40ae-b8d5-756bda9096fb.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BA.5.2.7*&aaMutations1=Orf1b%3A1050N%2COrf1a%3AT2152I%2CS%3A444M&nextcladePangoLineage1=BA.5.2*&analysisMode=CompareEquals&

In fact Usher doesnt put it in BA.5.2.7 and that is supported from what showed above (@AngieHinrichs )
![Schermata 2022-09-02 alle 23 27 44](https://user-images.githubusercontent.com/87669813/188237624-619a2fa2-c5db-4584-b5cf-ed03702f6175.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_deb1_2737d0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T16617C

A28330G > C1627T > G12310A > C16616A > C27513T > C27012T > T16617C > C6720T, G21753T, A22893T, G29422T

**Comment by FedeGueli** [comment]
More Cornelius there are zero sequence of this sublineage with 17958T defining of BA.5.2.7: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_deb1_2737d0.json?branchLabel=aa%20mutations&c=gt-nuc_17958&label=nuc%20mutations:T16617C

and 0 BA.5.2.7 with T16617C  or G29422T

**Comment by AngieHinrichs** [comment]
Right @FedeGueli, BA.5.2.7 also has C17958T and T2058C (ORF1a:M598T) which these sequences do not have.  Unlike BA.5.2.7, these sequences have T16617C, C6720T (ORF1a:T2152I), G21753T (S:W64L), and G29422T.  I will change the title, thanks for pointing that out.

**Comment by FedeGueli** [comment]
Thanks very much @AngieHinrichs .

cc @corneliusroemer

**Comment by FedeGueli** [comment]
One moer sequence from England uploaded today to GISAID: EPI_ISL_14804489 collected on 
2022-08-22

**Comment by FedeGueli** [comment]
One more sequence from Denmark collected on 27/08/2022 : EPI_ISL_14809988

I would highlight you to check : https://cov-spectrum.org/collections/23  it seems to have an important growth advantage, while too early to say, always good to be aware of this kind of advantages.

**Comment by FedeGueli** [comment]
Another one and from a new country Portugal: EPI_ISL_14813123 collected on 19/08/22

**Comment by FedeGueli** [comment]
One more sequence from Scotland : EPI_ISL_14819243 collected on 25/08/2022

**Comment by FedeGueli** [comment]
One more sequence from Virginia EPI_ISL_14834782 collected on 23/08/22

**Comment by FedeGueli** [comment]
3 more sequences from Ontario,Canada collected between 29-30 August

**Comment by FedeGueli** [comment]
2 more sequences from Japanese airport surveillance related with travel from  Switzerland.

**Comment by corneliusroemer** [comment]
Thanks @AngieHinrichs @FedeGueli 
I checked and noticed that what caused me to err here was that there are more than 10% of sequences reverted at both positions you call defining for BA.5.2.7 - so we should remove these sequences if these are supposed to be defining.

As a result Nextclade decided, based on designated sequences, that only S:444M was defining.

But I can see that it appears that this proposed lineage and BA.5.2.7 seem to have acquired S:444M independently.

I know that having some reverted sequences helps pangoLEARN - but there's a limit to what is acceptable and we should make sure that not more than 10% have reversions, otherwise what is defining becomes murky.

This one can be designated - as BA.5.2.X.

**Comment by FedeGueli** [comment]
Thx @corneliusroemer , should i prepare a new list without reversions?

**Comment by FedeGueli** [comment]
One more sequence from Scotland: EPI_ISL_14859047

**Comment by FedeGueli** [comment]
@corneliusroemer this list that i checked on Nextclade should contain just samples with all  defining AA and Nucleotides mutations:

EPI_ISL_14152149
EPI_ISL_14152150
EPI_ISL_14162362
EPI_ISL_14391178
EPI_ISL_14392990
EPI_ISL_14393113
EPI_ISL_14433044
EPI_ISL_14602418
EPI_ISL_14613173
EPI_ISL_14619689
EPI_ISL_14635117
EPI_ISL_14683901
EPI_ISL_14696982
EPI_ISL_14714018
EPI_ISL_14714210
EPI_ISL_14717141
EPI_ISL_14772717
EPI_ISL_14774620
EPI_ISL_14804489
EPI_ISL_14809988
EPI_ISL_14813123
EPI_ISL_14819243
EPI_ISL_14834782
EPI_ISL_14843220
EPI_ISL_14843418
EPI_ISL_14844464
EPI_ISL_14853756
EPI_ISL_14853757
EPI_ISL_14859047


I could be wrong , in the case excuse me it was an attempt to help.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.14 with 9 newly designated sequences, and 0 updated designations. Defining mutation A22893T (S:K444M) (following G21753T (S:W64L)).
