### ISSUE TITLE
BA.2.75 sublineage with S:P272L, S:A348S, ORF1a:R1386C (2 seq. Israel)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1003]
Proposal for a sublineage of BA.2.75
Earliest sequence: 20.08.2022 (Israel)
Countries detected: Israel

Defining mutation:
C22377T = S:P272L
G22604T = S:A348S
C4421T = ORF1a:R1386C
C26028T

GISAID query: Spike_P272L, Spike_A348S, Spike_W152R

This subvariant is defined by S:P272L, S:A348S, ORF1a:R1386C and was first detected in Israel. 

Site 348 is one of the major sites according the Bloom Lab Escape calculator (https://jbloomlab.github.io/SARS2_RBD_Ab_escape_maps/escape-calc/). Apparently we havent seen BA.2.75 with a 348 mutation yet. 

![grafik](https://user-images.githubusercontent.com/102166254/187141215-3807ebd9-2a9a-4655-8f5e-412d761cddbe.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f698_c5c090.json?branchLabel=aa%20mutations&c=pango_lineage_usher

![grafik](https://user-images.githubusercontent.com/102166254/187141624-ae43b7da-798b-4c64-9896-0cce9660d380.png)

Covspectrum:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AP272L%2CS%3AA348S%2CORF1a%3AR1386C&pangoLineage=BA.2.75*&aaMutations1=ORF3a%3A78Y&nucMutations1=C22792T&pangoLineage1=BA.2&

EPI_ISL_14687299
EPI_ISL_14687291

**Comment by c19850727** [comment]
Came across this duo earlier today.

Also interesting is that Spike P272L according to this study is a T-cell escaping substitution:
https://doi.org/10.1016/j.cell.2022.07.002

![image](https://user-images.githubusercontent.com/86835836/187158422-ed87ea8c-f742-45ef-8943-e86191db6c90.png)

**Comment by chrisruis** [comment]
We need new issues to either have an epidemiological event or be close to exhibiting an epidemiological event before opening. Will therefore close this one for now
