### ISSUE TITLE
BA.5.5 with ORF1a:A903V and ORF1b:V666I [174 seq as of 2022-08-29, mostly North America]

### ISSUE THREAD

**Issue by ndkling** [cov-lineages/pango-designation#1005]
Proposal for a sublineage of BA.5.5
Earliest sequence: 2022-05-29 (United States, EPI_ISL_13436059)
Countries detected: Mostly USA and Canada, but also Europe, Oceania, and Mexico

I have something of an obsession with nsp12-14 as they're highly conserved and nsp12 is a common anti-viral target, so forgive me.  I'll only open issues with a meaningful growth advantage, broad geographic distribution, and a significant number of isolates.

ORF1a:A903V appears to have come first and done fairly well, followed by C28333T, followed by ORF1b:V666I, the branch from C28333T with the most descendants.  ORF1b:V666I, in RdRp, is significantly rarer, only appearing in 2 quality sequences in BA.5.5 without ORF1a:A903V.  It's present in fewer sequences of any other Omicron-derived variant.  Interestingly, the tandem has made a cluster.

The homoplasic C2973T and C5512T are also on the branch from C28333T.  All are synonymous changes, including for ORF9b.

Slow starter, but its growth rate appears to have accelerated during the last two months.  We'll see if it keeps up.

Genomes:

[A903V+V5067I.csv](https://github.com/cov-lineages/pango-designation/files/9448940/A903V%2BV5067I.csv)

obtained through covSPECTRUM with the following query:

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=orf1b%3A666i%2Corf1a%3A903v&nextcladePangoLineage=ba.5.5*&nextcladeQcOverallScoreTo=29&

Evidence:

Clusters very cleanly with all samples being called as BA.5.5 by UShER.

![A903V+V5067I](https://user-images.githubusercontent.com/82973333/187330645-94ef20ec-d63e-43fc-b0c4-1fa5c59642e6.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_14922_d50f70.json?branchLabel=aa%20mutations&label=nuc%20mutations:C21789T

A moderate 3-month growth advantage is exhibited over background:

![vsBackground](https://user-images.githubusercontent.com/82973333/187331927-951fa0ac-f455-4035-86ef-658d1158a250.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladeQcOverallScoreTo=29&aaMutations=orf1b%3A666i%2Corf1a%3A903v&nextcladePangoLineage=BA.5.5

with a marginally smaller advantage over BA.5.5:

![vsBA 5 5](https://user-images.githubusercontent.com/82973333/187332188-6e194ad3-5467-4562-9c58-e8748af820c7.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=BA.5.5&aaMutations1=orf1b%3A666i%2Corf1a%3A903v&nextcladePangoLineage1=ba.5.5*&analysisMode=CompareToBaseline&nextcladeQcOverallScoreTo=29&

Thank you for the warm welcome, everyone!

**Comment by ndkling** [comment]
(As an aside, I don't know whether BA.5.5 + ORF1a:A903V should have been designated independently at some point, making this a sublineage.  It had a very good summer in the USA, reaching 10.7% representation, and 4.4% globally.  It's rebounding now with ORF1b:V666I.)

https://cov-spectrum.org/explore/United%20States/AllSamples/Past6M/variants?nextcladeQcOverallScoreTo=29&aaMutations=orf1a%3A903a&nextcladePangoLineage=BA.5.5*&

**Comment by ndkling** [comment]
190 good-quality sequences as of 2022-09-03.  The growth advantage over BA.5.5 has nudged down to 19%.

**Comment by corneliusroemer** [comment]
Growth advantage should rarely be based on world query - but be done in the country where there are the largest number of sequences to combat differences in upload speed.

Here's for US:
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/25161793/188325496-73b61e30-a776-4466-a778-50746d26060b.png">
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?nextcladeQcOverallScoreTo=29&nextcladePangoLineage=ba.5.5*&aaMutations1=orf1b%3A666i%2Corf1a%3A903v&nextcladePangoLineage1=ba.5.5*&analysisMode=CompareToBaseline&

**Comment by ndkling** [comment]
Thank you so much for the tip and your time. I'll do that in all future proposals. Should I also use only good+ quality sequences? @FedeGueli suggested that it's appropriate to use all sequences for growth advantage determination and good+ for tree building.

For posterity, the USA growth advantage on 2022-09-04 using Cornelius' query is 17% (CI 10-24%).

**Comment by corneliusroemer** [comment]
Not big anywhere - it's in well sampled areas.

So I think it's better to close for now. We can reopen if something happens.

![Uploading image.png…]()
