### ISSUE TITLE
Potential BA.5*/BA.2*/BA.5.1* recombinant (90 sequences as of 2022-08-29, mainly UK)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1006]
### Description
**Recombinant between**: BA.5*/BA.2*/BA.5.1*
**Earliest sequence**: 2022/05/23 (UK-England)
**Most recent sequence**: 2022/07/26 (UK-England)
**Countries circulating**: 
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/itine/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/itine/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">

Country | Count
-- | --
United Kingdom | 81
Israel | 2
United States | 2
France | 1
Netherlands | 1
Portugal | 1
Spain | 1
Sweden | 1

</body>

</html>

**Likely breakpoint 1**: between 26532 and 27381
**Likely breakpoint 2**: between 27810 and 29665
**Mutations on branch**: G28028A (ORF8:W45stop)
**Mutations from potential BA.2 donor**: GAT27382CTC (ORF6:D61L), T27889C (reversion from BA.5)
**Mutations from potential BA.5 donor (as distinguished from BA.4)**:  G26529A (M:D3N), C29666T
**Cov-spectrum query**: A27383T, T27384C, C27807T, G26529A, C29666T, G28028A, T27889C

Nuc mutations (those in red frames are likely from BA.2*):
![image](https://user-images.githubusercontent.com/86835836/187408854-0d8b3f51-9f90-499f-b80e-93e91a608707.png)

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/187409337-4cf0e84b-267e-46e1-9682-d521a2d92f7c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28dda_dd62c0.json?branchLabel=aa%20mutations&c=gt-nuc_11522,28028,27879,6843&label=nuc%20mutations:T26858C

### Genomes:
[genomes.csv](https://github.com/cov-lineages/pango-designation/files/9451877/genomes.csv)

**Comment by corneliusroemer** [comment]
Good spot - but kind of dead now.
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/25161793/190932572-aa9e0327-bedc-4d1f-b0d0-6658f738fc9d.png">

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there have been no new sequences recorded over the past 3M, and there was no major epidemiological event associated with this clade, the proposal can be closed for now. Should the lineage reappear and show relevant characteristics again, then please feel free to reopen or to create a new issue.
