### ISSUE TITLE
BA.2.75.2 with S:E1150Q [4 seq, 2x JP, 1x SGP, 1x IL as of 2022-08-30]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1007]
BA.2.75.2 seems to be growing fast. There's a recent sublineage of interest with extra S2 mutation S:E1150Q that has been found in 3 different countries in 4 uploads since 2022-08-26.

The Japanese sequences are in travellers from India, the Singaporean is a local case.

hCoV-19/Japan/IC-13723/2022|EPI_ISL_14721368|2022-08-17
hCoV-19/Japan/IC-13724/2022|EPI_ISL_14721369|2022-08-17
hCoV-19/Israel/SMC-7100104/2022|EPI_ISL_14686537|2022-08-15
hCoV-19/Singapore/10506/2022|EPI_ISL_14649920|2022-08-19

The mutation seems to be straight on top of the BA.2.75.2 polytomy.

**Comment by chrisruis** [comment]
We need new issues to either have an epidemiological event or be close to exhibiting an epidemiological event before opening. Will therefore close this one for now

**Comment by corneliusroemer** [comment]
New sequence from Karnataka
hCoV-19/India/KA-RFNB-16717/2022
