### ISSUE TITLE
Sublineage of BA.2.3 with S:69-70del, S:R346T, S:R403K, S:L452M, S:A570V, S:Q672E, S:A852V, M:S4F, ORF8:A65V, ORF1a:E2089D, ORF1a:E3310Q, and ORF1a:T4311I (5 seq on Aug 30)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1009]
### **Description**
**Sub-lineage of:** BA.2.3
**Earliest sequence:** 2022-8-4, Australia, South Australia — EPI_ISL_14577670
**Most recent sequence:** 2022-8-17, Australia, South Australia — EPI_ISL_14723238
**Countries Sequenced In:** Australia (4 sequences), South Korea (1 imported case from USA)
**Number of Sequences:** 5
**Substitutions on top of BA.2.3:**
**Spike:** R346T, R403K, L452M, A570V, Q672E, A852V
**M**: S4F
**ORF8:** A65V
**ORF1a:** E2089D, E3310Q, T4311I
**Nucleotide:** G6532T, G10193C, C13197T, T15382C, G22599C, G22770A, C22916A, C23271T, C23846G, C24117T, C26533T, C28087T

**USHER Tree**
The tree is a little messed up because one sequence lacked coverage at spike 672 and Usher therefore assumes the mutation is absent but that it developed twice independently in the two other branches. Obviously, it is far more likely that they all inherited S:Q672E. 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_89d6_e3a9f0%E2%80%94BA.2.3%2B.json 
![Screen Shot 2022-08-30 at 5 44 59 PM—USHERTREE](https://user-images.githubusercontent.com/33738461/187549718-c7729dca-22c2-45f4-9882-ba0e32e55baf.png)

**Evidence**
The fact that this microlineage has been found in South Korea in a traveler from the USA and has now been detected four times in South Australia seems to indicate that it is fairly geographically widespread. All of the spike mutations—with the possible exception of the rare mutation Q762E, which involves the rarest of nucleotide mutations, C>G, which makes up only ~0.4% of all nuc mutations—are convergent and have been seen in previous variants of interest. The same can be said for M:S4F and ORF1a:T4311I. The combination of geographic spread, convergent mutations, and a large saltation make this lineage one of interest. 

The substantial genetic distance between these five sequences, with two distinct branches, also suggests this lineage is present in greater numbers either in an area with very little sequencing or one with a substantial delay between sequencing and uploading to GISAID. One sequence has S:K147E, also found in BA.2.75, while another has S:E1202Q, also found in BA.2.43, BA.2.54, and B.1.1.318.  

**Genomes**
EPI_ISL_14577670
EPI_ISL_14577685
EPI_ISL_14663097
EPI_ISL_14723211
EPI_ISL_14723238

**Comment by FedeGueli** [comment]
Potential Gisaid query : Spike_A852V, M_S4F

**Comment by corneliusroemer** [comment]
There seem to be 2 more of these. Given the spike profile and international spread I think it's good to designate this, just like BA.2.3.21 - it will help get it into pangoLEARN/Usher/Nextclade more quickly. No big harm done if it doesn't become huge.

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/25161793/188183904-e8b9dadd-394b-4d28-8a71-de3460b517a5.png">

Thanks for the query @FedeGueli very helpful.

Singapore reported first case with travel history Philippines.

Now we also have a New South Wales case, in contrast to the South Australia before.

**Comment by corneliusroemer** [comment]
Running them through the latest Nextclade, I noticed that this is actually a BA.2.3.16 sublineage.

BA.2.3.16 was dominant in Papua New Guinea in the latest data from there (a couple of months ago).

So the possible regions of origin could be wide, somewhere in South East Asia/Oceania.

**Comment by corneliusroemer** [comment]
Closed in [a64e9bc](https://github.com/cov-lineages/pango-designation/commit/a64e9bcac07967ff3b0e1dadde2c4c1af852f163)

Designated as BP.1 = BA.2.3.16.1

**Comment by shay671** [comment]
Hi @corneliusroemer 

I see 9 other BA.2.3.16 samples also have C26681T found in this one (synonymous mutation) from Australia, 03-05/2022.  But, they do not cluster in Usher with this one.  

EPI_ISL_12846561
EPI_ISL_12114627
EPI_ISL_12112530
EPI_ISL_11362191
EPI_ISL_12645123
EPI_ISL_12277098
EPI_ISL_12849508
EPI_ISL_12114208
EPI_ISL_12275693

**Comment by shay671** [comment]
Two samples were uploaded :
EPI_ISL_14788980
EPI_ISL_14785646

From Singapore and Australia. 
And so we are in 3 countries already (there is also South Korea). 

If this is a lineage evolved from a specific australAustralian and not an unknown country, it is probably a very new variant. 

Usher build
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_203ff_60aa50.json?c=pango_lineage_usher&label=nuc%20mutations:C26533T

**Comment by FedeGueli** [comment]
One more from NSW Australia: EPI_ISL_14912863 collected on 15/08/2022
