### ISSUE TITLE
New lineage proposal of B.1.617.4

### ISSUE THREAD

**Issue by 08011990** [cov-lineages/pango-designation#101]
Submitted by Rakesh Sarkar (Senior Research Fellow, Division of Virology, ICMR-NICED, Kolkata, West Bengal, India) and Dr. Mamta Chawla-Sarkar (Scientist F, Division of Virology, ICMR-NICED)
Description:
Sub-lineage of B.1.617
Earlier sequence: EPI_ISL_1415164, 13th February 2021
Most recent: EPI_ISL_1415358, 16th February 2021
Country circulation: India (State: Maharashtra)
Characteristic: We identified 13 sequences which are characterized by the presence of 38 coexisting mutations. Mutations are as follows
NSP3: A1526V, T1830I
NSP5: A194S
NSP6: A117V
NSP12: P323L
S glycoprotein: E156G, F157del, R158del, L452R, E484Q, D614G, P681R
NS3: E19G, I20S, K21R, D22Y, A23C, T24N, P25D, S26T, ΔF28, ΔV29, ΔR30, ΔA31, ΔT32, ΔA33, ΔT34, ΔI35, ΔP36, ΔI37, ΔQ38, A39T, ins41T
NS7a: V82A
NS8: T26I
N: P67S, R203M, D377Y

Genomes accession number:
[Sequence file.docx](https://github.com/cov-lineages/pango-designation/files/6585281/Sequence.file.docx)
Though these sequences have been classified as B.1.617.3 by GISAID. We think these sequence should be classified as different lineage.

Phylogenetic analysis by Nextstrain:

![Tree](https://user-images.githubusercontent.com/84579950/120501121-fb3a7380-c3de-11eb-9f7a-166b7eb11e64.jpg)

Proposed lineage name: B.617.4

**Comment by AngieHinrichs** [comment]
@08011990 that group of sequences does not appear to be monophyletic, which is an important requirement for a new lineage.  The requirements for a new lineage are now documented in detail here: https://pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/
