### ISSUE TITLE
Proposal for BA.5.2.1 sublineage with N:T49I and N:T379I in Japan (429 seqs. as of 2022/08/31)

### ISSUE THREAD

**Issue by takaabe8050** [cov-lineages/pango-designation#1010]
By Japan COVID-19 Open Data Consortium

Description
Sub-lineage of: BA.5.2.1 (429 sequences)
Earliest sequence: 2022/06/22 (Japan/TKYnat3293/2022, EPI_ISL_14044264)
Most recent sequence: 2022/08/20 (Japan/OPHO-M517/2022, EPI_ISL_14615611)
Countries circulating: Japan (428 sequences), Singapore (1)

Associated mutations
C28419T (N:T49I)
C29409T (N:T379I)
A3859G (synonymous, ORF1ab:1198)
A9343G (synonymous, ORF1ab:3026)
T23269C (synonymous, S:569)

Genomes
[GenomeID.txt](https://github.com/cov-lineages/pango-designation/files/9458283/GenomeID.txt)

Evidence
UShER tree

![UShER_Tree](https://user-images.githubusercontent.com/89957075/187589621-d5b34267-7d96-4608-bf18-4ae7ce840fad.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_29a2c_ea29d0.json?c=userOrOld

Relative growth advantage
![RGA](https://user-images.githubusercontent.com/89957075/187589649-4dbf9b33-431d-453d-b0d5-6d406fa09869.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C28419T%2CC29409T&nextcladePangoLineage=BA.5.2.1*&

Proposed lineage name
Next BA.5.2.1.X (BF.X)

**Comment by corneliusroemer** [comment]
Thanks! They make up about 5-10% of BA.5.2.1 in Japan - but no growth advantage

Could still be worth designating - I guess it qualifies under the epidemiological event rule

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/25161793/187680553-ea5b379f-e8b5-4f73-9b69-52b2670eff6b.png">

**Comment by aq-sun** [comment]
Thanks @takaabe8050, as this fits our criteria for an epidemiological event, we have designated it as BF.22, with 60 new designations and 3 updated from BA.5.2.1. Defining mutation: C29409T (N:T379I)
