### ISSUE TITLE
BA.2 sublineage with S:F486I, ORF3a:H78Y (24 seq. as of 31.08.22; mostly Japan, Croatia)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1011]
Proposal for a sublineage of BA.2
Earliest sequence: 06.07.2022 (Japan)
Countries detected: Japan (23), Croatia (1)

Defining mutation:

T23018A = S:F486I
C25624T = ORF3a:H78Y
C9943T
C25614T
C27513T

GISAID query: NS3_H78Y, Spike_F486I

![grafik](https://user-images.githubusercontent.com/102166254/187647043-59adb286-1035-411c-9e1c-6fd01bd25a9b.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1db62_f246f0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C27513T

![grafik](https://user-images.githubusercontent.com/102166254/187645682-4354ac1b-01ce-4e40-a449-b5041f1cd820.png)

![grafik](https://user-images.githubusercontent.com/102166254/187647550-713a5025-bcfc-45b8-8173-1c7135f78b54.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF3a%3AH78Y%2CS%3AF486I&nucMutations=C9943T%2CC25614T%2CC27513T&pangoLineage=BA.2*&aaMutations1=ORF3a%3AH78Y%2CS%3AF486I&nucMutations1=C9943T%2CC25614T%2CC27513T&pangoLineage1=BA.2&

Growth advantage vs. BA.5 6months Japan:
![grafik](https://user-images.githubusercontent.com/102166254/187647274-639bd57d-c613-4992-a915-62ce48bd266e.png)

EPI_ISL_14589691
EPI_ISL_14347305
EPI_ISL_14720741
EPI_ISL_14720900
EPI_ISL_14724652
EPI_ISL_14732544
EPI_ISL_14748627
EPI_ISL_14639136
EPI_ISL_14549487
EPI_ISL_14520268
EPI_ISL_14519614
EPI_ISL_14508754
EPI_ISL_14347486
EPI_ISL_14352507
EPI_ISL_14353225
EPI_ISL_14733583
EPI_ISL_14644500
EPI_ISL_14644499
EPI_ISL_14643311
EPI_ISL_14351187
EPI_ISL_14259765
EPI_ISL_14644828
EPI_ISL_14644829

**Comment by FedeGueli** [comment]
Having C1627T and missing 9866T i suspect this is a recombinant between BA.5/BA.2

**Comment by FedeGueli** [comment]
@c19850727 @josetteshoenma i think this is a plain BA.5 / BA.2 recombinant or somewhere between 12160 and 23018 (spike 486 but we have already seen BA.5s with 486I so it could come from BA.5 too) or somewhere between 23018 and 25416.

Having C1627 and being designated a sublineage of BA.5.2.1 BF.12 defined by  S:486I i think the recombination is :

BF.12/ BA.2.9

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF3a%3AH78Y%2CS%3AF486I&nucMutations=C9943T%2CC25614T%2CC27513T&nextcladePangoLineage1=BF.12*&analysisMode=CompareEquals&

This lineage not shared with BF.12 mutations
![Schermata 2022-08-31 alle 18 05 59](https://user-images.githubusercontent.com/87669813/187725888-bca3ead0-4305-4c78-9616-5525bc39ab58.png)

BF.12 not shared mutations: 
![Schermata 2022-08-31 alle 18 06 40](https://user-images.githubusercontent.com/87669813/187726038-8cecf05d-183c-484b-803b-11726011634e.png)

Shared mutations between this lineage and BF.12
![Schermata 2022-08-31 alle 18 07 32](https://user-images.githubusercontent.com/87669813/187726220-494def2a-157a-45c0-94d7-027c55ae86fb.png)

**Comment by FedeGueli** [comment]
Alternatively it could be from a BA.5.2* sublineage that had C9943T and there are 200sequence:

![Schermata 2022-08-31 alle 18 14 14](https://user-images.githubusercontent.com/87669813/187727837-fa6abe89-25ba-47c0-b762-5c576e0de428.png)

if so the breakpoint should be between 12160 and 23012 if we would attribute S:486I to the BA.2.9 part or 
between 12160 and 25416 if we think S:486I was from an unsampled BA.5.2+C9943T sublineage or that it was gained after the recombination event.

**Comment by agamedilab** [comment]
@FedeGueli nice spot! F486I, ORF3a:H78Y reminded me also of BF.12 and BA.2.9 respectively, however i thought it is convergence or coincidence. A test for recombination would be interesting.

**Comment by corneliusroemer** [comment]
Small and dead - so I'll close, thanks nonetheless!

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF3a%3AH78Y%2CS%3AF486I&nucMutations=C9943T%2CC25614T%2CC27513T&pangoLineage=BA.2*&aaMutations1=ORF3a%3AH78Y%2CS%3AF486I&nucMutations1=C9943T%2CC25614T%2CC27513T&pangoLineage1=BA.2&
