### ISSUE TITLE
BA.5.2 + Orf1b:T1050N defined by Orf1b:A1369T with high prevalence in Russia -  259 out of 264 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1012]
Here i want to propose a sublineage of BA.5.2 circulating in Russia  defined by Orf1b:T1050N and Orf1b:A1369T

It has to be noted that this lineage represents 253 out of 1262 samples collected in Russia during last month, so it is very close to 20% of prevalence there.

Gisaid query : M_D3N, NSP13_A446T, NSP13_T127N

First sequence: 
hCoV-19/South Africa/CERI-KRISP-K042178/2022
EPI_ISL_12845553 collected on 3th of May 2022
Nr of sequences : 264
List of sequences :
EPI_ISL_12845553
EPI_ISL_12845554
EPI_ISL_12845555
EPI_ISL_12845556
EPI_ISL_12845557
EPI_ISL_12845558
EPI_ISL_12845559
EPI_ISL_12845560
EPI_ISL_12845561
EPI_ISL_12845562
EPI_ISL_12845563
EPI_ISL_12845564
EPI_ISL_12845565
EPI_ISL_12845566
EPI_ISL_12845567
EPI_ISL_12845568
EPI_ISL_12845569
EPI_ISL_12845570
EPI_ISL_12845571
EPI_ISL_12845572
EPI_ISL_12845573
EPI_ISL_12845574
EPI_ISL_12845575
EPI_ISL_12845576
EPI_ISL_12845577
EPI_ISL_12845578
EPI_ISL_12845579
EPI_ISL_12845580
EPI_ISL_12845581
EPI_ISL_12845582
EPI_ISL_12845583
EPI_ISL_12845584
EPI_ISL_12845585
EPI_ISL_12845586
EPI_ISL_12845587
EPI_ISL_12845588
EPI_ISL_12845589
EPI_ISL_12845590
EPI_ISL_12845591
EPI_ISL_12845592
EPI_ISL_12845593
EPI_ISL_12845594
EPI_ISL_12845595
EPI_ISL_12845596
EPI_ISL_12845597
EPI_ISL_12845598
EPI_ISL_12845599
EPI_ISL_12845600
EPI_ISL_12845601
EPI_ISL_12845602
EPI_ISL_12845603
EPI_ISL_12845604
EPI_ISL_12845605
EPI_ISL_12845606
EPI_ISL_12845607
EPI_ISL_12845608
EPI_ISL_12845609
EPI_ISL_12845610
EPI_ISL_12845611
EPI_ISL_12845612
EPI_ISL_12845613
EPI_ISL_12845614
EPI_ISL_12845615
EPI_ISL_12845616
EPI_ISL_12845617
EPI_ISL_12845618
EPI_ISL_12845619
EPI_ISL_12845620
EPI_ISL_12845621
EPI_ISL_12845622
EPI_ISL_12845623
EPI_ISL_12845624
EPI_ISL_12845625
EPI_ISL_12845626
EPI_ISL_12845627
EPI_ISL_12845628
EPI_ISL_12845629
EPI_ISL_12845630
EPI_ISL_12845631
EPI_ISL_12845632
EPI_ISL_12845633
EPI_ISL_12845634
EPI_ISL_12845635
EPI_ISL_12845636
EPI_ISL_12845637
EPI_ISL_12845638
EPI_ISL_12845639
EPI_ISL_12845640
EPI_ISL_12845641
EPI_ISL_12845642
EPI_ISL_12845643
EPI_ISL_12845644
EPI_ISL_12845645
EPI_ISL_12845646
EPI_ISL_12845647
EPI_ISL_12845648
EPI_ISL_12845649
EPI_ISL_12845650
EPI_ISL_12845651
EPI_ISL_12845652
EPI_ISL_12845653
EPI_ISL_12845654
EPI_ISL_12845655
EPI_ISL_12845656
EPI_ISL_12845657
EPI_ISL_12845658
EPI_ISL_12845659
EPI_ISL_12845660
EPI_ISL_12845661
EPI_ISL_12845662
EPI_ISL_12845663
EPI_ISL_12845664
EPI_ISL_12845665
EPI_ISL_12845666
EPI_ISL_12845667
EPI_ISL_12845668
EPI_ISL_12845669
EPI_ISL_12845670
EPI_ISL_12845671
EPI_ISL_12845672
EPI_ISL_12845673
EPI_ISL_12845674
EPI_ISL_12845675
EPI_ISL_12845676
EPI_ISL_12845677
EPI_ISL_12845678
EPI_ISL_12845679
EPI_ISL_12845680
EPI_ISL_12845681
EPI_ISL_12845682
EPI_ISL_12845683
EPI_ISL_12845684
EPI_ISL_12845685
EPI_ISL_12845686
EPI_ISL_12845687
EPI_ISL_12845688
EPI_ISL_12845689
EPI_ISL_12845690
EPI_ISL_12845691
EPI_ISL_12845692
EPI_ISL_12845693
EPI_ISL_12845694
EPI_ISL_12845695
EPI_ISL_12845696
EPI_ISL_12845697
EPI_ISL_12845698
EPI_ISL_12845699
EPI_ISL_12845700
EPI_ISL_12845701
EPI_ISL_12845702
EPI_ISL_12845703
EPI_ISL_12845704
EPI_ISL_12845705
EPI_ISL_12845706
EPI_ISL_12845707
EPI_ISL_12845708
EPI_ISL_12845709
EPI_ISL_12845710
EPI_ISL_12845711
EPI_ISL_12845712
EPI_ISL_12845713
EPI_ISL_12845714
EPI_ISL_12845715
EPI_ISL_12845716
EPI_ISL_12845717
EPI_ISL_12845718
EPI_ISL_12845719
EPI_ISL_12845720
EPI_ISL_12845721
EPI_ISL_12845722
EPI_ISL_12845723
EPI_ISL_12845724
EPI_ISL_12845725
EPI_ISL_12845726
EPI_ISL_12845727
EPI_ISL_12845728
EPI_ISL_12845729
EPI_ISL_12845730
EPI_ISL_12845731
EPI_ISL_12845732
EPI_ISL_12845733
EPI_ISL_12845734
EPI_ISL_12845735
EPI_ISL_12845736
EPI_ISL_12845737
EPI_ISL_12845738
EPI_ISL_12845739
EPI_ISL_12845740
EPI_ISL_12845741
EPI_ISL_12845742
EPI_ISL_12845743
EPI_ISL_12845744
EPI_ISL_12845745
EPI_ISL_12845746
EPI_ISL_12845747
EPI_ISL_12845748
EPI_ISL_12845749
EPI_ISL_12845750
EPI_ISL_12845751
EPI_ISL_12845752
EPI_ISL_12845753
EPI_ISL_12845754
EPI_ISL_12845755
EPI_ISL_12845756
EPI_ISL_12845757
EPI_ISL_12845758
EPI_ISL_12845759
EPI_ISL_12845760
EPI_ISL_12845761
EPI_ISL_12845762
EPI_ISL_12845763
EPI_ISL_12845764
EPI_ISL_12845765
EPI_ISL_12845766
EPI_ISL_12845767
EPI_ISL_12845768
EPI_ISL_12845769
EPI_ISL_12845770
EPI_ISL_12845771
EPI_ISL_12845772
EPI_ISL_12845773
EPI_ISL_12845774
EPI_ISL_12845775
EPI_ISL_12845776
EPI_ISL_12845777
EPI_ISL_12845778
EPI_ISL_12845779
EPI_ISL_12845780
EPI_ISL_12845781
EPI_ISL_12845782
EPI_ISL_12845783
EPI_ISL_12845784
EPI_ISL_12845785
EPI_ISL_12845786
EPI_ISL_12845787
EPI_ISL_12845788
EPI_ISL_12845789
EPI_ISL_12845790
EPI_ISL_12845791
EPI_ISL_12845792
EPI_ISL_12845793
EPI_ISL_12845794
EPI_ISL_12845795
EPI_ISL_12845796
EPI_ISL_12845797
EPI_ISL_12845798
EPI_ISL_12845799
EPI_ISL_12845800
EPI_ISL_12845801
EPI_ISL_12845802
EPI_ISL_12845803
EPI_ISL_12845804
EPI_ISL_12845805
EPI_ISL_12845806
EPI_ISL_12845807
EPI_ISL_12845808
EPI_ISL_12845809
EPI_ISL_12845810
EPI_ISL_12845811
EPI_ISL_12845812
EPI_ISL_12845813
EPI_ISL_12845814
EPI_ISL_12845815
EPI_ISL_12845816

Weirdly just 11 sequences are found by CovSpectrum (quite unexplicable to me @chaoran-chen ):
 https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1b%3AT1050N%2COrf1b%3AA1369T&nextcladePangoLineage=BA.5.2&aaMutations1=ORF3a%3AH78Y%2CS%3AF486I&nucMutations1=C9943T%2CC25614T%2CC27513T&

i have checked on Nextclade and they seem Ok.
![Schermata 2022-08-31 alle 19 28 19](https://user-images.githubusercontent.com/87669813/187741830-8afe4194-edc4-41c3-bfe3-4e0176d72283.png)

@corneliusroemer @aq-sun @chrisruis @InfrPopGen

**Comment by FedeGueli** [comment]
@AngieHinrichs could you take a look please? finally i found a tree grouping most of the sequences of this sublineage ( while i found at least 8 trees with this mutation still i am convinced it is  monophyletic) :
unlikely the most numerous group is defined by a reversion S:I19T 
![Schermata 2022-09-01 alle 09 35 36](https://user-images.githubusercontent.com/87669813/187858467-6e37bcc8-0938-4d30-9520-96165dbff302.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice6_genome_2171b_5d1d0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C241T,T670G,C1627T,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,G12310A,C12880T,C14408T,C15714T,C16616A,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,C27012T,C27513T,C27807T,C27889T,A28271T,C28311T,A28330G,G28881A,G28882A,G28883C,A29510C

Then there is another one smaller defined by G9424T and G5305A
![Schermata 2022-09-01 alle 09 38 09](https://user-images.githubusercontent.com/87669813/187858923-c5da11cb-8c1a-4632-83d9-410bf5446e2c.png)
 https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2171b_5d1d0.json?branchLabel=nuc%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G9424T

**Comment by chaoran-chen** [comment]
@FedeGueli, I looked at the sequences that you listed and most of them are not considered a BA.5.2 (or sublineage) by Nextclade which explains why the cov-spectrum query does not return them.

**Comment by FedeGueli** [comment]
@chaoran-chen very weird when i run them through Nextclade (Aksamentov, I., Roemer, C., Hodcroft, E. B., & Neher, R. A., (2021). Nextclade: clade assignment, mutation calling and quality control for viral genomes. Journal of Open Source Software, 6(67), 3773, https://doi.org/10.21105/joss.03773) i got all of them BA.5.2 :
![Schermata 2022-09-01 alle 23 06 28](https://user-images@corneliusroemer hubusercontent.com/87669813/188013093-36a9b202-f057-43d9-a4e7-d0b5a88bdd77.png)


@corneliusroemer

**Comment by FedeGueli** [comment]
> The pace of growth is impressive, at least quadrupling each week (I plotted the numbers for Moscow and Moscow region, which are fairly well covered by sequencing with about 500 genomes for each of the weeks on the plot) ![image](https://user-images.githubusercontent.com/93294184/187864602-2278ddf0-b100-4e9a-9228-d01471d8fcf6.png)

Quite suspicious i would say , @enabieva could you take a look at this potential sublineage please? it is already at 20% of samples from Russia, is it real or  are there some known pipeline issues around Orf1b:A1369T ??

**Comment by AngieHinrichs** [comment]
Hi @FedeGueli - aside from EPI_ISL_12845553 I get a completely different list of EPI_ISL's from the GISAID query:
EPI_ISL_12845553
EPI_ISL_14400340
EPI_ISL_14423493
EPI_ISL_14423944
EPI_ISL_14423973
EPI_ISL_14423995
EPI_ISL_14424822
EPI_ISL_14424857
EPI_ISL_14425187
EPI_ISL_14425231
EPI_ISL_14425276
EPI_ISL_14545929
EPI_ISL_14694612
EPI_ISL_14729903
EPI_ISL_14729909
EPI_ISL_14729911
EPI_ISL_14729913
EPI_ISL_14729916
EPI_ISL_14729919
EPI_ISL_14729921
EPI_ISL_14729924
EPI_ISL_14729941
EPI_ISL_14729942
EPI_ISL_14729943
EPI_ISL_14729947
EPI_ISL_14729949
EPI_ISL_14729950
EPI_ISL_14729951
EPI_ISL_14729956
EPI_ISL_14729959
EPI_ISL_14729961
EPI_ISL_14729966
EPI_ISL_14729970
EPI_ISL_14729971
EPI_ISL_14729978
EPI_ISL_14729979
EPI_ISL_14729982
EPI_ISL_14729990
EPI_ISL_14729993
EPI_ISL_14729997
EPI_ISL_14730002
EPI_ISL_14730006
EPI_ISL_14730012
EPI_ISL_14730013
EPI_ISL_14730015
EPI_ISL_14730016
EPI_ISL_14730019
EPI_ISL_14730022
EPI_ISL_14730024
EPI_ISL_14730025
EPI_ISL_14730028
EPI_ISL_14730031
EPI_ISL_14730033
EPI_ISL_14730035
EPI_ISL_14730036
EPI_ISL_14730044
EPI_ISL_14730046
EPI_ISL_14730052
EPI_ISL_14730063
EPI_ISL_14730064
EPI_ISL_14730066
EPI_ISL_14730069
EPI_ISL_14730071
EPI_ISL_14730074
EPI_ISL_14730079
EPI_ISL_14730080
EPI_ISL_14730082
EPI_ISL_14730083
EPI_ISL_14730084
EPI_ISL_14730086
EPI_ISL_14730088
EPI_ISL_14730090
EPI_ISL_14730091
EPI_ISL_14730092
EPI_ISL_14730100
EPI_ISL_14730111
EPI_ISL_14730112
EPI_ISL_14730118
EPI_ISL_14730121
EPI_ISL_14730122
EPI_ISL_14730123
EPI_ISL_14730126
EPI_ISL_14730129
EPI_ISL_14730132
EPI_ISL_14730133
EPI_ISL_14730135
EPI_ISL_14730136
EPI_ISL_14730139
EPI_ISL_14730143
EPI_ISL_14730144
EPI_ISL_14730148
EPI_ISL_14730151
EPI_ISL_14730155
EPI_ISL_14730163
EPI_ISL_14730164
EPI_ISL_14730166
EPI_ISL_14730167
EPI_ISL_14730172
EPI_ISL_14730176
EPI_ISL_14730177
EPI_ISL_14730181
EPI_ISL_14730185
EPI_ISL_14730187
EPI_ISL_14730194
EPI_ISL_14730199
EPI_ISL_14730200
EPI_ISL_14730201
EPI_ISL_14730202
EPI_ISL_14730207
EPI_ISL_14730208
EPI_ISL_14730211
EPI_ISL_14730215
EPI_ISL_14730221
EPI_ISL_14730225
EPI_ISL_14730230
EPI_ISL_14730231
EPI_ISL_14730233
EPI_ISL_14730236
EPI_ISL_14730238
EPI_ISL_14730240
EPI_ISL_14730241
EPI_ISL_14730243
EPI_ISL_14730245
EPI_ISL_14730247
EPI_ISL_14730249
EPI_ISL_14730250
EPI_ISL_14730251
EPI_ISL_14730252
EPI_ISL_14730253
EPI_ISL_14730254
EPI_ISL_14730257
EPI_ISL_14730258
EPI_ISL_14730259
EPI_ISL_14730265
EPI_ISL_14730266
EPI_ISL_14730267
EPI_ISL_14730271
EPI_ISL_14730272
EPI_ISL_14730276
EPI_ISL_14730279
EPI_ISL_14730284
EPI_ISL_14730296
EPI_ISL_14730299
EPI_ISL_14730300
EPI_ISL_14730303
EPI_ISL_14730304
EPI_ISL_14730305
EPI_ISL_14730308
EPI_ISL_14730314
EPI_ISL_14730316
EPI_ISL_14730327
EPI_ISL_14730328
EPI_ISL_14730330
EPI_ISL_14730332
EPI_ISL_14730333
EPI_ISL_14730336
EPI_ISL_14730337
EPI_ISL_14730338
EPI_ISL_14730342
EPI_ISL_14730346
EPI_ISL_14730354
EPI_ISL_14730358
EPI_ISL_14730360
EPI_ISL_14730363
EPI_ISL_14730364
EPI_ISL_14730365
EPI_ISL_14730366
EPI_ISL_14730367
EPI_ISL_14730368
EPI_ISL_14730372
EPI_ISL_14730383
EPI_ISL_14730390
EPI_ISL_14730392
EPI_ISL_14730394
EPI_ISL_14730395
EPI_ISL_14730398
EPI_ISL_14730404
EPI_ISL_14730405
EPI_ISL_14730407
EPI_ISL_14730408
EPI_ISL_14730409
EPI_ISL_14730412
EPI_ISL_14730423
EPI_ISL_14730429
EPI_ISL_14730434
EPI_ISL_14730441
EPI_ISL_14730447
EPI_ISL_14730448
EPI_ISL_14730457
EPI_ISL_14730463
EPI_ISL_14730464
EPI_ISL_14730469
EPI_ISL_14730474
EPI_ISL_14730487
EPI_ISL_14731088
EPI_ISL_14731092
EPI_ISL_14731119
EPI_ISL_14731140
EPI_ISL_14731193
EPI_ISL_14731319
EPI_ISL_14731320
EPI_ISL_14731324
EPI_ISL_14731330
EPI_ISL_14731348
EPI_ISL_14731352
EPI_ISL_14731355
EPI_ISL_14731358
EPI_ISL_14731364
EPI_ISL_14731366
EPI_ISL_14731372
EPI_ISL_14731376
EPI_ISL_14731381
EPI_ISL_14731382
EPI_ISL_14731386
EPI_ISL_14731390
EPI_ISL_14731393
EPI_ISL_14731396
EPI_ISL_14731398
EPI_ISL_14731413
EPI_ISL_14731419
EPI_ISL_14731424
EPI_ISL_14731426
EPI_ISL_14731428
EPI_ISL_14731430
EPI_ISL_14731431
EPI_ISL_14731433
EPI_ISL_14731434
EPI_ISL_14731436
EPI_ISL_14731437
EPI_ISL_14731438
EPI_ISL_14731439
EPI_ISL_14731442
EPI_ISL_14731443
EPI_ISL_14731444
EPI_ISL_14731445
EPI_ISL_14731446
EPI_ISL_14731447
EPI_ISL_14731456
EPI_ISL_14731458
EPI_ISL_14731464
EPI_ISL_14731470
EPI_ISL_14731471
EPI_ISL_14731474
EPI_ISL_14731475
EPI_ISL_14731477

**Comment by corneliusroemer** [comment]
Let's put the EPI_ISLs in collapsibles otherwise this gets out of hand :D 

```md
<details>
  <summary>Expand for EPI_ISLs</summary>
  EPI ISLs go here
</details>
```

This looks like a bioinfo problem as the mutation appears all over the tree and is not monophyletic.

I'll close this to not ring alarm bells when they aren't due - the growth as suggested would have been bad. But we've seen things like this before. Would be good for the lab to fix.

<img width="1628" alt="image" src="https://user-images.githubusercontent.com/25161793/188022474-66e6180a-18fc-4404-a818-4dd804c36713.png">

How did I verify? I downloaded all sequences submitted to GISAID with collection date >1st of August.

Then ran through Nextclade. And the mutation that separates these is all over the tree - not just in BA.5.2.

**Comment by AngieHinrichs** [comment]
The 2022-08-31 UShER tree has a branch BA.5.2 > G12310A > C16616A (ORF1b:T1050N) that has 94,326 samples.  Of the 245 EPI_ISL's that I get from your GISAID query (M_D3N, NSP13_A446T, NSP13_T127N), 157 are in the tree on that branch -- and they are all over the place.  Here is a taxonium view of the ORF1b:T1050N branch (yellow) with dark blue circles around samples from the query and green circles around nodes with ORF1b:1369 (nsp13:446) mutations to T:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/186983/188021872-4231d4c2-f779-40a0-a4a5-47bf39bcbe23.png">

So yes, all those dark blue circled sequences have ORF1b:T1050N and G17572A (ORF1b:1369T / nsp13:446T) -- but it seems that they also have multiple other mutations in common with other sequences which do not have G17572A, so they are pulled into many different branches.  It's also possible that they have some ambiguous or N bases that allow them to match in different places.

OK, I see @corneliusroemer's update now -- it looks like we are getting at the same thing, with complementary colors.  😄  Thanks for the tip about `<details>`, I will edit.

**Comment by FedeGueli** [comment]
Thx everyone for looking at it!
