### ISSUE TITLE
BA.5.5 with ORF1a:V3166F and ORF1b:L314R [156 good seq & 299 total seq as of 2022-09-01]

### ISSUE THREAD

**Issue by ndkling** [cov-lineages/pango-designation#1015]
Proposal for a sublineage of BA.5.5
Earliest sequences: 2022-06-06 (Colorado, USA, ON969679.1, ON901335.1)
Countries detected: Mostly USA, but some Canadian and overseas international distribution

ORF1b:P314L is the second most successful mutation in SARS-CoV-2, only 1.1% less prevalent than S:D614G globally throughout the pandemic to date.  It results in P323L in the RdRp enzyme, which is associated with [increased plaque sizes](https://www.biorxiv.org/content/10.1101/2021.12.23.474030v1.full).  Omicron relies on endocytosis with high ACE2 affinity and [makes smaller plaques than Delta](https://www.nature.com/articles/s41586-022-04474-x), so 323L may not benefit it as much as most earlier lineages.  My proteomics are too poor to even guess what R might do in place of L or P.

Curiously, ORF1a:V3166F is in nsp4, which per covSPECTRUM, "anchors viral replication-transcription complex to ER membranes".  There is a possibility that the two mutations are synergistic, with the combination only found in [5 non-BA.5.5 sequences (which might be miscalled)](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nextcladeQcOverallScoreTo=29&aaMutations=orf1b%3A314r%2CORF1a%3AV3166F&nextcladePangoLineage=BA.5.5&aaMutations1=ORF1a%3AV3166F%2CORF1b%3A314R&analysisMode=CompareEquals&) in the entire pandemic.  [ORF1b:314R never did well alone, though it remains at extremely low prevalence](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nextcladeQcOverallScoreTo=29&aaMutations=orf1b%3A314r&aaMutations1=ORF1a%3AV3166F%2CORF1b%3A314R&).

![orf1b314rOverWholePandemic](https://user-images.githubusercontent.com/82973333/187907119-4cc4fe69-ba66-45d5-bf41-3b08b26817a3.png)

Anyway, a cluster of ORF1a:3166F and ORF1b:314R sequences has emerged, primarily in the USA.  The lineage appears to be BA.5.5->nuc:C5512T->ORF1a:V3166F and ORF1b:L314R.  Global growth advantages are substantial, but not high.  However, BA.2.75 may be demonstrating that possible advantages in replication (ORF1b:G662S) can increase the rate of evolution, leading to larger later growth advantages with faster acquisition of beneficial traits over time.  Thus, I consider this my most "promising" proposed lineage yet.

I'm puzzled and concerned by the low ratio of good reads here, so explanations are welcome.

Genomes:

[C5512TtoV3166F+L4715R.csv](https://github.com/cov-lineages/pango-designation/files/9469285/C5512TtoV3166F%2BL4715R.csv)

obtained through covSPECTRUM with the following query:

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladeQcOverallScoreTo=29&aaMutations=orf1b%3A314r%2CORF1a%3AV3166F&nucMutations=C5512T&nextcladePangoLineage=BA.5.5&aaMutations1=ORF1a%3AV3166F%2CORF1b%3A314R&

Evidence:

Clusters pretty cleanly within the C5512T nucleotide with one minor exception: BA.5.5 with ORF1a:V3166F and ORF1b:L314R independently arose once without C5512T, only producing 2 isolates (to date).

![C5512TtoV3166F+L4715R](https://user-images.githubusercontent.com/82973333/187902351-7cbcffff-d87c-491d-94ee-f3e345307e91.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3a217_7f1b0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:T4388C

A solid 28%(CI 22-33%) 3-month global growth advantage is exhibited over background:

![vsBackground](https://user-images.githubusercontent.com/82973333/187892852-20683b56-35d2-4070-9d28-c87a6367e6c3.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=orf1b%3A314r%2Corf1a%3A3166f&nucMutations=C5512T&nextcladePangoLineage=ba.5.5*

Surprisingly, the advantage over BA.5.5 is nearly the same, at 27%(CI 21-33%):

![vsBA 5 5](https://user-images.githubusercontent.com/82973333/187893723-333f5d80-738c-4a1d-bcfc-dd9cf87b9867.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=ba.5.5*&aaMutations1=orf1b%3A314r%2Corf1a%3Av3166f&nucMutations1=c5512t&nextcladePangoLineage1=ba.5.5&analysisMode=CompareToBaseline&

**Comment by corneliusroemer** [comment]
Interesting proposal as it does seem to have a real growth advantage that is due to non-Spike.

It doesn't seem to grow that fast and will likely not become a big thing in the pandemic but it's got an Epi link (US) so worth designating in my view.

**Comment by corneliusroemer** [comment]
Designated as BA.5.5.3

**Comment by ndkling** [comment]
One parting note for any researchers who come across this someday.  ORF1b:L314R resulted from T14408G.  U>G is the second rarest mutation in SARS-CoV-2, while its reversion is the second most common mutation.  The ancestral strain was 50.9% U and equilibrium in humans is believed as of this writing to be around 65%.

Beyond the simple growth advantage, its successful persistence in an apparently significant residue indicates a competitive advantage of some sort in this genotype.
