### ISSUE TITLE
BA.1* sublineage with spike P9S, I128V, S151del, W152R, R190T, R346T, F490S, D936Y, and possibly N370K, V445A and N460K (4 seqs as of 2022-08-31, Peru)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1016]
### Description
**Sub-lineage of**: BA.1* (possibly BA.1.22)
**Earliest sequence**: 2022-7-17, Peru-Lima
**Most recent sequence**: 2022-8-8, Peru-Lima
**Countries sequenced**: Peru
**Number of Sequences**: 4,  **from 4 different patients**, of which 3 are collected in Lima, and 1 in Huancavelica (425KM away from Lima)
**Substitutions on top of BA.1**:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/itine/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/itine/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Gene | Nuc mutations and amino substitutions
-- | --
ORF1a | A486V, F914L, G5515T, K1795Q, S2535L, A3657V
S | P9S, I128V, S151del, W152R, R190T, R346T, F490S, **D936Y** **(2-nuc mutation)**
ORF3a | S177N

</body>

</html>

Potentially, there might be a few aditional amino changes but not represented by sequencing.
The following is the substitution table of EPI_ISL_14721894, the genome with best coverage and least NNNs:
![image](https://user-images.githubusercontent.com/86835836/188107246-21018e8e-f65f-4de6-9902-a1ec65ecd502.png)
It has additional spike N370K (another 2-nuc substitution), V445A and N460K, where all other 3 genomes have an X at site 445.

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/188118815-19bc307a-a410-410b-9539-efc0e2bdd6c2.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c880_162070.json?branchLabel=Spike%20mutations&label=nuc%20mutations:T18318G

### Genomes:
EPI_ISL_14535112, EPI_ISL_14721837, EPI_ISL_14721894,
EPI_ISL_14746124

**Comment by c19850727** [comment]
ehh forgot to mention the extraordinary dN/dS ratio and spike/non-spike ratio.

**Comment by corneliusroemer** [comment]
Interesting find. @Vjimenez-vasquez I think you could be interested in this - it's in your courtyard!

It would be great to know if this is a single chronic case or what's known about the patient(s).

**Comment by c19850727** [comment]
Hi @corneliusroemer I've actually already mentioned that all 4 patients are different based on age/sex provided in the metadata.

**Comment by corneliusroemer** [comment]
No more sequences since the initial 4 - I'll close. Let's reopen if this reappears!
