### ISSUE TITLE
Sublineage of BA.5.9 with S:E471Q mutation (86 sequences) and its sublineage with N:P168S circulating in Japan (39 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1017]
Here i want to propose a sublineage of BA.5.9 that i already highlighted in #753 defined by another spike mutation S:E471Q

S:E471Q is present in just 1200 samples but very sparse in the different vocs spanning from Alpha to Delta sublineages

Defining mutations of this proposed lineage: Nuc: C14676T S:E471Q

Tree:
![Schermata 2022-09-02 alle 17 20 40](https://user-images.githubusercontent.com/87669813/188181703-c6ec2636-2052-4850-999c-01c9bbfac2aa.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ef6c_21e850.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C14676T

Covspectrum query finds only 39 out of 70 sequences: 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AE471Q&nextcladePangoLineage=BA.5.9*&
in 7 countries:
 
![GeographicDistribution](https://user-images.githubusercontent.com/87669813/188181206-b32122c7-ba0b-4307-a3d5-915978f537ea.png)

Gisaid Query : Spike_r346I,Spike_E471Q finds 70 Sequences:
First sequence: EPI_ISL_13498780 from Uk  2022-06-20
List of Sequences:
<details>
<summary>Expand for EPI_ISLs</summary> 
EPI_ISL_13498726
EPI_ISL_13498767
EPI_ISL_13498780
EPI_ISL_13498789
EPI_ISL_13498794
EPI_ISL_13566766
EPI_ISL_13566845
EPI_ISL_13566890
EPI_ISL_13656538
EPI_ISL_13656619
EPI_ISL_13798055
EPI_ISL_13936086
EPI_ISL_13937076
EPI_ISL_13945687
EPI_ISL_13986726
EPI_ISL_14020579
EPI_ISL_14140531
EPI_ISL_14140666
EPI_ISL_14167818
EPI_ISL_14167826
EPI_ISL_14212069
EPI_ISL_14348479
EPI_ISL_14352885
EPI_ISL_14389348
EPI_ISL_14397278
EPI_ISL_14401816
EPI_ISL_14405006
EPI_ISL_14413633
EPI_ISL_14445982
EPI_ISL_14504876
EPI_ISL_14519228
EPI_ISL_14520029
EPI_ISL_14520673
EPI_ISL_14521025
EPI_ISL_14548557
EPI_ISL_14548595
EPI_ISL_14549363
EPI_ISL_14590321
EPI_ISL_14590403
EPI_ISL_14597146
EPI_ISL_14642891
EPI_ISL_14692394
EPI_ISL_14692614
EPI_ISL_14692989
EPI_ISL_14694234
EPI_ISL_14753149
EPI_ISL_14754217
EPI_ISL_14767751
EPI_ISL_14767770
EPI_ISL_14767771
EPI_ISL_14767772
EPI_ISL_14767773
EPI_ISL_14767774
EPI_ISL_14767775
EPI_ISL_14767776
EPI_ISL_14767777
EPI_ISL_14767778
EPI_ISL_14767779
EPI_ISL_14767780
EPI_ISL_14767781
EPI_ISL_14767782
EPI_ISL_14767783
EPI_ISL_14767784
EPI_ISL_14767785
EPI_ISL_14767786
EPI_ISL_14767787
EPI_ISL_14767788
EPI_ISL_14767789
EPI_ISL_14773946
EPI_ISL_14782518
</details>

**Comment by FedeGueli** [comment]
Note that the japanese branch of this proposed lineage is well defined by N:P168S and counts already  30 Sequences.
If the main lineage wont be designated for growth rate the japanese branch is well supported by geographical /Epi links

**Comment by FedeGueli** [comment]
One more sequence from Slovenia: EPI_ISL_14814752

**Comment by FedeGueli** [comment]
74 as today

**Comment by corneliusroemer** [comment]
This seems to grow only very slowly, doesn't it? Only 3 new sequences in the past 9 days? Looks like it's dying so maybe not worth designating.

**Comment by FedeGueli** [comment]
@corneliusroemer yeah it is quite slow one. last batch of uploads mainly from the Japanese branch with N:P168S

**Comment by FedeGueli** [comment]
88 viruses as today
