### ISSUE TITLE
Potential BA.5.2 Sublineage with ORF1b:T1050N, ORF1a:I4291V, and ORF1a:N2102S (128 seqs as of 2022-09-11; Europe, Israel, USA)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1018]
There may be a BA.5.2 sublineage with ORF1a:N2102S (A6570G), ORF1a:I4291V (A13136G), ORF1b:T1050N (C16616A) first detected in England, United Kingdom.

As of 2022-09-02, Cov-Spectrum reports 118 BA.5.2+ORF1a:2102S+ORF1a:4291V+ORF1b:1050N sequences with good quality control scores:
![BA 5 2+ORF1a_2102S+ORF1a_4291V+ORF1b_1050N_Counts](https://user-images.githubusercontent.com/88959107/188244484-fc97a19a-c8d8-49e4-a398-8685aa7d9e14.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2+%26+ORF1a%3AN2102S+%26+ORF1a%3AI4291V+%26+ORF1b%3AT1050N&nextcladeQcOverallScoreTo=29&

As of 2022-09-02 and considering only sequences with good quality control scores, Cov-Spectrum calculates a growth advantage of 24% compared to BA.5.2* in the United Kingdom:
![BA 5 2+ORF1a_2102S+ORF1a_4291V+ORF1b_1050N_Growth_vs_BA 5 2](https://user-images.githubusercontent.com/88959107/188244508-44e6eca7-ffb3-455f-adb5-b53bfc2c92b2.png)
Source: https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2*&variantQuery1=nextcladePangoLineage%3ABA.5.2+%26+ORF1a%3AN2102S+%26+ORF1a%3AI4291V+%26+ORF1b%3AT1050N&analysisMode=CompareToBaseline&nextcladeQcOverallScoreTo=29&

As of 2022-09-02 and considering only sequences with good quality control scores, Cov-Spectrum calculates a growth advantage of 28% compared to BA.5* in the United Kingdom:
![BA 5 2+ORF1a_2102S+ORF1a_4291V+ORF1b_1050N_Growth_vs_BA 5](https://user-images.githubusercontent.com/88959107/188244522-8bed61bc-fa77-48ec-be0b-b5f6929b7df8.png)
Source: https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABA.5.2+%26+ORF1a%3AN2102S+%26+ORF1a%3AI4291V+%26+ORF1b%3AT1050N&analysisMode=CompareToBaseline&nextcladeQcOverallScoreTo=29&

As of 2022-09-02, UShER shows all of the GenBank samples are on a single subtree:
![BA 5 2+ORF1a_2102S+ORF1a_4291V+ORF1b_1050N_UShER](https://user-images.githubusercontent.com/88959107/188244546-96a6a9e5-f1d6-4e2c-82e7-dc9329cfc407.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/09/subtreeAuspice1_genome_BA.5.2%2BORF1a_2102S%2BORF1a_4291V%2BORF1b_1050N.json?branchLabel=aa%20mutations&c=gt-ORF1ab_2102

First GenBank sequence: England, United Kingdom 2022-06-15 

Most Recent GenBank sequence: England, United Kingdom 2022-08-12

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at [Support-BA.5.2+ORF1a_2102S+ORF1a_4291V+ORF1b_1050N.zip](https://github.com/cov-lineages/pango-designation/files/9481401/Support-BA.5.2%2BORF1a_2102S%2BORF1a_4291V%2BORF1b_1050N.zip)

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=BA.5.2&muts=ORF1a%3AN2102S&muts=ORF1a%3AI4291V&muts=ORF1b%3AT1050N.

**Comment by alurqu** [comment]
ORF1a:N2102S is also NSP3:N1284S, and ORF1a:I4291V is also NSP10:I38V.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. It has been showing increasingly negative trends since early October. As these look sustained, I think this can be closed for now. Nevertheless, please feel free to reopen should there be any major changes.
