### ISSUE TITLE
BA.5.2 + Orf1b:T1050N sublineage with a double spike mutation S:P251H, S:R1014K , circulating in  Denmark likely emerged in Serbia ( 62 Seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1019]
Defining mutations:
BA.5.2 >G12310A, Orf1b:1050N >C27012T, C27513T> 23707T >S:P251H, S:R1014K

Gisaid query: NSP13_T127N,Spike_P251H,Spike_R1014K
finds 36 sequences

CovSpectrum query:  BA.5.2* (Nextclade) + orf1b:1050N+  + 23707T + S:251H +S:R1014K
finds 27 sequences
 https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1b%3A1050N%2CS%3AR1014K%2CS%3AP251H&nucMutations=23707T&nextcladePangoLineage=BA.5.2*&aaMutations1=Orf1b%3A1050N&nextcladePangoLineage1=BA.5.2*&

 
<details>
<summary>Expand for EPI_ISLs</summary>

EPI_ISL_14213471
EPI_ISL_14416756
EPI_ISL_14468837
EPI_ISL_14474384
EPI_ISL_14474391
EPI_ISL_14474416
EPI_ISL_14529231
EPI_ISL_14545973
EPI_ISL_14569252
EPI_ISL_14569609
EPI_ISL_14608321
EPI_ISL_14625158
EPI_ISL_14662110
EPI_ISL_14690670
EPI_ISL_14690722
EPI_ISL_14690853
EPI_ISL_14691502
EPI_ISL_14692898
EPI_ISL_14694700
EPI_ISL_14699690
EPI_ISL_14699876
EPI_ISL_14702214
EPI_ISL_14705716
EPI_ISL_14705856
EPI_ISL_14722146
EPI_ISL_14722271
EPI_ISL_14722318
EPI_ISL_14750874
EPI_ISL_14750899
EPI_ISL_14751108
EPI_ISL_14756733
EPI_ISL_14757699
EPI_ISL_14772529
EPI_ISL_14775041
EPI_ISL_14789839
EPI_ISL_14802225

</details>

Countries:
13 Denmark, 4 Serbia , 4 US, 3 Germany, 2 Croatia, 2 Turkey, but also Netherlands, Israel, France, England, Sweden, Poland , Belgium and Luxembourg

Its growth in Denmark seems very fast but really too early to say:
sparse single samples from different countries makes me think that probably this lineage has a good prevalence somewhere in the Eastern/South Eastern Europe and a hint of that comes from the first two sequences both from Serbia:
EPI_ISL_14474416 / 
EPI_ISL_14474391
In Denmark (with an additional N:A398V mutation) it is already circulating and accumulating sequences very quickly.
And the diversity shown by the Usher tree could further push another confirmation :
![Schermata 2022-09-03 alle 01 48 06](https://user-images.githubusercontent.com/87669813/188247102-7f2f6bf5-bdd6-4415-99eb-1024eabad0cb.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ae1c_295540.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C22314A,G24603A

**Comment by dimadin** [comment]
Can you see locations where samples were collected? I see three sequences from Serbia in that tree: `EPI_ISL_14474416`, `EPI_ISL_14474391`, and `EPI_ISL_14474384`. They all have "Huo-yan national laboratory for molecular detection of infectious agents Nis" as originating laboratory. Submiting laboratory is "Institute of Molecular Genetics and Genetic Engineering University of Belgrade", where sequencing was done.

Niš is the third largest city in Serbia, and largest in southern Serbia. "Huo-yan" ("Fire eye") laboratory in Niš processes PCR samples collected in southern Serbia. (There is also Huo-yan Belgrade.) 

When I go to the [Nextstrain](https://nextstrain.org/ncov/gisaid/europe/6m?f_country=Serbia), for some sequences I see location (different towns). But I don't see these three sequences there.

**Comment by FedeGueli** [comment]
2 more sequences: Denmark collected on 28/08/2022 , NYC US collected on 29/08/2022

**Comment by FedeGueli** [comment]
> Can you see locations where samples were collected? I see three sequences from Serbia in that tree: `EPI_ISL_14474416`, `EPI_ISL_14474391`, and `EPI_ISL_14474384`. They all have "Huo-yan national laboratory for molecular detection of infectious agents Nis" as originating laboratory. Submiting laboratory is "Institute of Molecular Genetics and Genetic Engineering University of Belgrade", where sequencing was done.
> 
> Niš is the third largest city in Serbia, and largest in southern Serbia. "Huo-yan" ("Fire eye") laboratory in Niš processes PCR samples collected in southern Serbia. (There is also Huo-yan Belgrade.)
> 
> When I go to the [Nextstrain](https://nextstrain.org/ncov/gisaid/europe/6m?f_country=Serbia), for some sequences I see location (different towns). But I don't see these three sequences there.

I see one from Nis, and two from Vlasotince  @dimadin tell me if you need more informations.

**Comment by FedeGueli** [comment]
3 more sequences uploaded today two from Zagreb, Croatia and one from Denmark

**Comment by FedeGueli** [comment]
One more sequence from Denmark collected on 28/08/22

**Comment by FedeGueli** [comment]
New sequence from Montenegro: EPI_ISL_14837628, sampled in an elderly people, i think this means already a good circulation in the Balcanic area.

**Comment by FedeGueli** [comment]
One more sequence from Canada

**Comment by FedeGueli** [comment]
Two more sequence from Utah and Wisconsin. It seems growing fast. @corneliusroemer @InfrPopGen 
check collection #23 https://cov-spectrum.org/collections/23

**Comment by FedeGueli** [comment]
48 as today, new samples from Denmark, Germany and California

**Comment by FedeGueli** [comment]
4 more sequences , 1 from England , 3 from Denmark. 52 viruses as today

**Comment by FedeGueli** [comment]
Newly found in Turkey today. I think this deserves a designation @corneliusroemer

**Comment by FedeGueli** [comment]
A lot of new sequences uploaded yesterday and today: 8 ( 3 Utah, 1 Ireland,  2 Slovenia, 1 Slovakia, 
1 Denmark) 
@corneliusroemer @InfrPopGen i suggest to designate this one :
1) new countries meaning ongoing spread
2) quite rapid growth see Collections # 23 
3) Emerged in a specific area (Balkans)
4) Two spike quite uncommon mutations: one in NTD and one in S2  both in similar positions as fast lineages as BF.15 (S:248H) or BF.5 (S:1020S)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.17 with 36 newly designated sequences, and 0 updated designations. Defining mutations C22314A (S:P251H),G24603A (S:R1014K).

**Comment by FedeGueli** [comment]
71 viruses as today.
This seems to have some traction in Turkey from where 8 sequences were uploaded, one with two more spike mutations: S:359T, S:A958S.

**Comment by FedeGueli** [comment]
This now has been renamed BV.1  by @corneliusroemer 
Please @thomaspeacock or @InfrPopGen could change the milestone for it?

**Comment by FedeGueli** [comment]
Interesting new data on S:R1014K, defining mutation in BV.1 from this Nicholeas Wu paper :
"High-throughput identification of prefusion-stabilizing mutations in SARS-CoV-2 spike"
( Timothy J.C. Tan, Zongjun Mou, Ruipeng Lei,Wenhao O. Ouyang, Meng Yuan, Ge Song, Raiees Andrabi, Ian A. Wilson, Collin Kieffer, Xinghong Dai, Kenneth A. Matreyek, Nicholas C. Wu) 
https://www.biorxiv.org/content/10.1101/2022.09.24.509341v1.full

Apparently this mutation S:R1014K increases moderately fusogenicity and protein expression:
<img width="496" alt="Schermata 2022-09-29 alle 12 58 21" src="https://user-images.githubusercontent.com/87669813/193014164-2b7c820f-5415-4e37-b86b-86b595a36d1c.png">
