### ISSUE TITLE
B.1.617.2 subclade with N:G215C

### ISSUE THREAD

**Issue by mkedwards** [cov-lineages/pango-designation#102]
## New lineage proposal
by Michael K. Edwards <m.k.edwards@gmail.com>

### Description
Sub-lineage of: B.1.617.2
Earliest sequence: collected 2020-11-21
Most recent sequence: Now.
Countries circulating: Global.

I think this subclade (with N:G215C) ought to be tracked separately from the rest of B.1.617.2.  It appears to have been later in spreading outside India but may be spreading considerably faster where it's introduced.

Appears to have originated in India, perhaps specifically Uttar Pradesh.

The closest thing genomically to the founding strain in Nextstrain's Asia subsample appears to be GISAID EPI ISL 2272809; the earliest sample I've seen (which has some other drift) is 2373501 (collected 2020-11-21). Here are the visible changes specific to the variant:

N: G215C
ORF1a: A1306S, P2046L, P2287S, V2930L, T3255I, T3646A
ORF1b: G662S, P1000L, A1918V
ORF7b: T40I
plus A11332G (synonymous in nsp6)

on top of the set of mutations that appear to define B.1.617.2:
M: I82T
N: D63G, R203M, D377Y
ORF1b: P314L
ORF3a: S26L
ORF7a: V82A, T120I
ORF9b: T60A
S: T19R, EFR156–158G, L452R, T478K, D614G, P681R, D950N

Note that there is some calling weirdness at the end of ORF8 in a lot of B.1.617.2, and I'm leaving that out.

### Genomes
Easy enough to extract from a Nextstrain search.  Note that S:G142D is some kind of primer-related calling noise.  What seems to define this subclade is a series of drift-y mutations followed by an explosion after the discovery of ORF1a: P2046L,T3646A.  Note that T3646A is also present in B.1.617.1.  I am not wholly convinced that all of B.1.617.2 shares a common ancestor that B.1.617.1 doesn't.  Then again, P2046L has also been discovered in multiple unrelated clades; it's one of the defining mutations of B.1.351.3.  And C.36 also has ORF1a:P2287S, and T3255I is in several other clades, including B.1.1.519.  I'm starting to think that all four of these belong in the "fitness-increasing short putts from almost anywhere" category along with S:E484K and S:N501Y.

So if you want something really clade-defining, I'd filter on nucleotide A11332G.  N: G215C is also a good candidate, and is right there in the region that seems to most sensitively affect phosphorylation dynamics of the SR-rich linker — so it might be the real functional change.  (Take that, Spike-centric analyses!)

### Evidence
https://nextstrain.org/ncov/asia?branchLabel=aa&c=gt-N_215&f_pango_lineage=B.1.617.2&m=div

Observe the explosion in both sample count and genomic diversity after the discovery of ORF1a: P2046L,T3646A.

<img width="1407" alt="Screen Shot 2021-06-02 at 5 12 11 PM" src="https://user-images.githubusercontent.com/843186/120567222-177de680-c3c6-11eb-83bc-2c757a2b4853.png">

### Proposed lineage name
B.1.617.5?

**Comment by mkedwards** [comment]
I mean, honestly, I think the way that the N:R203M (B.1.617) clade has been split up is kind of busted.  There are three or four loosely related subclades in there (none of which is B.1.617.3, which is more or less noise); and a healthy chunk of what you're labeling "B.1.617.2" is more closely related to B.1.617.1.  Try slicing by ORF1b polymorphisms and you'll see what I mean.

https://nextstrain.org/ncov/asia?branchLabel=aa&c=gt-ORF1b_2310,662,1000,2285,1570&gt=N.203M&m=div

<img width="1403" alt="Screen Shot 2021-06-03 at 4 09 48 PM" src="https://user-images.githubusercontent.com/843186/120723245-39d73900-c486-11eb-8b49-8d5ec47cf153.png">

**Comment by mkedwards** [comment]
It's pretty clearly the N:G215C subclade that's exploding in the UK.

https://nextstrain.org/groups/neherlab/ncov/united-kingdom?branchLabel=aa&c=gt-ORF1b_2310,662,1000,2285,1570&label=clade:21A

<img width="1413" alt="Screen Shot 2021-06-03 at 8 22 32 PM" src="https://user-images.githubusercontent.com/843186/120741314-b7f90700-c4a9-11eb-9372-5df4116a1c20.png">

**Comment by zach-hensel** [comment]
T3646A might be a better or worse alternative to del3675/3677 in other major variants. On the DeepMind Nsp6 prediction, the 106-108 deletion (yellow) is in a loop and T77A (red) is in the middle of residues 60-98 (green) that are fairly conserved. Mutations in immunocompromised patients (orange) also contact this region and it's not hard to guess how L37F could play a similar role if any of this is significant (and if the predicted structure is close to accurate).

![image](https://user-images.githubusercontent.com/23096983/121757241-d350bb80-cb14-11eb-8061-6ee6ce814082.png)

T95I was also added and this subclade and T95I is now ~half UK sequences; India less well sampled but similar. I guess that increase in these mutations has something to do with Nepal/Sri Lanka/Maldives/Seychelles increasing transmission so quickly simultaneously (on top of what you'd expect from increased imports from India). It should be useful to know what if any transmission advantage there is since countries have different starting points depending on April/May travel policies; extrapolating to 100% Delta to decide near-term policies is difficult otherwise.

Also maybe of interest is N:G215C changing to N:del214/215. This is at the root of one of the large Singapore clusters and now it looks like a significant cluster in England starting 23/May and 34 sequences already.

**Comment by mkedwards** [comment]
Ping?  This subclade (as defined by the ORF1b SNPs above) is now up to something like 97% of Delta in the UK.

https://nextstrain.org/groups/neherlab/ncov/united-kingdom?branchLabel=aa&c=gt-ORF1b_2310,662,1000,2285,1570&f_country=United%20Kingdom&label=clade:21A%20%28Delta%29

<img width="1127" alt="Screen Shot 2021-06-18 at 1 39 48 PM" src="https://user-images.githubusercontent.com/843186/122614225-18a44a00-d03b-11eb-975e-9996378068e5.png">

**Comment by zach-hensel** [comment]
I imagine with AY.1 being a sublineage of this it's a bit complicated to sort out the designations and it seems to be getting more complicated. Here's a toy model I made of how Nsp6 mutations might be relevant based on DeepMind structure predictions; L37, T77, and SGF106-108 all could plausibly play a role in the conformation of a methionine rich region (yellow), which could be sensitive to oxidative stress to gate double membrane vesicles in a hexamer pore. Lots of K and one R outside are putative RNA binding regions (also some conservation here). An Nsp4 dodecamer outside is more speculative, but dimensions are roughly consistent with MHV EM data (Wolff et al. DOI: 10.1126/science.abd3629), fit the Nsp6 hexamer well, and surface charge is consistent with typical EM transmembrane protein polarity.

This and other putative structures could be tested by looking for coevolving residues at putative symmetric multimer and Nsp4-Nsp6 interfaces and the structure could be improved probably best with a coarse-grained or all-atom model adding a force to weakly constrain transmembrane domains and lipids within two bilayers with the ~11-nm separation observed for MHV. I've run out of relevant expertise at this point and the learning curve is steep for either of those, so if anyone finds this plausible and wants to pursue this lmk and I'll send PDBs.

![image](https://user-images.githubusercontent.com/23096983/122639257-db01f880-d0f0-11eb-8b02-f028d1a95222.png)

**Comment by mkedwards** [comment]
Add S:T95I and S:EFR156–158G, and you get the strain that I am guessing hit the Nos Tayons retirement home in Nivelles, Brabant Wallon, Belgium:  https://infodujour.fr/societe/50183-douze-morts-du-covid-en-belgique-tous-etaient-vaccines

https://nextstrain.org/groups/neherlab/ncov/belgium?branchLabel=aa&c=gt-N_209,210,215&f_country=Belgium&f_division=Brabant%20Wallon&m=div

(Check out the ages of the patients in the two clusters.  I don't have independent confirmation that these are the Nos Tayons samples, but the location and dates appear to check out.)

<img width="1407" alt="Screen Shot 2021-06-19 at 9 36 34 AM" src="https://user-images.githubusercontent.com/843186/122649256-da159a80-d0e1-11eb-9f55-e4574c0ae73e.png">

**Comment by mkedwards** [comment]
@zach-hensel the Wolff et al. paper is excellent science, and it's great to see you building on it.  Note that these pores are also the sites of vRNP formation, and I'd think there could be some functional coupling between nsp6 and N mutations.  One would expect N:R203M, and possibly also N:G215C, to modify the phosphorylation dynamics in the SR-rich region and therefore also the bindings to various 14-3-3 isoforms (https://www.biorxiv.org/content/10.1101/2020.12.26.424450v2.full).  I don't think it's yet know how the N dimers are assembled into RNPs, or even what the exact stoichiometry of an RNP is, though there's some progress on these fronts ( https://onlinelibrary.wiley.com/doi/10.1002/pro.3909, https://www.cell.com/cell/fulltext/S0092-8674(20)31159-4 ).  D377Y (which has been repeatedly reinvented) is in the C-tail ("spacer B / N3") region and may affect the formation of these higher-order N assemblies.  Any insight you might have into how these mutations relate to these structures, and what motifs in the nsp4/nsp6 transmembrane pore might interact with them, would be of great interest.

**Comment by zach-hensel** [comment]
N:del214/215 sequences have more than tripled in UK since I posted 9 days ago and is a majority of recent sequences in Singapore so I think responsible for the current large cluster. Could very well be noise but something to keep an eye on. Also possibly relevant is G214C in C.37; anything with an advantage in Peru is notable though the giant S deletion is more notable. Possibly disrupting phosphorylation confers a small advantage based on the number of (occasionally large) deletions and mutations between S:202 and S:215.

**Comment by FedeGueli** [comment]
Just a little update on this subclade:
it was mentioned in the  PHE technical briefing 19:
"the phylogeny of Delta in the UK, which is dominated by a large distinct 
clade. The clade has distinguishing mutations outside spike with uncertain biological 
significance, including NSP3: A488S, P1228L, P1469S; NSP4: D144D, V167L, T492I; 
NSP6: T77A, V120V; NSP14:A394V; ORF7b: T40I; N: G215C. The dominance of this clade 
in the UK may relate to epidemiological or biological effects or both. Further investigations 
are being undertaken"
![Screenshot_2021-07-24-17-17-33-050_com google android apps docs](https://user-images.githubusercontent.com/87669813/126873094-5becf151-94d4-451f-8d65-f4611124e0ea.jpg)

**Comment by zach-hensel** [comment]
It was weird to see this list missing T95I (I think, but not certain, in most but not all of this) yet T95I mentioned for the new VOI given that it's in that VOI and some others. I think not very important but also not unimportant.

> The clade has distinguishing mutations outside spike with uncertain biological
> significance, including NSP3: A488S, P1228L, P1469S; NSP4: D144D, V167L, T492I;
> NSP6: T77A, V120V; NSP14:A394V; ORF7b: T40I; N: G215C.

**Comment by mkedwards** [comment]
Note also that this subclade has become dominant in the sequences coming out of Bangladesh, which has been having a terrible surge in recent weeks.  I don't think this is just a founder effect.

**Comment by lukaszgit** [comment]
Yes, there seems to be a major division within "Delta" variant. Congratulations for noticing it early. It can be shown on phylogenetic trees and by clustering based on Jaccard distance between sets of mutations. The sub-lineage which you noticed seems to be growing much faster than the rest of "Delta" in every location we checked.

Here is the % of this sub-lineage within all "Delta" sublineages
![image](https://user-images.githubusercontent.com/12917655/127691399-e6972d88-b242-49b3-b4f8-8abea3673f63.png)

**Comment by lukaszgit** [comment]
What we tried was clustering of all Delta genomes from GISAID based on the Jaccard distance between their combinations of mutations (we included only protein-altering mutations). We obtained this:
![image](https://user-images.githubusercontent.com/12917655/127692195-0e25b2b5-7299-4e2d-b62a-99d17a4f1e5a.png)

**Comment by lukaszgit** [comment]
And then checked the mutations most characteristic for the 2 major clusters there (the bigger one is Cluster 1)
![image](https://user-images.githubusercontent.com/12917655/127693338-4782d895-5abe-4c88-b274-ad99f85d1999.png)

**Comment by lukaszgit** [comment]
These are very similar to what was already discussed here so would also say that there is a strong "case" for defining a new lineage containing a big part of the current B.1.617.2 (and probably AY.1 and some of AY.3 ?)

**Comment by FedeGueli** [comment]
Hi @lukaszgit thank you for your analysis: the cluster 2 in your table has been previously proposed as lineage in ISSUE #112 and currently it is still open.

**Comment by lukaszgit** [comment]
Hi, thanks !
I did not notice #112

Yes, definitely current "Delta" lineages can be improved.
It also probably suggests the importance of mutations in proteins other than Spike.

**Comment by chrisruis** [comment]
Thanks all for the submission and discussion. We're currently working on fitting all of B.1.617.2 into the Pango rules and will hopefully have an update soon. I'll close this one for now but potentially link back in once we have the update
