### ISSUE TITLE
Two BQ aliases, should be split

### ISSUE THREAD

**Issue by joshuailevy** [cov-lineages/pango-designation#1022]
Hi all, 
There's two BQs now. We should probably create a new alias for one of them. See https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.json

Best,
Josh

**Comment by corneliusroemer** [comment]
Thanks for raising this so quickly @joshuailevy  - it's a typo - the BA.2.75.4 one is supposed to be BR 🙃

**Comment by joshuailevy** [comment]
Of course! Thanks for the quick fix @corneliusroemer!
