### ISSUE TITLE
BA.5.2.1 with ORF1b:L314F and S:V6F [37 seq as of 2022-09-03, mostly Denmark and Italy]

### ISSUE THREAD

**Issue by ndkling** [cov-lineages/pango-designation#1023]
Proposal for a sublineage of BA.5.2.1
Earliest sequence: 2022-07-07 (Germany, EPI_ISL_13944997, Slovenia, EPI_ISL_14240915)
Countries detected: Mostly Denmark and Italy, but others in Europe and USA

Continuing my tour of ORF1b:L314 mutations, ORF1b:L314F has occurred multiple times within BA.5.2.1 (and BA.5.1, which I still need to look at).  A larger cluster of BA.5.2.1 with ORF1b:L314F alone occurred but appears to have stalled in recent weeks.  The mutation arose again in a new cluster that also carries S:V6F on the same branch.

It's still too early to determine whether this marks a clear epidemiological event, but it's demonstrating a substantial growth advantage over its parental BA.5.2.1 strain with unusual mutations, so I think it merits watching over time in an issue.

Interestingly, Eta([B.1.525](https://github.com/cov-lineages/pango-designation/issues/4)) included ORF1b:314F as a defining mutation.

Genomes:

[ORF1bL314F+SV6F.csv](https://github.com/cov-lineages/pango-designation/files/9483508/ORF1bL314F%2BSV6F.csv)

obtained through covSPECTRUM with the following query:

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladeQcOverallScoreTo=29&variantQuery=nextcladePangoLineage%3ABA.5.2.1+%26+ORF1b%3A314F+%26+S%3AV6F&

Evidence:

Clusters very cleanly with all samples being called as BA.5.2.1 by UShER.  I have no idea why Nextstrain displays ORF1ab:4715S both on the tree and in isolates instead of F ([no ORF1b:314S in BA.5.2.1 in covSPECTRUM](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladeQcOverallScoreTo=29&variantQuery=nextcladePangoLineage%3ABA.5.2.1+%26+ORF1b%3A314S&)).  If anyone does, I'd like to learn.

![ORF1bL314F+SV6F](https://user-images.githubusercontent.com/82973333/188290093-beda7ce8-8ead-4cb2-88f7-c24a0baa5209.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_28dc8_3ca810.json?branchLabel=aa%20mutations&c=pango_lineage&label=nuc%20mutations:C5284T

Growth advantage:

It's too early for me to put faith in the growth trajectory, but it looks strong at present against both background:

![vsBackground](https://user-images.githubusercontent.com/82973333/188289994-3713ae99-2688-417e-a674-d63b39b551b0.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=ORF1b%3A314F%2CS%3AV6F&nextcladePangoLineage=BA.5.2.1*&

and against BA.5.2.1:

![vsBA 5 2 1](https://user-images.githubusercontent.com/82973333/188289991-fa7ac5be-4726-4a84-a453-b41b05ea6b5f.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.1&variantQuery1=nextcladePangoLineage%3ABA.5.2.1+%26+ORF1b%3A314F+%26+S%3AV6F&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
This is the nuc mutation that gives Orf1b:L314F, probably Usher read it in Orf1b:P314 background and that gives it >S 
But really i could be wrong. 
![Schermata 2022-09-04 alle 01 47 04](https://user-images.githubusercontent.com/87669813/188290888-49bacafe-eb22-482a-b2d6-b7d5151bc9fe.png)

Good catch, 
it seems fast vs BA.5.2* + Orf1b:1050N  (Please remember to add always the * to your baselinecause if you dont put it you are confronting it to BA.5.2.1 less all the designated BF.s!)
Consider that growth advantage become stable and reliable usually after 100-200sequences  :

https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2*+%26+orf1b%3A1050N&variantQuery1=nextcladePangoLineage%3ABA.5.2.1+%26+ORF1b%3A314F+%26+S%3AV6F&analysisMode=CompareToBaseline&

**Comment by ndkling** [comment]
Thank you so much for the clarification and help, like always, @FedeGueli!  Your explanation makes perfect sense and I think you're right.

There are only 45 total sequences so far, so we'll see where the growth rate stabilizes.  I will be surprised if it remains this high, but it seems like it'll fare better than the other BA.5.2.1 + ORF1b:314R cluster did.

**Comment by corneliusroemer** [comment]
Bit too small I'd say. Let's reopen if it grows faster or gets an interesting sublineage.

**Comment by ndkling** [comment]
Up to 63 good+ and 80 total sequences.  Global growth advantage 36% (CI 28-45%) over background and 29% (CI 20-38%) over BA.5.2.1.
