### ISSUE TITLE
BA.5.2 + Orf1b:1050N with S:K444R circulating globally (147 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1025]
Here i want to propose another sublineage of BA.5.2 with S: K444R

Defining mutations:
BA.5.2 + 12310A + orf1b:1050N + 27513T +27012T + S:444R

Tree
![Schermata 2022-09-04 alle 10 12 29](https://user-images.githubusercontent.com/87669813/188304038-5220ac63-bac3-4212-8b7f-961900e7d741.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_a014_3dd820.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A22893G

It is very hard to establish a reliable CovSpectrum query or Gisaid Query for this one cause it starts directly from the politomy of main branch of BA.5.2

I suggest to designate it looking at growth advantage usually conferred by S:K444 mutations and specifically by S:444R (Bf.16)

Countries:
![Schermata 2022-09-04 alle 10 15 35](https://user-images.githubusercontent.com/87669813/188304167-5b9fa381-bfa8-44d0-bd43-1d3e497bc55b.png)

Nr of sequences  from Usher : 101

Gen Bank list of sequences: 

OP166543.1
OP241129.1
OX260796.1
OX237538.1
OX274550.1 
OX275355.1
OX275936.1
OX279457.1
OX277428.1
OX236546.1
OX247358.1
OX238850.1
OX277605.1
OX280866.1
OX279098.1
 
 <details>
<summary>Expand for EPI_ISLs</summary>

  ```
  USA/OH-CDC-LC0804343/2022\|OP166543.1\|2022-07-21
  Germany/NI-RKI-I-931743/2022\|EPI_ISL_14407722\|2022-07-04
  Germany/NI-RKI-I-930028/2022\|EPI_ISL_14404607\|2022-07-19
  France/ARA-HCL722003641701/2022\|EPI_ISL_14528442\|2022-07-25
  USA/TX-HMH-M-111703/2022\|EPI_ISL_14552448\|2022-08-08
  USA/IN-CDC-STM-HY4D7866K/2022\|EPI_ISL_14657005\|2022-08-08
  England/PHEC-YYGZTHB/2022\|2022-08-21
  Sweden/01_SE100_22CS507541/2022\|EPI_ISL_14710875\|2022-08-18
  England/QEUH-3F70EEB/2022\|2022-08-21
  Ireland/LD-Enfer-230822006_B6/2022\|EPI_ISL_14777965\|2022-08-23
  England/PHEC-YYFZ1PY/2022\|2022-06-27
  hCoV-19/Mongolia/Darkhan-5283/2022\|EPI_ISL_14807000.\|2022-08-11
  Australia/SA441487/2022\|EPI_ISL_14723246\|2022-08-05
  Malaysia/C19UMB2338/2022\|EPI_ISL_14590736\|2022-07-28
  Germany/BW-FR3811/2022\|EPI_ISL_14518116\|2022-07-05
  Germany/NW-RKI-I-899629/2022\|EPI_ISL_13933587\|2022-06-26
  France/NOR-CHURouen-77032411/2022\|EPI_ISL_14766344\|2022-08-19
  France/IDF-HCL022141807902/2022\|EPI_ISL_14754083\|2022-08-19
  USA/NJ-CDC-LC0820152/2022\|OP241129.1\|2022-08-03
  USA/NY-PRL-220808_01L15/2022\|EPI_ISL_14461691\|2022-08-05
  France/CVL-HCL722003864101/2022\|EPI_ISL_14754311\|2022-08-16
  France/HDF-IPP47915/2022\|EPI_ISL_14439303\|2022-08-01
  India/AS-ICMR-NIV-INSACOG-G-12144/2022\|EPI_ISL_14402537\|2022-07-11
  India/MH-ICMR-NIV-INSACOG-G-11534/2022\|EPI_ISL_14402467\|2022-07-10
  India/WB-INSACOG-1931503199264/2022\|EPI_ISL_14733734\|2022-06-20
  Luxembourg/LNS2705081/2022\|EPI_ISL_13666819\|2022-06-20
  Luxembourg/LNS4062802/2022\|EPI_ISL_13667277\|2022-06-20
  England/LSPA-3F57EAE/2022\|2022-08-07
  Scotland/LSPA-3F0713B/2022\|OX260796.1\|2022-07-22
  England/PHEC-YYGATEE/2022\|2022-08-27
  Switzerland/GE-HUG-38852726/2022\|EPI_ISL_14561163\|2022-08-05
  England/PHEC-YYGAD1B/2022\|2022-08-23
  England/PHEC-YYGZX1Z/2022\|2022-08-20
  Scotland/SCOT-17924/2022\|2022-07-30
  England/PHEC-YYG1YP5/2022\|2022-07-30
  England/PHEC-YYGIY1K/2022\|2022-08-13
  England/PHEC-YYGYNIP/2022\|2022-07-05
  England/PHEC-YYGAMZX/2022\|2022-08-25
  England/PHEC-YYGSI4D/2022\|2022-08-18
  England/QEUH-3F74DDB/2022\|2022-08-20
  England/QEUH-3F74E8D/2022\|2022-08-20
  England/PHEC-YYGTUEW/2022\|2022-07-27
  England/PHEC-YYGTUBN/2022\|2022-07-26
  England/PHEC-YYGT65N/2022\|2022-07-30
  England/PHEC-YYG1R54/2022\|2022-07-28
  England/PHEC-YYGUZSX/2022\|2022-08-02
  England/PHEC-YYGP64P/2022\|2022-07-26
  England/PHEC-YYGE544/2022\|2022-07-16
  England/PHEC-YYGE5UE/2022\|2022-07-17
  England/LSPA-3F54506/2022\|2022-08-06
  England/PHEC-YYGUZ69/2022\|2022-08-02
  England/PHEC-YYGW9K6/2022\|2022-08-12
  Denmark/2022\|OX237538.1\|2022-07-08
  Denmark/DCGC-551357/2022\|OX274550.1\|2022-07-14
  Denmark/DCGC-551928/2022\|EPI_ISL_14046317\|2022-07-18
  Denmark/DCGC-552101/2022\|OX275355.1\|2022-07-18
  Denmark/DCGC-552164/2022\|OX275936.1\|2022-07-18
  Denmark/DCGC-555042/2022\|OX279457.1\|2022-07-24
  Denmark/DCGC-556343/2022\|EPI_ISL_14197922\|2022-07-23
  Denmark/DCGC-555798/2022\|OX277428.1\|2022-07-23
  Denmark/2022\|OX236546.1\|2022-07-08
  CzechRepublic/NAT-22-28594/2022\|EPI_ISL_14440079\|2022-07-11
  CzechRepublic/FNHK-Ps-006203/2022\|EPI_ISL_14701398\|2022-07-19
  Finland/THL-202215781/2022\|EPI_ISL_14298032\|2022-07-08
  Denmark/DCGC-559841/2022\|EPI_ISL_14390500\|2022-08-04
  England/QEUH-3EECAC9/2022\|OX247358.1\|2022-07-14
  Denmark/2022\|OX238850.1\|2022-07-11
  Netherlands/NH-inBiome-212047/2022\|EPI_ISL_14773240\|2022-08-23
  Belgium/UZA-UA-65738756/2022\|EPI_ISL_14665169\|2022-08-16
  Denmark/DCGC-555955/2022\|OX277605.1\|2022-07-23
  Denmark/DCGC-557731/2022\|OX280866.1\|2022-07-30
  Denmark/DCGC-555756/2022\|OX279098.1\|2022-07-23
  Sweden/4021077155VN/2022\|EPI_ISL_14227707\|2022-07-14
  Sweden/01_SE100_22CS506649/2022\|EPI_ISL_14262493\|2022-07-22
  Sweden/01_SE100_22CS506633/2022\|EPI_ISL_14262509\|2022-07-21
  Russia/MOS-CRIE-7765014018/2022\|EPI_ISL_14423230\|2022-07-26
  Sweden/01_SE100_22CS507120/2022\|EPI_ISL_14488260\|2022-08-04
  Israel/SMC-7101246/2022\|EPI_ISL_14687045\|2022-08-18
  Germany/BY-RKI-I-961177/2022\|EPI_ISL_14696865\|2022-08-22
  Sweden/1260688689VN/2022\|EPI_ISL_14227783\|2022-07-18
  Belgium/ULG-27576/2022\|EPI_ISL_14070800\|2022-07-18
  Denmark/DCGC-567783/2022\|EPI_ISL_14602935\|2022-08-16
  Sweden/01_SE100_22CS105117/2022\|EPI_ISL_14561460\|2022-08-05
  Sweden/01_SE100_22CS105093/2022\|EPI_ISL_14561423\|2022-08-05
  Sweden/01_SE100_22CS105095/2022\|EPI_ISL_14561442\|2022-08-04
  Sweden/48630950X5/2022\|EPI_ISL_14544302\|2022-07-25
  Sweden/4021073900VN/2022\|EPI_ISL_14544997\|2022-07-22
  Austria/LB-R00094-S156/2022\|EPI_ISL_14492025\|2022-08-09
  Sweden/01_SE100_22CS507014/2022\|EPI_ISL_14488291\|2022-07-30
  Sweden/01_SE100_22CS506743/2022\|EPI_ISL_14262415\|2022-07-24
  Sweden/01_SE100_22CS506624/2022\|EPI_ISL_14262478\|2022-07-23
  Sweden/01_SE100_22CS506562/2022\|EPI_ISL_14262479\|2022-07-23
  Sweden/SUS0014543/2022\|EPI_ISL_14754727\|2022-08-17
  Sweden/SUS0014539/2022\|EPI_ISL_14754723\|2022-08-17
  Sweden/4072732564/2022\|EPI_ISL_14666481\|2022-08-15
  Sweden/01_SE100_22CS507561/2022\|EPI_ISL_14710833\|2022-08-20
  Sweden/01_SE100_22CS507088/2022\|EPI_ISL_14488248\|2022-08-06
  Sweden/01_SE100_22CS507260/2022\|EPI_ISL_14561513\|2022-08-07
  Sweden/01_SE100_22CS507395/2022\|EPI_ISL_14579103\|2022-08-11
  Sweden/01_SE100_22CS507508/2022\|EPI_ISL_14710840\|2022-08-20
  Sweden/01_SE100_22CS507089/2022\|EPI_ISL_14488258\|2022-08-06
  Sweden/01_SE100_22CS507472/2022\|EPI_ISL_14711006\|2022-08-15
  ```

</details>

**Comment by FedeGueli** [comment]
109 sequences as today:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1b%3AP85L%2Corf1b%3AN1700S%2CS%3AK444R%2COrf1b%3AT1050N&

**Comment by FedeGueli** [comment]
There is a clear sublineage of this one linked to Sweden defined by one further Orf1b mutation: Orf1b:N1700S
![Schermata 2022-09-05 alle 20 50 17](https://user-images.githubusercontent.com/87669813/188502173-13b59d5b-f088-42aa-a10e-7c76c900e3d9.png)
To be sure to generate the right tree of this lineage (the one proposed here) a good tip could be to use the query from Gisaid: NSP13_T127N,Spike_K444R, NSP14 N176S ( which finds Sweden sublineage only) and from those sequences build the Usher tree.

**Comment by FedeGueli** [comment]
124 sequences as today: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1436b_d00cd0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22893G
![Schermata 2022-09-10 alle 23 36 55](https://user-images.githubusercontent.com/87669813/189502585-94edfdca-7fc4-4291-bca1-2d648081e4a5.png)
The Orf1b:N1700S branch of this sublineage  reached 44 sequences with some clusters defined by additional spike mutations
![Schermata 2022-09-10 alle 23 37 49](https://user-images.githubusercontent.com/87669813/189502608-df589152-9be4-4e99-9806-75b97477e583.png)

@corneliusroemer not super urgent but also looking at the main branch there are some geoclustered sequences with NTD mutations as S:N148T in Uk, one with a RBD mutation  S:D427Y in Sweden , one with a FCS mutation S:A688V .
I suggest a designation as a whole or starting with the "swedish branch" waiting if some of the other branches show signs of growth advantage ( I personally dont like to jump to Sons/siblings but better than none )

**Comment by FedeGueli** [comment]
@corneliusroemer this reached 147 sequences: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a4fc_109970.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22893G

**Comment by corneliusroemer** [comment]
We need to look into whether this could be in fact a homoplasic branch - where Usher pulls all the S:444R together, when in fact the sequence of mutations was the other way round: first the branches, then S:444R.

Way to check: see whether there are branches in the tree without S:444R that have the mutations that come off the S:444R node.

**Comment by FedeGueli** [comment]
thx @corneliusroemer i will do as soon as possible

**Comment by corneliusroemer** [comment]
Thanks this does look interesting. If I search for BA.5.2 + ORF1b:1050N and S:444R I get ~400 sequences worldwide and growth advantage over ORF1b:1050N of about 30%/week.

So quite interesting - if it were to acquire something else. It's ~2% in Sweden. So I guess worthy of designation _if_ we can figure out monophyletic branches.

**Comment by corneliusroemer** [comment]
There's a separate South Korea branch that is not part of this that has ~30 sequences.

Nextclade will not know the difference so miscall it as also this lineage - but I guess no big harm done.

**Comment by FedeGueli** [comment]
thx Cornelius.

**Comment by FedeGueli** [comment]
> Thanks this does look interesting. If I search for BA.5.2 + ORF1b:1050N and S:444R I get ~400 sequences worldwide and growth advantage over ORF1b:1050N of about 30%/week.
> 
> So quite interesting - if it were to acquire something else. It's ~2% in Sweden. So I guess worthy of designation _if_ we can figure out monophyletic branches.

3 sequences from Massachussets with S:R346T
