### ISSUE TITLE
BA.5.2.18 (S:444R)  sublineage with S:R346T   (15 sequences: Denmark, Pakistan, Usa, Canada , Israel)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1026]
(**Edited**  As noticed by @JosetteSchoenma the Luxembourg and New Zealand sequence are not part of this sublineage)

Here i want to propose a very small sublineage of BA.5.2 with S:346T (22599C) and S:K444R (A22893G)

**Edited**  Refer to the tree analyzed in the comments by @JosetteSchoenma 
(Usher tree puts in a small branch with G12310A +Orf1b:1050N +27513T+ S:346T (22599C) but without 27012T :
![Schermata 2022-09-04 alle 10 38 38](https://user-images.githubusercontent.com/87669813/188305039-2f4be669-ed36-4cee-836e-c1dd8112aa02.png)

But the tree is not clear as it seems at first look, cause 27012T is acquired then just after a T27360C mutation that is reverted back to 27360T just after  acquiring S:K444R (A22893G):
![Schermata 2022-09-04 alle 10 39 18](https://user-images.githubusercontent.com/87669813/188305067-d380bec0-3724-430d-868e-b76471e1c000.png) 

@AngieHinrichs your help is needed here :https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_a014_3dd820.json?branchLabel=nuc%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G22599C

This a bit messy tree  brings to 4 samples from 3 continents and 4 countries bearing S:346T and S:444R in the backbone of the highest transmissible main BA.5 sublineage ( BA.5.2 + Orf1b:1050N):
so i think it is correct to monitor publicly being both spike mutations R346T and K444R able to confer a growth advantage in many different BA.5 designated lineages.)

Sequences id:
Denmark/DCGC-569039/2022|EPI_ISL_14690614|2022-08-20
Pakistan/NIH-B86-S9/2022|EPI_ISL_14751444|2022-08-25
( Edited
 **NO**
Luxembourg/LNS6637799/2022|EPI_ISL_14756571|2022-08-17
NewZealand/22XA1745/2022|EPI_ISL_14635713|2022-08-15
**NO**)

**Comment by FedeGueli** [comment]
Gisaid query: NSP13_T127N,Spike_R346T,Spike_K444R

**Comment by FedeGueli** [comment]
One more sequence uploaded today from Denmark :

EPI_ISL_14809934
collection date 29/08/22 it clusters with the other one sampled in Denmark.
![Schermata 2022-09-05 alle 18 58 48](https://user-images.githubusercontent.com/87669813/188492482-0d25fe4e-2a03-4637-a416-e7c315b4e962.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_433f4_62a0c0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22893G

@corneliusroemer i would flag this one.

**Comment by FedeGueli** [comment]
One more sequence from Denmark: 

EPI_ISL_14884588

**Comment by FedeGueli** [comment]
One more sequence from Denmark:

EPI_ISL_14935155
--

**Comment by corneliusroemer** [comment]
Bit too small I would say for designating at this point

**Comment by FedeGueli** [comment]
No squence uploaded.  closimg it for now

**Comment by FedeGueli** [comment]
@josetteshoenma found 4 more of this one uploaded  today .

@corneliusroemer  so.i have reopened it.

**Comment by JosetteSchoenma** [comment]
Yes. Four more BA.5.2 with R346T and K444R were uploaded to GISAID from Denmark today. But I believe the tree is built differently now, clustering one sample from Pakistan and  from Denmark. Not including the one from Luxembourg and New Zealand on this branch. I will try and find where those are now.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_11702_825210.json?branchLabel=aa%20mutations&label=nuc%20mutations:G15957T,G22599C
![image](https://user-images.githubusercontent.com/94831035/191107037-a3425cb8-a2ac-4f4b-a63a-c4843d693b9e.png)
![image](https://user-images.githubusercontent.com/94831035/191107201-f621ca4a-fb06-4eac-b063-fe768522fbba.png)

**Comment by JosetteSchoenma** [comment]
The one from Luxembourg does not seem to have R346T and the one from New Zealand has been put elsewhere on the tree on its own.
![image](https://user-images.githubusercontent.com/94831035/191109114-a173c9b2-d2d7-4384-9eba-232fb1864ed4.png)

**Comment by JosetteSchoenma** [comment]
This query should work. BA.5.2*, S:K444R, S:R346T, G15957T.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AK444R%2CS%3AR346T&nucMutations=C15957T&nextcladePangoLineage=BA.5.2*&
5 now. The 4 new ones from today are not up there yet. First sample 20th of August from Denmark

**Comment by AngieHinrichs** [comment]
@JosetteSchoenma a quick note about the UShER web interface: if you are looking for a sequence that is already in the tree, you don't have to upload FASTA for it, you can paste in its EPI_ISL_ ID or name instead.  That is a bit quicker, especially when you have a long list.

**Comment by JosetteSchoenma** [comment]
Thank you. And they would not each be showing twice in the tree either, I guess. I will try that next time.

**Comment by FedeGueli** [comment]
@JosetteSchoenma would you like to open a new issue for this one?

It seems potentially relevant but this proposal is a mess. So to me very ok if u want to do a new one with correct tree and correct sequences

**Comment by FedeGueli** [comment]
@JosetteSchoenma @AngieHinrichs 

Now Usher have placed this entire lineage as sublineage of BA.5.2.18 (correctly i think)
New Tree:
![Schermata 2022-09-28 alle 00 30 15](https://user-images.githubusercontent.com/87669813/192648999-cf7f1f3c-2777-435f-b733-29ff4959edb5.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1bfcf_377480.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G22599C
3 more sequences from massachussets.

**Comment by FedeGueli** [comment]
Two more sequences of this one from two new countries Israel (EPI_ISL_15171101) and Canada (EPI_ISL_15152938) found with this NSP13_T127N,Spike_R346T,Spike_K444R that works very well,
 @InfrPopGen  @corneliusroemer  total now is 15 i think a designation could come for this one bringing two of the core escape mutations circulating.

**Comment by FedeGueli** [comment]
now proposed in #1170

**Comment by FedeGueli** [comment]
Designsted  CR.1
