### ISSUE TITLE
Proposal to withdraw lineage BA.5.1.13 due to being defined by artefacts

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1029]
BA.5.1.13 was designated despite having a suspicious S:440 reversion to reference.

The other defining mutation is very homoplasic and linked to one lab that opened 3 issues for designation.

Overall, the evidence for the defining mutation ORF1a:I880V being a bioinformatics/sequencing artefact is overwhelming - at least in my opinion.

See more information in this comment to the other issue: https://github.com/cov-lineages/pango-designation/issues/956#issuecomment-1236364621

In the future, it would be good to be critical of issues if:
- there are reversion to reference in more than a small proportion of to be designated sequences
- most sequences come from one lab
- the mutation seems to appear in many sequences from that lab in different phylogenetic backgrounds
- the mutation has been observed at somewhat low rates in a geographically non-connected region (in this case Bahrain, Germany, Brazil) over an extended period of time

All the criteria above are fulfilled so the withdrawal should be a simple decision.

<img width="1893" alt="image" src="https://user-images.githubusercontent.com/25161793/188321603-c77511ed-f9a2-4b9b-9709-5136476ecd29.png">

@alex-ranieri You may want to look into what's going on in your pipeline regarding this mutation and also the reversion at S:440 - maybe it's a primer site? What primer scheme are you using? You seem to use Illumina according to GISAID metadata.

**Comment by bwlang** [comment]
ARTIC v3 has a likely disrupted primer at this locus (see image).
I think people should not be using ARTICv3 anymore.

<img width="981" alt="image" src="https://user-images.githubusercontent.com/61636/188323244-31b87975-d5c3-48b5-ac9d-14575a28f30b.png">

**Comment by bwlang** [comment]
880 also overlaps with an ARTIC v3 primer (9 RIGHT). That might be tricky to properly clip since they are actually 2 primers very nearby (ivar trim and samtools ampliconclip do handle this situation correctly if provided with both primer entries).
<img width="748" alt="image" src="https://user-images.githubusercontent.com/61636/188323427-54d9a630-4b46-4aa9-86d6-627ab858551e.png">

**Comment by corneliusroemer** [comment]
What's the reason people would still be using Artic V3?
Leftover stock?
Or does the price increase for every version?

**Comment by Mydtlwn** [comment]
I think in order to avoid big problems, I think it may be better to mark and add a symbol than to cancel it.

**Comment by Mydtlwn** [comment]
I think we can use the first letter of the word "questionable" as a suffix, such as Ba.5.1.13Q。

**Comment by bwlang** [comment]
primers are cheap compared to other steps. I think people are using older primers due to difficulties (real or perceived) in making changes in some environments.

**Comment by corneliusroemer** [comment]
Thanks, I see, so the cost of upgrading a system - same as why banks are
still running on COBOL on mainframes.

**Comment by corneliusroemer** [comment]
Big problems like?

It's normal to withdraw lineages that turn out to not be monophyletic or
due to artefacts or in the wrong place. We've done it before.

**Comment by alex-ranieri** [comment]
Thank you all for pointing this out. 
We are using Arctic V3. @corneliusroemer, I think it is leftover stock. I'll check with the sequencing team to confirm. 
The strange is, that we've assembled a lot of sequences and those mutations didn't appear. 
We'll reassemble those genomes passing the primer sequences to ivar (we are already using this tool in our pipeline).

**Comment by corneliusroemer** [comment]
Withdrawn in b29ee84a480352b4c265cde68843cfbe0a9ead20

@alex-ranieri - thanks for checking! Maybe you can get to the bottom of this and enlighten us on what happened.

**Comment by bwlang** [comment]
@alex-ranieri :
I'm not sure if you're using the NEB kit, but if so we are happy to ship new primers at no charge.

**Comment by alex-ranieri** [comment]
@bwlang, I've checked with the sequencing team and they are using Illumina's COVIDSeq kit. 
The Arctic V3 primers were being used due to contractual reasons. I suggested to our managers to start using V4!
@corneliusroemer, I've confirmed that, in fact, the mutations were caused by artifacts. We've improved our bioinformatics pipeline. I'm very sorry for the inconvenience. 
Thanks again!
