### ISSUE TITLE
BA.4.6 sublineage with S:A264T circulating in Usa (145 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1030]
Here i want to propose a sublineage of BA.4.6 circulating in USA showing a slight advantage over the parental lineage.

Defining mutations: BA.4.6 + S:A264T (G22352A)

Gisaid query :  N_P151S,Spike_A264T, Spike_r346T

Sequences: 78
First sequence: 2022-06-17 Missouri, Us EPI_ISL_13705014
Last sequence: 2022 -08-22 NYC, Us       EPI_ISL_14798082
List of good quality sequences:
[contributors.csv](https://github.com/cov-lineages/pango-designation/files/9485584/contributors.csv)

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4211d_51c860.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G22352A
![Schermata 2022-09-05 alle 00 00 09](https://user-images.githubusercontent.com/87669813/188335076-556d4cab-6afe-4a72-a7d2-cc050a57a76c.png)

Covspectrum query BA.4.6* nextclade + S:264T :
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AA264T&nextcladePangoLineage=BA.4.6*&nextcladePangoLineage1=BA.4.6*&

it is not clear its growth advantage over parental BA.4.6 
but still represents the third sublineage of BA.4.6 defined by a spike mutation during the past month after S:5F and S:152l
:https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?nextcladePangoLineage=BA.4.6*&aaMutations1=S%3AA264T&nextcladePangoLineage1=BA.4.6*&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
@corneliusroemer wrong label!!

**Comment by FedeGueli** [comment]
11 sequences uploaded yesterday from US: 4 Georgia, 2 Florida, and then Indiana, Illinois, Maryland  , Missouri , Connecticut

@InfrPopGen @corneliusroemer  i think this deserves a designation.

**Comment by FedeGueli** [comment]
8 new sequences uploaded from US . tot 97 as today.

**Comment by FedeGueli** [comment]
106 as today on Gisaid

**Comment by FedeGueli** [comment]
115 Sequences, still little or no exports from USA

**Comment by FedeGueli** [comment]
122 seqs. Steady growth just in US

**Comment by corneliusroemer** [comment]
It's not growing that fast but we haven't really broken down BA.4.6 enough yet so why not designate it.

I'll suggest it for designation for @InfrPopGen @aq-sun

**Comment by FedeGueli** [comment]
137 seqs as today. Probably it is correct closing this one? @corneliusroemer

**Comment by FedeGueli** [comment]
145 seqs as today

**Comment by FedeGueli** [comment]
@corneliusroemer @InfrPopGen 

this has been accepted and then it has never been designated.

To.me is ok to close without designating. lemme know your thoughts.

**Comment by InfrPopGen** [comment]
> @corneliusroemer @InfrPopGen
> 
> this has been accepted and then it has never been designated.
> 
> To.me is ok to close without designating. lemme know your thoughts.

I think it can be closed, as it has been in steady decline in US (rel to parent) over the past month, and it appears to have no growth advantage.

**Comment by FedeGueli** [comment]
Done
