### ISSUE TITLE
Sublineage of BA.5.10 with S:R346T 15 sequences - 3 continents 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1031]
BA.5.10 is a sublineage of BA.5  defined by S:A262S (beyond other AA mutations as E:S50G), likely  it emerged in Philippines,
and it is from Philippines that was intercepted by Singaporean airport genomic surveillance one sequence bearing S:346T too.

Looking at it and at another very recent sample uploaded today from New York i found that this is likely a new  sublineage of BA.5.10 already circulating at good levels , despite we have only 9 samples, they are from Canada (Surveillance of international border crossing by air travel) , Denmark, Singapore (travel from Philippines), Usa :
this means 3 continents and 2 samples travel related suggesting high or growing prevalence somewhere likely in Philippines.

All the samples have been collected after 4th of August so this lienage is very recent and it points further to high or gorwoing prevalence in an undersampled area.

Gisaid query  ( _E_S50G,Spike_A262S,Spike_R346T_) finds 9 sequences:

EPI_ISL_14393203 (First, Denmark 04/08/22)
EPI_ISL_14455894
EPI_ISL_14610908
EPI_ISL_14610912
EPI_ISL_14611100
EPI_ISL_14735877
EPI_ISL_14762091
EPI_ISL_14802573
EPI_ISL_14807954 (Last, NYC 22/08/22 )

Defining mutations: C9803T, Orf1b:T2432I , S:R346T
Tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_337b3_5333b0.json?label=nuc%20mutations:G22599C
![Schermata 2022-09-05 alle 01 34 00](https://user-images.githubusercontent.com/87669813/188337771-d6cdde59-4776-4e0f-825c-604b9a6e96f3.png)

CovSpectrum query (BA.5.10* (Nextclade) + C9803T + Orf1b:T2432I, S:R346T) finds 6 sequences as today
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AT2432I%2CS%3AR346T&nucMutations=C9803T&nextcladePangoLineage=BA.5.10*&aaMutations1=S%3A1070V&nextcladePangoLineage1=BA.5.1.12*&

**Comment by FedeGueli** [comment]
Just read a new paper where S: A262S (Defining mutation of BA.5.10 ):
"In addition, A262S and T478I significantly enhanced the utilization of various mammals ACE2."

https://onlinelibrary.wiley.com/doi/10.1002/jmv.28116

Maybe an extra attention should be paid on BA.5.10 and its sublineages.

**Comment by FedeGueli** [comment]
New sequence from California 

EPI_ISL_14825489 collected on 15/08/22

**Comment by FedeGueli** [comment]
It doesnt seem to slow fast , i'll close this one for now. I'll update the issue and reopen it if something new happens.

**Comment by FedeGueli** [comment]
One more from Texas.

**Comment by FedeGueli** [comment]
15 Sequences as today.
4 newly uploaded.
I reopen this issie after the 2 sequences of this lineage sampled in South Korea from travellers related with Philippines.

Thi suggests me a growth there and subsequent spread. @corneliusroemer

**Comment by FedeGueli** [comment]
Reopened this one being BA.5.10 the fourth fastest lineage without S:346X/444X or 460K.
So S:346T in that backbone could be efficient
 Lets see if true in the next two weeks.

**Comment by corneliusroemer** [comment]
Fair point - I'll designate this one as it's growing OK and widespread internationally - link to Philippines very reasonable.
