### ISSUE TITLE
BA.5.2.1 with S:1020S with growth in Czechia [250 seq of which 100 in CZ 2022-09-05]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1036]
Looking at where S:1020S was occurring I noticed that the share of a lineage was growing rather fast in Czechia over the last few weeks. There are 4 AA mutations on top of BA.5.2.1, 3 of which are in ORF1a/b which is quite a lot.

```
S:A1020S
ORF1a:L1507F
ORF1a:T3940I
ORF1b:S220N
```

Share of this lineage as proportion of BA.5.2.1 in Czechia:
<img width="1867" alt="image" src="https://user-images.githubusercontent.com/25161793/188486922-26781b66-24c5-4627-b0c2-e37b577cb78b.png">

~~Could this be a sequencing artefact? Or a single super spreading event? I'm a bit puzzled by the peaks and troughs in share.~~

The solution is simple: We never designated a BA.5.2.1 + S:1020S but only certain branches of it. As a result, there are already 2 related lineages with BA.5.2.1 + S:1020S: BF.5 and BF.3.

Now to clean up, we should probably designate this one as close to the polytomy as possible to prevent us from having to designate ever more BA.5.2.1 + S:1020S.

<img width="1622" alt="image" src="https://user-images.githubusercontent.com/25161793/188487897-e3759a9a-cd56-4b52-bd20-4de22d081754.png">

Usher tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6f40_61e4a0.json?branchLabel=back-mutations&c=pango_lineage_usher

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.23 with 136 newly designated sequences, and 34 updated designations from BA.5.2.1. Defining mutation C4784T (ORF1a:L1507F).
