### ISSUE TITLE
Sublineage of BE.3 with S:I231T, ORF3a:D238V in USA, primarily New York state (102 seq on Sept 12)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1037]
### **Description**
**Sub-lineage of:** BE.3
**Earliest sequence:** 2022-7-5, USA, NY, New York City, EPI_ISL_13887959
**Most recent sequence:** 2022-8-26, USA, NY, New York City, EPI_ISL_14808937
**Countries circulating:** USA exclusively. 58 sequences in New York state, 17 in other US states
**Number of Sequences:** 77 on Usher Tree, 75 returned by GISAID query “N_P151S, Spike_I231T, NS3_D238V”
**Substitutions on top of BE.3:**
**Spike:** I231T
**ORF3a:** D238V
**Nucleotide:** C6568T, T22254C, A26105T

Eight BE.3 sequences from New York City were uploaded yesterday (September 4), and since those are not yet on CovSpectrum, the growth advantages below do not include them. I231T is an uncommon mutation with just 6 sequences in 2020, 91 in 2021, and 222 so far in 2022 (filtering for good sequences on CovSpectrum), and BE.3 seems to be the first lineage with it to have spread significantly. 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_496e_61d890-BE.3%2BI231T%2BORF3a-D287V.json

![image](https://user-images.githubusercontent.com/33738461/188489389-de5532e9-01b7-446a-aa91-1f11447b15c7.png)

**Evidence**
CovSpectrum: 52% (CI:35%-69%) weekly growth advantage compared to nextcladePangoLineage:BE.3* in the last three months in the USA:
![Screen Shot 2022-09-05 at 12 17 41 PM - USA](https://user-images.githubusercontent.com/33738461/188489454-ac7dc32f-542d-403a-9c7b-8d513e4c29c7.png)
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ABE.3*&variantQuery1=nextcladePangoLineage%3ABE.3*+%26+S%3AI231T&analysisMode=CompareToBaseline&

CovSpectrum: 48% (CI:27%-68%) weekly growth advantage compared to nextcladePangoLineage:BE.3** in the last three months in New York state:
![Screen Shot 2022-09-05 at 12 16 49 PM - NY state](https://user-images.githubusercontent.com/33738461/188489484-7f50e8ab-04e4-4b8b-a885-82f45ed4156e.png)

**Genomes**
[GISAID_hcov-19_ids_2022_09_05_16_22—BE.3+I231T+ORF3aD238V.csv](https://github.com/cov-lineages/pango-designation/files/9491252/GISAID_hcov-19_ids_2022_09_05_16_22.BE.3%2BI231T%2BORF3aD238V.csv)

**Comment by ryhisner** [comment]
There are now 102 sequences of this lineage and the first two outside of the USA have appeared: one from Scotland (not yet on GISAID) and one from Ontario, Canada, (EPI_ISL_14927599, collection date September 2).

**Comment by corneliusroemer** [comment]
Slow growth, and not that many sequences despite being in the US which samples a lot. So I'll close for now - let's reopen if something interesting happens inside this.

**Comment by ryhisner** [comment]
Yeah, I agree. This is slow, & probably destined to extinction in a couple months.
