### ISSUE TITLE
Proposal to withdraw lineage BA.5.1.16 due to defining mutations being sketchy

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1040]
Looking at BA.5.1.16 I investigated the two defining mutations: A2969G, G27470A

G27470A is very close to the BA.5.1 defining mutation T27438C (32 bases away), it has almost never been seen in Japan until BA.5.1 showed up. It is also extremely rare worldwide over the whole pandemic. This suggests purifying selection and that the mutation may be an artefact.

A2969G has a very artefacty signature looking at covSpectrum: it suddenly popped up in Ireland when Delta appeared and just as suddenly disappeared again. Just before, it suddenly appeared and disappeared in Germany.

<img width="1686" alt="image" src="https://user-images.githubusercontent.com/25161793/188503409-0efcaaeb-beec-49f9-a779-25b441294ebe.png">

It also very suddenly appeared and disappeared in Russia. Suggestive of bioinformatics issue that was then resolved.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/25161793/188503559-2f70501b-e09f-4b30-aff5-0c0ebb47d964.png">

Here I'm not 100% convinced that this can't be real but I have my doubts.

**Comment by AngieHinrichs** [comment]
I'm not so sure this isn't real.  While this one is seen mostly in Japan, it has also been observed in several other countries.  Here it is colored by country, and you can see multiple countries with evidence of local transmission:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/186983/188511894-eeed58d3-49ca-458e-9c2a-ea4fa24e0d78.png">
Also, I don't see any reversions on 27470 or 2969 on that branch, which we might see if other mutations were pulling sequences in despite disagreeing on 27470 or 2969.

**Comment by corneliusroemer** [comment]
Thanks for looking at this! It's comforting that we may have some real here.

I should learn how to read the huge Usher tree live with taxonium instead
of making slow one-off Usher trees via usher.bio

So the best warning sign remains unusual clustering across geographic
boundaries. I feel like we might actually turn this into a metric that
could help spot artefacty parts of the tree!
