### ISSUE TITLE
Potential BA.5.1 Sublineage with C25006T and ORF9b:T95M (309 seqs as of 2022-11-15)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1041]
There may be a BA.5.1 sublineage with C25006T and ORF9b:T95M (C28567T) first detected in Brazil.

As of 2022-09-05, Cov-Spectrum reports 122 BA.5.1+ORF9b:95M+25006T sequences with good quality control scores:
![BA 5 1+ORF9b_95M+25006T-Counts](https://user-images.githubusercontent.com/88959107/188506940-02776d8c-fee5-4098-a851-082ffa8c0e0d.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.1+%26+ORF9b%3AT95M+%26+C25006T&nextcladeQcOverallScoreTo=29&

As of 2022-09-05 and considering only sequences with good quality control scores, Cov-Spectrum calculates notable positive growth advantages compared to BA.5.1* and BA.5& in the United States:

Growth Advantage vs. BA.5.1*: https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.1*&variantQuery1=nextcladePangoLineage%3ABA.5.1+%26+ORF9b%3AT95M+%26+C25006T&analysisMode=CompareToBaseline&nextcladeQcOverallScoreTo=29&

Growth Advantage vs. BA.5*: https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABA.5.1+%26+ORF9b%3AT95M+%26+C25006T&analysisMode=CompareToBaseline&nextcladeQcOverallScoreTo=29&

As of 2022-09-05, UShER shows all of the GenBank samples are on a single subtree:
![BA 5 1+ORF9b_95M+25006T-UShER](https://user-images.githubusercontent.com/88959107/188506904-a4a5e59f-1146-44c7-afb1-eb857ca64e22.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/09/subtreeAuspice1_genome_BA.5.1%2BORF9b_95M%2B25006T.json?c=gt-nuc_28567

First Cov-Spectrum sequence: Brazil, 2022 Week 23

First GenBank sequence: England, United Kingdom 2022-06-14 

Most Recent GenBank sequence: Minnesota, USA 2022-08-24

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at [Support-BA.5.1+ORF9b_95M+25006T.zip](https://github.com/cov-lineages/pango-designation/files/9491793/Support-BA.5.1%2BORF9b_95M%2B25006T.zip)

Note: There are different additional synonymous nucleotide mutations which produce other BA.5.1+ORF9b:95M lineages in UShER.  This proposal is for BA.5.1+25006T+ORF9b:T95M only.

**Comment by FedeGueli** [comment]
@alurqu it is quite  weird when one mutation pops up in many different lineages as i was fooled on the russian orf1b,  
cc   @corneliusroemer could you take a look at this please?

**Comment by alurqu** [comment]
@FedeGueli I've mutations pop up on multiple lineages before.  Indeed, I'm seeing something similar with BA.5.2+S:346I, but while S:346I seems like a credible mutation as of yesterday I didn't see a good rule to pull out a decent-sized BA.5.2+S:346I lineage.

I am aware of @corneliusroemer's recent tickets to withdraw lineages due to possible sequencing artifacts, and I don't have a good handle on possible sequencing artifacts, so a review for sequencing artifact risk seems reasonable.  I will note that for this proposed lineage and at this time, I count about 16 source labs in the GenBank data, CoV-Spectrum shows sequences from 17 different countries, and the GenBank sequence names indicate 15 different USA states.  With this in mind, if there is a sequencing artifact, it is likely happening in multiple geographically-distributed labs.

**Comment by corneliusroemer** [comment]
Thanks - it's a good idea to break down the BA.5.2 + ORF1b:1050N polytomy to reduce unspecific BA.5.2 calls.

This lineage seems most common in Thailand.

Please designate @InfrPopGen @aq-sun 

I've designated two large lineages without proposal that were also on that polytomy. That should help make analysis of sequences in that part of the tree easier in the future.

**Comment by alurqu** [comment]
This lineage is up to 309 good sequences but may now have fizzled out. I'm not sure if this proposal should stay open or if it would be better to close it.

**Comment by alurqu** [comment]
I'll close this. It can be reopened later if appropriate.
