### ISSUE TITLE
BA.5.3 sublineage with S:346T circulating in South Africa- 31 sequences with high prevalence in SA 10-20%

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1042]
Looking at last uploads from South Africa using Nextclade i spotted a new lineage with S:346T this time is a BA.5.3.

CovSpectrum Query : 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3A346T&nucMutations=13252T&nextcladePangoLineage=BA.5.3*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Gisaid query: BA.5.3 Spike_R346T

Defining mutations: 
BA.5.3 (=BA.5+C1931A) + C27839T + C13252T +S:346T

It counts just 10 sequences but being apparently 2% of last month samples in South Africa i feel it is worth proposing it :
Good Quality sequences:
EPI_ISL_13783494 First sequence South Africa 15/06/2022
EPI_ISL_14795075
EPI_ISL_14460196
EPI_ISL_14437994
EPI_ISL_14449033
EPI_ISL_14449035
EPI_ISL_14659842
EPI_ISL_14795059

Tree:
![Schermata 2022-09-06 alle 09 08 14](https://user-images.githubusercontent.com/87669813/188569260-cc4fbefa-d200-4b43-bf85-1e9bc673743f.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1c0e9_6f01d0.json?branchLabel=aa%20mutations&c=gt-nuc_27389,13252&label=nuc%20mutations:C13252T

**Comment by FedeGueli** [comment]
Being this quite slow, i'll close it for now keeping it monitored. I will reopen if it shows some growth or new mutation.

**Comment by FedeGueli** [comment]
(be awre there are another less recent BA.5.3.1 lineage with different  nuc mutations :  T18975C, C10834T circulating at low levels in Europe: so the Gisaid query above is not 100% reliable.

**Comment by FedeGueli** [comment]
South Africa uploaded a bunch of new sequences of this one, so i reopen it to be monitored.

**Comment by FedeGueli** [comment]
one more sequence from South Africa: EPI_ISL_15112392

**Comment by FedeGueli** [comment]
31 sequences as today

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.3.5 with 25 newly designated sequences, and 0 updated designations. Defining mutation G22599C (S:R346T) (following C13252T).

**Comment by jinyu-ncbi** [comment]
Is C27839T a typo? Using NC_045512.2 as the reference, it is a T at position 27839: https://www.ncbi.nlm.nih.gov/nuccore/1798174254

**Comment by AngieHinrichs** [comment]
Good spot @jinyu-ncbi.  From the UShER tree it appears to be C27389T (389 not 839, slip of the fingers).

**Comment by FedeGueli** [comment]
Thx @jinyu-ncbi for spotting it was one of my usual typoes sorry for that. Now updated and corrected. Many thx!
