### ISSUE TITLE
Potential BA.2.75* Sub-lineage with Spike F486L  in India, Singapore, South Korea, USA [16 sequences]

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#1046]
Description: Sub-lineage of BA.2.75* with S:F486L
Earliest sequence: 06/2022 Haryana, India [only month and year available]
Most recent sequence:  8/26/2022 from NY, USA (uploaded 9/4/22)
Countries: India (Delhi, Haryana, Karnataka, Odisha, Telangana), South Korea, Singapore, USA (New York)
Number of sequences: 16 
Unique Nucleotide mutations: :A14475C, T23018C

Singapore sequence is associated with travel history to France, Spain

Significance: Early Spike:F486L's were found in sequences from Bats (China), Pangolin (China), Minks (Canada, Lithuania, Netherlands, USA)  and White tailed Deer (Ontario, Canada)

Usher Tree:
![image](https://user-images.githubusercontent.com/98380390/188758139-ee0c2091-1e0a-43df-9947-2b6f3edb5ffa.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ba15_7c15f0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A14475C,T23018C

3 unique subclusters - one carrying orf1ab:A6623V; one with orf7a:C67S 

Importance of Orf7a:C67S
![gr2](https://user-images.githubusercontent.com/98380390/188759138-f17d7ffd-f5ee-4434-a7b5-9cbf0f9b3f72.jpg)

Holds the key beta strand sandwiches together (a functionally important interface)
Source: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7879101/

Cov-spectrum query: 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AF486L%2CE%3AT11A&

GISIAID IDs: 
EPI_ISL_14417549
EPI_ISL_14537467
EPI_ISL_14537478
EPI_ISL_14566954
EPI_ISL_14566955
EPI_ISL_14566958
EPI_ISL_14566961
EPI_ISL_14601854
EPI_ISL_14601905
EPI_ISL_14603948
EPI_ISL_14603949
EPI_ISL_14722484
EPI_ISL_14722540
EPI_ISL_14724154
EPI_ISL_14790098
EPI_ISL_14808679

**Comment by RajLABN** [comment]
One more BA.2.75* + S:F486L from Ontario, Canada uploaded today (sample collection date 8/23/22)
EPI_ISL_14844031

GISAID query: SPIKE_F486L, NSP3_S403L, NSP8_N118S

**Comment by corneliusroemer** [comment]
I've seen these two, probably makes sense to designate soon.

One needs to carefully check these are monophyletic and not homoplasic on top of the BA.2.75 founder.

For example these two are BA.2.75.3 - so at least these should not become part of this lineage, even if Usher may place them together:

```
hCoV-19/USA/NY-PRL-220829_00C12/2022|EPI_ISL_14808679|2022-08-26
hCoV-19/India/OR-ILSGS18942/2022|EPI_ISL_14601854|2022-07-30
```

The are in your list above @RajLABN - you can check for this by running them through Nextclade for example. Nextclade and Usher together should be good.

There are some partially shared mutations that should be checked whether they happened first: 
2800C
3774A
14475C

CovSpectrum is unfortunately down atm so can't check as I'm writing.

**Comment by corneliusroemer** [comment]
Alright, so BA.2.75 + 3774A is a lineage that then acquired S:486L.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=3774A&nextcladePangoLineage=BA.2.75*&

2800C seems to occur in a BA.2.75.5 lineage, but for some reason covSpectrum doesn't show the S:486L yet - maybe recent upload?

So the only one that would make sense to designate would be the 3774A one with 6 samples.

So we should probably wait a bit more to see whether any of these branches grow and designate only then.

**Comment by FedeGueli** [comment]
Quite interesting S:F486L was in RATG13 too.

**Comment by RajLABN** [comment]
BA.2.75* + S:F486L ( EPI_ISL_14926628 ) - from Estonia

**Comment by RajLABN** [comment]
3 more BA.2.75* + S:F486L - 2 from Estonia and 1 from Bengaluru, India [EPI_ISL_14926628, EPI_ISL_14933338, EPI_ISL_14934026]

GISAID query: spike_f486l,  nsp3_s403l, nsp8_n118s 

As of now S:F486L is found in 18 BA.2.75* and 2 BA.2.75.3* (once the BA.2.75.3* ---a potential sub-lineage as well)

**Comment by corneliusroemer** [comment]
I think this may not give that much of a growth advantage.

First sequence was uploaded more than a month ago, and it's still only 17 sequences. I will close this for now as it doesn't seem that much of a thing for now. We can reopen if something interesting comes out of it.
