### ISSUE TITLE
B.1.526-like with N:P13L,S202R spreading in US (especially east coast)

### ISSUE THREAD

**Issue by mkedwards** [cov-lineages/pango-designation#105]
## New lineage proposal
by Michael K. Edwards <m.k.edwards@gmail.com>

### Description
Sub-lineage of: B.1.526.2, ish, if you believe Nextstrain cladistics; does not have N:M234I,P199L or S:A701V, so I consider that highly questionable.
Earliest sequence: collected 2020-03-08, in Dominican Republic (GISAID EPI ISL 1378840)
Most recent sequence: Now.
Countries circulating: US, mostly; also Dominican Republic, Ghana, Romania.

The closest thing genomically to the founding strain in Nextstrain's North America subsample appears to be GISAID EPI ISL 1736682.

N: P13L, S202R
ORF1a: T265I, G1946S, L3201P, S3675-, G3676-, F3677-
ORF1b: P314L, Q1011H
ORF3a: P42L, Q57H
ORF7a: L116F
ORF8: T11I
ORF9b: P10S
S: L5F, T95I, D253G, S477N, D614G, Q957R

There's a further subclade that has picked up N:G204V and spread into Romania.

### Evidence
https://nextstrain.org/ncov/north-america?branchLabel=aa&c=gt-N_199,234,13,202,203,204&label=clade:21F%20%28Iota%29&m=div

<img width="1403" alt="Screen Shot 2021-06-09 at 10 21 15 AM" src="https://user-images.githubusercontent.com/843186/121400486-7f738600-c90c-11eb-94df-60acfa9bf4d5.png">

### Proposed lineage name
Probably *not* B.1.526.anything.  AX.1 or whatever we're up to.

**Comment by mkedwards** [comment]
Ping.  This lineage is still a thing, still spreading (though not in any conspicuously massive way), and still obscuring the dynamics of the spread of actual B.1.526.

**Comment by chrisruis** [comment]
These sequences don't appear to form a monophyletic clade in the latest UShER tree. This region of the tree has been examined in #154 with new designations to follow from that

**Comment by corneliusroemer** [comment]
When examining a new reference tree for Nextclade, I noticed that B.1.526 seems to have two main lineages that are actually quite well separated. Going through historical issues mentioning this lineage, I came across this issue that shares my observations.

The split occurs in a number of trees I looked at:

Lineage 1: `S:E484K, S:A701V, N:P199L`
Lineage 2: `S:S477N, S:Q957R, ORF7a:L116F, N:P13L, N:S202R, N:I234M, ORF9b: P10S, ORF1a:G1946S`

Quite a few of these sound familiar from other VOC/VOIs

I do think it's worth reconsidering splitting these up. Maybe there are just a few contaminated/coinfection sequences in there that make it look non-monophyletic. Or maybe there were recombinations?

In this thread this split was already discussed. Given that we've split Delta up quite well, maybe we can reevaluate with the benefit of hindsight? @AngieHinrichs proposed the split back then.
https://github.com/cov-lineages/pango-designation/issues/6

If using `S:A701V, N:P199L` for lineage 1 and `S:Q957R, N:S202R, S:477N` for lineage 2, they make up around 90% of B.1.526, splitting it nicely.

Lineage 2 has around 13k sequences, that's a respectable size: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_9d2_c83e70.json?label=nuc%20mutations:A10323G
![image](https://user-images.githubusercontent.com/25161793/152458557-11b651e7-5fd6-4603-9e9d-67a88372c7bd.png)


Lineage 1 would have even 26k sequences.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_d47_c84c00.json?label=nuc%20mutations:T9867C,G10323A,A20262G,C23664T,C25517T,C28869T,G28975A
![image](https://user-images.githubusercontent.com/25161793/152458719-da4bd565-6a76-47e6-98f8-227a6cbd7a15.png)


![image](https://user-images.githubusercontent.com/25161793/152457710-65948114-6e53-4fcc-8b80-cd813713e0a6.png)
https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?aaMutations=S%3AQ957R%2CN%3AS202R%2CS%3A477N&pangoLineage=B.1.526&aaMutations1=S%3AA701V%2CN%3AP199L&pangoLineage1=B.1.526&aaMutations2=S%3AQ957R%2CN%3AS202R%2CS%3A477N&pangoLineage2=B.1.526

The apparent reversion in Usher builds may just be artefacts/tree errors.

Other related issues:
https://github.com/cov-lineages/pango-designation/issues/45
https://github.com/cov-lineages/pango-designation/issues/154

**Comment by aineniamh** [comment]
I'm going to close this as issue has gone stale.
