### ISSUE TITLE
Sublineage of BA.5.2 with ORF1b:T17I & T6218C (~125 seq on Sept 18)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1050]
**Description**
**Sub-lineage of:** BA.5.2
**Earliest sequence:** 2022-7-30, USA, California — EPI_ISL_14790741
**Most recent sequence:** 2022-9-2, Denmark — EPI_ISL_14840418, EPI_ISL_14840428, EPI_ISL_14841229
**Countries circulating:** Denmark (58), Japan (3—all in incoming travelers from Iran/Turkey), Sweden (2), England (1), USA (1)
**Number of Sequences:** 65 on Usher Tree on Sept 7 (GISAID query unreliable because GISAID doesn’t allow nucleotide searches and there are numerous BA.5* lineages with ORF1b:T17I, including multiple separate branches of BA.5.2)
**GISAID Query:** NSP12_T26I, NSP13_T127N, Spike_F486V
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2 & T6218C & ORF1b:T17I
**Substitutions on top of BA.5.2:**
**ORF1b:** T17I
**ORF1b:** T1050N
**Nucleotide:** T6218C, C13517T, C16616A

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_188ca_8d6ba0-BA.5.2%2BORF1bT17N%2BT6218C.json 
![Screen Shot 2022-09-07 at 4 26 41 PM - BA 5 2 + ORF1bT17I Usher Tree](https://user-images.githubusercontent.com/33738461/188974548-db7ab31e-0859-4476-84b2-f68eff5b64e9.png)

**Evidence**
CovSpectrum: 83% (CI:51-116%) weekly growth advantage compared to NextcladePangoLineage:BA.5.2* & ORF1b:T1050N in the last three months in Denmark: <details> <summary>Link</summary>
https://cov-spectrum.org/explore/Denmark/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5.2*&variantQuery1=Nextcladepangolineage%3ABA.5.2+%26+ORF1b%3AT17I+%26+T6218C&analysisMode=CompareToBaseline& </details>

CovSpectrum: 75% (CI: 42-108%) weekly growth advantage compared to NextcladePangoLineage:BA.5.2 & ORF1b:T1050N in the last three months in Denmark. Note small sample size and short time period, which virtually always results in an exaggerated growth advantage. 
<details><summary>Link</summary>
https://cov-spectrum.org/explore/Denmark/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5.2+%26+ORF1b%3AT1050N&variantQuery1=Nextcladepangolineage%3ABA.
5.2+%26+ORF1b%3AT17I+%26+T6218C+%26+ORF1b%3AT1050N&analysisMode=CompareToBaseline& </details>

This sublineage also has ORF1b:T1050N, which is now found in a majority of BA.5.2 sequences. ORF1b:T17I (NSP12_T26I) is found in numerous other lineages BA.5* lineages, and has even emerged independently several times within BA.5.2, indicating strong convergent evolution. 

For example, in the past three months, there have been 341 BA.5.1 sequences worldwide (101 in Germany) with ORF1b:T17I according to CovSpectrum. BA.5.1 + ORF1b:T17I enjoys a 10% (CI: 5-14%) weekly growth advantage  globally and a 12% (CI: 4-20%) advantage in Germany relative to BA.5.1 over that time period, providing more evidence that this NSP12 mutation is advantageous for BA.5 lineages in the current global context. https://cov-spectrum.org/explore/Germany/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5.1&variantQuery1=Nextcladepangolineage%3ABA.5.1+%26+ORF1b%3AT17I&analysisMode=CompareToBaseline&

Similarly, from January 15 to May 15, BA.2* + ORF1b:T17I had a 10% (CI: 9-12%) weekly growth advantage globally compared to BA.2*, and in the UK, which easily had the most such sequences and the best genetic surveillance over this time period, the growth advantage was 24% (CI: 20-29%). https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/from=2022-01-15&to=2022-05-15/variants?variantQuery=Nextcladepangolineage%3ABA.2*&variantQuery1=Nextcladepangolineage%3ABA.2*+%26+ORF1b%3AT17I&analysisMode=CompareToBaseline& 

The same is true for BA.2.12.1. From March 1 to June 1 in North America (where the vast majority if sequences were from), BA.2.12.1 + ORF1b:T17I had a 22% (CI: 10-34%) growth advantage over BA.2.12.1. https://cov-spectrum.org/explore/North%20America/AllSamples/from=2022-03-01&to=2022-06-01/variants?variantQuery=Nextcladepangolineage%3ABA.2.12.1&variantQuery1=Nextcladepangolineage%3ABA.2.12.1+%26+ORF1b%3AT17I&analysisMode=CompareToBaseline&

All this is strong evidence that ORF1b:T17I confers a substantial growth advantage. 

**Genomes**
<details>
  <summary>EPI ISLs</summary>
EPI_ISL_14236088, EPI_ISL_14391342, EPI_ISL_14432708, EPI_ISL_14432802, EPI_ISL_14432925, EPI_ISL_14433006, EPI_ISL_14433041, EPI_ISL_14472293, EPI_ISL_14494491, EPI_ISL_14512288, EPI_ISL_14512317, EPI_ISL_14512471, EPI_ISL_14543012, EPI_ISL_14545767, EPI_ISL_14545798, EPI_ISL_14545967, EPI_ISL_14546000, EPI_ISL_14546035, EPI_ISL_14546069, EPI_ISL_14546587, EPI_ISL_14546588, EPI_ISL_14546628, EPI_ISL_14546657, EPI_ISL_14546669, EPI_ISL_14546694, EPI_ISL_14562515, EPI_ISL_14562522, EPI_ISL_14562631, EPI_ISL_14562787, EPI_ISL_14562898, EPI_ISL_14563096, EPI_ISL_14602372, EPI_ISL_14602476, EPI_ISL_14602495, EPI_ISL_14602509, EPI_ISL_14602815, EPI_ISL_14632351, EPI_ISL_14632352, EPI_ISL_14632353, EPI_ISL_14691398, EPI_ISL_14691546, EPI_ISL_14691671, EPI_ISL_14691782, EPI_ISL_14710959, EPI_ISL_14722154, EPI_ISL_14750733, EPI_ISL_14750890, EPI_ISL_14750933, EPI_ISL_14772558, EPI_ISL_14787365, EPI_ISL_14787382, EPI_ISL_14787457, EPI_ISL_14790741, EPI_ISL_14822875, EPI_ISL_14822933, EPI_ISL_14823152, EPI_ISL_14823172, EPI_ISL_14823209, EPI_ISL_14823211, EPI_ISL_14823226, EPI_ISL_14823293, EPI_ISL_14840304, EPI_ISL_14840418, EPI_ISL_14840428, EPI_ISL_14841189, EPI_ISL_14841229
</details>

**Comment by corneliusroemer** [comment]
I don't think you can trust the growth advantage here - there's strong observation bias. You're proposing it because of the growth advantage so this could just be chance.

I'd say we get remove the growth advantage graphs for now and check in a week with data since then ;)

Here's a screenshot for comparison in a week.

<img width="937" alt="image" src="https://user-images.githubusercontent.com/25161793/189095298-2bf691e9-5f91-49d2-bb7f-38d0ff7e0030.png">

**Comment by ryhisner** [comment]
I'll remove the 60-100% GA pictures, which I know are unrealistic. The smaller, but more certain GA's ORF1b:T17I conferred on BA.2* and BA.2.12.1 are really the only reason I proposed this in the first place. When a mutation rises in prevalence in multiple lineages, over long periods of time, that's usually a pretty solid indication it's advantageous.

I'll try to use that format for a collapsible. Usually I get the cvs from GISAID, but because GISAID, for some unfathomable reason, doesn't allow nucleotide searches, I couldn't do that for this lineage.

**Comment by corneliusroemer** [comment]
Thansk @ryhisner much appreciated!

One good rule is to use data from point of designation for growth advantages (especially in absence of S mutations heavily suspected of significant growth advantage). So now that you spotted it we can review in a week and see what's happening.

**Comment by ryhisner** [comment]
Using the GISAID query "Spike_F486V, NSP12_T26I, NSP13_T127N" there were 18 sequences uploaded in the past two days (14 today, four yesterday), but only 13 of those are from this lineage. The other five are not only unrelated to this lineage but are unrelated to each other as well. The way this mutation (ORF1b:T17I, NSP12_T26I) has evolved independently in many separate lineages—even multiple times within designated lineages—is to me another indication that it is likely advantageous. 

Also, I forgot to include some fascinating information about the three Japanese airport surveillance sequences, all collected on August 10 and uploaded Aug 26: they all are described as having travel history in Iran and Turkey. EPI_ISL_14632351, EPI_ISL_14632352, EPI_ISL_14632353

**Comment by ryhisner** [comment]
21 new sequences of this lineage uploaded in the past three days, most from Denmark, but including sequences from Switzerland, France, Belgium, India, and Iran. The three Japanese airport surveillance sequences had travel history in Iran (and Turkey), so this lineage may have a strong presence there.

**Comment by corneliusroemer** [comment]
Bit small - let's keep watching this. It could be OK as a way to reduce BA.5.2 unspecificity.

**Comment by ryhisner** [comment]
There were 8 sequences of BA.5.2 + ORF1b:T17I (with ORF1b:T1050N) uploaded from England today, none of them related to this lineage. The branch has 14 sequences, all very recent. I've seen ORF1b:T17I evolve independently so many times that I'm pretty convinced it's advantageous, at least on a BA.5.2 background. So far it's seemed to grow quickly, but that could be due to some local phenomenon in Denmark. I'll monitor and see what happens in the next week or two, which should be telling.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.29 with 88 newly designated sequences, and 0 updated designations. Defining mutation(s) C13517T (ORF1b:T17I) (following T6218C).
