### ISSUE TITLE
Potential Sublineage of BA.4.6 with 2 new spike mutations S:R21T, S:S494P sampled in Uk and France (7 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1051]
Here i want to propose and  monitor a potential sublineage of BA.4.6 with two additional spike mutations which has been sampled in England and in two different region of France (Occitanie and Ile-de-France) between 27/07 and 29/08

Defining mutations:
BA.4.6 (S:346T) + Orf1b:V691I + S:R21T + S:S494P 

List of sequences
EPI_ISL_14460096
EPI_ISL_14572806
EPI_ISL_14817002
EPI_ISL_14818238
EPI_ISL_14841850
England/PHEP-YYFWI8X/2022|2022-08-22

Gisaid query: Nsp12_v700I,Spike_R21T, Spike_S494P

CovSpectrum query: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A21T%2CS%3A494P&nextcladePangoLineage=BA.4.6*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Tree:
![Schermata 2022-09-08 alle 01 09 03](https://user-images.githubusercontent.com/87669813/188998776-45a251ee-43ab-424c-b5f9-e138d0636b76.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ef53_91ceb0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G15538A

**Comment by corneliusroemer** [comment]
I've seen S:S494P twice in BA.2.75* too

**Comment by FedeGueli** [comment]
@corneliusroemer Interestingly the sequence that made me found BQ.1 sampled in Japan, but travel related with Egypt Italy and Israel, had also S:S494  mutated (to P i think lemme check)

**Comment by FedeGueli** [comment]
And also S:S494P is defining in BA.2.10.4

**Comment by FedeGueli** [comment]
New one sampled in Japan travel related with Malta

**Comment by corneliusroemer** [comment]
Doesn't seem to be doing that much. Won't be enough to save BA.4.6 and this is still quite small. You can keep track of this and let me know if it grows significantly but I think better close for now.

**Comment by FedeGueli** [comment]
15 sequences as today now found also in Switzerland, Denmark, Israel, Luxembourg:
Interestingly the south korean airport surveillance found this virus in a traveller from Mongolia that could be a good candidate as country where this emerged. 

I ll ask you to reopen @corneliusroemer to better monitor it until it will be clearer its growth and spread.

**Comment by FedeGueli** [comment]
Not going anywhere i will cease monitoring it for a while. If someone spots it feel free to comment here i will reopen .

**Comment by FedeGueli** [comment]
24 sequences as today
