### ISSUE TITLE
BA.2 Sublineage with 13 mostly convergent spike mutations (India, 7 seq, 3 regions on Sept 15)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1053]
### **Description**
**Sub-lineage of:** BA.2
**Earliest sequence:** 2022-7-23, India, Rajasthan (Jodhpur) — EPI_ISL_14775115
**Most recent sequence:** 2022-8-5, India, Maharashtra (Pune) — EPI_ISL_14568402
**Countries circulating:** India
**Number of Sequences:** 3
**GISAID Query:** Spike_P9T, Spike_R1091H, Spike_V1264L
**CovSpectrum Query:** Nextcladepangolineage:BA.2* & S:P9T & S:R1091H & S:V1264L
**Substitutions on top of BA.2:**
**Spike:** P9T, W64R, 69-70del, 138-145del, R214L, 243-244del, G252D, G446S, N460K, K478T (Rev), R493Q (Rev), R1091H, V1264L
**N:** K65R
**E:** V58L
**ORF1a:** L2146F, T2174A, P3359S, T4010I, R4017K (only in RJ seq), T4311I
**ORF1b:** (Both found only in RJ seq) T1697E (2-nuc), T2099I
**Nucleotide:** C6701T, A6785G, C10340T, C12294T, G12315A, C13197T, A18556G, C18557A, C19763T, C19983T, T21180C, C21587A, T21752C, G22203T, G22317A, G22898A, T22942G, A22995C, G23040A, G24834A, G25352T, G26416C, A28467G
**Nucleotide deletions:** 21765-21770, 21972-21995, 22289-22294
 
The first three sequences of this lineage were collected in Pune, Maharashtra (MH), India (2022-8-1 & 2022-8-5) and Jodhpon, Rajasthan (RJ), India (2022-7-23), cities that are over 1100 km apart, indicating substantial geographic spread. (Metadata show that the two MH sequences are from separate patients.) One MH sequence unfortunately had low very coverage (over 32% NNN’s), but the other MH sequence was better, and by comparing the two MH with the RJ sequence, you can tell they are nearly identical. The Rajasthan sequence appears to have one additional ORF1a mutation (R4017K) and two ORF1b mutations (the 2-nuc T1697E and T2099I) that the other two seem not to have, but apart from that the sequences are identical wherever coverage allows them to be compared. I think it’s even possible that the MH sequences have these ORF1ab mutations even though on Nextclade they appear to have coverage there. The Usher tree is misleading in this respect.
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_30e18_a17040%2BR1091H-Monster.json
![Screen Shot 2022-09-08 at 1 27 55 PM - R1091H Usher Tree](https://user-images.githubusercontent.com/33738461/189191278-18d8916b-b5aa-4a3b-ac03-423dca6d94ea.png)

**Evidence**
Counting deletions, this BA.2 sublineage has either 12 spike mutations, including some of the classics we’ve all grown to love, such as W64R, 69-70del, 243-244del, G446S, N460K, and V1264L. P9T is rare but not uncommon in sequences resulting from large saltations. R214L and G252D are also rare but have been occurring more frequently in recent months, particularly in sequences with numerous private mutations. R1091H is the most unusual spike mutation here and the only one I haven’t noticed in other divergent sequences.

N:K65R was seen in 1.65% of all BA.2.1* sequences according to Cov-Spectrum, and no other lineage had it in more than 1% of sequences. E:V58L is extremely rare, and according to Outbreak.info, AY.124 is the only lineage for which E:V58L made up at least 1% of all sequences (109 of 5544).  

In ORF1a, P3359S is an NSP5 mutation (NSP5_P96S) while T4010I and R4017K are both NSP8 mutations. T4311I (NSP10_T58I) is an ORF1a mutation that I’ve noticed in a disproportionate share of divergent sequences. It is more common in BA.4 and BA.5 lineages, however, and doesn’t seem to be as associated with highly mutated sequences in them as it does for other lineages.

Mutations relative to BA.2, via NextClade, for the Rajasthan sequence, which is easily the most complete of the three, are pictured below. 
![Screen Shot 2022-09-08 at 1 51 49 PM](https://user-images.githubusercontent.com/33738461/189191897-575cef0b-3138-4698-a6de-e1835a5ed367.png)

**Genomes**
EPI_ISL_14568402
EPI_ISL_14775115
EPI_ISL_14861520

**Comment by cvejris** [comment]
Another lovely lineage. Note that K478T is reversion to WT

**Comment by AngieHinrichs** [comment]
This also seems to have the S:493Q reversion, which is why it has a lot of BA.4 neighbors in the local subtree:

https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_30e18_a17040+R1091H-Monster.json?branchLabel=Spike%20mutations&c=pango_lineage_usher

**Comment by ryhisner** [comment]
Oh, yes, thank you for calling attention to this @AngieHinrichs! I don't know how I managed to forget to include that one.

**Comment by FedeGueli** [comment]
New one uploaded today: EPI_ISL_14910446:
Andhra Pradesh collected on July

**Comment by FedeGueli** [comment]
One more sequence from India(MH, Pune) : EPI_ISL_14989106 collected on 24/08

**Comment by ryhisner** [comment]
This latest sequence has an additional convergent spike mutation—S:G181A.

**Comment by corneliusroemer** [comment]
Thanks for spotting this! It's interesting that it comes straight off the BA.2 polytomy (with 9866) - the first 2nd gen BA.2 to not be from somewhere later in the BA.2 tree.

I think this deserves a designation - too late here now for me to do it, maybe tomorrow or someone else goes for it. This has enough circulation to be worthy of a name.

<img width="2305" alt="image" src="https://user-images.githubusercontent.com/25161793/190880890-25d260c2-bde6-429d-8891-f2b360b527f6.png">

**Comment by thomasppeacock** [comment]
One of these has turned up in Denmark as well:
EPI_ISL_15037563

**Comment by ryhisner** [comment]
And those Denmark sequences have added S:L452R!
![image](https://user-images.githubusercontent.com/33738461/191271259-334ce947-925a-42a3-9a50-22ded65a5c71.png)

**Comment by FedeGueli** [comment]
Spotted today a sibling lineage of this one , likely it is unrelated maybe just sharing some common ancestor with BA.2.83:
<img width="1146" alt="Schermata 2022-11-10 alle 10 41 03" src="https://user-images.githubusercontent.com/87669813/201055800-ae904ae2-7c0a-4efc-8841-72df763650de.png">

put here to be monitored for its peculiar spike profile with S:N460K (T22942G):
<img width="1107" alt="Schermata 2022-11-10 alle 10 40 37" src="https://user-images.githubusercontent.com/87669813/201055717-0f8f3d02-56fe-43e3-8307-2a711aa510f1.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ef5b_cc5a50.json?c=pango_lineage_usher&label=nuc%20mutations:G22332T,G26393T

Sample from Novgorod  Russia EPI_ISL_15403898:
<img width="700" alt="Schermata 2022-11-10 alle 10 41 31" src="https://user-images.githubusercontent.com/87669813/201055887-23f1c023-6fbd-4aaf-8bec-94499b224bb2.png">

Sample from UFA Russia EPI_ISL_15403898:
<img width="693" alt="Schermata 2022-11-10 alle 10 42 36" src="https://user-images.githubusercontent.com/87669813/201056168-05581933-f55b-4528-8414-1ecfc7fbd7e5.png">


Common Branch: 
<img width="688" alt="Schermata 2022-11-10 alle 10 45 48" src="https://user-images.githubusercontent.com/87669813/201057125-8768c2f8-1ac3-453a-a852-b39b9d93a23e.png">


So Gisaid query for it could be  : Spike_N460K, Spike_Y449S,Spike_R190S,N_N29T
