### ISSUE TITLE
BA.5.2 + Orf1b:T1050N sublineage with Spike: K97T circulating in NYC (46 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1054]
Here i want to propose a new sublineaage of the infamous BA.5.2 + G12310A + Orf1b:T1050N sublineage:
i noticed this one in the past day while analyzing sequences from New York City but i was convinced to propose it immediately by the publication of this paper by Taiwanese scientists: 
https://www.ijidonline.com/article/S1201-9712(22)00500-8/fulltext 
where they have found links between  neurological pediatric symptoms and the local variant BA.2.3.7 that was very early here described by @silcn 8thx) in #643.
Ba.2.3.7 is defined by a mutation at the same residue but toward a different AA :
In BA.2.3.7 is S:K97E
in the lineage proposed here it is : S:K97T.
So nothing suggests that it could have the same or any impact , but i think right to propose and monitor it publicly after being aware of it already since some days ago.

Defining mutations:
 BA.5.2 + G12310A + C16616A (Orf1b:T1050N) >> C27513T > C27012T > A7259G  (Orf1a:I2332V)> A21852C  (S:K97T) 

Gisaid query Spike_K97T, NSP13_T127N,NSP3_I1514V finds 39 viruses  

while Usher Tree displays 42 viruses:
![Schermata 2022-09-09 alle 00 15 33](https://user-images.githubusercontent.com/87669813/189235513-b118b3d4-9c83-4b52-a061-8c9a211bf917.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39519_a65da0.json?branchLabel=aa%20mutations&label=nuc%20mutations:A21852C

List of sequences
<details>
<summary>Expand for EPI_ISLs</summary>

EPI_ISL_13746810
EPI_ISL_13889475
EPI_ISL_13889819
EPI_ISL_14176394
EPI_ISL_14178008
EPI_ISL_14182466
EPI_ISL_14265468
EPI_ISL_14269495
EPI_ISL_14274423
EPI_ISL_14274424
EPI_ISL_14284769
EPI_ISL_14306264
EPI_ISL_14461069
EPI_ISL_14461572
EPI_ISL_14504567
EPI_ISL_14504761
EPI_ISL_14504762
EPI_ISL_14523984
EPI_ISL_14560152
EPI_ISL_14574173
EPI_ISL_14574532
EPI_ISL_14574570
EPI_ISL_14574916
EPI_ISL_14624842
EPI_ISL_14650498
EPI_ISL_14652859
EPI_ISL_14652920
EPI_ISL_14659372
EPI_ISL_14684699
EPI_ISL_14685325
EPI_ISL_14717761
EPI_ISL_14742423
EPI_ISL_14759016
EPI_ISL_14776978
EPI_ISL_14776981
EPI_ISL_14808258
EPI_ISL_14808540
EPI_ISL_14808648
EPI_ISL_14852428
</details>

CovSpectrum Query : BA.5.2 (Nextclade) + G12310A + Orf1b:T1050N, Orf1a:I2332V, S:97T
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1b%3AT1050N%2COrf1a%3AI2332V%2CS%3A97T&nucMutations=G12310A%2CC27513T%2CC27012T&nextcladePangoLineage=BA.5.2&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

**Comment by corneliusroemer** [comment]
Thanks Fede! I wish we had given that ORF1b:T1050N the name BA.5.2.2 or something like it so that we would now have an alias for it :/ Too late now!

**Comment by AnonymousUserUse** [comment]
I think it is never too late to designate a lineage as long as it is reasonable.

**Comment by FedeGueli** [comment]
@corneliusroemer @AngieHinrichs 
i have tried! 
https://github.com/cov-lineages/pango-designation/issues/890

**Comment by FedeGueli** [comment]
45 seqs as today!

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.15 with 34 newly designated sequences, and 1 updated designations from BA.5.2. Defining mutation A21852C (S:K97T) (follows A7259G (Orf1a:I2332V)).

**Comment by shay671** [comment]
@corneliusroemer, I totally agree with you regarding the definition of the mediator branch. For instance, this one and BA.5.2.16 have the same three mutations above BA.5.2, while this one has another before the defining mutation. 

And I'd like to propose maybe an idea (excuse me if this is not the proper place) - to define the mediator branch (the branch until the branch point of the variant) for new variants. Not leaving an undefined mutational path between the last designated variant and the new one. Even if the mediator branch is not answering the rules for a new variant.
