### ISSUE TITLE
Potential BA.5.2.1 Sublineage with C5284T, ORF1b:G376S, S:R346T, and C15738T (54 seqs as of 2022-09-16; USA plus UK)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1056]
There may be a BA.5.2.1 sublineage with C5284T, ORF1b:G376S (G14593A; ORF1ab:G4777S; NSP12_G385S), S:R346T (G22599C), and C15738T first detected in New York, USA.  This resembles BF.7, but BF.7 seems to not have ORF1b:G376S or C5284T which UShER places upstream of S:R346T for this lineage.

As of 2022-09-10, Cov-Spectrum reports 42 BA.5.2.1+ORF1b:376S+S:346T+15738T+5284T sequences with good quality control scores:
![BA 5 2 1+ORF1b_376S+S_346T+15738T+5284T-Counts](https://user-images.githubusercontent.com/88959107/189494353-782375a7-3633-4d91-9f5f-1349c49bd39c.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.1+%26+ORF1b%3AG376S+%26+S%3AR346T+%26+C15738T+%26+C5284T&nextcladeQcOverallScoreTo=29&

As of 2022-09-10 and considering only sequences with good quality control scores, Cov-Spectrum calculates an early growth advantage of 72% compared to BA.5.2.1* in the United States:
![BA 5 2 1+ORF1b_376S+S_346T+15738T+5284T-Growth_vs_BA 5 2 1](https://user-images.githubusercontent.com/88959107/189494368-a16e6b88-7452-4f1c-b0c5-18d18d0ccbd0.png)
Source: https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.1*&variantQuery1=nextcladePangoLineage%3ABA.5.2.1+%26+ORF1b%3AG376S+%26+S%3AR346T+%26+C15738T+%26+C5284T&analysisMode=CompareToBaseline&nextcladeQcOverallScoreTo=29&

As of 2022-09-10 and considering only sequences with good quality control scores, Cov-Spectrum calculates an early growth advantage of 75% compared to BA.5* in the United States:
![BA 5 2 1+ORF1b_376S+S_346T+15738T+5284T-Growth_vs_BA 5](https://user-images.githubusercontent.com/88959107/189494390-08d534cf-2bc5-441a-a700-f0cecd06041f.png)
Source: https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABA.5.2.1+%26+ORF1b%3AG376S+%26+S%3AR346T+%26+C15738T+%26+C5284T&analysisMode=CompareToBaseline&nextcladeQcOverallScoreTo=29&

As of 2022-09-10, UShER shows all of the GenBank samples are on a single subtree:
![BA 5 2 1+ORF1b_376S+S_346T+15738T+5284T-UShER_subtree](https://user-images.githubusercontent.com/88959107/189494397-ff544e6c-fa19-4faf-ad8d-108c9da8feb9.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/09/subtreeAuspice1_genome_BA.5.2.1%2BORF1b_376S%2BS_346T%2B15738T%2B5284T.json?branchLabel=aa%20mutations&c=userOrOld&label=nuc%20mutations%3AC15738T%2CG22599C

![BA 5 2 1+ORF1b_376S+S_346T+15738T+5284T-UShER_downsampled](https://user-images.githubusercontent.com/88959107/189494402-3990e412-4996-4c19-a181-fd32d801850d.png)
To visualize on UShER in a downsampled global tree: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/09/singleSubtreeAuspice_genome_BA.5.2.1%2BORF1b_376S%2BS_346T%2B15738T%2B5284T.json?branchLabel=aa%20mutations&label=nuc%20mutations%3AC1627T%2CA28330G

First potential Outbreak.info sequence: New York, USA 2022-07-05

First GenBank sequence: New York, USA 2022-07-09 

Most Recent GenBank sequence: Louisiana, USA 2022-08-28

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at 
[Support-BA.5.2.1+ORF1b_376S+S_346T+15738T+5284T.zip](https://github.com/cov-lineages/pango-designation/files/9541016/Support-BA.5.2.1%2BORF1b_376S%2BS_346T%2B15738T%2B5284T.zip)

The closest Outbreak.info link for this potential lineage (nucleotide mutations are not supported) is https://outbreak.info/situation-reports?pango=BA.5.2.1&muts=ORF1b%3AG376S&muts=S%3AR346T.

This lineage is proposed at a lower sequence count in accord with [Issue 865](https://github.com/cov-lineages/pango-designation/issues/865).

**Comment by FedeGueli** [comment]
Gisaid query : NSP12_G385S, Spike_R346T finds 59 viruses nextclading them i was not sure they are from different lineages even if Nextclade calls 6 of them BA.5.2 and another one BE.1.2 but  ushering all of them i found just a [real ](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_43daa_cf54b0.json)BE.1.2 and two others belonging to another BA.5.2.1[ sublineage](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_43daa_cf54b0.json?c=pango_lineage_usher&label=nuc%20mutations:C21627T).

So probably although not 100% that gisaid query is sufficiently accurate to monitor this lineage:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43daa_cf54b0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G29734T

**Comment by alurqu** [comment]
@FedeGueli It's interesting that ORF1b:G376S also showed up with S:R346T in that BE.1.  Just to be clear to other readers, the lineage proposed here is a BA.5.2.1 sublineage and the BE.1 occurrence is something else.

The S:I1132V samples are part of this proposal and could be a developing branch, but there just isn't much there yet.

**Comment by RaphaelRaphael** [comment]
Did you notice anything related to the 28362_28370 deletion ?
In this issue, i discribe a GGT -> TTT mutation that migth be basal to BA.5.2.1 and is in linkage with C5284T
https://github.com/cov-lineages/pango-designation/issues/1069

**Comment by corneliusroemer** [comment]
Please don't add growth advantage plots for such small numbers of sequences - they are meaningless, inflated and clutter the proposal.

More relevant: add date of first sequence, 5th sequence, 10th sequence, 25th sequence submitted via GISAID. Also, please add a 

Being in USA it's not so under sampled so this is too small for now and I'll close. We can reopen if it's at say 200 sequences.
