### ISSUE TITLE
BJ.1/BA.2.75 recombinant with breakpoint in S1 [>=5 sequences, 3x Singapore, 2x US as of 2022-09-12]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1058]
I noticed a potential BJ.1/BA.2.75 recombinant in today's upload from Singapore.

A more extensive search using the simple GISAID query: `E_T11A,Spike_V83A` (ORF1ab/NTD BJ.1, S2 to 3' BA.2.75) revealed that this recombinant had also been sequenced in New York state. There are potentially similar recombinants but a lack of clean sequences does not allow a proposal at this point.

Definite members of this recombinant:

```txt
hCoV-19/Singapore/11487/2022|EPI_ISL_14917761|2022-09-06
hCoV-19/Singapore/11453/2022|EPI_ISL_14917728|2022-09-06
hCoV-19/Singapore/11377/2022|EPI_ISL_14917652|2022-09-07
hCoV-19/USA/NY-PRL-220907_01F03/2022|EPI_ISL_14914850|2022-09-06
hCoV-19/USA/NY-PRL-220907_01F01/2022|EPI_ISL_14914848|2022-09-06
```

Placement by Usher:
<img width="2190" alt="image" src="https://user-images.githubusercontent.com/25161793/189707243-f211e77b-9aa9-42f7-95c0-63a19ee5ab20.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e0c8_f5c9c0.json?c=pango_lineage_usher&label=nuc%20mutations:C15738T

Given the combination of two growing lineages and the presence in various countries and recent emergence, I suggest we designate this soon.

I'm interested in your thoughts @AngieHinrichs @thomasppeacock @silcn

Edit: I've removed the West Bengal sequences as it does not necessarily belong to the cluster. The NY/SGP sequences are much closer together. h/t @sinickle

**Comment by shay671** [comment]
A traveler returning from the USA returned to Israel with a sample clustering with this clade. 
Vaccinated a year ago (3rd dose).
I'll update the GISAID ref number as soon as it'll be uploaded by the lab. 

Usher build (the sample denoted IL) :

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_417d0_cad30.json?c=pango_lineage&label=nuc%20mutations:G22577C,G22898A,T22942G,T23019C,G23040A,A23955G,T24570G,C25416T,A26275G,T26529G,T29118C

**Comment by corneliusroemer** [comment]
Thanks @shay671!

Should we designate this one due to the geographic spread and combination of two 2nd gen variants?

Rough dating of MRCA suggest this recombinant has been around for 1-3 months (~3-4 mutations to founder) so probably not very explosive but good to give a name, nonetheless given it most likely arose in India where a smaller proportion of cases are sequenced than in say England.

**Comment by shay671** [comment]
I have to say that I don't have that much experience with recombinants. I remember the topology is quite problematic with all the reversions.

Several things I noticed on those five samples you gave here :
They have three unique mutations shared by all, 2 of which are NS in the RBD (in Positions486 &490).
When looking at non BA.2.75/BJ.1 mutations in the five samples shared by some of the other 5, we see a pattern that hints at quite a diversity. 
![image](https://user-images.githubusercontent.com/80166370/190352562-907c5040-24af-41aa-ba77-db618f5e2c56.png)
Data could be seen here :
[BJ-75 rec analysis.xlsx](https://github.com/cov-lineages/pango-designation/files/9573329/BJ-75.rec.analysis.xlsx)

Recombination requires a high rate of both variants in the same place. And the diversity we see here takes us quite back if we want to trace the MRCA.  Did BJ.1 spread at that time to assume it could reach a patient and co-infect with BA.2.75?

On the other hand, the breakpoint is quite clear, BA.2.75 is clear after that breakpoint, and of the 3 BA.2.75 unique mutations in that part, one is synonymous (the other 2 are NS in regions that go through convergence)

**Comment by shay671** [comment]
Regarding the Israeli sample (I urged the lab to upload it) - 
It has 2 of the 3 mutations of BA.2.75 found in those 5, the third position is not sequenced. Same for the 3 unique non BA.2.75/BJ.1 mutations.
And it also has 7 more unique mutations. 7 of which are in EPI_ISL_14914848.

So-  it is probably connected to this. 

And it means we got a sample from California as well which got into Israel.

**Comment by FedeGueli** [comment]
This Gisaid query catches 11 samples : Spike_H146Q,Spike_Q183E,E_T11A
of which one is from Bangladesh has been uploaded today: EPI_ISL_14986860 and clusters with other three sequences found by the same query:
![Schermata 2022-09-16 alle 00 21 07](https://user-images.githubusercontent.com/87669813/190518912-2fa0b2b8-90cd-4338-9533-53e82c373128.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d32b_3a4610.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A23283T

This other one, that i think it is more accurate and specific to this lineage finds 7 : NSP13_S36P,Spike_H146Q,Spike_Q183E,E_T11A
(2 India, 2 NYC, 3 Singapore)

**Comment by corneliusroemer** [comment]
I'll designate this one give continued appearance in at least 2 countries on different continents and interesting Spike combination

**Comment by corneliusroemer** [comment]
I just realized the breakpoint must be between S:446 and S:460 - which is pretty darn narrow of a region.

Also: the BA.2.75 side has S:486S and S:490S - which is unique to the just designated BM.1.1.1.

Both BM.1.1.1 and BJ.1 are common to Bangladesh and West Bengal. So we can be pretty sure that the recombination event happened in that region too.

Furthermore, the existence of such a recombinant is indicative of high degrees of circulation of both BM.1.1.1 and BJ.1 - since  the probability of a given recombinant being created is proportional to the incidences of both parents. It's a shame there are not more sequences from Bangladesh - it seems to have quite interesting circulation.

**Comment by FedeGueli** [comment]
Great catch @corneliusroemer

**Comment by corneliusroemer** [comment]
I think this should be enough: `S:V83A, S:F486S, S:F490S`

Same for GISAID: `Spike_V83A, Spike_F486S, Spike_F490S`

**Comment by emily-smith1** [comment]
Now in USA-CA (EPI_ISL_15000639). Thanks for the quick designation to make this easier to track, @corneliusroemer!

![image](https://user-images.githubusercontent.com/84812104/191062795-97d4fc7b-fdcb-4fc2-a502-2a047a7f5a19.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2588d_88e710.json?c=userOrOld&label=nuc%20mutations:G22577C,G22898A,T22942G,T23019C,G23040A,A23955G,T24570G,C25416T,A26275G,T26529G,T29118C

**Comment by shay671** [comment]
The sample from California clustered with a sample from Israel of a passenger returning from California. 

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d513_8b07f0.json?c=pango_lineage_usher&label=nuc%20mutations:G22577C,G22898A,T22942G,T23019C,G23040A,A23955G,T24570G,C25416T,A26275G,T26529G,T29118C

**Comment by c19850727** [comment]
In Singapore's latest batch of upload (2022-09-20), there are 9 XBB among a total of 377 genomes (2 imported from Bangladesh, 1 from Malaysia, and 6 local cases).

EPI_ISL_15031191-15031194, EPI_ISL_15031199-15031202, EPI_ISL_15031899

**Comment by shay671** [comment]
I took the GISAID query by @corneliusroemer and got 34 samples today. When running those ref numbers in USHER, 14 is not being recognized yet (probably will be in the next build). But there were many subtrees. When looking at the downsampled global tree, the samples are split into two branches :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_176a1_aed2a0.json?c=userOrOld&label=nuc%20mutations:T670G,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10198T,C12880T,C17410T,C21618T,C22673T,A22688G,A22786C,C26858T,G27382C,A27383T,T27384C,A29510C
![image](https://user-images.githubusercontent.com/80166370/191527535-c08f779f-349d-44e7-a382-f502d2074793.png)


@AngieHinrichs  - any thoughts?

**Comment by corneliusroemer** [comment]
This query only yields 18, which one are you using @shay671? `Spike_V83A, Spike_F486S, Spike_F490S`

**Comment by shay671** [comment]
Nope. I used the :
E_T11A,Spike_V83A
Probably this is the source of the mistake

**Comment by corneliusroemer** [comment]
Yeah I mentioned that that query is a _broad_ one designed to not have false negatives. But there will be false positives.

**Comment by FedeGueli** [comment]
Spike_Q183E, NSP13_S36P,E_T11A i use this one.

by the way one more from India.

**Comment by FedeGueli** [comment]
23 as today one more from Australia

**Comment by FedeGueli** [comment]
4 new sequences from Philippines today

**Comment by amniewiadomska** [comment]
Just adding some observations on diversity of this lineage:
- Some genomes from Bangladesh (n=8) don't have G142D
- A subset of genomes (n=35) have (G252V) as mentioned above. 
- A subset of these have a premature stop in ORF8 (G8stop) that will likely cause it to not be expressed. n=34

**Comment by corneliusroemer** [comment]
Thanks @amniewiadomska! I noticed that the Usher tree may be wrong in that G510A aka ORF1a:G82D is not part of the founder of XBB, but rather parallel to XBB.1 - so we have two main branches: 
1) XBB.1 = S:252V
2) XBB with ORF1a:G82D

Please correct me if I'm wrong but this is the conclusion I came to after looking at all XBBs. @AngieHinrichs

**Comment by cvejris** [comment]
Rapid growth (211 seqs globally) driven by Singapore (132 seqs, 97 of which are XBB.1)

**Comment by AngieHinrichs** [comment]
> Usher tree may be wrong in that G510A aka ORF1a:G82D is not part of the founder of XBB, but rather parallel to XBB.1

Yep, I agree.  And as more sequences are added (and with more daily rounds of `matOptimize`), the order of mutations and placement of XBB within the tree might hop around a bit.  Recombinants don't really belong in trees, we're just making do with what we've got.

**Comment by corneliusroemer** [comment]
I just wanted to add a brief note that XBB has S:144-, this may not be hugely relevant but is probably good to bear in mind if one wants to recreate XBB in the lab for neutralization studies.

The deletion comes from the BJ.1 parent, which also has S:144-

All XBBs have that deletion, it's very well called by all pipelines apparently, which is great news!

<img width="2311" alt="image" src="https://user-images.githubusercontent.com/25161793/193991787-3406984d-4dd0-4e40-bc21-7ded5d3becd5.png">

**Comment by silcn** [comment]
> I just wanted to add a brief note that XBB has S:144-, this may not be hugely relevant but is probably good to bear in mind if one wants to recreate XBB in the lab for neutralization studies.
> 
> The deletion comes from the BJ.1 parent, which also has S:144-

Yeah, 144del is present in all BJ.1 too. Any lists of BJ.1 mutations that don't include it are my fault for missing it originally.

**Comment by Mild1-ai** [comment]
Now, this is a great name.
