### ISSUE TITLE
BA.5.6.2 with S:N460K in Mexico [3 seqs as of 2022-09-12]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1059]
There's some convergence going on in BA.5.6.2 in the direction of BQ.1 and other second generation BA.2

BA.5.6.2 already has S:444T and now got S:N460K on top, at least in 3 sequences from Mexico-Yucatan:

```bash
hCoV-19/Mexico/YUC_LANGEBIO_IMSS_10681/2022|EPI_ISL_14711187|2022-08-05
hCoV-19/Mexico/YUC_IBT_IMSS_9216/2022|EPI_ISL_14806056|2022-08-18
hCoV-19/Mexico/YUC_CIAD-IMSS_01016719/2022|EPI_ISL_14901897|2022-08-25
```

GISAID query: `Spike_K444T, Spike_N460K, NSP2_V447I`

**Comment by FedeGueli** [comment]
Yes this was spotted by me and @ryhisner and it is actually in Collection #26 on Covspectrum , luckily still not showing signs of growth

**Comment by FedeGueli** [comment]
Hi @corneliusroemer , since a couple of BQ.1.1 picked up convergently (i think) NSP2_V447I (Orf1a:V627I)

the right Gisaid query should be : NSP13_A389V,Spike_K444T, Spike_N460K, NSP2_V447I

**Comment by corneliusroemer** [comment]
Well, now we're suddenly at 10 lineages, so I'll designate. This is same Spike as BQ.1...

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/25161793/190918531-325c0f52-566e-41f5-97f8-f2f0afb4c214.png">

**Comment by FedeGueli** [comment]
Great move @corneliusroemer

**Comment by FedeGueli** [comment]
cc @thomaspeacock @corneliusroemer @InfrPopGen Milestone of BW.1 is missing from this issue.

Putting here the @carlottaolivero finding that not all S:N460K are the same nuc mutation, BW.1 is T22942G as BA.2.75 different from T22942A of BQ.1* and XAW.
