### ISSUE TITLE
New potential BA.5.1 + ORF1b:N1025S lineage with N_A218S + S:K444N  S:K150E S:N460K Orf8:F41C that likely arose in Russia (9 seqs, Moscow,Denmark, Germany, Israel,England)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1060]
Early proposal for a potential lineage of interest circulating in Moscow Russia.
Just two samples but given their characteristicts i feel right to propose and monitor it.

Defining mutations:
BA.5.1 + A16541G (=ORF1b:N1025S) 2278seqs 
then
N:A218S (15seqs)
then S:K444N (14seqs)
then G5305A (4seqs
then
S:K150E, S:N460K Orf8:F41C (2seqs)

List of sequences: 
EPI_ISL_14921441
EPI_ISL_14921659

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f81e_fb0500.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G28925T
![Schermata 2022-09-13 alle 00 24 21](https://user-images.githubusercontent.com/87669813/189769051-17a6e1d8-cda2-48bf-bc59-74800fc9b798.png)

Gisaid query : Spike_K444N,Spike_N460K,N_A218S

Covspectrum to monitor this lineage starting with N:A218S and S:K444N:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=N%3AA218S%2CS%3A444N&nucMutations=A16541G&nextcladePangoLineage=BA.5.1&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Interestingly the growth rate of the parental BA.5.1 Orf1b:N1025S bigger, unproposed and undesignated lineage is not far from the infamous BA.5.2 + Orf1b:1050N global lineage.
+ https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3AN1025S&nextcladePangoLineage=BA.5.1&aaMutations1=orf1b%3A1050N&nextcladePangoLineage1=BA.5.2*&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
3 more sequences of the bigger lineage **without S:N460K** : 2 from Estonia, 1 Israel.

**Comment by corneliusroemer** [comment]
This needs to grow more before we act on it.

**Comment by FedeGueli** [comment]
N:A218S already popped up in 1000+ AY.103 sequences and in AY.103 this mutation conferred a growth advantage around 15% (12-18%) :
https://cov-spectrum.org/explore/United%20States/AllSamples/Y2021/variants?nextcladePangoLineage=AY.103*&aaMutations1=N%3AA218S&nextcladePangoLineage1=Ay.103*&analysisMode=CompareToBaseline&

**Comment by corneliusroemer** [comment]
The 444N cluster is now at 23 sequences it seems. Quite feasible that it's common in under sampled area of former soviet union. So worth designating, I think. The one with 460K would then be a sublineage, so let's first designate the outer one and see what happens.

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/25161793/192889271-d32f96e7-b30c-4dcb-ba96-fe1f397d650d.png">

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/25161793/192889482-0591c900-c010-404d-8fc7-751fcaaa2c10.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_42fa4_4afab0.json?c=pango_lineage_usher&label=nuc%20mutations:G22894T

**Comment by FedeGueli** [comment]
One more sequence of this one from Germany collected 15/09 cc @corneliusroemer the parental lineage with just S:444N reached 24 sequences

**Comment by FedeGueli** [comment]
one more sequence of this uploaded yesterday from Israel: EPI_ISL_15173613 cc @shay671

 @corneliusroemer it keeps expanding the range of countries where it has been sampled.

**Comment by FedeGueli** [comment]
8 sequences for this lineage newly found in England and one more from Denmark .

**Comment by FedeGueli** [comment]
Ushering them i find 9 sequences:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e7cf_ab4b50.json?label=nuc%20mutations:C9226T,A22010G,T22942A,T28015G
<img width="1107" alt="Schermata 2022-10-03 alle 12 29 54" src="https://user-images.githubusercontent.com/87669813/193556580-d234d57c-1f5d-4a44-bb4c-708008cb8cce.png">
Splitting by countries:
3 Denmark,
2 Russia
2 Israel
1 Germany
1 England

**Comment by FedeGueli** [comment]
@corneliusroemer @InfrPopGen  maybe is ti worth to start designating the parental with S:444N??:

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28f88_d51cc0.json?branchLabel=aa%20mutations&label=nuc%20mutations:G28925T

It reached 30 sequences:
<img width="1094" alt="Schermata 2022-10-05 alle 11 57 52" src="https://user-images.githubusercontent.com/87669813/194034115-664694d3-eb44-43b6-b6e4-f2a5beeb86ad.png">

Defining mutations: ORF1b:N1025S + N_A218S + S:K444N

Gisaid query: NSP13_N102S,Spike_K444N,N_A218S
Countries : Russia, Estonia, Sweden , Usa, Denmark, Georgi, England, Germany ,Israel, Italy
Nr of sequences 28:

EPI_ISL_13894615
EPI_ISL_14320232
EPI_ISL_14423767
EPI_ISL_14423936
EPI_ISL_14437634
EPI_ISL_14579096
EPI_ISL_14698508
EPI_ISL_14698660
EPI_ISL_14701469
EPI_ISL_14835506
EPI_ISL_14840221
EPI_ISL_14840238
EPI_ISL_14921441
EPI_ISL_14921659
EPI_ISL_14934749
EPI_ISL_14934835
EPI_ISL_14959917
EPI_ISL_15018341
EPI_ISL_15018405
EPI_ISL_15019275
EPI_ISL_15069535
EPI_ISL_15080465
EPI_ISL_15094691
EPI_ISL_15147298
EPI_ISL_15173613
EPI_ISL_15208263
EPI_ISL_15209791
EPI_ISL_15210631

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.1.29 with 9 newly designated sequences, and 1 updated designation from BA.5.1. Defining mutation G22894T (S:K444N) (following G28925T (N:A218S)).
If you can find time, please open a new proposal for the S:N460K sub-clade of this, assuming it continues to expand. A dedicated issue for the sub-lineage will help keep the milestones tidy and reduce risk of the sub-clade getting overlooked.

**Comment by FedeGueli** [comment]
Thx vm @InfrPopGen of course when i will spare some time to do it!
