### ISSUE TITLE
Potential BA.2.75.4 sub-lineage with S:R346T in Australia, England, India, Singapore [12 sequences]

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#1063]
Description: Sub-lineage of BA.2.75 with S:L452R 
Earliest Sample Collection Date: 08/16/2022 uploaded from Singapore [Travel history: India]
Most recent Sample Collection Date: 09/01/2022 from England
Countries: England (1), India (1), Singapore (1)
Number of sequences: 4

Found 7 BA.2.75* sequences with S:L452R and S:346T ( using Nextclade tool was able to identify 2 sequences as BA.2.75.2* and 1 as BA.2.75.6* )

BA.2.75.2* (S:346T, 486S, 1199N) with additional SpikeL452R will be proposed elsewhere [Both from USA (Texas, DC)]

The lone BA.2.75.6* sequence has L452R and M:D3N! (contains big FS in N region; not a high quality sequence)

![image](https://user-images.githubusercontent.com/98380390/189989336-b247951f-6464-445a-a8c0-53a8ad1cc545.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1925b_b68a0.json?branchLabel=aa%20mutations&c=gt-S_346,452,486&label=nuc%20mutations:C4586T,A22001G,T22016C,G22331A

Cov-Spectrum Query:  BA.2.75.4* (Nextclade) + S:R346T
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AR346T&nucMutations=C9532T%2CG19962T%2CT22917G&

**Comment by RajLABN** [comment]
One more BA.2.75* plus Spike 346T/452R sequence... from Austria [EPI_ISL_14948276]

**Comment by RajLABN** [comment]
BA.2.75.2* plus Spike 346T/452R .. from North Carolina, USA [EPI_ISL_14982602] - will wait for few more sequences to propose it separately

**Comment by RajLABN** [comment]
7 more BA.2.75.4* from New South Wales, Australia with Spike 346T/452R (all have 486I as well). This seems to be picking up!

Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_429bf_46d600.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C9532T,G19962T,T22917G
![image](https://user-images.githubusercontent.com/98380390/190640674-831c0db5-578a-4d69-ab1a-bb43c89e6c6e.png)

**Comment by corneliusroemer** [comment]
I've added the Australian S:346T and S:486I cluster as BR.2 as that is the most significant so far with strong similarities to BA.2.75.2 with addition to S:452R.

The others are very small clusters that are not monophyletic (probably). The English one could share ancestor with Australia but not necessarily likely given quite different mutations between the two. The India/Bahrain/Singapore one is different from the other two due to 8602A mutation.

Please update the issue if the other clusters grow @RajLABN

**Comment by FedeGueli** [comment]
credits also to @josetteshoenma who first spotted the S:486I sublineage.

**Comment by RajLABN** [comment]
One more BA.2.75.2* with Spike_L452R from North Carolina [EPI_ISL_15023190].. [Total 5 such sequences - 2 each from NC, TX and 1 from DC - all from USA]

**Comment by RajLABN** [comment]
One more BA.2.75.2* with Spike_L452R from New York [EPI_ISL_15043427]

**Comment by corneliusroemer** [comment]
Wait - is this now about BA.2.75.2* with 452R or BA.2.75.4 with S:346T?

We should have separate issues - and ideally also make sure that the lineages are monophyletic. As I noted above, the given clusters were _not_ monophyletic.

**Comment by corneliusroemer** [comment]
A general query to catch 346T and 452R in BA.2.75 is this: `E_T11A,NSP3_S403L,Spike_L452R, Spike_R346T`

But for a proposal to be designable, we need an Usher tree to see how things hang together - where they belong etc.

**Comment by corneliusroemer** [comment]
The Singapore and Austria ones cluster together - they should be designable as BR.3

<img width="1595" alt="image" src="https://user-images.githubusercontent.com/25161793/191576102-31681ad6-c983-402c-9fdf-152586dee3a9.png">

Also the BA.2.75.2 in the US are pretty well clustered together. 7 samples that share around 4 mutations each
<img width="1610" alt="image" src="https://user-images.githubusercontent.com/25161793/191576336-c789f315-91a1-4771-8007-607e8a62107c.png">

**Comment by corneliusroemer** [comment]
The two clusters I mentioned have been designated as BR.3 and CA.1 - so I'll close this for now. Let's reopen if another such lineage should be designated.

**Comment by jinyu-ncbi** [comment]
I am a little confused. BR.3 is defined with BA.2.75.4 + S:346T, and BR.2 is defined as BA.2.75.4 + S:346T + S:486I. Isn't BR.2 a sublineage of BR.3?

**Comment by RajLABN** [comment]
@corneliusroemer's BA.2.75* tree -  https://nextstrain.org/staging/nextclade/sars-cov-2/21L?label=clade:22D%20%28Omicron%29

**Comment by corneliusroemer** [comment]
No @jinyu-ncbi it's not so simple - there's more to it than Spike mutations. If you check the tree you see that 346T arose multiple times independently.

**Comment by JosetteSchoenma** [comment]
2 more Australian BA.2.75.4 plus R346T plus F486I. 9 in total now. BR.2.

**Comment by MCB6** [comment]
One new CA.1 has just been reported from Russia but it lacks F486S, D1199N or 604I (EPI_ISL_15418663). The sequence doesn't have gaps over the S gene. Is it a reliable call? 
It may be important because so far, none of @corneliusroemer 's tier 4+ strains have been detected in Russia. This CA.1 is supposed to be the first of them...
