### ISSUE TITLE
Sublineage of BA.5.2.16 with S:K444M, S:N460K (7 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1065]
**Description**
**Sub-lineage of:** BA.5.2.16
**Earliest sequence:** 2022-8-21, USA, Wisconsin — EPI_ISL_14849494
**Most recent sequence:** 2022-8-31, USA, California — EPI_ISL_14941093
**Countries circulating:** USA (6), England (1). States within USA: California (1), Illinois (1), Rhode Island (1), Texas (2), Wisconsin (1). 
**Number of Sequences:** 7 (two are not on GISAID yet)
**GISAID Query:** Spike_K444M, Spike_N460K, NSP5_A94V
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2 & S:K444M & S:N460K & ORF1a:A3357V
**Substitutions on top of BA.5.2:**
**Spike:** K444M, N460K
**ORF1a:** A3357V (NSP5_A94V), A3697V (NSP6_A128V)
**Nucleotide:** C10335T, C11355T, A22893T, T22942G

**USHER Tree**
Temporary link due to Usher not functioning this morning. Permanent link will be attached below soon.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1666d_12c620.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C10335T,A22893T,T22942G
https://nextstrain.org/fetch/ 
![image](https://user-images.githubusercontent.com/33738461/190145083-6152a6e0-d609-4a05-acf3-83dd82c97de1.png)

**Evidence**
Spike mutations K444M and N460K have been two of the most convergent mutations in the past several months. K444M and K444T seem to provide higher growth advantages for lineages carrying them than K444N and K444R. NSP5 mutations are rare, though ORF1a:A3357V (NSP5_A94V) has evolved countless times independently in dozens of different lineages, indicating it could confer an advantage in some contexts. 

Though there are only seven sequences, six in the United States, the US sequences are widespread, including the US West Coast (California), East Coast (Rhode Island), Deep South (Texas), north Midwest (Wisconsin), and central Midwest (Illinois). The one case in England indicates there could be some international spread as well. There are no amino acid differences between these seven sequences, and six of the seven are identical on the nucleotide level. Only the Wisconsin sequence has two synonymous nucleotide changes compared to the other six. This very wide geographic distribution and minimal diversity is indicative of rapid spread. 

Also of note, these BA.5.2 sequences have the ORF1b:T1050N mutation that has been shown to confer a 10-20% growth advantage over BA.5.2 sequences that lack it. 

The ORF1a:A3697V mutation is shared with about 950 other BA.5.2 sequences and is therefore not unique to this lineage. 

**Genomes**
Two of the seven sequences, including the one from England, are not yet on GISAID and are therefore not included below.
<details>
<summary>Genomes</summary>
EPI_ISL_14833076, EPI_ISL_14849494, EPI_ISL_14866417,
EPI_ISL_14869419, EPI_ISL_14941093
</details>

**Comment by corneliusroemer** [comment]
Thanks @ryhisner - the uploads have occurred over the past week. Low diversity and wide spread suggests significant growth.

Wisconsin and Illinois samples cluster together both having C10335T and C11335T - though these sites seem masked by Usher. @AngieHinrichs where can I see the sites masked by Usher?

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/25161793/190159152-a8cc2826-301d-43ae-9445-978de24d9451.png">

We should be able to designate this pretty soon.

This is how Nextclade places them, the S:444M branch is due to the homplasy - I shall split this join branch in a future version.

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/25161793/190159114-f29823eb-d073-49e5-8c71-8625a07966e9.png">

**Comment by corneliusroemer** [comment]
This lineage is a sublineage of BA.5.2 + ORF1b:T1050N + ORF1a:A3357V - which is an Indonesia lineage.

It's clearly much more frequent in Indonesia (factor 10-100) than anywhere else - so this is worth designating as an intermediate. It also means this lineage gets an alias.

There are a few interesting sublineages of that Indonesian lineage, e.g. with S:445A, S:444K, S:255F. So overall worth giving a name.

I'll start with the parent.

<img width="1606" alt="image" src="https://user-images.githubusercontent.com/25161793/190165719-c363649e-c479-41f7-b993-77a8d8d6c9cd.png">

**Comment by FedeGueli** [comment]
Hi Cornelius do you think the two early april indonesian sequences of BA.5.2 + Orf1b:1050N are reliable?
The first from South Africa are in the same days,
while already in march 2 sequences from Malaysia that  in the time spanning between 1/03 and 1/05 was the 2nd country for number of BA.5.2+Orf1b:1050N after South Africa :
13/47 Malaysia, 23/47 South Africa.

i tend to think still it was SA the BA.5.2 + Orf1b:1050N country of origin.

**Comment by FedeGueli** [comment]
One more from England : EPI_ISL_14973537

**Comment by corneliusroemer** [comment]
Excellent spot @FedeGueli - I had missed this. I think it may be worth designating soon.

And I'm not saying that Indonesia was where the mutation happened - but it is the country where this lineage grew big, maybe it was the lucky earliest BA.5 that got there first.

**Comment by FedeGueli** [comment]
Ok thx @corneliusroemer agree wirh you

**Comment by shay671** [comment]
Hi @corneliusroemer 
I looked at the data of the BA5.2.16, and it seems to evolve not directly from BA.5.2 but from a mediator branch with :
C16616A
C27513T
C27012T
And only then:
C11355T

**Comment by shay671** [comment]
Regarding BU.1 I see a deletion in 21992-21994
@corneliusroemer @ryhisner

**Comment by alurqu** [comment]
@shay671 I'm seeing that C16616A (ORF1b:T1050N) -> C27513T -> C27012T pattern repeatedly.  I don't know why C27513T and then C27012T seem to follow C16616A before the diversification, but that is what I see.  I have a discussion in an [Issue 1061 comment](https://github.com/cov-lineages/pango-designation/issues/1061#issuecomment-1246208566) about that.

Due to this I've actually added an override in my search software to not count C16616A/ORF1b:T1050N, C27513T, and C27012T as not part of the BA.5.2 baseline mutation set.

**Comment by ryhisner** [comment]
Thank you, @shay671! I've edited the title and original post to include the Y144 deletion.

**Comment by FedeGueli** [comment]
Great catch on the del @shay671 . Yes BA.5.2 has 3 main branches the first is BA.5.2.1 and the second one starts with G12310A then
C16616A (ORF1b:T1050N), C27513T, and C27012T.
For what i see these 4 mutations are always together. when i spotted one of them missing it then came back further in the tree. 
But this is just my observational.point of view while scanning trees looking at variants.

**Comment by FedeGueli** [comment]
Just putting here the @carlottaolivero finding: S:N460K here is from T22942G  as BA.2.75 and not T22942A as BQ.1.1 and XAW

**Comment by alurqu** [comment]
As a note, I've started to see BA.5.2+ORF1b:T1050N without C27513T and C27012T.  An example is [BA.5.2+ORF1b:T1050N+14670T+27800T+N:E136D+S:R346T](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=N%3A136D%2CORF1b%3A1050N%2CS%3A346T&nucMutations=14670T%2C27800T&nextcladePangoLineage=BA.5.2) which at this point is likely just a curiosity.

**Comment by FedeGueli** [comment]
> As a note, I've started to see BA.5.2+ORF1b:T1050N without C27513T and C27012T. An example is [BA.5.2+ORF1b:T1050N+14670T+27800T+N:E136D+S:R346T](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=N%3A136D%2CORF1b%3A1050N%2CS%3A346T&nucMutations=14670T%2C27800T&nextcladePangoLineage=BA.5.2) which at this point is likely just a curiosity.

It is not a curiosity it is a recombinant likely. @c19850727 @josettechoenma could you help here?

**Comment by FedeGueli** [comment]
@alurqu I have analyzed it: it likely a recombinant between BA.5.2+Orf1b:1050N+S:346T and BE.4+29868A:

https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=29868A&nextcladePangoLineage=BE.4*&aaMutations1=N%3A136D%2CORF1b%3A1050N%2CS%3A346T&nucMutations1=14670T%2C27800T&nextcladePangoLineage1=BA.5.2&analysisMode=CompareEquals&

The BE.4 part is from 23608 to N
![Schermata 2022-10-22 alle 10 58 04](https://user-images.githubusercontent.com/87669813/197330765-cfc39d9e-207c-4ad9-86c5-ae45c8a958ae.png)

The BA.5.2 part is from 0 to 23608 
![Schermata 2022-10-22 alle 11 11 54](https://user-images.githubusercontent.com/87669813/197331372-5d8830c3-d183-4443-a92b-0b8571f693a8.png)


I excluded that S:346T comes from BE.4.1 for the presence of  Nuc: G23608T in 100% of BE.4.1+29868A  

So it likely comes from the still undesignated  BA.5.2*+Orf1b:1050N + S:346T 
as BA.5.2.6 (45.28%)
BA.5.2.13 (15.30%)
BA.5.2.34 (13.79%)
BA.5.2.35 (9.68%)
BA.5.2.20 (4.47%)
CP.1 (3.21%)
BA.5.2 (3.02%)
CR.1 (2.57%)


@alurqu So please propose it!! great spot! or @corneliusroemer @InfrPopGen  could you designate from here directly? 

Ok i will open directly from here as an issue.

CovSpectrum query : BA.5.2 (Nextclade) + C27800T + N:E136D, ORF1b:T1050N, S:R346T
finds 108 seqs:
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=N%3A136D%2CORF1b%3A1050N%2CS%3A346T&nucMutations=27800T&nextcladePangoLineage=BA.5.2&aaMutations1=Orf1b%3A1050N&nextcladePangoLineage1=BA.5.2*&

Sequence list:
[contributors (2).csv](https://github.com/cov-lineages/pango-designation/files/9843985/contributors.2.csv)


Gisaid Query: -NSP13_M233I,N_E136D,Spike_R346T,NSP13_T127N finds 123 Viruses

Tree:
![Schermata 2022-10-22 alle 11 33 57](https://user-images.githubusercontent.com/87669813/197332269-fc6f218a-544d-48b4-b221-99f52cb4cfb9.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_327b4_3b62c0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C27800T
