### ISSUE TITLE
BL.1 sublineage with S:G261D, S:V308L (5 seq. Belgium, Austria)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1066]
Proposal for a sublineage of BL.1
Earliest sequence: 30.08.2022 (Belgium)
Countries detected: Belgium (1), Austria (4)

Defining mutation:
G22344A = S:G261D
G22484T = S:V308L
GISAID query: Spike_G261D, Spike_V308L, Spike_D574V

Potential BL.1 sublineage with S:G261D and S:V308L showed up in todays Austria upload. So far 5 sequences from two countries (Austria and Belgium).

Unfortunately Usher is not working for me today. 

![grafik](https://user-images.githubusercontent.com/102166254/190154516-ea3913ee-f866-4aff-a550-d951970ebaf6.png)

![grafik](https://user-images.githubusercontent.com/102166254/190152104-e5801fc5-96d7-4fa4-a3bc-d1d694be97a4.png)

![grafik](https://user-images.githubusercontent.com/102166254/190151792-54d56123-5578-47fc-a715-1a62a842cd5d.png)

EPI_ISL_14916836, EPI_ISL_14948262, EPI_ISL_14948266,
EPI_ISL_14948269, EPI_ISL_14948282

**Comment by corneliusroemer** [comment]
Thanks! I also saw these sequences. I'd say we wait for a few more days and/or sequences to see whether there are intermediates.

**Comment by agamedilab** [comment]
Now with Usher tree:

![grafik](https://user-images.githubusercontent.com/102166254/190334863-04dd48e0-c611-4df0-a52f-ad43d9212127.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1154e_2ca5a0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A25506G

**Comment by agamedilab** [comment]
+1 from Austria independet lab (hCoV-19/Austria/Medilab_1176/2022)

![grafik](https://user-images.githubusercontent.com/102166254/190370964-4f0e77a3-cdc1-4925-86ee-3cee27154524.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3b2a0_2e7280.json?branchLabel=aa%20mutations&c=pango_lineage&label=nuc%20mutations:G22484T,T25476C

**Comment by agamedilab** [comment]
![grafik](https://user-images.githubusercontent.com/102166254/190860480-3d4949c7-eb0a-4cf0-9e66-fc09feeb3486.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AG261D%2CS%3AV308L%2CS%3AD574V&

**Comment by FedeGueli** [comment]
I and i think @ryhisner noticed an overepresentation of S:261 in different lineages in Japanese sequences a dozen days ago, strongly suggesting some kind of artifact, i dont know if could be the same here.

**Comment by corneliusroemer** [comment]
Another upload from yet another Austrian lab.

Given we've seen an ancestor in Austria this could well be a local Austrian cluster.

I'll designate this given the fact it's in a growing lineage, has epi linkage to Austria and two S1 mutations.

**Comment by agamedilab** [comment]
If you have time i would be very happy if a "designate" label could be add to issue. Many thanks and all the best! @InfrPopGen

**Comment by FedeGueli** [comment]
Thx @agamedilab i ve missed this one got designated for that! Added now to CovSpectrum Collection # 24
