### ISSUE TITLE
Example of possibly unrelated B.1.617.2+K417N being assigned B.1.617.2.1/AY.1

### ISSUE THREAD

**Issue by rmcolq** [cov-lineages/pango-designation#107]
[B.1.617.2_K417N_USA_2021-06-05.ml.tree.pdf](https://github.com/cov-lineages/pango-designation/files/6632658/B.1.617.2_K417N_USA_2021-06-05.ml.tree.pdf)

Apparently epi-unrelated US samples including the following:
USA/IL-CDC-ASC210063383/2021|EPI_ISL_2283860|2021-05-13
USA/WI-UW-5228/2021|EPI_ISL_2340841|2021-05-18
USA/CA-CDC-FG-035491/2021|EPI_ISL_2371569|2021-05-22
USA/CA-CDC-FG-035351/2021|EPI_ISL_2371642|2021-05-21
USA/CA-CDC-FG-035389/2021|EPI_ISL_2371666|2021-05-22

None of these are in the designation list, so might be helpful to add them if they meet ambiguity criteria

**Comment by AngieHinrichs** [comment]
Good find @rmcolq!  That looks like a different lineage to me.  I uploaded your samples, along with several samples from #95 (AY.1), to usher with the maximum subtree size (5000) and they were placed in separate subtrees.  Even in the downsampled global tree view they look quite distinct, separated by many nucleotide mutations:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-107-singleSubtree.json?branchLabel=Spike%20mutations&label=nuc%20mutations:G210T,G15451A,C16466T,C21618G,G21987A,T22917G,C22995A,C23604G,G24410A,C25469T,T26767C,T27638C,C27752T,A28461G,G28881T,G29402T,G29742T

Here's a zoomed-in subtree view with your samples and the most closely related samples in the UCSC tree (all USA):
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-107-subtree2.json?branchLabel=Spike%20mutations&c=pango_lineage&label=nuc%20mutations:T3055C,G3701A,C17336T,C18570T,G22813T

**Comment by rmcolq** [comment]
I can't take the credit - someone else flagged them in a slack channel. So these are still B.1.617.2 and should be added to the designation list to help prevent them being assigned AY.1?

**Comment by rambaut** [comment]
This 2nd K417N lineage has expanded quite quickly and should now be given its own sublineage of B.1.617.2. This will also help distinguish these lineages.

**Comment by rambaut** [comment]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/686405/121879910-4a4ca680-cd05-11eb-94e2-f1a625779233.png">

**Comment by rambaut** [comment]
Yes - this would be `AY.2`. I guess the question that needs to be discussed is whether the Indian sequences should be included in `AY.2`? - Their distinguishing feature would be presence of `K417N` (independently of `AY.1`). But The USA lineage is clearly an epidemiologically distinct lineage.

The options are - 
1) Include the Indian and USA ones as `AY.2`
2) Include only the USA ones as `AY.2` but designate some of the Indian ones with `K417N` as B.1.617.2 to allow assignment.
3) Include the Indian ones a `AY.2` and the USA ones as `AY.2.1`

**Comment by rmcolq** [comment]
Ah, sorry, I missed this while the PR was sitting open. I think 3 more clear than 1 or 2?

In that tree there is only one India sample with an hCov prefix - are the others not on GISAID?

**Comment by rambaut** [comment]
Not on GISAID I think. So leave them for now
