### ISSUE TITLE
Potential BA.4.6* sublineage with S:D1199N mutation - 25 sequences mainly in USA

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#1072]
BA.4.6* + S:D1199N (and picking up others as well)

Early sample collection date: 6/29/22 from North Carolina, USA 
Latest: 8/29/22 from New Jersey

Shares this mutation with the high flying BA.2.75.2*

Defining mutations:
BA.4.6 (S:346T) + S:D1199N (most have ORF1a:R226K)

List of sequences
EPI_ISL_13726834, EPI_ISL_13849906, EPI_ISL_13849919,
EPI_ISL_13849924, EPI_ISL_13849926, EPI_ISL_14007842,
EPI_ISL_14145697, EPI_ISL_14186180, EPI_ISL_14287393,
EPI_ISL_14331657, EPI_ISL_14337173, EPI_ISL_14428694,
EPI_ISL_14451775, EPI_ISL_14476002, EPI_ISL_14476466,
EPI_ISL_14476680, EPI_ISL_14626300, EPI_ISL_14742875,
EPI_ISL_14848658, EPI_ISL_14852136-14852137, EPI_ISL_14897316,
EPI_ISL_14898918, EPI_ISL_14910387, EPI_ISL_14912637,

Gisaid query: Spike_L452R, Spike_R346T, Spike_D1199N

CovSpectrum query: https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?aaMutations=s%3Ad1199n&nextcladePangoLineage=BA.4.6*

Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9a33_38daf0.json?branchLabel=aa%20mutations&label=nuc%20mutations:G25157A

![image](https://user-images.githubusercontent.com/98380390/190507033-d1dfbc18-fa3d-46bc-9084-c7e27d469400.png)

**Comment by corneliusroemer** [comment]
It's taken 2 months to quintuple on GISAID - at that rate it'll only get to 100 sequences in 2 months, but by that time BA.4.6 will be pretty much gone.

Being from US and not under sampled region this sounds too small to be very relevant. I'll close for now, let's reopen if this picks up speed - if ever.
