### ISSUE TITLE
BA.4.1 lineage with Orf3a:G49V, S:N354D, S:R346T circulating in France (57seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1073]
Yesterday i spotted this sublineage of BA.4.1 with a double S (RBD) mutation: S:N354D, S:R346T.
It is already quite big and it seems fast growing especially in France. 

Defining mutations BA.4.1 + G29179A + Orf3a:G49V + S:N354D + S:346T

Tree:
![Schermata 2022-09-16 alle 01 24 55](https://user-images.githubusercontent.com/87669813/190525603-9f247cf9-1b54-4a8d-94e4-7a48def93393.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_258c7_3b35d0.json?branchLabel=aa%20mutations&c=pango_lineage&label=nuc%20mutations:G29179A

Interestingly seems that the lineage circulating and growing in France is defined by a further NUC mutation:C21910A (silent: S:S116S)
and it has been already  exported to Italy, Belgium
![Schermata 2022-09-16 alle 01 26 12](https://user-images.githubusercontent.com/87669813/190525744-28da65b3-9516-4d80-ab3d-b41597fc9aed.png)

A second smaller branch is defined by C29784T and this one too seems circulating through August and a sub-branch of it acquired a mutation of interest S:444R

![Schermata 2022-09-16 alle 01 29 41](https://user-images.githubusercontent.com/87669813/190526021-d07b0f1a-9ad6-4d1b-8c01-50d9fce82299.png)

Gisaid Query :Spike_N354D,SPike_R346T,Spike_V3G,
finds 57 sequences: 
<details>
<summary>Expand for EPI_ISLs</summary>
**EPI_ISL_13655828** - First sequence ( England) 30/06
EPI_ISL_13881961
EPI_ISL_13956302
EPI_ISL_14173020
EPI_ISL_14173314
EPI_ISL_14196743
EPI_ISL_14389598
EPI_ISL_14448903
EPI_ISL_14450752
EPI_ISL_14495869
EPI_ISL_14527352
EPI_ISL_14544027
EPI_ISL_14562777
EPI_ISL_14563244
EPI_ISL_14568216
EPI_ISL_14572924
EPI_ISL_14602744
EPI_ISL_14647172
EPI_ISL_14648162
EPI_ISL_14707403
EPI_ISL_14707404
EPI_ISL_14771153
EPI_ISL_14791137
EPI_ISL_14792032
EPI_ISL_14792114
EPI_ISL_14792122
EPI_ISL_14792197
EPI_ISL_14798133
EPI_ISL_14812721
EPI_ISL_14816405
EPI_ISL_14816877
EPI_ISL_14817281
EPI_ISL_14817427
EPI_ISL_14818164
EPI_ISL_14818274
EPI_ISL_14819191
EPI_ISL_14829199
EPI_ISL_14838720
EPI_ISL_14838967
EPI_ISL_14860727
EPI_ISL_14860797
EPI_ISL_14919896
**EPI_ISL_14935308** -Last sequence Denmark 06/09
EPI_ISL_14942123
EPI_ISL_14942280
EPI_ISL_14942389
EPI_ISL_14951654
EPI_ISL_14955512
EPI_ISL_14955633
EPI_ISL_14960191
EPI_ISL_14960224
EPI_ISL_14961470
EPI_ISL_14971328
EPI_ISL_14981719
EPI_ISL_14981877
EPI_ISL_14981887
EPI_ISL_14981938

</details>

CovSpectrum query : S:354D, S:346T, Orf3a:G49V
finds 45 sequences 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A354D%2CS%3A346T%2COrf3a%3AG49V&

A growth advantage comparison with high transmissible BA.5.2 +Orf1b:1050N baseline finds a significant advantage, still too early to think it is reliable.

Carrying a double RBD mutations i will keep this proposed lineage especially monitored cc @corneliusroemer

PS: @AngieHinrichs could you take a look at the tree before G29179A please  ? On Usher there is a reversion of both deletions in 69/70 and orf1a but i cant see them on Nextclade , so i suppose they arent real.

**Comment by AngieHinrichs** [comment]
> PS: @AngieHinrichs could you take a look at the tree before G29179A please ? On Usher there is a reversion of both deletions in 69/70 and orf1a but i cant see them on Nextclade , so i suppose they arent real.

Ah, thanks for pointing that out @FedeGueli!  Those are false "substitutions" that frequently appear in genome assemblies from pipelines that can't recognize deletions.  I need to mask out the BA.4-specific deletions in the BA.4 branch.  Those "substitutions" and "reversions" on 686, 694, 21767, and 21770 should disappear within a few days.  They are causing a chunk of BA.4.6 to be misplaced elsewhere on that branch, too.

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs!  yeah probably in the upper side of that tree??  i will recheck in some days and publish again once updated. Thank you very much.

**Comment by AngieHinrichs** [comment]
Yep, the upper side by Nextstrain view, lower side by taxonium view.  :)

**Comment by corneliusroemer** [comment]
Thanks - this one is really interesting. There's even a S:444R with 2 sequences inside 😬 

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/25161793/190879808-c0e21bcf-a553-4e54-a380-410d01b124ba.png">

I'll designate, just have to figure out whether it's a child of BA.4.1.9 (suggested by Nextclade but may be wrong).

**Comment by FedeGueli** [comment]
1 more sequence from Connecticut plus 2 from France
