### ISSUE TITLE
Potential BA.5.2+ORF1b:T1050N Sublineage with C27513T, C27012T, ORF8:P93S, and S:R346I (30 seqs; UK, Canada, USA, Iceland, and Sweden)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1074]
There may be a BA.5.2 sublineage with ORF1b:T1050N (C16616A), C27513T, C27012T, ORF8:P93S (C28170T), and S:R346I (G22599T) first detected in England, United Kingdom.

As of 2022-09-15, Cov-Spectrum reports 30 BA.5.2+ORF1b:1050N+ORF8:93S+S:346I+27012T+27513T sequences with good quality control scores:
![BA 5 2+ORF1b_1050N+ORF8_93S+S_346I+27012T+27513T-Counts](https://user-images.githubusercontent.com/88959107/190556565-81973128-1db0-47b0-b84d-8d259aa5b375.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2+%26+ORF1b%3AT1050N+%26+ORF8%3AP93S+%26+S%3AR346I+%26+C27012T+%26+C27513T&nextcladeQcOverallScoreTo=29&

As of 2022-09-15 and considering only sequences with good quality control scores, Cov-Spectrum calculates a significant positive growth advantage compared to BA.5.2* in the United Kingdom:
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2*&variantQuery1=nextcladePangoLineage%3ABA.5.2+%26+ORF1b%3AT1050N+%26+ORF8%3AP93S+%26+S%3AR346I+%26+C27012T+%26+C27513T&analysisMode=CompareToBaseline&nextcladeQcOverallScoreTo=29&

As of 2022-09-15 and considering only sequences with good quality control scores, Cov-Spectrum calculates a significant positive growth advantage compared to BA.5* in the United Kingdom: 
Source: https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABA.5.2+%26+ORF1b%3AT1050N+%26+ORF8%3AP93S+%26+S%3AR346I+%26+C27012T+%26+C27513T&analysisMode=CompareToBaseline&nextcladeQcOverallScoreTo=29&

As of 2022-09-15, UShER shows all of the GenBank samples are on a single subtree:
![BA 5 2+ORF1b_1050N+ORF8_93S+S_346I+27012T+27513T-UShER](https://user-images.githubusercontent.com/88959107/190556395-5423797e-8c23-4096-a3d7-91ae2094379d.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/09/singleSubtreeAuspice_genome_BA.5.2%2BORF1b_1050N%2BORF8_93S%2BS_346I%2B27012T%2B27513T.json?branchLabel=aa%20mutations&c=gt-S_346&label=nuc%20mutations%3aG12310A

To distinguish mutation order between ORF8:P93S and S:R346I, by not filtering for ORF8:P93S we see that UShER now places S:R346I after ORF8:P93S in the tree:
![BA 5 2+ORF1b_1050N+S_346I+27012T+27513T-UShER](https://user-images.githubusercontent.com/88959107/190556434-00f9bb86-4c9f-4f94-ba40-0253f4908595.png)
(To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/09/singleSubtreeAuspice_genome_BA.5.2%2BORF1b_1050N%2BS_346I%2B27012T%2B27513T.json?branchLabel=aa%20mutations&c=gt-S_346&label=nuc%20mutations%3aG12310A)
where the mutation order was still ambiguous on 2022-09-13 as [referenced in Issue 1061 comments](https://github.com/cov-lineages/pango-designation/issues/1061#issuecomment-1246208566):
![BA 5 2+ORF1b_1050N+S_346I_27012T+27513T_untrimmed_20220913](https://user-images.githubusercontent.com/88959107/190056749-13bd1332-42d2-42a0-86b0-60e13a4363f5.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/09/singleSubtreeAuspice_genome_BA.5.2%2BORF1b_1050N%2BS_346I%2B27012T%2B27513T_untrimmed_20220913.json?branchLabel=aa%20mutations&c=gt-S_346&label=nuc%20mutations%3aG12310A

First GenBank sequence: England, United Kingdom 2022-07-26 

Most Recent GenBank sequence: Georgia, USA 2022-08-27

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at
[Support-BA.5.2+ORF1b_1050N+ORF8_93S+S_346I+27012T+27513T.zip](https://github.com/cov-lineages/pango-designation/files/9580691/Support-BA.5.2%2BORF1b_1050N%2BORF8_93S%2BS_346I%2B27012T%2B27513T.zip)

The closest Outbreak.info link for this potential lineage (nucleotide mutations are not supported) is https://outbreak.info/situation-reports?pango=BA.5.2&muts=ORF1b%3AT1050N&muts=ORF8%3AP93S&muts=S%3AR346I. 

This sublineage is proposed at a low sequence count in accordance with the suggestion of [Issue 865](https://github.com/cov-lineages/pango-designation/issues/865) and in relation to the discussion on [Issue 1061](https://github.com/cov-lineages/pango-designation/issues/1061).

**Comment by corneliusroemer** [comment]
I think this is both too small and slow to be designated at this point.

There's already a fitter BA.5.2 + ORF1b:T1050N with S:346T which is more beneficial (BA.5.2.6).

I'll close this for now - we can reopen if something interesting happens in it.

Growth advantage is not reliable for such few sequences. We should only use it above 200 say.
