### ISSUE TITLE
Potential XAZ sublineage with S:E1182Q (G25106C) in Japan (17 seqs. as of 2022/09/16)

### ISSUE THREAD

**Issue by takaabe8050** [cov-lineages/pango-designation#1075]
By Japan COVID-19 Open Data Consortium

Description
Sub-lineage of: XAZ (17 sequences)
Earliest sequence: 2022/06/30 (Japan/PG-272678/2022, EPI_ISL_14131164)
Most recent sequence: 2022/08/08 (Japan/4GB-119/2022, EPI_ISL_14784989)
Countries circulating: Japan only

Associated mutations
G25106C (S:E1182Q)
T1906C (synonymous, ORF1ab:547)

Genomes
[GenomeList.txt](https://github.com/cov-lineages/pango-designation/files/9582652/GenomeList.txt)

Evidence
UShER tree
![Tree](https://user-images.githubusercontent.com/89957075/190604558-9156d44b-df14-40f6-b64d-a01927edfdf4.PNG)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e7fa_42f070.json?branchLabel=aa%20mutations&c=pango_lineage_usher

covSPECTRUM

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AE1182Q&nextcladePangoLineage=XAZ&

**Comment by corneliusroemer** [comment]
@takaabe8050 Thanks for the proposal - I'd not publish growth advantages when there are so few sequences. Given it's only one extra S1 and growth is limited I'd wait for more samples before designating this. Thanks nonetheless :)

**Comment by takaabe8050** [comment]
@corneliusroemer 
Two more sequences from Japan.
Japan/TKYmbc5324/2022
Japan/TKYhug6500/2022

**Comment by InfrPopGen** [comment]
Thanks again for proposing this one. It looks like there's been little activity over the past couple of months, and still very few sequences (since June 2022). Consequently, this one is being closed; however, should it show a future growth explosion, please feel free to request reopening or re-propose.
