### ISSUE TITLE
Proposal for a sublineage of BA.2.10 with S:K147E, S:N450D, S:G1219V, S:L8F, ORF3a:T175I, ORF3a:S117T (106 seq. mostly India, US; 16.09.22)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1076]
Proposal for a sublineage of BA.2.10
Earliest sequence: 06.06.2022 (India)
Countries detected: India(105), USA (1)

Defining mutation:
G21586T = S:L8F
G25218T = S:G1219V
A22910G = S:N450D
G25742T = ORF3a:S117T
C25916T = ORF3a:T175I

GISAID query: Spike_L8F, Spike_G1219V, Spike_N450D

![grafik](https://user-images.githubusercontent.com/102166254/190651160-a4d98894-6e29-48ab-b980-95de04ffb8de.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ea80_4745b0.json?branchLabel=aa%20mutations&c=pango_lineage_usher

![grafik](https://user-images.githubusercontent.com/102166254/190648649-8621328e-4966-44d7-b8e8-412e5cd09159.png)

EPI_ISL_14890903, EPI_ISL_14891453, EPI_ISL_14891745, EPI_ISL_14891392, EPI_ISL_14890823, EPI_ISL_14303351, EPI_ISL_14303105, EPI_ISL_14175832, EPI_ISL_14166803, EPI_ISL_14166824, EPI_ISL_14175861, EPI_ISL_14175443, EPI_ISL_14175309, EPI_ISL_14175356, EPI_ISL_14891457, EPI_ISL_14175646, EPI_ISL_14166765, EPI_ISL_14166745, EPI_ISL_14175596, EPI_ISL_13877177, EPI_ISL_13877040, EPI_ISL_13876906, EPI_ISL_13876856, EPI_ISL_13779613, EPI_ISL_13779762, EPI_ISL_13779770, EPI_ISL_13536971, EPI_ISL_13537088, EPI_ISL_13536957, EPI_ISL_14167122, EPI_ISL_13537008, EPI_ISL_13537065, EPI_ISL_13536975, EPI_ISL_13536752, EPI_ISL_13779722, EPI_ISL_13779520, EPI_ISL_13779607, EPI_ISL_13877101, EPI_ISL_13876817, EPI_ISL_13876923, EPI_ISL_13876834, EPI_ISL_13537041, EPI_ISL_13877084, EPI_ISL_13536661, EPI_ISL_14166807, EPI_ISL_14166813, EPI_ISL_14891443, EPI_ISL_13536593, EPI_ISL_14891764, EPI_ISL_14890986, EPI_ISL_14303855, EPI_ISL_14304034, EPI_ISL_14175488, EPI_ISL_14167095, EPI_ISL_14166800, EPI_ISL_14166984, EPI_ISL_14166746, EPI_ISL_13876912, EPI_ISL_14166801, EPI_ISL_13876953, EPI_ISL_13779738, EPI_ISL_14175398, EPI_ISL_13779407, EPI_ISL_14891722, EPI_ISL_14167039, EPI_ISL_13876865, EPI_ISL_14992935, OP291417.1, EPI_ISL_14358136, EPI_ISL_13779397, EPI_ISL_14175625, EPI_ISL_13537000, EPI_ISL_14167118, EPI_ISL_14890803, EPI_ISL_14167201, EPI_ISL_14890975, EPI_ISL_14890976, EPI_ISL_14890977, EPI_ISL_14890818, EPI_ISL_14175668, EPI_ISL_14175723, EPI_ISL_14167149, EPI_ISL_14167108, EPI_ISL_14890989, EPI_ISL_13536782, EPI_ISL_14890963, EPI_ISL_14890780, EPI_ISL_14166908, EPI_ISL_14149814, EPI_ISL_13877128, EPI_ISL_14890801, EPI_ISL_14175777, EPI_ISL_13779538, EPI_ISL_14166793, EPI_ISL_14303243, EPI_ISL_14891798, EPI_ISL_14166799, EPI_ISL_14891714, EPI_ISL_14302983, EPI_ISL_14175364, EPI_ISL_13779789, EPI_ISL_13536639, EPI_ISL_14891419, EPI_ISL_14891420, EPI_ISL_14890817, EPI_ISL_13537103

**Comment by agamedilab** [comment]
![grafik](https://user-images.githubusercontent.com/102166254/190860691-4e83a31a-8d34-44e1-ae0c-4f90567ddf59.png)


https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AG1219V%2CS%3AN450D%2CS%3AL8F&pangoLineage=BA.2*&pangoLineage1=BA.5*&

**Comment by corneliusroemer** [comment]
Thanks for the proposal - it's interesting but being dead already for a while I think we should close and reopen in case it reappears or has kids.
