### ISSUE TITLE
BA.5.6 sublineage with Orf1a:H2092Y and S:K444R circualting in Japan (87 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1077]
I spotted this sublineage of BA.5.6 circulating exclusively in Japan.
Gisaid query Spike_K444R,NSP3_H1274Y finds 87 sequences spanning between June and September.

Tree:
![Schermata 2022-09-16 alle 16 32 32](https://user-images.githubusercontent.com/87669813/190663775-3f9ce0f5-41bc-4a21-a418-be3b9724cf7a.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21806_4821a0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C6539T

defining mutations:
Orf1b:M1839I + Orf1b:T2537I + Orf1a:H2092Y (C6539T)+ C7564T + C11653T + S:K444R (A22893G )

CovSprectrum query C7564T, C11653T + ORF1b:M1839I, ORF1b:T2537I, S:K444R, ORF1a:H2092Y
finds 70:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1b%3AM1839I%2COrf1b%3AT2537I%2CS%3AK444R%2COrf1a%3AH2092Y&nucMutations=C7564T%2CC11653T&

Good quality Sequence list 
<details>
<summary>Expand for EPI_ISLs</summary>
 EPI_ISL_14642480
EPI_ISL_14643730
EPI_ISL_14876794
EPI_ISL_14345554
EPI_ISL_14642904
EPI_ISL_14348122
EPI_ISL_14301885
EPI_ISL_14640869
EPI_ISL_14643385
EPI_ISL_14876788
EPI_ISL_14349865
EPI_ISL_14638746
EPI_ISL_14141765
EPI_ISL_14647240
EPI_ISL_14646963
EPI_ISL_14644135
EPI_ISL_14647467
EPI_ISL_14640736
EPI_ISL_14872894
EPI_ISL_14879487
EPI_ISL_14349859
EPI_ISL_14640735
EPI_ISL_14590410
EPI_ISL_14128196
EPI_ISL_14349632
EPI_ISL_14879406
EPI_ISL_14341480
EPI_ISL_14876789
EPI_ISL_14345558
EPI_ISL_14644276
EPI_ISL_14933703
EPI_ISL_14647493
EPI_ISL_14646503
EPI_ISL_14299374
EPI_ISL_14872682
EPI_ISL_14642884
EPI_ISL_14146903
EPI_ISL_14351164
EPI_ISL_14872702
EPI_ISL_14641018
EPI_ISL_14874731
EPI_ISL_14838349
EPI_ISL_14340593
EPI_ISL_14348089
EPI_ISL_14641408
EPI_ISL_14349874
EPI_ISL_14882290
EPI_ISL_14876045
EPI_ISL_14343548
EPI_ISL_14638749
EPI_ISL_14767236
EPI_ISL_14642907
EPI_ISL_14140526
EPI_ISL_14638757
EPI_ISL_14780940
EPI_ISL_14344278
EPI_ISL_14724722
EPI_ISL_14640882
EPI_ISL_14118691
EPI_ISL_14874910
EPI_ISL_14838355
EPI_ISL_14140211
EPI_ISL_14640908
EPI_ISL_14118688 first sequence (13/06)
EPI_ISL_14345551
EPI_ISL_14877822
EPI_ISL_14346969
</details>

Sincerely i dont think this one could compete with the high transmissible lineages circulating today, but having a mutation of interest and being very well geographically linked to a country that had a huge BA.5 wave as Japan, i think it is worth a designation.

**Comment by corneliusroemer** [comment]
Dying in Japan and small, let's focus on bigger and growing things instead :)

![Uploading image.png…]()

**Comment by FedeGueli** [comment]
106 seqs as today, although i think the gisaid query is not totally specific. I think it is better to keep this closed

**Comment by FedeGueli** [comment]
116seqs as today

**Comment by FedeGueli** [comment]
134 seqs as today
