### ISSUE TITLE
BA.5.2 sublineage with S:D138N (1011 seq., international)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1078]
Proposal for a sublineage of BA.5.2
Earliest sequence: 22.05.2022 (Israel)
Countries detected: Australia, Austria, Bahrain, Belgium, Bonaire, Brazil, Canada, Chile, CostaRica, Croatia, CzechRepublic, Denmark, England, Estonia, Finland, France, Gambia, Georgia, Germany, Greece, Hong Kong, India, Ireland, Israel, Italy, Japan, Luxembourg, Netherlands, NewZealand, Norway, Poland, Portugal, Romania, Scotland, Singapore, Slovakia, Slovenia, South Africa, SouthKorea, Spain, Sweden, Switzerland, Turkey, USA, Wales

Defining mutation:
G21974A = S:D138N

This clade is apparently an unproposed sublineage of BA.5.2 defined by S:D138N (at least i could not find an issue containing S:D138N).
Currently there are c. 1011 seq from c. 45 countries on usher as of 17.09.22. 

![grafik](https://user-images.githubusercontent.com/102166254/190855480-9ae72e3a-789a-4a07-9727-637d4853d29c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1fce6_58d5c0.json?branchLabel=aa%20mutations&c=gt-S_138&label=nuc%20mutations:C241T,T670G,C1627T,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,C27807T,C27889T,A28271T,C28311T,A28330G,G28881A,G28882A,G28883C,A29510C

EPI_ISL_13072503, EPI_ISL_13269524, EPI_ISL_13305372, EPI_ISL_13326144, EPI_ISL_13326179, EPI_ISL_13326386, EPI_ISL_13327990, EPI_ISL_13346881, EPI_ISL_13368647, EPI_ISL_13382737, EPI_ISL_13385703, EPI_ISL_13386367, EPI_ISL_13391465, EPI_ISL_13400624, EPI_ISL_13407175, EPI_ISL_13428519, EPI_ISL_13438576, EPI_ISL_13442896, EPI_ISL_13460933, EPI_ISL_13461163, EPI_ISL_13480093, EPI_ISL_13480175, EPI_ISL_13480871, EPI_ISL_13499741, EPI_ISL_13499838, EPI_ISL_13506793, EPI_ISL_13508888, EPI_ISL_13517118, EPI_ISL_13527034, EPI_ISL_13527045, EPI_ISL_13527052, EPI_ISL_13537871, EPI_ISL_13540114, EPI_ISL_13540129, EPI_ISL_13569916, EPI_ISL_13570180, EPI_ISL_13570385, EPI_ISL_13580016, EPI_ISL_13580159, EPI_ISL_13588521, EPI_ISL_13611229, EPI_ISL_13613040, EPI_ISL_13613041, EPI_ISL_13613268, EPI_ISL_13618816, EPI_ISL_13620151, EPI_ISL_13621855, EPI_ISL_13621945, EPI_ISL_13625488, EPI_ISL_13625638, EPI_ISL_13638201, EPI_ISL_13655225, EPI_ISL_13692428, EPI_ISL_13698062, EPI_ISL_13713583, EPI_ISL_13713672, EPI_ISL_13714235, EPI_ISL_13716946, EPI_ISL_13717241, EPI_ISL_13725628, EPI_ISL_13727002, EPI_ISL_13730712, EPI_ISL_13743573, EPI_ISL_13744126, EPI_ISL_13744291, EPI_ISL_13748330, EPI_ISL_13748384, EPI_ISL_13749062, EPI_ISL_13749392, EPI_ISL_13749418, EPI_ISL_13749542, EPI_ISL_13749725, EPI_ISL_13749907, EPI_ISL_13749915, EPI_ISL_13751987, EPI_ISL_13752008, EPI_ISL_13766780, EPI_ISL_13766802, EPI_ISL_13766863, EPI_ISL_13774498, EPI_ISL_13782573, EPI_ISL_13795397, EPI_ISL_13795398, EPI_ISL_13800812, EPI_ISL_13801082, EPI_ISL_13801666, EPI_ISL_13826833, EPI_ISL_13826843, EPI_ISL_13826886, EPI_ISL_13826895, EPI_ISL_13826985, EPI_ISL_13827129, EPI_ISL_13827159, EPI_ISL_13840746, EPI_ISL_13844136, EPI_ISL_13844140, EPI_ISL_13844692, EPI_ISL_13854073, EPI_ISL_13854468, EPI_ISL_13860894, EPI_ISL_13860941, EPI_ISL_13868496, EPI_ISL_13873543, EPI_ISL_13873641, EPI_ISL_13874221, EPI_ISL_13874292, EPI_ISL_13877773, EPI_ISL_13877776, EPI_ISL_13879237, EPI_ISL_13884049, EPI_ISL_13884209, EPI_ISL_13884317, EPI_ISL_13884371, EPI_ISL_13884659, EPI_ISL_13886412, EPI_ISL_13888163, EPI_ISL_13896127, EPI_ISL_13908326, EPI_ISL_13909322, EPI_ISL_13916389, EPI_ISL_13917957, EPI_ISL_13919113, EPI_ISL_13919182, EPI_ISL_13923520, EPI_ISL_13923707, EPI_ISL_13923931, EPI_ISL_13924466, EPI_ISL_13924941, EPI_ISL_13928300, EPI_ISL_13928405, EPI_ISL_13929971, EPI_ISL_13932873, EPI_ISL_13932906, EPI_ISL_13933698, EPI_ISL_13934999, EPI_ISL_13937244, EPI_ISL_13937586, EPI_ISL_13938770, EPI_ISL_13938994, EPI_ISL_13939519, EPI_ISL_13943600, EPI_ISL_13943675, EPI_ISL_13943859, EPI_ISL_13943879, EPI_ISL_13945505, EPI_ISL_13946115, EPI_ISL_13946378, EPI_ISL_13950590, EPI_ISL_13950646, EPI_ISL_13955948, EPI_ISL_13957205, EPI_ISL_13965770, EPI_ISL_13965817, EPI_ISL_13966367, EPI_ISL_13966488, EPI_ISL_13970646, EPI_ISL_13972926, EPI_ISL_13979257, EPI_ISL_13979430, EPI_ISL_13990168, EPI_ISL_13991572, EPI_ISL_13991678, EPI_ISL_14000077, EPI_ISL_14012208, EPI_ISL_14017421, EPI_ISL_14018345, EPI_ISL_14019153, EPI_ISL_14022339, EPI_ISL_14026264, EPI_ISL_14026838, EPI_ISL_14026916, EPI_ISL_14026923, EPI_ISL_14028761, EPI_ISL_14029760, EPI_ISL_14030829, EPI_ISL_14030858, EPI_ISL_14032048, EPI_ISL_14032271, EPI_ISL_14038917, EPI_ISL_14047775, EPI_ISL_14059321, EPI_ISL_14062783, EPI_ISL_14067953, EPI_ISL_14068290, EPI_ISL_14068541, EPI_ISL_14071611, EPI_ISL_14072026, EPI_ISL_14074482, EPI_ISL_14085635, EPI_ISL_14096389, EPI_ISL_14096839, EPI_ISL_14100006, EPI_ISL_14101589, EPI_ISL_14101748, EPI_ISL_14104113, EPI_ISL_14136390, EPI_ISL_14136815, EPI_ISL_14136963, EPI_ISL_14137641, EPI_ISL_14138863, EPI_ISL_14139419, EPI_ISL_14140173, EPI_ISL_14145137, EPI_ISL_14145473, EPI_ISL_14149427, EPI_ISL_14149445, EPI_ISL_14158231, EPI_ISL_14159695, EPI_ISL_14160052, EPI_ISL_14163338, EPI_ISL_14163339, EPI_ISL_14170776, EPI_ISL_14173616, EPI_ISL_14176782, EPI_ISL_14177813, EPI_ISL_14177922, EPI_ISL_14182104, EPI_ISL_14187424, EPI_ISL_14189194, EPI_ISL_14193181, EPI_ISL_14193405, EPI_ISL_14194817, EPI_ISL_14195555, EPI_ISL_14197966, EPI_ISL_14203656, EPI_ISL_14205805, EPI_ISL_14215890, EPI_ISL_14215944, EPI_ISL_14216082, EPI_ISL_14216119, EPI_ISL_14216186, EPI_ISL_14217420, EPI_ISL_14218690, EPI_ISL_14218695, EPI_ISL_14220049, EPI_ISL_14220842, EPI_ISL_14226734, EPI_ISL_14227693, EPI_ISL_14227703, EPI_ISL_14227708, EPI_ISL_14227721, EPI_ISL_14228103, EPI_ISL_14230288, EPI_ISL_14231215, EPI_ISL_14231369, EPI_ISL_14234140, EPI_ISL_14236851, EPI_ISL_14237288, EPI_ISL_14237292, EPI_ISL_14240342, EPI_ISL_14240372, EPI_ISL_14242086, EPI_ISL_14243163, EPI_ISL_14248082, EPI_ISL_14248189, EPI_ISL_14248662, EPI_ISL_14253162, EPI_ISL_14254900, EPI_ISL_14255334, EPI_ISL_14255408, EPI_ISL_14257717, EPI_ISL_14260519, EPI_ISL_14262539, EPI_ISL_14278185, EPI_ISL_14285594, EPI_ISL_14288143, EPI_ISL_14288461, EPI_ISL_14289912, EPI_ISL_14290633, EPI_ISL_14290702, EPI_ISL_14292567, EPI_ISL_14297899, EPI_ISL_14298042, EPI_ISL_14298203, EPI_ISL_14298219, EPI_ISL_14302811, EPI_ISL_14302930, EPI_ISL_14305109, EPI_ISL_14305205, EPI_ISL_14305773, EPI_ISL_14306802, EPI_ISL_14307036, EPI_ISL_14315442, EPI_ISL_14320801, EPI_ISL_14324699, EPI_ISL_14326516, EPI_ISL_14326880, EPI_ISL_14328380, EPI_ISL_14328622, EPI_ISL_14328767, EPI_ISL_14355431, EPI_ISL_14359410, EPI_ISL_14359476, EPI_ISL_14359477, EPI_ISL_14359967, EPI_ISL_14363573, EPI_ISL_14364550, EPI_ISL_14365182, EPI_ISL_14367442, EPI_ISL_14369367, EPI_ISL_14369594, EPI_ISL_14370083, EPI_ISL_14370533, EPI_ISL_14371927, EPI_ISL_14372049, EPI_ISL_14378614, EPI_ISL_14379061, EPI_ISL_14390132, EPI_ISL_14390336, EPI_ISL_14392447, EPI_ISL_14394331, EPI_ISL_14396169, EPI_ISL_14397671, EPI_ISL_14397763, EPI_ISL_14398109, EPI_ISL_14398277, EPI_ISL_14398854, EPI_ISL_14398875, EPI_ISL_14399582, EPI_ISL_14399682, EPI_ISL_14400861, EPI_ISL_14401567, EPI_ISL_14403711, EPI_ISL_14404395, EPI_ISL_14404410, EPI_ISL_14404781, EPI_ISL_14405895, EPI_ISL_14407167, EPI_ISL_14408907, EPI_ISL_14409099, EPI_ISL_14410307, EPI_ISL_14410330, EPI_ISL_14410356, EPI_ISL_14411559, EPI_ISL_14412731, EPI_ISL_14412798, EPI_ISL_14413411, EPI_ISL_14415815, EPI_ISL_14418029, EPI_ISL_14419071, EPI_ISL_14419316, EPI_ISL_14419521, EPI_ISL_14420219, EPI_ISL_14420831, EPI_ISL_14424229, EPI_ISL_14426786, EPI_ISL_14426824, EPI_ISL_14429439, EPI_ISL_14433289, EPI_ISL_14433472, EPI_ISL_14433700, EPI_ISL_14433706, EPI_ISL_14437582, EPI_ISL_14437635, EPI_ISL_14442804, EPI_ISL_14445091, EPI_ISL_14455066, EPI_ISL_14455165, EPI_ISL_14456313, EPI_ISL_14456330, EPI_ISL_14456473, EPI_ISL_14457610, EPI_ISL_14458763, EPI_ISL_14460948, EPI_ISL_14463836, EPI_ISL_14465841, EPI_ISL_14466843, EPI_ISL_14468372, EPI_ISL_14473142, EPI_ISL_14474516, EPI_ISL_14475823, EPI_ISL_14478224, EPI_ISL_14478548, EPI_ISL_14491962, EPI_ISL_14494362, EPI_ISL_14494445, EPI_ISL_14496357, EPI_ISL_14496710, EPI_ISL_14504838, EPI_ISL_14504872, EPI_ISL_14504925, EPI_ISL_14506264, EPI_ISL_14507251, EPI_ISL_14507252, EPI_ISL_14516968, EPI_ISL_14517761, EPI_ISL_14519215, EPI_ISL_14519721, EPI_ISL_14521363, EPI_ISL_14521430, EPI_ISL_14521523, EPI_ISL_14521660, EPI_ISL_14521750, EPI_ISL_14521953, EPI_ISL_14522930, EPI_ISL_14523158, EPI_ISL_14523270, EPI_ISL_14523427, EPI_ISL_14523478, EPI_ISL_14525208, EPI_ISL_14525421, EPI_ISL_14525476, EPI_ISL_14527453, EPI_ISL_14527482, EPI_ISL_14530574, EPI_ISL_14532266, EPI_ISL_14535260, EPI_ISL_14536592, EPI_ISL_14537211, EPI_ISL_14537772, EPI_ISL_14537780, EPI_ISL_14541072, EPI_ISL_14541079, EPI_ISL_14543760, EPI_ISL_14543864, EPI_ISL_14544588, EPI_ISL_14544727, EPI_ISL_14544922, EPI_ISL_14544926, EPI_ISL_14546141, EPI_ISL_14546239, EPI_ISL_14547537, EPI_ISL_14549662, EPI_ISL_14554489, EPI_ISL_14561538, EPI_ISL_14562573, EPI_ISL_14563092, EPI_ISL_14563488, EPI_ISL_14563519, EPI_ISL_14568537, EPI_ISL_14570186, EPI_ISL_14570201, EPI_ISL_14570342, EPI_ISL_14570353, EPI_ISL_14570395, EPI_ISL_14570411, EPI_ISL_14571262, EPI_ISL_14574872, EPI_ISL_14576369, EPI_ISL_14583571, EPI_ISL_14585401, EPI_ISL_14586324, EPI_ISL_14588374, EPI_ISL_14589789, EPI_ISL_14594165, EPI_ISL_14594283, EPI_ISL_14594328, EPI_ISL_14596860, EPI_ISL_14598989, EPI_ISL_14602794, EPI_ISL_14604176, EPI_ISL_14614240, EPI_ISL_14617165, EPI_ISL_14617457, EPI_ISL_14617462, EPI_ISL_14619358, EPI_ISL_14619945, EPI_ISL_14620049, EPI_ISL_14622990, EPI_ISL_14623195, EPI_ISL_14625899, EPI_ISL_14626018, EPI_ISL_14626414, EPI_ISL_14626636, EPI_ISL_14647225, EPI_ISL_14649584, EPI_ISL_14654537, EPI_ISL_14654949, EPI_ISL_14655289, EPI_ISL_14662324, EPI_ISL_14662487, EPI_ISL_14662987, EPI_ISL_14663291, EPI_ISL_14664848, EPI_ISL_14665245, EPI_ISL_14666248, EPI_ISL_14666250, EPI_ISL_14681386, EPI_ISL_14681391, EPI_ISL_14681472, EPI_ISL_14690454, EPI_ISL_14690491, EPI_ISL_14690702, EPI_ISL_14690919, EPI_ISL_14691098, EPI_ISL_14691568, EPI_ISL_14692181, EPI_ISL_14692891, EPI_ISL_14693253, EPI_ISL_14693323, EPI_ISL_14693591, EPI_ISL_14693891, EPI_ISL_14694303, EPI_ISL_14694789, EPI_ISL_14694838, EPI_ISL_14694917, EPI_ISL_14695203, EPI_ISL_14696669, EPI_ISL_14696905, EPI_ISL_14697552, EPI_ISL_14697794, EPI_ISL_14698403, EPI_ISL_14701333, EPI_ISL_14701541, EPI_ISL_14717770, EPI_ISL_14722343, EPI_ISL_14722839, EPI_ISL_14723296, EPI_ISL_14729729, EPI_ISL_14730818, EPI_ISL_14745225, EPI_ISL_14746936, EPI_ISL_14747168, EPI_ISL_14747265, EPI_ISL_14747445, EPI_ISL_14750629, EPI_ISL_14750664, EPI_ISL_14750692, EPI_ISL_14750698, EPI_ISL_14750867, EPI_ISL_14751052, EPI_ISL_14753458, EPI_ISL_14754115, EPI_ISL_14754151, EPI_ISL_14754831, EPI_ISL_14756572, EPI_ISL_14756594, EPI_ISL_14757099, EPI_ISL_14758677, EPI_ISL_14758729, EPI_ISL_14760241, EPI_ISL_14760250, EPI_ISL_14761834, EPI_ISL_14761862, EPI_ISL_14762678, EPI_ISL_14763606, EPI_ISL_14763608, EPI_ISL_14764229, EPI_ISL_14768302, EPI_ISL_14768996, EPI_ISL_14771700, EPI_ISL_14772322, EPI_ISL_14773095, EPI_ISL_14773120, EPI_ISL_14773250, EPI_ISL_14773696, EPI_ISL_14773701, EPI_ISL_14773713, EPI_ISL_14775965, EPI_ISL_14777996, EPI_ISL_14785191, EPI_ISL_14785295, EPI_ISL_14785318, EPI_ISL_14787254, EPI_ISL_14787515, EPI_ISL_14787780, EPI_ISL_14791032, EPI_ISL_14791177, EPI_ISL_14791597, EPI_ISL_14791701, EPI_ISL_14791914, EPI_ISL_14791938, EPI_ISL_14792113, EPI_ISL_14792532, EPI_ISL_14792551, EPI_ISL_14792566, EPI_ISL_14792578, EPI_ISL_14792987, EPI_ISL_14793000, EPI_ISL_14795766, EPI_ISL_14799501, EPI_ISL_14802427, EPI_ISL_14806877, EPI_ISL_14806930, EPI_ISL_14809349, EPI_ISL_14810192, EPI_ISL_14810791, EPI_ISL_14811270, EPI_ISL_14811950, EPI_ISL_14813203, EPI_ISL_14813226, EPI_ISL_14813556, EPI_ISL_14813816, EPI_ISL_14814083, EPI_ISL_14814297, EPI_ISL_14814480, EPI_ISL_14814546, EPI_ISL_14814559, EPI_ISL_14814839, EPI_ISL_14814869, EPI_ISL_14815368, EPI_ISL_14819879, EPI_ISL_14825505, EPI_ISL_14825557, EPI_ISL_14836264, EPI_ISL_14836562, EPI_ISL_14839859, EPI_ISL_14840533, EPI_ISL_14841035, EPI_ISL_14846601, EPI_ISL_14853814, EPI_ISL_14855108, EPI_ISL_14856038, EPI_ISL_14856309, EPI_ISL_14861355, EPI_ISL_14861360, EPI_ISL_14862233, EPI_ISL_14863837, EPI_ISL_14867304, EPI_ISL_14870593, EPI_ISL_14884109, EPI_ISL_14884128, EPI_ISL_14884150, EPI_ISL_14884285, EPI_ISL_14884701, EPI_ISL_14884797, EPI_ISL_14885632, EPI_ISL_14886076, EPI_ISL_14886165, EPI_ISL_14886665, EPI_ISL_14886728, EPI_ISL_14887688, EPI_ISL_14888006, EPI_ISL_14891097, EPI_ISL_14891989, EPI_ISL_14892041, EPI_ISL_14892096, EPI_ISL_14892111, EPI_ISL_14892224, EPI_ISL_14892326, EPI_ISL_14892374, EPI_ISL_14892507, EPI_ISL_14892516, EPI_ISL_14908291, EPI_ISL_14914082, EPI_ISL_14917196, EPI_ISL_14917268, EPI_ISL_14920079, EPI_ISL_14920875, EPI_ISL_14921821, EPI_ISL_14922035, EPI_ISL_14922331, EPI_ISL_14922470, EPI_ISL_14922479, EPI_ISL_14923916, EPI_ISL_14923923, EPI_ISL_14925499, EPI_ISL_14925500, EPI_ISL_14925501, EPI_ISL_14926728, EPI_ISL_14926775, EPI_ISL_14927625, EPI_ISL_14930500, EPI_ISL_14932090, EPI_ISL_14934043, EPI_ISL_14934056, EPI_ISL_14935307, EPI_ISL_14935648, EPI_ISL_14935659, EPI_ISL_14935669, EPI_ISL_14936639, EPI_ISL_14936750, EPI_ISL_14950796, EPI_ISL_14950945, EPI_ISL_14951176, EPI_ISL_14952052, EPI_ISL_14952757, EPI_ISL_14974226, EPI_ISL_14974236, EPI_ISL_14974825, EPI_ISL_14975025, EPI_ISL_14975157, EPI_ISL_14975323, EPI_ISL_14975874, EPI_ISL_14977524, EPI_ISL_14978086, EPI_ISL_14979026, EPI_ISL_14979048, EPI_ISL_14980456, EPI_ISL_14982700, EPI_ISL_14987785, EPI_ISL_15004476, EPI_ISL_15004482, EPI_ISL_15004492, EPI_ISL_15004496, EPI_ISL_15004499, EPI_ISL_15004516, EPI_ISL_15004522, EPI_ISL_15004529

ON938841.1, ON957602.1, ON958345.1, ON958477.1, ON967447.1, ON968266.1, ON985429.1, ON999955.1, OP015128.1, OP025167.1, OP027091.1, OP031707.1, OP045541.1, OP048363.1, OP053662.1, OP053864.1, OP054815.1, OP093016.1, OP096120.1, OP102383.1, OP110109.1, OP114493.1, OP117863.1, OP118424.1, OP126504.1, OP137507.1, OP144948.1, OP148733.1, OP181348.1, OP181636.1, OP183578.1, OP202562.1, OP227371.1, OP229650.1, OP242563.1, OP243135.1, OP257712.1, OP258355.1, OP260586.1, OP279837.1, OP284693.1, OP285569.1, OP303454.1, OP304225.1, OP325117.1, OP331777.1, OP334365.1, OP334815.1, OP363384.1, OP367912.1, OP376365.1, OP385923.1, OP401944.1, OP406013.1, OP407533.1, OP411938.1, OP412285.1, OP412715.1, OP416724.1, OP423732.1, OX123386.1, OX140157.1, OX140178.1, OX148403.1, OX162278.1, OX180708.1, OX190410.1, OX190534.1, OX208151.1, OX210095.1, OX210485.1, OX211336.1, OX211958.1, OX213081.1, OX213201.1, OX213389.1, OX213422.1, OX214108.1, OX214721.1, OX215672.1, OX216144.1, OX216959.1, OX218587.1, OX219755.1, OX219789.1, OX220079.1, OX220649.1, OX220679.1, OX221267.1, OX221574.1, OX222390.1, OX222523.1, OX223516.1, OX224267.1, OX224523.1, OX224537.1, OX224757.1, OX224887.1, OX225010.1, OX225014.1, OX225228.1, OX225368.1, OX225713.1, OX225777.1, OX225852.1, OX225930.1, OX226140.1, OX226446.1, OX226493.1, OX226498.1, OX226542.1, OX226549.1, OX226603.1, OX226604.1, OX226696.1, OX226730.1, OX226745.1, OX226789.1, OX227026.1, OX227097.1, OX227352.1, OX227568.1, OX227582.1, OX227795.1, OX227798.1, OX227849.1, OX227936.1, OX227997.1, OX228202.1, OX228261.1, OX228298.1, OX228487.1, OX228488.1, OX228517.1, OX228777.1, OX228858.1, OX228927.1, OX228968.1, OX229056.1, OX229079.1, OX229355.1, OX229368.1, OX230745.1, OX230863.1, OX232067.1, OX232277.1, OX232355.1, OX232498.1, OX232523.1, OX233040.1, OX233159.1, OX233411.1, OX233422.1, OX233629.1, OX233975.1, OX234271.1, OX234347.1, OX234756.1, OX234884.1, OX235795.1, OX235815.1, OX235937.1, OX237403.1, OX237474.1, OX237531.1, OX237573.1, OX237709.1, OX238442.1, OX238780.1, OX238863.1, OX238902.1, OX238921.1, OX239038.1, OX239042.1, OX239417.1, OX239472.1, OX239544.1, OX244375.1, OX246558.1, OX248315.1, OX254193.1, OX255284.1, OX256869.1, OX259955.1, OX260389.1, OX261585.1, OX263952.1, OX264062.1, OX264416.1, OX264417.1, OX264511.1, OX264690.1, OX265142.1, OX265186.1, OX271212.1, OX272535.1, OX274538.1, OX275061.1, OX275156.1, OX275292.1, OX275302.1, OX275670.1, OX275716.1, OX275918.1, OX276090.1, OX276220.1, OX276224.1, OX276608.1, OX276642.1, OX276700.1, OX276748.1, OX277133.1, OX277257.1, OX277561.1, OX277675.1, OX277755.1, OX278437.1, OX278618.1, OX278625.1, OX278913.1, OX278957.1, OX279076.1, OX279400.1, OX279762.1, OX280127.1, OX280532.1, OX280564.1, OX280590.1, OX280713.1, OX280861.1, OX280998.1, OX281038.1, OX281094.1, OX281550.1, OX281928.1, OX282597.1, OX282686.1, OX282751.1, OX282756.1, OX282846.1, OX283054.1, OX283194.1, OX283545.1, OX283575.1, OX283709.1, OX283709.1, OX284303.1, OX284348.1, OX284734.1, OX284867.1, OX285150.1, OX285536.1, OX286440.1, OX286569.1, OX287042.1, OX287971.1, OX288027.1, OX288066.1, OX288279.1, OX288417.1, OX288682.1, OX289051.1, OX289393.1, OX289813.1, OX290522.1, OX290672.1, OX290805.1, OX290890.1, OX291901.1, OX292735.1, OX293127.1, OX293973.1, OX294059.1, OX294153.1, OX294260.1, OX294556.1, OX294628.1, OX294791.1, OX294888.1, OX295121.1, OX295180.1, OX295219.1, OX295243.1, OX295429.1, OX296253.1, OX297231.1, OX297440.1

**Comment by agamedilab** [comment]
![grafik](https://user-images.githubusercontent.com/102166254/190860273-92d1cb28-9a87-48f5-a3e5-3f3360e76dc3.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AD138N&pangoLineage=BA.5.2*&

**Comment by corneliusroemer** [comment]
Thanks for proposing! I have a bad feeling about this one - it's on a messed up branch of Usher - M_D3N starting out reverted - and there's some other mutation going back and forth. It's at very similar levels to BA.5.2 - decreasing in share. The share is very wiggly. This could be an artefact.

Since it's decreasing in share I don't think this needs a designation.

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/25161793/190869502-e555e072-32ee-4f61-b064-2485a0ad38d8.png">

<img width="2539" alt="image" src="https://user-images.githubusercontent.com/25161793/190869504-6c35db7d-f54f-4326-bf39-0b9b7e17c774.png">

https://cov-spectrum.org/explore/Europe/AllSamples/Past6M/variants?nextcladePangoLineage=BA.5.2&aaMutations1=S%3AD138N&pangoLineage1=BA.5.2*&analysisMode=CompareToBaseline&

**Comment by corneliusroemer** [comment]
Please put EPI_ISLs in a `details` collapsible - otherwise the issue gets very long:

It works like this

```md
<details>
  <summary>EPI ISLs</summary>

EPI_ISLs.....
</details>
```

It then looks like this: 
<details>
  <summary>EPI ISLs</summary>

EPI_ISLs.....
</details>

**Comment by FedeGueli** [comment]
I monitored this one too for a while no signs of increased transmissibility . I stopped a couple of weeks ago so maybe something has changed.

**Comment by corneliusroemer** [comment]
Let's reopen if something interesting starts - this could just be an early deleterious mutation.

If a child of this pops up that grows let's designate this as a parent.

**Comment by agamedilab** [comment]
1116 seq on usher as of 01.10.22.

![grafik](https://user-images.githubusercontent.com/102166254/193402658-eda2486b-cbbf-41ee-8bab-7bfa7411fff4.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3acdf_805660.json?branchLabel=aa%20mutations&label=nuc%20mutations:G21974A

It is still lingering on.
![grafik](https://user-images.githubusercontent.com/102166254/193402704-4dfec41d-355d-4515-9615-607a1f803cf7.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AD138N&pangoLineage=BA.5.2*&nextcladePangoLineage1=BA.5.2&

Should this be designated in the spirit of #1133? @corneliusroemer
