### ISSUE TITLE
Sublineage of BL.1 with S:G614S (5 seq, 4 countries)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1079]
**Description**
**Sub-lineage of:** BL.1
**Earliest sequence:** 2022-8-27, Singapore, EPI_ISL_14785669
**Most recent sequence:** 2022-9-5, Israel, EPI_ISL_14960580
**Countries circulating:** Singapore (3—2 local, 1 with travel from Malaysia), Israel (1), England (1)
**Number of Sequences:** 5
**GISAID Query:** Spike_R346T, Spike_D574V, Spike_D614S
**CovSpectrum Query:** Nextcladepangolineage:BL.1* & S:614S
**Substitutions on top of BL.1:**
**Spike:** G614S
**Nucleotide:** C10366T, G23402A

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_101fe_5bc280%E2%80%94BL.1%2BG614S.json 
![image](https://user-images.githubusercontent.com/33738461/190866075-1e957925-6aec-4e5d-a023-3f9af738f45c.png)

**Evidence**
S:D614G was the first major mutation in SARS-CoV-2 to have a global impact, first occurring in early 2020 and subsequently achieving total world dominance. Studies have shown that G614 increased infectivity and viral cell entry and is associated with higher viral loads than D614 viruses. https://www.science.org/doi/10.1126/science.abe8499
![image](https://user-images.githubusercontent.com/33738461/190866568-417f3ab9-892e-4519-ac19-99bd7fd03d44.png)

https://www.cell.com/cell/fulltext/S0092-8674(20)30820-5
![image](https://user-images.githubusercontent.com/33738461/190866604-890bab64-504d-4af9-937a-0f73e1892e86.png)

Studies looking at the effect of D614G on spike structure have determined that it induces multiple interactions not found in D614 viruses and that these interactions lead to greater spike stability and less premature S1 shedding. https://www.science.org/doi/10.1126/science.abf2303
![image](https://user-images.githubusercontent.com/33738461/190866640-9b8b6074-b1d5-46bb-8fbe-16ac788f721c.png)

One of the most interesting perspectives on the D614G mutation is by Qing, et al. in their study Dynamics of SARS-CoV-2 Spike Proteins in Cell Entry: Control Elements in Amino-Terminal Domains,” where they showed that the catastrophic effects of inserting a SARS-CoV-1 NTD into D614 SARS-CoV-2 virus-like particles (VLPs) were largely (but not entirely) ameliorated in G614 VLPs. SARS-CoV-1 has much shorter NTD loops than SARS-CoV-2 (similar to SARS-CoV-2 variants with large deletions in these loops), and shorter loops tend to be destabilizing in SARS-CoV-2, but they propose that G614, which is known to connect S1 and S2, allows the NTD to interact with more distant spike regions in a way that stabilizes the S1/S2 connection and prevents premature S1 shedding (which prevents cell entry). Specifically, they cite interactions between the NTD and CTD1 domain (codons 528-591). BL.1. BL.1, of course, has the D574V mutations in CTD1, so perhaps it plays a role in the S:614-mediated NTD-CTD1 interaction.
https://journals.asm.org/doi/10.1128/mBio.01590-21 
![image](https://user-images.githubusercontent.com/33738461/190866683-93c06c23-db99-4f35-9d57-61b025d6fbdf.png)

One of the most distinctive characteristics of BA.2.75 is its panoply of NTD mutations. Could these mutations, perhaps along with D574V, cause enough of a change in the spike architecture to make G614S mutation advantageous, or at least not disadvantageous? I have no idea, but I think it’s a fascinating question and would love to hear what experts have to say. 

Mutations to G614 have been rare, and have never, to my knowledge, spread to any appreciable extent, so the fact that there are now five BL.1 sequences with the G614S substitution have been found in such distant locations as Singapore, Israel, and England, suggests this is more than just a curiosity and might tell us something important about the BA.2.75(.1) variant. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_14785669
EPI_ISL_14810864
EPI_ISL_14890610
EPI_ISL_14960580
EPI_ISL_15004565
</details>

**Comment by FedeGueli** [comment]
Thx @ryhisner great proposal.

**Comment by corneliusroemer** [comment]
This is very interesting - given sudden appearance in various countries and interesting Spike mutation, I'll designate this.

**Comment by ryhisner** [comment]
Four more sequences today from Singapore: 
EPI_ISL_15031286 (collection date: Sept 14)
EPI_ISL_15031936 (Sept 10) 
EPI_ISL_15031944 (Sept 10) 
EPI_ISL_15031945 (Sept 8)

The last one has added S:A892V (C24237T), while the first three added ORF1a:E34G (A375G). 
![image](https://user-images.githubusercontent.com/33738461/191311556-aaa8345e-e5d6-4ce5-858c-ddc1226a022b.png)

**Comment by FedeGueli** [comment]
2 more seqs from Australia uploaded yesterday.
