### ISSUE TITLE
Collection of BQ.1(.1).  diversity to watch

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1082]
BQ.1 appears to be fast growing. Some Spike mutations are showing up repeatedly, but it's too early to designate sublineages other than BQ.1.1 for them at this point. I think it reduces noise to track them in one issue for now.

- [x] S:E619Q 6 times, 3x US, 1x CAN, 2x Austria (once in representative surveillance), the Austrians have S:549I as well `Spike_E619Q,Spike_N460K,Spike_L452R` designated as BQ.1.3
- [x] S:I666V 8 times, 2x US, 3x CAN, 1x IL, 1x DK, 1x GER `Spike_I666V,Spike_N460K,Spike_L452R` designated as BQ.1.2
- [x] S:144- https://github.com/cov-lineages/pango-designation/issues/1202
- [x] S:346T with G8075A, G20469A, 4x US
- [x] S:190T, 3x in DK, 2x also with S:556K  `Spike_R190T,Spike_N460K,Spike_L452R`
- [x] S:L54F, 5x US, 3x FR `Spike_L54F,Spike_N460K,Spike_L452R`
- [x] S:146L https://github.com/cov-lineages/pango-designation/issues/1189
- [x] S:144- with C26455T (maybe 8 to date) as BQ.1.18
- [ ] S:S151N, 3x AUS, `Spike_S151N,Spike_N460K,Spike_L452R`
- [ ] S:152L 2x in CAN, it's defining in BA.2.75 `Spike_W152L,Spike_N460K,Spike_L452R`
- [ ] S:A348S, 2x US, 1x FR
- [ ] S:260V https://github.com/cov-lineages/pango-designation/issues/1180

Furthermore:
- [ ] BQ.1.1 has picked up S:822F in 8 uploads from England `Spike_L822F,Spike_R346T,Spike_N460K,Spike_L452R`
- [ ] BQ.1.1 with S:147E, singlet NY, `Spike_K147E,Spike_R346T,Spike_N460K,Spike_L452R`
- [ ] BQ.1.1 with S:262S, singlet England `Spike_A262S,Spike_N460K,Spike_K444T,Spike_R346T,Nsp13_N268S`
- [x] S:253G (2x England) convergent with XBB and others #1209
- [ ] S:261D (1x Japan)
- [ ] S:251L
- [ ] S:352S (1x Congo) predicted to be fitter than BQ.1 alone
- [ ] S:494P (1x Denmark, 1x France, homoplasic)
- [ ] BQ.1.1 S:S490I (homoplasic, Italy England 1 each)
- [ ] BQ.1.1 S:V445A (England 1x)
- [ ] BQ.1.1 S:V445F (France 1x)
- [ ] BQ.1.1 S:G446S (England 1x) `Spike_G446S,Spike_N460K,Spike_K444T,Spike_R346T,Nsp13_N268S`
If you find interesting small things in BQ.1.(.1) that you think are not ready yet for an issue - feel free to add it as a comment here to this issue.

**Comment by FedeGueli** [comment]
S:I666V now is 12seqs

**Comment by corneliusroemer** [comment]
S:E619Q (now BQ.1.3) is very common in random surveillance in Austria - these can't be used for designations as they are spike only but they show growth.

**Comment by FedeGueli** [comment]
@corneliusroemer thanks for designating other sibling lineages of BQ.1.1, i have spotted a potential sublineage of BQ.1.1 defined by Orf8:F6S 3 sequences only between Switzerland and France. Put here to check if it shows some advantage 8hard to believe but still the only diversity i spotted as today)

**Comment by FedeGueli** [comment]
@ryhisner spotted a BQ.1.1 with S:A262S some days ago. that is something to monitor closely.

**Comment by FedeGueli** [comment]
One Bq.1.1 uploaded today from NYC with S:K147E (convergent with BA.2.75)

**Comment by corneliusroemer** [comment]
I also saw the 147E but it seems to still be a singlet. I'll add it to the list as this may well end up growing.

**Comment by FedeGueli** [comment]
BQ.1.1 Singlet with S:1020S from Canada.

**Comment by FedeGueli** [comment]
In Australia is circulating a sublineage of BQ.1 (3 sequences ) with a further spike mutation in the NTD: S:S151N .

Downsampled BQ.1 tree:
![Schermata 2022-09-27 alle 11 02 55](https://user-images.githubusercontent.com/87669813/192483230-0c4c90ad-fa14-4170-8527-96dfc6c60370.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_32fd6_2adf50.json?branchLabel=aa%20mutations&label=nuc%20mutations:C241T,T670G,C1931A,C2790T,T2954C,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,C11750T,G12160A,C12880T,T14257C,C14408T,C15714T,G16935A,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,A22893C,T22917G,T22942A,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,C27807T,C27889T,A28271T,C28311T,C28312T,G28681T,G28881A,G28882A,G28883C,A29510C
Spike_s151N,NSP12_Y273H,Spike_K444,Spike_N460K

**Comment by FedeGueli** [comment]
2 BQ.1 + S:R190T uploaded today, now in total there are 7 viruses sampled with S:R190T, Gisaid query for monitroing it: Spike_R190T,NSP12_Y273H,Spike_K444,Spike_N460K

**Comment by FedeGueli** [comment]
3 BQ.1 from Germany uploaded today with S:D1260Y 
Gisaid query: Spike_D1260Y,NSP12_Y273H,Spike_K444,Spike_N460K

**Comment by FedeGueli** [comment]
One more BQ.1 + S:D1260Y from Germany today (total is 4 )
3 BQ.1 + S:Y170H from italy today (tot is 4)
and two BQ.1 + S:A292V from England (tot 2)

**Comment by FedeGueli** [comment]
One more S:R190T bringing the total count to 8

i have counted 2 sequences with S:A348S

**Comment by FedeGueli** [comment]
One BQ.1.1 with S:D253Y spotted in ireland today

**Comment by FedeGueli** [comment]
BQ.1.1 +S:1020S now are two.

**Comment by FedeGueli** [comment]
BQ.1. +S:A348S now 4

**Comment by FedeGueli** [comment]
BQ.1+S:A260V 5 seqs from two countries proposed in #1180

**Comment by FedeGueli** [comment]
S:346S picked up by BQ.1 (or BQ.1.1) i m counting three of them if more i will propose it separately)

**Comment by FedeGueli** [comment]
18 BQ.1 seqs with S:H146L proposing it now

**Comment by FedeGueli** [comment]
3 with S:S689I from Luxembourg

**Comment by FedeGueli** [comment]
4 with S:N164T Usa/England

**Comment by FedeGueli** [comment]
1 Bq.1.2 from Netherlands with S:346S,  EPI_ISL_15315746

**Comment by corneliusroemer** [comment]
@FedeGueli your comments get a bit overwhelming, can you edit previous comments and structure them somehow rather than adding one comment after another? That'd be very helpful!
Which ones are the most notable ones in your view, that sort of stuff would be very useful. But just adding comment after comment is making it confusing. Thanks for your work!

**Comment by FedeGueli** [comment]
Ok @corneliusroemer i collect them in one only and delete them then

**Comment by FedeGueli** [comment]
BQ.1 query : NSP12_Y273H,Spike_K444T,Spike_N460K

+ Spike_A352S    -  1 sequence from Congo Brazzaville
+ Spike_R346S   - 6 sequences
+ SPike_A348S  - 4 sequences
+Spike_N164T  - 4 sequences
+Spike_S689I   -  4 sequences
Spike_A1020S   -2 sequences
Spike_D253Y  - 1 sequence

**Comment by FedeGueli** [comment]
@corneliusroemer i will update here situation of the lineages on your post (the ones in my comment will be updated directly on it:
S:A348S reached 6 sequences from 3 countries (USA,UK, FRANCE)

**Comment by FedeGueli** [comment]
@corneliusroemer  updated

**Comment by Sinickle** [comment]
S:484V on the S:666V branch, now in 8 sequence, 6 uploaded in the last 10 days. 

S:484V seems to come up often but not be advantageous, so not expecting much from it though.

**Comment by FedeGueli** [comment]
@corneliusroemer i have split the fast and slow spike mutated lineages in the post above.

**Comment by RajLABN** [comment]
BQ.1.1* with S:D1199G - from Spain & UK | EPI_ISL_15495043, EPI_ISL_15505617

(another BQ.1* with S:D1199B  from NY | EPI_ISL_15577876 )

**Comment by ryhisner** [comment]
Seven BQ.1.1.3 + A688V from New York City today. A few others from NYC today:

• BQ.1 + V445A
• BQ.1.1 + E471Q
• BQ.1.1 + K202R
• BQ.1.1.4 + W152R
• BQ.1.2 + K278R
• BQ.1.6 + K147R
• BQ.1.14 + T478I

There are lots more, but I'm too tired to log any more.

**Comment by RajLABN** [comment]
Two more BQ.1.1* with D1199N from NY - EPI_ISL_15669230, EPI_ISL_15669316

**Comment by FedeGueli** [comment]
> Two more BQ.1.1* with D1199N from NY - EPI_ISL_15669230, EPI_ISL_15669316

please propose it @RajLABN this issue s going too big. it will be helpful to check numbers but i dot think Cornelius can designate from such a long list!

**Comment by FedeGueli** [comment]
> Seven BQ.1.1.3 + A688V from New York City today. A few others from NYC today:
> 
> • BQ.1 + V445A • BQ.1.1 + E471Q • BQ.1.1 + K202R • BQ.1.1.4 + W152R • BQ.1.2 + K278R • BQ.1.6 + K147R • BQ.1.14 + T478I
> 
> There are lots more, but I'm too tired to log any more.

Thanks a lot @ryhisner ! i noticed that S:A688V that is fast in BQ.1.8 popped up in BQ.1.1 too so i think it is in some way beneficial cc @thomaspeacock maybe interested in this.

**Comment by ryhisner** [comment]
@RajLABN, one of those BQ.1.1 + D1199N—EPI_ISL_15669316—is that crazy CA.1/BQ.1.1 recombinant that took the worst/best mutations of both and added S:F490S. 

The other—EPI_ISL_15669230—is also a recombinant—it took K147E, W152R, and F157L from BA.2.75.2*.

**Comment by ryhisner** [comment]
BQ.1.1 + S221L looks like it's up to 12 sequences—only eight have R346T, but the other four have no coverage there, and they all share ORF1b:N1191S, which isn't found in the other two BQ.1* that have S221L (both of which are BQ.1.3). 

One of the BQ.1.1 uploaded today (missing coverage at S:346) also has G482D, which I believe is a first for a BQ.1*. EPI_ISL_15677319

**Comment by corneliusroemer** [comment]
I'll close this - I've gone pretty systematically through BQ.1* and BQ.1.1* designating any interesting Spike lineages.

**Comment by Over-There-Is** [comment]
ORF3a:T151I;S:P251H 179
