### ISSUE TITLE
BA.5.1 with S:K444N, ORF7b:H42Y (88 seq., mostly Peru, Australia, Belgium, Chile, Colombia as of 01.10.22)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1084]
Proposal for a sublineage of BA.5.1
Earliest sequence: 28.06.2022 (Peru)
Countries detected: Peru (62), Australia (1), Belgium (1)

Defining mutations:
G22894T = S:K444N
C27879T = ORF7b:H42Y
C11494T

This sublineage of BA.5.1 is defined by S:K444N, ORF7b:H42Y and was mostly detected in Peru but also Australia and Belgium. Currently 64 seq on usher as of 19.09.22. The lineage is apparently disctint from those proposed in #1060.

![grafik](https://user-images.githubusercontent.com/102166254/190973148-40d316b7-e444-4026-9b76-7e96aa914c42.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1772d_81db70.json?branchLabel=aa%20mutations&c=userOrOld&label=nuc%20mutations:G22894T

Silght advantage over BA.5.1 in Peru:
![grafik](https://user-images.githubusercontent.com/102166254/190988597-71ff3521-f00e-4b67-94c5-d186043a1770.png)
https://cov-spectrum.org/explore/Peru/AllSamples/Past6M/variants?pangoLineage=BA.5.1*&aaMutations1=S%3AK444N%2CORF7b%3AH42Y&pangoLineage1=BA.5.1*&analysisMode=CompareToBaseline&

<details>
  <summary>EPI ISLs</summary>

EPI_ISL_14569107
EPI_ISL_14568972
EPI_ISL_14570567
EPI_ISL_14616086
EPI_ISL_14907206
EPI_ISL_14907210
EPI_ISL_14907208
EPI_ISL_14907211
EPI_ISL_14933982
EPI_ISL_14956931
EPI_ISL_14721738
EPI_ISL_15017634
EPI_ISL_15017655
EPI_ISL_15017657
EPI_ISL_15017730
EPI_ISL_14957135
EPI_ISL_14957140
EPI_ISL_14957138
EPI_ISL_14957137
EPI_ISL_14241953
EPI_ISL_14570564
EPI_ISL_14241951
EPI_ISL_14241952
EPI_ISL_14241954
EPI_ISL_14957136
EPI_ISL_15017654
EPI_ISL_15017649
EPI_ISL_14241955
EPI_ISL_15017660
EPI_ISL_15017658
EPI_ISL_15017656
EPI_ISL_15017653
EPI_ISL_15017651
EPI_ISL_15017648
EPI_ISL_15017650
EPI_ISL_14534944
EPI_ISL_14745821
EPI_ISL_14816078
EPI_ISL_14907459
EPI_ISL_14956939
EPI_ISL_15017714
EPI_ISL_14241792
EPI_ISL_14816867
EPI_ISL_14745857
EPI_ISL_14534942
EPI_ISL_15017343
EPI_ISL_14569099
EPI_ISL_14734976
EPI_ISL_14734974
EPI_ISL_15017729
EPI_ISL_15017722
EPI_ISL_14569095
EPI_ISL_15017421
EPI_ISL_15017319
EPI_ISL_15017316
EPI_ISL_14721868
EPI_ISL_14569103
EPI_ISL_14569109
EPI_ISL_14956934
EPI_ISL_14569102
EPI_ISL_15017712
EPI_ISL_15017735
EPI_ISL_15017720
EPI_ISL_15017723

</details>

**Comment by agamedilab** [comment]
Silghty bigger advantage over BA.5.1 in Peru:
![grafik](https://user-images.githubusercontent.com/102166254/193204370-23d4c121-bb2c-4e77-a0a6-5a430988810d.png)
https://cov-spectrum.org/explore/Peru/AllSamples/Past6M/variants?nextcladePangoLineage=BA.5.1*&aaMutations1=S%3AK444N%2CORF7b%3AH42Y&nextcladePangoLineage1=BA.5.1*&analysisMode=CompareToBaseline&

**Comment by agamedilab** [comment]
88 seq as of 01.1022.
![grafik](https://user-images.githubusercontent.com/102166254/193402089-ef9ffdee-7165-4ee3-b7cd-93a358d30560.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41811_8014b0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:G22894T

**Comment by InfrPopGen** [comment]
Thank you for taking the time to propose this issue. As the clade is not showing much growth now and has negative estimated advantage relative to its parent in Peru since late September, the issue can be closed for now. Nevertheless, please feel free to reopen (or re-propose) should the clade show marked increases in growth and relative advantage.
