### ISSUE TITLE
BA.2.75.6 with S:F486V [16 seqs as of 2022-09-29]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1086]
Noticed that BA.2.75.6 (S:346T) picked up S:F486V in 4 sequences in England and US

```txt
hCoV-19/England/PHEC-YYG4WPZ/2022|EPI_ISL_15021194|2022-09-06
hCoV-19/England/QEUH-3F89F82/2022|EPI_ISL_14948777|2022-09-05
hCoV-19/England/LSPA-3F7C438/2022|EPI_ISL_14810559|2022-08-30
hCoV-19/Australia/NSW-ICPMR-33405/2022|EPI_ISL_14993456|2022-09-05
hCoV-19/USA/NJ-GBW-LWPOAAAB19540/2022|EPI_ISL_15017960|2022-09-10
```

The AUS sequence has S:357K as well. Not sure whether these are monophyletic or not. Needs to be seen.

Two of them were uploaded today.

GISAID query: `NSP3_S403L,Spike_R346T, Spike_N460K, Spike_F486V`

The RBD is very similar to BQ.1.1 - more than any other BA.2.75 so far.

**Comment by ryhisner** [comment]
The Usher tree shows a sequence from Bahrain as well, collection date August 29, though it doesn't appear to be on GISAID yet. That would make seven sequences with this spike mutation pattern, though the Australian one—which also has S:R357K, S:D745G, S:I909V, and several non-spike mutations not found in the others—appears to be unrelated to the other six. The New Jersey, USA, sequences has two ORF1ab mutations not found int he others (ORF1a:T796I and ORF1b:T797I).
![image](https://user-images.githubusercontent.com/33738461/191136026-8bff446e-f71a-4318-9668-408b1476361e.png)

**Comment by corneliusroemer** [comment]
Numbers have tripled in 10 days - probably worth designating

**Comment by InfrPopGen** [comment]
@corneliusroemer This looks like it might  be already designated as CB.1, should it be closed?

**Comment by corneliusroemer** [comment]
@InfrPopGen you may be right - it depends whether the base lineage is BA.2.75.6 or BA.2.75.9. Both have S:346T, but .9 has G17679T before it has S:346T.

One needs to Usher to check - not sure why I didn't do that.

**Comment by AngieHinrichs** [comment]
FWIW in the UShER tree CB.1 is placed under BA.2.75.9 (with G17679T).  

Of the 5 samples above, these 4 cluster in CB.1:
```
hCoV-19/England/PHEC-YYG4WPZ/2022|EPI_ISL_15021194|2022-09-06
hCoV-19/England/QEUH-3F89F82/2022|EPI_ISL_14948777|2022-09-05
hCoV-19/England/LSPA-3F7C438/2022|EPI_ISL_14810559|2022-08-30
hCoV-19/USA/NJ-GBW-LWPOAAAB19540/2022|EPI_ISL_15017960|2022-09-10
```
But this one clusters elsewhere (off the BA.2.75 main branch, with 3 other sequences that have S:I909V / A24287G) and does not appear to have G17679T:
```
hCoV-19/Australia/NSW-ICPMR-33405/2022|EPI_ISL_14993456|2022-09-05
```

**Comment by corneliusroemer** [comment]
Oof, it's complicated, maybe worth waiting which ones grow, as this problem may just disappear on its own

**Comment by InfrPopGen** [comment]
This issue may be closed for now at least, as most CB.1 appear to have S:F486V, and no sub-lineage has, in this context, distinguished itself, as yet. Of course, this can be re-opened if new matters come to light.
