### ISSUE TITLE
Potential revision needed: BA.3 is paraphyletic in the NCBI UShER tree on cov2tree

### ISSUE THREAD

**Issue by aineniamh** [cov-lineages/pango-designation#1087]
Leaving a note here as BA.3 might need revision/ removal if it's no longer well defined. A quick look on cov2tree shows only ~33 sequences and they're scattered across the Omicron clade. Obviously not the complete GISAID phylogeny, but it would seem there's an issue placing or assigning them based on the designations.
<img width="841" alt="Screenshot 2022-09-20 at 08 55 32" src="https://user-images.githubusercontent.com/11678307/191200370-558df80c-4af3-4010-a5d0-a131ec98df4b.png">

There are also reports that BA.3 is getting assigned in some cases when it should be BA.2.75. Think it could be worth checking this lineage and that it still exists as defined in the [constellation](https://github.com/cov-lineages/constellations/blob/main/constellations/definitions/cBA.3.json).

**Comment by corneliusroemer** [comment]
Why would it need to be revised or removed? Do we doubt it exists as found in December 2021? could this not just be a inference/tree building problem?

I have never encountered any problems with Nextclade.

What's the screenshot showing? Where the original designations are currently placed? Or where pangoLEARN calls BA.3s? Or where designations that have been designated over time are now in the current Usher tree?

>There are also reports that BA.3 is getting assigned in some cases when it should be BA.2.75.

Do you have a few examples so we can have a look what's going on in these cases? It could be a Scorpio issue or Usher/pangoLEARN problem?

**Comment by AngieHinrichs** [comment]
Searching for "PANGO lineage" = BA.3 on cov2tree.org (taxonium view of Theo's pruned version of the UCSC/UShER public sequence tree) produces that image:
https://cov2tree.org/?srch=%5B%7B%22key%22%3A%22aa1%22%2C%22type%22%3A%22meta_pangolin_lineage%22%2C%22method%22%3A%22text_exact%22%2C%22text%22%3A%22BA.3%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%5D

-- but those are the sequences assigned BA.3 by `pangolin --analysis-mode pangolearn` (and come to think of it, probably still v1.13, yikes), not BA.3 designated sequences.

Here is a view of BA.3 and BA.3.1 in the full 2022-09-19 tree, with blue circles around BA.3 designated sequences:
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/186983/191329055-f1a0617e-ba45-4595-bff7-35128814a6aa.png">

The designated sequences look OK to me.

**Comment by AngieHinrichs** [comment]
@theosanderson I think BA.3 is getting entirely pruned out of cov2tree.org because it's so tiny relative to BA.2 (especially when limited to publicly available sequences).  Searching for these GenBank IDs finds 0 sequences:
```
OV434461.1
OV576709.1
OV802032.1
OV982973.1
OW067118.1
OW063049.1
OV583874.1
OV992233.1
OW270427.1
OW147945.1
OV694126.1
OV647162.1
OW966460.2
OM740650.1
OM808349.1
OV815664.1
```

Also, any chance of adding the metadata column `pango_lineage_usher` as a coloring/search option?  🙂

**Comment by aineniamh** [comment]
Thanks for following this up! I had recieved an email saying BA.3 was being assigned incorrectly for likely BA.2.75 sequences so quickly had a look on cov2tree and saw the image above!

Thanks @AngieHinrichs for checking the GISAID tree. I wonder if the cov2tree NCBI should switch annotations to the UShER assigned ones for consistency? I had just assumed that's what they were actually!

**Comment by corneliusroemer** [comment]
@aineniamh Can you share the EPI_ISLs for the incorrectly assigned sequences? Would be good to see what they look like.

**Comment by aineniamh** [comment]
I didn't get the EPI ids, but they're contained in the GISAID seqs from India since June!

**Comment by theosanderson** [comment]
Hi folks,

Sorry for causing some confusion here!

>  I think BA.3 is getting entirely pruned out of cov2tree.org because it's so tiny relative to BA.2 (especially when limited to publicly available sequences). Searching for these GenBank IDs finds 0 sequences

That sounds very plausible. Sorry about that. There's clearly a huge trade-off with the decision to prune these rare cases from the tree. For those who don't know, wherever there is a node with children A and B, and A has >5000x more descendants than B, cov2tree prunes away B and its descendants, with the rationale that it probably represents sequencing errors, which generally it does, but occasionally like this it does not. I still think that the increased interpretability to new end-users is worth it, but acknowledge the downsides.

> Also, any chance of adding the metadata column pango_lineage_usher as a coloring/search option?

Yes! Not sure why I don't do that really. I think I was waiting to get around to using the clade annotations directly, but no reason to block on that. The JSONLs [now](https://github.com/theosanderson/cov2tree/commit/40025325c512896bb5bf62eb531208cc40bf0a2b) being generated will have this, and I'll tweak the config tomorrow to surface that. I'm tempted to actually lose the non-Usher version entirely for this especially if PangoLearn is no longer the Pangolin default. Thanks for flagging.

(BTW, I have a Gmail rule that sends all activity from this repo to a certain folder -- there's so much --  so feel free to email me if I don't notice being tagged here - I was lucky to happen to spot it this time :) )

**Comment by theosanderson** [comment]
And for visibility, if you want the unpruned tree you can put Angie's original file: https://hgwdev.gi.ucsc.edu/~angie/UShER_SARS-CoV-2/public-latest.all.masked.taxonium.jsonl.gz into Taxonium either as a URL or by downloading it and selecting the local file

**Comment by AngieHinrichs** [comment]
Great, thanks Theo!

**Comment by corneliusroemer** [comment]
Thanks! Here one can see the problem that pangoLEARN has with mostly Indian
BA.2*, miscalling them as BA.3.

https://cov-spectrum.org/explore/India/AllSamples/AllTimes/variants?pangoLineage=BA.3&

Neither Usher or Nextclade have this issue. GISAID should use Usher mode of
pangolin and these problems would be solved.

GISAID also still uses a very old version of pangoLEARN data (released in
July) so all recently designated lineages will be missing as well.

**Comment by theosanderson** [comment]
This Cov2Tree change has been made. As an aside I happened to notice yesterday that the UShER tree disagrees with the PANGO topology for some of the BM sublineages

<img width="747" alt="image" src="https://user-images.githubusercontent.com/19732295/191734331-0b44382f-30c8-4eef-9de1-472ce661ffef.png">

I guess that's inevitable and it may not be clear which way is correct

**Comment by AngieHinrichs** [comment]
Yes, UShER and matOptimize are being very stubborn about placing BM.1.1 on a reversion from BM.4.1.1, and BM.1 on a reversion from BM.1.1, instead of placing BM.1 directly on BA.2.75.3 and BM.1.1 on BM.1.  🙁  

(There's a similar frustrating persistent misplacement of BA.2 > T21765C as BA.2 > C22792T > T21765C > T22792C that has caused lots of fun for designations on the affected branch...)

**Comment by AngieHinrichs** [comment]
Anyway, thanks @theosanderson for updating cov2tree.org!  🙂  If it's not too much trouble it would be nice to also offer the pangoLEARN assignments as an alternative -- the tree has some branches that are collections of sequencing errors, and then they can attract sequences from other lineages that have the same combo of errors; in those cases UShER's lineage assignment is wrong and pangoLEARN's is often right.  For example, the branch that smears out to the right at the bottom here:
![image](https://user-images.githubusercontent.com/186983/191840877-61910b67-4701-47fa-8136-16fdbd828601.png)
-- I wouldn't be surprised if many of those sequences don't really belong in BA.1.1.11.  Yep, if I zoom in to just that branch, and highlight Revertants, I see a probable run-of-nucleotides error followed by a bunch of reversions:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/186983/191841544-e65d7af8-3adf-4d91-aa65-48c9ed2599b3.png">
-- and those reversions undo BA.1.1.11 and ultimately even BA.1.1!  I bet the pangoLEARN coloring (or even pangolin in default UShER mode except I haven't got around to adding that to the metadata files, ahem) would highlight that branch's sketchiness.
