### ISSUE TITLE
XBB sublineage with S:G252V  (85 seq. Singapore, Bangladesh, Denmark, UK, Belgium, Australia, Austria as of 03.10.22) 

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1088]
Proposal for a sublineage of XBB 
Earliest sequence: 06.09.2022 (Singapore)
Countries detected: Singapore (8)

Defining mutation:
S:N460K = T22942G
S:F490S = T23031C
S:F486S = T23019C
S:G252V =G22317T

G510A = ORF1a:G82D
A19326G

Provisorial Gisaid query: Spike_F490S, Spike_F486S, Spike_V445P, Spike_N460K, Spike_G252V

This sublineage of XBB is defined by S:N460K, S:F490S, S:F486S, S:G252V, ORF1a:G82D, A19326G and is currently mostly found in Singapure. The combo S:N460K, S:F490S, S:F486S is known previously from BM.1.1 (as noted https://github.com/cov-lineages/pango-designation/issues/1058). Apparently XBB is picking up Spike_G252V in Singapore.
 

![grafik](https://user-images.githubusercontent.com/102166254/191214810-199370e9-cd3a-4eeb-8312-a3f131a24886.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18f2f_9a1a40.json?branchLabel=aa%20mutations&c=pango_lineage_usher
Red ones are some of the proposed ones:
![grafik](https://user-images.githubusercontent.com/102166254/191197112-d6dea54e-b000-408d-a98b-9cd412bf9938.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AN460K%2CS%3AF490S%2CS%3AF486S%2CORF1a%3AG82D%2CS%3AG252V&nucMutations=A19326G&aaMutations1=ORF3a%3A78Y&nucMutations1=C22792T&pangoLineage1=BA.2&

EPI_ISL_14917652, EPI_ISL_14917761, EPI_ISL_15031191-15031194,
EPI_ISL_15031201, EPI_ISL_15031899

**Comment by corneliusroemer** [comment]
Yep looks interesting, let's wait a bit for more sequences to see if the tree is clean.

**Comment by FedeGueli** [comment]
One more sequence today of this sublineage from Denmark @agamedilab

**Comment by agamedilab** [comment]
+1 England: EPI_ISL_15110234

**Comment by agamedilab** [comment]
+1 England: EPI_ISL_15127958

**Comment by agamedilab** [comment]
25 seq on usher as of 30.09.22. Expansion into Bangladesh, Denmark, UK.

![grafik](https://user-images.githubusercontent.com/102166254/193207687-49f0b53c-0868-4eff-8016-fb37e14cc4d2.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_bccf_68e9c0.json?branchLabel=aa%20mutations&c=pango_lineage_usher

**Comment by agamedilab** [comment]
+ 3 sequences (spike only) Austria: EPI_ISL_15198276, EPI_ISL_15198287, EPI_ISL_15198429,

**Comment by agamedilab** [comment]
+51 from Singapore with todays upload:

EPI_ISL_15209055, EPI_ISL_15209059-15209064, EPI_ISL_15209066,
EPI_ISL_15209073, EPI_ISL_15209076-15209077, EPI_ISL_15209079,
EPI_ISL_15209084-15209087, EPI_ISL_15209092-15209093, EPI_ISL_15209100-15209101,
EPI_ISL_15209103, EPI_ISL_15209105, EPI_ISL_15209107-15209109,
EPI_ISL_15209112, EPI_ISL_15209115-15209116, EPI_ISL_15209122,
EPI_ISL_15209128, EPI_ISL_15209130-15209131, EPI_ISL_15209133,
EPI_ISL_15209135-15209136, EPI_ISL_15209140, EPI_ISL_15209143-15209144,
EPI_ISL_15209156, EPI_ISL_15209159, EPI_ISL_15209166,
EPI_ISL_15209169, EPI_ISL_15209171-15209172, EPI_ISL_15209177,
EPI_ISL_15209180, EPI_ISL_15209183, EPI_ISL_15209189,
EPI_ISL_15209195, EPI_ISL_15209197, EPI_ISL_15209203,

**Comment by agamedilab** [comment]
I would be very happy if a designate label & milestone could be added to the issue. many thanks! @corneliusroemer @InfrPopGen
