### ISSUE TITLE
"ISSUES RECAP" of  S:K444X sub lineages with S:N460K

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1089]
I think it is worth reopening this one to present various sublineages of BA.5 which independently acquired  S:N460K. and help designation of them  linking to the issue where they have been proposed individually 
S:N460K could be acquired in two ways: via T22942A or T22942G.

So in BA.5.2.24 :
with **T22942A** we have:

**1) **CK.3** issue #1121:  defined by  Orf7a:T39I+S:N460K (T22942A) / 24 sequences / multiple countries**

**2)** **BV.2**  Issue #1244 : defined by C23707T C18687T Orf1a:K669N N:S327L S:N460K (T22942A) / 2 seqs / 2 countries
(being C23707T the defining of BA.5.2.20 i suggest that this could be misplaced here or in #1122  and could be either a Ba.5.2.20 that acquired S:444N and S:N460K independently ( cc @AngieHinrichs pls if u have time take a look at the tree at the bottom of this issue) or a BA.5.2.24 with C23707T acuqired independently or via recombination

with T22942G we have:
**1)** CK.2.1 issue #1125 defined by E:V62F  S:N460K (T22942G) 
**2)** CK.2.1.1 issue #1190 defined by E:V62F, C8389T, G10998A, Orf1a:G3578D, Orf1a:V710I , S:S255F and S:N460K 5 seqs / 5 countries 
**3)** **CK.1** Issue #1120 defined by S:N460K (T22942G) / 18 sequences / 7 countries
**4)** now designated CY.1 ( BA.5.2.7(S:K444M) +S:N460K (T22942G) from #1247 )

BA.5.2.24 seems the lineage where the combo 444+460 appeared multiple times with 460K expressed by both G and A:
![Schermata 2022-10-22 alle 14 07 21](https://user-images.githubusercontent.com/87669813/197338204-bd4793c3-1137-45be-aa44-4d8e945eed48.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_406a8_38d410.json?branchLabel=aa%20mutations&c=gt-nuc_22942&label=nuc%20mutations:G26428T

Beyond the ones belonging to BA.5.2.24 mentioned above there are :
**1)** **BA.4.6.3** #1195: it is a BA.4.6 +S:460K (T22942G ) ,S:444N:   5 sequences / 4 countries
**2)** **CL.1** #1187: it is a BA.5.1.29 (S:444N) + S:460K (T22942A)  + S:K150E : 18 sequences/ 8 countries
**3)** #1138 it is a recombinant between # 1114 and / or # 1121  4 seqs / 3 countries . **With S:460K ( T22942A)**
**4)**  **BE.4.2** #1114 it is a BA.5.3.1 + S:444N and S:460K (T22942G)9 seqs/4 countries
**5)** **DJ.1.1** from  #1245  BA.5.1.25 + S:444N + S:460K (T22942G )  2 lineages in Peru' 10seqs 
**6)** **_Unproposed_** BF.7 + S:444R + S:N460K (T22942A) : Spike_R346T,M_D3N,-NSP12_Y273H,Spike_N460K,SPike_K444R 2 seqs Belgium

Then a bunch of lineages found with NSP13_T127N,Spike_R346T,M_D3N,-NSP12_Y273H,Spike_N460K,SPike_K444T
**7)** #1252  BA.5.2.35 recombinant with BQ.1   with  S:346T S:K444T S:460K (T22942A) 
**8)** **DB.1**  from #1258 BA.5.2.25 (S:K444T)sublineage with S:R346T and S:N460K (T22942G) 10 sequences
**9)** #1252 BA.5.2.35 + BQ.1* putative Recombinant from israel 2 sequences
**10)** #1261 BA.5.2 with S:444N +S: 460K plus orf3a:A99V and Orf3a:P267S 4 sequences from Israel

**Plus** a BF.7-Bq.1 putative recombinant:
**11)** #1252 BF.7 recombinant with BQ.1* 1 seq from Switzerland

12) BA.5.2.1 sublineage with S:444N and S:460K and Orf1a:T1336I emerged in India https://github.com/cov-lineages/pango-designation/issues/1325

Already designated **BQ.1** and **BW.1** with 460K + 444T and **BU.1** with 460K + 444M

**Comment by FedeGueli** [comment]
To be noted there is EPI_ISL_14789096 a BA.4.6 with S:444N/S:460K from Australia (20August)

**Comment by FedeGueli** [comment]
Ok @corneliusroemer  i ll redo all the stuff.

**Comment by FedeGueli** [comment]
@InfrPopGen @corneliusroemer i have completely rewrite this one to facilitate your work in designating or just distinguishing various S:K444N + S:N460K Lineages:

Beyond the ones belonging to BA.5.24 mentioned above there are :
1) #1195: it is a BA.4.6 +S:460K,S:444N:   5 sequences / 4 countries
2) #1187: it is a BA.5.1.29 (S:444N) + S:460K  + S:K150E : 18 sequences/ 8 countries
3) #1138 it is a recombinat between #1114 and /or #1121  4 seqs / 3 countries
4) #1114 it is a BA.5.3.1 + S:444N and S:460K 9 seqs/4 countries

**Comment by corneliusroemer** [comment]
Thank you @FedeGueli this is a really useful summary issue now!

**Comment by FedeGueli** [comment]
Most of lineages described here have been designated. thx @corneliusroemer @InfrPopGen for your super work!
