### ISSUE TITLE
Sublineage of BA.5.2 with S:Y145H, S:S255F, & S:V445A (Central America, USA; 41 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1090]
**Description**
**Sub-lineage of:** BA.5.2
**Earliest sequence:** 2022-8-3, Nicaragua — EPI_ISL_14561905
**Most recent sequence:** 2022-9-9, USA, New York City — EPI_ISL_15015951
**Countries circulating:** (18), Costa Rica (5), Mexico (2), Nicaragua (2), France (1) likely others in Central America
**Number of Sequences:** 41 on Usher tree, 28 results by GISAID returned by query “Spike_Y145H, Spike_S255F, Spike_V445A, Spike_F486V”
**GISAID Query:** Spike_Y145H, Spike_S255F, Spike_V445A, Spike_F486V
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2* & [3-of: T4579A, A4576T, S:Y145H, S:S255F, S:V445A]
**Substitutions on top of BA.5.2:**
**Spike:** Y145H, S255F, V445A
**Nucleotide:** A4576T, T4579A, T21995C, C22326T, T22896C 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_322f5_9b2d40-BA.5.2%2BY145H%2BS255F%2BV445A.json 

**Evidence**
All of the sequences form this lineage have very recent collection dates, so it appears to be growing fast. The sample size is still small, however, so caution is warranted. It appears to have originated in Central America, possibly Nicaragua, from which the first two sequences come. 

Here is a graph of the growth of this lineage relative to Nextcladepangolineage:BA.5.2* in North America over the past three months. The growth advantage figure has been censored as it is obscene and must not be allowed to corrupt the minds of the unwashed masses. It has been reviewed by the International Institute for Knowledge and Truth and declared unfit for public consumption.

(This CovSpectrum graph does not include the eight sequences uploaded on September 18 and 19, including four from Costa Rica. It also does not seem to include either of the Nicaraguan sequences. It seems Nicaraguan data does not exist on CovSpectrum for some reason.)

![image](https://user-images.githubusercontent.com/33738461/191266362-7f2ee325-5ad3-496b-bbfb-684ce7b9d85a.png)

https://cov-spectrum.org/explore/North%20America/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5.2*&variantQuery1=Nextcladepangolineage%3ABA.5.2*+%26+%5B3-of%3A+T4579A%2C+A4576T%2C+S%3AY145H%2C+S%3AS255F%2C+S%3AV445A%5D&analysisMode=CompareToBaseline&

**Genomes**
[GISAID_hcov-19_ids_2022_09_20_12_53-BA.5.2+Y145H+S255F+V445A.csv](https://github.com/cov-lineages/pango-designation/files/9607868/GISAID_hcov-19_ids_2022_09_20_12_53-BA.5.2%2BY145H%2BS255F%2BV445A.csv)

**Comment by corneliusroemer** [comment]
Looks worth designating.

Have you checked where this lies in the global tree - whether any of the branches leading up to it would also deserve designation?

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/25161793/191279002-b9da87cc-fa72-4623-a645-381309abce6f.png">

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.23 with 25 newly designated sequences, and 0 updated designations. Defining mutations T21995C (S:Y145H), C22326T (S:S255F), T22896C (S:V445A).

**Comment by corneliusroemer** [comment]
Thanks for the quick designation @InfrPopGen :)

**Comment by FedeGueli** [comment]
EPI_ISL_15142094 acquired S:R357K too. Today big upload from Costaarica it is very fast.
