### ISSUE TITLE
Central European BA.5.9 sublineage with S:Y473F, ORF7a:V24F [8 seqs as of 2022-09-20]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1094]
Going through lineages with escape mutations I noticed this BA.5.9 (S:346I, common in central Europe) lineage with S:Y473F that has appeared more or less suddenly, with collection dates very recent only.

Germany, Croatia, Poland, Austria so far.

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/25161793/191341060-c471ab23-b461-459f-a5e2-2ee7e0ba0832.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A473&nextcladePangoLineage=BA.5.9*&nextcladePangoLineage1=BA.5.9*&

**Comment by FedeGueli** [comment]
Gisaid Query : M_D3,S_Y473F,S_R346I 

Interestingly BA.5.9 has another sublineage with S:E471Q , maybe could it tolerate better than other lineages mutations in that area which has been quite conserved through today as rightly noticed by @shay671 in a twitter thread ?

**Comment by InfrPopGen** [comment]
This one can probably be closed, at least for now, as it has shown very little growth over the past 2 months.
