### ISSUE TITLE
BE.1.2 with S:445A [29 seqs, 1 early seq Panama, growing in Canada]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1095]
Spotted this cluster in recent Canada uploads. Has a lot of antibody escape so worth tracking and grows in Canada.

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/25161793/191435587-9dd7ce0e-aaf4-4bf5-bdfe-5446580975f8.png">

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AV445A&nextcladePangoLineage=BE.1.2*&
<img width="2147" alt="image" src="https://user-images.githubusercontent.com/25161793/191435601-5169f546-7424-43b0-a587-a98ebb654fa7.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_781a_ab4bb0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T22896C

**Comment by corneliusroemer** [comment]
Resolved by 6e83aa9

**Comment by FedeGueli** [comment]
Gisaid query : Spike_V445A,Spike_R346T, NSP2_F498L
