### ISSUE TITLE
BA.2.75.1 with S:444N [4x Australia as of 2022-09-21]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1096]
Noticed a cluster of BA.2.75.1 with S:444N in today's upload from Australia.

Let's watch this. Bit too early for designation.

```
hCoV-19/Australia/SA459976/2022|EPI_ISL_15052950|2022-09-12
hCoV-19/Australia/SA459932/2022|EPI_ISL_15052930|2022-09-12
hCoV-19/Australia/SA459905/2022|EPI_ISL_15052922|2022-09-12
hCoV-19/Australia/SA456551/2022|EPI_ISL_14947013|2022-08-31
```

**Comment by InfrPopGen** [comment]
Closing for now, as this one does not appear to be growing well, and it's not been showing any advantage since mid-November (at least).
