### ISSUE TITLE
Potential new lineage causing a cluster in Mayotte

### ISSUE THREAD

**Issue by Simon-LoriereLab** [cov-lineages/pango-designation#11]
Potential new lineage

by Etienne Simon-Loriere 
Description: 

Sub-lineage of: A
Earliest sequence: 2020-12-14 (Denmark)
Most recent sequence: 2021-01-20 (Turkey)
Countries circulating: Mayotte (French territory/department, part of the Comoros archipelago) and France at least

During a recent survey of the diversity of SARS-CoV-2 in Mayotte, a cluster of divergent sequences within lineage A (19B) was noted. More sequencing is underway to follow up. This variant has been also detected in Europe and France but sporadically.
We note 18 changes in the long branch leading to this cluster, including 7 NS changes in the spike (L18F, L452R, N501Y, A653V, H655Y, D796Y, G1219V), on a 614D background. We are exploring theories for emergence. A Pango lineage designation would help exchanges.

Genomes
[Mayotte_cluster_19B.txt](https://github.com/cov-lineages/pango-designation/files/5975465/Mayotte_cluster_19B.txt)

Evidence

![Screenshot_2021-02-13 auspice us](https://user-images.githubusercontent.com/60473383/107847805-f9788000-6dee-11eb-8e5e-3a2fdd106771.png)

**Comment by aineniamh** [comment]
New lineage designated A.27, tagged in release [v1.0.5](https://github.com/cov-lineages/pango-designation/releases/tag/v1.0.5). Apologies for the short delay!

**Comment by aineniamh** [comment]
Newly trained pangoLEARN model available now (tag: [2021-01-18](https://github.com/cov-lineages/pangoLEARN/releases/tag/2021-02-18))

**Comment by Simon-LoriereLab** [comment]
Thanks a lot Áine, it is super useful!
