### ISSUE TITLE
Delta (21I) / BA.2 recombinant (5 seq. Philippines, Austria)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1100]
Proposal for a sublineage of B.1.617.2
Earliest sequence: 22.08.2022 (Philippines)
Countries detected: Philippines (4), Austria (1)

This sublineage is defined by c.75 mutations compared to root (see below) including S:R19I, S:L212S, S:S371F, S:S373P, S:S375F, S:T376A, S:D405N, S:R408S, S:N440K, S:F486P, S:Q498R, S:Y505H, S:R681H, S:N703I, S:N764K, S:Q954H, S:N969K and was first detected at the Philippines (4) but also Austria (1).

To my knowledge this is the first big potetnial Delta saltation in recent time. I noticed the cluster from one odd sequence (EPI_ISL_15057614) of yesterdays Austria upload. No other Delta like sequence was uploaed in that batch. Interestingly this sequence was the apparently only one so far in Austria carrying S:F486P ( a double nuc mutation). All other European sequences with S:F486P collected since August belong to BA.2.10 and sublineages. 

Provisorial GISAID query: Spike_N703I, Spike_P25S

Defining mutations (derived from usher):

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/litho/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/litho/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

nuc | unique | T670G, G6576T, G7091A, G21618T, T22197C,   C22674T, T22679C, C22686T, A22688G, G22775A, A22786C, T22882G, T23018C,   T23019C, A23055G, T23075C, G23604A, A23670T, C23854A, A24424T, T24469A,   T26819C, T27718C
-- | -- | --
nuc | homoplasies | C2790T, C4893T, C6196T, T15030C, C15237T, C16616T, C21635T, C22188T,   G22205C, G22898A, G22992A, A23013C, A23063T, C23525T, T23599G, G23948T,   C25000T, T25469C, C25854T, C27752T
nuc | reversionsToRoot | T25469C
ORF1ab | unique | S135R, S2104I, V2276I
ORF1ab | homoplasies | T842I, T1543I, T5451I
S | unique | R19I, L212S, S371F, S373P, S375F, T376A, D405N, R408S, N440K, F486P,   Q498R, Y505H, R681H, N703I, N764K, Q954H, N969K
S | homoplasies | P25S, P209L, D215H, G446S, S477N, E484A, N501Y, H655Y, N679K, D796Y
ORF3a | homoplasies | L26S
ORF3a | reversionsToRoot | L26S
ORF7a | unique | F109L
ORF7a | homoplasies | T120I

</body>

</html>

![grafik](https://user-images.githubusercontent.com/102166254/191702065-ff560e39-2cc2-4e56-9dce-d4f70233b2b4.png)

A total of 5 sequences are derived from recent uploads.
![grafik](https://user-images.githubusercontent.com/102166254/191695959-85e509f3-f396-4981-9e46-3a1f5cfe2661.png)

Nextclade compared to BA.2:
![grafik](https://user-images.githubusercontent.com/102166254/191701100-5384f2ee-e28d-4796-b21c-7d54d213bd10.png)
![grafik](https://user-images.githubusercontent.com/102166254/191701726-a207b84e-7e31-4709-8d87-d16c99455bcb.png)

![grafik](https://user-images.githubusercontent.com/102166254/191700392-5b6cb467-9922-4803-92fd-a8ac74c45513.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_417ed_c18a70.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C27638T

A big jump for Delta if confirmed:
![grafik](https://user-images.githubusercontent.com/102166254/191700713-efd5ad4e-7bdd-4ff2-aea1-74c2dd592bd4.png)

EPI_ISL_15057245-15057248, EPI_ISL_15057614

**Comment by ryhisner** [comment]
Saw this yesterday morning but wanted to leave it to the recombinant experts to propose as I don't feel knowledgeable enough to give recombinants the proper treatment. Super interesting sequences. One of the most mysterious aspects of it to me is the Q498R *without* N501Y. Ever since the brilliant in vitro yeast display RBD evolution study by Bjorn Meyer and Gideon Schreiber did in early 2021 (final publication in Nature was in August, 2021, but the original preprint was out January 6, 2021), we've known that Q498R reduces ACE2 binding and RBD stability by itself but greatly increases ACE2 affinity in the presence of N501Y. https://www.nature.com/articles/s41564-021-00954-4

![image](https://user-images.githubusercontent.com/33738461/191727171-36ae195f-eb6a-4d22-bf97-61fd4ac06ee8.png)

Of course, this effect could weaken somewhat on a different spike background, but it seems unlikely to be eliminated. By itself, this particular variant doesn't overly frighten me; as @corneliusroemer has often pointed out, diversity in the first sequences of a lineage usually indicates slow growth. But if this picks up N501Y, as seems likely if it's able to stick around long enough... watch out. 

Delta, for whatever reason, has never been able to pick up many RBD mutations—even in chronic cases—and for a while now I've thought the nightmare scenario would be a Delta that picks up Q498R-N501Y, which might increase ACE2 affinity enough to create space for multiple immune-evasive RBD mutations. Of course, there could be other reasons Delta struggles to pick up RBD mutations that have nothing to do with ACE2 affinity, so maybe my thoughts are way off-track. In any case, this one still has the Omicron S2, including N969K, which seems to be the keystone to Omicron's proficient endosomal entry and its very weak TMPRSS2-entry and cell-cell fusion capabilities, as discovered by @thomasppeacock. So this isn't my hypothetical nightmare scenario, though yesterday a chronic Beta/Omicron recombinant appeared *without* the Omicron S2. Just a singlet and will most likely remain one, but if that one happens to spread, it could be disastrous. GISAID ID is EPI_ISL_15058903 if anyone's interested.

**Comment by ryhisner** [comment]
To better picture the significant diversity already present in this lineage, I put together this image from the Usher tree. 
![image](https://user-images.githubusercontent.com/33738461/191728100-3a0603d1-b35e-4e39-906a-8f8b27e6e684.png)

**Comment by cvejris** [comment]
This spike is definitely omicron, not Delta. If anything, this ought to be a recombinant

**Comment by agamedilab** [comment]
@ryhisner many thanks for yyour comments.

This has N501Y (see mutation Table under "S homoplasies" or Usher tree in first post)

Here is also the default nextclade mutation chart vs WT:

![grafik](https://user-images.githubusercontent.com/102166254/191730220-bf835e2f-a713-46db-997c-47a4abc9008c.png)

**Comment by agamedilab** [comment]
@cvejris A curious detail is that neither Austria nor the Philippines have other sequenced cases with S:F486P that could act as source for recombination (as of 22.09.22).
![grafik](https://user-images.githubusercontent.com/102166254/191731747-9ba25764-5e25-405b-82ef-014dd86f80a8.png)


![grafik](https://user-images.githubusercontent.com/102166254/191731326-1c850e12-bd8f-447b-94ac-7888af8b8f1d.png)

**Comment by ryhisner** [comment]
Oh, thanks for point out that it has N501Y, @agamedilab. I must've been thinking of another recombinant I'd recently seen that had Q498R but not N501Y. The variant situation is getting so complex that I'm getting things completely mixed up!

**Comment by FedeGueli** [comment]
@ryhisner sorry i am.a vit confused is this  same u spotted yesterday?

**Comment by agamedilab** [comment]
Also worth highlighting is the combo S:L212S, S:P209L, S:D215H which apparently does not occur in any other lineage so far.

![grafik](https://user-images.githubusercontent.com/102166254/191776979-bc38c3c3-e3d2-42d8-8964-b10defe2c3a5.png)
![grafik](https://user-images.githubusercontent.com/102166254/191777018-45f9f1a9-775d-4a57-9a46-3ff22a12ec79.png)
![grafik](https://user-images.githubusercontent.com/102166254/191777041-6903268d-5113-4bad-b895-a9bae54be65a.png)

**Comment by silcn** [comment]
This is definitely a recombinant and not a pure Delta saltation, and the title should be changed accordingly.

It is BA.2/Delta/BA.2/Delta.
1st breakpoint between 2790 and 4184 (recombinant has ORF1a:T842I but not ORF1a:G1307S)
2nd breakpoint between 22578 and 22674 (recombinant does not have S:G339H but has S:371F)
3rd breakpoint between 25000 and 25584 (recombinant has C25000T but not C25584T)

The Delta parent is from Nextstrain clade 21I rather than the more common 21J. It appears that 21J never got a foothold in the Philippines.

**Comment by shay671** [comment]
I also got 21I to be the most suitable than all 5 B.1617.2 main clades, with no 21I sub lineage more suitable. 
But the other parent seems most closely BA.2.10.4. 
But i find it somehow to be with 5 and not 3 breakpoints starting with BA.2.10.4.  Could it be ?

**Comment by AngieHinrichs** [comment]
[sc2rf](https://github.com/lenaschimmel/sc2rf) also finds it as a 21I / 21L recombinant:
<img width="1689" alt="image" src="https://user-images.githubusercontent.com/186983/191818631-b134f219-8e5a-4c82-a9d2-f2371e1c5797.png">

**Comment by AngieHinrichs** [comment]
If it were strict BA.2.10.4 I would also expect to see C24990T (S:P1143L) and T23042C (S:S494P).   The T23018C,T23019C (S:F486P), the 23040 reversion (S:R493Q) and G22898A (S:G446S) match BA.2.10.4 -- but each of those mutations is also found in at least one other designated lineage.  There is so much convergent evolution & probably unsampled diversity out there, it's increasingly difficult to tell what sequences are related and in what order these mutations are acquired.

**Comment by shay671** [comment]
After further analysis -

If it is BA.2.10.4 and not BA.2 in this recombination, it raises the breakpoints from 3 to 5, which makes this less likely. 
The mutations @AngieHinrichs  just mentioned that are missing raise the probability; of course, it's not BA.2.10.4. 

There are 21 nucsubs (not dels) added mutation (non-BA. 2 nor 21I). Most are not converging with past variants. The highest hit I found is 5-6 mutations (all are from nonhuman host samples).

So -this is still kind of strange. Maybe a recombinant that went further saltation in a cryptic source?

**Comment by FedeGueli** [comment]
Gisaid query that finds 5 / 5 : NS7a_F109L,NSP13_T127I

Interesting to note that this one has Orf1b:1050I

**Comment by shay671** [comment]
This variant has 26 mutations not found in any of its ancestors. 19 of which (~73%) are NS/Dels. 
Out of those, 19 NS/Del's-  11 are in S1. Meaning a strong concentration of NS evolvement in the S1 (in the BA.2 and the 21I parts).
S1 mutations are converging, which includes the two del's in the NTD  3 RBD mutations (2 of which in the same codon) and an RBD reversion.
These are indicators of a saltation evolvement, similar to what we see in chronic patients.

Also
If I understand correctly, this variant has ~25% BA.2. 
It also has seven novel mutations (not found in BA.2 nor 21I), which are synonymous/extragenic (and could be an estimator for illness length), only 1 of which is in the BA.2 part.
This may hint at a 21I chronic patient getting infected with BA.2. 

By the way - if I see it correctly, it also has an insertion of 3 nucleotides in NSP12b

**Comment by agamedilab** [comment]
@AngieHinrichs @shay671 many thanks for your analyses and comments! Given the amount of recent convergence and jumps in BA.2*, BA.5* etc. in recent days I initally thought that this could be a Delta catching up by converging towards a Omicron like spike. @AngieHinrichs many thanks for the clarifiying sc2rf analyses.

**Comment by thomasppeacock** [comment]
![image](https://user-images.githubusercontent.com/79373149/191961561-f7e923a6-8663-477f-aa68-e6e67c064890.png)
Had a go at making a breakpoint diagram comparing to the other complex recombinants XAY and XBA - I count 3 breakpoints and a tonne of private mutations. Concur with Silcns breakpoints above with slight alteration of final breakpoint between 25469 (its missing ORF3a:S26L) and 25584 (its missing C25584/ORF3a:T64T)

**Comment by FedeGueli** [comment]
2 new sequences of this one

**Comment by FedeGueli** [comment]
![Schermata 2022-09-24 alle 19 32 08](https://user-images.githubusercontent.com/87669813/192111206-0470bb0b-705a-4f98-8a3a-7879b4168f63.png)
Nextclade confirms.

**Comment by FedeGueli** [comment]
@corneliusroemer @thomasppeacock @AngieHinrichs @InfrPopGen i suggest a fast designation of this , recombination with the worst Sars cov 2 lineage and spread in three continents suggesting some sort of prevalence or growth in Philippines.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XBC with 7 newly designated sequences, and 0 updated designations.

**Comment by ryhisner** [comment]
One of these showed up in California. Collection date September 7. EPI_ISL_15103168

**Comment by c19850727** [comment]
As shwon in @FedeGueli 's screenshot, 4 genomes have additional **ORF1a:S391F**, **ORF1a:T3255I** and **S:L452M** (2 from Philippines, 1 from US-CA and 1 from US-AZ).

**Comment by agamedilab** [comment]
Now the lineage (XBC) clusters more closely to XBA and XBY according to usher:

![grafik](https://user-images.githubusercontent.com/102166254/192145598-10c181d2-d90e-49c2-b382-9707ccfc8c3a.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21a50_54740.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G15451A,C16466T,C19220T,A22688G,A22786C,T25000C,C25469T,T25584C,T26270C,G26577C,A26709G,T26767C

Could RIPPLES shed light on the potential partners/origins? @AngieHinrichs

**Comment by AngieHinrichs** [comment]
> Could RIPPLES shed light on the potential partners/origins? @AngieHinrichs

Good question @agamedilab!  The sequences are not yet in the UShER tree so ripples can't be applied yet, but hopefully by tomorrow they will be in the tree at least.  

In general, the placement in the tree of any recombinant lineage should be taken very skeptically because "tree" is the wrong data structure to represent recombinants, and UShER is just finding a tree that minimizes the number of substitutions required to explain the observed sequences.  When recombinant lineages from Delta and Omicron are placed together, they may have similarly placed breakpoints but different private mutations, for example, so while they have many familiar mutations in common, they might be derived from sequences that are not closely related to each other.

I think @thomasppeacock has an updated version of the diagram he shared [here](https://twitter.com/PeacockFlu/status/1563198682710740992) that includes XBC and shows a striking similarity in the first breakpoint in Spike among XAW, XAY, XBA, and now XBC.  Very much in line with the recent theme of convergence seen in all of the antibody-escape RBD mutations recurring in recent BA.2.75 / BA.5 sub-sub-sub-lineages.

**Comment by agamedilab** [comment]
@AngieHinrichs many thanks for comment! I am curious what RIPPLES would find.

**Comment by FedeGueli** [comment]
5 new sequences today 4 philippines 1 austria

**Comment by agamedilab** [comment]
2 more from Australia: EPI_ISL_15192669-15192670

**Comment by agamedilab** [comment]
2 more from England and Singapore: EPI_ISL_15209102, EPI_ISL_15209792
Total of 16 seq from 7 countries.

![grafik](https://user-images.githubusercontent.com/102166254/193552715-4ec14515-109a-44af-9e56-27396726c936.png)

**Comment by m-gall** [comment]
Added another from New South Wales, Australia - EPI_ISL_15250238

**Comment by FedeGueli** [comment]
@AngieHinrichs @shay671 @silcn at the end of the discussion what is th consensus for the parental BA.2 lineage for XBC ?

**Comment by silcn** [comment]
@FedeGueli there isn't enough left from the BA.2 parent to tell, it looks like all the private mutations were picked up during the saltation. All we can do rule out some of the big BA.2 branches e.g. C22792T.

**Comment by AngieHinrichs** [comment]
Ripples looks for one or two breakpoints -- this seems to have more.  There are 4 mutations in Omicron-derived regions that are suggestive of some sublineages of BA.2.75.2 or BA.2.75.3: G22813T, G22898A, T23018C, T23019C.  G22813T and G22898A are in all BA.2.75.2.  T23018C and T23019C are found together in BA.2.75.2 sublineage CA.4 and BA.2.75.3 sublineages CJ.1, CV.2, and CH.3.  All four of those mutations are pretty recurrent in general though, so it's not a slam-dunk, just suggestive I think.  I have not looked for mutations in those BA.2.75 sublineages that would be expected in Omicron-derived regions of XBC -- if they are missing, that would be evidence against those sublineages.

**Comment by AngieHinrichs** [comment]
FWIW here are my notes on XBC mutations found in other VoI designated lineages:
<details><summary>long list, click to expand</summary>

```
T670G	BA.2
C2790T	BA.2
C4893T  BA.2.2,BA.2.38.2,XR
C5184T	Delta
A5584G	Delta (21I)
C6196T  BA.2.33,BA.2.35,XS
G6576T
G7091A
C9073T	B.1.641
C9891T	Delta (21I), some P.1, B.1.637
T11418C Delta (21I)
C11514T Delta (21I)
C13019T Delta (21I: AY.10,AY.11,AY.133,AY.2,AY.24,AY.24.1,AY.26,AY.26.1,AY.27,AY.28,AY.37,AY.38,AY.47,AY.55,AY.56,AY.57,AY.58,AY.59,AY.60,AY.61,AY.62,AY.63,AY.64,AY.65,AY.66,AY.67,AY.68,AY.69,AY.70,AY.71,AY.72,AY.73,AY.74,AY.75,AY.75.2,AY.75.3,AY.9,AY.9.2,AY.9.2.1,AY.9.2.2)
C14408T
T15030C
C15237T	AY.42.1
G15451A	All Delta, BA.2.75, many recombs
C16466T	All Delta, some recombs
C16616T
C21618T BA.2
C21635T	
C22188T	BE.4.1
T22197C	BA.2.50,BA.2.72
G22205C	B.1.640.2
C22227T	Delta (21I)
C22674T	Omicron
T22679C	Omicron
C22686T	Omicron
A22688G	BA.2
G22775A	BA.2
A22786C	BA.2
G22813T	recurrent, including BA.2.75
T22882G	Omicron
G22898A	BA.1, BA.2.75
G22992A	Omicron
C22995A	Omicron, Delta
A23013C	Omicron, AY.122.6
T23018C	BA.2.10.4, sublineages of BA.2.75.2 (CA.4) and BA.2.75.3/BM.* (CJ.1, CV.2, CH.3), XBF, XBK, XBB.1.5
T23019C	BA.2.10.4, BA.2.75.2, subs of BA.2.75.3 (BM.1, CJ.1, CV*, BM.4.1(CH*), also subs of BA.2.3.20 (CM.*)
A23055G	Omicron
A23063T	Omicron, Alpha
T23075C	Omicron
C23525T	Omicron
T23599G	Omicron
C23604A	Omicron, Alpha
A23670T
C23854A	Omicron
G23948T	Omicron
A24424T	Omicron
T24469A	Omicron
C25000T	Omicron
C25854T	
T26767C	Delta
T26819C
T27718C
C27752T	Delta
G27890T
A27898C
A28271T Omicron, also P.5, C.37, many recombs
A28461G	Delta
G28881T	Delta
G29402T	Delta
G29742T	Delta
```
</details>

**Comment by silcn** [comment]
@AngieHinrichs G22813T is S:K417N which is in BA.2. There is no T22942G = S:N460K which we would expect to find in any BA.2.75-derived lineage.

**Comment by AngieHinrichs** [comment]
> G22813T is S:K417N which is in BA.2

Oops, how did I miss that?!  Thanks.  I will amend my notes above.

> There is no T22942G = S:N460K which we would expect to find in any BA.2.75-derived lineage.

OK then, that is a strong indicator that it's not BA.2.75*.  Just a lot of recurrent / advantageous mutations.  Thanks again!

**Comment by corneliusroemer** [comment]
@AngieHinrichs I just noticed that reversions of 13019 are messing up the XBC tree (West Australia seems to struggle with it). So maybe you can mask that mutation on the branch? Or maybe just mask it for Australia-WA strains? That would improve the tree a lot.

Similarly, 27718 is also often reverted, so is 22329 and 25000.

If you mask these on the XBC branch we'd get a _much_ cleaner tree, with much better understanding of what's going on.

<img width="1984" alt="image" src="https://user-images.githubusercontent.com/25161793/218222755-d2dfa022-5945-4a92-8def-00628c48f674.png">

Is there a way I can help you maintain these branch specific masks? I browse Usher trees a lot so would be neat if I could just send some PRs your way :)

**Comment by AngieHinrichs** [comment]
> reversions of 13019 are messing up the XBC tree ...
> Similarly, 27718 is also often reverted, so is 22329 and 25000.

OK, those will be masked in the 2023-03-01 build and beyond.  (13019 and 25000 have been masked for a few days because I noticed them independently; I'm just working my way back through my inbox now and saw this suggestion.)

> Is there a way I can help you maintain these branch specific masks?

Pointing them out in pango-designation issues (or email/slack etc) is helpful; now that I have a [simpler way](https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/utils/otto/sarscov2phylo/branchSpecificMask.yml) to specify these it's less effort to add new sites than it used to be (although there's always the caveat that recombinants placed on branches with masked reversions could be missing some reversions that they really ought to have).

**Comment by ryhisner** [comment]
I happened to notice the _**exact**_ same NSP12 insertion (ORF1b:ins_G814D or ins15909GAT) in a remarkable BA.2.10 sequence collected on October 3, which seemed an incredible coincidence to me—almost too unlikely to believe. But as I was looking at homoplasic insertions like ORF3a:ins103P (ins25701_CCC, sometimes ins25701_CCCCCC), N:ins_238Q (ins28987_CAA), S:ins253_S (ins22320_TTC), ORF1a:ins930E (ins_3055GAA), ORF1a:ins_936E (ins_3073GAA), and so on, which all involve nucleotide repeats that presumably cause an RdRp stutter, I thought back to this one. I'm convinced it has the same explanation. (Incidentally, it's not entirely clear to me why such repeats cause an RdRp stutter. It's easy to imagine a human copying something down to get confused by multiple repeats of the same thing, but it's harder for me to imagine why the same would happen to the RdRp.)

There's a repeat GAT in the exact location of the 15909GAT insert. And given that ORF1b:G814D is a mutation that happens fairly regularly, I think it's safe to say that the triple-D motif this creates doesn't cause a great deal of disruption or harm, so such an insertion is fairly well tolerated.

### **ORF1b:ins_G814D or ins15909GAT**
<img width="672" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/cdcd3239-5052-4828-a177-ef6f086e128b">

Below are some images depicting the homoplasic insertions I mentioned above, utilizing @theosanderson's invaluable GenSplore tool, which I can't recommend highly enough. https://gensplore.genomium.org/?gb=%2Fsequence.gb


### **ORF3a:ins103P (ins25701_CCC, sometimes ins25701_CCCCCC)**
This one I'm almost certain is caused both by the CCCC repeat at 25700-25703 and the presence of a "slippery sequence" of sorts on the 3' end of the CCCC that consists of 13/16 T's or A's. Part of the reason I feel certain of the role of this slippery region is that this insertion is hugely overrepresented in sequences that have ORF3a:L108F, which makes that 16-nt stretch even more slippy with 14/16 nucs being T or A.
<img width="1223" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/1aa9fd93-960e-4c76-8238-462d5d400bb9">



### **N:ins_238Q (ins28987_CAA)**
The PolyQ region of N gets a bit out of hand with this one. 
<img width="1248" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/ff2854ce-e9a5-4a09-a24f-b5fe58c557f4">


### **ORF1a:ins930E (ins_3055GAA), ORF1a:ins_936E (ins_3073GAA)**
There are over 650 genomes with the first insertion and over 1000 with the second one. 
<img width="1141" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/283f07cf-e2cc-4cef-8a6f-42f2ef0d581a">


### **S:ins253_S (ins22320_TTC)**
Nextclade registers this as a TCT insertion, but I'm pretty sure its actually TTC one nucleotide earlier, which is equivalent.
<img width="1167" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/c36e4203-cab2-48f4-9529-758a137dc4c1">

**Comment by Over-There-Is** [comment]
C9073T, T15030C= 21I> C2509T> G25352T(S:V1264L)> C9073T> T15030C, undesignated yet

**Comment by FedeGueli** [comment]
> C2509T> G25352T

what is this? have u the USHer tree for it?

**Comment by Over-There-Is** [comment]
> > C2509T> G25352T
> 
> what is this? have u the USHer tree for it?

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_343cd_f26970.json?f_userOrOld=uploaded%20sample

An undesignated branch, mislabeled as AY.38 by usher.

**Comment by Over-There-Is** [comment]
> > > C2509T> G25352T
> > 
> > 
> > what is this? have u the USHer tree for it?
> 
> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_343cd_f26970.json?f_userOrOld=uploaded%20sample
> 
> An undesignated branch, mislabeled as AY.38 by usher.

@AngieHinrichs all of undesignated 21J+C2509T branches are mislabeled as AY.38
