### ISSUE TITLE
Sublineage of BA.5.2 with S:N481K, ORF1a:N3540D, & ORF1b:T2488M

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1101]
**Description**
**Sub-lineage of:** BA.5.2
**Earliest sequence:** 2022-9-3, USA, Massachusetts (EPI_ISL_14939063), Virginia (EPI_ISL_15027761), Texas (EPI_ISL_15063899)
**Most recent sequence:** 2022-9-14, South Korea — EPI_ISL_15058623
**Countries circulating:** USA (8), South Korea (1)
**Number of Sequences:** 9
**GISAID Query:** Spike_N481K, NSP5_N277D, NSP16_T91M 
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2 & S:N481K & ORF1a:N3540D
**Substitutions on top of BA.5.2:**
**Spike:** N481K
**ORF1a:** N3540D (NSP5_N277D)
**ORF1b:** T2488M (NSP16_T91M)
**Nucleotide:** A10883G, C20930T, T23005A

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_f423_ccd000%20-%20BA.5.2%20%2B%20N481K%20%2B%20more.json

![image](https://user-images.githubusercontent.com/33738461/191862199-9a9e590f-ab2b-4bd4-b570-f10adc1e8f0b.png)

**Evidence**
Nine sequences is a small number, but this lineage has been found in a wide geographic spread of US states and in South Korea despite the first sequence having been collected on September 3. The US states in which it has been found include Virginia (4), Texas (1), Georgia (1), New Jersey (1), and Massachusetts (1).
Furthermore, there is virtually no genetic diversity here, indicating rapid spread. The eight US sequences are identical, and the South Korean sequence, though Usher places it three nuc mutations apart from the others, likely has either zero or one nucleotide difference from the US sequences. The “reversion” in the low-coverage South Korean sequence is accompanied by numerous other “missing” mutations that clearly should be there, and another nucleotide difference is adjacent to an area lacking coverage and therefore is likely a sequencing artifact. 

ORF1a:N3540D is an NSP5 mutation, a notably impactful part of ORF1a. All eight US sequences were collected in the four-day span from September 3-6. This sublineage occurs in the ORF1b:T1050N branch of BA.5.2 tree, which is known to have a growth advantage over the non-ORF1b:T1050N part.

Looking at the downsampled global tree, you can see that this lineage shares the synonymous nucleotide change C27012T with BA.5.2.3, BA.5.2.6, BA.5.2.20, and numerous other undesignated BA.5.2 branches.

![image](https://user-images.githubusercontent.com/33738461/191861963-d61f0795-6a93-45a6-886e-f0cd6973fc3e.png)

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_14939063, EPI_ISL_15027761, EPI_ISL_15029427, EPI_ISL_15058623, EPI_ISL_15063899, EPI_ISL_15064502, EPI_ISL_15064869, EPI_ISL_15064904, EPI_ISL_15065849
</details>

**Comment by FedeGueli** [comment]
S:N481K was in a proposed late delta sublineage spotted by @C19850727 that in New Zealand was faster than BA.1, and it was the only one we saw being faster than at least one Omicron lineage.

**Comment by FedeGueli** [comment]
11 seqs as today one newly uploaded from Indonesia.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there has been very little detected growth over the past couple of months, and this one still has not reached appreciable numbers, it is being closed for now. Please feel free to request reopening or to re-propose this if there should be a marked expansion of this clade.
