### ISSUE TITLE
A different Delta recombinant from St Petersburg, Russia?

### ISSUE THREAD

**Issue by MCB6** [cov-lineages/pango-designation#1103]
Three nearly-consecutive accessions from St Petersburg are marked as "ML" (Delta and Omicron) 
EPI_ISL_15084867, EPI_ISL_15084868, EPI_ISL_15084871
They are from the same Outpatient Clinic Number 107 (and the two numbers missing in the series above are both BA.2.75's, which is still very rare in Russia). Perhaps the selection wasn't random? 
The sequencing lab, of Russian Influenza Institute, was the one which first spotted the previous Delta/Omicron recombinant there, the XAW. So it wasn't a kind of a place from which one would expect a routine contamination...
![image](https://user-images.githubusercontent.com/93294184/192061166-a703c24d-fe90-4c48-9cfc-0ceff0f68574.png)

**Comment by thomasppeacock** [comment]
Just taking a look - I think they might just be XAW? currently version of pango being used by GISAID hasnt got XAW included yet which would be why they're not getting assigned.

**Comment by thomasppeacock** [comment]
Going to close for now as this appears to have been a duplicate
