### ISSUE TITLE
Sequences of lineage B.1 without specific classification assigned

### ISSUE THREAD

**Issue by marorjuelarod** [cov-lineages/pango-designation#111]
### **Issue:** 
Sequences of lineage B.1 without specific classification assigned
**By:** Marcela Orjuela Rodriguez, Alberto Cedro Tanda, Mireya Cisneros Villanueva, Alfredo Hidalgo Miranda. 

Sub-lineage of B.1
Earlier sequence: November 30, 2020
Most recent: June 5, 2021
### **Description**

Since April, we have observed an increase in sequences classified as B.1 by pangoLEARN from Mexico. These sequences are reported to GISAID by different Health Institutes of the country. Although they have high coverage and acceptable quality values, they do not obtain a specific lineage assignment. We have found 108 high-quality sequences from Mexico, the United States, Germany, Switzerland, and France that exhibit this condition. We have generated a phylogeny for these sequences in Nextclade by finding the clustering patterns described in the attached figures.

The sequences mainly share the mutations P314L, D614G, P681H, P959S, I3618V, T3255I, T732A, T478K, T4175I. Given these mutations, we consider they are related to the B.1.1.519 lineage. However, we were unable to confirm this assignment. Additionally, more than 20% of our data set presents the substitutions N: R203K, N: G204R, ORF1a: I3352F, ORF8: I4P. 27% of our sequences lost the ORF1a: T4175I substitution. We want to ask you if this is a misclassification by PangoLEARN given the introduction of new variability in the B.1.1.519 lineage or if it could be the emergence of a subclade of this group.

### **List of characteristic substitutions**

![image](https://user-images.githubusercontent.com/85902676/121949144-c226cb00-cd1d-11eb-82a3-a9dc31ee1488.png)

### Country circulation

Mexico, the United States, Germany, Switzerland, and France.

![image](https://user-images.githubusercontent.com/85902676/121949486-1b8efa00-cd1e-11eb-86db-65adc1f3e156.png)

### Phylogeny

![image](https://user-images.githubusercontent.com/85902676/121950159-e46d1880-cd1e-11eb-918d-fa49179c59cc.png)

![image](https://user-images.githubusercontent.com/85902676/121950268-05356e00-cd1f-11eb-9eba-08b2049863dc.png)

### Genomes

<b style="font-weight:normal;" id="docs-internal-guid-c5ed04af-7fff-3b1e-7488-ef28fd564922"><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:12pt;"></p><div dir="ltr" style="margin-left:0pt;" align="left">
EPI_ISL_1038459 | EPI_ISL_1404045 | EPI_ISL_1628668 | EPI_ISL_2105760
-- | -- | -- | --
EPI_ISL_1040536 | EPI_ISL_1416488 | EPI_ISL_1650365 | EPI_ISL_2105837
EPI_ISL_1055006 | EPI_ISL_1424018 | EPI_ISL_1660622 | EPI_ISL_2135078
EPI_ISL_1134327 | EPI_ISL_1478892 | EPI_ISL_1660623 | EPI_ISL_2166589
EPI_ISL_1134421 | EPI_ISL_1478901 | EPI_ISL_1660624 | EPI_ISL_2341319
EPI_ISL_1168493 | EPI_ISL_1478915 | EPI_ISL_1660626 | EPI_ISL_2341320
EPI_ISL_1168544 | EPI_ISL_1483140 | EPI_ISL_1660627 | EPI_ISL_2341333
EPI_ISL_1181708 | EPI_ISL_1500181 | EPI_ISL_1662114 | EPI_ISL_2343011
EPI_ISL_1195271 | EPI_ISL_1500182 | EPI_ISL_1700835 | EPI_ISL_2343013
EPI_ISL_1212960 | EPI_ISL_1516812 | EPI_ISL_1732580 | EPI_ISL_2444448
EPI_ISL_1279558 | EPI_ISL_1532273 | EPI_ISL_1732586 | EPI_ISL_847857
EPI_ISL_1279868 | EPI_ISL_1553220 | EPI_ISL_1736395 | EPI_ISL_847860
EPI_ISL_1288300 | EPI_ISL_1553221 | EPI_ISL_1807324 | EPI_ISL_847863
EPI_ISL_1288301 | EPI_ISL_1553222 | EPI_ISL_1807325 | EPI_ISL_897718
EPI_ISL_1288449 | EPI_ISL_1573033 | EPI_ISL_1807332 | EPI_ISL_897740
EPI_ISL_1300551 | EPI_ISL_1575449 | EPI_ISL_1810831 | EPI_ISL_897757
EPI_ISL_1305971 | EPI_ISL_1585624 | EPI_ISL_1824452 | EPI_ISL_897766
EPI_ISL_1313861 | EPI_ISL_1585654 | EPI_ISL_1824487 | EPI_ISL_897791
EPI_ISL_1315488 | EPI_ISL_1591601 | EPI_ISL_1857272 | EPI_ISL_897812
EPI_ISL_1319085 | EPI_ISL_1608160 | EPI_ISL_1857273 | EPI_ISL_897813
EPI_ISL_1336607 | EPI_ISL_1610793 | EPI_ISL_1857274 | EPI_ISL_897857
EPI_ISL_1340800 | EPI_ISL_1621177 | EPI_ISL_1895857 | EPI_ISL_897904
EPI_ISL_1340805 | EPI_ISL_1628575 | EPI_ISL_2023231 | EPI_ISL_897906
EPI_ISL_1351836 | EPI_ISL_1628615 | EPI_ISL_2080648 | EPI_ISL_897926
EPI_ISL_1352083 | EPI_ISL_1628617 | EPI_ISL_2091417 | EPI_ISL_912961
EPI_ISL_1391533 | EPI_ISL_1628629 | EPI_ISL_2105728 | EPI_ISL_933521
EPI_ISL_1403899 | EPI_ISL_1628667 | EPI_ISL_2105756 | EPI_ISL_965093

</div><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:12pt;">&nbsp;</p></b><br class="Apple-interchange-newline">

**Comment by AngieHinrichs** [comment]
In the UCSC tree, those samples appear distributed throughout the B.1.1.519 branch (mouse over "uploaded sample" in the legend to highlight the example ID):

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-111.json?c=pango_lineage

From the legend you can see that several other lineages are occasionally assigned to sequences on that branch, although the great majority of sequences are assigned B.1.1.519.  I believe assignment of the incorrect lineage is more likely than these being a new subclade.

**Comment by chrisruis** [comment]
Thanks @marorjuelarod for submitting. Based on what @AngieHinrichs shows above, we've now designated these sequences as B.1.1.519 in [v1.2.32](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.32). Thanks again
