### ISSUE TITLE
Sublineages of BA.5.2.20 with S:K444Q, ORF8:W45L (4 seq) & BA.5.6 + S:K444Q, S:E1202Q, M:H125Y (12 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1110]
### **Description #1**
**Sub-lineage of:** BA.5.2.20
**Earliest sequence:** 2022-7-25, Philippines — EPI_ISL_14918878
**Most recent sequence:** 2022-9-7, USA, California — EPI_ISL_15091380
**Countries circulating:** USA (2), Philippines (1)
**Number of Sequences:** 3
**GISAID Query:** Spike_K444Q, NS8_W45L, NSP13_T127N
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2.20* & S:K444Q
**Substitutions on top of BA.5.2.20:**
**Spike:** K444Q (+ F186V in the two USA seq)
**ORF8:** W45L
**Nucleotide:** A22892C, G28027T (plus T12457C & T22118G in two USA seq)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_412e7_f3e350%E2%80%94BA.5.2.20%2BK444Q%2BORF8W45L.json

![image](https://user-images.githubusercontent.com/33738461/192120626-cd838ccb-5d12-48f1-8fff-8ff23f043364.png)

**Evidence**
S:K444Q has emerged in singlets numerous times in the past few months, but these two microlineages are the first to contain multiple sequences. According to the Bloom Lab RBD ACE2 Affinity/RBD Expression Heat Map on a BA.2 background, K444Q has the highest ACE2 affinity and the highest RBD expression (a proxy measure for stability) of any K444 mutation. (I’ve transcribed the values for the change in ACE2 binding and RBD expression for each K444X mutation in the image below.) https://jbloomlab.github.io/SARS-CoV-2-RBD_DMS_Omicron/RBD-heatmaps/

![image](https://user-images.githubusercontent.com/33738461/192120766-0ededae5-bbfd-42a4-929d-3cfc5d266c12.png)

Furthermore, according to the deep mutational scanning (DMS) done by Yunlong Cao, “Imprinted SARS-CoV-2 humoral immunity induces converging Omicron RBD evolution,” K444Q is second only to K444E in evading antibodies from breakthrough BA.2- and BA.5-infection sera. 

![image](https://user-images.githubusercontent.com/33738461/192120959-145daefd-3b5b-4631-a150-58c86ed90ee1.png)

It's of course possible that other factors not accounted for by DMS and laboratory measurements of ACE2 affinity and RBD expression might make K444Q less advantageous in the real world than it appears in experiments, but I think it's a mutation worth monitoring in any case. The S:K444 residue appears to be the most important escape residue against a variety of different polyclonal sera from vaccination, infection, and vaccination + infection. Below is the Bloom Lab RBD Escape Calculator's map of escape mutations for those infected one with pre-Omicron SARS-CoV-2 then by BA.2. 

![image](https://user-images.githubusercontent.com/33738461/192121107-67c9ed4d-0fe3-422d-aa3e-071ac8a63437.png)

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_14918878, EPI_ISL_15002185, EPI_ISL_15091380
</details>

### **Description #2**
**Sub-lineage of:** BA.5.6
**Earliest sequence:** 2022-8-31, USA, New York — EPI_ISL_15015729, EPI_ISL_15065199 (separate patients)
**Most recent sequence:** 2022-9-6, USA, New Jersey — EPI_ISL_15065199
**Countries circulating:** USA (3)
**Number of Sequences:** 3
**GISAID Query:** Spike_K444Q, Spike_E1202Q, M_H125Y
**CovSpectrum Query:** Nextcladepangolineage:BA.5.6* & S:K444Q & M:H125Y
**Substitutions on top of BA.5.6:**
**Spike:** K444Q, E1202Q
**M:** H125Y
**Nucleotide:** C19269T, T21357C, A22892C, G25166C, C26895T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_205f_f41060%E2%80%94BA.5.6%2BK444Q%2BE1202Q%2BMH125Y.json

![image](https://user-images.githubusercontent.com/33738461/192120659-c5097015-73b0-4723-a22d-83121729245d.png)

**Evidence**
See above for evidence on the K444Q mutation. These three sequences also have S:E1202Q, a somewhat convergent S2 mutation, and M:H125Y, which is notable for being identified as one of only two non-spike mutations that occurred more than twice in the patients examined by @ThomasPeacock and Nick Loman in their study of immunocompromised patients who were repeatedly sequenced during chronic infections, “Recurrent SARS-CoV-2 mutations in immunodeficient patients.” https://academic.oup.com/ve/article/8/2/veac050/6661028

![image](https://user-images.githubusercontent.com/33738461/192120705-50d5301c-d0c3-4b80-84a9-0254a5f575d4.png)

M:H125Y frequency was 100-fold higher among patients in their study than in the UK sequences at the time (occurring in 1 in 7 patients in their study compared to 1 in 721 patients in the COG-UK dataset). In fact, M:H125Y was the third most frequent mutation (tied with deletions in the S:138 region) found in this study, behind only S:E484K and E:T30I.  

![image](https://user-images.githubusercontent.com/33738461/192120733-b34a73b3-7f6d-4f23-8db6-29a8e5828b7a.png)

M:H125Y has occurred repeatedly in highly mutated singlets, and was also found in the B.1.1.482, B.1.616, AV.1, B.1.177.72, B.1.1.269 (which had the most M:H125Y sequences with 555), and AY.4.16 variants, but this is the first time, to my knowledge, that it has been detected in multiple patients in any Omicron lineage. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_14914401, EPI_ISL_15015729, EPI_ISL_15065199
</details>

**Comment by FedeGueli** [comment]
4 sequences as today for lineage 1: Spike_K444Q, NS8_W45L, NSP13_T127N

**Comment by ryhisner** [comment]
Yes, and the newest one also has S:F186V and is geographically distant from the other three. It's from Massachusetts (USA), and the other three have been from the Philippines, Texas (USA), and Pennsylvania (USA).

**Comment by ryhisner** [comment]
Three new sequences for the S:K444Q + S:E1202Q + M:H125Y lineage were uploaded today from New York state, making a total of seven sequences now. EPI_ISL_15296998, EPI_ISL_15312328, EPI_ISL_15312346

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/33738461/194954515-04e66488-fcd3-46c7-8591-e49181cdf3cc.png">

**Comment by corneliusroemer** [comment]
@ryhisner please update the numbers in the issue title, as it seems to have increased. I classify this as low priority for now because it's a) small and b) likely less competitive than BQ.1.1 and XBB

**Comment by ryhisner** [comment]
The S:K444Q + S:E1201Q + M:H125Y lineage is now up to 12 sequences, including the first outside of New York (excepting one from neighboring New Jersey): one sequence each from New Hampshire; Washington, DC; and Quebec, Canada. It remains mostly a curiosity but has now at shown some geographical spread and appears to be growing in numbers, if slowly. 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_14914401, EPI_ISL_15015729, EPI_ISL_15065199, EPI_ISL_15222535, EPI_ISL_15296998, EPI_ISL_15312328, EPI_ISL_15312346, EPI_ISL_15324098, EPI_ISL_15351444, EPI_ISL_15393750, EPI_ISL_15409949, EPI_ISL_15410029
</details>

**Comment by corneliusroemer** [comment]
GISAID query just yields 4 for me. Do you have a current Usher tree?
