### ISSUE TITLE
Big sublineage of BA.5.2 Orf1b:1050N with S:K444T (71 sequences) with high prevalence in Guinea.

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1111]
@corneliusroemer i realized that this was never proposed and designated. Probably it was spotted first by @ryhisner but never found its way to become an issue here.

I think it deserves a fast designation to complete the BA.5.2 +Orf1b:1050N tree.

Here a brief proposal for it

Defining mutations:
G12310A > C16616A (Orf1b:T1050N) > A29700G > C1471T > T2698C > A22893C (S:K444T)
![Schermata 2022-09-25 alle 00 33 34](https://user-images.githubusercontent.com/87669813/192120911-13f297b9-b0f4-44b9-ab83-70321c89da2b.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34885_f7dd10.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C1471T

CovSpectrum Query : A29700G + ORF1b:T1050N, S:K444T
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1b%3A1050N%2CS%3A444T&nucMutations=29700G&

71 sequences
Interestingly this sublineage is wel represented in Guinea:
![Schermata 2022-09-25 alle 00 44 25](https://user-images.githubusercontent.com/87669813/192121152-1116166e-402a-4e5e-a533-cf966c7fe11f.png)
Representing 10% of (few) sequences uploaded in the last 6 months and beyond 30% of last week samples.

Using the Gisaid query : NSP13_T127N,Spike_K444T selecting for Africa i can find 11 samples of it

Here  alist of countrie where it is circulating
![Uploading GeographicDistribution (1).png…]()

Here a list of good quality sequences:
[contributors.csv](https://github.com/cov-lineages/pango-designation/files/9639702/contributors.csv)
 from Guinea

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.25 with 25 newly designated sequences, and 0 updated designations. Defining mutation A22893C (S:K444T) (follows C1471T>T2698C).
