### ISSUE TITLE
Sublineage of BA.5 with S:N460S, S:A688V, N:G96S, & four ORF1ab mutations (20 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1112]
**Description**
**Sub-lineage of:** BA.5
**Earliest sequence:** 2022-8-19, USA, Arizona — EPI_ISL_14831827
**Most recent sequence:** 2022-9-6, USA, California — EPI_ISL_15062911
**Countries circulating:** USA (all 21), mainly in California (17) but also bordering states of Arizona (2), Nevada (1), and Washington (1).
**Number of Sequences:** 21
**GISAID Query:** Spike_N460S, Spike_A688V, N_G96S
**CovSpectrum Query:** Nextcladepangolineage:BA.5* & S:N460S & S:A688V & N:G96S
**Substitutions on top of BA.5:**
**Spike:** N460S, A688V
**N:** G96S
**ORF1a:** G298D, E972G, A3705V
**ORF1b:** I2357T
**Nucleotide:** G1158A, A3180G, C5986T, C11379T, T20537C, A22941G, C23625T, G28559A

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_5138_f8c4c0%E2%80%94BA.5%2BN460S%2BA688V%2BNG96S%2B4xORF1ab.json 

![image](https://user-images.githubusercontent.com/33738461/192122308-6cf58e07-6058-4719-94fe-db0f18e9b7db.png)

**Evidence**
This sublineage occurs on a mini-saltation branch with six nucleotide mutations, all of which are nonsynonymous, a hallmark of chronic-infection evolution. (The Nevada sequence that interrupts the saltation branch has no coverage at S:688 and therefore almost certainly contains S:A688V along with all the other mutations on the branch.)

However, the S:N460S mutation is inherited from a much larger branch of BA.5 containing over 500 sequences but which is, bafflingly, not yet designated. @FedeGueli , in issue #731, proposed that this lineage be designated back in June, when it still had only 40 sequences, but the issue was closed. Now that it has grown to more than 500 sequences, I think it deserves to be reopened and designated. 

The smaller lineage I am presenting here probably needs to prove that it has growth potential before deserving a designation. The oldest sequence was collected on August 19, so it seems to have some growth potential, but in the past week, only three sequences has been uploaded. The next week or two should reveal whether this one has legs or not. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_14831827, EPI_ISL_14832907, EPI_ISL_14833914,
EPI_ISL_14852758, EPI_ISL_14867709, EPI_ISL_14898027,
EPI_ISL_14898115, EPI_ISL_14905481, EPI_ISL_14905705,
EPI_ISL_14929360, EPI_ISL_14941697, EPI_ISL_14961073,
EPI_ISL_14963172, EPI_ISL_14963178, EPI_ISL_14987425,
EPI_ISL_15000058, EPI_ISL_15000161, EPI_ISL_15062911,
EPI_ISL_15068032, EPI_ISL_15077514, EPI_ISL_15004659
</details>

**Comment by Mydtlwn** [comment]
#771 Open is XAN, are you sure the number of the question is this？

**Comment by FedeGueli** [comment]
> #771 Open is XAN, are you sure the number of the question is this？

it was #731

**Comment by Mydtlwn** [comment]
The number of the last question provided is correct.    Thx.

**Comment by ryhisner** [comment]
> #771 Open is XAN, are you sure the number of the question is this？

Fixed. Thank you for pointing out this error!
