### ISSUE TITLE
BM.4.1.1 with S:444T (15 seqs, Australia, Austria, US as of 2022-10-10)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1113]
Came across a BA.2.75 that had S:346T, S:486S and S:444T which looks like a combination that could be quite fit.

GISAID query: `Spike_R346T, Spike_F486S,Spike_K444T`

Found 3 sequences that cluster together on 3 continents - so worth monitoring:

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/25161793/192140015-85559d75-9cfb-44aa-9d06-15d47388eac0.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38bf3_f4f710.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22893C

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A346T%2CS%3A444T%2CS%3A486S&nextcladePangoLineage=BA.2.75*&

```
Australia/NSW-ICPMR-32565/2022|EPI_ISL_14789037|2022-08-17
Austria/LB-R00097-S304/2022|EPI_ISL_14841062|2022-08-30
hCoV-19/USA/CA-CDC-LC0881994/2022|EPI_ISL_15103933|2022-09-10
```

**Comment by ryhisner** [comment]
I'e been surprised K444T hasn't been found much in BA.2.75. There were a couple sequences earlier with R346T and K444T (and I think one other additional RBD mutation I can't remember), but it never went anywhere. Maybe this one will catch fire.

**Comment by corneliusroemer** [comment]
A fourth one has been uploaded:
```
hCoV-19/USA/IL-CDC-LC0881226/2022 | EPI_ISL_15102898
```

They all share: ORF1b:Q2425R in addition to S:444T.

**Comment by FedeGueli** [comment]
8 sequences of this one as today

**Comment by corneliusroemer** [comment]
@ryhisner the reason could be that BA.2.75 already has S:446S - making S:444 less beneficial in addition

**Comment by Sinickle** [comment]
13 sequences on CH.1.1.  

With 7 convergent RBD mutations, it won't be surprising if this is one of the fastest growing variants.

**Comment by FedeGueli** [comment]
for CH.1.1  NSP16_Q28R,Spike_K444T,Spike_L452R should work well

**Comment by xiaoxi-wu-tfs** [comment]
May I ask how does the CH.1* pango-lineages got named and how did you decide the initials? Thanks!

**Comment by FedeGueli** [comment]
> May I ask how does the CH.1* pango-lineages got named and how did you decide the initials? Thanks!

Initials are progressive so.it was the first avaible at the time of designation.
The exact moment of designation is once a commit was created for it and you can find in the comments above. In this case was a double designation : CH.1 with S:K444T and its sublineage CH.1.1 with S:L452R
