### ISSUE TITLE
BA.5.3.1 with S:444N and S:460K [8 seqs, as of 2022-09-30]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1114]
Came across a BQ.1 lookalike with potential origin in Bangladesh

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/25161793/192140624-c51321cd-2638-4e1e-8b35-13c5e9a558d0.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37679_f4e560.json?branchLabel=aa%20mutations&c=gt-S_460,444&label=nuc%20mutations:G23608T

It's on a G23608T branch of BA.5.3.1 and has S:444N followed by S:460K

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A444N%2CS%3A460K&nucMutations=G23608T&nextcladePangoLineage=BA.5.3.1*&

**Comment by FedeGueli** [comment]
I think it was already proposed here: 

https://github.com/cov-lineages/pango-designation/issues/1089

**Comment by FedeGueli** [comment]
@corneliusroemer two new sequences of this one from NYC it deserves a fast designation in my view.


EPI_ISL_15106495 


EPI_ISL_15106393 


This lineage has been spotted first by @ryhisner.

**Comment by FedeGueli** [comment]
@carlottaolivero noticed that  there are two different nuc mutations that bring S:N460K , this one has T22942G as BA.2.75 (while BQ.1 has T22942A)

**Comment by corneliusroemer** [comment]
@FedeGueli do you happen to have a GISAID query for this one?

**Comment by FedeGueli** [comment]
Yes NSP5_T45N,Spike_N460K,Spike_K444N @corneliusroemer

**Comment by corneliusroemer** [comment]
2 of the 7 you mention don't cluster with the rest, so we're still at 5

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/25161793/192362454-285e24da-bea1-4f7b-8e65-82ca8334e2e2.png">

**Comment by FedeGueli** [comment]
Thx @corneliusroemer i checked where these two (the french and Nyc ones ) were placed by usher and i find them in a weird part of the tree where BA.5.2 lose 1627T back to C and acquires Orf1a:556K defining of Ba.5.3.
But more interestingly the two sequences have Orf7a:T39I as the lineage S:444N+S:460K proposed in #1121 .

It would be very weird if they acquired all the three mutations independently and convergently

**Comment by corneliusroemer** [comment]
So the 444N/460K cluster has grown to now 8 sequences - 3 from England that don't yet seem to have made it into GISAID

<img width="1635" alt="image" src="https://user-images.githubusercontent.com/25161793/192887317-875372ca-0f84-4a0e-9009-046a84e30c6e.png">

Probably worth designating now. That would be the first 444N/460K.

**Comment by FedeGueli** [comment]
@corneliusroemer maybe i am wrong but probably designating all of them (S:444N+S:460K) would be helpful , they dont seem as fast as  BQ.1 but however  still being several lineages adding one sequence each day with this combo designating will help to track them and reassuring no threat come from them.

**Comment by FedeGueli** [comment]
Gisaid query for this is: N_E136D,NSP5_T45N,Spike_N460K,Spike_K444N finds 7 viruses

**Comment by FedeGueli** [comment]
@corneliusroemer this now should be BE.4

**Comment by FedeGueli** [comment]
Recap:

<google-sheets-html-origin><style type="text/css"></style>

BA.5.3.1+Orf1a:T3308N+460K+444N | N_E136D,NSP5_T45N,Spike_N460K,Spike_K444N | #1121 | 7
-- | -- | -- | --
BA.5.2.24+Orf7a:T39I+S:460K | -NSP2_Q376K,NS7a_T39I,Spike_N460K,Spike_K444N | #1114 | 3
Recomb BE.4/BA.5.2.24 | NSP5_T45N,NS7a_T39I,Spike_N460K,Spike_k444N | #1138 | 4

**Comment by FedeGueli** [comment]
One more sequence of this one from NYC. with the query : N_E136D,NSP5_T45N,Spike_N460K,Spike_K444N i found just 8 sequences of this lineage counting this last one.

**Comment by FedeGueli** [comment]
@corneliusroemer three new sequences of this one from England uploaded today. total count is now 11

**Comment by FedeGueli** [comment]
15 sequences as today with N_E136D,NSP5_T45N,Spike_N460K,Spike_K444N , 4 new sequences from NYC

@corneliusroemer maybe it is worth designating

**Comment by FedeGueli** [comment]
This is now 17 sequences . I noticed that all these 444N +460K have the same speed except for CL.1 that seems faster than the others. I suggest that probably designating them all would be better than choose one by one
