### ISSUE TITLE
BA.5.3.1 with S:346T and S:209L [50 seqs], sublineage with S:444R [10 seqs]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1115]
On the same branch of BA.5.3.1 with G23608T as #1114, there's a lineage with S:346T and S:209L that has a sublineage with S:444R. Again, this seems to be common in Bangladesh.

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/25161793/192140833-9763dc2a-a108-41b5-878e-6244189b42ad.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37679_f4e560.json?branchLabel=aa%20mutations&c=gt-S_346,444

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A346T%2CS%3A209L&nucMutations=G23608T&nextcladePangoLineage=BA.5.3.1*&

**Comment by FedeGueli** [comment]
11 sequences now for the lineaage of interest (346+444) : 
Gisaid :Spike_R346T,Spike_K444R,Spike_P209L

**Comment by FedeGueli** [comment]
12 viruses in the sublineage of interest  (346+444)

**Comment by FedeGueli** [comment]
@corneliusroemer why BE.4.1.1 and not BE.4.1?

**Comment by corneliusroemer** [comment]
The outermost one is BE.4, then with 209 and 346 is BE.4.1, inside with 444R is BE.4.1.1

**Comment by FedeGueli** [comment]
Thx!

**Comment by FedeGueli** [comment]
@corneliusroemer @thomaspeacock @theosanderson @AngieHinrichs 

<img width="1281" alt="Schermata 2022-10-13 alle 11 34 19" src="https://user-images.githubusercontent.com/87669813/195560733-0a35cda8-0048-40f0-8d1a-24d021d5bd03.png">

BE.4.1.1 seems really fast , still small numbers but maybe useful to be flagged, alot of noise in this chart but looking at lineages with consistent numbers BE.4.1.1 is there with highest transmissible lineages

**Comment by Mydtlwn** [comment]
lineage_note，BE.1.4.4

**Comment by FedeGueli** [comment]
@corneliusroemer i think we all missed that between BE.4.1 and BE.4.1.1  S:144 went deleted and so this deletion (S:Y144del) arrived to CQ.2
