### ISSUE TITLE
BA.5.2 + orf1b:T1050N sublineage with S:Y145H - 217 Sequences 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1117]
Here i want to propose a sublineage of BA.5.2+ orf1b:1050N defined by G6943T and S:Y145H
It counts 140 sequences worlwide and it shows a singificant growth advantage globally versus parental BA.5.2 + Orf1b:1050N

Covspectrum Query :BA.5.2 (Nextclade) + G6986G, C8097C, C6730C, T22896T + ORF1b:T1050N, S:Y145H (to distinguish it from other sibling lineages) finds 129 sequences (Here the list of good quality ones:
[contributors (2).csv](https://github.com/cov-lineages/pango-designation/files/9641126/contributors.2.csv) )

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1b%3A1050N%2CS%3A145H&nucMutations=6986G%2CC8097C%2C6730C%2C22896T&nextcladePangoLineage=BA.5.2&aaMutations1=orf1b%3A1050N&nextcladePangoLineage1=ba.5.2*&

Gisaid query NSP13_T127N, Spike_Y145H
finds unluckily more sequences than shown in this Tree by Usher:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3fd8b_6a700.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G6943T
![Schermata 2022-09-25 alle 17 05 09](https://user-images.githubusercontent.com/87669813/192150531-b5c7bddc-b3d2-4e9a-9d8e-cd0bfa6fbc57.png)

As said above  growth advantage versus parental lineage seems solid and steady through the time:
![Schermata 2022-09-25 alle 17 07 24](https://user-images.githubusercontent.com/87669813/192150635-ca30f61f-51ed-4681-b8e8-903453c9ed58.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1b%3A1050N&nextcladePangoLineage=ba.5.2*&aaMutations1=Orf1b%3A1050N%2CS%3A145H&nextcladePangoLineage1=BA.5.2*&analysisMode=CompareToBaseline&

**Comment by corneliusroemer** [comment]
The Usher branch looks unhealthy - too deep, potentially reversions? Where is it geographically concentrated?

**Comment by FedeGueli** [comment]
@corneliusroemer in agree it is not super clear one. I think it has originated in India. Maybe better closing it and see if one of the subbranch acquqires some distinctive mutation with growth advantage. In the wake of the BQ/Ba.2.3.20 wave i dont know if still has sense to designate this kind of lineages,

**Comment by corneliusroemer** [comment]
Oh now I see, a good part of the Usher branch has 145H reverted. So what you propose is "only" around 100 sequences in fact. There's also a little S:445A lineage nearby - probably too small to be worth designating at this point.

**Comment by AngieHinrichs** [comment]
Yes, that particular "unhealthy" branch seems to be pulled together by a run-of-nucleotide mutations on 26339-26341 (I believe run-of-nucleotides is a common pattern for sequencing errors).

**Comment by FedeGueli** [comment]
132 seqs on covspectrum today

**Comment by FedeGueli** [comment]
150 Sequences as today.


@corneliusroemer i noticed a sublineage of this that gained S:K356T:
It counts 5 sequences (3 Usa, 1 Germany , 1 India) 
it is defined by 2713G + S:356T and N:Q409H
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_369c5_dae430.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A2713G,A22629C,A29500C

**Comment by FedeGueli** [comment]
Very hard to track this one i find 190-224 sequences of this one..waiting for.Usher to clarify things a bit

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.37 with 49 newly designated sequences, and 0 updated designations. Defining mutation T21995C (S:Y145H) (following G6943T).

**Comment by InfrPopGen** [comment]
The current usher tree had a sub-clade within this, with sequences with H145Y. The members of this sub-clade all appear to have failed the QC step of the designation, otherwise I would have probably removed them anyway.
