### ISSUE TITLE
BA.5.6 with S:R346T and S:H146Y circulating in England (27 Sequences)

### ISSUE THREAD

**Issue by olias120676** [cov-lineages/pango-designation#1118]
The undesignated BA.5.6 with S:R346T hasn't shown much growth. However a branch with S:H146Y has 27 sequences all in England, first of which appeared on August 26th, suggesting fairly rapid growth

**GISAID query:** Spike_H146Y, nsp1_S34T, Spike_R346T
**Cov-Spectrum query:** S:H146Y, ORF1a:S34T, S:R346T ([link](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AH146Y%2CORF1a%3AS34T%2CS%3AR346T&nextcladePangoLineage=BA.5.6*&))

**USHER tree:**
https://nextstrain.org/fetch/raw.githubusercontent.com/olias120676/jsons/main/2022092601.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T365A,C21998T,G29254T
![ba56](https://user-images.githubusercontent.com/24962257/192176575-00d98483-ef05-4ef1-b07b-4236c21256b1.png)

**Defining mutations on top of BA.5.6:**
S:R346T 
S:H146Y
ORF1a:S34T (nsp1_S34T)
T365A
T15537C

**List of IDs:**
EPI_ISL_14858770
EPI_ISL_14858787
EPI_ISL_14919393
EPI_ISL_14995186
EPI_ISL_15021129
EPI_ISL_15020809

**Comment by FedeGueli** [comment]
Welcome back Dave. i have added this one to collection # 26 on covspectrum to see how it goes and def it goes very well, still quite far behind BQ.1 but the fastest of the unproposed lineages tracked there:https://cov-spectrum.org/collections/26

**Comment by corneliusroemer** [comment]
Looks like the parent without 146Y was more common in Romania - while the child is growing in England.

I'd probably designate the parent too - as S:346T is known to confer a significant growth advantage and we may regret not designating it.

**Comment by Lukas67** [comment]
We found our first sequence of BA.5.6 with S:R346T with Nanopore WGS and submitted to GISAID. 

EPI_ISL_15137796

**Comment by corneliusroemer** [comment]
All the English ones are from one lab so could well be clustered.

Still only 66 BA.5.6 with S:346T and this will likely be outrun by the various novel variants so not of big priority in my view.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A346T&nextcladePangoLineage=BA.5.6*&

**Comment by FedeGueli** [comment]
30 seqs as today

**Comment by corneliusroemer** [comment]
An interesting other tiny lineage with S:445A popped up in the outer one. I'd now designate the outer one with S:346T.

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/25161793/193458454-0ea77aad-0c75-4a9a-8fc0-007c6b1c99b7.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12753_99a5d0.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G22599C

**Comment by FedeGueli** [comment]
Now this grew to 47 with Spike_H146Y, nsp1_S34T, Spike_R346T , i think it is worth designating it @InfrPopGen

**Comment by corneliusroemer** [comment]
I would designate the outer one with 346T still, not the inner one (yet)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.6.3 with 11 newly designated sequences, and 0 updated designations. Defining mutation G22599C (S:R346T) (following G18984T (ORF1b:M1839I)). This is the parent of the lineage proposed here. Designation of the child lineage may follow, possibly after it has grown a little more.
