### ISSUE TITLE
XAW sublineage with S:D215Y (19 seq. Russia as of 2022-10-17)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1119]
Proposal for a sublineage of XAW
Earliest sequence: 28.07.2022 (Russia)
Countries detected: Russia (17)

Defining mutation:
G22205T = S:D215Y
A18585G

GISAID: NSP1_E102K, N_G97S, NS3_K67R, Spike_D215Y

This sublineage of XAW is defined by S:D215Y and was only detected in Russia so far. Acquisition of S:D215Y may hints at circulation (see also S:G252V in XBB (#1088) or S:L452M in XBC ( #1100)).

![grafik](https://user-images.githubusercontent.com/102166254/192216230-bdfb63f2-c969-41ec-94dd-bdd9a99ed525.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24435_145dc0.json?branchLabel=aa%20mutations&c=gt-S_215
![grafik](https://user-images.githubusercontent.com/102166254/192214805-96c45e65-b6f0-41b4-ad1b-c93e40f4c602.png)

EPI_ISL_14937854
EPI_ISL_14937873
EPI_ISL_14921426
EPI_ISL_14921425
EPI_ISL_15084871
EPI_ISL_15084868
EPI_ISL_14901371
EPI_ISL_14901335
EPI_ISL_14901374
EPI_ISL_14901367
EPI_ISL_14937708
EPI_ISL_14901337
EPI_ISL_15105298
EPI_ISL_15105281
EPI_ISL_15105299
EPI_ISL_15105284
EPI_ISL_15105293

**Comment by Mydtlwn** [comment]
Are there any other strains?

**Comment by corneliusroemer** [comment]
it's 19 now

**Comment by agamedilab** [comment]
its still 19. I close this for the time being.
