### ISSUE TITLE
BA.5.2.24 with S:N460K (T22942A) and Orf7a:T39I - 100 sequences (Austria, Greece, England, Singapore,Germany,Australia,Spain, Usa, Switzerland , Canada)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1121]
From #1089 here i want to propose the second of apparent sublineages of BA.5.2.24 which have acquired S:N460K

This potential sublineage has been already sampled in three different countries: Austria (EPI_ISL_15109578), England (PHEC-YYG56SA/2022) Greece (EPI_ISL_15110912)

it is defined by an Orf7a:T39I mutation that comes just before the S:N460K ( interestingly this AA substitution comes from T22942A as BQ.1*)
covspectrum query : BA.5.2* (Nextclade) + T22942A + S:K444N, ORF7a:T39I
catches zero sequences being all very recent ones
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A444N%2COrf7a%3AT39I&nucMutations=T22942A&nextcladePangoLineage=BA.5.2*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

**Edited**

Gisaid query  -NSP2_Q376K,NS7a_T39I,Spike_N460K,Spike_K444N  finds all the three sequences 

Here the tree as requested by @corneliusroemer : 
![Schermata 2022-09-26 alle 23 21 54](https://user-images.githubusercontent.com/87669813/192382955-55a3d418-4aab-40cd-b8b7-bfdc3b9d2739.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14417_1ac6e0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C27509T

Note that it is very close to the other  BA.5.2.24 + S:460K that there is instead T22942G
![Schermata 2022-09-26 alle 23 22 52](https://user-images.githubusercontent.com/87669813/192383116-0212c454-1a66-4305-91f7-8de28a9ddaea.png)

**Comment by corneliusroemer** [comment]
Do you have an Usher link for this one?

Is BA.5.2.24 defined as having S:K444N already?

**Comment by FedeGueli** [comment]
yes BA.5.2.24 has S:444N as defining.

wait i upload the tree in a minute

**Comment by FedeGueli** [comment]
one more sample of this one, a local case in Singapore.EPI_ISL_15209081

**Comment by FedeGueli** [comment]
6 sequences as today one more from England and one from Germany.

**Comment by corneliusroemer** [comment]
Bit slow growth, wouldn't designate at this point

**Comment by FedeGueli** [comment]
7 viruses as today last one from Singapore - local case

**Comment by corneliusroemer** [comment]
Very slow growth if it's still only 7 sequences up from 3 19 days ago, i'll close for now

**Comment by FedeGueli** [comment]
Apparently it is 16 now

**Comment by FedeGueli** [comment]
-NSP2_Q376K,NS7a_T39I,Spike_N460K,Spike_K444N finds now 16 sequences the last uploaded is from Canada.


@corneliusroemer my suggestion is to designate this one too so we have every BA.5.2.24 + 460K designated. 

Remember this one has T22942A and not T22942G as CK.1 /CK.2.1*

**Comment by corneliusroemer** [comment]
There isn't much evidence that this is not a CK.1 - with extra ORF7a:T39I

This one USA/TX sequence could well be dropout. So I've added this to CK.1

We can split it out if we get strong evidence that there are in fact ORF7a:T39I without S:N460K circulating.

But unless we have that I think we should just consider this a CK.1 and be happy :)

**Comment by FedeGueli** [comment]
> There isn't much evidence that this is not a CK.1 - with extra ORF7a:T39I
> 
> This one USA/TX sequence could well be dropout. So I've added this to CK.1
> 
> We can split it out if we get strong evidence that there are in fact ORF7a:T39I without S:N460K circulating.
> 
> But unless we have that I think we should just consider this a CK.1 and be happy :)

No Cornelius this has T22942A for S:N460K (as BQ.1 and XAW) while Ck.1 and Ck.2.1.1s have T22942G as XBB and BA.2.75s. So they are Unrelated .

@corneliusroemer

**Comment by FedeGueli** [comment]
As today i find 54 viruses on Gisaid with  -NSP2_Q376K,NS7a_T39I,Spike_N460K,Spike_K444N

Nextclading them i can confirm they are all from this lineage. 

here the Usher tree that confirms this is monophyletic: 
<img width="1162" alt="Schermata 2022-11-05 alle 19 24 01" src="https://user-images.githubusercontent.com/87669813/200135233-55bbc635-b59d-4eef-8a49-cfd57a426241.png">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_7513_6a9f20.json?c=pango_lineage_usher&label=nuc%20mutations:C27509T

And this is distinct  from every other BA.5.2.24 cause it has T22942A for S:N460K while the others have T22942G: 
<img width="790" alt="Schermata 2022-11-05 alle 19 27 22" src="https://user-images.githubusercontent.com/87669813/200135354-aaa19771-039e-4fbe-83f4-a5fbb3cdca99.png">
(on the top part of the tree is the CK.2 lineage while in the bootom part of the tree we can see CK.1, in the middle the lineage proposed here).

CC @InfrPopGen @corneliusroemer @AngieHinrichs @thomaspeacock i ask you to designate this for its relevance.

**Comment by FedeGueli** [comment]
77 sequences growing very fast @AngieHinrichs @thomaspeacock @corneliusroemer @InfrPopGen please reopen and designate this one

**Comment by corneliusroemer** [comment]
This is probably just CK.1 where one sample has dropout. There's not enough evidence that this is homoplasic.

**Comment by FedeGueli** [comment]
@corneliusroemer yeah and it was wrong 19days ago and  it is wrong now:. it has a different nuc mutation for N460K

**Comment by FedeGueli** [comment]
Evidences (already posted above)
![Screenshot_2022-11-09-11-50-42-142_com android chrome](https://user-images.githubusercontent.com/87669813/200811250-7bf73b79-e028-4a5e-8530-92da15e5d149.jpg)

**Comment by FedeGueli** [comment]
100 seqsas today newly found in Switzerland and Canada doubling time for date of submission is around 7-10days.

@corneliusroemer @InfrPopGen by the fact it is growing and reaching more and more countries i think it deserves a designation

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage CK.3 with 76 newly designated sequences, and 15 updated designations from CK.1. Defining mutations T22942A (S:N460K) (following C27509T (ORF7a:T39I)).

**Comment by FedeGueli** [comment]
Thx @InfrPopGen and @corneliusroemer for taking your time to listen to my thoughts on this one.
