### ISSUE TITLE
BA.5.2.20 sublineage with S:K444N (29 sequences) with a small cluster with S:N460K (T22942A) -3 seqs

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1123]
Here i want to propose a sublineage of the recently designated BA.5.2.20 lineage (that has Orf1b:1050N).

It is defined by S:K444N mutation, it stems out directly after the BA.5.2.20 defining NUC :C23707T .

it counts 29 sequences as today from 11 countries and 5 continents
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice7_genome_14417_1ac6e0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G22894T

Covspectrum query: BA.5.2* (Nextclade) + G12310A, C23707T, C14649C, C11704C + S:K444N
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AK444N&nucMutations=G12310A%2CC23707T%2C14649C%2C11704C&nextcladePangoLineage=BA.5.2*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Sequence list:
[contributors.csv](https://github.com/cov-lineages/pango-designation/files/9647326/contributors.csv)

a little branch with 3 sequences have acquired S:N460K (T22942A) , N:S327L, Orf1a;:K669N
<img width="1139" alt="Schermata 2022-09-26 alle 16 55 58" src="https://user-images.githubusercontent.com/87669813/192310248-2a509a7f-9db5-4718-b7f8-94d74f995a09.png">
Gisaid query for this last little cluster: Spike_N460K, N_S327L,Spike_K444N

**Comment by jknappen** [comment]
Looks the same as #1122

**Comment by FedeGueli** [comment]
thx connection issues made this happening
