### ISSUE TITLE
BL.1 sublineage with S:490L, Switzerland, Canada, Germany [7 seqs]

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1124]
**Description**
Sub-lineage of: BL.1
Earliest sequence: 2022-8-25, Switzerland — EPI_ISL_15036254
Most recent sequence: 2022-9-9, Canada — EPI_ISL_15054432
Countries circulating: Switzerland, 4. Canada, 1.
Number of Sequences: 5
GISAID Query: Spike_R346T, Spike_F490L, Spike_D574V
CovSpectrum Query: Nextcladepangolineage:BA.2.75* & S:346T & S:574v & S:490L
Substitutions on top of BL.1
Spike: F490L
ORF1b: P2612L, R2613N
Nucleotide: C21302T,G21305A,C21304A,T29867A,T23030C

**USHER Tree**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_daf3_1bd4e0.json?label=nuc%20mutations:G22599C

![image](https://user-images.githubusercontent.com/94097102/192313431-be6295c5-7851-406d-aca4-2db9e920279d.png)

**Evidence**
We already have designated a couple sublineages of BA.2.75 with an S:490S mutation (BN.1, BM.1.1). Although S:490S is the most common S:490 mutation in BA.2.75*, it appears that the site is under selection pressure in general, and there are also some sequences with S:490V and S:490L. 
This will possibly add additional advantage to BL.1, which is a fairly fit and large lineage already.  
I'd like to call attention to the peculiar ORF1b mutations, at position 2612,2613. These appear to have happened prior to the S:490L mutation. I haven't looked into this too closely, but it seems this pair of mutations has happened on many Omicron lineages, and more than 3000 sequences in the last 6 months. 

Genomes:EPI_ISL_15036254, EPI_ISL_15036087, EPI_ISL_15036334, EPI_ISL_15063485, EPI_ISL_15054432

**Comment by FedeGueli** [comment]
One more sequence from Germany uploaded today @Sinickle . Tot is 6 now

**Comment by shay671** [comment]
So this has been designated? @corneliusroemer  is it accepted?

**Comment by jknappen** [comment]
> So this has been designated? @corneliusroemer is it accepted?

Yes, it is BL.1.3 (click on the hex number and than open the first diff to see it)

**Comment by ryhisner** [comment]
@Sinickle, the ORF1b:R2613N mutation creates the sgmRNA AAACGAAC pattern noted by @theosanderson and @ThomasPeacock in their paper "Emergence of new subgenomic mRNAs in SARS-CoV-2." The ORF1b:P2612L I believe increases the homology of the nucleotides on either side of the AAACGAAC. I frankly don't understand how this works except that somehow, if the nucleotides on each side mirror each other, the sgmRNA works better. 
https://www.biorxiv.org/content/10.1101/2022.04.20.488895v1
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/33738461/193436254-5fc54177-1eff-48b2-b435-830f40bf58cc.png">

**Comment by shay671** [comment]
Hi @ryhisner , Those 3 nucsubs appear in a lot of variants 

![image](https://user-images.githubusercontent.com/80166370/195179811-3f659207-88c4-4930-bc87-178439f22cb0.png)

and also specifically in BA.2.75 
![image](https://user-images.githubusercontent.com/80166370/195180386-771baf87-f2f6-41b5-be4a-2d8208035348.png)


It might be that this is Ultra converging mutations go all together each time. Or this is some technical problem. 

@AngieHinrichs, what do you think ?
