### ISSUE TITLE
Third sublineage of  BA.5.2.24 + S:460K in the branch with E:V62F (8 sequences) circualting in Usa

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1125]
From #1089  i want to propose the third BA.5.2.24 + S:460K sublineage.

This likely emerged in Pakistan from a branch of BA.5.2.24 defined by E:V62F that has been spotted independently by @ryhisner and me, maybe it is worth a designation on its own if the S:N460K sub branch will go on growing:
![Schermata 2022-09-26 alle 23 26 56](https://user-images.githubusercontent.com/87669813/192383710-6917bdb2-4929-44a1-99cf-d3a0a6ca32bf.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14417_1ac6e0.json?branchLabel=aa%20mutations&c=gt-ORF7a_39&label=nuc%20mutations:G26428T

Defining mutations :  E:V62F then C25710T+ S:N460K (T22942G) + Orf1a:T4159I

Gisaid Query: E_V62F,Spike_K444N,Spike_N460K

CovSpectrum Query: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1a%3AT4159I%2CE%3AV62F&nucMutations=C25710T%2CT22942G&

Sequences: EPI_ISL_14899131
EPI_ISL_15029007

**Comment by corneliusroemer** [comment]
Very small but it's the well known 444/460 combination so worth monitoring. Thanks Fede.

**Comment by FedeGueli** [comment]
5 sequences as today

to be noticed that there is an independent sequence from denmark with S:460K and E:64F which shows two more Spike mutations  (Spike_N460K,E_V62F,Spike_T250I,Spike_S255F,Spike_K444N)

**Comment by FedeGueli** [comment]
6 sequences as today with: -Spike_S255F,E_V62F,Spike_K444N,Spike_N460K

**Comment by FedeGueli** [comment]
Big Upload from Pakistan today. It now counts 17 sequences.

**Comment by FedeGueli** [comment]
10 sequences as today https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a08d_d4b170.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G26428T
<img width="1150" alt="Schermata 2022-10-17 alle 16 05 32" src="https://user-images.githubusercontent.com/87669813/196198381-79382efd-8109-4a3e-938b-3fbab8e13d93.png">

**Comment by FedeGueli** [comment]
This has been designated CK.2.1 starting with E_V62F, Spike_N460K a step outer in respect of this proposal.

@thomasppeacock @corneliusroemer @InfrPopGen  please add the milestone so it will be easily found then.
