### ISSUE TITLE
New BA.5.2 + Orf1b:T1050N sublineage with S:K444M and Orf1a:S1520F (81 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1126]
Here i want one more sublineage with S:K444M stemming out of BA.5.2+ Orf1b:1050N  

Defining mutations from BA.5.2:
 G12310A > C16616A > C25714G > C24133T > C27143T > C4824T (orf1a:S1520F) > A22893T  (S:K444M)

tree:
![Schermata 2022-09-27 alle 13 27 11](https://user-images.githubusercontent.com/87669813/192513503-0a250197-315c-4ae0-a4db-cf9797ab9bbe.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24635_2dcb50.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C4824T

Gisaid query :Spike_K444M,NSP3_S702F finds 71 viruses

CovSpectrum query: Orf1a:S1520F+S:444M +Orf1b:1050N 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1a%3AS1520F&nucMutations=C16616A%2CA22893T&

List of good quality sequences:
[contributors.csv](https://github.com/cov-lineages/pango-designation/files/9654965/contributors.csv)

Countries: Poland , Denmark
![GeographicDistribution](https://user-images.githubusercontent.com/87669813/192514788-e26b6cfd-e274-4784-ba37-bbd0215990fe.png)

**Comment by corneliusroemer** [comment]
This is the biggest undesignated BA.5.2 + S:444M so why not

**Comment by FedeGueli** [comment]
79 viruses as today

**Comment by FedeGueli** [comment]
81 viruses as today

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage CG.1 with 33 newly designated sequences, and 4 updated designations from BA.5.2.26. Defining mutation A22893T (S:K444M) (following C4824T).

**Comment by FedeGueli** [comment]
Thx @InfrPopGen !
