### ISSUE TITLE
BA.5.2.20 sublineage with S:Y248H circulating in England (11seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1127]
Here i want to propose a BA.5.2.20 sublineage with S:Y248H 
Defining mutations: T22304C (S:Y248H)

tree:
<img width="1146" alt="Schermata 2022-09-27 alle 17 01 00" src="https://user-images.githubusercontent.com/87669813/192562655-db8199bb-ab08-4eb2-9b6e-3ac2d5839a10.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_6c42_2fc190.json?branchLabel=aa%20mutations&label=nuc%20mutations:T22304C

Countries : Uk, NZL

11 Sequences:
EPI_ISL_14494006 
EPI_ISL_14632957
EPI_ISL_14838860 
EPI_ISL_14919795
EPI_ISL_13711731
EPI_ISL_13711736
EPI_ISL_13711856
EPI_ISL_13711859
EPI_ISL_13711872
EPI_ISL_13711958
EPI_ISL_13712107

**Comment by corneliusroemer** [comment]
Old (beginning of July) and small (11 sequences) - I'll close for now.

**Comment by FedeGueli** [comment]
yeah i was tracking S:Y248H and missproposed this one so this is totally irrelevant. thx @corneliusroemer
