### ISSUE TITLE
Sublineage of BA.2.3.20 with S:N17S (24 seq, Sept 29)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1129]
**Description**
**Sub-lineage of:** BA.2.3.20
**Earliest sequence:** 2022-
**Most recent sequence:** 2022-
**Countries circulating:** 
**Number of Sequences:** 19
**GISAID Query:** Spike_E484R, Spike_N17S
**CovSpectrum Query:** Nextcladepangolineage:BA.2.3.20* & S:N17S
**Substitutions on top of BA.2.3.20:**
**Spike:** N17S
**Nucleotide:** A21612G, T22312C (one sequences lacks the latter)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_2e18e_384090-BA.2.3.20%2BN17S.json

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/33738461/192665156-79ae445b-c7da-437f-95cc-ad82c2a45c8d.png">

The nucleotide changes in the red boxes are involved in subgenomic RNA patterns. The top two create the extended homology pattern for the N:203-204 sgmRNA pattern noted by @theosanderson and @ThomasPeacock in their preprint “Emergence of new subgenomic mRNAs in SARS-CoV-2.” The figure below is from that paper. The nucleotide in the red box on the bottom branch is involved in the ORF1b sgmRNA noted in the same paper. https://www.biorxiv.org/content/10.1101/2022.04.20.488895v1 

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/33738461/192665103-b5bf62a0-4ae3-4eec-8f36-6c1a3342c178.png">

Of the approximately 115 full-length BA.2.3.20 sequences detected so far 19 have had S:N17S, an uncommon spike mutation at a residue where a glycan is normally attached, as described by Veesler & colleagues in their study “"N-terminal domain antigenic mapping reveals a site of vulnerability for SARS-CoV-2," published in Cell.  https://www.cell.com/cell/fulltext/S0092-8674(21)00356-1

![image](https://user-images.githubusercontent.com/33738461/192665032-69ab8ed9-14f5-4987-abfb-bc8c4ff95e69.png)
![image](https://user-images.githubusercontent.com/33738461/192665046-e4913b28-f5d8-4afa-8774-aea3b42aa811.png)

I do not know what the expected consequences of this mutation would be. Before BA.2.3.20, it was most notable for being in over 2000 B.1.1.7 sequences in Sweden during their spring 2021 Alpha wave. At its peak in early March, B.1.1.7 + S:N17S made up just over 5% of all sequences in Sweden. Determining whether or not S:N17S conferred a growth advantage or disadvantage in Sweden during this time is impossible due to the bizarre sequencing patterns in different regions of Sweden during this time. The region of Halland—where ~40% of all cases in early March were B.1.1.7 + S:N17S—seems to have almost completely stopped sequencing on March 11. Many other regions, like Vastra Gotaland have a similar pattern. I suppose this was part of Sweden’s….peculiar pandemic strategy. Skane is the only region that continued to sequence at a high level through the end of April, and there N17S appeared to grow as a percentage of B.1.1.7, but large confidence intervals make conclusions impossible.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_14727166, EPI_ISL_14916422, EPI_ISL_14994934, EPI_ISL_15031205, EPI_ISL_15031883, EPI_ISL_15031894, EPI_ISL_15054932, EPI_ISL_15057098, EPI_ISL_15072209, EPI_ISL_15072211, EPI_ISL_15072231, EPI_ISL_15072257, EPI_ISL_15072259, EPI_ISL_15072262, EPI_ISL_15109199, EPI_ISL_15115459, EPI_ISL_15121657, EPI_ISL_15121660, EPI_ISL_15121660, EPI_ISL_15121660
</details>

**Comment by FedeGueli** [comment]
i found 21 with Spike_E484R, Spike_N17S ( pulling out the three from bats!)

**Comment by ryhisner** [comment]
One of those 21 is a spike-only sequence and therefore doesn't count. Maybe the other one was from before BA.2.3.20 came into existence? I tried to limit the time period to collection dates after August 8.

**Comment by FedeGueli** [comment]
@ryhisner no no they are plain BA.2.3.20 , and the spike only too ( i dont understand what you mean for "it doesnt count" So they are 21 now.

**Comment by FedeGueli** [comment]
<img width="548" alt="Schermata 2022-09-28 alle 17 19 01" src="https://user-images.githubusercontent.com/87669813/192818519-269dce94-5f06-46f9-a200-189792af3022.png">

**Comment by ryhisner** [comment]
I said "it doesn't count" because I thought I remembered seeing @corneliusroemer say in another issue that spike-only sequences cannot be counted for designation purposes.

**Comment by corneliusroemer** [comment]
Oh I don't think I made such a rule - but Spike only definitely cannot be designated. They are still useful to see patterns of what is growing and what isn't.

I'd say let's wait and see what the impact of this is as it's not in the RBD. But definitely interesting diversity!

**Comment by oobb45729** [comment]
The glycan at N17 is already gone due to T19I.

**Comment by ryhisner** [comment]
> The glycan at N17 is already gone due to T19I.

@oobb45729, can you point me to any papers that discuss T19I, the N17 glycan, or mutation-caused glycan changes in general? I've only come across the topic of glycans when they are mentioned incidentally in studies on antibodies and such.

**Comment by oobb45729** [comment]
The basic rule is that the N-glycan can occur at the N of ---NXT--- or ---NXS--- (X is not P).
