### ISSUE TITLE
XBC with S:L452M, ORF1a:S391F (6 seq. Philippines, USA, South Korea)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1130]
Proposal for a sublineage of XBC
Earliest sequence: 22.08.2022 (Philippines)
Countries detected: Philippines (2), USA (2), South Korea (2),

Apparently there is already a emerging sublineage of XBC with S:L452M (as noted in  #1100, #1119) which is probably worth designating. Expansion into South Korea with todays upload. XBC now has 11 genomes on GISAID with 6 of them carrying S:L452M (as of 28.09.22). Both sublineages (with and without S:L452M) are widespread occuring at 2 (Philippines, USA, South Korea) and 3 continents (Philippines, Austria, South Korea), respectively.  

Defining mutation:
C22916A = S:L452M
C1437T = ORF1a:S391F

Provisorial GISAID query: Spike_N703I, Spike_P25S, Spike_L452M

![grafik](https://user-images.githubusercontent.com/102166254/192708034-2cd31b5a-ffa2-4a77-8966-834a905b9111.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_309d4_3e67c0.json?branchLabel=aa%20mutations&c=gt-S_452&label=nuc%20mutations:C4893T,C5184T,A5584G,C6196T,G6576T,G7091A,C9073T,C9891T,A10449C,T11418C,C11514T,C13019T,T15030C,C15237T,C16616T,T19220C,C21618T,C21635T,T21846C,C22188T,T22197C,G22205C,C22227T,A22578G,G22898A,T23018C,T23019C,G23040A,A23670T,C25854T,T26819C,T27718C,C27752T,T27807C,G27890T,A27898C,T28311C,A28461G,A28881T,A28882G,C28883G,G29402T

EPI_ISL_15057246-15057247, EPI_ISL_15102716, EPI_ISL_15103168,
EPI_ISL_15146639, EPI_ISL_15146923

**Comment by corneliusroemer** [comment]
Let's wait until the dust settles a bit. For example we have S:S256L appearing twice which indicates that some of the sequences have artifactual reversions.

**Comment by corneliusroemer** [comment]
One more sequence from Singapore today
hCoV-19/Singapore/12437/2022

**Comment by agamedilab** [comment]
I would be very happy if a designate label & milestone could be added to the issue. many thanks! @corneliusroemer @InfrPopGen

**Comment by shay671** [comment]
What about C10029T, isn't it part of this ?
@agamedilab
