### ISSUE TITLE
BA.5.1 (200k seqs) diversity to break it up into smaller chunks

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1131]
BA.5.1 is one of the biggest unbroken lineages - it may be worth breaking it up where possible to make it easier to quickly spot if BA.5.1 lineages are monophyletic or not - e.g. there are quite a few BA.5.1 with S:346T but there are likely a few independent lineages.

The biggest clusters (>10k sequences) with non-synonymous mutations in BA.5.1 seem to be:
- [ ] BA.5.1 + ORF1a:S302F (mostly Spain, where it reached almost 10%)
- [ ] BA.5.1 + ORF1b:S1273L (France, Germany, western Europe)
- [ ] ~BA.5.1 + ORF6:D6G (reached 5% in Sweden)~

Similar exercises could be worthwhile for the other big BA.5* like BA.5.2, BA.5.2.1

**Comment by corneliusroemer** [comment]
Problem with `BA.5.1 + ORF6:D6G`: this lineage already has a designated sublineage BA.5.1.9 :/

https://github.com/cov-lineages/pango-designation/issues/786

It got defined with C5221T which reduces the size from 10k to 1k. We should maybe be more careful about designating small lineages and go for the bigger ones instead - if possible. Opt more often for the 5% lineage instead of the 0.5% one.

I think @FedeGueli originally proposed the bigger one but it ended up being the small one.

**Comment by FedeGueli** [comment]
Agree Cornelius , i  prefer very much to propose big branches first then wait and if something fast happens to emerge propose it but sometimes the perceived thing from proposer point of view is that big lineages are not designated .For sure i can tell you the ba.5.2.1 + 0rf6:P57L was one to be designated as the S:1020S as a whole or the Orf1b:1050N as a whole. Looking at the unproposed ones  for certain there is a big BE.1 sublineage with Orf3a:K21N .

**Comment by agamedilab** [comment]
> Agree Cornelius , i prefer very much to propose big branches first then wait and if something fast happens to emerge propose it but sometimes the perceived thing from proposer point of view is that big lineages are not designated .For sure i can tell you the ba.5.2.1 + 0rf6:P57L was one to be designated as the S:1020S as a whole or the Orf1b:1050N as a whole. Looking at the unproposed ones for certain there is a big BE.1 sublineage with Orf3a:K21N .

I agree with @FedeGueli here. Big branches apparently tend to get shut down for not having an "epidemiological event of significance" even though there are already big and widespread. This sometimes seems to be born out of the desire to "clean things up". Smaller lineages however when proposed at the right time (e.g. when concurrently detected in a new area) get designated apparently more easily. I think the distribution/relation of parent and sublineages is corollary of the criteria for designation and how they are applied.
