### ISSUE TITLE
BF.7 sublineage with S:G261V (55 seq., 10 countries, Europe)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1132]
Proposal for a sublineage of BF.7
Earliest sequence: 22.08.2022 (Israel)
Countries detected: mostly Germany (39), Austria, Belgium, Denmark, Estonia, France, Israel, Netherlands, Spain, Sweden

Defining mutation:
G22344t = S:G261V

This sublineage of BF.7 was first detected in Israel and is now present in mostly in Germany and several other European countries.

![grafik](https://user-images.githubusercontent.com/102166254/192801327-cf79b244-2ca5-48b9-96bc-8ea8f61af8d7.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2aacb_453410.json?branchLabel=aa%20mutations&c=gt-S_261&label=nuc%20mutations:G22344T

EPI_ISL_13777120, EPI_ISL_14408644, EPI_ISL_14521126, EPI_ISL_14521113, EPI_ISL_14926618, EPI_ISL_14934012, EPI_ISL_14595943, EPI_ISL_14595962, EPI_ISL_14698912, EPI_ISL_14709650, EPI_ISL_14666212, EPI_ISL_14697999, EPI_ISL_14697155, EPI_ISL_14698186, EPI_ISL_14697979, EPI_ISL_14922578, EPI_ISL_14887538, EPI_ISL_14887793, EPI_ISL_14697783, EPI_ISL_14924378, EPI_ISL_14924390, EPI_ISL_14977637, EPI_ISL_14870594, EPI_ISL_14979701, EPI_ISL_14977764, EPI_ISL_15022384, EPI_ISL_15109905, EPI_ISL_14996096, EPI_ISL_15109451, EPI_ISL_15135904, EPI_ISL_15128422, EPI_ISL_15154514, EPI_ISL_15147835, EPI_ISL_15136398, EPI_ISL_15135615, EPI_ISL_15134283, EPI_ISL_15130716, EPI_ISL_15130244, EPI_ISL_15130195, EPI_ISL_15137607, EPI_ISL_15147520, EPI_ISL_15150017, EPI_ISL_15151231, EPI_ISL_15150549, EPI_ISL_15149070, EPI_ISL_15137253, EPI_ISL_15137164, EPI_ISL_15135982, EPI_ISL_15128216, EPI_ISL_15150676, EPI_ISL_15151173, EPI_ISL_15129586, EPI_ISL_15132440, EPI_ISL_15134375, EPI_ISL_15147147

**Comment by corneliusroemer** [comment]
What other mutations are there in addition to S:261V, do any of the intermediate nodes deserve a name? Not that we end up with the usual problem that we have dozens of sublineages but the parent still makes up >80%.

**Comment by corneliusroemer** [comment]
Alright, I think this is worth designating as it does seem to grow a bit faster than BF.7 itself

It's borderline small but just ok.

<img width="1585" alt="image" src="https://user-images.githubusercontent.com/25161793/193151504-d26e2e92-90ee-4929-b8f0-8ca99359ed56.png">

**Comment by Mydtlwn** [comment]
Other dominant mutant strains of BF.7 need to be designated as soon as possible.
