### ISSUE TITLE
Collection of large, currently undesignated BA.5.2.1 diversity

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1134]
Big lineages that could help reduce the monolithic block of BA.5.2.1:
- [x] #1142
- [x] #1140
- [x] #1141

**Comment by alurqu** [comment]
Parallel to [my comment](https://github.com/cov-lineages/pango-designation/issues/1135#issuecomment-1261549274l) on the BA.5.1 diversity ticket, https://cov-spectrum.org/collections/43 sorted by number of sequences might be helpful for identifying large pieces of the BA.5.2.1 undesignated diversity.
