### ISSUE TITLE
BA.2.75.2 Sub-lineage with  N:M101I mutation - (93 Sequences; 14 Countries from 4 Continents)

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#1136]
Proposal for a new BA.2.75.2 Sub-lineage with  N:M101I mutation 

Earliest Sample Collection Date: 08/2022 (Karnataka, India - Date error)
Latest Sample Collection Date: 09/18/2022 (Massachusetts, USA) 
Total Sequences: 47  (as of 9/29/22)

Defining Mutation: N:M101I (G28576C)
Other mutations: Spike R346T, F486S, D1199N, N460K

Nextstrain Tree:
![image](https://user-images.githubusercontent.com/98380390/192945161-99efe6cc-31ff-412e-bcd7-da0954e364e2.png)

CoV-Spectrum Growth Advantage vs parent lineage 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=BA.2.75.2*&aaMutations1=N%3AM101I&nextcladePangoLineage1=BA.2.75.2*&analysisMode=CompareToBaseline&

GISAID IDs: 
EPI_ISL_14587018
EPI_ISL_14724115
EPI_ISL_14724257
EPI_ISL_14724370
EPI_ISL_14915750
EPI_ISL_14915826
EPI_ISL_15074224
EPI_ISL_14640047
EPI_ISL_14533621
EPI_ISL_15050816
EPI_ISL_15050830
EPI_ISL_14649954
EPI_ISL_14904841
EPI_ISL_15074129
EPI_ISL_14785674
EPI_ISL_14989086
EPI_ISL_14975618
EPI_ISL_15111519
EPI_ISL_14890605
EPI_ISL_15043097
EPI_ISL_15146849
EPI_ISL_14993512
EPI_ISL_15043408
EPI_ISL_15078497
EPI_ISL_14917659
EPI_ISL_14948268
EPI_ISL_15036250
EPI_ISL_15036251
EPI_ISL_15036348
EPI_ISL_15031923
EPI_ISL_15036245
EPI_ISL_15103354
EPI_ISL_15110141
EPI_ISL_15031915
EPI_ISL_15031973
EPI_ISL_15081830
EPI_ISL_15110149
EPI_ISL_15119884
EPI_ISL_15146875
EPI_ISL_15162197
EPI_ISL_15057650
EPI_ISL_15153536
EPI_ISL_15153620
EPI_ISL_15153623
EPI_ISL_15160176
EPI_ISL_15145352

**Comment by RajLABN** [comment]
6 more BA.2.75.2* + N:M101I (GISAID IDs: EPI_ISL_15170649, EPI_ISL_15170678, EPI_ISL_15170680,
EPI_ISL_15170688, EPI_ISL_15170696, EPI_ISL_15173085)
- 5 from England and 1 from Israel)

**Comment by RajLABN** [comment]
2 more BA.2.75.2* + N:M101I (GISAID IDs: EPI_ISL_15192907, EPI_ISL_15196069)  - from New York USA and Queensland, Australia.

**Comment by RajLABN** [comment]
![nextstrain_fetch_genome ucsc edu_trash_ct_subtreeAuspice1_genome_55fb_b5d9e0 json](https://user-images.githubusercontent.com/98380390/193695284-82ea1673-d583-4234-a61b-055e30b513d7.svg)

![image](https://user-images.githubusercontent.com/98380390/193693795-11637efb-a3e8-4026-8db7-2a985fc003fb.png)

**Comment by RajLABN** [comment]
More BA.2.75.2* + N:M101I [EPI_ISL_15255559, EPI_ISL_15250317, EPI_ISL_15251306, EPI_ISL_15251399-15251400] from Australia, California (USA) and Tamil Nadu (India). [Tamil Nadu cluster is something to follow closely!]

**Comment by RajLABN** [comment]
More BA.2.75.2* + N:M101I  - 3 from New Zealand and 5 from England 
[EPI_ISL_15276652
EPI_ISL_15278065
EPI_ISL_15278550
EPI_ISL_15283247
EPI_ISL_15296292
EPI_ISL_15296316
EPI_ISL_15296319
EPI_ISL_15296358]

**Comment by FedeGueli** [comment]
Now designated CA.3 @thomasppeacock @InfrPopGen milestone missing and issue still open
