### ISSUE TITLE
Potential BA.2.75.2/BF.5 recombinants (27 sequences as of 2022-10-11)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1137]
I am proposing this potential recombinant with only 9 sequences based on its concerning mutation profile and geographical distribution.

### Description
**Recombinant between**: BA.2.75.2 and BF.5
**Earliest sequence**: 2022/08/25 (Hong Kong)
**Most recent sequence**: 2022/09/21 (Netherland)
**Countries circulating**: 
- Hong Kong (1 seq, likely local case based on address of the originating lab)
- Chile (1 seq)
- US-VA (1 seq)
- Netherland (2 seqs)
- India-TN (4 seqs)

**Potential breakpoint**: between spike 486 and 1020.
**Mutation table**:
![image](https://user-images.githubusercontent.com/86835836/192953887-a5d07fd8-8e5f-4e2c-8731-bdbe49066092.png)

**Mutation on branch**: C5192T, G22599C, T23019C, G24620T
**GISAID query**: NSP3_P822S, NSP8_N118S, Spike_A1020S, M_D3N, -E_T11A
**Cov-spectrum query**: C3927T, C5192T, G24620T, G26529A

### Evidence
**Usher tree of current proposal as well as sibling recombinant clusters (under monitoring, yet to be proposed)**:
![image](https://user-images.githubusercontent.com/86835836/192955652-db06aa0f-ae32-4dce-b2ac-c012fde3ca7a.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24d97_431bd0.json?c=gt-nuc_2326,22125,10097,5192,18039&label=nuc%20mutations:G22898A,T22942G

### Genomes
EPI_ISL_14810310, EPI_ISL_15002926, EPI_ISL_15120916,
EPI_ISL_15139302-15139303, EPI_ISL_15146650, EPI_ISL_15146671,
EPI_ISL_15146714, EPI_ISL_15146839

**Comment by c19850727** [comment]
the 10th genome emerged, from Hong Kong again.

**Comment by c19850727** [comment]
20 sequences as of 2022-10-05, newly found in UK-Scotland, Singapore and Liechtenstein.

**Comment by c19850727** [comment]
3 new sequences from Hong Kong and US-WA by 2022-10-06.

**Comment by c19850727** [comment]
1 new sequence from Singapore as of 2022-10-10 (sampled on 2022-10-04). EPI_ISL_15312839.
This is the first local case in Singapore, while the previous 2 sequences from Singapore were imported cases (from India).

**Comment by thomasppeacock** [comment]
Would recommend this is designated soon as its fairly unusual for the recombinants and very international

**Comment by corneliusroemer** [comment]
I agree @thomasppeacock 

@c19850727 Just a quick note that to get something designated fast, it really helps if there's a recent Usher link that I can use to directly grab the sequences. This saves me 5 minutes!

**Comment by corneliusroemer** [comment]
What makes us think this is BA.2.75.2 rather than BY.1? It doesn't have the S:1199N mutation. Where's the break point?

**Comment by corneliusroemer** [comment]
This is a level 5, with RBD scores: immune escape 0.63, ACE2 0.47, composite 0.99

**Comment by cvejris** [comment]
Great spot! But why is this supposed to be derived from BF.5? It has neither ORF7a:H47Y, nor ORF9b:K40R. It has ORF9b:D16G (and S:A1020S), though. I think BA.5.2.1 is the contributing "parent".

**Comment by corneliusroemer** [comment]
Possible, you're right, I didn't check closely. I remember we never designated the S:1020S founder but went down the geographical nightmare path.

If you can find the likely ancestor due to other shared mutations, that'd be useful :)

**Comment by c19850727** [comment]
@cvejris you're right, it's just a guesswork based on a quick cov-spectrum query of the most prevalent BA.5* with S:A1020S in Tamil Nadu. It could be anything else, including some undesignated branch.

**Comment by cvejris** [comment]
The ancestor is BA.5.2.1 (ORF9b:D16G, see #657  ) "pre-BF.5", i.e. before acquisition of ORF7a:H47Y. @corneliusroemer this and the tree below is the best I can do...
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3b4a_6c0da0.json?branchLabel=aa%20mutations&c=gt-ORF7a_47&label=nuc%20mutations:A27038G
