### ISSUE TITLE
Potential BA.2.3.7/BA.5.1 recombinants (10 sequences as of 2022-09-29)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1139]
I am proposing this potential recombinant with only 10 sequences based on its association with a concerning epidemiological event.

### Description
**Recombinant between**: BA.2.3.7 and BA.5.1
**Earliest sequence**: 2022/09/15 (Japan ex-Taiwan and/or China)
**Most recent sequence**: 2022/09/15 (Japan ex-Taiwan and/or China)
**Countries circulating**: All 10 sequences are from Japan border control, among which 9 patients have a recent travel history from both Taiwan and mainland China (and the other one has a travel history from Taiwan only), therefore it's currently unclear if it's been circulating in either Taiwan, or mainland China, or both, or even neither.

**Potential breakpoint**: between spike 97 and 452
**Mutation table**:
![image](https://user-images.githubusercontent.com/86835836/193028580-67372ea2-85bc-48c4-be73-54d5c6928be3.png)

**Private mutations**: ORF1a:E1209Q, ORF1a:T3224A, ORF1b:H604Y, ORF1b:P2531S, ORF3a:T89A 
**GISAID query**: NSP3_E391Q, NSP2_A127V, Spike_K97E, M_D3N
**Cov-spectrum query**: it's not visible on Cov-spectrum yet; will update once it's there.

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/193032258-a4ae3f40-d951-4d5e-9d1f-f5d3f8f388dc.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d1e2_58f810.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C186T,C1185T,C2156T,G3890C,T4804C,C6031T,C9866T,A9935G,A12160G,C14599T,C16733T,C21058T,A21851G,A25657G

### Genomes:
EPI_ISL_15168019, EPI_ISL_15168733-15168741

**Comment by FedeGueli** [comment]
20 sequences with NSP3_P822S, NSP8_N118S, Spike_A1020S, M_D3N, -E_T11A query. it seems very fast.

**Comment by corneliusroemer** [comment]
Any updates here @c19850727?

**Comment by c19850727** [comment]
Sorry @corneliusroemer there's no update, and there've been only minimal sequences uploaded from Taiwan in October.

**Comment by InfrPopGen** [comment]
Thank you for proposing this recombinant. It's recognized that if transmission is occurring in mainland China it could be a sampling/detection issue, with a small proportion of cases being detected in Japan; however, this lineage does not appear to be very active. Consequently, closing this for now, but should a burst of new cases occur, please feel free to request a re-opening (or re-propose anew).
