### ISSUE TITLE
Sequences where the pango designation does not match the scorpio designation

### ISSUE THREAD

**Issue by Isobel1** [cov-lineages/pango-designation#114]
I have been looking for sequences where the pango designation does not match the scorpio designation, and have found 25 sequences within the training set. 

**The sequences affected are:** 
Brazil/SP-IB_101688/2021
Brazil/SP-IB_102795/2021
Brazil/SP-IB_102814/2021
Brazil/SP-IB_102816/2021
Brazil/SP-IB_102871/2021
Brazil/SP-IB_102872/2021
Brazil/SP-IB_102873/2021
Brazil/SP-IB_102874/2021
Brazil/SP-IB_102875/2021
Brazil/SP-IB_102877/2021
Brazil/SP-IB_102878/2021
Brazil/SP-IB_102879/2021
Brazil/SP-IB_102880/2021
England/LIVE-DD9C69/2021
England/MILK-11C1FEC/2021
England/MILK-1204FFB/2021
England/MILK-1205033/2021
England/MILK-F9DB71/2021
England/MILK-F9DBDB/2021
England/PHEC-1542AC/2020
England/WSFT-25C6539/2021
Singapore/542/2021
USA/CA-CDPH-UC1653/2020
USA/CA-LACPHL-AF00135/2020

For most of the sequences, the pango assignation and designation matches, with the exceptions of: England/PHEC-1542AC/2020 and England/WSFT-25C6539/2021. 

Full details including mutations: 
[scorpio_designation_conflict.xlsx](https://github.com/cov-lineages/pango-designation/files/6670100/scorpio_designation_conflict.xlsx)

**Comment by mcroxen** [comment]
Hi @isobel1,

You may want to update to version v3.1.2. I suspect this issue is similar to what was reported here:

https://github.com/cov-lineages/pangolin/issues/241

**Comment by chrisruis** [comment]
Thanks @Isobel1 for submitting this. So it looks like in most of these cases, the designation is incorrect for these sequences and scorpio has given the correct assignment. So we've therefore updated the designations for the following sequences, all can be found in [v1.2.27](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.27):
Brazil/SP-IB_102880/2021 updated from P.4 to P.1
Brazil/SP-IB_102814/2021 updated from P.4 to P.1
Brazil/SP-IB_101688/2021 updated from P.4 to P.1
Brazil/SP-IB_102795/2021 updated from P.4 to P.1
Brazil/SP-IB_102816/2021 updated from P.4 to P.1
Brazil/SP-IB_102872/2021 updated from P.4 to P.1
Brazil/SP-IB_102878/2021 updated from P.4 to P.1
Brazil/SP-IB_102879/2021 updated from P.4 to P.1
Brazil/SP-IB_102873/2021 updated from P.4 to P.1
Brazil/SP-IB_102877/2021 updated from P.4 to P.1
Brazil/SP-IB_102871/2021 updated from P.4 to P.1
Brazil/SP-IB_102874/2021 updated from P.4 to P.1
Brazil/SP-IB_102875/2021 updated from P.4 to P.1
Singapore/542/2021 updated from B.1.617.1 to P.1
England/LIVE-DD9C69/2021 updated from B to A.23.1
USA/CA-LACPHL-AF00135/2020 updated from B.1.1.335 to B.1.429
England/MILK-11C1FEC/2021 updated from B.1.177 to B.1.525
England/MILK-1204FFB/2021 updated from B.1.177 to B.1.525
England/MILK-1205033/2021 updated from B.1.177 to B.1.525
England/WSFT-25C6539/2021 updated from B.1.177.48 to B.1.1.7

B.1.324.1-like actually refers to B.1.623 (from #25) so those sequences were designated and assigned correctly - we've now updated scorpio to reflect this
