### ISSUE TITLE
BA.5.2.1 + ORF1b:G376S, mostly Sweden and US, 5k seqs, https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3AG376S&nextcladePangoLineage=BA.5.2.1*&

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1142]

**Comment by fznajar-okstate** [comment]
It seems that it has an RDRP mutations and a new spike mutation: Spike: T19I, DEL@24, DEL@25, DEL@26, A27S, DEL@69, DEL@70, G142D, V213G, G339D, S371F, S373P, S375F, T376A, D405N, R408S, K417N, N440K, L452R, S477N, T478K, E484A, F486V, Q498R, N501Y, Y505H, D614G, H655Y, N679K, P681H, G744S, N764K, D796Y, Q954H, N969K.
Conserved  NSP3 mutation: L1244F

**Comment by Mydtlwn** [comment]
BF.26 Are there any progeny strains worthy of designation?

**Comment by Mydtlwn** [comment]
BF.26 Are there any progeny strains worthy of designation?

**Comment by fznajar-okstate** [comment]
I am in the process of checking for new updates on GenBank.
