### ISSUE TITLE
Sublineage of BF.7 with S:D80G (~80 seq on Oct 7)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1147]
### **Description**
**Sub-lineage of:** BF.7
**Earliest sequence:** 2022-8-23, Ireland — EPI_ISL_14974006
**Most recent sequence:** 2022-9-21, UK (2) & Australia — EPI_ISL_15127852, EPI_ISL_15128006, EPI_ISL_15185490
**Countries circulating:** USA (17), UK (10), Ireland (2), France (2), Denmark (2), Australia (2), Germany (2), Netherlands (2), Israel (1), Japan (1), Portugal (1), Canada (1)
**Number of Sequences:** 43 (or 50 if you exclude the two synonymous nucleotide mutations)
**GISAID Query:** Spike_R346T, N_S33F, Spike_D80G (misses quite a few as some BF.7 sequences don't detect N:S33F)
**CovSpectrum Query:** Nextcladepangolineage:BF.7* & S:D80G
**Substitutions on top of BF.7:**
**Spike:** D80G
**Nucleotide:** A11506G, C20436T, A21801G
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_19f1d_875200%E2%80%94BF.7%2BD80G%E2%80%94v.2.json

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/33738461/193420953-e9afc3d6-e01b-4284-9155-7ccb3d7e4db1.png">

**Evidence**
Of the 43 sequences in this lineage, all have collection dates of August 23 or later, and 27 have collection dates of September 10 or later. It has primarily been detected in the US and NW Europe so far, but it has been found in 12 countries, including Australia, Japan, Israel, Canada, and Portugal. There is little diversity, suggesting rapid growth.

S:D80G is fairly rare mutation, but it does appear to be convergent in highly mutated, chronic-infection sequences. For example, two recent BA.1 sequences (same patient) with 12 spike mutations on top of BA.1 had D80G. A recent B.1.1.7, also with 12 additional spike mutations, had D80G, as did a BA.1.20 with 10 additional spike mutations. These are not the only examples. Convergent mutations in hypermutated chronic-infection sequences have often anticipated future trends. For example, S:R493Q and S:N460K were the two most common mutations seen in chronic-infection sequences long before they became common in normal sequences.
 
Furthermore, the only two previous lineages to possess S:D80G—AV.1 and B.1.637— were both saltation variants, featuring numerous novel spike mutations. These almost certainly originated in chronic infections. This all suggests that S:D80G is capable of conferring a significant fitness advantage in some contexts and could possibly grant this lineage an advantage over its parent lineage.

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/33738461/193418764-2d02a37f-288a-43b6-b18c-7c1b26ae7513.png">
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_14888215, EPI_ISL_14908975, EPI_ISL_14908996, EPI_ISL_14924375, EPI_ISL_14924418, EPI_ISL_14963033, EPI_ISL_14974006, EPI_ISL_15026072, EPI_ISL_15027112, EPI_ISL_15037051, EPI_ISL_15053816, EPI_ISL_15065260, EPI_ISL_15065421, EPI_ISL_15072258, EPI_ISL_15097433, EPI_ISL_15099457, EPI_ISL_15101030, EPI_ISL_15101109, EPI_ISL_15102885, EPI_ISL_15103730, EPI_ISL_15113585, EPI_ISL_15113901, EPI_ISL_15114884, EPI_ISL_15124952, EPI_ISL_15127852, EPI_ISL_15128006, EPI_ISL_15137651, EPI_ISL_15140932, EPI_ISL_15140966, EPI_ISL_15148849, EPI_ISL_15159295, EPI_ISL_15159786, EPI_ISL_15167946, EPI_ISL_15169645, EPI_ISL_15170749, EPI_ISL_15179091, EPI_ISL_15182936, EPI_ISL_15183034, EPI_ISL_15183500, EPI_ISL_15185490, EPI_ISL_15192321, EPI_ISL_15192974, EPI_ISL_15193208
</details>
 
<details>
<summary>Genomes with S:D80G but not A11506G & C20436T</summary>
EPI_ISL_14390829, EPI_ISL_14816614, EPI_ISL_14861210, EPI_ISL_15021810, EPI_ISL_15127904, EPI_ISL_15128281, EPI_ISL_15128286
</details>

**Comment by FedeGueli** [comment]
i found 45 as today with Spike_R346T, N_S33F, Spike_D80G,

**Comment by FedeGueli** [comment]
62 sequences as today.

I was tracking it in Collection #26 and it seems very fast not far from BQ.1 
https://cov-spectrum.org/collections/26

@InfrPopGen @corneliusroemer this should be designated .

**Comment by ryhisner** [comment]
Up to about 80 sequences as of October 7. It's hard to tell the exact number since you can't do nucleotide searches in GISAID. Sample is still too small to be reliable, but BQ.1 only has a 5% global weekly growth advantage over this lineage (BQ.1* has a 13% advantage). https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?variantQuery=Nextcladepangolineage%3ABQ.1&variantQuery1=Nextcladepangolineage%3ABF.7*+%26+S%3AD80G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
I can confirm it is not far from BQ.1 , i think a fast designation could help cc @InfrPopGen @corneliusroemer what do u think??

**Comment by FedeGueli** [comment]
@ryhisner i found that lineage BF.7  substittions: Spike_D80G on Gisaid finds 75 so very close to reality!

**Comment by corneliusroemer** [comment]
Let's see, not that fast, but could be OK designation nonetheless, not super urgent still.

**Comment by ryhisner** [comment]
It's still too small to put much confidence in the growth advantage numbers, but so far it looks pretty fast—barely below BN.1* according to a global CovSpectrum search. When I use it as a baseline for Collection 24, it ranks in between Level 5 and Level 6. 
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/33738461/195963779-d2a16183-d6ec-4c6c-ab7b-58f803bd4f82.png">

**Comment by InfrPopGen** [comment]
It looks like, since a designation on October 16th 2022, this clade now falls into BE.1.4 (B.1.1.529.5.3.1.1.4). If correct, then this won't be reflected in the tree until the next update.

**Comment by corneliusroemer** [comment]
Hmm that's weird, BF.7 is somewhere totally different than BE.1.4

**Comment by corneliusroemer** [comment]
It's clearly a BF.7.7 with extra muts 11506G, 20436T

Around 140 sequences now.

To check whether things belong to a recently designated lineage, do check it here on Nextclade nightly: https://nextclade-git-feat-composite-fitness-nextstrain.vercel.app/?dataset-name=sars-cov-2-21L&input-tree=https://api.codetabs.com/v1/proxy?quest=https://nextstrain.org/charon/getDataset?prefix=staging/nextclade/sars-cov-2/21L

<img width="2286" alt="image" src="https://user-images.githubusercontent.com/25161793/197009364-b17c7f37-797c-43fe-aa65-6f57b6af3859.png">

**Comment by InfrPopGen** [comment]
@corneliusroemer Problem might be lineages.csv, as Nextclade (above image) has Denmark/DCGC-583955/2022 listed as BF.7.7, which makes sense, but in lineages.csv it is Denmark/DCGC-583955/2022,BE.1.4 (and the same is true for every sequence in the clade proposed here, they're all BE.1.4).
