### ISSUE TITLE
BA.2.75.5 on ORF1a:G392D branch with S:450D [5 seqs, India, US, Germany, Israel]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1150]
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/25161793/193458378-cbf550ac-7634-4a0d-a1c1-3d6a9537d948.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_11e09_99a170.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22910G

**Comment by corneliusroemer** [comment]
GISAID query: `Spike_G446S,Spike_N460K, Spike_K356T,Spike_N450D`

A new Israeli sequence is interesting in that it has an additional Spike_F490S, so this should be even fitter.

hCoV-19/Israel/ICH-741187507/2022|EPI_ISL_15180262|2022-09-21

Query for that singlet: `Spike_G446S,Spike_N460K, Spike_K356T,Spike_N450D,Spike_F490S`

**Comment by corneliusroemer** [comment]
The singlet with the double mutation 450D and 490S is now 3 sequences, 2 new popped up today!

It's now been seen in 3 countries, probably worth a designation to track it.

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/25161793/195486697-c68a871d-92d2-4656-b63f-1941f5ec30b1.png">

**Comment by corneliusroemer** [comment]
The outer lineage is at 12 sequences

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/25161793/195486776-f52ee442-7401-472a-bea1-af8eb8b2ce54.png">

**Comment by InfrPopGen** [comment]
It looks like this lineage was designated as BN.3, and the S:F490S sub-lineage is almost all of BN.3.1. As originally proposed, the major lineage still has an apparent 2 month growth advantage of 40%  (17-63%) in the UK.
