### ISSUE TITLE
BA.2.3.20 sublineage with ORF1a:T2087I and ORF1a:S2103F (23 sequences: Denmark 22x, Israel 1x)

### ISSUE THREAD

**Issue by cvejris** [cov-lineages/pango-designation#1153]
This sublineage I already mentioned in #1013 has two additional AA mutations with respect to vanilla BA.2.3.20: ORF1a:T2087I and ORF1a:S2103F, corresponding to T1269I and S1285F in NSP3 (betaCoV-specific marker domain). 
The succession of mutations appearing on the BA.2.3.20 background is: first ORF1a:S2103F (many more samples, cosmopolitan), then ORF1a:T2087I (specific for ORF1a:S2103F-bearing subset of BA.2.3.20).
Countries detected: Denmark 22x (September 6th-25th), Israel 1x (September 18th) (as deposited in GISAID on October 3rd) - over 10% of total BA.2.3.20 worldwide. This sublineage represents a great majority (22/27) of Danish BA.2.3.20! 
GISAID query: NSP2_T547I,NSP3_I896T,NSP3_T1269I,NSP3_S1285F
CovSpectrum link: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AT2087I%2CORF1a%3AS2103F&nextcladePangoLineage=Ba.2.3.20*&
GISAID accession ID list:
EPI_ISL_14935736
EPI_ISL_14951071
EPI_ISL_14975009
EPI_ISL_14975202
EPI_ISL_14975306
EPI_ISL_15018355
EPI_ISL_15018396
EPI_ISL_15018444
EPI_ISL_15018492
EPI_ISL_15057002
EPI_ISL_15057123
EPI_ISL_15069949
EPI_ISL_15069986
EPI_ISL_15070031
EPI_ISL_15100654
EPI_ISL_15101232
EPI_ISL_15138709
EPI_ISL_15155354
EPI_ISL_15155944
EPI_ISL_15156076
EPI_ISL_15170274
EPI_ISL_15207347
EPI_ISL_15208534
I think this represents a clear and fast epidemic spread, thus the lineage is worth monitoring, not only in Denmark. Also, the Danish genomic surveillance has been outstanding and their timely efforts deserve to be rewarded by timely designation.

**Comment by corneliusroemer** [comment]
We usually like to have an Usher tree ;)

Let's wait for a bit to see how BA.2.3.20 pans out - there's no reason a priori why these two AA must would make a huge difference.

**Comment by alurqu** [comment]
I've been watching BA.2.3.20+25171C+ORF1a:S2103F which appears to be the parent of the sublineage proposed here, and note that synonymous mutation 25171C may have been the first mutation to occur on this branch.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As this lineage is not showing a marked growth advantage (in fact it's currently showing the opposite) at the moment, the issue is being closed. Please feel free to request re-opening or to re-propose as a new issue, should there be be signs of sustained growth advantage (or other events of interest).
