### ISSUE TITLE
Slovenian BA.1.1 with continued circulation till August and cryptic wastewater signature [~20 seqs]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1154]
Using Marc Johnson's suggestion for cryptic wastewater lineage signature of RBD mutations: https://cov-spectrum.org/collections/57 I spotted this most mutated Slovenian BA.1.1 lineage with a lot of RBD mutations.

Would be interesting to hear if this is one patient sampled over a long time or circulation in Slovenia

<img width="2265" alt="image" src="https://user-images.githubusercontent.com/25161793/193704250-990f4658-718b-4cb8-8da2-7728ae6848ab.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35858_b6edc0.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C4876T,G6741A,C13536T,A16653G,T24892C,G28560T

**Comment by agamedilab** [comment]
Hi @corneliusroemer, this lineage is likely derived from an chronic infected 61 year old women (which then turned 62) and was already proposed in June (#778). 

EPI_ISL_13251406
EPI_ISL_12284821
EPI_ISL_13251514
EPI_ISL_13271922
EPI_ISL_13272223
EPI_ISL_13253132
EPI_ISL_13272001
EPI_ISL_13665110
EPI_ISL_14961972
EPI_ISL_14027788
EPI_ISL_14047361
EPI_ISL_13253550
EPI_ISL_13253416
EPI_ISL_13368501
EPI_ISL_13478425
EPI_ISL_14962617
EPI_ISL_13253164
EPI_ISL_13253296
EPI_ISL_14962429
EPI_ISL_14962212
EPI_ISL_14027304
EPI_ISL_14951595
EPI_ISL_14952059
EPI_ISL_14953487

**Comment by corneliusroemer** [comment]
Good spot, thanks @agamedilab 

I wonder whether we could find out whether this started circulating more broadly. Either that or the patient had some quite interesting intra-host diversity!

**Comment by aviczhl2** [comment]
It seems that another(or more than one?) Slovenia branch of heavily mutated BA.1 emerged in late 2022. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice10_genome_44f6_2befa0.json)
