### ISSUE TITLE
BA.4.6 with S:F490V in England [8 seqs as of 2022-10-04]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1155]
This is possibly one of the fittest BA.4.6 around with extra S:F490V, 8 recent sequences from England

<img width="2289" alt="image" src="https://user-images.githubusercontent.com/25161793/193822449-5a7672f9-aedf-4248-b03a-4748fbfbce77.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43bd1_c28de0.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T23030G

**Comment by InfrPopGen** [comment]
Closing this one for now, as it appears to be stagnant, both world wide and in its original hot spots.
