### ISSUE TITLE
BQ.1.1 sublineage with ORF1a:V3855I and ORF1b:P2313L (22 seqs; Europe, USA, Israel)

### ISSUE THREAD

**Issue by cvejris** [cov-lineages/pango-designation#1156]
![image](https://user-images.githubusercontent.com/110762428/193827081-4ef6fcd8-a8d3-453c-8e5c-f0d880df7558.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_42a5b_c28410.json?branchLabel=aa%20mutations&c=gt-ORF1ab_3855,6714&label=nuc%20mutations:C17676T
Both defining mutations (ORF1a:V3855I and ORF1b:P2313L) always occur together.
Oldest sample: September 2nd (Texas, USA)
Wide distribution: Israel 1x, Denmark 1x, Portugal 1x, Belgium 4x, France 5x, UK 6x, USA 4x
GISAID IDs (query: Spike_N460K,Spike_K444T,Spike_R346T,Nsp13_N268S,NSP15_P262L, NSP6_V286I):
EPI_ISL_14954443
EPI_ISL_15199222
EPI_ISL_15170008
EPI_ISL_15114732
EPI_ISL_15097771
EPI_ISL_15141316
EPI_ISL_15175614
EPI_ISL_15175616
EPI_ISL_15039224
EPI_ISL_15100774
EPI_ISL_15214679
EPI_ISL_15221558
EPI_ISL_15154520
EPI_ISL_15203046
EPI_ISL_15194815
EPI_ISL_15203250
EPI_ISL_15203268
EPI_ISL_15203272
EPI_ISL_15203279
EPI_ISL_15215484
EPI_ISL_15194832
EPI_ISL_15203280

Let´s see how it will fare in Europe in competion with other BQ.1.1

**Comment by cvejris** [comment]
Germany and Canada, 1x each

**Comment by cvejris** [comment]
Japan 1x

**Comment by corneliusroemer** [comment]
Not clear why we should designate this at this point, there are always going to be branches. Is there a reason this should be faster? Could be defined by artefact etc.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there currently does not seem to be good clear growth relative to BQ.1.1 itself (in US, UK or France), this issue is being closed for now. Nevertheless, please do request a re-opening or re-propose this as a new issue should the growth situation change markedly.
