### ISSUE TITLE
Proposal of new sub-lineage of BA.2.12.1 with additional mutations Orf1ab:E726K, V1020A, F1632L, F2321L in peruvian genomes

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#1157]
**Proposal of new sub-lineage of BA.2.12.1 with additional mutations Orf1ab:E726K, V1020A, F1632L, F2321L in peruvian genomes by Group of Genomic Surveillance INS-PERU**

**Description**
**Sub-lineage of: Potential new sub-lineage of BA.2.12.1**
**Earliest sequence:** hCoV-19/Peru/LIM-INS-21035/2022 (22/06/2022, Peru)
**Most recent sequence:** hCoV-19/Peru/UCA-INS-27157/2022 (09/08/2022, Peru)

**Countries circulating**
Peru (28)

This potential BA.2.12.1 is principally distributed in Ucayali, Peru. Some genomes of new sub lineage carry a reversion in Spike:S408R

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/9708833/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20670_c369b0.json?branchLabel=aa%20mutations&c=gt-ORF1ab_726,1020,1632,2321&label=nuc%20mutations:T5161A,T7226C,C27630T&tl=country

<img width="1739" alt="BA 2 12 1 Orf1ab" src="https://user-images.githubusercontent.com/87997149/193872689-a2daf2d8-9ad8-41bc-80a4-1e09b1df3cac.png">

<img width="1285" alt="BA 2 12 1 Orf1ab2" src="https://user-images.githubusercontent.com/87997149/193874865-82bccac7-c562-48e8-8ff0-056ed7f8a51f.png">

<img width="1743" alt="BA 2 12 1 Orf1ab3" src="https://user-images.githubusercontent.com/87997149/193872853-77ecb4c5-f5de-4b54-aa7c-aa38435975fa.png">

<img width="1567" alt="BA 2 12 1 Orf1ab4" src="https://user-images.githubusercontent.com/87997149/193872907-8f2c6ad8-d13c-47d2-afd0-6222d06c9511.png">

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BG.7 with 27 newly designated sequences, and 0 updated designations. Defining mutations T5161A (ORF1a:F1632L), T7226C (ORF1a:F2321L), and nt:C27630T.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BG.7 with 27 newly designated sequences, and 0 updated designations. Defining mutations T5161A (ORF1a:F1632L), T7226C (ORF1a:F2321L), and nt:C27630T.
