### ISSUE TITLE
New possible BF.5.* lineage containing ORF1ab: G638C mutation identified by the group of Genomic Surveillance of INS-Peru

### ISSUE THREAD

**Issue by Vjimenez-vasquez** [cov-lineages/pango-designation#1158]
**Description**
New possible BF.5.* lineage containing ORF1a: G638C mutation identified by the group of Genomic Surveillance of INS-Peru and mainly circulating in Peru, Chile and USA. 

**Evidence**
Usher general phylogeny
![usher_phylogeny](https://user-images.githubusercontent.com/89874227/193879817-4f30c47d-e8ed-4af8-8d63-d3651ff5d8cb.jpeg)

Usher subtree
![usher_phylogeny_subtree](https://user-images.githubusercontent.com/89874227/193879844-9cacbd9f-e98f-4691-a0bc-df3f8742a1be.jpeg)

**Mutations**
ORF1ab: G638C

**Genomes**
[EPI_CODES.txt](https://github.com/cov-lineages/pango-designation/files/9709059/EPI_CODES.txt)

**Earliest sequence: 2022-07-02**
hCoV-19/Peru/LIM-INS-22632/2022 (EPI_ISL_14241162)
hCoV-19/Peru/LIM-INS-22631/2022 (EPI_ISL_14241163)

**Most recent sequence: 2022-09-16**
hCoV-19/USA/KY-CDC-LC0888026/2022 (EPI_ISL_15159938)

**Countries circulating**
Chile(3), Peru(18) and USA (22)

**Comment by InfrPopGen** [comment]
Thank you for proposing this as a lineage. As it has not shown much growth since September, this can be closed for now. Please re-propose or request re-opening should this lineage reappear with a clear advantage.
