### ISSUE TITLE
Proposal of new potential sub-lineage of BA.2.12.1 containing Spike: Q677H, Q675H, ORF1ab:H81del, G82del mutation identified by the group of Genomic Surveillance of INS-Peru 

### ISSUE THREAD

**Issue by IrisSilvaINS** [cov-lineages/pango-designation#1159]
**Description**
Proposal of new potential sub-lineage of BA.2.12.1 containing Spike: Q677H, Q675H, ORF1ab:H81del, G82del mutation identified by the group of Genomic Surveillance of INS-Peru 

**Earliest sequence**: 2022/05/02
hCoV-19/USA/PA-Curative-313453/2022 (EPI_ISL_12713690)

**Most recent sequence**: 2022/08/14
hCoV-19/Peru/TAC-INS-26663/2022 (EPI_ISL_14926493)

**Mutations**
Mutations : Spike: Q677H, Q675H; ORF1ab:H81del, G82del

**Genomes**
[GENOMES.txt](https://github.com/cov-lineages/pango-designation/files/9709730/GENOMES.txt)

**Countries circulating**
Peru(41), USA (6) and Chile(1)

**Evidence**

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1c62_c456f0.json?branchLabel=aa%20mutations&c=gt-S_675,677&label=nuc%20mutations:C7600T,G23587T,G23593T

https://cov-spectrum.org/explore/Peru/AllSamples/Past6M/variants?aaMutations=S%3AQ677H%2CS%3AQ675H&nextcladePangoLineage=BA.2.12.1&

![image](https://user-images.githubusercontent.com/93674902/193900057-2e4b7662-3af2-42f2-aabf-a278ff37b351.png)

![image](https://user-images.githubusercontent.com/93674902/193900093-ed2f2c99-0bb1-452f-a599-3739d895a1e6.png)

![image](https://user-images.githubusercontent.com/93674902/193900128-c925d2ee-228a-4745-9312-729865cdc601.png)

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there appear to be no new detections within this clade since mid-August, this issue can be closed for now. Please re-propose or request re-opening should this lineage show major expansion in the future.
