### ISSUE TITLE
Potential new lineage B.1.575 lineage with E484K in Navarra

### ISSUE THREAD

**Issue by Urruti** [cov-lineages/pango-designation#116]
Description
Sub-lineage of: B.1.575 with E484K
Earliest sequence: EPI_ISL_2516688 Collection date 2021-05-27
Most recent sequence: EPI_ISL_2516940 Collection date  2021-06-08

Countries: Navarra, Spain

There are more than 100 sequences uploaded to GISAID from Navarra of B.1.575 with E484K.
Most of them are from the last month, implying this variant may be expanding rapidly while the general SARS-CoV-2 numbers have been on a steadily decrease. 
Presenting this E484K which is now well known as worrisome I think this may be worth of a new sublineage of B.1.575

![image](https://user-images.githubusercontent.com/8407888/122451727-c581b700-cfa8-11eb-8a80-643575d7407b.png)

**Comment by chrisruis** [comment]
Thanks very much @Urruti for submitting this. We've added this as lineage B.1.575.2 with 89 new sequence designations in [v1.2.22](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.22)
