### ISSUE TITLE
Proposal of new BA.5.1 sublineage with ORF7a:P99S, ORF1ab: Q975R, Nuc: A10378G, T29575C mutations circulating in Peru.

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#1160]
**Description**
Potential BA.5.1 sub-lineage with ORF7a:P99S, ORF1ab: Q975R, Nuc: A10378G, T29575C mutations proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru. 

**Earliest sequence:** 2022-07-22
Peru/CUS-INS-25399/2022

**Most recent sequence:** 2022-09-01
Peru/CUS-INS-27656/2022
Peru/CUS-INS-27679/2022

**Countries circulating:**
Peru (6)

**Genomes**
[Genomes.csv](https://github.com/cov-lineages/pango-designation/files/9709890/Genomes.csv)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_11192_c3e090.json?branchLabel=aa%20mutations&c=userOrOld
![Captura de pantalla de 2022-10-04 09-12-50](https://user-images.githubusercontent.com/89021119/193905657-e0547274-e0ad-4873-ac90-885e44870beb.png)

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As this clade has remained small and there do not be any signs of growth since early September, the issue can be closed for now. Please re-propose or request re-opening for this lineage should there be a marked change in the situation.
