### ISSUE TITLE
Proposal of new sub-lineage of BA.5.1 with additional mutation Orf8:Y111C in peruvian genomes

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#1161]
**Proposal of new sub-lineage of BA.5.1 with additional mutation Orf8:Y111C in peruvian genomes by Group of Genomic Surveillance INS-PERU**

**Description**
**Sub-lineage of:** Potential new sub-lineage of BA.5.1
**Earliest sequence:** hCoV-19/Peru/TAC-INS-24188/2022 (09/07/2022, Peru)
**Most recent sequence:** hCoV-19/Peru/TAC-INS-28713/2022 (02/09/2022, Peru)

**Countries circulating**
Peru (11)

This potential BA.5.1 is principally distributed in Tacna, Peru. 

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/9711571/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2815e_cb0d90.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A28225G

<img width="1730" alt="BA 5 1 Orf8 2" src="https://user-images.githubusercontent.com/87997149/193951921-e2357071-7eb6-4462-8535-ba9281172199.png">

<img width="1182" alt="BA 5 1 Orf8" src="https://user-images.githubusercontent.com/87997149/193951760-06221641-1535-49c9-9d8d-4d1bd1b8c0e6.png">

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there has not been detected growth of this clade since September 5th, this can be closed for now. Please re-propose or request re-opening should there be a marked change in the situation in the future.
