### ISSUE TITLE
BA.5.2.1 with ORF3a:M260K via nuc:U26171A [132 good+ seq as of 2022-10-04]

### ISSUE THREAD

**Issue by ndkling** [cov-lineages/pango-designation#1162]
Proposal for a sublineage of BA.5.2.1
Earliest sequence: 2022-06-29 (New York, USA, EPI_ISL_13949083)
Countries detected: Mostly Denmark, but some US, UK, and global

While ORF3a:M260K has been found sporadically since early in the pandemic, this cluster acquired it through the unusual combination of G>A at 26172 followed by U>A at 26171, a pairing found only 40 times in good+ sequences outside BA.5.2.1.  The largest other cluster of 26171A + 26172A was found in England in AY.4.2, emerging and doing well just before getting steamrolled by Omicron.  ORF3a:M260K seems unremarkable without 26172A.

Genomes:

[BA.5.2.1+G26172A+T26171A.csv](https://github.com/cov-lineages/pango-designation/files/9712767/BA.5.2.1%2BG26172A%2BT26171A.csv)

obtained through covSPECTRUM using the query:

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladeQcOverallScoreTo=29&variantQuery=G26172A+%26+T26171A+%26+BA.5.2.1*

Evidence:

I'm not sure that UShER has the tree drawn exactly right, showing U26171A arising independently several times.  Given the global rarity of U26171A, it seems more likely that it arose fewer times, but I don't know enough to judge.  The cluster is otherwise clean.

![BA 5 2 1+G26172A+T26171A](https://user-images.githubusercontent.com/82973333/193983743-0ed6e20b-f3b1-4f05-8205-9f27f4fd6d85.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1508b_d0b4b0.json?branchLabel=nuc%20mutations&c=userOrOld&label=nuc%20mutations:G26172A

Looking at the main subtree reveals more public genomes that aren't found by covSPECTRUM.  Manual inspection reveals 26172A, 26171A, BA.5.2.1 consistently called, and ORF3:M260K, so I don't know why they aren't included.

![subtree1](https://user-images.githubusercontent.com/82973333/193987564-751b0b23-94c8-4060-816b-59b0f2de34fa.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14426_d0b0b0.json?branchLabel=nuc%20mutations&c=userOrOld&label=nuc%20mutations:T26171A

Given that the majority of sequences are from Denmark, growth advantages are calculated there, although global numbers are similar.  With 120 total Danish sequences, these estimates should be reasonable if preliminary and yield a 28% (CI 21-36%) growth advantage over BA.5.2.1*:

![vsBA 5 2 1](https://user-images.githubusercontent.com/82973333/193984131-6efa3f7a-dc04-410d-8880-16317eec1a9a.png)

https://cov-spectrum.org/explore/Denmark/AllSamples/Past6M/variants?variantQuery=BA.5.2.1*&variantQuery1=G26172A+%26+T26171A+%26+BA.5.2.1*&analysisMode=CompareToBaseline&

and 35% (CI 28-42%) over background.

![vsBackground](https://user-images.githubusercontent.com/82973333/193984155-afc86f9c-0127-45ab-b1ce-b67b2e2ba23e.png)

https://cov-spectrum.org/explore/Denmark/AllSamples/Past6M/variants?variantQuery=G26172A+%26+T26171A+%26+BA.5.2.1*

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.29 with 111 newly designated sequences, and 3 updated designations from BA.5.2.1. Defining mutation T26171A (ORF3a:M260K) (following G26172A (ORF3a:M260I)).
