### ISSUE TITLE
BN.1 with S:K444R (1 sequence, Singapore, 2022-10-05)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1163]
When looking at most recent GISAID uploads, I noticed a BN.1 from Singapore with an extra S:K444R which is predicted to increase immune escape based on Jesse Bloom's escape calculator as implemented in Nextclade 

<img width="455" alt="image" src="https://user-images.githubusercontent.com/25161793/193988524-ff98ea5f-0137-4f86-a794-bd79f4be6de8.png">

(This feature is in experimental mode, you can access the most experimental composite fitness feature by using this link https://nextclade-git-feat-composite-fitness-nextstrain.vercel.app/?dataset-name=sars-cov-2-21L&input-tree=https://api.codetabs.com/v1/proxy?quest=https://nextstrain.org/charon/getDataset?prefix=staging/nextclade/sars-cov-2/21L)

This could be become one of the fittest BA.2.75* so it's good to watch for future sequences showing up.

This is the singlet EPI_ISL: hCoV-19/Singapore/12380/2022|EPI_ISL_15229455|2022-09-23

Usher tree:

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/25161793/193988239-a98c5284-48c7-4e50-b1e8-423bedf67763.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_42ffe_d155c0.json?branchLabel=Spike%20mutations&c=pango_lineage_usher

GISAID query: 
`Spike_R346T, Spike_K356T, Spike_K444R, Spike_F490S`

**Comment by FedeGueli** [comment]
@corneliusroemer maybe better to open a BN.1 diversity issue? i have a BN.1 + S:445A and one BN.1 +S:N481K

**Comment by corneliusroemer** [comment]
@FedeGueli feel free to open that issue sounds like a good idea to reduce number of issues, I can edit your issue then (as I have issue edit rights). You can use the same layout as I have in the past, with checkboxes etc, keep it nice and succinct to make it easy for review:
- [ ] key mutation, seq numbers countries, gisaid query, that's it

**Comment by corneliusroemer** [comment]
Nothing has happened here, I'll close for now

**Comment by FedeGueli** [comment]
> @FedeGueli feel free to open that issue sounds like a good idea to reduce number of issues, I can edit your issue then (as I have issue edit rights). You can use the same layout as I have in the past, with checkboxes etc, keep it nice and succinct to make it easy for review:
> 
> * [ ]  key mutation, seq numbers countries, gisaid query, that's it

thx Cornelius, i hvae now opened one for BN.1 in #1213
