### ISSUE TITLE
Lineage with XBB-like spike with extra S:K444R (2 sequences, India-OR, 2022-10-05)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1164]
I noticed two sequences from India-OR with the same XBB-like Spike that has an extra S:K444R added on top, which is predicted to make this Spike more immune evasive than XBB itself. Of course with so many Spike mutations it's possible that the limits of a DMS calculator is approached, as there may be interactions between mutations that DMS can't capture. But this is good to keep an eye on for future developments, and potentially tests in the lab, given that XBB was found to be the most immune evasive yet by Yunlong Cao et al

There's an interesting triple AA mutation here:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/25161793/193989135-f0f59c15-f745-4288-954a-caf3dc9a5443.png">

```
hCoV-19/India/OR-RMRC_B-ICMR-INSACOG-BBS431044/2022|EPI_ISL_15231502|2022-09-19
hCoV-19/India/OR-RMRC_B-ICMR-INSACOG-RMRC10942/2022|EPI_ISL_15231536|2022-09-19
```

The two sequences are down here in black:

<img width="2291" alt="image" src="https://user-images.githubusercontent.com/25161793/193989218-498588e3-9442-4a94-b358-28ec2e82b42d.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42ffe_d155b0.json?label=nuc%20mutations:C22664A

**Comment by RajLABN** [comment]
There is also a XBB sequence with Spike K444N from West Bengal (EPI_ISL_14891587)
