### ISSUE TITLE
BA.2.3.20 with S:A348S (2 sequences, Singapore, as of 2022-10-10)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1165]
BA.2.3.20 is relatively fit but notably does not yet have a S:346T lineage yet, which could feasibly arise and be a potential competitor with XBB and BQ.1.1

I noticed a BA.2.3.20 with extra S:A348S which is in a similar location and could have similar effects as S:346T, at least it's predicted to increase immune escape by the Bloom lab calculator.

This case is from a 97 year old patient in Singapore:
hCoV-19/Singapore/12349/2022|EPI_ISL_15229428|2022-09-24

GISAID query: `Spike_A348S,Spike_L452M`

**Comment by FedeGueli** [comment]
There are also 3 BQ.1 with S:A348S

**Comment by corneliusroemer** [comment]
Good spot @FedeGueli - that mutation looked strangely familiar, now I know why!

Could be a sign that it's potentially beneficial, or at least that it's not very deleterious.

**Comment by oobb45729** [comment]
Some mutations at the 348 site with larger side chains like D/E/H/K are predicted to have large immune escape effects, but A348S is not among them. I suspect that the reason is that a large side chain at the 348 site clashes with atoms nearby, leading to a drastic structural change around the area, which causes immune escape and is likely deleterious. A348S (or A348P) won't clash with atoms nearby. I doubt it will have a large immune escape effect. This is unlike R346X where R346 interacts with antibodies directly.

**Comment by oobb45729** [comment]
Speaking of R346X, there might be a reason why BA.2.3.20 hasn't gained R346X yet. I suspect that N450D forms a salt bridge with R346, which could potentially make R346X mutations less advantageous. The concurrence of N450D and R346X has been very rare so far.

**Comment by corneliusroemer** [comment]
Now there seems to be a second Singaporean with S:348S

Let's wait until we have 5 before designation, shouldn't take too long if it doubles every week.

hCoV-19/Singapore/12824/2022|EPI_ISL_15312821|2022-10-05
hCoV-19/Singapore/12349/2022|EPI_ISL_15229428|2022-09-24

**Comment by ryhisner** [comment]
> Speaking of R346X, there might be a reason why BA.2.3.20 hasn't gained R346X yet. I suspect that N450D forms a salt bridge with R346, which could potentially make R346X mutations less advantageous. The concurrence of N450D and R346X has been very rare so far.

Wow, there have only ever been three sequences ever with R346T and N450D. You're definitely onto something. I thought it was only a matter of time before BA.2.3.20 picked up R346T, but I no longer think that. This essentially makes N450D positively detrimental to any lineage that has it, and it might well doom BA.2.3.20 to extinction at the hands of variants with R346T.

**Comment by InfrPopGen** [comment]
These appear to have been designated as CM.6.1, so this is being closed as completed.
