### ISSUE TITLE
Collection of BA.2.3.20 (spike) diversity

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1166]
Based on Ryan Hisner's and others' work, I looked at BA.2.3.20 and noticed there's quite some Spike diversity that may be worth looking into for proposals at some point.

- [x] S:N17S, already proposed in #1129 
- [ ] S:H69Y, 5 seqs, all US
- [ ] S:K150I, 4 seqs, all US-CA
- [ ] S:262G, 3 seqs, all US-CA
- [ ] S:264V, 3 seqs, Austria
- [ ] S:V289I, 2 seqs, Singapore
- [ ] S:348S, 2 seqs, Singapore #1165 
- [ ] S:G485D, 3 seqs, 2x Australia, 1x US (I remember Ryan mentioning this too)

All but S:N17S are too small for designation at this point.

**Comment by RajLABN** [comment]
S:G675R too (Singapore, South Korea)

**Comment by FedeGueli** [comment]
New diversity from today uploads:
 S:N185T 2 seqs , 
S:D53N 2 seqs

**Comment by ryhisner** [comment]
There's only been one, but S:R444M showed up today in a sequence from California. That's going from R444 to M444 is a massive upgrade, so I wouldn't be surprised to see a lot more of those in the coming days. EPI_ISL_15256979

**Comment by ryhisner** [comment]
Super interesting South Korean sequence imported from the Philippines today: S:R444T, S:I596V, ORF1a:R226K, and ORF1b:D146G. EPI_ISL_15281031

ORF1b:D146G (NSP12_D155G) has been in several sequences recently.

**Comment by ryhisner** [comment]
S:G485D is up to four sequences now after one was uploaded from Australia yesterday. EPI_ISL_15275314

**Comment by ryhisner** [comment]
A second BA.2.3.20 with S:R444M has now turned up in Switzerland. Like the one from California, it is on the S:N17S branch. EPI_ISL_15285536

**Comment by FedeGueli** [comment]
3 sequences with S:A264V popped up today, and one with S:K478E

**Comment by ryhisner** [comment]
I saw the A264V sequences, but I didn't notice the K478E! Nice spot, Fede.

The other sequence that, although just a singlet, I think deserves mention is the BA.2.3.20 with three FCS mutations: S:Q675R, S:K679R, and S:A684V. This is a remarkable set of concurrent mutations. There has never been a sequence with S:Q675R and S:K679R. There has also never been a sequence with S:K679R and S:A684V. And there have only ever been two previous sequences—one from February 2021 and the other from September 2020. For all three to show up in the same sequences is remarkable and suggests some sort of selection is at work.

The sequence is from USA, Colorado, and has a collection date of September 12. EPI_ISL_15318843

**Comment by ryhisner** [comment]
Four more S:G485D sequences uploaded in the past 24 hours: EPI_ISL_15275314, EPI_ISL_15358772, EPI_ISL_15359092,
EPI_ISL_15359810

Other notable sequences from the last 24 hours:

EPI_ISL_15359472 — S:R444W  (This is the first ever S:W444 sequence.)
EPI_ISL_15362187 — S:K150E (This brings the K150E count to 4 sequences, all uploaded in the past two days)
EPI_ISL_15362291 — S:G446S + S:K478I
EPI_ISL_15362632 — S:V445A
EPI_ISL_15359314 — S:R214C
EPI_ISL_15358847 — S:I68T
EPI_ISL_15362287 — E1202K

**Comment by ryhisner** [comment]
There have now been two BA.2.3.20 sequences with S:F486S, one from Australia and one from Singapore. The Singapore sequence, uploaded today, is from a person with travel history in the Philippines, which is where a lot of the most interesting BA.2.3.20 sequences seem to be originating from (and the country where it has likely been circulating the longest).
EPI_ISL_15258516
EPI_ISL_15384166

**Comment by FedeGueli** [comment]
updates: 
( ) Spike_Q675R reached 4 sequences
( ) Spike_T478E reached 3 sequences
( ) Spike_A262G reached 4  seqs
( ) Spike_V289I reached 5 sequences

**Comment by emily-smith1** [comment]
Small group of recent BA.2.3.20s from USA (California) that have both S:S256L and N:P6T

EPI_ISL_15483507
EPI_ISL_15532257
EPI_ISL_15550095
EPI_ISL_15550096
EPI_ISL_15550097

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1365d_c4eb20.json?branchLabel=aa%20mutations

![image](https://user-images.githubusercontent.com/84812104/198741098-25255536-8a0e-4b54-82b6-644f45ed389a.png)

**Comment by corneliusroemer** [comment]
Will close this as it has served its purpose and BA.2.3.20 is no longer a top priority lineage with the emergence of XBB.1.5 & co
