### ISSUE TITLE
BM.1.1.1 sublineage with S:F486P (5 seq., Singapore, Austria)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1171]
Proposal for a sublineage of BM.1.1.1
Earliest sequence: 23.09.2022 (Singapore)
Countries detected: Singapore (2), Austria (3)

Defining mutation:
T23018C = S:F486P

This sublineage of BM.1.1.1 is defined by S:F486P and was first detected in Singapore before showing up in yesterdays Austria upload.

![grafik](https://user-images.githubusercontent.com/102166254/194210920-456c1b88-e4c4-4c54-9a33-e02a169f5594.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_311e4_e4dc90.json?branchLabel=aa%20mutations&c=gt-S_486&label=nuc%20mutations:A5006G,T23018C

EPI_ISL_15229455
EPI_ISL_15229451
EPI_ISL_15259754
EPI_ISL_15259639
EPI_ISL_15259696

**Comment by FedeGueli** [comment]
Saw that yesterday too. Good proposals

**Comment by agamedilab** [comment]
+1 UK: EPI_ISL_15262599

**Comment by corneliusroemer** [comment]
Noticed this just now, and then found the proposal. Good spot! Worth designating given we've seen the S:F486P pop up repeatedly and it's predicted to be advantageous to ACE2 binding.

**Comment by corneliusroemer** [comment]
Adding GISAID query in future would be great, I don't know how to do these double mutations in GISAID with Spike muts... Maybe we need to ORF1ab one instead as a proxy.

**Comment by FedeGueli** [comment]
@corneliusroemer there isnt a single sublineage with S:486P i think we have at least three this one, the other one proposed in NZL and another with two sequences which are close but not in the same branch (BM.1.1)

**Comment by agamedilab** [comment]
I would be very happy if a designate label & milestone could be added to the issue. many thanks! @corneliusroemer @InfrPopGen

**Comment by corneliusroemer** [comment]
Milestone was already added 15 hours ago ;)
