### ISSUE TITLE
XBB with 	S:D253G [7 seqs, India, Japan from India, AUS-NSW]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1173]
I spotted 3 XBB with S:D253G from 3 countries.

What struck me was the proximity to the XBB.1 defining mutations S:252V

The fact that we see two mutations arise in almost the same position could indicate growth advantage to mutations at that position. Let's see how this develops.

S:D253F was part of the Iota variant

GISAID query: `Spike_D253G, Spike_V83A, Spike_F486S, Spike_F490S`

hCoV-19/India/WB-INSACOG-1931503322615/2022|EPI_ISL_15172933|2022-08-24
hCoV-19/Australia/NSW-ICPMR-34181/2022|EPI_ISL_15250346|2022-09-26
hCoV-19/Japan/IC-14346/2022|EPI_ISL_15167930|2022-09-09

**Comment by agamedilab** [comment]
+3 Austria: 
EPI_ISL_15329501, EPI_ISL_15329479, EPI_ISL_15329395

![grafik](https://user-images.githubusercontent.com/102166254/195276298-077eabba-5a61-4ec8-858b-b7c7a09f6ae0.png)

7 total as of 12.10.22.

**Comment by FedeGueli** [comment]
I think the commit is wrongly associated with this issue @corneliusroemer

**Comment by AnonymousUserUse** [comment]
I think the commit is wrongly associated with this issue @corneliusroemer
