### ISSUE TITLE
XBB with S:444R [2 seqs, India]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1175]
I noticed that with the latest covSpectrum update there were the first ever 2 BA.2* derivatives with 8 relevant spike mutations.

Turns out they are XBB.1 with S:K444R in addition.

![image](https://user-images.githubusercontent.com/25161793/194384257-eb5e045d-3496-47da-a9ac-302df5f8b1ea.png)

Let's hope these are artefacts. The sequences have quality issues: dropouts and reversions, so before we designate this we would want to see at least a high quality genome without QC issues. But it's feasible that XBB would acquire S:444R, and would fit the pattern of evolution we've been observing for a few months now.

EPI_ISL_15231502
EPI_ISL_15231536

**Comment by AngieHinrichs** [comment]
FWIW UShER placed those two (pink-circled) as XBB not XBB.1, on a branch with a ton of reversions (blue-circled):
<img width="835" alt="image" src="https://user-images.githubusercontent.com/186983/194386833-d477cf31-7fdb-4263-9a87-cf3f1dfd9d7f.png">
So yeah, could be artefacts.

**Comment by AngieHinrichs** [comment]
Those two sequences don't have XBB.1-defining S:G252V / G22317T.

**Comment by corneliusroemer** [comment]
Thanks for checking - I agree that they are not great sequences, so I wouldn't designate until we have high quality ones, but it is something to look out for.

They have dropouts in the region where XBB.1 is defined - and since that's possibly the only mutation that defines XBB.1 it was silly of me to name it XBB.1 - no clue why Nextclade places one as XBB.1

![image](https://user-images.githubusercontent.com/25161793/194388505-e1c54376-03ab-410a-aae6-8fa17baa23e0.png)

**Comment by c19850727** [comment]
3rd one emerged in Korea. EPI_ISL_15359945

**Comment by corneliusroemer** [comment]
Designated as XBB.4 (not the Indian sequences as they were too messy).
