### ISSUE TITLE
BN.1 with S:494P [6 seqs, IND, US, DK, AT]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1176]
BN.1 seems to have acquired S:494P in this lineage, all of these 3 sequences also share C28585T so look like they are monophyletic, but one should check Usher:

hCoV-19/Denmark/DCGC-581901/2022|EPI_ISL_15069931|2022-09-15
hCoV-19/India/GJ-INSACOG-GBRC8752/2022|EPI_ISL_15058581|2022-08-09
hCoV-19/USA/IN-CDC-STM-66NUUCW56/2022|EPI_ISL_15024980|2022-09-07

This would be a level 7 variant, similar to XBB in having 7 key RBD mutations compared to BA.2, it's also how I spotted it, using the level 7 collection from covSpectrum.

https://cov-spectrum.org/collections/54

GISAID query: ` Spike_S494P,Spike_K356T, Spike_F490S, Spike_R346T`

**Comment by corneliusroemer** [comment]
Checking on GISAID, there may already be 4 more, all from Austria:

hCoV-19/Austria/Medilab_1292/2022 | Original | EPI_ISL_15269672 | 2022-09-29 | 2022-10-06
hCoV-19/Austria/Medilab_1276/2022 | Original | EPI_ISL_15269658 | 2022-09-25 | 2022-10-06
hCoV-19/Austria/LB-R00104-S190/2022 | Original | EPI_ISL_15259635 | 2022-09-26 | 2022-10-05
hCoV-19/Austria/LB-R00104-S189/2022

**Comment by corneliusroemer** [comment]
The Austrians are the same lineage.

Some even have an extra NTD mutation S:N185D, the full genome sequences also all have C28585T, so seems to be all one lineage.

Worth designating immediately if someone has time before me and Usher is clean.

**Comment by agamedilab** [comment]
Hi @corneliusroemer just to let you know: Both, Medilab and LB (LifeBrain), perform "Random" and "Preselected sampling". In the present case (EPI_ISL_15269672, EPI_ISL_15269658, EPI_ISL_15259635, EPI_ISL_15259634) the samples are derived from "Preselected sampling" (not representative surveillance). In Austria, only IMBA/AGES performs exclusively representative surveillance, however those sequences are almost exclusively spike only (S untill AA839 see https://github.com/cov-lineages/pango-designation/issues/752) and have therefore limited utility for lineage spotting/designation.

**Comment by corneliusroemer** [comment]
Thanks I got that Medilab and IMBA confused!

I think the Spike only are extremly useful as they are fast and representative, but yeah they can't be used to designate on their own. But they help spot interesting things very quickly.

**Comment by FedeGueli** [comment]
Cornelius the gisaid query posted above is wrong one

**Comment by ryhisner** [comment]
Does S494P really deserve to be included in the "key RBD mutations"? I don't think there's any real evidence it provides an advantage. As one eminent phylogenetic expert said when I mentioned that Indiana BN.1 with S494P a couple weeks ago, "They pop up but don't grow much."

**Comment by corneliusroemer** [comment]
Looks like a slight but consistent advantage, having it there doesn't do much harm as long as it's not harmful and it doesn't look like it is. Popping up often -> likely beneficial.

<img width="2334" alt="image" src="https://user-images.githubusercontent.com/25161793/195207577-644d3460-88c3-42e6-8446-44721a0c9d9c.png">

**Comment by corneliusroemer** [comment]
For more just uploaded from Austria:
```
hCoV-19/Austria/LB-R00105-S287/2022|EPI_ISL_15329478|2022-10-04
hCoV-19/Austria/LB-R00105-S314/2022|EPI_ISL_15329506|2022-10-04
hCoV-19/Austria/LB-R00105-S324/2022|EPI_ISL_15329516|2022-10-04
hCoV-19/Austria/LB-R00105-S339/2022|EPI_ISL_15329531|2022-10-04
```

**Comment by FedeGueli** [comment]
Now designated BN.1.1 @corneliusroemer @InfrPopGen milestone missing and issue to close

**Comment by FedeGueli** [comment]
16 sequences. This has been designated and should be closed @thomaspeacock
