### ISSUE TITLE
BN.1 with S:K444R [1 seq, 1xSGP]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1177]
Spotted a BN.1 with S:K444R by using the level 7 query from https://cov-spectrum.org/collections/54

According to a rough fitness metric using ACE2 and RBD immune escape scores from the Bloomlab calculators via Nextclade, this could be one of the fittest lineages around so I open this issue even though it's only a singlet.

We can close if there are no new representatives in 2 weeks.

hCoV-19/Singapore/12200/2022|EPI_ISL_15231879|2022-09-21

GISAID query: `Spike_K444R,Spike_K356T, Spike_F490S, Spike_R346T, Spike_N460K`

**Comment by FedeGueli** [comment]
Put here cause to soon to open another issue, Found a BN.1 with S:V445F from England.

**Comment by InfrPopGen** [comment]
Does appear to be a duplicate of #1163 which was closed as it did not thrive. Consequently, closing this parallel issue also.
