### ISSUE TITLE
Proposal of new BA.4.6 sub-lineage with ORF1ab:A6296V, S:S98F mutations circulating in Peru 

### ISSUE THREAD

**Issue by AliNunz** [cov-lineages/pango-designation#1178]
Description:
Potential BA.4.6 sub-lineage containing ORF1ab:A6296V, S:S98F mutations proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

Sub-linage of: BA.4.6

Earliest sequence: 2022-07-26
hCoV-19/Peru/TUM-INS-26138/2022

Most recent sequence: 2022-09-05
hCoV-19/Peru/LIM-INS-28937/2022

Countries circulating
Peru (9)

Genomes:
[Genomes.csv](https://github.com/cov-lineages/pango-designation/files/9728190/Genomes.csv)

Evidence:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_36e31_f26c60.json?branchLabel=aa%20mutations&c=pango_lineage&label=nuc%20mutations:C8140T,C14599T,G22599C

<img width="2686" alt="imagen" src="https://user-images.githubusercontent.com/115187682/194411389-1b7f3c3f-e436-4298-a69a-e36888f75900.png">

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there appears to be no change since mid-October, this can be closed for now. Please re-propose or request re-opening should this one wake up again in the future.
