### ISSUE TITLE
Sublineage of BA.2.75.4 with S:K444T, S:S446G (Rev), ORF3a:T32I (15 seq on Oct 11)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1179]
### **Description**
**Sub-lineage of:** BA.2.75.4
**Earliest sequence:** 2022-9-22, Canada, Ontario — EPI_ISL_15225511, EPI_ISL_15225558
**Most recent sequence:** 2022-9-28, Australia, Sydney — EPI_ISL_15250336, EPI_ISL_15250314
**Countries circulating:** Canada (3), Australia (2)
**Number of Sequences:** 5
**GISAID Query:** Spike_L452R, Spike_K444T, NS3a_T32I, NSP8_N118S
**CovSpectrum Query:** Nextcladepangolineage:BA.2.75.4 & S:K444T & ORF3a:T32I
**Substitutions on top of BA.2.75.4:**
**Spike:** K444T
**ORF3a:** T32I
**Nucleotide:** G8602A, A22893C, A22898G, C25487T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_1285d_f4cec0%E2%80%94BA.2.75.4%2BK444T%2BS446G%2BORF3aT32I.json 

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/33738461/194426764-ec3c4466-188c-4ca3-83b3-0f23a1d3ef60.png">

**Evidence**
All five sequences are very recent, and the most recent two are thousands of miles away from the first three. The S:S446G reversion might be thought of as a handicap, but we see the same reversion in probably a majority of BA.1* chronic cases, indicating that, like S:Q493R, there are some spike environments in which it is advantageous to drop G446S. BA.2, without G446S, certainly had no problem outperforming BA.1, which had it. 

The L452R and K444T spike mutations, of course, have proven to be highly advantageous. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15225511, EPI_ISL_15225558, EPI_ISL_15225584, EPI_ISL_15250314, EPI_ISL_15250336
</details>

**Comment by corneliusroemer** [comment]
How sure are we about the reversion? Prior usually strongly suggests artefact - is it on a clean branch or not? Looks like the branch could be dirty, seeing how small it appears.

**Comment by ryhisner** [comment]
I feel pretty certain about the reversion. There have been 10 sequences of this branch uploaded from Karnataka in the past few days, and none have G446S. These are not the highest-quality sequences, but 8/10 have coverage at both K444T and L452R. I'm pretty sure at least a few would've found G446S if it were actually there. The odds of all these sequences having K444T and ORF3a:T32I—a combination not seen in any other BA.2.75 sequences—all just happening to register a false reversion in labs in multiple countries are vanishingly small. On the other hand, the S446G reversion is common in chronic infections—it happens in a majority of the chronic BA.1* sequences we see—so we don't have to invoke incredibly long odds to explain its occurrence.

**Comment by corneliusroemer** [comment]
The fact that we see a S:N417K reversion there sort of doesn't make me trust these very much but the fact that we have ORF3a:T32I sounds alright.
