### ISSUE TITLE
New BQ.1 sublineage with S:A260V + ORF1b:I2378V (8 seqs - Germany, England)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1180]
I have spotted a new sublineage  of BQ.1 with S:A260V, this AA substitution is close to some of the mutations known to give some advantageous fitness, so i write an early proposal:
![Schermata 2022-10-07 alle 10 09 01](https://user-images.githubusercontent.com/87669813/194505068-92fa7854-8cdd-4d14-8d61-e11c639c255d.png)
 

5 sequences : 2 England, 3 Germany 

EPI_ISL_15099432
EPI_ISL_15265566
EPI_ISL_15265724
EPI_ISL_15265769
EPI_ISL_15272460

Defining mutations: A11983G, A20599G(orf1b:I2378V) C22341T (S:A260V), C25006T then T6727C

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_399ba_fdf120.json?label=nuc%20mutations:A11983G,A20599G,C22341T,C25006T
![Schermata 2022-10-07 alle 10 44 15](https://user-images.githubusercontent.com/87669813/194512207-1a97174f-4d11-41ac-976f-ad7759a49341.png)

CovSpectrum query: A11983G, C25006T, T6727C + ORF1b:I2378V, S:A260V
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1b%3AI2378V%2CS%3AA260V&nucMutations=A11983G%2CC25006T%2CT6727C&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Gisaid Query: NSp15_I327V,Spike_A260V,NSP12_Y273H

**Comment by FedeGueli** [comment]
1 more sequence from England

**Comment by corneliusroemer** [comment]
@FedeGueli it would be great if you created one single comment that tracks various new BQ.1(.1) diversity proposals (as you can't edit my comment). Thanks!

**Comment by FedeGueli** [comment]
7 seqs as today

**Comment by FedeGueli** [comment]
still 8 viruses . @corneliusroemer i m closing this one, everything suggests to me the 260V mut isnt of any help to BQ.1
