### ISSUE TITLE
BA.2.75.2 sublineage with S:F486P (5 seq., New Zealand)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1181]
Proposal for a sublineage of BA.2.75.2
Earliest sequence: 23.08.2022 (New Zealand)
Countries detected: New Zealand

Defining mutation:
T23018C = S:F486P

This sublineage of BA.2.75.2 is defined by S:F486P and was detected in New Zealand.

![grafik](https://user-images.githubusercontent.com/102166254/194532816-f4d3b1f2-f63d-420d-b73c-8ef12feb2ff8.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c08a_ffcbd0.json?branchLabel=aa%20mutations&c=gt-S_486&label=nuc%20mutations:G3250T,T23018C

EPI_ISL_15277569, EPI_ISL_15277680, EPI_ISL_15277789,
EPI_ISL_15277794, EPI_ISL_15277796

**Comment by cvejris** [comment]
This is interesting - the 486S present in multiple BA.2.75 sublineages is mutating further into proline. 486S considerably decrases ACE2 binding, so its convergent replacement makes sense. It also explains why BA.2.10.4 already had F486P when discovered.

**Comment by agamedilab** [comment]
I would be very happy if a milestone & designate label (CA.4) could be added to the issue. Many thanks! @InfrPopGen @corneliusroemer 

![grafik](https://user-images.githubusercontent.com/102166254/200871230-e9f75e4c-b4eb-4bc2-bacd-6cb0dfb0ea28.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_f326_bc30d0.json?c=pango_lineage_usher

![grafik](https://user-images.githubusercontent.com/102166254/200870970-be208e40-ff9c-496c-842a-db11512f1f67.png)
