### ISSUE TITLE
BY.1 sublineage with S:S494P, ORF1a:G101V (8 seq., Austria)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1184]
Proposal for a sublineage of BY.1
Earliest sequence: 19.09.2022 (Austria)
Countries detected: Austria

Defining mutation:
T23042C = S:S494P
G567T = ORF1a:G101V
G12797A = ORF1ab:G4178S
G370T
G26828T

This sublineage of BY.1 is defined by S:S494P and was detected in Austria.

![grafik](https://user-images.githubusercontent.com/102166254/194569698-d294ef65-bb74-4314-b54b-ac099f6c970f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c142_29590.json?branchLabel=aa%20mutations&c=gt-nuc_23042&label=nuc%20mutations:G26828T

EPI_ISL_15153792
EPI_ISL_15153823
EPI_ISL_15153829
EPI_ISL_15153830
EPI_ISL_15259734
EPI_ISL_15259735
EPI_ISL_15259736
EPI_ISL_15259738

**Comment by corneliusroemer** [comment]
There are 3 or more independent lineages with this type of Spike now:
BA.2.75.2
BY.1
BM.1.1 all have S:346T, S:486S and then got S:494P

In total around 40 now.

**Comment by agamedilab** [comment]
I would be very happy if a designate label and milestone could be added to the issue (BY.1.2, BY.1.2.1). Many thanks! @corneliusroemer @InfrPopGen 
![grafik](https://user-images.githubusercontent.com/102166254/197334330-614c4a89-6363-4bd2-b591-d16e7ccc729c.png)
