### ISSUE TITLE
Sublineage of BY.1 with S:L452R, S:N185D, S:H207R, Austria, Spain, Switzerland, Germany [40 seqs]

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1186]
Note: BY.1 is BA.2.75 + S:346T + S:486S

**Description**
Sub-lineage of: BY.1
Earliest sequence: 2022-9-13, Austria — EPI_ISL_15057709
Most recent sequence: 2022-9-28, Austria — EPI_ISL_15259731
Countries circulating: Austria, 3. Spain, 1. Switzerland, 1.
Number of Sequences: 5
GISAID Query: Spike_L452R, Spike_N185D, Spike_H207R
CovSpectrum Query: S:452R, S:185D, S:207R
Substitutions on top of BY.1
Spike: S452R, S185D, S207R
ORF1A: A2912S, K2771R
Nucleotide: T22917G,G7071T,G8999T,A8577G,A22182G,A22115G,A1034G

**Usher Tree**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f94f_3d2b0.json?label=nuc%20mutations:T22917G

![image](https://user-images.githubusercontent.com/94097102/194588873-6a71970c-eb0f-41e8-b4b0-a1e3439ddf2a.png)

**Additional Comment**
It looks to me like this branch is probably separate from the other BY.1 + S:452R branch in the photo. Right now it seems that my proposed branch obtained all 5 AA mutations in a single step, although that might change as more sequences come in. 

**Genomes**: EPI_ISL_15259731, EPI_ISL_15232882, EPI_ISL_15153816, EPI_ISL_15074530, EPI_ISL_15057709

**Comment by shay671** [comment]
With EPI_ISL_15263678, They are six now.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36cdb_58ad90.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T22917G

Samples are from 4 countries (Austria, Switzerland, Germany, and Spain) 
Besides the L452R in the base, the four mutations in this branch do not seem to converge to anything before, But those are 4/4 Nonsynonymous with 2 in the NTD. 

There is apparent variation between the samples, including two steps in Austria, which indicates that this lineage is undersampled.

From my point of view,  this looks like a variant to get a designation as soon as it gets 2-3 more seq.   

But - if this one gets designated, its mediator from BY.1, which include L452R, should probably get a designation as well.

@corneliusroemer

**Comment by agamedilab** [comment]
![grafik](https://user-images.githubusercontent.com/102166254/195283111-e117028a-d5f8-4502-b381-c56f44e43754.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_723b_66daa0.json?branchLabel=aa%20mutations&c=gt-S_185

![grafik](https://user-images.githubusercontent.com/102166254/195283491-37f03144-e3e8-410c-b2d3-732e1cb1bb24.png)

OX338888.1
EPI_ISL_15074530
EPI_ISL_15263678
EPI_ISL_15329527
EPI_ISL_15232882
EPI_ISL_15057709
EPI_ISL_15259731
EPI_ISL_15153816

8 seq as of 12.10.22.

**Comment by shay671** [comment]
@agamedilab
Does EPI_ISL_15074530 different than EPI_ISL_15074530 ?

**Comment by corneliusroemer** [comment]
Thanks @agamedilab - let's wait maybe a week more, but this looks like it could get a designation soon.

**Comment by agamedilab** [comment]
@shay671 many thanks for pointing this out!  Apparently OX338888.1is the same sample than EPI_ISL_15074530 but submitted to NCBI.

**Comment by Sinickle** [comment]
I don't think it makes sense to designate BY.1 with just S:452R. I don't think there's a strong argument that S:452R was the first mutation acquired. We know that S:452R will be very convergent, so it would make sense for different branches to acquire it. Possibly that other branch obtained M:3N -> S:452R. 

I don't think it's so likely that all 5 aa mutations were obtained at once, but I believe that's what we are seeing from our 7 sequences so far.

**Comment by Sinickle** [comment]
Oh, this has been designated BY.1.1.1. 

Can this receive the tag and then be closed?
