### ISSUE TITLE
BA.5.1.29 sublineage with S:K150E, S:460K, Orf8:F41C (18 Sequences: Russia, Israel, Denmark, Germany, England, Czechia, South Korea, Turkey)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1187]
Following the suggestion of @InfrPopGen in #1060 from which  BA.5.1.29 has been designated.
I further propose a  BA.5.1.29 sublineage of interest (BQ.1-like) defined by
nuc C9226T
and then S:K150E, S:N460K, Orf8:F41C 

<img width="1154" alt="Schermata 2022-10-07 alle 17 51 32" src="https://user-images.githubusercontent.com/87669813/194595755-68181dc6-7963-4fbf-abbd-77709bc8479f.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_f40a_4a830.json?branchLabel=aa%20mutations&label=nuc%20mutations:G22894T
It counts now 14 sequences steadily growing and spreading to new countries , likely emerged in Russia .

List of sequences:
EPI_ISL_14921441
EPI_ISL_14921659
EPI_ISL_15018341
EPI_ISL_15018405
EPI_ISL_15147298
EPI_ISL_15173613
EPI_ISL_15208263
EPI_ISL_15209791
EPI_ISL_15265243
EPI_ISL_15267788
EPI_ISL_15281076
EPI_ISL_15283081
EPI_ISL_15283798
EPI_ISL_15283896

Gisaid Query: Spike_K444N,Spike_N460K,N_A218S
CovSpectrum Query: BA.5.1 (Nextclade) + A16541G + N:A218S, S:K444N, S:N460K, S:K150E
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=N%3AA218S%2CS%3A444N%2CS%3AN460K%2CS%3Ak150E&nucMutations=A16541G&nextcladePangoLineage=BA.5.1&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

**Comment by FedeGueli** [comment]
2 new sequences from Turkey

**Comment by FedeGueli** [comment]
Two new sequences one from Denmark, one from Russia. It is going i reccomend a fast designation of it .
Also to remember it has the same Nuc change ( T22942A) for S:N460K  as BQ.1.

**Comment by c19850727** [comment]
@FedeGueli the 2 new sequences from Turkey have additional M_I82T and ORF1a:P3371S (a NSP5 change).

**Comment by FedeGueli** [comment]
24 SEQUENCES AS TODAY .
Some S:H49Y or S:V71F  diversity spotted. i ll go on monitoring this one.
