### ISSUE TITLE
BQ.1 sublineage with S:H146L and Orf1a:E352A spreading in Italy (31 Sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1189]
Here i want to propose a sublineage of BQ.1 defined by S:H146L

Defining mutations:
BQ.1 + C27600T then  C3040T then Orf1a:E352A (A1320C)  then S:H164L (A21999T)

tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_332c8_94250.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C27600T
![Schermata 2022-10-07 alle 23 12 56](https://user-images.githubusercontent.com/87669813/194653207-0ca010d3-3a4d-45e6-b37b-0be5787dbebe.png)

 

Gisaid Query: Spike_H146L, NSP12_Y273H, Spike_K444T, Spike_N460K
CovSpectrum Query : C27600T + ORF1a:E352A, S:H164L
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1a%3AE352A%2CS%3AH164L&nucMutations=C27600T&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

List of sequences:

EPI_ISL_15206578
EPI_ISL_15206797
EPI_ISL_15210634
EPI_ISL_15210635
EPI_ISL_15210638
EPI_ISL_15210639
EPI_ISL_15210644
EPI_ISL_15210645
EPI_ISL_15210646
EPI_ISL_15210647
EPI_ISL_15210648
EPI_ISL_15210651
EPI_ISL_15210652
EPI_ISL_15210654
EPI_ISL_15232568
EPI_ISL_15262480
EPI_ISL_15272093
EPI_ISL_15284177

Countries:
Italy, Denmark, England

**Comment by FedeGueli** [comment]
3 new sequences of this one from Denmark

**Comment by corneliusroemer** [comment]
Hmm, not really clean on Usher. Let's see whether this is maybe an artefact

**Comment by AngieHinrichs** [comment]
> Hmm, not really clean on Usher.

It doesn't look that bad to me.  Here's BQ.1 in the 2022-10-05 tree in taxonium, colored by S:146:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/186983/195165056-abf015ac-6669-4b64-89ee-d7a74bba4e3b.png">
That little pink blip is the cluster.  Zooming in:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/186983/195165246-ce49490c-3a8f-4309-8fee-6d7e0f56736c.png">
OK, there's a little disagreement over A1320C (ORF1a:E352A), but I've seen worse.  Is it looking a lot worse in the version of the tree that you're looking at?  Or are you starting with a covspectrum query of a few mutations, and the sequences are landing all over BA.5 or something?

**Comment by FedeGueli** [comment]
@AngieHinrichs @corneliusroemer i dont think it is an artefact let see if some other sequences from new labs will pop up

**Comment by cvejris** [comment]
Today USA 1x, Canada 1x. Both are baseline surveillance samples. It appears this sublineage has potential

**Comment by corneliusroemer** [comment]
This is now a BQ.1.10 sublineage, I'll designate it as BQ.1.10.1

**Comment by FedeGueli** [comment]
Hi Cornelius BQ.1.10 starts with?

**Comment by corneliusroemer** [comment]
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/25161793/195892347-dbdf7977-2809-4842-9fb3-8633569e96a5.png">

**Comment by corneliusroemer** [comment]
Designated as BQ.1.10.1

**Comment by FedeGueli** [comment]
thx!
