### ISSUE TITLE
Easily parseable parent-child relationships between lineages

### ISSUE THREAD

**Issue by matthuska** [cov-lineages/pango-designation#119]
I see that on cov-lineages.org, parent and child lineages for each pango lineage are clearly indicated. That is useful for one-off checks, but for automated analysis it would be useful to have a computer readable table or data structure containing this information. Something like a .tsv file with two columns, "parent" and "child", would suffice. Something like this must already exist for the generation of the cov-lineage.org page, so maybe I just need to be pointed to the right repo/file.

**Comment by aineniamh** [comment]
Is this what you're looking for? https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.json
It's what we use for the website parent/ child generation.

**Comment by matthuska** [comment]
Yes that should do the trick, thanks :)
