### ISSUE TITLE
Sublineage of BA.2.75.5 with S:R346S, ORF1a:K1795R (42 seq., 7 countries)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1194]
Proposal for a sublineage of BA.2.75.5
Earliest sequence: 28.09.2022 (England)
Countries detected: India (8), Singapore (3), USA (2), England (1)

Defining mutations:
A5649G = ORF1a:K1795R
A22600T = S:R346S

This sublineage of BA.2.75.5 is defined by S:R346S and was first detected in England. This issue is distinct from #1105.

![grafik](https://user-images.githubusercontent.com/102166254/194756850-52325b42-387a-4554-a42c-e949a800069f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1bfad_2b9a10.json?branchLabel=aa%20mutations&c=pango_lineage_usher

England/PHEP-YYFA7AH/2022

EPI_ISL_14599111
EPI_ISL_14599120
EPI_ISL_14910819
EPI_ISL_15031287
EPI_ISL_15031287
EPI_ISL_15146793
EPI_ISL_15146794
EPI_ISL_15146795
EPI_ISL_15146796
EPI_ISL_15200863
EPI_ISL_15213641
EPI_ISL_15213734
EPI_ISL_15213767
EPI_ISL_15231847

**Comment by agamedilab** [comment]
42 seq as of 09.11.2022. Alternatively one could designate from node N:G34E (= 60 seq.)

![grafik](https://user-images.githubusercontent.com/102166254/200865279-21c35100-7161-4c46-b8b6-347252f8b777.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8001_bc00a0.json?c=gt-N_34

**Comment by ryhisner** [comment]
Several interesting sub-branches in this one, including one with ORF3a:T229I and ORF1a:K3839R (NSP6_K270R), another with S:V622A in the USA, another with the convergent ORF1a mutation T4175I, and a single sequence with S:F490S + ORF1a:M4241V (NSP9_M101V). It's also very widespread geographically, with sequences from India, Japan, Singapore (local cases), Germany, England, Canada, and four different US states.

**Comment by InfrPopGen** [comment]
Thank you for submitting this lineage proposal. As there were only slight growth advantages apparent in November, and these are now negative across the board (India, UK (3%) and US) over the past three months, this proposal can be closed for now. Please feel free to re-propose or request re-opening should this lineage show marked advantages in the future.
