### ISSUE TITLE
BA.4.6 + Orf1a: G963C + S:K444N +S:N460K 5 sequences Us, Canada, Australia, Turkey

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1195]
[Level 6, BQ.1.1 lookalike but from BA.4 base] 

Here i want to propose this lineage spotted along with : @josetteshoenma and Marc Johnson

EPI_ISL_14789096, EPI_ISL_15227017, EPI_ISL_15250517,
EPI_ISL_15278924, EPI_ISL_15287317
![Schermata 2022-10-09 alle 15 42 44](https://user-images.githubusercontent.com/87669813/194760232-6e6b5d23-ec8c-4801-a0be-24b3e50fb2b4.png)

Defining mutations: Orf1a:G963C (G3152T) then S:K444N and S:N460K
![Schermata 2022-10-09 alle 15 48 08](https://user-images.githubusercontent.com/87669813/194760468-e1a395fe-18dc-4eda-9b6d-33356d19b511.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1af3c_2d0540.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G3152T

Gisaid Query : NSP3_G145C,N_P151S,Spike_N460K,Spike_K444N,Spike_R346T
CovSpectrum query : ORF1a:G963C, S:K444N, S:N460K

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1a%3AG963C%2CS%3AK444N%2CS%3AN460K&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

To be noticed that the sequence from turkey has two additional Spike mutations: S:I770V, S:L864S unique to that sequence.

**Comment by Mydtlwn** [comment]
Has the Orf1a:G963C mutation appeared before? mutation appeared before?

**Comment by Mydtlwn** [comment]
Has the Orf1a:G963C mutation appeared before?

**Comment by FedeGueli** [comment]
> Has the Orf1a:G963C mutation appeared before?
yes multiple times:
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=Orf1a%3AG963C&

**Comment by Mydtlwn** [comment]
thx

**Comment by corneliusroemer** [comment]
If they have S:144- that could help them compensate for BA.4 base badness compared to BA.5 - thanks @Sinickle for noticing.

Given broad global spread this is worth designating, if we can figure out where to start it and it's clean.

**Comment by FedeGueli** [comment]
@corneliusroemer @thomasppeacock @InfrPopGen @AngieHinrichs  i want to flag u here that today a BA.4.6.3 sequence was uploaded in uk with a NTD mutation known to give some extra boost in growth advantage : **EPI_ISL_15365449** with **S:248S**
