### ISSUE TITLE
Lineage Notes Potential Issue

### ISSUE THREAD

**Issue by ciscorucinski** [cov-lineages/pango-designation#1197]
`CE.1	Alias of B.1.1.529.5.2.33, UK lineage, defined by S:R346I`. This I believe should be `B.1.1.529.5.2.33.1`

https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt

**Comment by ciscorucinski** [comment]
`BH.1	Alias of B.1.1.529.2.38.3.1, mainly found in India, from pango-designation issue #913` (Line 708) is in the wrong location in the file. It is grouped wrong. 

It should be right beneath `BA.2.38.3	Alias of B.1.1.529.2.38.3, mainly found in India, from pango-designation issue #840` (Line 743)

**Comment by corneliusroemer** [comment]
You may well be right, it's possible I messed this up as this is a simple text document that is for human consumption only.

**Comment by ciscorucinski** [comment]
Thanks for the fix. I only found it because I'm using it as an API

**Comment by corneliusroemer** [comment]
If you have something that finds these kinds of errors automatically, feel free to propose it as an addition to our CI checks.

I'd love to look at a PR of yours :)

**Comment by ciscorucinski** [comment]
`BE.4.1.1	Alias of B.1.1.529.5.3.1.4.1, Bangladesh, defined by S:K444R, from issue #1115` is mis-aliased. It has the same alias as `BE.4.1`, so I believe it should end with an additional `.1`

`CQ.1	Alias of B.1.1.529.5.3.1.4.1.1, Bangladesh, defined by S:Y144- and 11866T` will have the same issue with a mis-alias with `BE.4.1.1`'s fix. I believe it will need to end with an additional `.1`

**Comment by ciscorucinski** [comment]
> If you have something that finds these kinds of errors automatically, feel free to propose it as an addition to our CI checks.
> 
> I'd love to look at a PR of yours :)

I am using Google Docs and ObservableHQ to create a pipeline from your document to an Observable Plot.Tree object. When there are issues, Observable will throw an error and not create a tree plot. From there I can look at the lineage notes document for the issue. So, I can't directly translate it to a CI check yet. Also, I haven't done CI before, can you point me to where to start looking at whether I can implement a CI check for your project. It seems like you use BASH. Looks like I'd have to review [GitHub Actions + CI](https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration) documentation
