### ISSUE TITLE
BA.4.6 sublineage with S:V445A, ORF1a:D1323G (29 seq., Dominican Republic, USA)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1198]
Proposal for a sublineage of BA.4.6
Earliest sequence: 11.08.2022 (Dominican Republic)
Countries detected: USA (18), Dominican Republic (11) 

T22896C = S:V445A
A4233G = ORF1a:D1323G

This sublineage of BA.4.6 is defined by S:V445A, ORF1a:D1323G and was first detected in the Dominican Republic and the USA.

![grafik](https://user-images.githubusercontent.com/102166254/194822326-bb2eab58-592b-4468-b743-7a533e793e34.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_c818_3be450.json?branchLabel=aa%20mutations&c=gt-S_445&label=nuc%20mutations:A4233G

![grafik](https://user-images.githubusercontent.com/102166254/194823004-87055284-9cfa-42b9-8335-5b5c3121ada9.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AV445A&nucMutations=A4233G&nextcladePangoLineage=BA.4.6*&aaMutations1=Orf3a%3AH78Y&pangoLineage1=BA.2*&

EPI_ISL_14614301
EPI_ISL_14805807
EPI_ISL_15105985
EPI_ISL_15146564
EPI_ISL_15146568
EPI_ISL_15164585
EPI_ISL_15164596
EPI_ISL_15164608
EPI_ISL_15164647
EPI_ISL_15205767
EPI_ISL_15205919
EPI_ISL_15205936
EPI_ISL_15206001
EPI_ISL_15226157
EPI_ISL_15256123
EPI_ISL_15256124
EPI_ISL_15256126
EPI_ISL_15296659
EPI_ISL_15296840
EPI_ISL_15296985
EPI_ISL_15297952
OP437357.1
OP504141.1
OP544795.1
OP552321.1
OP552514.1
OP569991.1
OP582730.1
OP589927.1

**Comment by corneliusroemer** [comment]
Thanks, good proposal because despite being probably not competitive with BQ.1.1 and co, it seems to have significant share in an undersampled region.

**Comment by agamedilab** [comment]
I would be very happy if a designate label could be added to the issue. many thanks! @corneliusroemer @InfrPopGen
