### ISSUE TITLE
 pango-designation/ pangolin-data v1.15.1not updatable

### ISSUE THREAD

**Issue by MantaRay87** [cov-lineages/pango-designation#1199]
when performing `pangolin --update` we still only get `pangolin-data already latest release (v1.14)`

Mayor update and new installation also just give us v.1.14.

We are also not sure if "pangolin-data" is "pango-designation" or if there is a trick for the update. 

In the past it always worked fine with` pangolin --update.`

**Comment by aineniamh** [comment]
We haven't tagged a new pangolin data release yet, the latest one is still 1.14. Will tag it later today, just giving GISAID the time to update prior to tagging the release

**Comment by aineniamh** [comment]
You can see the latest releases here https://github.com/cov-lineages/pangolin-data/releases

**Comment by MantaRay87** [comment]
Thanks for the feedback. We did not realize that these are two different/ parallel things. Now it worked like a charm :) 

Thanks also for the great work in keeping the software up and running and up to date in general! Highly appreciated :)
