### ISSUE TITLE
Potential new lineage in France

### ISSUE THREAD

**Issue by Simon-LoriereLab** [cov-lineages/pango-designation#12]
Potential new lineage in France

by Etienne Simon-Loriere 
Description: 

Sub-lineage of: A
Earliest sequence: 2020-12-22 (Oman)
Most recent sequence: 2021-02-02 (France)
Countries circulating: France at least, Spain?

This hospital based cluster was noted because of a spike of cases. We note 9 changes on this branch, including the 69-70del, N501T (not Y) and H655Y. (This variant is picked up by the qPCR S drop).  More sequencing is underway to follow up. A Pango lineage designation would help exchanges.

Genomes
[cluster_19B_IDF.txt](https://github.com/cov-lineages/pango-designation/files/5975513/cluster_19B_IDF.txt)

Evidence

![Screenshot_2021-02-13 auspice us](https://user-images.githubusercontent.com/60473383/107848256-3a25c880-6df2-11eb-918d-66d66e066dcb.png)

**Comment by rambaut** [comment]
Thanks Etienne - this looks interesting. Can you provide a tree graphic with tip labels?

**Comment by Simon-LoriereLab** [comment]
Hi Andrew, thanks for looking into this!
Here is the same subtree:
[19B_clusters_Mayotte_IDF.pdf](https://github.com/cov-lineages/pango-designation/files/5975695/19B_clusters_Mayotte_IDF.pdf)

[19B_clusters_Mayotte_IDF.nex.txt](https://github.com/cov-lineages/pango-designation/files/5975697/19B_clusters_Mayotte_IDF.nex.txt)

**Comment by aineniamh** [comment]
New lineage tagged as A.28, apologies for the short delay! 

https://github.com/cov-lineages/pango-designation/releases/tag/v1.0.5

**Comment by aineniamh** [comment]
Newly trained pangoLEARN model available now (tag: [2021-01-18](https://github.com/cov-lineages/pangoLEARN/releases/tag/2021-02-18))
