### ISSUE TITLE
Apparent B.617.2 sample assigned to B.1.404

### ISSUE THREAD

**Issue by jornhell** [cov-lineages/pango-designation#120]
Sequence checks all the boxes for being designated to B.617.2 lineage but B.1.404 is called. 

S-gene mutations: 
T19R
G142D
R158G
L452R
T478K
D614G
P681R
D950N
E156-,
F157-

Sequence
[B16172 or B1404.txt](https://github.com/cov-lineages/pango-designation/files/6692997/B16172.or.B1404.txt)
 (in .TXT format) in attachment.

**Comment by aineniamh** [comment]
I've just run your sequnce through pangolin and get:
```
taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,version,pangolin_version,pangoLEARN_version,pango_version,status,note
read_mapping_COV-4362683_S15_L001_(paired)_MN908947.3_consensus,B.1.617.2,0.0,0.9780509559080157,Delta (B.1.617.2-like),1.000000,0.000000,PLEARN-v1.2.13,3.1.4,2021-06-15,v1.2.13,passed_qc,scorpio call: Alt alleles 12; Ref alleles 0; Amb alleles 0; scorpio replaced lineage assignment B.1.404
```

**Comment by jornhell** [comment]
Dear Aine, 

I am using the webtool. 

"scorpio replaced lineage assignment B.1.404"
Does this mean Scorpio replaced B.1.404 by B.617.2 or the other way around? 

Thanks for the response.

**Comment by aineniamh** [comment]
It means the final lineage call is B.1.617.2- based on SNPs scorpio overwrote the pangoLEARN call.

**Comment by aineniamh** [comment]
Thanks @jornhell, going to close this now!
