### ISSUE TITLE
Sublineage of BF.10 with S:W64C, S:R346T (40 seq, all USA)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1200]
**Description**
**Sub-lineage of:** BF.10
**Earliest sequence:** 2022-7-20, USA, New York, Monroe County — EPI_ISL_14444839, EPI_ISL_14444848
**Most recent sequence:** 2022-9-27, USA, North Carolina, Pitt County — EPI_ISL_15255140
**Countries circulating:** USA (40)
**Number of Sequences:** 40
**GISAID Query:** NSP13_A368V, Spike_R346T, Spike_W64C
**CovSpectrum Query:** Nextcladepangolineage:BF.10* & S:W64C & C9967T
**Substitutions on top of BF.10:** 
**Spike:** W64C, R346T
**Nucleotide:** C9967T, G12442A, C20703T, G21754T, G22599C
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BF.10%2BW64C%2BR346T%E2%80%94subtreeAuspice1_genome_6366_35a3d0.json

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/33738461/194841662-bc97991f-93fe-4262-be47-9b8b5ba1eada.png">

**Evidence**
S:R346T mutation speaks for itself. We’ve seen S:W64 mutations fairly frequently, but usually it’s W64R or W64L. Of the S:W64 mutations in 2022 thus far, 70.8% have been W64R, 25.6% W64L, and 2.8% W64C (the balance being the clearly artifactual W64*). 

<img width="966" alt="image" src="https://user-images.githubusercontent.com/33738461/194841557-f8200cdd-c2ce-45d6-bafb-bb4d7fc98d8d.png">

In the past two months, however, 16.6% of W64 mutations have been W64C, which is due pretty much entirely to this proposed sublineage. 

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/33738461/194841265-7e8bbc25-5d7f-486a-bb32-1217238e5e0a.png">

The only lineage ever to have had W64C in a majority of sequences was U.2, a sublineage of B.1.177.60 found mainly in Denmark and Lithuania from November 2020 to February 2021. 

28 of the 40 sequences in the lineage so far have collection dates in September, so it seems to be growing fairly quickly and is widespread throughout the United States. It doesn’t appear to be especially concentrated in any particular area. I don't know if it will be able to get off the ground before the BQ.1*/BA.2.3.20/BA.2.75*/XBB wave flattens it, however. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_14293977, EPI_ISL_14330354, EPI_ISL_14444839, EPI_ISL_14444848, EPI_ISL_14501103, EPI_ISL_14649670, EPI_ISL_14649744, EPI_ISL_14775442, EPI_ISL_14833097, EPI_ISL_14909945, EPI_ISL_14987551, EPI_ISL_15001375, EPI_ISL_15001649, EPI_ISL_15001701, EPI_ISL_15053905, EPI_ISL_15060224, EPI_ISL_15060805, EPI_ISL_15063959, EPI_ISL_15113774, EPI_ISL_15122896, EPI_ISL_15142184, EPI_ISL_15144286, EPI_ISL_15144438, EPI_ISL_15159155, EPI_ISL_15161112, EPI_ISL_15179448, EPI_ISL_15179858, EPI_ISL_15183871, EPI_ISL_15204590, EPI_ISL_15205832, EPI_ISL_15205859, EPI_ISL_15220590, EPI_ISL_15220759, EPI_ISL_15221954, EPI_ISL_15241608, EPI_ISL_15249999, EPI_ISL_15255140, EPI_ISL_15260296, EPI_ISL_15268385, EPI_ISL_15271078
</details>

**Comment by corneliusroemer** [comment]
BF.10 is level 3 so this one is low priority for now (this lineage proposal would "just" be a level 4)

**Comment by AngieHinrichs** [comment]
What are these levels and how are they defined?

**Comment by ryhisner** [comment]
I'll close, and if it shows rapid growth or additional mutations, we can always reopen.

**Comment by corneliusroemer** [comment]
@AngieHinrichs the levels are numbers of key RBD mutations on top of BA.2.

They very strongly correlate with growth advantage - as in, all the fastest growing lineages are at least level 5.

https://cov-spectrum.org/collections/54

These are the mutations at the moment, but the details can change in the future.

S:346, S:356, S:444, S:445, S:450, S:446, S:452, S:460, S:486, S:490, S:494, S:493Q

**Comment by FedeGueli** [comment]
This reached 76 sequences as today @ryhisner maybe this could be kept open for a while. Low priority doesnt mean it wont be designated.

**Comment by Mydtlwn** [comment]
Are there any other fast-growing strains in BF.10? Including those that have not been taken seriously before!
