### ISSUE TITLE
Collection of XBB Spike diversity

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1201]
XBB:
- [x] S:253G (10 seqs), very similar to XBB.1 defining S:252V, https://github.com/cov-lineages/pango-designation/issues/1173
- [ ] S:146K, 4 seqs, 4 continents (potentially artefact, very homoplasic)
- [ ] S:640P (3x Austria)
- [x] S:A653V (5x India, Australia, Singapore)
- [x] #1241

XBB.1:
- [ ] S:S708T, 
- [ ] S:T236A (1xSingapore)
- [ ] S:N30K (1x singapore)
- [ ] S:P85S (1x singapore)
- [ ] S:A263T (1x singapore)
- [x] S:484T (1x Italy)
- [x] S:640F (4x Singapore)
- [ ] S:883T (3x, Italy, Singapore, Belgium)
- [ ] S:845S (2x Austria/Switzerland)

XBB:
- [x] #1239

**Comment by FedeGueli** [comment]
I spotted one XBB.1 from Japan via traveller from Saudi Arabi with S:S708Tand one XBB.1 sequence with S:T236A (Singapore)

**Comment by Sinickle** [comment]
Regular XBB with S:Q677R, 13 sequences, concentrated in Singapore, but comes from India.

**Comment by FedeGueli** [comment]
XBB.2 with Spike_N764R 2 sequences Australia and Germany ( i think monophyletic but i will check in case it will show up again) Being S:N764K one of the defining S2 of Omicron i think it is interesting to monitor it although from K to R wont be a big difference, right @thomaspeacock ?

**Comment by ryhisner** [comment]
• ∆241-247,  XBB.1.1 uploaded today, collected Oct 14. Local case from Singapore. 
EPI_ISL_15452755

• A484T, 2 sequences; one Belgium (w/much missing coverage) & one Italy. Not clear if they're monophyletic or not. 
EPI_ISL_15333931, EPI_ISL_15455499

**Comment by ryhisner** [comment]
Usher thinks the Belgian & Italian A484T's are closely related. Take away the fake reversions from the Belgian sequence (which are due to bad coverage) and they are in fact very similar. The shared ORF1a:P2287S seems to be the clincher. 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/33738461/197298306-008b3a47-5e0f-40af-8b49-9a736cd6c8a9.png">

**Comment by ryhisner** [comment]
Four more XBB + S:A484T today from West Bengal. One of them also has S:G476S.

EPI_ISL_15465690, EPI_ISL_15465702, EPI_ISL_15465706, EPI_ISL_15465716

**Comment by cvejris** [comment]
By ORF1a:P2287S, 5/6 are monophyletic. Given the international spread and obvious consequences of mutations at S:484, I think this should be designated right away.

**Comment by corneliusroemer** [comment]
@ryhisner 4 more today from India-TN, so I designated the XBB.1 + S:A484T as XBB.1.3

**Comment by Mydtlwn** [comment]
What is the growth rate of XBB+640P?
