### ISSUE TITLE
Sublineage of BA.5.2 (ORF1b:T1050N) with S:K444T, S:K356T (8 seq) + wider S:K444T lineage (~25 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1203]
### **Description (for K444T + K356T)**
**Sub-lineage of:** BA.5.2
**Earliest sequence:** 2022-8-7, Japan — EPI_ISL_14875680
**Most recent sequence:** 2022-9-25, England — EPI_ISL_15303416
**Countries circulating:** USA (5), Japan (2), England (1)
**Number of Sequences:** 8 (about 25 in the wider K444T lineage)
**GISAID Query:** Spike_K444T, Spike_K356T, NSP13_T127N
**CovSpectrum Query for K356T Lineage:** Nextcladepangolineage:BA.5.2* & ORF1b:T1050N & S:K356T & S:K444T & !C1471T & !T2698C & !A29700G
**CovSpectrum Query for Wider Lineage:** Nextcladepangolineage:BA.5.2* & ORF1b:T1050N & S:K444T & !C1471T & !T2698C & !A29700G
**Substitutions on top of BA.5.2 + ORF1b:T1050N:**
**Spike:** K356T, K444T
**Nucleotide:** A22629C, A22893C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.5.2%2BK444T%2BK356T(not_BA.5.2.25)%E2%80%94subtreeAuspice1_genome_34680_47cea0.json 

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/33738461/194954010-12b1d6ce-9262-4e2a-b5e4-757e95397463.png">

**Evidence**
First, this is not BA.5.2.25. It lacks the nucleotide mutations C1471T, T2698C, & A29700G found in that lineage. Unfortunately, there seem to be no nucleotide mutations found in the K444T branch here that are not found in BA.5.2.25. 

I don’t believe there’s been a designated lineage with K356T and K444T, though I could be wrong about that. Both are among the most potent escape mutations. It’s already found a foothold in three different continents, with sequences in Japan, England, and USA. 

The wider lineage here (without K356T) includes a 14-sequence branch—all from England—with ORF1a:M2719V, ORF1b:M2322I, and ORF8:A51V. All 14 have collection dates in September. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_14819554, EPI_ISL_14875680, EPI_ISL_15016055, EPI_ISL_15016077, EPI_ISL_15237117, EPI_ISL_15296822, EPI_ISL_15296925, EPI_ISL_15303416
</details>

**Comment by ryhisner** [comment]
So...did these two lineages get designated? I can't find any duplicate proposals for it, but I'm looking at the Usher tree, and these two lineages are labeled BA.5.2.36 and CT.1. 
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/33738461/197618956-2c15c983-f8e6-432d-b01e-f6060ceb287c.png">

**Comment by corneliusroemer** [comment]
Added as BA.5.2.36 and CT.1
