### ISSUE TITLE
BF.7 with S:T883I (C24210T) in Belgium, The Netherlands, Germany and other countries (108 sequences)

### ISSUE THREAD

**Issue by geertmartens** [cov-lineages/pango-designation#1205]
BF.7 (BA.5.2.1 with S:R346T) has a high prevalence in Belgium above 25% today. At AZ Delta Hospital, Roeselare, Belgium, we notice a possible sublineage of BF.7 forming characterized only by the additional S:T883I (C24210T) mutation. As compared to other BF.7 strains currently circulating, this BF.7 with S:T883I as a group also appears to have a lower variety of mutations in the ORF1a and ORF1b than BF.7 isolates without S:T883I. 

First sequence identified in Roeselare, Belgium on 20/08/2022. Possibly earlier, before designation of BF.7. To date, on covSPECTRUM 44 sequences in Belgium, 108 world wide classified as BF.7*+S:T883I

Might be a trivial observation since the S:T883I mutation has previously appeared in other SARS-CoV-2 variants. 

Illustrative sequences: 
EPI_ISL_15309551
EPI_ISL_15309499
EPI_ISL_15309571
EPI_ISL_15309581
EPI_ISL_15309601
EPI_ISL_15309618
EPI_ISL_15222957
EPI_ISL_15223010
EPI_ISL_15182362
EPI_ISL_15057825
EPI_ISL_14760484

**Comment by corneliusroemer** [comment]
I've designated this now.
