### ISSUE TITLE
B.1.617.2 sub-lineage with ORF1a: I3731V

### ISSUE THREAD

**Issue by zach-hensel** [cov-lineages/pango-designation#121]
## B.1.617.2 sub-lineage with ORF1a: I3731V
Zach Hensel
### Description
**Sub-lineage of**: B.1.617.2

**Earliest sequence**: 23 April, 2021 Illinois, USA (searched for N:G215C, ORF1a:T3646A, ORF1a:I3731V on LANL analysis pipeline)
	EPI_ISL_2040338
	EPI_ISL_2254398

**Most recent sequence**: 23 June, 2021 (outbreak.info)

**Countries circulating**: USA (245; most in Missouri, Kansas and Mississippi), UK (1) as of 28/June/2021 (outbreak.info)

**Defined by**: ORF1a:I3731V and common AY.1 mutations except for S:K417N. Combination of ORF1a:T3646A and ORF1a:I3731V.

**Potential significance**: It is not clear that this sub-lineage is significant as it could be an artifact of growth of the number of infections where it is found for unrelated reasons and/or non-random sequencing and reporting. Since mid-May this sub-lineage is growing as a fraction of sequences in the USA and as a fraction of B.1.617.2 (including its sub-lineages). Like AY.2, which is growing in the USA at a similar rate (**Fig. 1**), it contains two mutations in Nsp6 (**Fig 2**) compared to one mutation in most recent B.1.617.2 sequences (T3646A) and a deletion in most VOCs (del3675/3677). **Fig 3a** shows the positions in the 4/August/2020 DeepMind Nsp6 prediction of other mutations and **Fig. 3b** and **3c** show the positions of T77 (T3646) and I162 (I3731) relative to a methionine-rich loop.

![image](https://user-images.githubusercontent.com/23096983/123561493-80c40000-d7a0-11eb-9423-a9bc55e04d33.png)
**Figure 1**. Ratio of the number of sequences of AY.2 or this sub-lineage (containing both ORF1a T3646A and I3731V mutations) and the total number of sequences containing Delta-defining S mutations in the USA. Using rolling lineage or mutation counts from outbreak.info as of 27/June/2021.

![image](https://user-images.githubusercontent.com/23096983/123563294-dce05180-d7ab-11eb-9f3b-9f1cbd8536f8.png)
**Figure 2**. Frequent mutations in Nsp6 in many significant variants. From outbreak.info

![image](https://user-images.githubusercontent.com/23096983/123561509-9d603800-d7a0-11eb-9fb6-360876d56aaf.png)
**Figure 3**. DeepMind Nsp6 structure (a) 106-108 deletion shortens predicted methionine rich loop, and recurrent L37F mutation recognized early in the pandemic could also affect the loop’s conformation. (b, c) T77 (ORF1a 3646) is in the middle of a conserved region spanning the predicted helical domain. I162 (ORF1a 3731) is one of the closest neighboring residues in the predicted tertiary structure.

### Example Genomes
USA/MO-CDC-QDX25576121/2021
USA/WA-CDC-UW21060749869/2021
USA/WA-CDC-UW21060513970/2021
USA/IN-INSPHL-02198/2021
USA/IL-CDC-QDX25576149/2021
USA/KS-KHEL-2297/2021
USA/FL-CDC-LC0069884/2021 is very similar except for part of N

### Phylogenetic Tree
![image](https://user-images.githubusercontent.com/23096983/123561541-da2c2f00-d7a0-11eb-9741-4bc5387c0ec5.png)

**Tree from**: https://nextstrain.org/groups/neherlab/ncov/21A.Delta?c=gt-ORF1a_3646,3731&label=mlabel:21A%20%28Delta%29/A11456G

**No lineage name is proposed**. Monitoring the relative growth of this sub-lineage, AY.2 and Delta at large in states having both (as of now: California, Minnesota, Alaska, Louisiana, Wisconsin, Illinois, Florida) may indicate whether this sub-lineage is significant. At the moment, it is not clear that this sub-lineage is outcompeting other B.1.617.2 sub-lineages in Missouri or Kansas.

**Comment by chrisruis** [comment]
Thanks @zach-hensel for submitting. From UShER, it looks like there's currently 110 sequences in this clade downstream of the ORF1a:I3731V mutation with GISAID IDs and <5% ambiguity. All of the sequences in this clade currently are from the USA. We've designated this clade as AY.3 in [v1.2.28](https://github.com/cov-lineages/pango-designation/releases/tag/v.1.2.28) containing these 110 sequences

**Comment by shay671** [comment]
Hi @chrisruis 
Regarding AY.3 and it's rise in several states. 
As we published on Saturday :

https://www.medrxiv.org/content/10.1101/2021.08.05.21261642v1

Delta is comprised of 5 main clades, Much different from what seen for any other Variant. Those 5 has 16 mutations in Consensus. But one of the clades (which we named Delta D), Rise to dominance all over the world in parallel. In every place it was the minority of sequences of Delta in the beginning and now in many placed it's the vast majority. 

AY.3 is actually Delta D + 2 silent mutations and a NS mutation in NSP6. 
So AY.3 should be compared to Delta D and not to Delta in General (as Delta D is known to rise over the other Delta clasdes, Whether it's called AY.3 or not). 

Using Virusurf platform i made this analysis for sequences number in 3 US states and for UK : 

![image](https://user-images.githubusercontent.com/80166370/128695687-0d7cb84b-5014-4a9f-b707-f8d0268d9a8d.png)

![image](https://user-images.githubusercontent.com/80166370/128695715-45ecd27b-5fa5-496d-b20e-c057ceb5d89e.png)


So, It actually does not seem that AY.3 is much different that Delta D.  Maybe AY.3 is just a local mutational signature in that area in the US.

**Comment by zach-hensel** [comment]
@shay671 -- This is what I was getting at with "it is not clear that this sub-lineage is outcompeting other B.1.617.2 sub-lineages in Missouri or Kansas." Some are reacting to the increasing prevalence overall without considering the founder effects of being the first sub-lineage to be amplified a lot in a summer vacation capital of the country between Memorial Day and the 4th of July.

I think there are significant-but-not-significant-enough-to-outrun-increasing-immunity non-Spike differences between Delta sub-lineages, and if anything I would guess that AY.3 corrects a small fitness defect in the parent lineage by adding another Nsp6 mutation. The ORF1a:T3255I mutation shows up ~simultaneously and is also in significant (imo) lineages B.1.1.519, B.1.575, and B.1.621.

I think the same might be true for the addition of Nsp6 T181I to Nsp6 V149A going from (A-C) to A in your scheme. Also, note that A is where Spike:A222V first became prevalent; a few sequences lack this. There's a similar small-but-significant possibility for Spike:T95I in some "D".

Lastly note that ORF1a:T3646A is ~defining in B.1.617.1 in addition to B.1.617.2 "D". To me this suggests either recombination or selection of a reversion?

**Comment by shay671** [comment]
Hi @zach-hensel  
Regarding B.1.617.1 
There are 7 mutations that i found which are at B.1.617.1 and B.1.617.2  and 6 out of these are also in B.1.617.3 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Shai/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Shai/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



refpos | refvar | qvar | Mutation |  
-- | -- | -- | -- | --
22917 | T | G | S:L452R |  
27638 | T | C | ORF7a:V82A |  
23604 | C | G | S:P681R |  
28881 | G | T | N:R203M |  
25469 | C | T | ORF3a:S26L | Not inB.1.617.3
210 | G | T | 5'UTR:210 |  
29402 | G | T | N:D377Y |  
  |   |   |   |  



</body>

</html>

Also - the NSP15:K259R is in Delta E and also B.1.617.1. Ans as we noted in the paper, Delta E has some very clear signs of recombination within it.

**Comment by zach-hensel** [comment]
@shay671 there are 2 early sequences that are B.1.617.1 except for ORF1a V2930L, T3255I, and T3646A in a row; without close phylogenetic links in either direction it's hard to rule out contamination from B.1.617.2 in the same place, at the same time, though. Recombination of the mutations that aren't common between very prevalent B.1.617.1 and nascent B.1.617.2 early in 2021 could explain an upshift in B.1.617.2 fitness and why there's unsampled B.1.617.2 diversity.

It seems important to know how significant mutations are in Delta including non-Spike and how frequently they are exchanged through recombination; "D" has an advantage in global prevalence, but "A" is not far off in parts of the United States, for example. If this can play a role it could be similarly significant to gradual acquisition of immune escape mutations that is also occurring in determining how Delta changes going into the northern hemisphere winter.
