### ISSUE TITLE
BF.7 with S:H1101Y, S:F486I and ORF3a:T176I in Denmark (55 sequences)

### ISSUE THREAD

**Issue by AleksanderRing** [cov-lineages/pango-designation#1216]
## Proposal for new sublineage of BF.7 with additional mutations S:H1101Y, S:F486I and ORF3a:T176I. 

Countries detected: Denmark (55)

Earliest sequence: (dd-mm-yyyy) 02-09-2022

Defining mutations: S:H1101Y, S:F486I, ORF3a:T176I

GISAID query: Spike_H1101Y,Spike_F486I

![image](https://user-images.githubusercontent.com/102508994/195601414-5c253faf-444d-49f3-ad2b-f331e3574dc8.png)

55 sequences uploaded to GISAID and more have been sequenced pending upload to GISAID

EPI_ISL_14884400, EPI_ISL_15037816, EPI_ISL_15037907,
EPI_ISL_15100507, EPI_ISL_15138430, EPI_ISL_15138528,
EPI_ISL_15138723, EPI_ISL_15155190, EPI_ISL_15155337,
EPI_ISL_15155910, EPI_ISL_15155932, EPI_ISL_15155968,
EPI_ISL_15156102, EPI_ISL_15206663, EPI_ISL_15207793,
EPI_ISL_15208352, EPI_ISL_15208539, EPI_ISL_15208562,
EPI_ISL_15233377, EPI_ISL_15233422, EPI_ISL_15233431,
EPI_ISL_15233665, EPI_ISL_15233900, EPI_ISL_15234029,
EPI_ISL_15267162, EPI_ISL_15267208, EPI_ISL_15267429,
EPI_ISL_15267432, EPI_ISL_15267468, EPI_ISL_15267486,
EPI_ISL_15267809, EPI_ISL_15268085, EPI_ISL_15268172,
EPI_ISL_15283976, EPI_ISL_15284067, EPI_ISL_15293082,
EPI_ISL_15293127, EPI_ISL_15293574, EPI_ISL_15293647,
EPI_ISL_15293696, EPI_ISL_15316583, EPI_ISL_15316660,
EPI_ISL_15316729, EPI_ISL_15316792, EPI_ISL_15331211,
EPI_ISL_15331423, EPI_ISL_15331508, EPI_ISL_15347008,
EPI_ISL_15347057, EPI_ISL_15347078, EPI_ISL_15347225,
EPI_ISL_15347334, EPI_ISL_15347357, EPI_ISL_15347364,
EPI_ISL_15347514

**Comment by cvejris** [comment]
Nice, F486I is a second order mutation (descending from 486V, which was defining for BA.5)

**Comment by corneliusroemer** [comment]
Thanks @AleksanderRing for the good proposal - did you spot this as part of the Danish sequencing consortium?

There are a few more BF.7 that may be worth designating, I noticed S:Y144- is on the rise, I'll take a look at some point in the near future to designate things more systematically.

**Comment by AleksanderRing** [comment]
Yes, we spotted this as a part of the work we do in the Danish sequencing consortium. We recently updated our monitoring systems to monitor mutations.

**Comment by FedeGueli** [comment]
Interesting S:H1101Y is defining in XAK
