### ISSUE TITLE
B.60 representative sequences are all COG-UK-only (not in GISAID); no hashes?, most called as B.40

### ISSUE THREAD

**Issue by AngieHinrichs** [cov-lineages/pango-designation#122]
The 73 representative sequences for B.60 in lineages.csv are all COG-UK (specifically England/PHEC-*) names that are not in GISAID.  They are not assigned B.60 in [cog-metadata.csv](https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_metadata.csv) -- most are assigned B.40.  I'm guessing that since their names are not found in GISAID, pangoLEARN is not getting any training data for B.60 and the designation hashes are not added, although they could be added separately from COG-UK fasta.

There are a few GISAID sequences that are identical to either designated sequences or very similar sequences.
* England/20130086304/2020|EPI_ISL_423672|2020-03-20 is identical to England/PHEC-145FB/2020 with leading/trailing Ns trimmed 
* England/20156036604/2020|EPI_ISL_466307|2020-04-08 is identical to England/PHEC-1C21A/2020 with leading/trailing Ns trimmed
* England/20156036504/2020|EPI_ISL_466306|2020-04-08 is identical to England/PHEC-1C20B/2020 with leading/trailing Ns trimmed (England/PHEC-1C20B/2020 is not a designated sequence and is no longer in cog_metadata.csv but is still in the UCSC tree, must have been added but then dropped from the COG-UK download files)

There are several other COG-UK sequences that are not designated sequences but cluster with them in UCSC's tree:

England/PORT-2D224B/2020 (also in GISAID, EPI_ISL_507136)
England/PHEC-14FB1/2020
England/PHEC-18C3E/2020
England/PHEC-1B5B8/2020
England/PHEC-1C20B/2020
England/PHEC-1DF12/2020

I can add the four GISAID sequences as representatives, and then pangoLEARN will have at least a little data to train on.

Is there a standalone way to compute designation hashes, e.g. from COG-UK sequences?

**Comment by AngieHinrichs** [comment]
Nextstrain view of subtree of UCSC tree:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-122.json?label=nuc%20mutations:C7011T

**Comment by aineniamh** [comment]
Thanks for this @AngieHinrichs. 
I'd rather not compute the hashes separately and would prefer in general to work from one database (I feel if we get into using COG-specific data, then we'd open a can of worms and probably want to look at other countries repositories too). I think adding those four GISAID sequences would be a great start and hopefully the UK sequences will make their way onto GISAID shortly (as far as I'm aware everything does make it's way to GISAID still?). 
As an aside, that's probably a good idea in general though, to designate identical sequences to the ones that are already designated- the assignments won't change from the hash-based assignments, but it'll give a better designated/not-designated ratio. I'll look at doing that!

**Comment by AngieHinrichs** [comment]
I understand not wanting to add additional sources -- as simple as it may sound on the surface, aggregation and deduplication is an enormous timesink and extremely hard to get just right.  

[I still can't help but ask... what other countries have open data like COG-UK's?  There are the INSDC databases (GenBank/ENA/DDBJ), but I would be happy to learn about the existence of more COGs like COG-UK...]

[TL;DR I think it's possible that the B.60 representative sequences, from March & April 2020, were submitted to GISAID, but rejected for QC reasons and not resubmitted.]  This is only hearsay (hearSlack?), and you can probably confirm this with more reliable local sources, but I have heard that COG-UK does not resubmit sequences that are rejected by GISAID/GenBank QC for various reasons e.g. early stop codon or frameshift indel mutations (which are actually not too uncommon in ORF8).  With the huge scale of COG-UK's submissions, it would take an incredible amount of time and effort to screenshot & email read-level evidence for every rejected sequence, and for that matter, for the repositories to review the evidence for so many sequences -- so it's not surprising that some COG-UK sequences might be submitted to GISAID, but auto-rejected -- so they'd be available in COG-UK's dataset which is available for public download, but not in GISAID.

OK, I will add those 4 GISAID seqs.

**Comment by AngieHinrichs** [comment]
I spoke too soon -- the three England/201.../2020 sequences have too many Ns.  So I'll add England/PORT-2D224B/2020.  

It would be nice to have way to designate hashes for sequences that have too many Ns to go in lineages.csv like the three England/201.../2020 sequences, but that are known to belong to a lineage.
