### ISSUE TITLE
Potential XBB sublineage with ORF1a:G82D

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1222]
There may be a XBB sublineage with ORF1a:G82D (G510A) first detected in India.

As of 2022-10-16, Cov-Spectrum reports 94 XBB+ORF1a:82D sequences with good quality control scores:
![counts_XBB+ORF1a_82D](https://user-images.githubusercontent.com/88959107/196059512-088405ca-fce2-464e-9899-0bb60776c7cc.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXBB+%26+ORF1a%3AG82D&nextcladeQcOverallScoreTo=29&

As of 2022-10-16, UShER shows all of the GenBank samples are on a single subtree:
![usher_genbank_XBB+ORF1a_82D](https://user-images.githubusercontent.com/88959107/196059520-ae497b22-502b-4735-8ff8-104ba3853bfa.png)
To visualize on UShER: https://nextstrain.org/fetch/raw.githubusercontent.com/alurqu/pango-designation-support-alurqu/main/2022/10/singleSubtreeAuspice_genome_XBB%2BORF1a_82D.json

Although UShER with CoV-Spectrum shows a downstream reversion branch which may be incorrect:
![usher_cov-spectrum_XBB+ORF1a_82D](https://user-images.githubusercontent.com/88959107/196059539-3b00b0da-9a82-4f9c-8499-0c111d1f1dbb.png)

To visualize on UShER: https://nextstrain.org/fetch/raw.githubusercontent.com/alurqu/pango-designation-support-alurqu/main/2022/10/subtreeAuspice1_genome_cov-spectrum_XBB%2BORF1a_82D.json?c=gt-ORF1ab_82&label=nuc%20mutations:G23040A

First CoV-Spectrum sequence: India, 2022 Week 33

First GenBank sequence: California, USA 2022-09-02 

Most Recent GenBank sequence: California, USA 2022-09-22

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at 
[Support-XBB+ORF1a_82D.zip](https://github.com/cov-lineages/pango-designation/files/9795735/Support-XBB%2BORF1a_82D.zip)

The list of GISAID sequence identifiers is in
[sequence_list-XBB+ORF1a_82D.csv](https://github.com/cov-lineages/pango-designation/files/9795736/sequence_list-XBB%2BORF1a_82D.csv)

Edit: put the sequence count in the text.

**Comment by corneliusroemer** [comment]
It's part of some of the newly designated XBB lineages, but not a lineage of its own as it's too common for a level of its own
