### ISSUE TITLE
BA.5.2.35 

### ISSUE THREAD

**Issue by alantsangmb** [cov-lineages/pango-designation#1223]
Hi, apologize that I cannot find much discussion about BA.5.2.35 in previous threads.

However, I notice that BA.5.2.35 possess the mutations of BA.5.2.6 with additional mutations e.g. C7006T and G28423C.
Might I know if there is any reason why this is not designated as a sub-lineage of BA.5.2.6 * ?
Thank you so much

**Comment by corneliusroemer** [comment]
It's homoplasy.

If you look at the Usher tree, it's clear that S:346T arose independently in BA.5.2.35, _after_ mutations C7006T and G28423C.

It may _look_ like a child of BA.5.2.6 if you just consider designated lineages, but we have more information.

**Comment by alantsangmb** [comment]
I got it, thanks a lot

**Comment by FedeGueli** [comment]
G28423C. is ORF9b:R47P and seems it managed to circulate  a bit before gaining S:346T , looking at the tree Pakistan could be a place where this lineage emerged:

T16617C is the defining mutation of the bigger branch that collects both BA.5.2.35 and BA.5.2.14 which are probably sibling and both likely emerged in Pakistan .
in the same tree there is  a third lineage, much smaller than the first two, defined by Orf1a:T2952I that acquired then S:V445A and that is  likely a Pakistan lineage too:

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3000c_5b9dd0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T6394C

![Schermata 2022-10-24 alle 00 28 48](https://user-images.githubusercontent.com/87669813/197421216-51de2933-4044-4f75-8a1d-516f69e3afa6.png)
