### ISSUE TITLE
Mini saltation with S:444R,S:R646H,S:D253G + S:A942S spotted in BA.5.2.6 (S:346T)  -10 sequences Uk, Denmark, Spain, Netherlands, Usa

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1226]
It was mentioned already in #1170 but now USher places it in BA.5.2.6 (+S:346T)  ( @AngieHinrichs )

Defining mutations:
C1714T + S:A942S (G24386T) (10seqs)
then
T23197C +S:D253G (A22320G), S:R646H (G23499A) S:K444R (A22893G) + Orf1a:F406V (T1481G) 3 seqs:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_23e72_d622c0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C1714T,G24386T
<img width="1150" alt="Schermata 2022-10-17 alle 16 28 01" src="https://user-images.githubusercontent.com/87669813/196203752-4eb00fce-d199-45fc-8114-a088fd0bc862.png">

Gisaid query : Spike_R346T,Spike_K444R,Spike_A942S,Spike_R646H

Sequences: EPI_ISL_15209823, EPI_ISL_15209892, EPI_ISL_15386854,

**Comment by FedeGueli** [comment]
Luckily no new sequence appeared in a week, being in Uk i think it is ok to close it for now

**Comment by oobb45729** [comment]
There is international spread of this one now and S:A942S is one alarming mutation:
![pnas 2119467119fig01](https://user-images.githubusercontent.com/115189228/201205090-ec69e9ea-a373-4a3c-8490-e40a113eb2a5.jpg)
https://www.pnas.org/doi/10.1073/pnas.2119467119

**Comment by FedeGueli** [comment]
> There is international spread of this one now and S:A942S is one alarming mutation: ![pnas 2119467119fig01](https://user-images.githubusercontent.com/115189228/201205090-ec69e9ea-a373-4a3c-8490-e40a113eb2a5.jpg) https://www.pnas.org/doi/10.1073/pnas.2119467119

Thanks for monitoring this one.
It is now 8 sequences and newly found in Denmark, Spain and Netherlands. Reopening it.

**Comment by FedeGueli** [comment]
9 sequences, newly found in USA, Illinois

**Comment by FedeGueli** [comment]
no growth for this one :

**Comment by aretchless** [comment]
This is still drifting along, but does not seem to be growing.

3 sequences reported in November -- 2 in USA, 1 in Spain
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AR646H%2CS%3AD253G%2CS%3AA942S%2CS%3A444R&
