### ISSUE TITLE
XBB with S:K147E, S:W152R, S:F157L  (2 seq., India)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1231]
Proposal for a sublineage of XBB
Earliest sequence: 03.09.2022 (India)
Countries detected: India (2)

Potential sublineage of XBB (or different recombinant clustering with XBB) defined by S:K147E, S:W152R, S:F157L.

Gisaid query: Spike_K147E, Spike_W152R, Spike_F157L, Spike_L368I, Spike_V445P

![grafik](https://user-images.githubusercontent.com/102166254/196375707-8b89e2ac-d082-4fe1-afe6-17f145658a4c.png)
![grafik](https://user-images.githubusercontent.com/102166254/196376349-c17b9575-ff84-414f-aaa2-4354ef74aa01.png)
![grafik](https://user-images.githubusercontent.com/102166254/196376561-8891dd30-93af-49f3-92af-061b88fac58f.png)

The two accessions sit on a bit of a messy clade (e.g only the two apparently really carry S:K147E, S:W152R, S:F157L even though usher indicates otherwise...):
![grafik](https://user-images.githubusercontent.com/102166254/196376946-9d6535a2-7309-4f76-9679-ca193e046c55.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9bf5_e57770.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C21810T,A22200G

EPI_ISL_14987876, EPI_ISL_14987880

**Comment by corneliusroemer** [comment]
I wouldn't trust these, they look potentially artefactual, they are from one lab at one point in time, no recent sequences.

I'll close so this doesn't mislead anyone - if we see more circulation in a less messy part of the tree let's reconsider.

**Comment by corneliusroemer** [comment]
The sequences are not identical, they have different reversions, overall looks strongly like artefacts to me. If you see so many reversions, and if it's in a messy part of Usher tree, be wary.


<img width="598" alt="image" src="https://user-images.githubusercontent.com/25161793/196400134-a58c43b2-3aff-41b4-9cc7-12bb3b1086c0.png">

<img width="589" alt="image" src="https://user-images.githubusercontent.com/25161793/196400139-599278a8-db3e-4bcc-829e-6b3fc5617584.png">
