### ISSUE TITLE
BA.5.2.1 +T6979G + A3859G sublineage with S:R646H, S:R346T - 64 sequences (England Australia Denmark Ireland India Israel France) spotted by @ryhisner

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1233]
@ryhisner and me in the last few weeks are noticing that S:R646H mutation is popping up here and there, 
and it is usually associated with multiple AA substitution 
Yesterday i proposed a BA.5.2.6 cluster with S:R646H in #1226

Now  i want to propose another interesting branch with S:R646H **(Independent and unrelated to #1226**) that was **FIRST SPOTTED AND DESCRIBED** by _RYAN HISNER ( @ryhisner ) to me two or three weeks ago (i missed it was the same so i proposed it on my own, sorry!)

It is a BA.5.2.1 ( > C1627T > A27038G )
defined by :  
T6979G > A3859G >
Orf3a:L115F( G25737T) then C21516T then S:R646H (G23499A) then S:R346T ( G23499A ) 
Tree:
<img width="1146" alt="Schermata 2022-10-18 alle 17 47 25" src="https://user-images.githubusercontent.com/87669813/196479791-7da3ebf4-7177-4e1f-a5e6-8fdf29ff51e8.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2b5bd_ec8a10.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G25737T

Gisaid Query: Spike_R646H,NS3_L115F
CovSpectrum query : C21516T, T6979G, A3859G + S:R346T, S:R646H, ORF3a:L115F
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AR346T%2CS%3AR646H%2COrf3a%3AL115F&nucMutations=C21516T%2CT6979G%2CA3859G&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Sequences: EPI_ISL_14352124, EPI_ISL_14812442, EPI_ISL_15176899,
EPI_ISL_15209330, EPI_ISL_15233789, EPI_ISL_15260789,
EPI_ISL_15269841, EPI_ISL_15299980, EPI_ISL_15301320,
EPI_ISL_15301926, EPI_ISL_15345151, EPI_ISL_15347956,
EPI_ISL_15362370-15362371, EPI_ISL_15362448, EPI_ISL_15381519,
EPI_ISL_15385714, EPI_ISL_15393765, EPI_ISL_15399502,
EPI_ISL_15409691-15409693

to be noticed that three sequences from ireland uploaded today have also S:A846V.
<img width="1157" alt="Schermata 2022-10-18 alle 18 01 21" src="https://user-images.githubusercontent.com/87669813/196483088-6ba1976f-8a3a-4e49-a179-f3f126db5b43.png">

**Comment by FedeGueli** [comment]
Big uploads  of this one on last Friday from germany and today  from England , probably clusters?

CC @corneliusroemer @thomasppeacock @InfrPopGen it would be worth to check this with _**UKHSA**_ cause it jumper to 40 in a few days ( one doubling) , if it is not related with a single epidemiological event i suggest to designate it very soon, otherwise we can wait if more of that will pop up from different dyas/labs/countries.

**Comment by FedeGueli** [comment]
45 seqs as today. the new ones are from England.

**Comment by FedeGueli** [comment]
64 sequences as today

 @corneliusroemer @InfrPopGen i think this deserves a designation:
steady growth, peculiar mutations, S:346T, it seems going well in Canada (where samples are from baseline surveillance, if this means random samples)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.34 with 47 newly designated sequences, and 0 updated designations. Defining mutation G22599C (S:R346T) (following G23499A).
