### ISSUE TITLE
BF.11 with S:Y453F [2 seq, England, 2022-10-19]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1234]
During my routine review of new sequences in Nextclade, I noticed two sequences from England with S:Y453F.

This mutation is predicted to increase ACE2 binding a lot on a BA.2 background. It could be that this is not true however if S:L452R is also present. So this is worth watching.

hCoV-19/England/QEUH-325A7EF4/2022|EPI_ISL_15418438|2022-10-05
hCoV-19/England/QEUH-325A88F5/2022|EPI_ISL_15418329|2022-10-05

There was another recent BA.5 with S:Y453F recently from Sweden - but unrelated phlogenetically.

**Comment by oobb45729** [comment]
Y453F is one of the convergent mutations on remaining Deltas. If anything, L452R probably would reinforce Y453F.

**Comment by corneliusroemer** [comment]
It's also a Mink adaption mutation, apparently

**Comment by corneliusroemer** [comment]
Two new S:Y453F clusters (1 doublet from Sweden with extra S:N450D, 1 singlet from Portugal):

And a long branch sequence from Australia derived from BA.1.17:
hCoV-19/Australia/VIC73058/2022|EPI_ISL_15471420|2022-10-12

Sweden:
hCoV-19/Sweden/SUS0016208/2022|EPI_ISL_15385329|2022-10-03
hCoV-19/Sweden/SUS0016401/2022|EPI_ISL_15479554|2022-10-09

Portugal:
hCoV-19/Portugal/PT43503/2022|EPI_ISL_15481203|2022-10-08

**Comment by InfrPopGen** [comment]
I think after four months it may be safe to close this one, as it did not appear again anywhere else.

**Comment by corneliusroemer** [comment]
Yes indeed! Thanks!
