### ISSUE TITLE
BN.1 with S:F486S (2 sequences England, as of 2022-10-19)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1235]
Spike_F486,Spike_K356T, Spike_F490S, Spike_R346T

Predicted to have high predicted immune escape so worth watching)

hCoV-19/England/QEUH-325A81AF/2022|EPI_ISL_15418355|2022-10-07
hCoV-19/England/QEUH-3259B3F4/2022|EPI_ISL_15365642|2022-10-04

**Comment by InfrPopGen** [comment]
As this has not shown much growth, and no advantages, since detection, this can be closed for now. Of course, please re-open should it reemerge with appreciable growth in the future.
