### ISSUE TITLE
Clarify BF.7.5 Lineage Notes

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1236]
The lineage_notes.txt entry for BF.7.5 shows that this sublineage is distinguished by a mutation at ORF1b:P1427, but it does not specify the new residue. I believe that this should this be ORF1b:P1427L.  (Updating "ORF1b:P1427" to "ORF1b:P1427L".)

**Comment by alantsangmb** [comment]
Sorry if this is a little off topic.

Among the 753 designated BF.7.5 genomes, I found that EPI_ISL_15100906 could potentially be a BF.7.5/BA.5.2.* recombinant lineage. The genome of EPI_ISL_15100906 is similar to other BF.7.5 from genome position 1 to 27011. However,
, downstream from position 27012, it is more similar to other BA.5.2.*, e.g. BA.5.2.6 or BA.5.2.13. It has C27012T and C27513T, but has neither BF.7 N:S33F and A28777G.

Is this genome needed to remove from BF.7.5 designation or re-designated to another lineage?
Thank you.

**Comment by corneliusroemer** [comment]
@alantsangmb The assignment algorithms should be robust to small outliers like potential recombinants. You could propose a PR to remove this one, if you like.
