### ISSUE TITLE
BA.5.2 with S:N417Y and S:E406Q in France

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1237]
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AN417Y%2CS%3AE406Q&nextcladePangoLineage=BA.5.2*&

N417Y is predicted to increase ACE2 binding significantly and E406Q is located near N417Y.

**Comment by alurqu** [comment]
Here's an UShER tree using the data from the original query: ![UShER_CoV-Spectrum_Issue_1237](https://user-images.githubusercontent.com/88959107/196814694-4e75021f-54c2-4319-91b9-d03a04fcb364.png)

It looks like this is another BA.5.2+ORF1b:T1050N+27012T+27513T sublineage, It looks there's also ORF1b:P2404S in the mutation path to these samples.

These all appear to be from Bourgogne-France-Comté with the last collected on 15 Sep 2022, and 271 samples have been collected from Bourgogne-France-Comté after 15 Sep 2022 and reported with nothing matching this query being reported from there or elsewhere.

**Comment by oobb45729** [comment]
Only 17 for now. Close it.

**Comment by oobb45729** [comment]
Apparently, a BA.5.2 saltation with S:406Q and S:417Y showed up in France.
https://cov-spectrum.org/explore/France/AllSamples/AllTimes/variants?variantQuery=S%3A417y%26S%3A406q%26orf1b%3A1264d&
It does not have Orf1b:T1050N or Orf1b:P2404S but it has A27038G.
It has new mutations ORF1a:A1716V, ORF1a:L3808F, ORF1b:I214M, ORF1b:E1264D(also in Gamma), S:Y144-, S:NL211I, S:504D, S:987F, ORF7b:A43V, N:S327L.
It is a case of convergent evolution or a case of recombination with BA.5.2.1?

**Comment by FedeGueli** [comment]
is it from the same lab?

**Comment by oobb45729** [comment]
I don't know. I don't have access to GISAID. It's from a region where 417Y+406Q had not shown up before.

**Comment by oobb45729** [comment]
The second sequence of BA.5.2.1+S:417Y+S:406Q showed up.
