### ISSUE TITLE
Potential BN.1.2 sublineage  with S:T470N , Orf1b:K1471I circulating in Uk (14 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1238]
Maybe it is worth monitoring for a while this BN.1 sublineage that popped up in England very recently.
Main characteristic of it is a mutation right in the RBM , S:T470N , although it is not known to confer any specific advantage on nextclade in some (but not all) sequences seems to raise slighty composite fitness value (ACE2 binding + Escape) that it is already very high for BN.1.

It is  part of a broader lineage defined by a mutation in E : 
E:D72G (A26459G) - 74 sequences recently designated **BN.1.2** (EDITED @AngieHinrichs still not on USHER)
then
C1915T 
then
S:T470N + Orf1b:K1471I 

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1020d_5daf0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C1915T
<img width="1136" alt="Schermata 2022-10-19 alle 22 47 39" src="https://user-images.githubusercontent.com/87669813/196800835-8b190b5b-abcf-45a1-b3f9-1719ac60df18.png">

Gisaid query: **Spike_K356T,Spike_T470N,NSP14_K147I** finds 7 sequences , two of them arent on Usher (One from Portugal and the other from Austria) so probably the total is now already 12.

CovSpectrum : https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AT470N&nextcladePangoLineage=BN.1*&

List of sequences :
EPI_ISL_15249244, EPI_ISL_15330433, EPI_ISL_15345108,
EPI_ISL_15365062, EPI_ISL_15389815, EPI_ISL_15403589,
EPI_ISL_15421198

**Comment by FedeGueli** [comment]
Two more sequences uploaded today from England

**Comment by oobb45729** [comment]
T470N is near F490S.
