### ISSUE TITLE
New BQ.1.19 ( =S:494P) sublineage with S:N603S and S:D614S  circulating in Canada (26 Seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1243]
Here i want to propose another sublineage that has the B.1 defining mutation S:D614G mutated further from **G** to **S** (after BL.1.1 spotted and proposed by @ryhisner in #1079 ).

It is part of the recently designated BQ.1.19 defined by S:S494P followed by S:N603S then C19596T then ORF1A:A486T THEN S:D614S

17 sequences all from Canada
<img width="1160" alt="Schermata 2022-10-22 alle 00 18 16" src="https://user-images.githubusercontent.com/87669813/197296660-49e88bfc-922b-42b4-91c3-d984c272d28e.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c8a0_317e00.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T23042C

Gisaid query: Spike_N603S,Spike_D614S

CovSpectrum query : C19596T + S:S494P, S:N603S, ORF1a:A486T, S:D614S
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AS494P%2CS%3AN603S%2CORF1A%3AA486T%2CS%3AD614S&nucMutations=C19596T&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Sequences : EPI_ISL_15320233, EPI_ISL_15396524, EPI_ISL_15396851,
EPI_ISL_15396859, EPI_ISL_15418120, EPI_ISL_15433923-15433924,
EPI_ISL_15434031, EPI_ISL_15434036, EPI_ISL_15434043,
EPI_ISL_15434196, EPI_ISL_15434217-15434218, EPI_ISL_15434259,
EPI_ISL_15434341-15434342, EPI_ISL_15434401

**Comment by oobb45729** [comment]
N603 is an N-glycan site.

**Comment by FedeGueli** [comment]
26 viruses as today.

**Comment by FedeGueli** [comment]
Closing this cause it doesnt show any special growth
