### ISSUE TITLE
South American BA.5.1.25 sublineage with S:K444N (263 sequences)  with two independent sublineages with S:N460K (T22942G): with N:T265S - 112 seqs and another with N:G5E - 7seqs

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1245]
Here i want to propose a sublineage of BA.5.1.25 defined by S:K444N circulating in three south american countries (Peru', Chile and Colombia) .

Defining mutations:
BA.5.1.25  (orf7b:H42Y)+ S:K444N
![Schermata 2022-10-22 alle 09 32 47](https://user-images.githubusercontent.com/87669813/197326875-dfe24c36-bfdb-4f28-9f31-9e8141926c99.png)

[contributors (1).csv](https://github.com/cov-lineages/pango-designation/files/9843794/contributors.1.csv)

This lineage has  two sublineages with potential interest defined by S:N:460K 

Gisaid query for them (NS7b_H42Y,M_D3N,-NSP12_Y273H,Spike_N460K,SPike_K444N ) finds 7 viruses :
![Schermata 2022-10-22 alle 09 36 12](https://user-images.githubusercontent.com/87669813/197326987-13afe734-95e9-47cf-a81b-ad247eaa97b5.png)

Especially the bottom one seems circulating and can be monitored on CovSpectrum with : BA.5.1.25* (Nextclade) + S:K444N, N:T265S, S:N460K
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AK444N%2CN%3AT265S%2CS%3AN460K&nextcladePangoLineage=BA.5.1.25*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

or Gisaid : N_T265S,NS7b_H42Y,M_D3N,-NSP12_Y273H,Spike_N460K,SPike_K444N

while the top one can be checked with N_G5E,NS7b_H42Y,M_D3N,-NSP12_Y273H,Spike_N460K,SPike_K444N

**Comment by FedeGueli** [comment]
10 seqs as today

**Comment by FedeGueli** [comment]
The parental lineage defined by S:444N ( NS7b_H42Y,M_D3N,-NSP12_Y273H,SPike_K444N)  is now at 152 sequences, in 4 continents and 7 countries
<img width="1158" alt="Schermata 2022-11-16 alle 21 38 47" src="https://user-images.githubusercontent.com/87669813/202289158-09a24f0f-4c0c-4ea5-82e1-b862631adbdc.png">

the mayor sublineage defined by N:T265S + S:N460K reached 16 sequences and has been sampled in NYC too beyond Peru
<img width="1160" alt="Schermata 2022-11-16 alle 21 40 22" src="https://user-images.githubusercontent.com/87669813/202289425-571e9080-bf83-4979-ba8d-d29aee09f30c.png">

the minor sublineage defined by N:G5E +S:N460K counts 5 sequences and doesnt seem to circulate beyond local level:
<img width="1160" alt="Schermata 2022-11-16 alle 21 42 21" src="https://user-images.githubusercontent.com/87669813/202289778-d7001a0c-855c-429e-a480-658dbf8b6596.png">

tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26a58_5493e0.json?c=gt-S_460&label=nuc%20mutations:G22894T

@corneliusroemer @InfrPopGen please keep in mind proportions:
the two sublineage with S:N460K reached a 7% of sequences in two consecutive weeks very recently in **PERU'**:
<img width="1103" alt="Schermata 2022-11-16 alle 21 45 26" src="https://user-images.githubusercontent.com/87669813/202290390-56d8c795-13ae-419f-a346-76253227b413.png">
https://cov-spectrum.org/explore/Peru/AllSamples/Past6M/variants?aaMutations=S%3AK444N%2CS%3AN460K&nextcladePangoLineage=BA.5.1.25*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

**Comment by c19850727** [comment]
Hi @FedeGueli there's a big upload of "N_T265S,NS7b_H42Y,M_D3N,-NSP12_Y273H,Spike_N460K,SPike_K444N" just now. ~104 sequences  in total, collected between Sept 27th and Oct 28th.

**Comment by FedeGueli** [comment]
Thank you very much @c19850727 !
I updated the count and this my proposal for designation (cc @corneliusroemer @InfrPopGen) 
BA.5.1.25+ S:444N now 263 seqs > D'X'.1
BA.5.1.25+ S:444N+ N:T265S now 110 seqs > D'X'.1.1
BA.5.1.25+ S:444N + N:G5E now 52 viruses 7 with 460K  > D'X'.1.2

**Comment by FedeGueli** [comment]
two new seqeunces of the big branch with S:N460K both from USA, pointing to high real prevalence as in Covspectrum.

**Comment by InfrPopGen** [comment]
Thanks for submitting. For the parental lineage so far, we've added lineage DJ.1 with 87 newly designated sequences, and 61 updated designations. Defining mutation G22894T (S:K444N) (following BA.5.1.25 C27879T (ORF7b:H42Y) on current tree). Sub-lineages are pending...

**Comment by InfrPopGen** [comment]
For the larger of the proposed sublineages we've added now added lineage DJ.1.1 with 0 newly designated sequences, and 17 updated designations from DJ.1. Defining mutations C21757T (S:N460K), T22942G (following A29066T (N:T265S)). The issue can be closed for now, but should the smaller of the sub-lineages show signs of epidemiological significance in the future then please either re-propose it as a new issue, or prompt for reopening of this issue, so either way it can be re-considered.

**Comment by FedeGueli** [comment]
@InfrPopGen thanks for designating this one,
the minor lineage (the putative DJ.1.2 with S:N460K + N:G5E) reached 8 sequences  but interestingly it was exported to Japan: EPI_ISL_15907987 collected on 11/11/22 

As @vjimenez-vasquez annouced in the commit linked to this issue a new batch of sequences from Peru will be uploaded next week. If the amount of sequences of this smaller lineage wll be enough i suggest direct designation from here. 

otherwise i will manage to prompt a new issue (Unless the super careful peruvian scientists want to do on their own!)

cc @corneliusroemer

**Comment by Vjimenez-vasquez** [comment]
> @InfrPopGen thanks for designating this one, the minor lineage (the putative DJ.1.2 with S:N460K + N:G5E) reached 8 sequences but interestingly it was exported to Japan: EPI_ISL_15907987 collected on 11/11/22
> 
> As @Vjimenez-vasquez announced in the commit linked to this issue a new batch of sequences from Peru will be uploaded next week. If the amount of sequences of this smaller lineage wll be enough i suggest direct designation from here.
> 
> otherwise i will manage to prompt a new issue (Unless the super careful peruvian scientists want to do on their own!)
> 
> cc @corneliusroemer

Thanks @FedeGueli !!!

**Comment by FedeGueli** [comment]
As announced by @Vjimenez-vasquez a big upload of DJ. sequences today!
DJ.1.1 went well over 200sequences
while the smaller one  (Gisaid query: N_G5E,Spike_N460K,NS7b_H42Y,M_D3N,-NSP12_Y273H,SPike_K444N) now counts 54 sequences !! a big jump from 8 to 54 highlighting probably it has a similar fitness as its sibling designated lineage.

@InfrPopGen i cant reopen on my own this ine cause it was closed by you maintainers. so i will open a new one! 

cc @corneliusroemer
