### ISSUE TITLE
Putative recombinant between BA.5.2+Orf1b:1050N+S:346T and BE.4+29868A spotted by @Alurqu and circulating in USA (122 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1246]
@alurqu spotted this lineage and highlighted it in #1065 

i am convinced that it is a recombinant between BA.5.2+Orf1b:1050N+S:346T and BE.4+29868A:

https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=29868A&nextcladePangoLineage=BE.4*&aaMutations1=N%3A136D%2CORF1b%3A1050N%2CS%3A346T&nucMutations1=14670T%2C27800T&nextcladePangoLineage1=BA.5.2&analysisMode=CompareEquals&

The BE.4 part is from somewhere after 23609 to N
![Schermata 2022-10-22 alle 10 58 04](https://user-images.githubusercontent.com/87669813/197330765-cfc39d9e-207c-4ad9-86c5-ae45c8a958ae.png)

The BA.5.2 part is  from 0 to at least 23608 
![Schermata 2022-10-22 alle 11 11 54](https://user-images.githubusercontent.com/87669813/197331372-5d8830c3-d183-4443-a92b-0b8571f693a8.png)

I excluded that S:346T comes from BE.4.1 for the presence of  Nuc: G23608T in 100% of BE.4.1+29868A  

So it likely comes from the still undesignated  BA.5.2*+Orf1b:1050N + S:346T 
as BA.5.2.6 (45.28%)
BA.5.2.13 (15.30%)
BA.5.2.34 (13.79%)
BA.5.2.35 (9.68%)
BA.5.2.20 (4.47%)
CP.1 (3.21%)
BA.5.2 (3.02%)
CR.1 (2.57%)

CovSpectrum query : BA.5.2 (Nextclade) + C27800T + N:E136D, ORF1b:T1050N, S:R346T
finds 108 seqs:
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=N%3A136D%2CORF1b%3A1050N%2CS%3A346T&nucMutations=27800T&nextcladePangoLineage=BA.5.2&aaMutations1=Orf1b%3A1050N&nextcladePangoLineage1=BA.5.2*&

Sequence list:
[contributors (2).csv](https://github.com/cov-lineages/pango-designation/files/9843985/contributors.2.csv)

Gisaid Query: -NSP13_M233I,N_E136D,Spike_R346T,NSP13_T127N finds 123 Viruses

Tree:
![Schermata 2022-10-22 alle 11 33 57](https://user-images.githubusercontent.com/87669813/197332269-fc6f218a-544d-48b4-b221-99f52cb4cfb9.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_327b4_3b62c0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C27800T

_Originally posted by @FedeGueli in https://github.com/cov-lineages/pango-designation/issues/1065#issuecomment-1287694806_

@c19850727 @josetteshoenma @angiehinrichs your help will be great with this!

All credits to @alurqu

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XBE with 104 newly designated sequences, and 0 updated designations. Defining mutation: nt:G22599C (S:R346T) (following C1627T).
