### ISSUE TITLE
BA.5.2.7(S:K444M) sublineage with  S:N460K (T22942G) 20 sequences circulating in Benelux 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1247]
Here i want to propose another combo S:444/460.

This time it appeared in BA.5.2.7 (S:444M)  .

Defining  mutations
 > A28330G > C1627T > C27513T > C27012T > G12310A > C16616A > C17958T > T2058C > A22893T > T22942G
S:N460K (T22942G)

**EDITED**
Gisaid query: NSP2_M418T,Spike_K444M,Spike_N460K 
finds 13 sequences

Number of sequences from Usher:  11

<details>
<summary>Expand for EPI_ISLs</summary>
EPI_ISL_15250146
EPI_ISL_15223056
EPI_ISL_15285602
EPI_ISL_15313211
EPI_ISL_15433780
EPI_ISL_15422617
EPI_ISL_15285895
EPI_ISL_15216299
EPI_ISL_15374736
EPI_ISL_15175819
</details>

Countries:
![Schermata 2022-10-22 alle 14 03 15](https://user-images.githubusercontent.com/87669813/197338007-dad26128-ed3f-47e8-80fe-cb9775983f0d.png)

CovSpectrum: BA.5.2.7* (Nextclade) + S:N460K finds 10
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AN460K&nextcladePangoLineage=BA.5.2.7*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Tree:
![Schermata 2022-10-22 alle 13 56 06](https://user-images.githubusercontent.com/87669813/197337634-5b1ecbb3-fd42-4f49-acbf-340e73c4fb3a.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_237c9_3aaa70.json?c=pango_lineage_usher&label=nuc%20mutations:T22942G

**Comment by FedeGueli** [comment]
New query posted above finds 13 seqs.

**Comment by FedeGueli** [comment]
15 seqs now with NSP2_M418T,Spike_K444M,Spike_N460K : 
The new sequences are from: one from Chile, one from Germany

**Comment by FedeGueli** [comment]
Two more sequences from netherlands

**Comment by FedeGueli** [comment]
three more sequences from Luxembourg is going quite fast @corneliusroemer

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage CY.1 with 3 newly designated sequences, and 0 updated designations. Defining mutation T22942G (S:N460K) (following A22893T (S:K444M)).

**Comment by FedeGueli** [comment]
Thx @InfrPopGen !

**Comment by Mydtlwn** [comment]
Is it not good that CY.1 in the file lineage_notes.txt is placed under CW? After all, CY.1 is a child of Ba.5.2.7, and there is a big difference between them.
