### ISSUE TITLE
Sublineage of BA.5.1.3 with N:ins211SESF (>900 sequences)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1249]
### **Description**
**Sub-lineage of:** BA.5.1.3
**Earliest sequence:** 2022-5-12, Germany, Schleswig-Holstein — EPI_ISL_12824704
**Most recent sequence:** 2022-10-16, Denmark, Syddanmark — EPI_ISL_15467625
**Countries:** Total sequences via CovSpectrum—Germany (517), USA (71), Denmark (53), France (43), Sweden (32), Netherlands (22), etc.
**Number of Sequences:** About 926
**GISAID Query:** N_ins211SESF, Spike_V289I
**CovSpectrum Query:** Nextcladepangolineage:BA.5.1.3* & ins_N:211:SESF
**Mutations on top of BA.5.1.3:**
**AA Insertions:** N:ins211SESF
**Nucleotide Insertions:** ins_28906:AGCGAAAGCTTT
 
**USHER Tree**
It’s not really possible to do a proper Usher tree for this one. I tried uploading the 30 most recent sequences to form an Usher tree, and Usher scattered them in several different places on the tree. There’s a sublineage with 51 sequences that has S:T747I, almost all of which are located in the United States. I went ahead and created an Usher tree for those (permalink below), but it’s not a real Usher tree for the lineage, which I don’t know how to create.
 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.5.1.3%2BN_Insertion_USA_S-T747I_Branch_subtreeAuspice1_genome_2016c_5dede0.json
 
**Evidence**
I can’t recall seeing insertions in N in any other lineage. BA.5.1.3 is destined to go extinct as BQ.1.1, XBB*, & the rest take over, so this insertion will go with it, barring some unforeseen recombination. But it’s fascinating nonetheless, particularly given the novel sgmRNA at N:203-204 that all B.1* lineages possess. I believe this insertion would be a part of the shortened protein formed by this sgmRNA sequence (which a recent paper called N* to distinguish it from N proper).

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/33738461/197426831-8bea1876-d882-4d82-8fdb-f40f63ef3b7e.png">
 
**Genomes**
[BA.5.1.3 + N_ins211SESF - GISAID_hcov-19_ids_2022_10_24_00_29.csv](https://github.com/cov-lineages/pango-designation/files/9847961/BA.5.1.3.%2B.N_ins211SESF.-.GISAID_hcov-19_ids_2022_10_24_00_29.csv)

**Comment by AngieHinrichs** [comment]
Right, UShER sees only substitutions not indels, so it can't see this one.  

Complicating matters, many genome assembly pipelines don't handle indels very well, so it could be that the true number of sequences with the insertion is a lot bigger than 900.  Does it seem pretty well confined to BA.5.1.3 or do you see more than a few matches outside BA.5.1.3?

**Comment by ryhisner** [comment]
As far as I can tell, it's confined to BA.5.1.3. There are 929 results for N_ins211SESF, Spike_V289I on GISAID, and only 45 sequences for N_ins211SESF, -Spike_V289I. I looked at the 45 sequences without S:V289I, and almost all of them have missing or bad coverage in the S:289 area and are categorized as BA.5.1. 

There are just three exceptions, all BE.1.1 from Germany. They have all the BE.1.1 ORF1ab mutations: ORF1a:Q556K, ORF1a:L3829F, and ORF1b:M1156I. I don't know whether these are due to contamination, recombination, or independent evolution of the insertion. The last seems very unlikely, particularly given that these three sequences are from Germany, where the vast majority of this BA.5.1.3 lineage is from. My guess us contamination. They were all from the same lab and look like they were sequenced on the same day. EPI_ISL_13382717, EPI_ISL_13382972, EPI_ISL_13386020

**Comment by corneliusroemer** [comment]
Interesting observation. The insertion does however not seem to confer a growth advantage, it appears neutral. About 10% of BA.5.1.3 have contained the insertion over the past few months:

<img width="2100" alt="image" src="https://user-images.githubusercontent.com/25161793/198109673-b8bab37a-db76-44cf-b829-758ee7c37826.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BA.5.1.3&aaInsertions1=ins_N%3A211%3ASESF&nextcladePangoLineage1=BA.5.1.3&analysisMode=CompareToBaseline&

**Comment by Mydtlwn** [comment]
This can be observed for another week, although it doesn't make any sense.

**Comment by InfrPopGen** [comment]
Thank you for proposing this as a pango lineage. As it is not showing much growth advantage in most countries (slight growth in US and France, but probably just "drift"), this can be closed for now. Please re-propose or request re-opening should this one expand rapidly in the future.
