### ISSUE TITLE
Sublineage of BA.5.2.20 (or less likely BA.5.2.36) with S:N148S, S:K150E, S:N334K, S:444T & ORF1a:E726K (34 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1251]
### **Description**
**Sub-lineage of:** BA.5.2.20
**Earliest sequence:** 2022-9-28, Sweden, Stockholm — EPI_ISL_15307037
**Most recent sequence:** 2022-10-13, Sweden, Skane — EPI_ISL_15479721, & Stockholm — EPI_ISL_15485325
**Countries circulating:** Sweden
**Number of Sequences:** 9
**GISAID Query:** Spike_N148S, Spike_K150E, Spike_N334K, NSP2_E546K
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2.20* & S:N148S & S:K150E & S:N334K
**Substitutions on top of BA.5.2.36:**
**Spike:** N148S, K150E, N334K, K444T
**ORF1a:** E726K
**Nucleotide:** G2441A, T6067C, A22005G, A22010G, C22564A, A22893C

 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.5.2_%2B_N148S%2CK150E%2CN334K%2CK444T%2CORF1aE762K_v.2_subtreeAuspice1_genome_aa5b_700b80.json
 
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/33738461/197636263-5bd72dc0-7b8e-46bb-8bfb-019808b36283.png">

**Evidence**
It looks like a mini-saltation from BA.5.2.20 led to this lineage, most likely from a long-term infection in one individual. One of the nine sequences is placed earlier in the tree, without K444T, but it has zero RBM coverage, so it almost certainly belongs with the other eight, meaning all nine sequences here are identical. This suggests rapid growth, though numbers are too small to be sure about anything yet.

Six of the sequences here are from Stockholm, but three of the most recent four have been from Skane. Skane appears to be a county in the extreme south of Sweden, over 300 miles away from Stockholm, so it seems there has already been some geographic spread here. 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15307020, EPI_ISL_15307037, EPI_ISL_15393194, EPI_ISL_15393348, EPI_ISL_15393415, EPI_ISL_15479635, EPI_ISL_15479693, EPI_ISL_15479721, EPI_ISL_15485325
</details>

**Comment by ryhisner** [comment]
The first sequence in this lineage outside of Sweden showed up today—in Colorado, right in the middle of the US. It has also picked up S:R346I, a mutation not found in any of the previous sequences. EPI_ISL_15585173

Also, I just ran an Usher tree, and now Usher places this lineage within BA.5.2.36, not BA.5.2.20. There are no reversions, and the proximity of Sweden to England—the primary home of BA.5.2.36—suggests this is the right placement. I've changed the title of the proposal to reflect this. There's also now a sequence from Bahrain that shares a synonymous mutation with this lineage but none of the AA mutations.

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/33738461/199120582-b7997aa8-47a6-48b4-abe9-9e6b989a5da8.png">

**Comment by AngieHinrichs** [comment]
> now Usher places this lineage within BA.5.2.36, not BA.5.2.20

Yes -- both BA.5.2.20 and BA.5.2.36 are one mutation after the undesignated BA.5.2 > 4-mutation big branch with ORF1b:T1050N.  BA.5.2.20 is branch > C23707T and BA.5.2.36 is branch > A22893C (S:K444T).  These sequences have both C23707T and A22893C, so they fit equally well on either branch by parsimony.

**Comment by corneliusroemer** [comment]
Homoplasic mutations should be given less weight. Counting mutations/parsimony is fine in most cases but for tie-breaking it makes sense to use likelihood approach. Hence this is more likely to be a BA.5.2.20 rather than BA.5.2.36 sublineage.

**Comment by ryhisner** [comment]
Seven more sequences of this lineage uploaded yesterday, all from Sweden, bringing the total to 17.

**Comment by ryhisner** [comment]
Four more sequences from Sweden uploaded yesterday, making 26 sequences in total now.

**Comment by FedeGueli** [comment]
33 sequences as today with Spike_N334K,Spike_K444T,Spike_n148S
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_293bb_cf0890.json?label=id:node_6892983

**Comment by ryhisner** [comment]
Nothing for 9 days, so I'm pretty sure this one is dead.

**Comment by ryhisner** [comment]
Not entirely dead, apparently, as four more sequences from Sweden showed up today. Still clearly on the decline, however.
