### ISSUE TITLE
Multiple different,independent BA.5.2+orf1b:1050N/ BA.5.2.1 recombinants with BQ.1* 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1252]
**1) BA.5.2.35 from NDL**

EPI_ISL_15375002 involving BA.5.2.35 a singlet from Netherland
![Schermata 2022-11-02 alle 09 57 36](https://user-images.githubusercontent.com/87669813/199445795-70192861-23d6-455e-bcdc-6862343e7979.png)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_1eac6_22e2c0.json?c=pango_lineage_usher&label=nuc%20mutations:T6979G

**2) BA.5.3.1 from Israel** 

EPI_ISL_15474168  
EPI_ISL_15474152  
EPI_ISL_15486358
both related from Israel:
![Schermata 2022-11-02 alle 09 58 38](https://user-images.githubusercontent.com/87669813/199446233-fed4c47b-359c-4fa8-8592-07e7b8e61525.png)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_1eac6_22e2c0.json?c=pango_lineage_usher&label=nuc%20mutations:C1627T

3) one more from england defined by orf1a:N508S : England/LSPA-325A5E6F/2022|2022-10-10

Gisaid Query :NSP13_T127N,Spike_R346T,M_D3N,-NSP12_Y273H,Spike_N460K,SPike_K444T please check with nextclade if S:N460K comes from T22942A (just 3 out of 4 found by this query have T22942A)

**3) N_S33F,-Spike_R346T,Spike_N460K,Spike_K444T,NSP12_Y273H**

Here another EPI_ISL_15501352  BF.7/BQ.1 recombinant from Switzerland 
Gisaid query N_S33F,-Spike_R346T,Spike_N460K,Spike_K444T,NSP12 Y273H
![Schermata 2022-10-26 alle 15 32 22](https://user-images.githubusercontent.com/87669813/198039429-d78df5e2-3e4f-4763-8339-0f6525e01c43.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_43fa3_934e30.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G27084T

**Comment by AnonymousUserUse** [comment]
I think the title may be edited to "Multiple different, independent BA.5.2 + BQ.1.1 recombinants". The information of mutation ORF1b:T1050N and the information of sublineage BA.5.2.1 is not so important for the title, and without them, the readability of title can be significantly increased.

**Comment by FedeGueli** [comment]
> I think the title may be edited to "Multiple different, independent BA.5.2 + BQ.1.1 recombinants". The information of mutation ORF1b:T1050N and the information of sublineage BA.5.2.1 is not so important for the title, and without them, the readability of title can be significantly increased.

disagree sorry it is a multiple issue without a real proposal just to highlight and to be, possibly, public monitored.

Orf1b:1050N is a key in increased transmissibility in BA.5.2 ( it alone gives a 6-8% of advantage versus plain BA.5.2/Ba.5.2.1) and it is for that reason i opened an issue.

**Comment by FedeGueli** [comment]
Closing this for the moment , most of the ones found by the query above are now DB.1 and the BA.5.3.1 recomb seems not going anywhere from israel and neither the english one: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_8f5f_54dd30.json?label=nuc%20mutations:C1627T

same for the swiss BF.7 recombinant: still a singlet
