### ISSUE TITLE
XAY.1 with S:346T (1 sequence, South Africa)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1255]
One South African XAY.1 with extra S:R346T has recently been uploaded:

```
hCoV-19/South_Africa/NICD-CRDM12706/2022|EPI_ISL_15509716|2022-10-13
```

It is likely that similar sequences will appear given the well established benefit of S:346T.

**Comment by FedeGueli** [comment]
Thx Cornelius i ve seen that yesterday and hit me the fact it was very recent from very young patient and pneumonia surveillance. For some reasons i mistakenly thought XAY had already 346T. Thx for noticing

**Comment by ErikoGomez** [comment]
2nd Sequence collected earlier on October 5th from Gauteng South Africa, EPI_ISL_15497216. This one also has S:A1174V.

**Comment by FedeGueli** [comment]
2 more sequence with S:346T  both collected on 11 october in Gauteng

with Spike_R346T,Spike_F186L,Spike_P621S i found 3 in total

@corneliusroemer i think at the fifth it should be designated.

**Comment by corneliusroemer** [comment]
@ErikoGomez the one you mentioned doesn't fit together with the others.

<img width="2064" alt="image" src="https://user-images.githubusercontent.com/25161793/199622549-4385ac89-614c-470e-8189-f4b9b060f64b.png">
