### ISSUE TITLE
Sublineage of BE.1.1 with S:D1260N, ORF9b:T72I & ORF3a:H150R (24 sequences, mainly in Quebec, Canada)

### ISSUE THREAD

**Issue by ilevade** [cov-lineages/pango-designation#1256]
Description
Sub-lineage of: BE.1.1
Earliest sequence: 2022-9-25
Most recent sequence: 2022-10-03
Countries circulating: Canada (18 sequences), United States, Denmark, Spain, Switzerland, France
Number of Sequences: 24

CovSpectrum: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AD1260N&nextcladePangoLineage=BE.1.1&

Substitutions on top of BE.1.1:
S:D1260N, ORF9b:T72I & ORF3a:H150R

USHER Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_535d_994770.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:G28079T

![image](https://user-images.githubusercontent.com/31353633/198129262-491791b1-d1bc-45f2-a360-1d058acd2133.png)

Genomes: 
EPI_ISL_15328523
EPI_ISL_15435858
EPI_ISL_15350969
EPI_ISL_15291371
EPI_ISL_15349064
EPI_ISL_15415989
EPI_ISL_15288255
EPI_ISL_15288265
EPI_ISL_15415735
EPI_ISL_15419878
EPI_ISL_15351201
EPI_ISL_15408189
EPI_ISL_15335397
EPI_ISL_15351204
EPI_ISL_15288234
EPI_ISL_15351172
EPI_ISL_15351173
EPI_ISL_15415755
EPI_ISL_15351477
EPI_ISL_15351231
EPI_ISL_15415886
EPI_ISL_15415952
EPI_ISL_15404698
EPI_ISL_15415819

**Comment by InfrPopGen** [comment]
Thank you for submitting this lineage proposal. As this lineage has been showing clear growth disadvantages over the past two months (e.g. in Canada, US, and France), this proposal can be closed for now. Please feel free to re-propose or request re-opening should this lineage show marked advantages in the future.
