### ISSUE TITLE
Misclassification of lineages as AY.2

### ISSUE THREAD

**Issue by batson** [cov-lineages/pango-designation#126]
Hello wonderful PANGO team!

I have noticed a number of lineages being misclassified as `AY.2`, a B.1.617.2 + K417N lineage seen in the United States.

I believe that all of the non_US sequences classified on GISAID as `AY.2` are misclassified, either because they contain a convergent `K417N` mutation (and are not necessarily B.1.617.2 even) or because they are B.1.617.2, and are a near outgroup to `AY.2`, but do not share other lineage-defining mutations:

![Screen Shot 2021-06-30 at 1 50 19 PM](https://user-images.githubusercontent.com/1261162/124029560-20a0aa00-d9aa-11eb-8235-86a9b92f73e8.png)

It is possible this could be addressed by either:

1. Adding more of the US lineages with strong phylogenetic support to the defined set of lineages for `AY.2`, which might improve the machine learning model when it is trained next
2. Updating the model (especially if scorpio is being used given VOC status)

**Comment by batson** [comment]
Here is a spreadsheet giving proposed PANGO lineage designations for all samples currently being called `AY.2`, cc: @AngieHinrichs . Includes nextclade (for QC) and USHER placements. 
[AY2_update.csv](https://github.com/cov-lineages/pango-designation/files/6744353/AY2_update.csv)

Nextstrain tree: https://nextstrain.org/fetch/hgwdev-demo-angie.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_hgwdev_demo_angie_6020_cec4e0.json

**Comment by AngieHinrichs** [comment]
Thanks so much Josh!  I will take a look & add some new designations.

**Comment by aineniamh** [comment]
This looks like the issue has been resolved! Thanks @AngieHinrichs!
