### ISSUE TITLE
XBD sublineage with S:N188S circulating in Hong Kong 24 sequences 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1260]
I spotted a sublineage of XBD defined by a spike mutation (NTD ) Spike_N188S _**(@c19850727 spotted first very early cause this mutation appeared in one of the first sequence of XBD)**_ 

Gisaid Query: Spike_N188S,NSP3_P822S, NSP8_N118S, Spike_A1020S, M_D3N, -E_T11A finds 11 sequences all from Hong Kong

9 out of 11 sequences have acquired a further S2 mutation: Spike_P1143L

Covspectrum query : XBD* (Nextclade) + S:N188S finds 5 seqs
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AN188S&nextcladePangoLineage=XBD*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Usher shows just 5 cause 6 were uploaded just yesterday.
<img width="1169" alt="Schermata 2022-10-29 alle 21 04 12" src="https://user-images.githubusercontent.com/87669813/198848603-d15d7fba-9ba0-43fe-a8db-88adda770ff0.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3aa6_d78750.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C5192T,G22599C,T23019C,G24620T

List of sequences:
EPI_ISL_14810310, EPI_ISL_15169331, EPI_ISL_15269281,
EPI_ISL_15269284, EPI_ISL_15402333, EPI_ISL_15570972,
EPI_ISL_15570994, EPI_ISL_15570997, EPI_ISL_15571001,
EPI_ISL_15571004, EPI_ISL_15571006

Uploading these sequences on Usher the result is quite messy:
<img width="1154" alt="Schermata 2022-10-29 alle 21 18 06" src="https://user-images.githubusercontent.com/87669813/198849053-455c099a-12e4-423c-b4f0-d6278bef22ff.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6172_d7ad00.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22125G

**Comment by c19850727** [comment]
In the last batch of upload from Hong Kong on 2022-10-28, there were 9 XBD among a total of 78, and based on originating lab, there were likely 6 XBD among a total of 43 local cases.

![image](https://user-images.githubusercontent.com/86835836/198855860-29187023-8dc1-409c-8bf4-5388cbab0905.png)
(this is the originating lab for likely imported cases)

Interestingly, all 6 likely local XBD have additional S:N188S.

**Comment by FedeGueli** [comment]
Thanks @c19850727 ! So it seems to have a good prevalence there. We will see with next batches

**Comment by FedeGueli** [comment]
No new sequence up this week i'll close for now

**Comment by FedeGueli** [comment]
12 seqs as today.

**Comment by FedeGueli** [comment]
still no in flow of new sequence i will wait a week and then closing this one, (waiting just to check if it has anything to do with the apparent chinese wave )

**Comment by FedeGueli** [comment]
21 seqs as today

**Comment by Mydtlwn** [comment]
It may be necessary to extend the opening time of uploading sequences in this place for half a month later.

**Comment by FedeGueli** [comment]
24 seqs i m closing this one
