### ISSUE TITLE
New sublineage of BA.5.2 + Orf1b:1050N with S:A435S (129 sequences Uk,Usa, Czechia, Slovenia , Germany, Netherlands,Sweden, Indonesia, South Korea )

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1263]
I noticed recently a new Spike mutation S:A435S in some BA.5.2 sublineages, after monitoring it for a bit while interestingly popped up independently in different sublineages of BA.5.2 +Orf1b:1050N as can be seen here:
<img width="1163" alt="Schermata 2022-10-30 alle 17 38 53" src="https://user-images.githubusercontent.com/87669813/198890364-23d635ac-4428-4f36-87d4-189aae693407.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_34645_ea4410.json?branchLabel=aa%20mutations&label=nuc%20mutations:G22599C

I think just one of them deserves to be proposed, luckily i managed to get an accurate Gisaid Query for it :
**_-NS3_M125I,-N_D144N,NSP13_T127N,Spike_A435S_**
that finds 82 sequences excluding main other lineages with S:A435S , defined one by N_D144N ( USA ) and the other by Orf3a_M125I (Czechia).

On usher tree i count 86 sequences from 6 Countries ( Uk, Usa, Czechia, Slovenia, Germany, Netherlands)
<img width="1144" alt="Schermata 2022-10-30 alle 17 44 01" src="https://user-images.githubusercontent.com/87669813/198890606-fedfa28e-e9ae-4323-9b4b-96001188f048.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34645_ea4400.json?branchLabel=aa%20mutations&c=gt-S_435&label=nuc%20mutations:C18441A

**Defining mutations**:

BA.5.2 +G12310A +Orf1b:t1050N ( C16616A) + C27012T +C27513T 
then C29614T 
then C18441A 
then T6661C + S:A435S (G22865T)

If i go to compare this new sublineage with parental BA.5.2 +Orf1b:1050N, that reached 22% as share of global sequences in the last weeks, it shows a growth advantage , too early to say if S:A435S is certainly beneficial but i think it is better monitoring it where it pops up.:
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=orf1b%3A1050N&nextcladePangoLineage=BA.5.2*&aaMutations1=Orf1b%3A1050N%2CS%3AA435S&nucMutations1=C29614T%2CC18441A%2CT6661C&nextcladePangoLineage1=BA.5.2*&analysisMode=CompareToBaseline&

CovSpectrum Query: BA.5.2* (Nextclade) + S:A435S + C29614T, C18441A, T6661C + ORF1b:T1050N
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1b%3A1050N%2CS%3AA435S&nucMutations=C29614T%2CC18441A%2CT6661C&nextcladePangoLineage=BA.5.2*&aaMutations1=orf1b%3A1050N&nextcladePangoLineage1=BA.5.2*&

List of sequences:
[contributors.csv](https://github.com/cov-lineages/pango-designation/files/9896340/contributors.csv)

**Comment by ryhisner** [comment]
For a long time, the spike area from 417-440 was pretty much devoid of mutations. With this new breed of variants, we're starting to see some show up though. The main ones I've noticed are D420N (found in ~40 BE.1.1.1 sequences & elsewhere), D428G/Y, T430I, and A435S. It will be interesting to see if any of them catch on.

**Comment by oobb45729** [comment]
D420N is expected to have some immune escape effects, similar to N460K.
T430I makes sense too, as it expected to stabilize RBD a bit and it may increase immune escape a bit.
It's harder to predict what D428G/Y will do, since D428 may interact with other parts of the S protein.
A435S, on the other hand, is located deep inside the RBD core. It may not doing much aside from destabilizing the RBD.

**Comment by FedeGueli** [comment]
@ryhisner thx Ryan! In my view better proposing that BE.1.1.1, this github page is the only one real time library on mutations beyond the designation fact. Always useful to see if something grows and how much fast.

**Comment by FedeGueli** [comment]
92 as today slow growth.

**Comment by FedeGueli** [comment]
100 sequences as today , newly found in South Korea (not travel related), Sweden and Indonesia

**Comment by FedeGueli** [comment]
i checked this lineage and it is no more monophyletic so i m closing it. ( the core of the one i proposed stayed identicasl without any growth for more than 10days )
