### ISSUE TITLE
Potential BM.2 sublineage with spike T478E and L452R (9 seqs as of 2022-10-30)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1264]
### Description
**Sublineage of**: BM.2 (aka BA.2.75.3.2)
**Earliest sequence**: 2022/08/23 (India-MH)
**Most recent sequence**: 2022/10/21 (Ireland)
**Countries circulating**: India (4), Australia (1), Belgium (1), Ireland (3)

**Mutations on top of BM.2**: S:T478E, S:L452R, ORF7b:A15D, N:P122S
The 3 most recent genomes from Ireland also have additional ORF1a:N1662S, S:Q183K, ORF1b:T40I

**GISAID Query**: NS7b_A15D, N_P122S

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/198894959-5f0d056a-6bee-4c59-b453-7468f508c949.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_f031_ebc870.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22994G,C27799A,C28637T,T29760C

### Genomes:
EPI_ISL_15300752, EPI_ISL_15300765, EPI_ISL_15309364,
EPI_ISL_15309368, EPI_ISL_15425760, EPI_ISL_15533187,
EPI_ISL_15576764, EPI_ISL_15576773, EPI_ISL_15576806

**Comment by FedeGueli** [comment]
Great catch @c19850727 ! I ve seen these ones too, i didnt realize it is a saltation branch.
I would add N:P122S as defining .

My gisaid query is query: Spike_T478E,N_P122S

**Comment by c19850727** [comment]
Thanks @FedeGueli! was a bit sleepy last night and forgot N:P122S. 

Already edited!

**Comment by FedeGueli** [comment]
11 seqs as today with Spike_T478E,N_P122S

**Comment by FedeGueli** [comment]
3 NEW SEQUENCES 2 FROM AUSTRALIA AND 1 FROM IRELAND

**Comment by InfrPopGen** [comment]
Thank you for submitting this lineage proposal. As there has been little growth since the initial proposal, and none over the past month, this proposal can be closed for now. Please feel free to re-propose or request re-opening should this lineage show marked advantages in the future.

**Comment by FedeGueli** [comment]
27 sequences now of this sublineage with last sequence from Ireland sampled in 2023
