### ISSUE TITLE
Sublineage of BA.5.2.6 + NSP3:M988L (38 sequences)

### ISSUE THREAD

**Issue by VirologiaHUCA** [cov-lineages/pango-designation#1267]
**By VirologiaHUCA**

**Description**
**Sub-lineage of:**  BA.5.2.6
**Earliest sequence:** 2022-07-14
**Most recent sequence:** 2022-10-06
**Countries circulating:** Denmark (1), France (4), Germany (1), Iceland (1), Luxembourg (1), Mauritius (11), Netherlands (1), Reunion (1), Spain (4 Asturias), Sweden (1), United Kingdom (12)

**Written description**
In BA.5.2.6 variants, this clade gained the NSP3: M988L mutation. 

**Genomes**
EPI_ISL_14211398; EPI_ISL_14757135; EPI_ISL_14835389; EPI_ISL_14925011; EPI_ISL_14950666; EPI_ISL_15057937; EPI_ISL_15059468; EPI_ISL_15059645; EPI_ISL_15059646; EPI_ISL_15075591; EPI_ISL_15115481; EPI_ISL_15116312; EPI_ISL_15116349; EPI_ISL_15140630; EPI_ISL_15195175; EPI_ISL_15195194; EPI_ISL_15204459; EPI_ISL_15207871; EPI_ISL_15213494; EPI_ISL_15287441; EPI_ISL_15287447; EPI_ISL_15287448; EPI_ISL_15292335; EPI_ISL_15302331; EPI_ISL_15303991; EPI_ISL_15304127; EPI_ISL_15304134; EPI_ISL_15304135; EPI_ISL_15304141; EPI_ISL_15304194; EPI_ISL_15304205; EPI_ISL_15327277; EPI_ISL_15349349; EPI_ISL_15365470; EPI_ISL_15370282; EPI_ISL_15386599; EPI_ISL_15407530; EPI_ISL_15407742

**Evidence**

![image](https://user-images.githubusercontent.com/105294581/198984537-42f4928f-eaa9-4c4a-aeea-05b2e0d30f71.png)

**Comment by alurqu** [comment]
I believe that NSP3:M988L is also ORF1a:M1806L. The CoV-Spectrum query for that is https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nextcladePangoLineage=BA.5.2.6*&aaMutations=ORF1a%3AM1806L.  As of 2022-11-01, I find 52 sequences of which 42 have good quality ratings.

Location looks like Mauritius with spread to Europe, North America, and Australia.

**Comment by InfrPopGen** [comment]
Thank you for proposing this as a pango lineage. As it is showing a relative growth disadvantage over the past three months in most regions (Mauritius, France, UK, Germany, etc), this can be closed for now. Please re-propose or request reopening should this lineage change to show a clear advantage in the future.
