### ISSUE TITLE
Issues with B.1.429 designations

### ISSUE THREAD

**Issue by andersonbrito** [cov-lineages/pango-designation#127]
By Anderson Brito

Description: Some genomes are being incorrectly designated as B.1.429, within B.1.1.7 and many other existing lineages/clades (see list below)

Countries circulating: USA

Genomes: List available [here](https://github.com/andersonbrito/pango/blob/master/auspice/pango_b1429_genomes.txt)

Evidence: https://nextstrain.org/community/andersonbrito/pango/b1429?c=category&f_category=VOC%20%28B.1.429%29&m=num_date&p=grid

**Comment by rmcolq** [comment]
When I tried following this up (with a subset of your IDs) using https://genome.ucsc.edu/cgi-bin/hgPhyloPlace it looks like most of them end up near the B.1.427 and B.1.429 sequences:
<img width="1425" alt="Screenshot 2021-07-12 at 21 14 16" src="https://user-images.githubusercontent.com/9866043/125350334-87cd3f80-e356-11eb-9298-b7123086ea38.png">
In both usher and pangolearn mode, most of them are assigned B.1.427 and B.1.429. And when I look with scorpio and I can't see any evidence of them belonging to B.1.1.7 
Alpha (B.1.1.7) counts
```
query,ref_count,alt_count,ambig_count,other_count,rule_count,support,conflict,call
USA/CA-CDPH-UC1445/2021,22,0,1,0,0,0.000000,0.956500,False
USA/CA-CHLA-PLM43780750/2020,23,0,0,0,0,0.000000,1.000000,False
USA/TX-HMH-MCoV-30614/2021,23,0,0,0,0,0.000000,1.000000,False
USA/TX-HMH-MCoV-30609/2021,21,2,0,0,0,0.087000,0.913000,False
USA/AZ-TG724526/2020,23,0,0,0,0,0.000000,1.000000,False
USA/CA-CDC-FG-007710/2021,23,0,0,0,0,0.000000,1.000000,False
USA/CA-CDC-FG-007510/2021,22,0,1,0,0,0.000000,0.956500,False
USA/CA-CDC-FG-007662/2021,23,0,0,0,0,0.000000,1.000000,False
USA/CA-CDC-FG-018168/2021,23,0,0,0,0,0.000000,1.000000,False
USA/CA-CDC-FG-018336/2021,23,0,0,0,0,0.000000,1.000000,False
USA/CO-CDC-FG-019134/2021,3,10,7,3,1,0.434800,0.130400,False
USA/OR-OHSU-5798/2020,21,0,2,0,0,0.000000,0.913000,False
USA/CA-CDC-FG-005993/2021,23,0,0,0,0,0.000000,1.000000,False
USA/CA-CDC-FG-005500/2021,21,0,2,0,0,0.000000,0.913000,False
USA/CA-CDC-FG-005555/2021,23,0,0,0,0,0.000000,1.000000,False
USA/WA-CDC-UW21050548715/2021,19,4,0,0,0,0.173900,0.826100,False
USA/AZ-ASU4062/2021,21,0,2,0,0,0.000000,0.913000,False
USA/WA-UW-21042440940/2021,19,4,0,0,0,0.173900,0.826100,False
USA/CA-ALSR-6291/2021,23,0,0,0,0,0.000000,1.000000,False
USA/WA-UW-67836/2021,9,11,3,0,0,0.478300,0.391300,False
USA/TX-HMH-MCoV-29176/2021,23,0,0,0,0,0.000000,1.000000,False
USA/TX-CDC-LC0064671/2021,20,0,3,0,0,0.000000,0.869600,False
USA/OH-21AM-060CO03207/2021,23,0,0,0,0,0.000000,1.000000,False
USA/FL-CDC-FG-022837/2021,23,0,0,0,0,0.000000,1.000000,False
USA/TX-HMH-MCoV-19489/2020,23,0,0,0,0,0.000000,1.000000,False
USA/TX-HMH-MCoV-24936/2021,23,0,0,0,0,0.000000,1.000000,False
USA/FL-CDC-STM-000011041/2021,22,0,1,0,0,0.000000,0.956500,False
USA/CA-RD614-CV0054/2021,23,0,0,0,0,0.000000,1.000000,False
USA/TX-HMH-MCoV-24409/2021,23,0,0,0,0,0.000000,1.000000,False
Mexico/TAM-INMEGEN-06-01-323/2021,21,1,1,0,0,0.043500,0.913000,False
USA/AZ-TG745509/2020,23,0,0,0,0,0.000000,1.000000,False
```
So I don't understand your issue.

Caveat: scorpio doesn't think they are a perfect fit for Epsilon (B.1.429/B.1.427) either

**Comment by andersonbrito** [comment]
Hi @rmcolq,

Thank you for letting me know. Based on what I see now on GISAID, those misplaced genomes are still labelled as B.1.429 (Pango v.3.1.5 2021-06-15). Let's see if with the next version of pangoLEARN will classify those in other lineages.

How does pangolin behaves upon recombinants or artefactual hybrids from poor quality genome assemblies?

**Comment by AngieHinrichs** [comment]
The way I interpret Anderson's link https://nextstrain.org/community/andersonbrito/pango/b1429?c=category&f_category=VOC%20%28B.1.429%29&m=num_date&p=grid, most of the sequences in his custom build that are assigned B.1.429 appear as expected, in or near the B.1.429 branch of the inferred tree, i.e. they appear to be assigned correctly:

![image](https://user-images.githubusercontent.com/186983/125356801-934f4500-e31b-11eb-9df6-f36cd86b379f.png)

@andersonbrito correct me if I'm wrong, but I think Anderson is pointing out that some of the sequences that are assigned B.1.429 (and thus pass the filter) are in other branches -- IMO those are the more interesting sequences from a pango-designation issue point of view.  :)  For example, there are a few in the B.1.1.7 branch:

![image](https://user-images.githubusercontent.com/186983/125356856-a530e800-e31b-11eb-8617-66e9533ac290.png)
If I click on the samples in that branch, I see their IDs are
USA/WA-UW-67836/2021
USA/CO-CDC-FG-019134/2021
USA/CA-CDC-LC0059298/2021

So at least according to Anderson's tree (iqtree? nextstrain/augur pipeline), those 3 samples were assigned B.1.429 incorrectly, and probably should have been assigned B.1.1.7.

@andersonbrito in the future if you subtract out the sequences that appear correct, that would be very helpful!

The latest version of pangolin & pangoLEARN no longer calls all of those sequences as B.1.429 or B.1.427 -- here are ones that are assigned to other lineages now:
```
taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,version,pangolin_version,pangoLEARN_version,pango_version,status,note
USA/CA-LACPHL-AF00443/2021,B.1.2,0.0,0.9163051575303449,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
USA/WA-UW-67836/2021,B.1,0.0,0.9379911538626702,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
USA/CA-CDC-FG-018336/2021,B.1.2,0.0,0.9738174273858922,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
USA/CO-CDC-FG-019134/2021,B.1.1.7,0.0,0.9263263002518016,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
USA/AZ-ASU4062/2021,B.1.2,0.0,0.924926099808729,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
USA/WI-WSLH-214223/2021,B.1.2,0.0,0.6256737982772993,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
USA/OR-OHSU-5798/2020,B.1.595,0.0,0.959570887673538,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
USA/CA-CDC-LC0059298/2021,B.1.1.7,0.0,0.9276298673141965,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
USA/CO-CDPHE-2100984825/2021,B.1.2,0.0,0.5945899869295903,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
Mexico/TAM-INMEGEN-06-01-323/2021,B.1.617.2,0.0,0.9873474735893866,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
USA/CA-CHLA-PLM43780750/2020,B.1,0.0,1.0,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
USA/CA-CDPH-UC1279/2020,B.1.561,0.0,0.7123965221013172,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
USA/CA-CDPH-UC1679/2020,B.1.1.192,0.0,0.8334433962264151,,,,PLEARN-v1.2.36,3.1.7,2021-07-09,v1.2.36,passed_qc,
```
So two of the three in the B.1.1.7 branch (USA/CO-CDC-FG-019134/2021 and USA/CA-CDC-LC0059298/2021) are now assigned consistently with the tree; one is assigned to B.1 (USA/WA-UW-67836/2021).
 
Looking at ones that fall outside of B.1.429 & B.1.427 on the UCSC tree, some look better with the latest pangoLEARN, some don't.  These look better to me with the latest pangoLEARN:

* USA/CA-CDPH-UC1279/2020 is assigned B.1.561 by latest pangolin/pangoLEARN, consistent w/UCSC tree
* USA/WA-UW-67836/2021 is assigned B.1 - fair enough, it has an interesting mix of mutations and clusters with other interesting-mix samples with an assortment of pangolin assignments (not the very latest version; and the ones closest to USA/WA-UW-67836/2021 are assigned B.1.1.7), there may be cases of contamination or something more interesting, don't have time to look into it: https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-127-subtree33.json?branchLabel=Spike%20mutations&c=pango_lineage&label=nuc%20mutations:T25563G

These don't look better, perhaps they should be added as representatives for B.1 / A.2.5:

* USA/WA-UW-2021040207846/2021 is still assigned B.1.427 but looks like a B.1 (has none of S:S13I, W152C, L452R)
* USA/TX-CDC-LC0064671/2021 is still assigned B.1.429 but clusters with A.2.5
* USA/TX-HMH-MCoV-19489/2020 is still assigned B.1.429 but looks like B.1
* USA/TX-HMH-MCoV-24409/2021 is still assigned B.1.429 but looks like B.1

Not sure what to make of these:

* Mexico/TAM-INMEGEN-06-01-323/2021 is now assigned B.1.617.2 by pangoLEARN (not scorpio) but is in this... interesting cluster which may not be in the right place on the UCSC tree: https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-127-subtree26.json?branchLabel=Spike%20mutations&c=pango_lineage&label=nuc%20mutations:G11417T,A28910T
* USA/WA-UW-21042440940/2021 and USA/NV-NSPHL-NV2054693/2020 are still assigned B.1.429; they and sequences they cluster with appear to my eye to have an odd mix-and-match of B.1.429 and B.1.1.7 mutations (contamination??): https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-127-subtree1.json?branchLabel=Spike%20mutations&c=pango_lineage&label=nuc%20mutations:C8947T
* USA/CA-CDC-FG-018336/2021 is assigned B.1.2 - it looks like almost-but-not-quite B.1.429, I would have to spend more time looking to see if B.1.2 seems correct given its mutations.

**Comment by AngieHinrichs** [comment]
Idle thought: I see a lot of cases (and a lot of odd little branches of the UCSC tree) where I wonder if contamination would explain what I'm seeing (odd mix of mutations and "pango rainbow" when coloring nodes by pangolin/pangoLEARN assignment).  I wonder if there's enough data now to make a good contamination detector/deconvolver.  I should look to see if someone has already attempted that...

**Comment by andersonbrito** [comment]
Hi @AngieHinrichs,

Your interpretation is correct. As you identified, those genomes you highlighted are misclassified as B.1.429, and they are still listed as such on gisaid. Next time I'll flag only the problematic genomes.

**Comment by chrisruis** [comment]
Thanks @andersonbrito and @AngieHinrichs. Just looking through these following up on Angie's work:
Sequences USA/WA-UW-67836/2021, USA/WA-UW-2021040207846/2021 and USA/NV-NSPHL-NV2054693/2020 have quite a few Ns and as they have >5% ambiguities, we can't include them in the designations. It might be that the high N content is causing trouble with trying to assign them.

USA/TX-HMH-MCoV-19489/2020 doesn't seem to have many ambiguities across its whole genome but does have ambiguity at quite a few of the positions in the epsilon constellation, which might make it tricky to place accurately. This was actually included in the designations before as B.1.429 so I've now taken this out of the designations.

USA/TX-HMH-MCoV-24409/2021 does look like a B.1 as it lacks most of the mutations in the epsilon constellation. So I've designated this as B.1.

I agree with Angie that USA/WA-UW-21042440940/2021 requires more of a look - it has quite a few of the epsilon constellation mutations, but not all of them and not S:L452R. We're working on some tools for this currently so should be able to look at this one with those soon.

USA/CA-CDC-FG-018336/2021 doesn't look like it shares mutations with B.1.2. It seems to cluster within the B.1.427/B.1.429 region of the UShER tree but again has ambiguity at several of the positions that define B.1.427/B.1.429. So again I don't think we should designate this one.

USA/TX-CDC-LC0064671/2021 looks like it has the defining A.2.5.2 mutations so I've designated this as A.2.5.2.

Mexico/TAM-INMEGEN-06-01-323/2021 is still being assigned B.1.617.2 but it doesn't look like it is B.1.617.2 as it's missing most of the B.1.617.2 constellation SNPs. I'm not sure where this one should go currently though!

These changes are in [v1.2.39](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.39)

**Comment by chrisruis** [comment]
Just revisiting the sequences that weren't resolved before.

In the latest UShER tree, USA/WA-UW-21042440940/2021 clusters in a small clade of USA sequences upstream of the main B.1.427/B.1.429 clade. This clade convergently acquires several mutations that are also acquired leading to the main B.1.427/B.1.429 clade. However, these mutations appear to drop in and out within the small clade, as do several other mutations acquired along deep branches within the small clade. This is therefore consistent with contamination or something else unusual with these sequences so I don't think we should designate this clade. I've removed sequences USA/CA-UCSF-UC1042/2021 and USA/CA-UCSF-UC1040/2021 from the designations in [v1.2.72](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.72) that are in this small clade and were previously designated B.1.429.

Mexico/TAM-INMEGEN-06-01-323/2021 appears to cluster within B.1.632 which was designated recently based on #156 and this sequence is included in the B.1.632 designations.
