### ISSUE TITLE
Fast BA.5.10.1 (S:R346T) sublineage with S:144del and Orf1a:Q1198R (156 Sequences) 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1270]
I recently noticed that BA.5.10.1 seemed to be accelerating and i was monitoring since the start a sublineage of it with S:144del 

Now i could state with some certainty that the acceleration is due to this S:144del sublineage that is over 100 sequences now. 

Gisaid Query : NSP3_Q380R,Spike_A262S,E_S50G,Spike_R346T
Defining mutations:
BA.5.10.1 
then T13794C + Orf1a:Q1198R +S:Y144del

Gisaid Query : NSP3_Q380R,Spike_A262S,E_S50G,Spike_R346T finds 110 sequences
CovSpectrum query: BA.5.10* (Nextclade) + T13794C + S:R346T, ORF1a:Q1198R finds 108 sequences 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A346T%2COrf1a%3AQ1198R&nucMutations=T13794C&nextcladePangoLineage=BA.5.10*&aaMutations1=S%3AR346T&nextcladePangoLineage1=BA.5.10*&

while surprisingly on USHER i found 176 sequences of it mainly from UK:
<img width="1156" alt="Schermata 2022-10-31 alle 19 21 10" src="https://user-images.githubusercontent.com/87669813/199081160-13aafb82-7d24-410b-9466-6b21983f3b30.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_51c0_fea0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T13794C

As BA.5.10 likely emerged in Philippines this sublineage of it is already a global one spread in 18 countries in 4 continents:
<img width="1158" alt="Schermata 2022-10-31 alle 19 21 41" src="https://user-images.githubusercontent.com/87669813/199081259-54708b38-6aaa-4ebf-b4c9-b971a6f543d8.png">

Recent  Richard Yunlong Cao paper highlighted how much S:144del could help in immune evasion properties of a strain:
https://www.biorxiv.org/content/10.1101/2022.09.15.507787v4

I suggest a rapid designation of this one looking at growth advantage versus parental BA.5.10.1:
<img width="944" alt="Schermata 2022-10-31 alle 19 24 50" src="https://user-images.githubusercontent.com/87669813/199081891-aba9b01e-d04b-43db-84e4-a1a6ab6f38dc.png">
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AR346T&nextcladePangoLineage=BA.5.10*&aaMutations1=S%3A346T%2COrf1a%3AQ1198R&nucMutations1=T13794C&nextcladePangoLineage1=BA.5.10*&analysisMode=CompareToBaseline&

@corneliusroemer i noticed that actually nextclade wrongly attributes 1000+ seqs to BA.5.10.1 so i changed the collection 24 query, i think its growth rate was consequently underestimated through today

**Comment by cvejris** [comment]
BM.4.1.1 and descendants also have Orf1a:Q1198 mutation (to K, though)

**Comment by FedeGueli** [comment]
Now 159 sequences . it is doubling at 7 or 8 days. i think it deserves to be designated @InfrPopGen @corneliusroemer

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage DF.1 with 11 newly designated sequences, and 2 updated designations from BA.5.10.1. Defining mutation A3858G (ORF1a:Q1198R) (following T13794C)

**Comment by FedeGueli** [comment]
thx @InfrPopGen !
