### ISSUE TITLE
Sublineage of BA.5.1.5 with S:K444Q, S:V1264L (15 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1272]
### **Description**
**Sub-lineage of:** BA.5.1.5
**Earliest sequence:** 2022-9-19, France, Ile de France — EPI_ISL_15334930, EPI_ISL_15295691
**Most recent sequence:** 2022-10-19, England — England/PHEC-YY8JN6E/2022, England/PHEC-YY8JN7K/2022
Most recent sequence on GISAID: 2022-10-16, England — EPI_ISL_15580394
**Countries circulating:** England (10), France (4), Denmark (1)
**Number of Sequences:** 15
**GISAID Query:** Spike_K444Q, Spike_P1263Q, Spike_V1264L
**CovSpectrum Query:** Nextcladepangolineage:BA.5.1.5 & S:K444Q & S:V1264L
**Substitutions on top of BA.5.1.5:**
**Spike:** K444Q, V1264L
**Nucleotide:** C683T, T10516C, A22892C, G25352T, T28510C
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.5.1.5%20%2B%20K444Q%20%2B%20V1264L%20-%20subtreeAuspice1_genome_52e3_33cb0.json
 
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/33738461/199110799-8be52db3-f890-4371-8fee-5e0fc157d56c.png">

**Evidence**
In the Bloom Lab RBD ACE2 Binding/RBD Expression Heat Map, S:K444Q not only has the best ACE2 binding of any K444 mutation, it also has the best RBD expression (a proxy for stability) of any of the 19 possible mutations.  
https://jbloomlab.github.io/SARS-CoV-2-RBD_DMS_Omicron/RBD-heatmaps/

![image](https://user-images.githubusercontent.com/33738461/199111115-30dae63a-899c-4256-9384-853f1b644ff5.png)
 
In addition, as I pointed out in issue #1110, the deep mutational scanning done by Yunlong Cao & others in, “Imprinted SARS-CoV-2 humoral immunity induces converging Omicron RBD evolution” found K444Q to be the second-best mutation at that residue for evading neutralizing antibodies from breakthrough-infection sera in a BA.2, a BA.2.75, and a BA.5 background. 

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/33738461/199118301-4daa0bf2-b106-4987-acea-25d841cafa26.png">

S:V1264L is a convergent mutation that’s evolved many times, presumably because in some contexts it provides a slight advantage. Most of these sequences are very recent: Four were uploaded from England to GISAID just today, and there are an additional four from England that appear on the Usher tree but have not yet appeared on GISAID.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15271187, EPI_ISL_15295691, EPI_ISL_15334930, EPI_ISL_15345321, EPI_ISL_15365447, EPI_ISL_15405904, EPI_ISL_15536129, EPI_ISL_15580394, EPI_ISL_15580519, EPI_ISL_15580714, EPI_ISL_15580715
</details>

**Comment by Mydtlwn** [comment]
Ba.2.83, BH.1 and AY.4.2.2 all seem to have mutations at position 1264.

**Comment by Mydtlwn** [comment]
Okay, I'm wrong. It shouldn't be BH.1, it should be Ba.2.38.3

**Comment by ryhisner** [comment]
Yes, several Delta lineages had it, and BG.2, a sublineage of BA.2.12.1, also had it. It appears pretty frequently in small quantities in almost every lineage.
<img width="970" alt="image" src="https://user-images.githubusercontent.com/33738461/199148021-72ce3fc3-65c6-4be2-96af-edd1fccc9d5a.png">

**Comment by ryhisner** [comment]
One sequence each from Switzerland uploaded Friday and one from Spain uploaded today. The Switzerland sequence has S:P1162L while the sequence from Spain has S:T299I. They appear on branches entirely separate from each other and from the England branch. 
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/33738461/201542763-ae1992f0-f122-461f-b259-76947439ecfc.png">

**Comment by ryhisner** [comment]
This one had sputtered, but three recent sequences (collection dates Nov 14-15, upload dates Nov 24, Nov 29, Nov 29) from France, Germany, and Japan (with travel from Malta) have brought the total number of sequences up to 21. Two of the these three recent ones also have S:T299I. 
EPI_ISL_15904187, EPI_ISL_15923514, EPI_ISL_15929282

**Comment by InfrPopGen** [comment]
Thank you for submitting this lineage proposal. As there has been little growth advantage over the parent, and this has declined over the past month, this proposal can be closed for now. Please feel free to re-propose or request re-opening should this lineage show marked advantages in the future.

**Comment by ryhisner** [comment]
I thought this one had disappeared, but it continues to hang around in various regions of France and to some extend in the surrounding countries. I don't think this merits reopening, but I'm surprised at its staying power. 38 sequences as of January 28, 2023.
