### ISSUE TITLE
Should recombinant alias keys all use unaliased names for parity

### ISSUE THREAD

**Issue by ciscorucinski** [cov-lineages/pango-designation#1273]
Since all non-recombinants use unaliased names in [Alias_key.json](https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.json), would it be good to have parity with the recombinants? Therefore `XBB` would use `B.1.1.529.2.10.1.1` and `B.1.1.529.2.75.3.1.1.1` instead of `BJ.1` and `BM.1.1.1`

I was trying to get all the omicron recombinant lineages and I noticed that there was no simple way to do it programmatically.  I was using a Google Sheets QUERY with 'contains 'BA' and it got all Omicron recombinants except XBB (which has BJ and BM aliases). Note: there isn't a good way to search for each BA realiased names in Google Sheets as there would be for Python.

**Comment by corneliusroemer** [comment]
To increase legibility, it makes sense to not use totally unaliased names in alias_key.json, this way there's also a reduced risk of typos

You can unalias the components with https://github.com/corneliusroemer/pango_aliasor

**Comment by ciscorucinski** [comment]
I didn't think it would happen, but it would make more sense for you to use the aliasor to more safely uncompress them to avoid typos while maintaining parity.
