### ISSUE TITLE
Large South African BA.5 + C1627T sublineage (without 28330G) with S:R346T and Orf7a:S44P (200 sequences - around 10% prevalence in South Africa )

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1277]
Here i want to propose a sublineage of BA.5 in the branch with C1627T 
(As BA.5.10* -**without the BA.5.2 defining mutation A28330G (orf9b:D16G)-**
see on this downsampled tree:
<img width="1153" alt="Schermata 2022-11-02 alle 01 24 35" src="https://user-images.githubusercontent.com/87669813/199366299-80d64498-09bc-49aa-90d0-9cdaaeab2620.png"> )

It is defined by **_C27389T + S:R346T and then Orf7a:S44P_** ( i leave to @corneliusroemer @InfrPopGen where to start the lineage as also without Orf7a:44P is currently circulating)

**Tree**:
<img width="1153" alt="Schermata 2022-11-02 alle 01 27 08" src="https://user-images.githubusercontent.com/87669813/199366640-44a7090d-68e8-4c50-9fd9-ff94fac185ad.png">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_55e19_1b6950.json?c=pango_lineage_usher&label=nuc%20mutations:G22599C

While **Covspectrum** finds only 108 sequences with C27389T, C1627T + ORF7a:S44P, S:R346T
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf7a%3AS44P%2CS%3AR346T&nucMutations=C27389T&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Gisaid query brings _NS7a_S44P,Spike_R346T_ back 122 viruses collected between July and today 

Usher finds 197 sequences sampled in 9 countries:
<img width="1146" alt="Schermata 2022-11-02 alle 01 31 13" src="https://user-images.githubusercontent.com/87669813/199366992-08ff6fd5-431d-458d-a55a-fce175928baf.png">

List of sequences

<details>
<summary>Expand for EPI_ISLs</summary>

EPI_ISL_14789095
EPI_ISL_14812670
EPI_ISL_14859495
EPI_ISL_14859496
EPI_ISL_14859498
EPI_ISL_14859500
EPI_ISL_14975904
EPI_ISL_15083991
EPI_ISL_15208224
EPI_ISL_15259568
EPI_ISL_15267854
EPI_ISL_15269978
EPI_ISL_15269979
EPI_ISL_15269980
EPI_ISL_15269986
EPI_ISL_15269987
EPI_ISL_15269988
EPI_ISL_15269990
EPI_ISL_15269991
EPI_ISL_15269992
EPI_ISL_15269993
EPI_ISL_15270000
EPI_ISL_15270001
EPI_ISL_15270002
EPI_ISL_15270004
EPI_ISL_15270011
EPI_ISL_15270012
EPI_ISL_15270013
EPI_ISL_15270015
EPI_ISL_15270016
EPI_ISL_15270017
EPI_ISL_15270018
EPI_ISL_15270019
EPI_ISL_15270021
EPI_ISL_15270022
EPI_ISL_15270023
EPI_ISL_15270024
EPI_ISL_15270025
EPI_ISL_15270026
EPI_ISL_15270032
EPI_ISL_15270033
EPI_ISL_15279365
EPI_ISL_15322109
EPI_ISL_15330499
EPI_ISL_15331370
EPI_ISL_15357495
EPI_ISL_15388892
EPI_ISL_15406113
EPI_ISL_15427791
EPI_ISL_15430779
EPI_ISL_15433788
EPI_ISL_15433790
EPI_ISL_15434508
EPI_ISL_15434511
EPI_ISL_15434514
EPI_ISL_15434534
EPI_ISL_15434542
EPI_ISL_15435503
EPI_ISL_15435505
EPI_ISL_15435508
EPI_ISL_15435538
EPI_ISL_15435539
EPI_ISL_15443743
EPI_ISL_15443745
EPI_ISL_15443749
EPI_ISL_15443750
EPI_ISL_15443751
EPI_ISL_15443752
EPI_ISL_15443765
EPI_ISL_15444827
EPI_ISL_15444837
EPI_ISL_15444847
EPI_ISL_15444848
EPI_ISL_15444849
EPI_ISL_15444850
EPI_ISL_15444851
EPI_ISL_15444852
EPI_ISL_15444853
EPI_ISL_15444854
EPI_ISL_15444855
EPI_ISL_15444858
EPI_ISL_15444859
EPI_ISL_15446772
EPI_ISL_15469791
EPI_ISL_15471087
EPI_ISL_15471144
EPI_ISL_15471220
EPI_ISL_15471339
EPI_ISL_15473038
EPI_ISL_15494248
EPI_ISL_15496154
EPI_ISL_15502404
EPI_ISL_15502407
EPI_ISL_15502408
EPI_ISL_15502409
EPI_ISL_15502410
EPI_ISL_15502411
EPI_ISL_15502413
EPI_ISL_15502416
EPI_ISL_15502417
EPI_ISL_15502418
EPI_ISL_15502420
EPI_ISL_15502421
EPI_ISL_15502423
EPI_ISL_15502426
EPI_ISL_15502427
EPI_ISL_15502430
EPI_ISL_15502431
EPI_ISL_15502433
EPI_ISL_15502434
EPI_ISL_15502443
EPI_ISL_15502445
EPI_ISL_15502453
EPI_ISL_15502456
EPI_ISL_15502458
EPI_ISL_15502463
EPI_ISL_15512339
EPI_ISL_15577189
EPI_ISL_15602529
</details>

Prevalence in South Africa seems around 5-10% :
<img width="1099" alt="Schermata 2022-11-02 alle 01 38 31" src="https://user-images.githubusercontent.com/87669813/199367711-db8873d1-0620-4fba-beef-7c288caf3289.png">

Addendum : looking forward in Covspectrum i noticed that this lineage is characterized by a deletion in Orf1ab: 
**Orf1a:G82-V86del** in 100% of sequences 
a vast mayority of sequences carry also a Orf7a deletion: 
**Orf7a:Q90-E95Del**
<img width="1005" alt="Schermata 2022-11-02 alle 01 45 14" src="https://user-images.githubusercontent.com/87669813/199368438-ce171582-b1e9-4d47-9b49-d563dd62148a.png">

**Comment by FedeGueli** [comment]
@corneliusroemer nextclade has some issues in recognizing this one:

![Schermata 2022-11-08 alle 19 54 34](https://user-images.githubusercontent.com/87669813/200651093-75fe4c61-b5d3-4696-9c07-a8a1fc18519c.png)

Maybe better to start it from Orf7a:S44P ??

**Comment by FedeGueli** [comment]
Spotted a sibling lineage of BA.5.11 with C1627T + S:R346T and saltation 
( ORF1a:L788F, orf1a:I1714T, orf1a:M1769V, orf1a:S2022LOrf1a:K3353R
S:K77R, S:H245 S:R346T,S: V445F
ORF3a:S74F, Orf3a:V255A)

:
![Schermata 2022-11-08 alle 20 57 55](https://user-images.githubusercontent.com/87669813/200662624-f53c5551-8897-47b5-88c1-aeb060ad316d.png)
![Schermata 2022-11-08 alle 20 58 23](https://user-images.githubusercontent.com/87669813/200662701-e3b9c52e-7d70-4c0c-afd7-e38cbc521a93.png)
![Schermata 2022-11-08 alle 20 58 46](https://user-images.githubusercontent.com/87669813/200662772-469a7c06-9313-4257-8f62-f598e6b33799.png)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2806c_aa7fe0.json?c=pango_lineage_usher&label=nuc%20mutations:C2627T,T5406C,A5570G,C6040T,C6330T,A10323G,C10450T,C20844T,A21792G,C22295A,G22599C,G22895T,C25613T,T26156C,C27294T,C28435T,A28654G


2 sequences found with Spike_R346T,NS3_S74F,Spike_K77R

put here to be monitored if this will trespasses the 5 seqs threshold i will propose it.

@corneliusroemer @InfrPopGen

**Comment by JosetteSchoenma** [comment]
Since Denmark was reporting a big increase in BA.5.11, ![Screenshot_20221124-223141_Photos.jpg](https://user-images.githubusercontent.com/94831035/203873520-f16aff49-b8e0-4cb9-a2c9-8df5c2a66772.jpg)
I went to search for them on GISAID, but I only found 18. Turns out that many of them have no coverage at NS7a_44.

Changing the query to NS7a_E92D, Spike_R 346T resulted in 301 Danish samples (thanks for the tip, @FedeGueli !). Nextclade calls most of them BA.5.11, 17 BA.5 and 1 that is indeed different, BA.4.6.1.
Usher finds several subbranches with mainly Danish samples. One branch with S:A1016S, another with N:T166I and a smaller one with ORF1ab:L3781I.

I am adding -Spike_W152L, Spike_L452R and -NSP12_M196L to the GISAID query to exclude BA.4.6.1, BA.2.75* and CP.1.

In total the query finds 481 samples. 300 from Denmark, 18 from Australia, 10 from the USA, 6 from the Netherlands and 122 from South Africa. But some from all around the world.

**Comment by JosetteSchoenma** [comment]
The query still isn't perfect. Around 20 samples aren't really BA.5.11. -S:N658S will lose some BA.4.6 from the USA eg.. 
Maybe I can find a better one tomorrow.

**Comment by FedeGueli** [comment]
Thx @JosetteSchoenma i m using this one:

-N_P151S,NS7a_E92D, R346T,-E_T11A

**Comment by JosetteSchoenma** [comment]
Oh, the -N_P151S is a good idea to exclude BA.4*. Thanks!

This still includes 15 CP.1 though. Plus 9 other BA.5* and even 2 Alpha from Japan!

It's a tough one.

**Comment by FedeGueli** [comment]
thx @JosetteSchoenma yes i will try a better one later ;)

**Comment by FedeGueli** [comment]
@JosetteSchoenma why ot proposing the sublineages?? it is  a branch stemming out of the BA.5 politomy and growing now means it is worth to be described further. i think @corneliusroemer and @InfrPopGen will be ok with designating everything that could have any epi relevance in the actual scenario. great work with query btw! thx!
