### ISSUE TITLE
 South African BA.5.3.1 + T28693C sublineage with S:R346T, Orf3a:P240S (72 sequences - 8% prevalence in SA)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1278]
Here i want to propose a sublineage of BA.5.3.1. circulating in South Africa in a branch with Orf6:M58L and Orf8:L4R which both immediately got reverted after it gained defining mutations S:R346T and Orf3a:P240S

Tree is quite messy but this lineage is circulating and deserves to be designated , please @corneliusroemer @AngieHinrichs help me if i m wrong:
<img width="1152" alt="Schermata 2022-11-02 alle 02 12 02" src="https://user-images.githubusercontent.com/87669813/199371452-c8931219-2e4d-495f-98ee-7ff31f5482a2.png">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_260a1_1c1f50.json?c=pango_lineage_usher&label=nuc%20mutations:T27904G

Angie, Cornelius to me the real tree starts here (ignoring the two nodes with reversions just after the start):
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_260a1_1c1f50.json?c=country&label=nuc%20mutations:G22
<img width="1143" alt="Schermata 2022-11-02 alle 02 13 22" src="https://user-images.githubusercontent.com/87669813/199371592-3b3aad80-ddc0-4ed1-94a2-e317643de8ad.png">
599C

Defining mutations are 
BA.5.3.1+ T28693C +S:R346T + Orf3a:P240S

Gisaid query : NS3_P240S,Spike_R346T,N_E136D finds 72 viruses

CovSpectrum query: BA.5.3.1 (Nextclade) + T28693C + S:R346T, ORF3a:P240S finds 64 viruses 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AR346T%2COrf3a%3AP240S&nucMutations=T28693C&nextcladePangoLineage=BA.5.3.1&aaMutations1=orf1b%3A1050N&nextcladePangoLineage1=BA.5.2*&

Countries. South Africa, Usa, Uk, Denmark, Australia

List of HQ sequences:
[contributors.csv](https://github.com/cov-lineages/pango-designation/files/9915055/contributors.csv)

Prevalence in South Africa around 8% :
<img width="1074" alt="Schermata 2022-11-02 alle 02 22 34" src="https://user-images.githubusercontent.com/87669813/199372630-929e8ce0-e0aa-4a09-9fb0-bdeab0a470d7.png">

**Comment by AngieHinrichs** [comment]
That is odd, I'm not sure what's going on there with the two reversions (with 4 intermediate mutations that seem to be shared by just enough sequences to link them).  Thanks for pointing that out.

**Comment by aviczhl2** [comment]
Anyone noticed this branch having a very long deletion on Orf7a? Is that real?

https://nextstrain.org/staging/nextclade/sars-cov-2
