### ISSUE TITLE
New BA.5.2 + orf1b:1050N sublineage with S:R346T (44seqs) Usa, Canada, Uk, Germany

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1279]
This is a sibling lineage of BA.5.2.25 sharing with it C1471T and T2698C
then it is defined by T8662C, A12976T, C4543T, S:R346T (G22599C)

Tree: 
![Schermata 2022-11-02 alle 10 16 18](https://user-images.githubusercontent.com/87669813/199451172-754473aa-8733-43ad-b909-dcf0e3391b53.png)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1eac6_22e2c0.json?c=pango_lineage_usher&label=nuc%20mutations:T2698C

CovSpectrum query :
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=T8662C%2CG22599C%2CA12976T%2CC4543T&nextcladePangoLineage=BA.5.2*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Countries: USa, Canada, Uk, Germany

<details>
<summary>Expand for EPI_ISLs</summary>
EPI_ISL_15263789
EPI_ISL_15499472
EPI_ISL_15465230
EPI_ISL_15178194
EPI_ISL_14984274
EPI_ISL_15458182
EPI_ISL_15490435
EPI_ISL_15531230
EPI_ISL_15467928
EPI_ISL_15313565
EPI_ISL_14718523
EPI_ISL_14740260
EPI_ISL_15427734
EPI_ISL_15313510
EPI_ISL_14696858
EPI_ISL_15425544
EPI_ISL_15524816
EPI_ISL_15386835
EPI_ISL_15265637
EPI_ISL_15545849
EPI_ISL_15501981
EPI_ISL_15352359
EPI_ISL_15229340
EPI_ISL_15476326
EPI_ISL_15502235
EPI_ISL_15468045
EPI_ISL_15468050
EPI_ISL_15313537
EPI_ISL_15098077
EPI_ISL_15502105
EPI_ISL_15043223
EPI_ISL_15531436
EPI_ISL_15269422
EPI_ISL_15413237
EPI_ISL_15546563
EPI_ISL_15490276

</details>

**Comment by corneliusroemer** [comment]
Designated as BA.5.2.39 in c67ba8fafb62ad5eefa425b0bf528f2137179af5
