### ISSUE TITLE
BA.2.3 Saltation lineage with several mutations (inc Spike R346T, Y449N, N460K, N481K and Q493L) from Philippines and Australia

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#1287]
**New proposed lineage**
By Tom Peacock

Description
Sub-lineage of: BA.2.3
Earliest Sequence: 2022-09-07
Latest Sequence: 2022-10-3

Countries circulating: Philippines (7 genomes), Australia (2 genomes)

Description:
Additional Spike mutations - P9L, Δ69-70, Δ144, V213E, G339N, R346T, Y449N, N460K, N481K, Q493L, K1205N
Additional non-Spike mutations - NSP4 – A146V
Synonymous mutations - T17901C, A28877T, G28878C

This appears to be yet another BA.2 saltation lineage (second generation BA.2) similar to BA.2.75, BJ.1, etc

Genomes:
EPI_ISL_15343178
EPI_ISL_15343197
EPI_ISL_15625844
EPI_ISL_15627678
EPI_ISL_15628269
EPI_ISL_15628276
EPI_ISL_15628277
EPI_ISL_15628290
EPI_ISL_15628301

Evidence:
![image](https://user-images.githubusercontent.com/79373149/199754304-8f211a68-2fed-469a-9c20-a15d7314b330.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_384c3_3d2810.json

Proposed lineage name: BA.2.3.x?

**Comment by MCB6** [comment]
In August, there was EPI_ISL_15625370 with N460K and 144del but without R346T in the same area of Western Visayas. BTW in the admittedly few October samples the new BA.2.3.x jumped to 30% there

**Comment by cvejris** [comment]
This lovely lineage has double nucleotide changes at three Spike AAs. The order of mutations (wt→BA.2→this):
213: V→G→E
339: G→D→N
493: Q→R→L
Among all designed BA.2 lineages, 3 DNCs are present only in XBB.1.3

**Comment by AngieHinrichs** [comment]
With the latest tree these are placed in BA.2.3.21 (BA.2.3 > C21588T/S:P9L).

**Comment by AngieHinrichs** [comment]
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-1287.json?c=pango_lineage_usher&label=nuc%20mutations:C21588T
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/186983/199835331-1feae542-7431-4cff-ad39-c0ba2502cf7d.png">

Australia/QLD0x011A1E/2022 and Australia/QLD0x0119E2/2022 are in the tree (in BA.2.3.21); the extra "N:S202C, N:S202T" branches are because the sequences have A28877T and G28878C which are masked after placement in the Omicron branch of the big tree (homoplasic -> tree problems), but they are not masked in the web interface.

**Comment by cvejris** [comment]
It still puzzles me how a lineage as minor as BA.2.3 could have given rise to four saltations
![image](https://user-images.githubusercontent.com/110762428/199948477-b7c77717-f8a4-4542-85c8-958d49f84652.png)

**Comment by corneliusroemer** [comment]
Why do you say it's a minor lineage?
It was the major BA.2 in Asia...

**Comment by cvejris** [comment]
Oops, I forgot to turn off the time limit for last 3 months at CovSpectrum. Thanks for reminding me! Still, the level of saltation in BA.2.3 is impressive

**Comment by FedeGueli** [comment]
Spike_G339N,Spike_Q493L

**Comment by ryhisner** [comment]
One of these showed up in USA, Michigan; Collection date September 27 — EPI_ISL_15702572

**Comment by aretchless** [comment]
Thanks Angie!
