### ISSUE TITLE
Potential CK.2.1.1 sub-lineage with Spike 252S from Australia, Denmark, South Korea and Spain [16 Sequences] with a sub-cluster of S:F490L and ORF7a: F87C

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#1288]
CK.2.1.1 sub-lineage with S:252S 

Countries: Australia, Denmark, South Korea, Spain
Total Sequences till date: 10
First Sequence: 10-06-2022 [S. Korea]
GISAID query: spike_g252s, spike_n460k, spike_k444n, e_v62f

Sub-cluster containing Spike F490L and Orf7a: F87C [5 sequences from Spain]

Contains convergent spike mutations: 452R, 444N, 460K, 486V, 490L, 493Q

![image](https://user-images.githubusercontent.com/98380390/199835437-183b8836-5aa4-4bc4-9564-2a79e49a7507.png)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_2a2a3_422c20.json?c=gt-S_490,444,452,486,493,252,460&label=nuc%20mutations:G22316A

Cov-Spectrum link: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=s%3Ag252s%2Cs%3An460k%2Cs%3Ak444n%2Ce%3Av62f&

Federico Gueli [@FedeGueli] prompted about the Spain cluster being part of a larger CK.2.1.1 + S:252S cluster

**Comment by FedeGueli** [comment]
@RajLABN many thanks for proposing this one, i fear we will hear about it in the next weeks. 
Two things i would like to add: the South Korean sample is realted to travel from Italy confirming a circulation in southern Europe.
While some of the spanish sequences are from very old people >95 unvaccinated people. I suspect that there could be a long term care facility outbreak

**Comment by FedeGueli** [comment]
11th sequence came from Australia

**Comment by FedeGueli** [comment]
13 sequences as today.

Now also in Connecticut Us

**Comment by RajLABN** [comment]
14th sequence uploaded from Singapore today

**Comment by corneliusroemer** [comment]
Designated as DG.1 - for the 490L cluster let's let it grow a bit outside of Spain first

**Comment by RajLABN** [comment]
8 more DG.1 (CK.2.1.1 w/ S:490L, S:252S) from Spain [@FedeGueli looks like it might be from the same cluster?]
EPI_ISL_15785016, EPI_ISL_15785022, EPI_ISL_15785027,
EPI_ISL_15785033, EPI_ISL_15785038, EPI_ISL_15785044,
EPI_ISL_15785050, EPI_ISL_15785055

**Comment by FedeGueli** [comment]
thx @RajLABN lets see if evolves in some new age range
