### ISSUE TITLE
Minor edit to the Alias for CU.1 

### ISSUE THREAD

**Issue by Sam8138** [cov-lineages/pango-designation#1289]
Thank you Angie Hinrichs.  I wanted to point these out, but was unsure the format or process and didn't want to spam your list. Thank you all for your excellent work.  <back to silent mode>

CU.1 Alias of BA.1.1.529.5.1.26.1, Central/Eastern Europe, S:T95I, S:T547K

should be: (extra "A", BA should be B)

CU.1 Alias of B.1.1.529.5.1.26.1, Central/Eastern Europe, S:T95I, S:T547K

**Comment by AngieHinrichs** [comment]
Thanks so much @Sam8138!  🙂  Fixed.
