### ISSUE TITLE
BQ.1.1 sublineage with Orf1a:A2529V and S:K182I circulating in USA (747 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1291]
Here i want to propose a sublinenage of BQ.1.1 defined by Orf1a:A2529V the infamous AY.4 defining mutation and a  spike mutation in the NTD

Defining mutations:
C18162T +Orf1a:A2529V plus S:K182I

Tree:
<img width="1089" alt="Schermata 2022-11-05 alle 09 58 13" src="https://user-images.githubusercontent.com/87669813/200112001-e02d617a-64d4-4007-9aec-800e987e5b9f.png">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_62e2d_621fa0.json?c=pango_lineage_usher&label=nuc%20mutations:C18162T

Gisaid query: Spike_K182I,NSP12_Y273H,Spike_K444T,Spike_N460K

Country: Usa

Nr of sequences: 20

List of sequences:
EPI_ISL_15465495, EPI_ISL_15465503-15465504, EPI_ISL_15481643,
EPI_ISL_15499816, EPI_ISL_15511626, EPI_ISL_15512551,
EPI_ISL_15539650, EPI_ISL_15545887, EPI_ISL_15575796,
EPI_ISL_15583358, EPI_ISL_15583582, EPI_ISL_15584012,
EPI_ISL_15584363, EPI_ISL_15584783, EPI_ISL_15584862,
EPI_ISL_15586041, EPI_ISL_15608935, EPI_ISL_15609350,
EPI_ISL_15622827

**Comment by FedeGueli** [comment]
23 viruses as today

**Comment by FedeGueli** [comment]
This is going on growing reaching 76 seqs as today @InfrPopGen @corneliusroemer  usher tree is very clear maybe worth a designation: 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_7e6b_e80a0.json?label=nuc%20mutations:C7851T,T24142C
<img width="1152" alt="Schermata 2022-11-25 alle 17 09 05" src="https://user-images.githubusercontent.com/87669813/204022572-9088739d-3459-4b26-84c7-1f6f299f9d8f.png">

**Comment by FedeGueli** [comment]
Reopening this one being now at 383 sequences maybe it is worth designating it

**Comment by FedeGueli** [comment]
399 as today

**Comment by ryhisner** [comment]
21 sequences of this uploaded from Costa Rica today, all of them with additional mutations ORF3a:T34M, M:V23L, and ORF1a:Q3346K (NSP5_Q83K). Using the nucleotide GISAID query 'C7851T, C18162T, A22107T, T24142C,' I find 490 sequences of this proposed lineage as of today, January 1.

**Comment by FedeGueli** [comment]
Thx @ryhisner ! updated the title with the new count. @InfrPopGen even if it is not a super fast one it grew steadily and with one NTD mutation plus a relevant outside spike mutation i think designate it could make sense.

**Comment by FedeGueli** [comment]
534 sequences as today it goes on growing, likely it is worth designating : @thomasppeacock

**Comment by FedeGueli** [comment]
585 sequences as today. it keeps growing . @corneliusroemer

**Comment by FedeGueli** [comment]
747 as today

**Comment by FedeGueli** [comment]
Now designated BQ.1.1.41
