### ISSUE TITLE
Fastly growing BR.2 with ORF8:S67F, at least 130 samples, Australia, USA and Japan

### ISSUE THREAD

**Issue by JosetteSchoenma** [cov-lineages/pango-designation#1292]
Description
Sub-lineage of: BR.2
Earliest sequence: 2022-10-03, Australia/New South Wales/Sydney — EPI_ISL_15362442
Most recent sequence: 2022-11-01, Australia/New South Wales/Sydney – EPI_ISL_15640795
Countries circulating: Australia (115, 103 NSW, 4 Queensland, 4 South Australia,  4 Victoria), Japan (1 with Travel history: Australia and Republic of Fiji)
Number of Sequences: 116, probably more, but several samples have N at ORF8:S67F.
GISAID Query: S403L, N118S, L452R, F486I, NS8_S67F, leaving out R346T, which is sometimes missing or reversed.
CovSpectrum Query: BR.2, ORF8:S67F, only 62 samples for now, since many are too recent
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf8%3AS67F&nextcladePangoLineage=BR.2*&

Prevalence in  Australia/New South Wales/Sydney
Week 40: 2/520 0,4%
Week 41: 20/669 3,0%
Week 42: 25/326 7,7%
Week 43: 52/458 11,4%
Week 44: 4/21

Usher tree:
Not up to date yet.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a9f4_64b0c0.json?branchLabel=aa%20mutations&label=nuc%20mutations:C21054T,T23018A
![image](https://user-images.githubusercontent.com/94831035/200119479-fc97f4da-df4b-4559-9332-63388e96e697.png)
![image](https://user-images.githubusercontent.com/94831035/200119527-51de7ef1-3d1e-4122-a05a-b2cd7d2fc7ee.png)

**Comment by FedeGueli** [comment]
Great catch @JosetteSchoenma could you fix please the gisaid query? are there a spike mutations?

**Comment by FedeGueli** [comment]
Spike_L452R, spike_F486I, NS8_S67F, 

  i think it is enough to find

**Comment by JosetteSchoenma** [comment]
Oke, thanks. 
Yeah, I often skip the 'Spike_ ' etc. part in GISAID. It usually works fine without. But of course, it is neater and more clear for others with.

**Comment by JosetteSchoenma** [comment]
6 from Tasmania, big Australian Island, uploaded today (black dots). The Usher tree has been updated. 123 samples on it now.
![image](https://user-images.githubusercontent.com/94831035/200307097-98fa0e7b-81ea-43b4-a621-1105333a1a9f.png)

**Comment by JosetteSchoenma** [comment]
6 new ones for Australia and 2 unrelated ones for the USA. From California and Florida.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BR.2.1 with 33 newly designated sequences, and 0 updated designations. Defining mutation C28093T (ORF8:S67F) (following C5812T)

**Comment by shay671** [comment]
Does this variant might have deletion at 21992-21994 ?

**Comment by JosetteSchoenma** [comment]
Not as far as I see in the latest samples, no.

It has G21987A (S:G142D) and A22001G (S:K147E) and I see no black lines in-between on Nextclade.

52-143 (AA) is often missing in Danish samples though and sometimes a bigger part is.
