### ISSUE TITLE
BA.5.1.22 sublineage with S:T385N and S:Y248S (23 sequences Germany)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1294]
Despite not being a threat in itself circulating already since august without any first glance advantage, i want to propose this lineage carrying an an unusual RBD mutation S:T385N.

Defining mutation:

BA.5.1.22 
C24082T then Orf1a:D2136N (C6582T )  then C8818T then  S:T385N (C22716A) then S:Y248S
<img width="1167" alt="Schermata 2022-11-06 alle 13 41 43" src="https://user-images.githubusercontent.com/87669813/200171348-15b61496-9b05-4d6a-859a-6724a0bbc2e0.png">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_41172_7a3c50.json?c=pango_lineage_usher&label=nuc%20mutations:C24082T

Gisaid query : Spike_T385N,Spike_Y248S 
finds 23 viruses:
EPI_ISL_14518240, EPI_ISL_14654797, EPI_ISL_14697439,
EPI_ISL_14699606, EPI_ISL_14699615, EPI_ISL_14886611,
EPI_ISL_15130525, EPI_ISL_15132471, EPI_ISL_15132507,
EPI_ISL_15132552, EPI_ISL_15132857, EPI_ISL_15134600,
EPI_ISL_15147594, EPI_ISL_15147741, EPI_ISL_15147754,
EPI_ISL_15147758, EPI_ISL_15147760, EPI_ISL_15147766,
EPI_ISL_15147780, EPI_ISL_15147786, EPI_ISL_15444165,
EPI_ISL_15446131, EPI_ISL_15647828

**Comment by ryhisner** [comment]
S:T385I is one of the convergent mutations we've seen in a lot of chronic-infection sequences, but T385N is rarely seen. I would be this is an immune-evasion mutation, maybe a T-cell epitope, like P272?

**Comment by FedeGueli** [comment]
@ryhisner maybe! or maybe something linked to Glycans? @thomasppeacock

**Comment by FedeGueli** [comment]
no new sequence i m closing this one.
