### ISSUE TITLE
BA.2.75 x XBB.3 recombinant [18 as of 2022-11-24, 15x US, 2x CH, 1x India]

### ISSUE THREAD

**Issue by emily-smith1** [cov-lineages/pango-designation#1296]
### **Description**
**Recombinant between**: BA.2.75 and XBB.3
**Earliest sequence**: 2022-09-29 (USA-CA)
**Most recent sequence**: 2022-10-18 (USA-VA)
**Countries circulating**: USA (CA, NY, VA, WV) 
**Potential breakpoint**: Between ORF1a:P1640S (present) and ORF1a:N4060S (absent)

Even though there are only 6 genomes this might be worth tracking for the time being to differentiate from XBB.3. 

### **Evidence**

**Mutation profile**:
![image](https://user-images.githubusercontent.com/84812104/200219946-3464e702-b07d-4485-a73f-a1efd8e327be.png)

**UShER link**: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_273f1_829070.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A2863G,C19554T,C25638T

![image](https://user-images.githubusercontent.com/84812104/200218730-73cd0aee-4306-4ef9-b950-b4dcd2df0acf.png)

**Genomes**:
EPI_ISL_15532165
EPI_ISL_15619029
EPI_ISL_15502095
EPI_ISL_15502008
EPI_ISL_15470614
EPI_ISL_15604093

**GISAID query**: NSP3_P822S, NSP14_I474V, Spike_L368I

^This also catches a sequence from Austria (EPI_ISL_15421276) but unsure if it’s part of the same recombination event. It’s in the UShER tree above as well if you zoom out.

**Comment by AngieHinrichs** [comment]
Good spot @emily-smith1 !  I believe this is the first proposed recombinant that has a recombinant for a parent.

**Comment by emily-smith1** [comment]
2 new sequences uploaded yesterday and today from Switzerland and USA-MA:
EPI_ISL_15722743
EPI_ISL_15724908

UShER link: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_413e9_d42c20.json?label=nuc%20mutations:G405A,C3796T,C3927T,C4586T,C5183T
![image](https://user-images.githubusercontent.com/84812104/201178168-e681fbec-93c1-474b-a0f1-591ac6768c7c.png)

**Comment by corneliusroemer** [comment]
Looks like there are 18 sequences of this recombinant now. Spread is all over the US and Switzerland where the lab in question (Risch) upsamples SGTP and hence tends to spot lots of XBBs.

There are 2 nearby clusters that could be independent recombinants, in particular one seems to be XBB.1

<img width="1539" alt="image" src="https://user-images.githubusercontent.com/25161793/203789280-2106e7c8-0da8-4329-a9d3-650293f0d855.png">

https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_249dd_f68bd0.json?c=gt-nuc_669,19459&f_userOrOld=GISAID%20and/or%20public&label=id:node_7408415

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XBN with 21 newly designated sequences, and 0 updated designations. Defining mutation C19554T (following A2863G,C25638T).

**Comment by FedeGueli** [comment]
51 as today

**Comment by JosetteSchoenma** [comment]
XBN
