### ISSUE TITLE
Sublineage of BA.5.2 + NSP3_E997G

### ISSUE THREAD

**Issue by VirologiaHUCA** [cov-lineages/pango-designation#1298]
By VirologiaHUCA
Description
Sub-lineage of: BA.5.2
Earliest sequence: 2022-09-06
Most recent sequence: 2022-09-27
Countries circulating: USA (4), Spain (3 Asturias), Portugal (1) 
Written description
In BA.5.2 variants, this clade gained the NSP3:E997G mutation.
Genomes
EPI_ISL_15043511, EPI_ISL_15106491, EPI_ISL_15159480, EPI_ISL_15220808, EPI_ISL_15349360, EPI_ISL_15349363, EPI_ISL_15349364, EPI_ISL_15114947

Evidence
![image](https://user-images.githubusercontent.com/105294581/200318623-4fce62df-a277-4e66-ac38-8be844ea13c2.png)

**Comment by InfrPopGen** [comment]
Thank you for submitting this lineage proposal. As there has been little growth over the past two months, and little sign of any advantage over the parent, this proposal can be closed for now. Please feel free to re-propose or request re-opening should this lineage show marked advantages in the future.
