### ISSUE TITLE
The pangolin web application don´t read my .fasta files

### ISSUE THREAD

**Issue by afmarti** [cov-lineages/pango-designation#13]
When I do the upload of my files, the software return this information:

FAILED: Sequence unable to be processed with Pangolin (unknown error)

I have already verified the files, and they are ok. It happens with 5 specific files, probably associate with P1 lineage, according to with mutations found. With the other  30 files, the process was ok.

**Comment by AngieHinrichs** [comment]
Hello @afmarti -- this github repository is for requesting new lineage designations.  https://github.com/cov-lineages/pangolin is a better place to report pangolin app / web-server problems.

**Comment by afmarti** [comment]
Thanks for your answer. However, it is happening just if .fasta files associate to clade 20J/501Y.V3, probably P1 lineage.
