### ISSUE TITLE
Two B.1 Honduras (exported to Mexico,USA,Spain) lineages with A688V,S735A,T1027I,P681H

### ISSUE THREAD

**Issue by babarlelephant** [cov-lineages/pango-designation#130]
Dear pangolin team, when filtering for the sequences having > 7 snp in common with EPI_ISL_2191153 two clear lineages appear as shown in the image, both assigned to B.1.

Otherwise you can see [there the tree that Usher](http://babarlelephant.free-hoster.net/dist/index.html?subtreeAuspice1_genome_d0a7_d4c020.sorted.jsoncompressed&c=gt-S_688,735,1027,681) gave me for the 1000 sequences context of this sequence.

According to recent sequences the two lineages represent 1-2% of cases in Mexico and > 90% in Honduras. Of note a related small lineage is assigned to B.1.241.

![image](https://user-images.githubusercontent.com/6537565/124076603-c73a8880-da46-11eb-97e9-48cf9d1f747b.png)

Lineage 1 
`EPI_ISL_2489776 EPI_ISL_1527724 EPI_ISL_2158309 EPI_ISL_1708605 EPI_ISL_2424183 EPI_ISL_2405214 EPI_ISL_1897352 EPI_ISL_1559549 EPI_ISL_1581905 EPI_ISL_2249654 EPI_ISL_1581977 EPI_ISL_2018480 EPI_ISL_2015165 EPI_ISL_1593654 EPI_ISL_1909355 EPI_ISL_2597996 EPI_ISL_2659570 EPI_ISL_2223040 EPI_ISL_1237662 EPI_ISL_1237674 EPI_ISL_1236224 EPI_ISL_2204773 EPI_ISL_1305168 EPI_ISL_1305396 EPI_ISL_2191162 EPI_ISL_2190425 EPI_ISL_2224406 EPI_ISL_2190322 EPI_ISL_2362696 EPI_ISL_2281652 EPI_ISL_2225330 EPI_ISL_2224665 EPI_ISL_2489774 EPI_ISL_2659353 EPI_ISL_2103199 EPI_ISL_1559530 EPI_ISL_2658680 EPI_ISL_2658597 EPI_ISL_1708608 EPI_ISL_1912945 EPI_ISL_1912939 EPI_ISL_1708609 EPI_ISL_1912940 EPI_ISL_1912941 EPI_ISL_2157348 EPI_ISL_1405591 EPI_ISL_2157350 EPI_ISL_2157351 EPI_ISL_2157356 EPI_ISL_2157353 EPI_ISL_2157354 EPI_ISL_1581952 EPI_ISL_2650526 EPI_ISL_1794455 EPI_ISL_2178726 EPI_ISL_2157347 EPI_ISL_2157344 EPI_ISL_2178750 EPI_ISL_2648257 EPI_ISL_2157352 EPI_ISL_2157355 EPI_ISL_2403709 EPI_ISL_2492493 EPI_ISL_1305362 EPI_ISL_2648261 EPI_ISL_2158308 EPI_ISL_2362693 EPI_ISL_2178759 EPI_ISL_2488759 EPI_ISL_1592226 EPI_ISL_1595608 EPI_ISL_2383220 EPI_ISL_2383230 EPI_ISL_2383229 EPI_ISL_2492492 EPI_ISL_1912943 EPI_ISL_1912944 EPI_ISL_1912942 EPI_ISL_2178728 EPI_ISL_2157349 EPI_ISL_2404855 EPI_ISL_2399619 EPI_ISL_1789722 EPI_ISL_1595607 EPI_ISL_2341031 EPI_ISL_2178774 EPI_ISL_2659343 EPI_ISL_2659312 EPI_ISL_2659562 EPI_ISL_2659539 EPI_ISL_1592767 EPI_ISL_1581878 EPI_ISL_2157346 EPI_ISL_2648245 EPI_ISL_2650536 EPI_ISL_2648262 EPI_ISL_2157345 EPI_ISL_1672590 EPI_ISL_2424205 EPI_ISL_2659434 EPI_ISL_2404854 EPI_ISL_2227431 EPI_ISL_2489777 EPI_ISL_2657685 EPI_ISL_2648246 EPI_ISL_1483053 EPI_ISL_1935508 EPI_ISL_1935446 EPI_ISL_1663176 EPI_ISL_2097328 EPI_ISL_2232583 EPI_ISL_1710980 EPI_ISL_1710978 EPI_ISL_1935506 EPI_ISL_1935510 EPI_ISL_1935507 EPI_ISL_1935509 EPI_ISL_1935511`

Lineage 2
`EPI_ISL_2222838 EPI_ISL_1236465 EPI_ISL_2191074 EPI_ISL_2659322 EPI_ISL_2190759 EPI_ISL_2658549 EPI_ISL_2483980 EPI_ISL_2659452 EPI_ISL_2659514 EPI_ISL_2659579 EPI_ISL_2402459 EPI_ISL_2373015 EPI_ISL_2508358 EPI_ISL_2508357 EPI_ISL_2508359 EPI_ISL_2508361 EPI_ISL_2508360 EPI_ISL_2617031 EPI_ISL_1912946 EPI_ISL_2443080 EPI_ISL_2659357 EPI_ISL_2443081 EPI_ISL_2533920 EPI_ISL_2636061 EPI_ISL_2617027 EPI_ISL_2598005 EPI_ISL_2443083 EPI_ISL_2443084 EPI_ISL_2443085 EPI_ISL_2178756 EPI_ISL_2652486 EPI_ISL_2598459 EPI_ISL_2658564 EPI_ISL_2658558 EPI_ISL_2598436 EPI_ISL_2178754 EPI_ISL_2224652 EPI_ISL_2380800 EPI_ISL_2098737 EPI_ISL_2158314 EPI_ISL_2492473 EPI_ISL_2492463 EPI_ISL_2492471 EPI_ISL_2492472 EPI_ISL_2492485 EPI_ISL_2492465 EPI_ISL_2362695 EPI_ISL_2443078 EPI_ISL_2617032 EPI_ISL_2492480 EPI_ISL_2225500 EPI_ISL_2492488 EPI_ISL_2492464 EPI_ISL_2400444 EPI_ISL_2443071 EPI_ISL_2492489 EPI_ISL_2598003 EPI_ISL_2492479 EPI_ISL_2158310 EPI_ISL_2617955 EPI_ISL_2158313 EPI_ISL_2424206 EPI_ISL_1191568 EPI_ISL_2650534 EPI_ISL_2157357 EPI_ISL_2157358 EPI_ISL_2648259 EPI_ISL_1662895 EPI_ISL_1694764 EPI_ISL_1543535 EPI_ISL_1935628 EPI_ISL_1662894 EPI_ISL_1662898 EPI_ISL_1662899 EPI_ISL_2650531 EPI_ISL_2648254 EPI_ISL_2650535 EPI_ISL_2648256 EPI_ISL_2650530 EPI_ISL_2648248 EPI_ISL_2648250 EPI_ISL_2648249 EPI_ISL_2648253 EPI_ISL_2648252 EPI_ISL_2648260 EPI_ISL_2362692 EPI_ISL_2405179 EPI_ISL_2659200 EPI_ISL_1660603 EPI_ISL_1660615 EPI_ISL_1660604 EPI_ISL_2424180 EPI_ISL_2224495 EPI_ISL_2443072 EPI_ISL_2617946 EPI_ISL_2650523 EPI_ISL_2648242 EPI_ISL_2650525 EPI_ISL_2650529 EPI_ISL_2621675 EPI_ISL_2404848 EPI_ISL_2392191 EPI_ISL_2392193 EPI_ISL_2424178 EPI_ISL_2424182 EPI_ISL_2362694 EPI_ISL_2597995 EPI_ISL_2392192 EPI_ISL_2659361 EPI_ISL_2659608 EPI_ISL_2659231 EPI_ISL_2491599 EPI_ISL_2103365 EPI_ISL_2308792 EPI_ISL_2405094 EPI_ISL_2400445 EPI_ISL_2405097 EPI_ISL_2400446 EPI_ISL_2448301 EPI_ISL_2277430 EPI_ISL_2598158 EPI_ISL_2652509 EPI_ISL_2501621 EPI_ISL_2657673 EPI_ISL_2657672 EPI_ISL_2190478 EPI_ISL_2190792 EPI_ISL_2189945 EPI_ISL_2190726 EPI_ISL_2212100 EPI_ISL_2190695 EPI_ISL_1305318 EPI_ISL_1581924 EPI_ISL_2203288 EPI_ISL_2205506 EPI_ISL_2211965 EPI_ISL_2211985 EPI_ISL_1935629 EPI_ISL_2211707 EPI_ISL_2222849 EPI_ISL_2103364 EPI_ISL_2489801 EPI_ISL_2489784 EPI_ISL_2139635 EPI_ISL_2424258 EPI_ISL_2423511 EPI_ISL_2557935 EPI_ISL_2612542 EPI_ISL_2473674 EPI_ISL_2650533 EPI_ISL_2404868 EPI_ISL_2617947 EPI_ISL_1581817 EPI_ISL_2203183 EPI_ISL_1716874 EPI_ISL_2405183 EPI_ISL_2617958 EPI_ISL_2617945 EPI_ISL_2373044 EPI_ISL_2598197 EPI_ISL_2658550 EPI_ISL_2425347 EPI_ISL_2650532 EPI_ISL_2650524 EPI_ISL_2650527 EPI_ISL_2648247 EPI_ISL_2558444 EPI_ISL_2382732 EPI_ISL_2382729 EPI_ISL_2648243 EPI_ISL_2676686 EPI_ISL_2528305 EPI_ISL_2601717 EPI_ISL_2304188 EPI_ISL_2601684 EPI_ISL_2483983 EPI_ISL_2483970 EPI_ISL_2424179 EPI_ISL_2245471 EPI_ISL_2558114 EPI_ISL_2558128 EPI_ISL_2659630 EPI_ISL_2659469 EPI_ISL_2659533 EPI_ISL_2659294 EPI_ISL_2650528 EPI_ISL_2598002 EPI_ISL_2501622 EPI_ISL_2689766 EPI_ISL_2598000 EPI_ISL_2617029 EPI_ISL_2598004 EPI_ISL_2445972 EPI_ISL_2399612 EPI_ISL_2146743 EPI_ISL_2620749 EPI_ISL_2399615 EPI_ISL_2392194 EPI_ISL_2424208 EPI_ISL_2399620 EPI_ISL_2404853 EPI_ISL_2399613 EPI_ISL_2399614 EPI_ISL_2424181 EPI_ISL_2404849 EPI_ISL_2424177 EPI_ISL_2424207`

**Comment by chrisruis** [comment]
Thanks @babarlelephant for submitting. We've designated your Lineage 1 as B.1.627 with 135 sequences in it. We've designated your Lineage 2 as B.1.628 with 256 sequences in it. These have been included in [v1.2.30](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.30)

In the latest UShER tree, it looks like a few sequences cluster in different locations so we haven't included these in the new designations:
EPI_ISL_2404855 - appears to cluster in B.1.429
EPI_ISL_2404868 - appears to cluster in B.1.1.7
EPI_ISL_2404849 - appears to cluster in A.2.5

**Comment by zach-hensel** [comment]
Lineage 2 here has many non-spike mutations of note unique from Lineage 1:

* N:S194L+N213Y; common region of mutations possibly disrupting N phosphorylation
* ORF1a: T3117A+A3143V+R3163S; all in Nsp4 and could impact DMV pore formation and RNA binding
* ORF1a:del3675/3677; common Nsp6 mutation in VOCs
* ORF1b: G662S; RdRp mutation **only common in B.1.617.2**
* ORF1b: P1000L; Nsp13 mutation **only common in B.1.617.2**

Similar to P314L both of the ORF1b mutations map near Nsp8 in replication complex structures.

Spike L18R and L452M also possibly interesting because of similarity but not identity to B.1.617.2.
