### ISSUE TITLE
Increasing prevalence of BA.5.3.1 sublineage in Amazonas, Brazil, with S:K444T, S:N460K and S:Y144del

### ISSUE THREAD

**Issue by akograf** [cov-lineages/pango-designation#1302]
By Rede Genômica Fiocruz

#Description:
We found a highly supported clade of BA.5.3.1 sequences in Amazonas, Brazil, harboring S:K444T, S:N460K and the deletions S:Y144. Such Amazonian BA.5.3.1 clade is independent of other BA.5.3.1 descendent lineages carrying the same mutations in the Spike (like lineages BE.1.* or BQ.1.*). Genomic surveillance in Amazonas shows that it is increasing fast, from around 25% of sequenced genomes in the first half of September to approximately 94% in the second half of October.

#Non-synonymous mutations outside the Spike:
ORF1a: V84del
ORF1a: M85del

#Synonymous mutations outside the Spike:
A27508C
A27749G
T28693C

Earliest sequence: 2022-09-08
Most recent sequence: 2022-10-20
Countries circulating: Brazil

250 Genomes
Data Availability 
GISAID Identifier: EPI_SET_221108bx
doi: [10.55876/gis8.221108bx](https://doi.org/10.55876/gis8.221108bx)

Evidence
<img width="1811" alt="BA531_tree" src="https://user-images.githubusercontent.com/11084299/200589515-2fbbd4e0-fa3f-49e8-a633-9a2568153f21.png">
![Linhagens AM 2022% SET_OUT](https://user-images.githubusercontent.com/11084299/200590058-2df6d336-bfc7-461d-baa1-c311f23eafc8.jpg)

**Comment by FedeGueli** [comment]
It has the same Nuc mutation for S:N460K as BQ* family T22942A
but misses both the defining mutations of BQ outside the spike: Orf9b:P10F and orf1b:ORF1b:Y264H

the two mutations outside the spike are:
ORF7a:T39P A27508C 
ORF7a:K119R A27749G 
while the other is synonymous : T28693C


first sequence of this lineage should be EPI_ISL_14853495 from Brazil which had S:N460K and not S:444T
collected on 16/07/2022

But before that there were 298 sequence of BA.5.3.1 with A27508C,A27749G,T28693C 
but without S:N460K and S:444T .
Although it is more likely convergent evolution especially after seeing this first sequene lacks genuinely the S:K444T mutation, being July the same time when BQ family emerged from Nigeria Ghana region i would not exclude this could have emerged after a recombinant event between the brazilian A27508C,A27749G,T28693C  lineage and one virus from the rising african BQ. family.

**Comment by akograf** [comment]
Thanks for you comment @FedeGueli 

We don’t believe this BA.5.3.1 can be a recombination with BQ.1 because:
1)	There is only one BQ.1 genome detected in Amazonas and it was detected in end of October. Thus, there was very few opportunities of a recombination have occurred. 
2)	Sequence EPI_ISL_15603705, from July and located at the base of the clade, has S:N460K+S:Y144del,  while BQ.1 doesn’t have Y144del. Recombination should had occurred in a very specific portion of the Spike protein.

Furthermore, we think that a new lineage should be designated only for the sequences harboring S:K444T, S:N460K and S:Y144del. Not including the ancestors with the incomplete set of mutations. This is the variant actually increasing in prevalence and responsible for the resurgence of covid19 in Amazonas. 

Finally, we found an issue with the mutations A27508C and A27749G. They only appear in sequences with a 240 bp gap at the positions 27509 to 27748 (see the images below from my BA.5.3.1 alignment). This is observed in sequences from several countries, and I suspect it can be a sequencing issue. Has someone else already observed it?

<img width="2048" alt="Screen Shot 2022-11-09 at 11 25 21" src="https://user-images.githubusercontent.com/11084299/200866303-e0629f9b-0854-4c43-bb0d-8f90e649d71d.png">

<img width="2048" alt="Screen Shot 2022-11-09 at 11 28 56" src="https://user-images.githubusercontent.com/11084299/200866323-ea47d926-80ba-4edd-b06a-5628476153f0.png">

**Comment by FedeGueli** [comment]
Thx @akograf agree on everything. i also noticed that two nuc mutations arent always shown by Covspectrum as AA mutations , dont know why , as you said some artifact or sequencing issue at work there

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BE.9 with 233 newly designated sequences, and 0 updated designations. Defining mutation A22893C (S:K444T) (following T22942A (S:N460K)).
The current usher tree has A27508C (ORF7a:T39P); then C27509A (ORF7a:P39Q) (this being on same node as nt:A27510G (ORF7a:Y40N), nt:T27511A, and nt:C27513T), in the path from BA.5.3.1 to A22893C (S:K444T).
