### ISSUE TITLE
BA.2.75.2* and BA.5.2.1* recombinant lineage in Ontario, Canada

### ISSUE THREAD

**Issue by braukmann** [cov-lineages/pango-designation#1305]
We have observed a cluster of cases of a recombinant lineage in Ontario, Canada. Currently there are 41 cases.
It is a recombinant between BA.2.75.2* and BA.5.2.1* (or sublineages of those parents).  The breakpoint is around 27013:27037 bp from the reference strain (Wuhan). Currently it is only circulating in Canada.
 
![image](https://user-images.githubusercontent.com/12940513/200683736-c8614892-526f-4741-bde2-8c6096bc7b62.png)

GISAID ids: EPI_ISL_15689904
EPI_ISL_15689912, EPI_ISL_15689914, EPI_ISL_15690002, EPI_ISL_15690013, EPI_ISL_15690014, EPI_ISL_15690015, EPI_ISL_15690016, EPI_ISL_15690024, EPI_ISL_15690026, EPI_ISL_15690027, EPI_ISL_15690032, EPI_ISL_15690034, EPI_ISL_15690100, EPI_ISL_15690248, EPI_ISL_15690252, EPI_ISL_15690254, EPI_ISL_15690255, EPI_ISL_15690256, EPI_ISL_15690257, EPI_ISL_15690258, EPI_ISL_15690284, EPI_ISL_15690285, EPI_ISL_15690299, EPI_ISL_15690303, EPI_ISL_15690305, EPI_ISL_15690314, EPI_ISL_15690316, EPI_ISL_15690326, EPI_ISL_15690329, EPI_ISL_15690332, EPI_ISL_15690335, EPI_ISL_15690343, EPI_ISL_15690423, EPI_ISL_15690539, EPI_ISL_15690602, EPI_ISL_15121701

Usher tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_12797_acb380.json
 
![image](https://user-images.githubusercontent.com/12940513/200683806-f42e6f99-cd4c-4859-af08-1d95ba2a7330.png)

Mutational profile:

![image](https://user-images.githubusercontent.com/12940513/200683838-74cce4d1-0724-4a76-81ac-4db5efec5969.png)

**Comment by AngieHinrichs** [comment]
One sequence from Quebec, Canada/QC-L00535835001/2022|EPI_ISL_15415948|2022-10-03, is placed together with Canada/ON-PHL-22-40620/2022|EPI_ISL_15121701|2022-09-19 in the UShER tree that includes GISAID sequences.  The other sequences just became available from GISAID yesterday and will be added to the tree in today's build (2022-11-08) which should become available shortly after 7pm Pacific time.  (In the [UShER web interface](https://usher.bio), select the tree of 12M sequences including GISAID.)

**Comment by FedeGueli** [comment]
So this has lost attenuating orf6 mutation and gained orf9b:16G that was key for BA.5.2 success worlwide. something to monitor closely.

**Comment by corneliusroemer** [comment]
Closing as no new sequences appeared from outside of Ontario
