### ISSUE TITLE
BN.1.3 sublineage with S:E147Q (35 seq., Austria, Germany, USA, Singapore, Italy)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1306]
Proposal for a sublineage of BN.1.3
Earliest sequence: 27.09.22 (Austria)
Countries detected: Austria (17), USA (4), Germany (3), Singapore (1), Italy (1)

Defining mutations:
G22001C = S:E147Q
T12871C
T4435C

Provisional GISAID query: 
Spike_F157L, Spike_W152R, Spike_K147Q, Spike_G257S, Spike_G339H, Spike_R346T

![grafik](https://user-images.githubusercontent.com/102166254/200843650-24c492f3-1c64-4b47-89ed-f7fa2c0c8142.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_219b8_b88ac0.json?c=pango_lineage_usher&label=nuc%20mutations:G22001C

![grafik](https://user-images.githubusercontent.com/102166254/200844608-5936710f-83ea-49a3-b106-aa12da0a877c.png)

EPI_ISL_15259713, EPI_ISL_15269662, EPI_ISL_15384172, EPI_ISL_15444884, EPI_ISL_15509383, EPI_ISL_15509387, EPI_ISL_15509388, EPI_ISL_15602814, EPI_ISL_15602828, EPI_ISL_15602842, EPI_ISL_15602844, EPI_ISL_15645559, EPI_ISL_15646414, EPI_ISL_15648308, EPI_ISL_15665564, EPI_ISL_15695687, EPI_ISL_15695700, EPI_ISL_15695711, EPI_ISL_15695736, EPI_ISL_15695790, EPI_ISL_15697152

hCoV-19/Austria/Medilab_1530/2022
hCoV-19/Austria/Medilab_1546/2022
hCoV-19/Austria/Medilab_1559/2022
OP737121.1
OP742136.1

**Comment by ryhisner** [comment]
I noticed this today! Pretty crazy. Some of the newer variants are moving through multiple second- or even third-nucleotide mutations right now, especially at S:147, 213, 478, 484, 486. Feels like a new era.

**Comment by agamedilab** [comment]
plus 8 seq Austria as of 14.11.22. 

![grafik](https://user-images.githubusercontent.com/102166254/201655307-01af6b1a-d135-4efd-ac86-75e7ad6b84d0.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_156b5_22dad0.json?label=nuc%20mutations:G22001C

**Comment by InfrPopGen** [comment]
Thank you for proposing this as a lineage. Although interesting in terms of subs saturation, this clade has not shown marked growth relative to its parent, and has been in relative decline since late November (inc. in USA, Austria and Germany). Consequently, this can be closed for now. Please do re-propose or request re-opening should this lineage show marked epidemiological significance in the future.
