### ISSUE TITLE
BN.1.3 sublineage with S:P631S (14 seqs. Austria, Switzerland,  Denmark, South Korea)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1307]
Proposal for a sublineage of BN.1.3
Earliest sequence: 26.10.22 (Austria)
Countries detected: Austria (9)

Defining mutations:
S:P631S = C23453T
C7390A
ORF1a:H110Y = C593T
ORF1a:M3627I = G11146T

Provisional GISAID query:
Spike_P631S, Spike_K147E, Spike_W152R, Spike_F157L

This subvariant of BN.1.3 is defined by S:P631S and was detected in Austria by three labs (IMBA, LB, Medilab).

![grafik](https://user-images.githubusercontent.com/102166254/200859234-49fd9871-2100-4e49-854b-8714a453a1ea.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3dd07_bb97a0.json?c=pango_lineage_usher

![grafik](https://user-images.githubusercontent.com/102166254/200859991-ea406c39-eee9-4220-9996-28798c7639f1.png)

EPI_ISL_15663959, EPI_ISL_15670904, EPI_ISL_15695707,
EPI_ISL_15695714, EPI_ISL_15695758, EPI_ISL_15695775,
EPI_ISL_15720338, EPI_ISL_15720351, EPI_ISL_15720395

**Comment by ryhisner** [comment]
ORF1a:H110Y keeps coming up again and again. Might have to add that to the small list of convergent ORF1ab mutations.

**Comment by agamedilab** [comment]
14 seq., Austria,  Denmark, South Korea as of 23.11.22.

![grafik](https://user-images.githubusercontent.com/102166254/203532947-5acd09cc-2d01-4f8a-a992-33d6b3f07a80.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d848_e00240.json?label=nuc%20mutations:C23453T

**Comment by AnonymousUserUse** [comment]
Proposed lineage BN.1.3 + C23453T + C7390A + C593T + G11146T has 53 sequences per CoV-Spectrum as of 2023/1/9.

Its parental lineage, BN.1.3 + C7390A + C593T + G11146T, 4422 sequences per CoV-Spectrum as of 2023/1/9, may be designated first. Otherwise, those sequences may be misassigned as the lineage proposed in this issue per Nextclade.

**Comment by FedeGueli** [comment]
164 seqs as today oin Gisaid with Spike_P631S, Spike_K147E, Spike_W152R, Spike_F157L

@agamedilab are you doing well? a lot of time you re not here.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As this has been showing negative growth relative to its parent in the Austria over the past three months (and negligible advantage in Germany), this can be closed at the moment. Nevertheless, please re-propose or request re-opening should this lineage show clear signs of relative growth in the future.
