### ISSUE TITLE
BN.1 Sublineage with S:I210del, S:M177T, & S:H1101Y (+ S:N211V, S:L212S??) [~49 seq]

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1310]
### **Description**
**Sub-lineage of:** BN.1
**Earliest sequence:** 2022-10-4, England — EPI_ISL_15407408
**Most recent sequence:** 2022-11-1, England — EPI_ISL_15697330
**Countries circulating:** England (15), USA (8), Canada (2), Denmark (1)
**Number of Sequences:** 26
**GISAID Query:** Spike_M177T, Spike_H1101Y, Spike_K356T
**CovSpectrum Query:** Nextcladepangolineage:BN.1* & S:M177T & S:H1101Y
**Substitutions on top of BN.1:**
**Spike:** I210del, M177T, H1101Y (N211V, L212S)
**Nucleotide:** T22092C, C22858T, C24863T
**AA Deletions:** S:I210
**Nucleotide Deletions:** 22194-22196
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BN.1%20%2B%20I210del%20%2B%20M177T%20%2B%20H1101Y%20-%20subtreeAuspice1_genome_368ff_c18d00.json
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/33738461/200947334-4fe26b43-efe4-48d6-bfdf-2d9de2271bfb.png">
 
**Evidence**
Half of the 26 sequences here have been uploaded in the past 72 hours, which would seem to indicate very rapid growth. S:M177X has been a convergent mutation, though it’s not been part of any large lineage, at least not to my knowledge. S:I210del and S:H1101Y have also been seen frequently in various lineages, likely indicating they provide some sort of advantage in some contexts.  

Most sequences are from England, but the geographical spread is impressive as this lineage stretches from England to Canada to New Mexico and Florida, USA.

Usher doesn’t show deletions, and it also masks any mutations that come about as a result of a deletion, like S:N211V and S:L212S in this lineage, according to NextClade. On NextClade, six of the 26 sequences appear to lack the S:I210 deletion, but I’m almost certain this is a sequencing artifact. Two of the sequences also lack the S:24-26 deletion, and all the others are low-quality in some way.

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/33738461/200948201-ff8c9c41-66e7-4a93-9973-8f3868d04e70.png">
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15407408, EPI_ISL_15474755, EPI_ISL_15475168,
EPI_ISL_15495667, EPI_ISL_15545593, EPI_ISL_15546688,
EPI_ISL_15551780, EPI_ISL_15580687, EPI_ISL_15629321,
EPI_ISL_15629366, EPI_ISL_15649362, EPI_ISL_15649364,
EPI_ISL_15649479, EPI_ISL_15677565, EPI_ISL_15681779,
EPI_ISL_15681936, EPI_ISL_15681969, EPI_ISL_15689211,
EPI_ISL_15689235, EPI_ISL_15697330, EPI_ISL_15705246,
EPI_ISL_15705543, EPI_ISL_15707279, EPI_ISL_15707640,
EPI_ISL_15719794, EPI_ISL_15719915
</details>

**Comment by ryhisner** [comment]
Six additional sequences uploaded today & yesterday (three England, two Wales, one Canada). Total now 32 sequences.

**Comment by cvejris** [comment]
Great catch, Ryan. But aren´t my eyes deceiving me? The deletion call is somehow misleading, it should read 211-212: NL→I. This is exactly the same mutation as in BA.1!
![image](https://user-images.githubusercontent.com/110762428/201470243-df8cf3d3-f811-4e49-a8d0-01457f62272a.png)
Let´s recap this spectacular succession: 
BA.2 had V213G 
BA.2.75 had I210V 
this has NL211/2I

**Comment by ryhisner** [comment]
Ah, now that would be interesting! You could be right, @cvejris. I've seen several BA.2/5* sequences with that BA.1 pattern of ∆N211 + L212I. Deletions are always tricky and get interpreted differently by GISAID and NextClade, while Usher doesn't register them at all. Perhaps @AngieHinrichs could help in the correct interpretation of this one?

**Comment by ryhisner** [comment]
So this is apparently BN.1.7 now? Could someone place a milestone marker on this, along with the "designated" tag?

**Comment by FedeGueli** [comment]
Yes it is BN.1.7 @thomasppeacock @InfrPopGen could you add the milestone here please?

@ryhisner

**Comment by FedeGueli** [comment]
commit:459650f68c24f8196
