### ISSUE TITLE
BA.5.2 (ORF1b:T1050N) Sublineage with S:G446D, S:N460K, & ORF1a:A1679V (32 seq, 22 with S:K147Q)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1312]
### **Description**
**Sub-lineage of:** BA.5.2 (ORF1b:T1050N)
**Earliest sequence:** 2022-9-15, Mongolia — EPI_ISL_15299167
**Most recent sequence:** 2022-11-1, Mongolia — EPI_ISL_15688016
**Countries circulating:** South Korea, Mongolia, England, Singapore, Japan
**Number of Sequences:** 17
**GISAID Query:** Spike_G446D, Spike_N460K, NSP13_T127N
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2* & ORF1b:T1050N & S:G446D & S:N460K
**Substitutions on top of BA.5.2 (T1050N):**
**Spike:** G446D, N460K
**ORF1a:** A1679V (NSP3_A861V)
**Nucleotide:** C5301T, C15933T, G22899A, T22942G
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.5.2%20%2B%20G446D%20%2B%20N460K%20%2B%20ORF1aA1679V%20-%20subtreeAuspice1_genome_15915_c25cd0.json
 
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/33738461/200956092-62a3d7b9-3565-4631-91d5-a22963fc2bb4.png">
 
**Evidence**
This lineage, like the one I proposed in Issue #1311, seems to extend back to the root of the BA.5.2 (T1050N) branch. Both lineages share S:G446D, but they diverge from there. In fact, as you can see on the downsampled global Usher tree below, Usher wants to put this lineage (along with Issue #1131) in an entirely separate branch from the other BA.5.2 + ORF1b:T1050N branch, which seems absurd. This looks like a real conundrum to me, and I don’t know what the true phylogenetic tree of this lineage should look like. 

Bizarrely, the regular Usher tree places this lineage 73 mutations away from the original SARS-CoV-2, but the downsampled global tree puts it 98 mutations away. I don't know how to explain this.

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/33738461/200956264-964c014b-446d-4d26-8c11-761bddcabe4c.png">

Five sequences in this lineage have come from Mongolia—including the two most recent sequences—which indicates this lineage could be much more widespread than its 17 sequences would lead us to believe.

And of course S:N460K seems to be the key that allows any lineage that acquires it to accumulate additional spike mutations. Over half of this lineage already has S:K147Q, and I wouldn’t be surprised to see many more NTD and RBD mutations soon.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15299167, EPI_ISL_15312995, EPI_ISL_15351813,
EPI_ISL_15492011, EPI_ISL_15492830, EPI_ISL_15493554,
EPI_ISL_15493634, EPI_ISL_15533895, EPI_ISL_15533946,
EPI_ISL_15533997, EPI_ISL_15534505, EPI_ISL_15607930,
EPI_ISL_15607933, EPI_ISL_15672651, EPI_ISL_15676879,
EPI_ISL_15683037, EPI_ISL_15688016
</details>

**Comment by ryhisner** [comment]
First sequence in North America from this lineage came into today. It's on the S:K147Q branch and came from California, USA. EPI_ISL_15766758

**Comment by ryhisner** [comment]
Six sequences from this lineage uploaded from South Korea today, all with S:K147Q. This brings the total number of sequences to 32, of which 22 have S:K147Q.

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/33738461/202821310-4f7da8dc-318b-4cf4-b505-93fcc4244758.png">

**Comment by FedeGueli** [comment]
I re-discovered the wheel this morning with this sublineage : after acquiring S:147Q it seems going faster and spreading in South Korea i noticed one sequence from Japan and that led me here!:

43 sequences on Usher as today:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d656_1c72f0.json

@thomasppeacock @AngieHinrichs @corneliusroemer @InfrPopGen  i think this should be designated soon is a different way for the virus to reach the same fitness using 147 (BA.2.75 teaches) and 446 (as BA.1 or Bh.1) and homoplasic S:460K (from 22942G as Ba.2.75)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.43 with 31 newly designated sequences, and 0 updated designations. Defining mutation C5301T (ORF1a:A1679V) (following T22942G (S:N460K) on current tree).
