### ISSUE TITLE
Potential BQ.1 sublineage with E:R61L and ORF3a:I169V (52 good seqs as of 2022-11-10; Asia, Europe, and North America)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1315]
There may be a BQ.1 sublineage with E:R61L (G26426T) and ORF3a:I169V (A25897G).

As of 2022-11-10, Cov-Spectrum reports 52 good quality (67 total) BQ.1+E:61L+ORF3a:169V sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABQ.1+%26+E%3AR61L+%26+ORF3a%3AI169V&nextcladeQcOverallScoreTo=29&

This lineage is showing a potentially-significant growth advantage

As of 2022-11-10, UShER shows all of the GISAID samples are on a single subtree with evidence of additional branching:
![BQ 1+E_61L+ORF3a_169V_UShER](https://user-images.githubusercontent.com/88959107/201234240-67e16afe-0da0-4eea-8225-416eb6425061.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/11/singleSubtreeAuspice_genome_CoV-Spectrum_BQ.1%2BE_61L%2BORF3a_169V.json?c=gt-ORF3a_169&label=nuc%20mutations%3AC1931A

First Outbreak.info sequence: Thailand 2022-08-15

First GenBank sequence: England, United Kingdom 2022-09-13 

Most Recent GenBank sequence: Sankt Gallen, Switzerland 2022-10-11

Most Recent Outbreak.info sequence: Denmark 2022-10-23

A zip archive of GenBank-derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-BQ.1+E_61L+ORF3a_169V.zip](https://github.com/cov-lineages/pango-designation/files/9985491/Support-BQ.1%2BE_61L%2BORF3a_169V.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at 
[gisaid-epi-isl-BQ.1+E_61L+ORF3a_169V.txt](https://github.com/cov-lineages/pango-designation/files/9985488/gisaid-epi-isl-BQ.1%2BE_61L%2BORF3a_169V.txt)

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=BQ.1&muts=E%3AR61L&muts=ORF3a%3AI169V. 

Edit: Corrected "with evidence of" to "with evidence of additional branching".

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.26 with 15 newly designated sequences, and 0 updated designations. Defining mutations A25897G (ORF3a:I169V) and G26426T (E:R61L) (following BQ.1, i.e. T22942A (S:N460K)).
