### ISSUE TITLE
Potential BF.7.5 sublineage with ORF1a:H712N (73 good seqs as of 2022-11-10; Europe, USA, Israel, Japan)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1317]
There may be a BF.7.5 sublineage with ORF1a:H712N (C2399A).

CoV-Spectrum shows a positive but not spectacular growth rate for this lineage.  However, it may currently be the fastest BF.7 descendant, and it is the first time that a new minimal TRS-B (Transcription Regulatory Sequence-Body) formed by the C2399A mutation, and possibly creating a novel sgmRNA, has managed to show continuted transmission.  Note: The evolution of a different novel sgmRNA in lineage B.1.1, an ancestor of Omicron and all other Variants of Concern so far, has been proposed by Mears et al https://doi.org/10.1101/2022.04.20.488895.

As of 2022-11-10, Cov-Spectrum reports 73 good-quality (93 total) BF.7.5+ORF1a:712N sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABF.7.5+%26+ORF1a%3AH712N&nextcladeQcOverallScoreTo=29&

As of 2022-11-10, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of continued branching:
![BF 7 5+ORF1a_712N_CoV-Spectrum_UShER](https://user-images.githubusercontent.com/88959107/201251817-96f005de-084f-4687-94b8-82faef9a40d1.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/11/singleSubtreeAuspice_genome_CoV-Spectrum_BF.7.5%2BORF1a_712N.json?c=gt-ORF1ab_712&label=nuc%20mutations%3AA27038G

First CoV-Spectrum sample: 2022 Week 37, Germany and Denmark

Most Recent CoV-Spectrum sample: 2022 Week 44, Germany

A zip archive of GenBank-derived metadata and FASTA files (very little data) plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-BF.7.5+ORF1a_712N.zip](https://github.com/cov-lineages/pango-designation/files/9986109/Support-BF.7.5%2BORF1a_712N.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-BF.7.5+ORF1a_712N.txt](https://github.com/cov-lineages/pango-designation/files/9986107/gisaid-epi-isl-BF.7.5%2BORF1a_712N.txt)

Please note that the TRS-B formed by C2399A is of the minimal conserved core SARS-CoV-2 form ACGAAC discussed in Malone et al https://doi.org/10.1038/s41580-021-00432-z.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.7.5.1 with 17 newly designated sequences, and 5 updated designations from BF.7.5. Defining mutations C2399A (ORF1a:H712N), G22104T (S:G181V) (following C26985T (M:H155Y)).
