### ISSUE TITLE
BA.2.3.20 Sublineage(s) with S:G213E—likely 2 independent lineages (27 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1318]
**Description**
**Sub-lineage of:** BA.2.3.20
**Earliest sequence:** 2022-10-4, South Korea (imported from Philippines) — EPI_ISL_15533748
**Most recent sequence:** 2022-10-26, Australia, Victoria — EPI_ISL_15641385
**Countries circulating:** Australia (4), Japan (4), Philippines (1, sequenced in South Korea)
**Number of Sequences:** 9
**GISAID Query:** Spike_E484R, Spike_V213E
**CovSpectrum Query:** Nextcladepangolineage:BA.2.3.20* & S:G213E
**Substitutions on top of BA.2.3.20:**
**Spike:** G213E
**Nucleotide:** G22200A, T25171C
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.2.3.20%20%2B%20G213E%20-%20subtreeAuspice1_genome_9569_e27de0.json
 
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/33738461/201328845-c5db65fb-0969-4d57-bcfe-dc6aab474589.png">
 
**Evidence**
S:G213E involves a second nucleotide change at that residue and has appeared in a number of sequences in various lineages, though it most notably is in all XBB* sequences.
 
Though Usher puts all nine sequences in the same branch, it seems likely to me that the “Japan branch” (4 seq) is separate from the other five since it allegedly has the C25171T reversion. The Japan branch also has ORF1b:C1367S and C6781T to distinguish it from the four-sequence “Australian branch” (which includes one sequence from Japan) and the sequence from a Filipino traveler to South Korea.
 
The Australian branch has two synonymous nucleotide mutations (C10519T, C13051T) and ORF7a:R25T (G27467C).
 
**Genomes (All)**
<details>
<summary>Genomes</summary>
EPI_ISL_15533748, EPI_ISL_15641215, EPI_ISL_15641385,
EPI_ISL_15642804, EPI_ISL_15653007, EPI_ISL_15712056,
EPI_ISL_15712099, EPI_ISL_15724325, EPI_ISL_15735277,
</details>
 
**Genomes (Australia + Philippines)**
<details>
<summary>Genomes</summary>
EPI_ISL_15533748, EPI_ISL_15641215, EPI_ISL_15641385,
EPI_ISL_15653007, EPI_ISL_15724325
</details>
 
 
**Genomes (Japan)**
<details>
<summary>Genomes</summary>
EPI_ISL_15642804, EPI_ISL_15712056, EPI_ISL_15712099,
EPI_ISL_15735277
</details>

**Comment by ryhisner** [comment]
The lineage with ORF1b:C1367S (but without T25171C) now seems to be at 12 sequences while the one with T25171C (but without ORF7a:G38V) also stands at 12 sequences. A third S:G213E lineage with T25171C + ORF7a:G38V has three sequences, all from USA, Washington state.

**Comment by InfrPopGen** [comment]
Thank you for proposing this/these as candidate lineages. Taking them individually they have remained apparently very small. Taken together they have not shown much growth since detection, neither in absolute terms or in relation to BA.2.3.20 (Japan is clearly negative over the past two or three months, and Australia is not significantly positive). Consequently, this issue can be closed for now; however, please re-propose any of these, should any show signs of marked growth advantage (or other signs of epidemiological significance worthy of concern).
