### ISSUE TITLE
Proposed New Lineage: B.1 Angola/Guinea Associated

### ISSUE THREAD

**Issue by nfellaby** [cov-lineages/pango-designation#132]
by Nicholas Ellaby

**Description:** Sub-lineage clade similar to Delta but derived from B.1, most cases are associated with Guinea (no collection dates for these though). Earliest case with collection dates are from Angola. Wide spread through Europe now.

**Geographical distribution:** 7x Guinea, 3x Angola, 6x France, 1x Germany, 8x Italy, 1x Luxembourg, 9x Spain, 1x UK

**Sub-lineage of:** B.1
**Earliest sequence:** 23/02/2021* *- Many samples from Guinea were not annotated with a collection date (uploaded on the 28/04/2021)
**Most recent sequence:** 23/06/2021
**Countries circulating:** Spain, Italy, and France (samples with collections dates from 01/05/2021)

**Evidence**
![image](https://user-images.githubusercontent.com/9819369/124107051-be54b180-da5c-11eb-99d9-a844bd7d068a.png)

Samples of interest are highlighted in Red. Note, some sequences from GISAID were not present in the main phylogenetic tree that are proposed as part of the lineage.

**Genomes**
[20210701_B.1_Guinea_Proposed_Lineage.csv](https://github.com/cov-lineages/pango-designation/files/6747235/20210701_B.1_Guinea_Proposed_Lineage.csv)
**Conserved Mutations**
[20210701_Conserved_Mutations.csv](https://github.com/cov-lineages/pango-designation/files/6747344/20210701_Conserved_Mutations.csv)

**Comment by chrisruis** [comment]
Thanks for submitting @nfellaby. We've added this as lineage B.1.629 in [v1.2.31](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.31) with 41 designated sequences
