### ISSUE TITLE
CM.4 Sublineage (BA.2.3.20 + ORF1b:D146G) with S:R444T (40 seq, Feb 15)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1320]
**Description**
**Sub-lineage of:** CM.4
**Earliest sequence:** 2022-9-15, South Korea, imported from Philippines — EPI_ISL_15281031
**Most recent sequence:** 2022-10-21, South Korea — EPI_ISL_15733419, EPI_ISL_15733536
**Countries circulating:** South Korea (2), Japan (2), Philippines (1, sequenced in South Korea)
**Number of Sequences:** 5
**GISAID Query:** Spike_E484R, NSP12_D155G, Spike_K444T
**CovSpectrum Query:** Nextcladepangolineage:CM.4* & S:R444T
**Substitutions on top of CM.4:**
**Spike:** R444T
**Nucleotide:** G22893C
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/CM.4%20%2B%20R444T%20-%20subtreeAuspice1_genome_24e71_e328d0.json
 
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/33738461/201335620-10802b94-1f63-421b-95b4-abc352c2bbf9.png">
 
**Evidence**
S:T444 has been one of the most phenomenally successful mutations over the past several months and is far more effective at evading antibodies than S:R444 in every RBD background in which it’s been tested. https://www.biorxiv.org/content/10.1101/2022.09.15.507787v4.full.pdf

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/33738461/201335422-21809b68-ca5c-4d3f-8f13-a29e0567c36d.png">

Notably, two sequences here, both from Japan, also have S:H66R. 

Like many other BA.2.3.20 sublineages, this one almost certainly originated in the Philippines since the earliest sequence (by far) was detected in a traveler from the Philippines. I would not be surprised if we see a significant number of CM.4 + S:R444T sequences uploaded from September & October in the coming weeks and months.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15281031, EPI_ISL_15599823, EPI_ISL_15599957,
EPI_ISL_15733419, EPI_ISL_15733536
</details>

**Comment by ryhisner** [comment]
With ~10 sequences collected since January 1, this one seems to be making something of a comeback, mainly in South Korea, so I'm reopening.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. After its come back early in the year, it looks like it has faded away again. It is 100% of South Korea's CM.4 detections, but CM.4 itself is only a few detections per month now. The apparent growth advantages are correspondingly negative for Asia. Consequently, this can be closed for now, but please request a re-opening or re-propose should these trends become greatly reversed in the future.
