### ISSUE TITLE
BM.1.1.3 Sublineage with S:F490P (39 seq, Jan 17)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1321]
### **Description**
**Sub-lineage of:** BM.1.1.3
**Earliest sequence:** 2022-10-18, Spain — EPI_ISL_15709266
**Most recent sequence:** 2022-10-28, Scotland — 15677457
**Countries circulating:** Scotland (4), Malaysia (1), Spain (1)
**Number of Sequences:** 6
**GISAID Query:** Spike_F490P, NSP14_V182I, Spike_F486S
**CovSpectrum Query:** Nextcladepangolineage:BM.1.1.3* & S:F490P
**Substitutions on top of BM.1.1:**
**Spike:** F490P
**Nucleotide:** T4057C, G13348T, C16626T, T23030C, T23031C 
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_1ca14_e51fb0.json
 
![image](https://user-images.githubusercontent.com/33738461/201355324-3439b3ba-f547-43ac-89a0-98af0f729f13.png)
 
**Evidence**
S:F490P is a two-nucleotide mutation, a likely indication that it results from strong selection pressure. 

![image](https://user-images.githubusercontent.com/33738461/201355601-cc33e109-4f00-4009-a6a7-c365a771d729.png)

The geographic spread covered by these six sequences is wide, stretching from Scotland to Spain, to Malaysia. There appear to be at least two intermediate sequences with S:F490S, one from Gujarat, India, and one from Japan. There are likely many others. 
All sequences were uploaded within the past four days, and the earliest collection date is October 18, a possible indication of the rapid spread of this lineage.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15677383, EPI_ISL_15677434, EPI_ISL_15677457, EPI_ISL_15709266, EPI_ISL_15727129, EPI_ISL_15738259
</details>

**Comment by ryhisner** [comment]
Two more sequences from Scotland today, bringing the total to nine sequences.

**Comment by ryhisner** [comment]
Three more sequences turned up in the last four days, but it seems pretty clear this is not a growing lineage, so I'm closing this issue.

**Comment by FedeGueli** [comment]
Hi Ryan! this recently grow to 31 sequences. maybe it is worth reopening it!

**Comment by ryhisner** [comment]
I'm still not sure what kind of growth potential this one has—it might be driven into the ground by XBB.1.5 over the next few weeks—but you've convinced me it's worth reopening at least, @FedeGueli!

**Comment by FedeGueli** [comment]
Thanks Ryan! That was my thohght when BQ.1 came into the game, but finally Cornelius was right in designating everything interesting popped up: now some of those ba.2.75 sublineages are faster much faster than bq.1! So mutations are always to track in my view even if not immediately successful!

**Comment by FedeGueli** [comment]
32 sequences as today

**Comment by ryhisner** [comment]
This is a dead lineage it seems.
