### ISSUE TITLE
First Ba.5.2.1 sublineage with S:444N and S:460K - 49 sequences - likely emerged in India 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1325]
I casually spotted this sublineage of BA.5.2.1 showing the "homoplasic" combo S:444N and S:460K.

Tree:
<img width="1159" alt="Schermata 2022-11-12 alle 21 58 21" src="https://user-images.githubusercontent.com/87669813/201494302-c8e0f5a7-5036-45d9-bdef-672bff963508.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d8d9_7960.json?c=pango_lineage_usher&label=nuc%20mutations:C6726T

Defining mutations:
Despite being placed by usher in a No28330 part of the tree it has A28330G ( @AngieHinrichs via forth back reversions
C1627T > A27038G > G28330A > C17678T > A28330G > C6726T > G22894T, T22942G )

So i should say defining mutations are simply : **_BA.5.2.1 then C17678T then Orf1a:T2154I (C6726T) then S:N460K (T22942G) and S:K444N ( G22894T)_**

Gisaid query: NSP3_T1336I,Spike_N460K,Spike_K444N finds 9 viruses 
EPI_ISL_15353046, EPI_ISL_15500969, EPI_ISL_15504881,
EPI_ISL_15613023, EPI_ISL_15644023, EPI_ISL_15655725,
EPI_ISL_15665309, EPI_ISL_15720028, EPI_ISL_15736443,

Looking at first sequence : EPI_ISL_15504880 sampled in India back in August i would say it emerged there.

**Comment by ryhisner** [comment]
Interesting to see ORF1a:T4175I in that tree as well. That's definitely a convergent ORF1a mutation, especially in highly mutated sequences.

**Comment by FedeGueli** [comment]
Tree as today: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_f594_54f940.json?label=nuc%20mutations:G22894T,T22942G
<img width="1135" alt="Schermata 2022-11-16 alle 22 03 02" src="https://user-images.githubusercontent.com/87669813/202293663-0d647ec1-c3cf-4707-9d1d-ad5f2f47cdf3.png">

As today there are 12 "real" sequences , i precedently miscalculate them as already 12. now we have a new one from England.

**Comment by FedeGueli** [comment]
17 viruses as today with : NSP3_T1336I,Spike_N460K,Spike_K444N

**Comment by FedeGueli** [comment]
22 viruses , found in Canada Switzerland, India, Netherlands , Germany, Uk , Australia, Usa.

The international spread seems bigger than we could expect from the number of samples. 
The tree points to a likely indian origin of this and we already spotted in the past lineages with mutlicontinental spread linked to circulation in downsampled areas of India.

**Comment by FedeGueli** [comment]
30 seqs aas today

**Comment by FedeGueli** [comment]
33 sequences . it still seems slow

**Comment by FedeGueli** [comment]
> Interesting to see ORF1a:T4175I in that tree as well. That's definitely a convergent ORF1a mutation, especially in highly mutated sequences.

@ryhisner i just realized that XBB.1.9 is defined by Orf1a:T4175I

**Comment by FedeGueli** [comment]
49 sequences as today. last sample came from Iran.
