### ISSUE TITLE
CP.5 (BA.5.2.6 + S:C1247F) Sublineage with S:T250I, S:N417T, N:G200S, & ORF7a:Q90R in Sweden (11 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1326]
**Description**
**Sub-lineage of:** BA.5.2.6
**Earliest sequence:** 2022-10-4, Sweden, Orebro — EPI_ISL_15288391
**Most recent sequence:** 2022-10-26, Sweden, Orebro — EPI_ISL_15725064
**Countries circulating:** Sweden (All)
**Number of Sequences:** 11
**GISAID Query:** Spike_T250I, Spike_K417T, Spike_C1247F, Spike_R346T
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2.6* & S:T250I & S:K417T
**Substitutions on top of BA.5.2.6:**
**Spike:** T250I, K417T, C1247F
**N:** G200S
**ORF7a:** Q90R
**Nucleotide:** C22311T, A22812C, A27662G, T28022C, G28871A
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.5.2.6%20%2B%20C1247F%20(CP.5)%20%2B%20T250I%20%2B%20K417T%20%2B%20N_G200S%20%2B%20ORF7aQ90R%20-%20subtreeAuspice1_genome_2249e_1c490.json 
 
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/33738461/201498211-e09adf6c-7527-4d3a-8e70-96aaf9e803f2.png">

**Evidence**
S:K417T has never gone well together with S:L452R or S:R346T. The number of sequences with K417T and L452R—just 111 sequences in 2022—is far lower than you’d expect from their overall frequency. The same goes for K417T and R346T, for which there have only ever been 208 sequences.  Up until now, it had seemed like K417T was straight-up incompatible with R346T + L452R; there had only ever been one sequence with all three mutations through October 3—and even that one sequence was very suspect and may have resulted from contamination. But since October 4, 11 sequences with all three mutations have showed up in Sweden. I have no idea why K417T has been so incompatible with R346T and L452R up to this point. I assume there is some interaction between these residues. I’d be curious to know if anyone with some knowledge of the RBD structure has any ideas.

I also have no idea why, in this lineage, R346T, L452R, and K417T have, for apparently the first time, coexisted and transmitted, though S:T250I seems to be the only new mutation that could possibly ameliorate whatever detrimental interaction existed between those three mutations previously. 
 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15288391, EPI_ISL_15423227, EPI_ISL_15423228, EPI_ISL_15582791, EPI_ISL_15582792, EPI_ISL_15657006, EPI_ISL_15657011, EPI_ISL_15725064, EPI_ISL_15725378, EPI_ISL_15725380, EPI_ISL_15725640
</details>

**Comment by oobb45729** [comment]
I don't know why N417T seems to appear more often over N417I/H/Y in BA.2. N417I/H/Y seem to be better choices in terms of both ACE2 binding and immune escape. I don't know know L452R changes N417T's fitness either, as they head toward opposite directions. However, the R493Q reversion is also quite near. I wonder whether R493Q is the reason.

**Comment by ryhisner** [comment]
Ah, I hadn't thought of Q493R being related to N417T/K417T's disappearance. There's probably something to that. I'll try to find time to look into that later.
