### ISSUE TITLE
B.1.623 genomes clustering with B.1.526, B.1.621, and other lineages

### ISSUE THREAD

**Issue by andersonbrito** [cov-lineages/pango-designation#133]
By Anderson Brito & [Grubaugh Lab](http://grubaughlab.com)

Description: Some genomes from lineage B.1.623 have been misclassified, clustering with B.1.526, B.1.621, and other lineages.

Earliest sequence: 2020-12-24 (USA/NY-PRL-2020_1229_00H03/2020)

Most recent sequence: 2021-05-13 (USA/GA-CDC-STM-000074282/2021)

Countries circulating: USA

Genomes: https://github.com/andersonbrito/pango/blob/master/auspice/pango_b1623_genomes.txt

Evidence: https://nextstrain.org/community/andersonbrito/pango/b1623?c=pango_lineage&f_pango_lineage=B.1.621,B.1.623&m=num_date

**Comment by AngieHinrichs** [comment]
Thanks Anderson!  It looks like the genomes in pango_b1623_genomes.txt are the ones that are correctly assigned B.1.623, is that right?  The out-of-place genomes assigned B.1.623 in your Nextstrain build are

Spain/MD-HGUGM-678490/2021
Switzerland/VS-HUG-34283250/2021
USA/MN-MDH-7945/2021
Italy/SAR-Cagliari259/2021
USA/AK-PHL9221/2021
USA/MA-CDC-ASC210106418/2021
Germany/NW-RKI-I-181655/2021
Austria/CeMM11084/2021
Austria/CeMM11257/2021
Austria/CeMM11093/2021
Austria/CeMM11267/2021
Austria/CeMM11087/2021
Austria/CeMM11220/2021
HongKong/CM21000386/2021
USA/WA-CDC-UW21061337332/2021
USA/WA-CDC-UW21060125014/2021
USA/AZ-TG927925/2020
USA/AZ-TG832270/2020

The USA/AZ-TG* samples cluster with B.1.609 in the UCSC tree, but seem to be the only sequences mis-assigned B.1.623 in that neighborhood:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-133-subtree2.json?c=pango_lineage

The USA/WA-CDC-UW* samples are part of a big cluster in B.1.526 (that acquired S:P681H) that are consistently mis-assigned B.1.623:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-133-subtree3.json?branchLabel=Spike%20mutations&c=pango_lineage

The rest of those samples are in this B.1.621 subtree, with all except HongKong/CM21000386/2021 in another big cluster consistently mis-assigned B.1.623:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-133-subtree1.json?c=pango_lineage

I think those samples should be added as designated sequences for the other lineages -- and probably other sequences in the large clusters of mis-assigned sequences should be added as designated sequences for the other lineages (B.1.526 and B.1.621) as well.

-- Ah, actually 10 of those sequences are already designated as B.1.621.1 in lineages.csv -- they just haven't made it through pangoLEARN training yet:
```
USA/MA-CDC-ASC210106418/2021,B.1.621.1
Austria/CeMM11084/2021,B.1.621.1
Austria/CeMM11087/2021,B.1.621.1
Austria/CeMM11093/2021,B.1.621.1
Austria/CeMM11220/2021,B.1.621.1
Austria/CeMM11257/2021,B.1.621.1
Austria/CeMM11267/2021,B.1.621.1
USA/AK-PHL9221/2021,B.1.621.1
USA/MN-MDH-7945/2021,B.1.621.1
Italy/SAR-Cagliari259/2021,B.1.621.1
```
So help is on the way for that cluster, and I guess it's not simply B.1.621.  :)

**Comment by andersonbrito** [comment]
Hi @AngieHinrichs,

Correct. In this issue report I have only provided the ones that currently fit the correct designation of B.1.623.
I see you identified all the others, great. Next time I'll submit the full list, correctly and incorrectly assigned genomes.

Thank you for correcting these designations. :)

**Comment by chrisruis** [comment]
Thanks @andersonbrito. Just looking through the 18 out of place sequences, it looks like 12 are now designated B.1.621.1. Sequence USA/AZ-TG927925/2020 has >5% ambiguity so we can't designate that one. Germany/NW-RKI-I-181655/2021 looks like it's also in B.1.621.1. I've designated the remaining sequences to what @AngieHinrichs found above, so that's:
HongKong/CM21000386/2021 - B.1.621
USA/WA-CDC-UW21061337332/2021 - B.1.526
USA/WA-CDC-UW21060125014/2021 - B.1.526
USA/AZ-TG832270/2020 - B.1.609

These are all in [v1.2.41](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.41)

I think that means we've looked at all of the sequences from the issue so I'll close this now. But please let me know if we've missed any
