### ISSUE TITLE
BA.2.3.20 with S:K147I (7 seq. Japan)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1333]
Proposal for a sublineage of BA.2.3.20
Earliest sequence: 16.10.22 (Japan)
Countries detected: Japan (7)

Defining mutations:
S:K147I = A22002T
ORF1A4255S = G13028A
C10156T
C11095T
A3196G
A21213G

Provisional GISAID query: Spike_K147I, Spike_M153T, Spike_N164K (also finds 3 unrelated seqs)

This subvariant of BA.2.3.20 is defined by S:K147I, ORF1A4255S and was detected only in Japan so far. Subtree also carries S:S408R.

![grafik](https://user-images.githubusercontent.com/102166254/201600732-a6765c7d-735a-44d4-a655-6199038c0de8.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d1e2_1e9140.json?c=pango_lineage_usher

EPI_ISL_15756178
EPI_ISL_15756177
EPI_ISL_15724179
EPI_ISL_15756182
EPI_ISL_15756180
EPI_ISL_15756162
EPI_ISL_15756161

**Comment by ryhisner** [comment]
It's fascinating to see these NTD mutations occurring in the S:144-152 area in BA.2.3.20. In addition to these seven, there have, as @agamedilab mentions, been three other unrelated K147I sequences. There have also been:

• 141-144del — 1 sequence
• Y144del - 7
• Y145H — 1 
• H146del — 5
• H146Y — 1
• K147E — 4
• K147N — 4
• N148D — 1
• N149D — 1
• K150E — 4
• K150I — 9
• S151I — 1
• W152R — 3

It's strange how BA.2.3.20 has a lot of spike diversity, including some mutations never seen before, but none of them seem to provide a substantial enough growth advantage to grow quickly, or even to increase its percentage of all BA.2.3.20 in any consistent way. Even convergent mutations like K444M, K444T, V445A, G446S, F486S, and F490S (among others) have appeared—some of them multiple times independently—but none of them have shown any real growth. Puzzling.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it has been found only 4 more times since November, and is showing markedly negative relative growth in Japan, this can be closed. Please re-propose or request reopening should this lineage show clear epidemiological significance in the future.
