### ISSUE TITLE
BA.2.3.20 with S:K147N (10 seq. UK, Denmark)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1335]
Proposal for a sublineage of BA.2.3.20
Earliest sequence: 19.10.22 (UK)
Countries detected: UK (England, Wales), Denmark

Defining mutations:
S:K147N = A22003T
ORF1A:T1822I =C5730T
G21778A
C21952T
C10279T
C12970T
T5278C
G19947A
C21622A

Prov. GISAID query: Spike_K147N, Spike_N164K

This subvariant of BA.2.3.20 is defined by S:K147N, ORF1A:T1822I and was detected th UK and Denmark. This cluster got a few more members uploaded since it was mentioned by @ryhisner in #1333.

![grafik](https://user-images.githubusercontent.com/102166254/201680077-5faedd74-6300-4994-ae61-7cdfc58bd01a.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25f11_246810.json?c=gt-S_147

EPI_ISL_15633736
EPI_ISL_15761029
EPI_ISL_15761031
EPI_ISL_15761036
Wales/PHWC-PKG1KK/2022
England/PHEP-YYF6MC5/2022
England/PHEP-YYF6MK9/2022
England/PHEP-YYF91A3/2022
England/PHEP-YYF9BEM/2022
England/PHEP-YYF9MWE/2022

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As is has not grown over December, and did not show a growth advantage, this can be closed for now. Please re-propose or request reopening should this lineage awaken in the future.
