### ISSUE TITLE
XBB with S:G257S (119 seq. 14+ countries)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1336]
Proposal for a sublineage of XBB
Earliest sequence: 15.09.22 (India)
Countries detected: India, Singapore, USA, Austria

Defining mutations:
S:G257S = G22331A

This subvariant of XBB is defined by S:G257Sand was detected in India, Singapore, USA and Austria.

![grafik](https://user-images.githubusercontent.com/102166254/201708372-f7931d85-a8e4-4a56-8d8d-0ad2958079a1.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_894e_265900.json?c=gt-S_257

![grafik](https://user-images.githubusercontent.com/102166254/201708557-224d4319-29fb-4496-bb50-ecaa82d1715a.png)

EPI_ISL_15229469
EPI_ISL_15378087
EPI_ISL_15398193
EPI_ISL_15720371
EPI_ISL_15760091
EPI_ISL_15760111
EPI_ISL_15760116
EPI_ISL_15760135
EPI_ISL_15760138
EPI_ISL_15760149
EPI_ISL_15760162
OP735690.1

**Comment by agamedilab** [comment]
119 seq as of 06.02.23.

![grafik](https://user-images.githubusercontent.com/102166254/217025008-2d7989ae-8fb6-4c58-b067-52c46fa1af4e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16937_124680.json?label=id:node_8009262

EPI_ISL_15213616, EPI_ISL_15229469, EPI_ISL_15229469, EPI_ISL_15378087, EPI_ISL_15378087, EPI_ISL_15398174, EPI_ISL_15398193, EPI_ISL_15398193, EPI_ISL_15635865, EPI_ISL_15720371, EPI_ISL_15760017, EPI_ISL_15760020, EPI_ISL_15760066, EPI_ISL_15760070, EPI_ISL_15760071, EPI_ISL_15760091, EPI_ISL_15760100, EPI_ISL_15760102, EPI_ISL_15760106, EPI_ISL_15760107, EPI_ISL_15760116, EPI_ISL_15760117, EPI_ISL_15760134, EPI_ISL_15760135, EPI_ISL_15760138, EPI_ISL_15760143, EPI_ISL_15760149, EPI_ISL_15760153, EPI_ISL_15760162, EPI_ISL_15789004, EPI_ISL_15870725, EPI_ISL_15913912, EPI_ISL_15930062, EPI_ISL_15983220, EPI_ISL_15983235, EPI_ISL_15983236, EPI_ISL_15983245, EPI_ISL_15983258, EPI_ISL_15983278, EPI_ISL_15983306, EPI_ISL_15983317, EPI_ISL_16019013, EPI_ISL_16024712, EPI_ISL_16048717, EPI_ISL_16056718, EPI_ISL_16056720, EPI_ISL_16121930, EPI_ISL_16156963, EPI_ISL_16156964, EPI_ISL_16157051, EPI_ISL_16161871, EPI_ISL_16183025, EPI_ISL_16199580, EPI_ISL_16199581, EPI_ISL_16199583, EPI_ISL_16199592, EPI_ISL_16199608, EPI_ISL_16199609, EPI_ISL_16199613, EPI_ISL_16199622, EPI_ISL_16199623, EPI_ISL_16199624, EPI_ISL_16199625, EPI_ISL_16199626, EPI_ISL_16199629, EPI_ISL_16199630, EPI_ISL_16199632, EPI_ISL_16199634, EPI_ISL_16199635, EPI_ISL_16199651, EPI_ISL_16199652, EPI_ISL_16342519, EPI_ISL_16383979, EPI_ISL_16412632, EPI_ISL_16412660, EPI_ISL_16436981, EPI_ISL_16437002, EPI_ISL_16437166, EPI_ISL_16453453, EPI_ISL_16485872, EPI_ISL_16520187, EPI_ISL_16528750, EPI_ISL_16541945, EPI_ISL_16568942, EPI_ISL_16604968, EPI_ISL_16752100, EPI_ISL_16819674, OP735690.1, OQ067303.1, OQ081522.1, OQ103965.1, OQ112481.1, OQ112486.1, OQ118565.1, OQ131289.1, OQ132466.1, OQ166118.1, OQ200233.1, OQ205609.1, OQ205736.1, OQ206137.1, OQ206308.1, OQ236863.1, OQ254713.1, OQ266478.1, OQ284781.1, OQ284791.1, OQ285649.1, OQ295041.1, OQ297776.1, OQ327568.1, OQ327669.1, OQ331803.1, OQ345509.1, OQ345794.1, OQ345806.1, OQ370289.1, OQ374865.1, OX408827.1

**Comment by corneliusroemer** [comment]
This part of the Usher tree is dodgy, there are lots of reversion, lots of signs of other known XBB lineages like XBB.1 appearing in there (see ORF8 stop,  that are known from other XBB lineages.

Then 257 reverts again higher up etc. I would be very wary to designate anything there. 

<img width="2136" alt="image" src="https://user-images.githubusercontent.com/25161793/217082998-6360fb51-39c5-408b-b8a2-a0a2f278cb2f.png"> - actually if anything can be designated there than that branch with S:323, as that's rather clean and recent - but it would be good if Usher regrafted that branch where it belongs.

Look at all the reversions there. Too few good quality sequences to designate. Also it's not really in recent circulation anymore.
<img width="2152" alt="image" src="https://user-images.githubusercontent.com/25161793/217083126-d7ba434c-5025-4c0a-9604-7b8139e974bf.png">
