### ISSUE TITLE
Likely BE.1 (Orf1b:M1156I) SubLineage(s)  circulating in Cameroon with S:N679R,Orf3a:E19D,Orf1b:M1156I (11 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1339]
Today Cameroon uploaded a bunch of sequences, analyzing them i spotted this new mutation S:679R sometimes coupled with S:K182R and always coupled with Orf3a:E19D and Orf1b:M1156I.
Usher doesnt put all the sequence in the same tree but in my view is more due to building issues or sequencing gaps .(@AngieHinrichs could u take a look please?)

Here the 3 relevant trees:
1
<img width="852" alt="Schermata 2022-11-14 alle 18 48 21" src="https://user-images.githubusercontent.com/87669813/201730471-ccae8e85-ce9f-42ad-a4d3-87c941fba674.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_3c780_27c6c0.json?c=pango_lineage_usher&label=nuc%20mutations:C1931A,C11750T,G16935A

2
<img width="1156" alt="Schermata 2022-11-14 alle 18 48 52" src="https://user-images.githubusercontent.com/87669813/201730552-e08037d3-7c15-49a6-8a6b-c4baeb751433.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_3c780_27c6c0.json?c=pango_lineage_usher&label=nuc%20mutations:G16935A

3
<img width="1140" alt="Schermata 2022-11-14 alle 18 49 26" src="https://user-images.githubusercontent.com/87669813/201730660-e7ca06c5-1ba4-4eb8-9785-7834a8203b49.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c780_27c6c0.json?label=nuc%20mutations:G16935A

Gisaid query: Spike_N679R,NS3_E19D,NSP13_M233I finds 11 viruses :

EPI_ISL_15763737, EPI_ISL_15763756-15763757, EPI_ISL_15763760,
EPI_ISL_15763762, EPI_ISL_15763764, EPI_ISL_15763766-15763767,
EPI_ISL_15763770, EPI_ISL_15763776, EPI_ISL_15763781

**Comment by AngieHinrichs** [comment]
I'm skeptical -- they are placed really far apart on BA.5.  Some have C1931A like BA.5.3, others have C1627T like BA.5.2.

**Comment by FedeGueli** [comment]
yeah @AngieHinrichs agree. i suppose these are or recombinants or contamination/sequencing artifacts . But still being a mutation straight in the FCS from a very undersampled area and being that mutation already popped up elsewhere as in S.Korea, i think it is worth monitoring. if nothing will pop up i ll close this one. Still there will be a trace of this mutation.

**Comment by FedeGueli** [comment]
closing this as no new sequence popped up anywhere
