### ISSUE TITLE
Potential BN.1.3/XBB.1 recombinant with multiple private mutations in N protein (2 sequences as of 2022-11-14)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1340]
I am proposing this potential recombinant with only 2 sequences based on its mutation profiles, especially in N protein.

### Description
**Recombinant between**: BN.1.3 and XBB.1
**Earliest sequence**: 2022/11/04 (Singapore local case)
**Most recent sequence**: 2022/11/04 (Singapore local case)
**Countries circulating**: Singapore

**Potential breakpoint**: somewhere between ORF1b and Spike NTD (16345 to 21808).
**Potential BN.1.3 donor**: BN.1.3 with ORF1a:H110Y and ORF1a:M3652I, such as EPI_ISL_14735990 from Singapore (local case collected on August 17th)

**Mutation profile**:
![image](https://user-images.githubusercontent.com/86835836/201870814-406544bb-ffe6-4677-b7d2-77fd77465981.png)
**Private mutation**: N:A50S, N:D144Y,N:R209I
**GISAID query**: NSP1_H110Y, NSP6_M58I, N_R209I

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/201871458-d272a1c4-a8cf-4e32-aca6-06df58a38240.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14c18_2f7f50.json?branchLabel=Spike%20mutations&c=gt-N_50&label=nuc%20mutations:C3796T

### Genomes:
EPI_ISL_15740431, EPI_ISL_15740449

**Comment by MCB6** [comment]
How does it compare with the numbered of N protein mutations in the more common strains? Implications for rapid antigen test sensitivity?

**Comment by braukmann** [comment]
Duplicate of issue #1305.

**Comment by FedeGueli** [comment]
> Duplicate of issue #1305.

they seem different ones, it is not a duplicate in my view.

**Comment by c19850727** [comment]
I'm going to close this issue for now as it's not growing.
