### ISSUE TITLE
BN.1.3 Sublineage with S:N149K, ORF1a:H110Y, ORF1a:S391F, & ORF1a:A687T (37 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1342]
### **Description**
**Sub-lineage of:** BN.1.3
**Earliest sequence:** 2022-10-17, Netherlands — EPI_ISL_15670776, EPI_ISL_15670777
**Most recent sequence:** 2022-11-8, Austria — EPI_ISL_15758191
**Countries circulating:** Netherlands (7), Italy (2), USA (2), Austria (1)
**Number of Sequences:** 12
**GISAID Query:** Spike_K356T, Spike_N149K
**CovSpectrum Query:** Nextcladepangolineage:BN.1.3* & S:N149K
**Substitutions on top of BN.1.3:**
**Spike:** N149K
**ORF1a:** H110Y, S391F, A687T
**Nucleotide:** C593T, C1437T, G2324A, C22009A, C24745T
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BN.1.3%20%2B%20N149K%20%2B%20ORF1aS391F%20%2B%20ORF1aA687T%20-%20subtreeAuspice1_genome_2a052_375eb0.json
 
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/33738461/201908539-90ba009b-53bd-412f-9e78-da7f4c81ac63.png">

**Evidence**
All 12 of these sequences have shown up very recently, and with appearances in Austria, Italy, the Netherlands, and USA (New Jersey), the geographic spread is already quite wide, all of which seems to indicate rapid growth. I’m not certain, but I think S:N149 might be the site of an N-linked glycan. If so, this could have a substantial effect on this area of spike.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15670203, EPI_ISL_15670776, EPI_ISL_15670777, EPI_ISL_15670780, EPI_ISL_15708258, EPI_ISL_15722042, EPI_ISL_15722055, EPI_ISL_15758191, EPI_ISL_15762703, EPI_ISL_15762705, EPI_ISL_15763339, EPI_ISL_15770645
</details>

**Comment by FedeGueli** [comment]
I have asked @fabriziochiodo a Glyco-scientist and mind of the design of super efficient cuban vaccines

**Comment by MCB6** [comment]
It was N glycosylated in Gong 2021 https://www.nature.com/articles/s41392-021-00809-8 among many other sites

**Comment by ryhisner** [comment]
Two more uploaded today. The three most recent sequences have been from USA (New Jersey), USA (California), and Italy. Total number of sequences is now 15.
