### ISSUE TITLE
BA.2.75.4 (S:L452R) Sublineage with S:K444T, S:D574V, & ORF1a:K4014R (168 seq, Jan 22)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1345]
**Description**
**Sub-lineage of:** BA.2.75.4
**Earliest sequence:** 2022-9-6, Singapore (Traveler from India)— EPI_ISL_14917768
**Most recent sequence:** 2022-11-3, England — EPI_ISL_15758527, EPI_ISL_15758586
**Countries circulating:**
**Number of Sequences:** 20
**GISAID Query:** Spike_K444T, Spike_D574V, Spike_L452R, NSP8_K72R
**CovSpectrum Query:** Nextcladepangolineage:BA.2.75.4* & S:K444T & S:D574V
**Substitutions on top of BA.2:75.4**
**Spike:** K444T, D574V
**ORF1a:** K4014R
**Nucleotide:** G8602A, A22893C, A12306G, A23283T, A26612T
 
 
**USHER Tree**
Note that though there are only 18 sequences on this tree (after subtracting duplicates), this is because Usher, rather comically, places two sequences from this lineage on the BA.2.76 tree.
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.2.75.4%20(L452R)%20%2B%20K444T%20%2B%20D574V%20%2B%20ORF1aK4014R%20-%20subtreeAuspice1_genome_6549_42b950.json
 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/33738461/202059028-fa8711e6-6fe6-4a6b-be60-0bfcbef0b58b.png">

**Evidence**
This clearly originated in India, but only slowly spread internationally. It seemed to appear in Australia (perhaps in travelers), then disappear for a month, only to return in the last couple weeks. The third and fourth sequences from England were uploaded yesterday, but nothing so far from continental Europe. One week ago the first two sequences from the USA were uploaded from Virginia.

The spike profile is certainly interesting, but it may be held back by the lack of any mutation at S:R346, S:348, and S:K356. R346T/S/I in particular has seemed to be a very easy mutation to pick up for most lineages, so it wouldn’t be surprising to see one of those appear in this lineage eventually, assuming it isn’t driven to extinction before that can happen.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_14917768, EPI_ISL_15357083, EPI_ISL_15357195, EPI_ISL_15357479, EPI_ISL_15358813, EPI_ISL_15363268, EPI_ISL_15469952, EPI_ISL_15474716, EPI_ISL_15573126, EPI_ISL_15580487, EPI_ISL_15609536, EPI_ISL_15617479, EPI_ISL_15654506, EPI_ISL_15705620, EPI_ISL_15705952, EPI_ISL_15731803, EPI_ISL_15732455, EPI_ISL_15732513, EPI_ISL_15758527, EPI_ISL_15758586
</details>

**Comment by ryhisner** [comment]
This seemed to vanish for a while but in recent days reappeared and after 12 sequences were uploaded over the past two days (mostly South Korea but one each from Belgium and Japan), it now stands at 56 sequences. 
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/33738461/208249740-cd1dc7ff-8578-4232-8d09-04bc79d6b52a.png">

**Comment by ryhisner** [comment]
Still a lot of this one in South Korea, and strangely, 12 sequences from North Carolina, USA, were uploaded last week.

**Comment by ryhisner** [comment]
15 sequences from South Korea uploaded three days ago (Thursday, Jan 19) and one uploaded today from Hawaii, USA. Total now 168 sequences.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BR.5 with 59 newly designated sequences, and 0 updated. Defining mutations A12306G (ORF1a:K4014R), A23283T (S:D574V), A26612T (following A22893C (S:K444T)).
