### ISSUE TITLE
Further BA.5.3.1 branch in South Africa which acquired S:R346T + C8836T - 250 sequences, prevalence around 10% in SA __ EDITED 4/01/23

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1347]
While checking south african sequences i noticed that a part of BA.5.3.1 with S:346T was still unassigned even after the designation of BE.7 BE.8 . It was  a bit unexpected to me so i went digging a bit on it, and discovered that there is abigger branch of BA.5.3.1 with S:346T that is still undesignated: one problem is that it branches off directly from BA.5.3.1 politomy so it can hardly be distinguished witha Gisaid query from the others ( and Nextclade assigns most of them to BE.7 consequently) , but i feel this deserves a designation on its own.

So we can designate it directly from the whole branch that is defined by BA.5.3.1 then T28693C then G22599C:
<img width="1135" alt="Schermata 2022-11-16 alle 22 38 56" src="https://user-images.githubusercontent.com/87669813/202300050-4358e454-cdd5-4f9e-891d-4dd1825996e5.png">

or choose the biggest branch of it, defined by Nuc : C8836T, that includes just 2/3 of the lineage :
<img width="1157" alt="Schermata 2022-11-16 alle 22 39 47" src="https://user-images.githubusercontent.com/87669813/202300228-809c2bc3-8e68-4291-96ca-9a4722e91dfc.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37b5_554610.json?c=pango_lineage_usher&label=nuc%20mutations:G22599C

Sequences: EPI_ISL_15698757
EPI_ISL_15427800
EPI_ISL_15698733
EPI_ISL_15698775
EPI_ISL_15613560
EPI_ISL_15698741
EPI_ISL_15698728
EPI_ISL_15613571
EPI_ISL_15613666
EPI_ISL_15698779
EPI_ISL_15613567
EPI_ISL_15613667
EPI_ISL_15698768
EPI_ISL_15613559
EPI_ISL_15698758
EPI_ISL_15698765
EPI_ISL_15613552
EPI_ISL_15698746
EPI_ISL_15698767
EPI_ISL_15728433
EPI_ISL_15427779
EPI_ISL_15613562
EPI_ISL_15728435
EPI_ISL_15611874
EPI_ISL_15427787
EPI_ISL_15698730
EPI_ISL_15613669
EPI_ISL_15613564
EPI_ISL_15698759
EPI_ISL_15613545
EPI_ISL_15698743
EPI_ISL_15613565
EPI_ISL_15698764
EPI_ISL_15698766

**Comment by AngieHinrichs** [comment]
For BE.8, there are some earlier sequences that indicate that C26110T (ORF3a:P240S) happened first, then G22599C (S:R346T) & others.  Here is a Taxonium view with red circles = subset of designated BE.8 sequences, pink=22599G and orange=22599C:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/186983/202316569-c1271b51-5424-4396-9796-182d2cdb90fb.png">

(Yesterday I did some pruning & re-optimization to fix the two back-mutations in the original path to BE.8 that you spotted earlier, and now it looks like the BE.8 label should be moved back a couple nodes to where 22599 is now placed.)

For comparison here is the start of the branch with just G22599C (after T28693C):
<img width="496" alt="image" src="https://user-images.githubusercontent.com/186983/202315720-874b4032-d901-4561-bce8-29455e0ef144.png">
-- there are some dates as early as 2022-05-31 on that branch, but most are later, ~contemporaneous with the BE.8 samples.

**Comment by FedeGueli** [comment]
Wow thanks very much @AngieHinrichs this makes things easier:
 i tried to put together a gisaid query but still it is not very specific: 
-NSP1_M85del,-NS3_P240S,-NSP3_T64I,-NS7A_T39A,-NSP3_S1375F,-NSP5_T45N,-NSP13_M233I,NSP2_Q376K,N_E136D,SPike_R346T

i suggest a rapid designation after looking the rapid deteriorating of the epi situation in South Africa (especially in KZN):
Not saying that it is directly linked to this lineage but the better we can describe viruses circualting there the easier we could spot some outlier that maybe is flying under the radar actually @corneliusroemer

**Comment by FedeGueli** [comment]
I ve tried to make a gisaid query bu really too hard to find one credible  (too much mini-lineages to exclude)
while i have checked SA variants' growth rate chart :
https://cov-spectrum.org/collections/71?country=South+Africa
last 3Months vs S:346T baseline and the situation is quite clear:
<img width="1324" alt="Schermata 2022-11-17 alle 10 43 00" src="https://user-images.githubusercontent.com/87669813/202411907-032cc5ff-d1cc-4deb-bb88-624949e4f706.png">
Being this sublineage missassigned as BE.7 it likely is contributing or maybe leading the actual growth in cases.

@corneliusroemer @InfrPopGen

**Comment by FedeGueli** [comment]
While we have seeing S:N460K becoming globally dominant (>50%) just after S:346T trespassed the 50% threshold worlwide,
in South Africa there was a different trend with S:346T  becoming dominant earlier before mid september and S:N460K accounting just for 25% of sequences as today:
<img width="827" alt="Schermata 2022-12-11 alle 12 59 23" src="https://user-images.githubusercontent.com/87669813/206902262-37cb0675-bef3-44b6-b64c-371e405950ee.png">

So, dear @corneliusroemer @InfrPopGen @AngieHinrichs @thomasppeacock ,
i think it is worth to designate this one after  it reached 266 seqs and it is the second biggest lineage circulating in South Africa as today
<img width="864" alt="Schermata 2022-12-11 alle 12 53 03" src="https://user-images.githubusercontent.com/87669813/206902038-d7773108-470e-4ee2-8119-3102bf7d9a57.png">

tree is much clearer now:
<img width="1143" alt="Schermata 2022-12-11 alle 13 02 20" src="https://user-images.githubusercontent.com/87669813/206902379-b3b14d68-fcfd-4239-bcd8-95c7f0aa007f.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_350f3_5b2fc0.json?label=id:node_2016124


And now this started to be exported internationally
<img width="1155" alt="Schermata 2022-12-11 alle 13 03 43" src="https://user-images.githubusercontent.com/87669813/206902457-9245c03d-4ae6-4fb9-ad29-64a60444610d.png">

**Comment by FedeGueli** [comment]
i found a gisaid query that identify the main lineage of this proposed one: **T28693C, G22599C, C8836T** 
it finds 208 sequecnes on Gisaid
while Usher shows 250 sequences for it
<img width="1160" alt="Schermata 2023-01-05 alle 00 38 18" src="https://user-images.githubusercontent.com/87669813/210670253-49f7acae-ed36-474f-a59d-db94767ce2fe.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_a1ed_60a4c0.json?branchLabel=nuc%20mutations&c=gt-nuc_8836&label=id:node_6179064

It is a really big lineage in South Africa round 10-12% in the last weeks
<img width="1098" alt="Schermata 2023-01-05 alle 00 40 08" src="https://user-images.githubusercontent.com/87669813/210670435-17c1c746-cc1f-423b-ac31-c664ef5a1abd.png">

@thomasppeacock @AngieHinrichs @corneliusroemer now i would designate (starting with C8836T) it so we would have completed the picture of this variant soup phase there.

**Comment by FedeGueli** [comment]
It seems too late to be designated closing it for now.
