### ISSUE TITLE
BA.5.7 Sublineage with S:Y453F, ORF1a:A1679T, & Unusual Diversity, Possible Molnupiravir Origin (Australia, 9 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1348]
**Description**
**Sub-lineage of:** BA.5.7
**Earliest sequence:** 2022-10-12, Australia, Queensland — EPI_ISL_15532754, EPI_ISL_15532755
**Most recent sequence:** 2022-10-21, Australia, Queensland — EPI_ISL_15797427
**Countries circulating:** Australia
**Number of Sequences:** 9
**GISAID Query:** Spike_Y453F, NSP3_A861T
**CovSpectrum Query:** Nextcladepangolineage:BA.5.7* & S:Y453F & ORF1a:A1679T
**Substitutions on top of BA.:**
**Spike:** Y453F
**ORF1a:** A1679T
**Nucleotide:** G5300A, A22920T
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/Molnupiravir%20-%20BA.5.7%20-%20Y453F%20%2B%20ORF1aA1679T%20%2B%20Unusual%20Diversity%20-%20subtreeAuspice1_genome_37d4_618400.json
 
![image](https://user-images.githubusercontent.com/33738461/202463907-9de46ccf-de8c-4ca4-bd99-236bc99cfe9b.png)

**Evidence**
As you can see from the Usher tree above, the diversity on this tree is extraordinary, particularly given that all the sequences were collected in a 10-day time period. Examining every branch here, I found that other than S:Y453F (A22920T), every single nucleotide mutation on this tree is a transition (C->T, T->C, A->G, G->A). In particular, C->T and G->A predominate. These are the of hallmarks of molnupiravir treatment, which the rapid accumulation of mutations in this lineage also suggests.
 
I’ve documented dozens of sequences that bear the unmistakable signatures of molnupiravir treatment. They have come from several different countries, but the bulk have been from Australia. I have no idea why Australia should churn out so many of these sequences—including at least four instances in which there appear to have been numerous transmissions, most notably the lineages mentioned in Issues #1286 and #1334, submitted by @Asinickle and @agamedilab—but I wish someone would investigate. As I've discussed elsewhere, molnupiravir is a completely ineffective treatment, so its use represents all risk and no gain.
 
Below is an analysis of the relevant measures for identifying possible molnupiravir causation in the top-rightmost two sequences from the tree and for the sum total of all branches on this tree (each branch only counted once, no matter how many sequences on it). The only measure that doesn’t fit for the top-right two sequences is the relatively high proportion of nonsynonymous mutations, which at 79.4% is quite high. However, when considering the entire tree, the nonsynonymous proportion drops dramatically, to 58.1%.

![image](https://user-images.githubusercontent.com/33738461/202464851-23a0336b-02d3-4c32-9da2-e322420a184a.png)
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15532754-15532755, EPI_ISL_15532776, EPI_ISL_15532778,
EPI_ISL_15729147, EPI_ISL_15797427, EPI_ISL_15797464,
EPI_ISL_15797823, EPI_ISL_15797872
</details>

**Comment by thomasppeacock** [comment]
Going to stick a monitor label on this until we can have it confirmed they all arent from a single patient

**Comment by MCB6** [comment]
Some of the sample id's look consecutive, but they came from two different labs on opposite ends of Brisbane City, some 12 km away from each other

**Comment by hsnguyen** [comment]
@thomasppeacock I can confirm these sequences were from different patients. We've been doing de-duplication based on epi info before submitting so you can expect QLD sequences were collected from different patients if they're 0 SNP different.

@ryhisner thanks for your proposals and analyses. Yes we've been seeing long-branch sequences popping up more often in Australia recently. Most of them were stand-alone sequences or forming small clusters and ultimately died out but we're scanning and reporting them weekly as well.
[Antiviral treatments](https://www.health.gov.au/health-alerts/covid-19/treatments/eligibility) including molnupiravir prescriptions are becoming more available here and that's maybe the reason for unusual transition rates.

Cheers,

**Comment by hsnguyen** [comment]
@thomasppeacock we've got a formal request from UK and will grab more genomic and epi info including these samples soon for you :)

**Comment by ryhisner** [comment]
No more sequences of this recently, so I'm closing.
