### ISSUE TITLE
BQ.1.1 with S:Y144-, ORF3a:H204Y, ORF1a:T891I and ORF1a:R1404C  in Denmark and Germany (33 sequences)

### ISSUE THREAD

**Issue by AleksanderRing** [cov-lineages/pango-designation#1349]
## Proposal for new sublineage of BQ.1.1 with additional mutations S:Y144-, ORF3a:H204Y, ORF1a:T891I and ORF1a:R1404C 

Countries detected: Denmark (32), Germany (1)

Earliest sequence: (dd-mm-yyyy) 29-10-2022

Defining mutations: S:Y144-, ORF3a:H204Y, ORF1a:T891I, ORF1a:R1404C 

GISAID query: NSP3_R586C,NSP3_T73I,NS3_H204Y

Evidence:
![bq 1 1_with_muts](https://user-images.githubusercontent.com/102508994/202462310-c57fa781-fa6c-4132-b1de-8302242cfb81.png)

32 sequences uploaded to GISAID and more have been sequenced pending upload to GISAID

EPI_ISL_15635014, EPI_ISL_15647702, EPI_ISL_15668351,
EPI_ISL_15668397, EPI_ISL_15697468, EPI_ISL_15697553,
EPI_ISL_15697859, EPI_ISL_15697963, EPI_ISL_15715598,
EPI_ISL_15715705, EPI_ISL_15715810, EPI_ISL_15715828,
EPI_ISL_15715931, EPI_ISL_15716293, EPI_ISL_15716327,
EPI_ISL_15716527, EPI_ISL_15716566, EPI_ISL_15726623,
EPI_ISL_15726641, EPI_ISL_15726651, EPI_ISL_15726892,
EPI_ISL_15726904, EPI_ISL_15742920, EPI_ISL_15757513,
EPI_ISL_15757552, EPI_ISL_15757555, EPI_ISL_15757579,
EPI_ISL_15757643, EPI_ISL_15757652, EPI_ISL_15786981,
EPI_ISL_15787002, EPI_ISL_15787679, EPI_ISL_15787774

**Comment by ryhisner** [comment]
I think this has mostly already been designated as BQ.1.1.20. The ORF1a mutations might be new. 
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/33738461/202586353-5684f33a-e417-475c-9fac-2f4a44e54a44.png">
https://nextstrain.org/staging/nextclade/sars-cov-2/21L?branchLabel=aa&label=clade:22E%20%28Omicron%29&tl=Nextclade_pango

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As this has been showing negative growth relative to its parent (BQ.1.1.20) over nearly two months now, this can be closed at the moment. Nevertheless, please re-propose or request re-opening should this lineage show clear signs of relative growth in the future.
