### ISSUE TITLE
New set of B.1.617.2 sequence designations

### ISSUE THREAD

**Issue by chrisruis** [cov-lineages/pango-designation#135]
The number of database sequences _assigned_ to B.1.617.2 was far larger than the number of sequences _designated_ as B.1.617.2 (i.e. in lineages.csv). We therefore took all sequences assigned to B.1.617.2 on GISAID as of 5th July 2021 and filtered them to retain those that have all 13 SNPs in the B.1.617.2 constellation (found [here](https://github.com/cov-lineages/constellations/blob/main/constellations/definitions/cB.1.617.2.json)) and <5% ambiguous genome positions. We have designated the 55,286 sequences that match these criteria as B.1.617.2 in [v1.2.33](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.33)

There are now 55,460 sequences designated B.1.617.2

**Comment by shay671** [comment]
Why synonymous mutations and extragenic regions mutations are not included in the definition?

**Comment by chrisruis** [comment]
Hi @shay671 we exclude the UTRs from our pipelines so extragenic mutations won't be included. Synonymous mutations can be included in the constellation if they are pulled out by scorpio.

We standardise and take the constellation from scorpio - if you think there are synonymous mutations that would be useful to include, please do raise an issue over at https://github.com/cov-lineages/constellations
