### ISSUE TITLE
BQ.1.18 with S:Y144-, S:F490S and N:G30- in New York (8 sequences)

### ISSUE THREAD

**Issue by rquiroga7** [cov-lineages/pango-designation#1350]
Countries detected: New York, USA (8)

Earliest sequence: (dd-mm-yyyy) 19-10-2022

Defining mutations: S:Y144-, S:F490S, N:G30-

Most of these have a pango designation of BQ.1.18, others BQ.1.1

Usher tree (provided by @FedeGueli):
![image](https://user-images.githubusercontent.com/8103453/202749655-b5cf5a02-9961-4a6e-a788-976f3271d275.png)

8 sequences uploaded:
USA/NY-PRL-221104_01B07/2022|EPI_ISL_15749855|2022-11-03
USA/NY-CDC-QDX43023894/2022|EPI_ISL_15770470|2022-10-29
USA/NY-PRL-221024_00C17/2022|EPI_ISL_15577542|2022-10-19
USA/NY-PRL-221102_00L03/2022|EPI_ISL_15749536|2022-10-31
USA/NY-PRL-221102_01G16/2022|EPI_ISL_15749647|2022-11-01
USA/NY-PRL-221102_00A22/2022|EPI_ISL_15749371|2022-10-31
USA/NY-CDC-LC0928227/2022|EPI_ISL_15779908|2022-11-04
USA/NY-PRL-221102_00I12/2022|EPI_ISL_15749503|2022-10-31

Please excuse me for any mistakes made, first time submitting an issue here.

**Comment by FedeGueli** [comment]
Congrats @rquiroga7 very good spot! 

looking at the route from roots highlighted by usher.bio search for these sequences it should have an additional nuc mutation ( while USher is blind to deletions so dont worry S:144del is there but invisble):

C1931A > G28681T > G16935A > T2954C > C11750T > C28312T > S:K444T (A22893C ) > T14257C > S:N460K (T22942A) > A17039G > S:R346T (G22599C)> **G13240A**, S:F490S (T23031C )
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ae4a_7a7680.json?c=pango_lineage_usher&label=nuc%20mutations:G13240A,T23031C

**Comment by rquiroga7** [comment]
I now count 17 sequences from US and 2 from Canada, so 11 additional sequences to the firt 8 reported.

![image](https://user-images.githubusercontent.com/8103453/203827647-6692309a-b22c-44a5-8677-1676949c2e9d.png)

**Comment by c19850727** [comment]
23 sequences as of 2022-11-25. 

![image](https://user-images.githubusercontent.com/86835836/204069865-24d8aa71-79b1-48ec-a6f0-836e9d9521d9.png)

**Comment by corneliusroemer** [comment]
This is already designated as BQ.1.1.25 🙃

**Comment by rquiroga7** [comment]
🙃🙃🙃

**Comment by rquiroga7** [comment]
🙃🙃

I looked at lineage_notes and BQ.1.1.25 did not say anything of Y144del, so thought they were not the same.

**Comment by rquiroga7** [comment]
Oh, I also noticed I opened this issue before BQ.1.1.25 was designated. Was worried I had overlooked something. I suggest this issue is closed, and S:Y144- be added as a definining mutation to the BQ.1.1.25 lineage notes.

**Comment by FedeGueli** [comment]
This was designated via Commit: https://github.com/cov-lineages/pango-designation/commit/188716eef80f7a7d9b3d695872997bc68e0ef95e

**Comment by FedeGueli** [comment]
Please @corneliusroemer @InfrPopGen @thomasppeacock add milestone to this one.
