### ISSUE TITLE
BQ.1.1.20 with S:S494P and ORF1a:Q2639H from Denmark (3 sequences)

### ISSUE THREAD

**Issue by rquiroga7** [cov-lineages/pango-designation#1351]
Countries detected: Denmark (3)

Earliest sequence: (dd-mm-yyyy) 07-11-2022

Defining mutations: S:S494P, ORF1a:Q2639H, S:SY144-, ORF3a:H204Y

Although Pango Usher lineage is BQ.1.1.20, actually not sure of the designation, there are many nucleotide differences between them (114 shared mutations, 28 unique to BQ.1.1 and 3 unique to these sequences).

Usher tree (provided by @FedeGueli):

![image](https://user-images.githubusercontent.com/8103453/202763185-960dc68d-6c7f-4d9c-9f43-83b31fa03aac.png)

Sequences:
Denmark/DCGC-609029/2022\|EPI_ISL_15757451\|2022-11-07
Denmark/DCGC-609009/2022\|EPI_ISL_15757430\|2022-11-07
Denmark/DCGC-609322/2022\|EPI_ISL_15757741\|2022-11-07

**Comment by rquiroga7** [comment]
One more sequence from Sweden:

hCoV-19/Sweden/01_SE100_22CS107367/2022

**Comment by FedeGueli** [comment]
still 3 sequences i think this should be closed.

**Comment by rquiroga7** [comment]
Agreed
