### ISSUE TITLE
CR.1 + S:144del + Orf1a:D2592G  + S:H146Q - 16 sequences 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1355]
As for #1354 it was @shay671 that led me to discover this new CR.1 sublineage after noticing that a good share of CR.1 sequences had acquired S:144del.

So the lineage i want to propose here is the following:

CR.1 + G15957T + Orf1a:D2592G (A8040G) + T29665C (Orf10:36) + S:H146Q (C22000A) 
![Schermata 2022-11-20 alle 13 40 08](https://user-images.githubusercontent.com/87669813/202902371-f7b85cf4-0de5-4561-81f3-414ee1fec144.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d3a0_a0c8b0.json?c=pango_lineage_usher&label=nuc%20mutations:A8040G

GISAID QUERY : Spike_K444R,Spike_R346T,NSP3_D1774G,SPIKE_H146Q,SPIKE_Y144DEL, finds 12 sequences:
EPI_ISL_15632518, EPI_ISL_15634583, EPI_ISL_15684787,
EPI_ISL_15715823, EPI_ISL_15742675, EPI_ISL_15742793,
EPI_ISL_15776174, EPI_ISL_15776512, EPI_ISL_15776651,
EPI_ISL_15812571, EPI_ISL_15819072, EPI_ISL_15826179

mainly from Denmark.

What striked me of this sublineage is the shape of the tree with nuc mutations accumulating very rapidly after gaining S:146Q.
I m not aware of any known interaction between S:144del and 146Q but i think it is worth monitoring it for a while , helped by the efficient danish sequencing and genomic surveillance.

**Comment by FedeGueli** [comment]
14 seqs as today

**Comment by FedeGueli** [comment]
16 seqs as today

**Comment by MCB6** [comment]
Can't find CR.1.1 topic... apologies for commenting here. Just wanted to mention explosive growth of CR.1.1 (with 144del) in Phoenix AZ.
![image](https://user-images.githubusercontent.com/93294184/204163274-9b4d211c-e8ef-4b1f-a775-9ee89a3348d9.png)
