### ISSUE TITLE
BF.7 + S:G257D + ORF1a:A1812V(519sequences)-Japan

### ISSUE THREAD

**Issue by DoropFan** [cov-lineages/pango-designation#1358]
Description
Sub-lineage of:BF.7
Earliest sequence:2022-10-25
Most recent sequence:2022-11-11
Countries circulating:Japan only
Sequences:6

Nucleotide mutations:G8-, A22-, A1558G, C5700T, G12170A, G22332A, G28077A
Amino acid changes:S:G257D, ORF1a:I431M, ORF1a:A1812V, ORF1a:A3969T, ORF8:V62M

CovSpectrum:BF.7 (Nextclade) + ORF1a:A1812V, ORF1a:A3969T, ORF1a:I431M, ORF8:V62M, S:G257D
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3AG257D%2CORF1a%3AA1812V%2CORF1a%3AA3969T%2CORF1a%3AI431M%2CORF8%3AV62M&nextcladePangoLineage=BF.7&

CovSpectrum Compare variants:https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nextcladePangoLineage=BF.7&aaMutations1=S%3AG257D%2CORF1a%3AA1812V%2CORF1a%3AA3969T%2CORF1a%3AI431M%2CORF8%3AV62M&nextcladePangoLineage1=BF.7&analysisMode=CompareEquals&
![924bf7](https://user-images.githubusercontent.com/118802079/203293218-25fb1d72-c05a-48c5-98a4-ebee09ac9ffa.jpg)

Genomes
EPI_ISL_15623082, EPI_ISL_15784708, EPI_ISL_15727216, EPI_ISL_15623073, EPI_ISL_15756770, EPI_ISL_15798100

**Comment by ryhisner** [comment]
Can I suggest changing this proposal to simply BF.7 + S:G257D + ORF1a:A1812V? There are 153 sequences of that lineage, including 45 that have been uploaded in the past 7 days. It is entirely confined to Japan, but it appears to be growing rapidly there, though perhaps this is mostly the effect of rising case numbers there. 

https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BF.7%20%2B%20G257D%20%2B%20ORF1a1812V%20-%20subtreeAuspice1_genome_22ea5_c8ecc0.json (Usher calls all BF.7 lineages BA.2 now for some reason, so ignore that aspect of the tree pictured below.)

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/33738461/205490494-9dfcc855-dcba-4c1e-b483-8489bfb064c1.png">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_14638199, EPI_ISL_14687446, EPI_ISL_14838480, EPI_ISL_14994346, EPI_ISL_15036899, EPI_ISL_15069227, EPI_ISL_15126082, EPI_ISL_15151549, EPI_ISL_15201292, EPI_ISL_15206089, EPI_ISL_15230866, EPI_ISL_15230869, EPI_ISL_15230871, EPI_ISL_15230873, EPI_ISL_15315306, EPI_ISL_15315350, EPI_ISL_15361552, EPI_ISL_15377430, EPI_ISL_15383446, EPI_ISL_15383665, EPI_ISL_15429079, EPI_ISL_15437418, EPI_ISL_15437508, EPI_ISL_15438701, EPI_ISL_15464185, EPI_ISL_15464189, EPI_ISL_15492188, EPI_ISL_15494847, EPI_ISL_15503259, EPI_ISL_15503308, EPI_ISL_15503640, EPI_ISL_15504561, EPI_ISL_15517281, EPI_ISL_15578711, EPI_ISL_15596868, EPI_ISL_15596875, EPI_ISL_15597139, EPI_ISL_15597344, EPI_ISL_15600485, EPI_ISL_15610129, EPI_ISL_15610415, EPI_ISL_15623073, EPI_ISL_15623082, EPI_ISL_15641933, EPI_ISL_15642118, EPI_ISL_15642119, EPI_ISL_15642121, EPI_ISL_15642137, EPI_ISL_15642433, EPI_ISL_15673621, EPI_ISL_15694325, EPI_ISL_15695553, EPI_ISL_15712226, EPI_ISL_15724241, EPI_ISL_15724320, EPI_ISL_15727216, EPI_ISL_15734599, EPI_ISL_15734600, EPI_ISL_15735998, EPI_ISL_15736271, EPI_ISL_15736335, EPI_ISL_15736337, EPI_ISL_15736343, EPI_ISL_15736344, EPI_ISL_15753705, EPI_ISL_15753708, EPI_ISL_15753713, EPI_ISL_15754082, EPI_ISL_15754126, EPI_ISL_15756491, EPI_ISL_15756493, EPI_ISL_15756497, EPI_ISL_15756516, EPI_ISL_15756770, EPI_ISL_15774382, EPI_ISL_15784708, EPI_ISL_15795464, EPI_ISL_15798100, EPI_ISL_15808368, EPI_ISL_15808369, EPI_ISL_15808370, EPI_ISL_15808371, EPI_ISL_15823556, EPI_ISL_15823859, EPI_ISL_15823863, EPI_ISL_15823876, EPI_ISL_15823926, EPI_ISL_15831546, EPI_ISL_15831853, EPI_ISL_15831878, EPI_ISL_15831884, EPI_ISL_15834855, EPI_ISL_15835186, EPI_ISL_15851535, EPI_ISL_15875265, EPI_ISL_15894278, EPI_ISL_15894451, EPI_ISL_15894489, EPI_ISL_15894519, EPI_ISL_15894731, EPI_ISL_15908431, EPI_ISL_15908433, EPI_ISL_15909358, EPI_ISL_15910365, EPI_ISL_15910424, EPI_ISL_15916736, EPI_ISL_15916825, EPI_ISL_15916938, EPI_ISL_15923409, EPI_ISL_15923718, EPI_ISL_15923719, EPI_ISL_15923720, EPI_ISL_15923721, EPI_ISL_15924032, EPI_ISL_15924072, EPI_ISL_15924110, EPI_ISL_15924606, EPI_ISL_15925277, EPI_ISL_15937255, EPI_ISL_15937308, EPI_ISL_15953540, EPI_ISL_15953544, EPI_ISL_15954057, EPI_ISL_15954201, EPI_ISL_15954224, EPI_ISL_15954242, EPI_ISL_15954282, EPI_ISL_15954346, EPI_ISL_15954455, EPI_ISL_15954471, EPI_ISL_15954656, EPI_ISL_15967701, EPI_ISL_15972455, EPI_ISL_15981399, EPI_ISL_15981696, EPI_ISL_15981710, EPI_ISL_15981759, EPI_ISL_15981766, EPI_ISL_15981781, EPI_ISL_15981966, EPI_ISL_15981970, EPI_ISL_15981981, EPI_ISL_15982180, EPI_ISL_15982181, EPI_ISL_15982182, EPI_ISL_15997238, EPI_ISL_15997334, EPI_ISL_15997358, EPI_ISL_15997368, EPI_ISL_15997417, EPI_ISL_15999932, EPI_ISL_16000246, EPI_ISL_16000254
</details>

**Comment by DoropFan** [comment]
Thank you @ryhisner
Change title.

**Comment by FedeGueli** [comment]
NSP3_A994V,Spike_G257D,Spike_R346T finds now 171 viruses

**Comment by FedeGueli** [comment]
275 seqs as today

**Comment by FedeGueli** [comment]
296 as today

**Comment by FedeGueli** [comment]
413 as today. @InfrPopGen i think this deserves to be designated

**Comment by FedeGueli** [comment]
@DoropFan @InfrPopGen @corneliusroemer i unluckily noticed that this lineage is very well represented in hospitalized cases even if it is just around 1% of samples in Japan . a designation could help to clarify its role there.

**Comment by FedeGueli** [comment]
472 sequences. this goes on growing.

**Comment by FedeGueli** [comment]
519 seqs as today

**Comment by FedeGueli** [comment]
One sequence uploaded from Shandong
