### ISSUE TITLE
BA.4.6.3 with S:S494P, ORF7a:K32N, and apparent S:K417N reversion, 3 sequences from California, USA

### ISSUE THREAD

**Issue by rquiroga7** [cov-lineages/pango-designation#1359]
Sub-lineage of: BA.4.6.3
Earliest sequence: 2022-10-28
Most recent sequence: 2022-10-28
Countries circulating: USA

I have been looking for lineages with 8 or more key spike mutations using Colelction 86 on COV Spectrum. The lineage I am proposing consists of 3 sequences from California, United States, which seem to be BA.4.6.3 that picked up the S:S494P mutation.

Genomes:
USA/CA-CDPH-FS48078510/2022\|EPI_ISL_15819259\|2022-10-28
USA/CA-CDPH-FS48078511/2022\|EPI_ISL_15819260\|2022-10-28
USA/CA-CDPH-FS48078508/2022\|EPI_ISL_15819258\|2022-10-28

Evidence
![image](https://user-images.githubusercontent.com/8103453/203368291-cdaf108e-2a62-4995-9646-4b070a066b4d.png)

**Comment by MCB6** [comment]
These three have consecutive id's and were collected on the same day in rural Imperial county, with just 3 more additional sequences from there on the same date. Probably a non-independent small cluster despite being collected for baseline surveillance

**Comment by rquiroga7** [comment]
Very good observation

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it has not been re-detected, and not seen over the past two months, this can be closed for now.
