### ISSUE TITLE
BA.2.75*/BA.5* Recombinant with S:K986Q & other private mutations (France, 8 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1360]
### **Description**
**Sub-lineage of:** Recombinant, BA.2.75* (likely BN.1* or BM.1.1*) and BA.5
**Earliest sequence:** 2022-11-12, France — EPI_ISL_15791904, EPI_ISL_15791905, EPI_ISL_15791906
**Most recent sequence:** 2022-11-15, France — EPI_ISL_15840068, EPI_ISL_15840071, EPI_ISL_15840078
**Countries circulating:** France
**Number of Sequences:** 7
**GISAID Query:** Spike_K986Q, Spike_K356T, Spike_F486S
**CovSpectrum Query:** S:K986Q & S:K356T & ORF3a:S74F
**Probable Private Substitutions on top of BA.2.75/BA.5:**
**Spike:** K986Q
**ORF3a:** S74F, S171L
**ORF1a:** T4175I
**ORF1b:** H364Y
**Nucleotide: (Uncertain)** C12789T, C14503T, A24518C, C25613T, C25904T (and likely others)
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/Recombinant%20-%20BA.2.75-BA.5%20-%20K986Q%20-%20subtreeAuspice1_genome_3d990_d2bfa0.json
 
![image](https://user-images.githubusercontent.com/33738461/203418773-2e30bbca-27a5-4f45-bfe1-1ea9e368ec47.png)

As with all recombinants, the Usher Tree doesn’t have much meaning, but I’m sticking the link here anyway.

![image](https://user-images.githubusercontent.com/33738461/203418311-4ef1c964-f28a-4709-bbfc-cb1935946792.png)

 
**Evidence**
This recombinant seems to have several private mutations, making its exact origins somewhat unclear. However, it seems likely to be either a BN.1 or BM.1.1.4 that has combined with a BA.5 of some sort or else an XBD. The ORF9b mutations D16G and R47P make BA.5.2.35 seem like a possibility, but this lineage doesn’t have many other nucleotide mutations of BA.5.2.35 in the 26275+ range, which is the BA.5 portion of this recombinant. According to CovSpectrum, there have been 35 sequences in the past three months with all 15 of the nucleotide mutations from 26270 upward that this lineage shares. Of these sequences, 11 are classified as XBD, eight as BF.26, and the rest from a variety of BA.5 lineages.
 
![image](https://user-images.githubusercontent.com/33738461/203418460-0ef5eac4-96dd-4521-a544-373dfb2b9104.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=%5B15-of%3A+C26270T%2C+G26529A%2C+C26577G%2C+G26709A%2C+A27038G%2C+C27807T%2C+C27889T%2C+A28271T%2C+C28311T%2C+A28330G%2C+G28423C%2C+G28881A%2C+G28882A%2C+G28883C%2C+A29510C%5D&
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15791904, EPI_ISL_15791905, EPI_ISL_15791906, EPI_ISL_15840068, EPI_ISL_15840071, EPI_ISL_15840078, EPI_ISL_15840084
</details>

**Comment by FedeGueli** [comment]
Great catch @ryhisner also @doropfan found this after you so i had two glances at it:

Maybe it is worth highlighting it has S:A1020S and for that reason Usher places it in the XBD tree

**Comment by corneliusroemer** [comment]
Let's wait for sequences from another lab

**Comment by ryhisner** [comment]
Still waiting. Seems dead.
