### ISSUE TITLE
CM.8.1 (BA.2.3.20 + S:G446S, S:F486S) Sublineage with S:R403K, ORF1a:D1962N, & ORF1a:L3606F (3 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1361]
### **Description**
**Sub-lineage of:** CM.8.1
**Earliest sequence:** 2022-11-1, Japan — EPI_ISL_15851253
**Most recent sequence:** 2022-11-2, Japan — EPI_ISL_15851304, EPI_ISL_15851305
**Countries circulating:** Japan
**Number of Sequences:** 3
**GISAID Query:** Spike_R403K, Spike_E484R
**CovSpectrum Query:** Nextcladepangolineage: CM.8* & S:R403K
**Substitutions on top of CM.8.1:**
**Spike:** R403K
**ORF1a:** D1962N (NSP3_D1144N), L3606F (NSP6_L37F)
**Nucleotide:** C1960T, C2485T, T6148A, G6149A, G11083T, C11767T, G22770A
 
 
**USHER Tree**
For some reason, Usher hides the ORF1a:L3606F (mutation found in all sequences of this lineage. And again, the C23013G / A484G nucleotide mutation is fake and appears on any BA.2.3.20 sequence uploaded to Usher.
 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.2.3.20%20-%20R403K%20%2B%20G446S%2C%20F486S%20(CM.8.1)%20-%20subtreeAuspice1_genome_112f7_cb9520.json

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/33738461/203451024-b2b98b37-a2af-46bf-85d1-9f854fc027f5.png">
 
**Evidence**
In just the past few days, CM.8.1 has started to grow.  S:G446S and S:F486S are, of course, well known immune-evasive mutations, but F486S imposes a steep cost in loss of ACE2 affinity—substantially larger than F486V does on a BA.2 background according to the Bloom Lab RBD Heat Map (though the higher RBD expression may partly make up for the loss). https://jbloomlab.github.io/SARS-CoV-2-RBD_DMS_Omicron/RBD-heatmaps/
 
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/33738461/203451246-5c60fd1d-437d-49a1-b11a-a1c16d98a9f7.png">

Together with the modest ACE2-affinity loss imposed by S:G446S, CM.8.1 very likely has substantially lower ACE2 affinity than all other BA.2.3.20 sublineages. This can readily be seen on the NextClade 21L tree, which displays predicted ACE2 affinity scores for each sublineage.
 
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/33738461/203451155-de1c1de1-caa0-4f08-a628-124f941219e5.png">
 
One of the few mutations that seems to be viable and which substantially increases ACE2 affinity on a BA.2 background is S:R403K. (On a BA.1 background, R403K actually weakens ACE2 affinity, presumably due to the effect of the S:D405N and S:R408S mutations found in BA.2 but not BA.1.)
 
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/33738461/203451287-aab21419-b58a-448f-903e-14a8e67f505a.png">

It’s not entirely clear what the ideal ACE2 affinity is or whether such an increase in ACE2 affinity would necessarily be advantageous in CM.1. However, we have seen ACE2-affinity-increasing mutations—most notably S:N460K and S:R493Q—paired with other immune-evasive mutations, presumably because they help offset the decreases in ACE2 binding strength that accompany most escape mutations. It’s possible that S:R403K would create more space for CM.8.1 to mutate, enabling it to further evade increasing population immunity and facilitating its spread.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15851253, EPI_ISL_15851304, EPI_ISL_15851305
</details>

**Comment by Mydtlwn** [comment]
In addition to this strain, are there any other sub-strains of CM.8.1 worthy of designation?

**Comment by ryhisner** [comment]
@Mydtlwn, not that I know of yet. It's growing, but it's still a small lineage in terms of sequences submitted. But with 14 sequences from California uploaded  in the past 48 hours, it may not be long before CM.8.1 sprouts some sublineages. One possible future candidate sublineage from California has ORF1a:E673K, two of which also have N:T49S.

**Comment by Mydtlwn** [comment]
thx.

**Comment by ryhisner** [comment]
This one seems dead.
