### ISSUE TITLE
Potential BA.2/BA.5 recombinant (6 seqs., UK) 

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1362]
Proposal for a sublineage of BA.2/BA.5
Earliest sequence: 16.11.22 (UK)
Countries detected: UK

Defining mutations:
nuc	unique	C1931A, G18910T, G24584A
nuc	homoplasies	C1471T, T1627C, C5183T, C11750T, G22898A, C27509T
nuc	reversionsToRoot	T1627C
ORF1ab	unique	Q556K, D6216Y
ORF1ab	homoplasies	P1640S, L3829F
S	unique	V1008M
S	homoplasies	G446S
ORF7a	homoplasies	T39I

This sublineage is defined by S:V1008M and S:G446S as well as several other mutations (see above). Nextclade identifies the sequences a BA.5.2.1 while Usher puts them nested within BA.2. I suspect this could be a potential recombinant.

![grafik](https://user-images.githubusercontent.com/102166254/203530868-188574b4-8760-46e4-98a4-09bb91ea1575.png)

![grafik](https://user-images.githubusercontent.com/102166254/203530970-2946d8eb-652d-4e4b-bad7-80fef8c530a1.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a4bb_df3180.json?c=pango_lineage_usher

EPI_ISL_15878195, EPI_ISL_15878231, EPI_ISL_15878266,
EPI_ISL_15878301

**Comment by agamedilab** [comment]
![grafik](https://user-images.githubusercontent.com/102166254/203550677-e72ff349-f24b-4b8e-b929-67954cf4b56b.png)

Prov. GISAID: Spike_V1008M, Spike_G446S, Spike_V6F

**Comment by agamedilab** [comment]
+ 2 UK: EPI_ISL_15909462, EPI_ISL_15909614

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it has not been seen over the past two months, and has not come close to the numbers required to justify designation as a recombinant, this can be closed for now.
