### ISSUE TITLE
Sublineage of XBD with S:N188S (21 seq., Hong Kong)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1366]
Proposal for a sublineage of XBD
Earliest sequence: 25.08.22 (Hong Kong)
Countries detected: Hong Kong

Defining mutations:
S:N188S = A22125G
Subclade also carries:  S:P1143L

This sublineage of XBD is defined by S:N188S and was only detected in Hong Kong so far.

![grafik](https://user-images.githubusercontent.com/102166254/203742757-3b676c61-e484-4107-89cd-928a52295134.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2bef9_f33e40.json?c=gt-S_188

![grafik](https://user-images.githubusercontent.com/102166254/203744467-91e1d7ad-0bf2-4abd-9df5-a08b4bcf55ef.png)

EPI_ISL_14810310
EPI_ISL_15681096
EPI_ISL_15269281
EPI_ISL_15571004
EPI_ISL_15571001
EPI_ISL_15571006
EPI_ISL_15570994
EPI_ISL_15570972
EPI_ISL_15570997
EPI_ISL_15402333
EPI_ISL_15269284
EPI_ISL_15169331
EPI_ISL_15894894
EPI_ISL_15894843
EPI_ISL_15894838
EPI_ISL_15894837
EPI_ISL_15894834
EPI_ISL_15894831
EPI_ISL_15894826
EPI_ISL_15894823
EPI_ISL_15894810

**Comment by FedeGueli** [comment]
Hi already proposed in #1260 and mentioned vy @c19850727 in the original XBD issue  thx for re spotting it!

**Comment by agamedilab** [comment]
@FedeGueli many thanks for pointing that out! I will close this than...
