### ISSUE TITLE
Potential BQ.1.26 sublineage with ORF1a:S248N (136 good seqs as of 2022-12-03; Denmark, USA, Germany)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1369]
There may be a BQ.1.26 sublineage with ORF1a:S248N (G1008A; NSP2:S68N) following G17721T and T27035C first detected in New York, USA.

As of 2022-11-25, Cov-Spectrum reports 104 good-quality (120 total) BQ.1.26+ORF1a:248N sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABQ.1.26+%26+ORF1a%3AS248N&nextcladeQcOverallScoreTo=29&

This sublineage is showing significant early potential growth.

As of 2022-11-25, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![BQ 1 26+ORF1a_248N_UShER_CoV-Spectrum](https://user-images.githubusercontent.com/88959107/204071894-ff69b09b-4289-4fdb-9981-bdd8e47dff67.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/11/subtreeAuspice1_genome_CoV-Spectrum_BQ.1.26%2BORF1a_248N.json?c=gt-ORF1ab_248&label=nuc%20mutations%3AA25897G%2CG26426T

First sequence: New York, USA 2022-10-06 (GenBank, Outbreak.info, and GISAID) 

Most Recent GenBank sequence: New Jersey, USA 2022-11-05

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for this lineage is available at [Support-BQ.1.26+ORF1a_248N.zip](https://github.com/cov-lineages/pango-designation/files/10095650/Support-BQ.1.26%2BORF1a_248N.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-BQ.1.26+ORF1a_248N.txt](https://github.com/cov-lineages/pango-designation/files/10095653/gisaid-epi-isl-BQ.1.26%2BORF1a_248N.txt)

GISAID query: Lineage BQ.1 with AA Substitutions E_R61L, NS3_I169V, NSP2_S68N.

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=BQ.1&muts=E%3AR61L&muts=ORF3a%3AI169V&muts=ORF1a%3AS248N. (Outbreak.info does not yet support BQ.1.26, so this query uses BQ.1 plus the defining mutations for BQ.1.26.)

Edit: Corrected Outbreak.info link.

**Comment by alurqu** [comment]
This has now been detected in South Korea.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.26.1 with 57 newly designated sequences, and 11 updated from BQ.1.26. Defining mutation G1008A (ORF1a:S248N) (following G17721T).
