### ISSUE TITLE
Potential New Lineage with Spike P9L, C136F, Y144-, A222V, L242-, A243-, L452R, T478R, E484Q, D614G, H655Y, D950N

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#137]
**Description**
Sub-lineage of: B.1
Clade: 20C
Country: Dominican Republic, US, Spain and France
Earliest sequence: 2021-03-17
Most recent sequence: 2021-06-17

**Defining mutations in Spike:**
S: P9L
C136F
Y144-
A222V
L242-
A243-
L452R
T478R
E484Q
D614G
H655Y
D950N

**Genomes**

Sample Id and Location
DominicanRepublic/21915/2021, Dominican Republic
USA/NY-Wadsworth-21062206-01/2021, USA
France/PAC-LBM-ALPHABIO/2021, France
USA/NJ-PHEL-21-15989/2021, USA
Spain/IB-HUSE-00899/2021, Spain
Spain/IB-HUSE-00924/2021, Spain
Spain/IB-HUSE-00960/2021, Spain
Spain/IB-HUSE-01062/2021, Spain

Here are some of the sequences in neherlab/ncov-europe build:

![image](https://user-images.githubusercontent.com/86835836/124673054-c55f4200-deea-11eb-9add-2d8ae69b6f9f.png)

**Comment by chrisruis** [comment]
Thanks for submitting @c19850727. We've added this as lineage B.1.630 in [v1.2.37](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.37). There's a few more sequences within this clade in the latest UShER tree so we've designated 28 B.1.630 sequences
