### ISSUE TITLE
CH.1.1 sublineage with S:P681R in Austria and Germany (58 sequences)

### ISSUE THREAD

**Issue by BorisUitham** [cov-lineages/pango-designation#1370]
CH.1.1 sublineage with S:P681R in Austria, Germany (25 sequences)

**Description**: Sub-lineage of CH.1.1 with S:P681R
**Earliest sequence:** 2022-11-02
**Most recent sequence:** 2022-11-30 
**Countries circulating:** Austria (33 sequences), Germany (1 sequence)
**GISAID query:** Spike_P681R, Spike_G339H, Spike_R346T, Spike_L452R

34 sequences of this CH.1.1 with the S:P681R mutation that is found in Delta, which is thought to be responsible for increased fusogenicity and pathogenicity. 33 sequences are from Vorarlberg, Austria and 1 from Baden-Wurttemberg, Germany.

**Genomes**
EPI_ISL_15915257
EPI_ISL_15915215
EPI_ISL_15915238
EPI_ISL_15915220
EPI_ISL_15915143
EPI_ISL_15915165
EPI_ISL_15916122
EPI_ISL_15816173
EPI_ISL_15816096
EPI_ISL_15816063
EPI_ISL_15747319
EPI_ISL_15747592

**Evidence**
USHER is unable to build a phylogenetic tree, since in the Austrian samples only a part of the spike was sequenced.

**Nextclade:**
![YtEQ29m4](https://user-images.githubusercontent.com/119106095/204089681-87663166-67e8-4f16-8fd2-d38cedd49368.jpg)

All Austrian samples containing a P681R mutation in Austria in October and November. Overview provided by @JosetteSchoenma

**Covspectrum query:**
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AP681R&nextcladePangoLineage=CH.1.1*& 

**Growth advantage:**
Too early to tell, however parent lineage CH.1.1 has a growth advantage thought to be around the same as BQ.1.1, and there are already 25 sequences in its first month of detection.

**Sidenotes:**
Interestingly, there seems to be a BF.7.9 (EPI_ISL_15816454 on 2022-11-08) and an AY.78 (EPI_ISL_15746291 on 2022-10-31) with the S:P681R mutation found in the same time period, also in Austria. It could be possible that this lineage is a recombinant with the BF.7.9 sublineage. Once a sample has been fully sequenced, it is interesting to look for 969K and 954H mutations, which are implicated in the altered cell entry phenotype of Omicron.

Thanks to @JosetteSchoenma for helping with putting the proposal together.
Also found by @health_enjoyer on twitter on november 22nd.

**Comment by JosetteSchoenma** [comment]
Well done,  @BorisUitham . Your first proposal!
Hopefully there will be a fully sequenced sample available soon. Among other things, to see if this is a recombinant or just a mutated CH.1.1.

**Comment by FedeGueli** [comment]
congrats great catch and great 1st proposal also @ryhisner and @UlrichElling are on these sequences

**Comment by UlrichElling** [comment]
Thanks everyone! Full genome sequencing ongoing.

**Comment by thomasppeacock** [comment]
Putting a monitor label on until we have full genomes and therefore get some more complete tree placement, etc

**Comment by corneliusroemer** [comment]
> All 12 sequences are from Vorarlberg, Austria

Do you know anything more about whether the patients are related? All being from one place this doesn't reall

> with the S:P681R mutation that is found in Delta, which is thought to be responsible for increased fusogenicity, pathogenicity and transmission

I would take increased transmission claims with a big grain of salt. If this mutation was beneficial in a BA.2/4/5/75 background it would have arisen much more often than the ~100 sequences we find on GISAID.

In BA.5 it hasn't done anything at all.

<img width="2525" alt="image" src="https://user-images.githubusercontent.com/25161793/204107674-893e8014-c8de-45c5-8e53-f787641aa0ce.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BA.5*&aaMutations1=S%3A681R&nextcladePangoLineage1=BA.5*&analysisMode=CompareToBaseline&

**Comment by JosetteSchoenma** [comment]
Well, there is no metadata on GISAID, but the Sampling Strategy says 'random'.
Maybe @UlrichElling knows more?

In Vorarlberg it seems to grow, but of course the numbers are still very small. 2/186 in week 44, 4/199 in week 45 and 6/183 in week 46.

**Comment by UlrichElling** [comment]
I have no access to detailed metadata nor to cluster relationships. I can request it but do not expect a return of detailed information. As for growth I agree with Cornelius: I believe it is most likely a founder effect as the mutation has appeared early it seems in CH.1.1 and CH.1.1 itself is expanding. We have no evidence at this point that P681R would make CH.1.1 faster.

**Comment by BorisUitham** [comment]
I included the "increased transmission" on memory of a delta-era paper where this mutation is connected with increased viral replication. But in hindsight this indeed shouldn't be extrapolated to omicron and doesnt directly say something about transmission anyways, so i'll remove that part of the proposal

**Comment by Mydtlwn** [comment]
I think I can observe it for a while.

**Comment by Mydtlwn** [comment]
I think this can be observed for a while.

**Comment by Mydtlwn** [comment]
I think this can be observed for a while.

**Comment by FedeGueli** [comment]
Spike_P681R,Spike_G339H,Spike_R346T,Spike_L452R avoid to catch a CA.3 that popped up from india with 681R today

**Comment by FedeGueli** [comment]
19 sequences so 7 new ones uploaded from Austria today. @JosetteSchoenma @UlrichElling

**Comment by JosetteSchoenma** [comment]
Thanks, Fede. Just saw them. All from Vorarlberg again. And Spike only sequences.
It's now 1,1%, 2,0%, 3,4% and 2,4% from weeks 44 to 47. Based on around 200 samples in total per week.

**Comment by corneliusroemer** [comment]
@UlrichElling any progress on full genomes? Would be great to get these.

Also, could you maybe share the raw reads of the sequences in question? Would be good to see how clean they are to exclude contamination etc.

They all have an N-stretch at 22064-22222, so this could indicate an artefact.

It's suspicious that we've only seen these sequences from one Austrian state and not any neighbouring countries. I would suspect Labor Risch would have picked up on these in Liechtenstein etc, they upsample SGTP which these samples seem to be.

**Comment by UlrichElling** [comment]
Samples are with Andreas Bergthaler and sequence analysis will be provided by https://github.com/fabou-uobaf . How do you add him to this issue? Apparently there was a delay, but data should be coming soon.
I can provide you with the data I have available right now by mail, Cornelius. There is also evidence of a P681R mutation in the sewage of the region, so that is somewhat an independent evidence. Not sure if sufficient mutations are physically linked to call CH.1.1 from the amplicon though, but where else should it be from... Andreas Bergthaler or Fabian Amman needs to provide that. 
We do not observe the mutation in all CH.1.1 cases, so while I am considering the possibility of an artefact of course I do not see how it could be. The mutation is in the middle of our amplicon, the cutoff to call mutations with high confidence in the last run was 456 reads/sample (1% of median in the run), and >50% of reads. So that is hundreds of reads in each case. We had no other P681R for a long time, so contamination seems close to impossible. Moreover: The mutation appears only in Vorarlberg despite the case that we sequence from all Austria.
I agree though, we would want to see it from Liechtenstein (my second home country BTW)  or more likely the other side of the Rhine by now. I will also look into amplicon failure, I suspect primer issues in the current primer set for BA.2.75 dependents, we are currently awaiting an updated primer set.

**Comment by UlrichElling** [comment]
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/109073004/205463310-8c5127b3-cc79-4035-afba-57bfcded7e94.png">
this is the region of our amplicon 12 containing the 681 mutation in the middle.

**Comment by JosetteSchoenma** [comment]
@corneliusroemer Vorarlberg has so far uploaded 827 samples from November 2022, while Liechtenstein has only uploaded 45 from that same period.
So, even if it passed the border, they might simply not have caught or sequenced it.

**Comment by JosetteSchoenma** [comment]
Thank you very much for the full sequences, @fabou-uobaf.
Looking at the Usher tree, it is not a recombinant, but simply CH.1.1 that gained S:P681R.
![image](https://user-images.githubusercontent.com/94831035/205698216-690537be-3dea-4949-9ef5-9d9875b51ea5.png)

**Comment by corneliusroemer** [comment]
Great work @fabou-uobaf @UlrichElling - given the limited observations I'd say we wait until there's more spread in neighbouring countries before designating. Seems like S:P681R doesn't do much compared to S:P681H - one thing less to worry about :)

**Comment by JosetteSchoenma** [comment]
Thanks, Fede. Just saw them. All from Vorarlberg again. And Spike only sequences.
It's now 1,1%, 2,0%, 3,4% and 2,4% from weeks 44 to 47. Based on around 200 samples in total per week.

**Comment by JosetteSchoenma** [comment]
I just saw that I forgot to really send my comment. It was already written last week.

But really just now a sample was uploaded from Germany/Baden-Wurttemberg, sampling date 2022-11-26. EPI_ISL_16043403

**Comment by oobb45729** [comment]
H681R happens in chronic Omicron cases though. Here is a well-documented one:
![F2 large](https://user-images.githubusercontent.com/115189228/206588014-8bf09b66-b658-489b-8a64-d3b2785ace02.jpg)
https://www.medrxiv.org/content/10.1101/2022.05.25.22275533v2.full-text

**Comment by oobb45729** [comment]
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=T6001C%26S%3A346t&

**Comment by ryhisner** [comment]
It appears that five of the CH.1.1 + S:P681R from @UlrichElling's lab—including three of the five most recent samples—also have S:D839N. However, S:D839N does not, for some reason show up on Nextclade. @UlrichElling, can you confirm that these sequences really do possess S:D839N? Thanks.
EPI_ISL_15915165, EPI_ISL_15995866, EPI_ISL_16064877, EPI_ISL_16064888, EPI_ISL_16064938

**Comment by silcn** [comment]
@ryhisner I'm guessing S:D839N doesn't show up on Nextclade because S:839 is the final codon covered by the Austrian partial spike sequences. It's certainly there in the fastas, and those 5 are the only Austrian sequences with that mutation since February, so it is very likely real.

S:D839N popped up semi-regularly in Delta and BA.1 but is extremely rare in BA.2/4/5-derived lineages; perhaps it is enabled here by S:P681R.

**Comment by ryhisner** [comment]
Thanks for the insights, @silcn. I've seen S:D839N in a handful of hypermutated chronic-infection cases, including several BA.1* lineages. S:D839V was also in one of the strangest chronic cases of recent note, from Russia, with private spike mutations L452R, A475V, A484I, P499R, A653V, E780A, D839V, T1027I. 

I think it's the only sequence ever with A484I and maybe the only one with P499R (along with one related sequence, probably from the same patient). Anyway, I think this is all an indication that S:D839N could be significant in some way. S:Q836 mutations show up somewhat frequently as well, often in sequences with numerous other mutations (most likely acquired during chronic infection), another indication this area might be significant. 

And while I'm not 100% certain it's real, a recent BQ.1.10 sequence from Texas, USA, popped up with spike mutations T76I, N211del, L212I, D836del, Y837H (along with four ORF1a mutations). S2 deletions are super rare, and the vast majority of the ones I've seen are either around S:620-622 or S:640. The sequence has a perfect QC score of Nextclade and nothing really looks suspicious, so I'm inclined to think it's real. EPI_ISL_16049617
<img width="882" alt="image" src="https://user-images.githubusercontent.com/33738461/206947744-5b18bdf8-a92f-4921-874b-b1b61cb870b1.png">

**Comment by silcn** [comment]
@ryhisner agree it looks like 839 has some significance, though maybe only within the host.
For the record, those two Russian sequences do indeed appear to be the only instances of S:E484I (not really A484I because they're not Omicrons). S:P499R on the other hand appeared many times in Delta, though it seems to be incompatible with Omicron's Q498R/N501Y.

**Comment by fabou-uobaf** [comment]
Brief update on the current situation as seen in wastewater: Last week's trend continuous as so far as S:P681R does not gain dominance in single sewer sheds. But it is still circulating in Western Austria (and Liechtenstein for that matter). Last weeks data suggest circulation in 2 catchments in Vorarlberg, 1 Tyrolian and 1 from Salzburg.

Here a plot of all monitored catchments where S:P681R was detected, and the CH.1.1 signal (if detected).

![VosI-Plot_CH 1 1-S_P681R](https://user-images.githubusercontent.com/11571552/207170894-e5976f51-1da3-4954-ab31-121494a2f5ea.png)

**Comment by fabou-uobaf** [comment]
![VosI-Plot_CH 1 1-S_P681R](https://user-images.githubusercontent.com/11571552/208191631-86cd90b6-1154-46a8-9a4b-5f29e3a5161c.png)

**Comment by BorisUitham** [comment]
S:D839N in this lineage indeed seems to be growing quicker relative to without, 6 out of 9 new sequences from vorarlberg today have it.

**Comment by oobb45729** [comment]
D839 is involved in calcium binding.
[https://www.biorxiv.org/content/10.1101/2022.03.03.482731v2.full](url)
This article is about SARS-CoV-1, whose E821 is the counterpart of SARS-CoV-2's D839.

**Comment by FedeGueli** [comment]
45 sequences as today on Gisaid with : Spike_P681R,Spike_G339H,Spike_R346T,Spike_L452R.

One sequence uploaded yesterday was from Tyrol.

**Comment by BorisUitham** [comment]
CH.1.1 + P681R + D839N has grown by 7 from 11 samples to 18 samples over the last week, two of which were collected in tyrol. Only one collected sample of CH.1.1 + P681R did not have D839N, so 87.5% did have it this week versus 66.7% in the preceding week.

I just saw your comment appear as I was typing this, FedeGueli. 3 of the 45 samples are fully sequenced duplicates.

**Comment by BorisUitham** [comment]
Up to 58 sequences. 2 uploaded on 12-26 (P681R), 14 on 01-06 (P681R + D839N). d839n is now 32 sequences
