### ISSUE TITLE
BN.1.4 sublineage with ORF1ab:P1096T, 104 samples, 51 from the Netherlands, 11 countries.

### ISSUE THREAD

**Issue by JosetteSchoenma** [cov-lineages/pango-designation#1372]
**Description:** Sub-lineage of BN.1.4 with ORF1ab:P1096T
**Nucleotide mutations:** T3106C and C3551A
**Earliest sequence**: 2022-10-03 from Belgium
**Most recent sequence:** 2022-11-19 from Denmark
**Countries circulating:** The Netherlands 49, Denmark 16, Belgium 13, USA 9, Canada 2, France 2, Germany 1, USA 1. Total 93.
**GISAID query:** NSP3_P278T, Spike_K356T, Spike_F490S, Spike_R346T
**Covspectrum query:**
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=ORF1a%3AP1096T&nextcladePangoLineage=BN.1.4*&

**Evidence**
**USHER tree**: red dots are double
![image](https://user-images.githubusercontent.com/94831035/204110544-5f6651b4-e3c9-4e12-bc62-5371ad9666a6.png)
![image](https://user-images.githubusercontent.com/94831035/204110588-da0310ba-2046-4b4c-b6b7-42655df47c6f.png)

**Growth advantage:**
In the Netherlands it is getting a bigger share in BA.2.75* and it seems to grow as fast as XBB, but too early to tell, of course.
![image](https://user-images.githubusercontent.com/94831035/204110609-44f53c71-9292-4f5d-ba94-6d6c4919c245.png)

**Comment by JosetteSchoenma** [comment]
101 now. First ones for Spain and Israel.
The Israeli an one is from October. Maybe I just missed it somehow before.

**Comment by FedeGueli** [comment]
113 as today

**Comment by JosetteSchoenma** [comment]
Yes. And still awaiting a big Dutch upload, which I know at least should contain many BA.2.75*, according to the RIVM report that came out today.

**Comment by FedeGueli** [comment]
126 seqs as today latest mainly from Netherlands @JosetteSchoenma

**Comment by JosetteSchoenma** [comment]
Yes. And still awaiting a big Dutch upload, which I know at least should contain many BA.2.75*, according to the RIVM report that came out today.

**Comment by JosetteSchoenma** [comment]
136 now. Most recent 4 from Iceland.

**Comment by FedeGueli** [comment]
it is growing quite fast but also BN.1 is fast in this period so i dont know how much it comes from the mutations of this lineage or not. Still i think it is worth designating it for its rapid spread in netherlands and from there internationally

**Comment by FedeGueli** [comment]
158 seqs as today

**Comment by JosetteSchoenma** [comment]
Yes. And 15 countries now.

**Comment by corneliusroemer** [comment]
Closing this as stale
