### ISSUE TITLE
New BM.1.1.3 sublineage with S:F486P  + ORF1a:G514E , ORF1b:Y1147C circulating in Chile and Usa (28 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1374]
Here i want to propose a new lineage carrying S:F486P , mutation that seems on fast rise globally with XBF XBC XAY XBB.1.5 and CJ.1  lineages and seems able to outcompete vs S:N460K lineages [CLICK HERE](https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=S%3AN460K&aaMutations1=S%3A486P&analysisMode=CompareToBaseline&)
This time arose from BM.1.1.3 (BA.2.75.3.1.1.3) branch of BA.2.75 big " family "

Defining mutations:
BM.1.1.3 + S:F486P (T23018C) > ORF1a:G514E (G1806A) , ORF1b:Y1147C (A16907G)

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16b67_516e80.json?label=nuc%20mutations:T23018C
![Schermata 2022-11-28 alle 21 30 10](https://user-images.githubusercontent.com/87669813/204374770-c66fd262-9e98-4813-a692-818726b2298a.png)

SEQUENCES:
EPI_ISL_15792444, EPI_ISL_15792459, EPI_ISL_15849942,
EPI_ISL_15855256, EPI_ISL_15855368, EPI_ISL_15855370,
EPI_ISL_15855408, EPI_ISL_15855414, EPI_ISL_15855417-15855418,
EPI_ISL_15859358, EPI_ISL_15859367, EPI_ISL_15867133,
EPI_ISL_15867136, EPI_ISL_15889597-15889601, EPI_ISL_15890841,
EPI_ISL_15890843, EPI_ISL_15890854-15890855
from CHILE
plus EPI_ISL_15824162 from Canada

Gisaid query: NSP2_G334E,Spike_F486P,E_T11A,NSP14_V182I,Spike_N460K

cc @corneliusroemer @InfrPopGen @AngieHinrichs @thomaspeacock

**Comment by corneliusroemer** [comment]
I'm a little skeptical as it seems to be just Chile yet. Let's see if it pops up elsewhere!

**Comment by FedeGueli** [comment]
@corneliusroemer it popped up in Canada and there were also two sequences from Usa i excluded cause they look like contamination or recombination..but i agree we should wait a bit to see if more sequences will pop up

**Comment by FedeGueli** [comment]
two new legit sequences (different form the two mentioned in the comment above)  were uploaded today from USA, both from baseline surveillance from two different and far states: Texas and Illinois .
Bringing the count to 25.

cc @corneliusroemer

**Comment by FedeGueli** [comment]
28 sequences as today the last 5 uploaded to Gisaid are 2 from Texas one from Illinois one from New York and one from Rio de Janeiro.

@corneliusroemer @InfrPopGen this kind of international spread suggests to me or a rapid spread in Chile or some sort of prevalence there.

**Comment by corneliusroemer** [comment]
Designated as CV.2

**Comment by FedeGueli** [comment]
thx @corneliusroemer
