### ISSUE TITLE
BM.4.1.1 sublineage with S:F486P recently emerged in Indonesia and already exported to New Zealand, Denmark and Australia - 14 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1375]
Here i want to propose to further monitor its eventual spread a sublineage of BM.4.1.1 carrying S:F486P.
As mentioned in the issue for the chilean BM.1.1.3 + S:F486P this mutation seems on the rise globally especially in recombinant lineages but it is worth monitor also the smaller one like this especially when they were able to be exported internationally as this one did.

**Tree:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_209ac_51d500.json?label=nuc%20mutations:T14565A
![Schermata 2022-11-28 alle 21 49 16](https://user-images.githubusercontent.com/87669813/204377955-5c733176-daee-413f-9f39-781906be07c8.png)

Defining mutations
BM.4.1.1 +  > ORF1b:Q2425R (A20741G)  > T14565A > T13090C, S:F486P (T23018C) 

Sequences:
EPI_ISL_15826757, EPI_ISL_15901229, EPI_ISL_15901239,
EPI_ISL_15901257 From Indonesia

EPI_ISL_15910914 from Denmark

Edited 

Gisaid query : NSP16_Q28R,Spike_F486P,E_T11A,NSP14_V182I

**Comment by FedeGueli** [comment]
One more sequence of this came today from Australia interesting it clusters with an indonesian sequence and share with it a further RBD mutation **S:S494P**

![Schermata 2022-11-30 alle 00 40 14](https://user-images.githubusercontent.com/87669813/204672377-2f3ea709-d406-43a6-899c-a861c3384f0c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22afe_698140.json?c=userOrOld&label=id:node_7614120

@corneliusroemer @InfrPopGen @thomasppeacock

**Comment by FedeGueli** [comment]
@corneliusroemer @thomasppeacock @InfrPopGen 8 new sequences of this one uploaded today:
one from Indonesia an hospitalized 72yrs old and 7 from New Zealand  five of them defined by Orf3a:W128L and two by S:S494T.

**Comment by corneliusroemer** [comment]
This looks interesting, thanks @FedeGueli  - I'll designate based on international spread, fast growth and known mutations.
