### ISSUE TITLE
BA.5.1(.15) sublineage with S:K444N, S:N460K, S:Q677H (~160 seq, mostly Brazil)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#1376]
Proposal for a sublineage of BA.5.1 (possibly BA.5.1.15)
Earliest seq: 2022-09-28 (Chile)
Countries detected: Brazil (~120 seq, majority from Pernambuco state), smaller numbers in Chile, French Guiana, USA, Denmark, France, Netherlands, UK, Israel

Defining mutations: 
S:K444N, N460K, Q677H
nuc:C8140T, C19029T

GISAID query: NSP5_H246Y, Spike_K444N, Spike_N460K, Spike_Q677H

This lineage is growing in prevalence in Brazil, and currently dominant in the state of Pernambuco. Its five defining mutations appear to have all been picked up at once in a mini-saltation. It is on the South American branch of BA.5.1 defined by C10790T = ORF1a:H3509Y; as mentioned by @corneliusroemer in #1039 this branch ought to be designated BA.5.1.15, as the other defining mutation is probably an artefact, but this change doesn't seem to have been made. 

<img width="737" alt="Brazil_444_460_677" src="https://user-images.githubusercontent.com/42699509/204397900-020fefc9-1853-4cb9-97c3-6cada0e9fb8a.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_8bed_536b80.json?branchLabel=Spike%20mutations&c=gt-S_444,460,677&label=nuc%20mutations:C8140T,C19029T,G22894T,T22942G,G23593T](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_8bed_536b80.json?branchLabel=Spike%20mutations&c=gt-S_444,460,677&label=nuc%20mutations:C8140T,C19029T,G22894T,T22942G,G23593T)

[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A444N%2CS%3A460K%2CS%3A677H%2CORF1a%3A3509Y&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A444N%2CS%3A460K%2CS%3A677H%2CORF1a%3A3509Y&)

**Comment by InfrPopGen** [comment]
Important: This assumes the proposal in #1039 (i.e. that BA.5.1.15 is defined by C10790T only), as I decided that having two affected lineages was worse than having just one (for a time). So, leaving this open for a while, and no milestone quite yet. @corneliusroemer @AngieHinrichs 

Thanks for submitting. We've added lineage DL.1 with 147 newly designated sequences, and 0 updated designations. Defining mutations C8140T (S:K444N), C19029T (S:N460K), G22894T (S:Q677H), T22942G, G23593T (following C10790T (ORF1a:H3509Y)).

**Comment by FedeGueli** [comment]
It seems quite fast in our chart.

PS @InfrPopGen i think there us a typo here : " C8140T (S:K444N), C19029T (S:N460K), G22894T (S:Q677H), T22942G, G23593T (following C10790T (ORF1a:H3509Y))" .
it should be C8140T,C19029T , G22894T (S:K444N),S:N460K (T22942G),S:Q677H (G23593T )
