### ISSUE TITLE
Sub-lineage of BA.5.2.1 with 20 mutations (G>A bias, 20 seqs, Australia).

### ISSUE THREAD

**Issue by theosanderson** [cov-lineages/pango-designation#1377]
**Description**
**Sub-lineage of:** BA.5.2.1
**Earliest sequence:** 2022-08-17, Sydney, Australia — EPI_ISL_15081620
**Most recent sequence:** 2022-8-30, Sydney, Australia – EPI_ISL_15260723
**Countries circulating:** Australia (20)
**Number of Sequences:** 20
**GISAID/CovSpectrum Query:** G20839A, G18712A, G18589A

**Substitutions in this branch**
ORF1a:P777L, S1400L, T2087I, V2943I, M3669I, M3934I, 
ORF1b:V1708I, A1749T, V2458I, 
S: N188D,
N:T24I, P142S
Nucleotide: C2595T, T3607C, C4464T, C6525T, G9092A, G11272A, G12067A, C12784T, G14430A, C14605T, G18589A, G18712A, G20839A, A22124G, C23170T, T25735C, A26169G, C28344T, C28697T, C29098T

**UShER Tree**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3af1d_6268a0.json

**Evidence:**

This clade is mostly interesting as a potentially molnupiravir-associated event as discussed by @ryhisner in https://github.com/cov-lineages/pango-designation/issues/1348 and [elsewhere](https://github.com/cov-lineages/pango-designation/issues/1286#issuecomment-1303013648). It was identified through a systematic search for such patterns.

35% of mutations are G->A and 45% are C->T. There is a subclade with 19/20 sequences with futher G->A/C-T mutations.

Samples are from multiple distinct patients per metadata ages.

<details><summary>Genomes</summary>EPI_ISL_15081441
EPI_ISL_15081620
EPI_ISL_15260633
EPI_ISL_15081595
EPI_ISL_15188037
EPI_ISL_15081579
EPI_ISL_15081603
EPI_ISL_15081526
EPI_ISL_15081447
EPI_ISL_15081446
EPI_ISL_15081444
EPI_ISL_15081443
EPI_ISL_15260630
EPI_ISL_15260629
EPI_ISL_15260643
EPI_ISL_15260650
EPI_ISL_15260642
EPI_ISL_15260723
EPI_ISL_15260704
EPI_ISL_15081448</details>

**Comment by corneliusroemer** [comment]
I think that we wouldn't generally give a name to such an old lineage without current circulation. But naming criteria are flexible.

The outbreak was rather limited, only a week within a single location. So Molnupiravir seems to have worked in making deleterious changes (maybe) 🙃 

Would you like a name for this so you can talk about it in a paper? That could be a reason for naming I guess. If it was the biggest such cluster or among the biggest.

**Comment by theosanderson** [comment]
Yeah, this repo seems to have a dual role of facilitating discussions and for naming. I agree naming isn't particularly important here. Maybe this closed issue can exist for reference.

**Comment by corneliusroemer** [comment]
I've raised it it in the committee - the white tailed deer spill back did get a name so there is precedent for this kind of lineage naming.
