### ISSUE TITLE
FollowUp of #1245 A second DJ.1 sublineage with S:N460K  (and multiple AA substitutions) emerged in Peru and now counts 67 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1379]
Thanks to   Genomic Surveillance Group at National Institute of Health (INS-Peru) efforts lead by @Vjimenez-vasquez it was possible an early identification of a second DJ.1 sublineage carrying the (now) homoplasic S:N460K mutation.
Today Peruvian scientists from the battlefield uploaded a huge number of sequences and many of them belong to DJ. family.

So Now this second DJ.1+S:N460K (after DJ.1.1 designated in #1245 )is worth a separate proposal as agreed with @InfrPopGen and @Vjimenez-vasquez (INS- Peru) 

**_Defining mutations :_** 
 **N:G5E** (G28287A) > **Orf1a:I4127V**(A12644G) > **Orf1a:L2869F** (G8872T) > ****S:L176F**(**C22088T), C14599T  > **S:N460K** (T22942G)

Gisaid query: N_G5E,Spike_N460K,NS7b_H42Y,M_D3N,-NSP12_Y273H,SPike_K444N

**_Sequences_** = (**54**)

**_EPI_ISLs_**:
EPI_ISL_15274852, EPI_ISL_15394142, EPI_ISL_15723653-15723654,
EPI_ISL_15723867, EPI_ISL_15805958, EPI_ISL_15805962,
EPI_ISL_15907987, EPI_ISL_15934107, EPI_ISL_15934111,
EPI_ISL_15934177, EPI_ISL_15934183, EPI_ISL_15934200,
EPI_ISL_15934220-15934221, EPI_ISL_15934241, EPI_ISL_15934256-15934257,
EPI_ISL_15934259, EPI_ISL_15934261, EPI_ISL_15934279,
EPI_ISL_15934322, EPI_ISL_15934338, EPI_ISL_15934346,
EPI_ISL_15934376-15934377, EPI_ISL_15934423-15934424, EPI_ISL_15934718,
EPI_ISL_15943114-15943120, EPI_ISL_15943130, EPI_ISL_15943154-15943156,
EPI_ISL_15943161, EPI_ISL_15943168, EPI_ISL_15943174,
EPI_ISL_15943186, EPI_ISL_15943200, EPI_ISL_15943209,
EPI_ISL_15943214-15943215, EPI_ISL_15943231-15943235, EPI_ISL_15944233,

**Country**: Peru, Japan

**_Usher Tree_**:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3404c_6916e0.json?c=country&label=id:node_6582095
![Schermata 2022-11-30 alle 00 21 57](https://user-images.githubusercontent.com/87669813/204670109-70e2728c-89ae-4032-bb24-ed4357ff7ce9.png)

**Comment by Vjimenez-vasquez** [comment]
Hi @FedeGueli,

We have been little worried about the designation of DJ.1 because there are actually two lineages associated to the COVID-19 rise cases in peruvian amazon (first) and Lima (later) since October. But we checked in our phylogenetic reconstructions that DJ.1 is not monophyletic whereas non-designated DJ.1.1 and DJ.1.2 are reciprocally monophyletic and thus they should be epidemiological important for us. We think COVID-19 rise is not only due to DJ.1. Please I would appreciate you guys to check the last genomes we (INS-Peru) are recently uploading  because we attribute the COVID-19 rise to XBB.2 and BQ.1.1 lineages as well. 

In a non-published phylogenetic tree conducted on XBB.2 we identified a single branch from Peru. I will upload this mentioned tree in a few days. 

Many thanks in advance,

**Comment by FedeGueli** [comment]
65 sequences as today @corneliusroemer @InfrPopGen i think it is better to designate all the 444n +460k from Peruì they are all growing

**Comment by Vjimenez-vasquez** [comment]
> 65 sequences as today @corneliusroemer @InfrPopGen i think it is better to designate all the 444n +460k from Peruì they are all growing

@FedeGueli, we agree !

**Comment by FedeGueli** [comment]
67 sequences as today

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage DJ.1.2 with 46 newly designated sequences, and 0 updated. Defining mutation T22942G (S:N460K) (following C14599T (S:L176F), nt:C22088T).

**Comment by FedeGueli** [comment]
Thx @InfrPopGen !

**Comment by Vjimenez-vasquez** [comment]
Thanks @InfrPopGen and @FedeGueli !!

**Comment by Vjimenez-vasquez** [comment]
> Thanks @InfrPopGen and @FedeGueli for considering the relevance of DJ.1.2!! Hello @AngieHinrichs, in order of a rapid identification of DJ.1, DJ.1.1 and DJ.1.2 (relevant for peruvian epidemiology), we appreciate the inclution of these lineages in pangolin algorithm.

Hi @corneliusroemer @AngieHinrichs @InfrPopGen. I noticed that DJ.1.2 and DJ.1.3 genomes cannot be identified by the lasta Pangolin version 4.2. Please, I'd appreciate the update.

Bests,

**Comment by AngieHinrichs** [comment]
Hi @Vjimenez-vasquez - the latest [pangolin-data release](https://github.com/cov-lineages/pangolin-data/releases) is v1.17.  Áine and I are working on the v1.18 update which will include DJ.1.2 and DJ.1.3 - hopefully it will be available some time this week.  In the meantime you can upload sequences to the UShER web interface (https://usher.bio/, thanks @corneliusroemer for the domain name) to see where they are placed in the global tree.  Alternatively, if you want to preview the v1.18 tree that hasn't been released yet, you can try this:
1. download https://raw.githubusercontent.com/cov-lineages/pangolin-data/prerelease_v1.18/pangolin_data/data/lineageTree.pb
2. run pangolin with `--usher-tree` and the path to the downloaded lineageTree.pb:
```
pangolin --usher-tree lineageTree.pb mySequences.fasta
```
If you try that and encounter any problems, please let me know.

**Comment by Vjimenez-vasquez** [comment]
> Hi @Vjimenez-vasquez - the latest [pangolin-data release](https://github.com/cov-lineages/pangolin-data/releases) is v1.17. Áine and I are working on the v1.18 update which will include DJ.1.2 and DJ.1.3 - hopefully it will be available some time this week. In the meantime you can upload sequences to the UShER web interface (https://usher.bio/, thanks @corneliusroemer for the domain name) to see where they are placed in the global tree. Alternatively, if you want to preview the v1.18 tree that hasn't been released yet, you can try this:
> 
> 1. download https://raw.githubusercontent.com/cov-lineages/pangolin-data/prerelease_v1.18/pangolin_data/data/lineageTree.pb
> 2. run pangolin with `--usher-tree` and the path to the downloaded lineageTree.pb:
> 
> ```
> pangolin --usher-tree lineageTree.pb mySequences.fasta
> ```
> 
> If you try that and encounter any problems, please let me know.

Thanks @AngieHinrichs !!!

**Comment by ryhisner** [comment]
A DJ.1.2 sequence from December 1, 2022, with S:Q493E was just uploaded today from Peru: EPI_ISL_17021529

There have also been four DJ.1.2 sequences from Japan with S:N481S, the most recent of which was collected on February 2 and has five private nucleotide mutations. EPI_ISL_15907987, EPI_ISL_16229490, EPI_ISL_16494255, EPI_ISL_16949061

**Comment by FedeGueli** [comment]
At the time of the proposal i didnt notice that N:G5E corresponds to Orf9b:D2N.

thx @aviczhl2 for noticing it in [#316](https://github.com/sars-cov-2-variants/lineage-proposals/issues/316)
