### ISSUE TITLE
Pango Lineage Request for Lineage Associated with Tanzania Travellers, Evidence of Presence in Sweden and UK.

### ISSUE THREAD

**Issue by nfellaby** [cov-lineages/pango-designation#138]
New lineage proposal

by Nicholas Ellaby
**Description**
Lineage that is associated with travellers from Tanzania, sampled and sequenced in Angola ([ref](https://www.medrxiv.org/content/10.1101/2021.03.30.21254323v1)). Additional samples have been detected in Sweden and England.
**Sub-lineage of:**  A
**Earliest sequence:** 2021-02-13
**Most recent sequence:** 2021-05-15 
**Countries circulating:** 3/4 (Sequenced in Angola as travellers, but no evidence for further circulation). 

**Genomes:** EPI_ISL_1347940, EPI_ISL_1347941, EPI_ISL_1347942, EPI_ISL_2746031, and EPI_ISL_2419105.

[20210708_Tanzania_Pango_Lineage_Request_Summary.csv](https://github.com/cov-lineages/pango-designation/files/6784369/20210708_Tanzania_Pango_Lineage_Request_Summary.csv)

**Evidence:**

![image](https://user-images.githubusercontent.com/9819369/124920761-954d9700-dfef-11eb-9f12-9f3fbe2daf53.png)
![image](https://user-images.githubusercontent.com/9819369/124920783-9b437800-dfef-11eb-8a64-02e01e712a4d.png)

**Proposed lineage name:** ?

**Comment by chrisruis** [comment]
Thanks @nfellaby for submitting. We've added this as lineage A.30 in [v1.2.36](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.36)
