### ISSUE TITLE
BF.31 sublineage with S:K187T, S255F, H519R, D574V, I651V, Q675H, D1084E (3 seq, Chile)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#1380]
Proposal for a sublineage of BF.31
Earliest seq: 2022-10-31
Countries detected: Chile (3 seq)

Defining mutations on top of BF.31
C28744T then T21820C then C24382G, C29686T and then a saltation:
S:K187T, S255F, H519R, D574V, I651V, Q675H, D1084E
ORF1a:P3504L
nuc:T10600C, C11308T

GISAID query: Spike_H519R, Spike_I651V, Spike_D1084E (or pretty much any combination of the spike mutations)

Proposing this very early because it looks so weird. 7 spike mutations but only one in the RBD, which is the very rare S:H519R (38 sequences worldwide in 2022). S:K187T is also pretty rare (97 seq worldwide in 2022) and S:I651V and S:1084E aren't exactly common either. So far this lineage has only been found in two low-population regions of northern Chile (Arica y Parinacota and Tarapaca) which have a total of 48 sequences with collection date since the first detection on 31 October.

Given the lack of RBD mutations it's unlikely this goes anywhere but still worth keeping an eye on it.

<img width="725" alt="Chile_BF31_187etc" src="https://user-images.githubusercontent.com/42699509/204674409-70fba401-471d-404b-a5ca-09135512839e.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_39839_694e60.json?branchLabel=Spike%20mutations&c=gt-S_187&label=id:node_6948827](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_39839_694e60.json?branchLabel=Spike%20mutations&c=gt-S_187&label=id:node_6948827)

[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=%5B4-of%3A+S%3AK187T%2C+S%3AS255F%2C+S%3AH519R%2C+S%3AD574V%2C+S%3AI651V%2C+S%3AQ675H%2C+S%3AD1084E%5D&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=%5B4-of%3A+S%3AK187T%2C+S%3AS255F%2C+S%3AH519R%2C+S%3AD574V%2C+S%3AI651V%2C+S%3AQ675H%2C+S%3AD1084E%5D&)

Samples:
EPI_ISL_15855314
EPI_ISL_15929741
EPI_ISL_15929749

**Comment by oobb45729** [comment]
K187T would create a new N-glycan site at N185.
H519R is also interesting. H519 is known to play a crucial role interacting with the N234 glycan in the RBD "up" position.
For most other SARS-Cov-like strains, N is at this position, but SARS-Cov-2 has H here. Also, We've seen H519Q and H519N in some wild wastewater samples.

**Comment by silcn** [comment]
Closing as this hasn't turned up again

**Comment by ryhisner** [comment]
It just turned up again in two sequences from Chile uploaded today. Collection dates December 6 and 7. EPI_ISL_16640202, EPI_ISL_16640203
Even more interesting is that a sequence turned up in Peru, collection date December 12. EPI_ISL_16505024

**Comment by silcn** [comment]
@ryhisner well spotted. The two new Chile sequences are both from Arica y Parinacota which borders Peru. The Peru sequence is from Tacna which is very close to the border with Chile, so this is still confined to a small geographical region and as such I'm not reopening this issue (yet).
