### ISSUE TITLE
BA.5.1 sublineage with S:P1162S and Orf1a:P626L and SPike147-148del  circulating in Denmark (706 sequences) 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1382]
Gisaid Query : Spike_K147del, Spike_N148del, NSP2_P446L finds 317 sequences mostly in Denmark.
I noticed this sublineage circulating massively only in Denmark with a deletion in S:147-148.

I am unsure this is real so i put here to be analyzed by @corneliusroemer @AngieHinrichs @thomaspeacock @InfrPopGen 

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_412aa_77de60.json?c=gt-ORF7b_1&label=id:node_6566938
<img width="1153" alt="Schermata 2022-11-30 alle 17 13 27" src="https://user-images.githubusercontent.com/87669813/204850248-3396854f-2864-423c-970d-3607478d7598.png">

Defining mutations: BA.5.1 + S:P1162S + Orf1a:P626L then C15720T + S:K147del + S:N148Del then Orf7b:M1L

Sequences :
[contributors.csv](https://github.com/cov-lineages/pango-designation/files/10125028/contributors.csv)

**Comment by AngieHinrichs** [comment]
Yeah, something weird is going on with those sequences but I'm not sure what.  There are inconsistent combinations not only with ORF7b:1 / A27756T, but also with ORF1ab: R2875H / G8889A:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-1382.json?branchLabel=nuc%20mutations&c=gt-nuc_8889,27756&label=id:node_6566941

-- although it looks like the reversion on 27438 explains the multiple appearances of G8889A.  I don't know what to make of C14340T vs. A27756T.

**Comment by FedeGueli** [comment]
720 seqs with Spike_K147del, Spike_N148del, NSP2_P446L

**Comment by Mydtlwn** [comment]
#1458

**Comment by FedeGueli** [comment]
Now in #1458
