### ISSUE TITLE
Sublineage of BA.5.2 (ORF1b:T1050N) with S:K444Q & ORF7a:A55V (92 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1383]
### **Description**
**Sub-lineage of:** BA.5.2 (ORF1b:T1050N)
**Earliest sequence:** 2022-9-17, USA, Minnesota — EPI_ISL_15227102
**Most recent sequence:** 2022-11-22, New Zealand — EPI_ISL_15956989
**Countries circulating:** New Zealand (68), Australia (17), USA (2), South Korea (1), Thailand (1)
**Number of Sequences:** 89
**GISAID Query:** Spike_K444Q, NS7a_A55V
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2* & ORF7a:A55V & S:K444Q
**Substitutions on top of BA.5.2 (ORF1b:T1050N):**
**Spike:** K444Q
**ORF7a:** A55V
**Nucleotide:** A8197G, T19896C, C21595T, A22892C, C25710T, C27557T
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.5.2%20(T1050N)%20%2B%20K444Q%20%2B%20ORF7aA55V%20-%20subtreeAuspice1_genome_a48d_770360.json
 
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/33738461/204919676-1018002b-1405-47e4-a351-492cc647dfdb.png">

**Evidence**
Of the 89 sequences in this lineage, 68 were uploaded today, all from New Zealand. S:444 is probably the most prominent antibody escape mutation in the current global context. I’ve previously described (in issues #1110 and #1272) how S:K444Q stands out on the Bloom Lab RBD Heat Map as having the most favorable combination of ACE2 affinity and RBD expression of any of the 19 possible AA substitutions on a BA.2 background.

![image](https://user-images.githubusercontent.com/33738461/204919863-1c0fa11d-7eb5-4024-ae89-83f296b4c016.png)

S:K444Q also appears to be the second-best mutation for evading neutralizing antibodies from breakthrough-infection convalescent sera. 

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/33738461/204920927-ff2afb9d-71e3-4ca5-80d7-f8ab636c3f73.png">
 
 
This hasn’t, however, translated into real-world success in terms of the prevalence of this mutation. S:R444Q has occurred in a number of BA.5 lineages, but all have either died out or have shrunk to insignificant levels. This lineage appears to be an exception, though its growth seems primarily confined to New Zealand and Australia.
 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15227102, EPI_ISL_15399291, EPI_ISL_15416413, EPI_ISL_15732157, EPI_ISL_15736397, EPI_ISL_15784105, EPI_ISL_15797328, EPI_ISL_15797567, EPI_ISL_15797771, EPI_ISL_15797799, EPI_ISL_15797897, EPI_ISL_15797930, EPI_ISL_15820571, EPI_ISL_15832186, EPI_ISL_15832312,
EPI_ISL_15832602, EPI_ISL_15832620, EPI_ISL_15848882, EPI_ISL_15870943, EPI_ISL_15917287, EPI_ISL_15941947, EPI_ISL_15955562, EPI_ISL_15955659, EPI_ISL_15955875, EPI_ISL_15955900, EPI_ISL_15956016, EPI_ISL_15956060, EPI_ISL_15956289, EPI_ISL_15956335, EPI_ISL_15956349,
EPI_ISL_15956371, EPI_ISL_15956403, EPI_ISL_15956438, EPI_ISL_15956444, EPI_ISL_15956445, EPI_ISL_15956483, EPI_ISL_15956484, EPI_ISL_15956552, EPI_ISL_15956567, EPI_ISL_15956646, EPI_ISL_15956665, EPI_ISL_15956699, EPI_ISL_15956731, EPI_ISL_15956759, EPI_ISL_15956792, EPI_ISL_15956872, EPI_ISL_15956915, EPI_ISL_15956968, EPI_ISL_15956971, EPI_ISL_15956978, EPI_ISL_15956986, EPI_ISL_15956989, EPI_ISL_15957065, EPI_ISL_15957069, EPI_ISL_15957088, EPI_ISL_15957090, EPI_ISL_15957097, EPI_ISL_15957208, EPI_ISL_15957449, EPI_ISL_15957456, EPI_ISL_15957490, EPI_ISL_15957512, EPI_ISL_15957710, EPI_ISL_15957783, EPI_ISL_15957806, EPI_ISL_15957903, EPI_ISL_15958112, EPI_ISL_15958122, EPI_ISL_15958131, EPI_ISL_15958151, EPI_ISL_15958176, EPI_ISL_15958217, EPI_ISL_15958246, EPI_ISL_15958254, EPI_ISL_15958264, EPI_ISL_15958290, EPI_ISL_15958298, EPI_ISL_15958329, EPI_ISL_15958334, EPI_ISL_15958335, EPI_ISL_15958370, EPI_ISL_15958382, EPI_ISL_15958450, EPI_ISL_15958541, EPI_ISL_15958625, EPI_ISL_15958689, EPI_ISL_15958786, EPI_ISL_15958824
</details>

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.45 with 19 newly designated sequences, and 0 updated designations. Defining mutations C21595T (S:K444Q), A22892C (following C25710T).

**Comment by icestorm972** [comment]
FYI
As I've seen some S:K444Q rising in my Germany RKI DESH data analysis tonight
![S-00444](https://user-images.githubusercontent.com/20755156/205508887-0591b97d-53d5-4fb9-bf77-40d7574f6e0d.png)
I took a closer look:

There are now 4 (representative) samples in total
* 1x BA.5.2.45  (BA.2 + S:K444Q + ORF7a:A55V)
  * 2022-11-17: IMS-10122-CVDP-BA1B523F-9940-494B-BE3B-57CFED6E2EF5
* 3x undesignated https://github.com/cov-lineages/pango-designation/issues/1272 (BA.5.1.5 + S:K444Q + S:V1264L):
  * 2022-11-07: IMS-10013-CVDP-C7EB07C4-5508-4D4B-A4B8-49B5E7D16F3C
  * 2022-11-15: IMS-10116-CVDP-58564FA6-9DBB-42F0-8E12-4AFA00FA812C
  * 2022-11-21: IMS-10116-CVDP-77FDC025-BDFA-4632-8DE5-6B10B5E752CA

CC @corneliusroemer
