### ISSUE TITLE
Sublineage of BQ.1.1 with S:K182E, S:Q218H, S:P251L, S:P1162L (104 seq, Jan 25)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1385]
**Description**
**Sub-lineage of:** BQ.1.1
**Earliest sequence:** 2022-9-15, Malaysia, EPI_ISL_15942617
**Most recent sequence:** 2022-11-15, Indonesia — EPI_ISL_15966070
**Countries circulating:** Indonesia (8), Malaysia (1)
**Number of Sequences:** 9
**GISAID Query:** Spike_K182E, Spike_Q218H, Spike_P1162L
**CovSpectrum Query:** Nextcladepangolineage:BQ.1* & S:K182E & S:Q218H
**Substitutions on top of BQ.1.1.:**
**Spike:** K182E, Q218H, P251L, P1162L (and A829S for 4/9 sequences)
**Nucleotide:** T19293C, A22106G, G22216T, C22314T, T23716C, C25047T, A28834G
 
 
**USHER Tree**
The bottom branch here appears to lack S:P251L but that is almost certainly an artifact. All four sequences lack coverage in that area. Also, the long branch is 100% artifactual, the seven “reversions” obviously being due to lack of sequencing coverage in the RBM. Only the ORF1a:P1947S (C4754T) mutation on that branch is real.
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1.1%20%2B%20K182E%2C%20Q218H%2C%20P251L%2C%20P1162L%20-%20subtreeAuspice1_genome_26c49_8934f0.json
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/33738461/205045980-aa1e4fff-21a1-4c8e-8143-49cdf103a645.png"> 

**Evidence**
The first sequence in this lineage is the only one from Malaysia and was collected on September 15, though it was only uploaded November 29. The other eight sequences, all from Indonesia, were collected nearly two months later—one on Nov 2 and the rest between Nov 11-15. There are many countries in this region with little to no sequencing, so it seems likely this lineage has been circulating in significant numbers somewhere in SE Asia.
 
There is really not much diversity in this lineage considering the two-month time difference between the Malaysian sequence and the others. As stated above, the long branch on the tree is definitely an artifact.

Notably, four of the more recent sequences (collection dates Nov 2, 11, 11, 15) also have S:A829S. It's possible that A829S  is also present in the other four Indonesian sequences but is not indicated due to the relatively poor quality of those sequences.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15754441, EPI_ISL_15826723, EPI_ISL_15901232, EPI_ISL_15901237, EPI_ISL_15901277, EPI_ISL_15901279, EPI_ISL_15942617, EPI_ISL_15966062, EPI_ISL_15966070, </details>

**Comment by ryhisner** [comment]
The first sequence from Singapore showed up today—a local case collected on November 26. It does not have S:A892S. Brings the current total number of sequences to 10.
EPI_ISL_16016839

**Comment by ryhisner** [comment]
Two more from Indonesia today. Both lacking coverage at S:251, but every sequences that has had coverage there has had S:P251L, so these presumably do as well. Total sequences now 12. EPI_ISL_16027258, EPI_ISL_16027287

**Comment by ryhisner** [comment]
One sequence from Iceland now, collection date December 5. It has S:A892S. EPI_ISL_16053824

**Comment by corneliusroemer** [comment]
Interesting stuff, let's watch a bit more to see where to delineate

**Comment by ryhisner** [comment]
First sequence from Germany came in yesterday, non-A892S branch. EPI_ISL_16218926

**Comment by ryhisner** [comment]
Six sequences uploaded from Singapore today bring the total number of sequences to 28. All six have S:A829S. Collection dates Dec 16-18.  

Oddly, two have S:T444M. We've seen S:T444M occasionally in various BQ* branches. I think it's probably slightly deleterious, but it's a C-->T nuc mutation, which I think accounts for it happening every now and then. Probably APOBEC'd.

**Comment by ryhisner** [comment]
Eight new sequences uploaded from this lineage so far today, including the first sequences from Thailand (2) and Japan (1). This brings the total to 36 sequences. The four most recently collected sequences uploaded today are from Singapore, and they all have S:A829S. The other four do not have S:A829S.

**Comment by ryhisner** [comment]
The first sequence from North America was uploaded today from Canada, as was the second sequence from Germany. The Canadian sequence, along with all the others that appear to lack S:P251L on the Usher tree, lacks coverage in that region of spike, so I think it's safe to say that all 38 sequences do in fact possess S:P251L. The "long" branch that's cut off in the picture below is full of false "reversions." If those two sequencing artifacts are taken into account, the diversity in this lineage is much less than what it appears to be if you just look at the tree.
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/33738461/210025154-0b88e22e-2b3e-48d2-be27-4c15821791a3.png">

**Comment by ryhisner** [comment]
Four new sequences uploaded today—including the first two from England and the first from the USA (Texas)—bring the total to 43 sequences.

**Comment by ryhisner** [comment]
One more sequence from the USA (Texas) and three more from Canada today, one of which has S:Y144del, a first for this lineage. Total 47 sequences.

**Comment by ryhisner** [comment]
12 new sequences of this lineage today: six from Canada (Ontario) and six from England. This brings the total to 68 sequences, and increase of 21 in the past four days.

**Comment by ryhisner** [comment]
Now up to 87 sequences. Six from England and one from Scotland uploaded so far today. There's a branch in Northern Ireland with S:D111N as well.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.1.39 with 86 newly designated sequences, and 0 updated. Defining mutations A22106G (S:K182E), G22216T (S:Q218H) (following T19293C, T23716C, A28834G). There was no clear extra growth advantage at this time with S:P251L or S:A829S, and the chosen node also coincides with a shift from mainly western European to a more cosmopolitan detection.

**Comment by jinyu-ncbi** [comment]
BQ.1.1.28, BQ.1.1.38, BQ.1.1.39 all have S:P251L. It seems a lineage should be designated to the one with S:P251L, which has sublineages BQ.1.1.28, BQ.1.1.38 and BQ.1.1.39.

**Comment by FedeGueli** [comment]
> BQ.1.1.28, BQ.1.1.38, BQ.1.1.39 all have S:P251L. It seems a lineage should be designated to the one with S:P251L, which has sublineages BQ.1.1.28, BQ.1.1.38 and BQ.1.1.39.

Did you check they are monophyletic stemming out from th same S:251L politomy or instead it is just homoplasy (that i think is likely)?

**Comment by jinyu-ncbi** [comment]
Looks to me S:P251L appeared before other mutations:

S:P251L (C22314T)
    -> C18828T, C16393T -> C6701T (BQ.1.1.28)
    -> A24129G, T7633C, A19703G, C19269T, C23664T (BQ.1.1.38)
    -> T19293C, A22106G, G22216T, T23716C, C25047T, A28834G (BQ.1.1.39)
    -> T18383C, T358C (not designated)

It is less likely other mutations appeared first, and then a single mutation C22314T was added to all these lineages.

**Comment by AngieHinrichs** [comment]
The branch with BQ.1.1 > C22314T has 393 sequences.  Scanning by eye I see dates from 2022-09-29 to 2023-01-16.  BQ.1.1.38 (261 sequences) is on that branch: C22314T > T7633C > A24129G.

The branch to BQ.1.1.28 starts with BQ.1.1 > C18828T -- there are about 1,000 sequences with just C18828T with dates from  2022-09-14 (USA/CA-CDC-STM-UCMS9EZJ6/2022 which is a couple mutations after C18828T).  Then BQ.1.1 > C18828T > C16393T has only 13 sequences (including Ghana and Chile 2022-10-07) so not as much data there to guess the real date range.  Then BQ.1.1.28 (C18828T > C16393T > C22314T) has 752 sequences; the earliest I see is 2022-09-21 (Israel/ICH-741187816/2022) although next after that is 2022-09-23 from Ghana (Ghana/NMIMR-CT-22-2226/2022).  So based on the number of sequences with BQ.1.1 > C18828T first, and the progression of dates, I think that order of mutations is plausible.

BQ.1.1.39 is BQ.1.1 > C25047T > T19293C,T23716C,A28834G > A22106G,G22216T.  There are ~211 non-BQ.1.1.39 sequences on BQ.1.1 > C25047T, earliest England/PLYM-3258AEE8/2022|2022-09-30 (with a couple of other mutations).  BQ.1.1.39 dates start at Malaysia/IMR_OS7240/2022|2022-09-15.  To me that indicates unsampled spread of C25047T before that date.  From that point there were ~80 sequences from SE Asia, Canada and Europe that had BQ.1.1, C25047T, T19293C,T23716C,A28834G, A22106G, and G22216T -- but not C22314T.  BQ.1.1.39 has a branch of 25 sequences that has all those mutations, plus C11020T, G18445A, C28948T.  Then finally, there is a branch of 23 of the 25 sequences that also have C22314T.  Those are all in the US and Canada and have dates from 2022-12-12 onward.  It sure seems to me like C22314T happened after all of those BQ.1.1.39 mutations.

I was just reminded that it's Friday night so I'll leave it at that -- but yeah, like @FedeGueli said, homoplasy seems likely.

**Comment by jinyu-ncbi** [comment]
Thank you, @AngieHinrichs. It seems the sequence records we see are slightly different. Anyway, it is possible that C22314T is homoplasy that appeared independently in BQ.1.1.28, BQ.1.1.38, BQ.1.1.39. If C18828T showed up earlier than other mutations (including C22314T) in BQ.1.1, then the C18828T branch (we have 901 sequences) have at least the following four sublineages:

1.	C22314T (S:P251L), C16393T (helicase:P53S) > C6701T (nsp3:L1328F): 408 sequences.
2.	C28138T (ORF8:S82F), C27944T, G17679T, C10228T, C1377A, (nsp2:P191Q) > G20931T: 156 sequences.
3.	T22119C (S:F186S), G28904A (N:211T), G4255A, C1627T, C21648T (S:T29I): 408 sequences.
4.	A1202T (nsp2:N133Y), C17436T > C5497T: 78 sequences.

I don’t know if lineages have been added or proposed for them.
