### ISSUE TITLE
Sublineage of CM.5 (BA.2.3.20 + C10802T) with S:G485D (45 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1386]
### **Description**
**Sub-lineage of:** CM.5 (BA.2.3.20 + C10802T)
**Earliest sequence:** 2022-10-14, USA, IL — EPI_ISL_15545729
**Most recent sequence:** 2022-11-18, Australia, Queensland — EPI_ISL_15967816, EPI_ISL_15967817, EPI_ISL_15967818
**Countries circulating:**
**Number of Sequences:** USA (25—23 in California), Australia (4), Netherlands (1),
**GISAID Query:** Spike_E484R, Spike_G485D  +  Nuc Search:C10802T
**CovSpectrum Query:** Nextcladepangolineage:
**Substitutions on top of CM.5:**
**Spike:** G485D
**Nucleotide:** G23016A
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/CM.5%20%2B%20G485D%20-%20subtreeAuspice1_genome_1e341_8b40e0.json

![image](https://user-images.githubusercontent.com/33738461/205101966-b3779636-b6c8-4fac-a3f3-9a682afde069.png)
 
 
**Evidence**
S:G485D is the defining mutation of the CM.3 branch of BA.2.3.20, first appearing in Australia in early September 2022. Recently, however, S:G485D has appeared in the CM.5 lineage of BA.2.3.20, defined by the synonymous mutation C10802T. The majority of CM.5 sequences with S:G485D have been from California, USA, (23/30), but it has also been detected in the US Midwest (Illinois) and Deep South (Florida). There have also been four sequences detected in Australia, so this lineage is already geographically widespread.
 
S:G485 mutations have been rare throughout the pandemic. If S:G485D were advantageous or even neutral in previous lineages, it surely would have occurred much more often than it has. But is S:G485D advantageous for BA.2.3.20? The existence of S:G485D in CM.3 could be attributed to happenstance; perhaps an early random mutation and large outbreak seeded S:G485D so that it occurs in a significant fraction of BA.2.3.20 sequences despite being neutral or slightly deleterious. I think this explanation fits the S:N17S mutation of CM.1, which was found in a decent proportion of early BA.2.3.20 sequences but has been fading ever since.
 
However, the independent evolution of S:G485D in a second BA.2.3.20 lineage seems to provide very strong evidence that this mutation is beneficial in a BA.2.3.20 context, particularly since no previous designated lineage has had S:G485D—or any S:G485 mutation, for that matter. The apparent growth advantage conferred by S:G485D when compared to all BA.2.3.20* according to CovSpectrum, as shown below, further solidifies the case. https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ABA.2.3.20*&variantQuery1=nextcladePangoLineage%3ABA.2.3.20*+%26+S%3AG485D&analysisMode=CompareToBaseline&
![image](https://user-images.githubusercontent.com/33738461/205102221-8a4cd728-d365-45e8-982d-671649f37d40.png)
 
S:G485D differentiates BA.2.3.20 from any previous SARS-CoV-2 lineage, but this isn’t the only indication that the unique RBM of BA.2.3.20 provides a significantly different RBD mutational background than that found in other lineages. There have been several BA.2.3.20 sequences with RBD mutations that have either never been seen before or have only been present in a few previous sequences. Notable examples include R444G, R444W, R444S, and ∆Y449. The proportion of BA.2.3.20 sequences with S:P499 mutations (currently 17 out of about 3300 total BA.2.3.20 sequences) also stands out.
 
Given the number of NTD and RBD mutations possessed by BA.2.3.20 but not by any predominant XBB*, BN*, BQ*, or BA.5* lineages, and the apparent ability of BA.2.3.20 to tolerate mutations that appear to be unviable in other lineages, it is perhaps a good candidate to grow in prevalence if XBB, BQ, or BN lineages ever falter (through growing population immunity, for example).
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15545729, EPI_ISL_15638637, EPI_ISL_15706160, EPI_ISL_15707433, EPI_ISL_15765686, EPI_ISL_15771300, EPI_ISL_15771732, EPI_ISL_15772294, EPI_ISL_15778981, EPI_ISL_15804186, EPI_ISL_15804955, EPI_ISL_15818787, EPI_ISL_15829949, EPI_ISL_15841224, EPI_ISL_15842660, EPI_ISL_15842757, EPI_ISL_15842985, EPI_ISL_15849564, EPI_ISL_15881087, EPI_ISL_15881089, EPI_ISL_15944200, EPI_ISL_15944888, EPI_ISL_15944930, EPI_ISL_15944954, EPI_ISL_15944957, EPI_ISL_15945275, EPI_ISL_15952689, EPI_ISL_15967816, EPI_ISL_15967817, EPI_ISL_15967818
</details>

**Comment by cvejris** [comment]
There´s got to be a connection between D485 and neighboring R484, the latter enabling the existence of the former. R484 is famously present only in BA.2.3.20, making sense of the absence of D485 elsewhere. Amazing catch as always, @ryhisner

**Comment by ryhisner** [comment]
In another clearly independent acquisition of S:G485D, two XBJ sequences uploaded from England today (collection dates Nov 27) have S:G485D. (XBJ is a BA.2.3.20/BA.5 recombinant whose spike is entirely BA.2.3.20). 
EPI_ISL_15998947, EPI_ISL_15999131

**Comment by silcn** [comment]
After multiple appearances of S:G485D in BA.2.3.20, today three sequences from the Philippines popped up with S:G485R, along with V483A and R484K. They were all sampled in mid-October, so due to lack of international spread I don't think this warrants a proposal yet, but it's still intriguing. G485R was incompatible with all previous Omicrons (only 2 genuine-looking sequences!) but occasionally appeared in the pre-Omicron era. These also seem to be the first Omicrons with the once-common S:484K, which required two mutations from 484A but only one from 484R.

<img width="425" alt="Philippines_483_484_485_nextclade" src="https://user-images.githubusercontent.com/42699509/206061869-97e28682-6c41-45bc-acd2-9b335f6d95e6.png">
<img width="674" alt="Philippines_483_484_485" src="https://user-images.githubusercontent.com/42699509/206061880-7e2d4e29-9c6f-42d1-9ee8-0e700c146052.png">

**Comment by silcn** [comment]
Yes, also noted that 446S+478I+1128I branch; it's turned up a couple of times outside the Philippines too, though long enough ago that I'd expect to have seen more if it had a growth advantage.

**Comment by corneliusroemer** [comment]
Wherever you go on the BA.2.3.20 tree, G485D pops up, really seems to be beneficial, hard to explain otherwise.
