### ISSUE TITLE
Proposal of new BA.5.1.12 Sublineage with ORF1ab:T4418I, S:V445A and ORF3a:I35T (10 seq, 6 with ORF1ab:L5904V) from Peru, Mexico

### ISSUE THREAD

**Issue by AliNunz** [cov-lineages/pango-designation#1387]
**Description:**
Potential BA. 5.1.12 sub-lineage containing  ORF1ab:T4418I, S:V445A,  ORF3a:I35T and ORF1ab:L5904V mutations proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS-Peru) 

**Sub-linage of:** BA.5.1.12

**Evidence:**
![BA 5 1 12](https://user-images.githubusercontent.com/115187682/205115730-4611539f-22cc-4551-ab89-dfdf6ce82543.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_b212_8e2ab0.json?c=Nextstrain_clade_usher&f_userOrOld=uploaded%20sample&label=id:node_6520048

**Earliest sequence:** 2022-10-03
hCoV-19/Peru/ICA-INS-30722/2022

**Most recent sequence:** 2022-11-11
hCoV-19/Peru/LIM-INS-32441/2022

**Countries circulating**
Peru (9), Mexico (1)

**Genomes:**
EPI_ISL_15621911, EPI_ISL_15621912, EPI_ISL_15621913, EPI_ISL_15805960, EPI_ISL_15671308, EPI_ISL_15934330, EPI_ISL_15934397, EPI_ISL_15943204, EPI_ISL_15934250, EPI_ISL_15934252

**Comment by ryhisner** [comment]
ORF1b:T17I is in BA.5.2.29 and has independently evolved in a number of different Omicron lineages, and it seems to confer a slight growth advantage in each of them—nothing dramatic but enough to suggest the effect could be real. I talked a bit about this in #1050.

**Comment by InfrPopGen** [comment]
Thanks for proposing this as a lineage. As it does not appear to have grown since it was proposed, this can be  closed  for now. Please re-propose or request re-opening should it show significant growth in the future.
