### ISSUE TITLE
Proposal of new sub-lineage of BA.5.1.12 with additional mutations Orf7a:A50S in peruvian genomes by Group of Genomic Surveillance INS-PERU

### ISSUE THREAD

**Issue by IrisSilvaINS** [cov-lineages/pango-designation#1388]
**Description**
Sub-lineage of: Potential new sub-lineage of BA.5.1.12
Earliest sequence: hCoV-19/Peru/LIM-INS-33007/2022 (22/08/2022, Peru)
Most recent sequence: hCoV-19/Peru/LIM-INS-32333/2022 (08/11/2022, Peru)

Countries circulating:
Peru (23)
This potential BA.5.1.12 is principally distributed in Lima, Peru.

**Genomes**
[genomes.txt](https://github.com/roblanf/sarscov2phylo/files/10135545/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4011e_8daff0.json?c=gt-ORF7a_50&label=id:node_6520142&tl=country
https://auspice.us/?c=lineage&f_lineage=BA.5.1.12

![BA 5 1 12_fig1](https://user-images.githubusercontent.com/93674902/205141598-7baba938-f721-458f-b054-d4e3fae5d3f9.png)

![usher_fig2](https://user-images.githubusercontent.com/93674902/205142630-951c80e7-93eb-46e6-9ff8-c4caab57e9a8.png)

![SPECTRUM_FINAL](https://user-images.githubusercontent.com/93674902/205143328-52458711-c6b0-487d-9dbe-bead924b9817.png)

**Comment by Wen1953** [comment]
31 sequences from GISAID to now:
![Captura desde 2022-12-12 13-38-21](https://user-images.githubusercontent.com/89021119/207127383-2042fdf6-a691-4c2b-ba3a-365018311edf.png)

**Comment by InfrPopGen** [comment]
Thank you for submitting this lineage proposal. As there has been little growth advantage over the parent, and this has become clearly negative over the past month, this proposal can be closed for now. Please feel free to re-propose or request re-opening should this lineage show marked advantages in the future.
