### ISSUE TITLE
Proposal of New sub-lineage of: BQ.1.1.4 with ORF1ab: P1596S mutation 

### ISSUE THREAD

**Issue by vekahurtado** [cov-lineages/pango-designation#1389]
**Description**
Proposal of New sub-lineage of: BQ.1.1.4 with orf1ab: P1596S mutations in peruvian genomes by Group of Genomic Surveillance INS-PERU
**Earliest sequence:** hCoV-19/France/NAQ-GENBIO-A13GN2760116/2022 EPI_ISL_15537793 (2022/10/03, France)
**Most recent sequence:** hCoV-19/Peru/LIM-INS-32414/2022 EPI_ISL_15934225 (2022/11/12, Peru) 
7 sequences from Peru
Countries circulating : Peru (7), France (5) Chile (1), Denmark (2) and Switzerland (1)
Genomes:
[genomes (1).txt](https://github.com/cov-lineages/pango-designation/files/10136295/genomes.1.txt)

**Evidence:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_171dc_8ce5b0.json?c=gt-ORF1ab_1596&label=id:node_6406676&tl=country

<img width="1695" alt="BQ 1 1 4 PROPUEST FINAL" src="https://user-images.githubusercontent.com/114951702/205163175-d5a1f877-3d83-4ed9-927c-30f4d6a7822b.png">
<img width="1260" alt="AUSPICE_BQ 1 1 4" src="https://user-images.githubusercontent.com/114951702/205164595-704d518a-c474-4ff5-9f27-7f0f4a7e56da.png">

**Comment by Wen1953** [comment]
22seqs to now
![Captura desde 2022-12-19 11-49-40](https://user-images.githubusercontent.com/89021119/208477573-72eceb2b-f3f2-4d37-a504-bc9754f9a4b0.png)

**Comment by InfrPopGen** [comment]
Thank you for submitting this lineage proposal. As there has been little growth over the past three months (and indications of a relative growth disadvantage in Peru and Europe), this proposal can be closed for now. Please feel free to re-propose or request re-opening should this lineage show marked advantages in the future.
