### ISSUE TITLE
C.1.X sublineage associated with Southern Africa

### ISSUE THREAD

**Issue by grovesn** [cov-lineages/pango-designation#139]
### C.1.X sublineage associated with Southern Africa
by Natalie Groves

## Description

Sub-lineage of: C.1
Earliest sequence: 2021-05-11
Most recent sequence: 2021-06-27
Countries circulating: South Africa (7), UK (2)

Small clade of sequences within lineage C.1 that have a distinct spike profile. Most sequences are from South Africa but sequences have also been observed in travellers in the UK. 

Mutations observed:

Gene | Mutations
--|--
orf1ab | E102K,T1246I,T1637I,L3201P,G3278S,3675-3677del,P4715L
S | P9L,P25L,C136F,144del,R190S,D215G,243-244del,Y449H,E484K,N501Y,D614G,H655Y,N679K,T716I,T859N
orf3a | 255del
M | I82T
N | P13L,R203K,G204R,Q384H

## Genomes

[clade_sequences.csv](https://github.com/cov-lineages/pango-designation/files/6790583/clade_sequences.csv)

## Evidence

Tree shows all GISAID C.1 sequences and clade described highlighted in yellow.

![c 1_investigation aligned tree](https://user-images.githubusercontent.com/15730790/125063816-d86b4100-e0a7-11eb-91bf-f2716c1fbdd1.png)

**Comment by rambaut** [comment]
These are very P.1-like mutations. Could they be a sublineage of P.1 (or recombinant) that is being wrongly placed in C.1?

**Comment by rambaut** [comment]
There are now more genomes of this from various countries - probably needs designating.

**Comment by insapathogenomics** [comment]
We have also recently detected one sequence with this profile (EPI_ISL_2989113) in Portugal.

**Comment by AngieHinrichs** [comment]
These sequences seem to cluster with @grovesn and @insapathogenomics sequences:
```
Shenzhen/IVDC-0610-33/2021      EPI_ISL_2931281 2021-06-15
SouthAfrica/NICD-N10213/2021    EPI_ISL_2984801 2021-07-02
SouthAfrica/NICD-N10228/2021    EPI_ISL_2988404 2021-06-29
SouthAfrica/NICD-N10245/2021    EPI_ISL_2988878 2021-06-29
SouthAfrica/NICD-N10255/2021    EPI_ISL_2988405 2021-06-26
SouthAfrica/NICD-N10596/2021    EPI_ISL_2988409 2021-06-30
SouthAfrica/NICD-N9826/2021     EPI_ISL_2942287 2021-06-15
SouthAfrica/VIDA-KRISP-K018954/2021   EPI_ISL_2841668   2021-06-24
SouthAfrica/VIDA-KRISP-K018963/2021   EPI_ISL_2841677   2021-06-21
Switzerland/VD-CHUV-GEN5512/2021      EPI_ISL_2868597   2021-06
```
They are kind of messy though, lots of mutations that appear together (or not) inconsistently, so I also wonder how much contamination is muddling the waters here.

Here's a Nextstrain view of all 20 sequences with the most closely related outgroup sequence, from a modified version of the 2021-07-20 UCSC tree (a weird probably-contaminated branch in the UCSC tree attracted the sequences, so I removed that branch and added back these 20 to get this view):
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-139_2021_07_20_lopped.json?branchLabel=Spike%20mutations&c=pango_lineage&label=nuc%20mutations:C2485T,G2659A,C5175T,A7699G,T9867C,A14431C,T28516C

**Comment by AngieHinrichs** [comment]
Here's another parsimony-ish view when the 20 sequences are added back in a different order (outgroup sequence in red):
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-139_2021_07_20_lopped_addedBack.json?branchLabel=Spike%20mutations&c=pango_lineage&label=nuc%20mutations:G23012A,C23525T,C23709T,T26767C

**Comment by chrisruis** [comment]
Thanks @grovesn. We've added this as C.1.2 in [v1.2.40](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.40) with 15 sequence designations (we didn't designate South_Africa/NICD-N10245/2021, South_Africa/NICD-N8122/2021, South_Africa/NICD-N8127/2021, South_Africa/NICD-N8104/2021 and South_Africa/VIDA-KRISP-K018963/2021 as they have >5% ambiguity)
