### ISSUE TITLE
BQ.1.1 Sublineage with ORF8:F6S, nuc: A14424C, ORF7a:S60G (74 seq)

### ISSUE THREAD

**Issue by AliNunz** [cov-lineages/pango-designation#1391]
**Description:**
Potential BQ.1.1 sub-lineage containing ORF8:F6S mutations proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS-Peru) 

**Sub-linage of:** BQ.1.1

**Evidence:**
![nextrain_peru](https://user-images.githubusercontent.com/115187682/205217192-2e68ad13-1673-4c44-bcbd-e0f704afc4f8.png)

![nexstrain](https://user-images.githubusercontent.com/115187682/205217443-1141704c-5f33-4fac-83b8-b7f458eedaeb.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_33235_96fff0.json?c=userOrOld

![covspectrum2](https://user-images.githubusercontent.com/115187682/205217245-a7450659-2872-4426-8bc5-7adb3dc5d490.png)

https://cov-spectrum.org/explore/Peru/AllSamples/Past6M/variants?aaMutations=ORF8%3AF6S&nextcladePangoLineage=BQ.1.1&

**Earliest sequence:** 2022-10-14
hCoV-19/Peru/LIM-INS-32180/2022

**Most recent sequence:** 2022-11-16
Denmark/DCGC-613205/2022

**Countries circulating**
Peru (13), Denmark (1)

**Genomes:**
EPI_ISL_15806283, EPI_ISL_15934586, EPI_ISL_15934268, EPI_ISL_15934589, EPI_ISL_15943404, EPI_ISL_15934635, EPI_ISL_15934083, EPI_ISL_15943431, EPI_ISL_15943430, EPI_ISL_15943450, EPI_ISL_15934242, EPI_ISL_15944203, EPI_ISL_15944202, EPI_ISL_15882195

**Comment by Wen1953** [comment]
Sublineage of BQ.1.1 with ORF8:F6S and S:S408R is still growing. Now in Brazil, Israel, Peru, Portugal and United States.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF8%3AF6S%2CS%3AS408R&nextcladePangoLineage=BQ.1.1&
![Captura desde 2022-12-12 11-32-18](https://user-images.githubusercontent.com/89021119/207100494-48a21362-29bb-4e34-ba35-ae09654de389.png)

**Comment by corneliusroemer** [comment]
I'm skeptical of `S:R408R` - this is a well known reversion that appears to usually be artefactual.

You can see how it varies widely by country but doesn't change over time. This is exactly the finger print of a bioinfo/sequencing artefact.

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/25161793/207110204-8bdfc4de-489b-446f-828a-8040a7c777b5.png">

The ORF8:F6S substitution looks good - one should throw them into Usher and see if they cluster nicely. Hard to tell from covSpectrum alone, but it does look like it's the most prominent BQ.1.1 linage in South America

**Comment by AliNunz** [comment]
thanks @corneliusroemer! 
Usher finds a branche with ORF7a: S60G after A14424C. 

74 sequences today from Canada, Denmark, France, Germany, Israel, Scotland, Switzerland, USA.

Earliest sequence: 2022-10-07
hCoV-19/USA/NY-URMC-2211A765-1/2022

Most recent sequence: 2022-12-05
hCoV-19/Canada/ON-PHL-22-55353/2022

![3](https://user-images.githubusercontent.com/115187682/207169598-39de75b9-71bc-4419-b1b2-29f91d7fac82.png)

https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_46f60_762e80.json?c=gt-ORF7a_60

Cov-Spectrum reports 57 BQ.1.1 +A14424C +ORF8:F6S +ORF7a:S60G sequences

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF8%3AF6S%2CORF7a%3AS60G&nucMutations=A14424C&nextcladePangoLineage=BQ.1.1&

[genome_BQ.1.1.csv](https://github.com/cov-lineages/pango-designation/files/10212700/genome_BQ.1.1.csv)

**Comment by Wen1953** [comment]
91 seqs of BQ.1.1 with A14424C +ORF8:F6S +ORF7a:S60G mutations: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF8%3AF6S%2CORF7a%3AS60G&nucMutations=A14424C&nextcladePangoLineage=BQ.1.1&

![Captura desde 2022-12-19 11-35-29](https://user-images.githubusercontent.com/89021119/208475075-d843130d-a80c-4209-ade5-d66a6cc70506.png)

**Comment by Wen1953** [comment]
![image](https://user-images.githubusercontent.com/89021119/209717190-70763f9d-b1cc-4229-bf87-3284b0ee0053.png)

**Comment by Wen1953** [comment]
Most of sequences from Canada
![imagen](https://user-images.githubusercontent.com/89021119/214389693-f93eb8c3-4f59-4146-a3ef-f7e68190d97d.png)

**Comment by Wen1953** [comment]
324 seqs to now

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. Although this is a long lived lineage, over the past two months it has shown a relative growth disadvantage in all countries where it is most detected (except for Canada, which is showing around 4% advantage). Consequently, this can be closed for now, but please re-propose or request re-opening should this show a marked resurgence in the future.
