### ISSUE TITLE
BQ.1.2 + N:H300N, S:Y144del (630sequences)

### ISSUE THREAD

**Issue by DoropFan** [cov-lineages/pango-designation#1392]
Description
Sub-lineage of:BQ.1.2
Earliest sequence:2022-09-07(Israel)
Most recent sequence:2022-11-23
Countries circulating:Mongolia,Turkey,Japan,United States,Germany...
Sequences:60

Amino acid changes:N:H300N, ORF1b:P1427S, S:Y144-

CovSpectrum:BQ.1.2 (Nextclade) + N:H300N, S:Y144-
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=N%3AH300N%2CS%3AY144-&nextcladePangoLineage=BQ.1.2

[CovSpectrum Compare variants](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BQ.1.2&aaMutations1=N%3AH300N%2CS%3AY144-&nextcladePangoLineage1=BQ.1.2&analysisMode=CompareEquals&)
![bq12nh300n](https://user-images.githubusercontent.com/118802079/205221889-9c602116-15cd-4f76-9079-aab290100010.jpg)
[Genomes](https://lapis.cov-spectrum.org/gisaid/v1/sample/gisaid-epi-isl?dateFrom=2022-05-30&dateTo=2022-11-25&aaMutations=N%3AH300N%2CS%3AY144-&nextcladePangoLineage=BQ.1.2*&host=Human&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&orderBy=random)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.2.1 with 570 newly designated sequences, and 0 updated. Defining mutations nt:C29171A (N:H300N), nt:C15960A, nt:C27513T (following A23558G (S:I666V)). There was no clear extra growth advantage at this time with ORF1b:P1427S, so this is designated from the previous node.
