### ISSUE TITLE
Potential BA.2.75*/BQ.1* recombinant (41 seqs as of 2023-01-28)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1393]
### Description
**Recombinant between**: BA.2.75* and BQ.1* (without S:R346T)
**Earliest sequence**: 2022/11/04 (US-TX)
**Most recent sequence**: 2022/11/26 (Canada-NB)
**Countries circulating**: US-TX (3/6), Canada-NB (2/6), France (1/6)
**Potential breakpoint**: Spike NTD (22193-22330)

**Mutation profile** (private mutations are in yellow color):
![image](https://user-images.githubusercontent.com/86835836/205232676-45dddbfa-e2be-4208-a38c-47796f39b178.png)
**Private mutations**: C7303T, C12952T, C13965T, C15277T (ORF1b:H604Y)
**GISAID query**: C7303T, C12952T, C13965T, C15277T

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/205233622-a8b18697-bb4d-4e45-9fe8-dfbb18adecaa.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41807_99a4b0.json?branchLabel=none&c=gt-nuc_12952&l=scatter&label=id:node_8931725&scatterY=gt

Genomes:
EPI_ISL_15841842, EPI_ISL_15853687, EPI_ISL_15893272, EPI_ISL_15951145, EPI_ISL_15976945, EPI_ISL_15977006

**Comment by silcn** [comment]
There are also a couple of private mutations in the BQ.1* part: C23625T = S:A688V and T23773C. The first suggests the parent might be a BQ.1.8.2, though the regions of geographic circulation don't match up.

**Comment by FedeGueli** [comment]
One more sequence with NSP12_H613Y, Spike_G339D,Spike_i210V, -E_T11A, NSp8_N118S

total count now 7

**Comment by c19850727** [comment]
10 sequences as of 2022-12-05. Newly found in Canada-ON and US-CA.

**Comment by FedeGueli** [comment]
12 seqs as today with NSP12_H613Y, Spike_G339D,Spike_i210V, -E_T11A, NSp8_N118S

**Comment by FedeGueli** [comment]
Now we are at 18seqs with Ireland and California accounting for the last six

**Comment by c19850727** [comment]
19 sequences as of 2022-12-25. Newly found in Ireland.

**Comment by FedeGueli** [comment]
22 seqs as today. From Nevada and Maryland last sequences came

**Comment by FedeGueli** [comment]
one more from England

**Comment by FedeGueli** [comment]
One more from California

**Comment by c19850727** [comment]
25 sequences as of 2023-01-05.

**Comment by FedeGueli** [comment]
30 sequences as today. last sequences from Uk,Usa, Denmark

**Comment by FedeGueli** [comment]
34 sequences as today, new ones from England 3 and Denmark 1

**Comment by FedeGueli** [comment]
38 as today

**Comment by c19850727** [comment]
37 sequences as of 2023-01-20. Newly found in the Netherlands.

**Comment by FedeGueli** [comment]
@c19850727 saka my query finds 38 : NSP12_H613Y, Spike_G339D,Spike_i210V, -E_T11A, NSp8_N118S , 
my last samples are NDL NDL TX MD DK EN EN correct?

**Comment by c19850727** [comment]
Hi @FedeGueli  I just double checked the usher tree and it seems you are right. There were one sequence (England/BRBR-3267E1FC/2022) with a N at 13965 that has been missed in my query but still got caught by yours.

BTW as of today there are 41 sequences (using a new and simplied query: C12952T, T23773C, C15277T)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XBP with 4 newly designated sequences, and 0 updated designations. Defining mutations C15277T (ORF1b:H604Y), A22190G (S:I210V), C12952T, T23773C (following A22893C, T22942A, G27038A, C28312T, G28330A).

**Comment by JosetteSchoenma** [comment]
XBP
