### ISSUE TITLE
BN.1.3 with S:V445A [10 sequences from 5 countries uploaded since 2022-11-21]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1397]
Noticed 10 BN.1.3 with S:V445A that was uploaded from 5 countries around the world within 10 days

GISAID query: aa `Spike_V445A,Spike_G446S`, nt `G11146T`

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/25161793/205375940-32c561d4-2d4a-413f-a34d-ed3f1a9dddc2.png">

There seems to be homoplasy? The Japanese and the other sequences don't cluster. So worth watching for a bit more.

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/25161793/205376747-6f86a41c-ce66-42f1-a91b-05787d9e8aea.png">

https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_327af_a59d10.json?f_userOrOld=uploaded%20sample

**Comment by cvejris** [comment]
445A has been super rare in Centaurus so far, and its presence in the already very successful BN.1.3 is concerning

**Comment by FedeGueli** [comment]
Gisaid Query withouth nuc muts : Spike_K356T,Spike_V445A,Spike_G446S,E_T11A

**Comment by FedeGueli** [comment]
14. as today

**Comment by ryhisner** [comment]
There are now 52 sequences of BN.1 with S:V445A; 43 of them in the (very large) ORF1a:H110Y branch. All 43 of these are from Japan and have ORF1b:L1783R.
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/33738461/208570670-d165bb2d-52d7-4c7c-829d-57b7221c5504.png">

There's another branch of BN.1.3 + S:V445A + T4435C with 8 sequences: three from England, two from Japan, one from Austria, one from New Zealand, and one from Russia.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39423_122330.json?f_userOrOld=uploaded%20sample&label=id:node_3791873

**Comment by FedeGueli** [comment]
Prelimanary 8x doubling in our chart is 20 days, very fast one. @corneliusroemer @InfrPopGen @thomasppeacock  i suggest to designate it.

**Comment by InfrPopGen** [comment]
Thank you for noting this, which has been added as lineage BN.1.3.2 with 25 newly designated sequences, and 0 updated. Defining mutations T18815G (ORF1b:L1783R), T22896C (S:V445A) (following C593T (ORF1a:H110Y)).
