### ISSUE TITLE
Mix-up between B.1.316 and B.1.1.316

### ISSUE THREAD

**Issue by yukifuruse1217** [cov-lineages/pango-designation#14]
On the PANGO lineages website, https://cov-lineages.org/lineages/lineage_B.1.html, it is described that "B.1.1.316 | International lineage with E484K mutation" and "B.1.316 | Canadian lineage." However, I believe that B.1.316 is the lineage with E484K mutation. Will you please check that (and correct it if necessary)?

Thanks,
Yuki Furuse
Assistant professor, Kyoto University

**Comment by aineniamh** [comment]
Hi @yukifuruse1217, thanks for pointing this out. 

The descriptions are correct however the designations had become slightly muddled by a typo. The image below shows lineage B.1.1.316, which has the E484K mutation. There is currently a pangoLEARN model training to rectify this issue and I have just tagged a new release of pango-designation (v1.0.4) to include this fix. B.1.316 is indeed a small Canadian lineage.
Thanks again for pointing this out.

<img width="1023" alt="Screenshot 2021-02-16 at 10 51 08" src="https://user-images.githubusercontent.com/11678307/108053108-e363fd00-7044-11eb-99fc-60e60548e16f.png">
