### ISSUE TITLE
AY.1 appearing in COG-UK lineage calls without K417N for PLEARN-v1.2.34

### ISSUE THREAD

**Issue by theosanderson** [cov-lineages/pango-designation#140]
Hi, it looks like a lot of AY.1 without K417N has appeared in the latest COG metadata using PLEARN-v1.2.34

 ```
wget https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_metadata.csv
grep AY.1 cog_metadata.csv | grep K417N | wc -l
49
```

 ```
grep AY.1 cog_metadata.csv | wc -l
2146
```

**Comment by rmcolq** [comment]
We are about to release the same model with an updated designation hash as a patch. Hopefully this will improve things while training the new model

**Comment by rmcolq** [comment]
This has been addressed:
1. PangoLEARN model is in the process of being retrained with the extra commits which include more background Delta samples
2. PangoLEARN patch created which add those into the designation hash while the model trains
3. Scorpio, constellations and pangolin updated to allow for a check between scorpio called lineage and pangolin called lineage which in some cases will now overwrite a child assignation with parent called by scorpio. Applied to this particular example it resolves the issues for AY.1 and provides a safety net for future problem VOC plus lineages
