### ISSUE TITLE
BQ.1.13 sublineage with S:Y144-, S:F157L first detected in New Jersey, USA (324 good and 363 total seqs as of 2022-12-24; North America, Europe, Israel, Australia, Singapore)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1400]
There may be a BQ.1.13 sublineage with S:F157L (C22033A) after synonymous mutation C7318T first detected in New Jersey, USA.

As of 2022-12-03, Cov-Spectrum reports 69 good-quality (73 total) BQ.1.13+S:157L sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABQ.1.13+%26+S%3AF157L&nextcladeQcOverallScoreTo=29&

Initial growth estimates indicate potentially strong growth.

As of 2022-12-03, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![BQ 1 13+S_157L_UShER_CoV-Spectrum json](https://user-images.githubusercontent.com/88959107/205468191-d4bf5d74-97bb-4913-83f5-bc14688421d2.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/12/subtreeAuspice1_CoV-Spectrum_BQ.1.13%2BS_157L.json?c=gt-S_157&label=id%3Anode_2035017

GISAID query: Lineage BQ.1.13, AA Substitutions Spike_F157L, Nucl mutations C7318T.

First GenBank sequence: 2022-10-10 New Jersey, USA

Most Recent GenBank sequence: 2022-11-18 New York, USA

Most Recent Outbreak.info sequence: 2022-11-23 England, United Kingdom

Most Recent GISAID sequence: 2022-11-28 both Iceland and Lombardy, Italy

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-BQ.1.13+S_157L.zip](https://github.com/cov-lineages/pango-designation/files/10147617/Support-BQ.1.13%2BS_157L.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-BQ.1.13+S_157L.txt](https://github.com/cov-lineages/pango-designation/files/10147618/gisaid-epi-isl-BQ.1.13%2BS_157L.txt)

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=BQ.1.13&muts=S%3AF157L.

**Comment by AnonymousUserUse** [comment]
I suggest to create and use a new label "BQ.1" for sublineages of that (since BQ.1 has been designated as a separate Nextstrain clade)

**Comment by alurqu** [comment]
I had missed the S:Y144 deletion. Thank you to @Sinickle for pointing it out.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.13.1 with 199 newly designated sequences, and 0 updated. Defining mutation C22033A (S:F157L) (following C7318T).
