### ISSUE TITLE
BQ.1.1 sublineage(s) with S:Y144-, S:M153I (607 and 75 seqs, mostly USA)

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1402]
**Description**
Sub-lineage of: BQ.1.1
Earliest sequence: 2022-10-19, USA California --- EPI_ISL_15665959
Most recent sequence: 2022-11-21, USA California — EPI_ISL_15976632
Countries circulating: USA (77), Australia (3), Chile (1), Japan (1), Italy (1), UK (1) 
Number of Sequences: 84
GISAID Query: Spike_K444T,Spike_F486V,Spike_R346T,Spike_M153I,Spike_y144del
CovSpectrum Query: s:153i & s:444t & s:486v & s:346t & s:144-
Substitutions on top of BQ.1.1
Spike: Y144del, M153I
Nucleotides: T21992-,A21993-,T21994- and then either G22021A or G22021T

**USHER Trees**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33a4c_d00b70.json?c=gt-S_153&label=id:node_2036828
![image](https://user-images.githubusercontent.com/94097102/205516052-567ddadf-368e-4050-9bf2-a31d624984e2.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_33a4c_d00b70.json?c=gt-S_153
![image](https://user-images.githubusercontent.com/94097102/205516010-2cee06bb-fb3f-4239-8daf-d3c0c4b3cb2a.png)

**Evidence**
I'm proposing these because I notice that in my [spike-protein-only BQ.1* sublineage tracking collection](https://cov-spectrum.org/collections/37), I noticed that it seems S:144- lineages seem to be picking up an additional NTD mutation, and these are appearing towards the top in measured growth advantage. 

@Alurqu proposed one of these in #1400. 
Another one I'll be looking to propose has S:S256L.

I believe that these lineages follow the prediction in the paper ["Imprinted SARS-CoV-2 humoral immunity induces convergent Omicron RBD evolution" ](https://www.biorxiv.org/content/10.1101/2022.09.15.507787v4.full.pdf+html) that BQ.1.1 needs to pick up NTD mutations to further evade immunity.  
S:144- can be clearly measured to provide growth advantage already. I believe that these additional NTD mutations may enhance its immune evasion and provide a further growth advantage to what is already a contender for the most fit spike protein at the moment.  Even if these mutations were not previously beneficial, its possible that they will now be advantageous due to removing a proportion of remaining immunity that now may be comparatively larger if S:144- has taken out a substantial amount of non-overlapping antibodies. 

S:153 is notably mutated to S:153T in BA.2.3.20. S:153I is also found in over 1000 BE.1 sequences, but does not seem to grant an advantage over regular BE.1 in this case. 

**Note:**
I suspect that this is two separate lineages, characterizable by the separate NT mutation to achieve S:153I. 
My numbers at the top are for both lineages. The 22021t sublineage is entirely in the US so far. 

**Genomes:**
[68 genomes - 22021a.txt](https://github.com/cov-lineages/pango-designation/files/10149513/22021a.txt)
[12 genomes - 22021t.txt](https://github.com/cov-lineages/pango-designation/files/10149514/22021t.txt)

**Comment by ryhisner** [comment]
Great spot and proposal! This is definitely one to watch. S:Y144del confers a clear growth advantage, and I suspect S:M153 mutations are quite advantageous as well.

**Comment by Sinickle** [comment]
The proposed lineage I mentioned with G22021A now has an offshoot with ~10 sequences mostly USA with the additional mutations 
ORF1a:R1464Q, ORF1a:V2522I, ORF8:I9S, S:T1120S

No reversions compared to my proposed parental lineage.

**Comment by FedeGueli** [comment]
@corneliusroemer @InfrPopGen this is one of the fastest BQ.1.1 , i think it deserves a fast designation.

**Comment by FedeGueli** [comment]
<img width="1155" alt="Schermata 2022-12-29 alle 23 47 39" src="https://user-images.githubusercontent.com/87669813/210018303-69397d8f-f304-4606-b3ca-1ff0994b6861.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_a5a9_e18840.json?label=id:node_6452756

**Comment by rquiroga7** [comment]
I was coming to comment the same thing @FedeGueli . 90% of the sequences in this M153I subtree are from USA, but sequences detected all over the world.
![image](https://user-images.githubusercontent.com/8103453/210119368-5a00f6a3-f601-4356-9afa-01f2dbf91798.png)

Notably, the G22021A branch seems to have added T23042C, which leads to S:494P. I have proposed that sub-lineage in issue #1484.

**Comment by Sinickle** [comment]
The S:T547K branch is up to 75 sequences.
The S:T1120S branch is up to 36 sequences. 
The S494P branch @rquiroga7 found is at 14 sequences. 
The S:K323I branch is up to 13 sequences. 
The M1229I branch is up to 12 sequences. 
A new S:L176F branch is at 10 sequences.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.1.32 with 218 newly designated sequences, and 0 updated. Defining mutation G22021A (S:M153I) (following A17039G (ORF1b:N1191S)).
Thanks for submitting. We've added lineage BQ.1.1.33 with 27 newly designated sequences, and 0 updated. Defining mutation G22021T (S:M153I) (following A15111G).
The most recent common ancestor of these two lineages is at shared node A17039G (ORF1b:N1191S).
Happy New Year!

**Comment by AngieHinrichs** [comment]
> Thanks for submitting. We've added lineage BQ.1.1.33 with 27 newly designated sequences, and 0 updated. Defining mutation G22021T (S:M153I) (following A15111G).

I believe BQ.1.1 > A15111G is BQ.1.1.3, so instead of BQ.1.1.33 I think it should be [new alias for BQ.1.1.3].1.

**Comment by InfrPopGen** [comment]
> > Thanks for submitting. We've added lineage BQ.1.1.33 with 27 newly designated sequences, and 0 updated. Defining mutation G22021T (S:M153I) (following A15111G).
> 
> I believe BQ.1.1 > A15111G is BQ.1.1.3, so instead of BQ.1.1.33 I think it should be [new alias for BQ.1.1.3].1.

Thanks for spotting that @AngieHinrichs , I have created alias DR.1, redesignated those that were BQ.1.1.33, and withdrawn BQ.1.1.33. I was so taken by the lovely infinite alleles violation in this case, that I forgot to check the second lineage.

**Comment by AngieHinrichs** [comment]
Thank you @InfrPopGen!
