### ISSUE TITLE
BQ.1.1 sublineage with S:Y144-, S:S256L (210 seqs, Europe, Asia, Australia)

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1403]
**Description**
Sub-lineage of: BQ.1.1
Earliest sequence: 2022-10-12, Indonesia --- EPI_ISL_15812519
Most recent sequence: 2022-11-26, Australia — EPI_ISL_15982517
Countries circulating: Australia (26), Indonesia (15), Germany (5), Singapore (3), Japan (2), UK (2), Austria (1), France (1),  Netherlands (1), 
Number of Sequences: 56
GISAID Query: Spike_K444T,Spike_F486V,Spike_R346T,Spike_S256L,Spike_y144del
CovSpectrum Query: s:256l & s:444t & s:486v & s:346t & s:144-
Substitutions on top of BQ.1.1
Spike: Y144del, S256L
Nucleotides: T21992-,A21993-,T21994-, C22329T

**USHER Trees**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33441_d00980.json?c=gt-S_256
![image](https://user-images.githubusercontent.com/94097102/205517254-5a262c5c-c6bd-4eba-8c76-df34b7b3358f.png)

**Evidence**
I'm proposing these because I notice that in my [spike-protein-only BQ.1* sublineage tracking collection](https://cov-spectrum.org/collections/37), I noticed that it seems S:144- lineages seem to be picking up an additional NTD mutation, and these are appearing towards the top in measured growth advantage.

@alurqu proposed one of these in https://github.com/cov-lineages/pango-designation/issues/1400.
I've proposed another one with S:153I in #1402 

I believe that these lineages follow the prediction in the paper ["Imprinted SARS-CoV-2 humoral immunity induces convergent Omicron RBD evolution" ](https://www.biorxiv.org/content/10.1101/2022.09.15.507787v4.full.pdf+html)that BQ.1.1 needs to pick up NTD mutations to further evade immunity.
S:144- can be clearly measured to provide growth advantage already. I believe that these additional NTD mutations may enhance its immune evasion and provide a further growth advantage to what is already a contender for the most fit spike protein at the moment. Even if these mutations were not previously beneficial, its possible that they will now be advantageous due to removing a proportion of remaining immunity that now may be comparatively larger if S:144- has taken out a substantial amount of non-overlapping antibodies.

S:256L has been sequenced over 1000 times in the last 6 months, notably being a part of CM.9, a BA.2.3.20 sublineage, as well as in XBC. 

**Genomes:**
45 seqs - [1402Genomes.txt](https://github.com/cov-lineages/pango-designation/files/10149551/1402Genomes.txt)

**Comment by Sinickle** [comment]
S:256L has come up on a few different BQ.1 lineages. Usher is still putting the vast majority with this particular spike profile on the same single branch though.

**Comment by FedeGueli** [comment]
@Sinickle is not already designated BQ.1.1.31?

**Comment by Sinickle** [comment]
@FedeGueli you're right!! I think the designation came after I created the issue, but regardless, it's designated so I'll close the issue now.
