### ISSUE TITLE
Potential CH.1.1 with Spike S255P mainly from Australia and New Zealand [98 Sequences]

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#1405]
CH.1.1 + S:255P [New Zealand (58 sequences), Australia (10) and Hong Kong (1)]
Earliest Specimen Collection date: 10-28-2022 (NZ)
Latest sequence submission date: 11-30-2022

A big sub-cluster of sequences with ORF1a:H1545Q (Papain-like protease domain) - mainly in NZ

GISAID query: Spike_S255P, Spike_R346T, Spike_F486S,Spike_K444T,Spike_L452R

Cov-Spectrum link: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3A255P&nextcladePangoLineage=ch.1.1*&
[GISAID_CH11_S255P.csv](https://github.com/cov-lineages/pango-designation/files/10149892/GISAID_CH11_S255P.csv)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34975_d3cdb0.json?c=gt-S_255,452,346,486&f_userOrOld=uploaded%20sample&label=id:node_2417846
![image](https://user-images.githubusercontent.com/98380390/205526633-9ea1308c-9f02-405e-ad6e-e52665ee5fed.png)
closer look
![image](https://user-images.githubusercontent.com/98380390/205526734-5e05de78-aecf-44f9-bfb5-025d0f57d48b.png)

Too early but seems to have regional growth advantage over parent and circulating lineages

**Comment by c19850727** [comment]
7 more from Hong Kong

**Comment by RajLABN** [comment]
15 more CH.1.1 + Spike S255P from New Zealand
