### ISSUE TITLE
New DJ.1.1 sublineage with ORF8:W45S, S:Y144-, Nuc:T15516C mutations circulating in Peru, USA.

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#1407]
**A) Description**
New possible DJ.1.1 sub-lineage with ORF8:W45S, S:Y144-, Nuc:T15516C mutations proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**B) Earliest sequence:** 2022-09-16
EPI_ISL_15934005

**C) Most recent sequence:** 2022-11-15
EPI_ISL_15944205

**D) Countries circulating:**
Peru (109)
USA(2)

**E) Genomes**
[genomes.csv](https://github.com/cov-lineages/pango-designation/files/10156383/genomes.csv)

**F) Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9b2b_e25990.json?c=userOrOld

![Captura desde 2022-12-05 12-11-42](https://user-images.githubusercontent.com/89021119/205700674-484bc03e-11b2-4204-8f6f-45c26832f852.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF8%3AW45S%2CS%3AY144-&nextcladePangoLineage=BA.5.1.25*&

![Captura desde 2022-12-05 12-02-33](https://user-images.githubusercontent.com/89021119/205700738-27af8280-2312-404a-9b11-8ea94674a351.png)
![Captura desde 2022-12-05 12-02-56](https://user-images.githubusercontent.com/89021119/205700750-c075f503-d2e0-4d4a-bfe7-af29cd389094.png)

Proposed lineage name
DJ.1.1.X

**Comment by FedeGueli** [comment]
> Notably this sublineage has further acquired S:K147N

Dear @Wen1953  ( and cc @InfrPopGen @corneliusroemer @AngieHinrichs)  i think there is something wrong in this proposal or better saying there is not just one lineage but  **_they are two lineages_** !! Both of them rooting in Orf8:W45S :  

The **first** one is **invisible** due the fact Usher doesnt show deletions and starts right after C18747T and counts 80 sequences (see [here](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF8%3AW45S%2CS%3AY144-&nucMutations=18747T&nextcladePangoLineage=BA.5.1.25*&)
Gisaid query for the **FIRST** one collecting all the bottom branches :  NS8_W45S,Spike_Y144del,N_T265S finds 84 sequences 



<details>
<summary>Expand for EPI_ISLs</summary>
EPI_ISL_15804877-15804878, EPI_ISL_15804880-15804881, EPI_ISL_15804883,
EPI_ISL_15804894-15804895, EPI_ISL_15804898, EPI_ISL_15804903,
EPI_ISL_15805499, EPI_ISL_15805503-15805504, EPI_ISL_15805506,
EPI_ISL_15805516, EPI_ISL_15805529, EPI_ISL_15805531,
EPI_ISL_15805534, EPI_ISL_15805541, EPI_ISL_15805552,
EPI_ISL_15805556, EPI_ISL_15805977, EPI_ISL_15806029,
EPI_ISL_15849955, EPI_ISL_15861393, EPI_ISL_15901822,
EPI_ISL_15913645, EPI_ISL_15933041, EPI_ISL_15934129,
EPI_ISL_15934131-15934133, EPI_ISL_15934137-15934138, EPI_ISL_15934146,
EPI_ISL_15934155, EPI_ISL_15934167, EPI_ISL_15934180,
EPI_ISL_15934197, EPI_ISL_15934199, EPI_ISL_15934209,
EPI_ISL_15934228-15934229, EPI_ISL_15934345, EPI_ISL_15934352,
EPI_ISL_15934357, EPI_ISL_15934359, EPI_ISL_15934371-15934374,
EPI_ISL_15934378, EPI_ISL_15934381, EPI_ISL_15934394,
EPI_ISL_15934419, EPI_ISL_15934649, EPI_ISL_15936781,
EPI_ISL_15943111, EPI_ISL_15943157, EPI_ISL_15943164,
EPI_ISL_15943169-15943170, EPI_ISL_15943173, EPI_ISL_15943175-15943178,
EPI_ISL_15943181, EPI_ISL_15943194, EPI_ISL_15943197-15943198,
EPI_ISL_15943213, EPI_ISL_15943229, EPI_ISL_15943238,
EPI_ISL_15944216, EPI_ISL_15944220, EPI_ISL_15944248,
EPI_ISL_15944252, EPI_ISL_15944267, EPI_ISL_15948699,
EPI_ISL_15960597, EPI_ISL_15987456, EPI_ISL_16007080,
EPI_ISL_16011232, EPI_ISL_16013193
</details>


The **second** one is the one i mentioned above and starts after T15516C then acquiring S:K147N  and counts 99 seqs (see [here](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF8%3AW45S%2CS%3AK147N&nucMutations=T15516C&nextcladePangoLineage=BA.5.1.25*&)
Gisaid query for the **SECOND** one at the top of the tree with S:147N :   **NS8_W45S,Spike_K147N,N_T265S** finds 104 sequences
<details>
<summary>Expand for EPI_ISLs</summary>
EPI_ISL_15804879, EPI_ISL_15804882, EPI_ISL_15804884,
EPI_ISL_15804886, EPI_ISL_15804891, EPI_ISL_15804897,
EPI_ISL_15804901, EPI_ISL_15804905, EPI_ISL_15805497,
EPI_ISL_15805500-15805502, EPI_ISL_15805513, EPI_ISL_15805518,
EPI_ISL_15805520-15805521, EPI_ISL_15805523, EPI_ISL_15805525,
EPI_ISL_15805528, EPI_ISL_15805530, EPI_ISL_15805535,
EPI_ISL_15805537-15805539, EPI_ISL_15805545-15805548, EPI_ISL_15805551,
EPI_ISL_15805553, EPI_ISL_15805555, EPI_ISL_15806026,
EPI_ISL_15806028, EPI_ISL_15806043, EPI_ISL_15815793,
EPI_ISL_15842130, EPI_ISL_15934005, EPI_ISL_15934010,
EPI_ISL_15934127, EPI_ISL_15934130, EPI_ISL_15934134-15934136,
EPI_ISL_15934140-15934141, EPI_ISL_15934143-15934145, EPI_ISL_15934147-15934150,
EPI_ISL_15934152-15934154, EPI_ISL_15934163, EPI_ISL_15934182,
EPI_ISL_15934192, EPI_ISL_15934204, EPI_ISL_15934265,
EPI_ISL_15934281, EPI_ISL_15934363-15934365, EPI_ISL_15934368-15934369,
EPI_ISL_15934380, EPI_ISL_15934388-15934389, EPI_ISL_15934391-15934392,
EPI_ISL_15934399-15934400, EPI_ISL_15934411, EPI_ISL_15934413-15934415,
EPI_ISL_15934624, EPI_ISL_15934631-15934632, EPI_ISL_15934641-15934642,
EPI_ISL_15934716, EPI_ISL_15934720, EPI_ISL_15935023,
EPI_ISL_15943109, EPI_ISL_15943153, EPI_ISL_15943159-15943160,
EPI_ISL_15943166, EPI_ISL_15943203, EPI_ISL_15943207,
EPI_ISL_15943236, EPI_ISL_15943239, EPI_ISL_15944205,
EPI_ISL_15944213, EPI_ISL_15944227, EPI_ISL_15944239,
EPI_ISL_15944268, EPI_ISL_16002601, EPI_ISL_16006702,
EPI_ISL_16006709, EPI_ISL_16007479, EPI_ISL_16009250,

</details>

**Comment by FedeGueli** [comment]
Both  these two sublineages are growing : S:144del reached 99 sequences,
instead S:147N reached 133 sequences

**Comment by Wen1953** [comment]
Hi @FedeGueli. It seems to be that many samples have C18747T, ORF8:W45S, S:Y144- and appears to be a new sublineage inside DJ.1.1. Likewise another sublineage is emerging from that defined by T15516C mutation as I described lines above. @InfrPopGen @corneliusroemer @chrisruis could it be?
Also, I thought that due to the high increasing of DJ.1 in many countries could be very useful to have a new version of pangolin. The last version is from October and it seems to be outdated.

**Comment by AngieHinrichs** [comment]
> Also, I thought that due to the high increasing of DJ.1 in many countries could be very useful to have a new version of pangolin. The last version is from October and it seems to be outdated.

The latest pangolin-data release is [v1.16](https://github.com/cov-lineages/pangolin-data/releases/tag/v1.16) which is from November 7th, so one month old today.  Two days ago @aineniamh tagged pango-designation release [v1.17](https://github.com/cov-lineages/pango-designation/releases/tag/v1.17) and we are working on updating the pangoLEARN model and minimized UShER tree for the next pangolin-data release, so stay tuned for pangolin-data v1.17 hopefully soon.

**Comment by Wen1953** [comment]
> 

Thanks @AngieHinrichs @aineniamh. We appreciate  all your efforts and contributions made to continue with genomic surveillance. We hope to hear from you soon.

**Comment by FedeGueli** [comment]
> Hi @FedeGueli. It seems to be that many samples have C18747T, ORF8:W45S, S:Y144- and appears to be a new sublineage inside DJ.1.1. Likewise another sublineage is emerging from that defined by T15516C mutation as I described lines above. @InfrPopGen @corneliusroemer @chrisruis could it be? Also, I thought that due to the high increasing of DJ.1 in many countries could be very useful to have a new version of pangolin. The last version is from October and it seems to be outdated.

@Wen1953 i actually think they are two and not one only:
the lineage starting with T15516C has not the S:144deletion as you can see from here: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AY144-&nucMutations=T15516C&nextcladePangoLineage=BA.5.1.25*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&
<img width="1062" alt="Schermata 2022-12-10 alle 09 35 24" src="https://user-images.githubusercontent.com/87669813/206841387-8252c251-34f2-4354-97a0-21d7f7d092ea.png">
while many sequences with C18747T have S:144del
<img width="1134" alt="Schermata 2022-12-10 alle 09 36 00" src="https://user-images.githubusercontent.com/87669813/206841418-265a64e4-1001-4d39-8cb9-ddfda97b855d.png">

Covspectrum finds around 300 sequences with C18747T and 49% of them has S:147N and 36% has 144del
<img width="290" alt="Schermata 2022-12-10 alle 09 37 48" src="https://user-images.githubusercontent.com/87669813/206841483-fbe66e2e-72d6-4fc7-b916-6f14c637ce07.png">.


Back to gisaid i found now 110 sequences for NS8_W45S,Spike_Y144del,N_T265S
and 146 for NS8_W45S,Spike_K147N,N_T265S 

Both the lineages are growing quite fast and are worth to be designated.

@InfrPopGen @corneliusroemer

**Comment by InfrPopGen** [comment]
In terms of designatable clades, there appears to be a parental clade, beginning with nt:C18747T, but that would have to designated one node rootward at ORF8:W45S, and within this (off one of the nt:C18747T multifurcations) a sub-clade with S:K147N, but (unlike its sister branches) this one is lacking the S:Y144- deletion (as noted by @FedeGueli). At the moment the apparent growth advantages (with BA.5.1.25*) are about the same for both the larger clade, and its S:K147N sub-clade, over 3 months in Peru, being 28% Current adv. 14-42% and 24% Current adv. 10-38%, respectively. Before designating a heirarchy of DJ.1.1 sublineages, it is probably worth waiting to see if one of these possible pango lineages markedly out competes the other(s).

**Comment by FedeGueli** [comment]
Thanks @InfrPopGen for the analysis in the meanwhile they both keep on growing : the one with S:144Del reached 144 samples and the other with S:147N reached 173.

**Comment by ryhisner** [comment]
Hi, @Wen1953 and @LuisBarcenaF, I noticed a small, five-sequence branch of the S:K147N part of this lineage that appears to have a S:N444K reversion, a mixed nucleotide at S:N460, and, most intriguingly, S:R452V in four of the five sequences, which involves two nucleotide mutations. The fifth sequence, which is not yet on GISAID, appears to have S:R452G (a one-nucleotide mutation) and was collected about 10 days after the others. 

There is a fair bit of missing coverage in these sequences, but almost all in non-spike regions of the genome. If you can give any insight into these peculiar sequences, I'd very much appreciate it. Thanks.
EPI_ISL_16039431-16039434

https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/DJ.1.1%20%2B%20L452V%2C%20etc%20-%20subtreeAuspice1_genome_11432_f03260.json

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage DJ.1.1.1 with 329 newly designated sequences, and 0 updated. Defining mutation A22003T (S:K147N) (following T15516C). For now only the S:K147N sub-clade is designated because the other sub-clade makes up most of the remainder of DJ.1.1 and is a polytomy. If the situation changes in the future please re-propose the S:Y144- sub-clade (or the fast growing sub-clade of it!).

**Comment by Wen1953** [comment]
Thanks @InfrPopGen
