### ISSUE TITLE
DJ.1 with additional mutations ORF1ab:T6098A, Nuc:T9070C, A22924G mutations circulating mostly in Peru

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#1409]
DJ.1 with additional mutations ORF1ab:T6098A, Nuc:T9070C, A22924G mutations by Group of Genomic Surveillance INS-PERU

**Description**
Sub-lineage of: Potential new sub-lineage of DJ.1
Earliest sequence: hCoV-19/Peru/LIM-INS-32572/2022 (14/10/2022, Peru)
Most recent sequence: hCoV-19/Peru/LIM-INS-32397/2022 (12/11/2022, Peru)

**Countries circulating**
Peru (5), Colombia (2), France (1), USA (1)

This potential BQ.1.1 is principally distributed in Madre de Dios, Lima y Loreto, Peru.

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/10158260/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_98cb_e57af0.json?c=gt-nuc_9070,18556,22924&label=id:node_6609104&tl=country

<img width="1371" alt="usher_DJ 1" src="https://user-images.githubusercontent.com/87997149/205754051-12dce31f-8cc9-405e-b5db-fd0c4d222511.png">

<img width="1278" alt="DJ 1" src="https://user-images.githubusercontent.com/87997149/205754143-6c0d439f-1f78-49cf-91d9-9743a30b371f.png">

**Proposed sub-lineage name**
DJ.1.X

**Comment by FedeGueli** [comment]
@LuisBarcenaF i would highlight in the headline that this sublineage of DJ.1 has S:N460K it is the third of this kind after DJ.1.1 the one proposed in #1379 with N:G5E 
@corneliusroemer @thomasppeacock @InfrPopGen i think that all these three sublineages with S:444N S:N460K need to be designated

**Comment by FedeGueli** [comment]
There are now 16 sequences of this sublineage. @corneliusroemer @InfrPopGen i suggest to designate it

**Comment by Wen1953** [comment]
It continues spreading. Now in Brasil. 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AT3287I%2CS%3AN460K&nucMutations=A22924G&nextcladePangoLineage=BA.5.1.25&
![Captura desde 2022-12-12 11-18-42](https://user-images.githubusercontent.com/89021119/207097536-4751581d-a88a-4741-845e-78619d530e7e.png)

**Comment by FedeGueli** [comment]
22 sequences as today. Beyond Peru' and Colombia newly found in NY and California.
@InfrPopGen @corneliusroemer i think it is worth designating this one too.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage DJ.1.3 with 25 newly designated sequences, and 1 updated. Defining mutation T22942G (S:N460K) (following C10125T (ORF1a:T3287I), A22924G).
