### ISSUE TITLE
New lineage proposal of SARS-CoV-2 P.1 (Gamma) lineage variants carrying Spike mutations 𝚫141-144, N679K or P681H

### ISSUE THREAD

**Issue by paolaresende** [cov-lineages/pango-designation#141]
**Description**
Sub-lineages of: P.1 (Gamma)

**P1-Δ141-144-AM:**

Earliest sequence: hCoV-19/Brazil/AM-FIOCRUZ-21891957JM/2021 	[EPI_ISL_2777689]  - 2021-03-12
Most recent sequence: hCoV-19/Brazil/AM-FIOCRUZ-21141985MLS/2021 [EPI_ISL_2777452] - 2021-05-28

**P.1+N679K-AM-I:** 

Earliest sequence: hCoV-19/Brazil/AM-FIOCRUZ-21896338DCF/2021 [EPI_ISL_2777824] - 2021-03-19
Most recent sequence: hCoV-19/Brazil/AM-FIOCRUZ-21890877JAA/2021 [EPI_ISL_2777287] - 2021-05-30

**P.1+N679K-AM-II**

Earliest sequence: hCoV-19/Brazil/AM-FIOCRUZ-21891575VSC/2021 [EPI_ISL_2777660] - |2021-04-03
Most recent sequence: hCoV-19/Brazil/AM-FIOCRUZ-21896191RDM/2021 [EPI_ISL_2777908] - |2021-05-18

**P.1+P681H-AM:**

Earliest sequence : hCoV-19/Brazil/AM-FIOCRUZ-21890984TSM/2021 - 2021-03-26
Most recent sequence : hCoV-19/Brazil/AM-FIOCRUZ-21890173RCC/2021 - 2021-05-31

**P.1+P681H-BR:**

Earliest sequence:  hCoV-19/Brazil/PR-FIOCRUZ-16724|2021-03-12
Most recent sequence: hCoV-19/Brazil/GO-HLAGYN-1702207/2021|EPI_ISL_2617625|2021-06-08 and hCoV-19/Brazil/GO-HLAGYN-1702192/2021|EPI_ISL_2617605|2021-06-08

**Countries circulating:** Brazil

These new proposed lineages evolve from lineage P.1 the major lineage circulating in Brazil since December 2021. More details is available in https://virological.org/t/emergence-and-spread-of-sars-cov-2-p-1-gamma-lineage-variants-carrying-spike-mutations-141-144-n679k-or-p681h-during-persistent-viral-circulation-in-amazonas-brazil/722
Viral isolation and neutralizing assay are in progress to understand the phenotypic characteristics of these sublineages.

**Evidence:**
![Tree_P1_sublineages](https://user-images.githubusercontent.com/51120623/125163019-82f36a80-e161-11eb-9ca1-820b59ccfc86.png)

**Genomes GISAID info:**
[Genomes_details.txt](https://github.com/cov-lineages/pango-designation/files/6795262/Genomes_details.txt)

**Proposed lineage name:** P1-Δ141-144-AM, P.1+N679K-AM-I, P.1+P681H-AM and P.1+P681H-BR may be named according to the Pangolin criteria of P.1 sublineages

**Comment by chrisruis** [comment]
Thanks @paolaresende for submitting. We've added these as lineages P.1.3-P.1.7 in [v1.2.41](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.41)

The lineages are:
P.1.3 - P1-Δ141-144-AM, 25 designated sequences
P.1.4 - P.1+N679K-AM-I, 93 designated sequences
P.1.5 - P.1+N679K-AM-II, 8 designated sequences
P.1.6 - P.1+P681H-AM, 85 designated sequences
P.1.7 - P.1+P681H-BR, 272 designated sequences

In the latest UShER tree, there were more sequences that clustered within several of these lineages so we've also included those in the designations
