### ISSUE TITLE
New BA.5.2+orf1b:1050N sublineage with combo S:N460K (T22942A ) and S:444N defined by Orf3a:Q38E  41 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1410]
While looking at a suspect long branch in Australia leading to a sequence with the Transitions/Trasversions ratio marker ( EPI_ISL_15979220) for Molnupiravir related samples, i found it belonged to a still undesignated BA.5.2 sublineage woith S:N460K and S:444N, and defined by parental lineage with Orf3a:Q38E.
This sublineage likely originated in Sweden and then it was exported to 3 more continents.

Tree isnt totally clear cause it reports a back mutation to Orf38Q in the top side of the tree.
I exclude that part for the count to designate this lineage but probbaly i would feel better if @AngieHinrichs could take a look at it:
<img width="1150" alt="Schermata 2022-12-06 alle 00 43 33" src="https://user-images.githubusercontent.com/87669813/205769293-91c02168-511f-40a9-8d2d-b00d064b34cf.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_230d0_e7dac0.json?label=id:node_6867646

Defining mutations:
BA.5.2 + (> C27513T > C27012T > G12310A > C16616A >) then
Orf3a:Q38E (C25504G) > S:K444N (G22894T) > S:N460K (T22942A ) 

Gisaid query: NS3_q38E,Spike_N460K,Spike_k444N
finds 24 sequences:
EPI_ISL_15479694, EPI_ISL_15531890, EPI_ISL_15532247,
EPI_ISL_15654729, EPI_ISL_15654811, EPI_ISL_15732276,
EPI_ISL_15756260, EPI_ISL_15756304, EPI_ISL_15760427,
EPI_ISL_15779316, EPI_ISL_15830143, EPI_ISL_15830221,
EPI_ISL_15841828, EPI_ISL_15841933, EPI_ISL_15846902,
EPI_ISL_15850312, EPI_ISL_15903053, EPI_ISL_15918344,
EPI_ISL_15931336, EPI_ISL_15947497, EPI_ISL_15954939,
EPI_ISL_15978914, EPI_ISL_15979220, EPI_ISL_15998607

Countries : Australia, Usa , Pakistan

**Comment by AngieHinrichs** [comment]
> Tree isnt totally clear cause it reports a back mutation to Orf38Q in the top side of the tree.
> I exclude that part for the count to designate this lineage

Yes, I agree those should be excluded -- that's not a good placement for them because they don't have ORF3a:Q38E (C25504G), but they were pulled in because they have S:K444N and S:N460K in common with those sequences.  From the sequence dates it looks more likely that ORF3a:Q38E (C25504G) happened first for the sequences that have ORF3a:Q38E, S:K444N and S:N460K.

**Comment by FedeGueli** [comment]
> > Tree isnt totally clear cause it reports a back mutation to Orf38Q in the top side of the tree.
> > I exclude that part for the count to designate this lineage
> 
> Yes, I agree those should be excluded -- that's not a good placement for them because they don't have ORF3a:Q38E (C25504G), but they were pulled in because they have S:K444N and S:N460K in common with those sequences. From the sequence dates it looks more likely that ORF3a:Q38E (C25504G) happened first for the sequences that have ORF3a:Q38E, S:K444N and S:N460K.

Thanks very much @AngieHinrichs !

**Comment by FedeGueli** [comment]
29 sequences as today last samples from Germany and England

**Comment by corneliusroemer** [comment]
These are basically CK.3 but with ORF3a:Q38E instead of ORF7a:T39I

Evidence for homoplasy of 444N seems pretty good in this case.

**Comment by FedeGueli** [comment]
41 as today

**Comment by FedeGueli** [comment]
46 seqs as today. very slow. i ll close this one for the moment
