### ISSUE TITLE
Another BA.5.3.1 sublineage with S:K444T and S:N460K (~290 seq, mainly Brazil)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#1411]
Proposal for a sublineage of BA.5.3.1
Earliest seq: 2022-08-09 (Sao Paulo, Brazil)
Countries detected: Brazil (~220 seq, ~130 from Sao Paulo), USA (25), smaller numbers in about 20 countries in 5 continents

Mutations on top of BA.5.3.1 (those in bold are defining for this lineage):
S: K444T, **N460K**
ORF1a: S74L, **S2822F**, M3911T
nuc: **C12919T, T14367C**, C26681T, C27393T

GISAID query: nucleotide mutations C12919T, T14367C (specific, at least for now)

Most of the substantial BA.5+444X/460K lineages have been designated now but this one seems to have slipped through the net. It is distinct from the recently designated BE.9. It made up around 30% of sequences from Sao Paulo in late October and early November, though it is probably on the decline now. It is also over 10% prevalence in Rio de Janeiro, and there has been a fair amount of international spread.

The ancestor of this lineage is a South African branch of BA.5.3.1 with C27393T and (mostly) ORF1a:S74L from the original BA.5 wave. There are two genuine-looking intermediate sequences from southern Africa with S:K444T but not S:N460K. One of these, from Mozambique in early August, lacks coverage at the 5' end, including ORF1a:S74L. This messes up the Usher tree, which thinks ORF1a:S74L arose after S:K444T and therefore places the S:N460K lineage (in yellow below) in a separate branch from the older ORF1a:S74L sequences (the big green clump at the top). In addition there are several mutations that appear to come and go in the tree, presumably due to sequencing issues.

<img width="734" alt="Brazil_444_460" src="https://user-images.githubusercontent.com/42699509/205809497-5db92e09-01cc-46c1-8379-fdcb7529d86e.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2ecf0_eb0730.json?branchLabel=Spike%20mutations&c=gt-S_460&label=id:node_6338104](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2ecf0_eb0730.json?branchLabel=Spike%20mutations&c=gt-S_460&label=id:node_6338104)

[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=%21C11750T+%26+%5B3-of%3A+S%3AN460K%2C+ORF1a%3AS2822F%2C+C12919T%2C+T14367C%5D&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=%21C11750T+%26+%5B3-of%3A+S%3AN460K%2C+ORF1a%3AS2822F%2C+C12919T%2C+T14367C%5D&)

**Comment by FedeGueli** [comment]
With the query NSP1_S74L,NSP4_S59F,NSP7_M52T i found 331 sequences on Gisaid.
I think thius should be designated as soon as possible being already quite large
. @InfrPopGen @corneliusroemer

**Comment by FedeGueli** [comment]
353 sequences as today recent uploads from  Singapore, Netherlands, Mexico, Australia , England plus various american states suggests a rapid spread and growth. @InfrPopGen i suggest to designate as soon as possible.

**Comment by FedeGueli** [comment]
There could be sublineage of BE.10 defined by Orf7a:P84L , accounting for half of the samples of this lineage with a slight growth advantage versus plain BE.10.

I link the covspectrum query and comparison tool to easily recheck that if necessary: 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nucMutations=C12919T%2CT14367C&aaMutations1=Orf7a%3AP84L&nucMutations1=C12919T%2CT14367C&analysisMode=CompareToBaseline&

@corneliusroemer @silcn
