### ISSUE TITLE
BA.4.6 with additional ORF3a:L106F, ORF1ab:S2224F mutations in Peru

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#1412]
BA.4.6 with additional ORF3a:L106F, ORF1ab:S2224F mutations by Group of Genomic Surveillance INS-PERU

**Description**
Sub-lineage of: Potential new sub-lineage of BA.4.6
Earliest sequence: hCoV-19/Peru/ICA-INS-30667/2022 (05/10/2022, Peru)
Most recent sequence: hCoV-19/Peru/ICA-INS-32442/2022 (11/11/2022, Peru)

**Countries circulating**
Peru (4)

This potential BA.4.6 is principally distributed in Ica, Peru.

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/10167748/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31cc1_f59df0.json?c=gt-nuc_6936,25708&label=id:node_5695946&tl=country

<img width="1490" alt="usher_ba 4 6" src="https://user-images.githubusercontent.com/87997149/205951925-5163dce4-3b5b-4fe7-9936-073489cab2ea.png">

<img width="1292" alt="ba 4 6" src="https://user-images.githubusercontent.com/87997149/205951952-34b79700-6d8d-4dce-9755-21d6150a773c.png">

**Proposed sub-lineage name**
BA.4.6.X

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. Despite initially fast growth in Peru, this lineage has not been detected over the past two months, and still remains very small. Consequently, this can be closed for now. Please re-propose or request re-opening should this lineage show a marked growth advantage in the future.
