### ISSUE TITLE
BE.1.1.1 Sublineage with S:T859S & ORF3a:L83V (207 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1413]
**Description**
**Sub-lineage of:** BE.1.1.1
**Earliest sequence:** 2022-10-16, USA, Utah — EPI_ISL_15878684
**Most recent sequence:** 2022-11-30, USA, Montana — EPI_ISL_16014574
**Countries circulating:** USA (138), Germany (1)
**Number of Sequences:** 139
**GISAID Query:** Spike_K444T, Spike_T859S, NSP2_Q376K, -Spike_N460K
**CovSpectrum Query:** Nextcladepangolineage:BE.1.1.1* & S:T859S & !T14257C
**Substitutions on top of BE.1.1.1:**
**Spike:** T859S
**ORF3a:** L83V
**Nucleotide:** C313T, C337T, C958T, C24138G, T25639G
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BE.1.1.1%20%2B%20T859S%20%2B%20ORF3aL83V%20-%20VsubtreeAuspice1_genome_3777f_fa1df0.json 

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/33738461/206022017-422782e6-cb67-4d86-9723-30a1e343d5a4.png">
 
**Evidence**
S:T859N is probably the most convergent mutation in chronic-infection Delta cases. S:T859S has been rare, possibly because it involves a C->G nucleotide mutation, which is the rarest type, only making up about 1% of all nuc mutations. 
 
This lineage is mostly confined to the US West, and has been found in especially high numbers in Utah, where 106/139 sequences have been from. In fact, there are almost certainly 50 sequences from Utah that belong to this lineage but which are not included in this proposal due to lack of coverage at S:K444. The Utah Public Health Laboratory, unfortunately, reverts to the reference genome where coverage is lacking. A GISAID search for Spike_T859S, NSP2_Q376K returns 155 sequences from Utah, but Spike_T859S, NSP2_Q376K, Spike_K444T only returns 106. 
 
This lineage appears to be growing very fast, but its true rate of growth is hard to determine. Utah Public Health does a lot of sequencing, so much of this growth may be due to the unusually large number of sequences that come from Utah. As it spreads, we should have a better idea of its growth potential.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15703795, EPI_ISL_15723375, EPI_ISL_15780019, EPI_ISL_15782680, EPI_ISL_15782683, EPI_ISL_15782686, EPI_ISL_15782711, EPI_ISL_15782774, EPI_ISL_15782845, EPI_ISL_15782847, EPI_ISL_15782975, EPI_ISL_15783002, EPI_ISL_15783007, EPI_ISL_15783032, EPI_ISL_15783058, EPI_ISL_15783059, EPI_ISL_15783073, EPI_ISL_15783082, EPI_ISL_15783087, EPI_ISL_15783125, EPI_ISL_15783141, EPI_ISL_15783165, EPI_ISL_15783199, EPI_ISL_15796633, EPI_ISL_15796685, EPI_ISL_15796731, EPI_ISL_15796748, EPI_ISL_15796888, EPI_ISL_15796921, EPI_ISL_15796940, EPI_ISL_15796981, EPI_ISL_15796989, EPI_ISL_15796993, EPI_ISL_15797045, EPI_ISL_15797115, EPI_ISL_15804947, EPI_ISL_15819166, EPI_ISL_15824661, EPI_ISL_15824682, EPI_ISL_15841573, EPI_ISL_15841575, EPI_ISL_15842031, EPI_ISL_15847410, EPI_ISL_15860113, EPI_ISL_15861535, EPI_ISL_15861584, EPI_ISL_15861681, EPI_ISL_15861767, EPI_ISL_15861804, EPI_ISL_15861822, EPI_ISL_15861871, EPI_ISL_15861895, EPI_ISL_15861925, EPI_ISL_15861951, EPI_ISL_15861957, EPI_ISL_15861980, EPI_ISL_15862035, EPI_ISL_15862091, EPI_ISL_15862094, EPI_ISL_15862180, EPI_ISL_15862229, EPI_ISL_15870332, EPI_ISL_15878676, EPI_ISL_15878684, EPI_ISL_15878686, EPI_ISL_15878725, EPI_ISL_15878749, EPI_ISL_15878750, EPI_ISL_15878769, EPI_ISL_15878807, EPI_ISL_15878860, EPI_ISL_15878904, EPI_ISL_15878956, EPI_ISL_15878964, EPI_ISL_15878991, EPI_ISL_15879020, EPI_ISL_15879045, EPI_ISL_15879052, EPI_ISL_15879061, EPI_ISL_15879076, EPI_ISL_15879086, EPI_ISL_15879095, EPI_ISL_15881538, EPI_ISL_15889891, EPI_ISL_15890544, EPI_ISL_15916519, EPI_ISL_15935285, EPI_ISL_15935364, EPI_ISL_15935381, EPI_ISL_15935407, EPI_ISL_15935437, EPI_ISL_15935456, EPI_ISL_15935479, EPI_ISL_15935523, EPI_ISL_15935530, EPI_ISL_15935588, EPI_ISL_15935753, EPI_ISL_15935769, EPI_ISL_15935803, EPI_ISL_15943523, EPI_ISL_15943593, EPI_ISL_15943612, EPI_ISL_15944319, EPI_ISL_15945013, EPI_ISL_15947136, EPI_ISL_15948937, EPI_ISL_15948971, EPI_ISL_15949005, EPI_ISL_15949008, EPI_ISL_15949060, EPI_ISL_15949154, EPI_ISL_15949215, EPI_ISL_15949218, EPI_ISL_15950831, EPI_ISL_15951161, EPI_ISL_15975802, EPI_ISL_15976271, EPI_ISL_15976512, EPI_ISL_15976769, EPI_ISL_15981267, EPI_ISL_15984930, EPI_ISL_15991274, EPI_ISL_15997849, EPI_ISL_15998068, EPI_ISL_15998199, EPI_ISL_15998232, EPI_ISL_15998329, EPI_ISL_15998360, EPI_ISL_15998378, EPI_ISL_15998383, EPI_ISL_15998570, EPI_ISL_15998705, EPI_ISL_16010009, EPI_ISL_16011615, EPI_ISL_16011881, EPI_ISL_16012309, EPI_ISL_16012313, EPI_ISL_16014574, EPI_ISL_16022924
</details>

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As this has been showing negative growth relative to its parent in the US for over a month, this can be closed at the moment. Nevertheless, please re-propose or request re-opening should this lineage show clear signs of relative growth in the future.
