### ISSUE TITLE
BQ.1 Sublineage with ORF3a:R68I, ORF1a:V2157I, ORF1b:P2321L (2641 seq, Dec 29) + Branch with S:ins248RWMD, S:Y248S, C25096T (158 seq, Dec 29)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1415]
### **Description 1**
**Sub-lineage of:** BQ.1
**Earliest sequence:** 2022-9-12, USA, Washington state — EPI_ISL_15249934, EPI_ISL_15269301
**Most recent sequence:** 2022-11-30, USA, Nebraska — EPI_ISL_16022503
**Countries circulating:** USA (727), Canada (27), Denmark (17), Australia (3), Japan (2), South Korea (2), Israel (1), Luxembourg (1), New Zealand (1), Peru (1), Switzerland (1)
**Number of Sequences:** 783
**GISAID Query:** NS3_R68I, NSP15_P270L, NSP3_V1339I, NSP12_Y273H
**CovSpectrum Query:** Nextcladepangolineage:BQ.1* & ORF3a:R68I & ORF1a:V2157I & ORF1b:P2321L
**Substitutions on top of BQ.1:**
**ORF3a:** R68I
**ORF1a:** V2157I
**ORF1b:** P2321L
**Nucleotide:** A1777G, G6734A, C20429T, G25595T, T29492C
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1%20%2B%20ORF3a%3BR68I%2C%20ORF1a%3BV2157I%2C%20ORF1b%3BP2321L%20-%20subtreeAuspice1_genome_7613_fdecf0.json
 
<img width="1259" alt="Screen Shot 2022-12-06 at 8 57 21 PM - BQ 1 Big Usher Tree Pic" src="https://user-images.githubusercontent.com/33738461/206072137-7542c329-b744-4711-94a0-5317ed4125d3.png">

**Evidence**
In the United States, over the past three months, this lineage has competed on an even footing with BQ.1.1*. A CovSpectrum growth advantage comparison shows a 1% advantage (CI: -3%-5%) for “Nextcladepangolineage:BQ.1* & ORF3a:R68I & ORF1a:V2157I & ORF1b:P2321L” compared to “Nextcladepangolineage:BQ.1.1*” in the United States, which is where the vast majority of sequences in this lineage come from.
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABQ.1.1*&variantQuery1=Nextcladepangolineage%3ABQ.1*+%26+ORF3a%3AR68I+%26+ORF1a%3AV2157I+%26+ORF1b%3AP2321L&analysisMode=CompareToBaseline&
 
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/33738461/206072069-aaf62a2d-4f08-47f4-926a-e4fd658c769f.png"> 
 
**Genomes**
[BQ.1 + ORF3a;R68I, ORF1a;V2157I, ORF1b;P2321L - GISAID_hcov-19_ids_2022_12_07_00_27.csv](https://github.com/cov-lineages/pango-designation/files/10172203/BQ.1.%2B.ORF3a.R68I.ORF1a.V2157I.ORF1b.P2321L.-.GISAID_hcov-19_ids_2022_12_07_00_27.csv)

 
 
### **Description 2**
**Sub-lineage of:** BQ.1
**Earliest sequence:** 2022-11-2, USA, California — EPI_ISL_15953080, EPI_ISL_15767138
**Most recent sequence:** 2022-11-22, USA, Florida — EPI_ISL_16021081
**Countries circulating:** USA (all)
**Number of Sequences:** 17
**GISAID Query:** Spike_ins248RWMD
**CovSpectrum Query:** Nextcladepangolineage:BQ.1* & C25096T & A1777G & G6734A & C20429T & G25595T & T29492C
**Substitutions on top of Proposal 1 (above):**
**Spike:** ins248RWMD
**Nucleotide:** ins22303TCAAGATGGATG, C25096T
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1%20%2B%20ins248RWMD%20-%20subtreeAuspice1_genome_333a6_fd5160.json  
 
 
<img width="1511" alt="Screen Shot 2022-12-06 at 8 59 23 PM - BQ 1 Insertion Tree" src="https://user-images.githubusercontent.com/33738461/206072166-8045c4da-8f28-4b4e-8f47-27eea8836c25.png">
 
**Evidence**
Nextclade describes this insertion as S:ins247SRWM + S:Y248D rather than Spike_ins248RWMD, Spike_Y248S, as it is called on GISAID. Every sequence that has this insertion also has C25096T, and there are no sequences that have C25096T that do not have the insertion. These sequences have come from three different labs, so I think it's safe to say this insertion is not a sequencing artifact.

Seven of the 17 sequences (15 California, two Florida) have been uploaded in the past 48 hours, so while numbers are far too small to draw any conclusions, it's at least possible this lineage is growing. 

I don’t know if there have been any other insertions in this region of spike previously in lineages with more than a few sequences. I don’t believe there have been any this year, though perhaps some exist that I’m just unaware of. I have no idea what effects an insertion like this would be expected to be, but I have to assume that since it occurs in an NTD region that has been a hotspot for mutations, it is likely to possess immune-evasion properties.

Experts in spike structure, do you have any thoughts on what the effects an insertion like this would be?
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15767138, EPI_ISL_15840517, EPI_ISL_15841024, EPI_ISL_15841619, EPI_ISL_15842277, EPI_ISL_15847278, EPI_ISL_15943531, EPI_ISL_15943931, EPI_ISL_15951856, EPI_ISL_15953080, EPI_ISL_16009159, EPI_ISL_16009752, EPI_ISL_16009841, EPI_ISL_16011923, EPI_ISL_16011938, EPI_ISL_16021081, EPI_ISL_16024875
</details>

**Comment by silcn** [comment]
@ryhisner insertions at S:247/248 are rare in BA.5 and its sublineages but appeared in BA.2 quite a few times. One such lineage was designated (BA.2.52, see #648) and there were various smaller ones too, including two with the exact same insertion as BA.2.52.

**Comment by ryhisner** [comment]
Three new sequences with Spike_ins248RWMD were uploaded yesterday and five more today, bringing the total to 25 sequences. Seven of these were from California and one from Texas.

**Comment by ryhisner** [comment]
The Spike_ins248RWMD lineage jumped to 44 sequences today. All 44 sequences have November collection dates. The very first sequence, collected Nov 2, was from Los Angeles County, California.

**Comment by ryhisner** [comment]
105 sequences now. Seems to be growing quickly.

**Comment by ryhisner** [comment]
The two most recently uploaded sequences from the Spike_ins248RWMD branch were from Shanghai, both from hospitalized people, one in their 20s and one in their 40s. EPI_ISL_16327608, EPI_ISL_16327650

**Comment by FedeGueli** [comment]
@corneliusroemer @thomasppeacock @InfrPopGen i think this should be prioritized.
I am monitoring it since it was proposed and it is doubling each 7/8 days with a 8 times doubling of 23 days. Although slower than XBB.1.5 it is in the leading pack and slighty faster than DN.1.1 or BQ.1.13.1 or BQ.1.1.26 recently designated.
The fact that now has been sampled in China, it is another reason to designate it.

**Comment by InfrPopGen** [comment]
Thanks for submitting. The umbrella lineage, without the insert, does not appear to have much of an advantage; however the sub-lineage does. So here is added, lineage BQ.1.28 with 51 newly designated sequences, and 0 updated. Defining mutations C25096T and ins_S:248:RWMD (following G6734A (ORF1a:V2157I)).

**Comment by AnonymousUserUse** [comment]
I wonder whether Nextclade and other lineage assignment tool can distinguish this lineage successfully. 
Since deletions and insertions are masked in Nextclade, there is only one synonymous homoplasic mutation (C25096T) to distinguish BQ.1.28 and its nearest parental branch (BQ.1 + C44T, A1777G, G6734A, C20429T, G25595T, T29492C), and there are six mutations (listed above) between its nearest parental branch to the designated parental lineage. Thus, I am afraid that a high number of sequences in the branch BQ.1 + C44T, A1777G, G6734A, C20429T, G25595T, T29492C will be misassigned as BQ.1.28.
Concerning the high number of sequences in the branch BQ.1 + C44T, A1777G, G6734A, C20429T, G25595T, T29492C, reaching 5% in California, I suggest to reassign BQ.1.28 as BQ.1 + C44T, A1777G, G6734A, C20429T, G25595T, T29492C and then assign BQ.1.28.1 as BQ.1 + C44T, A1777G, G6734A, C20429T, G25595T, T29492C + C25096T, ins22303TCAAGATGGATG.
See also: https://github.com/nextstrain/nextclade/issues/966; https://github.com/nextstrain/nextclade/issues/1045
