### ISSUE TITLE
BQ.1.8 with additional mutations ORF1ab:D6543N, Nuc:C18828T in Peru

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#1416]
BQ.1.8 with additional mutations ORF1ab:D6543N, Nuc:C18828T by Group of Genomic Surveillance INS-PERU

**Description**
Sub-lineage of: Potential new sub-lineage of BQ.1.8
Earliest sequence: hCoV-19/Peru/LIM-INS-33700/2022 (04/11/2022, Peru)
Most recent sequence: hCoV-19/Peru/LIM-INS-32443/2022 (12/11/2022, Peru)

**Countries circulating**
Peru (3)

This potential BQ.1.8 is distributed in Lima, Peru.

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/10176996/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28b5d_a2770.json?c=gt-nuc_18828,19891&label=id:node_8978540&tl=country

<img width="1477" alt="usher_bq 1 8" src="https://user-images.githubusercontent.com/87997149/206208953-9c355369-be8a-484d-9489-89fbd4412833.png">

<img width="1286" alt="bq 1 8" src="https://user-images.githubusercontent.com/87997149/206208971-b6139455-73ba-4937-86dd-b9fc874ba5d7.png">

**Proposed sub-lineage name**
BQ.1.8.X

**Comment by Wen1953** [comment]
20 seqs, all from Lima, Peru.

![image](https://user-images.githubusercontent.com/89021119/208446506-dcf86f47-4393-4390-8d5d-258addf67ed1.png)

**Comment by InfrPopGen** [comment]
Thank you for proposing this as a lineage. As this has grown very slowly and has shown a growth disadvantage relative to its parent over the past two months in Peru, this can be closed for now. Please re-propose or request reopening should this lineage show a marked advantage in the future.
