### ISSUE TITLE
BN.1.4 Sublineage with S:G261V, S:T678I, ORF3a:I37T, ORF3a:P240S, ORF8:D75G, & ORF1a:T4175I (80 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1417]
### **Description**
**Sub-lineage of:** BN.1.4
**Earliest sequence:** 2022-10-5, Scotland — EPI_ISL_15926883
**Most recent sequence:** 2022-11-23, Iceland — EPI_ISL_15983428, EPI_ISL_15971029
**Countries circulating:** Scotland (17), USA (4), Iceland (2), Germany (2), Australia (1), Ireland (1), Northern Ireland (1), Wales (1)
**Number of Sequences:** 29
**GISAID Query:** Spike_K356T, Spike_T678I, Spike_G261V, NS3_I37T
**CovSpectrum Query:** Nextcladepangolineage:BN.1.4* & S:G261V & S:T678I
**Substitutions on top of BN.1.4:**
**Spike:** G261V, T678I
**ORF3a:** I37T, P240S
**ORF8:** G75D
**ORF1a:** V3367I, T4175I (NSP5_V104I, NSP9_T35I)
**ORF1b:** T284I (NSP12_T275I)
**Nucleotide:** A10132T, T11773C, C12789T, G10364A, C14318T, G22344T, C23595T, T24850C, T25502C, C26110T, A28117G
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BN.1.4%20%2B%20G261V%2C%20T678I%2C%20ORF3aI37T%2C%20ORF3aP240S%2C%20ORF8D75G%2C%20etc%20-%20%20subtreeAuspice1_genome_39dd0_b0e70.json  
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/33738461/206226646-a0823af8-8e11-42c2-a159-c0521d1e9d5e.png">
 

**Evidence**
This is a pretty impressive saltation, particularly for such a relatively young lineage. S:T678I seems to be on the rise in a number of lineages. ORF3a is a major region for T-cell epitopes, so these may be immune-evasion mutations. ORF1a:T35I is one of the most convergent ORF1ab mutations in chronic-infection sequences, and it’s remarkable that the other two ORF1ab mutations here—which are not a part of the saltation but are shared with >150 other BN.1.4 sequences—are NSP5 and NSP12 mutations, the MPro and RdRp proteins.
 
The most recently uploaded sequence, from Wales, has S:T323I, ORF1a:H134R, and ORF1b:R1600L.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15713956, EPI_ISL_15713980, EPI_ISL_15758932, EPI_ISL_15811931, EPI_ISL_15837145, EPI_ISL_15854260, EPI_ISL_15878329, EPI_ISL_15878334, EPI_ISL_15878362, EPI_ISL_15905040, EPI_ISL_15909588, EPI_ISL_15909626, EPI_ISL_15909802, EPI_ISL_15909848, EPI_ISL_15918103, EPI_ISL_15926883, EPI_ISL_15926884, EPI_ISL_15926886, EPI_ISL_15960802, EPI_ISL_15971029, EPI_ISL_15971653, EPI_ISL_15974545, EPI_ISL_15983428, EPI_ISL_15989564, EPI_ISL_16011020, EPI_ISL_16011052, EPI_ISL_16011298, EPI_ISL_16024934, EPI_ISL_16028687
</details>

**Comment by Mydtlwn** [comment]
What is the role of the mutation at site 75?

**Comment by ryhisner** [comment]
@Mydtlwn, my guess is that the ORF8:G75D mutation plays no role at all. Stop codons that pretty much eliminate ORF8 have been really common—in Alpha, for example—and they don't seem to cause any disadvantage at all. It seems like SARS-CoV-2 could chuck ORF8 entirely without it causing any harm.

**Comment by Mydtlwn** [comment]
thx

**Comment by thomasppeacock** [comment]
Recommending this for assignment as i) its still clearly growing ii) its pretty widespread and iii) fairly clear evidence of a (mini) saltation

**Comment by FedeGueli** [comment]
74 seqs as today. i would like to highlight that S:678I was in a quite fast BA.5.1 sublineage that was not designated cause arose too late to compete with S:346Ters but it seemed fast enough to compete withOrf1b:1050N.
