### ISSUE TITLE
BA.5.2/CJ.1 recombinant or BM.1.1 sublineage with S:F486P and C1627T (not CJ.1), 46 samples from Denmark and 8 other countries

### ISSUE THREAD

**Issue by JosetteSchoenma** [cov-lineages/pango-designation#1418]
Description: Sub-lineage of BM.1.1 with S:F490S, S:F486P and C1627T or BA.5.2/CJ.1 recombinant
Nucleotide mutations: C1627T (and T23031C, T23018C)
Earliest sequence: 2022-10-07 from the Netherlands
Most recent sequence: 2022-122-02 from Australia
Countries circulating: Denmark 30, England and Norway 3, the Netherlands, Germany, Japan and USA 2, Sweden and Australia 1.
GISAID query: AA: Spike_F486P, NSP3_S403L Nuc.: C1627T
Covspectrum query:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AF486P&nucMutations=C1627T&nextcladePangoLineage=BM.1.1*&

Evidence:
Nextclade:
![image](https://user-images.githubusercontent.com/94831035/206474338-76744b7d-c030-4cc9-9ceb-6b4033ad22f4.png)

Usher tree:
The red dots in the branch with the black dots from uploaded samples are duplicates. the grey dots in the branch above are XBF.
![image](https://user-images.githubusercontent.com/94831035/206472714-b3b8bce0-aa45-4fbd-b49a-67d141ae0f4f.png)

Note:
Nextclade calls them CJ.1, while Usher calls them BM.1.1.1. I think both are incorrect, since CJ.1 do not have C1627T and BM.1.1.1 and CJ.1 do have G261A, while these samples do not.
I use NSP3_S403L in the GISAID query to distinguish them from XBF and C1627T to distinguish from CJ.1

EPI_ISL list:
EPI_ISL_15419587
EPI_ISL_15540509
EPI_ISL_15632647
EPI_ISL_15634582
EPI_ISL_15635386
EPI_ISL_15668070
EPI_ISL_15668080
EPI_ISL_15668216
EPI_ISL_15668510
EPI_ISL_15670264
EPI_ISL_15715737
EPI_ISL_15715859
EPI_ISL_15715968
EPI_ISL_15716150
EPI_ISL_15716243
EPI_ISL_15716489
EPI_ISL_15725177
EPI_ISL_15776105
EPI_ISL_15847358
EPI_ISL_15854335
EPI_ISL_15882238
EPI_ISL_15882590
EPI_ISL_15897767
EPI_ISL_15909912
EPI_ISL_15911390
EPI_ISL_15959210
EPI_ISL_15959263
EPI_ISL_15959767
EPI_ISL_15959905
EPI_ISL_15960161
EPI_ISL_15960291
EPI_ISL_15960415
EPI_ISL_15984211
EPI_ISL_16005400
EPI_ISL_16014538
EPI_ISL_16017667
EPI_ISL_16021134
EPI_ISL_16028628
EPI_ISL_16028662
EPI_ISL_16029057
EPI_ISL_16029467
EPI_ISL_16030088
EPI_ISL_16030106
EPI_ISL_16039576
EPI_ISL_16041149
EPI_ISL_16042824

Growth advantage:
I think it is a bit early to establish that, but designating it might make it easier to distinguish it from CJ.1. Also because it keeps popping up in different parts of the world.

**Comment by FedeGueli** [comment]
C1627 should make me think to a recomb wth a very tiny bit of BA.5.2, maybe?

**Comment by JosetteSchoenma** [comment]
I just remembered that these samples do not have G261A, like BM.1.1.1 and CJ.1 do, so I changed my issue.

@FedeGueli I think you could be right. I found 2 Dutch BA.5.2* from September and October that have C241T, T670G, C1627T and C2701T, like these samples do (and no G261A (red), like CJ.1), which means these samples could be BA.5.2/CJ.1 recombinants.

The orange CJ.1's in this Nextclade screenshot are the 2 Dutch possible BA.5.2/CJ.1 recombinants.
![image](https://user-images.githubusercontent.com/94831035/206588349-7e79ed0b-a4e6-4ed5-90d9-c23f8bad9d1d.png)

**Comment by FedeGueli** [comment]
Great analysis Josette!! definetely everything now points toward a recombination event happened in the Netherlands.

**Comment by JosetteSchoenma** [comment]
Thanks, @FedeGueli 
I just noticed a golden and green stripe that the Dutch CJ.1 do have and the recombinants do not. So I searched for CJ.1's without those mutations, which are A5006G and C8090T and found several in Belgium. Of course, Belgium is close to the Netherlands, so it might have been a joined venture.
On top are the  Dutch recombinants.
![image](https://user-images.githubusercontent.com/94831035/206668297-09f1aed4-0a12-4d98-a6c1-f081b5deb957.png)

**Comment by FedeGueli** [comment]
@JosetteSchoenma did u have a CJ.1 query that does not catch this recomb?

**Comment by JosetteSchoenma** [comment]
@FedeGueli I use Spike_F486P, NSP14_V182I, NSP3_S403L, G261A to find CJ.1 and it does not catch this recomb.

**Comment by JosetteSchoenma** [comment]
This is 194 samples now, from all over the world, but it is still called CJ.1 by Nextclade. Could you please change that, @corneliusroemer ?

It is growing fast in several places as well. In Denmark even close to how fast XBB.1.5 is growing.

**Comment by JosetteSchoenma** [comment]
XBK
