### ISSUE TITLE
BQ.1.1 Sublineage with S:P251L, S:N856S (~236 seq, Jan 22)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1419]
###  **Description**
**Sub-lineage of:** BQ.1.1
**Earliest sequence:** 2022-10-25, South Africa, Gauteng — EPI_ISL_15722271
**Most recent sequence:** 2022-11-26, USA, New York City — EPI_ISL_16001140
**Countries circulating:** USA (10), South Africa (7), Israel (2), Australia (1), Belgium (1)
**Number of Sequences:** 21
**GISAID Query:** Spike_P251L, Spike_R346T, Spike_N856S, NSP13_N268S
**CovSpectrum Query:** Nextcladepangolineage:BQ.1.1* & S:P251L & S:N856S
**Substitutions on top of BQ.1.1:**
**Spike:** P251L, N856S
**Nucleotide:** T7633C, C22314T, A24129G
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1.1%20%2B%20P251L%20%2B%20N856S%20-%20subtreeAuspice1_genome_35290_27df90.json  
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/33738461/206599570-c8a66739-8729-48b5-83ed-af632dcca0be.png">

**Evidence**
This lineage’s first sequence was collected on October 25, its second on November 4, yet it already has an impressive geographical spread, detected in South Africa, Israel, Belgium, Australia, and US states that span the country—including Hawaii. This is strikingly rapid geographical spread. It’s far too early to be able to accurately identify any growth advantage, but the early numbers are at least consistent with fast growth.

S:N856K was found in BA.1 but was subsequently not found in BA.2, BA.4, or BA.5. Most of the studies I’ve read attribute Omicron’s endosomal cell entry and decreased fusogenicity to S:N969K or S:H655Y. I don’t know what structural or functional role this residue plays, but it seems like it must be significant.
 
This is not the only lineage to recently evolve S:N856S, and its numbers seem to be increasing. According to CovSpectrum, which receives GISAID sequences a few days after they are uploaded, 15 different designated variants have had at least one sequence with S:N856S since October 15. From August 18 to October 8, there were only two sequences in the world with S:N856S, so this marks a distinct change.

It's also noteworthy that 12/21 sequence here—including seven of the nine most recently collected samples—also S:A701V and ORF1b:N2079S.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15722271, EPI_ISL_15827295, EPI_ISL_15830422, EPI_ISL_15912257, EPI_ISL_15944482, EPI_ISL_15945021, EPI_ISL_15946915, EPI_ISL_15963053, EPI_ISL_15963056, EPI_ISL_15963057, EPI_ISL_15963059, EPI_ISL_15976840, EPI_ISL_15978888, EPI_ISL_15994024, EPI_ISL_15997583, EPI_ISL_16001140, EPI_ISL_16001740, EPI_ISL_16019969, EPI_ISL_16020255, EPI_ISL_16047283, EPI_ISL_16049460
</details>

**Comment by ryhisner** [comment]
24 sequences of this were uploaded from South Africa today, bringing the total to 96. Given the low level of sequencing in South Africa and the surrounding countries in recent months, this lineage seems likely to be more prominent than the current number of sequences would suggest.

**Comment by ryhisner** [comment]
This lineage seems to make up a very high percentage of South African sequences. Of the 57 sequences uploaded from South Africa on January 13, 44% (25/57) were from this lineage. Many of them appear not to have S:P251L, but this is because a majority of sequences from South Africa have no coverage in that part of spike.

**Comment by FedeGueli** [comment]
This lineage has splitted in two main branches :
the upper one defined by S:A701V representing now 92 out of 150 sequences in uSher
and the bottom side domianted by South African sequences among them i would highlight a cluster of 4 sequences with S:A348S
<img width="1165" alt="Schermata 2023-01-15 alle 07 18 52" src="https://user-images.githubusercontent.com/87669813/212526039-ec242ada-b5e2-4cb8-97e9-88ccd5d301b7.png">

 i think it should be designated as fast as possible with its main sublineage @InfrPopGen @corneliusroemer

**Comment by FedeGueli** [comment]
200 sequences as today last doubling was 15days but it seems accelerating while being spread to countries outside SA.

in south africa it represents 23 viruses out of 161 samples collected in 2023 , suuggesting  a prevalence around 15% there.

I suggest to designate this one rapidly. @InfrPopGen @thomasppeacock @corneliusroemer

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.1.38 with 111 newly designated sequences, and 0 updated. Defining mutation A24129G (S:N856S) (following T7633C).
