### ISSUE TITLE
BQ.1.1 with S:K356R [5 seq, 3x Spain, 2x Denmark as of 2022-12-09]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1420]
I found a BQ.1.1 with S:K356R, 5 seq as of 2022-12-09,  3x Spain, 2x Denmark

It's on the BQ.1.1 branch with 16120A

Gisaid query: `Spike_R346T,Spike_K444T,Spike_K356R` `16120A`

Too small and too slow apparent growth for immediate designation - let's watch.

<img width="2143" alt="image" src="https://user-images.githubusercontent.com/25161793/206621401-67c79bed-f3aa-4840-8a13-4be6e08d32b8.png">

https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3d309_2b23d0.json?branchLabel=Spike%20mutations&label=id:node_6415304

<img width="734" alt="image" src="https://user-images.githubusercontent.com/25161793/206621430-c8589392-42b3-4c48-9758-9c590aa745ee.png">

**Comment by InfrPopGen** [comment]
Since December 2022 this appears to have gained 3 more sequences, and only one within the past two months. Consequently, it can be closed for now.
