### ISSUE TITLE
CH.3 sublineage with S:494P [13 sequences. Australia, Indonesia]

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1421]
**Description**
Sub-lineage of: CH.3
Earliest sequence: 2022-11-08, Australia -- West Australia -- EPI_ISL_15938494
Latest sequence: 2022-11-22, Australia -- West Australia -- EPI_ISL_16004311
Countries circulating: Australia (6), Indonesia (1)
Number of Sequences: 7
GISAID Query: Spike_R346T,Spike_F486P, Spike_S494P,-Spike_F490S
CovSpectrum Query: s:486p & s:494p & s:346t & s:490f
Substitutions on top of CH.3:
Spike: S494P
Nucleotide: T23042C, and in 5/7 sequences, C9679T

**USHER Tree**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39d0_2b87a0.json?c=gt-S_494&label=id:node_2424922
![image](https://user-images.githubusercontent.com/94097102/206626032-d69e6f85-94eb-4568-8630-f999e548d4ba.png)

**Evidence**
This spike protein is BA.2.75 with S:346T, S:486P, S:494P -- 3 additional convergent RBD mutations.

Additionally, this spike shows some convergence with BA.2.10.4. Their RBD from S:461 onwards is identical, meaning that they both have S:486P, S:493Q, S:494P, and no other mutations in this region. 

Notably, in the USHER tree in the image, there is only 20 sequences descending from CH.3, but two of those sequences have S:494T as well.  

In general, S:494P has not shown that much prevalence within BA.2.75*, and has not been particularly successful on larger sublineages such as BN.1.1. So, I think the neutral assumption might be that this proposed sublineage ends up being equivalent to or somewhat less fit than CH.3 (BA.2.75 spike with S:346T and S:486P). If the proposed sublineage is actually more successful then I think it should be considered that there is possibly some interaction between S:486P and S:494, at least on a BA.2.75 spike. 

**Genomes:**
EPI_ISL_16004165, EPI_ISL_16004170, EPI_ISL_16004233, EPI_ISL_16004311, EPI_ISL_16004302, EPI_ISL_15826757, EPI_ISL_15938494

**Comment by FedeGueli** [comment]
Thx @asinickle i think this is a sublineage of CH.3 , i mentioned there the first two sequences with S:494P, but great you proposed it!

https://github.com/cov-lineages/pango-designation/issues/1375#issuecomment-1331460674

**Comment by Sinickle** [comment]
Thanks for the correction @FedeGueli! 
I've updated my post accordingly. I should have known that you'd be on top of branches with S:486P!

**Comment by FedeGueli** [comment]
@Sinickle thanks to you for tracking this. Always a good thing to be more than one on things!
