### ISSUE TITLE
BF.7.5.1 (BF.7+S:Y144del+S:G181V+M:H155Y, etc) Sublineage with S:L212F, S:G446S, S:D1084E, ORF1b:D144Y (19 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1422]
### **Description**
**Sub-lineage of:** BF.7.5.1
**Earliest sequence:** 2022-11-10, Switzerland — EPI_ISL_15802362, EPI_ISL_15802396, EPI_ISL_15802424
**Most recent sequence:** 2022-11-25, Switzerland — EPI_ISL_15966310
**Countries circulating:** Switzerland
**Number of Sequences:** 18
**GISAID Query:** Spike_L212F, Spike_G181V, Spike_R346T, Spike_G446S, Spike_D1084E
**CovSpectrum Query:** Nextcladepangolineage:BF.7.5.1* & S:L212F & S:G446S & S:D1084E
**Substitutions on top of BF.7.5.1:**
**Spike:** L212F, G446S, D1084E
**ORF1b:** D144Y (NSP12_D153Y)
**Nucleotide:** C1648T, G13897T, C17304T, A22198T, G22898A, T24814A
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BF.7.5.1%20%2B%20L212F%2C%20G446S%2C%20D1084E%20%2B%20ORF1bD145Y%20-%20subtreeAuspice1_genome_753_331010.json 
![image](https://user-images.githubusercontent.com/33738461/206753373-02a68f84-f3fc-46e8-9707-7bd682b6c6da.png)

**Evidence**
BF.7.5.1 is already something of an outlier among BF.7 sublineages; it has more AA mutations than any other BF.7 sublineage with five. Two of those—S:Y144del, S:G181V—are convergent NTD mutations, the former a potent antibody-evasion mutation according to Yunlong Cao & co-authors in their preprint “Imprinted SARS-CoV-2 humoral immunity induces convergent Omicron RBD evolution.” https://www.biorxiv.org/content/10.1101/2022.09.15.507787v4

![image](https://user-images.githubusercontent.com/33738461/206754334-a2770900-62a0-44dd-8043-dcf2db0184c9.png)

S:G446S is one of the most well known escape mutations and speaks for itself. 
 
The spike region spanning AA residues 209-215 has been a mutational hotspot, particularly in Omicron lineages, with BA.1 possessing S:N211del + S:L212I and BA.2, BA.4, & BA.5 having S:V213G. BA.2.75 has S:I210V in addition to S:V213G. Furthermore, mutations and deletions in this region have repeatedly emerged independently in singlets and lineages, most recently in BN.1.7 (Issue #), which has a deletion and two substitutions at S:210-212. There have even been many sequences with a second nucleotide mutation at S:213 (primarily S:G213R and S:G213W). All of this indicates that the S:210-215 region is likely a target of likely antibodies.  
 
S:L212F, however, has been rare. According to CovSpectrum, apart from this lineage, it has been found in <45 legit sequences during the entire pandemic.  The nucleotides at S:212 are TTA (T22196, T22197, A22198), which places limits its one-nuc mutational possibilities two of the three possible mutations at T22197 lead to stop codons while the most common nucleotide mutation at T22196 (T->C) is synonymous. That leaves T22197C, which leads to S:L212S, as the only non-rare nucleotide change that isn’t synonymous and doesn’t create a stop codon. S:L212I was found in BA.1, but this was caused by an out-of-frame deletion, not a nucleotide substitution. S:L212F requires either an A->T or A->C substitution, both of which are relatively uncommon, making up 2.69% and 2.76%, respectively, of nuc substitutions in SARS-CoV-2, so this may partially explain why it has been rarely seen. (Figures based on the adjusted numbers by Richard Neher found here: https://github.com/neherlab/SC2_variant_rates/blob/master/data/mutation_rates.tsv)

I do not know whether S:D1084E is functionally significant, but it's worth noting that it is caused by the 3rd-rarest nucleotide substitution, T->A, which makes up just 2.06% of all nuc substitutions.

![image](https://user-images.githubusercontent.com/33738461/206754438-c13f078e-1783-45ca-b809-316b1fa9d4d8.png) 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15802362, EPI_ISL_15802396, EPI_ISL_15802424, EPI_ISL_15897973, EPI_ISL_15897978, EPI_ISL_15897980, EPI_ISL_15897993, EPI_ISL_15898003, EPI_ISL_15898008, EPI_ISL_15898028, EPI_ISL_15898029, EPI_ISL_15966201, EPI_ISL_15966276, EPI_ISL_15966298, EPI_ISL_15966301, EPI_ISL_15966310, EPI_ISL_15991949, EPI_ISL_16047899
</details>

**Comment by silcn** [comment]
S:D1084E is shared with that weird Chilean BF.31 saltation cluster (#1380), so it may well have some function though presumably not a very significant one.

**Comment by alurqu** [comment]
BF.7.5.1 also has that minimal TRS-B formed by C2399A which could be generating an additional sgmRNA.

**Comment by ryhisner** [comment]
Only a few more of these have showed up since the first batch was uploaded so I'm closing.
