### ISSUE TITLE
BQ.1.1 sublineage with S:484T, S:252D, ORF7a:P99L [4 sequences, France]

### ISSUE THREAD

**Issue by plomano** [cov-lineages/pango-designation#1423]
### **Description**
**Sub-lineage of:** BQ.1.1
**Earliest sequence:** 2022-11-15, France - Auvergne-Rhône-Alpes - EPI_ISL_15970313
**Latest sequence:** 2022-11-16, France - Auvergne-Rhône-Alpes - EPI_ISL_15970361
**Countries circulating:** France (4)
**Number of Sequences:** 4
**GISAID Query:** Spike_N460K, Spike_K444T, Spike_R346T, Spike_G252D, Nsp13_N268S, Spike_E484T
**CovSpectrum Query:** S:460K & S:444T & S:346T & S:484T & S:252D & ORF1b:N1191S

**Substitutions on top of BQ.1.1:**
**Spike:** G252D, E484T
**ORF7a:** P99L
**Nucleotide:** G22317A, G23012A, C27689T

### USHER Tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2a38f_3ed5f0.json?f_userOrOld=uploaded%20sample
![UO0001](https://user-images.githubusercontent.com/115512395/206826804-b3be306d-fe33-4b45-aa78-8d4f0ebb639c.jpg)

### Evidence

A double nucleotide mutation, 484T is at a location that is one of the more well known sites of evolution. In referencing Bloom Labs escape calculator and RBD heatmaps, 484T gives a moderate amount of escape, and a small increase in RBD expression and ACE2 affinity. This mutation seems to have little downside and seems like a natural evolution for BQ.1.1. However epistatic effects involving 484A may be disrupted with this change.

252D is an NTD mutation that has shown up multiple times recently, and may be related to antibody escape or structural changes. ORF7a:P99L is in a region that has been known to antagonize the IFN-I response, possibly contributing to immune evasion. There is also a 5th sequence with 484T from France that does not seem to cluster: EPI_ISL_15856610

There are still only a handful of sequences in one country, so I would request this be monitored to see if future sequences show increased numbers and geographical spread.

### Genomes:
EPI_ISL_15970337
EPI_ISL_15970313
EPI_ISL_15970361
EPI_ISL_15970352

**Comment by FedeGueli** [comment]
no new sequence popped up for this. France is not new to interesting lineaage popping up and then disappearing. Nice catch anyway.

**Comment by plomano** [comment]
> 

Good practice for my first one at least! 😬

Closing it down then.
