### ISSUE TITLE
BA.2.75* x BQ.1* x BA.2.75* recombinant [37 seqs, many countries, continents]

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1425]
**Description**
Recombinant between: BA.2.75* and BQ.1* 
Earliest sequence: 2022/11/20 (Japan-Fukushima)
Most recent sequence: 2022/11/23 (Japan-Fukushima, Australia-Sydney)
Countries circulating: Japan-Fukushima (3/6),  Malaysia-Selangor (2/6), Australia-Sydney (1/6),
Potential breakpoint: Spike NTD (22577, 22893) and (25416, 26275)
GISAID & CovSpectrum Query: C11124T, T13324C, T22942A, A26275G

Mutations that are not found in most of these parental sequences...
NT: C5192T,C11124T,T13324C,G18583A
ORF1a:A3620V
ORF1b:V1706I

Functionally, this is a BA.2.75 that gained S:346T, S:444T, S:452R, S:486V from BQ.1.1

**Usher Tree**

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6023_4ecdc0.json?label=id:node_2426506
![image](https://user-images.githubusercontent.com/94097102/206874861-cebffbe8-ac00-48cf-bbd6-c4aa029f5e99.png)

**Evidence**
The NT query "C11124T,T13324C,G18583A" returns 11 sequences for me as of 12/10. 6 are my proposed recombinant lineage, and 5 are BA.2.75.2 from Japan, France, Scotland. The oldest sequence is EPI_ISL_15599900, in Tokyo from 10/8. The last one is 11/17 in France and Scotland. Although none of these 5 are a perfect parent to my proposed recombinant, there is no mutation that is on 100% of them and not on my proposed recombinant. So, it seems plausible that the BA.2.75 donor for my recombinant is very closely related to those 5 sequences which are currently circulating. If this is the case, it means the S:346T most likely came from the BA.2.75 side.
If I consider these to be the parent rather than just BA.2.75*, then this lineage has **no private mutations**

This lineage is likely very fit, since it is basically just CH.1.1 but with S:486V instead of S:486S, and without the S:G446S mutation. 

There is already some genetic diversity amongst the sequences in this recombinant lineage, but I will wait for more sequences to come in before looking further into that. 

**Genomes**
EPI_ISL_16059015, EPI_ISL_16051178, EPI_ISL_16039683, EPI_ISL_16039622, EPI_ISL_15963046, EPI_ISL_15955402

**Comment by FedeGueli** [comment]
Old format gisaid query .  NSP6_A51V,NSP14_V182I,Spike_F486V

**Comment by FedeGueli** [comment]
9 sequences as today 2 more from japan and one from Malaysia where likely this Recomb lineage arose.
@Sinickle

**Comment by FedeGueli** [comment]
My query NSP6_A51V,NSP14_V182I,Spike_F486V finds 12 of this

**Comment by JosetteSchoenma** [comment]
@FedeGueli 's query also catches the Dutch one I noticed this morning. Thanks Saka.
EPI_ISL_16200084

**Comment by FedeGueli** [comment]
two new sequences popped up from Thailand and Malaysia today. my query finds 14 viruses.

**Comment by FedeGueli** [comment]
My query finds now 17 sequences

**Comment by FedeGueli** [comment]
19 last one from Thailand

**Comment by FedeGueli** [comment]
@Sinickle this two unrelated sequences are shown also in the tree of the last @c19850727 proposal #1543 !

see:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f44_e846a0.json?c=userOrOld&label=id:node_7958850
![Schermata 2023-01-11 alle 10 47 11](https://user-images.githubusercontent.com/87669813/211773160-0b4286d8-0e6f-42d7-9a10-5336ce789b50.png)

**Comment by Sinickle** [comment]
18th sequence is Singapore, but notes travel history: Italy

**Comment by FedeGueli** [comment]
21 as today

**Comment by corneliusroemer** [comment]
Slow but widely travelled, hmm... Not clear this should be designated (yet). Shall we wait a bit more? Where are we at now? 25? Maybe designate at ~50?

**Comment by FedeGueli** [comment]
> Slow but widely travelled, hmm... Not clear this should be designated (yet). Shall we wait a bit more? Where are we at now? 25? Maybe designate at ~50?

22 as today with  C11124T, T13324C, T22942A, A26275G

**Comment by Sinickle** [comment]
Honestly might want to wait to be able to determine if the related sequences I posted might need to be designated 

My proposed lineage has 2 breakpoints-- I think the related sequences represent the first breakpoint only. The proposed lineage might be a recombinant of those related sequences.

**Comment by FedeGueli** [comment]
> Honestly might want to wait to be able to determine if the related sequences I posted might need to be designated
> 
> My proposed lineage has 2 breakpoints-- I think the related sequences represent the first breakpoint only. The proposed lineage might be a recombinant of those related sequences.

yeah i forgot those two (still 2?)

**Comment by Sinickle** [comment]
First sequence from Israel uploaded today. 
None of the other lineage since Jan 26, which is still at just 3 sequences only in Singapore.

**Comment by Sinickle** [comment]
The other lineage (C11124T, T13324C, T22942A, G21893A) is now at 4 sequences, having shown up in the USA, Illinois.

**Comment by Sinickle** [comment]
The proposed lineage is up to 26 sequences, newly in New Zealand. 

The other lineage (C11124T, T13324C, T22942A, G21893A) is now at 8 sequences, having shown up in England.

**Comment by Sinickle** [comment]
#1674 has been opened for the other lineage I've been mentioning. 
@agamedilab do you agree that it looks like my proposed lineage is a recombinant of the one you've proposed?

**Comment by corneliusroemer** [comment]
Designating this as XBU it seems to be or have been common in an undersampled region.

It's not clear where the S:R346T comes from - could be either the BA.2.75.3 side (in which case it could be BM.2) or the BQ.1 side, in which case it could be one of the many BQ.1 or BQ.1.1 with 346T.

I think the original description is wrong in that it omits the loss of 446S (common to BA.2.75) - which could be due to Usher masking that site (hence the loss is not evident).

**Comment by FedeGueli** [comment]
> I think the original description is wrong in that it omits the loss of 446S (common to BA.2.75) - which could be due to Usher masking that site (hence the loss is not evident).

It has been mentioned twice! , the loss was via recomb with BQ.1 RBD with breakpoint just before and after it and also at the end of the main  post
>"...This lineage is likely very fit, since it is basically just CH.1.1 but with S:486V instead of S:486S, and without the S:G446S mutation...."

**Comment by JosetteSchoenma** [comment]
XBU
