### ISSUE TITLE
BQ.1.1 sublineage with Orf8:V62L and  S:S691F  emerged in Brazil - 436 sequences, with a sublineage with S:R765S - 89 seqs and S:M153T 57 seqs

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1426]
I was routinely checking South American sequences when i noticed in BQ.1.1  a FCS related mutation : S:S691F.
Digging a bit i fixed a Gisaid Query : NS8_V62L,Nsp13_N268S,Spike_S691F that finds 65 viruses clustering into a lineage that  likely emerged early in october in Brazil looking at first sequence from Bahia : EPI_ISL_16006496 .
Just 13 out of 65 sequences have been sampled outside Brazil

Defining mutations:  BQ.1.1 + ORF1b:N1191S( A17039G) > Orf8:V62L (G28077T) > S:S691F (C23634T)

Tree:
<img width="1167" alt="Schermata 2022-12-11 alle 17 11 08" src="https://user-images.githubusercontent.com/87669813/206914854-930982c9-4347-4c85-9e6c-506a8c6a6640.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a7b5_5fc520.json?c=gt-S_691&label=id:node_6426816

As can easily be spotted looking at the tree posted below this sublineage has further acquired 
Spike_R765S 
(15 sequences with Spike_R765S,NS8_V62L,Nsp13_N268S,Spike_S691F )
and then Spike_M153T  ( 9sequences with Spike_M153T,Spike_R765S,NS8_V62L,Spike_S691F ) 
<img width="1149" alt="Schermata 2022-12-11 alle 17 16 34" src="https://user-images.githubusercontent.com/87669813/206915194-7818e290-9f91-4561-ad8e-40c846746d85.png">

<details>
<summary>Expand for EPI_ISLs</summary>
EPI_ISL_15883445, EPI_ISL_15883450, EPI_ISL_15883452,
EPI_ISL_15883459, EPI_ISL_15883467, EPI_ISL_15883469,
EPI_ISL_15883471, EPI_ISL_15883474, EPI_ISL_15883489,
EPI_ISL_15909762, EPI_ISL_15918739, EPI_ISL_15932857-15932858,
EPI_ISL_15932861, EPI_ISL_15932865, EPI_ISL_15932872-15932874,
EPI_ISL_15932879, EPI_ISL_15932894, EPI_ISL_15935221,
EPI_ISL_15948628, EPI_ISL_15963344, EPI_ISL_15971541,
EPI_ISL_15974591, EPI_ISL_16002585, EPI_ISL_16006496,
EPI_ISL_16006498, EPI_ISL_16006509, EPI_ISL_16006518,
EPI_ISL_16006523, EPI_ISL_16006532, EPI_ISL_16006536,
EPI_ISL_16006859, EPI_ISL_16007424, EPI_ISL_16007729,
EPI_ISL_16007766, EPI_ISL_16007787, EPI_ISL_16007797,
EPI_ISL_16007809, EPI_ISL_16007811, EPI_ISL_16007825,
EPI_ISL_16007844, EPI_ISL_16007880, EPI_ISL_16008002,
EPI_ISL_16008011, EPI_ISL_16008014, EPI_ISL_16008027,
EPI_ISL_16008030, EPI_ISL_16008033, EPI_ISL_16010689,
EPI_ISL_16010765, EPI_ISL_16017932, EPI_ISL_16020891,
EPI_ISL_16022394, EPI_ISL_16022398, EPI_ISL_16022400,
EPI_ISL_16022427, EPI_ISL_16026526, EPI_ISL_16050747,
EPI_ISL_16050782, EPI_ISL_16050803, EPI_ISL_16050849,
EPI_ISL_16060843, EPI_ISL_16065934
</details>

CovSpectrum query: **T22942A + S:S691F, ORF8:V62L**
 https://cov-spectrum.org/explore/Brazil/AllSamples/Past3M/variants?aaMutations=S%3AS691F%2COrf8%3Av62L&nucMutations=22942A&nextcladePangoLineage1=BQ.1.1*&

**Comment by ryhisner** [comment]
S:R765X mutations are a real enigma. They used to occur all the time in chronic cases as well as in singlets scattered all over the phylogenetic tree, but I don't believe it's ever been found in any noteworthy lineages. No one substitution has predominated either, though S:R765S has been the least common of the five major ones: L, C, H, G, and S. 

Just noticed this oddball S:R765F mutation in a BQ.1.13 (S:F157L) from the Czech Republic, collection date November 28. EPI_ISL_16046927
<img width="962" alt="image" src="https://user-images.githubusercontent.com/33738461/206945632-5e3174d5-2566-4c2d-a011-1cdca16fd764.png">

**Comment by FedeGueli** [comment]
Thx @ryhisner !

**Comment by FedeGueli** [comment]
71 seqs as today newly found in Argentina, Florida, Texas, North Carolina and  Illinois

**Comment by FedeGueli** [comment]
77 sequences as today and 13 for the sublineage with a  further double Spike Mutation

**Comment by oobb45729** [comment]
> S:R765X mutations are a real enigma. They used to occur all the time in chronic cases as well as in singlets scattered all over the phylogenetic tree, but I don't believe it's ever been found in any noteworthy lineages. No one substitution has predominated either, though S:R765S has been the least common of the five major ones: L, C, H, G, and S.
> 
> Just noticed this oddball, 2-nuc S:R765F mutation in a BQ.1.13 (S:F157L) from the Czech Republic, collection date November 28. EPI_ISL_16046927 <img alt="image" width="962" src="https://user-images.githubusercontent.com/33738461/206945632-5e3174d5-2566-4c2d-a011-1cdca16fd764.png">

R765 and Q957 have an inter-protomer interaction. All of those mutations would likely weaken it.
Also there is BF.7.12 (A942S) with R765L may be doing something in Iceland.

**Comment by FedeGueli** [comment]
166 sequences of the bigger lineages while its sublineages with S:R765S reached 32 , and 21 of them have also S:M153T

**Comment by FedeGueli** [comment]
205 sequences for the bigger lineage while the S:765S reached 43 sequences and the S:M153T reached 28seqs.

This is the prevalence of various local variants in Brazil
The bigger lineage vs BE.9/BE.10/DL.1
<img width="909" alt="Schermata 2023-01-01 alle 18 45 17" src="https://user-images.githubusercontent.com/87669813/210180091-6b999781-e36c-4122-9d49-67486b4ff9ea.png">

The small lineage vs BE.9/BE.10/DL.1
<img width="780" alt="Schermata 2023-01-01 alle 18 43 59" src="https://user-images.githubusercontent.com/87669813/210180060-abc69c2d-b828-4241-8da0-742a32a40e46.png">

In my view it makes sense designate this one to better track things there.

**Comment by FedeGueli** [comment]
226 sequences and it keeps growing. today 10 sequences of its sublinegae with additional S:765S +S:M153T have been uploaded from Brazil.
I would like to highlight that competition in Brazil actually is very high cause there are also DL.1.1 BE.9 BE.10 circulating widely
<img width="799" alt="Schermata 2023-01-05 alle 00 08 14" src="https://user-images.githubusercontent.com/87669813/210666973-68b30b1a-b18b-4291-956d-e2eb1d4bfd57.png">

@thomasppeacock

**Comment by FedeGueli** [comment]
This reached 269 with ongoing transmission in Brazil-

**Comment by FedeGueli** [comment]
319 sequences, sampled in Argentina where it is around 1% of samples after Dec 1st

**Comment by FedeGueli** [comment]
@InfrPopGen @corneliusroemer This one with its sublineage and sub-sublineage never stopped growing and it is now circualting outside Brazil.

**Comment by FedeGueli** [comment]
436 sequences. i keep this open cause despite slowing down it is still circulating

**Comment by FedeGueli** [comment]
@InfrPopGen @corneliusroemer could you take a look at this one please?

It has keeping spreading in South America with samples from Argentina Chile and internationally being sampled in Usa, Australia, Germany,
Its  sublineage of this with S:R765S , a mutation we saw recurrently in heavy mutated sequences as @ryhisner could tell better tha me, 
reached 89 sequences and its sub sublineage with S:R765S and S:M153T reached 57 seqs.

<img width="1167" alt="Schermata 2023-02-06 alle 11 58 56" src="https://user-images.githubusercontent.com/87669813/216954678-598a2ed6-027f-4844-af7c-f93360736608.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40fa8_dd270.json?c=country&label=id:node_6377487

**Comment by FedeGueli** [comment]
@corneliusroemer i have see your amazing BQthatlon , what do you think about this one? should i close it? in my view it is quite interesting even if  it cant compete vs top lineages, it has a fcs (proximity) mutation, then its sublineage gained an interesting mutation 765S. please qhen u have time next time take a look and eventually close it directly!

**Comment by corneliusroemer** [comment]
It feels like I've seen and designated this... Let me check

**Comment by FedeGueli** [comment]
U re right @corneliusroemer i ve missed it ;) thank you!
