### ISSUE TITLE
BQ.1.1.26 (S:E471Q, ORF3a:Y107C) Sublineage with S:Y144del, S:N185T (80 seq, Jan 4)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1427]
### **Description**
**Sub-lineage of:** BQ.1.1.26
**Earliest sequence:** 2022-11-7, USA, Illinois — EPI_ISL_15893140
**Most recent sequence:** 2022-12-3, Denmark — EPI_ISL_16062199
**Countries circulating:** Denmark (17), Austria (2), Canada (1), Spain (1), England (1), USA (1)
**Number of Sequences:** 23
**GISAID Query:** Spike_Y144del, Spike_N185T, Spike_E471Q, NSP12_Y273H
**CovSpectrum Query:** Nextcladepangolineage: BQ.1.1.26* & S:N185T
**Substitutions on top of BQ.1.1.26:**
**Spike:** N185T
**Nucleotide:** A22116C
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1.1.26%20(E471Q)%20%2B%20N185T%20-%20subtreeAuspice1_genome_23b1a_675790.json
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/33738461/206940631-26a44b5b-0096-4bfa-bbc7-88fc44efdc76.png">

 
**Evidence**
The S:176-187 region—and particularly S:181-185—has been a mutational hotspot for many months now. This coincides with the protruding N4 loop of the NTD, which John M. Errico, Lucas J. Adams, and Daved H. Fremont, in their excellent review “Antibody-mediated immunity to SARS-CoV-2 spike,” identify as spanning spike residues 177-186 (as pictured below). The NTD loops are clearly antigenically important. The other four NTD loops (N1, N2, N3, and N5) have all been frequent sites of deletions in different variants, but N4 seemingly does not tolerate deletions. Instead, starting sometime in summer 2022, substitutions have become frequent across N4. https://pubmed.ncbi.nlm.nih.gov/36038194/
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/33738461/206940720-8b0e7cd5-4906-4e6a-9628-9047ffedfae4.png">
 
None of these substitutions seem to confer the kind of dramatic increase in fitness we see with recent RBD mutations like S:N460K and S:K444X, but they presumably help evade antibodies targeting the N4 loop. The continual independent evolution of spike mutations in this area suggests these mutations modestly increase fitness, most likely through immune-evasion.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15893140, EPI_ISL_15936940, EPI_ISL_15939459, EPI_ISL_15959307, EPI_ISL_15971571, EPI_ISL_15971574, EPI_ISL_15971972, EPI_ISL_15972187, EPI_ISL_15972197, EPI_ISL_16005805, EPI_ISL_16008157, EPI_ISL_16028887, EPI_ISL_16029351, EPI_ISL_16032747, EPI_ISL_16043625, EPI_ISL_16052421, EPI_ISL_16062199, EPI_ISL_16062239, EPI_ISL_16062912, EPI_ISL_16063074, EPI_ISL_16063333, EPI_ISL_16063408, EPI_ISL_16063488
</details>

**Comment by ryhisner** [comment]
The number of sequences in this lineage has doubled over the past five days, from 23 to 46.

**Comment by corneliusroemer** [comment]
The 2 extra mutations are interesting, but since this is now the major part of BQ.1.1.26 I don't think there's much need to designate at this point unless this lineage grows a lot, otherwise we just end up with more aliases.

<img width="2156" alt="image" src="https://user-images.githubusercontent.com/25161793/211231579-f75941c9-4219-48f6-a91e-0cb9e1dc72a0.png">

185 occurs in 80% of BQ.1.1.26 by now!

**Comment by InfrPopGen** [comment]
Thanks for proposing this lineage. As it has not shown marked growth over BQ.1.1.26, and is negative in Europe over the past two months, this can be closed for now. It also represents ~ three quarters of BQ.1.1.26.
