### ISSUE TITLE
XBB.1 sublineage with S:L216F (38 seqs from USA-CA, England, Australia, India)

### ISSUE THREAD

**Issue by emily-smith1** [cov-lineages/pango-designation#1428]
### Description
**Sublineage of:** XBB.1
**Earliest sequence**: 2022-10-05, India - EPI_ISL_15573093
**Most recent sequence:** 2022-11-25, USA - EPI_ISL_16049147
**Countries circulating:** USA, England, India, Australia
**GISAID Query:** Spike_V83A, Spike_F486S, Spike_F490S,Spike_G252V,Spike_L216F

I’m proposing this lineage with only 38 sequences due to quick spread, particularly in USA-CA. The California sequences are mostly on their own branch with ORF1a:H2520Q & S:H146K. UShER labels that Spike mutation S:H146**N** instead of S:H146**K** (I’m assuming because it’s 2 nucleotide changes for H->K).  

### Evidence

**UShER link**: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c526_67b930.json
![image](https://user-images.githubusercontent.com/84812104/206940778-cf12ec65-637a-4c87-b654-2a169a6cbf08.png)

**Mutations:**
![image](https://user-images.githubusercontent.com/84812104/206940457-cc5eb61f-2c6b-492b-a0a4-ba8968e3d45f.png)

**Comment by emily-smith1** [comment]
56 genomes in the UShER tree as of 2022-12-15. Newly found in Mexico, although those two genomes have multiple reversions. 

UShER link: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ee74_b77a70.json
![image](https://user-images.githubusercontent.com/84812104/207952042-7ea43033-2232-4fb3-b5a5-6260eb090e63.png)

**Comment by corneliusroemer** [comment]
Designated as XBB.1.6 starting from S:H146K due to that branch being very dominant.

Otherwise we'd have XBB.1.6.1 and XBB.1.6 would likely never go anywhere. Trying to keep names shorter ;)
