### ISSUE TITLE
Potential New Lineage with Spike T95I, R158S, N440K, E484Q, P681H,A688V,S735A

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#143]
Description
Sub-lineage of: B.1
Clade: 20C
Country: USA, Mexico
Earliest sequence: 2021-05-13
Most recent sequence: 2021-06-16

Defining mutations in Spike:
T95I
R158S
N440K
E484Q
D614G
P681H
A688V
S735A
N960N
T1027I

GISAID reference list is added to the first comment

**Comment by shay671** [comment]
[GisaidRef.xlsx](https://github.com/cov-lineages/pango-designation/files/6811402/GisaidRef.xlsx)

**Comment by shay671** [comment]
It could be related to B.1.628 as it has 23 out of the 29 mutations of B.1.628 and B.1.628 lacks 6 of the mutations in this suspected lineage.

**Comment by chrisruis** [comment]
Thanks @shay671 for submitting. It looks like these sequences cluster within B.1.628 in the latest UShER tree:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_hgwdev_117e6_1123c0.json?c=pango_lineage&label=nuc%20mutations:C24642T,C26222T
They seem to have the defining B.1.628 mutations to support this clustering. While these sequences have also acquired E484Q, we wouldn't normally recommend a new lineage based on that change alone. So we'd therefore recommend referring to these sequences as B.1.628 and have added these in as B.1.628, along with other B.1.628 sequences, in [v1.2.45](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.45).

There are now 496 sequences designated B.1.628. Thanks again

**Comment by shay671** [comment]
Hi @chrisruis  

I think that this is a bit more complicated than just one SNP in the S gene. I’ll explain and add a table which will illustrate this: 
B.1.628 has in total 29 defining mutations.
Out of those 29, B.1.628 and the variant reported here has a shared basis of only 23 mutations. 
To those 23, B.1.628 has of course another 6 defining mutations which are not present in the variant reported here and this includes S:L18R the known deletion of s,g,f in NSP6 which is present in many VOC’s and another 3 non synonymous mutations.

The variant reported here has above the shared 23 mutations another 9 mutations (6 of which are non synonymous) which are not present in B.1.628, and thus includes S:E484Q, and N:L221F. 

So I think the more reasonable explanation is that this variant and B.1.628 might have a similar variant they have been evolved from, but by themselves they are separate variants. 


![image](https://user-images.githubusercontent.com/80166370/127317885-ea2a56c4-7ec8-43cc-be2d-03b70be18b8e.png)

**Comment by chrisruis** [comment]
Thanks for that @shay671. Looking at the sequences in this clade in the UShER tree and the raw sequences, they seem to have NSP3:1475G, NSP6:106S, S:R18, ORF3a:255-, ORF7b:5L. So those changes above seem to be shared with the sequences in this lineage and not be unique to the rest of B.1.628. Here's the UShER tree, this view shows B.1.628 and you can label by mutations on each branch and by the genotype at particular positions:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_hgwdev_1d1dc_14e1e0.json?c=pango_lineage&label=nuc%20mutations:C24642T,C26222T

We'd expect to see some changes that are unique to this clade just through continued mutation of B.1.628. If this clade was incorrectly placed in B.1.628 in UShER, we'd expect to see at least some of the mutations that are acquired leading to B.1.628 reverting leading to this clade. We don't observe this. So I don't think there's anything to suggest that this isn't a clade of B.1.628.

**Comment by shay671** [comment]
Hi @chrisruis. Thank you for the focus -   i found the mistake in my analysis and indeed those samples share all the mutations of B.1.628 . But also has another 12 mutations , 6 of which are Non synonymous

NSP2:A205V
NSP2:R222R
NSP3:S1333I
NSP3:P1921S
NSP16:T110I
S:Q23Q
S:E484Q
E:V25V
N:F110F
N:L221F
3'UTR:29543
3'UTR:29692

 
for ref you can use those samples :
EPI_ISL_2533920
EPI_ISL_2709730
EPI_ISL_2790133
EPI_ISL_2790177
EPI_ISL_2835929
EPI_ISL_2861179
EPI_ISL_2987716
