### ISSUE TITLE
CH.1.1.1 sublineage with ORF1a:A427V, ORF1b:K2140R, and ORF3a:A110V (497 good and 546 total seqs as of 2023-01-05; UK, Europe, North America, Israel, Japan, China)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1432]
There may be a CH.1.1.1 sublineage with ORF1a:A427V (C1545T), ORF1b:K2140R (A19886G), ORF3a:A110V (C25721T) first detected in Colorado, USA.

As of 2022-12-12, Cov-Spectrum reports 69 good-quality (72 total) CH.1.1.1+ORF1a:427V+ORF1b:2140R+ORF3a:110V sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ACH.1.1%2A+%26+ORF1a%3AA427V+%26+ORF1b%3AK2140R+%26+ORF3a%3AA110V+%26+S%3AN185D&nextcladeQcOverallScoreTo=29&

This potential lineage is showing strong potential growth even compared to CH.1.1.1. Omitting ORF1b:K2140R, despite its presence as an intermediate mutation in UShER, results in over 100 sequences on CoV-Spectrum. Most of these sequences are from the UK.

As of 2022-12-12, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![CH 1 1 1+ORF1a_427V+ORF1b_2140R+ORF3a_110V_UShER_CoV-Spectrum](https://user-images.githubusercontent.com/88959107/207171838-6136918d-c7c1-4a28-b5ca-fc3e18457dc7.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/12/subtreeAuspice1_genome_CoV-Spectrum_CH.1.1.1%2BORF1a_427V%2BORF1b_2140R%2BORF3a_110V.json?c=gt-ORF3a_110&label=id%3Anode_2432437
For the full subsampled UShER tree: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/12/singleSubtreeAuspice_genome_CoV-Spectrum_CH.1.1.1%2BORF1a_427V%2BORF1b_2140R%2BORF3a_110V.json?c=gt-ORF3a_110&label=id%3Anode_2430617

GISAID query: Lineage CH.1.1; AA Substitutions Spike_N185D, NSP2_A427V, NSP15_K89R, NS3_A110V

First Outbreak.info sequence: United Kingdom 2022-11-11

First GenBank sequence: Colorado, USA 2022-11-16 

Most Recent GenBank sequence: England, United Kingdom 2022-11-26

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-CH.1.1.1+ORF1a_427V+ORF1b_2140R+ORF3a_110V.zip](https://github.com/cov-lineages/pango-designation/files/10212574/Support-CH.1.1.1%2BORF1a_427V%2BORF1b_2140R%2BORF3a_110V.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-CH.1.1.1+ORF1a_427V+ORF1b_2140R+ORF3a_110V.txt](https://github.com/cov-lineages/pango-designation/files/10212584/gisaid-epi-isl-CH.1.1.1%2BORF1a_427V%2BORF1b_2140R%2BORF3a_110V.txt)

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=CH.1.1&muts=ORF1a%3AA427V&muts=ORF1b%3AK2140R&muts=ORF3a%3AA110V&muts=S%3AN185D. 

Edit: S:N185D is in the base CH.1.1.1 definition.

**Comment by FedeGueli** [comment]
I think there is a typo in Gisaid query: Spike_N185,NS3_A110V,NSp2_A247V is corrreect and finds 150 seqs

**Comment by alurqu** [comment]
@FedeGueli Thanks for the greatly improved GISAID query. And FYI now that query returns 189 seqs.

**Comment by alurqu** [comment]
@FedeGueli's GISAID query now returns 205 seqs.

A more restrictive GISAID query Spike_N185D,NSP15_K89R,NS3_A110V,NSP2_A247V (to explicitly include the intermediate mutation ORF1b:K2140R) now returns 151 seqs.

**Comment by alurqu** [comment]
This lineage was not part of the initial definition of CH.1.1.1 but has come to represent the majority but not the totality of CH.1.1.1.
![Issue_432-Growth-History](https://user-images.githubusercontent.com/88959107/210120103-108c3322-1183-43df-9313-e8a0385e8e77.png)

If this was designated as a separate lineage, it would be the current third fastest on Collection 24 https://cov-spectrum.org/collections/24 as measured by "CI (low)" using S:F486P as a baseline and data from the past 2 months or no baseline and data from the past 6 months.

**Comment by Mydtlwn** [comment]
It's already a lot. It's a good idea to specify this quickly

**Comment by alurqu** [comment]
CoV-Spectrum currently calculates this lineage's growth advantage as 34% (23%-45% confidence interval) over its already-fast parent CH.1.1.1:
![CH 1 1 1+ORF1a_427V+ORF1b_2140R+ORF3a_110V_Growth_Advantage_20230105](https://user-images.githubusercontent.com/88959107/210806929-b4ac7b89-bea4-4b8b-8e92-348a57eb9691.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ACH.1.1.1*&variantQuery1=nextcladePangoLineage%3ACH.1.1.1*+%26+ORF1a%3AA427V+%26+ORF1b%3AK2140R+%26+ORF3a%3AA110V&analysisMode=CompareToBaseline&

As a secondary note, a new first sample of this lineage has been reported: EPI_ISL_16260650 from Ireland sampled 2022-11-03.

**Comment by alurqu** [comment]
CoV-Spectrum currently calculates this lineage's growth advantage as 20% (14%-26% confidence interval) relative to S:F486P using data from the past 2 months:
![CH 1 1 1+ORF1a_427V+ORF1b_2140R+ORF3a_110V_Growth_Advantage_vs_S_F486P_20230105](https://user-images.githubusercontent.com/88959107/210838550-d023a99c-9387-479e-ba23-40da64a1f286.png)

This places this lineage contending for second place with much smaller lineage DP.1 on [Collection 24](https://cov-spectrum.org/collections/24) with the same time period and baseline and sorted by the lower bound of the relative growth advantage confidence interval "CI (low)" descending.

**Comment by FedeGueli** [comment]
i find 960 seqs of this one.

**Comment by corneliusroemer** [comment]
Hmm, this is just the majority of CH.1.1.1 that is spreading - don't see much point in designating the major branch at this point, this just makes for longer names.

For growth advantage, if you don't limit to one country one quickly ends up with garbage results due to different upload delays.

**Comment by alurqu** [comment]
Closing as insufficiently distinct from CH.1.1.1 unless and until a CH.1.1.1 sublineage emerges that does not have these additional mutations.

**Comment by alurqu** [comment]
Closing as insufficiently distinct from CH.1.1.1 unless and until a CH.1.1.1 sublineage emerges that does not have these additional mutations.
