### ISSUE TITLE
CK.1 Sublineage with S:Y144del, S:F157L, & S:G181V (59 seq, Jan 12)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1433]
### **Description**
**Sub-lineage of:** CK.1
**Earliest sequence:** 2022-11-3, South Korea — EPI_ISL_15906487
**Most recent sequence:** 2022-11-27, USA, California — EPI_ISL_16082025
**Countries circulating:** USA (8), South Korea (1)
**Number of Sequences:** 9
**GISAID Query:** Spike_F157L, Spike_G181V, Spike_K444N, Spike_N460K, NSP13_T127N
**CovSpectrum Query:** Nextcladepangolineage:CK.1* & S:F157L & S:G181V
**Substitutions/Deletions on top of CK.1:**
**Spike:** F157L, G181V
**Nucleotide:** C22033A, G22104T
**AA Deletions:** Y144
**Nucleotide Deletions:** 21992-21994
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/CK.1%20%2B%20Y144del%2C%20F157L%2C%20G181V%20-%20subtreeAuspice1_genome_4145f_7bc6b0.json  
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33738461/207196704-a4556894-834e-4444-b455-3a28e2c11abe.png">

**Evidence**
This is already a fast-growing and immune-evasive lineage, and the addition of these three NTD mutations seems likely to increase its ability to evade immunity. The first sequence in this lineage was from South Korea, and it appears not to be related to travel. Seven of the nine sequences are from California, but there’s also been one detected on the opposite side of the US in New York, so this lineage, while small, is geographically widespread.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15906487, EPI_ISL_15943605, EPI_ISL_15945229, EPI_ISL_16020802, EPI_ISL_16080690, EPI_ISL_16081259, EPI_ISL_16081688, EPI_ISL_16081882, EPI_ISL_16082025,
</details>

**Comment by ryhisner** [comment]
This one has nearly doubled in the past four days, going from nine to 17 sequences.

**Comment by FedeGueli** [comment]
Just noticed a sibling of this one with S:181V that gained S:346T too. i m proposing it. great catches Ryan

**Comment by ryhisner** [comment]
Jumped from 30 to 38 sequences today. Seems to be doubling every 7-8 days so far.

**Comment by ryhisner** [comment]
Only four sequences in the past five days, so I'm closing this.

**Comment by oobb45729** [comment]
This one has grown a lot since. There is also a potential sublineage of it with S:A688V and N:P365S.

**Comment by FedeGueli** [comment]
Yes now it is 229seqs @ryhisner please reopen this one. 

cc @InfrPopGen worth taking a look of this one.

thx @oobb45729 !
