### ISSUE TITLE
BA.5.2.9 Sublineage with S:145-146del, S:V445A, S:N450D, S:K964T, ORF1a:S3099L, ORF1a:A3143V, ORF1a:V4369A (19 seq, Dec 29)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1434]
### **Description**
**Sub-lineage of:** BA.5.2.9
**Earliest sequence:** 2022-10-27, Mexico, Guerrero — EPI_ISL_15932563
**Most recent sequence:** 2022-11-27, USA, Washington state — EPI_ISL_16027055
**Countries circulating:** Mexico (6), USA (3)
**Number of Sequences:** 9
**GISAID Query:** Spike_K964T, Spike_V445A, Spike_N450D, NSP12_Y521C
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2.9* & S:V445A & S:N450D & S:K964T
**Substitutions/Deletions on top of BA.5.2.9:**
**Spike:** V445A, N450D, K964T
**ORF1a:** S3099L, A3143V, V4369A (NSP4_S336L, NSP4_A380V, NSP10_V116A)
**Nucleotide:** T5254C, C9561T, C9693T, C10726T, C11620T, T13371C, T22896C, A22910G, A24453C, T25686A, C26256T, G29374A
**AA Deletions:** 145-156
**Nucleotide Deletions:** 21993-21998
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.5.2.9%20%2B%20145-146del%2C%20V445A%2C%20N450D%2C%20K964T%20%2B%203xORF1a%20-%20subtreeAuspice1_genome_2de3_7bfce0.json
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/33738461/207201536-33fb2f98-9cf5-4e1a-83ce-f723ca71e755.png">

 
**Evidence**
Four of the nine sequences here appear not to have S:145-146del, but they are all from Mexico and also fail to detect S:69-70del, so I think it’s safe to say they also have this deletion.

Looking at the 12-nucleotide substitutions on top of BA.5.2.9, you’d think this was a saltation lineage, but looking at the tree, that doesn’t appear to be the case. More likely, this lineage has been evolving in an undersequenced area of Central America, only occasionally surfacing in other countries.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15932203, EPI_ISL_15932279, EPI_ISL_15932550, EPI_ISL_15932562, EPI_ISL_15932563, EPI_ISL_15932564, EPI_ISL_16027055, EPI_ISL_16081378, EPI_ISL_16081424
</details>

**Comment by FedeGueli** [comment]
Great catch Ryan. Wondering if K to T in 964 could change things around 969

**Comment by corneliusroemer** [comment]
The 450D branch is interesting in its own right, one could also label the ORF1a:T2684I as X.2 if we decide to designate.

Let's watch this one a bit more.

**Comment by ryhisner** [comment]
The 11th sequence came in today from California, USA, and has picked up S:N1108T. EPI_ISL_16131367
The 10th sequence, mentioned above by @corneliusroemer, added S:A688V.  EPI_ISL_16105165

**Comment by FedeGueli** [comment]
i see 18 sequences as today with Spike_K964T, Spike_V445A, Spike_N450D, NSP12_Y521C

**Comment by ryhisner** [comment]
One sequence today uploaded from Ohio, USA. It's the first sequence not from either Mexico or the US West Coast. EPI_ISL_16320877

**Comment by ryhisner** [comment]
This one seems to have died, so I'm closing.
