### ISSUE TITLE
BA.2.3.20 Sublineage with S:P1162S, S:E1202Q, S:C1250F, ORF1a: T4354I, ORF1b:E787G (16 seq, Jan 4)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1435]
### **Description**
**Sub-lineage of:** BA.2.3.20
**Earliest sequence:** 2022-11-7, USA, California — EPI_ISL_15952957
**Most recent sequence:** 2022-12-7, Scotland — EPI_ISL_16108797
**Countries circulating:** USA(6), Scotland (1)
**Number of Sequences:** 7
**GISAID Query:** Spike_E484R, Spike_P1162S, Spike_E1202Q, Spike_C1250F
**CovSpectrum Query:** Nextcladepangolineage: BA.2.3.20* & S:P1162S & S:E1202Q & S:C1250F
**Substitutions on top of BA.:**
**Spike:** P1162S, E1202Q, C1250F
**ORF1a:** T4354I
**ORF1b:** E787G
**Nucleotide:** G5665A, C13326T, A15827G, C20646T, C25046T, G25166C, G25311T
 
**USHER Tree**
Note: the "long" branch at the far right in the tree below actually has zero mutations compared to the sequences at the base of this lineage—the two on Usher are artifactual & due to a frame shift at the end of ORF3a. So the diversity here is less than what it at first appears to be. None of the seven sequences differ from the three basal sequences by more than one nucleotide substitution.
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.2.3.20%20%2B%20P1162S%2C%20E1202Q%2C%20C1250F%2C%20ORF1aT4354I%2C%20ORF1bE787G%20-%20subtreeAuspice1_genome_1abe0_9b5bd0.json
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/33738461/207594556-bd22292f-6aa4-4e7b-aa3b-89d183f3b547.png">
 
**Evidence**
It’s rare to see three S2 mutations on one branch; I’m not sure I’ve ever seen it except in singlets. This lineage, however, is clearly being transmitted, and today brought the first evidence that it had crossed an ocean. The first six sequences were all from USA, California, but the most recent one (collected December 7) was from Scotland. Typically, S2 mutations in AA residues higher than 1000 don’t have any noticeable effect on a lineage’s growth. Two possible exceptions might be S:P1263Q and S:V1264L, the former appearing to give a slight boost to BA.5.1.5 and the latter to BG.2. But it’s not clear that even those two have any real effect.
However, I don’t recall seeing three mutations in this region within 90 residues of each other in any notable lineage, so this may be uncharted territory. Perhaps there is epistasis of some sort here—or perhaps there was eventually bound to be a lineage that had three nether-region S2 mutations, none of which provide any real advantage or disadvantage.

S:P1162 mutations are quite common. This residue in at the dividing point between the stem helix (SH) and heptad repeat two (HR2), and is the only one of the three S2 mutations here that might play a modest antigenic role. Several weakly neutralizing S2 monoclonal antibodies have been found to bind to the SH epitope, pictured below in “Antibody-mediated immunity to SARS-CoV-2 spike,” by John M. Errico, Lucas J. Adams, and Daved H. Fremont.
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/33738461/207595267-0a10dc7b-6afe-471d-b7e5-4efc70b7c0a9.png">

S:E1202Q is in the middle of HR2, which binds to HR1 during the conformational shift initiating fusion with the cell membrane, while S:C1250F in the far C-terminal spike region not usually labeled and whose function I don’t know.
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/33738461/207595424-f78c5eb4-8e68-4ebb-b7d8-398f7ef0ed93.png">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15952951, EPI_ISL_15952957, EPI_ISL_16081408, EPI_ISL_16082155, EPI_ISL_16082473, EPI_ISL_16082499, EPI_ISL_16108797
</details>

**Comment by Mydtlwn** [comment]
The mutation at site 1162 needs attention.

**Comment by ryhisner** [comment]
Two more sequences from California today bring this up to 15 sequences.

**Comment by ryhisner** [comment]
This one's faded. Closing.
