### ISSUE TITLE
New XBB.2 sublineage with ORF1ab:S142L, P6657S mutations circulating in Peru (Ucayali)

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#1436]
**A) Description**
New possible omicron sub-lineage with ORF1ab:S142L (nuc: C690T), P6657S mutation circulating in Ucayali proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**B) Earliest sequence:** 2022-11-14
EPI_ISL_16114574

**C) Most recent sequence:** 2022-11-21
EPI_ISL_16114072
EPI_ISL_16114075
EPI_ISL_16114081
EPI_ISL_16114089
EPI_ISL_16114152
EPI_ISL_16114156
EPI_ISL_16114180
EPI_ISL_16114192
EPI_ISL_16114217
EPI_ISL_16114238
EPI_ISL_16113982
EPI_ISL_16114039
EPI_ISL_16114202

**D) Countries circulating:**
Peru (37 seq)

**E) Genomes**
[genomes.csv](https://github.com/cov-lineages/pango-designation/files/10229646/genomes.csv)

**F) Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d535_9f4ae0.json?label=id:node_9019475
![Captura desde 2022-12-14 11-14-20](https://user-images.githubusercontent.com/89021119/207649947-a7fd1985-5fb5-4918-9e7a-9e35d36ee97f.png)

**Comment by corneliusroemer** [comment]
Thanks @Wen1953 for tracking XBB spread in Peru! Looks like all sequences are still from one lab, let's wait for a little broader spread for designation.

**Comment by Wen1953** [comment]
392 seqs to now

**Comment by Wen1953** [comment]
566 to now

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it appears to be fading in terms of growth advantage (i.e. just growing along with its parent clade), and hasn't recently been detected in most of its "range", this can be closed for now. Please request re-opening, or re-propose, should this clade show strong relative growth in the future.
