### ISSUE TITLE
Potential BA.2.76/BF.3 recombinant with spike changes from both donors (110 seqs as of 2023-01-06)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1441]
This is a relatively old recombinant cluster likely from India-MH that I used to be monitoring since August. I was surprised to see it's still growing after almost a month of hiatus in September/October, and this time in a geographically distant areas (mainly Canada and the US). 

![image](https://user-images.githubusercontent.com/86835836/208214641-a26d8bfb-557e-4512-83e1-0ec151f6da68.png)

Interestingly this pattern of hiatus and reemergence is similar to #896 , which is another BA.2.76/BA.5.2* recombinant.

### Description
**Recombinant between**: BA.2.76 and BF.3
**Earliest sequence**: 2022/07/25 (India-MH)
**Most recent sequence**: 2022/12/07 (Canada-ON)
**Countries circulating**: US (33 seqs), Canada (17 seqs), India (15 seqs), Denmark (5 seqs), Germany (1 seq), Maritius (1 seq), UK-Scotland (1 seq).
**Likely breakpoint**: between 22601 and 22915 (Spike S1)

**Nuc mutations** (those in red frames are likely from BA.2.76):
![image](https://user-images.githubusercontent.com/86835836/208214433-0a228e7b-4ed8-4772-8d41-33bd59756e51.png)
**Likely donor from B.2.76 side**: EPI_ISL_14988943 from India-MH (BA.2.76 with additional G19891A and A19812G)
**Likely donor from BF.3 side**: BF.3 with additional C27549T
**GISAID and cov-spectrum query**: C27549T, G24620T, C23202T, A19812G

Evidence
Usher tree:
![image](https://user-images.githubusercontent.com/86835836/208217161-37d39261-4d88-4c43-930b-5d8514db8e5f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26d38_d09d20.json?branchLabel=Spike%20mutations&c=gt-nuc_19891&label=id:node_7264411

### Genome:
EPI_ISL_14355946, EPI_ISL_14832149, EPI_ISL_14861661, EPI_ISL_14915762, EPI_ISL_14923215, EPI_ISL_14923226, EPI_ISL_14923237, EPI_ISL_14989096, EPI_ISL_15028332, EPI_ISL_15047992, EPI_ISL_15059096, EPI_ISL_15059167, EPI_ISL_15063868, EPI_ISL_15074003, EPI_ISL_15074108, EPI_ISL_15074115, EPI_ISL_15074192, EPI_ISL_15085366, EPI_ISL_15146825, EPI_ISL_15275372, EPI_ISL_15348746, EPI_ISL_15373833, EPI_ISL_15422688, EPI_ISL_15433369, EPI_ISL_15497617, EPI_ISL_15497635, EPI_ISL_15618796, EPI_ISL_15689056, EPI_ISL_15706030, EPI_ISL_15744932, EPI_ISL_15744934, EPI_ISL_15744936, EPI_ISL_15766235, EPI_ISL_15768444, EPI_ISL_15772791, EPI_ISL_15772992, EPI_ISL_15778901, EPI_ISL_15804951, EPI_ISL_15819065, EPI_ISL_15851020, EPI_ISL_15854670, EPI_ISL_15854679, EPI_ISL_15860299, EPI_ISL_15904857, EPI_ISL_15930330, EPI_ISL_15944329, EPI_ISL_15948596, EPI_ISL_15950139, EPI_ISL_15959665, EPI_ISL_15960138, EPI_ISL_15960173, EPI_ISL_15974648, EPI_ISL_15999557, EPI_ISL_16015652, EPI_ISL_16015736-16015737, EPI_ISL_16015987, EPI_ISL_16016029-16016030, EPI_ISL_16025058, EPI_ISL_16032429, EPI_ISL_16040373, EPI_ISL_16063881, EPI_ISL_16068527, EPI_ISL_16081997, EPI_ISL_16085765, EPI_ISL_16085836, EPI_ISL_16086636, EPI_ISL_16086640, EPI_ISL_16086767, EPI_ISL_16086779-16086780, EPI_ISL_16100942

**Comment by c19850727** [comment]
86 sequences as of 2022-12-25. Re-emerged in Denmark and Germany as well.

**Comment by c19850727** [comment]
100 sequences as of 2022-12-31.

**Comment by ryhisner** [comment]
33 XBM sequences uploaded from Ontario, Canada, today!

**Comment by FedeGueli** [comment]
XBM is riding up Collection24 chart:
<img width="1274" alt="Schermata 2023-01-26 alle 17 09 02" src="https://user-images.githubusercontent.com/87669813/214887285-558bca60-2c7f-4e84-be4b-b49338d20c6f.png">
https://cov-spectrum.org/collections/24

**Comment by JosetteSchoenma** [comment]
XBM
