### ISSUE TITLE
BF.10 Sublineage with S:V445A, S:G446S, ORF8:ins18NG* (42 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1442]
### **Description**
**Sub-lineage of:** BF.10
**Earliest sequence:** 2022-10-4, USA, California — EPI_ISL_15661147
**Most recent sequence:** 2022-12-3, USA, California —EPI_ISL_16131881
**Countries circulating:** USA (38), Mexico (2)
**Number of Sequences:** 40
**GISAID Query:** Spike_V445A, Spike_G446S, NSP13_A368V
**CovSpectrum Query:** Nextcladepangolineage:BF.10* & S:V445A & S:G446S
**Substitutions on top of BF.10:**
**Spike:** V445A, G446S
**Nucleotide:** C22591T, T22896C, G22898A
**AA Insertions:** ORF8:ins18NG*
**Nucleotide Insertions:** ins27947AATGGTTAG
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BF.10%20%2B%20V445A%2C%20G446S%2C%20ORF8_ins18*%20-%20subtreeAuspice1_genome_3e470_dd35b0.json  

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/33738461/208247877-c7adbfe3-639a-4a36-af39-ad319aa78f84.png">

**Evidence**
The two Mexican sequences here are from Baja California. It’s possible this is circulating more widely in Mexico than in the USA given the huge difference in sequencing frequency between the two countries, particularly since California does more sequencing than most US states.
 
I’m not sure if there have been any lineages previously with an ORF8 insertion. I’m not aware of any, but I only started following these things closely last May. Probably should include more details here, but I’m too exhausted to write any more right now. I might come back and add more later.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15619314, EPI_ISL_15661147, EPI_ISL_15671160, EPI_ISL_15671163, EPI_ISL_15704016, EPI_ISL_15707413, EPI_ISL_15765833, EPI_ISL_15804632, EPI_ISL_15819104, EPI_ISL_15819196, EPI_ISL_15819437, EPI_ISL_15819454, EPI_ISL_15819455, EPI_ISL_15819456, EPI_ISL_15819457, EPI_ISL_15831747, EPI_ISL_15860308, EPI_ISL_15881190, EPI_ISL_15932510, EPI_ISL_15932524, EPI_ISL_15945082, EPI_ISL_15950471, EPI_ISL_15952606, EPI_ISL_15954610, EPI_ISL_16009494, EPI_ISL_16010992, EPI_ISL_16012175, EPI_ISL_16049098, EPI_ISL_16069396, EPI_ISL_16069891, EPI_ISL_16081464, EPI_ISL_16082160, EPI_ISL_16082793, EPI_ISL_16082904, EPI_ISL_16083097, EPI_ISL_16088156, EPI_ISL_16101095, EPI_ISL_16101096, EPI_ISL_16131881, EPI_ISL_16158852,
</details>

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.10.1 with 27 newly designated sequences, and 0 updated. Defining mutation G22898A (S:G446S) (following T22896C (S:V445A)).
