### ISSUE TITLE
Another BA.2.75*/BQ.1* recombinant similar to #1393 and #1425 (39 seqs as of 2023-03-30)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1444]
This is another BA.2.75*/BQ.1* sharing a very similar recombination pattern with #1393 and #1425 .

### Description
**Recombinant between**: BA.2.75* and BQ.1* (with S:R346T)
**Earliest sequence:** 2022/10/19 (Korea)
**Most recent sequence**: 2022/12/13 (Italy)
**Countries circulating**: Korea (1/8), France (1/8), Germany (1/8), US-KS (1/8), New Caledocia (1/8), Italy (3/8)
**Potential breakpoint**: Spike NTD (22580-22939)

**Mutation profile** (private mutations are in yellow color):
![image](https://user-images.githubusercontent.com/86835836/208339721-4e1a9020-643f-43d4-952b-c3f05e138713.png)
**Private mutations**: C1376T (ORF1a:P371S), T11645C (ORF1a:F3794L), G14430T
**GISAID and Cov-spectrum query**: C1376T, T11645C, G14430T

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/208349444-3189b52d-5eb6-423b-bf5b-acae7d1269ec.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3452e_f1d290.json?c=gt-nuc_1376&label=id:node_9067168

Genomes:
EPI_ISL_15609528, EPI_ISL_15968293, EPI_ISL_16061180, EPI_ISL_16153148, EPI_ISL_16166674, EPI_ISL_16166701-16166702, EPI_ISL_16168949

**Comment by corneliusroemer** [comment]
This one notably has S:T430I

**Comment by FedeGueli** [comment]
11 sequences as today the last three uploads from Umbria Italy

**Comment by FedeGueli** [comment]
12th sequence again from Umbria, Italy

**Comment by FedeGueli** [comment]
14 as today

**Comment by FedeGueli** [comment]
17 sequences as today. last two from Umbria It, and Occitaine Fr.

**Comment by SlimEKDev** [comment]
We had a similar sequence : EPI_ISL_16529593, similar to EPI_ISL16061180, from Bretagne (FRA).

**Comment by FedeGueli** [comment]
21 sequences as today last two samples from Umbria Italy

**Comment by c19850727** [comment]
44 sequences now but it seems it already stopped growing.
