### ISSUE TITLE
Proposal for BQ.1.1 sub-lineage with M:S212G and ORF1a:A903V in Japan (930 seqs as of 2023/1/17. 920 seqs in Japan)

### ISSUE THREAD

**Issue by takaabe8050** [cov-lineages/pango-designation#1445]
By Japan COVID-19 Open Data Consortium

Description
Sub-lineage of: BQ.1.1 (307 sequences)
Earliest sequence: 2022/10/12 (hCoV-19/Japan/PG-382146/2022, hCoV-19/Japan/PG-380509/2022, hCoV-19/Japan/TKYmbc12116/2022)
Most recent sequence: 2022/12/05 (hCoV-19/Japan/PG-409411/2022, hCoV-19/Japan/PG-407950/2022, hCoV-19/Australia/NSW-ICPMR-38950/2022, hCoV-19/Australia/NSW-ICPMR-38951/2022)
Countries circulating: Japan (302 sequences), Singapore (1), Hong Kong (1), Australia (2), South Korea (1)

This proposal sub-lineage is about 36 % of all BQ.1.1 in Japan.

Associated mutations
C2973T (ORF1a:A903V)
A27156G (M:S212G)

Genomes
[genome_list.txt](https://github.com/cov-lineages/pango-designation/files/10259430/genome_list.txt)

Evidence
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_8dfa_49aa0.json?c=userOrOld&f_userOrOld=uploaded%20sample

 
![image](https://user-images.githubusercontent.com/89957075/208432470-c03df4c9-2d1c-4b1f-84f6-b7790558836f.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=A27156G%2CC2973T&pangoLineage=BQ.1.1&

**Comment by takaabe8050** [comment]
62 sequences added as of 2022-12-23.

**Comment by takaabe8050** [comment]
56 sequences added as of 2022-12-28.

**Comment by FedeGueli** [comment]
i see 611 as today

**Comment by takaabe8050** [comment]
109 sequences added as of 2023-01-16.

**Comment by takaabe8050** [comment]
92 sequences added as of 2023-01-17.

**Comment by takaabe8050** [comment]
140 sequences added as of 2023-01-25.

**Comment by corneliusroemer** [comment]
Designated as BQ.1.1.70!
