### ISSUE TITLE
New BA.5.2  +Orf1b:1050N + C26681T with Orf1a:K510E, S:K444T and S:N460K  (T22942G) ( 40 seqs Japan,Germany)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1446]
Defining mutations:  BA.5.2 + C27513T > C27012T > G12310A > Orf1b:T1050N (C16616A ) > C26681T > Orf1a:K510E (A1793G) , S:K444T (A22893C), S:N460K (T22942G)

Tree:
![Schermata 2022-12-19 alle 20 50 21](https://user-images.githubusercontent.com/87669813/208508208-683d6023-82af-4b52-8147-bce8f480d103.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_5011_b87a0.json?c=gt-ORF1ab_510&label=id:node_6796540

Gisaid Query: NSP2_K330E,Spike_K444T,Spike_N460K
25 sequences: 
EPI_ISL_15284102, EPI_ISL_15642872, EPI_ISL_15722963,
EPI_ISL_15771744, EPI_ISL_15774167, EPI_ISL_15831531,
EPI_ISL_15846038, EPI_ISL_15875314, EPI_ISL_15997250,
EPI_ISL_16017536, EPI_ISL_16051341, EPI_ISL_16060580,
EPI_ISL_16070467, EPI_ISL_16073025, EPI_ISL_16079092,
EPI_ISL_16079178, EPI_ISL_16079188, EPI_ISL_16094133,
EPI_ISL_16107865, EPI_ISL_16110249, EPI_ISL_16112197,
EPI_ISL_16122546, EPI_ISL_16122900, EPI_ISL_16154767,
EPI_ISL_16174075

Countries: It likely emerged in a downsampled area in Asia (Indonesia?Malaysia?) being exported to denmark already at the beginning of October, but it seemed to be successful in japan after acquiring a further Orf1a:D203N mutation.

CovSpectrum tracking: C26681T, T22942G + ORF1a:K510E, S:K444T 
https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?aaMutations=Orf1a%3AK510E%2CS%3AK444T&nucMutations=C26681T%2CT22942G&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

**Comment by FedeGueli** [comment]
32 sequences as today. Newly found in Germany,

**Comment by FedeGueli** [comment]
40 sequences as today.
It seems a thing in Japan with all last sequences coming from there. @InfrPopGen i suggest a prudent designation of this one due the epidemic situation there, at least if it will die off it will have been just one of the many 444+460 lineages of ba.5.2

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.46 with 21 newly designated sequences, and 0 updated. Defining mutation A1793G (ORF1a:K510E), A22893C (S:K444T), T22942G (S:N460K) (following C26681T).

**Comment by FedeGueli** [comment]
Thx for your work @InfrPopGen
