### ISSUE TITLE
Potential XBB.4 sublineage with S:V90I, ORF1ab:T5675I, L6102F, ORF7a:H47Y mutation circulating in Peru (Ancash)

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#1447]
**A) Description**
New possible omicron sub-lineage with S:V90I, ORF1ab:T5675I, L6102F, ORF7a:H47Y mutation proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru. Additionally, it has Nuc: C1684T, T6025C, T10663C, C13384T, C17288T, C18568T, G21830A, C27532T mutations and a subtree rooted from  S: K444R, V445L. 

**B) Earliest sequence:** 2022-11-14
Peru/ANC-INS-34163/2022
Peru/ANC-INS-34209/2022

**C) Most recent sequence:** 2022-11-22
hCoV-19/Peru/ANC-INS-34869/2022
hCoV-19/Peru/ANC-INS-34870/2022
hCoV-19/Peru/ANC-INS-34871/2022

**D) Countries circulating:**
Peru, Ancash (21)

**E) Genomes**
[metadata.csv](https://github.com/cov-lineages/pango-designation/files/10262423/metadata.csv)

**F) Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22d75_c09f0.json?c=pango_lineage
![Captura desde 2022-12-19 15-03-46](https://user-images.githubusercontent.com/89021119/208510921-3eb13eac-8d8c-48b0-8114-068e54bae86f.png)

**Comment by FedeGueli** [comment]
24 sequences as today with the query C1684T, T6025C, T10663C, C13384T, C17288T, C18568T, G21830A, C27532T.
All of them are from Ancash

**Comment by Wen1953** [comment]
74 seq until now, most of them from Ancash (Peru)
https://cov-spectrum.org/explore/Peru/AllSamples/Past6M/variants?nucMutations=C1684T%2CT6025C%2CT10663C%2CC13384T%2CC17288T%2CC18568T%2CG21830A%2CC27532T&pangoLineage=XBB.4&

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. Although this shows some growth advantage over XBB.4 since first detection (around 10% worldwide), it makes up ~50% of that lineage over the same period. Consequently, a designation does not appear that useful at the moment. It seems to be growing gradually along with the rest of XBB.4, but please re-propose or request re-opening should this lineage markedly distinguish itself in the future.

**Comment by FedeGueli** [comment]
@shay671 here was your xbb.4 sublimeage!
