### ISSUE TITLE
DJ.1.1 with additional mutations ORF6:I14V; Nuc:C27128T mainly in Peru

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#1449]
DJ.1.1 with additional mutations ORF6:I14V; Nuc:C27128T by Group of Genomic Surveillance INS-PERU

**Description**
Sub-lineage of: Potential new sub-lineage of DJ.1.1
Earliest sequence: hCoV-19/Peru/LIM-INS-33135/2022 (28/10/2022, Peru)
Most recent sequence: hCoV-19/Canada/ON-KHS-22-16532-v1/2022 (5/12/2022, Canada)

**Countries circulating**
Peru (10), USA (3), Germany (1), Canada (1)

This potential DJ.1.1 is distributed mainly in Lima, Peru.

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/10263681/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_258a4_e2cc0.json?c=gt-ORF6_14&label=id:node_6660108&tl=country

<img width="1286" alt="DJ 1 1" src="https://user-images.githubusercontent.com/87997149/208553341-40d7c108-2c7a-4521-b37d-d46299f8a2a3.png">

<img width="1554" alt="usher_DJ 1 1" src="https://user-images.githubusercontent.com/87997149/208553350-a22ee384-45cf-4257-a8b4-b639e7d4b703.png">

**Proposed sub-lineage name**
DJ.1.1.X

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it has not been detected again for around two months now, this can be closed at present. Please request re-opening or re-propose should this clade start to show strong growth and epidemiological significance in the future.
