### ISSUE TITLE
B.1.617.2 sublineage with Q414H

### ISSUE THREAD

**Issue by georgimarinov** [cov-lineages/pango-designation#145]
by Georgi K. Marinov

**Description**

Sub-lineage of: B.1.617.2
Earliest sequence: 2021-05-26 hCoV-19/England/ALDP-15D9994/2021
Most recent sequence: 2021-07-06 hCoV-19/England/PLYM-189D692/2021
Countries circulating: United Kingdom, mostly England, some in Wales and Scotland

I have noticed these sequences (218 in total at the moment) having Q414H on top of B.617.2 showing up for a few weeks now, and they seem to form a separate clade. 

All of them are from the UK, starting in late May. 

The set of mutations is:

ORF1a	A1306S
ORF1a	P2046L
ORF1a	P2287S
ORF1a	V2930L
ORF1a	T3255I
ORF1a	T3646A
ORF1b	P314L
ORF1b	G662S
ORF1b	P1000L
ORF1b	A1918V
S	T19R
S	del157/158
S	Q414H
S	L452R
S	T478K
S	D614G
S	P681R
S	D950N
ORF3a	S26L
M	I82T
ORF7a	V82A
ORF7a	T120I
ORF7b	T40I
ORF8	del119/120
N	D63G
N	R203M
N	G215C
N	D377Y

**Evidence**

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_hgwdev_f253_f9ad30.json

![Q414H-2021_07_15_02](https://user-images.githubusercontent.com/6155873/125719962-ce3e8173-b454-4a23-ba2d-ad875bee6ed1.png)

**Genomes**

hCoV-19/England/NORT-1BCFDF9/2021
hCoV-19/England/PHEC-31A60E/2021
hCoV-19/England/PHEC-31CE7D/2021
hCoV-19/England/PHEC-31F399/2021
hCoV-19/England/ALDP-15D9994/2021
hCoV-19/England/ALDP-15DB2E2/2021
hCoV-19/England/ALDP-15DB30D/2021
hCoV-19/England/ALDP-15D3FC5/2021
hCoV-19/England/ALDP-15D4304/2021
hCoV-19/England/ALDP-15E3EE3/2021
hCoV-19/England/ALDP-15F3615/2021
hCoV-19/England/ALDP-15EDB4C/2021
hCoV-19/England/ALDP-15EEBC3/2021
hCoV-19/England/ALDP-15EB9AE/2021
hCoV-19/England/ALDP-15F2B08/2021
hCoV-19/England/ALDP-15F91A5/2021
hCoV-19/England/ALDP-15F95A9/2021
hCoV-19/England/ALDP-15F2591/2021
hCoV-19/England/PHEC-31656F/2021
hCoV-19/England/ALDP-160108E/2021
hCoV-19/England/ALDP-15FA5E4/2021
hCoV-19/England/ALDP-1601570/2021
hCoV-19/England/ALDP-1606AB8/2021
hCoV-19/England/ALDP-1611D2A/2021
hCoV-19/England/ALDP-16116D4/2021
hCoV-19/England/ALDP-1611847/2021
hCoV-19/England/ALDP-160F9A3/2021
hCoV-19/England/ALDP-160ADCA/2021
hCoV-19/England/ALDP-1617FB5/2021
hCoV-19/England/ALDP-162163B/2021
hCoV-19/England/ALDP-1624EB8/2021
hCoV-19/England/ALDP-1624E12/2021
hCoV-19/England/ALDP-1622087/2021
hCoV-19/England/ALDP-16220B4/2021
hCoV-19/England/ALDP-1635634/2021
hCoV-19/England/ALDP-1635519/2021
hCoV-19/England/ALDP-1639296/2021
hCoV-19/England/ALDP-16668F8/2021
hCoV-19/England/HSLL-16196FA/2021
hCoV-19/England/ALDP-1648C96/2021
hCoV-19/England/ALDP-1665F30/2021
hCoV-19/England/SHEF-10DB171/2021
hCoV-19/England/QEUH-163EFF4/2021
hCoV-19/England/MILK-162EC2D/2021
hCoV-19/England/MILK-162EC1E/2021
hCoV-19/England/ALDP-1650CE6/2021
hCoV-19/England/ALDP-1666AD4/2021
hCoV-19/England/ALDP-1657292/2021
hCoV-19/England/QEUH-16458D1/2021
hCoV-19/England/QEUH-1645BF6/2021
hCoV-19/England/QEUH-16459ED/2021
hCoV-19/England/QEUH-16459FC/2021
hCoV-19/England/MILK-163733B/2021
hCoV-19/England/QEUH-164EF1F/2021
hCoV-19/England/ALDP-167A2E4/2021
hCoV-19/England/ALDP-165713B/2021
hCoV-19/England/ALDP-1657283/2021
hCoV-19/England/ALDP-165A98B/2021
hCoV-19/England/ALDP-165A7DC/2021
hCoV-19/England/ALDP-1659825/2021
hCoV-19/England/ALDP-165A8E8/2021
hCoV-19/England/ALDP-1665D18/2021
hCoV-19/Wales/PHWC-PYF9FU/2021
hCoV-19/Wales/PHWC-PYGN5B/2021
hCoV-19/England/ALDP-1661B5E/2021
hCoV-19/England/ALDP-1686C8D/2021
hCoV-19/England/ALDP-1687651/2021
hCoV-19/England/ALDP-1687D01/2021
hCoV-19/Wales/PHWC-PYGBAE/2021
hCoV-19/England/ALDP-16677CD/2021
hCoV-19/England/ALDP-16674F3/2021
hCoV-19/England/HSLL-165F28B/2021
hCoV-19/England/HSLL-1663266/2021
hCoV-19/England/QEUH-1677593/2021
hCoV-19/England/ALDP-167B4CF/2021
hCoV-19/England/ALDP-168C09A/2021
hCoV-19/England/ALDP-1689DD2/2021
hCoV-19/England/ALDP-1689DF0/2021
hCoV-19/England/ALDP-168C22B/2021
hCoV-19/England/ALDP-168A15D/2021
hCoV-19/England/ALDP-168C276/2021
hCoV-19/England/ALDP-168DB98/2021
hCoV-19/England/ALDP-169ED8F/2021
hCoV-19/England/MILK-1675049/2021
hCoV-19/England/ALDP-168E06B/2021
hCoV-19/Wales/PHWC-PYGEUM/2021
hCoV-19/England/PHWC-PYGGM6/2021
hCoV-19/England/PHWC-PYGGXS/2021
hCoV-19/England/CAMB-AAC488/2021
hCoV-19/Portugal/PT8934/2021
hCoV-19/England/ALDP-16F3F46/2021
hCoV-19/England/ALDP-1700060/2021
hCoV-19/England/ALDP-170130C/2021
hCoV-19/England/ALDP-16FEFF0/2021
hCoV-19/England/HSLL-16F1A83/2021
hCoV-19/England/QEUH-16FAA02/2021
hCoV-19/England/ALDP-170E69D/2021
hCoV-19/England/ALDP-1715411/2021
hCoV-19/England/ALDP-17153E7/2021
hCoV-19/England/ALDP-1730058/2021
hCoV-19/England/ALDP-172FBE2/2021
hCoV-19/England/ALDP-172F8FA/2021
hCoV-19/England/ALDP-17342F4/2021
hCoV-19/England/ALDP-1741036/2021
hCoV-19/England/ALDP-172DD57/2021
hCoV-19/England/ALDP-172AEC0/2021
hCoV-19/England/MILK-170D573/2021
hCoV-19/England/ALDP-1732126/2021
hCoV-19/England/ALDP-173441C/2021
hCoV-19/England/ALDP-17575F2/2021
hCoV-19/England/ALDP-1757598/2021
hCoV-19/England/ALDP-172CA60/2021
hCoV-19/England/ALDP-177F5E5/2021
hCoV-19/England/PHEC-322357/2021
hCoV-19/England/ALDP-1726A0C/2021
hCoV-19/England/ALDP-17377F2/2021
hCoV-19/England/ALDP-1737A62/2021
hCoV-19/England/ALDP-174C781/2021
hCoV-19/England/PORT-1E76FAD/2021
hCoV-19/England/ALDP-17835EE/2021
hCoV-19/England/ALDP-1778DB7/2021
hCoV-19/England/ALDP-17B4E07/2021
hCoV-19/England/ALDP-178641B/2021
hCoV-19/England/ALDP-17A22F1/2021
hCoV-19/England/ALDP-1778142/2021
hCoV-19/England/ALDP-176C26C/2021
hCoV-19/England/PHEC-327941/2021
hCoV-19/England/ALDP-179286B/2021
hCoV-19/England/ALDP-17734C6/2021
hCoV-19/England/ALDP-17A7010/2021
hCoV-19/England/ALDP-17A7098/2021
hCoV-19/England/ALDP-17A9421/2021
hCoV-19/England/ALDP-1786132/2021
hCoV-19/England/ALDP-17CC7C5/2021
hCoV-19/England/QEUH-17715A7/2021
hCoV-19/England/ALDP-1796A25/2021
hCoV-19/England/ALDP-17CCB7E/2021
hCoV-19/England/ALDP-17C97B9/2021
hCoV-19/England/ALDP-17ACA3B/2021
hCoV-19/England/ALDP-17D33A9/2021
hCoV-19/England/HSLL-179DDCB/2021
hCoV-19/England/PHEC-32AB75/2021
hCoV-19/England/PLYM-1793396/2021
hCoV-19/England/MILK-179B000/2021
hCoV-19/England/ALDP-17DD20C/2021
hCoV-19/England/PHEC-32B039/2021
hCoV-19/England/MILK-17B38DD/2021
hCoV-19/England/MILK-17AEDB8/2021
hCoV-19/England/MILK-17B96CE/2021
hCoV-19/England/MILK-17B7709/2021
hCoV-19/England/ALDP-17EF911/2021
hCoV-19/England/PHWC-PYKKQC/2021
hCoV-19/Wales/PHWC-PYKBGF/2021
hCoV-19/England/ALDP-17FF680/2021
hCoV-19/England/MILK-17CBA09/2021
hCoV-19/Wales/PHWC-PYJ33E/2021
hCoV-19/England/ALDP-1801D67/2021
hCoV-19/England/ALDP-17FB3E7/2021
hCoV-19/England/ALDP-17F87DF/2021
hCoV-19/Scotland/QEUH-17F23FF/2021
hCoV-19/England/ALDP-17FF608/2021
hCoV-19/Scotland/QEUH-17D8FCE/2021
hCoV-19/England/PHEC-32EFFD/2021
hCoV-19/England/MILK-17EC56B/2021
hCoV-19/England/MILK-18002D2/2021
hCoV-19/England/MILK-18002B4/2021
hCoV-19/England/PHEC-32EACF/2021
hCoV-19/England/ALDP-180E650/2021
hCoV-19/England/MILK-17F8933/2021
hCoV-19/England/MILK-17F8915/2021
hCoV-19/England/ALDP-180B4D1/2021
hCoV-19/Scotland/QEUH-17FBE13/2021
hCoV-19/England/MILK-17FAEBA/2021
hCoV-19/England/ALDP-1847F7E/2021
hCoV-19/England/MILK-181BE85/2021
hCoV-19/England/MILK-181BE94/2021
hCoV-19/England/MILK-181BE0D/2021
hCoV-19/England/MILK-181298D/2021
hCoV-19/England/MILK-18114D8/2021
hCoV-19/England/MILK-181121A/2021
hCoV-19/England/MILK-181162D/2021
hCoV-19/England/MILK-1822FD3/2021
hCoV-19/England/MILK-1818FEF/2021
hCoV-19/England/MILK-18191D9/2021
hCoV-19/England/MILK-1819063/2021
hCoV-19/England/BRBR-182E450/2021
hCoV-19/England/BRBR-182E58A/2021
hCoV-19/England/BRBR-18376E5/2021
hCoV-19/England/PLYM-1824636/2021
hCoV-19/England/MILK-1866647/2021
hCoV-19/England/BRBR-183D02D/2021
hCoV-19/Scotland/QEUH-182EF04/2021
hCoV-19/England/MILK-18366AA/2021
hCoV-19/England/HSLL-1835289/2021
hCoV-19/England/ALDP-1887B41/2021
hCoV-19/England/MILK-18924EE/2021
hCoV-19/England/QEUH-18733F5/2021
hCoV-19/England/QEUH-1875681/2021
hCoV-19/England/BRBR-185E590/2021
hCoV-19/England/PLYM-183EEE6/2021
hCoV-19/England/BRBR-183A8DD/2021
hCoV-19/England/MILK-184B94F/2021
hCoV-19/England/MILK-184514D/2021
hCoV-19/England/MILK-186AE3C/2021
hCoV-19/England/MILK-18653BA/2021
hCoV-19/England/ALDP-187DEFA/2021
hCoV-19/England/MILK-1874F69/2021
hCoV-19/England/MILK-184B129/2021
hCoV-19/England/BRBR-1850E39/2021
hCoV-19/England/ALDP-18898A2/2021
hCoV-19/England/PHEC-331355/2021
hCoV-19/England/MILK-1877379/2021
hCoV-19/England/ALDP-18896A8/2021
hCoV-19/England/MILK-18A6C58/2021
hCoV-19/England/ALDP-1892BAD/2021
hCoV-19/Wales/BRBR-18649D7/2021
hCoV-19/England/MILK-1873119/2021
hCoV-19/England/MILK-189390C/2021
hCoV-19/England/QEUH-1891B71/2021
hCoV-19/England/MILK-1895C2F/2021
hCoV-19/England/QEUH-1896ABB/2021
hCoV-19/England/MILK-1896E37/2021
hCoV-19/England/MILK-18970E5/2021
hCoV-19/Scotland/QEUH-1891D6C/2021
hCoV-19/England/PLYM-189CD70/2021
hCoV-19/England/PLYM-189D692/2021

**Comment by c19850727** [comment]
There are 362 sequences now.
And 5 out of these 362 sequences have a further **Spike S686N** mutation.

![image](https://user-images.githubusercontent.com/86835836/128300318-f94d4cf4-3a81-4353-bab2-56b9941b8c49.png)

**Comment by chrisruis** [comment]
Thanks @georgimarinov. It looks like this is a subclade within the recently designated AY.4 lineage so we'd recommend referring to these as AY.4
