### ISSUE TITLE
NSP3 SUD-M domain deletion in Chile, in multiple variants, now being recurrent.

### ISSUE THREAD

**Issue by olireiv** [cov-lineages/pango-designation#1450]
In that case, it is more an issue reporting than a new variant.

- With the advanced search for Chile, only good sequences, from 09/10/2022 to 19/12/2022:
_[1-of:ORF1a:Y1423, ORF1a:K1428, ORF1a:T1429, ORF1a:S1433, ORF1a:N1436, ORF1a:D1440] (filter set with good sequences only)_
25 sequences of **various lineages** appear deleted from ORF1a:C1392- to ORF1a:V1441-
That's the exact position of NSP3 SUD domain M.
[Link to covSPECTRUM](https://cov-spectrum.org/explore/Chile/AllSamples/from=2022-10-09&to=2022-12-19/variants?nextcladeQcOverallScoreTo=29&variantQuery=[1-of%3AORF1a%3AY1423%2C+ORF1a%3AK1428%2C+ORF1a%3AT1429%2C+ORF1a%3AS1433%2C+ORF1a%3AN1436%2C+ORF1a%3AD1440]&pangoLineage1=BA.5.2&)

- As a control still in Chile, in the very close NSP3 SUD-N domain, from 01/01/2022 to 19/10/2022:
_[1-of:ORF1a:D1258, ORF1a:N1260, ORF1a:G1261, ORF1a:N1262]  (filter set with good sequences only)_
There are no sequences with a deletion in this domain.
[Link to covSPECTRUM](https://cov-spectrum.org/explore/Chile/AllSamples/from=2022-01-01&to=2022-12-19/variants?nextcladeQcOverallScoreTo=29&variantQuery=[1-of%3AORF1a%3AD1258%2C+ORF1a%3AN1260%2C+ORF1a%3AG1261%2C+ORF1a%3AN1262]&)

- In the five last sequences: EPI_ISL_16161255, EPI_ISL_16161537, EPI_ISL_16161671, EPI_ISL_16157840, EPI_ISL_16161539
The NSP3 deletion is getting bigger, from ORF1a:C1392- to ORF1a:V1457-

I'm not sure what this artefact means.
Could it be a "contamination" with another coronavirus, like HKU1 or OC43, which do not have SUD-M? Producing a jump in the sequencing of SARS-CoV-2 at this position.

**Comment by olireiv** [comment]
Two months later, the artefact is still present, still in the same proportions (4%):
[Link to covSPECTRUM](https://cov-spectrum.org/explore/Chile/AllSamples/from%3D2022-12-19%26to%3D2023-02-18/variants?variantQuery=%5B1-of%3AORF1a%3AY1423%2C+ORF1a%3AK1428%2C+ORF1a%3AT1429%2C+ORF1a%3AS1433%2C+ORF1a%3AN1436%2C+ORF1a%3AD1440%5D&nextcladeQcOverallScoreTo=29&)
And the interesting thing is that the relative growth advantage is now negative: -33%
Let's see if it still spreads, a dominant negative form of the virus? So far that doesn't translate into a different number of deaths.

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by olireiv** [comment]
Closed issue, since it is probably an artifact of the sequencing process, and it doesn't depend on the variant type.
