### ISSUE TITLE
CK.1 Sublineage with S:N856S, S:Y144del (Japan, 40 seq)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1452]
### **Description**
**Sub-lineage of:** CK.1
**Earliest sequence:** 2022-10-27, Japan, Aichi — EPI_ISL_15753943
**Most recent sequence:** 2022-12-2, Japan, Ishikawa — EPI_ISL_16194223
**Countries circulating:** Japan (all 32 sequences)
**Number of Sequences:** 32
**GISAID Query:** Spike_N856S, Spike_K444N, Spike_N460k, Spike_Y144del
**CovSpectrum Query:** Nextcladepangolineage:CK.1* & S:N856S & S:Y144-
**Substitutions on top of CK.1:**
**Spike:** N856S
**Nucleotide:** A24129G
**Deletions on top of CK.1:**
**AA Deletions:** Y144
**Nucleotide Deletions:** 21992-21994
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/CK.1%20%2B%20Y144del%20%2B%20N856S%20-%20subtreeAuspice1_genome_285ac_253ca0.json 
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/33738461/208793513-67a37673-866f-469c-9620-894354b0ef69.png">
 
**Evidence**
As mentioned in Issue #1451, the S:852-859 region seems more active of late. This is not the first recent lineage to pick up S:N856S (see #1419). I elaborated at (probably too much) length in those other issues, so I’ll keep this one short.
 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15753943, EPI_ISL_15831465, EPI_ISL_15907966, EPI_ISL_15916745, EPI_ISL_15916964, EPI_ISL_15923467, EPI_ISL_15923468, EPI_ISL_15923478, EPI_ISL_15923486, EPI_ISL_15923492, EPI_ISL_15954510, EPI_ISL_15982270, EPI_ISL_16040075, EPI_ISL_16040172, EPI_ISL_16040173, EPI_ISL_16040174, EPI_ISL_16060765, EPI_ISL_16093243, EPI_ISL_16093262, EPI_ISL_16121667, EPI_ISL_16121674, EPI_ISL_16138915, EPI_ISL_16165759, EPI_ISL_16165987, EPI_ISL_16166008, EPI_ISL_16176040, EPI_ISL_16176041, EPI_ISL_16176058, EPI_ISL_16194141, EPI_ISL_16194172, EPI_ISL_16194211, EPI_ISL_16194223
</details>

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage CK.1.1 with 20 newly designated sequences, and 0 updated. Defining mutation A24129G (S:N856S) (following T22942G (S:N460K)).
