### ISSUE TITLE
XBB.1 with S:186insSGG [14 sequences as of 2022-12-21, Denmark]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1455]
There's an XBB.1 with an insertion S:186insSGG

14 sequences in Denmark, first collection 23rd of November.

GISAID: `ins186SGG`

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaInsertions=ins_S%3A186%3ASGG& 

Nuc mutation C3241T allows classification without needing to keep track of the insertion.

**Comment by FedeGueli** [comment]
18seqs as today

**Comment by FedeGueli** [comment]
19 sequences as today, last one from denmark.

**Comment by FedeGueli** [comment]
Big jump to 25 . @corneliusroemer @InfrPopGen @thomasppeacock @AngieHinrichs  
ok it is denmark but still to put under monitoring label

**Comment by FedeGueli** [comment]
29 seqs as today

**Comment by FedeGueli** [comment]
35 seqs as today

**Comment by FedeGueli** [comment]
Designated XBB.1.8 milestone missing. @thomasppeacock @InfrPopGen

**Comment by corneliusroemer** [comment]
Designated in https://github.com/cov-lineages/pango-designation/commit/ca43ba883d3fb9895e18a271cc768a8030fcd121 as XBB.1.8
