### ISSUE TITLE
BA.2.75.3 sublineage with S:K356T, S:R346T and Orf1a:V3871I likely emerged in Thailand , circulating in Japan, South Korea , Usa ( 69 sequences ) _ as 01/03/2023

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1457]
I spotted this sublineage of BA.2.75.3 that went under the radar through today probably cause very similar to BA.2.75.5 and BN* tree.
things in my view hinting that this could be true:
Presence of ORF1b:V1706I defining of BA.2.75.3
C25611T & T28693C occuring between S:356T and 346T which both are absent from the BA.2.75.5 tree.

things pointing that this could be an artefact:
Little spread in comparison to original BA.2.75.5

Tree of the  entire sublineage:
<img width="1146" alt="Schermata 2023-01-05 alle 00 30 05" src="https://user-images.githubusercontent.com/87669813/210669395-35e0257a-e30f-4c23-bde5-bc44ce29899a.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_65b2_608350.json?c=userOrOld&label=id:node_7899636
 
Defining mutations:
**BA.2.75.3>S:K356T> C25611T & T28693C>S:346T>G11365T> Orf1a:V3871I (G11876A)**

Gisaid Query:
**Spike_R346T,Spike_K356T, NSP7_V12I** finds 36 sequences 

EPI_ISL_15233172, EPI_ISL_15531573, EPI_ISL_15641224,
EPI_ISL_15641245, EPI_ISL_15757365, EPI_ISL_15757388,
EPI_ISL_15857443, EPI_ISL_15857453, EPI_ISL_15857492,
EPI_ISL_15857557, EPI_ISL_15857575, EPI_ISL_15937456,
EPI_ISL_15941949, EPI_ISL_16012436, EPI_ISL_16028862,
EPI_ISL_16028949, EPI_ISL_16051522, EPI_ISL_16060533,
EPI_ISL_16062297, EPI_ISL_16095505, EPI_ISL_16121731,
EPI_ISL_16121950, EPI_ISL_16121994, EPI_ISL_16123312,
EPI_ISL_16138859, EPI_ISL_16173720, EPI_ISL_16174849,
EPI_ISL_16215120, EPI_ISL_16219562, EPI_ISL_16256823,
EPI_ISL_16259262, EPI_ISL_16273627, EPI_ISL_16292087,
EPI_ISL_16301402, EPI_ISL_16329599, EPI_ISL_16359081,

**Comment by FedeGueli** [comment]
7 viruses as today

**Comment by AngieHinrichs** [comment]
Seems fine to me.  All it has in common with BA.2.75.5 is A22629C (S:K356T), and it also has G22599C (S:R346T) but that's not too surprising, we see that all over the place.  I don't see any reversion branches.  Lots of sequences from different countries share other mutations that set it apart.  Maybe just a matter of luck and/or better competition over time?

**Comment by FedeGueli** [comment]
@corneliusroemer as today designates BL.6 i think it is worth designate this one to complete the BA.2.75 diversity picture (having S:356T as BA.2.75.5 i think.it could help to have it designated to fastly distinguish it)

**Comment by FedeGueli** [comment]
39 sequences as today

**Comment by FedeGueli** [comment]
51 sequences as today , last samples collected show introducrion in european countries as Denmark, Austria and also into USA

**Comment by FedeGueli** [comment]
57 sequences as today last samples from thailand, japan , usa

**Comment by FedeGueli** [comment]
65 sequences as today, last ones from Thailand and Germany

**Comment by FedeGueli** [comment]
68 viruses as today. last ones from Germany and Japan. @corneliusroemer i think it deserves a designation even if it wont compete vs fastest recombinants.

**Comment by FedeGueli** [comment]
one more sequence from california.
