### ISSUE TITLE
Strange BA.5.1 + S:P1162S + S:147/148del growing only in Denmark (600 seq as of 2022-12-22)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1458]
I noticed that BA.5.1 + S:P1162S is growing with a S:147/148del in Danish sequences.

It's strange that this lineage grows at all with current population immunity. It's not even got S:346T and BF.7 is on the way down.

Surely that 2-aa del isn't that special, enough to make it grow like this is XBB or BQ.1.1 - otherwise it would have popped up more often.

Very odd. If anyone has insights, I would appreciate them. I don't feel like designating as is due to concern for artefact. If this was real, it should show up in neighbouring countries, but it hasn't.

https://cov-spectrum.org/explore/Denmark/AllSamples/Past3M/variants?aaMutations=S%3A147-%2CS%3A148-%2CS%3AP1162S&nucMutations=C2142T&nextcladePangoLineage=BA.5.1*&

**Comment by FedeGueli** [comment]
Hi @corneliusroemer i proposed it back in #1382 .
agree with you it is very weird. i ll close my report now that you are on it!

**Comment by InfrPopGen** [comment]
This strange one is still going, with 146 over the past month, and 3 within the last 2wks. There's also some apparent spread (Germany 8, Netherlands 3, Sweden 2, Portugal/Ireland/Belgium 1), but not as much as expected given the transmission in Denmark. The relative growth is also good looking, with 52% Current adv. 49-55% over 6 months in Denmark, 39% Current adv. 37-40% for Europe overall, and 32% Current adv. 15-50% for Germany (although Germany is noisy).  @corneliusroemer it has not conveniently disappeared and remains a curiosity.

**Comment by InfrPopGen** [comment]
This has continued to grow, but more slowly than in its earlier days. Over the past 3 months it is showing a relative disadvantage across Europe, and has not spread significantly in the countries neighbouring Denmark (where it is currently showing almost no positive growth). Consequently, I think this can be closed for now.
