### ISSUE TITLE
Potential new lineage with spike L18R,T95I,R158S,L452M,P681H,A688V,S735A

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#146]
Description
Sub-lineage of: B.1
Clade: 20C
Countries: USA, Mexico
Earliest sequence: 2021-04-16
Most recent sequence: 2021-06-22

34 sequences 
Defining mutations in Spike:
L18R
T95I
R158S
L452M
P681H
A688V
S735A
N960N
T1027I

(Additional to that there are 4 other non synonymous mutations, 2 deletions, 6 synonymous and 2 in extragenic regions). 

5 of the mutations in this lineage are shared with : B.627,B.628 and the lineage described at Pangolin issue 143. 

List of GISAID refence to the sequences are in the first comment

**Comment by shay671** [comment]
[GISAID-Ref.xlsx](https://github.com/cov-lineages/pango-designation/files/6821600/GISAID-Ref.xlsx)

**Comment by chrisruis** [comment]
Thanks @shay671 for submitting. We've added this as lineage B.1.631 in [v1.2.43](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.43)
