### ISSUE TITLE
CR.1 (BA.5.2.18.1) x XBB.1 recombinant [5 seq, 2x UK, 1x US, 1x FR, 1x DK]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1460]
I've come across a BA.5 - XBB.1 recombinant with BA.5 5' end and breakpoint before Spike, around nt pos 20000.

```
hCoV-19/England/QEUH-325F8DE8/2022|EPI_ISL_15939141|2022-11-18
hCoV-19/USA/CA-HLX-STM-DF65Z7QDY/2022|EPI_ISL_16087814|2022-11-14
hCoV-19/France/ARA-HMN-22122070507/2022|EPI_ISL_16234849|2022-11-21
hCoV-19/Scotland/LSPA-32629512/2022|EPI_ISL_16236725|2022-12-07
hCoV-19/Denmark/DCGC-626678/2022|EPI_ISL_16238389|2022-12-14
```

There are extra Spike mutations: P521T, E554G, I870V

![image](https://user-images.githubusercontent.com/25161793/209181169-63f428fa-a26e-44fe-911f-f17da7d3b41e.png)

![image](https://user-images.githubusercontent.com/25161793/209182425-10de24ce-4b83-46e5-95ad-79c0424787f6.png)

![image](https://user-images.githubusercontent.com/25161793/209182443-b4d518f4-1f90-4a24-b988-4efd53d9e08d.png)

https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_216f9_487820.json?label=id:node_9106096

**Comment by corneliusroemer** [comment]
Putting the BA.5 mutations into covSpectrum landed a hit for CR.1 - so that seems to be the BA.5-side donor:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=A8040G%2CG15957T%2C12160A%2C12310A%2C16616A&

**Comment by FedeGueli** [comment]
Wow @corneliusroemer great catch. It has Orf1b:1050N doesnt look at all. Also interesting private spike mutations

**Comment by FedeGueli** [comment]
Gisaid query: E_T11A,Spike_E554G,Spike_P521T,NSP13_T127N

**Comment by FedeGueli** [comment]
One more sequence from Michigan, a young girl, so i presume it is possible that it is circualting more widely than we see

**Comment by FedeGueli** [comment]
Seventh sequence comes from Brunei.

**Comment by FedeGueli** [comment]
8 sequences, the 8th sample came from Canada.

**Comment by FedeGueli** [comment]
10 as today. 2 last from France cc @corneliusroemer

**Comment by corneliusroemer** [comment]
That's what it looks like on Usher:
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/25161793/211229553-b6bbc0c7-02a5-4a05-92c6-13eacb4cc569.png">

https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2e4c4_b70630.json?f_userOrOld=uploaded%20sample&label=id:node_7751250

**Comment by FedeGueli** [comment]
11 sequences as today

**Comment by FedeGueli** [comment]
12 sequences as today last one uploaded yesterday from Austria

**Comment by FedeGueli** [comment]
14 as today

**Comment by FedeGueli** [comment]
one more sequence , total count is 17, 2 of the last 5 samples submitted are from Indonesia , @corneliusroemer maybe this recombination happened there? still not going anywhere as today

**Comment by c19850727** [comment]
total count is 31 (or 30?) as of 2023-03-12.

Interestingly, this proposed recombinant further recombined with a BQ.1*:

![image](https://user-images.githubusercontent.com/86835836/224558372-93f8fb8e-554b-4216-a76b-9081b94136d6.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ba33_dfc590.json?c=gt-nuc_8040,25455&label=id:node_7771803

**Comment by FedeGueli** [comment]
@corneliusroemer @InfrPopGen @thomaspeacock @AngieHinrichs  maybe worth a designation, 30 sequences and the 31th found by great @c19850727 is very unique:
it has;
1 orf1ab from BA.5.2/1050N
2 Spike from.XBB.1 with 3 unique S mutations (521,554,870)
3 E-N from BQ.1 with all proposed as attenuating mutations gone.

**Comment by JosetteSchoenma** [comment]
XBV
