### ISSUE TITLE
Second gen BA.2.3 with 8 spike mutations (12 seqs as of 2022-12-30 - Philippines, Qatar, Germany)

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1462]
**Description**
Sub-lineage of: BA.2.3
Earliest sequence: 2022-07-19, Philippines --- EPI_ISL_14551186
Most recent sequence: 2022-11-13, Germany — EPI_ISL_15901009
Countries circulating: Germany (2), Philippines (1), Qatar (1)
Number of Sequences: 4
GISAID Query: Spike_F490A, Spike_K417T
CovSpectrum Query: S:490A, S:417T
Substitutions on top of BA.2:
Spike: H69-, S:V70-, W152L, N211-, L212I, S255F, R346T, K417T, F490A, A942S
ORF1b: P1452L
ORF7a: A105V
Nucleotides: C2842T, C3787T, C4582T, C17822T, T21765-, A21766-, C21767-, A21768-, T21769-, G21770-, G22017T, A22194-, T22195-, T22196-, C22326T, G22599C, A22812C, T23030G, T23031C, G24386T, C27707T

**USHER Tree**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e97a_530aa0.json?c=gt-S_490&label=id:node_7668507
![image](https://user-images.githubusercontent.com/94097102/209358609-8f940324-6ea6-4ae7-a222-abbfb301a1ca.png)

**Evidence**
This lineage has been observed in 4 different countries across a period of nearly 4 months. The two sequences in Germany are not from the same region. Based on the spike mutations, it isn't necessarily something we'd expect to be very fit. However, with 8 out of 10 AA mutations being in the spike itself, it does look like there was selection happening, even though it has missed most of the current "convergent" RBD mutations. 
That being said, all of the spike mutations are ones we've seen often enough before, except for S:A942S, and S:F490A. S:490 mutations are by far most likely to be S:F490S. After that, their frequency is F>L>V>P>Y>I>A.  
In WT, the S:490 codon is TTT. In the proposed lineage, it is GCT. This means it likely either passed through GTT (Valine/V) or TCT (Serine/S). All or almost all S:F490S codons we are seeing in COVID are 1 NT away from Alanine (A), yet my proposed lineage is still half of the S:F490A sequences within the last 9 months. To me, this means that S:F490A is not likely to be beneficial on the current large lineages with S:F490S such as BN.1 and XBB. If S:F490A is in fact beneficial in the proposed lineage, it could be because of it still retaining S:Q493R, which is absent from almost all currently circulating lineages. 

S:K417T is notable as a mutation that has been very beneficial on some BA.2 lineages, but doesn't seem beneficial on BA.5 lineages, and has largely vanished. This lineage continues to keep the trend that S:K417T does not go well with S:L452R or S:L452M. 

With the first sequence being in the Philippines, and it being a BA.2.3 descendent, it seems a reasonable guess that it emerged in the Philippines, which may be undersampling a region where it is more prominent. With only 4 sequences across the last 4 months, it is hard to tell if the lineage is growing or shrinking. 

**Genomes:** 
EPI_ISL_14551186, EPI_ISL_15901009, EPI_ISL_16149543, EPI_ISL_15922729

**Comment by Sinickle** [comment]
Oh, and credit to @ryhisner for finding 3 of these sequences, which was really the only reason I noticed they were related to begin with!

**Comment by oobb45729** [comment]
Up till now, K417T does not show up often in BA.2.75 sublineages either. I still doubt that L452X is the reason.
L452 is located on the "back" of the RBD, surrounded by (in clockwise order) N450, S494, F490, L492, Y351, and S349. Out of those sites, it seems that N450D and S494P (but not F490S) can work with L452R well.
I noticed that the side chains of R, Q, M all have -CH2-CH2-X like structure. I suspect that the hydrophobic interactions between the -CH2-CH2- part and nearby residues is why those mutations stabilize the RBD. -X part of R452 is positively charged, which may be the reason of the advantage of R452 over Q452 or M452.
T417 is toward another direction. I don't know how L452X would change its fitness.

**Comment by Sinickle** [comment]
@oobb45729 That's really interesting. I was thinking it would be related to L452R because K417T has been really successful on BA.2 but not on BA.5, and the only differences between the two are 69-70del on BA.5, L452R on BA.5, and Q493R on BA.2  
From what you're saying, it sounds more likely that Q493R is likely to be interacting with K417T though, huh? 

Looking through it again, I jumped to conclusions by thinking it was L452R, since L452R and R493Q almost always go together. 
Notably, BH.1 was a successful BA.2 lineage that had 69-70del, L452Q, but still had Q493R. 

Just to double check -- @olias120676 made [this](https://ukcovid.xyz/proximity.php?targetposition=417) program with a .pdb file I found for an Omicron spike. It shows that Spike-452 and Spike-493 are both around 11 angstroms away from Spike-417. I don't have nearly enough expertise to be able to say more than "that's close enough, maybe it interacts." 
You are pretty sure though that even with this close proximity, K417T isn't interacting with L452R? What would your thoughts be on Q493R? I notice you mentioned L492 and S494, but not Q493.

**Comment by oobb45729** [comment]
I'm not sure. The residues are close to each other but their side chains face toward different direction.
https://www.rcsb.org/3d-view/7XB0
Maybe L452R can interfere some N-glycans' positions? 
There's only one BA.4/5 spike trimer structure on RCSB and I have some doubts about its accuracy because it deviates too much from other BA.2-like structures there. If it is accurate though, the N417-Y453-Q493 hydrogen bonds there could help explain why N417T does not happen very often in BA.4/5.

**Comment by ryhisner** [comment]
Seven new sequences of this from Germany today! Brings the total number from 4 to 11.

All seven of the new sequences from Germany have the suboptimal sgmRNA motif near the end of ORF1b that involves three consecutive nucleotide changes: T21294A, G21295A, G21296A. These are the first sequences in this lineage to have this mutational pattern. 

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/33738461/210034595-e256148e-3bab-476c-9a5c-36bd28f63556.png">




<img width="1504" alt="image" src="https://user-images.githubusercontent.com/33738461/210034523-3991dd3f-6366-4f5a-9b13-497ded3208ae.png">

**Comment by AngieHinrichs** [comment]
> three consecutive nucleotide changes: T21294A, G21295A, G21296A.

When there's a run of consecutive or almost-consecutive substitutions like that, in my experience it's usually an artefact, but there are notable exceptions like B.1.1's 28881-28883.  So it would be good to wait and see if that run of mutations is observed using another sequencing & assembly method.  (Netherlands & Germany have had some shared error modes in the past, though they've both been great about fixing them when discovered.)

**Comment by ryhisner** [comment]
This 3-nuc mutation has actually been fairly common throughout the pandemic, much like the nearby 3-nuc-mutational pattern of C21302T, C21304A, G21305A, which has been independently acquired by a multitude of lineages. T21294A, G21295A, G21296A forms a suboptimal sgmRNA "TRS leader" sequence of AAACAAAC (one nuc off of the optimal AAACGAAC), and while I'm not 100% certain of this, I think the TCT sequence adjacent to and preceding the AAACAAAC is the ideal extended homology motif. This is the pattern the N-gene sgmRNA extended homology mutations (A28877T, G28878C) create anyway: 
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/33738461/210110318-524c0965-23d6-453e-a484-832576d82c92.png">


The extended homology mutation for the other major ORF1b sgmRNA TRS leader also changes the second nucleotide before the AAACGAAC to a C, though it creates ACT instead of TCT. 

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/33738461/210110355-05eda2de-8ed2-46cc-b972-b6ac2c72e920.png">

**Comment by FedeGueli** [comment]
12th sequence from Germany

**Comment by FedeGueli** [comment]
one more seq of this one uploaded today. very slow but still around.
