### ISSUE TITLE
DN.1 sublineage with ORF1a:R2159W first detected in England, United Kingdom (115 good and 122 total seqs as of 2022-12-24; Europe, North America)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1463]
There may be a DN.1 sublineage with ORF1a:R2159W (C6740T; also NSP3:R1341W) first detected in England, United Kingdom.

As of 2022-12-23, Cov-Spectrum reports 89 good-quality (95 total) DN.1+ORF1a:2159W sequences searched as BQ.1.1.5+ORF1a:2159W+S:147N.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABQ.1.1.5%2A+%26+ORF1a%3AR2159W+%26+S%3AK147N&nextcladeQcOverallScoreTo=29&

This lineage is showing initial strong growth both overall and in comparison to its parent DN.1.

As of 2022-12-23, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![DN 1+ORF1a_2159W_UShER_CoV-Spectrum](https://user-images.githubusercontent.com/88959107/209408288-963e5faf-ed76-47eb-8aa8-93a70095e4de.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/12/subtreeAuspice1_genome_CoV-Spectrum_DN.1%2BORF1a_2159W.json?c=gt-ORF1ab_2159&label=id%3Anode_6436515

GISAID query: Lineage BQ.1.1.5; AA Substitutions NSP3_R1341W, Spike_K147N

As of 2022-12-23, GISAID search shows 110 sequences.

First GenBank sequence: England, United Kingdom 2022-10-23

Most Recent GenBank sequence: England, United Kingdom 2022-12-07

Most Recent GISAID sequence: Sjaelland, Denmark 2022-12-18

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-DN.1+ORF1a_2159W.zip](https://github.com/cov-lineages/pango-designation/files/10297458/Support-DN.1%2BORF1a_2159W.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-DN.1+ORF1a_2159W.txt](https://github.com/cov-lineages/pango-designation/files/10297460/gisaid-epi-isl-DN.1%2BORF1a_2159W.txt)

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=BQ.1.1.5&muts=ORF1a%3AR2159W&muts=S%3AK147N.

**Comment by AnonymousUserUse** [comment]
@thomasppeacock 
DN.1 is a sublineage of BQ.1.1.5, so the label should be BA.5 instead of BA.2.75.
By the way, I propose to use the label BQ.1 for the sublineage of that (since BQ.1 has been designated as a separate Nextstrain clade and there is already a high number of pango-designation issues of BQ.1 sublineages).

**Comment by thomasppeacock** [comment]
Oh you are completely correct - and yes with the amount of BQ.1 lineage cropping up now I agree it makes sense to have a seperate catagory.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage DN.1.1 with 0 newly designated sequences, and 70 updated. Defining mutation C6740T (ORF1a:R2159W) (following A22003T (S:K147N)).

**Comment by ryhisner** [comment]
THere's an interesting five-sequence branch within this lineage form England with S:Y453F, ORF1a:V721I, and ORF1a:N2752S. Only three of the sequences are on GISAID right now, and there seems to be about a 5-day delay between when these sequences appear on the USHER tree and when they show up on GISAID. 
EPI_ISL_16281024, EPI_ISL_16281338, EPI_ISL_16281597
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42ca2_9aec80.json?label=id:node_3395515

**Comment by corneliusroemer** [comment]
Good spot @ryhisner - also saw this just now. It's now some 25 sequences, so I designated as DN.1.1.1
