### ISSUE TITLE
XAY.2 cluster shows  S:F486H 2 seqs Denmark

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1464]
Here i want to highlight this mutation that popped up in two XAY.2 sequences in Denmark.
Before this day it was found in just other 2 legit sequences and one very dubious from India.

Gisaid Query: Spike_f486H,Spike_F186L

Sequences:EPI_ISL_16170165, EPI_ISL_16238663

Defining mutations: 

C823T , ORF1a:T2495I (C7749T), C29518T then 

S:F486P (C23019A), N:P162S (C28757T)

Tree: (Note that Usher calls it S:F486Y)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_304f1_6375b0.json?c=gt-S_486&label=id:node_8125696
<img width="1160" alt="Schermata 2022-12-24 alle 00 29 28" src="https://user-images.githubusercontent.com/87669813/209413231-336206fd-9df2-4f95-b24e-7562671ae412.png">

**Comment by oobb45729** [comment]
Both H and F are aromatic. I wonder whether H486 can escape antibodies that target F486 well.

Speaking of Danish XAYs, I noticed a few XAY.2 and one XAY.1.1 have S:69-70del. I don't know if they are real or not.

**Comment by Sinickle** [comment]
The predicted ACE2 binding affinity relative to BA.2 drops from 0.61 to 0.32 with this mutation (P486H) I believe.  

It looks like Spike_P486 is really the first chance the virus has really had to acquire Spike_H486 though.

**Comment by FedeGueli** [comment]
it seems dead. i will wait just some more days to close it to be sure it is dusted

**Comment by FedeGueli** [comment]
Closing cause no new sequence popped up
