### ISSUE TITLE
BA.5.2+ORF1b:T1050N sublineage circulating in China (312 seq as of 2023-01-06)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#1471]
Proposal for a sublineage of BA.5.2.
Earliest seq: 2022-10-05 (Guangdong, China)
Countries detected: Singapore (16, including 9 travellers from China and 2 travellers from Hong Kong), China (7, all from Guangdong), Cambodia (1), England (1, yet to be uploaded to GISAID)

Mutations on top of BA.5.2:
G12310A, ORF1b:T1050N, C27012T, C27513T (the main branch of BA.5.2+ORF1b:T1050N)
then C2710T, then C8626T, then C16887T+T17208C (note C16887T is extremely homoplasic so doesn't show up on Usher)

GISAID query: nuc mutations C2710T, C8626T, T17208C

This is one of two major lineages that appear to be circulating in China, along with the BF.7 lineage in #1470. Like that lineage, it was present in China long before the end of the zero-Covid policy and therefore appears to be growing as the result of a founder effect. ORF1b:T1050N is the only AA mutation that distinguishes this from BA.5.2, but as BA.5.2+ORF1b:T1050N was never designated, I believe this lineage should still be eligible for designation.

The majority of the sequences in this lineage also have C11824T. Due to a single sequence from Japan on the C2710T+C8626T branch containing this mutation, along with the masking of C16887T, Usher has split the lineage into two separate branches on the tree, one with C11824T and one without. It's pretty clear that Usher has got this wrong.

Usher tree for sequences with C11824T:

<img width="733" alt="China_BA52_1" src="https://user-images.githubusercontent.com/42699509/209497438-5b4a3567-628d-48ce-97d1-b02ebd1cc32a.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2c776_9157f0.json?branchLabel=Spike%20mutations&c=gt-nuc_17208&label=id:node_7079342](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2c776_9157f0.json?branchLabel=Spike%20mutations&c=gt-nuc_17208&label=id:node_7079342)

Usher tree for sequences without C11824T:

<img width="682" alt="China_BA52_2" src="https://user-images.githubusercontent.com/42699509/209497617-99e29e27-b744-43f4-b41d-0bd5550cfadd.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2c8a3_915a30.json?branchLabel=Spike%20mutations&c=gt-nuc_17208&label=id:node_7079778](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2c8a3_915a30.json?branchLabel=Spike%20mutations&c=gt-nuc_17208&label=id:node_7079778)

[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2*+%26+%5B5-of%3A+G12310A%2C+ORF1b%3AT1050N%2C+C27012T%2C+C27513T%2C+C2710T%2C+C8626T%5D+%26+C16887T+%26+T17208C&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2*+%26+%5B5-of%3A+G12310A%2C+ORF1b%3AT1050N%2C+C27012T%2C+C27513T%2C+C2710T%2C+C8626T%5D+%26+C16887T+%26+T17208C&)

<details><summary>EPI_ISLs</summary>

EPI_ISL_16181562
EPI_ISL_16181568
EPI_ISL_16259461
EPI_ISL_16259462
EPI_ISL_16259465
EPI_ISL_16259469
EPI_ISL_16259474
EPI_ISL_16259475
EPI_ISL_16259477
EPI_ISL_16259479
EPI_ISL_16259481
EPI_ISL_16259483
EPI_ISL_16259489
EPI_ISL_16259494
EPI_ISL_16259504
EPI_ISL_16259506
EPI_ISL_16264215
EPI_ISL_16264216
EPI_ISL_16264219
EPI_ISL_16264220
EPI_ISL_16264221
EPI_ISL_16264222
EPI_ISL_16264223
EPI_ISL_16274001
</details>

**Comment by AnonymousUserUse** [comment]
I do not think we can conclude that the majority of the people infected by this lineage also have C11824T. If we exclude the sequences uploaded from China (which is strongly biased by the province that uploads sequences), only 11 from 18 sequences have this mutation.

**Comment by FedeGueli** [comment]
Now this counts 75 sequences if i got correctly the nucleotides gisaid query  : C2710T, C8626T, T17208C.

@InfrPopGen @corneliusroemer @AngieHinrichs @thomasppeacock i think a rapid designation is deserved:
1) already three sublineages of this one have been proposed
2) tripled in the first day we had aknowledgement of it
3) Likely it could account for thousands of viruses in China during in this wave.

**Comment by silcn** [comment]
> 3. Likely it could account for thousands of viruses in China during in this wave.

That's an understatement - this and #1470 could together account for as many of half of all infections worldwide right now. Seems like a pretty strong case for designation.

**Comment by FedeGueli** [comment]
> > 3. Likely it could account for thousands of viruses in China during in this wave.
> 
> That's an understatement - this and #1470 could together account for as many of half of all infections worldwide right now. Seems like a pretty strong case for designation.

yeah agree. i just avoided  big claims, the ones who will designate it know that very well ;)

**Comment by FedeGueli** [comment]
Correction actually it is 74 not 75 one sequence caught by Gisaid query C2710T, C8626T, T17208C is a totally unrelated bat virus from Yunnan.

**Comment by silcn** [comment]
Thanks for reminding me @FedeGueli, I had removed that sequence from the initial count but then forgot about it.

**Comment by FedeGueli** [comment]
> Thanks for reminding me @FedeGueli, I had removed that sequence from the initial count but then forgot about it.

nevermind it was a fault of mine.

**Comment by FedeGueli** [comment]
96 viruses as today

**Comment by FedeGueli** [comment]
102 viruses as today two new ones from India and one from California

**Comment by AngieHinrichs** [comment]
> Due to a single sequence from Japan on the C2710T+C8626T branch containing this mutation, along with the masking of C16887T, Usher has split the lineage into two separate branches on the tree, one with C11824T and one without. It's pretty clear that Usher has got this wrong.

Thanks @silcn.  I will try to fix that today.

**Comment by FedeGueli** [comment]
157 viruses as today. well represented in Shangai too. An exception to the not NUC only rules should be done to designate it . otherwise our work in tracking sublineages of it will be much harder .

**Comment by AngieHinrichs** [comment]
> Due to a single sequence from Japan on the C2710T+C8626T branch containing this mutation, along with the masking of C16887T, Usher has split the lineage into two separate branches on the tree, one with C11824T and one without. It's pretty clear that Usher has got this wrong.

I had to permanently exclude Japan/PG-356772/2022|EPI_ISL_15261684|2022-09-06 to stop matOptimize from splitting up T17208C, but it's intact in the 2022-12-30 tree.  [Not the initial version that rolled out at 7pm Pacific time yesterday, but an updated version from this morning that rolled out at 7am.]

**Comment by FedeGueli** [comment]
182 sequences as today. new upload from Bejing today

**Comment by FedeGueli** [comment]
216 as Now . Mass upload from Pechino plus more sequences from American airports.

**Comment by FedeGueli** [comment]
@thomasppeacock @corneliusroemer @InfrPopGen @AngieHinrichs 

the tree of this one looks like this now, and after the great catch by @SIlcn also its three proposed sublineages seem very well supported and there is one ore unproposed:
<img width="1146" alt="Schermata 2023-01-03 alle 09 08 02" src="https://user-images.githubusercontent.com/87669813/210319670-985ee9c7-f8f9-41fa-92df-8397f2f81955.png">



Indeed I proposed to designate everything in a row:
[ ] T17208C Parental lineage from this issue (#1471) 

then its main branches:
[ ] N:Q241K : .1  From #1478 
[ ] Orf1a:T1788M: .2 from #1472
[ ] Orf1b:T4432I: .3.  - 
[ ] S:A570S: .4  From #1479

**Comment by FedeGueli** [comment]
233 sequences as today: new samples come from Italy , Spallanzani institute, also in this case as the other BF.7 issue they are all from BAL, probably a sampling strategy choosen to try to isolate the virus then? i dont know.

**Comment by FedeGueli** [comment]
253 sequences as the BF.7 they are now appearing in mass.
Interesting one sample was sequenced in Chongqing too. Many samples from Lazio Italy and Singapore

**Comment by FedeGueli** [comment]
2 new sequences from Japanese airport surveillance. 
1 from California, 1 from Washington, 1 from Gujarat these last 3 dont seem to be related with inbound travels testing.

**Comment by FedeGueli** [comment]
280 as this evening , several sequences uploaded from Singapore: 7 from  airport surveillance but also 12 local cases.
Apparent local cases also from India and Austria

**Comment by FedeGueli** [comment]
300 as today it seems highly prevalent in the first samples from Hunan

**Comment by FedeGueli** [comment]
312 as today last samples coming from England Denmark Italy and India.
I repeat here what i wrote on the proposed BF.7 lineage issue. Wondering if India could be more at danger with these lineages imported from China not having had a real BA.5 wave. tagging @karyakarte allways on the battllefield .

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.48 with 217 newly designated sequences, and 0 updated. Defining mutations T17208C, C16887T (following C8626T).

**Comment by AngieHinrichs** [comment]
FYI 16887 is masked in the UShER tree because it is in https://github.com/W-L/ProblematicSites_SARS-CoV2 .

**Comment by AnonymousUserUse** [comment]
> then its main branches: [ ] N:Q241K : .1 From #1478 [ ] Orf1a:T1788M: .2 from #1472 [ ] Orf1b:T2432I: .3. - [ ] S:A570S: .4 From #1479

A sublineage of branch 3 is now proposed in https://github.com/cov-lineages/pango-designation/issues/1620.

**Comment by Mild1-ai** [comment]
> > then its main branches:
> > [ ] N:Q241K : .1 From #1474
> > [ ] Orf1a:T1788M: .2 from #1472
> > [ ] Orf1b:T2432I: .3. -
> > [ ] S:A570S: .4 From #1479
> 
> Just for notes: as of 2023/2/19, all these four branches have been designated as DY.2, DY.3, DY.4, and DY.1, respectively.

I noticed this, it is worth mentioning: #1474 is circulating in Japan

**Comment by AnonymousUserUse** [comment]
> > > then its main branches:
> > > [ ] N:Q241K : .1 From #1474
> > > [ ] Orf1a:T1788M: .2 from #1472
> > > [ ] Orf1b:T2432I: .3. -
> > > [ ] S:A570S: .4 From #1479
> > 
> > 
> > Just for notes: as of 2023/2/19, all these four branches have been designated as DY.2, DY.3, DY.4, and DY.1, respectively.
> 
> I noticed this, it is worth mentioning: #1474 is circulating in Japan

I have updated the correct issue. It should be #1478 instead of #1474.
