### ISSUE TITLE
BA.5.2.48 sublineage with ORF1a:T1788M and Nuc mutation C4573T previously mainly circulating in China, Guangdong (884 seq as of 2022-2-5)

### ISSUE THREAD

**Issue by zhchang5-GDCDC** [cov-lineages/pango-designation#1472]
Proposal for a sublineage of BA.5.2.48
Earliest seq: 2022-11-17 (Guangdong, China)
Countries detected: China (total 18, 5 from Guangdong, 5 from Fujian, 3 from Hunan, 2 from Shanghai, 2 from Zhejiang and 1 from Sichuan, ), South Korea (20), Singapore (15), Japan (15), USA (4), Australia (3), Thailand (2), Malaysia (2), Canada (2), Netherlands (1), South Africa (1), Switzerland (1), Cambodia (1).

Defining mutations:
BA.5.2 + ORF1a:T1788M (C5628T)
then
C4573T

![捕获2](https://user-images.githubusercontent.com/121416696/212449439-130bc601-4278-4288-9cc1-d5a311d537d6.PNG)

[https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_32c82_224cc0.json?branchLabel=nuc%20mutations&c=userOrOld&label=id:node_7367216](url)

This is the major lineages that appear to be circulating in South China (Guangdong province), it was present in Guandong before the end of the zero-Covid policy and become dominant after wide spreading. ORF1a:T1788M is the only AA mutation that distinguishes this from nearby BA.5.2 sequences, but as BA.5.2+ORF1a:T1788M was never designated, I believe this lineage should still be eligible for designation. Since the high prevalence of this lineage, even the takeover by BQ.1* and XBB* will still be a long time within which a new BA.5.2 lineage is necessary for the tracking of coronavirus mutation state in China.

Gisaid query : C5628T, C4573T finds 85 Sequences:
EPI_ISL_16181562,EPI_ISL_16274001,EPI_ISL_16264219,
EPI_ISL_16264220,EPI_ISL_16264221,EPI_ISL_16264222,
EPI_ISL_16264223,EPI_ISL_16283983,EPI_ISL_16283984,
EPI_ISL_16294667,EPI_ISL_16327468,EPI_ISL_16327560,
EPI_ISL_16340467,EPI_ISL_16334609,EPI_ISL_16334627,
EPI_ISL_16334620,EPI_ISL_16352291,EPI_ISL_16352298,
EPI_ISL_16352278,EPI_ISL_16386874,EPI_ISL_16378866,
EPI_ISL_16378864,EPI_ISL_16378857,EPI_ISL_16378860,
EPI_ISL_16390371,EPI_ISL_16390377,EPI_ISL_16390394,
EPI_ISL_16413637,EPI_ISL_16412739,EPI_ISL_16415266,
EPI_ISL_16415292,EPI_ISL_16415296,EPI_ISL_16428136,
EPI_ISL_16428143,EPI_ISL_16428145,EPI_ISL_16436283,
EPI_ISL_16449824,EPI_ISL_16452766,EPI_ISL_16445099,
EPI_ISL_16460306,EPI_ISL_16456560,EPI_ISL_16465905,
EPI_ISL_16465949,EPI_ISL_16481351,EPI_ISL_16481442,
EPI_ISL_16486743,EPI_ISL_16486744,EPI_ISL_16483088,
EPI_ISL_16483078,EPI_ISL_16483090,EPI_ISL_16501812,
EPI_ISL_16513918,EPI_ISL_16514106,EPI_ISL_16506749,
EPI_ISL_16513924,EPI_ISL_16513928,EPI_ISL_16495550,
EPI_ISL_16506330,EPI_ISL_16506397,EPI_ISL_16506398,
EPI_ISL_16514016,EPI_ISL_16514017,EPI_ISL_16510359,
EPI_ISL_16504748,EPI_ISL_16506501,EPI_ISL_16514168,
EPI_ISL_16514170,EPI_ISL_16514171,EPI_ISL_16514257,
EPI_ISL_16514258,EPI_ISL_16494580,EPI_ISL_16494582,
EPI_ISL_16503662,EPI_ISL_16494593,EPI_ISL_16494644,
EPI_ISL_16494652,EPI_ISL_16494653,EPI_ISL_16494630,
EPI_ISL_16494632,EPI_ISL_16494666,EPI_ISL_16494670,
EPI_ISL_16495695,EPI_ISL_16495746,EPI_ISL_16514266,
EPI_ISL_16506517

**Comment by silcn** [comment]
Note that this is a sublineage of #1471. There are two more sequences from Guangdong on the T17208C branch (really the C11824T branch, see #1471) before ORF1a:T1788M.

**Comment by zhchang5-GDCDC** [comment]
41 seq as of 2023-01-11

**Comment by FedeGueli** [comment]
@zhchang5-GDCDC this is a sublineage of BA.5.2.48 now! It would be great the proposal would be updated.

**Comment by zhchang5-GDCDC** [comment]
85 seq as of 2023-01-13

**Comment by AnonymousUserUse** [comment]
309 sequences as of 2023-01-25 per CoV-Spectrum, including 195 sequences in mainland China, including 87 sequences in Guangdong province (73.5% in last 2 months).
Considering the clear geographical focus within China, I think this lineage deserves designation.
![image](https://user-images.githubusercontent.com/113214374/214704247-81292e9c-9ffc-409a-9dd3-67d1e1c45bc5.png)

**Comment by zhchang5-GDCDC** [comment]
884 sequences as of 2023-02-05, including 745 sequences in mainland China, including 518 sequences in Guangdong province (77.5% in last 2 months).

**Comment by FedeGueli** [comment]
A sublineage of DY.3 seems be defined by S:F1121L @AnonymousUserUse
