### ISSUE TITLE
BA.5.2.6 sublineage defined by S:N703Y , 215 sequences (as 01/March/23) from Japan that acquired further multiple AA mutations Orf7a:E41D, Orf8:R52I, Orf1a:Y182H, Orf3a:I47V

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1473]
Just spotted a sublineage of BA.5.2.6 circulating in Japan that appears to be quite competitive versus [ S:460K](https://cov-spectrum.org/explore/Japan/AllSamples/Past2M/variants?aaMutations=S%3A346T&aaMutations1=S%3AN703Y%2COrf7a%3AE41D%2COrf8%3AR52I%2COrf1a%3AY182H%2COrf3a%3AI47V&analysisMode=CompareToBaseline&) carrying lineages, vs [S:346T](https://cov-spectrum.org/explore/Japan/AllSamples/Past2M/variants?aaMutations=S%3A346T&aaMutations1=S%3AN703Y%2COrf7a%3AE41D%2COrf8%3AR52I%2COrf1a%3AY182H%2COrf3a%3AI47V&analysisMode=CompareToBaseline&) carrying lineages , vs [BF.5](https://cov-spectrum.org/explore/Japan/AllSamples/Past2M/variants?aaMutations=S%3AA1020S&aaMutations1=S%3AN703Y%2COrf7a%3AE41D%2COrf8%3AR52I%2COrf1a%3AY182H%2COrf3a%3AI47V&analysisMode=CompareToBaseline&) lineages and not far from[ S:F486P](https://cov-spectrum.org/explore/Japan/AllSamples/Past2M/variants?aaMutations=S%3AF486P&aaMutations1=S%3AN703Y%2COrf7a%3AE41D%2COrf8%3AR52I%2COrf1a%3AY182H%2COrf3a%3AI47V&analysisMode=CompareToBaseline&) lineages

**Defining mutations:**
**BA.5.2.6**   > E:I9T (_REVERSION_ - T26270C)  > S:N703Y (A23669T) > T7831C > Orf7a:E41D (G27516T) > Orf8:R52I (G28048T) > Orf1a:Y182H (T809C), Orf3a:I47V (A25531G)

**Tree**:
<img width="1147" alt="Schermata 2022-12-26 alle 17 01 51" src="https://user-images.githubusercontent.com/87669813/209565955-41f62201-8ad7-4a47-aa67-2516d44e8dda.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_195c2_9c0ab0.json?label=id:node_7091291

**Gisaid query**: Spike_N703Y, NS3_I47V,NS8_R52I,NS7a_E41D finds 29 sequences from Japan

EPI_ISL_15571304, EPI_ISL_15784584, EPI_ISL_15823684,
EPI_ISL_15875361, EPI_ISL_15875613, EPI_ISL_15894498,
EPI_ISL_15997390, EPI_ISL_16060453, EPI_ISL_16079137,
EPI_ISL_16094074, EPI_ISL_16138662, EPI_ISL_16166137,
EPI_ISL_16175723, EPI_ISL_16176042, EPI_ISL_16176063-16176064,
EPI_ISL_16209846, EPI_ISL_16210873, EPI_ISL_16255318,
EPI_ISL_16273121, EPI_ISL_16273225, EPI_ISL_16279396-16279397,
EPI_ISL_16279518-16279520, EPI_ISL_16279676, EPI_ISL_16279774,
EPI_ISL_16279777

**Comment by FedeGueli** [comment]
35 sequences as today, further spreading in Japan only.

**Comment by FedeGueli** [comment]
36 as today

**Comment by FedeGueli** [comment]
Growing slowly i'll close this one

**Comment by agamedilab** [comment]
Hi @FedeGueli, this now has 218 seq of which c. 50% are relative recent (2023). Maybe worth reopening?

![grafik](https://user-images.githubusercontent.com/102166254/221117845-26ae8eba-1fb8-4a42-8873-325de3aa4ebd.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24ece_862c00.json?c=country

![grafik](https://user-images.githubusercontent.com/102166254/221118509-d137a2d3-db1a-43f1-ad6a-b9074e11c8fc.png)


EPI_ISL_15189980, EPI_ISL_15188557, EPI_ISL_14950077, EPI_ISL_15417307, EPI_ISL_15361474, EPI_ISL_15244954, EPI_ISL_15502611, EPI_ISL_15597216, EPI_ISL_15342895, EPI_ISL_15571304, EPI_ISL_15784584, EPI_ISL_15875361, EPI_ISL_16123719, EPI_ISL_15823684, EPI_ISL_16079137, EPI_ISL_15875613, EPI_ISL_15894498, EPI_ISL_16094074, EPI_ISL_16123669, EPI_ISL_15997390, EPI_ISL_16060453, EPI_ISL_16209846, EPI_ISL_16176042, EPI_ISL_16175723, EPI_ISL_16255318, EPI_ISL_16138662, EPI_ISL_16481129, EPI_ISL_16210873, EPI_ISL_16166137, EPI_ISL_16432801, EPI_ISL_16284403, EPI_ISL_16279397, EPI_ISL_16279396, EPI_ISL_16176064, EPI_ISL_16404308, EPI_ISL_16431635, EPI_ISL_16176063, EPI_ISL_16279519, EPI_ISL_16279518, EPI_ISL_16279520, EPI_ISL_16389996, EPI_ISL_16273225, EPI_ISL_16502168, EPI_ISL_16502361, EPI_ISL_16279676, EPI_ISL_16299179, EPI_ISL_16273121, EPI_ISL_16498719, EPI_ISL_16498720, EPI_ISL_16499736, EPI_ISL_16500182, EPI_ISL_16299300, EPI_ISL_16299294, EPI_ISL_16404519, EPI_ISL_16455686, EPI_ISL_16502518, EPI_ISL_16500108, EPI_ISL_16559521, EPI_ISL_16279774, EPI_ISL_16577239, EPI_ISL_16577215, EPI_ISL_16455740, EPI_ISL_16279777, EPI_ISL_16645013, EPI_ISL_16466983, EPI_ISL_16675532, EPI_ISL_16716521, EPI_ISL_16644504, EPI_ISL_16720430, EPI_ISL_16677492, EPI_ISL_16677758, EPI_ISL_16677869, EPI_ISL_16559263, EPI_ISL_16590374, EPI_ISL_16590375, EPI_ISL_16373786, EPI_ISL_16298604, EPI_ISL_16298605, EPI_ISL_16559261, EPI_ISL_16559503, EPI_ISL_16481963, EPI_ISL_16521761, EPI_ISL_16644496, EPI_ISL_16559373, EPI_ISL_16592509, EPI_ISL_16559426, EPI_ISL_16644545, EPI_ISL_16559440, EPI_ISL_16644252, EPI_ISL_16521939, EPI_ISL_16644311, EPI_ISL_16644318, EPI_ISL_16720353, EPI_ISL_16716394, EPI_ISL_16720354, EPI_ISL_16720336, EPI_ISL_16698378, EPI_ISL_16544933, EPI_ISL_16644461, EPI_ISL_16692899, EPI_ISL_16720189, EPI_ISL_16580436, EPI_ISL_16521499, EPI_ISL_16521497, EPI_ISL_16716481, EPI_ISL_16718439, EPI_ISL_16718408, EPI_ISL_16973267, EPI_ISL_16843288, EPI_ISL_16972198, EPI_ISL_16949422, EPI_ISL_16559531, EPI_ISL_16970956, EPI_ISL_16807222, EPI_ISL_16970927, EPI_ISL_16644736, EPI_ISL_16948591, EPI_ISL_16637442, EPI_ISL_16971014, EPI_ISL_16971013, EPI_ISL_16808186, EPI_ISL_16637305, EPI_ISL_16715192, EPI_ISL_16970999, EPI_ISL_16580497, EPI_ISL_16676133, EPI_ISL_16736484, EPI_ISL_16676143, EPI_ISL_16617856, EPI_ISL_16644935, EPI_ISL_16827979, EPI_ISL_16809367, EPI_ISL_16676167, EPI_ISL_16632573, EPI_ISL_16964952, EPI_ISL_16632949, EPI_ISL_16841491, EPI_ISL_16809641, EPI_ISL_16716210, EPI_ISL_16716224, EPI_ISL_16580797, EPI_ISL_16747733, EPI_ISL_16948679, EPI_ISL_16809638, EPI_ISL_16747817, EPI_ISL_16949816, EPI_ISL_16971184, EPI_ISL_16948516, EPI_ISL_16971268, EPI_ISL_16747869, EPI_ISL_16716299, EPI_ISL_16716285, EPI_ISL_16974266, EPI_ISL_16842363, EPI_ISL_16716322, EPI_ISL_16842619, EPI_ISL_16948661, EPI_ISL_16747111, EPI_ISL_16638442, EPI_ISL_16971375, EPI_ISL_16806091, EPI_ISL_16747112, EPI_ISL_16807696, EPI_ISL_16825645, EPI_ISL_16825651, EPI_ISL_17014291, EPI_ISL_16806130, EPI_ISL_16950225, EPI_ISL_16747227, EPI_ISL_16974059, EPI_ISL_16974072, EPI_ISL_16971100, EPI_ISL_16747234, EPI_ISL_16974152, EPI_ISL_16806310, EPI_ISL_16825745, EPI_ISL_16948244, EPI_ISL_16974219, EPI_ISL_16974161, EPI_ISL_16974672, EPI_ISL_16974300, EPI_ISL_16974299, EPI_ISL_16881142, EPI_ISL_16950596, EPI_ISL_16971358, EPI_ISL_16975463, EPI_ISL_16974865, EPI_ISL_16974643, EPI_ISL_16974872, EPI_ISL_16972086, EPI_ISL_17014505, EPI_ISL_17014504, EPI_ISL_17014424, EPI_ISL_16951280, EPI_ISL_16973582, EPI_ISL_17014473, EPI_ISL_16973880, EPI_ISL_16971793, EPI_ISL_17014462, EPI_ISL_17014562, EPI_ISL_17014583, EPI_ISL_16948309, EPI_ISL_16949055, EPI_ISL_16973969, EPI_ISL_16965266, EPI_ISL_16973621, EPI_ISL_16965274, EPI_ISL_17014615, EPI_ISL_17014454, EPI_ISL_16973851, EPI_ISL_17014556, EPI_ISL_17014577, EPI_ISL_16972966, EPI_ISL_17015286, EPI_ISL_17014178, EPI_ISL_17015325, EPI_ISL_17015329, EPI_ISL_17014595

**Comment by FedeGueli** [comment]
> Hi @FedeGueli, this now has 218 seq of which c. 50% are relative recent (2023). Maybe worth reopening?
> 
> ![grafik](https://user-images.githubusercontent.com/102166254/221117845-26ae8eba-1fb8-4a42-8873-325de3aa4ebd.png) https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24ece_862c00.json?c=country
> 
> ![grafik](https://user-images.githubusercontent.com/102166254/221118509-d137a2d3-db1a-43f1-ad6a-b9074e11c8fc.png)
> 


Thank you @agamedilab , 215 as today

**Comment by FedeGueli** [comment]
@InfrPopGen could you take a look at this one. it was closed for a while but ot keeps on circulating in Japan

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage CP.7 with 206 newly designated sequences, and 0 updated. Defining mutations T809C (ORF1a:Y182H), A25531G (ORF3a:I47V)  (following G28048T (ORF8:R52I)).
