### ISSUE TITLE
BA.5.2.7 sublineage circulating in Japan with S:T1066N, N:P20S, Orf1a:I2490S - 265 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1474]
Amongst the multiple lineages evolved from "first generation BA.5.2* sublineages " which are still dominating Japan giving birth a huge wave without (or better saying just partially showing ) the convergent RBD evolution and instead a costellation of Spike/Non spike mutations,I noticed one that i think it is worth to be proposed  defined by a triple mutation: S:T1066N, N:P20S, Orf1a:I2490S

**Defining mutations**:
_**BA.5.2.7** + C3695T > C3619T, C16954T, C18312T, **S:T1066N** (C24759A)> **N:P20S** (C28331T)> **Orf1a:I2490S** (T7734G)_

**Gisaid Query**: N_P20S ,Spike_T1066N,NSP3_I1672S

**Tree**:
<img width="1157" alt="Schermata 2022-12-26 alle 18 26 20" src="https://user-images.githubusercontent.com/87669813/209571589-a5536d13-6fd6-4d2c-815c-8e4548c62a67.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24fed_9d4970.json?c=userOrOld&label=id:node_6909618

CovSpectrum comparison vs dominant BF.5 : 
<img width="927" alt="Schermata 2022-12-26 alle 18 27 46" src="https://user-images.githubusercontent.com/87669813/209571677-110ed7df-8b83-4f6f-8dee-79c22000844b.png">
https://cov-spectrum.org/explore/Japan/AllSamples/Past2M/variants?aaMutations=S%3AA1020S&aaMutations1=S%3AT1066N%2CN%3A20S&nextcladePangoLineage1=BA.5.2.7*&analysisMode=CompareToBaseline&

**Sequences**:
<details>
<summary>Expand for EPI_ISLs</summary>
EPI_ISL_15642839, EPI_ISL_15823596, EPI_ISL_15833048,
EPI_ISL_15838588, EPI_ISL_15838612, EPI_ISL_15852952,
EPI_ISL_15853056, EPI_ISL_15853469, EPI_ISL_15909381,
EPI_ISL_15909982, EPI_ISL_15910370, EPI_ISL_15910672,
EPI_ISL_15923966, EPI_ISL_15924750, EPI_ISL_15925084,
EPI_ISL_15925168, EPI_ISL_16000002, EPI_ISL_16000426,
EPI_ISL_16051666, EPI_ISL_16051776, EPI_ISL_16060248,
EPI_ISL_16060343, EPI_ISL_16060481, EPI_ISL_16060613,
EPI_ISL_16078345, EPI_ISL_16078387, EPI_ISL_16094095,
EPI_ISL_16107692, EPI_ISL_16111810, EPI_ISL_16121305,
EPI_ISL_16122514, EPI_ISL_16122967, EPI_ISL_16123089,
EPI_ISL_16123173, EPI_ISL_16123946, EPI_ISL_16174457,
EPI_ISL_16175663, EPI_ISL_16175675, EPI_ISL_16176060,
EPI_ISL_16192850, EPI_ISL_16193412, EPI_ISL_16210037,
EPI_ISL_16210875, EPI_ISL_16240814, EPI_ISL_16254144,
EPI_ISL_16254286, EPI_ISL_16254449, EPI_ISL_16254875,
EPI_ISL_16255027, EPI_ISL_16255216, EPI_ISL_16255463,
EPI_ISL_16255979, EPI_ISL_16257380, EPI_ISL_16273484,
EPI_ISL_16273493, EPI_ISL_16279407, EPI_ISL_16279521,
EPI_ISL_16279943
</details>

**Comment by FedeGueli** [comment]
63 sequences as today

**Comment by FedeGueli** [comment]
68 sequences

**Comment by FedeGueli** [comment]
This is growing steadily, too slow to deseerve to be designated. i m closing it.

**Comment by FedeGueli** [comment]
16 viruses uploaded in the last two days from Japan, worth reopening this issue to watch if it calms down or keeps expanding

**Comment by FedeGueli** [comment]
100 Sequences of this one as today

**Comment by FedeGueli** [comment]
142 sequences as today it is growing steadily @InfrPopGen

**Comment by FedeGueli** [comment]
I am closing this one.

**Comment by FedeGueli** [comment]
179 sequences as today, it is growing steadily i reopen it for the moment

**Comment by FedeGueli** [comment]
189 sequences

**Comment by FedeGueli** [comment]
238 sequences, i prefer to close this one cause BA.5 is shrinking everywhere if it will survive in any form i will be ready to reopen

**Comment by FedeGueli** [comment]
this is still circualting in Japan keeping its 0,3% of share, worth looking at it a second time

 https://cov-spectrum.org/explore/Japan/AllSamples/Past2M/variants?aaMutations=S%3AT1066N%2CN%3A20S&nextcladePangoLineage=BA.5.2.7*&aaMutations1=S%3AA1020S&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage CY.2 with 259 newly designated sequences, and 0 updated. Defining mutation T7734G (ORF1a:I2490S) (following C28331T (N:P20S)).

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage CY.2 with 259 newly designated sequences, and 0 updated. Defining mutation T7734G (ORF1a:I2490S) (following C28331T (N:P20S)).

**Comment by FedeGueli** [comment]
Thx @InfrPopGen
