### ISSUE TITLE
BF.5 sublineage with S:346T  circulating in Japan - 317 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1475]
After seeing that BF.5 is keeping its first place in Japan i decided to propose this lineage of BF.5 that acquired S:346T,
It is worth noticing that is unlikely that this lineage had a main role in the ongoing huge wave in Japan

**Defining mutations**:
BF.5 +ORF1a:I2873V (A8882G)  + S:R346T

**tree**:
<img width="1161" alt="Schermata 2022-12-26 alle 19 04 50" src="https://user-images.githubusercontent.com/87669813/209573905-6ea75671-39bd-4e93-8abf-853d333ae70c.png">
<img width="1150" alt="Schermata 2022-12-26 alle 19 07 08" src="https://user-images.githubusercontent.com/87669813/209574051-bb60052c-1567-487f-ab12-f20e5038fd6e.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_130fb_9dea30.json?c=userOrOld&label=id:node_7254279

**Gisaid query**: NSP4_I110V,Spike_R346T,Spike_A1020S,NS7a_H47Y

**Sequences**:
<details>
<summary>Expand for EPI_ISLs</summary>
EPI_ISL_13609889, EPI_ISL_13730342, EPI_ISL_13730950,
EPI_ISL_13733709, EPI_ISL_13733882, EPI_ISL_13733962,
EPI_ISL_13734970, EPI_ISL_13735015, EPI_ISL_13735494,
EPI_ISL_13735680, EPI_ISL_13735738, EPI_ISL_13774270,
EPI_ISL_13776580, EPI_ISL_13776591, EPI_ISL_13885490,
EPI_ISL_13888963, EPI_ISL_13890590, EPI_ISL_13955933,
EPI_ISL_14067679, EPI_ISL_14159532, EPI_ISL_14159826,
EPI_ISL_14159979, EPI_ISL_14322523, EPI_ISL_14399814,
EPI_ISL_14458101, EPI_ISL_14458537, EPI_ISL_14468382,
EPI_ISL_14497148, EPI_ISL_14568775, EPI_ISL_15051693,
EPI_ISL_15068505, EPI_ISL_15152306, EPI_ISL_15169758,
EPI_ISL_15178058, EPI_ISL_15188095, EPI_ISL_15196009,
EPI_ISL_15201140, EPI_ISL_15247255, EPI_ISL_15275133,
EPI_ISL_15282013, EPI_ISL_15346406, EPI_ISL_15346466,
EPI_ISL_15346554, EPI_ISL_15360102, EPI_ISL_15361547,
EPI_ISL_15402369, EPI_ISL_15402543, EPI_ISL_15417196,
EPI_ISL_15438408, EPI_ISL_15476480, EPI_ISL_15487949,
EPI_ISL_15503377, EPI_ISL_15503625, EPI_ISL_15503647,
EPI_ISL_15526381, EPI_ISL_15576498, EPI_ISL_15597272,
EPI_ISL_15597375, EPI_ISL_15597936, EPI_ISL_15599874,
EPI_ISL_15599965, EPI_ISL_15600531, EPI_ISL_15610471,
EPI_ISL_15615612, EPI_ISL_15673440, EPI_ISL_15673446,
EPI_ISL_15673686, EPI_ISL_15694366, EPI_ISL_15694639,
EPI_ISL_15695670, EPI_ISL_15711782, EPI_ISL_15712109,
EPI_ISL_15724223-15724224, EPI_ISL_15727249, EPI_ISL_15734393-15734394,
EPI_ISL_15734436, EPI_ISL_15734748, EPI_ISL_15734828,
EPI_ISL_15734882, EPI_ISL_15735320, EPI_ISL_15754032,
EPI_ISL_15754059, EPI_ISL_15756860, EPI_ISL_15760312,
EPI_ISL_15774115, EPI_ISL_15784359, EPI_ISL_15784361,
EPI_ISL_15784825, EPI_ISL_15789924, EPI_ISL_15795454,
EPI_ISL_15810675, EPI_ISL_15813250, EPI_ISL_15813274,
EPI_ISL_15813513, EPI_ISL_15815535, EPI_ISL_15823238,
EPI_ISL_15823561, EPI_ISL_15831337, EPI_ISL_15831360,
EPI_ISL_15832665, EPI_ISL_15832869, EPI_ISL_15833550,
EPI_ISL_15833623, EPI_ISL_15833746, EPI_ISL_15833962,
EPI_ISL_15834265, EPI_ISL_15834848, EPI_ISL_15834874,
EPI_ISL_15834896, EPI_ISL_15834914, EPI_ISL_15835038,
EPI_ISL_15838739, EPI_ISL_15851192, EPI_ISL_15852827,
EPI_ISL_15852842, EPI_ISL_15857128-15857129, EPI_ISL_15864693,
EPI_ISL_15888778, EPI_ISL_15893784, EPI_ISL_15893844,
EPI_ISL_15893928, EPI_ISL_15893935, EPI_ISL_15893983,
EPI_ISL_15899640, EPI_ISL_15908445-15908447, EPI_ISL_15909963,
EPI_ISL_15910054, EPI_ISL_15910469, EPI_ISL_15910701,
EPI_ISL_15916926, EPI_ISL_15923706, EPI_ISL_15924218,
EPI_ISL_15924441, EPI_ISL_15924578, EPI_ISL_15924601,
EPI_ISL_15924639, EPI_ISL_15924790, EPI_ISL_15924817,
EPI_ISL_15924878, EPI_ISL_15924887, EPI_ISL_15925092,
EPI_ISL_15925512, EPI_ISL_15925709, EPI_ISL_15927414,
EPI_ISL_15954485, EPI_ISL_15954496, EPI_ISL_15954518,
EPI_ISL_15962476, EPI_ISL_15963618, EPI_ISL_15981453,
EPI_ISL_15981516, EPI_ISL_15981832, EPI_ISL_15981940,
EPI_ISL_15981945, EPI_ISL_15982057, EPI_ISL_15982174,
EPI_ISL_15982192, EPI_ISL_15997309, EPI_ISL_15997520,
EPI_ISL_15997557-15997558, EPI_ISL_16000110, EPI_ISL_16000307,
EPI_ISL_16000317, EPI_ISL_16000340, EPI_ISL_16000383,
EPI_ISL_16000522, EPI_ISL_16030403, EPI_ISL_16039726,
EPI_ISL_16039794-16039796, EPI_ISL_16040013, EPI_ISL_16040020,
EPI_ISL_16040051, EPI_ISL_16040250, EPI_ISL_16040304,
EPI_ISL_16040900, EPI_ISL_16051511, EPI_ISL_16053106,
EPI_ISL_16053113, EPI_ISL_16056210, EPI_ISL_16060175,
EPI_ISL_16060277, EPI_ISL_16060294, EPI_ISL_16060342,
EPI_ISL_16060586, EPI_ISL_16072919, EPI_ISL_16073166,
EPI_ISL_16077876, EPI_ISL_16078005, EPI_ISL_16093253,
EPI_ISL_16106957, EPI_ISL_16106978, EPI_ISL_16107124,
EPI_ISL_16107505, EPI_ISL_16107539, EPI_ISL_16107541,
EPI_ISL_16107545-16107546, EPI_ISL_16107550, EPI_ISL_16107552,
EPI_ISL_16107684, EPI_ISL_16107740, EPI_ISL_16107768,
EPI_ISL_16107982, EPI_ISL_16110037, EPI_ISL_16111082,
EPI_ISL_16111772, EPI_ISL_16111782, EPI_ISL_16112397,
EPI_ISL_16112639, EPI_ISL_16112814, EPI_ISL_16121202,
EPI_ISL_16121271, EPI_ISL_16121344, EPI_ISL_16121564,
EPI_ISL_16122602, EPI_ISL_16122625-16122626, EPI_ISL_16122800-16122801,
EPI_ISL_16123252, EPI_ISL_16123354, EPI_ISL_16123398,
EPI_ISL_16123637, EPI_ISL_16124664-16124665, EPI_ISL_16124706,
EPI_ISL_16125032, EPI_ISL_16125131, EPI_ISL_16125359,
EPI_ISL_16127653-16127654, EPI_ISL_16129478, EPI_ISL_16129949,
EPI_ISL_16135483, EPI_ISL_16138757, EPI_ISL_16138862,
EPI_ISL_16151189, EPI_ISL_16153431, EPI_ISL_16165591,
EPI_ISL_16165782, EPI_ISL_16165903, EPI_ISL_16165922,
EPI_ISL_16165985, EPI_ISL_16173769, EPI_ISL_16173962,
EPI_ISL_16174236, EPI_ISL_16174391, EPI_ISL_16174566,
EPI_ISL_16174568, EPI_ISL_16174575, EPI_ISL_16174577,
EPI_ISL_16174708, EPI_ISL_16175196, EPI_ISL_16175360,
EPI_ISL_16175491, EPI_ISL_16175706, EPI_ISL_16175710,
EPI_ISL_16192645, EPI_ISL_16192739, EPI_ISL_16193470,
EPI_ISL_16194050, EPI_ISL_16194206, EPI_ISL_16194257,
EPI_ISL_16202816, EPI_ISL_16210024, EPI_ISL_16210482,
EPI_ISL_16210503, EPI_ISL_16210629, EPI_ISL_16210751,
EPI_ISL_16210920, EPI_ISL_16229543, EPI_ISL_16229769-16229770,
EPI_ISL_16230760, EPI_ISL_16236697, EPI_ISL_16245678,
EPI_ISL_16252954, EPI_ISL_16253779, EPI_ISL_16254306,
EPI_ISL_16254472, EPI_ISL_16254521, EPI_ISL_16254685,
EPI_ISL_16254740, EPI_ISL_16254899, EPI_ISL_16255077,
EPI_ISL_16255434, EPI_ISL_16255508, EPI_ISL_16255580,
EPI_ISL_16255963, EPI_ISL_16256068, EPI_ISL_16256619,
EPI_ISL_16257047, EPI_ISL_16257146, EPI_ISL_16257450,
EPI_ISL_16273313, EPI_ISL_16273580, EPI_ISL_16279424,
EPI_ISL_16279476, EPI_ISL_16279626, EPI_ISL_16279705,
EPI_ISL_16279826, EPI_ISL_16279942, EPI_ISL_16279954,
EPI_ISL_16279979, EPI_ISL_16279986
</details>

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.5.1 with 202 newly designated sequences, and 4 updated. Defining mutation G22599C (S:R346T) (following A8882G (ORF1a:I2873V)).
Designated because of its representation in the recent Japanese surge, moderate sustained apparent advantages there, and its recent records of high proportions of BF.5 in France, Luxembourg and UK.
