### ISSUE TITLE
BF.5 sublineage with S:V445A circulating in Japan 47 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1476]
**Defining mutations**: BF.5* (Nextclade) + ORF1a:I2873V (A8882G) > C16954T,C11668T, T23443C > S:V445A (T22896C) 

**Tree:**
<img width="1158" alt="Schermata 2022-12-26 alle 19 17 52" src="https://user-images.githubusercontent.com/87669813/209574649-fbc6365a-b213-4672-a5c3-8824469f4308.png">
ORF1a:I2873V

**Gisaid Query**: NS7A_H47Y,NSP4_I110V,Spike_V445A,Spike_A1020S + Nuc:T23443C

**Sequences** : 47

EPI_ISL_15151511, EPI_ISL_15401767, EPI_ISL_15694848,
EPI_ISL_15784605, EPI_ISL_15823775, EPI_ISL_15833834,
EPI_ISL_15834492, EPI_ISL_15852957, EPI_ISL_15916714,
EPI_ISL_15924534, EPI_ISL_15924648, EPI_ISL_15925505,
EPI_ISL_15954333, EPI_ISL_15954601, EPI_ISL_15981527,
EPI_ISL_15981675, EPI_ISL_16040318, EPI_ISL_16051713,
EPI_ISL_16092849, EPI_ISL_16107226, EPI_ISL_16109972,
EPI_ISL_16111656, EPI_ISL_16112174, EPI_ISL_16123255,
EPI_ISL_16125099, EPI_ISL_16129608, EPI_ISL_16155421,
EPI_ISL_16166102, EPI_ISL_16174278, EPI_ISL_16174543,
EPI_ISL_16175767, EPI_ISL_16193040, EPI_ISL_16229494,
EPI_ISL_16229497, EPI_ISL_16240717, EPI_ISL_16240719,
EPI_ISL_16240746, EPI_ISL_16240755, EPI_ISL_16253184,
EPI_ISL_16256047, EPI_ISL_16257409, EPI_ISL_16273793,
EPI_ISL_16279435, EPI_ISL_16279452-16279453, EPI_ISL_16279531,
EPI_ISL_16279911

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.5.2 with 25 newly designated sequences, and 0 updated. Defining mutation T22896C (S:V445A) (following T23443C).
