### ISSUE TITLE
BA.5.2.48  sublineage with S:A570S circulating in China (206 sequences as 21/01/23)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1479]
Defining mutations: BA.5.2.48 > S:A570S (G23270T) **EDITED**

Tree: 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_1acf9_b0ad20.json?c=userOrOld&label=id:node_7080557
<img width="1106" alt="Schermata 2022-12-27 alle 16 26 08" src="https://user-images.githubusercontent.com/87669813/209687435-7e8e3090-1b64-44a9-a441-ed16abc648b6.png">

Gisaid query : Spike_a570S,NSP13_T127N,M_D3N + nuc T17208C

Sequences : 8
EPI_ISL_16181568, EPI_ISL_16259477, EPI_ISL_16259494,
EPI_ISL_16283957, EPI_ISL_16283972-16283973, EPI_ISL_16283981-16283982,

**Comment by AnonymousUserUse** [comment]
A little bit off-topic, but is the order BA.5.2 > C27513T > C27012T > G12310A >Orf1b:1050N (C16616A) correct?
What I can take from the Nextstrain tree (https://nextstrain.org/ncov/gisaid/global/6m) is the order BA.5.2 > G12310A > Orf1b:1050N (C16616A) > C27513T, C27012T

**Comment by AnonymousUserUse** [comment]
This lineage seems to be a sublineage of https://github.com/cov-lineages/pango-designation/issues/1471

**Comment by FedeGueli** [comment]
> This lineage seems to be a sublineage of #1471

yes true. also the othe ri proposed so probably #1471 should be designated starting from T17028C.

i will leave this open until i will see @corneliusroemer or @InfrPopGen will designate the ba.5.2 sublineage from a NUC or. not. thx for noticing.

**Comment by FedeGueli** [comment]
> A little bit off-topic, but is the order BA.5.2 > C27513T > C27012T > G12310A >Orf1b:1050N (C16616A) correct? What I can take from the Nextstrain tree (https://nextstrain.org/ncov/gisaid/global/6m) is the order BA.5.2 > G12310A > Orf1b:1050N (C16616A) > C27513T, C27012T

Quite the same, at the start of its spread it was on Usher as you said, now Usher puts in that order. all the 4 muts come together in the vast mayority of cases!

**Comment by silcn** [comment]
> yes true. also the other i proposed so probably #1471 should be designated starting from T17028C.
>
> i will leave this open until i will see @corneliusroemer or @InfrPopGen will designate the ba.5.2 sublineage from a NUC or. not. thx for noticing.

Yes agreed, starting from T17028C was the intention. I don't think starting from a silent mutation should be an issue, as there is still an AA mutation (ORF1b:T1050N) on the branch from the nearest designated ancestor.

It's a bit annoying that Usher is still splitting it into two different trees. I'd guess as more sequences come in it might start placing them correctly? Or a selective unmasking of C16887T on this branch would do it.

**Comment by FedeGueli** [comment]
> > yes true. also the other i proposed so probably #1471 should be designated starting from T17028C.
> > i will leave this open until i will see @corneliusroemer or @InfrPopGen will designate the ba.5.2 sublineage from a NUC or. not. thx for noticing.
> 
> Yes agreed, starting from T17028C was the intention. I don't think starting from a silent mutation should be an issue, as there is still an AA mutation (ORF1b:T1050N) on the branch from the nearest designated ancestor.
> 
> It's a bit annoying that Usher is still splitting it into two different trees. I'd guess as more sequences come in it might start placing them correctly? Or a selective unmasking of C16887T on this branch would do it.

@AngieHinrichs could help with that

**Comment by FedeGueli** [comment]
2 new sequences from Singapore

**Comment by FedeGueli** [comment]
12 sequences . pending until #1471 designation.

**Comment by FedeGueli** [comment]
It is the second biggest sublineage of #1471 now at 52 sequences. Waiting for the decision on its parent to see from where it will start.

**Comment by corneliusroemer** [comment]
Designated as DY.1

**Comment by FedeGueli** [comment]
@corneliusroemer there is a branch of DY.1 that acquired S:K147E convergently with BA.2.75.

I t seems fast. alao other sources pointed that ro me  i was waiting to propose it if the team would gave designated sublineages of the chinese wave strains.
i suggest a direct designation of it. otheteise i will make up a proposal later or tomorrow.

@InfrPopGen @thomasppeacock
