### ISSUE TITLE
Proposal for SARS-CoV-2 new lineage within B.1.1.28 with Q675H and Q677H Spike substitutions in Uruguay

### ISSUE THREAD

**Issue by natinreg** [cov-lineages/pango-designation#148]
by Natalia Rego, Cecilia Salazar, Mercedes Paz, Alicia Costábile, Gonzalo Bello, Pilar Moreno, Gonzalo Moratorio, Gregorio Iraola and Lucía Spangenberg on behalf of the Inter-institutional Working Group on SARS-CoV-2 genomic surveillance in Uruguay

**Description**

Sub-lineage of: B.1.1.28
Earliest sequence: 2020-12-02 (RT16-UYMO)
Most recent sequence: 2021-04-25 (CUY7-001455-UYMO)
Countries circulating: Uruguay (242), USA (2), Spain (1); (GISAID sequences)

The first sequence came from a sample collected on December 2, 2020, in Montevideo, Uruguay’s capital city. It was assigned to the B.1.1.28 lineage and presented additional amino acid substitutions in the Spike protein region (Q675H and Q677H), close to the S1/S2 cleavage site. This combination of S:Q675H and S:Q677H has not been reported before for lineage B.1.1.28. These mutations have gained attention given their proximity to the furin cleavage site and their recurrent emergence in independent lineages. 
During January, new sequences with this mutational pattern spread around Uruguay and we propose that its higher abundance was associated with a rise in active cases during late 2020 and early 2021 in the country. Latest sequences are also from Uruguay.

**List of characteristic amino acid changes of the new lineage:**
Orf1ab
C1077T - NSP2:P91
C3736T - NSP3:D399
C7043T - NSP3:P1442S
C8980T - NSP4:Y142
C10029T - NSP4:T492I
A14113G - NSP12:T225A
Spike
G23587C - S:Q675H
G23593T - S:Q677H
C24382T - S:940
Orf3a
C25665T - ORF3a:Y91 (most sequences)
G26172T - ORF3a:M260I (most sequences)
 
**Genomes:**
List of genomes, collected on 2021-07-07
[B.1.1.28.X_list_of_genomes.txt](https://github.com/natinreg/B.1.1.28-UY/blob/main/B.1.1.28.X_list_of_genomes.txt)

**Evidence:**
 
A Maximum-likelihood reconstruction of 1719 B.1.1.28 sequences from Brazil (1418) and Uruguay (297) (and four additional sequences from USA, Belgium and Spain) is shown below. Alignment was performed with MAFFT, phylogenetic reconstruction with IQ-TREE (GTR+F+R3 nucleotide substitution model) and branch support assessed with SH-aLRT with 1000 replicates. The tree is rooted with EPI_ISL_416036 (the earliest B.1.1.28 sequence from 5 March, 2020). In Figure 1A, in dark pink we show the B.1.1.28 Uruguayan clade harboring S:Q675H and S:Q677H mutations. It is composed of 246 sequences, most of them from Uruguay, one from Brazil, one from Spain and two collected in the USA. In light purple, we highlight five basal sequences from Brazil. In Figure 1B there is a zoom of this part of the tree, where SH-aLRTs values can be read. Additionally, a collapsed clade with 150 sequences is shown in blue (Figure 1A) and it is composed of 33 Uruguayan sequences and 117 Brazilian sequences harboring the mutation N:P13L, a B.1.1.28 sublineage widely distributed in southern Brazil and also at the Uruguayan-Brazilian border.
We have also posted on Virological about this sublineage.
https://virological.org/t/emergence-and-spread-of-a-b-1-1-28-derived-lineage-with-q675h-and-q677h-spike-mutations-in-uruguay/730
 
![fig1_pango-issue](https://user-images.githubusercontent.com/26191355/125841145-ef2ced30-ac33-4824-b6a0-3283a7a53fc7.png)

**Proposed lineage name:**
 
Next available designation with parent B.1.1.28 lineage (P.X).

**Comment by AngieHinrichs** [comment]
Thanks @natinreg!  I just want to note that the following EPI_ISL_IDs in B.1.1.28.X_list_of_genomes.txt are in the light purple (basal Brazilian) part of the tree and do not have the more new lineage mutations including S:Q675H and S:Q677H, so they should be excluded from the new lineage, correct?
```
Brazil/GO-HLAGYN-1375468/2021   EPI_ISL_2017309 2021-04-15
Brazil/GO-HLAGYN-1401623/2021   EPI_ISL_2187714 2021-01-13
Brazil/SP-1140/2020     EPI_ISL_1039705 2020-10-06
Brazil/SP-302/2020      EPI_ISL_534322  2020-04-24
Brazil/SP-844R2/2020    EPI_ISL_708530  2020-11-21
```
I also think `Uruguay/COR-M526/2021|EPI_ISL_2754960|2021-02-26` should be excluded because it does not have S:Q675H (G23587C) and S:Q677H (G23593T) like the rest of the new lineage samples.  Interestingly, it has S:Q677K (C23591A) instead.

`Brazil/RJ-00831/2021|EPI_ISL_1213397|2021-01-22` has S:Q675H but not S:Q677H, so perhaps it should be excluded as well?

This is a Nextstrain view of the branch of the UCSC tree where these samples are placed, found by uploading the EPI_ISL_IDs in B.1.1.28.X_list_of_genomes.txt to the [UShER web interface](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace) after selecting the GISAID+public tree and a subtree size of 2000:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-148.json?branchLabel=Spike%20mutations&c=userOrOld&label=nuc%20mutations:C12053T

**Comment by natinreg** [comment]
Thanks @AngieHinrichs  Yes, you are completely right. In fact, the Brazilian samples are branching basal to the clade (this is my mistake because we used to include them as an outgroup for the clade -forgot to remove them). And you are right, we don't understand the exact position of Uruguay/COR-M526/2021|EPI_ISL_2754960|2021-02-26 and also, in the bayesian analysis the Brazil/RJ-00831/2021|EPI_ISL_1213397|2021-01-22 sample (which is normally immediately out of the clade) is correctly positioned and does not belong to the Uruguayan clade.

**Comment by chrisruis** [comment]
Thanks @natinreg for submitting. We've added this as lineage P.6 in [v1.2.44](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.44). We've included the 171 sequences downstream of where S:Q677H occurs that have <5% ambiguity
