### ISSUE TITLE
Possible BA.2.3.20 sublineage circulating in Hong Kong and maybe exported to China with Orf8:T12I  ( 86 sequences 07/01/23 )

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1481]
A sample (EPI_ISL_16284869) from a traveller from China tested by Japanese airport surveillance uploaded today after another one (EPI_ISL_15923518) that was uploaded on 28/11/22 belonging to the same lineage 
may hint that a BA.2.3.20 sublineage is circulating there.

It is a lineage defined by Orf8:T12I and already sampled in Japan,Australia, Singapore, Israel, England, California and Michigan.

Defining mutations:BA.2.3.20 + Orf1b:T5805M + C18252T > C10189T > T25171C > T28282C then
 C2197T, C17163T, T20748C,  Orf8:T12I (C27928T)

Tree:
<img width="1159" alt="Schermata 2022-12-27 alle 16 49 00" src="https://user-images.githubusercontent.com/87669813/209689851-8d5f6168-4ac8-4760-85b5-dd858fef3365.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_1acf9_b0ad20.json?c=country&label=id:node_7786130

Gisaid query:  NSP2_T547I,NSP3_I896T,NS8_T12I
Sequences: 19
EPI_ISL_15545759, EPI_ISL_15797868, EPI_ISL_15808631,
EPI_ISL_15921092, EPI_ISL_15923518, EPI_ISL_15952893,
EPI_ISL_16009612, EPI_ISL_16011908, EPI_ISL_16012104,
EPI_ISL_16062159, EPI_ISL_16068242, EPI_ISL_16082329,
EPI_ISL_16130652, EPI_ISL_16133563, EPI_ISL_16148789,
EPI_ISL_16273201, EPI_ISL_16273993, EPI_ISL_16279420,
EPI_ISL_16284869

Country:
9 USA
3 Japan
3 Australia
2 China (via Japan)
1 England, Israel, Singapore

**Comment by AnonymousUserUse** [comment]
I do not think it is a Chinese lineage. There are only 2 (from 19) sequences with travel history from China, and the sample date of sequences with travel history from China is later than early sequences. It is possible that those with travel history from China are infected in other countries or in the airport or on the airplane, or there is only limited local transmission in China.

**Comment by FedeGueli** [comment]
> I do not think it is a Chinese lineage. There are only 2 (from 19) sequences with travel history from China, and the sample date of sequences with travel history from China is later than early sequences. It is possible that those with travel history from China are infected in other countries or in the airport or on the airplane, or there is only limited local transmission in China.

Maybe. even if It would be weird that a lineage as small as this one will be picked up by airport surveillance and exported from china 2 times. So i think it is better monitoring it.

**Comment by AnonymousUserUse** [comment]
> > I do not think it is a Chinese lineage. There are only 2 (from 19) sequences with travel history from China, and the sample date of sequences with travel history from China is later than early sequences. It is possible that those with travel history from China are infected in other countries or in the airport or on the airplane, or there is only limited local transmission in China.
> 
> Maybe. even if It would be weird that a lineage as small as this one will be picked up by airport surveillance and exported from china 2 times. So i think it is better monitoring it.

It is weird that people with travel history from China infected by several sublineages of BA.2.3.20 have been picked up by Japan, but not by Singapore. In contrast, Singapore has picked up a high number of sequences of lineage BA.5.2 from people with travel history from China.

**Comment by FedeGueli** [comment]
One more sequence with travel history from China uploaded now from Singapore: EPI_ISL_16294660

cc @AnonymousUserUse

**Comment by Mydtlwn** [comment]
I don't think it's from China either.

**Comment by FedeGueli** [comment]
> I don't think it's from China either.

It would be very weird that such a small lineage would have been sampled in 3 travellers from China to two different nations if it is not circulating there.

**Comment by FedeGueli** [comment]
one more sequence from Tokyo Japan

**Comment by FedeGueli** [comment]
One more sequence from Usa

**Comment by FedeGueli** [comment]
One more sequence from Hong Kong.

**Comment by FedeGueli** [comment]
Big upload of 47 sequences today from Hong Kong of this lineage ,  looking at collection data spanning form October to December it is entirely possible this lineage is circulating just  in Hong Kong or both in Hong Kong and China.

@thomasppeacock @corneliusroemer @InfrPopGen @AngieHinrichs

**Comment by FedeGueli** [comment]
New sample from Singapore, Airport surveillance in a traveller from Thailand

**Comment by FedeGueli** [comment]
2 sequences from Japan

**Comment by FedeGueli** [comment]
83 as today. last samples from Japan, Singapore, Malaysia
