### ISSUE TITLE
BQ.1.1 + S:Y144- + S:S494P in England (22 sequences) + Denmark (1 sequence)

### ISSUE THREAD

**Issue by rquiroga7** [cov-lineages/pango-designation#1483]
Sub-lineage of: BQ.1.1
Earliest sequence: 2022-11-26
Most recent sequence: 2022-12-17
Countries circulating: England

The proposed lineage has S:Y144- and S:494P, and although number of sequences is still low, seems to be growing fast. Although PANGO assigned lineage is BQ.1.1.13, there is no E:V62F mutation present. Also, a single sequence from Denmark appears within same subtree.

Genomes

England/EPI_ISL_16212837|2022-12-14
England/PHEC-YY81IKM/2022\|2022-12-12
England/PHEC-YY8WXET/2022\|2022-12-15
England/PHEC-YY8WQHJ/2022\|2022-12-17
England/LSPA-32629521/2022\|2022-12-14
England/LSPA-3262CB95/2022\|2022-12-15
England/LSPA-326293AF/2022\|2022-12-14
England/LSPA-3262957C/2022\|2022-12-14
England/LSPA-326286E3/2022\|2022-12-14
England/LSPA-32628A05/2022\|2022-12-14
England/LSPA-32629907/2022\|2022-12-14
England/LSPA-326293FA/2022\|2022-12-14
England/LSPA-326291B4/2022\|EPI_ISL_16212946\|2022-12-14
England/LSPA-32629011/2022\|2022-12-14
England/PHEC-YY8OTG5/2022\|2022-12-02
England/PHEC-YY8OTEZ/2022\|2022-11-27
England/PHEP-YYGBFG8/2022\|2022-11-26
England/PHEC-YY8OTMT/2022\|2022-11-27
England/QEUH-326234FD/2022\|2022-12-10
England/LSPA-32627AAC/2022\|2022-12-14
England/PHEC-YY8WDFD/2022\|2022-12-17
England/LSPA-3261351B/2022\|2022-12-06

Usher tree:
![image](https://user-images.githubusercontent.com/8103453/209844145-e521a17f-a01f-4eb9-97ae-5c05aec0cbc5.png)

**Comment by corneliusroemer** [comment]
This is on the C7528T branch of BQ.1.1
