### ISSUE TITLE
BQ.1.1.32 (S:M153I + Y144-) + S:S494P in England (16 sequences) + USA (2 sequences) 

### ISSUE THREAD

**Issue by rquiroga7** [cov-lineages/pango-designation#1484]
Sub-lineage of: BQ.1.1.32
Earliest sequence: 2022-11-15
Most recent sequence: 2022-12-20
Countries circulating: England

The proposed lineage has S:494P, and seems to be growing fast. This seems to be a sublineage of BQ.1.1.32, since they have S:M153I, and S:Y144-. Also, two sequences from USA appear within same subtree. Interestingly, same combination of Spike mutations as I reported in issue #1483 (S:Y144- + S:S494P).

Genomes

USA/CA-CDC-LC0956282/2022|EPI_ISL_16206113|2022-12-05
USA/CA-CDC-LC0956284/2022|EPI_ISL_16206111|2022-12-05
England/PHEP-YYGDYTT/2022|2022-12-09
England/LSPA-3262C4F4/2022|2022-12-15
England/LSPA-325EFB35/2022|OX378388.1|2022-11-15
England/PHEC-YY8W8Z4/2022|2022-12-19
England/PHEC-YY81TMP/2022|2022-12-07
England/PHEC-YY8TMZH/2022|2022-11-30
England/PHEC-YY8WKAI/2022|2022-12-18
England/PHEC-YY8UH8E/2022|2022-12-20
England/LSPA-3262C4E5/2022|2022-12-16
England/LSPA-32634C88/2022|2022-12-19
England/LSPA-32634EBF/2022|2022-12-19
England/LSPA-3262C88F/2022|2022-12-16

Usher tree:

![image](https://user-images.githubusercontent.com/8103453/209845899-054800e4-55c4-4c12-8d41-031fc21af7ee.png)

**Comment by silcn** [comment]
These don't have C913A, so they aren't BQ.1.1.22.

**Comment by AngieHinrichs** [comment]
I see that pangoLEARN really consistently calls the BQ.1.1 > S:M153I (G22021A) branch as BQ.1.1.22, although as @silcn points out, the sequences in this proposal do not have C913A so aren't fully BQ.1.1.22 as currently defined.  However, BQ.1.1.22 was motivated not by the synonymous mutation C913A but by the deletion that accompanies it.  From lineage_notes.txt:
```
BQ.1.1.22       Alias of B.1.1.529.5.3.1.1.1.1.1.1.22, Australia/England/Denmark, S:144- and C913A
```
I haven't looked at these sequences, but just speculating -- perhaps they also have the S:144- ?  That would be invisible to UShER since it deals only with substitutions, not insertions/deletions.

**Comment by silcn** [comment]
The S:M153I branch does also have 144del, and it turns out it has already been proposed in #1402, so a decision should be made on that proposal before this one. There are lots of BQ.1.1*+S:144del lineages; BQ.1.1.22 is one and the S:M153I branch is another.

**Comment by rquiroga7** [comment]
I think you are right about issue #1402, this might be a sub-branch of M153I+S:144- that has also acquired S494P. Do you agree @silcn?

**Comment by silcn** [comment]
@rquiroga7 yes, that's what I was trying to say though I didn't explain it very clearly - since this is a sublineage of #1402, it needs to be designated before this one.

**Comment by FedeGueli** [comment]
@silcn @rquiroga7 in #1402 there are two lineages a bigger one with G22021A  and a smaller one with G22021T

**Comment by rquiroga7** [comment]
Sorry, just noticed I missed ID of some of the genomes. Here are all:

USA/CA-CDC-LC0956282/2022\|OQ080983.1\|2022-12-05
USA/CA-CDC-LC0956284/2022\|OQ080981.1\|2022-12-05
England/PHEP-YYGDYTT/2022\|2022-12-09
England/LSPA-3262C4F4/2022\|2022-12-15
OX396335.1\|2022-12-15
England/LSPA-325EFB35/2022\|OX378388.1\|2022-11-15
England/LSPA-32641A60/2022\|2022-12-20
England/PHEC-YY8W8Z4/2022\|2022-12-19
England/PHEC-YY81TMP/2022\|2022-12-07
England/PHEC-YY8WKAI/2022\|2022-12-18
England/PHEC-YY8UH8E/2022\|2022-12-20
England/LSPA-32637B00/2022\|2022-12-20
England/LSPA-32638B5A/2022\|2022-12-20
England/QEUH-32638659/2022\|2022-12-12
England/PHEC-YY8TMZH/2022\|2022-11-30
England/LSPA-3262C4E5/2022\|2022-12-16
England/LSPA-32634C88/2022\|2022-12-19
England/LSPA-32634EBF/2022\|2022-12-19
England/LSPA-3262C88F/2022\|2022-12-16

**Comment by rquiroga7** [comment]
@FedeGueli The ancestral lineage to these sequences seem to be the G22021A sequences mentioned in issue #1402. These are the sequences mentioned there (there are quite a bit more sequences on the Usher tree now):

EPI_ISL_15841327
EPI_ISL_15947402
EPI_ISL_15841587
EPI_ISL_15945664
EPI_ISL_15804433
EPI_ISL_15893213
EPI_ISL_15851074
EPI_ISL_15951803
EPI_ISL_15945379
EPI_ISL_15902624
EPI_ISL_15945001
EPI_ISL_15945791
EPI_ISL_15824725
EPI_ISL_15976632
EPI_ISL_15864758
EPI_ISL_15945918
EPI_ISL_15860318
EPI_ISL_15665959
EPI_ISL_15951906
EPI_ISL_15704930
EPI_ISL_15860275
EPI_ISL_15952890
EPI_ISL_15842916
EPI_ISL_15754150
EPI_ISL_15818697
EPI_ISL_15976584
EPI_ISL_15945851
EPI_ISL_15943556
EPI_ISL_15860180
EPI_ISL_15880968
EPI_ISL_15889657
EPI_ISL_15952959
EPI_ISL_15943533
EPI_ISL_15851077
EPI_ISL_15859971
EPI_ISL_15824791
EPI_ISL_15770955
EPI_ISL_15793551
EPI_ISL_15859884
EPI_ISL_15948612
EPI_ISL_15944340
EPI_ISL_15944477
EPI_ISL_15944794
EPI_ISL_15952136
EPI_ISL_15907328
EPI_ISL_15819356
EPI_ISL_15943619
EPI_ISL_15944393
EPI_ISL_15841337
EPI_ISL_15951290
EPI_ISL_15952452
EPI_ISL_15890548
EPI_ISL_15946076
EPI_ISL_15890466
EPI_ISL_15841531
EPI_ISL_15953009
EPI_ISL_15780028
EPI_ISL_15907086
EPI_ISL_15951903
EPI_ISL_15859970
EPI_ISL_15976663
EPI_ISL_15847414
EPI_ISL_15805017
EPI_ISL_15836689
EPI_ISL_15951395
EPI_ISL_15976645
EPI_ISL_15945199
EPI_ISL_15945633

**Comment by rquiroga7** [comment]
This seems to be a sublineage of BQ.1.1.32, designated today. 

According to GISAID, in England, BQ.1.1.32 with no S:S494P mutations represented 0.14% of sequences sampled between 2022-12-01 and 2022-12-15, and also 0.14% of sequences sampled between 2022-12-15 and 2022-12-31.

Meanwhile, for the same time periods, BQ.1.1.32 + S:S494P went from 0.04% to 0.29% of sequences. This suggests that S:S494P gives this sublineage a fitness advantage.
