### ISSUE TITLE
Possible sublineage of XBB.1 with S:T732I and S:Q690R - 27 sequences  

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1485]
I spotted looking at airport sequences from Singapore this sublineage of XBB.1 defined by two Spike mutations,
 the first in S2 just after the furin cleavage site and the other just adjacent to FCS. 
Looking at its multicontinental spread with a little number of sequences i think it is worth monitoring it for a while

Tree:
<img width="1166" alt="Schermata 2022-12-28 alle 23 38 47" src="https://user-images.githubusercontent.com/87669813/209881466-86ab1c46-e284-4605-bdd4-7044a035ec6d.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c67b_cc3780.json?c=country&label=id:node_7675698

Defining mutations: 
XBB.1 + orf8:G8* (G27915T)>S:T732I (C23757T) > C2857T > S:Q690R (A23631G)

Gisaid query:  Spike_Q690R,Spike_T732I

Sequences:
EPI_ISL_15910129, EPI_ISL_15957732, EPI_ISL_16080383,
EPI_ISL_16085403, EPI_ISL_16103414, EPI_ISL_16103420,
EPI_ISL_16109792, EPI_ISL_16222861, EPI_ISL_16231061,
EPI_ISL_16234462, EPI_ISL_16240875, EPI_ISL_16259310,
EPI_ISL_16260529, EPI_ISL_16294587

Interesting two sequences have travel history but one from Turkey to Usa and the other from Philippines to Singapore.

Countries:

<img width="271" alt="Schermata 2022-12-28 alle 23 49 49" src="https://user-images.githubusercontent.com/87669813/209882322-c1eed121-b60c-45e5-9961-87cbeac32bdf.png">

CovSpectrum overview with : S:Q690R, S:T732I
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A690R%2CS%3A732I&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

**Note:
FCS sequence should become : YSQTQTKSHRRARSVASRS**

**Comment by FedeGueli** [comment]
One more sequence from Indonesia. tot 15

**Comment by FedeGueli** [comment]
16th sequence from Colombia. Really weird how this one is popping up here and there.

**Comment by FedeGueli** [comment]
17th sequence from Turkey confirming the one samples from a traveller from Turkey

**Comment by corneliusroemer** [comment]
Very international spread, quite interesting, looks like undersampling indeed.

**Comment by FedeGueli** [comment]
One more sample from USA

**Comment by FedeGueli** [comment]
One more sample from Indonesia

**Comment by FedeGueli** [comment]
Closing it for the moment i will keep it monitored

**Comment by FedeGueli** [comment]
New sequence from S Korea from a traveller from Turkey.

**Comment by FedeGueli** [comment]
One more sample came from California after a hyatus.

**Comment by FedeGueli** [comment]
Last sequences from Costa Rica and Indonesia

**Comment by FedeGueli** [comment]
i close this one again as no new seqs came out
