### ISSUE TITLE
 XBB.1 sublineage with S:F490P : 68 sequences - Usa , Czechia, Uk, Malaysia, Austria -EDITED as 09/02/23 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1487]
I totally edited this proposal. 
I would like to highlight to Pango team that S:f490P has been actually picked up by plenty XBB.1 and XBB.1.5 lineages.

Here i propose the biggest one:
On Usher is already 60 Sequences while Gisaid finds only 45,  so i will keep only the Gisaid number of sequences  in the headline.

**Tree:**
<img width="1109" alt="Schermata 2023-01-24 alle 09 39 30" src="https://user-images.githubusercontent.com/87669813/214246302-36789c3f-9f14-4760-a13e-8bf71692a9ba.png">

<img width="1154" alt="Schermata 2023-01-24 alle 09 34 11" src="https://user-images.githubusercontent.com/87669813/214245338-d7773b02-57a7-4b3c-aab1-ac38227057c7.png">
/87669813/214245297-b996e9e6-c778-4c5b-ac06-3dc649a54f62.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1fd49_f96b60.json?c=gt-S_490&label=id:node_7864390

Countries
<img width="280" alt="Schermata 2023-01-24 alle 09 34 45" src="https://user-images.githubusercontent.com/87669813/214245435-0ebf7832-a8d8-49e6-bd3d-344d9034efed.png">

**Defining mutations:**
XBB.1+ Orf8:G8* (G27915T ) + **S:490P** (T23030C) from S:F490S

**Gisaid query** : -T24796C, - C4999T, -C745T,T23031C , G22895C, T22896C ,C22664A , G22317T , G27915T, T23030C  finds 47 viruses:

<details>

<summary>Expand for EPI_ISLs</summary>
EPI_ISL_15779494, EPI_ISL_15783850, EPI_ISL_15850447,
EPI_ISL_15922900, EPI_ISL_16062761, EPI_ISL_16081265,
EPI_ISL_16082493, EPI_ISL_16098932, EPI_ISL_16108499,
EPI_ISL_16158794, EPI_ISL_16174510, EPI_ISL_16206578,
EPI_ISL_16212647, EPI_ISL_16212650, EPI_ISL_16251102,
EPI_ISL_16252833, EPI_ISL_16266009, EPI_ISL_16307624,
EPI_ISL_16307637, EPI_ISL_16320263, EPI_ISL_16343245,
EPI_ISL_16345430, EPI_ISL_16380935, EPI_ISL_16398743,
EPI_ISL_16412740, EPI_ISL_16439631, EPI_ISL_16439654,
EPI_ISL_16439685, EPI_ISL_16477580, EPI_ISL_16482966,
EPI_ISL_16484263, EPI_ISL_16489874, EPI_ISL_16507763,
EPI_ISL_16510859, EPI_ISL_16511583, EPI_ISL_16525874,
EPI_ISL_16533953, EPI_ISL_16557322, EPI_ISL_16572743,
EPI_ISL_16575442, EPI_ISL_16580025, EPI_ISL_16583385,
EPI_ISL_16598649, EPI_ISL_16619782, EPI_ISL_16629141,
</details>

**Comment by FedeGueli** [comment]
One more sequence from North Dakota

**Comment by FedeGueli** [comment]
32 sequences all the last three from New York

**Comment by FedeGueli** [comment]
one more from England. cc @corneliusroemer it seems fast.

**Comment by FedeGueli** [comment]
one more from Wales. it keeps growing @InfrPopGen

**Comment by FedeGueli** [comment]
one more from Usa Illinois. total count 34

**Comment by FedeGueli** [comment]
Two new from US Georgia and Malaysia

**Comment by corneliusroemer** [comment]
How do we know this is not an ancestor of XBB.1.5? Does it have any nuc mutation that XBB.1.5 doesn't have?

**Comment by silcn** [comment]
@corneliusroemer F486P ≠ F490P

**Comment by corneliusroemer** [comment]
Oh god, I'm blind. Sorry!

**Comment by corneliusroemer** [comment]
Usher seems to have multiple clusters of XBB.1 + S:490P. Which one is this one here?

Here's the biggest, a very international, which branches off XBB.1 directly: 

<img width="2084" alt="image" src="https://user-images.githubusercontent.com/25161793/211232205-88447f14-0c8b-4ad6-afc5-a0cc11c95fd6.png">

Then there's a predominantly Malaysian one after C4999T, A14427G
<img width="2156" alt="image" src="https://user-images.githubusercontent.com/25161793/211232276-8f0a943b-7151-494e-aa60-824ed55ff710.png">

And then there's another deep US-NY on a branch with among others A8897G

**Comment by FedeGueli** [comment]
> Usher seems to have multiple clusters of XBB.1 + S:490P. Which one is this one here?
> 
> Here's the biggest, a very international, which branches off XBB.1 directly:
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/25161793/211232205-88447f14-0c8b-4ad6-afc5-a0cc11c95fd6.png">
> 
> Then there's a predominantly Malaysian one after C4999T, A14427G <img alt="image" width="2000" src="https://user-images.githubusercontent.com/25161793/211232276-8f0a943b-7151-494e-aa60-824ed55ff710.png">
> 
> And then there's another deep US-NY on a branch with among others A8897G

The one proposed here is the first you mentioned.
Thank you i will restrict the gisaid query later

**Comment by FedeGueli** [comment]
there is this one too: 
C745T,T10939C,A28540G,A8897G,G10986A, T23030C, A29697G
<img width="1154" alt="Schermata 2023-01-09 alle 17 58 53" src="https://user-images.githubusercontent.com/87669813/211364358-7ff9e9e9-a197-40fa-8624-029d4d53a10b.png">

**Comment by FedeGueli** [comment]
> SO i ve changed the title of the issue consequently.
> 
> Multiple lineages as 12-01-23
> 
> **1) Main post** : Spike_V83A,Spike_L368I,Spike_F490P,Spike_G252V,-Spike_Q677L, NUC: -T24796C, - C4999T, -C745T
> 
> > 40 viruses
> 

@thomasppeacock 
It seems that this lineage is already much bigger with many sequences still not uploaded on Gisaid 👍 
here the last [Usher tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_824c_59da50.json?label=id:node_7819489)
<img width="1178" alt="Schermata 2023-01-16 alle 20 01 16" src="https://user-images.githubusercontent.com/87669813/212749594-0343ca1f-cd75-4165-9fef-d56a85deffb6.png">
in this tree i count 54 sequences (58 sequences minus 4 out of 5 uploaded samples already in the tree).


@corneliusroemer @InfrPopGen i count 6 different branches of XBB.1 with S:490P so designating the big one could help to distinguish the others rapidly, and i think @AngieHinrichs could find some more using taxonium  ( it seems S:486P is popping up a in several XBB.2 sublineages  while S:490P is appearing mainly in XBB.1
<img width="793" alt="Schermata 2023-01-16 alle 20 06 18" src="https://user-images.githubusercontent.com/87669813/212750390-fbd2af1f-3dcd-4272-b17f-34257843b43c.png">

**Comment by FedeGueli** [comment]
Spike_V83A,Spike_L368I,Spike_F490P,Spike_G252V,-Spike_Q677L, NUC: -T24796C, - C4999T, -C745T 
finds another sample today intercepted by Singapore surveillance with travel history from Saudi Arabia

**Comment by FedeGueli** [comment]
-T24796C, - C4999T, -C745T,T23031C , G22895C, T22896C ,C22664A , G22317T , G27915T, T23030C finds now 42 sequences on Gisaid last samples from Australia and USa

**Comment by FedeGueli** [comment]
-T24796C, - C4999T, -C745T,T23031C , G22895C, T22896C ,C22664A , G22317T , G27915T, T23030C 45 sequences as today

**Comment by FedeGueli** [comment]
I fully edited this proposal
while there are multiple lineages with S:F490P popping up in XBB.1 and XBB.1.5 

Here i want to propose just the one found by: -G1466A,-C12439T, -T24796C, - C4999T, -C745T,T23031C , G22895C, T22896C ,C22664A , G22317T , G27915T, T23030C 
finds 45 sequences as 24/01/2023


cc @thomasppeacock @corneliusroemer @InfrPopGen

**Comment by FedeGueli** [comment]
9 sequences uploaded today from Alaska and Georgia in the US and newly found in Czechia (4 samples which cluster with an austrian sample) 
Given it is quite widespread from Usa to Uk, from Malaysia to Australia , and in central europe is uggest to designate it, as you can see there are more sequences on Usher than the ones uploaded to Gisaid:
<img width="1142" alt="Schermata 2023-01-26 alle 01 40 08" src="https://user-images.githubusercontent.com/87669813/214727794-5d3b223d-2122-4666-be2c-7ee75356f99a.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_270c7_1ca1f0.json?c=country&label=id:node_7869707

@thomasppeacock @corneliusroemer  @InfrPopGen consider it shows an early advantage versus parental XBB.1 ( considering in it also XBB.1.5) : https://cov-spectrum.org/explore/World/AllSamples/from=2022-11-15&to=2023-01-25/variants?nextcladePangoLineage=XBB.1*&nucMutations1=T23031C%2CG22895C%2CT22896C%2CC22664A%2CG22317T%2CG27915T%2CT23030C%2C24796T%2C4999C%2C745C%2C1466G%2C12439C&analysisMode=CompareToBaseline&

<img width="924" alt="Schermata 2023-01-26 alle 01 44 23" src="https://user-images.githubusercontent.com/87669813/214728706-23109a1f-86d0-468d-8241-8b3784b0f143.png">

While it is not far from XBB.1.5 itself :
<img width="969" alt="Schermata 2023-01-26 alle 01 44 54" src="https://user-images.githubusercontent.com/87669813/214728784-f6732d18-619b-4f59-8744-7573b851e52f.png">

**Comment by FedeGueli** [comment]
60 seqeunces as today growing steadily last samples from Texas, and Georgia

**Comment by FedeGueli** [comment]
62 viruses as today . It is spreading quite well in Georgia .

@corneliusroemer i think it could be designated at this point

**Comment by FedeGueli** [comment]
On Usher it is already 79 sequences:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_a346_2da650.json?c=userOrOld&label=id:node_7976128

<img width="1147" alt="Schermata 2023-02-08 alle 02 39 07" src="https://user-images.githubusercontent.com/87669813/217406573-70ca66ba-992d-4bed-8797-5110dae31fad.png">

**Comment by FedeGueli** [comment]
68 sequences with 3 new samples from Czechia. i think it is worth designating it.
