### ISSUE TITLE
BA.5.1 sub lineage defined by ORF1b:D1565N, ORF1b:P1427S, N_S79I, ORF9b:V76F and N_A273S  circulating in China - 48 sequences as 14/01/23

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1488]
I have spotted a sequence belonging to BA.5.1 in a sample from Sichuan,
Looking at the tree i spotted. a couple of recent sequences belonging to the same lineage from Singapore:
One of them is from a traveller from China.
Although 2 sequences could be too few to say with certainty it is likely that tthis one had or has some circulation in China,
so better monitoring it.

**Gisaid query**: N_S79I, N_A273S finds 36 viruses:
EPI_ISL_15296146, EPI_ISL_15441055, EPI_ISL_15443346,
EPI_ISL_15445726, EPI_ISL_15445731, EPI_ISL_15447982,
EPI_ISL_15448942, EPI_ISL_15535107, EPI_ISL_15554173,
EPI_ISL_15633952, EPI_ISL_15647068, EPI_ISL_15647259,
EPI_ISL_15670588, EPI_ISL_15737998, EPI_ISL_15800961,
EPI_ISL_15901681, EPI_ISL_15902590, EPI_ISL_15902923,
EPI_ISL_15904351, EPI_ISL_15947835, EPI_ISL_15959235,
EPI_ISL_15960402, EPI_ISL_16041092, EPI_ISL_16068810,
EPI_ISL_16099178, EPI_ISL_16150960, EPI_ISL_16150967,
EPI_ISL_16151906, EPI_ISL_16151909, EPI_ISL_16181577,
EPI_ISL_16191871 (China via Singapore), EPI_ISL_16219149, EPI_ISL_16220741,
EPI_ISL_16260642, EPI_ISL_16305661, EPI_ISL_16306931 (Sichuan)

Tree: 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_50c_d5fcf0.json?label=id:node_6782191
<img width="1167" alt="Schermata 2022-12-29 alle 10 54 26" src="https://user-images.githubusercontent.com/87669813/209934668-8f5ab379-aad9-4556-9ed5-52f0867686c3.png">

Defining mutations:
BA.5.1 > C29614T > C17130T > ORF1b:D1565N (G18160A) > ORF1b:P1427S (C17746T) > N:S79I (G28509T), ORF9b:V76F > C14265T > C23191T, N:A273S (G29090T )

**Comment by FedeGueli** [comment]
4 New samples from chinese capital Pechino uploaded today confirm that this lineage is circulating in China.

@thomasppeacock

**Comment by FedeGueli** [comment]
2 more sequences from chinese capital city Pechino. @InfrPopGen

**Comment by FedeGueli** [comment]
2 new samples came from Beijiing today confirming this is circaulting there although not at the same level of BF.7.14, BA.5.2.48 and BA.5.2.49.

@InfrPopGen @thomasppeacock

**Comment by FedeGueli** [comment]
4 more samples from airport surveillance in SOuth Korea and Japan all of them with travel history to China.
total now is 48. 

@InfrPopGen @thomasppeacock @corneliusroemer i suggest to designate this one is likely the fourth biggest lineage in China. A Designation will help to track it a lot.

**Comment by thomasppeacock** [comment]
thanks Fede! going to recommend this to try and keep on top of diversity of viruses circulating in China

**Comment by FedeGueli** [comment]
Thx @thomasppeacock

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.1.32 with 42 newly designated sequences, and 0 updated. Defining mutations G29090T (N:A273S), nt:C23191T (following C14265T).

**Comment by corneliusroemer** [comment]
Good call, I had also identified this as a candidate lineage with circulation in China

**Comment by FedeGueli** [comment]
Thank you all.
