### ISSUE TITLE
Another XBB.1 sublineage with S:F486P (12 seq, mainly SE Asia)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#1490]
Proposal for a sublineage of XBB.1
Earliest seq: 2022-11-04 (Indonesia)
Countries detected: Indonesia (3, all from West Kalimantan), India (1, from Telangana)

Mutations on top of XBB.1:
ORF8:G8*, then G16377A, then C13968A, then S:F486P

GISAID query: Spike_F486P + nuc mutations C13968A, G16377A

This is on a separate branch from XBB.1.5 but differs from it only by silent mutations, so it should have a similar growth advantage. XBB.1.5 has a head start in much of the world, but this lineage is spreading in countries that do much less sequencing, so it could still gain a foothold in some places; for example, XBB.1.5 has not yet been detected in Indonesia.

As usual, Usher says S:F486L when it means S:F486P.
<img width="665" alt="Indonesia_XBB1_486P" src="https://user-images.githubusercontent.com/42699509/209990850-2b84085e-614e-4a20-b23c-850842263d34.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_168b9_dcd560.json?c=gt-S_486&label=id:node_7684421](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_168b9_dcd560.json?c=gt-S_486&label=id:node_7684421)

[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=XBB.1*+%26+S%3AF486P+%26+%5B2-of%3A+C16377A%2C+C13968A%2C+17124T%5D&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=XBB.1*+%26+S%3AF486P+%26+%5B2-of%3A+C16377A%2C+C13968A%2C+17124T%5D&)

EPI_ISL_16027116
EPI_ISL_16040384
EPI_ISL_16194415
EPI_ISL_16315250

**Comment by FedeGueli** [comment]
Thx @silcn checking this one i found another one (XBB) with S:E132Q i m going to propose it

**Comment by FedeGueli** [comment]
5th sequence came in from Singapore today.

**Comment by FedeGueli** [comment]
2 new ones from Brunei with Spike_F486P + C13968A, G16377A ( i didnt check them)

**Comment by FedeGueli** [comment]
17 seqs as today

**Comment by FedeGueli** [comment]
19 as today

**Comment by corneliusroemer** [comment]
It now looks like this: 
<img width="1572" alt="image" src="https://user-images.githubusercontent.com/25161793/215787521-5570bbb4-18d2-477c-a36b-55ba0f065017.png">

This is a clear example for independent evolution of S:486P within XBB.1. I'll make it XBB.1.11 / XBB.1.11.1

<img width="1591" alt="image" src="https://user-images.githubusercontent.com/25161793/215787932-fa410a7e-26bd-4dcd-9915-6439f8606d26.png">
