### ISSUE TITLE
BQ.1.1.22 sublineage with S:S256P circulating in Uk 280 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1492]
Gisaid Query: T22328C,C913A

Defining mutations: BQ.1.1.22 > C913A > S:S256P ( T22328C)
Tree:
<img width="1156" alt="Schermata 2022-12-29 alle 23 55 03" src="https://user-images.githubusercontent.com/87669813/210018788-753dd480-2d4c-46dd-b57f-52d90c727dab.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ac19_e18fa0.json?label=id:node_6474871

Sequences (all UK) : 55 ( 45 on Gisaid)
EPI_ISL_16285787
EPI_ISL_16286582
EPI_ISL_16281022
EPI_ISL_16108552
EPI_ISL_16280339
EPI_ISL_15681953
EPI_ISL_16257621
EPI_ISL_16286554
EPI_ISL_15939039
EPI_ISL_15938925
EPI_ISL_15925982
EPI_ISL_15580139
EPI_ISL_15580143
EPI_ISL_16108492
EPI_ISL_16053417
EPI_ISL_15960470
EPI_ISL_16142567
EPI_ISL_16212561
EPI_ISL_15630706
EPI_ISL_15681986
EPI_ISL_15926161
EPI_ISL_15926071
EPI_ISL_15801112
EPI_ISL_15760441
EPI_ISL_15681784
EPI_ISL_15896373
EPI_ISL_15681817
EPI_ISL_16212501
EPI_ISL_16108570
EPI_ISL_16095010
EPI_ISL_16108576
EPI_ISL_15681796
EPI_ISL_16281429
EPI_ISL_16212498
EPI_ISL_16281212
EPI_ISL_16108720
EPI_ISL_16213618
EPI_ISL_15910216
EPI_ISL_16281287
EPI_ISL_15681797
EPI_ISL_16281437
EPI_ISL_15925978
EPI_ISL_15681964
EPI_ISL_16212564

**Comment by FedeGueli** [comment]
it doesnt seem very fast , closing it .

**Comment by FedeGueli** [comment]
255seqs as today

**Comment by FedeGueli** [comment]
Reopening this one after its recent evolution proposed in #1715 by @agamedilab

**Comment by FedeGueli** [comment]
It seems quite fast lately i suggest a designation of this one @InfrPopGen cause its advantage versus parental BQ.1.1.22 is clear for the lineage proposed here:

<img width="1025" alt="Schermata 2023-03-04 alle 19 41 36" src="https://user-images.githubusercontent.com/87669813/222923296-bae1b77c-fe02-469c-a5a5-1102150ab9f3.png">

and becomes very significant for its sublineage with S:257S proposed by @agamedilab in #1715 

<img width="962" alt="Schermata 2023-03-04 alle 19 42 21" src="https://user-images.githubusercontent.com/87669813/222923315-1254237e-0e8d-4096-9544-89c8860710cd.png">

And not that far from XBB.1.5 in Uk:
<img width="1001" alt="Schermata 2023-03-04 alle 19 43 51" src="https://user-images.githubusercontent.com/87669813/222923368-8c56ab9e-59e9-4607-866b-0d3cbc2b0859.png">


Link to covspectrum comparison tool vs parental BQ.1.1.22
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/from%3D2022-12-15%26to%3D2023-03-04/variants?nextcladePangoLineage=BQ.1.1.22*&nucMutations1=T22328C%2CC913A&analysisMode=CompareToBaseline&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage ER.1 with 225 newly designated sequences, and 10 updated. Defining mutation T22328C (S:S256P) (following C913A).

**Comment by FedeGueli** [comment]
Thx @InfrPopGen
