### ISSUE TITLE
CH.1.1.1 Sublineage with S:L176F, S:Q613H, N:T265I (51 seq, Jan 9)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1493]
### **Description**
**Sub-lineage of:** CH.1.1.1
**Earliest sequence:** 2022-11-6, Australia – EPI_ISL_15808174 (2nd sequence 2022-11-28, Wales)
**Most recent sequence:** 2022-12-8, Wales – EPI_ISL_16282012
**Countries circulating:** Wales (12), Australia (1), USA (1)
**Number of Sequences:** 14
**GISAID Query:** Spike_L176F, Spike_N185D, Spike_K444T, -NSP12_Y273H
**CovSpectrum Query:** Nextcladepangolineage:CH.1.1.1 & S:L176F
**Substitutions on top of CH.1.1.1:**
**Spike:** L176F, Q613H
**N:** T265I
**ORF3a:** A110V
**Nucleotide:** T4402A, C22088T, G23401T, C25721T, C29067T
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/CH.1.1.1%20%2B%20L176F%2C%20Q613H%2C%20N_T265I%20-%20subtreeAuspice1_genome_2926_e48320.json
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/33738461/210028785-1ab75ed4-1733-478e-acd2-315838d11e68.png">

**Evidence**
CH.1.1.1 is one of the fastest growing lineages, particularly in the UK, so the addition of two spike mutations and a nucleocapsid mutation is certainly of interest.

S:L176F and S:Q613H have both appeared in numerous lineages, and S:Q613H in particular seems to be on the rise of late and appears to provide a growth advantage to BQ.1* lineages that possess it.
 
**Genomes**
<details>
<summary>Genomes</summary>EPI_ISL_15808174, EPI_ISL_16109249, EPI_ISL_16171799, EPI_ISL_16214037, EPI_ISL_16282012, EPI_ISL_16282016, EPI_ISL_16282040, EPI_ISL_16282066, EPI_ISL_16300299, EPI_ISL_16300300, EPI_ISL_16300377, EPI_ISL_16300403, EPI_ISL_16300405, EPI_ISL_16300487
</details>

**Comment by ryhisner** [comment]
First sequence from England came in today, collection date December 17. EPI_ISL_16336163

**Comment by oobb45729** [comment]
S:Q613H is a mystery. Q613H and Q613E seem to prevail over other Q613 mutations. I noticed that both G23401T(Q613H) and C23399G(Q613E) create a potential start codon ATG while A23403G(D614G) loses one. Could an alternative ORF be involved here?

**Comment by FedeGueli** [comment]
There was a lineage, then reamained undesignated cause died off,  that emerged in south africa and had 613E and 346I .

**Comment by FedeGueli** [comment]
40 as today @ryhisner @corneliusroemer it could be the usual fast Uk cluster but has to be noticed that it was exported to NYC and AUS

**Comment by ryhisner** [comment]
11 new sequences today bring the total to 51.

**Comment by ryhisner** [comment]
Seems confined to England, so I'm closing.
