### ISSUE TITLE
DF.1 + S:V445A, ORF8:A51V(163sequences)

### ISSUE THREAD

**Issue by DoropFan** [cov-lineages/pango-designation#1494]
Description
Sub-lineage of:DF.1(BA.5.10.1.1)
Earliest sequence:2022-10-19(United States)
Countries circulating:United States134, Germany9, Canada7, Switzerland1, France1, Japan1
Sequences:153

Nucleotide mutations:C15738T,T22896C,C28045T
Amino acid changes:ORF8:A51V,S:V445A
[CovSpectrum:DF.1 (Nextclade) + S:V445A, ORF8:A51V](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AV445A%2CORF8%3AA51V&nextcladePangoLineage=DF.1&nextcladePangoLineage1=DF.1&)
![df1advantage](https://user-images.githubusercontent.com/118802079/210055448-f2dfe60f-4733-479c-b103-4acc48d7a2b4.jpg)
[CovSpectrum Compare variants](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AV445A%2CORF8%3AA51V&nextcladePangoLineage=DF.1&nextcladePangoLineage1=DF.1&analysisMode=CompareEquals&)
![df1mutations](https://user-images.githubusercontent.com/118802079/210055460-71d0edf9-61df-4ae8-b98a-d06eda997652.jpg)
[Genomes](https://lapis.cov-spectrum.org/gisaid/v1/sample/gisaid-epi-isl?dateFrom=2022-06-27&dateTo=2022-12-23&aaMutations=S%3AV445A%2CORF8%3AA51V&nextcladePangoLineage=DF.1&host=Human&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&orderBy=random)

**Comment by FedeGueli** [comment]
Great catch @DoropFan  , BA.5.10 is a really a super good example of stepwise evolution around the world:
Arose back in May 2022 in Eswatini with E:S50G and then gained S:262S landing in Philippines from there  it has spread globally gaining S:346T first then S:144del and now S:445A

**Comment by DoropFan** [comment]
Thank you always. @FedeGueli

**Comment by FedeGueli** [comment]
@DoropFan looking at a tree for a totally unrelated lineage shown me by @ryhisner i noticed that 2 sampels of this proposed sublineage ( in a branch further defined by orf1a:L3644F ) are labelled by Usher as China , even if they are from Usa, so i think they are boith travel related with China.
<img width="971" alt="Schermata 2022-12-31 alle 20 38 16" src="https://user-images.githubusercontent.com/87669813/210154119-79a27530-80ea-488d-ae9b-ab26d88f8d0a.png">
<img width="979" alt="Schermata 2022-12-31 alle 20 38 30" src="https://user-images.githubusercontent.com/87669813/210154122-5819c99e-b4d5-4b54-8b37-a110b02d7c6f.png">
<img width="1154" alt="Schermata 2022-12-31 alle 20 38 44" src="https://user-images.githubusercontent.com/87669813/210154128-cd53147a-485b-4bb9-bb54-be23d700e2ed.png">

They doesnt seem to be on Gisaid, @alurqu could you check please the metadata of these sequences on Gen Bank (i am not expert with it)?
It would be useful to understand if they were really imported from China or elesewhere (Hong Kong?).

**Comment by AngieHinrichs** [comment]
Ah, the presence of "MN908947.3" (the reference sequence) in the sequence names is totally throwing off the metadata in the usher tree display!  Sorry about that.  Notice that the GenBank accession link is to MN908947.3 not OQ070230.1 or OQ070245.1 as it should be.  The lineage is B, Nextstrain clade 19A, date 2019-12... all that metadata is for the reference sequence not the new sequences.  Sorry about that!  I will figure out how to ignore a GenBank accession in the isolate name part (USA/USA_UT-IDEL-2022120547_2022_MN908947.3/2022) when there is an actual GenBank accession for the sequence.  I wish people weren't so creative with their names.

Here are the GenBank links for those two sequences:
https://www.ncbi.nlm.nih.gov/nuccore/OQ070230
https://www.ncbi.nlm.nih.gov/nuccore/OQ070245

**Comment by AngieHinrichs** [comment]
> the presence of "MN908947.3" (the reference sequence) in the sequence names is totally throwing off the metadata in the usher tree display

This is fixed now on the test site (dev.usher.bio -- thanks @corneliusroemer for the domain name, and caveats that as the test site, it is less stable than the main site).

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/186983/210155926-48cb5a2e-bf35-48b5-9113-46c66bdc0392.png">

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs !! and Happy new year!

**Comment by InfrPopGen** [comment]
Happy New Year! We've added lineage DF.1.1 with 95 newly designated sequences, and 0 updated. Defining mutation T22896C (S:V445A) (following C28045T (ORF8:A51V), C15738T).

**Comment by FedeGueli** [comment]
Thx @InfrPopGen and congrats to @DoropFan for your first designation!

**Comment by DoropFan** [comment]
Publishing and sharing information, creating databases, researchers, pango teams, variant hunters
Thank you to everyone fighting SARS-Cov-2.
