### ISSUE TITLE
Undesignated BA.5.2+orf1b:1050N+S:R346T lineage  with S:K147N sampled also in Shangai - 242 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1496]
Looking at samples uploaded today from China i found this lineage, i strongly suspect it is a sublineage of BA.5.2.6 but Usher calls it BA.5.2 and Nextclade as well (@AngieHinrichs could you take a look at this please?)

Defining mutations:
BA.5.2 + > C27513T > C27012T > G12310A > Orf1b:1050N (C16616A) > C12616T >S:R346T (G22599C) > C24745T > T12673G > S:K147N (A22003T)

Tree:
<img width="1150" alt="Schermata 2022-12-30 alle 18 35 41" src="https://user-images.githubusercontent.com/87669813/210097791-1d63cc7e-54dc-4168-895d-4957e26b9caf.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a036_f1d440.json?c=country&label=id:node_7065284

Gisaid query: G22599C,C24745T,T12673G,A22003T finds 240 sequences:

<details>
<summary>Expand for EPI_ISLs</summary>
EPI_ISL_15106969, EPI_ISL_15215711, EPI_ISL_15349315,
EPI_ISL_15381837, EPI_ISL_15469525, EPI_ISL_15494710,
EPI_ISL_15503884, EPI_ISL_15521199, EPI_ISL_15535248,
EPI_ISL_15541047, EPI_ISL_15579782, EPI_ISL_15580998,
EPI_ISL_15582832, EPI_ISL_15608061, EPI_ISL_15636428,
EPI_ISL_15640381, EPI_ISL_15642691, EPI_ISL_15670594,
EPI_ISL_15673239, EPI_ISL_15683223, EPI_ISL_15684718,
EPI_ISL_15684745, EPI_ISL_15684891, EPI_ISL_15686466,
EPI_ISL_15686471, EPI_ISL_15686487, EPI_ISL_15694605,
EPI_ISL_15695169, EPI_ISL_15741161, EPI_ISL_15743598,
EPI_ISL_15743665, EPI_ISL_15758447, EPI_ISL_15775084,
EPI_ISL_15779428, EPI_ISL_15782114, EPI_ISL_15782151,
EPI_ISL_15783502, EPI_ISL_15783563, EPI_ISL_15783576,
EPI_ISL_15784102, EPI_ISL_15784139-15784140, EPI_ISL_15791394,
EPI_ISL_15793137, EPI_ISL_15798025, EPI_ISL_15799190,
EPI_ISL_15799974, EPI_ISL_15801321, EPI_ISL_15802251,
EPI_ISL_15802255, EPI_ISL_15802257, EPI_ISL_15802259,
EPI_ISL_15802339, EPI_ISL_15808345, EPI_ISL_15808512,
EPI_ISL_15819160, EPI_ISL_15826405, EPI_ISL_15826520,
EPI_ISL_15826651, EPI_ISL_15830685, EPI_ISL_15837361,
EPI_ISL_15838320, EPI_ISL_15840714, EPI_ISL_15840887,
EPI_ISL_15854023, EPI_ISL_15857169, EPI_ISL_15879292,
EPI_ISL_15899529, EPI_ISL_15901466, EPI_ISL_15901536,
EPI_ISL_15901700, EPI_ISL_15902159, EPI_ISL_15904767,
EPI_ISL_15904786, EPI_ISL_15904996, EPI_ISL_15907038,
EPI_ISL_15908315, EPI_ISL_15908357, EPI_ISL_15908367,
EPI_ISL_15910499, EPI_ISL_15911419, EPI_ISL_15911430,
EPI_ISL_15917718, EPI_ISL_15923244, EPI_ISL_15925959,
EPI_ISL_15925961, EPI_ISL_15925963, EPI_ISL_15925965,
EPI_ISL_15929962, EPI_ISL_15930009, EPI_ISL_15930028,
EPI_ISL_15930053, EPI_ISL_15935213, EPI_ISL_15939645,
EPI_ISL_15944560, EPI_ISL_15944693, EPI_ISL_15952596,
EPI_ISL_15952858, EPI_ISL_15953639, EPI_ISL_15955098,
EPI_ISL_15959403, EPI_ISL_15962317, EPI_ISL_15963203,
EPI_ISL_15967825, EPI_ISL_15976119, EPI_ISL_15985863,
EPI_ISL_15986970, EPI_ISL_15987054, EPI_ISL_15987397,
EPI_ISL_15987490, EPI_ISL_15987603, EPI_ISL_15987761,
EPI_ISL_15988344, EPI_ISL_15988478, EPI_ISL_15990657,
EPI_ISL_15990695, EPI_ISL_15990812, EPI_ISL_16003750-16003751,
EPI_ISL_16004783, EPI_ISL_16004992, EPI_ISL_16005317,
EPI_ISL_16006470, EPI_ISL_16006491, EPI_ISL_16007097,
EPI_ISL_16009158, EPI_ISL_16009453, EPI_ISL_16010811,
EPI_ISL_16016881, EPI_ISL_16018782, EPI_ISL_16024378,
EPI_ISL_16027167, EPI_ISL_16027239, EPI_ISL_16030057,
EPI_ISL_16030079, EPI_ISL_16041407, EPI_ISL_16041671,
EPI_ISL_16042948, EPI_ISL_16048893, EPI_ISL_16048929,
EPI_ISL_16048935, EPI_ISL_16057602, EPI_ISL_16058080,
EPI_ISL_16062102, EPI_ISL_16069346, EPI_ISL_16073645,
EPI_ISL_16074044, EPI_ISL_16077183, EPI_ISL_16077217,
EPI_ISL_16077649, EPI_ISL_16077700, EPI_ISL_16077832,
EPI_ISL_16079867, EPI_ISL_16079951, EPI_ISL_16079959,
EPI_ISL_16082410, EPI_ISL_16087702, EPI_ISL_16088864,
EPI_ISL_16099106, EPI_ISL_16099492, EPI_ISL_16103490,
EPI_ISL_16108830, EPI_ISL_16111777, EPI_ISL_16122819,
EPI_ISL_16122970, EPI_ISL_16123506-16123507, EPI_ISL_16125136,
EPI_ISL_16131581, EPI_ISL_16131761, EPI_ISL_16131867,
EPI_ISL_16137248, EPI_ISL_16150980, EPI_ISL_16152180,
EPI_ISL_16152203, EPI_ISL_16152220, EPI_ISL_16152243,
EPI_ISL_16152777, EPI_ISL_16153190, EPI_ISL_16153366,
EPI_ISL_16154082, EPI_ISL_16154442, EPI_ISL_16154460,
EPI_ISL_16154551, EPI_ISL_16165928, EPI_ISL_16178788,
EPI_ISL_16178834, EPI_ISL_16179453, EPI_ISL_16184349,
EPI_ISL_16184581, EPI_ISL_16192528, EPI_ISL_16192557,
EPI_ISL_16193092, EPI_ISL_16198822, EPI_ISL_16202654,
EPI_ISL_16217327, EPI_ISL_16217917, EPI_ISL_16218361,
EPI_ISL_16218549, EPI_ISL_16218975, EPI_ISL_16219182,
EPI_ISL_16219270, EPI_ISL_16219281, EPI_ISL_16220546,
EPI_ISL_16220742, EPI_ISL_16222469, EPI_ISL_16236034,
EPI_ISL_16245621, EPI_ISL_16248775, EPI_ISL_16248780,
EPI_ISL_16251282, EPI_ISL_16253511, EPI_ISL_16254369,
EPI_ISL_16255085, EPI_ISL_16258400, EPI_ISL_16258420,
EPI_ISL_16266024, EPI_ISL_16277427, EPI_ISL_16277510,
EPI_ISL_16278064, EPI_ISL_16282654, EPI_ISL_16291169,
EPI_ISL_16291453, EPI_ISL_16292608, EPI_ISL_16301971,
EPI_ISL_16307164, EPI_ISL_16309144, EPI_ISL_16310236,
EPI_ISL_16314639, EPI_ISL_16314646, EPI_ISL_16315637,
EPI_ISL_16316269, EPI_ISL_16317005, EPI_ISL_16327460,
EPI_ISL_16328418, EPI_ISL_16328988, EPI_ISL_16329114,
EPI_ISL_16329137, EPI_ISL_16329610, EPI_ISL_16331012,

</details>

**Comment by silcn** [comment]
@FedeGueli I think that C12616T probably came before S:R346T and therefore this isn't BA.5.2.6.

BA.5.2+ORF1b:T1050N+C12616T, without S:R346T, was particularly common in Indonesia, reaching 3-4% prevalence there in July-August. BA.5.2+ORF1b:T1050N+C12616T+S:R346T was also most prevalent in Indonesia where it reached around 10% there in October. To me this strongly suggests that BA.5.2+ORF1b:T1050N+C12616T+S:R346T is not BA.5.2.6+C12616T but instead descends from the Indonesian BA.5.2+ORF1b:T1050N+C12616T branch.

I think there's a decent case for designating BA.5.2+ORF1b:T1050N+C12616T+S:R346T first as BA.5.2.* and then this lineage can be a sublineage of that.

**Comment by FedeGueli** [comment]
Thanks @silcn  great analysis. indeed i agree on the timeline youn proposed for designations

**Comment by InfrPopGen** [comment]
Happy New Year! We've added lineage BA.5.2.47 with 972 newly designated sequences, and 0 updated. Defining mutation G22599C (S:R346T) (following C12616T), and for the sub-lineage, we've added lineage DQ.1 with 0 newly designated sequences, and 155 updated. Defining mutation A22003T (S:K147N) (following T12673G).
