### ISSUE TITLE
New BA.5.2 + Orf1b:1050N sublineage defined by Orf6_N28H and Orf1a:R207C circulating in Hong Kong, Japan and maybe China (Macau)(591Sequences as 07/01/2023)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1498]
I spotted another BA.5.2+Orf1b:1050N sublineage circulating in China and likely introduced locally from Hong Kong.
It emerged first in Philippines and from where was introduced in Hong Kong .
A first sample from China was intercepted by Japanese surveillance already  in September but i think it is likely that was from Hong Kong too ( EPI_ISL_15167994)

Tree:
<img width="1158" alt="Schermata 2022-12-30 alle 19 40 01" src="https://user-images.githubusercontent.com/87669813/210102443-666f01bd-9eb0-4173-ac33-e8e763c76d29.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_248c9_f2f670.json?c=userOrOld&label=id:node_6944695

Defining mutations:
BA.5.2 + > C27513T > C27012T > G12310A >Orf1b:T1050N (C16616A) > Orf6:N28H (A27283C) > Orf1a:R207C (C884T)

Gisaid query : NS6_N28H, NSP2_R27C finds 502 sequences 

Sequences:
<details>
<summary>Expand for EPI_ISLs</summary>
EPI_ISL_13445322-13445323, EPI_ISL_13445326-13445327, EPI_ISL_13512039,
EPI_ISL_13538635, EPI_ISL_13637635, EPI_ISL_13637660-13637661,
EPI_ISL_13637667-13637671, EPI_ISL_13637737, EPI_ISL_13695685,
EPI_ISL_13695696, EPI_ISL_13695712, EPI_ISL_13711223,
EPI_ISL_13711226, EPI_ISL_13711228, EPI_ISL_13711240,
EPI_ISL_13711243-13711245, EPI_ISL_13711248-13711249, EPI_ISL_13711251,
EPI_ISL_13711253, EPI_ISL_13711255-13711256, EPI_ISL_13743587,
EPI_ISL_13743752, EPI_ISL_13750907, EPI_ISL_13750909,
EPI_ISL_13751060, EPI_ISL_13825187, EPI_ISL_13848982,
EPI_ISL_13864195, EPI_ISL_13909568, EPI_ISL_13963790,
EPI_ISL_13963793, EPI_ISL_13963809, EPI_ISL_13963816,
EPI_ISL_13963833, EPI_ISL_13963835, EPI_ISL_13963838,
EPI_ISL_13963840-13963841, EPI_ISL_13963846, EPI_ISL_13964177-13964179,
EPI_ISL_14029038, EPI_ISL_14043673, EPI_ISL_14043779,
EPI_ISL_14055197, EPI_ISL_14255396, EPI_ISL_14357889,
EPI_ISL_14383349, EPI_ISL_14432524, EPI_ISL_14436587,
EPI_ISL_14442666, EPI_ISL_14454983, EPI_ISL_14480543,
EPI_ISL_14484200, EPI_ISL_14484240, EPI_ISL_14496427,
EPI_ISL_14496615, EPI_ISL_14507247, EPI_ISL_14507249,
EPI_ISL_14507253, EPI_ISL_14507255, EPI_ISL_14507257,
EPI_ISL_14537242, EPI_ISL_14537309-14537310, EPI_ISL_14538212,
EPI_ISL_14552287, EPI_ISL_14553973, EPI_ISL_14558777,
EPI_ISL_14594794, EPI_ISL_14597972, EPI_ISL_14602156,
EPI_ISL_14602158, EPI_ISL_14602160-14602161, EPI_ISL_14602166,
EPI_ISL_14602168, EPI_ISL_14602178, EPI_ISL_14617453-14617454,
EPI_ISL_14617458, EPI_ISL_14617470, EPI_ISL_14617473,
EPI_ISL_14622772, EPI_ISL_14628237, EPI_ISL_14628638,
EPI_ISL_14637371, EPI_ISL_14637378, EPI_ISL_14650795,
EPI_ISL_14650925, EPI_ISL_14651498, EPI_ISL_14685330,
EPI_ISL_14700784, EPI_ISL_14716020, EPI_ISL_14736566,
EPI_ISL_14746202, EPI_ISL_14750736, EPI_ISL_14770205,
EPI_ISL_14784201, EPI_ISL_14799287, EPI_ISL_14810276,
EPI_ISL_14810286, EPI_ISL_14810290, EPI_ISL_14810301,
EPI_ISL_14810308, EPI_ISL_14810317, EPI_ISL_14810330-14810331,
EPI_ISL_14810339-14810340, EPI_ISL_14810342, EPI_ISL_14810348,
EPI_ISL_14810355, EPI_ISL_14810357, EPI_ISL_14810366,
EPI_ISL_14830071, EPI_ISL_14830832, EPI_ISL_14835978,
EPI_ISL_14849663, EPI_ISL_14850506, EPI_ISL_14856314,
EPI_ISL_14897040, EPI_ISL_14923467, EPI_ISL_14954697,
EPI_ISL_14979018, EPI_ISL_14982826, EPI_ISL_14998616,
EPI_ISL_15016550, EPI_ISL_15016711, EPI_ISL_15016877,
EPI_ISL_15021579-15021582, EPI_ISL_15021584, EPI_ISL_15021586-15021587,
EPI_ISL_15021589-15021591, EPI_ISL_15021593, EPI_ISL_15021595,
EPI_ISL_15021598, EPI_ISL_15021600, EPI_ISL_15021609-15021611,
EPI_ISL_15021615, EPI_ISL_15021617, EPI_ISL_15021621,
EPI_ISL_15021623-15021624, EPI_ISL_15021638, EPI_ISL_15021641,
EPI_ISL_15021651, EPI_ISL_15027225, EPI_ISL_15028444,
EPI_ISL_15035878, EPI_ISL_15035905, EPI_ISL_15037993,
EPI_ISL_15037995, EPI_ISL_15038013, EPI_ISL_15043433,
EPI_ISL_15047463, EPI_ISL_15052448, EPI_ISL_15055025,
EPI_ISL_15055030, EPI_ISL_15055032, EPI_ISL_15055035-15055036,
EPI_ISL_15055041, EPI_ISL_15055054, EPI_ISL_15055056-15055057,
EPI_ISL_15055059, EPI_ISL_15060768, EPI_ISL_15101383,
EPI_ISL_15101749, EPI_ISL_15110332, EPI_ISL_15120202,
EPI_ISL_15120217, EPI_ISL_15120280, EPI_ISL_15120294,
EPI_ISL_15123524, EPI_ISL_15151845, EPI_ISL_15152336,
EPI_ISL_15165813, EPI_ISL_15167994, EPI_ISL_15169282,
EPI_ISL_15169288-15169289, EPI_ISL_15169291, EPI_ISL_15169294-15169295,
EPI_ISL_15169306, EPI_ISL_15169325, EPI_ISL_15169327-15169328,
EPI_ISL_15169339, EPI_ISL_15178892, EPI_ISL_15179336,
EPI_ISL_15185409, EPI_ISL_15185429, EPI_ISL_15185469,
EPI_ISL_15185539, EPI_ISL_15185609, EPI_ISL_15247613,
EPI_ISL_15248231, EPI_ISL_15269242, EPI_ISL_15269259,
EPI_ISL_15269267, EPI_ISL_15269272, EPI_ISL_15269274,
EPI_ISL_15275262, EPI_ISL_15275811-15275812, EPI_ISL_15278939,
EPI_ISL_15301116, EPI_ISL_15318874, EPI_ISL_15341030,
EPI_ISL_15357096, EPI_ISL_15357150, EPI_ISL_15357224,
EPI_ISL_15357339, EPI_ISL_15357355, EPI_ISL_15357359,
EPI_ISL_15357446, EPI_ISL_15357505, EPI_ISL_15358017,
EPI_ISL_15364896, EPI_ISL_15373757, EPI_ISL_15376440,
EPI_ISL_15402220-15402222, EPI_ISL_15402233, EPI_ISL_15402235,
EPI_ISL_15402237, EPI_ISL_15402242-15402244, EPI_ISL_15402268,
EPI_ISL_15402272-15402273, EPI_ISL_15402275, EPI_ISL_15402285,
EPI_ISL_15402294, EPI_ISL_15402301, EPI_ISL_15402303,
EPI_ISL_15402308, EPI_ISL_15402316, EPI_ISL_15402326,
EPI_ISL_15407550, EPI_ISL_15423587, EPI_ISL_15447894,
EPI_ISL_15471032, EPI_ISL_15471190, EPI_ISL_15471405,
EPI_ISL_15471439, EPI_ISL_15471455, EPI_ISL_15476200,
EPI_ISL_15480275, EPI_ISL_15484385, EPI_ISL_15494639,
EPI_ISL_15504801, EPI_ISL_15531873, EPI_ISL_15531875,
EPI_ISL_15532675, EPI_ISL_15532977, EPI_ISL_15533350,
EPI_ISL_15539091-15539092, EPI_ISL_15539138, EPI_ISL_15570991,
EPI_ISL_15573814, EPI_ISL_15578284, EPI_ISL_15578383,
EPI_ISL_15580796, EPI_ISL_15593768, EPI_ISL_15625562,
EPI_ISL_15625814, EPI_ISL_15627012, EPI_ISL_15627466,
EPI_ISL_15627526, EPI_ISL_15627581, EPI_ISL_15641034,
EPI_ISL_15641053, EPI_ISL_15641063, EPI_ISL_15641080,
EPI_ISL_15641299, EPI_ISL_15641435, EPI_ISL_15657631-15657632,
EPI_ISL_15658621, EPI_ISL_15659243, EPI_ISL_15659520,
EPI_ISL_15679103, EPI_ISL_15679242-15679253, EPI_ISL_15679262,
EPI_ISL_15679293, EPI_ISL_15679318, EPI_ISL_15679370,
EPI_ISL_15679391, EPI_ISL_15679403, EPI_ISL_15679444-15679445,
EPI_ISL_15679482, EPI_ISL_15679506-15679507, EPI_ISL_15679513,
EPI_ISL_15679521-15679522, EPI_ISL_15679548-15679549, EPI_ISL_15679563,
EPI_ISL_15679576, EPI_ISL_15679578, EPI_ISL_15679585,
EPI_ISL_15679591, EPI_ISL_15679647, EPI_ISL_15679649,
EPI_ISL_15679688-15679689, EPI_ISL_15679716-15679718, EPI_ISL_15679734,
EPI_ISL_15679737-15679739, EPI_ISL_15679775, EPI_ISL_15679781,
EPI_ISL_15679797-15679798, EPI_ISL_15679810, EPI_ISL_15679829,
EPI_ISL_15679835, EPI_ISL_15679837, EPI_ISL_15679846,
EPI_ISL_15679852-15679854, EPI_ISL_15679861, EPI_ISL_15679864,
EPI_ISL_15679866-15679867, EPI_ISL_15679881, EPI_ISL_15679884,
EPI_ISL_15679931, EPI_ISL_15679936-15679956, EPI_ISL_15679983,
EPI_ISL_15679985, EPI_ISL_15679987, EPI_ISL_15679989,
EPI_ISL_15679995, EPI_ISL_15679997, EPI_ISL_15680008-15680009,
EPI_ISL_15680017, EPI_ISL_15680160, EPI_ISL_15680164,
EPI_ISL_15680223, EPI_ISL_15680225, EPI_ISL_15680232,
EPI_ISL_15680235, EPI_ISL_15680252, EPI_ISL_15680356-15680359,
EPI_ISL_15680376, EPI_ISL_15680378, EPI_ISL_15680428,
EPI_ISL_15680455, EPI_ISL_15680490-15680491, EPI_ISL_15680522,
EPI_ISL_15680525-15680529, EPI_ISL_15680531, EPI_ISL_15680547,
EPI_ISL_15680571, EPI_ISL_15680584, EPI_ISL_15680606,
EPI_ISL_15680614, EPI_ISL_15680634, EPI_ISL_15680663,
EPI_ISL_15680674, EPI_ISL_15680685, EPI_ISL_15680699,
EPI_ISL_15680725, EPI_ISL_15680832, EPI_ISL_15680954-15680957,
EPI_ISL_15680962, EPI_ISL_15680996, EPI_ISL_15680998,
EPI_ISL_15681006, EPI_ISL_15681009, EPI_ISL_15681018,
EPI_ISL_15681020, EPI_ISL_15681042, EPI_ISL_15681045,
EPI_ISL_15681049, EPI_ISL_15681054, EPI_ISL_15681098,
EPI_ISL_15681108, EPI_ISL_15681114, EPI_ISL_15684459,
EPI_ISL_15684461, EPI_ISL_15695125, EPI_ISL_15696883,
EPI_ISL_15731634, EPI_ISL_15739550, EPI_ISL_15740326,
EPI_ISL_15756035, EPI_ISL_15756076, EPI_ISL_15798113,
EPI_ISL_15810596, EPI_ISL_15811408, EPI_ISL_15823184,
EPI_ISL_15829560, EPI_ISL_15829964, EPI_ISL_15830383,
EPI_ISL_15832788, EPI_ISL_15834917, EPI_ISL_15875556,
EPI_ISL_15894792-15894793, EPI_ISL_15894858, EPI_ISL_15894921,
EPI_ISL_15924014, EPI_ISL_15924255, EPI_ISL_15925355-15925356,
EPI_ISL_15930673, EPI_ISL_15955177, EPI_ISL_15979177,
EPI_ISL_16003342, EPI_ISL_16014431, EPI_ISL_16016833,
EPI_ISL_16026828, EPI_ISL_16093297, EPI_ISL_16093313,
EPI_ISL_16102477, EPI_ISL_16160328, EPI_ISL_16179146,
EPI_ISL_16181555, EPI_ISL_16230750, EPI_ISL_16257423,
EPI_ISL_16327352, EPI_ISL_16327369, EPI_ISL_16327481,
EPI_ISL_16327635

</details>

**Comment by FedeGueli** [comment]
70 viruses uploaded today from Hong Kong collected back from August to December.
Likely this lineage has been exported to Shangai and sampled there from travellers .

**Comment by FedeGueli** [comment]
586 sequences as today. 4 samples from Shanghai not flagged as imported let me think maybe it is circulating at low levels there. waiting a bit before designating could be a good idea.

**Comment by AnonymousUserUse** [comment]
More than 60% of sequences of this lineage comes from Hong Kong, with a prevalence of up to 20% there, so I think it is clear a Hong Kong lineage.
