### ISSUE TITLE
New lineage proposal for B.1.1.74 with multiple spike mutations

### ISSUE THREAD

**Issue by erikalmecdc** [cov-lineages/pango-designation#15]
New lineage proposal for B.1.1.74 with multiple spike mutations
by Erik Alm

Description
Sub-lineage of: B.1.1.74
Earliest sequence: 2021-01-07
Most recent sequence: 2021-02-07
Countries circulating: Nigeria, UK, USA

Multiple spike mutations and NSP6 deletion commonly seen in VOCs compared to ancestral lineage, already spread to multiple countries.
Spike D614G, Spike D796H, Spike E484K, Spike P681H, Spike T95I, Spike Y144del
NSP6 106-108del

Evidence, see 
[new lineage.txt](https://github.com/cov-lineages/pango-designation/files/6002622/new.lineage.txt)
attachments

Proposed lineage name: Q.1
![new lineage](https://user-images.githubusercontent.com/36880285/108355039-91f57280-71ea-11eb-88e9-6ce222c029c4.PNG)

**Comment by rambaut** [comment]
Looks good, thanks Erik. Will wait for Áine to confirm.

**Comment by rambaut** [comment]
Can confirm the lineage but I don't think B.1.1.74 is the correct parent. 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/686405/108631315-34b72680-7461-11eb-8fdb-b953426028d7.png">

I think this should just be a sublineage of B.1.1

**Comment by rambaut** [comment]
An expanded list of taxa (as of 2021-02-21):
[B.1.1.X_Nigeria_UK_E484K_P681H_Y144del_nsp6del.taxa.txt](https://github.com/cov-lineages/pango-designation/files/6018100/B.1.1.X_Nigeria_UK_E484K_P681H_Y144del_nsp6del.taxa.txt)

**Comment by rambaut** [comment]
Defining mutations:
```
ORF1ab:	K2511N
		T2936I
		A9891V
		T3284I
		11288-11296 SGFdel
		V6772M
		
spike:	T95I
		21991-21993	Y144del
		E484K
T23287C	
		P681H
		D796H
C24382T
C25276A

M:		I82T

ORF8:	27886-27900del deletes MK at start of ORF8 and frameshift
G28209T

N:		28896-28900del AR->G
 ```

**Comment by aineniamh** [comment]
Now designated as B.1.1.318, tagged in release [1.0.7](https://github.com/cov-lineages/pango-designation/releases/tag/v1.0.7). Thanks @erikalmecdc for flagging the lineage!
