### ISSUE TITLE
XBB.1.5 sublineage with S:H146K (442 sequences from USA [Northeast USA, California, Idaho, North Carolina], Denmark, Netherlands)

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#1503]
**XBB.1.5 sublineage with S:H146K mainly in USA** 

**Earliest Sample collection date:** 11/01/2022 [New York City, NY; EPI_ISL_15749691]
**Latest sequence:** 12/21/2022 [New York City, NY; EPI_ISL_16344162]
**Countries circulating:** USA, Denmark, Netherlands
**GISAID Query:** Spike_H146K, Spike_V83A, Spike_G252V, Spike_F486P, Spike_F490S

**Highlight:** 
Two 2-nucleotide changes-
                  Spike:F486P (characteristic of XBB.1.5)
                  Spike:H146K (also found in the recently designated XBB.1.6 | #1428  

UshER doesn't deal very well with 2-nuc mutations as noted by others earlier. 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_403af_9d2c0.json?c=gt-S_486,146,83,252,183&label=id:node_7698366

![image](https://user-images.githubusercontent.com/98380390/210155118-168324d7-4479-4cdd-a981-30b31e5f1a57.png)

Early days, seems to be faster than the parent XBB.1.5
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?nextcladePangoLineage=XBB.1.5*&aaMutations1=S%3AH146K&nextcladePangoLineage1=XBB.1.5*&analysisMode=CompareToBaseline&
                 
GISAID IDs: 
[GISAID_hcov-19_ids_2022_12_31_20_35.csv](https://github.com/cov-lineages/pango-designation/files/10327948/GISAID_hcov-19_ids_2022_12_31_20_35.csv)

**Comment by silcn** [comment]
@RajLABN most of the sequences that GISAID claims to have H146K actually don't. There's some artefact that can cause it to show a sequence of spurious mutations Y144L, Y145P, H146K, N148Q, N149Q. If you want sequences that really have S:H146K you should use the nucleotide mutations C21998A and C22000A instead - currently there are 77 on GISAID and they aren't all monophyletic.

**Comment by Sinickle** [comment]
@silcn more artifacts in that region too! I think there's a legitimate S:146K and S:148T XBB.2 sublineage at the moment with 9 seqs, but just searching for those two mutations returns hundreds of sequences, not all XBB, many of which have Spike-insert-152K too..

**Comment by aviczhl2** [comment]
> @RajLABN most of the sequences that GISAID claims to have H146K actually don't. There's some artefact that can cause it to show a sequence of spurious mutations Y144L, Y145P, H146K, N148Q, N149Q. If you want sequences that really have S:H146K you should use the nucleotide mutations C21998A and C22000A instead - currently there are 77 on GISAID and they aren't all monophyletic.


Are seqs with both C21998A and C22000A ensured not artefacts? Or is there a possible query to filter out all non-artefact S:146K? 

 S:146K is quite common among all XBBs now, with 23098 seqs on GISAID, or 21065 if limiting the collection after 2023-1-1. 

I think something shall be worked on it instead of simply ignoring it.

**Comment by AngieHinrichs** [comment]
Yesterday I took a look at C21998A in XBB in the UShER tree and it is a mess.  Starting with the 2023-07-21 build, I'm going to mask sites 21994, 21995 (#1882) and 21998 (also mentioned in #1999 and #1918) in the XBB branch of the UShER tree.

First, C21998A appears an implausibly large number of times across pretty much all sublineages of XBB.  Look at all the scattered red in XBB.1.16 and XBB.1.9 (taxonium, coloring by base 21998):
<img width="980" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/186983/379db5c6-39b2-4557-a89e-0cab1b3fe4c5">

And a same-sized portion of XBB.1.5 (without T10204C):
<img width="980" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/186983/5dcdb574-b5a4-4ca5-8534-a4bf2da5abf4">

And XBB.1.5 (with T10204C):
<img width="980" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/186983/0d3a15c0-688f-4934-abbe-b411c9d737d1">

Most XBB sublineages have a branch that is sublineage > C21998A, and the larger sublineages not surprisingly have larger C21998A branches.  But if I zoom into one of those large sublineage > C21998A branches, and color the samples by pangolin-assigned lineage, I often see samples that probably belong in sub-sublineages being pulled in by C21998A.  For example, here's XBB.1.5 > C21998A -- still coloring by base at 21998, you can see there are a lot of reversions, another dubious sign:
<img width="468" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/186983/4fcd2aa5-028a-4fe1-992b-10268ef2db68">

Now if I color it by pangolin-assigned lineage, you can see a smattering of branches with other colors, where sequences have (in addition to C21998A) mutations characteristic of many XBB.1.5 sublineages:
<img width="468" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/186983/9a30eeeb-c63b-4702-96ab-655d8c2449a6">
A "mini-XBB.1.5" like that, to me, is a classic sign of a systematic error -- or if not an error, then a mutation that is so extremely homoplasic that it needs to be masked in UShER, to prevent it from messing up lineage assignments.

Masking 21998 will probably lose a few real mutations, but I believe it will prevent a lot more tree problems.

The situation with 21994 and 21995 is similar, but less dramatic in the tree, and those have been pretty well explained as a homopolymer/sequencing problem in the discussion in #1882.

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
Please close this issue
