### ISSUE TITLE
BQ.1.1 Sublineage with S:Q218L, S:T250N, >10% in Panama (47 seq, Jan 12)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1504]
### **Description**
**Sub-lineage of:** BQ.1.1
**Earliest sequence:** 2022-11-7, Panama — EPI_ISL_15866841
**Most recent sequence:** 2022-12-14, USA, California — EPI_ISL_16308141
**Countries circulating:** Panama (26), USA (8), Austria (2), Peru (1), Scotland (1)
**Number of Sequences:** 38
**GISAID Query:** Spike_Q218L, Spike_T250N
**CovSpectrum Query:** Nextcladepangolineage: BQ.1.1* & [3-of: C5575T, C14097T, A22215T, C22311A]
**Substitutions on top of BQ.1.1:**
**Spike:** Q218L, T250N
**Nucleotide:** C5575T, C14097T, A22215T, C22311A
 
 
**USHER Tree**
Due to low coverage in many Panama sequences and the bizarre decision of Usher to place 11 of these sequences in separate branches of a BA.2 tree, the Usher tree isn’t very enlightening here. Links to both trees are below, but only the BQ.1.1 tree is pictured.

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/33738461/210159796-d22249de-bbff-4865-9cef-dda5036db2cf.png">

https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1.1%20%2B%20Q218L%2C%20T250N%20-%20Tree%201%20-%20subtreeAuspice2_genome_3aba1_e4c80.json  
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1.1%20%2B%20Q218L%2C%20T250N%20-%20Tree%202%20-%20subtreeAuspice1_genome_3aba1_e4c70.json   
 
 
**Evidence**
This lineage appears to have originated in Panama in early November. Panama typically uploads sequences about once a week, though there’s some irregularity in that schedule. The numbers here are small, so all the usual caveats about uncertainty and possible biased sampling apply. However, taken at face value, this lineage appears to be growing as a percentage of all sequences in Panama, and in the most recent week, it made up 11.4% of the sequences uploaded (10/88), up from 6.5% the previous week. Given that the first sequence wasn’t uploaded until November 22, this appears to be remarkable growth.
 
If this had remained confined entirely to Panama and perhaps neighboring countries, I would suspect some urban superspreading event followed by biased sampling, but as one would expect if this lineage were truly growing and made up an appreciable proportion of sequences in Panama, it’s now begun to spread to other countries, some of them very far apart geographically. Sequences have turned up in Austria, Scotland, Peru, and in five different US states, ranging from the West Coast (California), the Deep South (Texas, Florida, Georgia), and the East Coast (New Jersey).

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/33738461/210159902-a6dd551f-2025-4b5a-933e-6caf5c5193c4.png">
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15866841, EPI_ISL_15866853, EPI_ISL_15866857, EPI_ISL_16018864, EPI_ISL_16018890, EPI_ISL_16018902, EPI_ISL_16018909, EPI_ISL_16018919, EPI_ISL_16018920, EPI_ISL_16095843, EPI_ISL_16104834, EPI_ISL_16114091, EPI_ISL_16163774, EPI_ISL_16184973, EPI_ISL_16203149, EPI_ISL_16205060, EPI_ISL_16225911, EPI_ISL_16237810, EPI_ISL_16237841, EPI_ISL_16237856, EPI_ISL_16237860, EPI_ISL_16237861, EPI_ISL_16237891, EPI_ISL_16262485, EPI_ISL_16308141, EPI_ISL_16315406, EPI_ISL_16315418, EPI_ISL_16315441, EPI_ISL_16315450, EPI_ISL_16315456, EPI_ISL_16315460, EPI_ISL_16315462, EPI_ISL_16315463, EPI_ISL_16315468, EPI_ISL_16315477, EPI_ISL_16316745, EPI_ISL_16318749, EPI_ISL_16320596
</details>

**Comment by AngieHinrichs** [comment]
> bizarre decision of Usher to place 11 of these sequences in separate branches of a BA.2 tree

Thanks for pointing out the garbage branch!  Will clean that up today.

**Comment by FedeGueli** [comment]
46 as today
