### ISSUE TITLE
BA.2.3.20 sublineage with additional S:R346T and S:F486S (17 sequences as of 2022-01-06)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1509]
### Description
**Sublineage of**: BA.2.3.20
**Earliest sequence**: 2022/11/07 (Australia-NSW)
**Most recent sequence**: 2022/12/14 (US-CA)
**Countries circulating**: US-CA (10/16), Korea (4/16), Israel (1/16), Australia-NSW (1/16) 
**Mutations on top of BA.2.3.20**: G22599C (S:R346T), T23019C (S:F486S)
**GISAID query**: -T25171C, C25810T, T22020C, G22599C, T23019C
**Cov-spectrum query**: 25171T, 25810T, 22020C, 22599C, 23019C

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/210185726-c87d041e-aec4-4f97-b47f-7798e194edb2.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14c6c_16a8c0.json?c=gt-nuc_25171&label=id:node_7817272
It is (mis)placed by Usher next to CM.7, but I think it's actually branched off the basal of BA.2.3.20 tree as it lacks a defining mutation (T25171C) of many CM.x. (@AngieHinrichs could you please take a look?)

### Genomes:
EPI_ISL_15820662, EPI_ISL_16021391, EPI_ISL_16082926, EPI_ISL_16083005, EPI_ISL_16132847, EPI_ISL_16132906, EPI_ISL_16132940, EPI_ISL_16135804, EPI_ISL_16136185, EPI_ISL_16226151, EPI_ISL_16246949, EPI_ISL_16250124, EPI_ISL_16265945, EPI_ISL_16293532, EPI_ISL_16340077, EPI_ISL_16341392

**Comment by AngieHinrichs** [comment]
> It is (mis)placed by Usher next to CM.7, but I think it's actually branched off the basal of BA.2.3.20 tree as it lacks a defining mutation (T25171C) of many CM.x.

Yeah -- looks like it was pulled in by a couple USA sequences (USA/FL-CDC-QDX42768003/2022 and USA/TX-CDC-QDX44166192/2022) that share BA.2.3.20 + S:F486S/T23019C + S:R346T/G22599C with these sequences and also have T25171C.  I will try pruning those two and reoptimizing which should move this branch out of the T25171C branch -- but when those two sequences are added back in the next daily build, it's possible that the branch might be moved back again until and unless there are some BA.2.3.20 + (either S:F486S/T23019C or S:R346T/G22599C) sequences for a parsimony win.  Fortunately the T25171C > ... > C25171T flip-flop doesn't risk messing up the lineage designation, this clearly would be CM.something.

**Comment by FedeGueli** [comment]
Already 20 seqs with NSP2_T547I,NSP3_I896T,Spike_r346T,Spike_F486S

**Comment by c19850727** [comment]
17 sequences now. Newly found in Singapore (local case).

**Comment by corneliusroemer** [comment]
Looks legit, the CM.7 triplet also looks legit but is homoplasic occurence of 346T and 486S

I thought someone said BA.2.3.20 wouldn't tolerate 346T due to some salt bridge.
