### ISSUE TITLE
B.1.243.1 lineage no longer being classified

### ISSUE THREAD

**Issue by ptskidmore** [cov-lineages/pango-designation#151]
The B.1.243.1 lineage was designated in issue #35. A recent version of pangolin no longer classifies this lineage. In fact, when filtering by this lineage in GISAID, no sequences are found.

One of the sequences used to define this lineage (EPI_ISL_1364812) is now classified as the parental B.1.243 lineage. This was done using pangolearn (2021-07-09), constellations (v0.0.11), and pango-designation (v1.2.38)

**Comment by chrisruis** [comment]
Thanks for letting us know @ptskidmore. B.1.243.1 should now be back with the latest pangolin update
