### ISSUE TITLE
BM.1.1.3 sublineage with S:F490P circulating in Scotland and 3 continents - 32 sequences 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1511]
Here i want to propose another lineage that popped up with S:F490P , it is a sublineage of BM.1.1.3

Defining mutations:
BM.1.1.3 + > S:F490S ( 1st nuc:T23031C) > T4057C, G13348T, C16626T, S:F490P (2nd Nuc:T23030C )

Tree:
<img width="1163" alt="Schermata 2023-01-02 alle 17 23 15" src="https://user-images.githubusercontent.com/87669813/210257194-bbd20f51-ec08-48ba-bc72-479937dfeff5.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_315c9_301ad0.json?c=userOrOld&label=id:node_7895052

CovSpectrum Query: T4057C, G13348T, C16626T   finds 32 samples

Gisaid query: T4057C, G13348T, C16626T finds 32 sequences:
EPI_ISL_15665209, EPI_ISL_15677383, EPI_ISL_15677434,
EPI_ISL_15677457, EPI_ISL_15709266, EPI_ISL_15727129,
EPI_ISL_15738259, EPI_ISL_15786006, EPI_ISL_15786019,
EPI_ISL_15926408, EPI_ISL_15955403, EPI_ISL_15974649,
EPI_ISL_16000846, EPI_ISL_16005603, EPI_ISL_16029826,
EPI_ISL_16040194, EPI_ISL_16062170, EPI_ISL_16095479,
EPI_ISL_16095877, EPI_ISL_16104173, EPI_ISL_16104337,
EPI_ISL_16108820, EPI_ISL_16126461, EPI_ISL_16126608,
EPI_ISL_16199222, EPI_ISL_16236730, EPI_ISL_16282190,
EPI_ISL_16294715, EPI_ISL_16312302, EPI_ISL_16312327,
EPI_ISL_16312331, EPI_ISL_16312333

Countries:
<img width="1156" alt="Schermata 2023-01-02 alle 17 26 59" src="https://user-images.githubusercontent.com/87669813/210257546-aa1f0759-830a-41b7-b72f-5e891dfcbe92.png">

**Comment by FedeGueli** [comment]
(Btw there are two more very recent sequences with S:F490P from Australia belonging to XBF , i will track them too with Spike_F486P,Spike_F490P)

**Comment by silcn** [comment]
Duplicate of #1321

**Comment by FedeGueli** [comment]
thx @silcn i commented there 4 days ago.. just forgotten!
