### ISSUE TITLE
BQ.1.1 Sublineage with S:Y248D (338 seq, Jan 22)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1512]
### **Description**
**Sub-lineage of:** BQ.1.1
**Earliest sequence:** 2022-10-10, France, Hauts-de-France, Denain — EPI_ISL_15480144
**Most recent sequence:** 2022-12-23, Denmark — EPI_ISL_16331436
**Countries circulating:** Mostly NW Europe—Netherlands (26), Denmark (14), France (11), Spain (10), Belgium (7), England (4), Sweden (3), Bonaire (2), Israel (2), Italy (2), Norway (2), Austria (1), Germany (1), Ireland (1), USA (1)
**Number of Sequences:** 87
**GISAID Query:** Spike_Y248D, -Spike_Y248del, NSP12_Y273H, -NSP13_Y421H
**CovSpectrum Query:** Nextcladepangolineage:BQ.1* & S:Y248D & !ORF1b:Y1344H
**Substitutions on top of BQ.1.1:**
**Spike:** Y248D
**Nucleotide:** T22304G
 
 
**USHER Tree**
Unfortunately, Usher places this lineage on a junky BA.2 tree that’s chock-full of “reversions,” so this tree is of limited usefulness.
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1.1%20%2B%20Y248D%20-%20subtreeAuspice1_genome_2bdd1_262480.json

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/33738461/210273237-3dc4c944-b14b-4878-9e66-bce0a2d9936a.png">

 
**Evidence**
We’ve seen three major variations on S:Y248 mutations so far: S:Y248S, S:Y248H, and S:Y248N. All three were contained in successful lineages and appeared to confer some degree of growth advantage relative to the lineages they descended from. S:Y248D, however, has been almost nonexistent until this lineage started to grow in early November. Very few pre-November sequences are returned by a CovSpectrum search for T22304G. Below is a graph of the proportion of sequences with T22304G throughout 2022.

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/33738461/210273210-0b4f3ccc-5128-413d-a17a-0e7dd6180c8a.png">

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15480144, EPI_ISL_15495039, EPI_ISL_15616119, EPI_ISL_15785056, EPI_ISL_15896651, EPI_ISL_15896659, EPI_ISL_15896711, EPI_ISL_15912227, EPI_ISL_15935239, EPI_ISL_15935247, EPI_ISL_16002568, EPI_ISL_16002570, EPI_ISL_16019846, EPI_ISL_16021396, EPI_ISL_16027987, EPI_ISL_16034705, EPI_ISL_16034835, EPI_ISL_16080214, EPI_ISL_16099517, EPI_ISL_16099522, EPI_ISL_16104142, EPI_ISL_16110916, EPI_ISL_16126846, EPI_ISL_16127561, EPI_ISL_16141712, EPI_ISL_16166705-16166706, EPI_ISL_16181895, EPI_ISL_16198327, EPI_ISL_16202038, EPI_ISL_16202445, EPI_ISL_16202574, EPI_ISL_16214673-16214674, EPI_ISL_16215039, EPI_ISL_16217340, EPI_ISL_16234062, EPI_ISL_16235132, EPI_ISL_16238355, EPI_ISL_16238604, EPI_ISL_16244821, EPI_ISL_16244826, EPI_ISL_16244833-16244834, EPI_ISL_16246709, EPI_ISL_16248675, EPI_ISL_16248707, EPI_ISL_16248944, EPI_ISL_16249241, EPI_ISL_16250934, EPI_ISL_16256572, EPI_ISL_16258677, EPI_ISL_16258895, EPI_ISL_16260187, EPI_ISL_16274886, EPI_ISL_16280443, EPI_ISL_16288173, EPI_ISL_16290098, EPI_ISL_16290109, EPI_ISL_16290286, EPI_ISL_16294494, EPI_ISL_16294497, EPI_ISL_16295375, EPI_ISL_16295505, EPI_ISL_16295742, EPI_ISL_16295892, EPI_ISL_16295917, EPI_ISL_16295925, EPI_ISL_16296002, EPI_ISL_16296358, EPI_ISL_16296379, EPI_ISL_16296496, EPI_ISL_16302623, EPI_ISL_16305978, EPI_ISL_16306121, EPI_ISL_16307030, EPI_ISL_16307069, EPI_ISL_16317659, EPI_ISL_16317668, EPI_ISL_16331436, EPI_ISL_16334938, EPI_ISL_16336170, EPI_ISL_16338836, EPI_ISL_16341895, EPI_ISL_16351400, EPI_ISL_16351544, EPI_ISL_16351556
</details>

**Comment by ryhisner** [comment]
Ten of these were uploaded from Ireland yesterday, along with 12 others, then four more today, three of them from Italy. Total seems to be 120 now.

**Comment by FedeGueli** [comment]
179 as today with Spike_Y248D, -Spike_Y248del, NSP12_Y273H, -NSP13_Y421H.

big upload from Netherlands and Bonaire maybe @josetteshoenma is interested in

**Comment by FedeGueli** [comment]
206 as today. It doubled in just 5 days even its 8x doubling is 27 days so not especially fast. something to keep monitored as well

**Comment by FedeGueli** [comment]
336 as today and one of the fastest bq.1.1 in our chart @corneliusroemer although likely slower than XBB.1.5 , XBF and CH.1.1.1

**Comment by FedeGueli** [comment]
@ryhisner this sublineage has no insertion right? cause i m finding a S:248D (on covspectrum but Spike_Y248S on Gisaid) with Ins:S:247:AED circulating in Italy and i want to be sure it is not the same as this one.

**Comment by corneliusroemer** [comment]
Designated as BQ.1.1.45
