### ISSUE TITLE
XBF (S:F486P) with S:F490P and Orf1b:V1021F   - 30 sequences Australia, Denmark, Usa, France, New Zealand  

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1514]
I spotted yesterday this sublineage of XBF that now doubled to 4 sequences.
So i prudentially propose it being a first time we see S:486P + S:490P 

Gisaid query: **Spike_F486P,Spike_F490P,Nsp1_K120N**
finds these sequences : EPI_ISL_16315599, EPI_ISL_16315735, EPI_ISL_16360493,
EPI_ISL_16360514

Tree: Although Usher seems misplacing it in a weird BA.1/BA.2 recombinant branch, it is a XBF (@AngieHinrichs could you check this please?)
<img width="1155" alt="Schermata 2023-01-03 alle 23 34 06" src="https://user-images.githubusercontent.com/87669813/210452476-8201925a-c7c8-4f01-9035-ad9809330866.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c231_4ac4c0.json?label=id:node_5341230

Defining mutations:
**XBF + Orf1b:V1021F (G7936C) + G16528T, S:F490P ( T23030C )**

**Comment by AngieHinrichs** [comment]
> Usher seems misplacing it in a weird BA.1/BA.2 recombinant branch

Ugh, another one to fix, thanks for flagging it @FedeGueli!

**Comment by FedeGueli** [comment]
Another seqeucne of this one came today from Denmark, it is a 2023 sample.

**Comment by FedeGueli** [comment]
6th sequence came from Australia today

**Comment by FedeGueli** [comment]
one more seq from Australia

**Comment by FedeGueli** [comment]
It seems the same combo of mutations 486-490>P was obtained by a XBB.1.5 in Usa.

**Comment by FedeGueli** [comment]
8 as today with Spike_F486P,Spike_F490P,Nsp1_K120N

**Comment by FedeGueli** [comment]
One more sequecne from west australia

**Comment by FedeGueli** [comment]
It reached 13 sequences, slow spread but still could be something in my view. i ll keep open for a while

**Comment by FedeGueli** [comment]
Now at 15 with two new samples from Usa: Utah and Florida:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f4de_b94350.json?c=userOrOld&label=id:node_8170783
<img width="1161" alt="Schermata 2023-02-02 alle 11 48 31" src="https://user-images.githubusercontent.com/87669813/216304580-652d4138-1228-4aaf-b4ef-b767b3a77214.png">

@AngieHinrichs i dont understand well why a double reversion is shown in the files uploaded from Gisaid why it is notnshown in the ones annotated by Usher.

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs i dont understand well why a double reversion is shown in the files uploaded from Gisaid why it is not shown in the ones annotated by Usher.

It's because of branch-specific masking done in the UShER tree daily build, after sequences are placed in the tree -- but that type of masking is not applied to sequences placed by the web interface because it would at least double the time that the web interface takes.

XBF is placed on the BM.1.1.1 branch which is part of the BA.2.75 branch, on which many many sites are masked because there were so many false reversions in the BA.2.75 sequences.  That gives a cleaner tree, at the cost of making recombinants appear to have some mutations according to the tree where they really should in fact show reversions (as the unmasked uploaded sequences do).

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs !

**Comment by FedeGueli** [comment]
3 new sequences uploaded from Australia and one from france (new country)

**Comment by FedeGueli** [comment]
S:V433I one sequence, it looks ugly for binding, but i put here the same

**Comment by FedeGueli** [comment]
19 seqs as today last one from USA

**Comment by FedeGueli** [comment]
20 seqs as today. slowly growing.

**Comment by FedeGueli** [comment]
24 sequences as today 4 new from West Australia, little signs it is increasing its circulation also by scientists on the lab ground

**Comment by FedeGueli** [comment]
Newly found in NZL

**Comment by FedeGueli** [comment]
27 seqs as today. it seems slow. waiting a bit before closing it.

**Comment by FedeGueli** [comment]
30 seqs as today last 3 from West Australia

**Comment by FedeGueli** [comment]
Just 31 samples it means one only in one week. closing this.

**Comment by FedeGueli** [comment]
Now 34 seqs
