### ISSUE TITLE
Big sublineage of BN.1.3 defined by Orf7b:C41W emerged in Vietnam977sequences as 2023/02/02

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1516]
I randomly met this sublineage while checking airport  surveillance it caught my attention cause its main mutation Orf7b:C41W (T27878G) sounded new to me and collection dates were all quite recent.
Digging a bit more i found that this sublineage of BN.1.3 is circulating with a significant prevalence in South Korea hanging around 2% of samples in the last few weeks while growing to 0,5% of cases in Japan.

So i decided to check growth advantages in SOuth Korea and it has a slight but solid advantage [versus parental BN.1.3 ](https://cov-spectrum.org/explore/South%20Korea/AllSamples/Past3M/variants?nextcladePangoLineage=BN.1.3*&aaMutations1=Orf7b%3AC41W&nextcladePangoLineage1=BN.1.3*&analysisMode=CompareToBaseline&)
<img width="923" alt="Schermata 2023-01-04 alle 22 21 26" src="https://user-images.githubusercontent.com/87669813/210652178-944b28b0-e5ec-4dc9-846d-401c51764242.png">

It seems ahead of BQ.1 clan while just ahead the leading group with  CH.1.1, even if it is still far from XBB.1.5.

I would like to highlight that a sublineage of this one gained a further ORf7b:W41L mutation with G27877T (15 sequences) ( @thomaspeacock could you check if i got it right please). Considering those sequences too the advantage seems slighty bigger

**Defining mutations:**
BN.1.3 + ORF1a:M3627I (G11146T) > ORF1a:H110Y (C593T) > C7390A > Orf7b:C41W (T27878G )

**Usher Tree:** i would like to highlight the big saltation branch on the top of the USher tree currently circulating in Japan and internationally and the little cluster with S:E471Q in the bottom part of the tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2143_5e6d10.json?c=country&label=id:node_7869439
<img width="1164" alt="Schermata 2023-01-04 alle 22 30 32" src="https://user-images.githubusercontent.com/87669813/210653565-1c1a4890-8ffa-41f2-b77a-d7e6e0f5f91d.png">

Gisaid query: NS7b_C41W,E_T11A,NS3_T229I
finds  455 Sequences :
<Details>
<summary>Expand for EPI_ISLs</summary>
EPI_ISL_15280956, EPI_ISL_15341181, EPI_ISL_15609500,
EPI_ISL_15609618, EPI_ISL_15609627, EPI_ISL_15641407,
EPI_ISL_15653379, EPI_ISL_15671987, EPI_ISL_15672526,
EPI_ISL_15694051, EPI_ISL_15695703, EPI_ISL_15695743,
EPI_ISL_15712256, EPI_ISL_15732187, EPI_ISL_15732258,
EPI_ISL_15732878, EPI_ISL_15733027, EPI_ISL_15736596,
EPI_ISL_15755897, EPI_ISL_15756084, EPI_ISL_15756220,
EPI_ISL_15757122, EPI_ISL_15757130, EPI_ISL_15757137,
EPI_ISL_15783588, EPI_ISL_15783784, EPI_ISL_15784352,
EPI_ISL_15794137, EPI_ISL_15794722, EPI_ISL_15804436,
EPI_ISL_15811198-15811199, EPI_ISL_15811297, EPI_ISL_15811301,
EPI_ISL_15820479, EPI_ISL_15831920, EPI_ISL_15838570,
EPI_ISL_15838573, EPI_ISL_15842274, EPI_ISL_15848957,
EPI_ISL_15849081, EPI_ISL_15850241, EPI_ISL_15850249,
EPI_ISL_15875604, EPI_ISL_15887437, EPI_ISL_15887456,
EPI_ISL_15896856, EPI_ISL_15896972, EPI_ISL_15897014,
EPI_ISL_15905785, EPI_ISL_15905920, EPI_ISL_15906229,
EPI_ISL_15906345, EPI_ISL_15906718, EPI_ISL_15907094,
EPI_ISL_15907356, EPI_ISL_15907753, EPI_ISL_15907982,
EPI_ISL_15910734, EPI_ISL_15916557, EPI_ISL_15917361,
EPI_ISL_15923945, EPI_ISL_15938456, EPI_ISL_15943762,
EPI_ISL_15944351, EPI_ISL_15944372, EPI_ISL_15944966,
EPI_ISL_15946986, EPI_ISL_15950714, EPI_ISL_15957977,
EPI_ISL_15961223, EPI_ISL_15978568, EPI_ISL_15979026,
EPI_ISL_15979247, EPI_ISL_15979270, EPI_ISL_15979469,
EPI_ISL_15979472, EPI_ISL_15979493, EPI_ISL_15979638,
EPI_ISL_15979692, EPI_ISL_15979967, EPI_ISL_15980180,
EPI_ISL_15981420, EPI_ISL_15981556-15981557, EPI_ISL_15981660,
EPI_ISL_15987669, EPI_ISL_15987677, EPI_ISL_15997256,
EPI_ISL_15997337, EPI_ISL_15999784, EPI_ISL_15999963,
EPI_ISL_16004094, EPI_ISL_16004167, EPI_ISL_16004234,
EPI_ISL_16004466, EPI_ISL_16010751, EPI_ISL_16011832,
EPI_ISL_16026624, EPI_ISL_16026626, EPI_ISL_16035681-16035682,
EPI_ISL_16036315, EPI_ISL_16036943, EPI_ISL_16040533,
EPI_ISL_16048728, EPI_ISL_16051039, EPI_ISL_16051737,
EPI_ISL_16051833, EPI_ISL_16058743, EPI_ISL_16058908,
EPI_ISL_16059055, EPI_ISL_16060198, EPI_ISL_16060276,
EPI_ISL_16060522, EPI_ISL_16060639, EPI_ISL_16060762,
EPI_ISL_16067524, EPI_ISL_16069571, EPI_ISL_16073621,
EPI_ISL_16073623, EPI_ISL_16077651, EPI_ISL_16077750,
EPI_ISL_16077768, EPI_ISL_16077785, EPI_ISL_16077845,
EPI_ISL_16078921, EPI_ISL_16086653, EPI_ISL_16091723,
EPI_ISL_16091955, EPI_ISL_16092606, EPI_ISL_16093839,
EPI_ISL_16096196, EPI_ISL_16099089, EPI_ISL_16105767,
EPI_ISL_16107792, EPI_ISL_16109839, EPI_ISL_16109932,
EPI_ISL_16110011, EPI_ISL_16111044, EPI_ISL_16112219,
EPI_ISL_16112822, EPI_ISL_16114521, EPI_ISL_16115590,
EPI_ISL_16115713, EPI_ISL_16120239, EPI_ISL_16120430,
EPI_ISL_16120697, EPI_ISL_16125129, EPI_ISL_16125177,
EPI_ISL_16125267, EPI_ISL_16128398, EPI_ISL_16128861,
EPI_ISL_16129606, EPI_ISL_16129612, EPI_ISL_16130481,
EPI_ISL_16131284, EPI_ISL_16132657, EPI_ISL_16133910,
EPI_ISL_16133933, EPI_ISL_16135111, EPI_ISL_16135153,
EPI_ISL_16135252, EPI_ISL_16135307, EPI_ISL_16135374,
EPI_ISL_16135413, EPI_ISL_16135502, EPI_ISL_16135634,
EPI_ISL_16135699, EPI_ISL_16135915, EPI_ISL_16135938,
EPI_ISL_16135969-16135970, EPI_ISL_16136052, EPI_ISL_16136136,
EPI_ISL_16136186, EPI_ISL_16136340, EPI_ISL_16136364,
EPI_ISL_16136380, EPI_ISL_16136385, EPI_ISL_16136415,
EPI_ISL_16136907, EPI_ISL_16137116, EPI_ISL_16137122,
EPI_ISL_16137170, EPI_ISL_16137232-16137239, EPI_ISL_16137285,
EPI_ISL_16137341, EPI_ISL_16137385, EPI_ISL_16137401,
EPI_ISL_16137403, EPI_ISL_16138779, EPI_ISL_16141406,
EPI_ISL_16143511, EPI_ISL_16144052, EPI_ISL_16144120,
EPI_ISL_16151787, EPI_ISL_16153376, EPI_ISL_16153523,
EPI_ISL_16158537-16158538, EPI_ISL_16161745, EPI_ISL_16161853,
EPI_ISL_16165348, EPI_ISL_16165767, EPI_ISL_16167531,
EPI_ISL_16169389, EPI_ISL_16173920, EPI_ISL_16173943,
EPI_ISL_16174192-16174193, EPI_ISL_16174392, EPI_ISL_16174737,
EPI_ISL_16175239, EPI_ISL_16180229, EPI_ISL_16186420,
EPI_ISL_16186725, EPI_ISL_16186792, EPI_ISL_16186972,
EPI_ISL_16187002, EPI_ISL_16187010, EPI_ISL_16187096,
EPI_ISL_16189318, EPI_ISL_16190550, EPI_ISL_16191270,
EPI_ISL_16191736, EPI_ISL_16192615, EPI_ISL_16192777,
EPI_ISL_16192782, EPI_ISL_16192831, EPI_ISL_16192840,
EPI_ISL_16192986, EPI_ISL_16193424, EPI_ISL_16194038,
EPI_ISL_16196484, EPI_ISL_16201160, EPI_ISL_16202003,
EPI_ISL_16206214, EPI_ISL_16209640, EPI_ISL_16210070,
EPI_ISL_16210745, EPI_ISL_16216251, EPI_ISL_16217368,
EPI_ISL_16217414, EPI_ISL_16217594, EPI_ISL_16220991,
EPI_ISL_16222658, EPI_ISL_16225868, EPI_ISL_16225875,
EPI_ISL_16225883, EPI_ISL_16229254, EPI_ISL_16234714,
EPI_ISL_16238369, EPI_ISL_16245772, EPI_ISL_16245903,
EPI_ISL_16245913, EPI_ISL_16246649, EPI_ISL_16246833,
EPI_ISL_16250577, EPI_ISL_16254458, EPI_ISL_16255347,
EPI_ISL_16255553, EPI_ISL_16256015, EPI_ISL_16256804,
EPI_ISL_16257458, EPI_ISL_16259454, EPI_ISL_16264666,
EPI_ISL_16264821, EPI_ISL_16265428, EPI_ISL_16265768,
EPI_ISL_16270893, EPI_ISL_16270953, EPI_ISL_16271226,
EPI_ISL_16271442, EPI_ISL_16271506, EPI_ISL_16272796,
EPI_ISL_16273338, EPI_ISL_16273357, EPI_ISL_16273613,
EPI_ISL_16273908, EPI_ISL_16273922, EPI_ISL_16274070,
EPI_ISL_16278531, EPI_ISL_16279286, EPI_ISL_16279297,
EPI_ISL_16279305, EPI_ISL_16279329, EPI_ISL_16279348,
EPI_ISL_16279384, EPI_ISL_16279840, EPI_ISL_16279926,
EPI_ISL_16280690, EPI_ISL_16284170, EPI_ISL_16284183,
EPI_ISL_16284429, EPI_ISL_16291136, EPI_ISL_16291409,
EPI_ISL_16291532, EPI_ISL_16291628, EPI_ISL_16291731,
EPI_ISL_16292222, EPI_ISL_16292303, EPI_ISL_16292367,
EPI_ISL_16292466, EPI_ISL_16292548, EPI_ISL_16292607,
EPI_ISL_16292632, EPI_ISL_16292639, EPI_ISL_16292858,
EPI_ISL_16294641, EPI_ISL_16298933, EPI_ISL_16299067,
EPI_ISL_16299085, EPI_ISL_16299236, EPI_ISL_16299254,
EPI_ISL_16301094, EPI_ISL_16301844, EPI_ISL_16301941,
EPI_ISL_16303190, EPI_ISL_16305383, EPI_ISL_16305415,
EPI_ISL_16307771, EPI_ISL_16308392, EPI_ISL_16311860,
EPI_ISL_16313345, EPI_ISL_16314029, EPI_ISL_16315608,
EPI_ISL_16319235, EPI_ISL_16319254, EPI_ISL_16320079,
EPI_ISL_16322030, EPI_ISL_16322041-16322042, EPI_ISL_16322296,
EPI_ISL_16322310-16322311, EPI_ISL_16323732-16323733, EPI_ISL_16323735,
EPI_ISL_16323739, EPI_ISL_16323921, EPI_ISL_16324973,
EPI_ISL_16329712, EPI_ISL_16329836, EPI_ISL_16330482,
EPI_ISL_16330500, EPI_ISL_16333508, EPI_ISL_16333879,
EPI_ISL_16333989, EPI_ISL_16336344, EPI_ISL_16336371,
EPI_ISL_16336453, EPI_ISL_16336470, EPI_ISL_16336518-16336519,
EPI_ISL_16336523, EPI_ISL_16336621, EPI_ISL_16336644,
EPI_ISL_16336689, EPI_ISL_16336772, EPI_ISL_16336812,
EPI_ISL_16337870, EPI_ISL_16337981, EPI_ISL_16338035-16338036,
EPI_ISL_16338045, EPI_ISL_16338095, EPI_ISL_16338198,
EPI_ISL_16338219, EPI_ISL_16338250, EPI_ISL_16339128,
EPI_ISL_16339162, EPI_ISL_16339200, EPI_ISL_16339279,
EPI_ISL_16339343, EPI_ISL_16339365-16339366, EPI_ISL_16339457,
EPI_ISL_16339481, EPI_ISL_16339589, EPI_ISL_16339618,
EPI_ISL_16339630, EPI_ISL_16339704, EPI_ISL_16339744,
EPI_ISL_16339924, EPI_ISL_16339950, EPI_ISL_16339961,
EPI_ISL_16340001, EPI_ISL_16340064, EPI_ISL_16340222,
EPI_ISL_16340262, EPI_ISL_16340269, EPI_ISL_16340297,
EPI_ISL_16340377, EPI_ISL_16340418, EPI_ISL_16340496,
EPI_ISL_16340605, EPI_ISL_16340611, EPI_ISL_16340729,
EPI_ISL_16340741, EPI_ISL_16340805, EPI_ISL_16340910,
EPI_ISL_16340994, EPI_ISL_16341100, EPI_ISL_16341144,
EPI_ISL_16341264, EPI_ISL_16341339, EPI_ISL_16341457,
EPI_ISL_16341485, EPI_ISL_16341488, EPI_ISL_16341510,
EPI_ISL_16341556, EPI_ISL_16341562, EPI_ISL_16342044,
EPI_ISL_16342072, EPI_ISL_16342366, EPI_ISL_16342375,
EPI_ISL_16342388, EPI_ISL_16342419, EPI_ISL_16342421,
EPI_ISL_16342428, EPI_ISL_16342726, EPI_ISL_16344676,
EPI_ISL_16347015, EPI_ISL_16347277, EPI_ISL_16352264,
EPI_ISL_16353616, EPI_ISL_16353868, EPI_ISL_16359036,
EPI_ISL_16359298, EPI_ISL_16359359, EPI_ISL_16359374,
EPI_ISL_16359582, EPI_ISL_16360513, EPI_ISL_16360528,
EPI_ISL_16360530, EPI_ISL_16360544, EPI_ISL_16364226,
EPI_ISL_16370161, EPI_ISL_16370659, EPI_ISL_16372196,
EPI_ISL_16374747, EPI_ISL_16376673, EPI_ISL_16377095,
EPI_ISL_16377108, EPI_ISL_16377955, EPI_ISL_16378818,
EPI_ISL_16379434
</details>

**Comment by HugonetX** [comment]
Covspectrum gives me 10 of those, recent, in France. 
With added :

N:S413R: Omicron frequent mutation seemingly doing nothing (Hossain A. et al, 2022, doi: 10.1016/j.micpath.2022.105699)

S:G142D: A very popular Delta infectivity, nab and remdevisir evading mutation (Lishuan Cheng et al, 2021, DOI:10.1101/2021.09.12.21263475)

**Comment by FedeGueli** [comment]
@HugonetX N:S413R is defining mutation in all BA.2/4/5 
S:142 usually is not real .

**Comment by FedeGueli** [comment]
521 as today (540 counting the sequences with orf7b:41 further mutated to L) with 67 viruses uploaded in the last thre days from Japan and South Korea but also Canada , Denmark, SIngapore , Usa.
i think its prevalence in SK will go up when last samples will be counted by covspectrum.
<img width="1076" alt="Schermata 2023-01-08 alle 00 30 14" src="https://user-images.githubusercontent.com/87669813/211174003-e83f262e-dfc4-4d09-a558-4c51e3b25497.png">
https://cov-spectrum.org/explore/South%20Korea/AllSamples/Past3M/variants?aaMutations=ORF1a%3AM3627I%2CORF1a%3AH110Y%2COrf7b%3AC41W&nextcladePangoLineage=BN.1.3&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

**Comment by FedeGueli** [comment]
684 sequences as today @thomasppeacock @InfrPopGen @corneliusroemer i think this one is pretty interesting one starting to spreading beyond South Korea and Japan to Singapore and Australia

**Comment by FedeGueli** [comment]
To be noticed further that two singaporean samples have travel history from Vietnam and Thailand and also samples have been taken of this lineage in ML Vietnam: exactly 19 samples out of 449 sequenced in Vietnam since October 1st.  suggesting a 5% prevalence in the last months there.

**Comment by FedeGueli** [comment]
805 sequences, it is spreading globally, England, Netherlands , Germany , Usa,  California and yesterday also one sequence from Shandong China. @thomasppeacock

**Comment by FedeGueli** [comment]
1030 sequences on Usher: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_15071_b89040.json?c=country&label=id:node_8110554
<img width="1165" alt="Schermata 2023-02-02 alle 11 41 41" src="https://user-images.githubusercontent.com/87669813/216303116-7d42f1d2-d366-4182-a44a-306ac5687761.png">

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BN.1.3.5 with 601 newly designated sequences, and 0 updated. Defining mutation T27878G (ORF7b:C41W) (following C7390A).

**Comment by FedeGueli** [comment]
Thx @InfrPopGen !
