### ISSUE TITLE
Highly Divergent BQ.1.1 Sublineage, 27 Private Nuc Mutations, Probable Molnupiravir Origin (14 seq, Jan 16)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1517]
### **Description**
**Sub-lineage of:** BQ.1.1
**Earliest sequence:** 2022-12-9, Australian Capital Territory — EPI_ISL_16359648
**Most recent sequence:** 2022-12-15, Australian Capital Territory —  EPI_ISL_16359724, EPI_ISL_16359730, EPI_ISL_16359737, EPI_ISL_16359739
**Countries circulating:** Australia
**Number of Sequences:** 11
**GISAID Query:** Spike_Q1113L, NSP1_G82S, NSP1_V116M, NSP2_K333E, NSP2_K355T
**CovSpectrum Query:** Nextcladepangolineage:BQ.1.1* & S:Q1113L & [4-of: G509A, G611A, A1802G, G1868A, C2881T, G3179A, G3287A]
**Substitutions on top of BQ.1.1:**
**Spike:** V90I, Q804R, Q1113L
**ORF1a:** G82S, V116M, K513E, A535T, E972K, V1008I, E2042K, S2406L
**ORF1b:** D144N, S1187N, M2220I
**Nucleotide:** G509A, G611A, A1802G, G1868A, C2881T, G3179A, G3287A, T5980C, G6389A, T6583C, T7120C, C7482T, G8785A, G13897A, C15633T, G17027A, T17955C, G20247A, G21830A, A23973G, A24900T, A25980G, C27573T, C27812T, G28202A, C29065T, C29119T
 
 
**USHER Tree**
The first two short branches contain mutations that are almost certainly shared between all sequences but which don’t show up for a few due to their lack of coverage in those areas, so I’ve included the mutations in both of those branches above.
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/Molnupiravir%20-%20BQ.1.1%20-%2011%20sequences%20-%20subtreeAuspice1_genome_8b78_60db30.json

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/33738461/210692001-bffae086-5d19-44a4-a959-4847fef3c52c.png">
 
**Evidence**
This cluster, like the BM.2 cluster before it, and like dozens up on dozens of other sequences and small clusters, bears the unmistakable imprint of molnupiravir (MOV), the ineffective, mutagenic antiviral from Merck that, for reasons unfathomable, remains in use in large parts of the world. I’ve gone over all of this before, so I’ll only give a very brief overview of the evidence. First, here is my analysis of the long branch shared by these 11 sequences.

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/33738461/210692253-8f3d3e9a-f2d4-488d-92e2-5033be8684b7.png">
 
**• Rapid accumulation of mutations in a short time period**—The closest related sequences on the Usher tree are from November 26-30, meaning the 27 nucleotide mutations of this sequence were acquired within a period of a few weeks or less. This is unheard of and can only be explained by the use of molnupiravir or some similar mutagenic drug.

**• Dominance of transition mutations**—26 of the 27 nucleotide mutations are transitions (C->T, T->C, A->G, G->A), the type of mutation MOV is known to induce. Furthermore, it is known that the two types of transitions most preferentially induced by MOV are C->T and G->A. Twelve of the 27 mutations (44.4%) consist of G->A mutations, which normally make up around 12% of all nucleotide mutations. C->T and G->A mutations together make up 70.4% of the mutations here compared to the typical rate of 45.9%. (Typical rates taken from Richard Neher’s database here:[https://github.com/neherlab/SC2_variant_rates/blob/master/data/mutation_rates.tsv](https://github.com/neherlab/SC2_variant_rates/blob/master/data/mutation_rates.tsv) )
 
**• Very low rate of non-synonymous nucleotide mutations**—In long branches created by chronic infections, we tend to see a very high percentage of non-synonymous nuc mutations—somewhere in the neighborhood of 80% is typical. Non-synonymous rates of 50% are never seen. The non-synonymous percentage of nuc mutations in this branch is 51.9%.
 
**• Widespread distribution of mutations + relatively low percentage of AA mutations in Spike**—Spike AA mutations make up 21.4% of the AA mutations here, about the same percentage that spike occupies in the SARS-CoV-2 genome—and exactly what would be expected if such mutations occurred randomly across the genome. In hypermutated, chronic-infection sequences, the percentage of AA mutations in spike is typically closer to 50%, with the bulk of those concentrated in the RBD or NTD. There are zero spike mutations in the RBD and only one in the NTD, in a site of little antigenic importance.
 
There is another probable molnupiravir cluster that’s recently appeared, but I don’t have time to write it up tonight. These clusters seem to be appearing at a more rapid clip of late, which is not a promising sign.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16359648, EPI_ISL_16359676, EPI_ISL_16359695, EPI_ISL_16359707-16359709, EPI_ISL_16359721, EPI_ISL_16359724, EPI_ISL_16359730, EPI_ISL_16359737, EPI_ISL_16359739
</details>

**Comment by FedeGueli** [comment]
Thanks for your efforts @ryhisner hope they will stay as they are: efforts and nothing more.

**Comment by hsnguyen** [comment]
Thanks guys, 
We also picked up this small cluster and notified ACT colleagues early this week via our national genomics sharing platform but your analysis in details is highly appreciated @ryhisner.
We'll monitor the cluster closely but as @FedeGueli said, expecting the saltation is deleterious and will die out ultimately like all other probable MOV long-branch clusters so far.

**Comment by LilKitt** [comment]
I have been following these clusters as well. Any ideas why it only seems to be occurring in Australia? The Panoramic study possibly?

**Comment by ryhisner** [comment]
@LilKitt, I'm not entirely sure, but I think it's because MOV has been used more in Australia than in other countries, particularly among the elderly. I don't have exact statistics to back that up, however. 

The other possibility, which I think is less likely, is the different immune landscape in Australia, due to their successfully avoiding large Covid outbreaks far longer than other countries. Perhaps affinity maturation and the broadening of antibody protection hasn't progressed as far in Australia as in other countries that have utilized MOV, enabling slightly deleterious mutations to persist for longer in circulation (and giving more chances for such deleterious mutations to be jettisoned through reversion or recombination). In that respect, it's interesting that the one non-Australian probable MOV cluster, consisting of 15 sequences, is in Japan, which also was far more successful at suppressing Covid circulation than most other countries. I'm going to try to write up a quick analysis of that cluster and post it later today. 

If the difference in immune landscape of Australia (and Japan) is contributing to these molnupiravir-variant clusters, then it's worrisome that China has recently approved molnupiravir for use. China obviously has the weakest Covid population immunity in the world, so MOV-variant clusters could perhaps persist there for much longer than elsewhere, enormously multiplying the chances that a MOV-induced variant that's both highly divergent from anything in existence and very fit could emerge.

**Comment by ryhisner** [comment]
Three more sequences from Australia from this lineage were uploaded today, bringing the total to 14 sequences. The first 11 sequences were collected between December 9-15. These most recent three were collected on December 17, 20, and 21. 
EPI_ISL_16523533, EPI_ISL_16523565, EPI_ISL_16523595

**Comment by hsnguyen** [comment]
Thanks @ryhisner 
It's 13 sequences we can pick up in this long branch cluster from our genomics sharing platform. I guess all the sequence data will be uploaded to GISAID by ACT jurisdiction at later time points.

**Comment by hsnguyen** [comment]
Apparently EPI_ISL_16359695 has >10% Ns so being excluded from our tree. So the number is now matching pefectly :) Will keep an eye on this. Cheers,

**Comment by corneliusroemer** [comment]
This has not grown since January so closing as stale
