### ISSUE TITLE
BA.5.1 sublineage defined by S:Q14H, S:V1264L, orf1a:T1444A, Orf1b:G662S and Orf9b:T95M - 235 sequences likely emerged in Reunion Island

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1522]
Looking at hospitalized patients in Japan i met this lineage and even it is in a descending trend it is quite interesting.

It arose likely in September in Reunion Island where it represents 0,5% of samples of last 4 months and from there has been exported to France Israel and from where to northern and eastern Europe: it reached 3% of little samples from Norway in Mid October and then in November from there reaching further far east Japan, and back to southern emisphere to New Zealand .

**Defining mutations**:
Ba.5.1 + > ORF1a:T1444A ( A4595G )> ORF1b:G662S (G15451A) >  S:V1264L (G25352T) > Orf9b:T95M (C28567T) > S:Q14H (G21604T)

Tree: 197 sequences
![Schermata 2023-01-05 alle 23 45 25](https://user-images.githubusercontent.com/87669813/210894491-d6bac752-ec50-43aa-b18c-6e95a55899eb.png)

**Gisaid query:** 
Spike_F486V,Spike_Q14H,NSP12_G671S,Spike_V1264L 
178 sequences

<Details>
<Summary> Sequences </Summary>
EPI_ISL_15180023, EPI_ISL_15207946, EPI_ISL_15231991,
EPI_ISL_15293122, EPI_ISL_15300038, EPI_ISL_15304890,
EPI_ISL_15327291, EPI_ISL_15347312, EPI_ISL_15353853,
EPI_ISL_15369222, EPI_ISL_15369228, EPI_ISL_15370557,
EPI_ISL_15391417, EPI_ISL_15406713, EPI_ISL_15407301,
EPI_ISL_15430834, EPI_ISL_15453108, EPI_ISL_15456214,
EPI_ISL_15472335, EPI_ISL_15495614, EPI_ISL_15514257,
EPI_ISL_15523348, EPI_ISL_15524592, EPI_ISL_15524923,
EPI_ISL_15527745, EPI_ISL_15542795, EPI_ISL_15543549,
EPI_ISL_15550632, EPI_ISL_15553043, EPI_ISL_15576777,
EPI_ISL_15581311, EPI_ISL_15618356, EPI_ISL_15628928,
EPI_ISL_15632622, EPI_ISL_15633761, EPI_ISL_15634405,
EPI_ISL_15634538, EPI_ISL_15634607, EPI_ISL_15634869,
EPI_ISL_15636079, EPI_ISL_15640638, EPI_ISL_15640683,
EPI_ISL_15645409, EPI_ISL_15645426, EPI_ISL_15664365,
EPI_ISL_15664440, EPI_ISL_15669948, EPI_ISL_15669971,
EPI_ISL_15672752, EPI_ISL_15681556, EPI_ISL_15682185,
EPI_ISL_15683218, EPI_ISL_15697632, EPI_ISL_15698054,
EPI_ISL_15716997, EPI_ISL_15717607, EPI_ISL_15717904,
EPI_ISL_15740831, EPI_ISL_15742430, EPI_ISL_15742441,
EPI_ISL_15742444, EPI_ISL_15742447, EPI_ISL_15743839,
EPI_ISL_15763986, EPI_ISL_15777153, EPI_ISL_15780278,
EPI_ISL_15785315, EPI_ISL_15787690, EPI_ISL_15788656,
EPI_ISL_15788665, EPI_ISL_15788686, EPI_ISL_15789259,
EPI_ISL_15789568, EPI_ISL_15796743, EPI_ISL_15798285,
EPI_ISL_15799670, EPI_ISL_15800279, EPI_ISL_15805089,
EPI_ISL_15805867, EPI_ISL_15807576, EPI_ISL_15810379,
EPI_ISL_15813424, EPI_ISL_15826154, EPI_ISL_15841094,
EPI_ISL_15848869, EPI_ISL_15853880, EPI_ISL_15859300,
EPI_ISL_15882478, EPI_ISL_15887392, EPI_ISL_15892626,
EPI_ISL_15895241, EPI_ISL_15898550, EPI_ISL_15898606,
EPI_ISL_15900025, EPI_ISL_15900950, EPI_ISL_15900953,
EPI_ISL_15901010, EPI_ISL_15904679, EPI_ISL_15904723,
EPI_ISL_15904877, EPI_ISL_15911206, EPI_ISL_15911224,
EPI_ISL_15911260, EPI_ISL_15911327, EPI_ISL_15937014,
EPI_ISL_15942683, EPI_ISL_15959174, EPI_ISL_15959182,
EPI_ISL_15960963, EPI_ISL_15964507, EPI_ISL_15972389,
EPI_ISL_15972391, EPI_ISL_15986646, EPI_ISL_15987434,
EPI_ISL_15987492, EPI_ISL_15987551, EPI_ISL_15989372,
EPI_ISL_15990888, EPI_ISL_15997377, EPI_ISL_16005761,
EPI_ISL_16017216, EPI_ISL_16022084, EPI_ISL_16028219,
EPI_ISL_16029515, EPI_ISL_16029517, EPI_ISL_16040913,
EPI_ISL_16041147, EPI_ISL_16041150, EPI_ISL_16042501,
EPI_ISL_16042518, EPI_ISL_16042783, EPI_ISL_16042822,
EPI_ISL_16044987, EPI_ISL_16044993, EPI_ISL_16064376,
EPI_ISL_16073516, EPI_ISL_16099084, EPI_ISL_16100321,
EPI_ISL_16103303, EPI_ISL_16103306, EPI_ISL_16103340,
EPI_ISL_16103389, EPI_ISL_16103404, EPI_ISL_16107998,
EPI_ISL_16116590, EPI_ISL_16126772, EPI_ISL_16129032,
EPI_ISL_16129441, EPI_ISL_16142215, EPI_ISL_16148648,
EPI_ISL_16150344, EPI_ISL_16158164, EPI_ISL_16158275,
EPI_ISL_16158303, EPI_ISL_16158305, EPI_ISL_16202142,
EPI_ISL_16210669, EPI_ISL_16210735, EPI_ISL_16218716,
EPI_ISL_16219596, EPI_ISL_16231412, EPI_ISL_16231490,
EPI_ISL_16233801, EPI_ISL_16235564, EPI_ISL_16235586,
EPI_ISL_16235784, EPI_ISL_16242823, EPI_ISL_16247438,
EPI_ISL_16247592, EPI_ISL_16254417, EPI_ISL_16264990,
EPI_ISL_16265184, EPI_ISL_16282255, EPI_ISL_16295379,
EPI_ISL_16299205, EPI_ISL_16299474, EPI_ISL_16329410,
EPI_ISL_16335498, EPI_ISL_16376602

</details>

This BA.5.1 lineage counts over 3000 sequences with orf1a:T1444A, going down to over 1000 for orf1b:G662S+S:V1264L and under 1000sequences for the Orf9:T95M

It has to be noticed that gaining S:Q14H it gained a 10% over the direct parental lineage with all mutations without S:Q14H:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1a%3AT1444A%2Corf1b%3AG662S&nucMutations=C28567T&nextcladePangoLineage=BA.5.1*&aaMutations1=S%3Aq14H&nucMutations1=c28567T&nextcladePangoLineage1=BA.5.1*&analysisMode=CompareToBaseline&

**Comment by HugonetX** [comment]
Oh. Yeah. Sorry about that. Our overseas territories are not big on vaccines. 

Orf1b:G662S was very popular in hospitals during the Delta wave.

**Comment by FedeGueli** [comment]
@HugonetX yes it was defining in Delta but brought in hospitals by Delta and not viceversa ( it is in all BA.2.75 lineages) , what it could do as a recent paper suggests , instead is a better tolerance to low temperatures , but still too few data to be sure of that.

**Comment by FedeGueli** [comment]
2 New samples coming from New Zealand and Japan

**Comment by FedeGueli** [comment]
198 sequences on Gisaid, Greece, Japan, Croatia, Netherlads countries of the last samples

**Comment by FedeGueli** [comment]
205 sequences on Gisaid , Austria Germany South Korea last samples uploaded

**Comment by FedeGueli** [comment]
210 sequences , very. slow closing it

**Comment by FedeGueli** [comment]
235 sequences and going on circulating in Japan. 
It is quite interesting to see that Japanese BA.5.1s are characterized by Orf9b mutations as i already showed [here](https://github.com/cov-lineages/pango-designation/issues/1677#issuecomment-1438668389).

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage EQ.1 with 8 newly designated sequences, and 213 updated. Defining mutation G21604T (S:Q14H) (following C28567T (Orf9b:T95M)). Mutations on top of BA.5.1.33 C28567T (Orf9b:T95M) and G21604T (S:Q14H).

**Comment by FedeGueli** [comment]
Thx @InfrPopGen
