### ISSUE TITLE
BQ.1.8.2 sublineage with S:S256L, S:Q613H, S:V1164I, ORF1a:I396V, ORF1b:T1511I (80 sequences as of 2022-03-20)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1523]
### Description
**Sublineage of**: BQ.1.8.2
**Earliest sequence**: 2022/11/10 (Ireland)
**Most recent sequence**: 2022/12/22 (UK-Scotland)
**Countries circulating**: Ireland (2/38), UK (36/38)
**Mutations on top of BQ.1.8.2**: G25052A (S:V1164I), then C22329T (S:S256L), G23401T (S:Q613H), A1451G (ORF1a:I396V), C17999T (ORF1b:T1511I)
**GISAID and Cov-spectrum query**: A1451G, C17999T, G23401T

In total, this proposed sublineage has a total of 5 amino changes at Spike relative to BQ.1 basal:

- S:Y144del (defining change of BQ.1.8), 
- S:A688V (defining change of BQ.1.8.2), 
- S:S256L, S:Q613H and S:V1164I

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/210938217-0a5c719d-fddd-4327-bfed-69ca70c5b84c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16514_777410.json?c=gt-nuc_1451&label=id:node_6359183

### Genomes:
EPI_ISL_15812059, EPI_ISL_16074239, EPI_ISL_16074295, EPI_ISL_16075133, EPI_ISL_16094643, EPI_ISL_16097965, EPI_ISL_16108464, EPI_ISL_16108466, EPI_ISL_16108468, EPI_ISL_16108530-16108531, EPI_ISL_16108565, EPI_ISL_16108574, EPI_ISL_16108627, EPI_ISL_16108645, EPI_ISL_16108654, EPI_ISL_16108724, EPI_ISL_16108731, EPI_ISL_16108738, EPI_ISL_16148676, EPI_ISL_16179755, EPI_ISL_16198746, EPI_ISL_16198769, EPI_ISL_16198974, EPI_ISL_16212929, EPI_ISL_16256315, EPI_ISL_16256371, EPI_ISL_16256380, EPI_ISL_16256545, EPI_ISL_16261075, EPI_ISL_16274110, EPI_ISL_16274317, EPI_ISL_16281111, EPI_ISL_16390784
 (only 34 of 38 sequences are on GISAID now)

**Comment by corneliusroemer** [comment]
The 2 extra S AA muts are interesting, but it seems to have disappeared recently, only 1 upload since December 26 - so I'd wait a bit more.

**Comment by c19850727** [comment]
41 sequences as of 2022-01-10.

**Comment by c19850727** [comment]
47 sequences as of 2022-01-14, newly found in Croatia.

**Comment by corneliusroemer** [comment]
64 now. It's 1164I by the way, capital i :)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage FF.1 with 65 newly designated sequences, and 0 updated. Defining mutation C22329T (S:S256L) (following A1451G (ORF1a:I396V), C17999T (ORF1b:T1511I), G23401T (S:Q613H)).
