### ISSUE TITLE
B.1.1.229 and B.1.1.230 are missing in lineage_notes.txt

### ISSUE THREAD

**Issue by PeterSlickers** [cov-lineages/pango-designation#1524]
B.1.1.229 and B.1.1.230 have several genomes assigned in lineages.csv, but they are not listed in lineage_notes.txt.

```
grep B.1.1.229 lineages.csv
  Germany/BE-ChVir8973/2020,B.1.1.229
  Italy/CAM-TIGEM-169/2020,B.1.1.229
  ...

grep B.1.1.230 lineages.csv
  USA/TX-HMH-MCoV-15413/2020,B.1.1.230
  USA/TX-HMH-MCoV-12990/2020,B.1.1.230
  ...

grep B.1.1.229 lineage_notes.txt

grep B.1.1.230 lineage_notes.txt

```
I also noted that the related URL are resulting empty pages.

- https://cov-lineages.org/lineage.html?lineage=B.1.1.229

- https://cov-lineages.org/lineage.html?lineage=B.1.1.230

**Comment by Mydtlwn** [comment]
Please use one issues to raise all errors about this file, when this issues is not closed

**Comment by InfrPopGen** [comment]
Thank you for spotting that, I have added missing entries for B.1.1.229 and B.1.1.230 to lineage_notes.txt
