### ISSUE TITLE
*B.1.36.17.1 in lineage_notes.txt

### ISSUE THREAD

**Issue by PeterSlickers** [cov-lineages/pango-designation#1525]
I guess that the first column in lineage_notes.txt if referring to lineages but not to aliases. However, I found one line referring to an alias.

```
grep '*B.1.36.17.1' lineage_notes.txt
*B.1.36.17.1    Withdrawn: Alias F.1 New Zealand lineage

```

**Comment by InfrPopGen** [comment]
Thank you for spotting that issue. I have deleted duplicate (and malformed) line for *F.1 in lineage_notes.txt
