### ISSUE TITLE
Sublineage of XBB.2 with Spike_H146K, Spike_N148T (10 sequences - UK, Netherlands)

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1529]
**Description**
Sub-lineage of: XBB.2 
Earliest sequence: 2022-11-20 — EPI_ISL_16295850, Netherlands
Countries circulating: UK (9), Netherlands (1)
Number of Sequences: 10
GISAID Query: Spike_H146K, Spike_N148T, C1063T, -C9866T
CovSpectrum Query: [6-of: C1063T, C6968T, C8958T, T9865A, T9868C, C14688T, C21998A, A22005C, C27247T]
Substitutions on top of XBB.2
Spike: H146K, N148T
ORF1a: L3201L (reversion)
Nucleotide C1063T,C6968T,C8958T,T9865A,T9868C,C14688T,C21998A,A22005C,C27247T

**USHER Tree**
[Link](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16312_88c7e0.json?c=gt-S_148&label=id:node_7745837)
![image](https://user-images.githubusercontent.com/94097102/211105214-d16ab551-e694-4e4b-915b-d9a64ab4c027.png)

**Evidence**
S:146K is convergent on XBB*, as seen in #1428 and #1503, and other unproposed branches of XBB. This mutation is very unique to XBB*. This is likely because on the reference genome, S:146K requires 2 NT mutations, but with XBB normally having S:H146Q, it just requires one more nucleotide mutation. 
S:N148T is less unique to XBB and only requires a single nucleotide mutation. However, it has appeared on multiple XBB branches, and around 16% of sequences with the mutation in the last 6 months are XBB*, despite XBB only making up around 1% of sequences in the last 6 months. 

Additionally, my proposed lineage is not the only XBB* with both of these spike mutations. EPI_ISL_16360605 is an XBB that independently acquired these mutations. 
I believe that this suggests that XBB may gain some advantage by further mutating this region of the NTD beyond the S:144del and S:H146Q it has already acquired. 

Interestingly, as seen in the USHER tree, my proposed lineage appears to have gained 5 nucleotide mutations in one step. This includes a reversion on ORF1a:3201. Notably, this was mutated in BA.2 and reverted in BA.5 (or never acquired in BA.5) 

**Note:** Some of the sequences don't have a read on S:253, so they are artifically lacking S:D253G. Additionally, there is an artifact that can incorrectly cause S:H146K and S:N148T to be read, but my query appears unaffected. 
Additionally, my query does not catch the independent XBB with S:146K, S:148T that I mentioned. 

**Genomes**
EPI_ISL_16285727, EPI_ISL_16236592, EPI_ISL_16213622, EPI_ISL_16198927, EPI_ISL_16236503, EPI_ISL_16213520, EPI_ISL_16236618, EPI_ISL_16213744, EPI_ISL_16295850

**Comment by corneliusroemer** [comment]
Since England sequences in a very bunched manner, it's best to wait for more sequences from a different lab (not LSPA) as right now we have effectively only ~1 cluster from UK and 1 sequence from Netherlands

**Comment by Sinickle** [comment]
It's been independently acquired a couple times, but doesn't seem to be granting growth advantage, and this particular proposed branch seems dead.
