### ISSUE TITLE
Possible new XBC.1.2.1 sublineage with S:F490S circulating in Denmark (18 sequences as 25-01-2023)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1533]
XBC.1.2.1 has been designated today by @corneliusroemer , it corresponds at a sublineage that was introduced successfully ( or emerged fastly after introduction) in Denmark defined by Orf1b:T132I.

Looking at its tree i notice a little cluster of 8 recent samples with S:490S and other AA mutations.
here i want to propose them:

**Tree:** 
<img width="1158" alt="Schermata 2023-01-07 alle 19 11 31" src="https://user-images.githubusercontent.com/87669813/211164673-142642d6-4170-44ef-acf8-3b6bec764761.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29530_9b51c0.json?label=id:node_8270810

**Defining mutations**: 
**XBC.1.2.1** > **ORF1a:S538P** (T1877C), **Orf1a:A1234V** (C3966T), A18861G,  **S:F490S** (T23031C) , C26882T

**Gisaid Query**: **NSP2_S358P,NSP3_A416V,Spike_F490S**

**Sequences:** 8 all from Denmark

EPI_ISL_16257116, EPI_ISL_16257474, EPI_ISL_16350275,
EPI_ISL_16350341, EPI_ISL_16408569, EPI_ISL_16409549,
EPI_ISL_16430699, EPI_ISL_16430845

**Comment by FedeGueli** [comment]
4 more sequences popped up of this one all from Denmark. @corneliusroemer @InfrPopGen @thomasppeacock this seems interesting.

**Comment by FedeGueli** [comment]
3 new uploads from Denmark today

**Comment by FedeGueli** [comment]
Closing for now it seems slow.

**Comment by corneliusroemer** [comment]
Keeping it open as it is intriguing, Denmark samples a lot so it may take a while before it shows up elsewhere.

**Comment by Outpfmance** [comment]
The cov-Spectrum shows that there are now 19 sequences

**Comment by FedeGueli** [comment]
still 18 sequences i think it is better to close this one. @corneliusroemer

**Comment by corneliusroemer** [comment]
Ok let's close then and reopen if it reappears!
