### ISSUE TITLE
BQ.1.1.22 Sublineage with ORF1b:E1871K circulating in Denmark, Ireland, USA and Others - 103 Sequences

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#1534]
BQ.1.1.22 Sublineage with Orf1ab:E6272K

GISAID query: Spike_Y144del, NSP14_E347K, NSP12_Y273H, Spike_K444, Spike_N460K

Nextstrain:
![image](https://user-images.githubusercontent.com/98380390/211182306-c017d718-0de4-4764-8e7d-6ee7b454e7d8.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26f0f_a56740.json?c=gt-ORF1ab_6272&f_userOrOld=uploaded%20sample&label=id:node_6321571

Recent uptick in Ireland 
![image](https://user-images.githubusercontent.com/98380390/211182381-3fce737b-66bc-4212-87bb-6295f9150bf8.png)

Will be proposing the other cluster BQ.1.1.22 with ORF1b:H1087Y if I notice a similar uptick.

**Comment by FedeGueli** [comment]
ORF1b:H1087Y is very homoplasic i m finding it in several different lineages.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it has been showing relative growth disadvantages over the past two months in UK, Ireland, Europe; this can be closed for now. Please re-propose or request re-opening should this trend reverse markedly in the future.
