### ISSUE TITLE
XBB.2  with S:F486P,S:P521S - 11 sequences USA, India as 25-01-23

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1535]
I have found another XBB.2 which gained S:F486P, it is just two sequences but worth monitoring it also cause it has another spike mutation S:P521S plus other AA mutations and notablySequen the reversion of Orf1b:959P to S , that was the old defining mutation inherited from BA.2.10*

Defining mutations:
**XBB.2** > **ORF7a:A13V** (C27431T) > **Orf1b:S959S** (C16342T) **REVERSION** > A3754G, C4234T > **Orf1a:G2091A** (G6536A), **S:F486P** (T23018C), **S:P519S** (C23123T), G29706T

Tree:
<img width="1146" alt="Schermata 2023-01-08 alle 09 50 54" src="https://user-images.githubusercontent.com/87669813/211187926-f708bf9d-6a0b-4c74-a645-1eb4a11d851c.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_5c25_a812c0.json?c=userOrOld&label=id:node_7759358

**Gisaid** : NS7a_A13V,Spike_D253G,Spike_F486P,Spike_P521S 
**Sequences**: EPI_ISL_16382405, EPI_ISL_16429057

**_EDITED_**
Interestingly there is an indian sequence (EPI_ISL_16392126) with the same reversion orf1b:S959S ,same orf7b:A13V and S:P521S but without S:F486P.
So this points that likely S:F486P emerged there during undersampled circulation of this sublineage:
<img width="1144" alt="Schermata 2023-01-08 alle 10 07 39" src="https://user-images.githubusercontent.com/87669813/211188411-afa4711c-7825-4291-ac49-b03454c69645.png">

**Comment by FedeGueli** [comment]
two new sequences uploaded from India, KA today clustering perfectly with the two american ones:

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_bd4_86610.json?c=userOrOld&label=id:node_7780277
<img width="1143" alt="Schermata 2023-01-12 alle 23 17 16" src="https://user-images.githubusercontent.com/87669813/212192967-75af6c03-d07e-474c-8851-68c46560493b.png">


maybe @karyakarte is interested in.

@corneliusroemer @thomasppeacock @InfrPopGen  after being sequenced in India i suggest prudentially to designate this also it has another S1 mutation and an Orf7a mutation which could be interesting to further investigate.

**Comment by FedeGueli** [comment]
8 sequences as today all the 4 new ones are from Karnataka. 
i would highlight as possible concern of this lineage cause it represents 6 out of 58 samples collected in Karnataka after 15th of December representing a potential 10% of sequences of that region and 2% of entire India in the same period.
cc @thomasppeacock @InfrPopGen @corneliusroemer @AngieHinrichs  and cc @karyakarte 
I think a rapid designation could help.

**Comment by FedeGueli** [comment]
XBB.2 seems really prone to acquire S:F486P now a cluster of two from Peru'

**Comment by LuisBarcenaF** [comment]
@FedeGueli We´ll be alert to the mutation

**Comment by FedeGueli** [comment]
3 new sequences from Delaware . 
As today no sample of this sublineage  was collected in 2023.

**Comment by FedeGueli** [comment]
Designated XBB.2.3 from #1603

**Comment by oobb45729** [comment]
ORF1b:S959P is an AUC->ACC mutation, which is the most frequent context of the U->C mutations. S:S494P, M:I82T, and ORF9b:I5T are other notable AUC->ACC mutations.
![](https://camo.githubusercontent.com/1b03d9b4737987193565705b1b6858b4ad7d55d80c0f9324fe924e24dea4b0d9/68747470733a2f2f7777772e6d6470692e636f6d2f766972757365732f766972757365732d31332d30303339342f61727469636c655f6465706c6f792f68746d6c2f696d616765732f766972757365732d31332d30303339342d673030322e706e67)
