### ISSUE TITLE
Sub-lineage of CH.1.1.4 with S:D839N. 55 sequences (Austria, Germany, Denmark, Croatia)

### ISSUE THREAD

**Issue by BorisUitham** [cov-lineages/pango-designation#1536]
Description: Sub-lineage of CH.1.1.4 with S:D839N
Earliest sequence: 2022-11-14
Most recent sequence: 2023-01-12
Countries circulating: Austria (38 sequences): 34 Vorarlberg, 3 Tyrol, 1 Lower Austria. Denmark (1 sequence): 1 Midtjylland. Germany (2 sequences): 2 Baden-Württemberg
GISAID query: Spike_P681R, Spike_D839N, Spike_F486S

Genomes
EPI_ISL_15915165, EPI_ISL_15995866, EPI_ISL_16064877,
EPI_ISL_16064888, EPI_ISL_16064938, EPI_ISL_16164357,
EPI_ISL_16164369, EPI_ISL_16164466, EPI_ISL_16164533,
EPI_ISL_16164581, EPI_ISL_16164711, EPI_ISL_16243487,
EPI_ISL_16262625, EPI_ISL_16263657, EPI_ISL_16263679,
EPI_ISL_16263693, EPI_ISL_16263749, EPI_ISL_16263756,
EPI_ISL_16420466, EPI_ISL_16421634, EPI_ISL_16421638,
EPI_ISL_16421662, EPI_ISL_16421665, EPI_ISL_16421667,
EPI_ISL_16421678, EPI_ISL_16421688-16421689, EPI_ISL_16421698,
EPI_ISL_16421714, EPI_ISL_16421728, EPI_ISL_16421745,
EPI_ISL_16421752

Usher Tree
Only one sample is fully sequenced and able to be placed in a phylogenetic tree. This shows the relation to CH.1.1.4.
![ch 1 1 4 1](https://user-images.githubusercontent.com/119106095/211350192-2683813e-b46b-4861-b4fc-e27f0e1744a9.png)

Covspectrum query:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3Ad839n%2Cs%3Ap681r&nextcladePangoLineage=ch.1.1*&

Growth advantage:
The recently designated CH.1.1.4 (when excluding samples with d839n) seems to be at a growth disadvantage and has not spread much. However, when comparing CH.1.1.4 + D839N with a baseline of CH.1.1*, there is an advantage of 53% (22-83) over ch.1.1* in austria. In vorarlberg alone, this is 68% (31-104) and predicts 68% of CH.1.1* samples on 09-01 to be CH.1.1.4 + D839N. For comparison, CH.1.1.4 minus D839N has a calculated advantage over ch.1.1 of -12 (-23 - 0) in austria and -7 (-20 - 5) in vorarlberg.
Thus the growth advantage over CH.1.1*. When looking at growth advantage over current variant mix, this is 78% (46 - 111) in austria and 85% (51 - 119) in vorarlberg. This would predict a prevalence of 26.07% (10.98 - 41.17) in vorarlberg on 09-01-2023, although i'm not certain on how accurate this is.
Since “pure” CH.1.1.4 is not growing much anymore and yet this added mutation is, I would like to propose this as a further sublineage.

Sidenotes:
D839N is a rare mutation, only being found in 909 samples since start of pandemic. Interestingly, most of these were during delta where a p681r was present as there is now: 69.70% of d839n in the 909 samples were with p681r. However even during delta this combo was only max 0.02% of all samples. Could it be that 681r allows for a stable 839n?

According to the following source from 2021, 839N might reduce fusogenicity. Extrapolation to omicron background is unknown.
Barrett CT, Neal HE, Edmonds K, Moncman CL, Thompson R, Branttie JM, Boggs KB, Wu C-Y, Leung DW, Dutch RE (2021) Effect of clinical isolate or cleavage site mutations in the SARS-CoV-2 spike protein on protein stability, cleavage, and cell-cell fusion. J Biol Chem 297:100902

**Comment by BorisUitham** [comment]
Since last week, + 1 sequence from Vorarlberg, Austria and +1 from Midtjylland, Denmark. Curiously, the sequence from Denmark also has I844V, another very rare mutation (2236 sequences as of today) and in close proximity to 839N

**Comment by ryhisner** [comment]
I'm pretty sure these two CH.1.1 uploaded from Germany belong to this lineage, but a lot of labs in Germany seem unable to sequence S:681, so no mutation is registered there on either. EPI_ISL_16597614, EPI_ISL_16597640

**Comment by BorisUitham** [comment]
Thank you, nextclade also assigns them CH.1.1.4 so it does seem that way.

**Comment by BorisUitham** [comment]
![Screenshot_20230129-181101](https://user-images.githubusercontent.com/119106095/215343548-41645a05-338e-411a-b708-ea1724c6b305.png)
Yellow: CH.1.1.4 without 839n.
Green: CH.1.1.4 with 839n, without 210v
Blue: CH.1.1.4 with 839n AND 210V
Looks like the mutations keep drifting along, with the addition of 210v. Not clear yet if blue will actually win over green like green won over yellow

**Comment by Outpfmance** [comment]
- Now it's up to 51 sequences. It's time to update the title. @BorisUitham

**Comment by BorisUitham** [comment]
I count 55 on GISAID. Two more from croatia and germany also have s:844v

**Comment by Outpfmance** [comment]
The cov-Spectrum shows that there are now 51 sequences(Spike_P681R,Spike_D839N,Spike_F486S), maybe it updates a little slower than GISAID

**Comment by Outpfmance** [comment]
It now has 53 sequences according to the cov-spectrum

**Comment by Mydtlwn** [comment]
![Uploading Screenshot_20230216_202358_com.tencent.mtt.png…]()

**Comment by Mydtlwn** [comment]
![Uploading Screenshot_20230216_202358_com.tencent.mtt.png…]()

**Comment by Outpfmance** [comment]
56 sequences now

**Comment by Outpfmance** [comment]
From the current point of view, up to 96% of the newly added CH.1.1.4 samples in the recent month contain D839N. Maybe there should be a discussion on whether to include D839N in the definition mutation of CH.1.1.4 and whether to name CH.1.1.4.1   ——(CH.1.1.4+D839N) @ryhisner @corneliusroemer @BorisUitham

**Comment by Outpfmance** [comment]
58 sequences now @BorisUitham

**Comment by Outpfmance** [comment]
59 sequences now @BorisUitham Maybe this issue should be updated

**Comment by corneliusroemer** [comment]
CH.1.1.4 doesn't really go anywhere, still only ~100 sequences worldwide, and this sublineage isn't much different. Will close for now.
