### ISSUE TITLE
XBC.2 sublineage with S:K444T [19 seqs, Australia]

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1538]
**Description**
Sublineage of: XBC.2
Earliest sequence: 2022/11/02/ Australia/ Western Australia
Most recent sequence: 2022/12/22 / Australia / Western Australia
Countries circulating: Australia - Western, Victoria, Tasmania
Mutations on top of XBC.2:
Spike- K444T
ORF1a - V498A (reversion), G1307S
ORF8 - A15T
Nucleotides: C222T, C1627T, G4184A, C9541T, A22893C, G27936A, T1758C (reversion), T23086C (reversion)
GISAID query: spike_f486p,spike_k444t, spike_k97r
cov-spec query: s:486p, s:444t, s:97r

[**USHER Tree**](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38977_c836b0.json?f_userOrOld=uploaded%20sample)
![image](https://user-images.githubusercontent.com/94097102/211419520-8466f792-0eca-44a0-a885-6dbcec232784.png)

**Evidence**
Spike_K444T has appeared on highly successful lineages such as BQ.1 and CH.1.1. 
XBC has not acquired K444T and L452M on the same branch yet, but if these are both independently successful mutations, it's possible they show a way that XBC can gain further advantage in the future and possibly stay relevant. 

I think it's odd that this has reversions relative to XBC.2, which has reversions relative to XBC. I think this shows that we likely did not designate the true XBC ancestor, and that my proposed lineage is also not a true descendant of XBC.2, but rather is a sibling lineage to it. 
![image](https://user-images.githubusercontent.com/94097102/211420034-7773c6d2-473a-4cfe-a9fe-cee039c3a8e4.png)

**Genomes:** EPI_ISL_15871036, EPI_ISL_16048844, EPI_ISL_16360629, EPI_ISL_16315535, EPI_ISL_16074134, EPI_ISL_16133825, EPI_ISL_16134171

**Comment by FedeGueli** [comment]
I think we are at 12 samples now: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21b65_b256b0.json?c=userOrOld&label=id:node_8382490
![Schermata 2023-01-21 alle 00 42 53](https://user-images.githubusercontent.com/87669813/213824346-90111f8e-71fc-49c4-b3f4-ba0746b4c7c3.png)

This is worth to be designated.

**Comment by corneliusroemer** [comment]
This is still around - 16 sequences now, let's keep watching

**Comment by corneliusroemer** [comment]
It's still at 16 sequences, but it's really interesting. Just found it again when looking at potential Delta containing recombinants.

This must involve another recombination even of some sort, maybe a bit like BA.1/2/4/5. It's complex, also tricky because Philippino sequences often have dropouts, and Australia-WA has some artefacts as well.

If anyone wants to figure out what happened here, would be great. 

A few points from a bit of an investigation:
- 5584 and 25000 are either problematic sites in Philippino sequences or the Philippino sequences are ancestral and 5584G and/or 25000T mutated later
- It'd also be good to figure out what the XBC ancestral state was at 1437, 1758, 10029. One should plot the hypothetical donors and XBC.1/2 next to each other and see what it shows

This recombinant shows some traits of XBC.2 but has 1758 like XBC.1. The explanation is possibly not so complicated as long as one figures out what are artefacts and what isn't.

**Comment by FedeGueli** [comment]
@corneliusroemer really messy thing it is harder to disentangle what could be artifact and what could be real,

 i would like to highlight that this proposed lineage has C1627T and then a reversion =orf1a:V498A =(T1758C)
and then it has G4184A =(orf1a:G1307S) that is present in 668K sequences of BA.5.2, this points to a possible recombiantion event XBC/BA.5.2 for this proposed lineage

<img width="404" alt="Schermata 2023-02-13 alle 00 19 47" src="https://user-images.githubusercontent.com/87669813/218343346-57e206b7-0d14-497c-a110-f961d1fdbe7d.png">

<img width="823" alt="Schermata 2023-02-13 alle 00 19 14" src="https://user-images.githubusercontent.com/87669813/218343313-371695e2-c757-4930-b715-68beee5b6a7d.png">

<img width="1399" alt="Schermata 2023-02-13 alle 00 24 25" src="https://user-images.githubusercontent.com/87669813/218343550-1970d5ff-4a39-4378-9c96-102dd1164135.png">

**Comment by Sinickle** [comment]
@FedeGueli that could be it, from what I can tell! 

I also found [these sequences](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C1627T%2CG4184A&nextcladePangoLineage=xbc&) which are XBC with the same two mutations you mentioned. They don't seem to be ancestral to my proposed lineage though, and they also seem to carry an additional nucleotide mutation that could be from BA.5.2 -- C5575T

**Comment by Sinickle** [comment]
I don't think BF.7.16 having C1758T is related, unless I'm misunderstanding your point? The proposed lineage has T1758C, which is [a reversion from how XBC.2 normally is. 
](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=1758t&nextcladePangoLineage=bf.7*&nextcladePangoLineage1=xbc.2&aaMutations2=s%3A444t%2Cs%3A486p%2Cs%3A97r&analysisMode=CompareEquals&)

**Comment by corneliusroemer** [comment]
Designated as XBC.2.1 - too unclear whether this is a recombinant and if so of which lineages. So for simplicity this is XBC.2.1 - also makes it easier to keep track of than if this was a recombinant.
