### ISSUE TITLE
CH.1.1 sublineage with ORF3a:P104S, C12781T, T17112C, and C193T first detected in Denmark (135 good and 141 total seqs as of 2023-01-12; Scandinavia, UK, Slovenia)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1539]
There may be a CH.1.1 sublineage with ORF3a:P104S (C25702T) following C193T, C12781T, and T17112C first detected in Hovedstaden, Denmark.

As of 2023-01-09, Cov-Spectrum reports 115 good-quality (121 total) CH.1.1+ORF3a:104S+12781T+17112C+193T sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ACH.1.1+%26+ORF3a%3AP104S+%26+C12781T+%26+T17112C+%26+C193T&nextcladeQcOverallScoreTo=29&

Considering the past 2 months of data, CoV-Spectrum estimated growth is 26% (confidence interval 9 to 43%) relative to parental lineage CH.1.1 in Denmark:
![Growth_CH 1 1+ORF3a_104S+12781T+17112C+193T_vs_CH 1 1_Denmark](https://user-images.githubusercontent.com/88959107/211421342-f1a32fff-e1ae-4372-979b-35419023c24d.png)
Source: https://cov-spectrum.org/explore/Denmark/AllSamples/Past2M/variants?variantQuery=nextcladePangoLineage%3ACH.1.1&variantQuery1=nextcladePangoLineage%3ACH.1.1+%26+ORF3a%3AP104S+%26+C12781T+%26+T17112C+%26+C193T&analysisMode=CompareToBaseline&

Considering the past 2 months of data, CoV-Spectrum estimated growth is 29% (confidence interval 12 to 45%) relative to S:F486P baseline in Denmark:
![Growth_CH 1 1+ORF3a_104S+12781T+17112C+193T_vs_S_F486P_Denmark](https://user-images.githubusercontent.com/88959107/211421362-d72a758d-f758-4db4-a3c4-eda43895a1b5.png)
Source: https://cov-spectrum.org/explore/Denmark/AllSamples/Past2M/variants?variantQuery=nextcladePangoLineage%3ACH.1.1&variantQuery1=nextcladePangoLineage%3ACH.1.1+%26+ORF3a%3AP104S+%26+C12781T+%26+T17112C+%26+C193T&analysisMode=CompareToBaseline&

As of 2023-01-09, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_CH 1 1+ORF3a_104S+12781T+17112C+193T_vs_CH 1 1](https://user-images.githubusercontent.com/88959107/211421396-da386526-aa30-493c-8608-78cb68cfc286.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/01/subtreeAuspice1_genome_CoV-Spectrum_CH.1.1%2BORF3a_104S%2B12781T%2B17112C%2B193T.json?c=gt-ORF3a_104&label=id%3Anode_7949994

GISAID query: Nucleotide: C25702T, C12781T, T17112C, C193T

First GISAID sequence: Hovedstaden, Denmark 2022-11-09

First GenBank sequence: England, United Kingdom 2022-11-12 

Most Recent GenBank sequence: England, United Kingdom 2022-12-21

Most Recent GISAID sequence: Sjaelland, Denmark and Syddanmark, Denmark 2023-01-01

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-CH.1.1+ORF3a_104S+12781T+17112C+193T.zip](https://github.com/cov-lineages/pango-designation/files/10377400/Support-CH.1.1%2BORF3a_104S%2B12781T%2B17112C%2B193T.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-CH.1.1+ORF3a_104S.txt](https://github.com/cov-lineages/pango-designation/files/10377399/gisaid-epi-isl-CH.1.1%2BORF3a_104S.txt)

The closest Outbreak.info link for this potential lineage (nucleotide mutations are not supported) is https://outbreak.info/situation-reports?pango=CH.1.1&muts=ORF3a%3AP104S.

Edit: Clarify that the GISAID query is a nucleotide query.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage CH.1.1.5 with 82 newly designated sequences, and 0 updated. Defining mutation C25702T (ORF3a:P104S) (following C12781T, T17112C).
