### ISSUE TITLE
BQ.1.1.2 sublineage with S:E1144Q and T10003C first detected in England, United Kingdom (128 good and 141 total seqs as of 2023-01-12; UK, Ireland, Denmark, Italy, Bonaire)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1540]
There may be a BQ.1.1.2 sublineage with S:E1144Q (G24992C), T10003C first detected in England, United Kingdom.

As of 2023-01-09, Cov-Spectrum reports 104 good-quality (113 total) BQ.1.1.2+S:1144Q+10003C sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3A1144Q&nucMutations=10003C&nextcladePangoLineage=BQ.1.1.2&nextcladeQcOverallScoreTo=29&

Considering the past 2 months of data, CoV-Spectrum estimated growth is 75% (confidence interval 44 to 106%) relative to parental lineage BQ.1.1.2 in the United Kingdom:
![Growth-BQ 1 1 2+S_1144Q+10003C_vs_BQ 1 1 2_UK](https://user-images.githubusercontent.com/88959107/211474166-915a829c-8ab1-4216-89f3-dcd3a55782b6.png)
Source: https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past2M/variants?nextcladePangoLineage=BQ.1.1.2&aaMutations1=S%3A1144Q&nucMutations1=10003C&nextcladePangoLineage1=BQ.1.1.2&analysisMode=CompareToBaseline&

Considering the past 2 months of data, CoV-Spectrum estimated growth is near the S:F486P baseline at 10% (confidence interval -9 to 29%) relative to S:F486P baseline in the United Kingdom:
![Growth-BQ 1 1 2+S_1144Q+10003C_vs_S_F486P_UK](https://user-images.githubusercontent.com/88959107/211474230-8c7e9673-a464-405d-b54a-7574395cf32f.png)
Source: https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past2M/variants?aaMutations=S%3AF486P&aaMutations1=S%3A1144Q&nucMutations1=10003C&nextcladePangoLineage1=BQ.1.1.2&analysisMode=CompareToBaseline&

As of 2023-01-09, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_BQ 1 1 2+S_1144Q+10003C](https://user-images.githubusercontent.com/88959107/211474275-71cc9e1c-bd57-4647-b5ba-675b4e1d0dca.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/01/subtreeAuspice1_genome_Cov-Spectrum_BQ.1.1.2%2BS_1144Q%2B10003C.json?c=gt-S_1144&label=id%3Anode_6372127

GISAID query: Nucleotide G27430A, A22320G, G24992C, T10003C

First GISAID sequence: England, United Kingdom 2022-11-19

First GenBank sequence: England, United Kingdom 2022-11-28 

Most Recent GenBank sequence: England, United Kingdom 2022-12-28

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at [Support-BQ.1.1.1+S_1144Q+10003C.zip](https://github.com/cov-lineages/pango-designation/files/10379416/Support-BQ.1.1.1%2BS_1144Q%2B10003C.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-BQ.1.1.2+S_1144Q+10003C.txt](https://github.com/cov-lineages/pango-designation/files/10379418/gisaid-epi-isl-BQ.1.1.2%2BS_1144Q%2B10003C.txt)

The closest Outbreak.info link for this potential lineage (nucleotide mutations are not supported) is https://outbreak.info/situation-reports?pango=BQ.1.1.2&muts=S%3AE1144Q.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage DU.1 with 56 newly designated sequences, and 0 updated. Defining mutation G24992C (S:E1144Q) (following T10003C).

**Comment by FedeGueli** [comment]
@alurqu great early catch of this one. It seems really one of the fastest of the bunch. 

<img width="1272" alt="Schermata 2023-01-24 alle 00 30 25" src="https://user-images.githubusercontent.com/87669813/214175577-54b4fb30-94fe-41f2-9eca-bec770a34c4d.png">
