### ISSUE TITLE
Another BA.2.75*/BQ.1* recombinant with RBD breakpoint (7 sequences as of 2023-02-23)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1543]
This is yet another BA.2.75*/BQ.1* with a similar recombination pattern to #1393 , #1425 and #1444 .

Interestingly, it has a combination of K444T+G446S+L452R+N460K (T22942A) at the RBM, but my preliminary analysis based on (lack of) defining nuc mutations has ruled out CH.1* or BR.4 as the potential donor for K444T, or CW.1 for G446S.
![image](https://user-images.githubusercontent.com/86835836/211692069-eb57ea46-3a1a-44e5-9f29-dbd25079018a.png)

Therefore I am to propose this cluster of recombinant with only 5 sequences, as it may indicate either an undesignated BA.2.75* with K444T, or an undesignated BQ.1* with G446S, as its donor; or else, this K444T/G446S change might have been picked up after the recombination event. Either way, I think it is worth monitoring from an early stage.

### Description
**Recombinant between**: BA.2.75* and BQ.1* (with S:R346T)
**Earliest sequence**: 2022/11/21 (US-CA)
**Most recent sequence**: 2022/12/26 (Singapore)
**Countries circulating**: Singapore ex-Vietnam (1/5), Singapore local case (2/5), Germany (1/5), US-CA (1/5)
**Mutation profile** (private mutations are in yellow color):
![image](https://user-images.githubusercontent.com/86835836/211692345-a1791bc2-bf25-4f3c-a13e-46c2fde979f0.png)
(BTW @AngieHinrichs USHER somehow thinks there is an E:T11A, but I am pretty sure there isn't...could you please take a look?)

**Private mutations**: A513G, T851C, C7948T, C8950T, C14724T, C25624T
**GISAID and Cov-spectrum query**: A513G, T851C, C25624T

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/211692718-19493eec-a8f9-4f2a-9a89-faa68bdf4377.png)

Genomes:
EPI_ISL_16153010, EPI_ISL_16191795, EPI_ISL_16191877, EPI_ISL_16227981, EPI_ISL_16378698

**Comment by AngieHinrichs** [comment]
> (BTW @AngieHinrichs USHER somehow thinks there is an E:T11A, but I am pretty sure there isn't...could you please take a look?)

Yes -- the BA.2.75 sequences were so riddled with apparently false reversions that were messing up the tree, I decided to mask reversions of BA.2.75 mutations on that branch, at the cost of falsely retaining some BA.2.75 mutations for recombinants placed there.  The reversions masked in the BA.2.75 branch are in https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/utils/otto/sarscov2phylo/maskDelta.sh (search for `BA275Node`).  26275 is the masked position causing the false E:T11A.

**Comment by FedeGueli** [comment]
6th sequence again from Singapore

**Comment by c19850727** [comment]
7th sequence uploaded from Philippines.

**Comment by c19850727** [comment]
I'll close this issue as it's not growing for more than a month.
