### ISSUE TITLE
Potential XBC.1 sublineage (5+ AA subs including S:K444R)

### ISSUE THREAD

**Issue by emily-smith1** [cov-lineages/pango-designation#1544]
**Sub-lineage of:** XBC.1
**Earliest sequence:** 2022-12-21
**Most recent sequence:** 2022-12-26
**Countries circulating:** USA (California)
**Number of sequences:** 2
**GISAID Query:** Spike_N703I, Spike_P25S, Spike_L452M,Spike_K444R
**Substitutions on top of XBC.1:** ORF1a:Q96R,ORF1a:A516V,ORF1b:T1404M,S:K444R,ORF3a:S171L

**Genomes:** (Both are in NCBI but only one in GISAID so far)
USA/CA-CDC-LC0973723/2022
USA/CA-CDC-LC0974962/2022

**UShER link:** https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_b1af_e142d0.json?f_userOrOld=uploaded%20sample
<img width="468" alt="image" src="https://user-images.githubusercontent.com/84812104/211699193-56fc663f-e463-4fae-aad5-50aaf873a23e.png">

We need to wait for more sequences but I wanted to make sure this was being monitored.

**Comment by emily-smith1** [comment]
There haven't been any more uploaded to GISAID after more than 2 weeks. Might be ok to close.

**Comment by InfrPopGen** [comment]
Thank you for proposing this one. As there's still only two known sequences over two weeks later, this one can be closed for now. Please re-propose or request re-opening should this one reappear and grow significantly in the future.
