### ISSUE TITLE
Correction - Recombinants with duplicate references on alias_key.json

### ISSUE THREAD

**Issue by 3dgiordano** [cov-lineages/pango-designation#1545]
You'll be able to see the duplicate value fir each designation here.

**XAC** - BA.2* duplicated
https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.json#L131

**XAZ** - BA.2.5 duplicated
https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.json#L151

**XBC** - "BA.2*","B.1.617.2*" duplicated
https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.json#L154

**XBL** - XBB.1 duplicated
https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.json#L162

**Comment by silcn** [comment]
These refer to recombinants with multiple breakpoints, showing the order in which sections derived from each donor occur.

**Comment by 3dgiordano** [comment]
Hi @silcn 

I'm trying to understand what you're telling me, but I don't know if I'm the one who didn't understand or maybe you didn't get what I meant.
I understand the use of the asterisk, what I mention is not in reference to that usage.

I will try to explain one of the indicated examples

From lineage_note.txt

XBC	Recombinant lineage of BA.2 and B.1.617.2*, predominantly in Philippines, from pango-designation issue #1100

The text on lineage_note.txt for XBC is clear the reference to two possible lineages references.

in alias_keys.json the two lineages appear as duplicates.

"XBC": ["BA.2*","B.1.617.2*","BA.2*","B.1.617.2*"],

If the idea is to mention the breakpoints, it is not clear to me that these duplicates are for that reason.

**Comment by AnonymousUserUse** [comment]
I think it would be better to describe _in a similar way as in alias_key.json_ in lineage_note.txt,
e.g.
XBC Recombinant lineage of BA.2*, B.1.627.2*, BA.2*, and B.1.627.2*, predominantly in Philippines, from pango-designation issue https://github.com/cov-lineages/pango-designation/issues/1100

**Comment by silcn** [comment]
> in alias_keys.json the two lineages appear as duplicates.
> 
> "XBC": ["BA.2*","B.1.617.2*","BA.2*","B.1.617.2*"],
> 
> If the idea is to mention the breakpoints, it is not clear to me that these duplicates are for that reason.

@3dgiordano the duplicates clearly are for that reason: XBC is a recombinant of two lineages with three breakpoints in precisely the pattern indicated by that line. Perhaps a further explanation of the convention used in that file should be added somewhere.

**Comment by 3dgiordano** [comment]
Thanks @silcn for the clarification. 

Such a pattern is not easy to guess or visualize.
An explanation in some document might help.

If it's okay to you, I don't see a problem in closing this issue, since this issue is due to a misinterpretation of the format for recombinants.

**Comment by Mydtlwn** [comment]
XBC is a pedigree with three breakpoints, while XBL is a pedigree with two breakpoints, and * is a pedigree representing the family formed by this branch. It means a branch of this family.

**Comment by corneliusroemer** [comment]
It's exactly as @silcn explained
