### ISSUE TITLE
DN.1.1 Sublineage with S:Y453F, ORF1a:V721I, & ORF1a:N2752S [24 seq, Jan 22]

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1548]
### **Description**
**Sub-lineage of:** DN.1.1 (BA.5.3.1.1.1.1.1.1.5.1.1)
**Earliest sequence:** 2022-12-11, England — EPI_ISL_16281338
**Most recent sequences:** 2023-1-3 — England/PHEC-YY8AW3B/2023, England/PHEC-YY8AUHH/2023
**Countries circulating:** England (16)
**Number of Sequences:** 16
**GISAID Query:** Nucleotide Search: G2426A, A8520G, C8905T, A22920T
**CovSpectrum Query:** Nextcladepangolineage:DN.1.1* & S:Y453F
**Substitutions on top of DN.1.1:**
**Spike:** Y453F
**ORF1a:** V721I, N2752S
**Nucleotide:** G2426A, A8520G, C8905T, A22920T, T29446C
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/DN.1.1%20%2B%20Y453F%20-%20subtreeAuspice1_genome_19188_c5ee0.json
 
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/33738461/212228374-50054891-85c8-4ce4-886b-df92b09e90e1.png">

**Evidence**
Only seven of the 16 sequences in this lineage are on GISAID, but it’s clear from the Usher tree that there are 16 sequences altogether. According to the Bloom Lab RBD Heat Map, S:Y453F is one of the most potent ACE2-affinity-enhancing mutations (on a BA.2 RBD background). 

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/33738461/212228571-e2a78f76-44c9-420e-80a4-00245cafc642.png">

One of the most consistent recent trends in SARS-CoV-2 evolution has been the acquisition of mutations that enhance ACE2 binding together with immune-evasive RBD mutations that reduce ACE2 binding. Examples include the Q498R-N501Y combination first found in BA.1 and BA.2; the R493Q reversion in BA.4 and BA.5; N460K in the BA.2.75 and BQ lineages; and most recently S486P in XBB.1.5.
 
The same pattern has been seen in countless hypermutated, chronic-infection sequences, as well as the cryptic wastewater variants observed by Marc Johnson, John Dennehey, and others.
 
S:Y453F has so far not been successful on a global scale. This might be taken as evidence that it is not an advantageous mutation, but the same could have been said for S:R493Q and S:N460K mutations, both of which were common in chronic-infection sequences long before they were present in dominant variants. This is not to say that Y453F is necessarily the next N460K, only that we cannot rule out the possibility that it could play that a similar role at some point.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16281024, EPI_ISL_16281338, EPI_ISL_16281597, EPI_ISL_16351247, EPI_ISL_16351334, EPI_ISL_16443071, EPI_ISL_16483651
</details>

**Comment by ryhisner** [comment]
This is now up to 19 sequences, including a new one with a collection date of January 6 with S:N536K and N:Q244H.
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/33738461/212697735-598b8f49-ed69-44de-95c9-abc3a4bed54a.png">

**Comment by ryhisner** [comment]
Three additional sequences from England uploaded today, all with N:Q244H and two with ORF1b:S424N (NSP12_S433N). There are 21 sequences on GISAID right now but 24 on the Usher tree. One at the base of the branch (and not yet on GISAID) has a collection date of January 14 and appears to lack the synonymous nucleotide mutations C8905T and T29446C, which are found in all other sequences. It is labelled "England/PHEC-YY87PF8/2023|2023-01-14"
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/33738461/213929395-181ff8f0-ca0d-470d-b8ac-2164d6d80e8c.png">

**Comment by corneliusroemer** [comment]
Commented on the DN.1.1 issue where you mentioned this
