### ISSUE TITLE
Proposed new B.1.617.X Delta-like lineage (currently miscalled as B.1.617.2) with Spike T76I, del144, E484A and D796H 

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#155]
New proposed lineage
By Tom Peacock

**Description**
**Sub-lineage of:** B.1.617 or possibly B.1
**Earliest Sequence:** 2021-03-17
**Latest Sequence:** 2021-05-19
**Countries circulating:** North and West India, single sequence from UK

**Description:** 
Conserved Spike mutations - T76I, Δ144, D253N, L452R, T478K, E484A, T572N, D614G, P681R, D796H, T859N, S939F

Conserved non-Spike mutations: NSP2 – S248G; NSP3 – T820I, S1578I; NSP4 – T492I; NSP6 – V149F, Y153C; NSP12 – P323L, S647I; ORF3a – Δ255; M -I82T; ORF7a – TRS disruption; N – R10P, Q28R, T205I, M234I, 

Lineage is still fairly low levels of genomes but appears to have a fairly wide geographic distribution in India. Many of the sequences from India, although from the Spring, have only been uploaded in recent weeks suggesting there may be more circulating than would appear. Group appears basal to the B.1.617 super-lineage so could probably be either described as B.1.617.X or B.1.X depending on how B.1.617 is defined.

**Genomes:** EPI_ISL_2253528, EPI_ISL_2461370, EPI_ISL_2461371, EPI_ISL_2556087, EPI_ISL_2556441, EPI_ISL_2880231, EPI_ISL_2880232, EPI_ISL_2881152, EPI_ISL_3006966, EPI_ISL_3006970, EPI_ISL_3006978

**Evidence:**

![b 1 617 X](https://user-images.githubusercontent.com/79373149/126639639-c1312856-841e-40a5-8eb2-9e98d818cf31.png)

**Proposed lineage name:** B.1.617.X or B.1.X?

**Comment by shay671** [comment]
I found 7 mutations which are found in B.1.617.1/2/3 (as seen in the table here) . 
out of those 7, only 2 found in this variant (L452R and P681R). 
So it seems more likely that it might be a new variant un related to B.1.617.2


![image](https://user-images.githubusercontent.com/80166370/126867471-b9e1e253-f313-4732-a5e4-c2153b63ce37.png)

**Comment by zach-hensel** [comment]
Nsp6: V149F is interesting here and in your other proposed lineage since V149A arose early in part of Delta and a naïve guess would be a mutation in the opposite direction with respect to structure. This mutation is also in B.1.1.348 and the sub-lineage defining B.1.1.348 and growing faster than the other one sharing the last common spike mutation includes V149F.

![image](https://user-images.githubusercontent.com/23096983/127186369-b7e58053-a6b4-4d24-abe1-1230b885955a.png)

**Comment by chrisruis** [comment]
Thanks @thomasppeacock. We've added this as B.1.633 in [v1.2.48](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.48). We didn't include a couple of sequences with >5% ambiguity across the genome or a few others (India/CT-ILSGS02490/2021, India/OR-ILSGS02497/2021, India/OR-ILSGS02788/2021, India/OR-ILSGS03114/2021) that have ambiguity at several of the lineage-defining SNP positions
