### ISSUE TITLE
XBK sublineage with S:P1162S mainly in Slovenia and Germany (>180 seq)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1551]
It's the largest subbranch of XBK with spike mutations right now.
Defining mutations:
XBK+S:P1162S(C25046T)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AP1162S&nextcladePangoLineage=XBK*&

**Comment by JosetteSchoenma** [comment]
Interesting. There is even one found in Shanghai/China, but it's an imported case.

**Comment by oobb45729** [comment]
![1](https://user-images.githubusercontent.com/115189228/215920817-7f51a8bd-0789-443d-9d96-0926aff8a689.png)

**Comment by alurqu** [comment]
This has been designated as XBK.1. It may need a "designated" tag and a milestone association.

**Comment by corneliusroemer** [comment]
@alurqu you create unnecessary work for me ;) who needs these designated/milestone things - just look at lineage notes :p

**Comment by HugonetX** [comment]
> 

The lineage notes would not fit into Excel 3.1 anymore...
