### ISSUE TITLE
CJ.1 Sublineage with S:R152Q, ORF1a:D4166N (101 seq, Feb 18)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1552]
**Description**
**Sub-lineage of:** CJ.1
**Earliest sequence:** 2022-11-28, France — EPI_ISL_16045205, EPI_ISL_16099603, EPI_ISL_16405771
**Most recent sequence:** 2022-12-31, France — EPI_ISL_16508759
**Countries circulating:** France (30), Netherlands (2), Ireland (2), Spain (1), Switzerland (1), UK (1)
**Number of Sequences:** 37
**GISAID Query:** Spike_W152Q, Spike_F486P, NSP9_D26N
**CovSpectrum Query:** Nextcladepangolineage:CJ.1* & S:R152Q
**Substitutions on top of CJ.1:**
**Spike:** R152Q
**ORF1a:** D4166N
**Nucleotide:** G12761A, G22017A
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/CJ.1_%2B_R152Q_%2B_ORF1aD4166N_subtreeAuspice1_genome_1e5f2_365f90.json
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/33738461/212521458-7e8f4129-6a41-47a8-9145-1ec2dcdbd5b6.png">

 
**Evidence**
R152Q involves an additional nucleotide mutation at S:152, G22017A. This lineage has so far been seen primarily in France, and France only very intermittently uploads sequences. This is likely why six of the last eight sequences uploaded have not been from France despite 28/29 sequences before those recent uploads being from France. In all likelihood there are a bunch of documented sequences of this lineage from France which they are still holding on to, for whatever reason.
<img width="971" alt="image" src="https://user-images.githubusercontent.com/33738461/212521484-bb573bda-9f92-44fe-bf2b-bbc9517da330.png">
 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16045205, EPI_ISL_16064118, EPI_ISL_16099603, EPI_ISL_16108816, EPI_ISL_16158520, EPI_ISL_16162160, EPI_ISL_16162161, EPI_ISL_16191683, EPI_ISL_16264976, EPI_ISL_16284267, EPI_ISL_16295600, EPI_ISL_16334692, EPI_ISL_16334749, EPI_ISL_16334800, EPI_ISL_16334864, EPI_ISL_16334890, EPI_ISL_16334972, EPI_ISL_16334987, EPI_ISL_16335041, EPI_ISL_16335042, EPI_ISL_16335086, EPI_ISL_16335116, EPI_ISL_16342704, EPI_ISL_16358692, EPI_ISL_16368112, EPI_ISL_16405771, EPI_ISL_16413432, EPI_ISL_16417737, EPI_ISL_16419856, EPI_ISL_16443909, EPI_ISL_16445339, EPI_ISL_16454438, EPI_ISL_16473965, EPI_ISL_16505485, EPI_ISL_16508759, EPI_ISL_16508812, EPI_ISL_16508813
</details>

**Comment by HugonetX** [comment]
We had eight laboratories uploading sequences. It has been cut to only two, now. Because, reasons...

**Comment by ryhisner** [comment]
Seems to be dying off, so I'm closing.
