### ISSUE TITLE
Lithuanian BQ.1.1 sublineage with S:T470I - 17 sequences 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1556]
I casually noticed a branch of BQ.1.1 defined by S:G482S then reverted to G while gaining S:T470I ,
it has  been sampled in Lithuania and England very recently and reached 16 sequences:

**Tree:** (Please @AngieHinrichs could you take a look at this reversion, do u think it is real?)
<img width="1139" alt="Schermata 2023-01-16 alle 01 31 47" src="https://user-images.githubusercontent.com/87669813/212575957-29b43463-43f1-4b67-ae56-a6a50b8dbce1.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f4a4_499a80.json?c=userOrOld&label=id:node_6345463

**Defining mutations**:
BQ.1.1* + A17039G > **G23006A (S:G482S)** >**Orf1a:T2124I** ( C6636T) > T14059C > C5239T, **S:T470I** ( C22971T) , A23006G (**S:S482G REVERSION**) 

**Gisaid query:** Spike_T470I,NSP3_T1306I finds **13** of them

**Sequences:**
 EPI_ISL_16157645, EPI_ISL_16250910, EPI_ISL_16344774,
EPI_ISL_16344810, EPI_ISL_16439756, EPI_ISL_16439783,
EPI_ISL_16439830, EPI_ISL_16473818, EPI_ISL_16473860,
EPI_ISL_16473864, EPI_ISL_16473924, EPI_ISL_16484204,
EPI_ISL_16484278

**Comment by FedeGueli** [comment]
15 seqs as today

**Comment by AngieHinrichs** [comment]
> Please @AngieHinrichs could you take a look at this reversion, do u think it is real?

I am skeptical, but the only way to tell for sure would be for someone with more knowledge about sequencing and genome assembly to look at BAM files from the raw data used to make the consensus genome assemblies.
