### ISSUE TITLE
Proposed new B.1.X lineage (currently misclassified as B.1.617.2) associated with Mexico/USA with Spike mutations S477N, E484K, H655Y and P681H

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#156]
**New proposed lineage
By Tom Peacock**

**Description**
**Sub-lineage of:** B.1 probably
**Earliest Sequence:** 2021-04-19
**Latest Sequence:** 2021-06-26
**Countries circulating:** Mexico (36 genomes), USA (2 genomes)

Description: 
Conserved Spike mutations - T29I, F32L, M153T, F157S, G252V, S477N, E484K, D614G, H655Y, P681H, D936H, D1260H

Conserved non-Spike mutations - NSP1 – T170N; NSP2 – T85I; NSP3 – V1522I; NSP4 – S163F, T492I; NSP5 – A7T; NSP6 - L37F, V84F, V149F; NSP8 – V160I; NSP12 – P323L; NSP13 – P77Q; NSP15 – F263L; ORF3a – Q57H; M – L29F, I82T;  N – R203K, N213Y

**Genomes:** 
[B1X Mexico.txt](https://github.com/cov-lineages/pango-designation/files/6862453/B1X.Mexico.txt)

note: EPI_ISL_2102644 appears to possibly be ancestral-like as it is missing several of the conserved mutations - may be better to exclude from lineage

**Evidence:** 
![Mexican B 1 X lineage](https://user-images.githubusercontent.com/79373149/126646467-792cf77b-fd74-4778-8a65-1a56e6669b45.png)

**Proposed lineage name:** B.1.X

**Comment by chrisruis** [comment]
Thanks @thomasppeacock for submitting. We've added this in as B.1.632 with 37 sequence designations in [v1.2.47](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.47)
