### ISSUE TITLE
Potentially new XBB.1.5 sublineage with ORF1ab:K322R and Nuc: C22945T mainly in USA

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#1561]
**A) Description**
New possible omicron sub-lineage with ORF1ab:K322R and Nuc: C22945T mutation proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**B) Earliest sequence:** 2022-12-02
USA/MA-CDCBI-CRSP_O6TUAUFFPYO2UVLR/2022

**C) Most recent sequence:** 2023-01-06
Ireland/KK-Enfer-060123005_C1/2023

**D) Countries circulating:**
USA, England, Ireland, Peru, Slovenia

**E) Genomes:**
[genomes.csv](https://github.com/cov-lineages/pango-designation/files/10450130/genomes.csv)

**F) Evidence:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ec42_849ad0.json?c=gt-ORF1ab_322&label=id:node_7819349
![Captura desde 2023-01-18 14-36-33](https://user-images.githubusercontent.com/89021119/213277704-6636c0e5-f872-448f-b1ba-f43c3643062f.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AK322R&nucMutations=A1230G%2CC22945T&nextcladePangoLineage=XBB.1.5&
![Captura desde 2023-01-18 14-15-40](https://user-images.githubusercontent.com/89021119/213275564-87cb2df3-98d5-4552-bcaf-82b792014464.png)

**Comment by Vjimenez-vasquez** [comment]
It seems like this XBB.1.5 will generate new  descendants in the next weeks as number of cases increases in USA

**Comment by Wen1953** [comment]
![imagen](https://user-images.githubusercontent.com/89021119/214390940-b78d310b-9114-47ae-8cf8-cd2f567106e2.png)

**Comment by Wen1953** [comment]
176 seqs to now
![image](https://user-images.githubusercontent.com/89021119/216992299-31a4c363-ab06-436e-ad95-30291c5e0175.png)

**Comment by Wen1953** [comment]
![imagen](https://user-images.githubusercontent.com/89021119/219381250-3d67c0d2-60dd-40b9-af56-2d380e11b417.png)

**Comment by Wen1953** [comment]
383seqs to now

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it has continued to show low or negative relative growth advantage, and seems to be just accumulating numbers along with XBB.1.5; this can be closed for now. Please re-propose or request re-opening should the situation change markedly in the future.
