### ISSUE TITLE
XBC.2 with S:F486L circulating in Brunei (28 sequences )

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1562]
While i am not sure of the current prevalence of this sublineage in Brunei, but i dont think it could be that high not having been exported anywhere but New Zealand ( mid december: EPI_ISL_16435258, that Usher puts outside the XBC tree stemming out from B:1.1.529 : https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_fd8b_8565a0.json?c=gt-S_486&label=id:node_8374137), still i think it is worth documenting this lineage and keep this issue open for a while to check if it has really died off.

Defining mutations XBC.2 + C23086T + C23019T (S:F486P > S:F486L) 
tree:
<img width="1198" alt="Schermata 2023-01-18 alle 21 22 40" src="https://user-images.githubusercontent.com/87669813/213286544-a7b1b864-de7d-4768-b71a-fb4d4c5867a8.png">

<img width="1152" alt="Schermata 2023-01-18 alle 21 29 57" src="https://user-images.githubusercontent.com/87669813/213288041-6e2ca66c-43a1-4cd1-8838-9c2b0571df83.png">

Gisaid query: Spike_F486L,Spike_S256L

Sequences: 29
EPI_ISL_15696710, EPI_ISL_15696712, EPI_ISL_15696715,
EPI_ISL_15710366, EPI_ISL_15710368, EPI_ISL_15710374-15710375,
EPI_ISL_15710377-15710379, EPI_ISL_16100122-16100123, EPI_ISL_16108216-16108219,
EPI_ISL_16108227-16108231, EPI_ISL_16174377-16174379, EPI_ISL_16174834,
EPI_ISL_16177087, EPI_ISL_16231619, EPI_ISL_16231621,
EPI_ISL_16435258

Countries: Brunei, New Zealand

**Comment by corneliusroemer** [comment]
This could just be a reversion to reference artefact, couldn't it?
