### ISSUE TITLE
Potential XBB.2 with additional mutation ORF1ab:E3932A mainly in Peru

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#1563]
**XBB.2 with additional mutation ORF1ab:E3932A by Group of Genomic Surveillance INS-PERU**

**Description**
Sub-lineage of: Potential new sub-lineage of XBB.2
Earliest sequence: hCoV-19/Peru/TAC-INS-34841/2022 (26/11/2022, Peru)
Most recent sequence: hCoV-19/Chile/AP-138456/2022 (18/12/2022, Chile)

**Countries circulating**
Peru (20), Chile (5)

This potential XBB.2 is distributed mainly in Tacna, Peru.

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/10451511/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1c2b_8672f0.json?c=gt-ORF1ab_3932&label=id:node_7831827

<img width="1306" alt="orf1abE3932A" src="https://user-images.githubusercontent.com/87997149/213305909-20d38018-7cf5-4b38-9956-884b812e88a6.png">

<img width="1680" alt="orf1abE3932A_usher" src="https://user-images.githubusercontent.com/87997149/213305931-606e9fa9-d9e1-4585-99a0-6a2a55b220a4.png">

**Proposed sub-lineage name**
XBB.2.X

**Comment by Vjimenez-vasquez** [comment]
Nice observation !!!

**Comment by Vjimenez-vasquez** [comment]
Nice observation !!!

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As this clade appears to have faded out, and is showing indicators of strong growth disadvantage in Peru over the last three months, this can be closed for now. Please request re-opening, or re-propose should these trends change markedly in the future.
