### ISSUE TITLE
BE.1.2.1 with S:N460S popped up in Costa Rica (29 sequences - 23-01-21)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1564]
I was checking qhat it was circualting in Costa Rica in the last weeks and i was surprised how well BE.1.2.1 is resisting there .
At first glance using the Covspectrum mutation "thermometer" it was self evident that S:N460S could have a role in its permanence there.

And Usher tree confirmed that a sublineage of BE.1.2.1 popped up there since the 2nd half of November.

So i think it is worth to propose it .

Defining mutations:
BE.1.2.1 > A29700G > Orf1a:T2836I (C8772T) > C1102T > S:N460S (A22941G)

Usher:
![Schermata 2023-01-20 alle 00 48 17](https://user-images.githubusercontent.com/87669813/213587123-9ef1d550-594c-4c46-9917-44b62b4187a8.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_133f6_9bdd20.json?label=id:node_6450363

Gisaid
Spike_V445A,Spike_N460S,N_E136D finds 28 sequences:
EPI_ISL_15578684, EPI_ISL_15708553, EPI_ISL_15767798,
EPI_ISL_15767805, EPI_ISL_15933298, EPI_ISL_15933366,
EPI_ISL_15933368, EPI_ISL_16098337, EPI_ISL_16294202,
EPI_ISL_16294238, EPI_ISL_16294282-16294283, EPI_ISL_16346887,
EPI_ISL_16347001, EPI_ISL_16347185, EPI_ISL_16347243,
EPI_ISL_16347368, EPI_ISL_16347392, EPI_ISL_16347483,
EPI_ISL_16347485, EPI_ISL_16456815, EPI_ISL_16522266,
EPI_ISL_16522297, EPI_ISL_16522312, EPI_ISL_16522338,
EPI_ISL_16523899, EPI_ISL_16523907-16523908

CovSpectrum shows an advantage for this lineage versus its parent :
![Schermata 2023-01-20 alle 00 51 07](https://user-images.githubusercontent.com/87669813/213587492-de511322-1c56-46ff-90bc-25344f7d9406.png)
https://cov-spectrum.org/explore/Costa%20Rica/AllSamples/from=2022-11-01&to=2023-01-19/variants?nextcladePangoLineage=BE.1.2.1*&aaMutations1=S%3AN460S&nextcladePangoLineage1=BE.1.2.1*&analysisMode=CompareToBaseline&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage DW.1 with 21 newly designated sequences, and 0 updated. Defining mutation A22941G (S:N460S) (following C1102T).
