### ISSUE TITLE
New  BA.5.2 +orf1b:1050N sublineage with  Orf1b:P1727L, then Orf1a:R207C and Orf1a:S2488F,  then Orf1b:S2339F circulating in Shandong China 79 seq

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1565]
EPI_ISL_16604347, EPI_ISL_16604351-16604353, EPI_ISL_16604355-16604357,
EPI_ISL_16604361-16604364, EPI_ISL_16604366-16604370, EPI_ISL_16604372-16604373,
EPI_ISL_16604375, EPI_ISL_16604378-16604381, EPI_ISL_16604383-16604388,
EPI_ISL_16604390-16604391, EPI_ISL_16604393, EPI_ISL_16604412-16604413,
EPI_ISL_16604416, EPI_ISL_16604418, EPI_ISL_16604424,
EPI_ISL_16604429, EPI_ISL_16604453, EPI_ISL_16604467,
EPI_ISL_16604474, EPI_ISL_16604483, EPI_ISL_16604485,
EPI_ISL_16604526, EPI_ISL_16604545, EPI_ISL_16604553,
EPI_ISL_16604555, EPI_ISL_16604558, EPI_ISL_16604563,
EPI_ISL_16604565-16604567, EPI_ISL_16604572, EPI_ISL_16604576,
EPI_ISL_16604579, EPI_ISL_16604612, EPI_ISL_16604620,
EPI_ISL_16604624, EPI_ISL_16604647-16604648, EPI_ISL_16604679,
EPI_ISL_16604691, EPI_ISL_16604736, EPI_ISL_16604767-16604768,
EPI_ISL_16604770-16604771, EPI_ISL_16604774, EPI_ISL_16604777,
EPI_ISL_16604780-16604785, EPI_ISL_16604789, EPI_ISL_16604885,
EPI_ISL_16604889, EPI_ISL_16604894

**Comment by FedeGueli** [comment]
Ok it is the same of #1542 i am closing this and updateing there

**Comment by Mild1-ai** [comment]
@FedeGueli I see that this issue has been closed, so I would like to ask, is EPI_ISL_16737228 variation in this sequence not normal? Thank you

**Comment by FedeGueli** [comment]
> 16737228

it seems BF.7.14 ,with a lot of mutations in orf1ab and S:T500A
<img width="733" alt="Schermata 2023-02-26 alle 19 28 55" src="https://user-images.githubusercontent.com/87669813/221429415-e1bb4c20-5991-4f67-86bc-0211c05c856d.png">
@ryhisner do u see any Mlnprvr related pattern??

**Comment by Mild1-ai** [comment]
Ok, thanks for the answer.

**Comment by ryhisner** [comment]
The S:T500A looks real, but almost all of the rest of those mutations are clustered closely together, which is always a sure sign of a sequencing error. I used to get fooled by sequences like that when I started doing this, but I've learned the common sequencing artifacts to be on the look out for.

**Comment by Mild1-ai** [comment]
The sequence is EPI_ISL_17027430 It could be DY.2.
The mutation is as follows.
ORF1a:L122F, ORF1b:G662S, S:R346T, S:L452Q, S:F490L, S:H519R, S:S1003I, ORF7a:S81P, ORF8:G66D
S:R346T, S:L452Q, S:F490L
S:H519R, S:S1003I and ORF1b:G662S

**Comment by Mild1-ai** [comment]
> The sequence is EPI_ISL_17027430 It could be DY.2. The mutation is as follows. ORF1a:L122F, ORF1b:G662S, S:R346T, S:L452Q, S:F490L, S:H519R, S:S1003I, ORF7a:S81P, ORF8:G66D S:R346T, S:L452Q, S:F490L S:H519R, S:S1003I and ORF1b:G662S

From Weibo user @ Pai Gang Leader

**Comment by Mild1-ai** [comment]
> The sequence is EPI_ISL_17027430 It could be DY.2. The mutation is as follows. ORF1a:L122F, ORF1b:G662S, S:R346T, S:L452Q, S:F490L, S:H519R, S:S1003I, ORF7a:S81P, ORF8:G66D S:R346T, S:L452Q, S:F490L S:H519R, S:S1003I and ORF1b:G662S

From Weibo user @ Pai Gang Leader
@FedeGueli

**Comment by FedeGueli** [comment]
thx @Mild1-ai already caught by @ryhisner

**Comment by ryhisner** [comment]
Yes, @Mild1-ai, many of the mutations in EPI_ISL_17027430 are frequently found in chronic-infection sequences, especially S:H519R, S:S1003I, and ORF1b:G662S. The other remarkable aspect of that sequence is that all 10 of its private mutations are non-synonymous. This is indicative of positive selection pressure and is another telltale marker of chronic-infection sequences. It is striking to see such a sequence already occurring in China. I expected to see a large number of chronic-infections from China beginning in a few months, but I did not expect to see any emerge so quickly.

**Comment by Mild1-ai** [comment]
> Yes, @Mild1-ai, many of the mutations in EPI_ISL_17027430 are frequently found in chronic-infection sequences, especially S:H519R, S:S1003I, and ORF1b:G662S. The other remarkable aspect of that sequence is that all 10 of its private mutations are non-synonymous. This is indicative of positive selection pressure and is another telltale marker of chronic-infection sequences. It is striking to see such a sequence already occurring in China. I expected to see a large number of chronic-infections from China beginning in a few months, but I did not expect to see any emerge so quickly.

@ryhisner I want to ask, what is chronic infection? And what are the effects of chronic infection? Thank you.

**Comment by Mild1-ai** [comment]
> Yes, @Mild1-ai, many of the mutations in EPI_ISL_17027430 are frequently found in chronic-infection sequences, especially S:H519R, S:S1003I, and ORF1b:G662S. The other remarkable aspect of that sequence is that all 10 of its private mutations are non-synonymous. This is indicative of positive selection pressure and is another telltale marker of chronic-infection sequences. It is striking to see such a sequence already occurring in China. I expected to see a large number of chronic-infections from China beginning in a few months, but I did not expect to see any emerge so quickly.

I think chronic infection is a concern, but I want to know, how did you guess that there would be chronic infection cases in China? Thank you for your answer.

**Comment by FedeGueli** [comment]
> > Yes, @Mild1-ai, many of the mutations in EPI_ISL_17027430 are frequently found in chronic-infection sequences, especially S:H519R, S:S1003I, and ORF1b:G662S. The other remarkable aspect of that sequence is that all 10 of its private mutations are non-synonymous. This is indicative of positive selection pressure and is another telltale marker of chronic-infection sequences. It is striking to see such a sequence already occurring in China. I expected to see a large number of chronic-infections from China beginning in a few months, but I did not expect to see any emerge so quickly.
> 
> I think chronic infection is a concern, but I want to know, how did you guess that there would be chronic infection cases in China? Thank you for your answer.

they are everywhere, potentially every immunocompromised people could have long term infection. But i guess there are also non imminocompromised people that could keep the virus replicating maybe in the GastroIntestinal tract. Someone recently coupled some lomg covid cases to that but i m not an expert in this theme so i cant judge how solid this coupling was

**Comment by Mild1-ai** [comment]
I see. Thank you for your answer.

**Comment by Mild1-ai** [comment]
@FedeGueli I tried to propose BA.5.2.48 and K444R, and there are four sequences

**Comment by Mild1-ai** [comment]
> @FedeGueli I tried to propose BA.5.2.48 and K444R, and there are four sequences

I see that BA.5.2.48 and S：K444R continue to grow, and there are currently 8 sequences all over South and North China.I also found the growth of BA.5.2.48 and S：A222V, and there are now 5 sequences from the provinces of South China and Shandong Province.

**Comment by FedeGueli** [comment]
@Mild1-ai propose them. i didnt give a proper look this week but the situation is moving there, better to keep tracked it if more than 5/10sewlqs from 2 or more regions

**Comment by Mild1-ai** [comment]
> @Mild1-ai propose them. i didnt give a proper look this week but the situation is moving there, better to keep tracked it if more than 5/10sewlqs from 2 or more regions

I understand that both branches have more than two or more regions. The K444R sequence continues to grow

**Comment by FedeGueli** [comment]
Put here to check it back : A28330G, A28363T, A28483G, G28541T

S:446D,S:L513I,S:G885S and orf9b:K67R Orf9b:E86D 
<img width="404" alt="Schermata 2023-03-13 alle 23 52 28" src="https://user-images.githubusercontent.com/87669813/224850107-33ad8fd7-61a5-411d-aa94-1d627f9abf76.png">

@Mild1-ai if you want to helpin keeping this and the other mentioned above monitored will be great.

**Comment by Mild1-ai** [comment]
Okay, I'll keep following up.
