### ISSUE TITLE
BA.5.3.5 + ORF1a:S2625F + ORF1b:P1664S sublineage circulating in South Africa with S:N185-, S:F186I, ORF1b:P918S , S:N460K, S:K444N and S:S494P (4  seqs  prevalence = 2% in 2023)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1566]
Checking South African sequences uploaded by wonderful scientist working on the battlefield there i noticed a cluster with heavy mutated (but convergent ) RBD stemming out directly from the politomy of BA.5.3.5 that was one of the first BA.5 sublineage to gain S:346T back this summer and since was able to keep a leading or coleading position among the lineages circulating in South Africa keeping out from there the variant soup coming from outside for a long time since finally some BQ.1* fast sublineage made it through there reaching dominance in the very last weeks.

4 Sequences belong to this sublineage: EPI_ISL_16415539, EPI_ISL_16521179-16521180, EPI_ISL_16585496,
one sampl ed just before Xmas 2022 and the other in 2023.

**Defining Mutations**: (EDITED)
From **Usher**
**BA.5.3.5** > C1912T, **ORF1a:S2625F** (C8139T) , **ORF1b:P1664S** (C18457T) > C14925T, **S:K444N**  (G22894T) , **S:N460K** (T22942G) > **ORF1b:P918S** (C16219T) **S:S494P** (T23042C) 

From **Nextclade**
I see it has also a deletion between S:185/186, so as result it should have also **S:N185-, S:F186I** too as defining.
<img width="629" alt="Schermata 2023-01-21 alle 12 48 17" src="https://user-images.githubusercontent.com/87669813/213865526-20970b2a-c29e-4a3f-9254-e1ee7b17fab6.png">
So as result it has also S:N185-, S:F186I

Please note that Epi-Isl_16521180 has S:484* too, that in CovSpectrum is S:E484S , 
@thomaspeacock, @corneliusroemer , @silcn @AngieHinrichs could you check this lineage? It has also a orf7a very messed up that if i am not wrong was described by @silcn in an unrelated Ba.4

**Tree:** (**EDITED)**
<img width="1150" alt="Schermata 2023-01-21 alle 15 22 54" src="https://user-images.githubusercontent.com/87669813/213871127-db24650e-6d64-4db3-b91c-fb8441e94889.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2cde6_bf3be0.json?c=userOrOld&label=id:node_6162661

**Gisaid query**: C14925T, C16219T, G22894T,T22942G, T23042C

**CovSpectrum query**: C8139T, C16219T, G22894T, T22942G, C1912T, C18457T, C14925T, T23042C
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C8139T%2CC16219T%2CG22894T%2CT22942G%2CC1912T%2CC18457T%2CC14925T%2CT23042C&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Geographically it seems to have arisen in the Western Cape area: samples are scattered among different ages and they have been sequenced by two different labs.

**Comment by corneliusroemer** [comment]
4 is a bit few, let's see what happens further. It's only been seen in Cape Town so far it appears

**Comment by FedeGueli** [comment]
Closing it for now
