### ISSUE TITLE
Yet another BA.2.75* x BQ.1.* recombinant with RBD breakpoint (30 sequences as of 2023-02-12)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1567]
This is the 5th BA.2.75* x BQ.1* recombinant cluster recently emerged, along with #1393 , #1425 , #1444 and #1543 . Again this recombinant has a breakpoint at RBD.

### Description
**Recombinant between**: BA.2.75* and BQ.1* (with S:R346T)
**Earliest sequence**: 2022/11/08 (Malaysia)
**Most recent sequence**: 2023/01/11 (UK-England)
**Countries circulating**: Malaysia (2/23), Austria (2/23), UK-England (19/23)
**Mutation profile** (private mutations are in yellow color):
![image](https://user-images.githubusercontent.com/86835836/213865500-f38eb4a4-e666-4abc-8297-02d06ac163c3.png)
**Private mutations**: C2842T, C6982T, T20748C
**GISAID and Cov-spectrum query**: C2842T, T20748C, C6982T, G22599C, G28681T

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/213865616-339a400e-cd7c-4355-857e-be57e43179ea.png)

### Genomes:
EPI_ISL_15788741, EPI_ISL_16192316, EPI_ISL_16192386, EPI_ISL_16240175, EPI_ISL_16375075, EPI_ISL_16440063, EPI_ISL_16485159, EPI_ISL_16535451, EPI_ISL_16535484, EPI_ISL_16535553, EPI_ISL_16535793, EPI_ISL_16560625, EPI_ISL_16560631, EPI_ISL_16560638, EPI_ISL_16560655, EPI_ISL_16560672, EPI_ISL_16560689, EPI_ISL_16560753, EPI_ISL_16560772, EPI_ISL_16560807, EPI_ISL_16560838, EPI_ISL_16586020, EPI_ISL_16586182

**Comment by JosetteSchoenma** [comment]
XBS
