### ISSUE TITLE
XAY.1.1 sublineage with ORF1a:P1640S and S:D1153Y (13 or 15 seq. France, Belgium, South Korea, Austria, Germany, likely Spain)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1569]
Defining mutations:
XAY.1.1+ORF1a:P1640S(C5183T)+S:D1153Y(G25019T)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AP1640S%2CS%3AD1153Y&nextcladePangoLineage=XAY.1*&

ORF1a:P1640S is also in BA.2.75 and the region around 1638-1640 of ORF1a is known to be a hotspot. There is also evidence that mutations in this area could potentially mean something significant. This paper shows that the T75L mutant of PLpro could alter the function of PLpro, increasing the K48-Ub cleavage:
https://www.nature.com/articles/s41586-020-2601-5
T75L of PLpro is ORF1a:T1638L.

S:D1153Y happens somewhat frequently. It was in BA.2.46, BA.2.59, and the majority of XAA. A few XAY.2s also has it.

**Comment by oobb45729** [comment]
The fifth sequence showed in Austria. Like the South Korean sequences, this one has nuc:C8140T. It also has S:I624V.

**Comment by oobb45729** [comment]
C8140T is also in BA.4.6. In fact, BA.4.6 has three mutations on the top of BA.4+S:658S: nuc:C8140T, nuc:C14599T, S:R346T.
XAY.1 picked up C14599T. XAY.1.1 picked up S:R346T. Now C8140T. Coincidence?

C8140T is not an ordinary mutation. It may be associated with a potential new TRS sequence.
The combination of C8140T+T8141C+G8144A happened multiple times independently. @ryhisner 
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=C8140T%26T8141C%26G8144A&

Also, coincidentally or not, some XAY.2s gained G8144A.

**Comment by oobb45729** [comment]
By the way, G6589C(ORF1a:K2108N) in XAY.1.1 is another mutation that is related to potential new TRS sequences.

G6589C is a rare mutation up till now with less than 100 sequences.
However, there are two cases of G6589C+T6586A, one case of G6589C+A6590G, and one case of G6589C+T6585C+T6586G, suggesting G6589C may play an important role.

**Comment by oobb45729** [comment]
New uploads from Spain: EPI_ISL_16621954 and EPI_ISL_16621955.

Missing ORF1a:P1640S and ORF1a:K2108N. But since they has S:R346T and S:D1153Y. They likely belong to this lineage too.

**Comment by oobb45729** [comment]
Apparently, S:D1153Y is predicted to escape two S2-targeting antibodies.
https://dms-vep.github.io/SARS-CoV-2_Omicron_BA.1_spike_DMS_mAbs/CC67.105_escape_plot.html
https://dms-vep.github.io/SARS-CoV-2_Omicron_BA.1_spike_DMS_mAbs/CC9.104_escape_plot.html

**Comment by oobb45729** [comment]
One more. New in Germany.
![XAY 1 1(230130)](https://user-images.githubusercontent.com/115189228/215598705-b48a0101-3d25-4005-b5a7-ddb32100f721.png)

**Comment by oobb45729** [comment]
One more from Belgium and four more from Germany. The Belgium one has S:S939F.
![1](https://user-images.githubusercontent.com/115189228/217104206-2f52b4a7-c774-4f2e-98a2-a57643fa6003.png)

**Comment by oobb45729** [comment]
More on S:D1153X: Aside from the DMS result, there were multiple reports about the epitopes of stem-helix-targeting antibodies. All of them seem to contain D1153.

>So far, six neutralizing mAbs targeting the stem-helix region, elicited by immunization in mice, or humanized mice (B6, 1.6C7, 28D9 and IgG22), or isolated from SARS-CoV-2 infected humans (CC40.8, S2P6, CV3-25), have been described[50](https://www.nature.com/articles/s42003-022-03262-7#ref-CR50),[57](https://www.nature.com/articles/s42003-022-03262-7#ref-CR57),[58](https://www.nature.com/articles/s42003-022-03262-7#ref-CR58),[59](https://www.nature.com/articles/s42003-022-03262-7#ref-CR59),[66](https://www.nature.com/articles/s42003-022-03262-7#ref-CR66),[72](https://www.nature.com/articles/s42003-022-03262-7#ref-CR72). All show varying degrees of cross-reactivity and cross-neutralizing activity against CoVs. Among these mAbs, four S2P6, CC40.8, IgG22 and B6 have previously been structurally characterized. All form a hydrophobic groove that cradles the hydrophobic face of the amphipathic SARS-CoV-2 stem helix (residues AA 1147-1156 for B6, residues 1142-1159 for CC40.8, 1147-1156 for IgG22, and residues 1146-1159 for S2P6). Alanine scanning of a stem helix peptide from MERS S suggests that the 1.6C7 and 28D9 mAbs which were isolated from humanized mice immunized sequentially with recombinant S from OC43, SARS and MERS, bind to a similar epitope region[64](https://www.nature.com/articles/s42003-022-03262-7#ref-CR64). In contrast to the other stem helix mAbs, CV3-25 binds to a distinct S2 epitope C terminal and on the opposite face of the amphipathic stem helix thus defining an additional site of vulnerability on pathogenic beta-CoVs.

From https://www.nature.com/articles/s42003-022-03262-7

**Comment by oobb45729** [comment]
S:D1153N and D1153A showed up in some wastewater cryptic lineages.
From https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1010636
![journal ppat 1010636 g008](https://user-images.githubusercontent.com/115189228/217113428-8b09ea72-e457-4636-b95f-e3aa14372660.PNG)

**Comment by oobb45729** [comment]
Proportions of multiple S:D1153X mutations has been increasing since the middle of 2022, showing a similar pattern to R346T, K356T, N460K, and F486X, suggesting a likely higher selection pressure.
D1153H
![H](https://user-images.githubusercontent.com/115189228/217117272-318a6443-5456-4aae-b44a-db5221e8226b.png)
D1153N
![N](https://user-images.githubusercontent.com/115189228/217117335-51716ff7-de34-49bb-9f55-e6d6d3387f1e.png)
D1153V
![V](https://user-images.githubusercontent.com/115189228/217117407-bf0080ba-3a15-4d91-9af4-0625a34bab96.png)
D1153A
![A](https://user-images.githubusercontent.com/115189228/217117468-b4f5585c-8269-4552-9b87-856fc851a2fb.png)
D1153E
![E](https://user-images.githubusercontent.com/115189228/217117536-0da2a973-34a2-4371-bf8b-cf52abe3374b.png)

Interestingly, S:D1153Y showed up quite often in earlier lineages, suggesting that it might have other functions.
![Y](https://user-images.githubusercontent.com/115189228/217118041-04f7a6e9-436b-4a51-af83-62631cf420f1.png)

**Comment by corneliusroemer** [comment]
Going up from 0.01% to 0.04% isn't quite comparable to 346T ;) But point taken, it looks like something could be happening there!

**Comment by oobb45729** [comment]
Two more from France.

**Comment by corneliusroemer** [comment]
Designating as XAY.1.1.1 - clearly spreading in Europe - doesn't matter whether it's due to 1153Y or not. Worth watching carefully. Thanks!

**Comment by FedeGueli** [comment]
big upload from germany yesterday, thx for designating
