### ISSUE TITLE
Another new B.1.X lineage (currently misclassified as B.1.620) associated with North America with Spike mutations del69-70, R346K, E484K, N501T, and P681H

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#157]
**New proposed lineage
By Tom Peacock**

**Description
Sub-lineage of:** B.1 probably
**Earliest Sequence:** 2021-05-12
**Latest Sequence:** 2021-07-05
**Countries circulating:** Mexico (53 sequences), USA (5 sequences), Canada (3 sequences), Spain (2 sequences)

**Description:**  

Conserved Spike mutations: Δ69-70, Δ242, R246T, R346K, E484K, N501T, D614G, P681H, T859N, S982L. 

Conserved non-Spike mutations: NSP3 –   I1489T; NSP6 – N82S; NSP12 – S6L, P323L; NSP13 – S38P, E128G; NSP14 –   Y124C; M – I82T; N – R10Q, T205I, A220V

Currently miscalled as B.1.620

**Genomes:**
[B1X Mexico lineage number 2.txt](https://github.com/cov-lineages/pango-designation/files/6862769/B1X.Mexico.lineage.number.2.txt)

**Evidence:** phylogenetic tree compared to B.1.525/Eta which according to Nextclade is the next closest large lineage

![anotherb1xlineage](https://user-images.githubusercontent.com/79373149/126656049-63ea6f44-ca4d-4263-9857-1244769be19b.png)

**Proposed lineage name:** B.1.X?

**Comment by chrisruis** [comment]
Thanks @thomasppeacock for submitting. In the latest UShER tree, this clade descends from B.1.415:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_hgwdev_1c49f_3bfcb0.json?c=pango_lineage&label=nuc%20mutations:G15732T,T19143C
This view is zoomed in on B.1.415 and the issue clade, reset layout will zoom it all the way out to see its context within B.1.

This clade does have the 2 SNPs that define B.1.415 - G15732T and T19143C, supporting it clustering with B.1.415. We've therefore designated this clade as B.1.415.1 in [v1.2.48](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.48)
