### ISSUE TITLE
BA.5.2.50	not added in the correct place in lineage_notes.txt

### ISSUE THREAD

**Issue by 3dgiordano** [cov-lineages/pango-designation#1570]
The line
https://github.com/cov-lineages/pango-designation/blob/e914fca31cf69637f773819c9b4976fb05878c88/lineage_notes.txt#L2665

it was added to the end of the file and not in the right place in lineage_notes.txt

the correct place should have been after BA.5.2.49
https://github.com/cov-lineages/pango-designation/blob/e914fca31cf69637f773819c9b4976fb05878c88/lineage_notes.txt#L1145

**Comment by Mydtlwn** [comment]
@InfrPopGen

**Comment by InfrPopGen** [comment]
Thank you @3dgiordano for pointing that out.
