### ISSUE TITLE
BF.7.14 sublineage with S:A626V mainly in China (48 sequences)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1573]
Defining mutations: BF.7.14 > S:A626V (C23439T) 

Earliest seq: 2022-11-24 (Beijing, China)
Most recent seq: 2023-01-16 (Fujian, China)
Countries detected: China (total 27, 17 from Jiangxi Province, 5 from Beijing Municipality, 3 from Fujian Province, 1 from Shandong Province, 1 from Anhui Province), Japan (1, traveller from China?)

Tree (By GISAID & China CDC, **notice that it should be S:A626V not S:A603V**. Also the definition of BF.7.14 in Fig.2 should be **S:C1243F not S:C1220F**)
![image](https://user-images.githubusercontent.com/121703496/214015885-0553b37b-db69-4ddf-95a3-d06939cf2e73.png)
![QQ截图20230123203908](https://user-images.githubusercontent.com/121703496/214041807-c99aa71e-8cbb-481f-9112-88b3bcabde72.png)

![QQ截图20230123180927](https://user-images.githubusercontent.com/121703496/214015947-140a3777-10df-441c-b731-aa1bf07e0eba.png)

https://gisaid.org/phylodynamics/china-cn/

sequences:
EPI_ISL_16334630, EPI_ISL_16350895, EPI_ISL_16357571, EPI_ISL_16494602, EPI_ISL_16522366, EPI_ISL_16522377, EPI_ISL_16579363,  EPI_ISL_16596989, EPI_ISL_16596997, EPI_ISL_16597033, EPI_ISL_16597034, EPI_ISL_16597036, EPI_ISL_16597037, EPI_ISL_16597039, EPI_ISL_16597040, EPI_ISL_16597041, EPI_ISL_16597042, EPI_ISL_16597043, EPI_ISL_16597046, EPI_ISL_16597055, EPI_ISL_16597059, EPI_ISL_16597064, EPI_ISL_16597068, EPI_ISL_16597072, EPI_ISL_16599082, EPI_ISL_16604718, EPI_ISL_16610762, EPI_ISL_16610877

**Comment by HynnSpylor** [comment]
46 seqs (correction). Including Australia (EPI_ISL_16386243), Singapore (EPI_ISL_16092938), South Korea (EPI_ISL_16514089) and Luxembourg (EPI_ISL_16527925).
![GISAIDQuery20230125](https://user-images.githubusercontent.com/121703496/214473419-4ccf0063-d4d2-4a12-a731-397d270bee20.png)

**Comment by corneliusroemer** [comment]
Designated as BF.7.14.3
