### ISSUE TITLE
BA.5.2.34 -> BA.2.75 -> BA.5.2.34 sandwich recombinant with RBD breakpoint. [142 seqs, Europe]

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1576]
**Description**
Recombinant of BA.2.75 -> BA.5.2.34, with the first breakpoint between 5183 and 9766, and the second breakpoint between 22577 and 22898. 
Earliest sequence: 2022-11-30, England and Germany. EPI_ISL_16234284, EPI_ISL_16152075
Most recent sequence: 2022-01-09, Germany, currently growing. 
Countries circulating: Germany (66), Denmark (4), UK (3), Austria (1), Switzerland (1)
Number of Sequences: 75
GISAID & CovSpectrum Query: C829T, A3207G, G4288A
Substitutions on top of parental BA.5.2.34: C829T
Substitutions on top of parental BA.2.75: G19327T (ORF1b:A1954S) (only present in 75%)

**From BA.5.2.34** it gains..
ORF1a:D981G, S:L452R, S:F486V, M:D3N, ORF9b:D16G
**From BA.2.75** it gains..
ORF1a:L3201F, ORF1a:N4060S, ORF1b:G662S, S:K147E, S:W152R, S:F157L, S:I210V, S:G257S, S:G339H, S:R346T

[**USHER Tree**](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_a6d9_efb7a0.json?c=gt-S_460)
![image](https://user-images.githubusercontent.com/94097102/214155455-26929591-9f3b-4dae-a3eb-1b1deb28a8b2.png)

**Evidence**
Here is a [Venn-Diagram ](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=%5B8-of%3AC829T%2CC1627T%2CA3207G%2CG4288A%2CG19327T%2CG23587A%2CC27012T%2CC27513T%2CA28330G%5D&nucMutations1=3207g%2C4288a&nextcladePangoLineage1=ba.5.2.34&nextcladePangoLineage2=ba.2.75*&analysisMode=CompareEquals&) comparing the proposed recombinant to the parental lineages. Notably the A3207G, G4288A mutations help make it clear that the BA.5 parent is BA.5.2.34. Beyond that, it shows that there is really only a single private mutation on this recombinant, making it less likely that it emerged from a chronic host. 

This proposed lineage doesn't look that fit to me, but it appears to be growing in Germany. The submission of 41 genomes of it on Jan 20 from Germany motivated me to propose it. 
In general, this fits into some of the larger picture that we've been seeing with recombinants -- BA.2.75 has a fit NTD, and [BA.5 wants it](https://github.com/cov-lineages/pango-designation/issues/1567). BA.2.75 seems to [drop ORF1a:S1221L, ORF1a:P1640S](https://github.com/cov-lineages/pango-designation/issues/1259) in some recombinants. 

Notably, 6 sequences (5 from Germany, 1 from Switzerland) have additional S:C1250F, S:G1251R. 

**Example Genomes**EPI_ISL_16356822, EPI_ISL_16152075, EPI_ISL_16590253, EPI_ISL_16590244, EPI_ISL_16593860, EPI_ISL_16487961, EPI_ISL_16595801, EPI_ISL_16597998

**Comment by FedeGueli** [comment]
@Sinickle it is not that slow, worth monitoring it.

**Comment by Sinickle** [comment]
Poland now has a sequence. Still quite Germany-centric though.

**Comment by Sinickle** [comment]
Scotland now has a (3) sequence(s).

**Comment by Sinickle** [comment]
Luxemborg now has a sequence, which is also the most recently collected of any- Jan 19.

**Comment by corneliusroemer** [comment]
Looks reasonable and with ~100 sequences worth designating IMHO

**Comment by FedeGueli** [comment]
136 as today

**Comment by Sinickle** [comment]
There is a sequence in Finland and Italy now as well.

**Comment by JosetteSchoenma** [comment]
I found an XBD/BA.5.2.1 recombinant. I did not propose it yet, since it only has 3 samples for now. It is very different, but Nextclade is calling it XBT now. The 3 samples are at the bottom. 2 from Denmark and 1 from the USA. @corneliusroemer 
![image](https://user-images.githubusercontent.com/94831035/223574525-c1d57038-d500-4cfa-a7d1-b4544251331a.png)

**Comment by JosetteSchoenma** [comment]
XBT
