### ISSUE TITLE
BQ.1.1 with additional mutations S:I210del and ORF1ab:K669R, T5193I in Peru

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#1577]
BQ.1.1 with additional mutations S:I210del and ORF1ab:K669R, T5193I by Group of Genomic Surveillance INS-PERU

**Description**
Sub-lineage of: Potential new sub-lineage of BQ.1.1
Earliest sequence: hCoV-19/Peru/TAC-INS-35021/2022 (25/11/2022, Peru)
Most recent sequence: hCoV-19/Peru/TAC-INS-38023/2022 (23/12/2022, Peru)

**Countries circulating**
Peru (24)

This potential BQ.1.1 is distributed mainly in Tacna, Peru.

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/10483854/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25cb0_eff7c0.json?c=gt-ORF1ab_669,5193&label=id:node_6414241

<img width="1257" alt="BQ 1 1" src="https://user-images.githubusercontent.com/87997149/214157578-2506ae85-16ba-4b22-a851-8f0377b2af40.png">
<img width="1699" alt="BQ 1 1_USHER" src="https://user-images.githubusercontent.com/87997149/214157589-4b5f5c3d-cb09-42bb-9776-aaf8b29272e4.png">

**Proposed sublineage name**
BQ.1.1.X

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.1.50 with 39 newly designated sequences, and 0 updated. Defining mutation C15842T (ORF1b:T792I) (following A2271G (ORF1a:K669R), T18159C).
