### ISSUE TITLE
DF.1 + S:G446V, S:N460K(15 sequences)

### ISSUE THREAD

**Issue by DoropFan** [cov-lineages/pango-designation#1578]
Description
Sub-lineage of:DF.1(BA.5.10.1.1)
Earliest sequence:2022-12-06(United Kingdom)
Countries circulating:United Kingdom13
Sequences:13

Nucleotide mutations:C8247T, A8399C, G22899T, T22942G
Amino acid changes:ORF1a:S2661F, ORF1a:I2712L, S:G446V, S:N460K
[CovSpectrum:ORF1a:S2661F, ORF1a:I2712L, S:G446V, S:N460K](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AS2661F%2CORF1a%3AI2712L%2CS%3AG446V%2CS%3AN460K&nextcladePangoLineage1=DF.1&)
![877df1g446vn460k](https://user-images.githubusercontent.com/118802079/214270871-3dd5f440-aede-47f1-a1e5-c7c3618d0352.jpg)
[Genomes](https://lapis.cov-spectrum.org/gisaid/v1/sample/gisaid-epi-isl?dateFrom=2022-07-18&dateTo=2023-01-17&aaMutations=ORF1a%3AS2661F%2CORF1a%3AI2712L%2CS%3AG446V%2CS%3AN460K&host=Human&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&orderBy=random)

**Comment by FedeGueli** [comment]
Great catch @DoropFan ! BA.5.10 is really a powerful example of stepwise evolution , emerged in a secondary branch of BA.5 in Eswatini took off from Philippines acquiring S:262S then S:R346T then S:144del and now S:G446V and S:N460K,

something to watch closely! Thank you!

**Comment by corneliusroemer** [comment]
Still at only 16 sequences, will close for now, just comment if there's development.
