### ISSUE TITLE
Potential new sublineage of C.37 with spike R21I, D253N, T572I, Q675H circulating in Europe

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#158]
Potential sublineage of C.37 (28 samples in Europe)
Earliest sequence: 2021/6/20 (Spain)
Most recent sequence: 2021/7/20 (Belgium)
Countries circulating: Belgium, Switzerland, Denmark, Spain, Ireland, France, Germany, Netherlands, Sweden.

In addition to usual C.37 mutations, this potential new sublineage also has:
Spike: R21I, D253N, T572I and Q675H (and 10 out of this 28 samples no longer have 246/253del);
N: H145Y, T366I;
ORF1a: K3351R;
ORF1B: M1596I;
ORF3a: I123T;
ORF10: P10S;

Genomes:
hCoV-19/Denmark/DCGC-124935/2021
hCoV-19/Denmark/DCGC-125495/2021
hCoV-19/Denmark/DCGC-125940/2021
hCoV-19/Spain/NC-CHN-01003728/2021
hCoV-19/Spain/NC-CHN-01003729/2021
hCoV-19/Germany/NI-RKI-I-187345/2021
hCoV-19/Denmark/DCGC-126794/2021
hCoV-19/Belgium/AZDelta-15602-2127R/2021
hCoV-19/Belgium/AZDelta-17066-2127R/2021
hCoV-19/Switzerland/BE-IFIK-1526-4308/2021
hCoV-19/Denmark/DCGC-127480/2021
hCoV-19/Sweden/2085757264/2021
hCoV-19/Netherlands/NB-RIVM-42905/2021
hCoV-19/Switzerland/VD-HUG-34705966/2021
hCoV-19/Ireland/LS-NVRL-S21IRL53472/2021
hCoV-19/France/IDF-IPP15418/2021
hCoV-19/Switzerland/BE-IFIK-1557-4656/2021
hCoV-19/Switzerland/BE-IFIK-1558-4699/2021
hCoV-19/Belgium/AZDelta-18761-2117R/2021
hCoV-19/Belgium/AZDelta-12635-2128R/2021
hCoV-19/Belgium/AZDelta-24735-2128R/2021
hCoV-19/Spain/CL-COV07261/2021
hCoV-19/Spain/CL-COV07382/2021
hCoV-19/Spain/CL-COV07388/2021
hCoV-19/Spain/CL-COV07393/2021
hCoV-19/Spain/CL-COV06689/2021
hCoV-19/Ireland/LS-NVRL-S21IRL53365/2021
hCoV-19/Ireland/LS-NVRL-S21IRL48818/2021

**Comment by chrisruis** [comment]
Thanks @c19850727 for submitting. We've added this as C.37.1 in [v1.2.49](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.49). We've pushed the start of the lineage back so it starts with an epidemiological event of exportation from South America. The start of the lineage is therefore defined by C20806T and is shown in the latest UShER tree here:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_hgwdev_1bc78_3d2160.json?c=country&label=nuc%20mutations:C20806T
