### ISSUE TITLE
XBJ sublineage carrying Orf1b:E1728D, Orf7b:S31L, S:N481- and S:G482S (Spike_N481S,Spike_G482del on Gisaid) emerged in USA 9 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1583]
Here i want to propose a sublineage carrying a deletion right in the rbm, i know from @thomaspeacock this is quite a recurrent thing in Sarbecovirus. 

It is a sublineage of XBJ which emerged by recombination between BA.5 and BA.2.3.20.

**Defining mutations**:  XBJ + Orf1b:E1728D, Orf7b:S31L, S:N481- and S:G482S (Spike_N481S,Spike_G482del on Gisaid)

**Gisaid query**: NSP14_E204D,NS7b_S31L,Spike_N481S, Spike_G482del,Spike_E484R

**Sequences:**
EPI_ISL_16089903, EPI_ISL_16130620, EPI_ISL_16380729,
EPI_ISL_16574300, EPI_ISL_16662824

**Usher** splits it in two **trees**, (probably due the fact S:481 and S:482 are masked in the main tree. cc @AngieHinrichs am i right?)
EPI_ISL_16130620
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_3af8e_23bdc0.json?c=gt-ORF3a_140

and the rest : https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3af8e_23bdc0.json?label=id:node_7997878
<img width="1150" alt="Schermata 2023-01-26 alle 10 19 22" src="https://user-images.githubusercontent.com/87669813/214799796-5fb142bd-9524-44cd-b72e-87e82c48675e.png">

CovSpectrum query: S:E484R, S:G482S, S:N481-, ORF7b:S31L, ORF1b:E1728D
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A484R%2CS%3A482S%2CS%3A481-%2COrf7b%3AS31L%2COrf1b%3AE1728D&nucMutations1=T23031C%2CG22895C%2CT22896C%2CC22664A%2CG22317T%2CG27915T%2CT23030C%2C24796T%2C4999C%2C745C%2C1466G%2C12439C&

**Comment by thomasppeacock** [comment]
Going to put into monitoring because of the low number of sequences currently - however if this shows any sign of growth I think this should be prioritised for assignment as the 481 deletion is predicted to have a very large antigenic impact

**Comment by FedeGueli** [comment]
@thomasppeacock unluckily another one popped up it is recent from USA  NC 9-1-23 : EPI_ISL_16684467

**Comment by c19850727** [comment]
@FedeGueli  if you broaden this proposal without S:N481- and S:G482S, there are actually 34 sequences already, but Usher somehow place the majority of them as a sibling branch due to 2 AA changes (S:G485D and N:R195K). Or maybe they are indeed from an independent recombination event? 

![image](https://user-images.githubusercontent.com/86835836/218301084-c10498f5-b5ec-4c59-99f0-fbd8a46bd561.png)

GISAID query: A16011G, C27847T

**Comment by FedeGueli** [comment]
7 sequences of the original proposed lineage as today.

thanks @c19850727 i ask help from @corneliusroemer @AngieHinrichs @thomasppeacock what do you think they are the same lineage ? it is worth designating this in its broader definition so it will be a lot easier to get also to track the sublineage of interest??

**Comment by corneliusroemer** [comment]
Let's first try to get a clean tree

The deletion itself is invisible to Usher and also not used by Nextclade for placement.

We should figure out if these are two or one lineages. Gut feeling is it's 1 but better clean it up first. Things get more stable of they get bigger.

**Comment by AngieHinrichs** [comment]
> Usher splits it in two trees, (probably due the fact S:481 and S:482 are masked in the main tree. cc @AngieHinrichs am i right?)

Deletions are invisible to usher, it can only see substitutions, but those sites are not masked.  When a large branch has a deletion and I observe false "substitutions" in the deleted range causing problems with the tree, then I might apply some [branch-specific masking](https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/utils/otto/sarscov2phylo/branchSpecificMask.yml) to the deleted range, but that is a very manual process and so far I have done that only for major VoCs.

I will see if I can clean up the XBJ neighborhood a bit.  :)  Temporarily removing Philippines/PH-RITM-3177/2022|EPI_ISL_16017331 and SouthKorea/KDCA182315/2022|EPI_ISL_16340475, and then reoptimizing, might be enough to merge those branches, we'll see.

**Comment by FedeGueli** [comment]
thx @AngieHinrichs the new tree looks like that:
<img width="1131" alt="Schermata 2023-02-16 alle 22 22 33" src="https://user-images.githubusercontent.com/87669813/219489693-4e486d9f-9a39-4245-b486-4f18759539bb.png">


now there are 8 sequences of the proposed lineage:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d7a4_e67b50.json?c=gt-ORF1ab_5583&label=id:node_8163099

**Comment by corneliusroemer** [comment]
Really nice new tree - masking fixed it! I'll have a look at designating.

**Comment by AngieHinrichs** [comment]
Actually, there was no masking (yet anyway) -- removing a sequence and re-optimizing was enough to get XBJ unified.  And then, when that sequence (Philippines/PH-RITM-3177/2022 ) was placed again, it was placed within XBJ.  (Without having looked at the details, I'm guessing that the sequence has a lot of Ns and was placed before other more complete sequences, so it had more reference alleles imputed, causing it to break up that branch.)

I haven't forgotten about your suggestions for adding more branch-specific masking!  I will get to those.  I'm just working down my list, and right now getting a good minimized tree for designation/data release v1.18.1 is at the top.  :)  In the meantime, suggestions for branches and reversions are helpful.  (With the caveat that if a recombinant arises on that branch, masking reversions may make the tree have the incorrect alleles for the recombinant.)  XBB is a mess with all the reversions, so overall I think it will be worth it to mask a lot of them.

**Comment by FedeGueli** [comment]
Still 9 in the proposed lineage. I will close it next week if no new seq will come in
