### ISSUE TITLE
XBM sublineage defined by Orf1a:T4090I, S:P251S, S:L455F, S:Q1180K - 16 sequences Canada as 24-02-23

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1585]
XBM is a BA.2.76/BF.3 recombinant lineage spotted by @c19850727 back in September in India defined by 4 spike mutations: S:248N/346T/547I/1020S
In october It seemed to have disappeared competely by our radars when it came back in December spreading fastly then in Us and Canada. 
Actually it is climbing the #Collection24 chart showing an apparent growth rate comparable to the top lineages:
<img width="1196" alt="Schermata 2023-01-26 alle 17 45 49" src="https://user-images.githubusercontent.com/87669813/214896472-774f2c5f-06f0-443d-b71e-794e66139b3a.png">

Since its re appearance in December it is mainly divided in two branches:
A canadian one defined by Orf1a:T4090I (NSP8) 
and an american one defined by Orf1a:N2065S (NSP3)

The Orf1a:T4090I branch seems slighty faster than the other one, while both seem much faster than the original XBM:
https://cov-spectrum.org/explore/World/AllSamples/from=2022-12-01&to=2023-01-26/variants?aaMutations=orf1a%3AN2065S&nextcladePangoLineage=XBM*&aaMutations1=ORF1a%3AT4090I&nextcladePangoLineage1=XBM*&analysisMode=CompareToBaseline&
<img width="785" alt="Schermata 2023-01-26 alle 17 52 35" src="https://user-images.githubusercontent.com/87669813/214898120-d9fb4b80-85f9-471c-9ae5-503062f6e3d7.png">

Today i want to propose a little cluster from the canadian branch with Orf1a:T4090I that acquired 3 further mutations in the spike (NTD,RBD,S2)

**Defining mutations:**

**XBM** > T18429C > **Orf1a:T4090I** (C12534T) > C24904T > 
C13680T, **S:P251S** (C22313T), **S:L455F** (G22927T),  **S:Q1180K** (C25100A)

**Tree:**
<img width="1161" alt="Schermata 2023-01-26 alle 17 58 27" src="https://user-images.githubusercontent.com/87669813/214899597-32b182c1-a85b-48b4-bb18-447f66421a81.png">
<img width="1139" alt="Schermata 2023-01-26 alle 17 58 49" src="https://user-images.githubusercontent.com/87669813/214899689-b48a6a3c-46ae-429d-a845-f1e625a53289.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1b38c_2a77b0.json?c=gt-S_251,455,1180&label=id:node_7202517

**Gisaid & Covspectrum queries**: C13680T, C22313T, G22927T,C25100A

**Sequences**: 
EPI_ISL_16531224, EPI_ISL_16531687, EPI_ISL_16629659,
EPI_ISL_16630143

**Comment by FedeGueli** [comment]
4 more sequences from Canada uploaded yesterday

**Comment by corneliusroemer** [comment]
Interesting, been going up quite a bit in Canada recently. A bit unexpectedly as XBM by itself doesn't seem that special

**Comment by FedeGueli** [comment]
> Interesting, been going up quite a bit in Canada recently. A bit unexpectedly as XBM by itself doesn't seem that special

agree @corneliusroemer me too (and the group too)  not getting exactly why XBM as a whole is going so good recently after disappearing for a while.

**Comment by corneliusroemer** [comment]
Just bear in mind that the collection growth advantages can be bogus if the country is set to World and a lineage is present in a country with lots of recent submissions. Better to look on a country basis.

**Comment by FedeGueli** [comment]
> Just bear in mind that the collection growth advantages can be bogus if the country is set to World and a lineage is present in a country with lots of recent submissions. Better to look on a country basis.

@corneliusroemer i lately think that the world advantage is better to compare different lineages, for absurd the more a country sequences the more the growth advantage become less reliable, this to me it is due that a intense sequencing ferequence could weigh more imoportation than when sequence intensity is inferior. In my view Uk,Denmark,Usa country growth advantage query should be avoided.

**Comment by FedeGueli** [comment]
6 new samples came from Ontario as the previous ones hinting to a limited circulation in that area. @corneliusroemer what do you think worth monitoring it a bit more or closing?

**Comment by FedeGueli** [comment]
It seems to be slowing closing it for now
