### ISSUE TITLE
Potential BA.2.75* x XBC.1.1 recombinant (6 sequences as of 2023-03-15)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1589]
I am to propose this small recombinant cluster with only 5 sequences, as it is a rare event of recombination of recombinants, especially with some remnants of Delta genome involved.

### Description
**Recombinant between**: BA.2.75* and XBC.1.1
**Earliest sequence**: 2022/12/14 (Australia-NSW)
**Most recent sequence**: 2023/01/11 (Australia-NSW)
**Countries circulating**: Australia (all in NSW)
**Potential breakpoint**: NSP3, between AA 1307 and 2104

Mutation profile (the part from potential BA.2.75* donor is in yellow color):
![image](https://user-images.githubusercontent.com/86835836/215324074-b52accbf-9813-429c-8e2b-5c484cf1ad4c.png)
**GISAID and Cov-spectrum query**: C3796T, C3927T, G4184A, C4321T, C4586T, C5183T, G8851T

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/215324283-0972ab0b-9286-45cf-8301-f7c7ab5a051b.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c9e0_51cdc0.json?branchLabel=Spike%20mutations&c=gt-nuc_4885&l=scatter&label=id:node_8471321&scatterY=gt

### Genomes:
EPI_ISL_16448106, EPI_ISL_16494002, EPI_ISL_16584982, EPI_ISL_16702526, EPI_ISL_16702529

**Comment by FedeGueli** [comment]
Thx @c19850727 very interesting

**Comment by c19850727** [comment]
6 sequences as of 2023-02-10. Newly found in Belgium.

**Comment by c19850727** [comment]
I'm to close this proposal as it's not growing any longer
