### ISSUE TITLE
Two potential sublineages of B.1 circulating in Mexico and the US

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#159]
### Proposed Sublineage 1:
Sublineage of B.1 (66 samples)
**Earliest sequence:** 2021/3/2 (US-Arizona)
**Most recent sequence:** 2021/6/2 (Mexico-Tabasco)
**Spike mutations:** 
L18R, del69/70, R158S, *N440K (31 out of 66 samples), E484K, D614G, A688V, N764K, *E1258D (20 out of 66 samples)
**Non-spike mutations:**
N: N213Y
ORF1a: T2283I, S2293G, I2790T, T3117A, A3143V, R3163S, del3675/3677
ORF1b: *V224I (20 out of 66 samples), P314L, G662S, P1000L
ORF9b: T83I
**Genomes:**
EPI_ISL_1184562, EPI_ISL_1531128, EPI_ISL_1660547-1660550,
EPI_ISL_1660577, EPI_ISL_1971461, EPI_ISL_2136393,
EPI_ISL_2178736, EPI_ISL_2178741, EPI_ISL_2362697-2362698,
EPI_ISL_2492476-2492477, EPI_ISL_2492486, EPI_ISL_2492497-2492498,
EPI_ISL_2525714, EPI_ISL_2527676, EPI_ISL_2544760,
EPI_ISL_2597979, EPI_ISL_2652511, EPI_ISL_2689795,
EPI_ISL_2709691-2709692, EPI_ISL_2709695, EPI_ISL_2709706,
EPI_ISL_2709708-2709711, EPI_ISL_2709722, EPI_ISL_2709728,
EPI_ISL_2709731, EPI_ISL_2727858, EPI_ISL_2758241,
EPI_ISL_2800944-2800945, EPI_ISL_2835915, EPI_ISL_2835918-2835919,
EPI_ISL_2835921, EPI_ISL_2835925, EPI_ISL_2835932,
EPI_ISL_2835938, EPI_ISL_2835949-2835950, EPI_ISL_2860416,
EPI_ISL_2861162-2861163, EPI_ISL_2861176, EPI_ISL_2861178,
EPI_ISL_2861184, EPI_ISL_2861188-2861189, EPI_ISL_2927335,
EPI_ISL_2928504, EPI_ISL_2966356-2966357, EPI_ISL_2966373-2966374,
EPI_ISL_2966410, EPI_ISL_2970387, EPI_ISL_3010943,
EPI_ISL_3046124

### Proposed Sublineage 2:
Sublineage of B.1 (47 samples)
**Earliest sequence:** 2021/1/16 (Mexico-Veracruz)
**Most recent sequence:** 2021/6/18 (Mexico-Veracruz)
**Spike mutations:** 
T19I, H49Y, del141/144, T259R, N450K, S477N, D614G
**Non-spike mutations:**
M: A63T
N: D81Y, G215V
ORF1a: *D582G (19 out of 47 samples), Y3722C
ORF1b: P314L, S1023G, S2198I
ORF7a: P34L
ORF9b: Q77H
**Genomes:**
EPI_ISL_941312, EPI_ISL_1012891, EPI_ISL_1037223,
EPI_ISL_1168492, EPI_ISL_1267991, EPI_ISL_1267997,
EPI_ISL_1279296-1279297, EPI_ISL_1288244-1288245, EPI_ISL_1288361,
EPI_ISL_1320534, EPI_ISL_1339509, EPI_ISL_1405906,
EPI_ISL_1416420-1416421, EPI_ISL_1416556-1416557, EPI_ISL_1416662,
EPI_ISL_1444886, EPI_ISL_1462311, EPI_ISL_1469118,
EPI_ISL_1479643, EPI_ISL_1562902, EPI_ISL_1585610,
EPI_ISL_1585612, EPI_ISL_1632554, EPI_ISL_1700815,
EPI_ISL_1761796, EPI_ISL_1811419, EPI_ISL_1909349,
EPI_ISL_2091368, EPI_ISL_2091434, EPI_ISL_2091449,
EPI_ISL_2391591, EPI_ISL_2490334, EPI_ISL_2671732-2671733,
EPI_ISL_2681278, EPI_ISL_2681282, EPI_ISL_2928465,
EPI_ISL_2942533, EPI_ISL_2942535, EPI_ISL_2942552,
EPI_ISL_2942554-2942555, EPI_ISL_2970056

**Comment by chrisruis** [comment]
Thanks @c19850727. We've added your sublineage 1 as B.1.634 and your sublineage 2 as B.1.635 in [v1.2.49](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.49)
