### ISSUE TITLE
XBJ saltation sublineage - with S:485D and ~10 private mutations [26 seq as of 2022-01-30]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1591]
Another XBJ-like recombinant has popped up - it's go a similar spike (except having S:485D in addition) but got quite some non-RBD private mutations compared to XBJ.

Seems most commonly sequenced in Japan and South Korea (though those are just heavy sequences in this area so not necessarily epicenters).

Example sequence: EPI_ISL_16715436

It's the top one here that's still assigned BA.2.3.20 by Usher. Nextclade calls these XBJ due to the similarity:

<img width="2099" alt="image" src="https://user-images.githubusercontent.com/25161793/215541360-81985eb4-5507-40ec-9ec3-59374e1b16c6.png">

https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4d498_7f4ae0.json

Queriable as: A253G, A16011G, T24349C
covSpectrum: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=A253G%2CA16011G%2CT24349C&

All submissions bar one from the Philippines have been in January 2023, suggesting potentially relevant growth.

Usher seems to exclude these sequences at the moment @AngieHinrichs 

Would be great if someone could investigate where the breakpoints are and what the parents are, potentially this has XBJ as a parent?

**Comment by FedeGueli** [comment]
@corneliusroemer i rapidly checked in the compare variant tool on covspectrum and it doesnt seem to me that XBJ ha any private mutation vs this lineage. So probably a saltation is more likely. (There is a deletion in spike but around 45% of sequences of XBJ missing a lot of genes. (maybe just ba.2.3.20 spike only ones)

**Comment by corneliusroemer** [comment]
The XBJ that are missing genes are Spike only BA.2.3.20 from Austria that get misassigned as recombinants due to known Nextclade issue. So disregard these ;)

You're right, the fact that these sequences here don't have any reversions wrt XBJ makes it more likely to be simple saltation rather than recombinant. So XBJ sublineage it is then. Thanks for looking into this @FedeGueli!

**Comment by FedeGueli** [comment]
Thx @corneliusroemer for your work as usual. I realized then that i digged a bit in this lineage (XBJ) the last week and if i am not wrong this long branch has not that advantage over its parent (quite surprisingly looking at the tree, where lineages with that kind of rapid "blooming" are linked to increased or slighty increased transmissibility), but maybe it got selected somewhere sequencing is very low)

**Comment by FedeGueli** [comment]
@corneliusroemer @thomasppeacock @InfrPopGen 
 this reached 44 seqs with  A253G, A16011G, T24349C keeping circulating in Japan and South Korea. I think a designation can be deserved.

**Comment by ryhisner** [comment]
There's a lot more diversity than you'd expect in this lineage. Could be a sign of slow growth, but might also indicate that the BA.2.3.20/BA.5 recombination, together with this saltation, opened up new evolutionary avenues. The longer branches on the tree aren't the usual artifactual, reversion-laden ones we typically see. They are all legit.
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/33738461/222913527-70fc69bb-9429-4b37-9107-0226dc830f73.png">
