### ISSUE TITLE
Proposal of new XBB.2 Sublineage with S: T19P (nuc: A21617C), Nuc: C5144T , T5731A (130 seq. Peru, USA, Chile, India) 

### ISSUE THREAD

**Issue by AliNunz** [cov-lineages/pango-designation#1593]
**Description:**
Potential XBB.2 sub-lineage containing S: T19P, Nuc: C5144T, T5731A (As @Vjimenez-vasquez  referenced in his comment on #1381) mutations proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**Sub-linage of:** XBB.2

**Earliest sequence:** 2022-11-01
hCoV-19/Peru/LIM-INS-33277/2022

**Most recent sequence:** 2023-01-06
hCoV-19/USA/TX-CDC-QDX45529161/2023
hCoV-19/Chile/RM-1195/2023

**Countries circulating:**
Peru (119), USA (6), Chile (4), India (1)

**Evidence:**
![nextstrain](https://user-images.githubusercontent.com/115187682/215575320-73c1e2b6-b1d1-4857-bfff-a07b10996f6e.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_29f53_817920.json?c=gt-S_19

![cov-spectrum](https://user-images.githubusercontent.com/115187682/215570034-6f204bb4-b29a-4b85-90d7-ead354d15ac9.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C5144T%2CT5731A%2CA21617C&nextcladePangoLineage=XBB.2&

**Genomes:**
[genomes.csv](https://github.com/cov-lineages/pango-designation/files/10539200/genomes.csv)

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As this appears to have faded away, with almost no detections over the past two months, and strongly negative growth in Peru and South America relative to its parent, this can be closed for now. Please re-propose or request reopening should this clade strongly reemerge in the future.
