### ISSUE TITLE
XBB.1.5 sublineage with ORF1a:T2300I first detected in England, United Kingdom (160 good and 173 total seqs as of 2023-02-10; UK, Canada, USA, Europe, South Africa, India, Australia)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1594]
There may be a XBB.1.5 sublineage with ORF1a:T2300I (C7164T; NSP3:T1482I) first detected in England, United Kingdom.

As of 2023-01-30, Cov-Spectrum reports 100 good-quality (109 total) XBB.1.5+ORF1a:2300I sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXBB.1.5+%26+ORF1a%3AT2300I&nextcladeQcOverallScoreTo=29&

As of 2023-01-30 and considering the past 2 months of data, CoV-Spectrum shows a 45% (confidence interval 21-68%) growth advantage for XBB.1.5+ORF1a:2300I over XBB.1.5 in the United Kingdom:
![Growth-XBB 1 5+ORF1a_2300I_vs_XBB 1 5_UK](https://user-images.githubusercontent.com/88959107/215590027-51cc6cf9-d595-4bdf-8c34-caad08294842.png)
Source: https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past2M/variants?nextcladePangoLineage=XBB.1.5&aaMutations1=ORF1a%3A2300I&nextcladePangoLineage1=XBB.1.5&analysisMode=CompareToBaseline&

As of 2023-01-30, UShER shows the CoV-Spectrum samples are on three parallel subtrees with evidence of additional branching, but this may actually be one subtree split into three due to artifacts related to S:252. 54 sequences have S:G252V, 54 more sequences show S:G252X so a definitely problem at S:252, and 1 sequence has a reversion S:G252G which is suspect.
![UShER_CoV-Spectrum_XBB 1 5+ORF1a_2300I](https://user-images.githubusercontent.com/88959107/215590201-4501dc44-b20d-45d9-8a95-7226b1203b40.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/01/singleSubtreeAuspice_genome_CoV-Spectrum_XBB.1.5%2BORF1a_2300I.json?c=gt-ORF1ab_2300&label=id%3Anode_7904888

GISAID query: Spike_F486P, NSP3_T1482I

First GISAID sequence: England, United Kingdom 2022-12-12

First GenBank sequence: England, United Kingdom 2022-12-12 

Most Recent GenBank sequence: Pennsylvania, USA 2023-01-10

Most Recent GISAID sequence: England, United Kingdom 2023-01-19

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at [Support-XBB.1.5_ORF1a_2300I.zip](https://github.com/cov-lineages/pango-designation/files/10539852/Support-XBB.1.5_ORF1a_2300I.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-XBB.1.5+ORF1a_2300I.txt](https://github.com/cov-lineages/pango-designation/files/10539857/gisaid-epi-isl-XBB.1.5%2BORF1a_2300I.txt)

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=XBB.1.5&muts=ORF1a%3AT2300I. 

Edit: Corrected growth source typo from UShER to CoV-Spectrum.

**Comment by corneliusroemer** [comment]
This is really just noise at this point:
> ![image](https://user-images.githubusercontent.com/25161793/215608688-be16bab8-c059-40c6-9fcb-ff3fcdea41c2.png)

**Comment by AngieHinrichs** [comment]
In the description:

> UShER shows a 45% (confidence interval 21-68%) growth advantage

credit where it's due: the growth advantage is from CoV-Spectrum not UShER.

**Comment by alurqu** [comment]
> credit where it's due: the growth advantage is from CoV-Spectrum not UShER.

That was an unintended error. Corrected.

**Comment by alurqu** [comment]
The growth advantage of this lineage over its parent XBB.1.5 in the UK is down to 14% (confidence interval 2-27%).

However, this lineage has now been detected in India, Australia, and several additional countries in Europe.

**Comment by corneliusroemer** [comment]
I told you this was just noise, growth advantages are almost always positive in the beginning ;)

I'll have systematic look at XBB lineages later this week.

Also, 1/3 of these sequences seem to have a reversion to root of S:V252G which isn't a great sign regarding sequence quality.

**Comment by alurqu** [comment]
The growth advantage of this lineage continues to drop. Closing at least for now.
