### ISSUE TITLE
XBB.1.5 with S:A348S [2 clusters]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1595]
According to the Bloom lab immune escape calculator, S:A348S is predicted to add to immune escape while coming at only a small ACE2 binding cost.

This mutation seems to have arisen already twice within XBB.1.5

There's one international cluster in US-NJ/NY, Canada-QC (east coast) and Finland with 5 sequences as of today and mutations G15957T (non-defining branch) then T8503C, G22604T (defining).

<img width="2106" alt="image" src="https://user-images.githubusercontent.com/25161793/215594782-81ab081a-79c3-489b-9288-389f150b0877.png">

There's another 2 sequence cluster from US-WA and Canada-ON (west coast) directly on the XBB.1.5 polytomy.

<img width="2112" alt="image" src="https://user-images.githubusercontent.com/25161793/215594811-a673ea8d-e6e2-4287-b2a1-adc2ca10c97b.png">

Both too small to designate but should be monitored. Both clusters had one sequence each uploaded today.

**Comment by Outpfmance** [comment]
XBB.1.5 with A348S now has 13 sequences @corneliusroemer

**Comment by FedeGueli** [comment]
The first one has been now designated FD.3

**Comment by FedeGueli** [comment]
i think this should be closed

**Comment by Memorablea** [comment]
111 NOW

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
This branch is dead, please close this issue
