### ISSUE TITLE
Proposal of new sub-lineage of BQ.1.1.13 with additional mutation ORF1ab: M5298V in Peruvian genomes by Group of Genomic Surveillance INS-PERU

### ISSUE THREAD

**Issue by IrisSilvaINS** [cov-lineages/pango-designation#1596]
**Description**
Potential new sub-lineage of BQ.1.1.13 with ORF1ab: M5298V mutations proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**Earliest sequence**:  2022-11-17
hCoV-19/Peru/CUS-INS-35348/2022 (EPI_ISL_16300787)

**Most recent sequence**: 2023-01-02
hCoV-19/Trinidad and Tobago/410154/2023 (EPI_ISL_16612758)

**Countries circulating**:
Peru (19 sequences), USA (1) and Trinidad and Tobago (1)

**Genomes**
[Genomes.txt](https://github.com/cov-lineages/pango-designation/files/10539863/Genomes.txt)

**Evidence**

<img width="1147" alt="imagen1" src="https://user-images.githubusercontent.com/93674902/215593459-84963b3e-38f0-47f7-8464-6304b7c80fee.png">

<img width="1704" alt="imagen2" src="https://user-images.githubusercontent.com/93674902/215595603-0248cdf8-8241-4fbc-b4ed-89d9bab52a22.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4286_814690.json?branchLabel=none&c=userOrOld&label=id:node_6324390

<img width="1552" alt="imagen3" src="https://user-images.githubusercontent.com/93674902/215594359-9c64ef93-48fd-4b59-b5c7-0f103577bd08.png">

https://cov-spectrum.org/explore/Peru/AllSamples/Past6M/variants?aaMutations=ORF1b%3AM897V&nextcladePangoLineage=BQ.1.1.13&

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As this appears to have faded away, with almost no detections over the past month, and strongly negative growth in Peru and world wide relative to its parent, this can be closed for now. Please re-propose or request reopening should this clade strongly reemerge in the future.
