### ISSUE TITLE
XBB.1.5 sublineage with ORF1b:E1264D, fast growing in Maryland, US (>90 seq)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1598]
ORF1b:E1264D is also in Gamma.

https://cov-spectrum.org/explore/United%20States/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3Axbb.1.5*%26orf1b%3A1264d&

![XBB 1 5+ORF1bE1264D](https://user-images.githubusercontent.com/115189228/215613784-79b35a54-97bb-48b2-af02-05881213a59e.png)
![Growth](https://user-images.githubusercontent.com/115189228/215613796-656807d6-ad0d-4117-92e1-de4f65685bf4.png)

**Comment by oobb45729** [comment]
![U](https://user-images.githubusercontent.com/115189228/215624099-f1c90cb0-8bf1-4e32-8ba4-b3d7761f8c41.png)

Query: T17124C+ORF1b:E1264D

**Comment by corneliusroemer** [comment]
Just Maryland is very suspicious, also that tree is messed up. Could well be an artefact.

**Comment by corneliusroemer** [comment]
Look how it went up and down in Maryland over the past 6 months, this is exactly the signature of an artefact

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/25161793/215625891-81aec366-7e6b-4639-bba1-efde552a9f68.png">

It's very bumpy, present only in some countries or even states. Classic artefact signature.

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/25161793/215625919-59218d5c-623d-4160-b8f8-37555ca9e9b6.png">

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/25161793/215625924-ee52caae-73fb-49e6-b25e-46ae3eb02c1e.png">

**Comment by corneliusroemer** [comment]
I'm wondering though where this artefact comes from. Primer trimming?

**Comment by FedeGueli** [comment]
> I'm wondering though where this artefact comes from. Primer trimming?

@josetteshoenma solved one similar artefact in the past contacting the submitting lab , in that case was a a mutation of BA.1 frequently and sparsely found in BA.2 in Germany. I dont recall exactly how it was happening.
