### ISSUE TITLE
Fast growing DY.1 sublineage with S:K147E emerged in Yunnan (36 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1599]
I was awaiting the designation of DY.1 to propose this sublineage of it with S:K147E .

**Defining mutations**: DY.1 > Orf1a:M315V (A1208G),Orf1b:T1637I  C18377T, S:K147E (A22001G) 

**Tree**:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2825e_844360.json?c=userOrOld&label=id:node_7482315
<img width="1148" alt="Schermata 2023-01-30 alle 23 49 23" src="https://user-images.githubusercontent.com/87669813/215614002-77173b52-a974-42ef-806f-fcc06e015b1f.png">

**Gisaid query**:  Spike_K147E,Spike_A570S,M_D3N

**Sequences**: 36
EPI_ISL_16334622, EPI_ISL_16355494, EPI_ISL_16377971,
EPI_ISL_16561148, EPI_ISL_16604910, EPI_ISL_16610765,
EPI_ISL_16610778, EPI_ISL_16610866, EPI_ISL_16610869,
EPI_ISL_16635615, EPI_ISL_16635972, EPI_ISL_16641629,
EPI_ISL_16641640, EPI_ISL_16641645, EPI_ISL_16641647,
EPI_ISL_16641651, EPI_ISL_16641656, EPI_ISL_16641665,
EPI_ISL_16641672, EPI_ISL_16641678, EPI_ISL_16646032,
EPI_ISL_16646048, EPI_ISL_16646050-16646051, EPI_ISL_16646058-16646059,
EPI_ISL_16646061-16646063, EPI_ISL_16646065-16646066, EPI_ISL_16646068,
EPI_ISL_16646087, EPI_ISL_16709101, EPI_ISL_16719084,
EPI_ISL_16723086

This lineage was also independently spotted by @real_Fearuncle ([here](https://twitter.com/real_Fearuncle/status/1619850529311686659?s=20&t=_6rWT9m1ED0krSVbjO8sPA
))

**Comment by HynnSpylor** [comment]
great proposal! I am also tracking this sublineage. Maybe more seqs in next few days.
![QQ截图20230131115238](https://user-images.githubusercontent.com/121703496/215659651-10e3af0c-c4a0-4195-ace1-6e4c0a7423f3.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage DY.1.1 with 0 newly designated sequences, and 9 updated from DY.1. Defining mutations  A1208G (ORF1a:M315V), C18377T (ORF1b:T1637I), A22001G (S:K147E) (following G23270T (S:A570S)).
