### ISSUE TITLE
New BF.7.14 sublineage defined by S:S366A 20 viruses circulating in China and maybe in Japan

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1601]
I noticed a subliNEage of BF.7.14 defined by S:S366A

DEFINING MUTATIONS: BF.7.14 > S:S366A (T22658G)

TREE:
<img width="1136" alt="Schermata 2023-01-31 alle 09 13 06" src="https://user-images.githubusercontent.com/87669813/215703422-c12eb7e9-a29a-4e5d-836b-17dc0cfd2b70.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18368_8cc910.json?c=userOrOld&label=id:node_7001284

GISAID : Spike_S366A,NS7A_H47Y,-M_I82T

SEQUENCES: 11

EPI_ISL_16506508, EPI_ISL_16598345, EPI_ISL_16598355,
EPI_ISL_16598369, EPI_ISL_16598409, EPI_ISL_16604593,
EPI_ISL_16616356, EPI_ISL_16616360, EPI_ISL_16713305,
EPI_ISL_16713307, EPI_ISL_16713310

COUNTRIES : China ( Shandong, Jilin, Heilongjang) , South Korea (via travellers from china), while the two japanese sequences both come from Hospitalized patients and they DONT appear to be travel related.

**Comment by FedeGueli** [comment]
14 samples as today last 3 came from Shandong

**Comment by FedeGueli** [comment]
17 samples last three came from Shanxi

**Comment by FedeGueli** [comment]
This lineage gone stale

**Comment by FedeGueli** [comment]
17 viruses but last one came from South Korea. From jan 1 there were 236 samples uploaded from travellers from China to South Korea and 2 of them were of this sublineage at a distance of some weeks.

Even if i dont trust that prevalence in China could be 1% but maybe this one is circualting at low levels. Reopening it to further monitor it

**Comment by FedeGueli** [comment]
20 sequences of this one as today.

**Comment by Mild1-ai** [comment]
I see this issue being closed. Is this issue designated?

> 20 sequences of this one as today.

**Comment by FedeGueli** [comment]
I closed this one cause still too slow.

**Comment by AnonymousUserUse** [comment]
@FedeGueli 
So if an issue is closed without designation, please close as not planned instead of close as completed. That would be more clearly.

**Comment by FedeGueli** [comment]
only Pango team could differentiate between completed and not planned. If the author does it results as completed.

**Comment by FedeGueli** [comment]
This kept circulating , there is a recent cluster from Heilongjiang in April. 32 seqs
