### ISSUE TITLE
XBB.2 clusters with S:S486P

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1603]
There appear to be 2 distinct XBB.2 clusters with S:S486P. But with 19 and 13 sequences each it's not entirely clear what to do about them at this point.

Cluster 1 with 13 sequences to date has T23018C directly on the XBB.2 polytomy. Geographic focus is Spain with export to Denmark and Germany.

There's a (probably artefactual) reversion of S:A83V in 3 Spanish sequences. I'm not 100% convinced that this lineage is real, probably worth waiting for it to get some more sequences to be sure.

<img width="1590" alt="image" src="https://user-images.githubusercontent.com/25161793/215764715-eea5f4d2-0201-4130-98d6-f6dd3b04f449.png">

Cluster 2 has 19 sequences, mostly India (8x KA, 1x GJ) and USA (4xDE/1xVA/2xCA) with singlets from Singapore and Indonesia.

It's on a long branch, starting with C27431T (on which there are also a few Australian/Japanese/Swedish) sequences, followed by C16342T, C23123T [16342 is a reversion to reference, the other one is S:P521S] - this branch was sequenced in India-KA a few times, suggesting the lineage evolved there, followed by, C4234T, and then G6536A and C23018C and G29706T. The A3754G flip flops for the US sequences and isn't found in the rest - so that may actually be a sublineage then 

Sequences are from a variety of countries and given the long branch with relatively few apparent reversions this lineage looks very real. Given relatively few recent sequences from India, this could actually be a major lineage there at the moment.

I'm puzzled by the reversion - it appears real but reversions have been relatively rare so I am somewhat skeptical still, but overall this seems worth designating.

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/25161793/215766248-74146aa6-1956-46b0-bc00-354681e4e6fb.png">

Any thoughts? Do any of the mutations ring a bell re artefacts? @AngieHinrichs

**Comment by FedeGueli** [comment]
@corneliusroemer i found the new optimal query fopr the undesignated branch of this issue (the "spanish one":
 **-NS8_G8,Spike_D253G,Spike_F486P,Spike_Q183E*,-NS7a_A13V + Nuc: -C5144T,-T6175A, -T4579A**

It finds **17 samples** now (02-02-23): 
<img width="1147" alt="Schermata 2023-02-02 alle 10 44 07" src="https://user-images.githubusercontent.com/87669813/216289210-8efaa81b-a5d9-4335-bc1d-b53a58e1e503.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_bf5e_b84a90.json?c=country&label=id:node_7962963

This has been Newly found in Germany.
i think it iwould be better to designate it.

**Comment by AngieHinrichs** [comment]
> Do any of the mutations ring a bell re artefacts? @AngieHinrichs

Not particularly.  The reversion on 16342 seems real.

> There's a (probably artefactual) reversion of S:A83V in 3 Spanish sequences.

Yeah, I see a lot of apparent reversions on S:83 (21810) scattered across XBB which is suspicious, and by eye they seem to all come from reversion-prone labs.

**Comment by corneliusroemer** [comment]
Thanks @AngieHinrichs! One idea I've had is to compile a reversion proneness index by lab to add as a coloring to help find real reversions. Right now it seems that the overwhelming majority are artefacts and it's hard to spot the real ones in the noise.

Given continued growth of the "Spanish" cluster I agree it makes sense to designate it in the next few days. Not urgent but good to add to the list of XBB.1.5-like lineages.

**Comment by FedeGueli** [comment]
@corneliusroemer this should be closed as completed @InfrPopGen
