### ISSUE TITLE
BA.4.1 sublineage with S:V445A, S:R346T, S:K147E circulating in Denmark 110 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1606]
Here i want to propose an undesignated member of variant soup this time evolved from a BA.4.1 background.

Defining mutations:
BA.4.1 + > G29179A > S:V445A( T22896C) > C10615T, C27389T, ORF7a:T28I  (C27476T) > T15978C > S:R346T (G22599C) > S:K147E (A22001G), ORF8:Q18L (A27946T)

Gisaid and Covspectrum query : C27389T, A27946T, G29179A, T22896C, C10615T, C27476T, T15978C, G22599C, A22001G

Tree:
<img width="1161" alt="Schermata 2023-01-31 alle 18 32 07" src="https://user-images.githubusercontent.com/87669813/215838182-8e5d8cb5-e64d-4c22-a4c0-6175370fb36a.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12b67_94a6f0.json?c=userOrOld

Looking at growth advantage , it has a slight disadvantage versus the new baseline ideated by @josetteshoenma which collectes all fast lineages:
https://cov-spectrum.org/explore/Denmark/AllSamples/Past2M/variants?variantQuery=%21+S%3A69-+%26+%21+S%3AF486V+%26+%28S%3AL452R+%7C+S%3AF486P%29&nucMutations1=C27389T%2CA27946T%2CG29179A%2CT22896C%2CC10615T%2CC27476T%2CT15978C%2CG22599C%2CA22001G&analysisMode=CompareToBaseline&
<img width="1088" alt="Schermata 2023-01-31 alle 18 29 05" src="https://user-images.githubusercontent.com/87669813/215837380-aa4dc8e3-8ddb-4f49-b2aa-1bc306be1cdf.png">

**Comment by Sinickle** [comment]
![image](https://user-images.githubusercontent.com/94097102/215840693-12b6f887-2257-434a-85c8-3a69472ad862.png)

This variant had an upwards signal in the week 2 2023 report from Denmark's SSI
https://covid19.ssi.dk/overvagningsdata/ugentlige-tendenser-for-covid-19-og-andre-luftvejsinfektioner

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.4.1.11 with 106 newly designated sequences, and 0 updated. Defining mutations A27946T (ORF8:Q18L), A22001G (S:K147E)(following G22599C (S:R346T)).

**Comment by corneliusroemer** [comment]
I would have probably designated the BA.4.1.11 after 346T, not requiring 147E, as the part with 346T and 445A is not negligible. The 147E part is only ~50% of the the 346T branch.

Now the 346T/445A part can't get a name. This isn't a big issue here as this lineage is not growing anymore but in the future better to designate broadly rather than narrowly.
