### ISSUE TITLE
BF.7.14 with C20703T (171 samples, 21% growth rate related to BF.7.14 )

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1607]
Sub-lineage of: BF.7.14
cov-spectrum query: BF.7.14*+C20703T

gisaid query: Spike_R346T,NS7a_H47Y,Spike_C1243F, C20703T

Earliest sequence: 2022-11-26 (EPI_ISL_16277977)
Most recent sequence: 2023-01-26 (EPI_ISL_16740873)
Countries circulating: China, Singapore(4 imported 1 local), USA,  Hong Kong, Italy, Japan(7 imported 1 local) and travel-related only in France and South Korea.

<img width="1370" alt="Screen Shot 2023-02-01 at 14 45 48" src="https://user-images.githubusercontent.com/10445944/215975444-83b8eba8-b616-4efc-a31c-45bd366471de.png">

<img width="1151" alt="Screen Shot 2023-02-01 at 14 49 44" src="https://user-images.githubusercontent.com/10445944/215975367-df1c9a3d-ad44-40c8-8d24-de5fdfe65142.png">

Genomes:
EPI_ISL_16259497, EPI_ISL_16277977, EPI_ISL_16283882,
EPI_ISL_16283964, EPI_ISL_16327533, EPI_ISL_16350563,
EPI_ISL_16350572, EPI_ISL_16376696, EPI_ISL_16390380,
EPI_ISL_16390390, EPI_ISL_16428125, EPI_ISL_16428141,
EPI_ISL_16431223, EPI_ISL_16436272, EPI_ISL_16438300-16438301,
EPI_ISL_16438303-16438305, EPI_ISL_16468021, EPI_ISL_16481860,
EPI_ISL_16483068, EPI_ISL_16494576, EPI_ISL_16506419,
EPI_ISL_16506515, EPI_ISL_16514015, EPI_ISL_16522220,
EPI_ISL_16522246, EPI_ISL_16524051-16524052, EPI_ISL_16524064-16524065,
EPI_ISL_16534532, EPI_ISL_16534536, EPI_ISL_16534547,
EPI_ISL_16534812, EPI_ISL_16561133, EPI_ISL_16568789,
EPI_ISL_16568849-16568850, EPI_ISL_16579359, EPI_ISL_16595764-16595765,
EPI_ISL_16595782-16595783, EPI_ISL_16595785, EPI_ISL_16596493,
EPI_ISL_16597093, EPI_ISL_16597210, EPI_ISL_16598354,
EPI_ISL_16598374, EPI_ISL_16598413, EPI_ISL_16598595,
EPI_ISL_16599067, EPI_ISL_16599074, EPI_ISL_16599076,
EPI_ISL_16599079-16599080, EPI_ISL_16604397, EPI_ISL_16604405,
EPI_ISL_16604410, EPI_ISL_16604435, EPI_ISL_16604438,
EPI_ISL_16604454, EPI_ISL_16604540, EPI_ISL_16604582,
EPI_ISL_16604588, EPI_ISL_16604619, EPI_ISL_16604631,
EPI_ISL_16604637, EPI_ISL_16604660, EPI_ISL_16604663,
EPI_ISL_16604723, EPI_ISL_16604800, EPI_ISL_16604806,
EPI_ISL_16604812, EPI_ISL_16604819, EPI_ISL_16604849,
EPI_ISL_16604862, EPI_ISL_16604865, EPI_ISL_16604929,
EPI_ISL_16610865, EPI_ISL_16610906, EPI_ISL_16616940,
EPI_ISL_16617028, EPI_ISL_16617235-16617236, EPI_ISL_16617258,
EPI_ISL_16633795, EPI_ISL_16634384, EPI_ISL_16634427,
EPI_ISL_16634450, EPI_ISL_16634485, EPI_ISL_16634553,
EPI_ISL_16634597, EPI_ISL_16634671, EPI_ISL_16635177,
EPI_ISL_16635238, EPI_ISL_16635287, EPI_ISL_16635313-16635314,
EPI_ISL_16635316, EPI_ISL_16635332, EPI_ISL_16635465,
EPI_ISL_16635547, EPI_ISL_16635608, EPI_ISL_16635667-16635668,
EPI_ISL_16635670, EPI_ISL_16635716-16635717, EPI_ISL_16635719-16635720,
EPI_ISL_16635819, EPI_ISL_16635821, EPI_ISL_16635844,
EPI_ISL_16636174, EPI_ISL_16636179, EPI_ISL_16636183,
EPI_ISL_16636191, EPI_ISL_16636221, EPI_ISL_16636225,
EPI_ISL_16636237, EPI_ISL_16636255, EPI_ISL_16641616,
EPI_ISL_16641618, EPI_ISL_16650354, EPI_ISL_16669481,
EPI_ISL_16670996, EPI_ISL_16671000, EPI_ISL_16674642,
EPI_ISL_16698438-16698440, EPI_ISL_16698452, EPI_ISL_16698458,
EPI_ISL_16698467, EPI_ISL_16702104, EPI_ISL_16709035,
EPI_ISL_16709064, EPI_ISL_16709448, EPI_ISL_16709461,
EPI_ISL_16709474, EPI_ISL_16711124, EPI_ISL_16711675,
EPI_ISL_16711696, EPI_ISL_16711732, EPI_ISL_16711735,
EPI_ISL_16711742, EPI_ISL_16711760, EPI_ISL_16711766,
EPI_ISL_16711810, EPI_ISL_16711861, EPI_ISL_16712016,
EPI_ISL_16717143, EPI_ISL_16719090, EPI_ISL_16720356,
EPI_ISL_16723078, EPI_ISL_16723167, EPI_ISL_16723169,
EPI_ISL_16723171, EPI_ISL_16735343, EPI_ISL_16740779,
EPI_ISL_16740804, EPI_ISL_16740836-16740838, EPI_ISL_16740845-16740846,
EPI_ISL_16740864, EPI_ISL_16740873

**Comment by corneliusroemer** [comment]
Need to take the growth advantages with a big pinch of salt. There's not much signal here. Also, a synonymous mutation is unlikely to cause much of an intrinsic, non-random growth advantage change compared to parent.

**Comment by aviczhl2** [comment]
This is designated as BF.7.14.5, so time to close this issue.
