### ISSUE TITLE
Possible DJ.1.1 sublineage with ORF1ab: T6038I mutation circulating mainly in Peru

### ISSUE THREAD

**Issue by vekahurtado** [cov-lineages/pango-designation#1608]
**A) Description**
New possible DJ.1.1 sub-lineage with ORF1ab:T6038I (Nuc: C18377T) mutation proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**B) Earliest sequence:** 2022-10-20
hCoV-19/Peru/LOR-INS-31756/2022

**C) Most recent sequence:** 2022-12-27
hCoV-19/Peru/TAC-INS-38420/2022

**D) Countries circulating:**
Peru, USA, Chile, Begium, Argentina

**E) Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/10569570/genomes.txt)

**F) Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3bd22_ac33f0.json?c=gt-ORF1ab_6038&label=id:node_6798804&tl=country
<img width="1588" alt="DJ 1 1-ORF1ab-T6038I" src="https://user-images.githubusercontent.com/114951702/216341670-d5e539f6-6d26-49ba-85f5-651ecae8e720.png">
<img width="1586" alt="DJ 1 1-ORF1ab-T6038I-COVSPETRUM" src="https://user-images.githubusercontent.com/114951702/216341718-36ff3c64-3034-4b22-9aba-e0b13b53f7f6.png">

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there have been no detections for two months, and there is no longer any relative growth advantage in South America, this can be closed for now. Please request re-opening or re-propose should this clade show marked growth in the future.
