### ISSUE TITLE
Bn.1.3 with S:V1122M with high prevalence in Laos (43 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1609]
there may be a sublineage of BN.1.3 with high prevalence in Laos.
I spotted it between unlabeled variant soup sequences likely imported in China.

Laos sequenced only 1047 samples from the beginning of the pandemic and only 48 in the past three months:
17 out of 48 belong to this proposed sublineage:
![](https://cov-spectrum.org/api/ppretty/get/18/37/1837cf77edc50441a746746dd2767d80874a1350c2e51f61bc83ea0ec26d2a1c.png)
https://cov-spectrum.org/explore/Laos/AllSamples/from=2022-10-31&to=2023-01-31/variants?aaMutations=S%3AV1122M&nucMutations=C7039T&nextcladePangoLineage=BN.1.3*&nextcladePangoLineage1=BN.1.3.2*&

**Defining mutations**:
BN.1.3 >Orf1a:H110Y ( C593T )> C7390A > M:R174Q (G27043A) > C7039T, S:V1122M (G24926A)

**Tree:**
<img width="1155" alt="Schermata 2023-02-02 alle 15 29 26" src="https://user-images.githubusercontent.com/87669813/216352065-a54501bc-bbab-4383-903e-535e30eeae10.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_a414_bc5950.json?c=userOrOld&label=id:node_8113175

**CovSpectrum/ Gisaid query**: C7039T,C7039T, G24926A,C26078T

Sequences:
EPI_ISL_15857548, EPI_ISL_15941396, EPI_ISL_15984232,
EPI_ISL_15984325, EPI_ISL_16017422-16017424, EPI_ISL_16017426,
EPI_ISL_16079389-16079391, EPI_ISL_16079396-16079400, EPI_ISL_16218291,
EPI_ISL_16250660, EPI_ISL_16327645, EPI_ISL_16340964,
EPI_ISL_16394192, EPI_ISL_16419293, EPI_ISL_16466171,
EPI_ISL_16468176, EPI_ISL_16485096, EPI_ISL_16506985,
EPI_ISL_16514242, EPI_ISL_16548465, EPI_ISL_16641047-16641048,
EPI_ISL_16675658, EPI_ISL_16700104, EPI_ISL_16700109,
EPI_ISL_16700115, EPI_ISL_16715007, EPI_ISL_16723888,
EPI_ISL_16750674, EPI_ISL_16758689, EPI_ISL_16758920,

**Comment by FedeGueli** [comment]
43 sequences last samples come from local case in South Korea where it likely started to circulate.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As this has been showing negative growth relative to its parent in Laos/Asia over the past few months, this can be closed at the moment. Nevertheless, please re-propose or request re-opening should this lineage show clear signs of relative growth in the future (e.g., explode in South Korea).

**Comment by FedeGueli** [comment]
47 sequences as today, the last one sampled in Thailand from a traveller from China
