### ISSUE TITLE
USA B.1.X lineage with Spike NTD insertion (ins214QAS), T478K, E484K, and NSP6 del106-108

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#161]
**New proposed lineage
By Tom Peacock**

**Description
Sub-lineage of:** B.1
**Earliest Sequence:** 2021-01-19
**Latest Sequence:** 2021-04-26

**Countries circulating:** USA (16 genomes; New York, New Jersey), Dominican Republic (1 genome), Denmark (1 genome)

**Description:
Conserved Spike mutations -** Δ69-70, M153T, 214insQAS, T478K, E484K, D614G, T859N, D936Y

**Conserved non-Spike mutations -** NSP2 – T439I; NSP6 – Δ106-108; NSP7 – L56F; NSP12 – L323P; NSP13 – P47T; ORF3a – Q213K, P240S, 257framshift-IQ-STOP; ORF8 – I9T; N – I157V

Although most of the genomes were collected several months ago a few have been uploaded in the last few weeks suggesting this is probably still out there - mainly flagged because of the NTD insertion (very similar to A.2.5 and B.1.214.2 lineages) and the Spike RBD mutations (T478K and E484K).

**Genomes:**
[B1X 214QAS insert lineage.csv.txt](https://github.com/cov-lineages/pango-designation/files/6884731/B1X.214QAS.insert.lineage.csv.txt)

**Proposed lineage name:** B.1.X

**Comment by chrisruis** [comment]
Thanks @thomasppeacock. It looks like the most recent sequence from this lineage in the latest UShER tree is still from 26/04/2021. We wouldn't typically designate a new lineage if it would be unobserved (not seen in the last 3 months) at the time of designating. So I'll add a monitor label to this for now and we can check back soon and see if there's any more recent sequences added

**Comment by chrisruis** [comment]
Just had another look in the latest UShER tree and it doesn't look like there's any more sequences in this clade. So we won't designate a new lineage at this stage. Thanks again @thomasppeacock for submitting

**Comment by thomasppeacock** [comment]
@chrisruis New sample from Puerto Rico last month (EPI_ISL_3851289). Groups with the others but on a long branch length which might imply some continuous unsampled cirulation. Only singlet for now but might be worth reopening and chucking back into monitoring see if anything else appears?

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1774d_d5620.json

**Comment by chrisruis** [comment]
Hi @thomasppeacock, happy to do that!

**Comment by thomasppeacock** [comment]
nothing else has popped up so will close for now unless some more recent sequences appear

**Comment by thomasppeacock** [comment]
And another couple sequences of this lineage from Massachusetts earlier this month:

EPI_ISL_5720730
EPI_ISL_5721629

latest Usher tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2222c_ebbd40.json?c=pango_lineage_usher

Interesting the latest samples form a subcluster away from the main (now historic) cluster. This subclsuter had some additional mutations, most interesting Q677R (as well as A520S). Q677R which lies in the furin site and might suggest a clue as to how this lineage is continuing to compete at a low level with Delta...

**Comment by jpkamil** [comment]
Yup. I agree re Q677R and IMO this is a really interesting little lineage.  Sorry for opening a new issue -- wish I'd noticed this one.

**Comment by chrisruis** [comment]
Thanks @thomasppeacock for keeping an eye on this one! We've added this in as B.1.639 in [v1.2.93](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.93) and included both the more historic and more recent clades in B.1.639. This therefore starts on the branch with T22020C (S:M153T), C22995A (S:T478K), C24138A (S:T859N), G24368T (S:D936Y), T27919C (Orf8:I9T), A28742G (N:I157V)
