### ISSUE TITLE
BQ.1.1.32 sublineage with S:T547K (440 seqs from USA, UK, France, Germany, Canada, China)

### ISSUE THREAD

**Issue by emily-smith1** [cov-lineages/pango-designation#1612]
### Description
**Sublineage of:** BQ.1.1.32
**Earliest sequence:** 2022-11-08 (USA-CA)
**Most recent sequence:** 2023-01-24 (USA-CA)
**Countries circulating:** USA, UK, France, Germany, Canada, China
**GISAID query:** Spike_K444T,Spike_F486V,Spike_R346T,Spike_M153I,Spike_y144del,Spike_T547K

The GISAID query returns 440 sequences, but almost half are missing from the UShER global tree. However, all sequences in GISAID receive a BQ.1.1.32 lineage assignment when uploaded to UShER. 

### Evidence

**UShER link**: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a6d5_c5ce30.json?label=id:node_3342795

Annotated by Spike position 547
![image](https://user-images.githubusercontent.com/84812104/216488310-fa233695-88fd-4d4f-afe6-bc1d1ccc8f1e.png)

Zoomed in to potential sublineage
![image](https://user-images.githubusercontent.com/84812104/216488324-c93c77aa-1d5b-4798-beb1-635fc3295d49.png)

35% growth advantage worldwide for the last 3 months (BQ.1.1.32 + S:T547K)
![image](https://user-images.githubusercontent.com/84812104/216488350-df6ab4ad-a45c-44ac-8fc4-71f4efc42a52.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage DT.2 with 392 newly designated sequences, and 19 updated from BQ.1.1.32. Defining mutation C23202A (S:T547K) (following G22021A (S:M153I)).
