### ISSUE TITLE
BA.5.2.25 sub lineage with S:R346T,S:N460K (10 samples, 6 countries, 3 continents)  

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#1613]
Joint work with @Boltyansky and MatrixDNA

**Description**

Sublineage of: BA.5.2.25
Earliest sequence: 2.11.22 (Belgium) 
Most recent sequence: 2023-01-24 (Canada)
Countries circulating: Belgium,Canada,France,Singapore,Luxemburg,Netherlands

**Evidence**

Usher link :

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_66a8_c2f370.json?branchLabel=Spike%20mutations&c=country&label=id:node_7265620

![image](https://user-images.githubusercontent.com/80166370/216545411-edbad551-57f6-4397-bce1-718756bc7a4c.png)

GISAID ref :
EPI_ISL_16529664
EPI_ISL_16419949
EPI_ISL_16238888
EPI_ISL_16640323
EPI_ISL_16581837
EPI_ISL_16550013
EPI_ISL_16534533
EPI_ISL_16099420
EPI_ISL_16497766
EPI_ISL_16158680

**Comment by corneliusroemer** [comment]
Small saltation, good spot!

**Comment by corneliusroemer** [comment]
How is this different from DB.1 (BA.5.2.25.1) which also has S:R346T and S:N460K?

**Comment by shay671** [comment]
DB.1 evolved from a BA.5.25 mediator branch having C27741T which is missing in the samples here.

**Comment by corneliusroemer** [comment]
Hmm, that sounds more like artefact to me. would want to see it on a tree and Nextclade

**Comment by AngieHinrichs** [comment]
Beware the "S:N460K"-level equivalence -- DB.1 has T22942G but these samples have T22942A.

DB.1 has C27741T as @shay671 pointed out and also C22450T, and these samples have neither of those.  However, these samples have the following mutations not seen in DB.1 so far: A2182G, C2334T, T14565G, T16950A, C18744T, G19542T, C26151T, and G28109A.

**Comment by shay671** [comment]
another sample uploaded for this : EPI_ISL_16866848 (France, collected on 30.01.23)

We got a monophyletic source, 11 samples from 6 countries and a genetic background that should alert. 

Most probably, this will not be the next world dominant variant or even close to that. But if the goal is to track lineages that **might** be problematic or needed for analysis of convergence, i would recommend designation.

**Comment by FedeGueli** [comment]
Agree with Shay. we have designated quite everything with 460K and this misses S:444T that was defining in DB.1.

Interestingly while 346T and 460k appear to be fixed the global share of 444 is going down maybe meaning its escape advantage has some side effect. SO i am not sure a 346/460 combo could not be more advantageous than the 444/460 combo or the tris 346/444/460

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage DB.3 with 10 newly designated sequences, and 0 updated. Defining mutations C2334T (ORF1a:A690V), T14565G, T16950A, G19542T (ORF1b:M2025I), G22599C (S:R346T), T22942A (S:N460K), C26151T (following G28109A).
