### ISSUE TITLE
BQ.1.1.38 sublineage with S:A348S - 41 sequences South Africa, Denmark, Nyc - as 24-02-23

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1618]
BQ.1.1.38, (spotted by @ryhisner very early months ago) is accordingly to Collection24 ( the covspectrum collection of all the designated lineages) the fastest among the BQ* descendants along with the italian BQ.1.1.37 ( the one defined by ins:S:247SAE S:248D )
<img width="1293" alt="Schermata 2023-02-04 alle 21 06 16" src="https://user-images.githubusercontent.com/87669813/216787590-e84d4885-28b2-45f2-865a-d9ed62f6ff01.png">
https://cov-spectrum.org/collections/24

BQ.1.1.38 is mainly split in two : the uppper part of the tree defined by a branch with S:A701V is internationally spread
while the bottom part of the tree is largely made by samples from south africa from mutliple branches showing high diversity pointing at some sort of sustained circulation there:
<img width="1143" alt="Schermata 2023-02-04 alle 21 09 11" src="https://user-images.githubusercontent.com/87669813/216787710-03cf7a27-fa1f-48bf-8f16-948a8e8113a1.png">

While weighing BQ.1.1.38 we should be aware that the "international branch with S:A701V is much slower than the rest of the lineage, suggesting maybe a founder effect for its wider spread in other countries
<img width="900" alt="Schermata 2023-02-04 alle 21 10 09" src="https://user-images.githubusercontent.com/87669813/216787749-dfcbcb99-5441-4826-985b-a9745c203d1b.png">
https://cov-spectrum.org/explore/World/AllSamples/from=2022-12-15&to=2023-02-04/variants?aaMutations=S%3AA701V&nextcladePangoLineage=BQ.1.1.38*&nextcladePangoLineage1=BQ.1.1.38*&analysisMode=CompareToBaseline&

So i noticed immediately the branch defined by S:A348S and digging into it i spotted that its sublineages acquired more Spike mutations as S:T470I (1seq) or S:S494P (4 seqs)
<img width="1126" alt="Schermata 2023-02-04 alle 21 14 20" src="https://user-images.githubusercontent.com/87669813/216787885-e02670da-656a-4810-87fd-624078a80915.png">

Defining mutations : 
BQ.1.1.38 > C421T > S:A348S (G22604T)

Usher Tree:
<img width="1154" alt="Schermata 2023-02-04 alle 21 15 38" src="https://user-images.githubusercontent.com/87669813/216787933-0a0b7658-9726-418e-aa2c-2a8533a96489.png">

Gisaid query: Spike_A348S,Spike_N856S,N_E136D

Sequences : 14 
EPI_ISL_16376011-16376013, EPI_ISL_16376016, EPI_ISL_16578154,
EPI_ISL_16580278, EPI_ISL_16649783, EPI_ISL_16713768,
EPI_ISL_16749592, EPI_ISL_16750770, EPI_ISL_16750826,
EPI_ISL_16750870, EPI_ISL_16750897, EPI_ISL_16823490,

Countries: Even if it is just 14 sequences it has been already exported to Denmark and NYC

**Comment by corneliusroemer** [comment]
Yep, also noticed this due to high predicted "combined fitness" of ACE2 binding and immune escape per Bloom lab calculator as implemented in Nextclade.

Thanks for looking at the Usher tree, looks pretty clean so should enable us to go and designate a few lineages. We're getting very few sequences from Africa recently so it makes sense to designate there even with only relatively few sequences, so far.

**Comment by FedeGueli** [comment]
Thx @corneliusroemer

**Comment by FedeGueli** [comment]
@corneliusroemer it jumped to 23 with just South African sequences .

**Comment by FedeGueli** [comment]
26 sequences as today

**Comment by FedeGueli** [comment]
26 sequences. it is clearly losing the game versus XBB.1.5. Interestingly these two last sequences both have S:N440R.

**Comment by FedeGueli** [comment]
41 sequences . Its prevalence in February hanging around 1%, likely it cannot compete with XBB.1.5 but clearly fast enough to keep circulating there.

@corneliusroemer

**Comment by FedeGueli** [comment]
it seems dead or better saying killed by XBB.1.5. @corneliusroemer dunno if it makes sense to designate it.

**Comment by FedeGueli** [comment]
@corneliusroemer designated it: EW.3 
https://github.com/cov-lineages/pango-designation/commit/911be6085b5055e1d11a4968a2b6f74a09072c00
