### ISSUE TITLE
XAY.3 sublineage with ORF1a:T2611I, ORF1a:T4355I, and ORF1b:D2087V in Austria (5 sequences and 11 potential spike only sequences)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1619]
Description
Sub-lineage of: XAY.3
Earliest sequence: 2022-12-05 (Austria)
Most recent sequence: 2023-01-23 (Austria)
Countries circulating: Austria
Number of sequences: 5 (There are also 11 spike only sequences that potentially belong to this lineage)
Query: C8097T, C13329T, A19727T
Substitutions on top of XAY.3: ORF1a:T2611I(C8097T), ORF1a:T4355I(C13329T), ORF1b:D2087V(A19727T)
![1](https://user-images.githubusercontent.com/115189228/216793856-77235a42-01c8-447f-93dc-092dba1818b7.png)

https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=C8097T%26C13329T%26A19727T&

The (n=4) cluster further acquired C3156T(ORF1a:A964V), T10606C, T11751C(ORF1a:L3829P), C21575T(S:L5F).
This one is weird. An unusual amount of ORF1ab mutations were accumulated in a relatively short period of time.
There are also 11 spike only sequence of XAY with S:L5F in Austria recently. They might belong to this lineage as well.

https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXAY*+%26+S%3AL5F+%26+%21ORF1a%3AI3126T&

**Comment by AngieHinrichs** [comment]
FYI position 21575 (S:5) is masked in the UShER tree because it is in the [Problematic Sites](https://github.com/W-L/ProblematicSites_SARS-CoV2) set.

**Comment by oobb45729** [comment]
I think S:L5F is similar to ORF1a:L3606F, right? Extremely homoplasic but most of them are real.

**Comment by corneliusroemer** [comment]
5 (+11) is a bit few for now, let's see how things develop within XAY.3 for a bit

**Comment by AngieHinrichs** [comment]
> I think S:L5F is similar to ORF1a:L3606F, right? Extremely homoplasic but most of them are real?

I think so, yeah.  21575 (S:5) along with 11083 (ORF1a:3606) were added to the set very early on.  [11083 was the most striking one, and what got me pulled into SARS-CoV-2 phylogenetics along with Russ & Yatish before there was even a plan for UShER!]  Cases like this (and deletions) are when I envy Nextstrain's augur pipeline's ability to mask some positions while constructing the tree, but then add back their alleles when making the final annotated tree for display in auspice.  🙂

**Comment by corneliusroemer** [comment]
> Cases like this (and deletions) are when I envy Nextstrain's augur pipeline's ability to mask some positions while constructing the tree, but then add back their alleles when making the final annotated tree for display in auspice.

It shouldn't be hard in principle to add the states at your tips for masked sites - sure this wouldn't be supper efficient as the information wouldn't be part of the usual MAT - but it could just be metadata for the few masked sites. Could be fairly efficiently encoded in a string. For positions [11083, 24753, 24843] you could encode them as "ATN" or something like that. Wouldn't be too bad to store some ~50 masked sites like that.

One should also be able to reconstruct the states at internal nodes, working backwards from the state of the tips with some easy parsimony heuristics.

**Comment by AngieHinrichs** [comment]
There are 265 problematic sites and 466 pairs of {node, site} for branch-specific masking at the moment.  But true, I could select a smaller subset of more interesting sites to keep in metadata.  And true, I could reimplement more bits and pieces of the Augur pipeline in the web interface and it's C so it could be pretty fast.  :)  Don't ask how soon I might actually get around to that though.
