### ISSUE TITLE
B.1.1.7 sub-lineage with spike A67V, E484K, K417R originating in Florida, USA

### ISSUE THREAD

**Issue by zach-hensel** [cov-lineages/pango-designation#162]
# B.1.1.7 sub-lineage with spike A67V, E484K, K417R originating in Florida, USA

Zach Hensel

## Description

Sub-lineage of: B.1.1.7
Earliest sequence: 1/April/2021
Most recent sequence: 13/July/2021
Number of sequences (number currently in UShER tree following the S:K417R event): 110
Mutations from parent: S:K417R (A22812G)
Countries circulating: USA (most in Florida, Oregon, and New York)

This sub-lineage appears to have emerged in Florida, USA based on sampling locations in the UShER tree built around the a sequence from 13/July/2021, USA/OR-OSPHL01315/2021|EPI_ISL_3048129|2021-07-13 - https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_596e2_ffb3d0.json?c=gt-S_67,484,417&label=nuc%20mutations:T17736C

## Potential significance in addition to S:E484K

* Alpha sub-lineage spreading in multiple US states and modestly growing as a fraction of sequences in the USA since introduction as the Alpha fraction has dropped dramatically overall.
* Possible significance of S:K417R -- conflicting evidence from experiments and modeling.
* S:A67V also appeared in the context of S:del69/70 in VOI B.1.525, and in B.1.258.22. It also appears in 42% of B.1.351.3 sequences; perhaps A67V plays the same role in both cases as both S:del69/70 and S:D80A are very close to S:67 in structural data.

## Genomes at the root of this sub-lineage

USA/OH-PLMI-HVJ7C-01116/2021|EPI_ISL_1716988|2021-04
USA/FL-CDC-ASC210071721/2021|MZ278025.1|2021-04-15
USA/NY-CDC-ASC210030639/2021|MZ283897.1|2021-04-22
USA/PA-CDC-STM-000060261/2021|MZ154623.1|2021-04-18
USA/MN-CDC-IBX933818260002/2021|MZ055054.1|2021-04-13
USA/FL-CDC-STM-000053145/2021|MZ059238.1|2021-04-10
USA/OH-PLMI-HVJ7C-01119/2021|EPI_ISL_1716991|2021-04
USA/FL-CDC-STM-000050015/2021|MZ009388.1|2021-04-03
USA/FL-CDC-ASC210040324/2021|MZ083595.1|2021-04-01
USA/FL-CDC-ASC210046984/2021|MZ083100.1|2021-04-05
USA/NY-CDC-QDX23997438/2021|MZ131260.1|2021-04-14
USA/MA-CDC-LC0055220/2021|MZ180987.1|2021-04-28
USA/NY-PRL-0510_00A01/2021|EPI_ISL_2106422|2021-05-05
USA/NY-UB-ECPHL-01058/2021|EPI_ISL_2662873|2021-04-28
USA/NY-UB-ECPHL-01056/2021|EPI_ISL_2662872|2021-04-28

## Evidence

![image](https://user-images.githubusercontent.com/23096983/127153495-33e272d5-cf26-424c-b04a-c84bb7b0d290.png)

## Proposed lineage name

B.1.1.7.x (and current alias), or B.1.1.7.x.y if designating parent E484K lineage separately in case it also goes in a different direction.

**Comment by zach-hensel** [comment]
I did not notice this when I suggested this, but I notice now that the most recent sequences in Oregon, e.g. EPI_ISL_2955395 have added Spike A701V, which is also in most of B.1.351 and about half of B.1.526.

**Comment by zach-hensel** [comment]
With no samples in August so far I'm going to optimistically close this.

**Comment by shay671** [comment]
Hi @zach-hensel 

4 samples were collected for this lineage in August : 
EPI_ISL_3696904
EPI_ISL_3753204
EPI_ISL_3769489
EPI_ISL_4019418

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4bac4_b54190.json?label=nuc%20mutations:C21762T

And much more samples were uploaded with collection date in late July. 

I agree with you that B.1.617.2 is outcompeting all the "old" variants but here we see something more like a variant based variant. The added mutational signature is something we haven't seen in B.1.1.7 so far. Personally i think that variant based variants are still a threat. Maybe somewhere there is an immunocompromised patient that the virus evolves in his body from B.1.1.7 (or other variant) and transforms to something new. We will see it as B.1.1.7 but it will be something else. 
Here, What we see is quite different from the evolvement of other variants as it evolved stepwise. And this is something even more alarming.

**Comment by zach-hensel** [comment]
Yes I saw there were a couple more sequences in August -- and I agree it's likely significant in that sort of way but I think not in a designated-lineage sort of way.
