### ISSUE TITLE
Another BA.5.2.48 sublineage with orf1a:T1788M (106 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1620]
Description
Sub-lineage of: BA.5.2.48
Earliest sequence: 2022-12-12 EPI_ISL_16617247
Most recent sequence: 2023-01-29 EPI_ISL_16723223
Countries circulating: China, Japan, Australia, Italy, travel-related-only in Singapore and South Korea
Number of sequences: 78
Query(both GISAID and cov-spectrum): C20762T, C12789T, G12111A, C5628T 
Substitutions on top of BA.5.2.48: ORF1b:T2432I(C20762T), ORF1a:T4175I(C12789T), ORF1a:S3949N(G12111A), ORF1a:T1788M(C5628T)

<img width="1112" alt="Screen Shot 2023-02-05 at 23 52 20" src="https://user-images.githubusercontent.com/10445944/216830445-5a52aad3-03cd-466b-89f5-97bafcd3cf77.png">

<img width="1400" alt="Screen Shot 2023-02-05 at 23 54 14" src="https://user-images.githubusercontent.com/10445944/216830451-81f4a09b-e060-46db-8530-4f5930fcb907.png">

Note that another undesigned branch of BA.5.2.48 also have orf1a:T1788M. 

[#1472 ](https://github.com/cov-lineages/pango-designation/issues/1472)

**Comment by FedeGueli** [comment]
Worth noting that Orf1a:T4175I is in XBB.1.9* too.

**Comment by aviczhl2** [comment]
> Worth noting that Orf1a:T4175I is in XBB.1.9* too.

Also in [BN.1.4.1](https://github.com/cov-lineages/pango-designation/issues/1417).

And orf1b:T2432I in [BA.5.10.1](https://github.com/cov-lineages/pango-designation/issues/1031)

**Comment by corneliusroemer** [comment]
I'd possibly designate more basal to keep the number of BA.5.2.48 from not getting too big. Maybe on ORF1a:S3949N for example. I'll have a look at BA.5.2.48 lineages in a bit. Thanks for the suggestion!

**Comment by HynnSpylor** [comment]
The definition may be considered carefully.  Notice that more sequences with ORF1ab:T1788M are without ORF1ab:T4175I.

![QQ截图20230207231423](https://user-images.githubusercontent.com/121703496/217285886-9da984a4-4982-4f02-baec-0d9de1cc75dd.png)
![QQ截图20230207231847](https://user-images.githubusercontent.com/121703496/217285865-1a009c41-5716-4c8e-bc23-3bd870db9932.png)

**Comment by AnonymousUserUse** [comment]
I think it is unlikely that those mutations have any real growth advantage, so it would be better to designate lineage that has a clear epidemiological event. In this case, the mutation ORF1b:T2432I (C20762T) coincides with the introduction into Hubei Province and therefore maybe designated. BA.5.2.48 + ORF1b:T2432I + ORF1a:T4175I + ORF1a:S3949N is just a main sublineage of BA.5.2.48 + ORF1b:T2432I without notable epidemiological event, at least not in provincial level.

![image](https://user-images.githubusercontent.com/113214374/218238572-9e57ecbd-8942-4b7f-b5cd-01d0201a1710.png)
