### ISSUE TITLE
XBB.1 +S:F486P with S:P681R, N:A50V, ORF9b:R47C and Orf1b:V1092I likely emerged from Malaysia (54 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1621]
Here i want to highlight this possible sublineage that USher calls XBB.1.5 and it is XBB.1.5 also according to the @corneliusroemer proposal to broad it  , but it is actually just a XBB.1 + S:F486P.
Despite being just two sequences it is a mini saltation of 3 AA and one of them is the infamous S:P681R, Although @thomaspeacock et al already showed that Omicron FCS is optimized and S:681R could do nothing more than 679K +681H, i prefer to put this here cause it emerged from an undersampled area as Malaysia and anyway it is on a mini-long branch.

Defining mutations:
XBB.1> >  **S:F486P** (T23018C) > C9430T, **Orf1b:V1092I** (G16741A), C19017T,  C19524T, **S:P681R** (A23604G), C27884T, **N:A50V** (C28422T)= ORF9b:R47C. **(EDITED)**

**Tree**:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d3c1_98b0.json?c=userOrOld&label=id:node_9550118&s=hCoV-19/USA/VA-CDC-QDX45592243/2023%7CEPI_ISL_16745478%7C2023-01-12
<img width="1010" alt="Schermata 2023-02-05 alle 21 07 08" src="https://user-images.githubusercontent.com/87669813/216842202-f948354c-efda-4a91-862a-90b7bc6896e6.png">

**Gisaid query**: N_A50V,Spike_P681R,Spike_f486P

**Sequences**: EPI_ISL_16745478, EPI_ISL_16807808

**Comment by FedeGueli** [comment]
A third sample of this sublineage popped up from England:
<img width="1127" alt="Schermata 2023-02-12 alle 20 22 44" src="https://user-images.githubusercontent.com/87669813/218332443-e3d3ac1b-05dd-4c63-947c-92de38074f84.png">

**Comment by FedeGueli** [comment]
5 samples as today. the last two uploaded by Israel cc @shay671

**Comment by Outpfmance** [comment]
It now has 5 sequences, so update the title to be the same @FedeGueli

**Comment by FedeGueli** [comment]
2 new sequences from England

**Comment by FedeGueli** [comment]
( samples as today. Last one came from Australia

**Comment by FedeGueli** [comment]
11 sequences as today. last samples from Australia, Maryland and NYC

**Comment by FedeGueli** [comment]
15 sequences as today. Interestingly among the last 4 sequences one was from Sudan and the other from Singapore airport surveillance sampled in a traveller from Thailand.

**Comment by corneliusroemer** [comment]
Let's watch this a bit more - but worth designating once it hits say 50, time helps it settle down

**Comment by FedeGueli** [comment]
18 sequences now also Canada and Uk

**Comment by agamedilab** [comment]
19 on usher as of 27.03.23.

![grafik](https://user-images.githubusercontent.com/102166254/227943777-b9cf53e1-7cd6-4261-94d9-2c789b954917.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18d83_18eae0.json?c=gt-S_681

**Comment by FedeGueli** [comment]
21 as today

**Comment by FedeGueli** [comment]
26 sequences as today.
It seems circulating now in Canada, France and England. One new sample from India too

**Comment by FedeGueli** [comment]
30 sequences as today, last ones from Canada , Australia and Maryland

**Comment by FedeGueli** [comment]
33 sequences last ones from Uk and Den

**Comment by agamedilab** [comment]
42 seq as of 12.04.23. 

![grafik](https://user-images.githubusercontent.com/102166254/231438530-1e58b986-2925-4dde-9cdd-dc74409b1257.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f66c_68ec30.json?c=gt-S_681

**Comment by FedeGueli** [comment]
Thx @agamedilab , i would like to point to wide diversity it is showing with further mutations at 356 507 554 (one for branch) and  eveb more outside spike . @corneliusroemer was waiting it to git 50seqs but sincerely given a limely significant prevalence in an undersampled area i would designate it, so everyone in the labs could manage to recognize it.
@thomasppeacock @InfrPopGen

**Comment by Outpfmance** [comment]
@agamedilab It has 40 sequences instead of 42. Although it's 50 sequences away, I also think this one should be named, it has emerged and spread in several countries around the world, and even some countries have uploaded clusters of cases, such as Sudan.
@InfrPopGen

**Comment by Outpfmance** [comment]
42 sequences now. 2 new sequences from England. @FedeGueli

**Comment by FedeGueli** [comment]
thx @outpfmance! also @Rajlabn pointed this to me.

**Comment by Outpfmance** [comment]
43 sequences now.[+1 from USA,New York.]EPI_ISL_17474792

**Comment by FedeGueli** [comment]
I have **edited** this issue cause this lineage has from the start an Orf9b mutation i missed before : ORF9b:R47C (=N:A50V)

**Comment by Outpfmance** [comment]
+1 sequences from [USA NewYork]. EPI_ISL_17486034

**Comment by Outpfmance** [comment]
47 sequences now. @FedeGueli 
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_2c2b8_6840.json?f_userOrOld=uploaded%20sample&label=id:node_3151481
![IMG_0098](https://user-images.githubusercontent.com/125484893/233127568-079287aa-150a-4c0e-a908-393b9abf633a.jpeg)
Note: The XBB.1.5 marked in the figure is XBB.1 in this issue.

**Comment by BorisUitham** [comment]
54 due to a chunk of canada uploads

**Comment by FedeGueli** [comment]
Now this has passed the 50 seqs threshold fixed by @corneliusroemer for designation! It is your turn! ;)

**Comment by FedeGueli** [comment]
Now it is 59, interestingly it landed in China Henan and was sampled from Travellers from Turkey in the Usa. likely more widespread than what the number of samples actually tells
