### ISSUE TITLE
XBC.1 with S:G184S, ORF1a:P3952S, ORF1a:V4072A  (42 seq., Australia, Singapore)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1622]
Proposal for a sublineage of XBC.1
Earliest sequence: 11.10.2022 (Australia)
Countries detected: Australia, Singapore

This sublineage is defiend by S:G184S, ORF1a:P3952S, ORF1a:V4072A and was only detected in Australia and Singapore so far (31 seq as of 06.02.23). 

Defining mutation:
G22112A = S:G184S
C12119T = ORF1a:P3952S
T12480C = ORF1a:V4072A

Provisorial GISAID query: Spike_N703I, Spike_P25S, Spike_G184S

![grafik](https://user-images.githubusercontent.com/102166254/216921059-00ce6ef0-4604-419c-83c3-5c7ae565b969.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42ee6_b67c0.json?c=gt-S_184&label=id:node_8574293

EPI_ISL_16004312, EPI_ISL_16826037, EPI_ISL_15440290, EPI_ISL_16389033, EPI_ISL_16717206, EPI_ISL_16717363, EPI_ISL_16717210, EPI_ISL_16717214, EPI_ISL_16717170, EPI_ISL_16826059, EPI_ISL_16717149, EPI_ISL_16447050, EPI_ISL_16004133, EPI_ISL_16717368, EPI_ISL_16825903, EPI_ISL_16825854, EPI_ISL_16826042, EPI_ISL_16826036, EPI_ISL_16825901, EPI_ISL_16717217, EPI_ISL_16004276, EPI_ISL_16315519, EPI_ISL_16004110, EPI_ISL_16825962, EPI_ISL_16825959, EPI_ISL_16826034, EPI_ISL_16717335, EPI_ISL_16717332, EPI_ISL_16717347, EPI_ISL_16826047, EPI_ISL_16523772

**Comment by Outpfmance** [comment]
Now that it has 36 sequences, it's time to update the issue. @agamedilab

**Comment by agamedilab** [comment]
42 seq. as of 20.02.2023. I just noticed this has already been designated XBC.1.4 by @corneliusroemer last week.

![grafik](https://user-images.githubusercontent.com/102166254/220099534-4a54e16a-0fa1-46b0-a55c-63a980772947.png)

![grafik](https://user-images.githubusercontent.com/102166254/220099073-d22943f0-6ed0-4c31-8a71-d3487fb7cab8.png)

It would be great if a designate label & a milestone could be added to the issue @InfrPopGen @corneliusroemer. Many thanks!
