### ISSUE TITLE
DV.3 sublineage with orf1b:V839I (65 seqs, 90% in Portugal DV.3)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1626]
Description
Sub-lineage of: DV.3
Earliest sequence: 2022-11-25 EPI_ISL_16073768
Most recent sequence: 2023-01-30 EPI_ISL_16815458
Countries circulating: Portugal, Ireland, Belgium, USA, Brazil, UK, Germany, France
Number of sequences: 52

Query(both GISAID and cov-spectrum): G15982A,G1394A,T13560C
Substitutions on top of DV.3: Orf1b:V839I(G15982A)

<img width="1384" alt="Screen Shot 2023-02-07 at 11 13 12" src="https://user-images.githubusercontent.com/10445944/217140394-394d31e4-ba86-49ad-bbb3-36cedceb67db.png">
<img width="1384" alt="Screen Shot 2023-02-07 at 11 11 07" src="https://user-images.githubusercontent.com/10445944/217140416-a4c934ec-dafc-4a4a-b47f-70c6f139afe4.png">

tree link:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4153d_1bfb70.json?c=gt-ORF1ab_5240&label=id:node_8213585&tl=none

growth advantage link:
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=orf1b%3Av839I&aaMutations1=ORF1b%3AV839I&nextcladePangoLineage1=DV.3*&analysisMode=CompareToBaseline&

There are 2 branches of Orf1b:V839I in DV.3, the lower smaller branch has a A12422C first. However, only one sequence on this branch doesn't have Orf1b:V839I. 

<img width="1136" alt="Screen Shot 2023-02-07 at 11 17 17" src="https://user-images.githubusercontent.com/10445944/217140875-23ae94c4-624f-4ada-bc42-18086fd7df5e.png">

Sequences:
EPI_ISL_16073760, EPI_ISL_16073768, EPI_ISL_16178653,
EPI_ISL_16405843, EPI_ISL_16406308, EPI_ISL_16441258,
EPI_ISL_16441316, EPI_ISL_16441356, EPI_ISL_16443631,
EPI_ISL_16443679, EPI_ISL_16486183, EPI_ISL_16533746-16533748,
EPI_ISL_16533824, EPI_ISL_16547285, EPI_ISL_16547329,
EPI_ISL_16547380, EPI_ISL_16590446, EPI_ISL_16615578,
EPI_ISL_16617909, EPI_ISL_16617912-16617913, EPI_ISL_16617927,
EPI_ISL_16618203, EPI_ISL_16618210, EPI_ISL_16677103,
EPI_ISL_16680218, EPI_ISL_16680233, EPI_ISL_16680243,
EPI_ISL_16680293, EPI_ISL_16682791, EPI_ISL_16698803,
EPI_ISL_16722231, EPI_ISL_16750649, EPI_ISL_16814013,
EPI_ISL_16814298, EPI_ISL_16815458, EPI_ISL_16815803,
EPI_ISL_16818572, EPI_ISL_16824377, EPI_ISL_16825064,
EPI_ISL_16825184, EPI_ISL_16825195-16825197, EPI_ISL_16825212,
EPI_ISL_16825218, EPI_ISL_16825263, EPI_ISL_16825271,
EPI_ISL_16825275, EPI_ISL_16825289

**Comment by FedeGueli** [comment]
Good catch @aviczhl2 could you add please the links to the tree and the covspectrum growth advantage ? This (especially the covspectrum link) will enable a rapid check in the next weeks.

**Comment by aviczhl2** [comment]
> Good catch @aviczhl2 could you add please the links to the tree and the covspectrum growth advantage ? This (especially the covspectrum link) will enable a rapid check in the next weeks.

Thanks for the suggestion. Link added.

**Comment by corneliusroemer** [comment]
Growth advantage of so few sequences has to be taken with huge pinch of salts. I'd say it's mostly noise at the moment looking at the scatter plot.

**Comment by Outpfmance** [comment]
Now that it has 64 sequences, it's time to update the issue.  @aviczhl2 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1b%3AV839I&nextcladePangoLineage=DV.3&

**Comment by aviczhl2** [comment]
> Now that it has 64 sequences, it's time to update the issue. @aviczhl2 https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1b%3AV839I&nextcladePangoLineage=DV.3&

Yeah, 65 seqs now, still having 28% relative growth advantage. 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=DV.3*&aaMutations1=orf1b%3AV839I&nextcladePangoLineage1=DV.3*&analysisMode=CompareToBaseline&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage DV.3.1 with 24 newly designated sequences, and 25 updated. Defining mutation G15982A (ORF1b:V839I) (following T13560C).
