### ISSUE TITLE
Potential new sublineage of BQ.1.10 with additional mutation S:S939F, ORF1a: T2300I, ORF1a: L2874S, and ORF3a: A23V in USA

### ISSUE THREAD

**Issue by munokh** [cov-lineages/pango-designation#1628]
## Description
Sub-lineage of: BQ.1.10
Earliest sequence:2023-01-01
Most recent sequences:2023-01-12
Countries circulating: USA
Number of sequences:13

Proposing new sublineage because these 13 sequences have defined mutation in S:S939F, ORF1a: T2300I, ORF1a: L2874S, and ORF3a: A23V not found in BQ.1.10 lineage.
C24378T=S: S939F 
C7164T=ORF1a:T2300I ,
T8886C=ORF1a:L2874S
C25460T=ORF3a: A23V

Genomes
EPI_ISL_16848921, EPI_ISL_16848920, EPI_ISL_16848912, EPI_ISL_16848923, EPI_ISL_16848911, EPI_ISL_16848922, EPI_ISL_16848914, EPI_ISL_16848913, EPI_ISL_16848916, EPI_ISL_16848915, EPI_ISL_16848918, EPI_ISL_16848917, EPI_ISL_16848919

Evidence
Phylogenetic tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3c37b_29af30.json?f_userOrOld=uploaded%20sample

![Phylogenetic tree](https://user-images.githubusercontent.com/108483303/217343061-e6dc27e8-d357-475d-9503-cb6069f2d80f.png)

**Comment by corneliusroemer** [comment]
Single lab for now and it's small though potentially a bit of a saltation. Let's see what happens. Also, collection quite a long time ago (1month) and no sequences since Can you use 5000 sequences for context when making Usher trees, here you seem to have used the default of 50 which fails to pull in sufficient context to judge based on the tree you built.

**Comment by munokh** [comment]
![Phylogenetic tree_2](https://user-images.githubusercontent.com/108483303/217633354-98a1c0fa-1848-4894-8936-9e2a02035ec3.png)

**Comment by corneliusroemer** [comment]
Use the zoomed subtree not the downsampled tree. These are still lacking context. Here's how you select 5000 sequences for context:
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/25161793/218098246-50a6d160-d0f3-410d-b239-74a1341278f1.png">

Oh and sharing the link to the tree is super useful for everyone as well.

**Comment by munokh** [comment]
Here is the link for using 5000 sequences.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41b75_6559a0.json?f_userOrOld=uploaded%20sample
![Phylogenetic tree 3](https://user-images.githubusercontent.com/108483303/218119637-04b503f3-a7c8-4dcd-a1da-9f420b246f05.png)

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there haven't been new detections over the past two months, and the growth advantage was not that high two months ago, this can be closed for now. Please request re-opening or re-propose should the situation change markedly.
