### ISSUE TITLE
Potential new sublineage of BQ.1.1 with reverted mutations Gene S:A376T/N477S/S480R plus additional mutations Gene S:F797C/G799S

### ISSUE THREAD

**Issue by VirologiaHUCA** [cov-lineages/pango-designation#1629]
By VirologiaHUCA
Description
Sub-lineage of: BQ.1.1
Earliest sequence: 2023-01-23
Most recent sequence: 2023-01-24
Countries circulating: Spain (6 Asturias) 

Written description
In BQ.1.1 variants, 5 sequences (EPI_ISL_16814846, EPI_ISL_16814847,EPI_ISL_16814849, 
EPI_ISL_16814850, EPI_ISL_16814851) has reverted these mutations Gene S:A376T/N477S/ S480R and gained these mutations Gene S:F797C/G799S. 
One sequence (EPI_ISL_16814848) has the reverted mutations but has not gained mutations Gene S:F797C/G799S.
Genomes
EPI_ISL_16814846, EPI_ISL_16814847, EPI_ISL_16814848, EPI_ISL_16814849,  EPI_ISL_16814850 y EPI_ISL_16814851

Evidence

![image](https://user-images.githubusercontent.com/105294581/217524607-182afb13-ba1e-4c83-9911-a6a56bf14571.png)

**Comment by ryhisner** [comment]
I think you intended to write S:S408R, not S:S480R. To me these look like sequencing artifacts. There is a ton of missing coverage on these, and many of the reversions/unusual mutations occur adjacent to areas of missing coverage. 
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/33738461/217652360-04fc878e-5a4e-4acd-9922-c37882d84dce.png">

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there haven't been new detections for over two months, and the reversions show some characteristics typical of artefacts, this can be closed now. Please re-propose or request re-opening should this clade reappear in samples from new labs/regions and show some growth advantages.
