### ISSUE TITLE
XBB.1.5 w/ spike mutation Q675H, present throughout Europe and USA (93 seqs as of 17-02-23)

### ISSUE THREAD

**Issue by BorisUitham** [cov-lineages/pango-designation#1631]
Sub-lineage of: XBB.1.5
Earliest sequence: 2022-12-06
Most recent sequence: 2023-02-03
Countries circulating: Austria, Canary Islands, Croatia, France, Germany, Ireland, Italy, Poland, Spain, Switzerland, Ukraine, USA (California, Illinois, Maryland, New Jersey, New York)

This mutation is interesting because although there are only 44 sequences, it is already very geographically widespread throughout Europe and USA. It is also growing pretty substantially. Also, position might be of interest for fusogenicity? I'm not sure

GISAID query: Hard to find a query that catches all sequences. I found 40 through “Spike_Q675H + lineage: xbb.1.5” and 42 through: “Spike_Q675H + Spike_Q183E + Spike_F486P” but the one misses sequences of the other. Combined, i found 44 unique sequences. If anyone is able to come up with a query that catches everything that would be appreciated.

Genomes
EPI_ISL_16218354, EPI_ISL_16239088, EPI_ISL_16527177,
EPI_ISL_16527220, EPI_ISL_16533688, EPI_ISL_16553570,
EPI_ISL_16629742, EPI_ISL_16637131, EPI_ISL_16637952,
EPI_ISL_16665369, EPI_ISL_16673394, EPI_ISL_16673421-16673423,
EPI_ISL_16674319, EPI_ISL_16676450, EPI_ISL_16678703,
EPI_ISL_16694080, EPI_ISL_16696024, EPI_ISL_16700527,
EPI_ISL_16703146, EPI_ISL_16743957, EPI_ISL_16753803,
EPI_ISL_16783870, EPI_ISL_16806723, EPI_ISL_16811040,
EPI_ISL_16811134, EPI_ISL_16811149, EPI_ISL_16812249,
EPI_ISL_16824467, EPI_ISL_16824496, EPI_ISL_16828805,
EPI_ISL_16828813-16828814, EPI_ISL_16828816, EPI_ISL_16831947,
EPI_ISL_16831982, EPI_ISL_16832116, EPI_ISL_16835187,
EPI_ISL_16851215

Evidence
![675h](https://user-images.githubusercontent.com/119106095/217550469-e21096ab-2f98-49ea-ac23-d175b9b77ffb.png)
This tree looks very messy so I am not sure if it is monophyletic.

Covspectrum: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3Aq675h&nextcladePangoLineage=xbb.1.5*&aaMutations1=s%3A675h&nextcladePangoLineage1=xbb.1.5*&

calculated worldwidegrowth advantage as of 08-02-23: 107 (64-150)

**Comment by BorisUitham** [comment]
And 12 sequences from austria already got uploaded, bringing the total from 44 to 56.

**Comment by BorisUitham** [comment]
Role of Q675H Mutation in Improving SARS-CoV-2 Spike Interaction with the Furin Binding Pocket
https://pubmed.ncbi.nlm.nih.gov/34960779/
pre-omicron paper

**Comment by AngieHinrichs** [comment]
> I'm not sure how I would go about proposing this then? Wait until one of the 675h lineages has a clear advantage over the others? Or what if they share the same growth advantage?

@corneliusroemer any guidelines for how big a potential lineage needs to grow before we can believe the growth advantage estimate, and otherwise how to tell when to propose different homoplasic branches as lineages?

@BorisUitham, to get the tree above, I'm assuming you clicked from the CoV-Spectrum query results into the tree you showed above into Other Websites -> UShER, and then clicked the "view downsampled global tree" button?

I tried CoVSpectrum -> Other Websites -> UShER, and since more than 5 different subtrees resulted from the query, the individual subtree buttons were not added (too much clutter).  However, the table that lists sequences and lineages has links to the subtrees in the rightmost column:

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/186983/217981058-8af9d8e7-ffc5-41e3-95c7-ffb9f163236b.png">

subtree 1 has the most uploaded sequences, subtree 2 has the second most and so on.  As of yesterday, subtree 1 had 17 "uploaded IDs" (IDs from the CoV-Spectrum query), on a branch with 21 sequences, preceded by nodes with C12781T and C2695T.  So you could monitor that largest cluster by adding C2695T and C12781T to your CoV-Spectrum query:

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3Axbb.1.5*+%26+s%3Aq675h+%26+C2695T+%26+C12781T

**Comment by BorisUitham** [comment]
Thank you @AngieHinrichs. Your query (c2695t +  c12781t + spike_q675h + xbb.1.5) now catches 33 of the 69 total sequences. I suspect that most of the 17 spike only sequences from austria also belong to this branch, but those nucleotides arent sequenced. that would potentially make this branch up to 50 of the 69 sequences. However, there is probably a very large amount of bias since austria just sequences more so it is very difficult to know which branch is actually growing the quickest, i suspect its mostly similar in each branch

**Comment by corneliusroemer** [comment]
@BorisUitham please use the maximum number of context samples when making Usher trees to help investigate these homoplasy questions better, and also see more nearby samples. This is how you do it, 5000 is the max
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/25161793/218097848-21d494ed-bcc2-4d8e-832a-cb12346f91c6.png">

**Comment by BorisUitham** [comment]
@corneliusroemer I did use the default value, which is 5000. The image produced is from the downsampled global tree, usher delivered a multitude of subtrees

**Comment by corneliusroemer** [comment]
Oh right, yeah the downsampled global tree is similarly uninformative as using few context samples. Choose a subtree or a few where your samples show clearly. Multiple subtrees doesn't mean you can't get a few major ones. If it's all over the place and there is no single big subtree then that points towards artefact.

**Comment by BorisUitham** [comment]
Here is another one, where i specifically searched for the branch (C2695t + C12781T) with most submitted sequences (which again might not be the actual largest). I hope this is a bit more informative
![nr2](https://user-images.githubusercontent.com/119106095/218448327-d0b70147-0b45-481a-84d4-c9d966479be5.png)

**Comment by corneliusroemer** [comment]
Again missing context ;) 

This is how it's best to investigate (also add the link so one doesn't need to recreate the tree, at least while Usher stores it)

Zoomed out: there are so many XBB.1.5 that not all are shown but all relevant neighbours are represented.
<img width="1921" alt="image" src="https://user-images.githubusercontent.com/25161793/218452238-e24bc862-c413-4f8d-98a1-f9ca513f8452.png">

That's the branch off of the XBB.1.5 US polytomy, bit of a European branch, makes sense as this lineage is predominantly European:
<img width="1987" alt="image" src="https://user-images.githubusercontent.com/25161793/218452380-c3e6a7f1-a75e-4539-89c5-fddc431d5732.png">

This is close up:
<img width="1858" alt="image" src="https://user-images.githubusercontent.com/25161793/218452514-cdd704f8-615e-4916-b04b-f6a8c883f091.png">


https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_a6b6_a25390.json?f_userOrOld=uploaded%20sample

Looks good, I'll take a look at how to break down the XBB.1.5 tree this week. Thanks for your work! Just trying to show you how I go about investigating such things so it saves all of us work!

**Comment by BorisUitham** [comment]
Thanks, next time I'll show the tree in different levels like that and include the link!

**Comment by corneliusroemer** [comment]
I should learn from you to use a downsampled one for overview and detection of homoplasy. It does put things into perspective!

**Comment by FedeGueli** [comment]
Designated EL.1

**Comment by BorisUitham** [comment]
Thanks!!
