### ISSUE TITLE
BQ.1.1 Sublineage with S:ins248KWLD, S:Y248S, ORF8:C102F (53 seq, Feb 10)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1635]
### **Description**
**Sub-lineage of:** BQ.1.1
**Earliest sequence:** 2022-12-5, Germany — EPI_ISL_16219081
**Most recent sequence:** 2023-1-30, Austria — EPI_ISL_16831707, EPI_ISL_16831745
**Countries circulating:** Turkey (10), Austria (8), Germany (5), USA (4), Belgium (3) ,France (1), Israel (1), Singapore (1), Slovenia (1), Wales (1)
**Number of Sequences:** 35
**GISAID Query:** Spike_ins248KWLD
**CovSpectrum Query:** Nextcladepangolineage:BQ.1.1* & C7006T & G28198T
**Substitutions/Insertions on top of BQ.1.1:**
**Spike:** ins248_KWLD, Y248S
**ORF8:** C102F
**Nucleotide:** C7006T, G28198T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1.1_ins248KWLD_subtreeAuspice1_genome_24244_41fcd0.json

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/33738461/217673484-1c7e2097-cf70-4964-a460-c3af988a8933.png">

**Evidence**
Nextclade prefers to interpret this insert as S:ins248SKWL + S:Y248D. There's been something of a renaissance in recent months around S:Y248. Insertions there have become much more common—most notably RWMD in BA.1.28, AED in BQ.1.1.37, and DAD in an undesignated Canadian branch of BQ.1.15 circulating in Canada & USA that's now up to 78 sequences—and so have substitutions, including S:Y248D, which was almost never seen until recently, and S:Y248N, which has resurged in the form of BA.2.76/BF.3 recombinant XBM—which seemed to almost disappear months ago before its sudden resurgence of late—and with BF.31.1 in South America, which features S:S247del, S:Y248N. There is also a lineage of BQ.1.1.28 that features S:S247N, S:Y248S, and S:P251L, and which originated in Italy but has since spread to other countries (62 seq total).

It seems clear that something about the global immunity landscape has changed and has now created a favorable environment for mutations in the S:Y248 region.

This particular lineage seems especially interesting to me because of its very recent appearance and because four of its sequences also have S:V445A. Furthermore, those four sequences have come from three geographically widespread countries: Austria, Singapore, and the USA (New York). (One sequence from Belgium features S:V445F, which seems to be a much less successful mutation than S:V445A.)

Additionally, the existence of 10 sequences from Turkey could indicate that this lineage is circulating in higher numbers there and in surrounding countries (Syria, Iraq, Iran, Armenia) where sequencing is almost nonexistent.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16219081, EPI_ISL_16221173, EPI_ISL_16395070, EPI_ISL_16395078, EPI_ISL_16414382, EPI_ISL_16414563, EPI_ISL_16414568, EPI_ISL_16414575, EPI_ISL_16414627, EPI_ISL_16414654, EPI_ISL_16414683, EPI_ISL_16414714, EPI_ISL_16424325, EPI_ISL_16449832, EPI_ISL_16570060, EPI_ISL_16646381, EPI_ISL_16647884, EPI_ISL_16676388, EPI_ISL_16693827, EPI_ISL_16703158, EPI_ISL_16710534, EPI_ISL_16738948, EPI_ISL_16754365, EPI_ISL_16811944, EPI_ISL_16812865, EPI_ISL_16831707, EPI_ISL_16831745, EPI_ISL_16847430, EPI_ISL_16851069, EPI_ISL_16857544, EPI_ISL_16857599, EPI_ISL_16857737, EPI_ISL_16857754, EPI_ISL_16857759, EPI_ISL_16858232
</details>

**Comment by FedeGueli** [comment]
Great proposal Ryan thx! it was just one or two sequences when i spotted BQ.1.1.37 two weeks ago so it is growing for sure.

**Comment by corneliusroemer** [comment]
Designated as EA.1
