### ISSUE TITLE
BA.5.2 Sublineage with S:K444N, S:N460K, ORF6:Y31C, ORF1a:A776V, ORF1a:T1794I (131 seq, Feb 8)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1636]
### **Description**
**Sub-lineage of:** BA.5.2
**Earliest sequence:** 2022-9-28, South Korea — EPI_ISL_15491592
**2nd-Earliest sequence:** 2022-10-30, Australia — EPI_ISL_15671796
**Most recent sequence:** 2023-1-27, Canada, Ontario — EPI_ISL_16840415 & five others
**Countries circulating:** Primarily Canada (52/56 sequences collected since January 1, 2023)
**Number of Sequences:** 128
**GISAID Query:** Spike_K444N, Spike_N460K, NSP2_A596V, NSP3_T976I, NS6_Y31C
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2* & [6-of: G2407A, C2485T, C2592T, C5646T, C8752T, G22894T, T22942A, A27293G]
**Substitutions on top of BA.5.2:** 
**Spike:** K444N, N460K
**ORF6:** Y31C
**ORF1a:** A776CV, T1794I
**Nucleotide:** G2407A, C2485T, C2592T, C5646T, C8752T, G22894T, T22942A, A27293G
**AA Deletions:** ∆Y144
**Nucleotide Deletions:** ∆21992-21994

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.5.2%20%2B%20K444N%20%2B%20N460K%20%2B%20ORF6_Y31C%2C%20etc%20-%20subtreeAuspice1_genome_3f83a_2a5130.json 

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/33738461/217697427-52615259-4033-4395-9d1b-d4ffe03e758b.png">

**Evidence**
I’m not 100% certain this is a new lineage, but Usher seems to think so, and it appears as if it involves a six-mutation mini-saltation. There’s obviously something slightly wrong with the Usher tree since ORF3a:Q38E appears just before this branch, then reverts ~20 sequences later. But I think it’s most likely the sequences with ORF3a:Q38E that are misplaced, not the ones in this lineage.

One sub-branch of this lineage with about 25 sequences leads to sequences mostly from England and California, USA, but the bulk of the sequences have an additional five synonymous mutations (A2563G, G3109A, C4099T, A8101G, C13115T). These are all from Canada, mostly Ontario, and make up most of the recent sequences from this lineage. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15491592, EPI_ISL_15671796, EPI_ISL_15784132, EPI_ISL_15784261, EPI_ISL_15823463, EPI_ISL_15906187, EPI_ISL_15927829, EPI_ISL_15945241, EPI_ISL_15945580, EPI_ISL_15980250, EPI_ISL_16009755, EPI_ISL_16052127, EPI_ISL_16072005, EPI_ISL_16072029, EPI_ISL_16072154, EPI_ISL_16074012, EPI_ISL_16074036, EPI_ISL_16074073, EPI_ISL_16074146, EPI_ISL_16081545, EPI_ISL_16085742, EPI_ISL_16085870, EPI_ISL_16137303, EPI_ISL_16186600, EPI_ISL_16186636, EPI_ISL_16187635, EPI_ISL_16187645, EPI_ISL_16187686, EPI_ISL_16191379, EPI_ISL_16212730, EPI_ISL_16237608, EPI_ISL_16237645, EPI_ISL_16237690, EPI_ISL_16293468, EPI_ISL_16299418, EPI_ISL_16299568, EPI_ISL_16301800, EPI_ISL_16301813-16301814, EPI_ISL_16319726, EPI_ISL_16321828, EPI_ISL_16322009, EPI_ISL_16322050, EPI_ISL_16322103, EPI_ISL_16322105, EPI_ISL_16322112, EPI_ISL_16322208-16322209, EPI_ISL_16322211, EPI_ISL_16322254, EPI_ISL_16322371, EPI_ISL_16323439, EPI_ISL_16323498, EPI_ISL_16324041, EPI_ISL_16324964, EPI_ISL_16324969, EPI_ISL_16325164, EPI_ISL_16334243, EPI_ISL_16369926, EPI_ISL_16370329, EPI_ISL_16378520, EPI_ISL_16378522, EPI_ISL_16378683, EPI_ISL_16414678, EPI_ISL_16452597, EPI_ISL_16452727, EPI_ISL_16452795, EPI_ISL_16452963, EPI_ISL_16467921, EPI_ISL_16512455, EPI_ISL_16529822, EPI_ISL_16530260, EPI_ISL_16530264, EPI_ISL_16530269, EPI_ISL_16530278, EPI_ISL_16530284, EPI_ISL_16530423-16530424, EPI_ISL_16530496, EPI_ISL_16530556, EPI_ISL_16531292, EPI_ISL_16531514, EPI_ISL_16531835, EPI_ISL_16541480, EPI_ISL_16541562, EPI_ISL_16577914, EPI_ISL_16586337, EPI_ISL_16612111, EPI_ISL_16612212, EPI_ISL_16629392, EPI_ISL_16629437, EPI_ISL_16629465, EPI_ISL_16629477, EPI_ISL_16629990, EPI_ISL_16630660, EPI_ISL_16642364, EPI_ISL_16690002, EPI_ISL_16690057, EPI_ISL_16690201, EPI_ISL_16715448, EPI_ISL_16729995, EPI_ISL_16730428-16730435, EPI_ISL_16730438-16730439, EPI_ISL_16730468, EPI_ISL_16730697, EPI_ISL_16731025, EPI_ISL_16839674, EPI_ISL_16839891-16839892, EPI_ISL_16839949, EPI_ISL_16839951, EPI_ISL_16839980, EPI_ISL_16839995, EPI_ISL_16839998, EPI_ISL_16840085, EPI_ISL_16840232, EPI_ISL_16840288, EPI_ISL_16840328-16840329, EPI_ISL_16840415
</details>

**Comment by FedeGueli** [comment]
Thx @ryhisner i proposed this one (the parental with 444+460 combo) in #1410 closed then cause it seemed slow at that time. But it is correct to repropose it now! thank you! (keeping ur updated open and mine old closed)

**Comment by ryhisner** [comment]
Oh, shoot, I should've known you'd be on top of all the K444N-N460K, @FedeGueli! I searched for but didn't find ORF6:Y31C, but I should've looked harder. Thanks for letting me know about your earlier proposal and for your unfailing graciousness!

**Comment by AnonymousUserUse** [comment]
I think this lineage may have molnupiravir origin: All mutations except convergent site S:K444N and S:N460K are transitions, up to the sublineage with ORF1a:L681F

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.63 with 111 newly designated sequences, and 0 updated. Defining mutations C2592T (ORF1a:A776V), C5646T (ORF1a:T1794I), A27293G (ORF6:Y31C), G2407A, C2485T, C8752T (following G25504C (ORF3a:E38Q)).
Interestingly, CK.1 has G22894T > T22942G which is similar to the G22894T > T22942A in this new lineage, both have ORF1b:T1050N nearby in path too (and I think the defining mutations were all at 2nd codons).

**Comment by FedeGueli** [comment]
@InfrPopGen orf3a:E38Q  is a reversion to wildtype Q is correct to highlight it as defining? ( naive question, just my fear it messes up assignments then)

**Comment by AngieHinrichs** [comment]
It is correct -- the BA.5.2.63 branch was placed on a branch that started with C25504G (ORF3a:Q38E) because it shares two mutations (S:K444N and S:N460K) with some sequences that also have C25504G.  But the BA.5.2.63 sequences do not have the C25504G mutation so usher put a reversion there.  It's more parsimonious to add one reversion than to make a new branch with the two shared mutations (S:K444N and S:N460K).  Parsimony is a fast algorithm, but it doesn't account for recurrent mutations that confer a selective advantage.
