### ISSUE TITLE
One more BA.2.75* x BQ.1* recombinant with spike breakpoint (39 seqs, 2023-02-19)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1637]
This is the 6th BA.2.75* x BQ.1* recombinant cluster recently emerged, along with #1393 , #1425 , #1444, #1543 and #1567 . Again this recombinant has a breakpoint at spike.

### Description
**Recombinant between**: BA.2.75* and BQ.1* (with S:R346T)
**Earliest sequence**: 2022/11/23 (Czech Republic)
**Most recent sequence**: 2023/01/20 (UK-England)
**Countries circulating**: Czech Republic (1/34), Canada-QC (6/34), UK-England (8/34), Israel (2/34), US-CA (17/34)
**Potential breakpoint**: Spike NTD (22034-22189)

**Mutation profile** (private mutations are in yellow color):
![image](https://user-images.githubusercontent.com/86835836/217726465-aa5bb2cd-156e-4692-b43e-9c0a1bae6f06.png)
**Private mutations**: G1440A, A1964G, A5844G, C8597T, G25471C, C25553T, T25569C, G26031A
**GISAID and Cov-spectrum query**: G1440A, A1964G, A5844G, C8597T, G25471C, C25553T, T25569C, G26031A

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/217727534-7e370c9a-3291-4ff3-a7d6-a911cbbed447.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33c7f_44df30.json?c=gt-nuc_1964,19075&label=id:node_7030659

### Genomes:
EPI_ISL_15927302, EPI_ISL_16180548, EPI_ISL_16351135, EPI_ISL_16380898, EPI_ISL_16406535, EPI_ISL_16460518, EPI_ISL_16467709, EPI_ISL_16509912, EPI_ISL_16525147, EPI_ISL_16574696, EPI_ISL_16574862, EPI_ISL_16602238, EPI_ISL_16602385, EPI_ISL_16602765, EPI_ISL_16613795, EPI_ISL_16614924, EPI_ISL_16615528, EPI_ISL_16619263, EPI_ISL_16619390, EPI_ISL_16619552, EPI_ISL_16654445-16654448, EPI_ISL_16657063-16657064, EPI_ISL_16663257, EPI_ISL_16670172, EPI_ISL_16679111, EPI_ISL_16690171, EPI_ISL_16703822, EPI_ISL_16735084, EPI_ISL_16738930, EPI_ISL_16818068

**Comment by c19850727** [comment]
35 sequences now, and interestingly the latest sequence has an additional S:P681R.

**Comment by c19850727** [comment]
39 sequences as of 2023-02-19. Newly found in Israel, and interestingly the 2 recent Israeli sequences have an additional S:T883I which is pretty convergent.

**Comment by AngieHinrichs** [comment]
Looks like BN.3.1 (BA.2.75.5 > *G1440A* > *A1964G* > *C21077T* > *C1093T* > A22910G > *A5844G,C8597T*) x BQ.1.25 (... > *T22942A* > *G22599C* > C22855T > T8038C,*T25569C,G26031A*).  Almost BQ.1.25.1 but not quite -- it has C25553T but not C24134A.

**Comment by JosetteSchoenma** [comment]
XBR
