### ISSUE TITLE
XBB.1.5 sublineage with S:K417S - 24 sequences as 18/02/23 Austria

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1638]
I noticed yesterday a sublineage of XBB.1.5 with S:K417S. today it has grown to 5 sequences all from Austria from 3 different submitting labs .

S:K417S is predicted to increase composite fitness of XBB.1.5 increasing its immune escape while reducing just a bit its rbd binding:
<img width="844" alt="Schermata 2023-02-09 alle 10 51 14" src="https://user-images.githubusercontent.com/87669813/217778376-3fa137e7-ef8e-4f66-9875-402898e3ef10.png">

Defining mutations:
XBB.1.5 > T21880C > G28079T > C16173T > S:K417S (A22812G), C26936A

Sequences:
EPI_ISL_16617626, EPI_ISL_16685975, EPI_ISL_16831886,
EPI_ISL_16857925, EPI_ISL_16858428

Tree: (Usher shows S:K417R due to its inability to show 2 nuc mutations)
<img width="1157" alt="Schermata 2023-02-09 alle 11 04 09" src="https://user-images.githubusercontent.com/87669813/217781402-59e6b75d-ba75-4bd2-ab62-93a80f2de3d4.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21430_4baa30.json?c=userOrOld&label=id:node_7987934

History of S:K417 

S:K417 is a key antigenic residue .
We first observed S:K417 mutated to N in Beta and to T in Gamma.
then reappeared mutated to N with the emergence of Omicron.
It as to be noticed that multiple BA.2 lineages mutated it from N to T as BA.2.38 that managed to become dominant in India in May 2022 before being suppressed by 2nd generation BA.2.75 there.
@sinickle proposed and got designated recently a second gen BA.2 (BA.2.3.22) with S:K417T

Gisaid query: Spike_F486P,Spike_K417S

**Comment by FedeGueli** [comment]
Big jump to 10 sequences all from Austria. the last 5 are spike only sequences by Ulrich Elling lab

**Comment by FedeGueli** [comment]
Five more sequences from Lifebrain labs Austria uploaded today. It seems fast. @corneliusroemer @thomasppeacock @InfrPopGen

**Comment by thomasppeacock** [comment]
this seems interesting so going to recommend for designation

**Comment by corneliusroemer** [comment]
We'll try a chunk of autolin designations in a few days, will designate it after that!

**Comment by FedeGueli** [comment]
18 viruses as today

**Comment by FedeGueli** [comment]
24 sequences as today it keeps growing very fast.

i would like that if its overall prevalence overall from 2023 ahead is around 0,1% it is growing quite fast and in the samples collected after 5 february it represents over 0,75% of Samples 

@corneliusroemer
