### ISSUE TITLE
Cluster of BA.2.31.1 still circulating in Uganda

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1639]
Sub-lineage of: BA.2.31.1

Sequences: 2023,Uganda, EPI_ISL_16844993-16844999
Number of Sequences: 7 (out of a total of 19 Uganda seqs collected and uploaded in 2023)
GISAID query: C17850T,T5448C

mutations on top of BA.2.31.1:
T19452C,ORF1a:V1728A(T5448C),C17850T
6 of the sequences have S:K440N reversion. 

<img width="1107" alt="Screen Shot 2023-02-09 at 14 28 24" src="https://user-images.githubusercontent.com/10445944/217787092-1117c1cb-1d52-4816-9a7b-15bb750f78c4.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice23_genome_25cc3_472110.json?c=gt-nuc_17850&label=id:node_9576001

On this branch, all the 2023 seqs are with C17850T while sequences sampled around 2022-6 don't.

**Comment by silcn** [comment]
Very odd for only one new mutation to be picked up in 6 months. Makes me suspect these are date errors.

**Comment by corneliusroemer** [comment]
Yeah, was about to say the same as @silcn. The 440 reversion and so few new mutations suggest this may be an artefact.

**Comment by aviczhl2** [comment]
8 seqs now, one more from Uganda sampled on 2022-11-23

**Comment by aviczhl2** [comment]
No more from Uganda. 
That's because Uganda has only submitted 8 recent(2023) sequences(and none of the 8 belongs to this branch) since 2023.2.7 though.  Close it down as no further spread.
