### ISSUE TITLE
Potential new sublineages of P.1 with spike P681R circulating in Brazil

### ISSUE THREAD

**Issue by paolaresende** [cov-lineages/pango-designation#164]
New lineage proposal
by Fiocruz COVID-19 Genomic Surveillance Network

Description
Sub-lineage of: P.1

Earliest sequence P.1+P681R+T470N:2021-05-24
Most recent sequence P.1+P681R+T470N:2021-06-25

Earliest sequence P.1+P681R: 2021-05-10
Most recent sequence P.1+P681R: 2021-05-26

Countries circulating: Brazil

These new proposed lineages (sublineages of P.1) evolve from lineage P.1 major lineage circulating in Brazil since May 2021. 

P.1+P681R+T470N and P.1+P681R clades highligted in red

Viral isolation and neutralizing assay are in progress to understand the phenotypical characteristics of these sublineages.

Genomes
[P681R-Proposta pangolin_details .txt](https://github.com/cov-lineages/pango-designation/files/6903530/P681R-Proposta.pangolin_details.txt)

Evidence
![P681R-Tree_P1_sublineages](https://user-images.githubusercontent.com/51120623/127563228-9c69abab-d6af-488d-aad0-e433534652bf.png)

Proposed lineage name: P.1.8 and P.1.9

**Comment by chrisruis** [comment]
Thanks for submitting @paolaresende. We've added your P.1+P681R+T470N clade as P.1.8 in [v1.2.53](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.53) with 32 sequences

In the latest UShER tree, Brazil/SP-IB_112204/2021 clusters away from the other 5 sequences in your P.1+P681R clade. As this clade only has 5 sequences in it and the most recent sequences are from May, we'd suggest putting a monitor label on this clade for now and checking back in soon to see if there's any more sequences from this clade

Thanks again

**Comment by chrisruis** [comment]
Thanks again @paolaresende. It looks like there's a few more recent sequences in your P.1+P681R clade so we've now added this as P.1.11 in [v1.2.62](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.62)
