### ISSUE TITLE
Description: BA.5.12/XBK recombinant, 16 samples, Denmark 14, the Netherlands 2.

### ISSUE THREAD

**Issue by JosetteSchoenma** [cov-lineages/pango-designation#1641]
**Description:** BA.5.12 sublineage/XBK recombinant, 5 samples
**Nucleotide mutations:** C1302T, G1463A, G2036T, G2095A, C3688T from the BA.5.12 plus T12574C, C21077T, G28162T
I think it recombined with XBK and not XBF or CJ.1, because 394 out of 503 XBK have T12574C, but none of the XBF or CJ.1 do. The spike is the same for all 4 variants.
**Breakpoint:** between nucleotide 9866 and 12160
**Earliest sequence:** 2023-01-16 from Denmark
**Most recent sequence:** 2023-02-02 from Denmark
**Countries circulating:** Denmark, 10
**GISAID query:** G15451A, C1302T, G1463A 
**Covspectrum query:**
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=G15451A%2CC1302T%2CG1463A& 

**Evidence**
**Nextclade:** On top the BA5.12 . At the bottom the similar BA.5.11. The samples from recombinant of this issue are the 5 red lines.
![image](https://user-images.githubusercontent.com/94831035/217890500-05fb251d-13bb-412f-8aa7-8497f2717aa7.png)

**Comment by JosetteSchoenma** [comment]
I forgot to include the EPI_ISL numbers. Here they are:
EPI_ISL_16856796
EPI_ISL_16856954
EPI_ISL_16646578
EPI_ISL_16856965
EPI_ISL_16856855

**Comment by JosetteSchoenma** [comment]
1 new one from Denmark.
EPI_ISL_16938872

**Comment by JosetteSchoenma** [comment]
4 new ones from Denmark today, bringing it's total to 10.

**Comment by JosetteSchoenma** [comment]
2 new ones from Denmark, bringing its total to 12.

**Comment by JosetteSchoenma** [comment]
I think there is a 13th in the Netherlands. Unfortunately it has got several N's, including at nucleotide 1302, which is why my query did not find it. And why it looks more differently on the tree than it really is. EPI_ISL_17064994
![image](https://user-images.githubusercontent.com/94831035/222460919-14d9fa3d-a6d7-4ad0-a7bd-2a4a88d55642.png)
![image](https://user-images.githubusercontent.com/94831035/222461150-a0adac25-1e99-4a84-9553-3277196824c7.png)

**Comment by JosetteSchoenma** [comment]
Another 2 from Denmark and another one from the Netherlands, bringing its total to 16.
It may be good to know that Denmark's sequencing numbers have gone way way down. From around 3000 to around 300 a week.

**Comment by InfrPopGen** [comment]
Thank you for proposing this recombinant. As it has shown negligible new detections over the past two months, it looks unlikely that this lineage has endowed the virus with any significant advantages, nor has is shown real international spread. Consequently, and acknowledging that the decline in sampling in Denmark would slow the apparent growth of this lineage, this can be closed for now. Please request re-opening should this clade start showing growth, spread, etc.
