### ISSUE TITLE
Potentially first mainland China recombinant: BA.5.2.48 x BF.7.14 [2 seq, Anhui]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1642]
Reviewing sequences from China submitted in the past week, I came across what looks like a bona fide mainland China lineage recombinant, with parents from the two highest prevalence lineages, exactly what one would expect.

Interestingly, but again not unexpectedly, Anhui is one of the provinces where BA.5.2.48 and BF.7.14 meet. BA.5.2.48 is a more South/Eastern lineage while BF.7.14 is more North/Western. Anhui is in between.

Definitely too small for designation but may help find similar recombinants if put in the tree by @AngieHinrichs :)

hCoV-19/Anhui/HBCDC-15/2023|EPI_ISL_16825332|2023-01-30
hCoV-19/Anhui/HBCDC-16/2023|EPI_ISL_16825333|2023-01-31

Both from Huaibei, 78yo female and 85yo male.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/25161793/217953724-9ad6759c-69f9-4095-a789-1888937713e3.png">

<img width="2540" alt="image" src="https://user-images.githubusercontent.com/25161793/217953729-e6725a3d-4578-407b-a12c-35e1a5916967.png">
<img width="2548" alt="image" src="https://user-images.githubusercontent.com/25161793/217953732-348454ad-2170-441b-8957-e1783df67d1b.png">

Breakpoint somewhere in ORF1b (>17k) or Spike (<23k).

Query for the BA.5.2.48 side: https://cov-spectrum.org/explore/China/AllSamples/Past3M/variants?variantQuery=%5B10-of%3A+C1627T%2C%09C2710T%2C%09C8626T%2C%09C11824T%2C%09G12160A%2C%09G12310A%2C%09C16616A%2C+C16887T%2C%09T17208C%2C%09C18744T%5D& (no good hits, the 2 other sequences are singlets and could be homoplasy).

Query for the BF.7.14 side: https://cov-spectrum.org/explore/China/AllSamples/Past3M/variants?variantQuery=%5B19-of%3A+G22599C%2C%09T22917G%2C%09C22993T%2C%09T23018G%2C%09G23040A%2C+G25290T%2C%09G26529A%2C%09T26858C%2C%09A27038G%2C%09C27259A%2C%09C27382G%2C%09T27383A%2C%09C27384T%2C+C27532T%2C%09C27889T%2C%09A28330G%2C%09G28361T%2C%09G28371T%2C%09C29632T%5D&

Good hits on the BF.7.14 side, there seems to be a cluster that donated that part with ~8 sequences on the Usher tree:
<img width="2011" alt="image" src="https://user-images.githubusercontent.com/25161793/217956148-3b7e5bdf-6d81-4df8-a646-be6aec6f0bd3.png">

https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3859b_5771a0.json

**Comment by FedeGueli** [comment]
Thx @corneliusroemer i spotted  this one too and maybe there are a couple more suspected recomb one of them a singlet of a BA.2.49/Dy.1 (wait i search for the epi-isl) . uploaded today still i didnt put too much time in tracking these ones, so a big thank you for doing the analysis.

**Comment by c19850727** [comment]
Yes as @FedeGueli mentioned there're a few other singlets. I've been monitoring this one found by Japan border screening, which is placed next to those 2 from Anhui (but probably not epi-related?)

![image](https://user-images.githubusercontent.com/86835836/217967472-1ec78a5e-29e6-4005-b8df-4ffbe786687f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14b54_58a010.json?c=gt-nuc_8626&label=id:node_6990373

**Comment by corneliusroemer** [comment]
@c19850727 if you looked into these, did you check whether some might come from the same recombination event/what their parents could be? For the Anhui BF.7.14 parent there's a nice hit. Maybe there's something similar for the other potential recombinants?

**Comment by AngieHinrichs** [comment]
> Definitely too small for designation but may help find similar recombinants if put in the tree by @AngieHinrichs :)

It is in the tree (as of the 2023-02-07 build).  And the filtering out of undesignated recombinants (and hopefully mostly plain old mixed/contaminated sequences) is based on nextclade!  🙂

**Comment by c19850727** [comment]
@corneliusroemer I tend to believe they're not the same recombination, as there are non-recombinant sequences having the same combo of private mutations as the 2 from Anhui?

**Comment by aviczhl2** [comment]
One more sequence from Hainan, carrying S3949N and T4175I(so probably from another branch of BA.5.2.48), sequenced on 2-10. 
EPI_ISL_16968126

**Comment by Mild1-ai** [comment]
> 来自海南的另一个序列，携带 S3949N 和 T4175I（因此可能来自 BA.5.2.48 的另一个分支），在 2-10 上测序。 EPI_ISL_16968126
I found the sequence you mentioned. The pedigree that can be displayed on GISAID is BF.7.14

**Comment by Mild1-ai** [comment]
How many sequences do you have now?

**Comment by corneliusroemer** [comment]
Seems to be stale, let's close for now
