### ISSUE TITLE
Multiple branches of XBB.1.5(or XBB*+S:486P?) with S:K97T in South Africa (234 seqs, Initially South Africa only but now in various countries, growth advantage inside South Africa against XBB.1.5)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1643]
I'm proposing this as @FedeGueli suggests me to propose a separate issue on XBB.1.5+S:K97T

Around 30% of the South African XBB.1.5 sequences have S:K97T, while none occur in elsewhere. 

First sequence: 2022-12-28, EPI_ISL_16574576
Last sequence: 2023-1-31, EPI_ISL_16823497

GISAID query: Spike_K97T,Spike_V83A, Spike_F486P, Spike_F490S
Countries: South Africa
No of sequences: 23

Sequences:
EPI_ISL_16520549, EPI_ISL_16574576, EPI_ISL_16580285,
EPI_ISL_16580293, EPI_ISL_16583854, EPI_ISL_16583857,
EPI_ISL_16738189-16738190, EPI_ISL_16738230, EPI_ISL_16738236,
EPI_ISL_16738239, EPI_ISL_16750841, EPI_ISL_16750887,
EPI_ISL_16750892-16750893, EPI_ISL_16750908, EPI_ISL_16823453,
EPI_ISL_16823460, EPI_ISL_16823462, EPI_ISL_16823471-16823472,
EPI_ISL_16823495, EPI_ISL_16823497

There are multiple branches contain this mutation.

<img width="1244" alt="Screen Shot 2023-02-10 at 12 04 22" src="https://user-images.githubusercontent.com/10445944/217998002-62f47663-eee6-43b2-88ca-d995bec02283.png">

Branch 1: XBB.1.5+S:K97T （16 seqs)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35321_59dfc0.json?f_userOrOld=uploaded%20sample&label=id:node_8012864

<img width="1220" alt="Screen Shot 2023-02-10 at 12 10 16" src="https://user-images.githubusercontent.com/10445944/217999160-6d82dfc6-f5d4-4fcd-beea-01c26373e06f.png">

Branch 2: XBB+S:486P+orf1ab:Q556K, M:E19Q(reversion)+S:G252V+M:D3N+**S:K444T,S:L452R**+S:K97T (4 seqs)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_35321_59dfc0.json?c=gt-S_97

<img width="1238" alt="Screen Shot 2023-02-10 at 12 36 55" src="https://user-images.githubusercontent.com/10445944/218001934-5869518f-047e-4624-81c9-9e20a42b817c.png">

Branch 3: XBB.1.5+C10369T+S:K97T,orf3a:T151I (2 seqs)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_35321_59dfc0.json?c=gt-S_97

<img width="1254" alt="Screen Shot 2023-02-10 at 12 44 24" src="https://user-images.githubusercontent.com/10445944/218002960-7e5e7625-e9ea-4aad-8947-c7eb8b04b8c7.png">

Branch 4: On a quite messed-up branch full of "reversions". (1 seq)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_35321_59dfc0.json?c=gt-S_97

**Comment by corneliusroemer** [comment]
Occurring multiple times in messy trees and just one country raises artefact suspicion, so let's watch this for a while before designating (if at all).

**Comment by aviczhl2** [comment]
> Occurring multiple times in messy trees and just one country raises artefact suspicion, so let's watch this for a while before designating (if at all).

Usher seems quite messy on XBB.1.5 sub-trees, there are many huge branches of "S:V252G reversions"  on the tree, as more than 5000 XBBs with S:486P do not have S:G252V (XBB.1 defining mutation), and usher seems to be categorizing most of them into XBB.1.5, and create back-and-forth 252G-252V sub-trees that makes everything very messy.


<img width="1013" alt="Screen Shot 2023-02-10 at 16 18 48" src="https://user-images.githubusercontent.com/10445944/218227378-652e24ca-75fc-4ad1-a9a2-04e4d9d36a57.png">

**Comment by aviczhl2** [comment]
This is an "XBB.1.5+S:V252G reversion" branch of 700+(902-129=773) descendants.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3952b_601230.json?f_userOrOld=uploaded%20sample&label=id:node_7992907

<img width="1213" alt="Screen Shot 2023-02-11 at 09 00 37" src="https://user-images.githubusercontent.com/10445944/218228707-0e9bbc66-a0f2-4b3f-aca2-1b9722525eea.png">

Another branch with 300+(404-83=321) descendants
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_3952b_601240.json?label=id:node_8008601
<img width="1231" alt="Screen Shot 2023-02-11 at 09 04 45" src="https://user-images.githubusercontent.com/10445944/218228953-d85d9698-5635-45b9-aff5-0db988b2ad41.png">

**Comment by corneliusroemer** [comment]
Ah that calls for branch specific masking 🙃  @AngieHinrichs 

The flip flopping is due to artefactual reversions to reference combined with that site also often being N due to dropout.

But generally, these flip flop branches are not of highest quality so need to be careful.

**Comment by FedeGueli** [comment]
Flip flop branches...great definition!

**Comment by aviczhl2** [comment]
> Ah that calls for branch specific masking 🙃 @AngieHinrichs
> 
> The flip flopping is due to artefactual reversions to reference combined with that site also often being N due to dropout.
> 
> But generally, these flip flop branches are not of highest quality so need to be careful.

Yeah, most of the 5000+ non-252 XBB.1.5 sequences are N dropouts.

However, 451 of them do have 252G. Are they really XBB.1.5? Where shall they be placed? 

<img width="1172" alt="Screen Shot 2023-02-11 at 21 56 18" src="https://user-images.githubusercontent.com/10445944/218261883-47a38587-7098-457b-84e0-e2cad5193ed1.png">

**Comment by aviczhl2** [comment]
35 viruses now. 
Exported from South Africa to Singapore. EPI_ISL_16905270

**Comment by aviczhl2** [comment]
50 seqs as of 2.17

**Comment by FedeGueli** [comment]
There has been a big upload of xbb.1.5 + S:k97T from South Africa , the total count now doubled to over 100

**Comment by aviczhl2** [comment]
> Spike_K97T,Spike_V83A, Spike_F486P, Spike_F490S

Yeah, 106 seqs now, and it is appearing in USA too.

**Comment by corneliusroemer** [comment]
I'd prefer to wait for the S:K97T to show up outside of South Africa, as the sequence quality is not great and it could be an artefact. As soon as we see a few more high quality sequences let me know and I'll designate.

**Comment by aviczhl2** [comment]
One more from Northern Ireland 
EPI_ISL_16996428

**Comment by aviczhl2** [comment]
130 seqs now.

It seems that branch 1 (XBB.1.5+S:K97T) is real, some of the additional branches are simply branch 1 but assigned to other branches due to having another common mutation with other XBB.1.5s.

But not sure about branch 2 as no more seqs coming from this branch.

**Comment by aviczhl2** [comment]
> > Ah that calls for branch specific masking 🙃 @AngieHinrichs
> 
> I added some branch-specific masking ([ucscGenomeBrowser/kent@ac5d7c6](https://github.com/ucscGenomeBrowser/kent/commit/ac5d7c6726a1d4ccbea22592fa64de309869e9bf)). Let me know if you see a difference, and beware that recombinants placed in XBB might have some missing reversions due to the masking.

Yeah it works somehow and result in new branch arrangement for branch 2. Now it has 10 seqs.

However, it seems that the new arrangement is still not where it shouldn't be, with another flip-flop reversion...

[new place for branch 2](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1f91a_ea1e00.json?label=id:node_7685702)

**Comment by aviczhl2** [comment]
135 seqs now.

**Comment by AngieHinrichs** [comment]
> However, it seems that the new arrangement is still not where it should be, with another flip-flop reversion...
> 
> [new place for branch 2](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1f91a_ea1e00.json?label=id:node_7685702)

Ah, thanks for pointing that out.  That is a different type of problem: the branch seems to share A27038T, T27039A, C27040A with USA/NC-CORVASEQ-CLT-014136/2023 which was placed with A24730T and T27810C (ORF7b:F19L).  But that branch doesn't have A24730T and T27810C so it gets reversions -- the 3 shared mutations are stronger than the 2 disagreeing mutations that require mutations.  (Having 3 mutations in consecutive bases (27038-27040) is usually though not always a sign of sequencing errors.)  I will see if I can clean that up by temporarily removing USA/NC-CORVASEQ-CLT-014136/2023 and reoptimizing.

**Comment by aviczhl2** [comment]
177 seqs now, detected in Austria and England.

**Comment by aviczhl2** [comment]
This one starts to show 14% growth advantage against XBB.1.5 in South Africa.

[compare link](
https://cov-spectrum.org/explore/South%20Africa/AllSamples/Past6M/variants?nextcladePangoLineage=xbb.1.5*&aaMutations1=S%3AK97T&nextcladePangoLineage1=xbb.1.5*&analysisMode=CompareToBaseline&)

<img width="1188" alt="Screen Shot 2023-03-09 at 11 46 09" src="https://user-images.githubusercontent.com/10445944/223911578-ac8574f5-403e-4105-bdca-f125be6f7ad4.png">

**Comment by aviczhl2** [comment]
187 seqs now, one more country of Poland.

**Comment by M-J-Murray** [comment]
This has been merged incorrectly into the `lineage_notes.txt`, instead of `S:K97T`, you have merged `S:97T`.
