### ISSUE TITLE
XBB.1 sublineage with S:F486A (32 seq, Denmark, Turkey, Germany, Israel, Austria, USA , Singapore, Australia, Netherlands, Switzerland)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1646]
Proposal for a sublineage of XBB.1
Earliest sequence: 21.11.2022 (Turkey)
Countries detected: Denmark, Turkey, Germany, Israel, Austria, USA

This sublineage of is defined by S:F486A and was found in five countries so far. It clusters badly in usher because of S:F486A. Subclade also carries S:R346T.

Defining mutation:
T23019C
T23018G = S:F486A

[OLD Gisaid query: T23018G, T23019C, A20262G]
**Better query: T23018G, T23019C, C6388T**

![grafik](https://user-images.githubusercontent.com/102166254/218122324-1447fcc8-fbcc-4e15-bbde-d1c580dd7cd8.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9ed_6573d0.json?c=userOrOld&label=id:node_7983111

![grafik](https://user-images.githubusercontent.com/102166254/218122462-65ed90c9-1147-4972-9e3c-92578663be55.png)

![grafik](https://user-images.githubusercontent.com/102166254/218123351-efc7878d-b975-4bd8-9b5a-fd7fddf24018.png)

EPI_ISL_16330609, EPI_ISL_16414341, EPI_ISL_16414465, EPI_ISL_16423847, EPI_ISL_16424061, EPI_ISL_16591836, EPI_ISL_16591959, EPI_ISL_16646954, EPI_ISL_16739023, EPI_ISL_16813268, EPI_ISL_16831851, EPI_ISL_16831851, EPI_ISL_16847478

OQ351058.1

**Comment by AnonymousUserUse** [comment]
![image](https://user-images.githubusercontent.com/113214374/218135728-c78bd471-0196-4f9d-be19-2392c956303b.png)

I do not think the clade with reversion S:T346R is real. Probably it is just bought by dropout of Turkish sequences at the codon S:346.

**Comment by agamedilab** [comment]
17 as of 20.02.23.

![grafik](https://user-images.githubusercontent.com/102166254/220107198-f3eb0b3a-b297-4b03-9696-178b48de75a2.png)

**Comment by FedeGueli** [comment]
22 as today

**Comment by agamedilab** [comment]
31 on usher, 32 on GISAID as of 09.03.23. 
Better query: T23018G, T23019C, C6388T

![grafik](https://user-images.githubusercontent.com/102166254/223947350-8642e6f5-ea44-4f88-a675-4ee1b7170221.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_155b_984a40.json?c=gt-nuc_6388

**Comment by corneliusroemer** [comment]
I'll have a look, but I'm a little cautious because Turkish sequences have had big quality problems in the past.

Based on dates of samples this isn't explosive so not urgent.

There's a lot of diversity. Hence old most recent common ancestor.

**Comment by FedeGueli** [comment]
38 as today

**Comment by corneliusroemer** [comment]
Designated - it's actually quite clean - there are lots of other mutations that are correlated in this lineage so not an issue. It seems to be particularly common in Turkey.
