### ISSUE TITLE
BQ.1.1.28 (S:P251L, ORF1b:P976S) Sublineage with S:S247N, S:Y248S (91 seq, Feb 18)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1648]
### **Description**
**Sub-lineage of:** BQ.1.1.28
**Earliest sequence:** 2022-12-12, Italy, EPI_ISL_16235776
**Most recent sequence:** 2023-2-5, Italy, EPI_ISL_16824351
**Countries circulating:** Italy (46), Austria (6), Germany (6), USA (3), Denmark (2), Belgium (1), England (1), France (1), Netherlands (1), Slovakia (1)
**Number of Sequences:** 68
**GISAID Query:** Spike_S247N, Spike_Y248S, Spike_P251L
**CovSpectrum Query:** Nextcladepangolineage:BQ.1.1.28 & S:S247N & S:Y248S
**Substitutions on top of BQ.1.1.28:**
**Spike:** S247N, Y248S
**Nucleotide:** G22302A, A22305C, A27388G

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1.1.28_S247N_Y248S_subtreeAuspice1_genome_b2ba_6fbba0.json
 
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/33738461/218267984-5d477a38-7794-41fc-981a-83d1456d510a.png">

**Evidence**
The S:S247N-S:Y248S combo has arisen independently close to 20 times, most prominently in BA.2.38.1 but also in singlets and clusters of numerous other lineages, including BA.1, BA.1.1, several BA.2 (non-38.1), BA.2.12.1, BA.2.3, BA.2.3.10, BA.2.9, BA.4.6.2, BA.5.1, BA.5.2.1, BE.1, BQ.1.1 (non-.28), and a few others. There's clearly some sort of positive epistasis going on between these two consecutive AA residues. This is the first time these two mutations have been accompanied by S:P251L, which seems to be a mutation on the rise in recent weeks.

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/33738461/218268618-27544fbf-b3f7-4fca-99a0-97029fd58edf.png">

With the renaissance in mutations, insertions, and deletions around S:248 (see my summary in #1635 for a bit more detail), it's not surprising to see this mutational combination recurring again and spreading. The first sequences in this lineage appeared in Italy, but it has now been sequenced in eight other countries in Europe and to the USA, where three sequences have occurred.

Recently, two sequences in this lineage appeared in Germany with additional spike mutations S:I233V and S:T859N. One of those two sequences also has S:K182E, which has been a convergent mutation in numerous lineages of late. (EPI_ISL_16884271, which, like many German sequences, unfortunately has unlabeled missing coverage and therefore artifactual reversions downstream in spike.) S:T859N appeared regularly in Delta sequences, and in the last several months, various S:T859 mutations have started to show up, mainly S:T859I, S:T859S, and S:T859N. @oobb45729 recently pointed out that it's possible T859N restores a salt bridge that was lost with D614G.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16220200, EPI_ISL_16220216, EPI_ISL_16220218, EPI_ISL_16220219, EPI_ISL_16220224, EPI_ISL_16220232, EPI_ISL_16220242, EPI_ISL_16235776, EPI_ISL_16240973, EPI_ISL_16240991, EPI_ISL_16293315, EPI_ISL_16392041, EPI_ISL_16482555, EPI_ISL_16485396, EPI_ISL_16514385, EPI_ISL_16524414, EPI_ISL_16526250, EPI_ISL_16527537, EPI_ISL_16529252, EPI_ISL_16530788, EPI_ISL_16539925, EPI_ISL_16540849, EPI_ISL_16548066, EPI_ISL_16555396, EPI_ISL_16555411, EPI_ISL_16582112, EPI_ISL_16593378, EPI_ISL_16600505, EPI_ISL_16612933, EPI_ISL_16614036, EPI_ISL_16619798, EPI_ISL_16619802, EPI_ISL_16636364, EPI_ISL_16647791, EPI_ISL_16647803, EPI_ISL_16686376, EPI_ISL_16696164, EPI_ISL_16697237, EPI_ISL_16712835, EPI_ISL_16713222, EPI_ISL_16713226, EPI_ISL_16713227, EPI_ISL_16713806, EPI_ISL_16737796, EPI_ISL_16737803, EPI_ISL_16737804, EPI_ISL_16737805, EPI_ISL_16737986, EPI_ISL_16740412, EPI_ISL_16752945, EPI_ISL_16754322, EPI_ISL_16824351, EPI_ISL_16845424, EPI_ISL_16845975, EPI_ISL_16846017, EPI_ISL_16846115, EPI_ISL_16846119, EPI_ISL_16846120, EPI_ISL_16846124, EPI_ISL_16854629, EPI_ISL_16857541, EPI_ISL_16859474, EPI_ISL_16868833, EPI_ISL_16874639, EPI_ISL_16876753, EPI_ISL_16882132, EPI_ISL_16884271, EPI_ISL_16885253
</details>

**Comment by Mydtlwn** [comment]
S:18X locus has appeared frequently recently, including 181, 182 and 185 mutations, which are worthy of attention. Besides, 187 loci have performed well.
