### ISSUE TITLE
Potential sublineage of B.1.1.7 circulating in Israel with N-protein A119S, T135I, Q281K and L331F

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#165]
Potential sublineage 1 of B.1.1.7 (38 samples in Israel, and that's more than half of their alpha sequences since June)
**Earliest sequence:** 2021/4/11 (Israel)
**Most recent sequence:** 2021/7/6 (Israel)
**Countries circulating:** Israel
In addition to usual B.1.1.7 mutations, this potential new sublineage also has:
**N:** A119S, T135I, Q281K, L331F
**ORF1a:** L730F
**ORF1b:** T730I, G2337V
**S:** D138H, F490S

**Genomes:**
EPI_ISL_3019656, EPI_ISL_3019684, EPI_ISL_3019786-3019787,
EPI_ISL_3019790-3019791, EPI_ISL_3019796, EPI_ISL_3019830,
EPI_ISL_3021558, EPI_ISL_3021639, EPI_ISL_3021642,
EPI_ISL_3021656, EPI_ISL_3021665, EPI_ISL_3021727,
EPI_ISL_3021743, EPI_ISL_3021816, EPI_ISL_3021868,
EPI_ISL_3022154, EPI_ISL_3022188, EPI_ISL_3022199,
EPI_ISL_3022204, EPI_ISL_3022230, EPI_ISL_3022235,
EPI_ISL_3022251, EPI_ISL_3022270, EPI_ISL_3022272,
EPI_ISL_3022278, EPI_ISL_3022320, EPI_ISL_3022344,
EPI_ISL_3024196, EPI_ISL_3024476, EPI_ISL_2545298, EPI_ISL_2545250

Evidence:
![image](https://user-images.githubusercontent.com/86835836/127745749-975527a6-beb6-4cd5-bca8-fcb55217abb0.png)

BTW, there might be some other potential sublineages associated with ORF1a L730F in Kenya, Germany and the US as well.

**Comment by chrisruis** [comment]
Thanks @c19850727. We've added this as Q.5 in [v1.2.64](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.64). There's a few sequences in this clade in the UShER tree that are associated with multiple GISAID accessions and these multiple accessions are from different lineages so we didn't include these sequences in the designation: Israel/SMC-7005181/2021, Israel/SMC-7005232/2021, Israel/SMC-7005293/2021, Israel/SMC-7005452/2021, Israel/SMC-7005529/2021, Israel/SMC-7005257/2021, Israel/SMC-7005604/2021
