### ISSUE TITLE
lineage_notes.txt(EF.2.BF.7.26.BF.37.XBB.2.1)

### ISSUE THREAD

**Issue by DoropFan** [cov-lineages/pango-designation#1650]
EF.2
B.1.1.529.5.3.1.1.1.1.1.1.13
B.1.1.529.5.3.1.1.1.1.1.1.13,2

BF.7.26
B.1.1.529.5.2.1.7.25
B.1.1.529.5.2.1.7.26

BF.37
ORF1a:S994L
ORF1a:S944L

XBB.2.1
S:N764S
S:N764R
![001note](https://user-images.githubusercontent.com/118802079/218367499-16a74c06-1aad-4843-8e82-a244fabbaf59.jpg)

**Comment by Mydtlwn** [comment]
@InfrPopGen

**Comment by corneliusroemer** [comment]
I'll fix it - it's my fault!
