### ISSUE TITLE
Possible recombinant lineage between BR.2.1 and CJ.1 (or XBF or XBK)   defined by ORF1b:R2613H ,S:I486P S:L452L(rev), S:F490S  ,Orf8:S82T, Orf8:S67S (rev) - 11 sequences 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1653]
Thank to the precious help from @josetteschoenma i can now propose this very recent recombinant sublineage between BR.2.1 and CJ.1 (or XBF or XBK) that  likely emerged in Australia .

First of all i want to highlight the defining mutations which distinguish it from parental BR.2.1 lineage:
**ORF1b:R2613H ,S:I486P, S:L452L(rev), S:F490S  ,Orf8:S82T, Orf8:S67S** (rev)

So i guess the bit from 1 to 22916 is from BR.2.1 and from 22917 to the end from CJ.1

taking a look at nuc mutations now:
A8812G quite rare mutation in the last 6 months but sampled in two BR.2.1 from December22 
G21305A (ORF1b:R2613H) Homoplasic it pops up regularly in quite all sublineages but never got fixed
G22917T reversion of S:452R (def of BR*) to L (as in CJ.1,XBF,XBK)
A23018C, S:F486P as CJ.1,XBF,XBK
T23019C S:F486P as CJ.1,XBF,XBK
T23031C S:F490S (def in CJ*,XBF,XBK , absent in BR.2.1) 
T28137A reversion of Orf8:S67F (defining in BR.2.1 )to S  

Why it is not BR.2 but BR.2.1? 
cause before the reversion of orf8:67F to S happened  (> C28093T > C5812T > T28093C ) it has C5812T that is nearly in 65% of BR.2.1 sequences

**Usher Tree:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3276c_a2bc10.json?c=userOrOld&label=id:node_8243759
<img width="1131" alt="Schermata 2023-02-13 alle 16 11 14" src="https://user-images.githubusercontent.com/87669813/218495740-615bc7d8-14f1-4b77-968b-21971d2c3099.png">

<img width="531" alt="Schermata 2023-02-13 alle 16 10 56" src="https://user-images.githubusercontent.com/87669813/218495651-4e77d24e-9b66-4c0e-8ba3-06f4ddb130a9.png">

**Nextclade**:
<img width="410" alt="Schermata 2023-02-13 alle 16 11 37" src="https://user-images.githubusercontent.com/87669813/218495844-15468c35-79fd-43d8-9c14-7de3738855d9.png">

**Gisaid query**:
Spike_F486P,NS8_S82T

**Sequences**: 6
EPI_ISL_16887591, EPI_ISL_16887750, EPI_ISL_16887834,
EPI_ISL_16899159, EPI_ISL_16902439, EPI_ISL_16902451

It is interesting to note that samples are from 3 different australian states (NSW, Queensland, South Australia) and all very recent (after 30/1/2023)

I want to thx @zach-hensel for suggesting to add XBF to the likely parents list. I focused on spike that it is the same. but given the high prevalence of XBF in Australia is more likely to be XBF the parent than CJ.1 or XBK

**Comment by FedeGueli** [comment]
One more sequence came from Victoria. 4th state.

**Comment by FedeGueli** [comment]
My query finds 10 , @c19850727 independently spotted it and  proposed it in #1669

**Comment by FedeGueli** [comment]
closing this and maintaing open the #1669 by @c19850727

**Comment by JosetteSchoenma** [comment]
XBY
