### ISSUE TITLE
New XBB.1 sublineage with S:F486P orf1a:K120R ,   - likely emerged from Malaysia -25 sequences - Singapore, Japan,

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1654]
_EDITED ON 09-03-23
Now the tree has competely changed so i am editing the proposal to start this lineage with:
Orf1:K120R (A624G)> S:F486P, C27297A

justified by the following tree:

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d48_a49000.json?c=userOrOld&label=id:node_7760413
 
<img width="1135" alt="Schermata 2023-03-09 alle 23 42 17" src="https://user-images.githubusercontent.com/87669813/224176828-6589b183-7729-4499-92e7-5c3587646b30.png">

15 sequences

Gisaid query:
A624G,C27297A,T23018C

has to be noticed that all the three "branches of this sublineage have additional spike mutations we have seen in variant soup at S:255 and s:256 but also at S:158 as Delta (but different AA)_

*************************************************************************************************************

**ORIGINAL proposal:**

### Put here to simplify the work in monitoring XBB.1 * 486P sublineages.
This is totally independent from the others already designated.

it carries two additional defining mutations:  Orf1a:K120R , Orf1a:k261N beyond S:F486P

**Tree:**
<img width="1144" alt="Schermata 2023-02-13 alle 17 13 24" src="https://user-images.githubusercontent.com/87669813/218511548-c761c531-5795-4a2f-8660-d717ef0aa568.png">
<img width="1124" alt="Schermata 2023-02-13 alle 17 12 51" src="https://user-images.githubusercontent.com/87669813/218511405-ecd12287-ba43-47f1-8e76-0e7a65c5a88e.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_430f4_a60ea0.json?c=userOrOld&label=id:node_9610401

**Gisaid query**:NSP1_K120R,NSP2_K81N, Spike_F486P

it has to be highlighted that one sample (with travel history from Malaysia) has also S:255F,S:T678P and N:E136Q

**Sequences:**
EPI_ISL_16847528, EPI_ISL_16899415, EPI_ISL_16899433 all of them have been sampled in Singapore and in February 2023
( 2 imported into Singapore from Malaysia, one local case in an elderly man)

**Defining mutations:** 
Orf1:K120R (A624G) then Orf1a:K261N G1048T), C27297A,  S:F486P (T23018C)

**Comment by AnonymousUserUse** [comment]
I think there is no evidence that Orf1a:k261N occurred beyond S:F486P, right?

**Comment by FedeGueli** [comment]
two new samples of this one came from Israel  cc @shay671

**Comment by FedeGueli** [comment]
two new samples from Japan and Singapore.

**Comment by FedeGueli** [comment]
2 new sequences uploaded from Malaysia (the first directly sampled there) confirming initial.hypothesis this arose in Malaysia

**Comment by FedeGueli** [comment]
10 sequences as today. Last samples from elderly people in Singapore (local cases)

**Comment by FedeGueli** [comment]
Now the tree has competely changed so i am editing the proposal to start this lineage with:
**Orf1:K120R (A624G)> S:F486P, C27297A**

justified by the following tree:

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d48_a49000.json?c=userOrOld&label=id:node_7760413
<img width="1165" alt="Schermata 2023-03-09 alle 23 40 00" src="https://user-images.githubusercontent.com/87669813/224176503-77047aac-71dc-490f-b08d-4cbbbcf47cef.png">

15 sequences

Gisaid query:
**A624G,C27297A,T23018C**

**Comment by FedeGueli** [comment]
20 samples of this one, two new samples from two different district of Japan

**Comment by FedeGueli** [comment]
25 sequences as today . Last samples from Japan and Singapore, one of them with travel history from Philippines.

**Comment by alurqu** [comment]
Lineage notes and the git commit log say this is XBB.1.5.27, which makes sense as the next-available designation, but this has been added to the XBB.1.27 milestone instead of the XBB.1.5.27 milestone.

**Comment by Mydtlwn** [comment]
This is indeed a mistake, the latest specified branch in the subbranch of XBB.1 is currently XBB.1.23, while the latest specified branch in the subbranch of XBB.1.5 is XBB.1.5.27

**Comment by HynnSpylor** [comment]
It should be XBB.1.24 (without T17124C)

**Comment by FedeGueli** [comment]
It hs been designated XBB.1.5.27 , just the milestone is uncorrect. About the fact to be a broader xbb.1.5 descendant or XBB.1 independent 486P acquisition i tend to think the second is more likely cause its geographical origin from Malaysia is quite well documented  , but too few evidence to state it is not a broader xbb.1.5 descendant for certain t

**Comment by corneliusroemer** [comment]
Sorry - I made a mistake here.

It should indeed be XBB.1.24 and not XBB.1.5.27 - I messed up somewhere along the way.

I'm fixing.

**Comment by FedeGueli** [comment]
Please remove XBB.1.27 milestone makes a bit mess when searching for it!
