### ISSUE TITLE
Twenty four DN.1 sequences with additional mutation orf1a_T4368I. Six of them have also additional mutation orf1a_E1205D(nsp3_E387D) and orf1a_G4178V(nsp9_G38V)

### ISSUE THREAD

**Issue by VirologiaHUCA** [cov-lineages/pango-designation#1655]
By VirologiaHUCA
Description
A) Eighteen sequences 
Sub-lineage of: DN.1
Earliest sequence: 2022-12-16
Most recent sequence: 2023-01-26
Countries circulating: Netherlands, United Kingdom

B) Six sequences
Sub-lineage of: DN.1
Earliest sequence: 2022-12-14
Most recent sequence: 2023-01-29
Countries circulating: Spain

Written description
A) Eighteen sequences (EPI_ISL_16375093 / EPI_ISL_16406391 / EPI_ISL_16407664 / EPI_ISL_16441338 / EPI_ISL_16441340 / EPI_ISL_16437477 / EPI_ISL_16440070 / EPI_ISL_16440748 / EPI_ISL_16441988 / EPI_ISL_16442462 / EPI_ISL_16442432 / EPI_ISL_16524980 / EPI_ISL_16524982 / EPI_ISL_16586133 / EPI_ISL_16586139 / EPI_ISL_16586148 / EPI_ISL_16692681 / EPI_ISL_16845541) from Netherlands and UK have gained mutation orf1a_T4368I(nsp10_T115I). 

B) Six sequences (EPI_ISL_16376394 / EPI_ISL_16395173 / EPI_ISL_16645315 / EPI_ISL_16751167 / EPI_ISL_16905385 / EPI_ISL_16905386) from Spain (Asturias and Catalunya) have gained mutations orf1a_T4368I(nsp10_T115I), orf1a_E1205D(nsp3_E387D) and orf1a_G4178V(nsp9_G38V)

Genomes
A) EPI_ISL_16375093 / EPI_ISL_16406391 / EPI_ISL_16407664 / EPI_ISL_16441338 / EPI_ISL_16441340 / EPI_ISL_16437477 / EPI_ISL_16440070 / EPI_ISL_16440748 / EPI_ISL_16441988 / EPI_ISL_16442462 / EPI_ISL_16442432 / EPI_ISL_16524980 / EPI_ISL_16524982 / EPI_ISL_16586133 / EPI_ISL_16586139 / EPI_ISL_16586148 / EPI_ISL_16692681 / EPI_ISL_16845541 

B) EPI_ISL_16376394 / EPI_ISL_16395173 / EPI_ISL_16645315 / EPI_ISL_16751167 / EPI_ISL_16905385 / EPI_ISL_16905386

Evidence
![image](https://user-images.githubusercontent.com/105294581/218756209-8356233c-54a4-4a31-997d-328fb28fcc65.png)

**Comment by InfrPopGen** [comment]
I think Usher has this as BQ.1.1, rather than DN.1 (so the former for cov-spectrum at the moment); then the path from BQ.1.1 is nt:C13368T (ORF1a:T4368I) > nt:A16842G > nt:A22003T (S:K147N), nt:C20628T

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As its relative growth was never very strong or clear, and there don't appear to have been any new detections for about a month now, this can be closed. Please request re-opening if this clade reemerges with strong growth relative to its parent or other co-circulating lineages at that time.
