### ISSUE TITLE
BQ.1.8 -> XBF-like recomb, BQ.1.8 spike with F486P. [Canada, 3 seq.]

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1658]
**Description**
Recombinant of BQ.1.8 -> XBF-like Breakpoint between 22942 and 23018 (S:460-S:486)
Earliest sequence: 2022-01-22, Canada Ontario. EPI_ISL_16730662
Most recent sequence: 2022-02-02, Canada Ontario. 
Countries circulating: Canada (Ontario) - 3
Number of Sequences: 3
GISAID & CovSpectrum Query: C7735T,C1779T,T23018C
Substitutions on top of parental BQ.1.8: C2485T,A3181G,T4873C,G5518A,C6781T,A7740G,C9808T (only adds ORF1a:D2492G)
Substitutions on top of parental XBF-like: none

**USHER Tree**
USHER tree is a mess due to being a recombinant, but the proposed sequences cluster. I'll just link [here](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1344f_ba6cb0.json)

**Evidence**:
The 3 sequences are uploaded on different days, and have non-matching patient data, and the sequences are fairly unique due to the large number of mutations on the BQ.1.8 side. However, these mutations are also in BQ.1.8 that are circulating in Canada -- there is even a sequence that has all of them, though it has now been removed from GISAID. There are other sequences that are only missing one of those mutations, meaning this recombination event likely happened in a non-chronic infection. 

I am proposing this at just 3 sequences because I believe that this is the first clear time BQ.1* has truly gained S:F486P and been given a chance to succeed. If this lineage doesn't spread further, then I believe that is insightful as well.

**Genomes**: EPI_ISL_16840526, EPI_ISL_16730662, EPI_ISL_16905900

**edit:** I initially claimed this was an XBB.1.5 recomb, so the comments in this post might mention that. I think @FedeGueli is right, and XBF is most likely, but there are a few possible candidates for the latter part of the genome in my proposed lineage.

**Comment by MCB6** [comment]
Apropos a recent conversation about "attempted lethal" mutagenesis stimulating recombinations ( https://github.com/cov-lineages/pango-designation/issues/895 ) ... here, too, I see that 7 out of 7 BQ-side private mutations are transitions?

**Comment by Sinickle** [comment]
Good catch that the mutations are transitions. At least in the other BQ.1.8 sequence that closest matches, I see two additional transition mutations on the side that got cut off by XBB.1.5, and no additional transversions. 

That being said, I think it is more likely a coincidence that this recombination event happened on a BQ.1.8 branch that is possibly the result of a mutagenic drug. 

Here are some similar BQ.1.8 sequences: 
EPI_ISL_16324644, EPI_ISL_16323574, EPI_ISL_16840526, EPI_ISL_16730662, EPI_ISL_16630868, EPI_ISL_16629887

They are from different patients. Since the BQ.1.8 part of my proposed lineage is so similar to these, I think it's there's a good chance the recombination event happened outside of the patient receiving treatment. Additionally, these sequences don't seem to have any clear disadvantageous mutations in the section that is replaced by XBB.1.5.

**Comment by corneliusroemer** [comment]
Ah just spotted this one too when querying GISAID for the still relatively rare combo of Spike_L452R, Spike_F486P (mostly XAY)

Are you sure this is XBB.1.5? Given that ORF8 stop is reverted, isn't it more parsimonious this was a different XBB + S:F486P? There are a few of them: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF8%3A8.%2CS%3AF486P&nextcladePangoLineage=XBB*& (though some of the reversions may be artefacts)

**Comment by Sinickle** [comment]
@corneliusroemer no, I'm not sure it's XBB.1.5. 
However, I did check with basically the same query you did, and the top match for it (XBB.6.1) is invalid because it has a mutation at 25539 that is absent in the proposed lineage. 

Then, the best guess appears to be XBB.1.5. 
It is the same picture for if you limit it to Canada (since the BQ.1.8 parental sequences seem to be limited to Canada, I think that is an okayish assumption) XBB.1.5 is the most frequent one that fits the description, and actually other variants' sequences would have extra mutations.  

If you think it should just be called "XBB* with S:F486P" then I'm fine with that. There's no certainty it is XBB.1.5.

**Comment by FedeGueli** [comment]
@corneliusroemer @Sinickle why not CJ.1 XBK or XBF? You cannot distinguish them from XBBè4896P after S:F490S ahead 
CJ.1 looks like a very recombination prone lineage (maybe for some reason longer persistance?)

**Comment by Sinickle** [comment]
@FedeGueli Great call! Absolutely I just neglected to consider the non-XBB S:F486P S:F490S variants. 

XBF seems most likely, having dozens of recent sequences in Ontario, where these sequences are from.

**Comment by ktmeaton** [comment]
Just getting caught up on this discussion! To confirm, are there any diagnostic mutations to resolve the second parent as XBF (rather than a BA.2.75 descendant like CJ.1 or XBK)? Or is the second parent considered XBF primarily because of the XBF prevalence in Canada?

**Comment by FedeGueli** [comment]
> Just getting caught up on this discussion! To confirm, are there any diagnostic mutations to resolve the second parent as XBF (rather than a BA.2.75 descendant like CJ.1 or XBK)? Or is the second parent considered XBF primarily because of the XBF prevalence in Canada?

No there isnt . it is impossible to distinguish CJ.1/XBF/XBK/XBQ from rbd ahead.

**Comment by Sinickle** [comment]
Yup! It's as Fede said and you're suspecting -- chose XBF as the most prevalent exact fit in the area.

**Comment by Sinickle** [comment]
Seems dead. I think this is evidence that S:F486P isn't magic on BQ.1, like it is on XBB*
