### ISSUE TITLE
CH.1.1.1 with S:S486P (2 seq, Austria, Canada) 

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1659]
Here come the first two sequences of CH.1.1 with S:486P.
EPI_ISL_16857346
EPI_ISL_16837429
![CH](https://user-images.githubusercontent.com/115189228/218890835-99a2a5a7-af72-4d8d-bd6d-9db48d8eb8bf.png)

CH.1.1.1 then C17703T then C27684T then A29031C(N:E253A) then C6429T(ORF1a:P2055L) then T23018C(S:S486P).

**Comment by corneliusroemer** [comment]
Interesting, they were uploaded on 6th and 8th of February - so not a super super recent development.

But they cluster, so likely real.

Would be great if you also showed a more zoomed out view and shared a link to the tree, so it doesn't need to be recreated by others who want to have a look at it.

Zoomed out:
<img width="1850" alt="image" src="https://user-images.githubusercontent.com/25161793/218905260-30f85b0d-ee3b-47a6-ba3a-26afa9a1b9c9.png">

Link: https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2413a_c37090.json?gt=S.486L

**Comment by FedeGueli** [comment]
Unluckily a new one popped up today in England.

**Comment by FedeGueli** [comment]
i found 5 today with NSP16_Q28R,Spike_K444T,Spike_L452R,Spike_F486P , looking at them if related.

**Comment by oobb45729** [comment]
CH.1.1*+S:486P has 8 results now. They belong to different clusters though.
![1](https://user-images.githubusercontent.com/115189228/224851429-603180f4-8454-42d6-b209-97f1a112434d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_375bc_fa74d0.json?f_userOrOld=uploaded sample&label=id:node_7938303

**Comment by oobb45729** [comment]
That DV.3 cluster is interesting. 4 new nsp2 mutations. ORF1a:E377K, A427V, L469F, L681F. They have Orf1a:M85del as well.
