### ISSUE TITLE
Potential sublineage of C.36.3 circulating in Germany, Netherlands and Belgium

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#166]
Potential sublineage of C.36.3 (15 samples in Europe, mainly Germany)
**Earliest sequence:** 2021/5/11 (Netherlands)
**Most recent sequence:** 2021/7/14 (Germany)
**Countries circulating:** Germany, Netherlands, Belgium
In addition to usual C.36.3 mutations, this potential new sublineage also has:
**N:** L219F
**ORF1a:** del141/143, Y196H, L3691S
**ORF1b:** A520V
**ORF7a:** T14I
**S:** T478R

**Genomes:**
EPI_ISL_2303971, EPI_ISL_2470202, EPI_ISL_2470204,
EPI_ISL_2472418, EPI_ISL_2635901, EPI_ISL_2635904,
EPI_ISL_2636913, EPI_ISL_2714902, EPI_ISL_2760272,
EPI_ISL_2760275, EPI_ISL_2788235-2788237, EPI_ISL_3044505,
EPI_ISL_3057635

**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/127972905-dd609483-403a-490f-9ebb-4312a81034f4.png)

**Comment by chrisruis** [comment]
Thanks @c19850727. It't not clear that there's an epidemiological event associated with this clade - the geographical distribution is similar to surrounding sequences and the mutations are not sufficient to require a new designation at this stage. We therefore recommend that for now these sequences are referred to as C.36.3

**Comment by shay671** [comment]
Since the report on this variant it's been uploaded in more cases (24 now). 
I find this one quite interesting as it is seems like a variant based variant and not just some genetic drift. 

![image](https://user-images.githubusercontent.com/80166370/129246847-09ccf1d9-4c2a-40a1-89a8-c8e8baf307e2.png)
