### ISSUE TITLE
XBB.1.5 with S:348T and ORF7a:V74A [Northeast USA and Canada, 27 sequences]

### ISSUE THREAD

**Issue by rquiroga7** [cov-lineages/pango-designation#1660]
Sub-lineage of: XBB.1.5
Earliest sequence: 2022-12-06
Most recent sequence: 2023-02-04
Countries circulating: USA (states: New York, New Jersey, Maryland, Ohio, Pennsylvania) and Canada

The proposed lineage has S:A348T, which is predicted by Bloom calculator to negatively affect RBD expression and ACE2 binding, but also to have a significant antigenic evasion effect. Perhaps XBB.1.5 increased ACE2 binding due to 486P allowed this rare mutation (only 610 sequences in GISAID), to provide increased fitness through antigenic evasion.

A sub-branch of this lineage appears to have incorporated nsp3:A991T (ORF1ab:A1809T), which is predicted to increase fitness in the Bloom lab fitness calculator (https://jbloomlab.github.io/SARS2-mut-fitness/nsp3.html).

Genomes:

EPI_ISL_16344978
EPI_ISL_16381444
EPI_ISL_16489210
EPI_ISL_16668655
EPI_ISL_16684729
EPI_ISL_16755815
EPI_ISL_16763677
EPI_ISL_16763724
EPI_ISL_16816540
EPI_ISL_16835989
EPI_ISL_16836031
EPI_ISL_16851232
EPI_ISL_16851844
EPI_ISL_16860731
EPI_ISL_16861161
EPI_ISL_16861440
EPI_ISL_16892289
EPI_ISL_16892421
EPI_ISL_16892528
EPI_ISL_16892779
EPI_ISL_16894038
EPI_ISL_16896131
EPI_ISL_16914851
EPI_ISL_16914872
EPI_ISL_16914873
EPI_ISL_16917690
EPI_ISL_16917914

Usher tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_693a_cec570.json
![image](https://user-images.githubusercontent.com/8103453/219044926-9e3d2246-d321-4bf9-abdb-eaf8502b5d4b.png)

**Comment by rquiroga7** [comment]
Two days later, this is at 36 sequences on GISAID.
New seqs:
EPI_ISL_16935947
EPI_ISL_16936066
EPI_ISL_16936253
EPI_ISL_16936397
EPI_ISL_16936493
EPI_ISL_16944391
EPI_ISL_16944399
EPI_ISL_16946239
EPI_ISL_16947511

**Comment by rquiroga7** [comment]
This is now at 60 sequences, and has been detected in US, Canada and Aruba.
[gisaid_hcov-19_2023_03_01_13.txt](https://github.com/cov-lineages/pango-designation/files/10861314/gisaid_hcov-19_2023_03_01_13.txt)

While some of the sub-branches of this branch have not been detected in a while, the branch with Orf1ab:I3108T (NSP4:I345T) has been detected frequently in february.

**Comment by InfrPopGen** [comment]
It looks like this is now XBB.1.5.30 with T27614C (ORF7a:V74A) after [a3541005](https://github.com/cov-lineages/pango-designation/commit/a35410056f4b3547de066ea40500f081cb7121a7)

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage, which was designated in March. Regarding the sublineage with (XBB.1.5.30 with T27614C (ORF7a:V74A)), this appears to be growing at the same rate as XBB.1.5.30 in general, or possibly with a slight growth disadvantage. Consequently, there seems little value in designating this as a sub-lineage at the moment. This issue can therefore now be closed; however, please request re-opening or re-propose the T27614C lineage should it show strong relative growth in the future.
