### ISSUE TITLE
XBB.1.5 with S:A348T, nsp3:P1228S and nsp16:I127V [USA, 27 sequences]

### ISSUE THREAD

**Issue by rquiroga7** [cov-lineages/pango-designation#1661]
Sub-lineage of: XBB.1.5
Earliest sequence: 2022-12-14
Most recent sequence: 2023-01-27
Countries circulating: USA (west and east coast)

The proposed lineage has S:A348T, which is predicted by Bloom calculator to negatively affect RBD expression and ACE2 binding, but also to have a significant antigenic evasion effect. Perhaps XBB.1.5 increased ACE2 binding due to 486P allowed this rare mutation (only 610 sequences in GISAID), to provide increased fitness through antigenic evasion. 

The proposed lineage also has nsp3:P1228S and NSP16:I127V , both of which are predicted as highly fit mutations by Bloom fitness calculator (https://jbloomlab.github.io/SARS2-mut-fitness/nsp3.html, https://jbloomlab.github.io/SARS2-mut-fitness/nsp16.html).

Genomes:
EPI_ISL_16388964
EPI_ISL_16415168
EPI_ISL_16573959
EPI_ISL_16576376
EPI_ISL_16576378
EPI_ISL_16663643
EPI_ISL_16670899
EPI_ISL_16681069
EPI_ISL_16742795
EPI_ISL_16753598
EPI_ISL_16754444
EPI_ISL_16754446
EPI_ISL_16754448
EPI_ISL_16754449
EPI_ISL_16754453
EPI_ISL_16763413
EPI_ISL_16763446
EPI_ISL_16823811
EPI_ISL_16850956
EPI_ISL_16860629
EPI_ISL_16861110
EPI_ISL_16862412
EPI_ISL_16863110
EPI_ISL_16892748
EPI_ISL_16896246
EPI_ISL_16906528
EPI_ISL_16915111

Usher tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1afb3_fd3ea0.json?f_userOrOld=uploaded%20sample
![image](https://user-images.githubusercontent.com/8103453/219052546-b304db38-c42b-43b8-bde6-84cc05c35ce6.png)

**Comment by rquiroga7** [comment]
This now at 47 sequences, but does not seem to be growing quickly in comparison to other XBB.1.5 lineages. 
[gisaid_hcov-19_2023_03_01_13.txt](https://github.com/cov-lineages/pango-designation/files/10861470/gisaid_hcov-19_2023_03_01_13.txt)

Considering closing this.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it is showing signs of fading away, a four-fold drop in relative growth advantage over the past month (now it is <5%) in the USA and it still has a low share of XBB.1.5s there (<0.5%), this can be closed for now. Please re-propose or request re-opening should this one show a marked trend reversal.
