### ISSUE TITLE
Potential XBB.1.9.2 sublineage with N:L219F first collected in Indonesia and Malayasia (137 good seqs as of 2023-02-16; Europe, North America, Asia, Australia)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1664]
There may be a XBB.1.9.2 sublineage with N:L219F (C28928T) first collected in India and Malayasia with known collections within the next week in California, USA; Germany; the Netherlands; Scotland, UK; and India.

As of 2023-02-16, Cov-Spectrum reports 137 good-quality (144 total) XBB.1.9.2+N:219F sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3AF486P%2CN%3AL219F&nucMutations=27507C%2C16878T&nextcladePangoLineage=XBB.1.9*&&nextcladeQcOverallScoreTo=29& (basing query from XBB.1.9 since CoV-Spectrum does not yet support XBB.1.9.2 at the time of this issue submission)

This lineage is scattered across multiple countries with too few samples in any one country to get a decent growth estimate relative to its parental XBB.1.9.2. However, N:L219F appears to mark a major
branch of XBB.1.9.2 with approximately 64% (144 of 225 sequences) of XBB.1.9.2 sequences having N:L219F while 36% (81 of 225) XBB.1.9.2 have an unmutated N:L219 at the time of this issue submission.

As of 2023-02-16, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_XBB 1 9 2+N_219F](https://user-images.githubusercontent.com/88959107/219444841-7c65ce21-8b17-41b5-bbf3-99e436683d45.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/02/subtreeAuspice1_genome_CoV-Spectrum_XBB.1.9.2%2BN_219F.json?c=gt-N_219&f_pango_lineage_usher=XBB.1.9.2&label=id%3Anode_8014847

GISAID query: AA Substitutions: N_L219F, Spike_F486P; Nucl Mutations: A27507C, A16878T

First GISAID sequences: Indonesia and Malayasia 2023-01-02 

Most Recent GISAID sequence: England, UK 2023-02-10

A zip archive of plus CoV=Spectrum-derived UShER output files for these sequences is available at [usher_subtrees_CoV-Spectrum_XBB.1.9.2+N_219F.zip](https://github.com/cov-lineages/pango-designation/files/10758940/usher_subtrees_CoV-Spectrum_XBB.1.9.2%2BN_219F.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-XBB.1.9.2+N_219F.txt](https://github.com/cov-lineages/pango-designation/files/10758943/gisaid-epi-isl-XBB.1.9.2%2BN_219F.txt)

Note: This lineage may also have a significant sublineage of its own branching from S:Q613H.

Edit: Correct link for the CoV-Spectrum sequence count query.

**Comment by FedeGueli** [comment]
this has been designated EG.1 starting deeper in the tree from S:Q613H

**Comment by corneliusroemer** [comment]
Thanks @FedeGueli! Related to https://github.com/jmcbroome/auto-pango-designation/pull/193

**Comment by alurqu** [comment]
> Note: This lineage may also have a significant sublineage of its own branching from S:Q613H.

I agree that this is related to [jmcbroome#193](https://github.com/jmcbroome/auto-pango-designation/pull/193) and that the designation of EG.1 closes this issue. For the record, I'll point out that my initial proposal did include a mention of the designated S:Q613H sublineage as a note at the end of the initial proposal. I had just assessed the S:Q613H sublineage as too small for its own proposal at that time.
