### ISSUE TITLE
Possible 5' tip recombinant (BA.5.2*) in EF.1.3 (Denmark, ~240 sequences)

### ISSUE THREAD

**Issue by AngieHinrichs** [cov-lineages/pango-designation#1666]
This is definitely more of a curiosity than a concern, but just for the record, a good chunk of EF.1.3 looks like it might have recombined with BA.5.2* only in the first ~2000 bases of the genome because it simultaneously loses BA.5.3-defining C1931A and gains BA.5.2-defining C1627T:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/EF.1.3.2023-02-17.json?branchLabel=back-mutations&c=gt-nuc_1627,1931&label=id:node_6365414

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/186983/219763072-11b485f1-d682-4bad-b65b-e82a3aa0e478.png">

Sequences on that possible recombinant branch are almost exclusively from Denmark (which sequences a lot, so this branch is probably over-represented within EF.1.3), with a little cluster in the US and a few sequences in England and France.

<details>
  <summary>Click to expand EPI_ISL list</summary>

EPI_ISL_16463545
EPI_ISL_16591837
EPI_ISL_15984156
EPI_ISL_16696131
EPI_ISL_16696144
EPI_ISL_16695783
EPI_ISL_16697676
EPI_ISL_16883383
EPI_ISL_16647276
EPI_ISL_16909904
EPI_ISL_16591516
EPI_ISL_16813194
EPI_ISL_16647297
EPI_ISL_16646557
EPI_ISL_16590950
EPI_ISL_16591857
EPI_ISL_16591830
EPI_ISL_16593472
EPI_ISL_16350248
EPI_ISL_16221436
EPI_ISL_16151398
EPI_ISL_16885005
EPI_ISL_15984277
EPI_ISL_15971504
EPI_ISL_16017960
EPI_ISL_16017878
EPI_ISL_16017915
EPI_ISL_16063002
EPI_ISL_16232639
EPI_ISL_15984368
EPI_ISL_16238280
EPI_ISL_16214305
EPI_ISL_16238813
EPI_ISL_15971726
EPI_ISL_16550908
EPI_ISL_16550837
EPI_ISL_16503588
EPI_ISL_16409006
EPI_ISL_16408969
EPI_ISL_16593332
EPI_ISL_16307003
EPI_ISL_16217209
EPI_ISL_16349561
EPI_ISL_16884941
EPI_ISL_16813505
EPI_ISL_16737974
EPI_ISL_16696223
EPI_ISL_16909946
EPI_ISL_16909921
EPI_ISL_16882148
EPI_ISL_16592133
EPI_ISL_16591841
EPI_ISL_16591832
EPI_ISL_16592129
EPI_ISL_16580182
EPI_ISL_16882109
EPI_ISL_16885199
EPI_ISL_16660586
EPI_ISL_16916999
EPI_ISL_16857930
EPI_ISL_16751561
EPI_ISL_16457453
EPI_ISL_16503442
EPI_ISL_16547818
EPI_ISL_16646967
EPI_ISL_16408773
EPI_ISL_16697553
EPI_ISL_16646855
EPI_ISL_16257157
EPI_ISL_16257225
EPI_ISL_16257577
EPI_ISL_16350498
EPI_ISL_16350065
EPI_ISL_16410395
EPI_ISL_16126791
EPI_ISL_16409776
EPI_ISL_16603243
EPI_ISL_16601772
EPI_ISL_16602486
EPI_ISL_16644128
EPI_ISL_16704821
EPI_ISL_16861904
EPI_ISL_16034712
EPI_ISL_16921083
EPI_ISL_16814376
EPI_ISL_16885916
EPI_ISL_16696166
EPI_ISL_16637997
EPI_ISL_16638131
EPI_ISL_16751904
EPI_ISL_16503154
EPI_ISL_16457433
EPI_ISL_16410078
EPI_ISL_16306197
EPI_ISL_16813695
EPI_ISL_16813726
EPI_ISL_16548137
EPI_ISL_16515450
EPI_ISL_16257569
EPI_ISL_16330743
EPI_ISL_16515345
EPI_ISL_16256846
EPI_ISL_16515410
EPI_ISL_16503585
EPI_ISL_16749793
EPI_ISL_16647289
EPI_ISL_16408502
EPI_ISL_16485487
EPI_ISL_16646964
EPI_ISL_16375703
EPI_ISL_16332190
EPI_ISL_16547758
EPI_ISL_16912588
EPI_ISL_16912406
EPI_ISL_16912434
EPI_ISL_16912711
EPI_ISL_16912371
EPI_ISL_16912515
EPI_ISL_16866432
EPI_ISL_16866509
EPI_ISL_16856757
EPI_ISL_16856618
EPI_ISL_16856774
EPI_ISL_16857008
EPI_ISL_16856995
EPI_ISL_16856654
EPI_ISL_16856737
EPI_ISL_16856743
EPI_ISL_16912716
EPI_ISL_16547813
EPI_ISL_16856764
EPI_ISL_16856660
EPI_ISL_16856560
EPI_ISL_16857081
EPI_ISL_16857016
EPI_ISL_16856803
EPI_ISL_16856679
EPI_ISL_16110887
EPI_ISL_16127423
EPI_ISL_16170144
EPI_ISL_16332024
EPI_ISL_16349741
EPI_ISL_15918915
EPI_ISL_16815509
EPI_ISL_16727203
EPI_ISL_16094430
EPI_ISL_16515421
EPI_ISL_16485466
EPI_ISL_16469901
EPI_ISL_16409104
EPI_ISL_16306217
EPI_ISL_16094330
EPI_ISL_16094284
EPI_ISL_16063650
EPI_ISL_16515290
EPI_ISL_16062809
EPI_ISL_15918735
EPI_ISL_15939473
EPI_ISL_15959963
EPI_ISL_15959337
EPI_ISL_15960176
EPI_ISL_16274722
EPI_ISL_15959460
EPI_ISL_15972206
EPI_ISL_15983812
EPI_ISL_15971700
EPI_ISL_15999621
EPI_ISL_15999701
EPI_ISL_16017840
EPI_ISL_16017715
EPI_ISL_16028786
EPI_ISL_16062471
EPI_ISL_15960322
EPI_ISL_16469751
EPI_ISL_16469502
EPI_ISL_16214834
EPI_ISL_16110771
EPI_ISL_16485258
EPI_ISL_16410393
EPI_ISL_16274695
EPI_ISL_16595889
EPI_ISL_16547858
EPI_ISL_16469633
EPI_ISL_16856956
EPI_ISL_16857087
EPI_ISL_16409823
EPI_ISL_16430592
EPI_ISL_16357082
EPI_ISL_16256554
EPI_ISL_16375966
EPI_ISL_16375585
EPI_ISL_16029152
EPI_ISL_16094466
EPI_ISL_16127464
EPI_ISL_16127252
EPI_ISL_16170350
EPI_ISL_16356671
EPI_ISL_16457566
EPI_ISL_15959272
EPI_ISL_16811223
EPI_ISL_16503138
EPI_ISL_16356831
EPI_ISL_16062401
EPI_ISL_16238608
EPI_ISL_16256858
EPI_ISL_16375521
EPI_ISL_16409946
EPI_ISL_16430481
EPI_ISL_16646670
EPI_ISL_16350289
EPI_ISL_16349484
EPI_ISL_16256814
EPI_ISL_16257090
EPI_ISL_16256792
EPI_ISL_16257161
EPI_ISL_16257084
EPI_ISL_16201747
EPI_ISL_16215000
EPI_ISL_16111607
EPI_ISL_16110109
EPI_ISL_16110430
EPI_ISL_16141401
EPI_ISL_16110507
EPI_ISL_16430866
EPI_ISL_16349910
EPI_ISL_16349488
EPI_ISL_16409243
EPI_ISL_16408497
EPI_ISL_16430729
EPI_ISL_16274634
EPI_ISL_16410221
EPI_ISL_16581777
EPI_ISL_16306231
EPI_ISL_16306070
EPI_ISL_16409501
EPI_ISL_16306131
EPI_ISL_15909536
EPI_ISL_16133102
EPI_ISL_16587614
EPI_ISL_16654098
EPI_ISL_16855715
EPI_ISL_16879529

</details>

**Comment by AnonymousUserUse** [comment]
For those who is about to check what EF.1.3 stands for:
EF.1.3 = BQ.1.1.13.1.3 = BE.1.1.1.1.1.13.1.3 = BA.5.3.1.1.1.1.1.1.13.1.3 = B.1.1.529.5.3.1.1.1.1.1.1.13.1.3

**Comment by FedeGueli** [comment]
C1627T seems always good to gain. Also XBK was faster than CJ differing for just G261A vs C1627T .
And being present in a significant branch without its ba.5.2 sister mutation a28330g some of its sublineage went far as BA.5.11 or BA.5.10 . while C1931A was never gained (or better saying never spread) without the entire bq.1 box of mutations. this suggests me that it could be a good exchange for BQ.1

**Comment by corneliusroemer** [comment]
Thanks @AngieHinrichs - I just noticed this independently, then saw your issue.

Should we designate this as a recombinant? I agree that it's more likely recombinant than not.

**Comment by InfrPopGen** [comment]
This "curiosity" was still showing some growth advantage, and still around, so I have added it as recombinant lineage XBZ with 0 newly designated sequences, and 238 updated designations. Defining mutations A1931C (ORF1a:K556Q), nt:C1627T (following C22858T).
