### ISSUE TITLE
Potential BN.1.2/BQ.1.25 recombinant, similar to XBP but with Spike: R346T, S371F, S373P, S375F, T376A, D405N, R408S, K417N, N440K, K444T, L452R, N460K, S477N, T478K, E484A, F486V (50 sequences in Canada, USA, England...)

### ISSUE THREAD

**Issue by ilevade** [cov-lineages/pango-designation#1667]
New recombinant Omicron/BA.2.75/22D,Omicron/BA.5/22B (BN.1.2*,BQ.1*) identified BA.5.2.1 by Pangolin and BQ.1.25 by Nextclade. 

Spike: T19I, K147E, W152R, F157L, V213G, G339D, R346T, S371F, S373P, S375F, T376A, D405N, R408S, K417N, N440K, K444T, L452R, N460K, S477N, T478K, E484A, F486V, Q498R, N501Y, Y505H, D614G, H655Y, N679K, P681H, N764K, D796Y, Q954H, N969K

Earliest date: 2022-11-20

Countries: Austria, Canada, Czech Republic, England, Israel, USA

Potential breakpoint:  22034:22189 in RBD

Mutation profile:
![image](https://user-images.githubusercontent.com/31353633/219790295-09329f77-2486-4f69-a7c3-d26a56c5ca94.png)

nuc	unique	C241T, T670G, C2790T, C3037T, C3796T, C3927T, G4184A, C4321T, C4586T, C5183T, C9344T, A9424G, C9534T, C9866T, C10029T, C10198T, G10447A, C10449A, G12160A, A12444G, C12880T, C14408T, G15451A, C15714T, C17410T, A18163G, C19955T, A20055G, C21618T, A22001G, T22016C, C22033A, T22200G, G22578A, G22599C, C22674T, T22679C, C22686T, A22688G, G22775A, A22786C, G22813T, T22882G, A22893C, T22917G, T22942A, G22992A, C22995A, A23013C, T23018G, A23055G, A23063T, T23075C, A23403G, C23525T, T23599G, C23604A, C23854A, G23948T, A24424T, T24469A, C25000T, C25584T, C26060T, C26270T, G26529A, C26577G, G26709A, C27807T, C27889T, A28271T, C28311T, C28312T, G28681T, G28881A, G28882A, G28883C, A29510C
ORF1ab	unique	S135R, T842I, S1221L, G1307S, P1640S, L3027F, T3090I, L3201F, T3255I, P3395H, N4060S, P4715L, G5063S, R5716C, I5967V, T6564I
S	unique	T19I, K147E, W152R, F157L, V213G, G339D, R346T, S371F, S373P, S375F, T376A, D405N, R408S, K417N, N440K, K444T, L452R, N460K, S477N, T478K, E484A, F486V, Q498R, N501Y, Y505H, D614G, H655Y, N679K, P681H, N764K, D796Y, Q954H, N969K
ORF3a	unique	T223I
E	unique	T9I
M	unique	D3N, Q19E, A63T
N	unique	P13L, E136D, R203K, G204R, S413R

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_10daf_fd6db0.json?c=country&label=id:node_7057413
![image](https://user-images.githubusercontent.com/31353633/219784464-83003d4f-8777-4fc1-a02f-071efce72feb.png)

Genomes:

Slovenia/23-003655-MB/2023\|EPI_ISL_16848357\|2023-01-24
England/LSPA-3269939B/2023\|OX418381.1\|2023-01-11
England/QEUH-32645F21/2022\|OX403031.1\|2022-12-20
Austria/LB-R00116-S266/2022\|EPI_ISL_16192386\|2022-12-14
England/PHEC-YY84OGE/2023\|2023-01-07
England/PHEC-YY8HM56/2023\|2023-01-11
England/PHEC-YY8HIUR/2023\|2023-01-11
England/LSPA-3269A2AC/2023\|OX416957.1\|2023-01-10
England/LSPA-326959CA/2023\|2023-01-10
England/LSPA-32699EA9/2023\|OX417082.1\|2023-01-10
England/LSPA-32699FC4/2023\|OX418423.1\|2023-01-10
England/LSPA-32699CCD/2023\|OX417062.1\|2023-01-10
England/BRBR-326B5E4D/2023\|2023-01-30
England/QEUH-326A7EC6/2023\|OX420769.1\|2023-01-17
USA/CA-HLX-STM-D88AKQBNP/2022\|EPI_ISL_16602765\|2022-12-19
USA/CA-HLX-STM-WS389Z448/2023\|EPI_ISL_16888466\|2023-01-12
Israel/ICH-741192391/2022\|EPI_ISL_15927302\|2022-11-20
USA/CA-CDPH-FS47307798/2023\|EPI_ISL_16735084\|2023-01-03
USA/CA-CDC-QDX44940066/2022\|OQ205135.1\|2022-12-24
England/LSPA-3267F54A/2022\|OX412460.1\|2022-12-20
USA/CA-CDC-STM-FXV5UD8TC/2023\|OQ284979.1\|2023-01-06
USA/CA-CDC-LC0971431/2022\|OQ165752.1\|2022-12-16
USA/CA-CDC-LC0985776/2023\|OQ258527.1\|2023-01-04
Israel/CVL-8013810/2023\|EPI_ISL_16738930\|2023-01-10
England/QEUH-326B5FD1/2023\|2023-01-29
England/PHEC-YY8ATRX/2023\|2023-01-04
USA/CA-LACPHL-AF18831/2023\|EPI_ISL_16921096\|2023-01-22
USA/CA-HLX-STM-HUQ8BB3RA/2022\|EPI_ISL_16818068\|2022-12-21
USA/CA-CDC-LC0981944/2022\|OQ263495.1\|2022-12-29
USA/CA-CDC-QDX45038137/2022\|OQ264851.1\|2022-12-23
USA/CA-CDC-STM-SF2FXJVT2/2022\|OQ219932.1\|2022-12-23
USA/CA-HLX-STM-BV73SAGDD/2022\|EPI_ISL_16703822\|2022-12-24
CzechRepublic/77SVUPHA_6857730198/2022\|EPI_ISL_16180548\|2022-11-23
USA/CA-CDC-LC0981935/2022\|OQ263496.1\|2022-12-29
England/PHEC-YY8WB1K/2022\|2022-12-21
England/QEUH-326A0267/2023\|OX417995.1\|2023-01-11
England/QEUH-326557F9/2022\|OX404125.1\|2022-12-16
England/PHEC-YY8H143/2023\|2023-01-05
England/PHEC-YY8HUIN/2023\|2023-01-05
England/DHSC-CY8QMQK/2023\|2023-01-20
England/PHEC-YY8HAF6/2023\|2023-01-12
USA/CA-HLX-STM-A8JYWVS4D/2022\|EPI_ISL_16602385\|2022-12-21
USA/CA-HLX-STM-73MEW6WSU/2022\|EPI_ISL_16602238\|2022-12-21
Canada/Qc-L00568616001/2022
Canada/QC-L00568616001/2022\|EPI_ISL_16460518\|2022-12-19
Canada/QC-L00577144001/2023\|EPI_ISL_16690171\|2023-01-15
Canada/QC-L00574704001/2023\|EPI_ISL_16619552\|2023-01-10
Canada/QC-L00575410001/2023\|EPI_ISL_16619263\|2023-01-10
Canada/QC-L00574703001/2023\|EPI_ISL_16619390\|2023-01-09
Canada/QC-L00571972001/2023\|EPI_ISL_16509912\|2023-01-02

**Comment by Mydtlwn** [comment]
The strain seems interesting.

**Comment by c19850727** [comment]
It looks like a duplicate to #1567 and #1637 ?

![image](https://user-images.githubusercontent.com/86835836/219829904-92e41875-aa08-45b0-99bc-220575d1039a.png)

**Comment by corneliusroemer** [comment]
Yep, duplicate
