### ISSUE TITLE
BF.31.1/BQ.1.10* Recombinant (>55 seq, Apr 13)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1668]
### **Description**
**Earliest sequence:** 2022-12-28, Chile, Nuble — EPI_ISL_16743083
**Most recent sequence:** 2023-2-2, Chile, Nuble — EPI_ISL_16942046, EPI_ISL_16942049, EPI_ISL_16942050
**Countries circulating:** Chile (all 21)
**Number of Sequences:** 12
**GISAID Query:** NSP8_A74T, Spike_S247N, Spike_Y248del, Spike_N460K, Spike_K444T
**GISAID Nucleotide Query:** G12311A, T22348A
**CovSpectrum Query:** [4-of: A11126G, G12311A, T22348A, C27600T, T28282C]
**Substitutions on top of BF.31.1/BQ.1.10:**
**ORF1a:** M3621V, A4016T
**Nucleotide:** A11126G, G12311A, T22348A, T28282C
**Breakpoint:** Between 22304 and 22893 (S:248 and S:444)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BF.31.1%2CBQ.1_21seq_subtreeAuspice1_genome_43e16_1610.json

**Evidence**
Pretty clear breakpoint somewhere in 22304-22893. In addition to ORF1a:M3621V and ORF1a:A4016T, 14/21 sequences have S:A262S. Peculiarly, two of the three nucleotides at S:262 are mutated, including the synonymous mutation T22348A, which has only appeared in 41 other sequences in the last six months.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/33738461/219818818-6bc1a2d2-55da-4d17-925a-75d7f3af7686.png">

The presence of C26700T, along with the relatively high prevalence of BQ.1.10 in Chile is what makes me think the 3' end of this recombinant comes from BQ.1.10.

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16654149, EPI_ISL_16660713, EPI_ISL_16740976, EPI_ISL_16741051, EPI_ISL_16741053, EPI_ISL_16743083, EPI_ISL_16761006, EPI_ISL_16833908, EPI_ISL_16833909, EPI_ISL_16833913-16833914, EPI_ISL_16847302, EPI_ISL_16847304-16847306, EPI_ISL_16935366, EPI_ISL_16935367, EPI_ISL_16935369, EPI_ISL_16942046, EPI_ISL_16942049, EPI_ISL_16942050
</details>

**Comment by ryhisner** [comment]
30 sequences now, but still confined to Chile. 
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/33738461/222851848-e5ed6734-0bb3-4d95-a24e-73ce71a88e1a.png">

**Comment by ryhisner** [comment]
This lineage has continued to show up in Chile with 12 sequences collected in March so far, but today the first sequence from outside of South America showed up in South Korea. EPI_ISL_17373830

**Comment by ryhisner** [comment]
First sequence of this recombinant from Europe was uploaded today from France. EPI_ISL_17383910

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XCB with 46 newly designated sequences, and 0 updated. Defining mutations A11126G (ORF1a:M3621V), G12311A (ORF1a:A4016T), C14724T, G18651A, T22348A, C27600T, T28282C (following T22942A (S:N460K)).
