### ISSUE TITLE
CH.1.1 with S:N679R [30 sequences, mostly Denmark]

### ISSUE THREAD

**Issue by Outpfmance** [cov-lineages/pango-designation#1670]
Here is a pedigree of the new CH.1.1
It is CH.1.1 with S:N679R
BorisUitham is tracking this variant for a number of reasons
And its relative growth advantage is huge (2023/02/10)
https://cov-spectrum.org/collections/146

It has 15 sequences now, most of them in Denmark
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A679r&nextcladePangoLineage=ch.1.1

I think we should look at this variant

**Comment by BorisUitham** [comment]
![ch1](https://user-images.githubusercontent.com/119106095/219902847-ce1c7993-e60c-4476-b49f-c31203bc5cc6.png)
This is the biggest subtree in denmark, 11 seqs. This part has orf1ab:A2850V and orf6:K23I. rest of the subtrees are a bit on their own.

![ch2](https://user-images.githubusercontent.com/119106095/219902910-0e5633cc-75a1-4c15-81dd-c8ff86e42e40.png)
Here you can see all the subtrees in context of downsampled global tree, leftmost branch is CH.1.1

you can use "spike_n679r, spike_f486s, spike_l452r" on GISAID to find them all or "spike_n679r, spike_f486s, spike_l452r, NS6_k23I" to find the danish branch of 11

**Comment by Outpfmance** [comment]
Thanks @BorisUitham!  Good job ! 
Gisaid query:Spike_N679R, Spike_F486S, Spike_L452R

**Comment by Outpfmance** [comment]
Thanks @BorisUitham! Good job!
Gisaid query:Spike_N679R, Spike_F486S, Spike_L452R

**Comment by Outpfmance** [comment]
Thank you @BorisUitham! Good job!

Gisaid query:Spike_N679R, Spike_F486S, Spike_L452R

**Comment by Outpfmance** [comment]
17 sequences now

**Comment by Outpfmance** [comment]
19 sequences now,mostly Denmark and Austra

**Comment by Outpfmance** [comment]
The other three sequences have been uploaded.

**Comment by Outpfmance** [comment]
24 sequences now.

**Comment by Outpfmance** [comment]
30 sequences now. Its growth rate is starting to increase.
