### ISSUE TITLE
XBC.1 sublineage with S:V171I (25 seq, Japan)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1671]
Proposal for a sublineage of XBC.1
Earliest sequence: 21.12.2022 (Japan)
Countries detected: Japan

Gisaid query: T17363C, G22073A

Defining mutations:
ORF1ab:I5700T = T17363C
S:V171I = G22073A

![grafik](https://user-images.githubusercontent.com/102166254/220046696-56b66fa6-a523-4ab0-95ea-78c1f6a2403f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c3aa_3270f0.json?c=gt-S_171

EPI_ISL_16973147
EPI_ISL_16972238
EPI_ISL_16825577
EPI_ISL_16736861
EPI_ISL_16545055
EPI_ISL_16950714
EPI_ISL_16948892
EPI_ISL_16971855
EPI_ISL_16559611
EPI_ISL_16637440
EPI_ISL_16637573
EPI_ISL_16633246
EPI_ISL_16645042
EPI_ISL_16633391
EPI_ISL_16971854
EPI_ISL_16645050
EPI_ISL_16950451
EPI_ISL_16482444
EPI_ISL_16950101
EPI_ISL_16825782
EPI_ISL_16950726
EPI_ISL_16950694
EPI_ISL_16950725
EPI_ISL_16809578
EPI_ISL_16455191

**Comment by corneliusroemer** [comment]
Designated slightly broader as XBC.1.5
