### ISSUE TITLE
BF.7.14 sublineage with S:S1021F in Sichuan (33% of the BF.7.14 sequences in Sichuan from 2023-1-9)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1672]
Sub-lineage of :BF.7.14
Earliest sequence: 2022.12.21(Singapore) EPI_ISL_16294572
Most Recent sequence:  2023.2.8 (Sichuan) EPI_ISL_16970282
GISAID query: G1085T,G25290T,T11587C,C24624T
No. of seqs: 13 (12 China, 1 Singapore(local case))

Mutations of top of BF.7.14: T11587C, C24624T(S:S1021F)

Genomes:
EPI_ISL_16294572, EPI_ISL_16596491, EPI_ISL_16636036,
EPI_ISL_16737884, EPI_ISL_16737886, EPI_ISL_16899479,
EPI_ISL_16899485, EPI_ISL_16970235, EPI_ISL_16970238-16970239,
EPI_ISL_16970282-16970284

This branch contains 11 out of 34 (33%) Sichuan BF.7.14 sequences from 2023-1-9. 
Note that Sichuan province has a larger population than UK. So each sequence may represent a large share of population. 

<img width="1249" alt="Screen Shot 2023-02-20 at 17 18 38" src="https://user-images.githubusercontent.com/10445944/220064017-179aca18-3922-493e-8860-3a196b56cdf0.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_32540_31fd20.json?c=gt-S_1021&label=id:node_7031086

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.7.14.7 with 6 newly designated sequences, and 1 updated. Defining mutation C24624T (S:S1021F) (following T11587C).
