### ISSUE TITLE
BQ.1.1.43 (S:Q613H) Sublineage with S:S247N, S:Y248S (125 seq; Mar 24)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1673]
### **Description**
**Sub-lineage of:** BQ.1.1.43
**Earliest sequence:** 2022-12-28, Spain — EPI_ISL_16955486
**Most recent sequence:** 2023-2-10, Ireland — EPI_ISL_16957159
**Countries circulating:** Portugal (19), France (7), Luxembourg (2), Germany (1), Ireland (1), Italy (1), Spain (1), Sweden (1)
**Number of Sequences:** 12
**GISAID Query:** Spike_S247N, Spike_Y248S, Spike_Q613H, -Spike_Q493R
**CovSpectrum Query:** Nextcladepangolineage: BQ.1.1.43* & S:S247N & S:Y248S
**Substitutions on top of BA.:**
**Spike:** S247N, Y248S
**Nucleotide:** G22302A, A22305C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1.1.43%2BS247N%2BY248S_subtreeAuspice1_genome_fa0b_355a50.json 

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/33738461/220094795-d1a8e23a-f482-4b9f-89e9-598e9952cb33.png">

**Evidence**
This seems further confirmation of the increasing importance of the S:247-251 region in the past couple months. S:252-253 should probably be included in this region of importance given their presence in the increasingly dominant XBB variants. However, the presence of ∆69-70 seems to make mutations at S:252-253 almost impossible. This was the insight of @Thomas_Peacock who helpfully pointed out that S:69-70 and S:252-253 are located pretty much on top of one another. For more discussion of the recent prominence of 247-251 mutations, see issue #1648.  
 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16617942, EPI_ISL_16618029, EPI_ISL_16618169, EPI_ISL_16759090, EPI_ISL_16832239, EPI_ISL_16832247, EPI_ISL_16866671, EPI_ISL_16866673, EPI_ISL_16866688, EPI_ISL_16866775, EPI_ISL_16886289, EPI_ISL_16913739, EPI_ISL_16925564, EPI_ISL_16925688, EPI_ISL_16954595, EPI_ISL_16955486, EPI_ISL_16957159, EPI_ISL_16975050, EPI_ISL_16975062, EPI_ISL_16975090, EPI_ISL_16975095, EPI_ISL_16975145, EPI_ISL_16975150, EPI_ISL_16975157, EPI_ISL_16975165, EPI_ISL_16975172, EPI_ISL_16975173, EPI_ISL_16975174, EPI_ISL_16975176, EPI_ISL_16975177, EPI_ISL_16975181, EPI_ISL_16975183, EPI_ISL_16975201
</details>

**Comment by FedeGueli** [comment]
Btw the other bq.1.1 with the same mutation is one of the fastest lineage at this point. I suggest to designate this one to keep track of it.

**Comment by ryhisner** [comment]
First sequence from England today, which has the unusual mutation N:M210K. EPI_ISL_16996344

**Comment by InfrPopGen** [comment]
I think this was prospectively designated as EZ.1, and also proposed in #1741 (as noted above), but this appears to be the original proposal, and so this can be closed with the milestone and designation linked to this issue.
