### ISSUE TITLE
Potential BA.2.75/BA.5 recombinant (51 seq., 7 countries)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1674]
Proposal for a sublineage of BA.2.75/BA.5
Earliest sequence: 22.12.2022 (Singapore)
Countries detected: Singapore, USA, UK, Austria

This is a potential recombinant between sublineages of BA.2.75/BA.5 which was detected in four countries so far (Singapore, USA, UK, Austria). Nextclade identifies the sequences as XBP while usher clusters them within BA.2.75.

Defining Mutations:
nuc	unique	C5748A, G21893A, C22747T, C23595T, T25975C
nuc	homoplasies	C11124T, T13324C
ORF1ab	unique	T1828N
ORF1ab	homoplasies	A3620V
S	unique	D111N, T678I
ORF3a	unique	S195P

Potential Gisaid query: C5748A, G21893A, C22747T, C23595T, T25975C

![grafik](https://user-images.githubusercontent.com/102166254/220112958-721f0abf-c659-4a4d-94f0-8ec98f6c48dd.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_30d99_368450.json?c=gt-S_111
![grafik](https://user-images.githubusercontent.com/102166254/220112351-e7279ffe-29b2-4fa5-bd8e-8e9f286845ba.png)

EPI_ISL_16352127, EPI_ISL_16415291, EPI_ISL_16676426,
EPI_ISL_16907101, EPI_ISL_16946169, EPI_ISL_16952041,
EPI_ISL_16952045, EPI_ISL_16969074, EPI_ISL_16976933,
EPI_ISL_16977008, EPI_ISL_16978835

**Comment by agamedilab** [comment]
29 on usher as of 09.03.23.

![grafik](https://user-images.githubusercontent.com/102166254/224021985-48e436f0-ef3a-4465-bab0-3311ae350b4f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8a6c_9ce000.json?c=userOrOld&label=id:node_7974580

**Comment by InfrPopGen** [comment]
Hi @agamedilab I feel this can be closed because it reminds me very much of #1752 which has already been designated.

**Comment by agamedilab** [comment]
@InfrPopGen many thanks for pointing this out!
