### ISSUE TITLE
Possible CH.1.1.1 sublineage with N: A50S (G28421T) mutation circulating in USA, Peru, Chile, UK (18 seqs) 

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#1675]
**A) Description**
New possible CH.1.1.1 sub-lineage with N: A50S (G28421T) mutation proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**B) Earliest sequence:** 
Peru/PUN-INS-37040/2022 (28/11/2022)

**C) Most recent sequence:** 
Peru/LIM-INS-39580/2023 (16/01/2023)

**D) Countries circulating:**
USA (1), Peru (15), Chile (1), UK (1)

**E) Genomes**
[genomes.csv](https://github.com/cov-lineages/pango-designation/files/10785288/genomes.csv)

**F) Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d19e_3804a0.json?c=country&label=id:node_8324707

![image](https://user-images.githubusercontent.com/89021119/220133298-0fb053a4-1b0a-4b66-856e-8830f16edeb6.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=N%3AA50S&nextcladePangoLineage=CH.1.1.1&

![image](https://user-images.githubusercontent.com/89021119/220133421-6adb2bdb-d43f-4e78-83c0-2e2543c73e3e.png)

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As this has not been detected for a while, hasn't shown marked relative growth over the past three months, and did not spread significantly outside of Peru, this can be closed for now. Please request re-opening should this clade show a future growth spurt and advantages.
