### ISSUE TITLE
BM.1.1.4 (S:K356T, S:T572I) Sublineage with S:L452R, ORF1b:V2406I (12 seq, Feb 21)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1676]
### **Description**
**Sub-lineage of:** BM.1.1.4
**Earliest sequence:** 2022-12-12, Bhutan — EPI_ISL_16984438
**Most recent sequence:** 2023-2-12, Singapore — EPI_ISL_16975343
**Countries circulating:** Bhutan (10), Singapore (2—but both with travel history from Malaysia)
**Number of Sequences:** 12
**GISAID Query:** G20683A, C14805T, G29527A, C912A, A2151C, -C3037T
**CovSpectrum Query:** Nextcladepangolineage:BM.1.1.4* & !C3037T & [5-of: C1102T, C14805T, G20683A, C7945T, A9343G, T22917G, C29200T]
**Substitutions on top of BM.1.1.4:**
**Spike:** L452R
**ORF1a:** V2406I
**Nucleotide:** C1102T, C14805T, G20683A, C7945T, A9343G, T22917G, C29200T
**Nucleotide Reversion (likely Usher tree artifact):** T3037C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BM.1.1.4%2BL452R_subtreeAuspice1_genome_127cb_49add0.json

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/33738461/220328932-353cdaf8-c75f-439e-9f63-d9ba379a9c22.png">
  
**Evidence**
This lineage appears to be dominant in Bhutan and is likely widely circulating in Malaysia and perhaps elsewhere in SE Asia. Eleven of the 12 sequences in this lineage have been uploaded in the past two days (February 20-21). Ten were uploaded today from Bhutan. One additional sequence from Bhutan uploaded today has ORF1b:V2406I but not S:L452R. Of the 11 sequences uploaded today from Bhutan collected January 1, 2023 or later, 10 are from this lineage. The most recently collected sequences here are from Singapore (collection dates Feb 5 and Feb 12), and both have travel history with Malaysia.

Six of the 10 sequences from Bhutan are listed as having had travel history in prior months. However, the earliest sequence, from December 12, had no travel history in prior months. I'm guessing the high percentage of subjects with travel history is due to such people being more likely to be sequenced. All indications are that this is in wide circulation locally.

The large number of additional mutations in this branch likely indicate this has been spreading undetected for some time. Many of the mutations are quite interesting, including S:T22N (2 seq), S:T76I (1), S:G181A (1), S:Y266C (1), S:A348T (1),  S:S704L (2), ORF3a:L53F (1), ORF3a:T64I (1), ORF1a:P4120S/NSP8P178S (9), N:P6L (1), N:G34R (1), and N:P151S (1).

I think there is likely a mistake in the BM.1.1.4 Usher tree. As pictured below, this branch and one other nearby branch of BM.1.1.4—which is probably worthy of designation in its own right—lack the nucleotide mutation C3037T. Since reversion is unlikely, I'm guessing these two branches belong together, though perhaps I'm overlooking something.

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/33738461/220329448-06c8230d-4800-492f-8081-3e2c33f43678.png">

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16899330, EPI_ISL_16975343, EPI_ISL_16984438, EPI_ISL_16984442, EPI_ISL_16984443, EPI_ISL_16984445, EPI_ISL_16984446, EPI_ISL_16984447, EPI_ISL_16984448, EPI_ISL_16984449, EPI_ISL_16984450, EPI_ISL_16984451
</details>

**Comment by corneliusroemer** [comment]
3037T dates back to the very early pandemic - it's in B.1, almost always present:
<img width="1982" alt="image" src="https://user-images.githubusercontent.com/25161793/220403355-5b43c6cd-fca3-4ba4-80b7-a6a16551ea73.png">

**Comment by c19850727** [comment]
14 seqs now. 2 newly uploaded from Singapore, both with recent travel history from Malaysia.

**Comment by AnonymousUserUse** [comment]
Milestone EP.1 missing

**Comment by FedeGueli** [comment]
18 sequences as today 2 new ones from Bhutan and two more from Singapore travel related with Thailand and Malaysia.
Being this likely spreading in an undersampled area and carrying a combo of mutations in key residues better flagging it. @thomasppeacock
