### ISSUE TITLE
Big undesignated branch of BA.5.1 with Orf9b:P10F still circulating in Japan ( 1481 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1677]
I put here cause i think it is worth not losing memory of it, unsure if it deserves an ex post designation, ex post because its circulation was at very low levels in 2023.
Still i i think it is interesting due the fact it shares Orf9b:S10F with BE.1.1.1,BQ.1 and BQ.1.1* and this lineage has a slight but clear advantage versus parental BA.5.1 and this could be take qith a good reliability cause this sublineage added in its main branches just Synonymous muts.

Tree:
<img width="1178" alt="Schermata 2023-02-21 alle 12 22 23" src="https://user-images.githubusercontent.com/87669813/220331888-77757488-4201-45c0-b181-6cd35d254377.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_96db_48ef30.json?c=country&label=id:node_6841454

Defining mutations:
BA.5.1> C29541T > C21057T > Orf9b:P10F (C28312T)

Gisaid query: C29541T , C21057T ,C28312T

Sequences : 1454
19 old sequences as reference:
EPI_ISL_13229406, EPI_ISL_13229560, EPI_ISL_13402291,
EPI_ISL_13470918, EPI_ISL_13493108, EPI_ISL_13499076,
EPI_ISL_13519698, EPI_ISL_13532497, EPI_ISL_13573843,
EPI_ISL_13618015, EPI_ISL_13731567, EPI_ISL_13762826,
EPI_ISL_13769930, EPI_ISL_13849124, EPI_ISL_13892456,
EPI_ISL_13901978, EPI_ISL_13959044, EPI_ISL_14093014,
EPI_ISL_14541452

Growth advantage vs BA.5.1:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BA.5.1*&aaMutations1=Orf9b%3A10F&nextcladePangoLineage1=BA.5.1*&analysisMode=CompareToBaseline&
<img width="933" alt="Schermata 2023-02-21 alle 12 29 27" src="https://user-images.githubusercontent.com/87669813/220333327-09d4240b-589a-4677-9f51-3f66c1260066.png">

**Comment by AnonymousUserUse** [comment]
I do not think that ORF9b:P10F has real growth advantage. The global growth advantage of BA.5.1 + ORF9b:P10F compared with BA.5.1 may be caused by the different epidemiological situation of countries where BA.5.1 and BA.5.1 + ORF9b:P10F are circulating. If we restrict the growth advantage within Japan, no growth advantage of BA.5.1 + ORF9b:P10F compared with BA.5.1 is observed.
https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?nextcladePangoLineage=BA.5.1*&aaMutations1=Orf9b%3A10F&nextcladePangoLineage1=BA.5.1*&analysisMode=CompareToBaseline&
![image](https://user-images.githubusercontent.com/113214374/220366152-e81c3575-a4a1-43ca-a3c5-36bafad07bad.png)

Personally speaking, I would not designate it for lack of epidemiological event.

**Comment by FedeGueli** [comment]
@AnonymousUserUse consider that looking at your graph you should take in account that likely one country only analysis is more sensitive to other ba.5.1 sublineages introduced there, with maybe more escape fitness.
Anyway i just notices XBL too has Orf9b:P10F.

**Comment by AnonymousUserUse** [comment]
@FedeGueli 

I have also checked the growth advantage excluding its designated sublineages of BA.5.1, and a similar result is obtained.
If there are any undesignated sublineages of BA.5.1 that has growth advantage, these should be designated first.

A mutation that is (highly) homoplastic does not necessarily mean that this mutation has any concerning feature at all.

**Comment by FedeGueli** [comment]
> @FedeGueli
> 
> I have also checked the growth advantage excluding its designated sublineages of BA.5.1, and a similar result is obtained. If there are any undesignated sublineages of BA.5.1 that has growth advantage, these should be designated first.
> 
> A mutation that is (highly) homoplastic does not necessarily mean that this mutation has any concerning feature at all. But I also wonder if there is research about the correlation between homoplasy and concerning feature of mutations.

BA.5.1 "expansion" in Japan was driven by four lineages all defined by Orf9b mutations : 
the one proposed here with Orf9b:P10F, 
BA.5.1.5 with Orf9b:V76A 
another one undesignated with Orf9b:T83I
another one undesignated with Orf9b:I45T

the one proposed here has 13% disadvantage versus BA.5.1.5
11% disadvantage versus Orf9b:T83I
9% disadvantage versus Orf9b:I45T
Still it had a significant advantage versus BA.5.1 baseline without this Orf9b mutated sublineages also in Japan.
All together they represented 45% of BA.5.1 in Japan in the last 6m  with an overall prevalence around 2% .
This is very significant and although the lineage proposed here was the slowest of them , it is meaningful and worth of further studies. If you want to propose the  other two undesignated lineages it would be great. BA.5.1 is one of the most undescribed lineages.

PS i disagree Orf9b:P10F is homoplasic, it wasnt: it popped up here in BE.1.1.1/BQ and XBL as real lineages and few more.

**Comment by AnonymousUserUse** [comment]
@FedeGueli 

Ok, but I think a lineage should be designated if it has substantial growth advantage compared with co-circulating lineages, and not only compared with its parental lineage without any further mutations.
> (iii) The clade may be observed to be growing rapidly and/or strongly increasing in frequency compared to other co-circulating lineages.

Source: https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/

> PS i disagree Orf9b:P10F is homoplasic, it wasnt: it popped up here in BE.1.1.1/BQ and XBL as real lineages and few more.

A mutation popping up several times can already be described as homoplastic. Officially, ORF9b:P10F is classfied as homoplastic mutation in https://nextstrain.org/staging/nextclade/sars-cov-2. And that does not mean any concerning feature.

**Comment by FedeGueli** [comment]
Last samples collected are from 1st of february

**Comment by FedeGueli** [comment]
1459 sequences as today last ones coming in from Japan

**Comment by FedeGueli** [comment]
Against odds it accumulated 10 more seqs in the last 3 days.
@InfrPopGen if you could take a look at this.
I think i will propose the other weird ba.5.1 survivors in japan which are showing a great resilience resisting better than the most of high escape variant soup lineages.
Maybe it is worth reasoning about it why and why in Japan

@thomasppeacock @AngieHinrichs @corneliusroemer mentioned that in his last neherlab report[(here)](https://github.com/neherlab/SARS-CoV-2_variant-reports/blob/main/reports/variant_report_latest_draft.md)

**Comment by FedeGueli** [comment]
1473 as today

**Comment by FedeGueli** [comment]
1477 as today

**Comment by FedeGueli** [comment]
1481 seqs as today

**Comment by corneliusroemer** [comment]
This actually has a child lineage now, BA.5.1.38, so it can't be designated anymore

**Comment by AngieHinrichs** [comment]
Hmm, that one is a little tricky to track down.  It was added to lineage_notes.txt in e55f0c38:
```
git blame lineage_notes.txt | grep -F BA.5.1.38
e55f0c38 (Cornelius Roemer 2023-02-11 15:39:01 +0100 1044) BA.5.1.38    Alias of B.1.1.529.5.1.38, Japan, ORF8:S103L, S:R346T
```
It's not mentioned in the commit comments, but it was added to lineages.csv in the same commit:
```
git show e55f0c38
commit e55f0c382dd78520f2bf0713d7e3d3a9d234f7b6
Author: Cornelius Roemer <cornelius.roemer@gmail.com>
Date:   Sat Feb 11 15:39:01 2023 +0100

    Added lineages BF.7.16 (ORF1a:A498V) and BF.7.16.1 (S:A688V)

...
 USA/NJ-CDC-QDX43990065/2022,BA.5.1.37
+strain,BA.5.1.38
+France/PDL-HMN-22102210308/2022,BA.5.1.38
+France/BRE-IPP51510/2022,BA.5.1.38
+Japan/PG-393257/2022,BA.5.1.38
...
```

**Comment by FedeGueli** [comment]
@corneliusroemer @AngieHinrichs this is not the parental of BA.5.1.38, the defining mutation of it is Orf9b:P10F that is absent from BA.5.1.38

I think you got confused by the fact we (with @AnonymousUserUse ) were discussing all japanese ba.5.1+orf9b mutated lineages, one of them is BA.5.1.38 that should carry [Orf9b:T83I]

**Comment by AngieHinrichs** [comment]
I think the proposed branch here is 
```
BA.5.1 > C29541T > C21057T > C28312T
```
while BA.5.1.38 is quite different:
```
BA.5.1 > C28531T > G21232A > G25855T > C29518T > A13611G > C24700T > G21255T > C28201T > G22599C
```
