### ISSUE TITLE
One more XBB.1 + S:F486P sublineage defined by A10042G and T21363C - 79 sequences likely emerged in Pakistan, now it has spread internationally 14-03-2023

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1680]
Maybe one more XBB.1 + S:F486P sublineage.

interestingly it occurs before Orf8:G8* even if a cluster from England within this sublineage shows the orf8:G8* , thing that may doubt of this entire tree.(@AngieHinrichs @corneliusroemer )

**Gisaid query:** A10042G, T23018C,T21363C

**Tree**:
<img width="1160" alt="Schermata 2023-02-22 alle 13 15 26" src="https://user-images.githubusercontent.com/87669813/220617177-3cb34785-7e76-4e1e-8022-c3d7ec31753e.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_dbfc_605c60.json?label=id:node_7616541

Defining mutations:  
XBB.1* (No orf8:G8*) > T21363C > A10042G, S.F486P (T23018C)

**Sequences**: 24
EPI_ISL_402131, EPI_ISL_16341896, EPI_ISL_16417766,
EPI_ISL_16443171, EPI_ISL_16483784, EPI_ISL_16525759,
EPI_ISL_16525789, EPI_ISL_16547145, EPI_ISL_16547148,
EPI_ISL_16584388, EPI_ISL_16585091, EPI_ISL_16613047,
EPI_ISL_16613181, EPI_ISL_16702968, EPI_ISL_16808771,
EPI_ISL_16808817, EPI_ISL_16808846, EPI_ISL_16860579,
EPI_ISL_16878048, EPI_ISL_16902904, EPI_ISL_16906683,
EPI_ISL_16925127, EPI_ISL_16978224, EPI_ISL_16978558

if this is part of the lineages proposed to be merged in XBB.1.5 please close it.

**Comment by AngieHinrichs** [comment]
Yes, the late acquisition of ORF8:G8* (G27915T) is suspicious.

**Comment by FedeGueli** [comment]
new sequences coming in from Pakistan, Germany, Italy.

**Comment by AnonymousUserUse** [comment]
Note that England/PHEC-YY8WOII/2022|2022-12-22 has the mutation C21363T reversion according to the tree displayed in this issue.
So I think, it is more likely that sequences from England with Orf8:G8* etc. should be a sublineage of XBB.1.5 that acquires homoplasic mutation A10042F independently, and then a sublineage of (4 from 5) that acquires T21363C independently -- although T21363C is classified as unique in Nextstrain tree. Other sequences should be a real lineage defined by A10042G, T23018C following T21363C.

**Comment by FedeGueli** [comment]
new sequences coming in from Australia and Usa . total count is 30

**Comment by corneliusroemer** [comment]
I think we'll designate this sooner or later, but best to let it stabilize a bit further with more sequences.

**Comment by FedeGueli** [comment]
Apparently it jumped to 44 as today.
@corneliusroemer @AngieHinrichs i cant access to the tree right now but if real it was a big jump.

**Comment by FedeGueli** [comment]
> Note that England/PHEC-YY8WOII/2022|2022-12-22 has the reversion C21363T according to the tree displayed in this issue. So I think, it is more likely that sequences from England with Orf8:G8* etc. should be a sublineage of XBB.1.5 that acquires homoplasic mutation A10042F independently, and then a sublineage of that (4 from 5) acquires T21363C independently -- although T21363C is classified as unique in Nextstrain tree. Other sequences should be a real sublineage of XBB.1 defined by A10042G, T23018C following T21363C.
> 
> Besides, regarding the founder effect, it seems that XBB.1 without G27915T has at least some circulation in Pakistan, which makes the sublineage proposed in this issue more likely to be real.

i ve not looked on depth but that English cluster could be recombination with any Omicron lineage without Orf8/orf9b/N/Orf10 mutations and the sequence with the reversionat 21363 maybe just base calling or coinfection.

**Comment by FedeGueli** [comment]
Last sequences from Spain, Usa, Denmark, Australia. Total count is now 55.

**Comment by FedeGueli** [comment]
57 seqs found with A10042G, T23018C,T21363C query from India (Telangana) , Malaysia and Denmark.

on Usher i see 60 sequences showing some convergent spike mutations (554,883):

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_18714_a30500.json?c=userOrOld&label=id:node_7660941

<img width="1153" alt="Schermata 2023-03-09 alle 20 21 44" src="https://user-images.githubusercontent.com/87669813/224132149-5d828bf1-6a62-4f77-b5b5-86f53c2356f9.png">


@corneliusroemer has already his eyes on this lineage but i think it may be better to designate also to disentangle variant specific effect in what seems to be a new incoming wave India cc @thomasppeacock @AngieHinrichs @InfrPopGen

**Comment by corneliusroemer** [comment]
This is on the 541T branch of XBB.1 - probably worth designating if real as it clarifies the early development of XBB.1

**Comment by FedeGueli** [comment]
74 sequences as today, 9 samples uploaded today from Usa (3 states)  England Japan Italy Canada

**Comment by FedeGueli** [comment]
79 sequences new samples uploaded from Pakistan and France

**Comment by ryhisner** [comment]
There are now 62 sequences on the S:E554K branch alone, including a longish 14-sequence branch with the convergent ORF1a:T1638I and S:D936G. Definitely feels worthy of designation.
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/33738461/225168743-ec2d443e-4bed-4efe-8b2a-a570bfe9fe90.png">

**Comment by FedeGueli** [comment]
@thomasppeacock maybe not superfast as other recent discovered xbb.1*486P but still probably better to designate it .

**Comment by corneliusroemer** [comment]
It's a curious lineage. The ORF8:8* is strange - either recombination or homoplasy, or contamination. But I think it's either recombination or homoplasy.

I looked at it for a long time to see if it could possibly be an artefact but the 3 mutations: 541, 10042 and 21363 cluster strongly together. It's got to be real.
