### ISSUE TITLE
XBB.1 sublineage without Orf8:G8* with S:L455F and S:F456L -11 seqs as 18/04 Pakistan, England, Israel

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1681]
I spotted this possible sublineage of XBB.1 (before Orf8:G8* happened) defined by S:L455F,S:F456L .
This combo is predicted to  reduce dramatically ACE2 binding while it could have an high impact on immune escape side.
Being the oldest sequence from Pakistan a very undersampled area and the two more recent ones from two different countries i prefer to propose it and monitor publicly for a while.

Gisaid query: C2509T,G22927T, T27531C ,T22928C

Defining mutations:
XBB.1 >C2509T >  T27531C, S:L455F (G22927T) ,S:F456L (T22928C)

Sequences:
EPI_ISL_16598936, EPI_ISL_16996058, EPI_ISL_1699664

Tree:
<img width="1065" alt="Schermata 2023-02-22 alle 13 45 37" src="https://user-images.githubusercontent.com/87669813/220623476-f4e6587e-9c72-4833-8190-8e601bcfd3b3.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_dbfc_605c60.json?c=userOrOld&label=id:node_9690563

**Comment by FedeGueli** [comment]
two new sequences uploaded from England. tot now is 5. I think it has some kind of prevalence right now in Pakistan . @corneliusroemer i will monitor this one closely.

**Comment by FedeGueli** [comment]
Looking at Usher there is one more sequence from Pakistan:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_27e24_7e3e50.json?c=userOrOld&label=id:node_9701260
<img width="1128" alt="Schermata 2023-02-23 alle 23 19 44" src="https://user-images.githubusercontent.com/87669813/221043572-67ae4bfd-f7ee-4cad-868d-223d9176d63d.png">

**Comment by FedeGueli** [comment]
No new sequences of this one, so i can close it.

**Comment by FedeGueli** [comment]
11 sequences now. Today 3 new samples of this lineage have been uploaded by Pakistani scientists ,
interestingly they cluster together and all of them have an additional rare spike mutation in S2 S:K933Q
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12c03_f06e80.json?c=userOrOld&label=id:node_5824545

<img width="1089" alt="Screenshot 2023-04-18 alle 23 28 52" src="https://user-images.githubusercontent.com/87669813/232909327-64f70ebb-629e-441e-b1ee-06fedd35403f.png">

**Comment by FedeGueli** [comment]
Put this again to sleep as no new sample popped up for a while. i ll check it pvtly

**Comment by krosa1910** [comment]
@FedeGueli Help me figure this one out.  Gisaid Inquiry using G12467T,G22927T, T22928C gives 4 new seqs, 1 Chile and 3 NJ, US.
It is put under a different tree at Usher, but I just wonder if it is a continuation of your lineage.
This popped up very recently, all showing up after 04-08.

**Comment by FedeGueli** [comment]
@krosa1910 thx for noticing i will check that for sure

**Comment by FedeGueli** [comment]
Designated XBB.1.48 via https://github.com/cov-lineages/pango-designation/commit/d9809606594475b005114a33bc78b12484416cae
