### ISSUE TITLE
DJ.1.1 sublineage with S:Y144-, ORF1ab:T4083M (302Seqs, mainly in Sweden and Peru)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1682]
Defining mutations: DJ.1.1 > S:Y144-,ORF1ab:T4083M (C12513T)

Earliest seq: 2022-10-13 (Peru, EPI_ISL_15804894)
Most recent seq: 2023-02-10 (Sweden, EPI_ISL_16954635)
Countries detected: Sweden (171), Peru (70), USA (21), Denmark (13), Austria (5), Germany (3), Canada (3), Portugal (1), Italy (1), Netherland (1), UK (1), Panama (1)

Tree:
![QQ截图20230222224146](https://user-images.githubusercontent.com/121703496/220656552-afbf9b21-1309-4403-8d27-b4a9a2907cff.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1fc04_454990.json

Description:
DJ.1 (BA.5.1.25.1) lineage is firstly detected in South America (once very common in Peru during Oct-Nov 2022). DJ.1 is defined as BA.5.1.25+S:K444N and DJ.1.1 further gets S:N460K (Fig.1) .

![QQ截图20230222213403](https://user-images.githubusercontent.com/121703496/220635828-c52a8b8b-bc07-407b-9668-0f5ebab3f8d0.png)

#1407   proposed a DJ.1.1 sublineage with Y:144- and ORF8:W45S and nuc T15516C, finally DJ.1.1.1 defined as DJ.1.1 with S:K147N. My proposal is also with ORF8:W45S and Y:144-, but without nuc T15516C (Fig.2).
![QQ截图20230222213226](https://user-images.githubusercontent.com/121703496/220643053-66beba86-20a9-418b-848c-6637575635a6.png)

Recently, most of DJ.1 sublineages have decayed (including DJ.1.1.1, shown in Fig.3), but the branch with S:Y144- and ORF1ab: T4083M "sailed across the Atlantic" and now slightly grows in Sweden (Fig.4).
![QQ截图20230222220615](https://user-images.githubusercontent.com/121703496/220644237-17083873-dec7-48e1-8927-f596740a2e92.png)
![QQ截图20230222220540](https://user-images.githubusercontent.com/121703496/220644324-21687c7e-a658-4035-a984-da98a64737d2.png)

 

Genomes:

[Genomes-for-possible-DJ.1.1-sublineage.txt](https://github.com/cov-lineages/pango-designation/files/10804847/Genomes-for-possible-DJ.1.1-sublineage.txt)

**Comment by HynnSpylor** [comment]
302 seqs now

**Comment by FedeGueli** [comment]
T15516C is jist in DJ.1.1.1 the proposef DJ.1.1 in #1407 mistakenly reported it but de facto the one proposed here is a sublineage of the one proposed and then tracked in #1407.

@InfrPopGen @thomasppeacock @corneliusroemer @AngieHinrichs please if you check this one i think we can close both issues just with the designatio  of eventually DJ.1.1.2 dtartimg with S:144del.

cc @HynnSpylor

**Comment by FedeGueli** [comment]
@corneliusroemer btw NExtclade massively misassigns DJ.1.1+ S:Y144del to DJ.1.1.1 which is instead defined by T15516C + S:K147N

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there have been very few detections over the past three months, and the initial growth advantages seen in some regions, have since faded; this can be closed for now. Please request re-opening should this lineage show a strong resurgence.
