### ISSUE TITLE
XBB.1.5 with S:P251S (134 seq., 8 countries)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1684]
Proposal for a sublineage of XBB.1.5
Earliest sequence: 24.12.2022 (USA)
Countries detected: USA, Irland, Scotland, England, Austria

Defining mutations:
S:P251S = C22313T

Gisaid query: A20118G, C22313T, G28079T

![grafik](https://user-images.githubusercontent.com/102166254/220731175-37d524bf-e25f-4607-af25-178e17a75e7d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_17593_663d70.json?label=id:node_7650674

EPI_ISL_16579224, EPI_ISL_16734149, EPI_ISL_16734176, EPI_ISL_16754452, EPI_ISL_16754582, EPI_ISL_16904571, EPI_ISL_16908137, EPI_ISL_16998382, EPI_ISL_16998386, EPI_ISL_16998387, EPI_ISL_16998388, EPI_ISL_16998389, EPI_ISL_16998390, EPI_ISL_16998391, EPI_ISL_16998392, EPI_ISL_16998393, EPI_ISL_16998394, EPI_ISL_16998398, EPI_ISL_16998399, EPI_ISL_16998400, EPI_ISL_16998401, EPI_ISL_16998402, EPI_ISL_16998408, EPI_ISL_16998409, EPI_ISL_16998419, EPI_ISL_16998426

OQ420254.1, OX427154.1, OX427437.1, OX427709.1, OX430833.1

**Comment by FedeGueli** [comment]
I was just highlighting it in the XBB.1.5 spike diversity. tracked there since a while.

**Comment by agamedilab** [comment]
47 seq as of 01.03.23.

![grafik](https://user-images.githubusercontent.com/102166254/222072156-003f35ce-0b8d-46f2-90b3-b8b00eed08e3.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c8a3_efdba0.json?c=country&label=id:node_7684955

**Comment by agamedilab** [comment]
96 on usher as of 09.03.23.

![grafik](https://user-images.githubusercontent.com/102166254/224020777-9b9cc431-2bbd-4d92-9aa6-989af1c5fb53.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8263_9cdcb0.json?c=gt-S_251&label=id:node_7705792

**Comment by agamedilab** [comment]
134 as of 20.03.23.

![grafik](https://user-images.githubusercontent.com/102166254/226272938-f39d8b6a-e01b-4b03-9119-a87c23917602.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3195a_809990.json?c=country&label=id:node_7770565

**Comment by FedeGueli** [comment]
Designated EK.3  from https://github.com/cov-lineages/pango-designation/commit/cb295223b59a842d7b010c25ed415792bb0adc5c

**Comment by agamedilab** [comment]
I would be very happy if a designated label and milestone could be added to the issue! Many thanks! @corneliusroemer @InfrPopGen

**Comment by agamedilab** [comment]
many thanks! @corneliusroemer
