### ISSUE TITLE
XBB.1 with additional mutations ORF1ab:P5371L; Nuc:G20670A mainly in Canada

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#1687]
XBB.1 with additional mutations ORF1ab:P5371L; Nuc:G20670A mainly in Canada by Group of Genomic Surveillance INS-PERU

**Description**
Sub-lineage of: Potential new sub-lineage of XBB.1
Earliest sequence: hCoV-19/USA/NC-CORVASEQ-1085-8506-z/2022 (13/12/2022, USA)
Most recent sequence: hCoV-19/Canada/ON-PHL-11142/2023 (07/02/2023, Canada)

**Countries circulating**
Canada (29), USA (1)

This potential XBB.1 is distributed mainly in Ontario, Canada.

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/10818972/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24893_7e2290.json?c=gt-nuc_16376,20670&label=id:node_7689071
<img width="1648" alt="ORF1abP5371L" src="https://user-images.githubusercontent.com/87997149/221042856-fcdbf5cc-f6de-4e28-996b-4bddf16b3a2c.png">
**Proposed sub-lineage name**
XBB.1.X

**Comment by LuisBarcenaF** [comment]
Hi, everyone

Progress in the past 2 months in Ontario, Canada

https://cov-spectrum.org/explore/Canada/AllSamples/Past2M/variants?aaMutations=ORF1b%3AP970L&nucMutations=G20670A&nextcladePangoLineage=XBB.1&

<img width="1559" alt="cov1" src="https://user-images.githubusercontent.com/87997149/221191562-ccbe94d5-5dcc-466a-92e2-c91ec654f801.png">

<img width="1565" alt="cov2" src="https://user-images.githubusercontent.com/87997149/221190912-9d906a9a-7310-46cc-9803-43c0fb170d50.png">

**Comment by FedeGueli** [comment]
Probably worth closing it if it didnt gain any spike mutation of interest?

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it did not show a relative growth advantage in February, and it has not been much detected since proposal, this can be closed for now. Please re-propose or request re-opening if this clade shows future re-emergence and marked growth.
