### ISSUE TITLE
XBB.1.5 + S:I410V and S:P521S circulating in central europe 199 sequences as today (18-03-23)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1688]
I spotted this sublineage of XBB.1.5 that seems accumulating fastly sequences in Germany, Austria (spike only samples), Netherlands and was sampled also in England, Scotalnd, Singapore (one local case and one in a traveller from Switzerland.

It captured my attention cause it is characterized by two spike mutation one in Rbd and the other right after RBD

**Defining mutations**:
XBB.1.5 > > C920T > C21910A > S:p521S (C23123T) > SPike:I410V (A22790G )

**Tree** ( note that 13 spike only sequences are missing from it):
<img width="1151" alt="Schermata 2023-02-23 alle 23 45 10" src="https://user-images.githubusercontent.com/87669813/221047707-1ebe432f-24ec-4d9e-b1ae-dc4a529ce168.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d83f_7e9b70.json?c=userOrOld&label=id:node_7652127

**Gisaid query**: Spike_I410V,Spike_P521S,Spike_F486P

**Sequences**: EPI_ISL_16874995, EPI_ISL_16899435, EPI_ISL_16905264,
EPI_ISL_16942932, EPI_ISL_16943133, EPI_ISL_16963356,
EPI_ISL_16978268, EPI_ISL_16996741, EPI_ISL_17004417,
EPI_ISL_17004420, EPI_ISL_17004519, EPI_ISL_17004533,
EPI_ISL_17004563, EPI_ISL_17006050, EPI_ISL_17006760,
EPI_ISL_17006837, EPI_ISL_17010099, EPI_ISL_17010112,
EPI_ISL_17010157, EPI_ISL_17010185, EPI_ISL_17010323,
EPI_ISL_17010543, EPI_ISL_17010552, EPI_ISL_17010691,
EPI_ISL_17011339, EPI_ISL_17011808

Predicted composite fitness is not better than original, but i dont know if any epistasis is at work here ( @thomaspeacock) :
<img width="192" alt="Schermata 2023-02-23 alle 23 47 19" src="https://user-images.githubusercontent.com/87669813/221048039-3b3f8e74-53f3-43c0-8b34-9a7658594c22.png">

**Comment by FedeGueli** [comment]
31 as today. all new samples from Austria (spike only seqs)

**Comment by FedeGueli** [comment]
34 sequences as today newly found in Denmark and Luxembourg beyond Germany, Austria, Netherlands, Uk, Singapore, Australia

**Comment by FedeGueli** [comment]
54 sequences as today, just from march uploads i see Iceland, Italy, Usa , Netherlands, Germany  , Austria.  I think this deserves a designation. @corneliusroemer @InfrPopGen

**Comment by FedeGueli** [comment]
New sequences are accumulating from central europe: last samples from Denmark Netherlands and Germany

**Comment by FedeGueli** [comment]
@corneliusroemer @thomasppeacock @InfrPopGen big jump of this sublineage in the last days:
It appears to be circulating in  Germany , Austria, Denmark and Netherlands
More than half of its samples have been collected after 20th of february,
Its prevalence in the last 20 days in Austria Denmark and Netherlands is around 1%

I suggest to designate it .

**Comment by FedeGueli** [comment]
135 sequences with the last mostly coming from Austria with singlets from Denmark and Netherlands

**Comment by FedeGueli** [comment]
@thomasppeacock i think that differently from other XBB.1.5 sublineages proposed by me where the spike mutation seems to identify a local lineage with limited spread outside , this is circulating widely in at least 4 countries in Central Europe.

**Comment by FedeGueli** [comment]
@thomasppeacock @corneliusroemer @AngieHinrichs @InfrPopGen 
Big upload yesterday from Austria it Jumped to 199, its last doubling estimated via Cornelius alternative method is 7 days ,
in comparison to 6 Days of XBB.1.16 and XBB.1*486P*D215H from Africa. Parent XBB.1.5 is far at 14 days and the XBB.1.9*Twins and XBB.1*486P*Y200C (that has orf1b:5t too) are at 11 days. 

I would designate this one.

**Comment by corneliusroemer** [comment]
Couldn't decide where to start so went all in with the 920T branch being XBB.1.5.26, S:521S being EU.1, and S:410V being EU.1.1

It's not clear if 410V is founder or not, hence makes sense to designate also the parent with just 521S.

**Comment by FedeGueli** [comment]
Thx @corneliusroemer for your great work. Agree wit your choice to differentiate it more than the proposed. thx.
