### ISSUE TITLE
BQ.1* x XBF (or XBK) recombinant (23 sequences as of 2023-03-04, Germany and Austria)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1689]
### Description
**Recombinant between**: BQ.1* and XBF (or XBK)
**Earliest sequence**: 2022/12/28 (Austria)
**Most recent sequence**: 2023/02/15 (Germany-BW)
**Countries circulating**: Austria (3/22), Germany (19/22)
**Potential breakpoint**: Spike, between AA 339 and 446
**Potential BQ.1 donor**: a BQ.1.1 subclade with additional T14257C, A17039G and G20679T from Austria, such as EPI_ISL_15936807.

**Mutation profile**:
![image](https://user-images.githubusercontent.com/86835836/221089372-9fd7b106-8171-4b06-9cce-a4f1c28171b9.png)

**Private mutations**: N:K299I (19/22 sequences in Germany)
**GISAID and Cov-spectrum query**: C1931A, A17039G, G20679T, A26275G

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/221089643-381fb8fe-dd09-4b53-ae16-fab0d44a4498.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8195_4af8f0.json?branchLabel=none&c=gt-nuc_20679,378,3181,4915,22115,22021&label=id:node_7954664

### Genomes:
EPI_ISL_16377998, EPI_ISL_16475710, EPI_ISL_16527367, EPI_ISL_16882917, EPI_ISL_16882928, EPI_ISL_16883034, EPI_ISL_16883038, EPI_ISL_16883059, EPI_ISL_16883062, EPI_ISL_16883095, EPI_ISL_16883117, EPI_ISL_16883170, EPI_ISL_16886072, EPI_ISL_16940242-16940243, EPI_ISL_17003777, EPI_ISL_17003803, EPI_ISL_17003841, EPI_ISL_17003857, EPI_ISL_17004926, EPI_ISL_17004997, EPI_ISL_17005077

**Comment by AnonymousUserUse** [comment]
The breakpoint is between S:339 and S:444 because of S:444K

**Comment by c19850727** [comment]
closing this proposal as it's not growing any longer.
