### ISSUE TITLE
Proposal for 3 potential new lineages circulating in Mexico and the US

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#169]
**Proposed new lineage 1**
Potential sublineage of A.2.5 (28 sequences in the US, mainly CA, and 6 in Mexico)
Earliest sequence: 2021/5/28 (US - CA)
Most recent sequence: 2021/7/22 (US - CA)
In addition to usual A.2.5 mutations, this potential new sublineage also has:
ORF1a: A967V, T1344R
ORF1b: V1149L, H1550Y
S: 141/144del, W152R, D215Y, T240I, A263S
**Genomes:**
EPI_ISL_2441921, EPI_ISL_2480167, EPI_ISL_2481551,
EPI_ISL_2598790, EPI_ISL_2715655, EPI_ISL_2774620,
EPI_ISL_2775608, EPI_ISL_2785604, EPI_ISL_2785612,
EPI_ISL_2787777, EPI_ISL_2801779, EPI_ISL_2810069,
EPI_ISL_2873126, EPI_ISL_2873593, EPI_ISL_2927395,
EPI_ISL_2942660, EPI_ISL_3016502, EPI_ISL_3050209,
EPI_ISL_3050212, EPI_ISL_3050214-3050215, EPI_ISL_3050243,
EPI_ISL_3050251, EPI_ISL_3208386, EPI_ISL_3211771,
EPI_ISL_3212428
**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/128197384-8e6109f8-36c8-45e9-97b2-74863cc628c2.png)

**Proposed new lineage 2**
Potential sublineage of B.1.243 (32 in Mexico)
Earliest sequence: 2021/5/10
Most recent sequence: 2021/7/15
In addition to usual B.1.243 mutations, this potential new sublineage also has:
N: P13L, S202G
ORF1a: A181T, H1500Y, A2344V, S2926F, D3222N, K3353R, T3646A, Q3777R, G3971S
ORF1b: E1728D
ORF9b: P10S
S: 246/248del, T478K, N501T, N679K, N751K, D936H, D950N 
**Genomes:**
EPI_ISL_2341030, EPI_ISL_2341032, EPI_ISL_2341042,
EPI_ISL_2598009, EPI_ISL_2779620, EPI_ISL_2790212,
EPI_ISL_2861192, EPI_ISL_2966365, EPI_ISL_2966381,
EPI_ISL_2966385, EPI_ISL_2966388-2966391, EPI_ISL_2966393-2966395,
EPI_ISL_2966397-2966398, EPI_ISL_2970391, EPI_ISL_3010940,
EPI_ISL_3010945, EPI_ISL_3010951, EPI_ISL_3062847,
EPI_ISL_3062855, EPI_ISL_3062858, EPI_ISL_3133773,
EPI_ISL_3133784, EPI_ISL_3162228, EPI_ISL_3162233,
EPI_ISL_3162237, EPI_ISL_3162259
**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/128200787-c85de475-1656-44b1-a5c0-ea5f34d7cfb9.png)

**Proposed new lineage 3**
Currently classified as B.1.2 (7 in Texas, the US)
Earliest sequence: 2021/5/21
Most recent sequence: 2021/6/12
Mutations:
N: P67S, P199L, R209I, L221F
ORF1a: T265I, Y1325F, T1638I, N2361K, M2606I, H2831Y, L3352F, L3606F, N4167K, A4285V
ORF1b: N129S, P314L, T1555I, N1653D, R2613C
ORF3a: Q57H, G172V
ORF8: S24L
ORF9b: R13H
S: T95I, D215H, 241/243DEL, E484K, F490S, D614G, Q836K, A1078V 
**Genomes:**
EPI_ISL_2658958, EPI_ISL_2658962-2658963, EPI_ISL_2658970-2658972,
EPI_ISL_2858877
**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/128204855-a6370468-0a33-4cf1-a21a-79c40caafd9e.png)

**Comment by chrisruis** [comment]
Thanks @c19850727. We've added your proposed lineage 2 as B.1.243.2 in [v1.2.67](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.67)

It's not clear that your proposed lineages 1 is epidemiologically distinct from A.2.5 so we haven't designated this. Additionally, proposed lineage 3 may represent continued circulation of B.1.2 but is too small to warrant a separate designation at this stage. We'd recommend that the sequences in proposed lineage 1 are referred to as A.2.5 and the sequences in proposed lineage 3 are referred to as B.1.2.
