### ISSUE TITLE
BA.2 Saltation/Recombinant Sublineage in Ukraine (12 seq, Apr 2)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1692]
### **Description**
**Sub-lineage of:** BA.2
**Earliest sequence:** 2023-1-9, Ukraine, Lviv — EPI_ISL_17018585
**Most recent sequence:** 2023-1-27, Ukraine, Poltava — EPI_ISL_16997637, EPI_ISL_17018651
**Countries circulating:** Ukraine
**Number of Sequences:** 10
**GISAID Query:** M_G6S, M_L16I, Spike_T961M
**CovSpectrum Query:** [8-of: G569A, A1585C, C3809T, C3811T, A4308G, T4435A, C13197T, C16101T, A22012T, C22088T, C22295A, C22326T, C23202A, C22792T, T24073C, C24444T, G26538A, C26568A, C28550A]
Note: only two other sequences have ever had four of the 19 nucleotide mutations listed above, so this search isn't likely to catch anything that doesn't belong to this lineage.
**Substitutions on top of BA.2:**
**Spike:** K150N, L176F, H245N, S255F, N417T, T547K, T961M
**ORF3a:** H78Y
**N:** P151L
**M:** G6S, L16I, E19Q (Reversion), T63A (Reversion)
**ORF9b:** D89E
**ORF1a:** E102K, R135S (Reversion), L1182F, K1348R, T4311I
**Nucleotide:** G569A, G670T (Reversion), A1585C, C3809T, C3811T, A4308G, T4435A, C13197T, C16101T, A22012T, C22088T, C22295A, C22326T, C23202A, C22792T, T24073C, C24444T, C25624T, G26538A, C26568A, G26577C (Reversion), A26709G (Reversion), T26858C (Reversion), C27259A (Reversion), C27382G (Reversion), T27383A (Reversion), C27384T (Reversion), C28550A
**AA Deletions:** S:69-70del, S:V483del, M:A2del
**Nucleotide Deletions:** 21765-21770, 23009-23011, 26526-26528

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/Ukraine_BA.2_Saltation_subtreeAuspice1_genome_3a8ea_8dabd0.json 
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/33738461/221241676-00753b83-edfc-477c-a42a-cbc1e7012110.png">

**Evidence**
This lineage has appeared suddenly in four different regions of Ukraine: Lviv, Poltava, Rivne, and Ternopil. The metadata indicate that four patients have likely been sequenced twice, meaning that six separate patients have been sequenced. There is missing coverage in all of these sequences, mostly in the same regions of the genome, so there could be additional mutations present but not yet detected. S:N417T, for example, is likely in all of these sequences, but the shaky coverage in that area fails to register it in every sequence. 

There are a large number of reversions here, which has to indicate some sort of recombination in the region from 26577-27384. However, I don’t know what variant this region would have been acquired from. The ORF1a:R135S reversion potentially indicates that the 5’ end of the genome may have been acquired via recombination as well, though this could also be a genuine reversion. 

The deletion at S:V483 is particularly interesting here. Deletions at S:483 and S:484 have been seen in isolated sequences, usually ones with signs of chronic infection. However, these have almost never spread. The only partial exception was a small branch of BF.7 with S:E484del in Denmark that showed up in a number of sequences before disappearing.

Also very interesting is the presence of ORF9b:D89E, which is also in BA.2.3.20 and which I've noticed in a number of other hypermutated, chronic-infection sequences. Another very rare mutation (<1000 sequences all time) in this lineage that shows up in some of the most extreme chronic-infection sequences is M:G6S. Together with M:A2del and M:L16I, this makes for an exceedingly unusual M gene. 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16997609, EPI_ISL_16997637, EPI_ISL_16997638, EPI_ISL_16997640, EPI_ISL_17018585, EPI_ISL_17018592, EPI_ISL_17018621, EPI_ISL_17018641, EPI_ISL_17018646, EPI_ISL_17018651
</details>

**Comment by aviczhl2** [comment]
Worth noticing that EPI_ISL_14503437, an AY.43 sampled on 2022.7 in Ukraine, also has ORF9b:D89E.

**Comment by thomasppeacock** [comment]
Going to put into monitoring until some higher coverage genomes are uncovered, and then i would suggest this gets prioritised for assignment

**Comment by corneliusroemer** [comment]
Interesting ones, we need some higher coverage ones for designation but these are interesting indeed.

<img width="2549" alt="image" src="https://user-images.githubusercontent.com/25161793/221396197-c46eb6c8-a1ea-46ba-83e4-ae405b41e111.png">

Nextclade thinks they are close to XAD/XAP which are BA.2/BA.1 recombinants - maybe because of the T547K?

**Comment by MCB6** [comment]
56 more genomes from Ukraine just got uploaded, mostly from Jan-Feb. Not a single instance of M_G6S, M_L16I, Spike_T961M in GISAID...

**Comment by ryhisner** [comment]
I noticed that, @MCB6. Partly, this may have been because only 8 or the 49 sequences from Jan/Feb were from the regions where this lineage had previously been detected (six from Lviv and two from Ternopil). There were no sequences in the recent upload from Rivne or Poltava.

**Comment by MCB6** [comment]
Interestingly, there were 10 samples (18 including apparent duplicates) from Rivne in an _earlier_ (Feb 2) upload, with the same collection date range as the suspected mutant.  Also 8 samples (13 including duplicates) from Lviv in the Feb 2 upload, again the same collection dates as the putative mutant.
So it popped across the nation at once but only in one upload batch. Not in other samples collected on the same dates but uploaded in different batches. Just saying...

**Comment by MCB6** [comment]
One more instance in today's upload from Ukraine,  EPI_ISL_17155988, collected in Odesa Feb 2.  But among the 17 samples from Lviv,  it wasn't seen again

**Comment by corneliusroemer** [comment]
Unfortunately same coverage issues again.

If anyone has contacts to submitters (Iryna Demchyshyna, Liudmyla Chernenko, Ihor Kuzin, Anna Iaruchyk, Olena Isnyuk, Liudmyla Kota), it could be interesting to investigate further.

**Comment by MCB6** [comment]
Ukraine's PHC has an email for queries, press@phc.org.ua, not sure if that can help though

**Comment by corneliusroemer** [comment]
@MCB6 I was thinking of informal channels 🙃

**Comment by MCB6** [comment]
There is a gmail associated with a number of Iryna Demchyshyna's publications, iradem27@gmail.com. Too many sites to consider my message a violation of privacy, I hope. The trick is to use the Russian spelling of her name, Ирина Демчишина, rather than Ukrainian spelling. The former spelling appeared on several publications with an email, the latter, Ukrainized spelling did not. There may be a grave reason why she dropped using contact info. She may have been harassed / hounded by the Putinists, who justify the war in Ukraine by alleging that the internationally funded pathogen research labs like hers are developing biological or genetic weapons against Russia or the Russians. According to Russian state propaganda, the alleged bio-threat is so severe that only defeating and occupying Ukraine may "make Russia safe". Iryna Demchyshyna's name is regularly invoked in Russian propaganda pieces among the names of the enemies. So she might have a legit reason to hide...

**Comment by MCB6** [comment]
@corneliusroemer  sent you a couple addresses @ phc.org.ua by gmail

**Comment by corneliusroemer** [comment]
No new sequence since March 8th, just checked GISAID

**Comment by MCB6** [comment]
There were no uploads from Ukraine since March 8.  But it isn't out of the ordinary. In February they had a 3-week break. And before January, at the height of the rocket attacks against electric power installations, they went months without any uploads.

**Comment by MCB6** [comment]
A new upload at last. No hypermutant. Few samples from its previous locations (just one from Lviv, 3 from Rivne, all of those XBB.1.5; 3 from Odesa with two of them XBB.1.5; and one from Poltava)

**Comment by MCB6** [comment]
and one more load, a 2nd one in 3 days. Mostly late Feb. No hypermutant.

**Comment by ryhisner** [comment]
This lineage seemed to have disappeared as quickly as it appeared, but one additional sequence was uploaded yesterday with a collection date (February 22) 20 days later than the next most recent sequence. Coverage is very bad, as with the others. 
EPI_ISL_17367282

**Comment by ryhisner** [comment]
Just realized that this most recent sequence has ∆2-3 in ORF7a, something not seen in any of the other sequences. It's possible the other sequences really do have this deletion but it was not detected, something that commonly occurs in low-resource countries. There are 12 sequences total in this lineage as of today. 
EPI_ISL_16997609, EPI_ISL_16997637, EPI_ISL_16997638, EPI_ISL_16997640, EPI_ISL_17018585, EPI_ISL_17018592, EPI_ISL_17018621, EPI_ISL_17018641, EPI_ISL_17018646, EPI_ISL_17018651, EPI_ISL_17155988, EPI_ISL_17367282
<img width="958" alt="image" src="https://user-images.githubusercontent.com/33738461/229383609-dad11dce-3e6b-4854-b868-63e332d2791a.png">

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there have been no new detections over nearly two months, this can be closed for now. Please request re-opening should this one reemerge or new data come out of the Ukraine, as delays/interruptions are likely.
