### ISSUE TITLE
Potential artefacts to be aware of

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1693]
While reviewing sequences, I often come across artefacts, so I thought I list them here so that they don't end up defining lineages by accident.

First probably artefact:

S:D80Y (turquoise mutation before yellow S:83 one) in UK BRBR sequences is suspicious because it happens only in that lab, is G>T (very rare) and across two distinct XBB lineages: XBB.1.9 and XBB.1.5, which have at least 2 Spike mutations that differ between them.

<img width="1922" alt="image" src="https://user-images.githubusercontent.com/25161793/221271547-b16ee147-472b-45cd-8e59-b9479878ac6d.png">

If you spot something suspicious, feel free to add. Let's keep it concise though to make it easy to scroll through.

**Comment by ryhisner** [comment]
Great idea for a thread. 

(Pedantic note: G->T, though only about half as common as it was in the pre-Omicron ear, is still one of the more common nucleotide mutations. Only C->T, G->A, A->G, and T->C are more common. T->G is one of the rarest, so I'm guessing you were thinking of that one.)

**Comment by corneliusroemer** [comment]
Good point @ryhisner, rephrase as it's one of the medium rare ones. C->T is the most common, followed by T->C and A-> G.

**Comment by alurqu** [comment]
ORF1a:C344F, another G->T mutation, suddenly appeared recently in several lineages including BQ.1.1, CH.1.1, XBB.1.5, and XBB.1.9.1. So far all but one sample is from Germany. I suspect that this might be an artefact.

ORF1a:D2299Y, yet another G->T mutation, also suddenly appeared recently in several lineages including BQ.1.1, CH.1.1, XBB.1.5, and XBB.1.9.1. So far all but six samples are from Germany; however, the other samples are from 5 other countries. This also frequently co-occurs with ORF1a:C344F. I also suspect that this might be an artefact.

Finally, synonymous nucleotide mutation A18585G has followed a similar recent pattern except it hasn't appeared in CH.1.1. It also has appeared previously. In the recent appearance, all but seven samples are from Germany. In this recent surge it has also frequently appeared with the other two mutations mentioned in this comment. I'm less certain about this one, but I still suspect it might be an artefact.

**Comment by corneliusroemer** [comment]
@alurqu the ones you mention are the same as I reported here, right? https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/issues/47:
- G1296T
- G7160T

**Comment by alurqu** [comment]
> @alurqu the ones you mention are the same as I reported here, right? [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#47](https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/issues/47):
> 
>     * G1296T
> 
>     * G7160T

Yes these are the two non-synonymous mutations that I mentioned as possible artefacts.
