### ISSUE TITLE
New XBB.2 sublineage with S:M153I and ORF1a: T2988I mutation circulating in Peru

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#1694]
**A) Description**
New possible XBB.2 sub-lineage with S:M153I, ORF1a: T2988I mutation proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**B) Dates:** from 2022-12-28 to 2022-12-29

**D) Countries circulating:**
Peru (27)

E) Genomes
[genome.csv](https://github.com/cov-lineages/pango-designation/files/10827984/genome.csv)

F) Evidence
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_11664_908670.json?c=gt-S_153&f_userOrOld=uploaded%20sample&label=id:node_9701282

![imagen](https://user-images.githubusercontent.com/89021119/221273290-acb3380a-2af9-4c82-9c47-4e3bff49f0ed.png)

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it has not shown much activity since January, this can be closed for now. Please re-propose or request re-opening should this clade re-emerge with marked growth.
