### ISSUE TITLE
CH.1.1.3 with Orf1a:A482T,Q2034H and T395I in Hong Kong (96% of the Hong Kong CH.1.1.3 seqs, 31 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1695]
Sub-lineage of :CH.1.1.3
Earliest sequence: 2022.11.12(Hong Kong) EPI_ISL_15894902
Most Recent sequence: 2023.1.31 (Hong Kong) EPI_ISL_16902556
GISAID query: Spike_S255P, Spike_R346T, Spike_F486S,Spike_K444T,Spike_L452R, G1709A,G6367T,C1449T
No. of seqs: 26 (23 Hong Kong, 2 Japan, 1 USA)

Mutations on top of CH.1.1.3: G1709A(Orf1a:a482T),G6367T(Orf1a:Q2034H),C1449T(Orf1a:T395I)

23/24(96%) of the Hong Kong CH.1.1.3 seqs have the 3 orf1a mutations.  

Genomes:
EPI_ISL_15894902, EPI_ISL_16026793, EPI_ISL_16026803,
EPI_ISL_16026824, EPI_ISL_16026841, EPI_ISL_16026862,
EPI_ISL_16026890, EPI_ISL_16026898, EPI_ISL_16077172,
EPI_ISL_16077189, EPI_ISL_16077196, EPI_ISL_16077210,
EPI_ISL_16348401, EPI_ISL_16376636, EPI_ISL_16376661,
EPI_ISL_16376689, EPI_ISL_16524094, EPI_ISL_16524102,
EPI_ISL_16524113, EPI_ISL_16664334, EPI_ISL_16717115,
EPI_ISL_16902501, EPI_ISL_16902556, EPI_ISL_16902562,
EPI_ISL_16948785, EPI_ISL_16973882
<img width="1227" alt="Screen Shot 2023-02-25 at 15 04 26" src="https://user-images.githubusercontent.com/10445944/221344078-eb557178-2242-47a5-bfc4-1a665b2af659.png">
<img width="1243" alt="Screen Shot 2023-02-25 at 15 04 18" src="https://user-images.githubusercontent.com/10445944/221344083-e14b38de-00d9-4437-b2d9-33027514d9e7.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_326d2_9ae9d0.json?c=gt-ORF1ab_482,2034,395&label=id:node_7944477

Also, for Hong Kong CH.1.1.3 seqs sampled after 2022-12-27, 7/8(87.5%) also have Orf1a:V2943I(G9092A, C13923T) on top of the orf1a:A482T,Q2034H and T395I, while 0 of the 16 sequences before 2022-12-26 has Orf1a:V2943I.

**Comment by aviczhl2** [comment]
29 seqs now.

**Comment by corneliusroemer** [comment]
Very slow, almost no new sequences in a month, closing for now
