### ISSUE TITLE
BQ.1.1.46 sublineage with S:V1264L (>200 seq, mainly in France)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1696]
Query: G25352T, T25406C, C22033A
Defining mutations: BQ.1.1.46+S:V1264L(G25352T)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=G25352T%26T25406C%26C22033A&
![1](https://user-images.githubusercontent.com/115189228/221347461-ffa29f0b-55a6-4e75-ac1a-a80aa5dbfd3c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9144_9c3d80.json?c=gt-S_1264&label=id:node_5989216

**Comment by oobb45729** [comment]
The growth advantage of BQ.1.1.46+S:V1264L over BQ.1.1.46(which is rising) is clear.
![2](https://user-images.githubusercontent.com/115189228/221353869-6adbc916-dac9-4f98-be2f-2298b93dbb01.png)
![3](https://user-images.githubusercontent.com/115189228/221353873-03461338-ea5f-4e2f-838b-04a586e4f56d.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=T25406C%26C22033A%26C1931A&variantQuery1=G25352T%26T25406C%26C22033A%26C1931A&analysisMode=CompareToBaseline&

**Comment by oobb45729** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9788845/
This recent paper claims:
>Together, these results indicate that the V1264L mutation hampers the localization of the spike protein on the cell surface, thereby preventing the incorporation of spike protein into pseudovirus particles, but also promotes the intracellular localization of the spike protein accordingly and facilitates the assembly of infectious SARS-CoV-2 virions.

**Comment by FedeGueli** [comment]
S:V1264L was already observed as beneficial in AY.23 in Singapore and in BH.1 in the indian era of BA.2 heavily mutated lineages.

**Comment by oobb45729** [comment]
If my understanding of the paper is right, the residues 1264 and 1265 is important, guiding the spike protein to the "right" place for the virion assembly. The two types of pseudovirus virions in the paper assembly at the plasma membrane while the actual SARS-CoV-2 virions assembly at the ER-to-Golgi intermediate compartment. Comparing to WT, the V1264L variant does a better job guiding the spike protein to the "right" place, facilitating the assembly of SARS-CoV-2 virions but not pseudovirus virions.
