### ISSUE TITLE
CH.1.1.11 with Orf1a:D983G mainly in Hong Kong (100% of CH.1.1.11 seqs in Hong Kong, 108 seqs, 6 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1697]
Sub-lineage of :CH.1.1.11
Earliest sequence: 2022.10.26(Japan) EPI_ISL_15774176
Most Recent sequence: 2023.2.17 (Singapore) EPI_ISL_17016323

GISAID query:  Spike_R346T, Spike_F486S,Spike_K444T,Spike_L452R, G3791A,A3213G
No. of seqs: 80 (58 Hong Kong, 1 USA, 1 Taiwan(import from Thailand), 4 Singapore(local cases), 15 Japan, 1 Italy )

Mutations on top of CH.1.1.11: A3213G(Orf1a:D983G)

58/58(100%) of the Hong Kong CH.1.1.11 seqs have orf1a:D983G.

<img width="1239" alt="Screen Shot 2023-02-25 at 17 06 49" src="https://user-images.githubusercontent.com/10445944/221348764-567d0302-c2c1-44dc-92a9-ad12c95a9b8b.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_aa2d_9cf290.json?c=gt-ORF1ab_983

Genomes:

EPI_ISL_15774176, EPI_ISL_15894899, EPI_ISL_15894919,
EPI_ISL_16000281, EPI_ISL_16026795-16026796, EPI_ISL_16026804,
EPI_ISL_16026829, EPI_ISL_16026838-16026839, EPI_ISL_16026850,
EPI_ISL_16026891, EPI_ISL_16026897, EPI_ISL_16026899,
EPI_ISL_16039792, EPI_ISL_16073402, EPI_ISL_16077182,
EPI_ISL_16173620, EPI_ISL_16173623, EPI_ISL_16173626,
EPI_ISL_16287337, EPI_ISL_16376634-16376635, EPI_ISL_16376637,
EPI_ISL_16376639-16376640, EPI_ISL_16376645, EPI_ISL_16376648-16376649,
EPI_ISL_16376653-16376654, EPI_ISL_16376656-16376657, EPI_ISL_16376659,
EPI_ISL_16376662, EPI_ISL_16376664, EPI_ISL_16376668,
EPI_ISL_16376670, EPI_ISL_16376674, EPI_ISL_16376688,
EPI_ISL_16376692, EPI_ISL_16376747, EPI_ISL_16426939,
EPI_ISL_16427787, EPI_ISL_16431610, EPI_ISL_16524055,
EPI_ISL_16524061, EPI_ISL_16524066, EPI_ISL_16524077,
EPI_ISL_16524097, EPI_ISL_16524106, EPI_ISL_16524109,
EPI_ISL_16524125, EPI_ISL_16524130, EPI_ISL_16586822,
EPI_ISL_16670723, EPI_ISL_16717108, EPI_ISL_16717111,
EPI_ISL_16717121, EPI_ISL_16717131, EPI_ISL_16717133,
EPI_ISL_16717137, EPI_ISL_16717139, EPI_ISL_16717142,
EPI_ISL_16717145, EPI_ISL_16806546, EPI_ISL_16807760,
EPI_ISL_16899507, EPI_ISL_16902506, EPI_ISL_16902513,
EPI_ISL_16902525, EPI_ISL_16902561, EPI_ISL_16902565,
EPI_ISL_16902567, EPI_ISL_16948684, EPI_ISL_16951814,
EPI_ISL_17014683, EPI_ISL_17016300, EPI_ISL_17016322-17016323,

**Comment by aviczhl2** [comment]
97 seqs now.

**Comment by aviczhl2** [comment]
108 seqs now, detected in USA

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. Although, this has constituted 100% of CH.1.1.11 sequences from Hong Kong, the clade has shown few new detections over the past month, and is showing a relative growth disadvantage relative to its parent over the past month. Consequently, this can be closed for now, but please request re-opening should this clade show marked growth in other countries or other signs of epidemiological interest.
