### ISSUE TITLE
New lineage proposal for B.1.1.316 with 3 additional spike mutations

### ISSUE THREAD

**Issue by erikalmecdc** [cov-lineages/pango-designation#17]
New lineage proposal
by Erik Alm

Lineage present in many countries, reported in media by Japan. These are currently assigned as B.1.316 but has many additional mutations including Spike E484K, G769V, W152L. The B.1.316 seems to be an old Canadian lineage (notice the time gap in the attached epicurve from cov-lineages.org), these new sequences are totally distinct from the old B.1.316
![New lineage in B-1-316 time](https://user-images.githubusercontent.com/36880285/108511175-d141c300-72bf-11eb-8d14-bc834a1c3051.PNG)
.

Sub-lineage of: B.1.316
Earliest sequence: 2020-11
Most recent sequence: 2021-02-11
Countries circulating: Ghana, Nigeria, Japan, UAE, Belgium, France, Netherlands, Switzerland, UK, Canada, USA, Australia

Evidence
83 viruses
![New lineage in B-1-316](https://user-images.githubusercontent.com/36880285/108510554-f6820180-72be-11eb-8b07-c33fa6b84a41.PNG)
[new.lineage in B-1-316.txt](https://github.com/cov-lineages/pango-designation/files/6010297/new.lineage.in.B-1-316.txt)

**Comment by rambaut** [comment]
There was a mix up with one of the training sets, this wider lineage is B.1.1.316:
https://github.com/cov-lineages/pango-designation/issues/14

Thus this sub lineage will likely be R.1 - will confirm this shortly.

**Comment by rambaut** [comment]
B.1.1.316 has 3 unusual sub-lineages:
![B 1 1 316 ml tree](https://user-images.githubusercontent.com/686405/108613764-d2244300-73ec-11eb-8ff9-5de27fe40749.png)

The largest, in blue, has the following 'defining' SNPs:
```
ORF1ab:
C14340T
		G5763R
C18877T
A19169G
		P6337H

spike:	W152L
		E484K
		G769V
		
M:		F28L
		
N:		S187L
		Q418H		
```

This will be lineage `R.1` as an alias for `B.1.1.316.1`

**Comment by rambaut** [comment]
Reopening until added to Pangolin

**Comment by aineniamh** [comment]
R.1 tagged in release [1.0.7](https://github.com/cov-lineages/pango-designation/releases/tag/v1.0.7). Thanks @erikalmecdc!

**Comment by shay671** [comment]
HI @rambaut
Could you please specify the defining mutations of B.1.1316 ?
The only mutation i seem to find in common for R.1 and samples that are B.1.1.316 in GISAID is t19839c  which seems to be much broader than B.1.1.316

**Comment by theosanderson** [comment]
Happened to also be looking at this lineage and came to the same conclusion as @shay671 - it doesn't seem obvious that this should be a sublineage of B.1.1.316
