### ISSUE TITLE
A probable sublineage of B.1.617.2 (Delta) circulating in Israel with Spike_T791I

### ISSUE THREAD

**Issue by banijolly** [cov-lineages/pango-designation#170]
**Description**
Sub-lineage of: B.1.617.2
Earliest sequence: 2020-12-16 (hCoV-19/USA/UT-UPHL-210729652440/2020)
Most recent sequence: 2021-08-02 (hCoV-19/Belgium/ULG-17571/2021)

B.1.617.2+Spike_T791I genomes are there in 19 other countries apart from Israel going by GISAID data, including USA, UK, Denmark, Belgium, India and Spain. The Israel sequences have been samples in June and July 2021, and the proportions appeared to reach 4% (source-outbreak.info).

![image](https://user-images.githubusercontent.com/47384613/128593813-f56068f7-69c8-4fd1-8714-1e6b6bb96179.png)

Here's an Usher sub-tree with all B.1.617.2 sequences from Israel:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_39437_e44b40.json

![image](https://user-images.githubusercontent.com/47384613/128594238-dd2f9649-ccad-4dea-b536-393978db9d61.png)

Genomes with T791I in the Israel Delta cluster:
![image](https://user-images.githubusercontent.com/47384613/128594351-ac4ee1ef-9cd9-40dc-b79f-b0d4a50f9085.png)

A list of all sequences from Israel that match the description: [Accession_IDs.txt](https://github.com/cov-lineages/pango-designation/files/6948835/Accession_IDs.txt)

**Comment by shay671** [comment]
Hi @banijolly  
The Israeli cluster you mentioned has other mutations defining it. For instance ORF3a:P42S 

Here is the Outbrek.info report for the prevalence of this dual mutation add to B.1.617.2

![image](https://user-images.githubusercontent.com/80166370/128636752-6ce65e8e-e9ca-4c1f-8675-18834700c0cc.png)

So, it does seems that it is a sub clade that has some prevalence in Israel, But it seems to be extremely specific to israel.

**Comment by chrisruis** [comment]
Thanks @banijolly. We've added this as AY.12 in [v1.2.56](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.56) and started it on the branch where C23934T occurs to coincide with the start of the Israel clade

**Comment by chrisruis** [comment]
AY.12 has now been renamed AY.122.1 as it clusters within the newly designated AY.122 lineage (designated in #320). The AY.12 label has therefore been withdrawn and the sequences from this clade updated to AY.122.1
