### ISSUE TITLE
Newly emerged DY.2 with S:G446S in Hubei (6 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1701]
Sub-lineage of :DY.2
Earliest sequence: 2023.2.14(Hubei) EPI_ISL_17031990
Most Recent sequence: 2023.2.17 (Hubei) EPI_ISL_17032028

GISAID query: T17208C,C2710T,C8626T,C28994A,G3259T, Spike_G446S
No. of seqs: 4 

Genomes:
EPI_ISL_17031990, EPI_ISL_17032025, EPI_ISL_17032027-17032028

Mutations on top of DY.2: G3259T(Orf1a:Q998H), C6543T(Orf1a:T2093I), C14676T, C14973T, C18501T, G22898A(S:G446S)

This lineage appears to be 4/14(29%) of the Hubei DY.2 seqs in 2023.2, or 4/50(8%) in total Hubei 2023.2 sequences.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36b9f_d6c1f0.json?branchLabel=Spike%20mutations&c=gt-S_446&showBranchLabels=all)

<img width="1247" alt="Screen Shot 2023-02-28 at 11 15 18" src="https://user-images.githubusercontent.com/10445944/221745382-a5ba16d5-d533-4c1c-a23d-65ebaf9dc77f.png">

A branch of DY.2 with orf1a:Q998H emerged in Hubei in late November, and in February it further picks a level-up mutation S:G446S.

**Comment by Mild1-ai** [comment]
Hello, DY. 2 and S: G446S have seven sequences, which are from Heilongjiang, Hubei, Xinjiang, Shanxi and Guangdong. (March 12, 2023)

**Comment by aviczhl2** [comment]
6 seqs now.

**Comment by corneliusroemer** [comment]
As long as it's a single province it's not worth designating due to being potentially just a small cluster.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there has been very little apparent growth of this clade since first detection, this can be closed for now. Please re-propose or request re-opening should this clade show future strong growth and wide geographical spread.
