### ISSUE TITLE
Mini saltation of XBL with S:Y453H (16 seqs as of 2023-03-30, Singapore)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1702]
First spotted by @ryhisner. Many thanks!

### Description
**Sublineage of**: XBL
**Earliest sequence**: 2023/02/04 (Singapore)
**Most recent sequence**: 2023/02/19 (Singapore)
**Countries circulating**: Singapore, all local cases
**Mutations on top of XBL**: C3961T, G4255A, C9286T, A11608G, T22919C (S:Y453H), C24937T
**GISAID and Cov-spectrum query**: C3961T, C9286T, A11608G, C24937T

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/221746013-5b182ef5-062e-416b-b052-f06eafa5e6d7.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18af2_d73490.json?c=gt-nuc_3961&label=id:node_7648988

### Genomes:
EPI_ISL_16899444, EPI_ISL_16905241, EPI_ISL_16905260, EPI_ISL_16905277, EPI_ISL_16975244, EPI_ISL_17016285, EPI_ISL_17016396

**Comment by FedeGueli** [comment]
XBL is one of the 5 fastest growing lineages, restricting some analysis it could me the fastest, even if i dont know if there coupd be a cluster sequencing bias in Singapore.
Given the rbd mutation i suggest to designate this soon to easily track it.

**Comment by c19850727** [comment]
one more sequence from Brunei.

**Comment by FedeGueli** [comment]
12 sequences as today

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As this has been showing negative growth relative to its parent across Asia and in Singapore itself over the past three months, this can be closed at the moment. It has also shown very few recent detections. Nevertheless, please re-propose or request re-opening should this lineage show clear signs of relative growth in the future.
