### ISSUE TITLE
Potential XBB.1 (or XBB.1.5?) sublineage with S:Y200C (A22161G), S:F486P(T23018C) and Orf9b:I5T(T28297C) (85seqs)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1704]
Defining mutations (used in GISAID query): XBB.1>T28297C>T23018C(S:F486P)>A22161G(S:Y200C) 

GISAID query: T28297C, T23018C, T23019C, A22161G
Earliest seq: 2023-01-12 (USA, EPI_ISL_16729101)
Most recent seq: 2023-02-21 (China, EPI_ISL_17039588)
Countries detected: UK (7), Australia (3), France (3), USA (2), Israel (2), Singapore (1), Malaysia (1), South Africa (1), Canada (1), China (1)

Usher tree: ("F486L" is F486P actually)
 
![QQ截图20230228200454](https://user-images.githubusercontent.com/121703496/221849857-4d4031da-3f5d-4518-b954-6b3557c37074.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_11f55_da65a0.json

Description:
I note the potential sublineage due to the sequence in Anhui, China updated today. I confuse it should be the potential sublineage of XBB.1 or XBB.1.5. The definition in Usher seems that XBB.1.5 should be XBB.1+S:F486P+T17124C ("original definition"), and my proposal genomes (without T17124C) are also preliminary classified as XBB.1 in Usher tree. 

However, my proposal genomes are only half of the branch in Usher tree. The rest of sequences are also XBB.1 in Usher, but classified as BA.2 in Pango Lineage (Hence my GISAID query genomes excludes them).   

The whole Usher tree has 3 branches with S:F486P (T23018C). The first branch are mainly XBB.1+S:F486P with T17124C, which is "original XBB.1.5"(blue box). The second branch in top are XBB.1+S:F486P with ORF1a:G1819S & ORF1a:T4175I(definition of XBB.1.9), which is XBB.1.9.1* (red box). The last one is XBB.1+S:F486P with T28297C (without two ORF1ab mutations in XBB.1.9) with 49 seqs in Usher(orange box), and almost of them (45 seqs) further gets A22161G (S:Y200C)).  

![Proposal](https://user-images.githubusercontent.com/121703496/221850368-abc4cfa7-8390-46b3-9dd3-54cf2483bac8.png)

Finally, I decied to propose the potential sublineage of XBB.1, defining with T28297C, then T23018C(S:F486P) finally A22161G (S:Y200C). if the definition of XBB.1.5 is expanded, it could be a sublineage of XBB.1.5.

Genomes:
EPI_ISL_16729101, EPI_ISL_16755906, EPI_ISL_16867223, EPI_ISL_16905245, EPI_ISL_16911728, EPI_ISL_16911818, EPI_ISL_16924796, EPI_ISL_16947582, EPI_ISL_16978121, EPI_ISL_16990132, EPI_ISL_16996132, EPI_ISL_16996211,
EPI_ISL_16996542, EPI_ISL_17007979, EPI_ISL_17008216, EPI_ISL_17008219, EPI_ISL_17026661, EPI_ISL_17026814,
EPI_ISL_17029474, EPI_ISL_17029509, EPI_ISL_17029524, EPI_ISL_17039588

**Comment by aviczhl2** [comment]
This is growing quite fast. Given its wide range prevalence in many under-sampled countries.

[growth advantage vs XBB.1*](https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?nextcladePangoLineage=XBB.1*&nucMutations1=T28297C%2CT23018C%2CT23019C%2CA22161G&nextcladePangoLineage1=XBB.1*&analysisMode=CompareToBaseline&)

Just in an hour it gets 2 more seqs from UK, 24 now.

**Comment by FedeGueli** [comment]
@HynnSpylor didnt you notice that T28297C is ORF9b:I5T ??

So it is in the same branch of XBB.1.9* and it is convergent with XBB.1.16

Now it counts 48 on Usher

New Usher tree ( it expires if not updated. but if you look for @babarelephant you will dicover a trick to keep it foprever @ryhisner maybe has it already at hand) :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_789e_eb7ab0.json?c=country&label=id:node_7765545

<img width="1158" alt="Schermata 2023-03-13 alle 06 54 08" src="https://user-images.githubusercontent.com/87669813/224618954-a21e49e1-090b-4a4d-a310-07f9a87078d0.png">

<img width="1168" alt="Schermata 2023-03-13 alle 06 55 12" src="https://user-images.githubusercontent.com/87669813/224619089-45ce3780-9daa-4e41-88bc-bbf2ddcca798.png">


@thomasppeacock @corneliusroemer @AngieHinrichs @InfrPopGen i suggest to designate it also to be able to distinguish it from the fastest XBB.1.9s and XBB.1.16, (Now it is assigned by nextclade to XBB.1.5 and by USher to XBB.1)

**Comment by HynnSpylor** [comment]
@FedeGueli This issue proposed earlier than #1723. Nextstrain did not show the T28297C induces ORF9b:I5T hence I ignored it.
Thanks a lot for the Usher tree advice. 
![QQ截图20230313151851](https://user-images.githubusercontent.com/121703496/224635715-062f9402-97e5-48ae-bee4-c3a5f9803a7c.png)

By the way, I suggest the #1712 should also be noticed since the higher growth rate (despite slightly lower than XBB.1.16)

**Comment by FedeGueli** [comment]
Thx @HynnSpylor i commented #1712 it looks like it has high prevalence in Africa! It should be deisgnated immediately.
Remember to highlight always if a lineage has high prevalence somewhere, it counts a lot. Thx for spotting.

About orf9b: it is never shown on Usher/nextstrain cause it overlaps N (same reason why you cant see orf9b mutations associated on CovSpectrum) my advice it is always to check on Covspectrum if some Orf9b mutation is present and then trying to associate it with a nuc , you should have memorized ba.5.2 orf9b:D16G as A28330G so you can get where to look for)

**Comment by FedeGueli** [comment]
55 sequences as today on Gisaid with 4 uploads from Indonesia today and 5 from England yesterday

**Comment by FedeGueli** [comment]
73 sequences as today last sequences from Italy India Australia Israel

**Comment by FedeGueli** [comment]
85 sequences as today. interestingly it seems spreading in South Africa too.
Most recent sequences from France.
Not very clear to me where this has emerged. 
To me this and the other with S:D215H should be designated as soon as possible to get the global picture. Now India increased it sequencing intensity and this could create a bias toward XBB.1.16 where likely other lineages are not that far from it.

**Comment by aviczhl2** [comment]
> Thx @HynnSpylor i commented #1712 it looks like it has high prevalence in Africa! It should be deisgnated immediately. Remember to highlight always if a lineage has high prevalence somewhere, it counts a lot. Thx for spotting.
> 
> About orf9b: it is never shown on Usher/nextstrain cause it overlaps N (same reason why you cant see orf9b mutations associated to a specific NUC on CovSpectrum) my advice it is always to check on Covspectrum if some Orf9b mutation is present and then trying to associate it with a nuc , you should have memorized ba.5.2 orf9b:D16G as A28330G so you can get where to look for)

Maybe I'm silly but I wanna know is there a easy way to link nuc mutation with orf9b mutations? It seems that we cannot read orf9b on GISAID too. 
I

**Comment by FedeGueli** [comment]
@aviczhl2 personally everytime i found any nuc mutation between 28100-29000 then i check it on covspectrum

**Comment by MCB6** [comment]
After yesterday's uploads it appears that XBB.1.22 suddenly took off in some US locations, approaching 15% in Rochester and 5% in Houston.
Is it some artifact of GISAID's analysis pipeline or a real change within the strain? I see that there's a new proposal for a potentially fast growing offshoot of XBB.1.22 today... https://github.com/cov-lineages/pango-designation/issues/1940
