### ISSUE TITLE
XBB.1.9.1 sublineage acquired Orf9b:P17L mutation - 195 sequences emerged in Malaysia  and seems growing in South Korea

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1709]
Similarly as BA.5 that soon after emergence acquired Orf9b:D16G i spotted a main branch of XBB.1.9.1 stemming out from the root with a mutation in Orf9b:P17L, a residue very close to the BA.5.2 defining , indeed i propose it immediately.

**Defining mutations**:
XBB.1.9.1  > C28333T  (**Orf9b:P17L**)

**Tree**:
<img width="1172" alt="Schermata 2023-02-28 alle 22 17 43" src="https://user-images.githubusercontent.com/87669813/221982223-e609c938-6479-4886-adfe-bf0e76f9cde3.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39f52_e6ea90.json?label=id:node_7639666

**Countries**: already widely spread likely it emerged in Malaysia (1st sequence : EPI_ISL_16504742 06-01-23)
then acquired a further mutation T3898C and went international very fastly
<img width="290" alt="Schermata 2023-02-28 alle 22 20 21" src="https://user-images.githubusercontent.com/87669813/221982740-e3c0cc57-ef0e-4634-876e-40b361284239.png">

**Gisaid Query**: C28333T  ,G5720A, T28297C,C12789T,T23018C

**Sequences:** 36

EPI_ISL_16647922, EPI_ISL_16744371, EPI_ISL_16754328,
EPI_ISL_16811067-16811068, EPI_ISL_16817158, EPI_ISL_16831653,
EPI_ISL_16881450, EPI_ISL_16881464, EPI_ISL_16881470,
EPI_ISL_16883828, EPI_ISL_16883893, EPI_ISL_16884774,
EPI_ISL_16885096, EPI_ISL_16886410, EPI_ISL_16913058,
EPI_ISL_16917034, EPI_ISL_16926013, EPI_ISL_16926044,
EPI_ISL_16947341, EPI_ISL_16953269, EPI_ISL_16979725,
EPI_ISL_16998542-16998543, EPI_ISL_17007343, EPI_ISL_17008885,
EPI_ISL_17013992, EPI_ISL_17016966, EPI_ISL_17026636,
EPI_ISL_17026700, EPI_ISL_17026789, EPI_ISL_17026810,
EPI_ISL_17026871, EPI_ISL_17036174, EPI_ISL_17036216,
EPI_ISL_17045802

**Comment by FedeGueli** [comment]
42 as today.

**Comment by FedeGueli** [comment]
47 sequences as todaty. Last uploads from England Austria Malaysia and Bahrain

**Comment by FedeGueli** [comment]
52 as today last samples from Brunei Germany and England

**Comment by FedeGueli** [comment]
69 samples. Most of the last samples. came from South Korea (local cases)

**Comment by FedeGueli** [comment]
123 sequences as today. last samples from Iceland, France, Scotland, Germany and Singapore

**Comment by FedeGueli** [comment]
153 as today. some sign of growth advantage just in south korea: https://cov-spectrum.org/explore/South%20Korea/AllSamples/Past3M/variants?nextcladePangoLineage=XBB.1.9.1*&nucMutations1=C28333T%2CG5720A%2CT28297C%2CC12789T%2CT23018C&analysisMode=CompareToBaseline&

**Comment by ryhisner** [comment]
Two related sequences in this lineage—one from Spain and one from South Korea—have picked up two additional ORF9b mutations: R32H and A57V. (They also share ORF1a:V60I.) Collection dates are March 16 and March 17. This gives these sequences five total ORF9b AA substitutions compared to wild-type: I5T, P10S, P17L, R32H, and A57V. 
EPI_ISL_17321642, EPI_ISL_17414954

ORF9b:R32H and A57V were also found together in five Delta sequences in December 2021 in the US—three in my state of Indiana, one in Ohio, and one in New York.
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/33738461/230727427-24435ac4-3ed3-47be-9c8a-1b0c7d4c92e2.png">

**Comment by FedeGueli** [comment]
Thx @ryhisner !

**Comment by FedeGueli** [comment]
176 seqs

**Comment by aviczhl2** [comment]
180 seqs , 4 additional are from Russia China Israel and Malaysia.

**Comment by corneliusroemer** [comment]
Too small at this point compared to other XBB.1.9.1 lineages
