### ISSUE TITLE
XBB.1.5 sublineage with S:N540K emerged in Austria (107 Seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1710]
Here i want to propose another sublineage of XBB.1.5 defined by a spike mutation, that was quite rare until emerged in XBB.1.5: S:N540K.

Defining mutations:
XBB.1.5> C4234T>A16953C>A16281G,S:N540K (T23182A)

Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_19589_f41270.json?branchLabel=nuc%20mutations

Gisaid query : Spike_V445P,Spike_N540K

Country : Austria
Sequences: 42
EPI_ISL_16831782, EPI_ISL_16831803, EPI_ISL_16831945-16831946,
EPI_ISL_16857520, EPI_ISL_16858215, EPI_ISL_16858273,
EPI_ISL_16858314, EPI_ISL_16858331, EPI_ISL_16858334,
EPI_ISL_16874291, EPI_ISL_16875359, EPI_ISL_16907906,
EPI_ISL_16907920, EPI_ISL_16908039, EPI_ISL_16908133,
EPI_ISL_16942282, EPI_ISL_16942943, EPI_ISL_16943130,
EPI_ISL_16951420, EPI_ISL_16951428, EPI_ISL_16951601,
EPI_ISL_16951626, EPI_ISL_16951647, EPI_ISL_16951649,
EPI_ISL_16951672, EPI_ISL_17002255, EPI_ISL_17010622,
EPI_ISL_17011709, EPI_ISL_17011732, EPI_ISL_17017720-17017721,
EPI_ISL_17017751, EPI_ISL_17017775-17017776, EPI_ISL_17017790,
EPI_ISL_17017823, EPI_ISL_17017907, EPI_ISL_17018007,
EPI_ISL_17018053, EPI_ISL_17018119, EPI_ISL_17034033,

**Comment by FedeGueli** [comment]
47 seqeunces as today all from Austria

**Comment by FedeGueli** [comment]
77 sequences as today. all from Austria.
41 of them are from Carinthia .

**Comment by FedeGueli** [comment]
87 sequences . Still an austrian only lineage

**Comment by FedeGueli** [comment]
107 seqs as today

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it has been showing relative growth disadvantages over the past three months (Austria, Europe, World), this can be closed for now. Please re-propose or request re-opening should this lineage show a marked resurgence.
