### ISSUE TITLE
Potential XBB.1 sublineage with ORF1ab:L469F (C1670T), S:D215H (G22205C) and S:F486P(T23018C) (189seqs)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1712]
Defining mutations: XBB.1>ORF8: G8* (G27915T)> ORF1ab: L469F (C1670T)> S:D215H (G22205C)> S:F486P (T23018C)

GISAID query: C1670T, G22205C, T23018C
Earliest seq: 2023-01-05 (Belgium, EPI_ISL_16751684)
Most recent seq: 2023-02-21 (USA, EPI_ISL_17036376)
Countries detected: USA (9), France (8), Germany (6), UK (4), Italy (4), Australia (2), Belgium (2), Canada (2), Israel (1), Cote d'Ivoire (1), Denmark (1), Netherland (1), Nigeria (1).  

Usher tree: ("F486L" is F486P actually)
![QQ截图20230302005905](https://user-images.githubusercontent.com/121703496/222209512-eb46289c-cf82-4259-80ae-af5a0a13e839.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16b31_f4e330.json

Description:
Another potential sublineage of XBB.1+S: F486P but without T17124C (original definition of XBB.1.5) like #1704. My proposal genomes are also preliminary classified as XBB.1 in Usher tree.

The evolution is XBB.1>T27995C>G27915T(ORF8: G8*)>ORF1ab: L469F (C1670T)> S:D215H (G22205C)> S:F486P (T23018C), and almost of S:D215H samples further get S:F486P. S: D215H, which has been observed in XBC.1, may increase fitness notably by Bloom calculator (https://jbloomlab.github.io/SARS2-mut-fitness/S.html)
![QQ截图20230302005446](https://user-images.githubusercontent.com/121703496/222209790-e1d2615f-c699-4ae4-9baa-df1af3bdd10b.png)

Finally, I decied to propose the potential sublineage of XBB.1, defining with ORF1ab: L469F, then S: D215H (A22161G), T23018C (S:F486P). If the definition of XBB.1.5 is expanded, it could be a sublineage of XBB.1.5. 

Growth rate (relative to XBB.1*+S: F486P): T17124T to exclude the "original XBB.1.5". Note that the samples may be not adequate now.
  
![QQ截图20230302011717](https://user-images.githubusercontent.com/121703496/222224688-9eeaeb6a-8339-4bbd-b8ff-5e6150d7cecb.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AF486P&nextcladePangoLineage=XBB.1*&aaMutations1=S%3AF486P%2CS%3AD215H&nucMutations1=T17124T&nextcladePangoLineage1=XBB.1*&analysisMode=CompareToBaseline&
Genomes:
EPI_ISL_16751684, EPI_ISL_16812411, EPI_ISL_16848885, EPI_ISL_16851107, EPI_ISL_16884066, EPI_ISL_16894720, EPI_ISL_16937857
EPI_ISL_16945292, EPI_ISL_16951757, EPI_ISL_16951776, EPI_ISL_16958399, EPI_ISL_16977032, EPI_ISL_16977036, EPI_ISL_16978132
EPI_ISL_16979751, EPI_ISL_16979754, EPI_ISL_16980719, EPI_ISL_16982326, EPI_ISL_16987720, EPI_ISL_16995984, EPI_ISL_16996931
EPI_ISL_16998081, EPI_ISL_17004156, EPI_ISL_17005456, EPI_ISL_17006146, EPI_ISL_17008091, EPI_ISL_17008206, EPI_ISL_17008942
EPI_ISL_17025221, EPI_ISL_17025282, EPI_ISL_17026244, EPI_ISL_17026274, EPI_ISL_17026336, EPI_ISL_17029925, EPI_ISL_17032320
EPI_ISL_17036227, EPI_ISL_17036376, EPI_ISL_17038849, EPI_ISL_17045894, EPI_ISL_17048614, EPI_ISL_17052797, EPI_ISL_17056944

**Comment by HynnSpylor** [comment]
53 seqs now

**Comment by HynnSpylor** [comment]
79 seqs now. it may be treated seriously.

**Comment by FedeGueli** [comment]
CC @AngieHinrichs @InfrPopGen @corneliusroemer @thomasppeacock 
I suggest a rapid designation of this one:
beyond the growth advantage comparable with top lineages circualating ([XBB.1.9.1](https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-01-09%26to%3D2023-03-13/variants?nextcladePangoLineage=XBB.1.9.1*&aaMutations1=s%3Af486P&nucMutations1=C1670T%2CG22205C%2CT23599G&analysisMode=CompareToBaseline&) and probably faster) this lineage seems to be highly prevalente in Africa:
It has been sampled from travellers from Mauritania, Kenya, Nigeria,
and directly uploaded to Gisaid by South Africa,  Nigeria and Cote D'Ivoire:
Especially in Cote d'Ivoire it represents 13 out of 20 sequences uploaded in 2023 representing 65% of prevalence.
<img width="1161" alt="Schermata 2023-03-13 alle 09 52 05" src="https://user-images.githubusercontent.com/87669813/224652224-89d3dc89-63fe-4f8d-8fea-a68604087a21.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3b98c_ee2cb0.json?c=country&label=id:node_7673727

Now it reached 134seqs

**Comment by FedeGueli** [comment]
Now this reached 173!!

Big upload of this lineage today mostly from France and Cote D'ivoire where it is 24/38 of samples in 2023,
but also England and Usa.

@thomasppeacock @corneliusroemer @InfrPopGen @AngieHinrichs i suggest to urgently designate it.

**Comment by FedeGueli** [comment]
189 sequences as today last sequences from Finland, Japan

**Comment by FedeGueli** [comment]
205 sequences as today, last sequences coming in from France, Scotland and Netherlands. Its last doubling ( estimated according to @corneliusroemer alternative method) was in 6 days as XBB.1.16, but still its 10-100 , 20-200 seems slower, but the fact the reservoir of this lineage is likely Africa could impair the comparison.

**Comment by corneliusroemer** [comment]
The major question here is: do we think the non-486P branch that the 486P branch descends from is real, in other words, is this a bona fide homoplasy of 486P? It does look like it, but we should look into this properly.

If it is, then this should be designated as XBB.1.17 (non 486P) and XBB.1.17.1 (with 486P), akin to XBB.1.9(.1)

**Comment by FedeGueli** [comment]
Yes @corneliusroemer i think that should be the best choice.

**Comment by HynnSpylor** [comment]
In my proposal sublineage, few seqs indeed show the S:D215H+S:F486S+ORF1ab:L469F(C1670T) (Earliest seqs is 2022-12-10 in USA(OQ109892.1) and 2022-12-12 in France (EPI_ISL_16486763), note that they are earlier than S:F486P branch excluding the low-quality Burkina Faso sequence), more seqs without F486P could be artefact. 

Even so, the evolution process ought to be T27995C>ORF1ab:L469F(C1670T)>S:D215H(G22205C)>S:F486P(T23018C). "T27995C+C1670T only" branch once spread in Russia in Nov-Dec 2022. 

However, almost sequences with S:D215H further get S:F486P. So my view is XBB.1.17 could be the branch with F486P, then XBB.1.17.1 could be its largest branch with G20173A (ORF1ab:V6637I)?

![QQ截图20230319022625](https://user-images.githubusercontent.com/121703496/226127603-f0d79adb-115e-47d8-86dd-0d545c68037f.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20717_5f2850.json

**Comment by corneliusroemer** [comment]
Given how much of a growth advantage 486P seems to confer to XBB.1, it's quite reasonable that 486P evolved independently here - despite not overwhelming evidence that the non-486P branch really existed.

The alternative history could be that they all should have 486P, and that the lack of it in mostly Russian sequences is just dropout/artefact. 50 of the 70 non-486P are Russian from 2 labs, so that's not impossible, but also not super likely.

If these had been actual 486P, we would expect them to have spread more broadly outside of Russia. They don't seem to, so it's consistent with the lack of 486P being real.

It's quite possible the 486P mutation happened in Africa or that this was one of the places that got this lineage earliest - this lineage seems to be dominant in Cote d'Ivoire, and also observed in Nigeria, Burkina Faso and South Africa. It's also growing particularly in France, which makes sense given French historical connections.

I'll designate the 27995C > 1670T as XBB.1.17

And then starting from 22205C > 23018C as XBB.1.17.1

The Russian lineage will be XBB.1.17.2 (assuming XBB.1.17 is the next, otherwise it's 18 etc, haven't looked yet)
