### ISSUE TITLE
BQ.1.1 with additional spike K182E, P251L and G446R (46 seqs as of 2023-03-01), and its related recombinant (2 seqs as of 2023-03-01)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1713]
First spotted by @oliasdave . Many thanks!

### Description
**Sublineage of**: BQ.1.1 (sibling to BQ.1.1.38 on Usher). 
**Earliest sequence**: 2022/12/30 (UK-England)
**Most recent sequence**: 2023/02/18 (UK-England)
**Countries circulating**: UK (45/46), Ireland (1/46)
**Mutations on top of BQ.1.1**: C22314T **(S:P251L)** > A28834G > A22106G **(S:K182E)**, T23716C > G2281A > C8950T > G22898C **(S:G446R)**, T25959C
It's convergent to BQ.1.1.39 (#1385 ) in terms of spike changes, but should be unrelated.
**GISAID and Cov-spectrum query**: G2281A, C8950T, T25959C

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/222335627-08ce944d-d307-471a-805c-171ffc343fc2.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_bf4f_f72260.json?c=gt-nuc_22898&label=id:node_6017558

**Relative growth advantage**
With only 36 sequences available on Cov-spectrum, it has a growth advantage of ~70% over BQ.1.1 in last 2 months in the UK, and almost the same as XBB.1.5 (wide confidence interval)
![image](https://user-images.githubusercontent.com/86835836/222336351-2d2221ab-fab1-4b67-a73d-205bc58ca5fd.png)

![image](https://user-images.githubusercontent.com/86835836/222336220-a695f6d3-0c29-4c90-9e76-edfb08b9cbb8.png)

### Genomes:
EPI_ISL_16441667, EPI_ISL_16496148, EPI_ISL_16496508, EPI_ISL_16525084, EPI_ISL_16535976, EPI_ISL_16535995, EPI_ISL_16536059, EPI_ISL_16584034, EPI_ISL_16613017, EPI_ISL_16613064, EPI_ISL_16645503, EPI_ISL_16722034, EPI_ISL_16722057, EPI_ISL_16808821, EPI_ISL_16810360, EPI_ISL_16810397, EPI_ISL_16829143, EPI_ISL_16924910, EPI_ISL_16937825, EPI_ISL_16952259, EPI_ISL_16954876, EPI_ISL_16978780, EPI_ISL_16978875, EPI_ISL_16978903, EPI_ISL_16978918, EPI_ISL_16985742, EPI_ISL_16985812, EPI_ISL_17007852, EPI_ISL_17016502, EPI_ISL_17016548, EPI_ISL_17016592, EPI_ISL_17016595, EPI_ISL_17016626, EPI_ISL_17016636, EPI_ISL_17016727, EPI_ISL_17016739, EPI_ISL_17016790, EPI_ISL_17017225, EPI_ISL_17026965, EPI_ISL_17032412, EPI_ISL_17032447, EPI_ISL_17032457, EPI_ISL_17032462, EPI_ISL_17032645, EPI_ISL_17063145, EPI_ISL_17063443

**Comment by c19850727** [comment]
I am also to propose a recombinant related to #1713.

### Description
**Recombinant between**: XBB.1.5* and #1713
**Earliest sequence**: 2023/02/16 (UK-England)
**Most recent sequence**: 2023/02/16 (UK-England)
**Countries circulating**: UK-England (2/2)
**Potential breakpoint**: between NSP14 and spike NTD (19327-22305)
**Potential BQ.1.1 donor**: #1713
**Potential XBB.1.5 donor**: XBB.1.5 with C5055T, C5301T, C5812T.
**Mutation profile**:
![image](https://user-images.githubusercontent.com/86835836/222339019-d65476cc-53af-4c54-ba7a-6233ee1e4a84.png)
**GISAID and Cov-spectrum query**: C5055T, C5301T, C5812T, T25959C

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/222339501-57dfa1e2-2682-4a64-8e76-4d6ebd42a8e5.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_db88_311b0.json?c=gt-nuc_5055&label=id:node_7436070

### Genomes:
England/PHEC-YYERMZS/2023
England/PHEC-YYERMAW/2023
Not yet on GISAID though.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.1.71 with 26 newly designated sequences, and 0 updated. Defining mutations G22898C (S:G446R), T25959C (following GC8950T). It might be good to create a dedicated issue for the recombinant, so we can keep an eye on it (and then this issue can be closed).

**Comment by c19850727** [comment]
Thanks @InfrPopGen ! I'll close this issue and make a separate proposal for the recombinant.

**Comment by FedeGueli** [comment]
BQ.1.1.71 appears as today the fastest non recombinant sublineage on earth so in the group just back the leading lineages :
https://cov-spectrum.org/collections/24

**Comment by FedeGueli** [comment]
cc @corneliusroemer someone noticed that S:G446R is not shown on the nextclade tree.

**Comment by c19850727** [comment]
I double checked BQ.1.1.71 and found 46 out of 64 genomes currently on GISAID also have S:Y144del. And those 18 genomes without Y144del are all from one lab (PHEC).

**Comment by FedeGueli** [comment]
> I double checked BQ.1.1.71 and found 46 out of 64 genomes currently on GISAID also have S:Y144del. And those 18 genomes without Y144del are all from one lab (PHEC).

Oh yes @c19850727 sorry for not saying that before, when i checked Nextclade tree this lineage has as unique defining mutation S144del!

**Comment by FedeGueli** [comment]
3 english sequences of this one added further S:Y248H , that is a residue in which mutations are known to benefit a lot on BQ.1 . all sampled in March 23:EPI_ISL_17153501, EPI_ISL_17153506, EPI_ISL_17153712,
@c19850727 @thomasppeacock maybe worth flagging.

**Comment by c19850727** [comment]
Yes @FedeGueli I am also monitoring it. There are 9 with S:Y248H in total. Will propose it once it grows further.

**Comment by FedeGueli** [comment]
> Yes @FedeGueli I am also monitoring it. There are 9 with S:Y248H in total. Will propose it once it grows further.

Sorrry i dint read this msg! i ve proposed it : https://github.com/cov-lineages/pango-designation/issues/1739 i will edit it crediting you!
