### ISSUE TITLE
BQ.1.2.1 cluster in Taiwan with S:D253G and Orf1a:P1213L (21 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1714]
Sub-lineage of :BQ.1.2.1
Earliest sequence: 2023.1.13(Taiwan) EPI_ISL_17013593
Most Recent sequence: 2023.2.18 (Singapore) EPI_ISL_17016408

GISAID query: C3903T,A22320G,C17746T
No. of seqs: 8 (6 Taiwan, 1 Japan, 1 Singapore)

Mutations on top of BQ.1.2.1: C3903T(Orf1a:P1213L),A22320G(S:D253G),C17746T(ORF1b:P1427S). 

Note that Taiwan submits more imported cases than local cases, so have to filter them out when looking at local cases of Taiwan. 

And this lineage appears to be 5/11(45%) of Taiwan's 2023.2 total local cases. 

[usher, pos 4414 seems messy. ](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_39f03_4ee70.json?c=gt-ORF1ab_1213&label=id:node_5902368)

<img width="1408" alt="Screen Shot 2023-03-02 at 15 44 23" src="https://user-images.githubusercontent.com/10445944/222365771-f2eff8e8-52f7-4d1a-92ae-6e6c37f7bc4d.png">

Genomes:
EPI_ISL_16971665, EPI_ISL_16987142, EPI_ISL_16996284-16996287,
EPI_ISL_17013593, EPI_ISL_17016408

**Comment by AngieHinrichs** [comment]
> [usher, pos 4414 seems messy.](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_39f03_4ee70.json?c=gt-ORF1ab_1213&label=id:node_5902368)

Good eye @aviczhl2.  I see most BQ.1.2.1 genomes have A4414G but then there are several little twigs from Germany, Taiwan and Brazil with reversions on 4414.  So far it doesn't look like it's causing enough problems to lead to misassignments, but we can keep an eye on it.

**Comment by aviczhl2** [comment]
14 seqs now.

**Comment by aviczhl2** [comment]
21 seqs now, 2 South Korea, 1 South Korea (imported from Taiwan),  1 Japan(imported from Taiwan), 2 Taiwan, 1 USA

**Comment by corneliusroemer** [comment]
The 253G parent has been designated as FB.1

**Comment by Sinickle** [comment]
For some reason this is looking like possibly the BQ doing the best at holding onto survival. Not sure why though...

**Comment by FedeGueli** [comment]
> For some reason this is looking like possibly the BQ doing the best at holding onto survival. Not sure why though...
BQ.1.2 is doing better than BQ.1.1 likely  its more fusogenic properties allow this.
