### ISSUE TITLE
BQ.1.1.22 with S:G257S, S:S256P (121 seq, UK, USA, Germany)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1715]
Proposal for a sublineage of BQ.1.1.22
Earliest sequence: 13.12.2022 (UK)
Countries detected: UK, USA, Germany

Defining Mutations:
S:G257S
S:S256P
ORF8:P38S
ORF1ab:P361S

GISAID query: T22328C, G5008T, C1346T, C28005T, G22331A

This sublineage is apparently a recent subclade of the lineage proposed in #1492 (maybe worth reopening?) and was detected in the UK, USA and Germany so far.

![grafik](https://user-images.githubusercontent.com/102166254/222445275-589d08f2-0023-406b-8f68-68753af6f223.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2043e_a3230.json?c=gt-S_257

EPI_ISL_16442596, EPI_ISL_16547046, EPI_ISL_16586509,
EPI_ISL_16586908, EPI_ISL_16614952, EPI_ISL_16750020,
EPI_ISL_16829117, EPI_ISL_16829322, EPI_ISL_16856300,
EPI_ISL_16903763, EPI_ISL_16903765, EPI_ISL_16903783,
EPI_ISL_16924021, EPI_ISL_16924117, EPI_ISL_16952065,
EPI_ISL_16968936, EPI_ISL_16968951, EPI_ISL_16968955,
EPI_ISL_16968998, EPI_ISL_16969033, EPI_ISL_16969117,
EPI_ISL_16969137, EPI_ISL_16969174, EPI_ISL_16969227,
EPI_ISL_16969245, EPI_ISL_16978468, EPI_ISL_16978483,
EPI_ISL_16978492, EPI_ISL_16985671, EPI_ISL_16829522,
EPI_ISL_16866210, EPI_ISL_16866340, EPI_ISL_16903784, 
EPI_ISL_16903850, EPI_ISL_17007423, EPI_ISL_17007761, 
EPI_ISL_17007795, EPI_ISL_17007800-17007801, EPI_ISL_17007936,
EPI_ISL_17017226, EPI_ISL_17017337, EPI_ISL_17026938,
EPI_ISL_17027042, EPI_ISL_17032201, EPI_ISL_17032268, 
EPI_ISL_17032273-17032274, EPI_ISL_17032279, 
EPI_ISL_17032283, EPI_ISL_17032353, EPI_ISL_17032385,
EPI_ISL_17032582, EPI_ISL_17071989, EPI_ISL_17071991,
EPI_ISL_17072015

OQ301475.1, OX396843.1, OX405547.1, OX405662.1, OX405732.1, OX405907.1, OX406341.1, OX407949.1, OX408862.1, OX409229.1, OX409247.1, OX409253.1, OX409266.1, OX409333.1, OX413503.1, OX414021.1, OX415451.1, OX415577.1, OX415777.1, OX418321.1, OX420166.1, OX422613.1, OX422914.1, OX428394.1, OX428395.1, OX428537.1, OX428596.1, OX428611.1, OX430386.1, OX430613.1, OX433726.1, OX435487.1, OX428394.1, OX428395.1, OX428397.1, OX428537.1, OX428596.1, OX428611.1, OX430613.1, OX430763.1, OX437145.1, OX437181.1, OX437189.1, OX437191.1, OX437429.1, OX437543.1, OX437611.1, OX437891.1, OX437893.1, OX437903.1

**Comment by FedeGueli** [comment]
I just reopened the parental lineage issue. @agamedilab @InfrPopGen @corneliusroemer @AngieHinrichs

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage ER.1.1 with 0 newly designated sequences, and 69 updated from ER.1. Defining mutation G22331A (S:G257S) (following C28005T (ORF8:P38S)).
