### ISSUE TITLE
Very new Chinese cluster of XBB.1.5 (4 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1717]
Sequences: EPI_ISL_17072126-17072129, 2023.2.20(Jiangsu)
Query: G15380T,T15651C
Mutations on top of XBB.1.5:  G15380T(Orf1b:S638I),T15651C,T24397A

This cluster takes 4/79(5%) seqs in Jiangsu sampled from 2023.2.1, or 4/11(36%) seqs sampled after 2023.2.20.

<img width="1397" alt="Screen Shot 2023-03-02 at 23 37 35" src="https://user-images.githubusercontent.com/10445944/222519938-6f75bcaf-91b7-4077-af4d-1652046213a2.png">

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice8_genome_279ed_bed20.json?f_userOrOld=uploaded%20sample&label=id:node_9733501)

**Comment by HynnSpylor** [comment]
Ah, it consists with ChinaCDC weekly report (4 seqs in 2.18-2.23).  It is highly concentrated in Lianyungang City with clear cluster, maybe a single chain of transimission.
It is worth further monitoring.

**Comment by MCB6** [comment]
Ages / sexes of the patients do not look like a dormitory / school / hospital outbreak. Middle age adults and two children ages 4 and 5. 
The province started uploading a relatively small trickle of data in late January, but until know there were just 3 samples from Lianyungang. Then 12 more came today.

**Comment by Mild1-ai** [comment]
I found that Lianyungang reported five XBB.1.5 sequences, aged 4, 5, 48, 46 and 32. I think it deserves attention.

**Comment by aviczhl2** [comment]
> I found that Lianyungang reported five XBB.1.5 sequences, aged 4, 5, 48, 46 and 32. I think it deserves attention.

Yeah.Another one is on another branch, with orf1a:A3143V and S:L229F. 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice12_genome_279ed_bed30.json?f_userOrOld=uploaded%20sample)

**Comment by Mild1-ai** [comment]
I saw that Guangdong uploaded two XBB.1.5 sequences today, both from Zhanjiang City.They are 4 years old and 67 years old.

However, I do not know whether the two sequences reported by Guangdong are related to Jiangsu for the time being.

Based on the timing of the sequencing, I assume that XBB.1.5 has spread in China.

**Comment by HynnSpylor** [comment]
@Mild1-ai the 2 sequences are without G15380T, so they are independent.
However, XBB.1.5/XBB.1.9.1 (reported in Xining, Qinghai & Meishan, Sichuan) seqs in China are not in major cities and far apart. Maybe XBB.1.5&XBB.1.9.1 have indeed spread.

**Comment by corneliusroemer** [comment]
Can you link to the CDC report @HynnSpylor?

As long as it's just a single location and no diversity it's very much below the threshold of deserving designation. It may be notable as the potentially first reported non-singlet cluster of XBB.1.5 in China, but that doesn't mean it will end up as the predominant one. Let's wait and see.

**Comment by beansrowning** [comment]
Per [China CDC Report](https://www.chinacdc.cn/jkzt/crb/zl/szkb_11803/jszl_13141/202303/t20230304_264035.html) there should be 11 XBB.1.5 from Dec 1 - Mar 2, which include the 3 from December in Shanghai which were marked as imported. By my count there's still one left to be uploaded.

Without looking at them in a tree, multiple seeding seems equally likely given loosening of restrictions.

**Comment by Mild1-ai** [comment]
Thank you very much for your answers.

The immune background in China is BA.5 and does not appear to be immune to XBB.In my opinion, XBB is more likely to spread in China and deserves attention.

**Comment by aviczhl2** [comment]
> Per [China CDC Report](https://www.chinacdc.cn/jkzt/crb/zl/szkb_11803/jszl_13141/202303/t20230304_264035.html) there should be 11 XBB.1.5 from Dec 1 - Mar 2, which include the 3 from December in Shanghai which were marked as imported. By my count there's still one left to be uploaded.
> 
> Without looking at them in a tree, multiple seeding seems equally likely given loosening of restrictions.

The 11 doesn't include the 3 from Shanghai, as they're imported cases. 

However, we don't know how they category viruses, maybe some XBB+S:486P are mis-categorized as XBB.1.5 and count for that 11.

**Comment by Mild1-ai** [comment]
> I saw that Guangdong uploaded two XBB.1.5 sequences today, both from Zhanjiang City.They are 4 years old and 67 years old.
> 
> However, I do not know whether the two sequences reported by Guangdong are related to Jiangsu for the time being.
> 
> Based on the timing of the sequencing, I assume that XBB.1.5 has spread in China.

My query found that 17170852 is EM.1. I don't know whether it is a recognition error or it is true.

**Comment by FedeGueli** [comment]
while XBB.1.9.1 popped up in Wuhan today!

**Comment by Mild1-ai** [comment]
> while XBB.1.9.1 popped up in Wuhan today!

This is in line with the weekly report issued by the Chinese Center for Disease Control and Prevention, and the sequence of XBB will be uploaded in the next few days.

**Comment by HynnSpylor** [comment]
@corneliusroemer   China CDC updates every Saturday (https://weekly.chinacdc.cn/), but it does not show the specific distribution.
[ChinaCDCWeekly-20230311.pdf](https://github.com/cov-lineages/pango-designation/files/10948832/ChinaCDCWeekly-20230311.pdf)

Now the total of XBB.1,5* is 20 and XBB.1.9* is 4, but some sequences are not shown in GISAID (may update later).

----
Today GISAID updates 4 XBB.1+F486P from Hubei Province (2 in Yichang City, 1 in Wuhan City and 1 in Jingzhou City). 
Collection date between Feb 28 to Mar 5.

sample in Wuhan is assigned as XBB.1.9.1 by Usher, and sample in Jingzhou is typical XBB.1.5. 2 seqs of Yichang may be XBB.1*+F486P (without T17124C).

To this day, these sequences are independent in different cities, and most of them are not in major cities (only Beijing and Wuhan updated one for each). is the first major cities, and maybe there are certain amount of XBB.1.5/XBB.1.9.1

**Comment by aviczhl2** [comment]
> @corneliusroemer China CDC updates every Saturday (https://weekly.chinacdc.cn/), but it does not show the specific distribution. [ChinaCDCWeekly-20230311.pdf](https://github.com/cov-lineages/pango-designation/files/10948832/ChinaCDCWeekly-20230311.pdf)
> 
> Now the total of XBB.1.5* is 20 and XBB.1.9* is 4, but some sequences are not shown in GISAID (may update later).
> 
> Today GISAID updates 4 XBB.1+F486P from Hubei Province (2 in Yichang City, 1 in Wuhan City and 1 in Jingzhou City). Collection date between Feb 28 to Mar 5.
> 
> sample in Wuhan is assigned as XBB.1.9.1 by Usher, and sample in Jingzhou is typical XBB.1.5. 2 seqs of Yichang may be XBB.1*+F486P (without T17124C).
> 
> To this day, these sequences are independent in different cities, and most of them are not in major cities (only Beijing and Wuhan updated one for each). is the first major cities, and maybe there are certain amount of XBB.1.5/XBB.1.9.1

The Jingzhou and Wuhan ones are labeled imported cases, so only 2 local.

**Comment by corneliusroemer** [comment]
So far the Chinese XBB clusters are all still very small, definitely not big enough to warrant designation. We should wait until they are sizeable ~50-100.

**Comment by Mild1-ai** [comment]
> So far the Chinese XBB clusters are all still very small, definitely not big enough to warrant designation. We should wait until they are sizeable ~50-100.

Next, I will continue to track the XBB cluster in China, and we expect a certain XBB branch in China to be designated.Thank you.

**Comment by HynnSpylor** [comment]
Today Guangdong province updates 15 seqs of XBB.1*+S:F486P (185 total).

Usher shows 6 of these 15 seqs are in same branch of EM.1 (alias of XBB.1.5.7.1, defined as XBB.1.5.7+S:R214L) with ORF1ab: V5894L, and note that they are related with a Guangdong sequence updated in 2023-02-02.


![7BF82624-C2E2-44A4-B198-8C580F613E20](https://user-images.githubusercontent.com/121703496/226801538-580722bb-1759-4bd4-80f3-e140826a587e.png)
![9B61AE06-C68B-4A39-9F1D-0C16A64BA9EC](https://user-images.githubusercontent.com/121703496/226801543-0ee568db-8309-4fc6-a64e-5785eb26aeee.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4dd3_a7e600.json

**Comment by aviczhl2** [comment]
> Today Guangdong province updates 15 seqs of XBB.1*+S:F486P (185 total).
> 
> Usher shows 6 of these 15 seqs are in same branch of EM.1 (alias of XBB.1.5.7.1, defined as XBB.1.5.7+S:R214L) with ORF1ab: V5894L, and note that they are related with a Guangdong sequence updated in 2023-02-02.
> 
> ![7BF82624-C2E2-44A4-B198-8C580F613E20](https://user-images.githubusercontent.com/121703496/226801538-580722bb-1759-4bd4-80f3-e140826a587e.png) ![9B61AE06-C68B-4A39-9F1D-0C16A64BA9EC](https://user-images.githubusercontent.com/121703496/226801543-0ee568db-8309-4fc6-a64e-5785eb26aeee.png)
> 
> https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4dd3_a7e600.json

Yeah given the sequence density in China (Guangdong: 120m pop, 802 seqs in 2023, UK: 67m pop, 40268 seqs in 2023), maybe this 7 seqs mean more people infected than the other ~400 seqs of EM.1 mainly in UK.

**Comment by aviczhl2** [comment]
<img width="1406" alt="Screen Shot 2023-03-22 at 16 13 30" src="https://user-images.githubusercontent.com/10445944/226839984-4713748b-9450-4668-a972-728c2643da82.png">
It seems that all EM.1s are from ~100x-sequence-density countries compared to China.  It is very possible that China tops the actual infection of EM.1 in real world.

**Comment by FedeGueli** [comment]
@aviczhl2 i suggest you to make this issue an issue on multiple xbb.1.5 lineages spreading in China. 
Maybe you can update and sum findings editing the original post making a list: 1 lineage *** usher sequences etc

**Comment by InfrPopGen** [comment]
Thank for posting and tracking these lineages. As this is not a specific lineage proposal, and the original proposed cluster has shown negligible growth over the past month, this issue should be closed. Please start an issue on multiple xbb.1.5 lineages spreading in China, as suggested by @FedeGueli above, or/and propose any of those lineages that do show signs of epidemiological impact, as individual lineage proposal issues.
