### ISSUE TITLE
CH.1.1.17 + S:D215G, S:Q613H(228 sequences)

### ISSUE THREAD

**Issue by DoropFan** [cov-lineages/pango-designation#1718]
Description
Sub-lineage of:CH.1.1(BA.2.75.3.4.1.1.1.1)
Earliest sequence:2022-12-30(New Zealand)
Countries circulating:New Zealand10, United Kingdom6, Austria4, Germany4, Australia3, Netherlands2, Switzerland1, Denmark1, France1
Sequences:32

Nucleotide mutations:C11750T,C18657T,C21811T,A22206G,G23401T,A27156G,C29555T
Amino acid changes:ORF1a:L3829F, S:D215G, S:Q613H, M:S212G
[CovSpectrum](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AL3829F%2CS%3AD215G%2CS%3AQ613H%2CM%3AS212G)

[Genomes](https://lapis.cov-spectrum.org/gisaid/v1/sample/gisaid-epi-isl?dateFrom=2022-08-29&dateTo=2023-02-24&aaMutations=ORF1a%3AL3829F%2CS%3AD215G%2CS%3AQ613H%2CM%3AS212G&host=Human&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&orderBy=random)
![ch11s215gs613h](https://user-images.githubusercontent.com/118802079/222596759-62cd594d-7a19-4098-9f82-bbc405b31018.jpg)
![ch11s215gs613h2](https://user-images.githubusercontent.com/118802079/222596769-31175cf9-8dda-4bd6-850a-0b8d5132054c.jpg)

**Comment by aviczhl2** [comment]
> oh, this one also have the orf1a:L3829F
> 
> <img alt="Screen Shot 2023-03-07 at 02 32 00" width="1367" src="https://user-images.githubusercontent.com/10445944/223202005-22ecca90-c179-4fa9-a83f-62fc95c7d66a.png">
> 
> And it is quite fast even among the fastest XBB sublineages, which means much faster than CH.1.1 (baseline: S:F486P)

**Comment by hsnguyen** [comment]
More sequences from Australia.
GISAID query (Spike_Q613H, Spike_D215G, M_S212G) returned 66 seq. now

**Comment by hsnguyen** [comment]
I found that M_S212G is gone missing from a number of sequences within this clade due to ambiguous bases, so changed the GISAID query to (NSP6_L260F, NSP8_N118S, Spike_D215G,Spike_Q613H). This one returned 100 viruses as of 21 March.
where
NSP6_L260F = ORF1a_L3829F = C11750T
NSP8_N118S = ORF1a_N4060S = A12444G

If only searching by spike mutations of CH.1.1+ Spike_Q613H, Spike_D215G, it'll return even more seqs as about 40 Austrian partial sequences (>2Kbp spike sequencing?) would add up to the result.
I think this one deserves a name for itself, just not sure if it'd be a direct sub-lineage from CH.1.1 or something further down.
Cheers,

**Comment by corneliusroemer** [comment]
I designated the parent lineage as CH.1.1.17 so this should become easier to track https://github.com/cov-lineages/pango-designation/commit/3812bd7e26a4d6cf5433766139348cba7ea75588

**Comment by DoropFan** [comment]
New Zealand
![nz](https://user-images.githubusercontent.com/118802079/227390080-dd3674eb-2585-4a0b-a075-338d5ebb62e2.jpg)

**Comment by FedeGueli** [comment]
it is 300 and its prent is already the fastest non - XBB lineage. @corneliusroemer  @InfrPopGen i think it deserves a designation .:
<img width="1393" alt="Schermata 2023-03-31 alle 00 14 05" src="https://user-images.githubusercontent.com/87669813/228975706-184497a3-3bec-44bd-b5d9-66c15f33da0d.png">


And more it has already split in two:
One branch with C27804T
and the other with Orf1a:L384F
<img width="1158" alt="Schermata 2023-03-31 alle 00 17 12" src="https://user-images.githubusercontent.com/87669813/228976117-d1626711-8f94-4c7c-9c65-c571c7b842b8.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_988e_609d80.json?c=userOrOld&label=id:node_8110628

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage FK.1 with 70 newly designated sequences, and 89 updated from CH.1.1 (30) and CH.1.1.17 (59). Defining mutation A22206G (S:D215G) (following C11750T (ORF1a:L3829F), G23401T (S:Q613H)).
