### ISSUE TITLE
Another new B.1.X lineage associated with North America with Spike mutations T19I, H49Y, N450K and S477N

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#172]
**New proposed lineage
By Tom Peacock**

**Description**
**Sub-lineage of:** B.1
**Earliest Sequence:** 2021-01-16
**Latest Sequence:** 2021-06-18

**Countries circulating:** Mexico (33 genomes), USA (14 genomes)

**Description:
Conserved Spike mutations -** T19I, H49Y, N450K, S477N, D614G

**Conserved non-Spike mutations -** NSP6 – Y153C;   NSP12 – P323L; NSP13 – S100G;  M – A63T;   N – D81Y, G215V

Appears to be yet another variant lineage appearing out of North America - theres a little diversity in there as well (subsets have L452M, a ~140 region deletion, and/or D215G)

Genomes:
[B.1.X N450K S477N.txt](https://github.com/cov-lineages/pango-designation/files/6950931/B.1.X.N450K.S477N.txt)

Evidence:
![image](https://user-images.githubusercontent.com/79373149/128635196-eb05a58c-92f0-424e-8556-270405806b46.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_59dc8_fe7140.json?c=pango_lineage

Proposed lineage name: B.1.X

**Comment by shay671** [comment]
Isn't this B.1.635?

**Comment by thomasppeacock** [comment]
Oh yeah it absolutely is - thanks for flagging!

**Comment by shay671** [comment]
@thomasppeacock  
I did the same mistake : 
https://github.com/cov-lineages/pango-designation/issues/167
