### ISSUE TITLE
DV.1 with S:Q613H [343 sequences, United Kingdom Canada and Iceland]

### ISSUE THREAD

**Issue by Outpfmance** [cov-lineages/pango-designation#1720]
This is a very strange branch.
Q613H did not appear in the original DV.1, but the branch(DV.1 +Q613H)has grown rapidly over time. Now it has 244 sequences, and all of DV.1's sequences have 320. Since January 2023, Q613H has accounted for 76% of all DV.1 sequenced sequences.

https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-01-01%26to%3D2023-02-24/variants?aaMutations=s%3A613h&nextcladePangoLineage=DV.1

GISAID querty: Spike_L176F, Spike_N185D, Spike_K444T,Spike_Q613H ,-NSP12_Y273H

**Comment by HynnSpylor** [comment]
#1493 mentioned this sublineage but has been closed. the sublineage was stagnated in January, while increased again in February.
GISAID query should be: CH.1.1.1 +Spike_L176F, Spike_Q613H (since DV.1 are not available in GISAID?) ---356 sequences 

Usher tree added:
 
![QQ截图20230303234215](https://user-images.githubusercontent.com/121703496/222764588-f5ef4925-2eff-4464-9e68-d9f1a8313c29.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1eda1_2095e0.json

**Comment by Outpfmance** [comment]
@HynnSpylor OK I see. But the final name doesn't seem to count Q613H as a defining mutation for DV.1, so we should call this one(DV.1+Q613H)DV.1.1? @corneliusroemer

**Comment by Mydtlwn** [comment]
#1523 #1664 #1718

**Comment by FedeGueli** [comment]
Spike_L176F, Spike_N185D, Spike_K444T,Spike_Q613H ,-NSP12_Y273H

is the query for that sublineage of DV.1 .
Please dont self assign on your own in comments cause if something else will be designated with the same alias then searching back it in the issues could be tricky. So it is DV.1 + S:Q613H until designation.

**Comment by Outpfmance** [comment]
@Mydtlwn Yes. Q613H also appears on these word branches.
@FedeGueli Ok, I see. Now it has been corrected.

**Comment by Outpfmance** [comment]
249 sequences now

**Comment by Outpfmance** [comment]
270 sequences now. And its share has reached 74%.

**Comment by FedeGueli** [comment]
@Outpfmance the fact its share of DV.1 is so high could make designation redundant , de facto it is already DV.1. But still i suggest @InfrPopGen and @corneliusroemer to designate to keep better track of S:Q613H mutations. We have seen it emerging from several lineages but we cannot say how much it brought in for their overall fitness

**Comment by Outpfmance** [comment]
@FedeGueli Yes, I also think DV.1+Q613H should be called DV.1.1, because Q613H is a notable mutation

**Comment by Outpfmance** [comment]
319 sequences now. It’s share has reached 75.95%.

**Comment by Outpfmance** [comment]
340 sequences now.

**Comment by Outpfmance** [comment]
This time it only adds three sequences.
