### ISSUE TITLE
BQ.1.1.65 sublineage with S:Q52R (142 sequences, mostly Canada)

### ISSUE THREAD

**Issue by emily-smith1** [cov-lineages/pango-designation#1722]
### Description
**Sublineage of**: BQ.1.1.65
**Earliest sequence:** 2022-12-19 (USA-TX)
**Most recent sequence**: 2023-02-23 (Canada)
**Countries circulating:** USA, Canada, UK
**GISAID query:** Spike_Q52R, Spike_K147I, Spike_N460K
**Cov-spectrum query:** BQ.1.1.65, S:Q52R

### Evidence

This appears to be growing quickly in Canada. According to Cov-spectrum, BQ.1.1.65 + S:Q52R has a 22% growth advantage over XBB.1.5 for the last 3 months.  

![image](https://user-images.githubusercontent.com/84812104/222856766-23528a74-92cf-412c-a703-52e0af0e6017.png)

**UShER link**: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ebce_289470.json?label=id:node_6036314

![image](https://user-images.githubusercontent.com/84812104/222856775-d4275ff6-73a5-4753-8be8-cdfce45a8f4d.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage ES.1 with 62 newly designated sequences, and 44 updated. Defining mutation A21717G (S:Q52R) (following A22002T (S:K147I)).
