### ISSUE TITLE
 BA.1.18 with multiple Spike Mutations in France (8 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1724]
First sequence: EPI_ISL_16751977(France) 2022.12.28
Most Recent Sequence: EPI_ISL_17050958(France) 2023.2.5

GISAID query: Spike_T22I,Spike_E132Q,Spike_V987F
Genome:
EPI_ISL_16751721-16751722, EPI_ISL_16751789, EPI_ISL_16751791,
EPI_ISL_16751977, EPI_ISL_16868993, EPI_ISL_16869007,
EPI_ISL_17050958

Mutations on top of BA.1.18: 
C3486A, A7986G, G21956C, G24521T, C26029A, C11750T, C22664A, A5405G, G5572T, T6905G, T7322C, C12623T, A22964G, G25677T, G28209T, C21627T, G22599C, T5406C, G7252T, T22846C, A28612T, C24337T

S: T22I, R346T, I468V, E132Q,L368I,V987F
orf1a: I1714A, L2329F, M1769I, S2214A, Y2353H, P4120S, A1074D, Q2574R, L3829F
orf3a:L95F,Q213K
orf8:E106stop

<img width="1397" alt="Screen Shot 2023-03-04 at 12 37 00" src="https://user-images.githubusercontent.com/10445944/222875949-b427b454-8fcf-4e50-a179-9d515f471784.png">

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_44f6_2bef80.json?branchLabel=Spike%20mutations&c=gt-S_987&showBranchLabels=all)

**Comment by silcn** [comment]
Metadata suggests these are all from a single chronic patient. BA.1 would probably need many more RBD mutations than that for sustained transmission.

**Comment by aviczhl2** [comment]
> Metadata suggests these are all from a single chronic patient. BA.1 would probably need many more RBD mutations than that for sustained transmission.

Yeah it seems they are from same-aged male in metadata. Can you confirm those sequences are from the same person?

 I'll restart this when more than 1 people is  infected by this.
