### ISSUE TITLE
XBB.2.7 + S:T478Q and S:Y453F after Orf1a:E250D.  11 sequences India, England, Denmark, Singapore and Scotland

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1725]
I was routinely checking S:Y453F when i found this little sublineage  of XBB.2 with some further AA substitutions.

**Defining mutations**:
XBB.2  > > orf1a:R3662H (G11250A )> Orf1a:E250D (A1015C), C20316T > C12400T, S:Y453F (A22920T), S:T478Q (A22994C) >

**Usher tree:**
<img width="1149" alt="Schermata 2023-03-04 alle 18 06 45" src="https://user-images.githubusercontent.com/87669813/222919238-7e8c2442-77b2-468c-8adc-074fdddd419b.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_29bcb_36bf80.json?c=gt-S_453,478&label=id:node_7740829

**CovSpectrum** &**Gisaid Query**: Spike_T478Q,Spike_Y453F

**Sequences**: 7 ( First ones  from India Kerala and Karnataka, last from Denmark)
EPI_ISL_16737817, EPI_ISL_16847536, EPI_ISL_16847543,
EPI_ISL_16888187, EPI_ISL_17017523, EPI_ISL_17048560,
EPI_ISL_17048580

Composite fitness predicted by Nextclade is very high, as expected for increased binding by S:Y453F 

<img width="899" alt="Schermata 2023-03-04 alle 18 41 03" src="https://user-images.githubusercontent.com/87669813/222920725-874bff9e-388f-4e0e-9052-e7ba58aa1ca6.png">

**Comment by FedeGueli** [comment]
2 new sequences from Scotland uploaded today.

**Comment by ryhisner** [comment]
And both with the T-cell-escape mutation S:P272L.

**Comment by FedeGueli** [comment]
Thx @ryhisner didnt give a deep look at them, but luckily there are you!

**Comment by FedeGueli** [comment]
Sorry it was mistakenly closed by me

**Comment by corneliusroemer** [comment]
Yep, I've also noticed this one. Thanks for tracking. I think the best is to designate the parent polytomy for now while it's so slow. That helps tracking.

**Comment by FedeGueli** [comment]
11 sequences as today. it doesnt seem to compete with 486P stuff.

**Comment by corneliusroemer** [comment]
Designated the parent branch as XBB.2.7

**Comment by Mild1-ai** [comment]
He has already been named, so it should be closed. @FedeGueli
