### ISSUE TITLE
DY.2+S:K444T in Anhui(10 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1727]
Sequences: EPI_ISL_17088869,EPI_ISL_17088873-17088877,EPI_ISL_17088879-17088881 2023.3.3(Anhui)
GISAID query: T12142C,A22893C,C26408T

Mutations on Top of DY.2: T12142C,A22893C,C26408T (E:S55F, S:K444T)

9/16 of today's upload from Xuancheng, Anhui. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1c81a_454e40.json?f_userOrOld=uploaded%20sample&label=id:node_9756599)

<img width="1398" alt="Screen Shot 2023-03-05 at 16 49 19" src="https://user-images.githubusercontent.com/10445944/222950935-82d05b3f-187d-4e6d-93a2-5d1a48c7e704.png">

**Comment by AnonymousUserUse** [comment]
The delay between sample date and submission date of some sequences from China (especially from Anhui) is exceptionally small, e.g. there are only 2 days between sample date and submission date for sequences in this issue.
Do someone know whether the sample date shown in GISAID is true, or is that actually the date when the sequencing lab received the sample, or even the date when the lab finished the sequencing, among these sequences?

**Comment by aviczhl2** [comment]
10 seqs now.

**Comment by aviczhl2** [comment]
> This appears to still be at 10 sequences and on that basis should be closed. Nevertheless, there might be new sequences of this on Genbase. If so, please give an update, with a link to a Genbase search (assuming that Genbase allows searching by mutation as well as pango lineage). Unfortunately, any such sequences would be missing from Cov-spectrum too. Thank you.

Sorry there seems no way so search based on mutations on GenBase. However it seems that those sequences are submitted to GISAID again with a delay. 

This one is still at 10 seqs, so I'll close this issue. Thanks for the reminder.
