### ISSUE TITLE
Lineages with orf1a:L3829F

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1729]
It seems that this mutation is gained independently on many chronic seqs, and is the defining mutation for BE.1.1. (Doesn't even appear in lineage_note.txt, with just a note "Germany lineage")

#405
#764 
#770 
#871 
#1052 
#1266 
#1723 
#1724 

Due to this mutation being part of defining seqs of the shrinking BQ.1, the "overall growth rate" of orf1a:L3829F is negative. 

However, if we look into every non-BE.1.1* lineages,   a different pattern can be found.

Almost every lineage, if it has some seqs with orf1a:L3829F, the orf1a:L3829F seqs show positive growth rate.

[BF.7.14](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BF.7.14*&aaMutations1=ORF1a%3AL3829F&nextcladePangoLineage1=BF.7.14*&analysisMode=CompareToBaseline&)

<img width="1029" alt="Screen Shot 2023-03-06 at 00 12 57" src="https://user-images.githubusercontent.com/10445944/222972318-cdac98f3-0f67-4ddc-b22a-484dbec4063d.png">

[BN.1.1.1](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BN.1.1.1*&aaMutations1=ORF1a%3AL3829F&nextcladePangoLineage1=BN.1.1.1*&analysisMode=CompareToBaseline&)
<img width="1267" alt="Screen Shot 2023-03-06 at 00 14 55" src="https://user-images.githubusercontent.com/10445944/222973390-f0665801-23f4-40be-bb12-ffb8642e7a29.png">

[BR.2.1](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BR.2.1*&aaMutations1=ORF1a%3AL3829F&nextcladePangoLineage1=BR.2.1*&analysisMode=CompareToBaseline&)

<img width="1062" alt="Screen Shot 2023-03-06 at 00 17 15" src="https://user-images.githubusercontent.com/10445944/222972453-5fe74617-0436-4067-82bc-21b88954d704.png">

[CH.1.1](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BR.2.1*&aaMutations1=ORF1a%3AL3829F&nextcladePangoLineage1=BR.2.1*&analysisMode=CompareToBaseline&)
<img width="1139" alt="Screen Shot 2023-03-06 at 00 18 22" src="https://user-images.githubusercontent.com/10445944/222972522-9035c9cb-b189-4dc2-b140-27854067b410.png">

[XBB.1.5](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BR.2.1*&aaMutations1=ORF1a%3AL3829F&nextcladePangoLineage1=BR.2.1*&analysisMode=CompareToBaseline&)
<img width="1133" alt="Screen Shot 2023-03-06 at 00 19 42" src="https://user-images.githubusercontent.com/10445944/222972596-b62ee3cc-dbd2-4598-bbfe-8d1aceb18478.png">

[XBR](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BR.2.1*&aaMutations1=ORF1a%3AL3829F&nextcladePangoLineage1=BR.2.1*&analysisMode=CompareToBaseline&)
<img width="1012" alt="Screen Shot 2023-03-06 at 00 20 45" src="https://user-images.githubusercontent.com/10445944/222972665-33db98bb-23f6-4061-b964-96b9ce96f7ec.png">

[BA.5.2.48](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BA.5.2.48*&aaMutations1=ORF1a%3AL3829F&nextcladePangoLineage1=BA.5.2.48*&analysisMode=CompareToBaseline&)

<img width="1162" alt="Screen Shot 2023-03-06 at 00 22 42" src="https://user-images.githubusercontent.com/10445944/222972752-85355afa-cf68-4825-94c4-e5df20154194.png">

[BN.1.4](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BN.1.4*&aaMutations1=ORF1a%3AL3829F&nextcladePangoLineage1=BN.1.4*&analysisMode=CompareToBaseline&)
<img width="1250" alt="Screen Shot 2023-03-06 at 00 24 31" src="https://user-images.githubusercontent.com/10445944/222972853-3136e3f2-7262-49e8-b374-e5e676268257.png">

Note that many orf1a:L3829F are independently gained, even inside the same lineage there may be several different clusters all gaining orf1a:L3829F independently.

**Comment by AnonymousUserUse** [comment]
It would be helpful if we can make a list for mutations that have been shown growth advantage, both inside and outside spike protein. Or maybe is there already a list for that?

**Comment by FedeGueli** [comment]
Maybe @zach-hensel could add some more detail on this mutation in NSP6.

**Comment by aviczhl2** [comment]
> It would be helpful if we can make a list for mutations that have been shown growth advantage, both inside and outside spike protein. Or maybe is there already a list for that?

Lineage-based analysis is needed. Overall growth rate of single mutations is easily influenced by prevalence of lineages. For example, despite orf1a:L3829F being relatively growing in all lineages, however due to being part of the shrinking BQ.1, it's overall growth is negative.

**Comment by zach-hensel** [comment]
> Maybe @zach-hensel could add some more detail on this mutation in NSP6.

I do not have anything to add on this mutation specifically. Only a a suggestion to check out the recent @jbloomlab et al mutational fitness estimates here - https://github.com/jbloomlab/SARS2-mut-fitness - which addresses some of the concerns in this thread.

It's possible there may be differences in fitness benefits of nsp6 mutations in Delta compared to other variants as Delta lacks a 3-residue deletion in nsp6 characterizing other variants. A small fraction of recombinant lineages today carry a Delta nsp6 and might be interesting for comparison.

**Comment by aviczhl2** [comment]
> > Maybe @zach-hensel could add some more detail on this mutation in NSP6.
> 
> I do not have anything to add on this mutation specifically. Only a a suggestion to check out the recent @jbloomlab et al mutational fitness estimates here - https://github.com/jbloomlab/SARS2-mut-fitness - which addresses some of the concerns in this thread.
> 
> It's possible there may be differences in fitness benefits of nsp6 mutations in Delta compared to other variants as Delta lacks a 3-residue deletion in nsp6 characterizing other variants. A small fraction of recombinant lineages today carry a Delta nsp6 and might be interesting for comparison.

It has a highest fitness of +2.02 in all clades. It seems that altering the clade shows no change of that +2.02.  

But unlike Spike, orf8, orf7a  that are somehow explained by papers, this site is lack of explanation.

**Comment by zach-hensel** [comment]
@aviczhl2 Yes perhaps some minor bugs e.g. L37F does not display there. I have not explored the different clades; the analysis results are available to not go through the web interface.

I can't help much by way of explanation. There is another recent preprint with a similar take home to your paper and some insight into nsp3/4/6 published recently, but this mutation is a mystery to me. I believe the paper you link compares to WA-1 and not a 106-108 deletion VOC. I do not know any apples-to-apples comparison of 105-107, 106-108 deletions, various Delta nsp6 versions, etc. If there is a major difference for "Delta" vs "Omicron" nsp6, perhaps it would be noticed for one of the recombinant lineages with a Delta nsp6, but there are not many of these.

Here is a picture very quickly annotating nsp6 L260 on a predicted nsp6 structure after some molecular dynamics in a bilayer. Other residues with mutations scoring +1 or higher are shown as sticks and the orange and pink balls are alpha carbons for residues 105-108 and methionine residues, respectively. L260 is not packed with any other hydrophobic (and at least here not buried in the bilayer). This does not tell you much about possible impacts of L260F. Changes in packing or an unknown protein-protein interaction might matter here since the adjacent D267 has probably small fitness increases with D267G and D267E.

Some other fitness-increasing mutations are predicted to be for buried residues and some appeared very early in the pandemic, for what that's worth. Hard to come up with one explanation that encompasses all of this.

![image](https://user-images.githubusercontent.com/23096983/223190490-758e2e63-29e5-49c1-9b60-a883c2540e7f.png)

**Comment by aviczhl2** [comment]
> @aviczhl2 Yes perhaps some minor bugs e.g. L37F does not display there. I have not explored the different clades; the analysis results are available to not go through the web interface.
> 
> I can't help much by way of explanation. There is another recent preprint with a similar take home to your paper and some insight into nsp3/4/6 published recently, but this mutation is a mystery to me. I believe the paper you link compares to WA-1 and not a 106-108 deletion VOC. I do not know any apples-to-apples comparison of 105-107, 106-108 deletions, various Delta nsp6 versions, etc. If there is a major difference for "Delta" vs "Omicron" nsp6, perhaps it would be noticed for one of the recombinant lineages with a Delta nsp6, but there are not many of these.
> 
> Here is a picture very quickly annotating nsp6 L260 on a predicted nsp6 structure after some molecular dynamics in a bilayer. Other residues with mutations scoring +1 or higher are shown as sticks and the orange and pink balls are alpha carbons for residues 105-108 and methionine residues, respectively. L260 is not packed with any other hydrophobic (and at least here not buried in the bilayer). This does not tell you much about possible impacts of L260F. Changes in packing or an unknown protein-protein interaction might matter here since the adjacent D267 has probably small fitness increases with D267G and D267E.
> 
> Some other fitness-increasing mutations are predicted to be for buried residues and some appeared very early in the pandemic, for what that's worth. Hard to come up with one explanation that encompasses all of this.
> 
> ![image](https://user-images.githubusercontent.com/23096983/223190490-758e2e63-29e5-49c1-9b60-a883c2540e7f.png)

Thanks very much for the detailed explanation. Mysterious mutation with function unknown driving a new convergent mutation, hmmm....

At least we can track it...

**Comment by zach-hensel** [comment]
Mysterious but not new. Over 4% of B.1.1.7* in April 2021. 2% of P.1* and B.1.351*. Yet rare in B.1.617.2*. And now back to being frequent for BA.1, BA.2, BA.5. Just only recently occurring in a major lineage with BQ.1.

The best hints of some function might lie in what's different about the different Delta nsp6 than all of the others.

**Comment by aviczhl2** [comment]
> Mysterious but not new. Over 4% of B.1.1.7* in April 2021. 2% of P.1* and B.1.351*. Yet rare in B.1.617.2*. And now back to being frequent for BA.1, BA.2, BA.5. Just only recently occurring in a major lineage with BQ.1.
> 
> The best hints of some function might lie in what's different about the different Delta nsp6 than all of the others.

Yeah this mutation occured a lot previously, but was not showing growth advantages.

<img width="1054" alt="Screen Shot 2023-03-07 at 02 35 33" src="https://user-images.githubusercontent.com/10445944/223200535-d8b22ae9-ce43-4c54-a66f-6e3c6c2828aa.png">
<img width="1290" alt="Screen Shot 2023-03-07 at 02 36 20" src="https://user-images.githubusercontent.com/10445944/223200570-c549f53e-ac05-4bf7-9b23-557af706bc22.png">
<img width="1042" alt="Screen Shot 2023-03-07 at 02 37 43" src="https://user-images.githubusercontent.com/10445944/223200736-df67de41-a979-48a4-849a-054e687c6b8b.png">

**Comment by aviczhl2** [comment]
> Just only recently occurring in a major lineage with BQ.1.

BQ.1's success may partially due to this. However clearly nobody paid attention to this and all credits were given to immune-escape Spike mutations. 

> BE.1.1	Alias of B.1.1.529.5.3.1.1.1, Germany lineage

**Comment by zach-hensel** [comment]
Yes -- not a huge growth advantage for lineages with this one mutation versus the field but there are not many variations where this isn't true.

**Comment by oobb45729** [comment]
There's one relatively recent AY.46 that has the mutation and the percentage of Deltas that has it still grew over time in the Delta era. Plus the mutation is in the CTD of nsp6 unlike most other nsp6 mutations in VOCs. I don't there is enough evidence that suggest that Delta does not like the mutation yet.

**Comment by zach-hensel** [comment]
> There's one relatively recent AY.46 that has the mutation and the percentage of Deltas that has it still grew over time in the Delta era. Plus the mutation is in the CTD of nsp6 unlike most other nsp6 mutations in VOCs. I don't there is enough evidence that suggest that Delta does not like the mutation yet.

This is very, very rough, but one useful quick check is against local synonymous mutations of the same type. In this case, for example, C11750U encodes nsp6 L260F while C11752U is synonymous. Sorry for the unlabeled screenshot, but what it shows is that L260F took an early lead as a fraction of B.1.617.2* but both were circa 0.1% of sequences when things shifted to Omicron which IME is pretty typical for C-to-U mutations not subject to much selective pressure. This isn't to say that L260F is exactly neutral in all Delta contexts, especially given diversity of Delta nsp6.

![Screenshot_20230307-091425_Chrome](https://user-images.githubusercontent.com/23096983/223377303-c8afef21-3a95-45df-83a1-1d0425d4ae8e.jpg)

**Comment by corneliusroemer** [comment]
Just because a mutation appears doesn't mean it has a growth advantage.

Certain mutations seem to happen a lot for some biological reasons (e.g. deletion around ORF1a:85, S:L5F, etc). If there's a high mutation rate, even somewhat deleterious mutations will have a significant equilibrium rate.

This mutation might be one on the list of highly homoplasic mutations masked by Usher. Not sure.

**Comment by corneliusroemer** [comment]
I'm going to close this for now - if there's a lineage to propose open an issue and reference this issue for context
