### ISSUE TITLE
Potential new North American lineage with spike L18F, N148T, A688V, G768R, T1027I

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#173]
Description
Sub-lineage of: B.1
Countries: USA, Mexico, Honduras 
Earliest sequence: 12.02.21
Most recent sequence: 19.07.21

Defining mutations in Spike:
L18F
N148T
A688V
G769R
T1027I

Other defining mutations : 
NSP6:S106-108 deletion 
Nucleocapsid : N8Y
Nucleocapsid : I157V

Usher analysis :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_287cd_440c0.json

List of GISAID refence:
[GISAID Ref list.xlsx](https://github.com/cov-lineages/pango-designation/files/6951434/GISAID.Ref.list.xlsx)

**Comment by chrisruis** [comment]
Thanks @shay671. We've added this as B.1.636 in [v1.2.58](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.58)
