### ISSUE TITLE
BQ.1. sublineage with M:A104V, N:Q39L and S:Y248S - 56 Sequences Mexico Usa

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1731]
Here i want to propose a sublineage that emerged via stepwise evolution from BQ.1 gaining first M:A104V then N:Q39L ( it was defining in BA.2.23.1 ) that then acquired S:Y248S (BA.2.54, BA.2.38.1 , BA.2.79, EA.1 and EH.1) that is circulating in Usa and Mexico.
Beyond its mutational profile that shows recurrent mutations in designated lineages 
I am proposing it cause it is not far from Baseline of lineages with S:F486P :
Here the comparison vs XBB.1.5
<img width="1018" alt="Schermata 2023-03-06 alle 02 05 09" src="https://user-images.githubusercontent.com/87669813/222997559-2add7945-6a23-42db-8dff-98697c6ea638.png">
 C26833T > A28389T > T12667C > C4084T > A22305C 

**Defining mutations**:   M:A104V (C26833T) > N:Q39L ( A28389T ) > T12667C > C4084T >S:Y248S ( A22305C )

**Tree**:
<img width="1158" alt="Schermata 2023-03-06 alle 02 07 13" src="https://user-images.githubusercontent.com/87669813/222997704-0f096a71-8a57-451b-ba9b-21406675adf3.png">
<img width="1157" alt="Schermata 2023-03-06 alle 02 07 29" src="https://user-images.githubusercontent.com/87669813/222997718-9617edac-bd4e-4363-8059-04f9599057df.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_102c2_537ea0.json?c=gt-S_248&label=id:node_5886047

**Gisaid Query** : N_Q39L,Spike_Y248S

**Sequences**: 50 
EPI_ISL_16361062, EPI_ISL_16380649, EPI_ISL_16542568,
EPI_ISL_16704734, EPI_ISL_16705016, EPI_ISL_16707329,
EPI_ISL_16712313, EPI_ISL_16728517, EPI_ISL_16728596,
EPI_ISL_16762469, EPI_ISL_16762558, EPI_ISL_16826467,
EPI_ISL_16834954, EPI_ISL_16848468, EPI_ISL_16849383,
EPI_ISL_16849426, EPI_ISL_16850909, EPI_ISL_16851606,
EPI_ISL_16877175, EPI_ISL_16877226, EPI_ISL_16877267,
EPI_ISL_16877272, EPI_ISL_16877327, EPI_ISL_16877335,
EPI_ISL_16889473, EPI_ISL_16892015, EPI_ISL_16892258,
EPI_ISL_16895881, EPI_ISL_16895906, EPI_ISL_16910637,
EPI_ISL_16916338, EPI_ISL_16939436, EPI_ISL_16945770,
EPI_ISL_16962161, EPI_ISL_16962200, EPI_ISL_16968696,
EPI_ISL_16968732, EPI_ISL_16982610, EPI_ISL_16991699,
EPI_ISL_17019528, EPI_ISL_17024864, EPI_ISL_17026582,
EPI_ISL_17026590, EPI_ISL_17049503, EPI_ISL_17058887,
EPI_ISL_17068198, EPI_ISL_17081338, EPI_ISL_17084644,
EPI_ISL_17084684, EPI_ISL_17089101

**Comment by FedeGueli** [comment]
56 seqs as today

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.32 with 39 newly designated sequences, and 0 updated. Defining mutation A22305C (S:Y248S) (following C4084T).

**Comment by FedeGueli** [comment]
Thx @InfrPopGen
