### ISSUE TITLE
DY.1 + S:V1228L circulating in Fujian, China (14seqs)

### ISSUE THREAD

**Issue by Last-Order** [cov-lineages/pango-designation#1733]
Sequences:
EPI_ISL_17072212-17072221, EPI_ISL_17100882-17100885
GISAID query:
BA.5.2.48 + Spike_A570S, Spike_V1228L
Earliest sequence:
2023-02-21 (China, EPI_ISL_17072212)
Most recent sequence:
2023-02-24 (China, EPI_ISL_17100885)

![image](https://user-images.githubusercontent.com/3362825/223310396-5ccf86f6-8a2c-4ba2-9eff-024305f08065.png)

**Comment by Last-Order** [comment]
close due to no more sequences.

**Comment by aviczhl2** [comment]
17 seqs now.
