### ISSUE TITLE
Potential Recombinant of BF.7.14 and BA.5.2* in Sichuan and Yunnan(6 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1734]
GISAID query: G1085T,G14181C,T11587C,-G25290T,-C27532T
Sequences: EPI_ISL_16737882, EPI_ISL_16970278, EPI_ISL_17062083, EPI_ISL_17104804 (Sichuan, from 3 different cities)
Earliest Sequence:EPI_ISL_16737882 2023.1.10
Latest Sequence:EPI_ISL_17104804 2023.2.21

The sequence shares all mutations with BF.7.14+T11587C branch before position 25290, then it is like a normal BA.5.2, without G25290T, A27038G or C27532T in BF.7.14. 

So I suspect it is a recombination of BF.7.14 and BA.5.2 (maybe 5.2.48, which is no different from vanilla BA.5.2 after 25290.)

<img width="1356" alt="Screen Shot 2023-03-07 at 15 00 54" src="https://user-images.githubusercontent.com/10445944/223353488-715904bc-1876-49b0-859c-a8f41010a99a.png">

[usher, it seems that there're a lot more singlet recombinations involving BF.7.14 on this “BA.5.2" branch](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice7_genome_24228_6df490.json?label=id:node_6965325)

**Comment by Mydtlwn** [comment]
#1642 #1719

**Comment by aviczhl2** [comment]
7 seqs when counting GenBase seqs.
