### ISSUE TITLE
CH.1.1 Sublineage with S:T299I, S:R403K, S:D1165G, ORF10:I4V (19 seq, Mar 24)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1736]
### **Description**
**Sub-lineage of:** CH.1.1
**Earliest sequence:** 2023-1-26, England — England/DHSC-CYGDD31/2023 (not on GISAID)
**Most recent sequence:** 2023-2-28, England — EPI_ISL_17105228
**Countries circulating:** England (16)
**Number of Sequences:** 16
**GISAID AA Query:** Spike_R403K, Spike_T299I, Spike_D1165G
**GISAID Nucleotide Query:** G2357A, C3857A, A25056G, C27389T, A29567G
**CovSpectrum Query:** Nextcladepangolineage:CH.1.1* & [3-of: C22458T, G22770A, A25056G, C27389T, A29567G]
**Substitutions on top of XBB.1.5:**
**Spike:** T299I, R403K, D1165G
**ORF1a:** A698T
**ORF10:** I4V
**Nucleotide:** G2357A, C22458T, G22770A, A25056G, C27389T, A29567G
 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/CH.1.1_T299I%2CR403K%2CD1165G_subtreeAuspice1_genome_ac74_719fe0.json   
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/33738461/223409012-c0c7658c-7e9f-4efd-a0cf-6d983e6e3b7d.png">

**Evidence**
This lineage only showed up very recently but appears to be growing quickly in England. It's possible it's a local outbreak that will die out quickly, as we've seen in England before, but the sequences come from three different originating labs, which I believe indicates they came from different locations in England.
 
The ACE2 affinity of CH.1.1 is weak, probably the weakest of any widely circulating variant—lower than XBB* lineages that still have S:F486S, for example. It seems possible an increase in ACE2 affinity could improve CH.1.1's fitness similar to how S:S486P increased XBB* fitness (though the magnitude of CH.1.1's increase would almost certainly be much smaller). See measured ACE2-binding affinity below as measured by Yunlong Cao, et al. in "Imprinted SARS-CoV-2 humoral immunity induces convergent Omicron RBD evolution." https://www.nature.com/articles/s41586-022-05644-7
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/33738461/223414334-07977679-2ab3-473d-8c7e-e797ec712ba5.png">

S:R403K is, according to the Bloom Lab RBD heat map one of the few known spike mutations to substantially enhance ACE2 affinity on a BA.2 background. https://jbloomlab.github.io/SARS-CoV-2-RBD_DMS_Omicron/RBD-heatmaps/
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/33738461/223413113-041dcf6c-7cc3-41c9-8d6f-15fe552b58a4.png">
 
S:T299I has been seen at low levels throughout the pandemic, and its fitness effects seem neutral. The nucleotide for this mutation is surrounded on both sides by two adenines, which is a perfect context for APOBEC-caused deamination, leading to C->T substitution, so this is the likely cause of T299I.
<img width="937" alt="image" src="https://user-images.githubusercontent.com/33738461/223409260-81b40442-e1a5-4271-a15c-2881cfab8610.png">
 
S:D1165G is much less common, only appearing in 18 sequences outside this lineage in the past three months.
 
**Genomes** (Note: 8/16 sequences are visible on the Usher tree but are not yet on GISAID and so are not included below)
<details>
<summary>Genomes</summary>
EPI_ISL_16937741, EPI_ISL_17016814, EPI_ISL_17032431, EPI_ISL_17097378, EPI_ISL_17098175, EPI_ISL_17098700, EPI_ISL_17105228, EPI_ISL_17105510
</details>

**Comment by oobb45729** [comment]
T299I actually is not far from Q613H, and they were seen together in some AY.33s.
T299I is even closer to Q314 and T315, which could interact with K764.

**Comment by thomasppeacock** [comment]
This looks very interesting - going to stick a monitor label on it but if it grows for another week or so I think we should designate it.

**Comment by Mild1-ai** [comment]
Thank you! It has been specified as CH.1.20!`e3c981f`

**Comment by FedeGueli** [comment]
> Thank you! It has been specified as CH.1.20!`e3c981f`

CH.1.1.20
