### ISSUE TITLE
Mini-saltation of CH.1.1 with additional spike V6F, N137S, Q183L and W152R (12 seqs as of 2023-03-30)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1738]
### Description
**Sublineage of**: CH.1.1
**Earliest sequence**: 2023/02/21 (UK-England)
**Most recent sequence**: 2023/02/27 (UK-England)
**Countries circulating**: UK-England

**Mutations on top of CH.1.1**: C2773T > T7292C > G21578T (S:V6F) > A21972G (S:N137S) > **G368T (ORF1a:V35L), T14418C, G22018T (S:W152R), A22110T (S:Q183L)**

**GISAID and Cov-spectrum query**: G368T, T14418C, A22110T

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/223603277-b8a79017-526b-4d73-b7fa-8e53b5674894.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3041f_75a630.json?branchLabel=Spike%20mutations&c=gt-nuc_14418&label=id:node_7974810

### Genomes:
EPI_ISL_17045616, EPI_ISL_17105071, EPI_ISL_17105090, EPI_ISL_17105101, EPI_ISL_17105123, EPI_ISL_17105137, EPI_ISL_17105158, EPI_ISL_17105160, EPI_ISL_17105179, EPI_ISL_17105191, EPI_ISL_17105271

**Comment by FedeGueli** [comment]
Great catch Saka. N137S on the move lately

**Comment by oobb45729** [comment]
With T22016C(S:W152R), G22018T is synonymous.

**Comment by FedeGueli** [comment]
Yes it S:W152R @c19850727

**Comment by c19850727** [comment]
I'm to close this issue as it's no longer growing.
