### ISSUE TITLE
New lineage within P.1 carrying Spike:Q675H

### ISSUE THREAD

**Issue by aplamarca** [cov-lineages/pango-designation#174]
**Description**

We have identified an expanding clade within P.1 carrying five mutations in ORF1ab (P109P, I1259V, F1925F, A3209V, P6128L) and the Q675H mutation in the Spike gene. We have identified a signal of episodic selection on codon 675 in the origin of this clade. We argue that this evidence and the repeated emergence of this mutation in other lineages suggest that Q675H pays an important role on viral evolution. To facilitate monitoring, this clade should be elevated to a new lineage. 

**Sub-lineage of:** P.1
**Earliest sequence:** hCoV-19/Brazil/RJ-LVM38097/2021|EPI_ISL_2629811|2021-04-09
**Most recent sequence:** hCoV-19/Brazil/RJ-FIOCRUZ-39302/2021|EPI_ISL_3235262|2021-07-12; hCoV-19/Brazil/RJ-LNN03554/2021|EPI_ISL_3245253|2021-07-15; hCoV-19/Brazil/RJ-LNN03570/2021|EPI_ISL_3245269|2021-07-15; hCoV-19/Brazil/RJ-LNN04292/2021|EPI_ISL_3245441|2021-07-15

**Countries circulating:** Brazil (83 sequences) and Mexico (1)

**Genomes**
[list_Q675H.txt](https://github.com/cov-lineages/pango-designation/files/6957702/list_Q675H.txt)

**Evidence**
![Q675H_tree](https://user-images.githubusercontent.com/82976078/128780457-9d1c1064-7169-49ec-8f81-7f5e958b78a9.png)
Node values correspond to bootstrap support. 

**Proposed lineage name:** P.1.9

**Comment by chrisruis** [comment]
Thanks @aplamarca. We've added this as P.1.9 in [v1.2.58](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.58)
