### ISSUE TITLE
BQ.1.1 sublineage with S:K147E, S:H207R (51 seq., Canada, Japan, Spain, USA)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1740]
Proposal for a sublineage of BQ.1.1
Earliest sequence: 12.12.2022 (Canada)
Countries detected: Canada, Japan, Spain, USA

Defining mutation:
S:K147E=A22001G
S:H207R=A22182G
T10441C
T16533C

Gisaid query: A22001G, A22182G, T10441C, T16533C

This recent sublineage of BQ.1.1 is defined by S:K147E, S:H207R  and was found in Canada, Japan, Spain, USA so far. 

![grafik](https://user-images.githubusercontent.com/102166254/223956603-4ee8b397-8321-4680-b0a6-4069a74eccfd.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d9b6_98cb90.json?c=country

![grafik](https://user-images.githubusercontent.com/102166254/223956823-52a64a23-7004-4160-938c-465cb5261881.png)

EPI_ISL_16242509, EPI_ISL_16306398, EPI_ISL_16306814, EPI_ISL_16459922, EPI_ISL_16489608, EPI_ISL_16489609, EPI_ISL_16489910, EPI_ISL_16495046, EPI_ISL_16510053, EPI_ISL_16690056, EPI_ISL_16732139, EPI_ISL_16747887, EPI_ISL_16837611, EPI_ISL_16869921, EPI_ISL_16869922, EPI_ISL_16869923, EPI_ISL_16869924, EPI_ISL_16869925, EPI_ISL_16869926, EPI_ISL_16869927, EPI_ISL_16869928, EPI_ISL_16869929, EPI_ISL_16869930, EPI_ISL_16869931, EPI_ISL_16869932, EPI_ISL_16869943, EPI_ISL_16973229, EPI_ISL_16974427, EPI_ISL_16986032, EPI_ISL_16986034, EPI_ISL_16989714, EPI_ISL_16989795, EPI_ISL_17034629, EPI_ISL_17056864, EPI_ISL_17063901, EPI_ISL_17063924, EPI_ISL_17085539, EPI_ISL_17085584, EPI_ISL_17085716, EPI_ISL_17152963, EPI_ISL_17152964, EPI_ISL_17152965

OQ295125.1
OQ399325.1

**Comment by FedeGueli** [comment]
Nice catch i spotted that H207R too.

**Comment by agamedilab** [comment]
51 on 24.03.23.

![image](https://user-images.githubusercontent.com/102166254/227515502-58080f66-9279-4aed-be26-643dc609c9e1.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4254f_d906f0.json?label=id:node_6143006

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.1.73 with 47 newly designated sequences, and 3 updated from BQ.1.1. Defining mutations A22182G (S:H207R), T10441C, T16533C (following A22001G (S:K147E)).
