### ISSUE TITLE
BQ.1.1.43 sublineage with S:S247N, S:Y248S (106 seq., c. 12 countries)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1741]
Proposal for a sublineage of BQ.1.1.43
Earliest sequence: 28.12.2022 (Spain)
Countries detected: Portugal, Germany, Italy, Spain, France, Luxembourg, Wales, England, Ireland, Belgium, Sweden, Switzerland, Israel

Defining mutation:
S:S247N = G22302A
S:Y248S = A22305C

Gisaid query: C26292T, G22302A, A22305C

This recent sublineage of BQ.1.1.43 is defined by S:S247N, S:Y248S (reminiscent to BA.2.38.1, #809 but with S:K444T) and was found in c. 12 countries so far.

![grafik](https://user-images.githubusercontent.com/102166254/223959600-195d5cca-4cf6-4997-9f32-bf98c62b6f7c.png)
![grafik](https://user-images.githubusercontent.com/102166254/223959753-c6c52dba-25f8-4b0b-987e-4c3b537165a7.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12e2c_990160.json?c=country&label=id:node_5956110

![grafik](https://user-images.githubusercontent.com/102166254/223961118-c0bca303-38b1-4d90-8870-70e1b648c064.png)

EPI_ISL_16617942, EPI_ISL_16618029, EPI_ISL_16618169, EPI_ISL_16759090, EPI_ISL_16832239, EPI_ISL_16832247, EPI_ISL_16866671, EPI_ISL_16866673, EPI_ISL_16866688, EPI_ISL_16866775, EPI_ISL_16886289, EPI_ISL_16913739, EPI_ISL_16925564, EPI_ISL_16925688, EPI_ISL_16954595, EPI_ISL_16955486, EPI_ISL_16957159, EPI_ISL_16975050, EPI_ISL_16975062, EPI_ISL_16975090, EPI_ISL_16975095, EPI_ISL_16975145, EPI_ISL_16975150, EPI_ISL_16975157, EPI_ISL_16975165, EPI_ISL_16975172, EPI_ISL_16975173, EPI_ISL_16975174, EPI_ISL_16975176, EPI_ISL_16975177, EPI_ISL_16975181, EPI_ISL_16975183, EPI_ISL_16975201, EPI_ISL_16996344, EPI_ISL_17025367, EPI_ISL_17025419, EPI_ISL_17063594, EPI_ISL_17075997, EPI_ISL_17077121, EPI_ISL_17096083, EPI_ISL_17096085, EPI_ISL_17096086, EPI_ISL_17096087, EPI_ISL_17096099, EPI_ISL_17096107, EPI_ISL_17096113, EPI_ISL_17096114, EPI_ISL_17096116, EPI_ISL_17096118, EPI_ISL_17096125, EPI_ISL_17096138, EPI_ISL_17096146, EPI_ISL_17096149, EPI_ISL_17096155, EPI_ISL_17096183, EPI_ISL_17096186, EPI_ISL_17096202, EPI_ISL_17096228, EPI_ISL_17096235, EPI_ISL_17096238, EPI_ISL_17097449, EPI_ISL_17097565, EPI_ISL_17155689, EPI_ISL_17156292

**Comment by FedeGueli** [comment]
Thx for proposing i thi k it is the one @ryhisner found some weeks ago and i was monitoring since. In my chart slowed down a lot but it is correct to propose it

**Comment by agamedilab** [comment]
106 seq as of 20.03.23.

![grafik](https://user-images.githubusercontent.com/102166254/226271721-10b0956d-832f-4ff8-8798-2f29cb5bfe65.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ee19_807cb0.json?c=gt-nuc_22305

**Comment by agamedilab** [comment]
@NkRMnZr thank you for pointing this out! I will close this one. #1673 should probably get the EZ.1 designated label & milstone. @InfrPopGen @corneliusroemer
