### ISSUE TITLE
XBB.1.5.39 sublineage with Orf1a:M3684T, Orf1a:S538L and S:I197V emerged in Canada - 332 sequences  

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1745]
I completely missed this lineage and this spike mutation emerged in XBB.1.5 until tonite, and while checking i saw it is already quite a big sublinegae even if it still mostly a canadian sublineage: it branches out from a part of the tree defined by two Orf1a mutations acquired step by step: 
first popped up Orf1a:M3648T = NSP6_M79T ( @zach-hensel maybe interested in) in NYC 
and then Orf1a:S538L =NSP2_S358L that likely marks the introduction into Canada 
This branch, counting around 500 sequences in total then acquired S:F197V,
 that now represents 1/4 of its sequences and it has been characterized by an efficient spread at least in Canada.

in #871 i ve already proposed an unsuccessful mini cluster of a BA.2 + S:I197V australian lineage that had been quite successful there reaching 500+ sequences before BA.2 declining

S:I197V is predicted by Bloom Lab calculator to increase viral fitness
<img width="149" alt="Schermata 2023-03-10 alle 00 08 07" src="https://user-images.githubusercontent.com/87669813/224180936-d272c8b0-54ec-4b5a-b347-7962bab58b81.png">
while the NSP& mutation seems deleterious and the NSp2 one very slighty beneficial.

**Defining mutations**:  XBB.1.5 > > T10204C >  Orf1a:M3684T (T11316C) > Orf1a:S538L (C1878T) > S:I197V (A22151G)

**Tree:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_2d9c7_a5f2a0.json?c=gt-S_197&label=id:node_7719239
<img width="1141" alt="Schermata 2023-03-10 alle 00 06 57" src="https://user-images.githubusercontent.com/87669813/224180766-c277e70c-6657-48eb-a866-237f18118f9d.png">

**Gisaid query** :
Spike_i197V,Spike_F486P,NSP2_S358L

Sequences: 120
[contributors (1).csv](https://github.com/cov-lineages/pango-designation/files/10937063/contributors.1.csv)

**Comment by FedeGueli** [comment]
150 sequences , the last 30 from Canada.

**Comment by FedeGueli** [comment]
196 seqs

**Comment by Memorablea** [comment]
> S:I197V is predicted by Bloom Lab calculator to increase viral fitness 

Could you please post a link to the Bloom Lab calculator? Thank you!

**Comment by FedeGueli** [comment]
> > S:I197V is predicted by Bloom Lab calculator to increase viral fitness
> 
> Could you please post a link to the Bloom Lab calculator? Thank you!

https://jbloomlab.github.io/SARS2-mut-fitness/

**Comment by FedeGueli** [comment]
261 sequences but especially it managed to be exported to Sweden and Belgium

**Comment by FedeGueli** [comment]
317 sequences mostly from Canada. i saw another lineage with S:i197V has been spotted and proposed recently , maybe worth designated to left track of this newly convergent mutation?? @InfrPopGen lemme know alternatively i can close this one.
