### ISSUE TITLE
Saltation of CH.1.1.18 with S:T323I, S:E484P, ORF8:L7S, N:A155V, N:T271I (13 seqs as of 2023-04-06 in 3 countries)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1747]
First spotted by @ryhisner , many thanks!

This proposed sublineage should be a sub-branch of CH.1.1 with S:K187T, an undesignated branch that currently has ~150 sequences, but it is (mis)placed at a sibling branch probably due to missing coverages.

![image](https://user-images.githubusercontent.com/86835836/224229598-381f5213-b4f9-42a1-b8da-44320037e6b9.png)

![image](https://user-images.githubusercontent.com/86835836/224233764-4e2fdef8-e947-4e0c-9ab2-7e2d80811940.png)

### Description
**Sublineage of**: CH.1.1
**Earliest sequence**: 2023/02/07 (Germany-SH)
**Most recent sequence**: 2023/02/20 (Germany-SH)
**Countries circulating**: Switzerland (1/6), Germany (2/6), Oman (3/6)
The 3 genomes from Oman have some detailed metadata, indicating one of which is from ILI sentinel surveillance sample, while the other two are from non-sentinel-surveillance in two different hospitals. 

**Mutations on top of CH.1.1**: A9154G, C11674T > A2015G (ORF1a:M584V), C23086T > C25710T, C28737T (N:A155V) > C3486T (ORF1a:A1074V) > A22122C (S:K187T)  > **A5068G, C22530T (S:T323I), G23012C (S:A484P), C23380T, T27913C (ORF8:L7S), C28312T, C29085T (N:T271I)**

**GISAID and Cov-spectrum query**: A2015G, C3486T, A5068G, A9154G

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/224236727-fa3f66fb-2462-4c13-8d74-4021b6aaf710.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_363cb_a8fae0.json?branchLabel=Spike%20mutations&c=gt-nuc_22122&label=id:node_8011844

### Genomes:
EPI_ISL_17004806, EPI_ISL_17026462, EPI_ISL_17026466, EPI_ISL_17026483, EPI_ISL_17071908, EPI_ISL_17076001

**Comment by Mydtlwn** [comment]
S:K187T  mutation was mentioned by @silcn and @oobb45729 in #1380

**Comment by ryhisner** [comment]
I believe K187T creates a potential glycan site: N-F-T.

**Comment by AnonymousUserUse** [comment]
Maybe this branch should be designated first: A9154G, C11674T > A2015G (ORF1a:M584V), C23086T > C25710T, C28737T (N:A155V) > C3486T (ORF1a:A1074V) > A22122C (S:K187T).
And then the further 7 mutations on the top are only mini-saltation.

**Comment by corneliusroemer** [comment]
Parent is designated CH.1.1.18. I suspect the tree is wrong and the parent is 187T.

**Comment by c19850727** [comment]
It seems it's no longer growing. Close the issue for now.
