### ISSUE TITLE
BN.1.3+S:V83F+orf1b:P976L circulating in Guangdong and South Korea(29 seqs, 5 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1748]
Earliest Seq: EPI_ISL_16455636 (USA) 2022.12.26
Latest Seq: EPI_ISL_17170979（Guangdong) 2023.2.22
No of seqs: 21 (8 Guangdong, 1 Japan(imported from China), 9 South Korea(1 imported from China, 8 local), 3 USA)
GISAID query: C16394T,G21809T,C593T

The lineage is imported from somewhere and locally-circulating in Guangdong( and maybe other parts of China), then exported to South Korea and Japan around 2023-1-1, and started local transmission in South Korea in late Jan.

Mutations on top of BN.1.3: G11146T(orf1a:M3627I),C593T,G21809T(S:V83F),C16394T(orf1b:P976L)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37c66_ac8110.json?f_userOrOld=uploaded%20sample&label=id:node_7924190)

 
<img width="1395" alt="Screen Shot 2023-03-10 at 14 07 13" src="https://user-images.githubusercontent.com/10445944/224238796-882d4711-8dfa-4ff8-bd8b-5041b8a3986f.png">

**Comment by aviczhl2** [comment]
24 seq, 3 more from South Korea.

**Comment by aviczhl2** [comment]
29 seqs, 5 more from today's batch from Guangdong.

**Comment by FedeGueli** [comment]
Now this should have been designated BN.1.3.9 from https://github.com/cov-lineages/pango-designation/commit/cdcebd4581843a92caf1606b2210690e0a8822fa

**Comment by corneliusroemer** [comment]
Well, the parent has been designated https://github.com/cov-lineages/pango-designation/commit/cdcebd4581843a92caf1606b2210690e0a8822fa not this sublineage (yet). Let's see how it evolves in Guangdong

**Comment by Memorablea** [comment]
> Well, the parent has been designated [cdcebd4](https://github.com/cov-lineages/pango-designation/commit/cdcebd4581843a92caf1606b2210690e0a8822fa) not this sublineage (yet). Let's see how it evolves in Guangdong

I don't understand why the BN.1.3 subline in Guangdong was designated. So please is this issue closed by error?

**Comment by aviczhl2** [comment]
6 more seqs in GenBase, C_AA003376,C_AA003380,C_AA003382,C_AA003383,C_AA003384,C_AA003387
