### ISSUE TITLE
2 probable sub lineages of B.1.617.2 (Delta) responsible for majority of the samples in Indonesia 

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#175]
Out of 477 last samples from Indonesia uploaded to GISAID (from 23.06 until today) 442 are Delta. 
From those Delta samples, 316 are from the first lineage described here, 123 are from the second and only 3 are not belong to those two.

 First lineage -  
Unique mutations * : NSP2_P200L,NSP3_P1228L,Spike_V1264L
Mainly circulates in : Singapore (1254),Indonesia (942), Australia (101), South Korea (84).
First sequence in Indonesia, March 2021.

Usher analysis
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_958c_19a100.json?label=nuc%20mutations:C1404T,C4752T,G25352T

Gisaid ref list 
[First lineage (Clade D based) GISAID ref.xlsx](https://github.com/cov-lineages/pango-designation/files/6960911/First.lineage.Clade.D.based.GISAID.ref.xlsx)

Second lineage-
Unique mutations * :  ORF3a:P104S, S:T778T (Silent mutation, c23896t). 
Mainly circulates in : Indonesia (259),Germany (65), Japan (44), France (43)
First sequence in New Zealand, March 2021. 

Usher analysis
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3b25f_252300.json?label=nuc%20mutations:C25702T

Gisaid ref list 
[Second lineage (clade A based) GISAID ref.xlsx](https://github.com/cov-lineages/pango-designation/files/6960912/Second.lineage.clade.A.based.GISAID.ref.xlsx)

* Mutations above the major Delta clades they evolved from 
First lineage evolved from Clade D
Second lineage evolved from Clade A
As described in :
https://www.medrxiv.org/content/10.1101/2021.08.05.21261642v1

**Comment by shay671** [comment]
What's interesting regarding the first lineage is that it share of the general Clade D samples (the Delta clade which became dominant worldwide as reported in the paper referenced above) in Indonesia and Singapore, shows an increase over time.  

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Shai/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Shai/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
Indonesia |   |   | Singapore |  
  | # Delta D * suspect | # General Delta D |   |   | # Delta D * suspect | # General Delta D
Jan | 1 | 2 |   |   |   |  
Mar | 1 | 1 |   |   |   |  
Apr | 15 | 11 |   | Apr | 0 | 45
May | 130 | 9 |   | May | 1 | 341
Jun | 706 | 15 |   | Jun | 19 | 327
Jul | 101 | 2 |   | Jul | 1204 | 36
Aug | 2 | 0 |   | Aug | 231 | 1



</body>

</html>




This trend, for instance, was not seen in AY.3 (which also evolved from clade D) when analyzed in different states in the US and the UK.

**Comment by shay671** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Shai/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Shai/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Indonesia |   |   | Singapore |  
-- | -- | -- | -- | --
  | # Delta D * suspect | # General Delta D |   |   | # Delta D * suspect | # General Delta D
Jan | 1 | 2 |   |   |   |  
Mar | 1 | 1 |   |   |   |  
Apr | 15 | 11 |   | Apr | 0 | 45
May | 130 | 9 |   | May | 1 | 341
Jun | 706 | 15 |   | Jun | 19 | 327
Jul | 101 | 2 |   | Jul | 1204 | 36
Aug | 2 | 0 |   | Aug | 231 | 1



</body>

</html>

**Comment by shay671** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Shai/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Shai/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Singapore |  
-- | --
  | # Delta D * suspect | # General Delta D
Apr | 0 | 45
May | 1 | 341
Jun | 19 | 327
Jul | 1204 | 36
Aug | 231 | 1



</body>

</html>



<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Shai/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Shai/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Indonesia |  
-- | --
  | # Delta D * suspect | # General Delta D
Jan | 1 | 2
Mar | 1 | 1
Apr | 15 | 11
May | 130 | 9
Jun | 706 | 15
Jul | 101 | 2
Aug | 2 | 0



</body>

</html>

**Comment by shay671** [comment]
What's interesting is that the share of the first lineage out of the general clade D it evolved from  is rising in Singapore and Indonesia.  

![iNDO](https://user-images.githubusercontent.com/80166370/128883641-2a55f551-8c45-4cfb-8225-a214b9db46d1.jpg)



This pattern was not seen when tracking the share of AY.3 out of general Delta clade D (which it also been evolved from) in the main US states it's abundant in and also in the UK

**Comment by shay671** [comment]
Regarding the A222V mutation, It's actually a defining mutation of the clade A of delta (as analyzed in the paper i referenced). 
But i think that the first lineage here is really the thing to check as it is evolved from clade D. Clade D is taking over worldwide.  

You wondered if there is a systematic way for catalog and find all these variants, well i actually have some kind of method. It's not based on phylogenetic trees but rather use them to verify the results. This is the method in the base of the paper i referenced, and the way i found B.1.631 and B.1.636. But, unfortunately i lack coding skills so i actually do this manually with excel sheets.

**Comment by chrisruis** [comment]
Thanks @shay671. We've added your lineage 1 as AY.23 and your lineage 2 as AY.24 in [v1.2.61](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.61)

**Comment by shay671** [comment]
Correction regarding AY.23 :

The mutation NSP3_P1228L is not a defining mutation of AY.23 but rather of clade D of delta from which it was evolved (it it defining it but not it's unique consensus). 
But - NSP3_T678I is a mutation of the unique consensus of AY.23 and was not mentioned in the first report i gave. 

@chrisruis

**Comment by chrisruis** [comment]
Thanks @shay671. I think NSP3_T678I is nucleotide mutation C4752T so this occurs on the branch where we started AY.23, as this coincides with the introduction(s) into Indonesia/Singapore/Japan/South Korea.

We've now got a summary of the AY lineages including their defining mutations [here](https://www.pango.network/new-ay-lineages-and-an-update-to-ay-4-ay-12/)

**Comment by shay671** [comment]
That's a great summary @chrisruis  , Thank you 
Regarding AY.12- It's mentioned there that it has S:T791I as a defining mutation. But the signature of this Israeli clade includes more mutations : 

First there are the 11 mutations of the Delta clade it is part of (and which is taking over the world), But let's put that aside. 

Than you got 5 mutations which accumulated in a stepwise order, ill mention them here in a ascending order according to their appearance in the phylogenetic tree : 
            
G1048T	- NSP2:K81N

C19983T	 - NSP15:V121V

G20937t	- NSP16:T93T

C23934T	- S:T791I

C25516T	- ORF3a:P42S (It was accumulated after S:T791I, but as AY.12 designated as an Israeli lineage, This last mutation is in the consensus of the Israeli part of this broader clade)


I think this specification is important as it  focus to thia lineage and not other unrelated B.1.617.2 lineages with S:T791I.

**Comment by chrisruis** [comment]
Thanks @shay671. The mutations listed for each lineage in that table are just those that are acquired along the branch immediately before the common ancestor of the lineage, i.e. on the branch where we've started the lineage. These mutations therefore separate the lineage from other closely related sequences and we'd expect that at least most sequences assigned to an AY lineage would have the listed mutations. But they aren't the only mutations that have occurred since the root of the Delta clade and there will be more mutations separating each of the AY lineages from more distant B.1.617.2 sequences and other AY lineages.

**Comment by shay671** [comment]
I run today some random samples based on GISAID of the 2 variants in USHER. There seems to be some misassignment of those 2.

Here is for AY.23 : 
![image](https://user-images.githubusercontent.com/80166370/132666961-bd188f13-4045-47bc-bdcb-2d03f03f5a6f.png)


And here is for AY.24 : 
![image](https://user-images.githubusercontent.com/80166370/132667050-3872ccb7-06b8-4115-b47a-6a3fbed040ee.png)
