### ISSUE TITLE
CH.1.1.1 with S:Q613H [197 sequences, United Kingdom and Sweden]

### ISSUE THREAD

**Issue by Outpfmance** [cov-lineages/pango-designation#1753]
This is another branch with the Q613H mutation, which is already present in a large proportion in DV.1 (CH.1.1.1.1), as well as in the ancestor of DV.1, CH.1.1.1, which is not as large as in DV.1, but is of concern.
And in recent times, the relative growth advantage of this variant has increased.
Cov-spectrum:
 https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-01-01%26to%3D2023-03-01/variants?aaMutations=s%3A613h&nextcladePangoLineage=CH.1.1.1&

Nextstrain: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_30e5b_85b1b0.json?f_userOrOld=uploaded%20sample

**Comment by Mydtlwn** [comment]
#1718 #1720

**Comment by Outpfmance** [comment]
128 sequences now.

**Comment by Outpfmance** [comment]
148 sequences now.

**Comment by Outpfmance** [comment]
@InfrPopGen I am confident that this branch exists, it is CH.1.1.1+Q613H (not DV.1), which can be found in the Nextstrain tree, a branch under DV.1, which had a sequence count of 148 in the last update of the cov-spectrum.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_30e5b_85b1b0.json?f_userOrOld=uploaded%20sample&label=id:node_3864100

**Comment by InfrPopGen** [comment]
> @InfrPopGen I am confident that this branch exists, it is CH.1.1.1+Q613H (not DV.1), which can be found in the Nextstrain tree, a branch under DV.1, which had a sequence count of 148 in the last update of the cov-spectrum. https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_30e5b_85b1b0.json?f_userOrOld=uploaded%20sample&label=id:node_3864100
> 
> https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_30e5b_85b1b0.json?f_userOrOld=uploaded%20sample

Thank you @Outpfmance 
I used your cov-spectrum query (changed to cover all times, rather than a few weeks) to find 168 sequences, and placing these on the tree suggested that I am looking at the same clade as you; this clade is in fact quite a bit bigger. The 168 sequences formed a clade with EPI_ISL_16732167 close to its root, which is the node with S:Q613H, but this would make the proposed clade a descendant of DV.1, because the mutation paths overlap on the tree:
# Path from CH.1.1.1 to DV.1 A22115G (S:N185D),T24991A,C1545T,A19886G,C25721T,T4402A,C22088T (S:L176F)
# Path from CH.1.1.1 to the proposed clade:
# A22115G (S:N185D), T24991A, C1545T, A19886G, C25721T, T4402A, C22088T (S:L176F) <--- root of DV.1, then G23401T (S:Q613H), and the proposed clade.
# So this would be DV.1 then G23401T (S:Q613H), which makes it a sub-lineage of DV.1
At least it looks that way?

**Comment by corneliusroemer** [comment]
Without having looked at it - this could well be homoplasy or artefact, needs to be looked at more closely

**Comment by corneliusroemer** [comment]
There's this DV.1 sibling, on the branch with DV.3 (25721T). Small UK/Australia (60). Sequences should be CH.1.1.1

<img width="1515" alt="image" src="https://user-images.githubusercontent.com/25161793/226416478-c93615e5-b5e3-43bf-ad64-a7431739c035.png">


<img width="1368" alt="image" src="https://user-images.githubusercontent.com/25161793/226414401-dac2a326-5523-418c-b0c5-f58e2684b893.png">

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/25161793/226414406-599afd8c-d847-4f76-bd65-039f82664c8d.png">

There's a CH.1.1 on C193T, C21811T branch with CH.1.1.5 etc. Mostly Sweden and Germany, 124 sequences, could be designated

<img width="1452" alt="image" src="https://user-images.githubusercontent.com/25161793/226415136-48295a67-17d0-495d-9ed6-7afdeb600942.png">

Then there is a 21811 branch which has quite some interesting sublineages, one is 613H and 215G. I'll designate the whole branch, the sublineages can be taken care of later if need be.

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/25161793/226416050-d9b3177a-4bbb-4dbe-9944-cdafb7d16dbb.png">

That should clear it all up. @Outpfmance as you can see it's not as easy as making a query on covspectrum - there are all sorts of things that need to be checked - it helps if you include screenshots of the lineages, not just links, as the link to Usher expires. Also the Nextclade reference tree is often useful to know where on the tree you are (it's sometimes not 100% correct when there's homoplasy but can be a good guide, as in this case, see screenshot above, here's the link: https://next.nextstrain.org/staging/nextclade/sars-cov-2/21L?branchLabel=aa)
