### ISSUE TITLE
XAY.1.1.1 sublineage with nuc:C8140T (>160 seq, Germany, Austria, Japan, etc.)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1754]
Things have become clearer about what's going on inside the XAY.1.1.1 branch that starts on S:D1153Y. There is a main subbranch that starts on ORF1a:P1640S and a minor Spanish one that starts on ORF3a:L65F.
![XAY 1 1 1](https://user-images.githubusercontent.com/115189228/224581025-a186027a-5e2b-4858-bc69-3a7bea5f467b.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_b89d_e5b890.json?c=country&label=id:node_8823183
For the ORF1a:P1640S branch, most recent sequences are on the German and Austrian subbranch that starts on nuc:C8140T.
Although there are only 12 sequences for now, the ORF3a:L65F branch has showed up in four provinces of Spain, and there is one in Italy as well.
![1](https://user-images.githubusercontent.com/115189228/224581528-14ca595d-0a54-4265-a417-1476de9f9484.png)
![2](https://user-images.githubusercontent.com/115189228/224581591-cf58bceb-ad3a-412f-943b-fd173ffe49b9.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXAY.1.1.1*&

**Comment by oobb45729** [comment]
The ORF3a:L65F has 16 sequences now, 14 in Spain and 2 in Italy.

**Comment by oobb45729** [comment]
I said "split" because all XAY.1s that have S:D1153Y so far have either ORF1a:P1640S or ORF3a:L65F. You are right. "Split" may be not the right word here. Yes, I'm propose two sublineages but I'm not sure whether they should be XAY.1.1.1.1 and XAY.1.1.1.2 or XAY.1.1.1 and XAY.1.1.2. There's a chance that they gained S:D1153Y independently.

**Comment by oobb45729** [comment]
How about designating XAY.1.1.1+nuc:C8140T as XAY.1.1.1.1? nuc:C8140T is related to the spread and the surge of this lineage in Germany. C8140T is also in BA.4.6. Coincidentally or not, this lineage picked up all 3 mutations of BA.4.6 over BA.4+S:N658S, C8140T, C14599T, and S:R346T.

**Comment by InfrPopGen** [comment]
Thank you for proposing this as a lineage. This one seems to have kept steady at around 80% of its parent, and is currently 100% of XAY.1.1.1 worldwide (and in Europe), and it is interesting in terms of the mutations it has acquired. Nevertheless, it has never shown any marked growth advantage over XAY.1.1.1, and it's prominence now could be explained by stochastic processes. Consequently, this can be closed as a Pango lineage proposal, as this clade is little distinct from XAY.1.1.1.
