### ISSUE TITLE
XBC.1 with S:L452R, S:R346S (52 seq. as of 2023-03-16, 2 states in Australia: SA, NSW)

### ISSUE THREAD

**Issue by hsnguyen** [cov-lineages/pango-designation#1755]
A sub-lineage of XBC.1 growing in South Australia
### Description
Sub-lineage of: XBC.1
Earliest sequence: 2023-01-17 (hCoV-19/Australia/SA520112/2023|EPI_ISL_17029337)
Most recent sequence: 2023-03-01 (hCoV-19/Australia/NSW-ICPMR-43030/2023|EPI_ISL_17173398)
Countries circulating: Australia (~~12~~ ~~40~~ 52)

### Evidence
![xbc1_452r](https://user-images.githubusercontent.com/7806873/224866417-b12ba371-7c0e-4d3e-84fa-551b5670bd20.png)

### Defining mutations
This sub-lineage has quite a number of private mutations from XBC, I couldn't find clear possible recombinant candidates so this might happens due to saltation? The S:L452R mutation here is CT22916AG, stepwise from XBC.1's S:L452M (C22916A)

According to usher tree above, the branch has:

|   |  |
|--------|---------------------------------------------------------------------------------------|
| nuc    | unique(9):C2334T, G3606T, C8240T, C8782T, C15180T, A22600T, T22917G, C25603T, C28801T |
| ORF1ab | unique(3):A690V, C1114F, H2659Y                                                       |
| S      | unique(2):R346S, L452R                                                                |

My GISAID query: Spike_R346S, Spike_L452R, Spike_F486P
### Genomes
EPI_ISL_16947325, EPI_ISL_17029041-17029042, EPI_ISL_17029044,
EPI_ISL_17029049-17029050, EPI_ISL_17029055, EPI_ISL_17029337,
EPI_ISL_17029339, EPI_ISL_17029343-17029344, EPI_ISL_17173398,
EPI_ISL_17198994, EPI_ISL_17198998, EPI_ISL_17199001-17199005,
EPI_ISL_17199007, EPI_ISL_17199011, EPI_ISL_17199014-17199023,
EPI_ISL_17199025-17199027, EPI_ISL_17199029-17199034, EPI_ISL_17206914,
EPI_ISL_17206917-17206919, EPI_ISL_17206921-17206922, EPI_ISL_17206924,
EPI_ISL_17206928-17206932

**Comment by oobb45729** [comment]
This one is S:L452M(C22916A) then M452R (T22917G) just like XAY. I noticed this one before and thought it might be just a cluster. So it's not? Already over 50 now? That's fast!

**Comment by FedeGueli** [comment]
now there are 40 of this on Gisaid

**Comment by FedeGueli** [comment]
by the way @c19850727 found the first sequence of this one a while ago and highlighted us its stepwise evo to 452R.

**Comment by ryhisner** [comment]
This is really wild. Seems to have exploded out of nowhere. I wish we could get some details on whether these are sequences collected from throughout the community or if they are concentrated around one hospital or long-term care home. There seems to be much more diversity that you would expect for something that seems to have appeared all at once. Perhaps it's been circulating in an undersequenced area for a while?
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/33738461/225170700-5d23a13d-a4a1-4a1b-919c-de06bd5aefe0.png">

**Comment by hsnguyen** [comment]
> This one is S:L452M(C22916A) then M452R (T22917G) just like XAY

Thanks @oobb45729 for clarification, yes it's 2 mutations accumulated within this codon that makes sense

>Seems to have exploded out of nowhere. I wish we could get some details on whether these are sequences collected from throughout the community or if they are concentrated around one hospital or long-term care home

Yeah @ryhisner I'm not sure about sampling strategy in SA neither but the sequencing number has reduced significantly here in Australia, covering only small proportion of positive cases that are very likely coming from healthcare facilities. Will try to check with our colleagues over there

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage XBC.1.6 with 29 newly designated sequences, and 0 updated. Defining mutations C2334T (ORF1a:A690V), G3606T (ORF1a:C1114F), C8240T (ORF1a:H2659Y), C8782T, C15180T, A22600T (S:R346S), T22917G (S:M452R), C25603T, C28801T (following T16986C, T24529C).

**Comment by FedeGueli** [comment]
@corneliusroemer no spike query: G3606T,  C12733T,C2334T finds 109 ( one less has not C12733T, but has orf1b:N498I that is part of one of the main branch of XBC.1.6):
<img width="1157" alt="Schermata 2023-03-29 alle 23 29 39" src="https://user-images.githubusercontent.com/87669813/228672072-9ec111f5-8626-478b-8d4f-1455c50a0caa.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_383a8_4ab960.json?label=id:node_9893246

**Comment by FedeGueli** [comment]
NSPs query: NSP2_A510V, NSP3_C296F,NSP3_H1841Y

**Comment by oobb45729** [comment]
The ORF1b:N498I may be an artifact. It is disproportionate in Australia in multiple lineages comparing to other countries.

**Comment by FedeGueli** [comment]
Thx @oobb45729 it was puzzling me.
