### ISSUE TITLE
CH.1.1 with additional S:P217L, S:T1117I, S:V1264L, N:T24I and N:S232I (23 seqs as of 2023-04-08, UK)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1759]
### Description
**Sublineage of**: CH.1.1
**Earliest sequence**: 2023/01/27 (Denmark)
**Most recent sequence**: 2023/03/07 (UK-England)
**Countries circulating**: Denmark (3/16), UK (13/16)

**Mutations on top of CH.1.1**: C24912T (S:T1117I) > G28968T (N:S232I) > C22212T (S:P217L) > **A3531C (ORF1a:D1089A), A17538G, G25352T (S:V1264L), C28344T (N:T24I)**

**GISAID and Cov-spectrum query**: A3531C, A17538G, G25352T, C28344T

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/225217686-ad94479a-36a3-4b2d-8e5e-fdfb3a917749.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a3f0_139ca0.json?c=gt-nuc_3531&label=id:node_8021552

### Genomes:
EPI_ISL_16856746, EPI_ISL_16856857, EPI_ISL_16866293, EPI_ISL_17032257, EPI_ISL_17178623, EPI_ISL_17178730, EPI_ISL_17182290, EPI_ISL_17182357-17182358, EPI_ISL_17182405, EPI_ISL_17182435, EPI_ISL_17182453, EPI_ISL_17201005, EPI_ISL_17201058, EPI_ISL_17201074, EPI_ISL_17201122

**Comment by FedeGueli** [comment]
19 as today

**Comment by FedeGueli** [comment]
20 as today

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. After a slightly promising start, this clade appears to have lost its momentum. Over the past two months there has been no UK/Europe growth apparent relative growth advantage, and almost no absolute growth. Consequently, this one can be closed for now, but please request re-opening or re-propose should the clade show strong growth again.
