### ISSUE TITLE
Sublineage of B.1.1.7 (Alpha) with spike H681R

### ISSUE THREAD

**Issue by rambaut** [cov-lineages/pango-designation#176]
There is a distinct lineage in `B.1.1.7`with `spike:H681R` (the more basic furin cleavage site mutation seen in `Delta` and `A.23.1`):
<img width="749" alt="image" src="https://user-images.githubusercontent.com/686405/128849010-78bcff6e-31fa-4de2-b62d-a8b774a60307.png">
These have:
ORF1a:A2320V (nsp3:A1502V, nucleotide C7224T)
S:H681R (A23604G)

There are 1857 genomes on GISAID that are assigned as `B.1.1.7` and have `spike:681R` + `nsp3:1502V`.

Given the convergent mutation in the FCS towards the more basic form seen in `Delta` I suggest rapid designation of a sublineage

**Comment by chrisruis** [comment]
Thanks @rambaut, this is now added as Q.4 in [v1.2.57](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.57)
