### ISSUE TITLE
lineage_notes.txt: XBB recomb: BJ.1 + BA.2.75, but alias_key.json: "XBB": ["BJ.1","BM.1.1.1"]

### ISSUE THREAD

**Issue by janko-js** [cov-lineages/pango-designation#1762]
As in the title:

lineage_notes.txt: 
"XBB	Recombinant lineage of BJ.1 and BA.2.75 with breakpoint in S1, found in USA and Singapore, from issue #1058"

but 

alias_key.json: 
"XBB": ["BJ.1","BM.1.1.1"]

It seems that lineage_notes.txt is inconsistent?

**Comment by Mydtlwn** [comment]
BM.1.1.1 is a descendant of Ba.2.75.3. When this pedigree was assigned, there was some discussion and it was decided that the designation of BM.1.1.1 as the basis for regrouping was the better option at the time, given the circumstances. Of course, assigning pedigrees is not always perfect and absolutely correct, and if you have a better solution, you can suggest it if you have a better reason.

**Comment by AngieHinrichs** [comment]
Thank you for point that out @janko-js, I have updated lineage_notes.txt to say BM.1.1.1 instead of BA.2.75.

**Comment by janko-js** [comment]
Thank you @AngieHinrichs ! 
I maintain https://github.com/janko-js/variants_text_tree and seen that the tree didn't match the lineage_notes.txt, 
I would be more than glad if you report in an issue all the errors I've made in the readme there or in the description (I'm quite sure they're obvious to you but I'm an "amateur").
