### ISSUE TITLE
DV.3 sublineage with ORF1a:L681F (>300 seq, mainly UK) and a further sublineage of it with ORF1a:L469F and S:S486P (9 seq, Germany, Israel, UK, Canada, USA)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1764]
For now, over 40% of DV.3 have ORF1a:L681F(C2306T). It is the third nsp2 mutation of the lineage after ORF1a:A427V and E377K. It does not have a clear advantage over DV.3 though.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ADV.3*%26ORF1a%3AL681F&
![1](https://user-images.githubusercontent.com/115189228/225511779-ea794321-d7eb-484a-9a9d-b6263dd54d44.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_b5f_28e2c0.json?c=gt-S_486&label=id:node_8045020
![2](https://user-images.githubusercontent.com/115189228/225511996-cf3b9867-15aa-4256-b8e1-d002d13b58c9.png)
There is also a sublineage of DV.3+ORF1a:L681F that further acquired ORF1a:L469F(C1670T) and S:S486P(T23018C).
![3](https://user-images.githubusercontent.com/115189228/225512727-d4f82f41-0541-4d2b-b53d-3ffa0ebeeb5c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_b5f_28e2c0.json?c=gt-S_486&label=id:node_8045338
There are only 3 sequences so far but they are in 3 countries with some diversity.
ORF1a:L469F would be the fourth nsp2 mutation of the lineage. It is also in #1712.

**Comment by oobb45729** [comment]
One more with ORF1a:L681F+S:S486P in UK.

**Comment by InfrPopGen** [comment]
Thank you for proposing this as a lineage. At the moment this is showing relative growth disadvantages relative to its parent, over the past three months, and more so over two months, i.e. the disadvantage gap is not closing. As this appears to be a large and not particularly fast growing clade among DV.3s, this can be closed for now. Please request a re-opening should this one show a marked change in these trends.
