### ISSUE TITLE
Potential XBB.1 sublineage with S:F486P(T23018C) and further S:E554K(G23222A) (47seqs)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1765]
Defining mutations: XBB.1>C541T>T21363C>A10042G, T23018C (S:F486P) >G23222A (S: E554K) 

GISAID query: G23222A, T23161C, T23018C, A10042G
Earliest seq: 2023-01-24 (USA, EPI_ISL_16860579)
Most recent seq: 2023-03-09 (Pakistan, EPI_ISL_17202412)
Countries detected: USA (16), Pakistan (8), Australia (6), UK (5), Malaysia (3), Isarel (2), Japan (2), France (1), Italy (1), Canada (1), Denmark (1), Spain (1)

Usher Tree:
![QQ截图20230316141729](https://user-images.githubusercontent.com/121703496/225537842-516a4154-8b2d-4601-ab55-2084acde3cfd.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1037f_1e1410.json
Description: 
I found this potential XBB.1*+F486P sublineage together with #1704 and #1712, but its growth rate was relatively low until recently. Since 13/47 of samples have been updated in last three days, I decide to propose the issue to discuss.

I wonder whether the XBB.1*+F486P+X (including XBB.1.9*+F486P+X) branches could be discussed as #1510.

Genomes:
EPI_ISL_16860579, EPI_ISL_16925127, EPI_ISL_17008441, EPI_ISL_17015546, EPI_ISL_17015547, EPI_ISL_17023243, EPI_ISL_17027713,
EPI_ISL_17030084, EPI_ISL_17045327, EPI_ISL_17045342, EPI_ISL_17051170, EPI_ISL_17051172, EPI_ISL_17051178, EPI_ISL_17051209, EPI_ISL_17058108, EPI_ISL_17065061, EPI_ISL_17094816, EPI_ISL_17120854, EPI_ISL_17132330, EPI_ISL_17150352, EPI_ISL_17154266, EPI_ISL_17155512, EPI_ISL_17162421, EPI_ISL_17170023, EPI_ISL_17170029, EPI_ISL_17170332, EPI_ISL_17173580, EPI_ISL_17173676,
EPI_ISL_17178457, EPI_ISL_17180652, EPI_ISL_17180917, EPI_ISL_17182552, EPI_ISL_17187112, EPI_ISL_17188248, EPI_ISL_17188387, EPI_ISL_17188509, EPI_ISL_17190743, EPI_ISL_17190747, EPI_ISL_17191096, EPI_ISL_17192754, EPI_ISL_17202412, EPI_ISL_17202797, EPI_ISL_17204267, EPI_ISL_17205124, EPI_ISL_17205128, EPI_ISL_17208732, EPI_ISL_17208736

**Comment by FedeGueli** [comment]
Hi @HynnSpylor already this has been already proposed in #1680

**Comment by HynnSpylor** [comment]
@FedeGueli Ah it’s my fault. Very sorry for it and I'll close it immediately. 
(Thx for your advice these days!)

**Comment by corneliusroemer** [comment]
It's XBB.1.19.1 now
