### ISSUE TITLE
XBB.1.5 sublineage with S:I410V, S:P521S, C21910A, and C920T first detected in Germany (91 good and 97 total seqs as of 2023-03-16; Germany, Austria, the Netherlands, other Europe, North America, Singapore, Australia)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1768]
There may be a XBB.1.5 sublineage with S:I410V (A22790G), S:P521S (C23123T), C21910A, C920T first detected in Germany.

As of 2023-03-16, Cov-Spectrum reports 91 good-quality (97 total) XBB.1.5+S:410V+S:521S+21910A+920T sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXBB.1.5+%26+S%3AI410V+%26+S%3AP521S+%26+C21910A+%26+C920T&nextcladeQcOverallScoreTo=29&

As of 2023-03-16 and, CoV-Spectrum estimates a growth advantage for this lineage of 59% (confidence interval 36-82%) over XBB.1.5 in Europe. Note that Europe has been used for growth data since significant numbers of sequences are spread across Germany (34), Austria (23), and the Netherlands (18) with no one country having enough data alone for even a mediocre growth rate estimate.
![Growth_XBB 1 5+S_410V+S_521S+21910A+920T_vs_XBB 1 5_Europe](https://user-images.githubusercontent.com/88959107/225776845-6ea166b1-9a36-4072-90e5-e2102ba72733.png)
Source: https://cov-spectrum.org/explore/Europe/AllSamples/Past2M/variants?nextcladePangoLineage=XBB.1.5*&aaMutations1=S%3A410V%2CS%3A521S&nucMutations1=21910A%2C920T&nextcladePangoLineage1=XBB.1.5&analysisMode=CompareToBaseline&

As of 2023-03-16, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_XBB 1 5+S_410V+S_521S+21910A+920T](https://user-images.githubusercontent.com/88959107/225776889-52db1ce7-cbb4-4489-9644-df642f1bcbde.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/03/subtreeAuspice1_genome_CoV-Spectrum_XBB.1.5%2BS_410V%2BS_521S%2B21910A%2B920T.json?c=gt-S_410&label=id:node_8281581

GISAID query: Nucl Mutations (note the last two select for XBB.1.5's S:F486P): A22790G, C23123T, C21910A, C920T, T23018C, T23019C

First GenBank sequence: Germany 2023-01-30 

Most Recent GenBank sequence: Germany 2023-03-10

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum UShER output files for these sequences is available at [Support-XBB.1.5+S_410V+S_521S+21910A+920T.zip](https://github.com/cov-lineages/pango-designation/files/10996671/Support-XBB.1.5%2BS_410V%2BS_521S%2B21910A%2B920T.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-XBB.1.5+S_410V+S_521S+21910A+920T.txt](https://github.com/cov-lineages/pango-designation/files/10996676/gisaid-epi-isl-XBB.1.5%2BS_410V%2BS_521S%2B21910A%2B920T.txt)

**Comment by FedeGueli** [comment]
Hi @alurqu this has been proposed already in #1688 !

**Comment by alurqu** [comment]
My search missed the earlier proposal. I am closing this because it is a duplicate.
