### ISSUE TITLE
Proposal for 2 potential new lineages circulating in South Africa

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#177]
**Proposed new lineage 1**
Currently misclassified as B.1.629, and used to be misclassied as B.1.416 before Pango v.3.1.10 (7 sequences from Nelson Mandela Bay, Eastern Cape, South Africa)
**Earliest sequence:** 2021/4/8
**Most recent sequence:** 2021/4/12 (there's some delay for the sequences from Eastern Cape to appear in GISAID)
**Mutations:**
E: L21F
N: T135I, S187L, T205I
ORF1a: E102V, S166G, T265I, V503L, T1437A, K1655N, K3353R, 3675/3677del
ORF1b: P314L, M991T, R1315C
ORF3a: T32I, S40L
S: T19A, W64R, T95I, K182N, T478K, E484K, D614G, Q957H, T1117I
**Genomes:** EPI_ISL_2727181-2727184, EPI_ISL_2727188, EPI_ISL_3275376, EPI_ISL_3275378
**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/129051459-c0f0a5dd-7d20-46d6-beaa-4de3deeebe9e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_bfd6_3dd320.json?c=gt-S_1117&label=nuc%20mutations:C1059T

**Proposed new lineage 2**
Currently misclassified as B.1.1.34 (48 sequences in South Africa, DRC, Belgium and Japan-EX DRC)
**Earliest sequence:** 2020/12/7 (Cape Town, South Africa)
**Most recent sequence:** 2021/7/19 (Belgium)
**Mutations:**
M: I82T
N: A152S, R203K, G204R, N213I, P344S
ORF1a: T395I, S610L, Q1201H, M3087I, R3164H, 3675/3677del, L3808F
ORF1b: P314L, G1129V
ORF3a: P42H
ORF9b: R32L
S: D138Y, N450K, D614G, P681R
**Genomes:**
EPI_ISL_745141, EPI_ISL_2382207, EPI_ISL_2621053,
EPI_ISL_2621742, EPI_ISL_2662688, EPI_ISL_2693045,
EPI_ISL_2693048, EPI_ISL_2693837-2693838, EPI_ISL_2693844,
EPI_ISL_2693846-2693848, EPI_ISL_2693882, EPI_ISL_2695836,
EPI_ISL_2695855, EPI_ISL_2710296, EPI_ISL_2727190,
EPI_ISL_2727207, EPI_ISL_2727211, EPI_ISL_2727231,
EPI_ISL_2727330, EPI_ISL_2727367, EPI_ISL_2770472,
EPI_ISL_2802107-2802108, EPI_ISL_2812361, EPI_ISL_2812388,
EPI_ISL_2812437, EPI_ISL_2876943, EPI_ISL_2893249,
EPI_ISL_2893272, EPI_ISL_2930783, EPI_ISL_2942280,
EPI_ISL_2955473, EPI_ISL_2955491, EPI_ISL_2956599,
EPI_ISL_2966654, EPI_ISL_2966656-2966657, EPI_ISL_2988403,
EPI_ISL_2988413, EPI_ISL_2988416, EPI_ISL_3032512,
EPI_ISL_3100120, EPI_ISL_3100123, EPI_ISL_3161795,
EPI_ISL_3275351
**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/129055878-b3ae6da6-52e9-4a76-921a-c26bd54b4633.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ee38_3e5f50.json?c=gt-N_152

**Comment by chrisruis** [comment]
Thanks @c19850727. We've added your proposed new lineage 2 as B.1.1.528 in [v1.2.64](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.64). It looks like there's 1 sequence in B.1.1.528 that was previously designated B.1.1.34. Also, B.1.1.528 and B.1.1.34 appear to have convergently acquired G16853T (Orf1ab:G5530V). So this is potentially why this clade was being mis-assigned B.1.1.34.

We wouldn't normally designate a new lineage if it would be unobserved (not seen in >3 months) at the time of designation. So we therefore haven't designated your proposed lineage 1 at this stage

**Comment by c19850727** [comment]
@chrisruis Hi Chris, It seems that there are now 2 more recent sequences related to proposed lineage 1.

They are EPI_ISL_3339536 and EPI_ISL_3394321, both sequenced in August, in New York, the US.

![image](https://user-images.githubusercontent.com/86835836/131219436-949448ce-d484-4495-b8be-9dd1304e80df.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26b09_a09770.json?c=gt-S_95,478&label=nuc%20mutations:C21846T

**Comment by chrisruis** [comment]
Thanks @c19850727. We need new lineages to be epidemiologically distinct. From your tree, while the new USA sequences and the South Africa sequences are in a single clade, they seem to be quite different. Additionally, both clades are still very small. So it doesn't seem that this forms a reasonably sized epidemiologically distinct cluster at this stage
