### ISSUE TITLE
LINEAGE DETERMINATION ISSUE

### ISSUE THREAD

**Issue by noutin2020** [cov-lineages/pango-designation#1770]
After analysing the Whole Genome Sequence of a positive SARS-CoV-2 sample collected on 31/01/2023,
I determined the lineage of the strain using both Nexclade and Pangolin
**The Output of Nexclade was: XBB.1.**

**The Output of Pangolin was: XBB.1.5(1/1)** with the following note:
**scorpio lineage BA.2 conflicts with inference lineage XBB.1.5,4.2,v1.18.1.1**

How can I interpret this note and make final decision on the lineage of this variant?

Your various responses will be highly appreciated!
I look forward to hearing from you.

Regards,
Noutin

**Comment by corneliusroemer** [comment]
Hi @noutin2020, it can happen that Usher and Nextclade show somewhat different results. In this case, the difference between XBB.1 and XBB.1.5 is small and depends on just a single to a few nucleotide substitutions.

When the sequence is incomplete (having some Ns), it is possible that the exact lineage cannot be determined with certainty. Likewise, sometimes there are bioinformatic analysis artefacts that can make it difficult for the algorithms to be certain about which exact lineage it is.

If you share the sequence I could have a look and see why the two tools disagree (slightly).

Based on the sampling date and location you provided, it is quite likely that the sample is XBB.1.5 (or another XBB with S:F486P), see covSpectrum graphic showing proportion of XBB* that is XBB.1.5 in Africa in the past 3 months:

![image](https://user-images.githubusercontent.com/25161793/225958657-3fb41781-f9e5-461e-ade7-885c559aa9ee.png)
https://cov-spectrum.org/explore/Africa/AllSamples/Past3M/variants?nextcladePangoLineage=XBB*&nextcladePangoLineage1=XBB.1.5*&analysisMode=CompareToBaseline&

**Comment by noutin2020** [comment]
> Hi @noutin2020, it can happen that Usher and Nextclade show somewhat different results. In this case, the difference between XBB.1 and XBB.1.5 is small and depends on just a single to a few nucleotide substitutions.
> 
> When the sequence is incomplete (having some Ns), it is possible that the exact lineage cannot be determined with certainty. Likewise, sometimes there are bioinformatic analysis artefacts that can make it difficult for the algorithms to be certain about which exact lineage it is.
> 
> If you share the sequence I could have a look and see why the two tools disagree (slightly).
> 
> Based on the sampling date and location you provided, it is quite likely that the sample is XBB.1.5 (or another XBB with S:F486P), see covSpectrum graphic showing proportion of XBB* that is XBB.1.5 in Africa in the past 3 months:
> 
> ![image](https://user-images.githubusercontent.com/25161793/225958657-3fb41781-f9e5-461e-ade7-885c559aa9ee.png) https://cov-spectrum.org/explore/Africa/AllSamples/Past3M/variants?nextcladePangoLineage=XBB*&nextcladePangoLineage1=XBB.1.5*&analysisMode=CompareToBaseline&

Hello @corneliusroemer,
Thank you so much for your clarifications.
The outputs of Usher and Nexclade are the same.
This sequence was deposited in GISAID and the accession number is EPI_ISL_17182746.
The genome of this strain contains only 9 missing nucleotides and its length is 29491. Should this be considered as incomplete genome? I do not think so because the strain EPI_ISL_172407715 contains 604 Ns and was classified as XBB.1.5. 

In addition, it has S:F486P mutation.
https://www.epicov.org/epi3/frontend#1903dc

Since you mentioned that it could be another XBB with S:F486P, which one could it be?
Below is the accession number of the sequence as requested:
EPI_ISL_17182746

I look forward to hearing from you.

![image](https://user-images.githubusercontent.com/69206657/226111331-3db514ae-57ba-45f4-be63-2bc9ea4187b1.png)

**Comment by FedeGueli** [comment]
> > Hi @noutin2020, it can happen that Usher and Nextclade show somewhat different results. In this case, the difference between XBB.1 and XBB.1.5 is small and depends on just a single to a few nucleotide substitutions.
> > When the sequence is incomplete (having some Ns), it is possible that the exact lineage cannot be determined with certainty. Likewise, sometimes there are bioinformatic analysis artefacts that can make it difficult for the algorithms to be certain about which exact lineage it is.
> > If you share the sequence I could have a look and see why the two tools disagree (slightly).
> > Based on the sampling date and location you provided, it is quite likely that the sample is XBB.1.5 (or another XBB with S:F486P), see covSpectrum graphic showing proportion of XBB* that is XBB.1.5 in Africa in the past 3 months:
> > ![image](https://user-images.githubusercontent.com/25161793/225958657-3fb41781-f9e5-461e-ade7-885c559aa9ee.png) https://cov-spectrum.org/explore/Africa/AllSamples/Past3M/variants?nextcladePangoLineage=XBB*&nextcladePangoLineage1=XBB.1.5*&analysisMode=CompareToBaseline&
> 
> Hello @corneliusroemer, Thank you so much for your clarifications. The outputs of Usher and Nexclade are the same. This sequence was deposited in GISAID and the accession number is EPI_ISL_17182746. The genome of this strain contains only 9 missing nucleotides and its length is 29491. Should this be considered as incomplete genome? I do not think so because the strain EPI_ISL_172407715 contains 604 Ns and was classified as XBB.1.5.
> 
> In addition, it has S:F486P mutation. https://www.epicov.org/epi3/frontend#1903dc
> 
> Since you mentioned that it could be another XBB with S:F486P, which one could it be? Below is the accession number of the sequence as requested: EPI_ISL_17182746
> 
> I look forward to hearing from you.
> 
> ![image](https://user-images.githubusercontent.com/69206657/226111331-3db514ae-57ba-45f4-be63-2bc9ea4187b1.png)

Hi the one on left is XBB.1.5 , the other on the right is part of a fast undesignated lineage that emerged in africa proposed in #1712

**Comment by corneliusroemer** [comment]
It's an XBB.1 with S:F486P - but without the T17124C usually found in XBB.1.5 (though not in 100%). So it _could_ be XBB.1.5, but could also be an independent acquisition of S:F486P. 

Nextclade calls it XBB.1.5 because it does fit the broad definition: XBB.1 + S:F486P. Though this could be a false positive.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/25161793/226118734-4542173a-a91c-4dfa-8243-f2eeec2159a1.png">

Usher finds this in a cluster of XBB.1 with S:F486P that is not labelled XBB.1.5. I'll have to study this part of the tree more closely to see whether this should be XBB.1.5 or is a genuinely independent XBB.1 + S:F486P. There could already be an issue for this.

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/25161793/226118946-2584a4a3-b358-4380-9838-38e234b2e080.png">

https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5ec3d_5e4250.json

**Comment by FedeGueli** [comment]
@corneliusroemer it is part of #1712

**Comment by FedeGueli** [comment]
>
> 
> @FedeGueli, about your strong recommendation
> Is it a general recommendation or specific to this sequence?
> 
> How can this designation be done?

It was a message for Cormelius, only the pango team could do designations, and designations are always about a lineage not a singlet sequence as stated in #1 .

By the way now it has been designated XBB.1.17.1 so your sequence on the right belongs to this lineage.

**Comment by noutin2020** [comment]
Thank you for concluding nicely this discussion.

Let's keep in touch!

**Comment by AnonymousUserUse** [comment]
@noutin2020 
Here "false positive" means, Nextclade assigns this sequence as XBB.1.5 but it does not real XBB.1.5. It refers to the algorithm of assigning PANGO lineage, not to the PCR test.

**Comment by noutin2020** [comment]
Ok. Rather sequencing run (not PCR). Thanks
