### ISSUE TITLE
BA.5.2.6 sublineage with S:Q183P(A22110C) mainly in Japan (160seqs)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1771]
Defining mutations: BA.5.2.6>A22110C (S:Q183P)
GISAID query: Spike_R346T, Spike_Q183P, C16616A, C27012T, C27513T
Cov-spectrum query: BA.5.2.6+ S:Q183P
Earliest seq: 2022-09-25 (Japan, EPI_ISL_15230909)
Most recent seq: 2023-02-24 (Japan, EPI_ISL_17213925)
Countries Detected: Japan(157), Denmark (2), Pakistan (1)

Usher Tree: (assigned as BA.5.2?)
![QQ截图20230317204254](https://user-images.githubusercontent.com/121703496/225908370-909a4b17-a214-4c77-8ed6-e82664f6a19f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_13fcf_45a290.json

Description:
A BA.5.2.6 sublineage that highly concentrated in Japan. It still spreads and has slightly advantage to its parent lineage (BA.5.2.6). 
![QQ截图20230317202622](https://user-images.githubusercontent.com/121703496/225908484-180447d7-0626-46bb-a53f-330d610d0944.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=BA.5.2.6*&aaMutations1=S%3AQ183P&nextcladePangoLineage1=BA.5.2.6*&analysisMode=CompareToBaseline&

S:Q183P, which is also observed in some CH.1.1* and BQ.1* lineages, may increase fitness by Bloom calculator 
(https://jbloomlab.github.io/SARS2-mut-fitness/S.html)
![QQ截图20230317204056](https://user-images.githubusercontent.com/121703496/225908595-0bc40930-ed23-4e48-ba26-752c923590cf.png)

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. Although it showed slight early promise, it has shown a relative growth disadvantage over the past two months, and few new detections since proposal. Consequently, this can be closed for now. Please re-propose or request re-opening should the situation change markedly.
