### ISSUE TITLE
Potential mini-saltation on a BA.5.2/BF.7.14.1 recombinant with additional S:M153I, orf1b:P976L, orf7a:V104F in Henan(4 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1777]
Seqs:
 EPI_ISL_17026202(2023-2-14, Henan)
EPI_ISL_17243396(2023-2-27,Henan)

GISAID query: Spike_V83F,Spike_M153I,Spike_R346T

Mutations on top of BA.5.2: S:R346T, Orf1a:V274L, Orf1b: L238F, C7528T (BF.7.14 defining mutation excluding S:C1243F and orf7a:H47Y)

This forms a "BA.5.2" branch full of different BA.5.2*/BF.7.14* recombinants on usher.

Branch-specific mutations: A3872G(orf1a:I1203V), A8967C(orf1a:K2901T),  G21809T(S:V83F)  (Possibly come from the S:V83F branch on BF.7.14.1 )
Private mutations:
C13806T, C16394T(orf1b:P976L), G21255T, G22021C(S:M153I), G27703T(orf7a:V104F) 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_ca61_7eecf0.json)

<img width="1395" alt="Screen Shot 2023-03-20 at 13 33 54" src="https://user-images.githubusercontent.com/10445944/226260187-2abf8656-0236-4064-b7c1-5c06b6c4542d.png">

S:M153I is also in 
#796 BE.1.3
#1402 BQ.1.1.32

**Comment by aviczhl2** [comment]
3 seqs now.

**Comment by aviczhl2** [comment]
4 seqs now. 
All 4 seqs are from Xinyang, the age is all 63, however, 3 are female and 1 is male, so it's not the same person.

**Comment by corneliusroemer** [comment]
Why do you think these are recombinants? They could just be bad quality sequences? Please elaborate on the evidence for recombination as opposed to dropout/artefact

**Comment by aviczhl2** [comment]
Supplement information for BA.5.2/BF.7.14 recombinant tree. (from #1811）

![image](https://user-images.githubusercontent.com/10445944/227994555-1c0c58a8-c381-4ec0-8eb9-2353dfb94e28.png)

The top branch of the "undesigned BA.5.2" is more likely a collection of multiple different BA.5.2.48(49,50)/BF.7.14 recombinants.

C7528T,S:R346T is for BF.7
orf1b:L238F and orf1a:V274L for BF.7.14

Also no orf1b:T1050N as it is BF.7 before S.

missing S:1243F and orf7a:H47Y and A27038G, suggesting the breakpoints (of that collection) are between S:346 and S:1243, so it is BA.5.2.x after S:1243.

Given that a billion people get infected in one month with ~25% BF.7.14, ~65% BA.5.2.48, ~10% BA.5.2.49/50, there shall be many many independent recombinants, and those recombinants shall look alike because they are all under BA.5.2 backbone.

Any single recombinant is too small, while the collection as a whole seems to have a small growth advantage against both BA.5.2.48 and BF.7.14. (but still too few seqs)

<img width="1384" alt="Screen Shot 2023-03-27 at 21 18 23" src="https://user-images.githubusercontent.com/10445944/227994218-657f54c6-9929-4fe6-80b7-c294314b0eaf.png">

<img width="1343" alt="Screen Shot 2023-03-27 at 21 18 42" src="https://user-images.githubusercontent.com/10445944/227994184-c02ff9f3-13a7-438f-8b44-6057e45c338f.png">

**Comment by FedeGueli** [comment]
there is also another DY.4 sublinegae which gained S:V83F and S:;R346T wondering if this lineage is involved . https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_8f0c_182b40.json?f_userOrOld=uploaded%20sample&label=id:node_7225366
<img width="1159" alt="Schermata 2023-03-27 alle 21 11 25" src="https://user-images.githubusercontent.com/87669813/228042829-bfe62aba-c301-45ae-8831-354cae93f730.png">

**Comment by aviczhl2** [comment]
> there is also another DY.4 sublinegae which gained S:V83F and S:;R346T wondering if this lineage is involved . https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_8f0c_182b40.json?f_userOrOld=uploaded%20sample&label=id:node_7225366 <img alt="Schermata 2023-03-27 alle 21 11 25" width="1159" src="https://user-images.githubusercontent.com/87669813/228042829-bfe62aba-c301-45ae-8831-354cae93f730.png">

Nice catch. 

Given that it has orf1b:I2432T reversion I guess it is more likely a sandwich recombination with BF.7.14.1 ? (with breakpoint 1 between 17208 and orf1b:2432 and breakpoint 2 between S:346 and S:1243)?

**Comment by FedeGueli** [comment]
Yes that was my guess too thanks for looking into it

**Comment by aviczhl2** [comment]
> there is also another DY.4 sublinegae which gained S:V83F and S:;R346T wondering if this lineage is involved . https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_8f0c_182b40.json?f_userOrOld=uploaded%20sample&label=id:node_7225366 <img alt="Schermata 2023-03-27 alle 21 11 25" width="1159" src="https://user-images.githubusercontent.com/87669813/228042829-bfe62aba-c301-45ae-8831-354cae93f730.png">

There is one more sequence of this on GenBase, C_AA002333, and it is from Bozhou, Anhui, which is a distance to Henan. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_2d59e_f852b0.json?branchLabel=Spike%20mutations&label=id:node_7246440&showBranchLabels=all)
<img width="1377" alt="Screen Shot 2023-04-07 at 11 34 12" src="https://user-images.githubusercontent.com/10445944/230535685-89eee20e-494a-4810-9c51-26420a8fcd64.png">

**Comment by aviczhl2** [comment]
Close down this as no seqs from GenBase belongs to this one.
