### ISSUE TITLE
XBB.2.3 with ORF1a:M3862I, S:P1263R and ORF8:Y42C from New Zealand (29 seqs as of 2023-04-11)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1779]
### Description
**Sublineage of**: XBB.2.3
**Earliest sequence**: 2023/02/27 (New Zealand)
**Most recent sequence**: 2023/03/11 (New Zealand)
**Countries circulating**: New Zealand

**Mutations on top of XBB.2.3**: C12525T >  G11851T (ORF1a:M3862I), T18669C, C25350G (S:P1263R), A28018G (ORF8:Y42C)

**GISAID and Cov-spectrum query**: G11851T, T18669C, C25350G, A28018G

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/226561473-da330a60-b708-46d0-8acf-ff4d671a46e0.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20025_972210.json?c=gt-nuc_11851&label=id:node_7819289

### Genomes:
EPI_ISL_17251979, EPI_ISL_17252183, EPI_ISL_17252345, EPI_ISL_17252483, EPI_ISL_17252530-17252537, EPI_ISL_17252541, EPI_ISL_17252545, EPI_ISL_17252548

**Comment by c19850727** [comment]
18 sequences as of 2023-03-30. Newly found in Canada-QC, US-RI and US-TX.

**Comment by c19850727** [comment]
26 seqs as of 2023-04-08. Newly found in Australia-VIC.

**Comment by c19850727** [comment]
29 Seqs as of 2023-04-11. Newly found in US-NY and US-HI.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. Although it is still slowly accumulating detections, it has been showing a marked relative decline over the past two months in NZ/Australia and world wide, and relatively low absolute detected growth, this can be closed for now; however, please request re-opening or re-propose should the situation change markedly.
