### ISSUE TITLE
New C.X lineage associated with South America/Caribbean with conserved Spike mutations: P9L, R190K, L452Q, P479S

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#178]
**New proposed lineage
By Tom Peacock**

**Description**
**Sub-lineage of:** B.1.1.1
**Earliest Sequence:** 2021-02-16
**Latest Sequence:** 2021-07-03

**Countries circulating:** Chile (6 genomes), Peru (2 genomes), Dominican Republic (1 genome)

**Description:**
Conserved Spike mutations - P9L,  R190K L452Q, P479S, D614G

Conserved non-Spike mutations - NSP3 – T428I, H682Y, T1336I, T1465I, N1543K; NSP4 – L438P; NSP5 – G15S; NSP6 – L125F; NSP12 – P323L, A382V, A585D; ORF3a – S216P; E – A41V; N – I157V, R203K, G204R

Interesting little clade that appears to be a cousin to C.37

**Genomes:**
[SouthAmericanCaribbeanCX.txt](https://github.com/cov-lineages/pango-designation/files/6974487/SouthAmericanCaribbeanCX.txt)

**Evidence:** 

![image](https://user-images.githubusercontent.com/79373149/129177644-37642ad8-a5f7-4da6-b85f-bed0c1727b34.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_124de_4ee380.json?c=pango_lineage

**Proposed lineage name:** C.X

**Comment by thomasppeacock** [comment]
Few more genomes (1x Peru, 4x Chile) that fit the definition uploaded since the initial issue:
Peru:
EPI_ISL_3375992
Chile:
EPI_ISL_3368907
EPI_ISL_3368906
EPI_ISL_3368905
EPI_ISL_3365100

**Comment by chrisruis** [comment]
Thanks @thomasppeacock for submitting. We've added this as C.39 in [v1.2.62](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.62)
