### ISSUE TITLE
New BF.7.14 sublineage with S:R403K and S:K440R arose in China 3 seqs

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1780]
I casually re spotted a new chinese sublineage of BF.7.14with two very interesting mutations S:R403K,S:N440R 
**EDITED:**
**that was before spotted and tracked by @c19850727 (Sorry for spoiling!)**

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a8ec_9dbb80.json?label=id:node_6668344
<img width="1161" alt="Schermata 2023-03-21 alle 17 34 22" src="https://user-images.githubusercontent.com/87669813/226678153-b7b834e2-c555-4321-b6c5-2fa693a819b0.png">

Defining mutations:
BF.7.14>A21282G >S:N440R (A22881G), S:R403K (G22770A)

Sequences: 3 collected in the first half of February
EPI_ISL_17031862 (From Hebei this sample has Orf7a:H47Y reverted to H), EPI_ISL_17199740  and EPI_ISL_17199743
(both from Heilongjiang)

Overall composite fitness of this sublineage seems boosted a lot by these two mutations:
<img width="866" alt="Schermata 2023-03-21 alle 17 41 58" src="https://user-images.githubusercontent.com/87669813/226680502-b87011b7-2b3d-4968-a5e0-ccab16c6d651.png">

Gisaid query: Spike_R403K,Spike_N440R,NS7A_H47Y

**Comment by aviczhl2** [comment]
Why is it on a orf7a:Y47H reversion branch? 

Is there a possibility that there's some form of recombination with BA.5.2.48 after S(which doesn't have mutations after 17208, effectively reverting the orf7a:H47Y) in Beijing and Hebei , while the Heilongjiang sequence gains these 2 S-mutations independently?

**Comment by FedeGueli** [comment]
No new sequence of this one. I archive it for now

**Comment by aviczhl2** [comment]
> No new sequence of this one. I archive it for now

Both Heilongjiang and Hebei haven't uploaded any samples since your proposal. No sequence no variants.
