### ISSUE TITLE
XBB.1.5 with S:ins681ASA = pseudo S:P681A (29 seq. Germany, Austria)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1785]
Proposal for a sublineage of XBB.1.5
Earliest sequence: 23.01.2023 (Germany)
Countries detected: Germany

Defining mutation:
S:ins681ASA -> GCCAGCGCG insert after the 681 CAT codon coding for H
(this looks like a S:P681A in Nextcalde vs Wuhan and GISAID even though it apparently has S:P681H)

![grafik](https://user-images.githubusercontent.com/102166254/233560391-e895ea01-cdc9-4108-a146-a0ed2225de49.png)

Gisaid query: Spike_P681A

This potential sublineage of XBB.1.5 is defined by an AA insertion after 678 and A23604G apparently resulting in S:P681A. The sequences look relatively clean but do not cluster well in usher probably because of the insertion. The sequences originate from two different submitting labs (RKI and LGL) in Germany (Bavaria, Saxony, Thuringia).

![grafik](https://user-images.githubusercontent.com/102166254/226835434-a9d77417-c3bc-447f-84a0-8498d3fe9dc6.png)

![grafik](https://user-images.githubusercontent.com/102166254/226845778-ebaf3da4-c83a-4e74-b7ee-b75d68f1706a.png)

![grafik](https://user-images.githubusercontent.com/102166254/226845878-cae8d2ad-61ee-410c-9747-07d870c0c7e5.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AP681A&

EPI_ISL_16882495, EPI_ISL_16914130, EPI_ISL_16939949,
EPI_ISL_16941229, EPI_ISL_16941563, EPI_ISL_16941570,
EPI_ISL_17005523, EPI_ISL_17006098, EPI_ISL_17006211,
EPI_ISL_17176244, EPI_ISL_17254674, EPI_ISL_17254723,
EPI_ISL_17254805, EPI_ISL_17255469, EPI_ISL_17263374,
EPI_ISL_17263782, EPI_ISL_17263846

**Comment by FedeGueli** [comment]
@thomasppeacock 
so it should be YQTQTKSHASARRARS did i get it right?

**Comment by agamedilab** [comment]
Hi @thomasppeacock, yes you are right. Apparently there is a GCCAGCGCG insert after the 681 CAT codon coding for H. This somehow messes with Nextclade displaying P681A (even though the CAT codon remains unchanged).

![grafik](https://user-images.githubusercontent.com/102166254/226902416-2cb53ee7-8b91-450d-a18e-2533449e04a6.png)

**Comment by thomasppeacock** [comment]
@FedeGueli - exactly right.

@agamedilab - I think this is probably due to nextclade using the Wuhan-hu-1 has a reference strain rather than XBB.1.5 and getting in a muddle with what are existing polymorphisms vs the novel insertion.

**Comment by corneliusroemer** [comment]
Haven't looked at the sequences but being from two labs: LGL and RKI means this is probably real. Germany has quite some quality issues often with reversions but this seems to not be one. Would be good to wait for more sequences, ideally one from abroad.

**Comment by AnonymousUserUse** [comment]
Starting with nuc:23603 aka S:681
Variant | Nucleotide | Amino acid
--- | --- | ---
Wild type | CCT | P
XBB/XBB.1.5 | CAT | H 
this issue | CATGCCAGCGCG | HASA

It is strange that Nextclade demonstrates S:P681A in this case.

**Comment by agamedilab** [comment]
+1 from Germany (LGL): EPI_ISL_17274314

**Comment by agamedilab** [comment]
+1 from Germany (RKI): EPI_ISL_17296522

**Comment by agamedilab** [comment]
+1 from a different country (Austria, Carinthia): EPI_ISL_17328443 @corneliusroemer 

![grafik](https://user-images.githubusercontent.com/102166254/228745620-81d3eecf-d8c1-4f3b-9392-adcbd7661d5a.png)

**Comment by agamedilab** [comment]
+2 Germany: EPI_ISL_17349298, EPI_ISL_17349294

**Comment by thomasppeacock** [comment]
another couple from Germany a few days back: EPI_ISL_17406294, EPI_ISL_17407330

Reckon this might be worth assigning due to the interesting location of the insertion and continuing finding of new sequences (including one from Austria)

**Comment by agamedilab** [comment]
27 seq as of 21.04.23.

**Comment by corneliusroemer** [comment]
Can't designate as there's no defining nuc substitution for this lineage (assuming insertion happened once)

The insertion appears to have happened directly on XBB.1.5 + T10204C

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/25161793/233794227-f1d64cdb-0ecb-44cc-b48d-0009bf88d0c2.png">

**Comment by agamedilab** [comment]
+1 Sweden: EPI_ISL_17565270

**Comment by corneliusroemer** [comment]
German sequences often have reversions artefacts - unlikely to be true ones
