### ISSUE TITLE
BQ.1.1.38 sublineage with S:T478R (C22995G) (97seqs, mainly in South Africa and Germany)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1786]
Defining mutations: BQ.1.1.38>T4579A>A22110C (S:Q183P)
GISAID query: Spike_R346T, Spike_N856S, Spike_T478R, Spike_P251L, T4579A
Cov-spectrum query: BQ.1.1.38+S:T478R
Earliest seq: 2022-11-29 (South Africa, EPI_ISL_16567241)
Most recent seq: 2023-02-28 (Germany, EPI_ISL_17255867)
Countries Detected: South Africa (54), Germany (36), Austria (2), New Zealand (2), USA (1), Denmark (1), Zambia (1)
Usher Tree:
![QQ截图20230322204720](https://user-images.githubusercontent.com/121703496/226910300-69acc143-6512-4407-89ba-7462ed4d8032.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24c7e_af3120.json

It also shows certain advantage to its parent lineage (BQ.1.1.38) in Cov-spectrum relative growth rate.
![QQ截图20230322205536](https://user-images.githubusercontent.com/121703496/226910979-b8369f8c-6b08-4cdb-91ac-512a4221ae1f.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=BQ.1.1.38*&aaMutations1=S%3AT478R&nextcladePangoLineage1=BQ.1.1.38*&analysisMode=CompareToBaseline&

Genomes:
[Genomes of BQ1.1.38 sublineage.txt](https://github.com/cov-lineages/pango-designation/files/11040121/Genomes.of.BQ1.1.38.sublineage.txt)

**Comment by FedeGueli** [comment]
i think it was designated last night

**Comment by HynnSpylor** [comment]
@FedeGueli Oh yes, I forgot to refresh the lineage_note.txt. Thx a lot (and I'll prevent similar mistake.)
