### ISSUE TITLE
Proposal for new sub-lineages within P.1

### ISSUE THREAD

**Issue by chrisruis** [cov-lineages/pango-designation#179]
**Proposal for new sub-lineages within P.1**
by Chris Ruis

**Description**
Examination of P.1 within the UShER tree shows a clade downstream of C1427T that was introduced into the USA with substantial onward transmission. This clade was subsequently introduced into Aruba and Mexico independently, in both cases with onward transmission. Propose that the USA clade is designated P.1.10 as the next available sub-lineage of P.1, the Aruba clade is designated P.1.10.1 and the Mexico clade is designated P.1.10.2.

Details of each sub-lineage
**P.1.10 - USA lineage**
Earliest sequence - 26/01/2021 (USA)
Latest sequence - 29/07/2021 (USA)
Countries circulating - USA (2056 sequences) and multiple other countries

**P.1.10.1 - Aruba lineage**
Earliest sequence - 25/04/2021 (Aruba)
Latest sequence - 29/06/2021 (Aruba)
Countries circulating - Aruba (55 sequences)

**P.1.10.2 - Mexico lineage**
Earliest sequence - 17/05/2021 (Mexico)
Latest sequence - 08/07/2021 (Mexico)
Countries circulating - Mexico (23 sequences)

**Genomes**
[P.1.10_sequences.txt](https://github.com/cov-lineages/pango-designation/files/6975221/P.1.10_sequences.txt)

**Evidence**
Tree view of the local P.1 clade coloured by proposed lineage:
![P 1 10](https://user-images.githubusercontent.com/47785131/129192595-1aacff0f-c361-4844-bd4c-19ee3facd18e.png)

**Proposed lineage names**
P.1.10, P.1.10.1 and P.1.10.2

**Comment by chrisruis** [comment]
Added as P.1.10, P.1.10.1 and P.1.10.2 in [v1.2.59](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.59)

**Comment by corneliusroemer** [comment]
The defining mutation for P.1.10.1 vs P.1.10 seems to be: `nuc: C26873T`

**Comment by AngieHinrichs** [comment]
FWIW what I'm [using](https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/utils/otto/sarscov2phylo/pango.clade-mutations.tsv) to annotate P.1.10.1 on the UCSC/UShER tree is P.1.10 + C13329T + C2841T + G4300T + C26873T, although it has been a long time since I looked at the tree to see if that is still the best match for the designated sequences.

**Comment by chrisruis** [comment]
I'd agree C26873T is the defining mutation for P.1.10.1. It looks like the set of mutations Angie is using above is still the best match for P.1.10.1
