### ISSUE TITLE
XBB.1 with S:P521S and S:R403K apparently circulating in Himachal Pradesh , India 12 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1791]
I spotted this little sublienage that may circulate in Himachal Pradesh India, being defined by two mutations expected to increase potentially viral fitness i propose it to keep it monitored while India is surging its sequencing efforts

Tree:
<img width="1120" alt="Schermata 2023-03-23 alle 14 00 53" src="https://user-images.githubusercontent.com/87669813/227212086-89a49bc5-077a-4ca1-a410-c86e15f35b80.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_16efd_c479a0.json?c=userOrOld&label=id:node_7686014

Defining mutations:
XBB.1 >> > C11956T > C26522T > S:P521S (C23123T) >S:R403K ( G22770A)

Gisaid query :   C11956T , C26522T ,C23123T,G22770A

Sequences : 7
hCoV-19/India/HP-NII-1586/2023\|EPI_ISL_17257455\|2023-02-27
India/HP-NII-1568/2023\|EPI_ISL_17096481\|2023-02-17
hCoV-19/India/HP-NII-1608/2023\|EPI_ISL_17257476\|2023-02-28
hCoV-19/India/HP-NII-1607/2023\|EPI_ISL_17257475\|2023-02-28
India/HP-INSACOG-NII-1539/2023\|EPI_ISL_16649090\|2023-01-06
hCoV-19/India/HP-NII-1606/2023\|EPI_ISL_17257474\|2023-02-27
India/HP-NII-1606/2023\|EPI_ISL_17257474\|2023-02-27

**Comment by FedeGueli** [comment]
A couple more of sequences of this sublineage are misplaced on Usher tree in one of that trashbin trees with many reversions. (cc @AngieHinrichs )
https://nextstrain.org/fetch/genome.ucsc.edu/t
<img width="1178" alt="Schermata 2023-03-23 alle 15 05 25" src="https://user-images.githubusercontent.com/87669813/227228723-c404fea6-9ee6-4733-a765-1239150b6fae.png">
rash/ct/subtreeAuspice3_genome_16efd_c479a0.json?label=id:node_9856447

So the total count should be 9.

**Comment by AngieHinrichs** [comment]
Those two sequences have such a high number of reversions that they have been excluded from the tree (they would form a bigger trash-magnet!)  But point taken, that little branch that pulled them in is just XBB > 3 reversions, and is more harm than help in this case.

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs !!

**Comment by FedeGueli** [comment]
10 as today

**Comment by FedeGueli** [comment]
12 as today:
![Schermata 2023-04-10 alle 09 02 51](https://user-images.githubusercontent.com/87669813/230846308-a7fc8578-aa29-4044-b093-42e1b72b2479.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1540f_3b2960.json?c=userOrOld&label=id:node_5827899

**Comment by FedeGueli** [comment]
PS: the S.Korean sequence is from airport surveillance (travel related with India)

**Comment by FedeGueli** [comment]
Notably some sequences has S:A344T @corneliusroemer could u give a look at this sublineage? Surely very small but in my view it seems another evolution route for XBB.1 convergent with other lineages

**Comment by FedeGueli** [comment]
One new sequence came from Delhi with 681R and 344T:
<img width="1099" alt="Screenshot 2023-04-16 alle 07 49 45" src="https://user-images.githubusercontent.com/87669813/232273848-03717d5c-2327-4bbf-b61a-77f313f75057.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37bd2_b8bdd0.json?label=id:node_5819304

**Comment by corneliusroemer** [comment]
Lacking 486P this is unlikely to grow much more against competition from XBB.1.16 - I'll close for now. Not enough good quality sequences to allow designation.
