### ISSUE TITLE
XBB.1.5(or XBB.1+S:F486P) with S:K478R and orf7a:T11I in India and Canada(36 seqs, 3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1792]
sublineage of:XBB.1.5 (or XBB.1+S:F486P)
GISAID query: C27425T,G28079T,T23018C,C22995G
First seq: EPI_ISL_17002495 2023-2-13(Canada)
Latest seq:EPI_ISL_17244717 2023-3-15(India, Maharashtra)

Mutations on top of XBB.1.5: S:K478R(C22995G), Orf7a:T11I(C27425T), G28079T

No. of seqs: 15 (1 Canada, 5 Maharashtra, 9 Gujarat)

Sequences: EPI_ISL_17002495, EPI_ISL_17182938, EPI_ISL_17242459,
EPI_ISL_17242463, EPI_ISL_17244712, EPI_ISL_17244717,
EPI_ISL_17269883, EPI_ISL_17269909, EPI_ISL_17269913,
EPI_ISL_17269918, EPI_ISL_17269935-17269936, EPI_ISL_17269942,
EPI_ISL_17270006, EPI_ISL_17270019

usher gives this branch XBB.1 and XBB.1.5 in two different runs, but both are on flip-flop reversion branchs. 

<img width="1398" alt="Screen Shot 2023-03-24 at 03 04 08" src="https://user-images.githubusercontent.com/10445944/227321499-63829162-043c-41d7-b74a-5bb5bc55a507.png">

<img width="1412" alt="Screen Shot 2023-03-24 at 03 04 42" src="https://user-images.githubusercontent.com/10445944/227321614-90785489-bb62-4e35-bb62-5f584cf313e2.png">

[run1, XBB.1.5](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3e67c_c9f440.json?f_userOrOld=uploaded%20sample)

[run2,XBB.1](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_2f3a7_c99e70.json)

**Comment by aviczhl2** [comment]
16 seqs.

**Comment by aviczhl2** [comment]
29 seqs now.

**Comment by aviczhl2** [comment]
31 seqs and additional country of Malaysia.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. Although this is still accumulating detections, it has shown a strong relative growth disadvantage over the past month in India and world wide. It is also very small relative to its large parent. Consequently, this can be closed for now, but please request re-opening or repropose should this clade show clear advantages and marked expansion in the future.
