### ISSUE TITLE
Potential BF.5 mini saltation (4 seq., Japan)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1796]
Proposal for a sublineage of BF.5
Earliest sequence: 27.02.2023 (Japan)
Countries detected: Japan

GISAID query: Spike_S50L, Spike_D138H, Spike_E340K

Mutations:
nuc	unique	C4672T, A5872G, A6567G, C8991T, C9348T, C9733T, C10279T, A12555G, T20961C, C21711T, G21974C, G22580A, T27324C, G27706A
nuc	homoplasies	T27532C, C28045T
nuc	reversionsToRoot	T27532C
ORF1ab	unique	D2101G, A2909V, T3028I, E4097G
S	unique	S50L, D138H, E340K
ORF7a	unique	A105T
ORF7a	homoplasies	Y47H
ORF7a	reversionsToRoot	Y47H
ORF8	homoplasies	A51V

![grafik](https://user-images.githubusercontent.com/102166254/227458832-59738d5d-d839-497b-80f7-e7b6ac4bfde9.png)

![grafik](https://user-images.githubusercontent.com/102166254/227459584-34aee395-1097-4918-80c9-fb486dc90a21.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3856b_d576e0.json?c=gt-S_340

EPI_ISL_17273453-17273456

**Comment by FedeGueli** [comment]
@ryhisner could you check this one?

**Comment by MCB6** [comment]
Another molnupiravir spawn?

**Comment by corneliusroemer** [comment]
Looks like single patient, all the EPI_ISLs are close together

**Comment by agamedilab** [comment]
Hi @corneliusroemer the collection dates are very close together so its very unlikely this is a single chronic patient....could be a family cluster though...

![grafik](https://user-images.githubusercontent.com/102166254/227593199-8e9d4c5c-9ec5-40c0-a035-2fface69f7da.png)

**Comment by ryhisner** [comment]
@FedeGueli @MCB6 — I checked this sequence, and though the saltation has a high percentage of transitions (18/20), there are only 3/20 G->A mutations, about the expected amount—and one of those is the sotrovimab resistance mutation E340K. Though it's possible, I don't think there was any molnupiravir role in this one, though sotrovimab definitely played some kind of role.

**Comment by InfrPopGen** [comment]
Thank you for highlighting this curious clade. Despite the interesting signs of therapeutic selection, this can be closed for now, as it does not appear to have spawned a transmission network beyond the initial cluster a month ago. Please re-quest reopening should this one reemerge with significant growth.
