### ISSUE TITLE
BQ.1.1.39 sublineage with S:P251L (C22314T), S:Q613H(G23401T) (39seqs, mainly in Sweden, Australia and France)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1797]
Defining mutations: BQ.1.1.39>C22314T (S:P251L) >G1577A (ORF1a:V438I) >G23401T (S:Q613H)
GISAID query: Spike_R346T, Spike_K182E, Spike_P251L, Spike_P1162L, Spike_Q613H, G1577A
Cov-spectrum query: BQ.1.1.39+S:Q613H
Earliest seq: 2023-01-30 (France, EPI_ISL_16895199)
Most recent seq: 2023-03-21 (Sweden, EPI_ISL_17276374)
Countries Detected: Sweden (23), Australia (6), France (6), England (2), Switzerland (1), Finland (1)

Usher Tree: Some of seqs further get S:G75V.
![QQ截图20230324214339](https://user-images.githubusercontent.com/121703496/227537480-a84a8422-4cec-412b-af94-7d31bb367420.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_dc2b_d9ca40.json

S:Q613H is popular recently. This sublineage also shows notable advantage to its parent lineage (BQ.1.1.39), even slightly faster than XBB.1.5 (though the samples are inadequate). 
![QQ截图20230324212051](https://user-images.githubusercontent.com/121703496/227536004-a2604d7f-9d0b-4a22-8626-bd1ddecf6a34.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nucMutations=T17124C&nextcladePangoLineage=XBB.1.5*&aaMutations1=S%3AQ613H&nextcladePangoLineage1=BQ.1.1.39*&analysisMode=CompareToBaseline&

Genomes:
EPI_ISL_16895199, EPI_ISL_16895202, EPI_ISL_16909187, EPI_ISL_16925402, EPI_ISL_16954554, EPI_ISL_16956607, EPI_ISL_16979611, EPI_ISL_16987093, EPI_ISL_17036555, EPI_ISL_17077542, EPI_ISL_17077712, EPI_ISL_17079474, EPI_ISL_17080379, EPI_ISL_17080419, EPI_ISL_17094435, EPI_ISL_17099044, EPI_ISL_17100178, EPI_ISL_17153931, EPI_ISL_17204691, EPI_ISL_17222554, EPI_ISL_17228995,
EPI_ISL_17229042, EPI_ISL_17248257, EPI_ISL_17276296, EPI_ISL_17276306, EPI_ISL_17276317-17276318, EPI_ISL_17276321,
EPI_ISL_17276329, EPI_ISL_17276341, EPI_ISL_17276345, EPI_ISL_17276352, EPI_ISL_17276364, EPI_ISL_17276374-17276375,
EPI_ISL_17280602, EPI_ISL_17280659, EPI_ISL_17280689, EPI_ISL_17280702

**Comment by corneliusroemer** [comment]
I don't like that S:P251L is homoplasic, something is off there with the tree. Probably tree getting misled by dropouts.

**Comment by HynnSpylor** [comment]
@corneliusroemer 
The question has been partially discussed in #1385 (definition of BQ.1.1.39). It is interesting that the branch of ORF1ab:V6061I (G18445A)+S: P251L are almost in North America (USA, Canada and Mexico), while S:P251L without ORF1ab:V6061I is worldwide. 
![QQ截图20230325013208](https://user-images.githubusercontent.com/121703496/227603676-87629057-dc69-4df9-9922-9075d743e5ce.png)

But it reminds me that my definition is not strict. BQ.1.1.39 is indeed defined as BQ.1.1 with S:K182E and S:Q218H (following T19293C, T23716C, A28834G, **without S:P251L**). I'll revise it. 

@thomasppeacock the label should be BQ.1?

**Comment by ryhisner** [comment]
@corneliusroemer — The tree is definitely distorted by dropout. I watched this lineage close from the beginning, and every sequence without S:P251L had no coverage there. Indonesia and a few other countries frequently have missing coverage in that area of spike for some reason. I'm convinced there are no sequences in this lineage that don't in reality have S:P251L.

**Comment by AngieHinrichs** [comment]
If those sequences have N at 22314, they may be helped by temporary removal & adding back.  I'll add that to the list.

**Comment by corneliusroemer** [comment]
If only the MAT kept track of Ns ;) @AngieHinrichs

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage FQ.1 with 40 newly designated sequences, and 0 updated. Defining mutation G23401T (S:Q613H) (following G1577A (ORF1a:V438I)).
