### ISSUE TITLE
XBB.1.5 Sublineages (3) with S:K304Q, mostly in USA (191/105/51 seq, May 8)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1798]
### **Full credit to @FedeGueli for tracking this mutation (and hundreds of others!) in the XBB.1.5 spike diversity issue, #1510. Fede had documented this long before I noticed the trend.**

**Description for Lineage 1 — XBB.1.5 + S:K304Q**
**Sub-lineage of:** XBB.1.5
**Earliest sequence:** 2023-1-18, USA, Texas — EPI_ISL_17120697
**Most recent sequence:** 2023-3-11, USA, Pennsylvania — EPI_ISL_17279077
**Countries circulating:** USA
**Number of Sequences:** 58
**GISAID AA Query:** Spike_K304Q, NSP13_S36P, -Spike_F486S, -N_I131R, -N_Q260L, -NSP1_L149R
**GISAID Nucleotide Query:** T16342C, A22472C, -T711G, -T10204C, -A29052T, -T28665G
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.5* & A22472C & !T711G & !T10204C & !A29052T & !T28665G
**Substitutions on top of XBB.1.5:**
**Spike:** K304Q
**Nucleotide:** A22472C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.5_K304Q_Lineage_1_subtreeAuspice1_genome_38b97_dd0fe0.json
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/33738461/227604923-18b0b681-4f7b-45e8-bc7f-01b2aad26c19.png">
 

**Evidence**
S:K305Q is a mutation that, before XBB.1.5, had only occurred about 20 times throughout the entire pandemic. Now there appear to be at least three substantial sublineages of XBB.1.5 that have acquired it independently, and all seem to be growing fairly quickly, though sample sizes are too small at this point to draw any conclusions about their growth potential. This seems to me a strong indication that something about XBB.1.5 permits S:K304Q where all previous lineages did not. Whether or not this mutation is advantageous or not remains to be seen.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16916659, EPI_ISL_16919295, EPI_ISL_16919734, EPI_ISL_16919737, EPI_ISL_16957540, EPI_ISL_16962358, EPI_ISL_16992526, EPI_ISL_16992992, EPI_ISL_17009307, EPI_ISL_17023378, EPI_ISL_17027198, EPI_ISL_17035090, EPI_ISL_17035242, EPI_ISL_17037387, EPI_ISL_17037430, EPI_ISL_17084701, EPI_ISL_17084948, EPI_ISL_17085120, EPI_ISL_17085161, EPI_ISL_17099098, EPI_ISL_17120697, EPI_ISL_17139282, EPI_ISL_17139821, EPI_ISL_17140243, EPI_ISL_17147035, EPI_ISL_17147482, EPI_ISL_17170014, EPI_ISL_17170022, EPI_ISL_17170040, EPI_ISL_17170342, EPI_ISL_17170360, EPI_ISL_17170361, EPI_ISL_17170389, EPI_ISL_17180109, EPI_ISL_17181363, EPI_ISL_17181379, EPI_ISL_17181861, EPI_ISL_17191626, EPI_ISL_17193231, EPI_ISL_17193497, EPI_ISL_17193717, EPI_ISL_17197256, EPI_ISL_17224080, EPI_ISL_17237229, EPI_ISL_17238375, EPI_ISL_17238663, EPI_ISL_17248802, EPI_ISL_17249727, EPI_ISL_17250474, EPI_ISL_17251207, EPI_ISL_17251260, EPI_ISL_17259478, EPI_ISL_17279077, EPI_ISL_17280091, EPI_ISL_17280202, EPI_ISL_17286996, EPI_ISL_17287145, EPI_ISL_17287166,
</details>
 
 

 
**Description for Lineage 2 — XBB.1.5.3 (S:A411S) + S:K304Q, N:I131R**
**Sub-lineage of:** XBB.1.5.3 (S:A411S)
**Earliest sequence:** 2023-1-18, USA, Nevada — EPI_ISL_16859435
**Most recent sequence:** 2023-3-13, USA, California — EPI_ISL_17279134
**Countries circulating:** USA
**Number of Sequences:** 38
**GISAID AA Query:** Spike_K304Q, NSP13_S36P, N_I131R
**GISAID Nucleotide Query:** T16342C, A22472C, T28665G
**CovSpectrum Query:** Nextcladepangolineage:
**Substitutions on top of XBB.1.5.3:**
**Spike:** K304Q
**N:** I131R
**Nucleotide:** A22472C, G22793T, T28665G

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.5.3_K304Q_Lineage_2_subtreeAuspice2_genome_38b97_dd0fe0.json  
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/33738461/227604788-aea51c25-50fd-4f2f-af0b-50ba07093640.png">

**Evidence**
See comments on Lineage 1 above.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16859435, EPI_ISL_16991536, EPI_ISL_16991537, EPI_ISL_17001566, EPI_ISL_17073180, EPI_ISL_17084827, EPI_ISL_17084952, EPI_ISL_17102474, EPI_ISL_17146251, EPI_ISL_17146707, EPI_ISL_17169365, EPI_ISL_17179782, EPI_ISL_17179979, EPI_ISL_17180086, EPI_ISL_17180099, EPI_ISL_17182039, EPI_ISL_17183338, EPI_ISL_17183340, EPI_ISL_17183343, EPI_ISL_17183345, EPI_ISL_17194646, EPI_ISL_17197035, EPI_ISL_17204095, EPI_ISL_17205263, EPI_ISL_17205266, EPI_ISL_17224677, EPI_ISL_17224851, EPI_ISL_17224852, EPI_ISL_17250682, EPI_ISL_17261170, EPI_ISL_17264663, EPI_ISL_17271707, EPI_ISL_17278484, EPI_ISL_17278531, EPI_ISL_17278596, EPI_ISL_17279134, EPI_ISL_17279748, EPI_ISL_17286477
</details>
 
 
 

 
**Description for Lineage 3 — XBB.1.5 + S:G261V, S:K304Q, N:Q260L**
**Sub-lineage of:** XBB.1.5
**Earliest sequence:** 2023-1-25, USA, Iowa — EPI_ISL_16853962
**Most recent sequence:** 2023-3-10, USA, Florida — EPI_ISL_17287229
**Countries circulating:** USA (*13), Mexico (11), Denmark (7), South Korea (1)
**Number of Sequences:** 32
**GISAID AA Query:** Spike_K304Q, NSP13_S36P, N_Q260L
**GISAID Nucleotide Query:** T16342C, A22472C, A29052T
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.5* & A22472C & A29052T
**Substitutions on top of XB.1.5:**
**Spike:** G261V, K304Q
**N:** Q260L
**Nucleotide:** G22344T, A22472C, A29052T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.5_K304Q_Lineage_3_subtreeAuspice3_genome_38b97_dd0fe0.json

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/33738461/227604565-7bef40a8-5447-45e5-abe5-5d72646928bd.png">

**Evidence**
(See comments for lineage 1 above.) This lineage is likely most prevalent in Mexico or Central America and likely is the most globally widespread of the three XBB.1.5 + S:K304Q lineages described here.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16853962, EPI_ISL_16991186, EPI_ISL_16991332, EPI_ISL_17007616, EPI_ISL_17026377, EPI_ISL_17048537, EPI_ISL_17048801, EPI_ISL_17066276, EPI_ISL_17167717, EPI_ISL_17170127, EPI_ISL_17170170, EPI_ISL_17170222, EPI_ISL_17170233, EPI_ISL_17170262, EPI_ISL_17170273, EPI_ISL_17172014, EPI_ISL_17196744, EPI_ISL_17196752, EPI_ISL_17210284, EPI_ISL_17210289, EPI_ISL_17210319, EPI_ISL_17223535, EPI_ISL_17268872, EPI_ISL_17270146, EPI_ISL_17270151, EPI_ISL_17270155, EPI_ISL_17270158, EPI_ISL_17272393, EPI_ISL_17272466, EPI_ISL_17273319, EPI_ISL_17286216, EPI_ISL_17287229
</details>

**Comment by oobb45729** [comment]
K304Q? That's intriguing. I was wondering about what S50L would do yesterday. S50L is a known chronic infection marker but it is relatively rare (for a C to U mutation) otherwise. S50 is very close to K304.

**Comment by FedeGueli** [comment]
Thx Ryan! it was the american par of S:I410V in Europe, they popped up quite at the same time and grew fast since. Happy you finally proposed them!

**Comment by ryhisner** [comment]
It looks like 304 is also very close to 275-278 and somewhat close to 957 and 960, at least based on this tool made by @OliasDave, which is the only way I know of figuring out the proximity of different spike sites.
https://ukcovid.xyz/proximity.php?targetposition=304

**Comment by aviczhl2** [comment]
363/143/61 now.

**Comment by FedeGueli** [comment]
> 363/143/61 now.

Lineage 1 doubled in two months,  not super fast but probably worth a designation. @aviczhl2 did any of them acquired some further mutations?

**Comment by aviczhl2** [comment]
> T16342C, A22472C, -T711G, -T10204C, -A29052T, -T28665G

53 of them have Orf1a:T4175I

**Comment by FedeGueli** [comment]
Branch 1 designated XBB.1.5.104 via https://github.com/cov-lineages/pango-designation/commit/9e084183db3a025a240f59341931fefe883c09a5

**MIlestone missing**

**Comment by FedeGueli** [comment]
Branch 2 designated ??? ( erroneous ALIAS in this designation) : via https://github.com/cov-lineages/pango-designation/commit/f9cd6630833036fef458c16132bb13a3bade400f

**Milestone missing**.

**Comment by corneliusroemer** [comment]
Oh damn, I'll fix it, sorry for the confusion

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
Please close this issue
