### ISSUE TITLE
Proposal for sub-lineages within B.1.617.2

### ISSUE THREAD

**Issue by chrisruis** [cov-lineages/pango-designation#180]
**Proposal for 7 B.1.617.2 sub-lineages in the UK**
by Chris Ruis

**Description**
Sub-lineages of B.1.617.2
These are clades within B.1.617.2 that contain predominantly UK sequences and have at least 1 mutation on the branch leading to their respective common ancestor. We propose that these are designated AY.4-AY.10.

Details of each sub-lineage
**AY.4**
Earliest sequence - 05/02/2021 (India)
Latest sequence - 07/07/2021 (UK)
Countries circulating - UK (3515 sequences) and multiple other countries
Associated mutation - C7851T

**AY.5**
Earliest sequence - 19/04/2021 (UK)
Latest sequence - 07/07/2021 (UK)
Countries circulating - UK (279 sequences) and multiple other countries
Associated mutation - G24928T

**AY.6**
Earliest sequence - 19/04/2021 (UK)
Latest sequence - 06/07/2021 (UK)
Countries circulating - UK (187 sequences) and multiple other countries
Associated mutation - G17331T

**AY.7**
Earliest sequence - 01/05/2021 (UK)
Latest sequence - 05/07/2021 (UK)
Countries circulating - UK (81 sequences), Denmark (1 sequence)
Associated mutations - G11365T, G12718T, C27629A

**AY.8**
Earliest sequence - 20/04/2021 (UK)
Latest sequence - 04/07/2021 (UK)
Countries circulating - UK (65 sequences)
Associated mutation - A14170G

**AY.9**
Earliest sequence - 26/03/2021 (UK)
Latest sequence - 06/07/2021 (UK)
Countries circulating - UK (315 sequences) and multiple other countries
Associated mutation - C22792T

**AY.10**
Earliest sequence - 13/04/2021 (Germany)
Latest sequence - 29/06/2021 (UK)
Countries circulating - UK (53 sequences) and multiple other countries
Associated mutations - C12756T, C13665T

**Genomes**
[AY.sublineage_sequences.txt](https://github.com/cov-lineages/pango-designation/files/6976217/AY.sublineage_sequences.txt)

**Proposed lineage names**
AY.4-AY.10

**Comment by FedeGueli** [comment]
Sorry i didnt know that citing this issue outside the pango lineages github would have created a direct link here .
Sorry for disturbing your work.
As a non technical citizen who tries to keep updating variants lists to keep public audience well informed, could you please write the defining AA substitutions too and not just the nucleotides changes? Thank you for your hard work.

**Comment by mkedwards** [comment]
AY.4:  C7851T is ORF1a:A2529V, also nsp3:A1711V.  nsp3 is frequently referred to as the "papain-like protease" or PLpro, though it is highly multifunctional; note that it corresponds to nsp2 in MHV and EAV, though some papers refer to it as nsp3 in all coronoviruses.  Its domain structure is still rather poorly determined, though there are newer and better references (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7113682/ especially) than you'll find in a lot of the SARS-CoV-2 papers.  It's multi-pass transmembrane and essential to the formation of replication organelles (DMVs).  It's a component of the DMV pore complex to which the replication-transcription complex is anchored: https://science.sciencemag.org/content/369/6509/1395.  A1711V is in its cytosolic C-terminal region, which has very high sequence similarity with its SARS-CoV homolog; it's close to the boundary of the Y1 and CoV-Y domains as defined in the Neuman review, which doesn't tell us a whole lot.  One might expect that region to be involved in oligomerization of nsp3 to form pore complexes, though.

Cladistically speaking, AY.4 is (in the UK) most of the S:T95I (C21846T) branch of Delta, which is in turn most of the N:G251C subclade.  In my opinion it's N:G215C (G28916T), plus half a dozen other mutations (mostly in nsps) that cropped up in a burst, that really forms a distinct subclade.  But given that the AY.3 horse has already bolted, I'm not going to lose sleep over it.

<img width="1396" alt="Screen Shot 2021-08-13 at 9 58 20 AM" src="https://user-images.githubusercontent.com/843186/129393993-e040988d-9641-42fe-ae4f-948e6cf69ce6.png">

**Comment by mkedwards** [comment]
AY.5:  G24928T is a synonymous mutation within S codon 1122.  Also a branch within N:G215C, though outside S:T95I.

AY.6:  Also a branch within N:G215C, though outside S:T95I.  G17331T is ORF1b:E1288D (in Nextstrain terms), which is nsp13:E365D.  nsp13 is the RNA helicase component of the replication-transcription complex, and this substitution is in its RecA-like 1A domain (https://www.nature.com/articles/s41467-020-19770-1).  It hasn't been repeatedly invented in other clades, and I don't think there's much reason to think it would cause a sudden increase in viral fitness.

G17331T co-occurs (almost?) 100% with ORF1a:D691N (G2336A).  The latter is in nsp2 (D511N), whose function is obscure but may include some sort of binding to ribosomal RNA (https://www.biorxiv.org/content/10.1101/2021.05.10.443524v1.full).  (It's possible that the screening of RNA-binding viroproteins in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7543886/ would have missed that, if the way they induced protein expression didn't result in a zinc ion in the zinc ribbon motif.)  Whether or not it has functional significance, it hasn't popped up in other clades.  Compare A2529V above — which has been seen in other clades, though it has not taken off in the same way — or any of the ORF1a mutations (P2046L,T3646A,T3255I) called out in the discussion at https://github.com/cov-lineages/pango-designation/issues/102.

Once again, I don't see any real reason to track these separately from N:G215C generally.  Even less so than S:T95I or ORF1a:A2529V (AY.4), really.  But I'm not going to lose sleep over it.  If I were looking for new things to worry about within Delta, I'd probably be paying attention to S:A222V (C22227T), which has popped up in the non-N:G215C branch of the clade and spread all over Europe.  That subclade is competing with N:G215C just fine, and between the two of them they've starved out the rest of Delta in Europe and North America.

**Comment by zach-hensel** [comment]
@mkedwards ORF1a:T3255I (Nsp4 T492I) is particularly interesting showing up so often in things that are relevant now... C.37, B.1.575, B.1.1.519, and now B.1.621.

It's very easy to find sub-lineages of 100s of Delta sequences with 2 or 3 plausibly significant Spike mutations and various plausibly significant non-Spike mutations... not sure it helps to focus on the ones that happen to be found over the broader trend.

**Comment by mkedwards** [comment]
nsp4:T492I is also interesting at a mechanistic level.  It's in the cytosolic C-terminal tail of nsp4, 8 residues away from the nsp4/nsp5 3CL protease cleavage site — possibly close enough to affect cleavage efficiency.  (Very small shifts in substrate alignment are enough to dramatically change cleavage efficiency, and nsp4/5 appears to be a rather highly tuned site already: https://www.biorxiv.org/content/10.1101/2021.04.20.440716v1.full.)  In Delta, this change seems to be an alternative to nsp4:A446V (ORF1a:A3209V) in the non-N:G215C branch, which is also in the cytosolic tail.  C.37 has T492I plus nsp4:L438P (ORF1a:L3201P) and nsp5:G14S (ORF1a:G3278S).

It would certainly be interesting to explore whether there's a connection between accelerated nsp4/5 cleavage — and/or greater exposure of the nearby, highly conserved YxPP motif (https://journals.iucr.org/d/issues/2009/08/00/dz5162/index.html), which is at least somewhat plausible as a functional effect — and viral fitness.  But in the absence of clinically ready 3CL protease inhibitors (which are coming along... slowly; https://anivive.com/coronavirus), it's fairly academic, except insofar as it could tell us which variants we need to be testing those candidate drugs against.

**Comment by FedeGueli** [comment]
Thank you very much @mkedwards !

**Comment by chrisruis** [comment]
Hi @FedeGueli. We've now posted a summary of the AY lineages designated so far with their defining mutations, including whether those are synonymous or nonsynonymous, [here](https://www.pango.network/new-ay-lineages-and-an-update-to-ay-4-ay-12/)

**Comment by FedeGueli** [comment]
Thank you very much @chrisruis !!
