### ISSUE TITLE
Second biggest branch of XBB.1.16 with Orf3a:V13L and Orf1a:P926H (328 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1802]
Looking at the tree that is still messed up by reversions beyond the clear XBB.1.16.1 with S:T547I branch, the second distinguishable branch comes with Orfa:V13L, Orf1a:P962H with 36 sequences , it may not have emerged in MH but instead in Gujarat and it was sampled also in Delhi and Haryana too. Very early it was sequenced by South Korean, Singaporean and north american airport surveillance. 
Interestingly one sample was sequenced in a traveller from Vietnam.

Gisaid query: NS3_V13L,NSP3_P108H

Sequences : 36
EPI_ISL_17012463, EPI_ISL_17012465, EPI_ISL_17073064,
EPI_ISL_17078574-17078576, EPI_ISL_17146514, EPI_ISL_17168404,
EPI_ISL_17182930, EPI_ISL_17190083, EPI_ISL_17190086,
EPI_ISL_17197627, EPI_ISL_17197638, EPI_ISL_17207392,
EPI_ISL_17229078-17229079, EPI_ISL_17229210, EPI_ISL_17230599,
EPI_ISL_17230936, EPI_ISL_17244693, EPI_ISL_17247049,
EPI_ISL_17247084, EPI_ISL_17257463, EPI_ISL_17257492,
EPI_ISL_17257495, EPI_ISL_17268903, EPI_ISL_17268923,
EPI_ISL_17268929, EPI_ISL_17268945, EPI_ISL_17269872,
EPI_ISL_17270033, EPI_ISL_17277419, EPI_ISL_17293144,
EPI_ISL_17293186, EPI_ISL_17293201-17293202

Tree:
<img width="1136" alt="Schermata 2023-03-26 alle 10 48 48" src="https://user-images.githubusercontent.com/87669813/227765206-f56c48c6-4d69-4f33-86e2-267a9179929f.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1b697_ffc380.json?c=gt-S_554&label=id:node_7690378

It appears to be slower than its parent: lets see if it holds or disappears.
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf3a%3AV13L%2Corf1a%3AP926H&nextcladePangoLineage1=XBB.1.16*&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
61 one of the last samples from Singapore had travel history from Indonesia.

**Comment by FedeGueli** [comment]
This branch counts 250 sequences now.

**Comment by InfrPopGen** [comment]
I think it is ORF3a:V13L followed by ORF1a:P926H, as in the title, rather than 4a as in the top post. The "monitor" here, doesn't mean that I think this is too small, just a bit young (and the growth advantage in Asia is less than in North America at the moment).

**Comment by FedeGueli** [comment]
thx @InfrPopGen yes orf4a was a typo thx for noticing.

**Comment by FedeGueli** [comment]
@InfrPopGen this has been designated now XBB.1.16.2 via https://github.com/cov-lineages/pango-designation/commit/c93a471ebbe34b4e9ca24a0b2eaed1cce26daac2,  could be added please the milestone?
