### ISSUE TITLE
lineage_notes.txt XBB.2.3

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#1803]
XBB.2.3	Defined by S:P521S and S:S486P, India/Indonesia/Singapore/USA, from #1776
XBB.2.3.2	Defined by S:G184V, ORF1a:R2159W, India
but #1776 seems to be XBB.2.3.2

**Comment by Mydtlwn** [comment]
Yes, it is an error, it was in the Actions when XBB.2.3.2 was specified earlier, but I didn't think that the error actually existed in the lineage_notes file as well, I just went and looked at it and it does exist.

**Comment by Mydtlwn** [comment]
@InfrPopGen

**Comment by Mydtlwn** [comment]
Thank you for pointing out the error, we will fix it soon.

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by AngieHinrichs** [comment]
Good spot @Over-There-Is, that seems to have been a copy-paste error in commit 42670696 when XBB.2.3.2 was added.
