### ISSUE TITLE
XBB.1.5* with S:R403K and S:L582F (8 sequences - South Africa)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1804]
There may be a XBB..5 sublineage circulating in Gauteng that have gained further two spike mutations: S:R403K,S:L582F.

It is just two samples so not necessarily could have any relevance. Put here to check for a while and eventually closing it.
the predicted composite fitness is increased by ACE2 binding going up, but i have to say i still never saw any mayor boost in transmissibility as with S:Y453F.
<img width="417" alt="Schermata 2023-03-26 alle 17 18 33" src="https://user-images.githubusercontent.com/87669813/227785580-bb59ffdb-6ef0-427a-a944-470e182afce7.png">

Tree:
<img width="1144" alt="Schermata 2023-03-26 alle 17 21 58" src="https://user-images.githubusercontent.com/87669813/227785794-618f8095-93d1-47ea-97bf-0ef49c62475a.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e3d5_59ac0.json?c=gt-S_403&label=id:node_7752195

Defining mutations:
XBB.1.5 > C21811T > T10204C >C6031T, C22498A , S:RT403K (G22770A),S:L582F (C23306T)
(Note that i exclude a bunch of reversions here, we will see if they are real)

Sequences:EPI_ISL_17222285, EPI_ISL_17285135

Gisaid query: Spike_F486P,Spike_L582F,Spike_R403K

**Comment by FedeGueli** [comment]
4 sequences now. 

![Schermata 2023-04-06 alle 15 43 06](https://user-images.githubusercontent.com/87669813/230396344-8e0d8d16-8dbf-40b1-9b4e-0934a4aaa81c.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice10_genome_2af10_de6b30.json?c=gt-nuc_6031&label=id:node_7802750

**Comment by FedeGueli** [comment]
5 sequences as today:
<img width="1138" alt="Screenshot 2023-04-16 alle 19 45 28" src="https://user-images.githubusercontent.com/87669813/232331569-ed26dbf9-0b14-4f81-84bd-327746b9b84c.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice18_genome_43bea_b994c0.json?c=userOrOld&label=id:node_5921827

**Comment by FedeGueli** [comment]
4 new sequences uploaded from South Africa and one from  Canada but this last one is not placed in the same tree by Usher due to presence of 12919 and absence of 10204 and 6031
![Schermata 2023-04-22 alle 16 12 22](https://user-images.githubusercontent.com/87669813/233789873-5c1aa09b-d42c-42f3-999b-614e1ed01ed6.png)

total count 9 
![Schermata 2023-04-22 alle 16 07 27](https://user-images.githubusercontent.com/87669813/233789671-ebe58fc8-43d9-492e-ae86-f9e0d0e9189e.png)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_55066_3e9a20.json?c=userOrOld&label=id:node_5949306

**Comment by InfrPopGen** [comment]
Hi @corneliusroemer these appear to be duplicated in lineages.csv (and can see similar effect in the first pair of sequences, at top, of the first tree in this issue above); for example,
SouthAfrica/NICD-N54078/2023,XBB.1.5.53
South_Africa/NICD-N54078/2023,XBB.1.5.53
...
South_Africa/NICD-N54038/2023,XBB.1.5.53
SouthAfrica/NICD-N54038/2023,XBB.1.5.53

These cryptic duplicates could easily creep in, as they appear to be present at source.
