### ISSUE TITLE
BA.1.1 Saltation with 3 forms (3 patients, Ontario) 

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1805]
**Sub-lineage of:** BA.1.1
**Earliest Sequence:** March 1, 2023
**Countries Circulating:** Canada, Ontario (4)
**Number of Sequences:** 4
**GISAID AA Query Combined:** Spike_N394Y, Spike_K417T,spike_k356t

**Shared mutations:** 
**ORF1A:** K141-, S142-, F143-, E452G, L3201P, V3718F, P4120S, 
**Spike:** D80G, F157S, E340A?, K356T, N394Y, K417T, D936Y
**ORF3a:** T14-,L15-
Nucleotide only: A686-,A687-,G688-,T689-,C690-,A691-,T692-,T693-,T694-,A1378C,A1620G,C9763T,T9867C,G11417T,C12623T,C15540T,A21801G,T22032C,A22629C,A22742T,A22812C,G24368T,A25432-,C25433-,T25434-,T25435-,T25436-,G25437-

Notably, **form 2 has S:Q613E, S:P681R**

Otherwise, I recommend using [this Venn-Diagram](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=s%3A417t%2Cs%3A394y%2Corf1a%3A3620v&nextcladePangoLineage=ba.1.1&aaMutations1=s%3A417t%2Cs%3A394y%2Corf1a%3A3620a%2Cs%3A681h&nextcladePangoLineage1=ba.1.1&aaMutations2=s%3A417t%2Cs%3A394y%2Cs%3A681r&nextcladePangoLineage2=ba.1.1&analysisMode=CompareEquals&) to contrast them. 

I've labeled them as forms 1-3 on the [USHER tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31aa2_6f6f0.json?f_userOrOld=uploaded%20sample) and Venn-Diagram (nucleotide differences). On the Venn-Diagram I also looked at where nucleotides are ambiguous, and might actually be shared. There are 3 possible spots between form 1-3. These are 823 (synonymous), 26395 (E:L51F), and 27388 (synonymous)
![image](https://user-images.githubusercontent.com/94097102/227793113-d4d49b71-de77-41cd-9ba2-c474c1046914.png)
![image](https://user-images.githubusercontent.com/94097102/227793123-10c3fc57-7a13-43f8-acd8-a2ac9dd55f17.png)

**Discussion:**
Credits to @ryhisner for finding the first sequence! 
This one is notable because it has been quite a while since we've seen BA.1.1 spread. In this case, the 3 sequences aren't really the same genome, but are clearly closely related. The very similar age of all patients makes me suspect that this is not spreading in the community at large, and might be more of an isolated, possibly healthcare-related incident, but I don't have confirmation on that.  
There are actually 4 sequences, but I believe that the one I've labeled form 3 is the same patient being sequenced twice, since the patient metadata and the genomes are the same.  

Form 3 appears to share mutations with form 1 and form 2, which form 1 and 2 do not share with each other. Additionally, there is nothing that form 1 and 2 share with each other that they do not share with form 3.  Unless I am missing a simpler explanation, there is no possible cause for this other than either convergent evolution or recombination. Neither of these explanations really seem well supported though either. I'm not finding a simple recombination pattern that would explain it, and this would include convergent evolution of at least one synonymous nucleotide. 

A few of the spike mutations are quite familiar. 
D80G was in Beta (thanks @FedeGueli!)
E340A is a sotrovimab resistance mutation, and present in forms 2 and 3, while ambiguous in form 1. 
K356T creates a new glycan site, and is present in BN.1*. 
K417T showed up in many Omicron variants prior to BA.5,/BA.2.75 granting an advantage. 

**Genomes:** EPI_ISL_17205892, EPI_ISL_17271226, EPI_ISL_17271194, EPI_ISL_17271272

**Comment by FedeGueli** [comment]
Great catch and proposal by you and Ryan!
Sincerely this cluster seems to re collect many of the first vocs era and omicron era advantageous mutations. 417T was in Gamma too and also quite successful in combination with 157S in BA.2.38.2 . Arent there reversions?
