### ISSUE TITLE
XBJ.1.1 with S: I68T, S:Y144F and 5 other aa (8 seq. South Korea)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1806]
Proposal for a sublineage of XBJ.1.1
Earliest sequence: 11.01.2023 (South Korea)
Countries detected: South Korea

Defining mutations:
nuc	unique	G10151A, A21993T
nuc	homoplasies	C5784T, C10507T, C12534T, G19684T, C28005T, T21765C
ORF1ab	unique	D3296N
ORF1ab	homoplasies	T1840I, T4090I, V6474L
ORF8	homoplasies	P38S
S	unique	Y144F
S	homoplasies	I68T

Gisaid query: G10151A, A21993T

![grafik](https://user-images.githubusercontent.com/102166254/227858170-92a00ab8-8ff5-4044-b578-972f5eb6229d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21c6d_1354e0.json?c=gt-S_144

![grafik](https://user-images.githubusercontent.com/102166254/227858359-4a4d28b9-ff3d-430e-bfdf-0a517d040b5e.png)

EPI_ISL_16899653
EPI_ISL_17164064
EPI_ISL_17293986
EPI_ISL_17293985
EPI_ISL_17293984
EPI_ISL_17293983
EPI_ISL_17293982
EPI_ISL_17230158

**Comment by agamedilab** [comment]
Just a wild guess: Do you think it is possible that ORF7B:S31L is adaptive by messing with the antiviral response?
https://www.sciencedirect.com/science/article/pii/S2589004222017163
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8414645/

**Comment by InfrPopGen** [comment]
A most interesting lineage, and great to highlight; however, as its epidemiological significance appears minimal at present (e.g. no new detections for a month or so), this can be closed for now. Please request re-opening should it demonstrate notable spread and onward transmission in the future.
