### ISSUE TITLE
XBB.1.11.1 with S:F186S, S:Q146H, S:A376T, S:P445A plus several reversions (8 Seq. Australia)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1807]
Proposal for a sublineage of XBB.1.11.1
Earliest sequence: 19.03.2023 (Australia)
Countries detected: Australia

Defining mutations:
nuc	unique	G6981A, A23513G, G9497A, T22119C
nuc	homoplasies	A22000C, G22688A, C22895G, C25976G, T27915G
nuc	reversionsToRoot	A22000C, G22688A, C22895G, T27915G
S	unique	I651V, F186S
S	homoplasies	Q146H, A376T, P445A
S	reversionsToRoot	Q146H, A376T
ORF1ab	unique	C2239Y, V3078I
ORF3a	homoplasies	S195C
ORF8	homoplasies	*8G
ORF8	reversionsToRoot	*8G

![grafik](https://user-images.githubusercontent.com/102166254/227859335-ed1c8693-da2d-4c43-a0cd-2c1af802cab1.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20c97_1342a0.json?c=gt-S_146&label=id:node_7706326

![grafik](https://user-images.githubusercontent.com/102166254/227863346-3f72cda0-ec1a-4fae-bcb6-62696af4013e.png)

![grafik](https://user-images.githubusercontent.com/102166254/227863280-588516f3-ccea-40d1-8346-bc7584cf1141.png)

EPI_ISL_17295639, EPI_ISL_17295641-17295647

**Comment by HynnSpylor** [comment]
The Usher Tree nowadays:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_158e7_e53940.json
![QQ截图20230418193249](https://user-images.githubusercontent.com/121703496/232766697-f34cdf23-b351-4c2d-8854-00b56a567185.png)

the 3 reversed S-mutations are probably artefacts as they come from the same lab. But the S:F186S is real and shows the advantage to parent lineage (XBB.1.11.1). 
https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-01-16%26to%3D2023-04-11/variants?nextcladePangoLineage=XBB.1.11.1*&aaMutations1=S%3AF186S&nextcladePangoLineage1=XBB.1.11.1*&analysisMode=CompareToBaseline&
![QQ截图20230418193956](https://user-images.githubusercontent.com/121703496/232766649-247cf507-38e7-42fd-808b-702ca0b3ac25.png)

Also note the branch with S:K478R and 3 ORF mutations in Indonesia (though only 5 seqs now).
I suggest to monitor the whole S:F186S sublineage further.

**Comment by InfrPopGen** [comment]
Thank you for proposing this as a lineage. As it doesn't appear to have been detected again since the start of April, this can be closed for now. Please request re-opening and/or perhaps transfer to the [issue tracker](https://github.com/sars-cov-2-variants/lineage-proposals/issues) for further tracking/contemplation.

**Comment by FedeGueli** [comment]
The parental branch with S:F186S designated FP.2
