### ISSUE TITLE
Undesignated  BA.5.2 sublineage (without both Orf1b:1050N and A27038G)  defined by C7528T with 135sequences that has acquired S:R346T and Orf1b:L238F (45seqs) . Now it is circulating in China, acquiring further spike mutations in a saltation sublineage (7seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1811]
While routinely screening chinese sequences (thx to submitters!)  i discover an entirely new branch of BA.5.2 ( in the branch with  C27513T ,C27012T, but without Orf1b:1050N) which have seeded early in 2022 in China and now after acquiring convergently S:R346T is gaining further mutations also with mini saltation sublineages and it is actually circulating in China.

Trees:
Big one: (light green is Chinese samples)
<img width="1110" alt="Schermata 2023-03-27 alle 14 07 35" src="https://user-images.githubusercontent.com/87669813/227937318-cc0b330e-37f0-4c35-8160-e7fa7cb83e55.png">
As you can see after defining  C7528T there are 4 main branches:
the two on the bottom seem dead and i wont analyzed further, but has to be noticed that the sparse singlets/clusters at the very bottom contain two samples from China one likely really belonging to this lineage (Beijing/BJCDC-1868/2022|EPI_ISL_16634016|2022-08-13) , while the other looks to me misplaced or maybe recomb, both highlighted in light green:
<img width="934" alt="Schermata 2023-03-27 alle 14 11 33" src="https://user-images.githubusercontent.com/87669813/227938252-1d15fe81-9279-43ce-93a6-fdefc205acfa.png">

the two main branches had both acquired S:R346T:
the bottom One , coloured in blue is mainly from Germany while the first on the top is mainly a chinese one
<img width="1142" alt="Schermata 2023-03-27 alle 14 15 48" src="https://user-images.githubusercontent.com/87669813/227939177-698c22cc-8245-481f-b50e-48b0e7c82261.png">

The German one interestingly has S:T229I convergently with BN.1:
<img width="1154" alt="Schermata 2023-03-27 alle 14 17 58" src="https://user-images.githubusercontent.com/87669813/227939705-ee3cfef0-dea9-47a1-a142-00dbd8859f71.png">

The top one instead seems to have been introduced to China after acquiring Orf1b:L238F
<img width="1104" alt="Schermata 2023-03-27 alle 14 18 53" src="https://user-images.githubusercontent.com/87669813/227939790-c3bf8dc5-4fb7-4177-b722-9837f324defe.png">

As can be easily spotted it seems to have acquired multiple times mutations which are defining of the main lineages circulating in China, a sign of possible multiple recombination not so easy to prove or disprove being the 99%of  the circulating lineages in China from a BA.5.2 backbone.

The most of recent sequences sampled in China belonging to this lineage is from the further branch with orf1a:V274L

<img width="1164" alt="Schermata 2023-03-27 alle 14 25 29" src="https://user-images.githubusercontent.com/87669813/227940895-67c9f22d-cbed-4676-be8d-7aa9935762a9.png">

I was especially struck by this saltation sublineage :
<img width="1118" alt="Schermata 2023-03-27 alle 14 24 25" src="https://user-images.githubusercontent.com/87669813/227940675-968ad4a0-cdc4-45f1-9ab2-ce6450710329.png">

<img width="1119" alt="Schermata 2023-03-27 alle 14 23 48" src="https://user-images.githubusercontent.com/87669813/227940532-ec94a943-02bb-4df1-91d0-a562432298bc.png">

Actually i propose the main Branch  with my proposal starting from its introduction in China , hoping @corneliusroemer @InfrPopGen @AngieHinrichs @thomaspeacock could help to describe better this sublineage and to check its reality.

Defining mutations:
BA.5.2 >> > C27513T > C27012T > C7528T > S:R346T (G22599C)  > Orf1b:L238F ( G14181C )

Sequences:
Hubei/WCDC-781/2023\|EPI_ISL_17254860\|2023-03-14
Jiangsu/WXCDC-095/2023\|EPI_ISL_17068981\|2023-01-11
Germany/BE-RKI-I-1009778/2022\|EPI_ISL_15520771\|2022-10-04
Germany/BE-RKI-I-1011420/2022\|EPI_ISL_15521791\|2022-10-04
Tianjin/TJCDC-20230221-27/2023\|EPI_ISL_17027426\|2023-02-08
Fujian/FCDC-202301S162/2023\|EPI_ISL_16839013\|2023-01-30
Jiangsu/YCCDC-095/2023\|EPI_ISL_17197689\|2023-02-26
Hainan/CDC-373/2023\|EPI_ISL_17104778\|2023-02-24
Hainan/CDC-328/2023\|EPI_ISL_17104745\|2023-02-22
Anhui/HFCDC-20/2023\|EPI_ISL_16740785\|2023-01-01
Russia/SPE-RII-MH81794S/2022\|EPI_ISL_15154855\|2022-09-02
SouthKorea/KDCA211201/2023\|EPI_ISL_16901892\|2023-01-21
Guangdong/GCDC-QYQIN5001/2023\|EPI_ISL_16711776\|2023-01-13
Shandong/SDCDC-0750/2023\|EPI_ISL_16758102\|2023-01-16
Germany/BY-LGL-IMS-10272-CVDP-c68013e0-6bcb-4be9-a9d5-585780f1aa03/2022\|EPI_ISL_15955436\|2022-11-14
France/HDF-ALPIGENE-2212050045/2022\|EPI_ISL_16402880\|2022-11-28
France/HDF-IPP60289/2022\|EPI_ISL_16395485\|2022-12-12
Zhejiang/ZJU-S40/2023\|EPI_ISL_16717085\|2023-01-05
SouthKorea/KDCA-196639/2023\|EPI_ISL_16568845\|2023-01-07
Tianjin/TJCDC-20230221-31/2023\|EPI_ISL_17027429\|2023-02-12
Shandong/SDCDC-0781/2023\|EPI_ISL_16758133\|2023-01-17
Sichuan/YB23091/2023\|EPI_ISL_17104804\|2023-02-21
Sichuan/ZGCDC-23136/2023\|EPI_ISL_17062083\|2023-02-13
Sichuan/ZY230049/2023\|EPI_ISL_16970278\|2023-02-07
hCoV-19/Henan/XYCDC-23/2023\|EPI_ISL_17243396\|2023-02-27
Henan/XYCDC-23/2023\|EPI_ISL_17243396\|2023-02-27
hCoV-19/Henan/XYCDC-16/2023\|EPI_ISL_17253547\|2023-02-20
Henan/XYCDC-16/2023\|EPI_ISL_17253547\|2023-02-20
hCoV-19/Henan/XYCDC-30/2023\|EPI_ISL_17280446\|2023-03-07
hCoV-19/Henan/XYCDC-8/2023\|EPI_ISL_17016202\|2023-02-14
Henan/XYCDC-8/2023\|EPI_ISL_17016202\|2023-02-14
Shandong/SDCDC-0817/2023\|EPI_ISL_16758169\|2023-01-16
Shaanxi/SXCDC-A004/2023\|EPI_ISL_16709451\|2023-01-02
Beijing/BJCDC-0473/2023\|EPI_ISL_16955423\|2023-01-23
Zhejiang/ZJU-S50/2023\|EPI_ISL_16717960\|2023-01-05
Anhui/LCDC-027/2023\|EPI_ISL_17075801\|2023-02-25
Anhui/LCDC-028/2023\|EPI_ISL_17075802\|2023-02-25
Anhui/LCDC-029/2023\|EPI_ISL_17075803\|2023-02-25
Shanxi/SXCDC-0028/2023\|EPI_ISL_16853782\|2023-01-05
Heilongjiang/HLJCDC-0234/2023\|EPI_ISL_17199703\|2023-02-04
Heilongjiang/HLJCDC-0331/2023\|EPI_ISL_17199774\|2023-02-08
Shandong/SDCDC-0200/2023\|EPI_ISL_16604584\|2023-01-03
Beijing/BJCDC-0223/2023\|EPI_ISL_16709145\|2023-01-09
Beijing/BJCDC-0529/2023\|EPI_ISL_16955409\|2023-02-01
Beijing/BJCDC-0502/2023\|EPI_ISL_16955401\|2023-02-03

**Comment by aviczhl2** [comment]
I guess this was proposed in #1777?

**Comment by AnonymousUserUse** [comment]
@FedeGueli 
Could you please post the link of the tree, instead of only the screenshot? Thanks.
