### ISSUE TITLE
CH.1.1 Sublineage with S:V367L, S:R403K. (52 seqs, Wales)

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1812]
**Credit to @FedeGueli who found this first!**

**Sub-lineage of**: CH.1.1
**Earliest sequence**: Feb 9, 2023 — EPI_ISL_17033072
**Countries circulating**: Wales UK
**Number of Sequences**: 41 (only 14 on GISAID)
**GISAID AA Query**: spike_r403k,spike_v367L,spike_f486s
[CovSpectrum Query](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A403k%2Cs%3A367l&nextcladePangoLineage=ch.1.1*&)

**Substitutions on top of CH.1.1**:
ORF1a: G298S, E311A, I601T
Spike: V367L, R403K [The 9 most recent sequences additionally have P1263L on GISAID, or the last 36 on that USHER tree]
ORF3a: A23T

[USHER tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_916c_1ab8e0.json?c=gt-nuc_22661&f_userOrOld=uploaded%20sample) -- I'm not sure why, but it doesn't display Spike_V367L, or its NT mutation G22661C, which display on GISAID and Nextclade. 

![image](https://user-images.githubusercontent.com/94097102/228059620-37a7996c-df1e-4c55-94e8-a8239ec2964a.png)

**Discussion:** 
First, a couple odd things... 
1. I don't know why Nextstrain doesn't display the S:V367L mutation. Maybe it is masked? Edit: it is. 
2. I don't know why these sequences appear just in Wales and so many of them see identical  - possibly they're a part of the same cluster? 

S:R403K has been covered extensively in various proposals here, due to it granting ACE2 binding affinity. Despite this, it is actually a rare mutation, only in 423 sequences on GISAID in 2023. Much rarer than it is V367L, only in 30 sequences, of which 14 belong to this proposed lineage. Among the remaining 16 sequences with S:V367L, 4 of them have S:R403K. These are all one-off sequences from different lineages (BA.4.1.6, BF.7.14, BA.5.1, BQ.1). They belong to all separate countries, and although the BA.5.1 is in the UK, it is for England. 

So, it seems that there is, for some reason, a very strong correlation for S:R403K showing up when S:V367L shows up. Neither of these sites are antigenic (JBloom's work), and they are also not located close together from what I can tell (definitely not an expert at this), so I have no guess for why there's a correlation here. 

That being said, it seems like it is spreading in this proposed lineage, and possibly quite quickly. There is no patient metadata, but many sequences were collected on the same day (but not all), so I don't imagine it's a chronic patient at least. I have no info on if this could be some sort of targeted sequencing though. 

**Genomes**: EPI_ISL_17267751, EPI_ISL_17267806, EPI_ISL_17299426, EPI_ISL_17299427, EPI_ISL_17299447, EPI_ISL_17299484, EPI_ISL_17299500, EPI_ISL_17299506, EPI_ISL_17299526, EPI_ISL_17299610, EPI_ISL_17209305, EPI_ISL_17154878, EPI_ISL_17076928, EPI_ISL_17033072

**Comment by FedeGueli** [comment]
Sorry @Sinickle this is the same i proposed some days ago in #1794 , but when you asked for before i didnt recognize it cause the 367 thing fooled me too!! i will let your open as it is more complete than mine!

**Comment by Sinickle** [comment]
Ohh my bad! I was so focused on the S:V367L part I totally overlooked yours!

**Comment by AngieHinrichs** [comment]
> I don't know why Nextstrain doesn't display the S:V367L mutation. Maybe it is masked?

Yes, 22661 is in the [Problematic Sites](https://github.com/W-L/ProblematicSites_SARS-CoV2) set that are masked in all sequences before they are added to the tree.

> I don't know why sequences are only in Wales, with almost all of the ones not uploaded to GISAID yet being identical. However, some of those from that batch of identical sequences are on GISAID now.

I've heard on here (maybe from @corneliusroemer ?) that the UK has switched over from population-level surveillance sequencing to more outbreak-oriented investigations, so the sequences tend to be more clustered and not necessarily representative of the general population.

**Comment by oobb45729** [comment]
Both mutations are near the interface of the inter-protomer interactions of RBDs.
By the way, V367F was predicted to be beneficial but it had become rare since BA.2-related lineages took over.

**Comment by Sinickle** [comment]
Still all in Wales.

**Comment by FedeGueli** [comment]
yes still a welsh thing: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_43bea_b99470.json?label=id:node_6275653
<img width="1142" alt="Screenshot 2023-04-16 alle 13 41 36" src="https://user-images.githubusercontent.com/87669813/232307466-db0fc50a-b9a4-40b5-83e3-3ae0f58adb8f.png">

**Comment by Sinickle** [comment]
No sequences uploaded in the last 2 weeks, and it never left Wales.

**Comment by FedeGueli** [comment]
Thx @Sinickle i was thinking the same
