### ISSUE TITLE
Taiwanese BN.1.2.3 sublineage defined by S:K187E and N:T366I (277 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1814]
I found a sublineage of BN.1.2.3 that likely emerged in Taiwan reaching there an high prevalence in February .
It was sampled both in Taiwan homeland and in travellers from Taiwan to Singapore,Usa, South Korea and Myanmar.
Then it started to circulate when it was sample little less than 100x times and showed there a growth comparable to XBB.1.5 (that doesnt seem to have started a wave there)

Gisaid query: C1471T,C1513T,C25572T, C29370T

Nr of total sequences: 188 (99 Japan)
Taiwanese sequences (27)
IDs
EPI_ISL_16259451, EPI_ISL_16537531, EPI_ISL_16676294,
EPI_ISL_16828717-16828720, EPI_ISL_16853149, EPI_ISL_17016390,
EPI_ISL_17040800, EPI_ISL_17040887, EPI_ISL_17053655,
EPI_ISL_17075667-17075668, EPI_ISL_17089525-17089526, EPI_ISL_17104729-17104730,
EPI_ISL_17104732, EPI_ISL_17104736, EPI_ISL_17172467,
EPI_ISL_17213326, EPI_ISL_17256547-17256548, EPI_ISL_17280157,
EPI_ISL_17289382, EPI_ISL_17289384

Defining mutations:
BN.1.2.3 (C1471T) >> S:K187E (A22121G) > C1513T >C25572T, N:T366I (C29370T)

Tree:
<img width="1147" alt="Schermata 2023-03-28 alle 13 59 18" src="https://user-images.githubusercontent.com/87669813/228229165-aa5c9269-7981-46dd-86e2-8470521483e0.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1fb0c_2cf250.json?c=country&label=id:node_8037222
 
Its gain of fitness seems clear 
<img width="1103" alt="Schermata 2023-03-28 alle 14 01 14" src="https://user-images.githubusercontent.com/87669813/228229585-eb0539f2-7da8-40df-b91a-00d68234a5f4.png">
It looked competitive with XBB.1.5 although this plot is highly biased by its peculiar geographical spread 
<img width="933" alt="Schermata 2023-03-28 alle 14 02 09" src="https://user-images.githubusercontent.com/87669813/228229794-96925668-5ddc-466b-abb1-4115f7581327.png">

its prevalence during 2023 in Taiwan was 27 sequences out of 306 globally foud searching for Taiwan/2023 on Gisaid.
but it was 18/128 in February maybe pointing that it managed to gain shares there.

**Comment by aviczhl2** [comment]
samples uploads from Taiwan are mostly imported cases. Exclude them, then you get a much higher ‘local share“ for the variant.

**Comment by FedeGueli** [comment]
This grew to 208. Last sequences coming in : from Singapore (2 local + 2 imported from TW) Taiwan and Japan.

Looking at samples from March only it is 4 out of 36 sequences. 2 out of 15 considering just the ones sampled in Taiwan

**Comment by FedeGueli** [comment]
251 sequences as today also sampled in New Zealand. Worth designating due its local relevance and international spread notwithstanding the fact is surely less transmissible than 486P carrying lineages

**Comment by FedeGueli** [comment]
274 sequences, 37 out of 274 from Taiwan or travellers from Taiwan.

The tree shows a lot of diversity and very little clustering both for countries and for timing ( i mean last sequences are all scattered in the tree) 
and it is quite strikingly that the biggest branch of this lineage counts only 21 sequences 
<img width="1162" alt="Screenshot 2023-04-16 alle 08 03 29" src="https://user-images.githubusercontent.com/87669813/232274733-f2f6c0e9-efc7-4fe4-87f5-c0b176e7ffcc.png">
<img width="1160" alt="Screenshot 2023-04-16 alle 08 03 48" src="https://user-images.githubusercontent.com/87669813/232274743-ca5e6d30-a3bc-40b1-bf1d-0510b7c3854b.png">
<img width="971" alt="Screenshot 2023-04-16 alle 08 04 38" src="https://user-images.githubusercontent.com/87669813/232274786-64ff3885-8bf6-40d2-b614-20242ac3ac31.png">

My guess these data point to a prolonged not very fast local circulation in an undersampled area likely Taiwan

**Comment by aviczhl2** [comment]
Do you find any GenBase seqs on this tree? They are not on GISAID but they've been added to usher recently.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage FR.1 with 244 newly designated sequences, and 4 updated. Defining mutations C29370T (N:T366I), C25572T (following C1513T).

**Comment by ryhisner** [comment]
Has anyone noticed that this lineage has a frameshift in ORF7b? GISAID, Nextclade, and BLAST all call it a one-nucleotide insertion: ins27791T. This corresponds to the third nucleotide in ORF7b:12. (Nextclade interprets a few sequences as having 2, 3, 4, 5, or 6 inserted T's at the same position These don't seem especially closely related though, so I suspect those are misreads, probably due to the fact that five consecutive T's normally follow 27791.) 

Notably, a stop codon doesn't arrive until 27851-27853, which, after the 1-nucleotide insertion, corresponds to ORF7b:33. So ORF7b's AA composition is changed dramatically, but the length of ORF7b is reduced from 43 AA to 32 AA, about a 25% reduction.

I believe the change in the AA composition of ORF7b should be as pictured below. (I did this manually, so there could be errors.) My first impression is that this insertion results in quite a few more polar residues than previously. 
<img width="1462" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/eff6920c-7b1d-4253-a4af-763cd3ea62d8">

**Comment by FedeGueli** [comment]
Great catch Ryan! @ryhisner

**Comment by ryhisner** [comment]
Actually, I think the new ORF7b this creates is much more widespread than just FR.1. I've noticed a recent trend for frameshift-causing, two-nucleotide deletions in this same area of ORF7b, but I didn't look into them very closely. I believe they should create the same modified, somewhat truncated version of ORF7b as the one-nucleotide insertion in FR.1 does. 
<img width="1402" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/865d5762-639d-4a50-ad38-eb2c55af002b">

**Comment by ryhisner** [comment]
I noticed that there's a synonymous ORF7b nuc mutation in all Omicron (C28007T) that makes a slight change in the sequence of the new version of ORF7b this creates. It's a small change: alanine to valine in the sixth residue after the insertion. XBC* does not have this mutation, so its sequence remains the same. I've put the sequences next to the old ORF7b sequence, with polar and charges residues in red and nonpolar residues in black.  
<img width="1481" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/e9349520-898a-4de3-ad11-860ad8c8e955">

**Comment by FedeGueli** [comment]
Wow @ryhisner great work.
FR.1 is scoring very high in  Collection42 by @alurqu  , partially due the fact China is uploading fastly and a lot, but still its significance could be beyond the simply acknowledgement of something new

**Comment by FedeGueli** [comment]
Look here what happened in XBC.1.1.2  @ryhisner it got a mutation right before the new stop codon:
![Schermata 2023-06-13 alle 19 47 41](https://github.com/cov-lineages/pango-designation/assets/87669813/608bf773-52c3-4077-99cd-1e2da07009a8)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_17adb_88fb00.json?c=userOrOld&label=id:node_6126821
