### ISSUE TITLE
CH.1.1.12 sublineage with Orf1a:Q3966R competing with XBB.1*486P variants in Denmark ( 147 Sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1816]
This was discovered due a great spot by Benedict Barclay on twitter ([HERE to read](https://twitter.com/BarclayBenedict/status/1640655999626366977?s=20))

He noticed that CH.1.1.12 in Denmark was not declining and instead has reached a share above 10%.

At a first check @josetteshoenma @alurqu and me spot have spotted one sublineage rising fast in Denmark as share of CH.1.1.12.
And curiously once again it was not defined by a spike mutation but by a NSP8 mutation, ( A12162G interestingly very close to BA.5 defining synonymous mutation G12160A cc @alurqu please share your analysis here!) that corresponds to orf1a:Q3966R 

Orf1a:Q3966R is not a new mutation in this pandemic : it emerged very early in Alpha reaching **69K** sequences and a maximum global share of 6% at the start of April 2021:
<img width="1087" alt="Schermata 2023-03-28 alle 22 11 16" src="https://user-images.githubusercontent.com/87669813/228355578-a038a7c3-8b4b-49de-a96a-35b99537c48d.png">
here the global Alpha Tree with this mutation:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_34069_349dd0.json?f_userOrOld=uploaded%20sample&label=id:node_8913109
<img width="1033" alt="Schermata 2023-03-28 alle 22 13 40" src="https://user-images.githubusercontent.com/87669813/228356111-b0fd3be7-5340-4bb4-ac5e-39f6097d0730.png">
Globally its apaprent advantage over plain alpha was around 5% in 2021
<img width="966" alt="Schermata 2023-03-28 alle 22 16 42" src="https://user-images.githubusercontent.com/87669813/228356731-89289e61-9668-4cc5-ae74-3a7cf22de6fa.png">

Beyond Alpha it recurrently popped up in various vocs:
<img width="890" alt="Schermata 2023-03-28 alle 22 15 26" src="https://user-images.githubusercontent.com/87669813/228356475-65d5526a-4275-43c3-a473-a2e515775027.png">

Weirdly it was never proposed nor mentioned in the whole Pango Designation Rep.

Coming back to our days:

Defining Mutations:
CH.1.1.12 >> Orf1a:Q3966R (A12162G =NSP8_Q24R)

Tree:
<img width="1136" alt="Schermata 2023-03-28 alle 22 20 29" src="https://user-images.githubusercontent.com/87669813/228357522-237bcca5-8486-484f-9ca2-1ae8926c64ab.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_350a7_2dd100.json?c=gt-ORF1ab_3966&label=id:node_8092323

Gisaid query: C6016T,A12162G,C24134A

Sequences:
EPI_ISL_16408537, EPI_ISL_16503204, EPI_ISL_16503290,
EPI_ISL_16503307, EPI_ISL_16503598, EPI_ISL_16515292,
EPI_ISL_16547768, EPI_ISL_16547821, EPI_ISL_16547970,
EPI_ISL_16548138, EPI_ISL_16646874, EPI_ISL_16647097,
EPI_ISL_16697621, EPI_ISL_16697645, EPI_ISL_16697649,
EPI_ISL_16749696, EPI_ISL_16749818, EPI_ISL_16856559,
EPI_ISL_16856698, EPI_ISL_16856797, EPI_ISL_16857091,
EPI_ISL_16866486, EPI_ISL_16912548, EPI_ISL_16912556,
EPI_ISL_16938752, EPI_ISL_16938778, EPI_ISL_16938792,
EPI_ISL_16938829, EPI_ISL_16938998, EPI_ISL_16985225,
EPI_ISL_16985240, EPI_ISL_16985407, EPI_ISL_17007580,
EPI_ISL_17007651-17007652, EPI_ISL_17007661, EPI_ISL_17007715,
EPI_ISL_17048498, EPI_ISL_17048508, EPI_ISL_17048581,
EPI_ISL_17048702, EPI_ISL_17048721, EPI_ISL_17048838,
EPI_ISL_17048927, EPI_ISL_17155362, EPI_ISL_17155424,
EPI_ISL_17155490, EPI_ISL_17155507, EPI_ISL_17155509,
EPI_ISL_17155565, EPI_ISL_17155570, EPI_ISL_17155630,
EPI_ISL_17155641, EPI_ISL_17155647, EPI_ISL_17210298,
EPI_ISL_17210358, EPI_ISL_17210362, EPI_ISL_17210365,
EPI_ISL_17210384, EPI_ISL_17210431, EPI_ISL_17210502,
EPI_ISL_17218585, EPI_ISL_17221869, EPI_ISL_17242664,
EPI_ISL_17257673, EPI_ISL_17257693, EPI_ISL_17257745,
EPI_ISL_17257764, EPI_ISL_17257775, EPI_ISL_17257799,
EPI_ISL_17257802, EPI_ISL_17257875, EPI_ISL_17257913,
EPI_ISL_17268865, EPI_ISL_17268979, EPI_ISL_17269001,
EPI_ISL_17269037, EPI_ISL_17269074, EPI_ISL_17269080,
EPI_ISL_17269097, EPI_ISL_17269140, EPI_ISL_17269223,
EPI_ISL_17269234, EPI_ISL_17269269, EPI_ISL_17269272,
EPI_ISL_17269281, EPI_ISL_17269302, EPI_ISL_17269320,
EPI_ISL_17269352, EPI_ISL_17269380, EPI_ISL_17269388,
EPI_ISL_17269408, EPI_ISL_17269417, EPI_ISL_17315148,
EPI_ISL_17315243, EPI_ISL_17315299, EPI_ISL_17315381,
EPI_ISL_17315428, EPI_ISL_17315472, EPI_ISL_17315496,
EPI_ISL_17315512, EPI_ISL_17315550, EPI_ISL_17315602,
EPI_ISL_17315694, EPI_ISL_17315761

Growth Advantage:
Looking at the last two months this sublineage has a comparable growth versus all XBB.1 sublineagees carrying S:F486P
<img width="967" alt="Schermata 2023-03-28 alle 22 24 38" src="https://user-images.githubusercontent.com/87669813/228358396-158e3465-2bea-4b6e-bd49-e9e0c6470b93.png">

And its growth is comparable to the XBB.1.9+S:F486P one (likely slower than .1 faster than .2 but that could be influenced by importation  rates, especially in a not so big country as Denmark)
<img width="949" alt="Schermata 2023-03-28 alle 22 26 23" src="https://user-images.githubusercontent.com/87669813/228358764-ac2f966c-5a93-4160-873e-aa55cd484594.png">

Covspectrum tools: https://cov-spectrum.org/explore/Denmark/AllSamples/Past3M/variants?aaMutations=S%3A486P&nextcladePangoLineage=XBB.1*&nucMutations1=C6016T%2CA12162G%2CC24134A&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
121 seqs s today. For the first tima a sample came from Luxembourg too

**Comment by alurqu** [comment]
This sublineage has also been noted to have a mutation that appears on some tools such as CoV-Spectrum as ORF1a:M85V (see https://twitter.com/mrmickme/status/1640905141992964097).

Looking at it, “ORF1a:M85V” is actually a 9-nucleotide deletion at 510-518 starting at the second nucleotide of the ORF1a:G82 and extending to the first nucleotide of ORF1a:M85. Tools call cases like this weird so some but not all will show ORF1a:M85V. For instance CoV-Spectrum shows ORF1a:M85V, but I don’t see it on the UShER phylogenetic tree. That is very likely due to differences in how the tools handle the deletion. But functionally this deletion changes ORF1a:82-85 from GHVM to simply V without a nucleotide change.

As far as I can tell, this 510-518 deletion happened somewhere along the evolutionary path from CH.1.1 to CH.1.1.12. I also note that recently-designated CH.1.1.21 has a different but similar 509-523 deletion that spans all of ORF1a:82-86 but is codon aligned.

Functionally, this deletion is in non-structural protein 1 (NSP1) of the ORF1a/ORF1ab polyprotein. NSP1 disrupts translation of host mRNA to proteins by locking host mRNA out of the ribosomes which impacts antiviral defenses such as interferon production, response to interferon stimulation, and likely just about every other cellular process. (Low et al https://www.mdpi.com/1999-4915/14/9/1991). If these deletions are in loop 3-4 of NSP1, they may particularly impact host translational processes. (https://compsysbio.ornl.gov/nonstructural-protein-1-nsp1/)

**Comment by FedeGueli** [comment]
Thanks @alurqu ! Orf1a:85 del was tracked for long time by @bitbyte2015 and discussed together with @thomasppeacock @corneliusroemer  several times. It was a del popping up several times reaching a  max of 5% in BA.2 era i think (i m going by memory so maybe wrong)

**Comment by FedeGueli** [comment]
France and England and  it reached 133.

**Comment by FedeGueli** [comment]
Looking at the tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_b3fc_16f6c0.json?c=country&label=id:node_8154487
![Schermata 2023-04-08 alle 16 42 33](https://user-images.githubusercontent.com/87669813/230727341-6c964fdc-160b-4b87-a5dd-5298a6f2e975.png)


It seems that this branch has gained further mutations, especially the branch with S:M1229I seems to be faster than the rest: https://cov-spectrum.org/explore/Denmark/AllSamples/Past3M/variants?aaMutations=ORF1a%3AQ3966R&nextcladePangoLineage=CH.1.1.12*&aaMutations1=S%3AM1229I&nextcladePangoLineage1=CH.1.1.12*&analysisMode=CompareToBaseline&



But also the other branches are showing very interesting evolution like in this case with 3 additional Spike mutations (186,556,614S) and one N mutation at defining BA.4 residue 151.
![Schermata 2023-04-08 alle 16 43 32](https://user-images.githubusercontent.com/87669813/230727388-6d3d0784-0149-46ff-b936-49d74473fe3d.png)

**Comment by FedeGueli** [comment]
147 sequences as today. Still just in Denmark

**Comment by FedeGueli** [comment]
160 sequences as today . newly found in Italy, France and Israel.

**Comment by FedeGueli** [comment]
![Schermata 2023-04-18 alle 11 37 18](https://user-images.githubusercontent.com/87669813/232736910-dbbe8ef7-89dc-4dba-a21b-ce3a9d69e232.png)
currently around 4% in Denmark

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage FS.1 with 111 newly designated sequences, and 24 updated. Defining mutation A12162G (ORF1a:Q3966R) (following C24134A (S:L858I), nt:C6016T).
