### ISSUE TITLE
XBB.1.9.1 with S:P681R [7 sequences, France and Germany]

### ISSUE THREAD

**Issue by Outpfmance** [cov-lineages/pango-designation#1819]
XBB.1.9.1 also has H681R after XBB.1 and XBB.1.5. Although P681R may not play a more effective role than P681H due to Omicron's FCS architecture and N969K, the sublines with this mutation are still noteworthy.
Cov-spectrum query: https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-02-01%26to%3D2023-03-14/variants?aaMutations=s%3A681r&nextcladePangoLineage=XBB.1.9.1&

Nextstrain: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_346e7_468760.json?f_userOrOld=uploaded%20sample&label=id:node_4664042

Two of the French sequences are ORF3a:V202aA
Sequences:EPI_ISL_17300463 EPI_ISL_17300464 EPI_ISL_17264715
![09473DF0-4B5D-4DFF-BBC0-5F3A8AFBAFE8](https://user-images.githubusercontent.com/125484893/228893439-e2d360dc-4a3d-43b1-9380-d3b9b7d4cecb.jpeg)

**Comment by Outpfmance** [comment]
![](edge://external-file/IMG_2619.jpg)

**Comment by Outpfmance** [comment]
![](edge://external-file/IMG_2619.jpg)

**Comment by Outpfmance** [comment]
7 sequences now.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_23062_7dfc60.json?f_userOrOld=uploaded%20sample&label=id:node_3141584
![IMG_0148](https://user-images.githubusercontent.com/125484893/234306863-29333979-0318-43c6-8ecd-de0a487f7362.jpeg)

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As these have since been designated as a small part of FL.5, the original clade as defined did not show subsequent growth, and the clade defined by S:681R is currently not clear on the usher tree; this can be closed for now. Please re-propose if an associated pango lineage proposal remains relevant here.
