### ISSUE TITLE
Another Peruvian C.X lineage with conserved spike mutations - D138Y, S477N, S939F

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#182]
**New proposed lineage
By Tom Peacock**

**Description**
**Sub-lineage of:** B.1.1.1
**Earliest Sequence:** 2020-12-14
**Latest Sequence:** 2021-04-16
**Countries circulating:** Peru (26 genomes)

**Description:**
Conserved Spike mutations - D138Y, V143D/del144*, S477N, D614G, S939F (*found in some, but not all, sequences)

Conserved non-Spike mutations - NSP3 – T428I, T724I, G1691D; NSP4 – T439M; NSP5 – G15S; NSP12 – P323L; NSP13 – F145V, G203C, V496L;  ORF8 -  TRS mutation, Q91L; N - R203K, G204R

Yet another C.X lineage from this region - sequences are maybe a little old but many have only been uploaded in last month which implies more are likely on their way.

**Genomes:**

[PeruC1X.txt](https://github.com/cov-lineages/pango-designation/files/6982493/PeruC1X.txt)

**Evidence:**

![image](https://user-images.githubusercontent.com/79373149/129359276-69851a1b-f123-4574-912e-8436aea11ce4.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_15a03_6676a0.json?c=pango_lineage

**Proposed lineage name:** C.X

**Comment by chrisruis** [comment]
Thanks @thomasppeacock. It looks like the most recent sequence in this clade is from 16/04/2021. We wouldn't normally designate a new lineage if it would be unobserved (not seen in >3 months) at the point of designation so we won't designate this one for now. But please do reopen this if you see additional more recent sequences clustering in this clade

**Comment by thomasppeacock** [comment]
Yeah completely understand - new sequences are still being uploaded but as you say they're mostly from the beginning of the year so very unclear if this lineage still exists (and lack of more recent international samples would suggest maybe not, or at least not widely)
