### ISSUE TITLE
XBB.1.16 with orf9b:T24S started in India(293 seqs, 31 countries )

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1820]
Sub-lineage of: XBB.1.16
Mutations on top of XBB.1.16: A28353T (orf9b:T24S, N:N27I) , C29386T
GISAID query: T28297C, A28353T
No. of seqs: 16(India 16)
First seq: EPI_ISL_17236461 (India) 2023-3-1
Latest seq: EPI_ISL_17326218(India) 2023-3-17
Sequences: 
EPI_ISL_17236461, EPI_ISL_17236463, EPI_ISL_17269904,
EPI_ISL_17269908, EPI_ISL_17269927, EPI_ISL_17269939,
EPI_ISL_17269950, EPI_ISL_17269993, EPI_ISL_17270042,
EPI_ISL_17270044, EPI_ISL_17326043, EPI_ISL_17326169,
EPI_ISL_17326190, EPI_ISL_17326218, EPI_ISL_17326224,
EPI_ISL_17326236

Usher shows that there is a major branch with some singlets hiding in artefact reversion branches.
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_222ad_503520.json?c=gt-nuc_28353)

<img width="1402" alt="Screen Shot 2023-03-30 at 11 55 24" src="https://user-images.githubusercontent.com/10445944/228725341-d175fc95-5461-4016-8fe2-75035764cd1c.png">

[this paper](https://link.springer.com/content/pdf/10.1007/s11427-022-2168-8.pdf) says orf9b:24 is one of the variable site among the residues involved in the formation of dimeric orf9b. 
>Of the 15 residues involved in the formation of dimeric ORF9b, only six (A22/T24/P51/N55/R58/K59) were variable, while the others were highly conserved. 

Orf9b:T24 mutations occurred in many previous seqs, but T24S was very rare, and have negative fitness score on previous backbones. However, this mutation always groups up with other orf9b mutations in previous seqs. (P10S, D16G or P60A) So it may make a difference given XBB.1.16's orf9b being different from original.

**Comment by aviczhl2** [comment]
17 seqs and detected in USA

**Comment by aviczhl2** [comment]
62 seqs now.

**Comment by aviczhl2** [comment]
66 seqs and detected in Switzerland.

**Comment by aviczhl2** [comment]
<img width="1006" alt="Screen Shot 2023-04-17 at 02 12 32" src="https://user-images.githubusercontent.com/10445944/232333184-034c7c12-37f0-46ab-a11f-1426769fa80d.png">
Wow, 45% growth advantage against XBB.1.16 in India.

**Comment by aviczhl2** [comment]
116 now and in Canada.  @corneliusroemer I think this one satisfies a designation now? Despite compared with others it appears less frequently outside India.

**Comment by aviczhl2** [comment]
135 seqs, massive upload from Canada and detected in Thailand .

**Comment by aviczhl2** [comment]
152 seqs and in China and Japan.

**Comment by aviczhl2** [comment]
157 seqs, Austria, France and Portugal

**Comment by aviczhl2** [comment]
172 seqs, Sweden

**Comment by aviczhl2** [comment]
182, Luxemburg

**Comment by aviczhl2** [comment]
183, South Korea

**Comment by aviczhl2** [comment]
187, Trinidad and Tobago

**Comment by aviczhl2** [comment]
194, Netherlands

**Comment by aviczhl2** [comment]
+1 Uganda

**Comment by aviczhl2** [comment]
198, Israel

**Comment by aviczhl2** [comment]
213, Norway

**Comment by aviczhl2** [comment]
222, Germany, Denmark

**Comment by aviczhl2** [comment]
229, Spain

**Comment by aviczhl2** [comment]
248, Croatia

**Comment by aviczhl2** [comment]
256, Sweden

**Comment by FedeGueli** [comment]
New leaders coming and this not so much to do : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=T28297C%2CA28353T&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
266, Grenada

**Comment by aviczhl2** [comment]
274, Italy

**Comment by aviczhl2** [comment]
279, Albania

**Comment by aviczhl2** [comment]
283, Australia

**Comment by aviczhl2** [comment]
286, Oman

**Comment by FedeGueli** [comment]
Thanks for tracking it! this lasted trhough october with no Spike mutation over original xbb.1.16. As we already saw in BA.5.1 in japan Orf9b mutations alone sometimes allow persistance of apparently outdated lineages. cc @ryhisner.
