### ISSUE TITLE
XBB.2.3 with orf1a:L3829F emerging in India (68 seqs, 7 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1821]
The highly-convergent orf1a:L3829F mutation is emerging in XBB.2.3 in 2023.3 too. 

Sub-lineage of: XBB.2.3
Mutations on top of XBB.2.3: G29706T, C6781T, T11750C(orf1a:L3829F)
original proposal GISAID query: C6781T,C11750T,G6536A
current query: C11750T, G6536A, C4234T,-A22996T
No. of seqs: 20 (India 17, USA 3)
First seq: EPI_ISL_16497404(India) 2022-12-23
Latest seq: EPI_ISL_17326325(India) 2023-3-17

Only 2 are in 2022.12, all other 18 are sampled in 2023.3

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_222ad_503530.json?label=id:node_7870999)
<img width="1396" alt="Screen Shot 2023-03-30 at 12 17 30" src="https://user-images.githubusercontent.com/10445944/228729553-fb88ff47-b93a-45b2-bf2c-e0315548c486.png">

**Comment by aviczhl2** [comment]
22 seqs and detected in australia and Israel.

**Comment by aviczhl2** [comment]
<img width="1381" alt="Screen Shot 2023-04-09 at 18 42 06" src="https://user-images.githubusercontent.com/10445944/230768091-be274ff4-c50c-4904-b304-bd5538c12430.png">

Seems that the tree structure is now reassigned as many seqs without C6781T but also having orf1a:L3829F has been detected. (Probably are different branches as orf1a:L3829F is highly homoplastic)

**Comment by aviczhl2** [comment]
55 seqs now.

**Comment by aviczhl2** [comment]
57 seqs but 7 belongs to #1895 
So have to alter the query again. 
Query now shall be: C11750T, G6536A, C4234T,-A22996T

**Comment by aviczhl2** [comment]
One major branch of this has the same orf3a:V13L mutation as XBB.1.16. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice8_genome_173a6_2dee10.json?label=id:node_6069378)

**Comment by FedeGueli** [comment]
> One major branch of this has the same orf3a:V13L mutation as XBB.1.16 branch.
> 
> [usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice8_genome_173a6_2dee10.json?label=id:node_6069378) <img alt="Screen Shot 2023-04-22 at 03 16 55" width="1351" src="https://user-images.githubusercontent.com/10445944/233717189-c69663e4-7695-4fbd-aa1c-cebaee4aa01e.png">

Curiously it was never proposed before these two events and do not remember it as part of any main sublineage also as not defining even if it popped up already 15k and more times since the start of the pandemic .
Still looking briefly back seems to have gained some time of glory at the start of the first Uk wave with B.1 and then B.1.1.7 , Ay.4 , Ay.103 through all omicron lineages.
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=Orf3a%3AV13L&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

**Comment by corneliusroemer** [comment]
orf1a:L3829F is known to be very homoplasic, so best not to use it as lineage defining (tree likely wrong)

Also there are only ~50 sequences so far, not many, so best to avoid this one for now.
