### ISSUE TITLE
Proposal for BF.7.15 sublineage with ORF1a:A3969T in Japan (2139 seqs as of 2023/03/30. 2127 seqs in Japan)

### ISSUE THREAD

**Issue by takaabe8050** [cov-lineages/pango-designation#1823]
By Japan COVID-19 Open Data Consortium

Description
Sub-lineage of: BF.7.15 (2,139 sequences)
Earliest sequences: 2022/9/27 (hCoV-19/Japan/PG-428825/2022, hCoV-19/Japan/PG-428826/2022, hCoV-19/Japan/PG-428827/2022)
Most recent sequences: 2023/03/12 (hCoV-19/Japan/PG-461964/2023, hCoV-19/Japan/PG-461965/2023)
Countries circulating: Japan (2,127 seqs), Singapore (4), China (2), South Korea (2), United States (1), India (1), Italy (1), Germany (1)

This proposal sublineage is 66.8 % of all BF.7.15 in Japan.

Associated mutations
G12170A (ORF1a:A3969T)

Genomes
[genome_list.txt](https://github.com/cov-lineages/pango-designation/files/11108581/genome_list.txt)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3ddab_527540.json?c=userOrOld&f_userOrOld=uploaded%20sample

 
![image](https://user-images.githubusercontent.com/89957075/228751121-e0d67be0-f379-4b7e-89cf-c84fa182ac70.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ddab_527540.json?f_userOrOld=uploaded%20sample

 
![image](https://user-images.githubusercontent.com/89957075/228751158-6eaad351-98ab-46ce-a656-f75c661b6b5e.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=G12170A&pangoLineage=BF.7.15&

 
![image](https://user-images.githubusercontent.com/89957075/228751182-7d987899-a266-4a29-b7ad-bf5c8979923b.png)

Proposed lineage name
Next BF.7.15

**Comment by DailyCovidCases** [comment]
Please close this issue
