### ISSUE TITLE
Proposal for a new sub-lineage of XBB.1.16 with Spike S494P mutation circulating in India, Japan, Singapore, Australia & USA - 17 Sequences)

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#1824]
XBB.1.16 sub-lineage with Spike S494P mutation

[Proposed this early considering the importance of this spike RBD mutation]

Earliest Sample Collection Date: 3/10/2023 (from Aurangabad, Maharashtra, India)
Circulating in Gujarat and Maharashtra

GISAID Query: T12730A, T28297C, A28447G, T23042C
CoV-Spectrum Query: T12730A, T28297C, A28447G, T23042C

GISAID IDs: EPI_ISL_17242503, EPI_ISL_17244678, EPI_ISL_17318654, EPI_ISL_17326235

![image](https://user-images.githubusercontent.com/98380390/228759045-1508dc37-016b-4ac5-82eb-535103ed7e76.png)

![image](https://user-images.githubusercontent.com/98380390/228759104-67ac9ba0-ab94-4862-9e2c-f1508d4443e1.png)

**Comment by RajLABN** [comment]
Two more XBB.1.16 with Spike 494P popped up in USA (California and New Jersey) via airport surveillance. [Travelers from India; both asymptomatic]

GISAID IDs: EPI_ISL_17387008, EPI_ISL_17387069

**Comment by RajLABN** [comment]
One more XBB.1.16 with Spike S494P from Victoria, Australia - EPI_ISL_17409304

**Comment by RajLABN** [comment]
Two more  XBB.1.16 with Spike S494P from Maharashtra, India (EPI_ISL_17530377, EPI_ISL_17530418)

**Comment by corneliusroemer** [comment]
Still too small, 494P hasn't been doing much in XBB

**Comment by RajLABN** [comment]
8 more XBB.1.16 with S:494P from Japan (they also have S:T547I >> XBB.1.16.1

**Comment by FedeGueli** [comment]
@RajLABN i think this last sublienage with S:G184S is indipendent from the one proposed here and should be proposed separately, in fact it belongs to XBB.1.16. And while the travel history is not clear consider that Vietnam realted samples are just 82 since 20th march so if all of them has travel history with Vietnam (unclear) it would mean a rough  prevalence around 10% : https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_aea2_bb37f0.json?f_userOrOld=uploaded%20sample&label=id:node_10066505

**Comment by RajLABN** [comment]
Two more XBB.1.16 + S:494P from India (EPI_ISL_17591524, EPI_ISL_17600021)

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. It is showing relative growth disadvantages over the past 2-3months, and little growth in terms of new detections. The XBB.1.16.1 lineage mentioned by @FedeGueli above, might be, or come to be, a slightly better candidate, to be proposed separately. In any case this can be closed for now, but please request re-opening should it start showing some steady, strong growth at some point.
