### ISSUE TITLE
Proposal for potential new sublineage of XBB.1.5 in the UK with Orf1a: S443F A1851V Orf1b: A1624G S: G184S Orf7a: G38V

### ISSUE THREAD

**Issue by UnusualTimes** [cov-lineages/pango-designation#1825]
Proposal for potential new sublineage of XBB.1.5 in the UK with 

Orf1a: S443F A1851V 
Orf1b: A1624G 
S: G184S 
Orf7a: G38V

few samples then a cluster in epiweek 168 may be nothing but worth watching since its probably fast

sequence_name | sample_date | epi_week | epi_date | lineage
-- | -- | -- | -- | --
England/BRBR-3270BF26/2023 | 20/03/2023 | 169 | 19/03/2023 | XBB.1.5
England/BRBR-3270BF17/2023 | 20/03/2023 | 169 | 19/03/2023 | XBB.1.5
England/BRBR-327097C6/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-327096C9/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-327097B7/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-327097D5/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-327097A8/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32707625/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-3270735B/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-3270779B/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32707018/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-3270786B/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-327074D0/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32707133/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32707555/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-327075CE/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32706DA9/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-3270740D/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32707458/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-327078A7/2023 | 16/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/PHEC-YYEPCTX/2023 | 14/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-327041FA/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32703FB5/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32703F4C/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-3270427F/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-3270402A/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32704118/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-327034F2/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32703683/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32703629/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-3270337D/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32703489/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-327036CF/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32703340/2023 | 13/03/2023 | 168 | 12/03/2023 | XBB.1.5
England/BRBR-32700905/2023 | 10/03/2023 | 167 | 05/03/2023 | XBB.1.5
Scotland/QEUH-327033B9/2023 | 07/03/2023 | 167 | 05/03/2023 | DV.1
England/PHEC-YYEK3WN/2023 | 07/03/2023 | 167 | 05/03/2023 | XBB.1.5
Wales/PHWC-PKP1RE/2023 | 06/03/2023 | 167 | 05/03/2023 | BQ.1.1.2
England/QEUH-326EBC62/2023 | 26/02/2023 | 166 | 26/02/2023 | XBB.1.5
Wales/PHWC-PKCAA5/2023 | 26/02/2023 | 166 | 26/02/2023 | XBB.1.5
England/PHEC-YYEJP4R/2023 | 25/02/2023 | 165 | 19/02/2023 | BQ.1.1.32
Wales/PHWC-PKCSA7/2023 | 25/02/2023 | 165 | 19/02/2023 | XBB.1.5

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there don't seem to have been any new detections over the past month, and there has been no evidence for a strong relative growth advantage (in fact the relative growth has been strongly negative over the past two months), this can be closed for now. Please request re-opening should it reemerge as a demonstrably fast lineage.
