### ISSUE TITLE
XBB.1 Sublineage with S:Y453F, ORF7a:A50S, ORF1a:E148D, ORF1a:L642F, ORF1a:T2121I, ORF1b:L2497I (8 seq, Mar 30)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1827]
### **Description**
**Sub-lineage of:** XBB.1
**Earliest sequence:** 2023-2-23, Philippines, Davao — EPI_ISL_17343863
**Most recent sequence:** 2023-3-6, Philippines, Davao — EPI_ISL_17343910 + 5 others
**Countries circulating:** Philippines (Davao)
**Number of Sequences:** 8
**GISAID AA Query:** Spike_Y453F, NSP1_E148D, NSP3_T1303I
**GISAID Nucleotide Query:** G709T, C6627T, A22920T
**CovSpectrum Query:** Nextcladepangolineage:XBB.1* & A22920T & [3-of: G709T, C2189T, C6627T, T3676C, T14865C, C20956A, G27541T]
**Substitutions on top of XBB.1:**
**Spike:** Y453F
**ORF7a:** A50S
**ORF1a:** E148D, L642F, T2121I (NSP1_E148D, NSP2_L462F, NSP3_T1303I)
**ORF1b:** L2497I (NSP16_L100I)
**Nucleotide:** G709T, C2189T, C6627T, T3676C, T13704C, T14865C, C20956A, A22920T, G27541T

**USHER Tree**
Note: As is typical for sequences from the Philippines, coverage is spotty, so there are several artifactual reversions on the tree, especially in the S:360-417 area.
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1_Y453F_ORF7aA50S_subtreeAuspice1_genome_43047_572970.json  
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/33738461/228832540-5609b820-d018-47ba-b345-00822b05793d.png">

**Evidence**
The Philippines recently uploaded 147 sequences collected between Feb 13 and Mar 7. A majority (75) were still BA.2.3.20*, which remarkably continues to maintain dominance there, despite being driven to negligible levels elsewhere in the world. But 8/147 sequences (5.4%) were from this XBB.1 sublineage. Furthermore, six of the eight sequences were collected on March 6, which puts them among the 20 most recently collected sequences from this upload. 

Six of the eight sequences also have ORF1a:A2123V. One sequence has S:N450D and another has S:E281Q, S:A845S, and ORF1a:D2296E. Two have ORF1a:C3301G (NSP5_C38G).

In addition to being a mutation associated with mink outbreaks, S:Y453F increases ACE2 binding strength by more than any other known mutation on a BA.2 background according to the Bloom Lab RBD Heat Map.

<img width="985" alt="image" src="https://user-images.githubusercontent.com/33738461/228833301-4cf8948a-6da5-482f-b839-a88dd00dbf71.png">
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17343831, EPI_ISL_17343863, EPI_ISL_17343901, EPI_ISL_17343903, EPI_ISL_17343904, EPI_IDL_17343905, EPI_ISL_17343907, EPI_ISL_17343910
</details>

**Comment by FedeGueli** [comment]
Sorry i didnt see it was already proposed!
