### ISSUE TITLE
XBB.1.9.3 with S:L212S (73 seq, 14 countries)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1828]
Proposal for a sublineage of XBB.1.9.3
Earliest sequence: 21.12.2022 (England)
Countries detected: England, Netherlands, Ireland, Spain, Singapore, Germany, India, Malaysia, France, Indonesia, USA, Austria, Philippines, Bahrain

Defining Mutations
nuc	unique	T22197C
S	unique	L212S

Gisaid query: T22197C, G18169T

![grafik](https://user-images.githubusercontent.com/102166254/228849231-4e3b8b2f-a06d-41ed-bb62-d4b0118d0da8.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24f4e_58a5a0.json?c=gt-S_212

![grafik](https://user-images.githubusercontent.com/102166254/228849034-fd4b0b24-50c1-4ec8-b01b-8115d2150dee.png)

EPI_ISL_16352468, EPI_ISL_16364062, EPI_ISL_16364066, EPI_ISL_16364073, EPI_ISL_16428182, EPI_ISL_16437501, EPI_ISL_16446435, EPI_ISL_16509455, EPI_ISL_16529247, EPI_ISL_16600945, EPI_ISL_16601018, EPI_ISL_16613280, EPI_ISL_16645278, EPI_ISL_16645279, EPI_ISL_16645296, EPI_ISL_16645297, EPI_ISL_16645298, EPI_ISL_16645299, EPI_ISL_16645300, EPI_ISL_16645301, EPI_ISL_16645302, EPI_ISL_16645303, EPI_ISL_16645306, EPI_ISL_16645307, EPI_ISL_16676343, EPI_ISL_16697259, EPI_ISL_16760415, EPI_ISL_16760420, EPI_ISL_16760421, EPI_ISL_16760487, EPI_ISL_16807783, EPI_ISL_16823335, EPI_ISL_16885387, EPI_ISL_16908537, EPI_ISL_16946759, EPI_ISL_16947580, EPI_ISL_16958367, EPI_ISL_17003032, EPI_ISL_17003041, EPI_ISL_17012245, EPI_ISL_17012483, EPI_ISL_17018050, EPI_ISL_17022868, EPI_ISL_17022870, EPI_ISL_17039343, EPI_ISL_17048959, EPI_ISL_17152979, EPI_ISL_17199559, EPI_ISL_17343833, EPI_ISL_17343838, EPI_ISL_17343839, EPI_ISL_17343841, EPI_ISL_17343847, EPI_ISL_17343856, EPI_ISL_17343864, EPI_ISL_17343875, EPI_ISL_17343899, EPI_ISL_17343900, EPI_ISL_17343933, EPI_ISL_17344369, EPI_ISL_17344372, EPI_ISL_17344378, EPI_ISL_17344379, EPI_ISL_17344382, EPI_ISL_17344383, EPI_ISL_17344385

OQ439101.1
OQ466982.1
OX415279.1
OX453997.1

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there have been few new detections since proposal, and correspondingly negative growth advantages, this can be closed for now. Please request re-opening should this reemerge as a fast growing lineage.
