### ISSUE TITLE
Proposal for 2 potential sublineages of B.1.1.7 circulating in France

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#183]
**Proposed new sublineage 1**
Currently classified as B.1.1.7 (63 sequences in France, 2 in Belgium and 1 in Spain)
**Earliest sequence**: 2021/6/8 (France)
**Most recent sequence**: 2021/7/24 (France)
**Mutations in addition to B.1.1.7:**
**N:** H300Y
**ORF8:** V62L, 66/67DEL, K68E
Some of the more recent sequences (since 2021-07-06) have the following additional mutations:
**N:** A35V 
**ORF1a:** A2379V
**ORF1b:** P1223L
**ORF9b:** R32C, A57V
No mutations on spikes though.
**Genomes:** 
[B.1.1.7 proposed sublineage 1.csv](https://github.com/cov-lineages/pango-designation/files/6986267/B.1.1.7.proposed.sublineage.1.csv)
**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/129442669-bbff7a6c-6ef9-4d9f-ad27-fa8b3ed5659f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_577a8_7778f0.json?c=gt-N_35,300&tl=country

**Proposed new sublineage 2**
Currently classified as B.1.1.7 (14 sequences in France)
**Earliest sequence**: 2021/4/15 (France)
**Most recent sequence**: 2021/7/8 (France)
**Mutations in addition to B.1.1.7:**
**ORF1a:** E2268D
**ORF3a:** W131L
**ORF7a:** S81P
**ORF8:** K68stop
**S:** A163V, M177T, L303F, V308L, G485V
Some of the more recent sequences (since 2021-6-18) also have the following additional spike mutations:
**S:** P251L, Y449H, N460K
**Genomes:** 
[B.1.1.7 proposed sublineage 2.csv](https://github.com/cov-lineages/pango-designation/files/6986295/B.1.1.7.proposed.sublineage.2.csv)
**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/129443486-fd0233db-ee08-417b-a31d-b3349bc9b180.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_686b6_68dd20.json?c=gt-S_163,177,303,308,449,460,485

**Comment by shay671** [comment]
Regarding the second variant  - I see that it has 3 mutations in the RBD.   
In all variants seemed so far (variants from the first generation, not variant based variants) there was no more than 3. 

I run a scan of the last B.1.1.7 sequences, And i have to say that it repeats in some variants there that was evolved from B.1.1.7. It seems that this virus has still a lot to evolve.

**Comment by chrisruis** [comment]
Thanks @c19850727. We've added your sublineage 1 as Q.6 and your sublineage 2 as Q.7 in [v1.2.66](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.66).

In both cases, we've taken the ancestor of the lineage back to start with a clear introduction(s) into France. For Q.6, this coincides with C29171T (N:H300Y) and for Q.7, this coincides with A7069C (Orf1ab:E2268D). Therefore Q.7 is wider than your proposed sublineage 2 but as the proposed sublineage 2 only contains a small number of genomes over several months, we haven't given this a further designation at this stage.

Thanks again for submitting
