### ISSUE TITLE
BQ.1.1 with S:S247R, S:Y248N, S:L249S (3 seq., USA, UK)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1830]
Proposal for a sublineage of BQ.1.1
Earliest sequence: 28.02.2023 (USA)
Countries detected: USA, UK

Defining Mutations
nuc	unique	C4794T, C934T, T22303A, T22304A, T22308C, G22309A, T25072C
nuc	homoplasies	T6025C, C19255T, C24337T, C13721T
S	unique	S247R, Y248N, L249S
ORF1ab	homoplasies	P4486L
ORF1ab	unique	S1510F

Gisaid query: Spike_S247R, Spike_Y248N, Spike_L249S

![grafik](https://user-images.githubusercontent.com/102166254/229132224-e4a0502d-ccee-4e92-bb05-1478dd0eed52.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e416_6dc470.json?c=gt-S_248,249

![grafik](https://user-images.githubusercontent.com/102166254/229130716-35c151d1-294b-47e0-bcd5-7aec563c3d53.png)

![grafik](https://user-images.githubusercontent.com/102166254/229130846-6e49d1db-da27-4a5c-99b5-337f64eaa174.png)

EPI_ISL_17363183
EPI_ISL_17298894
EPI_ISL_17249508

**Comment by ryhisner** [comment]
I saw these earlier and was particularly struck by two things: 

• There are sequences in Nevada, USA, and England, a remarkable geographic spread. 
• The synonymous G22309A mutation. No matter what the order in which these two mutations occurred (supposing they occurred sequentially and not simultaneously), this mutation is synonymous. That suggests to me that the whole stretch involving these four nucleotide mutations was borrowed from elsewhere in the genome and acquired all at once. 

I don't have a good way of searching for a given nucleotide sequence; I use BLAST, but it separates every 50 nucleotides with a new line, interrupting the sequence, so searching for the sequence there is very imperfect and time-consuming. If I copy and paste the nucleotides from the fasta into a Word doc, it does the same thing. If anyone knows of a convenient way of getting the full nucleotide list aligned and in one string—and that doesn't require knowledge of coding—I'd love to know it.

**Comment by Codes1985** [comment]
> I saw these earlier and was particularly struck by two things:
> 
> • There are sequences in Nevada, USA, and England, a remarkable geographic spread. • The synonymous G22309A mutation. No matter what the order in which these two mutations occurred (supposing they occurred sequentially and not simultaneously), this mutation is synonymous. That suggests to me that the whole stretch involving these four nucleotide mutations was borrowed from elsewhere in the genome and acquired all at once.
> 
> I don't have a good way of searching for a given nucleotide sequence; I use BLAST, but it separates every 50 nucleotides with a new line, interrupting the sequence, so searching for the sequence there is very imperfect and time-consuming. If I copy and paste the nucleotides from the fasta into a Word doc, it does the same thing. If anyone knows of a convenient way of getting the full nucleotide list aligned and in one string—and that doesn't require knowledge of coding—I'd love to know it.

Hi @ryhisner  You could try [Geneious](https://www.geneious.com/).  It's quite a nice GUI-based bioinformatics platform.  I don't necessarily reccomend it over using command-line tools, but it's really great for visualizing sequence data, and should accommodate your needs.  There is a free trial available, and I think the features your looking for should be free.  Another more old-school, but totally free option is [BioEdit](https://bioedit.software.informer.com/).  You should be able to open a sequence alignment and search for nucleotide strings easily enough!

**Comment by agamedilab** [comment]
+ 2 Netherlands: EPI_ISL_17515826, EPI_ISL_17468173

![grafik](https://user-images.githubusercontent.com/102166254/233557939-78d74789-5bb6-432b-bd79-d824b4c75351.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41327_22b8e0.json?c=userOrOld&label=id:node_7454459

**Comment by Sinickle** [comment]
I believe this is up to 11 seqs now with both Brazil and Canada uploading in the last week. Most recent collection date is April 12.
Notable 494P mutation on Canada, 367L mutation on Brazil.

**Comment by ryhisner** [comment]
One of these was uploaded from Greece yesterday as well, though the collection date was March 17. EPI_ISL_17668400

**Comment by agamedilab** [comment]
26 seq. as of 27.06.23

![grafik](https://github.com/cov-lineages/pango-designation/assets/102166254/b425d80a-20e5-495b-8053-8c83806f3afe)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_19958_a7f970.json

**Comment by DailyCovidCases** [comment]
Please close this issue
