### ISSUE TITLE
XBB.1.16.1 with S:Y453F 3 seqs from USA airport surveillance (California, Atlanta)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1832]
I spotted a couple of american airport surveillance samples with S:Y453F belonging to XBB.1.16.1

We never saw S:Y453F spreading in a fast lineage or pushing a lineage to rapid growth.

But i prefer to propose and monitor it.

Defining mutations:
XBB.1.16.1 >> T29410C, S:Y453F (A22920T)
![Schermata 2023-03-31 alle 16 31 27](https://user-images.githubusercontent.com/87669813/229149425-cadd99c6-7ea2-4d39-a45a-bfb1b1c11d24.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1970c_6ec5c0.json?label=id:node_7703085

![Schermata 2023-03-31 alle 16 32 14](https://user-images.githubusercontent.com/87669813/229149705-312520b2-ebeb-4bdb-99e9-d8ed0974a155.png)

Gisaid query : C11750T, C11956T, A22920T (thx @josetteshoenma)

Sequences: 

USA/GA-GBW-H10-010-4814/2023\|EPI_ISL_17308511\|2023-03-17
USA/CA-GBW-H10-011-2874/2023\|EPI_ISL_17308536\|2023-03-19

**Comment by ryhisner** [comment]
These are both pooled samples, so I kind of doubt if they are really XBB.1.16.1 with Y453F.  I think it's more likely that some XBB.1 with Y453F got mixed in with some XBB.1.16.1. 

Annoyingly, Ginkgo Bioworks often uploads pooled samples to GISAID with no clear indication that they are not normal samples. You have to look pretty far down the GISAID entry to discover that they are pooled samples. 
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/33738461/229163493-69ea9396-ffce-48a0-b7cf-a8a13b466557.png">

**Comment by FedeGueli** [comment]
Thx @ryhisner i didnt get they were the same samples you talked about some days ago

**Comment by FedeGueli** [comment]
Third sequence of this one same day of one of the first two. And this time it is from Hong Kong traveller.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24eb5_b52660.json 

This makes this much more real than initially thought. cc @ryhisner  (Also all the 3 samples have. a silent nuc mutation in common, it would  be weird if unreal

**Comment by FedeGueli** [comment]
Closing this no new sample came from airports or India.

**Comment by FedeGueli** [comment]
Designated FU.4
