### ISSUE TITLE
small saltation of BQ.1.23 sublineage (7seqs, Singapore) with S:R346K, S:K478R and S:F486A

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1833]
Defining mutations: BQ.1.23>A7240G>C6402T (ORF1a: P2046L), C9611T (ORF1a:L3116F), C10279T, A12466G, T23398C, G22599A (S:R346K), A22995G (S:K478R), T23019C (S:F486A), A25864C (ORF3a:I158L), T27935C 
and 3 of 7 further get T19279A (ORF1b:C1938S) 

GISAID query: Spike_R346K, Spike_F486A, Spike_T478R
Earliest seq: 2023-02-13 (Singapore, EPI_ISL_17016242)
Most recent seq: 2023-03-19 (Singapore, EPI_ISL_17347128)
Countries Detected: Singapore (7)

Usher Tree:
![QQ截图20230401024553](https://user-images.githubusercontent.com/121703496/229205314-f42ff62a-1c38-4318-ae7b-bb8b0884803c.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42a6c_7240b0.json
Description:
A small saltation lineage. the S: R346K and S:F486A are normal, while S:K478R is popular recently. 
Maybe the sublineage does not have obvious growth potential, but we can monitor for a time.

Genomes:
EPI_ISL_17016242, EPI_ISL_17016274, EPI_ISL_17029971, EPI_ISL_17146518, EPI_ISL_17262398, EPI_ISL_17262404, EPI_ISL_17347128

**Comment by FedeGueli** [comment]
Good catch! are all local cases?

**Comment by HynnSpylor** [comment]
@FedeGueli Yes. (based on sample information)
 2 seqs maybe the single patient (54 yrs old female), and others are individual.

**Comment by FedeGueli** [comment]
Thanks!

**Comment by thomasppeacock** [comment]
going to suggest monitoring for now but if more sequences appear (particularly outside Singapore) I think this should be prioritised for designation

**Comment by HynnSpylor** [comment]
It is not shown for a month. So close it.
