### ISSUE TITLE
XBB.1.5 with S:D1163G, S:H1101R (19 seq., UK, France, Germany)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1835]
Proposal for a sublineage of XBB.1.5
Earliest sequence: 27.01.2023 (UK)
Countries detected: UK, France, Germany

Defining Mutations:
nuc	unique	A24864G
nuc	homoplasies	A25050G
S	unique	H1101R
S	homoplasies	D1163G

Gisaid query: Spike_D1163G, Spike_H1101R

![grafik](https://user-images.githubusercontent.com/102166254/229354731-0d19cde8-ac8d-4029-af37-60ddb283a8a4.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34db5_97aba0.json?c=country&label=id:node_7816027

![grafik](https://user-images.githubusercontent.com/102166254/229354689-6280b5dd-5204-4d79-ad89-448491a55b70.png)

England/BRBR-326BD2B2/2023
England/QEUH-326C5AFB/2023
England/PHEC-YYERQCK/2023
Germany/BB-RKI-I-1119179/2023
France/ARA-HCL723000371701/2023
hCoV-19/England/BRBR-32712D5F/2023
England/PHEP-YYGJFA1/2023
England/PHEP-YYGOHI1/2023
England/PHEC-YYEQH4M/2023
England/DHSC-CYFUWIJ/2023
Wales/PHWC-PKCTSG/2023
England/PHEP-YYGM1QS/2023
England/PLYM-326ECA67/2023
England/QEUH-326E8218/2023
England/QEUH-326C391E/2023
England/QEUH-326CE6FE/2023

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it has shown very little growth since proposed, and strong apparent growth disadvantages over the past three months, this can be closed for now. Please request re-opening should this lineage show a clear reversal of these trends.
