### ISSUE TITLE
XBB.1.5* with S:K969N [4 or 19 sequences,Germany,Italy and many countries]

### ISSUE THREAD

**Issue by Outpfmance** [cov-lineages/pango-designation#1836]
This is a special branch, which is mainly composed of XBB and its subsidiaries. In this issue, XBB.1.5 and its subsidiaries, this branch removes one of the defining mutations of Omicron, N969K, which changes and locks the Omicron entry pathway, and greatly weakens FCS. At the same time, N969K is also the one with the highest stability and adaptability among 969. Therefore, only a small part of XBB* changes back to 969N. It is impossible to predict whether this trend will spread, but I think this subline is worth paying attention to.

This XBB.1.5* branch includes XBB.1.5, XBB.1.5.21, EL.1 (XBB.1.5.14.1), XBB.1.5.15, XBB.1.5.13, and XBB.1.5.7
Cov-spectrum query: https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-02-01%26to%3D2023-03-23/variants?aaMutations=s%3A969n&nextcladePangoLineage=XBB.1.5*&

Nextstrain: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3ddb_990830.json?f_userOrOld=uploaded%20sample
![B1C1A241-53A5-4D6C-9EC0-A79D4B8E222E](https://user-images.githubusercontent.com/125484893/229364295-62d99261-69ea-43ca-b049-6e4310c1e4b7.jpeg)

Among these sequences, 969 points were basically covered, but the sequences with high overall coverage and high confidence were the second to fifth sequences, mainly those from Germany.
![7703B447-D304-41A4-9EC4-1A7DDD72B1A9](https://user-images.githubusercontent.com/125484893/229364348-b53cd569-b212-4777-b16c-fbdc5d3ebb93.png)
Reference standard: original strain.

![C1168ED3-DA0D-4D72-B5FF-A979D653665F](https://user-images.githubusercontent.com/125484893/229364378-57bafae1-84c3-4209-91a6-6251d5e7c563.png)
Reference standard: BA.2 of Omicron.

![96509B4E-145D-4CA9-A1A9-FAFD2919F75A](https://user-images.githubusercontent.com/125484893/229364434-c6008694-b99a-4be3-ad22-65af0d7ae2cd.png)

Sequences: EPI_ISL_17221698
EPI_ISL_17179358
EPI_ISL_17221692
EPI_ISL_17175089
EPI_ISL_17271754
EPI_ISL_17257478
EPI_ISL_17175092
EPI_ISL_17084911
EPI_ISL_17295617
EPI_ISL_17203669
EPI_ISL_17069251
EPI_ISL_17222277
EPI_ISL_17175079
EPI_ISL_17221703
EPI_ISL_17164627
EPI_ISL_17208323
EPI_ISL_17204151
EPI_ISL_17236284
EPI_ISL_17305985

High confidence sequence: EPI_ISL_17069251 EPI_ISL_17175089 EPI_ISL_17175092 EPI_ISL_17175079

**Comment by FedeGueli** [comment]
@Outpfmance thx for higjlighting but
to my eyes these arent real, Germany has a long history of 969 reverted, plus they seems  too much scattered in the tree,
@corneliusroemer what do u think?

**Comment by oobb45729** [comment]
Both A24469T and A24469C result in S:K969N. However, up till now, A24469C is very rare in Omicron. Thus most cases of A24469T are probably not real.

**Comment by silcn** [comment]
Pretty clearly not real, artefactual reversions are very common in poorer quality sequences, and lots of these sequences have more "reversions" than just K969N as well as other signs of poor quality.

@oobb45729 makes a very good point. There are only two real-looking Omicron sequences with A24469C. One is a chronic BA.1.1 from Spain that also has S:S968A in the adjacent codon, and the other is a BA.5.2 from the Philippines. A->C is only slightly less common than A->T, so this suggests that (a) almost all of the 5000+ instances of A24469T aren't real, (b) S:K969N is very heavily selected against, and (c) if it does appear there is a good chance it is accompanied by another mutation nearby.

**Comment by Outpfmance** [comment]
In conclusion, I think these variants of K969N are still uncertain and need to be further observed in other sequences.

**Comment by silcn** [comment]
> @FedeGueli I don't think failure to detect 969K is the same concept as detection of 969N. Some time ago, I tracked the variation of CH.1.1.4. In the picture of Cov-spectrum below, the share of N969K and Q954H was only 24.29%. But there was no sequence when searching CH.1.1.4+K969N. These sequences may be not covered by 969 points in the laboratory sequencing, but they may still be N969K. However, in these sequences, 969N is clearly detected, which is more reliable. Also, part of the German credible sequence has H954Q.

Indeed they are not the same concept, but some bioinformatics pipelines have issues detecting certain mutations and commonly replace them with the reference. Look at the apparent "prevalence" of the reversion S:S408R in Germany, for instance. The sequences are scattered all over the tree.

If anything, the simultaneous "reversion" of S:Q954H is further indicative of a bioinformatics issue. Usher will often gather together sequences with "reversions" at 954 and 969 that should be placed elsewhere on the tree. I remember this being a big problem in the early days of BA.2.75 when many poor-quality sequences from India with lots of artefactual reversions were getting misplaced.

**Comment by Outpfmance** [comment]
@silcn Is it only three? I think there are four.
EPI_ISL_17069251 EPI_ISL_17175089 EPI_ISL_17175092 EPI_ISL_17175079

**Comment by silcn** [comment]
@Outpfmance none of those have T24424G, they all "have" T24424A. The three Omicrons that genuinely appear to have T24424G are EPI_ISL_13699876, EPI_ISL_14217801 and EPI_ISL_14883463.

**Comment by Outpfmance** [comment]
@silcn Oh, that's my mistake, I got it mixed up, I mean these four sequences look like they really have K969N. 
EPI_ISL_17069251 EPI_ISL_17175089 EPI_ISL_17175092 EPI_ISL_17175079

**Comment by silcn** [comment]
@Outpfmance As previously explained, many sequences superficially look as if they have S:K969N but almost all of them are artefacts. They are scattered all over the tree, don't form lineages, and are often poor quality. If S:K969N was genuinely occurring repeatedly, we would expect to see a mix of A24469T (reversion to WT) and A24469C, but we don't. We see almost all A24469T which is exactly what backfilling with the reference genome looks like. Don't think there's much more to be said about this, it's very clear-cut.

**Comment by Outpfmance** [comment]
Ok, now it should seem clear that these sequences are only A24469T but not A24469C. It's not quite true. I'll close this issue, thanks @silcn
