### ISSUE TITLE
XBB.1 sublineage with S:Y453F and S:K478R (10 sequenecs as of 2023-04-02)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1837]
### Description
**Sublineage of XBB.1** (with ORF8:G8stop but without S:S486P)
**Earliest sequence**: 2023/02/24 (Indonesia)
**Most recent sequence**: 2023/03/17 (Singapore)
**Countries circulating**: Indonesia (4/10), Singapore-local (5/10), Singapore ex-UAE (1/10)

**Mutations on top of XBB.1**: A14319G > A22920T (S:Y453F) > A22995G (S:K478R)

**GISAID and Cov-spectrum query**: A14319G, A22920T, C22995G

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/229364936-bb405297-5172-4fc5-9826-09f343078f23.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_153bb_95fff0.json?c=gt-nuc_22920,22995&label=id:node_7704877

According to Usher it seems it's branched off pretty early, right after ORF8:G8stop. Its potential parent seems to be from Indonesia in October 2022 (EPI_ISL_15826652).

### Genomes:
EPI_ISL_17213332, EPI_ISL_17262193, EPI_ISL_17262222, EPI_ISL_17262333, EPI_ISL_17262336, EPI_ISL_17324397, EPI_ISL_17347087, EPI_ISL_17347092, EPI_ISL_17372701, EPI_ISL_17372771

**Comment by FedeGueli** [comment]
Partially convergent with XBB.2.7.

**Comment by FedeGueli** [comment]
Got designated XBB.1.31 via https://github.com/cov-lineages/pango-designation/commit/9ac4960eef2b87de608db858e26fca0aae7261b3

**Comment by FedeGueli** [comment]
This seems fast worth monitoring closely
(check quick #collection42 by @alurqu)

**Comment by FedeGueli** [comment]
@c19850727 please close this issue. @InfrPopGen could you add please the milestone here??

**Comment by corneliusroemer** [comment]
Yes also saw this, apparently 496S was in Delta, predicted to increase ACE2 binding, maybe similar effect as 486P. Feel free to open new issue @FedeGueli

**Comment by FedeGueli** [comment]
thx @corneliusroemer i am goung to propose it
