### ISSUE TITLE
sublineage of CH.1.1.17 with S:G184V (G22113T), S:V90I (G21830A) (31seqs, mainly in UK)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1838]
Defining mutations: CH.1.1.17>G22113T (S:G184V)>C302T (ORF1a:H13Y)>G21830A (S:V90I)
GISAID query: Spike_F486S, Spike_K444T, Spike_G184V, Spike_V90I
Earliest seq: 2022-12-06 (England, EPI_ISL_16345100)
Most recent seq: 2023-03-25 (England, EPI_ISL_17372981)
Countries Detected: UK (27), Austria (4)

Usher Tree:
![QQ截图20230403025809](https://user-images.githubusercontent.com/121703496/229373717-a04b2ddb-5971-41dc-8bf9-924357035260.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_180c_98d200.json
This sublineage has been shown in #1718 . The tree is messy, as the S:V90I is split into two branches. But notice that the bottom one has only one seq without S:V90I, which may be an artefact as we could integrate them. (Of course it is just my suppose)
![QQ截图20230403031002](https://user-images.githubusercontent.com/121703496/229373798-005c3e9d-1aaa-4427-a3e9-952907fbf16d.png)

S:G184V is concerned recently as in XBB.2.3.2, but the most interesting is 5 of 31 seqs further get S:Q677K. S:Q677 mutation is uncommon in the past, as some B.1.2 seqs had S:Q677H (during Aug2020 to May2021), and BA.2.3.1 lineage had S:Q677E (in Japan during Feb to Jul 2022), while the S:Q677K is more rare, only once appeared in B.1.1 sublineage in Madagascar (during Oct 2020 to Mar 2021). The 5 seqs with S:Q677K are just detected recent days, maybe we should monitor for a time.

Genomes:
EPI_ISL_16345100, EPI_ISL_16345114, EPI_ISL_16345121, EPI_ISL_16345204, EPI_ISL_16356074, EPI_ISL_16375223, EPI_ISL_16440031, EPI_ISL_16440034, EPI_ISL_16440848, EPI_ISL_16440864, EPI_ISL_16440990, EPI_ISL_16441021, EPI_ISL_16442557, EPI_ISL_16442566, EPI_ISL_16442641, EPI_ISL_16496336, EPI_ISL_16515484, EPI_ISL_16584150, EPI_ISL_16676863, EPI_ISL_16803898, EPI_ISL_16952285,
EPI_ISL_17098662, EPI_ISL_17098802, EPI_ISL_17350975, EPI_ISL_17366809, EPI_ISL_17366820-17366821, EPI_ISL_17372944,
EPI_ISL_17372981, EPI_ISL_17372995, EPI_ISL_17373031

**Comment by FedeGueli** [comment]
S:Q677K makes the followingf FCS:
YSQTKTKSHRRARSVASQSI

@thomaspeacock do you think the newly found K-S-K sequence could further improve the furin cleavage?

**Comment by HynnSpylor** [comment]
It has faded away, so close it.
