### ISSUE TITLE
BQ.1* x CJ.1 (or XBF) recombinant (29 seqs as of 2023-04-28, mainly Israel)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1839]
This is a very early recombinant, emerged in Israel back in November 2022, but surprisingly still in circulation, and obtained a few additional spike changes in the process.

### Description
**Recombinant between**: BQ.1* and CJ.1 (or XBF)
**Earliest sequence**: 2022/11/12 (Israel)
**Most recent sequence**: 2023/03/21 (Israel)
**Countries circulating**: mainly in Israel (18/23), also used to be found in France (3/23), Germany (1/23) and Belgium (1/23) in its early circulation
**Potential breakpoint**: between NSP15 and Spike NTD (20137-21764)

**Mutation profile** (private mutations are in yellow color):
![image](https://user-images.githubusercontent.com/86835836/229390223-36e5a6f2-5f62-4192-ad72-e5e1354572b1.png)
**Private mutations**: T4915C, G20134A (ORF1b:V2223I)
It also obtained additional changes such as S:F186L and S:T883I more recently

**GISAID and Cov-spectrum query**: T4915C, C26681T, G20134A

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/229390426-9b21bb78-6602-4702-b006-735883f8be3e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24fd4_963ec0.json?c=gt-nuc_4915&label=id:node_7631381

### Genomes:
EPI_ISL_15920464, EPI_ISL_16020400, EPI_ISL_16278479, EPI_ISL_16283511, EPI_ISL_16395816, EPI_ISL_16679824, EPI_ISL_16679968, EPI_ISL_16703222, EPI_ISL_16738460, EPI_ISL_16738608, EPI_ISL_16739138, EPI_ISL_16739683, EPI_ISL_16940158, EPI_ISL_16958333, EPI_ISL_16996254, EPI_ISL_17189814, EPI_ISL_17208592-17208593, EPI_ISL_17208599, EPI_ISL_17241413, EPI_ISL_17241510, EPI_ISL_17272848, EPI_ISL_17344755

**Comment by FedeGueli** [comment]
still 29 as today maybe better closing this one.

**Comment by corneliusroemer** [comment]
Dead: https://cov-spectrum.org/explore/World/AllSamples/Y2023/variants?nucMutations=T4915C%2CC26681T%2CG20134A&
