### ISSUE TITLE
Potential new sublineages of C.37 with spike Q675H and  other with spike I714V

### ISSUE THREAD

**Issue by OrsonMM** [cov-lineages/pango-designation#184]
New proposed lineage
By Group of Genomic Survillance INS

**New lineage proposal by  Q675H mutation**
**Description:**

Sub-lineage of: Potencially new sub-lineage of C.37 (Q675H mutation)

Is different clade to previos reported https://github.com/cov-lineages/pango-designation/issues/158 (C.37.1), but the evidence of repeated emergence of mutation Q675H.

Earliest sequence: (2021-02-01)
Most recent sequence: (2021-07-04)
Countries circulating: Perú (57), Chile (49), USA (33), Spain (2) and Mexico (2)
This potentially C.37.X new sub-lineage was detected > 195 genomes and has mutations:
ORF9b: P51L
Spike:Q675H 
Genomes

[clade_675.txt](https://github.com/cov-lineages/pango-designation/files/6988393/clade_675.txt)

Evidence

![image](https://user-images.githubusercontent.com/12600107/129483450-9ed8ca33-7510-4db8-b0ac-3b4883be95b6.png)

Proposed lineage name

C.37.X

**New lineage proposal by  I714V mutation**
**Description:**

Sub-lineage of: Potencially new sub-lineage of C.37 (I714V mutation)
Earliest sequence: (2021-01-17).
Most recent sequence: (2021-07-19).
Countries circulating: Perú (90), USA (62), Chile (23), Germany (8), Ecuador (5), Mexico (2), CostaRica (2), Uruguay (1), France (1), Argentina (1).

This potentially C.37 new sub-lineage was detected in > 190 genomes and has mutations:
ORF8:A51S
S: I714V
Genomes

[clade_714.txt](https://github.com/cov-lineages/pango-designation/files/6988390/clade_714.txt)

Evidence

![image](https://user-images.githubusercontent.com/12600107/129483397-93a46449-7dce-478f-847b-f282c0947736.png)

Proposed lineage name

C.37.X

**Comment by Thor-cpu** [comment]
**Nextstrain link of plots, thanks dear Orson.**

**Comment by OrsonMM** [comment]
Hi Thor 

you can donwload .json file of https://github.com/INS-LBBM/PANGO-USheR/tree/main/auspice ,it was generated using USheR

**Comment by chrisruis** [comment]
Thanks @OrsonMM.

It's not clear that either of these clades is epidemiologically distinct from the rest of C.37. There isn't a clear change in geographical circulation and the mutations are not sufficient alone to warrant a new designation. C.37.1 was designated due a clear change in geographical location (out of South America) rather than due to the Q675H mutation alone.

We'd therefore recommend referring to these sequences as C.37
