### ISSUE TITLE
XBB.2 Saltation/BQ.1.1.7 Recombinant with S:S486P, S:S1242N, ORF7a: E33K, ORF8:D63N, + 6 ORF1a subs (5 seq, Apr 5)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1843]
**Description**
**Sub-lineage of:** XBB.2
**Earliest sequence:** 2023-3-13, England — EPI_ISL_17299052
**Most recent sequence:** 2023-3-19, England — EPI_ISL_17382349
**Countries circulating:** England (4)
**Number of Sequences:** 4
**GISAID AA Query:** Spike_F486P, NSP1_S166G, NSP8_P178H
**GISAID Nucleotide Query:** A761G, C12624A, T23018C
**CovSpectrum Query:** [8-of: A761G, C912A, G1820A, C1931A, C2455T, T2954C, C5284T, C12624A, C17119T, C18129T, T23018C, T23680C, C24023T, G25287A, G27490A, G28080A, C28435T]
**Substitutions on top of XBB.2:**
**Spike:** S486P, S1242N
**ORF7a:** E33K
**ORF8:** D63N
**ORF1a:** R47K (Reversion), S166G, S216Y, G519S, Q556K, P4120H 
**NSP Form:** NSP1_R47K (Reversion), NSP1_S166G, NSP2_S36Y, NSP2_Q376K, NSP8_P178H
**Nucleotide:** G405A (Reversion), A761G, C912A, G1820A, C1931A, C2455T, T2954C, C5284T, C12624A, C17119T, C18129T, T23018C, T23680C, C24023T, G25287A, G27490A, G28080A, C28435T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/MOV_XBB.2_Saltation_BQ.1.1.7_Recomb_subtreeAuspice1_genome_201bb_ac7b50.json  
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/33738461/229607689-b531be75-17f4-4e2b-9fc4-e33e42690fdf.png">

**Evidence**
I'm pretty certain the beginning of ORF1a in this lineage was taken from BQ.1.1.7, given that it has ORF1a:S216Y and ORF1a:Q556K. Just 2.29% BQ.1.1.7* sequences in the past six months have had ORF1a:S166G, a total of 97 sequences worldwide, but 78 of those 97 have been from the UK. This would also explain the ORF1a:R47K reversion and the synonymous mutations C2455T and T2954C. C2455T is only found in 2.34% of all BQ.1.1.7* in the past 6 months, but it’s been in 100% of BQ.1.1.7* with ORF1a:S166G.

Setting aside the mutations acquired via recombination, there are 11 private nucleotide mutations here, including T23018C, which creates S:S486P. I think this sublineage most likely originated in a chronic XBB.2 infection in a person that was later coinfected with BQ.1.1.7, from which it subsequently snagged about 10% of the genome on the 5’ end. It’s possible that this sequence was reversed, with BQ.1.1.7* infection occurring first, but I think this is unlikely given the greater prominence of XBB.2* in the UK well before the first arrival of BQ.1.1.7* with ORF1a:S166G.
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/33738461/229607848-de86b467-d5a6-4835-b28b-eaf1e2becdc5.png">

**Other notes:**
• ORF1a:P4120H (NSP8_P178H) is a pretty rare mutation, found in just 54 sequences worldwide over the past 6 months. 

• All of these sequences lack coverage from at least S:235-285 so it’s possible there could be mutations hiding in that region. 

• Of the 11 private non-recombinant mutations, 10/11 (90.9%) are transitions, with 3/11 (27.3%) G->A and 5/11 (45.5%) C->T. This suggests molnupiravir could have played a role in the creation of this sublineage, though the mutation numbers are too small to come to any confident conclusions on that front.  

**Genomes**
One sequence on the Usher tree has not yet been uploaded to GISAID and is therefore not included below.
<details>
<summary>Genomes</summary>
EPI_ISL_17299052, EPI_ISL_17299061, EPI_ISL_17382349
</details>

**Comment by ryhisner** [comment]
One of these showed up in South Australia today, collection date March 22. 
EPI_ISL_17398296

**Comment by FedeGueli** [comment]
Re -found it just now! : https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_296e8_8e52a0.json?c=gt-nuc_405,1931,2954,9866&label=id:node_6088439


I made a bit analysis and i concur it is BQ.1.1.7 the donor. Adding here : 

![Schermata 2023-04-26 alle 11 34 55](https://user-images.githubusercontent.com/87669813/234535143-5d1fd6f0-e869-4b03-902b-0bb8105b2ba1.png)
vs
![Schermata 2023-04-26 alle 11 35 23](https://user-images.githubusercontent.com/87669813/234535261-4f5ea77a-3978-4b4d-9a0f-eac74dc56297.png)


https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_296e8_8e52a0.json?c=gt-nuc_405,1931,2954,9866&label=id:node_6088439

**Comment by InfrPopGen** [comment]
Thank you for proposing this recombinant. As there hasn't been detected new growth for over a month, this can be closed for now. Please request re-opening should this start growing again and get into double figures. For tracking, this might also be a candidate for https://github.com/sars-cov-2-variants/lineage-proposals/issues
