### ISSUE TITLE
BA.1.17 potential mini saltation c. 18 uniqe aa mutations c. 12 aa homoplasies (2 seq., Netherlands)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1844]
Proposal for a sublineage of BA.1.17
Earliest sequence: 13.03.2023 (Netherlands)
Countries detected: Netherlands

This sublineage of BA.1.17 is defined by c. 18 uniqe aa mutations c. 12 aa homoplasies (see below) and is probably worth monitoring. The sequences originate from random surveillance (Hospital) and were uploaded on two different dates (03.18 and 04.03.23) from the same submitting lab.

Defining Mutations:
nuc	unique	C1420A, A4233C, T6934C, C8240T, G9203A, T12520A, G12614A, T12955C, C16329T, G16843T, C18693T, C20320T, A21611G, T21652A, T21995G, C22000T, C22664A, G22820A, A22881G, A22898G, C22916A, T23965C, A24538C, G26959A, A28338T
nuc	homoplasies	C5178T, C12756A, G18163T, T22579C, G22599A, G23040A, C23423T, G23587C, G24368T, G24434T, C25517T, C25904T, C29358A
nuc	reversionsToRoot	A22898G, G23040A
ORF1ab	unique	D1323A, H2659Y, D2980N, D4085E, D4117N, G5527C, H6686Y
ORF1ab	homoplasies	T1638I, T4164N, V5967L
S	unique	N17D, N30K, Y145D, L368I, D420N, K440R, S446G, L452M, Q992H
S	homoplasies	R346K, R493Q, P621S, Q675H, D936Y, A958S
S	reversionsToRoot	S446G, R493Q
ORF3a	homoplasies	P42L, S171L
M	unique	R146H
N	unique	D22V
N	homoplasies	T362K

vs Wuhan-Hu:
![grafik](https://user-images.githubusercontent.com/102166254/229716006-a4ef4482-4014-4f75-ac4f-e7b673ed097d.png)

![grafik](https://user-images.githubusercontent.com/102166254/229743892-91224058-5841-4ea6-9233-289e7c356ee9.png)

vs BA.2:
![grafik](https://user-images.githubusercontent.com/102166254/229717750-23989640-2a4b-426f-b98c-acf3444f892e.png)

![grafik](https://user-images.githubusercontent.com/102166254/229744163-84f88c15-375b-4063-b148-89643e416ee3.png)

![grafik](https://user-images.githubusercontent.com/102166254/229718078-8f8930ed-d0af-4150-89a0-127743ba44e7.png)
![grafik](https://user-images.githubusercontent.com/102166254/229717846-85f7d9f4-52c3-47df-970c-f98823862ddf.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35be4_bccef0.json?c=userOrOld

EPI_ISL_17241376, EPI_ISL_17389140

**Comment by ryhisner** [comment]
I've contacted the submitter about these, and both sequences are from one chronically infected patient.

**Comment by thomasppeacock** [comment]
thanks for doing that @ryhisner! 

In that case I'm going to close this for now as we dont assign lineages to chronic infections unless there is good evidence for onward transmission (ie issue #663). Feel free to flag again or reopen if theres any evidence of onwards transmission.

**Comment by FedeGueli** [comment]
yes  @NkRMnZr one patient we are in touch with local health authorities . thank you for tracking.

**Comment by AngieHinrichs** [comment]
This one is still going -- recent sample Netherlands/NH-AUMC-001316/2023|EPI_ISL_18054466|2023-07-24 has five additional Spike mutations beyond Netherlands/NH-AUMC-001169/2023|EPI_ISL_17481180|2023-04-06 (S:R408T, S:M452K, S:Y453F, S:M740T, S:T791A).

@ryhisner and @FedeGueli thanks for confirming it's from one patient.  In GISAID, all of the samples in this branch have "Sampling strategy:	Random surveillance hospital" (except EPI_ISL_14115208 from 2022-03-31 says "Study participant").  If all of the samples are from one patient, it's not random surveillance.  🙂  Can you ask your contacts to update the sampling strategy for the single-patient samples?  Thanks!

The samples on the branch (starting from the node where EPI_ISL_13884353|2022-07-03 splits off from the others):
```
Netherlands/NH-AUMC-024640/2022|EPI_ISL_13884353|2022-07-03
Netherlands/NH-AUMC-001286/2023|EPI_ISL_17815222|2023-06-08
Netherlands/NH-AUMC-001188/2023|EPI_ISL_17535664|2023-04-13
Netherlands/NH-AUMC-001217/2023|EPI_ISL_17621930|2023-04-26
Netherlands/NH-AUMC-001080/2023|EPI_ISL_17389140|2023-03-23
Netherlands/NH-AUMC-000972/2023|EPI_ISL_17241376|2023-03-13
Netherlands/NH-AUMC-001284/2023|EPI_ISL_17783358|2023-06-05
Netherlands/NH-AUMC-001245/2023|EPI_ISL_17654831|2023-05-08
Netherlands/NH-AUMC-001267/2023|EPI_ISL_17719162|2023-05-21
Netherlands/NH-AUMC-001300/2023|EPI_ISL_17838506|2023-06-19
Netherlands/NH-AUMC-001307/2023|EPI_ISL_17971223|2023-06-28
Netherlands/NH-AUMC-001169/2023|EPI_ISL_17481180|2023-04-06
Netherlands/NH-AUMC-001316/2023|EPI_ISL_18054466|2023-07-24
```
