### ISSUE TITLE
XBB.2.3 with S:478N emerging in India(25 seqs, 5 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1846]
Sub-lineage of: XBB.2.3
Mutations on top of XBB.2.3: A22996T(S:K478N),G29706T,C18570T
GISAID query:C18570T,A22996T
No. of seqs: 14 (5 USA(2 from India, 2 airport), 3 Singapore(2 from UAE, 1 from India), 6 India)
First seq: EPI_ISL_17073066(India) 2023-2-24
Latest seq: EPI_ISL_17388552(Singapore) 2023-3-24
Sequences:
EPI_ISL_17073066, EPI_ISL_17247073, EPI_ISL_17247111,
EPI_ISL_17247121-17247122, EPI_ISL_17346800, EPI_ISL_17346835,
EPI_ISL_17349530, EPI_ISL_17349558, EPI_ISL_17349563,
EPI_ISL_17349584, EPI_ISL_17384826, EPI_ISL_17388552,
EPI_ISL_17391395

It seems that various 2-nuc mutations on position S:478 are emerging in XBB.2.3. S:478Q from XBB.2.3.4, and this one is S:478N. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_2579e_cf7230.json)

<img width="1398" alt="Screen Shot 2023-04-05 at 13 11 10" src="https://user-images.githubusercontent.com/10445944/229989570-76f7a54d-7db2-4769-800a-4adf0ec048ad.png">

**Comment by FedeGueli** [comment]
There are 15 of this on Usher. https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_412ff_322d90.json?c=userOrOld&label=id:node_6021623

(i think the one more is from Texas (GenBank)

**Comment by FedeGueli** [comment]
Wow it seems very fast. @thomasppeacock @AngieHinrichs @corneliusroemer @InfrPopGen i think this should be designated as soon possible.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage XBB.2.3.5 with 5 newly designated sequences, and 0 updated. Defining mutation A22996T (S:K478N) (following C18570T).

**Comment by FedeGueli** [comment]
![Schermata 2023-04-12 alle 12 38 15](https://user-images.githubusercontent.com/87669813/231433390-33b5eeee-6948-4334-9bbc-4f441000a987.png)
Thx @InfrPopGen for the fast designation as shown above if i set it as baseline in Asia past 2 months it leaves very little room to compete. Obviosly too few to convlude anything and also Singapore has targeting sampling. so we will have to wait.
@thomaspeacock @AngieHinrichs @corneliusroemer 

great fast catch @aviczhl2 .

https://cov-spectrum.org/collections/42?region=Asia

**Comment by FedeGueli** [comment]
There was a sequence (EPI_ISL_17422163|2023-03-27) with S:K478N (and orf1a.A1670V) from France not belonging to XBB.2.3.5 apparently:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21653_c36090.json?c=userOrOld&label=id:node_9971520

**Comment by aviczhl2** [comment]
> There was a XBB.2.3 sequence (EPI_ISL_17422163|2023-03-27) with S:K478N (and orf1a.A1670V) from France not belonging to XBB.2.3.5 apparently: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21653_c36090.json?c=userOrOld&label=id:node_9971520

Yeah it doesn't have C18570T which is together with this proposal.
