### ISSUE TITLE
XBB.1.5 with S:P621S (Roeselare, Belgium)

### ISSUE THREAD

**Issue by geertmartens** [cov-lineages/pango-designation#1849]
In our last 3 runs, since early March 2023, we detected at least 24 sequences of XBB.1.5 with S:P621S (C23423T)

Here are some GISAID accession numbers: 

EPI_ISL_17280380
EPI_ISL_17280388
EPI_ISL_17280393
EPI_ISL_17280400
EPI_ISL_17280407
EPI_ISL_17280409
EPI_ISL_17280412
EPI_ISL_17280413
EPI_ISL_17280415
EPI_ISL_17280416
EPI_ISL_17280436
EPI_ISL_17280437
EPI_ISL_17280439

11 additional sequences were uploaded to GISAID today

**Comment by InfrPopGen** [comment]
Hi @geertmartens , thank you for highlighting this. Is this intended to be a new lineage proposal or simply an alert? There are over 1000 XBB.1.5 with S:P621S, and most have been detected in the USA and Canada, but they're fairly cosmopolitan. If there's a particular Belgium sub-clade being referred to here, please add further defining mutations. Thank you.

**Comment by oobb45729** [comment]
Let me complete this.
Substitutions on top of XBB.1.5: C10615T then ORF1b:S2312L(C20402T) then T19284C+S:P621S(C23423T)+C25324T
![1](https://user-images.githubusercontent.com/115189228/235500667-28edb10f-41d1-49c1-bd56-726c9657740e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1767c_ff95e0.json?c=gt-S_621&label=id:node_5990205
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=S%3AP621S%26T19284C&

**Comment by oobb45729** [comment]
I came across this after noticing 2309-2314 of ORF1b is a hotspot for wastewater-crypto-like sequences (I use the query ORF1a:V38A&N:S37P).
![1](https://user-images.githubusercontent.com/115189228/235503292-e845fa17-b25d-483c-948e-8ac595f792f2.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=ORF1a%3AV38A%26N%3AS37P&
https://jbloomlab.github.io/SARS2-mut-fitness/gisaid_2023-03-29/nsp15.html also show that this part of nsp15 (258-263) is a hotspot.
![2](https://user-images.githubusercontent.com/115189228/235504715-e06b77ad-36a6-4369-917f-47f2bfb53e44.png)
By the way, ORF1b:P2313L is in BQ.1.1.5*(DN*).

**Comment by FedeGueli** [comment]
Designated XBB.1.5.90 https://github.com/cov-lineages/pango-designation/commit/6a905e35a40b1d7d2a76706956cdd87df83eefd0
