### ISSUE TITLE
XBB.1.9.1 with orf1b:T42N and S:G614A in Pakistan, UK and China( 7 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1852]
sub-lineage of: XBB.1.9.1
mutations on top of XBB.1.9.1:C13592A(orf1b:T42N), G23403C(S:G614A)
GISAID query: A23403C,C13592A
No. of seqs: 6 (3 Pakistan, 2 UK, 1 China)
First seq:EPI_ISL_17364563 2023-3-10(UK)
Latest seq: C_AA003317 2023-3-27 (China)
Sequences:
EPI_ISL_17295670, EPI_ISL_17364563, EPI_ISL_17389606,
EPI_ISL_17389614, EPI_ISL_17409500
C_AA003317 (from [Genbase](https://ngdc.cncb.ac.cn/ncov/genome/search) )

[usher1](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_2ba38_f25950.json)
[usher2](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_224c0_f2e380.json)

<img width="1365" alt="Screen Shot 2023-04-07 at 04 45 47" src="https://user-images.githubusercontent.com/10445944/230490532-dd0c1ed9-bd2d-488c-88b9-1487f741e2f3.png">

<img width="1402" alt="Screen Shot 2023-04-07 at 04 45 34" src="https://user-images.githubusercontent.com/10445944/230490577-8b4ca4a7-7f08-408c-8e24-1fa3337fafe0.png">

**Comment by FedeGueli** [comment]
Great catch. btw it is Orf1b:T42N

**Comment by aviczhl2** [comment]
> Great catch. btw it is Orf1b:T42N

Sorry and corrected. Thanks.

**Comment by aviczhl2** [comment]
1 more in UK.

**Comment by aviczhl2** [comment]
No further seqs of this one, close down.
