### ISSUE TITLE
XAY.1.1.3 sublineage with S:N148D (Germany, China, 19 seq)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1856]
EPI_ISL_17254008
EPI_ISL_17070686
EPI_ISL_17253997
EPI_ISL_17256149
EPI_ISL_17070133
EPI_ISL_17176831
EPI_ISL_17263381
EPI_ISL_17070499
EPI_ISL_17296385
EPI_ISL_17005047
EPI_ISL_17254451
EPI_ISL_17004469
C_AA003638
Substitutions on top of XAY.1.1: C14599T then C6040T+C8290T+T15153C then S:N148D(A22004G)
![1](https://user-images.githubusercontent.com/115189228/230546294-5fffece2-3515-4745-ab3c-1ce26e235fff.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2eac7_fa7a20.json?c=gt-S_148&label=id:node_8955130
![2](https://user-images.githubusercontent.com/115189228/230546542-10c114e4-e6ce-46db-9e7f-70d9bd2d75af.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXAY.1.1*%26S%3A148D&

**Comment by ryhisner** [comment]
S:N148 may be a site of increasing importance. S:N148T has been increasing as a share of XBB.1.5 in the past month, particularly in the United States. 
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/33738461/230721617-24a0984f-0265-4526-8844-f490097024eb.png">

**Comment by aviczhl2** [comment]
> S:N148 may be a site of increasing importance. S:N148T has been increasing as a share of XBB.1.5 in the past month, particularly in the United States. <img alt="image" width="1453" src="https://user-images.githubusercontent.com/33738461/230721617-24a0984f-0265-4526-8844-f490097024eb.png">

Are you sure those S:N148T are real? GISAID categorizes #1882 as having S:N148T too.

**Comment by ryhisner** [comment]
A few could be artifacts, but I don't think CovSpectrum registers the #1882 sequences as having S:N148T. I just took a look at half a dozen of the CovSpectrum S:N148T sequences on GISAID, and they all look real. Here's the biggest branch, which seems to have >200 seq. 
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/33738461/232347151-961b8c97-44b3-4c73-8c69-2faf94e71362.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e01b_c79b00.json?label=id:node_3192032

**Comment by oobb45729** [comment]
Another one from China: C_AA009662.

**Comment by oobb45729** [comment]
Two more in China: C_AA010883, C_AA010907.

**Comment by corneliusroemer** [comment]
I designated the parent branch as XAY.1.1.3

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there have been very few new detections since proposal, and there is no clear signs of a relative growth advantage, this can be closed for now. Please request re-opening should the situation change markedly. Of course, this proposal could be transferred to https://github.com/sars-cov-2-variants/lineage-proposals/issues for ongoing tracking.
