### ISSUE TITLE
XBB.1.17.1 with orf9b:I5V and orf3a:T14N(31 seqs, 11 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1857]
sub-lineage of: XBB.1.17.1 
Mutations on top of XBB.1.17.1: G20173A(orf1b:V2236I), A1087G,C25433A(orf3a:T14N),T1711C,A28296G(orf9b:I5V, N:N8S)
No. of seqs: 7( Ukraine 2 Austria 1 Belgium 1 Denmark 1 Germany 1 China 1)
GISAID query: A28296G,C25433A

Sequences:
EPI_ISL_17076137, EPI_ISL_17076145, EPI_ISL_17273147,
EPI_ISL_17327569, EPI_ISL_17390098, EPI_ISL_17406270,
C_AA003630

First Seq: EPI_ISL_17076145(Ukraine) 2023-1-6
Latest Seq: EPI_ISL_17406270(Germany) 2023-3-27

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice17_genome_126fd_fd0ad0.json)

<img width="1328" alt="Screen Shot 2023-04-07 at 16 35 54" src="https://user-images.githubusercontent.com/10445944/230574371-8c7b5f81-e27b-4bb9-8d58-f791fa1262d3.png">

**Comment by aviczhl2** [comment]
1 more in France.

**Comment by ryhisner** [comment]
Eight sequences in seven countries! Vagabond viral variant, this one.

**Comment by aviczhl2** [comment]
1 more in Austria.

**Comment by aviczhl2** [comment]
another 1 in Austria

**Comment by aviczhl2** [comment]
15 seqs, relatively massive upload from Ukraine.

**Comment by FedeGueli** [comment]
Thx @aviczhl2 see those samples this morning i forgot it was already proposed. It is quite political interesting that a lineage that is widespread in western african countries is now popping up in Ukraine. Maybe due to neofascist Wagner para-militia that is based in thast part of Africa.

**Comment by aviczhl2** [comment]
17 seqs and spread to Sweden.

**Comment by aviczhl2** [comment]
20 and in USA.

**Comment by aviczhl2** [comment]
29, UK

**Comment by aviczhl2** [comment]
No new seqs in 3 weeks.
