### ISSUE TITLE
Sublineage of XBB.1.22.1 with ORF1b:S997P(T16456C) and S:I197T (T22152C) (48 seqs in 12 countries)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1859]
Defining mutations: XBB.1.22.1>T16456C (ORF1b:S997P), T22152C (S:I197T)
GISAID query: Spike_Y200C, Spike_I197T, T16456C, T28297C
Earliest seq: 2023-03-16 (Australia, EPI_ISL_17408836)
Most recent seq: 2023-03-30 (Malaysia, EPI_ISL_17417562)
Countries Detected: Australia (3), Malaysia (2), Denmark (2), Indonesia (1)

Usher Tree:
![QQ截图20230407234336](https://user-images.githubusercontent.com/121703496/230637506-0ee3d879-1cfd-4f88-ab22-06ec96afdf1d.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_227c3_33df0.json

Description:
A very new XBB.1.22.1(XBB.1 with S:F486P and S:Y200C on T28297C branch) sublineage, as all the 8 seqs are updated in recent days.
Since the site 197 and 200 are adjacent, the interaction of two mutations may have certain impact.

Genomes:
EPI_ISL_17359041, EPI_ISL_17389653, EPI_ISL_17389982, EPI_ISL_17390126, EPI_ISL_17408836, EPI_ISL_17409007, 
EPI_ISL_17417562-17417563

**Comment by HynnSpylor** [comment]
12 seqs in 6 countries now (add England, France)

**Comment by HynnSpylor** [comment]
18seqs in 7 countries now (Australia 6, Denmark 3, Malaysia 3, France 2, USA 2, England 1, Indonesia 1)

**Comment by HynnSpylor** [comment]
30 seqs in 11 countries (Singapore 7, Australia 6, Denmark 3, Malaysia 3, France 2, USA 2, Sweden 2, Austria 2, Indonesia 2, Sweden1, Japan 1)

**Comment by HynnSpylor** [comment]
48 seqs now. the seqs are risen in USA.

**Comment by FedeGueli** [comment]
53 sequences now, new uploads from Singapore (1 local, 1 Malaysia, 2 Philippines) and Thailand ( from a traveller, unknown country)

An easier Gisaid/Covspectrum query is : T22152C,T16456C, T28297C, A22161G

The way it is accumulating sequences is very fast
![Schermata 2023-05-03 alle 09 49 30](https://user-images.githubusercontent.com/87669813/235859251-9f2e857d-6bb8-489c-9125-6d53ba729855.png)

@corneliusroemer @thomasppeacock @InfrPopGen i suggest a fst deisgnation of this one for the following reason:
1) rapid geographical spread
2) travellers from different countries and especially Philippines : we had until yesterday just 14 samples Philippines related collected after 1/04 so these two new samples from Singapore may suggest a wider circualtion there.
3) Rapid accumulation of sequences in line with fastest circulating strains.

**Comment by FedeGueli** [comment]
More: 19 out of 53 samples have a FCS mutation S:A684V that makes it YSQTQTKSHRRVRSVA
