### ISSUE TITLE
Issues with AY.12 classification with Pangolin

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#186]
Recently the variant AY.12 was designated.  The sequences from that variant were almost solely from Israel. 
Two main NS mutations that characterize this Variant are Orf3a_P42S and S_T791I. 
On GISAID, 924 sequences has those 2 mutations. But 32,830 sequences are classified as AY.12. 
I took random sample of sequences out of those 32,830 and uploaded on Usher  :

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_15e6a_a3e710.json?label=nuc%20mutations:G15451A,C16466T,C22995A,G24410A,T26767C,C27752T,A28461G

![image](https://user-images.githubusercontent.com/80166370/129572154-694e1f38-3eb1-4717-8deb-2990b24b5bef.png)

 As can be seen, Those samples has no monophyletic source .

**Comment by matt-sd-watson** [comment]
I can also attest that the pango-designation version tested(1.2.59) with Pangolin v.3.1.11 seems to have an error in classifying delta variants with very high false positive rates for AY.12. 
Approximately 60-66% of our B.1.617.2 sequences were re-classified as AY.12, which is an extraordinary number of re-assignments given that the cluster is predominantly Israeli. Examination of the sequences showed that almost none of the re-classified sequences has either of the defining AY.12 mutations Orf3a_P42S and S_T791I.

This also holds true for a random subset of Israel sequences that I pulled from Gisaid. Only about 1/3 of the israel Gisaid sequences re-assigned as AY.12 since May 2021 have either of those two mutations.

**Comment by rambaut** [comment]
We are seeing a general problem with the PangoLEARN classifier that if members of a sublineage such as AY.12 remain in the training set as the parent lineage (B.1.617.2) then this can cause false positives for the sublineage. This currently has to be checked manually but some work is being done to add this as an automated QC step for designation. A work around for now may be to use the USHER classifier module in Pangolin to double check these calls.

**Comment by rmcolq** [comment]
Has this been resolved by the latest release, with the updated set of designated sequences?

**Comment by shay671** [comment]
Not really 
I run today random samples of AY.12 based on GISAID and still the samples are scattered. 

![image](https://user-images.githubusercontent.com/80166370/132133010-494ad0f4-7585-42eb-9ef2-3612232e5928.png)

**Comment by matt-sd-watson** [comment]
Initial review of our sequences indicates that there are still very high rates of false positives among AY.12s. Assessing calls made between both pangoLEARN and Usher from the current pangolin module reveals discordant results for almost all instances of this lineage as reported by the current pangoLEARN.

**Comment by rmcolq** [comment]
Thanks! We have found at least one problem with the AY.12 designated sequences - it appears a country was giving different samples the same `sample_name` and this is very likely to be causing the false positives. We will address this in the next release and keep debugging in the mean time.

**Comment by matt-sd-watson** [comment]
It appears from a very basic comparison that the assignment discrepancies for AY.12 have been resolved with the latest pangoLEARN release. Will double check this with our all of our internal sequences. 

Not sure if the latest plearn release has addressed the false positives with all AY lineages. We also saw discrepancies with other lineages such as AY.4, but all were to a lesser degree than AY.12.

**Comment by corneliusroemer** [comment]
@shay671 Have you checked whether the latest release has already propagated to GISAID? It could take another day or two.

**Comment by matt-sd-watson** [comment]
@corneliusroemer Thank you for mentioning this. I just checked and a number of AY.12 genomes that we uploaded over the past couple of months or so are still characterised using an old pangoLEARN version (2021-08-24). It is likely that genomes uploaded today and yesterday will be assigned using the new model, but it will take time to get all of the existing Gisaid sequences on the updated pangoLEARN.

**Comment by shay671** [comment]
Hi @matt-sd-watson  
from the samples uploaded Since Sunday (19/09) on GISAID,  82 were characterized as AY.12, 80 has Spike_D614G and only 4 has the Spike_T791I mutation. 
I tried using https://pangolin.cog-uk.io/ website to check the samples but currently it seems to be stuck ( even with 1 sample uploaded it runs for more than 15 min), ill try later and see if it runs.

**Comment by rmcolq** [comment]
The date is the date model training started rather than the release date (which was yesterday evening). I know the website was starting being updated last night, and GISAID sometimes takes more than a week to reassign lineages to existing samples. It is possible that the new model might not have fixed the issues with AY.12, but it is too early to be able to check yet on either of those platforms.

**Comment by AngieHinrichs** [comment]
FWIW in the 2021-09-20 UCSC/UShER tree with GISAID and public sequences, the branch annotated as AY.12 has 2724 sequences ([AY.12.2021-09-20.sequences.txt.gz](https://github.com/cov-lineages/pango-designation/files/7204566/AY.12.2021-09-20.sequences.txt.gz)) and has this path of mutations:
```
C14408T > C241T > C3037T > A23403G > G29742T > T22917G > T27638C > G28881T > G210T > C21618G > G29402T > C23604G > C25469T > G24410A > C22995A > A28461G > C27752T > C16466T > T26767C > G15451A > C10029T > C19220T > G28916T > G4181T > C27874T > C6402T > C7124T > G9053T > C8986T > T6402C > A11332G > A11201G > C6402T > G1048T > G20937T
```
That is actually missing some important mutations at the end, so the UShER web interface is also calling AY.12 too broadly.  Here is a Nextstrain view in which yellow is an AY.12 representative sequence from pango-designation/lineages.csv, blue is the branch that UShER is calling AY.12, and green is closely related B.1.617.2:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-186.2021-09-20.json?c=pango_lineage_usher

So lineage assignment has gone a little awry in our daily updates; I will look into how we can do a better job there.

There are some AY.12 representatives that do not have ORF3a:P42S (C25516T):
Israel/SMC-7003746/2021
Israel/SMC-7004863/2021
Israel/SMC-7006411/2021
Israel/SMC-7003749/2021
Israel/SMC-7003732/2021
Israel/SMC-7003748/2021
Israel/SMC-7003733/2021
Israel/SMC-7003734/2021
Israel/SMC-7005828/2021
Israel/SMC-7003747/2021
Israel/SMC-7003730/2021
Israel/SMC-7003884/2021
Israel/SMC-7004509/2021
Israel/SMC-7003745/2021
Israel/SMC-7003746/2021
Israel/SMC-7003717/2021
Israel/SMC-7003956/2021
Israel/SMC-7004211/2021
Israel/SMC-7006280/2021

@shay671 is ORF3a:P42S important enough that those samples should be removed?

The branch with S:T791I but without ORF3a:P42S has 1297 sequences:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-186.2021-09-20.json?c=pango_lineage_usher&label=nuc%20mutations:C23934T
The branch with ORF3a:P42S has 1242 sequences.

The lineageTree.pb file in the latest pangoLEARN release also has the path to AY.12 ending too soon at G20937T, so `pangolin --usher` is also calling AY.12 too broadly (but probably not nearly as broadly as pangoLEARN).

**Comment by matt-sd-watson** [comment]
@AngieHinrichs thanks for the update. This is also consistent with my observations for our sequences. Whereas prior to this update pangoLEARN was calling AY.12s too broadly as compared to usher, which was more conservative, after the update it is now Usher that is calling broadly and generating more false positives. Approximately 83% of our AY.12s called with usher do not have the defining mutations.

**Comment by chrisruis** [comment]
It looks like this is much improved in recent pangoLEARN models. AY.12 has now been updated to AY.122.1 based on #344
