### ISSUE TITLE
BQ.1.2 Sublineage with S:K147E, S:∆186-187, S:N188Y, S:R346T, S:V445A, ORF8:C90* (10 seq, April 8)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1861]
**Description**
**Sub-lineage of:** BQ.1.2
**Earliest sequence:** 2023-1-27, Nigeria — EPI_ISL_17038850
**2nd-earliest sequence:** 2023-3-20, Ireland — EPI_ISL_17325799
**Most recent sequence:** 2023-3-29, England — EPI_ISL_17423437 + 6 other sequences
**Countries circulating:** England (7), Ireland (1), Nigeria (1), USA (1)
**Number of Sequences:** 10
**GISAID AA Query:** Spike_I666V, Spike_V445A, NS8_C90stop  
**GISAID Nucleotide Query:** A22001G, G26951C, C28163A
**CovSpectrum Query:** Nextcladepangolineage:BQ* & [3-of: A22001G, G22599C, T22896C, G26951C, C28163A]
**Substitutions on top of BQ.1.2:**
**Spike:** K147E, N188Y, R346T, V445A (7/9 also have N703Y)
**ORF8:** C80*
**Nucleotide:** A22001G, G22599C, T22896C, G26951C, C28163A (and 7/9 with A23558G)
 
**AA Deletions:** S:∆186-187
**Nucleotide Deletions:** ∆22119-22124

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1.2_K147E_186-187del_V445A_N703Y_subtreeAuspice1_genome_20228_197cf0.json   
 
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/33738461/230733399-e3b2358c-2e68-4f68-b3cc-00fa3f2ee53c.png">

**Evidence**
The first sequence in this lineage was in late January in Nigeria. No further sequences appeared until very recently, when nine more have been uploaded—seven from England, one from Ireland, and one from Illinois, USA. It's hard to tell for certain due to lack of surveillance and low-quality sequencing, but this lineage could be much more common in the region around Nigeria than elsewhere. The recent spate of cases could be a fluke, but the number of spike mutations, the rare (out-of-frame) spike deletion, and the large differences between the sequences from four geographically widespread locations combine to make this an intriguing lineage.
 
All seven sequences from England almost certainly have both R346T and N703Y but three are missing coverage in one or both of those areas. The sequence from Nigeria has >6% NNN's.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17038850, EPI_ISL_17325799, EPI_ISL_17384968, EPI_ISL_17423308, EPI_ISL_17423360-17423361, EPI_ISL_17423369, EPI_ISL_17423392, EPI_ISL_17423410, EPI_ISL_17423437
</details>

**Comment by thomasppeacock** [comment]
Recommending this as it seems (a late) example of a great convergence lineage and I think its good to continue to try and keep tabs on those.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.2.2 with 7 newly designated sequences, and 0 updated. Defining mutations C28163A (ORF8:C90*), A22001G (S:K147E), T22896C (S:V445A), G26951C (following 22599C (S:R346T)).

**Comment by corneliusroemer** [comment]
Thanks @InfrPopGen!
