### ISSUE TITLE
New CH.1.1 sublineage with S:T323K with advantage versus parental lineage spreading in UK (41 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1862]
As expected where CH.1.1 reached early high prevalence (Uk,Aus,Den,SIngapore) there it has evolved in the most interesting ways. 
While no CH.1.1 lineage seems able to compete with the XBBers army i want to propose here a new sublineage with a large advantage over parental CH.1.1.
it belongs to the big CH.1.1 branch with C21811T ( as CH.1.1.12, FK.1 and other important sublineages)  

Defining mutations:
CH.1.1 >> >C21811T>C193T> A24772G >S:T323K ( C22530A)

Tree:

![Schermata 2023-04-08 alle 22 24 26](https://user-images.githubusercontent.com/87669813/230741205-77379da5-3f39-45be-ab54-7de2ed7f2621.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20f6c_1b8830.json?label=id:node_8158277

Gisaid query: C21811T,C193T, A24772G , C22530A

Sequences: 37 Gisaid (41 on Usher)
EPI_ISL_16484346, EPI_ISL_16515651, EPI_ISL_16978272,
EPI_ISL_16996419, EPI_ISL_17029562, EPI_ISL_17030854,
EPI_ISL_17097290, EPI_ISL_17098497, EPI_ISL_17098513,
EPI_ISL_17098525-17098526, EPI_ISL_17165076, EPI_ISL_17178506,
EPI_ISL_17178508, EPI_ISL_17178613, EPI_ISL_17198927,
EPI_ISL_17233516, EPI_ISL_17241840, EPI_ISL_17242167,
EPI_ISL_17245519, EPI_ISL_17245726, EPI_ISL_17245978,
EPI_ISL_17256971, EPI_ISL_17347504, EPI_ISL_17347509,
EPI_ISL_17347514, EPI_ISL_17363285, EPI_ISL_17372861,
EPI_ISL_17372885, EPI_ISL_17372902, EPI_ISL_17372979,
EPI_ISL_17373034, EPI_ISL_17382351, EPI_ISL_17412318,
EPI_ISL_17416768, EPI_ISL_17423304, EPI_ISL_17423366,

Countries:
![Schermata 2023-04-08 alle 22 27 05](https://user-images.githubusercontent.com/87669813/230741291-7824ae3d-842b-4b91-a500-02698c1c48b7.png)

Growth advantage versus parental lineage:
![Schermata 2023-04-08 alle 22 18 51](https://user-images.githubusercontent.com/87669813/230741005-ba93b22c-209a-4987-b8b5-7aebbad388f6.png)
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?nextcladePangoLineage=CH.1.1*&aaMutations1=S%3AT323K&nextcladePangoLineage1=CH.1.1*&analysisMode=CompareToBaseline&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage CH.1.1.23 with 21 newly designated sequences, and 3 updated. Defining mutation C22530A (S:T323K) (following A24772G).
