### ISSUE TITLE
XBB.2.3 sublineage with S:T478I - 11 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1865]
As noted by @aviczhl2 in #1846 S:478 is mutating in several ways in XBB.2.3,
![Schermata 2023-04-09 alle 23 01 31](https://user-images.githubusercontent.com/87669813/230796357-b3499858-0512-48b5-92ca-65e80d2d72d3.png)

here i spotted  a 11 sequences lineage likely circulating since a while in some undersampled area of India.
I dont think it will go anywhere but better to monitor it:

Defining mutations:
XBB.2.3 >> S:T478I ( A22995T)

Tree:
![Schermata 2023-04-09 alle 23 08 26](https://user-images.githubusercontent.com/87669813/230796567-e9d97750-68a8-4a34-a3d4-2828abfffe20.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_412ff_322d90.json?c=gt-S_478&label=id:node_6021442

Gisaid query : Spike_T478I,Spike_P521S

Sequences:11 
IND/2927/2023\|OQ701285.1\|2023-03-08
Singapore/R13MR53/2023\|EPI_ISL_16975275\|2023-02-09
Singapore/R12MR31/2023\|EPI_ISL_16905211\|2023-02-06
Singapore/R11MR123/2023\|EPI_ISL_16899375\|2023-02-04
India/KA-VRDL-BMCRI1119/2022\|EPI_ISL_16497148\|2022-12-28
India/KA-SLS-56009/2023\|EPI_ISL_17391362\|2023-02-27
India/KA-SLS-53006/2023\|EPI_ISL_16939602\|2023-01-03
India/GJ-GBRC10480/2023\|EPI_ISL_17269894\|2023-03-09
India/GJ-GBRC10550/2023\|EPI_ISL_17270018\|2023-03-09
India/KA-SLS-53026/2023\|EPI_ISL_16939621\|2023-01-15
India/KA-SLS-53021/2023\|EPI_ISL_16939616\|2023-01-10

**Comment by FedeGueli** [comment]
thx @aviczhl2 i ve downloaded them directly from the tree it likely has changed since i will recheck later from pc

**Comment by aviczhl2** [comment]
> thx @aviczhl2 i ve downloaded them directly from the tree it likely has changed since i will recheck later from pc

1: The usher branch of S:K478I has 11 seqs, which is what you listed.
2: However, 2 of the seqs has 478 reversion, likely not actually  belonging to this branch. So the actual number  of XBB.2.3+S:T478I is 9.
3: There are another 2 seqs in XBB.2.3.2 with S:478I. So querying the GISAID you also get 11.

**Comment by corneliusroemer** [comment]
Very small and no recent uploads, ping me if it reaches 50 sequences

**Comment by FedeGueli** [comment]
14 viruses as today last samples came from Karnataka and Delhi.

**Comment by FedeGueli** [comment]
20 sequences now.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12ed3_ff7980.json?c=gt-S_478&label=id:node_6106132
![Schermata 2023-05-01 alle 19 36 32](https://user-images.githubusercontent.com/87669813/235498275-c9465ce2-a213-4496-b110-3a90e1aad90f.png)
