### ISSUE TITLE
Multiple XBB.2.3 sublineages with S:T478R  (A Umbrella*= 72, D=XBB.2.3.10 + S:T478R = 18 )  updated on 04/05  

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1866]
While i dont expect much from #1865 , i think collection dates of these ones via international travels could make me wonder they could be fast.
They have all S:478K mutated to R as XBB.1.16 and a bunch of other lineages designated recently or undesignated.

**_**UMBRELLA LINEAGE A**_**   **NOW 72 seqs** updated on 04/05 It is **FAST** growing 
Defining mutations:
XBB.2.3 >> S:T478R (A22995G)

Gisaid query : C22995G ,C23123T,G6536A,-C10202T,-C2013T ,-C3773T,-C4577T,-T5947C,-C9661T,-T10093C,-A15002G,-T15411C,-T16389C, -C19200T, (NEW- EDITED)

**AS AKNOWLEDGED IN THE COMMENTS THIS IS NOT A MONOPHYLETIC LINEAGE BUT IT IS AN UMBRELLA WHERE USHER collects various independent emergence of S:T478R**

EDITED 04/05/2023

Actually i see:
Lineage A1 with C25075T at 29 sequences (eligible to designation)

Lineage A2 with G1742A (Orf1a:G493S) at 17 sequences

Lineage A3 with C13608T 9 sequences

Lineage A4 with T16389C 4 sequences

Lineage A5 with C5979T, T5983C,C21846T, C28657T 3 sequences

Tree: ![Schermata 2023-05-03 alle 11 29 35](https://user-images.githubusercontent.com/87669813/235880330-1bec230b-7516-4f2d-8c95-ad4cb314504d.png)
![Schermata 2023-05-04 alle 17 09 43](https://user-images.githubusercontent.com/87669813/236250238-74604b1e-404e-4567-ab94-558cf36877c6.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34030_3c8e20.json?c=userOrOld&label=id:node_6126915

**********************************************************

**LINEAGE D :**  NOW the parental with T5947C has been designated **XBB.2.3.10**  ( 18 sequences)

Defining mutations:
XBB.2.3.10 > S:T478R ( C22995G )

Gisaid query:   T5947C,C22995G

Sequences : **4** 
EPI_ISL_17465326, EPI_ISL_17504025, EPI_ISL_17511338, EPI_ISL_17495982

Countries : NZL , Thailand (via South Korea airports), India (Singapore Airport)

Tree: 
<img width="1082" alt="Screenshot 2023-04-29 alle 19 06 50" src="https://user-images.githubusercontent.com/87669813/235314906-5b270043-8705-4eac-acfe-a05cad0a596f.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a9e9_d4e3a0.json?c=userOrOld&label=id:node_6099533

DESIGNATED ONES below this line
**********************************************************

**_LINEAGE C_** now designated **XBB.2.3.8**

This is a sublineage of the one **proposed** by @aviczhl2 in #1821 ( and shown there in the last comment as 09-04-23)
So its designation should be postponed **after** the designation of the proposed branch in #1821 

Defining mutations:
XBB.2.3+Orf1a:L3839F (from #1821) >> ORF1a:A583V (C2013T),  T16389C, S:T478R (A22995G)

Gisaid query :  C2013T,  T16389C, C22995G

Sequences: **4** original post
EPI_ISL_17346815, EPI_ISL_17346837, EPI_ISL_17388575,
EPI_ISL_17416488

Tree:
![Schermata 2023-04-09 alle 23 56 33](https://user-images.githubusercontent.com/87669813/230798363-dbf3d048-5a49-4a3b-b4f9-495a705f7762.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_15711_32b920.json?c=userOrOld&label=id:node_6021792

*************

Lineage B **now **XBB.2.3.9 +S:T478R** 

Defining mutations:
XBB.2.3>> C18744T, C19200T, S:S98F (C21855T) > Orf1a:L1438F (C4577T), ORF1b:Y512C (A15002G), S:T478R (A22995G)

Gisaid query:NSP12_Y521C,Spike_T478R,NSP3_L620F

Sequences : 5 original post
EPI_ISL_17197607, EPI_ISL_17197654, EPI_ISL_17373798,
EPI_ISL_17391371

Tree:

![Schermata 2023-05-04 alle 16 57 03](https://user-images.githubusercontent.com/87669813/236246744-34214d97-52e1-4055-b188-c30cbc5f2af2.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29fef_3c5320.json?c=gt-S_478&label=id:node_6125743

**Comment by aviczhl2** [comment]
I wonder if the upper and lower branches of orf1a:L3829F are the same real branch or independently gained,  given it is a highly convergent mutation often appearing in chronic saltations. 

Maybe the upper and lower one shall be designated independently?  

Or even more, maybe the lower one is in fact a sub-branch of S:K478R and gets orf1a:L3829F together with orf1a:A583V?

**Comment by FedeGueli** [comment]
Yes @aviczhl2 it could be but cant be proven (as today) if the tree stays the same it is now i am not pro over designations even if what you explained in this issue and the other is likely true.

**Comment by aviczhl2** [comment]
> S:T478R is also homoplastic, so it is also doubtful whether the mutation S:T478R in the proposed lineage A is real monophyletic. Personally speaking, I would trust the automated generated tree and designate in that way as long as there is obvious artifact.

The tree may alter as more sequences come. It is not very stable though.

**Comment by FedeGueli** [comment]
4 new sequences from Singapore plus 2 from Virginia for **Lineage A**

5 sequences from Singapore for **Lineage C**

**Comment by FedeGueli** [comment]
Lineage A proposed here reached 33 sequences it is quite fast and it has been sampled from travellers both  from thailand and India. I suggest a rapid designation of LINEAGE A in this proposal @thomasppeacock @InfrPopGen @corneliusroemer @AngieHinrichs .

Caveat as pointed by @aviczhl2 lineae could collect various homoplasic emergence of 478R directly from the XBB.2.3 politomy. Same i think it would be designated also there is no way to distinguish homoplasic or monophyletic sub branches of it.

**Comment by corneliusroemer** [comment]
I'm sympathethic to designating these, but some are still a bit small and paths unstable so best to wait a week or two more for things to settle. There's already plenty of 478R lineages out there so these ones are not at the forefront in terms of spread.

C looks fine, but still too small with 12 sequences. It looks like T16389C and S:T478R appear together in other locations on the XBB.2.3 Usher tree, so T16389C may well have happened before the known homoplasic Orf1a:L3839F.

A doesn't look good, these are most likely multiple lineages given we have only deep branches but no basal sequences. The biggest lineage has 9 sequences so far, too small to ensure stability. I wouldn't call A a lineage, it's a collection of lineages.

B looks fine but very small (<10) - also there's the question about the S:98F, let's see how this grows.

Same with D, very small.

Please ping me if any of the proper lineages (C/B/D or sublineage of A reach 25 seuqences and I'll have another look)

**Comment by FedeGueli** [comment]
@AngieHinrichs i did not understand why usher groups lineage A proposed here together when every single branch has its own basal sequences without 478R, what could we do with them?

@corneliusroemer i would designate every one of them but Lineage B that is stale in the following way
(cause they are growing very fast i think among the fastest around as today. )

SO Keeping your ok greenlight  for C and D if they reach 50 and 25 seqs respectively(just to say) 
i would designate also the so called umbrella Lineage A  with:
1) C4582T, C25075T 11 seqs
2) G1742A (ORF1a:G493S) 9 seqs
3) C13608T 7 sequences 
IF they reach , to say, 25 seqs each.
the branch with T16389C instead i thin k it is basal to C.

**Comment by krosa1910** [comment]
Hi, fede @FedeGueli 
I independently discovered your lineage C when looking at L3829F in XBB.2.3* , that search overlap too much with #1821 and your current issue, so I would like to update on this issue.
Total of 104 seqs now exist under the umbrella search C22995G,C23123T,G6536A, 96 are good.
B seem to stay low and has disappeared for a while, I added C19200T and it showed 6/6 seqs.
C is growing fast, and a lot of seqs are updated after04/26. Using additional T16389C gives 42/42 seqs
D is decent for growth and spread but small, using additional T5947C gives 9/9 seqs.
Treating everything else as A, then it would have 47/39 seqs.
I guess that proposing multiple lineages mean that definition is really important. D for example seems a bit broad per say.
 Undeniably still, C seems most promising, followed by D. Unless A get specified clearly and some sub-A show levels comparable with C and D, or B spreads with new seqs I think those shall be postponed.
If you give the permission, then I would propose a new issue with C to keep it more focused.

**Comment by FedeGueli** [comment]
Lineage B scratched from main post: **_Lineage B_**   
Defining mutations:
XBB.2.3>>  C18744T, C19200T, S:S98F (C21855T) > Orf1a:L1438F (C4577T), ORF1b:Y512C (A15002G), S:T478R (A22995G)

Gisaid query:NSP12_Y521C,Spike_T478R,NSP3_L620F

Sequences : **5** original post
EPI_ISL_17197607, EPI_ISL_17197654, EPI_ISL_17373798,
EPI_ISL_17391371

Tree: 
![Schermata 2023-04-09 alle 23 48 30](https://user-images.githubusercontent.com/87669813/230798059-08016a61-b8ad-4614-8597-5ce9f1c1d513.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_15711_32b920.json?c=userOrOld&label=id:node_6021480

**Comment by FedeGueli** [comment]
Hi @krosa1910  i have updated number of sequences: (A=52 C=46 D=16) i have scratched B cause it is not growing. I think it is not better to open another issue there are already many. I think next week @corneliusroemer will check these lineages and he will choose the prominent ones. Unlikely A as a whole but both C and D could be designated quite directly from here.

**Comment by krosa1910** [comment]
> Hi @krosa1910 i have updated number of sequences: (A=52 C=46 D=16) i have scratched B cause it is not growing. I think it is not better to open another issue there are already many. I think next week @corneliusroemer will check these lineages and he will choose the prominent ones. Unlikely A as a whole but both C and D could be designated quite directly from here.

I feel like it would be very helpful if some standards of creating and designating issues would be set within the community. 

I would suppose say one would only open new issue if spot some variant with a minimum of 20 seqs, latest seq submitted within 30 days, and at least spreading in 3+ regions (for large countries)/ countries. Compromises could be made but a detailed explanation is required. Not sure how the procedure could got standarized on the assignee side.

**Comment by FedeGueli** [comment]
Thx @HynnSpylor i missed that (i didnt recheck the nextclade after D was added!) very important deletion, 186 is XAY defining  and the 181-185 series is usually one of the first way the virus tries to gain advantage especially from BA.5 rise ahead.

**Comment by corneliusroemer** [comment]
C can be designated now with ~50 sequences (or 25 if I double counted) and clean in Usher tree with defining mutations: C2013T, T16389C

**Comment by FedeGueli** [comment]
> C can be designated now with ~50 sequences (or 25 if I double counted) and clean in Usher tree with defining mutations: C2013T, T16389C

C=46 but ok i dont think it will take a lot to reach 50 ;)

**Comment by FedeGueli** [comment]
![Schermata 2023-05-01 alle 19 34 33](https://user-images.githubusercontent.com/87669813/235497964-85014135-a854-4de2-8061-39cf6be2337f.png)
D also clear but smaller at 15 samples.

**Comment by AnonymousUserUse** [comment]
Don't forget the link @FedeGueli

**Comment by FedeGueli** [comment]
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12ed3_ff7980.json?f_userOrOld=uploaded%20sample

**Comment by FedeGueli** [comment]
@corneliusroemer XBB.2.3.8 very preliminary scores high in Collection 24/42 , flagging this to you and the team.
![Schermata 2023-05-02 alle 02 25 48](https://user-images.githubusercontent.com/87669813/235554286-bac582d1-4c18-490c-b2b9-1af30e220b00.png)
https://cov-spectrum.org/collections/42

.

**Comment by corneliusroemer** [comment]
I'd recommend to hype small lineages less. We designate lineages that often by chance happen to have grown recently - so newly designated lineages will almost always have an inflated growth advantage. Also, those growth advantages using global sequences are heavily biased by where sequences are uploaded from most quickly. I'd really like it if this was not overinterpreted. You'll see it'll come down very soon.

**Comment by FedeGueli** [comment]
> I'd recommend to hype small lineages less. We designate lineages that often by chance happen to have grown recently - so newly designated lineages will almost always have an inflated growth advantage. Also, those growth advantages using global sequences are heavily biased by where sequences are uploaded from most quickly. I'd really like it if this was not overinterpreted. You'll see it'll come down very soon.

No hype here, just flagging as it is a duty of mine to do.
in this case i dont see a country that could bias this one more than the others in the same chart, the only thing is that it is very small so usually this kind of growth advantages set down to usual ranges. Still i ecpect this one to keep its place in the leading group. we will see

**Comment by FedeGueli** [comment]
Deleted a bunch of message to keep this readable.

**Comment by FedeGueli** [comment]
The new Lineage A query shows how many times 478R is popping up independently without counting for lineages grouped aunder A umbrella : Gisaid query : C22995G ,C23123T,G6536A,-C10202T,-C2013T ,-C3773T,-C4577T,-T5947C,-C9661T,-T10093C,-A15002G,-T15411C,-T16389C, -C19200T, (NEW- EDITED)

**Comment by FedeGueli** [comment]
Much clearer in the downsampled tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1a7f0_3cccc0.json?branchLabel=nuc%20mutations&f_userOrOld=uploaded%20sample&label=id:node_6125599
![Schermata 2023-05-04 alle 17 22 21](https://user-images.githubusercontent.com/87669813/236253801-4863ea5e-258e-4a16-90f9-9e1769e456e6.png)
I count 10 sublineages with S:T478R (9 +XBB.2.3.8)

**Comment by FedeGueli** [comment]
Fantastic work @corneliusroemer i m very.happy this super.messy issue is finally closed !
