### ISSUE TITLE
XAY.1.1.1 sublineage with S:K150N in Austria (4 seq and 11 spike-only seq) plus 1 seq of recombination with XBB+S:486P-like RBD

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1867]
EPI_ISL_17092915
EPI_ISL_17092899
EPI_ISL_17189750
EPI_ISL_17398232
Spike-only:
EPI_ISL_16874079
EPI_ISL_17235506
EPI_ISL_17083312
EPI_ISL_17235333
EPI_ISL_16804065
EPI_ISL_17082600
EPI_ISL_17366179
EPI_ISL_17011057
EPI_ISL_16942511
EPI_ISL_17166776
EPI_ISL_16874395
Substitutions on top of XAY.1.1.1: ORF1a:P1640S(C5183T) then C8140T then S:K150N(A22012T)
![1](https://user-images.githubusercontent.com/115189228/230830904-fbe4fcd6-13d4-442f-a962-4e86d22330c0.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33bfd_395560.json?c=gt-S_150&label=id:node_8979352
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXAY.1.1*%26S%3AK150N&
Three sequences further acquired S:K113R, S:NL211I, and ORF1a:A3625S.
That long branch (EPI_ISL_17401479) looks like a recombination with a XBB*+S:486P lineage. It has S:339H, S:368I, S:445P, S:446S, S:490S but does not have S:446D, S:452R, S:621S.

**Comment by aviczhl2** [comment]
Will XAY-XBB recombinants still be called "Omicron"?

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As, after a month, it has yet to evidence marked growth, spread or a strong relative growth advantage, this can be closed for now. Please request reopening should this one show a strong reemergence.
