### ISSUE TITLE
XBB.2.6 sublineage with S:P521S and Orf9b:P51Q circulating in Peru'/Chile/Brazil/USA, Netherlands, Canada (233 seqs - >20% prevalence in Peru' after April 1st.

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1869]
I have found a sublineage of XBB.2.6 defined by S:P521S that further acquired Orf9b:P51Q that has been sampled multiple times in US airport surveillance.

Defining mutations:
XBB.2.6 >>  > S:P521S (C23123T) > T6895C, T9148C, A15192C, Orf9b:P51Q  (C28435A )

Gisaid query: T9148C, A15192C, C28435A

Sequences: 7 (2 Chile, 2 Peru, 3 Us )
EPI_ISL_17168346, EPI_ISL_17271459, EPI_ISL_17286697,
EPI_ISL_17401628, EPI_ISL_17405026, EPI_ISL_17405045,
EPI_ISL_17411947

Tree:
![Schermata 2023-04-10 alle 12 12 40](https://user-images.githubusercontent.com/87669813/230882160-92994b1f-d96f-4b02-a128-7009e2a9b661.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2b381_3db880.json?c=userOrOld&label=id:node_6028006

**Comment by FedeGueli** [comment]
8 Sequences , last one from Chile.

**Comment by FedeGueli** [comment]
9 sequences last one from Chile

**Comment by FedeGueli** [comment]
12 sequences as today : 3 more samples two from Lima and one from Brazil, Minais Geras.

**Comment by FedeGueli** [comment]
Mores samples uploaded today from Peru' plus an airport surveillance from Virginia and one from Texas. total count is 20

**Comment by FedeGueli** [comment]
Odd but true this is growing fast , 7 new sequences 8from March) uploaded by Peruvian scientists:
It is 13 seqs out 99 collected in peru' after 1st of March .
pinging @corneliusroemer on this one, i would have not bet anything on this but it keeps going in South America.

**Comment by corneliusroemer** [comment]
Hmm, bit small, also 521S seems to be a bit too homoplasic in XBB.2.6 - maybe some QC issue?

**Comment by FedeGueli** [comment]
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20860_55bed0.json?c=userOrOld&label=id:node_6126969

![Schermata 2023-05-05 alle 21 44 00](https://user-images.githubusercontent.com/87669813/236554936-6f70b10a-c5ef-4c33-a7e7-d88c5e58de15.png)

Cornelius look at the tree it seems clean. S:P521S is larger than 521S +orf9b:P51Q

There is also a S:490P +S:P521Q that seems growing:
![Schermata 2023-05-05 alle 21 45 47](https://user-images.githubusercontent.com/87669813/236555205-e27e1c7e-5885-43eb-93c2-8a887032b383.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20860_55bed0.json?label=id:node_6126511

**Comment by FedeGueli** [comment]
@corneliusroemer i see what you meant the whole xbb.2.6 tree is messy at S:P521S , right, let see how evolves this sublineage 
![Schermata 2023-05-06 alle 08 47 31](https://user-images.githubusercontent.com/87669813/236608015-2eb0cc3b-788e-4f72-819c-1ae838b5177d.png)

**Comment by corneliusroemer** [comment]
Yeah, I think Peru has some QC issues, so that makes Usher struggle distinguishing between real and artefactual homoplasy.

**Comment by FedeGueli** [comment]
Huge uplaod from Peru' in the last  days it reached 110 sequences , it counts 31 out of 132 samples from Peru' collected after first of April . I am reopening it for the preproposal page asking for a review @corneliusroemer @InfrPopGen @thomasppeacock 

New tree:

**Comment by corneliusroemer** [comment]
I've also seen this on a few nextstrain trees now - I'll have a look

**Comment by FedeGueli** [comment]
One more sequence from Florida

**Comment by FedeGueli** [comment]
142 seqs as today

**Comment by FedeGueli** [comment]
@corneliusroemer another bump to 166 sequences newly found in Canada and Netherlands.
I think the Orf9b:P51Q could be the key of its apparrent growth.
It is more than 20% of Samples in Peru' ahead of April although looking week by week i can see likely it is starting to go down in the second half of April.
Worth noticing that is one of the few no 486P lineages able to compete nowadays (FK.1/EL.1/XBB.1.31/XBB.1.33/XBB.1.28/FV.1 and ?)

**Comment by FedeGueli** [comment]
Anpther big upload from Peru' reaching 233 seqs. Prevalence in Peru' seems slighty less than 20% in the seond half od April. Still i think it shuld be designated
