### ISSUE TITLE
XBB.1.9.1 with S:Y796H (114 seqs, 18 countries, 16 has S:554G)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1870]
sub-lineage of: XBB.1.9.1
mutations on top of XBB.1.9.1: G20464A(orf1b:D2333N), T23948C(S:Y796H)
GISAID query: G20464A,G23948C,T23018C
No. of sequence: 22(Australia 1 Canada 1 UK 3 Israel 1 Japan 2 Malaysia 1 Oman 1 Singapore 6(2 Turkey, 2 Saudi Arabia), China 4, USA 2)

GISAID query for additional S:554G: C6578T, C11956T, A23223G
Sequences:
C_AA003677, C_AA003678, C_AA003682, C_AA008525

EPI_ISL_17016278, EPI_ISL_17098180, EPI_ISL_17153970,
EPI_ISL_17207295, EPI_ISL_17229248, EPI_ISL_17241474,
EPI_ISL_17243140, EPI_ISL_17246035, EPI_ISL_17256794,
EPI_ISL_17274709, EPI_ISL_17346887, EPI_ISL_17346892,
EPI_ISL_17388104, EPI_ISL_17388463, EPI_ISL_17388813,
EPI_ISL_17394739, EPI_ISL_17428381, EPI_ISL_17429719,
  
First seq: EPI_ISL_17016278(Singapore imported from Saudi Arabia), 2023-2-13
Latest seq:EPI_ISL_17428381(USA) 2023-4-1

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice6_genome_c394_440f00.json?label=id:node_5838426)
<img width="1379" alt="Screen Shot 2023-04-11 at 01 15 25" src="https://user-images.githubusercontent.com/10445944/230955905-a68fd59d-42f5-4cea-b917-93a34efeb19e.png">

**Comment by ryhisner** [comment]
Y796H pops up every now and then, and I think it was one of the mutations seen in Ravi Gupta's early study that followed an immunocompromised patient with a chronic infection. Seems it was something of an antibody-evasion mutation that imposed a slight cost in infectivity. https://www.nature.com/articles/s41586-021-03291-y
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/33738461/231004868-ae8d6a02-9bae-416e-9d53-c830140ee5be.png">

Also interesting is a little 8-sequence cluster of XBB.1.5 that's recently popped up in the state of Ohio, USA. 
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/33738461/231006055-b472c78d-88fd-461e-adf4-1233cccc8d67.png">

**Comment by aviczhl2** [comment]
25 seqs and detected in Germany and France(exported to USA)

**Comment by aviczhl2** [comment]
30 seqs and detected in South Korea.

**Comment by aviczhl2** [comment]
one more from Reunion, Africa

**Comment by aviczhl2** [comment]
68 seqs, sweden, Norway

**Comment by aviczhl2** [comment]
71 seqs, Indonesia

**Comment by FedeGueli** [comment]
@avichzl2 i would add the 554G branch spotted by @NkRMnZr to this proposal, even if it is not predicted to be much beneficial
![Schermata 2023-08-07 alle 13 02 21](https://github.com/cov-lineages/pango-designation/assets/87669813/fa7e5844-0b20-4343-9cf3-20d1f24bb6ea)

**Comment by FedeGueli** [comment]
@NkRMnZr @aviczhl2 there are 4 more sample of the 554G sublineage not yet on Gisaid:
![Schermata 2023-08-08 alle 01 55 50](https://github.com/cov-lineages/pango-designation/assets/87669813/1e6323a2-ea63-4e5e-b1d6-3027e9047409)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2b957_183dd0.json?label=id:node_6751627

**Comment by aviczhl2** [comment]
A long time without new seqs.
