### ISSUE TITLE
Sublineage of CH.1.1.3 with S:S486P(T23018C) and ORF1b:V1520L (G18025T) (36 seqs in 4 conturies)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1872]
Defining mutations: CH.1.1.3>C4900A(ORF1a:H1545Q)>T23018C (S:F486P), G18025T(ORF1b:V1520L), A21979G, C24358T
GISAID query: Spike_F486P, Spike_K444T, Spike_S255P
Earliest seq: 2023-02-24 (New Zealand, EPI_ISL_17252157)
Most recent seq: 2023-03-22 (Australia, EPI_ISL_17408871)
Countries detected: New Zealand (4), Australia (2), Singapore (1)
Usher Tree:
![QQ截图20230411044134](https://user-images.githubusercontent.com/121703496/230996344-cb3f9af8-f351-4747-a014-417d2dfe4092.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_323e_466550.json

Description:
Another attempt for CH* to get S:F486P. It has been observed in 3 countries, but still too small and needs to watch for a time.
Genomes:
EPI_ISL_17252157, EPI_ISL_17252184, EPI_ISL_17347132, EPI_ISL_17388946, EPI_ISL_17408871, EPI_ISL_17422917, EPI_ISL_17422938

**Comment by HynnSpylor** [comment]
11 seqs in 3 countries now (New Zealand 5, Australia 5, Singapore 1)

**Comment by FedeGueli** [comment]
@corneliusroemer this differently from others CH.1.1+486P seems going . If new seqs will come next week i would designate it.

**Comment by HynnSpylor** [comment]
23 seqs now
