### ISSUE TITLE
XBB.2 + S:F486P+Orf1a:V2027I (NSP3_V1209I )sublineage circulating in Russia (81 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1877]
XBB.2 sublinege sampled in many different  regions of Russia (_Bryansk, Omsk, Mordova, Penza, Saint Petersburg, Kovrov, Moscow)_
and exported successfully to Singapore, Israel and Germany.

**Tree:**
<img width="1162" alt="Schermata 2023-04-12 alle 00 27 44" src="https://user-images.githubusercontent.com/87669813/231302558-7177322e-aeee-4911-b8c5-485cf59a1475.png">

<img width="1166" alt="Schermata 2023-04-12 alle 00 27 02" src="https://user-images.githubusercontent.com/87669813/231302473-833d9b3f-d551-4883-9c09-307d824f1037.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22b8f_5dd7c0.json?f_userOrOld=uploaded%20sample&label=id:node_6037818

**Defining mutations:**
XBB.2 >> A21231G >>  ORF1a:V2027I (G6344A),S:F486P (T23018C)

**Gisaid query**:  A21231G ,G6344A, T23018C 

**Sequences** : 40
EPI_ISL_16504361, EPI_ISL_16807781, EPI_ISL_16832523,
EPI_ISL_16847539, EPI_ISL_16975273, EPI_ISL_17105872,
EPI_ISL_17105927, EPI_ISL_17106038, EPI_ISL_17106092,
EPI_ISL_17106126, EPI_ISL_17106132-17106133, EPI_ISL_17106268,
EPI_ISL_17106314, EPI_ISL_17106328, EPI_ISL_17106384,
EPI_ISL_17106426, EPI_ISL_17106483, EPI_ISL_17106497,
EPI_ISL_17264407, EPI_ISL_17317850, EPI_ISL_17317954,
EPI_ISL_17317956, EPI_ISL_17318115, EPI_ISL_17318149,
EPI_ISL_17318250-17318251, EPI_ISL_17318257, EPI_ISL_17318335,
EPI_ISL_17318339, EPI_ISL_17318379, EPI_ISL_17318397,
EPI_ISL_17318443, EPI_ISL_17318471, EPI_ISL_17318482,
EPI_ISL_17318521, EPI_ISL_17318530, EPI_ISL_17318562,
EPI_ISL_17318580, EPI_ISL_17318585

**Comment by FedeGueli** [comment]
47 sequences as today. This week 4 more samples came from Russia (Moscow) 1 from Austria-Tyrol and 2 from Thailand one of them labeled as "foreigner".

@thomasppeacock @corneliusroemer @InfrPopGen I would designate this one for its geographical relevance and further international spread beyond the known fit of iots 486P mutation in the XBB.2 background.

**Comment by FedeGueli** [comment]
57 sequences as today all new samples from Moscow.

**Comment by FedeGueli** [comment]
58 last one from Austria

**Comment by corneliusroemer** [comment]
Ping me when this reaches 100 sequences

**Comment by FedeGueli** [comment]
Thx @corneliusroemer for your great work 
I think both this one and the other russian xbb.2 +486P have to be tracked for a while and i will be happy to do. I will ping you at 100seqs.

**Comment by FedeGueli** [comment]
New seq from Thailand

**Comment by FedeGueli** [comment]
Interestingly basal to this lineage, lacking defining Orf1a:V2027I there is a sequence from Belgium defined by S:G482S maybe just misplaced: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_296e8_8e52a0.json?c=gt-S_482&label=id:node_10054482
![Schermata 2023-04-26 alle 11 42 56](https://user-images.githubusercontent.com/87669813/234537190-68698000-acf1-4166-8039-301692cba919.png)

**Comment by FedeGueli** [comment]
One more sample from Germany

**Comment by FedeGueli** [comment]
Big Jump to 81 sequences for this one. Samples came in from 5 different Russian regions and Austria.
I think it deserves a rapid designation . @InfrPopGen @thomasppeacock @corneliusroemer

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage XBB.2.9 with 40 newly designated sequences, and 6 updated. Defining mutations G6344A (ORF1a:V2027I), T23018C (S:S486P) (following A21231G).

**Comment by FedeGueli** [comment]
Thz @InfrPopGen
