### ISSUE TITLE
XBB.1 Sublineage with S:A376T (Rev), S:S486P, S:K964E, ORF7a:Q76*, ORF8:Q72H, ORF1a:T1665I, ORF1a:Q2486P, ORF1b:L1061I (34 seq, April 17)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1879]
### **Description**
**Sub-lineage of:** XBB.1
**Earliest sequence:** 2023-2-21, Italy — EPI_ISL_17062976
**Most recent sequence:** 2023-4-4, Italy — EPI_ISL_17434236 and 8 others
**Countries circulating:** Italy (23), France (3), South Korea (1)
**Number of Sequences:** 27
**GISAID AA Query:** NS8_Q72H, Spike_K964E
**GISAID Nucleotide Query:** A24452G, G28109T
**CovSpectrum Query:** Nextcladepangolineage: XBB* & A24452G & G28109T
**Substitutions on top of XBB.1.5:**
**Spike:** A376T (Reversion), S486P, K964E
**ORF7a:** Q76*
**ORF8:** Q72H
**ORF1a:** T1665I, Q2486P (NSP3_T847I, NSP3_Q1668P)
**ORF1a:** L1061I (NSP13_L138I)
**Nucleotide:** G149C, C5259T, A7722C, C16648A, C18555T, T21201C, G22688A (Reversion), T23018C, A24452G, C27619T, A27965G, G28109T
**AA Deletions:** ORF1a:∆84-85
**Nucleotide Deletions:** ∆515-520

**USHER Tree** (Note: I've only included 21 sequences in this tree because the other six are of such low-quality that they badly distort the tree.)
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1_A376T_S486P_K964E_etc_subtreeAuspice1_genome_5eb8_5fec60.json
 
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/33738461/231322929-6abe6aba-8d79-496e-811a-224baa21aaf2.png">

**Evidence**
So far, XBB.1 lineages have been content with annihilating nearly all of ORF8, but this lineage goes a step further and snuffs out close to 40% of ORF7a. Accessory proteins are beneath it, it seems. I do not know whether it will continue to dismember disposable accessories, but it will be interesting to see. At first I wasn't sure if this lineage was real, but now that sequences have showed up in France and South Korea, I feel pretty confident it is. 

(UPDATE: Actually never mind, it turns out this is one of the very few XBB.1 lineages that does NOT have ORF8:G8*. Except that two sequences appear to have independently picked up ORF8:G8* already—EPI_ISL_17064265 & EPI_ISL_17418058—so maybe it won't be long before most of the rest do as well.)
 
Like a multitude of other XBB* lineages, this one has found S:S486P, and it has also acquired the much less common S:K964E. S:Q954H and S:N969K lent this region of S2 a more positive charge than pre-Omicron lineages, so I'm curious what this charge-reversal mutation might do to counteract that. Perhaps @oobb45729 has some ideas about that? In another rare move, this lineage has reverted back to the original S:376 residue with S:A376T.
 
It has an NSP3 mutation, ORF1a:Q2486P, that is extremely rare, appearing in only about 117 sequences in the entire pandemic. Even more extraordinarily rare is ORF1b:L1061I (NSP13_L138I), which seems to have occurred a mere 35 times outside of this branch of XBB.1 (though some 85 or so XBB.1 sequences share this mutation but not the others that mark this particular sub-branch of the tree).
 
Three of the most recent sequences here—all collected on April 4, 2023—also have S:K182I and N:P151S, the latter a BA.4 throwback. Mutations to various residues (mainly E, N, and I) at S:K182 have been quite common in the past few months, possibly indicating immune pressure there.

Several of the sequences here are so ugly they do not bear looking at—better to avert thine eyes. Still, as gnarled and twisted as parts of these sequences are, it's also clear they are part of this lineage, so I've included them in the count.

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17062976, EPI_ISL_17064265, EPI_ISL_17189377, EPI_ISL_17221706, EPI_ISL_17221708, EPI_ISL_17221711, EPI_ISL_17238724, EPI_ISL_17238814-17238815, EPI_ISL_17346653, EPI_ISL_17375076, EPI_ISL_17390376, EPI_ISL_17390974, EPI_ISL_17408478, EPI_ISL_17418058, EPI_ISL_17421904, EPI_ISL_17433509, EPI_ISL_17433512, EPI_ISL_17433907, EPI_ISL_17434229, EPI_ISL_17434232-17434233, EPI_ISL_17434236, EPI_ISL_17434241, EPI_ISL_17434248, EPI_ISL_17434258, EPI_ISL_17440510 </details>

**Comment by FedeGueli** [comment]
@carlottaolivero this could be interesting to know if you spotted in Wastewater.

**Comment by oobb45729** [comment]
I just came across a paper about seeking substitutions that stabilize the prefusion conformation today. K964E is one of those substitutions,
https://www.biorxiv.org/content/10.1101/2023.03.16.532924v1.full
![1](https://user-images.githubusercontent.com/115189228/231603132-e380d576-f2a0-4a0e-8b16-a24badcbea84.jpg)

**Comment by oobb45729** [comment]
I suspect that T376A may make F375 more flexible and made make switching between the two conformations of the RBD of BA.2-related variants easier. In [https://www.rcsb.org/3d-view/7YQU](url), F375 interacts with Y508, V503, and V407 of another protomer, while in [https://www.rcsb.org/3d-view/7YQW](url), F375 interacts with Y508, V503, and V407 of the same protomer.

**Comment by ryhisner** [comment]
@oobb45729, thanks as always for your insights, which are greatly appreciated! 

I don't see any description of what variant was used in the class I fusion protein preprint. I take that to mean they probably used wild-type, but that makes me wonder if the results are relevant at all in the current context. Omicron lineages may not dominate forever, but their hold on S2 seems unshakeable at this point, Y655H, N679K, N764K, Q954H, and N969K in particular, seem absolutely locked in at this point. There have been myriad recombinants, and just about the only constant they ALL share is the S2 of BA.2. 

It seems clear that all these mutations work together in such a way that the loss of any one—maybe even the the loss of any two of them—leads to a huge loss of fitness. How exactly this works and why this S2 arrangement shuts down fusion and propels endosomal entry is, to me, one of the great outstanding mysteries at the moment. Another one is what exactly the 371-373-375-(376) mutations are doing. Like the constellation of S2 mutations, these three seem pretty well locked in. It seems likely they work synergistically and will only be replaced if there's some kind of radical change.

I remember one weekend I spent some hours poring over papers that discussed the effects of the 371-373-375 mutations in BA.1 and BA.2. Two papers in particular came to pretty clear conclusions. One said the 371-373-375 mutations favored the three RBD down conformation. The other said they did the exact opposite, favoring the 2 RBD down, 1 up conformation. At least one of them, maybe both, found dramatic losses in infectivity with the 371-373-375 combo. Just about the only thing I learned from all that studying was that we don't seem to know much of anything about these mutations. Virology is bloody hard, it seems.

**Comment by oobb45729** [comment]
Maybe this paper about BA.2.75 has some clues about it. https://doi.org/10.1016/j.chom.2022.09.018 The paper shows that for BA.2.75, the ratio between 1-up and 3-down conformation is around 1:1 at pH 7.4, but the ratio between 1-up and 3-down conformation is around 3:1 at pH 5.5. The spike trimer of BA.2.75 is more stable than BA.1 at pH 7.4, but is less stable than BA.1 at pH 5.5. The paper further argues that this may help BA.2.75 utilize the endosomal pathway better, which proceeds with acidic pH.

The 3-down conformations of the spike trimer at pH 7.4 (7YQU) and pH 5.5 (7YQW) are quite different too. I described the main difference of the RBDs above. I think that D339H is probably responsible for it. Histidine gets protonated at low pH. Maybe this is why it triggers a conformational change.

I probably read the papers about the 371-373-375 combo you mentioned. I think they should also take into account at least Y505H, which is an essential part of the new interface between the RBDs.

It's known that N969K stabilizes the S2 unit (https://doi.org/10.1101/2022.09.24.509341). I suspect that what the wastewater classic L828F does too. Interestingly, the same study suggests that Q954H destabilizes the S2 unit (so do D950N and D950H). Maybe H954 could be involved in a pH-dependent thing too? I noticed that H954 is near R1014. My wild guess is that if pH is higher, the unprotonated H954 can interact with R1014, stabilizing the S2 unit, but if pH is lower, the protonated H954 repels R1014 away, getting ready for the fusion.

I have a wilder theory about S371F and S375F. In https://doi.org/10.26508/lsa.202101347, a novel sgRNA is described, which is called pORF2b there, with two alternative TRS's around 22501. If it is translated, the start codon is at 22614-22616 for WT. However, G22578A(G339D) introduces a new start codon, and it is conserved if D339 further mutates to H, Y, N, unless T22579 is also changed, which is not common. Some E340 mutations disrupt the start codon though. G22578A would make the protein 12aa longer. For WT, AlphaFold predicts that the protein would have a mainly α-helix structure that is disrupted by two prolines. The prolines would be lost after C22674T(S371F) and C22686T(S375F).

**Comment by FedeGueli** [comment]
> 
> It's known that N969K stabilizes the S2 unit (https://doi.org/10.1101/2022.09.24.509341). I suspect that what the wastewater classic L828F does too. Interestingly, the same study suggests that Q954H destabilizes the S2 unit (so do D950N and D950H). Maybe H954 could be involved in a pH-dependent thing too? I noticed that H954 is near R1014. My wild guess is that if pH is higher, the unprotonated H954 can interact with R1014, stabilizing the S2 unit, but if pH is lower, the protonated H954 repels R1014 away, getting ready for the fusion.
> 

BV.1 a Serbian BA.5.2 descendant had S:R1014K

**Comment by Outpfmance** [comment]
@ryhisner As we know, Omicron strains all carry N969K, this mutation can change and lock up the cellular pathway, and make FCS almost unuseful on Omicron. I tried to trace XBB*+K969N before, but these sequences were not qualified, which also proved that N969K was extremely stable, and Rev could not do it basically. So do you think a mutation like K964E that reverses charge could work against N969K? Can the Omicron entry pathway be unlocked and FCS function again?

**Comment by oobb45729** [comment]
> @ryhisner As we know, Omicron strains all carry N969K, this mutation can change and lock up the cellular pathway, and make FCS almost unuseful on Omicron. I tried to trace XBB*+K969N before, but these sequences were not qualified, which also proved that N969K was extremely stable, and 969NRev could not do it basically. So do you think a mutation like K964E that reverses charge could work against N969K? Can the Omicron entry pathway be unlocked and FCS function again?

I don't know.

**Comment by FedeGueli** [comment]
@corneliusroemer @InfrPopGen it seems to have increased its share in Italy, maybe better to wait a week more to be sure that there is not some cluster effect but usually Italy doesnt detect the growth of variants when numbers are small. Instead in this case it is clearly going up.

https://cov-spectrum.org/explore/Italy/AllSamples/from%3D2023-03-01%26to%3D2023-04-08/variants?nucMutations=A24452G%2CC27619T&

**Comment by focosi-cyber** [comment]
> I just came across a paper about seeking substitutions that stabilize the prefusion conformation today. K964E is one of those substitutions,
> 
> https://www.biorxiv.org/content/10.1101/2023.03.16.532924v1.full
> 
> ![1](https://user-images.githubusercontent.com/115189228/231603132-e380d576-f2a0-4a0e-8b16-a24badcbea84.jpg)
> 
> 

proline mutations have been introduced at K986 and V987 within HR1 of the S2 fusion machinery in both mRNA vaccines (BNT162b2 and mRNA-1273) to stabilize the perfusion conformation

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage XBB.1.33 with 40 newly designated sequences, and 0 updated. Defining mutation G22688A (S:A376T) (following T23018C (S:S486P)).

**Comment by ryhisner** [comment]
Second sequence of XBB.1.33 came in yesterday from South Korea. SK's a pretty fair jump from Italy. EPI_ISL_17538917

**Comment by Memorablea** [comment]
A sequence of XBB.1.33 was transmitted from Austria.EPI_ISL_17565463
![image](https://user-images.githubusercontent.com/125779492/235286936-e9bd7797-5288-490f-aaae-ae25ec5dc066.png)

**Comment by FedeGueli** [comment]
CC @AngieHinrichs i was looking at XBB.1.33 tree and i noticed that not all XBB.1.33 are assigned as XBB.1.33 by Usher:

Usher requires also C11644T but that is not defining of XBB.1.33

Also the other branch ith C19698T should be called XBB.1.33

![Schermata 2023-05-30 alle 01 04 16](https://github.com/cov-lineages/pango-designation/assets/87669813/f0d1877c-264e-4eb1-b974-08d3b37ab94d)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_2998b_52ed60.json?label=id:node_6643120

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs !!
