### ISSUE TITLE
Saltation of XBB.1.28.1 with ORF9b:I5T (6 seqs as of 2023-04-20, Korea)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1884]
I am to propose this potential saltation branch with only 5 sequences at the moment, based on its concerning mutation profiles.

### Description
**Sublineage of**: XBB.1.28.1 (XBB.1 with S:K356T and S:R403K)
**Earliest sequence**: 2023/03/13 (Korea)
**Most recent sequence**: 2023/04/01 (Korea)
**Countries circulating**: Korea

**Mutations on top of XBB.1.28.1**: G1306A, A8170G, T8634C (ORF1a:I2790T), A23670G (S:N703S), T28297C (ORF9b:I5T), C29518T

**GISAID and Cov-spectrum query**: G1306A, T8634C, A23670G

### Evidence
Usher tree:
![image](https://user-images.githubusercontent.com/86835836/231955407-5bea2de3-8412-41fc-8d9c-6fabb7f6ebce.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d05b_8e9f10.json?c=gt-nuc_28297&label=id:node_5864515

### Genomes:
EPI_ISL_17373954, EPI_ISL_17415316, EPI_ISL_17463591, EPI_ISL_17463594-17463595

**Comment by FedeGueli** [comment]
S:N703S was tracked for a while in the XBB.1.5 spike mutation issue , i rechecked it and it seems to confer a moderatea dvantage of 5% -  7% over plain xbb.1.5 baseline (https://cov-spectrum.org/explore/Europe/AllSamples/Past6M/variants?nextcladePangoLineage=XBB.1.5*&aaMutations1=S%3AN703S&nextcladePangoLineage1=XBB.1.5*&analysisMode=CompareToBaseline&)

**Comment by c19850727** [comment]
not growing. close for now.
