### ISSUE TITLE
XBB.1.28.1 with S:S486P, ORF1a:V627I, ORF1a:Q946R, ORF3a:S195P (9 seqs as of 2023-04-24, US-NC)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1885]
### Description
**Sublineage of**: XBB.1.28.1 (XBB.1 with S:K356T and S:R403K)
**Earliest sequence**: 2023/02/26 (Italy-Veneto)
**Most recent sequence**: 2023/04/03 (US-NC)
**Countries circulating**: US (6/8), Italy (2/8)

**Mutations on top of XBB.1.28.1**: G10835A (ORF1a:V3524I) > G2144A (ORF1a:V627I), A3102G (ORF1a:Q946R), C8293T, T23018C (S:S486P), T25975C (ORF3a:S195P) 

**GISAID and Cov-spectrum query**: A3102G, T25975C, G2144A, C8293T, T23018C

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/231960870-544aab59-bc41-4c00-8490-79ce7d077259.png)
(the S:403 reversion in the two Italian sequences are probably artefactual)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d05b_8e9f10.json?c=gt-nuc_3102&label=id:node_5864513

### Genomes
EPI_ISL_17165224, EPI_ISL_17165244, EPI_ISL_17353884, EPI_ISL_17417303-17417306, EPI_ISL_17466306

**Comment by FedeGueli** [comment]
i just noticed that the American branch of this sublineage has the infamous E:P71S mutation that has been shown in vitro to increase cell lethality:
https://www.biorxiv.org/content/10.1101/2023.01.09.523338v1.full ( thx to @ejustin46 > https://twitter.com/ejustin46/status/1646008348842622976?s=20)

**Comment by alurqu** [comment]
> i just noticed that the American branch of this sublineage has the infamous E:P71S mutation that has been shown in vitro to increase cell lethality: https://www.biorxiv.org/content/10.1101/2023.01.09.523338v1.full ( thx to @ejustin46 > https://twitter.com/ejustin46/status/1646008348842622976?s=20)

If I understand Schoeman et al, “The Flexible, Extended Coil of the PDZ-Binding Motif of the Three Deadly Human Coronavirus E Proteins Plays a Role in Pathogenicity", Viruses, https://doi.org/10.3390/v14081707 and that structural rigidity effect of proline correctly, E:P71S could reasonably increase the flexibility of the E C-terminal PDM and thus increase the pathogenicity of the virus. That gives a second source providing a possible mechanism for the effect of E:P71L and E:P71S discussed in Wang et al, “Inspiration of SARS-CoV-2 envelope protein mutations on pathogenicity of Omicron XBB", bioRxiv preprint, https://doi.org/10.1101/2023.01.09.523338 referenced by @FedeGueli.

Digging a little deeper and looking at the mutation fitness estimates (Bloom and Neher, “Fitness effects of mutations to SARS-CoV-2 proteins", bioRxiv preprint, https://doi.org/10.1101/2023.01.30.526314) specifically by clade (aamut_fitness_by_clade.csv in https://github.com/jbloomlab/SARS2-mut-fitness/tree/main/results/aa_fitness; caution large file), E:P71S shows an estimated small increase in fitness for a few Nextstrain clades specifically 20G, 22A, 20C, and 20I with no estimates available at this time for clades 22D, 22E, 22F, or 23A:

clade,gene,clade_founder_aa,mutant_aa,aa_site,aa_mutation,expected_count,actual_count,count_terminal,count_non_terminal,mean_log_size,subset_of_ORF1ab,delta_fitness
20A,E,P,S,71,P71S,12.273,7,5,2,1.002,False,-0.53243
20B,E,P,S,71,P71S,10.33,5,3,2,0.94724,False,-0.67757
20C,E,P,S,71,P71S,6.6838,7,5,2,1.0198,False,0.043075
20E,E,P,S,71,P71S,7.8907,5,3,2,0.66644,False,-0.42238
20G,E,P,S,71,P71S,10.809,13,7,6,0.73012,False,0.17709
20I,E,P,S,71,P71S,45.252,47,25,22,0.60916,False,0.037494
21C,E,P,S,71,P71S,4.7615,2,0,2,1.5455,False,-0.74413
21I,E,P,S,71,P71S,15.755,11,8,3,0.2259,False,-0.34605
21J,E,P,S,71,P71S,183.3,124,74,50,0.68694,False,-0.38954
21K,E,P,S,71,P71S,81.183,36,26,10,0.44845,False,-0.80553
21L,E,P,S,71,P71S,62.364,29,21,8,0.27467,False,-0.75658
22A,E,P,S,71,P71S,9.1052,10,7,3,0.38712,False,0.089071
22B,E,P,S,71,P71S,51.334,25,14,11,0.89469,False,-0.70937
22C,E,P,S,71,P71S,14.016,10,7,3,0.31781,False,-0.32388

However, across all cla

**Comment by corneliusroemer** [comment]
Bit small - no growth since it seems. Ping me if this reaches 25 sequences.

**Comment by c19850727** [comment]
seems not growing. close for now.
