### ISSUE TITLE
XBB.1.16.1 with c. 500 mutations, probably artefact (23 seq. India)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1886]
Proposal for a sublineage of XBB.1.16.1
Earliest sequence: 31.03.2023 (India)
Countries detected: India

I came across this weird cluster from India which is probaly an artefact. Single submitter, mutliple locations, yesterdays upload. 

![grafik](https://user-images.githubusercontent.com/102166254/232003388-d01f1293-51d4-4fe9-bccd-8ae7931ff7c1.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_333b1_91a7e0.json?f_userOrOld=uploaded%20sample

![grafik](https://user-images.githubusercontent.com/102166254/232004698-034579eb-b743-4435-9ab2-329806be35de.png)

EPI_ISL_17466156-17466161, EPI_ISL_17466163-17466179

**Comment by silcn** [comment]
"probably" an artefact? I think you mean "certainly". ORF1a is destroyed by a very early stop codon ORF1a:E10*, and all the new mutations are G->T.

**Comment by corneliusroemer** [comment]
If you think it's an artefact don't open an issue, this just creates admin and noise for everyone.
