### ISSUE TITLE
XBB.1.16 Sublineage with ORF9b:T83I (C28531T), G19326A (R), (22 seq, Apr 14, 16/22 w/S:T732I)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1888]
**Description**
**Sub-lineage of:** XBB.1.16
**Earliest sequence:** 2023-2-23, India, Maharashtra — EPI_ISL_17073061
**2nd sequence:** 2023-3-11, USA, California (traveler from India) —EPI_ISL_17247164
**Most recent sequence:** 2023-4-1, India, Delhi — EPI_ISL_17467336
**Countries circulating:** India (15), USA (3—all travelers, 2 from India, 1 from Singapore), Australia (3), New Zealand (1)
**Number of Sequences:** 22
**GISAID Nucleotide Query:** T28297C, A28447G, C28531T
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.16 & C28531T & !A19326G
**Substitutions on top of XBB.1.16:**
**Spike:** T732I (*16/22 sequences only)
**ORF9b:** T83I
**Nucleotide:** G19326A (Reversion), C28531T (*plus 16/22 with C23757T)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.16_ORF9bT83I_subtreeAuspice1_genome_af88_930ac0.json
 
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/33738461/232101063-264e88b0-21e9-4d6a-af4e-96d7755607b8.png">

**Evidence**
ORF9b, which has not seemed to play a very important role for most of the pandemic, has suddenly become a significant factor, with mutations like ORF9b:I5T seeming to confer a substantial growth advantage (to XBB.1.9.1 and XBB.1.9.2 over XBB.1.5, for example). I think ORF9b:T83I is another mutation that is likely advantageous, presumably by promoting interference with the innate immune response, which several studies have indicated ORF9b is capable of doing.  
 
The two major previous lineages that have had ORF9b:T83I in a substantial portion of sequences were B.1.526 and BA.5.1. In both cases, sublineages with ORF9b:T83I enjoyed a consistent 12-13% weekly growth advantage over those without ORF9b:T83I during the months in which these lineages were prominent. 
 
<img width="993" alt="image" src="https://user-images.githubusercontent.com/33738461/232100768-1881da99-2907-431f-9538-533181d66e99.png">

 
It's hard to say whether ORF9b:T83I will also translate into an advantage for XBB.1.16, but I think it's worth keeping an eye on. It's also noteworthy that over 70% of these sequences also possess S:T732I and that all 16 of these were collected on or after March 14. There is also a reversion of a synonymous nucleotide mutation in this lineage (G19326A), something quite rare but which I don't think is significant in any way.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17073061, EPI_ISL_17247164, EPI_ISL_17326119, EPI_ISL_17326255, EPI_ISL_17408841, EPI_ISL_17422862, EPI_ISL_17427665, EPI_ISL_17427679, EPI_ISL_17428041, EPI_ISL_17428124, EPI_ISL_17428379, EPI_ISL_17428419, EPI_ISL_17447301, EPI_ISL_17447369, EPI_ISL_17447410, EPI_ISL_17466910, EPI_ISL_17467139, EPI_ISL_17467140, EPI_ISL_17467336, EPI_ISL_17467381, EPI_ISL_17469138, EPI_ISL_17469187
</details>

**Comment by corneliusroemer** [comment]
Tree too messy at this point, we need more non-Indian sequences to see where this came from and how it plays with S:T732I which is all over the Usher tree at this point.

Ping me when we have something like 100 sequences of this.

**Comment by ryhisner** [comment]
73 sequences now but doesn't seem to be going anywhere, so I'm closing.

**Comment by FedeGueli** [comment]
Designated XBB.1.16.8

**Comment by FedeGueli** [comment]
> A19326G is the only private mutation on top of the two donors BJ.1 and BM.1.1.1 when they recombine into XBB. It may not be significant though one less efficient 'query hack' for XBBs.

thx great point!
