### ISSUE TITLE
XBB.2.3 sublineage with ORF1b:P403S and S:Q493L (18 seq. India, USA, Spain, Japan)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1889]
EPI_ISL_17427882
EPI_ISL_17326323
EPI_ISL_17269983
EPI_ISL_17428098
EPI_ISL_17326250
EPI_ISL_17326192
EPI_ISL_17308503
EPI_ISL_17427917
EPI_ISL_17268931
EPI_ISL_17428219
EPI_ISL_17268926
EPI_ISL_17326315

Substitutions on top of XBB.2.3: ORF1b:P403S(C14674T) then S:Q493L(A23040T)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2b7bc_9c18e0.json?c=gt-S_493&label=id:node_6033764
![1](https://user-images.githubusercontent.com/115189228/232157089-24d7149b-3d8e-43ca-9103-4cf27e66327a.png)
![2](https://user-images.githubusercontent.com/115189228/232157103-4201eb8f-6153-4ce6-a40c-ee6bc2a8ec4c.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXBB.2.3*%26S%3AQ493L&
![3](https://user-images.githubusercontent.com/115189228/232157398-5e1dac78-f6b5-4a92-9f58-32a2e6c84f94.png)

**Comment by corneliusroemer** [comment]
There've been lots of S:Q493L, none of them seem to have done much so far, so I wouldn't jump to designate with this few sequences.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As it is still, after a month, apparently small, and is showing relative growth disadvantages over the past three months, this can be closed for now. Please request re-opening should this clade show a marked growth acceleration.
