### ISSUE TITLE
XBB.2.3.2 sublineage with ORF1a:T2977I after G24193A and C26228A first detected in Singapore (93 good and 135 total seqs as of 2023-04-14; Asia, North America, Australia, Europe)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1890]
There may be a XBB.2.3.2 sublineage with ORF1a:T2977I (C9195T; NSP4:T214I) after G24193A and C26228A first detected in Singapore.

As of 2023-04-14, Cov-Spectrum reports 93 good-quality (135 total) XBB.2.3.2+ORF1a:2977I+24193A+26228A sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXBB.2.3+%26+ORF1a%3AR2159W+%26+ORF1a%3AT2977I+%26+S%3AG184V+%26+G24193A+%26+C26228A&nextcladeQcOverallScoreTo=29&

As of 2023-04-14, CoV-Spectrum shows that this lineage is the dominant form of XBB.2.3.2 in Singapore with little additional room to grow.
![Frequency-XBB 2 3 2+ORF1a_2977I+24193A+26228A](https://user-images.githubusercontent.com/88959107/232163328-333379c0-1672-4333-b93a-9d40877cd4eb.png)

Source: https://cov-spectrum.org/explore/Singapore/AllSamples/Past6M/variants?aaMutations=ORF1a%3A2159W%2CS%3A184V&nextcladePangoLineage=XBB.2.3&aaMutations1=ORF1a%3A2159W%2CORF1a%3A2977I%2CS%3A184V&nucMutations1=24193A%2C26228A&nextcladePangoLineage1=XBB.2.3&analysisMode=CompareToBaseline&

As of 2023-04-14, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_XBB 2 3 2+ORF1a_2977I+24193A+26228A](https://user-images.githubusercontent.com/88959107/232163365-c03ed02b-80f9-4cff-ab72-4ed6591b1ac4.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/04/subtreeAuspice1_genome_CoV-Spectrum_XBB.2.3.2%2BORF1a_2977I%2B24193A%2B26228A.json?c=gt-ORF1ab_2977&label=id%3Anode_6033410

GISAID query: C6740T, C9195T, G22113T, G24193A, C26228A

First GISAID sequence: Singapore 2023-02-25 

Most Recent GenBank sequence: Singapore 2023-04-04

A zip archive of GenBank-formatted and derived metadata and FASTA files plusCoV-Spectrum-derived UShER output files for these sequences is available at [Support-XBB.2.3.2+ORF1a_2977I+24193A+26228A.zip](https://github.com/cov-lineages/pango-designation/files/11237422/Support-XBB.2.3.2%2BORF1a_2977I%2B24193A%2B26228A.zip).

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-XBB.2.3.2+ORF1a_2977I_24193A+26228.txt](https://github.com/cov-lineages/pango-designation/files/11237423/gisaid-epi-isl-XBB.2.3.2%2BORF1a_2977I_24193A%2B26228.txt)

**Comment by corneliusroemer** [comment]
No need to subdivide XBB.2.3.2 in a non-systematic way when it has ~400 sequences

**Comment by alurqu** [comment]
A sublineage of this lineage -- defined by a synonymous RNA mutation -- was designated HH.1 on 14 July 2023 in commit https://github.com/cov-lineages/pango-designation/commit/b695ac6977c97dfe828634422e78fa26ef5c1177.
