### ISSUE TITLE
XBB.1.5.46 with Orf1a:R1464Q, A2636T, S:K478R (81 seqs, 14 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1891]
Sub-lineage of: XBB.1.5
mutations on top of XBB.1.5:C5770T,C15279T,G4656A(orf1a:R1464Q),C21622T,G8171A(orf1a:A2636T),A22995G(S:K478R)
Gisaid query:C5770T,C15279T,G4656A,C21622T,G8171A,C22995G
                       
No. of Seqs: 26(England 17 North Ireland 1 Brunei 1 Hong Kong 5 Shanghai 1 New Zealand 1)

First Seq: EPI_ISL_16969101(England) 2023.2.9
Latest Seq: C_AA009552(Shanghai) 2023.4.6

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice32_genome_38382_a19bd0.json?label=id:node_5912104)

<img width="1403" alt="Screen Shot 2023-04-15 at 11 42 00" src="https://user-images.githubusercontent.com/10445944/232181716-13ad7308-1cd2-47f1-89e5-779b5eee35f1.png">

**Comment by aviczhl2** [comment]
Seems that those Genbank seqs have GISAID backups but their GISAID ids are simply not displayed on usher. 
So here to fill it. 
EPI_ISL_16969101, EPI_ISL_17016962, EPI_ISL_17098190,
EPI_ISL_17098632, EPI_ISL_17098655, EPI_ISL_17182817,
EPI_ISL_17241808-17241809, EPI_ISL_17241820, EPI_ISL_17241876,
EPI_ISL_17242129, EPI_ISL_17257212, EPI_ISL_17257278,
EPI_ISL_17257291, EPI_ISL_17257382, EPI_ISL_17295416,
EPI_ISL_17317091, EPI_ISL_17350772, EPI_ISL_17433567,
EPI_ISL_17433573, EPI_ISL_17433584, EPI_ISL_17433590,
EPI_ISL_17464089, EPI_ISL_17465332, EPI_ISL_17474093,
C_AA009552

**Comment by aviczhl2** [comment]
28 seqs, Italy and South Korea.

**Comment by corneliusroemer** [comment]
Parent is now XBB.1.5.46

**Comment by aviczhl2** [comment]
35 seqs and detected in Japan.

**Comment by aviczhl2** [comment]
44 seqs, new country of Germany.

**Comment by aviczhl2** [comment]
60seqs,Finland,Singapore,Canada,USA,

**Comment by aviczhl2** [comment]
62 seqs, Portugal

**Comment by aviczhl2** [comment]
80 seqs, Austria
