### ISSUE TITLE
XBB.1.16 sublineage with S:A27S and S:R408S substitutions

### ISSUE THREAD

**Issue by biome-datascientist** [cov-lineages/pango-designation#1894]
Description
Sub-lineage of: XBB.1.16
Earliest sequence: 2023-01-09
Most recent sequence: 2023-04-04
Countries: India, Singapore, USA, Canada ....
Query in CovSpectrum: XBB.1.16* (Nextclade) + S:R408S, S:A27S
Substitutions in the background of XBB.1.16:
S:A27S
S:R408S

Additional mutations and its month wise frequency in India:
![Month_wise_mutations_calGISAID](https://user-images.githubusercontent.com/130817449/232185162-8515eb45-7197-4369-b4b7-33dd3fb8a2ea.png)

Evidence:
![XBB 1 16+S_R408S](https://user-images.githubusercontent.com/130817449/232186770-031159dd-9d52-4242-99d1-92db28dd45f5.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AR408S%2CS%3AA27S&nextcladePangoLineage=xbb.1.16*&

Escape calculator:
![bloom-408](https://user-images.githubusercontent.com/130817449/232186977-734f31b1-a8e6-4315-8710-df31ec5b2c0c.png)
https://jbloomlab.github.io/SARS2_RBD_Ab_escape_maps/escape-calc/ 

Existing mutation spectrum in the spike gene of XBB.1.16:

![XBB 1 16+S_R408S](https://user-images.githubusercontent.com/130817449/232193811-616ec2f8-93b8-47fc-9d09-a0ef807c805d.png)

https://outbreak.info/compare-lineages?pango=XBB.1.16&gene=S&threshold=75&nthresh=1&dark=false

Identified genomes:

<details>

EPI_ISL_17182905
EPI_ISL_17182925
EPI_ISL_17182930
EPI_ISL_17182931
EPI_ISL_17182934
EPI_ISL_17182949
EPI_ISL_17206426
EPI_ISL_17206435
EPI_ISL_17223627
EPI_ISL_17229374
EPI_ISL_17242420
EPI_ISL_17242422
EPI_ISL_17242423
EPI_ISL_17242424
EPI_ISL_17242438
EPI_ISL_17242439
EPI_ISL_17242440
EPI_ISL_17242441
EPI_ISL_17242442
EPI_ISL_17242443
EPI_ISL_17242445
EPI_ISL_17242446
EPI_ISL_17242447
EPI_ISL_17242448
EPI_ISL_17242450
EPI_ISL_17242451
EPI_ISL_17242452
EPI_ISL_17242453
EPI_ISL_17242458
EPI_ISL_17242473
EPI_ISL_17242479
EPI_ISL_17242480
EPI_ISL_17242497
EPI_ISL_17242503
EPI_ISL_17268903
EPI_ISL_17268904
EPI_ISL_17268909
EPI_ISL_17268910
EPI_ISL_17268916
EPI_ISL_17268917
EPI_ISL_17268925
EPI_ISL_17268929
EPI_ISL_17268930
EPI_ISL_17268945
EPI_ISL_17268956
EPI_ISL_17268957
EPI_ISL_17268958
EPI_ISL_17293132
EPI_ISL_17293133
EPI_ISL_17293134
EPI_ISL_17293136
EPI_ISL_17293137
EPI_ISL_17293138
EPI_ISL_17293140
EPI_ISL_17293141
EPI_ISL_17293142
EPI_ISL_17293146
EPI_ISL_17293148
EPI_ISL_17293152
EPI_ISL_17293153
EPI_ISL_17293157
EPI_ISL_17293159
EPI_ISL_17293161
EPI_ISL_17293162
EPI_ISL_17293163
EPI_ISL_17293169
EPI_ISL_17293171
EPI_ISL_17293173
EPI_ISL_17293174
EPI_ISL_17293177
EPI_ISL_17293178
EPI_ISL_17293181
EPI_ISL_17293184
EPI_ISL_17293185
EPI_ISL_17293186
EPI_ISL_17293187
EPI_ISL_17293189
EPI_ISL_17293190
EPI_ISL_17293193
EPI_ISL_17293195
EPI_ISL_17293196
EPI_ISL_17293197
EPI_ISL_17293198
EPI_ISL_17293203
EPI_ISL_17293219
EPI_ISL_17300662
EPI_ISL_17300782
EPI_ISL_17300783
EPI_ISL_17300785
EPI_ISL_17300792
EPI_ISL_17300795
EPI_ISL_17300796
EPI_ISL_17300798
EPI_ISL_17300801
EPI_ISL_17300821
EPI_ISL_17300827
EPI_ISL_17300834
EPI_ISL_17300836
EPI_ISL_17300837
EPI_ISL_17300851
EPI_ISL_17300858
EPI_ISL_17300860
EPI_ISL_17300862
EPI_ISL_17326864
EPI_ISL_17349533
EPI_ISL_17349539
EPI_ISL_17349543
EPI_ISL_17349561
EPI_ISL_17349588
EPI_ISL_17359471
EPI_ISL_17359472
EPI_ISL_17359476
EPI_ISL_17359485
EPI_ISL_17359490
EPI_ISL_17359492
EPI_ISL_17359508
EPI_ISL_17359510
EPI_ISL_17359526
EPI_ISL_17359532
EPI_ISL_17359534
EPI_ISL_17359542
EPI_ISL_17359547
EPI_ISL_17359548
EPI_ISL_17359549
EPI_ISL_17359550
EPI_ISL_17359553
EPI_ISL_17359554
EPI_ISL_17359555
EPI_ISL_17359556
EPI_ISL_17359557
EPI_ISL_17359558
EPI_ISL_17359559
EPI_ISL_17359560
EPI_ISL_17391177
EPI_ISL_17391186
EPI_ISL_17391188
EPI_ISL_17391189
EPI_ISL_17391191
EPI_ISL_17391192
EPI_ISL_17391193
EPI_ISL_17391206
EPI_ISL_17391207
EPI_ISL_17391374
EPI_ISL_17391380
EPI_ISL_17391381
EPI_ISL_17391403
EPI_ISL_17403724
EPI_ISL_17403726
EPI_ISL_17403727
EPI_ISL_17403728
EPI_ISL_17403731
EPI_ISL_17403734
EPI_ISL_17403736
EPI_ISL_17403737
EPI_ISL_17403740
EPI_ISL_17403744
EPI_ISL_17403752
EPI_ISL_17403753
EPI_ISL_17403754
EPI_ISL_17403762
EPI_ISL_17403765
EPI_ISL_17403767
EPI_ISL_17403768
EPI_ISL_17403769
EPI_ISL_17403770
EPI_ISL_17403773
EPI_ISL_17403774
EPI_ISL_17403778
EPI_ISL_17403779
EPI_ISL_17403780
EPI_ISL_17403781
EPI_ISL_17403785
EPI_ISL_17403788
EPI_ISL_17445676
EPI_ISL_17445677
EPI_ISL_17445678
EPI_ISL_17445680
EPI_ISL_17445684
EPI_ISL_17445685
EPI_ISL_17445686
EPI_ISL_17445687
EPI_ISL_17445690
EPI_ISL_17445691
EPI_ISL_17445695
EPI_ISL_17445699
EPI_ISL_17445700
EPI_ISL_17445702
EPI_ISL_17445703
EPI_ISL_17445706
EPI_ISL_17445707
EPI_ISL_17445709
EPI_ISL_17445727
EPI_ISL_17445728
EPI_ISL_17445733
EPI_ISL_17445736
EPI_ISL_17445737
EPI_ISL_17445739
EPI_ISL_17445740
EPI_ISL_17445741
EPI_ISL_17445744
EPI_ISL_17445747
EPI_ISL_17445762
EPI_ISL_17445763
EPI_ISL_17445766
EPI_ISL_17445770
EPI_ISL_17445774
EPI_ISL_17445779
EPI_ISL_17445782
EPI_ISL_17445786
EPI_ISL_17445790
EPI_ISL_17445793
EPI_ISL_17445798
EPI_ISL_17445800
EPI_ISL_17445802
EPI_ISL_17445804
EPI_ISL_17445806
EPI_ISL_17445814
EPI_ISL_17445815
EPI_ISL_17445816
EPI_ISL_17445837
EPI_ISL_17445841
EPI_ISL_17445842
EPI_ISL_17445845
EPI_ISL_17445846
EPI_ISL_17445849
EPI_ISL_17445850
EPI_ISL_17445854
EPI_ISL_17445855
EPI_ISL_17445857
EPI_ISL_17445858
EPI_ISL_17445859
EPI_ISL_17445860
EPI_ISL_17445861
EPI_ISL_17445862
EPI_ISL_17445863
EPI_ISL_17445864
EPI_ISL_17445865
EPI_ISL_17445866
EPI_ISL_17445867
EPI_ISL_17445868
EPI_ISL_17445869
EPI_ISL_17445870
EPI_ISL_17445871
EPI_ISL_17445873
EPI_ISL_17447210
EPI_ISL_17447215
EPI_ISL_17447216
EPI_ISL_17447217
EPI_ISL_17447219
EPI_ISL_17447222
EPI_ISL_17447223
EPI_ISL_17447225
EPI_ISL_17447227
EPI_ISL_17447229
EPI_ISL_17447230
EPI_ISL_17447233
EPI_ISL_17447236
EPI_ISL_17447240
EPI_ISL_17447249
EPI_ISL_17447252
EPI_ISL_17447253
EPI_ISL_17447255
EPI_ISL_17447256
EPI_ISL_17447259
EPI_ISL_17447268
EPI_ISL_17447271
EPI_ISL_17447279
EPI_ISL_17447280
EPI_ISL_17447287
EPI_ISL_17447288
EPI_ISL_17447289
EPI_ISL_17447298
EPI_ISL_17447303
EPI_ISL_17447312
EPI_ISL_17447316
EPI_ISL_17447328
EPI_ISL_17447332
EPI_ISL_17447336
EPI_ISL_17447341
EPI_ISL_17447357
EPI_ISL_17447370
EPI_ISL_17447371
EPI_ISL_17447372
EPI_ISL_17447388
EPI_ISL_17447390
EPI_ISL_17447391
EPI_ISL_17447399
EPI_ISL_17447400
EPI_ISL_17447401
EPI_ISL_17447402
EPI_ISL_17447404
EPI_ISL_17447406
EPI_ISL_17447409
EPI_ISL_17447410
EPI_ISL_17464043
EPI_ISL_17464044
EPI_ISL_17464046
EPI_ISL_17466156
EPI_ISL_17466157
EPI_ISL_17466158
EPI_ISL_17466159
EPI_ISL_17466160
EPI_ISL_17466161
EPI_ISL_17466162
EPI_ISL_17466164
EPI_ISL_17466165
EPI_ISL_17466166
EPI_ISL_17466168
EPI_ISL_17466169
EPI_ISL_17466170
EPI_ISL_17466171
EPI_ISL_17466172
EPI_ISL_17466173
EPI_ISL_17466174
EPI_ISL_17466175
EPI_ISL_17466176
EPI_ISL_17466177
EPI_ISL_17466178
EPI_ISL_17466179
EPI_ISL_17466374
EPI_ISL_17466375
EPI_ISL_17466376
EPI_ISL_17466377
EPI_ISL_17466381
EPI_ISL_17466382
EPI_ISL_17466383
EPI_ISL_17466384
EPI_ISL_17466385
EPI_ISL_17466386
EPI_ISL_17466387
EPI_ISL_17466388
EPI_ISL_17466389
EPI_ISL_17466390
EPI_ISL_17466392
EPI_ISL_17466393
EPI_ISL_17466394
EPI_ISL_17466396
EPI_ISL_17466397
EPI_ISL_17466898
EPI_ISL_17466902
EPI_ISL_17466906
EPI_ISL_17466909
EPI_ISL_17466910
EPI_ISL_17466913
EPI_ISL_17466915
EPI_ISL_17466916
EPI_ISL_17466917
EPI_ISL_17466921
EPI_ISL_17466927
EPI_ISL_17466928
EPI_ISL_17466931
EPI_ISL_17466961
EPI_ISL_17466964
EPI_ISL_17466976
EPI_ISL_17466978
EPI_ISL_17466986
EPI_ISL_17466991
EPI_ISL_17466996
EPI_ISL_17467004
EPI_ISL_17467023
EPI_ISL_17467033
EPI_ISL_17467034
EPI_ISL_17467038
EPI_ISL_17467047
EPI_ISL_17467051
EPI_ISL_17467057
EPI_ISL_17467058
EPI_ISL_17467067
EPI_ISL_17467098
EPI_ISL_17467100
EPI_ISL_17467109
EPI_ISL_17467114
EPI_ISL_17467115
EPI_ISL_17467118
EPI_ISL_17467119
EPI_ISL_17467122
EPI_ISL_17467124
EPI_ISL_17467125
EPI_ISL_17467131
EPI_ISL_17467136
EPI_ISL_17467139
EPI_ISL_17467146
EPI_ISL_17467148
EPI_ISL_17467154
EPI_ISL_17467157
EPI_ISL_17467184
EPI_ISL_17467196
EPI_ISL_17467197
EPI_ISL_17467208
EPI_ISL_17467218
EPI_ISL_17467228
EPI_ISL_17467240
EPI_ISL_17467257
EPI_ISL_17467278
EPI_ISL_17467293
EPI_ISL_17467300
EPI_ISL_17467305
EPI_ISL_17467308
EPI_ISL_17467312
EPI_ISL_17467314
EPI_ISL_17467316
EPI_ISL_17467336
EPI_ISL_17467344
EPI_ISL_17467352
EPI_ISL_17467358
EPI_ISL_17467363
EPI_ISL_17467364
EPI_ISL_17467369
EPI_ISL_17467373
EPI_ISL_17467377
EPI_ISL_17467378
EPI_ISL_17467380
EPI_ISL_17467381
EPI_ISL_17467386
EPI_ISL_17467387

</details>

Mutation map image source: https://covdb.stanford.edu/

**Comment by aviczhl2** [comment]
A27S and R408S are defining mutations for XBB.1.16.

https://nextstrain.org/staging/nextclade/sars-cov-2/?label=clade:22F&s=XBB.1.16

**Comment by aviczhl2** [comment]
<img width="999" alt="Screen Shot 2023-04-15 at 14 07 01" src="https://user-images.githubusercontent.com/10445944/232188595-0cc2eac7-ed40-42cd-8b72-74e1ff0201de.png">

Very few are having S:27A and 408R...

**Comment by aviczhl2** [comment]
However usher seems to put every XBB.1.16 with S:27A. 
Is it a bug? @AngieHinrichs 
<img width="1341" alt="Screen Shot 2023-04-15 at 14 09 08" src="https://user-images.githubusercontent.com/10445944/232189141-ab78f855-130d-449b-9502-21c73f5cab62.png">

**Comment by AngieHinrichs** [comment]
It is because of [branch-specific masking](https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/utils/otto/sarscov2phylo/branchSpecificMask.yml).  The BA.2 branch (which BTW has BA.4 and BA.5 as descendants) has several ranges including 21633-21641 masked (after sequences are added to the tree; branch-specific masking doesn't happen when sequences are uploaded to the web interface) because assembly errors often make false substitutions in the deleted regions.

Since XBB's parents are both BA.2 sublineages (BJ.1==BA.2.10.1.1 and BM.1.1.1==BA.2.75.3.1.1.1), I think XBB should have the BA.2 deletions, but I have not looked at the sequences.

**Comment by corneliusroemer** [comment]
408S is a common reversion to reference artefact
