### ISSUE TITLE
XBB.2.3.5 sublineage with Orf1a:L3829F spreading in Goa, India (7 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1895]
While rapidly reaching 50 sequences worlwide and being intercepted by Austrian,Washington, South Korea surveillance systems it is still not clear if XBB.2.3.5 is just prevalent in some undersampled area or instead it is very fast.

Here i want to propose to monitor the usual Orf1a:L3829F sublineage that already popped up in XBB.2.3.5 and seems spreading in Goa.

Defining mutations:
XBB.2.3.5 >>> C4084T, Orf1:L3829F (C11750T), C25782T

Gisaid query: C4084T, C11750T, C25782T, C18570T finds 6 

Sequences:  7 (India)
EPI_ISL_17445777-17445778, EPI_ISL_17445801, EPI_ISL_17445805,
EPI_ISL_17445808, EPI_ISL_17445818, EPI_ISL_17445821,

Tree:
<img width="1165" alt="Screenshot 2023-04-15 alle 12 54 01" src="https://user-images.githubusercontent.com/87669813/232209691-8a239bf3-4b88-4c0f-bd50-427743c2e138.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9584_a7f110.json?c=gt-ORF1ab_3829&label=id:node_6032890

**Comment by corneliusroemer** [comment]
Very small and no prior reason why this should be much different from parent. Ping me if this reaches 50 sequences for another look.
