### ISSUE TITLE
XBB.1.9.3 Sublineage with S:Y453F (22 seq, May 2)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1897]
### **Description**
**Sub-lineage of:** XBB.1.9.3
**Earliest sequence:** 2023-2-20, Mexico — EPI_ISL_17170298
**Most recent sequence:** 2023-4-5, USA, New York — EPI_ISL_17474787
**Countries circulating:** USA (5—with 2 from UK travelers), Mexico (1)
**Number of Sequences:** 6
**GISAID Nucleotide Query:** A22920T, T28297C, -A28447G
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.9* & C6286T & A22920T
**Substitutions on top of XBB.1.9.3:**
**Spike:** Y453F
**Nucleotide:** C6286T, A22920T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.9.3_Y453F_subtreeAuspice1_genome_255d1_b31dd0.json 
 
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/33738461/232258456-a9019684-abd8-4a1e-a164-9f66d7f56f3a.png">

**Evidence**
XBB* lineages that still have S:F486S, like this one, are hanging by a thread, and acquiring the massively ACE2-affinity-increasing mutation S:Y453F seems to be their last gambit. This sublineage might have an edge on the other XBB + F486S + Y453F lineages because it has ORF9b:I5T, which has proven its mettle, primarily by giving XBB.1.9.1 and XBB.1.9.2 a decisive growth advantage over XBB.1.5. I do not think it will compete against XBB.1.16, but it already seems geographically widespread, with sequences from Mexico, the Southwest US, the Northeast US, and two travel sequences from the UK.

<img width="945" alt="image" src="https://user-images.githubusercontent.com/33738461/232258509-f0412cad-93e4-4f77-91fd-3054408b984b.png">
 
The most recent sequence was collected on April 5 from New York and has S:G485D. Despite lacking coverage in over 20% of its genome, one of the two UK traveler sequences has four additional ORF1ab mutations—ORF1a:E1341D (NSP3_E523D), ORF1a: P1472L (NSP3_P654L), ORF1b:A37V (NSP12_A46V), and ORF1b:Q2400K (NSP16_Q3K).
 
The earliest sequence here by a margin of four weeks is from Mexico and the second sequence from Texas, so it seems likely this sublineage originated in Central America, where sequencing has been extremely thin in recent months. Surprisingly, two of the six sequences were detected in the US in travelers from the UK. Given the very good surveillance in the UK, this seems surprising. Perhaps the UK was an intermediate stop in a flight from another country?
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17170298, EPI_ISL_17384105, EPI_ISL_17428447, EPI_ISL_17428546, EPI_ISL_17428650, EPI_ISL_17474787
</details>

**Comment by corneliusroemer** [comment]
We already have plenty of 453F lineages, some even with 478, so I don't think this is very urgent (also being from well-sampled area). Ping me once this reaches something like 40 sequences.

**Comment by ryhisner** [comment]
Now at 21 sequences after an upload from Mexico, which seems to be the primary location of this one (perhaps along with nearby Central American countries who do ~zero sequencing).
