### ISSUE TITLE
DY.1 with N1/N2 PCR-test escaping mutations(C28311T,A28330G,C29200T) together with lots of orf1ab mutations emerging in Shanghai (40 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1899]
I noticed that a branch of DY.1 shows quite high prevalence in Shanghai's recent sequences of 3.10-4.10(21/311). Interestingly it has the PCR-test escaping mutation C29200T (on top of the BA.5.2's C28311T and A28330G.)

sub-lineage of: DY.1
mutations on top of DY.1: C6618T,C9611T(orf1a:L3116F), C20759T(orf1b:A2431V), C2388T(orf1a:T708I),G11417T(orf1a:V3718F), T20028C,C29200T
GISAID query: T20028C,C29200T,G11417T
No. of seqs: 21 (all in Shanghai)

First Seq: C_AA004803(2023.3.12)
Latest Seq: C_AA009519(2023.4.3) 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_36d49_be12c0.json?c=gt-nuc_29200&label=id:node_8640454)

<img width="1383" alt="Screen Shot 2023-04-16 at 20 46 37" src="https://user-images.githubusercontent.com/10445944/232312720-7f758991-1a98-48e1-a614-4ea98239f566.png">

[this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9237068/), [this paper](https://www.cambridge.org/core/journals/infection-control-and-hospital-epidemiology/article/nosocomial-severe-acute-respiratory-coronavirus-virus-2-sarscov2-transmission-arising-from-a-case-of-ngene-dropout-on-reversetranscription-polymerase-chain-reaction-rtpcr-testing/283CA5594DE3E0341FBF40B10BFEBC8E)  
and [this paper](https://www.accesocovid.com/blog-posts-english/sars-cov-2-samples-may-escape-detection-because-of-a-single-point-mutation-in-the-n-gene) alongside with many other papers all reported some singlet with C29200T escaping PCR tests.

And recently a Japanese research [here](https://www.cureus.com/articles/137317-stealth-omicron-a-novel-sars-cov-2-variant-that-is-insensitive-to-rt-qpcr-using-the-n1-and-n2-primer-probes) identifies a singlet Japanese BF.5 with PCR-test escaping sites of C28311T, A28330G and C29200T. 

According to this paper, C28311T and A28330G are both in most BA.5.2*, which makes PCR tests less sensitive, while with C29200T added, it can fully escape PCR tests targeting N1 and N2.  
<img width="900" alt="Screen Shot 2023-04-16 at 20 54 39" src="https://user-images.githubusercontent.com/10445944/232312857-daeba1e3-396b-4cd2-8258-d04170f285a2.png">

BA.5.2* with C29200T also has some prevalence(1-2% at peak) during last year's BA.5 wave in Japan and Canada, but no specified lineage was designated after it though.

**Comment by AnonymousUserUse** [comment]
Are there any overviews of the targets for commonly used PCR tests?

**Comment by AngieHinrichs** [comment]
> Are there any overviews of the targets for commonly used PCR tests?

The UCSC Genome Browser has a track with primers for several kits.  Here is a session link showing the N gene's primers:

https://genome.ucsc.edu/s/AngieHinrichs/N_primers

**Comment by thuchengyun21** [comment]
I remember China tests both N and orf1ab genes simultaneously to confirm a case; I might be wrong, though.

**Comment by aviczhl2** [comment]
3 more seqs from Shanghai.

**Comment by corneliusroemer** [comment]
Still small and only Shanghai and DY.1 are unlikely to be able to compete with global variants like XBB.1.16

**Comment by aviczhl2** [comment]
10/613 in today's Shanghai batch, still taking some share. Decaying but much more robust than other BA.5*.
