### ISSUE TITLE
Various branches of XBB.1.16 and XBB.1.16.1 with S:Q146K (93 seqs, 8 countries and 23 seqs, 8 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1900]
1:sublineage of: XBB.1.16
Mutations on top of XBB.1.16:C21998A (S:146K)
GISAID_query: T12730A, T28297C, A28447G,C21998A,-C23202T
No. of seqs: 74 (Australia 4 Canada 3 Singapore 3(1 from Thailand) USA 7 China 1 India 56)
First seq: EPI_ISL_17078571(India) 2023-2-26
Latest seq: C_AA009477(China) 2023-4-4
seqs:
C_AA009477,
EPI_ISL_17078571, EPI_ISL_17242447, EPI_ISL_17242450-17242451,
EPI_ISL_17242847, EPI_ISL_17266532, EPI_ISL_17269871,
EPI_ISL_17269879, EPI_ISL_17269895, EPI_ISL_17269911,
EPI_ISL_17269976, EPI_ISL_17286653, EPI_ISL_17293200,
EPI_ISL_17308481, EPI_ISL_17308504, EPI_ISL_17326082,
EPI_ISL_17326105, EPI_ISL_17326121, EPI_ISL_17326139,
EPI_ISL_17326162, EPI_ISL_17326171, EPI_ISL_17326182,
EPI_ISL_17326185, EPI_ISL_17326213, EPI_ISL_17326220,
EPI_ISL_17326232, EPI_ISL_17326273, EPI_ISL_17326300,
EPI_ISL_17326302, EPI_ISL_17326307, EPI_ISL_17347052,
EPI_ISL_17358975, EPI_ISL_17372514, EPI_ISL_17385827,
EPI_ISL_17395458, EPI_ISL_17408841, EPI_ISL_17409079,
EPI_ISL_17412930, EPI_ISL_17427668, EPI_ISL_17427716-17427717,
EPI_ISL_17427719, EPI_ISL_17427779, EPI_ISL_17427789,
EPI_ISL_17427864, EPI_ISL_17427898, EPI_ISL_17427924,
EPI_ISL_17428049, EPI_ISL_17428054, EPI_ISL_17428074,
EPI_ISL_17428108, EPI_ISL_17428126, EPI_ISL_17428158,
EPI_ISL_17428178, EPI_ISL_17428468, EPI_ISL_17428484,
EPI_ISL_17428486, EPI_ISL_17429774, EPI_ISL_17431995,
EPI_ISL_17432140, EPI_ISL_17445800, EPI_ISL_17447357,
EPI_ISL_17464037, EPI_ISL_17466949, EPI_ISL_17467005-17467006,
EPI_ISL_17467070, EPI_ISL_17467193, EPI_ISL_17467210,
EPI_ISL_17467222, EPI_ISL_17467304, EPI_ISL_17469146,
EPI_ISL_17477456

2:sublineage of: XBB.1.16.1
Mutations on top of XBB.1.16.1:C21998A (S:146K)
GISAID_query: T12730A, T28297C, A28447G,C21998A,C23202T
No. of seqs: 19 (Australia 2 Canada 1 UK 2 Singapore 1  India 13)

First seq: EPI_ISL_173595031(India) 2023-3-9
Latest seq: EPI_ISL_17480326(Australia) 2023-4-4
seqs:
EPI_ISL_17266291, EPI_ISL_17269967, EPI_ISL_17295565,
EPI_ISL_17300823, EPI_ISL_17326098, EPI_ISL_17326111,
EPI_ISL_17326147, EPI_ISL_17359493, EPI_ISL_17359503,
EPI_ISL_17427680, EPI_ISL_17427761, EPI_ISL_17432111,
EPI_ISL_17463987, EPI_ISL_17464035, EPI_ISL_17464109,
EPI_ISL_17467172, EPI_ISL_17467190, EPI_ISL_17470997,
EPI_ISL_17480326

S:146K is popping up in so many XBB.1.16 branches now that I cannot figure out a proper GISAID query to query only the main branch and exclude all other branches with singlet S:146K popping up. Even if I can it cannot adapt to future when more branches having S:146K popping up. 

Here I simply offer a general GISAID query for XBB.1.16+S:146K and XBB.1.16.1+S:146K and list branches with >=2 seqs.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8efb_c39990.json?branchLabel=Spike%20mutations&c=country&gt=S.146K)

<img width="1383" alt="Screen Shot 2023-04-17 at 02 26 45" src="https://user-images.githubusercontent.com/10445944/232334865-daafddb9-b70c-4072-a371-f2c7e8617d8b.png">

Branch 1.1(57 seqs):XBB.1.16+S:146K
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8efb_c39990.json?branchLabel=Spike%20mutations&c=country&gt=S.146K&label=id:node_5816798)
<img width="1371" alt="Screen Shot 2023-04-17 at 02 45 23" src="https://user-images.githubusercontent.com/10445944/232334838-efb27509-1a93-4adb-901b-8c1e8d50fb7b.png">

 Branch 1.2(9 seqs) XBB.1.16+C22414T+S:146K
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8efb_c39990.json?branchLabel=Spike%20mutations&c=country)
<img width="1398" alt="Screen Shot 2023-04-17 at 02 47 01" src="https://user-images.githubusercontent.com/10445944/232334964-1893da5e-8a28-481f-9124-433030f028ee.png">

There are also some singlets on other branches or on artefact reversion branches. 

Branch 2.1(5 seqs) XBB.1.16.1+S:146K
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8efb_c39990.json?branchLabel=Spike%20mutations&c=country&gt=S.146K&label=id:node_5816211)
<img width="1388" alt="Screen Shot 2023-04-17 at 02 52 12" src="https://user-images.githubusercontent.com/10445944/232335341-31d9bb2f-9ace-4d6f-b47b-e70371c44f88.png">

Branch 2.2(5 seqs) XBB.1.16.1+C20898T+S:146K
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8efb_c39990.json?branchLabel=Spike%20mutations&c=country&gt=S.146K)

<img width="1321" alt="Screen Shot 2023-04-17 at 02 55 09" src="https://user-images.githubusercontent.com/10445944/232335414-8f2035fb-c064-43f7-bd14-632e7f410e00.png">

branch 2.3(2 seqs) XBB.1.16.1+T21934C+S:146K (if we ignore those artefact reversions)
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8efb_c39990.json?branchLabel=Spike%20mutations&c=country&gt=S.146K&label=id:node_5815619)

<img width="1356" alt="Screen Shot 2023-04-17 at 02 56 05" src="https://user-images.githubusercontent.com/10445944/232335517-cad9a5f6-5a5f-41e4-b5d9-ca5f93622841.png">

Also there're some other singlets distributing on other branches.

**Comment by aviczhl2** [comment]
XBB.1.16.1+S:146K detected in USA too.

**Comment by aviczhl2** [comment]
XBB.1.16.1+S:146K detected in China and Japan.

**Comment by FedeGueli** [comment]
I m always a bit skeptical on 146K even if one of them was designated back in XBB.1.5

**Comment by corneliusroemer** [comment]
Agree with @FedeGueli - this has been a very jumpy/homoplasic mutation in XBB. It shouldn't be used as defining mutation because we don't know if it's real.

**Comment by AnonymousUserUse** [comment]
I do not think S:Q146K is too homoplasic to be used as a defining mutation of a lineage. In my view, a mutation with growth advantage may be designated even if it is very homoplasic as long as it doe not have to be masked.
