### ISSUE TITLE
XBB.2.3.3 with S:M153I in Europe and USA (79 seqs, 13 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1902]
sub-lineage of : XBB.2.3.3
Mutations on top of XBB.2.3.3: T24892C, S:M153I(G22021A)
GISAID query:  C1060T,G22021A ,T24892C (better query by FedeGueli)
No. of seqs: 11(4 USA 1 Netherlands 3 France 1 Ireland 1 UK) 
First seq: EPI_ISL_17096671 (Ireland) 2023-2-15
Latest seq: EPI_ISL_17481183 (Netherlands) 2023-4-7

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_357a1_c4c3e0.json?c=gt-S_153&label=id:node_6033685)
<img width="1314" alt="Screen Shot 2023-04-17 at 16 30 08" src="https://user-images.githubusercontent.com/10445944/232429540-b927c439-9d71-4ff9-8b52-3a270f2284b5.png">

**Comment by aviczhl2** [comment]
14 seqs and finally the first Indian seq.

**Comment by aviczhl2** [comment]
Close this as no more seqs.

**Comment by aviczhl2** [comment]
Reopen this as there seems to be a re-emergence and grows to 52 now.

**Comment by aviczhl2** [comment]
+1 China

**Comment by aviczhl2** [comment]
60, Israel

**Comment by FedeGueli** [comment]
When an issue become a bit older i suggest to repost the tree to check if it is still worth designating it. Sometime the shape of a tree and the evolution of branches (not just mutations but also exportations for example: exported to Canada starting then to circulate there) count a lot to designate something.
![Schermata 2023-07-25 alle 12 57 04](https://github.com/cov-lineages/pango-designation/assets/87669813/358bc918-1ce3-43fb-9168-628bda22a93b)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_336e4_faa420.json?label=id:node_7106797


Said that i think the query now gets one sequence belonging to GJ.1.2
![Schermata 2023-07-25 alle 12 58 17](https://github.com/cov-lineages/pango-designation/assets/87669813/15f263e0-0d90-489d-ae80-e2d24af4b8a1)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_336e4_faa420.json?label=id:node_7107340

i suggest to add -G16405A at your query or to use **C1060T,G22021A ,T24892C**, that strikingly finds 61!

**Comment by aviczhl2** [comment]
78, Spain

**Comment by FedeGueli** [comment]
Now it seems going quite well. Lets monitor it for a while more

**Comment by aviczhl2** [comment]
It gets designated as GJ.4

**Comment by FedeGueli** [comment]
cc @corneliusroemer pls add the milestone for automatic update.
