### ISSUE TITLE
XBB.1.16 sublineage with S:T678I - 100 seqs

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1903]
There is a quite well defined sublineage of XBB.1.16  with S:T678I,

**Defining mutation**s:
XBB.1.16>> S:T678I > (C23595T)

**Tree**:
<img width="1147" alt="Screenshot 2023-04-17 alle 13 08 48" src="https://user-images.githubusercontent.com/87669813/232467461-5d22e4ea-8b46-4bca-a7cf-d8f2cf5ef5ed.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1b31f_d25b90.json?c=gt-S_678&label=id:node_5832296

**Gisaid query**: T12730A, T28297C, A28447G,C23595T

**Sequences**:
EPI_ISL_17182927, EPI_ISL_17182943, EPI_ISL_17269961,
EPI_ISL_17278578, EPI_ISL_17280523, EPI_ISL_17280565,
EPI_ISL_17280692, EPI_ISL_17308511, EPI_ISL_17308526,
EPI_ISL_17324284, EPI_ISL_17353327, EPI_ISL_17358819,
EPI_ISL_17358932, EPI_ISL_17358960, EPI_ISL_17372263,
EPI_ISL_17372514, EPI_ISL_17388538, EPI_ISL_17393953,
EPI_ISL_17409249, EPI_ISL_17412569, EPI_ISL_17416227-17416228,
EPI_ISL_17428058, EPI_ISL_17428209, EPI_ISL_17428269,
EPI_ISL_17431888, EPI_ISL_17432096, EPI_ISL_17433208,
EPI_ISL_17434054, EPI_ISL_17445749, EPI_ISL_17464024,
EPI_ISL_17469958, EPI_ISL_17482315, EPI_ISL_17482521,

Countries:

<img width="278" alt="Screenshot 2023-04-17 alle 13 11 41" src="https://user-images.githubusercontent.com/87669813/232467984-228685d5-115f-4069-a6ad-704ead89b914.png">
To be noticed that the two Japanese sequences are from two different provinces and not labeled as travel related.

About S:T678I:

It was defining in a fast BA.5.1 sublineage that appeared to be competitive with Orf1b:T1050N
proposed in #1148 but never designated cause it was outcompeted by S:346T/S:n460K carrying lineages

and more importantly it was defining in BN.1.4.1 designated from: #1417 : as noticed that by @ryhisner S:T678I seems on the rise (slowly) : 
<img width="838" alt="Screenshot 2023-04-17 alle 13 22 40" src="https://user-images.githubusercontent.com/87669813/232470290-c1d870b1-4f7f-4643-9e9b-7c1459f5a446.png">

**Comment by aviczhl2** [comment]
It is also in yesterday's Chinese Genbase sequences.

**Comment by FedeGueli** [comment]
50 sequences as today

**Comment by corneliusroemer** [comment]
Not sure this is doing a lot, it's actually going down in India. Let's see what happens over next week or two and designate bigger branches first.

**Comment by FedeGueli** [comment]
73 sequences as today: last samples coming from Japan 3, Germany 2, Delhi 5, Tamil Nadu , South Korea, Finland 1 seq

**Comment by FedeGueli** [comment]
92 samples.
