### ISSUE TITLE
BA.4.1.9 with S:P337S, S:L938F, S:S1239T(6 seq. Spain)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1904]
Proposal for a sublineage of BA.4.1.9
Earliest sequence: 20.03.2023 (Spain)
Countries detected: Spain

Defining Mutations:
nuc	unique	A761G, C874A, T3508C, C5184A, C6336T, C6726T, C22571T, C29200T, G29212T, G25278C
nuc	homoplasies	C24374T
ORF1ab	unique	S166G, D203E, P1640H, S2024L, T2154I
S	unique	P337S, S1239T
S	homoplasies	L938F

![grafik](https://user-images.githubusercontent.com/102166254/232522481-b744be49-1017-4fbc-ba61-808613417d17.png)

![grafik](https://user-images.githubusercontent.com/102166254/232522736-d9ea8d15-3743-49da-bd38-b1536f60f4ac.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f58e_d5c050.json?c=gt-S_337

EPI_ISL_17482811
EPI_ISL_17245198
EPI_ISL_17482813
EPI_ISL_17276025
EPI_ISL_17482819
EPI_ISL_17482815

**Comment by ryhisner** [comment]
I think there are actually 12 sequences of this. The query 'Spike_V3G, Spike_H245D, -h245del' returns them all. 
EPI_ISL_17200348, EPI_ISL_17214693, EPI_ISL_17214805, EPI_ISL_17215676, EPI_ISL_17215686, EPI_ISL_17216822, EPI_ISL_17245198, EPI_ISL_17276025, EPI_ISL_17482811, EPI_ISL_17482813, EPI_ISL_17482815, EPI_ISL_17482819
https://raw.githubusercontent.com/ryhisner/jsons/main/BA.4.1.9_Chronic_Spain_12seq_subtreeAuspice1_genome_32d01_d655d0.json 
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/33738461/232537298-29b3d637-3bda-4dae-be47-f785fbbbf06d.png">


There is no metadata, but I assume these are all from the same patient. It has all the signatures of a chronic infection marked by intrahost competition of quasispecies, each probably occupying a different micro-environment in the host. There were ~24 nucleotide changes, including multiple reversions, during one 11-day period, from Feb 2 to Feb 13, represented on the Usher tree by a switch from the furthest sequence in the middle branch (AN-PMC-33316/2023, EPI_ISL_17216822) to the bottom part of the upper-right branch (AN-PMC-33449/2023, EPI_ISL_17276025), Included in that change was a move from ORF1a:P1640S changed to ORF1a:P1640H, which requires a reversion plus another nucleotide mutation. 

This was pretty clearly a change from one intrahost variant to another, possibly also involving some recombination. This change is clearly visible in this Nextclade nucleotide view of the 12 sequences, which are in chronological order. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33738461/232538044-95e3318c-5ce4-4bb0-9d24-fb613f43bcc8.png">

There's are also two alternations between the upper-right branch and the one below it, which are separated by 14 nucleotide differences.
• EPI_ISL_17245198 (AN-PMC-33449/2023), collected Feb 13, is on the lower branch.
• EPI_ISL_17276025 (AN-PMC-33841/2023), collected Feb 23, is on the upper branch.
• EPI_ISL_17482811 (AN-PMC-34369/2023), collected Mar 9, returns to the lower branch.
• EPI_ISL_17482813 (AN-PMC-34371/2023), collected Mar 13, flips back to the upper branch.
The remaining two sequences are also from the upper branch, which seems to have triumphed—perhaps temporarily—in the intrahost viral battle royale. 

This is also a classic example of the ease with which sotrovimab-resistant mutations evolve. At various times, this patient has had P337S, E340D, and/or K356T, all known sotrovimab-resistance mutations.

**Comment by agamedilab** [comment]
Hi metadata suggests two different sampling locations and orginating labs.

![grafik](https://user-images.githubusercontent.com/102166254/232553221-47c9c415-1ea9-415b-a3e7-fd2709d18b33.png)

**Comment by InfrPopGen** [comment]
Pangolin is currently seeing this as BA.4.1.6 (just a note for ref)

**Comment by AngieHinrichs** [comment]
> Pangolin is currently seeing this as BA.4.1.6 (just a note for ref)

pangolin with pangoLEARN mode calls it BA.4.1.6, but pangolin with the default usher mode gets BA.4.1.9 (at least for EPI_ISL_17482811 which I tried just now).  GISAID has been using pangoLEARN mode for most sequences, but pangoLEARN model files have not been updated since v1.18 due to lack of resources, and as of [pangolin v4.3](https://github.com/cov-lineages/pangolin/releases/tag/v4.3) (released today!) pangoLEARN mode is deprecated and usher mode will be used unless `--datadir` is given along with `--analysis-mode pangolearn`.

I will need to update my own scripts that have been running pangolin in pangoLEARN mode all this time!

**Comment by InfrPopGen** [comment]
Thank you @AngieHinrichs , sorry, yes it's Pangolin 4.1.6 only in certain contexts. I just put that note so that I (or any one else) wouldn't be surprised when cov-spectrum returns 0 sequences for this.

**Comment by agamedilab** [comment]
+2 sequences from different originating and submitting lab: 

hCoV-19/Spain/AN-PMC-35578/2023
hCoV-19/Spain/AN-PMC-35577/2023

**Comment by ryhisner** [comment]
I think the originating lab in this case is the same as most of the previous sequences, with the name expressed in a slightly different form. 
<img width="706" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/7001beaf-d0fa-4336-84f8-99234be928e2">

**Comment by DailyCovidCases** [comment]
Please close this issue
