### ISSUE TITLE
Potentially Interesting Lineage of XBB.1.5 with S:K356T, S:T572I, ORF3a:S92L circulating in North America

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#1907]
Sub Lineage of xbb.1.5
Additional Mutation on top of xbb.1.5: C1288T, C16332T C16989T ,C19263T , A22629C( S:K356T) ,C23277T(S:572I),C25667T (ORF3a:S92L)
Gisaid Inquiry: A22629C,C23277T,C25667T
Geographic Distribution: 3 Canada, 12 USA
Earliest sequence: hCoV-19/USA/CA-CDC-QDX47594794/2023|EPI_ISL_17248491|2023-03-01
Lastet sequence: hCoV-19/Canada/ON-PHL-23-21306/2023|EPI_ISL_17491043|2023-04-10
Sequence List:
EPI_ISL_17239814
EPI_ISL_17248491
EPI_ISL_17248966
EPI_ISL_17320926
EPI_ISL_17358776
EPI_ISL_17368834
EPI_ISL_17384215
EPI_ISL_17429782
EPI_ISL_17442602
EPI_ISL_17442762
EPI_ISL_17477554
EPI_ISL_17477563
EPI_ISL_17477906
EPI_ISL_17486385
EPI_ISL_17491043

usher link:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3aad9_da66f0.json?f_userOrOld=uploaded%20sample&label=id:node_3204397 
<img width="675" alt="32143B6C-29ED-45EE-81CE-B013342E2C08" src="https://user-images.githubusercontent.com/131021067/232607524-982cbf26-40a8-4bb6-ad14-15f20a283988.png">
I found this variant when just searching signals of S:356T within XBB*. According to many sources, 356 is one of the last few significant place that XBB* could get strong immune escape, and 356T have demonstrated to be quite successful in BN* variants, although they never present at large scales in other variants. 
As someone who is new to this field, I am not sure that if this variant is real, as there is little patient information about this gisaid inquiry. And the appearance of four silent C to T transitions makes this even less credible. So it could be that this variant is just an artifect.
However, I noticed that the combination K356T+572I in S protein was recorded before, in issue 1438, that later get designated as BM.1.1.4. BM.1.1.4 is quite similar to BM.1.1.1, one of the constitute variants during the recombination to form XBB. Thus, probably this combination could turn to be benign again in XBB.
Cov-spectrum indicate that a few more samples may lie in non-Gisaid databases, but I don't know how to inquiry those.

**Comment by krosa1910** [comment]
I think that within the tree, there are in total 21=15+6 samples. 15 are the gisaid samples that I made my inquiry on, while there are an additional 6 from public databases. That should be from Genbank because they fit with the description on cov-spectrum's open database.

**Comment by FedeGueli** [comment]
Good catch. It appears real Usher is quite clear.
All samples are quite recent so better tracking it to see if it shows any advantage.
S:K356T had circulated worlwide but was not widespread especially in western countries (while it reached good prevalences in Asia (S.Korea etc)

**Comment by krosa1910** [comment]
> Good catch. It appears real Usher is quite clear.
> All samples are quite recent so better tracking it to see if it shows any advantage.
> S:K356T had circulated worlwide but was not widespread especially in western countries (while it reached good prevalences in Asia (S.Korea etc)

I have conducted my own regression, and from my results I assume that the sequence has decent growth of about 52% each week (Technique is dividing variant within each two week period by the total gisaid sequence during the two weeks, then doing exponential regression). 
However, as evident in a lot of variants, initial outbreak usually lose its momentum gradually, so I am unsure about how reliable 52% each week could translate into later projections. 
Based on my assumptions of GISAID database that usually it submit 80% of the sequences after 3 weeks of sequences collected, I would project the sequence to reach about 50 at the end of April. Would see if my hypothesis is supported.
