### ISSUE TITLE
XBB.1.32 with S:Y453F and multiple AA substitutions likely circulating in Davao Philippines - 10 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1908]
While commenting a @ryhisner cool observation on Philippines "exceptionality" around the prolonged leading BA.2.3.20 era there  then i digged a bit and found an apparently interesting sublineages circulating there.

If i look for samples collected after 1st march 2023 and labeled as Philippines in Gisaid i found that 9 out of 92 are from XBB.1.32.
Out of these 9 only  one has not S:Y453F while 6 has S:Y453F and the 2 remaining have NNN but sharing with the S:Y453F an orf7a mutation: Orf7a:A50S.

So i decided to usher it and i found this is a clear sublineage of XBB.1.32 that emerged likely in Davao province and it is around 5% of samples collected in the region after 15 february.

Tree:
<img width="1183" alt="Screenshot 2023-04-17 alle 23 00 56" src="https://user-images.githubusercontent.com/87669813/232609813-c4ba7264-7128-45a3-98d9-b9b92de6ada8.png">
<img width="1136" alt="Screenshot 2023-04-17 alle 23 01 18" src="https://user-images.githubusercontent.com/87669813/232609892-3f4a8f54-d4cb-40d4-bd3a-a74749e0e246.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_29215_da73e0.json?c=userOrOld&label=id:node_5879801

Defining mutations:

**XBB.1.32** >>>**ORF1a:T2121I** (C6627T)(NSP3_T1303I) > T3676C, T14865C, **Orf7a:A50S** (G27541T) > **Orf1a:L642F** (C2189T)(NSP2_L462F), **ORF1b:L2497I** (C20956A)(NSP16_L100I) , **S:Y453F** (A22920T ) 

Gisaid query: NSP16_L100I,NSP3_T1303I,NSP2_L462F

Sequences:
EPI_ISL_17343831, EPI_ISL_17343863, EPI_ISL_17343901,
EPI_ISL_17343903-17343908, EPI_ISL_17343910

**Comment by FedeGueli** [comment]
still no new upload at all from Philippines, if it wont be present in the next one i will close it

**Comment by FedeGueli** [comment]
Low priority transferred to the new Pre Proposal Repo : https://github.com/sars-cov-2-variants/lineage-proposals/issues/3

**Comment by corneliusroemer** [comment]
A bunch of sequences were just uploaded from Thailand so I designated as XBB.1.32.1

The Thai sequences all had 450I as well, so that may become a sublineage if this turns out to circulate more widely.

**Comment by FedeGueli** [comment]
Thx @corneliusroemer !
