### ISSUE TITLE
New XBB.1 + Orf8:G8* sublineage with S:F486P spreading in India (Gujarat) and England 49 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1909]
While checking trees from Philippines i met this double headed XBB.1+486P lineage with two distinct branches one in Gujarat with S:Q613H and the other in England.
All sequences seems very recent so maybe worth keeping an eyes on it.

Defining mutations:
XBB.1> Orf8:G8*>C18744T>S:F486P (T23018C)
then
S:Q613H for the indian branch
and instead
for the english branch
Orf1a:V274L (G1085T),G12331A,ORF8:P93L (C28171T)

Tree:
<img width="1166" alt="Screenshot 2023-04-18 alle 00 06 27" src="https://user-images.githubusercontent.com/87669813/232621022-c024c743-5b56-4025-ab7a-33c8114c9cdb.png">
<img width="1111" alt="Screenshot 2023-04-18 alle 00 06 44" src="https://user-images.githubusercontent.com/87669813/232621072-75a2b43a-5dfe-4d14-8499-fd6699d8e2f6.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice13_genome_29215_da7400.json?c=gt-ORF8_8&label=id:node_5865699

Gisaid query:  -A1846G, -C2710T,C18744T,T23018C,G22317T,-C1613A,-A3139G,-T12730A,-G5720A,-T17124C,-A8001G,

Sequences: **26** 
<details>
<summary>Expand for EPI_ISLs</summary>
 EPI_ISL_17026904, EPI_ISL_17073060, EPI_ISL_17184360,
EPI_ISL_17231307, EPI_ISL_17231348, EPI_ISL_17232515,
EPI_ISL_17232523, EPI_ISL_17232525, EPI_ISL_17236453,
EPI_ISL_17237978, EPI_ISL_17242107, EPI_ISL_17245914,
EPI_ISL_17267176, EPI_ISL_17274016, EPI_ISL_17284451,
EPI_ISL_17287146, EPI_ISL_17318646, EPI_ISL_17318648,
EPI_ISL_17326247, EPI_ISL_17326262, EPI_ISL_17359928,
EPI_ISL_17428021, EPI_ISL_17428043, EPI_ISL_17428059,
EPI_ISL_17428190, EPI_ISL_17428239
</details>

On Usher tough there are more : **42** sequences:
<details>
<summary>Expand for more samples </summary>
India/GJ-GBRC11306/2023\|EPI_ISL_17427704\|2023-03-24
India/GJ-INSACOG-GBRC10779/2023\|EPI_ISL_17326247\|2023-03-18
India/MH-GMC-AUR-643729/2023\|EPI_ISL_17318648\|2023-03-16
India/MH-GMC-AUR-643722/2023\|EPI_ISL_17318646\|2023-03-16
USA/FL-CDC-QDX47772018/2023\|OQ684814.1\|2023-03-10
USA/FL-CDC-QDX47418383/2023\|OQ643518.1\|2023-02-28
India/GJ-GBRC11055/2023\|EPI_ISL_17428059\|2023-03-23
India/GJ-GBRC10970/2023\|EPI_ISL_17428021\|2023-03-21
India/MH-ICMR-NIV-231895/2023\|EPI_ISL_17359551\|2023-03-21
India/MH-NIV-231138/2023\|EPI_ISL_17073060\|2023-02-22
India/GJ-GBRC10952/2023\|EPI_ISL_17428190\|2023-03-20
India/GJ-INSACOG-GBRC10794/2023\|EPI_ISL_17326262\|2023-03-16
India/GJ-GBRC10957/2023\|EPI_ISL_17428043\|2023-03-21
India/GJ-GBRC11486/2023\|EPI_ISL_17428239\|2023-03-27
India/GJ-GBRC10364/2023\|EPI_ISL_17236453\|2023-03-06
England/QEUH-32705D40/2023\|OX457744.1\|2023-03-12
England/BRBR-326F50D2/2023\|OX452599.1\|2023-03-04
England/QEUH-326D821B/2023\|OX442027.1\|2023-02-14
England/PHEC-YYE1OW4/2023\|2023-03-27
England/PHEC-YYEKJRU/2023\|2023-03-01
England/PHEC-YYEWBZ9/2023\|2023-04-08
England/PHEC-YYEMXBT/2023\|2023-03-12
England/BRBR-3270039E/2023\|OX455002.1\|2023-03-09
England/BRBR-3270E785/2023\|OX462244.1\|2023-03-18
England/BRBR-32710814/2023\|2023-03-21
England/BRBR-32710814/2023\|OX462368.1\|2023-03-21
England/PHEC-YYEPS3I/2023\|2023-03-14
England/PHEC-YYEJH9M/2023\|2023-03-01
England/PHEC-YYEK8M8/2023\|2023-03-05
England/PHEC-YYEJ6QC/2023\|2023-02-27
England/PHEC-YYEJH7X/2023\|2023-03-01
England/PHEC-YYEJ7G7/2023\|2023-03-02
England/PHEC-YYEJ6TF/2023\|2023-02-28
England/PHEC-YYEKWJ6/2023\|2023-03-05
England/PHEC-YYEMR6B/2023\|2023-03-09
England/BRBR-326FFFCC/2023\|OX455468.1\|2023-03-10
England/BRBR-32706A39/2023\|OX457911.1\|2023-03-14
England/PHEC-YYEJ6EA/2023\|2023-02-27
England/PHEC-YYEJ7MU/2023\|2023-03-02
England/BRBR-327080F9/2023\|OX457723.1\|2023-03-14
England/BRBR-327116BF/2023\|2023-03-24
England/BRBR-32701B77/2023\|OX456069.1\|2023-03-13
</details>

EDITED in Gujarat its share seems hanging around 1% through March, but please keep in mind there is XBB.1.16 there already.

**Comment by Mydtlwn** [comment]
#1929

**Comment by FedeGueli** [comment]
49 sequences now on Usher:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c5f2_af0050.json?c=userOrOld&label=id:node_5881767
Interestingly the last samples from india got S:T478R
![Schermata 2023-04-28 alle 00 01 30](https://user-images.githubusercontent.com/87669813/235000809-959e05f5-97be-46be-a771-0d8041d17864.png)

**Comment by FedeGueli** [comment]
Growing very little notwithstanding the S:Q613H mutation. closing it fr the moment
