### ISSUE TITLE
New XBB.2.3 + nsp2_A357S + nsp3_T1004I

### ISSUE THREAD

**Issue by VirologiaHUCA** [cov-lineages/pango-designation#1911]
By VirologiaHUCA
Description
Sub-lineage of: XBB.2.3
Earliest sequence: 2023-02-27
Most recent sequence: 2023-03-13
Countries circulating: Spain (5 Asturias) 

Written description
In XBB.2.3 variants, 5 sequences has gained the following mutations (nsp2_A357S + nsp3_T1004I).  
Genomes
EPI_ISL_17096434, EPI_ISL_17233401, EPI_ISL_17233417, EPI_ISL_17233422, EPI_ISL_17299877

Evidence
![image](https://user-images.githubusercontent.com/105294581/232774758-873d7703-5479-4e85-b705-fb8a6dbfc26f.png)

**Comment by VirologiaHUCA** [comment]
Four new genomes (EPI_ISL_17359777, EPI_ISL_17521236, EPI_ISL_17521247, EPI_ISL_17521242) detected from 2023-03-20 to  2023-04-11 have also gained the mutations nsp2_A357S + nsp3_T1004I. Now, there are nine sequences to be included in this sub-lineage.

**Comment by VirologiaHUCA** [comment]
Twelve new genomes (EPI_ISL_17471124, EPI_ISL_17471132, EPI_ISL_17482103, EPI_ISL_17505459, EPI_ISL_17521230, EPI_ISL_17521889, EPI_ISL_17592267, EPI_ISL_17592268, EPI_ISL_17592276, EPI_ISL_17592277, EPI_ISL_17592283,
EPI_ISL_17592284) which were detected from 2023-03-16 to 2023-04-18 in Spain (9), Austria (1) and Japan (1) are also included in this group. 

![image](https://user-images.githubusercontent.com/105294581/235910256-f838f0ad-8f0b-4187-b3dc-ba17f04f4f95.png)

**Comment by corneliusroemer** [comment]
@VirologiaHUCA Please make the issue more similar to the other issues to make review easier:
1. Use ORF1ab instead of nsps
2. Add covSpectrum and GISAID queries (GISAID one is `nsp2_A357S, nsp3_T1004I` for example)
3. Add Usher tree links and screenshots
4. Add why you think this lineage is interesting: it was very small when you opened the issue, only 5 sequences

**Comment by VirologiaHUCA** [comment]
@corneliusroemer. Thanks for your comments

1. According to your suggestion, the mutations are  ORF1ab_A357S, ORF1ab_T1004I

2. Excuse me, could you explain you require in this point

3. This is the usher tree 
![image](https://user-images.githubusercontent.com/105294581/236449290-6bad8c41-98ab-41da-b61c-3c651728f380.png)

4. We agree with the fact that when the issue was opened, there was a low number of sequences. Nevertheless, the increase of this number suggests that the variant is active, not only in our region/country but in other countries.

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
Please close this issue
