### ISSUE TITLE
XBB.1.16 w/ s:Q613H (12 sequences, India)

### ISSUE THREAD

**Issue by BorisUitham** [cov-lineages/pango-designation#1917]
Defining mutation: spike_Q613H
Earliest sequence: 2023-03-18
Latest sequence: 2023-03-31
present in: gujarat (8), maharashtra (2), delhi (1), haryana (1)
covspectrum query: xbb.1.16, s:q613h

Due to bad sequencing with gaps i had a lot of trouble finding a simple gisaid query so at the moment its quite hacky with the exclusions. However, nextclade does recognize all of them as xbb.1.16. if anyone knows a better one that catches everything, please let me know.
GISAID query: spike_q613h, spike_e180v, -spike_l452r (AA) C2790T, -G5720A (NT)

Phylogenetic tree: The subtrees are very ugly due to bad sequences with gaps of missing mutations. I needed to use the downsampled global tree to get an overview, the top one has the best sequences. I couldn't really get a good screenshot that captured all the data properly, but i don't think this is what the actual tree looks like anyways. It includes a 417 reversion which I dont think is real.
![Screenshot_20230420-011349](https://user-images.githubusercontent.com/119106095/233219354-20daccf9-7265-4d8a-972d-ee85c8920ba3.png)

Growth advantage: There are only 5 sequences found via covspectrum so the calculated growth advantage is not accurate. However, since Q613H is a very convergent mutation, being very present in eg.1 which is a similar base to xbb.1.16, i believe this could add additional growth advantage on top of xbb.1.16. 12 sequences in first 13 days in india. 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A613h&nextcladePangoLineage=xbb.1.16*

Sequences:
EPI_ISL_17427733, EPI_ISL_17427788, EPI_ISL_17428133,
EPI_ISL_17445754, EPI_ISL_17464045, EPI_ISL_17497063,
EPI_ISL_17497068, EPI_ISL_17497187, EPI_ISL_17497192,
EPI_ISL_17497198, EPI_ISL_17500475, EPI_ISL_17508171,

**Comment by corneliusroemer** [comment]
Indian sequences often have lots of reversions, so need to wait for some international ones for confirmation/designation

**Comment by BorisUitham** [comment]
One month later, it does not look like the multiple convergent branches (46 sequences total) have much of an advantage. Closing this issue for now, but if anybody finds a xbb.1.16 613h branch that does have a lot of growth advantage, feel free to make a new issue
