### ISSUE TITLE
XBB.1.9.2 sublineages with S:F456L (61 sequences throughout asia, europe, n. america)

### ISSUE THREAD

**Issue by BorisUitham** [cov-lineages/pango-designation#1918]
Defining mutation: S:F456L
Earliest: 2023-02-17
Latest: 2023-04-11

Main lineage: 36 seqs
Secondary lineage: 14 seqs
Tertiary lineage: 6 seqs
Rest: 5 seqs

covspectrum query: xbb.1.9.2, s:f456l 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A456l&nextcladePangoLineage=xbb.1.9.2*&nextcladePangoLineage1=xbb.1.9.1&

GISAID query: spike_f456l, A27507C, A16878T
query main lineage: A27507C, T22930A, C9693T
query secondary lineage: A27507C, T22928C, C1684T
query tertiary lineage: A27507C, T22928C, C21998A
Phylogenetic tree:
![Screenshot_20230420-004644](https://user-images.githubusercontent.com/119106095/233216087-877d2509-7cae-46b5-939d-45046eb1d9b0.png)

It looks like usher gives two main lineages, with one branch being mostly israel. The main branch has orf1ab:a690v and orf1ab:a3143v. the israel branch has orf6:y49h. There is also a small dutch/german/french branch, but 146 is a bit of a dubious position so im unsure of its validity
the nuc mutation that led to f456l differs between the branches, main one is T22930A while secondary and tertiary are T22928C.

Growth advantage: F456L is a convergently growing mutation with a slight growth advantage, so I expect it to also add growth advantage on xbb.1.9.2. It already has a significant incidence in indonesia, and covspectrum calculates a growth advantage of 107% as of writing.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A456l&nextcladePangoLineage=xbb.1.9.2*&nextcladePangoLineage1=xbb.1.9.1&

Plugging it against the baseline of xbb.1.9.2 currently  gives it a growth advantage of 58% over that
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=xbb.1.9.2*&aaMutations1=s%3A456l&nextcladePangoLineage1=xbb.1.9.2*&analysisMode=CompareToBaseline&

Sequences:
EPI_ISL_17204637, EPI_ISL_17244403, EPI_ISL_17256318,
EPI_ISL_17269002, EPI_ISL_17269282, EPI_ISL_17298415,
EPI_ISL_17308406, EPI_ISL_17308775, EPI_ISL_17308780,
EPI_ISL_17308785, EPI_ISL_17344757, EPI_ISL_17349171,
EPI_ISL_17372765, EPI_ISL_17388641, EPI_ISL_17389268,
EPI_ISL_17389270, EPI_ISL_17393403, EPI_ISL_17408790,
EPI_ISL_17409143, EPI_ISL_17409239, EPI_ISL_17418267,
EPI_ISL_17422205, EPI_ISL_17428351, EPI_ISL_17432511,
EPI_ISL_17445205, EPI_ISL_17448558, EPI_ISL_17463187,
EPI_ISL_17465899, EPI_ISL_17468575, EPI_ISL_17469602,
EPI_ISL_17469700, EPI_ISL_17470035, EPI_ISL_17470513,
EPI_ISL_17471668, EPI_ISL_17472849, EPI_ISL_17474211,
EPI_ISL_17475323, EPI_ISL_17479956, EPI_ISL_17483735,
EPI_ISL_17483758, EPI_ISL_17483773, EPI_ISL_17483792,
EPI_ISL_17483821, EPI_ISL_17483838, EPI_ISL_17483857,
EPI_ISL_17483919, EPI_ISL_17483932, EPI_ISL_17483968,
EPI_ISL_17484004, EPI_ISL_17484007, EPI_ISL_17485080,
EPI_ISL_17486515, EPI_ISL_17495605, EPI_ISL_17496014,

**Comment by corneliusroemer** [comment]
Designated as EG.5

**Comment by FedeGueli** [comment]
One informative note found by @Krosa1910 is that EG.5 arrives at S:F456L from **T22930A** while the other designated lineages (FE.1/FD.1.1/XBB.1.5.10) got it from **T22928C**

**Comment by alurqu** [comment]
Which is the defining nucleotide mutation for EG.5? T22930A or via T22928C? Both are observed in XBB.1.9.2, and both result in S:F456L. See also Issue 1950 by @krosa1910 and referenced above by @FedeGueli.

**Comment by BorisUitham** [comment]
@alurqu: lineagesnotes defines eg.5 as S:F456L, ORF1a:A690V, ORF1a:A3143V. those orf1as are from the first lineage in my post, which is T22930A
