### ISSUE TITLE
BA.5.2.1 Saltation lineage, with 5 spike mutations (S:H245Y, R346T, L368I, K440R, A942T) and two reversions S:F486F,Orf9b:D16D (China , Liaoning/Guangdong 9 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1919]
Here i want to propose a first big saltation lineage emerging in China after discussing briefly with @ryhisner and @c19850727.

Looking at the basal sequences in the tree i suspect this could have been generated in a pre big wave chronic infection, in fct it descends from an old BA.5.2.1 branch with Orf6:P57L (that emerged likely in Africa) and had circulated back in [summer 2022 ]([url](https://cov-spectrum.org/explore/World/AllSamples/Y2022/variants?aaMutations=S%3AT747I%2Corf6%3AP57L&nextcladePangoLineage=BA.5.2.1*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&))defined by S:T747I mutation 
![Schermata 2023-04-20 alle 01 00 44](https://user-images.githubusercontent.com/87669813/233217646-ec75d864-2a1d-4f75-8fb6-29b1f82c1b85.png)
I found this saltation long branch looking for S:N440R mutation that lately is becoming a good marker of chronic infection derived lineages.

**Defining mutations**:
**BA.5.2.1** > T6979G > C26625T > ORF6:P57L (C27371T) > ORF1a:I616T (T2112C )> T6394C >S:T747I( C23802T) > ORF1a:P971L (C3177T) 
**(Start of the saltation)>> C1594T, ORF1a:N615K (C2110A), ORF1a:K1529R (A4851G), T6673C, C6968T, ORF1a:A2355G (C7329G), C8290T, A8992G , ORF1a:T4175I ( C12789T) ,ORF1b:G662S (G15451A), ORF1b:S2658F (C21440T), C22120T, S:H245Y (C22295T), S:R346T (G22599C),S:L368I (C22664A), S:N440R (A22881G), _REV S:F486F (T23018T)_ ,S:A942T (G24386A), E:V58I (G26416A), REV ORF6:L57P T27371C, REV G28330A, T29417C**** 

**Mutations** :
ORF1a :N615K, P971L, K1529R, A2355G ,T4175I  (**EDITED** first i missassigned to synonymous mutation A8992G a non existent ORF1a:2909V mutation thx @c19850727)
ORF1b:G662S, S2658F , 
S:H245Y R346T L368I, K440R, A942T 
E:V58I

**Reversions**: 
As @aviczhl2 , @ryhisner @c19850727 pointed to me all the 5 samples displays on Gisaid (but not the original chinese genbank ones)  the reversion  **S:F486F** **(EDITED)**
It has A28330A reverting BA.5.2 defining mutation: so it has also Orf9B:D16D ( **EDITED** Thx @silcn )
While it has also Orf6:P57P reverted from its own root Orf6:57L

**Convergence**:
Notably it has S:L368I and Orf1b:G662S as XBB*

**Tree**:
![Schermata 2023-04-20 alle 01 41 09](https://user-images.githubusercontent.com/87669813/233222369-a19e066a-65d7-4263-8ad7-e973fd5f160c.png)
![Schermata 2023-04-20 alle 01 42 16](https://user-images.githubusercontent.com/87669813/233222492-a0dc275a-008a-4503-91a0-307a707f1cda.png)

**Country**: China , all of them from Liaoning

**Samples**: 5 (with 4 different ages , all of them over 60)

**Sequences**:
EPI_ISL_17493027, EPI_ISL_17495186, EPI_ISL_17495358,
EPI_ISL_17495368-17495369

Gisaid query:C22664A,A22881G,C22120T (**EDITED**)  

Alternative Gisaid query: 2110A,A4851G

**Comment by aviczhl2** [comment]
There wasn't many patients before the big wave, however Liaoning is a province next to North Korea, where some virus is likely circulating and never any sequences from there.  

BTW ORF1a:A2909V is the defining mutation for BA.2.3.

**Comment by HynnSpylor** [comment]
great catch! S:K440R seems a little more frequent in China (some other BA.5.2*, including BF.7.14* seqs can observe it).

**Comment by silcn** [comment]
Worth noting given the recent attention on ORF9b mutations that the reversion G28330A is not silent, it encodes ORF9b:G16D.

**Comment by aviczhl2** [comment]
I don't know why usher gives it S:F486V,  looking at the original Genbase data, there's no S:F486V.
[genbase.2537](https://ngdc.cncb.ac.cn/ncov/genome/accession?q=C_AA002537.1#)

<img width="846" alt="Screen Shot 2023-04-20 at 21 04 37" src="https://user-images.githubusercontent.com/10445944/233375113-3f37a775-9da3-40ad-a84d-bb3ac249e322.png">

**Comment by thomasppeacock** [comment]
This looks really interesting - I'm just sticking it into monitoring for now due to the low numbers of sequences but if more pop up I think we should prioritise designating this.

**Comment by AngieHinrichs** [comment]
> I don't know why usher gives it S:F486V, looking at the original Genbase data, there's no S:F486V.

Again it's branch-specific masking -- all of BA.5 has the G23018T reversion masked because it often looked like a false reversion that would mess up the tree:

https://github.com/ucscGenomeBrowser/kent/blob/49029c6209ad86693a552fd4dd8e7a4a55d8777f/src/hg/utils/otto/sarscov2phylo/branchSpecificMask.yml#L99

**Comment by corneliusroemer** [comment]
Single province, some mutations could be artefacts, let's see if this pops up anywhere else

**Comment by FedeGueli** [comment]
No new sequence came out from China or elsewhere i  ll keep monitored prvtly

**Comment by FedeGueli** [comment]
Reopen to let @ryhisner do some observations on it.

**Comment by ryhisner** [comment]
Just wanted to add that there's a new sequence in this lineage that has the S:V486F reversion, which is becoming a convergent mutation in chronic-infection sequences lately. It also has two consecutive AA mutations in ORF1a with ORF1a:N615K, I616T.
![image](https://github.com/cov-lineages/pango-designation/assets/33738461/ce3ec49f-10a0-45e8-963c-55164e632d20)

**Comment by ryhisner** [comment]
New sequence from Guangdong popped up today—the first sequence from outside of Liaoning. Identical to the others except for one (supposed) synonymous nuc reversion (C22981T—likely a result of a slightly mistaken Usher-tree arrangement resulting from the failure to register the S:V486F reversion in several sequences), two new synonymous nuc mutations (C19854T, G28085A), and ORF1b:T1655I (C18431T). 
Collected April 24, which makes it the most recent sequence in this lineage. EPI_ISL_17697616

Zoomed-out and zoomed-in views of the current Usher tree below. 
<img width="1483" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/16805cfe-568c-4c7e-85e9-6895b6321d55">

**Comment by ryhisner** [comment]
Liaoning and Guangdong are not neighboring provinces. 
<img width="1372" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/464011ab-6c58-442d-9953-22de648c0de0">

**Comment by ryhisner** [comment]
Liaoning borders North Korea, so perhaps this lineage arose there. In epidemiological terms, North Korea is essentially an island. It seems possible that lineages could arise and circulate there for a long period of time before reaching other countries.
<img width="879" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/8353a700-4321-4a69-b5f3-0eef116f3d48">

**Comment by aviczhl2** [comment]
> I have checked the Metadata. The early 5 seqs are collected in Shenyang City, which is not at the border. If it arose in North Korea, some border cross in Jilin Province may also detect it

Bordering cities of Jilin and Liaoning have very few sequences uploaded to GISAID.

**Comment by FedeGueli** [comment]
Thx @ryhisner and everyone for keeping it monitored.

**Comment by FedeGueli** [comment]
EPI_ISL_17652380 is known to belong to this lineage. i found it looking for different things. just asking.

**Comment by FedeGueli** [comment]
![Schermata 2023-05-26 alle 22 54 35](https://github.com/cov-lineages/pango-designation/assets/87669813/57ac5de0-bf4d-4855-9aa6-856b0157705c)
the Guangdong sample clusters with this last discovered Liaoning one: with 

 C6224T (ORF1a:H1987Y) + T4579A

**Comment by Over-There-Is** [comment]
And the Guangdong sequence was detected by Shenzhen Customs, which means it is imported from somewhere out of China Mainland.

**Comment by Over-There-Is** [comment]
according to [GenBase](https://ngdc.cncb.ac.cn/genbase/search/gb/C_AA014901.1), EPI_ISL_17652380 is collected in Panjin.
![image](https://github.com/cov-lineages/pango-designation/assets/38100637/b8c3bae3-d3af-4585-b179-03b3c1c9263d)

**Comment by Over-There-Is** [comment]
I have checked the Metadata, the sequences uploaded between 04-01 to 04-12 are all tagged as collected in Shenyang, the Capital of Liaoning Province. 5 of the sequences in this lineage are collected then, and they are all actually from Panjin, which is a harbor city .

**Comment by HynnSpylor** [comment]
Panjin is a harbor city but not the China-DPRK border pass. The Chinese border cities (Dandong, Yanbian, etc.) circulated BA.2.3 lineage in Spring 2022, which is clearly from DPRK, is highly consisted with lineages in South Korea. So if it originated in DPRK, some seqs may also be found in South Korea.

**Comment by HynnSpylor** [comment]
Panjin is a harbor city but not the China-DPRK border pass. The Chinese border cities (Dandong, Yanbian, etc.) circulated BA.2.3 lineage in Spring 2022, which is clearly from DPRK, is highly consisted with lineages in South Korea. So if it originated in DPRK, some seqs may also be found in South Korea.

**Comment by aviczhl2** [comment]
> Although still so few, Yanbian and Tonghua actually have uploaded sequences more than this.

11 and 14 don't alter the conclusion that it is hard to detect anything. 

>  So if it originated in DPRK, some seqs may also be found in South Korea.

For obvious reasons, passing through NK-SK border is much stricter than NK-Chinese border. 

> The official stance of both the South and North Korean governments has been against the continuing balloon drops. However, the South Korean government has been hesitant to intervene in the launches by activists due to concerns about [freedom of expression](https://en.wikipedia.org/wiki/Freedom_of_expression).

Consider SK may fly propaganda balloons to NK, there's single-sided transmission that SK variants are more likely to go to NK but NK variants unlikely to go to SK.

**Comment by aviczhl2** [comment]
>  The Chinese border cities (Dandong, Yanbian, etc.) circulated BA.2.3 lineage in Spring 2022, which is clearly from DPRK, is highly consisted with lineages in South Korea. So if it originated in DPRK, some seqs may also be found in South Korea.

Dandong is a harbor city, the BA.2.3 may come from anywhere that have a sea trade route (Japan, SK directly, Taiwan, SE Asian countries etc.), and leaked to the society.  BA.2.3 was quite widespread at that time.

**Comment by FedeGueli** [comment]
2 more sequences of this one apparently from Liaoning.

**Comment by FedeGueli** [comment]
no sequence of any lineage uploaded from Liaoning. With the next upload we will se if this has died off as it seems.

**Comment by FedeGueli** [comment]
Closing this one, luckily.
