### ISSUE TITLE
XBB.1.16.2 sublineage with S:D178N (G22094A) (25 seqs in Canada)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1920]
Defining mutations: XBB.1.16>>G25429C (ORF3a:V13L) >C3042A (ORF1a:P926H)> C11962A>C8140T>G22094A(S:D178N)
GISAID query: Spike_E180V, Spike_D178N, T28297C, C8140T
Earliest seq: 2023-03-26 (Canada, EPI_ISL_17442164)
Most recent seq: 2023-04-10 (Canada, EPI_ISL_17491053)
Countries detected: Canada (25)
Usher Tree:
![QQ截图20230420091518](https://user-images.githubusercontent.com/121703496/233232692-b2163bf1-5da4-4daa-a394-78cfc4b40835.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_339e2_8fbe0.json

This sublineage is growing recently in Canada. Of course, the current growth advantage is uncertain (Cov-spectrum shows more than 500% to XBB.1.16), but the potential is worth monitoring. 

Genomes:
EPI_ISL_17442164, EPI_ISL_17442566, EPI_ISL_17442850, EPI_ISL_17442852, EPI_ISL_17442857-17442858, EPI_ISL_17442860-17442861,
EPI_ISL_17442869, EPI_ISL_17442881, EPI_ISL_17490801, EPI_ISL_17490807, EPI_ISL_17490811-17490812, EPI_ISL_17490825,
EPI_ISL_17490831, EPI_ISL_17490846, EPI_ISL_17490854, EPI_ISL_17491048, EPI_ISL_17491052-17491055, EPI_ISL_17491057, EPI_ISL_17491059

**Comment by FedeGueli** [comment]
@HynnSpylor there is a typo in  defining mutations
>>
>Defining mutations: XBB.1.16>>G25429C (ORF3a:V13L) >C3042A (ORF1a:P926H)> C11962A>C8140T>**G22094A(S:N178D)**
 
>>

**Comment by corneliusroemer** [comment]
Parent lineage is now XBB.1.16.2

**Comment by DailyCovidCases** [comment]
Please close this issue
