### ISSUE TITLE
BN.1.2 with Orf9b:I5V,Orf9b:G31V mostly in Taiwan (81 seqs, 11 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1923]
sub-lineage of: BN.1.2
mutations on top of BN.1.2: C16332T, A28296G(orf9b:I5V, N:N8S),G28375T(orf9b:G31V)
GISAID query: A28296G,G28375T
No. of seqs: 23( 3 Australia, 1 Indonesia, 2 Japan, 2 Jiangsu, 1 Malaysia, 1 Singapore(from Taiwan), 4 South Korea(1 from Thailand), 7 Taiwan, 2 USA)
First seq: 
EPI_ISL_16135415( South Korea from Thailand) 2022-11-23
Latest seq:
EPI_ISL_17505026(Jiangsu) 2023-4-3

Sequences:
EPI_ISL_16135415, EPI_ISL_16744381, EPI_ISL_16987143,
EPI_ISL_17013587, EPI_ISL_17013785, EPI_ISL_17015420,
EPI_ISL_17039330, EPI_ISL_17058118, EPI_ISL_17079912,
EPI_ISL_17164551, EPI_ISL_17168334, EPI_ISL_17168447,
EPI_ISL_17207418, EPI_ISL_17213322, EPI_ISL_17281712,
EPI_ISL_17294299, EPI_ISL_17295200, EPI_ISL_17323607,
EPI_ISL_17323610, EPI_ISL_17387791, EPI_ISL_17416135,
EPI_ISL_17505626, EPI_ISL_17505638

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice40_genome_41c67_dc5f0.json?label=id:node_6258066)

<img width="1315" alt="Screen Shot 2023-04-20 at 18 33 41" src="https://user-images.githubusercontent.com/10445944/233340963-a5050199-18e4-4a5a-bf1a-172c8131dba5.png">

**Comment by FedeGueli** [comment]
@corneliusroemer while this doent seem superfast as expected stemming out from BN.1 backbone , i would highlight that it shows interesting diversity and likely its share in Taiwan is significative:
It got a likely recombination with XBB.1+Orf8:G8* in one sample collected in Illinois:
![Schermata 2023-06-01 alle 09 58 57](https://github.com/cov-lineages/pango-designation/assets/87669813/7f1b7b37-c98e-4f32-81de-95f72f965cef)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35594_84d460.json?c=gt-ORF1ab_47&label=id:node_7234439
or this recent cluster in Japan with a further (unusual) Spike mutations S:F43Y
![Schermata 2023-06-01 alle 10 01 30](https://github.com/cov-lineages/pango-designation/assets/87669813/9b60bf8a-69c1-4ad6-906c-af0eb7834efe)

**Comment by aviczhl2** [comment]
57 and in New Zealand.

**Comment by aviczhl2** [comment]
66 and Austria.
