### ISSUE TITLE
NoteWorthy XBB.1* descendent with S:L455F and S:F456L

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#1925]
Sub-Lineage of XBB.1* (It has the G252V mutation, but interestingly lack G8*)
Mutations on top of XBB.1*: C2509T, G22927T, T22928C, T27531C
Gisaid Inquiry: Spike_V445P,Spike_L455F,Spike_F456L, T27531C
Earliest sequence: EPI_ISL_16598936|2023-01-08 Pakistan
Latest sequence: EPI_ISL_17501368|2023-04-04 Pakistan
Gisaid Inquiry Result:
EPI_ISL_16598936, EPI_ISL_16996058, EPI_ISL_16996643,
EPI_ISL_17007038, EPI_ISL_17098465, EPI_ISL_17373383,
EPI_ISL_17389621, EPI_ISL_17501368, EPI_ISL_17501379,
Regions: Pakistan (seemingly origin), Isareal (Imported?), UK (weird, probably travel?)
Usher Tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_75d2_167620.json?c=gt-ORF8_8&f_userOrOld=uploaded%20sample&gt=S.455F,456L,252V&label=id:node_3139017
<img width="602" alt="CA1F890A-3FCF-4BF3-A124-1E2B20DCE89B" src="https://user-images.githubusercontent.com/131021067/233432082-ea9fedc5-0868-48af-9bd0-2c2e429d0897.png">

This is quite interesting because when I was searching S:455, a powerful escape site of XBB mentioned in a past twitter of jbloomlab, I see that S:L455F could be potentially advantageous, so I perform a search with S:445P and S:455F. That give me utter gibberish with about 28 Gisaid Sequences in the USHER tree that is mostly manually put together with non 455F branches. Yet there is a subbranch with S:F456L, the opposite of what we see at S:L455F. 
That branch turned out to be of much higher quality, as USHER successfully put 9 Gisaid lineage and 6 open lineage together all bearing the same mutations. So I would like to nominate this lineage.
Not only does it show a decent escape, but the fact that those two RBD mutations are relatively speaking not changing amino acid much themselves and complementary means that this mutation probably keep a good protein structure of XBB, so it could be a free cake escape combination and being advantageous.
Note: there is one new Chilean lineage if the Gisaid inquiry is simply S:445P and the two defining RBD mutations of this lineage, but it is put on a different branch and has S:486P, so I am not sure whether that also belong to my definition.

**Comment by FedeGueli** [comment]
Hi @krosa1910 already proposed in #1681 .

cc @thomasppeacock

**Comment by krosa1910** [comment]
> Hi @krosa1910 already proposed in #1681 .
> 
> cc @thomasppeacock

Sorry, I would close this.

**Comment by FedeGueli** [comment]
> > Hi @krosa1910 already proposed in #1681 .
> > cc @thomasppeacock
> 
> Sorry, I would close this.

no worry it is always better being more than one in discovering new lineages

**Comment by FedeGueli** [comment]
Sorry @krosa1910 for being late your spot was now proposed by Ooob in #1982

**Comment by FedeGueli** [comment]
SO @krosa1910 i suggest you to reopen this one, you have the clear picture and could monitor the two better than me. please.

**Comment by FedeGueli** [comment]
@krosa1910 pls reopen this one in the other page

**Comment by FedeGueli** [comment]
Designated XBB.1.48 via https://github.com/cov-lineages/pango-designation/commit/d9809606594475b005114a33bc78b12484416cae
