### ISSUE TITLE
Descendent of XBC.1.6 with stop codon in orf7a:Q21* in South Australia

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#1928]
Sublineage of XBC.1.6
Mutation Gained Compared to XBC.1.6: G2744A/orf1a:D827N--->G5572I/orf1a:M1769I--->T1936C, C27454T/orf7a:Q21*
Gisaid Inquiry: under Lineage XBC.1.6, search C27454T
Inquiry Result:
EPI_ISL_17324195, EPI_ISL_17324208, EPI_ISL_17324217-17324219,
EPI_ISL_17324225, EPI_ISL_17324241, EPI_ISL_17324268,
EPI_ISL_17324276, EPI_ISL_17398298, EPI_ISL_17463441,
Earliest sequence: EPI_ISL_17324195|2023-03-20 South Australia
Latest sequence: EPI_ISL_17463441|2023-03-30 South Australia
quite evident that this is apart of XBC.1.6 family from this Usher tree classification
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20d7c_18bd80.json?c=gt-ORF7a_21&gmin=27027&label=id:node_4689690
<img width="635" alt="EB835738-724C-41D3-B65B-67E9B3E263D9" src="https://user-images.githubusercontent.com/131021067/233481700-9cb99e9b-875b-4f5d-b8bf-2916b78668d3.png">
Routinely checking XBC.1.6 genome, and find this lineage. 
It has a very concentrated sequence and submission pattern, and that is what I do not understand. I remember Mike Honey mentioned on twitter that some samples in Australia has group submission habits, so probably the concentrated pattern arises from such practice. 
Nevertheless, I consider this to be a new attempt of SARS-COV-2 to discard the highly debated and mysterious ORF proteins. Ryan Hisner have summarized excellently about the attempt of both XBB and XBC to discard ORF8, and now we see that both ORF7a and ORF 8 are largely truncated within a lineage. 
Would be curious about whether this can grow.  jbloomlab calculator strongly criticize Q21* in Orf7a, making it probably the worst position of ORF7a to be stopped.

**Comment by corneliusroemer** [comment]
Very small and not clear why something so specific should get designated at this point. We'd start designating big branches on the polytomy first before going so deep.
