### ISSUE TITLE
NEW XBB.1 + Orf8:G8* sublineage with S:F486P emerged in Russia 104 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1929]
After the XBB.2 +486P previously proposed i spotted another S:486P sublineage that likely emerged in Russia from XBB.1+Orf8:G8*

Tree:
XBB.1>> Orf8:G8*>>A5371G > S:F486P (T23018C)  

Gisaid query : G7459T ,A1846G, T27285C (**NOTE**: This query is just one step deeper in the tree and misses the first three sequences of this lineage)
![Schermata 2023-04-20 alle 23 11 52](https://user-images.githubusercontent.com/87669813/233488638-63dbfcea-4300-48f2-86b0-5805e68fa2be.png)

Tree:
![Schermata 2023-04-20 alle 23 12 29](https://user-images.githubusercontent.com/87669813/233488735-4e80f358-5ea6-4f49-9f08-ae8a8cc6e2a6.png)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice31_genome_test_4dcca_1a58c0.json?c=gt-S_486&label=id:node_5840600

Countries:
![Schermata 2023-04-20 alle 23 13 06](https://user-images.githubusercontent.com/87669813/233488839-182a41d8-639b-4524-a681-b9441210f988.png)

Sequences: 60
EPI_ISL_16879246, EPI_ISL_16879286, EPI_ISL_16899420,
EPI_ISL_16975262, EPI_ISL_17027395-17027398, EPI_ISL_17092878,
EPI_ISL_17105822, EPI_ISL_17106375, EPI_ISL_17150275,
EPI_ISL_17187401, EPI_ISL_17231176, EPI_ISL_17241626,
EPI_ISL_17328012, EPI_ISL_17344567, EPI_ISL_17344595,
EPI_ISL_17344684, EPI_ISL_17360625, EPI_ISL_17363280,
EPI_ISL_17364731, EPI_ISL_17407683, EPI_ISL_17408195,
EPI_ISL_17408939, EPI_ISL_17409267, EPI_ISL_17409756,
EPI_ISL_17409765, EPI_ISL_17412298, EPI_ISL_17412346,
EPI_ISL_17412391, EPI_ISL_17415689, EPI_ISL_17416183,
EPI_ISL_17419098, EPI_ISL_17428446, EPI_ISL_17433386,
EPI_ISL_17433393, EPI_ISL_17445923, EPI_ISL_17473356,
EPI_ISL_17474860, EPI_ISL_17474941, EPI_ISL_17480977,
EPI_ISL_17481015, EPI_ISL_17481039, EPI_ISL_17481048,
EPI_ISL_17481053, EPI_ISL_17481086, EPI_ISL_17481109,
EPI_ISL_17481121, EPI_ISL_17482247, EPI_ISL_17483742,
EPI_ISL_17483777, EPI_ISL_17484033, EPI_ISL_17500645,
EPI_ISL_17502093-17502096, EPI_ISL_17507183, EPI_ISL_17511375,

**Comment by Mydtlwn** [comment]
#1909 #1929 seems to be a little different.

**Comment by corneliusroemer** [comment]
Let's let them grow a bit more - don't think there's a rush given the genotype has been designated dozens of times already

**Comment by FedeGueli** [comment]
3 new samples from Thailand (  Chon Buri not a very turistic area: apparently that region harbours a big commercial harbour), South Korea and France ( from an inpatient middleaged woman)

@corneliusroemer This seems have managed to break the Russian borders and it is going international last week samples have been uploaded from 5 different countries.

**Comment by FedeGueli** [comment]
Big upload of this sublineage! it jumped to 99 sequences last samples came from 8 different regions of Russia (and Crimea) and from South Korea.

@corneliusroemer @thomasppeacock @InfrPopGen as its "sibling russian" xbb.2*486P i think it is better to designate it , it would be tracked easily. Its growth in the country of origin was clear and its ability to spread and circulate elesewhere too.

**Comment by FedeGueli** [comment]
Austria,Australia, South Korea (local) Israel  Sweden the last uploads.
@corneliusroemer this suggests to me that it could be  more widespread cause it is found where active surveillance is ongoing,

**Comment by aviczhl2** [comment]
Also appears in today's Hubei seqs. Globally now.

**Comment by FedeGueli** [comment]
thx @corneliusroemer for designating , one question i do see just 115 seqs on usher and 110 on Gisaid while in the commit you used 140. is it right?

my seqs for sure belonging to this lineage are:
EPI_ISL_16879246, EPI_ISL_16879286, EPI_ISL_16899420,
EPI_ISL_16975262, EPI_ISL_17027395-17027398, EPI_ISL_17092878,
EPI_ISL_17105822, EPI_ISL_17106375, EPI_ISL_17150275,
EPI_ISL_17187401, EPI_ISL_17231176, EPI_ISL_17241626,
EPI_ISL_17317854, EPI_ISL_17328012, EPI_ISL_17344567,
EPI_ISL_17344595, EPI_ISL_17344684, EPI_ISL_17360625,
EPI_ISL_17363280, EPI_ISL_17364731, EPI_ISL_17407683,
EPI_ISL_17408195, EPI_ISL_17408939, EPI_ISL_17409267,
EPI_ISL_17409756, EPI_ISL_17409765, EPI_ISL_17412298,
EPI_ISL_17412346, EPI_ISL_17412391, EPI_ISL_17415689,
EPI_ISL_17416183, EPI_ISL_17419098, EPI_ISL_17428277,
EPI_ISL_17428446, EPI_ISL_17433386, EPI_ISL_17433393,
EPI_ISL_17473356, EPI_ISL_17474860, EPI_ISL_17474941,
EPI_ISL_17480977, EPI_ISL_17481015, EPI_ISL_17481039,
EPI_ISL_17481048, EPI_ISL_17481053, EPI_ISL_17481086,
EPI_ISL_17481109, EPI_ISL_17481121, EPI_ISL_17483742,
EPI_ISL_17483777, EPI_ISL_17484033, EPI_ISL_17500645,
EPI_ISL_17502093-17502096, EPI_ISL_17507183, EPI_ISL_17511375,
EPI_ISL_17538978, EPI_ISL_17545456, EPI_ISL_17547296,
EPI_ISL_17563113-17563114, EPI_ISL_17563257, EPI_ISL_17563455,
EPI_ISL_17563476, EPI_ISL_17563812, EPI_ISL_17563923,
EPI_ISL_17563934, EPI_ISL_17564079, EPI_ISL_17566209,
EPI_ISL_17566227, EPI_ISL_17566294, EPI_ISL_17566306,
EPI_ISL_17566310, EPI_ISL_17566363, EPI_ISL_17566390,
EPI_ISL_17566408, EPI_ISL_17566443, EPI_ISL_17566454,
EPI_ISL_17566461, EPI_ISL_17566469, EPI_ISL_17566519,
EPI_ISL_17566522, EPI_ISL_17566527, EPI_ISL_17566921,
EPI_ISL_17566931, EPI_ISL_17566945, EPI_ISL_17566952,
EPI_ISL_17567054, EPI_ISL_17567057, EPI_ISL_17567096,
EPI_ISL_17567125, EPI_ISL_17567159, EPI_ISL_17567182,
EPI_ISL_17567197, EPI_ISL_17567250, EPI_ISL_17596214,
EPI_ISL_17596542, EPI_ISL_17604274, EPI_ISL_17604760,
EPI_ISL_17604838, EPI_ISL_17605328, EPI_ISL_17608066,
EPI_ISL_17615018
