### ISSUE TITLE
Some misassignment of B.1 lineages

### ISSUE THREAD

**Issue by Desperate-Dan** [cov-lineages/pango-designation#193]
Recently we've noticed some of our sequencing positive controls are being misassigned. Typically they are assigned B.1 but at the moment they are coming out as B.1.400 or more recently as B.1.402. This appears to be when there are slightly more Ns in the sequence (300 - 400Ns) and pangolin no longer uses the designation hash but uses PLEARN. I have a docker container with pangolin version 3.0.6 which calls the sequences in question B.1, but running these sample in my current build with pangolin version 3.1.11, both sequences come out as B.1.402. I've attached a snipit plot which shows that the SNP profiles of our two misassigned positives match B.1 rather than either B.1.400 or B.1.402. I think the designations of B.1.400 and B.1.402 may need to be checked for some B.1 sequences hiding in there. Cheers!

![snp_plot](https://user-images.githubusercontent.com/84576669/130040611-5d545e1f-1429-4819-84e9-30c7ae12b8cc.png)

**Comment by chrisruis** [comment]
Thanks @Desperate-Dan. It looks like there were 17 sequences designated B.1.400 that cluster outside of the main B.1.400 clade in the latest UShER tree. Additionally there was 1 sequence designated B.1.402 that clusters outside of the main B.1.402 in the latest UShER tree. We've removed these 18 sequences from the designations in [v1.2.69](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.69).

Hopefully that will solve your assignments but let us know if not and we'll take another look
