### ISSUE TITLE
BQ.1.1.13 with S:L176F emerging in China(27 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1932]
Maybe the 1st Chinese-specific BQ.1.1 sublineage, with the convergent mutation of S:176F. (DV.1)

sub-lineage of: BQ.1.1.13
mutations on top of BQ.1.1.13: C17502T, C6541T,A8938G,C22088T(S:L176F)
GISAID query: C6541T,A8938G,C22088T
No. of seqs: 19( China 18, South Korea 1)
First seq: EPI_ISL_17374380(South Korea) 2023-3-11
Latest seq: EPI_ISL_17511845(China) 2023-4-2

Sequences:
EPI_ISL_17374380, EPI_ISL_17485677-17485678, EPI_ISL_17511830,
EPI_ISL_17511845-17511846, EPI_ISL_17511855, EPI_ISL_17511931-17511932,
EPI_ISL_17511934, EPI_ISL_17511936-17511938, EPI_ISL_17511943,
EPI_ISL_17511945, EPI_ISL_17511949, EPI_ISL_17511954,
EPI_ISL_17511960, EPI_ISL_17511965

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_28789_2193d0.json?label=id:node_7370453)

<img width="1392" alt="Screen Shot 2023-04-21 at 14 40 48" src="https://user-images.githubusercontent.com/10445944/233560308-960350ac-26f1-4ce8-ae44-a466b7f5a2ae.png">

**Comment by corneliusroemer** [comment]
All Shanghai and a bit small still

**Comment by aviczhl2** [comment]
no new seqs
