### ISSUE TITLE
XBB.1.5 sublineage with S:E281D and further gets S:P445S (67seqs) 

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1933]
Defining mutations: XBB.1.5>C29095T>A22405T (S:E281D), then one branch further gets C22895T (S:P445S)
GISAID query: Spike_E281D, C29095T, T17124C
Earliest seq: 2023-01-13 (USA, EPI_ISL_16668636)
Most recent seq: 2023-04-12 (Vietnam, EPI_ISL_17481620)
Countries detected: South Korea (33), USA (13), Vietnam (9), Japan (3), Singapore (2), Canada (2), China (1), Germany (1), France (1), Austria (1), Sweden (1)

Usher Tree:
![QQ截图20230421183715](https://user-images.githubusercontent.com/121703496/233617455-7d36d01b-bf0b-43b8-b812-ea8db693f087.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36286_220110.json
The early seqs mainly appear in USA. When the branch further got S:P445S (probably in South Korea) the growth increased again. 
![QQ截图20230421184558](https://user-images.githubusercontent.com/121703496/233617378-b83a6058-70c8-467f-86e8-275a4d29d133.png)

https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-01-16%26to%3D2023-04-10/variants?nextcladePangoLineage=XBB.1.5*&aaMutations1=S%3AE281D&nextcladePangoLineage1=XBB.1.5*&analysisMode=CompareToBaseline&

Genomes: 
EPI_ISL_16668636, EPI_ISL_16780469, EPI_ISL_16889111, EPI_ISL_16906974, EPI_ISL_17014591, EPI_ISL_17090120, EPI_ISL_17193753, EPI_ISL_17249397, EPI_ISL_17262150-17262151, EPI_ISL_17278656, EPI_ISL_17281565, EPI_ISL_17343756, EPI_ISL_17348604, EPI_ISL_17364938, EPI_ISL_17373874, EPI_ISL_17373960, EPI_ISL_17374219, EPI_ISL_17374430, EPI_ISL_17375024, EPI_ISL_17375273, EPI_ISL_17375278, EPI_ISL_17388520, EPI_ISL_17414702, EPI_ISL_17414840, EPI_ISL_17414854, EPI_ISL_17414884, EPI_ISL_17414889,
EPI_ISL_17415006, EPI_ISL_17415147, EPI_ISL_17415185, EPI_ISL_17415187, EPI_ISL_17415810, EPI_ISL_17415866, EPI_ISL_17415868, EPI_ISL_17415945, EPI_ISL_17416174, EPI_ISL_17416195, EPI_ISL_17428356, EPI_ISL_17431915, EPI_ISL_17433114, EPI_ISL_17445002, EPI_ISL_17445008, EPI_ISL_17472090, EPI_ISL_17473525, EPI_ISL_17474196, EPI_ISL_17474423, EPI_ISL_17474541-17474544, EPI_ISL_17481608-17481609, EPI_ISL_17481613-17481616, EPI_ISL_17481618-17481620, EPI_ISL_17489973, EPI_ISL_17490046, EPI_ISL_17491136, EPI_ISL_17491832, EPI_ISL_17493945, EPI_ISL_17511419, EPI_ISL_17511614,

**Comment by FedeGueli** [comment]
Interestingly a S in 445 if 444 changes further to N as we saw a lot of times in BA.5s could lead to a potential new N Glycan due to 446S .
@thomaspeacock

**Comment by corneliusroemer** [comment]
Designated broadly, requiring S:E281D but not S:P445S

**Comment by FedeGueli** [comment]
@HynnSpylor @corneliusroemer  One of this showed up today in Yunnan very recent sample with S:69/70del beyond 445S and 281D : EPI_ISL_17547638.

i suggest to opne up an issue for the sublineage with 445S so the variant seeking community can keep it checked, this could give us some surprise. It is a change in one defining mut of XBB better to keep it under the spotlight.

**Comment by FedeGueli** [comment]
I am seeing that it is the lineage with Orf1a:K1655N to be growing faster and being the most represented in the recent samples.
It is partially found by A22405T,G5230T  query (17 out of 21)
Usher has 21 on its tree:
![Schermata 2023-04-26 alle 12 26 20](https://user-images.githubusercontent.com/87669813/234548023-8dd0a09b-6be8-4612-a291-54c818b8e575.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_be2d_8f9670.json?c=userOrOld&label=id:node_5962882 

Interestingly it has been sampled fro travellers  from S Korea, Thailand, Vietnam, and in two chinese samples (Shangai, Yunnan)
