### ISSUE TITLE
Another XBB.1 + Orf8:G8* sublineage with S:F486P and Orf9b:P3L circulating in Usa and Portugal and internationally (193 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1937]
I luckily spotted another XBB.1 +486P ( it is very easy to do just upload any XBB sample to Usher then colour the tree by S:486 and check any coloured sample, they are several, some very small, others under the XBB.1.5 umbrella, but still some unknown ones , so better to track'em)

This time the one proposed here has an additional Orf9b mutation and it is mainly circualting in two countries Portugal and Usa.

Orf9b:
<img width="674" alt="Screenshot 2023-04-22 alle 00 33 02" src="https://user-images.githubusercontent.com/87669813/233744171-83508284-49ff-4cb2-8fab-4437e1b12a1c.png">

Defining mutations:
XBB.1*>> orf8:G8* (G27915T) > T21000C > A19137G, Orf9b:P3L (C28291T) >A3139G, S:f486P (T23018C)

Gisaid query : A3139G, A19137G,T23018C, C28291T

Sequences: 127 
<Details>
<Summary> HERE EPI_ISLs </Summary>
EPI_ISL_16184049, EPI_ISL_16184225, EPI_ISL_16227569,
EPI_ISL_16344464, EPI_ISL_16397882, EPI_ISL_16524354,
EPI_ISL_16543053, EPI_ISL_16611139, EPI_ISL_16701518,
EPI_ISL_16709915, EPI_ISL_16732927, EPI_ISL_16734586,
EPI_ISL_16734993, EPI_ISL_16734995, EPI_ISL_16754625,
EPI_ISL_16818531, EPI_ISL_16876311, EPI_ISL_16876345,
EPI_ISL_16876521, EPI_ISL_16876571, EPI_ISL_16876624,
EPI_ISL_16962684, EPI_ISL_16962796, EPI_ISL_16968381,
EPI_ISL_16980471, EPI_ISL_16999572, EPI_ISL_16999618,
EPI_ISL_17001234, EPI_ISL_17001243, EPI_ISL_17001309,
EPI_ISL_17013561, EPI_ISL_17038728, EPI_ISL_17060233,
EPI_ISL_17089081, EPI_ISL_17096161, EPI_ISL_17096194,
EPI_ISL_17096262, EPI_ISL_17096264, EPI_ISL_17096494,
EPI_ISL_17138081, EPI_ISL_17146370, EPI_ISL_17148136,
EPI_ISL_17180264, EPI_ISL_17197092, EPI_ISL_17201706,
EPI_ISL_17203466, EPI_ISL_17240662, EPI_ISL_17242511,
EPI_ISL_17242525, EPI_ISL_17242534, EPI_ISL_17242566-17242567,
EPI_ISL_17242578, EPI_ISL_17261248, EPI_ISL_17286698,
EPI_ISL_17286809, EPI_ISL_17287683, EPI_ISL_17291730,
EPI_ISL_17291972, EPI_ISL_17291989, EPI_ISL_17295564,
EPI_ISL_17307449, EPI_ISL_17307525, EPI_ISL_17307535,
EPI_ISL_17307651, EPI_ISL_17307683, EPI_ISL_17307703,
EPI_ISL_17307712, EPI_ISL_17307714-17307716, EPI_ISL_17307737,
EPI_ISL_17307741, EPI_ISL_17307801, EPI_ISL_17307804,
EPI_ISL_17307867, EPI_ISL_17307879, EPI_ISL_17307957,
EPI_ISL_17321298, EPI_ISL_17321875, EPI_ISL_17347751,
EPI_ISL_17347784, EPI_ISL_17348976, EPI_ISL_17351972,
EPI_ISL_17376137, EPI_ISL_17376160, EPI_ISL_17376201,
EPI_ISL_17376214, EPI_ISL_17376221, EPI_ISL_17402213,
EPI_ISL_17411750, EPI_ISL_17411831, EPI_ISL_17419732,
EPI_ISL_17419938, EPI_ISL_17420042, EPI_ISL_17420089,
EPI_ISL_17420379, EPI_ISL_17420487, EPI_ISL_17420496,
EPI_ISL_17420499, EPI_ISL_17420542, EPI_ISL_17420733,
EPI_ISL_17429317, EPI_ISL_17429711, EPI_ISL_17430272,
EPI_ISL_17430334, EPI_ISL_17467691, EPI_ISL_17467726,
EPI_ISL_17467846, EPI_ISL_17467850, EPI_ISL_17467892,
EPI_ISL_17467907, EPI_ISL_17467913, EPI_ISL_17479943,
EPI_ISL_17484057-17484058, EPI_ISL_17484176, EPI_ISL_17484178,
EPI_ISL_17484280, EPI_ISL_17486021, EPI_ISL_17486476,
EPI_ISL_17486566, EPI_ISL_17492410-17492411, EPI_ISL_17492414,
EPI_ISL_17492422, EPI_ISL_17514347
</Details>

Tree:
<img width="1163" alt="Screenshot 2023-04-22 alle 00 45 52" src="https://user-images.githubusercontent.com/87669813/233745322-d497b9c6-049f-4039-a10d-7f1452e59b4c.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_27717_30e2f0.json?c=country&label=id:node_5874338

**Comment by corneliusroemer** [comment]
Hmm, it's very small - this is practically the same as XBB.1.5 - let's see if it grows more, we already have enough homoplasy designated

**Comment by FedeGueli** [comment]
11 new samples mostrly US mostly California , one from Canada. @corneliusroemer ok i got your reasoning,and i agree for sparse uploads only lineages, but this is still growing.

**Comment by FedeGueli** [comment]
144 samples all new samples came from California.

**Comment by FedeGueli** [comment]
Designated XBB.1.45.1 from https://github.com/cov-lineages/pango-designation/commit/c6a8528767f52be110e361a66c4a29f63cbd0275
