### ISSUE TITLE
BF.7.14 Sublineage with N:A35T, E:T11M, & 5x ORF1ab (12 seq, April 21)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1938]
**Description**
**Sub-lineage of:** BF.7.14
**Earliest sequence:** 2023-3-13, China, Zhejiang — EPI_ISL_17487943
**Most recent sequence:** 2023-4-7, China, Zhejiang —EPI_ISL_17501566
**Countries circulating:** China (12)
**Number of Sequences:** 12
**GISAID AA Query:** E_T11M, N_A35T, NSP12_S229N, NSP9_T35I
**GISAID Nucleotide Query:** C7113T, C7860T, C8092T, G10850A
**CovSpectrum Query:** Nextcladepangolineage:BF.7.14* & [3-of: C7113T, C7860T, C8092T, G10850A]
**Substitutions on top of BF.7.14:**
**N:** A35T
**E:** T11M
**ORF1a:** T2283I, T2532I, A3529T, T4175I
**ORF1b:** S220N
**Nucleotide:** C7081T, C7093T, C7113T, T7453C, C7860T, C8092T, G10850A, C12073T, C12789T, C11962A, G14126A, C18570T, T24763C, C26276T, G28376A
 
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BF.7.14_Zhejiang_Saltation_subtreeAuspice1_genome_19d52_33c250.json

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/33738461/233755791-e2e7a717-8f7e-41f6-a61a-38b639ad3cc2.png">

 
**Evidence**
This appears to be something of a saltation lineage in BF.7.14 in Zhejiang, China. E:T11M has been an extremely rare mutation throughout the pandemic, appearing in fewer than 180 sequences altogether. ORF1a:T4175I (NSP9_T35I) has long been common in chronic-infection sequences and has recently become a convergent mutation emerging in numerous circulating lineages.
 
ORF1a:A3529T (NSP5_A266T) is another very rare mutation, and has only been seen in 19 sequences since January 1, 2022.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17487864, EPI_ISL_17487943, EPI_ISL_17493709, EPI_ISL_17494732, EPI_ISL_17494734-17494736, EPI_ISL_17501481, EPI_ISL_17501520, EPI_ISL_17501551, EPI_ISL_17501566, EPI_ISL_17501575
</details>

**Comment by AnonymousUserUse** [comment]
Candidate for Molnupiravir-driven mutations?

**Comment by ryhisner** [comment]
@AnonymousUserUse, yes I believe this is a possible candidate for a molnupiravir-created lineage. Evidence in favor: 
 
• 14/15 transitions in the two preceding long branches
• Very high C->T + G->A content—12/15 (80%) in the two preceding branches and 8/8 (100%) in directly preceding branch
• Very low rate of non-synonymous mutations: 7/15 in two preceding branches (46.7%) and 4/8 in directly preceding branch (50%)
• 0/7 amino acid mutations in spike—unusual for most long-branch lineages but typical of molnupiravir sequences

Evidence against:

• G->A content, at 3/15 (20%) in two preceding branches and 1/8 (12.5%) in the directly preceding branch, is barely higher than expected.
• The two sequences from Anhui divide what would otherwise be a 15-mutation branch in two and suggest that there could be a large number of intermediate sequences that have not been sampled, meaning it's possible these long branches would really be divided into  numerous smaller branches, indicating stepwise evolution rather than saltations. 

There is one transversion in there and G->A mutations aren't quite high enough to make any definitive claim, but I think there's a decent chance molnupiravir use was involved.

**Comment by AnonymousUserUse** [comment]
Thanks for the analysis.
Saltation with intermediate branches is not uncommon: we have seen that in the case of BA.1/2/3/4/5 as well as B.1.617.1/2/3. It is unknown whether molnupiravir-driven saltation can also have intermediate branches, but I think it is possible, for exemple if transmission occurs from different forms of saltation of a patient who is treated with molnupiravir.

**Comment by DailyCovidCases** [comment]
Please close this issue
