### ISSUE TITLE
XBB.1.5.20 with S:Q954Y [29 sequences, Canada]

### ISSUE THREAD

**Issue by Outpfmance** [cov-lineages/pango-designation#1939]
Description
Sub-lineage of:XBB.1.5.20
Earliest sequences:2023-3-24,Canada EPI_ISL_17462154
Latest sequences:2023-4-2,Canada EPI_ISL_17500101/17500102
Countries:Canada(22)
Number of Sequences:22
GISAID query:Spike_Q954Y,T17124C,A19326G,T23018C,C9532T
Cov-spectrum: https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-03-01%26to%3D2023-04-22/variants?aaMutations=s%3A954Y&nextcladePangoLineage=XBB.1.5.20&
Nextstrain: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_27dfe_377050.json?f_userOrOld=uploaded%20sample
![IMG_0122](https://user-images.githubusercontent.com/125484893/233769432-8a3abe34-501e-46a4-a037-4df814410f7d.jpeg)
Nextclade:
![IMG_0119](https://user-images.githubusercontent.com/125484893/233769506-66f954b9-a75d-4774-ba40-e7077a3bb944.jpeg)

Evidence
This is a particular branch that replaces one of Omicron's defining mutations, Q954H. It is well known that S:Q954H and S:N969K make S2 in this region more positively charged than pre-Omicron lineages. Does this property change when one of them changes? I think this is a branch that needs to be looked at and tracked.
Sequences:
EPI_ISL_17412758	
EPI_ISL_17462154	 
EPI_ISL_17462155	 
EPI_ISL_17462158	
EPI_ISL_17462160	
EPI_ISL_17499741	
EPI_ISL_17499809	
EPI_ISL_17499811	
EPI_ISL_17499812	
EPI_ISL_17499857	
EPI_ISL_17499860	
EPI_ISL_17499863	
EPI_ISL_17500043	
EPI_ISL_17500044	
EPI_ISL_17500045	
EPI_ISL_17500047	
EPI_ISL_17500050	
EPI_ISL_17500051	
EPI_ISL_17500052	
EPI_ISL_17500056	
EPI_ISL_17500101	
EPI_ISL_17500102

**Comment by ryhisner** [comment]
I've seen a few H954L sequences lately as well. I wonder if there are some weak S2 antibodies to Q954H causing this (possible) trend.

**Comment by Outpfmance** [comment]
29 sequences now.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1bf99_a6b9d0.json?f_userOrOld=uploaded%20sample&label=id:node_4700458
![IMG_0157](https://user-images.githubusercontent.com/125484893/234864111-afc28f1c-2d31-4bf6-826c-3592e6e03998.jpeg)

**Comment by Outpfmance** [comment]
@ryhisner I open a issue for this. #1968

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
This branch is dead, please close this issue
