### ISSUE TITLE
proposal to merge B.59 into B.1.1.267

### ISSUE THREAD

**Issue by babarlelephant** [cov-lineages/pango-designation#194]
Hi, B.59 is a sublineage of B.1.1, mainly Ireland as well as US, UK, Greece, Latvia. 

Consensus mutations both in designated and assigned sequences 

`C241T,C3037T,C14408T,A23403G,G28881A,G28882A,G28883C,C14786T`

B.1.1.267 consensus is

`C241T,C3037T,C14408T,A23403G,G28881A,G28882A,G28883C,C14786T,A20952G`

and the only country is Ireland.

Otherwise B.1.1.190 has very few sequences, from UK, and its consensus is 

`C241T,C3037T,C14408T,A23403G,G28881A,G28882A,G28883C,C14786T,G28703A`

https://outbreak.info/situation-reports?pango=B.59
https://cov-lineages.org/lineage.html?lineage=B.59
https://cov-lineages.org/lineage.html?lineage=B.1.1.190
https://cov-lineages.org/lineage.html?lineage=B.1.1.267

A rapid look suggests that A20952G appeared in Ireland, following introduction of B.1.1+C14786T in early March. That is  B.1.1+A20952G wasn't seen outside Ireland in spring 2020.

First sequence with B.1.1+C14786T in Ireland, 13 March. So it does make sense to merge into the Irish lineage B.1.1.267, even if it is unlikely that C14786T appeared in Ireland, as it was seen a few days later in many different countries (Including Switzerland. But not Italy. One more super-spreading event in a ski station?)

**Comment by chrisruis** [comment]
Thanks @babarlelephant. Looking at this part of the latest UShER tree, both B.1.1.267 and B.1.1.269 emerge from within the diversity designated as B.59. These 3 lineages as well as sequences assigned B.1.1 in the same clade share A26314G (E:M24V). The sequences designated B.59 are not a single monophyletic clade and there doesn't seem to be a single mutation that defines them while excluding B.1.1.267 and B.1.1.269.

The sequences designated B.1.1.267 are in a single clade downstream of A20952G and C28991A and the sequences designated B.1.1.269 are in a single clade downstream of C26895T.

Based on this, there doesn't seem to be a reasonable way to merge these lineages so we've withdrawn lineage B.59 in [v1.2.70](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.70). We've left B.1.1.267 and B.1.1.269 as they were. Thanks again
