### ISSUE TITLE
XBB.1.22.1 Sublineage with S:A83S, S:T573I, N:T366I, ORF1a:K625E, ORF1b:D1782N (55 seq, Apr 22)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1940]
### **Description**
**Sub-lineage of:** XBB.1.22.1
**Earliest sequence:** 2023-2-13, Bahrain — BHR/981006523/2023|OQ748161.1, BHR/811009319/2023|OQ748189.1
**Most recent sequence:** 2023-3-26, Bahrain — BHR/23020151288/2023|OQ781667.1
**Countries circulating:** Bahrain (55)
**Number of Sequences:** 55
### **NOTE: There are zero sequences in this lineage on GISAID and CovSpectrum as of April 22**
**GISAID AA Query:** Spike_V83S, NSP3_K445E, Spike_T573I
**GISAID Nucleotide Query:** A2138G, C23280T, C29370T, C29627T
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.22.1* & [3-of: A2138G, C23280T, C29370T, C29627T]
**Substitutions on top of XBB.1.22.1:**
**Spike:** A83S, T573I
**N:** T366I
**ORF1a:** K625E (NSP2_K445E)
**ORF1b:** D1782N (NSP14_D258N)
**ORF10:** R24C
**Nucleotide:** A2138G, G18811A, G21809T, C23280T, C29370T, C29627T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.22.1_A83S_T573I__Bahrain_subtreeAuspice1_genome_cd64_3cd670.json   
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/33738461/233787450-5ce71f4b-8b0d-4225-a62f-76b8c325f272.png">

**Evidence**
For whatever reason, Bahrain sequences are only found on GenBank and not on GISAID or CovSpectrum. GenBank is incredibly user-unfriendly, and though I've tried, I have no idea how to do nucleotide, AA, country, or any other kind of search there. I'm relying entirely on the sequences I accidentally ran across on an Usher tree. I have no idea what percentage of Bahraini sequences this lineage makes up in the relevant time period, and I don't know if there are additional sequences not found on the Usher tree I used. If someone who knows how to use GenBank wants to do a more detailed search to figure these things out, that would be wonderful.
 
 
**Genomes** — None available on any database except the astonishingly clunky, inconvenient, opaque GenBank.

**Comment by aviczhl2** [comment]
Haha, Usher shall create a "whole tree" mode for those who wish to browse through the whole usher tree (and see its various data arranged together) without uploading sequences.  I think this may be something incredibly useful.

**Comment by corneliusroemer** [comment]
Taxonium can show the whole Usher tree @aviczhl2  https://taxonium.org/

@ryhisner you can use open.cov-spectrum.org for a frontend to Genbank (though hasn't been updated in a week)

There's also all open sequences with nucleotide and AA mutations available as tsv here: https://docs.nextstrain.org/en/latest/guides/share/download-data.html

I'd be careful with single country lineages. This looks like it could be an artefact:
<img width="1884" alt="image" src="https://user-images.githubusercontent.com/25161793/233806929-10569f17-b7af-4099-af68-7adffce452ee.png">

If it was present in Bahrain in February and it's transmissible it should show up elsewhere.

Let's see if this pops up elsewhere before designating.

**Comment by corneliusroemer** [comment]
@aviczhl2 feel free to open an issue here: https://github.com/yatisht/usher

The full tree exists, but GISAID does not allow it to be shared (so I've heard) but @AngieHinrichs knows best

**Comment by corneliusroemer** [comment]
Still no sequences here from outside Bahrain, let's assume this is an artefact for now
