### ISSUE TITLE
XBB.1.5 sublineage with S:V772I, S:P521T and S:N481S (64seqs, mainly in USA)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1941]
Defining mutations: XBB.1.5>G18583A (ORF1b:V1706I)>G23876A (S:V772I), C8818T>C10036T>C23123A (S:P521T)>T16203C>A23004G (S:N481S) 
GISAID query: Spike_V772I, Spike_P521T, Spike_N481S, G18583A
Earliest seq: 2023-01-18 (Canada, EPI_ISL_16731033) 
Most recent seq: 2023-04-09 (Canada, EPI_ISL_17516692) 
Countries detected: USA (55), Canada (8), Malaysia (1)
Usher Tree:
![QQ截图20230423032121](https://user-images.githubusercontent.com/121703496/233802731-2d2fd9a2-7d99-45b9-9697-709ce6096932.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1226e_3fefd0.json
the S:P521T(C23123A) mutation is interesting. It grows just recently and seems a "follower" of S:P521S (C23123T).
![QQ截图20230423031953](https://user-images.githubusercontent.com/121703496/233802775-c68038ce-1adb-444a-a105-cff97fdc9839.png)
![QQ截图20230423031929](https://user-images.githubusercontent.com/121703496/233802779-8b011504-07f9-46d7-9765-9bcfe627b1e3.png)

Genomes:
EPI_ISL_16731033, EPI_ISL_16839446, EPI_ISL_16860558, EPI_ISL_16906142, EPI_ISL_16906598, EPI_ISL_16926359, EPI_ISL_16980302, EPI_ISL_17160834, EPI_ISL_17170386, EPI_ISL_17181841, EPI_ISL_17190998, EPI_ISL_17192443, EPI_ISL_17192828, EPI_ISL_17193179, EPI_ISL_17211570, EPI_ISL_17222307, EPI_ISL_17222326, EPI_ISL_17222331, EPI_ISL_17238047, EPI_ISL_17248755, EPI_ISL_17249174,
EPI_ISL_17249382, EPI_ISL_17249820, EPI_ISL_17259245, EPI_ISL_17259374, EPI_ISL_17279039, EPI_ISL_17279115, EPI_ISL_17321190, EPI_ISL_17333270, EPI_ISL_17333401, EPI_ISL_17333523, EPI_ISL_17343495, EPI_ISL_17384132, EPI_ISL_17384471, EPI_ISL_17384663, EPI_ISL_17385568, EPI_ISL_17393400, EPI_ISL_17411769, EPI_ISL_17420227, EPI_ISL_17429464, EPI_ISL_17444216, EPI_ISL_17461881,
EPI_ISL_17465518, EPI_ISL_17465536, EPI_ISL_17477750, EPI_ISL_17478037, EPI_ISL_17478082, EPI_ISL_17478257, EPI_ISL_17486587, EPI_ISL_17491548, EPI_ISL_17491619, EPI_ISL_17492178, EPI_ISL_17492198, EPI_ISL_17508530, EPI_ISL_17508537, EPI_ISL_17514388, EPI_ISL_17516692, EPI_ISL_17523694, EPI_ISL_17524016, EPI_ISL_17524034,EPI_ISL_17524097, EPI_ISL_17524158, EPI_ISL_17524172,
EPI_ISL_17524265

**Comment by corneliusroemer** [comment]
Designated broadly (not requiring S:N481S) as XBB.1.5.41

The 481S can be taken care of as sublineage if it keeps growing.
