### ISSUE TITLE
XBB.1.16.1 Sublineage with S:P521S, ORF1a:L681F

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1942]
**Description**
**Sub-lineage of:** XBB.1.16.1
**Earliest sequence:** 2023-3-16, France — EPI_ISL_17497793
**2nd-Earliest Sequence:** 2023-4-1, Belgium — EPI_ISL_17484410
**Most recent sequence:** 2023-4-3, France — EPI_ISL_17524580
**Countries circulating:** France (3), Australia (2), Belgium (1)
**Number of Sequences:** 6
**GISAID AA Query:** Spike_T547I, Spike_P521S, NSP2_L401F
**GISAID Nucleotide Query:** C2306T, C23123T, C23202T
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.16* & C2306T & C23123T & C23202T
**Substitutions on top of XBB.1.16.1:**
**Spike:** P521S
**ORF1a:** L681F
**Nucleotide:** C2306T, C23123T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.16.1_P521S_subtreeAuspice1_genome_1807e_42fcc0.json
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/33738461/233803743-b31893ed-819d-4890-97b7-f36eba348518.png">

**Evidence**
According to CovSpectrum Collection 42, created & run by Andrew Urquhart, after XBB.1.16 and XBB.1.16.1, the fastest-growing variants (as measured by low CI growth advantage) with ≥250 sequences are XBB.2.3.2, EU.1 (XBB.1.5.26.1), EU.1.1 (XBB.1.5.26.1.1), and XBB.2.3. All of these lineages possess S:P521S. This mutation has not been noticeably advantageous previously, but the same could be said for S:K478R/Q/N. Whether due to epistasis with other XBB* + S:S486P mutations or due to some change in population immunity, S:P521S seems now to confer some degree of benefit. Furthermore, other mutations at the same site have appeared in other XBB* lineages, mainly S:P521Q and S:P521S.

Notably, the four sequences from France and Belgium all have the 2-nucleotide extended homology (A28877T, G28878C) for the TRS-B of N*, the novel sgRNA created by the 3-nucleotide N:203-204 mutations that has been in every B.1 lineage since it first emerged in 2020, and which one early study found to mess with host-cell interferon expression and increase viral loads. https://www.nature.com/articles/s41467-022-28287-8 
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/33738461/233804365-85caa39f-3468-44d9-bec9-afc71b919401.png">

Six sequences seems paltry, but the fact that five of these six sequences were collected in April and that they come from three different countries—one of which is on a different continent thousands of miles away from the other two—suggests this lineage may already be much more widespread than it appears to be. 

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17463472, EPI_ISL_17463479, EPI_ISL_17484410, EPI_ISL_17497793, EPI_ISL_17524580, EPI_ISL_17524590
</details>

**Comment by ryhisner** [comment]
One more of these showed up today, the first from India (Tamil Nadu). Though it's the most recently uploaded, it has the earliest collection date of all. I think this may have originated in an under-sequenced region of India. EPI_ISL_17601885

**Comment by corneliusroemer** [comment]
4 more sequences from Australia, let's designate once it gets a bit more stable, let's say 25 clean sequences (most Indian ones are too patchy right now). I count ~11 right now with 2306T and 23123T
<img width="1539" alt="image" src="https://user-images.githubusercontent.com/25161793/236283188-a0080205-f536-48d4-85a1-5bcd6afb056c.png">
https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_9366_3eac50.json?branchLabel=back-mutations&c=gt-S_521&gt=S.521S,nuc.2306T&label=id:node_5846399

**Comment by FedeGueli** [comment]
The query doesnt work well catching other samples, unrelated weirdly most of them are from different lineages from French Guyane.

Beyond this i think this should be designated with  the query C2306T, C23123T,   T12730A i find 54 sequences 
from 10 countries 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_2fa2a_986780.json?c=country&label=id:node_6609524
![Schermata 2023-06-26 alle 14 48 14](https://github.com/cov-lineages/pango-designation/assets/87669813/05fe733f-6064-4350-98a0-a62db7e0f216)

Maybe better to designate it. @corneliusroemer @ryhisner

**Comment by DailyCovidCases** [comment]
Please close this issue
