### ISSUE TITLE
lineage_notes.txt

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#1943]
FK.1.1	Alias of B.1.1.529.2.75.3.4.1.1.1.1.17.1.2, ORF1a:L384F, ORF1a:R550H
maybe typo of FK.1.2?

**Comment by Over-There-Is** [comment]
XCC	Recombinant lineage of CH.1.1.1 and XBB.1.9.1, predominantly Pakistan, Austrlia, from #1876
*Australia

**Comment by janko-js** [comment]
Today's commit described as FK.1.2 added the second F.1.1 line to lineage_notes.txt, obviously a typo:

https://github.com/cov-lineages/pango-designation/commit/416a59aa6cfd76e93830dc29dd182fcb58017399
