### ISSUE TITLE
Another XBB.2.3+S:G184V with orf1a:P1786L (451 seqs, 33 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1945]
I'd like to propose a side branch of XBB.2.3.2.

sub-lineage of: XBB.2.3
mutations on top of XBB.2.3: S:G184V(G22113T, same as XBB.2.3.2), Orf1a:P1786L(C5622T)
GISAID query: C5622T,G22113T,G6536A
No. of seqs: 43( Australia 1 Brunei 1 Scotland 2 USA 3(California 2 Texas 1) India 37)
First seq: EPI_ISL_17269931(India) 2023-3-9
Latest seq: EPI_ISL_17504909(Brunei) 2023-4-1

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_3f0a3_4ef8e0.json?label=id:node_6079786)

<img width="1400" alt="Screen Shot 2023-04-23 at 16 59 47" src="https://user-images.githubusercontent.com/10445944/233830130-237136e7-7a35-4902-b6ff-d0f6b4053a67.png">

Also having S:G184V, it is as fast as its very fast brother XBB.2.3.2, in fact a little faster under current data. Hence a lot faster than the whole XBB.2.3 family. Although number of seqs is still too small. 

<img width="1151" alt="Screen Shot 2023-04-23 at 17 00 54" src="https://user-images.githubusercontent.com/10445944/233830174-c351925e-5a48-4034-9bfb-3928dc92ed3d.png">

<img width="1101" alt="Screen Shot 2023-04-23 at 17 04 02" src="https://user-images.githubusercontent.com/10445944/233830330-01eb0c22-c08b-494e-bf87-de2dc2a93787.png">

**Comment by aviczhl2** [comment]
96 seqs and in Canada.

**Comment by aviczhl2** [comment]
101 seqs, Sweden and Japan

**Comment by aviczhl2** [comment]
112 and in China

**Comment by aviczhl2** [comment]
114 and in South Korea.

**Comment by aviczhl2** [comment]
128 seqs, Slovenia, Canary Islands , France

**Comment by aviczhl2** [comment]
131 and in Portugal

**Comment by aviczhl2** [comment]
two more in Mauritius

**Comment by aviczhl2** [comment]
139 seqs, Israel,

**Comment by aviczhl2** [comment]
146 seqs, Spain

**Comment by aviczhl2** [comment]
166, Austria, South Africa.

**Comment by aviczhl2** [comment]
174, Singapore

**Comment by FedeGueli** [comment]
This should get a designation in my view.

**Comment by aviczhl2** [comment]
190, Italy

**Comment by aviczhl2** [comment]
199, Bangladesh

**Comment by FedeGueli** [comment]
ping @corneliusroemer i think it is worth desingating also to differentiate from XBB.2.3.2

**Comment by aviczhl2** [comment]
230, Denmark

**Comment by aviczhl2** [comment]
238, Costa Rica

**Comment by aviczhl2** [comment]
258 and appears in Switzerland and Mexico.

**Comment by aviczhl2** [comment]
300, Oman,

**Comment by FedeGueli** [comment]
This should be designated : @corneliusroemer @thomasppeacock @AngieHinrichs @InfrPopGen

**Comment by FedeGueli** [comment]
Orf1a:P1786L is NSP3_P968L = PLPro_P223L  didnt find anything about that tough.

**Comment by aviczhl2** [comment]
311, Ireland.

**Comment by aviczhl2** [comment]
@FedeGueli  There seems to be more than #2241 sub-branch of this also growing quickly these days.

**Comment by FedeGueli** [comment]
> @FedeGueli There seems to be more than #2241 sub-branch of this also growing quickly these days.

thx i will take a look!

**Comment by aviczhl2** [comment]
325 now, new country of New Zealand

**Comment by FedeGueli** [comment]
I suggest to designte this one @corneliusroemer it is a late branch but still as fit as fit as the others and already widespread.

**Comment by aviczhl2** [comment]
392, Greece

**Comment by aviczhl2** [comment]
422, Germany, Singapore

**Comment by aviczhl2** [comment]
451, Turkey

**Comment by aviczhl2** [comment]
Designated XBB.2.3.19

**Comment by FedeGueli** [comment]
via https://github.com/cov-lineages/pango-designation/commit/083357e61c50408ca2b4230055a0fade243ecb18
