### ISSUE TITLE
XBB.1.9.1 sublineage defined by orf1a:L349F, originate in France, 138 seqs at 2023-05-05

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#1947]
Sublineage of: xbb.1.9.1*
Additional Mutations: G1312T/orf1ab:L349F,C28462T->A11782G->C9073T
Gisaid Inquiry:G1312T, A11782G
Note: One could apply additional requirement of G5720A, which would truncate one sample:
EPI_ISL_17386372, but because this sample contains 11956T of xbb.1.9.1 but lacks A28447G of XBB.1.16, it is very likely a valid sample just with bad result

Earliest Lineage: EPI_ISL_17396812 France, 2023-03-01
Latest Lineage:EPI_ISL_17524786 France, 2023-04-10
Distribution: 94 total samples, 1 China,  1 French Guiyana, 1 UK, 1 Spain, 1 Germany, the rest 89 France
 https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14fd8_532880.json?f_userOrOld=uploaded%20sample&label=id:node_4696733
Importance: This is reaching a significant share of recently uploaded sequences in France （2.57% in covspectrum）, and it clearly has a growth （59%，35-83% with covspectrum， my personal estimation of maybe 80% each week) and some international spread

**Comment by krosa1910** [comment]
Got to Canada, 2 seqs, also +6 seqs at France, making 102 Total

**Comment by krosa1910** [comment]
France just uploaded a horde of sequences today, +14 to G1312T, A11782G. Now it has 8 overseas sequence in 7 countries, and 114 French sequences

**Comment by krosa1910** [comment]
just noticed that nearly all of these variants has additionally acquired C9073T. If using all four nucleotide in the inquiry, this would give one less/122 sequences, so I believe that the definition should include all four mutations.

**Comment by krosa1910** [comment]
@thomasppeacock @corneliusroemer WIth the recent update this week, this got to 6 seq in French Guiana in April, which is a lot considering it to be a small province of France with only 50 collected seqs this year . Could you look at it sometime?

**Comment by corneliusroemer** [comment]
@krosa1910 50 sequences isn't maybe so few given that "According to the World Bank's latest data as of 2021, the population of French Guiana is estimated to be around 305,000 people." ;) 

50 seqs from there this year is like 200k sequences from China (there are only 15k)

But yeah it's Africa which has one of the lowest sequencing intensities. I've designated it now, it's clearly a notable FL lineage - thanks for the proposal

**Comment by krosa1910** [comment]
> @krosa1910 50 sequences isn't maybe so few given that "According to the World Bank's latest data as of 2021, the population of French Guiana is estimated to be around 305,000 people." ;)
> 
> 50 seqs from there this year is like 200k sequences from China (there are only 15k)
> 
> But yeah it's ~Africa~ South America which has one of the lowest sequencing intensities. I've designated it now, it's clearly a notable FL lineage - thanks for the proposal

Thanks for correcting me, I now realize that this is a decent number with population adjustment. But my major point is that it probably reached a higher stake at FG rather than France mainland ( I believe it is ~100 in more than 17k in France so 0.6% in 2023 cumulatively) and here it is 12%. I did not realize that FG has such a small population (maybe because it is not that small on map), and speaking seq to population ratio it is similar to Italy (50/300k versus 10000/60M).

**Comment by alurqu** [comment]
@corneliusroemer The Git commit log and lineage_notes.txt have this lineage distinguished by ORF1a:L394F instead of ORF1a:L349F. The "4" and "9" got swapped.
