### ISSUE TITLE
Proposal to withdraw lineage XBC.1.6.1 due to the defining mutation ORF1b:N498I being likely an artifact

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1948]
![1](https://user-images.githubusercontent.com/115189228/233860009-8803ecc0-684d-4b82-9405-32377757e33e.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=ORF1b%3AN498I&
![2](https://user-images.githubusercontent.com/115189228/233860017-892ae9f9-0aa8-477a-9121-c79d8178a1ad.png)
https://cov-spectrum.org/explore/Australia/AllSamples/AllTimes/variants?variantQuery=ORF1b%3AN498I&

**Comment by corneliusroemer** [comment]
Resolved in [b33756e](https://github.com/cov-lineages/pango-designation/commit/b33756ef8e33a8709f284ecbed3e66aabff41305)
