### ISSUE TITLE
Another XBB.1.5* with S:456L, 90  seqs at 2023-05-03

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#1949]
Not Clear Sub-lineage pattern within xbb.1.5*, so I would propose as of now it is just a descendent of the total family
Defining Mutations: xbb.1.5*-〉Orf1a:S2822P/T8729C -〉+S:F456L/T22928C
Gisaid Inquiry: using the two defining mutation plus any restriction to xbb.1.5 or uploaded after 2023-Jan suffices

Lineage Collection: EPI_ISL_16978334, EPI_ISL_17007938, EPI_ISL_17017398,
EPI_ISL_17164892, EPI_ISL_17184221, EPI_ISL_17208855,
EPI_ISL_17232441, EPI_ISL_17232446, EPI_ISL_17241909,
EPI_ISL_17241934, EPI_ISL_17241943, EPI_ISL_17241964,
EPI_ISL_17241988, EPI_ISL_17242062, EPI_ISL_17242072,
EPI_ISL_17242092, EPI_ISL_17242112, EPI_ISL_17245727,
EPI_ISL_17245786, EPI_ISL_17245955, EPI_ISL_17284249,
EPI_ISL_17284252, EPI_ISL_17284260, EPI_ISL_17284455-17284456,
EPI_ISL_17284462, EPI_ISL_17284466, EPI_ISL_17296734,
EPI_ISL_17298943-17298944, EPI_ISL_17299126, EPI_ISL_17299141,
EPI_ISL_17363149, EPI_ISL_17363304, EPI_ISL_17363414,
EPI_ISL_17364077, EPI_ISL_17372888, EPI_ISL_17372968,
EPI_ISL_17373567, EPI_ISL_17409751, EPI_ISL_17418237,
EPI_ISL_17426624, EPI_ISL_17428866, EPI_ISL_17446707,
EPI_ISL_17470298, EPI_ISL_17470323, EPI_ISL_17470517,
EPI_ISL_17470622, EPI_ISL_17484889, EPI_ISL_17484892,
EPI_ISL_17485097, EPI_ISL_17525559, EPI_ISL_17526203,
EPI_ISL_17526798, EPI_ISL_17526894

Earliest Sequence:  EPI_ISL_17007938, England 2023-02-06
Latest Sequence: EPI_ISL_17526894, Texas, US 2023-04-10
Distribution: 2 Austria, 46 England, 1 Netherland, 1 Germany, 1 Spain, 4 US (1 CA, 2NY, 1 TX)
After checking Yunlong Cao's twitter upon possible immune escape boost by S:456L, I decided to search upon it. Besides trees that are known to me (FD.1.1,FE.1,XBB.1.5.10), I discovered three new trees.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1b5a5_6081b0.json?f_userOrOld=uploaded%20sample (Large Tree, used to infer the structure)
<img width="831" alt="CCA6F3B9-2C91-4DDD-852F-41B0E3DC14A1" src="https://user-images.githubusercontent.com/131021067/233908037-df8ce521-e111-4ada-9ee5-6138003d09e9.png"> 
The most interesting one being the green one was a sublineage of XBB.1.9.2, and although I did not found an issue with it, I though that it was possibly the recently designated EG.5. However, I may propose it to be enlarged in a later issue.
The pink and blue trees, however, seem undesignated. The pink one is boring because it is solely developed in England, and I learned not to trust England sequence numbers. Yet the blue one seems more interesting, as it shows some spread.
Thus, I would like to propose the blue tree defined by S:456L and Orf1a:S2822P
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_334dc_68d620.json?f_userOrOld=uploaded%20sample
<img width="809" alt="D8DA8FA6-3D42-40D7-8BA1-C786E74E8368" src="https://user-images.githubusercontent.com/131021067/233905268-601968df-e29c-4a6c-8ffe-70ac8103952a.png">

**Comment by krosa1910** [comment]
Not directly Related to this proposal, but I just realized that I mistakenly categorize a polyphyletic group into one (the green one). Instead of acquiring the common T22928C as in other trees, the upper branch of green group acquired T22930A, while the bottom branch acquired the regular T22928C. This is interesting.

**Comment by FedeGueli** [comment]
Hi @krosa1910 could you add the usher tree link to your proposal please?

**Comment by krosa1910** [comment]
> Hi @krosa1910 could you add the usher tree link to your proposal please?

FIxed ( I was very tired and forgot to edit it in the standard way last night).

**Comment by FedeGueli** [comment]
thz no worries.

**Comment by krosa1910** [comment]
summary now: 2 Austria (no change), 49 England (+3), 1 Finland (New, detected 04-03, submitted today), no change  for 1 each Nethenland, Germany, Spain , 1 Singapore (New, detected 04-14, submitted today), 7US (1 CA, 1 TX no change, 5 NY +3 with similar detection parameter)

**Comment by krosa1910** [comment]
3 new sequences uploaded today, 1 england (but still earlier than the "ending time"), 1 france and 1 austria.
I suppose it is really something outside england, just ignore the island country origin may help us analyze its growth better.

**Comment by krosa1910** [comment]
recent spread to scotland and South Korea, 2 each

**Comment by krosa1910** [comment]
+3, 2 England, finally passing the "04-04 barrier" and one updated yesterday in Spain that I did not catch.

**Comment by FedeGueli** [comment]
@krosa1910 just spotted another XBB.1.5*N:S194P*S:F456L(T22928C) from Spain N_S194P, Spike_F456L it is something like 3% of spanish samples after 10th April likely just a cluster: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24d06_d0e730.json?c=country&label=id:node_5902649

**Comment by krosa1910** [comment]
> @krosa1910 just spotted another XBB.1.5_N:S194P_S:F456L(T22928C) from Spain N_S194P, Spike_F456L it is something like 3% of spanish samples after 10th April likely just a cluster: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24d06_d0e730.json?c=country&label=id:node_5902649

This is very interesting, however, this one lacks 17124C, so I doubt it being part of XBB.1.5( although it seemed that cornelius still kept T17124C out of XBB.1.5 definition)

**Comment by krosa1910** [comment]
also get to switzerland, so +2 for total number to be 75 now. I guess it is good at spreading to foreign countries.
