### ISSUE TITLE
Proposal for another 3 potential new lineages circulating in Mexico, the US and Europe

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#195]
**Proposed new lineage 1**
Potential sublineage of B.1 (26 sequences in the US, probably already died out though, and 5 in Mexico still likely circulating)
**Earliest sequence**: 2020/12/18 (US - CA)
**Most recent sequence**: 2021/6/18 (Mexico)
**Mutations**:
**N**: D144Y, S206A
**ORF1a**: T265I, S1106G, S3946L
**ORF1b**: P314L, D1183Y, P1325S
**ORF3a**: Q57H
**ORF9b**: M8T
**S**: S13I, G142C, 144del, R346K, L452R, L455F, N501Y, D614G
**Genomes:**
EPI_ISL_962655, EPI_ISL_1011358, EPI_ISL_1069045,
EPI_ISL_1081591, EPI_ISL_1132968, EPI_ISL_1811886,
EPI_ISL_1812175, EPI_ISL_1812561, EPI_ISL_1812683,
EPI_ISL_1812824, EPI_ISL_1812891, EPI_ISL_1813007,
EPI_ISL_1813276, EPI_ISL_1814419, EPI_ISL_1814576,
EPI_ISL_1815029, EPI_ISL_1815077, EPI_ISL_1816397,
EPI_ISL_2628530, EPI_ISL_2835540, EPI_ISL_2855696,
EPI_ISL_2882119, EPI_ISL_2942422, EPI_ISL_2942430-2942431,
EPI_ISL_2977977, EPI_ISL_3063894
**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/130324492-b25970e4-ca99-49d9-a985-80021e76155e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3128e_fca30.json?c=gt-S_346

**Proposed new lineage 2**
Potential sublineage of B.1.517 (8 sequences in US-CT)
**Earliest sequence**: 2020/5/3 (US - CT)
**Most recent sequence**: 2021/7/25 (US - CT)
**Mutations**:
**M**: I82V
**N**: S206F
**ORF1a**: T265I, A541S, G989V, H1580Y, D2136G, S4106G
**ORF1b**: P314L, P1161S, P2633S
**ORF3a**: Q57H
**ORF8**: S67F
**S**: W64C, Q493K, N501T, Q613H, D614G, T1027I
**Genomes:**
EPI_ISL_2035047, EPI_ISL_2159603, EPI_ISL_2501697, EPI_ISL_2860316, EPI_ISL_2716246, EPI_ISL_2776212, EPI_ISL_3133023, EPI_ISL_3370176
**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/130327916-d9fc4d85-4ade-4298-ba2e-ad951f0a5848.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2080c_ed110.json?c=gt-S_501,613,1027

**Proposed new lineage 3**
Currently classified as either B.1.617.2 or B.1.1.7 (11 in Europe and 3 in the US)
**Earliest sequence**: 2020/5/16 (Scotland)
**Most recent sequence**: 2021/7/19 (Sweden)
**Mutations**:
**M**: I82T
**N**: D3L, D63G (11/13 sequences), R203K, G204R, S235F
**ORF1a**: T1001I, A1306S (10/13 sequences), I2230T, P2287S (10/13 sequences), V2930L (11/13 sequences), 3675/3677del
**ORF1b**: P314L
**ORF3a**: S26L
**ORF7b**: T40I (11/13 sequences)
**ORF8**: Y73C (7/13 sequences)
**S**: 69/70del, 144del, L452R (12/13 sequences), T478K, A570D, D614G, P681R, D950N, S982A
**Genomes:**
EPI_ISL_2636922, EPI_ISL_3186311, EPI_ISL_2726841, EPI_ISL_2833755, OU285550.1, OU312766.1, OU330112.1, OU436541.1, OU346479.1, EPI_ISL_3186325, EPI_ISL_3186453, EPI_ISL_3138280, EPI_ISL_2566565, EPI_ISL_2876184
Evidence:
![image](https://user-images.githubusercontent.com/86835836/130337488-7e671def-d519-443b-a99b-9998341ad957.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_578e7_ee9180.json?c=gt-N_204

**Comment by thomasppeacock** [comment]
That third lineage looks really reassortant-y. Nearly all the substitutions it has are either from B.1.1.7  or B.1.617.2 but potentially with multiple break points?? ie N is clearly from B.1.1.7, as is ORF1a I think, ORF3a is 617.2-like while Spike is complete mix:

69/70del, 144del, -B.1.1.7
L452R T478K, -Delta
A570D, - B.1.1.7
P681R, D950N, - Delta
S982A - B.1.1.7

If this is a reassortment it would have to have at least 6+ different break points which I guess is possible...

**Comment by babarlelephant** [comment]
Lineage 3 looks like a garbage lineage to me (many NNN and problem with sequencing pipeline). A recombinant should stand on a relatively long branch, not produce a continuum of random mutations/reversions seen in the big lineages.

**Comment by chrisruis** [comment]
Thanks @c19850727. We need new lineages to be epidemiologically distinct and be of a reasonable size

Proposed lineage 1 does contain 31 sequences total in the latest UShER tree but most of these are from early 2021 with only 4 more recent sequences from Mexico in June. Therefore in recent context, this clade is too small to warrant a designation at this stage

Proposed lineage 2 again is rather small with only 10 sequences from the USA and we therefore haven't designated this at this stage

We haven't designated proposed lineage 3 due to the issues outlined by @thomasppeacock and @babarlelephant 

Thanks again for submitting
