### ISSUE TITLE
Sister Group of EG.5 being probably successful in Israel, 98 seqs total at 2023-06-01

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#1950]
Sublineage of: XBB.1.9.2
Mutations Acquired: Seems to be simply T22928C
Gisaid Inquiry: A16878T( to identify it as 1.9.2),22928C
Lineage Collections: EPI_ISL_17256318, EPI_ISL_17344757, EPI_ISL_17349171,
EPI_ISL_17418267, EPI_ISL_17422205, EPI_ISL_17469602,
EPI_ISL_17469700, EPI_ISL_17470513, EPI_ISL_17483735,
EPI_ISL_17483758, EPI_ISL_17483773, EPI_ISL_17483792,
EPI_ISL_17483821, EPI_ISL_17483838, EPI_ISL_17483857,
EPI_ISL_17483919, EPI_ISL_17483932, EPI_ISL_17483968,
EPI_ISL_17484004, EPI_ISL_17484007, EPI_ISL_17516620,

Earliest: EPI_ISL_17256318 Germany 2023-03-09
Latest:   EPI_ISL_17483857 Israel 2023-04-04
Distribution: 1 Canada, 1 England, 1 France, 4 Germany, 1 Netherland, 13 Israel
As what I described in #1949 , when checking trees with S:456L, I discovered three medium trees. The last of them is a tree within xbb.1.9.2. I was trying to propose it but later I found that some of its sequences are already proposed in EG.5. 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1b5a5_6081b0.json?f_userOrOld=uploaded%20sample （Total Structure of the tree with F456L）

Yet, what I initially naively treated as a "tree" was actually an agglomeration of two trees. L is an amino with 6 possible codon, and three such codon series are easily accessible form the triple U codon series from 22928-22930. The transition at 22928 from T to C is easier, and that's why it was chosen by FE.1,FD.1.1 and XBB.1.5.10, but EG.5 chose much rarer T22930A. 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3dab1_619c30.json?f_userOrOld=uploaded%20sample （EG。5 Tree）
However, a smaller tree existed below EG.5's tree, and that tree originate from the familiar T22928C path. Furthermore, there is evidence to suggest that it reach good share in Isarel that is far from Germany as where it could originate from,  and could prove to be successful.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_3dab1_619c30.json?f_userOrOld=uploaded%20sample （Small Tree，not sure why usher did its frequent wrong job of adding outgroup sequence）
<img width="847" alt="79113D8C-8B1B-4327-B5B0-517C14182387" src="https://user-images.githubusercontent.com/131021067/233913174-85a7b300-bc7a-4503-9a01-edaeeb4505e5.png">

<img width="880" alt="4181EE7A-B897-49E9-9E9F-EBD548638A50" src="https://user-images.githubusercontent.com/131021067/233913157-46b293a6-fa66-4a19-9307-d1c9046f8226.png">

<img width="849" alt="C7670D58-9E5D-4B2B-A3F4-9562D074D8F1" src="https://user-images.githubusercontent.com/131021067/233913140-fcc49164-195c-4c05-a027-5c96a635dfdc.png">

**Comment by FedeGueli** [comment]
@krosa1910 great catch, could you add the usher tree link please to each of your proposal? it would be much easier to first check the lineage. thx

**Comment by FedeGueli** [comment]
@krosa1910 did you find the original EG.5 issue? It is #1918 and it contains two more sublineages of XBB.1.9.2 with 456L / T22928C

**Comment by BorisUitham** [comment]
Yes, three lineages were described but only the biggest was designated. I also noticed the difference in nucleotide but only mentioned it shortly. I wonder what the ratio between the two nucleotides are across various 456l lineages

**Comment by FedeGueli** [comment]
@BorisUitham i suggest to open new issue for the other teo if you see they are growing too

**Comment by BorisUitham** [comment]
@FedeGueli I think this proposal is that already. I see the second biggest (israel+uk) and third biggest (germany, france, netherlands) are combined in this proposal, I found them as separate. I cant check right now if they are actually two different trees, but the difference was basically q146k in the german+french+dutch ones which sometimes is an artefact, right?

**Comment by krosa1910** [comment]
> Yes, three lineages were described but only the biggest was designated. I also noticed the difference in nucleotide but only mentioned it shortly. I wonder what the ratio between the two nucleotides are across various 456l lineages

I quoted that transitions in general are easier than transversion, so applying that conclusion to F456L, it means that the transversion T22930A would be less likely than T22928C. I think this is also clear from the fact that 22928C did arise multiple times with decent success (early 1.5.10, later FD.1.1 and FE.1 both reaching borderline success, growth comparable with EG.1 which I consider to be a great variant under monitor) , while it seems first time that T22930A is booming with EG.5. But for the virus duplication the effect would be similar, and EG.5 and this proposal seems to have advantage of arising in the already successful XBB.1.9.2 with additional good mutations. (I have tried to conduct comparisons of the two variants under 1.9.2, both is capable of growing at two digit rates, that makes them probably even comparable with the faster lineage we currently find, like 1.16 and  2.3.2)

**Comment by alurqu** [comment]
> > Yes, three lineages were described but only the biggest was designated. I also noticed the difference in nucleotide but only mentioned it shortly. I wonder what the ratio between the two nucleotides are across various 456l lineages
> 
> I quoted that transitions in general are easier than transversion, so applying that conclusion to F456L, it means that the transversion T22930A would be less likely than T22928C. I think this is also clear from the fact that 22928C did arise multiple times with decent success (early 1.5.10, later FD.1.1 and FE.1 both reaching borderline success, growth comparable with EG.1 which I consider to be a great variant under monitor) , while it seems first time that T22930A is booming with EG.5. But for the virus duplication the effect would be similar, and EG.5 and this proposal seems to have advantage of arising in the already successful XBB.1.9.2 with additional good mutations. (I have tried to conduct comparisons of the two variants under 1.9.2, both is capable of growing at two digit rates, that makes them probably even comparable with the faster lineage we currently find, like 1.16 and 2.3.2)

The observational results of Bloom and Neher also show that, as you expected, across all clades T-to-C transitions occur at a faster rate than T-to-A transversions. See https://github.com/jbloomlab/SARS2-mut-spectrum/blob/main/results/synonymous_mut_rates/rates_by_clade.csv

**Comment by FedeGueli** [comment]
With T22928C I see: 
1 a singlet from Canada defined by orf1a:P971L
2 a 6 seqs lineage from Germany with S:Q146K
3 a 8 seqs from Israel et al with C1684T and C17766T plus Orf6:Y49H

with T22930A i see:
1 EG.5 that notably has gained N:L161F
2 one singlet from Indonesia with many mutations S:Q52H,N:G215S,Orf1a:A690V, orf1a:A3143V
with a quadruplet at the end of Orf1b tht makes me think it could be a TRS (cc @ryhisner EPI_ISL_17308775)

**Comment by krosa1910** [comment]
@BorisUitham @FedeGueli 
Gisaid just uploaded a very old sequence:EPI_ISL_17537558 that is collected in 02-14, Canada but submitted yesterday.
 I thought that this could be a typo from 04-14 but was not sure. Could you help me decide upon that. 
This would mean a potential change of earliest lineage for this proposal, and even #1918 as it is earlier than the Indonesian lineage of EG.5( although we already know that the proposal is polyphyletic)

**Comment by krosa1910** [comment]
I think this proposal is linked with the designation of EG.6/EG.6.1. @corneliusroemer could you add the tag to this clade to make it clear

**Comment by FedeGueli** [comment]
Designated EG.6.1 via https://github.com/cov-lineages/pango-designation/commit/d0acddde41b45dda93204c9ab37d0de3c4cbd186
cc @InfrPopGen 

@krosa1910 could  younthe next time put the main mutation in the headline. I scrolled back to search this one but missed to find it

**Comment by FedeGueli** [comment]
@BorisUitham the third lineage here is still ongoing?

in that case please pre propose it in the other page.

**Comment by krosa1910** [comment]
> Designated EG.6.1 via [d0acddd](https://github.com/cov-lineages/pango-designation/commit/d0acddde41b45dda93204c9ab37d0de3c4cbd186) cc @InfrPopGen
> 
> @krosa1910 could younthe next time put the main mutation in the headline. I scrolled back to search this one but missed to find it

At the time I mentioned this，EG.5 is a well known concept （still is I would say）and I thought using it as reference for S：456L would be nice. I would usually use main S mutation followed by orf ones now.
