### ISSUE TITLE
XBB.4(or XBB+S:K444R) with S:478R, S:486P, Orf9b:I19V, Orf8:F120V,I121L (7 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1951]
I spotted an XBB.4(XBB+Orf1a:G82D+S:K444R) sub-lineage with the common  S:478R, S:486P combo together with some other mutations.

Sub-lineage of: XBB.4
Mutations on top of XBB.4: A22995G(S:478R),T23018C(S:486P), A28338G(Orf9b:I19V,N:D22G), C2065T, T28251G(Orf8:F120V),A28254C(Orf8:I121L)
GISAID query: C2065T,A28338G
No. of seqs: 7( USA 4(1 from Qatar) Australia 1 India 2)
First seq: 
EPI_ISL_17358228(USA from Qatar) 2023-3-20
Latest seq:
EPI_ISL_17486810(USA) 2023-4-3
PS. The two Indian seqs don't have their date specified. 

Sequences:
EPI_ISL_17358228, EPI_ISL_17406213, EPI_ISL_17478185,
EPI_ISL_17478268, EPI_ISL_17486810, EPI_ISL_17528292,
EPI_ISL_17528321

Usher places on XBB.3 but have the XBB.3 defining mutation reverted back and XBB.4 defining mutation added on. Without any branch specific mutation(except for Orf8:F120V,I121L which are common in all XBBs) , it should be sub-lineage of XBB.4.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice8_genome_33eeb_666d90.json)
<img width="1378" alt="Screen Shot 2023-04-24 at 19 59 02" src="https://user-images.githubusercontent.com/10445944/233989847-f136ff3d-d575-4a53-891b-cb854b1f004c.png">

**Comment by FedeGueli** [comment]
It has 510A that is defining both of XBB.3 and XBB.4 and it has reverted the orf1b:1998 mutation defining XBB.3 while it has S:444R defining of XBB.4, but also highly homoplasic in BA.5.2 and the orf8:120-121 that is homoplasic and @ryhisner could be interested in.
To me it is not neither XBB.3 or XBB.4 but a new XBB branch (belonging to the same 510A branch as .3 .4 .5 .6) circulating at low levels in some area in India as WB

**Comment by AnonymousUserUse** [comment]
> To me it is not neither XBB.3 or XBB.4 but a new XBB branch

Why do you think it is not a sublineage of XBB.4?

**Comment by corneliusroemer** [comment]
US-NY sequences is annotated as "Traveler from Qatar"

I agree that this doesn't look like an XBB.3 due to the reversion of XBB.3 defining mutation.

It'd be XBB.4 unless we find some ancestors that are in another lineage.

This is by genotype like XBB.1.16, but lacking the S:180, S:252V, ORF8:8*, and having S:444R in addition.

Probably not something much faster than XBB.1.16 so we can wait maybe for a week for new sequences to come in before designating.

**Comment by aviczhl2** [comment]
No new seqs in 2 week's time. So close it.
