### ISSUE TITLE
Potential recombinant of XBB.1.9.2* and XBB.1.22* emerging worldwide (152 seqs, 19 countries, 145 seqs contain S:Q613H)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1954]
I spotted an interesting branch under XBB.1.9.1. 

It is likely a recombinant of XBB.1.9.2* and XBB.1.22*.

Mutations on top of XBB.1.9.1: A16878T(one of XBB.1.9.2's defining mutation), A5720G(Orf1a:S1819G reversion),T11956C(reversion)
GISAID query: T23018C,T28297C,C12789T,-G5720A,A16878T,-A27507C,-C11956T (and exclude low coverage seqs)
cov-spectrum query: T23018C,T28297C,C12789T,5720G,A16878T,27507A,11956C
First seq: EPI_ISL_17372704(Indonesia) 2023-2-25
Latest seq: EPI_ISL_17539481(Hong Kong) 2023-4-18
No. of seqs: 27( Australia 4 Denmark 2 England 2  Indonesia 2 Israel 4 Italy 1 Malaysia 5 California 2 New York 1 Shanghai 2 Hong Kong 1 Jiangsu 1)

Sequences:
EPI_ISL_17199416, EPI_ISL_17208615, EPI_ISL_17241589,
EPI_ISL_17298603, EPI_ISL_17343448, EPI_ISL_17359095,
EPI_ISL_17372704, EPI_ISL_17373572, EPI_ISL_17408858,
EPI_ISL_17417167, EPI_ISL_17417516, EPI_ISL_17417535,
EPI_ISL_17446210, EPI_ISL_17446373, EPI_ISL_17467968,
EPI_ISL_17469964, EPI_ISL_17483732, EPI_ISL_17483822,
EPI_ISL_17502924, EPI_ISL_17502961, EPI_ISL_17505630,
EPI_ISL_17516251, EPI_ISL_17517431, EPI_ISL_17517526,
EPI_ISL_17536899, EPI_ISL_17536904, EPI_ISL_17539481,

I tend to think it is an artefact reversion of XBB.1.9.2, however they do have 5720G and 27507A, not Ns. 
And the time/geographical distribution don't support it being an artefact(if artefact it shall not have timely growth advantage against XBB.1.9.1, and shall not be distributed worldwide with each country having a few seqs. )And 23 of them also have S:Q613H, if artefact it shall not have that large proportion of S:Q613H. 

So I guess it is a sandwich recombinant of XBB.1.9.2*(for having A16878T) and XBB.1.22*( as it doesn't have A27507C and A5720G, but has T28297C). 12789-27506 is XBB.1.9.2, and before/after is XBB.1.22(or maybe others).

Maybe it is a recombinant of sth. else, or a collection of some different recombinants put together, but there's currently no(or sth. I missed) evidence for these assumptions. 

**I'm not quite confident with my analysis of this variant. But it is clear that it is not XBB.1.9(due to having its defining mutation reverted), unlikely an artefact, and is growing(mainly because of S:Q613H), so it deserves being taken a look at.**

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_cea7_776520.json?f_userOrOld=uploaded%20sample)

<img width="1384" alt="Screen Shot 2023-04-25 at 15 01 02" src="https://user-images.githubusercontent.com/10445944/234199169-fc870074-3f8d-4488-9883-24c15655961d.png">

<img width="1388" alt="Screen Shot 2023-04-25 at 15 07 16" src="https://user-images.githubusercontent.com/10445944/234200421-a01d265a-db72-48e2-bf49-7b5a5368e590.png">
(the lower yellow branch of 5720 reversion is the proposed branch)

[cov-spectrum](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=XBB.1.9.1*&nucMutations1=T28297C%2CC12789T%2CA16878T%2C27507A%2C5720G%2CT23018C&analysisMode=CompareToBaseline&)

<img width="1196" alt="Screen Shot 2023-04-25 at 15 03 40" src="https://user-images.githubusercontent.com/10445944/234199646-dffe11b7-6e0c-49f4-b590-3c198440127e.png">

**Comment by aviczhl2** [comment]
Suddenly Italy and Finland gets 1 more seq each.

**Comment by aviczhl2** [comment]
@FedeGueli  a clearer list:

>  A5720G reversion from XBB.1.9 defining
C12789T present defining of XBB.1.9 and XBB.1.23
A16878T present defining of XBB.1.9.2
T23018C Present defining of XBB.1.9*+486P
G23401T partially(24/28) present defining of XBB.1.9.2.1 (EG.1)
A27507C absent defining of XBB.1.9.2
T28297C present defining of XBB.1.9, XBB.1.22, XBB.1.26, XBB.1.25
C28928T absent defining of (EG.1)
T10663C absent defining of XBB.1.26
G487T,C673T absent defining of XBB.1.25

**Comment by AnonymousUserUse** [comment]
With only two mutations reverted, it is hard to say which lineage is involved in the recombination event. So I would rather designate it as a sublineage of XBB.1.9.2 (if it qualifies for a designation), which would also simplify the way to track this lineage.
See also https://github.com/cov-lineages/pango-designation/issues/1538.

**Comment by aviczhl2** [comment]
new seqs from Austria, South Korea, Japan and Sichuan province of China. Total 41.

**Comment by aviczhl2** [comment]
45 seqs and in Thailand

**Comment by aviczhl2** [comment]
Still suggesting to designate as X* (and X*.1 for S:Q613H), I don't think designating this as EG.* will simplify anything,  instead EG.* will just make things more complicated.

**Comment by AnonymousUserUse** [comment]
> Still suggesting to designate as X* (and X*.1 for S:Q613H).
> 
> I don't think designating this as EG.* will simplify anything, instead EG._(or FL._) will just make things more complicated, as doing so will basically making XBB.1.9 lose a clear definition and struggling on requiring 5720 or not.

Problem with the designation of a recombinant lineage is that it is hard to monitor a recombinant lineage before it grows. If we designate this as X*, it will not be considered if we query XBB* + S:484P + S:Q613H. Besides, some public health institutions, including China CDC, do not monitor the recombinant lineage at all before it reaches certain percentage. For exemple, XBL is not regarded as a variant of concern by China CDC though XBB involves in the lineage and it grows quickly.

Reversions can occur, even without recombinant event. I do not think it would be troublesome to track this lineage or it would be difficult for pangolin to distinguish this lineage under the designation with XBB.1.9.2*. (@AngieHinrichs Do you agree?)

**Comment by corneliusroemer** [comment]
How many reversions would this have from EG.1? 3: A5720G, A27507C, C28928T? That's unlikely to be non-recombinant reversions.

Why are you so sure that the breakpoint for XBB.1.9.2 -> non-XBB.1.9.2 is after the RBD?

I think this recombinant could be interesting for @c19850727 to look at - I feel the above discussion isn't quite complete yet. 

Agree with @aviczhl2, there's no problem with tracking (@AnonymousUserUse) - we shouldn't make designations based on how a single CDC defines their VOCs, that's up to them.

Letting it grow a bit more doesn't harm much, things will become clearer.

**Comment by FedeGueli** [comment]
@josetteshoenma could you check breakpoints with Sc2rf please if u have time?

**Comment by AnonymousUserUse** [comment]
> How many reversions would this have from EG.1? 3: A5720G, A27507C, C28928T? That's unlikely to be non-recombinant reversions.

There are only two reversions from XBB.1.9.2, though.

> Agree with @aviczhl2, there's no problem with tracking (@AnonymousUserUse) - we shouldn't make designations based on how a single CDC defines their VOCs, that's up to them.

You have used the argument of tracking in issue #1538 for the designation as a sublineage of XBC.2, where there are also reversions and a lineage that might have been involved in the recombination event was proposed. So I came across the idea to designate as a sublineage of XBB.1.9.2 and gave several examples for difficult tracking.

In my view, if there are no more than three reversions, the lineage involved in the recombination is likely to be unclear, the new lineage may inherit most of the characteristics, and the designation as a sublineage may also be justified, which simplifies tracking at the same time. If there are more reversions, the designation as a recombinant lineage would be necessary.
The technically correct way is, of course, to designate all lineages that are considered more likely to be involved in recombinant events as recombinant lineages.

**Comment by aviczhl2** [comment]
61 seqs,new country of Germany.

**Comment by aviczhl2** [comment]
102 seqs and in Spain.

**Comment by FedeGueli** [comment]
@corneliusroemer @thomasppeacock @InfrPopGen @AngieHinrichs i siggest to designate this one. well over 50seqs steadily growing

**Comment by aviczhl2** [comment]
113 seqs now, new country of Singapore.

**Comment by aviczhl2** [comment]
141 seqs, appearing in Sweden and more provinces in China.

**Comment by Over-There-Is** [comment]
Indonesia+1, Malaysia+1, Australia+1, totally 144 seq.

**Comment by FedeGueli** [comment]
@corneliusroemer has designated this one XBB.1.42  starting a step further in the tree from S:Q613H not supporting the recombination hypothesis ( hard to prove or disprove maybe )

**Comment by FedeGueli** [comment]
cc @InfrPopGen

**Comment by corneliusroemer** [comment]
Designated XBB.1.42

When designating I didn't quite realize I had looked at this in the past. It may well be a recombinant, but since it could be explained by one reversion or one convergent mutation a non-recombinant history is also plausible. Giving this a non-recombinant name keeps things easier for us, no need to remember yet another recombinant alias.
