### ISSUE TITLE
look-up function to de-aliasing the pango lineages or to WHO label?

### ISSUE THREAD

**Issue by rafalopespx** [cov-lineages/pango-designation#1956]
Hello there, 

Is there any function, or table, to de-aliasing the pango lineages into its before designated whole lineage?

Or a function, or a table, that can relates the now aliases lineages to WHO label?

Thanks!

**Comment by rafalopespx** [comment]
I just saw this after posting my issue, but this doesn't resolve the problem in totally, because more recent aliases are named after less recent aliases

**Comment by AnonymousUserUse** [comment]
In https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.js, the whole lineage name is shown.

**Comment by rafalopespx** [comment]
The link is broken

**Comment by AnonymousUserUse** [comment]
Edited

> The link is broken

**Comment by rafalopespx** [comment]
I was talking about things like this one:

 "XBB": ["BJ.1","BM.1.1.1"],
 
 Here, the XBB is an alias of aliases, I have to re-run several times the de-aliasing system to outcome that is the whole lineage name for XBB, which be something like, "B.1.1.529.2.10.1"X"B.1.1.529.2.75.3", so what is the entire name of this kind of pango lineage?

**Comment by corneliusroemer** [comment]
>"XBB": ["BJ.1","BM.1.1.1"]

This is not an alias, it's a recombinant.

**Comment by rafalopespx** [comment]
Right, so I don't have a whole lineage name for it, right?

Because it bears part from BJ.1 and BM.1, sorry I'm not a virologist, so maybe I'm mixing up concepts.

My problem is to figure out a way of easily classifying the pango lineages into just major categories, defined with some logic, like, all the BA.1 together, all the BA.2 together, and so on, all the recombinants together. The problem has been, on have a not totally manual coding way to this job, now I'm building these categories greping into the pango lineages, but I always forget some alias out of a category and end up miscategorizing them

**Comment by AnonymousUserUse** [comment]
I do not think there is an official entire/unaliased name for recombinant lineages. If you want to have the name in this form, you can run iteratively.
The use of such forms can become pretty unclear after several iterations. For exemple, EG.1 would become ["B.1.1.529.2.10.1.1","B.1.1.529.2.75.3.1.1.1"].1.9.2.1, and XBL.1 would become ["["B.1.1.529.2.10.1.1","B.1.1.529.2.75.3.1.1.1"].1","B.1.1.529.2.75","["B.1.1.529.2.10.1.1","B.1.1.529.2.75.3.1.1.1"].1"].1. This form is definitively not suitable for human being. Even for computer program, an iteration might also be better than using this form.

**Comment by corneliusroemer** [comment]
I'll close this as it's not something that's directly related to designations and more of a discussion.
