### ISSUE TITLE
CH.1.1.3 (ORF1ab) x EU.1.1.1 (Spike) recombinant (4 seq, 2x FIN, 1x AUT, 1xLTU) 

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1959]
hCoV-19/Lithuania/MB20_0058/2023|EPI_ISL_17394501|2023-03-15
hCoV-19/Austria/AGES-1132452/2023|EPI_ISL_17440454|2023-03-27
hCoV-19/Finland/THL-04321/2023|EPI_ISL_17540601|2023-04-01
hCoV-19/Finland/THL-04355/2023|EPI_ISL_17540630|2023-04-08

<img width="1932" alt="image" src="https://user-images.githubusercontent.com/25161793/234433226-09de568c-faca-4474-aeac-d97285f2f6cf.png">

Somewhat similar to XCC (CH.1.1 x XBB.1.9.1) #1876 

Breakpoint (rough analysis) ~12-15k

CH.1.1.3 part: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=%5B8-of%3AC3796T%2C%09C3857A%2C%09C3927T%2C%09C4586T%2C%09C5183T%2C%09C5869T%2C%09T7225C%2C%09C8895A%2C+A12444G%5D&

EU.1.1 part: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=%5B25-of%3AG15451A%2C%09C15738T%2C%09T15939C%2C%09T16342C%2C%09T17124C%2C%09T17859C%2C%09A19326G%2C+G19851T%2C%09G22200A%09%2CG22317T%2C%09G22577C%2C%09G22599C%2C%09C22664A%2C%09A22790G%2C%09G22895C%2C+T22896C%2C%09G22898A%2C%09T22942G%2C%09T23018C%2C%09T23019C%2C%09T23031C%2C%09G23040A%2C%09C23123T%2C+C25416T%2C%09C25513T%2C%09A26275G%2C%09C27145T%2C%09G27915T%2C%09C29666T%2C%09A29700T%5D&

<img width="2530" alt="image" src="https://user-images.githubusercontent.com/25161793/234433324-a6163fca-4ece-4208-8557-5d6842a18dd6.png">

https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_2ccb4_868ee0.json

Found by looking through today's submissions in Nextclade, noticing odd XCC that had EU.1.1 like Spike

**Comment by JosetteSchoenma** [comment]
Yes. I was monitoring this one with an XCC lookalike query. I think the breakpoint will lay between 12444 and 15939. It still has A12444G from CH.1.1.3 and even though there are a few CH.1.1. with T15939C, almost all EU.1.1 have it. And the only CH.1.1.3 that has the other mutations (see Nextclade sreenshot) does not have T15939C.
I only find the A21910C reversion weird though.
![image](https://user-images.githubusercontent.com/94831035/234718214-bb71d86d-cd60-4c4e-b562-f5e9aa323da9.png)

![image](https://user-images.githubusercontent.com/94831035/234718313-7b7e22ff-598e-476f-aef1-e2895df793d4.png)

**Comment by JosetteSchoenma** [comment]
Another one from Finland.

EPI_ISL_17598103

**Comment by FedeGueli** [comment]
![Schermata 2023-06-26 alle 14 27 04](https://github.com/cov-lineages/pango-designation/assets/87669813/c6e0e039-be3f-45b3-b8ce-44536d91a3b4)

![Schermata 2023-06-26 alle 14 27 37](https://github.com/cov-lineages/pango-designation/assets/87669813/1f794985-affb-4d8f-bc92-9f0a691135d9)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c4c7_983bb0.json?label=id:node_6982801

No new sample but putting here the tree.

**Comment by corneliusroemer** [comment]
Nothing new here: https://cov-spectrum.org/explore/World/AllSamples/Y2023/variants?aaMutations=ORF1a%3A2877N%2CS%3A410V%2CS%3A521S%2CORF3a%3A41F&
