### ISSUE TITLE
Potential new sublineage of B.1.617.2 with Spike A684S in Canada

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#196]
Potential sublineage of B.1.617.2 (25 sequences in Alberta, Canada)
**Earliest sequence**: 2020/8/4
**Most recent sequence**: 2021/8/10
Mutations in addition to B.1.617.2:
**M**: A81S
**N**: S412R
**ORF1a**: A687V, H712Q, V1550F, P1640L, A3209V, V3718A, T3750I
**ORF1b**: M1499I
**ORF8**: 119/120del
**ORF9b**: M8T
**S**: A222V, Q613H, A684S
**Genomes:**
EPI_ISL_3524943, EPI_ISL_3524970-3524971, EPI_ISL_3524986,
EPI_ISL_3525009, EPI_ISL_3525019, EPI_ISL_3525156,
EPI_ISL_3525186, EPI_ISL_3525193, EPI_ISL_3525204,
EPI_ISL_3525211, EPI_ISL_3525219, EPI_ISL_3525230-3525231,
EPI_ISL_3525239, EPI_ISL_3525304, EPI_ISL_3525399,
EPI_ISL_3525406, EPI_ISL_3525412, EPI_ISL_3525414,
EPI_ISL_3525418-3525419, EPI_ISL_3525435, EPI_ISL_3525440,
EPI_ISL_3525453

![image](https://user-images.githubusercontent.com/86835836/130345292-874478da-0b46-4634-b026-81db6ab2ca8b.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4c5ca_1edef0.json

**Comment by babarlelephant** [comment]
Hi, does it deserve a lineage? I don't think A684S is concerning, it seems deleterious and would be able to propagate a bit more thanks to P681H/R.

From what I checked the 500 sequences [Usher subtree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4c5ca_1edef0.json) you are showing may represent 1/20th of the Delta+A222V lineage,

and all but 3 of the >500 sequences with T11938C,A14475G,G29422T are from Canada.

To check the already assigned AY.x lineages, I computed a consensus of each lineage from [lineages.csv](https://github.com/cov-lineages/pango-designation/blob/master/lineages.csv) and I obtained an [usher tree]( https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_8860_210af0.json?c=userOrOld&label=nuc%20mutations:T1191C,T1267C,A5584G,C11514T,C13019T,C22227T) showing that the T11938C sublineage of Delta+A2222V is not assigned yet.

**Comment by FedeGueli** [comment]
Michael Edwards brought to my attention this growing Delta sublineage in Sri Lanka
carrying two spike mutations:
S:A222V, A701S
Here the nexstrain build 
https://nextstrain.org/community/aicbu/ncov/srilanka?c=gt-S_222,701&m=div
![Screenshot_2021-08-23-01-54-02-390_com linkedin android](https://user-images.githubusercontent.com/87669813/130374184-983ed948-2074-4b5b-9dc0-8404fa021ed6.jpg)

I would ask to @babarlelephant  if it could have some relevance as we are not technical, before opening a new issue on it.

**Comment by babarlelephant** [comment]
@FedeGueli According to [this tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4e97d_34b820.json?c=gt-S_1078,701) whose root is at the root of the Delta+A222V lineage, the branch with C331T splits into a USA lineage and your almost purely Sri Lanka lineage (the one with S:A1078S). Some of its sequences are designated as B.1.617.2 in lineages.csv.

**Comment by chrisruis** [comment]
Hi @FedeGueli, we're currently designating AY lineages that are epidemiologically distinct to enable fine-scale virus tracking (outlined at https://www.pango.network/new-ay-lineages/ and https://twitter.com/arambaut/status/1428272566469279749 if you haven't already seen them). So this Sri Lanka lineage looks like an ideal candidate for a new AY. Don't worry about submitting an issue for this one - I'll take a look at it and put the issue in tagging you if it all looks ok. Thanks!

**Comment by FedeGueli** [comment]
Thank you very much @chrisruis ,
So  i opened a new issue #199  on this sublineage:
https://github.com/cov-lineages/pango-designation/issues/199

Thank you @babarlelephant very much for your time.

**Comment by chrisruis** [comment]
Thanks @FedeGueli

**Comment by c19850727** [comment]
> Hi, does it deserve a lineage? I don't think A684S is concerning, it seems deleterious and would be able to propagate a bit more thanks to P681H/R.
> 
> From what I checked the 500 sequences [usher subtree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4c5ca_1edef0.json) you are showing (lineage Delta+A222V+ T11938C,A14475G,G29422T) may represent 1/50th of the Delta+A222V lineage, itself being about 1/12th of Delta.
> 
> and all but 3 of the >500 sequences of this Delta+A222V+ T11938C,A14475G,G29422T lineage are from Canada.
> 
> To check the already assigned AY.x lineages, I computed a consensus of each lineage from [lineages.csv](https://github.com/cov-lineages/pango-designation/blob/master/lineages.csv) and I obtained an [usher tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_8860_210af0.json?c=userOrOld&label=nuc%20mutations:T1191C,T1267C,A5584G,C11514T,C13019T,C22227T) showing that the T11938C sublineage of Delta+A2222V is not assigned yet.

Hi Babar I think you are right.

I was a bit shocked at the first sight of so many A684S suddenly emerging in August in a few different clusters so I didn't check it before submitting...thanks for the reply and sorry for being dramatic.

**Comment by chrisruis** [comment]
Thanks @c19850727. As outlined [here](https://www.pango.network/new-ay-lineages/), we're designating AY lineages that are epidemiologically distinct. It's not clear that the clade that you proposed is epidemiologically distinct. However, it is part of a larger clade of sequences from Canada that is the result of one or more introductions into Canada with onward transmission. This larger clade does warrant a new AY lineage and we've added this as AY.27 in [v1.2.68](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.68)

We've started AY.27 on a branch with G29422T (synonymous) and it currently has 1092 sequence designations

**Comment by corneliusroemer** [comment]
I stumbled across this issue when looking into S:613H homoplasies.

This is what AY.27 looks like in Canada at the moment (blue and green), the top is with S:613H in addition.

Unfortunately, pango-learn doesn't seem to designate any AY.27 at all. So it doesn't show up in outbreak.info or cov-spectrum.

![image](https://user-images.githubusercontent.com/25161793/134024989-da318316-11d9-4447-8fc4-934b3a196c34.png)

**Comment by AngieHinrichs** [comment]
> Unfortunately, pango-learn doesn't seem to designate any AY.27 at all. So it doesn't show up in outbreak.info or cov-spectrum.

@corneliusroemer Thanks so much for reporting that!  I believe @rmcolq has fixed that in today's [pangoLEARN release 2021-09-17](https://github.com/cov-lineages/pangoLEARN/releases/tag/2021-09-17).  Hopefully that will be reflected in GISAID and outbreak.info soon (few days?).

**Comment by FedeGueli** [comment]
Hi all of you, followimg thebgreat work of @corneliusroemer on it i was noticing that the Delta+613H is becoming a thing in Canada ( and not only there)
![Screenshot_2021-09-22-22-38-04-575_com android chrome](https://user-images.githubusercontent.com/87669813/134418530-80394bb0-c6fc-493b-8ac9-42b84b8e37ce.jpg)

My main concern came from Alberta where it is increasing in frequency
![Screenshot_2021-09-22-15-16-33-730_com android chrome](https://user-images.githubusercontent.com/87669813/134418668-509833d3-c893-4784-ac51-7436d774680f.jpg)

And in Alberta the epidemiological situation is out of control:
https://twitter.com/JenLeeCBC/status/1440382836431679489?s=20


I am not sure that there is any correlation between the two things but i hope professors @AngieHinrichs @chrisruis @rambaut @rmcolq @aineniamh could take a second look at this situation.

link of the screenshots
Covid Spectrum
https://cov-spectrum.ethz.ch/explore/Canada/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2%22%2C%22mutations%22%3A[%22S%3AQ613H%22]%7D%2C%22matchPercentage%22%3A1%7D

Outbreak
https://outbreak.info/situation-reports?pango&muts=S%3AQ613H&loc=USA&loc=USA_US-CA&loc=CAN&loc=DNK&selected=CAN&overlay=false

**Comment by silcn** [comment]
If anything S:Q613H has been stable at around 40% prevalence in Alberta since late July, which I would not call "increasing in frequency". CovSPECTRUM can produce unreliable estimates of transmissibility advantage when the increase in prevalence is due to a founder effect rather than a difference in fitness.

**Comment by FedeGueli** [comment]
> If anything S:Q613H has been stable at around 40% prevalence in Alberta since late July, which I would not call "increasing in frequency". CovSPECTRUM can produce unreliable estimates of transmissibility advantage when the increase in prevalence is due to a founder effect rather than a difference in fitness.

i know well i didnt look at growth advantage, but at the epidemiological situation.
there is not just trasmission advantage as possible issue.

**Comment by FedeGueli** [comment]
At the moment Alberta is experiencing the highest ratio icu per million pop,
(between the countries on ourworldindata) despite 74% of fully vaxxed,
and no age of vaccinated abnormality as we have seen in FLA or elsewhere.
![Screenshot_2021-09-30-14-25-02-875_com android chrome](https://user-images.githubusercontent.com/87669813/135462351-cd43ab2f-56b9-4673-bfc0-437d52217160.jpg)
![Screenshot_2021-09-30-10-35-58-923_com android chrome](https://user-images.githubusercontent.com/87669813/135462385-2198a663-39cb-4639-aee9-60982c39120d.jpg)
