### ISSUE TITLE
Lineages with S:403K to watch for growth

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1960]
Looked at recent lineages with S:403K that may be worth designating. All undesignated ones were a bit small, but a few should be worth tracking:

- XBF.9 (4, England/Wales)
- XBB.2 (4, Spain, with 428Y, 484V, and 1159R)
- ~XBB.1.9 (8, Indonesia/Poland/Israel, with 570T)~ designated XBB.1.9.6
- ~XBB.1.5 (6, South Africa, with 140I, 584F)~ designated XBB.1.5.53
- CH.1.1.1 (10, England/Slovenia)
- CH.1.1 (40, Wales, with 1263L)
- CM.8.1 (10, Utah)

Feel free to comment with queries/trees for these, I don't have the time right now to create them but the list above should be a good start for what to watch.

**Comment by FedeGueli** [comment]
The CH.1.1 from Wales has been proposed in https://github.com/cov-lineages/pango-designation/issues/1812
Both XBB.1.9.6 and XBB.1.5.53 were proposed i have added the issue to the commits.
We were tracking since some weeks the CM.8.1 waiting for it to show out of Utah , but this still didnt happen.
There were another XBB.1.9.1+403K but went stale (#1790) and also https://github.com/cov-lineages/pango-designation/issues/1791 from Himachal Pradesh likely gone extincted.

**Comment by Memorablea** [comment]
I suggest continuing to track sequences from the state of  Himachal Pradesh , as we have already seen too many Indian divine strains.

Additionally, what will be the consequences of the occurrence of S: 403K?

**Comment by FedeGueli** [comment]
> I suggest continuing to track sequences from the state of Himachal Pradesh , as we have already seen too many Indian Powerful COVID-19 mutant
> 
> Additionally, what will be the consequences of the occurrence of S: 403K?

I keep tracking also closed issues, even if with a slower rythm. S:403K is known to improve Ace2 binding.

**Comment by oobb45729** [comment]
There's one recently paper about R403K that gives results that are somewhat different from https://jbloomlab.github.io/SARS-CoV-2-RBD_DMS_Omicron/RBD-heatmaps/. ![](https://www.biorxiv.org/content/biorxiv/early/2023/03/22/2023.03.22.533805/F2.large.jpg?width=800&height=600&carousel=1) from https://www.biorxiv.org/content/10.1101/2023.03.22.533805v1.full

It claims that R403K, R346T, K356T improves ACE2 affinity at a similar level on BA.2.75. For DS.1, R403K is not enough to make up for the ACE2 affinity loss from F486S.

**Comment by FedeGueli** [comment]
I m noticing the combo S:R403K, S:A344T popping up in different lineage. it was in one sequence of that undersampled now closed issue in HP,India . wondering if it made it through recombining or just maybe a good combo for some unknown reason

**Comment by FedeGueli** [comment]
<img width="1158" alt="Screenshot 2023-05-11 alle 10 24 27" src="https://github.com/cov-lineages/pango-designation/assets/87669813/8b63ac99-095c-40c1-bfe1-ace8694bf546">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice7_genome_8d33_c186b0.json?label=id:node_6425143

@corneliusroemer the XBF.9 + S:R403K + S:D843G went on growing reaching 15 sequences mainly from its Welsh branch  that had further acquired Orf3a:P262L and Orf10:Q29* , should i propose in the preprosal page or will you procede to direct designation?

**Comment by FedeGueli** [comment]
There is a quite interesting XBB.1 that gained S:R403K along with two other spike mutations and an orf8 mutation, it likely emerged in malaysia but has been exported then in czechia and more recently in Italy and England.

![Schermata 2023-05-14 alle 09 17 24](https://github.com/cov-lineages/pango-designation/assets/87669813/f55931be-74ab-4cc9-8525-e72d414f5d51)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice11_genome_4065_81c40.json?c=userOrOld&label=id:node_6687743

defining mutations: XBB.1 >>  > C541T > C15951T > C8905T, S:R403K (G22770A), S:E619A)A23418C, S:N824S (A24033G), Orf8:Q27K (C27972A)

Gisaid query: G22770A,A23418C,A24033G,C27972A finds just 2 out of 3 sequences.

**Comment by FedeGueli** [comment]
Instead i m pre proposing this one: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_4065_81c20.json?label=id:node_6733437
![Schermata 2023-05-14 alle 09 29 10](https://github.com/cov-lineages/pango-designation/assets/87669813/5b504988-bc54-433b-a833-ad0abb57f602)

**Comment by FedeGueli** [comment]
Here another XBB.1.9.2 plus S:R403K and this time with S:A344T : https://github.com/sars-cov-2-variants/lineage-proposals/issues/57

**Comment by FedeGueli** [comment]
New one from Spain Italy France: CM.7 : 
![Schermata 2023-05-27 alle 08 43 17](https://github.com/cov-lineages/pango-designation/assets/87669813/41ef5199-1cb8-4770-9b82-7ebd5210f06b)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice11_genome_26c4_11ec90.json?label=id:node_7094192

Gisaid query:   G14500T, C26801T,G656A, G22770A finds 4.
cc @corneliusroemer

**Comment by FedeGueli** [comment]
Another one in DV.6 in England:
![Schermata 2023-05-27 alle 13 56 51](https://github.com/cov-lineages/pango-designation/assets/87669813/a872f741-b30c-4995-95a0-375136b2c595)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice13_genome_26c4_11ec90.json?c=gt-S_403&label=id:node_7276223

9 sequences: 
Query: T9723G, T21322G ,G22770A, C29420T

**Comment by FedeGueli** [comment]
Here another one: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_3b90_9964b0.json?c=userOrOld&label=id:node_7237008
![Schermata 2023-06-14 alle 12 36 42](https://github.com/cov-lineages/pango-designation/assets/87669813/1e3aaf78-d7fb-44f7-bf94-c0cf0b61623b)
with 4 spike mutations: F186L, R403K, A852V, S1147L

Gisaid query:
G1264A, C3276T, G8561T, A18273G

**Comment by FedeGueli** [comment]
Also : https://github.com/sars-cov-2-variants/lineage-proposals/issues/205: 

gisaid: G24620T,C23855A, C21411T

**Comment by FedeGueli** [comment]
also wuth S:R403T  found by @josetteshoenma: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice24_genome_test_160cc_c40760.json?label=id:node_7256174

Gisaid: C11103T, G11906A, G22770C

**Comment by FedeGueli** [comment]
Another branch of FL.5 got S:R403K:
 
![Schermata 2023-06-28 alle 15 48 09](https://github.com/cov-lineages/pango-designation/assets/87669813/dcedb28f-ed3c-4c0f-833a-3362d040688f)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice7_genome_test_c4f4_b5af40.json?c=gt-S_403&label=id:node_6686465

gisaid: C23188T, C2137T, G22770A, C29200T 
seqs 3

**Comment by FedeGueli** [comment]
> a singlet from EG.5.1.1 saltation EPI_ISL_17837041 got R403S [query: A22771C, G22344T] https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1019a_e0c1c0.json?f_userOrOld=uploaded%20sample

Yes thanks i m tracking that one!

**Comment by FedeGueli** [comment]
Australian saltation with 340K and 403K : 
query:C3984T, A5627G, C8991T,
count : 2
![Schermata 2023-07-11 alle 09 19 00](https://github.com/cov-lineages/pango-designation/assets/87669813/9f863660-9eb9-4424-80c9-42d1fff2462b)
[****](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_12359_cfa730.json?label=id:node_6806864)

**Comment by Memorablea** [comment]
EG.5+S:R403K 1 NOW

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
This branch is dead, please close this issue
