### ISSUE TITLE
Old XBB.1 (without Orf8:G8*) with S:F486P and S:F186L reappeared in China in March 2023. 11 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1963]
Here i want to propose an old 486P carrying XBB.1 lineage that failed to successfully spread even if it arose very soon in India in late 2022.
It maybe doesnt worth a proposal if not for the fact it suddenly reappeared in late march in China. Guizhou.
Before this sample it was intercepted by South Korean airport surveillance in a traveller from Vietnam.

Tree:
![Schermata 2023-04-26 alle 11 08 45](https://user-images.githubusercontent.com/87669813/234527647-f86ac748-9fe5-4ece-b9a2-1a81cc661f0d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_296e8_8e52a0.json?c=userOrOld&label=id:node_5828372

Defining mutations:
XBB.1. >> C6628T, N:P368L (C29376T) > Orf1a:L1110F (C3593T) > S:F486P (T23018C) >
>S:F186L (C22120A)

Gisaid query: C29376T,C3593T,T23018C

Sequences: 11
EPI_ISL_16549298, EPI_ISL_16708129, EPI_ISL_16853593,
EPI_ISL_16984444, EPI_ISL_16989732, EPI_ISL_17013976,
EPI_ISL_17065296, EPI_ISL_17065298, EPI_ISL_17079283,
EPI_ISL_17172430, EPI_ISL_17501626

Countries:
![Schermata 2023-04-26 alle 11 16 18](https://user-images.githubusercontent.com/87669813/234530202-49a9b0d6-7421-4166-8ecb-82b792cc69bd.png)

**Comment by aviczhl2** [comment]
> that failed to successfully spread

Maybe it is just failed to successfully spread in highly-sampled areas. 
I wonder if a map can be maintained for country/regions that have not uploaded any recent sequences. Such a map will be amazing.

**Comment by FedeGueli** [comment]
> > that failed to successfully spread
> 
> Maybe it is just failed to successfully spread in highly-sampled areas. I wonder if a map can be maintained for country/regions that have not uploaded any recent sequences. Such a map will be amazing.

Still if this is out there at a significant prevalence somewhere it would have been sampled in some airports doing sequencing  . So if it went ahead spreading unsampled it wasnt fast enough to exit its low mobility envinronment/pop.

**Comment by aviczhl2** [comment]
> Still if this is out there at a significant prevalence somewhere it would have been sampled in some airports doing sequencing . So if it went ahead spreading unsampled it wasnt fast enough to exit its low mobility envinronment/pop.

I think that will come out as singlets without significance. 
Evidence: 
1 billion people in China infected with BA.5.2.48/BF.7.14, however non-Chinese BA.5.2.48 has ~1000 seqs and non-Chinese BF.7.14 ~800 seqs, and that's under targeted sequencing that all countries target Chinese travelers.

So basically 0.5~1m infection=1 foreign sequence under targeted sequencing. Without targeted sequencing the ratio is even lower. 

So if a variant infects 10% of a medium-sized country/region of the population of 50million (50% prevalence of a wave infecting 20% of the population), that's a very high infection rate and the virus is certainly shall be regarded as circulating at high level.

However, given the actual infection number(5 million) and the infection-to-foreign-sequence ratio(0.5-1m infection/seq),  only less than 10 sequences will be captured if the country itself stopped uploading sequences.

**Comment by FedeGueli** [comment]
Nothing new i think it should be closed if in a ten days we dont see any new seq

**Comment by FedeGueli** [comment]
Transferred to https://github.com/sars-cov-2-variants/lineage-proposals/issues/8

**Comment by FedeGueli** [comment]
Not planned here
