### ISSUE TITLE
XBB.1.22.1 sublineages with S:K478R emerged in Indonesia (70 seqs)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1965]
Defining mutations: XBB.1.22.1>A22995G (S:K478R)
GISAID query: Spike_Y200C, Spike_T478R, Spike_F486P, -G5720A (to exclude some XBB.1.9 samples)
Earliest seq: 2023-03-10 (Indonesia, EPI_ISL_17324407)
Most recent seq: 2023-04-12 (China- Hubei Province, EPI_ISL_17545712)
Countries detected: Indonesia (3), China (2), South Korea (1)

Usher Tree:
![QQ截图20230426234205](https://user-images.githubusercontent.com/121703496/234630877-21097097-c20b-40e9-8be2-9a113c6852de.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1774_937500.json

S:K478R is very popular recently as the fast growing of XBB.1.16, but recently many other XBB.1*+F486P lineages gradually emerge it, maybe it will become more convergent.
Now the XBB.1.22.1+S:K478R is only 6 seqs. But notice that the latest two seqs (actually at least 3 seqs by GenBase) locates in Central China with high density of population (the total population of Hubei and Henan is more than 150M). As the other XBB.1.22.1 sublineage is spread in Hubei and Henan province (the red points in the figure below), the growth potential is of concern and worth monitoring.
![QQ截图20230426233920](https://user-images.githubusercontent.com/121703496/234630999-2e8c3f1c-49fc-4c80-9a85-639112dc23d0.png)

Genomes:
EPI_ISL_17324407, EPI_ISL_17469963, EPI_ISL_17470013, EPI_ISL_17511611, EPI_ISL_17545706, EPI_ISL_17545712,

**Comment by GeorgeS2019** [comment]
@HynnSpylor 
I have reason to believe from the protein structure of spike that **S:K478R** of e.g. XBB.1.16 could enhance RBD binding that is absent in e.g. S:T478K e.g. XBB.1.5

Please suggest where I could track this mutation more effectively.

**Comment by HynnSpylor** [comment]
@GeorgeS2019 Welcome to the community! I suppose that prompt attention to tracking the update of genome databases (GISAID, GenBase, etc., personal account is required) is enough. Welcome to open an issue and discuss if you find some new sublineages, it will be more effective.

**Comment by aviczhl2** [comment]
>actually at least 3 seqs by GenBase

How to do mutation-specific query on GenBase, and what are those seqs' IDs?

**Comment by corneliusroemer** [comment]
There are really 2 lineages here:
One detected in US with one travel surveillance suggesting it's from India, 4 seqs, with A19134G, C25836T on branch
The other one in Indonesia, China, South Korea with 6 seqs, directly on polytomy it seems,

Both are small, so let's see how things develop before designating. Ping me as soon as one reaches 20 sequences, until then let's just watch - too many comments make things hard to review.

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/25161793/236272449-2342ca80-5502-461c-ba23-6c940721386e.png">

**Comment by Memorablea** [comment]
It seems to have grown

**Comment by corneliusroemer** [comment]
@Memorablea it would be very helpful if you added quantitative statements for  growth (e.g. how many sequences now per cluster) and new Usher pics. That makes it much more valuable to everyone. As is your comment is noise and not much info

**Comment by GeorgeS2019** [comment]
I have reasons to believe that XBB.1.16 will prevail in US, replacing all growth advantage gained by XBB.1.9.1 over XBB.1.5

What will be critical will be **WHICH** will **replace** XBB.1.16

From which country WILL this successor of XBB.1.16 will come from

Am I assume right, this cold be XBB.1.122.1?

**Comment by FedeGueli** [comment]
> I have reasons to believe that XBB.1.16 will prevail in the US, replacing all growth advantage gained by XBB.1.9.1 over XBB.1.5
> 
> What will be critical will be **WHICH** will **replace** XBB.1.16
> 
> From which country WILL this successor of XBB.1.16 will come from
> 
> Am I assuming right, this could be XBB.1.122.1?

Hi feel free to open up a discussion issue in the new low priority page you find the link in the pinned issue in the homepage.

That kind of consideration can be widely disccussed there.

**Comment by HynnSpylor** [comment]
@Memorablea Nowadays the sublineage with ORF1a:E750K has been designated as FY.3 (and it is the main branch of XBB.1.22.1 in China). But the S:S408R is a reversed mutation and quite likely artefacts. 
The 2 new S:K478R seqs were updated several days ago, Thx for adding the Usher. But the seqs are not further increased these days. We should monitor for a time.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e5fe_5b6830.json?c=gt-S_478&label=id:node_5892381
![4FA0220C-5037-459E-B5F3-7D19C58892DF](https://github.com/cov-lineages/pango-designation/assets/121703496/69101f36-706c-415d-a299-731ef8d4cff7)

**Comment by Memorablea** [comment]
>We should monitor for a time.

I understand.

**Comment by HynnSpylor** [comment]
Today Indonesia updated 10 seqs on branch A (in Indonesia, China, South Korea and Japan), and the total is 24 (duplicate seqs are removed).
![QQ截图20230519095308](https://github.com/cov-lineages/pango-designation/assets/121703496/a7af9b83-309b-4d22-ba80-7ca6f31c61ef)

**Comment by HynnSpylor** [comment]
Now the branch A reaches 56 samples, and it has notably spread in Indonesia.
@corneliusroemer I suggest it can be designated.

**Comment by FedeGueli** [comment]
@HynnSpylor pls update the headline!

@corneliusroemer def one to get designated at first glance looking the xbb.1.22 tree:
![Schermata 2023-06-01 alle 10 14 08](https://github.com/cov-lineages/pango-designation/assets/87669813/81487630-13e6-411f-ad81-1a361870a8d8)

**Comment by FedeGueli** [comment]
Now 89 seqs in XBB.1.22.1 with S:T478R please @corneliusroemer designate the main branch:
![Schermata 2023-06-10 alle 20 44 46](https://github.com/cov-lineages/pango-designation/assets/87669813/7108091b-6454-4289-933a-8db4b062ff22)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1818e_4c42f0.json?f_userOrOld=uploaded%20sample&label=id:node_6638434

cc @HynnSpylor remove lineage B from this issue and propose it separately please casue we cna track both better. this one deserves rapid designation.

**Comment by FedeGueli** [comment]
Lineage B is : 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1818e_4c42f0.json?c=gt-S_478&label=id:node_6637654
![Schermata 2023-06-10 alle 20 47 00](https://github.com/cov-lineages/pango-designation/assets/87669813/0ecde51c-0c38-455e-88e8-dd93f0cdd9ee)

Defining FY.1 > S:T478R
Gisaid query: G18811A,A24813G
Sequences : 8

**Comment by HynnSpylor** [comment]
Now I change the title and focus on the former "Branch A"
I'll put Branch B (FY.1 sublineage) in SARS-Cov-2 lineage proposals for tracking

**Comment by FedeGueli** [comment]
Thx @HynnSpylor !

**Comment by HynnSpylor** [comment]
2 more seqs from Netherlands
