### ISSUE TITLE
XBB.1.9.2 with S:Q954Y [21 sequences, USA]

### ISSUE THREAD

**Issue by Outpfmance** [cov-lineages/pango-designation#1967]
Description:
Sub-lineage of:XBB.1.9.2
Earliest sequences:2023-3-28,USA EPI_ISL_17546332
Latest sequences:2023-4-5,USA EPI_ISL_17534897
Countries:USA(8)
Number of Sequences:8
GISAID query:Spike_Q954Y,-Spike_Q613H+G5720A,T28297C,C12789T,T23018C,A16878T
Cov-spectrum query: https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-03-01%26to%3D2023-04-27/variants?aaMutations=s%3A954Y&nextcladePangoLineage=XBB.1.9.2&
Nextstrain:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2c4c9_a8c5b0.json?f_userOrOld=uploaded%20sample&label=id:node_3147490
![IMG_0163](https://user-images.githubusercontent.com/125484893/234939148-63712136-fac0-4ca2-8787-52abe650f097.jpeg)
Nextclade:
![IMG_0162](https://user-images.githubusercontent.com/125484893/234939233-e9ed8375-8d23-46d9-95d7-2e26eeaa10b2.jpeg)
Evidence
This is another branch with S: Q954Y, which appears primarily in the United States, while #1939's XBB.1.5.20 appears in Canada, and both branches have been growing recently. Q954Y modifies one of Omicron's defining mutations, Q954H, and changes the chemistry and possibly affects N969K (see #1939 for details), which is a mutation of concern.
Sequences:
EPI_ISL_17477995
EPI_ISL_17486132
EPI_ISL_17486326
EPI_ISL_17486578
EPI_ISL_17546332
EPI_ISL_17546348
EPI_ISL_17499482
EPI_ISL_17534897

**Comment by FedeGueli** [comment]
this is now just 20. but last samples befor mid may. Maybe worth closing it?

**Comment by Outpfmance** [comment]
21 sequences now,I will still open this and keep updating. Thanks @FedeGueli for reminding me.

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
Please close this issue
