### ISSUE TITLE
EG.1 with S:Q954L[16 sequences ]

### ISSUE THREAD

**Issue by Outpfmance** [cov-lineages/pango-designation#1968]
Description
Sub-lineage of:EG.1(XBB.1.9.2.1)
Earliest sequences:2023-2-5,Italy EPI_ISL_16935797
Latest sequences:2023-4-8,Italy EPI_ISL_17483031
Countries:Italy(5 or 6),USA(1),Germany(1),Norway(1),Switzerland(1)
Number of Sequences:9 or 10
GISAID query:Spike_Q954L,Spike_Q613H+G5720A,T28297C,C12789T,T23018C,A16878T
Extra comment:One sequences in Italy EPI_ISL_17465439
Although the GISAID query is not found because the sequence is missing an A16878T, I think this is a problem of the Italian sequencing laboratory, and in fact it exists.
Cov-spectrum: https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-03-01%26to%3D2023-04-27/variants?aaMutations=s%3A954L&nextcladePangoLineage=EG.1&
Nextstrain: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_133bd_a92270.json?f_userOrOld=uploaded%20sample
![IMG_0165](https://user-images.githubusercontent.com/125484893/234940055-2d091423-d593-4be3-90cd-5af57b288c17.jpeg)
Nextclade:
![IMG_0164](https://user-images.githubusercontent.com/125484893/234940120-f2498e3a-1c82-498e-b67d-563209d09be4.jpeg)
Evidence
The appearance of S: Q954L is similar to S: Q954Y, both of which modified the definition mutation of Omicron and changed the chemical properties.Now this branch has been detected in many countries in the world. I set up a issue to facilitate our better detection.
Sequences:
EPI_ISL_17470215
EPI_ISL_17512342
EPI_ISL_17535288
EPI_ISL_16935797
EPI_ISL_17321958
EPI_ISL_17483031
EPI_ISL_17503773
EPI_ISL_17176089
EPI_ISL_17448009
(EPI_ISL_17465439)

**Comment by Outpfmance** [comment]
Thanks @FedeGueli. I will update this.

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
This branch is dead, please close this issue
