### ISSUE TITLE
XBB.1.5.46 with S:L518V and Orf9b:I5T 167 sequences (likely emerged in France)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1969]
I just noticed through 4 samples uploaded from Japan today that there is a lineage belonging to the big XBB.1.5.46 branch that has acquired S:L518V and then Orf9b:I5T (T28297C) convergently with XBB.1.9.1/2 and XBB.1.16

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3bf55_a924b0.json?c=country&label=id:node_5948270
![Schermata 2023-04-27 alle 19 12 30](https://user-images.githubusercontent.com/87669813/234938573-16719164-4f0b-4723-996b-9cf8b232c660.png)

**Defining mutations:**
XBB.1.5.46>> ORF8:V62L (G28077T) > S:L518V (C23114G) > Orf9b:I5T (T28297C)

**Gisaid query** : **G28077T,C23114G,28297C**

**Samples** : 152
<Details> 
<Summary>
SAMPLES IDs 
</Summary>
EPI_ISL_16812128, EPI_ISL_16882300, EPI_ISL_16895231,
EPI_ISL_16940932, EPI_ISL_16940976, EPI_ISL_17005815,
EPI_ISL_17005881, EPI_ISL_17005933, EPI_ISL_17006271,
EPI_ISL_17071376, EPI_ISL_17079051, EPI_ISL_17092941,
EPI_ISL_17175881, EPI_ISL_17194148, EPI_ISL_17204622-17204623,
EPI_ISL_17204633, EPI_ISL_17204708, EPI_ISL_17209576,
EPI_ISL_17226134, EPI_ISL_17232365, EPI_ISL_17256415,
EPI_ISL_17263137, EPI_ISL_17263273, EPI_ISL_17269598,
EPI_ISL_17269606, EPI_ISL_17269608, EPI_ISL_17270708,
EPI_ISL_17270737-17270738, EPI_ISL_17270763, EPI_ISL_17270796,
EPI_ISL_17270904, EPI_ISL_17285778, EPI_ISL_17300189,
EPI_ISL_17300215, EPI_ISL_17300227, EPI_ISL_17300257,
EPI_ISL_17300287, EPI_ISL_17300327, EPI_ISL_17300336,
EPI_ISL_17300462, EPI_ISL_17327798, EPI_ISL_17344017,
EPI_ISL_17344737, EPI_ISL_17346041, EPI_ISL_17346075,
EPI_ISL_17348241, EPI_ISL_17383785, EPI_ISL_17383849,
EPI_ISL_17383883, EPI_ISL_17383885, EPI_ISL_17386201,
EPI_ISL_17386285, EPI_ISL_17386448, EPI_ISL_17386475,
EPI_ISL_17397953, EPI_ISL_17407282, EPI_ISL_17407297,
EPI_ISL_17407824, EPI_ISL_17408263, EPI_ISL_17408375,
EPI_ISL_17408449, EPI_ISL_17419042, EPI_ISL_17419047,
EPI_ISL_17419100, EPI_ISL_17419106, EPI_ISL_17419110,
EPI_ISL_17419197, EPI_ISL_17419205, EPI_ISL_17419223,
EPI_ISL_17421818, EPI_ISL_17421869, EPI_ISL_17421887,
EPI_ISL_17422104, EPI_ISL_17422123, EPI_ISL_17422173,
EPI_ISL_17422211, EPI_ISL_17426693, EPI_ISL_17432454,
EPI_ISL_17446724, EPI_ISL_17461838, EPI_ISL_17461851-17461852,
EPI_ISL_17461880, EPI_ISL_17469690, EPI_ISL_17472461,
EPI_ISL_17475254, EPI_ISL_17475858, EPI_ISL_17475890,
EPI_ISL_17480470, EPI_ISL_17480504, EPI_ISL_17480810,
EPI_ISL_17483952, EPI_ISL_17483991, EPI_ISL_17491767,
EPI_ISL_17491894, EPI_ISL_17491969, EPI_ISL_17499721,
EPI_ISL_17501874, EPI_ISL_17501960, EPI_ISL_17501992,
EPI_ISL_17502042, EPI_ISL_17502049, EPI_ISL_17502062,
EPI_ISL_17502065, EPI_ISL_17502148, EPI_ISL_17502191,
EPI_ISL_17502203, EPI_ISL_17502273, EPI_ISL_17502276,
EPI_ISL_17502337, EPI_ISL_17514689, EPI_ISL_17518603,
EPI_ISL_17524426, EPI_ISL_17524773, EPI_ISL_17524829,
EPI_ISL_17524833-17524834, EPI_ISL_17524838, EPI_ISL_17542281,
EPI_ISL_17545293, EPI_ISL_17545298, EPI_ISL_17545321-17545323,
EPI_ISL_17545336, EPI_ISL_17545352, EPI_ISL_17545407,
EPI_ISL_17545413, EPI_ISL_17545416, EPI_ISL_17545444,
EPI_ISL_17545446, EPI_ISL_17545491-17545492, EPI_ISL_17545530,
EPI_ISL_17545550, EPI_ISL_17547207, EPI_ISL_17550385,
EPI_ISL_17550447, EPI_ISL_17550449, EPI_ISL_17550460,
EPI_ISL_17550463, EPI_ISL_17552442, EPI_ISL_17552487,
EPI_ISL_17554569-17554570, EPI_ISL_17557560, EPI_ISL_17558693,
EPI_ISL_17558700, EPI_ISL_17558830, EPI_ISL_17558844,

</Details>

**Countries:**
![Schermata 2023-04-27 alle 19 19 50](https://user-images.githubusercontent.com/87669813/234940187-f17a6198-14d8-4b34-86a4-681fd5ff3a24.png)

**Growth advantages**
Interestingly it is showing a solid growth advantage versus Orf9b:I5T carrying lineages baseline:
![Schermata 2023-04-27 alle 19 20 28](https://user-images.githubusercontent.com/87669813/234940376-d94fb7fe-552b-4b3f-abe4-51780a40a5e5.png)
A large advantage versus parental XBB.1.5:
![Schermata 2023-04-27 alle 19 22 43](https://user-images.githubusercontent.com/87669813/234940856-70147259-5054-4c8d-a719-a7a1590b89be.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=XBB.1.5*&nucMutations1=G28077T%2CC23114G%2C28297C&analysisMode=CompareToBaseline&
And a possible advantage versus XBB.1.9+486P baseline:
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=S%3A486P&nextcladePangoLineage=XBB.1.9*&nucMutations1=G28077T%2CC23114G%2C28297C&analysisMode=CompareToBaseline&
![Schermata 2023-04-27 alle 19 23 51](https://user-images.githubusercontent.com/87669813/234941100-ba44e3e9-92af-4288-8463-0a78f47049c0.png)

CC @AngieHinrichs  @InfrPopGen @corneliusroemer @thomaspeacock i suggest a rapid designation of this one.

**Comment by FedeGueli** [comment]
161 samples last ones from France Italy and South Korea

**Comment by AnonymousUserUse** [comment]
Designated as GB.1

**Comment by corneliusroemer** [comment]
The parent branch is GB.1, ORf9b:I5T is not defining
