### ISSUE TITLE
BA.1.17.2 Saltation sublineage in Italy in multiple forms, (5 seq, Apr 27)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1970]
### **Description**
**Sub-lineage of:** BA.1.17.2
**Earliest sequence:** 2023-3-15, Italy — EPI_ISL_17559168
**Most recent sequence:** 2023-3-27, Italy — EPI_ISL_17559167
**Countries circulating:** Italy (5)
**Number of Sequences:** 5
**GISAID AA Query:** Spike_N394S, Spike_L452Q, Spike_C1235F
**GISAID Nucleotide Query:** G25567A, -A23040G, G27556T, C27389T
**CovSpectrum Query:** Nextcladepangolineage: BA.1* & [6-of: G11417T, T11630C, G12071A, C21219T, C22079A, T22254C, C22323T, G22599C, A22743G, T22917A, T22942G, G23012A, C23741T, G24368C, G25266T, G25567A, C27389T, G27556T, A28319T, G28913T]
**Substitutions on top of BA.1.17.2:**
**Spike:** Q173K, I231T, S254F, R346T, N394S, L452Q, N460K, A484T, D936H, C1235F
**N:** T16S, G214C
**ORF3a:** A59T
**ORF7a:** A55S
**ORF9b:** L12F
**ORF1a:** V3718F, F3789L, D3936N
**Nucleotide:** G11417T, T11630C, G12071A, C21219T, C22079A, T22254C, C22323T, G22599C, A22743G, T22917A, T22942G, G23012A, C23741T, G23040A (Reversion), G24368C, G25266T, G25567A, C27389T, G27556T, A28319T, G28913T
 
**AA Deletions:** S:∆150-157 (4/5 sequences)
**Nucleotide Deletions:** ∆23010-23033 (4/5 sequences)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.1.17.2_Saltation_Italy_March_2023_subtreeAuspice1_genome_43a0a_b09810.json
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/33738461/235040095-bfae4a49-8556-4188-bafa-bc60439ec88b.png">
 
 
**Evidence**
There is metadata for two of the five sequences here indicating they come from different patients. The other three sequences have no metadata.
 
The main branch leading to these sequences has 18/19 non-synonymous nucleotide mutations. In reality, the two preceding branches—ORF3a:A59T and S:R493Q—also likely belong to this lineage, making 20/21 nuc mutations non-synonymous. The one synonymous mutation, C27389T, is fascinating in its own right. It's in the core TRS-B motif for ORF7a, and it spoils the TRS in the exact same way C27889T spoiled the ORF8 TRS in BA.5.
 
<img width="993" alt="image" src="https://user-images.githubusercontent.com/33738461/235041667-ef66dc05-109f-4803-9f9b-42116ed674e0.png">

 
The diversity in this lineage, primarily in spike, is striking. EPI_ISL_17559167, the bottom-branch sequence, which has 10/10 non-synonymous nucleotide mutations, stands a bit apart from the rest, with seven spike AA mutations not found in the other four sequences—T19A, D253G, V445A, S446G, F486P (a 2-nuc mutation), T791P, and H1101R. It also has a second-nuc mutation at 981 (S:F981S) which is shared with two other sequences here.
 
It also is the only sequence with M:L17F (a convergent mutation in chronic-infection sequences) and the only one that lacks S:∆150-157, a rare deletion that has, however, begun to show up more and more frequently in chronic BA.1* cases in the past six months or so.
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/33738461/235041054-3fca064c-23f7-42fe-858d-17f48bd8f91b.png">
 
Three sequence feature S:N439H, a mutation only seen in 3-4 other sequences ever. S:N394S, present in three sequences, is another rare mutation, though it was present in B.1.640.1 and B.1.640.2, two of the most interesting pre-Omicron lineages and the only ones to compete reasonably well with Delta. Two sequences have S:H1101Q and one has S:H1101R. These mutations are two nucleotide changes apart from one another, so they were presumably acquired independently. Two sequences have S:T376A, one of the defining BA.2 mutations.
 
The sequence on the far upper-right of the branch—EPI_ISL_17559165—is also worthy of mention as it has S:T376A and S:D843G along with four spike mutations not found in the other four sequences: N448S, S496T, K795T, and I896T.

I don't know for sure whether the the three sequences lacking metadata are from different patients than the two with metadata, but given that one of the sequences with no metadata is EPI_ISL_17559167, which stands out from the other four sequences. I'm pretty sure the GISAID  messaging service is non-functional, but I'll try to see if someone knows how to contact the submitting lab in order to ascertain whether all these sequences are from different patients and whether it is circulating in the wider community or confined to some treatment facility or long-term care home.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17559150, EPI_ISL_17559165, EPI_ISL_17559166, EPI_ISL_17559167, EPI_ISL_17559168,
</details>

**Comment by MCB6** [comment]
why not email to D.Cacchiarelli@tigem.it ?
https://www.tigem.it/research/research-faculty/cacchiarelli

**Comment by FedeGueli** [comment]
Hi @ryhisner thx for catching this, i ve spread the word to all my italian scientists contacts.

**Comment by FedeGueli** [comment]
@agrimaldi93

**Comment by agrimaldi93** [comment]
Hi everyone and thanks @FedeGueli for putting me in this exciting loop.
I will now take contact with our sample provider. I will also give a deeper look at sequencing data to check that everything is okay.

**Comment by FedeGueli** [comment]
> Hi everyone and thanks @FedeGueli for putting me in this exciting loop. I will now take contact with our sample provider. I will also give a deeper look at sequencing data to check that everything is okay.

Thank you very much!! It would be of utmost importance to understand how many patients have been sampled. From the avaible metadata we (Ryan) found at least two. But 3 samples have no patient metadata attached.

**Comment by FedeGueli** [comment]
@ryhisner @agrimaldi93 has news on this lineage.

**Comment by oobb45729** [comment]
On the topic of ORF7a, I think there might be some sort of correlation between nsp1 and ORF7a. I noticed that sequences that have large deletions in ORF7a (and sequences that have C27389T too) seem to more likely also have deletions around ORF1a:M85.

**Comment by agrimaldi93** [comment]
Dear all,
we checked with the sample provider and actually the sequences comes from the very same patient sampled multiple times.
I have asked the corrected metadata andh corrected the entries on gisaid.
Will take you posted if we find anything interesting.

**Comment by ryhisner** [comment]
Thank you, @agrimaldi93! I will now close this issue since it's clear this is a singlet and is not currently circulating.

**Comment by ryhisner** [comment]
@agrimaldi93, there is a new sequence in this lineage, and the metadata indicate it is from a different individual than the previous ones. Could you possibly find out if this is another mistake or whether it is correct this time? 
EPI_ISL_17722060

**Comment by agrimaldi93** [comment]
Dear all,
We are currently checking with our sample provider. The Swab was collected in a different city than the previous ones. Thus it should be a different patient.
I will keep you posted.
