### ISSUE TITLE
EG.1.2 with s:p479r and several orf muts (34 seqs, austria)

### ISSUE THREAD

**Issue by BorisUitham** [cov-lineages/pango-designation#1972]
Earliest sequence: 2023-03-06
Latest sequence: 2023-04-19
Mutations from EG.1.2: orf1b:L1701F >> s:P479R >> orf10:V6I >> orf7a:V71A. 
(ORF7b:H42Y is from eg.1.2)

Gisaid query: spike_p479r, T27605C
Covspectrum: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3Aeg.1*+%26+s%3A479r+%26+orf7b%3A42y+%26+orf7a%3A71a+%26+ORF1b%3A1701F

Along this path there are two more sequences making it 31 but it seems like its mostly the entire combination of mutations that is growing so I propose the 29 full sequences instead. Also three spike only sequences not included in the query, which would make it a total of 34 related sequences

Mutations at 479 are rare, even more R so I wonder what effect this could have. Perhaps advantage is given by changes in accessory proteins.

Highlighted is this specifc branch in context to eg.1.2:
![Screenshot_20230429_104017_Chrome~2](https://user-images.githubusercontent.com/119106095/235294346-cf203aa1-1cc1-4558-8a40-34fe2e6d64f5.jpg)

More detail: 
![Screenshot_20230429_104050_Chrome](https://user-images.githubusercontent.com/119106095/235294365-a398bc9a-1ef1-4b84-9057-f9163ec75f63.jpg)

Sequences:
EPI_ISL_17397922, EPI_ISL_17398155, EPI_ISL_17440364,
EPI_ISL_17472001, EPI_ISL_17472004, EPI_ISL_17472108,
EPI_ISL_17472125, EPI_ISL_17472309, EPI_ISL_17472705,
EPI_ISL_17479867, EPI_ISL_17497487, EPI_ISL_17505272,
EPI_ISL_17505384, EPI_ISL_17513988, EPI_ISL_17513993-17513994,
EPI_ISL_17518233, EPI_ISL_17547987, EPI_ISL_17548084,
EPI_ISL_17548140-17548141, EPI_ISL_17548168, EPI_ISL_17548185-17548186,
EPI_ISL_17565452-17565453, EPI_ISL_17565459, EPI_ISL_17565472,
EPI_ISL_17566005

**Comment by FedeGueli** [comment]
Great catch @BorisUitham , @thomaspeacock this was the one i mentioned you for K-R.

**Comment by FedeGueli** [comment]
@InfrPopGen @corneliusroemer this appears fast but likely biased of the optimal sequencing intensity of Austria (as happened with EK.1, but not with EU.1) so i would monitor this closely in the next days.

**Comment by HynnSpylor** [comment]
Good catch! I also tracked it recent days, but not opened the issue as it only emerged in Austria. P479R is really rare, we could monitor for a time (and concern if it spread into other countries).

**Comment by BorisUitham** [comment]
Now 34 sequences. 39 with the more inclusive query "spike_f486p,  spike_q613h,  spike_p479r". Still all from austria though. We'll have to see if it gets anywhere outside of austria.

**Comment by BorisUitham** [comment]
No uploads in 16 days, closing
