### ISSUE TITLE
Suggestion to designate the branch (without T17124C), shown on the same Usher branch of XBL, XBB.1.5.X defined by Orf9b:10F (C28312T) and A20379G 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1973]
@corneliusroemer in the XBB.1.5 branch without T17124C the next to be designasted should be the one with Orf9b:P10F  , the same of XBL. it has a couple of branch that looks interesting especially the N:S194P that acquired further S:F456L in Catalunya, Spain but also the other main branch  that interestingly gained a N mutation too N:D415N after orf1a:V2629I.

Evidences:
<img width="1142" alt="Screenshot 2023-04-29 alle 20 56 53" src="https://user-images.githubusercontent.com/87669813/235319601-79c38f14-f1e4-4436-bfae-b368e86596a1.png">

<img width="1131" alt="Screenshot 2023-04-29 alle 20 56 33" src="https://user-images.githubusercontent.com/87669813/235319586-95aec7eb-91d8-4d4e-9e43-8f80bcc6b2f1.png">

<img width="908" alt="Screenshot 2023-04-29 alle 20 57 11" src="https://user-images.githubusercontent.com/87669813/235319617-2f689fca-d4ac-4698-8776-0d79db0224c7.png">

N:S194P
<img width="1169" alt="Screenshot 2023-04-29 alle 20 57 37" src="https://user-images.githubusercontent.com/87669813/235319637-feecf8fe-e0dc-47fd-9979-fa7ce05b7f54.png">
N:S194P + S:F456L (9 sequences , not all shown below!)
<img width="1162" alt="Screenshot 2023-04-29 alle 20 58 10" src="https://user-images.githubusercontent.com/87669813/235319664-da3fefd0-ef16-49a3-b6c4-69fa691cd0c8.png">

Orf1a:V2629I + N:D415N 
<img width="1177" alt="Screenshot 2023-04-29 alle 20 59 17" src="https://user-images.githubusercontent.com/87669813/235319711-b55a5855-b7ab-4732-a362-230504091054.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24d06_d0e730.json?c=country&label=id:node_5908828

**Comment by AnonymousUserUse** [comment]
Could you please post the usher link for the proposed lineage? Thanks

**Comment by FedeGueli** [comment]
> Could you please post the usher link for the proposed lineage? Thanks
sorry. i ha e
added one of the same branch (but it is not rhe same tree of the pics

**Comment by FedeGueli** [comment]
Many samples uploaded in the last day in the subbranch with Orf1a:V2629I and N:D415N
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a617_21ebe0.json?c=userOrOld&label=id:node_5914244
![Schermata 2023-05-03 alle 10 46 51](https://user-images.githubusercontent.com/87669813/235870587-5ae64a08-4a3c-4b10-886e-817809db7063.png)

To me the entire branch and its two main sublineage (N:S194P) ( Orf1a:V2629I +N:D415N) should be deisgnated.
@corneliusroemer you surely already spotted this one, but it keeps going.

**Comment by corneliusroemer** [comment]
Designated as XBB.1.5.57, thanks!
