### ISSUE TITLE
XBB.1.5 without T17124C branch with Orf1b:K82R and S:G181R -   10 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1975]
In the XBB.1.5 branch without T17124C there is  a little cluster defined by S:G181R with a significant international spread hinting to an higher than sampled circulation. I spotted it looking at chinese samples collected after 1st April.

Defining mutations:
XBB.1* >>>G27915T > T23018C  > ORF1b:K82R (A13712G) > C29686T >S:G181R (G22103C)

Tree:
![Schermata 2023-04-30 alle 09 14 20](https://user-images.githubusercontent.com/87669813/235340735-a2209930-b286-46ce-afff-73c6631c146f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14234_e0c7a0.json?c=gt-ORF1ab_4483&label=id:node_5911779

Gisaid query: A13712G, C29686T , G22103C

Sequences:8 (3 from Shanghai)
EPI_ISL_17182954, EPI_ISL_17221841, EPI_ISL_17262339,
EPI_ISL_17307261, EPI_ISL_17481560, EPI_ISL_17536885-17536887,

**Comment by Over-There-Is** [comment]
according to genbase, all these 3 sequences are imported from Malaysia.

**Comment by FedeGueli** [comment]
> according to genbase, all these 3 sequences are imported from Malaysia.

thx! headline modified

**Comment by corneliusroemer** [comment]
> according to genbase, all these 3 sequences are imported from Malaysia.
Thanks for the info @Over-There-Is! GISAID seems to have dropped that metadatum :(

**Comment by FedeGueli** [comment]
10 sequences as today. one from Nepal.

**Comment by FedeGueli** [comment]
Transferred to pre proposal Repo : https://github.com/sars-cov-2-variants/lineage-proposals/issues/9
