### ISSUE TITLE
FQ.1 sublineage with N:S37P (16 seq. Australia, Canada, New Zealand)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1977]
EPI_ISL_17469133
EPI_ISL_17527572
EPI_ISL_17408864
EPI_ISL_17517382
EPI_ISL_17463350
EPI_ISL_17463183
EPI_ISL_17468441
EPI_ISL_17406208
EPI_ISL_17408914
EPI_ISL_17552447
EPI_ISL_17517250
EPI_ISL_17480157
EPI_ISL_17562305
EPI_ISL_17502585
EPI_ISL_17561359
Substitutions on top of FQ.1: T6571C then C26537T then N:S37P(T28382C)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c65a_ed5bb0.json?c=gt-N_37&label=id:node_7427678
![1](https://user-images.githubusercontent.com/115189228/235376617-cf71500d-1cd5-413b-99c0-07f15d7f7aa1.png)
![2](https://user-images.githubusercontent.com/115189228/235376619-c62b699d-cc99-41a3-aa61-cf8aa32346ac.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AFQ.1*%26N%3AS37P&
I found this thing after reading https://twitter.com/SolidEvidence/status/1652404073839181824, which mentioned the mutation N:S37P.
It seems to be expanding fast. It is already in 4 states of Australia and Canada and New Zealand. Its growth seems to be comparable to XBB.2.3* and XBB.1.16* in Australia.
![3](https://user-images.githubusercontent.com/115189228/235377316-821818c0-95c2-4aba-ae33-dccda46163b4.png)
https://cov-spectrum.org/explore/Australia/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3AFQ.1*%26N%3AS37P&variantQuery1=nextcladePangoLineage%3AXBB.2.3*&variantQuery2=nextcladePangoLineage%3AXBB.1.16*&analysisMode=CompareEquals&

**Comment by AnonymousUserUse** [comment]
Note: FQ.1 = BQ.1.1.39.1, it has Spike mutations P251L, K182E, Q218H, P1162L, Q613H on top of BQ.1.1

**Comment by corneliusroemer** [comment]
Bit early, too few sequences to be able to say whether the N does anything. FQ.1 is still a sufficient label at this time.
