### ISSUE TITLE
XBL.3 x BQ.1.1.13 recombinant (2x Australia, 1x Singapore as of 2023-05-01)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1978]
Interesting recombinant: XBB.1.5-like Spike with BA.2.75-like ORF1ab and BQ.1.1.13-like E,N,M etc.

```
Singapore/R24MR484/2023|EPI_ISL_17539782|2023-04-12
Australia/NSW-ICPMR-45452/2023|EPI_ISL_17561609|2023-04-14
Australia/NSW-ICPMR-45453/2023|EPI_ISL_17561610|2023-04-14
```

Nextclade currently calls it as XBW (XBB.1.5 x BQ.1.14)

GISAID: C17766T, G14400T,  G26428T, G26529A
covSpectrum: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=%5B5-of%3AC17766T%2C+G14400T%2C+C11824T%2C+C27889T%2C+A12390G%2C+G26428T%2C+G26529A%5D&

<img width="1955" alt="image" src="https://user-images.githubusercontent.com/25161793/235486962-a4dd14bb-4397-4b66-81dc-ae1fe0c688a4.png">

<img width="2043" alt="image" src="https://user-images.githubusercontent.com/25161793/235486958-96290d11-8397-4524-b0c2-9793c075912f.png">

https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28cb5_fe48e0.json

**Comment by JosetteSchoenma** [comment]
I think it is an XBL/BQ.1.1.13 recombinant. Breaking point between 23031 (S:F490S from XBL) and  25416.

![image](https://user-images.githubusercontent.com/94831035/235741298-255a471c-ac4a-4465-bb3c-88830413def7.png)
![image](https://user-images.githubusercontent.com/94831035/235741651-d208cc6b-ca2b-4943-8091-0a7e2d853ac6.png)

That would make A6832G and A12390G private mutations and a query!

**Comment by JosetteSchoenma** [comment]
I see now that XBL was already in the title. I was looking at the description. So, we agree ;-)

**Comment by corneliusroemer** [comment]
Now tracked in pre-proposal repo: https://github.com/sars-cov-2-variants/lineage-proposals/issues/23
