### ISSUE TITLE
New xbb.1.9.1 defined by S:256L and orf3a:V62I, 66 seqs at 2023-06-17, multiple countries.

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#1980]
Sublineage of xbb.1.9.1
Mutations Additional to it: C1441T,C2662T,C2710A,C22329T(S:256L),A23572T,A25576T(orf3a:V62I)
Gisaid Inquiry: C2710A, A23572T,C22329T
Earliest Sequence: EPI_ISL_17305034 Texas, US 2023-03-06
Latest Sequence: EPI_ISL_17562775 Italy 2023-04-18
Seqs collection:EPI_ISL_17259904, EPI_ISL_17262588, EPI_ISL_17287035,
EPI_ISL_17293579, EPI_ISL_17304653, EPI_ISL_17305034,
EPI_ISL_17333275, EPI_ISL_17333645, EPI_ISL_17334587,
EPI_ISL_17344775, EPI_ISL_17351667, EPI_ISL_17351946,
EPI_ISL_17371915, EPI_ISL_17403573, EPI_ISL_17411733,
EPI_ISL_17417879, EPI_ISL_17429140, EPI_ISL_17432792,
EPI_ISL_17440599, EPI_ISL_17463451, EPI_ISL_17478195,
EPI_ISL_17495645, EPI_ISL_17523508, EPI_ISL_17526808,
EPI_ISL_17526927, EPI_ISL_17526999, EPI_ISL_17546854,
EPI_ISL_17550860, EPI_ISL_17552291, EPI_ISL_17562775,
EPI_ISL_17563205, EPI_ISL_17588730, EPI_ISL_17588793,
EPI_ISL_17589654
Usher link
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_339fb_15b3f0.json?f_userOrOld=uploaded%20sample&label=id:node_3146553

I discovered this tree by searching xbb.1.9* with S:456L on cov-spectrum,  but typo happen so I actually searched S:256L. Yet this one is still quite interesting. It gained a foothold in multiple countries (australia, austria, guatamala (this is really unexpected), Italy, Israel, Japan, South Korea) besides a lot of states in US, and many sequences are quite recent.
Also S:256L is not just a random typo, it is one of the mutations in all XBC, and it is projected to be at least partially beneficial on jbloom calculator.

**Comment by FedeGueli** [comment]
68

**Comment by krosa1910** [comment]
This lineage have not shown up for about a month, so i would temporarily shut this proposal.

**Comment by FedeGueli** [comment]
=,1 % in SOuth Korea in June. reopen it here but pls keep here in this page to monitor it.
