### ISSUE TITLE
BN.1.3.5 mini-saltation(8 nuc/6 aa) in China (27 seqs, 2 countries )

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1981]
sub-lineage of: BN.1.3.5
mutations on top of BN.1.3.5: G4556A(orf1a:V1431I),G9753A(orf1a:R3163K),C17999T(orf1b:T1511I),G21785A(S:G75S), T25343C,C28102T(orf8:P70L),C28507T(orf9b:A75V),T28588C

GISAID query: C28507T,T28588C,C28102T
No. of seqs: 6(Zhejiang 3 Hebei 2 Singapore 1)

First seq: EPI_ISL_17490490(Hebei) 2023-3-17
Latest seq: EPI_ISL_17596232(Singapore) 2023-4-13

Sequences: EPI_ISL_17490383, EPI_ISL_17490490, EPI_ISL_17492813,
EPI_ISL_17495314-17495315, EPI_ISL_17596232
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice10_genome_2d1ff_360ae0.json)

<img width="1402" alt="Screen Shot 2023-05-04 at 16 24 22" src="https://user-images.githubusercontent.com/10445944/236149982-1cc68f52-73d9-4f26-9c4a-c8c90f361523.png">

**Comment by AnonymousUserUse** [comment]
This might also be a candidate for molnupiravir-driven lineage

**Comment by aviczhl2** [comment]
Migrated to https://github.com/sars-cov-2-variants/lineage-proposals/issues/15

**Comment by aviczhl2** [comment]
Closed https://github.com/sars-cov-2-variants/lineage-proposals/issues/15 due to having 25 seqs spread across various provinces.

**Comment by aviczhl2** [comment]
No new seqs after the re-open, re-close it.

**Comment by aviczhl2** [comment]
This lineage reappears in the recent Guangdong and Beijing batch, reopen.

**Comment by aviczhl2** [comment]
Seems dead.
