### ISSUE TITLE
Two FL.1(XBB.1.9.1.1) branches with S:K478R (A22995G) 

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1985]
Branch A: 15 seqs
Defining mutations: FL.1>G25186T(S:Q1208H)>A22995G (S:K478R)
GISAID query: Spike_A701V, Spike_Q1208H, Spike_K478R
Earliest seq: 2023-03-16 (Australia, EPI_ISL_17358833)
Most recent seq: 2023-04-19 (Vietnam, EPI_ISL_17614077)
Countries detected: Vietnam (6), Australia (5), USA (3), South Korea (1)

the 6 seqs from Vietnam are updated today. 10 of 15 seqs are updated in May, and 3 of 15 also get T23005A (S:N481K)

Genome:
EPI_ISL_17324221, EPI_ISL_17358833, EPI_ISL_17383727, EPI_ISL_17434080, EPI_ISL_17474522, EPI_ISL_17593074, EPI_ISL_17595399, EPI_ISL_17595484, EPI_ISL_17606386, EPI_ISL_17614065, EPI_ISL_17614067, EPI_ISL_17614076-17614078, EPI_ISL_17614092

--------

Branch B: 7 seqs
Defining mutations: FL.1>T6148A>G25696C (ORF3a:E102Q)>A24670G>A22995G (S:K478R), G25266T (S:C1235F), G29179C, C29311T
GISAID query: Spike_A701V, Spike_K478R, T6148A
Earliest seq: 2023-02-27 (Indonesia, EPI_ISL_17332707)
Most recent seq: 2023-04-12 (Indonesia, EPI_ISL_17518063)
Countries detected: Indonesia (7)

Genomes:
EPI_ISL_17372707, EPI_ISL_17389662, EPI_ISL_17465904, EPI_ISL_17475324, EPI_ISL_17475347, EPI_ISL_17503721, EPI_ISL_17518063

Usher Tree: Branch A is in light green and Branch B in blue.
![QQ截图20230505230814](https://user-images.githubusercontent.com/121703496/236498701-7e5416e3-f2e3-41eb-a995-a9d22090cb05.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16a16_5156a0.json?c=gt-S_478,1208

Branch A is more worthy of monitoring as the recent growth and spread into 4 countries.

**Comment by corneliusroemer** [comment]
Let's wait until they are at least 25 sequences, ping me then

**Comment by FedeGueli** [comment]
@cornelius about branch A i would highlight that we have just 99 vietnam related sequencse collected after 10th of April , and this is 7 out 99 with XBB.1.16 at 37 and XBB.1.5.42 at 17 , Vietnam is experimenting a sharp increase of cases and i would blame this 3 lineages for that . I would designate immediately Branch A.

**Comment by corneliusroemer** [comment]
Yeah I've seen this one. I'd like to wait a few more days to see where it falls exactly on the tree

**Comment by HynnSpylor** [comment]
@corneliusroemer Branch A reaches 36 seqs (further spread in South Korea and Australia). Its parent lineage (S:A701V&S:Q1208H without S:K478R) also has notable increase.

**Comment by AnonymousUserUse** [comment]
So the branch A has been designated as FL.1.4

**Comment by Over-There-Is** [comment]
The branch B of this issue is designated as FL.1.7 now.
