### ISSUE TITLE
XBB.1.5 sublineage with S:K182Q, ORF1a:T1322I (73 seq, May 5)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1986]
**Description**
**Sub-lineage of:** XBB.1.5
**Earliest sequence:** 2023-1-30, Slovakia — EPI_ISL_17173095 
**Most recent sequence:** 2023-4-24, Austria — EPI_ISL_17607553 & 3 others
**Countries circulating:** Slovakia (39), Austria (19), Czech Republic (6), England (4), Italy (3), Poland (2)
**Number of Sequences:** 73
**GISAID AA Query:** Spike_K182Q, NSP3_T504I
**GISAID Nucleotide Query:** C4230T, C5144T, A22106C
**CovSpectrum Query:** Nextcladepangolineage: XBB.1.5* & C4230T & [2-of: C5144T, A22106C, G26230T]
**Substitutions on top of XBB.1.5:**
**Spike:** K182Q
**ORF1a:** T1322I (NSP3_T504I)
**Nucleotide:** C4230T, C5144T, A22106C, G26230T

**USHER Tree** (Clearly, there are a lot of artifactual reversions in the Slovakian sequences, so the top branches here are misleading.)
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.5_K182Q_ORF1a_T1322I_72seq.json?c=gt-S_182&label=id:node_3236180
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/33738461/236571041-04fed6ff-078b-4869-8b61-a5bd00b9748b.png">

**Evidence**
ORF1a:T1322I (NSP3_T504I) has not been found in any major lineage so far, but it is a convergent mutation in highly mutated chronic-infection sequences, as are mutations at the adjacent site, ORF1a:D1323 (NSP3_D505). Chronic-infection sequences also very frequently harbor mutations in a few other ORF1a regions, some of which, like ORF1a:1322-1324, span two or more AA sites. Other such regions include ORF1a:1638-1640 (NSP3_820-822), ORF1a:4087-4088 (NSP8_145-146), ORF1a:4164-4166 (NSP9_24-26), and ORF1a:4175-4176 (NSP9_35-36).  

My guess is that these are T-cell epitopes, which would explain why they appear so often in chronic infections but don’t often show up in regular lineages; given the length of time it typically takes for T cells to be activated and the narrow transmission bottleneck documented by Lauring Lab and others, it may be unlikely such mutations would develop and transmit except in prolonged infections. The only mutations in these regions to have caught on in a major lineage are ORF1a:P1640S/L (L in ~9% of Delta sequences, S in all BA.2.75* lineages) and ORF1a:T4175I (which only recently took off in XBB.1.9* lineages).

With the recent prominence in growing lineages of advantageous non-spike mutations (ORF9b:I5T, ORF1a:L3829F, ORF8:G8*, etc), it seems as if selection on the global level has shifted somewhat toward non-spike regions, perhaps favoring mutations that help to evade innate and cellular immunity. I would not be surprised if some of these ORF1a mutations start to catch on, as ORF1a:T4175I has begun to do. 

G26320T is in the untranslated region between ORF3a and E. ORF6 and E have the most minimal TRS motifs of all the subgenomic genes—just ACGAAC instead of the AAACGAAC found in all others—and G26320T slightly increases the extended homology for E’s TRS, thought it may be too distant (-7 position relative to ACGAAC) to make much difference.
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/33738461/236573888-771627bc-afdd-4ce8-a3f4-14bfd8417588.png">
Image above made using @theosanderson's Gensplore site. https://gensplore.theo.io/
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16976852, EPI_ISL_17079991, EPI_ISL_17093101, EPI_ISL_17093204, EPI_ISL_17094138, EPI_ISL_17172984, EPI_ISL_17173095, EPI_ISL_17299066, EPI_ISL_17299070, EPI_ISL_17318938, EPI_ISL_17327417, EPI_ISL_17359577, EPI_ISL_17363072, EPI_ISL_17370758, EPI_ISL_17376031, EPI_ISL_17376033, EPI_ISL_17376035, EPI_ISL_17391073, EPI_ISL_17401362, EPI_ISL_17409748, EPI_ISL_17433533, EPI_ISL_17440724, EPI_ISL_17481685-17481686, EPI_ISL_17481693, EPI_ISL_17481723, EPI_ISL_17485081, EPI_ISL_17503137, EPI_ISL_17503170, EPI_ISL_17503182, EPI_ISL_17503192, EPI_ISL_17503214, EPI_ISL_17503219, EPI_ISL_17503221, EPI_ISL_17503223-17503225, EPI_ISL_17503230, EPI_ISL_17503264, EPI_ISL_17503381, EPI_ISL_17503390, EPI_ISL_17503410, EPI_ISL_17503417, EPI_ISL_17503442, EPI_ISL_17503447, EPI_ISL_17503453, EPI_ISL_17503473, EPI_ISL_17503479, EPI_ISL_17503488-17503489, EPI_ISL_17503504, EPI_ISL_17503525, EPI_ISL_17503568, EPI_ISL_17503571, EPI_ISL_17503575, EPI_ISL_17503624, EPI_ISL_17503630, EPI_ISL_17544744, EPI_ISL_17544798, EPI_ISL_17562755, EPI_ISL_17562970, EPI_ISL_17565578, EPI_ISL_17566017, EPI_ISL_17566031, EPI_ISL_17566037, EPI_ISL_17566040, EPI_ISL_17566052, EPI_ISL_17566076, EPI_ISL_17584940, EPI_ISL_17607553-17607555, EPI_ISL_17607559
</details>

**Comment by Mydtlwn** [comment]
The mutations on the non-spike mutations, ORF1a, ORF1b, ORF3a, ORF7a, ORF8, ORF9a, ORF9b are more frequent, and I think it is necessary to make the research more comprehensive to do some summary and reference information on this locus, so that it can be more convenient to have a help on the specified pedigree.

**Comment by oobb45729** [comment]
T-cell epitopes may be involved, but they may be not the sole reason. There's a paper that mentions that ORF1a:1638-1640 (PLpro:75-77) are related to a T-cell epitope, and there's also a paper that shows that PLpro:T75L may alter the function of PLpro (https://www.nature.com/articles/s41586-020-2601-5).
There are these two interesting sequences that have ORF1a:T1322I, ORF1a:T1638N, ORF1a:P1640F on the top of BQ.1.18, but there isn't much going on elsewhere, not even synonymous mutations.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=ORF1a%3AP1640F%26ORF1a%3AT1638N&
Another frequent mutated residue that is reported to be related to a T-cell epitope is ORF3a:Q213, but ORF3a:Q213X happens way too often, which makes wonder whether these mutation have other functions as well.
