### ISSUE TITLE
FL.4 with S:A766S,417K reversion in Myanmar(8 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1987]
I found a S:417K reversion branch that all of the sequences have S:417K (the nuc at 22813 is G not N). 

Sub-lineage of: FL.4
Mutations on top of FL.4: A28615G,G23858T(S:A766S),G7393T,T22813G(reversion)
GISAID query:A28615G,G23858T,G7393T,-G22813T
No. of seqs: 8 Myanmar with 22813G,  2 Japan seqs with unknown 22813(so may belong to this)

Sequences:
EPI_ISL_17599361-17599368(all 2023-3-22, Myanmar)

EPI_ISL_17495634, EPI_ISL_17540079 for Japanese seqs with unknown 22813. 

Myanmar only uploads 36 seqs in 2023, 13/16 of its Jan. batch include S:K417N, the other 3 has 22813 unknown , while only 1/20 of its March/Apr batch has S:417N and the other 19 all have S:417K (the nuc at 22813 is G not N).  

The XBB.2.3.5/XBB.1.16/XBB.1.16.1 in this Myanmar batch all share S:417K too, except for one XBB.1.16 which has S:417N.

<img width="1680" alt="Screen Shot 2023-05-06 at 13 56 40" src="https://user-images.githubusercontent.com/10445944/236605921-93dbf5e0-385c-4d5b-9912-d05a734f55b2.png">

Is it due to artefact (can it suddenly emerge in 2 months time, with 22813 being G?), or is it the immune background in Myanmar driving convergent S:417K(but 95% seems too high?)? 
However, gIven N=20, if actual prevalence is 75%, 19/20 still falls in the 95% Cl range. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18093_5e14e0.json)
<img width="1390" alt="Screen Shot 2023-05-06 at 13 45 17" src="https://user-images.githubusercontent.com/10445944/236602813-814cd770-8661-4796-9924-9b694978d30d.png">

**Comment by corneliusroemer** [comment]
This is exactly what an artefact looks like:
- From country with few sequences which has had issues with artefactual reversions in the past, just look at all the 200 sequences uploaded from Myanmar during the pandemic, the 417 reversion is common in BA.2, BN.1 
- Just seen in one country, Japan having N means nothing
- Seen homplasically: across multiple XBB lineages, but none of these cluster with other sequences from around the world that also have 417

Artefactual reversions are so extremely common that there needs to be strong evidence for the mutation being real:
- natural cluster
- from multiple labs and countries in a realistic way (i.e. the geographical distribution makes sense, isn't suggestive of artefact)
- some good quality sequences from labs that are known to have few artefacts

All 3 criteria should be satisfied. None are for this lineage so I'll close this for now to keep the number of proposals manageable and not have issues for likely artefacts.
