### ISSUE TITLE
Correct Lineage Notes for XBB.1.24.3

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1989]
The lineage notes and git commit logs for XBB.1.24.3 currently describe this lineage as "S:S256L, after ORF1a:K261N, N:A35T, Malaysia/Japan". Neither CoV-Spectrum nor GISAID return any sequences matching this description.

An UShER tree of XBB.1.24 + ORF1a:K261N suggests that the "N:A35T" in this description may be incorrect. If this is true, XBB.1.24.3 is the middle branch of the tree with S:S256L as a peer of N:A35T instead of after N:A35T:
![Screenshot 2023-05-07 at 14-25-06 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ subtreeAuspice1_genome_1eae_7fa2c0 json](https://user-images.githubusercontent.com/88959107/236698783-32a58e87-8dcb-45d4-949c-20eacb4a128e.png)

Please check to see if the lineage notes for XBB.1.24.3 need to be corrected to "S:S256L, after ORF1a:K261N, Malaysia/Japan".

**Comment by corneliusroemer** [comment]
Thanks, you're right! Next time you can submit a PR
