### ISSUE TITLE
XBB.1.9.1 with ORF1ab:M5974T and N:R195I and 3 spike mutations (S494P, N616D, S256L) 12 seq. only in France

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#1990]
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/e5e67407-27cc-469e-a314-c61280407525)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e1cd_c2e550.json?f_userOrOld=uploaded%20sample&label=id:node_5873170
First Sample 4-12-23
Most recent sequence: 4-25-23

**Comment by Mydtlwn** [comment]
Hello, friend, about this library has made some adjustments, for some sequences less pedigree can go to the new library first to raise issues, and then through the discussion and reach a certain amount of quantity and then raised here, this is the link to the new library:

https://github.com/sars-cov-2-variants/lineage-proposals/issues

**Comment by BorisUitham** [comment]
See discussion here: https://github.com/sars-cov-2-variants/lineage-proposals/issues/19

Theres 16 sequences now btw
