### ISSUE TITLE
XBB.1.9.1 with S:F456L starting in Vietnam(66 seqs, 11 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1994]
This is the 1st XBB.1.9.1 sub-lineage with the convergent S:F456L.
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/27

Sub-lineage of: XBB.1.9.1
Mutations on top of XBB.1.9.1: C28846T, G2174A(orf1a:E637K), T22928C(S:456L)
GISAID query: C28846T, G2174A, T22928C

No. of seqs: 27(3 USA 4 China 7 Vietnam 1 Singapore(from Vietnam) 2 France 2 Canada 3 South Korea(1 from Vietnam) 5 Japan)

Note that all 3 green Vietnamese seqs have S:456 dropout, they're likely to also have 456L.
GISAID query for the green Vietnamese seqs: C28846T, G2174A, G1464T,-T22928C,C12890T

First seq: 17481621, 2023-3-9, Vietnam
Latest seq: 17641519, 2023-5-1 ,Canada

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice17_genome_1570f_7df140.json?c=gt-S_456&label=id:node_5873226)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/2204bcbb-2cb8-410d-ad9e-4581d754bc4d)

**Comment by aviczhl2** [comment]
53 seqs now, new country of Australia and Spain(exported to South Korea).

**Comment by JosetteSchoenma** [comment]
This seems to grow quickly. Lots of new samples on the ORF1ab:G400V branch from Australia/NSW. 
![Screenshot_20230528_082905_Twitter.jpg](https://github.com/cov-lineages/pango-designation/assets/94831035/46fd33cd-2ef8-40f1-bde0-e2f13187cb65)

![Screenshot_20230528_082832_Twitter.jpg](https://github.com/cov-lineages/pango-designation/assets/94831035/ff8e71b2-b9b5-4af0-a375-dc7b6db9fa1e)

**Comment by FedeGueli** [comment]
ping @corneliusroemer @InfrPopGen 
reason to fast designate this one
1) growing fast outside the area where emerged from
2) 456L convergent evo able to increase fitness(escape)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage FL.15 with 53 newly designated sequences, and 0 updated designations. Defining mutation T22928C (S:F456L). There's currently two adjacent clades with S:F456L on the usher tree, but as it is likely that these are really one clade, they have been designated as if monophyletic.

**Comment by AngieHinrichs** [comment]
Good catch @InfrPopGen, I'll try to fix that soon.

**Comment by FedeGueli** [comment]
One sequence got S:L455F check via G15649A, G22927T,G1464T 
ID:EPI_ISL_17836859
