### ISSUE TITLE
XBB.8 Sublineage with S:S486P, ORF1a:A2529V, T1507G—SE Africa (14 seq, May 15)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1995]
**Description**
**Sub-lineage of:** XBB.8
**Earliest sequence:** 2023-2-27, Reunion — EPI_ISL_17520767
**Most recent sequence:** 2023-4-9, Mayotte — EPI_ISL_17657886
**Countries circulating:** Mauritius (3), Reunion (3), Mayotte (2), Denmark (1), Italy (1), USA (1)
**Number of Sequences:** 14
**GISAID AA Query:** NSP3__A1711V
**GISAID Nucleotide Query:** T1507G, C7851T, T23018C
**CovSpectrum Query:** Nextcladepangolineage:XBB* & [5-of: T1507G, C7851T, T14574C, T23018C]
**Substitutions on top of XBB.8:**
**Spike:** S486P
**ORF1a:** A2529V (NSP3_A1711V)
**Nucleotide:** T1507G, C7851T, T23018C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.8_S486P_A2529V_T1507G.json?c=gt-nuc_1507&label=id:node_3559184
<img width="1362" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/fa46f96d-98d5-42c5-9c4a-ebb2879e5452">

 
**Evidence**
Most of the sequences in this lineage have come from the very small island nations/territories of Mauritius, Reunion, and Mayotte. Geographically, these islands are closest to Madagascar, with Mozambique and Tanzania being the closest on the African continent. I do not think we have any recent sequences form any of those countries, so this lineage is likely much more common than the low number of sequences would make it appear.
 
The amount of diversity here also suggests circulation in a wider geographical area, though it also implies that the lineage as a whole is not growing particularly fast.
 
Some of the more interesting spike mutations in this lineage: T51I (6), K150E (2), P251S (2 seq), P521T (2), A1070T (2). The apparent saltation lineage consisting of two sequences from Mayotte is also very interesting. 

<img width="1423" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/1e3d6dee-0cdb-4437-924e-97d12e30e3fb">

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17446354, EPI_ISL_17520762, EPI_ISL_17520767, EPI_ISL_17520814, EPI_ISL_17538228, EPI_ISL_17585896, EPI_ISL_17620560, EPI_ISL_17657850, EPI_ISL_17657886-17657887, EPI_ISL_17657950, EPI_ISL_17657959-17657960, EPI_ISL_17657977
</details>

**Comment by FedeGueli** [comment]
Orf1a:A2529V was the signature of the infamous Delta sublineage AY.4.

It popped up in other lineages after that, some of them i proposed then, and i can confirm it gives some fitness to them.

**Comment by corneliusroemer** [comment]
A few more seem to have been uploaded from the French islands yesterday
