### ISSUE TITLE
XBB.1.9.1 sublineage with S:A411S emerged in China (85 seqs in China and Australia)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1996]
Defining mutations: XBB.1.9.1>C503T(ORF1a:P80S)>G22793T(S:A411S), then mostly further get C13011T(ORF1a:T4249I), G10658A (ORF1a:V3465I)
GISAID query: Spike_A411S, C503T, G5720A, C11956T
Earliest seq: 2023-04-19 (China, EPI_ISL_17618478)
Most recent seq: 2023-05-08 (Australia, EPI_ISL_17662973)
Countries detected: China (45, Sichuan Province 28, Hubei Province 13, Shanghai Municipality 2, Jiangsu Province 1, Qinghai Province 1), Australia (1)

Usher Tree:
![QQ截图20230516161344](https://github.com/cov-lineages/pango-designation/assets/121703496/b3c241a7-3637-4b1a-826f-b1ec35bd0414)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12505_336e00.json

A very new sublineage in China with fast growth. Today it is detected abroad (in Australia) and many seqs in Sichuan Province are updated.
Nowadays XBB.1.9.1 is the dominant sublineage in China, and we may keep monitoring.

Genomes:
EPI_ISL_17614986, EPI_ISL_17615014, EPI_ISL_17618478, EPI_ISL_17625318, EPI_ISL_17625363, EPI_ISL_17625367-17625369,
EPI_ISL_17625382, EPI_ISL_17625403, EPI_ISL_17625414, EPI_ISL_17625487, EPI_ISL_17632947, EPI_ISL_17632949, EPI_ISL_17632956, EPI_ISL_17632961, EPI_ISL_17637415, EPI_ISL_17637509, EPI_ISL_17645406, EPI_ISL_17645409-17645411, EPI_ISL_17645418-17645419, EPI_ISL_17645455, EPI_ISL_17645477, EPI_ISL_17645514, EPI_ISL_17652411, EPI_ISL_17662973, EPI_ISL_17664525, 
EPI_ISL_17664531-17664532, EPI_ISL_17664538, EPI_ISL_17664548, EPI_ISL_17664555, EPI_ISL_17664560, EPI_ISL_17664568, EPI_ISL_17664579-17664580, EPI_ISL_17664584, EPI_ISL_17664586, EPI_ISL_17664594-17664595, EPI_ISL_17664615, EPI_ISL_17664624-17664625

**Comment by HynnSpylor** [comment]
51 seqs (1 updated from Shanghai)

**Comment by FedeGueli** [comment]
@corneliusroemer @thomaspeacock @InfrPopGen @AngieHinrichs i suggest a rapid designation of this one.

**Comment by Last-Order** [comment]
76 seqs now. 2 new from Fujian.

**Comment by AnonymousUserUse** [comment]
Designated as FL.13.1
