### ISSUE TITLE
XBB.1* Sublineage with S:L335S, S:R403K, S:S486P, ORF1a:T403I, ORF1b:S2212I (15 seq, 4 continents, May 16—1 seq from Congo)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1997]
### **Description (Transferring this from the other page now that it's >10 seq & in four continents)**
**Sub-lineage of:** XBB.1* (Possibly XBB.1.28, but I'm not certain)
**Earliest sequence:** 2023-3-27, France — EPI_ISL_17480623
**Most recent sequence:** 2023-4-24, France
**Countries circulating:** France (2), China (1), USA (1)
**Number of Sequences:** 4
**GISAID AA Query:** Spike_L335S, Spike_F486P, Spike_R403K
**GISAID Nucleotide Query:** G22770A, T22566C, T23018C
**CovSpectrum Query:** Nextcladepangolineage:
**Substitutions on top of XBB.1:**
**Spike:** L335S, R403K, S486P
**ORF1a:** T403I (NSP2_T223I)
**ORF1b:** S2212I (NSP15_S161I)
**Nucleotide:** C1473T, G20102T, G22770A, T22566C, T23018C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1_L335S_R403K_S486P_4seq.json  
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/33738461/236979137-65024cd5-2181-45c8-a524-9dd4dc8dd912.png">

 
**Evidence**
There are only four sequences at this point, but they are spread across three continents, with sequences from China, USA, and France. Short description of additional mutations on each sub-branch:
 
• USA sequence—S:G476S, ORF1b:V1402I (NSP13_V479I) + synonymous nuc mutations G12331A, C17850T, C25276T, and C29416G
 
• France sequence 1 — synonymous nuc mutations G12331A, C17850T, C25276T, and C29416G
 
• France sequence 2—ORF6:L35H, ORF1a:R24C, ORF1a:A117T, ORF1a:E1293D, ORF1a:P1497T
 
• China sequence—S:K478R, ORF1a:L397F, ORF1b:I829V, ORF1b:Y1200H plus synonymous nuc mutations C17850T, C25276T, and C29416G

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17480623, EPI_ISL_17593232, EPI_ISL_17615418, EPI_ISL_17618380
</details>

**Comment by ryhisner** [comment]
There are now three sequences in this lineage with S:K478R. Only 13 sequences seem to show up on GISAID, but there are clearly 15 different ones on the Usher tree.

**Comment by HynnSpylor** [comment]
one more seq with S: K478R from Netherland

**Comment by HynnSpylor** [comment]
one new seq from Singapore

**Comment by ryhisner** [comment]
The sequences from Singapore today has travel history to Ghana. I think there's a good chance this variant originated in Africa somewhere. EPI_ISL_17694854

**Comment by FedeGueli** [comment]
@InfrPopGen @corneliusroemer ping you here for fast review of this one, very likely it is widely bigger than shown by sequence count

**Comment by ryhisner** [comment]
Democratic Republic of Congo (DRC) uploaded 14 sequences today, and 13 of them are XBB.1.41. Only one has a month and day listed, and it is from May 4. I think this is pretty good evidence that XBB.1.41 is dominant in DRC and possibly surrounding countries as well. 

The DRC sequences are scattered widely about the XBB.1.41 Usher tree. 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_27a6_78da80.json?c=gt-S_335&label=id:node_6658034
<img width="1495" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/fee020fd-e6d2-49a6-81eb-32782e8b786f">
