### ISSUE TITLE
XBB.1/XBB.1.5 Sublineage with S:I19L, S:K147N, S:R403K, S:S486P, S:S494P, S:L582R, S:A688P, ORF9b:D89E, ORF1a: T346I, ORF1a:K3499R (Guatemala, 10 seq, May 17)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1999]
### **Description**
**Sub-lineage of:** XBB.1(.5)
**Earliest sequence:** 2023-4-24, Guatemala — EPI_ISL_17674889
**Most recent sequence:** 2023-5-3, Guatemala — EPI_ISL_17674913, EPI_ISL_17674914
**Countries circulating:** Guatemala (10)
**Number of Sequences:** 10
**GISAID AA Query:** Spike_L582R, Spike_A688P
**GISAID Nucleotide Query:** T23307G, G23624C
**CovSpectrum Query:** Nextcladepangolineage:XBB.1* & [5-of: C1302T, G4255A, A10761G, A21507G, A22003T, A21617C, G22770A, T23018C, T23042C, T23307G, G23624C, C25386T, C28550A]
**Substitutions on top of XBB.1:**
**Spike:** I19L, K147N, R403K, S486P, S494P, L582R, A688P
**ORF9b:** D89E
**ORF1a:** T346I, K3499R (NSP2_T166I, NSP5_K236R)
**Nucleotide:** C1302T, G4255A, A10761G, A21507G, A22003T, A21617C, G22770A, T23018C, T23042C, T23307G, G23624C, C25386T, C28550A
 

**USHER Tree**
**Note 1**: All these sequences have S:K147N, but Usher apparently masks this, likely do to the large number of sequencing artifacts in the 144-146 area in XBB.
**Note 2**: I think the Usher placement is probably incorrect. None of these sequences show evidence of having the three-nucleotide ORF7b:A43L mutation (which involves extended homology for the ORF8 TRS—which, strangely, should lead to increased expression of the severely truncated, 7-amino acid ORF8 in XBB.1, perhaps indicating that something entirely different is afoot). Seven of the 10 sequences lack coverage in that area, but the three with coverage do not have any of the three nucleotide mutations there.
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1_+_I19L_R403K_S486P_L582R_A688P.json?c=gt-S_19&label=id:node_3679522
<img width="1510" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/5ad8934d-24a7-42d8-81ae-33bff0252c6d">

**Evidence**
These 10 sequences come from six different cities in Guatemala, including five from the city of Guatemala and one each from Mixco, Palencia, Retalhuleu, Santa Lucia Cotzumalguapa, and Villa Nueva. (All have been very recently collected: one April 24, one April 28, and the other eight from May 1-3. Guatemala is a very undersequenced country, as are the surrounding countries, so ten sequences might represent a substantial prevalence in the country or region.
All sequences have S:K147N, but for some reason it does not show up in the Usher tree.
 
ORF9b:D89E is also found in BA.2.3.20, the extremely odd BA.2 lineage that briefly appeared across Ukraine, and a lot of chronic-infection sequences.
 
One sequence here has S:P337S and another has S:L513F. The latter marks at least the third time that XBB.1 + S:R403K + S:S486P + S:L513F has independently arisen.

Seven sequences here have ORF1a:R4387S (C13424A), and at least one of the other three has no coverage in that area, so it's possible that all 10 sequences have this mutation. It forms a suboptimal novel TRS-B that is often accompanied, in other sequences, with one or two additional nucleotide mutations that further optimize the TRS-B. This TRS-B is followed by an in-frame start codon, so the effect would presumably to increase the expression of ORF1b.

The first diagram below is the single-nucleotide mutation found in this lineage. Below it is the three-nucleotide mutation seen in a number of other sequences/lineages, which forms an optimal TRS-B motif. 
<img width="1504" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/45e996bd-a140-4977-abb6-fe63c6faf99c">
<img width="1504" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/5bedf8b1-e5ea-4d55-8ad5-2522304987ea">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17674889, EPI_ISL_17674903, EPI_ISL_17674907-17674914
</details>

**Comment by HynnSpylor** [comment]
Great catch! I am just preparing to propose it.
One seq is absent in S:355-523, I suppose it should also get R:403K &S:S494P
![QQ截图20230518045654](https://github.com/cov-lineages/pango-designation/assets/121703496/34e68e1e-f97f-450d-8513-93f8d40385f7)
![QQ截图20230518045637](https://github.com/cov-lineages/pango-designation/assets/121703496/e6f91aae-681f-494f-9e57-6df7fca86c15)

**Comment by FedeGueli** [comment]
Interestingly it is the same part of the tree shown first by @corneliusroemer here: https://github.com/sars-cov-2-variants/lineage-proposals/issues/2 Do you think the Orf7b:A43L triple nuc is real?

**Comment by corneliusroemer** [comment]
Just came here to see if this was already opened by someone else ;)

Agree that this is an interesting lineage, let's designate asap once there's evidence of spread, meaning sequences from outside of Guatemala. Right now it's all Guatemala.

**Comment by ryhisner** [comment]
The triple-nuc ORF7b:A43L (which consists of C27881T, G27882C, & C27883T) is definitely real, but I don't think this lineage actually has it. One of the three nucleotides (C27881T) is actually in ORF7b:42 and is synonymous. Like the multiple-nucleotide mutations at the end of ORF8, which are much more common than the ORF7b 3-nuc mutations, this is a transcription-regulation sequence (TRS) phenomenon. These three nucleotide mutations create extended homology for the ORF8 TRS, which means they create a sequence that more closely resembles the TRS-L at the beginning of the genome. The more closely a TRS-B for a given sgRNA resembles the TRS-L, the more likely it is to be transcribed, so extended homology for a given TRS-B should increase the expression of the sgRNA downstream of it. 

<img width="1373" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/7ab34639-b412-4a11-a4e4-bdec4932e422">


There have been multiple forms of this ORF7b mutation. Some only have C27881T & G27882C and result in ORF7b:A43P. A common one is three nucleotide mutations accompanied by a two-nucleotide deletion. 
<img width="1400" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/c013b819-7078-45f0-ba7f-60fa7ecae50d">

A four-nucleotide mutation form that forms 5/8 of a second, novel ORF8 TRS upstream of the main one, and which also has four nucleotides of extended homology. 
<img width="1506" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/d4372fc7-b6a6-475c-9d18-04c2fb1a0832">

XBB.1 lineages have ORF8:G8*, and it seems extremely unlikely that the function of these multi-nuc ORF7b mutations is to make more 7-amino-acid peptides consisting of the first seven AA in ORF8. My only hypothesis is that this extended homology causes the RdRp to skip to the TRS-L more frequently at this spot, meaning that it's free to find another genome and start scanning again. (The RdRp scans "backwards.") This would increase the expression and the amount of cellular resources available for N and ORF9b, since they are the only sgRNAs up stream of this TRS-B and are therefore not directly affected by its more frequent diversion of the RdRp. This hypothesis also fits well with the extremely common acquisition of extended homology for the N/ORF9b TRS-B, which has independently evolved many thousands of times, and which appears to confer a small growth advantage in whatever lineage acquires it (though this small growth advantage has always been overwhelmed by larger, more dramatic changes in the variant landscape, obscuring its effect within a given lineage).

**Comment by ryhisner** [comment]
Two quick observations: First, these 10 sequences represent ~22% of the sequences collected in Guatemala since April 24, and the eight sequences collected in May make up ~30% of Guatemalan sequences collected in May. 

Second, S:L582R is a T->G nucleotide mutation, which is the second-rarest type (next to C->G), making up less than 2% of all nucleotide mutations. 

S:L582R has been an extremely rare mutation throughout the pandemic, appearing in just 68 sequences all time. However, there have been 10 sequences with S:L582R appear in the last three months, all of them in XBB + S:S486P lineages—six XBB.1.16, two XBB.2.3, one FD.4, and one XBB.1.5. The six XBB.1.16 with S:L582R are all related and have appeared in South Korea (4 seq), Hong Kong (1), and Zhejiang, China (1).

<img width="1108" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/c8694116-3865-4f7f-b19d-99f8ee51defc">

**Comment by oobb45729** [comment]
Did you find anything that has this ORF7b thing along with an interesting ORF8 (like Mu)?
All there ORF8 mutations of Mu (ORF8:T11K, ORF8:P38S, ORF8:S67F) happen quite frequently (even in lineages with ORF8:G8*).
ORF8:T11K is really puzzling. Why would this C->A mutation repeatedly happen in lineages with ORF8:G8*?

**Comment by FedeGueli** [comment]
Thans @ryhisner great explanation on orf7b!
let me add that 688P (we have already seen 688V successful on BQ.1 backbone) gives as Fcs surroundings the following sequence:
SYQTQTKSHRRARSVPSQ

**Comment by ryhisner** [comment]
@oobb45729, I haven't noticed any that have the TRS that also have interesting ORF8 mutations, but I haven't looked especially hard. 

Agree that ORF8:T11K, ORF8:P67S, and some others (including multiple forms of multi-nucleotide mutations around ORF8:80-81) are really hard to explain in lineages with ORF8:G8*. My only idea is that it has something to do with secondary RNA structure. It's possible there's some minor alternative reading frame in there, I guess, but I don't recall seeing any especially notable ones in the studies I've read that have looked for alternative ORFs, and I've never seen a novel TRS-like motifs in ORF8 that I can recall.

**Comment by ryhisner** [comment]
I don't want to crowd this proposal with too much ORF7b/ORF8 talk (particularly as the mutation most likely isn't in this lineage at all), so I've started a new discussion thread on the subject on the pre-proposal forum. I copied and pasted all the relevant comments from this issue so that no one has to go back and forth to follow the discussion. @oobb45729 @FedeGueli   https://github.com/sars-cov-2-variants/lineage-proposals/issues/70

**Comment by AngieHinrichs** [comment]
> Note 2: I think the Usher placement is probably incorrect. None of these sequences show evidence of having the three-nucleotide ORF7b:A43L mutation

Looks like the daily matOptimize has fixed that initial bad placement as of the 2023-05-17 tree.

**Comment by Sinickle** [comment]
3 more sequences, still Guatemala. 
Collected 5/4, 5/6, 5/8. 

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2eb92_b6ea50.json

![image](https://github.com/cov-lineages/pango-designation/assets/94097102/92da0cb5-fd27-4123-9e92-950ca4420685)
They come from different branches on the tree.

**Comment by Memorablea** [comment]
13 seqs now

**Comment by ryhisner** [comment]
Incredibly, despite having been detected in numerous regions of Guatemala, this thing seems to have disappeared. It's very reminiscent of the bizarre BA.2 lineage that suddenly showed up in like 6 regions of Ukraine, then vanished. Closing this as it seems very unlikely to be revived.
