### ISSUE TITLE
Novel lineage with key amino acid SNPs and a 9bp spike insertion

### ISSUE THREAD

**Issue by aineniamh** [cov-lineages/pango-designation#20]
### Proposed lineage name
B.1.214.2

### Description

Sub-lineage of: B.1.214
Countries circulating:  Belgium, Denmark, Switzerland, France, Mayotte

### Mutations 
```
S
9bp insertion 22204:ACAGATCGA
S:Q414K
S:N450K
S:T716I

ORF3a
30bp deletion 25448-25478

ORF1a deletion 11288-11297
```

The 9bp insertion in spike at position 22204:ACAGATCGA inserts the amino acids TDR downstream of R214. It also has a 30bp deletion in ORF3a (25448-25478) and approximately 60% of the samples have a 9bp deletion in ORF1a (11288-11297), the same deletion observed in the lineages B.1.1.7, B.1.351, B.1.525 and P.1. 

### Taxa
183 sequences on GISAID
![image](https://user-images.githubusercontent.com/11678307/109653475-faccdb00-7b58-11eb-89dd-a819191db14a.png)

[B.1.214_2021-03-02.lineages.csv.zip](https://github.com/cov-lineages/pango-designation/files/6068697/B.1.214_2021-03-02.lineages.csv.zip)

### Evidence
<img width="921" alt="Screenshot 2021-03-02 at 12 50 42" src="https://user-images.githubusercontent.com/11678307/109651000-e804d700-7b55-11eb-8ae7-c05d22276b97.png">
Red = B.1.214
Green = B.1.214.1 (Congo/ France lineage)
Blue = B.1.214.2 (European/ Belgian lineage with key mutations and insertion mutation)

### Suggested by

Keith Durkin, Piet Maes, Simon Dellicour, Guy Baele, Áine O'Toole, Andrew Rambaut

**Comment by rambaut** [comment]
This needs updating to record B.1.214.3 & B.1.214.4

**Comment by aineniamh** [comment]
## Updates:
Updated designations for sublineages of B.1.214. 
Now 4 sister lineages, B.1.214.1 from Congo, B.1.214.2 from Belgium with a defining 9bp insertion in the NTD of the spike gene, B.1.214.3 a french lineage and B.1.214.4 a Danish lineage.

```
B.1.214   43
B.1.214.1 20
B.1.214.2 344
B.1.214.3 58
B.1.214.4 89
```
Full details and sequence names at release [v1.1.6](https://github.com/cov-lineages/pango-designation/releases/tag/v1.1.6).
