### ISSUE TITLE
Proposal for new P.X lineage in Brazil with conserved spike mutations: F2L, Q14K, G75S, N501Y, Q677H, V1167F

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#200]
**New proposed lineage
By Tom Peacock**

**Description
Sub-lineage of:** B.1.1.28
**Earliest Sequence:** 2021-02-18
**Latest Sequence:** 2021-07-14 
**Countries circulating:** Brazil (12 sequences currently)

**Description:**
Conserved Spike mutations - F2L, Q14K, G75V, T95I*, G142D*, N501Y, D614G,  S640F*, Q677H, D936G/V(*), V1176F  (*found in majority)

Conserved non-Spike mutations - NSP2 – I101T; NSP3 – D821N; NSP4 – D459N; NSP6 – del106-108; NSP12 – P323L; NSP13 – S350L; M – I82T; ORF8 – Q29*STOP; N - R203K, G204R, G215C

**Genomes:**

EPI_ISL_1966646, EPI_ISL_2479922, EPI_ISL_2493202, EPI_ISL_2614253, EPI_ISL_2698099, EPI_ISL_2698102, EPI_ISL_2698105, EPI_ISL_2698106, EPI_ISL_3255132, EPI_ISL_3316275, EPI_ISL_3545782, EPI_ISL_3553692

**Evidence:**

![image](https://user-images.githubusercontent.com/79373149/130615529-d1b48882-451e-463f-ae8a-4689936a0444.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_66c4e_4e42f0.json

**Proposed lineage name:** P.X

**Comment by chrisruis** [comment]
Thanks for submitting @thomasppeacock. It looks like there's only 2 sequences from this clade collected in the past 3 months so we'd recommend putting a monitor label on this for now and checking it again in a couple of weeks. Thanks again

**Comment by thomasppeacock** [comment]
Quite a lot of sequences coming out of Brazil but none of this - I'm going to close for now but may reopen if anything else pops back up
