### ISSUE TITLE
Continuously growing FY.3 (XBB.1.22.1.3) and ORF1ab: E3764G (A11556G=NSP6-E195G) appear in China（628 seqs, from China, South Korea, United States, Australia, France, Germany, Canada, Laos, Singapore,Austria, Malaysia,Japan，Luxembourg）

### ISSUE THREAD

**Issue by Memorablea** [cov-lineages/pango-designation#2000]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/64

Lineage of:XBB.1.22.1.3 with ORF1ab: E3764G (A11556G) = NSP6_E195G
Earliest sequence:2023-03-31
Most recent sequence:2023-05-11
GISAID Search： G2513A,C23191T,A11556G

sequence：
<details><summary>Genomes:</summary>
EPI_ISL_17652363，EPI_ISL_17645500，EPI_ISL_17645475，EPI_ISL_17645474，EPI_ISL_17645465，EPI_ISL_17645449，EPI_ISL_17645441，EPI_ISL_17645433，EPI_ISL_17625392，EPI_ISL_17625374，EPI_ISL_17625364，EPI_ISL_17625345，EPI_ISL_17625330，EPI_ISL_17625308，EPI_ISL_17625289，EPI_ISL_17625288，EPI_ISL_17625287，EPI_ISL_17625282，EPI_ISL_17625271，EPI_ISL_17625270，EPI_ISL_17625263，EPI_ISL_17615025，EPI_ISL_17615020，EPI_ISL_17615013，EPI_ISL_17615000，EPI_ISL_17614998，EPI_ISL_17614996，EPI_ISL_17614995，EPI_ISL_17614993，EPI_ISL_17614990，EPI_ISL_17614982，EPI_ISL_17614981，EPI_ISL_17614978，EPI_ISL_17545759，EPI_ISL_17545753，EPI_ISL_17545732，EPI_ISL_17545718，EPI_ISL_17545717，EPI_ISL_17545710，EPI_ISL_17545698，EPI_ISL_17545692，EPI_ISL_17545691，EPI_ISL_17545687，EPI_ISL_17545671，EPI_ISL_17545653，EPI_ISL_17545645，EPI_ISL_17545641，EPI_ISL_17511956，EPI_ISL_17501449，EPI_ISL_17485743，EPI_ISL_17684362，EPI_ISL_17684361，EPI_ISL_17684324，EPI_ISL_17684111，EPI_ISL_17672060，EPI_ISL_17672048，EPI_ISL_17672032，EPI_ISL_17672021，EPI_ISL_17672018，EPI_ISL_17672003，EPI_ISL_17671999，EPI_ISL_17671996，EPI_ISL_17671993，EPI_ISL_17671987，EPI_ISL_17671986，EPI_ISL_17671955，EPI_ISL_17671935，EPI_ISL_17671932，EPI_ISL_17671918，EPI_ISL_17671909，EPI_ISL_17671898，EPI_ISL_17671895
</details>

![image](https://github.com/cov-lineages/pango-designation/assets/125779492/177a3062-7591-4c8b-b4e5-b3ad8aa547e3)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_17caa_761010.json?label=id:node_3638243

Editor: Thank you @FedeGueli 
![image](https://github.com/cov-lineages/pango-designation/assets/125779492/b2a2acd7-fdd1-4550-8819-6b7218bbdfaf)

**Comment by Memorablea** [comment]
One from Fujian.
EPI_ISL_17689380

**Comment by Memorablea** [comment]
One from Fujian. 83 seqs now

**Comment by Memorablea** [comment]
Four sequences from Hubei

**Comment by Memorablea** [comment]
One sequences from Sichuan

**Comment by Memorablea** [comment]
6 from Shanghai and 1 from Hubei.95 seqs now.

**Comment by Memorablea** [comment]
Today's from Hubei and Anhui.110 seqs now.

**Comment by Memorablea** [comment]
At present, there are 112 items, which continue to grow. I suggest specifying it.@corneliusroemer

**Comment by Memorablea** [comment]
1 form Anhui

**Comment by Memorablea** [comment]
Sequence from June 5th: This branch has already leaked to France, with another one from Anhui.

**Comment by Memorablea** [comment]
4 form Shanghai

**Comment by Memorablea** [comment]
124 NOW

**Comment by Memorablea** [comment]
He should have been designated because there are currently 125 sequences (continuously increasing), and this lineage has been dispersed to three countries (China, France, and the United States) since it was born in China.@corneliusroemer

**Comment by FedeGueli** [comment]
@Memorablea i think that while this lineage has a regional relevance when compared to FY.3 strikingly does not show any advantage: https://cov-spectrum.org/explore/Asia/AllSamples/Past3M/variants?nextcladePangoLineage=FY.3*&aaMutations1=ORF1a%3AE3764G&analysisMode=CompareToBaseline& 
I think if this will change @corneliusroemer and @InfrPopGen will designate it.

**Comment by Memorablea** [comment]
Continuing to spread: detected in Australia, currently 128 sequences from 4 countries

**Comment by Memorablea** [comment]
Singapore has detected 6 countries, so we will continue to wait for other country sequences to grow.

**Comment by Memorablea** [comment]
This bloodline has suddenly updated many sequences, and I still recommend specifying it. Increase to 162.

**Comment by Memorablea** [comment]
Sequences from Fujian, Australia, and Hubei. Total: 138.Two states in Australia have detected three cases, with the earliest being May 23 and the latest being May 28. It is recommended to continue tracking.

**Comment by Memorablea** [comment]
There are currently 182 cases, one of which comes from the United States and this lineage has been detected in multiple countries

**Comment by Memorablea** [comment]
There are currently 197 items, which are continuously increasing. There are already 3 sequences from Australia, 2 sequences from the United States, and 1 sequence from France

**Comment by FedeGueli** [comment]
ping @corneliusroemer to me this should be designated. it reached 19 out of 107 samples collected in June in Hubei.

**Comment by Memorablea** [comment]
It should be emphasized that this lineage has already overflowed. There are 228 sequences today, including 2 from the United States, 2 from Singapore, and 1 from Australia. This lineage no longer seems to have regional characteristics, but rather reflects global circulation.

**Comment by FedeGueli** [comment]
> It should be emphasized that this lineage has already overflowed. There are 228 sequences today, including 2 from the United States, 2 from Singapore, and 1 from Australia. This lineage no longer seems to have regional characteristics, but rather reflects global circulation.

Could you specify prevalences in June in the region where it emerged (i think hubei?)

**Comment by Memorablea** [comment]
> > It should be emphasized that this lineage has already overflowed. There are 228 sequences today, including 2 from the United States, 2 from Singapore, and 1 from Australia. This lineage no longer seems to have regional characteristics, but rather reflects global circulation.
> 
> Could you specify prevalences in June in the region where it emerged (i think hubei?)

Hubei：13%

**Comment by FedeGueli** [comment]
30 out of 162 in June i see closer to 20% in my math. 
What makes me always a bit slow down on pushing this forward is the fact it doesnt show a clear advantage over the parental lineage both in micro
![Schermata 2023-06-27 alle 12 16 04](https://github.com/cov-lineages/pango-designation/assets/87669813/5d8ef664-7982-4b95-b170-a88703908cef)
as in Macro:
![Schermata 2023-06-27 alle 12 16 45](https://github.com/cov-lineages/pango-designation/assets/87669813/ef2b7db0-2359-4d6a-adee-aee31d76fa37)
Still i think @corneliusroemer would do the right thing in designating it, it will be helpful to describe the tree and as shown it is being seeded outside from China (Maybe due the fact that Wuhan is very well globally interconnected)

**Comment by Memorablea** [comment]
243 sequences can be considered as covert transmission. Today's guests come from Japan, France, and South Korea.

**Comment by Memorablea** [comment]
cc @AngieHinrichs @corneliusroemer @InfrPopGen

**Comment by FedeGueli** [comment]
I think this should be designated , being widespread and having China as well established headquarter i bet this will have time to further evolve and XBB.1.22.1 seems one of the lineage able to fix more new S1 mutations ( as shown by designated lineages with 197/210/451 mutated residues) and noted first by @hynnspylor and me.  @corneliusroemer pls take a look.

**Comment by HynnSpylor** [comment]
Yes it is a notable growing branch especially in Hubei Province. FY.3 is popular in Yangtze Plain (including Hubei, Anhui, Jiangsu and Shanghai), as FY.3.1 (with S:I210T) is more common in latter three and this branch concentrates in Hubei province

**Comment by Memorablea** [comment]
There are currently 269, Austria has increased from 4 to 7, South Korea has increased to 3, Canada has added 1, and the rest come from Sichuan and Yunnan

**Comment by Memorablea** [comment]
New 6, 2 from South Korea, 1 from the United States

**Comment by Memorablea** [comment]
cc @AngieHinrichs @corneliusroemer @InfrPopGen.Excuse me, please forgive me.

**Comment by Memorablea** [comment]
4 from South Korea, 4 from the United States, 3 from Japan, 2 from Australia, and 1 from Luxembourg

**Comment by Memorablea** [comment]
Sorry, it's just a typo

**Comment by Memorablea** [comment]
323 now

**Comment by Memorablea** [comment]
cc @corneliusroemer

**Comment by Memorablea** [comment]
@FedeGueli @corneliusroemer @AngieHinrichs @InfrPopGen

**Comment by FedeGueli** [comment]
> @FedeGueli @corneliusroemer @AngieHinrichs @InfrPopGen

@corneliusroemer i think it should be designated it is a clear big branch of FY.3 likely one of the biggest lineage in circulation

**Comment by Memorablea** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/125779492/5068376d-793a-4f73-af06-e37ef31a4666)

**Comment by FedeGueli** [comment]
> ![image](https://user-images.githubusercontent.com/125779492/259623078-5068376d-793a-4f73-af06-e37ef31a4666.png)

please add the link of the comaprison. I think this is going on circulating where EG.5.1 arose , keeping a solid 10% of share in Hubei in the samples collected after 15/07

**Comment by Memorablea** [comment]
594now

**Comment by Memorablea** [comment]
601 now

**Comment by Memorablea** [comment]
616now

**Comment by Memorablea** [comment]
628now

**Comment by Memorablea** [comment]
thanks
