### ISSUE TITLE
XBB.1.9.1 sublineage with S:D215V (A22206T) rapidly increases in China (169 seqs)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#2001]
*Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/62

Defining mutations: XBB.1.9.1>C3511T>A22206T(S:D215V)
GISAID query: Spike_D215V, C3511T, C11956T
Earliest seq: 2023-04-25 (Sichuan Province, China, EPI_ISL_17637501)
Most recent seq: 2023-05-08 (Hubei Province, China, EPI_ISL_17671943)
Countries detected: China (57, Hubei Province 27, Sichuan Province 21, Shanghai Municipality 6, Gansu Province 1, Henan Province 1, Heilongjiang Province 1)

Usher Tree:
![QQ截图20230519221000](https://github.com/cov-lineages/pango-designation/assets/121703496/74d7c843-87ef-4748-a61f-390aeff3c573)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3059b_77bd80.json
A very new sublineage in China, and it grows rapidly and distributes widely- Heilongjiang is in northeastern China while Sichuan in southwestern China.

Nowadays XBB.1.9.1 is the dominant sublineage in China, and the sublineage should be highly concerned.

Genomes:
EPI_ISL_17625358, EPI_ISL_17625461, EPI_ISL_17625620, EPI_ISL_17637501, EPI_ISL_17645399, EPI_ISL_17645402, EPI_ISL_17645453, EPI_ISL_17645470, EPI_ISL_17645642, EPI_ISL_17652398, EPI_ISL_17664522, EPI_ISL_17664524, EPI_ISL_17664544, EPI_ISL_17664547, EPI_ISL_17664551, EPI_ISL_17664570, EPI_ISL_17671912, EPI_ISL_17671940, EPI_ISL_17671943, EPI_ISL_17671958, EPI_ISL_17671980,
EPI_ISL_17672057, EPI_ISL_17678295, EPI_ISL_17678310, EPI_ISL_17678340, EPI_ISL_17678402, EPI_ISL_17683972, EPI_ISL_17683976, EPI_ISL_17684009, EPI_ISL_17684015, EPI_ISL_17684045, EPI_ISL_17684066, EPI_ISL_17684088, EPI_ISL_17684096, EPI_ISL_17684120, EPI_ISL_17684125, EPI_ISL_17684135, EPI_ISL_17684140-17684141, EPI_ISL_17684150, EPI_ISL_17684152, EPI_ISL_17684161, EPI_ISL_17684192-17684193, EPI_ISL_17684202, EPI_ISL_17684326, EPI_ISL_17684417, EPI_ISL_17684423, EPI_ISL_17684425, EPI_ISL_17684431-17684434, EPI_ISL_17684437-17684438, EPI_ISL_17684443, EPI_ISL_17684467,

**Comment by HynnSpylor** [comment]
2 more seqs from Singapore. Notice that one is local case, and another with travel history to USA

**Comment by aviczhl2** [comment]
Worth noting that currently top 5 fastest lineages on collection42 https://cov-spectrum.org/collections/42 are all Chinese variants.

**Comment by FedeGueli** [comment]
@aviczhl2 to me that reflects recency of sequences uploaded. China has shortened time from collection to upload and increased its global share of genomes uploaded to Gisaid. 
Not sure this explains everything maybe just one factor of many

**Comment by aviczhl2** [comment]
> @aviczhl2 to me that reflects recency of sequences uploaded. China has shortened time from collection to upload and increased its global share of genomes uploaded to Gisaid. Not sure this explains everything maybe just one factor of many

Yeah among those variants only EG.5.1 shows a global advantage.

**Comment by FedeGueli** [comment]
> > @aviczhl2 to me that reflects recency of sequences uploaded. China has shortened time from collection to upload and increased its global share of genomes uploaded to Gisaid. Not sure this explains everything maybe just one factor of many
> 
> Yeah among those variants only EG.5.1 shows a global advantage.

Yeah but this one seems very fast look at last weeks of may:
![Schermata 2023-05-30 alle 18 06 06](https://github.com/cov-lineages/pango-designation/assets/87669813/15dfc2de-d783-4afb-ae9a-98316d836903)

cc @InfrPopGen @corneliusroemer looking at Chinese data only on Covspectrum (reliable cause they have cut timing from sampling to uploading) this seems quite doubling every week
https://cov-spectrum.org/explore/China/AllSamples/from%3D2023-05-01%26to%3D2023-05-30/variants?aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

**Comment by HynnSpylor** [comment]
113 seqs now. In addition, South Korea updated 12 seqs with Spike mutation only. It seems like XBB.1.9.1+S:D215V but can not be confirmed.

**Comment by aviczhl2** [comment]
> Yeah but this one seems very fast look at last weeks of may: ![Schermata 2023-05-30 alle 18 06 06](https://user-images.githubusercontent.com/87669813/242027613-15dfc2de-d783-4afb-ae9a-98316d836903.png)


I guess this may partially due to provincial uploading issues. Different provinces of China upload differently, and when some increases their sequences the provincial local dominated variants start to have a false advantage. 

Unfortunately cov-spectrum cannot do province-level growth analysis, can it?

**Comment by FedeGueli** [comment]
No it canon the growth advantage tool show more button

**Comment by aviczhl2** [comment]
> No it can on the growth advantage tool show more button

Yeah. This one do have a quite high relative advantage against its parent XBB.1.9.1 in provincial level.

<img width="724" alt="Screenshot 2023-06-09 at 01 32 27" src="https://github.com/cov-lineages/pango-designation/assets/10445944/725b7a30-7195-4b2d-9697-cbcece857bdf">
<img width="727" alt="Screenshot 2023-06-09 at 01 32 21" src="https://github.com/cov-lineages/pango-designation/assets/10445944/c9c9fdb9-5f2b-46c9-af7d-3cb7cba66693">
<img width="725" alt="Screenshot 2023-06-09 at 01 31 46" src="https://github.com/cov-lineages/pango-designation/assets/10445944/9f47001b-186f-443e-bcc8-997ddd3a3ab5">

**Comment by aviczhl2** [comment]
169 seqs now.
