### ISSUE TITLE
Unusual BA.1(.1) with 59 (yeah fifty nice) S mutations 2 samples in The Netherlands

### ISSUE THREAD

**Issue by UnusualTimes** [cov-lineages/pango-designation#2004]
Unusual BA.1(.1) with 59 S mutations 2 samples in The Netherlands

Title says it all, may be a chronic patient or a bioinformatics issue. Anyone looking at it please ?

https://cov-spectrum.org/explore/Netherlands/AllSamples/Past1M/variants?nextcladePangoLineage=ba.1*&nextcladePangoLineage1=ba.1&

Insertions
Amino acids
• ins_S:210:IVREPED (2 seqs)
Nucleotides
• ins_22206:GCCAGAAGATAATGTTGT (2 seqs)
Substitutions and deletions
Export
Show amino acid and nucleotide mutations separated|Show amino acid and nucleotide mutations together
Filter by proportion
5
%

-
100
%

0%20%40%60%80%100%

Show deletions
Sort by position|Sort by proportion|Sort by Jaccard similarity
•ORF1a:E102V (66.67%, 0.67)•ORF1a:G519S (33.33%, 0.01)•ORF1a:K856R (100.00%, 0.67)•ORF1a:D1323A (66.67%, 0.67)•ORF1a:A1352V (66.67%, 0.11)•ORF1a:P1472T (33.33%, 0.33)•ORF1a:T1638I (66.67%, 0.11)•ORF1a:P1803S (66.67%, 0.22)•ORF1a:V1887I (66.67%, 0.22)•ORF1a:L2084I (100.00%, 0.60)•ORF1a:H2659Y (33.33%, 0.09)•ORF1a:A2710T (100.00%, 1.00)•ORF1a:D2980N (66.67%, 0.15)•ORF1a:T3255I (100.00%, 0.00)•ORF1a:P3395H (100.00%, 0.00)•ORF1a:I3758V (100.00%, 0.21)•ORF1a:D4085E (66.67%, 0.67)•ORF1a:D4117N (66.67%, 0.67)•ORF1a:T4164N (66.67%, 0.50)•ORF1b:P314L (100.00%, 0.00)•ORF1b:Q866R (33.33%, 0.33)•ORF1b:G1126C (66.67%, 0.67)•ORF1b:I1566V (33.33%, 0.00)•ORF1b:I1566L (66.67%, 0.18)•ORF1b:H2285Y (66.67%, 0.29)•ORF1b:T2537I (33.33%, 0.06)•S:N17D (66.67%, 0.67)•S:N30K (66.67%, 0.67)•S:A67V (100.00%, 0.50)•S:T76I (33.33%, 0.04)•S:T95I (100.00%, 0.10)•S:Y144F (66.67%, 0.50)•S:Y145D (100.00%, 0.18)•S:R158T (66.67%, 0.67)•S:L212I (33.33%, 0.08)•S:L212V (66.67%, 0.67)•S:G339D (100.00%, 0.01)•S:E340K (66.67%, 0.40)•S:R346K (100.00%, 0.27)•S:L368I (66.67%, 0.00)•S:S371L (100.00%, 0.75)•S:S373P (100.00%, 0.00)•S:S375F (100.00%, 0.00)•S:K417N (100.00%, 0.00)•S:D420N (66.67%, 0.40)•S:N440K (33.33%, 0.00)•S:N440R (66.67%, 0.67)•S:G446S (33.33%, 0.00)•S:N450D (33.33%, 0.08)•S:L452M (66.67%, 0.25)•S:S477N (100.00%, 0.00)•S:T478K (100.00%, 0.00)•S:E484A (100.00%, 0.00)•S:Q493R (33.33%, 0.33)•S:G496S (100.00%, 0.60)•S:Q498R (66.67%, 0.00)•S:T500N (33.33%, 0.33)•S:N501Y (100.00%, 0.00)•S:Y505H (100.00%, 0.00)•S:T547K (100.00%, 0.27)•S:D574V (33.33%, 0.20)•S:D614G (100.00%, 0.00)•S:P621S (66.67%, 0.03)•S:H655Y (100.00%, 0.00)•S:Q675H (66.67%, 0.02)•S:N679K (100.00%, 0.00)•S:P681H (100.00%, 0.00)•S:N764K (100.00%, 0.00)•S:Q787K (33.33%, 0.33)•S:T791I (33.33%, 0.33)•S:D796Y (100.00%, 0.00)•S:N856K (100.00%, 1.00)•S:D936Y (66.67%, 0.14)•S:Q954H (100.00%, 0.00)•S:A958S (66.67%, 0.33)•S:N969K (100.00%, 0.00)•S:L981F (100.00%, 1.00)•S:Q992H (66.67%, 0.67)•S:D1127G (33.33%, 0.33)•S:E1258Q (33.33%, 0.25)•ORF3a:K21N (33.33%, 0.05)•ORF3a:P42L (66.67%, 0.14)•ORF3a:S171L (66.67%, 0.06)•ORF3a:T175I (33.33%, 0.05)•E:T9I (100.00%, 0.00)•M:D3G (100.00%, 0.60)•M:Q19E (100.00%, 0.00)•M:A63T (100.00%, 0.00)•M:R146H (66.67%, 0.07)•N:P13L (100.00%, 0.00)•N:D22V (66.67%, 0.50)•N:R203K (100.00%, 0.00)•N:G204R (100.00%, 0.00)•N:T205N (33.33%, 0.14)•N:T362K (66.67%, 0.29)•ORF9b:P10S (100.00%, 0.00)•ORF9b:I19F (66.67%, 0.50)•ORF9b:D89E (66.67%, 0.14)

Leading and trailing deletions are excluded.
Sort by position|Sort by proportion|Sort by Jaccard similarity
• C241T (100.00%, 0.00)• A570T (66.67%, 0.67)• C1420A (66.67%, 0.67)• G1820A (33.33%, 0.01)• A2832G (100.00%, 0.67)• C3037T (100.00%, 0.00)• A4233C (66.67%, 0.67)• C4320T (66.67%, 0.11)• C4679A (33.33%, 0.33)• C5178T (66.67%, 0.11)• T5386G (100.00%, 1.00)• C5672T (66.67%, 0.22)• G5924A (66.67%, 0.22)• T6934C (66.67%, 0.67)• T7984C (66.67%, 0.33)• C8240T (33.33%, 0.09)• G8393A (100.00%, 1.00)• G9203A (66.67%, 0.15)• C10029T (100.00%, 0.00)• C10449A (100.00%, 0.00)• A11537G (100.00%, 0.20)• T12520A (66.67%, 0.67)• G12614A (66.67%, 0.67)• C12756A (66.67%, 0.50)• T12955C (66.67%, 0.67)• T13195C (100.00%, 0.75)• C14408T (100.00%, 0.00)• C15240T (100.00%, 0.13)• A16064G (33.33%, 0.33)• C16329T (66.67%, 0.07)• G16843T (66.67%, 0.67)• G17193A (33.33%, 0.25)• C18060T (33.33%, 0.04)• A18163G (33.33%, 0.00)• A18163T (66.67%, 0.18)• C18693T (66.67%, 0.40)• C19572T (33.33%, 0.03)• T20017C (33.33%, 0.33)• C20320T (66.67%, 0.29)• C21077T (33.33%, 0.06)• A21611G (66.67%, 0.67)• T21652A (66.67%, 0.67)• C21762T (100.00%, 0.50)• C21789T (33.33%, 0.04)• C21846T (100.00%, 0.10)• T21995G (66.67%, 0.12)• C22000T (66.67%, 0.13)• G22035C (66.67%, 0.67)• T22441A (33.33%, 0.33)• G22578A (100.00%, 0.00)• T22579C (66.67%, 0.18)• G22580A (66.67%, 0.33)• G22599A (100.00%, 0.27)• C22664A (66.67%, 0.00)• T22673C (100.00%, 0.75)• C22674T (100.00%, 0.00)• T22679C (100.00%, 0.00)• C22686T (100.00%, 0.00)• G22813T (100.00%, 0.00)• G22820A (66.67%, 0.40)• A22881G (66.67%, 0.67)• T22882G (100.00%, 0.00)• G22898A (33.33%, 0.00)• A22910G (33.33%, 0.08)• C22916A (66.67%, 0.07)• G22992A (100.00%, 0.00)• C22995A (100.00%, 0.00)• A23013C (100.00%, 0.00)• A23040G (33.33%, 0.33)• G23048A (100.00%, 0.60)• A23055G (66.67%, 0.00)• C23061A (33.33%, 0.33)• A23063T (100.00%, 0.00)• T23075C (100.00%, 0.00)• C23202A (100.00%, 0.27)• A23283T (33.33%, 0.20)• A23403G (100.00%, 0.00)• C23423T (66.67%, 0.03)• C23525T (100.00%, 0.00)• G23587C (66.67%, 0.25)• T23599G (100.00%, 0.00)• C23604A (100.00%, 0.00)• C23785T (33.33%, 0.14)• C23854A (100.00%, 0.00)• C23921A (33.33%, 0.33)• C23934T (33.33%, 0.33)• G23948T (100.00%, 0.00)• T23965C (33.33%, 0.33)• C24130A (100.00%, 1.00)• G24368T (66.67%, 0.14)• A24424T (100.00%, 0.00)• G24434T (66.67%, 0.33)• T24469A (100.00%, 0.00)• C24503T (100.00%, 1.00)• A24538C (66.67%, 0.67)• A24942G (33.33%, 0.33)• C25000T (100.00%, 0.00)• G25334C (33.33%, 0.25)• G25455T (33.33%, 0.05)• C25517T (66.67%, 0.14)• C25584T (100.00%, 0.00)• C25904T (66.67%, 0.05)• C25916T (33.33%, 0.05)• C26270T (100.00%, 0.00)• A26530G (100.00%, 0.60)• T26546C (33.33%, 0.25)• C26577G (100.00%, 0.00)• G26709A (100.00%, 0.00)• G26959A (66.67%, 0.07)• A27259C (100.00%, 0.00)• T27384C (66.67%, 0.00)• C27630A (33.33%, 0.14)• C27807T (100.00%, 0.00)• C27855T (66.67%, 0.50)• A28271T (100.00%, 0.00)• C28311T (100.00%, 0.00)• A28338T (66.67%, 0.50)• C28550A (66.67%, 0.13)• G28881A (100.00%, 0.00)• G28882A (100.00%, 0.00)• G28883C (100.00%, 0.00)• C28887A (33.33%, 0.14)• C29358A (66.67%, 0.29)• T29471C (33.33%, 0.33)

**Comment by ryhisner** [comment]
There are actually five sequences now in this one, and they are all from the same chronically infected patient. There seem to be at least two somewhat different intrahost variants that are alternating in dominance. 
Crazy, crazy sequences, but fortunately not transmitting at the moment.  
EPI_ISL_17241376, EPI_ISL_17389140, EPI_ISL_17535664, EPI_ISL_17621930, EPI_ISL_17654831
https://github.com/cov-lineages/pango-designation/issues/1844#issuecomment-1521785974
<img width="1502" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/25c585e2-3d24-47ce-919b-31c7ba5b072d">

**Comment by oobb45729** [comment]
Many familiar non-spike mutations here. ORF1a:H2659Y is in XBC.1.6.

**Comment by UnusualTimes** [comment]
Ahh yes i recall it now thank you Ryan. I wonder if an infection of this duration could recombine with further infections, especially from the highly transmissible XBBs in an environment where nobody is taking precautions. Have we run any of these S mutes through Bloom Labs evasion model ?

**Comment by UnusualTimes** [comment]
The reason i ask, i think its plausible that the NTD mutations in saltated xbbs might enhance gut binding via MGP in addition to ACE2. In which case we may see mutiple variant infections in different cell tissue confounding genome sampling. Cross contamination in the same patient.

**Comment by corneliusroemer** [comment]
Closing as single chronic for now which we don't designate, let us know in case this does start circulating in the community
