### ISSUE TITLE
New possible XBB.1 sublineage rapidly growing in Campania, Italy

### ISSUE THREAD

**Issue by agrimaldi93** [cov-lineages/pango-designation#2008]
### By:
Antonio Grimaldi, _Telethon Institute of Genetics and Medicine_, SARS-CoV-2 genome surveillance unit.
Other participants @fedegueli

### *Description*
**Sub-lineage of:** XBB.1

**Mutations:**
_NS7a_Q76stop
NS8_Q72H
NSP13_L138I
NSP3_Q1668P
NSP3_T847I
Spike_K964E_

**Earliest sequence:** The first sequence was collected in campania in 2023-02-21
**Most recent sequence:** The lineage is currently circulating, last collection in 2023-05-13

**Countries circulating:**
Country | Number
-- | --
Italy (Campania) | 126 (91)
France | 5
South Korea | 2
Israel | 1
USA | 2
United Kingdom | 1
Croatia | 2
Switzerland | 1
Spain | 1

**Genomes**
[gisaid_hcov-19_2023_05_22_12.txt](https://github.com/cov-lineages/pango-designation/files/11531279/gisaid_hcov-19_2023_05_22_12.txt)

**Evidence**
Fig.1: Increase in the incidence of the variant in Campania (as a result of our genomic surveillance program). The variant basal genotype has been growing in the region in the past 2 months and has reached incidence values higher than 25% in Campania.
![image](https://github.com/cov-lineages/pango-designation/assets/53193948/f8d92563-59d0-4fe5-a727-33587ed68514)

Fig.2: Iqtree produced with 1500 randomly selected sequences from gisaid and including the genomes of the possible new variant. Nodepoints represent the result of Ultrafast bootstrapping (UFB). The UFB value of the proposed cluster is 100.
![image](https://github.com/cov-lineages/pango-designation/assets/53193948/24dc6f7e-4c51-44ee-a098-21178fab0b35)

**Comment by FedeGueli** [comment]
Thanks for being watching this! Always great when people from the submitting labs catch their own variants! In this case it has already been designated XBB.1.33 after being spotted and proposed very early by @ryhisner  in #1879

**Comment by agrimaldi93** [comment]
Thank you, Federico, for the update; I must have lost ryhisner post!
