### ISSUE TITLE
FY.3 (XBB.1.22.1.3) sublineage with S:I210T (T22191C) and ORF1a:T1760I (C5544T) emerged in China (43 seqs in 2 countries) 

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#2009]
*Transferred from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/49

Defining mutations: FY.3>C23191T>C5544T(ORF1a:T1760I), T22191C (S:I210T), and near half of them further get C21998A (S:Q146K)
GISAID query: Spike_Y200C, Spike_I210T, T28297C, G2513A
Earliest seq: 2023-04-18 (Jiangsu Province, China, EPI_ISL_17637401)
Most recent seq: 2023-05-10 (Anhui Province, China, EPI_ISL_17689268)
Countries detected: China (38, Hubei Province 12, Shanghai Municipality 11, Anhui Province 10, Jiangsu Province 3, Shanxi Province 1, Fujian Province 1), Japan (1)

Usher Tree:
![QQ截图20230522224111](https://github.com/cov-lineages/pango-designation/assets/121703496/9d7c96a7-c3f2-45ac-9dc9-2da41812e695)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f3b3_ae2880.json

Based on FY.3 (XBB.1.22.1+ORF1a:E750K) which is highly concentrated and rapidly increased in China, a branch with S: I210T emerged recently. S:I210T was mainly in B.1.619* (once popular in South Korea) and B.1.640.1 lineages. 
Today it is first detected outside China, so I move it to pango-designation for further tracking and discussion.

The growth rate and share in China:
![QQ截图20230522223050](https://github.com/cov-lineages/pango-designation/assets/121703496/df1c11a9-fd85-4967-a00c-8a286d42a8c0)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AI210T&nextcladePangoLineage=XBB.1.22.1*&

Genomes:
EPI_ISL_17619115, EPI_ISL_17619169, EPI_ISL_17625260, EPI_ISL_17625280, EPI_ISL_17625311, EPI_ISL_17625409,
EPI_ISL_17625551, EPI_ISL_17625563, EPI_ISL_17637397, EPI_ISL_17637401, EPI_ISL_17637426, EPI_ISL_17645438,
EPI_ISL_17645454, EPI_ISL_17645740, EPI_ISL_17645764-17645765, EPI_ISL_17645806, EPI_ISL_17646194, EPI_ISL_17652351,
EPI_ISL_17652353-17652354, EPI_ISL_17671913, EPI_ISL_17671927, EPI_ISL_17671994, EPI_ISL_17672041, EPI_ISL_17672043,
EPI_ISL_17672046, EPI_ISL_17678358, EPI_ISL_17678442, EPI_ISL_17684260, EPI_ISL_17689266, EPI_ISL_17689268, EPI_ISL_17689270, EPI_ISL_17689276, EPI_ISL_17689286, EPI_ISL_17689315, EPI_ISL_17689317, EPI_ISL_17689359, EPI_ISL_17692058

**Comment by FedeGueli** [comment]
Designated FY.3 via https://github.com/cov-lineages/pango-designation/commit/0e8bf367927044e77e62b104aa602835bb6dd7d0
