### ISSUE TITLE
Potential new sub-lineage of B.1.617.2/AY with A208S and G215C

### ISSUE THREAD

**Issue by mcmillet** [cov-lineages/pango-designation#201]
by: Tracy McMillen and Krupa Jani

**Description**
**Sub-lineage of:** B.1.617.2
**Earliest sequence:** 8/11/21
**Countries circulating:** United States (NY)
**Pango Lineage**: None
**GISAID Clade:** GK

**Mutations:**
**M:** I82T
**N:** A208S, D3G, G215C, R203M
**ORF3a**: S26L
**S:** D614G, D950N, L452R, T478K

**Genomes:** EPI_ISL_3542766

**Evidence**
![image](https://user-images.githubusercontent.com/89280733/130645182-da55f814-8f1c-4a10-90cd-8f2b33296bf8.png)

**Comment by shay671** [comment]
It seems that there is only one sequence in this lineage : 
USHER analysis -
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_5e544_5502e0.json?label=nuc%20mutations:T7124C

![image](https://user-images.githubusercontent.com/80166370/130682557-041c7453-05da-4a0e-ad8a-0949f3e9603c.png)

**Comment by chrisruis** [comment]
Thanks @mcmillet for submitting. It appears that there's only 1 sequence currently in your proposed lineage. It is in a slightly larger clade of USA sequences but this clade isn't large enough to warrant a designation at this stage. We'd recommend referring to your sequence as B.1.617.2 for now. Thanks again
