### ISSUE TITLE
XBB.1.16.4 (S:T678i) sublineage with S:Q677H (22 seqs, Australia)

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#2010]
**Description**
Sub-lineage of: XBB.1.16.4 (XBB.1.16 + S:T678i)
Earliest sequence: 2023-3-26, Victoria Australia 
Most recent sequence: 2023-5-2, Sydney Australia (current)
Countries circulating: 1 (Australia - Victoria, Sydney)
Number of Sequences: 15 (12 Victoria, 3 Sydney)
GISAID AA Query: Spike_V445P, Spike_T678i, Spike_Q677H
[CovSpectrum Query](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A677h&nextcladePangoLineage=XBB.1.16.4&nextcladePangoLineage1=xbb.1.16&)
**Substitutions on top of XBB.1.16.4**: 
ORF1b:K1194N, ORF1b:I2078N,
S:Q677H

[Usher Tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_50f5_b7c960.json)
![image](https://github.com/cov-lineages/pango-designation/assets/94097102/29b6297c-8973-4dad-aeef-89642029564d)

**Discussion:**
Although this lineage is still small and localized to Australia, I'm proposing it due to the interesting double FCS mutation. 
This double FCS mutation is brand new to Omicron, but actually has been seen multiple times in the past, including on Delta, C.36, B.1.1.50, B.1.525, B.1.1.7. 
These other lineages make up a variety of different FCS. However, this is its first emergence on an FCS with S:Q677H, S:T678I, S:N679K, S:P681H. 

Overall, I don't think that this combo has shown up many times indicates it works especially well together -- S:Q677H is a common mutation throughout much of the pandemic, and S:T678i isn't exactly rare. S:T678i is somewhat more likely to show up if S:Q677H is already present, but not enough to make a clear argument. 

**Genomes:** EPI_ISL_17612743, EPI_ISL_17656204, EPI_ISL_17656511, EPI_ISL_17656030, EPI_ISL_17409249

**Comment by FedeGueli** [comment]
FCS +Flanking residues sequence should be SYQTHIKSHRRARSVASQ really far from WT.

**Comment by Sinickle** [comment]
It died.

**Comment by FedeGueli** [comment]
thx @Sinickle it wont be the only one lineage ending this way in the next few weeks. ;)

**Comment by FedeGueli** [comment]
wrong repo
