### ISSUE TITLE
FL.2 sublineage with Orf1b:K1383R circulating in China and other countries (489 seq) and then N:R189L (187 seq)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2016]
FL.2 + Orf1b:K1383R (A17615G)
Transferred from [sars-cov-2-variants/lineage-proposals](https://github.com/sars-cov-2-variants/lineage-proposals/issues/78)

GISAID Query: C11956T, T4579A, A17615G
Earliest Sequence: 02-23 Singapore (imported from Saudi) EPI_ISL_17146466
Latest Sequence: 05-30 Lower Austria, Austria EPI_ISL_17782554

Regions Detected:

China 421+8: Guangdong 223(2 detected at Zhuhai Custom, probably imported from Macao), Hubei 86, Shanghai 37 (including 2 from Singapore, 2 from Thailand, 2 from Vietnam, 1 from HK,  1 from HK or Macao, 1 from Macao, 1 from Malaysia, 1 from S. Korea, 1 from Russia, 1 from UAE, 1 from unknown region), Fujian 20 (including 1 from Thailand), Yunnan 19, Sichuan 12, Heilongjiang 6, Xinjiang 5, Anhui 4, Shanxi 3, Qinghai 3, Zhejiang 2, Gansu 1; Hong Kong 7, Taiwan 1 (from Mainland);

Singapore 9 (1 from Saudi, 1 from China Mainland, 1 from HK, 1 from Japan), South Korea 9(1 from China Mainland, 1 from Taiwan), Japan 4 (2 from China), Malaysia 2;
Spain 3, Austria 2, France 2, Sweden 2, Russia 2, UK 2, Ireland 1, Netherlands 1;
US 14(9 Imported, 2 from Taiwan, 1 from Germany, 1 from Singapore, 1 from S. Korea, 4 airport screening), Canada 1;
Australia 4, NZ 2.

<details><summary>Already detected in 17/21 cities in Guangdong Province.</summary>
The sequences collected in Huizhou have 4388-4648 missing, therefore lost T4579A mutation.

Heyuan and Yangjiang did not upload sequence this time.
What means, Shanwei is the only city in Guangdong where did not detect this sequence.</details>Among sequences upload on 05-22, 27.0%(211/782) sequences in Guangdong Province and 45.0%(90/200) sequences in Guangzhou City belong to this sublineage. 

And Guangdong CDC updates sequences samples monthly now, the next time updating will be at the end of next month.

Maybe already circulate in low-sequencing regions e. g. Macao, Taiwan, UAE, Saudi etc.

[Genome Tree](https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_39469_cdac30.json)
![2023-05-24](https://github.com/cov-lineages/pango-designation/assets/38100637/d8326a61-9b9c-4c56-b898-76fc5cdf53df)
The sequences without C11956T are assigned manually as XBB.1.9, and the sequences without T4579A are assigned manually as XBB.1.9.1, and the sequences suspected to be recombined with DY.4/XBB.1.16/XBB.1.16.1 are assigned as the corresponding lineage.

<details><summary>Sequences:</summary>
EPI_ISL_17146466, EPI_ISL_17298736, EPI_ISL_17333208,
EPI_ISL_17545640, EPI_ISL_17547923, EPI_ISL_17584630,
EPI_ISL_17584634, EPI_ISL_17584636, EPI_ISL_17584640-17584642,
EPI_ISL_17584645, EPI_ISL_17584649, EPI_ISL_17584653,
EPI_ISL_17584655, EPI_ISL_17584676, EPI_ISL_17584688,
EPI_ISL_17615002, EPI_ISL_17620290, EPI_ISL_17625276,
EPI_ISL_17625279, EPI_ISL_17625305, EPI_ISL_17625310,
EPI_ISL_17625315, EPI_ISL_17625324, EPI_ISL_17625329,
EPI_ISL_17625339, EPI_ISL_17625341, EPI_ISL_17625344,
EPI_ISL_17625353, EPI_ISL_17625360, EPI_ISL_17625383-17625384,
EPI_ISL_17625386, EPI_ISL_17625389-17625390, EPI_ISL_17625413,
EPI_ISL_17625431, EPI_ISL_17625462, EPI_ISL_17625484,
EPI_ISL_17625499, EPI_ISL_17625517, EPI_ISL_17625561,
EPI_ISL_17625567, EPI_ISL_17625585, EPI_ISL_17632975-17632976,
EPI_ISL_17633004, EPI_ISL_17637623, EPI_ISL_17637640,
EPI_ISL_17645421, EPI_ISL_17645435, EPI_ISL_17645472,
EPI_ISL_17645476, EPI_ISL_17645482, EPI_ISL_17645485-17645486,
EPI_ISL_17645513, EPI_ISL_17645516, EPI_ISL_17645689,
EPI_ISL_17645761, EPI_ISL_17645781, EPI_ISL_17645945,
EPI_ISL_17652315, EPI_ISL_17652358, EPI_ISL_17654834,
EPI_ISL_17664527, EPI_ISL_17664543, EPI_ISL_17664763,
EPI_ISL_17664766, EPI_ISL_17669410, EPI_ISL_17671914,
EPI_ISL_17671919, EPI_ISL_17671928, EPI_ISL_17671938,
EPI_ISL_17671944-17671945, EPI_ISL_17671949, EPI_ISL_17671951,
EPI_ISL_17671956-17671957, EPI_ISL_17671976, EPI_ISL_17671985,
EPI_ISL_17671997-17671998, EPI_ISL_17672004-17672005, EPI_ISL_17672017,
EPI_ISL_17672024, EPI_ISL_17672062, EPI_ISL_17673622,
EPI_ISL_17678284, EPI_ISL_17678311, EPI_ISL_17678338,
EPI_ISL_17678369, EPI_ISL_17678372, EPI_ISL_17678427,
EPI_ISL_17678450, EPI_ISL_17680003, EPI_ISL_17684000,
EPI_ISL_17684028, EPI_ISL_17684038, EPI_ISL_17684126,
EPI_ISL_17684191, EPI_ISL_17684328-17684329, EPI_ISL_17684360,
EPI_ISL_17684398, EPI_ISL_17684401, EPI_ISL_17684403-17684404,
EPI_ISL_17684406, EPI_ISL_17684412, EPI_ISL_17684426,
EPI_ISL_17684430, EPI_ISL_17688136, EPI_ISL_17689324,
EPI_ISL_17689340, EPI_ISL_17689358, EPI_ISL_17689360,
EPI_ISL_17689391, EPI_ISL_17689401, EPI_ISL_17689404-17689405,
EPI_ISL_17689777, EPI_ISL_17689831, EPI_ISL_17694789,
EPI_ISL_17694888, EPI_ISL_17695035, EPI_ISL_17696747,
EPI_ISL_17696835, EPI_ISL_17696885, EPI_ISL_17696896,
EPI_ISL_17696903-17696904, EPI_ISL_17696909-17696911, EPI_ISL_17696913,
EPI_ISL_17697568, EPI_ISL_17697577, EPI_ISL_17697580,
EPI_ISL_17697585-17697586, EPI_ISL_17697589, EPI_ISL_17697595,
EPI_ISL_17697606, EPI_ISL_17697623-17697624, EPI_ISL_17697627,
EPI_ISL_17697630, EPI_ISL_17697635-17697636, EPI_ISL_17697644,
EPI_ISL_17697646, EPI_ISL_17697652, EPI_ISL_17697660,
EPI_ISL_17697671-17697672, EPI_ISL_17697683, EPI_ISL_17697688,
EPI_ISL_17697691, EPI_ISL_17697695, EPI_ISL_17697697-17697698,
EPI_ISL_17697700, EPI_ISL_17697702, EPI_ISL_17697709,
EPI_ISL_17697711, EPI_ISL_17697713, EPI_ISL_17697715,
EPI_ISL_17697719, EPI_ISL_17697721, EPI_ISL_17697723,
EPI_ISL_17697728, EPI_ISL_17697732, EPI_ISL_17697735,
EPI_ISL_17697739-17697741, EPI_ISL_17697755, EPI_ISL_17697759-17697760,
EPI_ISL_17697763-17697765, EPI_ISL_17697767, EPI_ISL_17697769,
EPI_ISL_17697777-17697778, EPI_ISL_17697782, EPI_ISL_17697785-17697786,
EPI_ISL_17697793-17697794, EPI_ISL_17697803, EPI_ISL_17697810-17697812,
EPI_ISL_17697814, EPI_ISL_17697818-17697819, EPI_ISL_17697822,
EPI_ISL_17697834, EPI_ISL_17697836-17697838, EPI_ISL_17697844,
EPI_ISL_17697846-17697853, EPI_ISL_17697857, EPI_ISL_17697860-17697863,
EPI_ISL_17697866-17697868, EPI_ISL_17697880, EPI_ISL_17697883-17697884,
EPI_ISL_17697887, EPI_ISL_17697891, EPI_ISL_17697900,
EPI_ISL_17697902, EPI_ISL_17697906-17697907, EPI_ISL_17697911,
EPI_ISL_17697914, EPI_ISL_17697936, EPI_ISL_17697939,
EPI_ISL_17697942, EPI_ISL_17697949, EPI_ISL_17697956,
EPI_ISL_17697958-17697960, EPI_ISL_17697966, EPI_ISL_17697970,
EPI_ISL_17697972-17697973, EPI_ISL_17697976-17697977, EPI_ISL_17697980,
EPI_ISL_17697987, EPI_ISL_17697997, EPI_ISL_17698002,
EPI_ISL_17698007, EPI_ISL_17698011-17698015, EPI_ISL_17698020,
EPI_ISL_17698022, EPI_ISL_17698024, EPI_ISL_17698026,
EPI_ISL_17698028-17698029, EPI_ISL_17698032-17698034, EPI_ISL_17698036,
EPI_ISL_17698038, EPI_ISL_17698045-17698046, EPI_ISL_17698049,
EPI_ISL_17698060, EPI_ISL_17698063, EPI_ISL_17698067,
EPI_ISL_17698069-17698070, EPI_ISL_17698073, EPI_ISL_17698077-17698080,
EPI_ISL_17698084, EPI_ISL_17698087, EPI_ISL_17698090,
EPI_ISL_17698092, EPI_ISL_17698094, EPI_ISL_17698104-17698105,
EPI_ISL_17698112, EPI_ISL_17698116-17698117, EPI_ISL_17698119,
EPI_ISL_17698123, EPI_ISL_17698134, EPI_ISL_17698137,
EPI_ISL_17698140, EPI_ISL_17698144-17698145, EPI_ISL_17698152,
EPI_ISL_17698155, EPI_ISL_17698158, EPI_ISL_17698164,
EPI_ISL_17698172, EPI_ISL_17698175-17698177, EPI_ISL_17698179,
EPI_ISL_17698189, EPI_ISL_17698191-17698193, EPI_ISL_17698199,
EPI_ISL_17698203, EPI_ISL_17698205, EPI_ISL_17698207,
EPI_ISL_17698221, EPI_ISL_17698226, EPI_ISL_17698233-17698234,
EPI_ISL_17698236, EPI_ISL_17698240-17698241, EPI_ISL_17698243,
EPI_ISL_17698248, EPI_ISL_17698250, EPI_ISL_17698253,
EPI_ISL_17698259-17698260, EPI_ISL_17698263-17698264, EPI_ISL_17698267,
EPI_ISL_17698270, EPI_ISL_17698275, EPI_ISL_17698277,
EPI_ISL_17698284, EPI_ISL_17698288, EPI_ISL_17698290,
EPI_ISL_17698292, EPI_ISL_17698298, EPI_ISL_17698300,
EPI_ISL_17698304-17698306, EPI_ISL_17698319, EPI_ISL_17698323-17698324,
EPI_ISL_17698326, EPI_ISL_17698328, EPI_ISL_17700345,
EPI_ISL_17700371, EPI_ISL_17700415, EPI_ISL_17700437,
EPI_ISL_17700460, EPI_ISL_17700760, EPI_ISL_17703623,
EPI_ISL_17703958, EPI_ISL_17703981, EPI_ISL_17703996,
EPI_ISL_17704016, EPI_ISL_17704053, EPI_ISL_17714255,
EPI_ISL_17714258, EPI_ISL_17714297, EPI_ISL_17714300,
EPI_ISL_17714311, EPI_ISL_17714383, EPI_ISL_17714410,
EPI_ISL_17714433, EPI_ISL_17716679, EPI_ISL_17717450,
EPI_ISL_17718379, EPI_ISL_17719296, EPI_ISL_17720648,
EPI_ISL_17723267, EPI_ISL_17724808-17724812, EPI_ISL_17724988,
EPI_ISL_17725086, EPI_ISL_17725094, EPI_ISL_17725106,
EPI_ISL_17725246, EPI_ISL_17725342, EPI_ISL_17725370,
EPI_ISL_17725494, EPI_ISL_17728910, EPI_ISL_17728939,
EPI_ISL_17729771, EPI_ISL_17729799, EPI_ISL_17729809,
EPI_ISL_17729811, EPI_ISL_17729817, EPI_ISL_17729852,
EPI_ISL_17729877, EPI_ISL_17729880, EPI_ISL_17729900,
EPI_ISL_17729907, EPI_ISL_17729909, EPI_ISL_17729912,
EPI_ISL_17729919, EPI_ISL_17729925-17729933, EPI_ISL_17729943,
EPI_ISL_17729963, EPI_ISL_17729965, EPI_ISL_17730020,
EPI_ISL_17730031, EPI_ISL_17730036, EPI_ISL_17735951,
EPI_ISL_17735994, EPI_ISL_17735997, EPI_ISL_17736072,
EPI_ISL_17737604, EPI_ISL_17739557, EPI_ISL_17739720,
EPI_ISL_17739759, EPI_ISL_17739788, EPI_ISL_17739804,
EPI_ISL_17739821, EPI_ISL_17739843, EPI_ISL_17740686,
EPI_ISL_17741537, EPI_ISL_17741591, EPI_ISL_17741805,
EPI_ISL_17741955-17741956, EPI_ISL_17744566, EPI_ISL_17744676,
EPI_ISL_17744682, EPI_ISL_17744736, EPI_ISL_17744754,
EPI_ISL_17744760, EPI_ISL_17761357, EPI_ISL_17761430,
EPI_ISL_17762878, EPI_ISL_17762885, EPI_ISL_17762937,
EPI_ISL_17762940, EPI_ISL_17762943, EPI_ISL_17765710,
EPI_ISL_17765894, EPI_ISL_17768069, EPI_ISL_17769773,
EPI_ISL_17770133, EPI_ISL_17770148, EPI_ISL_17770188,
EPI_ISL_17770222, EPI_ISL_17770332-17770333, EPI_ISL_17770345,
EPI_ISL_17770350, EPI_ISL_17770355, EPI_ISL_17770361,
EPI_ISL_17775217, EPI_ISL_17775367, EPI_ISL_17775431,
EPI_ISL_17775483, EPI_ISL_17775597, EPI_ISL_17778596,
EPI_ISL_17778599, EPI_ISL_17778611, EPI_ISL_17778629,
EPI_ISL_17778631, EPI_ISL_17778729, EPI_ISL_17778743,
EPI_ISL_17778763, EPI_ISL_17779003, EPI_ISL_17779047,
EPI_ISL_17779263, EPI_ISL_17779552, EPI_ISL_17779884,
EPI_ISL_17781820, EPI_ISL_17782554, EPI_ISL_17784249,
EPI_ISL_17784628, EPI_ISL_17785314, EPI_ISL_17785350,
EPI_ISL_17786004

Some sequences lost one of C11956T or T4579A due to sequencing error or reversion mutation (not included in counting):
EPI_ISL_17358180, EPI_ISL_17625391, EPI_ISL_17645489, EPI_ISL_17645493, EPI_ISL_17671948, EPI_ISL_17672006, EPI_ISL_17672022, EPI_ISL_17683464, EPI_ISL_17683472, EPI_ISL_17684336, EPI_ISL_17689826, EPI_ISL_17697798, EPI_ISL_17697799, EPI_ISL_17698166, EPI_ISL_17698171, EPI_ISL_17698231, EPI_ISL_17698301, EPI_ISL_17729924, EPI_ISL_17732669, EPI_ISL_17762898, EPI_ISL_17762908, EPI_ISL_17762915, EPI_ISL_17762944, EPI_ISL_17762957-17762958, EPI_ISL_17779230, EPI_ISL_17784411

Some sequences are suspected to be recombined with XBB.1.16(.1) or DY.4 (sequences without C11956T, T4579A or A17615G are not included in counting):
EPI_ISL_17625384, EPI_ISL_17625389, EPI_ISL_17698156, EPI_ISL_17698183
</details>

And a part of these sequences have further N:R189L(G28839T) mutation.

GISAID Query:	 C11956T, T4579A, A17615G, G28839T
Earliest Sequence: 04-12 Guangzhou, Guangdong, China EPI_ISL_17584655
Latest Sequence:  05-30 Lower Austria, Austria EPI_ISL_17782554

China 163+1: Guangdong 99(1 detected at Zhuhai Custom, probably imported from Macao), Hubei 29, Shanghai 13 (including 2 from Singapore, 1 from Thailand, 1 from unknown region), Fujian 4 (including 1 from Thailand), Sichuan 4, Yunnan 4, Heilongjiang 3, Shanxi 2, Fujian 1, Gansu 1, Qinghai 1, Xinjiang 1, Zhejiang1; Taiwan 1 (from Mainland);

US 8(1 from Germany, 1 from Singapore, 1 from S. Korea, 1 from Taiwan, 3 airport screening), Australia 2, France 2, NZ 2, Singapore 2(1 from Japan), South Korea 2(1 from China Mainland, 1 from Taiwan), Spain 2, Austria 1, Japan 1, Sweden 1.

<details><summary>Sequences:</summary>
EPI_ISL_17584641, EPI_ISL_17584649, EPI_ISL_17584653,
EPI_ISL_17584655, EPI_ISL_17584688, EPI_ISL_17625310,
EPI_ISL_17625383, EPI_ISL_17625386, EPI_ISL_17625462,
EPI_ISL_17625484, EPI_ISL_17625561, EPI_ISL_17645421,
EPI_ISL_17645761, EPI_ISL_17645945, EPI_ISL_17652315,
EPI_ISL_17671928, EPI_ISL_17671976, EPI_ISL_17673622,
EPI_ISL_17678311, EPI_ISL_17678338, EPI_ISL_17678369,
EPI_ISL_17684126, EPI_ISL_17684401, EPI_ISL_17684403-17684404,
EPI_ISL_17684406, EPI_ISL_17689324, EPI_ISL_17689360,
EPI_ISL_17689391, EPI_ISL_17696747, EPI_ISL_17696896,
EPI_ISL_17696903-17696904, EPI_ISL_17696909-17696911, EPI_ISL_17696913,
EPI_ISL_17697580, EPI_ISL_17697623, EPI_ISL_17697646,
EPI_ISL_17697660, EPI_ISL_17697671, EPI_ISL_17697697,
EPI_ISL_17697702, EPI_ISL_17697711, EPI_ISL_17697719,
EPI_ISL_17697721, EPI_ISL_17697728, EPI_ISL_17697732,
EPI_ISL_17697735, EPI_ISL_17697739-17697741, EPI_ISL_17697759,
EPI_ISL_17697782, EPI_ISL_17697794, EPI_ISL_17697810-17697812,
EPI_ISL_17697818-17697819, EPI_ISL_17697837, EPI_ISL_17697846-17697848,
EPI_ISL_17697850-17697853, EPI_ISL_17697857, EPI_ISL_17697860-17697863,
EPI_ISL_17697866-17697867, EPI_ISL_17697884, EPI_ISL_17697891,
EPI_ISL_17697902, EPI_ISL_17697936, EPI_ISL_17697939,
EPI_ISL_17697966, EPI_ISL_17697970, EPI_ISL_17697972-17697973,
EPI_ISL_17697976, EPI_ISL_17697997, EPI_ISL_17698002,
EPI_ISL_17698007, EPI_ISL_17698012, EPI_ISL_17698014,
EPI_ISL_17698022, EPI_ISL_17698024, EPI_ISL_17698026,
EPI_ISL_17698028, EPI_ISL_17698033, EPI_ISL_17698038,
EPI_ISL_17698060, EPI_ISL_17698063, EPI_ISL_17698067,
EPI_ISL_17698070, EPI_ISL_17698080, EPI_ISL_17698084,
EPI_ISL_17698094, EPI_ISL_17698116-17698117, EPI_ISL_17698119,
EPI_ISL_17698134, EPI_ISL_17698144-17698145, EPI_ISL_17698152,
EPI_ISL_17698158, EPI_ISL_17698176, EPI_ISL_17698189,
EPI_ISL_17698193, EPI_ISL_17698203, EPI_ISL_17698207,
EPI_ISL_17698221, EPI_ISL_17698236, EPI_ISL_17698241,
EPI_ISL_17698243, EPI_ISL_17698250, EPI_ISL_17698253,
EPI_ISL_17698277, EPI_ISL_17698290, EPI_ISL_17698298,
EPI_ISL_17698304-17698305, EPI_ISL_17698324, EPI_ISL_17698326,
EPI_ISL_17698328, EPI_ISL_17700345, EPI_ISL_17700371,
EPI_ISL_17700415, EPI_ISL_17700437, EPI_ISL_17700460,
EPI_ISL_17704016, EPI_ISL_17714258, EPI_ISL_17720648,
EPI_ISL_17724809, EPI_ISL_17724811, EPI_ISL_17725246,
EPI_ISL_17725342, EPI_ISL_17725494, EPI_ISL_17728910,
EPI_ISL_17728939, EPI_ISL_17729799, EPI_ISL_17729900,
EPI_ISL_17729907, EPI_ISL_17729919, EPI_ISL_17729925-17729933,
EPI_ISL_17729965, EPI_ISL_17730020, EPI_ISL_17735951,
EPI_ISL_17735994, EPI_ISL_17737604, EPI_ISL_17739557,
EPI_ISL_17739788, EPI_ISL_17739804, EPI_ISL_17739821,
EPI_ISL_17739843, EPI_ISL_17741537, EPI_ISL_17741956,
EPI_ISL_17744736, EPI_ISL_17744760, EPI_ISL_17765710,
EPI_ISL_17770333, EPI_ISL_17770355, EPI_ISL_17775483,
EPI_ISL_17778596, EPI_ISL_17778743, EPI_ISL_17778763,
EPI_ISL_17779552, EPI_ISL_17781820, EPI_ISL_17782554,
EPI_ISL_17784628, EPI_ISL_17785350, EPI_ISL_17786004

Lost one of C11956T or T4579A (not including in counting): EPI_ISL_17697798, EPI_ISL_17698301, EPI_ISL_17729924, EPI_ISL_17732669, EPI_ISL_17762957-17762958

Suspected to be recombined with XBB.1.16.1 (not including in counting): EPI_ISL_17698183 
</details>

**Comment by HynnSpylor** [comment]
I have tracked them since late April. It is the largest FL.2 (even XBB.1.9.1) branch in China despite without Spike mutation. 
Recently, the wave which XBB* lineages replace BA.5.2* lineages (BA.5.2.48*, BA.5.2.49*, BF.7.14* etc.) has swept across China, and XBB.1.9.1* become the dominant lineages (especially in South China). In this stage, the Spike mutation may be not the most important effects to obtain the preliminary advantage.

It deserves a designation and further tracking (if its sublineages emerge some key mutations).

**Comment by Over-There-Is** [comment]
Hubei+3 Yunnan+3 Zhejiang+2

**Comment by Over-There-Is** [comment]
Sichuan+1 Ohio+1

**Comment by Over-There-Is** [comment]
Sweden +1

**Comment by Over-There-Is** [comment]
Taiwan+1(Imported from China Mainland)

**Comment by Over-There-Is** [comment]
Singapore+5, 1 from Japan and 4 Local, S. Korea +1.

**Comment by Over-There-Is** [comment]
Shanghai+8, 5 collected by Customs and 3 local, travelling info not uploaded to GISAID, and not publicized yet on GenBase.

**Comment by Over-There-Is** [comment]
I don't know what happened, but USA/MD-CDC-QDX47869784/2023|EPI_ISL_17333208|2023-03-09 appears suddenly.

**Comment by Over-There-Is** [comment]
+30, Hubei 17(Jingzhou 12, Huangshi 2, Xiaogan 2 and Wuhan 1), Fujian 7(Amoy 3, Nanping 3 and Longyan 1), Qinghai 2(Xining and Yushu), Anhui 1(Bozhou), Shanxi 1(Shuozhou) and USA2(1 from Singapore and 1 airport screening).

**Comment by Over-There-Is** [comment]
Sichuan +4, 2 Meishan, 1 Guangyuan and 1 Zigong.

**Comment by Over-There-Is** [comment]
Illinois +1

**Comment by Over-There-Is** [comment]
Another sublineage with Orf1b:K1383R and S:H146K appeared. I found 2 new sequences with Orf1b:K1383R and S:H146K uploaded on 05-31, and assumed their are FL.2 sequences dropped T4579A out at first. But when I put them into usher, they turn into a 25 seq sublineage with a small saltation. sars-cov-2-variants/lineage-proposals#127

**Comment by Over-There-Is** [comment]
Heilongjiang +5, 3 with R189L.

**Comment by Over-There-Is** [comment]
And a friend of mine told me he has sequenced his first FL.2 sample. I don't know whether he upload that to the database, he is not a staff of CDC. Should I add it to the counting?
![微信图片_20230602111104](https://github.com/cov-lineages/pango-designation/assets/38100637/fe779b14-04bb-415d-b0f2-0fe91aadb93d)

**Comment by Memorablea** [comment]
436 seqs now

**Comment by Over-There-Is** [comment]
> 436 seqs now

I can only find 429 on gisaid.

**Comment by Over-There-Is** [comment]
2 NZ(Auckland), 2 Australia(NSW), 1 Japan, 3 South Korea(including 1 import from Taiwan Province)

**Comment by Over-There-Is** [comment]
Yunnan 5, California 1

**Comment by Over-There-Is** [comment]
Spain 1

**Comment by JosetteSchoenma** [comment]
I am getting completely confused by this tree, but this Spanish one has S:H146K. And the tree has a reversion thereafter, like I mentioned in this issue, https://github.com/sars-cov-2-variants/lineage-proposals/issues/97#issuecomment-1562339077 and @Memorablea answered to.
![image](https://github.com/cov-lineages/pango-designation/assets/94831035/1c857044-71da-4c13-a420-8b65faff35a3)

@Over-There-Is The tree I mentioned in issue #97 in lineage-proposals last week seems the same as in issue #127 you made a few days ago and mentioned here.

@FedeGueli @AngieHinrichs @Memorablea Would it be possible to fix the Usher tree?

**Comment by Over-There-Is** [comment]
Malaysia+1

**Comment by Over-There-Is** [comment]
Anhui +1, West Australia +1

**Comment by Over-There-Is** [comment]
California +1, Sweden +1

**Comment by Over-There-Is** [comment]
Shanghai +10

**Comment by Over-There-Is** [comment]
Xinjiang +5, 2 Hotan, 1 Changji, 1 Kashgar, and 1 Hami.

**Comment by Over-There-Is** [comment]
Yunnan+8, Gansu+1(Pingliang), South Korea+5

**Comment by Over-There-Is** [comment]
Austria +1

**Comment by Over-There-Is** [comment]
France+1

**Comment by Over-There-Is** [comment]
If using `G5720A, -A27507C, T4579A, A17615G` as query, not only 486 seq with C11956T but also 12 seq without C11956T can be found. Should I change the query?

**Comment by Over-There-Is** [comment]
@AngieHinrichs The flip-flop problem of FL.2.3 is fixed, but the sequences without C21998A(Q146K) are not assigned as FL.2.3
![2023-07-07](https://github.com/cov-lineages/pango-designation/assets/38100637/414a13df-6efa-47b9-8f5d-77125fdb5bdf)

**Comment by Over-There-Is** [comment]
Additionally, FR.1.1 sequences were assigned as FR.1 by usher recently, but I am not sure that whether the problem still exist or not.

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs The flip-flop problem of FL.2.3 is fixed, but the sequences without C21998A(Q146K) are not assigned as FL.2.3

Thanks @Over-There-Is -- that should be fixed in the 2023-07-07 build (available in ~5 hours).

> Additionally, FR.1.1 sequences were assigned as FR.1 by usher recently, but I am not sure that whether the problem still exist or not.

OK.  If you see any examples, please send a sequence name or ID.  Thanks.  

Taking a look at the full tree, I see the FR.1.1 branch has a child branch with a reversion of S:P82H (C21807A) that would explain their being called FR.1 in pangolin with usher mode -- it looks like it was pulled in by some sequences that share the reversion T337C.  337 is noisy in FR.1 (and in a branch of FR.1's parent BN.1.2.3).  I wonder if I should mask it out.

**Comment by Over-There-Is** [comment]
@AngieHinrichs 
BA.5.2.1/BF* is misplaced as a sibling branch of BA.5, and BF.7* is also not under under BF*
And BE.1.1\*/BQ* is not under BE.1*
![2023-07-09 (2)](https://github.com/cov-lineages/pango-designation/assets/38100637/beac0263-7856-43d7-a680-094cea9e4862)

**Comment by Over-There-Is** [comment]
@AngieHinrichs 
BA.5.2.1/BF* is misplaced as a sibling branch of BA.5, and BF.7* is also not under under BF*
And BE.1.1\*/BQ* is not under BA.5*
![2023-07-09 (2)](https://github.com/cov-lineages/pango-designation/assets/38100637/beac0263-7856-43d7-a680-094cea9e4862)
![2023-07-09 (2)](https://github.com/cov-lineages/pango-designation/assets/38100637/494528b6-956c-423f-8bfc-6b02af1d548b)

**Comment by AngieHinrichs** [comment]
Thank you @Over-There-Is -- yes, incomplete sequences have made some upstream-of-BA.5 branches that pulled in all of BA.5.2.1 and BE.1.1.  I will try to get that fixed in the 2023-07-10 build.

**Comment by Over-There-Is** [comment]
Sequences are not assigned as FL.2.3 again. @AngieHinrichs

**Comment by AngieHinrichs** [comment]
> Sequences are not assigned as FL.2.3 again. @AngieHinrichs

Can you send at least one example sequence name or ID that should be on the FL.2.3 branch but is not?  Thanks!

**Comment by Over-There-Is** [comment]
> > Sequences are not assigned as FL.2.3 again. @AngieHinrichs
> 
> Can you send at least one example sequence name or ID that should be on the FL.2.3 branch but is not? Thanks!

It did not work well 2 days ago, but yesterday it is fine.
