### ISSUE TITLE
Potential XBB.1.9.1/(1.9.2 or XBB.1.22.2) recombinant (103 samples) with a branch with S:Y200C and S:K478R (16 samples)

### ISSUE THREAD

**Issue by JosetteSchoenma** [cov-lineages/pango-designation#2019]
**Description:** XBB.1.9.1/XBB.1.9.2 recombinant, with a big (mostly South Korean) branch with ORF8:I74V and a smaller branch which first gained S:Y200C and an ORF3a frameshift and after that a small saltation with S:478R (Australia, USA, the Netherlands, China)
**Private mutations:** C6285T, G12907A, C28770T
**Breakpoint:** between nucleotide 16878 and 27507
**Earliest sequence:** 2023-03-10 from England (with S:Y200C and ORF3a frameshift)
2023-03-22 from South Korea (with ORF8:I74V)
2023-03-29 from NSW/Australia (with extra small saltation with S:478R)
**Most recent sequence:** 2023-05-15 from Fujian/China
**Countries circulating:** South Korea 31, Australia/USA 7, China 3, Japan/England 2, the Netherlands/Indonesia/Ireland/Taiwan 1
**GISAID query:** C6285T, C11956T, A27507C
**CovSpectrum query:** https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?nucMutations=C6285T%2CC11956T%2CA27507C&nextcladePangoLineage1=xbb.1.9.1*&
to which S:T478R or A28113G could be added to find the various sublineages.
**Usher tree:** 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8b73_effb30.json?branchLabel=nuc%20mutations&label=id:node_6674447
![image](https://github.com/cov-lineages/pango-designation/assets/94831035/e73b1e44-018b-4aa6-bdeb-c5329a9bd6c7)

Please note that because the XBB.1.9.2. part only differs one mutation from XBB.1.9.1 (A27507C), convergent evolution cannot be ruled out. But because of the extra private mutations, I think recombination is more likely.

Please see this issue from Fede for more background info and discussion: https://github.com/sars-cov-2-variants/lineage-proposals/issues/73.

**Comment by JosetteSchoenma** [comment]
EPI_ISL_17257300
EPI_ISL_17408992
EPI_ISL_17408993
EPI_ISL_17474493
EPI_ISL_17486324
EPI_ISL_17538740
EPI_ISL_17538786
EPI_ISL_17538789
EPI_ISL_17538825
EPI_ISL_17551409
EPI_ISL_17601614
EPI_ISL_17603875
EPI_ISL_17604506
EPI_ISL_17604507
EPI_ISL_17604650
EPI_ISL_17604753
EPI_ISL_17604791
EPI_ISL_17604836
EPI_ISL_17604967
EPI_ISL_17605107
EPI_ISL_17605182
EPI_ISL_17606011
EPI_ISL_17614765
EPI_ISL_17614857
EPI_ISL_17616209
EPI_ISL_17619092
EPI_ISL_17630732
EPI_ISL_17631979
EPI_ISL_17637630
EPI_ISL_17637843
EPI_ISL_17646850
EPI_ISL_17647343
EPI_ISL_17647413
EPI_ISL_17647543
EPI_ISL_17647788
EPI_ISL_17648589
EPI_ISL_17657166
EPI_ISL_17661231
EPI_ISL_17677572
EPI_ISL_17677617
EPI_ISL_17677934
EPI_ISL_17678411
EPI_ISL_17680081
EPI_ISL_17682885
EPI_ISL_17683629
EPI_ISL_17689132
EPI_ISL_17690576
EPI_ISL_17690748
EPI_ISL_17690983
EPI_ISL_17691002
EPI_ISL_17691273
EPI_ISL_17691484
EPI_ISL_17691653
EPI_ISL_17696738
EPI_ISL_17698828
EPI_ISL_17703980

**Comment by FedeGueli** [comment]
To track the smaller sublineage of this one with S:K478R i suggest this query :A22161G,C15390A, T26457C, G12907A.

cc @corneliusroemer @InfrPopGen @AngieHinrichs @thomaspeacock
My personal suggestion is a rapid review followed eventually by a designation of ( 'XC?' and .1 and .2 )

**Comment by aviczhl2** [comment]
A27507C is also in AY.25 and XBB.1.22.2.

**Comment by JosetteSchoenma** [comment]
Indeed, @aviczhl2 . I checked and it might have recombined with XBB.1.22.2 as well.

It is the same from G15451A (ORF:G662S) and forward. XBB.1.22.2 does have C15237T, which this recombinant and XBB.1.9.1/2 do not have. So, the breakpoint would be after that in case it recombined with XBB.1.22.2.

I do see 5 XBB.1.9.2 with C28770T, while I see no XBB.1.22.2 with it, which might make it sightly more likely that it recombined with XBB.1.9.2.

The Delta's with A27507C look very different, of course.

Thank you! I will adjust title.

**Comment by aviczhl2** [comment]
Sorry, what I actually want to express  is that A27507C, despite being a synonym mutation, is moderately convergent, so it is more likely convergent mutation. 

But, yes, recombination is also very common in SARS-2 too, with so many variants and infection rate being so high.

**Comment by JosetteSchoenma** [comment]
18 new samples. Mostly from South Korea, but also 3 from Shanghai and 2 from Australia.

74 in total now.

**Comment by JosetteSchoenma** [comment]
96 samples now. New samples mostly from South Korea but one from Austria from the A28113G branch.

**Comment by FedeGueli** [comment]
@corneliusroemer ping

**Comment by JosetteSchoenma** [comment]
103 samples now. New ones from South Korea, Indonesia and China (Anhui).

**Comment by ryhisner** [comment]
The S:Y200C, S:K478R, ORF1a:G519S, ORF1b:H641Q branch here has something super interesting going on that I don't think I've seen before. There are two deletions in ORF3a, both of which cause frameshifts. The first is ∆25474-25477 and the second ∆25520-25521, and they cancel each other out so that everything before and after them remains the same. But in between, there's a stretch of 14 frameshifted AA. 

I've tried to put together the resulting new AA residues in the diagram below. On the top, I've lined up the old and new AA sequences. The red are polar/charged residues. Residues 1 and 14 are the same in both, so I put both deletions at the end, even though the actual deletions aren't arranged that way. 
<img width="1459" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/387078c6-26e5-4cce-aa46-3dfd0fc67cd2">

**Comment by FedeGueli** [comment]
After this analysis by @ryhisner showing this lineage has a heavy mutated orf3a, i suggest to designate this one to track it in the next weeks beyond any growth advantage talk

 cc @corneliusroemer , @InfrPopGen

**Comment by FedeGueli** [comment]
135 samples as today . one new sample comes from Taiwan too.

**Comment by corneliusroemer** [comment]
I designated the 200C/478R sublineage as FL.18.1.1 - yes it could potentially be an FY.5 recombinant, but too little evidence to sacrifice the benefit of hierarchical lineage names.
