### ISSUE TITLE
EG.5.1 with orf1b:D54N in China, USA, Canada (501 seq)

### ISSUE THREAD

**Issue by BorisUitham** [cov-lineages/pango-designation#2020]
Earliest sequence: 2023-04-20
Recent sequence: 2023-05-22
Countries circulating: China (328), Canada (17), USA (14), Singapore (12), Australia (2), Netherlands (1), Italy (1), UK (1), france (1), Thailand (1), s. Korea (1), taiwan (1)
Query: G13627A, G21718T

Perhaps just a founder effect within China, but it is by far the most common eg.5.1 there and growing quickly.
Around 5% prevalence in china on 05-15 with about 91% growth advantage within china:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1b%3A54n&nextcladePangoLineage=eg.5.1*

Usher tree does not show any clear big branches yet but it does show diversity:
![eg51](https://github.com/cov-lineages/pango-designation/assets/119106095/022603df-aefd-4b91-9d61-0dd2ea46cc42)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_598c_772f0.json?c=gt-ORF1ab_4455&showBranchLabels=all

sequences:
EPI_ISL_17618946, EPI_ISL_17618977, EPI_ISL_17619084,
EPI_ISL_17619167, EPI_ISL_17625273, EPI_ISL_17625397,
EPI_ISL_17632964, EPI_ISL_17633000, EPI_ISL_17645405,
EPI_ISL_17645413-17645414, EPI_ISL_17645457, EPI_ISL_17645471,
EPI_ISL_17645519, EPI_ISL_17645682, EPI_ISL_17652355-17652356,
EPI_ISL_17662326, EPI_ISL_17664558, EPI_ISL_17664569,
EPI_ISL_17664608, EPI_ISL_17664627, EPI_ISL_17671906,
EPI_ISL_17671962, EPI_ISL_17672047, EPI_ISL_17672063,
EPI_ISL_17678349, EPI_ISL_17678416, EPI_ISL_17678418,
EPI_ISL_17678421, EPI_ISL_17678430, EPI_ISL_17678445,
EPI_ISL_17678448-17678449, EPI_ISL_17684032, EPI_ISL_17684049-17684050,
EPI_ISL_17684131, EPI_ISL_17684156, EPI_ISL_17684195,
EPI_ISL_17684246, EPI_ISL_17684267, EPI_ISL_17684396,
EPI_ISL_17684409, EPI_ISL_17684419, EPI_ISL_17684429,
EPI_ISL_17694920, EPI_ISL_17696755, EPI_ISL_17696845-17696846,
EPI_ISL_17696901, EPI_ISL_17697598, EPI_ISL_17697608,
EPI_ISL_17697622, EPI_ISL_17697642, EPI_ISL_17697654,
EPI_ISL_17697742, EPI_ISL_17697833, EPI_ISL_17697953,
EPI_ISL_17697975, EPI_ISL_17698041, EPI_ISL_17698047,
EPI_ISL_17698093, EPI_ISL_17698095, EPI_ISL_17698125,
EPI_ISL_17698159, EPI_ISL_17698314, EPI_ISL_17698321,
EPI_ISL_17700340, EPI_ISL_17700360, EPI_ISL_17703750-17703751,
EPI_ISL_17703753, EPI_ISL_17703973, EPI_ISL_17704051,
EPI_ISL_17714273, EPI_ISL_17714281, EPI_ISL_17714288-17714289,
EPI_ISL_17714298, EPI_ISL_17714301, EPI_ISL_17714304-17714305,
EPI_ISL_17714307-17714308, EPI_ISL_17714314, EPI_ISL_17714342,
EPI_ISL_17714364, EPI_ISL_17714373, EPI_ISL_17714376,
EPI_ISL_17714379, EPI_ISL_17714399, EPI_ISL_17714418,
EPI_ISL_17714435, EPI_ISL_17714438, EPI_ISL_17714441-17714442,

**Comment by FedeGueli** [comment]
@corneliusroemer this seems fast spreading in China, if it shows the same dynamics outside China i think it should get designated then.

**Comment by BorisUitham** [comment]
114. New in: australia (1)

**Comment by BorisUitham** [comment]
Also first sequence in Netherlands uploaded today

**Comment by FedeGueli** [comment]
This another one without spike mutations deserving to get designated for its transmissibility.
This perhaps the fastest lineages arising in the asian emisphere.
![Schermata 2023-05-31 alle 23 07 04](https://github.com/cov-lineages/pango-designation/assets/87669813/3a6b8311-c170-43f6-bed7-883bbd396087)
https://cov-spectrum.org/collections/42?country=China

Nothing compares.

**Comment by BorisUitham** [comment]
One of the recent uploads from fujian also has spike_p521s

**Comment by JosetteSchoenma** [comment]
7 recent Chinese samples with an extra S:H146K mutation.
![image](https://github.com/cov-lineages/pango-designation/assets/94831035/d0295f2e-f03f-4c0f-8a37-3037782decdc)

**Comment by Over-There-Is** [comment]
> 194 cases in total now on GISAID for G13627A, G21718T
> 
> 7 recent Chinese samples with an extra S:H146K mutation. ![image](https://user-images.githubusercontent.com/94831035/242829166-d0295f2e-f03f-4c0f-8a37-3037782decdc.png)
> 
> Adding S:H146K to the query finds 8, which are mostly put somewhere else or twice (so also somewhere else) on the Usher tree. On the other hand, some that are on the Usher tree you see up, might not yet be on GISAID. Seeing that the regions are alike, it might be monophyletic, with Usher having trouble placing them?
> 
> ![image](https://user-images.githubusercontent.com/94831035/242840239-51a4859c-b6ce-4297-90e7-4784e0d9c9aa.png) ![image](https://user-images.githubusercontent.com/94831035/242840366-e1ed3250-b9ba-40fd-8ae7-9711f4f548a1.png)

Usher seems does not work well to the sequences on S:Q146K-related branches. Such as #2016 is analyzed as FL.2> S:Q146K> Orf1ab:K5784R> S:K146Qrev.

**Comment by JosetteSchoenma** [comment]
Thanks, @Over-There-Is . I am seeing the same with S:P681R

.https://github.com/sars-cov-2-variants/lineage-proposals/issues/131

**Comment by BorisUitham** [comment]
198, and a sequence from italy

**Comment by FedeGueli** [comment]
Ping @corneliusroemer very fast

**Comment by JosetteSchoenma** [comment]
From 194 to 277 in 10 days.
With the extra S: H146K only from 8 to 9.

**Comment by BorisUitham** [comment]
Yes fast growth, even though it mostly seems to be because of intensive sequencing in China (so global growth estimates might be less accurate to truth than growth estimates from china only)

**Comment by FedeGueli** [comment]
![Schermata 2023-06-12 alle 19 16 51](https://github.com/cov-lineages/pango-designation/assets/87669813/50d894d3-81d2-4a04-a0a2-e56d21a6e4d9)Looking at China only there is nothing as fast as this one:
to check this let input G13627A, G21718T as baseline in COllection42:

https://cov-spectrum.org/collections/42?country=China

and this is true also looking at median growth advantage worlwide not too be too chinese dependent in the analysis:
![Schermata 2023-06-12 alle 19 19 03](https://github.com/cov-lineages/pango-designation/assets/87669813/2e618d69-816d-4804-a671-7c127b0e0940)


CC @corneliusroemer please designate this one to track it.

**Comment by BorisUitham** [comment]
Canada (ontario), seemingly a place which also had early local spread, seems to have its own branch with T9699C (orf1a:i3145t, nsp4:383t) representing 10 of 17 seqs

**Comment by FedeGueli** [comment]
@corneliusroemer i think it is this one driving EG.5.1 to the first place of Benj Murrell chart:
https://github.com/MurrellGroup/lineages

**Comment by aviczhl2** [comment]
It has 380 seqs now, and 52 are outside China.

**Comment by BorisUitham** [comment]
Thanks @aviczhl2.
Looking at the new current tree, there are no clear advantageous branches yet, but I think the s:g257v branch might potentially have some advantage due to it also very recently appearing across xbb.1.5, xbb.1.9.1 and xbb.1.16. It consists of 8 sequences in xinjiang at the moment
![Screenshot_20230614_163642_Chrome](https://github.com/cov-lineages/pango-designation/assets/119106095/92861b69-f0fb-452b-a4f6-a80bb6dfdeb4)

Case count:
Asia 343
- China 328
- Singapore 12 (local and airport)
- S. Korea 1
- Taiwan 1
- Thailand 1

N. america 31
- Canada 17 (local cases, most ontario)
- USA 14 (seemingly mostly airport surveillance)

Europe 4
- netherlands 1
- UK 1
- Italy 1
- France 1

Oceania 2
-australia 2

**Comment by Over-There-Is** [comment]
1 Taiwanese seq from Vietnam, 1 West Australia, 4 Ontario

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage EG.5.1.1 with 68 newly designated sequences, and 0 updated. Defining mutation G13627A (ORF1b:D54N) (following C6541T, C25572T).
