### ISSUE TITLE
XBB.1.11.1 (S:S486P) Sublineage with S:K478R (87 seq, May 20)—first proposed by @FedeGueli

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2021]
### **Transferred from pre-Proposal page** Issue 66 https://github.com/sars-cov-2-variants/lineage-proposals/issues/66

Note: A sub-branch of this lineage was previously proposed by @FedeGueli, but after a subsequent rearrangement of the Usher tree, I made the following proposal, not realizing it contained within it the branch proposed earlier. 

**Description**
**Sub-lineage of:** XBB.1.11.1
**Earliest sequence:** 2023-2-2, Indonesia — EPI_ISL_17012209
**Most recent sequence:** 2023-5-2, Indonesia — EPI_ISL_17655098
**Countries circulating:** Indonesia (29), Malaysia (7), England (3) South Korea (1), Australia (1), Spain (1), Japan (1)
**Number of Sequences:** 43
**GISAID Nucleotide Query:** C13968A, G16377A, C22995G, T23018C
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.11.1* & S:K478R
**Substitutions on top of XBB.1.11.1:**
**Spike:** K478R
**Nucleotide:** A22995G

**USHER Tree** (The tree below excludes several sequences with multiple artifactual reversions, so all the longer branches below consist of real mutations.)
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.11.1_(S486P)_K478R.json?c=gt-S_478&label=id:node_3679455
<img width="1493" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/89b372d0-3c35-461d-a5af-b8701ccf3de1">

**Evidence**
This lineages seems to be most in Indonesia, a country of about 275 million people from which we don't get very many sequences. It is also prominent in Malaysia. The base lineage can't be growing particularly fast or it would be more widespread internationally by now, but there's a great deal of diversity here, including a sizable branch with S:F186S and four additional AA mutations. This branch includes the most recently collected sequence (May 2) and first appeared on March 10 in Indonesia.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17012209, EPI_ISL_17164850, EPI_ISL_17324410, EPI_ISL_17389516, EPI_ISL_17389654, EPI_ISL_17389725, EPI_ISL_17416998, EPI_ISL_17469966, EPI_ISL_17470009, EPI_ISL_17470016-17470017, EPI_ISL_17470030, EPI_ISL_17518081, EPI_ISL_17542013, EPI_ISL_17546410, EPI_ISL_17546448, EPI_ISL_17551332, EPI_ISL_17551361, EPI_ISL_17551494, EPI_ISL_17551532, EPI_ISL_17554737, EPI_ISL_17558668, EPI_ISL_17612344-17612345, EPI_ISL_17612347, EPI_ISL_17612354, EPI_ISL_17612366, EPI_ISL_17612373-17612374, EPI_ISL_17622306, EPI_ISL_17622322, EPI_ISL_17622348, EPI_ISL_17622363, EPI_ISL_17630635, EPI_ISL_17630702, EPI_ISL_17652467, EPI_ISL_17654916, EPI_ISL_17654975, EPI_ISL_17654978, EPI_ISL_17655098, EPI_ISL_17655949, EPI_ISL_17656892, EPI_ISL_17664323
</details>

**Comment by FedeGueli** [comment]
In the same tree your one is the one in the middle coloured for F/R

![Schermata 2023-05-26 alle 16 23 31](https://github.com/cov-lineages/pango-designation/assets/87669813/6345e207-e88a-4839-bae8-d96ce9ca3256)

**Comment by ryhisner** [comment]
When I run the tree, I still get them both in the same branch, @FedeGueli. Maybe it depends on which sequences you upload together? That's definitely been the case for me before. 

I used the nucleotide query above (C13968A, G16377A, C22995G, T23018C) and uploaded all 89 results. Here's what I get:
<img width="1495" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/a9077392-7309-45ec-b968-093fa2feb596">

**Comment by FedeGueli** [comment]
very weird. try to repeat the op excludimg the saltation maybe now i m off pc i cant.

**Comment by FedeGueli** [comment]
@ryhisner also.the S:E780A was differently placed in mine .

**Comment by FedeGueli** [comment]
Designated FP.3 from https://github.com/cov-lineages/pango-designation/commit/b5e3461c0f9cd653b19feca250adec12433a4968

cc @InfrPopGen

**Comment by AngieHinrichs** [comment]
I haven't verified this, but I think it's possible that matOptimize might sometimes move the branch back and forth from day to day.  I can look at specific build dates if you want.
