### ISSUE TITLE
XBB.2.3.11 (S:K478R) Sublineage with S:E213D (40 seq, 4 continents, May 27)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2023]
### **Description**
**Sub-lineage of:** XBB.2.3.11
**Earliest sequence:** 2023-3-27, Australia, Western Australia — EPI_ISL_17463231
**Most recent sequence:** 2023-5-18, Australia, New South Wales — EPI_ISL_17718892
**Countries circulating:** Australia (35), India (2), USA (2), Germany (1),  
**Number of Sequences:** 40
**GISAID AA Query:** Spike_V213D, -V213del, NS7a_A13V, -T478Q
**GISAID Nucleotide Query:** C4582T, G22201T, C25075T
**CovSpectrum Query:** Nextcladepangolineage:XBB.2.3* & G22201T & [1-of: C4582T, C25075T]
**Substitutions on top of XBB.2.3.11:**
**Spike:** E213D
**Nucleotide:** C4582T, G22201T, C25075T
 
**Phylogenetic Order of Mutations:** C25075T (syn) **→** C4582T (syn) **→**  G22201T (S:E213D)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.2.3.11_V213D.json   
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.2.3.11_V213D.json?c=gt-S_213&label=id:node_3675074

<img width="1438" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/3274f10c-ebc0-429a-a997-0b8f4dd7969f">

**Evidence**
I don't have anything insightful to say except that these sequences are all quite recent and that over half of them have a lot of missing coverage, especially in spike. There are enough good sequences from different labs to ensure this is real, but I suspect some members of this lineage have been sequenced but get missed due to poor coverage. EPI_ISL_17717703, from Chandigarh, India, is one example of such a sequence. There may be others.

<img width="718" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/cfbbc4b2-d317-4afe-9580-5e04c253aeb5">

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17463231, EPI_ISL_17517448, EPI_ISL_17517468-17517469, EPI_ISL_17517509, EPI_ISL_17561098, EPI_ISL_17561127, EPI_ISL_17561149, EPI_ISL_17561181-17561182, EPI_ISL_17561189, EPI_ISL_17561437, EPI_ISL_17612738, EPI_ISL_17612764, EPI_ISL_17612775, EPI_ISL_17612846, EPI_ISL_17620927, EPI_ISL_17620954, EPI_ISL_17642142, EPI_ISL_17649085, EPI_ISL_17657153, EPI_ISL_17663893, EPI_ISL_17683067, EPI_ISL_17683089, EPI_ISL_17683275, EPI_ISL_17683290, EPI_ISL_17683356, EPI_ISL_17683445, EPI_ISL_17683509, EPI_ISL_17683606-17683607, EPI_ISL_17683642, EPI_ISL_17683711, EPI_ISL_17703763, EPI_ISL_17711601, EPI_ISL_17718747, EPI_ISL_17718761, EPI_ISL_17718892, EPI_ISL_17718903, EPI_ISL_17719059
</details>

**Comment by FedeGueli** [comment]
With a more generic query C4582T,C4234T, G6536A i find 79 sequences (and 77 are dropped in the tree proposed here)

And this is how the tree with them looks like:
![Schermata 2023-05-27 alle 14 08 07](https://github.com/cov-lineages/pango-designation/assets/87669813/b776ee51-4b4e-4554-8a2d-f969f8fecf36)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_886a_1f24b0.json?f_userOrOld=uploaded%20sample&label=id:node_6987789

**Comment by HynnSpylor** [comment]
another choice for 213 site(V213G in BA.2.75* and V213E for almost XBB*)

**Comment by HynnSpylor** [comment]
4 more seqs from Laos

**Comment by ryhisner** [comment]
The three from Laos also have S:T95N. 

Also worth noting that one of the longer-branch Australian sequences (the lower one in the picture below) appears to be an XBB.2.3/XBB.1.9.1 recombinant. 
<img width="1510" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/dd7bb44f-6416-43cd-be53-3bd8b8d79345">
