### ISSUE TITLE
BA.2.31.1 still circulating in Uganda with convergent S:R346T and N:L161F (41 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2034]
Surprisingly BA.2.31.1 still circulates in Uganda after more than one year.

I suggest a designation to keep track of it.

Defining mutations:

BA.2.31.1 >>> A18366G, G21255A, N:L161F (C28754T) > S:R346T (G22599C) 

Gisaid query : A18366G,T19452C

Tree:
![Schermata 2023-06-03 alle 23 59 19](https://github.com/cov-lineages/pango-designation/assets/87669813/91b89049-13ba-4073-8fb7-c79ac2c6aa4f)
![Schermata 2023-06-03 alle 23 59 52](https://github.com/cov-lineages/pango-designation/assets/87669813/fa39e83f-c968-44f5-a6b7-dc1ddf9bce80)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice11_genome_2514f_bb1da0.json?c=userOrOld&label=id:node_8111023

Samples: 41
EPI_ISL_13231354, EPI_ISL_13460277, EPI_ISL_13521099,
EPI_ISL_13521193, EPI_ISL_13542131, EPI_ISL_13611565,
EPI_ISL_13611575, EPI_ISL_13611578, EPI_ISL_13611581,
EPI_ISL_13772946, EPI_ISL_13772952, EPI_ISL_13773036,
EPI_ISL_13869368, EPI_ISL_13869373, EPI_ISL_13883348,
EPI_ISL_13952132, EPI_ISL_13952140, EPI_ISL_13952159-13952160,
EPI_ISL_13955176, EPI_ISL_13955179, EPI_ISL_13955183,
EPI_ISL_13955185-13955186, EPI_ISL_13990438, EPI_ISL_14090537,
EPI_ISL_14187418, EPI_ISL_14285687, EPI_ISL_14623330,
EPI_ISL_15477275, EPI_ISL_15488472, EPI_ISL_15909094-15909095,
EPI_ISL_16613357-16613358, EPI_ISL_16844989, EPI_ISL_16982267,
EPI_ISL_17261603, EPI_ISL_17292859, EPI_ISL_17686868,
EPI_ISL_17686870

Countries: 9
![Schermata 2023-06-04 alle 00 03 26](https://github.com/cov-lineages/pango-designation/assets/87669813/ce5d1cc8-d5fe-4c86-b87f-66b7bd295db8)

**Comment by silcn** [comment]
Are we sure that's not a date error? As in #1639, we'd expect many more mutations over this period of time.

**Comment by FedeGueli** [comment]
> Are we sure that's not a date error? As in #1639, we'd expect many more mutations over this period of time.

It could be but to me it seems real

**Comment by ryhisner** [comment]
Coverage is so bad that it's hard to tell much of anything. It would be nice to have at least one fairly good sequence. 
<img width="1472" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/21a8f13a-9d6f-4692-80cf-e2c561618fa3">
