### ISSUE TITLE
FU.1 with A460G to describe tree (2399 seq.)

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2037]
transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/50
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/9ebd28f0-14e5-4547-bf84-4bae3b1fb230)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42d59_c69110.json?c=gt-nuc_460&label=id:node_6665765
Gisaid query A460G,T12730A, T3802C.

**Comment by Over-There-Is** [comment]
China 642+3:
Shanghai 526, 88 imported: 6 HK, 7 Macao, 2 TW; 30 Thailand, 7 S. Korea, 4 UAE, 4 Singapore, 4 Japan, 4 Vietnam, 4 Malaysia, 3 Egypt, 2 US, 2 UK, 1 Deutschland, 1 Algeria, 1 Sweden, 1 Switzerland, 1 India, 1 NZ, 3 travelling info unavailable.
Hubei 24: 5 Jingzhou, 4 Huanggang, 3 Huangshi, 3 Ezhou, 2 Jingzhou, 2 Xiangyang, 1 Wuhan, 1 Xiaogan, 1 Enshi, 1 Shiyan and 1 Xianning.
Fujian 24: 12 Fuzhou, 3 Longyan, 3 Sanming, 2 Amoy, 2 Nanping, 1 Zhangzhou and 1 Quanzhou.
Anhui 21: 8 Hefei, 6 Bozhou, 5 Lu'an and 2 Fuyang.
Guangdong 12: 7 Shenzhen, 2 Guangzhou, 1 Meizhou, 1 Zhanjiang and 1 Dongguan.
Yunnan 9, city not assigned.
Sichuan 8: 2 Yibin, 2 Luzhou, 1 Neijiang, 1 Ya'an, 1 Guangyuan, 1 Liangshan.
Xinjiang 5: 3 Aksu, 1 Urumqi, 1 Kizilsu.
Jiangsu 4: 2 Zhenjiang, 1 Wuxi, 1 Changzhou.
Taiwan 3, all from Mainland.
Henan 2: 1 Hebi and 1 Xinyang.
Qinghai 2, all in Xining.
Beijing 1, Zhejiang 1(Hangzhou?), Heilongjiang 1, Shanxi 1(Jincheng), Liaoning 1(Chaoyang).

US 14: 1 from Deutschland, 1 from China Mainland, 2 from Taiwan, 1 from South Korea, 1 from Greece, 6 Airport Screening, 2 local cases in Washington State
South Korea 9: 4 from China, 2 from Switzerland, 1 from Turkey.
Japan 6, 5 Imported, at least 3 from China.
Australia 3(NSW 2, SA 1)
NZ 2(Auckland & Waitemata)
Singapore 2, all Local.
Austria 1(Vienna)
France 1(Occitanie)
Canada 1(Ontario)

**Comment by FedeGueli** [comment]
@corneliusroemer this is really a big branch i think it deserves a designation on its own beyond the fact it has no AA mut.

**Comment by ryhisner** [comment]
Do we really need more lineage designations that are indistinguishable from their parent lineage? The designations are already quickly becoming incomprehensible. Unless there is a known function for a synonymous nucleotide mutation (such as alteration of gene expression through changing the TRS), it seems better to me to not designate them.

**Comment by FedeGueli** [comment]
[One](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice8_genome_16288_a5150.json) sequence with S:L455F |EPI_ISL_17811100
[one](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice8_genome_16288_a5150.json?c=gt-S_456&label=id:node_6615929) with s:F456L: EPI_ISL_17836700

**Comment by aviczhl2** [comment]
2416 now
