### ISSUE TITLE
Sudden Emergence of FR.1+9-nuc,3-aa including  orf9b:G31R in China(56 seqs,5 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2039]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/126

FR.1+C25572T+C337T+C882T(orf1a:A206V)+C14097T,C15017T(orf1b:A517V)+T28019C,C14599T,C25603T+G28374A(orf9b:G31R, N:G34E)

GISAID query: del28367_28375,T28019C,C14599T,C25603T

Note that the default for omicron is del28364_28372, and GISAID categorizes del28364_28372+G28374A to del28367_28375.

No. of seqs: 48( China 46(9 provinces , 2 from Singapore, 1 from Canada), Singapore 1(from Hong Kong) South Korea 1(from Hong Kong))

First seq: EPI_ISL_17645692, Sichuan, 4-1
Latest: EPI_ISL_17735959, Sichuan, 5-22

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice9_genome_27786_848c90.json?label=id:node_7227896)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/a1c60388-1f14-4157-a5ee-15953568355c)

**Comment by aviczhl2** [comment]
56 and detected in Luxemberg.

**Comment by aviczhl2** [comment]
This is FR.1.3 and shall add a label on it. @corneliusroemer

**Comment by aviczhl2** [comment]
The label shall be FR.1.3

**Comment by Over-There-Is** [comment]
@corneliusroemer
