### ISSUE TITLE
FL.5 (XBB.1.9.1.5) with ORF7b:L25I and S:M177T (84 seqs, 12 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2041]
Transferred from sars-cov-2-variants/lineage-proposals#67

**Defining mutations:** _On top of FL.5 C29358T(N:T362I) >_ C27828A(ORF7b:L25I) > C2710T > C7039T > T22092C(S:M177T)
**Query:** T22092C, C27828A
**Earliest seq:** 2023-02-27 (EPI_ISL_17094227, Singapore)
**Latest seq:** 2023-05-25 (EPI_ISL_1776205, South Korea)
**Sampled in Countries:** South Korea (23), Japan (12), USA (10, California/4, Washington/2, Pennsylvania/1, New Jersey/1, Ohio/1, Florida/1), Singapore (3), China (3, Heilongjiang/2, Shanghai/1), Australia (2), Malaysia (1), Canada (1, Ontario), UK (1, England), Indonesia (1)
<details><summary>GISAID Genomes: </summary>
EPI_ISL_17094227, EPI_ISL_17388455, EPI_ISL_17416132, EPI_ISL_17495626, EPI_ISL_17539253, EPI_ISL_17540224, EPI_ISL_17552065, EPI_ISL_17552995, EPI_ISL_17554549, EPI_ISL_17561173, EPI_ISL_17563044, EPI_ISL_17563273, EPI_ISL_17585974, EPI_ISL_17590265, EPI_ISL_17604252, EPI_ISL_17605181, EPI_ISL_17619111, EPI_ISL_17621663, EPI_ISL_17629652, EPI_ISL_17629997, EPI_ISL_17631021, EPI_ISL_17631059, EPI_ISL_17631066, EPI_ISL_17637729, EPI_ISL_17646768, EPI_ISL_17648028, EPI_ISL_17651043, EPI_ISL_17653108, EPI_ISL_17662201, EPI_ISL_17672489, EPI_ISL_17678653, EPI_ISL_17688946, EPI_ISL_17690487, EPI_ISL_17691120, EPI_ISL_17691756, EPI_ISL_17694767, EPI_ISL_17717444, EPI_ISL_17721783, EPI_ISL_17723173, EPI_ISL_17723960, EPI_ISL_17728892, EPI_ISL_17729048, EPI_ISL_17730355, EPI_ISL_17730367, EPI_ISL_17730369, EPI_ISL_17730379, EPI_ISL_17730643, EPI_ISL_17730700, EPI_ISL_17730816, EPI_ISL_17739682, EPI_ISL_17739695, EPI_ISL_17761980, EPI_ISL_17762050, EPI_ISL_17762051, EPI_ISL_17762052, EPI_ISL_17762055, EPI_ISL_17774249
</details>

<details><summary>GenBank Genomes: </summary>
USA/CA-CDPH-500110242/2023|OQ970911.1|2023-04-19,
USA/FL-CDC-LC1036184/2023|OQ832929.1|2023-04-03,
USA/NY-PRL-230420_81C04/2023|OQ930358.1|2023-04-18,
USA/OH-UHTL-3164/2023|OR061356.1|2023-05-13
</details>

**UShER:**

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21de5_17b3f0.json?f_userOrOld=uploaded%20sample

Detailed view:
![Detail](https://github.com/cov-lineages/pango-designation/assets/125747944/e75ad5c5-4bdf-4ff9-b969-d4b553ef4e0e)

Overview of proposed lineage on FL.5 polytomy:
![Overview](https://github.com/cov-lineages/pango-designation/assets/125747944/97669f67-833a-4661-a60e-1ecc33b4c302)

**Trivia:** 
- S:M177T is the definition of BN.1.7 and XBB.3.2, also popped up in @FedeGueli 's XBB.1.5 spike mutation tracker cov-lineages/pango-designation#1510 , however it doens't seems to make much influence previously, let's see how it does this time on XBB.1.9*. 
- Parent branch FL.5 C29358T(N:T362I) > C27828A(ORF7b:L25I) now has at least 345 seqs using gisaid query: G5720A, C11956T, C29358T, C27828A
- A sub-branch with G24842T(S:V1094F) first, then T22092C(S:M177T), involving 3 outliers EPI_ISL_17416132, EPI_ISL_17499428, EPI_ISL_17642618, there could be dropouts that causing the split of branches, and they are not counted.
- EPI_ISL_17669171 now falls under another sub-branch involving C22995G(S:T478R).
- genbank accession OQ970911.1, OQ832929.1, OQ930358.1, OR061356.1 not on GISAID yet but can be found on UShER tree.

**Comment by Over-There-Is** [comment]
\*It is GenBank but not GenBase. GenBank is an American database and GenBase is Chinese.

**Comment by FedeGueli** [comment]
It is expanding in eastern asia but still i dont see big prevalence of it anywhere, maybe Philippines being already there in April ?
