### ISSUE TITLE
Possible XBB.1.5* × BQ.1* recombinant with ORF1a:T4031I, S:R214H, S:T478I, ORF8:V62L (13 seqs, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2042]
Transferred from sars-cov-2-variants/lineage-proposals#148

**Query:** G22203A, C22995T, C28657T 
**Earliest seq:** 2023-01-26 (EPI_ISL_17683933, Indonesia)
**Latest seq:** 2023-05-25 (EPI_ISL_17742133, Australia)
**Sampled in Countries:** Indonesia (6), South Korea (5), Australia (1, NSW), USA (1, Virginia)

**Genomes:** EPI_ISL_17647594, EPI_ISL_17647595, EPI_ISL_17647596, EPI_ISL_17723340, EPI_ISL_17723346, EPI_ISL_17742133, EPI_ISL_17716667, EPI_ISL_17736554, EPI_ISL_17736565, EPI_ISL_17683903, EPI_ISL_17683933, EPI_ISL_17736545, EPI_ISL_17736560

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_3dd43_ed0b40.json?f_userOrOld=uploaded%20sample
![Detailed](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/0192eec5-9cac-4634-a1b6-2d78b7f7d1d8)

**Evidence:**
![Mut](https://github.com/cov-lineages/pango-designation/assets/125747944/0e852157-ef0a-4a80-80aa-5b7a29a82378)

- Somehow nextclade recognize it as XBW, but it is not, for it doesn't have T22612C, C24130T, G29260A
- it does not have many of XBB.1.5's T17124C 
- it has XBB.1's G22317T (S:G252V) instead of XBB.2.3's A22320G (S:D253G), ruled out possiblity of XBB.2.3* + S:T478I
- it has S:F486P (T23018C, T23019C), one of the donor could be either XBB.1.5 pre T17124C or other XBB.1 + S:F486P
- it does not have XBB's C25416T, A26275G (E:T11A), means breakpoint before C25416T, probably the reason being recognized as XBW
- ~~it does not have BA.5's G26529A (M:D3N), either a second breakpoint or simply reversion~~ _Edit:_ the only sequence that witoutht G26529A (M:D3N) is the earlist sequence EPI_ISL_17683933, others should all have it. Thanks to @FedeGueli for correction.
- it does not have XBB's M:D61L (G27382C, A27383T, T27384C)
- it has BQ.1's ORF9b:P10F (C28311T, C28312T), interestingly XBB.1.5.57 (donor of XBL, without T17124C) also has it
- it has BQ.1's G28681T (N:E136D)

**Conclusions & Putative Donors:** (cc. @FedeGueli see comments for details)
- 5' end donor could be a pre T17124C XBB.1.5*, or any other XBB.1* that has S:F486P
- breakpoint between 23019 and 25416.
- 3' end donor could be BQ.1.1.25

**Private mutations:**
C12357T (ORF1a:T4031I), T18006C (ORF1b:L590L), A19173G (ORF1b:T1902T), G22203A (S:R214H), C22995T(S:T478I), G28077T (ORF8:V62L), C28657T (N:D128D)

**Comment by FedeGueli** [comment]
@NkRMnZr there is an error, this lineage DO HAVE M:D3N :
![Schermata 2023-06-06 alle 16 48 44](https://github.com/cov-lineages/pango-designation/assets/87669813/f081af9a-0434-49a4-81b3-6b0a3ce041dd)

**Comment by focosi-cyber** [comment]
Could the XBB.*donor be XBB.1.5.40? At top of my head that's the only XBB.* with T478I ....That's quite rare as a 478 mutation. But I understand XBB.1.5.40 has never been sequenced in Indonesia, Australia or South Korea : only USA.

**Comment by JosetteSchoenma** [comment]
XCD
