### ISSUE TITLE
New S:F486P carrying sublineage of XBB.1 + orf8:G8* defined by S:T747I, Orf1a:A540V and Orf3a:S195F 63 seqs (Malaysia-XINJIANG) 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2043]
Originally proposed here: https://github.com/sars-cov-2-variants/lineage-proposals/issues/113#issuecomment-1582721850

I decided to propose it after @aviczhl2 spotted  a batch of sequences belonging to this lineage uploaded by Xinjiang.

It has gained S:f486P after a previous spike mutation S:T747I.
Looking at the tree it seems divided in two big branches one circulating in Xinjiang defined by T13177A
and the other likely emerged in Malaysia defined by C1663T, A18146C.
Expanding back the tree the roots of this lineage could may point to Russia.

Defining mutations:
XBB.1 >> Orf8:G8* (G27915T) > C21306T > S:T747I (C23802T) > G4720T > Orf1a:A540V (C1884T) > S:F486P (T23018C), Orf3a:S195F (C25976T)

Gisaid query: G4720T ,C1884T,C25976T

Tree:
![Schermata 2023-06-08 alle 17 25 05](https://github.com/cov-lineages/pango-designation/assets/87669813/37534625-8e9a-45ab-bc4b-acc99d7d8ac7)
![Schermata 2023-06-08 alle 17 26 47](https://github.com/cov-lineages/pango-designation/assets/87669813/07564b94-4caa-4ca4-85f3-c7040c0d71a2)
![Schermata 2023-06-08 alle 17 27 47](https://github.com/cov-lineages/pango-designation/assets/87669813/5a4508b2-0b71-4e6a-97aa-52be5193ef9f)

Sequences:
EPI_ISL_17189408, EPI_ISL_17497652, EPI_ISL_17566544,
EPI_ISL_17623687, EPI_ISL_17631811, EPI_ISL_17691827,
EPI_ISL_17691841-17691842, EPI_ISL_17691862, EPI_ISL_17700317,
EPI_ISL_17735946, EPI_ISL_17775142, EPI_ISL_17775149,
EPI_ISL_17775174, EPI_ISL_17775177, EPI_ISL_17775218,
EPI_ISL_17775229, EPI_ISL_17775231, EPI_ISL_17775239,
EPI_ISL_17775246, EPI_ISL_17775292, EPI_ISL_17775299,
EPI_ISL_17775302, EPI_ISL_17775306, EPI_ISL_17775312,
EPI_ISL_17775336, EPI_ISL_17775361, EPI_ISL_17775385,
EPI_ISL_17775388, EPI_ISL_17775394, EPI_ISL_17775410,
EPI_ISL_17775442, EPI_ISL_17775451, EPI_ISL_17775459,
EPI_ISL_17775461, EPI_ISL_17775464, EPI_ISL_17775472,
EPI_ISL_17775481, EPI_ISL_17775486, EPI_ISL_17775507,
EPI_ISL_17775524, EPI_ISL_17775527, EPI_ISL_17775530,
EPI_ISL_17775538, EPI_ISL_17775556, EPI_ISL_17775588,
EPI_ISL_17775613, EPI_ISL_17775619, EPI_ISL_17775624,
EPI_ISL_17775638, EPI_ISL_17775642-17775643, EPI_ISL_17775645,
EPI_ISL_17775656-17775657, EPI_ISL_17775659, EPI_ISL_17775662,

**Comment by corneliusroemer** [comment]
Ah, just saw this independently and designated as XBB.1.44.1

**Comment by FedeGueli** [comment]
Designated XBB.1.44.1 from https://github.com/cov-lineages/pango-designation/commit/46bcf7bfaad61c93a9dbf282e3a8459f43a9a56f
