### ISSUE TITLE
FL.10.1 Referenced As FL.1.10.1

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#2044]
@corneliusroemer The git commit log for commit 0666c344f5371ccde711f2cd37c1e7a75a15df00 and lineages.csv reference FL.1.10.1, but lineage_notes.txt references FL.10.1 (no first level .1) and there is no parent FL.1.10 designated.

Is FL.1.10.1 correct, or is the designation intended to be FL.10.1?

**Comment by ciscorucinski** [comment]
I tried to edit the file, but I am unable to. So I can't submit a pull request.

It cannot be `FL.1.10.1` as it only goes up to `FL.1.5` so far. There is a `FL.10`

![Screenshot from 2023-06-10 16-27-50](https://github.com/cov-lineages/pango-designation/assets/8707125/de174706-80d2-4920-8589-112166fdf556)

**Comment by corneliusroemer** [comment]
Thanks for noticing, I've fixed it
