### ISSUE TITLE
Fast growing DV.6+Orf1b:T1522I+S:Q613H (150 seqs, 16 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2045]
Transfered from https://github.com/sars-cov-2-variants/lineage-proposals/issues/116

DV.6+G23401T(S:Q613H),C18032T(Orf1b:T1522I),C6628T
GISAID query: G23401T,C18032T,C6628T

Number of seqs: 150(Australia 4 Austria 24 Belgium 1 Czech Rep 1 England 2 Finland 6 Germany 7 Hong Kong 1 Shanghai 4 Taiwan 9 Italy 1 Japan 8 Luxemburg 14 Malaysia 1 Netherlands 2 Singapore 11(1 from Malaysia) South Korea 32(1 from Japan)  USA-CA 1 USA-OH 19 USA-WA 2)

First seq: EPI_ISL_16976816, Austria, 2023-2-13
Latest: EPI_ISL_17782337, Austria, 2023-5-30

Much faster than its DV.6 parent, faster than XBB.1.9.1* but slightly slower than XBB.1.16*.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice27_genome_25cac_587c60.json?label=id:node_7289347)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/ecf1d011-35f2-49a5-8bd3-dba3981dbacc)

<img width="1083" alt="Screenshot 2023-06-10 at 13 36 36" src="https://github.com/cov-lineages/pango-designation/assets/10445944/9ec6669e-8385-4bac-ac51-3e1714c12a6a">
<img width="1053" alt="Screenshot 2023-06-10 at 13 36 15" src="https://github.com/cov-lineages/pango-designation/assets/10445944/1b07ecb5-1e22-4727-8633-d008f0d4e510">

<img width="1056" alt="Screenshot 2023-06-10 at 13 35 58" src="https://github.com/cov-lineages/pango-designation/assets/10445944/1112f837-dc12-4f8f-bc49-0d60f768561f">

**Comment by FedeGueli** [comment]
While it doesnt seem as fast as FK.1.1 is clearly faster than circulating CH.1.1* baseline: https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-03-31%26to%3D2023-06-10/variants?nextcladePangoLineage=CH.1.1*&nucMutations1=G23401T%2CC18032T%2CC6628T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Designated DV.6.2 via https://github.com/cov-lineages/pango-designation/commit/cbd5a7b15cdbed91be84a044d0edc2b64c6d8aba
