### ISSUE TITLE
Lineage BR.5.1 Notes Errata

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#2048]
The commit log and lineage notes show "ORF1b:T5923I" as a defining mutation for BR.5.1. This residue position is too large. Was "ORF1ab:T5923I" intended? This would be ORF1b:T1522I.

The listed mutations BR.5 + ORF1a:K2029N, ORF1b:T5923I, A20289G cause an error on CoV-Spectrum. However, BR.5 + ORF1a:K2029N, ORF1b:T5923I, A20289G returns approximately the expected number of sequences mostly from South Korea.

**Comment by Over-There-Is** [comment]
It is actually ORF1ab:T5923I, namely ORF1b:T1522I.
