### ISSUE TITLE
Proposal for a potential sublineage of B.1 circulating in Eastern Cape, South Africa, with Spike P384L, T415A, N440K, Y453F, N460K, A475V and E484K

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#205]
Potential sublineage of B.1 (9 sequences in the Nelson Mandela Bay, Eastern Cape, South Africa)
**Earliest sequence**: 2020/5/24
**Most recent sequence**: 2021/6/10
**Mutations**:
**N**: I84V, R203S
**ORF1a**: T265I, L3201P (7/9 sequences), K3353R, 3675/3677del
**ORF1b**: P314L
**ORF3a**: S40L, Q57H (8/9 sequences)
**ORF7a**: V71L
**S**: W64R, T95I, T415A, N440T, N460K, E484K, D614G, Q675R, T859N, D936G (8/9 sequences), G1219C (8/9 sequences)
5 out of these 9 sequences also have the following additional mutations:
**E**: S68F
**S**: L5F, 14/18DEL, 136/137DEL, 141/143DEL, W152R, 210DEL, P384L, N440K, Y453F, A475V, P621S, H655Y, P681H
Genomes:
EPI_ISL_2693834, EPI_ISL_2693841, EPI_ISL_2955458, EPI_ISL_3451089-3451094
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/130893591-2ac8731c-90e6-44b7-b7e4-a9eb45e2ec5f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31138_703740.json?c=gt-S_460

**Comment by chrisruis** [comment]
Thanks @c19850727. We've added this as lineage B.1.638 in [v1.2.73](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.73)

**Comment by c19850727** [comment]
I just double checked and 2 of those sequences have a big bad insertion at NTD.
S:ins214KKLIRGD, in EPI_ISL_3451093 and EPI_ISL_3451094.

**Comment by thomasppeacock** [comment]
Similar region (but much larger insert) to the insertions seens in A.2.5, B.1.214.2 and #161 (as well as lots of smaller lineages/clusters/singlets). Described as an insertion hotspot here: https://www.biorxiv.org/content/10.1101/2021.04.17.440288v2.full

Very odd cluster of isolates - as I said before I suspect if we get a lot more of them B.1.638 will end up split into subvariants (similar to how the origional B.1.617 was)

**Comment by silcn** [comment]
Perhaps rather than lots of undetected circulation, this diverse cluster resulted from multiple genetically distinct transmissions from a single immunocompromised person? Otherwise seems unlikely that you'd have such diversity but only concentrated in one area.

**Comment by shay671** [comment]
Few points regarding B.1.638 :

- When analyzing it's 13 known sequences, There a consensus of 14 mutations present in 12-13 sequences. But! the samples are much more mutated, 8 of them with more than 40 mutations, (up to 49). a lot of the added mutations are in regions that are conserved (RBD , NTD, N) . as stated above by @thomasppeacock , if more samples will arrive than B.1.638 will be the "mother" lineage from which other lineages evolved, although there is no sequence of this B.1.638 by  itself. 

The separation between the 13 sequences could also be observed from this similarity matrix of mutations :
![image](https://user-images.githubusercontent.com/80166370/132490338-b4c3de9a-cc13-4b06-a85e-9fc3e5672ebf.png)


-There is a non defined lineage of 6 sequences from South Africa. This lineage has 6 out of the 14 defining mutations of B.1.638:

NSP2:T85I
NSP5:K90R
NSP6- The SGF deletion
S:W64R
S:T95I
S:E484K

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_141d5_7b8720.json?label=nuc%20mutations:C25487T,A28272G

(This 6 sequences lineage are quite interesting by itself, having also S:T478K, and 3 non synonymous mutation om N. But it seems there are no known sequences for it in the last 3 months). 

- There is a strong convergence convergence in amino acid position 460 in the RBD. All 13 has it mutated from N to K , and all through mutation in nucleotide 22942. But 10 through the mutation to G and 3 through te mutation to A. Different codons, Same amino acid mutation. Kind of a hint that maybe there's an epistatic advantage for this mutation? 


- The RBD of this lineage is quite interesting - 
![image](https://user-images.githubusercontent.com/80166370/132491504-e1bcc8a5-4010-4b8a-8460-b7723bd4a469.png)
Only 2 mutations are shared by all 13 in the RBD. 484 and 460. 
As far as i remember,  6 is a new record for RBD mutations for defined lineage (correct me please if i'm wrong)

**Comment by JosieLikesCats** [comment]
Hi everyone, I'm from the National Institute for Communicable Diseases in SA. Thanks for the interesting input on these sequences. We flagged these internally when we deposited them and have been following up since then, and so far it looks like it was an isolated outbreak.
