### ISSUE TITLE
Saltation of BQ.1.1.40 with S:S71Y, S:S112L, S:E132Q, S:L212I, S:D339H, S:T385I, S:Y453F, S:A653V, S:D1139Y and 4 other non-Spike mutation (11 seqs in Ontario, Canada) 

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#2052]
transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/132

Defining mutations: BQ.1.1.40>C1441T, C1441T, C23191T, G25690T(ORF3:G200C)>saltation branch

Substitutions in saltation:
Spike: S:S71Y, S:S112L, S:E132Q (some seqs are missing S:132), S:L212I, S:D339H, S:T385I, S:Y453F, S:A653V, S:D1139Y
ORF1a: R24C, N2162S
ORF1b:M1839L
N: A252S
![QQ截图20230612233812](https://github.com/cov-lineages/pango-designation/assets/121703496/97f2f9bf-2af9-4f5a-8368-ed20ab5645ca)

Deletions in saltation (shown Spike only) 
del S:69-70 (del nuc 21765-21770), del S:211 (del nuc 22194-22196)
![QQ截图20230612233827](https://github.com/cov-lineages/pango-designation/assets/121703496/6a3a08e4-09c9-433b-9507-e99b97e63291)
![QQ截图20230612233820](https://github.com/cov-lineages/pango-designation/assets/121703496/0468702c-ea9f-4504-9f46-43221ee36db8)

GISAID query: Spike_Y453F, Spike_G339H, Spike_S112L (NUCs only query: A6750G, C12241T)
Earliest seq: 2023-05-21 (Canada, EPI_ISL_17743165)
Most recent seq: 2023-06-03 (Canada, EPI_ISL_17787556)
Countries detected: Canada (11, all in Ontario, Canada)

Usher Tree:
![QQ截图20230612233749](https://github.com/cov-lineages/pango-designation/assets/121703496/e69a7588-6a7d-4448-941b-2093359cd527)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3664f_721740.json
As the neighbor seqs are collected in Dec2022 to Mar 2023, the long saltation may have evolved several months, which is quite likely associated with chronic.

MetaData show all the seqs are from different patient, and most of them are aged 70+.

However, Canada is often updated a series of seqs with same mutations, which may be a nursing home outbreak pointed by @ryhisner. Now all the seqs are in Ontario, and they need a further watch if emerge outside Ontairo.

Genomes:
EPI_ISL_17743165, EPI_ISL_17743168, EPI_ISL_17763978, EPI_ISL_17763985, EPI_ISL_17767043, EPI_ISL_17767046,
EPI_ISL_17767051-17767052, EPI_ISL_17767054, EPI_ISL_17787549, EPI_ISL_17787556

**Comment by plomano** [comment]
As a note, we may be able to get more info from the Public Health Ontario genomics report that updates every Tuesday. The latest report only covers until the 27th of May, so next week most of those sequences should show up.

I’ll link the reports page, the [SARS-CoV-2 Genomic Surveillance in Ontario] report is the one to open.

https://www.publichealthontario.ca/en/Data-and-Analysis/Infectious-Disease/COVID-19-Data-Surveillance

@corneliusroemer @FedeGueli

**Comment by alex-m-a** [comment]
After follow-up with the submitter, it has been confirmed that these are associated with a case cluster from a singular facility.

**Comment by FedeGueli** [comment]
It seems dying off, luckily .

**Comment by HynnSpylor** [comment]
Fortunately it seems a nosocomial infection event and onlynot spread further. I‘ll close it if no new seqs updated in 3 days.
