### ISSUE TITLE
XBB.1.22.1 sublineage with S:Q675K (99 seqs in 18 countries)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#2053]
Defining mutations: XBB.1.22.1>C925A (ORF1a:D220E), G2265A (ORF1a:C667Y), C23585A (S:Q675K)
GISAID query: Spike_Y200C, Spike_Q675K, G2265A
Earliest seq: 2023-02-20 (Germany, EPI_ISL_17254760)
Most recent seq: 2023-05-29 (Portugal, EPI_ISL_17786191)
Countries detected: Indonesia (11), Germany (3), Portugal (3), India (2), UK (2), Brunei (2), Malaysia (2), France (1), Luxemburg (1), USA (1), Japan (1), Singapore (1)

Usher Tree:
![QQ截图20230613012936](https://github.com/cov-lineages/pango-designation/assets/121703496/fe47cb8a-e533-4149-84e7-5fb62f8f2035)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e1ba_74eb00.json?c=gt-S_675
A mutation near FCS, despite S:Q675H is more common than S:Q675K. 

Genomes:
EPI_ISL_17223621, EPI_ISL_17254760, EPI_ISL_17266838, EPI_ISL_17388874, EPI_ISL_17389250-17389251, EPI_ISL_17389319,
EPI_ISL_17406962, EPI_ISL_17469048, EPI_ISL_17503882, EPI_ISL_17503885, EPI_ISL_17521393, EPI_ISL_17630669,
EPI_ISL_17630982, EPI_ISL_17654409, EPI_ISL_17655046, EPI_ISL_17657336, EPI_ISL_17681329, EPI_ISL_17681356,
EPI_ISL_17691900, EPI_ISL_17712546, EPI_ISL_17717567, EPI_ISL_17721796, EPI_ISL_17742266, EPI_ISL_17771926,
EPI_ISL_17786112, EPI_ISL_17786191, EPI_ISL_17788306, EPI_ISL_17788344, EPI_ISL_17788378

**Comment by FedeGueli** [comment]
Why not on the other page?

**Comment by HynnSpylor** [comment]
@FedeGueli I'm very sorry but puzzled - do you mean why I did not propose it in SARS-Cov-2 lineage proposals?
In my view if a sublineage reaches 30 seqs and emerges in more than two countries, then it can be directly proposed in main page.

**Comment by FedeGueli** [comment]
Yeah of course @HynnSpylor i think there is always time to propose. Here it could be overlooked. with our double scheme we are getting the fast lineages lineages designated before, but that is just my view, of course anyone could urge to propose directly here if there are reasons to .

**Comment by FedeGueli** [comment]
still 31 viruses last sample from Australia that did not upload a big batch this week.  we will see the next week.

**Comment by HynnSpylor** [comment]
34 seqs now and with a branch of S:S408N (6 seqs)
![QQ截图20230626201243](https://github.com/cov-lineages/pango-designation/assets/121703496/8959c29d-f3f6-4dbd-a0c6-cae77b9d0020)

**Comment by FedeGueli** [comment]
This now reached 43seqs  and one sublineage counting 8 sequences has got S:R408N


https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a8f_3a240.json?c=userOrOld&label=id:node_6707443
![Schermata 2023-07-01 alle 18 05 55](https://github.com/cov-lineages/pango-designation/assets/87669813/c33ed5df-e204-4907-92c3-a33091879956)


Speaking broadly XBB.1.22.1 seems first lineage to tolerate or promote the emergence of various mutations at 408 (defining in BA.2 with S)
![Uploading Schermata 2023-07-01 alle 18.06.41.png…]()

see also the lineage proposed in the other page today.

I would designate this one . cc @corneliusroemer @InfrPopGen

**Comment by FedeGueli** [comment]
C925A , G2265A , C23585A finds 62 as today. 


![Schermata 2023-07-26 alle 10 55 24](https://github.com/cov-lineages/pango-designation/assets/87669813/e7e2b0e1-d6d5-439b-b093-498280d4ccba)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2bf2_dc130.json?c=country&label=id:node_6775589

ping @corneliusroemer i suggest to designate this one.

**Comment by HynnSpylor** [comment]
81 seqs in 18 countries now
Recently the branch with S:T385A and S:D1118Y is circulating in Europe, and branch with S:R408G in US
<img width="707" alt="屏幕截图 2023-08-21 220142" src="https://github.com/cov-lineages/pango-designation/assets/121703496/6e37cb85-a0a7-43a4-966a-8dc3c89c03ae">

**Comment by HynnSpylor** [comment]
87 seqs now and it seems circulating again.
US branch (with S:R408G) has 2 new seqs with S:N481S

**Comment by FedeGueli** [comment]
Likely it deserves a designation.

**Comment by Memorablea** [comment]
94 NOW

**Comment by FedeGueli** [comment]
Now designated FY.9 via https://github.com/cov-lineages/pango-designation/commit/066dbbb5223ad40263a8df202c920a31ff25ae6f 

milestone missing @corneliusroemer
