### ISSUE TITLE
Proposal for Broadening XBC.1.1.2 to Orf3a:P262L due  the fact  actual defining mutation orf7b:L32F comes after the XBC orf7b frameshift

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2055]
Evidences:
https://github.com/cov-lineages/pango-designation/commit/0910a303d6fcafbde56874c80ca2f0f7ccf55a3c#commitcomment-117867742

**Comment by FedeGueli** [comment]
cc @corneliusroemer

**Comment by aviczhl2** [comment]
What's the real mutation of this? 
Is there currently a way to describe frame-shifted mutations?

**Comment by FedeGueli** [comment]
Orf7b:T32I , i dont think so .
I think @ryhisner is finding more lineages with the new Orf7b.

**Comment by FedeGueli** [comment]
@AngieHinrichs when you have time to look at this. to me is quite important, cause we have a lineage with a non existent defining mutation due a frameshift that cause the creation of a brand new Orf7b (obviously not annotated anywhere)

**Comment by FedeGueli** [comment]
no answer closing it.

**Comment by AngieHinrichs** [comment]
Yeah, sorry, I didn't have a good answer.  :)  Indels are invisible to UShER, so as long as lineage discovery and the pangolin tool's assignments depend on the UShER tree, we need a "marker" substitution mutation for any lineage that also has an indel.  Fortunately substitutions are common enough that so far we've been able to find one.

Also, SARS-CoV-2 sequences are assembled by many different pipelines, some of which totally fail to correctly assemble indels (and many of which occasionally fail when read coverage isn't good enough I guess).  So indels are very inconsistently detected... and if UShER did pay attention to them, it would probably be misled a lot!

**Comment by FedeGueli** [comment]
> Yeah, sorry, I didn't have a good answer. :) Indels are invisible to UShER, so as long as lineage discovery and the pangolin tool's assignments depend on the UShER tree, we need a "marker" substitution mutation for any lineage that also has an indel. Fortunately substitutions are common enough that so far we've been able to find one.
> 
> Also, SARS-CoV-2 sequences are assembled by many different pipelines, some of which totally fail to correctly assemble indels (and many of which occasionally fail when read coverage isn't good enough I guess). So indels are very inconsistently detected... and if UShER did pay attention to them, it would probably be misled a lot!

Thank you Angie you have already answered me in the commit! i mean no answer no decision so closing it . To me is weird to have the defining mutation that is unreal (in fact it is after the frameshift a completely different mutation) that could lead to errors in anyone looking at it for any reason . But still this is very small so not that important at the end.
