### ISSUE TITLE
xbc.1.6.3 with ORF1a:T1597I and ORF1a:A2123V (365 seq.) mostly Australia

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2056]
transfered from https://github.com/sars-cov-2-variants/lineage-proposals/issues/71 
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/a95ccdfc-86f3-45dc-8dde-53190c8e5a00)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29c0b_c05b70.json?c=gt-nuc_6633&label=id:node_6127687

**Comment by FedeGueli** [comment]
Gisaid query : C13297T, C28791T, C5055T now returns  208 sequences for this one . interestingly it reaches 2% of samples from NSW AUS in June. ping @corneliusroemer

**Comment by Fearuncle** [comment]
C13297T, C28791T, C5055T returns 265

**Comment by Fearuncle** [comment]
designated as HW.1
