### ISSUE TITLE
GJ.1 sublineage with ORF1b:V1110I, C1549T, and C7819G first detected in South Korea (164 GISAID seqs as of 2023-06-16; USA, China, Singapore, China, South Korea, Australia, Italy, Japan, New Zealand, Switzerland, Finland, Hong Kong, Philippines, Spain, Sweden, UK)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#2059]
GJ.1 sublineage with ORF1b:V1110I (NSP13:V187I, G16795A), C1549T, and C7819G first detected in South Korea and detected in at least 15 different countries.

This issue is promoted from https://github.com/sars-cov-2-variants/lineage-proposals/issues/112 at @FedeGueli's request.

As of 2023-06-16, Cov-Spectrum reports 106 good-quality (139 total) GJ.1+ORF1b:1110I+1549T+7819G sequences. GISAID shows 164 sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXBB.2.3.3*+%26+ORF1a%3AI4205V+%26+ORF1b%3AV1110I+%26+ORF8%3AE106Q+%26+C1549T+%26+C7819G&nextcladeQcOverallScoreTo=29&

As of 2023-06-16 there is insufficient data in any particular country to determine reliable growth advantages relative to GJ.1 at this time. However, over time more countries are reporting sammples of this lineage.

On 2023-05-29, UShER showed all of the CoV-Spectrum samples on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_XBB 2 3 3+ORF1a_4205V+ORF1b_1110I+ORF8_106Q+1549T+7819G](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/629ee2ed-924a-4e64-a38a-5766fd9f9c63)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/05/subtreeAuspice1_genome_CoV-Spectrum_XBB.2.3.3%2BORF1a_4205V%2BORF1b_1110I%2BORF8_106Q%2B1549T%2B7819G.json?c=gt-ORF1ab_5511&label=id%3Anode_6996120

GISAID query: A12878G, G16795A, G28209C, C1549T, C7819G

First GISAID sequence: South Korea 2023-04-13

Most Recent GISAID sequence: Singapore 2023-06-06

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support_XBB.2.3.3+ORF1a_4205V+ORF1b_1110I+ORF8_106Q+1549T_7819G.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/11593575/Support_XBB.2.3.3%2BORF1a_4205V%2BORF1b_1110I%2BORF8_106Q%2B1549T_7819G.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at[gisaid-epi-isl_XBB.2.3.3+ORF1a_4205V_ORF1b_1110I+ORF8_106Q+1549T+7819G.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/11593573/gisaid-epi-isl_XBB.2.3.3%2BORF1a_4205V_ORF1b_1110I%2BORF8_106Q%2B1549T%2B7819G.txt).

This is a sibling of the lineage described in https://github.com/sars-cov-2-variants/lineage-proposals/issues/109.

This lineage was first noted as a branch in the initial submission for the GJ.1 designation proposal https://github.com/cov-lineages/pango-designation/issues/2005.

**Comment by FedeGueli** [comment]
202 sequences as today 1%of samples collected in Singapore in June.
