### ISSUE TITLE
Proposal for a few potential new lineages sequenced at Japan's border-entry tests

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#206]
So I was browsing a few hundred sequences that NIID of Japan uploaded concerning those cases that they caught positive at border-entry tests. They sequenced a lot of them; and interestingly, some of those cases have had travel history from regions with otherwise no/low sequence coverage.
 
Thus some of the following proposed new lineage are small in number, and maybe a bit outdated. 

**Proposed new lineage 1**
Potential sublineage of B.1.617.2 (49 sequences)
**Countries circulating**: Ghana (24 sequences), Italy (9), the UK (12), the US (1), New Zealand (2), Japan ex-Ghana (1)
**Earliest sequence**: 2020/5/18 (Ghana)
**Most recent sequence**: 2021/8/20 (The UK)
Mutations in addition to B.1.617.2: **E:D72Y**
**Genomes**:
[Proposed lineage 1.csv](https://github.com/cov-lineages/pango-designation/files/7080408/Proposed.lineage.1.csv)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_55a1b_d79d30.json?c=gt-E_72
BTW: There is a parent lineage with a total of 153 sequences, featuring N:P151S, most of which are also from Ghana.

**Proposed new lineage 2**
Potential sublineage of B.1.617.2 (21 sequences)
**Countries circulating**: Korea ex-Myanmar (11 sequences), Thailand ex-Myanmar (4) Singapore ex-Myanmar (2), Japan ex-Myanmar (3), the UK (1)
**Earliest sequence**: 2020/6/30 (Korea ex-Myanmar)
**Most recent sequence**: 2021/7/31 (Korea ex-Myanmar)
Mutations in addition to B.1.617.2: **N:T362I, N:R385K, S:S640P, S:V1104L**
**Genomes**:
[Proposed lineage 2.csv](https://github.com/cov-lineages/pango-designation/files/7080560/Proposed.lineage.2.csv)
![image](https://user-images.githubusercontent.com/86835836/131429621-9ce6a37e-dd35-4055-bc47-ae8c143dfc50.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3b37d_d6c000.json?c=gt-S_640&tl=country

**Proposed new lineage 3**
Potential sublineage of B.1.617.2 (155 sequences)
**Countries circulating**: Japan ex-Afghanistan (3 sequences), Australia, New Zealand, the US, the UK and Europe
**Earliest sequence**: 2020/5/21 (Netherlands)
**Most recent sequence**: 2021/8/26 (Belgium)
Mutations in addition to B.1.617.2: **N:P364L, ORF1a: R184C, ORF7b:L14S**
**Genomes**:
[Proposed lineage 3.csv](https://github.com/cov-lineages/pango-designation/files/7081112/Proposed.lineage.3.csv)
![image](https://user-images.githubusercontent.com/86835836/131440117-8f528ec2-5395-4c09-9b06-a0e463e33492.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_30b2b_da4d20.json?c=gt-ORF1a_184
However, these 3 sequences found at Japan airport from Afghanistan do have additional N:214/215del and ORF1a:L104F mutations that are not shared with the other sequences.

**Proposed new lineage 4**
Potential sublineage of B.1.617.2 (116 sequences)
**Countries circulating**: Japan ex-Morocco (1 sequence), the US, the UK, Canada and Europe
**Earliest sequence**: 2020/6/11 (Japan ex-Morocco)
**Most recent sequence**: 2021/8/24 (Denmark)
Mutations in addition to B.1.617.2: **N:Q289H, S:T29A, S:T250I, S:T299I, S:Q613H**
**Genomes**:
[Proposed lineage 4.csv](https://github.com/cov-lineages/pango-designation/files/7081199/Proposed.lineage.4.csv)
![image](https://user-images.githubusercontent.com/86835836/131441833-3c590a22-8daa-433d-b3f9-49512c9a925f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d8be_d9f330.json?c=gt-N_289

**Proposed new lineage 5**
Potential sublineage of P.3 (5 sequences)
**Countries circulating**: Japan ex-the Philippines (2 sequences), the US-NJ (2), Norway (1)
**Earliest sequence**: 2020/6/21 (Japan ex-the Philippines)
**Most recent sequence**: 2021/7/21 (Japan ex-the Philippines)
Mutations in addition to P.3: 
**N**: T391I, 
**ORF1a**: Y496C, A599V, E1340D, S2625F, D2980N, L3201P, D3681E, L3930F, R4387C
**ORF1b**: K1679R
**S**: P9L, W64R, Y265C
**Genomes**:
[Proposed lineage 5.csv](https://github.com/cov-lineages/pango-designation/files/7081350/Proposed.lineage.5.csv)
![image](https://user-images.githubusercontent.com/86835836/131445124-2cd98920-6195-4408-9712-d26bc669e833.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2cc20_d62070.json?c=gt-ORF1a_1340&label=nuc%20mutations:A1752G,C2061T,T4516C,A18503G,A20244G,C21588T,C29445T

**Proposed new lineage 6**
Looks like a cousin of B.1.1.523 (6 sequences)
**Countries circulating**: Russia (3 sequences, probably already died out though), the US-CA (1), the US-NJ (1), Japan ex-Tajikistan (1)
**Earliest sequence**: 2020/2/25 (Russia)
**Most recent sequence**: 2021/7/2 (Japan ex-Tajikistan)
Mutations:
**N**: R203K, G204R
**ORF1a**: N449D
**ORF1b**: P314L, P1000L
**ORF3a**: S171L
**S**: W152L, R158S, E484K, D614G, D796Y, D839V
The more recent 3 sequences (the 2 in the US and 1 in Japan) also have the following additional mutations:
**E**: A41V
**M**: I82S
**N**: P80R
**ORF1a**: R3164H, T3255I, V3653F
**ORF1b**: S220N, H1087Y, E1288D
**ORF9b**: Q77E
**S**: H66Q, A67T, 144del, R346K, T478K, P681H
**Genomes**:
[Proposed lineage 6.csv](https://github.com/cov-lineages/pango-designation/files/7081457/Proposed.lineage.6.csv)
![image](https://user-images.githubusercontent.com/86835836/131447195-c80787ec-cb65-4dc1-9cb1-c2f6562c7dd9.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_379d8_cf3fa0.json?c=gt-S_796

**Comment by chrisruis** [comment]
Thanks @c19850727 for submitting.

Proposed lineage 2 appears to be a Myanmar lineage, with most sequences within the clade either being from Myanmar or having travel history from Myanmar. This lineage is therefore likely to be epidemiologically distinct and we've added this as AY.31 in [v1.2.75](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.75) with 27 designated sequences. We've started this lineage on a branch with T3306C (Orf1ab:M1014T), T23480C (S:S640P) and G24872T (S:V1104L).

We need new lineages to be epidemiologically distinct. Proposed lineages 1, 3 and 4 are in parts of the tree where sequences from lots of countries are interspersed without travel history information for most sequences. These clades therefore do not appear to be epidemiologically distinct and we recommend these sequences are referred to as B.1.617.2 for now.

P.3 is a predominantly Philippines lineage so proposed lineage 5 doesn't appear to be epidemiologically distinct from the rest of P.3.

Proposed lineage 6 is in a small clade containing 7 sequences collected over 4 months, with the Japan sequence being the only sequence with a recorded history of travel. This therefore doesn't appear to warrant a new lineage at this stage.

Thanks again for submitting.
