### ISSUE TITLE
XBB.1.5 sublineage with S:Q613H, S:H1058Y and NSP5_M17V (146 seq in 13 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2061]
XBB.1.5> T17124C> T10204C> C4993T, A10103G(Orf1a:M3280V = NSP5_M17V), C12025T> T23488C, C24734T(S:H1058Y)> G29543T> G23401T(S:Q613H)

Transfer from sars-cov-2-variants/lineage-proposals#105

GISAID Query: A10103G, G23401T
Earliest Sequence: 02-07 Texas, US EPI_ISL_17018910
Latest Sequence: 09-13 Ontario, Canada EPI_ISL_18278021
Regions Detected:
**US** 66 (Texas 19, Florida 10, Ohio 9, California 8, New Mexico 6, Pennsylvania 4, Arizona 1, Delaware 1, Georgia 1, Illinois 1, Maine 1, Maryland 1, Minnesota 1, Mississippi 1, New York 1, S. Carolina 1), **Canada** 32 (Ontario 20, Quebec 9, BC 1, Manitoba 1, Saskatchewan 1), **Jamaica** 2,
**China** 36 (Guangdong 17[5 imported], Shanghai 7 [1 from HK, 1 from Macao, 2 from Japan, 2 from **S. Korea**], Sichuan 6, Hubei 2, Xinjiang 2, Fujian 1, Gansu 1), **Singapore** 2(1 from China), **Japan** 1,
**Italy** 2(Emilia-Romagna 1, Lombardy 1), **Austria** 1(Kärnten), **Norway** 1(Viken), **Spain** 1(Madrid), **UK** 1(Scotland),
**NZ** 1(Auckland)

[Genome Tree](https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_10868_1eeed0.json?label=id:node_6880832)

![2023-06-19](https://github.com/cov-lineages/pango-designation/assets/38100637/b391faa1-bd82-42bb-9936-21bea7ccbabf)

<details><summary>Sequences:</summary>

EPI_ISL_17018910, EPI_ISL_17128466, EPI_ISL_17134670,
EPI_ISL_17147355, EPI_ISL_17180122, EPI_ISL_17240790,
EPI_ISL_17240820, EPI_ISL_17251151, EPI_ISL_17307062,
EPI_ISL_17328203, EPI_ISL_17333504, EPI_ISL_17384370,
EPI_ISL_17428843, EPI_ISL_17430630, EPI_ISL_17442452,
EPI_ISL_17466859, EPI_ISL_17478010, EPI_ISL_17486149,
EPI_ISL_17490820, EPI_ISL_17490828, EPI_ISL_17490840-17490841,
EPI_ISL_17490843, EPI_ISL_17495826-17495827, EPI_ISL_17495830,
EPI_ISL_17513804, EPI_ISL_17526677, EPI_ISL_17537178,
EPI_ISL_17537425, EPI_ISL_17537546, EPI_ISL_17543608,
EPI_ISL_17543762, EPI_ISL_17543766, EPI_ISL_17546803,
EPI_ISL_17582017, EPI_ISL_17582875, EPI_ISL_17589757,
EPI_ISL_17590587, EPI_ISL_17635248, EPI_ISL_17641720,
EPI_ISL_17645061, EPI_ISL_17645836, EPI_ISL_17648261,
EPI_ISL_17651042, EPI_ISL_17651443, EPI_ISL_17651516,
EPI_ISL_17651539, EPI_ISL_17653325, EPI_ISL_17680721,
EPI_ISL_17680723-17680724, EPI_ISL_17684163-17684164, EPI_ISL_17687653,
EPI_ISL_17690049, EPI_ISL_17693975, EPI_ISL_17693983,
EPI_ISL_17697653, EPI_ISL_17697716, EPI_ISL_17697854,
EPI_ISL_17698017, EPI_ISL_17698088, EPI_ISL_17711169,
EPI_ISL_17711499, EPI_ISL_17714292, EPI_ISL_17717370,
EPI_ISL_17718430, EPI_ISL_17722753, EPI_ISL_17722767,
EPI_ISL_17724530, EPI_ISL_17725128-17725129, EPI_ISL_17727015,
EPI_ISL_17727142, EPI_ISL_17744319, EPI_ISL_17744321-17744322,
EPI_ISL_17744333, EPI_ISL_17763572, EPI_ISL_17764393,
EPI_ISL_17765395, EPI_ISL_17775378, EPI_ISL_17775477,
EPI_ISL_17778265, EPI_ISL_17782073, EPI_ISL_17782082,
EPI_ISL_17789672, EPI_ISL_17790551, EPI_ISL_17795103,
EPI_ISL_17795530, EPI_ISL_17797681, EPI_ISL_17801945,
EPI_ISL_17809778, EPI_ISL_17810540, EPI_ISL_17811083,
EPI_ISL_17811134, EPI_ISL_17850757, EPI_ISL_17852382,
EPI_ISL_17852481, EPI_ISL_17853376, EPI_ISL_17854944,
EPI_ISL_17859915, EPI_ISL_17861080, EPI_ISL_17861548,
EPI_ISL_17862584, EPI_ISL_17871147, EPI_ISL_17871169,
EPI_ISL_17879902, EPI_ISL_17959985, EPI_ISL_17962607,
EPI_ISL_17965691, EPI_ISL_17965757, EPI_ISL_17965770,
EPI_ISL_17972215, EPI_ISL_17979460, EPI_ISL_17987472,
EPI_ISL_17989048, EPI_ISL_17990205, EPI_ISL_17990326,
EPI_ISL_18007540, EPI_ISL_18030510, EPI_ISL_18033771,
EPI_ISL_18034288, EPI_ISL_18034785, EPI_ISL_18034825,
EPI_ISL_18034873, EPI_ISL_18034945, EPI_ISL_18035997,
EPI_ISL_18036116, EPI_ISL_18036383, EPI_ISL_18036766,
EPI_ISL_18036857, EPI_ISL_18037246, EPI_ISL_18069682,
EPI_ISL_18073942, EPI_ISL_18079559, EPI_ISL_18133926,
EPI_ISL_18146101, EPI_ISL_18277671, EPI_ISL_18278007,
EPI_ISL_18278021, EPI_ISL_18279864, EPI_ISL_18279889,
OQ867774.1

An Australian sequence with S:Q613H dropout (not including in counting): EPI_ISL_17683550</details>

**Comment by Over-There-Is** [comment]
I am sure that the G9805A, T18765A branch is still circulating in Guangdong until June. Wait for uploading.

**Comment by FedeGueli** [comment]
This should be designated to me is coming from an area with low sequencing, it could be also in some countries with good coverage as China or Japan, to say, but with regions less sequenced.

**Comment by Over-There-Is** [comment]
> I am sure that the G9805A, T18765A branch is still circulating in Guangdong until June. Wait for uploading.

A sequence with G9805A, T18765A from Macao is detected by Shanghai, and Macao is a city next to Guangdong.

**Comment by Over-There-Is** [comment]
Slovakia 04-19

**Comment by FedeGueli** [comment]
Ping @corneliusroemer @InfrPopGen this should be designated S:Q613H is still one of the mutations giving some (slight)advantage. 
![Schermata 2023-07-16 alle 12 50 50](https://github.com/cov-lineages/pango-designation/assets/87669813/f853be18-dbe5-4063-813d-7025ca4d18c4)

**Comment by Over-There-Is** [comment]
> Slovakia 04-19

Convergence

**Comment by Over-There-Is** [comment]
Italy EPI_ISL_17990205

**Comment by Over-There-Is** [comment]
Guangdong +12, 5 imported

**Comment by Over-There-Is** [comment]
One more Chinese province detected

**Comment by Over-There-Is** [comment]
Hubei/HCDC-YC2612/2023|EPI_ISL_18146101|2023-08-09 F456L

**Comment by FedeGueli** [comment]
The 456L branch seems dead could be removed from the proposal i think

**Comment by FedeGueli** [comment]
146 ses for the wider branch very slow, i suggest to close it directly.

**Comment by Over-There-Is** [comment]
Canada+3, Jamaica+2
