### ISSUE TITLE
Huge Branch (1500 seqs，70%+ of parent, increased to about 85% recently and still growing) of XBB.2.3.2 that we need to classify: XBB.2.3.2*+G24193A

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#2064]
Sublineage of XBB.2.3.2
Additional Mutation: G24193A
Gisaid Inquiry: XBB.2.3.2+G24193A (I applied a rather arbitrary filter of S:V213G and time filter of samples from those, but nevertheless it is still very big)
Earliest Sequence: EPI_ISL_17396813 France 2023-03-01 (there are many sequences without clear indication of date or erroneous date, so I pick this one)
Latest Sequence: EPI_ISL_17812772 Bangladesh 2023-06-17
Sequence List: (there are 1500 of them, this list is mildly incomplete)
EPI_ISL_17374766, EPI_ISL_17388410, EPI_ISL_17388419,
EPI_ISL_17388450, EPI_ISL_17388464, EPI_ISL_17388469,
EPI_ISL_17388480, EPI_ISL_17388483, EPI_ISL_17388488,
EPI_ISL_17388493, EPI_ISL_17388503-17388504, EPI_ISL_17388546,
EPI_ISL_17388554, EPI_ISL_17388561, EPI_ISL_17388564,
EPI_ISL_17388579, EPI_ISL_17388630, EPI_ISL_17388644,
EPI_ISL_17388646, EPI_ISL_17388655, EPI_ISL_17388658,
EPI_ISL_17388665, EPI_ISL_17388675, EPI_ISL_17388678,
EPI_ISL_17388705, EPI_ISL_17388710, EPI_ISL_17388723,
EPI_ISL_17388758, EPI_ISL_17388783, EPI_ISL_17388815,
EPI_ISL_17388821, EPI_ISL_17388832, EPI_ISL_17388840,
EPI_ISL_17388848, EPI_ISL_17388851, EPI_ISL_17388862,
EPI_ISL_17388865, EPI_ISL_17388871, EPI_ISL_17390416,
EPI_ISL_17391204, EPI_ISL_17393765, EPI_ISL_17394647,
EPI_ISL_17396813, EPI_ISL_17400482, EPI_ISL_17403766,
EPI_ISL_17403771, EPI_ISL_17405885, EPI_ISL_17408139,
EPI_ISL_17409392, EPI_ISL_17409396, EPI_ISL_17415633,
EPI_ISL_17417477, EPI_ISL_17417533, EPI_ISL_17417851,
EPI_ISL_17419333, EPI_ISL_17423208, EPI_ISL_17425704,
EPI_ISL_17428362, EPI_ISL_17428492, EPI_ISL_17428529,
EPI_ISL_17431951, EPI_ISL_17431954, EPI_ISL_17431956,
EPI_ISL_17431958, EPI_ISL_17431962-17431965, EPI_ISL_17431968,
EPI_ISL_17431970-17431971, EPI_ISL_17431976, EPI_ISL_17431988,
EPI_ISL_17431999, EPI_ISL_17432007, EPI_ISL_17432037,
EPI_ISL_17432043, EPI_ISL_17432071, EPI_ISL_17432080,
EPI_ISL_17432104, EPI_ISL_17432114, EPI_ISL_17432119,
EPI_ISL_17432123, EPI_ISL_17432132, EPI_ISL_17432155,
EPI_ISL_17432191, EPI_ISL_17432193, EPI_ISL_17432195,
EPI_ISL_17432198, EPI_ISL_17432200, EPI_ISL_17432206,
EPI_ISL_17432226-17432227, EPI_ISL_17432233, EPI_ISL_17432235,
EPI_ISL_17432243, EPI_ISL_17432253, EPI_ISL_17432256-17432257,
EPI_ISL_17432279, EPI_ISL_17434165, EPI_ISL_17441011,
EPI_ISL_17445714, EPI_ISL_17445723-17445724, EPI_ISL_17445771,
EPI_ISL_17445785, EPI_ISL_17445847, EPI_ISL_17446126,
EPI_ISL_17447257, EPI_ISL_17462440, EPI_ISL_17467082,
EPI_ISL_17467105, EPI_ISL_17467185, EPI_ISL_17467199,
EPI_ISL_17473012, EPI_ISL_17473529, EPI_ISL_17473670,
EPI_ISL_17474537, EPI_ISL_17482265, EPI_ISL_17482283,
EPI_ISL_17484817, EPI_ISL_17484867, EPI_ISL_17486679,
EPI_ISL_17486716, EPI_ISL_17495633, EPI_ISL_17495869-17495906,
EPI_ISL_17495908-17495909, EPI_ISL_17495912-17495917, EPI_ISL_17495919-17495924,
EPI_ISL_17496297-17496301, EPI_ISL_17496373-17496379, EPI_ISL_17496459,
EPI_ISL_17497317, EPI_ISL_17497329, EPI_ISL_17499488,
EPI_ISL_17500421, EPI_ISL_17500661, EPI_ISL_17500694,
EPI_ISL_17500699, EPI_ISL_17503906, EPI_ISL_17503928,
EPI_ISL_17504051, EPI_ISL_17507952, EPI_ISL_17511491,
EPI_ISL_17516148, EPI_ISL_17517488-17517490, EPI_ISL_17517492,
EPI_ISL_17519302, EPI_ISL_17523174, EPI_ISL_17526363,
EPI_ISL_17526854, EPI_ISL_17527378, EPI_ISL_17527467,
EPI_ISL_17527505, EPI_ISL_17527914, EPI_ISL_17527919,
EPI_ISL_17528621, EPI_ISL_17529062, EPI_ISL_17529216,
EPI_ISL_17530262, EPI_ISL_17530334, EPI_ISL_17530340,
EPI_ISL_17530404, EPI_ISL_17530407, EPI_ISL_17530414,
EPI_ISL_17530469, EPI_ISL_17530471-17530472, EPI_ISL_17530487,
EPI_ISL_17537870, EPI_ISL_17539477, EPI_ISL_17539509,
EPI_ISL_17539511-17539512, EPI_ISL_17539517, EPI_ISL_17539529,
EPI_ISL_17539537, EPI_ISL_17539543, EPI_ISL_17539563,
EPI_ISL_17539570, EPI_ISL_17539597-17539598, EPI_ISL_17539609,
EPI_ISL_17539618, EPI_ISL_17539621, EPI_ISL_17539627,
EPI_ISL_17539631, EPI_ISL_17539639, EPI_ISL_17539644,
EPI_ISL_17539668, EPI_ISL_17539685, EPI_ISL_17539698,
EPI_ISL_17539755, EPI_ISL_17539759-17539760, EPI_ISL_17539776,
EPI_ISL_17539780, EPI_ISL_17539809, EPI_ISL_17539826-17539827,
EPI_ISL_17539838, EPI_ISL_17539840, EPI_ISL_17539845,
EPI_ISL_17539847, EPI_ISL_17539858, EPI_ISL_17539866,
EPI_ISL_17539870, EPI_ISL_17539872, EPI_ISL_17539885,
EPI_ISL_17539888, EPI_ISL_17539913, EPI_ISL_17539922,
EPI_ISL_17539924, EPI_ISL_17539927, EPI_ISL_17539929,
EPI_ISL_17539933-17539934, EPI_ISL_17539947, EPI_ISL_17540123,
EPI_ISL_17540215, EPI_ISL_17541900, EPI_ISL_17541954,
EPI_ISL_17542398, EPI_ISL_17542474, EPI_ISL_17543281,
EPI_ISL_17543839, EPI_ISL_17544449, EPI_ISL_17547535,
EPI_ISL_17548494, EPI_ISL_17548499, EPI_ISL_17548799,
EPI_ISL_17549847, EPI_ISL_17550757, EPI_ISL_17550826,
EPI_ISL_17551988, EPI_ISL_17554891, EPI_ISL_17556596-17556598,
EPI_ISL_17556600-17556601, EPI_ISL_17557967, EPI_ISL_17558186,
EPI_ISL_17558188, EPI_ISL_17558474-17558477, EPI_ISL_17561634,
EPI_ISL_17562113, EPI_ISL_17562260, EPI_ISL_17562593,
EPI_ISL_17562634, EPI_ISL_17563950, EPI_ISL_17565526,
EPI_ISL_17565546, EPI_ISL_17565699, EPI_ISL_17582000,
EPI_ISL_17582317, EPI_ISL_17582982, EPI_ISL_17584533,
EPI_ISL_17586944, EPI_ISL_17587161, EPI_ISL_17587474,
EPI_ISL_17588209, EPI_ISL_17589554, EPI_ISL_17590129,
EPI_ISL_17590150, EPI_ISL_17590252, EPI_ISL_17591414,
EPI_ISL_17591510, EPI_ISL_17591721, EPI_ISL_17592341,
EPI_ISL_17595211, EPI_ISL_17595756, EPI_ISL_17595833,
EPI_ISL_17596092, EPI_ISL_17596101, EPI_ISL_17596105,
EPI_ISL_17596109, EPI_ISL_17596111, EPI_ISL_17596132,
EPI_ISL_17596161, EPI_ISL_17596171, EPI_ISL_17596175,
EPI_ISL_17596187, EPI_ISL_17596193-17596194, EPI_ISL_17596215,
EPI_ISL_17596219, EPI_ISL_17596236-17596237, EPI_ISL_17596239,
EPI_ISL_17596248, EPI_ISL_17596253, EPI_ISL_17596267,
EPI_ISL_17596270, EPI_ISL_17596274, EPI_ISL_17596291,
EPI_ISL_17596314, EPI_ISL_17596320, EPI_ISL_17596328,
EPI_ISL_17596333, EPI_ISL_17596336-17596337, EPI_ISL_17596356-17596358,
EPI_ISL_17596375-17596377, EPI_ISL_17596387, EPI_ISL_17596405,
EPI_ISL_17596413, EPI_ISL_17596421, EPI_ISL_17596431,
EPI_ISL_17596433, EPI_ISL_17596452, EPI_ISL_17596455-17596456,
EPI_ISL_17596465, EPI_ISL_17596472-17596473, EPI_ISL_17596483-17596486,
EPI_ISL_17596491, EPI_ISL_17596703, EPI_ISL_17597645,
EPI_ISL_17598729, EPI_ISL_17599058, EPI_ISL_17599749,
EPI_ISL_17599753, EPI_ISL_17599917, EPI_ISL_17599946,
EPI_ISL_17600024, EPI_ISL_17600028, EPI_ISL_17601896,
EPI_ISL_17602466, EPI_ISL_17604582, EPI_ISL_17605346,
EPI_ISL_17605951, EPI_ISL_17606332, EPI_ISL_17606488,
EPI_ISL_17606915, EPI_ISL_17607454, EPI_ISL_17611292,
EPI_ISL_17611327, EPI_ISL_17612769, EPI_ISL_17613530,
EPI_ISL_17613734, EPI_ISL_17614716, EPI_ISL_17614813,
EPI_ISL_17615871, EPI_ISL_17618254, EPI_ISL_17618338,
EPI_ISL_17618345, EPI_ISL_17618392, EPI_ISL_17618424,
EPI_ISL_17618468, EPI_ISL_17618648, EPI_ISL_17618704,
EPI_ISL_17620686, EPI_ISL_17621383, EPI_ISL_17623654,
EPI_ISL_17623661, EPI_ISL_17623684, EPI_ISL_17624069,
EPI_ISL_17624071, EPI_ISL_17625669, EPI_ISL_17625692,
EPI_ISL_17625698, EPI_ISL_17625700, EPI_ISL_17626932,
EPI_ISL_17627090, EPI_ISL_17627840, EPI_ISL_17629513,
EPI_ISL_17629600, EPI_ISL_17629708, EPI_ISL_17630672,
EPI_ISL_17630814, EPI_ISL_17630826, EPI_ISL_17631120,
EPI_ISL_17631313, EPI_ISL_17631315, EPI_ISL_17631321,
EPI_ISL_17631323, EPI_ISL_17631332, EPI_ISL_17631334,
EPI_ISL_17631345, EPI_ISL_17631352, EPI_ISL_17631359,
EPI_ISL_17631361, EPI_ISL_17631363, EPI_ISL_17631366,
EPI_ISL_17631369, EPI_ISL_17631383, EPI_ISL_17631394,
EPI_ISL_17631399, EPI_ISL_17631402-17631403, EPI_ISL_17631416,
EPI_ISL_17631420, EPI_ISL_17631447, EPI_ISL_17631454,
EPI_ISL_17631456, EPI_ISL_17631460, EPI_ISL_17631467,
EPI_ISL_17631473-17631474, EPI_ISL_17631476, EPI_ISL_17631482-17631483,
EPI_ISL_17631486, EPI_ISL_17631490-17631491, EPI_ISL_17631494,
EPI_ISL_17631505, EPI_ISL_17631539, EPI_ISL_17631549-17631551,
EPI_ISL_17631606, EPI_ISL_17631613, EPI_ISL_17633705,
EPI_ISL_17633749, EPI_ISL_17634263, EPI_ISL_17635192,
EPI_ISL_17635200, EPI_ISL_17635203, EPI_ISL_17635217,
EPI_ISL_17637614, EPI_ISL_17637690, EPI_ISL_17637726,
EPI_ISL_17642051, EPI_ISL_17642405, EPI_ISL_17642915,
EPI_ISL_17642919, EPI_ISL_17643039, EPI_ISL_17644150,
EPI_ISL_17644658, EPI_ISL_17645120, EPI_ISL_17645124,
EPI_ISL_17645726, EPI_ISL_17645730, EPI_ISL_17645755,
EPI_ISL_17645782, EPI_ISL_17646747, EPI_ISL_17647041,
EPI_ISL_17647173, EPI_ISL_17647300, EPI_ISL_17647358,
EPI_ISL_17647735, EPI_ISL_17648029, EPI_ISL_17648603,
EPI_ISL_17649064, EPI_ISL_17649095, EPI_ISL_17649143,
EPI_ISL_17649163, EPI_ISL_17652027, EPI_ISL_17652300,
EPI_ISL_17652325, EPI_ISL_17653578, EPI_ISL_17653582,
EPI_ISL_17653638, EPI_ISL_17655019, EPI_ISL_17655378,
EPI_ISL_17655875, EPI_ISL_17656588, EPI_ISL_17656655,
EPI_ISL_17656763, EPI_ISL_17656857, EPI_ISL_17657002,
EPI_ISL_17657056, EPI_ISL_17657239, EPI_ISL_17657241,
EPI_ISL_17658681, EPI_ISL_17659465-17659466, EPI_ISL_17659513,
EPI_ISL_17659539, EPI_ISL_17659573, EPI_ISL_17659698,
EPI_ISL_17659700, EPI_ISL_17659708, EPI_ISL_17659712,
EPI_ISL_17659766, EPI_ISL_17659861, EPI_ISL_17659918,
EPI_ISL_17660952, EPI_ISL_17660962, EPI_ISL_17661214,
EPI_ISL_17661743, EPI_ISL_17661745, EPI_ISL_17662750,
EPI_ISL_17662907, EPI_ISL_17662917, EPI_ISL_17663262,
EPI_ISL_17664067, EPI_ISL_17666324, EPI_ISL_17666591,
EPI_ISL_17666625, EPI_ISL_17666710, EPI_ISL_17667480,
EPI_ISL_17669074, EPI_ISL_17669411, EPI_ISL_17669423,
EPI_ISL_17669870, EPI_ISL_17670090, EPI_ISL_17670094,
EPI_ISL_17670102, EPI_ISL_17670113, EPI_ISL_17670118,
EPI_ISL_17670121, EPI_ISL_17670149, EPI_ISL_17670151-17670152,
EPI_ISL_17670154-17670155, EPI_ISL_17670162, EPI_ISL_17670168,
EPI_ISL_17670172-17670173, EPI_ISL_17670176, EPI_ISL_17670179,
EPI_ISL_17670187-17670188, EPI_ISL_17670197, EPI_ISL_17670207,
EPI_ISL_17670213, EPI_ISL_17670217, EPI_ISL_17670230,
EPI_ISL_17670234, EPI_ISL_17670242, EPI_ISL_17670247,
EPI_ISL_17670252-17670253, EPI_ISL_17670260, EPI_ISL_17670268,
EPI_ISL_17670270-17670272, EPI_ISL_17670279-17670281, EPI_ISL_17670284,
EPI_ISL_17670286, EPI_ISL_17670292, EPI_ISL_17670294,
EPI_ISL_17670313, EPI_ISL_17670318, EPI_ISL_17670321,
EPI_ISL_17670332, EPI_ISL_17670350, EPI_ISL_17670378,
EPI_ISL_17670385, EPI_ISL_17670391, EPI_ISL_17670415,
EPI_ISL_17670421, EPI_ISL_17670429, EPI_ISL_17670445,
EPI_ISL_17670449, EPI_ISL_17670458, EPI_ISL_17670472,
EPI_ISL_17670480, EPI_ISL_17670484, EPI_ISL_17670496,
EPI_ISL_17670507, EPI_ISL_17670512, EPI_ISL_17670526,
EPI_ISL_17670528, EPI_ISL_17670538, EPI_ISL_17670544,
EPI_ISL_17670554, EPI_ISL_17672444-17672446, EPI_ISL_17672491,
EPI_ISL_17672494, EPI_ISL_17674459, EPI_ISL_17677552,
EPI_ISL_17677724, EPI_ISL_17678554, EPI_ISL_17678716,
EPI_ISL_17678770, EPI_ISL_17680102, EPI_ISL_17681170,
EPI_ISL_17681537, EPI_ISL_17682408-17682409, EPI_ISL_17682416,
EPI_ISL_17682420, EPI_ISL_17682424, EPI_ISL_17682438,
EPI_ISL_17682440, EPI_ISL_17682445, EPI_ISL_17682447,
EPI_ISL_17682454, EPI_ISL_17682462, EPI_ISL_17682471,
EPI_ISL_17682479, EPI_ISL_17682482, EPI_ISL_17682484,
EPI_ISL_17682491-17682492, EPI_ISL_17682509, EPI_ISL_17682518,
EPI_ISL_17682524, EPI_ISL_17682527, EPI_ISL_17682530,
EPI_ISL_17682548-17682549, EPI_ISL_17682556, EPI_ISL_17682558,
EPI_ISL_17682561, EPI_ISL_17682571, EPI_ISL_17682575,
EPI_ISL_17682580, EPI_ISL_17682582, EPI_ISL_17682586,
EPI_ISL_17682597, EPI_ISL_17682606-17682607, EPI_ISL_17682614,
EPI_ISL_17682617, EPI_ISL_17682625-17682627, EPI_ISL_17682631,
EPI_ISL_17682641, EPI_ISL_17682643, EPI_ISL_17682650,
EPI_ISL_17682652, EPI_ISL_17682666, EPI_ISL_17682668,
EPI_ISL_17682979, EPI_ISL_17683063, EPI_ISL_17683100,
EPI_ISL_17683180, EPI_ISL_17683200, EPI_ISL_17683437,
EPI_ISL_17683449, EPI_ISL_17683492, EPI_ISL_17683608,
EPI_ISL_17683692, EPI_ISL_17683716, EPI_ISL_17684228,
EPI_ISL_17684231, EPI_ISL_17684715, EPI_ISL_17685648,
EPI_ISL_17685693, EPI_ISL_17685803, EPI_ISL_17686302,
EPI_ISL_17686320, EPI_ISL_17686322-17686323, EPI_ISL_17686331,
EPI_ISL_17686344, EPI_ISL_17686774, EPI_ISL_17686776,
EPI_ISL_17686787, EPI_ISL_17686790, EPI_ISL_17686797,
EPI_ISL_17686799, EPI_ISL_17686803, EPI_ISL_17687064,
EPI_ISL_17688648, EPI_ISL_17689428, EPI_ISL_17689521,
EPI_ISL_17689788, EPI_ISL_17690518, EPI_ISL_17690893,
EPI_ISL_17691031, EPI_ISL_17691214, EPI_ISL_17691654,
EPI_ISL_17691701, EPI_ISL_17691710, EPI_ISL_17691763,
EPI_ISL_17691851, EPI_ISL_17691855, EPI_ISL_17692057,
EPI_ISL_17692071, EPI_ISL_17692142, EPI_ISL_17692167,
EPI_ISL_17692600, EPI_ISL_17692913, EPI_ISL_17692920,
EPI_ISL_17692975, EPI_ISL_17694072, EPI_ISL_17694801,
EPI_ISL_17694804, EPI_ISL_17694808, EPI_ISL_17694815,
EPI_ISL_17694818, EPI_ISL_17694825, EPI_ISL_17694839,
EPI_ISL_17694843, EPI_ISL_17694864, EPI_ISL_17694903,
EPI_ISL_17694907, EPI_ISL_17694912, EPI_ISL_17694923-17694924,
EPI_ISL_17694934, EPI_ISL_17694949, EPI_ISL_17694975,
EPI_ISL_17694977, EPI_ISL_17694996, EPI_ISL_17695001,
EPI_ISL_17695005, EPI_ISL_17695013, EPI_ISL_17695026,
EPI_ISL_17695033, EPI_ISL_17695036, EPI_ISL_17695047,
EPI_ISL_17695056, EPI_ISL_17695077-17695078, EPI_ISL_17695081-17695082,
EPI_ISL_17695084, EPI_ISL_17695086, EPI_ISL_17695736,
EPI_ISL_17695763, EPI_ISL_17696430, EPI_ISL_17696461,
EPI_ISL_17696627, EPI_ISL_17696655, EPI_ISL_17696688,
EPI_ISL_17696690, EPI_ISL_17699198, EPI_ISL_17699254,
EPI_ISL_17699266, EPI_ISL_17700427, EPI_ISL_17703834,
EPI_ISL_17703936, EPI_ISL_17704220, EPI_ISL_17704299,
EPI_ISL_17704791, EPI_ISL_17704800, EPI_ISL_17705030,
EPI_ISL_17706781, EPI_ISL_17706814, EPI_ISL_17706950,
EPI_ISL_17707754, EPI_ISL_17708088, EPI_ISL_17709233,
EPI_ISL_17711258, EPI_ISL_17715140, EPI_ISL_17715161,
EPI_ISL_17715188, EPI_ISL_17715204, EPI_ISL_17715939-17715940,
EPI_ISL_17715945, EPI_ISL_17715949, EPI_ISL_17716345,
EPI_ISL_17716650, EPI_ISL_17716732, EPI_ISL_17717559,
EPI_ISL_17718594, EPI_ISL_17718609, EPI_ISL_17718663,
EPI_ISL_17718899, EPI_ISL_17718932, EPI_ISL_17718961,
EPI_ISL_17719015, EPI_ISL_17719379, EPI_ISL_17720466,
EPI_ISL_17720501, EPI_ISL_17720761, EPI_ISL_17720763,
EPI_ISL_17721646, EPI_ISL_17721892, EPI_ISL_17722526,
EPI_ISL_17722993, EPI_ISL_17723150, EPI_ISL_17723217,
EPI_ISL_17723262, EPI_ISL_17723336, EPI_ISL_17723417,
EPI_ISL_17723517, EPI_ISL_17723596-17723597, EPI_ISL_17723668,
EPI_ISL_17723797-17723798, EPI_ISL_17723875, EPI_ISL_17723923,
EPI_ISL_17723983, EPI_ISL_17724092, EPI_ISL_17724144,
EPI_ISL_17724146, EPI_ISL_17724589-17724603, EPI_ISL_17724605-17724621,
EPI_ISL_17724623-17724662, EPI_ISL_17724664-17724682, EPI_ISL_17725142,
EPI_ISL_17725514, EPI_ISL_17726279, EPI_ISL_17726289,
EPI_ISL_17727687, EPI_ISL_17729548, EPI_ISL_17729567,
EPI_ISL_17729627, EPI_ISL_17729735, EPI_ISL_17729746-17729750,
EPI_ISL_17730407, EPI_ISL_17730539, EPI_ISL_17730559,
EPI_ISL_17730565, EPI_ISL_17730600, EPI_ISL_17730625,
EPI_ISL_17730729, EPI_ISL_17730737, EPI_ISL_17730791,
EPI_ISL_17730874, EPI_ISL_17730943, EPI_ISL_17730954,
EPI_ISL_17730998, EPI_ISL_17731135, EPI_ISL_17731216-17731217,
EPI_ISL_17731824, EPI_ISL_17731897, EPI_ISL_17735468,
EPI_ISL_17736453, EPI_ISL_17736492, EPI_ISL_17738841,
EPI_ISL_17738947, EPI_ISL_17739037, EPI_ISL_17739039,
EPI_ISL_17739090, EPI_ISL_17739159, EPI_ISL_17739329,
EPI_ISL_17739732, EPI_ISL_17740183, EPI_ISL_17740693,
EPI_ISL_17740904, EPI_ISL_17741142, EPI_ISL_17741150,
EPI_ISL_17741302, EPI_ISL_17741403, EPI_ISL_17741524,
EPI_ISL_17741641, EPI_ISL_17741766, EPI_ISL_17741852,
EPI_ISL_17742105, EPI_ISL_17742206, EPI_ISL_17742315,
EPI_ISL_17742667, EPI_ISL_17742995, EPI_ISL_17743103,
EPI_ISL_17743160, EPI_ISL_17743324, EPI_ISL_17743519,
EPI_ISL_17743566, EPI_ISL_17743619, EPI_ISL_17743631,
EPI_ISL_17743775, EPI_ISL_17743782, EPI_ISL_17744420,
EPI_ISL_17744557, EPI_ISL_17761394, EPI_ISL_17761398,
EPI_ISL_17762298, EPI_ISL_17762579, EPI_ISL_17762786,
EPI_ISL_17762870, EPI_ISL_17763193, EPI_ISL_17763274,
EPI_ISL_17763278, EPI_ISL_17763379-17763381, EPI_ISL_17763389,
EPI_ISL_17764545, EPI_ISL_17765446, EPI_ISL_17765672,
EPI_ISL_17765711, EPI_ISL_17765737, EPI_ISL_17766086,
EPI_ISL_17766841, EPI_ISL_17766856, EPI_ISL_17767921,
EPI_ISL_17767994, EPI_ISL_17768281, EPI_ISL_17768378,
EPI_ISL_17768744, EPI_ISL_17768981, EPI_ISL_17769293,
EPI_ISL_17769512, EPI_ISL_17769621-17769623, EPI_ISL_17770152,
EPI_ISL_17771950, EPI_ISL_17773328, EPI_ISL_17773371,
EPI_ISL_17773396, EPI_ISL_17773429, EPI_ISL_17774005,
EPI_ISL_17774426, EPI_ISL_17774507, EPI_ISL_17774533,
EPI_ISL_17775018, EPI_ISL_17775022, EPI_ISL_17775886,
EPI_ISL_17775982, EPI_ISL_17776180, EPI_ISL_17776703,
EPI_ISL_17778284, EPI_ISL_17778376, EPI_ISL_17778444,
EPI_ISL_17778838, EPI_ISL_17778937, EPI_ISL_17779106,
EPI_ISL_17779235, EPI_ISL_17779260, EPI_ISL_17779290,
EPI_ISL_17779368, EPI_ISL_17779391, EPI_ISL_17779422,
EPI_ISL_17779795, EPI_ISL_17779862, EPI_ISL_17780170,
EPI_ISL_17781382, EPI_ISL_17781398-17781399, EPI_ISL_17781691,
EPI_ISL_17781757, EPI_ISL_17782259, EPI_ISL_17782357,
EPI_ISL_17782673, EPI_ISL_17782842, EPI_ISL_17782942,
EPI_ISL_17783006, EPI_ISL_17784000, EPI_ISL_17784367-17784368,
EPI_ISL_17784419, EPI_ISL_17785849, EPI_ISL_17785987,
EPI_ISL_17786202, EPI_ISL_17786254, EPI_ISL_17786283,
EPI_ISL_17786496, EPI_ISL_17788452, EPI_ISL_17788841,
EPI_ISL_17788851, EPI_ISL_17788868, EPI_ISL_17788961,
EPI_ISL_17789045, EPI_ISL_17789065, EPI_ISL_17789174,
EPI_ISL_17789240, EPI_ISL_17790127, EPI_ISL_17790131,
EPI_ISL_17790325-17790339, EPI_ISL_17790341-17790362, EPI_ISL_17790509,
EPI_ISL_17790513, EPI_ISL_17790520, EPI_ISL_17790527,
EPI_ISL_17790533-17790534, EPI_ISL_17790553, EPI_ISL_17790558,
EPI_ISL_17790586, EPI_ISL_17790613, EPI_ISL_17790627,
EPI_ISL_17790641-17790642, EPI_ISL_17790644, EPI_ISL_17790649,
EPI_ISL_17790653, EPI_ISL_17790671, EPI_ISL_17790674-17790675,
EPI_ISL_17790681, EPI_ISL_17790684, EPI_ISL_17790691,
EPI_ISL_17790693, EPI_ISL_17790698, EPI_ISL_17790708,
EPI_ISL_17790712, EPI_ISL_17790720, EPI_ISL_17790728,
EPI_ISL_17790730, EPI_ISL_17790738, EPI_ISL_17790744,
EPI_ISL_17790747-17790748, EPI_ISL_17790750, EPI_ISL_17790752,
EPI_ISL_17790764, EPI_ISL_17790776, EPI_ISL_17790781,
EPI_ISL_17790794, EPI_ISL_17790803, EPI_ISL_17790806-17790807,
EPI_ISL_17790811, EPI_ISL_17790819, EPI_ISL_17790830,
EPI_ISL_17790833, EPI_ISL_17790839, EPI_ISL_17790847,
EPI_ISL_17790880, EPI_ISL_17790884-17790885, EPI_ISL_17790918,
EPI_ISL_17791004, EPI_ISL_17791063-17791064, EPI_ISL_17791608,
EPI_ISL_17791750, EPI_ISL_17791933, EPI_ISL_17791959,
EPI_ISL_17791974, EPI_ISL_17791983, EPI_ISL_17792005,
EPI_ISL_17792017, EPI_ISL_17792026, EPI_ISL_17792040,
EPI_ISL_17792042, EPI_ISL_17792047, EPI_ISL_17792459,
EPI_ISL_17792463, EPI_ISL_17793391, EPI_ISL_17793459,
EPI_ISL_17795279, EPI_ISL_17795925, EPI_ISL_17795948-17795949,
EPI_ISL_17796285, EPI_ISL_17796738, EPI_ISL_17798118-17798119,
EPI_ISL_17798860, EPI_ISL_17798925, EPI_ISL_17801775,
EPI_ISL_17801956, EPI_ISL_17802066, EPI_ISL_17802070,
EPI_ISL_17802139, EPI_ISL_17802150, EPI_ISL_17802435,
EPI_ISL_17803050, EPI_ISL_17803082, EPI_ISL_17803134,
EPI_ISL_17803163, EPI_ISL_17803552, EPI_ISL_17803563,
EPI_ISL_17803581, EPI_ISL_17803735, EPI_ISL_17803853,
EPI_ISL_17803864, EPI_ISL_17803880, EPI_ISL_17803945,
EPI_ISL_17803958, EPI_ISL_17804066, EPI_ISL_17804073,
EPI_ISL_17804093, EPI_ISL_17804105-17804106, EPI_ISL_17806747,
EPI_ISL_17806849, EPI_ISL_17806938, EPI_ISL_17806984,
EPI_ISL_17807043, EPI_ISL_17807425, EPI_ISL_17807470,
EPI_ISL_17807490, EPI_ISL_17807687, EPI_ISL_17807717,
EPI_ISL_17807805, EPI_ISL_17807935, EPI_ISL_17808040,
EPI_ISL_17808247, EPI_ISL_17808558, EPI_ISL_17809057,
EPI_ISL_17809634, EPI_ISL_17809820, EPI_ISL_17810214,
EPI_ISL_17810368, EPI_ISL_17810992, EPI_ISL_17811000,
EPI_ISL_17811652, EPI_ISL_17811846, EPI_ISL_17812661,
EPI_ISL_17812772, EPI_ISL_17813208, EPI_ISL_17813448,
EPI_ISL_17813643, EPI_ISL_17815258, EPI_ISL_17815608,
EPI_ISL_17815610, EPI_ISL_17815618, EPI_ISL_17815640-17815641,
EPI_ISL_17815646, EPI_ISL_17815652-17815653, EPI_ISL_17815656,
EPI_ISL_17815667, EPI_ISL_17815676, EPI_ISL_17815679-17815681,
EPI_ISL_17815684, EPI_ISL_17815691, EPI_ISL_17815706,
EPI_ISL_17815715, EPI_ISL_17815732, EPI_ISL_17815751,
EPI_ISL_17815764, EPI_ISL_17815767, EPI_ISL_17815788,
EPI_ISL_17815805, EPI_ISL_17815815, EPI_ISL_17815820,
EPI_ISL_17815824-17815825, EPI_ISL_17815832, EPI_ISL_17815849,
EPI_ISL_17815853, EPI_ISL_17815855-17815858, EPI_ISL_17815863,
EPI_ISL_17815902, EPI_ISL_17815932, EPI_ISL_17815938,
EPI_ISL_17815942, EPI_ISL_17815949, EPI_ISL_17815962,
EPI_ISL_17815973-17815975, EPI_ISL_17815980, EPI_ISL_17815986,
EPI_ISL_17815990, EPI_ISL_17815992, EPI_ISL_17815994,
EPI_ISL_17816010-17816011, EPI_ISL_17816282, EPI_ISL_17816284,
EPI_ISL_17816288, EPI_ISL_17816294, EPI_ISL_17816412,
EPI_ISL_17816418, EPI_ISL_17816493, EPI_ISL_17816507,
EPI_ISL_17816663, EPI_ISL_17816693, EPI_ISL_17816746,
EPI_ISL_17816761, EPI_ISL_17816799, EPI_ISL_17816813,
EPI_ISL_17817252, EPI_ISL_17817412, EPI_ISL_17817434,
EPI_ISL_17818988, EPI_ISL_17819782, EPI_ISL_17819790,
EPI_ISL_17819808, EPI_ISL_17819819, EPI_ISL_17819822,
EPI_ISL_17819836, EPI_ISL_17819886, EPI_ISL_17820740,
EPI_ISL_17820742, EPI_ISL_17820799
tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_350f2_31bd20.json?f_userOrOld=uploaded%20sample
When I was looking at my collection 174 https://cov-spectrum.org/collections/174, one thing I noticed is that there exist some large mutations without clear "belongings". Most of those belong to reversions, low quality issues or amplicon problems, yet G24193A seem immune of these problems but still major, and cov-spectrum says 95% of those belong to XBB.2.3.2. I made an inquiry and found out that it is true. Not only XBB.2.3.2 constitute most of this mutation, but XBB.2.3.2 with the mutation constitute most of XBB.2.3.2 itself.
XBB.2.3.2 is itself a major variant with decent growth, and if this mutation, even seemingly silent, could demonstrate both numerical and growth advantage over its peers, then it is something we should figure out.
![038E6BF0-1B0D-453F-85FC-2EE8F8DD8135](https://github.com/cov-lineages/pango-designation/assets/131021067/6faa6a49-b6eb-4b41-a024-0271dc6d64d5)
@corneliusroemer

**Comment by FedeGueli** [comment]
i have just 1800 XBB.2.3.2 when a branch is so big and just defined by just  a nuc mutation i dont think it is very useful to designate it, XBB.2.3.2 is already mostly this lineeage.

**Comment by krosa1910** [comment]
> i have just 1800 XBB.2.3.2 when a branch is so big and just defined by just a nuc mutation i dont think it is very useful to designate it, XBB.2.3.2 is already mostly this lineeage.

Then I would suggest change the definition of XBB.2.3.2 to include two silent mutations (G24193A and C26228A). And there does exist a clear sub-category under it, mentioned in #1890 as these two silent mutation+orf1a:T2977I which itself reached around half of XBB.2.3.2 to become the .1 member of the family
