### ISSUE TITLE
XBB.1.16.2 with S:L84I, ORF1ab:A4068S in China (88 seq)

### ISSUE THREAD

**Issue by BorisUitham** [cov-lineages/pango-designation#2066]
Earliest sequence: 2023-04-25
Recent sequence: 2023-06-14
GISAID query: G12467T, C21812A

While S:L84I has popped up throughout the pandemic especially in ba.5 lineages, orf1ab:a4068s (NSP8_A126S EDITED) is very recently getting traction, mostly in xbb.1.5 so far but also bq* and ch*.

There is also some sequences with s:f456l found by fedegueli, making yet another entrance of the 456l 478r combination:
https://github.com/sars-cov-2-variants/lineage-proposals/issues/238

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=G12467T%2CC21812A&

![Screenshot_20230622_214618_Chrome](https://github.com/cov-lineages/pango-designation/assets/119106095/e51cbaac-c1fd-4340-88f3-f9ff086e8f89)
![Screenshot_20230622_214641_Chrome](https://github.com/cov-lineages/pango-designation/assets/119106095/df71745f-edbd-499c-90fd-22cdc030f80d)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_95cb_4a4bb0.json?c=gt-ORF1ab_4068&label=id:node_6573760&showBranchLabels=all

**Comment by FedeGueli** [comment]
I would like to highlight @corneliusroemer and @InfrPopGen that we did monitor it for some weeks and even if it is not the fastest apparently week after week it went on accumulating sequence in China and being exported outside China.

**Comment by FedeGueli** [comment]
93 seqs as today Last samples coming from: Gansu Shanghai South Korea and Sweden
