### ISSUE TITLE
FE.1.1.1+Orf8:A55V+S:V622I in Puerto Rico and Canada (173 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2067]
from  https://github.com/sars-cov-2-variants/lineage-proposals/issues/155
FE.1.1.1+C15180T+T9445C+C28057T(orf8:A55V)+G23426A(S:V622L)

GISAID query: G23426A,C28057T,T23018C
No of seqs: 110( Puerto Rico 75 Canada 31 USA-FL 1 USA-OH 2 USA-TX 1)
First:EPI_ISL_17537601 2023-2-12, Canada
Latest:EPI_ISL_17831578,2023-5-30,Puerto Rico

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_f9e1_7036e0.json)

<img width="1408" alt="Screenshot 2023-06-24 at 23 30 25" src="https://github.com/cov-lineages/pango-designation/assets/10445944/0bb633d7-86cd-4711-9be1-986ac19374b5">

**Comment by aviczhl2** [comment]
131, Germany

**Comment by arodzh-sudo** [comment]
An update on this, now 169 seqs as of 07/10/2023.
Latest: EPI_ISL_17851506, EPI_ISL_17950296, EPI_ISL_17952483 from NY and Massachusetts 2023-06-17

A possible additional sublineage with ORF1a:V710I/G2393A (NSP2:V530I) with 97 seqs all from Puerto Rico.

[https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1c102_d96550.json](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1c102_d96550.json)

![Screenshot 2023-07-11 at 13-51-51 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ subtreeAuspice1_genome_1c102_d96550 json](https://github.com/cov-lineages/pango-designation/assets/54407020/b1f9bc4f-36f1-4c98-918f-748fd6f77e02)

**Comment by aviczhl2** [comment]
> now 169 seqs as of 07/10/2023

I only find 135 on GISAID. Are some of them masked on G23426A,C28057T or T9445C? 

Note that some seqs are uploaded both to GISAID and other platforms like GenBank. On usher you need to be careful that non-GISAID seqs may have a GISAID back-up.

**Comment by arodzh-sudo** [comment]
The number of sequences (169) is based on the cov-spectrum query FE.1.1.1* (Nextclade) + ORF8:A55V, S:V622I (World) using GISAID as source. Some of these sequences do not exhibit T9445C and C15180T or do not have sequencing coverage on those regions.

> I only find 135 on GISAID. Are some of them masked on G23426A,C28057T or T9445C? Do you have an updated query?

Based on this and using only G23426A,C28057T as the Nucl Mutations query the total of seqs are 173 (excluding two B.1.1 seqs from 2021) which all exhibit the main mutations Orf8:A55V+S:V622I.

**Comment by aviczhl2** [comment]
It is designated as HE.1
