### ISSUE TITLE
FL.4 with S:D1259Y and N:T334I (292 seqs, 11 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2074]
from https://github.com/sars-cov-2-variants/lineage-proposals/issues/140
FL.4+C2416T+C29274T(N:T334)+G25337T(S:D1259Y)
GISAID query: C2416T,C29274T,G25337T

Usher classifies it on an FL.2+orf1b:V1092F(FL.4 defining)+ A4579T(reversion of FL.2 defining) branch, which is actually FL.4

No. of seqs: 175(Canada 1 UK 1 Japan 6 Laos 1 New Zealand 1 Singapore 4(2 from China), South Korea 1 Thailand 1 USA 10 China 149)
171 on GISAID, and also C_AA023179.1, C_AA016907.1, C_AA013770.1, C_AA024637.1 on GenBase

First seq: EPI_ISL_17433565, 2023-3-13, Hong Kong
Latest: EPI_ISL_17850212, 2023-6-15, Fujian
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a812_ba00e0.json)
![屏幕截图 2023-06-27 215615](https://github.com/cov-lineages/pango-designation/assets/10445944/e1887be0-0fb7-4df5-8db0-f547b543601e)

**Comment by Over-There-Is** [comment]
C_AA023179.1=EPI_ISL_17794707 T2416Crev
C_AA016907.1=EPI_ISL_17697604 C2416N
C_AA013770.1=EPI_ISL_17632946 searchable with query C2416T, C29274T, G25337T
C_AA024637.1 is not uploaded to gisaid

**Comment by Over-There-Is** [comment]
182 seq on GISAID with C2416T, C29274T, G25337T now, including the dropped-out sequences and genbase sequences it will be 185.

**Comment by aviczhl2** [comment]
219, Australia.

**Comment by aviczhl2** [comment]
FL.4.11

**Comment by Over-There-Is** [comment]
It seems all FL.4.11 should have C3773T(Orf1a:R1170C), and a few sequences dropped it out.

**Comment by aviczhl2** [comment]
> It seems all FL.4.11 should have C3773T(Orf1a:R1170C), and a few sequences dropped it out.

Can you confirm that all dropout seqs have that pos masked?

**Comment by Over-There-Is** [comment]
Guangdong/GDCDC_GZ_0124/2023|EPI_ISL_17584613|2023-04-14 and Fujian/FCDC-QZ05S067/2023|EPI_ISL_17729827|2023-05-15 share T26903C with 88 sequences with C3773T.
Yunnan/YNCDC-1483/2023|EPI_ISL_17966375|2023-06-23 and Jiangxi/JXJDZ-018/2023|EPI_ISL_17794481|2023-04-25 share A27372T with 73 sequence, then Yunnan/YNCDC-1483/2023|EPI_ISL_17966375|2023-06-23 shares A22029T with 30 sequences and C1441T with 19 sequences additionally, and Jiangxi/JXJDZ-018/2023|EPI_ISL_17794481|2023-04-25 is potential recombined or contaminated with FR.1*.
USA/NY-URMC-N3S1G116-1/2023|EPI_ISL_17695644|2023-05-06 shares C25614T with 16 sequences.
Guangdong/GDCDC_GZ_0372/2023|EPI_ISL_17698245|2023-05-09 shares T8835C and T15521A with 2 sequences, then additionally shares C25803T with 1 sequence.
I did not find sequences having same extra mutations with Hubei/HCDC-WH1229/2023|EPI_ISL_17645498|2023-05-04, but it has T11956Crev and A23854Crev. So, its T3773Crev is probably artefact too. And Guangdong/GDCDC_GZ_0267/2023|EPI_ISL_17698237|2023-04-26(G26577Crev) probably has C3773T too.
