### ISSUE TITLE
Long time tracked CM.8.1 + S:R403K  circulating since months in Utah 45

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2075]
All the members of our variant spotting group have discovered this lineage independently multiple times. so no credit to me only.
It is really a weirdo.
It keeps circulating since in Utah without any exportation to any area outside of Utah.
Being quite different from the vaccine strain i think it could be helpful for local health agencies to be aware of it.

Defining mutations:
CM.8.1 >>G14622A >  Orf7a:Q62* (C27577T) >> S:R403K (G22770A)

Query: C27577T,G22770A,G14622A

Sequences:44 
First: hCoV-19/USA/UT-UPHL-221223915221/2022 | Original | EPI_ISL_16401146 | 2022-12-08
Last: hCoV-19/USA/UT-UPHL-0608432912/2023 | Original | EPI_ISL_17788436 | 2023-05-22
EPI_ISL_16400597, EPI_ISL_16400612, EPI_ISL_16400616,
EPI_ISL_16401146, EPI_ISL_16493704, EPI_ISL_16493716,
EPI_ISL_16643286, EPI_ISL_16918766, EPI_ISL_17001279,
EPI_ISL_17001321, EPI_ISL_17001645, EPI_ISL_17068161,
EPI_ISL_17068231, EPI_ISL_17103747, EPI_ISL_17103780,
EPI_ISL_17191007, EPI_ISL_17278695, EPI_ISL_17445142,
EPI_ISL_17445148, EPI_ISL_17445171, EPI_ISL_17445218,
EPI_ISL_17445237, EPI_ISL_17445328, EPI_ISL_17502878-17502879,
EPI_ISL_17508552, EPI_ISL_17583753, EPI_ISL_17583780,
EPI_ISL_17669834, EPI_ISL_17669847, EPI_ISL_17727547,
EPI_ISL_17727573, EPI_ISL_17727603, EPI_ISL_17758992,
EPI_ISL_17759006, EPI_ISL_17759412, EPI_ISL_17759446,
EPI_ISL_17759681, EPI_ISL_17759726, EPI_ISL_17788436,
EPI_ISL_17848300, EPI_ISL_17848359, EPI_ISL_17857012,
EPI_ISL_17857098

Tree:
![Schermata 2023-06-28 alle 16 18 53](https://github.com/cov-lineages/pango-designation/assets/87669813/1e06437b-8faa-455d-8642-1c1b08fcf520)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_23252_c3da20.json?c=userOrOld&label=id:node_7120178

**Comment by MCB6** [comment]
3% of the Utah samples collected between May 1 - May 10
1.5% of the samples from May 11 - May 20
1% of the samples from May 20 - May 31 (a lone sample of May 22)
Not yet seen in June, although it's only 24 genomes uploaded.

Probably on the way out...

**Comment by FedeGueli** [comment]
One sample from California uploaded in June but sampled in April.

**Comment by FedeGueli** [comment]
58 sequences now, still the most recent from MAY.
