### ISSUE TITLE
XBB.1.9.1 x XBB.1.16 recombinant: 8 sequences (7x Malaysia, 1x NZ as of 2023-06-29)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#2077]
Came across what is probably a XBB.1.9.1 x XBB.1.16 recombinant, where Spike is XBB.1.16 but up and downstream of spike is XBB.1.9.1, effectively a XBB.1.9.1 that has gained ORF1b:D1746Y, S:180V and S:478R from XBB.1.16

7x in Malaysia, 1x in New Zealand

```
hCoV-19/New_Zealand/23YA2772/2023|EPI_ISL_17739516|2023-05-09
hCoV-19/Malaysia/MKAK_CL_23_34102/2023|EPI_ISL_17851370|2023-06-06
hCoV-19/Malaysia/MKAK_CL_23_34106/2023|EPI_ISL_17851371|2023-06-06
hCoV-19/Malaysia/UNIMAS-GHML2142/2023|EPI_ISL_17884268|2023-05-02
hCoV-19/Malaysia/UNIMAS-B19434/2023|EPI_ISL_17884273|2023-05-12
hCoV-19/Malaysia/UNIMAS-B19438/2023|EPI_ISL_17884277|2023-05-12
hCoV-19/Malaysia/UNIMAS-B19468/2023|EPI_ISL_17884300|2023-05-12
hCoV-19/Malaysia/UNIMAS-HSIBUML597/2023|EPI_ISL_17884420|2023-06-06
```

<img width="2059" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/ee828573-a6be-4ad8-892a-7e68d8baca04">

https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_65367_e05a00.json?label=id:node_6649464

Private mutations with respect to XBB.1.9.1:
<img width="685" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/cc56f430-e768-4e17-a50b-2e439a296d79">

**Comment by FedeGueli** [comment]
N:L219F made me think if it was possible maybe that  this could be a EG.1/XBB.1.16/EG.1 recombinant with a longer stretch of XBB.1.16 through C11956T but it is missing T12730A and it has 12789T so  if anything it should imply a triple coinfection , more likely N:L219F has been acquired independently

**Comment by aviczhl2** [comment]
Here's a large branch of EG.1+C11956T, maybe this branch involves some recombination with XBB.1.9.1
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_147be_edbf90.json?f_user
OrOld=uploaded%20sample&label=id:node_2914086)
![屏幕截图 2023-06-30 084757](https://github.com/cov-lineages/pango-designation/assets/10445944/18cdf17a-a201-4e9d-94a9-80ad2717489e)

**Comment by corneliusroemer** [comment]
Dead, nothing new has come 

This query should work in case it reappears: https://cov-spectrum.org/explore/World/AllSamples/Y2023/variants?variantQuery=%5B4-of%3AG18703T+%2C+A22101T+%2C+C28928T+%2C+T6800C+%2C+C27923T%5D&
