### ISSUE TITLE
Proposal for new sub-lineage of AY with C5239T and T5514C (ORF1ab:V1750A) in Japan

### ISSUE THREAD

**Issue by takaabe8050** [cov-lineages/pango-designation#208]
By Japan COVID-19 Open Data Consortium

Description
Sub-lineage of: B.1.617.2 (908 sequences)
Earliest sequence: 2020-04 (Japan)
Most recent sequence: 2020-08-23 (UK / Belgium)
Countries circulating: Japan (883 sequences), Hong Kong (2), Belgium (1), Italy (1), United Kingdom (13), USA (2), New Zealand (6)

Associated mutations
C5239T (ORF1ab: synonymous)
T5514C (ORF1ab: V1750A)

Genomes
[New_AY_x_genomelist.txt](https://github.com/cov-lineages/pango-designation/files/7097328/New_AY_x_genomelist.txt)

Evidence

![image](https://user-images.githubusercontent.com/89957075/131809347-a11fa3a6-20b7-476c-a178-0eaac2ede788.png)
[https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_53c56_3cd40.json](url)

Proposed lineage name
Next AY.x

**Comment by chrisruis** [comment]
Thanks @takaabe8050. We've added this as lineage AY.29 in [v1.2.74](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.74) with 820 sequence designations
