### ISSUE TITLE
FY.2 with ORF1a:T1874I (NSP3_T1056I) and S:A684V (79 seqs, 15 countries), futher gained S:A348S (2 seqs, Australia)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2080]
_Transferred from sars-cov-2-variants/lineage-proposals#234_

**Defining Mutations:** _on top of FY.2_ > C5886T(ORF1a:T1874I) > A28699G > C23613T(S:A684V)
**Query:** C5886T, A28699G, C23613T
**Query for S:A348S sub-branch:** A7150G, G22604T, C23613T
**Earliest seq:** 2023-03-26 (EPI_ISL_17558757, Kanagawa, Japan)
**Latest seq:** 2023-06-19 (EPI_ISL_17837754, Singapore)
**Sampled Countries:** Singapore (18), Italy (9), Japan (7), Australia (7, NSW/3, Victoria/2, WA/1, Queensland/1), USA (6, Washington/2, Maryland/1, Illinois/1, Florida/1, Indiana/1), Denmark (3), Slovenia (3), South Korea (3), Norway (2), Austria (2), Philippines (2), Mauritius (1), China (1, Taiwan)

<details><summary>Genomes: </summary>
EPI_ISL_17389982, EPI_ISL_17390126, EPI_ISL_17409007, EPI_ISL_17446299, EPI_ISL_17477627, EPI_ISL_17480221, EPI_ISL_17480282, EPI_ISL_17496169, EPI_ISL_17539534, EPI_ISL_17539536, EPI_ISL_17539599, EPI_ISL_17539832, EPI_ISL_17539863, EPI_ISL_17540125, EPI_ISL_17556294, EPI_ISL_17558757, EPI_ISL_17595458, EPI_ISL_17595469, EPI_ISL_17596127, EPI_ISL_17629476, EPI_ISL_17631089, EPI_ISL_17646980, EPI_ISL_17656704, EPI_ISL_17670258, EPI_ISL_17670261, EPI_ISL_17695002, EPI_ISL_17711188, EPI_ISL_17724751, EPI_ISL_17730577, EPI_ISL_17738046, EPI_ISL_17765622, EPI_ISL_17768415, EPI_ISL_17776985, EPI_ISL_17777003, EPI_ISL_17777015, EPI_ISL_17778484, EPI_ISL_17778790, EPI_ISL_17782568, EPI_ISL_17790418, EPI_ISL_17790419, EPI_ISL_17796528, EPI_ISL_17802109, EPI_ISL_17803285, EPI_ISL_17804234, EPI_ISL_17804235, EPI_ISL_17811608, EPI_ISL_17812606, EPI_ISL_17813488, EPI_ISL_17815817, EPI_ISL_17815818, EPI_ISL_17815985, EPI_ISL_17832767, EPI_ISL_17832772, EPI_ISL_17832773, EPI_ISL_17832775, EPI_ISL_17837754, EPI_ISL_17837755, EPI_ISL_17856099, EPI_ISL_17881053, EPI_ISL_17881067, EPI_ISL_17882231, EPI_ISL_17882975, EPI_ISL_17851144, EPI_ISL_17879993, EPI_ISL_17948917
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1641b_f2faf0.json?f_userOrOld=uploaded%20sample

- overview from FY.2 polytomy:
![Overview](https://github.com/cov-lineages/pango-designation/assets/125747944/fec90ad0-2926-4ce3-85e2-0c901f8be686)

- Details:
![Details](https://github.com/cov-lineages/pango-designation/assets/125747944/46f6ae71-8e66-4105-9972-32c6dbd82f11)

**Trivia:**
- Yet another FCS change.
- cc. @FedeGueli and @HynnSpylor spot it first.

**Comment by HynnSpylor** [comment]
desingated as FY.2.1
