### ISSUE TITLE
Recently spreading XBB.1.5 Branch with Orf1a:S771I ( = G2577T) designation request , three levels already 1966 seqs

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2082]
cc @corneliusroemer 

 @NkRMnZr found first and i independently rediscovered an undesignated branch of XBB.1.5 that seems beeing disproportionately sampled from MAY ahead and it is acquiring interesting new mutations and spreading in Spain Asia and Worlwide.

The first, valid, description of it is in this proposal : https://github.com/sars-cov-2-variants/lineage-proposals/issues/307 
full credit to @NkRMnZr

I sum it just to finalize its designation as soon as possible.

.1
It is a XBB.1.5 branch , missassigned by Nextclade to XBB.1.5.40 
It is defined by XBB.1.5 >> **Orf1a:S771I ( G2577T)**  
Its query is : G2577T,T17124C finds 1957 , 385 from May 2023 ahead

.1.1
then its first sublineage  is defined by
XBB.1.5 >> Orf1a:S771I ( G2577T)  >>  **Orf1a:N2140S ( A6684G )**
Gisaid : A6684G,G2577T,T17124C finds 986 sequences 247 of them collected after MAY 1 

.1.1.1
this branch has a big sublineage defined by 
XBB.1.5 >> Orf1a:S771I ( G2577T)  >>  Orf1a:N2140S ( A6684G )>> **Orf7a:K2E (A27397G)** 
Gisaid: A6684G,G2577T,T17124C,A27397G finds 432 100 of them collected after MAY 1

.1.2
then there is a second sublineage of Orf1a:S771I
defined by a nuc mutations
XBB.1.5 >> Orf1a:S771I ( G2577T)  >> **C5512T**
Gisaid query:  ,G2577T,T17124C,C5512T finds 669  113 collected after MAY.1

1.2.1
this  branch has a sublineage defined by **Orf1a:T882I (C2910T) & S:P621A (C23423G)**
Gisaid query :  T17124C,C5512T,C23423G finds 60  all collected from MAY ahead

1.2.2
this branch is defined by C5512T + **C8752T + S:E654K (G23522A)**
Gisaid query: G23522A,C8752T,C5512T finds 16 all from MAY ahead
(proposed here https://github.com/sars-cov-2-variants/lineage-proposals/issues/311 )

Further sublineages:
Then there are the proposals of further sublineages the one proposed by  @NkRMnZr in https://github.com/sars-cov-2-variants/lineage-proposals/issues/307

ALL the sublineages discsussed highlighted here:
Light green = .1
Orange = .1.1
Grey = .1.1.1
Red = 1.2 
Green: 1.2.1  S:P621A
Yellow =  1.2.2 E:654K 
 

![Schermata 2023-07-03 alle 13 08 35](https://github.com/cov-lineages/pango-designation/assets/87669813/af67a145-27d5-40c2-a85c-bda757a4b2c2)

CC @corneliusroemer @InfrPopGen @thomaspeacockl @AngieHinrichs if you could review and designate at least the mayor branches it would be great to make tracking the smaller lineages easier and also useful Thank you in advance.

![Schermata 2023-07-03 alle 13 06 46](https://github.com/cov-lineages/pango-designation/assets/87669813/9ef61462-e637-4d3b-a6de-4c0b2084849c)

![Schermata 2023-07-03 alle 13 00 16](https://github.com/cov-lineages/pango-designation/assets/87669813/9a57c794-67bf-4530-9b00-2cd331ec11b0)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1faf9_29cf20.json?c=country&label=id:node_6874183

**Comment by FedeGueli** [comment]
I mistakenly wrote S:771L instead of 771I now corrected.

**Comment by ryhisner** [comment]
The S:P621A branch here is particularly interesting. That's a C->G nucleotide mutation, and those are rare. A rare nuc mutation like C->G or T->G is, in my view, much more likely to be adaptive than the more common C->T, A->G, G->T and similar nuc substitutions, which are driven by APOBEC, ADAR, ROS, and perhaps other host-driven mechanisms. 

Furthermore, we know S:P621 is an AA residue of interest. S:P621S has been successful in several XBB* lineages, and I believe it is fairly close to the S:Y636 cleavage site that has convincingly been proposed in the study below. 
<img width="1317" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/258e59cd-2cf5-4860-a65c-4d7619510163">
https://www.nature.com/articles/s41421-022-00419-w

**Comment by FedeGueli** [comment]
Thank you @ryhisner
