### ISSUE TITLE
 XBB.1.16.13 with S:K304N circulating in South Korea and Japan ( 155 seqs) 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2083]
We tracked this one for a while : https://github.com/sars-cov-2-variants/lineage-proposals/issues/298
**EDITED**
Just noticed that the parental lineage with Orf1a:G519S and Orf1a:G1101D has been designated XBB.1.16.13. 
Sorry for being late in the update.
It is def worth a rapid review and eventually a designation.

With @ryhisner we tracked for a while S:K304Q sublineages of XBB.1.5 but none of them  took off as first we thought.
Then we kept spotting variation at 304 but also at 307 (mainly with @hynnspylor) with some more success.
Here i want to propose a sublineage of XBB.1.16 that seems fast and is spreading in South Korea and Japan.

Gisaid query:  **C17949T, C25006T,A22474C**

Defining mutations:
XBB.1.16.13 (**Orf1a:G519S** +**Orf1a:G1101D** =**NSP3_G283D**) **>>>** C17949T, C25006T > **S:K304N** (A22474C)

Samples: 
First :
hCoV-19/USA/WA-GBW-H20-312-9890/2023 | Original | EPI_ISL_17700412 | 2023-05-10 (Travel related with South Korea)
Last:
hCoV-19/Singapore/R42MR63/2023 | Original | EPI_ISL_17837587 | 2023-06-15 (local case in an elderly people)

IDS:
<Details>
<Summary>
EPI_ISL_17685653, EPI_ISL_17700412, EPI_ISL_17730673,
EPI_ISL_17741288, EPI_ISL_17741320, EPI_ISL_17741374,
EPI_ISL_17741397, EPI_ISL_17778963, EPI_ISL_17779097,
EPI_ISL_17779216, EPI_ISL_17779312, EPI_ISL_17779342,
EPI_ISL_17779344, EPI_ISL_17779443, EPI_ISL_17780164,
EPI_ISL_17788737, EPI_ISL_17788935, EPI_ISL_17789145,
EPI_ISL_17789270, EPI_ISL_17790707, EPI_ISL_17796659,
EPI_ISL_17806884-17806885, EPI_ISL_17807115, EPI_ISL_17807449,
EPI_ISL_17807461, EPI_ISL_17807528, EPI_ISL_17807826,
EPI_ISL_17807864, EPI_ISL_17815255, EPI_ISL_17815741,
EPI_ISL_17816404, EPI_ISL_17816522, EPI_ISL_17816580,
EPI_ISL_17816589, EPI_ISL_17816622, EPI_ISL_17831217,
EPI_ISL_17834715, EPI_ISL_17834831, EPI_ISL_17834875,
EPI_ISL_17834930, EPI_ISL_17835021, EPI_ISL_17835183,
EPI_ISL_17835223, EPI_ISL_17835327, EPI_ISL_17835360,
EPI_ISL_17835374, EPI_ISL_17835376, EPI_ISL_17835397,
EPI_ISL_17835468, EPI_ISL_17835489, EPI_ISL_17835766,
EPI_ISL_17837587, EPI_ISL_17853927, EPI_ISL_17853953,
EPI_ISL_17856343, EPI_ISL_17856704, EPI_ISL_17882477,
EPI_ISL_17882660, EPI_ISL_17882684, EPI_ISL_17883111,
EPI_ISL_17883938, EPI_ISL_17883947-17883948, EPI_ISL_17884021,
EPI_ISL_17884125, EPI_ISL_17884164-17884165, EPI_ISL_17927763,
EPI_ISL_17927778, EPI_ISL_17927823, EPI_ISL_17927853,
EPI_ISL_17927880, EPI_ISL_17927920, EPI_ISL_17927928,
EPI_ISL_17927980, EPI_ISL_17928040, EPI_ISL_17928057,
EPI_ISL_17928061, EPI_ISL_17928150, EPI_ISL_17930348,
EPI_ISL_17930435, EPI_ISL_17930494, EPI_ISL_17930513,
EPI_ISL_17930655, EPI_ISL_17930658, EPI_ISL_17930685,
EPI_ISL_17930720, EPI_ISL_17930775, EPI_ISL_17932506,
EPI_ISL_17932551, EPI_ISL_17932592, EPI_ISL_17949234,
EPI_ISL_17950544, EPI_ISL_17950604, EPI_ISL_17950710,
EPI_ISL_17952421, EPI_ISL_17952561, EPI_ISL_17952579,
EPI_ISL_17955536
</Details>

Tree:
![Schermata 2023-07-04 alle 00 01 29](https://github.com/cov-lineages/pango-designation/assets/87669813/50fc8193-85a5-4dc0-bd25-92628c4a6123)

![Schermata 2023-07-03 alle 23 59 54](https://github.com/cov-lineages/pango-designation/assets/87669813/c8fc90c5-5d13-4993-ba39-a3ac1319192c)
![Schermata 2023-07-04 alle 00 01 51](https://github.com/cov-lineages/pango-designation/assets/87669813/0d42b76c-04a0-43d7-9975-efff7e368678)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_18248_3444d0.json?c=country&label=id:node_6604002

Growth advantage:
Apparently it has a good chance to be faster than other xbb.1.16 circulating in South Korea:
![Schermata 2023-07-04 alle 00 02 40](https://github.com/cov-lineages/pango-designation/assets/87669813/64d95eaf-7930-4b6e-b9c1-338088e2860e)
https://cov-spectrum.org/explore/South%20Korea/AllSamples/from%3D2023-05-01%26to%3D2023-06-30/variants?nextcladePangoLineage=XBB.1.16*&aaMutations1=S%3AK304N&nextcladePangoLineage1=xbb.1.16*&analysisMode=CompareToBaseline&

Ping @corneliusroemer @InfrPopGen

**Comment by HynnSpylor** [comment]
139 seqs now with rapid increasing

**Comment by FedeGueli** [comment]
> C17949T, C25006T,A22474C

Mainly SOuth Korea or increasing also in Japan?

**Comment by FedeGueli** [comment]
13 new samples one from Us, one from Aus the rest from Japan. Ping @corneliusroemer it is growing fast.

**Comment by alurqu** [comment]
Is this now designated HF.1?

**Comment by FedeGueli** [comment]
https://github.com/cov-lineages/pango-designation/commit/c36d5d613c740826d2ec46a4a99fb3e9ad542db2
