### ISSUE TITLE
XBB.1.16.1 Sublineage with ORF9b:Q70R (A28492G) (164 seq, 19 countries, Jul 4)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2085]
(Transferred from pre-proposal page. Original proposal June 13.)
### **Description**
**Sub-lineage of:** XBB.1.16.1
**Earliest sequence:** 2023-3-13, India, Delhi — EPI_ISL_17447212
**Most recent sequence:** 2023-5-31, Australia, New South Wales — EPI_ISL_17784416
**Countries circulating:** Canada (18), USA (17), India (15), Mauritius (13), Hong Kong (9), Australia (6), Singapore (6), South Korea (4), China (2), Reunion (2), Sweden (2), Iceland (1), Japan (1), Taiwan (1), Thailand (1)
**Number of Sequences:** 97
**GISAID AA Query:** None
**GISAID Nucleotide Query:** A28447G, A28492G
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.16.1* & A28492G
**Substitutions on top of XBB.1.16.1:**
**ORF9b:** Q70R
**Nucleotide:** A28492G
 
**Phylogenetic Order of Mutations:** A28492G (ORF9b:Q70R)

**USHER Tree**
Note that all the long branches in the middle of this tree are garbage, full of false reversions and such. I wish there was a way to mask any sequence you wanted to in Usher. It would make the trees look a whole lot more realistic. For now, we're stuck with these funhouse-mirror trees. 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.16.1_ORF9b_Q70R.json?c=gt-nuc_28492&label=id:node_6574479
<img width="1492" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/8be25dee-76c4-49dd-bc8b-7eb89b3c45a5">
 

**Evidence**
ORF9b mutations have become remarkably influential in the past several months. This is a relatively new one, and judging by its rapid geographic spread, it seems possible it could be a successful one. It's difficult to tell though, as XBB.1.16.1 itself is also spreading rapidly around the world.

One sequence collected in the US on May 21 has travel history in Mexico and one collected April 23 has travel history in Thailand. One sequence from Singapore has travel history in Indonesia, another Taiwan, and another India. The sequence from Taiwan had travel history in Japan.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17391403, EPI_ISL_17431902, EPI_ISL_17447212, EPI_ISL_17447221, EPI_ISL_17447252, EPI_ISL_17447309, EPI_ISL_17447313, EPI_ISL_17447358, EPI_ISL_17466899, EPI_ISL_17526273, EPI_ISL_17539472, EPI_ISL_17548454, EPI_ISL_17588932, EPI_ISL_17588940, EPI_ISL_17595358, EPI_ISL_17595431, EPI_ISL_17595523, EPI_ISL_17605511, EPI_ISL_17605541, EPI_ISL_17605569, EPI_ISL_17605760, EPI_ISL_17611315, EPI_ISL_17614852, EPI_ISL_17620632, EPI_ISL_17630316, EPI_ISL_17630479, EPI_ISL_17631408, EPI_ISL_17633693, EPI_ISL_17644853, EPI_ISL_17657866, EPI_ISL_17660144, EPI_ISL_17660177, EPI_ISL_17660391, EPI_ISL_17662069, EPI_ISL_17669621, EPI_ISL_17686745, EPI_ISL_17689807, EPI_ISL_17689818, EPI_ISL_17689819, EPI_ISL_17690692, EPI_ISL_17695014, EPI_ISL_17697634, EPI_ISL_17697706, EPI_ISL_17699191, EPI_ISL_17699210, EPI_ISL_17699219, EPI_ISL_17699233, EPI_ISL_17701143, EPI_ISL_17701237, EPI_ISL_17701239, EPI_ISL_17701448, EPI_ISL_17706278, EPI_ISL_17709545, EPI_ISL_17715125, EPI_ISL_17716096, EPI_ISL_17718879, EPI_ISL_17720574, EPI_ISL_17722632, EPI_ISL_17724357, EPI_ISL_17724373, EPI_ISL_17726325, EPI_ISL_17729036, EPI_ISL_17729051, EPI_ISL_17730731, EPI_ISL_17734745, EPI_ISL_17761065, EPI_ISL_17761081, EPI_ISL_17762879, EPI_ISL_17762884, EPI_ISL_17762893, EPI_ISL_17762913, EPI_ISL_17764391, EPI_ISL_17766449, EPI_ISL_17767939, EPI_ISL_17767966, EPI_ISL_17768274, EPI_ISL_17778454, EPI_ISL_17779541, EPI_ISL_17779787, EPI_ISL_17784144, EPI_ISL_17784146, EPI_ISL_17784416, EPI_ISL_17784440, EPI_ISL_17786433, EPI_ISL_17787202, EPI_ISL_17788455, EPI_ISL_17788462, EPI_ISL_17788957, EPI_ISL_17789096, EPI_ISL_17790870, EPI_ISL_17791957, EPI_ISL_17791966, EPI_ISL_17791969, EPI_ISL_17791972, EPI_ISL_17791987, EPI_ISL_17792004, EPI_ISL_17792015
</details>

**Comment by FedeGueli** [comment]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/177

**Comment by FedeGueli** [comment]
185 as today  i want to ping Cornelius this has also 17 sequences from Japan ( i dont know why are not listed in the @ryhisner proposal probably just  a copy past from the original pre proposal)

**Comment by ryhisner** [comment]
There's also an interesting cluster in this lineage from Sweden that has an out-of-frame, 15-nucleotide deletion in the middle of N. Eight sequences, all uploaded on July 7 and collected from June 6-8. One also has S:G261V. 
<img width="1311" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/0fa240c3-6ede-4872-a327-def4817bad9f">

Each of these eight sequences also has the classic, three-nuc-mutation, ORF1b novel TRS as well. 
<img width="981" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/96ef9ee0-5e52-4a78-bf68-ad05e0fada2c">
<img width="1160" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/6b7825ca-e333-4fa4-b983-36d108292d34">

**Comment by DailyCovidCases** [comment]
Please close this issue
