### ISSUE TITLE
GF.1 (XBB.1.5.24.1) with ORF1b:Q1546H, ORF1b:G814D (1001 seqs, mainly in China, 24 countries), further with a potential recombinant with EG.5.1* that gained S:F456L (5 seqs, China, Sweden)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2086]
Transferred from sars-cov-2-variants/lineage-proposals#191

**Defining Mutations:** _on top of GF.1 (XBB.1.5.24.1)_ > `A8197G` > `G18105T(ORF1b:Q1546H/nsp14_G22H)` > `G15908A (ORF1b:G814D/nsp12_G823D)` 
**Query:** `A8197G, G15908A`
**Earliest seq:** 2023-03-15 [`EPI_ISL_17494031`, Jiangsu, China]
**Latest seq:** 2023-06-23 [`EPI_ISL_17956706`, Tianjin, China]
**Sampled Countries:** China, USA, Singapore, Canada, Japan, South Korea, Australia, Italy, Thailand, Austria, Spain, France

<details><summary>Genomes: </summary>

EPI_ISL_17494031, EPI_ISL_17505628-17505629, EPI_ISL_17505635,
EPI_ISL_17505648-17505649, EPI_ISL_17511820, EPI_ISL_17511892,
EPI_ISL_17516743, EPI_ISL_17584959-17584960, EPI_ISL_17614989,
EPI_ISL_17615012, EPI_ISL_17618432, EPI_ISL_17618482,
EPI_ISL_17618501, EPI_ISL_17618641, EPI_ISL_17618659,
EPI_ISL_17618667, EPI_ISL_17618719, EPI_ISL_17619023,
EPI_ISL_17619119, EPI_ISL_17619127, EPI_ISL_17619161,
EPI_ISL_17619185, EPI_ISL_17620292, EPI_ISL_17625285,
EPI_ISL_17625540, EPI_ISL_17625589, EPI_ISL_17625652,
EPI_ISL_17637385, EPI_ISL_17637387-17637395, EPI_ISL_17637399-17637400,
EPI_ISL_17637402-17637405, EPI_ISL_17637412, EPI_ISL_17637420,
EPI_ISL_17637440, EPI_ISL_17637446-17637447, EPI_ISL_17637467,
EPI_ISL_17637473, EPI_ISL_17637475, EPI_ISL_17637477,
EPI_ISL_17645420, EPI_ISL_17645699, EPI_ISL_17645801,
EPI_ISL_17646003, EPI_ISL_17652359, EPI_ISL_17652364,
EPI_ISL_17669050, EPI_ISL_17669084, EPI_ISL_17669111,
EPI_ISL_17669165, EPI_ISL_17672027, EPI_ISL_17678325,
EPI_ISL_17678389, EPI_ISL_17683967, EPI_ISL_17684040,
EPI_ISL_17684051, EPI_ISL_17684113, EPI_ISL_17684123,
EPI_ISL_17684180, EPI_ISL_17684265, EPI_ISL_17684276-17684277,
EPI_ISL_17684290-17684295, EPI_ISL_17684335, EPI_ISL_17684449,
EPI_ISL_17689267, EPI_ISL_17689269, EPI_ISL_17689271,
EPI_ISL_17689275, EPI_ISL_17689292-17689293, EPI_ISL_17689310,
EPI_ISL_17689312, EPI_ISL_17689347, EPI_ISL_17689434,
EPI_ISL_17696871, EPI_ISL_17696894, EPI_ISL_17696897,
EPI_ISL_17696983, EPI_ISL_17697567, EPI_ISL_17697984,
EPI_ISL_17698091, EPI_ISL_17698136, EPI_ISL_17698830,
EPI_ISL_17703735, EPI_ISL_17703964, EPI_ISL_17703991,
EPI_ISL_17714315, EPI_ISL_17714358, EPI_ISL_17714385,
EPI_ISL_17714389, EPI_ISL_17714421, EPI_ISL_17714429,
EPI_ISL_17723154, EPI_ISL_17724510, EPI_ISL_17724514,
EPI_ISL_17724978, EPI_ISL_17724981, EPI_ISL_17725015,
EPI_ISL_17725019, EPI_ISL_17725056, EPI_ISL_17725099,
EPI_ISL_17725103, EPI_ISL_17725169, EPI_ISL_17725192,
EPI_ISL_17725197, EPI_ISL_17725199-17725200, EPI_ISL_17725233,
EPI_ISL_17725241, EPI_ISL_17725243, EPI_ISL_17725250-17725251,
EPI_ISL_17725259, EPI_ISL_17725288, EPI_ISL_17725295-17725296,
EPI_ISL_17725302, EPI_ISL_17725311, EPI_ISL_17725322,
EPI_ISL_17725328-17725329, EPI_ISL_17725353, EPI_ISL_17725359,
EPI_ISL_17725371, EPI_ISL_17725461, EPI_ISL_17725477,
EPI_ISL_17725485, EPI_ISL_17725502, EPI_ISL_17728929,
EPI_ISL_17729094, EPI_ISL_17729760-17729761, EPI_ISL_17729765,
EPI_ISL_17729769, EPI_ISL_17729775, EPI_ISL_17729787,
EPI_ISL_17729791, EPI_ISL_17729966, EPI_ISL_17735956,
EPI_ISL_17738979, EPI_ISL_17739687, EPI_ISL_17739715,
EPI_ISL_17744592, EPI_ISL_17744604, EPI_ISL_17744611,
EPI_ISL_17744643, EPI_ISL_17744747, EPI_ISL_17744791,
EPI_ISL_17744794, EPI_ISL_17765823, EPI_ISL_17765848,
EPI_ISL_17765885, EPI_ISL_17765891, EPI_ISL_17765914,
EPI_ISL_17765930-17765931, EPI_ISL_17765938, EPI_ISL_17769933,
EPI_ISL_17769957, EPI_ISL_17769973, EPI_ISL_17769984,
EPI_ISL_17769990, EPI_ISL_17769998, EPI_ISL_17770042,
EPI_ISL_17770050, EPI_ISL_17770092, EPI_ISL_17770109,
EPI_ISL_17770123, EPI_ISL_17770146, EPI_ISL_17770150,
EPI_ISL_17770169, EPI_ISL_17770174, EPI_ISL_17770201,
EPI_ISL_17770206, EPI_ISL_17770226-17770227, EPI_ISL_17770231,
EPI_ISL_17770244-17770245, EPI_ISL_17770251, EPI_ISL_17770267,
EPI_ISL_17770280, EPI_ISL_17770291, EPI_ISL_17770314,
EPI_ISL_17770325, EPI_ISL_17770338, EPI_ISL_17770354,
EPI_ISL_17770411, EPI_ISL_17774029, EPI_ISL_17775176,
EPI_ISL_17775200, EPI_ISL_17775214, EPI_ISL_17775654,
EPI_ISL_17778684, EPI_ISL_17778705, EPI_ISL_17778717,
EPI_ISL_17778726, EPI_ISL_17778750, EPI_ISL_17779892,
EPI_ISL_17780121, EPI_ISL_17783137, EPI_ISL_17784868,
EPI_ISL_17784892, EPI_ISL_17785122, EPI_ISL_17785146,
EPI_ISL_17785148, EPI_ISL_17785169, EPI_ISL_17785205,
EPI_ISL_17785214, EPI_ISL_17785217, EPI_ISL_17785271-17785272,
EPI_ISL_17785277, EPI_ISL_17785287, EPI_ISL_17785289,
EPI_ISL_17785318, EPI_ISL_17785364, EPI_ISL_17788502,
EPI_ISL_17788863, EPI_ISL_17789542, EPI_ISL_17790291,
EPI_ISL_17790843, EPI_ISL_17791896, EPI_ISL_17793980,
EPI_ISL_17793983-17793985, EPI_ISL_17793987, EPI_ISL_17793989,
EPI_ISL_17793991-17793992, EPI_ISL_17793994-17793996, EPI_ISL_17793998-17793999,
EPI_ISL_17794001-17794003, EPI_ISL_17794005, EPI_ISL_17794008-17794009,
EPI_ISL_17794031-17794033, EPI_ISL_17794035, EPI_ISL_17794037,
EPI_ISL_17794041-17794046, EPI_ISL_17794049-17794051, EPI_ISL_17794053,
EPI_ISL_17794057, EPI_ISL_17794530, EPI_ISL_17794560,
EPI_ISL_17794699-17794700, EPI_ISL_17794727, EPI_ISL_17794752,
EPI_ISL_17794845, EPI_ISL_17794852, EPI_ISL_17794857,
EPI_ISL_17794884, EPI_ISL_17794981, EPI_ISL_17795016,
EPI_ISL_17795022-17795023, EPI_ISL_17795025-17795026, EPI_ISL_17795053,
EPI_ISL_17795056-17795058, EPI_ISL_17795062-17795063, EPI_ISL_17795067-17795072,
EPI_ISL_17795075, EPI_ISL_17795078-17795079, EPI_ISL_17795081,
EPI_ISL_17795083-17795084, EPI_ISL_17795086-17795088, EPI_ISL_17795108,
EPI_ISL_17795122, EPI_ISL_17795152-17795153, EPI_ISL_17795172,
EPI_ISL_17795179, EPI_ISL_17795190-17795191, EPI_ISL_17795198,
EPI_ISL_17795206, EPI_ISL_17795235, EPI_ISL_17795278,
EPI_ISL_17795296, EPI_ISL_17795332, EPI_ISL_17795347,
EPI_ISL_17795371, EPI_ISL_17795379, EPI_ISL_17795428,
EPI_ISL_17795456, EPI_ISL_17795471, EPI_ISL_17795479,
EPI_ISL_17795500, EPI_ISL_17795502, EPI_ISL_17795505,
EPI_ISL_17795524, EPI_ISL_17795528, EPI_ISL_17795532,
EPI_ISL_17795542, EPI_ISL_17795564, EPI_ISL_17795572,
EPI_ISL_17795574, EPI_ISL_17795578, EPI_ISL_17795581-17795584,
EPI_ISL_17795586-17795587, EPI_ISL_17795600-17795608, EPI_ISL_17795620,
EPI_ISL_17795626, EPI_ISL_17795652, EPI_ISL_17795656,
EPI_ISL_17795660, EPI_ISL_17795676, EPI_ISL_17795685-17795686,
EPI_ISL_17795688, EPI_ISL_17795693, EPI_ISL_17795696,
EPI_ISL_17795708, EPI_ISL_17795727-17795728, EPI_ISL_17795743,
EPI_ISL_17795746, EPI_ISL_17795768, EPI_ISL_17795777,
EPI_ISL_17795779-17795780, EPI_ISL_17795783, EPI_ISL_17795786,
EPI_ISL_17795789, EPI_ISL_17801807, EPI_ISL_17801895,
EPI_ISL_17801911, EPI_ISL_17801985, EPI_ISL_17802520,
EPI_ISL_17802776, EPI_ISL_17807512, EPI_ISL_17807760,
EPI_ISL_17808096, EPI_ISL_17808102, EPI_ISL_17808116,
EPI_ISL_17808130, EPI_ISL_17808132, EPI_ISL_17808135,
EPI_ISL_17808138, EPI_ISL_17808147, EPI_ISL_17808164-17808166,
EPI_ISL_17808200, EPI_ISL_17808236, EPI_ISL_17808310,
EPI_ISL_17808417, EPI_ISL_17808420, EPI_ISL_17809368,
EPI_ISL_17811016, EPI_ISL_17811031, EPI_ISL_17811056,
EPI_ISL_17811097, EPI_ISL_17811160, EPI_ISL_17811168,
EPI_ISL_17811197, EPI_ISL_17811214, EPI_ISL_17811222,
EPI_ISL_17811232-17811233, EPI_ISL_17811245-17811246, EPI_ISL_17811261,
EPI_ISL_17811272, EPI_ISL_17811321, EPI_ISL_17811354,
EPI_ISL_17813654, EPI_ISL_17814685, EPI_ISL_17816293,
EPI_ISL_17816467, EPI_ISL_17816641, EPI_ISL_17816736,
EPI_ISL_17816852, EPI_ISL_17816966-17816967, EPI_ISL_17817006,
EPI_ISL_17817039, EPI_ISL_17819890, EPI_ISL_17826706,
EPI_ISL_17826966, EPI_ISL_17830353, EPI_ISL_17830374,
EPI_ISL_17830392, EPI_ISL_17832372, EPI_ISL_17832406,
EPI_ISL_17835227, EPI_ISL_17835326, EPI_ISL_17836228,
EPI_ISL_17836272, EPI_ISL_17836346, EPI_ISL_17836354,
EPI_ISL_17836452, EPI_ISL_17836467, EPI_ISL_17836479,
EPI_ISL_17836518, EPI_ISL_17836524, EPI_ISL_17836526,
EPI_ISL_17836541, EPI_ISL_17836560, EPI_ISL_17836562,
EPI_ISL_17836566, EPI_ISL_17836635, EPI_ISL_17836690,
EPI_ISL_17836697, EPI_ISL_17836734-17836735, EPI_ISL_17836739,
EPI_ISL_17836764, EPI_ISL_17836791, EPI_ISL_17836800,
EPI_ISL_17836826, EPI_ISL_17836828, EPI_ISL_17836866,
EPI_ISL_17836884, EPI_ISL_17836914, EPI_ISL_17836918,
EPI_ISL_17836924, EPI_ISL_17836932, EPI_ISL_17836955-17836956,
EPI_ISL_17836961, EPI_ISL_17836972, EPI_ISL_17836990,
EPI_ISL_17837027, EPI_ISL_17837029, EPI_ISL_17837071,
EPI_ISL_17837123, EPI_ISL_17837642-17837644, EPI_ISL_17850155,
EPI_ISL_17850173, EPI_ISL_17850222, EPI_ISL_17850253,
EPI_ISL_17850410, EPI_ISL_17850617, EPI_ISL_17850755,
EPI_ISL_17852421, EPI_ISL_17854185, EPI_ISL_17855413,
EPI_ISL_17855903, EPI_ISL_17856105, EPI_ISL_17856804,
EPI_ISL_17861551, EPI_ISL_17879917, EPI_ISL_17880017,
EPI_ISL_17880930, EPI_ISL_17881028, EPI_ISL_17882082,
EPI_ISL_17883873, EPI_ISL_17884027, EPI_ISL_17924300,
EPI_ISL_17927884, EPI_ISL_17927954, EPI_ISL_17930501,
EPI_ISL_17937841, EPI_ISL_17950900, EPI_ISL_17951222,
EPI_ISL_17951233, EPI_ISL_17951243, EPI_ISL_17951323,
EPI_ISL_17951326, EPI_ISL_17951392, EPI_ISL_17951596,
EPI_ISL_17952479, EPI_ISL_17956706, EPI_ISL_17956761,
EPI_ISL_17956809-17956810, EPI_ISL_17956868, EPI_ISL_17956923,
EPI_ISL_17956938, EPI_ISL_17956943, EPI_ISL_17956958,
EPI_ISL_17956975, EPI_ISL_17956986, EPI_ISL_17956990,
EPI_ISL_17957005, EPI_ISL_17957028-17957029, EPI_ISL_17957051,
EPI_ISL_17957063, EPI_ISL_17957080, EPI_ISL_17957084,
EPI_ISL_17957133, EPI_ISL_17957143, EPI_ISL_17957155,
EPI_ISL_17957161, EPI_ISL_17958233, EPI_ISL_17958715,
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36cb8_553490.json?c=gt-nuc_8197,15908

view from GF.1 (XBB.1.5.24.1) polytomy
![Overview](https://github.com/cov-lineages/pango-designation/assets/125747944/161a83d5-8eea-425f-bbcf-8f1fc4d7236f)

diversity
![Details](https://github.com/cov-lineages/pango-designation/assets/125747944/7c7b4b0d-972f-4f9d-80dd-4548ba523855)

**Trivia:**
- 5% local prevalence in certain provinces of China, according to @FedeGueli it doubles every 9-10 days.
![Intl](https://github.com/cov-lineages/pango-designation/assets/125747944/7a8052bb-369d-4f76-b315-67898859a146)

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by oobb45729** [comment]
Interestingly, XBC has the insertion ins_ORF1b:814:D, and ORF1b:G814D showed up in another Deltacron strain:
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=ORF1b%3AG814D%26M%3AI82T%26S%3AT859N%26S%3AV736I&

**Comment by Over-There-Is** [comment]
Heilongjiang, Henan, Shanxi
