### ISSUE TITLE
FL.4 + N:K256R sublineage  emerged in China and sampled in 12 countries as 18/08 (353 seqs )

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2087]
After being tracked on the preproposal page for some weeks mainly by @over_There_is @memorablea and me 
we decided to propose it cause it shows a steady growth that made it reaching 200 sequences quite fastly 
  
Original issue
https://github.com/sars-cov-2-variants/lineage-proposals/issues/117#issuecomment-1621889954

Rapid review (updated as 05/07/23)
Gisaid query: G16741T, A29040G,T28297C

Defining mutations: FL.4 >> N:K256R (A29040G)

Tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3dd4b_581c30.json?label=id:node_6705665
![Schermata 2023-07-05 alle 16 47 03](https://github.com/cov-lineages/pango-designation/assets/87669813/c662f878-c012-4d7f-98b9-5e47e45bff41)
![Schermata 2023-07-05 alle 16 47 25](https://github.com/cov-lineages/pango-designation/assets/87669813/e86603d7-1d02-4efa-a90b-e4109ab2dd1b)

Samples: 203
First sample: hCoV-19/Guangdong/GDCDC_GZ_0255/2023 | Original | EPI_ISL_17697978 | 2023-04-17
First documented exportation: hCoV-19/USA/NY-GBW-H20-310-2558/2023 | Original | EPI_ISL_17716662 | 2023-05-14
Last sample: hCoV-19/Tianjn/TJCDC0630-38/2023 | Original | EPI_ISL_17956718 | 2023-06-23
<details>
<summary>
EPI_ISL_17625346, EPI_ISL_17625376, EPI_ISL_17625396,
EPI_ISL_17645431, EPI_ISL_17645495-17645496, EPI_ISL_17645502-17645503,
EPI_ISL_17652437, EPI_ISL_17664554, EPI_ISL_17664556,
EPI_ISL_17671922, EPI_ISL_17672042, EPI_ISL_17672044,
EPI_ISL_17678296, EPI_ISL_17678328, EPI_ISL_17678353,
EPI_ISL_17678432, EPI_ISL_17683129, EPI_ISL_17684134,
EPI_ISL_17684348-17684349, EPI_ISL_17684358, EPI_ISL_17684363-17684364,
EPI_ISL_17684369, EPI_ISL_17684376-17684377, EPI_ISL_17684380,
EPI_ISL_17684385-17684386, EPI_ISL_17684389-17684391, EPI_ISL_17684393,
EPI_ISL_17684463, EPI_ISL_17689342, EPI_ISL_17689427,
EPI_ISL_17689429, EPI_ISL_17694990, EPI_ISL_17696757,
EPI_ISL_17696924, EPI_ISL_17696950, EPI_ISL_17696953,
EPI_ISL_17696962, EPI_ISL_17696966, EPI_ISL_17696980,
EPI_ISL_17697978, EPI_ISL_17698001, EPI_ISL_17698102,
EPI_ISL_17703966, EPI_ISL_17714320, EPI_ISL_17714323,
EPI_ISL_17714325-17714327, EPI_ISL_17714332, EPI_ISL_17714380,
EPI_ISL_17714398, EPI_ISL_17714401, EPI_ISL_17716662,
EPI_ISL_17718354-17718355, EPI_ISL_17724934-17724935, EPI_ISL_17724969,
EPI_ISL_17725029, EPI_ISL_17725059-17725061, EPI_ISL_17725098,
EPI_ISL_17725211, EPI_ISL_17725244, EPI_ISL_17725462,
EPI_ISL_17725472, EPI_ISL_17729766, EPI_ISL_17729801,
EPI_ISL_17729835, EPI_ISL_17729899, EPI_ISL_17729908,
EPI_ISL_17739678, EPI_ISL_17744714, EPI_ISL_17744779,
EPI_ISL_17763775, EPI_ISL_17765908, EPI_ISL_17770173,
EPI_ISL_17770236, EPI_ISL_17775539, EPI_ISL_17775660,
EPI_ISL_17778584, EPI_ISL_17778668, EPI_ISL_17778671,
EPI_ISL_17778765-17778766, EPI_ISL_17779907, EPI_ISL_17784360,
EPI_ISL_17785142, EPI_ISL_17785163, EPI_ISL_17785341,
EPI_ISL_17785351, EPI_ISL_17790432, EPI_ISL_17790440,
EPI_ISL_17794095, EPI_ISL_17794110, EPI_ISL_17794166-17794169,
EPI_ISL_17794171-17794174, EPI_ISL_17794176-17794177, EPI_ISL_17794180-17794183,
EPI_ISL_17794191, EPI_ISL_17794207, EPI_ISL_17794216,
EPI_ISL_17794721, EPI_ISL_17794774, EPI_ISL_17795121,
EPI_ISL_17795285, EPI_ISL_17795326, EPI_ISL_17795407,
EPI_ISL_17795619, EPI_ISL_17795793, EPI_ISL_17801772,
EPI_ISL_17801786, EPI_ISL_17801833, EPI_ISL_17801836,
EPI_ISL_17801868, EPI_ISL_17801969, EPI_ISL_17808076,
EPI_ISL_17808261-17808262, EPI_ISL_17808266, EPI_ISL_17808321,
EPI_ISL_17811007, EPI_ISL_17811090-17811091, EPI_ISL_17811119,
EPI_ISL_17811164, EPI_ISL_17811167, EPI_ISL_17811247,
EPI_ISL_17811336, EPI_ISL_17811718, EPI_ISL_17815537,
EPI_ISL_17815673, EPI_ISL_17816592, EPI_ISL_17816963,
EPI_ISL_17816980, EPI_ISL_17816982, EPI_ISL_17817007,
EPI_ISL_17817025, EPI_ISL_17830325, EPI_ISL_17830338,
EPI_ISL_17830393, EPI_ISL_17830457, EPI_ISL_17836287,
EPI_ISL_17836295, EPI_ISL_17836323, EPI_ISL_17836525,
EPI_ISL_17836794, EPI_ISL_17836935, EPI_ISL_17836975,
EPI_ISL_17837014, EPI_ISL_17837760, EPI_ISL_17837763,
EPI_ISL_17850320, EPI_ISL_17850422, EPI_ISL_17850586,
EPI_ISL_17850858, EPI_ISL_17850863, EPI_ISL_17854147,
EPI_ISL_17854305, EPI_ISL_17856447, EPI_ISL_17857195,
EPI_ISL_17884046, EPI_ISL_17951211, EPI_ISL_17951268,
EPI_ISL_17951317, EPI_ISL_17951335, EPI_ISL_17952752,
EPI_ISL_17953116, EPI_ISL_17954678, EPI_ISL_17954948,
EPI_ISL_17956629-17956633, EPI_ISL_17956718, EPI_ISL_17956804,
EPI_ISL_17956973, EPI_ISL_17957006, EPI_ISL_17957068,
EPI_ISL_17957078, EPI_ISL_17957118, EPI_ISL_17957163,
EPI_ISL_17959335
</details>

Countries: 8
![Schermata 2023-07-05 alle 16 46 13](https://github.com/cov-lineages/pango-designation/assets/87669813/b717638e-eab3-4cd5-b778-4937f04c7523)

Growth advantage Comparing it to EG.5.1.1 i think it is useful to look at chinese regions where it circualtes the most: 
Hubei 
![Schermata 2023-07-05 alle 16 52 59](https://github.com/cov-lineages/pango-designation/assets/87669813/a8074a48-937c-415e-bab0-81abaccd7787)
Shanghai
![Schermata 2023-07-05 alle 16 54 01](https://github.com/cov-lineages/pango-designation/assets/87669813/715e19f1-0a20-4ac2-bcec-f7f56fd2e316)
Although it seems slower than EG.5.1.1 the Upper confidential interval does not assign it very far from it.

To understand exactly  what this growth disadvantage could mean just look at [#Collection127](https://cov-spectrum.org/collections/127) by @alurqu :
![Schermata 2023-07-05 alle 16 59 30](https://github.com/cov-lineages/pango-designation/assets/87669813/b106de19-cbc8-459f-9e3f-b2f1f0d7a3e7)

It represents a clear 16% of growth advantage against [Omicron](https://cov-spectrum.org/explore/China/AllSamples/from%3D2023-04-01%26to%3D2023-06-28/variants?aaMutations=S%3AN679K&aaMutations1=N%3AK256R&analysisMode=CompareToBaseline&) lineages circulating as today
![Schermata 2023-07-05 alle 17 00 13](https://github.com/cov-lineages/pango-designation/assets/87669813/200f01b7-21c1-438b-965a-49f2c8fefd65)

**Comment by BorisUitham** [comment]
Weird how there is only still 2 456l sequences, those seem to do well in eg and fl lineages

**Comment by FedeGueli** [comment]
Addendum : the main branch of this lineage got Spike_V1129I
It counts 59 sequences more than half from Hubei.
It has a slight advantage on parental lineage:
![Schermata 2023-07-05 alle 18 58 33](https://github.com/cov-lineages/pango-designation/assets/87669813/0643e958-53e0-49a3-995e-d4cb3d222f36)
https://cov-spectrum.org/explore/China/AllSamples/from%3D2023-04-01%26to%3D2023-06-28/variants?aaMutations=N%3AK256R&aaMutations1=S%3AV1129I%2CN%3A256R&analysisMode=CompareToBaseline&

**Comment by Over-There-Is** [comment]
208

**Comment by Over-There-Is** [comment]
218

**Comment by Over-There-Is** [comment]
239

**Comment by FedeGueli** [comment]
cc @corneliusroemer this is big and growing

**Comment by FedeGueli** [comment]
> another spike mutation emerged: `S:R1014K(G24603A)`

It wss already in a BA.5 sublineage (lemme check which one) and we also identified some possible functions of it (i ll update this later)

**Comment by FedeGueli** [comment]
![Schermata 2023-08-10 alle 00 17 29](https://github.com/cov-lineages/pango-designation/assets/87669813/2096a448-4965-430a-9809-a09571d98ffe)
Most of the recent samples come from the S:V1129I branch.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37980_40f9b0.json?label=id:node_6826695

**Comment by FedeGueli** [comment]
This is slowing down https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=G16741T%2CA29040G%2CT28297C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
designated FL.4.10 via  https://github.com/cov-lineages/pango-designation/commit/1403582daca652ff33227de157a09b16add58a8d
please add milestone
