### ISSUE TITLE
GE.1 with S:T732I 106 seq.

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2088]
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/ac6e6aa7-7d8f-47e4-a108-70ad8f2dc197)
transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/102
tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1262e_869630.json?c=gt-S_732&label=id:node_7046568
query: A17674G,C23757T, T24127C

**Comment by FedeGueli** [comment]
Designated GE.1.3 Milestone added from the original issue https://github.com/sars-cov-2-variants/lineage-proposals/issues/102

**Comment by FedeGueli** [comment]
https://github.com/cov-lineages/pango-designation/commit/cffd0e3b3e3096c90628178666413149aef1b1bc
