### ISSUE TITLE
XBB.1.5.5 sublineage with S:G181V (114 seqs mainly in Japan)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#2090]
*Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/333
Defining mutations: XBB.1.5.5>C7002T (ORF1a:S2246L) >C5506T, G22104T(S:G181V)
GISAID query: C5506T, C7002T, G22104T, A25104T
Earliest seq: 2023-04-14 (US, EPI_ISL_17861832)
Most recent seq: 2023-06-24 (Japan, EPI_ISL_17959003)
Countries detected: Japan (76), Luxemburg (3), China (1), US (1), Australia (1), South Korea (1)

Usher Tree:
<img width="710" alt="屏幕截图 2023-07-12 022227" src="https://github.com/cov-lineages/pango-designation/assets/121703496/abb9f0ed-4d97-4734-a121-19ccf785d11e">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d5f9_d9d8f0.json

Another S:G181 mutation, which is considered to improve the fitness notably (Bloom and Neher 2023)

![251184784-3901b633-f007-499e-a3b1-e7663a624ed2](https://github.com/cov-lineages/pango-designation/assets/121703496/e4825aa4-bcbd-4d5b-839a-c8bcf14f523f)

(https://jbloomlab.github.io/SARS2-mut-fitness/S.html)

Notice that the sublineage increases notably (mainly in Japan), especially the branch with ORF7a: T39I (C27509T)
![251185734-c9b172ce-4af3-47fc-abd2-710dc7ce92a0 (1)](https://github.com/cov-lineages/pango-designation/assets/121703496/db838245-6e94-4234-b025-d9ec9a11214b)

Genomes:
EPI_ISL_17633136, EPI_ISL_17633311, EPI_ISL_17633332, EPI_ISL_17718947, EPI_ISL_17741819, EPI_ISL_17775019-17775021,
EPI_ISL_17780108, EPI_ISL_17780112, EPI_ISL_17780130, EPI_ISL_17780137, EPI_ISL_17780147, EPI_ISL_17780158, EPI_ISL_17780181, EPI_ISL_17803856, EPI_ISL_17803868-17803869, EPI_ISL_17803885, EPI_ISL_17813818, EPI_ISL_17819774,
EPI_ISL_17819779, EPI_ISL_17820030-17820037, EPI_ISL_17820085, EPI_ISL_17836876, EPI_ISL_17861832, EPI_ISL_17880156,
EPI_ISL_17880465, EPI_ISL_17881418, EPI_ISL_17881870, EPI_ISL_17881961, EPI_ISL_17881987, EPI_ISL_17882197, EPI_ISL_17882267, EPI_ISL_17882367, EPI_ISL_17882412, EPI_ISL_17882547, EPI_ISL_17882627, EPI_ISL_17882675,
EPI_ISL_17883132, EPI_ISL_17883144, EPI_ISL_17883350, EPI_ISL_17883387, EPI_ISL_17883749, EPI_ISL_17883881,
EPI_ISL_17941083, EPI_ISL_17941085, EPI_ISL_17941108, EPI_ISL_17941164, EPI_ISL_17952676, EPI_ISL_17957648,
EPI_ISL_17958631, EPI_ISL_17958652, EPI_ISL_17958688, EPI_ISL_17958729-17958731, EPI_ISL_17958997-17959001, EPI_ISL_17959003, EPI_ISL_17960014, EPI_ISL_17960060, EPI_ISL_17960103, EPI_ISL_17966919, EPI_ISL_17973123, EPI_ISL_17973143, EPI_ISL_17973170, EPI_ISL_17973209, EPI_ISL_17973235, EPI_ISL_17973288, EPI_ISL_17973305, EPI_ISL_17978084, EPI_ISL_17978122, EPI_ISL_17978736, EPI_ISL_17978786, EPI_ISL_17978809

**Comment by HynnSpylor** [comment]
114 seqs now

**Comment by DailyCovidCases** [comment]
Please close this issue
