### ISSUE TITLE
XBB.1.16 gained S:P521S and S:K147N (37 seqs - 8 countries as 12/07)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2092]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/374

Thanks to [olias120676](https://github.com/olias120676) double mutations [tracker tool ](https://ukcovid.xyz/spike-combo.php?type=multi&mincount=2)that tracks double S mutation in Uk i found this lineage that has two mutations in the spike known to be beneficial.

Defining mutations:
**XBB.1.16 > C27513T > S:P521S (C23123T), T10756C, T14067C, S:K147N (A22003T)**

Gisaid query: **C23123T, T10756C, T14067C**

Samples:34
First:
hCoV-19/Portugal/PT48089/2023 | Original | EPI_ISL_17720216 | 2023-05-15
Last:
hCoV-19/USA/NY-GBW-H20-310-6255/2023 | Original | EPI_ISL_17960219 | 2023-06-23 (traveller from Sweden)

DS
EPI_ISL_17720216, EPI_ISL_17780601, EPI_ISL_17787041,
EPI_ISL_17791824, EPI_ISL_17791888, EPI_ISL_17808963,
EPI_ISL_17816718, EPI_ISL_17826679, EPI_ISL_17856646,
EPI_ISL_17880986, EPI_ISL_17885012, EPI_ISL_17960180,
EPI_ISL_17960219, EPI_ISL_17960274, EPI_ISL_17960308,
EPI_ISL_17960318, EPI_ISL_17970759

Countries: 
8 (Wales, England, Us, Ireland, Portugal, Netherlands, Austria SOuth Korea

Tree:
![Schermata 2023-07-12 alle 16 50 51](https://github.com/cov-lineages/pango-designation/assets/87669813/001b27a8-c4f3-4207-a6ae-b1800ec575bb)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_285b7_ebd190.json?label=id:node_10536614

**Comment by ryhisner** [comment]
In addition to the 16 sequences uploaded today from Wales, there are now three sequences from Ireland. Collection dates June 25, 27, 29.
EPI_ISL_17980963, EPI_ISL_17980964, EPI_ISL_17980967

**Comment by FedeGueli** [comment]
Thx @ryhisner it seems fast

**Comment by corneliusroemer** [comment]
C27513T was also on that BA.5.2 branch
<img width="1641" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/bdb03080-9636-43f3-8d72-fac0ce0fd47f">
