### ISSUE TITLE
XBB.1.5+Orf1a:P2287S+S:N185D(16 seqs, Canada) and its potential recombinant with GK.1 (9 seqs, 5 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2093]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/396
XBB.1.5+C4586T,T16974C,C7124T(Orf1a:P2287S),A22115G(S:N185D)

GISAID query: T16974C,A22115G,-C23673T
No. of seqs: 16(Canada)
First: EPI_ISL_17590678, 2023-4-17
Latest: EPI_ISL_17701147, 2023-5-10

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f152_e51990.json?c=gt-S_185&label=id:node_6926286&showBranchLabels=all)

Most samples gets S:S940F additionally.

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/bfc4fe28-5b7a-4fe2-868c-79c94e5e740b)

GK.1+T16974C,A22115G(S:N185D)

GISAID query: T16974C,A22115G,C23673T

No. of seqs: 9(Dominician Rep 1 France 2 Spain 2 Brazil 1 Canada 3)
First: EPI_ISL_17948645, Spain, 2023-5-17
Latest: EPI_ISL_17976067, Dominician Rep, 2023-6-27

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice6_genome_23b5d_e49c60.json?branchLabel=Spike%20mutations&label=id:node_6921738&showBranchLabels=all)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/7f338cac-cd02-434b-8fdc-109d08edecfb)

I suppose it is a recombinant, because they have the common T16974C, which is rare with S:N185D samples(only appears in these 2 lineages). Also both GK.1 and the proposed XBB.1.5 branch don't have additional mutations between 16974 and 22115, so it's possible to be a recombinant.

Also its pattern satisfies a pattern that it emerges in some undersampled areas, and outputs early the weak version of XBB.1.5+S:N185D to Canada only and lately the powerful recombinant (S:185D, with additional S:455,456,704 from GK.1) to multiple countries.

Breakpoint shall be between 12468 and 16973, and breakpoint 2 between 22116 and 22623, as GK.1 has G12467T and C22624T.

**Comment by aviczhl2** [comment]
It seems that it is designated as GK.1.2, Brazil. 

However there's only 1 seq from Brazil.

**Comment by FedeGueli** [comment]
https://github.com/cov-lineages/pango-designation/commit/7afb37ca3526a5b03b8cfb64f4e748c4b3cc2fbb

**Comment by aviczhl2** [comment]
@corneliusroemer  There's only 1/9 of GK.1.2 coming from Brazil, and it's not the earlist one. Why can we jump into conclusion that it is from Brazil?

**Comment by corneliusroemer** [comment]
XBB.1.5.70 is very much most common in Brazil, and Brazil doesn't sequence much, so having 1 sequence from Brazil is quite a lot. Also very early sequences are from Brazil. These country-notes in lineage_notes.txt don't mean much in any case, we could also leave them out

**Comment by corneliusroemer** [comment]
This issue wasn't actually about 2093, removing it from lineage notes.

In the future, it's helpful if each issue is about one lineage. The recombinant part (which I don't think is one, at least there's no strong evidence) would have been left out of this issue.
