### ISSUE TITLE
FY.5 (XBB.1.22.1 + S:K478R) Sublineage with S:L176F, ORF9b:S6N (42 seq, Aug 18)--1st proposed by @HynnSpylor

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2101]
### Credit to @HynnSpylor for first proposing this branch
**Description**
**Sub-lineage of:** FY.5 (XBB.1.22.1.5 = XBB.1.22.1 + S:K478R)
**Earliest sequence:** 2023-3-25, Indonesia — EPI_ISL_17696519
**Most recent sequence:** 2023-7-4, Australia, New South Wales — EPI_ISL_17985081, EPI_ISL_17985085
**Countries circulating:** Indonesia (6), Australia (5), USA (5—one from Taiwan traveler), Austria (2), Belgium (1), Canada (1), England (1), New Zealand (1), Singapore (1), South Korea (1), Spain (1)
**Number of Sequences:** 25
**GISAID Nucleotide Query:** C22088T, A22161G, G28300A
**CovSpectrum Query:** Nextcladepangolineage:
**Substitutions on top of FY.5:**
**Spike:** L176F
**ORF9b:** S6N
**Nucleotide:** C22088T, G28300A

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/FY.5_L176F__ORF9b_S6N.json?c=gt-nuc_28300&label=id:node_2946047

<img width="1450" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/ca23d1f9-f86a-4deb-a422-e944f8b5beb0">

**Evidence**
This lineage appeared early on in Indonesia, but Indonesia's sequencing has decreased markedly and also are often uploaded months after they are collected, so it could be growing under the radar in Indonesia. Yesterday (July 14) the three sequences from Australia were uploaded and the first sequence from Spain showed up as well. The main reason I find this branch intriguing is the ORF9b:S6N mutation. In combination with ORF9b:I5T, it creates two additional overlapping suboptimal TRS-B motifs for ORF9b, one from 28294-28301 and another from 28298-28305. Both are near ORF9b:M8, which composes an in-frame start codon for a slightly truncated version of ORF9b.  

<img width="554" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/b8bdd7b3-54cb-41a7-91f4-688b70f704e0">

I call these novel suboptimal ORF9b TRS's 3 and 4 because these are in addition to two other suboptimal novel ORF9b TRS motifs that I've discussed before, namely 28282-28289 (which was significantly enhanced in Alpha by the triple-nucleotide N:D3L mutation) and 28303-28310 (which is enhanced by C28311T in all Omicron and even more by C28312T in BQ* lineages and in a small but increasing proportion of XBB* sequences). 

<img width="554" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/f47b55f0-6c5a-4fe8-846f-8675a4666c5f">

The canonical TRS shared by N and ORF9b itself has a 2nd, overlapping suboptimal TRS, so in some sense, these could be called the 5th and 6th TRS’s for ORF9b.

<img width="554" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/a01bc9ab-ac05-454a-834f-f2b4d5847763">

If this mutation grows in prevalence, it will be about the 12th indication of the importance of ORF9b, which I think is a very important but overlooked protein. I discussed the other pieces of evidence for ORF9b's importance in this marathon, 59-tweet thread, which probably no one made it to the end of. https://twitter.com/LongDesertTrain/status/1673488090957004802
 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17655094, EPI_ISL_17696519, EPI_ISL_17736313, EPI_ISL_17740666, EPI_ISL_17793439, EPI_ISL_17815049, EPI_ISL_17815873, EPI_ISL_17832385, EPI_ISL_17833340, EPI_ISL_17833345, EPI_ISL_17835856, EPI_ISL_17838373, EPI_ISL_17854290, EPI_ISL_17879961, EPI_ISL_17881057, EPI_ISL_17885635, EPI_ISL_17952342, EPI_ISL_17953395, EPI_ISL_17961839, EPI_ISL_17963006, EPI_ISL_17965649, EPI_ISL_17985018, EPI_ISL_17985081, EPI_ISL_17985085, EPI_ISL_17987386
</details>

**Comment by FedeGueli** [comment]
26 *1 from finland

**Comment by ryhisner** [comment]
Another from Indonesia showed up today on the S:I468V branch but with an additional nine nucleotide mutations (4 non-synonymous). Collected June 8. EPI_ISL_17997233
<img width="1488" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/e1701baf-a5c4-41ca-be40-1ec56954fa97">

**Comment by HynnSpylor** [comment]
Ah it is firstly proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/267
But I ignored the ORF9b mutation (as Usher not shown)

**Comment by HynnSpylor** [comment]
now it reaches 42
and there are some further branches, including get S:K182Q (6seqs) and further get S:N211Y (3 seqs in Canada)
<img width="906" alt="屏幕截图 2023-08-16 160751" src="https://github.com/cov-lineages/pango-designation/assets/121703496/c9a5526d-32e2-4749-965c-76f71282a180">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c31a_c81c10.json?c=gt-S_182

**Comment by FedeGueli** [comment]
Ping Cornelius this is adding further NTD  mutations.

**Comment by FedeGueli** [comment]
This now is 71

**Comment by FedeGueli** [comment]
Slowed down no recent sample from more than one month i suggest to close this down.

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
Please close this issue
