### ISSUE TITLE
POSSIBLE NEW P.1 SUB-LINEAGE (P.1.X) DOUBLE SPIKE MUTANT: R246G and N679K AND CIRCULATING PREDOMINANTLY IN PERU 

### ISSUE THREAD

**Issue by Vjimenez-vasquez** [cov-lineages/pango-designation#212]
New lineage proposal
By Group of Genomic Surveillance INS-PERU

Description
Sub-lineage of: P.1 
Earliest sequence: 2021-05-07
Most recent sequence: 2021-08-27
Countries circulating: Peru, Chile, Ecuador, Italy, USA, Switzerland (121 genomes) 

This is a sub-linage of P.1 and is classified as P.1.4 by PANGO algorithm, however it contains one additional spike mutation at position 246, R246G. This samples does not form a clade 
with current P.1.4. Additionally, we have noticed that Peruvian sequences are misclassified by PANGO.  

Conserved Spike mutations : R246G and N679K
Conserved ORF3a mutations : S74F and T151I

Genomes
[metadata.csv.txt](https://github.com/cov-lineages/pango-designation/files/7123353/metadata.csv.txt)

Evidence
[proposal_P.1.X.pdf](https://github.com/cov-lineages/pango-designation/files/7123354/proposal_P.1.X.pdf)
![proposal_P 1 X](https://user-images.githubusercontent.com/89874227/132387844-b09a2030-762d-4891-b97b-816ff6bb44db.png)

P.1.X

**Comment by chrisruis** [comment]
Thanks @Vjimenez-vasquez We've added this as P.1.12 in [v1.2.77](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.77)

I think we need to work on the P.1 region of the tree, watch this space!

**Comment by Vjimenez-vasquez** [comment]
Thanks @chrisruis. Here in Peru the **"Group of Genomic Surveillance INS-PERU"** were under the expectation that the PANGO-COMITTEE accept our proposal. We will continue working on this new lineage.
