### ISSUE TITLE
xbb.1.9.2 with ORF1a:S302F, S:K478R, S:N185S (seq. 75)

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2121]
transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/99
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/90f88bfe-8e3d-44a7-ac18-ea049dbdd283)
query: C1170T, C2485T, A22116G

**Comment by FedeGueli** [comment]
beyond EG.2 seems 478R was not very successful on XBB.1.9 backbone
