### ISSUE TITLE
(GF.1)#2086 with Orf8 frameshift . (11 seqs, China)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2122]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/215

#2086 +A9153G(Orf1a:Q2963R)+del27903_27910(Orf8 frameshift, causing the stop codon to move, effectively creating a brand new Orf8 that stops at 20)

GISAID query: A9153G, del27903_27910
No. of seqs: 10(Shanghai, Jiangsu)

First seq: EPI_ISL_17637420, Jiangsu, 2023-4-20
Latest: EPI_ISL_17956810, Shanghai, 2023-6-20

Usher treats this as Orf8:V5I/G27906A as it cannot handle frameshifts.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_1f652_c8f0e0.json?label=id:node_7056634)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/82482b81-41a0-4dba-9bc3-ff1ee6c96d50)

This Orf8 frameshift is actually across all variants. But only this lineage is active so proposed this one.

**Comment by silcn** [comment]
The new ORF8 is 17AA long, still pretty short. Stop codon is at 27953-27955, between ORF8:20-21.
<img width="597" alt="newstopcodon" src="https://github.com/cov-lineages/pango-designation/assets/42699509/7c1c1cc5-e7f0-4217-8fc0-b3a3e9ab9a5d">

**Comment by aviczhl2** [comment]
Seems dead
