### ISSUE TITLE
Possible new B.1.617.2 (Delta) sublineage circulating predominantly in UK and Ireland with mutation Spike:G446V and ORF1a:T814I

### ISSUE THREAD

**Issue by banijolly** [cov-lineages/pango-designation#214]
Sublineage of: AY.4
Countries circulating: predominantly in the UK (Scotland and England) and Ireland. Other countries include USA, Gibraltar, Finland, Italy, Poland, Canada and Australia. The sample collection dates are from June-August 2021, which makes the cluster fairly recent. 

The subcluster of genomes contains the spike mutation G446S along with ORF1ab mutations T814I and I6704L.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_647_a47770.json

![image](https://user-images.githubusercontent.com/47384613/132741795-ca8c8b7a-ca43-4cd6-b098-ad9a3930cc9a.png)
![image](https://user-images.githubusercontent.com/47384613/132738249-36a477f0-d8c3-4fd0-b50b-8bf8248ca898.png)

And it appears to be branching out of the AY.4 cluster, as they all have ORF1ab:A2529V also in common:

![image](https://user-images.githubusercontent.com/47384613/132739713-d25060fa-c9e6-4b16-995f-c70a77cba579.png)

Not sure if this classifies to be a sub-clade since the number of cases in these regions is pretty low if we go by proportions.

Genomes used to build Usher tree: 
[Accession_IDs.txt](https://github.com/cov-lineages/pango-designation/files/7138894/Accession_IDs.txt)

**Comment by chrisruis** [comment]
Thanks @banijolly We agree this looks like it's in AY.4 so we've added this as AY.4.1 in [v1.2.78](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.78)
