### ISSUE TITLE
EG.5.2 sublineage with ORF1a:P748L, ORF1a:S1905F, and S:L455F (12 seq. Canada, USA)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#2141]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/443
![1](https://github.com/cov-lineages/pango-designation/assets/115189228/97095efc-031d-4e1c-b74e-f5e064f6f553)
![](https://user-images.githubusercontent.com/87669813/255896352-a6253c50-2b1b-4338-908c-9a10ec0093a7.png)
![](https://user-images.githubusercontent.com/87669813/255896882-cf69c68b-4552-4c0d-9080-0cca6dad9f88.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_41326_fbadf0.json?c=gt-S_455&label=id:node_6703338
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AEG.5.2*%26S%3AL455F&

**Comment by corneliusroemer** [comment]
Let's wait until it's more than 1 lab and ideally more than just Canada which sequences maybe the most of any country in the world per capita at the moment.

**Comment by FedeGueli** [comment]
> Let's wait until it's more than 1 lab and ideally more than just Canada which sequences maybe the most of any country in the world per capita at the moment.

Ninth sequence came from Michigan after a 4 week Hyatus. I would wait more sequences to come, it seems quite slow.

**Comment by aviczhl2** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/24de9763-adb6-49bb-9193-87023ba85233)
+3 USA, without orf1b:P976S

**Comment by FedeGueli** [comment]
Thx @aviczhl2 

@oobb45729 i suggest to edit the proposal leaving alone the query G2086A, C2508T, C5979T  without orf1b:P967S. Now this went to 12

**Comment by aviczhl2** [comment]
17 now
