### ISSUE TITLE
FL.21 sublineage with S:D1084N circulating in South Korea(112 seq, 6 countries) with a sub branch with S:E554A (29 seqs, 2 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2143]
FL.21>G24812A(S:D1084N)

Transferred from sars-cov-2-variants/lineage-proposals#310
The second largest branch of FL.21, mainly circulating in South Korea.

Query: A10564T, G24812A
Query for the sub branch with **S:E554A**: A10564T, G24812A, A23223C

Earliest Sequence: 03-15 South Korea EPI_ISL_17416089
Latest Sequence: 07-04 Miyagi, Japan EPI_ISL_18040361
Regions Detected: **South Korea** 103(2 from **Hungary**, 1 from **Vietnam**), **US** 5(Illinois 1, New York 4[2 from **France**, 2 airport screening]), **Japan** 4(Miyagi 3, Aichi 1)

[usher](https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_1644e_1aac30.json?label=id:node_6650137)
![2023-07-26 (69)](https://github.com/cov-lineages/pango-designation/assets/38100637/1a685e08-b4df-4c0e-a522-904e1d6067d6)

And also 6 Korean sequences with only spike gene (2 /w S:E554A):
Query: -A10564T, T23018C, T23019C, G24812A, Asia / South Korea
Query for the sub branch with **S:E554A**: -A10564T, G24812A, A23223C, Asia / South Korea
<details><summary>Sequences:</summary>

EPI_ISL_17416089, EPI_ISL_17474202, EPI_ISL_17538340,
EPI_ISL_17538970, EPI_ISL_17563149, EPI_ISL_17563510-17563511,
EPI_ISL_17563894, EPI_ISL_17564203, EPI_ISL_17604126,
EPI_ISL_17604319, EPI_ISL_17604509, EPI_ISL_17605279,
EPI_ISL_17647080, EPI_ISL_17647312, EPI_ISL_17647712,
EPI_ISL_17648476, EPI_ISL_17677458, EPI_ISL_17677474,
EPI_ISL_17690590, EPI_ISL_17690642, EPI_ISL_17690852-17690853,
EPI_ISL_17690907, EPI_ISL_17691393, EPI_ISL_17691407,
EPI_ISL_17691481, EPI_ISL_17691511, EPI_ISL_17691576,
EPI_ISL_17723168, EPI_ISL_17723763, EPI_ISL_17723886-17723887,
EPI_ISL_17723907, EPI_ISL_17730353, EPI_ISL_17730809,
EPI_ISL_17740690-17740691, EPI_ISL_17741074, EPI_ISL_17741235,
EPI_ISL_17741293, EPI_ISL_17741444, EPI_ISL_17778935,
EPI_ISL_17778949, EPI_ISL_17779369, EPI_ISL_17779508,
EPI_ISL_17779662, EPI_ISL_17779670, EPI_ISL_17779810,
EPI_ISL_17791879, EPI_ISL_17791929, EPI_ISL_17792387,
EPI_ISL_17792406, EPI_ISL_17804392, EPI_ISL_17806987,
EPI_ISL_17807266, EPI_ISL_17807326, EPI_ISL_17807735,
EPI_ISL_17807739, EPI_ISL_17807799, EPI_ISL_17807913,
EPI_ISL_17816709-17816710, EPI_ISL_17816741, EPI_ISL_17834671,
EPI_ISL_17834716, EPI_ISL_17834802, EPI_ISL_17834901,
EPI_ISL_17835089, EPI_ISL_17835341, EPI_ISL_17835526,
EPI_ISL_17835536, EPI_ISL_17835572, EPI_ISL_17835723,
EPI_ISL_17835728, EPI_ISL_17835771, EPI_ISL_17927834,
EPI_ISL_17927968, EPI_ISL_17928017, EPI_ISL_17928020,
EPI_ISL_17928022, EPI_ISL_17930351-17930352, EPI_ISL_17930524,
EPI_ISL_17930738, EPI_ISL_17930770, EPI_ISL_17930788,
EPI_ISL_17969516, EPI_ISL_17969649, EPI_ISL_17970094,
EPI_ISL_17970231, EPI_ISL_17970350, EPI_ISL_17970391,
EPI_ISL_17983473, EPI_ISL_17983597, EPI_ISL_17983631,
EPI_ISL_17983674, EPI_ISL_17984145, EPI_ISL_17984409,
EPI_ISL_18006638, EPI_ISL_18006680, EPI_ISL_18006973,
EPI_ISL_18030754, EPI_ISL_18030792, EPI_ISL_18031032,
EPI_ISL_18031269, EPI_ISL_18031381, EPI_ISL_18031407,
EPI_ISL_18031544, EPI_ISL_18031593, EPI_ISL_18038785,
EPI_ISL_18040361

Spike-only sequences:
EPI_ISL_17725828, EPI_ISL_17725890, EPI_ISL_17725987,
EPI_ISL_17812000, EPI_ISL_17973587, EPI_ISL_18032896
</details>

**Comment by corneliusroemer** [comment]
Designated, in general I'm careful with South Korean lineages like this as South Korea sequences _sooo_ much more than almost any other country. In general, I'd wait for there to be significant outside South Korea spread before designation.
