### ISSUE TITLE
Undesignated XBB.1.9.1's C7165T branch (878 seqs, mainly in Ukraine, 31 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2144]
_Transferred from sars-cov-2-variants/lineage-proposals#315_

**Defining Mutations:** `XBB.1.9.1` > `C7165T`

**Query:** `C11956T, C7165T, -C1380T` [filter: `Lineage:XBB.1.9.1`, `host: Human`]
**Query (alt):** `G5720A, C11956T, C7165T, -C1380T, -T1753C, -G2235A, -C2147T, -A3027G, -G3242A, -G3539T, -T4579A, -C4999T, -C5812T, -C8772T, -C13430A, -G13726A, -C14322T, -G16741T, -T17328G, -C17766T, -C21622A, -C22971A -C29311T, -C29358T, -T29691C` [in case lineage filter does not work, `host: Human`]

**Earliest seq:** 2023-01-27 (`EPI_ISL_17076139`, Ukraine)
**Latest seq:** 2023-07-07 (`EPI_ISL_17990687`, Sweden)

**Sampled Countries:** Austria, Australia, Belgium, Canada, China, Czech, Finland, France, Germany, Indonesia, Iran, Ireland, Israel, Italy, Japan, Luxembourg, Netherlands, Malaysia, New Zealand, Norway, Poland, Slovenia, South Korea, Spain, Sweden, Switzerland, UK, Ukraine, USA

<details><summary>Genomes: </summary>

`EPI_ISL_17076139, EPI_ISL_17165443, EPI_ISL_17176236, EPI_ISL_17193904, EPI_ISL_17238761, EPI_ISL_17259711, EPI_ISL_17263777, EPI_ISL_17267115, EPI_ISL_17268601-17268602, EPI_ISL_17284071, EPI_ISL_17297196, EPI_ISL_17297614, EPI_ISL_17328145, EPI_ISL_17347587, EPI_ISL_17347589-17347590, EPI_ISL_17347593, EPI_ISL_17347598, EPI_ISL_17349409, EPI_ISL_17385826, EPI_ISL_17388102, EPI_ISL_17389273, EPI_ISL_17390612-17390613, EPI_ISL_17390708-17390712, EPI_ISL_17390714-17390715, EPI_ISL_17390721-17390723, EPI_ISL_17390725, EPI_ISL_17394650, EPI_ISL_17401040, EPI_ISL_17418966, EPI_ISL_17418968, EPI_ISL_17418978, EPI_ISL_17441215, EPI_ISL_17465267, EPI_ISL_17466191-17466192, EPI_ISL_17468788, EPI_ISL_17468795, EPI_ISL_17482504, EPI_ISL_17482510, EPI_ISL_17482867, EPI_ISL_17484709, EPI_ISL_17485117, EPI_ISL_17485367, EPI_ISL_17490930, EPI_ISL_17492049, EPI_ISL_17492052, EPI_ISL_17492065, EPI_ISL_17492115, EPI_ISL_17492117-17492119, EPI_ISL_17492130, EPI_ISL_17492133-17492134, EPI_ISL_17492136-17492137, EPI_ISL_17492142, EPI_ISL_17495578, EPI_ISL_17495639, EPI_ISL_17495660-17495661, EPI_ISL_17500220, EPI_ISL_17501278, EPI_ISL_17501292, EPI_ISL_17501320, EPI_ISL_17501322, EPI_ISL_17505243, EPI_ISL_17505581, EPI_ISL_17505937, EPI_ISL_17505939, EPI_ISL_17505941-17505942, EPI_ISL_17505945, EPI_ISL_17509082, EPI_ISL_17521069, EPI_ISL_17521084, EPI_ISL_17521086, EPI_ISL_17521089, EPI_ISL_17521105, EPI_ISL_17521112-17521113, EPI_ISL_17521132-17521133, EPI_ISL_17521178, EPI_ISL_17521187, EPI_ISL_17521293, EPI_ISL_17526151, EPI_ISL_17529336, EPI_ISL_17535509, EPI_ISL_17535511, EPI_ISL_17535887, EPI_ISL_17540000, EPI_ISL_17540233, EPI_ISL_17543404, EPI_ISL_17543406, EPI_ISL_17543527, EPI_ISL_17543535-17543539, EPI_ISL_17543547, EPI_ISL_17543549, EPI_ISL_17543551, EPI_ISL_17543873, EPI_ISL_17544808, EPI_ISL_17547202, EPI_ISL_17548099, EPI_ISL_17548765, EPI_ISL_17549067, EPI_ISL_17550657, EPI_ISL_17556364, EPI_ISL_17556446, EPI_ISL_17558202, EPI_ISL_17558225, EPI_ISL_17558784, EPI_ISL_17562727, EPI_ISL_17567264, EPI_ISL_17583231, EPI_ISL_17583234-17583235, EPI_ISL_17583241-17583242, EPI_ISL_17583245-17583246, EPI_ISL_17583251, EPI_ISL_17583256, EPI_ISL_17583260, EPI_ISL_17585505, EPI_ISL_17590124, EPI_ISL_17590134-17590135, EPI_ISL_17590149, EPI_ISL_17590206, EPI_ISL_17593737, EPI_ISL_17593767, EPI_ISL_17597967, EPI_ISL_17597977, EPI_ISL_17599490, EPI_ISL_17612894, EPI_ISL_17612934, EPI_ISL_17613912, EPI_ISL_17616557, EPI_ISL_17616917, EPI_ISL_17616923, EPI_ISL_17622631, EPI_ISL_17623514, EPI_ISL_17628753, EPI_ISL_17629607, EPI_ISL_17630630-17630631, EPI_ISL_17631082-17631083, EPI_ISL_17637002, EPI_ISL_17637006, EPI_ISL_17637008-17637009, EPI_ISL_17640936, EPI_ISL_17640952, EPI_ISL_17640985, EPI_ISL_17641008, EPI_ISL_17641043, EPI_ISL_17641054-17641055, EPI_ISL_17641059, EPI_ISL_17641062, EPI_ISL_17641069, EPI_ISL_17649114, EPI_ISL_17649764, EPI_ISL_17649773, EPI_ISL_17649775, EPI_ISL_17649781, EPI_ISL_17649830, EPI_ISL_17649833-17649836, EPI_ISL_17649842, EPI_ISL_17649845, EPI_ISL_17649853-17649857, EPI_ISL_17649860, EPI_ISL_17649865-17649867, EPI_ISL_17649870-17649872, EPI_ISL_17650611, EPI_ISL_17650627, EPI_ISL_17650808, EPI_ISL_17650890, EPI_ISL_17653458, EPI_ISL_17655683, EPI_ISL_17655690, EPI_ISL_17655694-17655695, EPI_ISL_17655697, EPI_ISL_17655701, EPI_ISL_17655704, EPI_ISL_17655706, EPI_ISL_17655708, EPI_ISL_17655716, EPI_ISL_17655722-17655724, EPI_ISL_17655726-17655727, EPI_ISL_17655739-17655744, EPI_ISL_17657724, EPI_ISL_17657733, EPI_ISL_17668958, EPI_ISL_17668966, EPI_ISL_17668970, EPI_ISL_17669010, EPI_ISL_17669085, EPI_ISL_17669249, EPI_ISL_17671287, EPI_ISL_17676219, EPI_ISL_17684250, EPI_ISL_17684635, EPI_ISL_17684637-17684639, EPI_ISL_17684644-17684645, EPI_ISL_17684649, EPI_ISL_17684652, EPI_ISL_17684654, EPI_ISL_17684656, EPI_ISL_17684660-17684661, EPI_ISL_17684663-17684664, EPI_ISL_17684666-17684667, EPI_ISL_17684674, EPI_ISL_17684677, EPI_ISL_17685571, EPI_ISL_17689364, EPI_ISL_17689422, EPI_ISL_17689446, EPI_ISL_17693797, EPI_ISL_17695087, EPI_ISL_17695118, EPI_ISL_17695146, EPI_ISL_17696743, EPI_ISL_17697650, EPI_ISL_17697748, EPI_ISL_17699310, EPI_ISL_17705941, EPI_ISL_17711212, EPI_ISL_17711257, EPI_ISL_17711356, EPI_ISL_17711368, EPI_ISL_17711370, EPI_ISL_17711823, EPI_ISL_17711828, EPI_ISL_17713584, EPI_ISL_17715799, EPI_ISL_17716516, EPI_ISL_17718719, EPI_ISL_17722269, EPI_ISL_17722272, EPI_ISL_17722276-17722277, EPI_ISL_17722279-17722281, EPI_ISL_17722288, EPI_ISL_17722290-17722292, EPI_ISL_17722294, EPI_ISL_17725253, EPI_ISL_17732713, EPI_ISL_17732759, EPI_ISL_17732780, EPI_ISL_17741695, EPI_ISL_17741724, EPI_ISL_17742339-17742340, EPI_ISL_17742343-17742349, EPI_ISL_17742352, EPI_ISL_17742361-17742363, EPI_ISL_17742910-17742912, EPI_ISL_17742914, EPI_ISL_17742921, EPI_ISL_17742929, EPI_ISL_17742931, EPI_ISL_17742934-17742935, EPI_ISL_17742954-17742955, EPI_ISL_17742969, EPI_ISL_17763179, EPI_ISL_17769284, EPI_ISL_17769311, EPI_ISL_17769360-17769361, EPI_ISL_17769749, EPI_ISL_17770010, EPI_ISL_17777543, EPI_ISL_17777548, EPI_ISL_17778646, EPI_ISL_17781271, EPI_ISL_17781274-17781276, EPI_ISL_17781280, EPI_ISL_17781282, EPI_ISL_17781285-17781286, EPI_ISL_17781288, EPI_ISL_17781291, EPI_ISL_17782266, EPI_ISL_17784862, EPI_ISL_17785052-17785053, EPI_ISL_17785115, EPI_ISL_17785121, EPI_ISL_17785123, EPI_ISL_17785179, EPI_ISL_17786344, EPI_ISL_17788229, EPI_ISL_17788245, EPI_ISL_17788273, EPI_ISL_17791799, EPI_ISL_17797008-17797009, EPI_ISL_17797011-17797012, EPI_ISL_17797014, EPI_ISL_17797019-17797021, EPI_ISL_17797023, EPI_ISL_17797025, EPI_ISL_17797030, EPI_ISL_17808450, EPI_ISL_17808503, EPI_ISL_17814269-17814270, EPI_ISL_17814289, EPI_ISL_17814298, EPI_ISL_17814300, EPI_ISL_17814304, EPI_ISL_17819939, EPI_ISL_17821153, EPI_ISL_17821155-17821158, EPI_ISL_17821161, EPI_ISL_17821166-17821170, EPI_ISL_17821172, EPI_ISL_17821178, EPI_ISL_17821715-17821718, EPI_ISL_17826892, EPI_ISL_17826916, EPI_ISL_17827085, EPI_ISL_17830373, EPI_ISL_17830515, EPI_ISL_17830521-17830523, EPI_ISL_17830527-17830529, EPI_ISL_17830548, EPI_ISL_17830550, EPI_ISL_17830554, EPI_ISL_17830556-17830559, EPI_ISL_17830566, EPI_ISL_17830568, EPI_ISL_17830570, EPI_ISL_17832643, EPI_ISL_17833425, EPI_ISL_17833429-17833430, EPI_ISL_17833432, EPI_ISL_17833436-17833439, EPI_ISL_17833441, EPI_ISL_17833443, EPI_ISL_17833446-17833447, EPI_ISL_17833449, EPI_ISL_17833455-17833456, EPI_ISL_17833458-17833461, EPI_ISL_17833464, EPI_ISL_17833468, EPI_ISL_17833473, EPI_ISL_17833475, EPI_ISL_17833478-17833486, EPI_ISL_17833489-17833490, EPI_ISL_17833492, EPI_ISL_17833632, EPI_ISL_17835344, EPI_ISL_17836556, EPI_ISL_17850011, EPI_ISL_17850065, EPI_ISL_17850437, EPI_ISL_17850613, EPI_ISL_17850622, EPI_ISL_17855178, EPI_ISL_17855227, EPI_ISL_17859512, EPI_ISL_17880949, EPI_ISL_17881097, EPI_ISL_17881153, EPI_ISL_17881204, EPI_ISL_17882949, EPI_ISL_17883036, EPI_ISL_17884875, EPI_ISL_17884878, EPI_ISL_17884881-17884882, EPI_ISL_17884886-17884887, EPI_ISL_17884890-17884891, EPI_ISL_17884893, EPI_ISL_17884896, EPI_ISL_17884898, EPI_ISL_17884900, EPI_ISL_17884906, EPI_ISL_17884911, EPI_ISL_17884914, EPI_ISL_17949825, EPI_ISL_17949833, EPI_ISL_17960034, EPI_ISL_17962493, EPI_ISL_17962897, EPI_ISL_17964468, EPI_ISL_17966561, EPI_ISL_17971189-17971195, EPI_ISL_17971197-17971203, EPI_ISL_17971206, EPI_ISL_17971210-17971218, EPI_ISL_17971829, EPI_ISL_17972990, EPI_ISL_17973189, EPI_ISL_17976150, EPI_ISL_17980355, EPI_ISL_17982461, EPI_ISL_17982467, EPI_ISL_17982474, EPI_ISL_17982477-17982478, EPI_ISL_17982491-17982492, EPI_ISL_17982495-17982496, EPI_ISL_17985301-17985303, EPI_ISL_17985307-17985310, EPI_ISL_17985312, EPI_ISL_17985317, EPI_ISL_17985326-17985328, EPI_ISL_17985330, EPI_ISL_17985332, EPI_ISL_17985334, EPI_ISL_17985336-17985337, EPI_ISL_17985339, EPI_ISL_17985341-17985347, EPI_ISL_17985352-17985354, EPI_ISL_17985356-17985359, EPI_ISL_17985362, EPI_ISL_17985365, EPI_ISL_17985368-17985370, EPI_ISL_17985963, EPI_ISL_17989638, EPI_ISL_17990675, EPI_ISL_17990687, EPI_ISL_18008298, EPI_ISL_18008313, EPI_ISL_18008315, EPI_ISL_18008317-18008318, EPI_ISL_18008324-18008325, EPI_ISL_18008327, EPI_ISL_18008329-18008333, EPI_ISL_18008335, EPI_ISL_18008342-18008343, EPI_ISL_18008346, EPI_ISL_18008349-18008350, EPI_ISL_18008352-18008354, EPI_ISL_18008356, EPI_ISL_18008358, EPI_ISL_18008361, EPI_ISL_18009741, EPI_ISL_18009765, EPI_ISL_18009768, EPI_ISL_18009777, EPI_ISL_18009801, EPI_ISL_18009826, EPI_ISL_18009838, EPI_ISL_18009851, EPI_ISL_18009861, EPI_ISL_18009879, EPI_ISL_18009926, EPI_ISL_18012995, EPI_ISL_18032299, EPI_ISL_18033432-18033434, EPI_ISL_18033438, EPI_ISL_18033444, EPI_ISL_18033451, EPI_ISL_18033453, EPI_ISL_18033466, EPI_ISL_18033470, EPI_ISL_18033472-18033474, EPI_ISL_18033478, EPI_ISL_18033521-18033522, EPI_ISL_18033619, EPI_ISL_18033662-18033663, EPI_ISL_18034108, EPI_ISL_18034158, EPI_ISL_18034259, EPI_ISL_18034382, EPI_ISL_18034424, EPI_ISL_18034428-18034429, EPI_ISL_18035024, EPI_ISL_18035850, EPI_ISL_18036001, EPI_ISL_18036024`

</details>

<details><summary>Env. seqs from Ukraine: </summary>

`EPI_ISL_17492145, EPI_ISL_17821709-17821710, EPI_ISL_17821712, EPI_ISL_17821714, EPI_ISL_18008230, EPI_ISL_18008235`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31cf1_ff0e80.json?f_userOrOld=uploaded%20sample&label=id:node_6760202

view from XBB.1.9.1 polytomy
![overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/31d7a904-d6b4-492b-bc9e-329ee08a885f)

<details><summary>detailed view from C7165T branch with T478X filter and samples collected since May: </summary>

![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/15faa39f-199e-4264-af24-3532f5fb7c55)
</details>

<details><summary>diversity view from `C7165T` branch with `T478X` filter with updated sequences, now some `T478X` branches seems to cluster</summary>

![478X](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/7b46256f-3c53-4c97-a403-79c5607b6689)
</details>

**Trivia:**
- This branch could be something big in Ukraine (or even Eastern Europe), the query is including 7 env samples from Ukraine if not using host filter.
![intl](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/36590ff0-ec0c-4d0c-8c30-98998b2a6dbb)
- The query is very rough though, it may contain other XBB.1.9.1*/FL* branches with `C7165T`;  Adding alternate query should GISAID lineage assignment not work. This alternate query may also include sequences from other FL* lineages, tried my best to filter them out.

**Comment by Over-There-Is** [comment]
EPI_ISL_18041788 Bucharest, Romania

**Comment by MCB6** [comment]
It seems to have completed its sweep of Ukraine. In today's upload, 13 / 15 late June samples from Ukraine have C7165T, and the geography spans the whole country

**Comment by Over-There-Is** [comment]
Beijing +19

**Comment by Over-There-Is** [comment]
Ukraine +4, Dnipro 2, Rivne 2
(Sweden +2?)

**Comment by Over-There-Is** [comment]
Wien, Österreich+1
Noord Holland, Netherlands+1
Hauts de France, France +1
Ukraine +3, Ivano-Frankivsk 1, Kirovohrad 1, Mykolaiv 1

**Comment by Over-There-Is** [comment]
Stopped growing in Beijing
