### ISSUE TITLE
CH.1.1 on C21811T branch with ORF1a:E974A (nsp3_E156A), S:L858I and N:P80Q/ORF9b:Q77K (257 seqs, mainly in Europe, 27 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2150]
Transferred from sars-cov-2-variants/lineage-proposals#327

**Defining Mutations:** [_on top of `CH.1.1 > C21811T` branch, that is, **sibling to `CH.1.1.11/17/28`**_] > `C2455T` > `A3186C(ORF1a:E974A), C14491T` > `C24134A(**S:L858I**)` > `C28512A(N:P80Q/ORF9b:Q77K)`
**Query:** `C2455T, C14491T, C24134A, C28512A`
**Earliest seq:** 2023-01-20 (`EPI_ISL_17081524`, Bahrain)
**Latest seq:** 2023-07-07 (`EPI_ISL_17986713`, New York, USA)
**Sampled Countries:** Germany (54), Canada (24), France (19), Netherlands (19), USA (16), Sweden (15), Spain (12), Denmark (11), UK (9), Italy (7), Japan (7), Austria (6), Belgium (4), Greece (3), Bahrain (2), China (2), Finland (2), Russia (2), Colombia (1), Israel (1), Luxembourg (1), Norway (1), Poland (1), Slovenia (1), Switzerland (1)

<details><summary>Genomes: </summary>

`EPI_ISL_16981090, EPI_ISL_17003376, EPI_ISL_17008639, EPI_ISL_17025318, EPI_ISL_17025430, EPI_ISL_17027056, EPI_ISL_17070250, EPI_ISL_17081468, EPI_ISL_17081524, EPI_ISL_17155460, EPI_ISL_17174490, EPI_ISL_17186719, EPI_ISL_17186766, EPI_ISL_17186795, EPI_ISL_17199422, EPI_ISL_17204653, EPI_ISL_17210402, EPI_ISL_17213225, EPI_ISL_17232373, EPI_ISL_17242252, EPI_ISL_17242283, EPI_ISL_17248721, EPI_ISL_17256006, EPI_ISL_17256472, EPI_ISL_17270939, EPI_ISL_17270944-17270945, EPI_ISL_17274519, EPI_ISL_17278603, EPI_ISL_17292307, EPI_ISL_17292497, EPI_ISL_17292548, EPI_ISL_17300107, EPI_ISL_17317856, EPI_ISL_17333976, EPI_ISL_17344390, EPI_ISL_17344447, EPI_ISL_17348384, EPI_ISL_17386047, EPI_ISL_17386370, EPI_ISL_17389916, EPI_ISL_17389937, EPI_ISL_17394123, EPI_ISL_17407829, EPI_ISL_17414512, EPI_ISL_17414517, EPI_ISL_17419147, EPI_ISL_17433624, EPI_ISL_17442072, EPI_ISL_17446291, EPI_ISL_17468157, EPI_ISL_17468170, EPI_ISL_17468174, EPI_ISL_17475901, EPI_ISL_17491947, EPI_ISL_17495391, EPI_ISL_17501497, EPI_ISL_17502166, EPI_ISL_17510737, EPI_ISL_17511289, EPI_ISL_17511747, EPI_ISL_17512376, EPI_ISL_17514775, EPI_ISL_17516649-17516650, EPI_ISL_17518335, EPI_ISL_17518540, EPI_ISL_17519394, EPI_ISL_17519888, EPI_ISL_17519890, EPI_ISL_17519898, EPI_ISL_17528868, EPI_ISL_17541338, EPI_ISL_17545498, EPI_ISL_17547507, EPI_ISL_17550318, EPI_ISL_17553689, EPI_ISL_17565407, EPI_ISL_17566336, EPI_ISL_17584841, EPI_ISL_17584870, EPI_ISL_17597812, EPI_ISL_17598313, EPI_ISL_17598333, EPI_ISL_17598372, EPI_ISL_17607832, EPI_ISL_17612944, EPI_ISL_17612955, EPI_ISL_17612968, EPI_ISL_17612976-17612977, EPI_ISL_17612979, EPI_ISL_17613279, EPI_ISL_17613281, EPI_ISL_17625941-17625943, EPI_ISL_17625948, EPI_ISL_17626453, EPI_ISL_17626467, EPI_ISL_17634131, EPI_ISL_17637917, EPI_ISL_17637925-17637927, EPI_ISL_17637929, EPI_ISL_17637932, EPI_ISL_17637937, EPI_ISL_17637939, EPI_ISL_17637943, EPI_ISL_17637948, EPI_ISL_17637955, EPI_ISL_17637958, EPI_ISL_17637960, EPI_ISL_17637972, EPI_ISL_17637979, EPI_ISL_17640796, EPI_ISL_17653087, EPI_ISL_17653165, EPI_ISL_17655311, EPI_ISL_17666689, EPI_ISL_17667597, EPI_ISL_17668772, EPI_ISL_17680201, EPI_ISL_17682391, EPI_ISL_17685448, EPI_ISL_17685551, EPI_ISL_17689069, EPI_ISL_17689078, EPI_ISL_17689085, EPI_ISL_17689105, EPI_ISL_17693972, EPI_ISL_17701067, EPI_ISL_17704564, EPI_ISL_17704656, EPI_ISL_17704660, EPI_ISL_17704668, EPI_ISL_17705025, EPI_ISL_17707778, EPI_ISL_17710668, EPI_ISL_17711050, EPI_ISL_17711061, EPI_ISL_17713827, EPI_ISL_17713839, EPI_ISL_17714166, EPI_ISL_17714169, EPI_ISL_17714197, EPI_ISL_17715275, EPI_ISL_17716157, EPI_ISL_17716266, EPI_ISL_17716273, EPI_ISL_17722205, EPI_ISL_17722832, EPI_ISL_17731486-17731487, EPI_ISL_17731490, EPI_ISL_17737028, EPI_ISL_17741753, EPI_ISL_17743115, EPI_ISL_17743714, EPI_ISL_17763094, EPI_ISL_17769369, EPI_ISL_17769410, EPI_ISL_17769581, EPI_ISL_17776339, EPI_ISL_17776349, EPI_ISL_17776355, EPI_ISL_17776851, EPI_ISL_17780972, EPI_ISL_17786796, EPI_ISL_17787213, EPI_ISL_17787216, EPI_ISL_17787374, EPI_ISL_17788492, EPI_ISL_17789552, EPI_ISL_17789556, EPI_ISL_17803446, EPI_ISL_17803538, EPI_ISL_17804216-17804218, EPI_ISL_17808484, EPI_ISL_17808490, EPI_ISL_17808534, EPI_ISL_17813268, EPI_ISL_17813325-17813326, EPI_ISL_17837361, EPI_ISL_17849240, EPI_ISL_17853740, EPI_ISL_17854709, EPI_ISL_17855318, EPI_ISL_17883464, EPI_ISL_17884608, EPI_ISL_17884957, EPI_ISL_17885485, EPI_ISL_17949111-17949112, EPI_ISL_17950828, EPI_ISL_17950844, EPI_ISL_17960572, EPI_ISL_17960687, EPI_ISL_17960708, EPI_ISL_17974239, EPI_ISL_17977819, EPI_ISL_17977834-17977835, EPI_ISL_17979687, EPI_ISL_17981780, EPI_ISL_17984713, EPI_ISL_17986713, EPI_ISL_17993970, EPI_ISL_17993972-17993973, EPI_ISL_17993975-17993976, EPI_ISL_17993987, EPI_ISL_17996958, EPI_ISL_17996968, EPI_ISL_18042893, EPI_ISL_18042909`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_27491_4d1b50.json?f_userOrOld=uploaded%20sample&label=id:node_7430770

view from `CH.1.1 > C21811T` branch
![poly](https://github.com/cov-lineages/pango-designation/assets/125747944/3c0156b4-7e22-41f7-8fe4-10185d909c8f)

diversity from `C2455T` sub-branch
![diver](https://github.com/cov-lineages/pango-designation/assets/125747944/89f80a12-774a-40f7-9096-65ba041848c4)

**Trivia:**
- The actual UShER assignment has a `S:R346T/C22599G` flip-flop (which is neglected above), probably due to the following seqs:

<details><summary>Potential dropout causing UShER flip-flop, 3 seqs: </summary>

```
Turkey/KSS-UEAH4935030861/2022|EPI_ISL_16414782|2022-12-26
Turkey/KSS-SBU4935144473/2022|EPI_ISL_16414738|2022-12-26
Turkey/KSS-PCTSH4919223903/2022|EPI_ISL_16424226|2022-12-12
```

</details>

- Another `CH.1.1*` lineage to have `S:L858I(C24134A)`, after `DV.7(CH.1.1.1.7)` and `CH.1.1.12`.
- Many interesting mutations scattered around: `S:Q52R(A21717G)`, `S:V445F(G22895T)`, `S:L922F(G24328C)`, etc.

**Comment by FedeGueli** [comment]
238 is the other CH.1.1 still resisting.

**Comment by AngieHinrichs** [comment]
Thanks for pointing out the flip-flop, fixed in 2023-08-17 tree.

**Comment by FedeGueli** [comment]
designated CH.1.1.32 via https://github.com/cov-lineages/pango-designation/commit/3461b2a9ac101ce1a3db67c0feb9ab307e16211d milestone added to the original issue.
