### ISSUE TITLE
XBB.1.5 with ORF3a:P240L, S:V1122M and S:T478R (295 seqs, 7 countries), further acquired S:F456L (148 seqs, 5 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2153]
_Transferred from **Branch 3** of sars-cov-2-variants/lineage-proposals#453_

**Defining Mutations:** `XBB.1.5 [T17124C > T23018C]` > `C26111T(ORF3a:P240L)` > `G24926A(S:V1122M)` > `A9562G` > `C22995G(S:T478R)` > `A20898G`
**Query:** `C26111T, A20898G, C22995G`

**Defining Mutations for Follow-up S:F456L:** _Main proposal_ > `A5839G` > `T22928C(S:F456L)`
**Query:** `C26111T, A20898G, C22995G, T22928C`

**Defining Mutations for Follow-up S:Q613H:** _Main proposal_ > `A5839G` > `C29545A` > `A19337G(ORF1b:K1957R), G23401T(S:Q613H)`
**Query:** `C26111T, A20898G, C22995G, G23401T`

**Earliest seq:** 2023-04-28 (`EPI_ISL_17707100`, California, USA)
**Latest seq:** 2023-07-13 (`EPI_ISL_18036951`, California, USA, with travel history to: Mexico)
**Sampled Countries:** USA (29), Canada (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17707100, EPI_ISL_17744399, EPI_ISL_17767971, EPI_ISL_17788420, EPI_ISL_17788778, EPI_ISL_17788998, EPI_ISL_17789103, EPI_ISL_17852118, EPI_ISL_17852638, EPI_ISL_17856294, EPI_ISL_17856633, EPI_ISL_17950491, EPI_ISL_17950750, EPI_ISL_17950759, EPI_ISL_17955500, EPI_ISL_17971792, EPI_ISL_17971814, EPI_ISL_17972481, EPI_ISL_17986607, EPI_ISL_17997501, EPI_ISL_18036951, EPI_ISL_18037574-18037575, EPI_ISL_18037666, EPI_ISL_18039763, EPI_ISL_18045316, EPI_ISL_18045335, EPI_ISL_18045578, EPI_ISL_18046071, EPI_ISL_18046136`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ac00_4e3ca0.json?f_userOrOld=uploaded%20sample&label=id:node_6969332

diversity from `ORF3a:P240L` branch
![diversity](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/5173d73f-dd80-4a16-93c3-4f5845371a87)

**Trivia:**
- Almost doubled in 10 days, despite small quantities yet.
- Already showed some diversity on Spike, apart from `S:F456L` which may give extra boost, it also acquired mutations like `S:N969R` (`K>R`, `A24468G` over existing `T24469A` introduced from `B.1.1.529`), `S:T547I`, `S:I233V`, to name a few.
![969R](https://github.com/cov-lineages/pango-designation/assets/125747944/213c6e49-4dfe-424e-a27c-cf36300884d4)
- Query for `S:N969K>R` branch: `C26111T, A20898G, 22995G, A24468G`

**Comment by FedeGueli** [comment]
The 456L branch acquired also S:V618S : https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a7d2_1aa5b0.json?label=id:node_7230998
![Schermata 2023-09-13 alle 14 36 08](https://github.com/cov-lineages/pango-designation/assets/87669813/8d740e29-7516-4bd7-ace4-c74b3e18df3f)

**Comment by FedeGueli** [comment]
F456L now 43

**Comment by FedeGueli** [comment]
tracker: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C26111T%2CA20898G%2C22995G%2CT22928C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
ping @corneliusroemer although not super fast is faster than many deisgnated lineages and well above EG.5.1/FL.1.5.1 i think it should be designated.

**Comment by DailyCovidCases** [comment]
Please close this issue
