### ISSUE TITLE
XBB.1.5 sublineage emerged in Ecuador, then spreading to Spain and US,  with orf9b:I5T and S:T20N (seen in Gamma) and  now growing fast in Uk with  further S:H1101Y - 42 seqs-

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2156]
This xbb.1.5 sublineage has emerged  iin Ecuador from an undesignated XBB.1.5 with Orf9b:I5T (T28297C)
and further gained the infamous Gamma defining mutation S:T20N.
After growing fast initially in Ecuador then it was spotted sporadically in Spain but now it seems to be circualting quite fast in England so  i propose it from original issue https://github.com/sars-cov-2-variants/lineage-proposals/issues/134 opened back on June 3.

Defining mutations:
XBB.1.5 >> T28297C > C19140T, S:T20N (C21621A)

Gisaid query: C19140T, C21621A,T28297C

Samples: 34

<Details>
<Summary>
GENOMES
</Summary>
EPI_ISL_17683024, EPI_ISL_17683035, EPI_ISL_17683041,
EPI_ISL_17711720, EPI_ISL_17711724, EPI_ISL_17722405,
EPI_ISL_17726431, EPI_ISL_17786023, EPI_ISL_17797695,
EPI_ISL_17798402, EPI_ISL_17798424, EPI_ISL_17956145,
EPI_ISL_17961540, EPI_ISL_17961561-17961562, EPI_ISL_17961583-17961584,
EPI_ISL_17961596, EPI_ISL_17961603, EPI_ISL_17961615,
EPI_ISL_17972346, EPI_ISL_17987366, EPI_ISL_17990098,
EPI_ISL_18000666, EPI_ISL_18037732, EPI_ISL_18044371,
EPI_ISL_18044373, EPI_ISL_18044391, EPI_ISL_18044405,
EPI_ISL_18044414, EPI_ISL_18044416, EPI_ISL_18052527,
EPI_ISL_18052534-18052535

</Details>

Countries:
After Emerging in Ecuador and being detected then in Spain and US.
As you can notice below in UK it gained a further spike mutation :**S:H1101Y** plus  Orf1a:A248T 

Tree:
![Schermata 2023-07-31 alle 15 48 02](https://github.com/cov-lineages/pango-designation/assets/87669813/ab856766-2e5e-46d7-ac5e-7c2a1e8925b8)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_17469_7bb480.json?label=id:node_7085987

About S:T20N see the super interesting comment by @ryhisner:
![Schermata 2023-07-31 alle 15 47 00](https://github.com/cov-lineages/pango-designation/assets/87669813/b6304f12-4b81-435d-970d-bd538b208f54)
https://github.com/sars-cov-2-variants/lineage-proposals/issues/134#issuecomment-1574432348

**Comment by oobb45729** [comment]
I remember that I read something about Gamma that T20N creates a new N-glycan site at N20 that is occupied (so is R190S), and the N20 site compete with the N17 site for occupation, so the N17 site is not occupied in Gamma. It's another way of losing the N17 glycan in VOCs, apart from T19R and T19I.

**Comment by FedeGueli** [comment]
Closing this one seems having slowed down a lot.
