### ISSUE TITLE
Proposal for a potential sublineage of B.1.617.2 circulating in Denmark with messed-up ORF7a

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#216]
**Description**
**Sub-lineage of**: B.1.617.2 (1263 sequences)
**Earliest sequence**: 2021/05/19 (Germany)
**Most recent sequence**: 2021/9/7 (Germany)
**Countries circulating**: mainly Denmark (771 sequences), Germany (252 sequences) and elsewhere.
**Mutations in addition to B.1.617.2**: S:I850L, ORF3a: L16T, NSP16_K160R, and a messed-up ORF7a that is beyond me.
The ORF7a either looks like this:
![8 1](https://user-images.githubusercontent.com/86835836/132938236-db248ec8-25da-46a7-b4be-e55d9d9c4ad6.png)
or looks likes this:
![8](https://user-images.githubusercontent.com/86835836/132938260-3167ba3d-4035-430a-a8a1-ff5f9c0f0a8e.png)
or this:
![image](https://user-images.githubusercontent.com/86835836/132938501-c5183dc9-0dc0-4524-afb4-8825f400a185.png)

**Genomes**:
[ORF7a that bothers me.csv](https://github.com/cov-lineages/pango-designation/files/7147336/ORF7a.that.bothers.me.csv)

**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/132939101-acc19901-30d7-4992-b252-abc6e4b7a3fa.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_1f180_a39a80.json?c=gt-nuc_27544&l=radial

**Comment by andreijl** [comment]
You might want to look at #202 . The cluster with ORF7a:L49P and all that weirdness seems to have grown a lot.

**Comment by c19850727** [comment]
Thanks @andreijl !

**Comment by chrisruis** [comment]
Thanks @c19850727. Looking at the sequences in this clade, they seem to have Ns throughout that region of Orf7a so they've potentially got a deletion in this region of Orf7a. This is a challenge to designate as this clade seems to come off a big multi-continent polytomy in the tree and the only mutations in the UShER tree after this polytomy are in the potentially deleted Orf7a region so are unreliable. So it doesn't look like there's any reliable mutations to tag this clade so I don't think we can designate it as a new lineage
