### ISSUE TITLE
XBB.2.3.2 sublineage with ORF1a:L293I + ORF1a:P4197S + S:K147N + ORF8:T26I (74 seqs in 11 countries)

### ISSUE THREAD

**Issue by arodzh-sudo** [cov-lineages/pango-designation#2161]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/438

Sub-lineage of: XBB.2.3.2
Substitution on top of **XBB.2.3.2: ORF1a:L293I (C1142A), ORF1a:P4197S (C12854T), S:K147N (A22003T), ORF8:T26I (C27970T)**
Earliest sequence: 2023-5-11, USA, North Carolina — EPI_ISL_17768942
Most recent sequence: 2023-8-29, Canada — EPI_ISL_18224820
Countries circulating: **USA (32), Spain (25), France (6), Japan (2), Puerto Rico (2), Canada (2), Germany (1), UK (1), South Korea (1), Denmark (1), Trinidad and Tobago (1)**
Number of sequences: 74
GISAID nucleotide query: **C1142A,C12854T,A22003T,C27970T**
CovSpectrum query: [XBB.2.3.2* (Nextclade) + **ORF1a:L293I, ORF1a:P4197S, S:K147N, ORF8:T26I**](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AL293I%2CORF1a%3AP4197S%2CS%3AK147N%2CORF8%3AT26I&nextcladePangoLineage=xbb.2.3.2*&)

```{r, echo=FALSE}
EPI_ISL_17768942,EPI_ISL_17853014,EPI_ISL_17852577,EPI_ISL_17717513,EPI_ISL_18006029,EPI_ISL_17821259,EPI_ISL_17847968,EPI_ISL_17847923,EPI_ISL_17885598,EPI_ISL_18040561,EPI_ISL_18040591,EPI_ISL_17965018,EPI_ISL_17982655,EPI_ISL_17810179,EPI_ISL_17958259,EPI_ISL_17958260,EPI_ISL_17958263,EPI_ISL_17958264,EPI_ISL_17958265,EPI_ISL_17982677,EPI_ISL_17972326,EPI_ISL_17979090,EPI_ISL_17990082,EPI_ISL_18064412,EPI_ISL_18015657,EPI_ISL_18064414,EPI_ISL_18064415,EPI_ISL_17995579,EPI_ISL_18064416,EPI_ISL_18064417,EPI_ISL_18064418,EPI_ISL_17986670,EPI_ISL_18064419,EPI_ISL_18064420,EPI_ISL_18037537,EPI_ISL_17996336,EPI_ISL_18042292,EPI_ISL_18064422,EPI_ISL_18064425,EPI_ISL_17994111,EPI_ISL_18037689,EPI_ISL_18050097,EPI_ISL_18065353,EPI_ISL_18072222,EPI_ISL_18072805,EPI_ISL_18080077,EPI_ISL_18080123,EPI_ISL_18090222,EPI_ISL_18090236,EPI_ISL_18090314,EPI_ISL_18112381,EPI_ISL_18112386,EPI_ISL_18112436,EPI_ISL_18112440,EPI_ISL_18113496,EPI_ISL_18117258,EPI_ISL_18118319,EPI_ISL_18118368,EPI_ISL_18119383,EPI_ISL_18123274,EPI_ISL_18123276,EPI_ISL_18126476,EPI_ISL_18144410,EPI_ISL_18145412,EPI_ISL_18159863,EPI_ISL_18162840,EPI_ISL_18168423,EPI_ISL_18212739,EPI_ISL_18220949,EPI_ISL_18222914,EPI_ISL_18224820,EPI_ISL_18228812,EPI_ISL_18229917,EPI_ISL_18235143

```
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22a58_bbb7f0.json?c=gt-nuc_1142,12854,22003,27970&label=id:node_7181693

![Screenshot 2023-08-03 at 10-51-30 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ subtreeAuspice1_genome_22a58_bbb7f0 json](https://github.com/cov-lineages/pango-designation/assets/54407020/cc895ebe-b3c7-4d1b-a67c-ac1d659da7f9)

S:K147N mutation is considered to improve fitness considerably (Bloom and Neher 2023)
![K147N](https://github.com/cov-lineages/pango-designation/assets/54407020/ca2f6b58-704c-4a3a-85ca-6b425b475f22)

**Comment by ryhisner** [comment]
Today there were 10 sequence from Spain uploaded that have the additional spike mutation S:I714V. 
<img width="1498" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/bc7f0d58-85f6-46eb-b5e0-59aa038f2f77">

**Comment by arodzh-sudo** [comment]
Thank you @ryhisner. @FedeGueli made a separate proposal for the S:I714V sublineage, see [#540](https://github.com/sars-cov-2-variants/lineage-proposals/issues/540).

**Comment by arodzh-sudo** [comment]
An update on this: 6 additional sequences from parent branch (S:K147N), one of them with S:714V from Spain and now detected in South Korea totaling 9 countries.
