### ISSUE TITLE
XBB.1.5.94 +11-nuc,5-aa including S:478R (33 seqs, 14 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2164]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/314

XBB.1.5.94+A8434G, A15426G + A2730T(orf1a:K822M), T3766C + C7086T(orf1a:T2274I)+T3460C, C11460A(orf1a:S3732Y, NSP6_S163Y), C15240T, A22995G(S:478R), A26915G, G28090A(orf8:G66D)

GISAID query: T3460C,C11460A,C15240T,C22995G,A26915G,G28090A

No. of seqs: 10( China 2 USA 1 South Korea 3 France 1 Italy 2 Canada 1)

First seq: EPI_ISL_17983658, South Korea, 2023-6-18
Latest seq: EPI_ISL_18067144, USA, 2023-7-27

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ce9b_dbc7a0.json?c=gt-S_478)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/98a54a2a-a6dc-404e-a24a-aa03c9fde609)

**Comment by aviczhl2** [comment]
No new seqs of this for a long time.

**Comment by aviczhl2** [comment]
There seems to be a re-emergence of this one. New country of Switzerland, Germany and France. Total=21 now.

**Comment by FedeGueli** [comment]
613H+487R seems trending up (8% over S:t478R only, but -12% against S:456L-478R combo )
![Schermata 2023-10-01 alle 10 47 11](https://github.com/cov-lineages/pango-designation/assets/87669813/da6f37a0-ff93-4af1-bd87-53e378e51329)

**Comment by aviczhl2** [comment]
25, Slovenia

**Comment by aviczhl2** [comment]
31, Bulgaria

**Comment by aviczhl2** [comment]
33, Norway,Australia

**Comment by aviczhl2** [comment]
Vanish again.
