### ISSUE TITLE
XBB.1.16+E:P71S in Japan(666 seqs, 15 countries) 

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2166]
from https://github.com/sars-cov-2-variants/lineage-proposals/issues/513

XBB.1.16+C26455T(E:P71S)

GISAID query: C26455T,T28297C,T23018C,T12730A,-23202
No. of seqs: 215( India 2 China 2 Australia 2 South Korea 15 Japan 194)

First: EPI_ISL_17565086, India, 2023-3
Latest: EPI_ISL_18051740, Japan, 2023-7-21

Only 103 of the seqs have A28447G（Orf9b:N55S), the other 112 don't have.

This lineage is 24/212 of Okinawa's 2023.7 seqs. 

On usher it is splitted into multiple branches. One main branch and some flip-flop reversion branches.

[usher1,XBB.1.16+E:P71S](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43d9a_eee220.json?f_userOrOld=uploaded%20sample)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/eee37128-4407-4e48-a1e2-066eaf0ebd3a)

[usher2,XBB.1.16+C4586T+E:P71S,Orf9b:S55N+T4586C](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_43d9a_eee230.json?branchLabel=nuc%20mutations)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/0e929c27-d43d-4f54-b644-7b21a0280c26)

@AngieHinrichs is there a way to fix branch 2?

**Comment by aviczhl2** [comment]
It is growing fast in Japan. @corneliusroemer 

https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?nextcladePangoLineage=XBB.1.16*&aaMutations1=E%3AP71S&nextcladePangoLineage1=XBB.1.16*&analysisMode=CompareToBaseline&

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/3fc09ace-b197-402f-81b5-3976fea6022f)

**Comment by aviczhl2** [comment]
294, USA

**Comment by aviczhl2** [comment]
391, Switzerland

**Comment by aviczhl2** [comment]
400, France

**Comment by FedeGueli** [comment]
WHile it is big enough and being a drivere of Okinawa wave , it is likely not more able to compete: https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?aaMutations=S%3AL455F&aaMutations1=E%3AP71S&nextcladePangoLineage1=XBB.1.16*&analysisMode=CompareToBaseline& 
cc @corneliusroemer what do you think about this kind of lineages? 
we have plenty of this kind that likely deserved a designation but now they will be outcompeted, if you can draw a rule we will act consequently.
My personal idea is that better designating things timely when emerging but understanding that a designation without perspective is a workload  when it is late better to drop them not having any chance to compete. but open to hear your opinion. 
To me : 1) emerging mutations (spike or not)
2) growth advantages ( in the range of 15% under the fastest lineage) should be un- written guidelines to our common process. 

If we can fix a threshold it will save a lot of times in tracking /proposing/closing/designating process

**Comment by aviczhl2** [comment]
> WHile it is big enough and being a driver of Okinawa wave , it is likely not more able to compete: https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?aaMutations=S%3AL455F&aaMutations1=E%3AP71S&nextcladePangoLineage1=XBB.1.16*&analysisMode=CompareToBaseline& cc @corneliusroemer what do you think about this kind of lineages? we have plenty of this kind that likely deserved a designation but now they will be outcompeted, if you can draw a rule we will act consequently. My personal idea is that better designating things timely when emerging but understanding that a designation without perspective is a workload when it is late better to drop them not having any chance to compete. but open to hear your opinion. To me : 1) emerging mutations (spike or not) or combinations 2) growth advantages ( in the range of 15% under the fastest lineage) should be un- written guidelines to our common process.
> 
> If we can fix a threshold it will save a lot of times in tracking /proposing/closing/designating process

E:P71S is not all about growth advantage, it is also about severity.

**Comment by aviczhl2** [comment]
408, Canada.

**Comment by aviczhl2** [comment]
446, Spain

**Comment by aviczhl2** [comment]
467, Denmark

**Comment by aviczhl2** [comment]
566, Thailand

**Comment by aviczhl2** [comment]
568, Netherlands

**Comment by aviczhl2** [comment]
+2 Greece

**Comment by aviczhl2** [comment]
+2 Sweden
