### ISSUE TITLE
XBB.2.3 with S:T883I in a branch with a BA.2 defining reversion at Orf1a:S135S. Japan ( 79 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2169]
Originally discussed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/281

Defining mutations:
XBB.2.3 >> > C13959T > Orf1a:S135S REV (G670T), C2119T > Orf1a:D3042N (G9389A = NSP4_D279N), C25797T > G14712T, S:T883I (C24210T)

Gisaid query : C25797T ,G14712T,C2119T

Samples : 59 

<Details>
<Summary>
IDs
</Summary>
EPI_ISL_17780138, EPI_ISL_17780191, EPI_ISL_17803876,
EPI_ISL_17819832, EPI_ISL_17820005, EPI_ISL_17820008,
EPI_ISL_17820010, EPI_ISL_17820050, EPI_ISL_17881372,
EPI_ISL_17881711, EPI_ISL_17881813, EPI_ISL_17882217,
EPI_ISL_17882431, EPI_ISL_17882834, EPI_ISL_17883383,
EPI_ISL_17883879, EPI_ISL_17884030, EPI_ISL_17884139,
EPI_ISL_17941124, EPI_ISL_17952576, EPI_ISL_17958725,
EPI_ISL_17958734, EPI_ISL_17959012, EPI_ISL_17959931,
EPI_ISL_17961064, EPI_ISL_17973262, EPI_ISL_17978727,
EPI_ISL_17999339, EPI_ISL_18000520, EPI_ISL_18000570,
EPI_ISL_18006376, EPI_ISL_18006537, EPI_ISL_18006542,
EPI_ISL_18006985, EPI_ISL_18010298, EPI_ISL_18010336-18010337,
EPI_ISL_18010339, EPI_ISL_18010341, EPI_ISL_18010352,
EPI_ISL_18039422, EPI_ISL_18040627, EPI_ISL_18040796,
EPI_ISL_18044091, EPI_ISL_18047778, EPI_ISL_18050895,
EPI_ISL_18050975, EPI_ISL_18051821, EPI_ISL_18055949,
EPI_ISL_18056226, EPI_ISL_18056406, EPI_ISL_18056452,
EPI_ISL_18058384, EPI_ISL_18058409, EPI_ISL_18065184,
EPI_ISL_18065276, EPI_ISL_18065297, EPI_ISL_18065301,
EPI_ISL_18066237

</Details>

Tree:
![Schermata 2023-08-06 alle 17 13 14](https://github.com/cov-lineages/pango-designation/assets/87669813/8abeee12-8bc6-4752-b8f5-04e1db5592f4)

![Schermata 2023-08-06 alle 17 11 04](https://github.com/cov-lineages/pango-designation/assets/87669813/5d9cf893-b0ed-49c0-b417-7256ca949e06)
![Schermata 2023-08-06 alle 17 12 56](https://github.com/cov-lineages/pango-designation/assets/87669813/fece7d6c-b547-4700-9827-a50ccc4a46aa)

**Comment by FedeGueli** [comment]
this is not far from EG on Covspectrum maybe japanese sequencing intensity pushes it up : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C25797T%2CG14712T%2CC2119T&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
Designated XBB.2.3.21
