### ISSUE TITLE
Two potential sublineages of B.1.617.2, one with S:Q677H, and the other with S:E484Q

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#217]
**Proposed sublineage 1**
**Description**
**Sub-lineage of**: B.1.617.2 (692 sequences)
**Earliest sequence**: 2021/4/3 (Senegal)
**Most recent sequence**: 2021/9/11 (Jordan)

**Countries circulating**: France (177 sequences), the US (120 sequences), the UK (70 sequences), Germany (58 sequences) and a few other countries
**Detection at border-entry**: Japan ex-Senegal (4 sequences, on 4 different occassions), Japan ex-Morocco (1 sequence), Korea ex-Jordan (3 sequences)

**Mutations in addition to B.1.617.2**: 
- ORF1a:C3059F;
- and then S:Q677H and ORF1b:M1596I;
- then ORF1a:V2930L, ORF3a:ins104P, and N:L230F;
- then S:L1265F (defining)
- interestingly, 6 sequences in England also have ORF8:Q27stop

**Genomes**:
[Q677H delta.csv](https://github.com/cov-lineages/pango-designation/files/7170322/Q677H.delta.csv)

**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/133449089-e870907a-82b0-4eb8-84f9-9227165facb9.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ce92_1e41e0.json?c=gt-S_1265&l=radial

**Proposed sublineage 2**
**Description**
**Sub-lineage of**: B.1.617.2 (604 sequences)
**Earliest sequence**: 2021/04/20 (the UK)
**Most recent sequence**: 2021/9/3 (the US)

**Countries circulating**: the US (590 sequences), and a few other countries

**Mutations in addition to B.1.617.2**: 
- ORF1a:P309L, ORF1a:P1921Q, ORF1a:D2980N, ORF1a:F3138S, S:K77T
- and then S:E484Q (defining)
- a subclade of 102 sequences mainly from Texas also has S:L5F

**Genomes**:
[E484Q delta.csv](https://github.com/cov-lineages/pango-designation/files/7170688/E484Q.delta.csv)

**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/133444562-4b80585f-2f65-4729-928a-42b69828c540.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d621_1f54f0.json?c=gt-S_484&l=radial

**Comment by FedeGueli** [comment]
This paper on conformational changes in S1 of different VOCs/VOIs spikes suggests to monitor closely E484Q in Delta 

[Screenshot_2021-09-16-09-37-58-349_com android chrome](https://user-images.githubusercontent.com/87669813/133570625-b2967b04-cf7a-4642-98f0-db87e58ad26d.jpg)
C
ause in Kappa that mutation favoured the presentation of the spike as a dimer of trimers with RBDs bound head to head.

👇

https://www.biorxiv.org/content/10.1101/2021.09.12.459978v1

**Comment by FedeGueli** [comment]
![Screenshot_2021-09-16-09-37-58-349_com android chrome](https://user-images.githubusercontent.com/87669813/133570884-968559dc-c67a-4036-a1f2-ad701be368f9.jpg)

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added the clade with S:Q677H as AY.34 and the clade with S:E484Q as AY.35 in [v1.2.78](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.78)

**Comment by c19850727** [comment]
@chrisruis 

Hi Chris, I was double checking AY.35 today and found there's a sibling clade that seems growing quite steadily.
It's defined by ORF8:E19stop and then S:T547I (and 2 synominous mutations). There are around 900 sequences now, predominantly in the US.
![image](https://user-images.githubusercontent.com/86835836/135591836-64661680-3003-41ca-bd38-8a5bdc4790a4.png)

![image](https://user-images.githubusercontent.com/86835836/135593617-1818a8eb-9f0c-4d33-a17f-3c29b4bb3c33.png)

Do you think if it's better to change the defining substitution of AY.35 to their common parant (ORF1a:P309L, ORF1a:P1921Q, ORF1a:D2980N, ORF1a:F3138S and S:K77T), or just give a new designation to this clade with ORF8:E19stop and S:T547I? 

Thanks!
