### ISSUE TITLE
FY.4.2 sublineage with S:L212S  recently spreading in Japan and found multiple times in travellers to US (114 as 19/09)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2170]
Originally discussed here: https://github.com/sars-cov-2-variants/lineage-proposals/issues/487#issuecomment-1667139571 with @HynnSpylor 

I noticed an international spread branch of FY.4 defined by Orf1b:V2287I that has further acquired S:L212S.
S:L212S has been quite homoplasic at the end of original BA.2 era conferring some slight advantage.
As noticed by @hynnspylor XBB.1.22.1 has an apparent propension to acquire further S1 mutations so it is not surprising to see S:L212S appearing here.

**Defining mutations:**
FY.4 >> C7417T, **ORF1b:V2287I** (G20326A) > **ORF1a:Y2171F** (A6777T) > **ORF3a:S177**I (G25922T)  > **S:L212S** (T22197C) >  **N:A218T** (G28925A) 
 
**NSPs mutations**:
NSP15_V236I > Orf1b:V2287I 
NSP3_Y1353F > ORF1a:Y2171F

**Gisaid query** : G20326A,T22197C, G28925A

**Samples**: 18 all very recent mostly from Japan, Japanese travellers to US (3 from different airports)
with one, the first, from Kenya not on Gisaid
 
**First:** 
KEN/SS11824/2023|OR045009.1|2023-05-08
**Last**:
hCoV-19/Japan/PG-553168/2023 | Original | EPI_ISL_18071663 | 2023-07-21

<Details>
<Summary> EPI_ISLs </summary>
 EPI_ISL_17986666, EPI_ISL_18010943, EPI_ISL_18011708,
EPI_ISL_18013336, EPI_ISL_18036876, EPI_ISL_18036887,
EPI_ISL_18036950, EPI_ISL_18036959, EPI_ISL_18047108,
EPI_ISL_18049184, EPI_ISL_18049331, EPI_ISL_18051828,
EPI_ISL_18051964, EPI_ISL_18054419, EPI_ISL_18054456,
EPI_ISL_18071589, EPI_ISL_18071663
 </Details>

**Tree:**

![Schermata 2023-08-07 alle 09 53 08](https://github.com/cov-lineages/pango-designation/assets/87669813/d2ef3b12-9755-4d5d-9f2b-c66c6d751eb0)
![Schermata 2023-08-07 alle 09 54 04](https://github.com/cov-lineages/pango-designation/assets/87669813/176d4f90-fe55-4bfd-a895-627130a7c1a8)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d2e6_a19a0.json?label=id:node_6841786

**Growth advantage:**
It shows a faster growth rate of EG.5.1 , but lets keep in ind that GBW samples are usually duplicated and that could be a confounder. 
For sure it is a recent lineage showing fitness while spreading in competition with fast variants.
Alternatively it could be related to a superspreading event as swimming world championship in Fukuoka , but i would have expected a more random distribution in international cases , or finally it could be related to a region/population with specific links to US  (excluding Okinawa after the recent upload that showed Arcturus being the dominant variant in that prefecture)
![Schermata 2023-08-07 alle 09 48 10](https://github.com/cov-lineages/pango-designation/assets/87669813/5ddcd382-70b3-48ca-b89f-b57485452f17)
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?nextcladePangoLineage=EG.5.1*&nucMutations1=G20326A%2CT22197C%2CG28925A&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
cc @corneliusroemer  @InfrPopGen @thomeaspeacock @AngieHinrichs  i suggest rapid review of this one.

**Comment by HynnSpylor** [comment]
Its parent lineage (with ORF1a:Y2171F, ORF1b:V2287I) has been designated as FY.4.2

**Comment by FedeGueli** [comment]
> Its parent lineage (with ORF1a:Y2171F, ORF1b:V2287I) has been designated as FY.4.2
> 
> One more seq from Shanghai, China

thx i ve changed the title and added the milestone in the other repo.

**Comment by FedeGueli** [comment]
One more from US - Michigan

**Comment by HynnSpylor** [comment]
29 seqs now
2 samples from Mississippi, US show S:K528R and S:M1237V

**Comment by FedeGueli** [comment]
33 seqs now also in Australia. this should be designated.
Growth rate in the high range: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=G20326A%2CT22197C%2CG28925A&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
while COvspectrum shows it as fast as current dominant lineages i am seeing it slowing down . another week and i'll close it : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=G20326A%2CT22197C%2CG28925A&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
> while COvspectrum shows it as fast as current dominant lineages i am seeing it slowing down . another week and i'll close it : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=G20326A%2CT22197C%2CG28925A&analysisMode=CompareToBaseline&

i was wrong.

**Comment by FedeGueli** [comment]
@corneliusroemer not sure this can compete vs HK.3 : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G20326A%2CT22197C%2CG28925A&analysisMode=CompareToBaseline&

Still seems  faster thatn the rest of the family :https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=FY.4*&nucMutations1=G20326A%2CT22197C%2CG28925A&analysisMode=CompareToBaseline& 

Is this still relavant? let me know your thoughts so i can choose selecting thighter or looser the criteria to be  proposed. If we put HK.3 (that is already 1000seq worlwide as baseline very few proposal could be supported) . Let me know please so we can be coordinated.

**Comment by FedeGueli** [comment]
114, closing it cause no chance to compete
