### ISSUE TITLE
EG.1.3 saltation with S:A222V, S:D253Y and 3 non-Spike aa mutations (19 seqs in Sweden and Israel)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#2171]
*Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/494

Defining mutations:
EG.1.3>G1914A (ORF1a:R550H = NSP2_R370H), T6394A (ORF1a:D2043E = NSP3_D1225E), G15372A, C18508T (ORF1b:L1681F = NSP14_L157F), C22227T (S:A222V), C22264T, G22319T (S:D253Y) 

GISAID query: T6394A, G15372T, C22227T, G22319T
Earliest seq: 2023-06-09 (Sweden, EPI_ISL_17804180)
Most recent seq: 2023-07-25 (Israel, EPI_ISL_18062677)
Countries detected: Sweden (18), Israel (1)

Usher Tree:
<img width="710" alt="屏幕截图 2023-08-07 162532" src="https://github.com/cov-lineages/pango-designation/assets/121703496/6cc759cd-8add-423d-a5c2-c35a69371f25">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41e5e_aa460.json?c=gt-S_222

S:A222V was popular in B.1.177, some Delta (B.1.617.2*) lineages and nowadays in XBC* lineages. S:D253Y is another attempt for site S:D253 (like S:D253G in XBB.2*).
At one time it was only in Sweden, but recently Israel also detected it. So I decide to propose it in main page.

Genomes:
EPI_ISL_17804180, EPI_ISL_17950806, EPI_ISL_17950816-17950817, EPI_ISL_17950821, EPI_ISL_17950842, EPI_ISL_17969285,
EPI_ISL_17990578, EPI_ISL_17990584, EPI_ISL_17990662, EPI_ISL_17990672, EPI_ISL_18008250, EPI_ISL_18010813,
EPI_ISL_18062677, EPI_ISL_18067352, EPI_ISL_18067354, EPI_ISL_18067358-18067360

**Comment by DailyCovidCases** [comment]
Please close this issue
