### ISSUE TITLE
GK.1.1/XBB.1.9.1* Recombinant (FLip+T573I+S704L)(27 seq; Aug 23)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2173]
**Description**
**Recombinant Between:** GK.1.3 (XBB.1.5.70.1.3) and XBB.1.9.1* (Most likely. It could also be XBB.1.16)
**Earliest sequence:** 2023-6-9, USA, Colorado — EPI_ISL_17856744
**Most recent sequence:** 2023-7-25, Australia (NSW) — EPI_ISL_18073787; Spain (Basque) — EPI_ISL_18056891
**Countries circulating:** Australia (3), USA (2), France (1), Spain (1)
**Number of Sequences:** 7
**GISAID AA Query:** Not possible
**GISAID Nucleotide Query:** G25947C, T28297C, C28657T
**CovSpectrum Query:** [3-of: G25947C, C27741T, T28297C, C28657T] & [4-of: A1124G, C1973T, A2163C, C7564T, T8737C, G12467T, A16856G, C23673T] & !A25045G & !C25658T & !C27059T & !C28005T
**Breakpoints:**
First Breakpoint: 23673-25044 (S:704-S:1161)
Second Breakpoint: 28297-28656 (N:8-N:128)
 
**Private Mutations:** ORF3a:Q185H (G25947C)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/GK.1.3_XBB.1.9.1_Recomb__7_seq.json?c=gt-nuc_25947&label=id:node_3098784

<img width="1498" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/18f64644-5f14-48b8-b395-dee81dc7ad59">

**Evidence**
Given wide geographic spread and that this recombination joins together the magic FLip combo of S:L455F & S:F456L (not to mention S:S704L) with the advantageous ORF9b:I5T, I think this one is worth flagging. The five most recently collected sequences in this lineage, all collected between July 18-25, have S:T573I and three additional synonymous nucleotide mutations (G9220A, T9952C, C26907T).

At first, this looks simply like a GK.1.3 that picked up three nucleotide mutations: G25947C (ORF3a:Q185H), C27741T (syn), T28297C (ORF9b:I5T). But it's missing four synonymous nucleotides that all GK.1.3 possess: A25045G, C25658T, C27059T, & C28005T. However, it retains the synonymous C28657T, which is found in all GK.1 but is rare elsewhere.
 
There are zero XBB* sequences (other than the ones in this lineage) returned by the following CovSpectrum search query:
 
Nextcladepangolineage:XBB* & [2-of: C28657T, G25947C, C27741T] & T28297C & !A25045G & !C25658T & !C27059T & !C28005T
 
But CovSpectrum returns 541 other results for the search query below:

Nextcladepangolineage:XBB* & [1-of: C27741T, G25947C] & T28297C & !A25045G & !C25658T & !C27059T & !C28005T
 
Any lineage with sequences matching this description could be the partner recombinant. Here is the breakdown of the 541 sequences returned.
 
XBB.1.9.1* — 344 (63.6%)
XBB.1.16* — 108 (20.0%)
XBB.1.9.2* — 66 (12.2%)
XBB.1.22* — 14 (2.6%)
XBB.1.9.6* — 3 (0.55%)
XBB.1.42* — 3 (0.55%)
XBB.1.5* — 2 (0.37%)
XBB.1.9 — 1 (0.18%)
 
So this is probably a GK.1.3 recombinant with an XBB.1.9.1* lineage of some sort, but it could be any of the others listed above as well.
  
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17856744, EPI_ISL_17976216, EPI_ISL_18046369, EPI_ISL_18056891, EPI_ISL_18060735, EPI_ISL_18066425, EPI_ISL_18073787
</details>

**Comment by aviczhl2** [comment]
It cannot be XBB.1.16 as it has 28447G.

**Comment by ryhisner** [comment]
> It cannot be XBB.1.16 as it has 28447G.

Yeah, but it also has C28657T, which is in GK.1.3, so this is a sandwich recombinant. If the last breakpoint occurred before 28477, then the other donor lineage could still be XBB.1.16.

**Comment by FedeGueli** [comment]
12 now

**Comment by FedeGueli** [comment]
16 now last ones from Spain Germany and US

**Comment by FedeGueli** [comment]
22 AS TODAY . 5 RECENT SEQUENCES  from Spain, Australia and France.

cc @ryhisner i cant send dm so please take  alook. cc @corneliusroemer i think this is growing fast.

**Comment by FedeGueli** [comment]
Just to make it clear this is a FLip lineage with ORf8:8Stop and Orf9b:I5T so quite expected to be fast.

cc @ryhisner i suggest to clarify in the title that is a FLip lineage.

![Schermata 2023-08-18 alle 16 14 07](https://github.com/cov-lineages/pango-designation/assets/87669813/1d6e8306-bd4c-4886-811a-f91d36334f4b)

**Comment by FedeGueli** [comment]
And @ryhisner sorry for bothering here but this is GK.1.1 with 573/704 not GK.1.3!!

**Comment by ryhisner** [comment]
> And @ryhisner sorry for bothering here but this is GK.1.1 with 573/704 not GK.1.3!!

Thanks for the correction, Fede! Will edit the title presently.

**Comment by corneliusroemer** [comment]
I will designate, have looked at it in the past just didn't have time to go through the motions, sorry for the delay.

**Comment by FedeGueli** [comment]
Now it is 27 from 10 to 25 in 11 days ping @corneliusroemer

**Comment by corneliusroemer** [comment]
Where does it start?Was 573 independently acquired compared to GK.1.1. It's suspicious because 573I is in GK.1.1

<img width="2190" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/976434cd-c58d-4549-b31d-e6b835515ba6">

**Comment by FedeGueli** [comment]
@corneliusroemer to me it is a plain GK.1.1 recombinant, why do you think it has been independently acquired?

**Comment by FedeGueli** [comment]
Ok i was completely worng it is GK.1.3 not GK.1.1 the father i was got fooled by the 573I  during the routinely checks.. sorry Cornelius and Ryan

**Comment by FedeGueli** [comment]
the S:T573I branch designated XCH.1  i cant add any milestone cause it was directly proposed here. cc @corneliusroemer

**Comment by FedeGueli** [comment]
XCH.
