### ISSUE TITLE
JD.1 Sublineage with S:A475V, ORF8:A65V, ORF1b:A241V (32seq, Aug 25)—originally found by @oobb45729

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2174]
### **Description**  All credit goes to @oobb45729 for being the first to discover this branch and for proposing its parent branch. The only reason I created (then closed) this issue was because I was fooled by the incorrect Usher tree placement into thinking this was a different lineage.
**Sub-lineage of:** JD.1
**Earliest sequence:** 2023-7-8, USA, Florida — EPI_ISL_18012368
**Most recent sequence:** 2023-8-21, Spain, Basque Country — EPI_ISL_18134783
**Countries circulating:** 
**Number of Sequences:** ~32
**GISAID Nucleotide Query:** C14189T, A14634G, C19185T, T28282C
**CovSpectrum Query:** Nextcladepangolineage:JD.1* & [4-of: C14189T, A14634G, C19185T, G22927T, T22928C, C22986T, T28282C]
**Substitutions on top of JD.1:**
**Spike:** A475V
**ORF8:** A65V
**ORF1b:** A241V (NSP12_A250V)
**Nucleotide:** C14189T, C19185T, C22986T, C28087T
 
 
**Phylogenetic Order of Mutations:** C14189T (ORF1b:A241V)   **→**   C28087T (ORF8:A65V)   **→**   C19185T, G22927T, T22928C, C22986T, T28282C (S:L455F, S:F456L, S:A475V, ORF1b:A241V)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/JD.1_A475V.json?c=gt-nuc_22986&label=id:node_7177834

<img width="1486" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/3ca0aac7-cbcc-4a56-b12d-2e8055ca30d5">

**Evidence**
The benefits of the FLip (S:L455F, S:F456L) in XBB lineages is famous already, but S:A475V has been far less common. It is an escape mutation, and according to @Asinickle, is located extremely close to 455-456. A475V has also shown up recently in other scattered L455F-F456L lineages, so perhaps the Flip opens the door to A475V, which previously, judging by its rarity, must have imposed a steep fitness cost.

One really interesting detail: this lineage—like its parent, JD.1—has T28282C, which is synonymous in N but substantially upgrades the ORF9b Kozak sequence—from worst to best at the -2 spot—so this should somewhat increase the expression of ORF9b, a theme that has occurred again and again throughout the pandemic.

.
<img width="1385" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/557cf105-4807-45f1-bd18-015f39c6ff81">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17979082, EPI_ISL_18033321-18033322, EPI_ISL_18037173, EPI_ISL_18070073, EPI_ISL_18072815, EPI_ISL_18072818, EPI_ISL_18072823-18072824, EPI_ISL_18092160, EPI_ISL_18094726, EPI_ISL_18095944, EPI_ISL_18098754, EPI_ISL_18105023, EPI_ISL_18105120, EPI_ISL_18106546, EPI_ISL_18110057, EPI_ISL_18113215, EPI_ISL_18118823, EPI_ISL_18119237, EPI_ISL_18119241, EPI_ISL_18119349, EPI_ISL_18119784, EPI_ISL_18121880, EPI_ISL_18123909, EPI_ISL_18124225, EPI_ISL_18124982, EPI_ISL_18130473, EPI_ISL_18134783, EPI_ISL_18134811, EPI_ISL_18134853, EPI_ISL_18134859
</details>

**Comment by ryhisner** [comment]
This looks like a duplicate that confused me because Usher made it look entirely separate from a bunch of other sequences that are probably related to it. My mistake.

**Comment by FedeGueli** [comment]
@ryhisner i was checking this but then fell.asleep while ushering. I see 17 seqs with the Trio 455-4566-475V they should be GK.3.1 plus the other undesignated xbb.1.5 flip

**Comment by FedeGueli** [comment]
@ryhisner if @oobb45729 agrees you can reopen this one as sublineage of the recently designated JD.1 cause it was a bit a messy designation cause Cornelius saw it from the Brazilian scientists which have correctly highlighted it , but we were tracking it thanks to OObb since it was 2 sequences only in another issue where we widely have spoken about this S:A475V sublineage . SO all the discussion is now buried and i fear this sublineage could not be tracked properly cause anyone finds it as already proposed but instead no one is aware of all the tale about this one. so Please reopen it after OOBB approval.

**Comment by oobb45729** [comment]
I am OK with it.

**Comment by FedeGueli** [comment]
> I am OK with it.

Thank you! @ryhisner please reopen it as sublineage of JD.1

**Comment by ryhisner** [comment]
I've tried to edit the title and description and Usher trees to correct all the previous mistakes, but I'm in a rush and am certain I've missed some and/or made other mistakes, but I'm reopening this issue at the urging of @FedeGueli & with the blessing of @oobb45729, to whom all credit for discovering and describing this lineage should go.

**Comment by FedeGueli** [comment]
Designated JD.1.1 please @corneliusroemer add milestone-

**Comment by oobb45729** [comment]
The A475V branch was not found by me. Give credit to @FedeGueli.
