### ISSUE TITLE
FL.2 with S:N641K emerged likely in Eastern Africa and shows a lot of Spike diversity: three branches 259S / 809T / 471Q  (79 seqs, 14 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2180]
_Transferred from sars-cov-2-variants/lineage-proposals#520_

**Defining Mutations:** `FL.2` > `C25521T` > `T23485A(S:N641K), A29683T`
**Query:** `T23485A, C25521T`
**Earliest seq:** 2023-03-15 (`EPI_ISL_17363241`, England, UK)
**Latest seq:** 2023-08-03 (`EPI_ISL_18089995`, Sweden)
**Sampled Countries:** USA (23; California/16, Arizona/4, New York/2, Texas/1), Sweden (21), Canada (9, Ontario), UK (6, England/5, Scotland/1), France (2), Austria (1), China (1, Shanghai), Germany (1), India (1), Ireland (1), Israel (1), Italy (1), Japan (1), Spain (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17363241, EPI_ISL_17395881, EPI_ISL_17400810, EPI_ISL_17448553, EPI_ISL_17488308, EPI_ISL_17488334, EPI_ISL_17511907, EPI_ISL_17514054, EPI_ISL_17537803, EPI_ISL_17537913, EPI_ISL_17549297, EPI_ISL_17553672, EPI_ISL_17555869, EPI_ISL_17558172, EPI_ISL_17590487, EPI_ISL_17630281, EPI_ISL_17630455, EPI_ISL_17630478, EPI_ISL_17664440, EPI_ISL_17668930, EPI_ISL_17668978, EPI_ISL_17668999, EPI_ISL_17690272, EPI_ISL_17713615, EPI_ISL_17721736, EPI_ISL_17722643-17722644, EPI_ISL_17722718, EPI_ISL_17731144, EPI_ISL_17731521, EPI_ISL_17732731, EPI_ISL_17732763, EPI_ISL_17732771, EPI_ISL_17732773, EPI_ISL_17732812, EPI_ISL_17732815, EPI_ISL_17732819, EPI_ISL_17764343, EPI_ISL_17764728, EPI_ISL_17767911, EPI_ISL_17768311, EPI_ISL_17769714, EPI_ISL_17781527, EPI_ISL_17791659, EPI_ISL_17797041, EPI_ISL_17809292, EPI_ISL_17809729, EPI_ISL_17838302, EPI_ISL_17838841, EPI_ISL_17854148, EPI_ISL_17855011, EPI_ISL_17950471, EPI_ISL_17950512, EPI_ISL_17951643, EPI_ISL_17981065, EPI_ISL_18005336, EPI_ISL_18010050, EPI_ISL_18045881, EPI_ISL_18046161, EPI_ISL_18046249, EPI_ISL_18046277, EPI_ISL_18055042, EPI_ISL_18057063, EPI_ISL_18069764, EPI_ISL_18069768, EPI_ISL_18069925, EPI_ISL_18089985, EPI_ISL_18089987, EPI_ISL_18089990, EPI_ISL_18089995`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_432ef_8c6650.json?f_userOrOld=uploaded%20sample
![diversity](https://github.com/cov-lineages/pango-designation/assets/125747944/513b3f19-b184-4ce6-9378-6f0fe50c7261)

**Trivia:**
- `S:N641K` only sampled 170 times during the whole pandemic, about 1/3 is from this branch. It may be associated with novel cleavage site of HAT (see [comment](https://github.com/sars-cov-2-variants/lineage-proposals/issues/520#issuecomment-1676167049) by @thiolist ), related study: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9167920/
- Not a fast lineage, but got sampled here and there sparsely. 
- One of the most recent branch is the one with the most spike mutations, follows: `S:259S, E554A` and `K356N`, but there are also mutations like `S:P809T`, `E471Q` from other branches, all forms some kind of long branches:

1. A29683T > C29098T > G4357A > A22337T(**S:T259S**) > C2942T, C11396T(ORF1a:L3711F), A23223C(**S:E554A**), C29108T(**N:P279S**)
2. A29683T > C23987A(**S:P809T**) > C8016T(ORF1a:A2584V), T15276C, G17032A(ORF1b:V1189I), A21137G(ORF1b:K2557R), G23012T(**S:E484S**), C24210T(**S:T883I**)
3. G1820A(ORF1a:G519S) > G22973C(**S:E471Q**), C27389T(_TRS of ORF7a_), A28319G(**N:T16A**), C29696T

**Comment by ryhisner** [comment]
Continuing the discussion from the previous page, it seems like a HAT cleavage site at S:R667 may have played an important role in SARS-CoV-1, at least according to this paper. https://journals.physiology.org/doi/full/10.1152/ajplung.00509.2016
<img width="1208" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/0055c348-c61e-4fa1-9287-29c75391b6e3">

**Comment by ryhisner** [comment]
It appears that a HAT cleavage site promotes cell-cell fusion, something we haven't seen a great deal of since Delta. https://journals.asm.org/doi/10.1128/jvi.05300-11 


.
<img width="1320" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/5b56ce2a-c76a-4aca-b9c2-1f8425d3abaa">

**Comment by FedeGueli** [comment]
> It appears that a HAT cleavage site promotes cell-cell fusion, something we haven't seen a great deal of since Delta. https://journals.asm.org/doi/10.1128/jvi.05300-11
> 
> . <img alt="image" width="1320" src="https://user-images.githubusercontent.com/33738461/260302730-5b56ce2a-c76a-4aca-b9c2-1f8425d3abaa.png">

Now i am extending a bit too much ( also Sars1 not having the FCS could have an impact) but S:I666V in BQ.1.2 was the only mutation found experimentally in cell lines to bring back fusogenictity to pre omicron era. Wondering if linked. c @thomaspeacock

**Comment by FedeGueli** [comment]
The emergence in Eastern Africa is deduced by two early (march-april) samples from airport surveillance from Kenya and Somalia

**Comment by thiolist** [comment]
Hello Fredrico,

I use the software tool "Peptide Cutter".

https://web.expasy.org/peptide_cutter/



When given the test sequence ...GS*N*VF.... (and the "Trypsin" optimized
analysis is enabled) this is the result:

[image: Peptide cutter result for "GSNVF" sequence.png]


*No cleavage *(from Trypsin or any other enzyme supported by Peptide
Cutter).


But the sequence ...S*K*V... produces:

[image: Peptide cutter result for "GSKVF" sequence.png]


*100% cleavage* (if the enzyme has access to the ...GS*K*VF... sequence).


Interestingly, TMPRSS2 (another trypsin-like protease) is membrane bound.
The spile only becomes available to this enzyme after it has become bound
to ACE2 at the cellular membrane.

Conversely, the HAT enzyme is soluble, so the spike is continuously
available to this enzyme prior to binding to ACE2.

Therefore, the spike that antibodies "see" prior to ACE2 binding can have
this site already cleaved, and therefore not be recognized by the antibody.

*IMPORTANT*

Tissues other than the human airway will not have this site cleaved by HAT,
and therefore antibodies that target this site on the spike should still
function in the rest of the body.

- thiolist
(Michael Ott)

**Comment by thiolist** [comment]
<img width="436" alt="Peptide cutter result for  GSNVF  sequence" src="https://github.com/cov-lineages/pango-designation/assets/142126282/2f0e17a2-338d-459c-87de-23781e931a7c">



<img width="957" alt="Peptide cutter result for  GSKVF  sequence" src="https://github.com/cov-lineages/pango-designation/assets/142126282/1132cb1f-d923-41b9-8dc2-53a51b3caed5">

**Comment by FedeGueli** [comment]
Thank you @th

**Comment by FedeGueli** [comment]
both w 259S
