### ISSUE TITLE
EG.5.1.1 with S:D253G and ORF1a:1923T (66 sequences)

### ISSUE THREAD

**Issue by BorisUitham** [cov-lineages/pango-designation#2184]
Query:  T14988C, A23014T, G6032A, A22320G

First sequence: 2023-06-26, wales
Recent sequence: 2023-08-07, ireland
Countries: Austria, UK (Wales, England), Ireland, Israel, Spain, Sweden, USA (baseline in florida + airport travellers from france and spain), Belgium, Italy (Belgium and italy are not found with the query but are on the usher tree)

I noticed this subbranch when it was 5 sequences and thought it was interesting because s:253g is the alternative to 252v in xbb.2.3, and here they are combined. A week later it increased to 12, and a week later it was 25. Now a day later I check again and there are 35 sequences on gisaid with this query. Usher shows more sequences than the query, mostly because 456l was not sequenced properly there I think. If sequences would translate directly in infection counts (not very much, especially nowadays) this would mean that the doubling time is less than a week at the moment.

I'm also interested in the spanish S:R78M branch. Doesn't look like it has been very common or advantageous over the pandemic but also not very disadvantageous either.

![eg511sublin](https://github.com/cov-lineages/pango-designation/assets/119106095/e1511e16-cad3-4e86-a09b-9ce185ef52f7)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1d051_a41750.json?f_userOrOld=uploaded%20sample

EPI_ISL_17989851, EPI_ISL_18010868, EPI_ISL_18015591,
EPI_ISL_18015753, EPI_ISL_18015770, EPI_ISL_18036932,
EPI_ISL_18056772, EPI_ISL_18059100, EPI_ISL_18066791,
EPI_ISL_18066797, EPI_ISL_18066843, EPI_ISL_18067350,
EPI_ISL_18075844, EPI_ISL_18078139, EPI_ISL_18078363,
EPI_ISL_18078381, EPI_ISL_18088371, EPI_ISL_18094196,
EPI_ISL_18094208, EPI_ISL_18094235, EPI_ISL_18094272,
EPI_ISL_18094342-18094343, EPI_ISL_18095882, EPI_ISL_18096790,
EPI_ISL_18097979, EPI_ISL_18097990, EPI_ISL_18098067,
EPI_ISL_18098113, EPI_ISL_18098123, EPI_ISL_18098156,
EPI_ISL_18098165, EPI_ISL_18098540, EPI_ISL_18098543-18098544,

**Comment by BorisUitham** [comment]
As you can see from my edits i have been fiddling around trying to find a good query that catches all the missing sequences as well but I kept finding that it included other sequences as well. There seem to be at least a handful like the belgian and italian sequence, but i will keep it at the original query for now

**Comment by BorisUitham** [comment]
It's starting to look like it has higher incidence in england, ireland and spain.

**Comment by FedeGueli** [comment]
50 . super fast one it is doubling well under 10 days now

**Comment by FedeGueli** [comment]
cc @corneliusroemer should be designated before the release .

**Comment by FedeGueli** [comment]
Designated HK.6

**Comment by BorisUitham** [comment]
Thanks.
