### ISSUE TITLE
XBB.1.16 with S:T883I (159 seqs, mainly in the USA, 13 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2190]
_Transferred from sars-cov-2-variants/lineage-proposals#524_

**Defining Mutations:** `XBB.1.16` > `C7765T` > `C7081T, T22912C, C24210T(S:T883I)`
**Query:** `C7081T, T22912C, C24210T`
**Earliest seq:** 2023-04-11 (`EPI_ISL_17525649`, North Carolina, USA)
**Latest seq:** 2023-07-25 (`EPI_ISL_18097900`, Northern Ireland, UK)
**Sampled Countries:** USA (48), Canada (1, Ontario), Italy (1), Japan (1), UK(1)

<details><summary>Genomes: </summary>

`EPI_ISL_17525649, EPI_ISL_17525653, EPI_ISL_17580927, EPI_ISL_17589257, EPI_ISL_17608715-17608716, EPI_ISL_17620963, EPI_ISL_17689591, EPI_ISL_17699852, EPI_ISL_17768926, EPI_ISL_17768931, EPI_ISL_17839152, EPI_ISL_17852630, EPI_ISL_17855235, EPI_ISL_17856548, EPI_ISL_17885534, EPI_ISL_17885539, EPI_ISL_17950863, EPI_ISL_17955602, EPI_ISL_17965292, EPI_ISL_17971800, EPI_ISL_17971852, EPI_ISL_17971860, EPI_ISL_17976377, EPI_ISL_17979510, EPI_ISL_17989089, EPI_ISL_17992048, EPI_ISL_17992050, EPI_ISL_17996883, EPI_ISL_18009155, EPI_ISL_18009373, EPI_ISL_18011186, EPI_ISL_18012980, EPI_ISL_18030614, EPI_ISL_18043548, EPI_ISL_18046044, EPI_ISL_18050179, EPI_ISL_18053813, EPI_ISL_18053828, EPI_ISL_18057147, EPI_ISL_18057699, EPI_ISL_18072247, EPI_ISL_18072337, EPI_ISL_18079372, EPI_ISL_18079578, EPI_ISL_18079984, EPI_ISL_18080710, EPI_ISL_18080712, EPI_ISL_18080746, EPI_ISL_18080785, EPI_ISL_18080805, EPI_ISL_18097900`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c307_a6e930.json?f_userOrOld=uploaded%20sample

view from `C7765T` polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/8a350880-f751-4b29-858d-48316260d339)

details & diversity
![details](https://github.com/cov-lineages/pango-designation/assets/125747944/d936f4e9-c892-4fa3-884b-19572150ed5a)

**Trivia:**
- `C7765T` is one of the large undesignated XBB.1.16 branch, 242 out of 571 collected since June 1st (query: `A22101T, T28297C, C7765T`), there are also mutations like `S:E554Q` from neighbouring sub-branches (follows: `C7765T` > `T25779C` > `G23222C(S:E554Q)`, query: `C7765T, G23222C`, proposed sars-cov-2-variants/lineage-proposals#554
- `T22912C` is `S:N450` silent mutation

**Comment by FedeGueli** [comment]
Thank you for cleaning stale issues!
