### ISSUE TITLE
Potential FY.6 (XBB.1.22.1.6) and XBB.1.5* (with T17124C) recombinant, already has spike diversity of S:T478R or S:S939F then S:T572I (211 seqs, 12 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2191]
Transferred from sars-cov-2-variants/lineage-proposals#530

**Query:** `C2037T, T17124C, A22161G`
**Earliest seq:** 2023-03-29 (`EPI_ISL_17819055`, Davao, Philippines)
**Latest seq:** 2023-07-29 (`EPI_ISL_18097510`, Fukuoka, Japan)
**Sampled Countries:** Philippines (26), Japan (19), Australia (5), USA (4), China (3), Singapore (2), Canada (1), Germany (1), Italy (1), South Korea (1), Sweden (1)

**Recombinant Profile:** 
- Mutation gained on **FY.6**: `T17124C`
- Mutation lost on **FY.6**: `T2935C`
- ~~XBB.1.5 could contributed between two breakpoints within `2037 (ORF1a:A591)` to `2935` and `17124` to `22161 (S:Y200)`, both 3' and 5' end are from **FY.6** donor.~~ _OR_ as @FedeGueli [suggested](https://github.com/sars-cov-2-variants/lineage-proposals/issues/530#issuecomment-1663760049), there's one breakpoint possiblity that a certain XBB.1.5* with both `C2037T (ORF1a:A591V)` and  `T17124C` from 5' end, recombined XBB.1.22.1* from 3' end, breakpoint between `nuc 17124` to `nuc 22161 (Spike_Y200)`.

<details><summary>Genomes: </summary>

`EPI_ISL_17618343, EPI_ISL_17653060, EPI_ISL_17669269, EPI_ISL_17669271, EPI_ISL_17685392, EPI_ISL_17689338, EPI_ISL_17704344, EPI_ISL_17718856, EPI_ISL_17741717, EPI_ISL_17790405, EPI_ISL_17796559, EPI_ISL_17802590, EPI_ISL_17802872, EPI_ISL_17802904, EPI_ISL_17802906, EPI_ISL_17815658, EPI_ISL_17819033, EPI_ISL_17819038, EPI_ISL_17819054-17819055, EPI_ISL_17819063, EPI_ISL_17819083, EPI_ISL_17819200, EPI_ISL_17819204, EPI_ISL_17819213, EPI_ISL_17819223, EPI_ISL_17819229, EPI_ISL_17819258-17819259, EPI_ISL_17819306-17819309, EPI_ISL_17948680-17948681, EPI_ISL_17948686, EPI_ISL_17948729, EPI_ISL_17948865, EPI_ISL_17948878, EPI_ISL_17948922, EPI_ISL_17948933, EPI_ISL_17958377, EPI_ISL_17997390, EPI_ISL_18013358, EPI_ISL_18033978, EPI_ISL_18040384, EPI_ISL_18040386, EPI_ISL_18040442, EPI_ISL_18044090, EPI_ISL_18051833, EPI_ISL_18051836, EPI_ISL_18051926, EPI_ISL_18058420, EPI_ISL_18064407, EPI_ISL_18065832, EPI_ISL_18067007, EPI_ISL_18067295, EPI_ISL_18075777, EPI_ISL_18076390, EPI_ISL_18081996, EPI_ISL_18082406, EPI_ISL_18082801, EPI_ISL_18097389, EPI_ISL_18097510`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_107e0_a71090.json?f_userOrOld=uploaded%20sample

UShER now placed it under FY.6
![placement](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/cd26893d-a57b-4224-9ec6-4d45c6d22f92)

details
![details](https://github.com/cov-lineages/pango-designation/assets/125747944/9af4a40c-69a3-44de-bc4d-2f44031d154a)

**Trivia:**
- Thanks to @FedeGueli for the recombinant analysis.
![Schermata 2023-08-13 alle 17 52 18](https://user-images.githubusercontent.com/87669813/260313594-f8c65753-a161-4a9e-8d50-b69ac8d1495f.png)

**Comment by FedeGueli** [comment]
The 939F branch got designated FY.6.1
