### ISSUE TITLE
very new HK.3 (EG.5.1.1.3) sublineage with S:F157L (16 seqs in China)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#2193]
*Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/580

Defining mutations (EDITED):
HK.3>C22033A (S:F157L)
GISAID query: G5720A, G13627A, G22927T, C22033A (EDITED)
Earliest seq: 2023-07-31 (Hubei Province, China- EPI_ISL_18078259)
Most recent seq: 2023-08-09 (Hubei Province, China- EPI_ISL_18105520)
Countries detected: China (16)

Usher Tree:
<img width="903" alt="屏幕截图 2023-08-20 163829" src="https://github.com/cov-lineages/pango-designation/assets/121703496/1cb2ccd1-0ec8-44ec-b32d-f1b30cd3a5e0">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1af0d_1cfdd0.json?c=gt-S_157

Another branch with S:F157L (which has emerged in EG.5.1.6 lineages). HK.3 is one of lineages with L455F-F456L "exchange" Combo mutations, and this branch (with S:F157L) popped up very recently (in last 15 days). Rapid view may be needed.

*One seq further gets S:A484S and S:G485D
<img width="260" alt="屏幕截图 2023-08-16 174618" src="https://github.com/cov-lineages/pango-designation/assets/121703496/068eea11-38df-490f-b3af-ebc1d0c3a5c3">

Genomes: (EDITED)
EPI_ISL_18078259, EPI_ISL_18078261-18078262, EPI_ISL_18078265-18078266,
EPI_ISL_18078268-18078269, EPI_ISL_18105513, EPI_ISL_18105515-18105518,
EPI_ISL_18105520, EPI_ISL_18108422, EPI_ISL_18108617,
EPI_ISL_18114704

**Comment by FedeGueli** [comment]
> Today Shanghai updated 2 seqs with S:F157L but without S:Q146K(?) and ORF1a:T4129I.

i suggest to ignore 146

**Comment by aviczhl2** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/bc8ea950-75c2-44ea-94bd-db2e45f99f2b)

Not all have Orf1a:T4129I

**Comment by FedeGueli** [comment]
> ![image](https://user-images.githubusercontent.com/10445944/261764868-bc8ea950-75c2-44ea-94bd-db2e45f99f2b.png)
> 
> Not all have Orf1a:T4129I. Maybe shall adjust the proposal to S:F157L only.

Please broaden it to just S:F157L @HynnSpylor

**Comment by FedeGueli** [comment]
(it is actually the fastest on earth so better to track it completely)

**Comment by ryhisner** [comment]
Thank you for including the partially unaliased Pango name in the title @aviczhl2. With the proliferation of new designations, I think this should be standard practice here. Only the legendary @FedeGueli is capable of knowing and remembering them all!

The S:E484S-G485D combo is fascinating. I believe it's the only sequence ever to possess those two mutations.

Also interesting is the S:T19L branch. A few months ago I think I remember a number of sequences with T19L popping up around the same time. Haven't seem as many lately though.

**Comment by HynnSpylor** [comment]
Thanks for reminding me! @FedeGueli 
I have edited the title and definition.

**Comment by FedeGueli** [comment]
Designated HK.3.1 from https://github.com/cov-lineages/pango-designation/commit/2d2cdd668e05e9ae1a6ca247d1e9833f1155e24e

**Comment by FedeGueli** [comment]
Milestone missing @corneliusroemer

**Comment by FedeGueli** [comment]
> Milestone missing @corneliusroemer
i ll add it in the original issue sorry i was thinking it was a direct proposal. so @HynnSpylor you can close this one

**Comment by FedeGueli** [comment]
Cor nleius i was lookin at the new feature in the nextclade tree , like looking at frameshift. It points 1 for HK.3.1 is rellay there? let me check it.

**Comment by FedeGueli** [comment]
![Schermata 2023-08-25 alle 15 38 08](https://github.com/cov-lineages/pango-designation/assets/87669813/5a17514b-04f4-4fdc-9602-013bea2d13f8)
I dont see any likely some tree building stuff. sorry for bothering @corneliusroemer
