### ISSUE TITLE
Another EG.5.1.1 with S:L455F via G22927C (90 seqs, China, South Korea)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2194]
_Taken from **Branch 3** of multitask tracker sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** `EG.5.1.1` > `C11779T` > `C6781T, C17802T, G22927C`(**S:L455F**)
**Query:** `C6781T, C17802T, G22927C`
**Earliest seq:** 2023-07-04 (`EPI_ISL_17994488`, Shanghai, China)
**Latest seq:** 2023-07-24 (`EPI_ISL_18105818`, Shanghai, China)
**Sampled Countries:** China (17, Shanghai)

<details><summary>Genomes: </summary>

`EPI_ISL_17994488, EPI_ISL_18074751, EPI_ISL_18074754, EPI_ISL_18105750, EPI_ISL_18105752, EPI_ISL_18105756-18105765, EPI_ISL_18105768, EPI_ISL_18105818`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_172f6_cd0e70.json?f_userOrOld=uploaded%20sample&label=id:node_6790894
![Branch3](https://github.com/cov-lineages/pango-designation/assets/125747944/14b03776-a5cc-476b-babf-1e6bf449b2a8)

**Comment by aviczhl2** [comment]
33 seqs now.

**Comment by aviczhl2** [comment]
It becomes 43 after the new Shanghai upload.

**Comment by FedeGueli** [comment]
@corneliusroemer super ping here.

**Comment by aviczhl2** [comment]
62 seqs now

**Comment by corneliusroemer** [comment]
I've been watching this for a while and would have designated if it was not phylogenetically unstable and mostly restricted to Shanghai. It's notably got G22927C instead of G22927T (put this into the issue title next time as that's probably the most interesting thing about this lineage right now).

Somehow I'm not sure this isn't an artefact, especially as Shanghai seems to have another lineage of G22927C but on top of EG.5.1 rather than EG.5.1.1.

**Comment by corneliusroemer** [comment]
I've designated a few more EG.5.1 + 455F, but there's so much homoplasy, it's hard to tell what's real and what's actually an artefact branch of an another already designated lineage.

**Comment by FedeGueli** [comment]
> Thanks @corneliusroemer
> 
> there are two lineages that seemingly misplacement with weird reversions, one [pointed out](https://github.com/cov-lineages/pango-designation/commit/f6556710dd5e198e827b227bd3db24ae11b45c74#commitcomment-126187019) by @FedeGueli on [f655671](https://github.com/cov-lineages/pango-designation/commit/f655671), for mostly Danish seqs.
> 
> there's another follows EG.5.1.1 > `C22264T` > `G22927T(S:L455F)` > _T22264C_reversion_ for mostly Finnish seqs.
> 
> https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_404dd_2012c0.json?c=gt-nuc_22264&gmax=23264&gmin=21264&label=id:node_6941300 ![image](https://user-images.githubusercontent.com/125747944/265072126-39b2e93c-cd2a-4062-8f48-7983a5be7fd4.png)
> 
> could you check those lineages @AngieHinrichs ?
> 
> aside of those, the rest can be monitored for some time to see if they are potential artifact either by phylogenetic assessment or sequencing.

thx , @AngieHinrichs could you check please? 

cc @corneliusroemer it could also recombination between similar lineages? they all or  quite all have been bred in the same country and in the same timeframe and exceptionally fit well over other lineages so not unlikely coinfecting people ?

**Comment by corneliusroemer** [comment]
Let's wait and see. The fact it's mostly one city/lab is very suspicious.

**Comment by aviczhl2** [comment]
> Let's wait and see. The fact it's mostly one city/lab is very suspicious.

Worth noticing the 63th seq comes from Anhui, the first outside Shanghai. 

Let's wait for it to appear in another country?

**Comment by aviczhl2** [comment]
+1 Sichuan
