### ISSUE TITLE
New Linage proposal: B.1.177.637

### ISSUE THREAD

**Issue by PathoGenOmics** [cov-lineages/pango-designation#22]
# New Linage proposal: B.1.177.637
 **Suggested by:** Paula Ruiz-Rodriguez and Mireia Coscolla
### Description:
**Sublineage of:** B.1.177
**Proposed name:** B.1.177.637
**Earliest sequence:** 2020-06-29
**Latest sequence:** 2021-02-06
**Countries circulating:** United Kingdom, Spain, France, Italy, Gibraltar, Denmark, Ireland, Norway, Switzerland, Hong Kong, Belgium, Portugal, Poland, Canada, China, Singapore, Japan, South Korea, Czech Republic, Austria, Luxembourg, Germany, Netherlands.

### Genomes:
[B.1.177.637.txt](https://github.com/cov-lineages/pango-designation/files/6070644/B.1.177.637.txt)

### Mutations of B.1.177.637:

Nucleotide   position | Reference | Mutation | Type of mutation | Protein | Amino acid   replacement
-- | -- | -- | -- | -- | --
445 | T | C | synonymous_variant | ORF1ab | V60V
3037 | C | T | synonymous_variant | ORF1ab | F924F
6286 | C | T | synonymous_variant | ORF1ab | T2007T
14408 | C | T | missense_variant | ORF1ab | P4715L
21255 | G | C | synonymous_variant | ORF1ab | A6997A
22227 | C | T | missense_variant | S | A222V
23403 | A | G | missense_variant | S | D614G
25049 | G | T | missense_variant | S | D1163Y
25062 | G | T | missense_variant | S | G1167V
26801 | C | G | synonymous_variant | M | L93L
28657 | C | T | synonymous_variant | N | D128D
28932 | C | T | missense_variant | N | A220V
29366 | C | T | missense_variant | N | P365S
29645 | G | T | missense_variant | ORF10 | V30L

### Evidence:
![B 1 177_and_B 1 177 637_phylo](https://user-images.githubusercontent.com/79568662/109690731-f28b9480-7b86-11eb-97e7-d4e3559f8b01.png)

**Comment by PathoGenOmics** [comment]
One of the major characteristics that characterize this possible lineage is the co-occurrence of D1163Y and G1167V (In the S protein) which is only found in this clade.
The publication associated with mentioned lineage: https://www.medrxiv.org/content/10.1101/2021.03.08.21253075v1
Twitter thread explaining it:  https://twitter.com/gen_uv/status/1370384465076322305?s=20

**Comment by chrisruis** [comment]
Hi, thanks very much for submitting this. To be designated as a Pango lineage, a clade needs to be associated with an epidemiological event, such as an introduction into a new country, and exhibit onward transmission within that new region. We've recently run through the B.1.177 tree and identified 87 B.1.177 sublineages that currently meet the requirements, outlined [here](https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt). Where there's lots of mixing between countries without clear evidence of onward transmission within a country, the sequences retain the parental lineage. I've run the sequences you submitted through the new pangolin that contains the B.1.177 sublineages and the sequences are mostly assigned to B.1.177 and B.1.177.11 under the new lineage classifications. This is the pangolin output:
[lineage_report.txt](https://github.com/cov-lineages/pango-designation/files/6278621/lineage_report.txt). Under the Pango rules, I don't think there's a justification for a new B.1.177 sublineage in this case but these sequences fall into multiple current lineages. Thanks again for you submission
