### ISSUE TITLE
Mini Saltation Branch of XBB.1.5.18 with S:W152R, S:K478R and multiple Orf  mutations, a branch with S:E554Q  (at 09-26 ,74 seq, 6 countries for main,  seq for branch 22 US, 1 Dom R, 1 Italy) 

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#2201]
Sublineage of: XBB.1.5(.18 likely as it also contains Orf1a:T2300I as of XBB.1.5.18)
Mutations on top of XBB.1.5.18*: ORF1a:G2265S,ORF1a:V2779A,S:W152R,S:T478R->,ORF1a:A2345V,,ORF1a:A2345V (and other silent ones)
Gisaid Inquiry: A5821G,C7299T
Earliest Seq: EPI_ISL_17789137 CA, USA, 05-26, 2023
Latest Seq:  EPI_ISL_18115293, NY, USA, 08-05, 2023
Sequence List: EPI_ISL_17789137, EPI_ISL_17799169, EPI_ISL_17849241,
EPI_ISL_17850072, EPI_ISL_17851510, EPI_ISL_17851544,
EPI_ISL_17852362, EPI_ISL_17871626, EPI_ISL_17872403,
EPI_ISL_17955645, EPI_ISL_17955804, EPI_ISL_17955836,
EPI_ISL_17956205, EPI_ISL_17971502, EPI_ISL_17990159,
EPI_ISL_17996287, EPI_ISL_18008766, EPI_ISL_18022489,
EPI_ISL_18038416, EPI_ISL_18045508, EPI_ISL_18055139,
EPI_ISL_18057938, EPI_ISL_18058233, EPI_ISL_18058240,
EPI_ISL_18059494, EPI_ISL_18069788, EPI_ISL_18081428,
EPI_ISL_18081449, EPI_ISL_18104306, EPI_ISL_18104591,
EPI_ISL_18104665, EPI_ISL_18104738, EPI_ISL_18107595,
EPI_ISL_18107638, EPI_ISL_18114216, EPI_ISL_18114279,
EPI_ISL_18115293

Distribution: 4 Canada, 7 Dominican Republic, 1 Italy, the rest USA
There is a further branch defined by S:E554Q, that is given by the following search
Gisaid Inquiry: A5821G,C7299T,G23222C

Earliest Sequence: EPI_ISL_17850072 Italy, 06-10, 2023
Latest Sequence: EPI_ISL_18104665 US, 07-31, 2023
Sequences: EPI_ISL_17850072, EPI_ISL_17956205, EPI_ISL_18008766,
EPI_ISL_18045508, EPI_ISL_18081428, EPI_ISL_18081449,
EPI_ISL_18104306, EPI_ISL_18104665, EPI_ISL_18114216,
EPI_ISL_18114279
DIstribution: 1 Italy, 1 Dominican Republic, the rest US

Trees for those branches: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42de1_2db820.json?f_userOrOld=uploaded%20sample
<img width="937" alt="A8C5DB27-FAAC-4C3C-AC22-203DC0D3CE8C" src="https://github.com/cov-lineages/pango-designation/assets/131021067/7f011b16-d177-4256-b350-3912b102d2a1">
And this is a figure showing how recently this branch become quite significant among its XBB.1.5.18* parent.
<img width="976" alt="54713D45-03FE-4B64-9606-6F5FB45BC791" src="https://github.com/cov-lineages/pango-designation/assets/131021067/9de0556c-6173-4bc6-9648-ad5e96ca8e43">

S:554Q is predicted by the jbloom lab calculator to be beneficial on XBB.1.5* basis, and it is similar to S:554Q, so I would closely monitor this branch.

**Comment by FedeGueli** [comment]
Originally proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/275

**Comment by krosa1910** [comment]
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4040_aa4130.json
The newest usher tree.

**Comment by FedeGueli** [comment]
![Schermata 2023-09-08 alle 11 15 50](https://github.com/cov-lineages/pango-designation/assets/87669813/144527ad-d166-469f-917f-5c7c41346f75)
to me this is very interesting .

**Comment by krosa1910** [comment]
Up to 61/19, no new country added.

**Comment by krosa1910** [comment]
Unable to compete with EG.5.1*, closing it for now unless new saltations or branches rise
![2662187734](https://github.com/cov-lineages/pango-designation/assets/131021067/152010e0-dcd8-4a68-92fb-00f60cd5a3a0)

**Comment by krosa1910** [comment]
Update, would watch it.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_21226_a09eb0.json?f_userOrOld=uploaded%20sample&label=id:node_1092004
<img width="1199" alt="Screenshot 2023-10-13 at 11 26 13 PM" src="https://github.com/cov-lineages/pango-designation/assets/131021067/d81128c8-48b1-477a-85d9-e038a6341b61">
The further branch with 1184Y seems to be something.

**Comment by FedeGueli** [comment]
@krosa1910 reopen this one it is still circualting with a lot of diversity in the tree and some recent samples:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_23ef7_351970.json?label=id:node_3729094
![Schermata 2023-11-14 alle 12 14 22](https://github.com/cov-lineages/pango-designation/assets/87669813/4777deb8-563d-42d0-b7bf-834781c75977)
![Schermata 2023-11-14 alle 12 14 37](https://github.com/cov-lineages/pango-designation/assets/87669813/e55ecb5d-6d67-4687-9ab5-80048f7374f9)

95 now in the main 478R branch
