### ISSUE TITLE
XBB.1.5  sublineage with S:L455F, S:F456L, C14085T, A14634G and C19488T

### ISSUE THREAD

**Issue by ighorarantes** [cov-lineages/pango-designation#2203]
By Rede Genômica Fiocruz

#Description:

We found a highly supported clade of XBB.1.5. sequences (n = 83) harboring mutation S:L455F, S:F456L, C14085T, A14634G and C19488T mostly from Brazil (n = 53, 64%), USA (n = 18, 22%) and Europe (n = 11, 13%).

Defining mutations:  S:L455F, S:F456L, C14085T, A14634G and C19488T

Gisaid query: S:L455F, S:F456L, C14085T, A14634G and C19488T

Earliest sequence: EPI_ISL_17737679, Brazil 2023-03-11

Latest sequence: EPI_ISL_18119349, USA 2023-08-11

Lineage Collection: GISAID Identifier: EPI_SET_230821ka
doi: 10.55876/gis8.230821ka

![hcov_19_xbb_L455F_F456L_n474 fasta treefile](https://github.com/cov-lineages/pango-designation/assets/108748180/3294b33d-16b5-40f5-8d23-c3addaa35d28)

**Comment by corneliusroemer** [comment]
Could this be a recombinant involving XBB.1.5.70? XBB.1.5.70 also has the same mutations at 455F and 456L. Or just convergent evolution?

**Comment by FedeGueli** [comment]
Duplicate of #2071
