### ISSUE TITLE
New XBB.1.5+S:F456L+Orf1b:A1547S,S:K304N (81 seqs, 17 countries, 5% Ecuador)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2205]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/550

XBB.1.5(with 17124C but without 10204C)+C23506T+C2245T,T22930A(S:F456L),C28657T+G18106T(Orf1b:A1547S),A22474T(S:K304N)

GISAID query: C23506T,C2245T,A22474T
No. of seqs: 10(Spain 6 China 1 UK 2 France 1)

9 on GISAID, also CLIMB_CM7Y8Q7R not on GISAID

First: EPI_ISL_180118130, Spain, 2023-6-9
Latest: EPI_ISL_18118822, Spain, 2023-7-30

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/xbb_1_5_f456l_k304n.json?label=id:node_7036067)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/ed752f0c-df61-40ae-9494-0ff1b1904ae2)

**Comment by aviczhl2** [comment]
20 now, doubled in the past week, also in Sweden.

**Comment by aviczhl2** [comment]
29, New Zealand.

**Comment by aviczhl2** [comment]
Includes a GBW-H10/20 duplicate and there are 2 USA-traveler from Belgium.

**Comment by aviczhl2** [comment]
40, Italy, Romania

**Comment by aviczhl2** [comment]
56, Israel

**Comment by FedeGueli** [comment]
This is slowing down i think.

**Comment by aviczhl2** [comment]
59, Austria, Switzerland

**Comment by aviczhl2** [comment]
> This is slowing down i think.

Yeah, but entering many new countries.

**Comment by aviczhl2** [comment]
63, Germany

**Comment by aviczhl2** [comment]
70, Japan, Slovenia

**Comment by aviczhl2** [comment]
79, Ecuador

**Comment by FedeGueli** [comment]
2/42 sequences uploaded from Ecuador in October

**Comment by corneliusroemer** [comment]
Yeah I think it's XBB.1.5.108 but for certainty check that the GISAID queried samples match the designated

**Comment by aviczhl2** [comment]
> Yeah I think it's XBB.1.5.108 but for certainty check that the GISAID queried samples match the designated

Yeah it is.
