### ISSUE TITLE
XBB.1.16.6 (S:F456L) with S:L455F emerging in Florida (14 seqs) representing the first lineage carrying FLip+S:478 worth to be designated

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2207]
Transferred from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/531#issuecomment-1689281906

I was monitoring this sublineage of XBB.1.16.6 since it was one sequence only when i realized it got convergently S:L455F, the infamous FLip emerging combo.

As today it reached 14 sequences so it is better to propose it here (ping @corneliusroemer ):

Defining mutations:
XBB.1.16.6 >> C8947T > A10861G > T23986C > S:L455F (G22927T)

Gisaid query: G22927T, A10861G,T12730A,-C27937T

Samples: 14 
hCoV-19/USA/NJ-GBW-H10-016-0401/2023 | EPI_ISL_17971832 | 2023-06-27
hCoV-19/USA/FL-CDC-LC1046276/2023 | EPI_ISL_18037649 | 2023-07-12
hCoV-19/USA/FL-CDC-VSX-A352095/2023 | EPI_ISL_18060741 | 2023-07-20
hCoV-19/USA/FL-CDC-QDX83126253/2023 | EPI_ISL_18095896 | 2023-07-23
hCoV-19/USA/FL-CDC-QDX83301046/2023 | EPI_ISL_18104574 | 2023-07-29
hCoV-19/Sweden/C-03_SE600_000200603582N2/2023 | EPI_ISL_18109943 | 2023-08-02
hCoV-19/England/CLIMB-CM7YROYW/2023 | EPI_ISL_18112134 | 2023-08-03
hCoV-19/USA/NY-CDC-QDX83578845/2023 | EPI_ISL_18121762 | 2023-08-04
hCoV-19/USA/NY-CDC-QDX83578896/2023 | EPI_ISL_18121850 | 2023-08-05
hCoV-19/Sweden/C-03_SE600_000200604575N2/2023 | EPI_ISL_18109991 | 2023-08-06
hCoV-19/France/IDF-IPP16944/2023 | EPI_ISL_18123393 | 2023-08-07
hCoV-19/USA/FL-CDC-LC1050116/2023 | EPI_ISL_18126444 | 2023-08-07
hCoV-19/USA/NC-CDC-LC1050118/2023 | EPI_ISL_18126456 | 2023-08-08
hCoV-19/USA/CA-GBW-H20-330-3973/2023 | EPI_ISL_18125015 | 2023-08-10 (Travel related to Mexico)

Tree:
![Schermata 2023-08-23 alle 16 45 03](https://github.com/cov-lineages/pango-designation/assets/87669813/30650bc9-188c-4fa3-b493-4a1139479c1f)

![Schermata 2023-08-23 alle 16 44 34](https://github.com/cov-lineages/pango-designation/assets/87669813/5d4e13ba-c2db-4af6-9ec1-6d1a20fdc7ee)

Countries:
![Schermata 2023-08-23 alle 16 45 42](https://github.com/cov-lineages/pango-designation/assets/87669813/2eaeb6d2-d6a5-4001-814b-e1bb50a46a49) + Mexico

Growth advantage over EG.5.1.1: for future monitoring when the number of sequences will be enough to give a reliable result
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=G22927T%2CA10861G%2CT12730A%2C27937C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Designated JF.1 via https://github.com/cov-lineages/pango-designation/commit/7e6a6613234930ff49365e7984615e9ad93e1b63

i will put the milestone in the original issue to smplify the thing.

**Comment by corneliusroemer** [comment]
Oh, now I get what the FLip means, it's the S:L455F, S:F456L mutation. Was wondering what all these FLips meant in titles ;)
