### ISSUE TITLE
EG.5.1.4+Orf3a:P240L+S:L455F,Orf3a:I47V Exploding in Japan(27 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2208]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/644

EG.5.1.4+C26111T(Orf3a:P240L)+G22927T,A25531G(S:L455F,Orf3a:I47V)

GISAID query:G22927T,A25531G,C26111T
No. of seqs: 18(Japan 16(Chiba, Tokyo, Kagawa, Hyogo,Tochigi) Hong Kong 1 Yunnan 1)

First: EPI_ISL_17997269, Hong Kong, 2023-6-29
Latest: EPI_ISL_18123086, Chiba, 2023-8-7

EG.5.1 is the current best backbone, S:L455F+S:F456L is the fittest Spike combo, Orf1b:2557 in EG.5.1.4 is also a fitness mutation, and Orf3a:P240L/I47V both have good fit advantage on Bloom and Neher estimates. 

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/EG_5_1_4_l455f.json?label=id:node_6904825)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/596de643-037c-412b-8191-1b4c79c0619f)

**Comment by FedeGueli** [comment]
Designated JJ.1 via https://github.com/cov-lineages/pango-designation/commit/36e3fb099782e00f74e2ea4d9843cebe5aa48b60 milestone added to original issue

**Comment by FedeGueli** [comment]
milestone removed from the original issue.
