### ISSUE TITLE
EG.5.1.3/XBB.1.16.19 recombinant in USA and Canada (162 seqs, 3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2210]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/600

Mutations on top of EG.5.1: T2334C(rev), A5720G(rev), T5422C, C7044A, T9693C(rev), C22570T, C27507A(rev), G27065A, A28182G, A28447G, T29625C(rev) C29386T

XBB.1.16.19---EG.5.1.3---XBB.1.16.19
Breakpoint 1: between 9694 and 11749
Breakpoint 2: between 22996 and 27064

Private mutations: T5422C, C7044A(Orf1a:P2260H), G27065A,A28182G(Orf8:S97G)
T5422C, C7044A, G27065A are from an American XBB.1.16.19 branch. A28182G is unique. 

Usher places it under EG.5.1.1 but it has all 3 EG.5.1.1 defining mutations reverted.

It has one of the EG.5.1.3 defining mutations (C22570T) and the other defining mutation for EG.5.1.3(C1889T) is on XBB.1.16 part. So the EG.5.1-side donor is likely EG.5.1.3.

This one is basically EG.5.1-spike with XBB.1.16-Orf9b.

GISAID query: C22570T, G27065A,A28182G
No. of seqs: 16(USA 12(7 states), Canada 4)

FIrst: EPI_ISL_18095385, Utah, 2023-7-12
Latest: EPI_ISL_18129876, Canada, 2023-8-14

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/EG_5_1_3_XBB_1_16_19_recomb.json?f_userOrOld=uploaded%20sample&label=id:node_6908206)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/7cc739ba-3ae8-4728-b331-4fa08f7ac67e)

**Comment by FedeGueli** [comment]
One more from Oregon

**Comment by FedeGueli** [comment]
43

**Comment by aviczhl2** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/e2ddfcb8-3a1a-4a9e-8428-c08e54185ce5)

Usher now treats this as a sibling branch of EG.5.1.3

**Comment by aviczhl2** [comment]
102 now  @corneliusroemer @InfrPopGen

**Comment by aviczhl2** [comment]
134 now, a lot of new seqs from Japan.

**Comment by JosetteSchoenma** [comment]
XCV

**Comment by JosetteSchoenma** [comment]
This turned up in the Netherlands. 1 sample. 177 in totaal now.
