### ISSUE TITLE
XBB.1.5 with ORF8:I47V and S:F456L (154 seqs, mainly in Spain, 14 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2213]
transferred from sars-cov-2-variants/lineage-proposals#544

**Defining Mutations:** `XBB.1.5 [T17124C > T23018C]` > `A21366T` > `C6268T` > `C29119A` > _`A28032G(ORF8:I47V)`_ > `T22928C(S:F456L)`
**Query:** `C6268T, A21366T, T22928C, -A17799G`
**Earliest seq:** 2023-03-03 (`EPI_ISL_17482561`, Granada, Andalusia, Spain)
**Latest seq:** 2023-08-08 (`EPI_ISL_18119310`, New York, USA)
**Sampled Countries:** Spain (84), France (7), USA (6), Austria (5), Canada (2), Japan (1), Switzerland (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17482561, EPI_ISL_17678943, EPI_ISL_17678953, EPI_ISL_17678956-17678957, EPI_ISL_17679065, EPI_ISL_17679082, EPI_ISL_17679149, EPI_ISL_17679153, EPI_ISL_17679159, EPI_ISL_17679168, EPI_ISL_17679171, EPI_ISL_17679259, EPI_ISL_17679278-17679282, EPI_ISL_17679286-17679290, EPI_ISL_17679626, EPI_ISL_17734964, EPI_ISL_17734967, EPI_ISL_17768521, EPI_ISL_17768655, EPI_ISL_17777136, EPI_ISL_17780240, EPI_ISL_17780242-17780243, EPI_ISL_17780704, EPI_ISL_17780717, EPI_ISL_17780929, EPI_ISL_17782437, EPI_ISL_17782553, EPI_ISL_17782555, EPI_ISL_17782600, EPI_ISL_17787138, EPI_ISL_17787184, EPI_ISL_17795955, EPI_ISL_17797658, EPI_ISL_17817656, EPI_ISL_17817827, EPI_ISL_17817842, EPI_ISL_17830600, EPI_ISL_17833506, EPI_ISL_17878362, EPI_ISL_17881269, EPI_ISL_17948501, EPI_ISL_17948521, EPI_ISL_17948561-17948562, EPI_ISL_17948579, EPI_ISL_17948588, EPI_ISL_17948661, EPI_ISL_17949008, EPI_ISL_17949030, EPI_ISL_17949033, EPI_ISL_17949096, EPI_ISL_17949322, EPI_ISL_17949395-17949396, EPI_ISL_17949583-17949584, EPI_ISL_17949611, EPI_ISL_17949972, EPI_ISL_17973561, EPI_ISL_17974798, EPI_ISL_17976571, EPI_ISL_17989173, EPI_ISL_17989180, EPI_ISL_17989973, EPI_ISL_17990075, EPI_ISL_17990079, EPI_ISL_17990086, EPI_ISL_17990123, EPI_ISL_18042102, EPI_ISL_18042238, EPI_ISL_18042286, EPI_ISL_18042311, EPI_ISL_18042318, EPI_ISL_18044763, EPI_ISL_18058870-18058871, EPI_ISL_18067322, EPI_ISL_18071571, EPI_ISL_18071573, EPI_ISL_18094813-18094814, EPI_ISL_18094875, EPI_ISL_18099821, EPI_ISL_18104963, EPI_ISL_18104965, EPI_ISL_18109058, EPI_ISL_18109062, EPI_ISL_18109072, EPI_ISL_18112422, EPI_ISL_18112542, EPI_ISL_18118118-18118121, EPI_ISL_18118310, EPI_ISL_18118392, EPI_ISL_18118534, EPI_ISL_18118657, EPI_ISL_18119310, EPI_ISL_18129928`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_13ae0_891540.json?label=id:node_7246444
![diversity](https://github.com/cov-lineages/pango-designation/assets/125747944/171c5318-3324-4877-b73b-b6cfe5555c99)

**Trivia:**
- There's a side branch also got `S:F456L`, follows:  `XBB.1.5 [T17124C > T23018C]` > `A21366T` > `C6268T` > `C2189T(ORF1a:L642F), A17799G, T22928C(S:F456L)` [Query: `C2189T, A17799G, T22928C`, 4 seqs, 08/21] , that is why the query for main proposal is using `-A17799G` to filter it out.

**Comment by FedeGueli** [comment]
119 from  9 countries . 

although covspectrum gives it low chances https://cov-spectrum.org/explore/Spain/AllSamples/from%3D2023-05-29%26to%3D2023-08-31/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C6268T%2CA21366T%2CT22928C&analysisMode=CompareToBaseline& 

i think it is worth designating it .

**Comment by FedeGueli** [comment]
This is slow and slowed further  not sure @corneliusroemer is prone to designate this kind of lineage. Likely better closing it , i m sorry for the long tracking @NkRMnZr .
