### ISSUE TITLE
Potential FL.1.5.1 x BQ.1.2.2 Recombinant, Nigeria, Canada and US (9 seqs as of 2023-08-30)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#2215]
As preproposed here: https://github.com/sars-cov-2-variants/lineage-proposals/issues/630

**Query**: T2128C, T18096C, C28163A
**Earliest sequence**: EPI_ISL_18110467, 2023-07-20, Nigeria
**Most recent sequence**: EPI_ISL_18126488, 2023-08-08, US-NJ

![image](https://github.com/cov-lineages/pango-designation/assets/86835836/aa27d9c3-0384-470c-a612-5b50b7b6608e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37ef4_94ca10.json?c=gt-nuc_2128&label=id:node_10765449

Breakpoint is likely somewhere between nuc 23665 (spike 701) and 25415 (ORF3a 8). Everything upstream is from a FL.1.5.1 donor, and everything from 25416 to 3' is from BQ.1.2.2 donor.

Unique AA changes donated by BQ.1.2.2: ORF3:255/258del, ORF8:C90stop
![image](https://github.com/cov-lineages/pango-designation/assets/86835836/b53c8b71-2a93-4052-8f7a-d672452ef888)

**Sequences**: EPI_ISL_18098706, EPI_ISL_18110467, EPI_ISL_18110470, EPI_ISL_18111443 (low quality), EPI_ISL_18119590, EPI_ISL_18119920, EPI_ISL_18126488

**Comment by FedeGueli** [comment]
One more sample: EPI_ISL_18138544 collected at NYc JFK airport surveillance pooled sample on 13/08

**Comment by FedeGueli** [comment]
![Schermata 2023-08-27 alle 22 34 31](https://github.com/cov-lineages/pango-designation/assets/87669813/0a5bb94b-454b-4ca6-80a8-45e312ca3edb)

**Comment by c19850727** [comment]
Yes Fede I believe so and thanks!

**Comment by c19850727** [comment]
One more from Canada-NS, EPI_ISL_18160866

**Comment by JosetteSchoenma** [comment]
XCK
