### ISSUE TITLE
Proposal for sublineage of AY.4 with S:P26S

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#222]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: AY.4
Earliest sequence: UK 2021-19, then Portugal in 28, Ireland in 29, Switzerland/Sweden in 30
Most recent sequence: Current
Countries circulating: Originally UK, but now mostly Sweden, Switzerland and Germany plus most European countries at low levels

Lineage deriving from AY.4 but with extra Spike mutation S:P26S which was also part of Gamma and is hence of potential special interest. It seems to have grown without strong founder effect. There's a sub-lineage of this proposed lineage that has another Spike mutation S:L54F in addition. This sub-sub-lineage of AY.4 is the one that is slowly but steadily growing in Switzerland, Sweden and Germany. Since S:P26S is in itself interesting, I suggest to keep the net wider for now. Should the S:L54F sub-lineage grow further it could become a daughter of this one.

<html><head></head><body>

Country | Total Variant Sequences | First seq. found at | Last seq. found at |  
-- | -- | -- | -- | --
Austria | 1 | 2021-33 | 2021-33 |  
Belgium | 6 | 2021-34 | 2021-36 |  
Bulgaria | 1 | 2021-32 | 2021-32 |  
Czechia | 5 | 2021-35 | 2021-36 |  
Denmark | 23 | 2021-30 | 2021-36 |  
Finland | 2 | 2021-33 | 2021-34 |  
France | 3 | 2021-32 | 2021-34 |  
Germany | 84 | 2021-31 | 2021-36 |  
Iceland | 1 | 2021-33 | 2021-33 |  
Ireland | 17 | 2021-29 | 2021-35 |  
Italy | 4 | 2021-31 | 2021-37 |  
Lithuania | 1 | 2021-33 | 2021-33 |  
Netherlands | 1 | 2021-34 | 2021-34 |  
Norway | 2 | 2021-34 | 2021-34 |  
Portugal | 4 | 2021-28 | 2021-31 |  
Romania | 1 | 2021-36 | 2021-36 |  
Slovenia | 7 | 2021-31 | 2021-33 |  
Sweden | 78 | 2021-30 | 2021-36 |  
Switzerland | 39 | 2021-30 | 2021-36 |  
United Kingdom | 505 | 2021-19 | 2021-37 |  
United States | 1 | 2021-34 | 2021-34

</body></html>

![image](https://user-images.githubusercontent.com/25161793/134748861-2ccfa3c2-c125-44f0-937d-1854b8c82c06.png)

See here for further details: https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22s%3A26S%22%2C%22orf1a%3A2529v%22]%7D%2C%22matchPercentage%22%3A1%7D

Genomes
[ay_4_P26S.txt](https://github.com/cov-lineages/pango-designation/files/7228758/ay_4_P26S.txt)

Evidence
![image](https://user-images.githubusercontent.com/25161793/134748773-836f4897-9abb-41a5-a7c2-bcb85bf3e2f9.png)
See here for Usher tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_128de_e43110.json?branchLabel=Spike%20mutations&label=nuc%20mutations:G4181T,C6402T,C7124T,C8986T,G9053T,C10029T,A11201G,A11332G,C19220T,C27874T,G28916T

Proposed lineage name
AY.4.2

**Comment by FedeGueli** [comment]
Hi @corneliusroemer i noticed an AY.4 sub clade with S:54F that arose independently, from the S:P26S one,in Norway.
It reached 6% and it is still there.
![Schermata 2021-10-16 alle 23 35 26](https://user-images.githubusercontent.com/87669813/137614196-640d81b1-1d72-4f73-ac03-6cd2bae53eb6.png)

![Schermata 2021-10-17 alle 08 19 23](https://user-images.githubusercontent.com/87669813/137614260-a2b1d2d3-d888-46a1-b843-758deeb482cb.png)


Maybe it would be worth to assign a lineage to avoid missassignment between the two.
