### ISSUE TITLE
FL.10 saltation with ORF1a:G4178S, ORF1b:N1382S, S:K356T, S:T523N, ORF3a:D27N, ORF7b:N38I, N:K373N, N:D415E (14 seqs, Canada and USA)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2220]
_transferred from sars-cov-2-variants/lineage-proposals#527_

**Defining Mutations:** `FL.10` > `C18888T` > `T11422C, G12797A(ORF1a:G4178S/nsp9_G38S), A17612G(ORF1b:N1382S/nsp13_N459S), A22629C(S:K356T), C23130A(S:T523N), G25471A(ORF3a:D27N), A27868T(ORF7b:N38I), G29392C(N:K373N), C29518A(N:D415E)`
**Query:** `A22629C, C23130A, G25471A`
**Earliest seq:** 2023-06-10 (`EPI_ISL_17821379`, Alberta, Canada)
**Latest seq:** 2023-08-07 (`EPI_ISL_18129707`, Alberta, Canada)
**Sampled Countries:** Canada (11: Alberta/6; Ontario/4; Saskatchewan/1), US (3: Washington/2; Iowa/1)

<details><summary>Genomes: </summary>

`EPI_ISL_17821379, EPI_ISL_17994047, EPI_ISL_18030530, EPI_ISL_18040062, EPI_ISL_18055211, EPI_ISL_18062502, EPI_ISL_18105084, EPI_ISL_18111070, EPI_ISL_18115924, EPI_ISL_18121166, EPI_ISL_18129671, EPI_ISL_18129682, EPI_ISL_18129690, EPI_ISL_18129707`
</details>

**Saltation Profile:**

mutations on neatest neighboring branch:

```
nuc	unique	G12797A, A17612G, C23130A, G25471A, A27868T, G29392C, C29518A
nuc	homoplasies	T11422C, A22629C
ORF1ab	unique	G4178S, N5783S
S	unique	T523N
S	homoplasies	K356T
ORF3a	unique	D27N
ORF7b	unique	N38I
N	unique	K373N
N	homoplasies	D415E
```
details
![mut](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/bfef02e2-f8f3-4746-8ad7-4750172770a6)

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c3b8_b309b0.json?label=id:node_6974120
![details](https://github.com/cov-lineages/pango-designation/assets/125747944/5d35e910-8944-4e91-8f08-015e871dc310)

**Comment by FedeGueli** [comment]
Milestone missing. Please @AngieHinrichs and @corneliusroemer tell me if i have to add to issues in the preproposal page or not. i was doing that to save your time but i see that sometimes it has been added still here so. if i know what to do it will be great

**Comment by AngieHinrichs** [comment]
@corneliusroemer I defer cross-repo / milestone questions to you.
