### ISSUE TITLE
GL.1+S:Y144del sublineage with  ORF1a:KSF141-143del and ORF3a:D155H (58 seq. Mainly Tasmania, Australia ~40% prevalence in August 2023)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#2222]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/701.
![1](https://github.com/cov-lineages/pango-designation/assets/115189228/2d407976-0edd-4203-ba37-0f09a8e1b145)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39b95_ae74a0.json?c=gt-ORF3a_155&label=id:node_6402106
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AGL.1*%26ORF3a%3AD155H&
ORF1a:KSF141-143del (the same deletion as BA.4) has already occurred on GL.1* three times independently.
It first appeared on the Austrian branch (without S:Y144-).
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AGL.1*%26ORF6%3AE46G&
Then it appeared on this one.
Then it appeared on the Canary Islands branch nuc:C8293T > ORF1a:E2089D(G6532T) > ORF1a:G7S(G284A)+ORF1a:KSF141-143del.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AGL.1*%26ORF1a%3AG7S&
![2](https://github.com/cov-lineages/pango-designation/assets/115189228/caeb28e7-3ce2-4b72-9f0f-de0aafb049e9)

**Comment by oobb45729** [comment]
51 now and it's gaining new spike mutations. 13 with S:E748Q and 6 further gained S:NG481-482S.

**Comment by FedeGueli** [comment]
It is 38/91 sequences collected in Tasmania after August 1, and 30/61 of sequences collected after August 15!

cc @corneliusroemer being this lineage now dominant in one region i think it should be prioritized

**Comment by corneliusroemer** [comment]
Tasmania has just 500k inhabitants and is an island, so founder effect likely

**Comment by FedeGueli** [comment]
> Tasmania has just 500k inhabitants and is an island, so founder effect likely

Island effect ;) still gaining S:144del interesting!
