### ISSUE TITLE
Triple spike mutations S:K182E,S:V551I,S:E554K for a saltation XBB.1.16 sublineage emerging in MH, India (20 seqs , 4 countries - Prevalence 15% in MH,India after July 1)) update Sept 1

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2223]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/672

Defining mutations:
**XBB.1.16** >> > C29386T > A25410G > **Orf1a:P748L** (T2242C),**Orf1a:E972K** (C2508T), G3179A, **S:K182E** (A22106G), **S:V551I** (G23213A), **S:E554K** (G23222A)

 Gisaid query:  **G3179A,  C2508T** (NEW)

Samples: **12** from  **India** (11= 9,**MH** + 2 **GJ**)) , **Pennsylvania**.,Us (1)
First from MH collected on 2023-04-28 (There is a sample from 01/08 bit is for sure a date input error)
Last from MH collected on 2023-08-12
IDs:
EPI_ISL_17686342, EPI_ISL_17978171, EPI_ISL_18094379,
EPI_ISL_18094384-18094385, EPI_ISL_18120269, EPI_ISL_18120320,
EPI_ISL_18121354, EPI_ISL_18128324-18128325, EPI_ISL_18136389,
EPI_ISL_18136391

Tree:
![Schermata 2023-08-28 alle 01 25 43](https://github.com/cov-lineages/pango-designation/assets/87669813/77b8d27f-c191-4e19-8608-4fd1542aac97)
![Schermata 2023-08-28 alle 01 26 51](https://github.com/cov-lineages/pango-designation/assets/87669813/ebc7d549-5803-4e46-87e7-4badf02a148c)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5cf3f_bdb180.json?label=id:node_6841457

Prevalence:
It represents 6 out of 46 samples collected in MH after July 1 so if this could represent a fair enough amount of infections in the real world.

**Comment by HynnSpylor** [comment]
1 more seq in Singapore (the 3rd detected country) 
EPI_ISL_18141171

**Comment by FedeGueli** [comment]
One more very recent sample from Australia: 2 exportations (collection date) in the last ten days make me thinking this is quite growing or already prevalent in India).  cc @HynnSpylor i modified the query to catch them all.
![Schermata 2023-08-31 alle 16 39 35](https://github.com/cov-lineages/pango-designation/assets/87669813/eb19065b-0c49-484c-acd0-6da287d952c3)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3efd9_a4b60.json?label=id:node_6843588

Ping @corneliusroemer something under the radr in India.

**Comment by FedeGueli** [comment]
Another big jump for this one all sequences from MH India . 15% its prevalence there in August.

ping @corneliusroemer
