### ISSUE TITLE
EG.5.1 with S:L455F (41+3+1 seqs, 9 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2224]
_Taken from **Branch 4** of multitask sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** `EG.5.1` > `G22927T(S:L455F)` > `C12100G`
**Query:** `C12100G, G22927T`
**Earliest seq:** 2023-07-09 (`EPI_ISL_18060822`, Shanghai, China)
**Latest seq:** 2023-08-22 (`EPI_ISL_18141214`, Singapore)
**Sampled Countries:** China (8: Shanghai/6, 1 ex. Thailand, 1 ex. Philippines; Anhui/1; Liaoning/1), USA (3: Washington/2, ex. Japan; New York/1), Singapore (2)

<details><summary>Genomes: </summary>

`EPI_ISL_18060822, EPI_ISL_18075026, EPI_ISL_18094946, EPI_ISL_18094969, EPI_ISL_18108375, EPI_ISL_18114693, EPI_ISL_18114890, EPI_ISL_18126507, EPI_ISL_18133875, EPI_ISL_18138157, EPI_ISL_18138216, EPI_ISL_18138268, EPI_ISL_18141110, EPI_ISL_18141214, EPI_ISL_18116315`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4142c_c991a0.json?label=id:node_6935246
![Branch4](https://github.com/cov-lineages/pango-designation/assets/125747944/a95a46ce-ddd4-4441-bcc1-263470ac779c)

**Comment by FedeGueli** [comment]
> Things get a bit trickier now, cause there's a side branch of `G10900A` rather than `C12100G` also popping up: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice13_genome_11ef0_db0960.json?label=id:node_6934008
> 
> ![image](https://user-images.githubusercontent.com/125747944/263975240-9bfd5098-0fc1-4e53-943f-222331efee22.png)
> 
> it's quite hard to catch the whole lineage using simple query now, does gisaid support conditional/boolean/wildcard queries like `2-of` in cov-spectrum?

Looking at collection dates i suspect they are two different lineages that Usher place together. As we saw with XBB.2.3 +478R before they ve been designated. @corneliusroemer @AngieHinrichs what do you think? i would prefer to have them distinguished with the bottom one back to tracking in the other repo

**Comment by FedeGueli** [comment]
This is accumualting further spike mutations. it should be designated.

**Comment by FedeGueli** [comment]
I suggest to keep the proposla restricted to the branch proposed if subbranhces without C12100G pop up we can track in the tracking issue. at least the C12100G is very clear  and should be deisgnated @corneliusroemer

**Comment by FedeGueli** [comment]
Designated EG.5.1.8
