### ISSUE TITLE
EG.5.1.1 branch with  orf1a:T1589I (NSP3_T771I = PLPro_T26I )that acquired then S:L455F FLip lineage    - 772samples ( as Nov 21)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2226]
This has been found once it was two and then tracked in https://github.com/sars-cov-2-variants/lineage-proposals/issues/525

Defining mutations
**EG.5.1.1 >> C6541T > Orf1a:T1589I (C5031T = NSP3_T771I = PLPro_T26I ) >   S:L455F (G22927T)**

Gisaid query: **G22927T,C5031T**

Samples: 15 from China (5 regions) , South Korea, Japan, Singapore
First : Liaoning (CHN) 2023-06-27
Last:  Singapore 2023-08-17
IDs_
EPI_ISL_18034950, EPI_ISL_18049761, EPI_ISL_18074983,
EPI_ISL_18105346, EPI_ISL_18111106, EPI_ISL_18111145-18111146,
EPI_ISL_18111217, EPI_ISL_18138028, EPI_ISL_18138071,
EPI_ISL_18138137, EPI_ISL_18140133, EPI_ISL_18140222,
EPI_ISL_18140936, EPI_ISL_18141106

Tree:
![Uploading Schermata 2023-08-29 alle 16.21.09.png…]()

![Schermata 2023-08-29 alle 01 24 28](https://github.com/cov-lineages/pango-designation/assets/87669813/25543332-f2b3-4b2f-91d4-c26a565ac16c)
 https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1b7f8_d2c1d0.json?c=userOrOld&label=id:node_6937495

Here the tracker for its growth advantage vs parental lineage: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=G22927T%2CC5031T&analysisMode=CompareToBaseline&

**Comment by Memorablea** [comment]
https://github.com/cov-lineages/pango-designation/commit/39a35ba57d785e6bdda763fd612b9d7ba4442119 ？

**Comment by aviczhl2** [comment]
Orf1a:T4249I is only a subbranch of this.

**Comment by FedeGueli** [comment]
> Orf1a:T4249I is only a subbranch of this.

Thank you very much i got sticked to the original issue cause the query caught already the whole lineage. Thank you for noticing now updated.

**Comment by FedeGueli** [comment]
> [39a35ba](https://github.com/cov-lineages/pango-designation/commit/39a35ba57d785e6bdda763fd612b9d7ba4442119) ？

No i dont think so, L455F is just highly homoplasic in EG.5.1.1 backbone like we saw 444N/460K last year for BA.5.2

**Comment by FedeGueli** [comment]
+1 Hubei

**Comment by FedeGueli** [comment]
+ 3 Yunnan.

**Comment by FedeGueli** [comment]
3 Shanghai + 1 Denmark

**Comment by aviczhl2** [comment]
38 seqs now.

**Comment by FedeGueli** [comment]
Impressive international spread in the last ten days from 4 country all in Asia to 9 in 3 continents.

cc @corneliusroemer i suggest to designate this one

**Comment by FedeGueli** [comment]
> 38 seqs now.
> 
> ![image](https://user-images.githubusercontent.com/10445944/265883969-12266409-348c-488d-9b77-4f3537c1a32c.png)
> 
> Seems to break into 2 sub-branches but one sub-branch(C5144T) has only 1 non-455F seq so probably the two are still the same branch.

@AngieHinrichs could you take a look? this fast lineage seems broke in two separate branches by only one sequence!

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs could you take a look? this fast lineage seems broke in two separate branches by only one sequence!

Yes!  That is one of the few branches where I was not so sure (when looking at all the many EG.5.1 branches with G22927T for sars-cov-2-variants/lineage-proposals#537), so I will prune that one sequence (Tianjn/TJCDC0630-17/2023|EPI_ISL_17956695|2023-06-16), re-opt, re-place & see what happens in the 2023-09-07 build.

**Comment by FedeGueli** [comment]
> > @AngieHinrichs could you take a look? this fast lineage seems broke in two separate branches by only one sequence!
> 
> Yes! That is one of the few branches where I was not so sure (when looking at all the many EG.5.1 branches with G22927T for [sars-cov-2-variants/lineage-proposals#537](https://github.com/sars-cov-2-variants/lineage-proposals/issues/537)), so I will prune that one sequence (Tianjn/TJCDC0630-17/2023|EPI_ISL_17956695|2023-06-16), re-opt, re-place & see what happens in the 2023-09-07 build.

Thank you!

**Comment by aviczhl2** [comment]
47 seqs now and today's usher re-assigns them into one branch.

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/a752053a-5756-4fd1-a029-2f3ecbe9a240)

**Comment by FedeGueli** [comment]
New batch from Singapore , and more from China

**Comment by aviczhl2** [comment]
53 now.

**Comment by FedeGueli** [comment]
53 yunnan

**Comment by aviczhl2** [comment]
There is also a HV.1+Orf1a:T1589I branch, https://github.com/sars-cov-2-variants/lineage-proposals/issues/802, I guess the mutation itself has some meaning under EG.5.1 backbone, suggest to designate this as HK.* and the S:L455F branch as HK.*.1

**Comment by aviczhl2** [comment]
BTW this one has 74 seqs now.

**Comment by FedeGueli** [comment]
I just realized that Orf1:T1589I is NSP3_T771I = PLPro_T26I  cc @ryhisner

**Comment by aviczhl2** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/4c40f518-fa63-43d8-814b-7591e5057cf9)
This lineage is one scale faster than HK.3 too.

**Comment by FedeGueli** [comment]
Now 80 . cc @corneliusroemer now this is : big enough , growing , already spred in multiple contries with multiple sequences, apparently faster than HK.3 i think it is ready to be designated. Do you want aone more ping at 100seqs?

**Comment by aviczhl2** [comment]
97 now

**Comment by FedeGueli** [comment]
133 now cc @corneliusroemer i think it deserves a designation it is already alone 10% of samples from Yunnan in September.

**Comment by FedeGueli** [comment]
163 last samples from 3 continents but be aware it entered in some long term care in Ontario so you will see numbers artificially boosted by targeted sequencing  cc @corneliusroemer

**Comment by aviczhl2** [comment]
The T1589I branch is advanturous. 

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=EG.5.1.1*&nucMutations1=C5031T&nextcladePangoLineage1=EG.5.1.1*&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
192 seqs now

**Comment by FedeGueli** [comment]
Doubling slower than Hk.3 still close to 200 (196)

**Comment by FedeGueli** [comment]
it is now over 200 and starting accumulating further Spike mutations as S:14 or S:256.
it is also globally spread:
![Schermata 2023-10-04 alle 11 40 35](https://github.com/cov-lineages/pango-designation/assets/87669813/b6f6c0d6-9180-4eef-9eef-f26944e56f7d)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_36695_d30970.json?c=country&label=id:node_3637690
The shape of the tree suggests it have had sustained circulation in the country where it emerged.

@corneliusroemer i think it is ready to be designated.

**Comment by FedeGueli** [comment]
It now reaches 1% in Singapore and it is the third EG.5.1+FLip in Uk after HK.3 JG.3 and another hk.3 like branch

**Comment by aviczhl2** [comment]
329 now.

**Comment by FedeGueli** [comment]
@corneliusroemer this is quite big, not the fastest of the bunch but stil relevant,

**Comment by FedeGueli** [comment]
411 too big to leave it undesignated @corneliusroemer

**Comment by FedeGueli** [comment]
463

**Comment by aviczhl2** [comment]
613 seqs now.

**Comment by FedeGueli** [comment]
> 613 seqs now.

+1 Japan. @corneliusroemer i would designate this one.

**Comment by FedeGueli** [comment]
667 now

**Comment by FedeGueli** [comment]
772 as today  cc @corneliusroemer despite not being fast it is big enough to be designated without regrets i think.

**Comment by aviczhl2** [comment]
> 772 as today cc @corneliusroemer despite not being fast it is big enough to be designated without regrets i think.

Not the fastest but definitely much faster than what it is now being called. (EG.5.1.1)

**Comment by aviczhl2** [comment]
875 now

**Comment by Memorablea** [comment]
Congratulations! Designated as HK.27 and HK.27.1!https://github.com/cov-lineages/pango-designation/commit/9c4557995295c25c867d5c65920f0ec3672db4d4
