### ISSUE TITLE
HV.1 sublineage with ORF1a:T4083M first detected in California, USA (1216 GISAID seqs as of 2023-10-10; All Inhabited Continents)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#2228]
There may be a HV.1 sublineage with ORF1a:T4083M (C12513T; NSP8:T141M) first detected in California, USA.

As of 2023-08-30, Cov-Spectrum reports 29 good-quality (34 total) HV.1+ORF1a:4083M sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AHV.1+%26+ORF1a%3AT4083M&nextcladeQcOverallScoreTo=29&

There are not yet enough sequences in any one country to reliably estimate a growth advantage, but this lineage is a sublineage of a fast parent lineage, has been detected in 4 countries on 3 continents including 3 Canadian provinces and 19 American states, and it has an additional mutation ORF1a:T4083M (aka NSP8:T141M) that Bloom and Neher show as providing a growth advantage in all clades.

As of 2023-08-24, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_HV 1+ORF1a_4083M](https://github.com/cov-lineages/pango-designation/assets/88959107/2df446c1-32cf-49a2-b486-a8f6c97ca276)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/08/subtreeAuspice1_genome_CoV-Spectrum_HV.1%2BORF1a_4083M.json?c=gt-ORF1ab_4083&label=id%3Anode_6908889

GISAID query: C12513T, C22033A, C5835T (improved query courtesy of @FedeGueli)

First GISAID sequence: California, USA 2023-07-24 

Most Recent GISAID sequence: Ontario, Canada and Quebec, Canada 2023-08-21

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-HV.1+ORF1a_4083M.zip](https://github.com/cov-lineages/pango-designation/files/12475514/Support-HV.1%2BORF1a_4083M.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-HV.1+ORF1a_4083M.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/12441771/gisaid-epi-isl-HV.1%2BORF1a_4083M.txt)

This proposal has been promoted from pre-proposal https://github.com/sars-cov-2-variants/lineage-proposals/issues/683

Potential effects of the non-synonymous mutation on viral relative fitness
-------------------------------------------------------------------------------------------------

Now to consider the clade-specific Bloom and Neher estimates (from https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv) of the fitness effects of the non-synonymous mutations in their order on the UShER tree:

For ORF1a:T4083M,

clade,gene,aa_mutation,delta_fitness
20A,ORF1ab,T4083M,1.3672
20B,ORF1ab,T4083M,1.2216
20C,ORF1ab,T4083M,1.308
20E,ORF1ab,T4083M,1.2706
20G,ORF1ab,T4083M,1.5972
20I,ORF1ab,T4083M,0.97347
21C,ORF1ab,T4083M,1.6464
21I,ORF1ab,T4083M,1.2674
21J,ORF1ab,T4083M,1.3126
21K,ORF1ab,T4083M,1.1227
21L,ORF1ab,T4083M,0.62093
22A,ORF1ab,T4083M,0.57972
22B,ORF1ab,T4083M,0.98779
22C,ORF1ab,T4083M,0.64668
22D,ORF1ab,T4083M,0.27632
22E,ORF1ab,T4083M,0.82636
22F,ORF1ab,T4083M,1.0486
23A,ORF1ab,T4083M,0.63056

**Comment by FedeGueli** [comment]
Just to add i think @corneliusroemer maybe could remember the same mutation was highly homoplasic on AY.4 background back in 2021: https://github.com/cov-lineages/pango-designation/issues/332#issuecomment-999478578

**Comment by alurqu** [comment]
Now detected on a 4th continent.

**Comment by alurqu** [comment]
This lineage has really jumped in counts in the last 8 days and has now been reported on all continents with significant human populations.

This lineage also appears to be a major sublineage of but not a majority of HV.1:
![UShER-HV 1+ORF1a_T4083M](https://github.com/cov-lineages/pango-designation/assets/88959107/8dc4cb64-d866-4b1d-83d5-5fa2ff09aa96)

**Comment by FedeGueli** [comment]
Yes it is the one driving HV.,1 very high in growth advantages

**Comment by FedeGueli** [comment]
368 now . it is the only non flip lineage (ba.2.86 excluded) to be faster than HK.3

**Comment by alurqu** [comment]
This lineage continues to grow robustly, but in the USA where it is most common it shows little growth advantage over its parent HV.1. I'm ambivalent over whether to close this issue due to lack of growth advantage or leave it open due to the robust growth and likelihood that this is developing into a large branch of its own.

**Comment by FedeGueli** [comment]
661 as today
with the new update by CovSpectrum its advantage over the parental HV.1 is clear with all the 3 CIs pointing to at least a 5% of advantage. 
![Schermata 2023-10-02 alle 15 25 13](https://github.com/cov-lineages/pango-designation/assets/87669813/26e223be-c0b1-4b59-9449-bd2df5c399e5)
It is also not far from HK.3 
![Schermata 2023-10-02 alle 15 26 54](https://github.com/cov-lineages/pango-designation/assets/87669813/cce5d0bc-f334-4891-bdc8-58fed438716d)

**Comment by FedeGueli** [comment]
793 as today
this is how it is doing vs its parent lineage HV.1
![Schermata 2023-10-04 alle 10 43 51](https://github.com/cov-lineages/pango-designation/assets/87669813/229059b9-3b48-418b-97fa-9945adb5bd5b)

**Comment by alurqu** [comment]
A separately-proposed sublineage of this has been designated HV.1.1 leaving no room for this to be designated.

I am closing this proposal as unplanned.
