### ISSUE TITLE
Proposal for AY.4 sublineage with S:145H + S:222V (mostly UK)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#223]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: AY.4
Earliest sequence: UK 2021-23
Most recent sequence: Current
Countries circulating: Mostly UK (now 5%), also Denmark at 1-2% and other European countries

Lineage deriving from AY.4 with extra Spike mutations S:Y145H and S:A222V. It has a pretty steady growth rate in the UK over the past weeks which could be indicative of a real fitness advantage as opposed to a chance event (founder effect).

If we want to cast the net wide, the first mutation in addition to AY.4 was T17040C (synonymous). But since it's synonymous, it probably doesn't makes more sense to make the 2 spike mutations defining.

<html><head></head><body>

Country | Total Variant Sequences | First seq. found at | Last seq. found at |  
-- | -- | -- | -- | --
Australia | 1 | 2021-32 | 2021-32 |  
Belgium | 4 | 2021-35 | 2021-37 |  
Denmark | 206 | 2021-31 | 2021-37 |  
Estonia | 1 | 2021-33 | 2021-33 |  
Finland | 1 | 2021-33 | 2021-33 |  
France | 8 | 2021-28 | 2021-35 |  
Germany | 44 | 2021-27 | 2021-36 |  
Ireland | 11 | 2021-26 | 2021-35 |  
Italy | 9 | 2021-26 | 2021-37 |  
Japan | 1 | 2021-34 | 2021-34 |  
Lithuania | 2 | 2021-29 | 2021-30 |  
Netherlands | 7 | 2021-33 | 2021-36 |  
Norway | 6 | 2021-33 | 2021-35 |  
Poland | 6 | 2021-33 | 2021-35 |  
Portugal | 3 | 2021-34 | 2021-35 |  
Romania | 7 | 2021-34 | 2021-37 |  
Singapore | 1 | 2021-36 | 2021-36 |  
Slovakia | 3 | 2021-29 | 2021-29 |  
Spain | 1 | 2021-30 | 2021-30 |  
Sweden | 3 | 2021-34 | 2021-35 |  
Switzerland | 3 | 2021-30 | 2021-35 |  
United Kingdom | 8833 | 2021-23 | 2021-37 |  
United States | 4 | 2021-33 | 2021-35

</body></html>

![image](https://user-images.githubusercontent.com/25161793/134753024-84a83d91-b563-4bd8-ad3f-a45a06068ccb.png)

See here for further details: https://cov-spectrum.ethz.ch/explore/United%20Kingdom/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22s%3A222V%22%2C%22s%3A145H%22]%7D%2C%22matchPercentage%22%3A1%7D

Genomes (already 9000!)
[ay_4_145h_222v.txt](https://github.com/cov-lineages/pango-designation/files/7228954/ay_4_145h_222v.txt)

Evidence
![image](https://user-images.githubusercontent.com/25161793/134753035-ebe43dfb-9662-4769-8c29-4bdefbadf5b3.png)

See here for Auspice json:
[auspice.zip](https://github.com/cov-lineages/pango-designation/files/7228957/auspice.zip)

Proposed lineage name
AY.4.3 (AY.4.2 if this is designated before #222)

**Comment by corneliusroemer** [comment]
Have you had a chance to have a look at this lineage proposal @chrisruis @rmcolq @AngieHinrichs ? I noticed that while you designated most of my other proposals, there's no comment on this one here. It would be interesting to hear your thoughts.

While one cannot know for sure whether growth of this lineage is a chance event or not, I believe it deserves attention as a potential candidate for increased fitness.

It's grown to almost 9% in Scotland, and it's not a founder effect, since it grew while Delta was already widespread.
![image](https://user-images.githubusercontent.com/25161793/135274279-f1bf63d6-2b71-4c00-acf3-2b4c3fc12558.png)

**Comment by chrisruis** [comment]
Hi @corneliusroemer Thanks for submitting, we haven't had a chance to look at this one yet but should do soon

**Comment by AngieHinrichs** [comment]
Here is a taxodium.org view of the larger clade, colored by country (orange = Scotland, red=England, lighter greens = Germany/Switzerland, dark green = Denmark):
![image](https://user-images.githubusercontent.com/186983/135657837-04fc44c5-5f05-4741-a659-ceb0f37d6353.png)
The black circle shows the S:Y145H node.  The one above that is S:A222V, and the one above that (the root of the larger clade) is C25614T (synonymous ORF3a:S74).

**Comment by AngieHinrichs** [comment]
There does seem to be a lot more expansion after the hop to mostly-England with S:A222V (the originally proposed start of the sublineage).

**Comment by FedeGueli** [comment]
It seems to be growing in Romania too, and there is a sharp increase of cases there.

**Comment by corneliusroemer** [comment]
@chrisruis @rmcolq May I politely express my view that this lineage should be given priority in the designation backlog as it keeps growing within UK and also abroad (Germany, Romania, ...). It's now at 7% in UK up from 5.8% when I proposed the lineage 9 days ago. Total sequences 11k vs 8k. Is there anything that would help you in designating? Are you unsure where to start on the tree, similar to what Angie investigated?

![image](https://user-images.githubusercontent.com/25161793/135844861-5eaf611d-e091-4b8a-9210-01a265341a58.png)

@AngieHinrichs Thanks for investigating - this is interesting. Do I understand you correctly that 222V seems to have happened first, and only after 145H did the growth kickstart? Is the orange circle placed correctly? Should it be a bit higher up and left, on the node, instead or do I misunderstand something?

**Comment by chrisruis** [comment]
Thanks @corneliusroemer As @AngieHinrichs says, it looks like S:A222V occurs one branch upstream of S:Y145H and the expansion of this clade happens after S:Y145H is acquired. So I'd therefore suggest that we start this lineage on the branch with S:Y145H.

We've added this as lineage AY.4.2 in [v1.2.82](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.82) with 9075 designated sequences.

**Comment by FedeGueli** [comment]
Thank.you for your work.
