### ISSUE TITLE
EG.5.1.1 on C11779T with S:L455F (15 seqs, mainly in China, 3 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2230]
_Taken from **Branch 1** of multitask sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** `EG.5.1.1` > `C11779T` > `G22927T(S:L455F)`
**Query:** `C6541T, C11779T, G22927T`
**Earliest seq:** 2023-06-27 (`EPI_ISL_18060870`, Yibin, Sichuan, China)
**Latest seq:** 2023-08-19 (`EPI_ISL_18147277`, `EWR` airport, New Jersey, USA, travel history: Singapore)
**Sampled Countries:** China (13: Fujian/5; Sichuan7/; Shanghai/1), Canada (1, Ontario), USA (1, NJ ex. Singapore)

<details><summary>Genomes: </summary>

`EPI_ISL_18060870, EPI_ISL_18060877, EPI_ISL_18076513, EPI_ISL_18108313, EPI_ISL_18108479, EPI_ISL_18127148, EPI_ISL_18127155, EPI_ISL_18133988, EPI_ISL_18133990, EPI_ISL_18133993-18133995, EPI_ISL_18145944, EPI_ISL_18145952, EPI_ISL_18147277`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d339_f56760.json?label=id:node_6943652
![Branch1](https://github.com/cov-lineages/pango-designation/assets/125747944/9f06f5c0-376d-48f2-8265-a583f31f9a99)

**Trivia:**
- `C11779T` is the largest undesignated branch of EG.5.1.1 right now, so this is _definitely not_ HK.3.

**Comment by FedeGueli** [comment]
Designated HK.8 via https://github.com/cov-lineages/pango-designation/commit/9527e15afb0acedf720e1042d5da347a4c0abd7d 
Milestone missing
