### ISSUE TITLE
Rapid identification of BA.2.86 branches (=/>2seqs)(tracking issue)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2236]
BA.2.86

Branches (more than 1seq only):
1
Orf1a:K1973R (A6183G), C12815T  query :A6183G, C12815T 
1a : Orf1a:Y621C (A2127G) Query : A6183G, C12815T, A2127G
1b : N:E378Q (G29405C) Query : G29405C,A6183G,C12815T 
1c S:748Q ( G23804C), C11152T Query:  ,A6183G,G23804C, C11152T
1d: Orf1b:T1274I(T11614C), C17288T : query: T11614C, C17288T
1e: C7528T Query: A7842G,C7528T,A6183G
1f: A23566T, N:T135I (C28677T) Query: A23566T  ,C28677T,A6183G
1g: C13971T,C29635T Query:C13971T,C29635T,A6183G
1h: ORF1a:K2507R (A7785G),Orf1a:A2784V (C8616T) Query:A7785G, C8616T,A6183G
 
 

2
ORF7a:E22D (G27459T) Query: A7842G,G27459T
2a: C1663T Query : C1663T, G27459T,A7842G

3
C2137T, S:I670V (A23570G), Orf8:T87I (C28153T), N:G243S (G29000A)

cc @corneliusroemer @AngieHinrichs  based on Cornelius Tree: https://nextstrain.org/groups/neherlab/ncov/BA.2.86?c=gt-nuc_25000,25207
![Schermata 2023-09-01 alle 10 09 27](https://github.com/cov-lineages/pango-designation/assets/87669813/edadd939-8d63-42d0-8821-92e7c8b05d96)

**Comment by corneliusroemer** [comment]
Yep, this is on the radar, for now waiting for a bit longer, maybe 1-2 weeks to see whether the BA.2.86 common ancestor stays there and for the phylogeny to stabilize.

**Comment by FedeGueli** [comment]
> Yep, this is on the radar, for now waiting for a bit longer, maybe 1-2 weeks to see whether the BA.2.86 common ancestor stays there and for the phylogeny to stabilize.

Yes thx for looking into it, i thought it was good to describe early the tree before it becomes too big to track ( always hard then to do after) So if something shows some advantage we can catch it immediately

**Comment by Over-There-Is** [comment]
BA.2.86.1> A28795G
England/CLIMB-CM7YEUMZ/2023|EPI_ISL_18227401|2023-08-27
USA/CO-CDPHE-41186476/2023|EPI_ISL_18223813|2023-08-19

**Comment by FedeGueli** [comment]
> BA.2.86.1> A28795G England/CLIMB-CM7YEUMZ/2023|EPI_ISL_18227401|2023-08-27 USA/CO-CDPHE-41186476/2023|EPI_ISL_18223813|2023-08-19

Thx added!

**Comment by Over-There-Is** [comment]
No, there is no T21610C branch. It is just an inaccurate presentation of ins21608TC....
The original nucleotides are ...GTGTGTTAA... there, and after insertion, they become ...GTGTGTCAT..., and sometimes there will be a missing section, and they will become ...GTGTGTCAN... and get analyzed as T21610C.
USA/CO-CDPHE-41186476/2023|EPI_ISL_18223813|2023-08-19 is BA.2.86.1> A28795G> C3811T, C22752T
and England/CLIMB-CM7YEUMZ/2023|EPI_ISL_18227401|2023-08-27 is BA.2.86.1> A28795G> C2676T, 21612-21640N
All the other sequences with T21610C have Ns from 21611 or 21612 to 21640 too.

**Comment by FedeGueli** [comment]
Thank you very much @Over-There-Is i stop this here! we will see soon which ones spread the fast. 
This could be kept as archive of early branches that usually when a lineages grow over 5000 is hard to track back.
