### ISSUE TITLE
HS.1 (XBB.1.5.95+S:T478R) with S:F456L (25 seqs, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2237]
_Transferred from sars-cov-2-variants/lineage-proposals#633_

**Defining Mutations:** `HS.1` > `T10084A` > `C6628T` > `C10252T, T22928C(S:F456L)` > `G28077T(ORF8:V62L)`
**Query:** `C6628T, T10084A, T22928C`
**Earliest seq:** 2023-05-30 (`EPI_ISL_17985957`, Puerto Rico)
**Latest seq:** 2023-08-17 (`EPI_ISL_18164469`, Texas)
**Sampled Countries:** USA(14: Texas/14; Mississippi/6; New York/2; Puerto Rico/2; Delaware/1)

<details><summary>Genomes: </summary>

`EPI_ISL_17856278, EPI_ISL_17985957, EPI_ISL_18057331, EPI_ISL_18057336, EPI_ISL_18057506, EPI_ISL_18059619, EPI_ISL_18099024, EPI_ISL_18099037, EPI_ISL_18104808, EPI_ISL_18104885, EPI_ISL_18107764, EPI_ISL_18110481, EPI_ISL_18110498, EPI_ISL_18110544, EPI_ISL_18119552, EPI_ISL_18119627, EPI_ISL_18119742, EPI_ISL_18126335, EPI_ISL_18137238, EPI_ISL_18160078, EPI_ISL_18162754, EPI_ISL_18163770, EPI_ISL_18163829, EPI_ISL_18164356, EPI_ISL_18164469`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_5140_1a6330.json?c=gt-S_478%2C456&gmax=25384&gmin=21563&label=id%3Anode_7279618

view from XBB.1.5.95 polytomy
![poly](https://github.com/cov-lineages/pango-designation/assets/125747944/923504a5-b534-4199-8f49-adbdfae0941a)

details
![details](https://github.com/cov-lineages/pango-designation/assets/125747944/305c6a79-34bd-443c-bb5c-42ce119908ce)

**Comment by FedeGueli** [comment]
Doubling (submission date) around 15 days.
