### ISSUE TITLE
Two JH aliases，should be split

### ISSUE THREAD

**Issue by Kevin050308** [cov-lineages/pango-designation#2239]
![image](https://github.com/cov-lineages/pango-designation/assets/121531357/7289600f-b47a-427b-8cf2-d7b8d1315d17)

**Comment by Kevin050308** [comment]
Hi all，
There are two JHs now.We should probably create a new alias for the latter.
Best,
Kevin Xu

**Comment by Kevin050308** [comment]
At the same time，there is a typo in lineages note for current JJ.1
Designate JJ.1（XBB.1.9.2.5.1.**3**.1，S：L455F，ORF3a：I47V，China/Japan）
cc@corneliusroemer

**Comment by HynnSpylor** [comment]
Thx @Kevin050308 
I have submitted the correction of JJ.1 typo.
the conflict of "JH" needs to be reassigned @corneliusroemer

**Comment by corneliusroemer** [comment]
Sorry everyone, that was quite a screwup 🙈 

Now fixed by moving XBB.1.5.3.1 to JK.1
