### ISSUE TITLE
XBB.2.3 sublineage with S:E654K and possible S:K478T reversion (65 seqs in 9 countries) 

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#2241]
*Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/731
@ryhisner has noticed it and the parent lineage is tracked by @aviczhl2 in #1945. Thx a lot! 

Defining mutations:
XBB.2.3> C5622T (ORF1a:P1786L)> C7303A> C10776T (ORF1a:P3504L), C22624T, G23522A (S:E654K)
GISAID query: C7303A, C10776T, G23522A
Earliest seq: 2023-06-20 (Maharashtra, India- EPI_ISL_18052802)
Most recent seq: 2023-08-24 (Maharashtra, India- EPI_ISL_18209977)
Countries detected: India (24, including 1 detected in US International Airport), US (1)

Usher Tree:
![QQ截图20230901220922](https://github.com/cov-lineages/pango-designation/assets/121703496/332fbe8a-2597-4483-8bf3-a03f43973871)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10b57_1ed5f0.json?c=gt-S_654

It is a branch with S:G184V ( proposed but undesignated in https://github.com/cov-lineages/pango-designation/issues/1945) but without another defining mutation of XBB.2.3.2 (ORF1a:R2159W), hence it is not classified as XBB.2.3.2

Another notable feature is the almost seqs are possible S:K478T reversion. If we show the S:478 on neighbored branches, the other branch are not the concentrative reversion. Moreover, if we query the other samples updated in the same batch on GISAID, the samples outside the branch are all showing the S:T478X mutation. Therefore, I suggest the reversion is possibly true instead of artefacts.
![QQ截图20230901221055](https://github.com/cov-lineages/pango-designation/assets/121703496/3fa67f6d-d107-460f-964a-27263283bedc)

*The branch accounts for >30% of samples updated in MH, India today, and over half of them are collected in last 10 days.

Genomes:
EPI_ISL_18052798, EPI_ISL_18052802, EPI_ISL_18120273, EPI_ISL_18120276, EPI_ISL_18125007, EPI_ISL_18126472,
EPI_ISL_18209930-18209931, EPI_ISL_18209936, EPI_ISL_18209945, EPI_ISL_18209947-18209948, EPI_ISL_18209950-18209951, EPI_ISL_18209954, EPI_ISL_18209959, EPI_ISL_18209961, EPI_ISL_18209967, EPI_ISL_18209969, EPI_ISL_18209973,
EPI_ISL_18209976-18209977, EPI_ISL_18209980-18209981, EPI_ISL_18209983

**Comment by HynnSpylor** [comment]
1 more seq in Australia

**Comment by HynnSpylor** [comment]
today +3, Ireland, France and UK (England).

**Comment by HynnSpylor** [comment]
54 seqs now and it has a ~35% prevalence in MH, India.

**Comment by FedeGueli** [comment]
65 now

**Comment by FedeGueli** [comment]
85 now @corneliusroemer this one even if likely not able to compete with HK.3  represents 30% of samples (5/15 so...) collected in MH, India. Dr Karyakarte confirmed us XBB.2.3 is still on the lead there. 
I think could be a good idea to deisngate this one. Not urgent.
