### ISSUE TITLE
FL.1.5.1 with s:494p, s:253G, ORF1a:G345C (4)

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2242]
transferred from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/383  
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/566824c8-5284-48e2-acd7-807b2b62244f)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_142aa_29c840.json?c=gt-S_253&gmax=25384&gmin=21563&label=id:node_6982454
Tracker provided by @FedeGueli :https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=T23042C%2CG20060T%2CC22995G&analysisMode=CompareToBaseline&
gisaid query: G1298T, A22995G, G20060T
EPI_ISL_18162736 OR440330.1 EPI_ISL_18162835 EPI_ISL_18165599
First Seq: 2023-07-28
Most Recent: 2023-08-16

**Comment by corneliusroemer** [comment]
Too small
