### ISSUE TITLE
EG.5.1.1 with ORF3a:D155H and S:S494P, already with spike diveristy of S:R403T, S:S704L etc. (478 seqs, 16 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2243]
_Taken from **Branch 1** of multitask sars-cov-2-variants/lineage-proposals#648_

**Defining Mutations:** `EG.5.1.1` > `G25855C(ORF3a:D155H)` > `T23042C(S:S494P)`
**Query:** `C6541T, T23042C, G25855C`
**Earliest seq:** 2023-07-04 (`EPI_ISL_18046800`, South Korea)
**Latest seq:** 2023-08-18 (`EPI_ISL_18208475`, Shanghai, China)
**Sampled Countries:** South Korea (31), China (7: Shanghai/3; Gansu/2; Anhui/1; Henan/1), Israel (1), South Africa (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18046800, EPI_ISL_18047579, EPI_ISL_18047616, EPI_ISL_18067477, EPI_ISL_18067703, EPI_ISL_18067843, EPI_ISL_18068488, EPI_ISL_18096876, EPI_ISL_18105782, EPI_ISL_18111600, EPI_ISL_18113582, EPI_ISL_18114674, EPI_ISL_18114826, EPI_ISL_18114912, EPI_ISL_18116437, EPI_ISL_18116466, EPI_ISL_18116549, EPI_ISL_18116640, EPI_ISL_18116815, EPI_ISL_18117127, EPI_ISL_18117318, EPI_ISL_18117416, EPI_ISL_18117444, EPI_ISL_18117550, EPI_ISL_18117652, EPI_ISL_18117880, EPI_ISL_18118004, EPI_ISL_18138008, EPI_ISL_18139779, EPI_ISL_18139815, EPI_ISL_18139893, EPI_ISL_18140132, EPI_ISL_18140336, EPI_ISL_18140544, EPI_ISL_18140567, EPI_ISL_18165816, EPI_ISL_18165845, EPI_ISL_18165967, EPI_ISL_18208326, EPI_ISL_18208475`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1aa71_311810.json?f_userOrOld=uploaded%20sample
![details](https://github.com/cov-lineages/pango-designation/assets/125747944/f6b04c30-4eb8-4264-9d0b-8ff04e3d3926)

**Comment by FedeGueli** [comment]
47 now Quinqhai and South Korea

**Comment by FedeGueli** [comment]
77 as today 

Ass the most of lineages little hopes vs HK.3 : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C6541T%2CT23042C%2CG25855C&analysisMode=CompareToBaseline&

**Comment by DailyCovidCases** [comment]
Please close this issue
