### ISSUE TITLE
XBB.1.16 with ORF1b:Q1546H, ORF3a:L41F, ORF1a:Q2660H, ORF1b:A1620V, ORF1b:T284I and S:K304Q (23 seqs, 7 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2244]
_Taken from **Branch 2** of Multitask sars-cov-2-variants/lineage-proposals#517_

**Defining Mutations:** `XBB.1.16` > `G18105T(ORF1b:Q1546H/nsp14_Q22H)` > `T16209C, C25513T(ORF3a:L41F)` > `A8245C(ORF1a:Q2660H/nsp3_Q1842H), C16608T` > `C18326T(ORF1b:A1620V/nsp14_A96V)` > `C14318T(ORF1b:T284I/nsp12_T293I)` > `A22472C(S:K304Q)`
**Query:** `C14318T, C18326T, A22472C`
**Earliest seq:** 2023-04-28 (`EPI_ISL_17625420`, Shanghai, China, travel history to: Singapore)
**Latest seq:** 2023-08-23 (`EPI_ISL_18211080`, New York, USA)
**Sampled Countries:** China (12: Heilongjiang/3, Shanghai/3, Shanxi/1, Hubei/1, Jiangsu/1, Sichuan/1), USA (6, New York/5, New Jersey/1), South Korea (2), Laos (1), Singapore (1), Switzerland (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17625420, EPI_ISL_17850378, EPI_ISL_17850453, EPI_ISL_17951213, EPI_ISL_17989079, EPI_ISL_18022610, EPI_ISL_18034134, EPI_ISL_18038504, EPI_ISL_18047554, EPI_ISL_18055693, EPI_ISL_18057798, EPI_ISL_18067375, EPI_ISL_18080211, EPI_ISL_18104523, EPI_ISL_18105848, EPI_ISL_18105951, EPI_ISL_18127506, EPI_ISL_18138323, EPI_ISL_18162986, EPI_ISL_18208537, EPI_ISL_18211080`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c34d_31d7f0.json?f_userOrOld=uploaded%20sample&label=id:node_6823117

view from `ORF1b:Q1546H` branch
![b2poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/bfe1a928-3403-493b-8510-4588d80de6fa)

details
![Branch2](https://github.com/cov-lineages/pango-designation/assets/125747944/c3871381-bbf2-46f6-8caa-7599569df54c)

**Comment by corneliusroemer** [comment]
How does this relate to XBB.1.16.23?

**Comment by FedeGueli** [comment]
This = > XBB.1.16 > G18105T(ORF1b:Q1546H/nsp14_Q22H) > T16209C, C25513T(ORF3a:L41F) > A8245C(ORF1a:Q2660H/nsp3_Q1842H), C16608T > C18326T(ORF1b:A1620V/nsp14_A96V) > C14318T(ORF1b:T284I/nsp12_T293I) > A22472C(S:K304Q)

XBB.1.16.23 =>XBB.1.16 > A22472C(S:K304Q) 
![Schermata 2023-09-04 alle 14 55 34](https://github.com/cov-lineages/pango-designation/assets/87669813/f441eb50-d39b-4ed7-a15e-b54fe2504a99)

**Comment by corneliusroemer** [comment]
Too small, doesn't seem to grow and doesn't have novel RBD haplotype either
