### ISSUE TITLE
FL.15+Orf1a:G400V+S:Q14H(Designated FL.15.2)+S:L455F (17 seqs, 3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2248]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/578

FL.15+G1464T(Orf1a:G400V)+C12890T+C29236T,C1684T,C11747T,G21604T(S:Q14H)

GISAID query: C29236T,C1684T,C11747T
No. of seqs: 23(Japan 5 China 18)

21 on GISAID, 2 Japanese seqs not in GISAID.
 SZ-NTC-183/184

GISAID query for S:L455F branch: C29236T,C1684T,C11747T,G22927T
Samples:2

First: EPI_ISL_17836269. Xinjiang, 2023-5-25
Latest: EPI_ISL_18208569,Shanghai, 2023-8-15

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/fl_15_q14h.json?label=id:node_6914402)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/076e1694-d38c-457e-acf2-0cfa27033ec9)

**Comment by FedeGueli** [comment]
@corneliusroemer i suggest to start sub designating the FL.15 (456L) branches cause they are going to be messy to track :
We have : 
**A**:
FL.15 + S:L455F in the branch with T5161C proposed here: https://github.com/sars-cov-2-variants/lineage-proposals/issues/747 query: T15357G,G22927T
![Schermata 2023-09-25 alle 11 06 02](https://github.com/cov-lineages/pango-designation/assets/87669813/48d27acf-7851-44a5-9aa0-db16ba02bc73)
then
we have:
**B**
the main FL.15 branch with  Orf1aG400V (G1464T) counting  around 750 sequences Query (T22928C, C12890T,G1464T):
![Schermata 2023-09-25 alle 11 06 51](https://github.com/cov-lineages/pango-designation/assets/87669813/b009bd73-fe04-4cda-8d89-bd6cba9d614e) 
that has two branches of interest:
**BA**
the one proposed in this issue #2248 with S:Q14H (C29236T,C1684T,C11747T) and then S:L455F (C29236T,C1684T,C11747T,G22927T) 
![Schermata 2023-09-25 alle 11 09 55](https://github.com/cov-lineages/pango-designation/assets/87669813/f7ef2c4e-1eaf-4231-bba0-d02644e0a1a9)
**BB**
The other  branch is defined by Orf1a:S2185N (G6819A) (query : G6819A,G1464T,C12890T) counting 69seqs:
![Schermata 2023-09-25 alle 11 13 01](https://github.com/cov-lineages/pango-designation/assets/87669813/2fdb3bc7-e412-4f2a-9c79-44ecec2956f2)
that splits further in:
**BBA**
with S:Q14H (G21604T) proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/547 (Query:G21604T,G6819A,C12890T)
![Schermata 2023-09-25 alle 11 16 56](https://github.com/cov-lineages/pango-designation/assets/87669813/c6380b52-1dea-45fc-9fda-698d98eb546f)
and
**BBB**
defined by S:L455F (G22927T) and Orf1a:T2007I (C6285T) proposed in https://github.com/cov-lineages/pango-designation/issues/2293 (Query:C6285T,G6819A,G22927T)
![Schermata 2023-09-25 alle 11 19 40](https://github.com/cov-lineages/pango-designation/assets/87669813/32af88d5-4374-4a16-a9fc-481a449a3e04)


Hope this could help.

**Comment by FedeGueli** [comment]
cc @AngieHinrichs please take a look to the comment above to me they seem really independent acquisiton .

@corneliusroemer i ve created a collection for it to facilitate your work: https://cov-spectrum.org/collections/28097

**Comment by FedeGueli** [comment]
Designated FL.15.2 via https://github.com/cov-lineages/pango-designation/commit/81a254acab70b66c7a4f7c24f840f226aeef3ec2#commitcomment-128527167

**Comment by FedeGueli** [comment]
> C29236T,C1684T,C11747T,G22927T

i think :T15357G,G22927T could work too.

**Comment by FedeGueli** [comment]
> > Designated FL.15.2 via [81a254a#commitcomment-128527167](https://github.com/cov-lineages/pango-designation/commit/81a254acab70b66c7a4f7c24f840f226aeef3ec2#commitcomment-128527167)
> 
> Okay let's not close this and continue to track the L455F branch here.

yes please.  i would modify the proposal body too.

**Comment by FedeGueli** [comment]
10 now

**Comment by aviczhl2** [comment]
+2 Singapore, 1 local, 1 from China

**Comment by aviczhl2** [comment]
+1 Germany

**Comment by aviczhl2** [comment]
No new seqs
