### ISSUE TITLE
New Delta sublineage dominant in Nigeria with S:1104L but distinct from AY.20 (Mexico)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#225]
New lineage proposal
by @CorneliusRoemer

*It's important to designate this lineage not only because it's a valid lineage in itself but also to reduce false-positives around AY.20 classification. Sequences in this lineage are misclassified as AY.20 even though it does not satisfy the criteria: it doesn't have Orf1a:599V*

Description
Sub-lineage of: B.1.617.2 (sister lineage of AY.20, as it shares a common ancestor with S:1104L)
Earliest sequence: Spain 2021-22, then Nigeria 2021-24, then UK 2021-25
Most recent sequence: Current
Countries circulating: Dominant in Nigeria, on the increase in UK and rest of Europe

Sister lineage of AY.20 (Mexico). It shares a common ancestor with S:1104L.
AY.20 has Orf1a:599V
This lineage has two different AA substitutions: orf1b:721R, orf1b:1538L and two synonymous mutations: 15628C and 29738T

It would probably have made sense to classify these two lineages under a common ancestor in the form AY.20.1 and AY.20.2 but probably too late, also not doing this saves points.

Country | Total Variant Sequences | First seq. found at | Last seq. found at |  
-- | -- | -- | -- | --
Australia | 4 | 2021-34 | 2021-37 |  
Belgium | 50 | 2021-30 | 2021-36 |  
Botswana | 1 | 2021-35 | 2021-35 |  
Brazil | 53 | 2021-31 | 2021-35 |  
Bulgaria | 1 | 2021-30 | 2021-30 |  
Burkina Faso | 21 | 2020-38 | 2021-16 |  
Canada | 43 | 2021-26 | 2021-34 |  
Croatia | 8 | 2021-29 | 2021-31 |  
Czechia | 2 | 2021-36 | 2021-36 |  
Denmark | 25 | 2021-25 | 2021-34 |  
France | 44 | 2021-25 | 2021-35 |  
Germany | 65 | 2021-24 | 2021-36 |  
Ghana | 6 | 2021-27 | 2021-33 |  
Hong Kong | 1 | 2021-32 | 2021-32 |  
Iceland | 2 | 2021-29 | 2021-31 |  
India | 1 | 2021-27 | 2021-27 |  
Ireland | 12 | 2021-27 | 2021-34 |  
Italy | 13 | 2021-29 | 2021-36 |  
Japan | 5 | 2021-27 | 2021-32 |  
Lithuania | 9 | 2021-27 | 2021-33 |  
Mexico | 3 | 2021-28 | 2021-31 |  
Netherlands | 18 | 2021-31 | 2021-35 |  
Nigeria | 346 | 2021-24 | 2021-36 |  
Norway | 3 | 2021-31 | 2021-33 |  
Poland | 2 | 2021-33 | 2021-35 |  
Portugal | 6 | 2021-31 | 2021-36 |  
Romania | 1 | 2021-33 | 2021-33 |  
Slovakia | 2 | 2021-33 | 2021-33 |  
Slovenia | 1 | 2021-28 | 2021-28 |  
South Korea | 2 | 2021-30 | 2021-32 |  
Spain | 111 | 2021-22 | 2021-34 |  
Sweden | 23 | 2021-30 | 2021-36 |  
Switzerland | 15 | 2021-25 | 2021-36 |  
Togo | 3 | 2021-29 | 2021-30 |  
United Kingdom | 657 | 2021-25 | 2021-37 |  
United States | 218 | 2021-26 | 2021-37

![image](https://user-images.githubusercontent.com/25161793/134757315-2576ed38-f65f-4949-88ff-0a40df4fe878.png)

https://cov-spectrum.ethz.ch/explore/World/AllSamples/Past3M/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22s%3A1104L%22%2C%22orf1b%3A721R%22]%7D%2C%22matchPercentage%22%3A1%7D

Genomes (~ 2000)
[1104l_nigeria.txt](https://github.com/cov-lineages/pango-designation/files/7229120/1104l_nigeria.txt)

Evidence
The top (light blue) is AY.20, the yellow sister is this sublineage. Below is AY.4 and other delta sublineages.
![image](https://user-images.githubusercontent.com/25161793/134757359-e67fa604-9db9-420f-9856-52200418871c.png)

Proposed lineage name
Either AY.36 or AY.20.2 (if AY.20 is renamed AY.20.1)

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as AY.36 in [v1.2.80](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.80). We've started the lineage on a branch with T15628C (Orf1ab:C5122R) and G18079T (Orf1ab:V5939L) which is after the divergence of this clade from AY.20 and coincides with the root of the Nigeria/USA/UK clade
