### ISSUE TITLE
EG.5.1.1 with ORF1b:D1267G (nsp13_D344G) and S:L455F (11 seqs, China)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2251]
_Taken from **Branch 10** of multitask sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** EG.5.1.1 > A17267G(ORF1b:D1267G) > C11173T, G22927T(**S:L455F**)
**Query:** `C11173T, G13627A, G22927T`
**Earliest seq:** 2023-07-16 (`EPI_ISL_18049850`, Qinghai)
**Latest seq:** 2023-08-28 (`EPI_ISL_18213226`, Fujian)
**Sampled Countries:** China (11: Shanghai/3; Qinghai/2; Fujian/1; Hubei/1; Liaoning/1; Sichuan/1; Xinjiang/1; Yunnan/1)

<details><summary>Genomes: </summary>

`EPI_ISL_18049850, EPI_ISL_18108872, EPI_ISL_18114762, EPI_ISL_18116311, EPI_ISL_18133939, EPI_ISL_18133980, EPI_ISL_18138175, EPI_ISL_18146058, EPI_ISL_18166202, EPI_ISL_18208650, EPI_ISL_18213226`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6d28_46d7b0.json?c=gt-S_455&gmax=25384&gmin=21563&label=id:node_6951068

view from EG.5.1.1's `ORF1b:D1267G (A17267G)` branch
![poly](https://github.com/cov-lineages/pango-designation/assets/125747944/871b74b2-1b54-4732-bdbc-c7f217e557cd)

details
![Branch10](https://github.com/cov-lineages/pango-designation/assets/125747944/0f6deea2-cbfb-42df-ad16-0053b8ec73a4)

**Comment by corneliusroemer** [comment]
Too small, there are already many sister lineages with this genotype, let's wait which ones become big otherwise we end up with 10s of lineages with the same genotype most of which never become big

**Comment by FedeGueli** [comment]
The sense of the proposals was exactly the opposite to designate them after being tracked briefly here  to avoid a lot of confusion: @corneliusroemer we are actually 63 sublineages/singlets of EG.5.1 with S:L455F 15 above 3 seqs the vast  so prepare yourself it will be the mess now or one month it doesnt change the fact that an unprecedented evolution happening in China.

**Comment by FedeGueli** [comment]
@NkRMnZr please restart the tracking in the other page we will raise the threeshold to be proposed to 50 seqs  , it will be reopenened here when reached.

**Comment by AngieHinrichs** [comment]
> 63 sublineages/douplets/singlets of EG.5.1 with S:L455F

That sounds crazy!  I wonder if dropout or primer-overlap or other problems are causing that position to be inconsistently detected... that could potentially cause that kind of weirdness.  I will take a closer look later.

**Comment by FedeGueli** [comment]
> > 63 sublineages/douplets/singlets of EG.5.1 with S:L455F
> 
> That sounds crazy! I wonder if dropout or primer-overlap or other problems are causing that position to be inconsistently detected... that could potentially cause that kind of weirdness. I will take a closer look later.

i dont think so cause in 1/3 of cases they went to 3 seqs in more than half they arrived to 2. i didnt check how many are from the same lab but we have seen in the biggest ones that they expand to other areas/labs. To me is something from an evolutionary point of view very significant happening here.

**Comment by aviczhl2** [comment]
67 now. Not small.

**Comment by FedeGueli** [comment]
@corneliusroemer pls reopen this one
showing further spike diversity (even if not very successful as 335F or 105F) as S:Q607R 
![Schermata 2023-10-05 alle 10 33 30](https://github.com/cov-lineages/pango-designation/assets/87669813/be0f23b0-8e8f-4780-8426-9576194bdb7b)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2a402_e74280.json?label=id:node_3997756

**Comment by FedeGueli** [comment]
82 now

**Comment by Over-There-Is** [comment]
+4, Sichuan 1, NSW 3, seem recombined

**Comment by FedeGueli** [comment]
@corneliusroemer please reopen this one.

**Comment by Over-There-Is** [comment]
seems only 2 has A17267G(ORF1b:D1267G).

**Comment by FedeGueli** [comment]
> seems only 2 has A17267G(ORF1b:D1267G).

Thanks for noticing @NkRMnZr please change the proposal to C11173T only. It is still Branch 10.

**Comment by FedeGueli** [comment]
Thank you @NkRMnZr , all credit to @Over-There-Is i only rechecked if it has been merged to other trees in the meanwhile.

**Comment by Over-There-Is** [comment]
328

**Comment by FedeGueli** [comment]
495

**Comment by Over-There-Is** [comment]
565?

**Comment by FedeGueli** [comment]
@corneliusroemer this is quite big a pity to leave it out from a designation, not urgent nor important but still...

**Comment by aviczhl2** [comment]
668 seqs now. @corneliusroemer
