### ISSUE TITLE
EG.5.1.4 with Orf3a:P240L, ORF1a:R1170H and S:V483I  (18 samples from England-only Climb no Gisaid)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2254]
cc @corneliusroemer this apparently is growing fast it could be a cluster but it reached 18 on CLIMB database before getting anyone uploaded to Gisaid. I suggest if it pops up outside Uk to designate it for two reasons:
1) Fast backbone
2) Key RBD mutation 
Transferred 
From the original proposal: https://github.com/sars-cov-2-variants/lineage-proposals/issues/710

Defining mutations:
**EG.5.1.4** >> **Orf3a:P240L** (C26111T) > T9115C > **ORF1a:R1170H** (G3774A = NSP3_R352H), **S:V483I** ( G23009A)

Tree:
![Schermata 2023-09-04 alle 00 48 09](https://github.com/cov-lineages/pango-designation/assets/87669813/6bbf285d-5d26-49fc-8188-23f14cddaca2)
![Schermata 2023-09-04 alle 00 48 31](https://github.com/cov-lineages/pango-designation/assets/87669813/ce1521c2-6688-4fc5-a1ec-01228bcd22ca)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1b127_50a1d0.json?c=gt-S_483&gmax=25384&gmin=21563&label=id:node_6937949

Samples:
England/CLIMB-CM7YGJSW/2023\|2023-08-21
England/CLIMB-CM7YEI3F/2023\|2023-08-19
England/CLIMB-CM7YJQA4/2023\|2023-08-19
England/CLIMB-CM7YFWSI/2023\|2023-08-21
England/CLIMB-CM7YKGGZ/2023\|2023-08-24
England/CLIMB-CM7YKXEZ/2023\|2023-08-24
England/CLIMB-CM7YGFKO/2023\|2023-08-24
England/CLIMB-CM7YKOT9/2023\|2023-08-23
England/CLIMB-CM7YENF8/2023\|2023-08-23
England/CLIMB-CM7Y8M7G/2023\|2023-08-25
England/CLIMB-CM7YRXWI/2023\|2023-08-29
England/CLIMB-CM7YEB75/2023\|2023-08-26
England/CLIMB-CM7YKWXI/2023\|2023-08-24
England/CLIMB-CM7YFQO3/2023\|2023-08-29
England/CLIMB-CM7YJ9JM/2023\|2023-08-23
England/CLIMB-CM7YFY64/2023\|2023-08-23
England/CLIMB-CM7YF3NC/2023\|2023-08-23
England/CLIMB-CM7YE4T4/2023\|2023-08-23

Gisaid query : G23009A,G3774A
finds 0 Sequences.

[New data](https://dms-vep.github.io/SARS-CoV-2_XBB.1.5_spike_DMS/htmls/summary_overlaid.html) from J.Bloom
shows as S:V483I could be slighty advantageous both for Binding,ENtry and escape:

![Schermata 2023-09-04 alle 00 53 23](https://github.com/cov-lineages/pango-designation/assets/87669813/849703d8-1d3a-4bd9-8d31-fd2b4ef3c6c9)

While [data ](https://tstarrlab.github.io/SARS-CoV-2-RBD_DMS_Omicron-XBB-BQ/RBD-heatmaps/)from T.Starr could indicate both directions:
![Schermata 2023-09-04 alle 00 53 46](https://github.com/cov-lineages/pango-designation/assets/87669813/6a12f332-ea39-4027-a13a-f7dc2642ad43)

**Comment by corneliusroemer** [comment]
too early: we need GISAID genomes, and ideally more than just England spread

**Comment by FedeGueli** [comment]
> too early: we need GISAID genomes, and ideally more than just England spread

yes obviously. i will trck in the other repo.

**Comment by FedeGueli** [comment]
By the way three now on Gisaid : EPI_ISL_18216158, EPI_ISL_18216304, EPI_ISL_18216306

**Comment by FedeGueli** [comment]
Now all the 18 samples are on Gisaid:
EPI_ISL_18216158, EPI_ISL_18216304, EPI_ISL_18216306,
EPI_ISL_18227081, EPI_ISL_18227104, EPI_ISL_18227314,
EPI_ISL_18227316, EPI_ISL_18227319-18227321, EPI_ISL_18227323-18227325,
EPI_ISL_18227354, EPI_ISL_18227369, EPI_ISL_18227375,
EPI_ISL_18227377-18227378


cc @corneliusroemer

**Comment by FedeGueli** [comment]
28 samples on Gisaid now . cc @corneliusroemer its doubling seems fast

**Comment by corneliusroemer** [comment]
England has pretty much the biggest overdispersion=clustering of any country. Need to divide numbers mentally by 5.

Will designate once this gets picked up somewhere else.

**Comment by FedeGueli** [comment]
> England has pretty much the biggest overdispersion=clustering of any country. Need to divide numbers mentally by 5.
> 
> Will designate once this gets picked up somewhere else.

Likely only Canada is worse than it. I think it is correct to wait until.it preads to another country at least. I ll keepmit updated

**Comment by FedeGueli** [comment]
32

**Comment by FedeGueli** [comment]
37 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G23009A%2CG3774A&analysisMode=CompareToBaseline&
