### ISSUE TITLE
New EG.5+Orf1a:Q990R,Orf1b:S2212I, S:Q14K,A522P in China(43 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2256]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/632

EG.5+A3234G, G20102T, A20532G, G23126C,T9622C, C21602A (Orf1a:Q990R,Orf1b:S2212I, S:Q14K,A522P)

GISAID query:G23126C,C21602A,A20532G
No. of seqs:21 ( Shanghai 19, USA 1 Italy 1)

First: EPI_ISL_17994570, Shanghai, 2023-7-5
Latest: EPI_ISL_18213125 Italy, 2023-8-30

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/eg_5_a522p_q14k.json?gt=S.522P&label=id:node_6954062)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/f9a2a998-5639-4076-b8f3-735f83533f6b)

**Comment by aviczhl2** [comment]
+1 Japan

**Comment by aviczhl2** [comment]
Seems dead.

**Comment by FedeGueli** [comment]
Thank you, i m planning a big closing day
