### ISSUE TITLE
EG.6.1 Sublineage with S:L242I, S:A484K, ORF1a: P1786L, ORF1b:R1576K (39 seq, 10 countries, Sept 21)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2257]
### **Description** (transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/546)
**Sub-lineage of:** EG.6.1 (XBB.1.9.2.6.1 = EG.6 + S:F456L)
**Earliest sequence:** 2023-7-7, Spain — EPI_ISL_17995565
**Most recent sequence:** 2023-8-22, England — England/CLIMB-CM7YFFTX/2023|2023-08-22 (not yet on GISAID)
**Countries circulating:** Portugal (2), South Korea (2), Canada (1), Croatia (1—via USA travel), England (1), Germany (1), France (1), Spain (1), USA (1)
**Number of Sequences:** 11
**GISAID AA Query:** Spike_E484K, Spike_F486P, Spike_L242I
**GISAID Nucleotide Query:** G18194A , T27346C, -A23013C, -A22812C, -G25563T  
**CovSpectrum Query:** Nextcladepangolineage:EG.6.1* & S:E484K
**Substitutions on top of EG.6.1:**
**Spike:** L242I, E484K
**ORF1a:** P1786L
**ORF1b:** R1576K
**Nucleotide:** C5622T, G18194A, C22286A, G23012A, C23013A, C27881T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/EG.6.1_L242I_A484K_v.2.json?c=gt-S_242&gmax=25384&gmin=21563&label=id:node_6978287

<img width="1378" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/de17ca3a-be9f-439c-84ee-66c80ea480eb">

 
**Evidence**
Speaks for itself. S:A484K is a 2-nucleotide mutation, and numerous lineages have picked up A484K, always acquiring the two nucleotide mutations in one jump, with no intermediate sequences. (Usher masks A484K, so the tree is misleading in this respect.)

The number of sequences in this lineage is still small, but the fact that the 11 sequences collected so far come from nine different countries suggests this could be somewhat more common in a country with no surveillance which is exporting cases that haven't yet gained a foothold in other countries. 
 
Note that there are 12 sequences listed on GISAID, but two of them are pooled samples from Ginkgo Bozoworks. One is a duplicate, but the other doesn't have a corresponding individual sequence. Hopefully, an individual sequences will be forthcoming so we can tell which country the traveler came from. 
 
**Genomes**
England/CLIMB-CM7YFFTX/2023|2023-08-22   (not yet on GISAID but on Usher tree)
<details>
<summary>Genomes</summary>
EPI_ISL_17995565, EPI_ISL_18052373, EPI_ISL_18067147, EPI_ISL_18067206, EPI_ISL_18072859, EPI_ISL_18116510, EPI_ISL_18142326, EPI_ISL_18143997, EPI_ISL_18147264, EPI_ISL_18168464, EPI_ISL_18168941, EPI_ISL_18215443
</details>

**Comment by HynnSpylor** [comment]
14 seqs now

**Comment by Sinickle** [comment]
9 sequences from Canada today!

**Comment by DailyCovidCases** [comment]
Please close this issue
