### ISSUE TITLE
EG.5.1.6 + ORF8:R115C (144) mostly USA 

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2259]
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/d36fa99d-4aa1-4848-b117-53376d7bf7e6)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_282b1_610340.json?c=gt-ORF8_115&label=id:node_6939711
Gisaid query: C28236T,C5835T
transferred from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/653

**Comment by corneliusroemer** [comment]
Just founder effect in a country that sequences much - nothing going on in Spike
