### ISSUE TITLE
Two potential sublineages of B.1.621, one with ORF7b:E3stop, and the other with ORF1a:L3210F

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#226]
**Proposed sublineage 1**
**Description**
Sub-lineage of: B.1.621 (121 sequences)
**Earliest sequence**: 2021/3/2 (Colombia)
**Most recent sequence**: 2021/9/2 (the US-NC)
**Countries circulating**: The US (67 sequences), Chile (28 sequences), Ecuador (7 sequences), Colombia (6 sequences), Peru (4 sequences), Spain (4 sequences), Frane (2 sequences), Puerto Rico (2 sequences), Venezuela (1 sequence), Aruba (1 sequence)
**Mutations in addition to B.1.621**: N:D377Y, ORF1a:82/86DEL, ORF1b:M1573I, ORF3a:V256I, ORF7b:E3stop (defining), S:M1237I (defining)
**Genomes**:
[Mu E3stop.csv](https://github.com/cov-lineages/pango-designation/files/7229141/Mu.E3stop.csv)

**Proposed sublineage 2**
**Description**
Sub-lineage of: B.1.621 (239 sequences)
**Earliest sequence**: 2021/4/22 (the US-CA)
**Most recent sequence**: 2021/9/10 (the US-OR)
**Countries circulating**: the US
**Mutations in addition to B.1.621**: ORF1a:S2103F, ORF1a:L3210F (defining), ORF1b:Y512C, ORF1b:E1184D, ORF3a:I20M, ORF3a:V256I
**Genomes**:
[Mu L3210F.csv](https://github.com/cov-lineages/pango-designation/files/7229221/Mu.L3210F.csv)

**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/134759948-d40d9e71-ebaa-4bb3-8beb-dfd77dcf33c6.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_57e80_e70250.json?c=gt-nuc_25273,9893&l=radial

**Comment by corneliusroemer** [comment]
Both proposed lineages are dying out

Sublineage 1
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.621*%22%2C%22mutations%22%3A[%22N%3AD377Y%22%2C%22S%3AM1237I%22]%7D%2C%22matchPercentage%22%3A1%7D

Sublineage 2
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.621*%22%2C%22mutations%22%3A[%22ORF3a%3AI20M%22%2C%22ORF1a%3AS2103F%22]%7D%2C%22matchPercentage%22%3A1%7D

**Comment by InfrPopGen** [comment]
Thank you very much for proposing these as lineages; however, they both fall short of being suitable for designation in one or more of the required criteria (although they do satisfy some of the other criteria). Specifically, in the case of Proposal 1: the proposed member sequences do form a monophyletic clade, but this alone is not sufficient. The proposed lineage is defined by  S:M1237I and ORF7b:E3*, and partially defined by N:D377Y|V; however, these changes occur scattered across the regional sub-tree within which the proposed lineage arises. The sequences proposed correspond to geographically widespread samples, most concentrated in the Americas, but with a few European samples. Further, the lineage appears to be either extinct or in significant relative decline, and none of the variants peculiar to it are of epidemiological significance, aside from its descent from VOI Mu, nor are the cases related to it.

Proposal 2: The cluster defined by the proposed sequences is not monophyletic---the clade contains 8 non-proposed genomes (all US), and excludes two genomes (USA/WA-Altius-ALTCOV-QDD6NRBUV624VVBB/2021|EPI_ISL_2489800|2021-05-17 and USA/WA-Altius-ALTCOV-7Z7EQIOZHE7D3JAN/2021|EPI_ISL_2489793|2021-05-19), which fall in a sister subtree (one of around 50 subtrees currently forming a multifurcation from the common ancestral node). Sample USA/CA-Curative-080256/2021|EPI_ISL_2941902|2021-06-20 also falls well outside the local subtree. The proposed defining mutations are common regionally and globally (on the tree), excepting ORF3a:I20M, which is quite rare globally, but occurs occasionally in B.1.621. All defining mutations are characteristic of the local subtree, except for ORF1a:L3210F, but this is an amino acid replacement commonly occurring on the global tree and especially in B.1.621. The proposed lineage could be expanded to include the local subtree, but it would then lose its geographical character (ie. it would no longer be US). In addition, the lineage appears to be either extinct or in significant relative decline, and none of the variants peculiar to it are of epidemiological significance, aside from its descent from VOI Mu, nor are the cases related to it.

Designation might be appropriate in the future should these subtrees show signs of expansion or involvement in a noteworthy epidemiological event.
