### ISSUE TITLE
XBB.2.3/XBB.1.16 Recombinant (51 seq, Sept 21)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2260]
###  **Description**
**Recombinant of:** XBB.2.3/XBB.1.16
**Breakpoint:** Between S:521 and ORF7a:13 (23123-27430)
**Earliest sequence:** 2023-7-6, USA, Iowa — EPI_ISL_18012194
**Most recent sequence:** 2023-8-21, USA, Maryland — EPI_ISL_18163068
**Countries circulating:** USA (28), India (1)
**Number of Sequences:** 29
**GISAID AA Query:** Spike_I210del, Spike_P521S
**GISAID Nucleotide Query:** T6394C, G8863T, T14305C
**CovSpectrum Query:** [5-of: T6394C, G8863T, T14305C, G18636A, T18882C, C27684T, C27513T, T28034C]
**Substitutions/Deletions on top of XBB.2.3/XBB.1.16:**
**Spike:** I210del
**ORF1b:**Y280H
**Nucleotide:** T6394C, G8863T, T14305C, G18636A, T18882C, ∆22190-22192, C27684T, C27513T, T28034C

 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.2.3_XBB.1.16_Recombinant.json?c=gt-nuc_8863&gmax=9863&gmin=7863&label=id:node_7391224 
 
<img width="1499" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/44cba671-d559-4718-94fe-fd0b6a67ba40">

**Evidence**
XBB.2.3 has never picked up ORF9b:I5T, which has proven advantageous for XBB.1* lineages. It has also never picked up an ORF8 stop codon. It's not clear if there's a connection between those two things, but this recombinant lineage has picked up both, along with ORF9b:N55S. It seemed slow for a while, but in the past week its numbers have doubled from ~15 to ~30.

Just one sequence has been from India, but given the extremely low level of sequencing in that country of over 1.4 billion, it's possible this lineage is more common there than anywhere else.
 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18012194, EPI_ISL_18012785, EPI_ISL_18061007,
EPI_ISL_18098772, EPI_ISL_18099225, EPI_ISL_18107710,
EPI_ISL_18113783, EPI_ISL_18115190, EPI_ISL_18119727,
EPI_ISL_18119760, EPI_ISL_18120279, EPI_ISL_18120962,
EPI_ISL_18121722, EPI_ISL_18126531, EPI_ISL_18131591,
EPI_ISL_18160398, EPI_ISL_18162514, EPI_ISL_18162532,
EPI_ISL_18162559, EPI_ISL_18162596, EPI_ISL_18162936,
EPI_ISL_18163068, EPI_ISL_18165514, EPI_ISL_18165596,
EPI_ISL_18168409, EPI_ISL_18212749, EPI_ISL_18212766,
EPI_ISL_18212811, EPI_ISL_18216934
</details>

**Comment by ryhisner** [comment]
The longest branch in this lineage is a sequence from Illinois, USA, that has what is either an unusual artifact or an unusual combination of mutations in NSP3. This is a CDC sequence, and they are invariably of high quality, so I'm inclined to think it's real.     EPI_ISL_18212749
ORF1a:T1055L, V1056L, V1057I
A3428T, C3429T, G3431C, G3433A, G3434A
<img width="1475" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/a58cb48d-b008-469e-8214-a964b606c5d6">

If it is real, it's possible it is an import from ORF6, specifically 27243-27252. However, it's easy to fool yourself with coincidental similarities, and this could be a coincidence. 
.
<img width="1506" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/c377e4cd-5856-47b8-9887-ba56db189bb1">

**Comment by FedeGueli** [comment]
Original issue : https://github.com/sars-cov-2-variants/lineage-proposals/issues/535

**Comment by aviczhl2** [comment]
The XBB.2.3-side donor is from a subbranch used to have 15% prevalence in Bangladesh. https://github.com/sars-cov-2-variants/lineage-proposals/issues/328

**Comment by ryhisner** [comment]
The first European sequences came in yesterday and today: one from Germany and one from France. Both collected August 21. EPI_ISL_18229297, EPI_ISL_18234598

**Comment by ryhisner** [comment]
First sequence from Canada, collected August 22: EPI_ISL_18256685

**Comment by FedeGueli** [comment]
47 as today

**Comment by FedeGueli** [comment]
now 58. it slowed a lot in my chart. https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=T6394C%2CG8863T%2CT14305C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Designated XCW via https://github.com/cov-lineages/pango-designation/commit/f44449ccb56ad5c6b622ecf664bae6c329eeea46

**Comment by FedeGueli** [comment]
@corneliusroemer you should add the milestone here casue Ryan proposed this one directly here without preproposal in the secondary report.

**Comment by FedeGueli** [comment]
> @corneliusroemer you should add the milestone here casue Ryan proposed this one directly here without preproposal in the secondary report.

Scratch that it's already in lineage notes .
