### ISSUE TITLE
Sibling lineage of XBB.1.5.59 with F456L and Orf1a:T654A spreading in South Korea and South America (58 on Gisaid  seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2262]
transferred from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/471

In the same tree of XBB.1.5.59 and XCF now is clearly visible  a new XBB.1.5 sublineage with S:F456L

Gisaid query: A2225G,C5512T, C17439T, A29700G
finds : **52** samples
from 14 countries  (5 from central and south america, 6 Europe , 2 North american, 1 Asia , )

<Details>
<summary>
Samples: 
First:2023-05-11 Florida
Last:2023-08-10 Scotland
</summary>
EPI_ISL_17768046, EPI_ISL_17779305, EPI_ISL_17780614,
EPI_ISL_17816933, EPI_ISL_17853017, EPI_ISL_17853114,
EPI_ISL_17954142, EPI_ISL_17960522, EPI_ISL_17969427,
EPI_ISL_17969448, EPI_ISL_17979152, EPI_ISL_18010883,
EPI_ISL_18011000, EPI_ISL_18031207-18031210, EPI_ISL_18031547-18031551,
EPI_ISL_18053842, EPI_ISL_18071446, EPI_ISL_18076699,
EPI_ISL_18076891, EPI_ISL_18095455, EPI_ISL_18112759,
EPI_ISL_18113391, EPI_ISL_18113484, EPI_ISL_18113718,
EPI_ISL_18115236, EPI_ISL_18116045, EPI_ISL_18118344,
EPI_ISL_18120143, EPI_ISL_18129938, EPI_ISL_18129947,
EPI_ISL_18129971, EPI_ISL_18130464, EPI_ISL_18134868,
EPI_ISL_18160093, EPI_ISL_18167876, EPI_ISL_18167898,
EPI_ISL_18167929, EPI_ISL_18167935, EPI_ISL_18168003,
EPI_ISL_18168043, EPI_ISL_18168066, EPI_ISL_18168097,
EPI_ISL_18168103, EPI_ISL_18168171, EPI_ISL_18210717,

</details>

Defining mutations:
**XBB.1.5 >> S:F456L (T22928C) > Orf1a:T654A (A2225G), C5512T, C17439T, A29700G**

Tree:
 
![Schermata 2023-09-05 alle 13 55 17](https://github.com/cov-lineages/pango-designation/assets/87669813/7eac81e3-ef2c-44df-a3e4-0c1c3ee003a9)

![Schermata 2023-09-05 alle 13 53 34](https://github.com/cov-lineages/pango-designation/assets/87669813/13abfc49-cead-44fa-a23d-4887c567158d)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_151eb_7167e0.json?c=gt-nuc_2225&gmax=3225&gmin=1225&label=id:node_7293003

The tree has split in two and both the branches are showing sublineages potentially interesting (one with S:A684T,one with  Orf3:S26L as Delta, a couple of seqs with S:N>K679R

Note that Usher misclassify it as XBB.1.5.59 while it is missing the defining mutation of XBB.1.5.59 (cc @AngieHinrichs )
![Schermata 2023-07-25 alle 17 07 47](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a5c6a30b-e79c-423a-9e16-0f02bafac492)

Growth comparison: 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=A2225G%2CC5512T%2CC17439T%2CA29700G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
58 on gisaid now.

**Comment by corneliusroemer** [comment]
Too small and doesn't have novel RBD haplotype either

**Comment by aviczhl2** [comment]
Designated XBB.1.5.109.
