### ISSUE TITLE
EG.5.1 with ORF1a:P309Q (nsp2_P129Q), S:D1146A and S:T573I (126 seqs, mainly in Japan, 6 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2263]
_Transferred from sars-cov-2-variants/lineage-proposals/issues/515_

**Defining Mutations:** `EG.5.1` > `T15198A` > `C1191A(ORF1a:P309Q), A24999C(S:D1146A), A27642G, A28254Δ(ORF8:I121Δ)` > `C23280T(S:T573I)`
**Query:** `T15198A, C23280T, A24999C, -T3283C`
**Earliest seq:** 2023-06-22 (`EPI_ISL_17978793`, Kyoto, Japan)
**Latest seq:** 2023-08-17 (`EPI_ISL_18208965`, Yamaguchi, Japan)
**Sampled Countries:** Japan (39), USA (2, travel history to Japan), Singapore (1), South Korea (1), Thailand (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17978793, EPI_ISL_18006986, EPI_ISL_18010885, EPI_ISL_18011011, EPI_ISL_18013372, EPI_ISL_18040388, EPI_ISL_18040838, EPI_ISL_18047763, EPI_ISL_18051713, EPI_ISL_18051715-18051717, EPI_ISL_18051719, EPI_ISL_18065167, EPI_ISL_18065241, EPI_ISL_18071748-18071749, EPI_ISL_18077506-18077508, EPI_ISL_18077516-18077517, EPI_ISL_18077546, EPI_ISL_18097627, EPI_ISL_18100801, EPI_ISL_18100829, EPI_ISL_18101021-18101022, EPI_ISL_18130199, EPI_ISL_18139883, EPI_ISL_18140796, EPI_ISL_18141033, EPI_ISL_18141196, EPI_ISL_18160810, EPI_ISL_18164704, EPI_ISL_18164970, EPI_ISL_18166492, EPI_ISL_18166637, EPI_ISL_18207825, EPI_ISL_18208965, EPI_ISL_18214788, EPI_ISL_18214809, EPI_ISL_18217956, EPI_ISL_18218257`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f3c0_7224e0.json?c=gt-S_573&f_userOrOld=uploaded%20sample&gmax=25384&gmin=21563&label=id:node_6940435

view from EG.5 polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/c4bbeeed-9a27-48fc-b124-470dd153a6a9)

diveristy from `T15198A` branch
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/4454ccd6-5440-4ba1-8458-24cfd1626f71)

details
![details](https://github.com/cov-lineages/pango-designation/assets/125747944/e7932fa2-aa79-4689-830c-c2e92ddd5792)

**Comment by corneliusroemer** [comment]
Too small for now
