### ISSUE TITLE
EG.1 with ORF1a:G379R (nsp3_G1007R) and S:L452R (122 seqs, mainly South Korea, 7 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2268]
_Transferred from sars-cov-2-variants/lineage-proposals#713_

**Defining Mutations:** `EG.1` > `C21306T` > `G1400A(ORF1a:G379R)` > `T22917G(S:L452R), C29218T`
**Query:** `G1400A, C21306T, T22917G`
**Earliest seq:** 2023-05-30 (`EPI_ISL_17927651`, South Korea)
**Latest seq:** 2023-08-13 (`EPI_ISL_18143415`, British Columbia, Canada)
**Sampled Countries:** South Korea (48), China (1, ex. South Korea), Canada (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17835109, EPI_ISL_17835518, EPI_ISL_17927651, EPI_ISL_17927653-17927654, EPI_ISL_17930639, EPI_ISL_17970523, EPI_ISL_18030840, EPI_ISL_18031123, EPI_ISL_18031405, EPI_ISL_18031924, EPI_ISL_18038893, EPI_ISL_18039139, EPI_ISL_18039142, EPI_ISL_18046758, EPI_ISL_18046799, EPI_ISL_18047378, EPI_ISL_18047420, EPI_ISL_18047452, EPI_ISL_18047694, EPI_ISL_18067746, EPI_ISL_18067752, EPI_ISL_18067802, EPI_ISL_18068044, EPI_ISL_18068048, EPI_ISL_18068161, EPI_ISL_18068279, EPI_ISL_18111501, EPI_ISL_18116372, EPI_ISL_18116717, EPI_ISL_18116947, EPI_ISL_18117940, EPI_ISL_18117987, EPI_ISL_18117998, EPI_ISL_18134244, EPI_ISL_18139900, EPI_ISL_18139903, EPI_ISL_18140041, EPI_ISL_18140304, EPI_ISL_18140327-18140330, EPI_ISL_18140363, EPI_ISL_18140612, EPI_ISL_18143415, EPI_ISL_18165980-18165982, EPI_ISL_18213780`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3922a_733d30.json?f_userOrOld=uploaded%20sample&label=id:node_6975798
![details](https://github.com/cov-lineages/pango-designation/assets/125747944/e5baf9a8-e99b-4fb4-8f25-1b3fe4248025)

**Trivia:**
- 2 US samples `USA/CA-HLX-STM-NW8AZRHVG/2023|EPI_ISL_18069601|2023-07-18` and `USA/NV-SNPHL-772840/2023|EPI_ISL_18078844|2023-07-20` have Ns around `Spike_452` probably causing the split of branches.

**Comment by FedeGueli** [comment]
98 now
