### ISSUE TITLE
A few potential sublineage of B.1.1.7

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#227]
**Proposed sublineage 1**
**Description**
**Sub-lineage of**: B.1.1.7 (414 sequences)
**Earliest sequence**: 2021/3/9 (the US-FL)
**Most recent sequence**: 2021/8/24 (the US-AK)
**Countries circulating**: The US (410 sequences), Canada-QC (4 sequences)
**Mutations in addition to B.1.1.7**: S:K1191N, ORF6:L52V (defining)
**Genomes**:
[Alpha L52V.csv](https://github.com/cov-lineages/pango-designation/files/7229435/Alpha.L52V.csv)
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/134765079-68201ff6-3f70-479b-8342-2175d78f3e60.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_5cf69_ed2a40.json?c=gt-ORF6_52&l=radial

**Proposed sublineage 2**
**Description**
**Sub-lineage of**: B.1.1.7 (315 sequences)
**Earliest sequence**: 2021/3/24 (the US-LA)
**Most recent sequence**: 2021/9/4 (the US-TX)
**Countries circulating**: the US (314 sequences), Bosnia_and_Herzegovina (1 sequence)
**Mutations in addition to B.1.1.7**: ORF1a:M2259I, ORF1a:A3209V (defining), ORF1b:P218L, ORF8:C61F
**Genomes**:
[Alpha A3209V.csv](https://github.com/cov-lineages/pango-designation/files/7229639/Alpha.A3209V.csv)
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/134769361-587087e0-0979-454a-b5b4-34bbb6134b31.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36682_e59a20.json?c=gt-nuc_9891&l=radial

**Proposed sublineage 3**
**Description**
**Sub-lineage of**: B.1.1.7 (237 sequences)
**Earliest sequence**: 2021/4/16 (Canada-QC)
**Most recent sequence**: 2021/9/6 (Canada-NB)
**Countries circulating**: Canada (predominantly Quebec and New Brunswick)
**Mutations in addition to B.1.1.7**: S:L216F, ORF3a:W131C, ORF1b:H1387Y (defining)
**Genomes**:
[Alpha H1387Y.csv](https://github.com/cov-lineages/pango-designation/files/7229460/Alpha.H1387Y.csv)
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/134765725-e357c76c-2962-452f-b3fe-2e60b409f72f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_45765_e68020.json?c=gt-nuc_17626&l=radial

**Proposed sublineage 4**
**Description**
**Sub-lineage of**: B.1.1.7 (90 sequences)
**Earliest sequence**: 2021/5/10 (the Netherlands)
**Most recent sequence**: 2021/8/26 (Sweden)
**Countries circulating**: Greece (64 sequences) and some other European countries
**Mutations in addition to B.1.1.7**: 
Spike: S98F, D138H, G181V (defining), 
N:N8D, G243C, Q289H (defining),
ORF1a: E2K (defining), L730F, 
ORF8: W45L
**Genomes**:
[Alpha E2K.csv](https://github.com/cov-lineages/pango-designation/files/7229474/Alpha.E2K.csv)
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/134766147-395a6d2e-a9b7-4ca5-b141-8ccbcaf91091.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_37a2c_e5c480.json?c=gt-nuc_269&l=radial

**Proposed sublineage 5**
**Description**
**Sub-lineage of**: B.1.1.7 (144 sequences)
**Earliest sequence**: 2021/6/23 (Japan)
**Most recent sequence**: 2021/9 (Japan)
**Countries circulating**: Japan
**Mutations in addition to B.1.1.7**: S:QS836R, S:G1251R (defining), ORF1b:E1184D, ORF1b:T2537I (defining)
**Genomes**:
[Alpha G1251R.csv](https://github.com/cov-lineages/pango-designation/files/7229672/Alpha.G1251R.csv)
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/134770171-4182f021-a042-40a7-983e-baf7917b3411.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_65c67_df3e20.json?c=gt-S_1251&l=radial

**Proposed sublineage 6**
**Description**
**Sub-lineage of**: B.1.1.7 (38 sequences)
**Earliest sequence**: 2021/6/14 (Korea ex-Mongolia)
**Most recent sequence**: 2021/9/6 (Japan ex-Mongolia)
**Countries circulating**: Australia-QLD (31 sequences)
**Detected at border entry**: Korea ex-Mongolia (4 sequences, on 4 different occasions), Korea ex-India (1 sequence), Japan ex-Mongolia (1 sequence)
**Mutations in addition to B.1.1.7**: 
**Genomes**:
[Alpha ex-Mongolia.csv](https://github.com/cov-lineages/pango-designation/files/7229731/Alpha.ex-Mongolia.csv)
**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/134772240-15c1499d-7d40-4685-9751-7fc247f97734.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_572a3_cfcb20.json?c=gt-nuc_3821&l=radial

**Proposed sublineage 7**
**Description**
**Sub-lineage of**: B.1.1.7 (121 sequences)
**Earliest sequence**: 2021/5/16 (Cambodia)
**Most recent sequence**: 2021/9/10 (Cambodia)
**Countries circulating**: Cambodia (118 sequences)
**Detected at border entry**: Korea ex-Cambodia (1 sequence), Hong Kong ex-Cambodia (1 sequence)
**Mutations in addition to B.1.1.7**: C13115T (defining), ORF9b:P10S, S:E484K, ORF1a:P3504L
**Genomes**:
[Alpha Cambodia.csv](https://github.com/cov-lineages/pango-designation/files/7229856/Alpha.Cambodia.csv)
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/134774035-f2f06f3b-40c6-47b3-8a82-dbdd282007cc.png)
https://nextstrain.org/fetch/genome-euro.ucsc.edu/trash/ct/subtreeAuspice1_genome_euro_f1a_b5f1e0.json?c=gt-nuc_13115&l=radial

**Comment by corneliusroemer** [comment]
Here are cov-spectrum frequency analyses - I think it'd be useful if you included a link to the frequency analyses with every proposed lineage. I'm doing it now. @c19850727 

Is it worth designating dead lineages? 

Sublineage
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22mutations%22%3A[%22S%3AK1191N%22%2C%22ORF6%3AL52V%22]%7D%2C%22matchPercentage%22%3A1%7D

![image](https://user-images.githubusercontent.com/25161793/134780195-52aff7dd-5655-496e-8dfa-b20c9ab67293.png)

Sublineage 2
![image](https://user-images.githubusercontent.com/25161793/134780240-712307e2-1a9d-44ae-b02e-bbc26fb0466f.png)
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22mutations%22%3A[%22ORF8%3AC61F%22%2C%22ORF1a%3AM2259I%22%2C%22ORF1a%3AA3209V%22]%7D%2C%22matchPercentage%22%3A1%7D

Sublineage 3
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.1.7*%22%2C%22mutations%22%3A[%22S%3AL216F%22%2C%22ORF3a%3AW131C%22]%7D%2C%22matchPercentage%22%3A1%7D

Sublineage 4
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.1.7*%22%2C%22mutations%22%3A[%22S%3AS98F%22%2C%22S%3AD138H%22%2C%22S%3AG181V%22]%7D%2C%22matchPercentage%22%3A1%7D

Sublineage 5
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.1.7*%22%2C%22mutations%22%3A[%22S%3AG1251R%22%2C%22S%3A836R%22]%7D%2C%22matchPercentage%22%3A1%7D

Sublineage 7 is the only one that's not obviously dying out
![image](https://user-images.githubusercontent.com/25161793/134780450-6a6e8c20-020b-48b8-a697-aca598d003f1.png)

https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.1.7*%22%2C%22mutations%22%3A[%22ORF9b%3AP10S%22%2C%22S%3AE484K%22%2C%22ORF1a%3AP3504L%22]%7D%2C%22matchPercentage%22%3A1%7D

**Comment by shay671** [comment]
Hi @c19850727  

Number 4 seems very problematic and has features of variant based variant : 

a "jump" of 10 mutations.  and this is from a region which is sequencing not that bad, meaning we can suspect it is a result of improvement in the body of one patient. 

7/10 of those are non synonymous. 

out of those 7 - 3 are in the S1 (all in NTD) and 2 in N. 

Another mutation in N (above the 10)  gave a branch which responsible for the most of  the samples.

**Comment by LilKitt** [comment]
Is there section on this site or someplace else to discuss findings with others?

**Comment by c19850727** [comment]
Many of the proposed sublineages don't survive.
May I close this issue and make new submissions of the few that're still circulating.

**Comment by FedeGueli** [comment]
> Many of the proposed sublineages don't survive. May I close this issue and make new submissions of the few that're still circulating.

Hi @c19850727 i suggest you to open an issue for sublineage 7, still circulating in Cambodia and Thailand.

https://nextstrain.org/groups/neherlab/ncov/global?branchLabel=aa&c=gt-ORF1a_3504&tl=pango_usher
![Schermata 2021-10-31 alle 19 18 56](https://user-images.githubusercontent.com/87669813/139596629-2bcfe6dc-8b4a-4e99-9c83-baed6d957941.png)
![Schermata 2021-10-31 alle 19 19 34](https://user-images.githubusercontent.com/87669813/139596646-492e25f6-c093-4d7c-a049-ed88ac6f92d7.png)
https://cov-spectrum.ethz.ch/explore/Asia/AllSamples/AllTimes/variants?aaMutations=ORF1a%3AP3504L%2CS%3AE484K&nucMutations=C1825T%2CC17862T%2CC29585T&pangoLineage=B.1.1.7*
