### ISSUE TITLE
/

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2273]

**Comment by aviczhl2** [comment]
#2210

**Comment by FedeGueli** [comment]
it was proposed in https://github.com/cov-lineages/pango-designation/issues/2210

**Comment by FedeGueli** [comment]
> Was proposed in #2210. The EG.5.1 side is EG.5.1.3.

my bad i did tell ryan it wasnt proposed. Recomb are hard to find back.
