### ISSUE TITLE
XBB.1.5.70 sublineage with ORF1a:T2859I and ORF1b:T310I (20 seq) and a further sublineage with S:A475V (10 seq. France, Spain, China, USA, UK)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#2276]
Defining mutations: XBB.1.5.70 then nuc:C12469T then ORF1a:T2859I(C8841T), ORF1b:T310I(C14396T), nuc:C18807T
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/509797fe-758d-4e3a-b398-1faccaff90ea)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36b9_ced9a0.json?label=id:node_7249805
This thing share nuc:C12469T with GK.3. I'm not sure about what to do with it. Broaden GK.3 or designate it with GK.x?
![2](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/1abf9708-3f83-4d50-b02b-b784e5f9a3cd)

**Comment by corneliusroemer** [comment]
This looks too suspicious (potential artefact due to 475V popping up twice there nearby each other) for it to be worth the risk at this point given it's only 10 sequences. It's spike is the same as GK.3.1 so not pressing to designate.
