### ISSUE TITLE
Delta sublineage dominant in Liberia with S:222V and ORF1a:640D

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#228]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: B.1.617.2 (part of the early Delta split lineage with S:222V, then nuc:C2509T)
Earliest sequence: Liberia 2021-10
Most recent sequence: Current in US, UK, Belgium
Countries circulating: Dominant in Liberia (at least in most recent sequences from CW 27), circulating also in US, UK etc.

Contains defining mutation: ORF1a:640D on top of amongst others: S:222V and  nuc:C2509T

Country | Total Variant Sequences | First seq. found at | Last seq. found at |  
-- | -- | -- | -- | --
Australia | 5 | 2021-22 | 2021-27 |  
Belgium | 41 | 2021-24 | 2021-37 |  
Bulgaria | 9 | 2021-26 | 2021-31 |  
Canada | 9 | 2021-23 | 2021-30 |  
Costa Rica | 1 | 2021-29 | 2021-29 |  
Denmark | 12 | 2021-27 | 2021-32 |  
Finland | 2 | 2021-28 | 2021-30 |  
France | 197 | 2021-25 | 2021-35 |  
Germany | 23 | 2021-25 | 2021-36 |  
Ghana | 6 | 2021-21 | 2021-31 |  
Greece | 1 | 2021-32 | 2021-32 |  
India | 3 | 2021-22 | 2021-32 |  
Israel | 5 | 2021-24 | 2021-32 |  
Italy | 10 | 2021-27 | 2021-35 |  
Japan | 4 | 2021-24 | 2021-29 |  
Liberia | 51 | 2021-10 | 2021-27 |  
Monaco | 1 | 2021-29 | 2021-29 |  
Netherlands | 9 | 2021-31 | 2021-35 |  
Nigeria | 3 | 2021-30 | 2021-30 |  
Poland | 7 | 2021-33 | 2021-34 |  
Portugal | 2 | 2021-31 | 2021-32 |  
Russia | 1 | 2021-27 | 2021-27 |  
Slovakia | 1 | 2021-29 | 2021-29 |  
South Korea | 1 | 2021-24 | 2021-24 |  
Sweden | 6 | 2021-23 | 2021-34 |  
Switzerland | 11 | 2021-27 | 2021-36 |  
Togo | 2 | 2021-24 | 2021-26 |  
Turkey | 16 | 2021-26 | 2021-36 |  
United Kingdom | 19 | 2021-23 | 2021-37 |  
United States | 1326 | 2021-22 | 2021-37

![image](https://user-images.githubusercontent.com/25161793/134783250-069f2a25-a1e5-4dec-9f91-13ca1c1a9706.png)

https://cov-spectrum.ethz.ch/explore/Liberia/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22s%3A222v%22%2C%22orf1a%3A640d%22]%7D%2C%22matchPercentage%22%3A1%7D

Genomes (~ 2000)
[lib.txt](https://github.com/cov-lineages/pango-designation/files/7230231/lib.txt)

![image](https://user-images.githubusercontent.com/25161793/134783346-e1e89685-df1b-47bc-8e1c-f43ee9782ad3.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_5adef_f71f60.json?label=nuc%20mutations:T1191C,T1267C,A5584G,C11514T,C13019T,C22227T

Just Liberia (earliest sequences of this lineage)
![image](https://user-images.githubusercontent.com/25161793/134783351-7435e51d-0e3e-4974-8d03-4203f54b686f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_57a8e_f6f8e0.json?label=nuc%20mutations:C1191T,C1267T,C5184T

Designating this lineage helps remove problems with AY.10 and AY.12 since pango currently classifies many members of this lineage wrongly (see #186)
![image](https://user-images.githubusercontent.com/25161793/134783395-8833a4ec-f51b-4d8f-8bac-0851732fea6a.png)

Proposed lineage name
AY.x

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as AY.37 in [v1.2.80](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.80) with 942 sequence designations. We've started the lineage on a branch with T20911C (synonymous) which coincides with the start of the Liberia/USA/France clade

**Comment by corneliusroemer** [comment]
@chrisruis Thanks! I trust your decisions. If you have general feedback on the format of my proposals, please let me know - since I've done a number of them and will probably keep making proposals, let's make it as smooth for all of us as possible! Is there anything you find particularly useful, things I could leave out?

**Comment by chrisruis** [comment]
Hi @corneliusroemer Your proposals look great! I think the key things are the list of sequences in the proposed lineage and a summary of why it's being proposed so we can figure out where to start it. And a tree showing where it clusters is always useful as well. Thanks
