### ISSUE TITLE
FL.21 (or XBB.1.9.1) sublineage with Orf7a:T14I, Orf8:C90S(40 seq, 3 countries) then S:F456L(29 seq, 8 states in USA)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2282]
Query: C9166T, A10564T(Edited)
Query for F456L sequences: C9166T, A10564T, T22928C

Transferred from sars-cov-2-variants/lineage-proposals#617

FL.21> T2845C, C4543T, C9166T, A16431G, C27434T(Orf7a:T14I), T28161A(~Orf8:C90S~)
Or XBB.1.9.1> C27434T(Orf7a:T14I)> T2845C, C4543T, C9166T, A10564T, A16431G, T28161A(~Orf8:C90S~)
Then> C5144T> T22928C(S:F456L)

Earliest sequence: 04-22 Virginia, USA EPI_ISL_17593231
Earliest sequence with F456L: 06-23 Louisiana, USA EPI_ISL_18053704
Latest sequences: 08-31 Houston, Texas, USA EPI_ISL_18264671
\*A sequence from Tennesse was assigned as collected on 01-24, but according to phylogenic tree, its collecting date is probably mislabeled.

Regions detected: **US** 8+**29**(**Texas** 5+**21**, **California** 1+**2**, **Tennesse** 1+**1**, **Louisiana 1**, **New Jersey 1**, **New York 1**, **North Carolina 1**, Virginia 1, **Wisconsin 1**), Spain 2(Castilla y Leon 1, Murcia 1), UK 1(England)
The number of sequences with F456L is bolded.

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_1644e_1aac30.json?label=id:node_6918650
![2023-09-14 (3)](https://github.com/cov-lineages/pango-designation/assets/38100637/bbb4bfe3-562a-4f9e-bf3e-02493d55e29c)

<details><summary>Sequences:</summary>

EPI_ISL_17593231, EPI_ISL_17806562, EPI_ISL_17808967,
EPI_ISL_17855155, EPI_ISL_17955566, EPI_ISL_17955640,
EPI_ISL_18053704, EPI_ISL_18057201, EPI_ISL_18057212,
EPI_ISL_18069723, EPI_ISL_18072239, EPI_ISL_18076295,
EPI_ISL_18080870, EPI_ISL_18090095, EPI_ISL_18104390,
EPI_ISL_18107733, EPI_ISL_18118197, EPI_ISL_18163828,
EPI_ISL_18163946, EPI_ISL_18163973, EPI_ISL_18164002,
EPI_ISL_18164401, EPI_ISL_18164596, EPI_ISL_18210849,
EPI_ISL_18212504, EPI_ISL_18222756, EPI_ISL_18233897,
EPI_ISL_18241729, EPI_ISL_18256236, EPI_ISL_18256260,
EPI_ISL_18256388, EPI_ISL_18264671, EPI_ISL_18266867,
EPI_ISL_18267510

</details>

**Comment by corneliusroemer** [comment]
Almost all US-Texas, US produces 40% of global samples so 40 isn't much.

The RBD genotype is boring, just another XBB.1.9.1 + 456L

**Comment by Over-There-Is** [comment]
F456L> G15380A(Orf1b:S638N)> A22995G(S:K478R), C24989T(S:P1143S) 3seq

**Comment by FedeGueli** [comment]
> C9166T, A10564T

worth tracking it separately could you reopen the original issue and add this one please?
