### ISSUE TITLE
BA.2.86 Monitor:BA.2.86.1 with ORF1a:Y621C （A2127G）( 78 seqs）

### ISSUE THREAD

**Issue by Memorablea** [cov-lineages/pango-designation#2284]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/767

![image](https://github.com/cov-lineages/pango-designation/assets/125779492/dd550137-ba5d-4375-91ba-27b532d59833)

40 articles, accounting for 39% in BA. 2.86.1 and 25% in BA.2.86 (. 1)

**Comment by Memorablea** [comment]
45 NOW

**Comment by Memorablea** [comment]
53now

**Comment by Memorablea** [comment]
57

**Comment by Memorablea** [comment]
cc @corneliusroemer

**Comment by Memorablea** [comment]
78

**Comment by Memorablea** [comment]
#https://github.com/cov-lineages/pango-designation/commit/62ee71fda492d8305882f8a8611804094501d7f2

**Comment by JosetteSchoenma** [comment]
JN.2
