### ISSUE TITLE
XBB.1.16.12 (S:Q52H) with T5619C = Orf1a:T1785I and C14117T= Orf1b:T217M （112 Seq at 09-20)

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#2285]
Mutations on top of XBB.1.16.12: T5619C, C14117T
Gisaid Inquiry: T5619C,G21718T,C22995G
Sequences: 
EPI_ISL_17775025, EPI_ISL_17783018, EPI_ISL_17799024,
EPI_ISL_17799052, EPI_ISL_17799498, EPI_ISL_17821360,
EPI_ISL_17832561, EPI_ISL_17838810, EPI_ISL_17856224,
EPI_ISL_17856323, EPI_ISL_17865633, EPI_ISL_17871121,
EPI_ISL_17927679, EPI_ISL_17928065, EPI_ISL_17952666,
EPI_ISL_17954499, EPI_ISL_17954890, EPI_ISL_17959276,
EPI_ISL_17973206, EPI_ISL_17975435, EPI_ISL_17975523,
EPI_ISL_17978111, EPI_ISL_17979240, EPI_ISL_17980582,
EPI_ISL_17980591, EPI_ISL_17986827, EPI_ISL_17990541,
EPI_ISL_17996352, EPI_ISL_17998370, EPI_ISL_17998592,
EPI_ISL_18000380, EPI_ISL_18000478, EPI_ISL_18000552,
EPI_ISL_18005468, EPI_ISL_18005566, EPI_ISL_18008618,
EPI_ISL_18010949, EPI_ISL_18011095, EPI_ISL_18033008,
EPI_ISL_18045996, EPI_ISL_18047297, EPI_ISL_18051456,
EPI_ISL_18051677, EPI_ISL_18052894, EPI_ISL_18059025,
EPI_ISL_18059651, EPI_ISL_18062381, EPI_ISL_18071622,
EPI_ISL_18071640, EPI_ISL_18071746, EPI_ISL_18072248,
EPI_ISL_18079035, EPI_ISL_18081756, EPI_ISL_18081795-18081796,
EPI_ISL_18082344, EPI_ISL_18093677, EPI_ISL_18094320,
EPI_ISL_18104129, EPI_ISL_18104379, EPI_ISL_18112372,
EPI_ISL_18115246, EPI_ISL_18123148, EPI_ISL_18125215,
EPI_ISL_18126452, EPI_ISL_18127654, EPI_ISL_18129275,
EPI_ISL_18135065, EPI_ISL_18138438, EPI_ISL_18138491,
EPI_ISL_18138546, EPI_ISL_18140772, EPI_ISL_18140774,
EPI_ISL_18147529, EPI_ISL_18147535, EPI_ISL_18158032,
EPI_ISL_18160296, EPI_ISL_18162538, EPI_ISL_18163062,
EPI_ISL_18164981, EPI_ISL_18208019, EPI_ISL_18208042,
EPI_ISL_18208356, EPI_ISL_18208367, EPI_ISL_18216019,
EPI_ISL_18222420, EPI_ISL_18223014, EPI_ISL_18226202,
EPI_ISL_18227343, EPI_ISL_18233564, EPI_ISL_18235176,
EPI_ISL_18237177, EPI_ISL_18243024, EPI_ISL_18243221,
EPI_ISL_18246572, EPI_ISL_18247215, EPI_ISL_18247569,
EPI_ISL_18247634, EPI_ISL_18256822, EPI_ISL_18263650,
EPI_ISL_18264760, EPI_ISL_18266531, EPI_ISL_18267298,
Earliest: EPI_ISL_17832561 05-15 Thailand, 05-15
Latest:EPI_ISL_18247634 08-30 US, NY, 08-30
Usher:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ae25_62bcd0.json?f_userOrOld=uploaded%20sample&label=id:node_3045378
<img width="1067" alt="BC05D22C-E595-480E-AD83-7BA1108EBD66" src="https://github.com/cov-lineages/pango-designation/assets/131021067/93c8ad4b-ba23-4d11-8220-f654bacf6cc3">

Note: Not a lineage particularly fast or having interesting mutations from its parent, yet it has maintained a steady share and still spread around in multiple countries, and its overall numbers is not so small, so I propose it here.

**Comment by FedeGueli** [comment]
Moved here From https://github.com/sars-cov-2-variants/lineage-proposals/issues/358

**Comment by krosa1910** [comment]
Not competitive

**Comment by krosa1910** [comment]
This thing somehow persisted for a while, still it did not pass 2023 when the pressure of JN.1* becomes too large and clade 23B is on obvious decline even within XBB*s.

**Comment by FedeGueli** [comment]
Thanks
