### ISSUE TITLE
FE.1.1 with S:E554K (75 seqs, mainly in Brazil, 8 countries) further with S:S494P (10 seqs, Denmark, UK, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2288]
_Transferred from sars-cov-2-variants/lineage-proposals#556_

**Defining Mutations:** `FE.1.1` > `G23222A(S:E554K), A23233G`
**Query:** `A8001G, G23222A, A23233G`
**Earliest seq:** 2023-04-09 (`EPI_ISL_18043094`, Aracaju, Sergipe, Brazil)
**Latest seq:** 2023-09-01 (`EPI_ISL_18265392`, Cravinhos, São Paulo, Brazil)
**Sampled Countries:** Brazil (34), USA (7), Luxembourg (4), Mexico (2), France (1), Greece (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17710208, EPI_ISL_17734501-17734502, EPI_ISL_17771913, EPI_ISL_17792515, EPI_ISL_17813601, EPI_ISL_17814902, EPI_ISL_17832079, EPI_ISL_17960998, EPI_ISL_17961011, EPI_ISL_17975041, EPI_ISL_17975113, EPI_ISL_17990624, EPI_ISL_18022412, EPI_ISL_18043094, EPI_ISL_18054028, EPI_ISL_18058116, EPI_ISL_18058118-18058119, EPI_ISL_18058124, EPI_ISL_18058948, EPI_ISL_18067133, EPI_ISL_18069203, EPI_ISL_18090103, EPI_ISL_18090238, EPI_ISL_18095981, EPI_ISL_18095988, EPI_ISL_18096002, EPI_ISL_18096051, EPI_ISL_18096573, EPI_ISL_18107143, EPI_ISL_18113529, EPI_ISL_18113553, EPI_ISL_18131520, EPI_ISL_18150280, EPI_ISL_18150323, EPI_ISL_18164112, EPI_ISL_18208302, EPI_ISL_18208307, EPI_ISL_18216777, EPI_ISL_18216794, EPI_ISL_18223888, EPI_ISL_18229874, EPI_ISL_18239848, EPI_ISL_18253293, EPI_ISL_18253303, EPI_ISL_18253374, EPI_ISL_18265392, EPI_ISL_18268922`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42cef_83fcb0.json?label=id:node_7078344
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/6cb64fa2-08e3-4501-b094-4d367dcee71e)

**Trivia:**
- It still sits on a flip-flop _S:H505Y_reversion_ sub-branch of **FE.1** on UShER, it doesn't seems to be real though. The sequences causing this are `EPI_ISL_17651916, EPI_ISL_17821287`
- `A23233G` is `S:K557` silent mutation
- 7 seqs from USA collected as of 09/08 are from 7 different states, may also suggests that it could have some kind of prevalence in Brazil.

**Comment by AngieHinrichs** [comment]
> It still sits on a flip-flop S:H505Y_reversion sub-branch of FE.1 on UShER, it doesn't seems to be real though.

Ah thanks for pointing that out.  Added to the list of things to fix, hopefully better in a couple days.
