### ISSUE TITLE
Another XBB.2.3 and XBB.1.5 recombinant, with S:T732I (79 seqs, mainly in Guatemala, 8 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2289]
_Transferred from sars-cov-2-variants/lineage-proposals#711, it's a different recombinant to sars-cov-2-variants/lineage-proposals#604_

**Query:** `A13187G, C22388T, C23757T` (if considering potential `ORF1a:G2091S` dropout)
**Earliest seq:** 2023-06-30 (`EPI_ISL_18080753`, California, USA)
**Latest seq:** 2023-09-03 (`EPI_ISL_18258876`, Liège, Belgium)
**Sampled Countries:** Guatemala (21), USA (12, Many with foreign travel history), Spain (3), Belgium (6), Mexico (1), UK (1: England)

**Recombinant Profile:**
- Nearest Branch on Phylogenetic Tree: `XBB.2.3` > _T27431C_reversion(ORF7a:V13A_reversion)_ > _T29706G_reversion_ > `A13187G(ORF1a:I4308V/nsp10_I55V), C22388T, C23757T(S:T732I)` > `G6536A(ORF1a:G2091S)` > `G27915T(ORF8:G8*)`
- Donor A: XBB.2.3, upstream from 5' end to breakpoint
- Breakpoint: Between `nuc 23123/spike_521` to `nuc 27431/ORF7a_13`
- Donor B: Any XBB.1* with `ORF8:G8*` and without `ORF9:I5T`, most likely XBB.1.5, downsteram from breakpoint to 3' end.
- Private mutations: `ORF1a:I4308V`, `C22388T`, `S:T732I`
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/61640571-5cbc-41d8-ae56-03deee31489f)

<details><summary>Genomes: </summary>

`EPI_ISL_17954534, EPI_ISL_17954569, EPI_ISL_17982568, EPI_ISL_17982581, EPI_ISL_17982586, EPI_ISL_18011156, EPI_ISL_18023025, EPI_ISL_18037651, EPI_ISL_18080753, EPI_ISL_18081441, EPI_ISL_18090453, EPI_ISL_18094954, EPI_ISL_18099400, EPI_ISL_18099404, EPI_ISL_18099406, EPI_ISL_18099415, EPI_ISL_18099422, EPI_ISL_18099424, EPI_ISL_18099433, EPI_ISL_18104413, EPI_ISL_18118410, EPI_ISL_18136401, EPI_ISL_18137317, EPI_ISL_18138518, EPI_ISL_18139698, EPI_ISL_18139701, EPI_ISL_18139731, EPI_ISL_18139754, EPI_ISL_18139756, EPI_ISL_18144338, EPI_ISL_18163511, EPI_ISL_18163519, EPI_ISL_18163522, EPI_ISL_18163581, EPI_ISL_18168281-18168282, EPI_ISL_18227406, EPI_ISL_18234086, EPI_ISL_18243314, EPI_ISL_18252808, EPI_ISL_18258869, EPI_ISL_18258871, EPI_ISL_18258876, EPI_ISL_18260691`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9fd0_844560.json?label=id:node_7422389
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/5430ad5c-b220-4ae3-bff1-3f4f0f09f03f)

**Comment by JosetteSchoenma** [comment]
I am putting XCQ here, to see if that would help with searching GItHub for it.

And maybe the designated name could be put in the title as well? I think that will make searching for things a lot easier.

**Comment by JosetteSchoenma** [comment]
Yes, it helps! Now I can find it with searching for 'XCQ', while before my comment, it wasn't found.
