### ISSUE TITLE
Delta sublineage with S:222V and S:250S (mostly in South Africa)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#229]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: B.1.617 (sister lineage of #228 as it shares a synonymous mutation C2509T)
Earliest sequence: US 2021-12 (just 1 single sequence), then South Africa 2021-19 where it reached 15-20% relative overall share
Most recent sequence: Current
Countries circulating: Mostly South Africa, but also around the world

Significant mutations (amongst others): ORF1b:765C, s:250S
Country | Total Variant Sequences | First seq. found at | Last seq. found at |  
-- | -- | -- | -- | --
Australia | 15 | 2021-25 | 2021-29 |  
Austria | 1 | 2021-23 | 2021-23 |  
Belgium | 3 | 2021-24 | 2021-34 |  
Brazil | 3 | 2021-31 | 2021-31 |  
Canada | 4 | 2021-22 | 2021-27 |  
Croatia | 3 | 2021-25 | 2021-25 |  
Denmark | 4 | 2021-27 | 2021-33 |  
Eswatini | 7 | 2021-25 | 2021-27 |  
Finland | 2 | 2021-31 | 2021-31 |  
France | 8 | 2021-25 | 2021-29 |  
Germany | 40 | 2021-22 | 2021-37 |  
Greece | 12 | 2021-29 | 2021-32 |  
Ireland | 3 | 2021-29 | 2021-32 |  
Israel | 1 | 2021-31 | 2021-31 |  
Italy | 6 | 2021-27 | 2021-32 |  
Japan | 1 | 2021-31 | 2021-31 |  
Luxembourg | 3 | 2021-25 | 2021-27 |  
Mauritius | 1 | 2021-24 | 2021-24 |  
Netherlands | 11 | 2021-23 | 2021-26 |  
New Zealand | 1 | 2021-28 | 2021-28 |  
Norway | 2 | 2021-32 | 2021-33 |  
Poland | 1 | 2021-35 | 2021-35 |  
South Africa | 738 | 2021-19 | 2021-35 |  
South Korea | 1 | 2021-26 | 2021-26 |  
Spain | 2 | 2021-25 | 2021-31 |  
Sweden | 146 | 2021-24 | 2021-36 |  
Switzerland | 4 | 2021-25 | 2021-33 |  
United Kingdom | 18 | 2021-20 | 2021-35 |  
United States | 38 | 2021-12 | 2021-35 |  
Zimbabwe | 1 | 2021-27 | 2021-27

![image](https://user-images.githubusercontent.com/25161793/134783802-52a21593-2b4b-4b5a-965a-e8e04702d82a.png)
https://cov-spectrum.ethz.ch/explore/South%20Africa/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22s%3A250s%22%2C%22s%3A222v%22%2C%22orf1b%3A765c%22]%7D%2C%22matchPercentage%22%3A1%7D

Genomes (~ 1000)
[sa.txt](https://github.com/cov-lineages/pango-designation/files/7230252/sa.txt)

Evidence
![image](https://user-images.githubusercontent.com/25161793/134783827-150e32fc-a5f6-4077-b31e-4033abd6e7b4.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_5835b_f70100.json?c=country&label=nuc%20mutations:C2509T,G15760T,A22310T,G29212T,T29742G

Proposed lineage name
AY.x

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as lineage AY.38 in [v1.2.80](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.80) with 924 sequence designations. We've started the lineage on a branch with C2509T (synonymous) which seems to coincide with the introduction(s) into South Africa. S:T250S therefore occurs several branches downstream of where we've started AY.38

**Comment by ryhisner** [comment]
I just noticed that this lineage has a very large s2m deletion: ∆29717-29772. At 56 nucleotides, that makes it more than twice as large as the 26-nucleotide BA.2/4/5 s2m deletion of ∆29734-29759. I'm not aware of any other Delta lineages that have an s2m deletion, though I haven't done an exhaustive search or anything. 

Also interesting: about 10% of AY.38 have ORF9b:I5T.

**Comment by FedeGueli** [comment]
> I just noticed that this lineage has a very large s2m deletion: ∆29717-29772. At 56 nucleotides, that makes it more than twice as large as the 26-nucleotide BA.2/4/5 s2m deletion of ∆29734-29759. I'm not aware of any other Delta lineages that have an s2m deletion, though I haven't done an exhaustive search or anything.
> 
> Also interesting: about 10% of AY.38 have ORF9b:I5T.

Thx Ryan!!
