### ISSUE TITLE
FL.40 with ORF1a:L3116F (nsp4_L353F), ORF1b:T577A (nsp12_T586A), S:T19L and S:T478R (28 seqs, 5 countries, many with foreign travel history)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2292]
_Transferred from sars-cov-2-variants/lineage-proposals#377_

**Defining Mutations:** **FL.40** > `C1912T, C9611T(ORF1a:L3116F), A15196G(ORF1b:T577A), A21617C(S:T19L), C22995G(S:T478R)`
**Query:** `A15196G, A21617C, C22995G`
**Earliest seq:** 2023-04-17 (`EPI_ISL_17818160`, Yamalo-Nenets, Russia)
**Latest seq:** 2023-08-24 (`EPI_ISL_17879194`, `SEA` airport, Washington, USA, travel history: Türkiye)
**Sampled Countries:** Russia (14), USA (5, all travel-related), China (1, travel-related), Canada (1: NS), Japan (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17618334, EPI_ISL_17634778, EPI_ISL_17716496, EPI_ISL_17818160, EPI_ISL_17818250, EPI_ISL_17818340, EPI_ISL_17831501, EPI_ISL_17831512, EPI_ISL_17831518, EPI_ISL_17831521, EPI_ISL_17831537, EPI_ISL_17879194, EPI_ISL_18007282, EPI_ISL_18023420, EPI_ISL_18110991, EPI_ISL_18111023-18111024, EPI_ISL_18147044, EPI_ISL_18222100, EPI_ISL_18222102, EPI_ISL_18222143, EPI_ISL_18239127`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21b67_84dd60.json?f_userOrOld=uploaded%20sample&label=id:node_6955020

view from XBB.1.9.1 polytomy with filter of codon 19, 478 of S gene
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/f6065f5c-b52e-4486-afda-fb5a00e8f6a2)

details
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/197afd51-4de6-40f8-86c7-c2177a9b2dd2)

**Trivia:**
- Most seqs from parent `ORF1a:I3758V` branch comes from Russia, [with 5-24% local prevalence](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AI3758V&nextcladePangoLineage=XBB.1.9.1*), but too few (and maybe a little bit delayed) seqs to confirm this.
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/1aa92470-45d4-41f6-989a-8804cb3b2d79)
- Many sequences are travel related, from multiple undersample areas.

**Comment by FedeGueli** [comment]
parental lineage starting with Orf1a:I3758V designated FL.40
