### ISSUE TITLE
FL.15(S:456L)+Orf1a:G400V,S2185N,T2007I, S:L455F (44 seqs, 9 countries, 24 with S:A475V)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2293]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/646
FL.15+G1464T(Orf1a:G400V)+C12890T+G6819A(Orf1a:S2185N)+A15456G, C6285T,G22927T(Orf1a:T2007I, S:L455F)

GISAID query: C6285T,G6819A,G22927T
No. of seqs: 27(Belgium 2 Canada 10 Romania 7 Japan 4 France 2 Italy 1 Germany 1)
The query can find 26, plus EPI_ISL_18213167 with missing coverage

GISAID query for S:A475V subbranch: C6285T,G6819A,G22927T,C22986T
No. of seqs: 18

First: EPI_ISL_18097851, Japan, 2023-6-30
Latest: EPI_ISL_18287942, Canada, 2023-9-14

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/fl_15_l455f.json?label=id:node_7014910)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/99c9b4ab-f98c-4fad-b6dd-e8c18481db26)

**Comment by FedeGueli** [comment]
32 with 455F and 
24 with 455F +S:A475V now ( with sequences uploaded today from Spain, England, Romania and Australia)

ping @corneliusroemer this seems really fast i suggest a rapid designation of the whole FL.15 thing

**Comment by aviczhl2** [comment]
44, Spain, Australia
