### ISSUE TITLE
XBB.1.16.15 (S:K147N, P521S) Sublineage with ORF9b:P3L, ORF1a:S2024L, ORF1b:N2328S (94 seq, 25 countries, Sept 23)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2294]
**Description** — transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/695
**Sub-lineage of:** XBB.1.16.15 (XBB.1.16 + S:K147N, S:P521S)
**Earliest sequence:** 2023-7-10, Shanghai, China — EPI_ISL_18074327
**Most recent sequence:** 2023-8-21, Spain, Basque Country — EPI_ISL_18134790
**Countries circulating:** England (3), Sweden (3), Denmark (2), Spain (2), USA (2), China (1), France (1—traveler to USA), Germany (1), Israel (1), Netherlands (1)
**Number of Sequences:** 17
**GISAID AA Query:** NSP3_S1206L, NSP15_N277S, -Spike_D138H, -Spike_ins925FRYAM
**GISAID Nucleotide Query:** C6336T, T10756C, T14067C, C28291T
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.16* & C6336T & [2-of: A20450G, A24121G, C28291T]
**Substitutions on top of XBB.1.16.15:**
**ORF9b:** P3L
**ORF1a:** S2024L
**ORF1b:** N2328S
**Nucleotide:** C6336T, T10756C, A20450G, A24121G, C28291T   
 
**Phylogenetic Order of Mutations:**  T10756C   **→**   C28291T (ORF9b:P3L)   **→**   A20450G, A24121G (ORF1b:N2823S)   **→**  C6336T (ORF1a:S2024L)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.16.15_9bP3L_1aS2024L_1bN2328S.json?c=gt-nuc_6336&label=id:node_6826659 
<img width="1384" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/ef67c555-dde4-4fe5-a80c-66cb8996918f">
.

.
**Evidence**
ORF1a:S2024L/NSP3_S1206L is modestly convergent in chronic-infection sequences. C28291T (ORF9b:P3L) slightly increases the extended homology for what I believe is a suboptimal ORF9b TRS. It has very gradually increased in prevalence during the XBB era and might be slightly advantageous. 

ORF1b:N2328S/NSP15_N277S is an uncommon mutation. NSP15 seems to be a pretty conserved part of the genome in general, and this mutation has been in <800 sequences in the entire pandemic. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18074327, EPI_ISL_18095053, EPI_ISL_18097303, EPI_ISL_18099903, EPI_ISL_18099909, EPI_ISL_18099941, EPI_ISL_18112044, EPI_ISL_18112170, EPI_ISL_18115821, EPI_ISL_18123736, EPI_ISL_18124221, EPI_ISL_18126764, EPI_ISL_18126765, EPI_ISL_18130459, EPI_ISL_18130705, EPI_ISL_18134790, EPI_ISL_18135290
</details>

**Comment by DailyCovidCases** [comment]
Please close this issue
