### ISSUE TITLE
XBB.1.16.15 has two aliases.

### ISSUE THREAD

**Issue by Kevin050308** [cov-lineages/pango-designation#2295]
![image](https://github.com/cov-lineages/pango-designation/assets/121531357/9b967be2-de92-40d9-9695-b925b2b6bfc6)

**Comment by corneliusroemer** [comment]
Good spot! I (or someone who wants to help) should write tests that I can run with pre-commit to prevent these silly errors from me ending up on the main branch 🙃

**Comment by corneliusroemer** [comment]
Ok, set up better tests for alias_key.json, see .pre-commit-config.yaml
