### ISSUE TITLE
EG.5.1 with S:K182Q, S:T478R, ORF3a:Y91C, ORF1a:L450F, ORF1b:G2510C and S:L455F via G22927C (9 seqs, 8 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2296]
_Taken from **Branch 44** of multitask sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** `EG.5.1` > `A22106C(S:K182Q)` > `C22995G(S:T478R), A25664G(ORF3a:Y91C)` > `C1613T(ORF1a:L450F), G20995T(ORF1b:G2510C), G22927C(S:L455F), A27388C`
**Query:** `A22106C, G22927C, C22995G`
**Earliest seq:** 2023-08-14 (`EPI_ISL_18160020`, Denmark, _OR_ `EPI_ISL_18278998`, Singapore)
**Latest seq:** 2023-09-13 (`EPI_ISL_18295307`, `SFO` airport, California, USA with travel history to: Japan)
**Sampled Countries:** Denmark (2), France (1), Singapore (1), USA (1, ex. Japan)

<details><summary>Genomes: </summary>

`EPI_ISL_18160020, EPI_ISL_18243476, EPI_ISL_18278998, EPI_ISL_18295307, EPI_ISL_18314088`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_ec32_42b9b0.json?label=id:node_6951991
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/ce098d91-f8a4-49e6-8d3c-83eaac4d4f19)

**Trivia:**
- Another `S:L455F` via `G22927C`, branching from a seemingly hiatus `S:T478R` sublineage from Indonesia, where doesn't have much sequences available since June.
- `A27388C` is ORF7a TRS related.

**Comment by FedeGueli** [comment]
Ping @corneliusroemer  i suggest a close monitor of this one:
1) The tree roots could suggest it emerged in Indonesia ( we have only 4 travellers sample for Indonesia = 200M  for september) 
2) the mutational profile combines FLip to 478R and with 182 residue mutated to Q that is N in XBB.2.3.3 and it is associated usually to fit lineages.
3) 5 samples 4 countries considering that French sample in a young woman the danish is recent two from Singapore with two different age and the one intercepted in Us airports is in a traveller coming from Japan.

**Comment by FedeGueli** [comment]
7 Spain (new country)

**Comment by FedeGueli** [comment]
8 Austria new country

**Comment by ryhisner** [comment]
Worth noting that the A27388C in this branch spoils the ORF7a/ORF7b TRS. There's probably almost no ORF7a or ORF7b expression in this lineage. 
<img width="1341" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/f60ffaae-588d-4387-a00f-2f24cefdb32b">

**Comment by FedeGueli** [comment]
i would add Or7ab expression ablated in the headline

**Comment by FedeGueli** [comment]
This is now a sublineage of JR.1 (EG.5.1.11.1)

**Comment by FedeGueli** [comment]
Sorry already designated JR.1.1 via https://github.com/cov-lineages/pango-designation/commit/bd9a2f7e2cc8baf43ae8317b9105c62673cacd63
