### ISSUE TITLE
JG.3+Orf1a:S2556L,Orf3a:L140F,S:T307I(113 seqs, 15 countries )

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2297]
This lineage grows from 14 to 53 in 10 days, but it is well expected as an even faster sub-branch of the current fastest lineage JG.3. 

From https://github.com/sars-cov-2-variants/lineage-proposals/issues/829

JG.3+C7932T,C25810T(Orf1a:S2556L,Orf3a:L140F)+S:T307I(C22482T)

GISAID query: C7932T,C25810T,C22482T
No. of seqs: 53(Austria 1 Canada 1 Denmark 17 UK 20 Germany 6 Greece 1 Romania 1 Sweden 1 USA 5)

First: EPI_ISL_18210634, Denmark, 2023-8-21
Latest: EPI_ISL_18315322, UK, 2023-9-19

There is also another EG.5.1+Flip+307 branch, #2310, T307I is quite convergent.

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jg3_t307i.json?f_userOrOld=uploaded%20sample&label=id:node_6985183)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/70aa5f29-71ef-4788-8b23-558165486516)

**Comment by FedeGueli** [comment]
Doubling for submission date around 7 days , even if not all the CIs show a clear growth advantage over the parental  for sure it is not slow and still interesting with a RBD mutation. cc @corneliusroemer

**Comment by aviczhl2** [comment]
+1 Italy

**Comment by aviczhl2** [comment]
81, Norway, Finland

**Comment by FedeGueli** [comment]
CLear advantage over HK.3
![Schermata 2023-10-06 alle 06 24 05](https://github.com/cov-lineages/pango-designation/assets/87669813/a7b5b0ed-33da-4ff7-8036-35a3d48168ce)
Still to see if clearly  advantageous over JG.3, it looks like yes but lower CI is negtive.
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nucMutations=G22927T%2CC23673T%2CC1889T&nucMutations1=C7932T%2CC25810T%2CC22482T&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
101, France,Iceland,Israel

**Comment by aviczhl2** [comment]
Designated JG.3.1
