### ISSUE TITLE
New lineage proposal for B.1.111 with Spike substitutions E484K and L249S

### ISSUE THREAD

**Issue by juciro** [cov-lineages/pango-designation#23]
by Katherine Laiton-Donato, Jose A. Usme-Ciro, Carlos Franco-Muñoz, Diego A. Álvarez-Díaz, Hector Alejandro Ruiz-Moreno, Jhonnatan Reales-González, Diego Andrés Prada, Sheryll Corchuelo, Maria T. Herrera-Sepúlveda, Julian Naizaque, Gerardo Santamaría, Magdalena Wiesner, Diana Marcela Walteros, Martha Lucia Ospina Martínez, Marcela Mercado-Reyes.

Description
Sub-lineage of: B.1.111
Earliest sequence: 2020-12-26 (hCoV-19/Colombia/CES-INS-VG-248/2020)
Most recent sequence: 2021-02-17 (hCoV-19/USA/NY-NYCPHL-003387/2021)
Countries circulating: Colombia (4), USA (10), Belgium (1), Aruba (2).
Four Colombian sequences collected between December 26, 2020 and January 14, 2021, were assigned to the B.1.111 lineage by Pangolin COVID-19 Lineage Assigner (https://pangolin.cog-uk.io/), however, these sequences share a characteristic mutation pattern, including two amino acid changes in the Spike protein (E484K and L249S). B.1.111+484K/249S sequences have been obtained from SARS-CoV-2 recently circulating in Colombia, USA, Belgium and Aruba. The preliminary results are consistent with the emergence of a novel and phylogenetically distant lineage from the parental B.1.111 lineage (Figure 1).
List of characteristic amino acid changes of the new lineage:
[List of characteristic amino acid changes of new lineage.txt](https://github.com/cov-lineages/pango-designation/files/6070735/List.of.characteristic.amino.acid.changes.of.new.lineage.txt)

Genomes
List of genomes, collated 2021-03-02, attached.
[Genome sequences list.txt](https://github.com/cov-lineages/pango-designation/files/6070737/Genome.sequences.list.txt)

Evidence
![Phylogeny for proposal](https://user-images.githubusercontent.com/34484729/109692715-d5d76880-7b56-11eb-92ae-67b67896a40a.png)
The full phylogenetic tree can be accessed through this link: https://microreact.org/project/fTa6f3kY9JraG9NPmQYGog/42c3e045 

Proposed lineage name
To be designated.

**Comment by juciro** [comment]
A detailed description of the proposed lineage can be found in the following link:
https://www.medrxiv.org/content/10.1101/2021.03.12.21253000v1

**Comment by juciro** [comment]
@rambaut @aineniamh could you please check if the available evidence and genetic distance is enough to be considered a new lineage? We emphasize the presence of two Spike substitutions, however, the lineage contains 21 substitution (including 10 nonsynonymous substitutions) in the whole genome. The high genetic distance from the more closely related sequences is enigmatic  as it has happened with several VOI and VOC. Thanks in advance!

**Comment by ha-ruiz75** [comment]
I would like to follow up on this and update with GISAID sequences found up to 2021-04-22.

### Description
Sub-lineage of: **B.1**
Earliest sequence: **2020-12-17** (hCoV-19/Colombia/SUC-INS-VG-1153/2020|EPI_ISL_1220065)
Most recent sequence: **2021-04-03** (hCoV-19/Spain/MD-HGUGM-21153075/2021|EPI_ISL_1511206)
Countries circulating: USA (39), Colombia (15), Curazao (2), Aruba (2), Belgium (1), Spain (1); (GISAID sequences)

The first sequence came from a sample collected on December 17, 2020. It was assigned to the B.1 lineage and presents amino acid substitutions in the Spike protein region (E484K, L249S). S:L249S seems to be characteristic to this lineage, among other amino acid substitutions. 

This mutation profile was first detected in sequences from the northwest of Colombia. Spread of this lineage has evidenced to other regions of the Country. There is a rise in the number of sequences from USA with this mutation profile starting in early February. Latest sequences are from USA, Colombia and Spain.

Sequences used to be assigned to the B.1.111 lineage. After a pangolin update, sequences many sequences were reassigned to B.1 lineage. Phylogenetic analysis suggest B.1 is the parental lineage.

### Genomes
List of genomes, collected 2021-04-22, attached.
[list.txt](https://github.com/cov-lineages/pango-designation/files/6386967/list.txt)

### Evidence
The full phylogenetic tree can be accessed through this link: [proposed lineage B.1.X](https://microreact.org/project/f1uCyyAKGPXSioYu8MiXiS/798a7339)

![árbol_vert](https://user-images.githubusercontent.com/34463016/116297862-5b475580-a761-11eb-897b-fe8ad158ea52.png)


### Proposed lineage name
Next available designation within parent B.1 lineage (B.1.X)

**Comment by chrisruis** [comment]
This issue has gone stale so we'll close it for now. If this would still be a useful lineage designation, please reopen this. Thanks
