### ISSUE TITLE
Suggestion: Enable Github discussion feature for this repo

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#230]
It seems like what @LilKitt would like is for the Github discussion feature to be enabled on the repo? See here for details on how to do this: https://docs.github.com/en/discussions

> Is there section on this site or someplace else to discuss findings with others?

_Originally posted by @LilKitt in https://github.com/cov-lineages/pango-designation/issues/227#issuecomment-927946188_

**Comment by LilKitt** [comment]
Is this something that already exists? I am new here and just trying to familiarize myself with the setup. I think it would be interesting to be able to discuss findings and research with others.
