### ISSUE TITLE
HH.2 (XBB.2.3.2.2) with S:T478R (63 seqs, mainly in France, 8 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2300]
_Taken from Branch 10 of multitask sars-cov-2-variants/lineage-proposals#236_

**Defining Mutations:** `HH.2` > `C21077T(ORF1b:T2537I)` > `G9973A` > `C10296T(ORF1a:S3344F)` > `C22995G(S:T478R)`
**Query:** `G9973A, C10296T, C22995G, -T316C`
**Earliest seq:** 2023-07-13 (`EPI_ISL_18070067`, France)
**Latest seq:** 2023-09-13 (`EPI_ISL_18301610`, England, UK)
**Sampled Countries:** France (19: Mainland/17; Martinique/2), US (9: EN/8; SC/1), USA (4: CA/3; NY/1), Spain (3), Belgium (2), China (1, Shanghai), Singapore (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18070067, EPI_ISL_18070136, EPI_ISL_18119099, EPI_ISL_18123355, EPI_ISL_18135038, EPI_ISL_18141126, EPI_ISL_18167749, EPI_ISL_18208440, EPI_ISL_18215186, EPI_ISL_18216045, EPI_ISL_18216981, EPI_ISL_18220087, EPI_ISL_18220093, EPI_ISL_18229069, EPI_ISL_18229512, EPI_ISL_18229514, EPI_ISL_18239672, EPI_ISL_18244651, EPI_ISL_18244654, EPI_ISL_18257956, EPI_ISL_18258865, EPI_ISL_18265648, EPI_ISL_18269529-18269530, EPI_ISL_18270093, EPI_ISL_18273269-18273270, EPI_ISL_18273547, EPI_ISL_18274125, EPI_ISL_18275013, EPI_ISL_18280028, EPI_ISL_18280597, EPI_ISL_18280750, EPI_ISL_18287776, EPI_ISL_18287786-18287787, EPI_ISL_18293824, EPI_ISL_18295885, EPI_ISL_18301610`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_16df1_6abac0.json?label=id:node_7327768
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/78793d5c-5c49-4549-8cba-9daa12923f8d)

**Comment by FedeGueli** [comment]
Still clearly behind HK.3 : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G9973A%2CC10296T%2CC22995G%2C316T&analysisMode=CompareToBaseline&
