### ISSUE TITLE
GK.1 sublineage with ORF3a:V50I (>160 seq in 19 countries. Maybe originated in Colombia) and a further sublineage with ORF1a:I114V and S:A475V (18 seq. Spain, Colombia, USA, Germany, Israel, Australia, Italy, Canada)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#2304]
Defining mutations:
GK.1 then nuc:C853T+ORF3a:V50I(G25540A)
![1](https://github.com/cov-lineages/pango-designation/assets/115189228/547515d9-833c-432a-9d79-f8b0f5c98b1d)
![2](https://github.com/cov-lineages/pango-designation/assets/115189228/c1423c60-f6a0-4450-a0e8-52e169938239)
![3](https://github.com/cov-lineages/pango-designation/assets/115189228/1caf0594-aff0-4fa8-a003-989cec0c5f37)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_13bdd_8bc040.json?c=gt-S_475&gmax=25384&gmin=21563&label=id:node_3914667
![5](https://github.com/cov-lineages/pango-designation/assets/115189228/9f71d8a0-f955-4a72-80ec-dfbf687aa98e)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AGK.1*%26ORF3a%3AV50I&
The first sequence of this sublineage is from Colombia. (Up till now, it hasn't shown up in Brazil yet.) Colombia does not upload many sequences. However, considering how widespread this lineage is, it likely did well somewhere (maybe in Colombia or nearby countries).

**Comment by FedeGueli** [comment]
former cluster 9 in https://github.com/sars-cov-2-variants/lineage-proposals/issues/643

**Comment by FedeGueli** [comment]
Gisaid query: A605G,C22986T finds 11 samples

**Comment by FedeGueli** [comment]
14 now
