### ISSUE TITLE
New Recombinant of GK.1/XBB.1.16(25 seqs, 4 countries, 9% in Sweden) (Flip+704+Orf9b:5,55, 15 with S:747I, 5 with S:689I)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2311]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/824

XBB.1.5.70+
C12253A, C17010T,C23673T(S:S704L), G25045A(rev), T27059C(rev),A27669G,T28005C(Orf8:38 rev),T28297C(Orf9b:5),A28447G(Orf9b:55), A29221G,T29386C

C23673T from GK.1
C12253A, C17010T from an American GK.1 branch
G25045A(rev), T27059C(rev),A27669G,T28005C(Orf8:38 rev),T28297C(Orf9b:5),A28447G(Orf9b:55), A29221G,T29386C from an American XBB.1.16 branch

GK.1--XBB.1.16
Breakpoint between 23674 and 25044

GISAID query: C12253A,A27669G,A29221G

No. of seqs: 24 (USA 3 Sweden 20 Italy 1)

First: EPI_ISL_18270019, USA, 2023-7-31
Latest: EPI_ISL_18360151, Sweden, 2023-10-3

12/137 in the most recent Swedish 10-06 batch, 9% prevalence

It has already gotten some further spike diversity. 5 seqs have additional S:689I, 15 with S:747I

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/gk_1_xbb_1_16_recomb.json?f_userOrOld=uploaded%20sample&label=id:node_4264874)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/e9b19f12-40c3-4507-be18-4c377f2d7c47)

XBB.1.16-side donor
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/2d0b7004-f46f-4dea-b56f-9e3fc739e429)

GK.1-side donor
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/cf0c3461-c86e-4d87-9029-08751e9e7184)

**Comment by AngieHinrichs** [comment]
Added IDs from tree, thanks.

**Comment by aviczhl2** [comment]
+1 Austria

**Comment by JosetteSchoenma** [comment]
XCS
