### ISSUE TITLE
XCH + ORF3a:T175K + N:P6T +ORF9b:D2E (129)

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2312]
transferred from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/868
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/8f5d1b41-f50f-48fa-a66b-87c0f5f01cb8)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_19f9_1cbba0.json?c=gt-N_6&label=id:node_3684489
Gisaid Query: C28289A, A16923C

**Comment by FedeGueli** [comment]
ping @corneliusroemer it reached quite fastly 99 seqs. still mainly NYC

**Comment by FedeGueli** [comment]
Slowed down a lot i suggest closing this one
