### ISSUE TITLE
GK.1 sublineage with ORF1a:L16F, ORF1a:G2207S, ORF1a:S2214L, S:A475V, and S:E554K (20 seq. Luxembourg, Brazil, France, Chile, USA, UK)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#2313]
Defining mutations:
GK.1 then ORF1a:L16F(C311T)+nuc:A5608G+ORF1a:G2207S(G6884A)+ORF1a:S2214L(C6906T)+nuc:C18120T+S:A475V(C22986T)+S:E554K(G23222A)+nuc:T25370C
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXBB.1.5.70.1*%26S%3AE554K%26ORF1a%3AG2207S&
![1](https://github.com/cov-lineages/pango-designation/assets/115189228/7ad596a9-5982-4fe3-9522-a727eaf8b6c8)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2695b_1dd730.json?f_userOrOld=uploaded%20sample&label=id:node_3687353
![2](https://github.com/cov-lineages/pango-designation/assets/115189228/30f547ad-e349-4a67-9735-ba4ddec7e4bc)
3 of 17 sequences (2 from Luxembourg and 1 from Brazil) lack coverage at S:475. They likely have S:A475V too.

**Comment by FedeGueli** [comment]
Query: A5608G,G6884A,C22986T finds 15
