### ISSUE TITLE
GK.1.2 (or GK.1+S:N185D) sublineage with ORF1a:D147G, ORF1a:D2592Y, ORF1a:T4175I, ORF1b:N1426K, S:A475V (11 seq. Brazil, Germany, USA, Colombia)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#2314]
Defining mutations:
GK.1 then S:N185D(A22115G) then ORF1a:D147G(A705G)+nuc:C4586T+ORF1a:D2592Y(G8039T)+ORF1a:T4175I(C12789T)+nuc:C17718T+ORF1b:N1426K(C17745A)+nuc:C18693A+nuc:T21802C+S:A475V(C22986T)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXBB.1.5.70.1*%26ORF1b%3AN1426K&
They have S:N185D but they don't have nuc:T16974C like most GK.1.2s.
![1](https://github.com/cov-lineages/pango-designation/assets/115189228/76edf2c6-c22e-4c90-8654-ce80f46a2ad8)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f665_1e7b40.json?c=gt-nuc_705&gmax=1070&label=id:node_3686643

**Comment by FedeGueli** [comment]
Query :  A22115G, C17745A, ,C22986T 
there are three more from Colombia
![Schermata 2023-10-08 alle 11 26 25](https://github.com/cov-lineages/pango-designation/assets/87669813/63498854-c3a5-4082-b318-67399d9c4970)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_10f38_2752b0.json?label=id:node_3694389

@oobb45729 it cant be GK.1.2 cause GK.1.2 is a recombinant sublinegae between XBB.1.5 and XBB.1.5.70 described here and its defining inherited by XBB.1.5 donor is T16974C.

So this is a plain GK.1 with S:N185D 

cc @corneliusroemer @AngieHinrichs could you confirm?
Short synthesis:
GK.1.2 was a recombinant between XBB.1.5 donor with 185S and T16974C and XBB.1.5.70.
here we have a GK.1 sublineage that Usher places as sibling of GK.1.2 but lacking the T16794C defining mutation inherited by the XBB.1.5 donor i think it is just convergence.

**Comment by FedeGueli** [comment]
Query: A5608G,G6884A,C22986T finds 15

**Comment by oobb45729** [comment]
I'm not so sure.
This is the map of GK.1.2* (with T16974C) detected in Brazil
![1](https://github.com/cov-lineages/pango-designation/assets/115189228/8ceed581-acc1-4ad9-86f6-8025c114b5e6)
https://cov-spectrum.org/explore/Brazil/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXBB.1.5.70.1.2*%26T16974C&
This is the map of GK.1*+S:N185D (without T16974C) detected in Brazil
![2](https://github.com/cov-lineages/pango-designation/assets/115189228/87374a04-e37f-4659-80a7-3b9e23a75d7b)
https://cov-spectrum.org/explore/Brazil/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXBB.1.5.70.1*%26S%3AN185D%26%21T16974C&
They are similar.

**Comment by FedeGueli** [comment]
> I'm not so sure. This is the map of GK.1.2* (with T16974C) detected in Brazil ![1](https://user-images.githubusercontent.com/115189228/273474306-8ceed581-acc1-4ad9-86f6-8025c114b5e6.png) https://cov-spectrum.org/explore/Brazil/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXBB.1.5.70.1.2*%26T16974C& This is the map of GK.1*+S:N185D (without T16974C) detected in Brazil ![2](https://user-images.githubusercontent.com/115189228/273474371-87374a04-e37f-4659-80a7-3b9e23a75d7b.png) https://cov-spectrum.org/explore/Brazil/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXBB.1.5.70.1*%26S%3AN185D%26%21T16974C& They are similar.

maybe a recombinant itself?  T16974C defining of gk.1.2  is inherited from the XBB.1.5 donor if reverted i can explain it only with recombination

**Comment by corneliusroemer** [comment]
>@oobb45729 it cant be GK.1.2 cause GK.1.2 is a recombinant sublinegae between XBB.1.5 and XBB.1.5.70 described here and its defining inherited by XBB.1.5 donor is T16974C.
Some more evidence for your claim would be nice @FedeGueli. Is this something that was discussed elsewhere?

**Comment by FedeGueli** [comment]
> > @oobb45729 it cant be GK.1.2 cause GK.1.2 is a recombinant sublinegae between XBB.1.5 and XBB.1.5.70 described here and its defining inherited by XBB.1.5 donor is T16974C.
> > Some more evidence for your claim of GK.1.2 being recombinant would be nice @FedeGueli. Is this something that was discussed elsewhere?
> 
> You claim that presence of nuc:T16974C means GK.1.2 is recombinant? A single not widespread nuc is a bit scant evidence.
> 
> S:N185D could well be homoplasy here - hard to know for sure.

it was in the original issue , not proposed by me , https://github.com/sars-cov-2-variants/lineage-proposals/issues/396

**Comment by corneliusroemer** [comment]
Thanks, that's too weak evidence in my view

**Comment by corneliusroemer** [comment]
No reason GK.1.2 would require nuc:T16974C - it's better to make 185D alone defining (that's also what lineage notes say)

So this is GK.1.2.1

**Comment by FedeGueli** [comment]
Thx for looking it. agree it could not be 100% true or false so well going this way
