### ISSUE TITLE
GK.1 sublineage with ORF1a:P309L and S:A475V (60 seq. Brazil, USA, Canada, Italy, Spain, Peru)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#2315]
Defining mutations:
GK.1 then nuc:T3766C then nuc:A25725G then ORF1a:P309L(C1191T)+S:A475V(C22986T)
![1](https://github.com/cov-lineages/pango-designation/assets/115189228/6440af04-d4e1-4104-9728-0a8c151d7ec1)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20126_1f5020.json?label=id:node_3684441
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AGK.1*%26ORF1a%3AP309L%26S%3AA475V&

**Comment by FedeGueli** [comment]
Query : T3766C,A25725G,C1191T

**Comment by FedeGueli** [comment]
27. This seesm expanding in Brazi i suggest to designate it.

**Comment by FedeGueli** [comment]
45 now, tough its share in Espiritu Santu,Brazil is likely around 10% more than 20% previously estimeated by me.

**Comment by aviczhl2** [comment]
Designated GK.1.11

**Comment by FedeGueli** [comment]
via https://github.com/cov-lineages/pango-designation/commit/9ff2ee0a41823fd6fbfe8a579e95b979942b2cbe
