### ISSUE TITLE
HV.1 + ORF1a:T4083M (issue #2228) with S:K444T (19 seqs, USA, Canada, Singapore, Denmark, Italy)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2317]
_Transferred from sars-cov-2-variants/lineage-proposals#866_

**Defining Mutations:** `HV.1 (EG.5.1.6.1)` > `C12513T(ORF1a:T4083M/nsp8_T141M)` (#2228) > `A22893C(S:K444T)`
**Query:** `C5835T, C12513T, A22893C`
**Earliest seq:** 2023-08-30 (`EPI_ISL_18276226`, New York, USA)
**Latest seq:** 2023-09-25 (`EPI_ISL_18360534`, Denmark, _OR_ `EPI_ISL_18354907`, Singapore)
**Sampled Countries:** USA (9: HI/3; NY/3; CA; FL; NJ), Canada (2: ON), Singapore (2), Denmark (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18276226, EPI_ISL_18276468, EPI_ISL_18300264, EPI_ISL_18304836, EPI_ISL_18305437, EPI_ISL_18327914, EPI_ISL_18333419, EPI_ISL_18333947, EPI_ISL_18337152, EPI_ISL_18346020, EPI_ISL_18346976, EPI_ISL_18354906-18354907, EPI_ISL_18360534`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40bae_3d7570.json?f_userOrOld=uploaded%20sample&label=id:node_3418205
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/33935625-462c-43e2-8dc1-51462603b123)

**Comment by Sinickle** [comment]
EPI_ISL_18372718 collected 9/21 in Italy has additionally gained S:L455S. 
19 seq in the proposed lineage now.

**Comment by FedeGueli** [comment]
> EPI_ISL_18372718 collected 9/21 in Italy has additionally gained S:L455S. Especially notable because there is still no HV.1 with S:L455F still.
> 
> 19 seq in the proposed lineage now.

Thank you great catch!

**Comment by FedeGueli** [comment]
23 now (1 only with 455S)

**Comment by FedeGueli** [comment]
> EPI_ISL_18372718 collected 9/21 in Italy has additionally gained S:L455S. Especially notable because there is still no HV.1 with S:L455F still.
> 
> 19 seq in the proposed lineage now.

Now it is designated HV.1.1 please keep the 455S sublineage monitored!
