### ISSUE TITLE
EG.5.1+S:I19L(Total 616 seqs, 26 countries, main branch 505)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2318]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/940

There seems to be a branch on EG.5.1 with the 2-nuc mutation S:19:T->I->L, though it doesn't seem to have very large advantage. (+2% with EG.5.1 and +4% with EG.5.1 without L455F)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=EG.5.1*&aaMutations1=S%3A19L&nextcladePangoLineage1=EG.5.1*&analysisMode=CompareToBaseline&

EG.5.1+A21617C(S:I19L)

GISAID query: A21617C,C29625T,T28297C （General Branch)）
No. of seqs: 223(Australia 3 Canada 16 Canary Islands 1 Denmark 1 UK 7 France 1 China 11 Ireland 1 Italy 13 Japan 2 Portugal 1
Puerto Rico 1 Singapore 6 South Korea 10 Spain 9 USA 139(1 from Japan 1 from Dominician Republic) Ukraine 1 )

Main branch: A21617C,C29625T,T28297C,-G22927T,-G11266A (may increase -s as convergence going on)
Thanks @FedeGueli discovers multiple convergent branches of this in recent samples in EG.5.1.8 ,HK.1 and HK.3. More convergence may occur after that so query for main branch may increase -s. 

First: EPI_ISL_18287671, USA, 2023-1-31
Latest: EPI_ISL_18361997, Singapore, 2023-10-4

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/eg_5_1_i19l.json?label=id:node_3407112)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/00f39a6e-ba8b-4449-864b-00c393d0a590)

**Comment by aviczhl2** [comment]
259, Sweden

**Comment by aviczhl2** [comment]
302, Switzerland, Belgium

**Comment by FedeGueli** [comment]
hard for it to compete without additional mutations:https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=A21617C%2CC29625T%2CT28297C&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
322, Russia

**Comment by FedeGueli** [comment]
It seems to have gained S:L455F> lemme check

**Comment by FedeGueli** [comment]
> It seems to have gained S:L455F> lemme check

It didn't but your query catches also 4 HK.3 branches with S:T19L:
![Schermata 2023-10-22 alle 12 52 37](https://github.com/cov-lineages/pango-designation/assets/87669813/dcdf4b32-fa24-4c94-b868-4c6aaeab2c17)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_16544_4fe6b0.json?f_userOrOld=uploaded%20sample&label=id:node_3482337

plus another one of EG.5.1.8:
![Schermata 2023-10-22 alle 12 53 50](https://github.com/cov-lineages/pango-designation/assets/87669813/af265560-185c-449e-984a-9225c6c08887)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_16544_4fe6b0.json?f_userOrOld=uploaded%20sample&label=id:node_3454940

and also one in HK.1
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_16544_4fe6b0.json?f_userOrOld=uploaded%20sample&label=id:node_3456081
![Schermata 2023-10-22 alle 12 55 30](https://github.com/cov-lineages/pango-designation/assets/87669813/15cfa30f-a993-4da8-8979-6a1b5759719f)

**Comment by FedeGueli** [comment]
I suggest to change your query in : A21617C,C29625T,T28297C,-G22927T,-G11266A, that should exclude all these ones unrelated samples giving 292.

It is interesting to see how S:T19L seems going homoplasic as we saw for S:Q14

**Comment by aviczhl2** [comment]
405, Israel, Chile

**Comment by FedeGueli** [comment]
@corneliusroemer convergent evolution worth to be designated.

**Comment by aviczhl2** [comment]
429, Czech Republic

**Comment by aviczhl2** [comment]
524, Austria

**Comment by aviczhl2** [comment]
604, Germany
