### ISSUE TITLE
HK.2 with S:L455F (51 seqs, Singapore, China)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2319]
_Taken from Branch 23 of Multitask sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** `HK.2 (EG.5.1.1.2)` > `G22927T(S:L455F)`
**Query:** `C6541T, G21604T, G22927T, -A518G, -C934T, -C1426T, -G3663A, -C5031T, -C7712T, -A7849G, -C8320T, -T16545G`
**Earliest seq:** 2023-08-21 (`EPI_ISL_18141161`, Singapore)
**Latest seq:** 2023-10-04 (`EPI_ISL_18361986`, Singapore)
**Sampled Countries:** Singapore (42), China (7: SH/4; SC/3)

<details><summary>Genomes: </summary>

`EPI_ISL_18141161, EPI_ISL_18232598-18232599, EPI_ISL_18243535, EPI_ISL_18243547, EPI_ISL_18284673, EPI_ISL_18284676, EPI_ISL_18284792, EPI_ISL_18284928, EPI_ISL_18304265, EPI_ISL_18307050, EPI_ISL_18307053, EPI_ISL_18307061, EPI_ISL_18307099, EPI_ISL_18307102-18307103, EPI_ISL_18307105, EPI_ISL_18307107, EPI_ISL_18307112, EPI_ISL_18307182, EPI_ISL_18354947, EPI_ISL_18354954, EPI_ISL_18354956, EPI_ISL_18354983, EPI_ISL_18354995, EPI_ISL_18355001, EPI_ISL_18355021, EPI_ISL_18355024, EPI_ISL_18355036, EPI_ISL_18355050, EPI_ISL_18361722, EPI_ISL_18361757, EPI_ISL_18361769-18361770, EPI_ISL_18361774, EPI_ISL_18361805, EPI_ISL_18361811, EPI_ISL_18361828, EPI_ISL_18361847, EPI_ISL_18361863, EPI_ISL_18361888, EPI_ISL_18361929, EPI_ISL_18361941, EPI_ISL_18361946, EPI_ISL_18361986-18361987, EPI_ISL_18362111-18362112, EPI_ISL_18362114`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_f95d_696c50.json?f_userOrOld=uploaded sample&label=id:node_3440309
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/8c7227a6-7961-4a73-9a1f-ee927d3e1582)

**Trivia:**
- Both `G21604T(S:Q14H)` (definition of HK.2) and `G22927T(S:L455F)` (definition of HK.3) are quite homoplastic on EG.5* backbone, so be careful if this needs designation (either as `HK.2 + L455F` or `HK.3 + Q14H`)

**Comment by FedeGueli** [comment]
Likely a fast one: https://cov-spectrum.org/explore/Singapore/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C6541T%2CG21604T%2CG22927T%2CT16545T%2CC8320C%2CC7712C%2CA7849A%2CC5031C%2CC1426C%2CG3663G%2CC934C%2CA518A&analysisMode=CompareToBaseline&  but still not all the three CIs showing growth advantage.
