### ISSUE TITLE
EG.5.1.1 with ORF1a:L3919F (nsp7_L60F), ORF1a:A656V (nsp2_A476V) and S:L455F (215 seqs, 25 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2321]
_Taken from **Branch 31** of Multitask sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** **EG.5.1.1** > `C12020T(ORF1a:L3919F), T24496C` > `C2232T(ORF1a:A656V), C21516T, G22927T(S:L455F)`
**Query:** `C6541T, C12020T, G22927T, -C8982A, -C28087T`
**Earliest seq:** 2023-08-21 (`EPI_ISL_18216560`, Galway, Ireland)
**Latest seq:** 2023-10-01 (`EPI_ISL_18372127`, Ontario, Canada)
**Sampled Countries:** UK (19: EN/16; WS/2; SC/1), Ireland (10), USA (2: FL; OH), Canada (1: ON), China (1: HB), Sweden (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18216560, EPI_ISL_18244531, EPI_ISL_18254216, EPI_ISL_18263700, EPI_ISL_18263710, EPI_ISL_18263712, EPI_ISL_18273572, EPI_ISL_18273769, EPI_ISL_18275799, EPI_ISL_18281553, EPI_ISL_18281559, EPI_ISL_18281563, EPI_ISL_18281565-18281566, EPI_ISL_18281571, EPI_ISL_18286405, EPI_ISL_18288159, EPI_ISL_18290901, EPI_ISL_18301950, EPI_ISL_18302430, EPI_ISL_18302969-18302970, EPI_ISL_18302981, EPI_ISL_18315490, EPI_ISL_18332019, EPI_ISL_18332514, EPI_ISL_18332960, EPI_ISL_18355820, EPI_ISL_18355868, EPI_ISL_18363053, EPI_ISL_18366468, EPI_ISL_18367062, EPI_ISL_18372127, EPI_ISL_18373373`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_877_69f060.json?f_userOrOld=uploaded%20sample&label=id:node_3449912
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/84be9c7a-b95e-4bd3-aad8-7f6e153fce5d)

**Trivia:**
- There's a [discussion](https://github.com/sars-cov-2-variants/lineage-proposals/issues/537#issuecomment-1737557539) of this branch whether simply being HK.3-dropout or independently acquires `S:L455F`, also @FedeGueli suggests that both `ORF1a:L3919F` and `ORF1a:A656V` are predicted to be beneficial according to Bloom/Neher calculator.

**Comment by FedeGueli** [comment]
I see 49 with C6541T, C12020T, G22927T, -C28087T why?

**Comment by FedeGueli** [comment]
Thx

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by Over-There-Is** [comment]
247

**Comment by FedeGueli** [comment]
> 247

old ones
