### ISSUE TITLE
New GK.1.1/FU.1 recombinant in USA(21 seqs, 2 countries, 2 with S:ins214ESGL)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2323]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/885

XBB.1.5.70+
C23280T(S:T573I),C23673T(S:S704L), A24373C,G25045A(rev),A25359G(S:K1266R),A26708G, T27059C(rev),T28005C(Orf8:38 rev),T28297C(Orf9b:I5T),A28447G(Orf9b:N55S), T29386C

C23280T,C23673T from GK.1.1
A24373C,G25045A(rev),A25359G(S:K1266R),A26708G, T27059C(rev),T28005C(Orf8:38 rev),T28297C(Orf9b:I5T),A28447G(Orf9b:N55S), T29386C from an American FU.1 branch

GK.1.1---FU.1
Breakpoint between 23674 and 24372

GISAID query: A24373C,A25359G,C23280T
No. of seqs: 21(USA, 1 from Germany)
20 using the given query, plus EPI_ISL_18357618. 

First: EPI_ISL_18266013, FL, 2023-8-23
Latest: EPI_ISL_18379363, WA, 2023-9-28

There are 2 seqs with S:ins214ESGL,  ins_22204GAGTCAGGCTTA thanks @ryhisner.

GISAID query for ins214ESGL branch: A24373C,A25359G,C23280T,ins22204

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/gk_1_1_fu_1_recomb.json?label=id:node_3703612)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/d48521ff-19f1-4b32-aea3-2aac44ac49d0)

FU.1-side donor:

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/66c0e58d-b3a0-4b39-af4b-394b78869a45)

**Comment by JosetteSchoenma** [comment]
XCR
