### ISSUE TITLE
XBB.1.5.103+S:E554K(63 seqs,14 countries) 

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2326]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/822

XBB.1.5.103+G23222A(S:E554K)

GISAID query 1: G23222A, C4575T
GISAID query 2:  A2389G,G23222A,del22100, -C4575T
No. of seqs: 63(Argentina 8 Belgium 1 Brazil 2 Peru 1 Denmark 1 UK 6 France 5 Germany 1 Greece 1 Italy 4 Spain 13 Sweden 3 USA 19 Uraguay 1)
 query 1 finds 56 and query 2 finds 7 more, all belongs to this branch.

First: EPI_ISL_18095189, Argentina, 2023-7-2
Latest: EPI_ISL_18364656, Italy, 2023-9-26

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/xbb_1_5_103_e554k.json?label=id:node_3550822)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/9eb57472-93d9-4075-98d3-56af03e21a6f)

**Comment by FedeGueli** [comment]
Designated KA.1 via https://github.com/cov-lineages/pango-designation/commit/f8fd4e6b95f8d5a6c7ab7fc3434c5835c18b81b3
