### ISSUE TITLE
EG.5.1.1 with 356T, 681R and T28251G, C28253T,A28254C (3 seqs, US-NY/US-NJ-GBW/Austria)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#2327]
Came across what looks like an interesting saltation that popped up fairly suddenly in US and Austria.

@ryhisner do you know whether this pattern of T28251G,C28253T,A28254C could have something to do with TRSs? Doesn't look like for me, do you know of other reasons such a pattern could occur frequently?

Usher placement:
<img width="2224" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/3afbae7a-3cb4-4823-8f07-71f902572d58">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5cae6_bd3fe0.json

```txt
hCoV-19/USA/NJ-GBW-H10-016-2699/2023|EPI_ISL_18386597|2023-10-05
hCoV-19/Austria/AGES-1141231/2023|EPI_ISL_18385103|2023-10-03
USA/NY-CDC-QDX85770892/2023|OR662426.1|2023-09-28
```

Usher seems to mask the 28253 mutation?

This is the new pattern:
<img width="481" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/827d8313-5f35-4878-a48c-2abd3a5c67c4">

**Comment by ryhisner** [comment]
Yes, that's one of the many forms of extended homology for the ORF9b/N TRS. It adds five additional nucleotides of perfect extended homology to the TRS-L. One of the constants in SARS-CoV-2 evolution seems to be mutations to increase ORF9b/N expression.
<img width="1392" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/81cf3e31-310f-4a0f-9a03-eddd70f46b57">

**Comment by aviczhl2** [comment]
I think usher shall mask 28245-28254 site. @AngieHinrichs 

1:Although they're real, they are very convergent but only have minor effects. 
2:They usually contain insertions that usher cannot handle. For example, ins28250CT is one of the most common form, and usher always misread it.
3:Usher always put a lot of mutations in these region, this makes neighboring lineages with such kind of late-Orf8 form shift don't be in the correct place, only follows the largest nearby group with the same late-orf8 form.

**Comment by AngieHinrichs** [comment]
Sorry about the slow reply.  I agree, and it looks like masking 28245, 28251 and 28254 will take care of most of the problems.  I will mask those in the BA.2 branch (includes BA.4, BA.5 & XBB) starting in today's build 2023-11-09.

**Comment by corneliusroemer** [comment]
14 sequences now but a bit slow/small for designation

**Comment by corneliusroemer** [comment]
Quite a saltation though
<img width="2145" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/c1030045-5304-46fa-add2-287f3cae7fbe">

**Comment by FedeGueli** [comment]
I was tracking it from @ryhisner proposal : https://github.com/sars-cov-2-variants/lineage-proposals/issues/986 that came after this one.

**Comment by corneliusroemer** [comment]
Not quite sure why I closed this as not planned, it keeps popping up and it's really a big saltation, I just rediscovered it 🤦 and had entirely forgotten I had made this issue a month ago. Thanks @ryhisner  for tracking it in https://github.com/sars-cov-2-variants/lineage-proposals/issues/986

**Comment by Mydtlwn** [comment]
> Not quite sure why I closed this as not planned, it keeps popping up and it's really a big saltation, I just rediscovered it 🤦 and had entirely forgotten I had made this issue a month ago. Thanks @ryhisner for tracking it in [sars-cov-2-variants/lineage-proposals#986](https://github.com/sars-cov-2-variants/lineage-proposals/issues/986)

I also usually have a case of forgetting, and my solution is to create a JSON file called a catalog so I can always look it up and see the title of the issues as well as the content, time, and author information.
