### ISSUE TITLE
GY.1 (XBB.1.16.2) with S:F456L then S:L455F (47 seqs, 11 countries) futher with S:A475V (9 seqs, Thailand)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2337]
_Transferred from sars-cov-2-variants/lineage-proposals#804_

**Defining Mutations:** `GY.1 (XBB.1.16.2)` > `T22928C(S:F456L)` > `C19380T, G22927T(S:L455F)`
**Query:** `C3042A, G12467T, G22927T`

**Defining Mutations for `S:A475V` mini-saltation branch:** `Main proposal` > `C1091T(ORF1a:P276S/nsp2_P96S), C3117T(ORF1a:T951I/nsp3_T133I), G3452A(ORF1a:V1063I/nsp3_V245I), C11020T, T15276C, C22986T(S:A475V)`
**Query for `S:A475V` sub-branch:** `C3042A, G12467T, C22986T`

**Earliest seq:** 2023-06-20 (`EPI_ISL_18556598`, Lampang, Thailand)
**Latest seq:** 2023-10-06 (`EPI_ISL_18398421`, England, UK)
**Sampled Countries:** Canada (8: MB), China (6: SC/3; HB/1; SX/1; YN/1), UK (3: EN), USA (3: NY; ex. UK/2), Denmark (2), Austria (1), France (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18246357, EPI_ISL_18254262, EPI_ISL_18258452, EPI_ISL_18292669, EPI_ISL_18294558, EPI_ISL_18304249, EPI_ISL_18333682, EPI_ISL_18377682, EPI_ISL_18384484, EPI_ISL_18386637, EPI_ISL_18386651, EPI_ISL_18396443, EPI_ISL_18396445-18396446, EPI_ISL_18396448, EPI_ISL_18396476, EPI_ISL_18396479, EPI_ISL_18396497-18396498, EPI_ISL_18398139, EPI_ISL_18398411, EPI_ISL_18398421, EPI_ISL_18401949, EPI_ISL_18406265`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice10_genome_d207_6dec80.json?label=id:node_3276753
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/5f293aed-b09a-490a-90ec-8869967937d7)

**Comment by FedeGueli** [comment]
39 now it seems to have slowed down a lot, maybe better closing it

**Comment by Over-There-Is** [comment]
GY.1.1 and GY.1.1.1
