### ISSUE TITLE
HN.2 with ORF1a:G2269D (431)

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2339]
transferred: https://github.com/sars-cov-2-variants/lineage-proposals/issues/676
Query for this proposal: C14134T, C21036T, G7071A
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/ac9ec1f7-e557-4abb-93a4-90e76f11c268)

**Comment by FedeGueli** [comment]
> almost 90% of HN.2 has ORF1a:G2269D

In this case a further designation in absence of something new it is not worth. i suggest to close this one. 

cc @corneliusroemer what do you think?
