### ISSUE TITLE
EG.5.1.1 with ORF8:A65V and S:L455F (224 seqs, 13 countries) further gained S:A348S (54 seqs, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2340]
_Taken from **Branch 15** of multitask sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** `EG.5.1.1` > `C28087T(ORF8:A65V)` > `G22927T(S:L455F)` , mostly with further `C8982A(ORF1a:T2906N/nsp4_T143N), T19710C, C27213T` sub-branch
**Query:** `C6541T, G22927T, C28087T, -A4306G, -G4444A, -A6889G, -G8171A, -T8305C, -C10039T, -C19185T, -C25207T` **OR** `C8982A, T19710C` if only count the major `ORF1a:T2906N` sub-branch

**Defining Mutations for further S:A348S sub-branch:** `Main proposal` > `C8982A(ORF1a:T2906N), T19710C, C27213T` > `G1067T(ORF1a:G268W)` > `G22604T(S:A348S)`
**Query for further S:A348S sub-branch:** `G1067T, C8982A, G22604T`

**Earliest seq:** 2023-08-10 (`EPI_ISL_18138246`, Shanghai)
**Latest seq:** 2023-10-11 (`EPI_ISL_18397348`, Singapore)
**Sampled Countries:** Singapore (39), China (16: SH/6; SC/3; QH/2; HA; HB; HL; LN; SX), Japan (6), South Korea (5), Belgium (2), Canada (2: AB; ON), Australia (1: NSW), Austria (1), USA (1: AZ)

<details><summary>Genomes: </summary>

`EPI_ISL_18138040, EPI_ISL_18138246, EPI_ISL_18208534, EPI_ISL_18213338, EPI_ISL_18243416, EPI_ISL_18284693, EPI_ISL_18284883, EPI_ISL_18284945, EPI_ISL_18285015, EPI_ISL_18285039, EPI_ISL_18289913, EPI_ISL_18292661, EPI_ISL_18312855, EPI_ISL_18313044, EPI_ISL_18313125, EPI_ISL_18313232, EPI_ISL_18320677, EPI_ISL_18320703, EPI_ISL_18324382, EPI_ISL_18324868, EPI_ISL_18346119, EPI_ISL_18354784, EPI_ISL_18354968, EPI_ISL_18354976, EPI_ISL_18355029, EPI_ISL_18361857, EPI_ISL_18361924, EPI_ISL_18361928, EPI_ISL_18361967, EPI_ISL_18362004, EPI_ISL_18362012, EPI_ISL_18362042, EPI_ISL_18362056, EPI_ISL_18362082, EPI_ISL_18372524, EPI_ISL_18376804, EPI_ISL_18376810, EPI_ISL_18376814, EPI_ISL_18376830, EPI_ISL_18376851, EPI_ISL_18376867, EPI_ISL_18376933, EPI_ISL_18379403, EPI_ISL_18382112, EPI_ISL_18382725, EPI_ISL_18384400, EPI_ISL_18385457, EPI_ISL_18385461, EPI_ISL_18397250, EPI_ISL_18397275, EPI_ISL_18397308, EPI_ISL_18397326, EPI_ISL_18397348, EPI_ISL_18397352, EPI_ISL_18397366, EPI_ISL_18397371, EPI_ISL_18397408, EPI_ISL_18397428, EPI_ISL_18397446, EPI_ISL_18397456, EPI_ISL_18397463, EPI_ISL_18397524, EPI_ISL_18397532, EPI_ISL_18397540, EPI_ISL_18397553, EPI_ISL_18397602, EPI_ISL_18397623, EPI_ISL_18402854, EPI_ISL_18406266, EPI_ISL_18408689, EPI_ISL_18409307, EPI_ISL_18411310, EPI_ISL_18411340`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_28cd5_2dbad0.json?f_userOrOld=uploaded%20sample&label=id:node_3458668
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/f5fe9891-f455-4f94-9283-ff58d8f6e9c4)

**Comment by FedeGueli** [comment]
Being Orf8:A65V a known messy homoplasic mutation we could decide to start it deeper with Orf1a:T2906N cc @corneliusroemer @NkRMnZr

**Comment by FedeGueli** [comment]
103 now , It is going fast in Singapore.

**Comment by FedeGueli** [comment]
Thx @NkRMnZr good catch  on 348S. I noticed two JG.3 in Singapore with S:A348 mutated too, we should monitor if it is nt a possible new pathway fro FLIP to evolve further.

About the growth of this one, it is in some long term care hospice in Canada lets see if it goes well outside that.

**Comment by FedeGueli** [comment]
India not Singapore.

**Comment by FedeGueli** [comment]
the 348S branch is doubling in 7 days well below the HK.3 & alike doubling time

**Comment by FedeGueli** [comment]
257 as today subbranch with S:A348S at 63. one of the fastest flip but slower than JG.3
