### ISSUE TITLE
EG.5.1.1 with ORF3a:T34K, N:G204P (G>R>P) and S:L455F (196 seqs, 19 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2342]
_Taken from **Branch 27** of multitask sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** `EG.5.1.1` > `C25493A(ORF3a:T34K)` > `G28884C(N:G204P)` > `G22927T(S:L455F)`
**Query:** `C6541T, G22927T, C25493A`
**Earliest seq:** 2023-07-18 (`EPI_ISL_18245992`, Heilongjiang)
**Latest seq:** 2023-10-10 (`EPI_ISL_18397223`, Singapore)
**Sampled Countries:** China (18: HL/10; LN/2; SH/2; HB; SC; SX; YN), Singapore (14), Denmark (4), Italy (3), USA (3: CA/2; NY), France (2), Australia (1: NSW), Germany (1), South Korea (1), Sweden (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18138073, EPI_ISL_18232576, EPI_ISL_18244264, EPI_ISL_18245964, EPI_ISL_18245971, EPI_ISL_18245992, EPI_ISL_18246139, EPI_ISL_18246193, EPI_ISL_18282065, EPI_ISL_18300796, EPI_ISL_18306948, EPI_ISL_18306976, EPI_ISL_18306993, EPI_ISL_18307005-18307006, EPI_ISL_18307019, EPI_ISL_18307026, EPI_ISL_18313136, EPI_ISL_18320696, EPI_ISL_18324230, EPI_ISL_18329168, EPI_ISL_18330265, EPI_ISL_18339790, EPI_ISL_18352920, EPI_ISL_18356975, EPI_ISL_18361976, EPI_ISL_18362045, EPI_ISL_18376532, EPI_ISL_18376955, EPI_ISL_18377536, EPI_ISL_18377636, EPI_ISL_18382895, EPI_ISL_18384393, EPI_ISL_18384413, EPI_ISL_18384418, EPI_ISL_18384426, EPI_ISL_18384448, EPI_ISL_18384625, EPI_ISL_18384643, EPI_ISL_18391206-18391207, EPI_ISL_18397223, EPI_ISL_18397241, EPI_ISL_18397267, EPI_ISL_18397584, EPI_ISL_18401938, EPI_ISL_18405209, EPI_ISL_18406218`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_58dd0_2eda30.json?f_userOrOld=uploaded%20sample&label=id:node_3458763
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/287e4c21-ad58-4ae8-8be9-f6b2b6b93270)

**Comment by FedeGueli** [comment]
173

**Comment by DailyCovidCases** [comment]
Please close this issue
