### ISSUE TITLE
HK.3 with Orf3a:L52I , 210 seqs with a sublineage of interest with S:A475V (4 , Finland ) 

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#2343]
Transfered from issue 763 of the other repository
Gisaid Search: C25546A,T14988C,-C22264T,G22927T
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_35a3b_473fc0.json?f_userOrOld=uploaded%20sample&label=id:node_991688
<img width="1484" alt="Screenshot 2023-10-21 at 9 00 59 PM" src="https://github.com/cov-lineages/pango-designation/assets/131021067/0f8fed5a-690f-461e-8132-725740095713">

There is a minor branch with S:A475V that is currently limited in Finland, and its search is given by  C22986T, C25546A ,G22927T

**Comment by oobb45729** [comment]
19 with S:A475V now and new in Denmark and USA.

**Comment by FedeGueli** [comment]
@corneliusroemer i suggest to designate the 475V branch

**Comment by FedeGueli** [comment]
20 now

**Comment by FedeGueli** [comment]
HK.3.11 via https://github.com/cov-lineages/pango-designation/commit/738adab884bcae6fecd3cf0dce7cb7aa4a6c4a88

**Comment by krosa1910** [comment]
Quite some massive uploads of the A475V branch when I am out.
<img width="1174" alt="Screenshot 2023-12-21 at 4 09 15 AM" src="https://github.com/cov-lineages/pango-designation/assets/131021067/ec8a8bf8-e8b6-40df-99c5-489fab886a8f">
@corneliusroemer @FedeGueli I suggest designation of the largest branch as it seems clearly defined. After that this issue can be closed.

**Comment by krosa1910** [comment]
Oh that's already done (Why do Fede write HK.3.11 here, makes me confused.). The thing is actually HK.26 and 26.1

**Comment by FedeGueli** [comment]
> Oh that's already done (Why do Fede write HK.3.11 here, makes me confused.). The thing is actually HK.26 and 26.1

yeah it was then retracted and i missed to correct here (forgotten completely about it ) sorry! i apologize.
