### ISSUE TITLE
GN.1 with mutation S:G181V and nucleotide T2548C,T21799C

### ISSUE THREAD

**Issue by OrsonMM** [cov-lineages/pango-designation#2349]
GN.1 with mutation S:G181V and nucleotide T2548C,T21799C spread in Peru
by Group of Genomic Surveillance INS-PERU

Description
Sublineage of: Potencially new sublineage of GN.1.X (S:G181V and nucl T2548C,T21799C )
Earliest sequence: hCoV-19/Peru/LIM-INS-46131/2023 (2023-08-17, Peru)
Most recent sequence: hCoV-19/USA/NJ-GBW-H20-340-8871/2023 (2023-09-29, USA)
Countries circulating: Peru (22), USA (2), Costa Rica (1)

Mutation

nucl T2548C,T21799C and S:G181V

Genomes

EPI_ISL_18252004, EPI_ISL_18336991, EPI_ISL_18337033,
EPI_ISL_18337036, EPI_ISL_18337079, EPI_ISL_18368448,
EPI_ISL_18368589, EPI_ISL_18379236, EPI_ISL_18379244,
EPI_ISL_18379246, EPI_ISL_18379255, EPI_ISL_18379290,
EPI_ISL_18379304, EPI_ISL_18379336, EPI_ISL_18379338,
EPI_ISL_18380443, EPI_ISL_18380471, EPI_ISL_18380492,
EPI_ISL_18380505, EPI_ISL_18380507, EPI_ISL_18380529,
EPI_ISL_18380537-18380538, EPI_ISL_18380541, EPI_ISL_18435203,

Evidence

![image](https://github.com/cov-lineages/pango-designation/assets/12600107/cd4bc41c-2f8c-4d32-ad88-a3be0b4dd485)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ac19_ab9870.json?c=gt-nuc_2548,21799&gmax=22799&gmin=1548&label=id:node_3570649

Proposed lineage name

GN.1.X

COV SPECTRUM

https://cov-spectrum.org/explore/Peru/AllSamples/Past6M/variants?nucMutations=T2548C%2CT21799C&

![image](https://github.com/cov-lineages/pango-designation/assets/12600107/bd3202a4-007f-4e25-b3de-4a37038384b6)

**Comment by Vjimenez-vasquez** [comment]
Nice observation colleage ! Still waitig the increase of this clade after the detection of "Pirola" in Peru.

**Comment by OrsonMM** [comment]
14 Genomes more to peru

EPI_ISL_18437450, EPI_ISL_18437505, EPI_ISL_18437528,
EPI_ISL_18437543, EPI_ISL_18437557, EPI_ISL_18474412,
EPI_ISL_18474415, EPI_ISL_18474420, EPI_ISL_18474434,
EPI_ISL_18474444, EPI_ISL_18474473, EPI_ISL_18474480,
EPI_ISL_18474482, EPI_ISL_18474521

**Comment by OrsonMM** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/12600107/81ba68ae-4e18-4146-acee-1fdf7bbc12c6)

**Comment by INDEINS** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/138617344/76631f4e-c9ec-463d-8641-23a9fe1556bb)

**Comment by FedeGueli** [comment]
78 sequences now and 10% prevalence in Peru through November cc @corneliusroemer i suggest to designate it.

**Comment by FedeGueli** [comment]
Designted GN.1.4 via https://github.com/cov-lineages/pango-designation/commit/72a1e52adbafec108c48fd82da874e7f52a9860d 
@corneliusroemer please add milestone here.

**Comment by DailyCovidCases** [comment]
Please close this issue
