### ISSUE TITLE
EG.5.1.1/non-EG.5 recombinant involving S:I1114T (186 seqs, 23 countries, 181 with Flip, 3% Malaysia 3% Gansu) 

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2351]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/914

EG.5.1.1+T29625C(Orf10:F23S rev)+C15981T,T24903C(S:I1114T)

EG.5.1.1--anything non-EG.5
Breakpoint before 25573 and 29624, range depend on donor

T29625C(rev) from anything non-EG.5
one of C15981T,T24903C come from an EG.5.1.1 branch, the other is private. 

GISAID query: C15981T,T24903C
No. of seqs: 25(UK 1 France 6 Iceland 1 Malaysia 1 Norway 1 Sweden 3 Switzerland 2 China 10)

First: EPI_ISL_18111103, Yunnan, 2023-7-30
Latest: EPI_ISL_18439950, UK, 2023-10-16

GISAID query for branch with S:L455F: C15981T,T24903C,G22927T  (23 seqs)

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/eg_5_1_1_recomb_i1114t.json?label=id:node_3495891)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/788c68ec-b0a4-4677-a74c-e4eed2f2f837)

**Comment by aviczhl2** [comment]
27, Germany

**Comment by aviczhl2** [comment]
34, Mauritius, Malaysia, Denmark

**Comment by aviczhl2** [comment]
It seems that there's 13 additional CLIMB seqs not on GISAID now.

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/5a45131d-d19d-4e36-8441-07ef6beb3cd5)

**Comment by aviczhl2** [comment]
While losing Orf10:S23F through recomb, the newly uploaded UK branch regains Orf10:R24C independently.  @FedeGueli @ryhisner @corneliusroemer

**Comment by FedeGueli** [comment]
up to 74 now.

**Comment by aviczhl2** [comment]
New country of Singapore

**Comment by aviczhl2** [comment]
89, New Zealand, Spain
Don't know why but this one seems fast.

**Comment by FedeGueli** [comment]
Yes it well over other designated lineages: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1*&nucMutations1=C15981T%2CT24903C&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
111 now. @corneliusroemer @InfrPopGen

**Comment by FedeGueli** [comment]
one of the fastest not Ba.2.86 lineage

**Comment by aviczhl2** [comment]
Wait I find a way to express this recomb to 0 private mutations. 
We can regard it as recomb between XBB.1.9.2+S:1114T and EG.5.1.1+C15981T. Maybe this is a better way?

**Comment by aviczhl2** [comment]
> Wait I find a way to express this recomb to 0 private mutations. We can view it as recomb between XBB.1.9.2+S:1114T and EG.5.1.1+C15981T. Maybe this is a better way? This view increases 1 explained mutation and reduces private mutations from 1 to 0.

Sorry this one cannot happen as there's no XBB.1.9.2+S:I1114T having T25572C. Breakpoint shall be after 25573 though

**Comment by aviczhl2** [comment]
128, Italy

**Comment by aviczhl2** [comment]
130, Finland

**Comment by aviczhl2** [comment]
141, Netherlands, Japan. 

Also 5/367 in the 12-19 Singapore batch.

**Comment by FedeGueli** [comment]
@corneliusroemer this is increasing its share in Singapore, still low numbers so it could be biased , but still i think it is worth designating. i noticed that nextclade assigns it to multiple different lineages 
![Schermata 2023-12-19 alle 11 28 06](https://github.com/cov-lineages/pango-designation/assets/87669813/064f53b5-c24b-4a51-b522-89dd64b21005)
 maybe better designating and keep it tracked.

**Comment by aviczhl2** [comment]
> @corneliusroemer this is increasing its share in Singapore, still low numbers so it could be biased , but still i think it is worth designating. i noticed that nextclade assigns it to multiple different lineages ![Schermata 2023-12-19 alle 11 28 06]

I don't find any sub-branch having S:Q14H or S:T883I. Why is it assigned to HK.2.1 or HK.4?

**Comment by aviczhl2** [comment]
153, Austria , Greece

**Comment by FedeGueli** [comment]
162 now with a 2% prevlaence in Gansu, China. @corneliusroemer i suggest a designation of this one being big enough and enough widespread.
Its growth disadvantage vs JN.1 is clear but not super huge: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nucMutations=C15981T%2CT24903C&nextcladePangoLineage1=JN.1*&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
5/175 in the 12-24 Gansu batch

**Comment by aviczhl2** [comment]
11/387 in Malaysia seqs from 2023.11.1

**Comment by aviczhl2** [comment]
182, Poland

**Comment by aviczhl2** [comment]
186, Australia

**Comment by FedeGueli** [comment]
XDL
