### ISSUE TITLE
Potential GW.5.1*/ FL.13.4 recombinant that gained ORF8:G8* and ORF9b:I5T (15 seqs, Pakistan, France, USA, Australia, Austria)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2352]
_Transferred from sars-cov-2-variants/lineage-proposals#855_

**Query:** `C7113T, G22927T, C29535T`
**Earliest seq:** 2023-09-14 (`EPI_ISL_18294822`, Islamabad, Pakistan)
**Latest seq:** 2023-10-09 (`EPI_ISL_18428132`, Chalon-sur-Saône, France)
**Sampled Countries:** Pakistan (7), France (2), Australia (1: NSW), USA (1: NJ) 

**Recombinant Profiles:**
- Placement on Phylogenetic Tree: `XBB.1.19.1` > _`C28511T(N:P80S)`_ > `C1170T(ORF1a:S302F)` > `C12473T, C12924T(ORF1a:P4220L), C22995T(S:T478I), C24034T` > `C2260T, C7113T(ORF1a:T2283I), G22927T(S:L455F), T22928C(S:F456L), G27915T(ORF8:G8*), T28297C(ORF9b:I5T)`, _`T28511C_reversion(N:S80P_reversion)`_, `C29535T`
- Donor A: **GW.5***, upstream from 5' end to breakpoint
- Donor B: Any **XBB.1*** with `ORF8:G8*` and `ORF9b:I5T`, possibly FL.13.4 (thanks to analysis by @Over-There-Is ), downstream from breakpoint to 3' end.
- Breakpoint: Between `nuc_24034/spike_824` to `nuc_24046/spike_828`
- Private mutations: `C2260T`, `C7113T/ORF1a:T2283I`, `C29535T`
![mut](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/fa942c04-400f-4def-ab81-685750045312)

<details><summary>Genomes: </summary>

`EPI_ISL_18294822, EPI_ISL_18294824-18294825, EPI_ISL_18294827, EPI_ISL_18387869, EPI_ISL_18389828, EPI_ISL_18411746, EPI_ISL_18428132, EPI_ISL_18445466, EPI_ISL_18445468, EPI_ISL_18445472`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_abeb_91c90.json?label=id:node_3206598

current placement, with `ORF8_G8` genotype filter
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/1402140b-c895-4002-9c45-ac8392f129ae)

details
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/7279f6ac-bfd4-4532-8ee8-7a7c13bc8df7)

**Trivia:**
- This looks like contaminated to me at first, however, after cheking that 3 seqs have Ns around `nuc_6501` but `EPI_ISL_18294827` does cover that and has `C6501A(ORF1a:P2079Q)`, it cannot be ruled out of a real recombinant.
- There's a sub-branch with `ORF1a:T2283I` follows: `GW.5` > `A28768G` > `G25839T(ORF3a:W149C)` > `C7113T(ORF1a:T2283I)` suits Donor A, but all seqs are from England.
- There's a `FL.13` sequence from that area suits Donor B with query: `G27915T, T28297C, C29535T, -C28511T`, `EPI_ISL_17690187` but that was collected months back.
- Further analysis by @Over-There-Is : 
_Possible Donor A: `GW.5.1` > `C7113T(ORF1a:T2283I)`
Possible Donor B: `FL.13.4` > `T19896C, C29535T` > `C2434T, A22893G(S:K444R), G23222A(S:E554K), A26612G`_

**Comment by Over-There-Is** [comment]
https://github.com/sars-cov-2-variants/lineage-proposals/issues/855#issuecomment-1778532829
All sequences have G or N on 26612, it should be inherited A26612G from FL.13.4 > T19896C, C29535T > C2434T, A22893G(S:K444R), G23222A(S:E554K), A26612G branch.

**Comment by FedeGueli** [comment]
Great catch @Over-There-Is
