### ISSUE TITLE
Another EG.5.1.4 (side-branch of JJ.1) with ORF3:P240L and S:L455F (383 seqs, mainly in Canada, 9 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2354]
_Taken from **Branch 35** of Multitask sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** `EG.5.1.4` > `C26111T(ORF3:P240L)` > `C18555T` > `T17268C` > `G22927T(S:L455F)`
**Query:** `T17268C, G22927T, C26111T`
**Earliest seq:** 2023-08-08 (`EPI_ISL_18132133`, Newfoundland and Labrador)
**Latest seq:** 2023-10-23 (`EPI_ISL_18448815`, Ontario, Canada)
**Sampled Countries:** Canada (49: ON/22; NL/15; AB/10; BC/1; NS/1), US (7: CA/2; NY/2; AZ/1; UT/1; VA/1), France (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18132133, EPI_ISL_18256806, EPI_ISL_18258767, EPI_ISL_18258769-18258770, EPI_ISL_18258773, EPI_ISL_18258778, EPI_ISL_18291996, EPI_ISL_18291998, EPI_ISL_18292017, EPI_ISL_18292020-18292022, EPI_ISL_18292026-18292028, EPI_ISL_18333999, EPI_ISL_18344763, EPI_ISL_18357035, EPI_ISL_18372328, EPI_ISL_18372367, EPI_ISL_18383112, EPI_ISL_18383123-18383124, EPI_ISL_18383697, EPI_ISL_18388693, EPI_ISL_18395288, EPI_ISL_18395414, EPI_ISL_18395581, EPI_ISL_18404467, EPI_ISL_18425010, EPI_ISL_18425420, EPI_ISL_18425431, EPI_ISL_18425847, EPI_ISL_18425967, EPI_ISL_18426727, EPI_ISL_18427300, EPI_ISL_18427492, EPI_ISL_18427494, EPI_ISL_18427496, EPI_ISL_18427507, EPI_ISL_18427602, EPI_ISL_18431345, EPI_ISL_18436820, EPI_ISL_18437028, EPI_ISL_18437176, EPI_ISL_18438632, EPI_ISL_18438777, EPI_ISL_18448237, EPI_ISL_18448584-18448585, EPI_ISL_18448588, EPI_ISL_18448699-18448700, EPI_ISL_18448702, EPI_ISL_18448740, EPI_ISL_18448815`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_17f71_c79a0.json?f_userOrOld=uploaded%20sample&label=id:node_3447785

view from EG.5.1.4 polytomy
![sc](https://github.com/cov-lineages/pango-designation/assets/125747944/ebe6d072-41ab-4699-892f-106d43762671)

details
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/eedd1bf9-8911-4fee-a970-ca8e9fca6d2f)

**Comment by FedeGueli** [comment]
248 now

**Comment by FedeGueli** [comment]
410

**Comment by krosa1910** [comment]
<img width="977" alt="Screenshot 2024-03-01 at 11 38 28 AM" src="https://github.com/cov-lineages/pango-designation/assets/131021067/e8b3132d-604f-4593-999a-46f69824694d">
There seems a major stepwise mutation branch here ,defined by G28079T->T508C->G28089C(Orf8:G66R)->G14398A(Orf1ab:V4712M)->C12484T->T14514C->C27567T->G8258T(Orf1ab:V2665F),A11782G 
<img width="977" alt="Screenshot 2024-03-01 at 11 44 47 AM" src="https://github.com/cov-lineages/pango-designation/assets/131021067/f1f01a8d-f99e-4b4e-9f60-b0900693535a">


<img width="977" alt="Screenshot 2024-03-01 at 11 44 55 AM" src="https://github.com/cov-lineages/pango-designation/assets/131021067/4b7265b3-893a-4d55-af57-a0915e5da180">


<img width="977" alt="Screenshot 2024-03-01 at 11 39 00 AM" src="https://github.com/cov-lineages/pango-designation/assets/131021067/4a7e9c13-fec2-4fcc-8aed-8dcd4c622d2d">

**Comment by DailyCovidCases** [comment]
Please close this issue
