### ISSUE TITLE
HK.8+Orf3a:S171L+S:D1153Y(108 seqs, 9 countries, 13% in Sichuan)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2356]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/794

HK.8+C25904T(Orf3a:S171L)+C25019T(S:D1153Y)

GISAID query: G25019T,C25904T,G22927T
No. of seqs: 55(Belgium 1 Canada 2 Italy 1 Singapore 1 USA 4(1 from Singapore) China 46)

First: EPI_ISL_18241520, Yunnan, 2023-8-10
Latest: EPI_ISL_18445529, Belgium, 2023-10-24

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/hk_8_d1153y.json?label=id:node_3503371)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/804b0d3c-f8bf-4a7a-85c3-6d9c7b3fe129)

Already showing further Spike diversity such as S256L or P1162L.

**Comment by aviczhl2** [comment]
85, Japan

**Comment by aviczhl2** [comment]
17/135=13% in Sichuan's latest batch

**Comment by FedeGueli** [comment]
ping @corneliusroemer this is bringing up HK.8 that in itself is slower than HK.3, and it is quite well distributed in China

**Comment by aviczhl2** [comment]
108, Austria, South Korea

**Comment by FedeGueli** [comment]
Thx @aviczhl2 for your tireless  tracking of this.

**Comment by aviczhl2** [comment]
> there's a few or at least a sub-branch with `S:N481del, G482S (del23004-23006)` ![image](https://private-user-images.githubusercontent.com/125747944/286455439-8cad3e1d-cf79-4777-a5cf-b0074fbd182b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjUyNjAsIm5iZiI6MTcwMTIyNDk2MCwicGF0aCI6Ii8xMjU3NDc5NDQvMjg2NDU1NDM5LThjYWQzZTFkLWNmNzktNDc3Ny1hNWNmLWIwMDc0ZmJkMTgyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQwMjI5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTVhZGVlNzdkNmVlYWE2M2MwMjFkODk3NzczZTk1ZDYxNzEyMTkwYzZhMGI3ZjZhMWQ2YTc2OWFlNzk4YmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JhgHAcP78ZLkX0mHiYcy5ib-hij7NHVe-meeFS4FaPc)

13 seqs,GISAID shows this as del23003_23005 and G23006A.

**Comment by aviczhl2** [comment]
> Well so that's only a part of HK.8.1, not all of it, misguided by UShER label https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18fdc_69fbc0.json?f_userOrOld=uploaded%20sample&label=id:node_3524325

You shall make an issue to track this.

**Comment by FedeGueli** [comment]
please comment under the commit so Corneliu could see if possible to designate it directly.

**Comment by AngieHinrichs** [comment]
I see the HK.8.1 path included C19032T which was not intended.  I will fix it so it's one level up at G25019T (S:D1153Y).  No need to make a separate issue for that.

**Comment by aviczhl2** [comment]
> I see the HK.8.1 path included C19032T which was not intended. I will fix it so it's one level up at G25019T (S:D1153Y). No need to make a separate issue for that.

Oh, it's not about this. The issue here is that there is an HK.8.1+S:481- ,S:G482S branch and usher cannot handle deletions.
