### ISSUE TITLE
HK.3 with S:L452Q (13 seq, Australia, USA)

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#2357]
GISAID Query: G18332A, T22917A, T15408C
Earliest Sequence: Sep 17, Australia NSW - EPI_ISL_18324789
Countries: Australia - 12 (multiple regions), USA - 1

**Mutations**:
ORF1a:V2238A,
ORF1b:R1622K,
S:L452Q,
ORF3a:M5I
C2662T, T2698C, A3019G, T6978C, T15408C, G18332A, T22917A, T24709C, G25407T

[USHER](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_394e2_3b36a0.json?f_userOrOld=uploaded%20sample)
![image](https://github.com/cov-lineages/pango-designation/assets/94097102/8d4f5365-90ec-4d83-82e7-ac59861ef50d)

**Discussion:** 
11/13 of the sequences at the moment are in October. There are sequences for Australian regions SA, WA, QLD, NSW. The New York sequence is baseline surveillance, so likely not directly travel-related. 
At the moment, this is the largest XBB lineage that has both an S:452 and an S:455 mutation.

**Comment by FedeGueli** [comment]
@corneliusroemer proposed directly here you have to add the milestone

**Comment by corneliusroemer** [comment]
Surprise appearance in South Africa, two times

At 59 sequences now in GISAID, not massively fast but also not bad
