### ISSUE TITLE
EG.5.1.1 on A23539T branch with S:L455F (264 seqs, mainly in Australia, 10 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2360]
_Taken from **Branch 48** of Multitask sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** `EG.5.1.1` > `A23539T(S:S659S)` > `G22927T(S:L455F)`
**Query:** `G13627A, G22927T, A23539T, -A708C, -T899C, -C2662T, -C4686T, -C10015T, -T12865C, -G22332A`
**Earliest seq:** 2023-08-16 (`EPI_ISL_18141107`, Singapore)
**Latest seq:** 2023-10-22 (`EPI_ISL_18440472`, Netherlands)
**Sampled Countries:** Australia (32: NSW/14; SA/8; QLD/4; VIC/3; TAS/1; WA/1), China (10: SC/4; HB/2; SH/2; FJ/1; XJ/1), New Zealand (9), Singapore (4), Netherlands (3), USA (2), France (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18141107, EPI_ISL_18246326, EPI_ISL_18278997, EPI_ISL_18279955, EPI_ISL_18292475, EPI_ISL_18300669, EPI_ISL_18307132, EPI_ISL_18320781, EPI_ISL_18324527, EPI_ISL_18324537, EPI_ISL_18324951, EPI_ISL_18346779, EPI_ISL_18346805, EPI_ISL_18346818, EPI_ISL_18347516, EPI_ISL_18347639, EPI_ISL_18347703-18347704, EPI_ISL_18347710, EPI_ISL_18352381, EPI_ISL_18355046, EPI_ISL_18360352, EPI_ISL_18365605, EPI_ISL_18365672, EPI_ISL_18365874, EPI_ISL_18376439, EPI_ISL_18388898, EPI_ISL_18396188, EPI_ISL_18411419, EPI_ISL_18411467, EPI_ISL_18411551, EPI_ISL_18411564, EPI_ISL_18411674, EPI_ISL_18411695, EPI_ISL_18423924, EPI_ISL_18427871, EPI_ISL_18428112, EPI_ISL_18435043, EPI_ISL_18438373, EPI_ISL_18440466, EPI_ISL_18440472, EPI_ISL_18440476, EPI_ISL_18442757, EPI_ISL_18442774, EPI_ISL_18447732, EPI_ISL_18454463, EPI_ISL_18454489, EPI_ISL_18457508, EPI_ISL_18459380, EPI_ISL_18459604, EPI_ISL_18459721, EPI_ISL_18459855, EPI_ISL_18459912, EPI_ISL_18459940, EPI_ISL_18461585, EPI_ISL_18461782, EPI_ISL_18461792, EPI_ISL_18461895, EPI_ISL_18461916, EPI_ISL_18461956, EPI_ISL_18464115`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e62_757100.json?label=id:node_3495970
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/0c8ae009-2418-4dc0-91ad-5509025355a1)

**Trivia:**
-  Please check potential misplacement: it seems only one seqs preceeding `S:L455F` branch, being `Sichuan/BZCDC-043/2023|EPI_ISL_17988879|2023-06-12`; however the mutations on the follow-up sub-branch `G571A, C2263A, A28959G` are "unique" to the EG.5.1.1* tree which may support it be a different lineage than `HK.3`.

**Comment by AngieHinrichs** [comment]
> Please check potential misplacement: it seems only one seqs preceeding S:L455F branch, being Sichuan/BZCDC-043/2023|EPI_ISL_17988879|2023-06-12; however the mutations on the follow-up sub-branch G571A, C2263A, A28959G are "unique" to the EG.5.1.1* tree which may support it be a different lineage than HK.3.

Yes, I think it is plausible that this is yet another independent G22927T (S:L455F) in EG.5.1.1, distinct from HK.3.

**Comment by FedeGueli** [comment]
80 now it seems fast.

**Comment by aviczhl2** [comment]
115 now

**Comment by FedeGueli** [comment]
118 now 10% in Tasmania in October

**Comment by FedeGueli** [comment]
![Schermata 2023-11-23 alle 13 41 14](https://github.com/cov-lineages/pango-designation/assets/87669813/e3283826-3c7c-40b3-bb20-108e4a115c14)

![Schermata 2023-11-23 alle 13 42 17](https://github.com/cov-lineages/pango-designation/assets/87669813/80496fd9-93fd-4c49-8e7b-20d543696e06)


137 now 97 in the branch with N:Q229R and 78 with further spike mutation S:G1267R i suggest a designation for this or at least for the G1267R branch.

**Comment by DailyCovidCases** [comment]
Please close this issue
