### ISSUE TITLE
JF.1 sublineage with ORF1a:S2030L (>900 seq) and a further sublineage with ORF1a:P2005S, S:A475V, ORF10:V30I (29 seq. Canada)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#2361]
Defining mutations: JF.1 then ORF1a:S2030L(C6354T)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AJF.1*%26ORF1a%3AS2030L&
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6f04_94f520.json?c=gt-S_475&gmax=25384&gmin=21563&label=id:node_3289868
![1](https://github.com/cov-lineages/pango-designation/assets/115189228/986c9799-06e8-42b3-a607-e4ce91e7ed86)
Defining mutations of the S:A475V subbranch: JF.1 then ORF1a:S2030L(C6354T) then nuc:C3874T then ORF10:V30I(G29645A) then ORF1a:P2005S(C6278T)+S:A475V(C22986T)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AJF.1*%26ORF1a%3AP2005S%26S%3AA475V&
![2](https://github.com/cov-lineages/pango-designation/assets/115189228/a59d7aea-33cc-4036-89e5-538e0ea0ad44)

**Comment by corneliusroemer** [comment]
Just Canada, doesn't seem to grow, closing for now
