### ISSUE TITLE
EG.5.1.1 with ORF1a:T568I (nsp2_T388I), ORF1b:Q2181H (nsp15_Q130H), S:L455F (via G22927C) and ORF8:S67F (238 seqs, 22 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2366]
_Taken from **Branch 53** of multitask sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** `EG.5.1.1` > `C27741T` > `C1912T, C1968T(ORF1a:T568I), T7111C, A20010T(ORF1b:Q2181H), T20592C, G22927C(S:L455F), C28093T(ORF8:S67F)`
**Query:** `C6541T, G22927C, C27741T`
**Earliest seq:** 2023-08-28 (`EPI_ISL_18345224`, Cork, Ireland)
**Latest seq:** 2023-10-23 (`EPI_ISL_18471085`, Connecticut, USA)
**Sampled Countries:** UK (17: EN/16; WS/1), USA (14: NY/3; NJ/2; TX/2; UT/2; AZ/1; CA/1; CT/1; MN/1; OH/1), Ireland (9), Canada (4: ON/3; BC/1), Denmark (2), France (2), China (2: SC/1; ex. Spain/1), Belgium (1), South Korea (1), Netherlands (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18250090, EPI_ISL_18284832, EPI_ISL_18290882, EPI_ISL_18290915, EPI_ISL_18308328, EPI_ISL_18308339, EPI_ISL_18315360, EPI_ISL_18321565, EPI_ISL_18332107, EPI_ISL_18332505, EPI_ISL_18345224, EPI_ISL_18354139, EPI_ISL_18362839, EPI_ISL_18362880-18362881, EPI_ISL_18362951, EPI_ISL_18375850, EPI_ISL_18377642, EPI_ISL_18385706, EPI_ISL_18385720, EPI_ISL_18385728, EPI_ISL_18385734, EPI_ISL_18388184, EPI_ISL_18388760-18388761, EPI_ISL_18389241, EPI_ISL_18398829, EPI_ISL_18399988, EPI_ISL_18400877, EPI_ISL_18403587, EPI_ISL_18403998, EPI_ISL_18407932, EPI_ISL_18416430, EPI_ISL_18416450, EPI_ISL_18420893, EPI_ISL_18420911, EPI_ISL_18422267, EPI_ISL_18427521, EPI_ISL_18429173, EPI_ISL_18429518, EPI_ISL_18430506, EPI_ISL_18433870, EPI_ISL_18438642, EPI_ISL_18442008, EPI_ISL_18443922, EPI_ISL_18448322, EPI_ISL_18452961, EPI_ISL_18456955, EPI_ISL_18467439, EPI_ISL_18467445, EPI_ISL_18467479, EPI_ISL_18471085, EPI_ISL_18475314`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2eee6_b4b600.json?label=id:node_3484946
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/7a31b77c-042f-44ee-b8fc-0e102b4632b7)

**Comment by FedeGueli** [comment]
172 now

**Comment by DailyCovidCases** [comment]
Please close this issue
