### ISSUE TITLE
EG.5.1.1 with S:T470N, with further S:D796H (32 seqs, 10 countries), and a sub-branch with S:N450K (5 seqs, Canada)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2367]
_Taken from **Branch 2** of Multitask sars-cov-2-variants/lineage-proposals#1014 , Mostly with one of the `B.1.1.529` definition changing `S:D796H (D>Y>H) / G23948C (G>T>C)`_

**Defining Mutations:** `EG.5.1.1` > `C21306T` > `C22971A(S:T470N)`
**Query:** `C6541T, G13627A, C21306T, C22971A`
**Earliest seq:** 2023-08-08 (`EPI_ISL_18213963`, South Korea)
**Latest seq:** 2023-10-29 (`EPI_ISL_18470605`, Ontario, Canada)
**Sampled Countries:** Australia (7: QLD/6; SA/1), Canada (7: ON), USA (6: MN/2; CA; TX; UT; WA), Italy (4), UK (2: EN), Spain (2), China (1, MO), France (1), South Korea (1), Sweden (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18138048, EPI_ISL_18213963, EPI_ISL_18277441, EPI_ISL_18296533, EPI_ISL_18322922, EPI_ISL_18335701, EPI_ISL_18392772, EPI_ISL_18395635, EPI_ISL_18400833, EPI_ISL_18410941, EPI_ISL_18410950-18410951, EPI_ISL_18411001, EPI_ISL_18412979, EPI_ISL_18423795, EPI_ISL_18427023, EPI_ISL_18427296, EPI_ISL_18430448, EPI_ISL_18435019, EPI_ISL_18435032, EPI_ISL_18448040, EPI_ISL_18450374, EPI_ISL_18451074, EPI_ISL_18451085, EPI_ISL_18451090, EPI_ISL_18451107, EPI_ISL_18453604, EPI_ISL_18453665, EPI_ISL_18468308, EPI_ISL_18468315, EPI_ISL_18470605, EPI_ISL_18471631`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2415c_b7b6c0.json?f_userOrOld=uploaded%20sample
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/fa266903-c9af-4b6b-8b38-b6a57a9c946b)

**Trivia:**
- A sub-branch with `S:N450K/T22912G` emerged, phylogenetic order follows: `Main proposal` > `C20016T, T23948C(S:D796H)` > `G4207T` > `G4076A(ORF1a:V1271I)` > `T22912G/S:N450K` , query for it: `G4076A, G4207T, T22912G`. `S:N450K` is less popolar than `S:N450D/A22910G`, only sampled about 2.1k times during the whole pandemic, recent designated lineage with it being `GY.4 (XBB.1.16.2.4)`

**Comment by corneliusroemer** [comment]
Designated as HK.21
