### ISSUE TITLE
HK.3.2 sublineage with S:R214H(128 sequences, 16 countries), most with S:I1221T(99)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2369]
Transferred from sars-cov-2-variants/lineage-proposals#955

HK.3.2> C10039T> C29555T> G22203A(S:R214H)> T25224C(S:I1221T)
Query: C853T, G22203A, C29555T(6 dropout)
Query: C2334T, G22203A, C29555T (3 dropout)
Query for S:I1221T branch: A405G, C853, T25224C(1 dropout)
Query for ORF1ab:G2265D branch: G7059A, C10543T

Earliest Sequence: 09-14 Singapore EPI_ISL_18306940
Latest Sequence: 01-12 Kagoshima, Japan EPI_ISL_18870027
Regions Detected:
**South Korea** 29, **China** 6(Sichuan 2, Shanghai 2[1 from Taiwan], Hong Kong 1, Xinjiang 1), **Japan** 5(Osaka 1, Okayama 1, Kagoshima 1, Saitama 1, Tokyo 1), **Singapore** 4(1 from China), **Malaysia** 2(Sarawak), **Thailand** 2(Bangkok),**Turkey** 1(Ankara);
**New Zealand** 29(Auckland 12, Manukau 11, Canterbury 3, Hutt Valley 1, Waikato 1, Waitemata 1), **Australia** 5(NSW 3, SA 1, WA 1);
**US** 14(Hawaii 6, Florida 2, NY 2, California 1, Maryland 1, Nebraska 1, Washington 1[SEA airport, from Japan]), **Canada** 8(Quebec);
**UK** 4(Wales 2, England 1, Scotland 1), **France** 2(IDF 1, Grand Est 1), **Austria** 1(Wien), **Germany** 1(Berlin)

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_20684_763510.json?c=country&label=id:node_11091714
![2023-12-03 (2)](https://github.com/cov-lineages/pango-designation/assets/38100637/f4b12615-0a14-4d38-a647-dd6f353517db)

<details><summary>Sequences:</summary>

EPI_ISL_18306940, EPI_ISL_18309458, EPI_ISL_18365612,
EPI_ISL_18366380, EPI_ISL_18373566, EPI_ISL_18402554,
EPI_ISL_18438950, EPI_ISL_18444964, EPI_ISL_18449268,
EPI_ISL_18473002, EPI_ISL_18478209, EPI_ISL_18485459,
EPI_ISL_18491839, EPI_ISL_18496078, EPI_ISL_18503972,
EPI_ISL_18505579, EPI_ISL_18511015, EPI_ISL_18511352,
EPI_ISL_18511402, EPI_ISL_18511453, EPI_ISL_18522309,
EPI_ISL_18529063, EPI_ISL_18530202, EPI_ISL_18535023,
EPI_ISL_18547793, EPI_ISL_18556655, EPI_ISL_18561619,
EPI_ISL_18561621, EPI_ISL_18561628, EPI_ISL_18561660,
EPI_ISL_18561743, EPI_ISL_18561758, EPI_ISL_18561802,
EPI_ISL_18561910, EPI_ISL_18561922, EPI_ISL_18561999-18562000,
EPI_ISL_18562105, EPI_ISL_18562164, EPI_ISL_18562178,
EPI_ISL_18562194, EPI_ISL_18562381, EPI_ISL_18562507,
EPI_ISL_18562621, EPI_ISL_18564317, EPI_ISL_18566674,
EPI_ISL_18566688, EPI_ISL_18578230, EPI_ISL_18578245,
EPI_ISL_18586313-18586314, EPI_ISL_18593074, EPI_ISL_18597029,
EPI_ISL_18597439, EPI_ISL_18605056, EPI_ISL_18613624,
EPI_ISL_18613670, EPI_ISL_18620912, EPI_ISL_18632616,
EPI_ISL_18633569, EPI_ISL_18633996, EPI_ISL_18643178,
EPI_ISL_18651082, EPI_ISL_18651871, EPI_ISL_18651923,
EPI_ISL_18654332, EPI_ISL_18654353, EPI_ISL_18661661,
EPI_ISL_18670801, EPI_ISL_18670897, EPI_ISL_18670919,
EPI_ISL_18671233, EPI_ISL_18671273, EPI_ISL_18671308,
EPI_ISL_18671390, EPI_ISL_18671542, EPI_ISL_18671573,
EPI_ISL_18671621, EPI_ISL_18671647, EPI_ISL_18672145,
EPI_ISL_18673083, EPI_ISL_18686768, EPI_ISL_18687310,
EPI_ISL_18688829, EPI_ISL_18720502, EPI_ISL_18728768,
EPI_ISL_18732946, EPI_ISL_18732961, EPI_ISL_18733483,
EPI_ISL_18739241, EPI_ISL_18752019-18752020, EPI_ISL_18752023-18752025,
EPI_ISL_18752028-18752031, EPI_ISL_18774844, EPI_ISL_18777898,
EPI_ISL_18777983, EPI_ISL_18777985, EPI_ISL_18791691-18791693,
EPI_ISL_18791868, EPI_ISL_18792071, EPI_ISL_18792161,
EPI_ISL_18823640, EPI_ISL_18847191, EPI_ISL_18858720,
EPI_ISL_18870027

</details>

**Comment by Over-There-Is** [comment]
Tokyo S:R214H without S:I1221T

**Comment by FedeGueli** [comment]
> Tokyo S:R214H without S:I1221T

is it basal to the tree?

**Comment by Over-There-Is** [comment]
> > Tokyo S:R214H without S:I1221T
> 
> is it basal to the tree?

Y

**Comment by Over-There-Is** [comment]
Thailand+1, without I1221T

**Comment by Over-There-Is** [comment]
NZ+17 CN+1

**Comment by Over-There-Is** [comment]
Quebec+2

**Comment by Over-There-Is** [comment]
KR+2

**Comment by Over-There-Is** [comment]
Singapore/R91MR120/2023|EPI_ISL_18651082|2023-12-07 K356T

**Comment by Over-There-Is** [comment]
Sarawak+2 Berlin+1

**Comment by FedeGueli** [comment]
This seems quite widespread in eastern asai i think it should be designated cc @corneliusroemer

**Comment by DailyCovidCases** [comment]
This branch is dead, please close this issue

**Comment by DailyCovidCases** [comment]
It seems that this branch has stopped growing. You should close this. @Over-There-Is

**Comment by DailyCovidCases** [comment]
@Over-There-Is Please close this issue
