### ISSUE TITLE
4 Potential sublineages of Delta

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#237]
**Proposed sublineage 1**
**Description**
**Sub-lineage of**: AY.4 (1202 sequences)
**Earliest sequence**: 2021/3/19(Slovakia)
**Most recent sequence**: 2021/10/1 (the UK)
**Countries circulating**: Bulgaria (404 sequences), Germany (310 sequences), Denmark (152 sequences), the UK (97 sequences), Slovakia (33 sequences), Czech Republic (23 sequences), and a few other European countries
**Mutations in addition to AY.4**:
S:L5F, ORF1a:A2529V, 
then ORF1b:V248F, 
then C22000T,
then S:S929T
**Genomes**:
[AY.4 S929T.csv](https://github.com/cov-lineages/pango-designation/files/7298882/AY.4.S929T.csv)
**Evidence**:
https://nextstrain.org/fetch/genome-euro.ucsc.edu/trash/ct/subtreeAuspice1_genome_euro_39b9_e5d800.json?c=gt-S_929&l=radial
![image](https://user-images.githubusercontent.com/86835836/136314764-f4e23df6-a217-4d89-bbc7-8f8a02f58787.png)

**Proposed sublineage 2**
**Description**
**Sub-lineage of**: B.1.617.2 (535 sequences)
**Earliest sequence**: 2021/7/12 (Reunion)
**Most recent sequence**: 2021/9/14 (Reunion)
**Countries circulating**: Reunion (523 sequences), France (12 sequences)
**Mutations in addition to B.1.617.2**: 
N:R385K, ORF1a:P309L, ORF1a:P1640L, ORF1a:H2092Y, ORF1a:A3209V, ORF1a:V3718A, ORF1b:H2285Y, ORF7a:L116F,
then N:L139F,
then ORF1a:I431M, ORF1b:M809V, 
then G2755T,
then S:D574Y,
then ORF8:S69L
**Genomes**:
[Delta S69L.csv](https://github.com/cov-lineages/pango-designation/files/7299237/Delta.S69L.csv)
**Evidence**:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12da5_c661c0.json?c=gt-nuc_28099&l=radial
![image](https://user-images.githubusercontent.com/86835836/136328778-4851be6a-fc79-4deb-bbd0-f1465e84e591.png)

**Proposed sublineage 3**
**Description**
**Sub-lineage of**: AY.23 (883 sequences)
**Earliest sequence**: 2021/8/22 (Singapore)
**Most recent sequence**: 2021/10/1 (Australia-QLD)
**Countries circulating**: Singapore (881 sequences)
Detected at border-entry: Hong Kong ex-Singapore (1 sequence), Australia ex-Singapore (1 sequence) 
**Mutations in addition to AY.23**:
A7537G, G17679T,
then C5497T, C12100T,
then ORF1a:T333M,
then A14748G,
then S:L1234I 
**Genomes**:
[AY.23 L1234I.csv](https://github.com/cov-lineages/pango-designation/files/7299413/AY.23.L1234I.csv)
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/136332970-3d14c829-47ab-49bb-bfe2-d78ece8aa68c.png)
https://nextstrain.org/fetch/genome-euro.ucsc.edu/trash/ct/subtreeAuspice1_genome_euro_1d0b1_e92000.json?c=gt-S_1234&l=radial
BTW, this proposed sublineage of AY.23 is growing fast, probably due to Singapore's ongoing outbreak:
![image](https://user-images.githubusercontent.com/86835836/136333769-3d752774-fa5e-42c3-b8b6-f8525cda0d70.png)

**Proposed sublineage 4**
**Description**
**Sub-lineage of**: B.1.617.2 (1375 sequences, 682 of them are misclassified as AY.4)
**Earliest sequence**: 2021/6 (Austria)
**Most recent sequence**: 2021/10 (Italy)
**Countries circulating**: Germany (613 sequences), Austria (232 sequencecs), Croatia (127 sequences), Slovenia (123 sequences), and a few other European countries
**Detected at border-entry**: Korea ex-the Netherlands (1 sequence)
**Mutations in addition to B.1.617.2**:
ORF1b:A1643V,
then S:G1167V,
then G9220A,
then ORF1b:K82R, 
then G7936T,
then ORF1b:I1257V, 
then ORF1a:K669N, 
then ORF1a:G519S and S:S477I,
then S:A262S
then ORF1b:P218S 
Genomes:
[Delta S477I.csv](https://github.com/cov-lineages/pango-designation/files/7301024/Delta.S477I.csv)
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/136355477-941f7774-5631-4a44-8f79-422a3ba51e8c.png)
https://nextstrain.org/fetch/genome-euro.ucsc.edu/trash/ct/subtreeAuspice1_genome_euro_65a5_eaae10.json?c=gt-nuc_14119&l=radial

**Comment by corneliusroemer** [comment]
I'm not sure I agree with AY.41, it's very deep right now and I think there should be a parent designated.

There's a big branch globally with ORF1b:1257V that reached 50% in Croatia and up to 20% in the US.

Croatia and US can be separated by mutations:
Croatia has among others S:1167V and US has one synonymous nuc:24208T, so I would designate two parents with ORF1b:1257V and then make this one proposed by @c19850727 a child of the Croatian one.
![image](https://user-images.githubusercontent.com/25161793/136995923-e7aa3ae0-c68d-4d2d-b312-98aaa613b7a5.png)
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22ORF1b%3A1257V%22]%7D%2C%22matchPercentage%22%3A1%7D


The Croatian/European one has: S:1167V and ORF1b:1257V, ORF1b:1643V (see country distribution here https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22ORF1b%3A1257V%22%2C%22S%3A1167V%22]%7D%2C%22matchPercentage%22%3A1%7D)
![image](https://user-images.githubusercontent.com/25161793/136996174-e34f2322-1019-4334-acca-df69804c8c71.png)

Right now it's green, but I'd propose to broaden to blue
![image](https://user-images.githubusercontent.com/25161793/136997507-48b9da58-5f02-4da0-9b98-6a498f46122a.png)

https://nextstrain.org/groups/neherlab/ncov/croatia?c=gt-ORF1b_1257,218&label=spike_mutations:I95T&m=div

**Comment by FedeGueli** [comment]
Hi @corneliusroemer and @chrisruis i didnt realize that one of the two sublineage,mentioned by Cornelius in the comment cited by me below, the one with nuc:24208T, has then been then designated AY.103 the dominant north american delta sublineage.

Not designating AY.41 starting  from S:1167V and ORF1b:1257V, ORF1b:1643V as suggested here by @corneliusroemer but deeper in the tree left undesignated a big part of this branch that has kept evolving accumulating mutations and circulating till week 5/ 2022 in Germany where i spotted it and proposed in #436 .


So in my view the best thing to do it is to broad AY.41 to the Cornelius' proposed definition S:1167V, ORF1b:1257V, ORF1b:1643V 

> I'm not sure I agree with AY.41, it's very deep right now and I think there should be a parent designated.
> 
> There's a big branch globally with ORF1b:1257V that reached 50% in Croatia and up to 20% in the US.
> 
> Croatia and US can be separated by mutations: Croatia has among others S:1167V and US has one synonymous nuc:24208T, so I would designate two parents with ORF1b:1257V and then make this one proposed by @c19850727 a child of the Croatian one. ![image](https://user-images.githubusercontent.com/25161793/136995923-e7aa3ae0-c68d-4d2d-b312-98aaa613b7a5.png) [https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22ORF1b%3A1257V%22]%7D%2C%22matchPercentage%22%3A1%7D](https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A%5B%22ORF1b%3A1257V%22%5D%7D%2C%22matchPercentage%22%3A1%7D)
> 
> The Croatian/European one has: S:1167V and ORF1b:1257V, ORF1b:1643V (see country distribution here [https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22ORF1b%3A1257V%22%2C%22S%3A1167V%22]%7D%2C%22matchPercentage%22%3A1%7D](https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A%5B%22ORF1b%3A1257V%22%2C%22S%3A1167V%22%5D%7D%2C%22matchPercentage%22%3A1%7D)) ![image](https://user-images.githubusercontent.com/25161793/136996174-e34f2322-1019-4334-acca-df69804c8c71.png)
> 
> Right now it's green, but I'd propose to broaden to blue ![image](https://user-images.githubusercontent.com/25161793/136997507-48b9da58-5f02-4da0-9b98-6a498f46122a.png)
> 
> https://nextstrain.org/groups/neherlab/ncov/croatia?c=gt-ORF1b_1257,218&label=spike_mutations:I95T&m=div
