### ISSUE TITLE
Proposal for new sublineage of BA.2.86.1 with additional mutations  S:N30G and S:G594S

### ISSUE THREAD

**Issue by AleksanderRing** [cov-lineages/pango-designation#2373]
## Proposal for new sublineage f BA.2.86.1with additional mutations  S:N30G and S:G594S

Countries detected: Denmark(10)

Earliest sequence: (dd-mm-yy) 19-09-23

Defining mutations: S:N30G and S:G594S

GISAID Query: Spike_N30G,Spike_G594S

![ba_evidence](https://github.com/cov-lineages/pango-designation/assets/102508994/903790cf-4a35-428c-a18f-986cc6607d4f)

![ba_evidence_grow](https://github.com/cov-lineages/pango-designation/assets/102508994/c67e4276-be91-4a93-9adc-bdfdee46111f)

10 sequences uploaded to GISAID and more have been sequenced pending upload to gisaid

EPI_ISL_18464651
EPI_ISL_18360504
EPI_ISL_18442971
EPI_ISL_18464562
EPI_ISL_18464624
EPI_ISL_18494612
EPI_ISL_18360400
EPI_ISL_18442913
EPI_ISL_18442950
EPI_ISL_18442871

**Comment by FedeGueli** [comment]
Hi @AleksanderRing it is already preproposed by @ryhisner in the pre proposal repo : https://github.com/sars-cov-2-variants/lineage-proposals/issues/1076

**Comment by corneliusroemer** [comment]
Thanks for giving a heads up! I've designated the parent lineage with 594S as JN.7, the child can be designated as well if it grows

**Comment by DailyCovidCases** [comment]
This branch is dead, please close this issue
