### ISSUE TITLE
HK.3.2 subbranch with Orf8:M1L(35 sequences, 11 countries),  most with S:N185D (33)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2374]
Transferred from sars-cov-2-variants/lineage-proposals#867

HK.3.2> C100T> G7290A(Orf1a:G2342E)> C1348T, T25496C(Orf3a:I35T), A27894T(Orf8:M1L)> C4543T, A22115G(S:N185D)
Query: C853T, A27894T
Query for S:N185D branch: A22115G, A27894T

2 with further S:P621S

Earliest Sequence: 09-11 Xining, Qinghai, China EPI_ISL_18268266
Latest Sequence: 11-11 Tasmania, Australia EPI_ISL_18510954
Regions Detected:
**Australia** 11(NSW 8, SA 2, Tasmania 1), **New Zealand** 1(Auckland); 
**US** 7(Minnesota 2, Washington 2[from **Japan**], California 1, Florida 1, New Jersey 1), **Canada** 3(Ontario 2, Alberta 1);
**Sweden** 3(Västra Götaland), **France** 2(ARA 1, IDF 1), **Greece** 2(Peloponnesus 1, Western Greece 1), **Netherlands** 1(Noord Holland), **UK** 1(England);
**China** 4(Hong Kong 2, Hubei 1, Qinghai 1);

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_20684_763510.json?label=id:node_10923271
![2023-11-15 (1)](https://github.com/cov-lineages/pango-designation/assets/38100637/2d45c2d8-ee37-4656-b81c-692b1e7c23ab)

<details><summary>Sequences:</summary>

EPI_ISL_18268266, EPI_ISL_18306770, EPI_ISL_18388903,
EPI_ISL_18394411, EPI_ISL_18412334, EPI_ISL_18441055,
EPI_ISL_18447191, EPI_ISL_18453668, EPI_ISL_18453678,
EPI_ISL_18455951, EPI_ISL_18459205, EPI_ISL_18461762,
EPI_ISL_18461777, EPI_ISL_18461976, EPI_ISL_18463892,
EPI_ISL_18463919, EPI_ISL_18471634, EPI_ISL_18472086,
EPI_ISL_18484253, EPI_ISL_18484264, EPI_ISL_18490880,
EPI_ISL_18490950, EPI_ISL_18497161, EPI_ISL_18498645,
EPI_ISL_18510699, EPI_ISL_18510954, EPI_ISL_18513303,
EPI_ISL_18513402, EPI_ISL_18513444, EPI_ISL_18513683,
EPI_ISL_18513925, EPI_ISL_18522530, EPI_ISL_18528730,
EPI_ISL_18532585, EPI_ISL_18536266
</details>

**Comment by corneliusroemer** [comment]
Bit small for now

**Comment by Over-There-Is** [comment]
Sydney +5

**Comment by FedeGueli** [comment]
Designated HK.3.2.2 via https://github.com/cov-lineages/pango-designation/commit/a699198d41ab8151456c85f81f27dfd2888ca517

**Comment by Walde1nsamkeit** [comment]
Orf8:MNHHNCSCISPRM (started at 27914)

By @ryhisner:
> Interesting. At first, this looks like a handy way to get rid of the wasteful production of the first seven ORF8 AA residues. But the next start codon actually overlaps ORF8:G8* and would result in a 14-AA peptide instead of the current 7-AA one.
> 
> <img alt="Image" width="1497" height="271" src="https://private-user-images.githubusercontent.com/33738461/463937000-e5e29342-26fc-4da3-a9f8-14f6b2167773.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIwMjg0MTAsIm5iZiI6MTc1MjAyODExMCwicGF0aCI6Ii8zMzczODQ2MS80NjM5MzcwMDAtZTVlMjkzNDItMjZmYy00ZGEzLWE5ZjgtMTRmNmIyMTY3NzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA5VDAyMjgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmOTZiM2ZkMDI5ZTVjODdhODJjYjQ2YzlhMDM2ODU5NjVkY2U3ZDI0ODIxZTExMTc5ZDk1ODdlNjIyODJjMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XluOJbJjuOe9c7QR3Kb4_4J4tnx4q09mOs_al9HF2LU">
> The Kozak sequence for that start codon is pretty miserable though, so there maybe be some leaky scanning and use of the next start codon (with a good Kozak sequence) at 27950-27952, and that one very efficiently leads directly to a stop codon: M*.
