### ISSUE TITLE
JG.3 (EG.5.1.3.3) with S:N450D (47 seqs, mainly in Canada, 7 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2376]
_Transferred from sars-cov-2-variants/lineage-proposals#1036_

**Defining Mutations:** `JG.3` > `A22910G(S:N450D)`
**Query:** `C1889T, C7086T, A22910G`
**Earliest seq:** 2023-09-25 (`EPI_ISL_18389298`, Denmark)
**Latest seq:** 2023-10-25 (`EPI_ISL_18445218`, Singapore, travel history: USA)
**Sampled Countries:** Canada (40: ON), USA (2: CA; NY), Australia (1: SA), Denmark (1), France (1), Japan (1), Singapore (1, ex. USA)

<details><summary>Genomes: </summary>

`EPI_ISL_18389298, EPI_ISL_18416588, EPI_ISL_18427335, EPI_ISL_18427349, EPI_ISL_18445218, EPI_ISL_18448124, EPI_ISL_18448534, EPI_ISL_18448610-18448611, EPI_ISL_18448770, EPI_ISL_18448872, EPI_ISL_18470401, EPI_ISL_18470584, EPI_ISL_18471347, EPI_ISL_18471658, EPI_ISL_18471749, EPI_ISL_18472011, EPI_ISL_18485152, EPI_ISL_18496011, EPI_ISL_18496759, EPI_ISL_18497819, EPI_ISL_18504364, EPI_ISL_18504413, EPI_ISL_18504575, EPI_ISL_18504583, EPI_ISL_18504635, EPI_ISL_18504695, EPI_ISL_18504787, EPI_ISL_18504907, EPI_ISL_18504980-18504981, EPI_ISL_18504988-18504989, EPI_ISL_18505087, EPI_ISL_18505090, EPI_ISL_18505143, EPI_ISL_18505195, EPI_ISL_18505314, EPI_ISL_18505388, EPI_ISL_18505409, EPI_ISL_18505417, EPI_ISL_18505419, EPI_ISL_18505421-18505423, EPI_ISL_18505426, EPI_ISL_18505428`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4a5_5e4050.json?f_userOrOld=uploaded%20sample&label=id:node_3537250
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/17a2c6c5-b726-434b-b95e-7ac5285582a1)

**Comment by jasondorjeshort** [comment]
JG.3 is one of the fastest-growing lineages currently - on pace to be one of the ~5 most prevalent in the US within a month, and one of the few competitive with JN.1 (of course there is huge uncertainty in such fits, but JG.3 has over 100 sequences now). Assigning any sub-lineages quickly, especially the ones with not-previously-successful escape mutations, would be a good idea.

![United States-1-log-voc-exact-all](https://github.com/cov-lineages/pango-designation/assets/17172327/5722c91e-9bc8-415e-8fef-971811a0a4e3)
