### ISSUE TITLE
FD.1.1 with ORF1b:H1807Y, S:F157L, N:T379I, N:H300Y and S:L455W (27 seqs, Spain, UK, Netherlands, USA) 

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2379]
Transferred from sars-cov-2-variants/lineage-proposals#967

**Defining Mutations:** `FD.1.1 (XBB.1.5.15.1.1)` > `C18886T(ORF1b:H1807Y/nsp14_H283Y)` > `C22033A(S:F157L)` > `A17817G` > `C29409T(N:T379I)` > `C29171T(N:H300Y)` > `T22926G(S:L455W)`, many with follow-up `A29373G(N:E367G)` > `C6606T(ORF1a:S2114F/nsp3_S1296F)`
**Query:** `A17817G, C22033A, T22926G`
**Earliest seq:** 2023-07-31 (`EPI_ISL_18112788`, Ribeira, Galicia, Spain)
**Latest seq:** 2023-11-07 (`EPI_ISL_18514496`, England, UK)
**Sampled Countries:** UK (11: EN), Spain (10: GA/6; AN; CL; MC; MD)

<details><summary>Genomes: </summary>

`EPI_ISL_18112788, EPI_ISL_18388510, EPI_ISL_18391250, EPI_ISL_18400383, EPI_ISL_18412413, EPI_ISL_18436070, EPI_ISL_18436095, EPI_ISL_18453737, EPI_ISL_18457955, EPI_ISL_18457966, EPI_ISL_18466925, EPI_ISL_18497057-18497060, EPI_ISL_18497064, EPI_ISL_18497137, EPI_ISL_18497139, EPI_ISL_18497490, EPI_ISL_18509533, EPI_ISL_18514496`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3439c_886410.json?label=id:node_3928901
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/2b65057c-6868-4f67-a326-65682e4f89f1)

**Comment by corneliusroemer** [comment]
Hmm, basically dead, already around for a long time (>2 months) with that genotype yet not much growth

**Comment by FedeGueli** [comment]
> Hmm, basically dead, already around for a long time (>2 months) with that genotype yet not much growth

It doesn't look dead @corneliusroemer 4 samples from 2 countries in November and 11/21 samples in the last 25 days. But agree it is not super fast, still maybe worth a designation in my view , also i think the triple N mutation in that region could give  NGTF for PCR and maybe also interact negatively with some antigenic LFT.

**Comment by FedeGueli** [comment]
last sample is recent from Nov 24 from Netherlands

**Comment by FedeGueli** [comment]
Still not in January, lets see if it has survived!
