### ISSUE TITLE
JD.1.1+Orf7b:L32F+S:E554G(47 seqs, 5 countries, 9 with S:V483F, 3% NSW)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2380]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1056

JD.1.1+C27849T(Orf7b:L32F)+T5303C+A23223G,C29245T(S:E554G)

GISAID query: A23223G,C29245T
No. of seqs: 47(Australia 43 Germany 1 New Zealand 1 Greece 1 South Korea 1)

First: EPI_ISL_18324743, 2023-9-20
Latest: EPI_ISL_18513929, 2023-11-6

20/752=3% in NSW from 10-20

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jd_1_1_e554g.json?label=id:node_3650749)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/c75b06ca-e646-4e71-92a1-65ef9e00da87)

**Comment by corneliusroemer** [comment]
JD.1.1.4
