### ISSUE TITLE
JN.1 Branches

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2381]
transferred: https://github.com/sars-cov-2-variants/lineage-proposals/issues/987 
- [x] JN.1 + ORF1a:F499L (712)
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/7979d8ab-175e-41e1-9ba3-7f9a48dee402)
- [ ] JN.1 + ORF1a:T170I (4424)
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/95c7689c-f23f-4938-a19b-88aa6db96bd1)

**Comment by Fearuncle** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/9723ed6c-0660-4791-bab3-57cafd6622d0)
JN.1 + ORF1a:T170I has a 20% growth advantage over JN.1

**Comment by Fearuncle** [comment]
JN.1 + ORF1a:T170I now has a growth advantage of 32% over jn.1

**Comment by corneliusroemer** [comment]
it looks like 499L is deleterious, hence everything else will appear beneficial.

**Comment by FedeGueli** [comment]
It could be even if this would be the same for all linegaes while it doesnt seem so: https://cov-spectrum.org/collections/188
![Schermata 2023-12-01 alle 09 50 29](https://github.com/cov-lineages/pango-designation/assets/87669813/f1972072-6a7e-43e1-a5f0-3f508344715f)

**Comment by Mydtlwn** [comment]
JN.1 +ORF1a:T170I @corneliusroemer

**Comment by Fearuncle** [comment]
JN.1 +ORF1a:T170I passed 1300 seq.

**Comment by Fearuncle** [comment]
JN.1+ ORF1a:T170I passed 2000 seq.

**Comment by FedeGueli** [comment]
> JN.1+ ORF1a:T170I passed 2000 seq.

@corneliusroemer ping for branch designation.

**Comment by Fearuncle** [comment]
passed 3000

**Comment by Fearuncle** [comment]
passed 4000

**Comment by FedeGueli** [comment]
@corneliusroemer S:T170I should be designated consoider that JN.1 is already quite big (22k seqs) and it has 4 sublineages only.
