### ISSUE TITLE
(XDF/XCM recomb)/(FL.20.1+S:T732I,K1191N) recombinant (16 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2382]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1050

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/f0bb7aea-e177-464f-a1a1-21c9bf1f93b7)

[(XBB/EG.5.1.3 recomb)/XCM recomb](https://github.com/sars-cov-2-variants/lineage-proposals/issues/944)--[FL.20.1+S:T732I,K1191N](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1049)
Breakpoint between 19984 and 21717

Additional mutations: T17220C

GISAID query: C1387T,T3453C, T17220C
No.of seqs: 9(Germany 4 Spain 4 Switzerland 1)

First: EPI_ISL_18455079, 2023-10-8, Germany
Latest: EPI_ISL_18525777, 2023-11-2, Germany

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/multi-recomb.json?c=gt-ORF1ab_24&label=id:node_3368141)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/ed956c44-4d93-45ef-83a5-9a800519d4ab)

[usher for (XBB/EG.5.1.3 recomb)/XCM recomb donor](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/multi-recomb-0.json?label=id:node_11117183)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/31f33630-6f13-4af8-abbb-6a889c4cc27c)

[usher for the (XBB/EG.5.1.3 recomb) ](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f4d9_cfa190.json?branchLabel=nuc%20mutations&c=gt-nuc_11782&gmax=12782&gmin=10782)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/7a639fae-4ca8-4fb7-bf2c-2e7880f2cc72)

**Comment by aviczhl2** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/fcd3c4c1-2799-437a-9378-0c94eacddd14)

Recomb tower of this variant.

Related issues:

https://github.com/sars-cov-2-variants/lineage-proposals/issues/1088

https://github.com/sars-cov-2-variants/lineage-proposals/issues/944

https://github.com/sars-cov-2-variants/lineage-proposals/issues/1050

**Comment by corneliusroemer** [comment]
9 sequences is a bit small, Spain/Switzerland/Germany are not super undersampled so I'll hold off on this one for now

**Comment by aviczhl2** [comment]
+2 Germany

**Comment by aviczhl2** [comment]
+1 Germany

**Comment by aviczhl2** [comment]
+2 Netherlands

**Comment by aviczhl2** [comment]
One more from Switzerland

**Comment by aviczhl2** [comment]
+1 Germany

**Comment by yatisht** [comment]
This seems to correspond to node_1089047 on the Dec 17 update of RIVET (https://rivet.ucsd.edu/). 

```
Recombinant Origin Date: 2023-10-14
Recombinant Between: FL.20.1 and XBB.1
Number Sequences: 16
```

Descendants (16 sequences):
```
Spain/IB-HUSE-08920/2023|EPI_ISL_18446890|2023-10-24
Germany/SN-RKI-I-1138763/2023|EPI_ISL_18455102|2023-10-16
Switzerland/BS-UHB-USB_2023_11_07_c551e258/2023|OY770255.1|2023-10-25
Germany/BY-MVP-000022371/2023|EPI_ISL_18540579|2023-11-06
Switzerland/AG-UZH-IMV-3ba6c1b7/2023|OY973705.1|2023-12-01
Germany/SN-RKI-I-1138739/2023|EPI_ISL_18455079|2023-10-08
Germany/SN-RKI-I-1139624/2023|EPI_ISL_18570357|2023-11-01
Germany/BY-MVP-000022291/2023|EPI_ISL_18525777|2023-11-02
Germany/BY-MVP-000022493/2023|EPI_ISL_18632962|2023-11-16
Germany/SN-RKI-I-1138766/2023|EPI_ISL_18455105|2023-10-16
Germany/BY-MVP-000022414/2023|EPI_ISL_18540595|2023-11-06
Spain/IB-HUSE-08866/2023|EPI_ISL_18446872|2023-10-14
Spain/IB-HUSE-08914/2023|EPI_ISL_18446854|2023-10-15
Spain/IB-HUSE-08868/2023|EPI_ISL_18446906|2023-10-17
Netherlands/NH-RIVM-133412/2023|EPI_ISL_18576880|2023-11-14
Netherlands/NH-RIVM-133413/2023|EPI_ISL_18576881|2023-11-11
```

SNV plot:
![node_1089047_trio](https://github.com/cov-lineages/pango-designation/assets/34664884/587607e3-afbe-40bf-a841-29e5ed932c39)

UShER subtree (takes a minute to load): [link](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace?db=wuhCor1&subtreeSize=1000&phyloPlaceTree=hgPhyloPlaceData/wuhCor1/public.plusGisaid.latest.masked.pb&namesOrIds=Spain%2FIB-HUSE-08914%2F2023%7CEPI_ISL_18446854%7C2023-10-15%0AGermany%2FBY-MVP-000022291%2F2023%7CEPI_ISL_18525777%7C2023-11-02%0ANetherlands%2FNH-RIVM-133413%2F2023%7CEPI_ISL_18576881%7C2023-11-11%0AGermany%2FSN-RKI-I-1139624%2F2023%7CEPI_ISL_18570357%7C2023-11-01%0ASpain%2FIB-HUSE-08920%2F2023%7CEPI_ISL_18446890%7C2023-10-24%0AGermany%2FSN-RKI-I-1138766%2F2023%7CEPI_ISL_18455105%7C2023-10-16%0AGermany%2FBY-MVP-000022371%2F2023%7CEPI_ISL_18540579%7C2023-11-06%0ANetherlands%2FNH-RIVM-133412%2F2023%7CEPI_ISL_18576880%7C2023-11-14%0AGermany%2FBY-MVP-000022493%2F2023%7CEPI_ISL_18632962%7C2023-11-16%0AGermany%2FSN-RKI-I-1138763%2F2023%7CEPI_ISL_18455102%7C2023-10-16)

We will look into why the parent lineages don't match XDF/XCM.

**Comment by aviczhl2** [comment]
> We will look into why the parent lineages don't match XDF/XCM.

The parent is an XDF/XCM recomb, not XDF or XCM.

**Comment by FedeGueli** [comment]
> Yes, RIVET is predicting FL.20.1 and XBB.1 as the two parental lineages.

likely being the donor an undesignated recombination it shows back the ancestor XBB.1

**Comment by aviczhl2** [comment]
No new seqs
