### ISSUE TITLE
XBB.1.16 with S:V1230A, ORF1a:S994N (nsp3_S994N), S:Q613H and S:Q675K (331 seqs, mainly in Russia, 19 countries) 

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2383]
_Transferred from sars-cov-2-variants/lineage-proposals#1000_

**Defining Mutations:**  `XBB.1.16` > `T13518C` > `T17250G` > `T25251C(S:V1230A)` > `G3246A(ORF1a:S994N), G23401T(S:Q613H), C23585A(S:Q675K)`
**Query:** `T13518C, T17250G , G23401T`
**Earliest seq:** 2023-07-28 (`EPI_ISL_18417219`, Kovylkino, Mordovia, Russia)
**Latest seq:** 2023-11-08 (`EPI_ISL_18519534`, Noord-Holland, Netherlands)
**Sampled Countries:** Russia (174: SPE/131; MOW/19; ME/12; VOR/4; MO/2; TYU/2; AST/1; SAM/1; SAR/1; SVE/1), Denmark (4), Netherlands (2), USA (2: FL; UT), Austria (1), Belgium (1), Canada (1: BC), China (2: SH/1; ex. Russia/1), Finland (1), Italy (1), Kazakhstan (1), Spain (1), Sweden (1), Ukraine (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18078437, EPI_ISL_18238343-18238344, EPI_ISL_18238350, EPI_ISL_18238352, EPI_ISL_18317229, EPI_ISL_18360222, EPI_ISL_18406327, EPI_ISL_18411852, EPI_ISL_18416733, EPI_ISL_18416738-18416739, EPI_ISL_18416759, EPI_ISL_18416762, EPI_ISL_18416859, EPI_ISL_18416865, EPI_ISL_18416869, EPI_ISL_18416881, EPI_ISL_18416885-18416886, EPI_ISL_18416893, EPI_ISL_18416900, EPI_ISL_18416914, EPI_ISL_18416923, EPI_ISL_18416925, EPI_ISL_18416937, EPI_ISL_18416953-18416954, EPI_ISL_18416956, EPI_ISL_18417026, EPI_ISL_18417094, EPI_ISL_18417100-18417101, EPI_ISL_18417103, EPI_ISL_18417106, EPI_ISL_18417112-18417113, EPI_ISL_18417121, EPI_ISL_18417136, EPI_ISL_18417146, EPI_ISL_18417160-18417161, EPI_ISL_18417170, EPI_ISL_18417179, EPI_ISL_18417187, EPI_ISL_18417189, EPI_ISL_18417192, EPI_ISL_18417195, EPI_ISL_18417208, EPI_ISL_18417210, EPI_ISL_18417213, EPI_ISL_18417219-18417220, EPI_ISL_18417355, EPI_ISL_18417366, EPI_ISL_18417370, EPI_ISL_18417381, EPI_ISL_18417384-18417385, EPI_ISL_18417387, EPI_ISL_18417389, EPI_ISL_18417397, EPI_ISL_18417405, EPI_ISL_18417411, EPI_ISL_18417415, EPI_ISL_18417419, EPI_ISL_18417424, EPI_ISL_18417426, EPI_ISL_18417468, EPI_ISL_18417569, EPI_ISL_18417610, EPI_ISL_18438692, EPI_ISL_18458516, EPI_ISL_18462771, EPI_ISL_18472318, EPI_ISL_18475131, EPI_ISL_18481151, EPI_ISL_18484316, EPI_ISL_18486934, EPI_ISL_18486938-18486939, EPI_ISL_18486941, EPI_ISL_18486952, EPI_ISL_18486957-18486958, EPI_ISL_18486960, EPI_ISL_18486964, EPI_ISL_18486978, EPI_ISL_18486987, EPI_ISL_18487006, EPI_ISL_18487025, EPI_ISL_18487030-18487031, EPI_ISL_18487047, EPI_ISL_18487059, EPI_ISL_18487061, EPI_ISL_18487068, EPI_ISL_18487112, EPI_ISL_18487116, EPI_ISL_18487143, EPI_ISL_18487155, EPI_ISL_18487162, EPI_ISL_18487174, EPI_ISL_18487183, EPI_ISL_18487190, EPI_ISL_18487232, EPI_ISL_18487240, EPI_ISL_18487252, EPI_ISL_18487254, EPI_ISL_18487284, EPI_ISL_18487312, EPI_ISL_18487331, EPI_ISL_18487346, EPI_ISL_18487363, EPI_ISL_18487365, EPI_ISL_18487369, EPI_ISL_18487372-18487373, EPI_ISL_18487376, EPI_ISL_18487381-18487382, EPI_ISL_18487386, EPI_ISL_18487389, EPI_ISL_18487391, EPI_ISL_18487393, EPI_ISL_18487396, EPI_ISL_18487402, EPI_ISL_18487408, EPI_ISL_18487414, EPI_ISL_18487426-18487427, EPI_ISL_18487438, EPI_ISL_18487444, EPI_ISL_18487447, EPI_ISL_18487452, EPI_ISL_18487460, EPI_ISL_18487479, EPI_ISL_18487481, EPI_ISL_18487484, EPI_ISL_18487488, EPI_ISL_18487515, EPI_ISL_18487522-18487524, EPI_ISL_18487541, EPI_ISL_18487564, EPI_ISL_18487566-18487567, EPI_ISL_18487571-18487572, EPI_ISL_18487574, EPI_ISL_18487577, EPI_ISL_18487579, EPI_ISL_18487582, EPI_ISL_18487587, EPI_ISL_18487598, EPI_ISL_18487600, EPI_ISL_18487603, EPI_ISL_18487608, EPI_ISL_18487617, EPI_ISL_18487623, EPI_ISL_18487632, EPI_ISL_18487639, EPI_ISL_18487671-18487672, EPI_ISL_18487676, EPI_ISL_18487694, EPI_ISL_18487724, EPI_ISL_18487738, EPI_ISL_18487741, EPI_ISL_18487744-18487745, EPI_ISL_18487760, EPI_ISL_18487772-18487773, EPI_ISL_18487784, EPI_ISL_18487805, EPI_ISL_18487837, EPI_ISL_18487841, EPI_ISL_18492419, EPI_ISL_18494265, EPI_ISL_18494273, EPI_ISL_18494368, EPI_ISL_18494630, EPI_ISL_18495676, EPI_ISL_18495680, EPI_ISL_18495690, EPI_ISL_18495695, EPI_ISL_18495708-18495710, EPI_ISL_18519534, EPI_ISL_18525137, EPI_ISL_18526955`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_252e8_f0e7a0.json?label=id:node_3338674
![613](https://github.com/cov-lineages/pango-designation/assets/125747944/16975560-910f-4ffb-a5aa-e36d53360ff8)

**Trivia:**
- Quite significant prevalence in Russia (St. Petersburg region especially), estimated around 10%~20% since October ([Cov-Spectrum](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AV1230A%2CS%3AQ613H%2CS%3AQ675K&nextcladePangoLineage=XBB.1.16*))
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/a38c6f48-1f53-4f6f-991b-c9176cf32b97)

**Comment by FedeGueli** [comment]
284 now with a 4% of prevalence in Russia in November.

**Comment by FedeGueli** [comment]
7% in Russia.

@corneliusroemer i would designate these lineages, they have been away from the focus and charts due the de facto isolation of Russia but it is very likely they are among the fittest of the XBB era . If you need i can email a short list of them are 3/4 not that much.
