### ISSUE TITLE
Another FY.5 with S:T572I (65 seqs, 12 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2385]
_Taken from **Branch 2** of Multitask sars-cov-2-variants/lineage-proposals#929_

**Defining Mutations:** `FY.5` > `A6019G` > `C23277T(S:T572I)`, mostly with `G9290A(ORF1a:D3009N/nsp4_D246N), A12495G(ORF1a:Y4077C/nsp8_Y135C), C14016T, C18252T`
**Query:** `C14016T, C18252T, C23277T`
**Earliest seq:** 2023-05-20 (`EPI_ISL_17842747`, Iowa, USA)
**Latest seq:** 2023-11-14 (`EPI_ISL_18530367`, England, UK)
**Sampled Countries:** UK (20: EN/19; WS), Australia (10: NSW/8; QLD; AGES), USA (9: VA/2; CA; CO; IA; NJ; PA; ex. Germany/2), Greece (5), Sweden (4), Ukraine (4), Croatia (3), Netherlands (3), Germany (2), Italy (2), Slovakia (2), France (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17832393, EPI_ISL_17842747, EPI_ISL_17924327, EPI_ISL_18011132, EPI_ISL_18012276, EPI_ISL_18048618, EPI_ISL_18123726, EPI_ISL_18142764-18142765, EPI_ISL_18212907, EPI_ISL_18212912, EPI_ISL_18227436, EPI_ISL_18227438, EPI_ISL_18229230, EPI_ISL_18242626, EPI_ISL_18246700, EPI_ISL_18248722, EPI_ISL_18248741, EPI_ISL_18250174, EPI_ISL_18286900, EPI_ISL_18300055, EPI_ISL_18300716, EPI_ISL_18302481, EPI_ISL_18333044, EPI_ISL_18337884, EPI_ISL_18339640, EPI_ISL_18373574, EPI_ISL_18378388, EPI_ISL_18378982, EPI_ISL_18378985, EPI_ISL_18386724, EPI_ISL_18386833, EPI_ISL_18392738, EPI_ISL_18397074, EPI_ISL_18398250, EPI_ISL_18398386, EPI_ISL_18403212, EPI_ISL_18403228, EPI_ISL_18412613, EPI_ISL_18412647-18412648, EPI_ISL_18433082, EPI_ISL_18433560, EPI_ISL_18444544, EPI_ISL_18446375, EPI_ISL_18453281, EPI_ISL_18455119, EPI_ISL_18462746, EPI_ISL_18464430, EPI_ISL_18466627, EPI_ISL_18466629, EPI_ISL_18474934, EPI_ISL_18475006, EPI_ISL_18486389, EPI_ISL_18486395, EPI_ISL_18490312, EPI_ISL_18490320, EPI_ISL_18490329, EPI_ISL_18490354, EPI_ISL_18490536, EPI_ISL_18507565, EPI_ISL_18509845, EPI_ISL_18509847, EPI_ISL_18530367, EPI_ISL_18530410`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_288f_f1a5a0.json?f_userOrOld=uploaded%20sample&label=id:node_3216951
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/71af655e-2cd1-446e-bef6-130ee58a0e9c)

**Trivia:**
- `S:T572I` seems to be a mutation that can increase binding affinty by tweaking RBD conformation, paired with `S:Y200C` which has the opposite effect that gains some significant human sera escape by sacrificing a lot of binding affinty, XBB.1.22.1* seems to find a unique way in viral evolution, its strategy seems to work well surviving this long amongst so many strong competitors. Details can be found in the recent preprint by Dadonaite, Bloom et al. (2023) https://www.biorxiv.org/content/10.1101/2023.11.13.566961v1

**Comment by FedeGueli** [comment]
designated FY.5.4 via https://github.com/cov-lineages/pango-designation/commit/372aae1c1ab4fbd45da7617a7706c27f694105d4
