### ISSUE TITLE
HK.3+C14889T+S:Q14R(62 seqs, 11 countries, 17% Henan)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2387]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/601

HK.3+C14889T+A21603G(S:Q14R)

GISAID query: A21603G,C6541T, C14889T
No. of seqs: 59(Australia 1 Canada 1 Denmark 1 Japan 4 Russia 1 Singapore 6(1 from Thailand 1 from Hong Kong) South Korea 1 Switzerland 2 USA 10 China 32(Fujian, Henan, Hubei, Liaoning, Shanxi, Sichuan, Shanghai))

This query finds 58 and EPI_ISL_18465882 has S:14 masked but shares mutations with others that have S:Q14R, shall belong to this branch. 

First: EPI_ISL_18313159, Hubei, 2023-9-2
Latest: EPI_ISL_18535375, Hubei, 2023-11-15

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/hk_3_q14r.json?label=id:node_3534032)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/d9f1868a-ee6c-45bd-b572-500c20f1c5cf)

**Comment by FedeGueli** [comment]
It represents  a 1/6 of samples collected  in Henan in November cc @corneliusroemer

**Comment by aviczhl2** [comment]
Designated HK.3.13
