### ISSUE TITLE
JE.1.1+S:V1122A+Orf1a:R135S(rev), N:13F (71 seqs, 15 countries, 30 with S:E554K, 1.3% Singapore)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2390]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1116

Finds this interesting branch with interesting mutations(1 reversion Orf1a:R135S and 1 2-nuc mutation N:13 P->L->F) and good growth advantage, while also from travelers of multiple undersampled regions.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=JE.1.1*&nucMutations1=670T&nextcladePangoLineage1=JE.1.1*&analysisMode=CompareToBaseline&

JE.1.1+T24927C(S:V1122A)+G670T(Orf1a:R135S rev), C28310T(N:L13F)

GISAID query: T24927C, C28310T
No. of seqs: 28(Australia 5 Canada 1 Denmark 1 UK 2 France 7 Japan 1 Singapore 5(2 from Phillipines) Spain 1 USA 5(1 from Qatar 1 from Phillipines 1 from Hong Kong) Belgium 1, Taiwan 1( from Philippines)  )

4 samples from Phillipine travelers sampled in different countries.

This branch is also the largest branch apart from BA.2.86* and Flip (both at ~45%) in the recent Singapore upload. 

First: EPI_ISL_18278964, 2023-8-10, Singapore.
Latest: EPI_ISL_18544824, 2023-11-21,Singapore

GISAID query for S:E554K branch: C28310T,T24927C,G23222A(8 seqs)

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/je_1_1_r135s_l10f.json?label=id:node_4030391)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/b755e355-f516-4b0e-8738-3ba31480db90)

**Comment by FedeGueli** [comment]
This went to 37 and 9 for the E554K sublineage:
Yesterday upload : 4 France 3 Singapore 2 Usa 1 Belgium 1 South Australia  all collected after Oct 30

quite impressive 

Ping @corneliusroemer i suggest a rapid designation of this one.

**Comment by FedeGueli** [comment]
40 now  Thailand, France , Canada

**Comment by FedeGueli** [comment]
51 now. it seems one of the fastest behind JN.1 
@corneliusroemer  i suggest to designate it.

**Comment by aviczhl2** [comment]
also come from Curacao.

**Comment by FedeGueli** [comment]
54 one sample from Japan via Taiwan, @corneliusroemer suggesting a designation of this one one of the most different spikes with fitness circulating.

**Comment by aviczhl2** [comment]
10/685 in Singapore seqs from 2023-11-29. It seems expanding despite JN.1 already dominated.

**Comment by FedeGueli** [comment]
> T24927C, C28310T

1% after November 25 in Singapore

**Comment by FedeGueli** [comment]
82 now. + 4  today in the  upload from Philippines it represents 7/39 related to Philippines in November:

New tree seems very intersting with further spike diveristy:
![Schermata 2023-12-20 alle 10 40 26](https://github.com/cov-lineages/pango-designation/assets/87669813/a2c5cc63-8e0e-49cb-a2b8-4ee9dfe33aa2)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_36373_2b5620.json?c=userOrOld&label=id:node_4028655
In red recent samples related to Philippines.

@corneliusroemer i suggest a fast designation of this one.

**Comment by FedeGueli** [comment]
Thx @corneliusroemer
