### ISSUE TITLE
HK.3.1 with S:T478R (71 seqs, mainly in Sweden, 8 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2393]
_Taken from **Branch 14** of Multitask sars-cov-2-variants/lineage-proposals#787_

**Defining Mutations:** `HK.3.1` > `C19017T` > `C1288T, T4057C` > `C22995G(S:T478R)`
**Query:** `C1288T, T4057C, C22995G`
**Earliest seq:** 2023-10-13 (`EPI_ISL_18435593`, Skåne, Sweden) 
**Latest seq:** 2023-11-19 (`EPI_ISL_18543800`, Noord-Holland, Netherlands) 
**Sampled Countries:** Sweden (16), Denmark (4), Germany (1), Netherlands (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18435593, EPI_ISL_18435596, EPI_ISL_18472820, EPI_ISL_18494552, EPI_ISL_18500965, EPI_ISL_18500984, EPI_ISL_18500986, EPI_ISL_18501005, EPI_ISL_18501009, EPI_ISL_18501038, EPI_ISL_18501066-18501067, EPI_ISL_18506905, EPI_ISL_18518456, EPI_ISL_18523106, EPI_ISL_18523121, EPI_ISL_18537846-18537847, EPI_ISL_18537882, EPI_ISL_18538323, EPI_ISL_18540321, EPI_ISL_18543800`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ecda_53ed00.json?f_userOrOld=uploaded%20sample&label=id:node_3534934
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/8e572785-ce04-458c-9389-d5068317b284)

**Comment by FedeGueli** [comment]
29 in 6 countries

**Comment by DailyCovidCases** [comment]
Please close this issue
