### ISSUE TITLE
Another EG.5.1/DV.7.1 recombinant on usher remove place( 38 seqs, 7 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2394]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/972

There is another EG.5.1/DV.7.1 recombinant different from XCT.

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/d084f60a-c0a9-4f9c-8fc9-a6f8b0d3a634)

EG.5.1--DV.7.1
Breakpoint between 14125 and 15025.

Additional mutations: del518_520, C1471T, T14124A,C15924T, C29518T,T29793A

Orf1a: M85-

del518_520, C1471T,T14124A from a EG.5.1 branch having S:F186L.

C15924T, C29518T, T29793A from a DV.7.1 branch

GISAID query:T14124A,C15924T
No. of seqs: 27(Belgium 2 Italy 1 Switzerland 1 Canada 23)

EPI_ISL_18393248, Belgium, 2023-9-27
EPI_ISL_18549487, Canada, 2023-11-17

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/eg_5_1_dv_7_1_recomb.json?label=id:node_4468138)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/95613389-ed15-4a22-bd20-84802e51d819)

The Belgium seqs have 27915 missing coverage. Shall have that. 

One Belgium and an Italian seq shall be further recombs of this one and XBB*.  

[usher for EG.5.1-donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_19c35_560cc0.json)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/c2c2dbc6-4c93-4e95-9b3a-dc286616231f)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/174fd4a7-3960-400e-8388-145ac2c109be)

[usher for DV.7.1-donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_278f7_565570.json?c=gt-nuc_15924,29518&gmin=14924)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/e38babd5-7b36-44f0-a85a-37b47a2d25c2)

**Comment by aviczhl2** [comment]
30, Sweden

**Comment by aviczhl2** [comment]
+2 Netherlands

**Comment by aviczhl2** [comment]
Also there seems to be Canadian recomb of this lineage and XBB.2.3  (EPI_ISL_18610325), the 2nd further recomb formed by this lineage.

**Comment by aviczhl2** [comment]
+1 Israel

**Comment by aviczhl2** [comment]
No new seqs.

**Comment by FedeGueli** [comment]
+3 Canada now 37

**Comment by aviczhl2** [comment]
@corneliusroemer  This one is on a quite diverse location of the tree. Very different from anything else.

Suggest to designate to monitor diversity of the virus.

**Comment by aviczhl2** [comment]
No new seqs
