### ISSUE TITLE
EG.5.1.1 with ORF1a:V3660M(nsp6_V91M), S:F186S and S:K356T (31 seqs, mainly in Singapore, 3 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2396]
_Taken from **Branch 2** of Multitask sars-cov-2-variants/lineage-proposals#1048 , Sub-branch of sars-cov-2-variants/lineage-proposals#905 proposed by @aviczhl2_

**Defining Mutations:** `EG.5.1.1` > `C2644T` > `G11243A(ORF1a:V3660M)` > `C3457T, T16383A, C25614T` > `T22119C(S:F186S)` > `C19011T` > `A22629C(S:K356T)`
**Query:** `C3457T, T16383A, A22629C`
**Earliest seq:** 2023-09-18 (`EPI_ISL_18425433`, California, USA)
**Latest seq:** 2023-11-22 (`EPI_ISL_18544885`, Singapore)
**Sampled Countries:** Singapore (28: Local/27; ex. Malaysia/1), USA (2: CA), UK (1: SC)

<details><summary>Genomes: </summary>

`EPI_ISL_18307098, EPI_ISL_18355099, EPI_ISL_18355131, EPI_ISL_18361852, EPI_ISL_18361882, EPI_ISL_18361972, EPI_ISL_18361998, EPI_ISL_18397213, EPI_ISL_18425433, EPI_ISL_18428777, EPI_ISL_18445021, EPI_ISL_18445037, EPI_ISL_18445056, EPI_ISL_18445151, EPI_ISL_18473286, EPI_ISL_18473358, EPI_ISL_18473409, EPI_ISL_18473411, EPI_ISL_18473563, EPI_ISL_18473628, EPI_ISL_18497460, EPI_ISL_18502441, EPI_ISL_18544498, EPI_ISL_18544502, EPI_ISL_18544595, EPI_ISL_18544652, EPI_ISL_18544688, EPI_ISL_18544707, EPI_ISL_18544807, EPI_ISL_18544829, EPI_ISL_18544885`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_203d5_58a530.json?f_userOrOld=uploaded%20sample&label=id:node_3511604
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/9f676325-8bc7-4aa7-ac72-5711e653c91d)

**Comment by aviczhl2** [comment]
Sub-branch of https://github.com/sars-cov-2-variants/lineage-proposals/issues/905

**Comment by aviczhl2** [comment]
Designated HK.34.1
