### ISSUE TITLE
EG.5.1.1 with S:L455F on C5812T branch, mostly with M:K15Q and N:T166R (159 seqs, mainly in South Korea, 10 countries) further with S:A475V (50 seqs, 5 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2398]
_Main branch taken from **Branch 28** of Multitask sars-cov-2-variants/lineage-proposals#537_
_Follow-up branch taken from **Branch 2** of Multitask sars-cov-2-variants/lineage-proposals#978_

**Defining Mutations:** **EG.5.1.1** > `C5812T` > `G22927T(S:L455F)`, mostly with >> `A26565C(M:K15Q), C28770G(N:T166R)`
**Query:** `C5812T, G22927T, C28770G` (for major `A26565C(M:K15Q), C28770G(N:T166R)` sub-branch only)

**Defining Mutations for follow-up `S:A475V` sub-branch:** `Main proposal` > `A26565C(M:K15Q), C28770G(N:T166R)` > `A10323G(ORF1a:K3353R), C22986T(S:A475V)`
**Query for follow-up `S:A475V` sub-branch:** `C5812T, C22986T, A26565C`

**Earliest seq:** 2023-08-09 (`EPI_ISL_18214077`, South Korea)
**Latest seq:** 2023-11-09 (`EPI_ISL_18547984`, Nevada, USA)
**Sampled Countries:** South Korea (68), USA (5: NV/2; NC/1; ex. S. Korea/2), Australia (2: NSW; QLD), China (2: SC/1; ex. S. Korea/1), Denmark (2), Hungary (2), Finland (1), Japan (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18214077, EPI_ISL_18236938, EPI_ISL_18293068, EPI_ISL_18293497, EPI_ISL_18347905, EPI_ISL_18353940, EPI_ISL_18354370, EPI_ISL_18354403, EPI_ISL_18355265, EPI_ISL_18355547, EPI_ISL_18368528, EPI_ISL_18382157, EPI_ISL_18382304, EPI_ISL_18382505, EPI_ISL_18382615, EPI_ISL_18386641, EPI_ISL_18408701-18408702, EPI_ISL_18408814, EPI_ISL_18408878, EPI_ISL_18411301, EPI_ISL_18415920, EPI_ISL_18435710, EPI_ISL_18438964, EPI_ISL_18439203, EPI_ISL_18439262-18439263, EPI_ISL_18439368, EPI_ISL_18439436, EPI_ISL_18460639, EPI_ISL_18460726, EPI_ISL_18460826, EPI_ISL_18461023, EPI_ISL_18461030, EPI_ISL_18461109, EPI_ISL_18461117, EPI_ISL_18461139, EPI_ISL_18488790, EPI_ISL_18488878, EPI_ISL_18488904, EPI_ISL_18489119, EPI_ISL_18501908, EPI_ISL_18502007, EPI_ISL_18503617, EPI_ISL_18503624, EPI_ISL_18503755, EPI_ISL_18503952, EPI_ISL_18503974, EPI_ISL_18511170, EPI_ISL_18511222, EPI_ISL_18511248, EPI_ISL_18511257, EPI_ISL_18511484, EPI_ISL_18513699, EPI_ISL_18518361, EPI_ISL_18535616, EPI_ISL_18535618, EPI_ISL_18535641, EPI_ISL_18535643-18535644, EPI_ISL_18535683, EPI_ISL_18539076, EPI_ISL_18539319, EPI_ISL_18539641, EPI_ISL_18539827, EPI_ISL_18540358, EPI_ISL_18544082, EPI_ISL_18547609, EPI_ISL_18547984, EPI_ISL_18550336, EPI_ISL_18552522, EPI_ISL_18559930, EPI_ISL_18564453, EPI_ISL_18564477, EPI_ISL_18564533, EPI_ISL_18564565, EPI_ISL_18564603, EPI_ISL_18564701, EPI_ISL_18564813, EPI_ISL_18564892, EPI_ISL_18564897, EPI_ISL_18565136`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_356f8_c1a890.json?label=id:node_3518019
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/4396addb-0170-4ef0-b401-e67de407edec)

**Trivia:**
- [Note](https://github.com/sars-cov-2-variants/lineage-proposals/issues/537#issuecomment-1817537972) by @ryhisner:
> To me, branch 28 deserves to be moved to the main Pango page. There are lots of interesting branches there, and a really interesting sequence from Shanghai just showed up as well—EPI_ISL_18518361. The one branch has C26681T, the synonymous mutation in M that is also in BA.2.86 and many other sequences/lineages of interest.
> 
> M:K15Q is an A->C nuc mutation and N:T166R is C->G. These are rare nuc mutations, and I don't think they happened by accident.

**Comment by FedeGueli** [comment]
475V branch now 59 no January sample yet

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by Over-There-Is** [comment]
183 now
