### ISSUE TITLE
Potential new B.1.X-B.1.2 sublineage in Texas

### ISSUE THREAD

**Issue by ShelbyReneeBSW** [cov-lineages/pango-designation#24]
Submitted by: Shelby Hendrickson and Caitlin Maloney

Description
Sub-lineage of: B.1 or B.1.2 with Spike_L18F and Spike_E780Q, also associated with ORF8_H17Y
Earliest sequence: 09/25/2020
Most recent sequence: 2/19/2021
Countries circulating: US, Canada

Appears to be two clusters of these spike mutations appearing concurrently.
First reported in GISAID 09/25/2020 in British Columbia, Canada = 595 cases, with 582 occurring in British Columbia. 17% prevalence of cases submitted to GISAID for Texas.
Also reported in GISAID 101/20/2020 in Texas, USA.  USA = 375 cases, with 305 occurring in Texas.  4% prevalence of cases submitted to GISAID for Texas.
[https://outbreak.info/situation-reports?country=United%20States&country=Canada&division=Texas&division=British%20Columbia&pango&muts=S%3AE780Q&muts=S%3AL18F&selected=United%20States&selectedType=country](url)

Genomes
EPI_ISL_979400
EPI_ISL_979398
EPI_ISL_979396
EPI_ISL_979386
EPI_ISL_979380
EPI_ISL_978312
EPI_ISL_967510
EPI_ISL_967163
EPI_ISL_966655
EPI_ISL_966313
EPI_ISL_942926
EPI_ISL_942923
EPI_ISL_942914
EPI_ISL_942910
EPI_ISL_940807
EPI_ISL_935734
EPI_ISL_935721
EPI_ISL_935702
EPI_ISL_911669
EPI_ISL_911668
EPI_ISL_911493
EPI_ISL_911479
EPI_ISL_911475
EPI_ISL_886571
EPI_ISL_872379
EPI_ISL_786618
EPI_ISL_786170
EPI_ISL_786002
EPI_ISL_785824
EPI_ISL_785296
EPI_ISL_785255
EPI_ISL_785213
EPI_ISL_785132
EPI_ISL_785118
EPI_ISL_785114
EPI_ISL_785107
EPI_ISL_785054
EPI_ISL_785021
EPI_ISL_784992
EPI_ISL_784839
EPI_ISL_784789
EPI_ISL_784736
EPI_ISL_784699
EPI_ISL_784644
EPI_ISL_784607
EPI_ISL_784581
EPI_ISL_784546
EPI_ISL_784160
EPI_ISL_784143
EPI_ISL_783981
EPI_ISL_783925
EPI_ISL_783867
EPI_ISL_783792
EPI_ISL_783756
EPI_ISL_783718
EPI_ISL_783613
EPI_ISL_1114143
EPI_ISL_1114027
EPI_ISL_1113917
EPI_ISL_1113899
EPI_ISL_1113895
EPI_ISL_1113875
EPI_ISL_1110294
EPI_ISL_1110290
EPI_ISL_1109990
EPI_ISL_1090836
EPI_ISL_1090696
EPI_ISL_1090671
EPI_ISL_1090626
EPI_ISL_1090527
EPI_ISL_1090462
EPI_ISL_1089106
EPI_ISL_1088589
EPI_ISL_1088293
EPI_ISL_1087894
EPI_ISL_1087851
EPI_ISL_1087010
EPI_ISL_1086590
EPI_ISL_1086565
EPI_ISL_1086477
EPI_ISL_1086459
EPI_ISL_1086394
EPI_ISL_1081176
EPI_ISL_1081034
EPI_ISL_1081017
EPI_ISL_1081011
EPI_ISL_1080946
EPI_ISL_1080925
EPI_ISL_1080920
EPI_ISL_1080865
EPI_ISL_1080367
EPI_ISL_1080306
EPI_ISL_1080102
EPI_ISL_1080095
EPI_ISL_1080047
EPI_ISL_1079989
EPI_ISL_1079988
EPI_ISL_1079885
EPI_ISL_1079830
EPI_ISL_1079817
EPI_ISL_1079788
EPI_ISL_1079785
EPI_ISL_1079757
EPI_ISL_1079727
EPI_ISL_1079679
EPI_ISL_1079668
EPI_ISL_1079637
EPI_ISL_1079614
EPI_ISL_1079573
EPI_ISL_1079505
EPI_ISL_1079501
EPI_ISL_1079497
EPI_ISL_1079491
EPI_ISL_1079413
EPI_ISL_1079329
EPI_ISL_1079327
EPI_ISL_1079306
EPI_ISL_1079286
EPI_ISL_1079260
EPI_ISL_1079255
EPI_ISL_1079245
EPI_ISL_1079242
EPI_ISL_1079228
EPI_ISL_1079225
EPI_ISL_1079170
EPI_ISL_1079167
EPI_ISL_1079155
EPI_ISL_1079138
EPI_ISL_1079112
EPI_ISL_1079075
EPI_ISL_1079066
EPI_ISL_1079059
EPI_ISL_1078892
EPI_ISL_1078862
EPI_ISL_1078861
EPI_ISL_1078809
EPI_ISL_1078691
EPI_ISL_1078672
EPI_ISL_1078662
EPI_ISL_1078466
EPI_ISL_1078435
EPI_ISL_1078425
EPI_ISL_1078421
EPI_ISL_1078420
EPI_ISL_1078387
EPI_ISL_1078380
EPI_ISL_1078332
EPI_ISL_1078318
EPI_ISL_1078269
EPI_ISL_1078236
EPI_ISL_1078221
EPI_ISL_1078176
EPI_ISL_1078122
EPI_ISL_1078060
EPI_ISL_1078038
EPI_ISL_1078009
EPI_ISL_1078001
EPI_ISL_1077987
EPI_ISL_1077974
EPI_ISL_1077931
EPI_ISL_1077908
EPI_ISL_1077901
EPI_ISL_1077884
EPI_ISL_1077864
EPI_ISL_1077863
EPI_ISL_1077854
EPI_ISL_1077838
EPI_ISL_1077829
EPI_ISL_1077785
EPI_ISL_1077748
EPI_ISL_1077719
EPI_ISL_1077713
EPI_ISL_1077682
EPI_ISL_1077675
EPI_ISL_1077631
EPI_ISL_1077600
EPI_ISL_1077590
EPI_ISL_1077566
EPI_ISL_1077543
EPI_ISL_1077507
EPI_ISL_1077494
EPI_ISL_1077489
EPI_ISL_1077473
EPI_ISL_1077469
EPI_ISL_1077442
EPI_ISL_1077428
EPI_ISL_1077344
EPI_ISL_1077323
EPI_ISL_1077217
EPI_ISL_1077195
EPI_ISL_1077143
EPI_ISL_1077137
EPI_ISL_1077110
EPI_ISL_1077061
EPI_ISL_1077025
EPI_ISL_1077024
EPI_ISL_1077010
EPI_ISL_1076969
EPI_ISL_1076938
EPI_ISL_1076906
EPI_ISL_1076903
EPI_ISL_1076858
EPI_ISL_1076855
EPI_ISL_1076843
EPI_ISL_1076816
EPI_ISL_1076786
EPI_ISL_1076757
EPI_ISL_1076756
EPI_ISL_1076746
EPI_ISL_1076719
EPI_ISL_1076718
EPI_ISL_1076717
EPI_ISL_1076663
EPI_ISL_1076657
EPI_ISL_1076648
EPI_ISL_1076587
EPI_ISL_1076507
EPI_ISL_1076323
EPI_ISL_1076309
EPI_ISL_1076302
EPI_ISL_1076272
EPI_ISL_1076256
EPI_ISL_1076244
EPI_ISL_1076226
EPI_ISL_1076217
EPI_ISL_1076203
EPI_ISL_1076184
EPI_ISL_1076137
EPI_ISL_1076120
EPI_ISL_1076102
EPI_ISL_1076079
EPI_ISL_1076038
EPI_ISL_1075945
EPI_ISL_1075913
EPI_ISL_1075884
EPI_ISL_1075873
EPI_ISL_1075848
EPI_ISL_1075822
EPI_ISL_1075793
EPI_ISL_1075678
EPI_ISL_1075668
EPI_ISL_1075547
EPI_ISL_1075504
EPI_ISL_1075423
EPI_ISL_1075354
EPI_ISL_1075304
EPI_ISL_1075299
EPI_ISL_1075287
EPI_ISL_1075241
EPI_ISL_1075186
EPI_ISL_1075177
EPI_ISL_1075145
EPI_ISL_1075137
EPI_ISL_1075112
EPI_ISL_1075097
EPI_ISL_1075084
EPI_ISL_1075071
EPI_ISL_1075068
EPI_ISL_1075057
EPI_ISL_1075055
EPI_ISL_1075052
EPI_ISL_1074978
EPI_ISL_1074970
EPI_ISL_1074962
EPI_ISL_1074949
EPI_ISL_1074936
EPI_ISL_1074912
EPI_ISL_1074890
EPI_ISL_1074850
EPI_ISL_1074847
EPI_ISL_1074839
EPI_ISL_1074817
EPI_ISL_1074750
EPI_ISL_1074682
EPI_ISL_1074670
EPI_ISL_1074662
EPI_ISL_1074652
EPI_ISL_1074641
EPI_ISL_1074626
EPI_ISL_1074619
EPI_ISL_1074615
EPI_ISL_1074612
EPI_ISL_1074597
EPI_ISL_1074570
EPI_ISL_1074562
EPI_ISL_1074519
EPI_ISL_1074515
EPI_ISL_1074514
EPI_ISL_1074511
EPI_ISL_1074449
EPI_ISL_1074420
EPI_ISL_1074395
EPI_ISL_1074394
EPI_ISL_1074370
EPI_ISL_1074358
EPI_ISL_1074327
EPI_ISL_1074318
EPI_ISL_1074312
EPI_ISL_1059264
EPI_ISL_1059263
EPI_ISL_1059248
EPI_ISL_1059245
EPI_ISL_1059244
EPI_ISL_1036945
EPI_ISL_1029838
EPI_ISL_1027715
[B.1.X-B.1.2 Sublineage Texas.pdf](https://github.com/cov-lineages/pango-designation/files/6070925/B.1.X-B.1.2.Sublineage.Texas.pdf)

Evidence
![B 1 2 X](https://user-images.githubusercontent.com/79931611/109696960-e1bd2d80-7b4a-11eb-91fa-defa7b87484a.png)

**Comment by chrisruis** [comment]
This issue has gone stale so we'll close it for now. If this would still be a useful lineage designation, please reopen this. Thanks
