### ISSUE TITLE
EG.5.1.1 with S:L455F on T14034C branch (130 seqs, mainly in South Korea, 9 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2400]
Taken from Branch 63 of Multitask sars-cov-2-variants/lineage-proposals#537

**Defining Mutations:** `EG.5.1.1` > `T14034C` > `T6556C` > `G22927T(S:L455F)`
**Query:** `T6556C, T14034C, G22927T`
**Earliest seq:** 2023-08-28 (`EPI_ISL_18236022`, Chiba, Japan)
**Latest seq:** 2023-11-16 (`EPI_ISL_18568493`, Ardèche, France)
**Sampled Countries:** South Korea (66), Japan (11), France (7), China (2: Taiwan), Singapore (2), Germany (1), Ireland (1), UK (1: England)

<details><summary>Genomes: </summary>

`EPI_ISL_18236022, EPI_ISL_18307101, EPI_ISL_18307183, EPI_ISL_18312967, EPI_ISL_18354179, EPI_ISL_18354386, EPI_ISL_18371409, EPI_ISL_18371437, EPI_ISL_18376385, EPI_ISL_18381917, EPI_ISL_18382077, EPI_ISL_18382170, EPI_ISL_18382306, EPI_ISL_18382313, EPI_ISL_18384744, EPI_ISL_18390972, EPI_ISL_18408733, EPI_ISL_18408999, EPI_ISL_18409046, EPI_ISL_18409110, EPI_ISL_18418096, EPI_ISL_18418099, EPI_ISL_18420466, EPI_ISL_18423347, EPI_ISL_18438958, EPI_ISL_18439063, EPI_ISL_18439157, EPI_ISL_18439221, EPI_ISL_18439371, EPI_ISL_18460530, EPI_ISL_18460541, EPI_ISL_18460589, EPI_ISL_18460966, EPI_ISL_18460978, EPI_ISL_18461033, EPI_ISL_18461094, EPI_ISL_18461485, EPI_ISL_18465933, EPI_ISL_18468665, EPI_ISL_18486472, EPI_ISL_18491815, EPI_ISL_18496187, EPI_ISL_18501996, EPI_ISL_18502046, EPI_ISL_18502053, EPI_ISL_18502059, EPI_ISL_18503696, EPI_ISL_18503846, EPI_ISL_18510036, EPI_ISL_18510038, EPI_ISL_18511034, EPI_ISL_18511095, EPI_ISL_18511104, EPI_ISL_18511108, EPI_ISL_18511172, EPI_ISL_18511241, EPI_ISL_18511380, EPI_ISL_18511416, EPI_ISL_18511461, EPI_ISL_18511469, EPI_ISL_18511480, EPI_ISL_18511508, EPI_ISL_18511521, EPI_ISL_18511532, EPI_ISL_18511557, EPI_ISL_18511580, EPI_ISL_18511661, EPI_ISL_18511670, EPI_ISL_18535606, EPI_ISL_18535663, EPI_ISL_18535697, EPI_ISL_18539307, EPI_ISL_18539369, EPI_ISL_18539422, EPI_ISL_18539428, EPI_ISL_18539447, EPI_ISL_18539483, EPI_ISL_18539547, EPI_ISL_18545014, EPI_ISL_18564392, EPI_ISL_18564436, EPI_ISL_18564462-18564463, EPI_ISL_18564564, EPI_ISL_18564669, EPI_ISL_18564752, EPI_ISL_18564926, EPI_ISL_18565014, EPI_ISL_18565195, EPI_ISL_18568493, EPI_ISL_18570360`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21541_c2c6a0.json?label=id:node_3526922
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/5b90b3a7-63c8-46ce-9548-ea7813bc5bf0)

**Trivia:**
- Only 3 seqs preceeding this branch without `S:L455F`: `France/GES-IPP16513/2023|EPI_ISL_18109814|2023-07-241, `Australia/QLD0x0138F8/2023|EPI_ISL_18324553|2023-09-12`, and `SouthKorea/KDCA_270758/2023|EPI_ISL_18503707|2023-10-12` ⚠️ so please check potential dropout/misplacement.

**Comment by DailyCovidCases** [comment]
Please close this issue
