### ISSUE TITLE
EG.5.1.6 with S:L455F (96 seqs, mainly in Canada, 12 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2401]
_Taken from **Branch 77** of Multitask sars-cov-2-variants/lineage-proposals#537_

**Defining Mutations:** `EG.5.1.6` > `C925T, C27161T` > `C14919A` > `G14559A` > `G22927T(S:L455F)`
**Query:** `C5835T, G14559A, G22927T`
**Earliest seq:** 2023-09-11 (`EPI_ISL_18381025`, British Columbia, Canada)
**Latest seq:** 2023-11-21 (`EPI_ISL_18572342`, Israel)
**Sampled Countries:** Canada (59: AB/25; BC/25; SK/7; ON/1; QC/1), Israel (5), USA (3: NY/2; CA), Finland (2), Sweden (2), Austria (1), Ireland (1), UK (1: EN)

<details><summary>Genomes: </summary>

`EPI_ISL_18313726, EPI_ISL_18374552, EPI_ISL_18381025, EPI_ISL_18381642, EPI_ISL_18399548, EPI_ISL_18405416, EPI_ISL_18429724, EPI_ISL_18431316, EPI_ISL_18431484, EPI_ISL_18431577, EPI_ISL_18448820, EPI_ISL_18449315, EPI_ISL_18451058, EPI_ISL_18452675, EPI_ISL_18453011, EPI_ISL_18453157, EPI_ISL_18456002, EPI_ISL_18456201, EPI_ISL_18493062, EPI_ISL_18499142, EPI_ISL_18501414, EPI_ISL_18501469, EPI_ISL_18501539, EPI_ISL_18501675, EPI_ISL_18512520, EPI_ISL_18512575, EPI_ISL_18512726, EPI_ISL_18512904, EPI_ISL_18512975, EPI_ISL_18513012, EPI_ISL_18516832, EPI_ISL_18516837, EPI_ISL_18517029, EPI_ISL_18517372, EPI_ISL_18517374-18517375, EPI_ISL_18517477, EPI_ISL_18517505, EPI_ISL_18526773, EPI_ISL_18526937-18526938, EPI_ISL_18526942, EPI_ISL_18526999, EPI_ISL_18527195, EPI_ISL_18532450-18532451, EPI_ISL_18533407, EPI_ISL_18538515, EPI_ISL_18538528, EPI_ISL_18538535, EPI_ISL_18538740, EPI_ISL_18538774, EPI_ISL_18538986, EPI_ISL_18541507-18541508, EPI_ISL_18547665, EPI_ISL_18552699, EPI_ISL_18553923, EPI_ISL_18553948, EPI_ISL_18558921, EPI_ISL_18560813, EPI_ISL_18563933, EPI_ISL_18563975, EPI_ISL_18563992, EPI_ISL_18564064, EPI_ISL_18564086, EPI_ISL_18564088, EPI_ISL_18564119, EPI_ISL_18564154, EPI_ISL_18564182, EPI_ISL_18564194, EPI_ISL_18572342, EPI_ISL_18572380, EPI_ISL_18572384`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d8f9_c314c0.json?label=id:node_3469419
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/c6c9b3f6-d7ed-46ce-a522-6c7068b9e27b)

**Comment by aviczhl2** [comment]
Designated HV.2

**Comment by FedeGueli** [comment]
I see it on Nextclade  but  i cannot find here

**Comment by aviczhl2** [comment]
> > Designated HV.2
> 
> Where ?? i cannot find the commit for this.

Together with JD.1.1.7

**Comment by FedeGueli** [comment]
> > > Designated HV.2
> > 
> > 
> > Where ?? i cannot find the commit for this.
> 
> Together with JD.1.1.7

thanks!! the hidden row!
