### ISSUE TITLE
XDE/JN.1/XDE recombinant (14 sequences from USA, China, & Germany)

### ISSUE THREAD

**Issue by emily-smith1** [cov-lineages/pango-designation#2402]
There is only one sequence so far, but this is worth monitoring as we know that JN.1 has a clear growth advantage worldwide. ORF1ab appears to be GW.5*, Spike is JN.1, and N/ORF9b are likely XBB.1.9* due to the presence of ORF9b:I5T and absence of N:Q229K (thanks to @ryhisner for help determining this). 

### **Description**
**Earliest sequence**: 2023-11-09
**Most recent sequence**: 2023-11-09
**Countries circulating**: USA-CA
**GISAID query**: C1170T,C6501A,T22926C

### **Genomes**
EPI_ISL_18576372

### **Evidence**
![image](https://github.com/cov-lineages/pango-designation/assets/84812104/df4de3b1-9cca-4a49-88a5-af9fc8c7bf51)

**Comment by aviczhl2** [comment]
Was discussed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/991, it seems that the donor is XDE,

**Comment by Over-There-Is** [comment]
Let's wait for the next sequences and check 29535 site. It could be an XDE/JN.1 sandwich recombinant.

**Comment by FedeGueli** [comment]
@corneliusroemer it is the one you posted in # 991 other repo yesterday morning.

**Comment by emily-smith1** [comment]
The above GISAID nucleotide query does now identify a second genome (EPI_ISL_18651234), but it has many AA substitutions in ORF1a and ORF1b that differentiate it from the first. I'm hesitant to say these are the same recombinant without more data. I think we would also expect more localized spread in USA-CA if this were truly growing. This other genome is from Singapore but a traveler from Saudi Arabia, collected 2023-12-06.

**Comment by aviczhl2** [comment]
> The above GISAID nucleotide query does now identify a second genome (EPI_ISL_18651234), but it has many AA substitutions in ORF1a and ORF1b that differentiate it from the first. I'm hesitant to say these are the same recombinant without more data. I think we would also expect more localized spread in USA-CA if this were truly growing. This other genome is from Singapore but a traveler from Saudi Arabia, collected 2023-12-06.

That one is a recombinant of GW.5.3.1 and JN.1.

**Comment by aviczhl2** [comment]
+1 for the XDE/JN.1 recomb in the proposal. 
Suggest to change query to C1170T,C6501A,T22926C,T28297C

**Comment by aviczhl2** [comment]
+2 more for this.

@AngieHinrichs It seems that they are still not on usher tree despite I add them to recombinants.tsv.

**Comment by aviczhl2** [comment]
+2 EPI_ISL_18837291 and EPI_ISL_18837421

**Comment by FedeGueli** [comment]
> C1170T,C6501A,T22926C

further two samples popped up from France 
total 8

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs It seems that they are still not on usher tree despite I add them to recombinants.tsv.

Ah, there were two different places where I needed to make filtering of long paths less stringent, not just one.  This was being added to the tree every day but then was filtered out.  It should be fixed in tomorrow's build, 2024-01-31.  Thanks for pointing it out @aviczhl2!

**Comment by aviczhl2** [comment]
One more sample.

**Comment by aviczhl2** [comment]
14 seqs now

**Comment by alantsangmb** [comment]
Could XDE still be the donar for them (XDE+JN.1 recombinant), considering that they possess the C7113T (XDE) but lack the C29535T (JN.1)? The potential breakpoint lies between 19326 and 213363.

**Comment by aviczhl2** [comment]
> C1170T,C6501A,T22926C,T28297C

This one is dead anyway. 

> Could XDE still be the donar for them (XDE+JN.1 recombinant), considering that they possess the C7113T (XDE) but lack the C29535T (JN.1)? The potential breakpoint lies between 19326 and 213363.

It can be a 3-BP XDE/JN.1 recomb though, with 3rd BP before 29535. 

Given there exist other clear 3-BP recombs now. https://github.com/sars-cov-2-variants/lineage-proposals/issues/1428

**Comment by aviczhl2** [comment]
+1 Hong Kong with additional S:F456L.

**Comment by Over-There-Is** [comment]
> +1 Hong Kong with additional S:F456L.

and this sequence has no private mutations sharing with other sequences.

**Comment by Over-There-Is** [comment]
breakpoints:
19326\~21608
27915\~28297
28958\~29535
no private mutation

**Comment by aviczhl2** [comment]
+1 Gansu, China. with additional S:G504D

**Comment by aviczhl2** [comment]
> breakpoints: 19326~21608 27915~28297 28958~29535 no private mutation

yeah, more likely a 3-BP XDE/JN.1 recomb.

**Comment by aviczhl2** [comment]
+2 GBW from Hong Kong, with the same T22930A-S:F456L of the Hong Kong local seq.

**Comment by aviczhl2** [comment]
@corneliusroemer  suggest to designate this.  correct query: C1170T,C6501A,T22926C,T28297C

**Comment by aviczhl2** [comment]
One more Germany seq from the S:F456L branch

**Comment by corneliusroemer** [comment]
Indeed looks like a single XDE/JN.1/XDE recombinant - interestingly the 456L is T22930A, which is a lot rarer than T22928C - there's not a single designated JN.1 lineage yet with 22930A as opposed to 22928C

This suggests that 456L was acquired on top of the original recombinant - as opposed to through an independent recombination even involving XDE and a 456L JN.1 sublineage

**Comment by aviczhl2** [comment]
> Indeed looks like a single XDE/JN.1/XDE recombinant - interestingly the 456L is T22930A, which is a lot rarer than T22928C - there's not a single designated JN.1 lineage yet with 22930A as opposed to 22928C
> 
> This suggests that 456L was acquired on top of the original recombinant - as opposed to through an independent recombination even involving XDE and a 456L JN.1 sublineage

It lacks the XDE-defining 29353(which is from its FL.13.4.1 donor), so has to be XDE/JN.1/XDE/JN.1, 3 breakpoints.

**Comment by corneliusroemer** [comment]
Right! It could be either reversion, or 3 breakpoints, or an extra XBB ORF9b:5T donor involved, or reversion of 29535

Lots of options, luckily not really relevant for designation, other than having something reasonable in lineage notes

**Comment by corneliusroemer** [comment]
And there's another one: hCoV-19/Australia/NSW-ICPMR-53316/2024|EPI_ISL_19027110|2024-03-18

Now designated as XDV (this issue) and XDV.1 (with 456L)

**Comment by FedeGueli** [comment]
Now there is one with 346T > FLiRT : EPI_ISL_19110341
