### ISSUE TITLE
#2286(GK.2.1+Orf7b:E39*) +Orf1a:R135S(rev), S:Q14R (82 seqs, 10 countries, 75 with S:V1264L)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2403]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1122

#2286+G670T(Orf1a:R135S rev), A21603G(S:Q14R)

G670T rev seems popular these days.

GISAID query: A21603G, G27870T,C2135A
No. of seqs:50(Canada 1 Denmark 1 UK 2 France 37 Ireland 1 Italy 3 Netherlands 1 Spain 1 USA 3)

First: EPI_ISL_18244283, 2023-8-21, Denmark
Latest: EPI_ISL_18568939, 2023-11-20, France

GISAID query for S:V1264L subbranch: A21603G, G27870T,C2135A,G25352C(43 seqs)

usher places on a Orf1b:2557 flip-flop reversion branch, shall be sub-branch of #2286

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/2286_q14r.json?label=id:node_3731184)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/c0ca78dc-fc8b-457f-8d65-1ab04523187b)

**Comment by FedeGueli** [comment]
49 for the sublineage with 1264L , i suggest to designate this @corneliusroemer

**Comment by AngieHinrichs** [comment]
Yeah, the flip-flop looks wrong, I'll add it to the list to fix, thanks.

**Comment by FedeGueli** [comment]
11/69 from December and multiple countries , i was tracking this woth another query (A21603G,C14599T,G27870T) so i didnt match it with this, but it finds less sequences (65) so better keeping your one. to me this deserves a designation. In december has been very hard for lineages to keep spreading due to the rise of Jn.1 , the ones making it through should be designated (my 2 cents)

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by aviczhl2** [comment]
> 11/69 from December and multiple countries , i was tracking this woth another query (A21603G,C14599T,G27870T) so i didnt match it with this, but it finds less sequences (65) so better keeping your one. to me this deserves a designation. In december has been very hard for lineages to keep spreading due to the rise of Jn.1 , the ones making it through should be designated (my 2 cents)

It is still circulating in Janruary.

**Comment by FedeGueli** [comment]
ping @corneliusroemer this is interestingly convergent with HK-Flips and also with reversion in KH.1 mopre it is not slow but fast obviously less than JN.1 but satrting from a lower point as was GK.2 is still something it is still going. i think that it  could be worth designating it.

**Comment by aviczhl2** [comment]
+1 Germany

**Comment by aviczhl2** [comment]
No new seqs
