### ISSUE TITLE
HK.3.2 sublineage with S:G184A (131 sequences, 16 countries) with S:P1162 diversity(22 S:P1162L and 42 S:P1162T)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2406]
Transferred from sars-cov-2-variants/lineage-proposals#955

HK.3.2> C22591T> G22113C(S:G184A)
Query: C21602A, G22113C (3 dropped out)
Query: Spike_Q14K, Spike_G184A (3 dropped out)
Query for P1162L Branch: C21602A, C22591T, C25047T (Including 2 dropped-out sequences)
Query for dropped-out sequences  on G1721A branch: G1721A, C21602A, C22591T, -G22113C
5 sequences are unable to be searched with nuc query temporally due to GISAID error.

Earliest Sequence: 08-30 Shanghai, China EPI_ISL_18268408
Latest Sequence: 01-25 Tieling, Liaoning, China EPI_ISL_18876887
Regions Detected: 
China 39(Shanxi 6, Yunnan 9, Shanghai 6, Henan 6, Anhui 3, Gansu 3, Sichuan 2, Xinjiang 2, Hubei 1, Liaoning 2), South Korea 37, Japan 18(Hokkaido 9, Niigata 2, Kanagawa 1, Saitama 1, Miyagi 1, Hiroshima 1, Fukuoka 1, Fukushima 1, Yamaguchi 1), Singapore 3(1 from China), Brunei 2, Cambodia 2, Thailand 4(Surat Thani 2, Ratchaburi 1, Songkhla 1), Laos 1(Champasack); 
Denmark 2, France 1(Occitanie), Greece 1(Attica), Sweden 1(Västerbotten), UK 1(England);
Australia 2(Queensland 1, SA 1), New Zealand 1(Hutt Valley);
US 2(Minnesota 1, NY 1)

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_20684_763510.json?label=id:node_11967928
![image](https://github.com/cov-lineages/pango-designation/assets/38100637/775816e7-87f3-442f-8c3c-e81df7ee2105)

<details><summary>Sequences:</summary>

EPI_ISL_18268408, EPI_ISL_18284987, EPI_ISL_18360355,
EPI_ISL_18397574, EPI_ISL_18438469, EPI_ISL_18438507,
EPI_ISL_18442766, EPI_ISL_18454369, EPI_ISL_18459750,
EPI_ISL_18468827, EPI_ISL_18489124, EPI_ISL_18525012,
EPI_ISL_18539614, EPI_ISL_18544066, EPI_ISL_18558211,
EPI_ISL_18590047, EPI_ISL_18593213, EPI_ISL_18593277-18593278,
EPI_ISL_18597085, EPI_ISL_18597219, EPI_ISL_18598013,
EPI_ISL_18602635, EPI_ISL_18602639, EPI_ISL_18602655,
EPI_ISL_18602687, EPI_ISL_18602702, EPI_ISL_18602714,
EPI_ISL_18602737, EPI_ISL_18602750, EPI_ISL_18602774,
EPI_ISL_18602852, EPI_ISL_18602942, EPI_ISL_18602966,
EPI_ISL_18608339, EPI_ISL_18617366, EPI_ISL_18623912,
EPI_ISL_18639717, EPI_ISL_18639742, EPI_ISL_18639783,
EPI_ISL_18659248, EPI_ISL_18660967, EPI_ISL_18672308,
EPI_ISL_18672370, EPI_ISL_18679542, EPI_ISL_18680538,
EPI_ISL_18684519, EPI_ISL_18687654, EPI_ISL_18692898,
EPI_ISL_18694305, EPI_ISL_18694308, EPI_ISL_18703860,
EPI_ISL_18703864, EPI_ISL_18705841, EPI_ISL_18724019,
EPI_ISL_18731639, EPI_ISL_18732911, EPI_ISL_18733010,
EPI_ISL_18733499, EPI_ISL_18733542, EPI_ISL_18734417,
EPI_ISL_18744246, EPI_ISL_18745719, EPI_ISL_18751627,
EPI_ISL_18752000, EPI_ISL_18752113, EPI_ISL_18752150,
EPI_ISL_18758210, EPI_ISL_18769915, EPI_ISL_18769918,
EPI_ISL_18771114, EPI_ISL_18771433, EPI_ISL_18771435,
EPI_ISL_18780184, EPI_ISL_18787321, EPI_ISL_18788898,
EPI_ISL_18788904, EPI_ISL_18791680, EPI_ISL_18791740,
EPI_ISL_18791931, EPI_ISL_18792046, EPI_ISL_18793053-18793054,
EPI_ISL_18793073, EPI_ISL_18793091, EPI_ISL_18819474,
EPI_ISL_18819510, EPI_ISL_18823305, EPI_ISL_18823478,
EPI_ISL_18823513-18823514, EPI_ISL_18823526, EPI_ISL_18823540-18823541,
EPI_ISL_18823551-18823552, EPI_ISL_18823558, EPI_ISL_18823560-18823561,
EPI_ISL_18823580, EPI_ISL_18823613, EPI_ISL_18841667-18841668,
EPI_ISL_18841938, EPI_ISL_18841962, EPI_ISL_18848545,
EPI_ISL_18858616, EPI_ISL_18858715, EPI_ISL_18858816,
EPI_ISL_18858842, EPI_ISL_18858844, EPI_ISL_18866186,
EPI_ISL_18869251, EPI_ISL_18876806, EPI_ISL_18876887,
EPI_ISL_18876967, EPI_ISL_18877024-18877025
</details>

**Comment by Over-There-Is** [comment]
China+12

**Comment by Over-There-Is** [comment]
Denmark+1

**Comment by Over-There-Is** [comment]
Cambodia +2

**Comment by Over-There-Is** [comment]
Both S:P1162L and S:P1162T reaches 13.

**Comment by FedeGueli** [comment]
90, SK

**Comment by Over-There-Is** [comment]
Brunei

**Comment by FedeGueli** [comment]
106. now

**Comment by FedeGueli** [comment]
116 now 10 from January collected in 4 different Asian countries and 2 different provinced of China

cc @corneliusroemer i suggest to designate it.

**Comment by Over-There-Is** [comment]
Yunnan A475V*3 on P1162L branch

**Comment by Over-There-Is** [comment]
US

**Comment by DailyCovidCases** [comment]
This branch is dead, please close this issue

**Comment by Over-There-Is** [comment]
Hainan

**Comment by FedeGueli** [comment]
> Hainan

where do u find it?
