### ISSUE TITLE
HN.4 Sublineage with S:A766S, S:T768N (147 seq, May 3) 

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2408]
### Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/916
**Description**
**Sub-lineage of:** FL.1.5.1 now HN.4 (EDITED)
**Earliest sequence:** 2023-8-1, Washington (state), USA — EPI_ISL_18104048
**Most recent sequence:** 2023-11-25, Canada — EPI_ISL_18581626
**Countries circulating:** USA (51), Canada (40), France (1), Israel (1), Italy (1—travel to USA)
**Number of Sequences:** 95 (subtracting one pooled sequence from Ginkgo Bozoworks)
**GISAID Nucleotide Query:** T2242A, G23858T, C23865A
**CovSpectrum Query:** Nextcladepangolineage:FL.1* & G23858T & C23865A
**Substitutions on top of FL.1.5.1:**
**Spike:** A766S, T768N
**ORF9b:** G31E
**ORF1a:** T403I
**Nucleotide:** C1473T, T2242A, C5986T, G19962T, G23858T, C23865A, C25710T, G28375A

**Phylogenetic Order of Mutations:** HN.4 [= FL.1.5.1 > G28375A (ORF9b:G31E)  **→**  G19962T   **→**  C5986T  **→**  C1473T  (ORF1a:T403I)]  **→**   C25710T  **→**  T2242A  **→**  G23858T, C23865A (S:A766S, S:T768N) 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/FL.1.5.1_A766S_T768N_2023-10-4.json  
<img width="1492" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/5fbe0cb1-1c15-42b3-bc23-dad7818e0029">

**Evidence**
This lineage isn't growing particularly fast or anything, but I find it interesting that two relatively rare S2 mutations, both requiring transversion mutations, would appear together all at once like this. 

S:A766S has only ever occurred in 277 sequences, and 195 of those have been in XBB* lineages. S:T768N has been in 1224 sequences, with about 60% of those in BA.2.9. In 2023 it has been in 110 sequences outside of this lineage. A766S and T768N appear to have been acquired in one jump. After an initial spurt of early August sequences from Washington state, USA, it seemed to die off but has started growing in other regions more recently. It’s worth noting that the WU sequences from Washington often appear months after they were collected, so it’s possible there were sequences collected in the past couple months that haven’t been uploaded yet.

While this seems to be confined to North America, one sequence is from a person who traveled from Italy to the US. 

Obviously, there is one outlier sequence in this lineage, and it is unquestionably from a patient treated with molnupiravir. It was collected September 21 in Washington (state), USA. All 32 private mutations are transitions, and 21/32 are G->A, the type of mutation MOV is known to preferentially create. Furthermore, the nucleotide contexts match those seen in other MOV sequences extremely well, as can be seen at the top of the image below, which—using an amazing tool created by @theosanderson—reports how well the nucleotide contexts of each transition mutation match those seen to predominate in other MOV sequences. 

<img width="1053" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/66e95486-7e93-426c-895e-6a09cf995c8e">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18104048, EPI_ISL_18104058, EPI_ISL_18104063,
EPI_ISL_18104068, EPI_ISL_18104073, EPI_ISL_18212563,
EPI_ISL_18252060, EPI_ISL_18260888, EPI_ISL_18269752,
EPI_ISL_18282445, EPI_ISL_18282677, EPI_ISL_18305161,
EPI_ISL_18305180, EPI_ISL_18305413, EPI_ISL_18310437,
EPI_ISL_18312100, EPI_ISL_18316897, EPI_ISL_18319042,
EPI_ISL_18332609, EPI_ISL_18343894
</details>

**Comment by FedeGueli** [comment]
120 as Jan 04. @corneliusroemer i suggest to designate this one.
