### ISSUE TITLE
Proposal for Lithuanian AY.4 sub-lineage with S:1259Y and ORF1b:472A (~5k sequences)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#241]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: AY.4
Earliest sequence: UK 2021-22
Most recent sequence: Current
Countries circulating: Mostly Lithuania (at peak was 80% of all sequences)

Lineage deriving from AY.4 but with extra Spike mutation S:1259Y and ORF1b:472A. This lineage reached 80% share in Lithuania, probably due to founder effect, since share is now dropping and not rising in any other country.

![image](https://user-images.githubusercontent.com/25161793/136677298-a6dff81d-d8ee-491d-bbb0-6c9d5fba9b4e.png)
https://cov-spectrum.ethz.ch/explore/Lithuania/AllSamples/from=2021-05-01&to=2021-10-10/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22S%3A1259Y%22%2C%22ORF1a%3A2529V%22%2C%22ORF1b%3A472A%22]%7D%2C%22matchPercentage%22%3A1%7D

Genomes (~5k)
[ORF1a:2529V-S:1259Y-nuc:14882C.intersection.txt](https://github.com/cov-lineages/pango-designation/files/7316638/ORF1a.2529V-S.1259Y-nuc.14882C.intersection.txt)

Evidence
![image](https://user-images.githubusercontent.com/25161793/136677355-368d68ec-8ce8-49fb-9665-f6db8d59aa34.png)
https://nextstrain.org/groups/neherlab/ncov/europe?c=gt-ORF1b_472&m=div

Proposed lineage name
AY.4.x

**Comment by andreijl** [comment]
I was also monitoring this and I think it's pretty relevant.
