### ISSUE TITLE
JN.1 (BA.2.86.1.1) sublineage with S:Q183H (243 seqs) 

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#2410]
*Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1096

Defining mutations: JN.1>G22111T (S:Q183H)
GISAID query: G11727A, G22111T, T22926C
Earliest seq: 2023-10-25 (NY, US- EPI_ISL_18499187)
Most recent seq: 2023-12-03 (England, UK- EPI_ISL_18613217)
Countries detected: US (11), UK (10), Canada (6), Japan (2), Sweden (1), Spain (1), Singapore (1)
Usher Tree: 
![联想截图_20231213014604](https://github.com/cov-lineages/pango-designation/assets/121703496/8f307fe0-4480-4023-8630-f62912a927d8)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28fae_895240.json
Notice that S:Q183E is for XBB* lineages. Now JN.1+S:Q183H branch is circulating and we can track it for a time.

Genomes:
EPI_ISL_18499187, EPI_ISL_18499266, EPI_ISL_18504314, EPI_ISL_18505101, EPI_ISL_18513037, EPI_ISL_18517615, EPI_ISL_18520852, EPI_ISL_18520856, EPI_ISL_18545705, EPI_ISL_18553101, EPI_ISL_18577828, EPI_ISL_18578276, EPI_ISL_18578341, EPI_ISL_18578369, EPI_ISL_18578447, EPI_ISL_18581364, EPI_ISL_18581366, EPI_ISL_18581377, EPI_ISL_18581447, EPI_ISL_18583095, EPI_ISL_18583284,
EPI_ISL_18583618, EPI_ISL_18587072, EPI_ISL_18590592, EPI_ISL_18593967, EPI_ISL_18599087, EPI_ISL_18601535, EPI_ISL_18610802, EPI_ISL_18611837, EPI_ISL_18613217, EPI_ISL_18613273, EPI_ISL_18614468

**Comment by HynnSpylor** [comment]
44 seqs now

**Comment by FedeGueli** [comment]
73 now!

**Comment by HynnSpylor** [comment]
72 seqs now and it seems quite fast

**Comment by HynnSpylor** [comment]
121 seqs!

**Comment by HynnSpylor** [comment]
243 seqs now!
There is also a branch with S:T572I (8 seqs in 3 countries), which is also popular in JN.1* seqs
![联想截图_20240106232620](https://github.com/cov-lineages/pango-designation/assets/121703496/f7383ecf-b11f-406d-8ebf-fca815810e64)

**Comment by FedeGueli** [comment]
i bet it will be the first Cornelius' choice when he will be back.

**Comment by FedeGueli** [comment]
@HynnSpylor  i m checking but this should have a S:t572I sublineage wait a min

**Comment by FedeGueli** [comment]
<img width="1171" alt="Screenshot 2024-01-06 alle 23 25 53" src="https://github.com/cov-lineages/pango-designation/assets/87669813/bf0e8f6f-ab60-4098-8084-d9a0534d716a">
Here we come ! it has not only S:T572I but also the EG.5.1 defining Orf1a:A3143V! and it is not small i will track it in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1097 but please add it here in this proposal!

**Comment by HynnSpylor** [comment]
@FedeGueli Thx for pointing out the evolution! I forgot to mention it.
As S:Q183H and S:T572I are two most popular Spike mutations in JN.1* now, the branch may be remarkable.

**Comment by corneliusroemer** [comment]
JN.1.9

**Comment by HynnSpylor** [comment]
Thx @corneliusroemer 
Now the T572I branch also reaches 11

**Comment by HynnSpylor** [comment]
Now JN.1.9 with S:T572I reaches 35. I suggest to open a new issue to track it.

**Comment by FedeGueli** [comment]
> Now JN.1.9 with S:T572I reaches 35. I suggest to open a new issue to track it.

i think it is tracked in the multiple lineage issue about Jn.1 + 572I
