### ISSUE TITLE
FL.1 with ORF1a:T2300I (nsp3_T1482I), ORF1a:K4348R (nsp10_K95R), S:T478R, S:P521T and M:I8V (58 seqs, 12 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2412]
Transferred from sars-cov-2-variants/lineage-proposals#1058

**Defining Mutations:** `FL.1` > `G5917A, C7164T(ORF1a:T2300I), A13308G(ORF1a:K4348R), C14877T` > `C22995G(S:T478R), C23123A(S:P521T), A26544G(M:I8V)`
**Query:** `C7164T, A13308G, C22995G`
**Earliest seq:** 2023-08-02 (`EPI_ISL_18129436`, Wisconsin, USA)
**Latest seq:** 2023-12-04 (`EPI_ISL_18603893`, Noord-Holland, Netherlands)
**Sampled Countries:** Russia (24), UK (6: WS/3; EN/3), Netherlands (5), Israel (4), USA (3), Greece (2), Switzerland (2), China (1), Denmark (1), Ireland (1), Japan (1), Kazakhstan (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18129436, EPI_ISL_18238370, EPI_ISL_18246964, EPI_ISL_18276299, EPI_ISL_18300085, EPI_ISL_18331416, EPI_ISL_18339107, EPI_ISL_18340038, EPI_ISL_18356282, EPI_ISL_18360490, EPI_ISL_18411854, EPI_ISL_18416719-18416720, EPI_ISL_18417199, EPI_ISL_18417425, EPI_ISL_18417580, EPI_ISL_18417602, EPI_ISL_18417629, EPI_ISL_18417689-18417690, EPI_ISL_18419982, EPI_ISL_18421296, EPI_ISL_18429135, EPI_ISL_18440409, EPI_ISL_18440434, EPI_ISL_18444569, EPI_ISL_18450591, EPI_ISL_18451030, EPI_ISL_18455020, EPI_ISL_18464822, EPI_ISL_18486475, EPI_ISL_18487011, EPI_ISL_18487311, EPI_ISL_18487383, EPI_ISL_18487761, EPI_ISL_18491380, EPI_ISL_18491600, EPI_ISL_18505722, EPI_ISL_18559909, EPI_ISL_18561309, EPI_ISL_18561411, EPI_ISL_18561517, EPI_ISL_18579931, EPI_ISL_18579946, EPI_ISL_18579956, EPI_ISL_18580092, EPI_ISL_18580128, EPI_ISL_18580178, EPI_ISL_18603893, EPI_ISL_18606526, EPI_ISL_18612844`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_179ef_c1c050.json?f_userOrOld=uploaded%20sample&label=id:node_3384110
![image](https://github.com/cov-lineages/pango-designation/assets/125747944/8dec7cf0-b027-4dc6-9d19-101ee3d3b215)

**Trivia:**
- Already seen a couple of recombinant with `XBB.2.3*` (placed at the bottom of the tree) : `Russia/PRI-RII-MH145732S/2023|EPI_ISL_18417689|2023-09-14` and `Russia/SPE-RII-MH145868S/2023|EPI_ISL_18416719|2023-10-03`
- About 3% prevalence in Russia

**Comment by FedeGueli** [comment]
Designated FL.1.8 vi https://github.com/cov-lineages/pango-designation/commit/b89aa1c34d3cfbaebc1c67c4b0eeffa421291719
