### ISSUE TITLE
Another branch of XBB.1.16.6+S:L455F(70 seqs, 10 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2413]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1059

XBB.1.16.6+T23986C+C29296T+C26192T(Orf3a:P267L)+G463A,G22927T(S:L455F)

GISAID query: G463A,C26192T
No. of seqs: 50(Germany 20 Austria 1 Australia 1 Finland 1 Sweden 3 Canada 1 France 3 Ireland 19 UK 1)

First: EPI_ISL_18343008, Germany, 2023-9-13
Latest: EPI_ISL_18626811, Ireland, 2023-12-10

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/xbb_1_16_6_l455f.json?label=id:node_3254611)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/76eab82f-92b7-4cab-99eb-31e1bb211a67)

**Comment by aviczhl2** [comment]
59, USA

**Comment by FedeGueli** [comment]
nothing from january yet

**Comment by aviczhl2** [comment]
Dead
