### ISSUE TITLE
how to select representative sequences for each lineage?

### ISSUE THREAD

**Issue by liamxg** [cov-lineages/pango-designation#2416]
Dear @pango-designation team,

Could I know how to select representative sequences for each lineages? Hope can help me out, thanks.

**Comment by FedeGueli** [comment]
do you mean one per lineages or all sequences used to define one lineage? If it is the latter you can check lineages.csv

**Comment by FedeGueli** [comment]
> Dear @FedeGueli,
> 
> may be 3 of representative sequences per lineage?

So you can use Lineages.CSV https://github.com/cov-lineages/pango-designation/commit/42e991c

**Comment by AngieHinrichs** [comment]
@liamxg, @corneliusroemer's repository https://github.com/corneliusroemer/pango-sequences might be what you're looking for.

**Comment by DailyCovidCases** [comment]
Please close this issue
