### ISSUE TITLE
could I know the sequences from lineages.csv file are all from GISAID or some from Genbank?

### ISSUE THREAD

**Issue by liamxg** [cov-lineages/pango-designation#2418]
Dear @pango-designation,

Could I know the the sequences from lineages.csv file are all from GISAID or some from Genbank? Thanks.

**Comment by Memorablea** [comment]
All from GISAID

**Comment by AngieHinrichs** [comment]
Initially only GISAID sequences were used, but for the past couple of years or so a mix of GISAID and INSDC or CNCB sequence names from the UShER tree have been used.  

In retrospect it would have been better to include sequence accessions along with the names.  Not only would that make the source of each sequence more clear, but also the same name is sometimes used for more than one sequence and the accessions would help to distinguish those cases.  But at this point there are over 2.5 million names in lineages.csv, so updating it to include accessions would require a significant effort.

**Comment by AngieHinrichs** [comment]
Hopefully they can all be found if you paste or upload the sequence names into https://usher.bio/ , and then you can click from the results into a Nextstrain view of a subtree with more sequences including the ones whose names you uploaded.  (For pango work, you will want to increase usher.bio's default subtree size of 50 to something much larger like 500 or more.). The subtree names will include accessions like EPI_ISL_... for GISAID sequences, C_AA... for CNCB [GenBase](https://ngdc.cncb.ac.cn/genbase/) sequences, or two-letter six-number for INSDC (GenBank, ENA, DDBJ) sequences that you can download from [NCBI Virus](https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/virus?SeqType_s=Nucleotide&VirusLineage_ss=Severe%20acute%20respiratory%20syndrome%20coronavirus%202,%20taxid:2697049).  I think GenBase also offers downloads of INSDC sequences, but I have not tried that in a long time.

The Nextstrain subtree view has a "DOWNLOAD DATA" link towards the bottom of the page that can give a file with all sequence names including accessions.

So, I'm sorry that there is not a single website where you can conveniently download all the sequences by name -- but whatever you cannot find on GISAID, hopefully you can download from the GenBase and/or NCBI Virus portals.

If there are still sequences that you cannot find, please provide their names.  (Another problem with using only names and not accessions is that sometimes names are changed.  If this has happened then we should update lineages.csv.)

**Comment by Over-There-Is** [comment]
some chinese sequences share same name on genbase, like CHN/MSCDC-3/2023. @AngieHinrichs

**Comment by AngieHinrichs** [comment]
> some chinese sequences share same name on genbase, like CHN/MSCDC-3/2023. @AngieHinrichs

Yes, that is unfortunate.  The name "CHN/MSCDC-4/2023" already caused trouble for a new lineage designation because it matches several different sequences in the tree in different lineages.  I sent an email to a contact at GenBase, asking if they could reach out to the submitter to ask them to submit distinct names for those different sequences, but have not heard a reply.  If more people email them, then maybe it will help to get their attention.

**Comment by DailyCovidCases** [comment]
Please close this issue
