### ISSUE TITLE
JN.1 + 2-nuc ORF1b:V1271T (495 seq; Dec 29)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2419]
### **Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1143**
**Description**
**Sub-lineage of:** JN.1
**Earliest sequence:** 2023-10-30, France – EPI_ISL_18510103
**Most recent sequence:** 2023-11-22, Israel – EPI_ISL_18572353
**Continents circulating:** Asia (38), Europe (5), Oceania (1), North America (1)
**Countries circulating:** Singapore (36), France (3), Israel (2), Switzerland (2), Australia (1), Canada (1)
**Number of Sequences:** 45
**GISAID Nucleotide Query:** C897A, G17278A, T17279C
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & G17278A & T17279C
**Substitutions on top of JN.1:**
**ORF1b:** V1271T (NSP13_V348T)
**Nucleotide:** G17278A, T17279C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1_G17278A_T17279C.json?c=gt-ORF1ab_5672&gmax=21555&gmin=266&label=id:node_4491220

<img width="1490" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f0a6fe52-f89f-4e66-a02b-df5a58fff02a">

**Evidence**
Two-nuc mutations are rare, but this one has emerged several times independently—most recent in FL.16.3, XBB.1.16, and JG.3—which might indicate strong selection pressure. Or perhaps it’s just some unusual replication error that randomly occurs now and then. 

<img width="1390" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d49d6a90-37e0-4f4d-bd7a-879e19d91fe9">

It’s possible this is actually two separate lineages. Five of the sequences have ORF7a:T28I, also found on another branch of JN.1. Usher joins these two together and give about 40 of the 45 sequences in this lineage an ORF7a:I28T reversion. Most likely ORF7a:T28I was acquired separately by the other branch and the five sequences in this branch. The other possibility is that the 2-nuc ORF1b:A1271T was acquired twice independently. 

Curiously, two sequences on this branch have S:R683Q and one has S:P681S, both of which would abolish the FCS. Two others, from France, allegedly have S:R681P. Hard to take reversions like that seriously until you see it from multiple different labs, however. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18510103, EPI_ISL_18524417, EPI_ISL_18541866,
EPI_ISL_18541869, EPI_ISL_18544451, EPI_ISL_18544456,
EPI_ISL_18544544, EPI_ISL_18544568, EPI_ISL_18544576,
EPI_ISL_18544579, EPI_ISL_18544588, EPI_ISL_18544592,
EPI_ISL_18544610, EPI_ISL_18544689, EPI_ISL_18544691,
EPI_ISL_18544700-18544701, EPI_ISL_18544719, EPI_ISL_18544726-18544727,
EPI_ISL_18544735, EPI_ISL_18544754, EPI_ISL_18544763,
EPI_ISL_18544773, EPI_ISL_18544776, EPI_ISL_18544781,
EPI_ISL_18544783, EPI_ISL_18544794, EPI_ISL_18544804-18544805,
EPI_ISL_18544812, EPI_ISL_18544819-18544820, EPI_ISL_18544836,
EPI_ISL_18544842, EPI_ISL_18544857, EPI_ISL_18544872,
EPI_ISL_18544880-18544881, EPI_ISL_18544884, EPI_ISL_18551379,
EPI_ISL_18553476, EPI_ISL_18569059, EPI_ISL_18572344,
EPI_ISL_18572353 </details>

**Comment by FedeGueli** [comment]
This is also high in Malaysia 25% of samples there

**Comment by AngieHinrichs** [comment]
> Usher joins these two together and give about 40 of the 45 sequences in this lineage an ORF7a:I28T reversion. Most likely ORF7a:T28I was acquired separately by the other branch and the five sequences in this branch. 

Yeah, that would be my guess too.  I will try a little prune/re-opt/re-place to see if I can at least get rid of the flip-flop on 27476 (ORF7a:28).

**Comment by FedeGueli** [comment]
5% of samples in Indonesia in Decmber . now 378

**Comment by alurqu** [comment]
![Screenshot 2023-12-25 at 23-45-11 SARS-CoV-2 wuhCor1 NC_045512v2 17268-17288 UCSC Genome Browser v458](https://github.com/cov-lineages/pango-designation/assets/88959107/047163ce-8f88-48cd-818e-82af2a3f6c43)
If I'm correct, G17278A T17279C yields an RNA sequence of AAACGAAU which differs from the canonical sarbecoronavirus TRS-B in only the last nucleotide being U instead of C. Could this function as a new suboptimal TRS-B?

If so, the next potential start codon I see would be at out-of-frame starting at 17300 but running not far with a stop codon in that frame starting at 17315 yielding only MSFVL. Unless that is some high-value signaling molecule, it would seem a waste of energy for the virus to produce an sgmRNA for this. So perhaps this is not significant or the trailing U reduces the sgmRNA transcription cost.

**Comment by ryhisner** [comment]
Oh, dang, you're right. Nice spot! Not sure how I missed that one, but it's definitely just one nuc away from the optimal TRS. I think the final C is pretty essential, so I don't think this would result in the transcription of much of anything. But it could be a clue that this 2-nuc mutation formed through some sort of recombination with the TRS-L. Normally, you'd expect to see more than 7 matching nucs or at least some pretty good extended homology, but not always.

**Comment by FedeGueli** [comment]
great catch @alurqu . btw this is 390 now with the last 47 samples coming from outside Singapore and from 9 different countries. Now with these additional data @corneliusroemer i would not wait to designate it.

**Comment by ryhisner** [comment]
There are, uh...102 new sequences of this lineage today from Singapore out of 495 sequences uploaded from there today, so over 20%.

**Comment by FedeGueli** [comment]
> There are, uh...102 new sequences of this lineage today from Singapore out of 495 sequences uploaded from there today, so over 20%.

Yeah i have to say that means it is pretty stable cause it was floating around 20 25 if i am not wrong.

**Comment by corneliusroemer** [comment]
Stretches of As (or any nucleotide) are always prone to sequencing errors as well, that could in general explain homoplasy as well. Not saying that's the case here though - especially given it's reliably called in a number of countries.
