### ISSUE TITLE
JY.1/XBB.1.16.24 recombinant with S:N641S and ORF1a:S2535L (67 sequences - 12 countries )

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2420]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1067

**First spotted and described by Ryan Hisner @ryhisner**  _all credits to him._

Another recombinant XBB.2.3/XBB.1.16 recombinant emerging from India.

This time the recombination is quite clear with a single Breakpoint
1-23522  < JY.1
BP
25410- 3'end of genome < XBB.1.16.24

[JY.1 Donor](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2d7e5_a33d50.json?c=gt-ORF8_8&gmax=28259&gmin=27894&label=id:node_3967139)
[XBB.1.16.24 donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34d30_ac30b0.json?f_userOrOld=uploaded%20sample&label=id:node_3265326): 

_Private mutations_:
T2552C, C5173T ,C7869T (**ORF1a:S2535L**), T10891C, A23484G (**S:N641S**)  

_Mutations from_ **JY.1:** C4234T, ORF1a:P1786L (C5622T), ORF1a:G2091S (G6536A),  C7303A,ORF1a:P3504L (C10776T), ORF1b:K2579R (A21203G) , S:G184V (G22113T), ,S:D253G (A22320G),  C22624T, S:P521S (C23123T),S:E654K (G23522A)

_Mutations from_ **XBB.1.16.24** : A25410G, Orf3a:E194K (G25972A), Orf8:G8* (G27915T), Orf9b:I5T (T28297C), Orf9b:N55S (A28447G), C29386T

_Diagram:_
![Schermata 2023-11-08 alle 00 24 36](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/842c7a48-5fe1-48f5-9cc8-f76a9776ef11)
https://cov-spectrum.org/explore/World/AllSamples/Y2023/variants?nucMutations=A25410G%2CG25972A%2CC7869T&nucMutations1=G27915T%2CA28447G%2CC29386T%2CA25410G%2CG25972A%2C25410G&nextcladePangoLineage1=XBB.1.16.24*&nextcladePangoLineage2=JY.1*&analysisMode=CompareEquals&

_Tree:_
![Schermata 2023-12-20 alle 10 14 05](https://github.com/cov-lineages/pango-designation/assets/87669813/e1989a90-817b-402a-8e1d-8623bfabb5bc)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_16feb_2b02f0.json?label=id:node_4016155
 

_Gisaid query_: **A25410G, G25972A, C7869T**

_Samples:_ 44
First collected on 2023-09-12 in Illinois - Us
EPI_ISL_18233959, EPI_ISL_18315295, EPI_ISL_18326042,
EPI_ISL_18331958, EPI_ISL_18362750, EPI_ISL_18379967,
EPI_ISL_18379983, EPI_ISL_18421357, EPI_ISL_18438651,
EPI_ISL_18439804, EPI_ISL_18441663, EPI_ISL_18444719,
EPI_ISL_18452226, EPI_ISL_18454881, EPI_ISL_18457552,
EPI_ISL_18457741, EPI_ISL_18464696, EPI_ISL_18487320,
EPI_ISL_18494480, EPI_ISL_18497366, EPI_ISL_18523631,
EPI_ISL_18531518, EPI_ISL_18531531, EPI_ISL_18537855,
EPI_ISL_18537901, EPI_ISL_18544919-18544920, EPI_ISL_18545047,
EPI_ISL_18551558, EPI_ISL_18553085, EPI_ISL_18578102,
EPI_ISL_18585285, EPI_ISL_18585337, EPI_ISL_18601590,
EPI_ISL_18605624, EPI_ISL_18605626, EPI_ISL_18605883,
EPI_ISL_18621015, EPI_ISL_18621301, EPI_ISL_18638524,
EPI_ISL_18640721, EPI_ISL_18644467, EPI_ISL_18644525,
EPI_ISL_18659072

Countries:
![Schermata 2023-12-20 alle 10 14 26](https://github.com/cov-lineages/pango-designation/assets/87669813/b7ce01cf-41dd-4b41-8748-59b512440fbb)

Additional notes:
Looking at the tree this is displaying some diveristy with some saltation branch and some spike mutation especially S:K528R recently found in US.

**Comment by mrkylesmith** [comment]
I believe this description also closely matches what RIVET identifies, with some differences worth noting below.

The SNP plot for the closest match to your description that I found on our latest RIVET analysis:
![node_1308908_trio](https://github.com/cov-lineages/pango-designation/assets/52357182/81c852b0-cbb7-4cc8-93ac-8dbf800adc0d)


The corresponding node id from analysis done on the Dec 17 UShER-MAT is node_1308908. It is inferred as a recombinant between JY.1 and XBB.1.16. The predicted breakpoint interval matches what is listed above,(23522,25410), as seen in the SNP plot above.  The RIVET analysis yields the number of samples as 48 and the Chronumental-inferred origin date as 2023-08-29.

I have also attached the list of descendants for the recombinant node: 
[node_1308908_descendants.txt](https://github.com/cov-lineages/pango-designation/files/13758024/node_1308908_descendants.txt)


RIVET infers the recombinant node at this long branch shown below, with a few of the mentioned private mutations above, coming from JY.1 (T2552C, C5173T, T10891C).
<img width="960" alt="JY 1" src="https://github.com/cov-lineages/pango-designation/assets/52357182/077c101e-29a0-4041-bb47-b5af2088e950">



Further analysis can be seen at [https://rivet.ucsd.edu/](https://rivet.ucsd.edu/) and searching for node id: `node_1308908` in the search bar.  I hope this is helpful, and curious to hear any thoughts/feedback!

**Comment by FedeGueli** [comment]
> I believe this description also closely matches what RIVET identifies, with some differences worth noting below.
> 
> The SNP plot for the closest match to your description that I found on our latest RIVET analysis: ![node_1308908_trio](https://private-user-images.githubusercontent.com/52357182/292608943-81c852b0-cbb7-4cc8-93ac-8dbf800adc0d.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMTY4MTksIm5iZiI6MTcwMzMxNjUxOSwicGF0aCI6Ii81MjM1NzE4Mi8yOTI2MDg5NDMtODFjODUyYjAtY2JiNy00Y2M4LTkzYWMtOGRiZjgwMGFkYzBkLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDA3MjgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyOThlMTYwNTczNTZhYWQ0MjFjOWExNjQxODBhMjExZWY0NzUzNmNmMjJkZDdmMDc2ZDFkNjE5NDVhOGM1YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BIC3CdwIOA8lT7TtqsWuh_PWJGSWy1dsRt4SjKYdRgU)
> 
> The corresponding node id from analysis done on the Dec 17 UShER-MAT is node_1308908. It is inferred as a recombinant between JY.1 and XBB.1.16. The predicted breakpoint interval matches what is listed above,(23522,25410), as seen in the SNP plot above. The RIVET analysis yields the number of samples as 48 and the Chronumental-inferred origin date as 2023-08-29.
> 
> I have also attached the list of descendants for the recombinant node: [node_1308908_descendants.txt](https://github.com/cov-lineages/pango-designation/files/13758024/node_1308908_descendants.txt)
> 
> RIVET infers the recombinant node at this long branch shown below, with a few of the mentioned private mutations above, coming from JY.1 (T2552C, C5173T, T10891C). <img alt="JY 1" width="960" src="https://private-user-images.githubusercontent.com/52357182/292608971-077c101e-29a0-4041-bb47-b5af2088e950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMTY4MTksIm5iZiI6MTcwMzMxNjUxOSwicGF0aCI6Ii81MjM1NzE4Mi8yOTI2MDg5NzEtMDc3YzEwMWUtMjlhMC00MDQxLWJiNDctYjVhZjIwODhlOTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDA3MjgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNTQ3ZmE2YjM4ZjQxZDA0ZjY4NDM2NmFhMmRhNjEwZDE5Y2U1NjNjZjllNGZiNjJiOTk5NWI3YzUwMzk0NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aFriMrZwDFb9dOrp885naIeRmQ2crpsUYUs42JUe9HU">
> 
> Further analysis can be seen at https://rivet.ucsd.edu/ and searching for node id: `node_1308908` in the search bar. I hope this is helpful, and curious to hear any thoughts/feedback!

thank you for the analysis, i am not a specialist of recombinants, one thing: i think that the donor is a branch of XBB.1.16.24 with Orf3a:E194K   tough.

**Comment by aviczhl2** [comment]
51 now

**Comment by FedeGueli** [comment]
58. now

**Comment by FedeGueli** [comment]
Last sample came  from India (December)

**Comment by aviczhl2** [comment]
65 now

**Comment by FedeGueli** [comment]
> 65 now

and most importantly one sample in 2024 so it made it through the new year.

**Comment by FedeGueli** [comment]
66, one sample only from January likely dying off.

**Comment by FedeGueli** [comment]
Likely dead
