### ISSUE TITLE
HK.3.2 sublineage with S:A352S(41 sequences, 8 countries, mainly in Scandinavia)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2421]
Transferred from sars-cov-2-variants/lineage-proposals#955

HK.3.2> C22591T> G1186T, C3425T(Orf1a:P1054S)> C27513T> G22616T(S:A352S), T25159C
Query: C21602A, T25159C, C27513T

Earliest Sequence: 09-25 Straßburg, Grand Est, France EPI_ISL_18376149
Latest Sequence: 01-03 Finland EPI_ISL_18832792
Regions Detected:
Finland 20, Sweden 6(Norrbotten 2, Västernorrland 2, Uppsala 1, Västerbotten 1), Germany 4(Berlin 2, Sachsen-Anhalt 2), UK 4(England 3, Wales 1), France 1(Grand Est), Greece 1(Attica);
Singapore 3, Malaysia 1(Johor)

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_20684_763510.json?label=id:node_3551104
![2023-12-22 (2)](https://github.com/cov-lineages/pango-designation/assets/38100637/d4a88411-4644-4623-9bc2-4d690a1e830d)

<details><summary>Sequences:</summary>

EPI_ISL_18376149, EPI_ISL_18407103, EPI_ISL_18445032,
EPI_ISL_18451674, EPI_ISL_18473586, EPI_ISL_18500597,
EPI_ISL_18521511, EPI_ISL_18521514, EPI_ISL_18541276,
EPI_ISL_18541286, EPI_ISL_18541323, EPI_ISL_18541417,
EPI_ISL_18541429, EPI_ISL_18541441, EPI_ISL_18541448,
EPI_ISL_18552774, EPI_ISL_18585478, EPI_ISL_18587042,
EPI_ISL_18589925, EPI_ISL_18614140, EPI_ISL_18624769,
EPI_ISL_18634939, EPI_ISL_18634988, EPI_ISL_18635131,
EPI_ISL_18635137, EPI_ISL_18635260, EPI_ISL_18635385,
EPI_ISL_18661559, EPI_ISL_18661562, EPI_ISL_18661898,
EPI_ISL_18668044, EPI_ISL_18698136, EPI_ISL_18713094,
EPI_ISL_18713107, EPI_ISL_18713209, EPI_ISL_18713283,
EPI_ISL_18713300, EPI_ISL_18713303, EPI_ISL_18766943,
EPI_ISL_18832792
</details>

**Comment by DailyCovidCases** [comment]
This branch is dead, please close this issue

**Comment by DailyCovidCases** [comment]
It seems that this branch has stopped growing. You should close this. @Over-There-Is

**Comment by DailyCovidCases** [comment]
@Over-There-Is Please close this issue
