### ISSUE TITLE
HK.3 / XBB.2.3.8 recombinant with "FLippeR" (17 seq, KR 16, SG 1)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2422]
Spotted by @corneliusroemer in sars-cov-2-variants/lineage-proposals#1136 firstly.

HK.3 / XBB.2.3.8

Query: C2675T, C10834T, T23797C

Earliest Sequence: 09-27 South Korea EPI_ISL_18461089
Latest Sequence: 12-07 Singapore EPI_ISL_18651059
Regions Detected: South Korea 16, Singapore 1

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_b794_471c20.json?c=country&label=id:node_3470773
![2023-12-22 (3)](https://github.com/cov-lineages/pango-designation/assets/38100637/583226d6-0d41-4bea-94d0-eb14dbcab391)

Mutations based on XBB+S:S486P: C2334T(Orf1a:A690V), **C2675T(Orf1a:P804S)**, G5720A(Orf1a:G1819S), C6541T, C9693T(Orf1a:A3143V), **C10834T**, C12789T(Orf1a:T4175I), G13627A(Orf1b:D54N), A16878T, A18492G, G21718T(S:Q52H), G22317T(S:G252V), C22480T, G22927T(S:L455F), T22930A(S:F456L) / A22995G(S:K478R), C23123T(S:P521S), **T23797C**, C27431T(Orf7a:A13V), **A29534T**, G29706T

Breakpoint: 22930\~22995
3' donor is XBB.2.3.8> T23797C> _G19563A_, _T22579C_> A29534T, most with further > _C5986T_> _A15005C_.
5' donor could be HK.3+C2675T or HK.3+C10834T, I think the latter could be more possible. There is a HK.3> C10834T> _T28672A_ branch circulates in South Korea.

<details><summary>Sequences:</summary>

EPI_ISL_18461089, EPI_ISL_18461103, EPI_ISL_18511642,
EPI_ISL_18539618, EPI_ISL_18564912, EPI_ISL_18564922,
EPI_ISL_18564933-18564934, EPI_ISL_18564945, EPI_ISL_18597191,
EPI_ISL_18597426, EPI_ISL_18639508, EPI_ISL_18639697,
EPI_ISL_18639784, EPI_ISL_18651059, EPI_ISL_18686847,
EPI_ISL_18686891
</details>

**Comment by FedeGueli** [comment]
very interesting one. we will see how Flip goes with a mostly XBB.2.3 backbone for accesory proteins.

**Comment by FedeGueli** [comment]
> C2675T, C10834T, T23797C

new samples lacking

**Comment by FedeGueli** [comment]
it seems dead
