### ISSUE TITLE
BA.2.86.1 with S:S680F （179seqs）

### ISSUE THREAD

**Issue by Memorablea** [cov-lineages/pango-designation#2424]
from sars-cov-2-variants/lineage-proposals/issues/1182

BA.2.86.1 with S:S680F
Country:China,Singapore,Germany,Thailand,New Zealand
GISAID seach：A7842, C23601T, C29614T
THX for @Over-There-Is

**Comment by Memorablea** [comment]
Indonesia+1 23seqs

**Comment by Over-There-Is** [comment]
Singapore/R94MR134/2023|EPI_ISL_18701018|2023-12-18 from China

**Comment by FedeGueli** [comment]
25 seqs now.

**Comment by Memorablea** [comment]
> Singapore/R94MR134/2023|EPI_ISL_18701018|2023-12-18 from China

+1


> Indonesia in December

+1

25seqs now.THX @Over-There-Is @FedeGueli

**Comment by Memorablea** [comment]
26 now

**Comment by Memorablea** [comment]
Japan +1 27now

**Comment by Memorablea** [comment]
68 now

**Comment by Memorablea** [comment]
87seqs now

**Comment by Memorablea** [comment]
93

**Comment by Memorablea** [comment]
@corneliusroemer

**Comment by Memorablea** [comment]
95

**Comment by FedeGueli** [comment]
@Memorablea  i think mthe title is wrong this is BA.2.86.1 isn't it?

**Comment by Memorablea** [comment]
> @Memorablea i think mthe title is wrong this is BA.2.86.1 isn't it?

Yes,you are right.Thank for you！

**Comment by Memorablea** [comment]
115

**Comment by Memorablea** [comment]
120

**Comment by Memorablea** [comment]
146 now

**Comment by Memorablea** [comment]
@FedeGueli @corneliusroemer

**Comment by aviczhl2** [comment]
188 now

**Comment by aviczhl2** [comment]
Designated JN.14
