### ISSUE TITLE
JN.1.4+C28201T（ORF8:S103L）（5678seqs）

### ISSUE THREAD

**Issue by Memorablea** [cov-lineages/pango-designation#2426]
from github.com/sars-cov-2-variants/lineage-proposals/issues/1171
GISAID seach ：`T18453C,C28201T,A7842, C8293T, G8393A`
On the basis of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1155 T18471C.
![image](https://github.com/cov-lineages/pango-designation/assets/125779492/60c62374-1d93-4e42-b371-312ee364583a)

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by Memorablea** [comment]
Add the latest UshER tree 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_b916_a664f0.json?f_userOrOld=uploaded%20sample
![image](https://github.com/cov-lineages/pango-designation/assets/125779492/74086735-a7bf-444a-be6d-d43df91ebf44)

**Comment by ryhisner** [comment]
There's a 68-sequence lineage with the classic 3-nucleotide ORF1b TRS mutation in this branch that is either entirely confined or almost entirely confined to Israel. 
<img width="1012" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/c0a49a63-750d-4469-9dcd-2339d762ae7f">

**GISAID Nucleotide Query:** C774T, C21302T, C21304A, T27810C, -C1762A, -A13278G, -C28528T
**Usher Tree:** https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1__C21302T_C21304A_G21305A_C28201T.json?c=gt-nuc_21302&gmax=22302&gmin=20302&label=id:node_6810451
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18616083, EPI_ISL_18616126, EPI_ISL_18673123,
EPI_ISL_18673128, EPI_ISL_18673134, EPI_ISL_18673138,
EPI_ISL_18673142, EPI_ISL_18673146, EPI_ISL_18673148,
EPI_ISL_18673151, EPI_ISL_18673153-18673155, EPI_ISL_18673160,
EPI_ISL_18673165, EPI_ISL_18673167, EPI_ISL_18673172,
EPI_ISL_18673175-18673176, EPI_ISL_18673182, EPI_ISL_18673186,
EPI_ISL_18673200, EPI_ISL_18673204, EPI_ISL_18683452,
EPI_ISL_18683454, EPI_ISL_18683474, EPI_ISL_18683480,
EPI_ISL_18683482, EPI_ISL_18683491, EPI_ISL_18683493,
EPI_ISL_18683496-18683497, EPI_ISL_18683520, EPI_ISL_18683524,
EPI_ISL_18683526, EPI_ISL_18683538, EPI_ISL_18683542,
EPI_ISL_18683546-18683548, EPI_ISL_18683571-18683572, EPI_ISL_18683574-18683575,
EPI_ISL_18683577-18683578, EPI_ISL_18683584, EPI_ISL_18683595,
EPI_ISL_18700196, EPI_ISL_18700203, EPI_ISL_18700218-18700220,
EPI_ISL_18700228, EPI_ISL_18700231, EPI_ISL_18700233,
EPI_ISL_18700239-18700240, EPI_ISL_18700242, EPI_ISL_18700251-18700252,
EPI_ISL_18700257, EPI_ISL_18700261, EPI_ISL_18700267-18700268,
EPI_ISL_18700270, EPI_ISL_18700272, EPI_ISL_18701887,
</details>

**Comment by FedeGueli** [comment]
> There's a 68-sequence lineage with the classic 3-nucleotide ORF1b TRS mutation in this branch that is either entirely confined or almost entirely confined to Israel. First sequences was November 29, and 54/68 have collection dates of Dec 10 or later. 28/68 were collected on or after Dec 15. <img alt="image" width="1012" src="https://private-user-images.githubusercontent.com/33738461/293402199-c0a49a63-750d-4469-9dcd-2339d762ae7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4OTIwMjksIm5iZiI6MTcwMzg5MTcyOSwicGF0aCI6Ii8zMzczODQ2MS8yOTM0MDIxOTktYzBhNDlhNjMtNzUwZC00NDY5LTlkY2QtMjMzOWQ3NjJhZTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDIzMTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZjM2ZTZiNzFjMDc4ZDJkNjRjMjkxODQ0NzNlYWMwYjM3MmU2ZjU2YTYzMzQwZTQyZWU4NDkxOWU1NjAyZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VfKJ8ehS_FsXEdhwxiVvDCVLzEgmvhJcBMzGe4qaTOQ">
> 
> **GISAID Nucleotide Query:** C774T, C21302T, C21304A, T27810C, -C1762A, -A13278G, -C28528T **Usher Tree:** https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1__C21302T_C21304A_G21305A_C28201T.json?c=gt-nuc_21302&gmax=22302&gmin=20302&label=id:node_6810451 <img alt="image" width="975" src="https://private-user-images.githubusercontent.com/33738461/293403047-4c1852ac-1521-4529-8d63-eaa1f6058513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4OTIwMjksIm5iZiI6MTcwMzg5MTcyOSwicGF0aCI6Ii8zMzczODQ2MS8yOTM0MDMwNDctNGMxODUyYWMtMTUyMS00NTI5LThkNjMtZWFhMWY2MDU4NTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDIzMTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNjZlZDRlZTJmNjk5NTRiMDM1M2M5YzllZjFhOWNkZGNjOGE0YjU4NzE3ZjkzZDI3ZDI4ZWJkOWE5NGU3ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VymYkG_iHlKvTbOUhujhnYQQbWAcoImeTld7yLJISuE">
> 
> **Genomes**
> 
> Genomes

most of them with PLPro_T277I too.

**Comment by Memorablea** [comment]
1212seqs now

**Comment by Memorablea** [comment]
1272 now

**Comment by Memorablea** [comment]
1301now

**Comment by Memorablea** [comment]
1354now @AngieHinrichs @corneliusroemer

**Comment by Memorablea** [comment]
1674now @corneliusroemer @FedeGueli

**Comment by Memorablea** [comment]
1851now

**Comment by Memorablea** [comment]
2459 now

**Comment by Memorablea** [comment]
3596

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by Memorablea** [comment]
3866

**Comment by Memorablea** [comment]
@corneliusroemer @FedeGueli @AngieHinrichs

**Comment by Memorablea** [comment]
4063

**Comment by Mydtlwn** [comment]
This one may need to be designated quickly, plus there are some sub-branches of this branch that are also very interesting.   @corneliusroemer

**Comment by Memorablea** [comment]
@corneliusroemer

**Comment by Memorablea** [comment]
5067

**Comment by Memorablea** [comment]
5678

**Comment by Memorablea** [comment]
Currently 6598 seqs, due to excessive total number, it may not be specified, so the update will be stopped @FedeGueli

**Comment by FedeGueli** [comment]
> Currently 6598 seqs, due to excessive total number, it may not be specified, so the update will be stopped @FedeGueli

thank you @Memorablea for tracking this, not sure if @corneliusroemer wants to designate it

**Comment by FedeGueli** [comment]
Designated JN.1.4.5 via https://github.com/cov-lineages/pango-designation/commit/72ac2581c7b6f9866c9e4443191d4565db19678c

**Comment by Memorablea** [comment]
THX

**Comment by Memorablea** [comment]
> There's a 68-sequence lineage with the classic 3-nucleotide ORF1b TRS mutation in this branch that is either entirely confined or almost entirely confined to Israel. First sequences was November 29, and 54/68 have collection dates of Dec 10 or later. 28/68 were collected on or after Dec 15. <img alt="image" width="1012" src="https://private-user-images.githubusercontent.com/33738461/293402199-c0a49a63-750d-4469-9dcd-2339d762ae7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjQxMjUsIm5iZiI6MTcxMDQyMzgyNSwicGF0aCI6Ii8zMzczODQ2MS8yOTM0MDIxOTktYzBhNDlhNjMtNzUwZC00NDY5LTlkY2QtMjMzOWQ3NjJhZTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEzNDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YTkyNDM2Zjg3NmJhNjQ1OWQ4ZmI2ZGFmNzRlYzAwMGY4Mjc4OGQ3NWVkYTFhNDhmYzYxYzE2MzAwODBmMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n4AwHunQmZu11ULmU3K1L7T4tIDpVpaPPylGa480EK4">
> 
> **GISAID Nucleotide Query:** C774T, C21302T, C21304A, T27810C, -C1762A, -A13278G, -C28528T **Usher Tree:** https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1__C21302T_C21304A_G21305A_C28201T.json?c=gt-nuc_21302&gmax=22302&gmin=20302&label=id:node_6810451 <img alt="image" width="975" src="https://private-user-images.githubusercontent.com/33738461/293403047-4c1852ac-1521-4529-8d63-eaa1f6058513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjQxMjUsIm5iZiI6MTcxMDQyMzgyNSwicGF0aCI6Ii8zMzczODQ2MS8yOTM0MDMwNDctNGMxODUyYWMtMTUyMS00NTI5LThkNjMtZWFhMWY2MDU4NTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEzNDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5Nzg5MmI3ODA0NWVmOGNhMzIyYTc3Y2UwM2JhMDJjNTMxMDk4YzI0MDVmYjllZjRlNjI4ZjJiOWJmZjIwYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5-p5eTERKM7g9s1XcEVOvUfJV7zIyiFwlgjfA42ZgaA">
> 
> **Genomes**
> 
> Genomes
> EPI_ISL_18616083, EPI_ISL_18616126, EPI_ISL_18673123, EPI_ISL_18673128, EPI_ISL_18673134, EPI_ISL_18673138, EPI_ISL_18673142, EPI_ISL_18673146, EPI_ISL_18673148, EPI_ISL_18673151, EPI_ISL_18673153-18673155, EPI_ISL_18673160, EPI_ISL_18673165, EPI_ISL_18673167, EPI_ISL_18673172, EPI_ISL_18673175-18673176, EPI_ISL_18673182, EPI_ISL_18673186, EPI_ISL_18673200, EPI_ISL_18673204, EPI_ISL_18683452, EPI_ISL_18683454, EPI_ISL_18683474, EPI_ISL_18683480, EPI_ISL_18683482, EPI_ISL_18683491, EPI_ISL_18683493, EPI_ISL_18683496-18683497, EPI_ISL_18683520, EPI_ISL_18683524, EPI_ISL_18683526, EPI_ISL_18683538, EPI_ISL_18683542, EPI_ISL_18683546-18683548, EPI_ISL_18683571-18683572, EPI_ISL_18683574-18683575, EPI_ISL_18683577-18683578, EPI_ISL_18683584, EPI_ISL_18683595, EPI_ISL_18700196, EPI_ISL_18700203, EPI_ISL_18700218-18700220, EPI_ISL_18700228, EPI_ISL_18700231, EPI_ISL_18700233, EPI_ISL_18700239-18700240, EPI_ISL_18700242, EPI_ISL_18700251-18700252, EPI_ISL_18700257, EPI_ISL_18700261, EPI_ISL_18700267-18700268, EPI_ISL_18700270, EPI_ISL_18700272, EPI_ISL_18701887,

316 seqs now,suggest proposing it! @ryhisner
