### ISSUE TITLE
JN.1 plus S:T572I and S:E1150D   (63 Seqs - 8 countries)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2428]
This is **Branch 1** of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1097

S:T572I is highly homoplasic in JN.1 as we saw in XBB.1.22.1 descendants and as shown by Dadonaite and Bloom it is a mutation able to restore SCE2 binding loss. 

Defining mutations:
JN.1 > C25566T > S:T572I (C23277T),S:E1150D (G25012T)
Query: A7842G, G25012T, C25566T,C23277T
Samples : 29 
<Details>
<Summary>
Genomes
</Summary>
EPI_ISL_18516431, EPI_ISL_18577370, EPI_ISL_18592154,
EPI_ISL_18618109, EPI_ISL_18618170, EPI_ISL_18640642,
EPI_ISL_18640647, EPI_ISL_18647279, EPI_ISL_18653194,
EPI_ISL_18653253, EPI_ISL_18660977, EPI_ISL_18662082,
EPI_ISL_18662562, EPI_ISL_18663699, EPI_ISL_18673598,
EPI_ISL_18676208, EPI_ISL_18676747, EPI_ISL_18677028,
EPI_ISL_18681722, EPI_ISL_18684593, EPI_ISL_18688474,
EPI_ISL_18690123, EPI_ISL_18690219, EPI_ISL_18690922,
EPI_ISL_18691710, EPI_ISL_18691894, EPI_ISL_18692383,
EPI_ISL_18692386, EPI_ISL_18692393
</details> 
Countries: 6 (Uk, US, France, Ireland, Netherlands and Spain - via GBW)

Tree:
![Schermata 2023-12-27 alle 17 08 37](https://github.com/cov-lineages/pango-designation/assets/87669813/3c28b380-df0e-45fb-b0bc-338dec7df853)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4170_c4be00.json?label=id:node_6806014

**Comment by HynnSpylor** [comment]
35 seqs now. The branch grows quite fast in US

**Comment by FedeGueli** [comment]
+1 Singapore

**Comment by FedeGueli** [comment]
63 seqs 8 countries ping @corneliusroemer

**Comment by FedeGueli** [comment]
Designated JN.1.7
