### ISSUE TITLE
Proposal for a few delta sublineages

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#243]
**Proposed sublineage 1**
**Description**
**Sub-lineage of**: AY.23 (240 sequences)
**Earliest sequence**: 2021/7/22 (Switzerland)
**Most recent sequence**: 2021/9/27 (Sweden)
**Countries circulating**: Germany (85 sequences), Sweden (75 sequences), and a few other European countries.
![image](https://user-images.githubusercontent.com/86835836/136683328-1dc5947a-4c54-4336-bd95-38bbef3d5b4c.png)
Mutations in addition to AY.23:
C15960T,
then A20979G,
then ORF1a:R3880G and S:E702V,
then T26112C
It's a very small clade at the moment, maybe better be put under monitoring for a while before designation, but it's interesting to see how a Southeast Asian lineage has been introduced into Europe (seemingly in a single event) and established there.
The transmission advantage according to CoVspectrum is estimatedly 17%:
![image](https://user-images.githubusercontent.com/86835836/136683669-0a65bbf4-fe25-4da7-aba1-f6f8258754bd.png)
**Genomes**:
[AY.23 E702V.csv](https://github.com/cov-lineages/pango-designation/files/7316903/AY.23.E702V.csv)
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/136683692-9f2f55c4-e476-4eea-b47a-5f81fa7d03c6.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10484_252640.json?c=gt-nuc_26112&l=radial

![image](https://user-images.githubusercontent.com/86835836/136683738-4a441315-f000-41f2-a91f-43c141e844a5.png)

**Proposed sublineage 2**
**Description**
**Sub-lineage of**: B.1.617.2 (738 sequences)
**Earliest sequence**: 2021/3/9 (Turkey)
**Most recent sequence**: 2021/10/1 (the UK)
**Countries circulating**: Germany (188 sequences), Turkey (103 sequences), Sweden (77 sequences), Iran (4 sequences) and multiple other countries.
**Detected at border-entry**: Japan ex-Iran (2 sequences), Hong Kong ex-Iran (1 sequence).
![image](https://user-images.githubusercontent.com/86835836/136684213-99c978ea-f437-4945-917c-a14cdec9e0e3.png)
**Mutations in addition to B.1.617.2**: SE1202Q
 It's fairly likely that this clade was originated in Iran and has a greater prevalence there despite relatively few sequences. The transmission advantage according to CoVspectrum is estimatedly 5%:
![image](https://user-images.githubusercontent.com/86835836/136684732-96ffd1fb-f6f6-473a-bf0e-0fcb77c7a8cc.png)
**Genomes**:
[Delta E1202Q.csv](https://github.com/cov-lineages/pango-designation/files/7316961/Delta.E1202Q.csv)
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/136684463-0da97d9c-0831-458c-8e4a-478d0c996e5c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e4d0_250490.json?c=gt-S_1202&l=radial

![image](https://user-images.githubusercontent.com/86835836/136683738-4a441315-f000-41f2-a91f-43c141e844a5.png)

**Proposed sublineage 3**
**Description**
**Sub-lineage of**: B.1.617.2 (685 sequences)
**Earliest sequence**: 2021/3/16 (Italy...maybe a wrong date input? because the second earliest sequence was in June.)
**Most recent sequence**: 2021/10/3 (Denmark)
**Countries circulating**: Germany (228 sequences), Sweden (158 sequences), Denmark (109 sequences), and a few other European countries
![image](https://user-images.githubusercontent.com/86835836/136686403-e633846d-7c18-4332-a731-f7858c5690d3.png)
**Mutations in addition to B.1.617.2**: 
ORF3a:D238Y
then C4455T and ORF1a:A1397V and ORF1b:A1643V and S:S680T
Noticeably, a subclade of this proposed lineage has an additional Spike subtitution D427G (103 sequences).
**Genomes**:
[Delta S680T.csv](https://github.com/cov-lineages/pango-designation/files/7317042/Delta.S680T.csv)
**Evidence:**
![image](https://user-images.githubusercontent.com/86835836/136686532-7fef030b-88eb-42b7-9eec-3d61ead53704.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3659f_1a7430.json?c=gt-nuc_4455&l=radial

![image](https://user-images.githubusercontent.com/86835836/136683738-4a441315-f000-41f2-a91f-43c141e844a5.png)

**Proposed sublineage 4**
**Description**
**Sub-lineage of**: B.1.617.2 (1090 sequences)
**Earliest sequence**: 2021/6/29 (Finland)
**Most recent sequence**: 2021/9/27 (Sweden)
**Countries circulating**: Sweden (627 sequences), Finland (319 sequences), Estonia (106 sequences), and a few other European countries
![image](https://user-images.githubusercontent.com/86835836/136685358-93c4a9e4-6b45-4985-9400-1ff6f9f50c66.png)
**Mutations in addition to B.1.617.2**: 
ORF7a:P45L
then ORF1b:C142Y,
then G14772A and S:A411S
Genomes:
[Delta A411S.csv](https://github.com/cov-lineages/pango-designation/files/7316995/Delta.A411S.csv)
Evidence:
![image](https://user-images.githubusercontent.com/86835836/136685451-bf3df061-d7a7-47a6-8eec-67e5e1c964ba.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3b8c2_23bd90.json?c=gt-nuc_14772&l=radial

![image](https://user-images.githubusercontent.com/86835836/136683738-4a441315-f000-41f2-a91f-43c141e844a5.png)

**Proposed sublineage 5**
**Description**
**Sub-lineage of**: B.1.617.2 (899 sequences)
**Earliest sequence**: 2021/4/23 (Russia)
**Most recent sequence**: 2021/10/2 (Italy)
**Countries circulating**: Estonia (450 sequences), Finland (157 sequences), Russia (57 sequenecs) and some other European countries
**Detected at border-entry**: Japan ex-Estonia (1 sequence), Korea ex-Russia (2 sequences), 
![image](https://user-images.githubusercontent.com/86835836/136690387-54566154-c5be-47e9-96e7-d8e6e9881ca9.png)
**Mutations in addition to B.1.617.2**: 
ORF7a:P45L
then S:S680P
Most of the sequences from Estonia have further substitutions of ORF1a:K851E and ORF3a:S40P (446 sequences, shown in blue color)
Genomes:
[Delta S680P.csv](https://github.com/cov-lineages/pango-designation/files/7317260/Delta.S680P.csv)
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/136691646-bde5de93-08c5-4313-8b98-56f028126ef2.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_30be8_fa49d0.json?c=gt-nuc_23600,25510&l=radial

![image](https://user-images.githubusercontent.com/86835836/136683738-4a441315-f000-41f2-a91f-43c141e844a5.png)

**Proposed sublineage 6**
**Description**
**Sub-lineage of**: B.1.617.2 (414 sequences)
**Earliest sequence**: 2021/8/1 (Sweden)
**Most recent sequence**: 2021/9/25 (Sweden)
**Countries circulating**: Sweden (294 sequences), Norway (92 sequences), and a few other European countries.
![image](https://user-images.githubusercontent.com/86835836/136697957-42c65240-7d1c-4762-9c44-b8968f0ffc27.png)
**Mutations in addition to B.1.617.2**: 
ORF7a:P45L,
then C27294T,
then G20679T,
then T14343C,
then ORF1a:N2603S,
then ORF1b:D1782A,
then C9943T,
then ORF1a:T2016I,
then N:T135I,
then S:P25S
**genomes**: 
[Delta P25S.csv](https://github.com/cov-lineages/pango-designation/files/7317519/Delta.P25S.csv)
Evidence:
![image](https://user-images.githubusercontent.com/86835836/136698342-540b0088-d9fa-4509-89f4-fc6901f6ac04.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_192b1_25bf50.json?c=gt-S_25&l=radial

![image](https://user-images.githubusercontent.com/86835836/136683738-4a441315-f000-41f2-a91f-43c141e844a5.png)

**Proposed sublineage 7**
**Description**
**Sub-lineage of**: B.1.617.2 (3375 sequences)
**Earliest sequence**: 2021/2/22 (Monaco)
**Most recent sequence**: 2021/10/5 (Italy...maybe a wrong date input again? as it's a bit unlikely to submit a sequence only one day after collection IMHO......Anyway the 2nd latest sequence was on 2021/10/4 from Germany)
**Countries circulating**: Germany (768 sequences), France (761 sequences), Sint Maarten (105 sequences), and multiple other countires.
**Detected at border-entry**: Japan ex-Spain (1 sequence)
![image](https://user-images.githubusercontent.com/86835836/136692062-c9ad2d44-c096-490a-97ca-e8becfb1d97a.png)
**Mutations in addition to B.1.617.2**: 
ORF1a:A498V and ORF7a:R118G,
then S:G181V
There's also a subclade with additional S:N354K (345 sequences, shown in red color, mainly from Belgium).
**Genomes**:
[Delta G181V.csv](https://github.com/cov-lineages/pango-designation/files/7317344/Delta.G181V.csv)
**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/136694373-6b0a1907-9ec3-43d3-bed1-9ee3132fd81d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2cb7c_fac3a0.json?c=gt-nuc_22104,22624&l=radial
![image](https://user-images.githubusercontent.com/86835836/136683738-4a441315-f000-41f2-a91f-43c141e844a5.png)

**Comment by c19850727** [comment]
My apologies everyone, it seems that submitting 7 proposal packed in one issue, especially with some proposal too fine-grained than it might need to be, was a bit messy for everyone including myself. 

@corneliusroemer thanks for letting me know, and @chrisruis let me close this current issue and split those proposals in new one.

**Comment by FedeGueli** [comment]
Hi @c19850727 , i think it is time to.reopen Lineage 7 of this proposal:
Orf7a:R118G + Orf1a:3483F is doing quite well in Denmark:
![VariantTimeDistributionChart (5)](https://user-images.githubusercontent.com/87669813/142948227-dda6d1c4-0178-4969-a5a4-19d8b4ec24bb.png)
CovSpectrum[CovSpectrum](https://cov-spectrum.ethz.ch/explore/Denmark/AllSamples/from=2021-10-30&to=2021-11-22/variants?aaMutations=orf1a%3A3483F%2COrf7a%3AR118G) 

cc @corneliusroemer

**Comment by FedeGueli** [comment]
Lineage 7 with Orf1a:A498V and Orf7a:R118G (belonging to AY.122 ) seems to grow in France too:
![VariantTimeDistributionChart (15)](https://user-images.githubusercontent.com/87669813/143788540-dd9ae85c-56ad-45f3-8a58-b210acf93c9e.png)

@corneliusroemer this lineage is present in several european country as Italy, Germany, France, Switzerland,Denmark , Sweden around 2-6% each during the last two weeks.

@c19850727 please rethink about re-propose it

**Comment by Over-There-Is** [comment]
> Lineage 7 with Orf1a:A498V and Orf7a:R118G (belonging to AY.122 ) seems to grow in France too: ![VariantTimeDistributionChart (15)](https://user-images.githubusercontent.com/87669813/143788540-dd9ae85c-56ad-45f3-8a58-b210acf93c9e.png)
> 
> @corneliusroemer this lineage is present in several european country as Italy, Germany, France, Switzerland,Denmark , Sweden around 2-6% each during the last two weeks.
> 
> @c19850727 please rethink about re-propose it

~12153 now
