### ISSUE TITLE
HV.1.6.1 with S:K444N (221 seqs, 4 countries, mainly in Ontario, Canada)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2430]
**Defining Mutations:** `HV.1.6.1` > `G22894T(S:K444N)`
**Query:** `C6317T, C11020T, G22894T`
**Earliest seq:** 2023-10-13 (`EPI_ISL_18427211`, Ontario, Canada)
**Latest seq:** 2023-12-19 (`EPI_ISL_18696415`, Ontario, Canada)
**Sampled Countries:** Canada (210, ON/209; BC/1), USA (6: MD/2; NY/2; TX; WV), Japan (4), Switzerland (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18427211, EPI_ISL_18427397, EPI_ISL_18427629, EPI_ISL_18448613, EPI_ISL_18448709, EPI_ISL_18448952-18448953, EPI_ISL_18451478, EPI_ISL_18451508, EPI_ISL_18451523, EPI_ISL_18451578, EPI_ISL_18471317, EPI_ISL_18471319, EPI_ISL_18471326, EPI_ISL_18471819, EPI_ISL_18472153, EPI_ISL_18474372, EPI_ISL_18504005, EPI_ISL_18504717, EPI_ISL_18505163, EPI_ISL_18505305, EPI_ISL_18523718, EPI_ISL_18548710, EPI_ISL_18549002-18549003, EPI_ISL_18549304, EPI_ISL_18549337, EPI_ISL_18580674, EPI_ISL_18580690, EPI_ISL_18581579-18581580, EPI_ISL_18581592, EPI_ISL_18581596, EPI_ISL_18581608, EPI_ISL_18581627-18581630, EPI_ISL_18581691, EPI_ISL_18581694, EPI_ISL_18581717, EPI_ISL_18581850, EPI_ISL_18581922, EPI_ISL_18582050, EPI_ISL_18582205-18582206, EPI_ISL_18582420, EPI_ISL_18582607, EPI_ISL_18582725, EPI_ISL_18582976, EPI_ISL_18583023, EPI_ISL_18583032, EPI_ISL_18583061, EPI_ISL_18583094, EPI_ISL_18583098, EPI_ISL_18583166, EPI_ISL_18583208, EPI_ISL_18583224, EPI_ISL_18583241, EPI_ISL_18583272, EPI_ISL_18583274, EPI_ISL_18591181, EPI_ISL_18591301, EPI_ISL_18591324, EPI_ISL_18591376, EPI_ISL_18591549, EPI_ISL_18602359, EPI_ISL_18609168, EPI_ISL_18610364, EPI_ISL_18610556, EPI_ISL_18610674, EPI_ISL_18610692, EPI_ISL_18610712, EPI_ISL_18610714-18610717, EPI_ISL_18610719, EPI_ISL_18610882, EPI_ISL_18610983, EPI_ISL_18611054, EPI_ISL_18611056, EPI_ISL_18611074, EPI_ISL_18611228, EPI_ISL_18614976, EPI_ISL_18614984, EPI_ISL_18615020, EPI_ISL_18615036, EPI_ISL_18615058, EPI_ISL_18615060, EPI_ISL_18615083, EPI_ISL_18615087, EPI_ISL_18615136, EPI_ISL_18615159, EPI_ISL_18636463, EPI_ISL_18643310, EPI_ISL_18643442-18643445, EPI_ISL_18643491, EPI_ISL_18645036, EPI_ISL_18645346, EPI_ISL_18645432, EPI_ISL_18645447, EPI_ISL_18645450, EPI_ISL_18645503, EPI_ISL_18645609, EPI_ISL_18645650, EPI_ISL_18645660, EPI_ISL_18645696, EPI_ISL_18645706, EPI_ISL_18645739, EPI_ISL_18645742, EPI_ISL_18645748, EPI_ISL_18645761, EPI_ISL_18645779, EPI_ISL_18645814, EPI_ISL_18645859, EPI_ISL_18645889, EPI_ISL_18645896, EPI_ISL_18645898-18645899, EPI_ISL_18645934, EPI_ISL_18645997, EPI_ISL_18651765, EPI_ISL_18653742, EPI_ISL_18653895, EPI_ISL_18653900, EPI_ISL_18665151, EPI_ISL_18673245, EPI_ISL_18679048, EPI_ISL_18686369, EPI_ISL_18690072, EPI_ISL_18693046, EPI_ISL_18695734, EPI_ISL_18695772, EPI_ISL_18695785, EPI_ISL_18695788, EPI_ISL_18695791, EPI_ISL_18695806, EPI_ISL_18695837, EPI_ISL_18695854, EPI_ISL_18695880, EPI_ISL_18695887, EPI_ISL_18695927, EPI_ISL_18695931, EPI_ISL_18695968-18695969, EPI_ISL_18695994, EPI_ISL_18696030, EPI_ISL_18696040, EPI_ISL_18696050, EPI_ISL_18696061, EPI_ISL_18696081, EPI_ISL_18696088, EPI_ISL_18696090, EPI_ISL_18696092-18696094, EPI_ISL_18696100, EPI_ISL_18696105, EPI_ISL_18696110, EPI_ISL_18696118, EPI_ISL_18696126, EPI_ISL_18696128, EPI_ISL_18696150, EPI_ISL_18696171-18696172, EPI_ISL_18696176, EPI_ISL_18696183, EPI_ISL_18696189, EPI_ISL_18696233-18696234, EPI_ISL_18696241, EPI_ISL_18696245, EPI_ISL_18696263, EPI_ISL_18696286, EPI_ISL_18696357, EPI_ISL_18696379-18696380, EPI_ISL_18696382-18696384, EPI_ISL_18696391, EPI_ISL_18696415, EPI_ISL_18696513, EPI_ISL_18696525, EPI_ISL_18696594, EPI_ISL_18696719, EPI_ISL_18696748, EPI_ISL_18696774, EPI_ISL_18696784-18696785, EPI_ISL_18696787-18696788, EPI_ISL_18696807, EPI_ISL_18696876, EPI_ISL_18696882, EPI_ISL_18696916, EPI_ISL_18696981, EPI_ISL_18697220, EPI_ISL_18697231, EPI_ISL_18697362, EPI_ISL_18697395, EPI_ISL_18697399, EPI_ISL_18697457-18697458, EPI_ISL_18697487-18697490, EPI_ISL_18697500, EPI_ISL_18697508, EPI_ISL_18697572, EPI_ISL_18697615, EPI_ISL_18697628, EPI_ISL_18697633, EPI_ISL_18697643, EPI_ISL_18697651, EPI_ISL_18697684`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_59555_d799c0.json?label=id:node_3558411
![tree](https://github.com/cov-lineages/pango-designation/assets/125747944/17c0f2ad-7ca8-49a0-90e2-f70bad09ee75)

**Trivia:**
- Looks like typical Canadian cluster due to high sample density, from different labs in Ontario though.
- The interesting part is a sub-branch with ORF8:W45S(G28027C) acquired further ORF8:W45*(G28027A), on top of already truncated ORF8:G8*. What is going on out there?
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ade5a853-5088-4746-ae4a-ce7f93cfcd52)
- ~~Does `K444N` form glycan with `G446S`?~~
- Thanks to @krosa1910 for providing better query, [there seems to be a problem](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1174#issuecomment-1871725310) reading `nuc_5600-5700` from certain labs.

**Comment by krosa1910** [comment]
As far as I know, HV.1* have no problem with having Orf8:Q18* while already inheriting Orf8:G8* like in HV.1.4*, although hard to say it confer a specific growth advantage from HV.1 parent (HV.1* just diminishing and it does not seem to save it from that fate).

**Comment by FedeGueli** [comment]
> * Does `K444N` form glycan with `G446S`

No cause there is a P after N it is N-P-S where N Glycan could be created where the sequence is N- X (= All But P)- S/T  and it is exposed

**Comment by FedeGueli** [comment]
ping @corneliusroemer although boosted by canadian cluster this is still interesting alreedy on paper.

**Comment by aviczhl2** [comment]
Designated KL.1
