### ISSUE TITLE
HK.3.2 sublineage with S:E471Q(48 sequences, 14 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2431]
from sars-cov-2-variants/lineage-proposals#955

HK.3.2> C10039T> C7765T, T21333C, G22973C(S:E471Q), C25782T

Query: T21333, G22973C(2 dropped out)
Query from dropped out sequences: G13627A, T21333, C25782T, -G22973C 

Earliest Sequence: 10-12 Singapore (from Hong Kong SAR, China) EPI_ISL_18428701
Latest Sequence: 01-12 Saitama City, Saitama, Japan EPI_ISL_18815223
Regions Detected: 
*China** 12(Henan 3, Hong Kong 1, Hubei 1, Liaoning 1, Sichuan 1, Xinjiang 5), **Singapore** 10(2 from Malaysia, 1 from HK, 1 from Japan, 6 Local), ***Japan** 4(Fukuoka 1, Hokkaido 1, Saitama 1, Tokyo 1), **Malaysia** 1(Perek);
**France** 2(GES 1, PAC 1), **Italy** 1(Trentino-Alto Adige), **Germany** 1(Schleswig-Holstein), **Greece** 1(Attica);
**US** 3(California[1 from **South Korea**]);
**Australia** 3(NSW); 
**Mauritius** 1(Plaines Wilhems), **South Africa** 1(North West)

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_20684_763510.json?label=id:node_11040561

![2023-12-30](https://github.com/cov-lineages/pango-designation/assets/38100637/e886b872-d4dd-4007-b1b7-db55dbe73d2c)

<details><summary>Sequences:</summary>

EPI_ISL_18428560, EPI_ISL_18428643, EPI_ISL_18428701,
EPI_ISL_18438381, EPI_ISL_18505844, EPI_ISL_18513737,
EPI_ISL_18513858, EPI_ISL_18530961, EPI_ISL_18535426,
EPI_ISL_18551068, EPI_ISL_18605199, EPI_ISL_18609408,
EPI_ISL_18611425, EPI_ISL_18618118, EPI_ISL_18625059,
EPI_ISL_18651128, EPI_ISL_18669216, EPI_ISL_18672194,
EPI_ISL_18672196, EPI_ISL_18677021, EPI_ISL_18700389,
EPI_ISL_18701020-18701021, EPI_ISL_18701030, EPI_ISL_18701034,
EPI_ISL_18705758, EPI_ISL_18725375, EPI_ISL_18731531,
EPI_ISL_18797850, EPI_ISL_18799066, EPI_ISL_18815095,
EPI_ISL_18815223, EPI_ISL_18819507, EPI_ISL_18855102,
EPI_ISL_18858702, EPI_ISL_18858804, EPI_ISL_18858824,
EPI_ISL_18858833, EPI_ISL_18863038
</details>

**Comment by FedeGueli** [comment]
It seems fast, maybe just Singapore effect. maybe not tough

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
This branch is dead, please close this issue

**Comment by DailyCovidCases** [comment]
It seems that this branch has stopped growing. You should close this. @Over-There-Is

**Comment by FedeGueli** [comment]
Dead please close @Over-There-Is
