### ISSUE TITLE
HV.1.8*+S:P681R (Originally HV.1.8* as the largest branch of HV.1*+S:T208M)

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#2432]
Gisaid Search:C23604G,C22185T,C14195T
Earliest Sequence: EPI_ISL_18465456 US, CO 2023-09-14
Latest Sequence: 
EPI_ISL_18663603 Canada 2023-12-10
Geo Spread 85 total , mostly in US, spread to Canada, UK, Greece, Netherlands, Spain, Switzerland
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3ac33_fe82a0.json?f_userOrOld=uploaded%20sample
![image](https://github.com/cov-lineages/pango-designation/assets/131021067/e3f5566f-7029-4a25-9775-3d632a489fd1)
----------------------------------------------------
(Updated)
Branch with S:P681R
Gisaid Search: C22185T,C14195T,C23604G
Earliest Sequence: EPI_ISL_18465456 CO, US, 2023-09-14
Latest Seqeunce: 
EPI_ISL_18892537 Canada, 2024-01-26
pretty wide geographic spread with possible significance in Ecuador.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2884d_4c66d0.json?f_userOrOld=uploaded%20sample&label=id:node_1036260
<img width="985" alt="Screenshot 2024-02-20 at 11 34 45 PM" src="https://github.com/cov-lineages/pango-designation/assets/131021067/40028b70-a91b-4f80-bf7c-e4bbf0029332">

**Comment by krosa1910** [comment]
This is introduced by the issue 957, or HV.1* Spike Diversity Collection issue in the other sector.

**Comment by FedeGueli** [comment]
> This is introduced by the issue 957, or HV.1* Spike Diversity Collection issue in the other sector.

https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox/FMfcgzGtxdbRJPLhhksWrjNmhgGHQKTg

**Comment by FedeGueli** [comment]
92 samoples 7 countries

**Comment by corneliusroemer** [comment]
You somehow got a somewhat misleading subtree from Usher - not all 208M have 681R:

<img width="2328" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/9ebdc540-4d72-43f0-b17f-3f53c17e2c7a">

Above is what I get when I make an Usher tree.

I'll designate the 208M.

**Comment by krosa1910** [comment]
I have changed this issue to make it more meaningful after the S:T208M branch is designated.
Sub-branch 1: S:P681R (convergent to JN.1* of course)
Gisaid Search: C5835T,C1093T,C22185T,C14195T,C23604G
Earliest Sequence: EPI_ISL_18465456 CO, US, 2023-09-14
Latest Sequence: EPI_ISL_18797757 Ecuador 2024-01-10
Geographic Distribution: 7 Canada, 1 Czech, 4 Ecuador, 1 England, 2 Netherlands, 3 Spain, 1 Switzeland, Rest US
Sub-branch 1.1: S:P681R+S:M153I
Gisaid Search: C5835T,C1093T,C22185T,G22021T
Earliest Sequence: EPI_ISL_18497763 CA, US, 2023-10-24
Latest Sequence: EPI_ISL_18779959 CA, US, 2023-12-28
Geographic Distribution: 16 CA, US 4 UT, US
Sub-branch 2: S:R452W+S:E554Q
Gisaid Search:
Earliest Sequence: EPI_ISL_18407513 MN, US, 2023-10-03
Latest Sequence: EPI_ISL_18807668 CO,US, 2023-12-24
Geographic Distribution: 10 MN, 1 CO (latest spread)
Usher for the total Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_ad24_205e30.json?f_userOrOld=uploaded%20sample&label=id:node_1030207
<img width="958" alt="Screenshot 2024-01-25 at 3 07 57 PM" src="https://github.com/cov-lineages/pango-designation/assets/131021067/9478027e-85b9-4b33-9202-ff9e94b6e831">

**Comment by FedeGueli** [comment]
Branch 1 query:  C22185T,C14195T,C23604G
Branch 2 query: C1302T, C6310T,G23222C,

**Comment by krosa1910** [comment]
No submission for a while, I will give it another week?
