### ISSUE TITLE
New EG.5.1.1-Flip lineage with insertion on Orf8(104 seqs, 11 countries, 26 seqs with S:G184S)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2434]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1186

EG.5.1.1->T14988C, A23014T->C1471T->C12823T->G25459T,G22927T(Orf3a:A23S,S:L455F), ins28214T or TT or TTT

GISAID query: C12823,G25459, C1471,C29625T
No. of seqs: 80(Denmark 2 UK 1 Finland 28 France 4 Lithuania 29 Netherlands 3 Poland 2 Sweden 9 USA 1)

First: EPI_ISL_18393737,Lithuania, 2023-9-6
Latest: EPI_ISL_18659915, Sweden, 2023-12-15

GISAID query for S:G184S sub-branch: C12823T,G22112,G25459,16456 (19 seqs)

Most of the seqs has insertion on 28214(Orf8:107), however the insertion pattern seems complex. Some has ins28214T, some has ins28214TT, some has ins28214TTT or more Ts. Every insertion seqs are distributed all over the branch.
I guess they shall have the same insertion but due to some artefact it is sequenced as various forms.

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/eg_5_1_1_ins28214.json?label=id:node_3456344)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/e26b1483-33ab-42bb-800c-fd77ca548af5)

**Comment by FedeGueli** [comment]
97, 0 from January

**Comment by aviczhl2** [comment]
New country of Switzerland

**Comment by aviczhl2** [comment]
No new seqs
