### ISSUE TITLE
EG.5.1.13+Orf1a:R135S(rev) (1485 seqs ，33 countries, further gaining Flip+S:A288S,P1162L, 56 Seqs) 

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2435]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1074

There's a large branch of convergent reversion Orf1a:R135S(rev) presented in KH.1 under EG.5.1.13 too.

EG.5.1.13+G670T(Orf1a:R135S)(rev)

GISAID query: C12439T,C241T,-T670G, C2334T, T22930A
No. of seqs: 1327(Australia, Belgium, Brazil, Canada, Chile, Denmark, UK, France, Germany, Greece, Iceland, Israel, Ireland, Italy,
Japan, Mexico, Netherlands, New Zealand, Peru, Portugal, Romania, South Korea, Spain, Sweden, Switzerland, USA, Poland, China, Luxembourg, Norway, Finland)

First: EPI_ISL_18080900, 2023-6-27, USA
Latest:EPI_ISL_18708636, 2023-12-19, Canada

GISAID query for sub-branch with S:A288S,P1162L,L455F: G22927T,C25047T, G22424T(41 seqs)

Usher seems to be placing G670T before C12439T now, causing trouble on identification of EG.5.1.13.  @AngieHinrichs @corneliusroemer 

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/eg_5_1_13_r135s.json?c=gt-S_288,1162,455&gmax=25384&gmin=21563&label=id:node_3588116)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/4a92a08d-a090-47c6-9baf-7616c58b00e3)

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by aviczhl2** [comment]
1349, Slovakia,Colombia

**Comment by FedeGueli** [comment]
the Flip sublineage seems dead
