### ISSUE TITLE
FL.1.5.1 with S:ins248_KRD (36 seq, maybe dominant in Haiti)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2438]
**Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/996**
### **Description**
**Sub-lineage of:** FL.1.5.1 
**Earliest sequence:** 2023-9-11, Haiti — EPI_ISL_18360180
**Most recent sequence:** 2023-10-6, Haiti — 2 sequences
**Countries circulating:** Haiti (8), USA (3)
**Number of Sequences:** 11
**GISAID AA Query:** Spike_ins248KRD
**GISAID Nucleotide Query:** ins22306AAACGGGAT (incorrect, but this is what you have to search for)
**CovSpectrum Query:** Nextcladepangolineage:FL.1.5.1* & [2-of: T23042C, A6391T, A27477T, A29320C] or `ins_22304:ACAAACGGG`
**Substitutions on top of XBB.:**
**Spike:** ins248_KRD
**Nucleotide:** ins22304ACAAACGGG (Nextclade)

**Phylogenetic Order of Mutations:** Unclear, but my best guess is:
ins22306AAACGGGAT (S:ins248KRD)       **→**       A6391T (ORF1a:E2042D)    **→**     T23042C (S:S494P)       

**USHER Tree** (Usher incorrectly places the three US sequences in a different branch than the Haitian sequences)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2350a_300c80.json?c=gt-ORF1ab_2042&f_userOrOld=uploaded%20sample&label=id:node_3396610 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/FL.1.5.1_S494P_ins248KRD_14_seq.json   

<img width="1474" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2ae5d77d-9582-4b3b-ba06-e1a3345fd76e">

**Evidence**
All six uploads from Haiti collected in October are duplicated in GISAID, and I’ve adjusted the numbers to reflect this. I’ve included all EPI_ISL’s below. I’m including one sequence that has no coverage at S:248 because it shares both A6791T and A27477T with the other sequences. 

5/6 sequences collected in Haiti in October are a part of this lineage, and 8/14 collected since September 8. Three have been seen in the US, but it hasn’t spread. Perhaps it’s not fit enough to compete with the globally dominant lineages. 

6/11 sequences have S:S494P, and none of the three US sequences have S:S494P, suggesting that the insertion occurred before S:S494P was acquired. Only 8/11 of these sequences have ORF1a:E2042D, so the insertion likely occurred before this mutation was acquired as well. I therefore didn’t include either of those mutations in the proposal despite them both being present in a majority of sequences. The same is true for the synonymous A27477T, which is in 8/11 sequences.

Only 2/8 Haitian sequences have coverage in the S:435-460 region, so it’s possible that several other sequences have S:K444M or other mutations there.  

Interesting spike mutations in this branch:
• S:Q14L (1 seq)
• S:K182E (1)
• S:K182R (1)
• S:K444M (1)
• S:V483F (1)

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18340268, EPI_ISL_18357036, EPI_ISL_18360180-18360181,
EPI_ISL_18369514, EPI_ISL_18415080-18415082, EPI_ISL_18415084,
EPI_ISL_18415757-18415760, EPI_ISL_18415762
</details>

**Comment by corneliusroemer** [comment]
We have to wait for more sequences from non-Haiti, right now the tree is a bit too messy
