### ISSUE TITLE
HK.3.1 + ORF1a:G49C, N:V270L 301 seq.

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2440]
transferred from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/791
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/3397d9c6-ceda-402a-93cb-71d72e9ef610)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1b903_729560.json?c=gt-ORF1ab_49&label=id:node_3506085

gisaid Query: G410T, T11269C

**Comment by aviczhl2** [comment]
This one is donor of XDJ

**Comment by FedeGueli** [comment]
> G410T, T11269C

Thx!
