### ISSUE TITLE
JN.3+N:H300Y(57 seq, 12 countries) and further S:F456V(23 seq, 8 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2445]
Transferred from sars-cov-2-variants/lineage-proposals#1160

JN.3> C2939T(Orf1a:P892S)> C29171T(N:H300Y)> A17637G, T22928G(S:F456V), C29095T, C29253T(N:S327L)

S:F456V branch is spotted by @Huachuan1120 on 12-04.
A recombinant of S:F456V branch with EG.5.1.3 has been spotted and proposed by @aviczhl2 in sars-cov-2-variants/lineage-proposals#1267.

Query: C2939T, A6183, C29171(4 dropout, 7 not on GISAID)
Query for S:F456V branch: A17637G, T22928G (including the recombinant, 2 dropout)
Alternative query for S:F456V branch: C6525T, C29095T, C29253T (not including the recombinant)

Earliest Sequence: 09-18 Auvergne-Rhône-Alpes, France EPI_ISL_18327129
Latest Sequence: 12-30 England, UK EPI_ISL_18764443
Regions Detected: 
**France** 3 _+10_(_ARA 6, HDF 3,_ Bretagne 1, IDF 1, _Normandie 1,_ PDL 1), **UK** 2 _+9_(_Scotland 9,_ England 2), **Germany** 10(Bayern 6, Berlin 3, BW 1), **Switzerland** 3(Berne 2, Zürich 1), _**Ireland** 3(Dublin 2, Kildare 1),_ **Denmark** 2, **Italy** 1(Friuli-Venezia Giulia), _**Netherlands** 1(Limburg);_
**US** 1 _+7_(_Michigan 7,_ NJ 1), _**Canada** 3(Ontario);_
_**China** 1(HK),_ **Singapore** 1

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_6c9b_389ab0.json?c=country&label=id:node_4507656
![2024-01-10 (1)](https://github.com/cov-lineages/pango-designation/assets/38100637/83ae8e67-9955-4033-9632-41789fc1ecef)

<details><summary>Sequences:</summary>

EPI_ISL_18327129, EPI_ISL_18345205, EPI_ISL_18393016,
EPI_ISL_18398880, EPI_ISL_18421665, EPI_ISL_18421669,
EPI_ISL_18444789, EPI_ISL_18444795, EPI_ISL_18444860,
EPI_ISL_18444880, EPI_ISL_18493326, EPI_ISL_18510026,
EPI_ISL_18541096, EPI_ISL_18547047, EPI_ISL_18577281,
EPI_ISL_18577373, EPI_ISL_18592282, EPI_ISL_18596299,
EPI_ISL_18598210, EPI_ISL_18599846, EPI_ISL_18599863,
EPI_ISL_18606074, EPI_ISL_18605945, EPI_ISL_18619751,
EPI_ISL_18631463, EPI_ISL_18632934, EPI_ISL_18633152,
EPI_ISL_18645464, EPI_ISL_18652958, EPI_ISL_18661656,
EPI_ISL_18674685, EPI_ISL_18676345, EPI_ISL_18676927,
EPI_ISL_18680575, EPI_ISL_18688159, EPI_ISL_18688784,
EPI_ISL_18695237, EPI_ISL_18700645, EPI_ISL_18708522,
EPI_ISL_18713427, EPI_ISL_18716994, EPI_ISL_18717245,
EPI_ISL_18724621, EPI_ISL_18726821, EPI_ISL_18742238,
EPI_ISL_18749823, EPI_ISL_18755890, EPI_ISL_18755899,
EPI_ISL_18764443, EPI_ISL_18768801

American sequences not uploaded to GISAID:
OR981977.1, PP002773.1, PP002783.1,
PP002856.1, PP099237.1, PP099810.1,
PP099826.1

Potential recombinant with EG.5.1.3:
EPI_ISL_18705445, EPI_ISL_18724545, CLIMB-CM7YFQ6T
</details>

**Comment by FedeGueli** [comment]
ping @corneliusroemer

**Comment by Over-There-Is** [comment]
Italy
