### ISSUE TITLE
JN.1+S:V1104L emerging in India(21 seqs, 2 countries, 6 with Orf1a:T2283I and S:F456L, 2.5% India)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2446]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253 branch 4 and https://github.com/sars-cov-2-variants/lineage-proposals/issues/1262

JN.1+G17334T,G24872T(S:V1104L)

GISAID query: G24872T, G17334T,C28958A
No. of seqs: 21(India 20 UK 1)

First: EPI_ISL_18694669, India-GJ, 2023-12-7
Latest: EPI_ISL_18725672, India-MH, 2024-1-1

20/790=2.5% in India seqs from 2023-12. From GJ, KA and MH.

+C7113T,T22928C(Orf1a:T2283I,S:F456L)
GISAID query: C7113T,T22928C,T3565C 
No. of seqs: 6(India 5 UK 1)

Note that due to artefacts usher places those seqs on different branches. Some with S:V483G artefact are placed together, 
some with artefacts around S:16 are placed together, and seqs with other artefacts are placed in other places. 

@AngieHinrichs 

[current usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_cf3c_e8a550.json?f_userOrOld=uploaded%20sample&label=id:node_6808589)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/33197f75-ae4f-45ab-9815-0fff8e404604)

**Comment by FedeGueli** [comment]
i have added a spike independent query: C4069T, C4999T,C19951A

**Comment by corneliusroemer** [comment]
Also found this one - it's a bit tricky to designate due to the artefacts, there's now an Israeli sequence as well though with 456L `hCoV-19/England/CLIMB-CM7YMUES/2023|EPI_ISL_18735395|2023-12-29`

And two Texas seqs without 456L:
```
hCoV-19/USA/TX-HMH-M-136910/2023|EPI_ISL_18743029|2023-12-27
hCoV-19/USA/TX-HMH-M-136429/2023|EPI_ISL_18743507|2023-12-15
```

**Comment by corneliusroemer** [comment]
I've designated via the non-Indian sequences with 1104L for now as JN.1.11, the 456L would be a sublineage in the future

**Comment by AngieHinrichs** [comment]
Yep, it's currently placed on a messy reversion branch within JN.1.1 instead of JN.1.  When the 2024-01-11 build finishes I will do some pruning & re-optimization on the tree, and then hopefully in tomorrow's 2024-01-12 build JN.1.11 will be in the right place.

**Comment by aviczhl2** [comment]
The S:F456L branch is 10 now.

**Comment by FedeGueli** [comment]
456L 15 now

**Comment by aviczhl2** [comment]
Countries for F456L branch:
India, UK, USA, Israel, Singapore

**Comment by FedeGueli** [comment]
> I've designated via the non-Indian sequences with 1104L for now as JN.1.11, the 456L would be a sublineage in the future

@corneliusroemer could you reopen this one to track properly the 456L branch please?

**Comment by Over-There-Is** [comment]
JN.11> A12889G> T3055C> T22926C or JN.11.1> T3055C?
