### ISSUE TITLE
Possible new JN.1.X circuling with DELETION 28254 (ORF8:I121-) 

### ISSUE THREAD

**Issue by OrsonMM** [cov-lineages/pango-designation#2447]
**Description**

New possible omicron sub-lineage with DEL 28254 (ORF8:I121-) mutation proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

JN.1 (EPI_ISL_18705178) firts detected was England, with date missing

**Earliest sequence:** 2023-10-06
hCoV-19/USA/NJ-GBW-H10-016-3356/2023 (EPI_ISL_18400009)

**Most recent sequence:** 2024-01-02
hCoV-19/Singapore/R1MQ167/2024 (EPI_ISL_18726129)

**Countries circulating:**

      2  Australia
      2  Belgium
     14  Canada
      1  Chile
      1  Colombia
      1  Croatia
     26  Denmark
      1  Ecuador
     11  France
      2  Germany
      1  India
      6  Ireland
      2  Italy
      9  Netherlands
      2  Poland
      3  Puerto Rico
      3  Singapore
      2  Slovenia
     15  Spain
      4  Sweden
     33  United Kingdom
    104  USA

**Evidence:**

https://cov-spectrum.org/explore/United%20States/AllSamples/Past6M/variants?aaMutations=ORF8%3AI121-&nextcladePangoLineage=JN.1&

![image](https://github.com/cov-lineages/pango-designation/assets/12600107/84286e6f-e7e2-4d57-82b3-c309adbd3088)

![image](https://github.com/cov-lineages/pango-designation/assets/12600107/cbea589e-79cc-4675-ac26-bccd367987eb)

** Genomes**

EPI_ISL_18705178,EPI_ISL_18716841,EPI_ISL_18729426,EPI_ISL_18400009,EPI_ISL_18400052,EPI_ISL_18446335,EPI_ISL_18550096,EPI_ISL_18497284,EPI_ISL_18550398,EPI_ISL_18547370,EPI_ISL_18528115,EPI_ISL_18525393,EPI_ISL_18566313,EPI_ISL_18525508,EPI_ISL_18548139,EPI_ISL_18614873,EPI_ISL_18620508,EPI_ISL_18556920,EPI_ISL_18583823,EPI_ISL_18583835,EPI_ISL_18526627,EPI_ISL_18544269,EPI_ISL_18592645,EPI_ISL_18609463,EPI_ISL_18679213,EPI_ISL_18544272,EPI_ISL_18632982,EPI_ISL_18640270,EPI_ISL_18670161,EPI_ISL_18566609,EPI_ISL_18719256,EPI_ISL_18577925,EPI_ISL_18612637,EPI_ISL_18544809,EPI_ISL_18591063,EPI_ISL_18614509,EPI_ISL_18614510,EPI_ISL_18690227,EPI_ISL_18560219,EPI_ISL_18663271,EPI_ISL_18592129,EPI_ISL_18569521,EPI_ISL_18640352,EPI_ISL_18585377,EPI_ISL_18647413,EPI_ISL_18674929,EPI_ISL_18585302,EPI_ISL_18596453,EPI_ISL_18596658,EPI_ISL_18676554,EPI_ISL_18677040,EPI_ISL_18680236,EPI_ISL_18610587,EPI_ISL_18611168,EPI_ISL_18613188,EPI_ISL_18643514,EPI_ISL_18693953,EPI_ISL_18712930,EPI_ISL_18724592,EPI_ISL_18614429,EPI_ISL_18620272,EPI_ISL_18621004,EPI_ISL_18621007,EPI_ISL_18621384,EPI_ISL_18643542,EPI_ISL_18690612,EPI_ISL_18726508,EPI_ISL_18614430,EPI_ISL_18614431,EPI_ISL_18621070,EPI_ISL_18643667,EPI_ISL_18644355,EPI_ISL_18675852,EPI_ISL_18690501,EPI_ISL_18706836,EPI_ISL_18644568,EPI_ISL_18690450,EPI_ISL_18644593,EPI_ISL_18675902,EPI_ISL_18690869,EPI_ISL_18620260,EPI_ISL_18644477,EPI_ISL_18617684,EPI_ISL_18620244,EPI_ISL_18644771,EPI_ISL_18661791,EPI_ISL_18666463,EPI_ISL_18666464,EPI_ISL_18676758,EPI_ISL_18680286,EPI_ISL_18680305,EPI_ISL_18681040,EPI_ISL_18709676,EPI_ISL_18716775,EPI_ISL_18734725,EPI_ISL_18612993,EPI_ISL_18647439,EPI_ISL_18657971,EPI_ISL_18688788,EPI_ISL_18691143,EPI_ISL_18709661,EPI_ISL_18740457,EPI_ISL_18624700,EPI_ISL_18642888,EPI_ISL_18643377,EPI_ISL_18691202,EPI_ISL_18712850,EPI_ISL_18652323,EPI_ISL_18691387,EPI_ISL_18691429,EPI_ISL_18696850,EPI_ISL_18648199,EPI_ISL_18688809,EPI_ISL_18696823,EPI_ISL_18674930,EPI_ISL_18684791,EPI_ISL_18691844,EPI_ISL_18738204,EPI_ISL_18690134,EPI_ISL_18691917,EPI_ISL_18691920,EPI_ISL_18691942,EPI_ISL_18713975,EPI_ISL_18631332,EPI_ISL_18660655,EPI_ISL_18660838,EPI_ISL_18676150,EPI_ISL_18680361,EPI_ISL_18680777,EPI_ISL_18681065,EPI_ISL_18696973,EPI_ISL_18699427,EPI_ISL_18699467,EPI_ISL_18704610,EPI_ISL_18709462,EPI_ISL_18717283,EPI_ISL_18717379,EPI_ISL_18717575,EPI_ISL_18726034,EPI_ISL_18734687,EPI_ISL_18734719,EPI_ISL_18739374,EPI_ISL_18652026,EPI_ISL_18660662,EPI_ISL_18666462,EPI_ISL_18669813,EPI_ISL_18670482,EPI_ISL_18675335,EPI_ISL_18688611,EPI_ISL_18684717,EPI_ISL_18688960,EPI_ISL_18695610,EPI_ISL_18715725,EPI_ISL_18728330,EPI_ISL_18728405,EPI_ISL_18728417,EPI_ISL_18728451,EPI_ISL_18731101,EPI_ISL_18670403,EPI_ISL_18670451,EPI_ISL_18685172,EPI_ISL_18685188,EPI_ISL_18695573,EPI_ISL_18714899,EPI_ISL_18722454,EPI_ISL_18728625,EPI_ISL_18740214,EPI_ISL_18695372,EPI_ISL_18696289,EPI_ISL_18709741,EPI_ISL_18728777,EPI_ISL_18735827,EPI_ISL_18690056,EPI_ISL_18701706,EPI_ISL_18715811,EPI_ISL_18715825,EPI_ISL_18728889,EPI_ISL_18728928,EPI_ISL_18696290,EPI_ISL_18701923,EPI_ISL_18709932,EPI_ISL_18709971,EPI_ISL_18688032,EPI_ISL_18688125,EPI_ISL_18688133,EPI_ISL_18688509,EPI_ISL_18694486,EPI_ISL_18696570,EPI_ISL_18704801,EPI_ISL_18704881,EPI_ISL_18704978,EPI_ISL_18715967,EPI_ISL_18721501,EPI_ISL_18724265,EPI_ISL_18724355,EPI_ISL_18729138,EPI_ISL_18729170,EPI_ISL_18731463,EPI_ISL_18734634,EPI_ISL_18734747,EPI_ISL_18734930,EPI_ISL_18694293,EPI_ISL_18694492,EPI_ISL_18700695,EPI_ISL_18716004,EPI_ISL_18729253,EPI_ISL_18729285,EPI_ISL_18731148,EPI_ISL_18733942,EPI_ISL_18709839,EPI_ISL_18709905,EPI_ISL_18716059,EPI_ISL_18716103,EPI_ISL_18716113,EPI_ISL_18716114,EPI_ISL_18716712,EPI_ISL_18727138,EPI_ISL_18709938,EPI_ISL_18716132,EPI_ISL_18723240,EPI_ISL_18731561,EPI_ISL_18712934,EPI_ISL_18716147,EPI_ISL_18727095,EPI_ISL_18732683,EPI_ISL_18724353,EPI_ISL_18740868,EPI_ISL_18730756,EPI_ISL_18735683,EPI_ISL_18727457,EPI_ISL_18732309,EPI_ISL_18738076,EPI_ISL_18715195,EPI_ISL_18727415,EPI_ISL_18732223,EPI_ISL_18718483,EPI_ISL_18718548,EPI_ISL_18727422,EPI_ISL_18732799,EPI_ISL_18740887,EPI_ISL_18741488,EPI_ISL_18718556,EPI_ISL_18718484,EPI_ISL_18726129,EPI_ISL_18737746

**Comment by DailyCovidCases** [comment]
Please close this issue
