### ISSUE TITLE
XDN: JN.1.1/JD.1* or XCP recombinant(37 seqs, 2 countries)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2448]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1158

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/1b0b0882-294a-4ccf-b092-a11dcfd4506b)

JN.1.1--JD.1* or XCP (thanks @JosetteSchoenma pointing out possibility of XCP)
Breakpoint likely between 24379 and 24989
Very few JD.1* or XCP seqs have 24378T, so may between 23605 and 24377 with little chance. 

Additional mutations: C280T

C280T from a JN.1.1 branch

GISAID query: T28282,A6183,T22926,-27810,-28958(edited)
No. of seqs : 20(UK 16 USA 4)
First: EPI_ISL_18552726, UK, 2023-11-21 (credit to @JosetteSchoenma )
Latest: EPI_ISL_18743268, USA, 2023-12-29

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_1_jd_1_xcp_recomb.json?label=id:node_6819606)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/83c82be2-f593-4e45-bdb7-e952d998b536)

**Comment by FedeGueli** [comment]
Some trouble in the transfer

**Comment by JosetteSchoenma** [comment]
Like I mentioned in the other issue, the one without a date is the first one. I discovered it on the 1st of December, when all the other ones weren't submitted to GISAID yet. 🙃

The date for EPI_ISL_18552726 is 2023-11-21 (only 2023 on GISAID).

Plus, alternative query from @FedeGueli
C11747T, C11812A, C14425T.

It misses one bad sequence from England which might be different. No S:F486P for example.

Other issue: https://github.com/sars-cov-2-variants/lineage-proposals/issues/1158

**Comment by aviczhl2** [comment]
> It misses one bad sequence from England which might be different. No S:F486P for example.

That seq certainly belongs to this branch, at least on usher. Just with some missing coverage.

**Comment by JosetteSchoenma** [comment]
> 
> > It misses one bad sequence from England which might be different. No S:F486P for example.
> 
> That seq certainly belongs to this branch, at least on usher. Just with some missing coverage. 

It could very well belong here, but I wouldn't really in Usher for that.

**Comment by aviczhl2** [comment]
There exists new seqs without C11812A for this recomb. Change query.

**Comment by aviczhl2** [comment]
It seems that one seq of this recomb, EPI_ISL_18707947 is removed due to submitter's request. So despite 3 new seqs were added yesterday, currently it is 22 on GISAID.

**Comment by FedeGueli** [comment]
this is growing faster than JN.1 : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1*&nucMutations1=T28282%2CC14425%2CA6183&analysisMode=CompareToBaseline& still very small to conclude anything but interesting to keep in mind.

**Comment by aviczhl2** [comment]
> It misses one bad sequence from England which might be different. No S:F486P for example.


Seems that the seq is now retracted by submitter.

**Comment by aviczhl2** [comment]
+14 UK today, total=36 now. @corneliusroemer

**Comment by aviczhl2** [comment]
Seqs without 14425T appears, change query.

**Comment by FedeGueli** [comment]
Thank you

**Comment by aviczhl2** [comment]
2 more from UK today.
