### ISSUE TITLE
HK.3.2 sublineage with S:L216F, S:E554K(45 sequences, 10 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2453]
Transferred from sars-cov-2-variants/lineage-proposals#955

HK.3.2> C100T> C22208T(S:L216F), G23222A(S:E554K), A26441G(E:N66S)
Query: C22208T, A26441G

S:L216F and S:E554K are convergent with BA.2.86.

Earliest Sequence: 09-17 Ningde, Fujian, China EPI_ISL_18401711
Latest Sequence: 01-01 Burgenland, Austria EPI_ISL_18744746
Regions Detected: 
**China** 16(Heilongjiang 11, Shanghai 3, Fujian 1, Hubei 1), **Japan** 3(Kanagawa 1, Tokyo 1, Nagano 1), **Malaysia** 3(Sarawak 2, Johor 1), **Singapore** 1(from **Saudi Arabia**), **South Korea** 1;
**Slovakia** 7(Banská Bystrica 6, Prešov 1), **Austria** 3(Wien 2, Burgenland 1), **Germany** 3(Bayern), **Sweden** 3(Södermanland 2, Örebro 1);
**Canada** 1(Ontario), **US** 1 (California)

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_20684_763510.json?abel=id:node_3507506
![2024-01-14](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/5de4e1a9-799a-401d-bad0-cbe5deac2c2d)

<details><summary>Sequences:</summary>

EPI_ISL_18401711, EPI_ISL_18443959, EPI_ISL_18500119
EPI_ISL_18508529, EPI_ISL_18520766, EPI_ISL_18526195,
EPI_ISL_18575611, EPI_ISL_18598256-18598257, EPI_ISL_18615804,
EPI_ISL_18615836, EPI_ISL_18615842, EPI_ISL_18615861,
EPI_ISL_18632894, EPI_ISL_18638379, EPI_ISL_18639709,
EPI_ISL_18701033, EPI_ISL_18716393, EPI_ISL_18722165,
EPI_ISL_18723913, EPI_ISL_18723927, EPI_ISL_18723933,
EPI_ISL_18724542, EPI_ISL_18744746, EPI_ISL_18744907,
EPI_ISL_18769906-18769908, EPI_ISL_18777196, EPI_ISL_18777200,
EPI_ISL_18777261, EPI_ISL_18780132, EPI_ISL_18781596,
EPI_ISL_18811814, EPI_ISL_18821334, EPI_ISL_18836788,
EPI_ISL_18857558, EPI_ISL_18857566, EPI_ISL_18857579-18857581,
EPI_ISL_18857586
</details>

**Comment by FedeGueli** [comment]
28

**Comment by FedeGueli** [comment]
36

**Comment by aviczhl2** [comment]
42 seqs now

**Comment by DailyCovidCases** [comment]
Please close this issue

**Comment by DailyCovidCases** [comment]
This branch is dead, please close this issue

**Comment by DailyCovidCases** [comment]
It seems that this branch has stopped growing. You should close this.

**Comment by DailyCovidCases** [comment]
@Over-There-Is Please close this issue

**Comment by Over-There-Is** [comment]
> 42 seqs now

some are convergent JN.1.
