### ISSUE TITLE
FU.2 with ORF1b:F2309L (nsp15_F258L, ORF8:A65V, ORF1a:L349F (nsp2_L169F) and S:E554K (215 seqs, mainly in Mexico and USA, 12 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2454]
_Transferred from sars-cov-2-variants/lineage-proposals#835_

**Defining Mutations:** **FU.2** > `C26750T` > `T20392C(ORF1b:F2309L)` > `T826C` > _`C28087T(ORF8:A65V)`_ > `G1312T(ORF1a:L349F), G23222A(S:E554K)`
**Query:** `T826C, G1312T, G23222A`
**Earliest seq:** 2023-07-03 (`EPI_ISL_18131853`, Nuevo León, Mexico)
**Latest seq:** 2023-12-22 (`EPI_ISL_18743141`, Texas, USA)
**Sampled Countries:** **USA** (171: TX/52; CA/43; NY/20; CO/14; MN/5; NM/5; MI/4; AZ/3; IA/3; IL/3; LA/3; OH/3; OK/3; PA/3; MA/2; WA/2; HI/1; NC/1; NE/1), **Mexico** (21: NLE/10; CMX/6; COA/1; JAL/1; MEX/1; MIC/1; TAB/1), **Canada** (8: BC/3; AB/2; ON/2; QC), **Italy** (4), **Denmark** (3), **Spain** (2), **Austria** (1), **China** (1: ex. Japan), **Colombia** (1), **Germany** (1), **New Zealand** (1), **Switzerland** (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18114132, EPI_ISL_18119763, EPI_ISL_18121227, EPI_ISL_18121615, EPI_ISL_18131847, EPI_ISL_18131853-18131854, EPI_ISL_18131863, EPI_ISL_18131996, EPI_ISL_18134775, EPI_ISL_18137414, EPI_ISL_18163795, EPI_ISL_18163810, EPI_ISL_18163833, EPI_ISL_18163835, EPI_ISL_18177793, EPI_ISL_18210474, EPI_ISL_18213011, EPI_ISL_18222464, EPI_ISL_18223143, EPI_ISL_18223611, EPI_ISL_18223831, EPI_ISL_18223868, EPI_ISL_18223878, EPI_ISL_18224028, EPI_ISL_18224068, EPI_ISL_18225082, EPI_ISL_18225457, EPI_ISL_18229870, EPI_ISL_18237333, EPI_ISL_18240145, EPI_ISL_18247125, EPI_ISL_18252404, EPI_ISL_18253965, EPI_ISL_18253999-18254000, EPI_ISL_18254023, EPI_ISL_18254034, EPI_ISL_18264174, EPI_ISL_18264811, EPI_ISL_18265938, EPI_ISL_18267587, EPI_ISL_18267656, EPI_ISL_18268315, EPI_ISL_18276309, EPI_ISL_18276403, EPI_ISL_18279589, EPI_ISL_18279600, EPI_ISL_18279692-18279693, EPI_ISL_18279735, EPI_ISL_18282231, EPI_ISL_18291721, EPI_ISL_18295281, EPI_ISL_18299252, EPI_ISL_18303124, EPI_ISL_18307727, EPI_ISL_18308907, EPI_ISL_18309501, EPI_ISL_18317556, EPI_ISL_18323467, EPI_ISL_18328031, EPI_ISL_18328062, EPI_ISL_18328835, EPI_ISL_18328976, EPI_ISL_18329040, EPI_ISL_18329084, EPI_ISL_18329159, EPI_ISL_18329432, EPI_ISL_18333201, EPI_ISL_18333236, EPI_ISL_18334023, EPI_ISL_18334432, EPI_ISL_18339145, EPI_ISL_18339614, EPI_ISL_18341765, EPI_ISL_18342173, EPI_ISL_18347396, EPI_ISL_18349854-18349855, EPI_ISL_18349872, EPI_ISL_18349907-18349908, EPI_ISL_18359781, EPI_ISL_18359786, EPI_ISL_18369029, EPI_ISL_18369518, EPI_ISL_18369586, EPI_ISL_18370272, EPI_ISL_18375288, EPI_ISL_18375719, EPI_ISL_18384197, EPI_ISL_18386475, EPI_ISL_18387978, EPI_ISL_18387993, EPI_ISL_18388058, EPI_ISL_18388088, EPI_ISL_18389320, EPI_ISL_18389370, EPI_ISL_18389475, EPI_ISL_18389617, EPI_ISL_18389816, EPI_ISL_18398018, EPI_ISL_18404488, EPI_ISL_18404724, EPI_ISL_18407598, EPI_ISL_18407718, EPI_ISL_18407978, EPI_ISL_18409532, EPI_ISL_18409544, EPI_ISL_18409807, EPI_ISL_18409860, EPI_ISL_18413715, EPI_ISL_18413911, EPI_ISL_18413917, EPI_ISL_18413924, EPI_ISL_18424351, EPI_ISL_18424375, EPI_ISL_18434061, EPI_ISL_18434149, EPI_ISL_18434153, EPI_ISL_18436659, EPI_ISL_18437857, EPI_ISL_18442461, EPI_ISL_18442676, EPI_ISL_18443458, EPI_ISL_18444127, EPI_ISL_18444136, EPI_ISL_18444156, EPI_ISL_18446340, EPI_ISL_18446453, EPI_ISL_18447844, EPI_ISL_18452444, EPI_ISL_18452994, EPI_ISL_18456365-18456366, EPI_ISL_18460387, EPI_ISL_18463750-18463751, EPI_ISL_18463753, EPI_ISL_18474885, EPI_ISL_18475561, EPI_ISL_18488604-18488605, EPI_ISL_18488612, EPI_ISL_18488647, EPI_ISL_18494664, EPI_ISL_18497785, EPI_ISL_18498415, EPI_ISL_18498418, EPI_ISL_18498454, EPI_ISL_18498693, EPI_ISL_18498718, EPI_ISL_18498860, EPI_ISL_18499104, EPI_ISL_18499230, EPI_ISL_18502123, EPI_ISL_18510283, EPI_ISL_18510309, EPI_ISL_18513123, EPI_ISL_18518232, EPI_ISL_18527899, EPI_ISL_18530100, EPI_ISL_18530117, EPI_ISL_18533184, EPI_ISL_18534180, EPI_ISL_18534420, EPI_ISL_18547571, EPI_ISL_18547661, EPI_ISL_18550962, EPI_ISL_18554431, EPI_ISL_18562857-18562858, EPI_ISL_18576587, EPI_ISL_18576620, EPI_ISL_18581169, EPI_ISL_18581172, EPI_ISL_18581205, EPI_ISL_18589461, EPI_ISL_18589480, EPI_ISL_18589523, EPI_ISL_18589637, EPI_ISL_18589675, EPI_ISL_18592543, EPI_ISL_18594765, EPI_ISL_18595111, EPI_ISL_18608480, EPI_ISL_18608689, EPI_ISL_18621073, EPI_ISL_18622975, EPI_ISL_18632687, EPI_ISL_18633635, EPI_ISL_18637993, EPI_ISL_18638048, EPI_ISL_18644681, EPI_ISL_18648578, EPI_ISL_18649748, EPI_ISL_18661582, EPI_ISL_18662670, EPI_ISL_18667056, EPI_ISL_18667081, EPI_ISL_18669934, EPI_ISL_18671234, EPI_ISL_18679153, EPI_ISL_18691913, EPI_ISL_18707339, EPI_ISL_18714275-18714276, EPI_ISL_18722382-18722384, EPI_ISL_18728194, EPI_ISL_18728462, EPI_ISL_18728464, EPI_ISL_18743141`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43383_374af0.json?label=id:node_3290966

view from FU.2 polytomy
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/9f55772e-20cf-4615-bdb7-67890b6f5269)

details
![details](https://github.com/cov-lineages/pango-designation/assets/125747944/7497f9e7-02fe-4b70-b45d-1ddd70a50bea)

**Comment by DailyCovidCases** [comment]
Please close this issue
