### ISSUE TITLE
HK.30 with S:T478R (157 seqs, mainly in Russia, 6 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2458]
_Taken from **Branch 5** of Multitask sars-cov-2-variants/lineage-proposals#787_

**Defining Mutations:** `HK.30` > `C9319T, C22995G(S:T478R)` (ignores `C27507T` flip-flop)
**Query:** `C9319T, C22995G, T26609C, -A2977G`
**Earliest seq:** 2023-09-11 (`EPI_ISL_18417620`, Tyumen, Russia)
**Latest seq:** 2023-12-18 (`EPI_ISL_18721444`, Denmark)
**Sampled Countries:** **Russia** (148: SPE/99; ME/19; TYU/6; MOS/4; TA/4; MOW/3; LEN/2; MAG/2; MO/2; NIZ/2; VLG/2; AMU; KLU; SAM), **USA** (3: ID; IN; TX), **Denmark** (2), **New Zealand** (2), **China** (1: ex. Russia), **Ukraine** (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18416868, EPI_ISL_18416917, EPI_ISL_18417066, EPI_ISL_18417075, EPI_ISL_18417084, EPI_ISL_18417086, EPI_ISL_18417313, EPI_ISL_18417371, EPI_ISL_18417374, EPI_ISL_18417574, EPI_ISL_18417620, EPI_ISL_18417639, EPI_ISL_18487069, EPI_ISL_18487203, EPI_ISL_18487207, EPI_ISL_18487290, EPI_ISL_18487328, EPI_ISL_18487348, EPI_ISL_18487448, EPI_ISL_18487451, EPI_ISL_18487654, EPI_ISL_18487657, EPI_ISL_18487678, EPI_ISL_18487691, EPI_ISL_18487762, EPI_ISL_18487769, EPI_ISL_18550560, EPI_ISL_18561244, EPI_ISL_18561291, EPI_ISL_18561369, EPI_ISL_18561395, EPI_ISL_18562139, EPI_ISL_18579945, EPI_ISL_18580191, EPI_ISL_18638598, EPI_ISL_18638600, EPI_ISL_18638641, EPI_ISL_18638775, EPI_ISL_18638787, EPI_ISL_18638789, EPI_ISL_18638841, EPI_ISL_18638851, EPI_ISL_18638888, EPI_ISL_18638896, EPI_ISL_18638965, EPI_ISL_18639024, EPI_ISL_18643646, EPI_ISL_18671614, EPI_ISL_18679983, EPI_ISL_18682690, EPI_ISL_18682713, EPI_ISL_18682716, EPI_ISL_18682739, EPI_ISL_18682770, EPI_ISL_18682786, EPI_ISL_18682815, EPI_ISL_18682832, EPI_ISL_18682849, EPI_ISL_18682853, EPI_ISL_18682858, EPI_ISL_18682863, EPI_ISL_18682893, EPI_ISL_18682927, EPI_ISL_18682975, EPI_ISL_18682992, EPI_ISL_18685398, EPI_ISL_18685506, EPI_ISL_18685554, EPI_ISL_18685557, EPI_ISL_18685569, EPI_ISL_18685578, EPI_ISL_18685612, EPI_ISL_18685616, EPI_ISL_18685697, EPI_ISL_18685727, EPI_ISL_18685749, EPI_ISL_18685786, EPI_ISL_18685798-18685799, EPI_ISL_18685880, EPI_ISL_18685883, EPI_ISL_18685899, EPI_ISL_18685909, EPI_ISL_18685950, EPI_ISL_18685959, EPI_ISL_18685961, EPI_ISL_18685971, EPI_ISL_18685985, EPI_ISL_18685989, EPI_ISL_18686007, EPI_ISL_18686025, EPI_ISL_18686062, EPI_ISL_18686126, EPI_ISL_18686139, EPI_ISL_18686154, EPI_ISL_18686177, EPI_ISL_18686208-18686209, EPI_ISL_18686226, EPI_ISL_18686238-18686239, EPI_ISL_18686245, EPI_ISL_18703850, EPI_ISL_18721444, EPI_ISL_18736049, EPI_ISL_18736052, EPI_ISL_18736143, EPI_ISL_18736157-18736158, EPI_ISL_18736170, EPI_ISL_18736195, EPI_ISL_18736197, EPI_ISL_18736201, EPI_ISL_18736207, EPI_ISL_18736221, EPI_ISL_18736250, EPI_ISL_18736252, EPI_ISL_18736386-18736387, EPI_ISL_18736424, EPI_ISL_18736426, EPI_ISL_18736441, EPI_ISL_18736452, EPI_ISL_18736461, EPI_ISL_18736518, EPI_ISL_18736534, EPI_ISL_18736539, EPI_ISL_18736548, EPI_ISL_18736579, EPI_ISL_18736634, EPI_ISL_18736669, EPI_ISL_18736690, EPI_ISL_18736744, EPI_ISL_18736752, EPI_ISL_18736763, EPI_ISL_18736846, EPI_ISL_18736855, EPI_ISL_18736896, EPI_ISL_18736905, EPI_ISL_18736950, EPI_ISL_18736973, EPI_ISL_18737032, EPI_ISL_18737087, EPI_ISL_18737119, EPI_ISL_18737147, EPI_ISL_18737164, EPI_ISL_18737170, EPI_ISL_18737183, EPI_ISL_18737189, EPI_ISL_18737194, EPI_ISL_18737205, EPI_ISL_18737208, EPI_ISL_18737221, EPI_ISL_18737289, EPI_ISL_18737343, EPI_ISL_18744035, EPI_ISL_18754622`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22e80_469090.json?label=id:node_3452170
![HK 30+478R](https://github.com/cov-lineages/pango-designation/assets/125747944/1a7f0644-1795-462a-8f4a-42d520c2cf4b)

**Trivia:**
- Formerly (mis)placed under either `C22995G(S:T478R)` branch right under **HK.3** polytomy or **EG.5.1.1**'s flip-flop `C27507T` (aka revoked unclear **HK.32**)

<details><summary>Historical query for those branches, including the real S:T478R branch right under HK.3 polytomy</summary>

`C6541T, C22995G, C29625T, -C541T, -C673T, -G2075A, -G2648A, -T3049C, -C3168A, -G3692T, -G4180A, -G5917A, -T6274C, -C6310T, -G6369T, -C6752T, -G7791A, -C7973T, -A8107T, -C9907T, -T11186C, -C11750T, -C11779T, -G12482A, -A13712G, -C13378T, -C13860T, -A14270T, -T14988C, -G15093A, -C18508T, -T20281C, -T20407C, -G22927T, -T23803C, -T24259C, -C24912T, -C25418A, -C25517T, -G25526T, -T26543C, -T28105C, -C29272T`</details>

**Comment by FedeGueli** [comment]
Alternative query:A27507,T26609C, 22995G,C9319T

**Comment by corneliusroemer** [comment]
What's going on with 27507 there? I'm confused - is this a known artefact?

<img width="2226" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/7200db6f-fd5e-43c7-a2dd-94f7b41ad51e">

**Comment by FedeGueli** [comment]
> What's going on with 27507 there? I'm confused - is this a known artefact?
> 
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/25161793/301893922-7200db6f-fd5e-43c7-a2dd-94f7b41ad51e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTEzMTIsIm5iZiI6MTcwNjg5MTAxMiwicGF0aCI6Ii8yNTE2MTc5My8zMDE4OTM5MjItNzIwMGRiNmYtZmQ1ZS00M2M3LWEyZGQtOTRmN2I0MWFkNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE2MjMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYmUwNzRlNzM2YWYwY2Q1M2E0ZmE3MDBjZjI5NGI1OWJiNDViYzJkYjViMDA1MmQwNmRiMzE5ZDc3MTQ5YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uroqb83_oKYwndAHOIvurB4180QTYevhpjVkV_G_YR8">

Not known one it is just this part of the tree  with it doing flip flop. If you read the original i tried to look into it but still unclear how to explain it

**Comment by corneliusroemer** [comment]
Looks like this just happened homoplasically in those two lineages and Usher (wrongly) decided to put them on the same branch due to dropouts

**Comment by AngieHinrichs** [comment]
Yeah, that looks wrong, I will see if I can get those re-placed separately.
