### ISSUE TITLE
HK.26 with ORF3a:L52I and S:T478R (52 seqs, mainly in Finland, 12 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2459]
_Taken from **Branch 11** of Multitask sars-cov-2-variants/lineage-proposals#787_

**Defining Mutations:** `HK.26 (C25546A/ORF3a:L52I)` > `T9577C` > `C22995G(S:T478R)`
**Query:** `T9577C, T14988C, C22995G`
**Earliest seq:** 2023-09-19 (`EPI_ISL_18452026`, Plovdiv, Bulgaria)
**Latest seq:** 2023-12-28 (`EPI_ISL_18754426`, Västra Götalands, Sweden)
**Sampled Countries:** **Finland** (21), **Sweden** (11), **USA** (7: FL/3; NY; OH; OR; UT), **Denmark** (4), **France** (2), **Bulgaria** (1), **Italy** (1), **Lithuania** (1), **New Zealand** (1), **Norway** (1), **Portugal** (1), **UK** (1: EN)

<details><summary>Genomes: </summary>

`EPI_ISL_18452026, EPI_ISL_18458286, EPI_ISL_18458317, EPI_ISL_18458355, EPI_ISL_18458443, EPI_ISL_18498158, EPI_ISL_18499386, EPI_ISL_18500972, EPI_ISL_18500991, EPI_ISL_18501018, EPI_ISL_18521950, EPI_ISL_18523122, EPI_ISL_18540316, EPI_ISL_18541289, EPI_ISL_18541379, EPI_ISL_18569438, EPI_ISL_18587007, EPI_ISL_18587319, EPI_ISL_18588097, EPI_ISL_18596255, EPI_ISL_18596358, EPI_ISL_18626259, EPI_ISL_18634896, EPI_ISL_18634919, EPI_ISL_18634926, EPI_ISL_18635176, EPI_ISL_18635277, EPI_ISL_18635292, EPI_ISL_18635314, EPI_ISL_18635338, EPI_ISL_18635342, EPI_ISL_18635361, EPI_ISL_18635367, EPI_ISL_18635372, EPI_ISL_18636458, EPI_ISL_18654029, EPI_ISL_18668754, EPI_ISL_18670579, EPI_ISL_18680850, EPI_ISL_18688452, EPI_ISL_18694205, EPI_ISL_18713134, EPI_ISL_18713140, EPI_ISL_18713154, EPI_ISL_18714214, EPI_ISL_18716916, EPI_ISL_18726965, EPI_ISL_18729107, EPI_ISL_18729197, EPI_ISL_18753036, EPI_ISL_18754426, EPI_ISL_18756863`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ee6f_46f550.json?f_userOrOld=uploaded%20sample&label=id:node_3524511
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/a694370d-d217-4120-9b6b-98e5659bb012)

**Comment by FedeGueli** [comment]
57 now

**Comment by FedeGueli** [comment]
59 now, although still to be sampled in January

**Comment by FedeGueli** [comment]
67  new country Bulgaria (13 tot) 4 samples in january
