### ISSUE TITLE
Proposal for South African Delta sub-lineage (~50%, 15k seq)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#246]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: B.1.617.2
Earliest sequence: May 2021 (South Africa)
Most recent sequence: Current
Countries circulating: Mostly South Africa where it makes up ~50 of all sequences

Defining: nuc:25413T then ORF1b:115I
There is another smaller lineage, also mostly South Africa with nuc:25413T + ORF1a:536L + ORF8:115C that may be designated as well. 

One could always choose nuc:25413T by itself as common ancestor of both because that lineage is present in many more countries. Narrowing to ORF1b:115I makes it more focused on South Africa.

I'd designate the parent of both that has nuc:25413T, since that's the epidemiologically significant (it seems, single introduction to SA)

https://nextstrain.org/groups/neherlab/ncov/global?branchLabel=aa&c=gt-nuc_25413
![image](https://user-images.githubusercontent.com/25161793/136815557-e7c082d2-dc3b-42a0-b08e-590a26909145.png)

Genomes
[nuc:25413T.txt](https://github.com/cov-lineages/pango-designation/files/7323610/nuc.25413T.txt)
[ORF1b:115I.txt](https://github.com/cov-lineages/pango-designation/files/7323612/ORF1b.115I.txt)

Proposed lineage name
AY.x

**Comment by chrisruis** [comment]
Thanks @corneliusroemer It looks like these sequences have been split in the latest UShER tree so they are now in several clades that branch off a large polytomy. There is a clear South Africa clade that contains a lot of the sequences and we've designated this clade as AY.45 in [v1.2.87](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.87). AY.45 starts on a branch with G13812T (Orf1ab:M4516I) and has 3669 sequence designations. It looks like the other sequences are in small clades without clear geographical clustering so we haven't designated these for now.

**Comment by FedeGueli** [comment]
cc @chrisruis @corneliusroemer 
The previously undesignated subclade proposed here  starting with ORF8:R115C has now been designated AY.91 
commit: 
https://github.com/cov-lineages/pango-designation/commit/d11d64b93df7a664779b5c38c3cdc8347ad4585e

and

https://github.com/cov-lineages/pango-designation/commit/086bbc11a7c6f1cf7ac4caeeb85dc3dea780b0e4
