### ISSUE TITLE
JN.1 +Orf3a:L85F + ORF1a:T2152I +S:T572I  (650 ). With a S:F456L sub-branch (384)  with Multiple branches of interest: 1) R346T Branch (62) 2) S:S60P,S:W64L branch (23) 3) Orf9b:E7V branch (44)  

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2461]
transferred from Branch 14 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1097 
**EDITED on June 19** 
Now **JN.1.65**:
JN.1 >> **Orf3a:L85F (G25647T) > T23629C > A5053G, ORF1a:T2152I (C6720T)> S:T572I (C23277T)**
Query: C23277T, A5053G ,C6720T
Country: Uk
Samples:469
<Details>
<Summary>
IDs
</Summary>
EPI_ISL_18684531, EPI_ISL_18684647-18684648, EPI_ISL_18684650-18684651,
EPI_ISL_18684765, EPI_ISL_18688351, EPI_ISL_18688369,
EPI_ISL_18688406, EPI_ISL_18688468, EPI_ISL_18688472,
EPI_ISL_18688476, EPI_ISL_18694531, EPI_ISL_18707741,
EPI_ISL_18707846, EPI_ISL_18712894, EPI_ISL_18712900,
EPI_ISL_18727128, EPI_ISL_18735596, EPI_ISL_18735610,
EPI_ISL_18735617, EPI_ISL_18735633, EPI_ISL_18735638,
EPI_ISL_18763566, EPI_ISL_18763706, EPI_ISL_18763739,
EPI_ISL_18763916, EPI_ISL_18763918, EPI_ISL_18764279,
EPI_ISL_18764324, EPI_ISL_18764350, EPI_ISL_18764375,
EPI_ISL_18771812, EPI_ISL_18782642, EPI_ISL_18782650,
EPI_ISL_18782762, EPI_ISL_18793755, EPI_ISL_18800507,
EPI_ISL_18800687, EPI_ISL_18800702, EPI_ISL_18800768,
EPI_ISL_18809664, EPI_ISL_18809674, EPI_ISL_18809680,
EPI_ISL_18809768, EPI_ISL_18809806, EPI_ISL_18821717,
EPI_ISL_18825003, EPI_ISL_18825046, EPI_ISL_18830621,
EPI_ISL_18831842, EPI_ISL_18842841, EPI_ISL_18854606-18854607,
EPI_ISL_18854664, EPI_ISL_18854695, EPI_ISL_18854732,
EPI_ISL_18860690, EPI_ISL_18860838, EPI_ISL_18867115,
EPI_ISL_18867150, EPI_ISL_18867170-18867171, EPI_ISL_18867186,
EPI_ISL_18867235, EPI_ISL_18867237, EPI_ISL_18867246,
EPI_ISL_18877469, EPI_ISL_18877522, EPI_ISL_18877532-18877533,
EPI_ISL_18881026, EPI_ISL_18881411, EPI_ISL_18881565,
EPI_ISL_18881572, EPI_ISL_18881639, EPI_ISL_18881676,
EPI_ISL_18881716, EPI_ISL_18881782, EPI_ISL_18881786,
EPI_ISL_18885365, EPI_ISL_18890651, EPI_ISL_18890658,
EPI_ISL_18901473, EPI_ISL_18901481, EPI_ISL_18910236,
EPI_ISL_18910243, EPI_ISL_18910294, EPI_ISL_18910384,
EPI_ISL_18910388, EPI_ISL_18910392, EPI_ISL_18913399,
EPI_ISL_18913484, EPI_ISL_18926656, EPI_ISL_18926683,
EPI_ISL_18932469, EPI_ISL_18932491, EPI_ISL_18932493,
EPI_ISL_18932509, EPI_ISL_18932526, EPI_ISL_18932544,
EPI_ISL_18932595, EPI_ISL_18932611, EPI_ISL_18932622,
EPI_ISL_18932626, EPI_ISL_18932741, EPI_ISL_18932748,
EPI_ISL_18932802, EPI_ISL_18932806, EPI_ISL_18936357,
EPI_ISL_18936381, EPI_ISL_18936388, EPI_ISL_18936392,
EPI_ISL_18944071, EPI_ISL_18944089, EPI_ISL_18944123,
EPI_ISL_18944138, EPI_ISL_18951109, EPI_ISL_18951113,
EPI_ISL_18951119, EPI_ISL_18969285, EPI_ISL_18969296,
EPI_ISL_18969472, EPI_ISL_18969480, EPI_ISL_18969510,
EPI_ISL_18969512, EPI_ISL_18976298, EPI_ISL_18983519,
EPI_ISL_18987628, EPI_ISL_18987660, EPI_ISL_18987672,
EPI_ISL_18987677, EPI_ISL_18987734, EPI_ISL_18993577,
EPI_ISL_18993581, EPI_ISL_18993592, EPI_ISL_19002144,
EPI_ISL_19002157, EPI_ISL_19002162, EPI_ISL_19006607,
EPI_ISL_19006626, EPI_ISL_19006700, EPI_ISL_19006723,
EPI_ISL_19010296, EPI_ISL_19010329, EPI_ISL_19010335-19010337,
EPI_ISL_19010426, EPI_ISL_19022882, EPI_ISL_19022931,
EPI_ISL_19022989, EPI_ISL_19023011, EPI_ISL_19023038,
EPI_ISL_19023071, EPI_ISL_19023110, EPI_ISL_19025890,
EPI_ISL_19025916, EPI_ISL_19025919, EPI_ISL_19033350,
EPI_ISL_19033911, EPI_ISL_19033942, EPI_ISL_19036248,
EPI_ISL_19044471, EPI_ISL_19044593, EPI_ISL_19044598,
EPI_ISL_19050414, EPI_ISL_19050557, EPI_ISL_19053436,
EPI_ISL_19053555, EPI_ISL_19055598, EPI_ISL_19055604-19055606,
EPI_ISL_19055608, EPI_ISL_19055611, EPI_ISL_19055691,
EPI_ISL_19062578, EPI_ISL_19062829, EPI_ISL_19069644,
EPI_ISL_19069674, EPI_ISL_19072210-19072211, EPI_ISL_19086847,
EPI_ISL_19088201, EPI_ISL_19094350, EPI_ISL_19095494,
EPI_ISL_19108595, EPI_ISL_19108707, EPI_ISL_19109642,
EPI_ISL_19131015, EPI_ISL_19131019, EPI_ISL_19132948,
EPI_ISL_19132956, EPI_ISL_19139041, EPI_ISL_19139118,
EPI_ISL_19139281, EPI_ISL_19140784, EPI_ISL_19140805,
EPI_ISL_19140993, EPI_ISL_19141024, EPI_ISL_19141029,
EPI_ISL_19141034, EPI_ISL_19141036-19141037, EPI_ISL_19141043,
EPI_ISL_19143904-19143909, EPI_ISL_19143911, EPI_ISL_19143917,
EPI_ISL_19143923, EPI_ISL_19144180, EPI_ISL_19144197,
EPI_ISL_19144618, EPI_ISL_19145550, EPI_ISL_19146225,
EPI_ISL_19146330, EPI_ISL_19146333, EPI_ISL_19146351,
EPI_ISL_19146361, EPI_ISL_19146364, EPI_ISL_19147157,
EPI_ISL_19151164, EPI_ISL_19151440, EPI_ISL_19157480-19157481,
EPI_ISL_19157651, EPI_ISL_19157653, EPI_ISL_19159971-19159972,
EPI_ISL_19161853, EPI_ISL_19162085, EPI_ISL_19163971-19163972,
EPI_ISL_19164413, EPI_ISL_19164656, EPI_ISL_19164707,
EPI_ISL_19164727, EPI_ISL_19164729-19164730, EPI_ISL_19165288,
EPI_ISL_19165386, EPI_ISL_19165403, EPI_ISL_19165812,
EPI_ISL_19165857, EPI_ISL_19165867, EPI_ISL_19165872,
EPI_ISL_19165876-19165877, EPI_ISL_19165885, EPI_ISL_19166083,
EPI_ISL_19166137, EPI_ISL_19166140, EPI_ISL_19166226,
EPI_ISL_19167758, EPI_ISL_19167873, EPI_ISL_19167887,
EPI_ISL_19175150, EPI_ISL_19175162-19175164, EPI_ISL_19175167,
EPI_ISL_19175194-19175195, EPI_ISL_19175297-19175298, EPI_ISL_19175440,
EPI_ISL_19175446, EPI_ISL_19175450, EPI_ISL_19175481,
EPI_ISL_19175503, EPI_ISL_19175518-19175519, EPI_ISL_19175522,
EPI_ISL_19176303-19176304, EPI_ISL_19176346, EPI_ISL_19176364,
EPI_ISL_19176382, EPI_ISL_19176639, EPI_ISL_19176641,
EPI_ISL_19176643, EPI_ISL_19176646, EPI_ISL_19176652,
EPI_ISL_19176658, EPI_ISL_19176909, EPI_ISL_19177779,
EPI_ISL_19178510-19178511, EPI_ISL_19178516-19178517, EPI_ISL_19178521,
EPI_ISL_19178524, EPI_ISL_19178534, EPI_ISL_19178536,
EPI_ISL_19178540, EPI_ISL_19178548, EPI_ISL_19178550,
EPI_ISL_19178558, EPI_ISL_19178561, EPI_ISL_19178568,
EPI_ISL_19178573, EPI_ISL_19178576-19178577, EPI_ISL_19178588,
EPI_ISL_19178596, EPI_ISL_19178602, EPI_ISL_19178605,
EPI_ISL_19178870, EPI_ISL_19178877, EPI_ISL_19178881,
EPI_ISL_19178963, EPI_ISL_19178968, EPI_ISL_19179031,
EPI_ISL_19181403, EPI_ISL_19181412, EPI_ISL_19183236,
EPI_ISL_19183639, EPI_ISL_19185413, EPI_ISL_19185416,
EPI_ISL_19185472, EPI_ISL_19185639, EPI_ISL_19186480,
EPI_ISL_19186482, EPI_ISL_19186670, EPI_ISL_19187535,
EPI_ISL_19187545, EPI_ISL_19187554, EPI_ISL_19187605,
EPI_ISL_19187716, EPI_ISL_19187917-19187918, EPI_ISL_19187921-19187922,
EPI_ISL_19187935, EPI_ISL_19187953, EPI_ISL_19187955,
EPI_ISL_19187959, EPI_ISL_19187967, EPI_ISL_19187974,
EPI_ISL_19187981, EPI_ISL_19188092, EPI_ISL_19188097,
EPI_ISL_19188099, EPI_ISL_19188410, EPI_ISL_19188424,
EPI_ISL_19188428, EPI_ISL_19189750, EPI_ISL_19189775-19189776,
EPI_ISL_19189812-19189816, EPI_ISL_19190049, EPI_ISL_19190058-19190060,
EPI_ISL_19190062, EPI_ISL_19190077, EPI_ISL_19190366-19190367,
EPI_ISL_19190380-19190381, EPI_ISL_19190384-19190385, EPI_ISL_19190387,
EPI_ISL_19190904, EPI_ISL_19191191, EPI_ISL_19191280,
EPI_ISL_19191290, EPI_ISL_19191312, EPI_ISL_19191398,
EPI_ISL_19191417, EPI_ISL_19191426, EPI_ISL_19191556,
EPI_ISL_19191784, EPI_ISL_19192197, EPI_ISL_19192205,
EPI_ISL_19192207, EPI_ISL_19193420, EPI_ISL_19193860,
EPI_ISL_19193876, EPI_ISL_19193916, EPI_ISL_19193921,
EPI_ISL_19193928-19193929, EPI_ISL_19193932, EPI_ISL_19193942,
EPI_ISL_19193945, EPI_ISL_19193995, EPI_ISL_19193997-19193999,
EPI_ISL_19194005, EPI_ISL_19194009, EPI_ISL_19194013,
EPI_ISL_19194462, EPI_ISL_19194764, EPI_ISL_19194771,
EPI_ISL_19194784, EPI_ISL_19194786, EPI_ISL_19194791,
EPI_ISL_19194804, EPI_ISL_19194813, EPI_ISL_19194817,
EPI_ISL_19194828, EPI_ISL_19194843, EPI_ISL_19194845,
EPI_ISL_19194855, EPI_ISL_19194893, EPI_ISL_19194905,
EPI_ISL_19194914-19194915, EPI_ISL_19194953, EPI_ISL_19194961-19194962,
EPI_ISL_19194983, EPI_ISL_19195000, EPI_ISL_19195009,
EPI_ISL_19195035, EPI_ISL_19195044, EPI_ISL_19195060,
EPI_ISL_19195063, EPI_ISL_19195095-19195096, EPI_ISL_19195104,
EPI_ISL_19195119, EPI_ISL_19195781, EPI_ISL_19197010,
EPI_ISL_19197150, EPI_ISL_19197181, EPI_ISL_19197900,
EPI_ISL_19197910, EPI_ISL_19198462, EPI_ISL_19198471,
EPI_ISL_19198523, EPI_ISL_19199255, EPI_ISL_19201275,
EPI_ISL_19201303, EPI_ISL_19201314, EPI_ISL_19201371,
EPI_ISL_19201427, EPI_ISL_19201513, EPI_ISL_19201521,
EPI_ISL_19201526, EPI_ISL_19201589, EPI_ISL_19201592,
EPI_ISL_19201634, EPI_ISL_19201646, EPI_ISL_19201652,
EPI_ISL_19201696, EPI_ISL_19201699, EPI_ISL_19201704,
EPI_ISL_19201716, EPI_ISL_19201728, EPI_ISL_19201730,
EPI_ISL_19203586, EPI_ISL_19203623
</details>

NOW **JN.1.65.1**:
**BRANCH with S:F456L**
There is a further **COMBO** branch with S:F456L spotted and tracked by **@aviczhl2** 
JN.1 >> Orf3a:L85F (G25647T) > T23629C > A5053G, ORF1a:T2152I (C6720T)> S:T572I (C23277T)**>C5884T, Orf1b:S2339F (C20483T), C29149T > S:F456L (T22928C)**
**  A5053G ,C6720T,T22928C**, 
229 seqs, Spain, Italy, Netherlands, France, US, Portugal, Canada, Canary Isl.,Israel, England
 <Details>
<Summary>
IDs
</Summary>
EPI_ISL_19033350, EPI_ISL_19036248, EPI_ISL_19050414,
EPI_ISL_19072210-19072211, EPI_ISL_19094350, EPI_ISL_19095494,
EPI_ISL_19108707, EPI_ISL_19109642, EPI_ISL_19131015,
EPI_ISL_19131019, EPI_ISL_19132948, EPI_ISL_19132956,
EPI_ISL_19139281, EPI_ISL_19140784, EPI_ISL_19140805,
EPI_ISL_19140993, EPI_ISL_19141024, EPI_ISL_19141034,
EPI_ISL_19141036-19141037, EPI_ISL_19141043, EPI_ISL_19144180,
EPI_ISL_19144197, EPI_ISL_19144618, EPI_ISL_19145550,
EPI_ISL_19146330, EPI_ISL_19146333, EPI_ISL_19146351,
EPI_ISL_19146361, EPI_ISL_19146364, EPI_ISL_19151440,
EPI_ISL_19157480-19157481, EPI_ISL_19157651, EPI_ISL_19157653,
EPI_ISL_19162085, EPI_ISL_19163971-19163972, EPI_ISL_19164413,
EPI_ISL_19164656, EPI_ISL_19164707, EPI_ISL_19164727,
EPI_ISL_19164729-19164730, EPI_ISL_19165386, EPI_ISL_19165403,
EPI_ISL_19165812, EPI_ISL_19165857, EPI_ISL_19165867,
EPI_ISL_19165872, EPI_ISL_19165876-19165877, EPI_ISL_19165885,
EPI_ISL_19166083, EPI_ISL_19166137, EPI_ISL_19166140,
EPI_ISL_19166226, EPI_ISL_19167758, EPI_ISL_19167873,
EPI_ISL_19167887, EPI_ISL_19175150, EPI_ISL_19175162-19175164,
EPI_ISL_19175167, EPI_ISL_19175194-19175195, EPI_ISL_19175297-19175298,
EPI_ISL_19175440, EPI_ISL_19175446, EPI_ISL_19175481,
EPI_ISL_19175503, EPI_ISL_19175518-19175519, EPI_ISL_19175522,
EPI_ISL_19176303-19176304, EPI_ISL_19176346, EPI_ISL_19176364,
EPI_ISL_19176382, EPI_ISL_19177779, EPI_ISL_19178548,
EPI_ISL_19178550, EPI_ISL_19178558, EPI_ISL_19178561,
EPI_ISL_19178568, EPI_ISL_19178573, EPI_ISL_19178576-19178577,
EPI_ISL_19178588, EPI_ISL_19178596, EPI_ISL_19178602,
EPI_ISL_19178605, EPI_ISL_19178870, EPI_ISL_19178877,
EPI_ISL_19178881, EPI_ISL_19178963, EPI_ISL_19178968,
EPI_ISL_19179031, EPI_ISL_19181403, EPI_ISL_19181412,
EPI_ISL_19183639, EPI_ISL_19185413, EPI_ISL_19185416,
EPI_ISL_19185472, EPI_ISL_19185639, EPI_ISL_19186480,
EPI_ISL_19186482, EPI_ISL_19186670, EPI_ISL_19187535,
EPI_ISL_19187545, EPI_ISL_19187554, EPI_ISL_19187605,
EPI_ISL_19187917-19187918, EPI_ISL_19187921-19187922, EPI_ISL_19187935,
EPI_ISL_19187953, EPI_ISL_19187955, EPI_ISL_19188092,
EPI_ISL_19188097, EPI_ISL_19188099, EPI_ISL_19189750,
EPI_ISL_19189775-19189776, EPI_ISL_19189812-19189816, EPI_ISL_19190049,
EPI_ISL_19190058-19190060, EPI_ISL_19190062, EPI_ISL_19190077,
EPI_ISL_19190366-19190367, EPI_ISL_19190904, EPI_ISL_19191191,
EPI_ISL_19191280, EPI_ISL_19191290, EPI_ISL_19191312,
EPI_ISL_19191398, EPI_ISL_19191417, EPI_ISL_19191426,
EPI_ISL_19191556, EPI_ISL_19191784, EPI_ISL_19192197,
EPI_ISL_19192205, EPI_ISL_19192207, EPI_ISL_19193420,
EPI_ISL_19193860, EPI_ISL_19193876, EPI_ISL_19193916,
EPI_ISL_19193921, EPI_ISL_19193928-19193929, EPI_ISL_19193932,
EPI_ISL_19193942, EPI_ISL_19193945, EPI_ISL_19193995,
EPI_ISL_19193997-19193999, EPI_ISL_19194005, EPI_ISL_19194009,
EPI_ISL_19194013, EPI_ISL_19194462, EPI_ISL_19194764,
EPI_ISL_19194771, EPI_ISL_19194784, EPI_ISL_19194786,
EPI_ISL_19194791, EPI_ISL_19194804, EPI_ISL_19194813,
EPI_ISL_19194817, EPI_ISL_19194843, EPI_ISL_19194845,
EPI_ISL_19194855, EPI_ISL_19194893, EPI_ISL_19194905,
EPI_ISL_19194914-19194915, EPI_ISL_19194924, EPI_ISL_19194953,
EPI_ISL_19194961-19194962, EPI_ISL_19194983, EPI_ISL_19195009,
EPI_ISL_19195035, EPI_ISL_19195044, EPI_ISL_19195060,
EPI_ISL_19195063, EPI_ISL_19195095-19195096, EPI_ISL_19195104,
EPI_ISL_19195781, EPI_ISL_19197010, EPI_ISL_19197900,
EPI_ISL_19197910, EPI_ISL_19198462, EPI_ISL_19198471,
EPI_ISL_19198523, EPI_ISL_19199255, EPI_ISL_19201275,
EPI_ISL_19201303, EPI_ISL_19201314, EPI_ISL_19201371,
EPI_ISL_19201418, EPI_ISL_19201427, EPI_ISL_19201513,
EPI_ISL_19201521, EPI_ISL_19201526, EPI_ISL_19201589,
EPI_ISL_19201592, EPI_ISL_19201634, EPI_ISL_19201646,
EPI_ISL_19201652, EPI_ISL_19201696, EPI_ISL_19201699,
EPI_ISL_19201704, EPI_ISL_19201716, EPI_ISL_19201728,
EPI_ISL_19201730, EPI_ISL_19203623
</Details>

_There are further branches of interest_:

Now **MF.1**:
**Branch with TRIO (346T 456L 572I):**
 thanks to @NkRMnZr for highlighting the previous query was not catching most of them
JN.1 >> Orf3a:L85F (G25647T) > T23629C > A5053G, ORF1a:T2152I (C6720T)> S:T572I (C23277T)>C5884T, Orf1b:S2339F (C20483T), C29149T > S:F456L (T22928C)> **Reversion Orf1b:F2339FS (T20483C)> SIlent S:Y473Y (T22981C) > Silent S:Y37Y (T21673C), S:R346T (G22599C)**  
Query: T22981C,T21673C ,G22599C
Samples:30 (Spain , US, France, Israel, Italy)
<Details>
<Summary>
IDs
</Summary>
EPI_ISL_19094350, EPI_ISL_19141036, EPI_ISL_19175162,
EPI_ISL_19176364, EPI_ISL_19177779, EPI_ISL_19179031,
EPI_ISL_19183639, EPI_ISL_19187921, EPI_ISL_19188424,
EPI_ISL_19189750, EPI_ISL_19189775-19189776, EPI_ISL_19191398,
EPI_ISL_19191417, EPI_ISL_19191426, EPI_ISL_19191556,
EPI_ISL_19193928, EPI_ISL_19194773, EPI_ISL_19194845,
EPI_ISL_19194914-19194915, EPI_ISL_19195096, EPI_ISL_19195104,
EPI_ISL_19197181, EPI_ISL_19198523, EPI_ISL_19201589,
EPI_ISL_19201592, EPI_ISL_19201646, EPI_ISL_19201716,
EPI_ISL_19203623
</Details>

NOW **MF.2**:
**On the S:F456L Branch  Sublineage with further S:S60P S:W64L** 
spotted by @NkRMnZr (see comments)
JN.1 >> Orf3a:L85F (G25647T) > T23629C > A5053G, ORF1a:T2152I (C6720T)> S:T572I (C23277T)>C5884T, Orf1b:S2339F (C20483T), C29149T > S:F456L (T22928C) > **S:S60P (T21740C), S:W64L (G21753T)**
Query:  T21740C,G21753T,T3565C [EDITED there was a typo between S:W64L (correct)and S:W64R(wrong)]
Samples: 19 (Spain, England, Ireland, US)
<Details>
<Summary>
IDs
</Summary>
EPI_ISL_19164730, EPI_ISL_19176639, EPI_ISL_19178558,
EPI_ISL_19178568, EPI_ISL_19178596, EPI_ISL_19178605,
EPI_ISL_19187637, EPI_ISL_19187967, EPI_ISL_19193916,
EPI_ISL_19193921, EPI_ISL_19194771, EPI_ISL_19194784,
EPI_ISL_19194786, EPI_ISL_19201526, EPI_ISL_19201652,
EPI_ISL_19201696, EPI_ISL_19201699, EPI_ISL_19201704,
EPI_ISL_19201730
</Details>

**On the S:F456L Branch sublineage with further S:V503I** 
JN.1 >> Orf3a:L85F (G25647T) > T23629C > A5053G, ORF1a:T2152I (C6720T)> S:T572I (C23277T)>C5884T, Orf1b:S2339F (C20483T), C29149T > S:F456L (T22928C)> **Reversion Orf1b:F2339FS (T20483C) > T22981C> S:V503I (G23069A)** 
Query: T22981C ,G23069A, A10420G
Samples: 5 (Spain and France)
<Details>
<Summary>
IDs
</Summary>
EPI_ISL_19146333, EPI_ISL_19189812, EPI_ISL_19194804,
EPI_ISL_19194905, EPI_ISL_19194983
</Details>

 
**New Update on June 21:**
It seems that this lineage has got a fast sublineage defined by Orf9:E7V too:
JN.1 >> Orf3a:L85F (G25647T) > T23629C > A5053G, ORF1a:T2152I (C6720T)> S:T572I (C23277T)>C5884T, Orf1b:S2339F (C20483T), C29149T > S:F456L (T22928C)> **Reversion Orf1b:F2339FS (T20483C) > T22981C > G19800A, C21342T, Orf9b:E7V (A28303T)
Query:G19800A, A28303T  ,C21342T
Samples: 35 (Spain, Netherlands, England Italy-GBW and France)
<Details>
<Summary>
IDs
</Summary>
EPI_ISL_19139281, EPI_ISL_19140784, EPI_ISL_19146330,
EPI_ISL_19157480-19157481, EPI_ISL_19164413, EPI_ISL_19167887,
EPI_ISL_19175163-19175164, EPI_ISL_19175167, EPI_ISL_19175519,
EPI_ISL_19178588, EPI_ISL_19188097, EPI_ISL_19189814-19189816,
EPI_ISL_19193876, EPI_ISL_19193929, EPI_ISL_19193945,
EPI_ISL_19193995, EPI_ISL_19193997-19193999, EPI_ISL_19194009,
EPI_ISL_19194013, EPI_ISL_19194764-19194765, EPI_ISL_19194961,
EPI_ISL_19197900, EPI_ISL_19197910, EPI_ISL_19201275,
EPI_ISL_19201314, EPI_ISL_19201521, EPI_ISL_19206061,
EPI_ISL_19210123
</details>

Tree as of June 21:
<img width="1154" alt="Screenshot 2024-06-22 alle 02 38 01" src="https://github.com/cov-lineages/pango-designation/assets/87669813/d65a5fda-eadc-456f-a1ca-2d645cc60b64">
<img width="1168" alt="Screenshot 2024-06-22 alle 02 39 41" src="https://github.com/cov-lineages/pango-designation/assets/87669813/1ae9ea5b-fb60-447a-a8dd-322d238e254f">
<img width="1172" alt="Screenshot 2024-06-22 alle 02 40 21" src="https://github.com/cov-lineages/pango-designation/assets/87669813/436cc498-a534-42ca-a72e-47c1fef3942d">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_26d0d_61a540.json?c=gt-nuc_28303&gmax=29303&gmin=27303&label=id:node_6941360

_Many thanks to @aviczhl2 and @NkRMnZr for helping in tracking this lineage_

**Comment by FedeGueli** [comment]
46 now but only England.

**Comment by FedeGueli** [comment]
51

**Comment by FedeGueli** [comment]
67

**Comment by FedeGueli** [comment]
109

**Comment by aviczhl2** [comment]
There is an S:F456L branch under this now.

**Comment by FedeGueli** [comment]
190 now with 9 carrying 456L

**Comment by FedeGueli** [comment]
194 and 13 with 456L

**Comment by FedeGueli** [comment]
@corneliusroemer the 456L branch quite unexplicably has started to climb the charts, i suspect that the ongoing starting wave in Spain shortened very much time from collecting to uploading artificially booosting the growth of lineages based in Spain ( Spain represents around 5% of samples in May when it was around 2% in March)

**Comment by FedeGueli** [comment]
@corneliusroemer likely this one the only one quite fast ( togetrher with the 456L + M:L46F from China) that you missed in your superlative night effort in designations.

**Comment by FedeGueli** [comment]
77 for the 456L branch, @corneliusroemer i suggest to designate it because it is around 5% (23/435) in Spain after May 10, and Spain is experiencing a wave right now

**Comment by FedeGueli** [comment]
One more Trio sequence added from Andalusia right now.

**Comment by FedeGueli** [comment]
333 - 115 - 3

**Comment by FedeGueli** [comment]
142 +17 today

**Comment by FedeGueli** [comment]
439 with 203 Flirt @corneliusroemer another designation needed here

**Comment by Memorablea** [comment]
@corneliusroemer

**Comment by FedeGueli** [comment]
@corneliusroemer please take a look at this collective work in tracking this lineage that is urgent to designate.
All three and samples updated as of today.

**Comment by FedeGueli** [comment]
thx @Aviczhl2 i have updated, this should be designate , it is quite a textbook example of stepwise evo.

**Comment by DailyCovidCases** [comment]
Designated JN.1.65, JN.1.65.1, MF.1 (JN.1.65.1.1), MF.2 (JN.1.65.1.2)

**Comment by FedeGueli** [comment]
all designated JN.1.65 (572I) , JN.1.65.1 (456L) MF.1 (Trio) MF.2 ( S:S60P,S:W64L) via 
https://github.com/cov-lineages/pango-designation/commit/0720b7772f5e12cd6e7b550f2acb215c462e32e1
