### ISSUE TITLE
JN.1.4 + S:N185D ( 293 sequences, 8 countries)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2462]
Transferred from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/1180

Defining mutations:
JN.1.4 [Orf1a:T170I (C774T)] > T18453C > S:N185D (A22115G)

Query:C774T,T18453C,A22115G
Tree:
<img width="1170" alt="Screenshot 2024-01-17 alle 13 10 04" src="https://github.com/cov-lineages/pango-designation/assets/87669813/7e3015e4-c7d5-4971-ab19-293a1727779f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_9e38_7c3610.json?label=id:node_6862179
Countries:
<img width="224" alt="Screenshot 2024-01-17 alle 13 10 35" src="https://github.com/cov-lineages/pango-designation/assets/87669813/516477c5-7c68-46a2-85ca-ecec59d8113e">
Samples: 118 
First sample collected on 2023-11-17 EPI_ISL_18601499 NY
IDs:
<Details> 
<Summary>
Here
</summary>
EPI_ISL_18601499, EPI_ISL_18621722, EPI_ISL_18621757,
EPI_ISL_18621810, EPI_ISL_18621904, EPI_ISL_18621928,
EPI_ISL_18636446, EPI_ISL_18636476, EPI_ISL_18636501,
EPI_ISL_18644755, EPI_ISL_18644779, EPI_ISL_18691048,
EPI_ISL_18691137, EPI_ISL_18691301, EPI_ISL_18691545,
EPI_ISL_18691870, EPI_ISL_18691903, EPI_ISL_18691931,
EPI_ISL_18692251, EPI_ISL_18692305, EPI_ISL_18695464,
EPI_ISL_18695471, EPI_ISL_18704446, EPI_ISL_18704455,
EPI_ISL_18713067, EPI_ISL_18714063, EPI_ISL_18721012,
EPI_ISL_18724910, EPI_ISL_18728290, EPI_ISL_18728325,
EPI_ISL_18728449, EPI_ISL_18728496, EPI_ISL_18728527,
EPI_ISL_18728652, EPI_ISL_18728657, EPI_ISL_18728668,
EPI_ISL_18728670, EPI_ISL_18728694, EPI_ISL_18728759,
EPI_ISL_18728972, EPI_ISL_18729007, EPI_ISL_18729017,
EPI_ISL_18729037, EPI_ISL_18729054, EPI_ISL_18729134,
EPI_ISL_18729192, EPI_ISL_18729205, EPI_ISL_18729208,
EPI_ISL_18729217, EPI_ISL_18729239, EPI_ISL_18729302,
EPI_ISL_18730675, EPI_ISL_18730696-18730697, EPI_ISL_18730700,
EPI_ISL_18730704, EPI_ISL_18730707, EPI_ISL_18730730,
EPI_ISL_18730733, EPI_ISL_18730737, EPI_ISL_18741991,
EPI_ISL_18751814, EPI_ISL_18756465, EPI_ISL_18756723,
EPI_ISL_18756898, EPI_ISL_18756989, EPI_ISL_18757115,
EPI_ISL_18757125, EPI_ISL_18757139, EPI_ISL_18757166,
EPI_ISL_18757171, EPI_ISL_18757222, EPI_ISL_18757358,
EPI_ISL_18757369, EPI_ISL_18757389, EPI_ISL_18757394,
EPI_ISL_18757553, EPI_ISL_18769099, EPI_ISL_18772763,
EPI_ISL_18772813, EPI_ISL_18772843, EPI_ISL_18773880,
EPI_ISL_18778005, EPI_ISL_18779060, EPI_ISL_18779063,
EPI_ISL_18779074, EPI_ISL_18779080, EPI_ISL_18779291,
EPI_ISL_18779337, EPI_ISL_18779563, EPI_ISL_18779844,
EPI_ISL_18779864, EPI_ISL_18779875, EPI_ISL_18779934,
EPI_ISL_18779968, EPI_ISL_18780053, EPI_ISL_18780075,
EPI_ISL_18780298, EPI_ISL_18780341, EPI_ISL_18780385,
EPI_ISL_18780436, EPI_ISL_18780516, EPI_ISL_18780646,
EPI_ISL_18780660, EPI_ISL_18780664, EPI_ISL_18780766,
EPI_ISL_18780793, EPI_ISL_18780854, EPI_ISL_18780866-18780867,
EPI_ISL_18780935, EPI_ISL_18780969, EPI_ISL_18780991,
EPI_ISL_18781042, EPI_ISL_18781047, EPI_ISL_18781072,
EPI_ISL_18781131, EPI_ISL_18781162
</details>

**Comment by FedeGueli** [comment]
169 expanding to South Korea and Canada

**Comment by FedeGueli** [comment]
251 now widespread in different countries and 4 continents , @corneliusroemer i suggest to designate it.

**Comment by FedeGueli** [comment]
293 new country new continent.

**Comment by Mydtlwn** [comment]
@corneliusroemer
