### ISSUE TITLE
JN.1 with S:A1087S > S:R346T > S:F59S [17 with 346, US east coast + 1 Canada]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#2464]
GISAID query: `C26894T,C25680T,G24821T`

Could be that 346T becomes increasingly beneficial as immunity to JN.1 without 346T develops. The first 346T lineages e.g. in France didn't seem to have growth advantage. Maybe that's changing now.

JN.1 with S:A1087S > S:R346T > S:F59S [17 with 346, US east coast + 1 Canada]

<img width="1418" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/0dcf5652-c624-4163-b3dd-2fcd14116d37">

Tricky thing here is that it's not clear how to break into sublineages, if at all. I'd prefer to wait a few more days to see where it makes sense to delineate.

<img width="2164" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/cf727aff-a22a-4d6a-b268-8dd1f73092b7">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_29456_810590.json

**Comment by ujoshi4** [comment]
This seems to be the best S:R346T branch with that S2 mutation that might be evasive.
