### ISSUE TITLE
JN.1 + S:N185S(105 seq, 12 countries)

### ISSUE THREAD

**Issue by DoropFan** [cov-lineages/pango-designation#2471]
Transferred from:https://github.com/sars-cov-2-variants/lineage-proposals/issues/1214

Sub-lineage of:JN.1(BA.2.86.1.1)
Earliest sequence:2023-10-31(Spain)EPI_ISL_18724688

UShER Tree
JN.1>C11833T, T27863C>C27434T(ORF7a:T14I)>T14100C, A22116G(S:N185S), C27810T(ORF7b:L19F(rev)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1409e_f214d0.json?c=gt-nuc_22116&gmax=23116&gmin=21116&label=id:node_6846872
GISAID:T14100C, A22116G, C27434T
![JN1+185Sp2](https://github.com/cov-lineages/pango-designation/assets/118802079/dd6efff8-7d12-4a1c-b045-621d5f424254)

[CovSpectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3AN185S%2CORF7a%3AT14I&nextcladePangoLineage=JN.1*)
[Genomes](https://lapis.cov-spectrum.org/gisaid/v1/sample/gisaid-epi-isl?dateFrom=2020-01-06&dateTo=2024-01-16&aaMutations=S%3AN185S%2CORF7a%3AT14I&nextcladePangoLineage=JN.1*&host=Human&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&orderBy=random)

**Comment by corneliusroemer** [comment]
The reversion is weird - it sort of points at recombination but there's not much other evidence for it.

**Comment by aviczhl2** [comment]
> T27863C>C27434T

The prevalence of two nearby mutations lower the chance for recomb. If it is a recomb it has to be a sandwich recomb with BP 1 between 27435 and 27809 and BP 2 between 27811 and 27862.

**Comment by FedeGueli** [comment]
this slowed down a lot. 105 now.

**Comment by DoropFan** [comment]
There seems to be no new sequence, so I'll close it.

**Comment by DoropFan** [comment]
There seems to be no new sequence, so I'll close it.
