### ISSUE TITLE
BA.2.86.1/(anything with Orf9b:I5T) recombinant(53 seqs, 12 countries) 

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2474]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1164

BA.2.86.1+T11914C,T28297C, A28958C(rev)

Orf9b:I5T
N:K229Q(rev)

T11914C from a BA.2.86.1 branch
T28297C, A28958C(rev) from an anything with Orf9b:I5T (May not restricted to XBB* as there is also chance for XCT,XDH etc)

BA.2.86.1--anything with Orf9b:I5T
Breakpoint between 27916(likely) and 28296

GISAID query: T28297,T11614,-27915,-28958
No. of seqs: 28(Austria 6 Czech Republic 1 Denmark 1 Finland 2 Germany 3 Ireland 1 Italy 3 Netherlands 2 Spain 1 Switzerland 2 USA 6)

First: EPI_ISL_18530899, Germany, 2023-11-9
Latest: EPI_ISL_18821649, Italy,2024-1-17

The green one is proposed recomb. yellow one with Orf8:G8* are other recombs. 
[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/ba_2_86_1_recomb.json?c=gt-ORF8_8&gmax=28259&gmin=27894&label=id:node_6849333)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/66a3ad4b-f2e9-467c-b8db-d72f96a11a09)

**Comment by aviczhl2** [comment]
+1 Iceland

**Comment by FedeGueli** [comment]
It seems to have slowed down

**Comment by aviczhl2** [comment]
No new seqs
