### ISSUE TITLE
Stepwise GK.1.10+S:A475V(Designated GK.1.10.1)+S:Y200C(43 seqs,2 countries)+S:L5F,N450D(20 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2479]
From branch 1 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/814

GK.1.10+C22986T(S:A475V)+C29668T+A22161G(S:Y200C)+C5526T(Orf1a:T1754I)+C21575T(S:L5F),A22910G(S:N450D)

GISAID query for GK.1.10+S:A475V: C12651T, C28567T,C22986T,-T7049C
No. of seqs: 65(Brazil 54 UK 7 Philippines 1 USA 3)
First: EPI_ISL_18572803, Brazil, 2023-9-11
Latest: EPI_ISL_18831479, Brazil, 2023-12-28

GISAID query for S:Y200C sub-branch: A22161G, C12651T, C22986T
No. of seqs: 40(Brazil)
First: EPI_ISL_18558732, 2023-9-20
Latest: EPI_ISL_18831479, 2023-12-28

GISAID query for S:L5F,N450D sub-sub-branch: C21575T,A22910G,C5526T
No. of seqs: 19(Brazil)
First: EPI_ISL_18814311, 2023-12-3
Latest: EPI_ISL_18831479, 2023-12-28

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/gk_1_10_a475v.json?label=id:node_3781821)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/ace98eda-250c-45b0-ad87-e3df2c84cdff)

**Comment by Sinickle** [comment]
The L5F N450D subbranch is now found in Florida - 1 seq, collected Jan 16.

**Comment by corneliusroemer** [comment]
Child lineages with 200C and 450D are interesting but still a bit slow, let's wait a bit more

**Comment by aviczhl2** [comment]
+1 USA for Y200C,L5F,N450D branch
