### ISSUE TITLE
Proposal for a sublineage of AY.4.2 with N:S202I and S:V36F 

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#248]
Joint work with :
Cornelius Romer (https://github.com/corneliusroemer)
Dror Bendet (https://github.com/DrorBendet/)

Description:
Sublineage of AY.4.2
Earliest sequences : 23.07.21
Most resent :  06.10.21
Added non synonymous mutations : N:S202I , S:V36F 
Added synonymous mutations : C15720T,C18687T
Main countries : UK,Germany

GISAID ref :
[AY.4.2. sub lin GISAID list.csv](https://github.com/cov-lineages/pango-designation/files/7332239/AY.4.2.sub.lin.GISAID.list.csv)

Usher :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_170e6_5c2110.json?label=nuc%20mutations:T17040C,G28248A

Global distribution :
![AY 4 2 sub lin spread](https://user-images.githubusercontent.com/80166370/137007678-3fac9ff5-b245-4c56-adc7-b1e2ccf3061e.jpg)

Comparison to AY.4.2 in UK : 

![AY 4 2 sub lin  comparison](https://user-images.githubusercontent.com/80166370/137008573-e9566fac-fe95-4851-9cfd-cccf94d19ae8.jpg)

**Comment by chrisruis** [comment]
Thanks @shay671 We've added this as AY.4.2.1 in [v1.2.93](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.93) starting on the branch with N:S202I (G28878T). It looks like S:V36F was acquired one branch downstream of this but there's only 3 sequences in the latest UShER tree with N:S202I and not S:V36F so both of these mutations are good markers of this lineage.

We've also designated all of the current sequences in the other AY.4.2 clade that has convergently acquired S:V36F as AY.4.2 to try to help assignments of AY.4.2.1
