### ISSUE TITLE
BA.2.86.1/FL.15.1.1 recombinant (25 seqs, 10 countries, 4 with S:A475V) 

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2481]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1291

BA.2.86.1+
C7420T,T22846C, T24378C(rev), T24990C(rev), T25207C(rev),C25416T, A26275G, C26529G(rev), T26681C(rev), T26833C(rev),G27915T, A27980G,T28297C, C28846T,A28958C(rev),T29023C

S:F939S(rev),L1143P(rev)
E:T11A
M:H3D(rev),V104A(rev)
Orf8:G8*
Orf9b:I5T
N:K229Q(rev)

BA.2.86.1--FL.15.1.1
breakpoint between 23605 and 24377

C7420T from a BA.2.86.1* branch, many candidates
T24378C(rev), T24990C(rev), T25207C(rev),C25416T, A26275G, C26529G(rev), T26681C(rev), T26833C(rev),G27915T, T28297C, C28846T,A28958C(rev) from FL.15.1.1
T29023C from a FL.15.1.1 branch
T22846C,A27980G is private

GISAID query: C28846T,C23604G,C7420T,T28297C
No. of seqs: 22(UK 1 Fujian 1(from Taiwan) Taiwan 1(from Vietnam) Sweden 1 USA 2(1 from Qatar 1 from Japan) South Korea 5 Japan 6(1 from Vietnam) Singapore 5(1 from Hong Kong))

First: EPI_ISL_18598081, 2023-11-14, South Korea
Latest: EPI_ISL_18840256, 2024-1-18, USA from Qatar

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/ba_2_86_1_fl_15_1_1_recomb.json?label=id:node_6858064)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/e2e7f5c5-7052-4f51-aedf-c3eb35b1f05d)

**Comment by FedeGueli** [comment]
24 now + 2 Japan +1 Australia

**Comment by FedeGueli** [comment]
Put here a rapid overview:
<img width="685" alt="Screenshot 2024-01-31 alle 10 01 13" src="https://github.com/cov-lineages/pango-designation/assets/87669813/208a129b-2150-4468-9626-dbad66714246">

**Comment by FedeGueli** [comment]
the branch with S:A475V is now 16
