### ISSUE TITLE
JN.1.5 with C5986T and ORF1a:P1921S first detected in Ticino, Switzerland (231 GISAID seqs as of 2024-01-30; 19 countries, 4 continents) 

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#2482]
Transferring [Pre-Proposal 1228](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1228) on request from @FedeGueli.

Proposing a JN.1.5 sublineage with C5986T, and ORF1a:P1921S (NSP3:P1103S; C6026T) first detected in Ticino, Switzerland. 

As of 2024-01-30, Cov-Spectrum reported 142 good-quality (221 total) JN.1.5+ORF1a:1921S+5986T sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nextcladeQcOverallScoreTo=29&variantQuery=nextcladePangoLineage%3AJN.1.5*+%26+ORF1a%3AP1921S+%26+C5986T&

This lineage has been reported from 4 continents and shows a possible growth advantage over its parent JN.1.5. While this lineage has been detected in stellar sequencing countries Canada and Singapore, the majority of the global sequences are not from these two countries so their relatively intense sequencing is not likely to be biasing the global growth advantage. The plurality of sequences for this lineage are from Malaysia where this lineage's growth relative to its parent JN.1.5 is unimpressive but possibly due to this sublineage already dominating JN.1.5 in that country.

However, in Singapore which has submitted the second-most sequences of this sublineage (66 on CoV-Spectrum as of 2024-01-30), this sublineage shows a growth rate relative its parent JN.1.5 of 42% (confidence interval 22 to 69%).

Checking Bloom and Neher's data https://jbloomlab.github.io/SARS2-mut-fitness/ and https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv, as shown below ORF1a:P1921S is associated with a relative growth advantage for all clades. As a novel 2-nucleotide mutation, ORF1b:V1271T has no data in the Bloom and Neher dataset.

As of 2023-12-25, UShER showed all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_JN 1+ORF1a_1921S+ORF1b_1271T+5986T](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/d17a6f57-ad9c-4b71-a6fb-0b7c37b24cd6)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/12/subtreeAuspice1_genome_CoV-Spectrum_JN.1%2BORF1a_1921S%2BORF1b_1271T%2B5986T.json?c=gt-ORF1ab_1921&label=id%3Anode_6802619

GISAID query: G17278A, T17279C, C5986T, C6026T

First GISAID sequence: Ticino, Switzerland 2023-11-17

Most Recent GISAID sequence: Singapore 2024-01-22

A zip archive of CoV-Spectrum-derived UShER output files for these sequences as of 2023-12-25 is available at [Support-JN.1+ORF1a_P1921S+ORF1b_1271T+5986T.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/13768059/Support-JN.1%2BORF1a_P1921S%2BORF1b_1271T%2B5986T.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences as of 2023-12-25 is available at [gisaid-epi-isl-JN.1+ORF1a_P1921S+ORF1b_1271T+5986T.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/13768061/gisaid-epi-isl-JN.1%2BORF1a_P1921S%2BORF1b_1271T%2B5986T.txt)

Potential effects of the non-synonymous mutation ORF1a:P1921S on viral relative fitness
---------------------------------------------------------------------------------------

From the clade-specific Bloom and Neher estimates (from https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv) of the fitness effects of the non-synonymous mutations, for ORF1a:P1921S:

clade,gene,aa_mutation,delta_fitness
20A,ORF1ab,P1921S,0.45975
20B,ORF1ab,P1921S,1.1701
20C,ORF1ab,P1921S,1.0042
20E,ORF1ab,P1921S,0.9422
20G,ORF1ab,P1921S,0.42036
20I,ORF1ab,P1921S,0.78364
21C,ORF1ab,P1921S,0.46398
21I,ORF1ab,P1921S,0.57457
21J,ORF1ab,P1921S,0.85523
21K,ORF1ab,P1921S,0.82125
21L,ORF1ab,P1921S,0.75162
22A,ORF1ab,P1921S,0.89186
22B,ORF1ab,P1921S,0.83121
22C,ORF1ab,P1921S,0.53524
22D,ORF1ab,P1921S,0.58985
22E,ORF1ab,P1921S,0.84586
22F,ORF1ab,P1921S,1.1764
23A,ORF1ab,P1921S,0.75612
23B,ORF1ab,P1921S,0.057158
23D,ORF1ab,P1921S,0.78267

ORF1a:P1921S has a positive fitness effect for all clades with the strongest positive fitness effect in clades 22F, 20B, 20C, and 20E and a weak likely negligible effect in clade 23B.

As of this writing, Bloom and Neher provide no relative fitness estimates for ORF1b:V1271T. However, for some clades ORF1b:V1271L and ORF1b:V1271A are associated with positive relative fitness impacts with some of the impacts, such as ORF1b:V1271L, having significant positive relative fitness impacts such as +1.6328 in clade 22B and +1.448 in clade 22C. So mutations at ORF1b:V1271 are plausibly beneficial to viral fitness.

**Comment by FedeGueli** [comment]
> a possible growth advantage
Comparison to JN.1.5:
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1.5*&nucMutations1=G17278A%2CT17279C%2CC5986T%2CC6026T&analysisMode=CompareToBaseline&
<img width="987" alt="Screenshot 2024-01-31 alle 10 03 25" src="https://github.com/cov-lineages/pango-designation/assets/87669813/e3956c45-9f52-432a-87cb-23712cf9fe15">

**Comment by alurqu** [comment]
This lineage is still growing but slowly. I'm closing this proposal.

**Comment by Over-There-Is** [comment]
434 now
