### ISSUE TITLE
JN.1.4 + ORF9b:P10F (354 seq in 45 countries as April 24)

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2483]
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/c4a671cf-8060-4a53-a471-36b082d3f538)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d813_a80960.json?label=id:node_6914059
transferred from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/1254

Gisaid Query: C25710T, C28312T, T18453C

**Comment by Over-There-Is** [comment]
420

**Comment by Fearuncle** [comment]
dead
