### ISSUE TITLE
XDT: BA.2.86.4/GK.1 recombinant from Ireland, England and Scotland, 28 samples

### ISSUE THREAD

**Issue by JosetteSchoenma** [cov-lineages/pango-designation#2485]
Originally proposed by @DeepakPhuyal, see https://github.com/sars-cov-2-variants/lineage-proposals/issues/1183

Description:BA.2.86.4/GK.1 recombinant, First and biggest part (incl. from Spike) from BA.2.86.4
Private mutations: Really private:C1601T, T4654C, T7633C, C9661T and A19326G (thanks @Over-There-Is )
From BA.2.86.4: T5767C, A8633G
From GK.1: T25496C, G27014A
Breakpoint: between nucleotide 23673 and 24378 (Spike 704 and 939)
Earliest sequence: 2023-11-13 from Ireland
Most recent sequence: 2024-01-22 from England
Countries circulating: Ireland 20, England 7, Scotland 1
GISAID query: A18492G, C23604G, A25045G, C25658T
or C897A, A7842G, C1601T, A8633G found by @aviczhl2 
CovSpectrum query: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C25658T&pangoLineage=BA.2.86.4*&
Usher tree:
![image](https://github.com/cov-lineages/pango-designation/assets/94831035/e7399812-d375-4565-9753-6909f4d24a79)
Nextclade:
![image](https://github.com/cov-lineages/pango-designation/assets/94831035/84e2ba70-bfb5-4290-839e-df334be0d943)
Nextclade comparison:
![image](https://github.com/cov-lineages/pango-designation/assets/94831035/468d5e4b-77bb-4286-b216-de4bae851cfb)

Note:
I recommend designating this one, since right now half of the BA.2.86.4 sequences found are actually this recombinant.
Plus, BA.2.86.4 seems to have stopped growing, while this recombinant has not.
![image](https://github.com/cov-lineages/pango-designation/assets/94831035/ce4bdf50-0268-4f76-a635-6306effb5cde)

**Comment by JosetteSchoenma** [comment]
EPI_ISL_18729417
EPI_ISL_18521215
EPI_ISL_18636423
EPI_ISL_18636413
EPI_ISL_18636425
EPI_ISL_18636426
EPI_ISL_18722271
EPI_ISL_18722272
EPI_ISL_18722273
EPI_ISL_18722278
EPI_ISL_18722281
EPI_ISL_18737403
EPI_ISL_18754827
EPI_ISL_18737405
EPI_ISL_18763509
EPI_ISL_18815885
EPI_ISL_18784536
EPI_ISL_18784537
EPI_ISL_18800867
EPI_ISL_18822220
EPI_ISL_18822217
EPI_ISL_18815827
EPI_ISL_18822222
EPI_ISL_18822230
EPI_ISL_18822231
EPI_ISL_18832275
EPI_ISL_18854665
EPI_ISL_18839063

**Comment by aviczhl2** [comment]
35 now. It is not slow.

**Comment by FedeGueli** [comment]
ping @corneliusroemer this should be designated. again we see BA.2.86 re - gaining some fitness via recombination with FLip lineages , i think it is the third with this trend.

**Comment by JosetteSchoenma** [comment]
XDT

**Comment by Over-There-Is** [comment]
And G29778A is also inherited from that GK.1 branch.

**Comment by JosetteSchoenma** [comment]
> And G29778A is also inherited from that GK.1 branch.

I am not sure about that. Almost half of the samples do not have it. And I believe the matching GK.1's do not have it either, but I should check that further.
