### ISSUE TITLE
JN.1.4.3  (S:T572I)  with S:R346T (66-US)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2487]
Transferred from Branch 8 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1097 

<Details>
<Summary>
Original proposal
</Summary>
Defining mutations:
JN.1.4 > S:t572I (C23277T)
Query: C774T,C23277T, -T18453C,-C3177T,-C4327T,-G25445A,-T5389C,-C2980T

Samples: 28
 
<img width="382" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/87669813/3c442f52-112a-478e-b1b6-52f84cd70338">

Tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_403e1_f87880.json?c=userOrOld&label=id:node_6928638 
<img width="1166" alt="Screenshot 2024-02-04 alle 13 54 59" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/18212a40-2345-4af7-b382-80a548beda1a">
</Details>

Important:
This got a sub-lineage with S:R346T (even if it could be an independent one) :  
Query: C774T,G22599C, C23277T,-C2980T,C18894T 
Samples 6 (US-4 states)
EPI_ISL_18818630, EPI_ISL_18826826, EPI_ISL_18849701,
EPI_ISL_18859307, EPI_ISL_18866094, EPI_ISL_18867924,
Tree:
<img width="1139" alt="Screenshot 2024-02-07 alle 09 43 26" src="https://github.com/cov-lineages/pango-designation/assets/87669813/117b01d1-56f7-4a00-9f79-ad4a77cb56ef">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_59c9e_341240.json?label=id:node_6860926

**Comment by Fearuncle** [comment]
jn.1.4 + S:T572I + s:346T is now 9

**Comment by Fearuncle** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/944009b1-0f72-48a2-9894-80f823ca61b5)

**Comment by FedeGueli** [comment]
> jn.1.4 + S:T572I + s:346T is now 9

thank you

**Comment by corneliusroemer** [comment]
JN.1.4.3, I haven't designated the 346T yet, just the 572I

Let's wait a bit more with 346T until it's something like 25

**Comment by FedeGueli** [comment]
+5 Us (4 Ga, 1 FLA)

**Comment by aviczhl2** [comment]
30 now

**Comment by FedeGueli** [comment]
> 30 now

Thank you @aviczhl2 , @corneliusroemer this seems fast taking it with many caveats being concentrated in high sequencing areas:  https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?%2FAllSamples%2FPast3M%2Fvariants%3FnextcladePangoLineage=JN.1*&nextcladePangoLineage=JN.1*&nucMutations1=C774T%2CG22599C%2CC23277T%2CC18894T%2CC2980C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
36

**Comment by FedeGueli** [comment]
59 very fast.

**Comment by FedeGueli** [comment]
66 fast still US mainly but different states especially GA

**Comment by FedeGueli** [comment]
Designated KQ.1 via https://github.com/cov-lineages/pango-designation/commit/a528c797030e5fa63be113b1726ab0947dba92c1
