### ISSUE TITLE
Proposal for sublineage of AY.4.2 with S:1264L (mostly Scotland)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#249]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: AY.4.2
Earliest sequence: Scotland 2021-29,
Most recent sequence: Current
Countries circulating: Mostly UK (~2k seq) but also observed in a few EU countries plus US

Lineage deriving from AY.4.2 but with extra Spike mutation S:1264L. That mutation is interesting, because it seems to be arising independently within Delta a couple of times.

It's quite remarkable how quickly this lineage has grown to >5% in Scotland, in less than 10 weeks going from first occurrence to 2000 sequences. It's now more than 50% of all AY.4.2 in Scotland, while <10% in UK showing epidemiological significance.

<html><head></head><body>

Denmark | 1 | 2021-38 | 2021-38 |  
Germany | 1 | 2021-35 | 2021-35 |  
Ireland | 3 | 2021-37 | 2021-38 |  
Italy | 1 | 2021-35 | 2021-35 |  
Portugal | 2 | 2021-38 | 2021-39 |  
United Kingdom | 1941 | 2021-29 | 2021-40 |  
United States | 2 | 2021-33 | 2021-33

<br class="Apple-interchange-newline">

![image](https://user-images.githubusercontent.com/25161793/137026755-1b3f4997-76e3-4a37-964b-4a56eecdae6e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_11fa6_5f2c10.json?branchLabel=Spike%20mutations&c=gt-S_1264

![image](https://user-images.githubusercontent.com/25161793/137026789-ed7ba68c-5cd3-476c-8eb6-c9ac4a5280a0.png)

https://cov-spectrum.ethz.ch/explore/United%20Kingdom/AllSamples/Past6M/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22S%3A1264L%22%2C%22S%3A145H%22]%7D%2C%22matchPercentage%22%3A1%7D

Genomes
[S:145H-S:1264L.intersection.txt](https://github.com/cov-lineages/pango-designation/files/7333067/S.145H-S.1264L.intersection.txt)

Proposed lineage name
AY.4.2.1

**Comment by chrisruis** [comment]
Thanks @corneliusroemer This clade has steadily increased as a proportion of total AY.4.2 sequences in the UK and has been responsible for ~25% of UK AY.4.2 sequences over the past few weeks (comparing AY.4.2 in the UK at https://cov-spectrum.ethz.ch/explore/United%20Kingdom/AllSamples/AllTimes/variants?pangoLineage=AY.4.2 with AY.4.2+S:V1264L in the UK at https://cov-spectrum.ethz.ch/explore/United%20Kingdom/AllSamples/AllTimes/variants?aaMutations=S%3A1264L&pangoLineage=AY.4.2).

We've therefore designated this as AY.4.2.2 in [v1.2.103](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.103) to start on the branch with G25352C (S:V1264L)
