### ISSUE TITLE
JN.1.8 Plus S:R346T (34 sequences, 8 countries including 3 different African countries)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2495]
_Former branch 9 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089_

There is a sublineage of JN.1.8 with S:R346T, that likely will deserve a designation having been found already in 5 continents despite the small number of sequences including Africa.

Defining mutations: JN.1.8 > A12928G,> S:R346T (G22599C),
Query: A12928G, G22599C,C27476T
Samples : 27 
Countries: Australia, NZL, France, Canada, Singapore, US, Uk, Nigeria
IDs:EPI_ISL_18700854, EPI_ISL_18700885, EPI_ISL_18700900,
EPI_ISL_18728695, EPI_ISL_18757659, EPI_ISL_18779344,
EPI_ISL_18779965, EPI_ISL_18808493, EPI_ISL_18809293,
EPI_ISL_18842214, EPI_ISL_18850209, EPI_ISL_18859463,
EPI_ISL_18867202, EPI_ISL_18880191, EPI_ISL_18892580,
EPI_ISL_18907782, EPI_ISL_18910154, EPI_ISL_18910176,
EPI_ISL_18910247, EPI_ISL_18913511, EPI_ISL_18915627,
EPI_ISL_18916637, EPI_ISL_18916649, EPI_ISL_18916651,
EPI_ISL_18916656, EPI_ISL_18916660, EPI_ISL_18916666

Tree:
<img width="1150" alt="Screenshot 2024-02-21 alle 13 39 10" src="https://github.com/cov-lineages/pango-designation/assets/87669813/af445297-9392-4292-83ac-aca8cc8295f9">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_41bc1_5d8d80.json?label=id:node_6904022

**Comment by FedeGueli** [comment]
39

**Comment by FedeGueli** [comment]
34 sorry i ve edited a previous wrong issue update

**Comment by aviczhl2** [comment]
Designated JN.1.8.2

**Comment by FedeGueli** [comment]
via https://github.com/cov-lineages/pango-designation/commit/ce0782ace48769d2d5c5d502482ccd306cc5907f
