### ISSUE TITLE
GE.1.2 with S:R>S408N emerged in Kenya featuring the Ryan's complete deletion of Orf7ab/Orf8 (25 seqs) 30% of sequences in Kenya after Jan 16 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2496]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1340

There is a sibling branch of GE.1.2.1 that was widespread in Kenyan sequences since December defined by multiple AA changes, the most noteworthy is S:S408N in the RBD that is popping up in several lineages lately..
More interestingly it displays the identical large Orf7ab/Orf8 deletion that is featured by its sibling GE.1.2.1 and unrelated FW.1.1.1 and GW..5.1.1 first spotted and analyzed by @ryhisner 
Now this lineage , apparently reached a striking 8/20 samples collected in Kenya after January 16.
As for FY.4 it could Kenyan scientists are working onn this variant or it can just a geographical distribution of the last sequence influencing it. Still in my view better to designate it also cause there has been a couple of exportation to US meaning for sure it has a good prevalence in the area.
GE.1.2.1 is still the most competitive non BA.2.86 lineage as of today.

Defining mutations:
GE.1.2 > T2872C, Orf1b:A517V (C15017T), Orf1b:D1899E (C19164A), S:S408N (G22785A) 
Query: G22785A ,  C6026T, T13371C
Samples : 24 (Kenya 22, US 2)
First: 2023-11-27 Kenya
EPI_ISL_18788105, EPI_ISL_18788107, EPI_ISL_18788142-18788148,
EPI_ISL_18788165-18788167, EPI_ISL_18788178, EPI_ISL_18788220,
EPI_ISL_18837464, EPI_ISL_18880732, EPI_ISL_18918881-18918884,
EPI_ISL_18918891-18918893, EPI_ISL_18918901

  
Tree:
 https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_8b09_75da00.json?label=id:node_4152242
<img width="1148" alt="Screenshot 2024-02-22 alle 16 01 09" src="https://github.com/cov-lineages/pango-designation/assets/87669813/398bf756-d693-467a-a31a-8b7579d2bd30">
<img width="1169" alt="Screenshot 2024-02-22 alle 16 00 19" src="https://github.com/cov-lineages/pango-designation/assets/87669813/7e267716-e6ca-48e0-ac99-3342f80f2a21">

Looking at the tree it seems being split in two :one defined by further S:R246T mutation and the other defined by Orf10:I4V

**Comment by aviczhl2** [comment]
Designated GE.1.2.2

**Comment by FedeGueli** [comment]
One more very recent sample from England.

**Comment by FedeGueli** [comment]
Designated GE.1.2.2 via https://github.com/cov-lineages/pango-designation/commit/cb172ab49c31a1a12f774ddf00247e8c8e6985f3
