### ISSUE TITLE
XDQ+S:A475V(41 seqs, 6 countries, 17% South Korea)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2497]
https://github.com/sars-cov-2-variants/lineage-proposals/issues/1370
The S:A475V branch of XDQ is exploding.

XDQ+C22986T(S:A475V)

GISAID query: C28846T,C7420T,C22986T
No. of seqs: 37(Sweden 1 Australia 1 South Korea 19 Japan 16)

First: EPI_ISL_18795907, Sweden, 2023-12-16
Latest: EPI_ISL_18924543. South Korea. 2024-2-5

15/90=17% in South Korean seqs in 2024-2. 

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/xdq_a475v.json?label=id:node_6879602)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/f05e0abf-cc8c-4a1c-a507-4e6633346462)

**Comment by aviczhl2** [comment]
+1 China from Singapore

**Comment by FedeGueli** [comment]
+1 Jap

**Comment by FedeGueli** [comment]
+1 Australia Queensland

**Comment by FedeGueli** [comment]
Designated XDQ.1
