### ISSUE TITLE
JN.1+C21762T(S:A67V) (36 sequences, at least 7 countries)

### ISSUE THREAD

**Issue by yanjin1234** [cov-lineages/pango-designation#2498]
Sub-lineage of:JN.1

First: EPI_ISL_18819543, Japan, 2023-11-28
Latest: EPI_ISL_18944034,China, 2024-02-20

No. of seqs: 36( China 20  USA 8 Germany 4   Singapore 1   Japan 1 Poland 1  Oman 1 ）
Among the 20 sequences from China, 17 come from our laboratory. They were detected within a short timeframe. interesting fact is that S:A67V is a highly prevalent mutation in BA.1, located at the superantigen site of the S protein's N-terminal domain

IDs:EPI_ISL_18926250, 
EPI_ISL_18926252, 
EPI_ISL_18926251, 
EPI_ISL_18926254, 
EPI_ISL_18926253
EPI_ISL_18944034
GISAID query:T111C,C5512T,G2782T,C21762T,C18894T

<img width="1621" alt="截屏2024-03-01 19 30 21" src="https://github.com/cov-lineages/pango-designation/assets/131598281/40c76106-a10b-4d72-b8ce-71dfb9ca5fd0">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1aa02_1ec780.json?f_userOrOld=uploaded%20sample

**Comment by FedeGueli** [comment]
Hi @yanjin1234 this was proposed yesterday by @aviczhl2 in the pre proposal repository : https://github.com/sars-cov-2-variants/lineage-proposals/issues/1395 
If he agrees i suggest him to close that and to track the lineage together here . 
Thank you for proposing

**Comment by yanjin1234** [comment]
Among the 10 sequences that passed QC this week, 6 are JN.1+S:A67V. We will continue to track the prevalence of this variant strain locally.

**Comment by aviczhl2** [comment]
The proposed lineage shall be independent lineage with additional mutations of C5512T and G2782T as described in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1395?

Other ~40 seqs shall belong to other separate lineages I guess?

**Comment by FedeGueli** [comment]
@corneliusroemer this proposal embraces a various of lineage, the one emerging in Chonqqing,  where is the lab that put out this proposal is found with C5512T,G2782T,C21762T,C18894T and described by @aviczhl2 in secondary report issue # 1395

**Comment by yanjin1234** [comment]
@FedeGueli @corneliusroemer As an addition, the JN.1+S:A67V lineage, identified in Chongqing, is characterized by the following sites: T111C, C5512T, G2782T, C21762T, and C18894T.

**Comment by yanjin1234** [comment]
The number of sequences with this characteristic mutation in Chongqing has increased to 19. Gisaid ID will be provided later.
![微信图片_20240301144926](https://github.com/cov-lineages/pango-designation/assets/131598281/5e5135b5-f2e7-4def-a3bd-82891db63115)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3c2e6_1793d0.json?f_userOrOld=uploaded%20sample

**Comment by FedeGueli** [comment]
@corneliusroemer i suggest to designate this one.

**Comment by yanjin1234** [comment]
EPI_ISL ID： EPI_ISL_18944031- EPI_ISL_18944041

**Comment by aviczhl2** [comment]
> @corneliusroemer i suggest to designate this one.

I think the designation show follow
https://github.com/sars-cov-2-variants/lineage-proposals/issues/1395 as other branches here are separate branches getting S:A67V independently.

**Comment by yanjin1234** [comment]
@FedeGueli @corneliusroemer @aviczhl2 You've done a great job, but it is based on the sequences we specifically uploaded. It is recommended that the Pango committee grant naming rights to the laboratory that uploaded the data, in recognition of the hard work of the laboratory scientists. Thank you.

**Comment by yanjin1234** [comment]
+2 Yibin, another city 300 kilometers away from Chongqing.

**Comment by FedeGueli** [comment]
+2 Indonesia and Japan using the query : C5512T,G2782T,C21762T,C18894T  by @aviczhl2

**Comment by yanjin1234** [comment]
> +2 Indonesia and Japan using the query : C5512T,G2782T,C21762T,C18894T by @aviczhl2 (44 total)+2 印度尼西亚和日本使用查询 ： C5512T，G2782T，C21762T，C18894T by （44 总计）
> 
> cc @corneliusroemer this is going very well i would designate it as soon as possible.抄送：进展顺利，我会尽快指定它。

If the A67V lineage cannot have any sub-lineages, then should the sequence query include T111C?
![微信图片_20240304174016](https://github.com/cov-lineages/pango-designation/assets/131598281/c0ed4de7-b99f-4d49-a979-2ab946568ced)

**Comment by FedeGueli** [comment]
i suggest to start the designation from S:A67V not from T111C cause the sequences included seems really part of this lineage via nucleotides marker , not a big issue anyway cause the sequences not part of T111C seem quite older than the main branch
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2d411_5a5550.json?c=country&label=id:node_6911005

**Comment by FedeGueli** [comment]
45 with C5512T,G2782T,C21762T,C18894T today uploads from Japan, Thailandia and Indonesia

**Comment by FedeGueli** [comment]
52  including not T111C samples cc @corneliusroemer

**Comment by yanjin1234** [comment]
This week, there was an increase of 13

**Comment by yanjin1234** [comment]
![微信图片_20240308173747](https://github.com/cov-lineages/pango-designation/assets/131598281/5d6c331e-b333-49f7-9eac-8bf19440dd43)

**Comment by FedeGueli** [comment]
> ![微信图片_20240308173747](https://private-user-images.githubusercontent.com/131598281/311189269-5d6c331e-b333-49f7-9eac-8bf19440dd43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NDM2MjksIm5iZiI6MTcwOTk0MzMyOSwicGF0aCI6Ii8xMzE1OTgyODEvMzExMTg5MjY5LTVkNmMzMzFlLWIzMzMtNDlmNy05ZWFjLThiZjE5NDQwZGQ0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQwMDE1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTE0ODkwMGZjN2Y5Njc3YzQ3YzkzZTg3YWIxNjM0NWNjOGFjNGNhYjhkNmExNzIxZjMyYTAwOTYyYmFmZDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pfsx93TVr2ingePb-TP7EaPCMts9iytrUhhA2KSeSXM)

now it is 67 with C5512T,G2782T,C21762T,C18894T @corneliusroemer ping this is fast.

**Comment by aviczhl2** [comment]
There is an S:F456L sub-branch of this lineage.  Query : C21762T,C18894T,T22928C in France

**Comment by FedeGueli** [comment]
> There is an S:F456L sub-branch of this lineage. Query : C21762T,C18894T,T22928C in France

one to watch

**Comment by yanjin1234** [comment]
@FedeGueli   +10 All from China

**Comment by FedeGueli** [comment]
> @FedeGueli +10 All from China

thx!! i see 77 with my query most or all the new ones from Sichuan right?

**Comment by FedeGueli** [comment]
@corneliusroemer designation needed this one has prevalence and actually widespread in multiple states of China

**Comment by FedeGueli** [comment]
and as @aviczhl2 it likely recombined already with JN.1.18 to creat branch 51 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089

**Comment by yanjin1234** [comment]
> and as @aviczhl2 noted, it likely recombined already with JN.1.18 to create branch 51 of [sars-cov-2-variants/lineage-proposals#1089](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089)如前所述，它可能已经与 JN.1.18 重新组合以创建 sars-cov-2-variants/lineage-proposals#1089 的分支 51

This branch does not carry S:A67V

**Comment by aviczhl2** [comment]
I checked seqs with S:A67V from this branch. 72 of them have 111C, 5 of them have 111 missing coverage, none of them have 111T. 

So T111C is shared by all seqs of this branch. 

The correct trajectory shall be JN.1->G2782T->T111C->C5512T, S:A67V.

**Comment by FedeGueli** [comment]
> of

Thanks for the analysis .

**Comment by FedeGueli** [comment]
> > and as @aviczhl2 noted, it likely recombined already with JN.1.18 to create branch 51 of [sars-cov-2-variants/lineage-proposals#1089](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089)如前所述，它可能已经与 JN.1.18 重新组合以创建 [sars-cov-2-variants/lineage-proposals#1089](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089) 的分支 51
> 
> This branch does not carry S:A67V

yeah we thought it was a donor of the recombinant. But @aviczhl2 went further in the comments below.

**Comment by yanjin1234** [comment]
This week, the laboratory continued to detect an additional 11 cases.

**Comment by yanjin1234** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/131598281/988a6a8d-f74f-46e0-92d3-28450496f4e7)

This week, the laboratory continued to detect an additional 11 cases.

**Comment by Memorablea** [comment]
please designation

**Comment by FedeGueli** [comment]
93

**Comment by aviczhl2** [comment]
Designated JN.1.33

**Comment by FedeGueli** [comment]
Designated JN.1.33 via https://github.com/cov-lineages/pango-designation/commit/98da9b23d589330f4a12657b75707c76f976fbbb

**Comment by FedeGueli** [comment]
> 21762T,C18894T,T22928C in France

this query now catches an unrelated sample from Brazil. I suiggest to use C13694T, C24718T  ,T22928C to monitor it although the two samples appear to be quite old now so unlikely it is growing

**Comment by DailyCovidCases** [comment]
This branch is dead, please close this issue
