### ISSUE TITLE
KV.2 (JN.1.4.5 + S:T572I ) with S:F456L (5,Mississippi)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2500]
<Details>
<Summary>
Original KV.2 Proposal
</summary>
Former branch 18 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1097

Defining JN.1.4.5 [T18453C > Orf8:S103L (C28201T)]> Orf1a:P971L (C3177T), C11956T, S:T572I (C23277T)
Query: C28201T,C3177T, C11956T,
Samples: 201 
Countries: 6 mostly US, but now expoerted to China,India, Portugal
<Details>
<Summary>
Genomes
</Summary>
EPI_ISL_18594616, EPI_ISL_18715666, EPI_ISL_18715709,
EPI_ISL_18743056, EPI_ISL_18743391, EPI_ISL_18743414,
EPI_ISL_18743508, EPI_ISL_18743511, EPI_ISL_18743529,
EPI_ISL_18743718, EPI_ISL_18756315, EPI_ISL_18757279,
EPI_ISL_18776734, EPI_ISL_18779236, EPI_ISL_18779266,
EPI_ISL_18779698, EPI_ISL_18783863, EPI_ISL_18796384,
EPI_ISL_18796392, EPI_ISL_18797570, EPI_ISL_18797581,
EPI_ISL_18804974, EPI_ISL_18809261, EPI_ISL_18816361,
EPI_ISL_18816365, EPI_ISL_18816468, EPI_ISL_18816473,
EPI_ISL_18816530, EPI_ISL_18816539, EPI_ISL_18816543,
EPI_ISL_18816577, EPI_ISL_18816582-18816583, EPI_ISL_18816652,
EPI_ISL_18816730, EPI_ISL_18816769, EPI_ISL_18816771,
EPI_ISL_18816910, EPI_ISL_18817000, EPI_ISL_18817061,
EPI_ISL_18817065, EPI_ISL_18817076, EPI_ISL_18817090,
EPI_ISL_18817092, EPI_ISL_18817100, EPI_ISL_18824206,
EPI_ISL_18827118, EPI_ISL_18827142-18827143, EPI_ISL_18835904,
EPI_ISL_18836017, EPI_ISL_18836023, EPI_ISL_18846785,
EPI_ISL_18846962, EPI_ISL_18847665, EPI_ISL_18847711,
EPI_ISL_18848500, EPI_ISL_18848704, EPI_ISL_18848710,
EPI_ISL_18849520, EPI_ISL_18849522-18849523, EPI_ISL_18852363,
EPI_ISL_18859650, EPI_ISL_18864347, EPI_ISL_18869491,
EPI_ISL_18869513, EPI_ISL_18869516, EPI_ISL_18869524,
EPI_ISL_18869532, EPI_ISL_18869550, EPI_ISL_18869804,
EPI_ISL_18874035, EPI_ISL_18874038, EPI_ISL_18874242,
EPI_ISL_18874248, EPI_ISL_18874263, EPI_ISL_18874271,
EPI_ISL_18874314, EPI_ISL_18874334, EPI_ISL_18874339,
EPI_ISL_18874407, EPI_ISL_18874410, EPI_ISL_18874412,
EPI_ISL_18874419, EPI_ISL_18874456, EPI_ISL_18874515,
EPI_ISL_18874519, EPI_ISL_18874558, EPI_ISL_18874567,
EPI_ISL_18874588, EPI_ISL_18874591, EPI_ISL_18874658,
EPI_ISL_18874728, EPI_ISL_18874744, EPI_ISL_18874757,
EPI_ISL_18874771, EPI_ISL_18874833, EPI_ISL_18874966,
EPI_ISL_18874979, EPI_ISL_18880134, EPI_ISL_18882451,
EPI_ISL_18882949, EPI_ISL_18887092, EPI_ISL_18887270,
EPI_ISL_18887524, EPI_ISL_18887575, EPI_ISL_18892319,
EPI_ISL_18895049, EPI_ISL_18895338, EPI_ISL_18895462,
EPI_ISL_18899522, EPI_ISL_18902909, EPI_ISL_18911402,
EPI_ISL_18911973, EPI_ISL_18914459, EPI_ISL_18914722,
EPI_ISL_18915345, EPI_ISL_18916903, EPI_ISL_18917125,
EPI_ISL_18917145, EPI_ISL_18917164, EPI_ISL_18917611,
EPI_ISL_18917636, EPI_ISL_18917773, EPI_ISL_18917779,
EPI_ISL_18918021, EPI_ISL_18918033, EPI_ISL_18920044,
EPI_ISL_18920115, EPI_ISL_18920177, EPI_ISL_18920180,
EPI_ISL_18920195, EPI_ISL_18920209, EPI_ISL_18920410,
EPI_ISL_18921082, EPI_ISL_18921273, EPI_ISL_18922106,
EPI_ISL_18922425, EPI_ISL_18923193, EPI_ISL_18923211,
EPI_ISL_18923217, EPI_ISL_18923226, EPI_ISL_18923230,
EPI_ISL_18927428, EPI_ISL_18927432, EPI_ISL_18927437,
EPI_ISL_18927480, EPI_ISL_18927517, EPI_ISL_18927524,
EPI_ISL_18927534, EPI_ISL_18927540, EPI_ISL_18927554,
EPI_ISL_18927598, EPI_ISL_18927630, EPI_ISL_18927646,
EPI_ISL_18927648, EPI_ISL_18927696-18927697, EPI_ISL_18927700,
EPI_ISL_18927724, EPI_ISL_18927736, EPI_ISL_18927747,
EPI_ISL_18927768, EPI_ISL_18927778, EPI_ISL_18927780,
EPI_ISL_18927805, EPI_ISL_18927807, EPI_ISL_18927819-18927820,
EPI_ISL_18927830, EPI_ISL_18927865, EPI_ISL_18927877,
EPI_ISL_18927900, EPI_ISL_18927915, EPI_ISL_18927929,
EPI_ISL_18927962, EPI_ISL_18927986, EPI_ISL_18928020,
EPI_ISL_18928042, EPI_ISL_18928080, EPI_ISL_18928134,
EPI_ISL_18928138, EPI_ISL_18928154, EPI_ISL_18928173,
EPI_ISL_18928176, EPI_ISL_18928261, EPI_ISL_18928301,
EPI_ISL_18928323, EPI_ISL_18928339, EPI_ISL_18928632,
EPI_ISL_18928712-18928713, EPI_ISL_18928715, EPI_ISL_18930631,
EPI_ISL_18930703, EPI_ISL_18930749, EPI_ISL_18931261,
EPI_ISL_18931263, EPI_ISL_18931339, EPI_ISL_18931388,
</Details>
Tree:
<img width="1167" alt="Screenshot 2024-02-25 alle 08 34 42" src="https://github.com/cov-lineages/pango-designation/assets/87669813/88610ec2-f2d9-48f2-a7ce-ebd628444cf0">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5917c_aed620.json?f_userOrOld=uploaded%20sample&label=id:node_6964174

EDITED
</Details>

Just identified a branch of this proposed lineage with S:F456L
JN.1.4 >> T18453C > Orf8:S103L (C28201T)  Orf1a:P971L (C3177T)> C11956T, S:T572I (C23277T) >  C2005T > C1188T , 7981G, Orf1b:P2313T (C20404A), S:F456L (T22928C)
Query: C2005T ,C1188T , 7981G
Samples: 2

**Comment by FedeGueli** [comment]
250 total the 456L sublinegae doubled to 4 all from Mississippi

**Comment by FedeGueli** [comment]
387

**Comment by FedeGueli** [comment]
467 now, while 456L sublin. went to 5

**Comment by aviczhl2** [comment]
479 now @corneliusroemer

**Comment by aviczhl2** [comment]
479 now @corneliusroemer

**Comment by Memorablea** [comment]
@corneliusroemer

**Comment by aviczhl2** [comment]
Designated KV.2

**Comment by FedeGueli** [comment]
Designated KV.2 via https://github.com/cov-lineages/pango-designation/commit/4a1ca7397364139bb8132be42f1909c11baa3e27

**Comment by FedeGueli** [comment]
i think i can close this one
