### ISSUE TITLE
XBB.1.16/BA.2.86.1 recombinant, 19 samples from Japan

### ISSUE THREAD

**Issue by JosetteSchoenma** [cov-lineages/pango-designation#2502]
Description: XBB.1.16(https://github.com/cov-lineages/pango-designation/issues/2404)/BA.2.86.1 recombinant. 1 breaking point, Spike from BA.2.86.1
Private mutations: C12115T
C3177T, C3587T and C3944A from XBB.1.16, C26078T from BA.2.86.1
Breakpoint: between nucleotide 11957 and 12729
First sequence: 2023-10-11 from Japan/Kanagawa
Latest Sequence: 2024-02-01 from Japan/Tokyo
Countries circulating: Japan
GISAID query: C3944A,C12115T

Usher tree:
![image](https://github.com/cov-lineages/pango-designation/assets/94831035/d8ac86bb-7636-4fe9-83dd-6cbe34c0e2e9)

 See https://github.com/sars-cov-2-variants/lineage-proposals/issues/1084 for more info

**Comment by aviczhl2** [comment]
+1

**Comment by FedeGueli** [comment]
one only from February

**Comment by aviczhl2** [comment]
+3, 19 seqs now

**Comment by FedeGueli** [comment]
> C3944A,C12115T

now also present in March.

**Comment by JosetteSchoenma** [comment]
XDU
