### ISSUE TITLE
JN.1.4 plus S:T572I  ( 322 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2504]
Ex Branch 19 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1097

JN.1.4> T18453C > S:T572I (C23277T)
Query: C23277T,T18453C,C774T,-G3085T,-G3085T,-T1483C,-C4795T,-T9769C,-C401T,-C29311T,-T18471C,-C2232T,-C25465T,-C1288T,-C3177T,-G910A,-C1762A,-G7393A,-C10748A,-C6781T,-A14487T,-C28201T,-G2202T,-A13308G,-C15277T,-C23595T,-T18164C,-C6541T,-C19320T,-A9782G,-T7734C,-A161G,-G6169T,-T11092A,-C7600T,-C19763T,-G910A,-A977C,-G18816C,-C23595T,-C8668T,-T13294C,-G10151A,-C8668T,-C23595T,-C17745T,-C1762A,-G6183A,- C14649T,-C26192T,-C10078T,-A7319G,-T14091C,-G25112T,-C1426T,
Samples: 74 (? @corneliusroemer i ve tried to exclude most of the unrelated branches but still not sure of the real numbers of this lineage
While here you can find the sequences put together by Usher in the tree of this lineage
<img width="373" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/87669813/a22102a2-8c71-4083-8a59-c723fce37b97">
Countries:12
Tree:
<img width="1136" alt="Screenshot 2024-02-27 alle 15 14 56" src="https://github.com/cov-lineages/pango-designation/assets/87669813/207e060b-3ecc-42ec-8320-fa9399a2075c">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_2cdac_dec850.json?f_userOrOld=uploaded%20sample&label=id:node_6958375

**Comment by aviczhl2** [comment]
Designated JN.1.4.6

**Comment by FedeGueli** [comment]
Designated JN.1.4.6 via https://github.com/cov-lineages/pango-designation/commit/58f350c503054d0dbadb6b221c159d88d9dc65f5

**Comment by FedeGueli** [comment]
97 with query updated

**Comment by FedeGueli** [comment]
226

**Comment by FedeGueli** [comment]
308

**Comment by FedeGueli** [comment]
**too messy**
