### ISSUE TITLE
Proposal for a sublineage of AY.23 with N:K28R

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#251]
Description:
Sublineage of AY.23  
Earliest sequences : 14.05.21
Most resent : 04.10.21
Added non synonymous mutations (1st and 2nd steps) : N:K38R,NSP2:N168S
Added synonymous mutations (3rd and 4th steps) : C28312T,T21369C

Main countries : Indonesia, Germany, Switzerland

USHER analysis :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1c58f_6ef3f0.json

GISAID ref list (878 seq):
[GISAID ref list AY.23 sub lin.csv](https://github.com/cov-lineages/pango-designation/files/7339874/GISAID.ref.list.AY.23.sub.lin.csv)

Global sequences over time (main countries) :
![image](https://user-images.githubusercontent.com/80166370/137173440-d0755134-4385-4d1a-9123-33c9663df40f.png)

**Comment by shay671** [comment]
Hi @corneliusroemer , That is actually a very good question. 
If we look at this new sub lineage and compare it to it's mother varaiant ,AY.23, we see in the places he got that he is increasing it's share in comparison to the overall AY.23's. The data are small of course but the fact it consistent in 3 places which have some geographic distance and difference from my point of view is worth mentioning :

![image](https://user-images.githubusercontent.com/80166370/137187430-19fc23ea-f7c8-463b-8aad-4e49511f9f10.png)

**Comment by chrisruis** [comment]
Thanks @shay671 It looks like this clade has declined with very few recent sequences so we won't designate this for now
