### ISSUE TITLE
KP.1.1 (JN.1.11.1 + S:456L,1086R, S:R346T) with S:K182N (8) in multiple countries

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2510]
S:R346T is emerging mutliple times on JN.1.11.1 backbone and it seems fast hence i will propose a few lineages with it even if they are still very small.

**Credit : @aviczhl2 is the one who spotted this then it was tracked then in the multiple lineages issue for 346X as Branch 46 : https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089**

Defining mutations
KP.1.1 (KP.1 > S:R346T) then > Orf1b:L2213F (C20104T), S:K182N (A22108C)
<Details>
<Summary>
Query for KP.1.1
</Summary>
**Query for the whole branch**: A24819G,C7113T,G22599C
Samples: 9
Countries: Turkey, Argentina, New Zealand,India,UK, Singapore
IDs:EPI_ISL_18914549, EPI_ISL_18914875, EPI_ISL_18931358,
EPI_ISL_18937644, EPI_ISL_18949256
</Details>

**Query for the 182N branch**: C20104T,A22108C, T22928C 
Samples 4 (3 patients)
Countries: India, New Zealand Singapore
IDs:EPI_ISL_18923611, EPI_ISL_18945726, EPI_ISL_18945946,
EPI_ISL_18949264

Tree: Note that is splitted by an artifact:
<img width="1170" alt="Screenshot 2024-03-04 alle 11 57 01" src="https://github.com/cov-lineages/pango-designation/assets/87669813/d886a43c-0f91-4dbf-8335-d55fcb9d81ce">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_233f_5a1ac0.json?c=gt-S_346,1086&gmax=25384&gmin=21563&label=id:node_6920719

**Comment by aviczhl2** [comment]
@AngieHinrichs  it seems that there is an usher issue on S:483 for JN.1.11.1. Usher places some have 483G and some have 483V, however actually they shall have S:483-.

**Comment by FedeGueli** [comment]
+1 Spain

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs it seems that there is an usher issue on S:483 for JN.1.11.1. Usher places some have 483G and some have 483V, however actually they shall have S:483-.

Thanks @aviczhl2.  Do you know the nucleotide coordinates of the deletion?  (Or at least if only S:483 is deleted, or other nearby bases as well?)

**Comment by aviczhl2** [comment]
> > @AngieHinrichs it seems that there is an usher issue on S:483 for JN.1.11.1. Usher places some have 483G and some have 483V, however actually they shall have S:483-.
> 
> Thanks @aviczhl2. Do you know the nucleotide coordinates of the deletion? (Or at least if only S:483 is deleted, or other nearby bases as well?)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/c1a177c0-73a5-40c2-9d89-08fb529892b2)

I picked EPI_ISL_18939081 from the KP.1.1-483V branch, EPI_ISL_18937644 from the KP.1.1-483G branch, and EPI_ISL_18700192 as JN.1 reference. 

Nextclade shows they are the same around S:483, all have S:483-

**Comment by aviczhl2** [comment]
Designated KP.1.1

**Comment by FedeGueli** [comment]
S:R346T designated KP.1.1 via https://github.com/cov-lineages/pango-designation/commit/a29effeda0cc9cfe0d1f858975988972387d54d7 i keep this open to track the 182N branch

**Comment by AngieHinrichs** [comment]
> I picked EPI_ISL_18939081 from the KP.1.1-483V branch, EPI_ISL_18937644 from the KP.1.1-483G branch, and EPI_ISL_18700192 as JN.1 reference.
> 
> Nextclade shows they are the same around S:483, all have S:483- (using BA.2.86 reference)

OK, so it is a 3-nucleotide deletion 23009-23011 and it has unambiguous placement (alignment tools can't slide it left/right).  Thanks.  I will mask those positions in JN.1.

**Comment by aviczhl2** [comment]
> > I picked EPI_ISL_18939081 from the KP.1.1-483V branch, EPI_ISL_18937644 from the KP.1.1-483G branch, and EPI_ISL_18700192 as JN.1 reference.
> > Nextclade shows they are the same around S:483, all have S:483- (using BA.2.86 reference)
> 
> OK, so it is a 3-nucleotide deletion 23009-23011 and it has unambiguous placement (alignment tools can't slide it left/right). Thanks. I will mask those positions in JN.1.

It seems that there's some alignment issues on usher and usher still mess them up on 23008A/T despite no seqs really have that mutation. 

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/0ceb253b-9127-42ba-8f80-e84c29e7fdf5)

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs It seems that there's some alignment issues on usher and usher still mess them up on 23008A/T despite no seqs really have that mutation.

Ah, thanks.  I see now that when aligning to the Wuhan/Hu-1 reference (NC_045512.2) that is used for the whole tree (and provides a consistent coordinate system for nucleotides and amino acids across the pandemic to date), instead of to a more local reference as in nextclade, the placement of the gap can be different, and some sequences have an extra substitution G23004A that changes the gap placement even more and leads to the false 23008T.  One of the sequences that changes 23008 back does not show any deletion (it appears to be filling in reference sequence).

I will mask 23008 too.  Unfortunately the G23004A won't be shown, because aligning to the original reference causes the gap for sequences with that mutation to be placed at 23004-23006 (with a substitution later at 23008) instead of 23009-23011.

For the record here are alignments of several sequences from that branch that I looked at to come to the above conclusions.
```
22222222222222222222
33333333333333333333
00000000000000000000
00000000011111111111
12345678901234567890
GTAATGGTGTTGAAGGTTTT ref
    |      |     ||
gtaaagg---taaaggtcct mafft EPI_ISL_18718993
gtaaagg---taaaggtcct mafft EPI_ISL_18882483
gtaaaggtgttgaaggtcct mafft EPI_ISL_18932335

gta---gagntaaaggtcct mafft EPI_ISL_18860046
       |   |     || 
GTAATGGTGTTGAAGGTTTT ref
```
If a more local reference were used, then I think the A23004G and gap could be placed correctly:
```
GTAATGGTGTTGAAGGTTTT ref
    |      |     ||
gtaaagg---taaaggtcct mafft EPI_ISL_18882483
   |             
gtagagn---taaaggtcct mafft EPI_ISL_18860046 if aligned to local (EPI_ISL_18882483) instead of ref
                                            -- but aligning to ref, mafft put the del first and
                                               subst later.
```

**Comment by FedeGueli** [comment]
likely not fast.

**Comment by FedeGueli** [comment]
> likely not fast (the 182N sublineage i mean)

+1 Singapore today

**Comment by HynnSpylor** [comment]
K182N branch +1 (England)

**Comment by FedeGueli** [comment]
8 , new ones are a doubled sample from India caught by GBW

**Comment by aviczhl2** [comment]
Designated KP.1.1.1
