### ISSUE TITLE
JN.1.16 (456L) got S:R346T (35 Samples , 15 countries)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2511]
Another combo 456L-346T on Jn.1 Backbone is growing it was tracked as Branch 41 in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089

Defining: JN.1.16(S:F456L) > S:R346T (G22599C)
Query:   ,T22928C, T3565C, G22599C, T27810C,-C835T,-T26066C,-C13620T,-A405G,-C1938T,-G25290T,-C26894T,-G24872T ,-C1762A,-C774T, -A18093G ,-T1871G,-C11747T,-G1156T,-G21255T,-T16342C
Samples: 22 ( the above query manage to find 24 but two are from unrelated dead lineages: one Netherlands and one Ukraine-Env that i failed to exclude)
EPI_ISL_18860864, EPI_ISL_18882963, EPI_ISL_18888321,
EPI_ISL_18909091, EPI_ISL_18916650, EPI_ISL_18916652,
EPI_ISL_18916659, EPI_ISL_18931021, EPI_ISL_18931348,
EPI_ISL_18931393, EPI_ISL_18931429, EPI_ISL_18932646,
EPI_ISL_18937081, EPI_ISL_18937393, EPI_ISL_18937515,
EPI_ISL_18938829, EPI_ISL_18938846, EPI_ISL_18941397,
EPI_ISL_18945718, EPI_ISL_18945932, EPI_ISL_18949269,
EPI_ISL_18949473

Tree:
<img width="1164" alt="Screenshot 2024-03-05 alle 10 20 46" src="https://github.com/cov-lineages/pango-designation/assets/87669813/67906fd9-f53e-49b3-b517-dd7dde02b8b1">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5c93a_6e19c0.json?c=gt-S_346&label=id:node_6982680

Countries:
<img width="284" alt="Screenshot 2024-03-05 alle 10 21 18" src="https://github.com/cov-lineages/pango-designation/assets/87669813/e5a67a53-b721-4f67-9c9f-8a33e05fe93b">

**Comment by FedeGueli** [comment]
> Or JN.1.18+S:F456L.

oh damn would you mean i m tracking that two times?

**Comment by FedeGueli** [comment]
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1*&nucMutations1=T22928C%2CT3565C%2CG22599C%2CT27810C%2CC13620C%2CA405A%2CC1938C%2CG25290G%2CC26894C%2CG24872G%2CC1762C%2CC774C%2CA18093A&analysisMode=CompareToBaseline& anyway it seems fast

**Comment by aviczhl2** [comment]
> > Or JN.1.18+S:F456L.
> 
> oh damn would you mean i m tracking that two times? checked not. yeas could be JN.1.18 too.

I mean the order may change and this branch may one day becomes JN.1.18+F456L.  Actually this is not distinguishable.

**Comment by corneliusroemer** [comment]
Yeah that's why I'm hesitant with designation - both names are equally appropriate. Have to make a choice at some point.

**Comment by FedeGueli** [comment]
QUERY UPDATED STILL NOT PERFECT

**Comment by FedeGueli** [comment]
Query updated now 34 samples from 15 countries (many found in GBW)

**Comment by aviczhl2** [comment]
Is there a way to extract GBW lineage prevalence by countries? )

**Comment by FedeGueli** [comment]
> Is there a way to extract GBW lineage prevalence and growth rate by countries?

Only manually you can try proposing this in covspectrum github as ENHancing issue

**Comment by aviczhl2** [comment]
> Only manually you can try proposing this in covspectrum github as ENHancing issue

Yeah the origin countries are also not on usher tree.

**Comment by FedeGueli** [comment]
35 query updated

**Comment by aviczhl2** [comment]
Designated JN.1.16.1

**Comment by FedeGueli** [comment]
Designated Jn.1.16.1 via https://github.com/cov-lineages/pango-designation/commit/b316ca11cb343d853ae0c2d4e76ca6a4157e4f3b
