### ISSUE TITLE
JN.1.28 + ORF1a:P1640L (= PLPro_P77L), S:T572I (113 seq. in 10 countries)

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2513]
transferred from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/1244
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/d10de1ff-30c9-4d1e-963c-0990c3bef6ca)
gisaid query: C19545T, C24370T ,C5184T,C23277T

**Comment by FedeGueli** [comment]
with a subbranch with 456L

**Comment by FedeGueli** [comment]
167 now with 11 sequences with 456L ,
this lineage represents 22/151 from Australia in March but better to restrict to SA where it is 14/94 . ping @corneliusroemer

**Comment by aviczhl2** [comment]
Designated KW.1

**Comment by FedeGueli** [comment]
the KW.1 branch with 456L is now at 15 ping @corneliusroemer

**Comment by FedeGueli** [comment]
also the 456L got designated KW.1.1 @fearuncle please close this one.
