### ISSUE TITLE
 KU.2 (JN.1.30.1 + S:F456L) FLiRT sublineage got S:G213E and Orf1a:P2739L(19) in Uk, France, NZL

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2514]
Formerly known as branch 28 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089

JN.1.30.1 designated =
>Branch 28: JN.1.30( G21255T) > T7789C > S:R346T (G22599C)
Query:G21255T , G22599C,T3565C,G11727A
Samples : 26 India 

KU.2 designated=
>With further S:F456L branch following:
JN.1.30 (G21255T) > T7789C > S:R346T (G22599C) > S:F456L (T22928C)
Query: G22599C,T22928C,G21255T,T3565C
Samples : 4 Uk 

KU.2 with further S:G213E **NOW PROPOSED**: 
KU.2>Orf1a:P2739L (C8481T), S:G213E (G22200A),C22432T
Query: C8481T, C22432T,T22928C
Samples: 13 Uk
EPI_ISL_18969314, EPI_ISL_18969579, EPI_ISL_18969597,
EPI_ISL_18987610, EPI_ISL_18987614, EPI_ISL_18987693,
EPI_ISL_18987696, EPI_ISL_18987703, EPI_ISL_19002136,
EPI_ISL_19002141, EPI_ISL_19002143, EPI_ISL_19006296,
EPI_ISL_19006611

Tree:https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_b36d_f0f8b0.json?c=gt-nuc_7789&gmax=8789&gmin=6789&label=id:node_6907783
<img width="1150" alt="Screenshot 2024-03-11 alle 15 29 04" src="https://github.com/cov-lineages/pango-designation/assets/87669813/c6d721b7-5893-4979-9ae3-7caf2bec639c">
<img width="1173" alt="Screenshot 2024-03-11 alle 15 29 30" src="https://github.com/cov-lineages/pango-designation/assets/87669813/b2ca70bf-b81f-4333-84bf-e183134483d8">
<img width="1166" alt="Screenshot 2024-03-11 alle 15 29 55" src="https://github.com/cov-lineages/pango-designation/assets/87669813/5213dd8c-f32a-439c-9a61-45c8f001cae1">

<Details>
<Summary>
Original proposal
</Summary>
Samples: 
<img width="370" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/87669813/f94bd119-04d7-44d1-ac16-809385b63abb">

Usher finds more sequences than Gisaid cause many samples have T7789C defining as missing nucleotide, 
T7789C is needed in the query cause there is a smaller branch bottom with G21255T > > S:R346T (G22599C)
Manually checking it on Nextclade i found just three samples that has not T7789C and has no missing nuc in that position or very close to it , so to me likely it is there in the very most of them ( Query including sequences placed in the other branch by Usher:
 G21255T , T3565C, G22599C 

<img width="1173" alt="Screenshot 2024-03-11 alle 15 41 29" src="https://github.com/cov-lineages/pango-designation/assets/87669813/447b0fcd-2eec-4a7b-b82b-c69ec240c67b">
<img width="360" alt="Screenshot 2024-03-11 alle 15 44 13" src="https://github.com/cov-lineages/pango-designation/assets/87669813/824f81e1-a31e-4409-9cf5-5866aa27474b">
</Details>

**Comment by aviczhl2** [comment]
S:G213E is appeared together with S:R346T in XDK.1

**Comment by FedeGueli** [comment]
32 for 346T and 6 for 456L

**Comment by FedeGueli** [comment]
S:R346T went to 35 with three samples from Australia ( 2 from NSW one from SA)
The FLirt sublinegae up to 7 with one of the two samples coming from NSW being FLiRT and havig S:W64L too.
S:W64L was previously defining mutation of BA.2.14 and BA.5.2.14 indicating some beneficial effect of it.

**Comment by FedeGueli** [comment]
Big upload from Uk

**Comment by FedeGueli** [comment]
Now the total is 50 i ve updated the qeury with G21255T , G22599C,T3565C,G11727A ,
it catches also a flip flop branch that belongs to this :
<img width="1152" alt="Screenshot 2024-03-18 alle 13 46 01" src="https://github.com/cov-lineages/pango-designation/assets/87669813/90cbda35-1fd2-43b3-a886-4f60f1242581">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_540db_836390.json?label=id:node_6911800 Ping @corneliusroemer i suggest the designation of the three levels

**Comment by aviczhl2** [comment]
Designated JN.1.30.1

**Comment by FedeGueli** [comment]
JN.1.30.1 via https://github.com/cov-lineages/pango-designation/commit/e03042f9c2bacc2d7f5bffce3194fd29ef2420b5

**Comment by aviczhl2** [comment]
19 for S:F456L and 11 for S:G213E now.

**Comment by FedeGueli** [comment]
> 19 for S:F456L and 11 for S:G213E now.

Thx! @corneliusroemer  i would designate them.

**Comment by FedeGueli** [comment]
the JN.1.30.1 branch with S:F456L designated KU.2 via https://github.com/cov-lineages/pango-designation/commit/1cda06ac97854e9a8e33c4340d91c599921f8490
Leaving this open to track the S:G213E branch

**Comment by FedeGueli** [comment]
+2

**Comment by FedeGueli** [comment]
17 for the G213E branch

**Comment by FedeGueli** [comment]
the sublineage is stale

**Comment by FedeGueli** [comment]
Designated KU.2.2 via https://github.com/cov-lineages/pango-designation/commit/699fb71616e45ddde4f74e0af21644fda0c4ef24
