### ISSUE TITLE
JN.1*+S:Q677H and sublineage with S:S680F (transferred from issue 1326)

### ISSUE THREAD

**Issue by krosa1910** [cov-lineages/pango-designation#2516]
JN.1*> A29086T > G23593T(S:Q677H)
Query:G23593T, A29086T,T3565C
Samples: 122( 7 Aus, 6 Japan, 3 Scotland, 1 Shanghai-China (likely imported), 1 SIngapore, 103 South Korea, 1 US)
Earliest: EPI_ISL_18598041 South Korea 2023-11-10
Latest: EPI_ISL_18967096 South Korea 2024-02-27

A sublineage has further acquired S:S680F in the FCS
Search: C23601T,T15756A,C18894T,G23593T,
Mutations Added: A29086T (a relatively large branch of JN.1*, nor sure if it is mentioned or not)->G23593T(S:Q677H) ,C23601T (S:S680F)
Samples: 29
First Sequence: EPI_ISL_18688878 Scotland 2023-11-30
Latest Sequence: EPI_ISL_18967096 South Korea 2024-02-27

Usher:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1b79d_1536b0.json?f_userOrOld=uploaded%20sample&label=id:node_2333509

<img width="994" alt="Screenshot 2024-03-13 at 3 21 32 PM" src="https://github.com/cov-lineages/pango-designation/assets/131021067/d4b82f5b-609d-4e85-aaf1-ba4fa1354bbd">

Many of the sequences are actually trash as they contain too many reversions ( I hate South Korea for its trash sequences), but showing up in three countries is good enough for me, and if it is not completely an artefect, it could resemble the trend @LongDesertTrain have observed that multiple close to FCS mutations are now rising among JN.1*

**Comment by aviczhl2** [comment]
Designated JN.1.36
