### ISSUE TITLE
Proposal for AY.35 to be broadened to S:K77T + 8 other mutations, AY.35 -> AY.35.1

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#252]
New lineage/Redesignation proposal
by @CorneliusRoemer

> Note: I came across this lineage and wanted to designate, only to find shortly before submitting, that a sub-lineage of this lineage is already designated as AY.35 through #217.
> 
> I think it would be good to broaden AY.35 due to the mutational distinctness of the parent clade. If it was felt necessary to keep what was designated as AY.35 as its own lineage, it should be placed under the new AY.35 as AY.35.1
> 

Description
Sub-lineage of: B.1.617.2
Earliest sequence: India 2021-05
Most recent sequence: Current, US/UK 2021-40
Countries circulating: India (max 5%), but also with significant percentage in Turkey (max 6%), US, Canada, Netherlands (1-2%)
Total sequences: ~10k

This is a very early distinct Delta lineage, it split early from the main Delta branches that lead to Nextstrain 21I (S:222V) and 21J (e.g. N:215C) (they have ORf1ab:5036S, which this proposed lineage doesn't have). It acquired around 10 mutations on its own, among others: S:K77T.

While this lineage isn't by itself associated with just one country, it is very interesting because it is so different from the other Delta lineages. And it did reach a fair share in the US (~3%) but not in other countries.

Country | Total Variant Sequences | First seq. found at | Last seq. found at |  
-- | -- | -- | -- | --
Argentina | 2 | 2021-16 | 2021-29 |  
Australia | 17 | 2021-11 | 2021-18 |  
Belgium | 40 | 2021-16 | 2021-35 |  
Bulgaria | 1 | 2021-31 | 2021-31 |  
Canada | 295 | 2021-14 | 2021-33 |  
Chile | 5 | 2021-26 | 2021-34 |  
Colombia | 1 | 2021-33 | 2021-33 |  
Croatia | 1 | 2021-30 | 2021-30 |  
Czechia | 10 | 2021-31 | 2021-36 |  
Denmark | 70 | 2021-16 | 2021-37 |  
Estonia | 7 | 2021-31 | 2021-34 |  
Finland | 7 | 2021-28 | 2021-31 |  
France | 26 | 2021-16 | 2021-36 |  
Germany | 184 | 2021-12 | 2021-39 |  
Guatemala | 1 | 2021-27 | 2021-27 |  
Hong Kong | 2 | 2021-12 | 2021-35 |  
Iceland | 4 | 2021-31 | 2021-32 |  
India | 852 | 2021-05 | 2021-36 |  
Indonesia | 2 | 2021-17 | 2021-31 |  
Iran | 1 | 2021-17 | 2021-17 |  
Ireland | 6 | 2021-35 | 2021-39 |  
Israel | 5 | 2021-18 | 2021-31 |  
Italy | 83 | 2021-16 | 2021-34 |  
Japan | 78 | 2021-17 | 2021-32 |  
Luxembourg | 2 | 2021-17 | 2021-26 |  
Malaysia | 4 | 2021-25 | 2021-35 |  
Mexico | 25 | 2021-26 | 2021-38 |  
Netherlands | 160 | 2021-15 | 2021-38 |  
Nigeria | 1 | 2021-19 | 2021-19 |  
Norway | 15 | 2021-18 | 2021-35 |  
Oman | 8 | 2021-16 | 2021-25 |  
Pakistan | 4 | 2021-32 | 2021-34 |  
Poland | 7 | 2021-22 | 2021-38 |  
Portugal | 83 | 2021-18 | 2021-39 |  
Qatar | 2 | 2021-16 | 2021-18 |  
Romania | 1 | 2021-36 | 2021-36 |  
Russia | 3 | 2021-24 | 2021-25 |  
Rwanda | 50 | 2021-24 | 2021-34 |  
Singapore | 23 | 2021-15 | 2021-21 |  
Slovakia | 1 | 2021-28 | 2021-28 |  
South Africa | 6 | 2021-18 | 2021-18 |  
South Korea | 1 | 2021-19 | 2021-19 |  
Spain | 4 | 2021-16 | 2021-25 |  
Sweden | 58 | 2021-21 | 2021-35 |  
Switzerland | 18 | 2021-17 | 2021-35 |  
Turkey | 409 | 2021-18 | 2021-39 |  
United Kingdom | 382 | 2021-14 | 2021-40 |  
United States | 8428 | 2021-11 | 2021-40 |  
Vietnam | 2 | 2021-16 | 2021-18

Red: what I propose as new AY.35 (currently B.1.617.2 apart from the current AY.35 which is light green at the top)
Green: the current AY.35, what I would designate as AY.35.1
![image](https://user-images.githubusercontent.com/25161793/137484678-b4f01ff0-8477-4894-a193-445e83b7d73c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_19884_96d280.json?branchLabel=Spike%20mutations&c=gt-nuc_15451&label=nuc%20mutations:G210T,C21618G,T22917G,C23604G,C25469T,T27638C,G28881T,G29402T

Genomes (~10k)
[ORF1a:309L-S:77T.intersection.txt](https://github.com/cov-lineages/pango-designation/files/7353277/ORF1a.309L-S.77T.intersection.txt)

See covSPECTRUM for country/frequency overview
![image](https://user-images.githubusercontent.com/25161793/137485112-e2eff527-fc6b-4875-b1e3-fe3709a89f0f.png)
![image](https://user-images.githubusercontent.com/25161793/137485114-6de2d921-8268-43c5-a4ea-e903daa23460.png)

https://cov-spectrum.ethz.ch/explore/United%20States/AllSamples/Y2021/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22S%3A77T%22%2C%22ORF1a%3A309L%22]%7D%2C%22matchPercentage%22%3A1%7D

**Comment by corneliusroemer** [comment]
There's a paper on early structure of Delta and my proposal aligns with what Stern, @shay671 et al call Delta E in their paper: https://www.medrxiv.org/content/10.1101/2021.08.05.21261642v1.full-text

![image](https://user-images.githubusercontent.com/25161793/137591118-e1fea10c-84dd-4c2c-baa9-98c6931dc475.png)

**Comment by chrisruis** [comment]
Thanks @corneliusroemer It looks like this clade has declined and isn't associated with many recent sequences, both within the USA and more broadly so we haven't designated this clade for now
