### ISSUE TITLE
JN.1.24.1 (346T)  > FLiRT  with S:F456L (72 seqs) likely emerged in Texas  with further S:A288T in Ireland (19)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2520]
Originally tracked in Branch 37 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089

JN.1.24.1 [ S:C1243F (G25290T)] > S:R346T (G22599C)] > S:F456L (T22928C)

Query for the S:R346T branch  : **G22599C, G25290T, A6183G**
Samples: 22 
Countries:  Us (mainly Texas), Canada, Sweden
IDs: EPI_ISL_18811311, EPI_ISL_18816744, EPI_ISL_18816982,
EPI_ISL_18817077, EPI_ISL_18817110, EPI_ISL_18874220,
EPI_ISL_18874505, EPI_ISL_18874870, EPI_ISL_18920907,
EPI_ISL_18928072, EPI_ISL_18947689, EPI_ISL_18981402

Query for FLiRT Combo S:R346T + S:F456L  :**G22599C, G25290T, A6183G,T22928C** or **G22599C, T22928C, G25290T,T3565C** 
Samples: 10 
Country : US (All Texas), Canada
EPI_ISL_18874396, EPI_ISL_18933600, EPI_ISL_18980900,
EPI_ISL_18980941, EPI_ISL_18980948, EPI_ISL_18980957,
EPI_ISL_18981020, EPI_ISL_18981101, EPI_ISL_18981255,
EPI_ISL_18981378

Query for Irish FLiRT branch with S:A288T :**C20178T,A27489G,G22424A**
JN.1.24.1 [ S:C1243F (G25290T)] > S:R346T (G22599C)] > S:F456L (T22928C) >C20178T>A27489G> S:A288T (G22424A)
 
Samples:14 
 

Tree as of May 2:
<img width="1157" alt="Screenshot 2024-05-02 alle 20 09 46" src="https://github.com/cov-lineages/pango-designation/assets/87669813/d6d4a665-499b-4f5c-9701-f9e9c8b18ef5">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_4a23b_3d3430.json?label=id:node_6937346
 

Tree for the S:A288T branch
<img width="1179" alt="Screenshot 2024-05-02 alle 20 05 45" src="https://github.com/cov-lineages/pango-designation/assets/87669813/24554e18-b51f-498d-98b0-b22e072c90fb">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_4a23b_3d3430.json?label=id:node_6937346

**Comment by krosa1910** [comment]
It was lineage 9 of my issue 1421, and just two days ago it was a doublet there. I updated the issue to include an usher tree for it regularly but did not pay attention to lineage updates or change on weekday updates so I missed it. Anyway this would be a good FLirt+ extra S mutation example and let's see if it is comparable with other FLirts.

**Comment by FedeGueli** [comment]
this is now 25 , 12 with FLiRT . last came from Israel so internationally spread now.

@corneliusroemer i suggest a designation of this one.

**Comment by FedeGueli** [comment]
the S:R346T branch designated JN.1.24.1 via https://github.com/cov-lineages/pango-designation/commit/2a82248247436c1b8454e7b0cc703045675be1fa

**Comment by FedeGueli** [comment]
+2 Minnesota , Ireland

**Comment by FedeGueli** [comment]
+1 Ontario

**Comment by FedeGueli** [comment]
+1 Texas

**Comment by FedeGueli** [comment]
+2 Ireland and Wisconsin

**Comment by FedeGueli** [comment]
30 now with a big upload from Texas yesterday

**Comment by FedeGueli** [comment]
Big upload today from Ireland in the area of Dublin all carrying the additional S:A288T mutation
JN.1.24.1 [ S:C1243F (G25290T)] > S:R346T (G22599C)] > S:F456L (T22928C) >C20178T>A27489G> S:A288T (G22424A)
Query:C20178T,A27489G,G22424A
Samples:14 
<img width="1179" alt="Screenshot 2024-05-02 alle 20 05 45" src="https://github.com/cov-lineages/pango-designation/assets/87669813/24554e18-b51f-498d-98b0-b22e072c90fb">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_4a23b_3d3430.json?label=id:node_6937346

**Comment by FedeGueli** [comment]
56 now (FLiRT)

**Comment by FedeGueli** [comment]
57 Hawaii

**Comment by FedeGueli** [comment]
79

**Comment by FedeGueli** [comment]
dying off closing this

**Comment by FedeGueli** [comment]
83 still around in Texas not worth reopening, interestingly one from NZL has DeFLIRT

**Comment by aviczhl2** [comment]
4/10 in the most recent batch of Guadeloupe.

**Comment by FedeGueli** [comment]
> 4/10 in the most recent batch of Guadeloupe.

Rearranged the proposal with a new query and reopened the issue thank you for spotting!

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_4fc2_a93810.json?f_userOrOld=uploaded%20sample)
![Screenshot (185)](https://github.com/user-attachments/assets/58f702ae-a846-4538-8777-b6586b20b9de)
