### ISSUE TITLE
Another JN.1.11.1 lineage with FLiRT (456L 346T) 44 seqs , 6 countries with a branch with S:W258R (6)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2521]
This was previously tracked as Branch 53 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089

JN.1.11.1 > C6070T > C19884T > S:R346T (G22599C)
Query: C6070T,G22599C,C7113T,G24872T, C19884T
Samples: 7
Countries: Australia , Canada, US (Texas), India (GBW)
IDs:EPI_ISL_18912216, EPI_ISL_18937582, EPI_ISL_18937584,
EPI_ISL_18960842, EPI_ISL_18965320, EPI_ISL_18972869,
EPI_ISL_18980922

Tree as of April 8:
 
<img width="1171" alt="Screenshot 2024-04-08 alle 14 36 23" src="https://github.com/cov-lineages/pango-designation/assets/87669813/73c7dc62-e461-452a-9765-53a544fdde9e">
<img width="1143" alt="Screenshot 2024-04-08 alle 14 36 40" src="https://github.com/cov-lineages/pango-designation/assets/87669813/238e06e5-b10c-45b7-8244-258f83eeef19">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_139f2_3e3b50.json?label=id:node_6962173

There is further branch with S:W258R (T22334A) spotted by @aviczhl2 
Query: T22334A,G24872T,T3565C Samples: 4
<img width="1140" alt="Screenshot 2024-04-08 alle 14 37 05" src="https://github.com/cov-lineages/pango-designation/assets/87669813/6934ab09-1122-4f2c-ae52-6211cbc6219d">

**Comment by aviczhl2** [comment]
Why not proposing the K187R branch

**Comment by FedeGueli** [comment]
> Why not proposing the K187R branch

i m waiting one more sequence

**Comment by FedeGueli** [comment]
+1 India (GBW)

**Comment by FedeGueli** [comment]
11 sequences now

**Comment by FedeGueli** [comment]
15 seqs new country Vietnam

**Comment by FedeGueli** [comment]
34

**Comment by aviczhl2** [comment]
There is a S:W258R sub-branc of this.

**Comment by FedeGueli** [comment]
> There is a S:W258R sub-branc of this.

thx added it to the proposal

**Comment by FedeGueli** [comment]
44 now and 6 with 258R

**Comment by FedeGueli** [comment]
Designated KP.4.1. via https://github.com/cov-lineages/pango-designation/commit/8fbd0bccca8b93f0293ab4139818fbd28d41cf74

**Comment by FedeGueli** [comment]
the sub branch with S:W258R designated KP.4.1.1 via https://github.com/cov-lineages/pango-designation/commit/df86946c8a512ec73b93a228adec286b6610bb78
