### ISSUE TITLE
JN.1.4 + A29799G (Octanucleotide mutation) (2057 seq, Aug 9)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2522]
**Description**
**Sub-lineage of:** JN.1.4
**Earliest sequence:** 2023-10-23, Germany, Bavaria — EPI_ISL_18526215
**Most recent sequence:** 2024-3-4, USA, California — EPI_ISL_18975471
**Continents circulating:** Asia (643), Europe (300), North America (245), Oceania (3), Africa (1)
**Countries circulating:** South Korea (610), USA (242), UK (97), Germany (69), Denmark (66)
**Number of Sequences:** 1192
**GISAID Nucleotide Query:** C774T, A29799G, C897A
**CovSpectrum Query:** Nextcladepangolineage:JN.1.4* & A29799G
**Substitutions on top of JN.1.4:**
**Nucleotide:** A29799G (in Octanucleotide Motif—ONM)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1_A29799G.json?c=gt-nuc_29799&gmin=28799&label=id:node_7017655
<img width="1379" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/658063e3-d11f-4b15-93be-127b23daafa5">

**Evidence**
A29799G is in the Octanucleotide Motif (ONM), an 8-nucleotide sequence of the 3' UTR (29794-29801) that is **absolutely conserved** among **_ALL_ coronaviruses**. Mutations in the ONM have been, as expected, extremely rare in SARS-CoV-2—until the last few months.

<img width="1369" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/63401575-5f85-4961-9f0c-263a24bc1bcf">

This branch of JN.1.4 is easily the largest lineage ever with an ONM mutation. The second-largest lineage with an ONM mutation was a ~660-sequence BA.4.6 branch with A29799T, mainly found in the US from July-September 2022. 

<img width="1349" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/bb01d803-78d9-4665-85a1-4fb872d8d86f">

The ONM is nucleotides 29794-29801 and has a sequence of GGAAGAGC. Its function is unknown, but given that it is absolutely conserved in all coronaviruses, it is clearly doing something important. Below are three different depictions of the ONM from these studies:
https://academic.oup.com/nar/article/49/6/3092/6163084
https://www.cell.com/cell/fulltext/S0092-8674(21)00158-6 
https://journals.asm.org/doi/full/10.1128/mmbr.00057-21 

<img width="1220" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/9148bb85-0855-4299-84ed-1ff51daddfbe">

.
<img width="1482" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/5e5a7187-c78f-4676-be26-6237982ea983">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18526215, EPI_ISL_18547876, EPI_ISL_18556834,
EPI_ISL_18556924, EPI_ISL_18567228, EPI_ISL_18569122,
EPI_ISL_18570359, EPI_ISL_18577761, EPI_ISL_18590802,
EPI_ISL_18591095, EPI_ISL_18596297, EPI_ISL_18596360,
EPI_ISL_18596472, EPI_ISL_18596662, EPI_ISL_18599910,
EPI_ISL_18613283, EPI_ISL_18615367, EPI_ISL_18615407,
EPI_ISL_18619741, EPI_ISL_18633057, EPI_ISL_18634387,
EPI_ISL_18637178, EPI_ISL_18644311, EPI_ISL_18652396,
EPI_ISL_18652538, EPI_ISL_18652548, EPI_ISL_18661775,
EPI_ISL_18663493, EPI_ISL_18679987, EPI_ISL_18680064,
EPI_ISL_18680155, EPI_ISL_18680275, EPI_ISL_18680366,
EPI_ISL_18680435, EPI_ISL_18680765, EPI_ISL_18680880,
EPI_ISL_18680989, EPI_ISL_18684498, EPI_ISL_18684589,
EPI_ISL_18686680, EPI_ISL_18687459, EPI_ISL_18687588,
EPI_ISL_18691353, EPI_ISL_18693014, EPI_ISL_18693342,
EPI_ISL_18694795, EPI_ISL_18694817, EPI_ISL_18695176,
EPI_ISL_18695188, EPI_ISL_18695200-18695201, EPI_ISL_18695203,
EPI_ISL_18695205, EPI_ISL_18695219, EPI_ISL_18695280,
EPI_ISL_18702396-18702397, EPI_ISL_18704591, EPI_ISL_18704619,
EPI_ISL_18704810, EPI_ISL_18704892, EPI_ISL_18704917,
EPI_ISL_18705200, EPI_ISL_18705523, EPI_ISL_18705548,
EPI_ISL_18705550, EPI_ISL_18705554, EPI_ISL_18705558,
EPI_ISL_18706816, EPI_ISL_18706831, EPI_ISL_18707250,
EPI_ISL_18707469, EPI_ISL_18708062, EPI_ISL_18711497,
EPI_ISL_18711575-18711576, EPI_ISL_18711927, EPI_ISL_18711937,
EPI_ISL_18712068, EPI_ISL_18712103, EPI_ISL_18712319,
EPI_ISL_18712983, EPI_ISL_18713127, EPI_ISL_18716760,
EPI_ISL_18717921, EPI_ISL_18721359, EPI_ISL_18721477,
EPI_ISL_18721589-18721590, EPI_ISL_18724141, EPI_ISL_18724155,
EPI_ISL_18724167, EPI_ISL_18724194, EPI_ISL_18724374,
EPI_ISL_18724386, EPI_ISL_18724642, EPI_ISL_18727003,
EPI_ISL_18727119, EPI_ISL_18727657, EPI_ISL_18729159,
EPI_ISL_18729235, EPI_ISL_18729403, EPI_ISL_18732970,
EPI_ISL_18733031, EPI_ISL_18733113, EPI_ISL_18733156,
EPI_ISL_18733418, EPI_ISL_18733493, EPI_ISL_18733592,
EPI_ISL_18733602, EPI_ISL_18733758, EPI_ISL_18733780,
EPI_ISL_18733844, EPI_ISL_18734554, EPI_ISL_18734557,
EPI_ISL_18734586, EPI_ISL_18734612, EPI_ISL_18734721,
EPI_ISL_18734877, EPI_ISL_18734951, EPI_ISL_18734954,
EPI_ISL_18734957, EPI_ISL_18735362, EPI_ISL_18735588,
EPI_ISL_18740159, EPI_ISL_18740229-18740230, EPI_ISL_18740233-18740241,
EPI_ISL_18740243-18740244, EPI_ISL_18740332, EPI_ISL_18741007,
EPI_ISL_18741088, EPI_ISL_18741245, EPI_ISL_18741302,
EPI_ISL_18741339, EPI_ISL_18741341, EPI_ISL_18743272,
EPI_ISL_18743366, EPI_ISL_18744667, EPI_ISL_18744679,
EPI_ISL_18750702, EPI_ISL_18751368, EPI_ISL_18751402,
EPI_ISL_18751421, EPI_ISL_18751556-18751557, EPI_ISL_18751574,
EPI_ISL_18751580, EPI_ISL_18751597, EPI_ISL_18751705,
EPI_ISL_18751733, EPI_ISL_18751740, EPI_ISL_18751746,
EPI_ISL_18751748, EPI_ISL_18751757, EPI_ISL_18751787,
EPI_ISL_18751798, EPI_ISL_18751839, EPI_ISL_18751847,
EPI_ISL_18751858, EPI_ISL_18751896, EPI_ISL_18751917,
EPI_ISL_18751932, EPI_ISL_18751974, EPI_ISL_18751991,
EPI_ISL_18752157, EPI_ISL_18752957, EPI_ISL_18752963,
EPI_ISL_18752981, EPI_ISL_18752983, EPI_ISL_18752986,
EPI_ISL_18753013, EPI_ISL_18753015, EPI_ISL_18753100,
EPI_ISL_18753197, EPI_ISL_18753234, EPI_ISL_18753326,
EPI_ISL_18753389, EPI_ISL_18754696, EPI_ISL_18754794,
EPI_ISL_18757131, EPI_ISL_18757548, EPI_ISL_18757664,
EPI_ISL_18757820, EPI_ISL_18757824, EPI_ISL_18757827,
EPI_ISL_18757924, EPI_ISL_18757943, EPI_ISL_18757986,
EPI_ISL_18763384, EPI_ISL_18763490, EPI_ISL_18763504-18763505,
EPI_ISL_18763588, EPI_ISL_18764201, EPI_ISL_18764432,
EPI_ISL_18764500, EPI_ISL_18769935, EPI_ISL_18770731,
EPI_ISL_18771779, EPI_ISL_18772764-18772765, EPI_ISL_18773963,
EPI_ISL_18773978, EPI_ISL_18774235, EPI_ISL_18774254,
EPI_ISL_18774447, EPI_ISL_18774575, EPI_ISL_18774698,
EPI_ISL_18774727, EPI_ISL_18774808, EPI_ISL_18774881,
EPI_ISL_18774989, EPI_ISL_18775030, EPI_ISL_18775179,
EPI_ISL_18780377, EPI_ISL_18782671, EPI_ISL_18783199-18783200,
EPI_ISL_18783207, EPI_ISL_18783233, EPI_ISL_18784831,
EPI_ISL_18784940, EPI_ISL_18785239, EPI_ISL_18785304,
EPI_ISL_18785509, EPI_ISL_18785550, EPI_ISL_18785643,
EPI_ISL_18785691, EPI_ISL_18791821, EPI_ISL_18791832,
EPI_ISL_18791852, EPI_ISL_18791913-18791914, EPI_ISL_18791919,
EPI_ISL_18791947, EPI_ISL_18791950, EPI_ISL_18791986,
EPI_ISL_18791995, EPI_ISL_18792049, EPI_ISL_18792080,
EPI_ISL_18792084, EPI_ISL_18792128, EPI_ISL_18792131,
EPI_ISL_18792140, EPI_ISL_18792142, EPI_ISL_18792147-18792148,
EPI_ISL_18792157, EPI_ISL_18792162, EPI_ISL_18792165,
EPI_ISL_18792168, EPI_ISL_18792969, EPI_ISL_18793015,
EPI_ISL_18793039, EPI_ISL_18793043-18793044, EPI_ISL_18793061-18793071,
EPI_ISL_18793087, EPI_ISL_18793092, EPI_ISL_18793169,
EPI_ISL_18793182, EPI_ISL_18793190, EPI_ISL_18793219,
EPI_ISL_18793224, EPI_ISL_18793229, EPI_ISL_18793943-18793944,
EPI_ISL_18794267, EPI_ISL_18796331, EPI_ISL_18797929,
EPI_ISL_18798057, EPI_ISL_18798070, EPI_ISL_18799249,
EPI_ISL_18799252, EPI_ISL_18799308, EPI_ISL_18800862,
EPI_ISL_18800963, EPI_ISL_18800977, EPI_ISL_18800998,
EPI_ISL_18801447, EPI_ISL_18801825, EPI_ISL_18802024-18802025,
EPI_ISL_18802032, EPI_ISL_18802048, EPI_ISL_18802094,
EPI_ISL_18802137-18802138, EPI_ISL_18806805, EPI_ISL_18806810,
EPI_ISL_18808161, EPI_ISL_18808807, EPI_ISL_18809684,
EPI_ISL_18809755, EPI_ISL_18809784, EPI_ISL_18810198,
EPI_ISL_18810232, EPI_ISL_18810250, EPI_ISL_18810266,
EPI_ISL_18810271-18810272, EPI_ISL_18810277, EPI_ISL_18813490,
EPI_ISL_18813777-18813778, EPI_ISL_18813820-18813831, EPI_ISL_18815343,
EPI_ISL_18815810, EPI_ISL_18816338, EPI_ISL_18816922,
EPI_ISL_18818011, EPI_ISL_18818109, EPI_ISL_18818124,
EPI_ISL_18818156, EPI_ISL_18818163, EPI_ISL_18818199,
EPI_ISL_18818306, EPI_ISL_18818322, EPI_ISL_18818444,
EPI_ISL_18818495, EPI_ISL_18818500, EPI_ISL_18818522,
EPI_ISL_18818647, EPI_ISL_18818703, EPI_ISL_18820136,
EPI_ISL_18820183, EPI_ISL_18820221-18820223, EPI_ISL_18821075,
EPI_ISL_18822020, EPI_ISL_18823289, EPI_ISL_18823291,
EPI_ISL_18823295, EPI_ISL_18823298, EPI_ISL_18823315,
EPI_ISL_18823317, EPI_ISL_18823351, EPI_ISL_18823353,
EPI_ISL_18823361-18823362, EPI_ISL_18823366, EPI_ISL_18823371,
EPI_ISL_18823385, EPI_ISL_18823395, EPI_ISL_18823402,
EPI_ISL_18823404, EPI_ISL_18823409, EPI_ISL_18823432,
EPI_ISL_18823440, EPI_ISL_18823450-18823451, EPI_ISL_18823454-18823455,
EPI_ISL_18823465, EPI_ISL_18823474, EPI_ISL_18823481,
EPI_ISL_18823490, EPI_ISL_18823500, EPI_ISL_18823512,
EPI_ISL_18823530-18823531, EPI_ISL_18823545, EPI_ISL_18823557,
EPI_ISL_18823566, EPI_ISL_18823578, EPI_ISL_18823588,
EPI_ISL_18823591, EPI_ISL_18823598, EPI_ISL_18823610,
EPI_ISL_18823612, EPI_ISL_18823653, EPI_ISL_18823724,
EPI_ISL_18823750, EPI_ISL_18823791, EPI_ISL_18823814,
EPI_ISL_18823826, EPI_ISL_18823830, EPI_ISL_18823847,
EPI_ISL_18823850, EPI_ISL_18823854, EPI_ISL_18824428,
EPI_ISL_18825031, EPI_ISL_18826595, EPI_ISL_18826820,
EPI_ISL_18827023, EPI_ISL_18827297, EPI_ISL_18827613,
EPI_ISL_18829889, EPI_ISL_18829893, EPI_ISL_18830026,
EPI_ISL_18830219, EPI_ISL_18831685, EPI_ISL_18831707,
EPI_ISL_18831796, EPI_ISL_18831834, EPI_ISL_18831864,
EPI_ISL_18832892, EPI_ISL_18833358, EPI_ISL_18834491,
EPI_ISL_18834509, EPI_ISL_18834720, EPI_ISL_18834769,
EPI_ISL_18834842, EPI_ISL_18834886, EPI_ISL_18834944,
EPI_ISL_18834952, EPI_ISL_18834966, EPI_ISL_18835054,
EPI_ISL_18835175, EPI_ISL_18835280, EPI_ISL_18835307,
EPI_ISL_18835342, EPI_ISL_18835542, EPI_ISL_18837890,
EPI_ISL_18839202, EPI_ISL_18841347, EPI_ISL_18841393,
EPI_ISL_18842333, EPI_ISL_18842792, EPI_ISL_18842801,
EPI_ISL_18842863, EPI_ISL_18842889, EPI_ISL_18842892,
EPI_ISL_18842896, EPI_ISL_18842898, EPI_ISL_18842901,
EPI_ISL_18842933-18842934, EPI_ISL_18842936, EPI_ISL_18845395,
EPI_ISL_18846493, EPI_ISL_18846737, EPI_ISL_18846854,
EPI_ISL_18847196-18847197, EPI_ISL_18850074, EPI_ISL_18851582,
EPI_ISL_18853513, EPI_ISL_18854015, EPI_ISL_18854027,
EPI_ISL_18854884, EPI_ISL_18855504, EPI_ISL_18858602,
EPI_ISL_18859009, EPI_ISL_18860101, EPI_ISL_18860748,
EPI_ISL_18860816, EPI_ISL_18861036-18861037, EPI_ISL_18861086,
EPI_ISL_18861189, EPI_ISL_18864340, EPI_ISL_18865116,
EPI_ISL_18865157, EPI_ISL_18865162, EPI_ISL_18866075,
EPI_ISL_18867081, EPI_ISL_18868446, EPI_ISL_18868500,
EPI_ISL_18868562, EPI_ISL_18868572, EPI_ISL_18868601,
EPI_ISL_18868700, EPI_ISL_18868703, EPI_ISL_18868722,
EPI_ISL_18868745, EPI_ISL_18869639, EPI_ISL_18869725,
EPI_ISL_18869814, EPI_ISL_18869937, EPI_ISL_18869945,
EPI_ISL_18869948, EPI_ISL_18870199, EPI_ISL_18871689,
EPI_ISL_18872058, EPI_ISL_18872101, EPI_ISL_18872110,
EPI_ISL_18872166, EPI_ISL_18872215, EPI_ISL_18872899,
EPI_ISL_18872925, EPI_ISL_18876388, EPI_ISL_18877470,
EPI_ISL_18877473-18877474, EPI_ISL_18877501, EPI_ISL_18878112,
EPI_ISL_18878337, EPI_ISL_18878527, EPI_ISL_18879545,
EPI_ISL_18879570, EPI_ISL_18879583, EPI_ISL_18879587,
EPI_ISL_18879642, EPI_ISL_18880684, EPI_ISL_18881320,
EPI_ISL_18881429, EPI_ISL_18881470, EPI_ISL_18881523,
EPI_ISL_18881641, EPI_ISL_18881648, EPI_ISL_18881660,
EPI_ISL_18881697-18881698, EPI_ISL_18884639, EPI_ISL_18886360,
EPI_ISL_18887191, EPI_ISL_18887355, EPI_ISL_18887488,
EPI_ISL_18887532, EPI_ISL_18887535, EPI_ISL_18887549,
EPI_ISL_18887748, EPI_ISL_18887761, EPI_ISL_18887777-18887778,
EPI_ISL_18887796, EPI_ISL_18887801, EPI_ISL_18887810,
EPI_ISL_18887813, EPI_ISL_18887817, EPI_ISL_18887819,
EPI_ISL_18887825-18887826, EPI_ISL_18887828, EPI_ISL_18887831,
EPI_ISL_18887833-18887834, EPI_ISL_18887837, EPI_ISL_18887839,
EPI_ISL_18887845, EPI_ISL_18887848, EPI_ISL_18887857,
EPI_ISL_18887893, EPI_ISL_18887906, EPI_ISL_18887912,
EPI_ISL_18887926, EPI_ISL_18887947, EPI_ISL_18887987,
EPI_ISL_18888007-18888008, EPI_ISL_18888015, EPI_ISL_18888030,
EPI_ISL_18888037, EPI_ISL_18888039, EPI_ISL_18888049,
EPI_ISL_18888068, EPI_ISL_18888089-18888090, EPI_ISL_18888103,
EPI_ISL_18888105, EPI_ISL_18888109-18888111, EPI_ISL_18888125,
EPI_ISL_18888135, EPI_ISL_18888144, EPI_ISL_18888148,
EPI_ISL_18888170, EPI_ISL_18888192, EPI_ISL_18888207,
EPI_ISL_18888228, EPI_ISL_18888271, EPI_ISL_18889673,
EPI_ISL_18889678, EPI_ISL_18890632, EPI_ISL_18890636,
EPI_ISL_18890760, EPI_ISL_18892652, EPI_ISL_18895233,
EPI_ISL_18895681, EPI_ISL_18895722, EPI_ISL_18895842,
EPI_ISL_18896141, EPI_ISL_18896263, EPI_ISL_18896273,
EPI_ISL_18896409, EPI_ISL_18896443, EPI_ISL_18896632,
EPI_ISL_18896681, EPI_ISL_18896713, EPI_ISL_18896815,
EPI_ISL_18896891, EPI_ISL_18897535, EPI_ISL_18899653,
EPI_ISL_18899655, EPI_ISL_18899662, EPI_ISL_18899680,
EPI_ISL_18899684-18899685, EPI_ISL_18899689, EPI_ISL_18899708,
EPI_ISL_18899716, EPI_ISL_18899719, EPI_ISL_18899732,
EPI_ISL_18899771, EPI_ISL_18899778, EPI_ISL_18899797-18899798,
EPI_ISL_18899818, EPI_ISL_18899824, EPI_ISL_18899841,
EPI_ISL_18899851, EPI_ISL_18899853, EPI_ISL_18899866,
EPI_ISL_18899871, EPI_ISL_18899876-18899877, EPI_ISL_18899882,
EPI_ISL_18899884, EPI_ISL_18899896-18899897, EPI_ISL_18899899,
EPI_ISL_18899903, EPI_ISL_18899911, EPI_ISL_18899913,
EPI_ISL_18899916, EPI_ISL_18899925-18899929, EPI_ISL_18899932,
EPI_ISL_18899941, EPI_ISL_18899944-18899945, EPI_ISL_18899951-18899954,
EPI_ISL_18899960, EPI_ISL_18899968, EPI_ISL_18899975-18899976,
EPI_ISL_18899986, EPI_ISL_18899992, EPI_ISL_18899995,
EPI_ISL_18900005, EPI_ISL_18900016, EPI_ISL_18900018,
EPI_ISL_18900021, EPI_ISL_18900026, EPI_ISL_18900030-18900031,
EPI_ISL_18900042, EPI_ISL_18900047, EPI_ISL_18900049,
EPI_ISL_18900058, EPI_ISL_18900060, EPI_ISL_18900062,
EPI_ISL_18900071, EPI_ISL_18900073, EPI_ISL_18900080-18900081,
EPI_ISL_18900084, EPI_ISL_18900087, EPI_ISL_18900091-18900092,
EPI_ISL_18900094, EPI_ISL_18900098, EPI_ISL_18900101,
EPI_ISL_18900108, EPI_ISL_18900110-18900111, EPI_ISL_18900119,
EPI_ISL_18900122, EPI_ISL_18900129, EPI_ISL_18900131,
EPI_ISL_18900137, EPI_ISL_18900144-18900145, EPI_ISL_18900155-18900156,
EPI_ISL_18900164, EPI_ISL_18900167, EPI_ISL_18900177,
EPI_ISL_18900183, EPI_ISL_18900187, EPI_ISL_18900192-18900193,
EPI_ISL_18900205, EPI_ISL_18900213, EPI_ISL_18900223,
EPI_ISL_18900225, EPI_ISL_18901694, EPI_ISL_18901755,
EPI_ISL_18902546, EPI_ISL_18902841, EPI_ISL_18903091,
EPI_ISL_18903160, EPI_ISL_18903166, EPI_ISL_18903252,
EPI_ISL_18903256, EPI_ISL_18903316, EPI_ISL_18903379,
EPI_ISL_18903403, EPI_ISL_18903494, EPI_ISL_18903549,
EPI_ISL_18903575, EPI_ISL_18903694, EPI_ISL_18903710,
EPI_ISL_18903740, EPI_ISL_18903743, EPI_ISL_18909147,
EPI_ISL_18909457, EPI_ISL_18910230, EPI_ISL_18910267,
EPI_ISL_18910276, EPI_ISL_18914790, EPI_ISL_18914831,
EPI_ISL_18915003, EPI_ISL_18915515, EPI_ISL_18915631,
EPI_ISL_18915853, EPI_ISL_18916150, EPI_ISL_18916264,
EPI_ISL_18918050, EPI_ISL_18918346, EPI_ISL_18918352,
EPI_ISL_18918552, EPI_ISL_18918563, EPI_ISL_18918576,
EPI_ISL_18918586, EPI_ISL_18918588, EPI_ISL_18918619,
EPI_ISL_18920327, EPI_ISL_18920485, EPI_ISL_18920609,
EPI_ISL_18921124, EPI_ISL_18921166, EPI_ISL_18921442,
EPI_ISL_18921919, EPI_ISL_18922183, EPI_ISL_18922243,
EPI_ISL_18922295, EPI_ISL_18922335, EPI_ISL_18922454,
EPI_ISL_18923904, EPI_ISL_18923923, EPI_ISL_18923927,
EPI_ISL_18923932, EPI_ISL_18923953, EPI_ISL_18923958-18923959,
EPI_ISL_18923966, EPI_ISL_18923970, EPI_ISL_18923974,
EPI_ISL_18923982, EPI_ISL_18923992, EPI_ISL_18924001-18924002,
EPI_ISL_18924004, EPI_ISL_18924008, EPI_ISL_18924027,
EPI_ISL_18924031, EPI_ISL_18924034-18924036, EPI_ISL_18924038,
EPI_ISL_18924044, EPI_ISL_18924046, EPI_ISL_18924049,
EPI_ISL_18924053, EPI_ISL_18924057, EPI_ISL_18924060,
EPI_ISL_18924062, EPI_ISL_18924088, EPI_ISL_18924102,
EPI_ISL_18924105, EPI_ISL_18924109-18924110, EPI_ISL_18924119-18924120,
EPI_ISL_18924128, EPI_ISL_18924131, EPI_ISL_18924134-18924137,
EPI_ISL_18924147, EPI_ISL_18924155, EPI_ISL_18924166-18924167,
EPI_ISL_18924178, EPI_ISL_18924185, EPI_ISL_18924193,
EPI_ISL_18924198-18924199, EPI_ISL_18924203, EPI_ISL_18924207,
EPI_ISL_18924209, EPI_ISL_18924213, EPI_ISL_18924217,
EPI_ISL_18924229, EPI_ISL_18924245, EPI_ISL_18924259,
EPI_ISL_18924300, EPI_ISL_18924306, EPI_ISL_18924321,
EPI_ISL_18924323-18924326, EPI_ISL_18924342, EPI_ISL_18924354,
EPI_ISL_18924356, EPI_ISL_18924366, EPI_ISL_18924370,
EPI_ISL_18924372, EPI_ISL_18924379, EPI_ISL_18924403,
EPI_ISL_18924417-18924419, EPI_ISL_18924425, EPI_ISL_18924431,
EPI_ISL_18924437, EPI_ISL_18924449, EPI_ISL_18924453-18924455,
EPI_ISL_18924494, EPI_ISL_18924496, EPI_ISL_18924505,
EPI_ISL_18924516-18924517, EPI_ISL_18924524, EPI_ISL_18924554,
EPI_ISL_18926604, EPI_ISL_18927178, EPI_ISL_18927234,
EPI_ISL_18927625, EPI_ISL_18927932, EPI_ISL_18928146,
EPI_ISL_18930385, EPI_ISL_18930568, EPI_ISL_18931340,
EPI_ISL_18931343, EPI_ISL_18931433, EPI_ISL_18931435-18931436,
EPI_ISL_18931448-18931449, EPI_ISL_18931452, EPI_ISL_18931492,
EPI_ISL_18931499, EPI_ISL_18931552, EPI_ISL_18932471,
EPI_ISL_18932617, EPI_ISL_18933298, EPI_ISL_18933311,
EPI_ISL_18933349, EPI_ISL_18935571, EPI_ISL_18935593,
EPI_ISL_18936379, EPI_ISL_18936419, EPI_ISL_18938398,
EPI_ISL_18938432, EPI_ISL_18938463, EPI_ISL_18938950,
EPI_ISL_18939178, EPI_ISL_18939725, EPI_ISL_18939729,
EPI_ISL_18940073, EPI_ISL_18940326, EPI_ISL_18940400,
EPI_ISL_18941837, EPI_ISL_18941873, EPI_ISL_18942192,
EPI_ISL_18942510, EPI_ISL_18944202, EPI_ISL_18946382,
EPI_ISL_18948100, EPI_ISL_18948104, EPI_ISL_18948114,
EPI_ISL_18948123, EPI_ISL_18948135, EPI_ISL_18948138-18948139,
EPI_ISL_18948147, EPI_ISL_18948167, EPI_ISL_18948176,
EPI_ISL_18948179, EPI_ISL_18948207-18948208, EPI_ISL_18948210,
EPI_ISL_18948213, EPI_ISL_18948219-18948221, EPI_ISL_18948229,
EPI_ISL_18948243, EPI_ISL_18948245, EPI_ISL_18948252,
EPI_ISL_18948256-18948257, EPI_ISL_18948269, EPI_ISL_18948291,
EPI_ISL_18948299-18948300, EPI_ISL_18948315, EPI_ISL_18948321,
EPI_ISL_18948326, EPI_ISL_18948331-18948332, EPI_ISL_18948342,
EPI_ISL_18948372, EPI_ISL_18948376-18948377, EPI_ISL_18948380,
EPI_ISL_18948382, EPI_ISL_18948385, EPI_ISL_18948404,
EPI_ISL_18948409, EPI_ISL_18948412, EPI_ISL_18948425,
EPI_ISL_18948429, EPI_ISL_18948434, EPI_ISL_18948442,
EPI_ISL_18948447, EPI_ISL_18948457, EPI_ISL_18948465,
EPI_ISL_18948480, EPI_ISL_18948482, EPI_ISL_18948486-18948488,
EPI_ISL_18948494, EPI_ISL_18948497, EPI_ISL_18948499,
EPI_ISL_18948508-18948509, EPI_ISL_18948511, EPI_ISL_18948527,
EPI_ISL_18948539-18948540, EPI_ISL_18948545, EPI_ISL_18948549,
EPI_ISL_18948552, EPI_ISL_18948554, EPI_ISL_18948563,
EPI_ISL_18948575-18948576, EPI_ISL_18948583, EPI_ISL_18948587,
EPI_ISL_18948644, EPI_ISL_18948649, EPI_ISL_18948657,
EPI_ISL_18949288, EPI_ISL_18950317, EPI_ISL_18950322,
EPI_ISL_18950509, EPI_ISL_18950961, EPI_ISL_18951050,
EPI_ISL_18951099, EPI_ISL_18951283, EPI_ISL_18951763,
EPI_ISL_18951888, EPI_ISL_18952001, EPI_ISL_18952536,
EPI_ISL_18952766, EPI_ISL_18954279, EPI_ISL_18954376,
EPI_ISL_18954416, EPI_ISL_18954476, EPI_ISL_18954506,
EPI_ISL_18954597, EPI_ISL_18954619, EPI_ISL_18956162,
EPI_ISL_18957922, EPI_ISL_18961438, EPI_ISL_18962781,
EPI_ISL_18962861, EPI_ISL_18962923, EPI_ISL_18962954,
EPI_ISL_18963042, EPI_ISL_18963856, EPI_ISL_18963906,
EPI_ISL_18963954, EPI_ISL_18964204, EPI_ISL_18964473,
EPI_ISL_18964953, EPI_ISL_18966486, EPI_ISL_18966511,
EPI_ISL_18966520, EPI_ISL_18966537, EPI_ISL_18966550,
EPI_ISL_18966556, EPI_ISL_18966561, EPI_ISL_18966565,
EPI_ISL_18966567, EPI_ISL_18966571-18966573, EPI_ISL_18966584,
EPI_ISL_18966595, EPI_ISL_18966597, EPI_ISL_18966612,
EPI_ISL_18966622, EPI_ISL_18966634, EPI_ISL_18966639,
EPI_ISL_18966645, EPI_ISL_18966667-18966668, EPI_ISL_18966670-18966671,
EPI_ISL_18966673, EPI_ISL_18966685, EPI_ISL_18966687,
EPI_ISL_18966708, EPI_ISL_18966727, EPI_ISL_18966736,
EPI_ISL_18966746-18966747, EPI_ISL_18966751, EPI_ISL_18966754,
EPI_ISL_18966765, EPI_ISL_18966776, EPI_ISL_18966781,
EPI_ISL_18966784, EPI_ISL_18966789, EPI_ISL_18966791,
EPI_ISL_18966806-18966807, EPI_ISL_18966835, EPI_ISL_18966840,
EPI_ISL_18966845, EPI_ISL_18966854, EPI_ISL_18966876,
EPI_ISL_18966890-18966892, EPI_ISL_18966905, EPI_ISL_18966921,
EPI_ISL_18966923-18966926, EPI_ISL_18966930, EPI_ISL_18966936,
EPI_ISL_18966945, EPI_ISL_18966952-18966953, EPI_ISL_18966956,
EPI_ISL_18966966, EPI_ISL_18966968, EPI_ISL_18966985,
EPI_ISL_18967004, EPI_ISL_18967008, EPI_ISL_18967010,
EPI_ISL_18967017, EPI_ISL_18967025, EPI_ISL_18967031,
EPI_ISL_18967057, EPI_ISL_18967061-18967066, EPI_ISL_18967071,
EPI_ISL_18967073, EPI_ISL_18967075-18967076, EPI_ISL_18967078-18967079,
EPI_ISL_18967087, EPI_ISL_18967089, EPI_ISL_18967091,
EPI_ISL_18967197, EPI_ISL_18967971, EPI_ISL_18968610,
EPI_ISL_18969394, EPI_ISL_18969548, EPI_ISL_18973253,
EPI_ISL_18973377, EPI_ISL_18973423, EPI_ISL_18973608,
EPI_ISL_18973758, EPI_ISL_18974791, EPI_ISL_18975418,
EPI_ISL_18975471, EPI_ISL_18975734, EPI_ISL_18975785,
EPI_ISL_18975830, EPI_ISL_18977876, EPI_ISL_18977900,
EPI_ISL_18977923, EPI_ISL_18978795, EPI_ISL_18980302,
EPI_ISL_18980784, EPI_ISL_18981166, EPI_ISL_18981826,
EPI_ISL_18982285, EPI_ISL_18982295, EPI_ISL_18982301,
EPI_ISL_18982309, EPI_ISL_18982320, EPI_ISL_18982326,
EPI_ISL_18982329, EPI_ISL_18982333, EPI_ISL_18982356,
EPI_ISL_18982362-18982363, EPI_ISL_18982383, EPI_ISL_18982401,
EPI_ISL_18982406, EPI_ISL_18982414, EPI_ISL_18982421,
EPI_ISL_18982443, EPI_ISL_18982451, EPI_ISL_18982453,
EPI_ISL_18982456, EPI_ISL_18982463, EPI_ISL_18982471,
EPI_ISL_18982481, EPI_ISL_18982487, EPI_ISL_18982489-18982490,
EPI_ISL_18982493, EPI_ISL_18982496, EPI_ISL_18982502,
EPI_ISL_18982520-18982521, EPI_ISL_18982525, EPI_ISL_18982528,
EPI_ISL_18982533, EPI_ISL_18982535-18982536, EPI_ISL_18982541,
EPI_ISL_18982550, EPI_ISL_18982558, EPI_ISL_18982570,
EPI_ISL_18982573-18982574, EPI_ISL_18982581-18982583, EPI_ISL_18982604,
EPI_ISL_18982616-18982617, EPI_ISL_18982658, EPI_ISL_18982671,
EPI_ISL_18982700, EPI_ISL_18982737, EPI_ISL_18982754-18982755,
EPI_ISL_18982788, EPI_ISL_18982791, EPI_ISL_18982794,
EPI_ISL_18982800, EPI_ISL_18982806-18982807, EPI_ISL_18982838,
EPI_ISL_18982855, EPI_ISL_18983549, EPI_ISL_18983693,
EPI_ISL_18983701, EPI_ISL_18983898, EPI_ISL_18984551,
</details>

**Comment by Over-There-Is** [comment]
It's on T18453C branch
