### ISSUE TITLE
JN.1.11.1+C6070T with FLiRT (346T+456L) and S:K187R (32 sequences, 10 countries )

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2523]
Previously tracked as Branch 52 in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089
One more JN.1.11.1 sublineage got FliRT combo mutation S:F456L S:R346T and a further NTD mutation S:K187R

JN.1.11.1 > C6070T > S:K187R (A22122G), S:R346T (G22599C)
Query: C6070T,G22599C,C7113T,G24872T,-C19884T
Samples: 9
Countries: Australia, US ( NY, NJ), Lebanon, Singapore (via China), India (via GBW)
IDs:
EPI_ISL_18933442, EPI_ISL_18939081, EPI_ISL_18945988,
EPI_ISL_18953029, EPI_ISL_18961244-18961245, EPI_ISL_18983740,
EPI_ISL_18983801, EPI_ISL_18983814
Tree:
<img width="1174" alt="Screenshot 2024-03-17 alle 04 09 18" src="https://github.com/cov-lineages/pango-designation/assets/87669813/3ee742c2-6a92-4e1f-99af-ec7963c3069d">
<img width="1163" alt="Screenshot 2024-03-17 alle 04 08 59" src="https://github.com/cov-lineages/pango-designation/assets/87669813/2baccba1-e999-412f-84df-e1afd6e8a10c">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_c546_5e69a0.json?c=gt-S_346,187&gmax=25384&gmin=21563&label=id:node_6944915

**Comment by karyakarte** [comment]
@FedeGueli as discussed earlier, JN.1 and JN.1.1 are declining in February as JN.1.11.1 and JN.1.18 are on a rise.

**Comment by FedeGueli** [comment]
+1 California

**Comment by FedeGueli** [comment]
16 now also from Scotland , Singapore (GBW) and Canada

**Comment by FedeGueli** [comment]
20, @corneliusroemer i suggest to designate it.

**Comment by aviczhl2** [comment]
27 now

**Comment by FedeGueli** [comment]
32 seqs

**Comment by FedeGueli** [comment]
designated KP.4.2 via https://github.com/cov-lineages/pango-designation/commit/8fbd0bccca8b93f0293ab4139818fbd28d41cf74

**Comment by FedeGueli** [comment]
One sequence of KP.4.2 popped up today in Texas with a further mutation at S:187 : S:K>R187S involving two nucleotides in two steps: A22122G (>R) > A22123T (>S) 
Query: A22122G,A22123T  (cause it is the first ever sample with it)

Interestingly it should create a N Glycan at S:N185
<img width="1163" alt="Screenshot 2024-05-02 alle 22 49 15" src="https://github.com/cov-lineages/pango-designation/assets/87669813/b033c4fd-e6e4-4979-9366-79ae41f0b7bc">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_4a23b_3d3430.json?c=gt-S_187&label=id:node_6979126
