### ISSUE TITLE
JN.1 with N:Q240L, ORF9b:I5T, ORF1a:G519S (107 seq, May 3)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2528]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1342
**Description**
**Sub-lineage of:** JN.1
**Earliest sequence:** 2023-12-8, England — EPI_ISL_18652267
**Most recent sequence:** 2024-1-14, England — EPI_ISL_18809846
**Continents circulating:** Europe (12), North America (12)
**Countries circulating:** USA (12), England (9), Italy (2), Mexico (1), Netherlands (1), Scotland (1), Spain (1)
**Number of Sequences:** 24
**GISAID Nucleotide Query:** A28992T, T28297C, C28958A
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & T28297C & [3-of: G1820A, C8299T, G8578A, A13063G, C26499G, A28992T]
**Substitutions on top of JN.1:**
**N:** Q240L
**ORF9b:** I5T
**ORF1a:** G519S
**Nucleotide:** G1820A, C8299T, G8578A, A13063G, C26499G, T28297C, A28992T  

**Phylogenetic Order of Mutations:**  G8578A  **→**  C26499G  **→**  A28992T (N:Q240L)   **→**   G1820A (ORF1a:G519S)   **→**  C8299T, A13063G   **→**   T28297C (ORF9b:I5T)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1_N.Q240L_ORF9b.I5T.json?c=gt-nuc_28297&gmax=29297&gmin=27297&label=id:node_6854307
<img width="1448" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d0a85f2e-5fb2-48b3-a59c-4ab6a4e63695">

**Evidence**
This is surprisingly geographically widespread perhaps indicating that it originates in a region with no sequencing. Like Germany, for example. 

There is one sequence from England and one sequence from the US on the Usher tree but not yet on GISAID. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18652267, EPI_ISL_18668187, EPI_ISL_18668195,
EPI_ISL_18688910, EPI_ISL_18699137, EPI_ISL_18701770,
EPI_ISL_18721176, EPI_ISL_18721203, EPI_ISL_18722984,
EPI_ISL_18723009, EPI_ISL_18731528, EPI_ISL_18763944,
EPI_ISL_18763949, EPI_ISL_18763951, EPI_ISL_18771708,
EPI_ISL_18774842, EPI_ISL_18775066, EPI_ISL_18793807,
EPI_ISL_18799435, EPI_ISL_18809175, EPI_ISL_18809846,
EPI_ISL_18809849, EPI_ISL_18822360-18822361
</details>

**Comment by FedeGueli** [comment]
Thank you!
