### ISSUE TITLE
Proposal to reopen #202: Delta with S:I850L and ORF3a:K16T spreading in Turkey, Denmark, and Germany

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#253]
@c19850727 helpfully pointed out that this lineage seems to have sustained growth. I did a quick review of recent developments and would suggest  to consider reopening this issue.

I can see a) potential growth signals and b) epidemiological clustering in countries: Turkey (~20%), Slovakia (~20%) and significant growing shares in Germany, Denmark, Netherlands, Belgium and Switzerland. It also has a spike mutation and a few accompanying ones, making it rather distinct on the tree.

It's clearly a Europe lineage [localized in only certain European countries], not spread all over the world.

30% of these sequences are currently misclassified as AY.4, so it'd also be useful in that direction to designate.

Here are a few screenshots and links to trees and cov-spectrum:

It's grown to 5% in Germany within the last month or two, it's visible on a Germany/Europe  build:
![image](https://user-images.githubusercontent.com/25161793/137351462-ec27962f-1779-47b0-89b6-0b1b8a92fef4.png)
https://nextstrain.org/groups/neherlab/ncov/europe?branchLabel=aa&c=gt-S_850&m=div

![image](https://user-images.githubusercontent.com/25161793/137351646-ac5b4d31-4d3d-496c-ab56-84fba7121817.png)
![image](https://user-images.githubusercontent.com/25161793/137351656-26ea9e28-8ef2-4564-886f-fe05e88122c8.png)

![image](https://user-images.githubusercontent.com/25161793/137351706-21297a41-cf0f-43bc-85a0-c7588feb3b36.png)

https://cov-spectrum.ethz.ch/explore/Germany/AllSamples/Past6M/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22S%3A850L%22]%7D%2C%22matchPercentage%22%3A1%7D

This is the proportion share changing over two months, it's going up in all countries shown, despite Delta already being established in all these countries, so no singular founder effect.
![image](https://user-images.githubusercontent.com/25161793/137352303-f5ac84b2-f149-485a-953d-0ddf76a3a554.png)

![image](https://user-images.githubusercontent.com/25161793/137352305-7ce43a63-de5f-4a73-8e17-a361f9b2999d.png)

_Originally posted by @corneliusroemer in https://github.com/cov-lineages/pango-designation/issues/202#issuecomment-943486593_

**Comment by FedeGueli** [comment]
A part of this undesignated sublineage is currently missassigned as AY.39,AY.46 and AY.43:
![chrome_screenshot_1636966350367](https://user-images.githubusercontent.com/87669813/141751300-ada55892-dacd-4149-bd02-4738b99b57c1.png)

But it doesnt seem to have emerged indepently in these lineages:
![chrome_screenshot_1636966261339](https://user-images.githubusercontent.com/87669813/141751462-2b5e1e00-6b52-47d8-87a5-5383e00663b9.png)

So i think it would be helpful to designate it to avoid unnecessary rumour to the AY.s monitoring

@corneliusroemer @chrisruis 

And it was already disccussed in public on twitter:
https://twitter.com/HuJirui/status/1459961669057196036?s=20

It would be better to designate it to assess thing correctly.

**Comment by FedeGueli** [comment]
Still this clade is often missassigned as AY.39:
In Germany is up to 40% of assigned AY.39 sequences:
![Schermata 2021-11-21 alle 10 33 15](https://user-images.githubusercontent.com/87669813/142756900-dfbcd8ef-56c7-4f96-9841-f1ef7438eaf8.png)

A rapid designation of this one would greatly help to monitor the (hard) epi situation in Europe

@chrisruis @AngieHinrichs

**Comment by FedeGueli** [comment]
BTW It is still at 4% of seqs (declining) in Germany that is experimenting a tremendous wave
https://cov-spectrum.ethz.ch/explore/Europe/AllSamples/from=2021-10-16&to=2021-11-21/variants?aaMutations=S%3A850L&pangoLineage=B.1.617.2*

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as AY.126 in [v1.2.103](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.103) to start on a branch with A21137G (Orf1ab:K6958R)
