### ISSUE TITLE
Another JN.1+S:S31F(119 seqs, 8 countries, 47 with S:R346T, 27 with FLiRT)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2530]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1445
JN.1+C24023T+C21654T(S:S31F)

GISAID query:C24023T,C21654T,C18894T
No. of seqs: 59(South Korea 57 Japan 1 USA 1)
58 on GISAID , 1 USA seq PP077093.1 not. 
GISAID query for S:R346T branch: C24023T,C21654T,C18894T,G22599C (9 seqs)
GISAID query for further S:F456L: C24023T,C21654T,C18894T,G22599C ,T22928C (1 seq)

First: EPI_ISL_18687243, South Korea 2023-11-21
Latest: EPI_ISL_19001311, South Korea, 2024-2-26

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_s31f.json?label=id:node_7003246)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/065ab6d7-d063-4702-a381-0d2d47842032)

**Comment by aviczhl2** [comment]
One FLiRT seq emerges from this branch.

**Comment by FedeGueli** [comment]
79 now for S:S31F
17 for S:R346T (all from S.Korea)
3 for S:F456L (All south Korea)

cc @corneliusroemer i suggest to designate this one.

**Comment by aviczhl2** [comment]
new country of Netherlands

**Comment by FedeGueli** [comment]
now: 90 > 27 > 10 

Big upload today of samples from South Korea  belonging to the FLiRT branch:
<img width="1171" alt="Screenshot 2024-04-29 alle 13 07 17" src="https://github.com/cov-lineages/pango-designation/assets/87669813/51123d2b-91de-40e3-8bdc-a5285cbad314">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_129bc_f78670.json?c=userOrOld&label=id:node_7027376

**Comment by FedeGueli** [comment]
98 31F > 31 346T  > 14 FLiRT  ping @corneliusroemer i think this should be designated.

**Comment by FedeGueli** [comment]
16 with FLiRT

**Comment by FedeGueli** [comment]
18 for FLiRT

**Comment by FedeGueli** [comment]
105  , 18 FLiRT, slowed down a lot in my view

**Comment by FedeGueli** [comment]
19 for FLiRT after one month hiatus

**Comment by aviczhl2** [comment]
111, Spain, China, France

**Comment by aviczhl2** [comment]
119,Canada
