### ISSUE TITLE
JN.1+M:L46F+S:F456L(1922 seqs, 38 countries, 28% China, 22 with S:R346T, 51 with S:S31F, 6 with S:T22N)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2531]
From branch 26 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253

JN.1 > M:L46F (G26660T) > G4162A > S:F456L (T22928C)

GISAID query:G26660T, G4162A ,T22928C,T3565C  (26 seqs)
GISAID supplementary query: G4162A,-22928,G1126A,T3565C (2 seqs, for seqs with no coverage at S:F456 but share mutation)
No. of seqs:  28(USA 4(2 from Singapore, 2 from South Korea) China 24(Hubei, Shanxi, Heilongjiang, Gansu, Henan, Hong Kong, Fujian from Taiwan, 1 from Malaysia 1 from Australia 1 from Thailand))

GISAID query for S:R346T branch: G26660T, G4162A ,T22928C,T3565C,G22599C (1 seq)
GISAID query for S:S31F branch: G26660T, G4162A ,T22928C,T3565C, C21654T

First: EPI_ISL_18872894, Hong Kong, 2024-1-27
Latest: EPI_ISL_18999287, USA from South Korea, 2024-3-12

Seems widely distributed in China and SE Asian countries. 
Usher splits into two branches but the G1126A is separated by 2 Hong Kong seqs with no coverage on S:456, they shall have S:F456L too. 
[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_f456l.json?label=id:node_6963464)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/206cdaeb-b7a8-4afe-96b4-0f5be8f4f792)

**Comment by FedeGueli** [comment]
Thank you great work

**Comment by aviczhl2** [comment]
+1 Japan

**Comment by aviczhl2** [comment]
+1 UK

**Comment by aviczhl2** [comment]
+1 Taiwan

**Comment by aviczhl2** [comment]
+8 from Fujian, Anhui, Hubei and Taiwan.

**Comment by FedeGueli** [comment]
<img width="625" alt="Screenshot 2024-03-27 alle 18 42 44" src="https://github.com/cov-lineages/pango-designation/assets/87669813/17938240-1b50-4cd0-b5bf-7775c7b6b69e">
To me it seems really a fastg lineage, likely less than FLiRT tough.

**Comment by aviczhl2** [comment]
14/81=17% in the 4-1 Shanxi batch.

**Comment by FedeGueli** [comment]
ping @corneliusroemer this is fast

**Comment by aviczhl2** [comment]
+22. 

16/207=8% in Hubei seqs from 2024.3.20.

**Comment by aviczhl2** [comment]
+1 South Korea with the same situation of  Hong Kong seqs(share mut+ no coverage at 456)

**Comment by FedeGueli** [comment]
fast growing and prevalent, ping @corneliusroemer

**Comment by FedeGueli** [comment]
It got FLIRT! : EPI_ISL_19045970 @corneliusroemer this one is to watch

**Comment by aviczhl2** [comment]
153, New Zeland, France,

**Comment by aviczhl2** [comment]
19/189=10% in Hubei seqs after 4-1

**Comment by FedeGueli** [comment]
This likely the fastest non Flirt behind KP.3 : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1*&nucMutations1=G26660T%2CG4162A%2CT22928C%2CT3565C&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
189, Qatar,

**Comment by aviczhl2** [comment]
251 seqs now

**Comment by FedeGueli** [comment]
> 17/153=11% in Heilongjiang seqs after 2024-4 19/111=17% in Hubei seqs after 2024-4-15, growing fast (from 10%)

@corneliusroemer this is faster than many Flirt lineages , already big enough to exclude founder or cluster effect, i suggest strongly an urgent designation

**Comment by aviczhl2** [comment]
> > 17/153=11% in Heilongjiang seqs after 2024-4 19/111=17% in Hubei seqs after 2024-4-15, growing fast (from 10%)
> 
> @corneliusroemer this is faster than many Flirt lineages , already big enough to exclude founder or cluster effect, i suggest strongly an urgent designation

Maybe like EG.5.1 being faster than many early Flips.

**Comment by FedeGueli** [comment]
> > > 17/153=11% in Heilongjiang seqs after 2024-4 19/111=17% in Hubei seqs after 2024-4-15, growing fast (from 10%)
> > 
> > 
> > @corneliusroemer this is faster than many Flirt lineages , already big enough to exclude founder or cluster effect, i suggest strongly an urgent designation
> 
> Maybe like EG.5.1 being faster than many early Flips.

Yeah one thing to notice is that in China FLiRT are still very low numbers so baseline is lower there allowing maybe a easier spread than , to say India or other places with higher FLiRT prevalence

**Comment by FedeGueli** [comment]
+3 South Korea, it starts expanding outside China

**Comment by Over-There-Is** [comment]
Hong_Kong/HKU-240503-042/2023|EPI_ISL_19093478|2023-12-17
JN.1> G26660T> G4162A> A10066G
The earliest sequence with or without T22928C are both from Hong Kong.(Exactly EPI_ISL_18872894 and EPI_ISL_18872895 have no coverage on 22928, but the existence of T22928C could be inferenced by the following G1126A.)
I think this branch could originates in some undersampled southern provinces(e. g. Guangdong).
Or it could be from Hong Kong too, the only sequence without T22928C in Mainland is collected from Shanghai.
Rather than interior provinces which interact frequently with Guangdong, Hong Kong is more closely connected to Shanghai.

**Comment by FedeGueli** [comment]
> Hong_Kong/HKU-240503-042/2023|EPI_ISL_19093478|2023-12-17 JN.1> G26660T> G4162A> A10066G The earliest sequence with or without T22928C are both from Hong Kong.(Exactly EPI_ISL_18872894 and EPI_ISL_18872895 have no coverage on 22928, but the existence of T22928C could be inferenced by the following G1126A.) I think this branch could originates in some undersampled southern provinces(e. g. Guangdong). Or it could be from Hong Kong too, the only sequence without T22928C in Mainland is collected from Shanghai. Rather than interior provinces which interact frequently with Guangdong, Hong Kong is more closely connected to Shanghai.

thx for the analysis

**Comment by aviczhl2** [comment]
274, Netherlands, Ireland (both via GBW)

**Comment by FedeGueli** [comment]
imopressive fast , @corneliusroemer when you will be back this is one of the first to need a designation

**Comment by Over-There-Is** [comment]
some liaoning sequences got 4162 reverted, but i dont think theyre true

**Comment by Over-There-Is** [comment]
Multiple cities, Liaoning 05-10 13/101
Jincheng, Shanxi 05-07 6/51

**Comment by Over-There-Is** [comment]
*Some sequences have neither G1126A nor G4162A. They should be investigated further.

**Comment by FedeGueli** [comment]
> *Some sequences have neither G1126A nor G4162A. They should be investigated further.

new query G26660T,T22928C,T3565C should catch all of them , count 343

**Comment by Over-There-Is** [comment]
> > *Some sequences have neither G1126A nor G4162A. They should be investigated further.
> 
> new query G26660T,T22928C,T3565C should catch all of them , count 343
> 
> G1162A is not defining of this: <img alt="Screenshot 2024-05-11 alle 15 52 56" width="1175" src="https://private-user-images.githubusercontent.com/87669813/329786277-57eb9fb6-da7d-46d1-97d0-2cba9a4f095e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzU4OTIsIm5iZiI6MTcxNTQzNTU5MiwicGF0aCI6Ii84NzY2OTgxMy8zMjk3ODYyNzctNTdlYjlmYjYtZGE3ZC00NmQxLTk3ZDAtMmNiYTlhNGYwOTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEzNTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYjZkMDg0ZGY1NjNmZTBlMmU0ZTljZDg2MjRmOWMzYzMyZTYwNzg5ZmIwMzk3YzQxZjk2YTYxOTIzZjExZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PoHSFH2Qc2qmPoQM8i99xu-wQGZwawvy6NyeR1-Ys9E"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_334cb_f77170.json?c=gt-nuc_1126&f_userOrOld=uploaded%20sample&gmax=2126&gmin=126&label=id:node_6996795

But some sequences have reversions on 4162 and 3565, but they could still identified by G1126A.

**Comment by aviczhl2** [comment]
377, Germany

**Comment by aviczhl2** [comment]
18/154=12% in Sichuan seqs after 2024-4-1

**Comment by aviczhl2** [comment]
401,Swden, New Zealand

**Comment by aviczhl2** [comment]
@corneliusroemer please designate this one.

**Comment by Over-There-Is** [comment]
Sichuan (from several cities) 29/182
Hubei (from several cities) 51/240
Henan(Hebi) 5/13

**Comment by Over-There-Is** [comment]
covSPECTRUM query: nextcladePangoLineage:JN.1* & T22928C & [1-of: G4162A, G26660T] (423 adopted)

GISAID query: C8293T, T22928C, G26660T (520) + G4162A, C8293T, T22928C, -G26660T(32) + T3565C, G4162A, -C8293T, T22928C, G26660T(1)=553

**Comment by Over-There-Is** [comment]
9% slower than KP* globally, and samples of KP* from China is too few to be compared. But it's still growing much faster than other JN.1*, both in China or aboard.
![2024-05-22 (6)](https://github.com/cov-lineages/pango-designation/assets/38100637/1edb239b-1e20-4359-9e0b-2b8316e15f0a)
![2024-05-22 (7)](https://github.com/cov-lineages/pango-designation/assets/38100637/251bf621-a17f-469d-a88f-764af29df6f3)
![2024-05-22 (8)](https://github.com/cov-lineages/pango-designation/assets/38100637/3f38bf28-d3f7-4ab4-8958-46df1c6d4c40)

**Comment by Over-There-Is** [comment]
Rather than 3565, 6183 or 8393, C8293T is much more stable in sequences (harder to be dropped out).

**Comment by Over-There-Is** [comment]
> covSPECTRUM query: nextcladePangoLineage:JN.1* & T22928C & (C7113C | C7113N) & [1-of: G4162A, G26660T] (422 adopted)
> 
> GISAID query: -C7113T, C8293T, T22928C, G26660T (519) + G4162A, C8293T, T22928C, -G26660T(32) + T3565C, G4162A, -C8293T, T22928C, G26660T(1)=552

Additional GISAID queries:
G1126A, G4162A, C8293T, -T22928C=10 (including the earliest 2 Hongkongese sequences)
G1126A, -G4162A, C8293T, -T22928C, G26660T=1

-C7113T, C8293T, T22928C, G26660T=577
G4162A, C8293T, T22928C, -G26660T=35
T3565C, G4162A, -C8293T, T22928C, G26660T=2

There are no evidence to prove the existence of 22928 dropped-out sequences from non-G1126A branches.
577+35+2+10+1=625

Updated covSPECTRUM query:
NextcladePangoLineage:JN.1* & (C7113C | C7113N) & [1-of: G1126A,T22928C] & [1-of: G4162A,G26660T] =563

**Comment by HynnSpylor** [comment]
for -C7113T, C8293T, T22928C, G26660T: 181/828 in China since Apr 15,2024
I suppose it should be designated as a high prevalence.

**Comment by aviczhl2** [comment]
670 seqs now.  Israel, 

Prevalence in China after 5-1 is 65/259=25%  

@corneliusroemer  this is missed for designation.

**Comment by Over-There-Is** [comment]
-C7113T, C8293T, T22928C, G26660T=844
G4162A, C8293T, T22928C, -G26660T=50
T3565C, G4162A, -C8293T, T22928C, G26660T=2
G1126A, G4162A, C8293T, -T22928C=16
G1126A, -G4162A, C8293T, -T22928C, G26660T=2
Totally 914 now

**Comment by FedeGueli** [comment]
already very big. @corneliusroemer

**Comment by Memorablea** [comment]
@corneliusroemer

**Comment by Over-There-Is** [comment]
881+50+2+16+2=951

**Comment by Over-There-Is** [comment]
963+57+2+17+2=1061
The designation of this branch should no more be delayed.

**Comment by FedeGueli** [comment]
@corneliusroemer designation required here

**Comment by FedeGueli** [comment]
2 FLiRT of this uploaded today from Hong Kong
total 3 ( 1 Anhui, 2 HK)
Query: G26660T, G4162A ,G22599C,G1126A
<img width="1167" alt="Screenshot 2024-06-17 alle 10 19 08" src="https://github.com/cov-lineages/pango-designation/assets/87669813/e744ac11-1f34-4643-bbf8-c01f68a5a28b">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5e3eb_ff05a0.json?c=userOrOld&label=id:node_11491539

**Comment by Mydtlwn** [comment]
@corneliusroemer @FedeGueli

**Comment by Mydtlwn** [comment]
@ryhisner

**Comment by FedeGueli** [comment]
> it's getting further key spike mutations like R346T, A475V, T572I etc.

Also in the NTD: here a recent cluster from Hubei with S:T22N:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_442aa_217ce0.json?label=id:node_7021832
<img width="1169" alt="Screenshot 2024-06-19 alle 02 44 21" src="https://github.com/cov-lineages/pango-designation/assets/87669813/299d3e2c-c1ab-4fec-8f6f-9846a8e4cc98">

**Comment by FedeGueli** [comment]
Flirt went to 4 with a sample from Netherlands. @aviczhl2

**Comment by FedeGueli** [comment]
2 samples from GBW interestingly both coming from Oceania: from Fiji with S:L441F and from NZL

**Comment by Memorablea** [comment]
China +95.7 get S:I794T,3 get S:S31F,1 get S:N282S, S:S680F.

**Comment by FedeGueli** [comment]
> China +95.7 get S:I794T,3 get S:S31F,1 get S:N282S, S:S680F.

@corneliusroemer ping

**Comment by DailyCovidCases** [comment]
This branch should be designated now

**Comment by aviczhl2** [comment]
1170 now,

**Comment by aviczhl2** [comment]
30/120 in Chinese seqs after 6-1, stable at 25%. @corneliusroemer

**Comment by Over-There-Is** [comment]
1197+73+2+18+2=1292

**Comment by aviczhl2** [comment]
1214, Spain

**Comment by Memorablea** [comment]
China+135

**Comment by FedeGueli** [comment]
5 in the FLiRT lin eage with G26660T, G4162A ,G22599C,G1126A, last sample from France

**Comment by aviczhl2** [comment]
> 5 in the FLiRT lineage with G26660T, G4162A ,G22599C,G1126A, last sample from France 8 with G26660T, G4162A ,T22928C,T3565C,G22599C last sample from Arizona

So 2 FLiRTs already?

**Comment by aviczhl2** [comment]
1356, Russia

64/228=28% in Chinese seqs after 6-1.

**Comment by aviczhl2** [comment]
@corneliusroemer  This one seems to be ignored from designation for quite a long time.

**Comment by DailyCovidCases** [comment]
This branch should be designated, one possibility is JN.1.65 or JN.1.66

**Comment by FedeGueli** [comment]
> > 5 in the FLiRT lineage with G26660T, G4162A ,G22599C,G1126A, last sample from France 8 with G26660T, G4162A ,T22928C,T3565C,G22599C last sample from Arizona
> 
> So 2 FLiRTs already?

I have to check i was thinking my query was just not good i'll update later!

**Comment by FedeGueli** [comment]
> G26660T, G4162A ,G22599C,G1126A

checked they are the same FLiRT

**Comment by FedeGueli** [comment]
> This branch should be designated, one possibility is JN.1.65 or JN.1.66

please don't write possible designation numbers because someone could then be fooled finding this issue in the issue instead the correct one so call it JN.1.X please

**Comment by DailyCovidCases** [comment]
1356 seqs now
Is this branch worth to be designated?

**Comment by aviczhl2** [comment]
1479, Sweden, Laos, Switzerland, Germany, Slovenia, 10 with S:R346T, 38 with S:S31F

**Comment by aviczhl2** [comment]
@corneliusroemer

**Comment by DailyCovidCases** [comment]
Tracked in [tracker26a](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=G26660T%2CG4162A%2CT22928C%2CT3565C&nextcladePangoLineage=JN.1*&)

**Comment by Over-There-Is** [comment]
@corneliusroemer

**Comment by aviczhl2** [comment]
1574 seqs now. Italy, Iceland

40 for S:S31F and 11 for S:R346T

**Comment by DailyCovidCases** [comment]
@corneliusroemer This one seems to be ignored from designation for quite a long time

**Comment by FedeGueli** [comment]
> @corneliusroemer This one seems to be ignored from designation for quite a long time

@dailycovidcases consider that each designation means work for all the chain of people involved, Cornelius knows when designating something. If he doesn't he will have his reasons, wrong or right. So until nothing new happens better wait calmly. This is big but not fast. So while i would prefer to see it designated it could happen that designations miss a lineage.

**Comment by aviczhl2** [comment]
1595, Qatar, Israel

**Comment by aviczhl2** [comment]
1632, Denmark and GBW from India

**Comment by aviczhl2** [comment]
1718 seqs, Luxembourg,

**Comment by DailyCovidCases** [comment]
@corneliusroemer This one seems to be ignored from designation for quite a long time

**Comment by FedeGueli** [comment]
> @corneliusroemer This one seems to be ignored from designation for quite a long time

a bit a pity maybe now it is not that relevant even if we have no clear picture of what is happening in China where this had and has a good share @corneliusroemer

**Comment by DailyCovidCases** [comment]
Ping @corneliusroemer rapid designation needed

**Comment by DailyCovidCases** [comment]
Ping @corneliusroemer rapid designation needed

**Comment by DailyCovidCases** [comment]
Why isn't this branch be designated, though it has more than 1700 seqs?

**Comment by DailyCovidCases** [comment]
Ping @corneliusroemer rapid designation needed

**Comment by aviczhl2** [comment]
![image](https://github.com/user-attachments/assets/f52ce63b-3726-4833-b958-3ee88bc3b949)

**Comment by FedeGueli** [comment]
also on Gisaid it represents more than 15% (54/330) of samples collected in or related to China after July 15

**Comment by DailyCovidCases** [comment]
@corneliusroemer suggest to designate some trajectory of this

**Comment by Memorablea** [comment]
For now, I don't think this branch will be specified.Although this branch is very broad.

However, attention should be paid to the emergence and development of noteworthy mutations in the population.

If we can.

**Comment by aviczhl2** [comment]
> For now, I don't think this branch will be specified.Although this branch is very broad.
> 
> However, attention should be paid to the emergence and development of noteworthy mutations in the branch.
> 
> If we can.

Still I think this needs designation. It is very large, and most of the sequences actually come from an underrepresented region (China and around). 

Given its prevalence infection toll can be more than 100 million.

**Comment by Memorablea** [comment]
> > For now, I don't think this branch will be specified.Although this branch is very broad.
> > However, attention should be paid to the emergence and development of noteworthy mutations in the branch.
> > If we can.
> 
> Still I think this needs designation. It is very large, and most of the sequences actually come from an underrepresented region (China and around).
> 
> Given its prevalence infection toll can be more than 100 million.

Yes,you are right.I understand that the epidemic of this disease is very wide.I have also been paying attention to the monthly report of China CDC.In China, we have found too much of this branch.

Of course, I would very much like you to be designated.Because it will help the research further.

**Comment by FedeGueli** [comment]
In August this has been over 30% of samples in Gansu, i think we should designate it. China has two lineages that are leading and co-leading the epidemic there, XDV.1 and this one, being both very different from what we see outside China it would be of special interest to follow them both. more: M:L46F is acquiring more spike mutations.

**Comment by DailyCovidCases** [comment]
I think the branch on https://github.com/cov-lineages/pango-designation/issues/2543 should be designated as well

**Comment by DailyCovidCases** [comment]
At least 1777 seqs now

**Comment by aviczhl2** [comment]
1922 seqs now. GBW from Cayman Islands, 

51 with S:S31F
22 with S:R346T
6 with S:T22N

**Comment by DailyCovidCases** [comment]
@corneliusroemer this branch should be designated as fast as possible

**Comment by FedeGueli** [comment]
Designated JN.1.67 and JN.1.67.1 via https://github.com/cov-lineages/pango-designation/commit/477df9d9f6baf6c4809cebcfcb6c46714fb323ee

**Comment by Memorablea** [comment]
THX

**Comment by Over-There-Is** [comment]
S:F59S, R346T mainly in China: sars-cov-2-variants/lineage-proposals#1971

**Comment by aviczhl2** [comment]
The S31F sub-branch is designated MZ.1
