### ISSUE TITLE
JN.1.18+S:F456V misplaced as JN.1.16.1+S:L456V(109 seqs, 19 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2538]
From branch 37 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253 and https://github.com/sars-cov-2-variants/lineage-proposals/issues/1437

JN.1.18+S:F456V(T22928G)

GISAID query: G22599C, T22928G,C18894T, -6705,-C774T,-25658,-7789
No. of seqs: 5(USA 3 Singapore 1(from Saudi Arabia) Bangladesh 1)

First: EPI_ISL_18851598, Singapore from Saudi Arabia, 2024-1-12
Latest: EPI_ISL_19011021, USA, 2024-3-16

Usher places it in JN.1.16.1(R346T+F456L)+S:L456V (C22928G) . However that means position 22928 has to mutate from T->C->G in a short time, which is highly unlikely. 
@AngieHinrichs @corneliusroemer 

A better explanation shall be JN.1.18(R346T)+S:F456V(T22928G).  

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_18_f456v.json?label=id:node_6971769)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/9630bc3a-3f42-43c7-b0d8-49880b1943e2)

**Comment by FedeGueli** [comment]
Thank you i noticed you havve excluded a couple more of convergent lineages are they among the ones already tracked?

**Comment by FedeGueli** [comment]
> > Thank you i noticed you havve excluded a couple more of convergent lineages are they among the ones already tracked?
> 
> No. They are singlets, one under JN.1.30.1 and another under an undesignated JN,1 branch

thx just checked one is Singlet 6 of # 1089 while the other is unknown till you spotted i will add with credits to the tracking issue

**Comment by FedeGueli** [comment]
7 now two more GBW unknown country samples

**Comment by aviczhl2** [comment]
+1 Canada

**Comment by aviczhl2** [comment]
14, India

**Comment by aviczhl2** [comment]
20, Australia

**Comment by FedeGueli** [comment]
21

**Comment by FedeGueli** [comment]
24 now (+4 with 2 from Qatar ) ping @corneliusroemer

**Comment by FedeGueli** [comment]
31 now  @corneliusroemer i suggest to designate this one.

**Comment by FedeGueli** [comment]
35 now with 4 new sequences coming from New Zealand, i suggest designating it.

**Comment by FedeGueli** [comment]
36 now last from England

**Comment by aviczhl2** [comment]
37, Japan, UK,

**Comment by FedeGueli** [comment]
the fastest FViRT: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?%2FAllSamples%2FPast3M%2Fvariants%3FnextcladePangoLineage=JN.1*&nextcladePangoLineage=JN.1*&nucMutations1=G22599C%2CT22928G%2CC18894T%2CC774C%2C6705A%2C25658C%2C7789T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
43 (+6 California,Illinois, NJ, Queensland, England )

**Comment by FedeGueli** [comment]
59 (5 England  +1 Japan)

**Comment by FedeGueli** [comment]
One of the UK sequences got S:S31Del and two additional spike mutations
Jn.1.18>S:f456V > C13620T > 11749G, T21610C, S:R190S (G22132T),S:E780A (A23901C), C27649T, ORF10:N36S(A29664G)
Query: del21653, C13620T

**Comment by aviczhl2** [comment]
65, South Korea, UAE,

**Comment by FedeGueli** [comment]
83

**Comment by FedeGueli** [comment]
88, designation needed

**Comment by FedeGueli** [comment]
106 in 17 countries + airports samples that i didnt count in countries ,now 
ping @corneliusroemer now also Australia and New Zealand

**Comment by aviczhl2** [comment]
109, Thailand, Peru, Germany, Norway, Brazil

**Comment by FedeGueli** [comment]
+1 Jap

**Comment by aviczhl2** [comment]
Designated JN.1.18.3

**Comment by FedeGueli** [comment]
Jn.1.18.3 via https://github.com/cov-lineages/pango-designation/commit/978a25ac55834715bbb2c9e1fa209aa70e64631b
