### ISSUE TITLE
Proposed north american sublineage of B.1.617.2 with S:V289I , Orf1ab E1633D E1633D and N:G18V

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#254]
Proposal of a sublineage of Delta with:
Orf1ab: E1633D, N:G18V , S:V289I
18000 sequences mainly in USA 
it reached 6% in Florida and it was circulating in the caribbean area
https://outbreak.info/situation-reports?pango=B.1.617.2&muts=S%3AV289I&loc=USA&loc=USA_US-CA&selected=Worldwide&overlay=false
![Schermata 2021-10-16 alle 12 48 45](https://user-images.githubusercontent.com/87669813/137584547-244d3168-6d3a-49ae-8993-98eb012a613e.png)

It seems to have now a trasmission disadvantage (2-3%) on the other circulating strains according to:
https://cov-spectrum.ethz.ch/explore/United%20States/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2%22%2C%22mutations%22%3A[%22S%3A289I%22]%7D%2C%22matchPercentage%22%3A1%7D
![Schermata 2021-10-16 alle 12 55 01](https://user-images.githubusercontent.com/87669813/137584581-32b2688a-bc77-455f-bace-3aec8fb87fae.png)

But it deserves to be designated to monitor diversity in Delta and it could help to avoid misassignements
![Schermata 2021-10-16 alle 12 53 57](https://user-images.githubusercontent.com/87669813/137584590-817488d9-5c6b-45da-bb0a-c712f8eb3e9f.png)

https://nextstrain.org/ncov/gisaid/global?branchLabel=aa&c=gt-S_289&d=tree,entropy,frequencies&f_region=North%20America&p=full&tl=pango_lineage

**Comment by corneliusroemer** [comment]
I support this proposal.

It's clearly related to single outbreak in US, centered on Florida where it reached 15% in June 2021.

Overall in the US it reached 4% and is now still at 2%. It's not really got big anywhere else in the world.

Here are frequency plots from covSPECTRUM and a link: https://cov-spectrum.ethz.ch/explore/United%20States/AllSamples/Past6M/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22S%3A222V%22%2C%22S%3A289I%22]%7D%2C%22matchPercentage%22%3A1%7D

![image](https://user-images.githubusercontent.com/25161793/137590476-d16736c6-06be-4474-8b19-e5899b28b934.png)

![image](https://user-images.githubusercontent.com/25161793/137590478-09db9057-ac11-4ddb-87c2-ffe1c1018d83.png)

This is what a US-focused tree looks like within 21I, the cluster is nice and distinct:
![image](https://user-images.githubusercontent.com/25161793/137590507-5f2600b4-5671-4488-ab3a-314591031a67.png)

https://nextstrain.org/groups/neherlab/ncov/north-america?branchLabel=spike_mutations&c=gt-S_289&label=clade:21I%20%28Delta%29&tl=S1_mutations

Here's a country count including first observation, it's 19k in US and never more than 100 in any other country.
<html><head></head><body>

Country | Total Variant Sequences | First seq. found at | Last seq. found at |  
-- | -- | -- | -- | --
Argentina | 13 | 2021-29 | 2021-35 |  
Austria | 2 | 2021-28 | 2021-28 |  
Belgium | 1 | 2021-32 | 2021-32 |  
Brazil | 5 | 2021-30 | 2021-37 |  
Bulgaria | 2 | 2021-29 | 2021-29 |  
Canada | 14 | 2021-29 | 2021-35 |  
Chile | 4 | 2021-31 | 2021-33 |  
Colombia | 2 | 2021-31 | 2021-34 |  
Costa Rica | 1 | 2021-32 | 2021-32 |  
Croatia | 3 | 2021-32 | 2021-32 |  
Denmark | 5 | 2021-31 | 2021-34 |  
France | 1 | 2021-33 | 2021-33 |  
Germany | 13 | 2021-29 | 2021-40 |  
Iceland | 12 | 2021-30 | 2021-33 |  
Israel | 3 | 2021-26 | 2021-31 |  
Italy | 3 | 2021-34 | 2021-40 |  
Japan | 7 | 2021-30 | 2021-36 |  
Mexico | 13 | 2021-29 | 2021-38 |  
Netherlands | 13 | 2021-28 | 2021-38 |  
Peru | 5 | 2021-32 | 2021-36 |  
Poland | 5 | 2021-34 | 2021-36 |  
Portugal | 4 | 2021-32 | 2021-39 |  
South Africa | 1 | 2021-31 | 2021-31 |  
South Korea | 1 | 2021-35 | 2021-35 |  
Sweden | 3 | 2021-29 | 2021-33 |  
Switzerland | 1 | 2021-33 | 2021-33 |  
United Kingdom | 60 | 2021-29 | 2021-40 |  
United States | 18954 | 2021-17 | 2021-40

</body></html>
