### ISSUE TITLE
JN.1.11 (S:V1104L) got S:R346T being caught multiple times in GBW samples (119) and further gaining S:F59L (17)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2542]
Formerly known as Branch 61 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089

JN.1.11 > S:R346T
Query: G22599C,T3565C,-C7113T,G24872T,G17334T,-T22928C
Samples: 13 

Countries: Australia, India (3 states), Sri Lanka (GBW), US, Wales
IDs:EPI_ISL_18912232, EPI_ISL_18937508, EPI_ISL_18937595,
EPI_ISL_18974099, EPI_ISL_18983800, EPI_ISL_18987776,
EPI_ISL_18994562, EPI_ISL_18998316, EPI_ISL_19000809,
EPI_ISL_19000860, EPI_ISL_19000970, EPI_ISL_19016227,
EPI_ISL_19019176

Tree:
<img width="1165" alt="Screenshot 2024-03-31 alle 18 04 14" src="https://github.com/cov-lineages/pango-designation/assets/87669813/76393e9c-8300-4ce2-8f25-8cfeffcad317">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_313d4_94d180.json?label=id:node_11373385

Three samples from two patient have got S:F59L 
Query for it: G22599C,T3565C,G24872T,T21737C,-C7113T,G24872T,G17334T,-T22928C

**Comment by FedeGueli** [comment]
16 now

**Comment by FedeGueli** [comment]
19 and 5 now

**Comment by FedeGueli** [comment]
28 Now 9 with S:F59L

**Comment by FedeGueli** [comment]
Slowed down

**Comment by aviczhl2** [comment]
There is a further FLiRT sub-branch of this emerging.

**Comment by FedeGueli** [comment]
Reopening for a while

**Comment by FedeGueli** [comment]
119/17

**Comment by FedeGueli** [comment]
This slowly expanded  and now there is a 478T sublineage spotted by @aviczhl2 and  proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/2068

**Comment by xz-keg** [comment]
the R346T+F59L branch is designated JN.1.11.2

**Comment by FedeGueli** [comment]
> the R346T+F59L branch is designated JN.1.11.2

via https://github.com/cov-lineages/pango-designation/commit/608685eef547ed9e65a36dd2f7030268e60f7511
