### ISSUE TITLE
JN.1.39+S:F456L mostly misplaced under JN.1.16 (456 seqs, 250 with S:R346T(designated JN.1.39.1), 16 with S:T572I and S:478Q)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2543]
From branch 11 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253

JN.1.39+T22928C(S:F456L)

GISAID query: G2782T,T22926C,T22928C,-T111C,-23601,-C1594T,-26873, -10369
GISAID query for S:T572I, K478Q branch: C6781T, C12733T,C23277T (By @FedeGueli )
No. of seqs: 43( Germany 2 China 1 Japan 1 USA 39(1 from Japan, 1 from Switzerland, 1 from UAE)

First: EPI_ISL_18695414, USA, 2023-12-16
Latest: EPI_ISL_19005864, Japan, 2024-3-13

Mostly misplace as JN.1.16+G2782T, as S:F456L(T22928C) is much more of a convergent mutation than G2782T this shall be JN.1.39+S:F456L(T22928C).  Seqs placed on other branches are excluded, maybe recombs. 

@AngieHinrichs @corneliusroemer 

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_39_f456l.json?f_userOrOld=uploaded%20sample&label=id:node_7026585)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/335d0405-ad18-433c-a143-fddcc34f80ba)

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by aviczhl2** [comment]
57, Canada,Australia

**Comment by aviczhl2** [comment]
68, Ireland

**Comment by FedeGueli** [comment]
it has now a **FLiRS** branch of 2 
[JN.1.16> G2782T ] = JN.1.39 >  S:F456L > S:R346S (A22600C), T25054C
Query: G2782T,T3565C,A22600C, T25054C

<img width="1173" alt="Screenshot 2024-05-01 alle 23 01 29" src="https://github.com/cov-lineages/pango-designation/assets/87669813/153c5f42-547b-44ca-b161-fe1ab15509dd">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_1b8fb_26cb10.json?c=userOrOld&label=id:node_11429162


Note that there is another likely misplaced JN.1.39 with S:S346S but this time it is anticipated by S:S31F and it chould not be the same lineage of the one found here even if there is Geographical contiguity (US):
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1cd44_2abef0.json?label=id:node_6934825
<img width="1171" alt="Screenshot 2024-05-01 alle 23 05 44" src="https://github.com/cov-lineages/pango-designation/assets/87669813/de172530-ef1c-4505-9577-2ce03b8cfe49">
<img width="1163" alt="Screenshot 2024-05-01 alle 23 05 58" src="https://github.com/cov-lineages/pango-designation/assets/87669813/5acd20f1-3f90-412c-a76f-53650e6c46d4">

**Comment by aviczhl2** [comment]
96, Singapore

**Comment by aviczhl2** [comment]
The R346T sub-branch is designated JN.1.39.1

**Comment by aviczhl2** [comment]
The 21034 shall also be part of this branch. The S:R346T branch is designated JN.1.39.1.

**Comment by AngieHinrichs** [comment]
I did a force move so the branch with USA/NY-CDC-LC1094418/2024 is now JN.1.39 > T22928C (S:F456L), so far matOptimize left it there.

**Comment by aviczhl2** [comment]
265 seqs now.

**Comment by FedeGueli** [comment]
308

**Comment by DailyCovidCases** [comment]
Branch 11 designated JN.1.39.a.b = LZ.b

**Comment by FedeGueli** [comment]
> Branch 11 designated JN.1.39.a.b = LZ.b

what do you mean?

**Comment by FedeGueli** [comment]
the tree looks like this now:
<img width="1173" alt="Screenshot 2024-06-20 alle 11 06 57" src="https://github.com/cov-lineages/pango-designation/assets/87669813/59768cdd-7da7-48ca-8b3c-ef3623214ffc">
the top branch is JN.1.39.1

the bottom one is still undesignated .

Interestingly it got S:T572I and S:T478Q
<img width="1175" alt="Screenshot 2024-06-20 alle 11 07 48" src="https://github.com/cov-lineages/pango-designation/assets/87669813/802b3d2e-dbd4-4a73-9cfe-6fee79f5359b">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_41918_3ecf40.json?f_userOrOld=uploaded%20sample&label=id:node_12184780

So i suggest @aviczhl2 to modify the query to: **G2782T,T22926C,T22928C,-G22599C,-T111C,-23601,-C1594T,-26873, -10369**

and adding two sublineages to the proposal:
JN.1.39 > S:F456L (T22928C) > orf1b:T634I (C15368T) > C6781T, C12733T, S:T572I C23277T, C24157T > 
Query :C6781T, C12733T,C23277T
Samples: 9 ( 7 with S:T478Q and 2 with S:G213R)
<img width="1109" alt="Screenshot 2024-06-20 alle 11 12 47" src="https://github.com/cov-lineages/pango-designation/assets/87669813/b2f791e5-cbaf-463c-894c-4898df402035">

And
JN.1.39> S:F456L (T22928C) > S:R346S (A22600C), T25054C
Query: A22600C, T25054C
Samples: 7

**Comment by DailyCovidCases** [comment]
304 seqs, the tree looks like this now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3242b_68cdd0.json?f_userOrOld=uploaded%20sample)
![Screenshot (126)](https://github.com/cov-lineages/pango-designation/assets/92421581/94070044-2308-4166-835c-8a92219de961)

**Comment by FedeGueli** [comment]
Another sublineage of this has emerged this time in Portorico:
#2543>> G29134A > Orf1a:T1168I (C3768T), A9337G, S:N641T (A23484C)
Query:C3768T, A9337G
Samples: 15
<img width="1130" alt="Screenshot 2024-07-01 alle 07 31 08" src="https://github.com/cov-lineages/pango-designation/assets/87669813/d2ddcab7-4b86-4c29-ba93-b9e60300bd34">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice17_genome_test_1041f_236200.json?label=id:node_7155768

**Comment by DailyCovidCases** [comment]
332 seqs now, this branch worth to be designated

**Comment by DailyCovidCases** [comment]
332 seqs now
Is this branch worth to be designated?

**Comment by DailyCovidCases** [comment]
368 seqs now
Is this branch worth to be designated?

**Comment by DailyCovidCases** [comment]
379 seqs now
Tracked in [tracker11](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=G2782T%2CT22926C%2CT22928C&nextcladePangoLineage=JN.1.39*&)

**Comment by DailyCovidCases** [comment]
@corneliusroemer

**Comment by DailyCovidCases** [comment]
404 seqs now
@corneliusroemer This one seems to be ignored from designation for quite a long time

**Comment by aviczhl2** [comment]
It seems that seqs outside JN.1.39.1 is close to stopped growing. Close this.

**Comment by DailyCovidCases** [comment]
@corneliusroemer This one seems to be ignored from designation for quite a long time

**Comment by DailyCovidCases** [comment]
482 seqs now

**Comment by aviczhl2** [comment]
Re-open it to track the 456L-572I-478Q sub-branch

**Comment by DailyCovidCases** [comment]
Ping @corneliusroemer rapid designation needed

**Comment by DailyCovidCases** [comment]
Ping @corneliusroemer rapid designation needed

**Comment by DailyCovidCases** [comment]
Ping @corneliusroemer rapid designation needed

**Comment by DailyCovidCases** [comment]
Why isn't this branch be designated, though it has nearly 500 seqs?

**Comment by FedeGueli** [comment]
> Why isn't this branch be designated, though it has nearly 500 seqs?

sometimes a branch can being not designated even if it is quite big, likely if there is no fast offspring even if it is 500 or even it was 1000 but slowing down it won't be designated.

**Comment by DailyCovidCases** [comment]
![Screenshot (163)](https://github.com/user-attachments/assets/d55d2792-f33e-4ef2-a993-26a9908d422c)
@corneliusroemer In some countries, some of the "JN.1" (yellow bar) can belong to this branch. So I think this branch shall get designated to distinguish from vanilla JN.1.
Example: 
https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/covid-19/documents/bulletin-national/covid-19-en-france.-point-au-7-aout-2024
https://covid.cdc.gov/covid-data-tracker/#variant-proportions

**Comment by DailyCovidCases** [comment]
@corneliusroemer suggest to designate some trajectory of this.

**Comment by DailyCovidCases** [comment]
@corneliusroemer suggest to designate some trajectory of this

**Comment by DailyCovidCases** [comment]
How many seqs in this branch now? Please update it

**Comment by DailyCovidCases** [comment]
I think this branch should be designated as soon as possible

**Comment by aviczhl2** [comment]
It seems that the T572I-478Q branch has also stopped growing. Close down.

**Comment by DailyCovidCases** [comment]
Now 508 seqs

**Comment by DailyCovidCases** [comment]
Now 508 seqs
@corneliusroemer In France, some of the "JN.1" (yellow bar) can belong to this branch. So I think this branch shall get designated to distinguish from vanilla JN.1.
https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/covid-19/documents/bulletin-national/covid-19-en-france.-point-au-7-aout-2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1abbb_aaf00.json?f_userOrOld=uploaded%20sample)
![Screenshot (163)](https://github.com/user-attachments/assets/70c8e9d6-42de-430f-b9bd-9a3fceb64fdf)
![Screenshot (173)](https://github.com/user-attachments/assets/bc938f5e-5585-4ff7-98e1-7276e8294f37)
![Screenshot (174)](https://github.com/user-attachments/assets/bb526bfa-9d71-40a0-a574-df04f95dd70d)

**Comment by DailyCovidCases** [comment]
Now 509 seqs, this branch is not dead, but the upload speed is obviously very slow

**Comment by DailyCovidCases** [comment]
Designated JN.1.39.something

**Comment by DailyCovidCases** [comment]
513 seqs now, 2 new sample from USA and Sweden

**Comment by FedeGueli** [comment]
Interestingly 3/10 of the ost recent samples of it are from the Trio sublineage with S:K478Q 
New Query: C6781T,C24157T, C15368T,C12733T
Samples: 19
countries : 5
tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4f14d_b8fe90.json?label=id:node_7234738
<img width="1163" alt="Screenshot 2024-08-25 alle 22 21 11" src="https://github.com/user-attachments/assets/03e66218-2bba-490a-a4aa-e2a5629b1d1a">

Even if it has low chance to compete: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?%2FAllSamples%2FPast3M%2Fvariants%3FnextcladePangoLineage=JN.1*&nextcladePangoLineage=KP.3*&nucMutations1=C6781T%2CC24157T%2CC15368T%2CC12733T&analysisMode=CompareToBaseline& 
i would consider to rearrange the proposal around it

**Comment by DailyCovidCases** [comment]
@aviczhl2 Now 520 seqs, please update the title

**Comment by FedeGueli** [comment]
> @aviczhl2 Now 520 seqs, please update the title

it is 204 see the comments above . cc @corneliusroemer

**Comment by DailyCovidCases** [comment]
> > @aviczhl2 Now 520 seqs, please update the title
> 
> it is 205 see the comments above . cc @corneliusroemer correct query is G2782T,T22926C,T22928C,-G25647T,-C23039G,-G24872T,-T6913C,-G22599C,-T111C,-23601,-C1594T,-26873, -10369

I think this branch should be designated ping @corneliusroemer

**Comment by FedeGueli** [comment]
206

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3cb32_938740.json?c=pango_lineage&f_userOrOld=uploaded%20sample)
![Screenshot (210)](https://github.com/user-attachments/assets/768f0847-a811-4598-929b-3c94a59c55a1)
ping @corneliusroemer worth a designation this one

**Comment by FedeGueli** [comment]
G2782T,T22926C,T22928C,-G25647T,-C23039G,-G24872T,-T6913C,-G22599C,-T111C,-23601,-C1594T,-26873, -10369 finds 220  circulating in August at low levels in Hubei with further S:S31F

25 with 478Q using C6781T,C24157T, C15368T,C12733T  with a Louisiana cluster that added S:S256L

**Comment by DailyCovidCases** [comment]
@corneliusroemer This branch should be designated

**Comment by FedeGueli** [comment]
> @corneliusroemer This branch should be designated

one only sample from September
