### ISSUE TITLE
LB.1 (JN.1.9 + FLiRT) with S:S31del (339) with a singlet with S:A475V (this subbranch spotted by @hynnspylor)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2546]
Formerly known as Branch 62 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089

**Edited after LB.1 designation**

LB.1 [JN.1.9 > S:R346T(G22599C) > S:F456L (T22928C)] > S:S31del (21653-21655del) [Edited thx to @aviczhl2 adding the deletion at S:S31del]
Query for LB.1 FLiRT : G22111T , G22599C , T22928C,T3565C finds 7 but Usher displays 11 sequences  ( plus two misplaced, on the top with 183Q REV)
Query for Flirt S:S31Del: G22599C, T22928C, T3565C, del21653, G22111T 
Tree:
<img width="1156" alt="Screenshot 2024-04-03 alle 11 25 54" src="https://github.com/cov-lineages/pango-designation/assets/87669813/55c6eb44-2e83-4f8e-8ac5-c23e09d9d065">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice6_genome_test_3acf3_d18670.json?label=id:node_6949186
Samples : 11 
<img width="361" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/87669813/7eeffc96-e37f-418a-8f3e-bf796e8f27c3">
Countries: 5
<img width="279" alt="Screenshot 2024-04-03 alle 11 28 40" src="https://github.com/cov-lineages/pango-designation/assets/87669813/cea3a949-6ce4-4596-9648-a6e2c1032563">

@HynnSpylor spotted one sublineage uploaded on 05/07 with S:A475V
Query: C22986T, C28957T,del21653, G22111T 
Samples: 1 (GBW)

**Comment by FedeGueli** [comment]
+1 France @corneliusroemer i suggest rapid designation of this one.

**Comment by FedeGueli** [comment]
> This branch also has S:S31del.

Thank you @aviczhl2 , i ve completely missed that. that is a good remainder that when  transferring branches, usually found very early, to re check mutations/Deletions .

**Comment by FedeGueli** [comment]
13 total 10 with S:S31del

**Comment by FedeGueli** [comment]
+1

**Comment by FedeGueli** [comment]
Designated JN.1.9.2 and LB.1 from https://github.com/cov-lineages/pango-designation/commit/b51c68c051f7d07ab0459f2ffb67b41d7e8528d3

**Comment by FedeGueli** [comment]
Big jump of the S:S31Del branch that went to 22 with 8 samples uploaded on April 19:
3 from NYC the remaining five from GBW airport surveillance from 3 different countries France, India and Japan,
@corneliusroemer i suggest to designate it ( or to broaden LB.1 to S:S31Del being 22 out of 26 LB.1

**Comment by FedeGueli** [comment]
There maybe a sub-branch of this that is misplaced in LB.1 but it has the S:Q183Q reversion:
Query: G17562T, G22599C , T22928C,T3565C
Tree:
<img width="1171" alt="Screenshot 2024-04-23 alle 12 52 09" src="https://github.com/cov-lineages/pango-designation/assets/87669813/d23660f9-3fea-4c4e-936f-5323827be65f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice5_genome_test_62fd1_778280.json?label=id:node_6962416
It also could be that the reversion is real maybe due a micro inter JN.1 Recombination

**Comment by FedeGueli** [comment]
The LB.1 plus S:S31F is now 25 from 9 different countries including Pakistan, Qatar, India, Taiwan, Japan , France, Australia, Canada, US.

**Comment by aviczhl2** [comment]
> There maybe a sub-branch of LB.1 that is misplaced in LB.1 but it has the S:Q183Q reversion: Query: G17562T, G22599C , T22928C,T3565C Tree: <img alt="Screenshot 2024-04-23 alle 12 52 09" width="1171" src="https://private-user-images.githubusercontent.com/87669813/324802646-d23660f9-3fea-4c4e-936f-5323827be65f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzY3NTMsIm5iZiI6MTcxMzg3NjQ1MywicGF0aCI6Ii84NzY2OTgxMy8zMjQ4MDI2NDYtZDIzNjYwZjktM2ZlYS00YzRlLTkzNmYtNTMyMzgyN2JlNjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEyNDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZmM4NDczOGJjZGVlNjVjM2MyZDRkOTRiMGJjYzVjYmU3MzNhOTU2NjEyZjA1ZTM4OWFjYmViZTg2ODhjZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4npJSSoGrNQIe4UuYpRLJAIA3JYkHj8ic1b8VdMLXH0"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice5_genome_test_62fd1_778280.json?label=id:node_6962416 It also could be that the reversion is real maybe due a micro inter JN.1 Recombination cc @AngieHinrichs

That's the 17562 branch with Filrt. See branch 62 of #1253

**Comment by FedeGueli** [comment]
> > There maybe a sub-branch of LB.1 that is misplaced in LB.1 but it has the S:Q183Q reversion: Query: G17562T, G22599C , T22928C,T3565C Tree: <img alt="Screenshot 2024-04-23 alle 12 52 09" width="1171" src="https://private-user-images.githubusercontent.com/87669813/324802646-d23660f9-3fea-4c4e-936f-5323827be65f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzY3NTMsIm5iZiI6MTcxMzg3NjQ1MywicGF0aCI6Ii84NzY2OTgxMy8zMjQ4MDI2NDYtZDIzNjYwZjktM2ZlYS00YzRlLTkzNmYtNTMyMzgyN2JlNjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEyNDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZmM4NDczOGJjZGVlNjVjM2MyZDRkOTRiMGJjYzVjYmU3MzNhOTU2NjEyZjA1ZTM4OWFjYmViZTg2ODhjZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4npJSSoGrNQIe4UuYpRLJAIA3JYkHj8ic1b8VdMLXH0"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice5_genome_test_62fd1_778280.json?label=id:node_6962416 It also could be that the reversion is real maybe due a micro inter JN.1 Recombination cc @AngieHinrichs
> 
> That's the 17562 branch with Filrt. See branch 62 of #1253

ahha yeah i ve forgot that!

**Comment by FedeGueli** [comment]
+2 Canada , US: going up very quickly

**Comment by FedeGueli** [comment]
29 +2 Australia, it seems really fast i have it as the fastest in my list of designated/undesignated lineages: @corneliusroemer is it possible to designate from a deletion only?

**Comment by AngieHinrichs** [comment]
> is it possible to designate from a deletion only?

Unless the pangolin tool were upgraded to use some method other than usher,
it would not be able to recognize a deletion-only lineage because deletions
are invisible to usher.

**Comment by FedeGueli** [comment]
> is it possible to designate from a deletion only?
> Unless the pangolin tool were upgraded to use some method other than usher, it would not be able to recognize a deletion-only lineage because deletions are invisible to usher.

Thank you @AngieHinrichs , being around 3/5 of LB.1 if it is faster than parental it won't take much time to be a vast mayority of it so LB.1 will be a proxy good enough for it. @corneliusroemer should i close this issue then?

**Comment by FedeGueli** [comment]
35 now out of 42 total LB.1 samples

**Comment by AngieHinrichs** [comment]
> 35 now out of 42 total LB.1 samples

I don't know if the assembly pipelines have improved in this regard, but at least earlier in the pandemic, that's close to the ratio of sequences in which a deletion was correctly assembled.  I.e. some of the samples that appeared not to have a deletion might actually have a deletion, but the assembly pipeline filled in NNNNs or reference bases.

**Comment by FedeGueli** [comment]
> > 35 now out of 42 total LB.1 samples
> 
> I don't know if the assembly pipelines have improved in this regard, but at least earlier in the pandemic, that's close to the ratio of sequences in which a deletion was correctly assembled. I.e. some of the samples that appeared not to have a deletion might actually have a deletion, but the assembly pipeline filled in NNNNs or reference bases.

Yeah very likely!

**Comment by FedeGueli** [comment]
42/50 now with S:31Del

**Comment by aviczhl2** [comment]
98 now

**Comment by FedeGueli** [comment]
> 98 now

103

**Comment by FedeGueli** [comment]
It seems impossible to designate from a deletion so not sure how much i would keep this open , note that is the fastest lineages since weeks.

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by FedeGueli** [comment]
@corneliusroemer @AngieHinrichs being that 800/900 of LB.1 sequences have S:S31del it could be added to its defining mutations as happened with KP.2.3 ??
