### ISSUE TITLE
JN.1.48+S:F456L branches, one designated JN.1.48.1 and LD.1, the other with Orf3a:S60F (43 seqs, 13 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2547]
From branch 50 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253

There a very recent FLiRT+S:S60P lineage growing very rapidly. After some investigation it seems quite complex. 

JN.1+T18471C+C25688T(Orf3a:A99V)+T3913A+C8092T, T21740C, G22599C, C25378T(S:S60P,R346T) +T22928C(S:F456L)

GISAID query: C25378T, G22599, C8092, T21740
No. of seqs: 6(USA 5(2 from India), UK 1)

First: EPI_ISL_18874336, 2024-1-24, USA-TX
Latest: EPI_ISL_19028035, 2024-3-22, USA-CA

GISAID query for S:F456L branch: C25378T, G22599, T22928,C8092 (5 seqs)
GISAID query for FLIRT branch: C25378T, G22599, T22928,C8092,C23277T (1 seq)

Above S:F456L branch--JN.1+Orf3a:S60F

Breakpoint between 22929 and 25377

C25378T, C25688T reverted in exchange for C25571T(Orf3a:S60F)
Many JN.1* branches have C25571T so unable to decide the precise branch.
Additional mutation: C5547T(Orf1a: T1761I), private mutation

This can also be separate S:F456L emergence under JN.1.48.

GISAID query: C25571T, C8092T,T22928C 
No. of seqs: 2(USA-GBW baseline survellience)

EPI_ISL_19019175, 19028032, 2024-3-21

Due to the complexity, usher isn't showing the correct mutation order.  
The bottom is the recomb and the upper is the main branch.
@AngieHinrichs 

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_s60p_r346t_f456l.json?label=id:node_6971728)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/15411c56-46c4-4d15-9c5d-99f3a402aab1)

**Comment by FedeGueli** [comment]
thanks for the analysis!

**Comment by aviczhl2** [comment]
+1 India local

**Comment by FedeGueli** [comment]
> +1 USA +1 Australia There is a S:T572I FLIRT USA seq on this branch.

Query for Trio : C23277T,C25378T, T3913. (the US sample has T3913W)

**Comment by aviczhl2** [comment]
13, Netherlands

**Comment by FedeGueli** [comment]
> C25378T, G22599, T22928,C8092,C23277T

it seems very fast to me.

**Comment by FedeGueli** [comment]
Designated JN.1.48.1 via https://github.com/cov-lineages/pango-designation/commit/67f48bf24283999f1940f3aee8159f404124ff3f

**Comment by aviczhl2** [comment]
> Designated JN.1.48.1 via [67f48bf](https://github.com/cov-lineages/pango-designation/commit/67f48bf24283999f1940f3aee8159f404124ff3f)

That's a quite ambigious desgination.

**Comment by FedeGueli** [comment]
> > Designated JN.1.48.1 via [67f48bf](https://github.com/cov-lineages/pango-designation/commit/67f48bf24283999f1940f3aee8159f404124ff3f)
> 
> That's a quite ambigious designation. Does it refers to S:R346T branch, F456L further-branch, or the recomb with Orf3a: 60 instead of Orf3a:99? @corneliusroemer
> 
> Also calling @AngieHinrichs to fix the tree here. Here a recombinant is disrupting the placement of non-recombinants.

after orf3a:A99V according to the line of lineage notes

**Comment by corneliusroemer** [comment]
unclear by nature of the lack of sequences so far, we'll see when more sequences come in

**Comment by AngieHinrichs** [comment]
The red circles here are designated sequences from lineages.csv and they clearly indicate this branch that has both R346T and F456L as well as two other mutations (it is downstream of the node with ORF3a:A99V):
<img width="544" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/186983/0a7acf75-0a78-4ac5-b4b9-928366422116">



> Also calling @AngieHinrichs to fix the tree here. Here a recombinant is disrupting the placement of non-recombinants.

I don't see the problem -- can you give examples of sequence names that you think are in the wrong place?  I see that there is a reversion on ORF3a:A99V in the two USA/VA-GBW sequences, and a reversion on C22928T (S:L456F) in 3 India sequences, but I don't see a way to get something better with a parsimony tree.

**Comment by aviczhl2** [comment]
> The red circles here are designated sequences from lineages.csv and they clearly indicate this branch that has both R346T and F456L as well as two other mutations (it is downstream of the node with ORF3a:A99V): <img alt="image" width="544" src="https://private-user-images.githubusercontent.com/186983/322951322-0a7acf75-0a78-4ac5-b4b9-928366422116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyOTk5NTMsIm5iZiI6MTcxMzI5OTY1MywicGF0aCI6Ii8xODY5ODMvMzIyOTUxMzIyLTBhN2FjZjc1LTBhNzgtNGFjNS1iNGI5LTkyODM2NjQyMjExNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQyMDM0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTFmODhhZDYwZGFiYzYyY2FlOGQzMTc4MmRmMTA4MjY5MzFiOGVlNjdiZDhiY2U2Njk0NTBmNDgyNjU5ZTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6P-K_E-uALtQr_N5oJZtH2vWGXDK0qfbI4ZBaXw3H0o">
> 
> > Also calling @AngieHinrichs to fix the tree here. Here a recombinant is disrupting the placement of non-recombinants.
> 
> I don't see the problem -- can you give examples of sequence names that you think are in the wrong place? I see that there is a reversion on ORF3a:A99V in the two USA/VA-GBW sequences, and a reversion on C22928T (S:L456F) in 3 India sequences, but I don't see a way to get something better with a parsimony tree.

Some have S:L456F reversion.

**Comment by aviczhl2** [comment]
The usher tree alters to be correct now, and the designation of JN.1.48.1 becomes buggy. 
@corneliusroemer 

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice20_genome_test_532d7_872c60.json?label=id:node_6982641)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/c1cbecdc-a9b2-4316-9481-24baf261114b)

**Comment by aviczhl2** [comment]
> The usher tree alters to be correct now, and the designation of JN.1.48.1 becomes buggy. (Only includes the recomb described in this issue) 

@corneliusroemer
> 
> [usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice20_genome_test_532d7_872c60.json?label=id:node_6982641)
> 
> ![image](https://private-user-images.githubusercontent.com/10445944/325142020-c1cbecdc-a9b2-4316-9481-24baf261114b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDc2MjcsIm5iZiI6MTcxMzk0NzMyNywicGF0aCI6Ii8xMDQ0NTk0NC8zMjUxNDIwMjAtYzFjYmVjZGMtYTliMi00MzE2LTk0ODEtMjRiYWYyNjExMTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA4Mjg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYWRkMTdkOWZlY2ExYmM3MTE4MjVlMmZiODNmYWJkZTNjODBjNzBhYTMxMzkzZTVjNjNjZGM3NzQ3NWI0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.irSQ1HawUbNoLBK1KwHkCmgP3L_kzmJ7ej0WaYZuM1I)



> The usher tree alters to be correct now, and the designation of JN.1.48.1 becomes buggy. @corneliusroemer
> 
> [usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice20_genome_test_532d7_872c60.json?label=id:node_6982641)
> 
> ![image](https://private-user-images.githubusercontent.com/10445944/325142020-c1cbecdc-a9b2-4316-9481-24baf261114b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDc2MjcsIm5iZiI6MTcxMzk0NzMyNywicGF0aCI6Ii8xMDQ0NTk0NC8zMjUxNDIwMjAtYzFjYmVjZGMtYTliMi00MzE2LTk0ODEtMjRiYWYyNjExMTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA4Mjg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYWRkMTdkOWZlY2ExYmM3MTE4MjVlMmZiODNmYWJkZTNjODBjNzBhYTMxMzkzZTVjNjNjZGM3NzQ3NWI0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.irSQ1HawUbNoLBK1KwHkCmgP3L_kzmJ7ej0WaYZuM1I)

**Comment by aviczhl2** [comment]
> Already asked to @AngieHinrichs it should be fixed.

The usher tree is correct now. The designation needs to be fixed.

**Comment by FedeGueli** [comment]
> > Already asked to @AngieHinrichs it should be fixed.
> 
> The usher tree is correct now. The designation needs to be fixed.

but the designation is this one: JN.1.48.1	Alias of B.1.1.529.2.86.1.1.48.1, S:S60P, S:R346T, S:F456L, after ORF3a:A99V so it should be ok isn it?

**Comment by FedeGueli** [comment]
in the mean while second sequence with FLiRTrio (346T 456L 572I) for this one

**Comment by AngieHinrichs** [comment]
@corneliusroemer There are 3 designated sequences for JN.1.48.1 that (according to the UShER tree so they might have N at 22928?) do not have S:F456L:
```
India/MH_BJCOG_6494/2024|EPI_ISL_19032849|2024-02-22
India/MH_BJCOG_INSACOG_6562/2024|EPI_ISL_19033124|2024-03-02
USA/TX-HMH-M-138364/2024|EPI_ISL_18874336|2024-01-24
```

**Comment by aviczhl2** [comment]
> but the designation is this one: JN.1.48.1 Alias of B.1.1.529.2.86.1.1.48.1, S:S60P, S:R346T, S:F456L, after ORF3a:A99V so it should be ok isn it?

It now only includes the recombinant branch of 3 seqs.

**Comment by FedeGueli** [comment]
> > but the designation is this one: JN.1.48.1 Alias of B.1.1.529.2.86.1.1.48.1, S:S60P, S:R346T, S:F456L, after ORF3a:A99V so it should be ok isn it?
> 
> It now only includes the recombinant branch of 3 seqs.

You mean only three sequences added? Cause the commit  and the lineages note are both correct.

**Comment by FedeGueli** [comment]
> in the mean while second sequence with FLiRTrio (346T 456L 572I) for this one

3 now
<img width="1163" alt="Screenshot 2024-04-25 alle 23 29 38" src="https://github.com/cov-lineages/pango-designation/assets/87669813/9a466077-1048-4910-9137-ff6aec173cbf">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_471cf_abe240.json?f_userOrOld=uploaded%20sample&label=id:node_6982025&s=hCoV-19/USA/MA-CDC-LC1103020/2024%7CEPI_ISL_19070143%7C2024-04-06

**Comment by aviczhl2** [comment]
> > > but the designation is this one: JN.1.48.1 Alias of B.1.1.529.2.86.1.1.48.1, S:S60P, S:R346T, S:F456L, after ORF3a:A99V so it should be ok isn it?
> > 
> > 
> > It now only includes the recombinant branch of 3 seqs.
> 
> You mean only three sequences added? Cause the commit and the lineages note are both correct.

It is only 3 on usher now. 
It was ill-defined at that time(falsely includes wrong things because of wrong tree), and the tree changes to be correct after designation, so the designation doesn't fit the correct tree now.

**Comment by FedeGueli** [comment]
JN.1.48.1 plus S:T572I is now 5, please re-arrange the proposal to highlight it, 

<img width="1160" alt="Screenshot 2024-05-02 alle 09 57 30" src="https://github.com/cov-lineages/pango-designation/assets/87669813/88bb3c85-3acb-4758-8917-7eeebb11168b">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice10_genome_test_2243_340e10.json?label=id:node_6989022

About the route of JN.1.48.1 i think now it is correct:
JN.1>>  T18471C > G29134T > Orf3a:A99V (C25688T) > T3913A > C8092T, S:S60P (T21740C), C25378T > S:S346T (G22599C) > S:f456L (T22928C) > S:T572I  (C23277T )

**Comment by FedeGueli** [comment]
T572I branch  now at 6

**Comment by FedeGueli** [comment]
FLIRT>TRIO BRANCH now tops  7

**Comment by FedeGueli** [comment]
Trio >> 8

**Comment by FedeGueli** [comment]
Recomb now 12

**Comment by aviczhl2** [comment]
The recombinant is now 16 seqs in France, USA. South Africa, and GBW from Germany and Fiji.

**Comment by FedeGueli** [comment]
26

**Comment by aviczhl2** [comment]
Spain, Mexico, Jamaica and New Zealand for the recomb

**Comment by aviczhl2** [comment]
@corneliusroemer  suggest to designate the recomb here. 26 seqs from 9 countries now.

**Comment by FedeGueli** [comment]
> C25571T, C8092T,T22928C

agree two samples in the last GBW batch from two countries both undersampled ones.

**Comment by aviczhl2** [comment]
28,Canada

**Comment by aviczhl2** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/36128bc8-cd7c-4e51-a100-33f0fd4b114b)

Currently usher explains them as two separate S:F456L emergence of JN.1.48. That could be possible and hence recomb may not be the only explanation.

**Comment by aviczhl2** [comment]
43, Netherlands, Ecuador, Australia

**Comment by FedeGueli** [comment]
The orf3a:S60F Designated JN.1.48.3 via https://github.com/cov-lineages/pango-designation/commit/3c532568a646b7b3533ab20b369bd0a75050877a
