### ISSUE TITLE
JN.1.1.6 (456L) got S:346T (FLiRT spotted first by @Krosa1910, 10 Sequences ) and then S:T572I (TRIO)  in South Australia (5)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2548]
Formerly known as  Branch 56 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089 sublineage of JN.1.1.6
**this was first spotted by @Krosa1910** 
Defining mutations
JN.1.1.6 (C11747T > S:F456L=T22928C) > Orf1b:V1092F (G16741T) > S:R346T (G22599C)
Query : G16741T,G22599C, C11747T ,T22928C
Samples: 10 UK US Australia
IDs:EPI_ISL_18913301, EPI_ISL_18941884, EPI_ISL_18965272,
EPI_ISL_18965335, EPI_ISL_18969267
Then emerged a  **S:T572I sublineage**
JN.1.1.6 (C11747T > S:F456L=T22928C) > Orf1b:V1092F (G16741T) > S:R346T (G22599C)>Orf1a:L1546I (C4901A),S:T572I (C23277T)
Query: G16741T,C4901A,C23277T
Samples: 5 South Australia
EPI_ISL_19028189, EPI_ISL_19028240, EPI_ISL_19028247,
EPI_ISL_19028277, EPI_ISL_19028287

Tree:
<img width="1148" alt="Screenshot 2024-04-03 alle 12 09 15" src="https://github.com/cov-lineages/pango-designation/assets/87669813/871f3018-17d4-460b-abca-37488d84c264">
<img width="1127" alt="Screenshot 2024-04-03 alle 12 09 34" src="https://github.com/cov-lineages/pango-designation/assets/87669813/285a1780-ea3b-4663-b90a-00a048829fb2">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_3acf3_d18660.json?c=gt-S_346,572&gmax=25384&gmin=21563&label=id:node_11377197

**Comment by aviczhl2** [comment]
Designated KZ.1.1 and KZ.1.1.1

**Comment by FedeGueli** [comment]
KZ.1.1 and KZ.1.1.1 via https://github.com/cov-lineages/pango-designation/commit/13431047d046233f6e1558a876a7f1d1ed58b1fd

**Comment by FedeGueli** [comment]
KZ.1.1.1 Trio got now also S:S680P 
<img width="1143" alt="Screenshot 2024-05-07 alle 14 48 35" src="https://github.com/cov-lineages/pango-designation/assets/87669813/4f5181a2-1ee3-4855-9db2-5527e8523654">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_34e78_a0dca0.json?label=id:node_11435275
