### ISSUE TITLE
JN.1+C4777T+S:F456L(84 seqs, 16 countries) with S:R346T(36 seqs) and S:R346I( 20 seqs) misplaced under JN.1.16 and JN.1.16.1

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2555]
From branch 46 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253

JN.1+C4777T+T22928C(S:F456L)+G22599C(S:R346T)/G22599T(S:R346I)

This is a lineage with serious usher misplacement issue.  C4777T shouldn't be a convergent mutation, however S:456L and S:346T/I are very convergent, everything with C4777T shall belong to the same branch of JN.1+C4777T. 

There are 3 misplacements for this lineage @AngieHinrichs @corneliusroemer 
1: Usher misplaces JN.1+C4777T+S:F456L as JN.1.16+C4777T
2: Usher misplaces JN.1+C4777T+S:F456L+S:R346T as JN.1.16.1+C4777T
3: Usher misplaces JN.1+C4777T+S:F456L+S:R346I as JN.1.16.1+C4777T+S:T346I

GISAID query: C4777T,T22926C, T22928C
No. of seqs: 69(Australia 9 Canada 7 UK 38 France 2 Ireland 1 Israel 1 Malaysia 1 Pakistan 1 Singapore 1 USA 8(2 from Japan, 2 from UAE))
First: EPI_ISL_18885437, UK, 2024-1-31
Latest: EPI_ISL_19033862, UK, 2024-3-25
GISAID query for S:R346T branch: C4777T, T22926C, T22928C, G22599C (31 seqs)
GISAID query for S:R346I branch: C4777T, T22926C, T22928C, G22599T (16 seqs)

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_f456l_r346ti.json?f_userOrOld=uploaded%20sample&label=id:node_7067390)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/e3e4d866-b5dd-4a74-941f-0cbd5062ad87)

**Comment by FedeGueli** [comment]
the FLiRI branch was Branch 76 of  https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089

**Comment by aviczhl2** [comment]
84, Italy, Germany, Netherlands, Luxembourg

**Comment by FedeGueli** [comment]
this is fast:https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1*&nucMutations1=C4777T%2CT22926C%2CT22928C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Designated JN.1.16.2, LA.1 (346T) and LA.2 (346I) via https://github.com/cov-lineages/pango-designation/commit/52f33370c5df719f0b25d0b8b78ced0727d1171b
