### ISSUE TITLE
Another JN.1.11.1 sublineage got FLiRT after Orf1b:A2143V (NSP15_A92V) 63 sequences   

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2562]
Formerly known as FLIRT Branch 63 (spotted by @aviczhl2)
Defining:
JN.1.11.1 > Orf1b:A2143V (C19895T) > S:R346T (G22599C)
Query : C19895T,G22599C,T3565C

Samples: 5 On Gisaid   from  Australia , NJ , Scotland, Portugal and US
but on USHER there are much more : 11 ( two with defining C19895T reverted)
IDs:
<img width="348" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/87669813/ebe27bff-46c8-4193-a814-34dded86d88b">

Tree:
<img width="1175" alt="Screenshot 2024-04-17 alle 11 31 05" src="https://github.com/cov-lineages/pango-designation/assets/87669813/6c7d4d41-c13f-47f0-aa1b-94f45464cc8f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_51bc8_eece90.json?label=id:node_6968541

There is a sublineage of this with Orf8:Q18* 
Query: C3583T ,C27945T,T3565C
Defining #2562>>C3583T, Orf8:Q18*, C27945T
Samples: 5

Now there is a **FLiRT>TRIO** 
JN.1.11.1 > Orf1b:A2143V (C19895T) > S:R346T (G22599C) > S:T572I (C23277T)
Query: C19895T,C23277T,G24872T
Samples : 1 (Illinois(

**Comment by FedeGueli** [comment]
There were in the mean while a big upload from Australia with 6 sequences placed by Usher in this tree but missing the defining Orf1a:A2143V:
<img width="1152" alt="Screenshot 2024-04-17 alle 13 49 24" src="https://github.com/cov-lineages/pango-designation/assets/87669813/f9af7577-b120-468a-92ba-76d16c4545ab">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a6ab_fa5210.json?c=userOrOld&label=id:node_6968619

cc @corneliusroemer @AngieHinrichs could you give a look at this please?

**Comment by AngieHinrichs** [comment]
Ah, Portugal/PT50701/2024|EPI_ISL_19033732|2024-03-24 has an N at 19895, and must have been pulled into that branch by the G22599C (S:R346T) after C19895T, with usher inferring C19895T -- incorrectly, in light of the Australia sequences.  After the Australia sequences have been added to the tree, I should be able to fix it.

**Comment by FedeGueli** [comment]
> Ah, Portugal/PT50701/2024|EPI_ISL_19033732|2024-03-24 has an N at 19895, and must have been pulled into that branch by the G22599C (S:R346T) after C19895T, with usher inferring C19895T -- incorrectly, in light of the Australia sequences. After the Australia sequences have been added to the tree, I should be able to fix it.

Thank you!

**Comment by FedeGueli** [comment]
+1 Hawaii

**Comment by FedeGueli** [comment]
12 on Gisaid more on Usher also with TRIO:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1e741_ea7b60.json?c=userOrOld&label=id:node_6983815
<img width="1165" alt="Screenshot 2024-05-11 alle 15 06 56" src="https://github.com/cov-lineages/pango-designation/assets/87669813/1c61e537-bef4-4ebc-9a0b-d2d8aa589e1d">
Not sure if misplacement for real reversion tough

**Comment by FedeGueli** [comment]
Still around but designation not needed closing it

**Comment by FedeGueli** [comment]
34

**Comment by FedeGueli** [comment]
63 last sample from Malaysia but it is time to close this
