### ISSUE TITLE
New FLiRT JN.1 with 4 spike mutations (S:S71F,R346T,F456L H1101Y), 18 sequences Uk, Canada  

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2565]
Formerly tracked as Branch 94 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089
JN.1 > S:H1101Y > S:F456L > S:R346T > S:S71F
Query: C24863T, G22599C, T3565C,C21774T
Samples: 9 Uk, US, Canada
EPI_ISL_19010354, EPI_ISL_19059574, EPI_ISL_19062909-19062913,
EPI_ISL_19062915, EPI_ISL_19064899

It further gained S:L1203F:
JN.1 > S:H1101Y > S:F456L > S:R346T > S:S71F > Orf1a:P1912S (C6026T) > A7285G > S:L1203F (C25169T)
Query: C25169T,A7285G
Samples: 2 (Scotland)

Tree: updated at 05/07:
<img width="1169" alt="Screenshot 2024-05-07 alle 09 56 08" src="https://github.com/cov-lineages/pango-designation/assets/87669813/6d7acc23-2206-4cb1-911f-67e4d792416f">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice8_genome_2696e_95ba50.json?label=id:node_6958379
 

 

To be noted that there is another lineage that has JN.1 > S:S71F > S:R346T > S:F456L without S:H1101Y
tracked as branch 99 in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089 
View it here :
<Details> 
<Summary> Same lineage???</Summary> 
Query:C21774T ,G22599C ,T22928C,T3565C,-C7113T,-C24863T
[tree](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_464f0_7af8b0.json?label=id:node_6936214)
<img width="1168" alt="Screenshot 2024-04-23 alle 14 56 12" src="https://github.com/cov-lineages/pango-designation/assets/87669813/8abc10a1-8416-4775-a9b0-d0bdc99704d7">
</Details>
cc @AngieHinrichs @corneliusroemer

**Comment by FedeGueli** [comment]
+2

**Comment by FedeGueli** [comment]
12 on Gisaid , 14 on Usher. Typical stepwise evolutio tree with last sample carrying a further S2 mutation : S:L1203F

**Comment by FedeGueli** [comment]
13

**Comment by FedeGueli** [comment]
14

**Comment by FedeGueli** [comment]
18 seqs but not relevant for designation

**Comment by DailyCovidCases** [comment]
Tracked in [tracker49](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=C24863T%2CG22599C%2CT3565C%2CC21774T&nextcladePangoLineage=JN.1*&)
