### ISSUE TITLE
JN.1 + S:K679R emerged in Malaysia(147 samples) with a sublineage with S:F456L in South Korea (25) representing around 10% of samples collected in May  there

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2571]
Previously tracked in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1350

Defining mutations:
JN.1 >> C19011T > C9836T > S:N>K679R (A23598G)
Query: A23598G,C9836T,C19011T
Samples: 97 (14 countries likely originating in Malaysia and widespread in eastern Asia)
First collected on 2023-12-21
Tree:
<img width="1165" alt="Screenshot 2024-04-29 alle 11 15 51" src="https://github.com/cov-lineages/pango-designation/assets/87669813/7764ae7e-4aa4-4d14-beb5-ad3dc33065e6">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5f086_f63c10.json?label=id:node_6987520
<Details>
<Summary> IDs
</Summary>
EPI_ISL_18726082, EPI_ISL_18726163, EPI_ISL_18726219,
EPI_ISL_18734231, EPI_ISL_18770790, EPI_ISL_18770891,
EPI_ISL_18770901, EPI_ISL_18771027, EPI_ISL_18771057,
EPI_ISL_18806594, EPI_ISL_18806600, EPI_ISL_18806603,
EPI_ISL_18806743, EPI_ISL_18806761, EPI_ISL_18806769,
EPI_ISL_18806923, EPI_ISL_18825081, EPI_ISL_18825087,
EPI_ISL_18831092, EPI_ISL_18831096, EPI_ISL_18831155,
EPI_ISL_18860219, EPI_ISL_18860233-18860234, EPI_ISL_18866060,
EPI_ISL_18866404, EPI_ISL_18866835, EPI_ISL_18870333,
EPI_ISL_18874676, EPI_ISL_18887884, EPI_ISL_18900043,
EPI_ISL_18901945, EPI_ISL_18908296, EPI_ISL_18909554,
EPI_ISL_18916136, EPI_ISL_18922475, EPI_ISL_18924514-18924515,
EPI_ISL_18935685, EPI_ISL_18935719, EPI_ISL_18948088,
EPI_ISL_18952488, EPI_ISL_18952504, EPI_ISL_18952506,
EPI_ISL_18952851, EPI_ISL_18952853, EPI_ISL_18966475,
EPI_ISL_18966478, EPI_ISL_18967107, EPI_ISL_18968646,
EPI_ISL_18982143, EPI_ISL_18982518-18982519, EPI_ISL_18984020,
EPI_ISL_18987183, EPI_ISL_18999175, EPI_ISL_18999249,
EPI_ISL_19001265, EPI_ISL_19009755, EPI_ISL_19013724,
EPI_ISL_19013763, EPI_ISL_19017453, EPI_ISL_19017977,
EPI_ISL_19018024, EPI_ISL_19023243, EPI_ISL_19023248,
EPI_ISL_19023263, EPI_ISL_19025950-19025951, EPI_ISL_19027375,
EPI_ISL_19031079, EPI_ISL_19031091, EPI_ISL_19031130,
EPI_ISL_19031215, EPI_ISL_19032888, EPI_ISL_19032973,
EPI_ISL_19038238, EPI_ISL_19046129, EPI_ISL_19046472,
EPI_ISL_19061933, EPI_ISL_19062106, EPI_ISL_19065264,
EPI_ISL_19065415, EPI_ISL_19065553, EPI_ISL_19065659,
EPI_ISL_19071400, EPI_ISL_19074301, EPI_ISL_19074333,
EPI_ISL_19074556, EPI_ISL_19080148

</Details

There is a recent sublineage of this with S:F456L (T22930A) in South Korea
JN.1 >> C19011T > C9836T > S:N>K679R (A23598G)>>**C2061T, S:F456L (T22930A)**
Query for S:F456L:  C2061T, T22930A, C9836T
Samples: 7 ( South Korea)
First collected on 2024-03-18
<img width="1051" alt="Screenshot 2024-04-29 alle 11 16 33" src="https://github.com/cov-lineages/pango-designation/assets/87669813/fa15c507-2bd4-45f3-8ac3-82a4a3f45605">
IDs:
EPI_ISL_19046398, EPI_ISL_19046416, EPI_ISL_19065287,
EPI_ISL_19079706, EPI_ISL_19079739, EPI_ISL_19080032,
EPI_ISL_19080143

**Comment by FedeGueli** [comment]
106 , 8 with 456L

**Comment by FedeGueli** [comment]
118/12

**Comment by FedeGueli** [comment]
the 456L sublineage  represents around 10% opf samples in S.Korea in May

**Comment by DailyCovidCases** [comment]
Now 160 seqs
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_28fc4_81b0d0.json?f_userOrOld=uploaded%20sample)
![Screenshot (192)](https://github.com/user-attachments/assets/0a46143b-d546-4deb-8da6-fc9fcd6e7c5d)

**Comment by FedeGueli** [comment]
thx @DailyCovidCases  161 but only two from July

**Comment by DailyCovidCases** [comment]
I think this branch should be designated ping @corneliusroemer

**Comment by xz-keg** [comment]
designated JN.1.68.1

**Comment by FedeGueli** [comment]
Designated JN.1.68.1 via https://github.com/cov-lineages/pango-designation/commit/0c6652152ec349f92de8f6dfcd0f6d62a5c919a2#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1600
