### ISSUE TITLE
JN.1 + S:V1229I emerged in Russia - 10% after March 1 in St Petersburg region (126 seqs )with a branch with S:T572I (9)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2572]
This was tracked in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1360
Although not super fast it kept a local high prevalence in St Petersburg area until today.
It got a couple of unrelated sequences with S:R346I and a small branch with S:T572I

JN.1 >> ORF1a :T2846I (C8802T) > S:V1129I (G24947A)
Query: C8802T,G24947A
Query. for S:T572I: C23277T,C8802T,G24947A
Samples 122 ( 8 with S:T572I)
Countries: 4  Mainly Russia
 
<Details> <Summary> IDs: </Summary> EPI_ISL_18686250, EPI_ISL_18686264, EPI_ISL_18831128,
EPI_ISL_18831148, EPI_ISL_18845517-18845518, EPI_ISL_18845520,
EPI_ISL_18845532, EPI_ISL_18845555, EPI_ISL_18845569,
EPI_ISL_18845581, EPI_ISL_18845593, EPI_ISL_18845595,
EPI_ISL_18845605-18845606, EPI_ISL_18962921, EPI_ISL_18973593,
EPI_ISL_18973600-18973601, EPI_ISL_18973637, EPI_ISL_18973643,
EPI_ISL_18973660, EPI_ISL_18973665, EPI_ISL_18973667,
EPI_ISL_18973678, EPI_ISL_18973688, EPI_ISL_18973701,
EPI_ISL_18973704, EPI_ISL_18973706-18973707, EPI_ISL_18973709,
EPI_ISL_18973716, EPI_ISL_18973739, EPI_ISL_18973742-18973743,
EPI_ISL_18973764, EPI_ISL_18973767, EPI_ISL_18973772,
EPI_ISL_18973783, EPI_ISL_18973798, EPI_ISL_18973800,
EPI_ISL_18973802, EPI_ISL_18973811, EPI_ISL_18973816,
EPI_ISL_18973862, EPI_ISL_18973876, EPI_ISL_18973883,
EPI_ISL_18973902, EPI_ISL_18973907, EPI_ISL_18973915,
EPI_ISL_18973917, EPI_ISL_18973930-18973932, EPI_ISL_18973937,
EPI_ISL_18973939, EPI_ISL_18973947, EPI_ISL_18973959,
EPI_ISL_18973967, EPI_ISL_18973983, EPI_ISL_18973998,
EPI_ISL_18974003, EPI_ISL_18974007, EPI_ISL_18974021,
EPI_ISL_18974032, EPI_ISL_18974036, EPI_ISL_18974038-18974039,
EPI_ISL_18974047, EPI_ISL_18974054, EPI_ISL_18974072,
EPI_ISL_18974081, EPI_ISL_18974103-18974104, EPI_ISL_18974106,
EPI_ISL_18974120, EPI_ISL_18974123, EPI_ISL_18974125-18974126,
EPI_ISL_18974133, EPI_ISL_18974138, EPI_ISL_18974141,
EPI_ISL_18974145, EPI_ISL_18974156, EPI_ISL_18974183,
EPI_ISL_18974228, EPI_ISL_18974244, EPI_ISL_18974267,
EPI_ISL_19022403, EPI_ISL_19022409, EPI_ISL_19022421,
EPI_ISL_19022455, EPI_ISL_19022497, EPI_ISL_19022513,
EPI_ISL_19022550, EPI_ISL_19022603, EPI_ISL_19060504,
EPI_ISL_19060548, EPI_ISL_19060651, EPI_ISL_19060681,
EPI_ISL_19060691, EPI_ISL_19060712, EPI_ISL_19060730,
EPI_ISL_19060737, EPI_ISL_19060751, EPI_ISL_19060761,
EPI_ISL_19060765, EPI_ISL_19060780, EPI_ISL_19060825,
EPI_ISL_19060836, EPI_ISL_19060845, EPI_ISL_19060851,
EPI_ISL_19060860, EPI_ISL_19060875, EPI_ISL_19060880,
EPI_ISL_19060883, EPI_ISL_19060885, EPI_ISL_19062303,
EPI_ISL_19062337, EPI_ISL_19062351, EPI_ISL_19062365,
EPI_ISL_19066795
</Details>
Tree:
<img width="1151" alt="Screenshot 2024-04-29 alle 11 38 23" src="https://github.com/cov-lineages/pango-designation/assets/87669813/d8156665-35fd-40c0-ae10-e916566d62e9">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_29d5d_f687d0.json?c=gt-S_572&label=id:node_7050993

**Comment by FedeGueli** [comment]
Not expanding outside Russia, closing for now

**Comment by Over-There-Is** [comment]
144
