### ISSUE TITLE
Another JN.1+S:1143F(20 seqs, 6 countries)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2576]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1543
JN.1+C6145T+C20451T+C22498T+C24989T(S:L1143F)

GISAID query: C24989T,C22498T,C20451T
No. of seqs: (South Korea 3 Mauritius 2 France 2 Spain 4 Portugal 1 China 8(Shanghai,Taiwan, Shanxi, Sichuan))

First: EPI_ISL_18821834, 2023-11-29, Mauritius
Latest: EPI_ISL_19130941, 2024-5-8, Taiwan

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_42afe_c5aa20.json?f_userOrOld=uploaded%20sample)
![Screenshot (52)](https://github.com/cov-lineages/pango-designation/assets/92421581/cc71131d-985e-46ff-9fa0-e8c59095ae54)

**Comment by FedeGueli** [comment]
Sorry , why did u open this here? Are you from any lab involved?

**Comment by DailyCovidCases** [comment]
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=C24989T%2CC22498T%2CC20451T&nextcladePangoLineage=JN.1*&
