### ISSUE TITLE
JN.1.4+S:F456L(298 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2577]
From branch 17 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1.4(with T18453C)+T22928C(S:F456L)

GISAID query: C774T,T18453C,T22926C, T22928C,-9979,-12525,-28201,-29799,-25710,-10615,-6040,-28708,-17676,-3411,-6267,-14318,-12676,-22664,-11020,-5284,-22450,-17491,-C2070T,-13665, -C1912T, -25513,-19602, -28748,-C7735T, -A3908G,-22564,-22115, -21255, -28774, -23262,-29725

No. of seqs: 119(Canada 1 UK 1 China 3 Japan 2 Lithuania 1 South Korea 97 Spain 8 Sweden 1 USA 4(2 from South Korea))

First: EPI_ISL_19042097, Lithuania, 2023-12-16
Latest: EPI_ISL_19093619, USA from South Korea, 2024-4-25

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_4_f456l.json?label=id:node_7080541)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/048f2b1b-81ae-4306-9cbd-dbf78f777e68)

**Comment by aviczhl2** [comment]
@corneliusroemer 205 seqs now

**Comment by aviczhl2** [comment]
216, Ecuador, Brazil, Italy

**Comment by FedeGueli** [comment]
238 now, 

<img width="991" alt="Screenshot 2024-06-17 alle 02 43 38" src="https://github.com/cov-lineages/pango-designation/assets/87669813/6d84e130-8ba0-4162-ab45-e05ccc0ef936">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5fd27_eb3700.json?c=gt-nuc_27297&gmax=28297&gmin=26297&label=id:node_7124970

Interestingly it has a branch with S:T95I and Orf8:Q18*: 
<img width="1170" alt="Screenshot 2024-06-17 alle 02 46 49" src="https://github.com/cov-lineages/pango-designation/assets/87669813/6d912604-7ecd-4ea3-812e-ec01e02363ec">

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by aviczhl2** [comment]
250, France, Ireland, Germany

**Comment by DailyCovidCases** [comment]
This branch worth to be designated

**Comment by DailyCovidCases** [comment]
How many sequences have been found now?

**Comment by DailyCovidCases** [comment]
259 seqs now
Tracked in [tracker17](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=C774T%2CT18453C%2CT22926C%2CT22928C%2CC9979C%2CT12525T&nextcladePangoLineage=JN.1.4*&)

**Comment by DailyCovidCases** [comment]
@corneliusroemer

**Comment by DailyCovidCases** [comment]
268 seqs now
@corneliusroemer This one seems to be ignored from designation for quite a long time

**Comment by DailyCovidCases** [comment]
@corneliusroemer This one seems to be ignored from designation for quite a long time

**Comment by DailyCovidCases** [comment]
294 seqs now

**Comment by Over-There-Is** [comment]
*not all of JN.1.4 has T18453C.

**Comment by DailyCovidCases** [comment]
Ping @corneliusroemer rapid designation needed

**Comment by DailyCovidCases** [comment]
![Screenshot (164)](https://github.com/user-attachments/assets/7ebe88f4-5400-4681-8712-a05b20a6a06f)
@corneliusroemer In USA and Canada, some of the "JN.1" can belong to this branch. So I think this branch shall get designated to distinguish from vanilla JN.1
Source: 
https://health-infobase.canada.ca/covid-19/testing-variants.html
https://covid.cdc.gov/covid-data-tracker/#variant-proportions

**Comment by DailyCovidCases** [comment]
@corneliusroemer suggest to designate some trajectory of this

**Comment by DailyCovidCases** [comment]
How many seqs in this branch now? Please update it

**Comment by DailyCovidCases** [comment]
This branch might be dying off, please close it

**Comment by DailyCovidCases** [comment]
This branch might be dying off, please close it

**Comment by corneliusroemer** [comment]
JN.1.4.9

**Comment by DailyCovidCases** [comment]
> JN.1.4.9

@corneliusroemer Why the branch on https://github.com/cov-lineages/pango-designation/issues/2517 is not designated? That branch got significant proportion in March and April in Canada and USA.
