### ISSUE TITLE
JN.1+S:F456L on C23683T branch(136 seqs, 9 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2578]
From branch 15 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1+C23683T+T22928C(S:F456L)

GISAID query: C23683T ,T22928C,C897A,-24821,-14877,-17334, -2782,-4795,-17746,-18453,-C774T,-C1762A,-18131,-13121,-24904,-4162,-7850
No. of seqs:102(Canada 1 Japan 4 China 1 Thailand 1 USA 1 South Korea 94)

First: EPI_ISL_18853287, South Korea, 2024-1-9
Latset: EPI_ISL_19093084, South Korea, 2024-4-14

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_23683_f456l.json?label=id:node_7106893)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/2cc1180a-a269-42f4-a4d5-7bd12763d9af)

**Comment by aviczhl2** [comment]
I'm unsure about this C14877T+C23683T+S:F456L branch, likely something misplaced and shall belong to this branch? Or recomb? 

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/2f9a8aed-23fa-4c0b-91cb-cf1ab482ab7c)

**Comment by FedeGueli** [comment]
14877 is highly homoplasic toward a point it could be note real:

<img width="1166" alt="Screenshot 2024-05-13 alle 13 09 16" src="https://github.com/cov-lineages/pango-designation/assets/87669813/3cb1c0ba-d7cc-4406-9e85-43301e495382">
 
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_5a205_1f3b50.json?f_userOrOld=uploaded%20sample&label=id:node_6914949

**Comment by aviczhl2** [comment]
132, Singapore

**Comment by FedeGueli** [comment]
174

**Comment by DailyCovidCases** [comment]
181 seqs now, this branch worth to be designated

**Comment by DailyCovidCases** [comment]
181 seqs now
Is this branch worth to be designated?

**Comment by DailyCovidCases** [comment]
182 now, apprarently slowing down

**Comment by DailyCovidCases** [comment]
183 seqs now
Tracked in [tracker15](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=C23683T%2CT22928C%2CC897A&nextcladePangoLineage=JN.1*&)

**Comment by DailyCovidCases** [comment]
@corneliusroemer

**Comment by DailyCovidCases** [comment]
197 seqs now
@corneliusroemer This one seems to be ignored from designation for quite a long time

**Comment by aviczhl2** [comment]
140, France, Sweden

**Comment by DailyCovidCases** [comment]
@corneliusroemer This one seems to be ignored from designation for quite a long time

**Comment by DailyCovidCases** [comment]
219 seqs now

**Comment by DailyCovidCases** [comment]
Ping @corneliusroemer rapid designation needed

**Comment by FedeGueli** [comment]
> C23683T ,T22928C,C897A,-24821,-14877,-17334, -2782,-4795,-17746

only 5 samples after July 1, still one from August so maybe it is worth keeping this open but no designation needed as of today in my view.

**Comment by aviczhl2** [comment]
Add more -s , the current count shall be 136, but there's still August seq so worth tracking

**Comment by DailyCovidCases** [comment]
@corneliusroemer suggest to designate some trajectory of this

**Comment by DailyCovidCases** [comment]
This branch might be dying off, please close it

**Comment by DailyCovidCases** [comment]
Now 243 seqs

**Comment by Over-There-Is** [comment]
163?

**Comment by FedeGueli** [comment]
> 163?

Nope 136 the remaining are not belonging to this:
<img width="1172" alt="Screenshot 2024-12-10 alle 10 33 17" src="https://github.com/user-attachments/assets/ced0309f-cfe0-41b6-b786-fba118f62fbc">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/singleSubtreeAuspice_genome_test_4acc8_809c80.json?f_userOrOld=uploaded%20sample&label=id:node_6959814
