### ISSUE TITLE
Proposal for dominant Brazilian Delta lineage with ORF1a:1091V (~7k, 50%)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#258]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: B.1.617.2
Earliest sequence: India 2021-15
Most recent sequence: Current
Countries circulating: Mostly Brazil with >50%, in some regions even >90%

Lineage deriving from B.1.617.2 with extra ORF1a:1091V and synonymous nuc:13216C
The largest sub-branch (90%) has ORF1a:4087I, the other smaller one ORF1a:2910I

![image](https://user-images.githubusercontent.com/25161793/137605795-df8515ee-c5a2-4a54-a4fd-b664a3f79e64.png)
https://cov-spectrum.ethz.ch/explore/Brazil/AllSamples/Past6M/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22orf1a%3A1091V%22]%7D%2C%22matchPercentage%22%3A1%7D

![image](https://user-images.githubusercontent.com/25161793/137605800-0368cbd0-5423-4ade-bedb-cfc2b9e613bb.png)

https://nextstrain.org/groups/neherlab/ncov/sa-brazil?branchLabel=aa&c=gt-nuc_3536,4927,8994

![image](https://user-images.githubusercontent.com/25161793/137605818-1eacd9b3-86ac-4c28-8fd7-1a5697023234.png)

![image](https://user-images.githubusercontent.com/25161793/137605821-ca132f2d-9742-4da6-acce-944a25c654bc.png)

<html><head></head><body>

Country | Total Variant Sequences | First seq. found at | Last seq. found at |  
-- | -- | -- | -- | --
Argentina | 1 | 2021-36 | 2021-36 |  
Australia | 4 | 2021-19 | 2021-35 |  
Austria | 64 | 2021-17 | 2021-29 |  
Belgium | 2 | 2021-32 | 2021-33 |  
Brazil | 5873 | 2021-23 | 2021-40 |  
Canada | 9 | 2021-30 | 2021-35 |  
Chile | 4 | 2021-30 | 2021-38 |  
Croatia | 2 | 2021-26 | 2021-32 |  
Denmark | 6 | 2021-29 | 2021-34 |  
Finland | 1 | 2021-28 | 2021-28 |  
France | 4 | 2021-28 | 2021-37 |  
Germany | 13 | 2021-17 | 2021-40 |  
Ghana | 2 | 2021-31 | 2021-33 |  
Hong Kong | 2 | 2021-33 | 2021-33 |  
Iceland | 2 | 2021-31 | 2021-32 |  
India | 6 | 2021-15 | 2021-27 |  
Ireland | 2 | 2021-32 | 2021-33 |  
Italy | 2 | 2021-39 | 2021-40 |  
Japan | 6 | 2021-27 | 2021-34 |  
New Zealand | 1 | 2021-28 | 2021-28 |  
Nigeria | 61 | 2021-29 | 2021-36 |  
Norway | 8 | 2021-26 | 2021-31 |  
Pakistan | 2 | 2021-35 | 2021-35 |  
Portugal | 14 | 2021-35 | 2021-39 |  
Qatar | 1 | 2021-17 | 2021-17 |  
South Africa | 147 | 2021-19 | 2021-37 |  
South Korea | 1 | 2021-29 | 2021-29 |  
Spain | 3 | 2021-36 | 2021-38 |  
Sweden | 1 | 2021-33 | 2021-33 |  
Switzerland | 4 | 2021-30 | 2021-35 |  
Ukraine | 1 | 2021-25 | 2021-25 |  
United Kingdom | 358 | 2021-26 | 2021-40 |  
United States | 284 | 2021-16 | 2021-40

</body></html>

**Comment by FedeGueli** [comment]
CC @chrisruis @corneliusroemer 
This has now been designated as AY.99 starting with ORF1a:I1091V

Commit:
https://github.com/cov-lineages/pango-designation/commit/5410dddbee23dcfcbd7d9f41590e951ceda2301e

**Comment by FedeGueli** [comment]
CC @chrisruis @corneliusroemer 

The two subclades identified here have been designated:

AY.99.1 starting with Orf1a:T2910I
commit:
https://github.com/cov-lineages/pango-designation/commit/cd2f203d4e939461bbcc5dbfb647ec3d3ddde97b

and AY.99.2 starting with  C4927T (synonymous),C12525T (Orf1a:T4087I)
commit:
https://github.com/cov-lineages/pango-designation/commit/6a28193357f2fd5187ba5672ba04abecc58e964d

**Comment by corneliusroemer** [comment]
Designated
