### ISSUE TITLE
JN.1+S:F456L on C4795T branch (114 seqs, 14 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2581]
From branch 32 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1+C4795T+T22928C(S:F456L)

GISAID query: C4795T, T22928C, T3565C,-C1762A,-17334
No. of seqs:98(Australia 20 Canada 16 UK 1 Finland 7 France 1 China 4 Japan 8 New Zealand 1 South Korea 30 Vietnam 1 USA 9(2 from Japan, 2 from Thailand, 1 from Qatar, 1 from Taiwan))

First: EPI_ISL_18949364, Vietnam, 2024-1-19
Latest: EPI_ISL_19093705, USA from Thailand, 2024-4-23

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_4795_f456l.json?label=id:node_6957652)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/586a91e8-ad9e-47a5-8be0-cfdb9b7626b6)

**Comment by aviczhl2** [comment]
114, Singapore

**Comment by aviczhl2** [comment]
Designated JN.1.51.1

**Comment by FedeGueli** [comment]
Hi @aviczhl2 i had a query for the S:22N branch  linked to this issue , C21627A,C4795T, T22928C, T3565C,-C1762A,-17334 , it is the same query of this and all of them has S:T22N too so i think this is also LJ.1

**Comment by aviczhl2** [comment]
> Hi @aviczhl2 i had a query for the S:22N branch linked to this issue , C21627A,C4795T, T22928C, T3565C,-C1762A,-17334 , it is the same query of this and all of them has S:T22N too so i think this is also LJ,1

Do you mean all JN.1.51.1 seqs are LJ.1?

**Comment by FedeGueli** [comment]
> C21627A

Sorry i saw your comment now, my mistake i have added C21627A to the query so i would let this open to seek designation of the 44seqs S:T22N  sublineage of JN.1.51.1.
