### ISSUE TITLE
JN.1 + S:F456L + S:V407i (37 seqs, Spain)

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#2584]
This proposed lineage was first found by @aviczhl2 in [this issue.](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253)

GISAID Query: T17556C, G22781A
First Seq: EPI_ISL_18963344, Feb 11 Spain / Andalusia / Almeria
Prevalence: 
 15/75 sequences collected from Galicia Spain March 3-April 5.
 18/79 of sequences in Galicia Spain collected since April 6.
Mutations: JN.1 + A9085G -> S:F456L + S:V407i + T17556C. Then all except for the first sequence have T6552C and C12400T. 
It's also possible that this is instead JN.16 + A9085G + S:V407i + T17556C

[Tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3797e_8e1d90.json)
![image](https://github.com/cov-lineages/pango-designation/assets/94097102/956eb6f2-616c-47db-88d1-d920094521ef)

**Discussion:**
Proposing this one due to its high prevalence in two different regions of Galicia Spain, which has accumulated across 3 uploads. Additionally this proposed sublineage is in Asturias Spain in addition to Andalusia and Galicia. Since the S:V407i mutation is accompanied by T17556C, it is pretty distinct.

**Comment by FedeGueli** [comment]
it doesn't seem slow.

**Comment by aviczhl2** [comment]
This is not sub-branch of JN.1.16, but rather sub-branch of branch 34 in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253

**Comment by FedeGueli** [comment]
> This is not sub-branch of JN.1.16, but rather sub-branch of branch 34 in [sars-cov-2-variants/lineage-proposals#1253](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253)

Yes you are right, @Sinickle please broad the proposal with that so jn.1+456L (as in # 1253) crediting @aviczhl2 and then the sublineage of interest with S:V407I

**Comment by FedeGueli** [comment]
Wow it went to 28! @corneliusroemer ping!

**Comment by Sinickle** [comment]
I don't think it's clear that this is a sublineage of JN.1 rather than JN.1.16? 
It looks to me like JN.1 is suspected due to a branch of it having A9085G. However, JN.1.16 has S:F456L. Since the proposed lineage has both A9085G and S:F456L, and it acquired S:F456L and A9085G before S:V407i, isn't it unclear if it comes from JN.1 or JN.1.16?

**Comment by aviczhl2** [comment]
> I don't think it's clear that this is a sublineage of JN.1 rather than JN.1.16? It looks to me like JN.1 is suspected due to a branch of it having A9085G. However, JN.1.16 has S:F456L. Since the proposed lineage has both A9085G and S:F456L, and it acquired S:F456L and A9085G before S:V407i, isn't it unclear if it comes from JN.1 or JN.1.16?

More likely from A9085G branch because S:F456L is much more convergent than A9085G, it is unlikely for A9085G to appear multiple times and form sizeable branches, but very likely for T22928C to appear both under JN.1 and JN.1+A9085G .

**Comment by FedeGueli** [comment]
> > I don't think it's clear that this is a sublineage of JN.1 rather than JN.1.16? It looks to me like JN.1 is suspected due to a branch of it having A9085G. However, JN.1.16 has S:F456L. Since the proposed lineage has both A9085G and S:F456L, and it acquired S:F456L and A9085G before S:V407i, isn't it unclear if it comes from JN.1 or JN.1.16?
> 
> More likely from A9085G branch because S:F456L is much more convergent than A9085G, it is unlikely for A9085G to appear multiple times and form sizeable branches, but very likely for T22928C to appear both under JN.1 and JN.1+A9085G .

@Sinickle i agree with @aviczhl2 Jn.1.16 ( as Jn.1.18 ) are not monophyletic lineages but instead big collectors of early convergent branches with 456L (or 346T for JN.1.18) In fact sometime we find in those lineages misplaced branches that are instead also outside of it . So if this has A9058G and A9085G exists outside S:f456L, it is 99% it comes before

**Comment by Sinickle** [comment]
Even though S:F456L is more convergent, "vanilla" JN.1.16 is still much larger than JN.1 + A9085G. So that aspect would shift it in favor of JN.1.16. 

I tried to trim off some of the branches to get a query for ["vanilla" JN.1 + A9085G](https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-10-01%26to%3D2024-02-01/variants?nucMutations=9085g%2C829.%2C2727.%2C13252.%2C14925.%2C16192.%2C21610.%2C9238.%2C11788.%2C17274.%2C22624.%2C24046.%2C26029.%2C26882.&nextcladePangoLineage=jn.1&variantQuery1=nextcladePangoLineage%3Ajn.1.16+%26+1126.+%26+4162.+%26+4777.+%26+4795.+%26+5422.+%26+6145.+%26+22599.+%26+23683.+%26+24727.+%26+26660.&), and for [vanilla JN.1.16](https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-11-06%26to%3D2024-02-11/variants?variantQuery=nextcladePangoLineage%3Ajn.1.16+%26+G1126.+%26+G4162.+%26+C4777.+%26+C4795.++%26+A24727.+%26+G26660.+%26++C23683.+%26+5422.+%26+6145.+%26+26753.+%26+26691.+%26+25758.+%26+22858.+%26+21911.+%26+532.+%26+1461.+%26+1463.+%26+2608.+%26+11224.+%26+12781.+%26+6552.+%26+11083.+%26+12073.+%26+12400.+%26+17556.+%26+17562.+%267039.+%26+8802.+%26+21610.+%26+25578.+%26+25703.+%26+27573.+&nextcladePangoLineage1=jn.1&), to see how large each was. JN.1.16 is still the larger one, but if we limit it to Spain and limit it to before the first sequence of the proposed lineage appeared, then JN.1.16 has 11 in Spain, and JN.1 has 7 in Spain, which isn't enough of a size difference to make up for the difference in the convergent nature of S:F456L. 

**So I agree that JN.1 is more likely overall.** Thanks!

**Comment by FedeGueli** [comment]
i found some  news of an apparent increase in cases in Galicia, we should monitor this one if related or not to that> https://x.com/Miguel_Leiva_/status/1789347080718123008

**Comment by FedeGueli** [comment]
32 +2 Galicia (Coruna)

**Comment by Sinickle** [comment]
There is now one of this proposed sublineage collected May 5 from Toledo Spain.

**Comment by aviczhl2** [comment]
Designated JN.1.54.1

**Comment by FedeGueli** [comment]
Designated JN.1.54.1 via https://github.com/cov-lineages/pango-designation/commit/d4897dae54782f87ceda609bc30252dcd22905c7

**Comment by FedeGueli** [comment]
From the [comment](https://github.com/cov-lineages/pango-designation/commit/d4897dae54782f87ceda609bc30252dcd22905c7) to the co mmit of JN.1.54.1 : 
>@corneliusroemer @sinickle 
i just noticed that there is an entire branch of JN.1.54 with s:F456L and without S:V407I misplaced by Usher (cc @AngieHinrichs ) to a flip flop 455L big branch of JN.1 .
It is quite interesting cause it is first time we (at least me) see Orf8 being splitted in two ( same as happened in Sars1??) equally long parts due a S:C61Stop S:V62M double nuc mutation (C28076A, G28077A):
<img width="675" alt="Screenshot 2024-06-03 alle 13 14 24" src="https://github.com/cov-lineages/pango-designation/assets/87669813/43432581-3e58-47b3-a0ab-c2b0c8839890">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice29_genome_test_af16_d9e850.json?label=id:node_6955337
<img width="1159" alt="Screenshot 2024-06-03 alle 13 15 45" src="https://github.com/cov-lineages/pango-designation/assets/87669813/d8552fff-aa43-4710-88d5-04ae64706fcd">
Query for it:  A9085G,T22928C,T3565C , C8917T 
finds 41 sequences 
EPI_ISL_19055427, EPI_ISL_19126142, EPI_ISL_19126554,
EPI_ISL_19141038, EPI_ISL_19141042, EPI_ISL_19146196,
EPI_ISL_19146198, EPI_ISL_19146200, EPI_ISL_19146209,
EPI_ISL_19146217, EPI_ISL_19146290, EPI_ISL_19146292-19146293,
EPI_ISL_19146295-19146298, EPI_ISL_19146300, EPI_ISL_19146302-19146305,
EPI_ISL_19146343, EPI_ISL_19146356, EPI_ISL_19146358,
EPI_ISL_19147058, EPI_ISL_19151426, EPI_ISL_19151430,
EPI_ISL_19163931, EPI_ISL_19164648, EPI_ISL_19165395,
EPI_ISL_19167760, EPI_ISL_19175169-19175170, EPI_ISL_19175173,
EPI_ISL_19175176, EPI_ISL_19175179, EPI_ISL_19175181,
EPI_ISL_19175184, EPI_ISL_19175190, EPI_ISL_19175517,
Samples are from 3 countries mostly Spain  from different areas spanning from Canary Is. to Andalusia and different labs.


Maybe @corneliusroemer it could be designated JN.1.54.X  having both this interesting splitted Orf8 and 456L???

**Comment by FedeGueli** [comment]
> From the [comment](https://github.com/cov-lineages/pango-designation/commit/d4897dae54782f87ceda609bc30252dcd22905c7) to the commit of JN.1.54.1 :
> 
> > @corneliusroemer @Sinickle
> > i just noticed that there is an entire branch of JN.1.54 with s:F456L and without S:V407I misplaced by Usher (cc @AngieHinrichs ) to a flip flop 455L big branch of JN.1 .
> > It is quite interesting cause it is first time we (at least me) see Orf8 being splitted in two ( same as happened in Sars1??) equally long parts due a S:C61Stop S:V62M double nuc mutation (C28076A, G28077A):
> 
> <img alt="Screenshot 2024-06-03 alle 13 14 24" width="675" src="https://private-user-images.githubusercontent.com/87669813/336048485-43432581-3e58-47b3-a0ab-c2b0c8839890.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjA5MjgsIm5iZiI6MTcxODYyMDYyOCwicGF0aCI6Ii84NzY2OTgxMy8zMzYwNDg0ODUtNDM0MzI1ODEtM2U1OC00N2IzLWEwYWItYzJiMGM4ODM5ODkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEwMzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NDZhMTNmNWYwN2I3NDUzYzE3NTE4YTFmMzRiNmU4ZmM3OGVmZjc1MTU3NDIzOGQ5YjQyM2M4ZWI1YjE4OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s84yXcq1u0TucigA420yky9XnODcHIrL4wDnW9m2DEo"> <img alt="Screenshot 2024-06-03 alle 13 15 45" width="1159" src="https://private-user-images.githubusercontent.com/87669813/336048796-d8552fff-aa43-4710-88d5-04ae64706fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjA5MjgsIm5iZiI6MTcxODYyMDYyOCwicGF0aCI6Ii84NzY2OTgxMy8zMzYwNDg3OTYtZDg1NTJmZmYtYWE0My00NzEwLTg4ZDUtMDRhZTY0NzA2ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEwMzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNGRmOTlkYmQyYWI5ZjI0NjYwOWM1MDk4MmI1MjM4NGE1ZjQ3Y2JhZDdhNWU4ZjI2YmY0NjZlNmJjOWRiZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.31yI-nXv95U_G5xKLDw996aAzq0Vws2IAiEOgJcFtow">
> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice29_genome_test_af16_d9e850.json?label=id:node_6955337
> 
> Query for it: A9085G,T22928C,T3565C , C8917T finds 41 sequences EPI_ISL_19055427, EPI_ISL_19126142, EPI_ISL_19126554, EPI_ISL_19141038, EPI_ISL_19141042, EPI_ISL_19146196, EPI_ISL_19146198, EPI_ISL_19146200, EPI_ISL_19146209, EPI_ISL_19146217, EPI_ISL_19146290, EPI_ISL_19146292-19146293, EPI_ISL_19146295-19146298, EPI_ISL_19146300, EPI_ISL_19146302-19146305, EPI_ISL_19146343, EPI_ISL_19146356, EPI_ISL_19146358, EPI_ISL_19147058, EPI_ISL_19151426, EPI_ISL_19151430, EPI_ISL_19163931, EPI_ISL_19164648, EPI_ISL_19165395, EPI_ISL_19167760, EPI_ISL_19175169-19175170, EPI_ISL_19175173, EPI_ISL_19175176, EPI_ISL_19175179, EPI_ISL_19175181, EPI_ISL_19175184, EPI_ISL_19175190, EPI_ISL_19175517,
> 
> Samples are from 3 countries mostly Spain from different areas spanning from Canary Is. to Andalusia and different labs.
> 
> Maybe @corneliusroemer it could be designated JN.1.54.X having both this interesting splitted Orf8 and 456L???

45 now of this

**Comment by DailyCovidCases** [comment]
This branch is designated, please close it
