### ISSUE TITLE
JN.1+S:F456L on C6145T branch (94 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2585]
From branch 9 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253

JN.1+C6145T+T22928C(S:F456L)

GISAID query: C6145T, T22928C,T22926C,T3565C,-2782,-5184,-18453,-G17334T,-A161G,-A1461G,-G1857T
No. of seqs: 56(Canada 2 Japan 23 Netherlands 1 China 2(1 from Japan) Singapore 1 South Korea 17 USA 6)

First: EPI_ISL_18843993, Japan, 2024-1-1
Latest: EPI_ISL_19095766, Singapore, 2024-4-16

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_6145_f456l.json?label=id:node_7025214)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/a86812d0-3212-4209-a589-cadc2be51895)

**Comment by aviczhl2** [comment]
72, Australia, UK

**Comment by DailyCovidCases** [comment]
88 seqs

**Comment by FedeGueli** [comment]
New query: C6145T, T22928C,T22926C,T3565C,-2782,-5184,-18453,-G17334T,-A161G,-A1461G,-G1857T finds 75

**Comment by DailyCovidCases** [comment]
Close this issue please

**Comment by aviczhl2** [comment]
94, Qatar, Kuwait, Malaysia, Ireland, Brazil

**Comment by DailyCovidCases** [comment]
Tracked in [tracker9](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=C6145T%2CT22928C%2CT22926C%2CT3565C&nextcladePangoLineage=JN.1*&)

**Comment by aviczhl2** [comment]
82 using @FedeGueli 's new query

**Comment by DailyCovidCases** [comment]
109 seqs now

**Comment by DailyCovidCases** [comment]
Now 109 seqs, not dead yet

**Comment by FedeGueli** [comment]
> Now 109 seqs, not dead yet

83 with this: C6145T, T22928C,T22926C,T3565C,-2782,-5184,-18453,-G17334T,-A161G,-A1461G,-G1857T

**Comment by DailyCovidCases** [comment]
Please close it

**Comment by DailyCovidCases** [comment]
144 seqs now

**Comment by aviczhl2** [comment]
94, Russia
