### ISSUE TITLE
JN.1.50(JN.1 + S:A67V, S:L249F, S:V445P, S:F456L) + S:R346T(6 seq, 3 countries)

### ISSUE THREAD

**Issue by DoropFan** [cov-lineages/pango-designation#2587]
Add---
JN.1.50 + S:R346T Found it By @FedeGueli
https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253

JN.1.50>T8749G, C11704T, S:R346T(G22599C)

------

Transferred from:https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
Branch 83

Sub-lineage of:JN.1
Earliest sequence:2024-03-22(Norway)|EPI_ISL_19114550
Most recent sequence:2024-04-29(United States)|EPI_ISL_19108763
Countries circulating:United States(2), Norway(1), France(1), Ireland(1)
Sequences:5

[UShER Tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_226a0_163b20.json?c=gt-S_456&gmax=25384&gmin=21563&label=id:node_6968820)
JN.1>C9298T>S:L249F(G22309C)>S:A67V(C21762T), S:F456L(T22930G)>C4456T, S:H445P(A22896C)
![JN1+L249F+A67VF456L+346T](https://github.com/cov-lineages/pango-designation/assets/118802079/1cfa7185-465c-4744-b8b6-8fc2639aa81b)

Query: G22309C, C4456T, C9298T
346T: G22309C, C4456T, C9298T, G22599C

[CovSpectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=G22309C%2CC4456T%2CC9298T&nextcladePangoLineage1=JN.1&)

Genomes
EPI_ISL_19116225
EPI_ISL_19086278
EPI_ISL_19108763
EPI_ISL_19114550
EPI_ISL_19108187

**Comment by DoropFan** [comment]
Spain
EPI_ISL_19131017
EPI_ISL_19131026

**Comment by DoropFan** [comment]
Denmark|EPI_ISL_19129949

**Comment by FedeGueli** [comment]
10 now It popped up in Galicia(Spain) where there is an uptick in cases and British Columbia (Canada)
@corneliusroemer this could be one of the fastest.

**Comment by FedeGueli** [comment]
Designated! JN.1.1.8 via https://github.com/cov-lineages/pango-designation/commit/5191300c600e7d71f4fb70517406330d42b572e1
First 445P desingated on JN.1 backbone cc @DoropFan

**Comment by FedeGueli** [comment]
Now designated JN.1.50 via https://github.com/cov-lineages/pango-designation/commit/935a255118c85a1f5309186fe434936365ca912d

**Comment by DoropFan** [comment]
346T England![JN1 50+346T](https://github.com/cov-lineages/pango-designation/assets/118802079/d342b64d-1420-4962-85e0-c970a659e86e)

**Comment by FedeGueli** [comment]
> 346T England![JN1 50+346T](https://private-user-images.githubusercontent.com/118802079/331851215-d342b64d-1420-4962-85e0-c970a659e86e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDg4MTUsIm5iZiI6MTcxNjEwODUxNSwicGF0aCI6Ii8xMTg4MDIwNzkvMzMxODUxMjE1LWQzNDJiNjRkLTE0MjAtNDk2Mi04NWUwLWM5NzBhNjU5ZTg2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwODQ4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWM2MzE2NjY3MTNkZGE2ZmU0ZDE3NGQ4Zjc2Nzc1MzM4Y2RkYzI1MTE5ZWQ3YzQwNDQ0ZTg2OGJlMjM2YmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l8KrNslKPIyU8-CCo5sjm9D7K0zOoeIXzBihOb7z3Nk)

Please rearrange the title to seek a designation of the JN.1.50 Flirt Branch that is now 3

**Comment by FedeGueli** [comment]
Designated JN.1.50.1 via https://github.com/cov-lineages/pango-designation/commit/06fd16443ab74c0df2837af401bda0c635f67641
