### ISSUE TITLE
JN.1+S:F456L via T22930A (331 seqs, 160 with S:R346T designated JN.1.18.5)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2588]
From branch 20 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1+T22930A(S:F456L)

GISAID query: T22930A, T3565, T22926C,-A2543G,-C4455T,-T8862C,-C25658T,-G260A,-A6705G,-A2251G,-C1762A,-C774T,-G25552T,-A6705G,-T23031C,-T24364C,-C2061T,-G18756T,-C26684T,-A4005G,-A720G,-G16377T,-C14724T,-C2574T,-18348,-18657, -A2782G,-C7113T,-5581,-25566, -18453, -G2782T, -25012,-9996,-20930, -16329, -21137,-8290

GISAID query for S:R346T branch:  T22930A, T3565, T22926C,-A2543G,-C4455T,-T8862C,-C25658T,-G260A,-A6705G,-A2251G,-C1762A,-C774T,-G25552T,-A6705G,-T23031C,-T24364C,-C2061T,-G18756T,-C26684T,-A4005G,-A720G,-G16377T,-C14724T,-C2574T,-18348,-18657, -A2782G,-C7113T,-5581, G22599C
No. of seqs: 49(Argentina 1 UK 4 France 2 Germany 2 Ireland 1 Italy 16 Japan 1 Netherlands 1 Singapore 1 South Korea 13 China 1 USA 6 (1 from UK))

First: EPI_ISL_19049553, Italy, 2024-1-3
Latest: EPI_ISL_19130959, Taiwan, 2024-5-8

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_t22930a.json?gt=nuc.22930A&label=id:node_6981602)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/5d00a4b7-57ed-4ece-982d-40b688b0063c)

Another T22930G branch is misplaced under this branch, that shall be designated separately.

**Comment by FedeGueli** [comment]
> 
> Another T22930G branch is misplaced under this branch, that shall be designated separately.

It is the Orf6:I60T branch already proposed in https://github.com/cov-lineages/pango-designation/issues/2567

**Comment by aviczhl2** [comment]
> > Another T22930G branch is misplaced under this branch, that shall be designated separately.
> 
> It is the Orf6:I60T branch already proposed in #2567

Shall that be a sub-branch of JN.1.18?

**Comment by FedeGueli** [comment]
> > > Another T22930G branch is misplaced under this branch, that shall be designated separately.
> > 
> > 
> > It is the Orf6:I60T branch already proposed in #2567
> 
> Shall that be a sub-branch of JN.1.18?

Thank you! i am following that lineage since it was one or two sequences and it has been here and there in the tree so i didn't notice that it was the FLiRT of Jn.1.18  and it makes sense cause Jn.1.18 ( as collector lineage) was present in Africa very early and this is the natural development for it.

**Comment by FedeGueli** [comment]
@aviczhl2 +1 FLiRT

**Comment by aviczhl2** [comment]
The R346T branch is designated JN.1.18.5.

**Comment by FedeGueli** [comment]
142 
but impossible to designate ?

**Comment by aviczhl2** [comment]
231 now.

**Comment by aviczhl2** [comment]
257 when adding more - s. Most are JN.1.18.5 and pure JN.1+T22930A is not a lot.  so better close it.
