### ISSUE TITLE
Another JN.1 + FLiRT lineage emerged in the Iberian Peninsula (141 seqs , 11 countries)  

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2589]
Previously tracked as Branch 133 **FLiRT**  of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089

JN.1 > T17859C > T3172G > S:R346T (G22599C), S:F456L (T22928C) 
Query: G22599C, T22928C, T17859C, T3172G, T3565C
Samples: 6 (Portugal 4, Spain 2)
First collected in Madrid on 2024-03-22
IDs:EPI_ISL_19050411, EPI_ISL_19132939, EPI_ISL_19135497,
EPI_ISL_19135500-19135501, EPI_ISL_19135503
Tree:
<img width="1152" alt="Screenshot 2024-05-14 alle 23 46 14" src="https://github.com/cov-lineages/pango-designation/assets/87669813/49c6e95f-8464-4c2c-ac57-05e44e1a2916">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice6_genome_test_36311_3cdc50.json?c=gt-S_346,456&gmax=25384&gmin=21563&label=id:node_6984442

Query for the 493E singlet branch spotted by @NkRMnZr : C23039, T17859C, T3172G, T3565C count: 1
Query for TRIO branch Spotted by @aviczhl2 : T19104A ,C23277T,T3565C count: 3

**Comment by DailyCovidCases** [comment]
I think Branch 3 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089 is dying

**Comment by FedeGueli** [comment]
+2 Spain

**Comment by FedeGueli** [comment]
12 +1 uk

**Comment by FedeGueli** [comment]
19 multiple provinces of Spain

**Comment by FedeGueli** [comment]
35 now also in Israel and Ireland

**Comment by FedeGueli** [comment]
+5 ( 4 Portugal 1 Galicia)

**Comment by FedeGueli** [comment]
56 now, expanding in the course of the ongoing wave in Spain and Portugal

**Comment by DailyCovidCases** [comment]
Tracked in [tracker99](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=G22599C%2CT22928C%2CT17859C%2CT3172G%2CT3565C&nextcladePangoLineage=JN.1*&)

**Comment by aviczhl2** [comment]
There is a new S:T572I Trio branch emerged from this.

**Comment by DailyCovidCases** [comment]
@corneliusroemer

**Comment by FedeGueli** [comment]
> G22599C, T22928C, T17859C, T3172G, T3565C

I don't see any : 
<img width="1174" alt="Screenshot 2024-07-13 alle 15 17 13" src="https://github.com/user-attachments/assets/8e5cb1d0-4a23-4b0c-b423-4ed84f9d9ca8">

**Comment by aviczhl2** [comment]
![image](https://github.com/user-attachments/assets/b8eac0be-f361-4541-ad2d-d0bb4cf03682)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice267_genome_test_151ba_201c20.json?gt=S.572I&label=id:node_5453328

**Comment by FedeGueli** [comment]
> ![image](https://private-user-images.githubusercontent.com/10445944/348476293-b8eac0be-f361-4541-ad2d-d0bb4cf03682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4ODAwODYsIm5iZiI6MTcyMDg3OTc4NiwicGF0aCI6Ii8xMDQ0NTk0NC8zNDg0NzYyOTMtYjhlYWMwYmUtZjM2MS00NTQxLWFkMmQtZDBiYjRjZjAzNjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDE0MDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYmJlNjM3MWYwODUxMjliMjJkZTcxNTM1NjE4ODRjNjA4M2U1NGY4MTNmNTFjMjFlNzU2OGNjNzlmNjQ1ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R0TWFqx_NBD7MpmBzQLgGRrZf24rmchAcsHWBeq2RUY)
> 
> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice267_genome_test_151ba_201c20.json?gt=S.572I&label=id:node_5453328

oh what is your query i cant find any with mine.

**Comment by FedeGueli** [comment]
> i can't find

Just found they all have dropout at both 456L and 346T

**Comment by DailyCovidCases** [comment]
This branch might be dying off, please update this

**Comment by DailyCovidCases** [comment]
126 seqs now

**Comment by FedeGueli** [comment]
132

**Comment by DailyCovidCases** [comment]
@corneliusroemer This one seems to be ignored from designation for quite a long time

**Comment by DailyCovidCases** [comment]
135 seqs now: 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_58a9_778cd0.json?f_userOrOld=uploaded%20sample)
![Screenshot (166)](https://github.com/user-attachments/assets/0d57d868-6cb8-4747-a5de-ea1a0fe17532)
@corneliusroemer suggest to designate some trajectory of this

**Comment by DailyCovidCases** [comment]
This branch might be dying off, please close it

**Comment by aviczhl2** [comment]
This one is 141 now, with quite a few uploaded recently. This shouldn't be closed. 

@FedeGueli  Please ignore advices from DaliyCovidCases. He seems to be using some weird criteria.

**Comment by FedeGueli** [comment]
> This one is 141 now, with quite a few uploaded recently. This shouldn't be closed.
> 
> @FedeGueli Please ignore advices from DaliyCovidCases. He seems to be using some weird criteria.
Yeah for sure, but i was closing it becuase not expanding further, lets keep it open for a while more tough

**Comment by aviczhl2** [comment]
It is designated LF.6 as a sub-branch of JN.1.16.1. Shall be independent branch.

**Comment by FedeGueli** [comment]
LF.6 from https://github.com/cov-lineages/pango-designation/commit/8b27ff68dc12fe3913fca84b34a4b2e521335559

**Comment by AngieHinrichs** [comment]
@DailyCovidCases can you state your criteria for determining that a branch is dying?

Also, a bit of advice: when your comments are the same word-for-word, it gives the impression that you are running a script instead of critically evaluating the data.  I think it would help a lot to include your reason for judging a branch as dying.  For example, "This branch has had no new sequences since <date>, and since it was circulating in <country> that uploads sequences <regularly/monthly/sporadically/etc>, I would expect to have seen more sequences by now."  But not exactly in those words -- please tell us what you're thinking.  🙂  And then if FedeGueli or others tell you that your criteria need to be more complicated, then next time show that you applied the more complicated criteria.

**Comment by DailyCovidCases** [comment]
> @DailyCovidCases can you state your criteria for determining that a branch is dying?
> 
> Also, a bit of advice: when your comments are the same word-for-word, it gives the impression that you are running a script instead of critically evaluating the data. I think it would help a lot to include your reason for judging a branch as dying. For example, "This branch has had no new sequences since `<date>`, and since it was circulating in that uploads sequences `<regularly/monthly/sporadically/etc>`, I would expect to have seen more sequences by now." But not exactly in those words -- please tell us what you're thinking. 🙂 And then if FedeGueli or others tell you that your criteria need to be more complicated, then next time show that you applied the more complicated criteria.

My criteria: 4 weeks with 0 sequences updated and the branch will be counted as dead. Is it too quickly for you?

**Comment by AngieHinrichs** [comment]
> My criteria: 6 weeks with 0 sequences updated and the branch will be counted as dead. Is it too quickly?

6 weeks sounds reasonable to me for countries that have a shorter lag time from sample collection to release of sequences, like only a few weeks.  I think @FedeGueli has explained in a different issue that unfortunately many countries, especially countries with fewer resources, may take more than a month to get sequences and release them publicly.  So I think it depends on the country or region, not only the amount of time that has passed.  @FedeGueli @aviczhl2 do you have recommendations for specific criteria to apply, taking countries or regions into account?

It would be awesome if every country had the resources to rapidly sequence an adequate sample of positive test cases, and the willingness and ability to rapidly release the sequences.  But the reality is much more uneven.

**Comment by FedeGueli** [comment]
> > My criteria: 6 weeks with 0 sequences updated and the branch will be counted as dead. Is it too quickly?
> 
> 6 weeks sounds reasonable to me for countries that have a shorter lag time from sample collection to release of sequences, like only a few weeks. I think @FedeGueli has explained in a different issue that unfortunately many countries, especially countries with fewer resources, may take more than a month to get sequences and release them publicly. So I think it depends on the country or region, not only the amount of time that has passed. @FedeGueli @aviczhl2 do you have recommendations for specific criteria to apply, taking countries or regions into account?
> 
> It would be awesome if every country had the resources to rapidly sequence an adequate sample of positive test cases, and the willingness and ability to rapidly release the sequences. But the reality is much more uneven.

I prefer to use a different criteria % of sequences uploaded in the last month with uploads vs total number of sequences of that lineage if it is 10% it is better closing it.

**Comment by AngieHinrichs** [comment]
> I prefer to use a different criteria % of sequences uploaded in the last month with uploads vs total number of sequences of that lineage if it is 10% it is better closing it.

Thanks @FedeGueli!  If I rephrase it this way, does this sound correct?

1. Determine the last month in which sequences on the branch were uploaded (not the month in which the samples were collected).  This is the "last month with uploads."  [How to do this -- by doing a GISAID query and looking at the Submission Date column?]
2. Find the number of sequences on the branch that were uploaded in that month.
3. Divide that number by the total number of sequences on the branch.
4. If the ratio is less than 10%, then comment on the issue, including all the numbers.

?  Thanks.  🙂  Also, what if the last month in which sequences were uploaded was two months ago?  Three months ago?  Have you seen lag times longer than that?

**Comment by aviczhl2** [comment]
> > My criteria: 6 weeks with 0 sequences updated and the branch will be counted as dead. Is it too quickly?

> 6 weeks sounds reasonable to me for countries that have a shorter lag time from sample collection to release of sequences, like only a few weeks.

 

This criteria is not bad. However, I don't think he is actually using that criteria. 

Take this one for example, many seqs are collected in 7/1~7/22 and uploaded on 7/30~8/12 to GISAID. Clearly that's within the 6 weeks range, but he still comments "dying" for this. 

![image](https://github.com/user-attachments/assets/a7e13c74-afa7-4f47-bfd5-3843443a9d02)

**Comment by FedeGueli** [comment]
> > I prefer to use a different criteria % of sequences uploaded in the last month with uploads vs total number of sequences of that lineage if it is 10% it is better closing it.
> 
> Thanks @FedeGueli! If I rephrase it this way, does this sound correct?
> 
> 1. Determine the last month in which sequences on the branch were uploaded (not the month in which the samples were collected).  This is the "last month with uploads."  [How to do this -- by doing a GISAID query and looking at the Submission Date column?]
> 2. Find the number of sequences on the branch that were uploaded in that month.
> 3. Divide that number by the total number of sequences on the branch.
> 4. If the ratio is less than 10%, then comment on the issue, including all the numbers.
> 
> ? Thanks. 🙂 Also, what if the last month in which sequences were uploaded was two months ago? Three months ago? Have you seen lag times longer than that?

yes plus or less that one, if the country where it emerged or it is prevalent didnt upload or uploaded very small numbers in the last three months we usually in the other repo tag that kind of lineages as emerged in an undersampled area and we keep them alive.

**Comment by AngieHinrichs** [comment]
> Take this one for example, many seqs are collected in 7/1-7/22 and uploaded on 7/30-8/12 to GISAID. Clearly that's within the 6 weeks range, but he still comments "dying" for this.

Yes -- the original comment said "4 weeks" but then it was edited to say "6 weeks".  I guess that means that DailyCovidCases formerly applied a 4-week cutoff, but now is thinking 6 weeks.  

@DailyCovidCases in the future it would be more clear to explain the change in the comment instead of just changing a number.  And does the process for accounting for a country's delay make sense to you?

**Comment by aviczhl2** [comment]
> > Take this one for example, many seqs are collected in 7/1-7/22 and uploaded on 7/30-8/12 to GISAID. Clearly that's within the 6 weeks range, but he still comments "dying" for this.
> 
> Yes -- the original comment said "4 weeks" but then it was edited to say "6 weeks". I guess that means that DailyCovidCases formerly applied a 4-week cutoff, but now is thinking 6 weeks.
> 
> @DailyCovidCases in the future it would be more clear to explain the change in the comment instead of just changing a number. And does the process for accounting for a country's delay make sense to you?

But 4 weeks is also not what he is actually using. This one has samples uploaded from 8/12(less than 1 week) and collected in 7/22(3 weeks ago)

**Comment by aviczhl2** [comment]
@AngieHinrichs I prefer temperoraily banning him unless he open source his code and we verify it bug-free. Without seeing his code it is impossible to find what is the actual bug.

**Comment by aviczhl2** [comment]
@corneliusroemer  There seems more evidence of this one being a separate branch than JN.1.16.1

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_157d5_ea3e20.json?label=id:node_5462228)
![image](https://github.com/user-attachments/assets/1407744d-4d36-4c0c-ade4-1e66ef86073f)

**Comment by FedeGueli** [comment]
> the `S:Q493E` singlet now has a follow up with some accumulated spike mutations: ![image](https://private-user-images.githubusercontent.com/125747944/365439557-d046e1e1-c768-4911-ba07-42caba73765a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDQ5OTgsIm5iZiI6MTcyNTgwNDY5OCwicGF0aCI6Ii8xMjU3NDc5NDQvMzY1NDM5NTU3LWQwNDZlMWUxLWM3NjgtNDkxMS1iYTA3LTQyY2FiYTczNzY1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNDExMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGRkYzA5MWExNDNjMzIyMjIzYzBhZGY1M2ZkYzJiMDExMmY5ODA1MWY1M2JhMGRhZThhMWM2NjA2ZTRlOTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p8KhS5-V6TPpcvB-gNFf0E1ZQXaWRCTpb26uS6Eaqn0)
> 
> https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice51_genome_1a12c_d72dc0.json?label=id:node_11644668

thx we will track it here .

**Comment by FedeGueli** [comment]
the 493E branch seems dead
