### ISSUE TITLE
Proposal for a south american sublineage of B.1.617.2 with Orf3a:23V ( Parallel clade of the proposed #258 )

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#259]
Sublineage of B.1.617.2 
with mutations: Orf3a: A23V
circulating in Chile (15%), Brazil (around 2,5% in the last weeks) > 1000 sequences
![Schermata 2021-10-17 alle 14 13 52](https://user-images.githubusercontent.com/87669813/137626774-3905ca37-aa6b-4819-9d3d-58bde9d5a9c7.png)

I would start the Tree with Nucleotide T28007C
https://nextstrain.org/groups/neherlab/ncov/south-america?branchLabel=aa&c=gt-nuc_28007&tl=pango_lineage
![Schermata 2021-10-18 alle 00 37 03](https://user-images.githubusercontent.com/87669813/137647516-f81a9ca7-540e-4c41-b7d8-4cb4b70024e8.png)

or 
with Orf3A ( but we  could then regret to have missed the parent lineage)
https://nextstrain.org/groups/neherlab/ncov/south-america?branchLabel=aa&c=gt-ORF3a_239,23&label=spike_mutations:I95T&tl=pango_lineage
![Schermata 2021-10-17 alle 14 07 30](https://user-images.githubusercontent.com/87669813/137626736-2cc1b693-358b-4f68-a27b-17e764a9973f.png)

I think it is worth better defining the circulating viruses in South America in line with #258 Proposal
![Schermata 2021-10-17 alle 14 09 43](https://user-images.githubusercontent.com/87669813/137626732-4ce10fbb-df76-4c6c-9637-76ffc5d81dc8.png)

**Comment by chrisruis** [comment]
Thanks @FedeGueli It looks like in recent UShER trees, almost all of the sequences with Orf3a:A23V are included in AY.101. There are some South American sequences in AY.100 but they appear to be low frequency currently so don't warrant a designation at this stage

**Comment by FedeGueli** [comment]
Thank you very much @chrisruis
