### ISSUE TITLE
JN.1.1 with a S:R346T sublineage (1092 seqs)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2591]
Formerly tracked as Branch 3 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089
Defining mutations:
JN.1.1 > C11747T >S:R346T (G22599C)
Query: -G4720A,-C21952T,C11747T,G22599C, -C9142T,-C20629T,C1762A,-T3488C,-C21654T,-G22703A,-G23120T,-T22928C,-C21654T,-T25207C
Samples: 100
First:  EPI_ISL_18605963, 2023-11-20
Latest: EPI_ISL_19074693, 2024-4-10
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_17d3a_b4ea90.json?f_userOrOld=uploaded%20sample&label=id:node_7024446)
![Screenshot (50)](https://github.com/cov-lineages/pango-designation/assets/92421581/266eade0-dde9-4f6e-be3d-68de2c892522)

**Comment by FedeGueli** [comment]
This one was on hold casue the query catches a lot of unrelated samples

**Comment by DailyCovidCases** [comment]
![Screenshot (116)](https://github.com/cov-lineages/pango-designation/assets/92421581/10707dfc-dcb5-4992-8be4-ee70c30cc360)
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_13fd_4bf210.json?label=id:node_12105524)

**Comment by DailyCovidCases** [comment]
1092 seqs now

**Comment by aviczhl2** [comment]
This one was broadened to JN.1.1.3 long ago.

**Comment by FedeGueli** [comment]
> This one was broadened to JN.1.1.3 long ago.

cool didn't think that this was the result : https://github.com/cov-lineages/pango-designation/commit/0c19ec354cacce2f1703927bc9d863947e9afba3
