### ISSUE TITLE
JN.1.22 with Orf1a:G445V (38 sequences, 2 countries)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2595]
Previously tracked as Branch 16 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1.22 > Orf1a:G445V (G1599T) > C11704T > S:F456L (T22928C)
Query: G1599T, C11704T ,T22928C
No. of seqs: 38 (Spain 2 USA 36)
First: PP258906.1, 2024-01-10
Latest: EPI_ISL_19132380, 2024-04-25
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_104d7_a27d00.json?f_userOrOld=uploaded%20sample&gmax=29701&label=id:node_7003671&s=USA/NY-URMC-O4S1N942-1/2024%7CEPI_ISL_19132380%7C2024-04-25)
![Screenshot (48)](https://github.com/cov-lineages/pango-designation/assets/92421581/e521c454-dbac-4a4a-b30b-1216d58c599d)

**Comment by FedeGueli** [comment]
not fast.

**Comment by DailyCovidCases** [comment]
Tracked in [tracker16](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=G1599T%2CC11704T%2CT22928C&nextcladePangoLineage=JN.1.22*&)
