### ISSUE TITLE
JN.1.16  got  S:T572I  (277 mostly Spain , 15 countries)  

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2598]
cc @AngieHinrichs this is likely another misplacement due high convergence in JN.1:
It is displayed in the JN.1.30 tree but it lacks (or has it reverted) G21255T.
Instead it has C27573T

My propose route is:
JN.1.16 > C27573T  > Orf1b:T2432I (C20762T), S:T572I (C23277T)
Query: C27573T , C20762T, C23277T
Samples: 15
Country: Spain 13, US, UK
solved [Tree ( as mentioned above it is misplaced there because it lacks JN.1.30 defining G21255T:]
<img width="1163" alt="Screenshot 2024-05-20 alle 12 54 52" src="https://github.com/cov-lineages/pango-designation/assets/87669813/0baf27d4-e96f-4b4f-a09f-1093358b250f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_36e7f_b21640.json?label=id:node_7073772

It seems that there is an Orf3a:C153Y sublineage of this with a significant growth advantage:
Query: G25850A  ,C21590T,T3565C
Samples:22
tree:
<img width="1167" alt="Screenshot 2024-05-31 alle 16 14 17" src="https://github.com/cov-lineages/pango-designation/assets/87669813/7a95770e-03b6-4ed4-9551-d3d10c9d1e1f">

maybe just a cluster.

**Comment by FedeGueli** [comment]
+2 Canary Isl. , Uk

**Comment by AngieHinrichs** [comment]
This is in JN.1.16 now.

**Comment by FedeGueli** [comment]
It seems fast.

**Comment by FedeGueli** [comment]
43/28 now

**Comment by FedeGueli** [comment]
44/32

**Comment by FedeGueli** [comment]
54 now we samples coming outside from Spain : England, Scotland, Canary Islands, Japan.

@corneliusroemer this is the fastest undesignated lineage as of today (together with the other undesignated KP.2+S:S31del)

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by FedeGueli** [comment]
93 now. ping @corneliusroemer

**Comment by FedeGueli** [comment]
big jump to 190 in one week.

**Comment by FedeGueli** [comment]
202

**Comment by FedeGueli** [comment]
@corneliusroemer when you specified JN.1.16.3 you were meaning to designate this one? cause i don't see very much plain JN.1.16.3 (mostly from Hubei less than 10)

**Comment by FedeGueli** [comment]
Only a dozen of samples in July

**Comment by Over-There-Is** [comment]
293
