### ISSUE TITLE
New Lineage proposal: N.9 (sub-lineage of B.1.1.33)

### ISSUE THREAD

**Issue by paolacristinaresende** [cov-lineages/pango-designation#26]
Description
Sub-lineage of: **B.1.1.33**
Earliest sequence:  EPI_ISL_861899 - 11/11/2020
Most recent sequence: hCoV-19/Brazil/MA-FIOCRUZ-6876/2021 - 01/03/2021 - under submission in GISAID
Countries circulating: **Brazil**

I would like to suggest a new pangolin lineage to support the B.1.1.33(E484K) clade circulating in Brazil.
We would like to call this N.5 following the other sublineages inside the ancestor B.1.1.33 lineage. This branch is highly supported as we can see highlighted in Blue in the tree attached.
The defining mutations are NSP3:A1711V, NSP6:F36L, S:E484K and NS7b:E33A.

Genomes
[Data_N.5_lineage.txt](https://github.com/cov-lineages/pango-designation/files/6095194/Data_N.5_lineage.txt)

Evidence
![N 5](https://user-images.githubusercontent.com/80154344/110204320-24378080-7e51-11eb-897a-a2629aad592b.png)

Proposed lineage name **N.5**

**Comment by paolacristinaresende** [comment]
Hi all,
Yesterday, we posted on Virological.org a post about the description of this lineage in Brazil. We called this new lineage N.9, after contact with Aine.

https://virological.org/t/a-potential-sars-cov-2-variant-of-interest-voi-harboring-mutation-e484k-in-the-spike-protein-was-identified-within-lineage-b-1-1-33-circulating-in-brazil/645

Please let us know if any change happened.
Cheers,
Paola

**Comment by aineniamh** [comment]
Designated N.9 in latest releases!
