### ISSUE TITLE
Proposal for a South Korean delta 21I sub-lineage with ORF3a:A110S (~3.5k sequences, ~77% prevalence in Korea)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#260]
Description
**Sub-lineage of**: B.1.617.2 (3544 sequences on GISAID as of 2021/10/18)
**Earliest sequence**: 2021/5/29 (South Korea)
**Most recent sequence**: 2021/9/26 (South Korea)
**Countries circulating**: predominantly South Korea
![image](https://user-images.githubusercontent.com/86835836/137661666-7c76f697-a700-4d09-8bf6-606c9a82fcb8.png)

**Mutations in addition to B.1.617.2**:
ORF1a:V3718A, T3750I
then ORF3a:A110S,
then ORF1a:I1525V, ORF1a:V3056I, ORF1b:V1133I and nuc C27559T,
then ORF8:G66V (largely reversed later),
then nuc C4405T,
then ORF1a:T1240I and nuc G17847A

**Genomes**:
[Delta Korea.csv](https://github.com/cov-lineages/pango-designation/files/7361585/Delta.Korea.csv)

**Evidence**:
**UShER subtree**:
![image](https://user-images.githubusercontent.com/86835836/137663117-c6fc9c3b-8077-45ed-a6aa-647483d11685.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_bcee_cd8d80.json?c=gt-nuc_3984,25720&l=radial

**NeherLab (in orange color)**:
![image](https://user-images.githubusercontent.com/86835836/137663603-b1463d67-6a8f-4057-9394-d20ee2347112.png)
![image](https://user-images.githubusercontent.com/86835836/137663707-9b1c447c-b4fb-4a7e-b19a-ec62918102ed.png)
https://nextstrain.org/groups/neherlab/ncov/asia-south-korea?c=gt-nuc_27559,3984&p=grid&r=division

**Transmissibility advantage and local prevalence as per Cov-Spectrum**:
![image](https://user-images.githubusercontent.com/86835836/137663220-ac4bc2b3-8694-4341-abd2-de8ff3710bde.png)
![image](https://user-images.githubusercontent.com/86835836/137663383-1d49dfa0-1833-4a8f-8635-dc00ac9dbce9.png)
https://cov-spectrum.ethz.ch/explore/South%20Korea/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22mutations%22%3A[%22ORF3a%3AA110S%22%2C%22ORF1a%3AT1240I%22]%7D%2C%22matchPercentage%22%3A1%7D

**Comment by corneliusroemer** [comment]
Very interesting!

This lineage is part of Nextstrain 21I, that's the smaller one with S:222V.

I would make the lineage a bit broader than you suggested, including the blue part, since it is also exclusively in South Korea.

These would be defining instead:
ORF3a:A110S, ORF1a:I1525V, ORF1a:V3056I, ORF1b:V1133I

![Screenshot_20211018-123144.jpg](https://user-images.githubusercontent.com/25161793/137715301-20a70d48-3d47-4650-9ebb-dc280f64582a.jpg)

![Screenshot_20211018-123209.jpg](https://user-images.githubusercontent.com/25161793/137715693-33f577c9-1b55-4322-abae-641d1dd1e260.jpg)

**Comment by c19850727** [comment]
@corneliusroemer sure, already done.

**Comment by FedeGueli** [comment]
This has been designated as AY.69 starting with A4838G (Orf1ab:I1525V),G9431A (Orf1ab:V3056I),G16864A (Orf1ab:V5534I),C27559T (synonymous)
according to: https://www.pango.network/summary-of-designated-ay-lineages/

cc @chrisruis @c19850727 @corneliusroemer 

tree:
![Schermata 2021-11-01 alle 21 12 21](https://user-images.githubusercontent.com/87669813/139735404-5de1817d-3663-4e04-95ce-d1d7a81aa19c.png)
