### ISSUE TITLE
JN.1.4.5 + S:R346T that further gained S:T732I (65 seqs, 9 countries)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2601]
From branch 16 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089
JN.1.4.5 (Orf8:S103L ) >C28201T > C28948T > S:R346T (G22599C) that further gained S:T732I
Query: C774T, C28948T, G22599C
Samples : 52 (China 3 Japan 41 Mexico 1 Myanmar 2 Singapore 3 Thailand 1 US 1)
First: EPI_ISL_18604882, 2023-11-30
Latest: EPI_ISL_19095925, 2024-4-19
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_a02f_c5d9f0.json?f_userOrOld=uploaded%20sample)
![Screenshot (53)](https://github.com/cov-lineages/pango-designation/assets/92421581/8b2a75ec-024d-433a-834d-caecd1780f04)

**Comment by FedeGueli** [comment]
74 ,  but two only samples from June

**Comment by DailyCovidCases** [comment]
This branch is dead, I will close it now

**Comment by DailyCovidCases** [comment]
Tree now: 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_f88e_e2c6e0.json?f_userOrOld=uploaded%20sample)
![Screenshot (218)](https://github.com/user-attachments/assets/e6b7057e-1eff-412c-85a9-0da2fd91cee9)

**Comment by FedeGueli** [comment]
82 with 2 from August one from France one from Singapore both without S:T732I
