### ISSUE TITLE
JN.1.4 with Orf1a:D4117N, S:T22N and S:R346T (37 seqs)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2602]
From branch 24 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089
JN.1.4 > T18453C > C7732T, Orf1a:D4117N (G12614A),S:T22N (C21627A), G22111A, S:R346T (G22599C), C27944T
Query: T18453C ,C7732T, ,G12614A,G22599C
Samples : 37 ( US 36 Mexico 1)
First: EPI_ISL_18730727, 2023-12-16
Latest: PP774304.1, 2024-04-21
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2e6_e10d00.json?f_userOrOld=uploaded%20sample)
![Screenshot (63)](https://github.com/cov-lineages/pango-designation/assets/92421581/3644e407-c4d6-4156-9a7b-bf620cd99edc)

**Comment by FedeGueli** [comment]
New Query: C27944T,G12614A,C774T, G22599C 
samples: 40
It seems S:T22N came before S:R346T but it is not possible to exclude it was acquired multiple times independently by this lineage
Current tree:
<img width="1155" alt="Screenshot 2024-06-30 alle 16 14 04" src="https://github.com/cov-lineages/pango-designation/assets/87669813/de6c0a90-bae5-4026-8cbd-067586c7d461">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice13_genome_test_318ef_115640.json?label=id:node_7107010

**Comment by ryhisner** [comment]
Just 2 sequences since April 21 for a lineage that first appeared in December. Makes sense to close this issue I think.

**Comment by DailyCovidCases** [comment]
This branch is dead now, I will close it

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1c9d3_e32510.json?c=pango_lineage&f_userOrOld=uploaded%20sample)
![Screenshot (220)](https://github.com/user-attachments/assets/f875bb2a-107d-4b53-858b-8f5a962eae0a)
@corneliusroemer Is this branch worth a designation?

**Comment by FedeGueli** [comment]
54 with the new query: C27944T,G12614A,C774T, G22599C 
3 samples after July ( 1 in August)
