### ISSUE TITLE
KP.1 + S:R346T on Orf1a:G519S (11 seqs)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2603]
From branch 68 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089
KP.1 > Orf1a:G519S (G1820A)> S:R346T (G22599C)
Query: G1820A, A24819G, G22599C, T3565C
Samples: 5 (3 on UShER , Oman 2 USA 1)
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1e820_f26730.json?f_userOrOld=uploaded%20sample)
![Screenshot (65)](https://github.com/cov-lineages/pango-designation/assets/92421581/df38c647-71b3-46c1-b42c-97755e37f7ea)

**Comment by FedeGueli** [comment]
5 samples now

**Comment by FedeGueli** [comment]
this is now 25 with mayority samples coming from multiple countries in late June ( and a Canadian cluster) please reopen this.

**Comment by FedeGueli** [comment]
> this is now 25 with mayority samples coming from multiple countries in late June ( and a Canadian cluster) please reopen this.
<img width="1172" alt="Screenshot 2024-07-14 alle 10 40 15" src="https://github.com/user-attachments/assets/b5cf93b1-4637-444f-af57-8950823d436a">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_3688a_38eae0.json?f_userOrOld=uploaded%20sample
scratch that not monophyletic!!
