### ISSUE TITLE
JN.1.26 + S:F456L on C7732T branch (72 seqs)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2605]
From branch 30 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1.26+S:F456L
Query: C26894T, C7732T,G22599C, T22928C
No. of seqs: 32 (Canada 26 USA 6)
First: EPI_ISL_18945673, 2024-2-17
Latest: EPI_ISL_19142000, 2024-4-30
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2828_65910.json?f_userOrOld=uploaded%20sample)
![Screenshot (67)](https://github.com/cov-lineages/pango-designation/assets/92421581/baff7dd4-8da3-4f71-b491-7507251ebfb7)

**Comment by FedeGueli** [comment]
This is FLiRT

**Comment by FedeGueli** [comment]
52 now

**Comment by DailyCovidCases** [comment]
This branch is dead, I will close it

**Comment by FedeGueli** [comment]
71 now with C26894T, C7732T,G22599C, T22928C

**Comment by DailyCovidCases** [comment]
Why does it say 0 seqs here?
[tracker30](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=C26894T%2CC7732T%2CG22599C%2CT22928C&nextcladePangoLineage=JN.1.26*&)

**Comment by DailyCovidCases** [comment]
Tree now:
![Screenshot (167)](https://github.com/user-attachments/assets/d6cbfb2f-b78b-4194-a03f-922c07169a9e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_406df_86f170.json?f_userOrOld=uploaded%20sample&label=id:node_7200922

**Comment by FedeGueli** [comment]
The most recent sample has been collected at the start of July, not sure if worth tracking it further
