### ISSUE TITLE
JN.1.4.5 + S:F456L with C28201T branch (96 seqs)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2607]
From branch 21 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1.4.5+S:F456L
Query: C28201T, T22928C, T22926C, -C28948T,-G2654A,-C3177T,-20823
No. of seqs: 46 (USA 18 New Zealand 2 Australia 9 Sweden 2 Spain 3 Greece 3 Israel 1 China 7 Switzerland 1)
First: EPI_ISL_18614037, 2023-11-26
Latest: EPI_ISL_19150487, 2024-05-14
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1d7fd_b4fb0.json?f_userOrOld=uploaded%20sample&label=id:node_7113042)
![Screenshot (73)](https://github.com/cov-lineages/pango-designation/assets/92421581/460b72fd-d3fc-412e-bffe-ac65dd7f18cb)

**Comment by FedeGueli** [comment]
59 now

**Comment by DailyCovidCases** [comment]
71 now

**Comment by FedeGueli** [comment]
not monophyletic at all close it down please (or find a good query):
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_41bb9_3f4f80.json?f_userOrOld=uploaded%20sample&label=id:node_6942273
<img width="1158" alt="Screenshot 2024-07-14 alle 18 14 03" src="https://github.com/user-attachments/assets/e901f21e-8e79-489b-bcfe-e838f2a57cb8">

**Comment by DailyCovidCases** [comment]
Tracked in [tracker21](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=C28201T%2CT22928C%2CT22926C&nextcladePangoLineage=JN.1.4.5*&)

**Comment by FedeGueli** [comment]
it is not monophyletic. 47 have S:S31del and are form several variants spanning from XDY to LB.1s please close this.
ping @corneliusroemer 
<img width="1135" alt="Screenshot 2024-08-27 alle 00 47 06" src="https://github.com/user-attachments/assets/35028de6-0cd5-4b49-8650-c68fd4ce9fdd">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_5717e_d059c0.json?f_userOrOld=uploaded%20sample&label=id:node_6948800

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_6ab0_3c4660.json?c=pango_lineage&f_userOrOld=uploaded%20sample)
![Screenshot (237)](https://github.com/user-attachments/assets/6d88ec53-17aa-470c-b391-e6ba7790e911)

**Comment by FedeGueli** [comment]
Close this no recent samples
