### ISSUE TITLE
Fixing existing assignments of AY lineages

### ISSUE THREAD

**Issue by andersonbrito** [cov-lineages/pango-designation#261]
By Anderson Brito
Description: Some AY lineages do not cluster as monophyletic groups. Below you can find proposals of corrections to existing assignments AY lineages.

**Genomes**
Click [here](https://www.dropbox.com/s/o1n2wvxooc6tnpj/AYcorrections.zip?dl=0) to download a compressed file with lists of genomes from correct and incorrect assignments within AY lineages.

In that compressed file one can find separate files with the following naming format:
> "ay1_correct_headers.tsv" = list of genomes _correctly_ assigned to lineage AY.1 (largest monophyletic clade)
> "ay1_incorrect_headers.tsv" = list of genomes _incorrectly_ assigned to lineage AY.1 (singletons and small clades)

**Evidence**
Drop [this file](https://www.dropbox.com/s/3mgj0z1grb77bii/correct_assignments.tsv?dl=0) on this [nextstrain build](https://nextstrain.org/community/andersonbrito/ncovbr/delta?c=pango_lineage&m=div&r=division) to see the proposed corrections. Switch the `Color by` to 'Lineage' to see how the assignments differ.

**Comment by chrisruis** [comment]
Thanks @andersonbrito We've had a major update of designations to these lineages which should have helped assignments. It's possible to run pangolin with the --usher flag which may improve assignments in some cases. We're also regularly checking the designated sequences to make sure they cluster within their designated lineage
