### ISSUE TITLE
XDK+S:F456L+N:G30V, Orf9b:V30L on C29762T branch(47, GB-EN 45, CN-HK 2), most with S:R237K(GB-EN 45) and then S:Q1201K(42)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2610]
Transferred from sars-cov-2-variants/lineage-proposals#1572

XDK> C29762T> T22297C, T22928C(S:F456L), G28371T(N:G30V, Orf9b:V30L)> A1633G, G22272A(S:R237K)> C25162A, C25163A(S:Q1201K)
G28371T is also in a BA.5.2.1 branch with BF.7,  BF.38, etc., and an FE.1.1 branch with FE.1.1.3.
C25162A, C25163A is also in BF.7.10, BF.38.1 and KP.2.1.

Query: C5314T, T22297C, T22928C

Earliest sequence: 04-16 Shatin, Hong Kong SAR, China EPI_ISL_19146025
Latest sequence: 05-10 England, United Kingdom EPI_ISL_19161837
Regions Detected: UK 45(England), China 2(Hong Kong)

![2024-05-25](https://github.com/cov-lineages/pango-designation/assets/38100637/231154e1-4708-47c3-a76b-fc1cf46b7d80)
[nextclade.auspice.json](https://github.com/cov-lineages/pango-designation/files/15442718/nextclade.auspice.json)

<details><summary>Sequences:</summary>

EPI_ISL_19088230, EPI_ISL_19088237, EPI_ISL_19133005,
EPI_ISL_19133026, EPI_ISL_19133032, EPI_ISL_19133042,
EPI_ISL_19139191, EPI_ISL_19139197, EPI_ISL_19143961,
EPI_ISL_19146025, EPI_ISL_19146029, EPI_ISL_19146684,
EPI_ISL_19146688, EPI_ISL_19146702, EPI_ISL_19146706,
EPI_ISL_19146708, EPI_ISL_19146773, EPI_ISL_19151204,
EPI_ISL_19157209-19157214, EPI_ISL_19157216-19157217, EPI_ISL_19157219-19157220,
EPI_ISL_19157223, EPI_ISL_19157231-19157233, EPI_ISL_19157235,
EPI_ISL_19157238, EPI_ISL_19157241, EPI_ISL_19157248,
EPI_ISL_19157250, EPI_ISL_19157264, EPI_ISL_19157270-19157271,
EPI_ISL_19157274, EPI_ISL_19157277-19157279, EPI_ISL_19157287,
EPI_ISL_19161837, EPI_ISL_19161854
</details>

**Comment by Over-There-Is** [comment]
@FedeGueli

**Comment by FedeGueli** [comment]
<img width="599" alt="Screenshot 2024-05-25 alle 17 12 05" src="https://github.com/cov-lineages/pango-designation/assets/87669813/da8f4c2d-6109-441d-b00c-a466e4e81570">
this should be the real pattern there.
<img width="113" alt="Screenshot 2024-05-25 alle 17 14 10" src="https://github.com/cov-lineages/pango-designation/assets/87669813/cfe3c454-2d7b-4418-b7b8-cdcf25ff5da9">

**Comment by Over-There-Is** [comment]
FE.1.1.3 has G28371T too. But why this branch evolves C25162A, C25163A combo like BF.7.10 and BF.38.1?

**Comment by Over-There-Is** [comment]
FE.1.1.3 has G28371T too. But why this branch evolves C25162A, C25163A combo like BF.7.10 and BF.38.1?

**Comment by FedeGueli** [comment]
> FE.1.1.3 has G28371T too. But why this branch evolves C25162A, C25163A combo convergent to BF.7.10 and BF.38.1?

that is very common double nuc mutation

**Comment by aviczhl2** [comment]
Designated XDK.6

**Comment by FedeGueli** [comment]
via https://github.com/cov-lineages/pango-designation/commit/8bd6644bd4309f49d32f5a6f801346269d2529de
