### ISSUE TITLE
XDK+C22388T  branch with  S:F456L rising in Spain (37)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2611]
previosuly mentioned in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253 comments
XDK (572I) > C22388T (S:L276L) > S:F456L (T22928C) 
Query: C5314T, T22928C,C22388T 
Samples: 37
Tree:
<img width="1170" alt="Screenshot 2024-05-26 alle 01 36 03" src="https://github.com/cov-lineages/pango-designation/assets/87669813/90398a6f-e2a3-4369-8ac8-4a11fb928cdf">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice6_genome_test_53192_26cc50.json?label=id:node_7038405

IDs:
EPI_ISL_19044628, EPI_ISL_19050425, EPI_ISL_19072142,
EPI_ISL_19072151, EPI_ISL_19072219, EPI_ISL_19095496,
EPI_ISL_19095502-19095505, EPI_ISL_19095512, EPI_ISL_19095541,
EPI_ISL_19108705, EPI_ISL_19108708-19108709, EPI_ISL_19108711,
EPI_ISL_19108713, EPI_ISL_19109639, EPI_ISL_19131030,
EPI_ISL_19132717, EPI_ISL_19134313, EPI_ISL_19140782,
EPI_ISL_19140800, EPI_ISL_19141033, EPI_ISL_19144189,
EPI_ISL_19145539, EPI_ISL_19145552, EPI_ISL_19145567,
EPI_ISL_19146301, EPI_ISL_19146369, EPI_ISL_19146491,
EPI_ISL_19153943, EPI_ISL_19157475, EPI_ISL_19162083,
EPI_ISL_19162095, EPI_ISL_19162108, EPI_ISL_19162539,

**Comment by aviczhl2** [comment]
Designated XDK.5

**Comment by FedeGueli** [comment]
Designated XDK.5 via https://github.com/cov-lineages/pango-designation/commit/f6c8c34fab8f2ed6fa6cae01d14abce886e3fa03

**Comment by FedeGueli** [comment]
added PR
