### ISSUE TITLE
JN.1.4.2+S:S680F+S:F456L with C23601T branch (54 seqs, 4 countries)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2615]
From branch 52 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1.4.2+S:S680F+S:F456L(T22930A)
Query: T22930A, C23601T, A22115G
No. of seqs: 58 (Israel 1 New Zealand 6 Canada 1 USA 46)
First: PP218753.1, 2024-1-13
Latest: EPI_ISL_19153588, 2024-5-14
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_28450_4adf00.json?f_userOrOld=uploaded%20sample)
![Screenshot (88)](https://github.com/cov-lineages/pango-designation/assets/92421581/7df72682-5768-4390-ac26-5693de419bf3)

**Comment by aviczhl2** [comment]
Designated LL.1

**Comment by FedeGueli** [comment]
via https://github.com/cov-lineages/pango-designation/commit/891b587110a8c753bd224c51bae14168b8701eed
