### ISSUE TITLE
New sub-lineages within B.1.617.2 (Delta)

### ISSUE THREAD

**Issue by andersonbrito** [cov-lineages/pango-designation#262]
By Anderson Brito

Description: New sub-lineages within B.1.617.2 (Delta).

Sub-lineage of: B.1.617.2

> Proposed lineage name: AY.42
> Earliest sequence: 2021-01-02
> Most recent sequence: 2021-10-04
> Countries circulating: USA, India
> Clade-defining SNP: S:T95I (C21846T)
> 
> Proposed lineage name: AY.43
> Earliest sequence: 2021-07-15
> Most recent sequence: 2021-09-28
> Countries circulating: USA
> Clade-defining SNP: ORF1b:A1847S (C8829T, G19006T)
> 
> Proposed lineage name: AY.44
> Earliest sequence: 2020-09-09
> Most recent sequence: 2021-09-29
> Countries circulating: USA
> Clade-defining SNP: C6040T
> 
> Proposed lineage name: AY.45
> Earliest sequence: 2021-03-04
> Most recent sequence: 2021-09-22
> Countries circulating: USA
> Clade-defining SNP: S:G142D (G21987A)
> 
> Proposed lineage name: AY.46
> Earliest sequence: 2021-05-19
> Most recent sequence: 2021-09-20
> Countries circulating: USA
> Clade-defining SNP: C29541T

**Genomes**
 Click [here](https://www.dropbox.com/s/9m28w5ag1ga3x81/new_AY_lineages.zip?dl=0) to download a compressed file with lists of genomes from each of the proposed AY lineages.

**Evidence**
Drop [this file](https://www.dropbox.com/s/iu7pj560s01i3qu/new_lineages.tsv?dl=0) on this [nextstrain build](https://nextstrain.org/community/andersonbrito/ncovbr/delta) to see the proposed lineages (unders `Color by` = 'new_lineages'). Switch the `Color by` to 'Lineage' to see how those clades are currently classified.

**Comment by chrisruis** [comment]
Thanks @andersonbrito We've recently added a lot more AY lineages and each of these was designated as part of this:
Your proposed AY.42 is designated AY.118
Your proposed AY.43 is designated AY.119
Your proposed AY.44 is designated AY.44
Your proposed AY.45 is designated AY.103
Your proposed AY.46 is designated AY.37
