### ISSUE TITLE
JN.1 + S:F456L with Orf3a:A54S (32 seqs) of which 27 seqs has S:G213E (T22200A)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2621]
From branch 53 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1+Orf3a:A54S+S:F456L(T22930A)
Query: G25552T,T22930A,C18894T
No. of seqs: 18 (USA)
First: EPI_ISL_18964427, 2024-1-26
Latest: PP701896.1, 2024-4-6
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_298b0_5bb140.json?f_userOrOld=uploaded%20sample&label=id:node_6977718)
![Screenshot (90)](https://github.com/cov-lineages/pango-designation/assets/92421581/4a3cd58a-2fc7-4c51-99bb-425b7a4e1a8e)

**Comment by FedeGueli** [comment]
21 but only two samples from MAy i would close this down

**Comment by DailyCovidCases** [comment]
Tracked in [tracker53](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=G25552T%2CT22930A%2CC18894T&nextcladePangoLineage=JN.1*&)

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3beae_5131d0.json?f_userOrOld=uploaded%20sample)
![Screenshot (188)](https://github.com/user-attachments/assets/a516f6fc-2f13-4cb2-880a-9501ca974057)

**Comment by FedeGueli** [comment]
@DailyCovidCases thx for reopening, however it is likely slow but please add the S:G213E mutation to the title and  if you can add T22200A (=213E) to the query. In that way @corneliusroemer can evaluate if the double spike mutation is worth to be designated or not. thx.

**Comment by DailyCovidCases** [comment]
Tree now: 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_30da9_7bd2e0.json?f_userOrOld=uploaded%20sample)
![Screenshot (191)](https://github.com/user-attachments/assets/6f271245-51fa-4798-b4c8-77709baa71e8)
However this picture only show 15 seqs, while the S:G213E mutation has 27

**Comment by FedeGueli** [comment]
thx

**Comment by FedeGueli** [comment]
Last samples from July please close it
