### ISSUE TITLE
JN.1 + S:F456L with C26873T branch (409 seqs)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2622]
From branch 51 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1+C26873T+S:F456L, 
Query: T22928C, C26873T, C18894T
No. of seqs: 59 (Australia 2 Canada 28 China 5 Germany 1 Japan 1 Netherlands 1 New Zealand 5 Portugal 1 Singapore 3 South Korea 2 USA 10)
First: EPI_ISL_18896825, 2024-1-18
Latest:  EPI_ISL_19153513, 2024-5-12
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_238de_6bcc70.json?f_userOrOld=uploaded%20sample)
![Screenshot (91)](https://github.com/cov-lineages/pango-designation/assets/92421581/89cdae16-81ca-471b-b7d0-052095dbb44d)

**Comment by FedeGueli** [comment]
Close this one not monophyletic:
<img width="948" alt="Screenshot 2024-06-17 alle 10 54 14" src="https://github.com/cov-lineages/pango-designation/assets/87669813/c3dee0fe-ea2f-4e76-a01f-37254b28ab45">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_1aa84_ff9170.json?f_userOrOld=uploaded%20sample&label=id:node_7029116

**Comment by DailyCovidCases** [comment]
Tracked in [tracker51](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=T22928C%2CC26873T%2CC18894T&nextcladePangoLineage=JN.1*&)

**Comment by DailyCovidCases** [comment]
Now 376 seqs

**Comment by FedeGueli** [comment]
> Close this one not monophyletic: <img alt="Screenshot 2024-06-17 alle 10 54 14" width="948" src="https://private-user-images.githubusercontent.com/87669813/340241715-c3dee0fe-ea2f-4e76-a01f-37254b28ab45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDI3NDUsIm5iZiI6MTcyNTQ0MjQ0NSwicGF0aCI6Ii84NzY2OTgxMy8zNDAyNDE3MTUtYzNkZWUwZmUtZWEyZi00ZTc2LWEwMWYtMzcyNTRiMjhhYjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA5MzQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjIzOTFhMDI0NGNkNmRjNzk4YTIzYTg2MmQyOTNmMDQzNGQyYzM1ZTA0ODc1MDM1NThjODI1OTQ1OWU0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RbGwnh5VOEUE2sWPmPg88n2V6dv9kNPlNrgvm_uPVGU"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_1aa84_ff9170.json?f_userOrOld=uploaded%20sample&label=id:node_7029116

this is not monophyletic , if you see any branch growing you have to modify the query and the proposal and the title then

**Comment by ryhisner** [comment]
<img width="1185" alt="image" src="https://github.com/user-attachments/assets/11376722-1c06-4588-b800-bdc62c97c96f">
