### ISSUE TITLE
Undesignated JN.1.18 plus S:F59S went FLiRT (44) with a S:F65Y,Q183P branch (11) 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2623]
**EDITED VERSION** (14/06/2024)
 
Initially it was tracked as Branch 118  of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089
it is  different from JN.1.18.2 because it lacks both T22321C and C4331T

 

JN.1.18 > S:F59S (T21738C)> S:F456L (T22928C)  >> S:F65Y (T21756A), S:Q183P (A22110C), T28693C
 
**Query for JN.1.18+S:F59S FLiRT T22928C** : 
T22928C,T21738C,T3565C,G22599C,-C25680T,-C7113T,-G22111T,-G17334T,-C1762A,-C774T,-C25566T,-C26894T,-C7002T,-A3941G,-C26004T
Samples:20
Countries: 7 Uk, US, Qatar, Spain, France, Germany
IDs:  EPI_ISL_19130874, EPI_ISL_19146801, EPI_ISL_19146863,
EPI_ISL_19151361, EPI_ISL_19153096, EPI_ISL_19153109,
EPI_ISL_19156827, EPI_ISL_19174104,
EPI_ISL_19177941, EPI_ISL_19177998, EPI_ISL_19179355,
EPI_ISL_19183059,  , EPI_ISL_19185559-19185560,
EPI_ISL_19186343, EPI_ISL_19189742,  
 
**Query for  the S:F65Y,S:Q183P sublineage** :   T21756A, A22110C , T3565C,T22928C
or new query : T21756A, A22110C, T28693C, T21738C by @aviczhl2 in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1634
Samples: 4
Countries: 3
IDs:EPI_ISL_19177691, EPI_ISL_19177998, EPI_ISL_19183070,
EPI_ISL_19194774

Tree:
<img width="1149" alt="Screenshot 2024-06-14 alle 11 51 27" src="https://github.com/cov-lineages/pango-designation/assets/87669813/1cc1cf88-0dd8-40bf-bf04-7d5fbd8574dd">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_21aa9_c0b5d0.json?c=userOrOld&label=id:node_7143771

**********************

To be noticed that from JN.1.18> S:F59S stem out some more interesting lineages that i put below to the attention of @corneliusroemer :
Lineage 2 
Query for FLiRT T22930A : C18348T ,t3565C,T22930A  
Samples:6 
Countries:UK
EPI_ISL_19088229, EPI_ISL_19088233, EPI_ISL_19088235,
EPI_ISL_19130893, EPI_ISL_19151197, EPI_ISL_19151347

Lineage 3
Query for S:D1260Y + S:T22N: A1900G, G25340T,C21627A
Samples: 4
Countries:
Uk, CHina, France
IDs: EPI_ISL_19146983, EPI_ISL_19167472

**Comment by aviczhl2** [comment]
Is there a direct JN.1+S:F59S branch?

**Comment by FedeGueli** [comment]
> Is there a direct JN.1+S:F59S branch?

Not that i am aware of

**Comment by FedeGueli** [comment]
@corneliusroemer please take a look at this branch.

**Comment by FedeGueli** [comment]
@corneliusroemer i have edited the proposal pls take a look.

**Comment by FedeGueli** [comment]
27 - 5 for the subbranch

**Comment by FedeGueli** [comment]
36/10

**Comment by aviczhl2** [comment]
Designated JN.1.18.6 and LY.1

**Comment by FedeGueli** [comment]
Lineage 3 designated JN.1.18.7 via https://github.com/cov-lineages/pango-designation/commit/8349a3841affe73bdae955739d9af75c7e2f46c3

**Comment by FedeGueli** [comment]
designated JN.1.18.6 via https://github.com/cov-lineages/pango-designation/commit/40ed9bf3ff1588edbd692b8fd33bdba066963c80 
and LY.1 via https://github.com/cov-lineages/pango-designation/commit/3cdd87c309cd17351fa2f570fbe4cfb508516177

**Comment by FedeGueli** [comment]
parent of this is now JN.1.18.9
>To be noticed that from JN.1.18> S:F59S stem out some more interesting lineages that i put below to the attention of @corneliusroemer :
Lineage 2 Dead
Query for FLiRT T22930A : C18348T ,t3565C,T22930A
Samples:8
Countries:UK
EPI_ISL_19088229, EPI_ISL_19088233, EPI_ISL_19088235,
EPI_ISL_19130893, EPI_ISL_19151197, EPI_ISL_19151347
