### ISSUE TITLE
JN.1.22/XDD.1 recombinant(53 seqs, 2 countries, 13 with S:F456L)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2624]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1397

XDD.1--JN.1.22--XDD.1

Breakpoint 1 between 3566 and 5719
Breakpoint 2 between 13020 and 23972

Private mutations:G12111A,C19164T

GISAID query: C13019T, A6183G, C29625T
GISAID query for S:F456L sub-branch: C13019T, A6183G, C29625T,T22928C
No. of seqs: 35(Spain)
First: EPI_ISL_18927194, 2024-2-13
Latest: EPI_ISL_19167759, 2024-5-22

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_22_xdd_1_recomb.json?label=id:node_7035632)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/6a78358b-c25b-4a21-b188-d1b8b74b9024)

**Comment by FedeGueli** [comment]
around 1 % in Spain in May

**Comment by aviczhl2** [comment]
Spreads to France.

**Comment by FedeGueli** [comment]
+1 Galicia

**Comment by aviczhl2** [comment]
Dead
