### ISSUE TITLE
KP.3 with C18490T(ORF1b:P1675S)(309seqs) 

### ISSUE THREAD

**Issue by Memorablea** [cov-lineages/pango-designation#2627]
from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1562
KP.3>C18490T（ORF1b:P1675S/ORF1ab:P6076S）
Query: C23039G,C18490T
![image](https://github.com/cov-lineages/pango-designation/assets/125779492/937821f0-4d70-41e8-9bc7-3e3ad974ed5b)

**Comment by Memorablea** [comment]
309

**Comment by FedeGueli** [comment]
Designated KP.3.1.4 via https://github.com/cov-lineages/pango-designation/commit/000e4446ff22dd2a53003e11e26d99b2e3c6a2c6
