### ISSUE TITLE
JN.1.4 + S:F456L with C9979T branch (18 seqs, 2 countries)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2630]
From branch 10 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1.4 + C9979T + S:F456L
Query: T18453C, T22928C,C9979T
No. of seqs: 18 (Norway 1 Sweden 17)

First: EPI_ISL_18754441, 2024-1-3
Latest: EPI_ISL_19044733, 2024-3-8
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2ab90_9fa3c0.json?f_userOrOld=uploaded%20sample)
![Screenshot (93)](https://github.com/cov-lineages/pango-designation/assets/92421581/b63867d5-a71a-4b8a-8141-2f1a92468c8b)

**Comment by FedeGueli** [comment]
you have already proposed this in https://github.com/cov-lineages/pango-designation/issues/2599
