### ISSUE TITLE
Lineage note distinctive mutation for JN.1.56 is incorrect.

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#2631]
The lineage note for JN.1.56 is incorrect. It specifies ORF3a:K399R as the distinctive mutation, and ORF3a's highest residue is 275, so this note must be incorrect. The commit logs also have the same error.

The correct mutation may be ORF3a:Q213K.

**Comment by FedeGueli** [comment]
> The lineage note for JN.1.56 is incorrect. It specifies ORF3a:K399R as the distinctive mutation, and ORF3a's highest residue is 275, so this note must be incorrect. The commit logs also have the same error.
> 
> The correct mutation may be ORF3a:Q213K.

Thank you i ve already Pull Requested it!

**Comment by DailyCovidCases** [comment]
You can close this issue now
