### ISSUE TITLE
Proposal for European AY.4 sub-lineage with N:232S, ORF1b:2313S (~3k, 10% in Denmark)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#264]
New lineage proposal
by @CorneliusRoemer after tip-off from @shay671 who discovered it

Description
Sub-lineage of: AY.4
Earliest sequence: UK 2021-25, then in 2021-29: Switzerland, Sweden, Germany, Denmark, almost all EU countries by 2021-32
Most recent sequence: Current
Countries circulating: 10% in Denmark, but ~1% in many EU countries

Lineage deriving from AY.4 with N:232S, ORF1b:2313S. The lineage has an interesting spread: It appeared a few times in the UK from 2021-25, and then suddenly popped up all over Europe 4 weeks later - which is strange: why would a lineage that seems to have originated in the UK establish itself around Europe but decline in the UK?

It's established itself at low levels in almost all EU countries. It accounts for 10% of cases in Denmark. It has a really interesting long branch with 8 extra mutations in Denmark containing AA muts: ORF1a:671V, ORF1a:3140M, ORF1a:3353R, ORF1a:475F plus 4 synonymous. I checked whether this could be a recombination event, but couldn't find another lineage that shares more than 1 of the mutations on the branch.

![image](https://user-images.githubusercontent.com/25161793/137801929-70d5652c-d756-4630-9e22-2f86c13a002f.png)
https://nextstrain.org/groups/neherlab/ncov/europe?branchLabel=aa&c=gt-ORF1b_2313&m=div

![image](https://user-images.githubusercontent.com/25161793/137802251-2d92553e-705a-47b7-9e3c-4a139136d788.png)

![image](https://user-images.githubusercontent.com/25161793/137802263-b9eba753-7797-4c2f-bd84-ab96f06e2cc5.png)

![image](https://user-images.githubusercontent.com/25161793/137802267-fe29a1fb-81db-4d78-abbc-d106ffe3c047.png)

![image](https://user-images.githubusercontent.com/25161793/137802271-44951cbf-af7b-440f-9f23-8fd00eb660e7.png)

![image](https://user-images.githubusercontent.com/25161793/137802274-464ca971-f686-42f3-85ae-91c71f6edaa3.png)

Country | Total Variant Sequences | First seq. found at | Last seq. found at
-- | -- | -- | --
United Kingdom | 30 | 2021-25 | 2021-38
Switzerland | 53 | 2021-29 | 2021-38
Sweden | 31 | 2021-29 | 2021-39
Germany | 463 | 2021-29 | 2021-41
Denmark | 2581 | 2021-29 | 2021-40
USA | 11 | 2021-30 | 2021-37
Finland | 4 | 2021-30 | 2021-32
Japan | 15 | 2021-30 | 2021-32
Turkey | 67 | 2021-30 | 2021-39
Belgium | 38 | 2021-30 | 2021-37
Netherlands | 90 | 2021-31 | 2021-39
Czech Republic | 49 | 2021-31 | 2021-39
Slovakia | 7 | 2021-31 | 2021-34
Israel | 3 | 2021-31 | 2021-31
France | 10 | 2021-32 | 2021-38
Romania | 1 | 2021-32 | 2021-32
Bulgaria | 2 | 2021-32 | 2021-33
Norway | 1 | 2021-32 | 2021-32
Lithuania | 2 | 2021-33 | 2021-33
Russia | 2 | 2021-33 | 2021-34
Italy | 5 | 2021-34 | 2021-35
Spain | 1 | 2021-35 | 2021-35
Poland | 1 | 2021-39 | 2021-39

[https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/Past6M/variants?aaMutations=orf1b%3A2313s%2Cn%3A232G%2Corf1a%3A2529V&pangoLineage=B.1.617.2*](https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/Past6M/variants?aaMutations=orf1b%3A2313s%2Cn%3A232G%2Corf1a%3A2529V&pangoLineage=B.1.617.2*)

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as AY.4.6 in [v1.2.103](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.103) to start on a branch with C20404T (Orf1ab:P6714S) which corresponds to the non-UK clade

**Comment by shay671** [comment]
Hi @chrisruis  

There is a sub lineage of AY.4.6 which i think should also been designated (AY.4.6.X). And this for 2 main reasons :

1. It's the main branch of AY.4.6, rose to dominance of this branch :
![image](https://user-images.githubusercontent.com/80166370/143938015-3ce1d80b-72d5-4f13-9e67-a26301dfc37d.png)


2. It seems to be a result of a mutation jump (i hope this time i did this correct). I took the AY.4.6 total samples and run it on Usher, the long branch of this clade is clearly visible. 
![image](https://user-images.githubusercontent.com/80166370/143938661-0ae1ce4b-5cf0-47ef-a7c4-d6957b8771b8.png)



https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_28171_52fe50.json?c=gt-nuc_20404,209&label=nuc%20mutations:C16293T,C19524T,A28967G

The mutations for this branch are :
C140T, T209C, A2276G (NSP2:I491V), T2308C , A9685G (NSP4:I377M), T10084A, A10323G(NSP5:K90R), G10688T(NSP5:V212F)
