### ISSUE TITLE
KP.3.1 + ∆29728-29776 (bigger s2m deletion) [485 seq, Aug 16]

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2646]
### Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1573
**Description**
**Sub-lineage of:** KP.3.1 (JN.1.11.1.3 = JN.1 + S:F456L, Q493E, V1104L)
**Earliest sequence:** 2024-4-15, Australia, Victoria — EPI_ISL_19084514
**Most recent sequence:** 2024-5-6, Spain, Madrid — EPI_ISL_19144199
**Continents circulating:** Oceania (7), Asia (2), Europe (2)
**Countries circulating:** Australia (5), New Zealand (2), Spain (2), China (1), Singapore (1)
**Number of Sequences:** 11
**GISAID Nucleotide Query:** A1620G, G15372T, -G29734
**CovSpectrum Query:** Nextcladepangolineage:KP.3* & [2-of: A1620G, G15372T] & [1-of: 29729-, !29735-]
**Substitutions/Deletions on top of KP.3:**
**ORF1a:** E452G (NSP2_E282G)
**Nucleotide:** G15372T, A19722G, A1620G, ∆29728-29733 + ∆29760-29776

**Phylogenetic Order of Mutations:** G15372T, A19722G **→** A1620G (ORF1a:E452G), ∆29728-29733 + ∆ 29760-29776 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.3_29728-29776.json?c=gt-ORF1ab_452&gmax=21555&gmin=266&label=id:node_2371524

<img width="1410" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/51383d4c-b42d-4517-b156-9d48519e168b">
<img width="1414" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/b8303e78-e730-496c-ad5b-e0a484410be0">

**Evidence**
BA.2 was the first global variant to feature a deletion in s2m, a 3' UTR stem-loop that is highly conserved in sarbecoviruses. All Omicron since BA.1 have had ∆29734-29759. This sublineage adds 23 nucleotides to the standard Omicron s2m deletion with ∆29728-29776. When the s2m deletion is enlarged, this is the most common pattern. s2m's function is unknown, and the reason for its deletion in BA.2/4/5 is also a mystery. 

<img width="1496" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/0fbfb7ba-4610-4744-8fc2-5d3c31011e75">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19084514, EPI_ISL_19095989, EPI_ISL_19122535,
EPI_ISL_19122574, EPI_ISL_19122576, EPI_ISL_19122578,
EPI_ISL_19134818, EPI_ISL_19142295, EPI_ISL_19142321,
EPI_ISL_19144199, EPI_ISL_19146486</details>

**Comment by aviczhl2** [comment]
This has a large S:K679R--S:L176F branch now. 
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/ebebf7ac-2245-4ecc-9c82-17ed982e4320)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice59_genome_test_5e445_fb01a0.json?label=id:node_5450611

**Comment by FedeGueli** [comment]
> This has a large S:K679R--S:L176F branch now. ![image](https://private-user-images.githubusercontent.com/10445944/344556004-ebebf7ac-2245-4ecc-9c82-17ed982e4320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjIwNjIsIm5iZiI6MTcxOTgyMTc2MiwicGF0aCI6Ii8xMDQ0NTk0NC8zNDQ1NTYwMDQtZWJlYmY3YWMtMjI0NS00ZWNjLTljODItMTdlZDk4MmU0MzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA4MTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYmIwNDVmNGFhN2M4YzY2OGY4M2ZiNWY5YzE4ZTQ0MDZiM2NkOGM5ZWJhOTg1MjNjYzRmM2E2ZWE1MmZkOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U4RiGhTKXgdD8soweh-96maGLdPXjtVnVy9QIpbj4bc)
> 
> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice59_genome_test_5e445_fb01a0.json?label=id:node_5450611

Query: C14216T, A23598G,T3565C

**Comment by FedeGueli** [comment]
It is now 213 with 37 with S:K679R cc @ryhisner @corneliusroemer

**Comment by ryhisner** [comment]
Still around in decent numbers, but not growing fast, Closing.
