### ISSUE TITLE
KP.1.1+Orf1b:L2213F+S:N185del, F186I(331 seqs, >10 places, 17 with S:S31F, 7 with further S:K478T rev, 6 with further S:F32S, further recombinant proposed in #2791)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2649]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1509

Other than KP.1.1.1(S:K182N), other seqs on the Orf1b:L2213F branch of KP.1.1 have another NTD mutation set that usher doesn't display.

KP.1.1+C20104T(Orf1b:L2213F)+del22115_22117,T22118A(S:N185-, F186I)

GISAID query: T22926C,C7113,T22118A,A24819G
GISAID query for S:S31F sub-branch: T22926C,C7113,T22118A,C21654T,A24819G
GISAID query for S:K478T rev further branch:C7113,T22118A,C21654T,-22995,A24819G
GISAID query for S:F32S further branch:C7113,T22118A,C21654T,-22995,T21657C

GISAID query for recombinant with additional S:T22N but losing S:K1086R:C25587T, C26195T,A26927G (#2791)

K478T branch--KP.2

Breakpoint between 22119 and 24818

Additional mutations: C21627A,C25587T, C26195T,A26927G
S:T22N
Orf3a:T268M

one of C25587T,C26195T,A26927G from a JN.1.11.1* branch(multiple potential choices)
C21627A and the other 2 of C25587T,C26195T,A26927G are private

No. of seqs: 117(Australia 1 Canada 10 Denmark 2 UK 35 France 14 Germany 1 India 2 Ireland 1 Japan 12 Nepal 2 South Korea 1 Singapore 7 Spain 5 Thailand 1 USA 20(2 from Qatar, 2 from France, 1 from India, 1 from South Africa, 2 from UK))

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/kp_1_1_n185-_f186i.json?f_userOrOld=uploaded%20sample&label=id:node_6999015)

Usher doesn't display this deletion+mutation and simply put it next to KP.1.1.1. Most seqs on KP.1.1+Orf1b:L2213F branch that is not KP.1.1.1 are in this branch. 

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/01fe5c7f-afc0-4a6c-b834-caafc62c3fc4)

Further stepwise S:S31F-S:K478T-recombinant losing S:K1086R but getting S:T22N branch found by @FedeGueli :
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_50bcb_9e8d40.json?label=id:node_5730247
![image](https://github.com/user-attachments/assets/a81614e0-2292-45bf-b5bf-5f0a4bf011c2)

**Comment by FedeGueli** [comment]
136 now with 3 samples collected in June , 2 in Hubei. ping @corneliusroemer

**Comment by aviczhl2** [comment]
167, Netherlands, China, Portugal, Malaysia, New Zealand

**Comment by aviczhl2** [comment]
186, Iceland

**Comment by aviczhl2** [comment]
213, Norway, Italy, Mexico

**Comment by FedeGueli** [comment]
231 ping @corneliusroemer worth a designation this one

**Comment by aviczhl2** [comment]
253, Sweden

**Comment by aviczhl2** [comment]
276, Luxembourg

**Comment by aviczhl2** [comment]
284, UAE

**Comment by aviczhl2** [comment]
289, Israel

**Comment by aviczhl2** [comment]
309, Poland

**Comment by aviczhl2** [comment]
@AngieHinrichs This is another example of non-displayed AA change thing.

**Comment by aviczhl2** [comment]
314, Czech Republic

**Comment by DailyCovidCases** [comment]
ping @corneliusroemer worth a designation this one

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_6393_f88470.json?c=pango_lineage&f_userOrOld=uploaded%20sample)
Tracked in [Issue 2649](https://cov-spectrum.org/explore/World/AllSamples/from%3D2024-01-01%26to%3D2024-09-15/variants?aaMutations=ORF1b%3AL2213F%2CS%3AN185-&nucMutations=C20104T&nextcladePangoLineage=KP.1.1*&)
![Screenshot (224)](https://github.com/user-attachments/assets/37da5f21-c030-4082-9eed-21794e5ebc14)
I think @corneliusroemer this branch should get designated

**Comment by aviczhl2** [comment]
Edited proposal to include #2791

**Comment by FedeGueli** [comment]
> Edited proposal to include the recombinant described in #2791
> 
> KP.1.1+S:N185-,F186I,S:S31F, S:K478T rev, S:T22N, and recombines with a KP.2 branch to lose S:K1086R, breakpoint between 22119 and 24818

thx!

**Comment by xz-keg** [comment]
![image](https://github.com/user-attachments/assets/06fa9654-eaf5-4272-9354-1b8bcb1c5754)
There is a further S:F32S branch besides the recombinant, now 6 seqs. @FedeGueli

**Comment by xz-keg** [comment]
355/23/13/6 now

**Comment by FedeGueli** [comment]
> C7113,T22118A,C21654T,-22995,T21657C

wow. thx

**Comment by FedeGueli** [comment]
@xz-keg some of the new S:F32S branch have 182K (rev) do u think it is real?

**Comment by xz-keg** [comment]
> @xz-keg some of the new S:F32S branch have 182K (rev) do u think it is real?

182N is for KP.1.1.1, this one is not KP.1.1.1, it is KP.1.1+N185-, F186I so it shall have 182K which is not rev( as it never had 182 mutated to anything else)

**Comment by FedeGueli** [comment]
> > @xz-keg some of the new S:F32S branch have 182K (rev) do u think it is real?
> 
> 182N is for KP.1.1.1, this one is not KP.1.1.1, it is KP.1.1+N185-, F186I so it shall have 182K which is not rev( as it never had 182 mutated to anything else)

yeah yeah sorry my bad

**Comment by xz-keg** [comment]
365-32-22-6

**Comment by FedeGueli** [comment]
> 365-32-22-6

@xz-keg i was scratching a bit my head around this but it seems to me that the 478T branch doesnt exist as such: it is the recombinant and the S:F32S branch 
<img width="1171" alt="Screenshot 2024-10-14 alle 11 19 57" src="https://github.com/user-attachments/assets/5dce4e1f-55d4-46cc-bf62-7fca5dc34a99">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_59dad_ce1a60.json?f_userOrOld=uploaded%20sample&label=id:node_7358966

**Comment by xz-keg** [comment]
> > 365-32-22-6
> 
> @xz-keg i was scratching a bit my head around this but it seems to me that the 478T branch doesnt exist as such: it is the recombinant and the S:F32S branch <img alt="Screenshot 2024-10-14 alle 11 19 57" width="1171" src="https://private-user-images.githubusercontent.com/87669813/376179077-5dce4e1f-55d4-46cc-bf62-7fca5dc34a99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTkwMDUsIm5iZiI6MTcyODg5ODcwNSwicGF0aCI6Ii84NzY2OTgxMy8zNzYxNzkwNzctNWRjZTRlMWYtNTVkNC00NmNjLWJmNjItN2ZjYTVkYzM0YTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA5MzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYzI4NWYxYzhkNDU4MTlhNjRhNzFiZTY3YjJkYmEzNTg3NzQ3ODYxNjFhZDY4NzQ3OWVhM2NkYmM2ZjA3ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tXBbZ8m756UufqiIL5-xF45OBLGFO8lnBeLtX9KTpj8"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_59dad_ce1a60.json?f_userOrOld=uploaded%20sample&label=id:node_7358966

Yeah I adjust query to exclude the recomb by forcing it to have S:K1086R. 331-17-7-6 now.

**Comment by FedeGueli** [comment]
> > > 365-32-22-6
> > 
> > 
> > @xz-keg i was scratching a bit my head around this but it seems to me that the 478T branch doesnt exist as such: it is the recombinant and the S:F32S branch <img alt="Screenshot 2024-10-14 alle 11 19 57" width="1171" src="https://private-user-images.githubusercontent.com/87669813/376179077-5dce4e1f-55d4-46cc-bf62-7fca5dc34a99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTkwMDUsIm5iZiI6MTcyODg5ODcwNSwicGF0aCI6Ii84NzY2OTgxMy8zNzYxNzkwNzctNWRjZTRlMWYtNTVkNC00NmNjLWJmNjItN2ZjYTVkYzM0YTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA5MzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYzI4NWYxYzhkNDU4MTlhNjRhNzFiZTY3YjJkYmEzNTg3NzQ3ODYxNjFhZDY4NzQ3OWVhM2NkYmM2ZjA3ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tXBbZ8m756UufqiIL5-xF45OBLGFO8lnBeLtX9KTpj8"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_59dad_ce1a60.json?f_userOrOld=uploaded%20sample&label=id:node_7358966
> 
> Yeah I adjust query to exclude the recomb and other similar recombs by forcing it to have S:K1086R. 331-17-7-6 now.

to me being 6/7 with 32S is not useful as of today.

**Comment by DailyCovidCases** [comment]
@corneliusroemer please designate this branch

**Comment by DailyCovidCases** [comment]
Grow advantage now:
![Screenshot (267)](https://github.com/user-attachments/assets/880f77cd-35c4-49ef-a9ad-139b3e4748b5)

**Comment by FedeGueli** [comment]
Designated KP.1.1.6 via https://github.com/cov-lineages/pango-designation/commit/6637343d6226fd8dac057fdea05d39c1c51f419b

**Comment by FedeGueli** [comment]
S:F32S creates a  new N Glycan at S:N30 , this path to gain a new N Glycan was also recently designated in ND.1.1.3
