### ISSUE TITLE
New DeFLiRT : JN.1.16.1 with S:S31del and Orf8:Q29* emerged recently in France (53 seqs, 12 countries )

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2652]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1590

JN.1.16.1>> N:R385K (G29427A) > Orf1a:T4368I (C13368T) > Orf1a:G519S (G1820A) > S:S31del (del21653_55), G8824A, Orf8:Q29* (C27978T )
Query:C13368T,del21653, G1820A
Samples: 21 
Countries: France (5 different regions), Italy , Spain, NYC, Qatar (via GBW), Canada , UK 
First collected on 2024-04-16
IDs: EPI_ISL_19157165, EPI_ISL_19162603, EPI_ISL_19166117,
EPI_ISL_19166138, EPI_ISL_19173792, EPI_ISL_19174164,
EPI_ISL_19175832, EPI_ISL_19179051, EPI_ISL_19184850,
EPI_ISL_19187673, EPI_ISL_19189739, EPI_ISL_19189743-19189744,
EPI_ISL_19189754, EPI_ISL_19189770, EPI_ISL_19189772,
EPI_ISL_19190899, EPI_ISL_19191421, EPI_ISL_19191423,
EPI_ISL_19191441, EPI_ISL_19191525

Tree:
<img width="1159" alt="Screenshot 2024-06-12 alle 14 21 52" src="https://github.com/cov-lineages/pango-designation/assets/87669813/33d16996-3b57-4314-ae33-ffe8d39d9b05">
<img width="1167" alt="Screenshot 2024-06-12 alle 14 22 18" src="https://github.com/cov-lineages/pango-designation/assets/87669813/db471633-d353-4359-8004-edeb7f332f26">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5525e_992c90.json?label=id:node_7140940

**Comment by FedeGueli** [comment]
ping @corneliusroemer @AngieHinrichs  interesting one due the comeback of an Orf8 truncation on a competitive DeFLiRT backbone. Orf8:Q29stop came together with S:S31del in the same node.

**Comment by FedeGueli** [comment]
+2 from 2 different region of Spain

**Comment by FedeGueli** [comment]
32 now also in French Guyana. ping @corneliusroemer

**Comment by FedeGueli** [comment]
46 now with recent samples coming from France , Spain and Qatar (via GBW) ping @corneliusroemer i suggest to designate it

**Comment by FedeGueli** [comment]
53 expanding in multiple countries.

**Comment by aviczhl2** [comment]
Designated LF.4.1

**Comment by FedeGueli** [comment]
Designated LF.4.1 via https://github.com/cov-lineages/pango-designation/commit/6c579b80861260450f670f8d640e6d193f7679e0
