### ISSUE TITLE
JN.1.18.2 (59S) Flirt lineage mostly with Orf10:Q29* (60 seqs 15 countries 6 continents) and further S:K478E (3,Hubei)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2653]
From Branch 147 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089

Defining mutations: JN.1.18.2 ( S:R346T+S:F59S) > Orf1a:K1226E (A3941G) > S:F456L (T22928C) > Orf10:Q29* (C29642T)
Query: A3941G ,T22928C, T21738C
Samples: 12 
Countries: Hubei, Hong Kong Taiwan, Australia,New Zealand, England , US (Colorado)
IDs:
EPI_ISL_19145817, EPI_ISL_19150615, EPI_ISL_19164254,
EPI_ISL_19164437, EPI_ISL_19179007, EPI_ISL_19179014,
EPI_ISL_19179199, EPI_ISL_19186710, EPI_ISL_19186728,
EPI_ISL_19187084, EPI_ISL_19187283, EPI_ISL_19193264,

Tree:
<img width="1168" alt="Screenshot 2024-06-14 alle 10 31 44" src="https://github.com/cov-lineages/pango-designation/assets/87669813/5dfd5609-3946-4fe2-aaee-531acfa42ec4">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_33207_bfc510.json?label=id:node_7142877

**Comment by FedeGueli** [comment]
Likely dying off

**Comment by FedeGueli** [comment]
23 now it seems back on the rise.

**Comment by FedeGueli** [comment]
29, new country Mexico (via GBW)

**Comment by FedeGueli** [comment]
44 this is still around in China and has a noticeable geographical distribution , 1/3 of samples have been collected in July, i would keep it open for a while even if it is not super fast.

**Comment by aviczhl2** [comment]
It seems that Orf10:Q29* is not necessarily defining this branch now. 

![image](https://github.com/user-attachments/assets/03c784bf-9a37-4cc9-b4fa-07eaa65c0963)

**Comment by FedeGueli** [comment]
60 with 13 new uploads from 3 different regions of China and one from Malaysia , worth designating it.
it is around 4% of Chinese samples  after July 15

**Comment by FedeGueli** [comment]
Dwesignated LZ.2 via https://github.com/cov-lineages/pango-designation/commit/2c6deafbe1cc1a52cd7c282d9bd5719189962d0c

**Comment by aviczhl2** [comment]
The Orf10:Q29* sub-branch is designated LZ.2.1
