### ISSUE TITLE
JN.1.18.2 (S:F59S) FLirt lineage emerging fast in Puerto Rico - 10% prevalence (50 samples) with further S:P217S, S:N1125S (37) and a Canadian cluster with S:Q675R (8)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2654]
_Now also Branch 108 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253_ (edited 6/25)

Defining mutations: JN.1.18.2 > > T23377C (silent S:S605S) > Orf1a:I740V (A2483G) > N:A152T (G28727A) > S:F456L (T22930A)> S:P217S (C22211T), S:N1125S (A24936G)
Query for JN.1.18.2 Plus S:F456L(T22930A): A2483G,G28727A,T3565C,-C19017T
or ( **T22930A, T22321C, T21738C** By @aviczhl2  in # 1253)
Samples: 19  (Puerto Rico, Dominica Republic,Uk, Canada) 
IDs: EPI_ISL_19157245, EPI_ISL_19165198, EPI_ISL_19165269,
EPI_ISL_19184739, EPI_ISL_19184743, EPI_ISL_19184746,
EPI_ISL_19185021, EPI_ISL_19185798, EPI_ISL_19185826,
EPI_ISL_19190670, EPI_ISL_19192966, EPI_ISL_19192971-19192972,
EPI_ISL_19192974, EPI_ISL_19192979, EPI_ISL_19192987,
EPI_ISL_19192994, EPI_ISL_19192998, EPI_ISL_19193004,

Query for S:P217S+S:N1125S sublineage: C22211T, A24936G
Samples: 13  (Puerto Rico, Dominican Republic)
IDs: EPI_ISL_19184739, EPI_ISL_19184743, EPI_ISL_19184746,
EPI_ISL_19190670, EPI_ISL_19192966, EPI_ISL_19192971-19192972,
EPI_ISL_19192974, EPI_ISL_19192979, EPI_ISL_19192987,
EPI_ISL_19192994, EPI_ISL_19192998, EPI_ISL_19193004,

Tree as of 6-26:
 
<img width="1167" alt="Screenshot 2024-06-26 alle 01 27 19" src="https://github.com/cov-lineages/pango-designation/assets/87669813/51ba7ffc-e51c-4c77-9e20-1df59ffe6e68">

[https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_43cbc_b516b0.json?label=id:node_7170166](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_43cbc_b516b0.json?label=id:node_7170166)

There is also a cluster in Canada with S:Q675R 
Query: C3583T,A23586G, G26951C
Samples: 8

**Comment by aviczhl2** [comment]
Pls update, 42 seqs now with query T22930A, T22321C, T21738C

**Comment by FedeGueli** [comment]
50 FLirt and 37 with further 217S/1125S ping @corneliusroemer

**Comment by FedeGueli** [comment]
> Pls update, 42 seqs now with query T22930A, T22321C, T21738C

original query still finds more sequences.

**Comment by aviczhl2** [comment]
Designated LZ.1 and LZ.1.1

**Comment by FedeGueli** [comment]
Desingated LZ.1 and LZ.1.1 via https://github.com/cov-lineages/pango-designation/commit/c0e97bd72b1bcc8e0f3cd14d2f85757a078f7aff
