### ISSUE TITLE
JN.1.3+S:F456L with Orf8:Q18* (C27945T branch) (95 seqs)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2655]
From branch 25 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1.3+S:F456L 
Query: T3565C,T22928C,C27945T,-C4777T
No. of seqs: 62
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_36bc0_2c0e0.json?label=id:node_6945345)
![Screenshot (113)](https://github.com/cov-lineages/pango-designation/assets/92421581/c5c0f0f3-cd14-4b7c-800d-962157d91a5f)

**Comment by FedeGueli** [comment]
ping @corneliusroemer  this is very interesting it has Orf8:Q18* and then 456L and then 190S:
<img width="1173" alt="Screenshot 2024-06-16 alle 11 48 23" src="https://github.com/cov-lineages/pango-designation/assets/87669813/75d651c5-d5fa-4f2a-853c-5df9c45de460">
<img width="1163" alt="Screenshot 2024-06-16 alle 11 48 38" src="https://github.com/cov-lineages/pango-designation/assets/87669813/b9f10ae5-51d8-43bf-abdf-0611cc3a706d">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_5fd27_eb3700.json?c=gt-S_456&gmax=25384&gmin=21563&label=id:node_6945828

Query for the S:R190S branch (the one that is still around): C2156T, G18079A, A20486C
Samples:10 
EPI_ISL_18847465, EPI_ISL_18878653, EPI_ISL_18878658,
EPI_ISL_18885936, EPI_ISL_18931712, EPI_ISL_19146012,
EPI_ISL_19146014, EPI_ISL_19162530, EPI_ISL_19162533,
EPI_ISL_19164065

thx @DailyCovidCases

**Comment by FedeGueli** [comment]
Btw 27945T corresponds to Orf8:Q18* please add it to the title @DailyCovidCases

**Comment by DailyCovidCases** [comment]
307 seqs with Orf8:Q18* now

**Comment by FedeGueli** [comment]
i see 62, can you check?

**Comment by DailyCovidCases** [comment]
I think you should send me an image

**Comment by DailyCovidCases** [comment]
How can you find the correct query of this issue?. I used this website:
[nextclade](https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-10-01%26to%3D2024-06-22/variants?nucMutations=C27945T&nextcladePangoLineage=JN.1.3*&)

**Comment by FedeGueli** [comment]
> How can you find the correct query of this issue?. I used this website: [nextclade](https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-10-01%26to%3D2024-06-22/variants?nucMutations=C27945T&nextcladePangoLineage=JN.1.3*&) I type JN.1.3+S:F456L and it says 0 sequences!

Try orf8:Q18*, S:456L, T3565C,

**Comment by DailyCovidCases** [comment]
It still says there are 0 sequences! Maybe your query is incorrect

**Comment by FedeGueli** [comment]
don't add JN.1.3 and [you will get (click)](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?%2FAllSamples%2FPast3M%2Fvariants%3FnextcladePangoLineage=JN.1*&aaMutations=orf8%3AQ18*%2CS%3A456L&nucMutations=T3565C&nucMutations1=C13297T%2CA13121T&)

Anyway and more important this lineage got S:R190S

So the proposal should be edited: 
JN.1.3> T22928C> ORF1a:L631F (C2156T) Orf1b:V1538I (G18079A), S:R190S (G22132T), C26907T, T29689C
Query: C2156T, G18079A, G22132T

Samples: 30

Please edit the proposal

Ping @corneliusroemer  this is quite interesting 
Tree:
<img width="1170" alt="Screenshot 2024-06-29 alle 23 55 42" src="https://github.com/cov-lineages/pango-designation/assets/87669813/28179013-9ab4-4218-b6d4-d38b3a80fbb2">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2a0a7_a700.json?label=id:node_6945677

**Comment by DailyCovidCases** [comment]
Tracked in [tracker25](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?%2FAllSamples%2FPast3M%2Fvariants%3FnextcladePangoLineage=JN.1*&aaMutations=orf8%3AQ18*%2CS%3A456L&nucMutations=T3565C&nucMutations1=C13297T%2CA13121T&)

**Comment by DailyCovidCases** [comment]
This branch is not monophyletic, so I will count it as dead

**Comment by DailyCovidCases** [comment]
Tree now: 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_226c0_ac8fb0.json?f_userOrOld=uploaded%20sample&label=id:node_6958853)
![Screenshot (168)](https://github.com/user-attachments/assets/0949d2cb-7c4c-4e9d-8375-ce99e1c268ca)

**Comment by FedeGueli** [comment]
All the recent samples are from other lineages it is no more monophyletic:

<img width="1165" alt="Screenshot 2024-08-27 alle 15 50 29" src="https://github.com/user-attachments/assets/258de781-3e53-44ac-bb70-f0b657bd09a4">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_5958_dd85d0.json?f_userOrOld=uploaded%20sample&label=id:node_6948800

**Comment by DailyCovidCases** [comment]
This lineage are no longer monophyletic. Closing this.
