### ISSUE TITLE
Proposal for a small sub-clade of AY.23 with S:E702V in Europe (262 sequences)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#266]
I am thinking these small clade might be worth keeping an eye on, as it's a sub-branch of a predominantly SE Asian lineage introduced into Europe.
![image](https://user-images.githubusercontent.com/86835836/137841347-03c630d2-c8d1-4825-9cd0-17f278dc8375.png)

**Sub-lineage of:** AY.23 (262 sequences)
**Earliest sequence**: 2021/7/22 (Switzerland)
**Most recent sequence**: 2021/10/9 (Sweden)
**Countries circulating**:  Sweden (81 sequences), Germany (77 sequences), and a few other European countries.

Cumulative prevalence and number of sequences as per Outbreak.info:
![image](https://user-images.githubusercontent.com/86835836/137840960-7dcfe12b-afe7-4191-b5f3-2297dab81e41.png)

**Mutations in addition to AY.23**:
C15960T,
then A20979G,
then ORF1a:R3880G and S:E702V

Genomes:
[AY.23+E702V.csv](https://github.com/cov-lineages/pango-designation/files/7370114/AY.23%2BE702V.csv)

**Evidence**:
UsHER subree of AY.23:
![image](https://user-images.githubusercontent.com/86835836/137842545-0e465b75-c1d8-4f36-8936-9dae765ee9d0.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_5c55_e35f00.json?c=gt-nuc_1263,11903&l=radial

Downsized  sequences of AY.23 in Europe as per LeherLab:
![image](https://user-images.githubusercontent.com/86835836/137842143-429a19f0-7482-4462-b72a-551b6ac217c9.png)
https://nextstrain.org/groups/neherlab/ncov/sweden?c=gt-ORF1a_3880&f_pango_lineage=AY.23&p=grid&r=division

Transmission advantage of AY.23+S:E702V+ORF1a:R3880G as per CoV-Spectrum:
![image](https://user-images.githubusercontent.com/86835836/137843079-63de9650-a996-4fab-8548-bbc91ac3dc84.png)
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22mutations%22%3A[%22S%3AE702V%22%2C%22ORF1a%3A3880G%22]%7D%2C%22matchPercentage%22%3A1%7D

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as AY.23.2 in [v1.2.103](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.103) to start on a branch with T3718A (synonymous), A11903G (Orf1ab:R2880G) and A23667T (S:E702V) which likely coincides with the introduction(s) into Europe
