### ISSUE TITLE
JN.1+S:F456L possible dead branch

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2660]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
Branch 44: 10 seqs, last sample was on 19 April 2024 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_12394_bcb5e0.json?f_userOrOld=uploaded%20sample)
Branch 85: 5 seqs, last sample was on 6 May 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_27e70_fa240.json?f_userOrOld=uploaded%20sample)
Branch 78: 4 seqs, last sample was on 20 May 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1d5e4_f8f00.json?f_userOrOld=uploaded%20sample)
Branch 97: 4 seqs, last sample was on 15 May 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_248d4_18cb50.json?f_userOrOld=uploaded%20sample)
Branch 90: 5 seqs, last sample was on 30 April 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_25805_18d050.json?f_userOrOld=uploaded%20sample)

**Comment by FedeGueli** [comment]
All corrected now please close this.

**Comment by DailyCovidCases** [comment]
Branch 76: 10 seqs, last sample was on 14 May 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_f66d_22fd70.json?f_userOrOld=uploaded%20sample)
Branch 89: 7 seqs, last sample was on 27 April 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_40df5_231050.json?f_userOrOld=uploaded%20sample)
Branch 88: 8 seqs, last sample was on 25 April 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_41fdf_231ab0.json?f_userOrOld=uploaded%20sample)
Branch 53: 26 seqs, last sample was on 13 May 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_9e9_233880.json?f_userOrOld=uploaded%20sample)

**Comment by FedeGueli** [comment]
Alll corrected but. Branch 79 is far from dead

**Comment by FedeGueli** [comment]
branch 89 not dead

**Comment by FedeGueli** [comment]
All corrected now , please close or trnasfer it to the secondary repo, Pango repo is not thought for this kind of issue.

**Comment by DailyCovidCases** [comment]
Possible dead branch as of 6/23/2024:
Branch 9: 89 seqs, last sample was on 27 May 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_36d9c_7d58e0.json?f_userOrOld=uploaded%20sample&label=id:node_7064232)
Branch 38: 13 seqs, last sample was on 11 May 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_40d35_8c9010.json?f_userOrOld=uploaded%20sample)
Branch 49: 19 seqs, last sample was on 24 May 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1d47_7dd520.json?f_userOrOld=uploaded%20sample)
Branch 63: 21 seqs, last sample was on 24 April 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_39bef_7e0ea0.json?f_userOrOld=uploaded%20sample)
Branch 74: 23 seqs, last sample was on 13 May 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3ab7c_7e1990.json?f_userOrOld=uploaded%20sample)
Branch 100: 16 seqs, last sample was on 1 May 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_5baa_8ce320.json?f_userOrOld=uploaded%20sample)
Branch 103: maybe it was only a small cluster, please close it

**Comment by FedeGueli** [comment]
done

**Comment by DailyCovidCases** [comment]
+) Possible dead branch as of 6/26/2024: 
Branch 104: 6 seqs, last sample was on 23 May 2024: 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2b9df_98ebf0.json?f_userOrOld=uploaded%20sample) 
Branch 82: 144 seqs, last sample was on 22 May 2024: 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_38d06_990c30.json?f_userOrOld=uploaded%20sample) 
Branch 70: 25 seqs, last sample was on 24 May 2024: 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_428a6_993210.json?f_userOrOld=uploaded%20sample) 
Branch 58: 64 seqs, last sample was on 26 May 2024 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3e3ad_ae1f20.json?f_userOrOld=uploaded%20sample) 
Branch 25: 44 seqs
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_12489_b83fc0.json?f_userOrOld=uploaded%20sample)
+) Branches that worth be designated:
Branch 7: 253 seqs with an interesting combo branch with S:T572I 
[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_205a6_3f5100.json?c=userOrOld&label=id:node_12205827) 
Branch 11: 316 seqs
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3242b_68cdd0.json?f_userOrOld=uploaded%20sample) 
Branch 15: 175 seqs 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1093c_998df0.json?f_userOrOld=uploaded%20sample) 
Branch 22: 47 seqs, last sample was on 27 May 2024 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_345e2_aded40.json?f_userOrOld=uploaded%20sample) 
Branch 71: 54 seqs, last sample was on 3 June 2024: 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2eedd_addc80.json?f_userOrOld=uploaded%20sample) 
ping @corneliusroemer

**Comment by FedeGueli** [comment]
done

**Comment by DailyCovidCases** [comment]
Branch 21,36,41,48,51,57,58,62,73 might be dying off, please update this

**Comment by DailyCovidCases** [comment]
Branch 21: 85 seqs, not monophyletic, last sample was on 22 June 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2f7cb_9082a0.json?f_userOrOld=uploaded%20sample)
Branch 58: 77 seqs, last sample was on 27 June 2024:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_374cd_90bb30.json?f_userOrOld=uploaded%20sample)
Branch 73: 20 seqs, last sample was on 2 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_42b6c_90cee0.json?f_userOrOld=uploaded%20sample&label=id:node_6979794)
