### ISSUE TITLE
New JN.1.16.1 plus S:S31del after Orf1b:Q215K (C14110A) (135 samples, 8 countries including Mexico and South Africa)  

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2661]
Jn.1.16.1 > Orf1b:Q215K (C14110A) > S:S31del (Del21653-55)
Query: C14110A,del21653
Query for S:A771S sub branch: C14110A,del21653,C13426T > 19
Samples: 81 (Canada, England, US
Tree:  
<img width="1161" alt="Screenshot 2024-08-15 alle 10 38 52" src="https://github.com/user-attachments/assets/04fb3b8f-8076-44b2-a4ab-57ccf745024c">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1f3f4_dbda70.json?label=id:node_7258807

IDs:
EPI_ISL_19158673, EPI_ISL_19165120, EPI_ISL_19175973,
EPI_ISL_19177682, EPI_ISL_19177701, EPI_ISL_19186223,
EPI_ISL_19186270, EPI_ISL_19186528, EPI_ISL_19192671,
EPI_ISL_19194452, EPI_ISL_19194467, EPI_ISL_19194469,
EPI_ISL_19194483, EPI_ISL_19194496, EPI_ISL_19195949,
EPI_ISL_19197519, EPI_ISL_19198933, EPI_ISL_19199087,
EPI_ISL_19199090-19199091, EPI_ISL_19199103, EPI_ISL_19205743,
EPI_ISL_19208013, EPI_ISL_19208085, EPI_ISL_19208097,
EPI_ISL_19212266, EPI_ISL_19215295, EPI_ISL_19218336,
EPI_ISL_19221195, EPI_ISL_19221905, EPI_ISL_19223539,
EPI_ISL_19225272, EPI_ISL_19232901, EPI_ISL_19233009,
EPI_ISL_19251255, EPI_ISL_19259346, EPI_ISL_19259378,
EPI_ISL_19262459, EPI_ISL_19262948, EPI_ISL_19262976,
EPI_ISL_19263370, EPI_ISL_19268552, EPI_ISL_19268577,
EPI_ISL_19269204, EPI_ISL_19274423, EPI_ISL_19277612,
EPI_ISL_19277679, EPI_ISL_19277734, EPI_ISL_19277794,
EPI_ISL_19281987, EPI_ISL_19282057, EPI_ISL_19282096,
EPI_ISL_19282762-19282763, EPI_ISL_19285288, EPI_ISL_19286773,
EPI_ISL_19286807, EPI_ISL_19289014, EPI_ISL_19289161,
EPI_ISL_19289396, EPI_ISL_19295157, EPI_ISL_19295505,
EPI_ISL_19302593, EPI_ISL_19304241, EPI_ISL_19304473,
EPI_ISL_19304491, EPI_ISL_19308528, EPI_ISL_19308585,
EPI_ISL_19308653, EPI_ISL_19313846, EPI_ISL_19313929,
EPI_ISL_19316933, EPI_ISL_19316979, EPI_ISL_19317080,
EPI_ISL_19325907, EPI_ISL_19326123, EPI_ISL_19327927,
EPI_ISL_19329022, EPI_ISL_19329147, EPI_ISL_19329460,
EPI_ISL_19332532

**Comment by FedeGueli** [comment]
Wrong repo i leave  this here. in the case not growing i will close it as usual

**Comment by FedeGueli** [comment]
26

**Comment by FedeGueli** [comment]
Designated LF.4.1 via https://github.com/cov-lineages/pango-designation/commit/6c579b80861260450f670f8d640e6d193f7679e0

**Comment by FedeGueli** [comment]
41

**Comment by FedeGueli** [comment]
54

**Comment by FedeGueli** [comment]
60

**Comment by FedeGueli** [comment]
no chance to survive closing it

**Comment by FedeGueli** [comment]
reopened hence it is 81 now and circualting recently also in Mexico. ping @corneliusroemer

**Comment by FedeGueli** [comment]
104

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_35370_9a5800.json?c=pango_lineage&f_userOrOld=uploaded%20sample&label=id:node_7109091)
![Screenshot (212)](https://github.com/user-attachments/assets/4633ab42-d3ee-400c-b03f-0e0a6359e419)
ping @corneliusroemer Is this branch worth a designation?

**Comment by DailyCovidCases** [comment]
This branch has slowed down a lot. I think you can close this

**Comment by FedeGueli** [comment]
> This branch has slowed down a lot. I think you can close this

yeah but two very recent samples

**Comment by DailyCovidCases** [comment]
Now 121 seqs

**Comment by FedeGueli** [comment]
4 recent samples of this from California

**Comment by DailyCovidCases** [comment]
Slowing down now

**Comment by Over-There-Is** [comment]
148
