### ISSUE TITLE
LB.1.3 + S:K147E, Y660R (2-nuc) (26 seq, 12 countries, Aug 9)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2662]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1601
**Description** 
**Sub-lineage of:** LB.1.3 (S:∆S31, Q183H, R346T, F456L)
**Earliest sequence:** 2024-4-29, France - EPI_ISL_19166088
**Most recent sequence:** 2024-5-16, Switzerland -  EPI_ISL_19185299
**Continents circulating:** Europe (9), Asia (1), North America (1)
**Countries circulating:** France (5), Germany (2—both travel to USA), Canada (1), Denmark (1), Qatar (1—travel to USA), Sweden (1), Switzerland (1)
**Number of Sequences:** 12
**GISAID Nucleotide Query:** T23540C, A23541G, G27261T
**CovSpectrum Query:** Nextcladepangolineage:LB.1* & [3-of: T23540C, A23541G, G27261T, C18131T]
**Substitutions on top of LB.1.3:**
**Spike:** K147E, Y660R
**Nucleotide:** A22001G, T23540C, A23541G, G27261T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/Y660R_at_9_seq.json?c=gt-S_660&gmax=25384&gmin=21563&label=id:node_7145835
<img width="1466" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/327ebcc4-a319-438a-bb6c-f106e301f853">

**Evidence**
I call LB.1.3 the "global" branch of LB.1 because it seems to come disproportionately from travel sequences. The xtremely unusual 2-nuc S:Y660R mutation caught my eye here. S:K147E has been advantageous in the past and is another mutation increasing NTD's negative charge, which is a trend that's been going on for a long time now and shows no signs of slowing. 

The most closely related sequence is a travel sequence from Qatar collected in the US. 

<img width="1201" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/28428a50-eff8-41d6-b24e-ae6c2e5c1014">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19166088, EPI_ISL_19185299, EPI_ISL_19189757,
EPI_ISL_19192350, EPI_ISL_19193564, EPI_ISL_19195905,
EPI_ISL_19195971, EPI_ISL_19198865, EPI_ISL_19202120,
EPI_ISL_19205790, EPI_ISL_19205796, EPI_ISL_19210286,
</details>

**Comment by ryhisner** [comment]
Today a sequence from Qatar in a traveler to the USA showed up. Collection date June 11. Given the relatively small amount of diversity, the recent collection dates, and the wide geographical spread, I think there's a chance this lineage is pretty fit. 

Right now it seems like Qatar and Germany are the top two candidates for being its epicenter. The most closely related sequence not in this lineage is a sequence from a traveler to the US from Qatar, collected May 15. Germany itself basically does no surveillance at all, and there are two sequences from German travelers to the US. Also, S:Y660R showed up in one of the German wastewater samples uploaded to GISAID.

**Comment by FedeGueli** [comment]
13 ses in total with T23540C, A23541G, G27261T

**Comment by FedeGueli** [comment]
23 now with Netherlands and UAE (via GBW) as new countries

**Comment by FedeGueli** [comment]
In france 5/11 samples are from Inpatients while the average of sequences labeled as hospitalized there is 1/5 - 1/6 in June: i think we should keep an eye on this.

**Comment by FedeGueli** [comment]
24 samples from 11 countries now, last sample came from Iceland

cc @corneliusroemer

**Comment by FedeGueli** [comment]
26 from 12 countries including two middle eastern countries cc @ryhisner please update the count!
@corneliusroemer worth deisgnating this although not very fast
