### ISSUE TITLE
LE.1 (JN.1.4.7.1) got FLiRT  (43 , 8 countries)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2663]
@aviczhl2 and me tracked abunch of sublineages stemming out from LE.1 with 456X:
>LE.1.1 , LE.1.3.1 , https://github.com/cov-lineages/pango-designation/issues/2663 and Branch 107 of # 1253 (secondary repo) plus another singlet i found looking at a better query for 2663

Now two of them  with S:F456L (T22928C) have been merged by usher in one only lineage (that absorbs both # 2663 and branch 107 of # 1253 in the other repo) hence here the new defining mutations:
LE.1 >> S:f456L (T22928C)
Query:G25445A,G22599C,C774T,T22928C,-C1471T
Samples: 19
Countries: 5 ( with several GBW samples from Spain, France, Italy)
Tree ( by @aviczhl2 ):
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice174_genome_test_5e445_fb01d0.json?label=id:node_5537613
<img width="1156" alt="Screenshot 2024-07-01 alle 10 37 13" src="https://github.com/cov-lineages/pango-designation/assets/87669813/2dd6c545-48c3-4b80-9b4e-aa7d78ae7f93">

IDs:
EPI_ISL_19162370, EPI_ISL_19163658, EPI_ISL_19184862,
EPI_ISL_19184966, EPI_ISL_19191540, EPI_ISL_19191560,
EPI_ISL_19192761, EPI_ISL_19194079, EPI_ISL_19198272,
EPI_ISL_19198420, EPI_ISL_19201070, EPI_ISL_19205799-19205800,
EPI_ISL_19214361, EPI_ISL_19214463-19214464, EPI_ISL_19215296,
EPI_ISL_19215375, EPI_ISL_19221231

 
<Details>
<Summary>
Original proposal:
</summary>
LE.1> Orf1a:T1589I (C5031T), G5470A, S:F456L (T22928C)
Query:C5031T, G5470A,T22928C  
Samples: 5
Countries: France ; Uk, US
IDs:EPI_ISL_19163658, EPI_ISL_19198272, EPI_ISL_19198420,
EPI_ISL_19205799-19205800
Tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice24_genome_test_2f72b_43b540.json?c=userOrOld&label=id:node_12193340
<img width="1152" alt="Screenshot 2024-06-20 alle 17 09 33" src="https://github.com/cov-lineages/pango-designation/assets/87669813/a980ac1a-35bf-43a4-ba12-1442553f9d08">
**EDITED**
**On Today 6-25** another branch of this appeared in GBW samples (from Italy) it lacks the defining proposed here but has some more interesting mutations , already seen with different AA in KP.2.3 and XBB.1:
C176T, Orf1a:V84F (G515T),C12400T, C13761T, S:G252D (G22317A), Orf3a:K67E (A25591G)
Query: C176T, G515T, G22317A
Samples: 2 (GBW - Italy)
Tree:
<img width="1176" alt="Screenshot 2024-06-25 alle 20 58 30" src="https://github.com/cov-lineages/pango-designation/assets/87669813/a9025313-2900-4875-9ba4-478edce43a1f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice19_genome_test_20ceb_b11030.json?c=userOrOld&label=id:node_11496828
</Details>

**Comment by FedeGueli** [comment]
again for the third time in a row wrong repo.

**Comment by FedeGueli** [comment]
main branch now 6 from Spain (new country) plus a separate branch caught by GBW in a traveler from Italy.

**Comment by FedeGueli** [comment]
This is not Branch #107 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253 

There are at least 4 lineages with 456X on LE.1 backbone:
LE.1.1 , LE.1.3.1 , #2663 and Branch 107 of # 1253 (secondary repo) plus another singlet  i found looking at a better query for 2663

**Comment by aviczhl2** [comment]
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/609834f5-4c09-45e0-adce-cbe9387dd5e8)

Those LE.1-FLiRT Branches are gathered now.

**Comment by FedeGueli** [comment]
@aviczhl2 @corneliusroemer this is worth to get a designation , potentially, so i don't transfer it back to secondary repo.
Sorry for opening 5 issues directly here in the few last weeks.

**Comment by FedeGueli** [comment]
34

**Comment by FedeGueli** [comment]
Dying
