### ISSUE TITLE
KP.3.1 + S:ins16_MPVF, ORF1a:T1854I (283 seq, Aug 15)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2664]
**Description**
**Sub-lineage of:** KP.3.1
**Earliest sequence:** 2024-4-28, Spain, Basque Country — EPI_ISL_19095498
**Most recent sequence:** 2024-6-21, Japan, Saitama —EPI_ISL_19218509
**Continents circulating:** Europe (97), North America (3), Asia (1)
**Countries circulating:** Spain (93), USA (3), Portugal (2), Canary Islands (1), France (1—traveler to USA), Japan (1), Scotland (1)
**Number of Sequences:** 101
**GISAID Nucleotide Query:** C897A, C5826T, C18570T
**CovSpectrum Query:** Nextcladepangolineage: KP.3* & [2-of: C5826T, C18570T]
**Substitutions on top of KP.3.1:**
**Spike:** ins16MPFV (in place of MPLF)
**ORF1a:** T1854I (NSP3_T1036I)
**Nucleotide:** C5826T, C18570T, ins21608_TCATGCCGGTGT (C→G at nuc 9, replacing ins21608_TCATGCCGCTGT)

**Phylogenetic Order of Mutations:** C18570T **→** C5826T (ORF1a:T1854I) 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.3.1_ins16_MPVF__T1854I_80seq.json?label=id:node_5612770

<img width="1490" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/ee6b4675-0e2a-4687-a2a2-ec089b6d08c1">

**Evidence**
Fortunately, this mutation in the insertion is accompanied by another nucleotide mutation (C5826T) that, as far as I can tell, is exclusive to this lineage, and which every sequence in this lineage possesses. Only 64 of the 79 sequences in this branch register the insertion, but 100% of these have MPVF. I think it's safe to assume that the remaining 15 sequences, which failed to register the insertion, have the same mutation within the insertion.

Notably, there is a 5-sequence branch here that has S:R190S, an old Gamma mutation that adds a glycan at N188. One of these sequences looks like a coinfection with KP.2.2. Since it has the MPVF insertion, S:F59L, S:R190S, R346T, and K1266R and lacks Q493E, the only way it could be a recombinant is if it had three breakpoints, one between S:16 and S:59, another between S:59 and S:R190S, and another between S:R190S and S:R346T. Seems unlikely. 

<img width="1430" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/6296167f-fc84-4183-ad54-d69e93963d70">

This involves a C->G nucleotide mutation (the rarest of all nuc mutations) in the ninth nucleotide of the S:ins16_MPLF insertion, changing it to MPVF. The insertion's nucleotide sequences changes from TCATGCCGCTGT → TCATGCCGGTGT. 

It's mostly in Spain but has been detected in 10 different regions of Spain (Andalusia, Asturias, Basque Country, Catalunya, Extremadura, Galicia, Guadalajara, Madrid, Murcia, and Navarra), and sequences from France, Scotland and the US show it's not just an Iberian phenomenon.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19095498, EPI_ISL_19140785-19140786, EPI_ISL_19140790-19140793,
EPI_ISL_19145543, EPI_ISL_19145554, EPI_ISL_19147551,
EPI_ISL_19151048, EPI_ISL_19157478, EPI_ISL_19167871,
EPI_ISL_19167883, EPI_ISL_19175464, EPI_ISL_19175492,
EPI_ISL_19178537, EPI_ISL_19179530-19179531, EPI_ISL_19185407,
EPI_ISL_19185409, EPI_ISL_19185422, EPI_ISL_19185514,
EPI_ISL_19187594, EPI_ISL_19187889, EPI_ISL_19187957,
EPI_ISL_19188434, EPI_ISL_19189122, EPI_ISL_19189978,
EPI_ISL_19190778-19190779, EPI_ISL_19193934, EPI_ISL_19193948,
EPI_ISL_19194008, EPI_ISL_19194798, EPI_ISL_19194811,
EPI_ISL_19194836, EPI_ISL_19194853, EPI_ISL_19194860,
EPI_ISL_19194896, EPI_ISL_19194919, EPI_ISL_19194934,
EPI_ISL_19194958, EPI_ISL_19194999, EPI_ISL_19195010,
EPI_ISL_19195026, EPI_ISL_19195033, EPI_ISL_19195088,
EPI_ISL_19195387, EPI_ISL_19195929, EPI_ISL_19195962,
EPI_ISL_19196521, EPI_ISL_19196525, EPI_ISL_19196971,
EPI_ISL_19196977, EPI_ISL_19196980, EPI_ISL_19197892,
EPI_ISL_19197903-19197904, EPI_ISL_19198470, EPI_ISL_19201367-19201368,
EPI_ISL_19201405, EPI_ISL_19201409, EPI_ISL_19201414,
EPI_ISL_19201417, EPI_ISL_19201420, EPI_ISL_19201425,
EPI_ISL_19201429, EPI_ISL_19201439, EPI_ISL_19201533,
EPI_ISL_19201538-19201539, EPI_ISL_19201630, EPI_ISL_19202190,
EPI_ISL_19203533, EPI_ISL_19204048-19204049, EPI_ISL_19209676,
EPI_ISL_19210114
</details>

**Comment by FedeGueli** [comment]
Thanks @ryhisner i have noticed that on covspectrum but assumed it was artifact, thx for looking into it

**Comment by FedeGueli** [comment]
This can compete with KP.3.1.1

**Comment by FedeGueli** [comment]
the orf1a mutation should correspond to PLPro_T291I = NSP3_T1036I

**Comment by FedeGueli** [comment]
82 on gisaid now : C897A, C5826T, C18570T

**Comment by FedeGueli** [comment]
102 is growing quite fast

**Comment by ryhisner** [comment]
Yeah, growing fast in Spain. One sequence has now appeared in Japan. The real test will be to see if it grows anywhere outside of Spain. It hasn't done so yet.

**Comment by ryhisner** [comment]
Still around but not growing fast, so I'm closing.
