### ISSUE TITLE
JN.1.18.3 + S:∆S31, S:R190S (37 seqs, 6 continents, 16 countries, Jun 28)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2665]
### **Description** Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1635
**Sub-lineage of:** JN.1.18.3 (JN.1 + S:R346T, F456V)
**Earliest sequence:** 2024-4-18, England — EPI_ISL_19088216
**2nd-earliest Sequence:** 2024-5-13, Sweden — EPI_ISL_19166238
**Most recent sequence:** 2024-6-23, Senegal — EPI_ISL_19217367, EPI_ISL_19217368
**Continents circulating:** Europe (16), North America (7), Asia (6), Africa (5), Oceania (2), South America (1)
**Countries circulating:** Wales (8), Senegal (5), USA (4), Canada (3), Australia (2), Netherlands (2), Sweden (2), United Arab Emirates (2), Argentina (1), Denmark (1), England (1), France (1), India (1), Japan (1), Malaysia (1), Qatar (1) 
**Number of Sequences:** 37
**GISAID Nucleotide Query:**  C13620T, G22132T, T22928G (query suggested by @FedeGueli)
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & !A27259C & [2-of: C13620T, A29664G, G22132T]
**Substitutions/Deletions on top of JN.1.18.3:**
**Spike:** ∆S31, R190S 
**3' UTR:** A29664G
**Nucleotide:** C13620T, ∆21653-21655, G22132T, C27259A (most), A29664G

**Phylogenetic Order of Mutations:** C13620T  **→** A29664G (3' UTR) **→** G22132T (S:R190S) **→** C27259A (reversion)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1.18.3_S31del_R190S.json?c=gt-S_190&gmax=25384&gmin=21563&label=id:node_6956494
<img width="1492" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/fd8843bd-e11a-48e1-ba0a-3af68ffb1425">

**Evidence**
Several of these sequences are from travelers to the USA, including the two UAE sequences and the Argentina sequence. S:F456V doesn't seem as successful as F456L, so this lineage may be handicapped by this. It does, however, have S:∆S31, R346T, and R190S, which is starting to appear more lately. ∆S31 and R190S both add glycans, which can help shield spike from antibodies and also have important structural effects.

One sequence from Denmark supposedly has S:S31F, but I think this is a misread of a deletion. Denmark has had longstanding problems sequencing deletions. 

This has to be one of the most well-traveled lineages ever. Only 37 sequences, yet it's been detected in all six continents and 16 different countries. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19088216, EPI_ISL_19166238, EPI_ISL_19187993,
EPI_ISL_19187995, EPI_ISL_19192355, EPI_ISL_19193240,
EPI_ISL_19194503, EPI_ISL_19195632, EPI_ISL_19195710,
EPI_ISL_19195886, EPI_ISL_19197347, EPI_ISL_19201214,
EPI_ISL_19201239, EPI_ISL_19205485, EPI_ISL_19205631,
EPI_ISL_19205989, EPI_ISL_19209937, EPI_ISL_19209972,
EPI_ISL_19209974, EPI_ISL_19210018, EPI_ISL_19210773,
EPI_ISL_19214974, EPI_ISL_19215003, EPI_ISL_19217361,
EPI_ISL_19217364, EPI_ISL_19217367-19217369, EPI_ISL_19218563,
EPI_ISL_19219779, EPI_ISL_19220592, EPI_ISL_19220619,
EPI_ISL_19221237, EPI_ISL_19221804, EPI_ISL_19221974,
EPI_ISL_19222212, EPI_ISL_19222235
</details>

**Comment by FedeGueli** [comment]
this is now 29, with 5 samples coming from Senegal .
Senegal uploaded yesterday 15 samples , 13 of them are flagged as samples collected from travelers 
Public Health authorities in Senegal have found several positive paople among Pilgrims coming back from Meccah:
https://aps.sn/pelerins-positifs-au-coronavirus-ibrahima-sy-appelle-les-populations-au-respect-strict-des-mesures-preventives-contre-cette-maladie/
Public health authorities in Senegal have linked high mortality in the few past days in Pilgrims in Mecca not only to the heat wave there but also to respiratory symptoms:
https://aps.sn/hajj-un-taux-de-positivite-au-coronavirus-entre-20-et-60-chez-les-pelerins-de-retour-darabie-saoudite-medecin/
So i think we need to designate to properly monitor it:
Tree of samples collected from travelers in Senegal
<img width="1170" alt="Screenshot 2024-06-27 alle 10 34 10" src="https://github.com/cov-lineages/pango-designation/assets/87669813/889f7894-aefb-4862-b0ca-68bd434ebf59">
[r this one.](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_3a6b5_d23600.json?f_userOrOld=uploaded%20sample&label=id:node_6939611)
( the two samples apparently not belonging to travellers are LF.3.1.1 and LR.1)

cc @corneliusroemer @thomasppeacock @AngieHinrichs

**Comment by FedeGueli** [comment]
29 now! it is rising fast. And that makes being present during the pilgrimage to Mecca .
Today from New York, Wales, Canada , France and Qatar (GBW)

**Comment by FedeGueli** [comment]
ping @corneliusroemer designation needed here

**Comment by aviczhl2** [comment]
Designated MA.1

**Comment by FedeGueli** [comment]
Designated MA.1 via https://github.com/cov-lineages/pango-designation/commit/17a53f071f9c378c379b3e31945c868f887af201

**Comment by FedeGueli** [comment]
@ryhisner closed as " completed"
