### ISSUE TITLE
JN.1+S:F456L branch that should be designated

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2667]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1654
Branch 11: 368 seqs (4 in 2023 and 364 in 2024)
[tracker](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=G2782T%2CT22926C%2CT22928C&nextcladePangoLineage=JN.1.39*&)
Branch 15: 182 seqs (182 in 2024)
[tracker](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=C23683T%2CT22928C%2CC897A&nextcladePangoLineage=JN.1*&)
Branch 7: 262 seqs (5 in 2023 and 257 in 2024)
[tracker](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=T18453C%2CC12525T%2CT22928C&nextcladePangoLineage=JN.1.4*&)
Branch 17: 259 seqs (5 in 2023 and 254 in 2024)
[tracker](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=C774T%2CT18453C%2CT22926C%2CT22928C%2CC9979C%2CT12525T&nextcladePangoLineage=JN.1.4*&)
Branch 26: 1299 seqs (1 in 2023 and 1298 in 2024)
[tracker](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=G26660T%2CG4162A%2CT22928C%2CT3565C&nextcladePangoLineage=JN.1*&)
Branch 62: 149 seqs (2 in 2023 and 147 in 2024)
[tracker](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=G17562T%2CT3565C%2CT22928C%2CT8716T&nextcladePangoLineage=JN.1*&)
Branch 36: 130 seqs (130 in 2024)
[tracker](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=T22928C%2CC26753T%2CC18894T&nextcladePangoLineage=JN.1*&)

**Comment by Memorablea** [comment]
Please close
