### ISSUE TITLE
KP.2.3 (S:∆S31) + ORF1a:R1973S (114 seq, 20 countries; Aug 9)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2668]
### **Description** Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1594
**Sub-lineage of:** KP.2.3 (= JN.1 + S:∆S31, S:H146Q, S:R346T, F456L, V1104L + ORF3a:K67N + ORf1a:T2283I)
**Earliest sequence:** 2024-3-12, France (travel to USA, California), EPI_ISL_18999293
**Most recent sequence:** 2024-6-17, Ireland, EPI_ISL_19210778
**Continents circulating:** Europe (14), Asia (29), North America (10), Oceania (3)
**Countries circulating:** Singapore (25), USA (8), France (6), Ireland (5), Malaysia (4),  Israel (4), Australia (3—different provinces), England (3), Canada (2), India (2—1 travel to USA), Japan (2), Scotland (2), Spain (2), Denmark (1), Italy (1), Qatar (1—travel to USA), Senegal (1), South Africa (1), South Korea (1), Taiwan (1)
**Number of Sequences:** 49
**GISAID Nucleotide Query:** A6183G, A6184C, G25593T
**CovSpectrum Query:** Nextcladepangolineage:KP.2.3* & A6184C
**Substitutions on top of KP.2.3:**
**ORF1a:** R1973S
**Nucleotide:** A6184C, A29647G (3' UTR)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.2.3_S31del_R1973S_16.json?c=gt-nuc_6184&gmax=7184&gmin=5184&label=id:node_2374230

<img width="1502" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/9fc192d4-f5db-46e9-ba94-6821fca7f91c">

**Evidence**
This lineage, despite only consisting of 15 sequences, is present in 11 countries and four continents. The travel sequence originating in India could be particularly meaningful. (I am excluding the pooled Ginkgo Bozoworks sequences in these numbers, which are almost always duplicates and invariably of poor quality.)

This is the second nucleotide mutation in ORF1a:1973 in this lineage. ORF1a:K1973R is common to all BA.2.86.1 lineages (but not other BA.2.86 lineages, which have mostly died off). ORF1a:K1973R is the only amino acid difference between BA.2.86.1 and the other BA.2.86 sublineages, so it may have been relevant to BA.2.86.1's faster growth and subsequent global dominance over those competing sublineages. 

<img width="1053" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/aee57ea1-2864-4da8-a9a4-08dfa2b2a81c">

ORF1a:1973 is NSP3_1155, which is in the nucleic-acid binding (NAB) domain of NSP3. The ultimate function of NAB is not well understood, but it is known to bind nucleic acids, preferring triple-G nucleotide motifs, also a characteristic of Mac3 (SUD-M) and DPUP (SUD-C), two other NSP3 domains. ORF1a:1973 is located 7 AA upstream of consecutive lysine residues known to be key to NAB's nucleic acid-binding activity and could therefore conceivably modulate the primary known property of NAB. Information above is from the paper "Nsp3 of coronaviruses: Structures and functions of a large multi-domain protein" by Jian Lei, Yuri Kusov, and Rolf Hilgenfeld, and is based off the SARS-CoV-1 NAB structure, which seems likely to very closely resemble the ASARS-CoV-2 structure. 

<img width="1125" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/ed4ac69d-075e-4115-89bb-d407a168d9a3">

EDIT: I now realize the SARS-CoV-2 NAB structure is actually available. Here it is, with ORF1a:K1973 highlighted in yellow and K/R residues known to be important in RNA binding in green.

<img width="1271" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/ef0bb62c-fb1a-47e2-82b7-e36ad39bea6a">

 
Notably, K1973R is a reversion to the SARS-1/Bat-CoV residue. JN.1 lineages feature a striking number of such "reversions" to either the Bat-CoV (BC) residue, the SARS-CoV-1 (S1) residue or both, particularly in spike, including the N30 glycan (in the rising S:∆S31 lineages), S50L, K356T, R403K, N440K, N460K, L455S, F456L, P621S, and D796Y. Non-spike "reversions" or near-reversions to the SARS-CoV-1 (S1) and/or Bat-CoV (BC) AA residues include M:T30A, ORF1a:K1973R, ORF1a:A2710T (also in BA.1), and ORF1a:T4175I. 

<img width="1280" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a8cdfa26-2e44-40cd-9c65-c41ebc060651">

ORF1a:R1973S would therefore be a move away from the dominant SARS-1/Bat-Cov residue. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18999293, EPI_ISL_19071309, EPI_ISL_19081749,
EPI_ISL_19095987, EPI_ISL_19130848, EPI_ISL_19153297,
EPI_ISL_19153979, EPI_ISL_19155431, EPI_ISL_19161406,
EPI_ISL_19161657, EPI_ISL_19162457, EPI_ISL_19169585,
EPI_ISL_19175928, EPI_ISL_19176426, EPI_ISL_19176768,
EPI_ISL_19180508, EPI_ISL_19180936, EPI_ISL_19180959,
EPI_ISL_19181120, EPI_ISL_19181198, EPI_ISL_19181301,
EPI_ISL_19181307, EPI_ISL_19181347, EPI_ISL_19181367,
EPI_ISL_19181389, EPI_ISL_19181570, EPI_ISL_19181852,
EPI_ISL_19182055, EPI_ISL_19182291, EPI_ISL_19182293,
EPI_ISL_19182303-19182304, EPI_ISL_19182367, EPI_ISL_19182461,
EPI_ISL_19184455, EPI_ISL_19186571, EPI_ISL_19188063,
EPI_ISL_19189909, EPI_ISL_19191306, EPI_ISL_19191375,
EPI_ISL_19192454, EPI_ISL_19194490, EPI_ISL_19195198,
EPI_ISL_19197835, EPI_ISL_19201151, EPI_ISL_19208442,
EPI_ISL_19210778, EPI_ISL_19210788, EPI_ISL_19215116,
EPI_ISL_19215118, EPI_ISL_19215121-19215122, EPI_ISL_19216219,
EPI_ISL_19216466, EPI_ISL_19216523, EPI_ISL_19216686,
</details>

**Comment by FedeGueli** [comment]
High prevalence in Malaysia in June.

**Comment by xz-keg** [comment]
designated KP.2.3.11

**Comment by FedeGueli** [comment]
> designated KP.2.3.11

via https://github.com/cov-lineages/pango-designation/commit/d39304704862930caed86d10b5785fa1131b2b17
