### ISSUE TITLE
LF.3.1  with S:P>L1143F in USA (42)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2669]
@ryhisner spotted a big upload of this sublineage from Colorado yesterday i was wrongly tracking this as it was already LF.3.1.X
Better proporosing here (originally in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1558)
LF.3.1 ( S:V>H445P) > C13860T > C10894T, C18888T, C20628T, S:P>L1143F ( C24989T)
Query: C10894T, C18888T,T3565C
Samples: 42
Countries: USA mainly Colorado
Tree (by Ryan)
<img width="1159" alt="Screenshot 2024-06-28 alle 11 21 23" src="https://github.com/cov-lineages/pango-designation/assets/87669813/95cb4fbe-5e5d-40cf-ba2f-891afd385a19">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43ad9_e2c9f0.json
IDs: EPI_ISL_19101709, EPI_ISL_19168073, EPI_ISL_19175945,
EPI_ISL_19182879, EPI_ISL_19182909, EPI_ISL_19185752,
EPI_ISL_19188815, EPI_ISL_19188998, EPI_ISL_19191292,
EPI_ISL_19191821, EPI_ISL_19191823, EPI_ISL_19193242,
EPI_ISL_19193258, EPI_ISL_19193296, EPI_ISL_19193311,
EPI_ISL_19193369, EPI_ISL_19202814, EPI_ISL_19209647,
EPI_ISL_19210857, EPI_ISL_19213583, EPI_ISL_19214478,
EPI_ISL_19214480, EPI_ISL_19216263, EPI_ISL_19219859,
EPI_ISL_19219868-19219870, EPI_ISL_19219877-19219881, EPI_ISL_19219883,
EPI_ISL_19219885-19219890, EPI_ISL_19219894-19219895, EPI_ISL_19219900,

**Comment by aviczhl2** [comment]
Designated LF.3.1.1

**Comment by FedeGueli** [comment]
Designated LF.3.1.1 via https://github.com/cov-lineages/pango-designation/commit/b0a4a61f6bbc49802b3e644a3117e48fb0426372
