### ISSUE TITLE
Proposal for a potential delta lineage with ORF3a:D238Y (~6.5K sequences), and its sub-lineage with S:S680T (802 sequences)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#267]
**Description**:
**Sub-lineage of**: B.1.617.2, Clade 21J (~6.5K sequences)
Earliest sequence: 2021/2/1 (India)
**Most recent sequence**: 2021/10/12 (Denmark)
**Countries circulating**:  fairly wide-spread worldwide, with highest prevalence in Mozambique

**Mutations in addition to B.1.617.2**:
ORF1a:K261N,
then ORF3a:D238Y

Genomes:
[Delta D238Y.csv](https://github.com/cov-lineages/pango-designation/files/7370586/Delta.D238Y.csv)

**Evidence**:

Number of samples sequenced as per outbreak.info:
![image](https://user-images.githubusercontent.com/86835836/137850788-956e5a92-4b3e-4ee8-be7e-046c7315775c.png)
https://outbreak.info/situation-reports?pango&muts=ORF3a%3AD238Y&muts=ORF1a%3AK261N

Downsized tree as per NeherLab:
![image](https://user-images.githubusercontent.com/86835836/137851438-792ea944-cb49-4803-b8ea-31c813c88d7c.png)
https://nextstrain.org/groups/neherlab/ncov/africa-mozambique?c=gt-ORF3a_238&f_clade_membership=21J%20%28Delta%29&label=spike_mutations:I95T&p=grid&r=division

Transmission advantage as per CoV-Spectrum:
![image](https://user-images.githubusercontent.com/86835836/137852051-93d746ac-5e8d-4ef8-8384-7fa26d285478.png)
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22mutations%22%3A[%22ORF3a%3AD238Y%22%2C%22ORF1a%3A261N%22]%7D%2C%22matchPercentage%22%3A1%7D

![image](https://user-images.githubusercontent.com/86835836/137852137-49108621-6d6a-4066-8eba-82a394613c1b.png)

Noticeably there's a branch with additional S:S680T within this clade, which is geographically more concentrated, and grows considerably faster.

**Description**:
**Sub-lineage of**: B.1.617.2, Clade 21J (802 sequences)
Earliest sequence: 2021/6/17 (Armenia)
**Most recent sequence**: 2021/10/12 (Denmark)
**Countries circulating**: some European countries

Cumulative prevalence and number of samples sequenced as per Outbreak.info:
![image](https://user-images.githubusercontent.com/86835836/137853380-92c3324b-fff5-4328-9ae5-df1ec9a76d22.png)

**Mutations in addition to B.1.617.2**:
ORF1a:K261N,
then ORF3a:D238Y
then C4455T and ORF1a:A1397V and ORF1b:A1643V and S:S680T

Genomes:
[Delta D238Y+S680T.csv](https://github.com/cov-lineages/pango-designation/files/7370775/Delta.D238Y%2BS680T.csv)

**Evidence**
UsHER subtree:
![image](https://user-images.githubusercontent.com/86835836/137854546-8912e768-d8f9-4762-8f49-fe122e233bac.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d424_e63470.json?c=gt-S_680&l=radial

Downsized tree as per NeherLab:
![image](https://user-images.githubusercontent.com/86835836/137854920-09a0ce1c-716b-4835-9558-e9a0a01be497.png)
https://nextstrain.org/groups/neherlab/ncov/sweden?c=gt-S_680&f_clade_membership=21J%20%28Delta%29&label=spike_mutations:I95T&p=grid&r=division

Transmission advantage as per CoV-Spectrum:
![image](https://user-images.githubusercontent.com/86835836/137854720-77301d9c-7e0b-46bc-bf67-072ada48a627.png)
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22mutations%22%3A[%22ORF3a%3AD238Y%22%2C%22ORF1a%3A261N%22%2C%22S%3AS680T%22]%7D%2C%22matchPercentage%22%3A1%7D

**Comment by FedeGueli** [comment]
The parental lineage has now been designated as AY.122 in #320 .

maybe it would be useful to close this and repropose?

@corneliusroemer

**Comment by chrisruis** [comment]
It doesn't look like these clades have expanded relative to the rest of AY.122 so I'll close this for now
