### ISSUE TITLE
KP.2.3+S:K535T(83 seqs, 8 countries)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2670]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1645
KP.2.3+C28714T+A1087G+A23166C(S:K535T)

GISAID query: C28714T,A1087G,A23166C
No. of seqs: 37(USA 3 France 1 Spain 1 UK 32)

First: EPI_ISL_19062811, UK, 2024-4-14
Latest: EPI_ISL_19203518, Spain, 2024-6-11
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2ca46_ebbf60.json)
![Screenshot (127)](https://github.com/cov-lineages/pango-designation/assets/92421581/d927a865-6a62-41fa-9fe9-5bfe33ddbf16)

**Comment by Memorablea** [comment]
Hello, I noticed that you raised it.But what I want to say is that it's best for the original author to propose this. Thank you for your work.

**Comment by FedeGueli** [comment]
> Hello, I noticed that you raised it.But what I want to say is that it's best for the original author to propose this. Thank you for your work.

i think it is worth at least asking before because the author could have her/his own idea on the lineage . Also in multiple lineages issue asking i would propose branch 7 - 14 -58 (examples) what do you think would be great so we can avoid to propose lineages where the query is not anymore working

**Comment by Memorablea** [comment]
> > Hello, I noticed that you raised it.But what I want to say is that it's best for the original author to propose this. Thank you for your work.
> 
> i think it is worth at least asking before because the author could have her/his own idea on the lineage . Also in multiple lineages issue asking "i would propose branch 7 - 14 -58 (examples) what do you think? " would be great so we can avoid to propose lineages where the query is not anymore working

I think it's not just the author's viewpoint, but it may not be worth mentioning (for example, many branches of JN.1 and S: F456L). If there are other mutations worth mentioning (such as 346/456/572), then you are welcome to bring them up.

**Comment by ryhisner** [comment]
> From [sars-cov-2-variants/lineage-proposals#1645](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1645) KP.2.3+C28714T+A1087G+A23166C(S:K535T)
> 
> GISAID query: C28714T,A1087G,A23166C No. of seqs: 37(USA 3 France 1 Spain 1 UK 32)
> 
> First: EPI_ISL_19062811, UK, 2024-4-14 Latest: EPI_ISL_19203518, Spain, 2024-6-11 [usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2ca46_ebbf60.json) ![Screenshot (127)](https://private-user-images.githubusercontent.com/92421581/344181685-d927a865-6a62-41fa-9fe9-5bfe33ddbf16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDc3MzQsIm5iZiI6MTcyMjAwNzQzNCwicGF0aCI6Ii85MjQyMTU4MS8zNDQxODE2ODUtZDkyN2E4NjUtNmE2Mi00MWZhLTlmZTktNWJmZTMzZGRiZjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE1MjM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MmRiMmNhODAzYTlkZjUyNTRkZmY3MDQzNjMyMDcwNjVlNTc5MDQ3NTQxY2ZjMmJlNTNlNDMzNjljNjhhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hnYb4O2L3ffk6aXabVYAYXySxTos69IrBJWFBR02B5Q)

@DailyCovidCases, what kind of AI are you? Some of us were wondering.

**Comment by FedeGueli** [comment]
> > From [sars-cov-2-variants/lineage-proposals#1645](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1645) KP.2.3+C28714T+A1087G+A23166C(S:K535T)
> > GISAID query: C28714T,A1087G,A23166C No. of seqs: 37(USA 3 France 1 Spain 1 UK 32)
> > First: EPI_ISL_19062811, UK, 2024-4-14 Latest: EPI_ISL_19203518, Spain, 2024-6-11 [usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2ca46_ebbf60.json) ![Screenshot (127)](https://private-user-images.githubusercontent.com/92421581/344181685-d927a865-6a62-41fa-9fe9-5bfe33ddbf16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDc3MzQsIm5iZiI6MTcyMjAwNzQzNCwicGF0aCI6Ii85MjQyMTU4MS8zNDQxODE2ODUtZDkyN2E4NjUtNmE2Mi00MWZhLTlmZTktNWJmZTMzZGRiZjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE1MjM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MmRiMmNhODAzYTlkZjUyNTRkZmY3MDQzNjMyMDcwNjVlNTc5MDQ3NTQxY2ZjMmJlNTNlNDMzNjljNjhhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hnYb4O2L3ffk6aXabVYAYXySxTos69IrBJWFBR02B5Q)
> 
> @DailyCovidCases, what kind of AI are you? Some of us were wondering. I thought @corneliusroemer might be interested in knowing as well.

I agree with @ryhisner , if you are not an AI-tool please make a contact with me by mail or via X.

**Comment by DailyCovidCases** [comment]
I'm not an AI, thanks

**Comment by FedeGueli** [comment]
Designated KP.2.3.5 via https://github.com/cov-lineages/pango-designation/commit/aac77b1bd5675afba44c4a7843b9d2796db96e54
