### ISSUE TITLE
Another unspecified KP.1.1+S:F59S,ORF1ab:T6303I（183 Seqs）with S:T572I (168 seqs) 

### ISSUE THREAD

**Issue by Memorablea** [cov-lineages/pango-designation#2676]
Renew：
### **Another KP.1.1>S:F59S,ORF1ab:T6303I (NO KP.1.1.5)**
GISAID Query:`C2488T,C19172T,T21738C`
Describe: 40seqs, 8 countries
Thanks @aviczhl2 @FedeGueli 

UshER Tree：
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33421_6413b0.json

EPI_ISL ID:
EPI_ISL_19165525, EPI_ISL_19180991, EPI_ISL_19181107,
EPI_ISL_19181750, EPI_ISL_19181923, EPI_ISL_19182161,
EPI_ISL_19182250, EPI_ISL_19182421, EPI_ISL_19183300,
EPI_ISL_19186883-19186884, EPI_ISL_19191711, EPI_ISL_19191810,
EPI_ISL_19192229, EPI_ISL_19192236, EPI_ISL_19192783,
EPI_ISL_19208041, EPI_ISL_19210331, EPI_ISL_19210346,
EPI_ISL_19210627, EPI_ISL_19216203, EPI_ISL_19221033,
EPI_ISL_19221180, EPI_ISL_19222880, EPI_ISL_19225257,
EPI_ISL_19225675, EPI_ISL_19226560, EPI_ISL_19226586,
EPI_ISL_19226601, EPI_ISL_19226762, EPI_ISL_19226789,
EPI_ISL_19226814, EPI_ISL_19227597, EPI_ISL_19227928,
EPI_ISL_19229642, EPI_ISL_19229785, EPI_ISL_19229835,
EPI_ISL_19231014, EPI_ISL_19233259, EPI_ISL_19233272,

### **KP.1.1(S:F456L,S:R346T)>S:F59S,ORF1ab:T6303I>ORF1ab:P4339T>S:T572I**>S:A27P/S:S31P/S:K484E
GISAID Query:`C2488T,C19172T, T21738C,C23277T`
from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1646

EPI_ISL ID:
EPI_ISL_19180991, EPI_ISL_19181107, EPI_ISL_19181750,
EPI_ISL_19181923, EPI_ISL_19182161, EPI_ISL_19182250,
EPI_ISL_19182421, EPI_ISL_19183300, EPI_ISL_19186883-19186884,
EPI_ISL_19192229, EPI_ISL_19192236, EPI_ISL_19192783,
EPI_ISL_19208041, EPI_ISL_19210331, EPI_ISL_19210346,
EPI_ISL_19210627, EPI_ISL_19216203, EPI_ISL_19221033,
EPI_ISL_19221180, EPI_ISL_19225257, EPI_ISL_19225675,
EPI_ISL_19226560, EPI_ISL_19226586, EPI_ISL_19226601,
EPI_ISL_19226762, EPI_ISL_19226789, EPI_ISL_19226814,
EPI_ISL_19227597, EPI_ISL_19227928, EPI_ISL_19229642,
EPI_ISL_19229785, EPI_ISL_19229835, EPI_ISL_19231014,
EPI_ISL_19233259, EPI_ISL_19233272

UshER Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33421_6413b0.json?label=id:node_7021277

**Comment by Memorablea** [comment]
30 now

**Comment by Memorablea** [comment]
USA+3, Canada+1. 34now

**Comment by aviczhl2** [comment]
There is an S:A27P, S31P sub-branch of this now.

**Comment by Memorablea** [comment]
> There is an S:A27P, S31P sub-branch of this now.
> 
> ![image](https://private-user-images.githubusercontent.com/10445944/345684745-414e920a-3b82-4ea2-8334-1249fce467be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzUxMTcsIm5iZiI6MTcyMDA3NDgxNywicGF0aCI6Ii8xMDQ0NTk0NC8zNDU2ODQ3NDUtNDE0ZTkyMGEtM2I4Mi00ZWEyLTgzMzQtMTI0OWZjZTQ2N2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA2MzMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZjFiZmYwNDJkMWRlOThhMmQ5NmQyOWQxZDBiMGExOGY4NDQ2ZmNlN2I4Y2RlMTAyZGQxMzVhNmU5M2E1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ElGey_SFLc__4hrA0h8TS5n7InXCJ8G0Q5EG19PZW7M)

Okay, thank you. I noticed that there seems to be an error in my UshER Tree, and I need to edit it again.

**Comment by Memorablea** [comment]
44,39

**Comment by Memorablea** [comment]
56,51.ping @corneliusroemer

**Comment by FedeGueli** [comment]
@corneliusroemer i suggest to designate this.

**Comment by Mydtlwn** [comment]
I agree!

**Comment by Memorablea** [comment]
62,57

**Comment by Memorablea** [comment]
64,59

**Comment by Memorablea** [comment]
73,67

**Comment by Memorablea** [comment]
78,70

**Comment by Memorablea** [comment]
115，106

**Comment by Memorablea** [comment]
116,107

**Comment by FedeGueli** [comment]
ping @corneliusroemer this should get a designation TRIO+59S

**Comment by Memorablea** [comment]
119,110

**Comment by FedeGueli** [comment]
183 >> 168 with Trio now worth getting designated in my view ping @corneliusroemer

**Comment by aviczhl2** [comment]
Designated MU.1 for T572I branch.

**Comment by Memorablea** [comment]
It doesn't seem to be KP.1.1.5?

Was incorrectly designated as KP.1.1.5.1?

For the sake of specifying MU.1, let's close this issue for a while.Of course, it can still be discussed here.

ping @FedeGueli

**Comment by aviczhl2** [comment]
> It doesn't seem to be KP.1.1.5?
> 
> Was incorrectly designated as KP.1.1.5.1?
> 
> For the sake of specifying MU.1, let's close this issue for a while.Of course, it can still be discussed here.
> 
> ping @FedeGueli

Yeah same problem for LF.6.

**Comment by Memorablea** [comment]
> > It doesn't seem to be KP.1.1.5?
> > Was incorrectly designated as KP.1.1.5.1?
> > For the sake of specifying MU.1, let's close this issue for a while.Of course, it can still be discussed here.
> > ping @FedeGueli
> 
> Yeah same problem for LF.6.

So it seems that the designated problem is really not small!

**Comment by FedeGueli** [comment]
Cornelius answered in the commit. It is just one sequence to keep the branches splitted so good it is MU.1

**Comment by aviczhl2** [comment]
I checked and it seems that it is placed to a separate branch by only one sequence EPI_ISL_19035144. 

So this one can be (and is likely to be) descendant of KP.1.1.5.

**Comment by FedeGueli** [comment]
> > > It doesn't seem to be KP.1.1.5?
> > > Was incorrectly designated as KP.1.1.5.1?
> > > For the sake of specifying MU.1, let's close this issue for a while.Of course, it can still be discussed here.
> > > ping @FedeGueli
> > 
> > 
> > Yeah same problem for LF.6.
> 
> So it seems that the designated problem is really not small!

not at all, no big issues with designations. sometimes the easier thing is also the best even if not 100% clear.

**Comment by Memorablea** [comment]
> Yeah Usher is likely wrong here, only weak evidence it's a separate occurrence of 59S, hence a KP.1.1.5 child. I do this kind of analysis all the time.

OK.Thank you very much.

**Comment by Memorablea** [comment]
> > > > It doesn't seem to be KP.1.1.5?
> > > > Was incorrectly designated as KP.1.1.5.1?
> > > > For the sake of specifying MU.1, let's close this issue for a while.Of course, it can still be discussed here.
> > > > ping @FedeGueli
> > > 
> > > 
> > > Yeah same problem for LF.6.
> > 
> > 
> > So it seems that the designated problem is really not small!
> 
> not at all, no big issues with designations. sometimes the easier thing is also the best even if not 100% clear.

What I want to say is that there are still some very widely distributed branches that are not specified.Although some of the designations went wrong, it didn't really matter.

All in all, thank Pango for your work!

**Comment by FedeGueli** [comment]
> > > > > It doesn't seem to be KP.1.1.5?
> > > > > Was incorrectly designated as KP.1.1.5.1?
> > > > > For the sake of specifying MU.1, let's close this issue for a while.Of course, it can still be discussed here.
> > > > > ping @FedeGueli
> > > > 
> > > > 
> > > > Yeah same problem for LF.6.
> > > 
> > > 
> > > So it seems that the designated problem is really not small!
> > 
> > 
> > not at all, no big issues with designations. sometimes the easier thing is also the best even if not 100% clear.
> 
> What I want to say is that there are still some very widely distributed branches that are not specified.Although some of the designations went wrong, it didn't really matter.
> 
> All in all, thank Pango for your work!

that happens all the time the important thing is not to miss the ones growing . most of the undesignated are either small or flat.
