### ISSUE TITLE
Persistent S:R346T and N:N29T/Orf9b:A29L circulating in South Africa with exportations to France and Israel (11)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2677]
From Branch 146 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089
JN.1 > C823T > S:R346T (G22599C) > A12772G, N:N29T / Orf9b:A29L(A28359C)
Query:A12772G, A28359C
Samples: 11 (South Africa, France , Israel)
IDs:EPI_ISL_19011037, EPI_ISL_19125678-19125679, EPI_ISL_19131001,
EPI_ISL_19139072, EPI_ISL_19139105, EPI_ISL_19161570,
EPI_ISL_19169589, EPI_ISL_19195281, EPI_ISL_19215134,
EPI_ISL_19225608
Tree:
<img width="1165" alt="Screenshot 2024-07-01 alle 18 08 40" src="https://github.com/cov-lineages/pango-designation/assets/87669813/b9393b6e-74d7-4131-aa0c-a2f71489968e">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5f88d_2d4560.json?label=id:node_6991552

**Comment by DailyCovidCases** [comment]
This branch is likely dying off, please close it
