### ISSUE TITLE
JN.1+2-nuc Orf1b:I2273S+FLiRT (42 seqs, 7 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2679]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1503

JN.1+T20285C,A20284T(Orf1b:I2273S)+G22599C,T22928C(S:R346T,F456L)

GISAID query:T20285C, A20284T, C18894T, G22599C,T22928C,-17334,-16741
No. of seqs: 33(Australia 1 Canada 10 UK 2 Singapore 1 USA 19 (3 from UK 1 from Italy))

First: EPI_ISL_18983833, USA from UK, 2024-3-4
Latest: EPI_ISL_19213679, UK, 2024-6-8

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_i2273s_r346t_f456l.json?label=id:node_5525006)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/18b45bfb-f325-43b2-a9ac-3306b788dd81)

**Comment by DailyCovidCases** [comment]
85 seqs now
Is this branch worth to be designated?

**Comment by aviczhl2** [comment]
42, France
