### ISSUE TITLE
Proposal for a delta lineage with ORF7a:P45L (~56k sequences, ~33% prevalence in Russia), and 2 related sub-lineages

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#268]
Description
**Sub-lineage of**: B.1.617.2, Clade 21J (~56K sequences, including a ~10K sub-clade where ORF7a:45L mutates back to 45P)
**Earliest sequence**: 2021/4/15 (the UK)
**Most recent sequence**: 2021/10/14 (Italy)
**Countries circulating**: wide-spread, with higher prevalence in Russia and Eastern Europe

Cumulative prevalence and number of samples sequenced as per Outbreak.info:
![image](https://user-images.githubusercontent.com/86835836/137879904-a13c5dad-d942-435b-bd66-03d88167340b.png)
https://outbreak.info/situation-reports?pango&muts=S%3AP681R&muts=ORF7a%3AP45L&muts=ORF1a%3AK261N

**Mutations in addition to B.1.617.2, Clade 21J**:
ORF1a:K261N
then ORF7a:P45L

**Genomes**:
[Delta P45L.csv](https://github.com/cov-lineages/pango-designation/files/7371890/Delta.P45L.csv)

**Evidence**
Downsiezed tree as per NeherLab (shown in yellow color):
![image](https://user-images.githubusercontent.com/86835836/137880462-a3fa574f-bf54-4ee6-bc60-cff70bc9656f.png)
https://nextstrain.org/groups/neherlab/ncov/europe?c=gt-ORF7a_45&f_clade_membership=21J%20%28Delta%29&label=spike_mutations:I95T&p=grid&r=division

Transmission advantage as per CoV-Spectrum:
![image](https://user-images.githubusercontent.com/86835836/137883182-8f373163-faa4-4af5-8323-ad4a1d3b31b7.png)
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22mutations%22%3A[%22ORF1a%3AK261N%22%2C%22ORF7a%3AP45%22]%7D%2C%22matchPercentage%22%3A1%7D

![image](https://user-images.githubusercontent.com/86835836/137882379-b4365ec5-4c17-4f55-ab7c-d751473a4087.png)

Interestingly, big chunk of its sub-branch has the ORF7a:45L mutated back to 45P.

**Sub-lineage of**: B.1.617.2, Clade 21J (~9.2K sequences)
**Earliest sequence**: 2021/4/15 (the UK)
**Most recent sequence**: 2021/10/12 (Denmark)
**Countries circulating**: wide-spread, with higher prevalence in France, Italy and Monaco.

Cumulative prevalence and number of samples sequenced as per Outbreak.info:
![image](https://user-images.githubusercontent.com/86835836/137884067-37abc39c-25bd-4fa9-aa20-8ced10101b45.png)
https://outbreak.info/situation-reports?pango&muts=S%3AP681R&muts=ORF7a%3AR118G&muts=ORF1a%3AK261N

**Mutations in addition to B.1.617.2, Clade 21J**:
ORF1a:K261N
then ORF7a:P45L
then ORF7a:L45P, ORF7a:R118G and ORF1a:A498V

**genomes**: 
[Delta R118G.csv](https://github.com/cov-lineages/pango-designation/files/7372069/Delta.R118G.csv)

**Evidence**
Downsized tree as per NeherLab (shown in light green):
![image](https://user-images.githubusercontent.com/86835836/137885046-cd476c27-95ab-4d9f-9a26-4bf5080885c8.png)
https://nextstrain.org/groups/neherlab/ncov/europe?c=gt-ORF7a_45,118&f_clade_membership=21J%20%28Delta%29&label=spike_mutations:I95T&p=grid&r=division

Transmission advantage as per CoV-Spectrum:
![image](https://user-images.githubusercontent.com/86835836/137885181-3083aaec-e530-4a02-be13-d9a53c8dd9b2.png)
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22mutations%22%3A[%22ORF1a%3AK261N%22%2C%22ORF7a%3AR118G%22%2C%22ORF1a%3AA498V%22]%7D%2C%22matchPercentage%22%3A1%7D

![image](https://user-images.githubusercontent.com/86835836/137882379-b4365ec5-4c17-4f55-ab7c-d751473a4087.png)

There is another much smaller sub-branch:

**Sub-lineage of**: B.1.617.2, Clade 21J (~913 sequences)
**Earliest sequence**: 2021/4/23 (Russia)
**Most recent sequence**: 2021/10/10 (Denmark)
**Countries circulating**: Mainly Estonia (~16% prevalence), and a few other European countries

Cumulative prevalence and number of samples sequenced as per Outbreak.info:
![image](https://user-images.githubusercontent.com/86835836/137893901-bf0c509e-258c-4087-9b2b-1d254ba4ee4c.png)
https://outbreak.info/situation-reports?pango&muts=S%3AP681R&muts=S%3AS680P&muts=ORF1a%3AK261N

**Mutations in addition to B.1.617.2, Clade 21J**:
ORF1a:K261N
then ORF7a:P45L
then S:S680P
more than half of the sequences from Estonia have further substitutions of ORF1a:K851E, ORF1a:A903V, ORF1b:D815Y, ORF3a:S40P and nuc C6781T and  (524 sequences, shown in blue color)

**Genomes**:
[Delta P45L+S680P.csv](https://github.com/cov-lineages/pango-designation/files/7372559/Delta.P45L%2BS680P.csv)

**Evidence**
Downsized tree as per NeherLab (shown in blue color):
![image](https://user-images.githubusercontent.com/86835836/137896281-4fd867b3-feff-44fc-bcc5-573b78b81eb9.png)
https://nextstrain.org/groups/neherlab/ncov/estonia?c=gt-S_680&f_clade_membership=21J%20%28Delta%29&p=grid&r=division

Transmission advantage as per CoV-Spectrum:
![image](https://user-images.githubusercontent.com/86835836/137895512-fa7a0791-ac0a-4658-92f6-22225c012803.png)
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22mutations%22%3A[%22ORF1a%3AK261N%22%2C%22S%3AS680P%22]%7D%2C%22matchPercentage%22%3A1%7D

**Comment by MCB6** [comment]
>  normal tree building issues, nothing else

would it help with tree-building uncertainties if this substrain is designated? It gets a little bewildering now. In the new uploads from Ukraine, 7 genomes with NSP2:K81N + ORF7a:P45L are assigned to 4 different Pango lineages...
![Ukraine-NSP2_K81N](https://user-images.githubusercontent.com/93294184/140242359-e207e766-0037-4d8e-873a-90d13e13a4bd.png)

**Comment by FedeGueli** [comment]
I suggest the designation of the parental lineages with  sublineages, Estonia is actually the worst hit country in Europe and sublineage 3 proposed here is about 1/4 of the sequences there.

https://cov-spectrum.ethz.ch/explore/Estonia/AllSamples/Past3M/variants?aaMutations=S%3AS680P%2COrf7a%3AP45L&pangoLineage=B.1.617.2*

@chrisruis @corneliusroemer

**Comment by MCB6** [comment]
Exactly the same lineage ambiguity is observed in today's upload from Russia. 40/42 samples collected in mid-October have  NSP2:K81N + ORF7a:P45L, but they are assigned to 4 different lineages. Mostly AY.43 and B.1.617.2, but neither accounts for even half of the total...
![Orenburg_NSP2-K87N](https://user-images.githubusercontent.com/93294184/140586119-e0bb116f-0525-4168-9c47-fec05d480d11.png)

**Comment by FedeGueli** [comment]
Designated as AY.122 in #320

**Comment by FedeGueli** [comment]
Hi @c19850727 here the second proposed sublineage of the newly designated AY.122 is still very intetestimg and should be proposed in a dedicated issue.

It is still growing in Denmark where i arrives at 3,3% of the last twenty days sequences 

![VariantTimeDistributionChart (6)](https://user-images.githubusercontent.com/87669813/142950407-24f65fd4-b5bf-4c10-b489-404099a606c2.png)


Core mutation: orf1a:3483F, Orf7a:R118G, Orf1a:A498V
First sequences from Denmark: week 36
Total Sequences:1304 (1274 in Denmark)

[Covspectrum](https://cov-spectrum.ethz.ch/explore/Denmark/AllSamples/from=2021-10-23&to=2021-11-23/variants?aaMutations=orf1a%3A3483F%2COrf7a%3AR118G%2COrf1a%3AA498V) 

Nexst[Neher Lab Tree](https://nextstrain.org/groups/neherlab/ncov/denmark?branchLabel=aa&c=gt-ORF7a_118&tl=pango_usher) 


@corneliusroemer
