### ISSUE TITLE
KR.1 (FLiRT) got S:F59S  (110, >10 countries including Philippines and Japan) with a branch with S:A435S,S:S680P (12, South Korea,US)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2681]
transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1670

KR.1 >  **S:F59S** (T21738C) >> ORF1a:C3419Y (G10521A),G29543T
then>>C16675T > A13318G, T22054C (S:N164N), S:A435S (G22865T)
Query: C28498T ,T22928C,C1762A,T21738C
Samples: 89
Countries: 10 mainly Philippines (where it likely emerged), Japan, California, South Korea, Canada , Australia
With a branch, **spotted by @aviczhl2** ,  carrying two additional spike mutations S:A435S and S:S680P
Query for the 435S branch: C16675T,A13318G, T22054C
Samples: 8 (S.Korea,US)

Tree:
<img width="1180" alt="Screenshot 2024-09-01 alle 14 53 59" src="https://github.com/user-attachments/assets/256fd971-9b8a-498a-adf5-b61c143c57c6">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_256e7_4632b0.json?f_userOrOld=uploaded%20sample&label=id:node_7171824
Tree for the 435S branch:
<img width="1173" alt="Screenshot 2024-09-01 alle 14 54 39" src="https://github.com/user-attachments/assets/33ce2a8a-bab5-490b-b3d7-2a080b6f09c8">

IDs
EPI_ISL_19162486, EPI_ISL_19162527, EPI_ISL_19189341,
EPI_ISL_19190117, EPI_ISL_19191455, EPI_ISL_19192899,
EPI_ISL_19195692, EPI_ISL_19199242, EPI_ISL_19208173,
EPI_ISL_19210931, EPI_ISL_19220364, EPI_ISL_19220372,
EPI_ISL_19222088, EPI_ISL_19226740, EPI_ISL_19227262,
EPI_ISL_19230901, EPI_ISL_19230975-19230976, EPI_ISL_19230992,
EPI_ISL_19232851, EPI_ISL_19232854, EPI_ISL_19233915,
EPI_ISL_19238872, EPI_ISL_19241332, EPI_ISL_19245124,
EPI_ISL_19245126, EPI_ISL_19245195, EPI_ISL_19251028,
EPI_ISL_19251504, EPI_ISL_19257384, EPI_ISL_19257904-19257905,
EPI_ISL_19258078, EPI_ISL_19258109, EPI_ISL_19258125,
EPI_ISL_19261935, EPI_ISL_19263205, EPI_ISL_19264232,
EPI_ISL_19266193, EPI_ISL_19273928, EPI_ISL_19274080,
EPI_ISL_19282963, EPI_ISL_19282975, EPI_ISL_19299317,
EPI_ISL_19302444, EPI_ISL_19302508, EPI_ISL_19304264,
EPI_ISL_19304438, EPI_ISL_19304445, EPI_ISL_19304547,
EPI_ISL_19304552, EPI_ISL_19304723, EPI_ISL_19304726,
EPI_ISL_19306374, EPI_ISL_19306531, EPI_ISL_19309917,
EPI_ISL_19311314, EPI_ISL_19314099, EPI_ISL_19314124,
EPI_ISL_19314130, EPI_ISL_19314142, EPI_ISL_19314162,
EPI_ISL_19314167, EPI_ISL_19314173, EPI_ISL_19314197,
EPI_ISL_19314226, EPI_ISL_19314228, EPI_ISL_19314237,
EPI_ISL_19314264, EPI_ISL_19317263, EPI_ISL_19326019,
EPI_ISL_19332576, EPI_ISL_19340508, EPI_ISL_19340562,
EPI_ISL_19340803, EPI_ISL_19344202, EPI_ISL_19345455,
EPI_ISL_19346312, EPI_ISL_19347664, EPI_ISL_19352517,
EPI_ISL_19352641, EPI_ISL_19354461, EPI_ISL_19358645,
EPI_ISL_19360437, EPI_ISL_19367497, EPI_ISL_19368928,
EPI_ISL_19368946, EPI_ISL_19369006, EPI_ISL_19369009,

**Comment by FedeGueli** [comment]
I ve reopened it here after @aviczhl2 spotted a sublineage of interest with 435S

Ping @corneliusroemer

**Comment by FedeGueli** [comment]
97/11 i think this could be designated likely circulated much more than what we see from seqs count.

**Comment by DailyCovidCases** [comment]
Now 100 seqs. Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_20fcb_9a99c0.json?c=pango_lineage&f_userOrOld=uploaded%20sample)
![Screenshot (213)](https://github.com/user-attachments/assets/e3dc65a2-5eb1-42cb-8efd-beccb37f58e9)
ping @corneliusroemer Is this branch worth a designation?

**Comment by DailyCovidCases** [comment]
This branch has slowed down a lot. You can close this.

**Comment by FedeGueli** [comment]
Lets wait a bit more, S Korea is slow to upload ,

**Comment by FedeGueli** [comment]
104 none recent closing it

**Comment by FedeGueli** [comment]
One more from S Korea in September

**Comment by DailyCovidCases** [comment]
Slowing down closing it

**Comment by FedeGueli** [comment]
designated KR.1.4 via https://github.com/cov-lineages/pango-designation/commit/73becf76eb345c5a843bd52f97a137acd0742c56

**Comment by Over-There-Is** [comment]
A435S 18 now, old
