### ISSUE TITLE
KP.2.3 (∆S31) + S:N185T, ORF8:∆53-92 (oof) [69 seq, 22 countries; July 17]

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2684]
**Description** - Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1618
**Sub-lineage of:** KP.2.3 (S:∆S31, H146Q, R346T, F456L)
**Earliest sequence:** 2024-4-22, Singapore — EPI_ISL_19096038
**Most recent sequence:** 2024-6-22, Canada, Ontario — EPI_ISL_19230977; Hong Kong — EPI_ISL_19232547
**Continents circulating:** North America (27), Europe (24), Asia (17), Africa (1)
**Countries circulating:** USA (15), Canada (12), Singapore (8), Ireland (7), France (4), England (3), Hong Kong (3), Italy (2), Netherlands (2), Belgium (1), China (1), Denmark (1), Germany (1), Iceland (1), India (1), Japan (1), Kenya (1), Malaysia (1), Sweden (1), Switzerland (1), Taiwan (1), Turkey (1)
**Number of Sequences:** 43
**GISAID Nucleotide Query:** A22116C, G25593T, C28714T
**CovSpectrum Query:** Nextcladepangolineage:KP.2* & [3-of: A22116C, G25593T, C28714T]
**Substitutions/Deletions on top of KP.2.3:**
**Spike:** N185T
**ORF8:** ∆53-92
**Nucleotide:** A22116C, ∆28050-28168, C28714T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.2.3_N185T_ORF8_deletion.json?c=gt-S_185&gmax=25384&gmin=21563&label=id:node_5611638
<img width="1492" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/6d40dd35-148c-46e5-a642-4757c63bb910">

**Evidence**
There is one sequence from India from a traveler to the US, another from Kenya from a traveler to the US, and another from Turkey from a traveler to the US, all regions where there is virtually no surveillance, so it seems possible that this lineage is more widespread than its small numbers would suggest.

<img width="1468" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/65102802-7368-4025-9789-717a3d5e4221">

ORF8 has remained surprisingly intact in BA.2.86 thus far. There have been remarkably few stop codons and very little in the way of TRS destruction. But maybe ORF8 is just biding its time with JN.1, allowing a few immune-evasive spike mutations to pile up before obliterating itself (along with its tendency to reduce spike-surface expression). 

This lineage has a large ORF8 deletion, ORF8:∆53-92 (∆28050-28168) that registers in most sequences as dropout, along with various artifactual mutations along the edges of the deletion, which causes the Usher tree to be more divided than it really should be. Two recent sequences from Ireland, however, have gotten the deletion right. 

A stop codon almost immediately follows the deletion (TAA from 28172-28174, or ORF8:93-94)

**Genomes - 
Note: Three sequences appear on the Usher tree but not on GISAID:**
Switzerland/ZH-UZH-IMV-485cc4b7/2024|OZ075092.1|2024-05-17
USA/NC-CDC-LC1105927/2024|PP938805.1|2024-06-05
USA/FL-CDC-LC1106366/2024|PP957313.1|2024-06-05
<details>
<summary>Genomes</summary>
EPI_ISL_19093699, EPI_ISL_19096038, EPI_ISL_19146033,
EPI_ISL_19146038, EPI_ISL_19162517, EPI_ISL_19178153,
EPI_ISL_19181364, EPI_ISL_19182095, EPI_ISL_19185987,
EPI_ISL_19189567, EPI_ISL_19191245, EPI_ISL_19195345,
EPI_ISL_19195347, EPI_ISL_19196009, EPI_ISL_19196017,
EPI_ISL_19201552, EPI_ISL_19209901, EPI_ISL_19209909,
EPI_ISL_19210058, EPI_ISL_19214440-19214441, EPI_ISL_19214447,
EPI_ISL_19218670, EPI_ISL_19220366, EPI_ISL_19221005,
EPI_ISL_19221015, EPI_ISL_19221248, EPI_ISL_19221904,
EPI_ISL_19221932, EPI_ISL_19225039, EPI_ISL_19227199,
EPI_ISL_19227740, EPI_ISL_19227835, EPI_ISL_19227837,
EPI_ISL_19228163, EPI_ISL_19229792, EPI_ISL_19229796,
EPI_ISL_19230918, EPI_ISL_19230977, EPI_ISL_19231103,
EPI_ISL_19231133, EPI_ISL_19232547
</details>

**Comment by aviczhl2** [comment]
Isn't this one KP.2.3.3?

**Comment by FedeGueli** [comment]
> Isn't this one KP.2.3.3?

Yeah! i can't find the commit back! but i hve seen 185T  in the nextstrain tree, i never made the connection between the two sorry! thank you for spotting!
