### ISSUE TITLE
Proposal for a potential sublineage of AY.34 with S:T859I (~500 sequences, ~42% prevalence in Martinique)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#269]
Description
**Sub-lineage of**: AY.34 (489 sequences)
Earliest sequence: 2021/4/19 (the UK)
Most recent sequence: 2021/9/28 (Martinique)
Countries circulating: mainly Martinique (217 sequences) and France (102 sequences)

Cumulative prevalence and number of samples sequenced as per Outbreak.info:
![image](https://user-images.githubusercontent.com/86835836/137956121-3ec637db-5d8e-49bf-b3cc-eaace81cd318.png)

**Mutations in addition to Ay.34**:
nuc G19563A,
then ORF1b:T2548I,
then ORF1a:V3718F and S:T859I

Genomes:
[AY.34+T859I.csv](https://github.com/cov-lineages/pango-designation/files/7375343/AY.34%2BT859I.csv)

**Evidence**
Downsized tree as per NeherLab:
![image](https://user-images.githubusercontent.com/86835836/137956638-6050655d-64f4-4940-befe-30bfe90a9d2d.png)
https://nextstrain.org/groups/neherlab/ncov/france?c=gt-S_859&p=grid&r=division

UShER sub-tree:
![image](https://user-images.githubusercontent.com/86835836/137957085-37bf837f-c857-498f-9dfb-f4b2cef7d59b.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3bd0a_ef8c10.json?c=gt-S_859&l=radial

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as AY.34.2 in [v1.2.103](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.103) to start on a branch with G11417T (Orf1ab:V3718F) which coincides with the clade containing the Martinique sequences

**Comment by FedeGueli** [comment]
@chrisruis @corneliusroemer 

Put this here, cause i am not sure if i'll go proposing it,
but it is surely worth a mention
In november a sublineage of AY.4 with the same mutation S:T859I was on the raise in Denmark reaching around 4% in mid november.
[Covspectrum past 3m](https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?aaMutations=S%3A859I&pangoLineage=AY.4*) 
Interestingly the danish clade carried S:I101T too

To note that B.1.640 carries a different mutation in the same residue S:T859N
