### ISSUE TITLE
JN.1+ORF1ab:S2242F+S:F456L+S:N960S(25 sequences, 4 countries)

### ISSUE THREAD

**Issue by Outpfmance** [cov-lineages/pango-designation#2692]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1304#issuecomment-2227402013

Sub-lineage of:JN.1
Earliest sequence: EPI_ISL_19205731,France,2024-5-28
Latest sequence: EPI_ISL_19260271,Ireland,2024-6-29
countries:USA(2),France(5),Ireland(9),Spain(4)
GISAID query: A24441G,C6990T,T22928C
Number of Sequences:20
UShER tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_756_3fd150.json?f_userOrOld=uploaded%20sample
![IMG_0094](https://github.com/user-attachments/assets/e3cac254-43b2-411d-a29c-a2982e5e6113)

**Comment by FedeGueli** [comment]
22

**Comment by FedeGueli** [comment]
it seems going to die off

**Comment by Outpfmance** [comment]
still look for a week

**Comment by DailyCovidCases** [comment]
It seems that this branch is close to stopped growing, so I think you should close this

**Comment by Outpfmance** [comment]
Yes, I will close it.
