### ISSUE TITLE
LF.3.1 sub-branch with S:D745A ( 100 seqs, 13 countries, 4 of them in South America)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2697]
This is the sibling lineage of LF.3.1.1 previously described as Branch 2 in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1558.
It is still a small lineage but having been sampled in or from three South American countries this could be quite widespread 
LF.3.1 [Jn.1.16.1>  C5581A, C7594T, Orf1a:A4285V (C13119T) > S:V>H445P ( T>A22896C)] > S:D745A (A23796C)
Query: T22896C,A23796C,T3565C
Samples: 20
Countries : 6 (including : Peru', Colombia, Ecuador)
IDs: EPI_ISL_19101707, EPI_ISL_19135408, EPI_ISL_19136576,
EPI_ISL_19148755, EPI_ISL_19195661, EPI_ISL_19195708,
EPI_ISL_19195728, EPI_ISL_19210403, EPI_ISL_19221376,
EPI_ISL_19253469, EPI_ISL_19259535, EPI_ISL_19260233,
EPI_ISL_19262880, EPI_ISL_19262909, EPI_ISL_19269271,
EPI_ISL_19271577, EPI_ISL_19273633, EPI_ISL_19273850,
EPI_ISL_19279807, EPI_ISL_19280173

Tree:
<img width="1168" alt="Screenshot 2024-07-23 alle 23 52 09" src="https://github.com/user-attachments/assets/f6a2e9e6-7e42-4182-ae68-fb41fd8b56a6">
<img width="1159" alt="Screenshot 2024-07-23 alle 23 52 36" src="https://github.com/user-attachments/assets/606fd9bd-7f53-497a-a2f8-d1cb5774837e">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice18_genome_test_abdd_fdb2d0.json?label=id:node_7206124

**Comment by ryhisner** [comment]
There were four sequences from New Zealand uploaded yesterday with S:D745E, and of course there's MK.1 (KP.3.1.6.1) that has S:D745G. This is looking like it could be a new site for convergent mutations.

**Comment by FedeGueli** [comment]
still around now at 26

**Comment by aviczhl2** [comment]
58 seqs now.

**Comment by FedeGueli** [comment]
Thx!

**Comment by aviczhl2** [comment]
67 After adding another Peru/Chile batch

**Comment by FedeGueli** [comment]
69 now with samples coming from Chile, new country the 4th in South America. To be noticed thast one GBW sample is from  India.

**Comment by FedeGueli** [comment]
78 ping @corneliusroemer this although not super fast deserves a designation due to its spread in Southern America

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_d615_2e5ea0.json?f_userOrOld=uploaded%20sample)
Tracked in [issue2697](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=T22896C%2CA23796C%2CT3565C&nextcladePangoLineage=LF.3.1*&)
![Screenshot (236)](https://github.com/user-attachments/assets/a776af72-e27c-4437-91fc-f9ed215bdb2e)

**Comment by FedeGueli** [comment]
91, greece

**Comment by DailyCovidCases** [comment]
@FedeGueli This branch has slowed down a lot. You can close this issue in a few weeks

**Comment by Over-There-Is** [comment]
110 now

**Comment by FedeGueli** [comment]
Designated LF.3.1.2 via https://github.com/cov-lineages/pango-designation/commit/d247018d827cb510992c2ecb1d739b086441e36e#commitcomment-148151048
