### ISSUE TITLE
KP.2+S:H146Y misread on GISAID (178 seqs, >10 places)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2698]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1666

GISAID reads this mutation as T21994C+del21998_22000, resulting in S:H146del instead of the S:Y144del for normal JN.1*s.
However, starting from S:Y144del, usher's S:H146Y shall be the correct mutation path.

S:146 mutation is present in XBB* and KP.2.3. 

GISAID query: G17334T, G22599C, C15579T, del21998
No. of seqs: 105(Australia 1 Canada 5 Ireland 2 Netherlands 1 New Zealand 1 Norway 2 UK 1 Singapore 1 Sweden 1 Switzerland 1 USA 89(1 from Netherlands 2 from El Salvador ))

First: EPI_ISL_19024975, USA, 2024-3-12
Latest: EPI_ISL_192709078, Sweden, 2024-7-14

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/kp_2_h146y.json?label=id:node_5491045)
![image](https://github.com/user-attachments/assets/27b1a8b7-a279-4562-842c-918d0f474f66)

**Comment by aviczhl2** [comment]
131, Germany

**Comment by FedeGueli** [comment]
Only 10% of total samples are from July it is lkely slowing down

**Comment by aviczhl2** [comment]
159, Mexico

**Comment by FedeGueli** [comment]
to be noticed that Covspectrum query is G17334T, G22599C, C15579T + S:H146-,

being Y144 and the mutation here 146Y it seems the pipelines switch the deletion to 146 and  conserve WT Y at 144. If this will happen in a dominant strain it could be an issue for vaccines.

**Comment by aviczhl2** [comment]
> to be noticed that Covspectrum query is G17334T, G22599C, C15579T + S:H146-,
> 
> being Y144 and Y145 and the mutation here 146Y it seems the pipelines switch the deletion to 146 and conserve WT Y at 144.

Same as GISAID

**Comment by FedeGueli** [comment]
> > to be noticed that Covspectrum query is G17334T, G22599C, C15579T + S:H146-,
> > being Y144 and Y145 and the mutation here 146Y it seems the pipelines switch the deletion to 146 and conserve WT Y at 144.
> 
> Same as GISAID

also nextclade!

**Comment by DailyCovidCases** [comment]
ping @corneliusroemer worth a designation this one

**Comment by DailyCovidCases** [comment]
This branch is dying off, please close this. @xz-keg
