### ISSUE TITLE
KP.3.1.6 + S:R346T, H445R; ORF1a:L293F, S1272G, T2069N, D2592Y (>20 seq; Aug 6)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2699]
### **Description** (Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1655)
**Sub-lineage of:** KP.3.1
**Earliest sequence:** 2024-6-8, USA, Colorado – EPI_ISL_19217715, EPI_ISL_19217894
**Most recent sequence:** 2024-7-9, USA, Iowa - EPI_ISL_19284825 and USA, New York - EPI_ISL_19277632
**Continents circulating:** North America (10), Asia (2)
**Countries circulating:** USA (10), Japan (1), United Arab Emirates (1)
**Number of Sequences:** 12
**GISAID Nucleotide Query:** C6471A, G22599C, G22895C, T22896G
**CovSpectrum Query:** Nextcladepangolineage:KP.3.1* & [2-of: G22599C, A22896G]
**Substitutions on top of KP.3.1:**
**Spike:** R346T, H445R
**ORF1a:** L293F, S1272G, T2069N, D2592Y
**Nucleotide:** C1142T, A4079G, C6471A, A7432G, G8039T, T19305C, G22599C, A22896G 

**Phylogenetic Order of Mutations:** T19305C   **→**   G8039T (ORF1a:D2592Y)   **→**   A4079G (ORF1a:S1272G)   **→**   C1142T (ORF1a:L293F)   **→** C6471A, A7432G, G22599C, A22896G (S:R346T, S:H445R, ORF1a:T2069N)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.3.1_v445r_r346t.json?c=gt-S_445&gmax=25384&gmin=21563&label=id:node_7003604
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/5c180507-a6b2-439d-9899-68ac28c51703">

**Evidence**
These are just the 3rd and 4th KP.3 sequences with S:R346T, and they are the first with evidence of transmission. Clearly, there is something about R346T that does not mesh well with S:Q493E. I don't think it's a coincidence that S:H445R showed up simultaneously with R346T here. Historically, R346T has been nearly incompatible with N450D, for reasons that remain unclear. H445R is a significant shift toward more positive charge, so perhaps it somehow is able to neutralize whatever deleterious interaction R346T and N450D have. 

Also worth noting is ORF1a:S1272G, a very rare mutation that when it appears, is often associated with chronic infections. Here it appears to have been acquired in circulation and is transmitting well. 

**Genomes** - Note: There are still three sequences on Usher from New York that are not on GISAID. I'm pretty sure there's a lab in New York whose sequences never get uploaded to GISAID but which show up on Usher trees, so I'm not sure if these sequences will ever be on GISAID.
<details>
<summary>Genomes</summary>
EPI_ISL_19217715, EPI_ISL_19217894, EPI_ISL_19221915,
EPI_ISL_19231606, EPI_ISL_19262935, EPI_ISL_19273796,
EPI_ISL_19277632, EPI_ISL_19284824-19284825
</details>

**Comment by aviczhl2** [comment]
The parent is now KP.3.1.6

**Comment by FedeGueli** [comment]
13 on Gisaid that should mean 16. One sample from Switzerland via GBW

**Comment by FedeGueli** [comment]
19 on Gisaid checking in USher this is quite fast.

**Comment by Mydtlwn** [comment]
At the same time, it has S:R346T and S:H445R, I think you'll be very interested.
@corneliusroemer

**Comment by FedeGueli** [comment]
Designated MK.3 via https://github.com/cov-lineages/pango-designation/commit/2b11a9d8c2daa2f71ba63d0ddf96e61e4d43a0d0
