### ISSUE TITLE
Sublineage of B.1.1.28 (proposed P.3) with spike mutations E484K, N501Y, P681H, 141-143del

### ISSUE THREAD

**Issue by rambaut** [cov-lineages/pango-designation#27]
A sublineage of B.1.1.28 predominantly in the Philippines (plus 1 genome from Germany). 
12 amino acid altering mutations (3 synonymous mutations) including 6 in spike

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/686405/110505208-d68f7200-80f5-11eb-9917-a981b3694b7b.png">

```
ORF1a:    D1554G
          D2980N
          L3201P
          D3681E

ORF1b:    L1203F

spike:    141-143del
          E484K
          N501Y
          P681H
          E1092K
          H1101Y

ORF8:     K2Q

synonymous: C7564A, T23341C, T24187A
```

Genome set:
[P.3.txt](https://github.com/cov-lineages/pango-designation/files/6110041/P.3.txt)

**Comment by rambaut** [comment]
A preprint about this lineage has been published:
https://www.medrxiv.org/content/10.1101/2021.03.03.21252812v2

**Comment by aineniamh** [comment]
Designation release now tagged with the addition of the 34 P.3 sequences.
https://github.com/cov-lineages/pango-designation/releases/tag/v1.0.9
