### ISSUE TITLE
Proposal for growing Thai Delta-21J lineage with E:62F, ORF1a:148G, ORF3a:140F (>50%)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#270]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: Delta 21J
Earliest sequence: Thailand end of May, the first sequence from Jan is probably date error
Most recent sequence: Current
Countries circulating: Thailand >50%, Cambodia 20%, Sweden 1%

Lineage deriving from B.1.617.2 (21J) but with extra mutations E:62F, ORF1a:148G, ORF3a:140F. It has shown very significant growth especially in Thailand where it seems to have grow to beyond 60% quadrupling in less than 2 months.

Country | Total Variant Sequences | First seq. found at | Last seq. found at
-- | -- | -- | --
Thailand | 300 | 2021-01 | 2021-39
Cambodia | 47 | 2021-27 | 2021-38
Japan | 2 | 2021-27 | 2021-37
Canada | 3 | 2021-27 | 2021-35
USA | 1 | 2021-28 | 2021-28
Germany | 4 | 2021-30 | 2021-40
Sweden | 79 | 2021-30 | 2021-36
Finland | 5 | 2021-30 | 2021-32
Austria | 2 | 2021-30 | 2021-34
United Kingdom | 1 | 2021-31 | 2021-31
India | 2 | 2021-32 | 2021-33

![image](https://user-images.githubusercontent.com/25161793/137985442-f370597d-9028-4c90-921a-9511ff7cbe08.png)
https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/Thailand/AllSamples/AllTimes/variants?aaMutations=E%3A62F%2CORF1a%3A148G&pangoLineage=B.1.617.2*

![image](https://user-images.githubusercontent.com/25161793/137985492-2a0ae158-24c1-4ea2-ab2c-236756ce6c2d.png)
https://nextstrain.org/groups/neherlab/ncov/asia-thailand?branchLabel=aa&c=gt-ORF3a_140&label=clade:21J%20%28Delta%29&m=div&tl=pango_lineage

**Comment by chrisruis** [comment]
Thanks @corneliusroemer This was added during the recent large update of Delta as AY.85
