### ISSUE TITLE
KP.2.3 + S:∆S31, T572I [Full Quad] (51 seq,  12 countries, July 25)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2700]
### **Description** Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1582
**Sub-lineage of:** KP.2.3 (JN.1.11.1.2.3 = JN.1 + S:H146Q, R346T, F456L, V1104L, ORF3a:K67N, ORF1a:T2283I)
**Earliest sequence:** 2024-4-24, Mauritius, Grand Port — EPI_ISL_19170222
**Most recent sequence:** 2024-5-7, Canada, Alberta — EPI_ISL_19163154
**Continents circulating:** Africa (1), Asia (1), Europe (29), North America (18)
**Countries circulating:**  12 different ones
**Number of Sequences:** 51
**GISAID Nucleotide Query:** C23277T, G25593T, C28714T, T3565C, C28714T, -C25416T, -T16746C, -A21917G, -C25708A, -G25088T
**CovSpectrum Query:** Nextcladepangolineage:KP.2* & [2-of: C23277T, G25593T]
**Substitutions on top of KP.2.3:** 
**Spike:** ∆S31, T572I
**Nucleotide:** ∆21653-21655, C23277T, C28714T

**Phylogenetic Order of Mutations:** C28714T, ∆21653-21655 (S:∆S31)  **→** C23277T (S:T572I) 

**USHER Tree** (Temporary link)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e5c7_2455d0.json?f_userOrOld=uploaded%20sample&label=id:node_7039539
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/2e546d86-cdc3-4d4e-94bd-e144db755a61">

**Evidence**
The S:Q1002H branch is especially interesting. S:Q1002H is a rare mutation but has been seem in some remarkable chronic infections, including one very well documented BA.1 infection in the Netherlands. ORF7a:T39I and ORF1a:L122F are also characteristic of chronics. 

There are three CDC sequences from the US on the Usher tree but not on GISAID—two from New York and one from Florida. 

This is maybe the first branch to have the Full Quad, as I call it: S:∆S31, S:R346T, S:F456L, S:T572I. KP.2.3 also has S:H146Q, famously in  BJ.1/XBB. However, the Mauritius sequence does not register S:H146Q, but given the amount of dropout in that sequence, along with the fact that his region of spike is often a troublesome one (with either S:G142D or S:∆Y144 often missing from sequences), and *especially* the fact that the Mauritius sequence shares the synonymous C28714T with the other two sequences I think it's almost certain that it really has H146Q. 

Incidentally, C28714T is one of the three defining mutations of KP.2.3.1, along with S:∆S31. So these sequences have two of the three defining KP.2.3.1 mutations but all lack the third, which is S:A475V.

If the Mauritius sequence really does not have S:H146Q, then it would not technically be part of KP.2.3, even though it contains the other KP.2.3-defining mutation, ORF3a:K67N, and two of the three defining KP.2.3 mutations (S:∆S31 & C28714T). It would constitute a separate KP.2 + S:∆S31 + S:T572I + ORF3a:K67N branch. But that seems extraordinarily unlikely.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19163154, EPI_ISL_19166256, EPI_ISL_19170222,
EPI_ISL_19192876, EPI_ISL_19194175, EPI_ISL_19195633,
EPI_ISL_19195901, EPI_ISL_19201415, EPI_ISL_19214034,
EPI_ISL_19219787, EPI_ISL_19228107, EPI_ISL_19229098,
EPI_ISL_19229121, EPI_ISL_19230366, EPI_ISL_19244526,
EPI_ISL_19251944-19251945, EPI_ISL_19251949, EPI_ISL_19251960,
EPI_ISL_19251977, EPI_ISL_19251985, EPI_ISL_19251994,
EPI_ISL_19252002, EPI_ISL_19258121, EPI_ISL_19260931,
EPI_ISL_19260967, EPI_ISL_19262078, EPI_ISL_19262370,
EPI_ISL_19264949, EPI_ISL_19265008, EPI_ISL_19268306-19268308,
EPI_ISL_19273894, EPI_ISL_19279050, EPI_ISL_19279054,
EPI_ISL_19279079, EPI_ISL_19279111, EPI_ISL_19279801,
EPI_ISL_19283729, EPI_ISL_19283864, EPI_ISL_19284964,
EPI_ISL_19285044, EPI_ISL_19285068, EPI_ISL_19285092,
EPI_ISL_19285125, EPI_ISL_19285132, EPI_ISL_19285191,
EPI_ISL_19285201
</details>

**Comment by FedeGueli** [comment]
Designated KP.2.3.6 via https://github.com/cov-lineages/pango-designation/commit/4ee31e1915ed234bfcd5ae74e79aec4842a0aadd
