### ISSUE TITLE
KP.2+S:S31del+Orf3a:A110S,Orf8:G77S( 105 seqs, 9 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2702]
From branch 18 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1502
KP.2+C11020T+del21653_21655(S;S31del)+T9499G, G25720T, G28122A(Orf3a:A110S, Orf8:G77S)

GISAID query: C11020T,del21653_21655,G28122A
No. of seqs: 91(UK 74 France 4 Germany 2 Israel 5 Netherlands 2 USA 4(2 from New Zealand 1 from Spain))

First: EPI_ISL_19088106, 2024-4-16, UK
Latest: EPI_ISL_19289652, 2024-7-15, USA from New Zealand

There are also some KP.2+C11020T+S:S31del seqs on other branches, however given the high convergence of C11020T they may not actually belong to the same branch as this branch. 

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/kp_2_s31-.json?f_userOrOld=uploaded%20sample&label=id:node_5494738)
![image](https://github.com/user-attachments/assets/5a1e7ed3-799f-4168-89fa-7931d3b527d3)

**Comment by aviczhl2** [comment]
105, Canada

**Comment by aviczhl2** [comment]
Designated KP.2.23

**Comment by FedeGueli** [comment]
Kp.2.23 via https://github.com/cov-lineages/pango-designation/commit/44e1946dd2751d2adbdf8a99d4692f87e27dad3f
