### ISSUE TITLE
KP.3.3 + ORF1a:I1367L (423 seq, 5 continents, 25 countries; Aug 4)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2707]
**Description** - Trasferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1801
**Sub-lineage of:** KP.3.3
**Earliest sequence:** 2024-5-13, Luxembourg — EPI_ISL_19229409
**Most recent sequence:** 2024-7-22, Denmark — EPI_ISL_19299736
**Continents circulating:** Europe (328), North America (32), Africa (1), Asia (1), Oceania (1)
**Countries circulating:** Germany (130), Netherlands (51), France (30), Denmark (27), England (27), Spain (17), Scotland (9), USA (8), Luxembourg (7), Wales (7), Austria (5), Iceland (3), Ireland (3), Italy (3), Norway (3), Belgium (2), Canada (2), Canary Islands (2), Croatia (2), Switzerland (2), Australia (1), Kenya (1), Northern Ireland (1), Slovenia (1), Taiwan (1)
**Number of Sequences:**  355
**GISAID Nucleotide Query:** A4364C, T8263C, -A3081C
**CovSpectrum Query:** [2-of: A4364C, T8263C] & !A3081C
**Substitutions on top of KP.3.3:**
**ORF1a:** I1367L (NSP3_I549L)

**Nucleotide:** A4364C, T8263C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.3.3_I1367L.json

Note that the poor quality of a large number of these genomes, particular those from Germany and Luxembourg, makes the Usher tree appear as if there is far more diversity than there actually is. If artifactual reversions could be removed, this would be a much more compact tree. 

<img width="1498" alt="image" src="https://github.com/user-attachments/assets/222a1aa4-0640-4bf4-939e-2b4b519cea3d">

**Evidence**
ORF1a:I1367L (NSP3_I549L) has been a very rare mutation. Excluding BA.2.86* (which are virtually all in this lineage), CovSpectrum counts only 220 sequences ever. Restricting the search to "good" sequences returns just 116 sequences. But ORF1a:I1367L has been a prominent mutation in many chronic-infection sequences. 

I keep a large list of such sequences, and after adjusting for mutation frequency in circulating lineages, ORF1a:I1367L is the 19th most frequent chronic-infection mutation (considering only mutations that appear at least 10 times independently). Restricting to sequences that appear at least 20 times independently, it comes in at `#8`. 

But as described above, it's a mutation that has been virtually nonexistent in circulating lineages, which is why it's remarkable that it has succeeded so well in KP.3.3 over the last two months, primarily in Europe, but also with detections in five of the six other inhabited continents. 

Note: A large number of these genomes are really, really low-quality sequences from Germany, a country heretofore known for its craftsmanship and high-quality productions. The spike protein in most of these sequences is almost nonexistent downstream of S:210, but ORF1a is reasonably well covered. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19189948,EPI_ISL_19189954,EPI_ISL_19189956,EPI_ISL_19192347,EPI_ISL_19192359,EPI_ISL_19197977,EPI_ISL_19198271,EPI_ISL_19203525,EPI_ISL_19205892,EPI_ISL_19206086,EPI_ISL_19206089,EPI_ISL_19209798,EPI_ISL_19210151,EPI_ISL_19210272,EPI_ISL_19210350,EPI_ISL_19220531,EPI_ISL_19220631,EPI_ISL_19221125,EPI_ISL_19221141,EPI_ISL_19221582,EPI_ISL_19221672,EPI_ISL_19221719,EPI_ISL_19225081,EPI_ISL_19225216,EPI_ISL_19225233,EPI_ISL_19225522,EPI_ISL_19226128,EPI_ISL_19229053,EPI_ISL_19229320,EPI_ISL_19229323,EPI_ISL_19229328,EPI_ISL_19229331,EPI_ISL_19229338-19229340,EPI_ISL_19229366,EPI_ISL_19229401,EPI_ISL_19229409,EPI_ISL_19229494,EPI_ISL_19229516,EPI_ISL_19229541,EPI_ISL_19229586,EPI_ISL_19229810,EPI_ISL_19229858,EPI_ISL_19230365,EPI_ISL_19232258,EPI_ISL_19232262,EPI_ISL_19232336,EPI_ISL_19232442,EPI_ISL_19232603,EPI_ISL_19232952,EPI_ISL_19232965,EPI_ISL_19232975,EPI_ISL_19233071,EPI_ISL_19239301,EPI_ISL_19239305,EPI_ISL_19239914,EPI_ISL_19239964,EPI_ISL_19240153,EPI_ISL_19240384,EPI_ISL_19240386,EPI_ISL_19240803,EPI_ISL_19240811,EPI_ISL_19240871,EPI_ISL_19243713,EPI_ISL_19243799,EPI_ISL_19243913,EPI_ISL_19244005,EPI_ISL_19244014,EPI_ISL_19244164,EPI_ISL_19244215-19244216,EPI_ISL_19244231-19244232,EPI_ISL_19244236,EPI_ISL_19244250,EPI_ISL_19244324,EPI_ISL_19244358,EPI_ISL_19244493,EPI_ISL_19244510,EPI_ISL_19244586,EPI_ISL_19244589,EPI_ISL_19244592,EPI_ISL_19244603,EPI_ISL_19244610,EPI_ISL_19244620-19244621,EPI_ISL_19244623,EPI_ISL_19244626-19244627,EPI_ISL_19244629,EPI_ISL_19244639,EPI_ISL_19244646,EPI_ISL_19244651,EPI_ISL_19244660,EPI_ISL_19244669,EPI_ISL_19244677,EPI_ISL_19244680,EPI_ISL_19244685-19244686,EPI_ISL_19244692,EPI_ISL_19244695,EPI_ISL_19244707-19244708,EPI_ISL_19244713-19244715,EPI_ISL_19244717-19244718,EPI_ISL_19244725,EPI_ISL_19244729,EPI_ISL_19244732,EPI_ISL_19244739,EPI_ISL_19244746,EPI_ISL_19244754,EPI_ISL_19244758,EPI_ISL_19244762-19244763,EPI_ISL_19244771-19244772,EPI_ISL_19250949,EPI_ISL_19251980,EPI_ISL_19252426,EPI_ISL_19252437,EPI_ISL_19252882,EPI_ISL_19252918,EPI_ISL_19253375,EPI_ISL_19254246,EPI_ISL_19254266,EPI_ISL_19254268,EPI_ISL_19254294,EPI_ISL_19254497,EPI_ISL_19254630,EPI_ISL_19256831,EPI_ISL_19256927,EPI_ISL_19257044,EPI_ISL_19258203,EPI_ISL_19258206,EPI_ISL_19258208,EPI_ISL_19258214-19258215,EPI_ISL_19258414,EPI_ISL_19260250,EPI_ISL_19261237,EPI_ISL_19261271,EPI_ISL_19261308,EPI_ISL_19261377,EPI_ISL_19261460,EPI_ISL_19261546,EPI_ISL_19261560,EPI_ISL_19261576,EPI_ISL_19261732-19261735,EPI_ISL_19261854,EPI_ISL_19261885,EPI_ISL_19261908,EPI_ISL_19261942,EPI_ISL_19261953,EPI_ISL_19261955,EPI_ISL_19261989,EPI_ISL_19262035,EPI_ISL_19262045,EPI_ISL_19262062,EPI_ISL_19262101,EPI_ISL_19262108,EPI_ISL_19262112,EPI_ISL_19264938,EPI_ISL_19264941,EPI_ISL_19265031,EPI_ISL_19265173-19265174,EPI_ISL_19265215,EPI_ISL_19267201,EPI_ISL_19267536-19267537,EPI_ISL_19267565,EPI_ISL_19267938-19267939,EPI_ISL_19268291,EPI_ISL_19268296,EPI_ISL_19269868,EPI_ISL_19270124,EPI_ISL_19270168,EPI_ISL_19270189,EPI_ISL_19270222,EPI_ISL_19270860,EPI_ISL_19270877,EPI_ISL_19272196,EPI_ISL_19272658,EPI_ISL_19273409,EPI_ISL_19273448,EPI_ISL_19273564,EPI_ISL_19273801,EPI_ISL_19276082,EPI_ISL_19276391,EPI_ISL_19276538,EPI_ISL_19277115,EPI_ISL_19279089,EPI_ISL_19279684,EPI_ISL_19279686,EPI_ISL_19279787,EPI_ISL_19280039-19280040,EPI_ISL_19280440,EPI_ISL_19281116,EPI_ISL_19281361,EPI_ISL_19281374,EPI_ISL_19281386,EPI_ISL_19281411,EPI_ISL_19281844,EPI_ISL_19283606,EPI_ISL_19283735,EPI_ISL_19283737,EPI_ISL_19283743,EPI_ISL_19283747,EPI_ISL_19283753-19283754,EPI_ISL_19283761,EPI_ISL_19283763-19283764,EPI_ISL_19283771,EPI_ISL_19283776,EPI_ISL_19283779-19283781,EPI_ISL_19283787,EPI_ISL_19283790,EPI_ISL_19283795,EPI_ISL_19283802,EPI_ISL_19283806,EPI_ISL_19283809-19283810,EPI_ISL_19283815-19283816,EPI_ISL_19283818,EPI_ISL_19283820,EPI_ISL_19283825,EPI_ISL_19283836,EPI_ISL_19283840-19283841,EPI_ISL_19283844,EPI_ISL_19283850,EPI_ISL_19283852-19283853,EPI_ISL_19283857,EPI_ISL_19283862,EPI_ISL_19283867,EPI_ISL_19283876,EPI_ISL_19283886,EPI_ISL_19283893,EPI_ISL_19283903,EPI_ISL_19283907,EPI_ISL_19283910,EPI_ISL_19283915-19283916,EPI_ISL_19283918,EPI_ISL_19283920,EPI_ISL_19283929-19283930,EPI_ISL_19283933,EPI_ISL_19283938,EPI_ISL_19283948,EPI_ISL_19283951-19283952,EPI_ISL_19283961,EPI_ISL_19283967,EPI_ISL_19283970,EPI_ISL_19283976,EPI_ISL_19285261,EPI_ISL_19285640,EPI_ISL_19285647,EPI_ISL_19285703,EPI_ISL_19285719,EPI_ISL_19285736,EPI_ISL_19285761,EPI_ISL_19285791,EPI_ISL_19285829,EPI_ISL_19285900,EPI_ISL_19285923,EPI_ISL_19285925,EPI_ISL_19287461,EPI_ISL_19287888,EPI_ISL_19288018,EPI_ISL_19288067,EPI_ISL_19288090,EPI_ISL_19288094,EPI_ISL_19288105,EPI_ISL_19288145,EPI_ISL_19288275,EPI_ISL_19288355,EPI_ISL_19288358,EPI_ISL_19288361,EPI_ISL_19288365,EPI_ISL_19288367,EPI_ISL_19288373,EPI_ISL_19288375,EPI_ISL_19288397,EPI_ISL_19289755,EPI_ISL_19289882,EPI_ISL_19289951,EPI_ISL_19291357,EPI_ISL_19291378-19291379,EPI_ISL_19291453,EPI_ISL_19291476,EPI_ISL_19291853,EPI_ISL_19291866,EPI_ISL_19292078,EPI_ISL_19292226,EPI_ISL_19292333,EPI_ISL_19292471,EPI_ISL_19292781,EPI_ISL_19292796,EPI_ISL_19292800,EPI_ISL_19292805,EPI_ISL_19292813-19292814,EPI_ISL_19292828,EPI_ISL_19292833,EPI_ISL_19292835,EPI_ISL_19292860,EPI_ISL_19292878,EPI_ISL_19292898,EPI_ISL_19292949,EPI_ISL_19293173,EPI_ISL_19293222,EPI_ISL_19293230,EPI_ISL_19293263,EPI_ISL_19293272,EPI_ISL_19293305,EPI_ISL_19293346,EPI_ISL_19293371,EPI_ISL_19293373,EPI_ISL_19294999,EPI_ISL_19295180,EPI_ISL_19295187,EPI_ISL_19296640,EPI_ISL_19296980,EPI_ISL_19297047,EPI_ISL_19297062,EPI_ISL_19297927-19297928,EPI_ISL_19298060,EPI_ISL_19298340,EPI_ISL_19299642,EPI_ISL_19299655,EPI_ISL_19299684,EPI_ISL_19299688,EPI_ISL_19299722,EPI_ISL_19299724,EPI_ISL_19299728,EPI_ISL_19299736,EPI_ISL_19299816,EPI_ISL_19299821,EPI_ISL_19299839,EPI_ISL_19299895,EPI_ISL_19299961,EPI_ISL_19300044,EPI_ISL_19300160,EPI_ISL_19300321,
</details>

**Comment by FedeGueli** [comment]
454 now spreading fast.

**Comment by FedeGueli** [comment]
464

**Comment by FedeGueli** [comment]
Designated KP.3.3.4 via https://github.com/cov-lineages/pango-designation/commit/5718a44995e6aede1a14292c5001dc7494746a4a
