### ISSUE TITLE
JN.1.29.1(S:F456L) subbranch with S:R346T(23 seqs, 4 countries) and further S:L56V(15 seqs, 3 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2708]
Found with @aviczhl2 's phylogenic tree analysis tool.

JN.1.29.1> C8917T> G22599C(S:R346T)> G18318T, C20930T(Orf1b:T2488M)> A259G, A28984G> T21728G(S:L56V)
Query: C8917T, A9935G, G22599C, -A405G

Earliest sequence: 03-26 Eusebio, Ceara, Brazil EPI_ISL_19282419
Latest sequences: 06-30 California, USA(imported from Spain) EPI_ISL_19273788
Regions detected: Brazil 18, US 4(including 1 in Puerto Rico, 2 from Spain, 1 from unknown), UK 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3adbf_bc87e0.json?f_userOrOld=uploaded%20sample
![image](https://github.com/user-attachments/assets/c356d40f-1bfa-431a-a4c4-94c834410c44)

<details> <summary> Sequences: </summary>

EPI_ISL_18952414, EPI_ISL_18961998, EPI_ISL_18998958-18998959,
EPI_ISL_19043828, EPI_ISL_19064049, EPI_ISL_19133577,
EPI_ISL_19230423, EPI_ISL_19254506, EPI_ISL_19269974,
EPI_ISL_19271357, EPI_ISL_19273788, EPI_ISL_19282403-19282404,
EPI_ISL_19282406-19282409, EPI_ISL_19282420, EPI_ISL_19282423-19282424,
EPI_ISL_19287115, EPI_ISL_19288494

</details>

**Comment by FedeGueli** [comment]
wrong repo

**Comment by Over-There-Is** [comment]
sars-cov-2-variants/lineage-proposals#1813

**Comment by Over-There-Is** [comment]
MC.2.1
