### ISSUE TITLE
KP.3.1 subbranch with S:L84I(61 seqs, 9 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2709]
This lineage is already proposed by @aviczhl2 in sars-cov-2-variants/lineage-proposals#1709.
Query: G15372T, A19722G, C21812A (host: human)

Earliest sequence: 05-11 Virginia ,USA (imported from Austria) EPI_ISL_19162555
Latest sequence: 07-22 Denmark EPI_ISL_19299842
Regions detected: UK 20, US 20(1 from Austria, 1 from Turkey), Canada 10, Ireland 5, France 3, Denmark 2, Italy 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2ab39_c39010.json?c=country&label=id:node_7030430
![image](https://github.com/user-attachments/assets/010b389d-1e6f-4164-b5b4-8a4e5a0af8e7)

<details> <summary> Sequences: </summary>

EPI_ISL_19162555-19162556, EPI_ISL_19184769, EPI_ISL_19189107,
EPI_ISL_19191343, EPI_ISL_19191513, EPI_ISL_19192434,
EPI_ISL_19205540, EPI_ISL_19216232, EPI_ISL_19223650,
EPI_ISL_19224103, EPI_ISL_19228970, EPI_ISL_19228993,
EPI_ISL_19230643, EPI_ISL_19232330, EPI_ISL_19239407,
EPI_ISL_19240284-19240285, EPI_ISL_19253131, EPI_ISL_19257068,
EPI_ISL_19257107, EPI_ISL_19258529, EPI_ISL_19258591,
EPI_ISL_19260267, EPI_ISL_19260868, EPI_ISL_19261233,
EPI_ISL_19261558, EPI_ISL_19265447, EPI_ISL_19265638,
EPI_ISL_19267221, EPI_ISL_19269410, EPI_ISL_19269903,
EPI_ISL_19270126, EPI_ISL_19270729, EPI_ISL_19271532,
EPI_ISL_19272124, EPI_ISL_19272162, EPI_ISL_19276428,
EPI_ISL_19276439, EPI_ISL_19281701, EPI_ISL_19282056,
EPI_ISL_19282348, EPI_ISL_19284070, EPI_ISL_19285030,
EPI_ISL_19285110, EPI_ISL_19285186, EPI_ISL_19285202,
EPI_ISL_19285693, EPI_ISL_19286579, EPI_ISL_19288034,
EPI_ISL_19288043, EPI_ISL_19288172, EPI_ISL_19289503,
EPI_ISL_19290145, EPI_ISL_19294375, EPI_ISL_19294417,
EPI_ISL_19294441, EPI_ISL_19294883, EPI_ISL_19298912,
EPI_ISL_19299842, EPI_ISL_19303234

</details>

**Comment by aviczhl2** [comment]
Transfered from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1709

**Comment by Over-There-Is** [comment]
Mis operated. I didn't notice it's the main repo here. I'm trying to propose this on the preproposal repo, and didn't find it was already proposed by @aviczhl2.

**Comment by aviczhl2** [comment]
> Mis operated. I didn't notice it's the main repo here. I'm trying to propose this on the preproposal repo, and didn't find it was already proposed by @aviczhl2.

You can transfer that here.

**Comment by FedeGueli** [comment]
KP.3.1.7

**Comment by FedeGueli** [comment]
There is a subbranch of this with S:P384S counting 18 all recent but all from New Brunswick, Canada, very likely a cluster
Query: G15372T, A19722G, C21812A, C22712T

**Comment by DailyCovidCases** [comment]
242 seqs now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_cb44_55ae20.json?f_userOrOld=uploaded%20sample)
https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nextcladePangoLineage=KP.3.1.7*&
![Screenshot (250)](https://github.com/user-attachments/assets/ae213561-e70b-4449-b5ad-a20705a31ca6)

**Comment by FedeGueli** [comment]
> 242 seqs now: [usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_cb44_55ae20.json?f_userOrOld=uploaded%20sample) https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nextcladePangoLineage=KP.3.1.7*& ![Screenshot (250)](https://private-user-images.githubusercontent.com/92421581/374643004-ae213561-e70b-4449-b5ad-a20705a31ca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MjMxNDEsIm5iZiI6MTcyODQyMjg0MSwicGF0aCI6Ii85MjQyMTU4MS8zNzQ2NDMwMDQtYWUyMTM1NjEtZTcwYi00NDQ5LWI1YWQtYTIwNzA1YTMxY2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIxMjcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NDE1ZDhlMzg5NmY5ZDdmZjYzMzU5ZjNmZTJiMWY5M2RmMjc3NzIwNDYyMjIwODRjMmRlYTJiMDNkNzc4NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8BeIm86Hfh2M9AUY_lkbAEUJUo4cD1rDNcfU6YE0fTo)

it is alreadat KP.3.1.7
