### ISSUE TITLE
Proposal for a new B.1.617.2 sublineage with N:P207S, Orf1b:K469N circulating in Belgium

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#271]
Looking at 20I Nextstrain clade i spotted a couple of still undesignated sublineages:

The first one is a relatively small clade circulating in Belgium (407 sequences) and Netherlands (161 sequences) since may 2021
with key mutations Orf1b:K469N and N:P207S plus synonymous T6496C,G14874T
![Schermata 2021-10-19 alle 23 23 41](https://user-images.githubusercontent.com/87669813/137992788-05c3faef-a2f1-43d1-8781-67459f1f07b2.png)
https://nextstrain.org/groups/neherlab/ncov/belgium?branchLabel=aa&c=gt-nuc_6469,14874&d=tree,entropy,frequencies&p=full&r=division&tl=pango_lineage

It is around 3% in Belgium according to covspectrum.ethz.ch:
![Schermata 2021-10-19 alle 23 28 56](https://user-images.githubusercontent.com/87669813/137993448-b67fff13-c022-47f4-b07c-eea17e86ddd5.png)

2% cumulative prevalence in Belgium on Outbreak.info:
![Schermata 2021-10-19 alle 23 30 02](https://user-images.githubusercontent.com/87669813/137993617-b9f19e45-0195-444a-8bd3-0eedf0511258.png)

Looking at the same tree it is quite clear that a clade (the one starting with N950D) is still mistakenly not assigned to AY.9:
![Schermata 2021-10-19 alle 23 33 08](https://user-images.githubusercontent.com/87669813/137994211-f3fa6ea5-8759-4cbf-8205-bfc278ffc7c4.png)

Here the sequences if it could help:
![Schermata 2021-10-19 alle 23 36 26](https://user-images.githubusercontent.com/87669813/137994367-6f3ae5e1-deb2-43e8-b124-514b9ccdd8dc.png)

**Comment by FedeGueli** [comment]
This has been designated as AY.66 starting with T6496C 
According to new designations from https://www.pango.network/summary-of-designated-ay-lineages/
Tree:
![Schermata 2021-11-01 alle 20 50 32](https://user-images.githubusercontent.com/87669813/139732903-99baa326-6aeb-4b4b-ab32-7925c15dd867.png)


cc @chrisruis

**Comment by corneliusroemer** [comment]
Thanks @FedeGueli you should include the commit message of the designation to improve trackability like this https://github.com/cov-lineages/pango-designation/commit/1478ff2e39eedfcfad874c88cd8deede256e4e62

you can find the commit by using github search for say AY.66

**Comment by FedeGueli** [comment]
Hi @corneliusroemer thank you, i wasnt able to find the commit of the others issues i matched with new AY.s
