### ISSUE TITLE
KP.2.15+S:T572I FULL QUAD(26 seqs, 6 countries, 10 with S:G798S) 

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2711]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1791
KP.2.15(DeFLiRT)+T12304C+A3580G, T9418C, C23277T(S:T572I)

GISAID query: C23277T, T12304C, A10861G, G17334T
No. of seqs: 26(Denmark 5 Germany 1 Luxembourg 1 Sweden 13 USA 6(1 from Germany))

First: EPI_ISL_19254796, Sweden, 2024-6-5
Latest: EPI_ISL_19311420, USA, 2024-7-23

GISAID query for S:G798S sub-branch: C23277T, T12304C, A10861G, G23954A

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/kp_2_15_t572i.json?label=id:node_7057402)

![image](https://github.com/user-attachments/assets/160831f3-a372-44ba-b5f2-37bd13e1f414)

@AngieHinrichs many 31del seqs are mislabeled as S31F in this branch, too.

**Comment by FedeGueli** [comment]
KP.2.15 via https://github.com/cov-lineages/pango-designation/commit/74458d84b3940a49a6b9b2b75daf8f071d7d508c

**Comment by FedeGueli** [comment]
@aviczhl2 would you like to reaarange the proposal for the G798S sublineage? is it worth?

**Comment by FedeGueli** [comment]
15 for the G798S branch
