### ISSUE TITLE
LB.1.2+S:T572I FULL QUAD( 32 seqs, 13 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2712]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1792
LB.1.2(DeFLiRT)+C23277T(S:T572I)

GISAID query: G19669A, C23277T, G22111T,G22599C
No. of seqs: 32(Australia 2 Canada 4 Denmark 1 Ireland 1 Israel 3 Japan 1(from USA) Malaysia 1 Netherlands 1 Spain 1 USA 17(2 from Mexico, 2 from Netherlands, 5 from Peru, 1 from Guatemala)

First: EPI_ISL_19205993, USA from Peru, 2024-6-7
Latest: EPI_ISL_19313369,Canada, 2024-7-29

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/lb_1_2_t572i.json?label=id:node_7238283)
![image](https://github.com/user-attachments/assets/9b7dcb42-f007-4381-94ca-5e2da52ccd06)

@AngieHinrichs  There is also S:S31F artifact branch under this, too.

**Comment by FedeGueli** [comment]
Designated LB.1.2.2 via https://github.com/cov-lineages/pango-designation/commit/968a20bc7a6ecf26db18dc0cc4bcbc86a37f4659
