### ISSUE TITLE
Potential KS.1.1/KP.3.3 recombinant (28 sequences, 8 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2717]
Transferred from sars-cov-2-variants/lineage-proposals#1827
Thx @aviczhl2 .

Mutations based on JN.1: C18657T, C19716T, C21627A(S:T22N), T21738C(S:F59S) / T22928C(S:F456L), C23039G(S:Q493E), G24872T(S:V1104L), C25006T, C28291A(Orf9b:P3H), G28884C(N:R204P)
The 5' donor could be from a pre-C6701T KS.1.1 branch with C18657T.
Breakpoint: 21738\~22599
Query: C18657T, C19716T, C25006T
Query for sequences without 19716 mutation: -G9130T, C18657T, -C19716T, G24872T, C25006T

Earliest sequence: 06-24 Berlin, Germany EPI_ISL_19283881
Latest sequence: 07-28 Stockholm, Sweden EPI_ISL_19310587
Regions detected:
**Germany** 11(Bayern 6, Berlin 3, Nordrhein-Westfalen 2), **Netherlands** 4(Noord-Brabant 1, Noord-Holland 1, Utrecht 1, Zuid-Holland 1), **Sweden** 3(Stockholm 2, Örebro 1), **France** 1(ARA), **Spain** 1(Asturias), **UK** 1(Scotland)
**US** 6(Virginia 3, Washington 2[1 from airport screening, 1 from Germany], Ohio 1); 
**South Korea** 1.

https://nextstrain.org/fetch/raw.githubusercontent.com/Over-There-Is/subtreeAuspice/main/KS.1.1-KP.3.3.json?c=country&label=id:node_7040630
![image](https://github.com/user-attachments/assets/31225968-f51c-46b5-a196-7e36f9ee6db9)

<details><summary>Sequences:</summary>

EPI_ISL_19270230, EPI_ISL_19283843, EPI_ISL_19283881,
EPI_ISL_19283891, EPI_ISL_19283905, EPI_ISL_19288354,
EPI_ISL_19292873, EPI_ISL_19299882, EPI_ISL_19300184,
EPI_ISL_19304941, EPI_ISL_19308953, EPI_ISL_19308959,
EPI_ISL_19308971, EPI_ISL_19308982, EPI_ISL_19308990,
EPI_ISL_19309895, EPI_ISL_19309916, EPI_ISL_19310160,
EPI_ISL_19310201, EPI_ISL_19310562, EPI_ISL_19310587,
EPI_ISL_19310626, EPI_ISL_19310656, EPI_ISL_19310662,
EPI_ISL_19312373, EPI_ISL_19313844, EPI_ISL_19313900,
EPI_ISL_19314468
</details>

**Comment by FedeGueli** [comment]
cc @corneliusroemer @AngieHinrichs @thomasppeacock initial growth pretty impressive i suggest direct designation for this.

**Comment by FedeGueli** [comment]
Wait wait the bottom branch has Orf1a:I1367L that is the defining of https://github.com/cov-lineages/pango-designation/issues/2707 and its sublineage #2704 both growing fast too , could be another recombination? or convergence?
@ryhisner (many thx for his neverending effort!) has identified that mutation as a marker in chronic infections that until today has not spread easily in general population, so how many chances it is a second appearance instead of a further recombination?

**Comment by aviczhl2** [comment]
> Wait wait the bottom branch has Orf1a:I1367L that is the defining of #2707 and its sublineage #2704 both growing fast too , could be another recombination? or convergence? @ryhisner (many thx for his neverending effort!) has identified that mutation as a marker in chronic infections that until today has not spread easily in general population, so how many chances it is a second appearance instead of a further recombination?

This is interesting. Like XDP/XEB, a 1-BP recomb and a 2-BP recomb of same lineages occur at the same time.

**Comment by FedeGueli** [comment]
33

**Comment by corneliusroemer** [comment]
I'm having a look! At a high level, this one is interesting because it has the somewhat beneficial N/ORF9b of KP.3.3 and S:59 and S:22, right?

22 on its own seems to be less beneficial than 31del, am I right? Have we ever seen 22 and 31del together? Are they additively beneficial?

**Comment by corneliusroemer** [comment]
Designated as XEC - thanks for the issue, characterisation and ping everyone!

**Comment by FedeGueli** [comment]
> I'm having a look! At a high level, this one is interesting because it has the somewhat beneficial N/ORF9b of KP.3.3 and S:59 and S:22, right?

Right!

> 22 on its own seems to be less beneficial than 31del, am I right? Have we ever seen 22 and 31del together? Are they additively beneficial?

Not yet just a dozen and half of sequences with that combo but all recent so it could be the next development but we saw 22N working quite well with S:31X i think in MB.1.1 

> 
> KS is JN.1.13.1 off the top of my head, correct?

yeah exactly!

Thx for designating

**Comment by Over-There-Is** [comment]
It's also detected in Canada now.

**Comment by aviczhl2** [comment]
> I'm having a look! At a high level, this one is interesting because it has the somewhat beneficial N/ORF9b of KP.3.3 and S:59 and S:22, right?
> 
> 22 on its own seems to be less beneficial than 31del, am I right? Have we ever seen 22 and 31del together? Are they additively beneficial?

S:T22N is slightly more beneficial than S:S31-. on both FLiRT and FLuQE (KP.2 and KP.3) backbone.

![image](https://github.com/user-attachments/assets/4dfad16e-c1aa-41af-a43e-ea7d1c8c5ba3)

![image](https://github.com/user-attachments/assets/6261b7da-73a3-47e0-8f3a-8fbce0fba032)

**Comment by aviczhl2** [comment]
![image](https://github.com/user-attachments/assets/9a2c05be-9fb6-47ea-bf25-82eeecbf90d2)

And the beneficial effects of T22N and S31- seem stack on FLiRT backbone. Although there's no KP.3+T22N+S:S31- seqs yet.

**Comment by FedeGueli** [comment]
> > I'm having a look! At a high level, this one is interesting because it has the somewhat beneficial N/ORF9b of KP.3.3 and S:59 and S:22, right?
> > 22 on its own seems to be less beneficial than 31del, am I right? Have we ever seen 22 and 31del together? Are they additively beneficial?
> 
> S:T22N is slightly more beneficial than S:S31-. on both FLiRT and FLuQE (KP.2 and KP.3) backbone.
> 
> ![image](https://private-user-images.githubusercontent.com/10445944/356052596-4dfad16e-c1aa-41af-a43e-ea7d1c8c5ba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDMyNTEsIm5iZiI6MTcyMzEwMjk1MSwicGF0aCI6Ii8xMDQ0NTk0NC8zNTYwNTI1OTYtNGRmYWQxNmUtYzFhYS00MWFmLWE0M2UtZWE3ZDFjOGM1YmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA3NDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZjM2NmQ1NGQwZWZiMmFmYjBhYjFmNmY4MmVmMzE0ODc0ZDlkOGI3ZGUzMjYyNTg2MTRlMWRhYmFjMmUzZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rp3jLwLlKYD4Xd42XXgyG77ozYbZJDaLvTBdSP7Xq8w)
> 
> ![image](https://private-user-images.githubusercontent.com/10445944/356052707-6261b7da-73a3-47e0-8f3a-8fbce0fba032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDMyNTEsIm5iZiI6MTcyMzEwMjk1MSwicGF0aCI6Ii8xMDQ0NTk0NC8zNTYwNTI3MDctNjI2MWI3ZGEtNzNhMy00N2UwLThmM2EtOGZiY2UwZmJhMDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA3NDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMTk4MWJiOGExODQwODMwNDNjNTFhMWQzYzFlMzdiYjYyZDMzYzIxZmNmYmUxNDdlMTgyYzI5OTk5OTEyY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P9D7DUCllobP692qgVC3d_bYS5HGuZI3pCBLG5YPvYo)

the 493E calculations is not reliable due to a big cluster of a lineage with S:T22N that is now sinking.

**Comment by FedeGueli** [comment]
> ![image](https://private-user-images.githubusercontent.com/10445944/356053182-9a2c05be-9fb6-47ea-bf25-82eeecbf90d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDMyNTEsIm5iZiI6MTcyMzEwMjk1MSwicGF0aCI6Ii8xMDQ0NTk0NC8zNTYwNTMxODItOWEyYzA1YmUtOWZiNi00N2VhLWJmMjUtODJlZWVjYmY5MGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA3NDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZmNiM2NhZDE2NGQ2YTI3NTRkM2FlYmU4Zjk3OTMxMWY5ZTllNmViMjI2OWQ3M2NiZWZhNTM0ZTIyNDg3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N4RG9aIbwfNyu1j1Y2ZpA4wU5yrlEP2LAMSS4WzA3Bc)
> 
> And the beneficial effects of T22N and S31- seem stack on FLiRT backbone. Although there's no KP.3+T22N+S:S31- seqs yet.

there is one KP.3.1.1 with it : EPI_ISL_19310599 from Sweden 

<img width="1147" alt="Screenshot 2024-08-08 alle 09 49 37" src="https://github.com/user-attachments/assets/76a4f88e-5a8f-4677-94d0-e57019e8e020">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3266_4785b0.json?c=userOrOld&label=id:node_11587690
Query: C1645T, C13264T, T26214C

**Comment by ryhisner** [comment]
Three Canadian sequences on the ORF1a:I1367L branch got the synonymous TRS-like A4576T, T4579A, one of my favorite little hidden gems. They've also got a very rare NSP5 mutation, ORF1a:V3336F (NSP5_V73F), which has been in fewer then 200 sequences ever. 
<img width="1494" alt="image" src="https://github.com/user-attachments/assets/fddc9b23-6202-4659-b187-cb89f5c11b82">

**Comment by FedeGueli** [comment]
> ryhisner

Thank you @ryhisner worth proposing it in a separate issue please!

**Comment by corneliusroemer** [comment]
Interesting - but we'll want some non-Canada or at least non-Ontario sequences here - as Canada is the country with the densest surveillance of all, I think, meaning they cluster a lot and a few sequences don't mean the lineage is very common globally.

**Comment by FedeGueli** [comment]
> Interesting - but we'll want some non-Canada or at least non-Ontario sequences here - as Canada is the country with the densest surveillance of all, I think, meaning they cluster a lot and a few sequences don't mean the lineage is very common globally.

Agree sorry i was thinking we were on the other repo, propose to track it separately there

**Comment by aviczhl2** [comment]
> Interesting - but we'll want some non-Canada or at least non-Ontario sequences here - as Canada is the country with the densest surveillance of all, I think, meaning they cluster a lot and a few sequences don't mean the lineage is very common globally.

May designate the Orf1a:I1367L branch. This is in various countries and a meaningful one convergent to KP.3.3.4.

**Comment by icestorm972** [comment]
FYI, regarding Germany:
As nextclade/pangolin-data has no XEC dataset currently (classifies them as KP.3.3), I used the "substitutions" column of a nextclade analysis of the RKI data*) with a "C18657T & C19716T & C25006T" query:
![XEC_logit_2024-08-21](https://github.com/user-attachments/assets/a0d34160-0b25-4666-b521-a309e4d03ee7)


*) Using RKI GitHub data (last updated today, 2024-08-21), that is (at least on a Wednesday) more up-to-date than GISAID and has sample collection date metadata.

**Comment by Over-There-Is** [comment]
Spotted by @NkRMnZr firstly on 20 Jul on Twitter.

**Comment by aviczhl2** [comment]
> FYI, regarding Germany: As nextclade/pangolin-data has no XEC dataset currently (classifies them as KP.3.3), I used the "substitutions" column of a nextclade analysis of the RKI data*) with a "C18657T & C19716T & C25006T" query: ![XEC_logit_2024-08-21](https://private-user-images.githubusercontent.com/20755156/359972358-a0d34160-0b25-4666-b521-a309e4d03ee7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTY0ODAsIm5iZiI6MTcyNDI1NjE4MCwicGF0aCI6Ii8yMDc1NTE1Ni8zNTk5NzIzNTgtYTBkMzQxNjAtMGIyNS00NjY2LWI1MjEtYTMwOWU0ZDAzZWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE2MDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkOGFlOTdlNTNiMTU5OTZkYWMyYjE0N2RlZmRkZDRkZmNjNGQ3ZDJiM2IwNmMzZTAwMTU5MzRmZDI3NGI2ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iNkLZtua4RnfKBPsSPu7GN9hiiXhvR38TjPmd3_Vw0M)
> 
> *) Using RKI GitHub data (last updated today, 2024-08-21), that is (at least on a Wednesday) more up-to-date than GISAID and has sample collection date metadata.

Since RKI is more up-to-date than GISAID, @AngieHinrichs is it possible to add it into your usher datasets?

**Comment by icestorm972** [comment]
> > FYI, regarding Germany: As nextclade/pangolin-data has no XEC dataset currently (classifies them as KP.3.3), I used the "substitutions" column of a nextclade analysis of the RKI data*) with a "C18657T & C19716T & C25006T" query: 
> > *) Using RKI GitHub data (last updated today, 2024-08-21), that is (at least on a Wednesday) more up-to-date than GISAID and has sample collection date metadata.
> 
> Since RKI is more up-to-date than GISAID, @AngieHinrichs is it possible to add it into your usher datasets?

They (RKI) upload the sequences (the German lab sequences they receive) to GISAID, just with some delay (that was what I meant with "more up-to-date"). So the sequences should land in the GISAID database (guess delayed by 1-7 days).

But as 
- GISAID has no "sample date" and 
- uses upload date (as far as I understand?), and 
- the samples the RKI receives per weekly batch are a mix of samples drawn over several weeks, and
- RKI provides better sample date metadata,
a analysis/observation of growth (for Germany) based on that sequences+metadata is probably better (especially in the beginning)

**Comment by Memorablea** [comment]
103 now

**Comment by Over-There-Is** [comment]
Of course, S:K356T is in all BA.2.86, and this lineage is a recombinant between two JN.1 lineages. It seems there are some sequences has no coverage on 22629, but it doesn't mean it's reverted.
![image](https://github.com/user-attachments/assets/73be3200-6050-41d7-83e8-9a3977edd1a3)

**Comment by Over-There-Is** [comment]
1936 from 46 regions/43 countries now:
china(mainland hk tw) israel japan korea österreich belgium hrvatska czech rep. danmark suomi france deutschland eirinn italia srbija(kosovo) luxembourg nederlands norge polska portugal slovenia españa(mainland canary) sverige uk canada us australia nz brazil ecuador
via US: bharat iraq maldives singapura uae ellada schweiz misr zuid afrika mexico dominican rep. peru
via Japan: philippines

and xek is 69 sequences from 13 regions/countries now:
österreich hrvatska danmark france deutschland eirinn italia nederlands slovenia españa sverige ukraina uk

**Comment by Over-There-Is** [comment]
Another XEC-liked recombinant:
Hubei/HCDC-JZ7482/2024|EPI_ISL_19529646|2024-10-22 Jingzhou, Hubei, China
KS.1.1.2+**A12627G**, C24463T / KP.3.3.1
Breakpoint: 21738\~22599 (same as XEC)
C4927T, C6628T, _C6701T_, C7165T, G11335T, **A12627G**, _C19716T, C21627A, T21738C_ / _T22928C, C23039G, C23202A, G24872T, C25006T, T25652C, C25803T, C28291A, G28884C_

As KS.1.1.2+A12627G, C24463T is detected in Hong Kong and KP.3.3.1 is circulating in whole China, I think this recombinant should be from some where in South China without (publicized) sequencing, e.g. Guangdong, Guangxi, Hunan or Jiangxi.
