### ISSUE TITLE
KP.2.2.2+S:T572I (91 seqs) and its sublineage with S:K182R,S:A846V (35 seqs)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2718]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1643
KP.2.2+C23277T(S:T572I)

GISAID query: C23277T, A25359G, T21737C, -A2745G, -24364,-28468,-25455,-29410
No. of seqs: 32

This has also a further main branch with two further spike mutations S:K182R,S:A846V
KP.2.2 > S:T572I (C23277T) > C5183T, S:K182R (A22107G), S:A846V (C24099T), A25315G
Query: C5183T, C24099T,T3565C
Samples: 25
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_189c2_39a1c0.json)
![Screenshot (160)](https://github.com/user-attachments/assets/f0c10a9d-812f-4eac-980d-9ba8126f30fb)

**Comment by FedeGueli** [comment]
Again you breached the rules.

**Comment by Mydtlwn** [comment]
Rules

1) While here everyone could propose everything (avoiding mindless proposals) , and it is allowed to comment freely on the issues, when we have to transfer a proposal to the main Pango repo or to extract one tracked branch from a multiple lineages issue it is STRICTLY needed to wait the green light by one of the moderators of this repo.

2) it is NOT possible to propose/transfer lineages described by other authors without the EXPLICIT consent of them.

**Comment by Sam8138** [comment]
On behalf of those of us who follow along quietly -

Thank you all for your continued hard work. It has not gone unnoticed or unappreciated.

There is no need for us to clutter your feed. And thought we remain silent, we deeply appreciate you and your work.

**Comment by AngieHinrichs** [comment]
@DailyCovidCases we really need to hear from you.  Can you answer these questions?

1. Did you write code to update and create GitHub issues, or are you doing this work manually (but just extremely consistently)?
2. Can you agree to reply, with detailed reasoning, when someone asks you why you did something or complains about something that you did?
3. Can you agree not to create an issue in the pango-designation repository, for a lineage already proposed by somebody else in the lineage-proposals repository, unless you first ask for permission and the original proposer says yes?
4. Does the use of the English language in this project make communication more difficult for you?

I don't think you are an "AI", I think you are a person who finds communicating with other people (perhaps especially in English?) more difficult than accomplishing tasks using computers, and therefore avoids that communication if possible.  But communication among the people working on this project is a critical element of the project.  We need for you to reply to questions, and to be willing to change some practices that don't work well for other people who have worked on this for a long time.  If using English is adding to the difficulty, then we may be able to find ways around it (for example, perhaps somebody else on the project speaks a language that you are more comfortable with?).

**Comment by FedeGueli** [comment]
Last pattern is copying and pasting exactly the words used by some of us to ping Cornelius about this or that lineage, that obviously ends to sound out of context.

**Comment by ryhisner** [comment]
I'm in favor of banning this account immediately. What are your thoughts, @corneliusroemer?

**Comment by AngieHinrichs** [comment]
GitHub's API makes it easy for a proficient programmer to write a script that comments on an issue or even submits a new issue.  I think of that as scripting, not AI -- although generative AI has made it a lot easier for any sufficiently motivated person to write such scripts.  

I don't think the use of scripts is inherently unacceptable, as long as the script author promptly fixes bugs in the scripts (like asking for issue #1 to be closed, or copying an issue to this repo without getting OP permission) when bugs are reported, and is willing to practice basic teamwork (like responding to questions/concerns).

Since @DailyCovidCases has not replied to our concerns and questions, but has continued to add templated comments and issues, I agree it's time to block them.  [Blocking a user](https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization) needs to be done by an owner or moderator of the organization (cov-lineages for this repo).  At the moment, neither @corneliusroemer nor I have that status in cov-lineages.  I have pinged the cov-lineages owners (outside of github).

**Comment by DailyCovidCases** [comment]
Did you write code to update and create GitHub issues, or are you doing this work manually (but just extremely consistently)?
Can you agree to reply, with detailed reasoning, when someone asks you why you did something or complains about something that you did?
Can you agree not to create an issue in the pango-designation repository, for a lineage already proposed by somebody else in the lineage-proposals repository, unless you first ask for permission and the original proposer says yes?
Does the use of the English language in this project make communication more difficult for you?
Answer: 
1. I did this work manually and consistantly
2. I agree that I will reply with detailed reasoning
3. I sincerely apologize you to create an issue too much.
4. No, I don't think so

**Comment by AngieHinrichs** [comment]
@DailyCovidCases thanks for replying.   I see that you have deleted the comments in issue #1 asking for it to be closed -- that is good.  

@FedeGueli wrote down some rules for the sars-cov-2-variants/lineage-proposals repo, and in particular about when it is OK to open issues in this repo: https://github.com/sars-cov-2-variants/lineage-proposals/issues/1833

I hope that after reading those rules, you can see why it was a problem to open this issue.  Can you confirm that for us, by explaining what was the problem about opening this issue?  And can you explain how you will avoid that problem in the future?

**Comment by DailyCovidCases** [comment]
Yes, I saw the green light "To be proposed" but it doesn't mean I can propose it immediately. In addition I wrote the title in this issue incorrectly.

**Comment by AngieHinrichs** [comment]
Sounds good to me @DailyCovidCases.  I'm glad we're communicating now.  @ryhisner are you willing to give DailyCovidCases another chance?

**Comment by ryhisner** [comment]
Yeah, sounds good to me.

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_14262_fcfa80.json?c=pango_lineage&f_userOrOld=uploaded%20sample)
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_118f5_fceae0.json?c=pango_lineage&f_userOrOld=uploaded%20sample)
![Screenshot (225)](https://github.com/user-attachments/assets/2924eedb-0da9-4334-8f1d-68f0b791f108)
![Screenshot (226)](https://github.com/user-attachments/assets/7e89df47-329c-437e-a0b1-785a37fc1094)

**Comment by FedeGueli** [comment]
it should  be 52  (13 after Aug 1) and 36 ( 5 after Aug 1)

**Comment by DailyCovidCases** [comment]
Now 83/35 seqs on Covspectrum

**Comment by FedeGueli** [comment]
only three seqs from September 1 ahead but from three continents so it is ok to keep this open

**Comment by FedeGueli** [comment]
You should change the title KP.2.2.2
