### ISSUE TITLE
KP.2.3(no 31del)+S:T572I(307 seqs, >10 places ) 

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2722]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1735
There is another T572I branch under KP.2.3 besides KP.2.3.6. Unlike the FULL QUAD KP.2.3.6, this one emerges before the S:S31del(which is in most but not all KP.2.3s)

KP.2.3(no 31del)+C23277T(S:T572I)
GISAID query: C22000A, C23277T, G25593T, -del21653, -28714
No. of seqs: 115(Australia 1 Canada 11 UK 2 Singapore 2  Ireland 1  Israel 9 New Zealand 7 Spain 1 USA 80(2 from France))

First: EPI_ISL_19233571, 2024-4-16, USA
Latest: EPI_ISL_19313288, 2024-7-29, Canada

I checked the KP.2.3+S:T572I branch, it seems that the largest ones (C7420T branch and C19089T, C23533T branch ) do not have S:S31del. So we shall assume T572I comes first after direct no-31-del KP.2.3. 
Designation can safely starts at S:T572I. 

[usher](https://nextstrain.org/fetch//raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/kp_2_3_t572i.json?label=id:node_5522990)
![image](https://github.com/user-attachments/assets/3fa49619-cfdd-4e0f-b552-bd40add51b4f)

**Comment by aviczhl2** [comment]
132, Italy, UAE

**Comment by FedeGueli** [comment]
new query : C22000A, C23277T, G25593T, -del21653, -28714

**Comment by aviczhl2** [comment]
194, Sweden

**Comment by aviczhl2** [comment]
209, Mexico

**Comment by aviczhl2** [comment]
220, China

**Comment by aviczhl2** [comment]
242, Slovenia, Luxembourg

**Comment by FedeGueli** [comment]
246 Australia

**Comment by DailyCovidCases** [comment]
Now 262 seqs
Tracked in [issue2722](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nucMutations=C22000A%2CC23277T%2CG25593T%2CC28714C&nextcladePangoLineage=KP.2.3*&)
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_181e0_e1ee0.json?f_userOrOld=uploaded%20sample)
![Screenshot (231)](https://github.com/user-attachments/assets/c51782e5-460e-4e66-835a-bd41c0e4aa97)
@corneliusroemer Is this branch worth a designation?

**Comment by aviczhl2** [comment]
261 ,greece

**Comment by Over-There-Is** [comment]
284

**Comment by FedeGueli** [comment]
15/289 from september likely dying off
