### ISSUE TITLE
LB.1.3+S:K182R( 26 seqs, 10 countries, 4 with S:N148T) 

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2723]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1717

LB.1.3+C9163T, A22107G(S:K182R)

GISAID query: C18131T,C9163T,A22107G,-16386
GISAID query for S:N148T sub-branch: G2305T, C17502T,T3565C
No. of seqs: 26(Canada 3 Denmark 1 UK 1 Netherlands 3 France 4 Germany 1  Israel 5 Italy 2 USA 5 Belgium 1)

First: EPI_ISL_19205794, 2024-5-28, France
Latest: EPI_ISL_19318624, 2024-7-31, USA

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/lb_1_3_k182r.json?label=id:node_5710847)
![image](https://github.com/user-attachments/assets/56d908e0-60dc-4bf4-80b0-253939c06f22)

**Comment by FedeGueli** [comment]
Designated LB.1.3.3 via https://github.com/cov-lineages/pango-designation/commit/1d153da0d1cd2fd514eaf0d3586dfbe353037b15
