### ISSUE TITLE
KP.3.1.1+S:R346T (248 seqs, >10 places, 18 with Orf9b:I5T, 10 with S:Q183H)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2729]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1809

Besides the main branch, there's a lot of separate emergences and seqs placed on artifact reversion branches.

My query excludes current separate emergences but do not exclude seqs on artifact reversion branches, there may be more -s.

GISAID query: G22599C, A13121T, C12616T, C23039G, -7086, -9778, -16224, -28936,-6536,-8326,-15202,-G2890A, -27804, -29716,-17613,-T28978A,-C13821A,-T6918G,-G28380A,-T9697C,-C10432T,-C29011T,-A13685G,-T27484C,-C10681T,-21255,-C15720T,-T15750C,-C1150T,-A6391G,-T8176C,-C11152T,-A9883G,-C14805T,-23635,-16332, -29485, -6148, -C1441T,-8683,-18674, -17751, -21658,-25887,-18555,-11345,-22107,-C2110A ( may include more -s)
GISAID query for Orf9b:I5T branch: T28297C, G22599C, C23039G,A13121T
Query for S:Q183H branch: : C12616T, C6525T, G22111T
No. of seqs: 23(Canada 1 Denmark 1 Germany 1 Netherlands 2 Spain 6 Sweden 1  USA 10(2 from Iceland) UK 1)

First: EPI_ISL_19281805, 2024-6-14, Spain
Latest: EPI_ISL_19320724, 2024-8-1, USA

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/kp_3_1_1_r346t.json?label=id:node_5487594)
![image](https://github.com/user-attachments/assets/49a8a447-e668-41cd-bc22-b163ed6dfb61)

**Comment by FedeGueli** [comment]
32

**Comment by aviczhl2** [comment]
35, France

**Comment by FedeGueli** [comment]
One sample in the Orf3a:P240H branch has gotS:V622del ( France via GBW),
Another branch is defined by Orf9b:I5T

<img width="1157" alt="Screenshot 2024-08-19 alle 01 03 42" src="https://github.com/user-attachments/assets/2c21e71c-8898-4365-b244-b572896e8fac">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_433fe_279b00.json?label=id:node_7035691

**Comment by aviczhl2** [comment]
+7, but total is 39 after include more -s.

**Comment by FedeGueli** [comment]
Thank you, impressive acceleration. it could be that r346T really works with 31del despite 493E , it would be a thing.

**Comment by aviczhl2** [comment]
+8 in the past day.

**Comment by aviczhl2** [comment]
73, Belgium, Japan

**Comment by aviczhl2** [comment]
110, Romania, South Korea, Portugal, Brazil

**Comment by FedeGueli** [comment]
> 110, Romania, South Korea, Portugal, Brazil

i think a some more -s has to be added:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_6032_561430.json?f_userOrOld=uploaded%20sample&label=id:node_7011297
<img width="1166" alt="Screenshot 2024-09-14 alle 12 20 27" src="https://github.com/user-attachments/assets/025b355c-446c-498c-91f8-6d273c54c111">
Don't care about the bottom branch is one Kp.3.1.1 tree misplaced under JN.1.11 already highlighted to @AngieHinrichs 

-s to be added: -T28978A,-C13821A,-T6918G,-G28380A,-T9697C

Resulting in G22599C, A13121T, C12616T, C23039G, -7086, -9778, -16224, -28936,-6536,-8326,-15202,-G2890A, -27804, -29716,-17613,-T28978A,-C13821A,-T6918G,-G28380A,-T9697C

giving 102 seqs

**Comment by aviczhl2** [comment]
> > 110, Romania, South Korea, Portugal, Brazil
> 
> i think a some more -s has to be added: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_6032_561430.json?f_userOrOld=uploaded%20sample&label=id:node_7011297 <img alt="Screenshot 2024-09-14 alle 12 20 27" width="1166" src="https://private-user-images.githubusercontent.com/87669813/367508133-025b355c-446c-498c-91f8-6d273c54c111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2Mzg0NTcsIm5iZiI6MTcyNjYzODE1NywicGF0aCI6Ii84NzY2OTgxMy8zNjc1MDgxMzMtMDI1YjM1NWMtNDQ2Yy00OThjLTkxZjgtNmQyNzNjNTRjMTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA1NDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZGJmZDY4NmUwN2MzMDBhYjE4NzNmNTk0NTg0ZGQ0ZDJiNDYxN2U5ZDNmZjUyOGQ4ZTRmNDlmMjZiYjY3YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sMsGkrM7act2ssFfTwsvF3Gd3vU6XoNllYbDPiS2Sbw"> Don't care about the bottom branch is one Kp.3.1.1 tree misplaced under JN.1.11 already highlighted to @AngieHinrichs
> 
> -s to be added: -T28978A,-C13821A,-T6918G,-G28380A,-T9697C
> 
> Resulting in G22599C, A13121T, C12616T, C23039G, -7086, -9778, -16224, -28936,-6536,-8326,-15202,-G2890A, -27804, -29716,-17613,-T28978A,-C13821A,-T6918G,-G28380A,-T9697C
> 
> giving 102 seqs

After adding those -s now it yields 114 seqs.

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_31216_12d680.json?c=pango_lineage&f_userOrOld=uploaded%20sample)
@corneliusroemer Is this branch worth a designation?

**Comment by FedeGueli** [comment]
> Tree now: [usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_31216_12d680.json?c=pango_lineage&f_userOrOld=uploaded%20sample) ![Screenshot (232)](https://private-user-images.githubusercontent.com/92421581/369810111-a2dc2551-f32e-4039-a353-03e3b0c66932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODU1MjcsIm5iZiI6MTcyNzA4NTIyNywicGF0aCI6Ii85MjQyMTU4MS8zNjk4MTAxMTEtYTJkYzI1NTEtZjMyZS00MDM5LWEzNTMtMDNlM2IwYzY2OTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA5NTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNjc1NTY1N2ZmN2Q1NDNiZjZlMDZmMjM3MWIxODVlMzMyZjVlNzlkOWRmMTkxMGU5Y2NlZDczMTEzOGFiYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pwwV6eH7ACqYoik-MzjMUfvJOcGDKpskBSn32nldBK0) @corneliusroemer Is this branch worth a designation?

Let me check very likely the query catches many unrelated samples with 346T

**Comment by FedeGueli** [comment]
to add: -C10432T,-C29011T,-A13685G,-C15720T,-T27484C,-C10681T,-G21255A,-G21255A,-C15720T,-T15750C,

>> new query: G22599C, A13121T, C12616T, C23039G, -7086, -9778, -16224, -28936,-6536,-8326,-15202,-G2890A, -27804, -29716,-17613,-T28978A,-C13821A,-T6918G,-G28380A,-T9697C,-C10432T,-C29011T,-A13685G,-C15720T,-T27484C,-C10681T,-G21255A,-G21255A,-C15720T,-T15750C,

Finds 120 but still several singlets unrelalted caught by it

**Comment by FedeGueli** [comment]
133 now i ve to check i supsect many more -s to be added

**Comment by aviczhl2** [comment]
> 133 now i ve to check i suspect many more -s to be added
> 
> new -s: -A6391G,-A29716T,-T8176C,-C11152T,-A9883G,-C14805T
> 
> New query: G22599C, A13121T, C12616T, C23039G, -7086, -9778, -16224, -28936,-6536,-8326,-15202,-G2890A, -27804, -29716,-17613,-T28978A,-C13821A,-T6918G,-G28380A,-T9697C,-C10432T,-C29011T,-A13685G,-C15720T,-T27484C,-C10681T,-G21255A,-G21255A,-C15720T,-T15750C,-A29716T,-C1150T -A6391G,-A29716T,-T8176C,-C11152T,-A9883G,-C14805T finds 130
> 
> still a dozen of unrelated singlet included

Updated. Now 141 seqs with 8 Orf9b:I5T

**Comment by FedeGueli** [comment]
New -s needed: -C7732T,-A29716T,-T9028C,-A6391G,-G21255A

New Query: G22599C, A13121T, C12616T, C23039G, -7086, -9778, -16224, -28936,-6536,-8326,-15202,-G2890A, -27804, -29716,-17613,-T28978A,-C13821A,-T6918G,-G28380A,-T9697C,-C10432T,-C29011T,-A13685G,-C15720T,-T27484C,-C10681T,-G21255A,-G21255A,-C15720T,-T15750C,-A29716T,-C1150T -A6391G,-A29716T,-T8176C,-C11152T,-A9883G,-C14805T , -C7732T,-A29716T,-T9028C,-A6391G,-G21255A

finds 132

**Comment by aviczhl2** [comment]
176/10 now

**Comment by FedeGueli** [comment]
> 176/10 now

with query checked?

**Comment by aviczhl2** [comment]
> > 176/10 now
> 
> with query checked?

No. Maybe more -s is needed.

**Comment by xz-keg** [comment]
Add some more -s, toll of the main branch becomes 153

**Comment by Over-There-Is** [comment]
there is a Q183H branch now.

**Comment by FedeGueli** [comment]
>Q183H branch

Thx for spotting it is a cluster from Berlin but already found in Spain and Italy recently.
Query for it :  C12616T, C6525T, G22111T
An easy one finally for this issue!

**Comment by xz-keg** [comment]
227 now.

**Comment by xz-keg** [comment]
248, Finland

**Comment by xz-keg** [comment]
designated MC.19

**Comment by FedeGueli** [comment]
> designated MC.19 

via https://github.com/cov-lineages/pango-designation/commit/b1e238c06bee3b81c2215478df708a0db6ca1e05#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1289

(Finally we can drop the query update!)

**Comment by FedeGueli** [comment]
11 for the 183H branch
