### ISSUE TITLE
Finnish/Estonian 21J lineage (20%) with S:411S (part of ORF1a:261N branch)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#273]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of #268 (21J with ORF1a:261N) need to read with this comment https://github.com/cov-lineages/pango-designation/issues/268#issuecomment-946881724
Earliest sequence: May to July 2021 in Finland
Most recent sequence: Current
Countries circulating: ~20% in Finland and Estonia

Lineage deriving from Delta 21J branch with ORF1a:261N with extra mut S:411S

![image](https://user-images.githubusercontent.com/25161793/138004629-fd5d8038-cf7f-473e-8dc7-6d227bf9ed36.png)

https://nextstrain.org/groups/neherlab/ncov/finland?branchLabel=aa&c=gt-S_411&gmin=15&label=spike_mutations:I95T&m=div

![image](https://user-images.githubusercontent.com/25161793/138004452-086182a5-d7a9-441d-b63d-80f36096b87d.png)

![image](https://user-images.githubusercontent.com/25161793/138004456-93164671-2c1a-49bf-b3ce-3a043dc6103c.png)

https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A411S%2CORF1a%3A261N&pangoLineage=B.1.617.2*

Country | Total Variant Sequences | First seq. found at | Last seq. found at
-- | -- | -- | --
Finland | 935 | 2021-25 | 2021-37
Germany | 3 | 2021-27 | 2021-37
Estonia | 178 | 2021-28 | 2021-37
United States | 5 | 2021-29 | 2021-37
Sweden | 661 | 2021-29 | 2021-39
Denmark | 7 | 2021-30 | 2021-33
United Kingdom | 5 | 2021-30 | 2021-40
New Zealand | 1 | 2021-30 | 2021-30
Norway | 11 | 2021-31 | 2021-34
Switzerland | 7 | 2021-33 | 2021-38
France | 12 | 2021-34 | 2021-38
Iceland | 1 | 2021-34 | 2021-34
Slovenia | 1 | 2021-34 | 2021-34
Czechia | 3 | 2021-34 | 2021-35
Turkey | 1 | 2021-36 | 2021-36
Lithuania | 2 | 2021-37 | 2021-38

AY.N.x (where N is chosen together with #267 and #268)

**Comment by FedeGueli** [comment]
The parental lineage has been designated AY.122 in #320 .
Pls @corneliusroemer evaluate if closing this or keeoing it monitored

**Comment by chrisruis** [comment]
Thanks @corneliusroemer This clade is a sublineage of AY.122 and increased as a proportion of total AY.122 in both Finland and Estonia. It may now be declining but is still responsible for ~30% of AY.122 sequences in these countries in the most recent weeks with data. We've therefore added this as AY.122.2 in [v1.2.109](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.109) to start on the branch with G22793T (S:A411S)
