### ISSUE TITLE
KP.2/KP.3.2.3 recombinant. most have additional S:S31F (46 seqs, 12 countries)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2731]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1650 and https://github.com/sars-cov-2-variants/lineage-proposals/issues/1576

There seems to be a new S:S31F branch that emerges from a recombinant of KP.3.2 and JN.1*.
 It is better explained by recombinant of KP.2 and KP.3.2.3 to reduce number of private mutations.
All seqs but the 1st one have S:S31F. 

KP.2--KP.3.2.3

Breakpoint between 11519 and 12438

Additional mutations: T772C, ,C7998T,C12439T
Orf1a:S2578F

T772C from a KP.2 branch
A2611C>A reversion of the defining of KP.3.2 (edited)
C12439T from a KP.3.2.3 branch 

C7998T is privat mutation

GISAID query: T772C, G17334, T25510C
No. of seqs: 34(Australia 1 Canada 1 Denmark 1 UK 9 France 5 Ireland 3 Luxembourg 1 Spain 12 USA 1(from Italy))

First:EPI_ISL_19153071, USA from Italy, 2024-4-29
Latest: EPI_ISL_19309169, Spain, 2024-7-26

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/kp_2_kp_3_2_3_recomb.json?f_userOrOld=uploaded%20sample&label=id:node_5504566)

![image](https://github.com/user-attachments/assets/c5cfd091-459b-4166-80b8-6c036c383fe8)

**Comment by aviczhl2** [comment]
39, Netherlands

**Comment by DailyCovidCases** [comment]
This branch has slowed down a lot. You can close this.

**Comment by FedeGueli** [comment]
Only 5 in august likely it could be closed , @aviczhl2

**Comment by aviczhl2** [comment]
+1 Uraguay

**Comment by FedeGueli** [comment]
very few from August likely dying off.

**Comment by DailyCovidCases** [comment]
Pretty much slowing down now

**Comment by FedeGueli** [comment]
yes @xz-keg  close this please
