### ISSUE TITLE
KP.2.3 + S:S31del branch with N:H145Y + S:K679R + ORF1a:T2016K (239 in 12 countries) + Branch with S:G184S (14) and a Branch with ORF1a:S944L + S:E1202G (26)

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2732]
from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/1603
![image](https://github.com/user-attachments/assets/841ee3cc-f216-487f-bcd9-ad1ccb1c7ce4)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43792_cbe980.json?f_userOrOld=uploaded%20sample

Query: C6312A, T19449C, A23598G, C28706T

Query with S:G184S: G22112A,C28706T, C6312A

Query with S:E1202G and ORF1a:S944L: C3096T, A25167G, C28706T

**Comment by Over-There-Is** [comment]
There is a subbranch with S:G184S. I think it's also worth tracking.

**Comment by FedeGueli** [comment]
> There is a subbranch with S:G184S. I think it's also worth tracking.

query: G22112A,C28706T,T3565C
Samples:12

Please @Fearuncle add this to the title ad the man proposal

**Comment by Over-There-Is** [comment]
EPI_ISL_19280116 imported from Peru

**Comment by Fearuncle** [comment]
9 with ORF1a:S944L + S:E1202G
![image](https://github.com/user-attachments/assets/3f5670bd-e8ad-4c74-b3a0-18ad6a69376e)

**Comment by Fearuncle** [comment]
Passed 200 seq.

**Comment by FedeGueli** [comment]
> 9 with ORF1a:S944L + S:E1202G (C3096T, A25167G, C28706T)

This is a canadian cluster >> scoring high for growth advantage but worth keeping it tracked if it starts emerging elsewhere.
@ryhisner any idea if S:E1202G could mean something? it is the same residue of the double nuc (silent 1201 + 1202K) we saw multiple times

**Comment by ryhisner** [comment]
Fede, you're thinking of S:Q1201K, which often has a silent mutation in S:L1200. But Q1201K also shows up pretty frequently without that second nuc mutation (which creates a suboptimal TRS motif), so I think it must have a function apart from its TRS implications. I don't know what it would be though. I don't think this region is an antibody target, but it's hard to be sure. 
<img width="1140" alt="image" src="https://github.com/user-attachments/assets/afdeeb72-a8aa-472c-8510-09c1dffae03a">

**Comment by FedeGueli** [comment]
> Fede, you're thinking of S:Q1201K, which often has a silent mutation in S:L1200. But Q1201K also shows up pretty frequently without that second nuc mutation (which creates a suboptimal TRS motif), so I think it must have a function apart from its TRS implications. I don't know what it would be though. I don't think this region is an antibody target, but it's hard to be sure. <img alt="image" width="1140" src="https://private-user-images.githubusercontent.com/33738461/365473001-afdeeb72-a8aa-472c-8510-09c1dffae03a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODExNjQsIm5iZiI6MTcyNTg4MDg2NCwicGF0aCI6Ii8zMzczODQ2MS8zNjU0NzMwMDEtYWZkZWViNzItYThhYS00NzJjLTg1MTAtMDljMWRmZmFlMDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDExMjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2N2RlN2M5YTllNzRiOGE2ZGFkYzJjOTM3NzE3MTU4MWM5ZWRhYTUyMTMxNmFhYTJlYzgwYTk1NDlhZTBjMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AWXFEBd09XHxhNR_I-e9VaB95Sot_2D9Exr9D6e99Ew">

Yeah sorry i miss recalled it as 1202 it is obviously 1201! and 1200 as silent. thank you very much!

**Comment by FedeGueli** [comment]
26

**Comment by DailyCovidCases** [comment]
@corneliusroemer 3 weeks without designation now, please designate some variants in https://github.com/cov-lineages/pango-designation/issues

**Comment by FedeGueli** [comment]
> @corneliusroemer 3 weeks without designation now, please designate some variants in https://github.com/cov-lineages/pango-designation/issues

How many times would you post this?

**Comment by FedeGueli** [comment]
It seems dying off to me or at least low priority now that many fast sublineages are popping up

**Comment by xz-keg** [comment]
designated KP.2.3.14

**Comment by FedeGueli** [comment]
> designated KP.2.3.14
via
https://github.com/cov-lineages/pango-designation/commit/0c6652152ec349f92de8f6dfcd0f6d62a5c919a2
