### ISSUE TITLE
 JN.1.16.1  (Usher places it under LR.1) plus S:T22N, S31P, K182R, R190S, K444R + ORF9b:I5T + ORF1a:S2535L  (7 seq, 6 countries; Aug 13)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2733]
**Description**
**Sub-lineage of:** JN.1.16.1
**Earliest sequence:** 2024-6-24, Senegal
**Most recent sequence:** 2024-7-27, Australia, Western Australia — EPI_ISL_19333883
**Continents circulating:** Africa (2), Europe (2), North America (1), Oceania (1)
**Countries circulating:** Senegal (2), Australia (1), Canada (1), England (1), France (1), Unknown Travel sequence (1)
**Number of Sequences:** 6-7
**GISAID Nucleotide Query:** C5239T, C7869T, C8818T, G12892A, T16600C
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & [4-of: C5239T, C7869T, C8818T, G12892A, T16600C]
**Substitutions on top of JN.1.16.1:**
**Spike:** T22N, S31P, K182R, R190S, K444R
**ORF1a:** S2535L
**ORF9b:** I5T
**Nucleotide:** C5239T, C7869T, C8818T, G12892A, T16600C, C21627A, T21653C, A22107G, G22132T, C22792T, A22893G, C22993T, T28297C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1.16.1_T22N_S31P_K182R_R190S_K444R.json?c=gt-S_444&gmax=25384&gmin=21563&label=id:node_6967258
<img width="1480" alt="image" src="https://github.com/user-attachments/assets/ed267647-bdb4-4d70-bf27-820721072ea5">

**Evidence**
Okay, so this has spread internationally. Putting together a permanent Usher tree link shortly, to be posted above. 

Hoping that the GBW pooled sequence is soon matched with an individual sequence so that we know what country that travel sequence originated from.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19273031, EPI_ISL_19273041, EPI_ISL_19293986,
EPI_ISL_19305721, EPI_ISL_19324095, EPI_ISL_19331105,
EPI_ISL_19333883
</details>

**Comment by corneliusroemer** [comment]
Ah, the `A21137G (ORF1b:K2557R)` is not actually present at all - pretty clear Usher tree building error it seems @AngieHinrichs 

<img width="2511" alt="Brave Browser 2024-08-15 14 43 00" src="https://github.com/user-attachments/assets/85549ebf-c8e9-4503-9353-3a3061e49698">

**Comment by corneliusroemer** [comment]
Didn't find any other reasonable ancestor, so will designate as JN.1.16.1 sublineage (it's most likely homoplasy but in absence of evidence let's keep the naming simpler)

**Comment by corneliusroemer** [comment]
Also in Egypt now: hCoV-19/Egypt/CPHL-EGY24173/2024|EPI_ISL_19334646|2024-06-26 missing from Usher due to low quality I think.

**Comment by FedeGueli** [comment]
Designated LF.7 via https://github.com/cov-lineages/pango-designation/commit/43d7733254e29c91714acb4ed0ea2003b2873551

**Comment by corneliusroemer** [comment]
I just plugged the private mutations into SMDP and it has a little bit of a molnupiravir signature, on the lower end.

https://eringill.shinyapps.io/covid_mutation_distributions/

<img width="2277" alt="Google Chrome 2024-08-15 18 35 53" src="https://github.com/user-attachments/assets/8fb51896-6408-4bfd-8319-021311f3c32c">

<img width="2509" alt="Google Chrome 2024-08-15 18 35 46" src="https://github.com/user-attachments/assets/91575a8d-f8b5-4963-8bc7-f002bb7c9145">

Not sure how to interpret movbranch results:

<img width="1240" alt="Google Chrome 2024-08-15 18 39 23" src="https://github.com/user-attachments/assets/c415d963-a70f-4e1b-b801-b5f4848d605e">

https://movbranchapp.streamlit.app/

**Comment by ryhisner** [comment]
Not impossible there was MOV involvement, but the relative lack of G->A mutations makes it doubtful I think. This may have been circulating in some part of Africa for a bit, though the five spike AA mutations suggest a probable (relatively short) chronic-infection origin.

**Comment by FedeGueli** [comment]
please close it is LF.7

**Comment by HynnSpylor** [comment]
Notice that the two seqs from Egypt get S:D614G->S. Another attempt to change the basic S:D614G
