### ISSUE TITLE
KP.2+Orf1a:P1803L, S:K558N, S:F32del(62 seqs, 14 countries)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2736]
From branch 4 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1768

KP.2+C5673T(Orf1a:P1803L)+C14220T+C3619T, C18657T,G23236T, C26936T, del21656_21658(S:K558N, F32del)

GISAID query: del21656_21658,C26936T,G23236T
No. of seqs: 26(Canada 6 France 4 Israel 1 Japan 2 Netherlands 2 Singapore 1 South Korea 1 Spain 1 Sweden 2 USA 6(1 from Italy))

First: EPI_ISL_19265819. USA, 2024-5-17
Latest: EPI_ISL_19334656, Canada, 2024-7-26

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/kp_2_k558n_f32-.json?f_userOrOld=uploaded%20sample&label=id:node_5527184)
![image](https://github.com/user-attachments/assets/5cbad506-b1af-4ac2-b2fa-9930c8ee646e)

**Comment by aviczhl2** [comment]
+1 UK

**Comment by FedeGueli** [comment]
+3 Poland this is going well.

**Comment by xz-keg** [comment]
+1 Australia

**Comment by DailyCovidCases** [comment]
@corneliusroemer Is this branch worth a designation?

**Comment by xz-keg** [comment]
Designated KP.2.25.2

**Comment by FedeGueli** [comment]
Via https://github.com/cov-lineages/pango-designation/commit/a3d38ca258578e6487aebe3e976302f258aeaeef

**Comment by FedeGueli** [comment]
Thx i didnt ever realized it was a sibling of the 30K branch
