### ISSUE TITLE
JN.1.4+S:S31del, S:R346T, Orf7a:Q94H (54 seqs, 3 countries)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2739]
From branch 9 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1502

JN.1.4+T18453C+del21653_21655,G22599C,A27675C(S:S31del, S:R346T, Orf7a:Q94H)

I cannot decide the order. 

GISAID query: del21653_21655, A27675C, T18453C (42 seqs)
GISAID supplementary query: A27675C, T18453C, G22599C, -del21653 (3 seqs)

No. of seqs: 45( Guatemala 38 USA 6(3 from Guatemala) Canada 1)

First: EPI_ISL_18962170, USA, 2024-2-21
Latest: EPI_ISL_19313808, USA from Guatemala, 2024-7-25

Usher places this on a Flip-flop branch under the A29799G which this branch doesn't really have.

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_4_r346t_s31-.json?label=id:node_7171665)

![image](https://github.com/user-attachments/assets/4253dd70-f94d-4230-a169-77488e9b9593)

**Comment by DailyCovidCases** [comment]
This branch has slowed down a lot. I think you can close this issue @aviczhl2

**Comment by DailyCovidCases** [comment]
This branch has slowed down a lot. I think you can close this issue @xz-keg

**Comment by FedeGueli** [comment]
Likely circualting locally in Guatemala

**Comment by DailyCovidCases** [comment]
Pretty much slowing down now

**Comment by DailyCovidCases** [comment]
Slowing down a lot now, please close it @xz-keg

**Comment by xz-keg** [comment]
No more seqs

**Comment by Over-There-Is** [comment]
there are also lots of JN.1.4+S:S31-, R346T sequence without Orf7a:Q94H.
