### ISSUE TITLE
Wrong assignment of AY.4.2

### ISSUE THREAD

**Issue by insapathogenomics** [cov-lineages/pango-designation#274]
After the release of the new pango-designation version, we have reclassified our whole genome dataset.

10 sequences were assigned as AY.4.2, including 9 correctly assigned sequences (as we expected based on previous screening of mutations), and one wrongly classified sequence (Portugal/PT12517/2021 - EPI_ISL_3204419).

Indeed, although this sequence contains the Spike mutation A222V, it does not cluster together with the other AY.4.2 sequences, neither does it contain any of the other AY.4.2 defining mutations (S:Y145H, T17040C or C25614T).
Since the mutation A222V has appeared multiple times independently within Delta, this could be an alert for potential further misclassifications.

**Comment by rmcolq** [comment]
I think it sounds like your install hasn't pulled in the new scorpio changes properly. Perhaps you updated with `pangolin --update-data` and not `pangolin --update`? 
When I run that sequence through scorpio, I get
```
query,constellations,mrca_lineage,ref_count,alt_count,ambig_count,other_count,rule_count,support,conflict,constellation_name
Portugal/PT12517/2021,Delta (AY.4-like),AY.4,1,44,2,0,5,0.936200,0.021300,Delta (AY.4-like)
```
