### ISSUE TITLE
KP.1.1+S:S71Y+S:S31del with A24819G branch (59 seqs, 31 with Orf1ab:T6777I)

### ISSUE THREAD

**Issue by DailyCovidCases** [cov-lineages/pango-designation#2742]
From branch 34 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1502
KP.1.1+S:S71Y,S:S31del, 
Query: A24819G, del21770_21775, del21653_21655
No of seqs: 59 
First: EPI_ISL_19095593, 2024-4-1
Latest: EPI_ISL_19333867, 2024-8-2
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2c2d1_5fe280.json?f_userOrOld=uploaded%20sample)
![Screenshot (182)](https://github.com/user-attachments/assets/d01a13d3-c6a1-47ff-8715-cacdaf96c524)

**Comment by FedeGueli** [comment]
This was pending to.me is LP.2 that had S:31del in most of samples from the start. Ping @corneliusroemer .

@DailyCovidCases before proposing you must ask the consent of the author.

**Comment by aviczhl2** [comment]
This proposal is inaccurate. Re-proposed in #2747
