### ISSUE TITLE
KP.3.1 subbranch with S:N>K679R(203 seqs, 20 regions, mainly in Spain) and further S:L176F(41, 8 regions)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2743]
Transferred from sars-cov-2-variants/lineage-proposals#1802

Found with @aviczhl2 's phylogenic tree analysis tool.
Spotted first by @aviczhl2 .

KP.3.1> A1620G(Orf1a:E452G), del29728-29776(#2646)> T2593C> C8616T(Orf1a:A2784V)> C14216T(Orf1b:T250I), A23598G(S:K679R)> C22088T(S:L176F)
Query: C14216T, A23598G, -G932A
Query for S:L176F branch: C14216T, C22088T, A23598G
This branch is misplaced on a T29728G> C14216T, A23598G> G29728T flip-flop branch yet due to the deletion.

Earliest sequence: 04-21 Madrid, Spain EPI_ISL_19164708
Latest sequence: 08-12 Denmark EPI_ISL_19348042
Regions detected: 
Spain 54(including 1 from Canary Islands), UK 8, France 6, Sweden 6, Denmark 4, Ireland 4, Italy 2, Portugal 2, Finland 1, Greece 1, Netherlands 1, Luxembourg 1;
US 8(1 from Greece, 1 from Spain), Canada 1;
Israel 1.

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3044b_6cd8c0.json?c=country&label=id:node_7028471
![image](https://github.com/user-attachments/assets/27a5def4-268a-4399-8cb4-eceee81378ec)

<details> <summary> Sequences: </summary>

EPI_ISL_19164708, EPI_ISL_19164712, EPI_ISL_19176965,
EPI_ISL_19178589, EPI_ISL_19179515, EPI_ISL_19185426,
EPI_ISL_19186676, EPI_ISL_19189621, EPI_ISL_19194760,
EPI_ISL_19194769, EPI_ISL_19195261, EPI_ISL_19197928,
EPI_ISL_19201438, EPI_ISL_19201738, EPI_ISL_19214624,
EPI_ISL_19215264, EPI_ISL_19215276, EPI_ISL_19216662,
EPI_ISL_19218924, EPI_ISL_19219465, EPI_ISL_19220641,
EPI_ISL_19221168, EPI_ISL_19221172, EPI_ISL_19221310,
EPI_ISL_19221771, EPI_ISL_19222000, EPI_ISL_19225530,
EPI_ISL_19225568, EPI_ISL_19225573, EPI_ISL_19229220,
EPI_ISL_19229223, EPI_ISL_19231626, EPI_ISL_19232532-19232533,
EPI_ISL_19232597, EPI_ISL_19235907, EPI_ISL_19252937,
EPI_ISL_19258573, EPI_ISL_19261329, EPI_ISL_19261586,
EPI_ISL_19263174, EPI_ISL_19263232, EPI_ISL_19263264,
EPI_ISL_19263302, EPI_ISL_19263321, EPI_ISL_19264890,
EPI_ISL_19265498, EPI_ISL_19265509, EPI_ISL_19266060,
EPI_ISL_19267058, EPI_ISL_19267060, EPI_ISL_19270338,
EPI_ISL_19271730, EPI_ISL_19273215, EPI_ISL_19276263,
EPI_ISL_19276287, EPI_ISL_19277304, EPI_ISL_19280649,
EPI_ISL_19280673, EPI_ISL_19280872, EPI_ISL_19281671,
EPI_ISL_19287047, EPI_ISL_19289400, EPI_ISL_19290827,
EPI_ISL_19291541, EPI_ISL_19292706, EPI_ISL_19293241,
EPI_ISL_19296711, EPI_ISL_19296910, EPI_ISL_19300146,
EPI_ISL_19305441, EPI_ISL_19305699, EPI_ISL_19307088,
EPI_ISL_19309647, EPI_ISL_19310720, EPI_ISL_19311299,
EPI_ISL_19312405, EPI_ISL_19312486, EPI_ISL_19312559,
EPI_ISL_19313452, EPI_ISL_19319581, EPI_ISL_19322327,
EPI_ISL_19322362, EPI_ISL_19322545, EPI_ISL_19323296,
EPI_ISL_19323471, EPI_ISL_19326372, EPI_ISL_19327347,
EPI_ISL_19331142, EPI_ISL_19331714, EPI_ISL_19332615,
EPI_ISL_19332675, EPI_ISL_19332799, EPI_ISL_19333749,
EPI_ISL_19333767, EPI_ISL_19335088, EPI_ISL_19338465,
EPI_ISL_19338542, EPI_ISL_19341069, EPI_ISL_19348042
</details>

**Comment by aviczhl2** [comment]
This branch is sub-branch of https://github.com/cov-lineages/pango-designation/issues/2646 so it has the del29728_29776 large deletion thing.

**Comment by Over-There-Is** [comment]
> This branch is sub-branch of #2646 so it has the del29728_29776 large deletion thing.

so T29728G is an artefact.

**Comment by Over-There-Is** [comment]
Poland

**Comment by Over-There-Is** [comment]
US+20

**Comment by DailyCovidCases** [comment]
Now 171/32 seqs:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_43787_12af0.json?f_userOrOld=uploaded%20sample)
![Screenshot (247)](https://github.com/user-attachments/assets/f1f4e17f-649c-49df-854b-8ffbd8524e20)

**Comment by FedeGueli** [comment]
8 in September from 5 different countries

**Comment by DailyCovidCases** [comment]
ping @corneliusroemer

**Comment by Over-There-Is** [comment]
Costa Rica, Slovenia

**Comment by DailyCovidCases** [comment]
@corneliusroemer This branch is worth designation now

**Comment by FedeGueli** [comment]
Likely dead

**Comment by DailyCovidCases** [comment]
Dead close it please @Over-There-Is

**Comment by FedeGueli** [comment]
Likely dead

**Comment by DailyCovidCases** [comment]
@corneliusroemer This branch is worth a designation now

**Comment by xz-keg** [comment]
designated NR.1

**Comment by FedeGueli** [comment]
Designated NR.1 Via https://github.com/cov-lineages/pango-designation/commit/5872a5a02c2723909dfb5cf8b211cbf485b552fa#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1326
