### ISSUE TITLE
KP.3.3 + S:I844V has spread globally from Australia ( 236 Samples, 14 countries)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2744]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1674
Original proposal
I have noticed a lineage circulating in Australia that has been sampled in 4 continents.
For sure it won't be fast but interesting to track S:I844V mutation that should be close the fusion peptide.
Defining : KP.3.3 > S:I844V (A24092G )
Query: A24092G,C25006T,T3565C
Samples: 144
First collected on 2024-04-08 in Qld Australia
Countries:  12 countries
Tree:
 <img width="1179" alt="Screenshot 2024-08-23 alle 00 54 13" src="https://github.com/user-attachments/assets/10718836-20d5-42ab-aa33-b31fddc1600c">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3457f_7c1650.json?f_userOrOld=uploaded%20sample&label=id:node_7019508

 
IDs: 
EPI_ISL_19069391, EPI_ISL_19122434, EPI_ISL_19122480,
EPI_ISL_19122548-19122549, EPI_ISL_19145755, EPI_ISL_19150394,
EPI_ISL_19183843, EPI_ISL_19188044, EPI_ISL_19189289,
EPI_ISL_19192870, EPI_ISL_19199086, EPI_ISL_19203036,
EPI_ISL_19203071, EPI_ISL_19203093, EPI_ISL_19203130,
EPI_ISL_19208145, EPI_ISL_19208244, EPI_ISL_19213524,
EPI_ISL_19213780, EPI_ISL_19214041, EPI_ISL_19223298,
EPI_ISL_19223643, EPI_ISL_19226556, EPI_ISL_19226562,
EPI_ISL_19226784-19226785, EPI_ISL_19226791, EPI_ISL_19226800,
EPI_ISL_19226804, EPI_ISL_19226825, EPI_ISL_19228576,
EPI_ISL_19228989, EPI_ISL_19230952, EPI_ISL_19238816,
EPI_ISL_19242700, EPI_ISL_19242734, EPI_ISL_19244616,
EPI_ISL_19245371, EPI_ISL_19251587, EPI_ISL_19255143,
EPI_ISL_19257379, EPI_ISL_19257523, EPI_ISL_19260080,
EPI_ISL_19261115, EPI_ISL_19261513, EPI_ISL_19264298-19264299,
EPI_ISL_19264303, EPI_ISL_19265595, EPI_ISL_19266420,
EPI_ISL_19266553, EPI_ISL_19266589, EPI_ISL_19269130,
EPI_ISL_19269711, EPI_ISL_19271639, EPI_ISL_19273197,
EPI_ISL_19274371, EPI_ISL_19274532, EPI_ISL_19274534,
EPI_ISL_19274637, EPI_ISL_19274639-19274640, EPI_ISL_19274812,
EPI_ISL_19274867, EPI_ISL_19275136, EPI_ISL_19275141-19275143,
EPI_ISL_19275183, EPI_ISL_19277250, EPI_ISL_19281013,
EPI_ISL_19281049, EPI_ISL_19282906, EPI_ISL_19282987,
EPI_ISL_19293576, EPI_ISL_19294368, EPI_ISL_19294622,
EPI_ISL_19294811, EPI_ISL_19295409, EPI_ISL_19295411,
EPI_ISL_19295432-19295433, EPI_ISL_19295611, EPI_ISL_19298710,
EPI_ISL_19298713, EPI_ISL_19298769, EPI_ISL_19302162,
EPI_ISL_19303226, EPI_ISL_19303267, EPI_ISL_19304823,
EPI_ISL_19306260, EPI_ISL_19306442, EPI_ISL_19306463,
EPI_ISL_19306490, EPI_ISL_19306497, EPI_ISL_19306554,
EPI_ISL_19306598, EPI_ISL_19306606-19306607, EPI_ISL_19308221-19308223,
EPI_ISL_19311809, EPI_ISL_19312024, EPI_ISL_19312756,
EPI_ISL_19316847, EPI_ISL_19316860, EPI_ISL_19317113,
EPI_ISL_19317476, EPI_ISL_19318353, EPI_ISL_19318749,
EPI_ISL_19318969, EPI_ISL_19321504, EPI_ISL_19322974,
EPI_ISL_19322994, EPI_ISL_19323030, EPI_ISL_19323041,
EPI_ISL_19325710, EPI_ISL_19328818, EPI_ISL_19330844,
EPI_ISL_19330860, EPI_ISL_19330887, EPI_ISL_19330904,
EPI_ISL_19334766, EPI_ISL_19336885, EPI_ISL_19337052,
EPI_ISL_19337142, EPI_ISL_19339501, EPI_ISL_19341192,
EPI_ISL_19341297, EPI_ISL_19343141, EPI_ISL_19345585,
EPI_ISL_19345652, EPI_ISL_19346052, EPI_ISL_19346120-19346121,
EPI_ISL_19346123-19346124, EPI_ISL_19346155, EPI_ISL_19346225,
EPI_ISL_19346228, EPI_ISL_19346231, EPI_ISL_19347550,
EPI_ISL_19347564, EPI_ISL_19347853, EPI_ISL_19348339,
EPI_ISL_19349057

**Comment by DailyCovidCases** [comment]
@corneliusroemer This one should be designated

**Comment by FedeGueli** [comment]
178

**Comment by FedeGueli** [comment]
198, Puerto RIco

**Comment by DailyCovidCases** [comment]
ping @corneliusroemer worth a designation this one

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2f283_93b800.json?c=pango_lineage&f_userOrOld=uploaded%20sample)
![Screenshot (211)](https://github.com/user-attachments/assets/3293a6d7-006b-4723-9276-3dc2536cda51)
ping @corneliusroemer worth a designation this one

**Comment by DailyCovidCases** [comment]
@corneliusroemer 3 weeks without designation now, please designate some variants in https://github.com/cov-lineages/pango-designation/issues

**Comment by DailyCovidCases** [comment]
Now 232 seqs

**Comment by Walde1nsamkeit** [comment]
269
