### ISSUE TITLE
KP.1.1+S:S71Y,S31del or JN.1.11.1/LP.2 recombinant(62 seqs, 14 countries)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2747]
KP.1.1+C21774A,del21653_21655(S:S71Y, S31del)

This is another re-proposal due to inaccurate proposal by DailyCovidCases.

From branch 34 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1502

This can also be explained as JN.1.11.1/LP.2 recombinant with breakpoint between 20595 and 21652 (no private mutation needed)

GISAID query: A24819G, del21770_21775, del21653_21655, -4999
Supplementary Query 1: A24819G, C21774A, -4999
Supplementary Query 2: C1263T,T11551C,C20823T, -C21774A,-del21770
No. of seqs: 33(China 2 Japan 1 Malaysia 5 Singapore 10 South Korea 3 USA 12(2 from India))

First: EPI_ISL_19095593, 2024-4-1,Singapore
Latest: EPI_ISL_19351788, 2024-8-5, Malaysia

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/kp_1_1_s71f_s31-.json?label=id:node_5517269)
![image](https://github.com/user-attachments/assets/af9b046e-ecc8-4b82-bc8b-14287da2ad94)

**Comment by FedeGueli** [comment]
there is a typo it is S:S71Y!

**Comment by Over-There-Is** [comment]
A24819G, del21770_21775, -4999=33
A24819G, C21774A, -4999=8
maybe there are at least 41 sequences.

**Comment by Over-There-Is** [comment]
C1263T,T11551C,C20823T, -C21774A, -del21770_21775=1
this sequence seems belonging to this branch too

**Comment by aviczhl2** [comment]
Add two supplementary queries that capture the Slovenia and Phillipines sample. Total shall be 42.

**Comment by aviczhl2** [comment]
48, UK

**Comment by aviczhl2** [comment]
+1 Netherlands

**Comment by aviczhl2** [comment]
52, Croatia

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_f42c_de240.json?f_userOrOld=uploaded%20sample)
![Screenshot (230)](https://github.com/user-attachments/assets/022362b0-d42b-459b-bbd2-f4802c3a0c78)
@corneliusroemer Is this branch worth a designation?

**Comment by FedeGueli** [comment]
last sampled one montha go worth closing it maybe,

**Comment by aviczhl2** [comment]
+1 Australia

**Comment by FedeGueli** [comment]
this is close to be dead

**Comment by Over-There-Is** [comment]
51+8+1=60

**Comment by xz-keg** [comment]
no new seqs
