### ISSUE TITLE
KP.2.2.1  (S:T22N) S:K97E/478T (12)  /  NY cluster with S:244-247  (15)/ 475V sublineage (9) with further S:ins678THKLL-S:K679E (4)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2748]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1662

S:T22N seems currently as fast as S:S31del globally. This derives by many different combinations so i think it is prudent to say S:T22N is at least not slow for sure in the current landscape.
For sure XEC with the slighty different 22N+59S combo (here we have 22N +59L) is going up rapidly.
We were tracking Kp.2.2 + 22N since some weeks in the secondary repo but now i think it is worth to be proposed here:

Proposal updated as of 10/02

KP.2.2.1 [ = T24364C > S:T22N (C21627A)  >> Orf1b:K2660R ( A21446G)] >> ORF1a:T1794I (C5646T = PLPro_T231I) > C4276T > **S:K97E** (A21851G), **S:K478T** (A22995C REV) 
KP.2.2.1 QUERY: T24364C ,C21627A,-C7594A 
Samples: 165
First sampled on 2024-05-13 in NJ and few days after that in Nepal.
Places : >15 including Nepal and Bhutan

With a **S:K97E/S:K478T** (rev) branch: Now designated **NH.1** via https://github.com/cov-lineages/pango-designation/commit/4744b7ae1eb832bad6b27a1b73baa66ecb928cce   
Query for S:K478T S:K97E branch: C4276T,C5646T,A21851G
Samples: 6 (All GBW)
Places : Netherlands and India

With  a 478Q branch now designated **NH.2** via via https://github.com/cov-lineages/pango-designation/commit/4744b7ae1eb832bad6b27a1b73baa66ecb928cce   
**KP.2.2 > T24364C >  S:T22N (C21627A)  >>**Orf1b:K2660R** (A21446G) then Orf1a:T1794I (C5646T)>>S:T478Q** (A22994C), C24904T
Query for 478Q: T24364C ,A22994C, C24904T
Samples: 2 (Canada)

With a branch with S:A475V  Now designated **NH.3**
Query for 475V:   C22986T,G2591T,T3565C finds 9 samples from India, Australia, Singapore
On october 9 @ryhisner spotted first four recent samples from Singapore belonging to this lineage with  **a large insertion in the FCS :**
**S:ins678THKLL + S:N679E** resulting in a FCS **673SYQTQTTHKLLESRRRARSVASQS691**
<img width="598" alt="Screenshot 2024-10-10 alle 13 29 53" src="https://github.com/user-attachments/assets/ce98d5e2-2036-461a-9e7d-2c5f2e639ee1">
Query for Ins678: C5842T, T26146G or ins23596ACACACAAGCTTCTA, finds 3 (but there are 4) from Singapore
tree for S:ins678:
<img width="1165" alt="Screenshot 2024-10-10 alle 13 39 33" src="https://github.com/user-attachments/assets/a947d56b-a2f2-47d8-a13c-99acf3b8b5d3">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1c4b7_7b91e0.json?c=userOrOld&label=id:node_11694906

 

And an undesignated cluster with S:244-247 (spotted by @Over-There-Is) with a large deletion at S:244-247:
Query: G11243A,C1190T
Samples: 14
Places : NY only

<Details><Summary>
dead sublineages
</Summary>
WIth two sibling branches after:
KP.2.2 > T24364C >   S:T22N (C21627A)  >>**Orf1b:K2660R** (A21446G) then Orf1a:T1794I (C5646T) =PLPro_T201I then
or
**KP.2.2 > T24364C >   S:T22N (C21627A)  >>**Orf1b:K2660R** (A21446G) then Orf1a:T1794I (C5646T)>>** C4276T >T6971C, T17400C, S:K97E (A21851G), **S:K478T** (A22995C) rev, T23119C
or 
 

Query for 478T :  C5646T,C4276T,T6971C
Samples: 3 (GBW Netherlands)
 

there is a single patient with S:A475V & S:G181E , that has been sampled by GBW  arriving from India   
Query for S:A475V: C1911T, T6082C,G22104A,
Samples:2 (GBW India)

and there is an interesting lineage on a different branch with **S:K478E and Orf3a:T24N**
KP.2.2 > T24364C >   S:T22N (C21627A)   >> **Orf1b:K2660R** (A21446G)  >> S:K478E (A22994G), Orf3a:T24N (C25463A)
Query: T24364C ,A22994G, C25463A
Samples: 3 India (GBW)with further S:L461P , Italy with further S:A794T, NZL

 

</Details>

Tree (updated on October 2):

<img width="1173" alt="Screenshot 2024-10-03 alle 00 42 40" src="https://github.com/user-attachments/assets/dba5f68f-828c-483d-b3e8-7c4eff3c853e">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice19_genome_test_7b41_d11a50.json?c=gt-S_97,478&gmax=25384&gmin=21563&label=id:node_7317231

 

<Details><Summary>
IDs </Summary>
EPI_ISL_19175957, EPI_ISL_19195789, EPI_ISL_19195940,
EPI_ISL_19196466, EPI_ISL_19196469, EPI_ISL_19196472,
EPI_ISL_19215569, EPI_ISL_19215579, EPI_ISL_19215584,
EPI_ISL_19221625, EPI_ISL_19227119, EPI_ISL_19227848,
EPI_ISL_19262919, EPI_ISL_19263096, EPI_ISL_19266639,
EPI_ISL_19268121, EPI_ISL_19273639, EPI_ISL_19273650,
EPI_ISL_19273754, EPI_ISL_19279853, EPI_ISL_19280236,
EPI_ISL_19281309, EPI_ISL_19284847, EPI_ISL_19286287,
EPI_ISL_19288317, EPI_ISL_19288321, EPI_ISL_19289660,
EPI_ISL_19289751, EPI_ISL_19298481, EPI_ISL_19298698,
EPI_ISL_19300171, EPI_ISL_19306360, EPI_ISL_19308849,
EPI_ISL_19309114, EPI_ISL_19311662, EPI_ISL_19311737,
EPI_ISL_19311762, EPI_ISL_19315274, EPI_ISL_19317137,
EPI_ISL_19318636, EPI_ISL_19318656, EPI_ISL_19323618,
EPI_ISL_19328302, EPI_ISL_19328305, EPI_ISL_19328481,
EPI_ISL_19328538, EPI_ISL_19329420, EPI_ISL_19329974,
EPI_ISL_19333104, EPI_ISL_19338989, EPI_ISL_19339143,
EPI_ISL_19339618, EPI_ISL_19340061, EPI_ISL_19340255,
EPI_ISL_19341177, EPI_ISL_19341265-19341266, EPI_ISL_19346691,
EPI_ISL_19346811, EPI_ISL_19346825, EPI_ISL_19346919,
EPI_ISL_19347330, EPI_ISL_19349917, EPI_ISL_19350183,
EPI_ISL_19350328, EPI_ISL_19350667, EPI_ISL_19351728,
EPI_ISL_19351751, EPI_ISL_19353646, EPI_ISL_19361224,
EPI_ISL_19362045, EPI_ISL_19369828, EPI_ISL_19369853,
EPI_ISL_19369946, EPI_ISL_19369990, EPI_ISL_19372150,
EPI_ISL_19373024, EPI_ISL_19373028, EPI_ISL_19376200,
EPI_ISL_19377834, EPI_ISL_19377854, EPI_ISL_19378943,
EPI_ISL_19379273, EPI_ISL_19379565, EPI_ISL_19379731,
EPI_ISL_19380400, EPI_ISL_19381041, EPI_ISL_19383565,
EPI_ISL_19384523, EPI_ISL_19384542, EPI_ISL_19386041,
EPI_ISL_19386108, EPI_ISL_19386115, EPI_ISL_19387400,
EPI_ISL_19388724, EPI_ISL_19390397
</Details>

**Comment by FedeGueli** [comment]
76 South Korea, Singapore.

**Comment by FedeGueli** [comment]
80 now with two more aptient caught by GBW from india and Hong Kong. ping @corneliusroemer

**Comment by FedeGueli** [comment]
75 after editing the query to exclude https://github.com/sars-cov-2-variants/lineage-proposals/issues/1963

**Comment by FedeGueli** [comment]
96 it goes one growing

**Comment by FedeGueli** [comment]
Now two sublineages of this got 478T and 478Q, i m updating the proposal

**Comment by FedeGueli** [comment]
@corneliusroemer ping similar to XEC it has 59L +22N but also further mutations have been acquired

**Comment by FedeGueli** [comment]
106 new country South Korea
there are two more branches with 478X :
478E+Orf3a:T24N from Italy and India
478I recent singlet from Singapore

@corneliusroemer i suggest to designate the 22N branch so we will track eaasily the further 478X branches that looks interesting

**Comment by Over-There-Is** [comment]
a cluster in new york gets S:244-247 deleted.

**Comment by FedeGueli** [comment]
@corneliusroemer i would designate this one also to track better its several sublineages with Spike muts/dels

**Comment by FedeGueli** [comment]
Another KP.2.2 popped up with https://github.com/sars-cov-2-variants/lineage-proposals/issues/2072

**Comment by FedeGueli** [comment]
130, Russia

**Comment by FedeGueli** [comment]
This is growing and likely very prevalent in the Indian Peninsula.

**Comment by Over-There-Is** [comment]
172

**Comment by Over-There-Is** [comment]
> a cluster in new york gets S:244-247 deleted.

Still growing

**Comment by FedeGueli** [comment]
> > a cluster in new york gets S:244-247 deleted.
> 
> Still growing

yeah in NY

**Comment by FedeGueli** [comment]
179 , and 8 for the 478T+97E sublineage with two from Ireland

**Comment by FedeGueli** [comment]
As noted by @ryhisner first , four recent samples from Singapore have a large insertion in the FCS :
<img width="598" alt="Screenshot 2024-10-10 alle 13 29 53" src="https://github.com/user-attachments/assets/ce98d5e2-2036-461a-9e7d-2c5f2e639ee1">
S:ins678THKLL + S:N679E resulting in a FCS 673SYQTQTTHKLLESRRRARSVASQS691
notably they belong to a branch with S:A475V different from the one formerly tracked (singlet dead)
Query for 475V:   C22986T,G2591T,T3565C finds 9 samples from India, Australia, Singapore
Query for Ins678: ins23596ACACACAAGCTTCTA, finds 3 (but there are 4) from Singapore

**Comment by FedeGueli** [comment]
Put to sleep the tracking for the 478E branch. the main branch goes to 204 with the 478T/97E branch rising to 12 with samples from Slovenia too.

**Comment by FedeGueli** [comment]
Main proposal designated  KP.2.2.1 via https://github.com/cov-lineages/pango-designation/commit/efe8e07488add0710c5a21427ee3737ac5b1c8b9

**Comment by FedeGueli** [comment]
Descendants of Kp.2.2.1 tracked here have been designated via https://github.com/cov-lineages/pango-designation/commit/4744b7ae1eb832bad6b27a1b73baa66ecb928cce#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1177
NH.1 is 97E+478T
NH.2 is 478Q
NH.3 is 475V + orf1a:ORF1a:A776S

**Comment by FedeGueli** [comment]
cc @Over-There-Is if you want to open an issue on the secondary repo for the sublineage with the 244-247 deletion it would be welcomed please.
