### ISSUE TITLE
A B.1.617.2 sublineage with Orf1a:P380S dominant in Vietnam

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#275]
Proposal of a B.1.617.2 (Nexstrain clade 20I) Sublineage circulating in Vietnam 

Prevalence: 
90-100% in Vietnam
![Schermata 2021-10-20 alle 14 06 38](https://user-images.githubusercontent.com/87669813/138089780-6d8b9183-3e13-436f-9bb1-2d4475d3abef.png)
https://cov-spectrum.ethz.ch/explore/Vietnam/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22b.1.617.2*%22%2C%22mutations%22%3A[%22Orf1a%3A380S%22]%7D%2C%22matchPercentage%22%3A1%7D

Number of sequences:
617 sequences (500+ in Vietnam, then  47 in Germany)
![Schermata 2021-10-20 alle 14 13 56](https://user-images.githubusercontent.com/87669813/138090512-a56757c7-d12d-4ffc-aa20-ea7bfa9d7d6b.png)
https://outbreak.info/situation-reports?pango=B.1.617.2&muts=Orf1a%3AP380S&loc=USA&loc=USA_US-CA&loc=VNM&selected=Worldwide&overlay=false

Tree:
Mutations
AA: Orf1a:P380S 
Nuc:C1403T, G5584T
https://nextstrain.org/groups/neherlab/ncov/asia-bahrain?branchLabel=aa&c=gt-ORF1a_380&label=clade:21I%20%28Delta%29&r=division&tl=pango_lineage
![Schermata 2021-10-20 alle 14 10 58](https://user-images.githubusercontent.com/87669813/138090230-8e316cba-2504-447a-8b9c-1e8ab0f40199.png)

**Comment by chrisruis** [comment]
Thanks @FedeGueli This was added during the recent large update of Delta lineages as AY.57

**Comment by FedeGueli** [comment]
thank you @chrisruis i totally misses it even if i doublechecked the list! Thank you for your work!
