### ISSUE TITLE
KS.1.1/JN.1* recombinant (337 seqs, >10 places, 16% South Korea 8% Hong Kong) 

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2751]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1806

KS.1.1--JN.1

Breakpoint between 22929 and 24820

Additional mutations: C6701T, C19716T, T25510C, C29311T

Orf1a:L2146F, Orf3a:S40P

C6701T, C19716T from a KS.1.1 branch,
One of T25510C, C29311T from a JN.1* branch, the other is private.

GISAID query: T25510C, C29311T,C19716T,T3565C
No. of seqs: 56(Canada 1 Japan 2 Russia 1 China 1 USA 7(2 from South Korea 1 from France) Netherlands 1 South Korea 41 Ireland 1 Israel 1)

First: EPI_ISL_19257990, South Korea, 2024-6-17
Latest: EPI_ISL_19352398, South Korea, 2024-8-3

30/556 of South Korean seqs after 7/20.
[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/ks_1_1_jn_1_recomb.json?label=id:node_5671987)
![image](https://github.com/user-attachments/assets/8b4aa062-a3ff-4f4a-a22a-19032c71fc87)

**Comment by FedeGueli** [comment]
61 now,
to be noticed that the last two GBW samples from Korea both carry S:K458N .
Query for them: C1960T, T25510C, G22936T
<img width="1362" alt="Screenshot 2024-08-28 alle 23 18 29" src="https://github.com/user-attachments/assets/749716b2-23bf-4b41-9b4f-9890ad2972e1">

**Comment by aviczhl2** [comment]
86, Singapore,

**Comment by aviczhl2** [comment]
South Korea prevalence climbs from 5% to 24/262=9% in seqs sampled after 8-1

**Comment by aviczhl2** [comment]
@corneliusroemer @AngieHinrichs This recomb is now placed under JN.1.18.6, but due to C6701T, C19716T  and S:T22N,F59S it is still better explained as KS.1.1/JN.1* recombinant. When designation please be careful and not designate it as JN.1.18.6 descendant.

**Comment by aviczhl2** [comment]
96, Denmark, Australia

**Comment by FedeGueli** [comment]
123 now , Denmark

**Comment by aviczhl2** [comment]
Also in Germany

**Comment by aviczhl2** [comment]
133, Bangladesh, Indonesia, Italy

**Comment by Over-There-Is** [comment]
KP.3.2.3+C29311T?

**Comment by Over-There-Is** [comment]
-C6701, -G25352T, C8293T, T25510C, C29311T=8
1 is Serbian old sequence, 3 are dropout of this sequences, and the rest 4 are KP.3.2.3

**Comment by Over-There-Is** [comment]
153 now

**Comment by FedeGueli** [comment]
ping @corneliusroemer this should get designated.

**Comment by aviczhl2** [comment]
> -C6701, -G25352T, C8293T, T25510C, C29311T=8 1 is Serbian old sequence, 3 are dropout of this sequences, and the rest 4 are KP.3.2.3

Shouldn't be. It lacks S:V1104L and its breakpoint is before S:1087, so cannot recomb with any KP*.

**Comment by aviczhl2** [comment]
164, Sweden

**Comment by DailyCovidCases** [comment]
Tree now: (150/164 seqs)
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_e713_ef11b0.json?c=pango_lineage&f_userOrOld=uploaded%20sample)
![Screenshot (221)](https://github.com/user-attachments/assets/31453a66-3a30-4d5b-8feb-3d500669d977)
i agree @corneliusroemer this branch is worth designation.

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by aviczhl2** [comment]
247 seqs now.

South Korea prevalence after 9-1=16/101=16%

**Comment by FedeGueli** [comment]
> C6701T, C19716T, T25510C, C29311T

yeah from South Korea, some Seqs from South Korea have some movement at the end of Orf6 but apparently it is not related to large deletions of Orf7ab/Orf8 as i was thinking.

**Comment by aviczhl2** [comment]
@corneliusroemer  this recombinant is huge now.

**Comment by FedeGueli** [comment]
> @corneliusroemer this recombinant is huge now.

Cornelius it is KS.1.1 spike without 1087S , so it belongs to the 22N+59S group with some tuning coming from outside the spike likely

**Comment by xz-keg** [comment]
3/40 in the most recent Hong Kong batch

**Comment by FedeGueli** [comment]
@corneliusroemer ping

**Comment by xz-keg** [comment]
There is a new stepwise S680F-R190S-K478I branch emerging from this.

**Comment by xz-keg** [comment]
329 seqs now.

**Comment by xz-keg** [comment]
> 334 , to me it is slowing down a lot

![image](https://github.com/user-attachments/assets/098e14a5-966d-4fba-b35d-bf6beb85b4bd)

Looks like it is still growing

**Comment by FedeGueli** [comment]
> > 334 , to me it is slowing down a lot
> 
> ![image](https://private-user-images.githubusercontent.com/10445944/376432039-098e14a5-966d-4fba-b35d-bf6beb85b4bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzA4NTQsIm5iZiI6MTcyODk3MDU1NCwicGF0aCI6Ii8xMDQ0NTk0NC8zNzY0MzIwMzktMDk4ZTE0YTUtOTY2ZC00ZmJhLWIzNWQtYmY2YmViODViNGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA1MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZWU0MTUxMTcwNjU0MzI2OTQzMWFkZjIzMjczOTE3MGM5MTlhY2MyYmYzMDRmYWRjMGYxZGIwMjhkZDRiYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.69-7EV7i4cbCkLo2yjIyNXH0td8X7ejVtBmJWWvLtgs)
> 
> Looks like it is still growing

Yeah but less than before lets wait S.Korea samples

**Comment by Over-There-Is** [comment]
kuwait

**Comment by FedeGueli** [comment]
Donor designated KS.1.1.2 via KS.1.1 donor now designated KS.1.1.2 via. https://github.com/cov-lineages/pango-designation/commit/c542eb9c3b5805a189bb9c314dce67744b27ba1e#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1277

This recombinant designated XEL via https://github.com/cov-lineages/pango-designation/commit/d247018d827cb510992c2ecb1d739b086441e36e

**Comment by Over-There-Is** [comment]
Hubei/HCDC-WH6856/2024|EPI_ISL_19384912|2024-08-14 from malaysia

**Comment by FedeGueli** [comment]
> There is a new stepwise S680F-R190S-K478I branch emerging from this.

<img width="1163" alt="Screenshot 2024-10-23 alle 14 45 59" src="https://github.com/user-attachments/assets/8016b6cf-902b-4c86-822b-e561bb875c0b">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5a608_8edb70.json?c=userOrOld&label=id:node_7364125

with a new sample from UAE collected in october via GBW

**Comment by FedeGueli** [comment]
> There is a new stepwise S680F-R190S-K478I branch emerging from this.

this went up to 5 now found in NY

**Comment by FedeGueli** [comment]
> > There is a new stepwise S680F-R190S-K478I branch emerging from this.
> 
> this went up to 5 now found in NY

Now 8  cc @xz-keg maybe worth proposing it??

**Comment by FedeGueli** [comment]
> > > There is a new stepwise S680F-R190S-K478I branch emerging from this.
> > 
> > 
> > this went up to 5 now found in NY
> 
> Now 8 cc @xz-keg maybe worth proposing it??

scratch that already proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/2138
