### ISSUE TITLE
JN.1.16.1+S:K444R, S:T22N (30 seq., 8 countries)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#2753]
Proposal for a sublineage of JN.1.16.1
Earliest sequence: 24.06.2024 (Senegal(/Egypt)
Countries detected: Egypt, Senegal, France, England, Canada, Australia, USA, Slovenia

Defining Mutations:
nuc	unique	G12892A, T16600C, T28297C, C8818T, A22893G, C21627A
nuc	homoplasies	C5239T, C7869T, T21653C, A22107G, C22993T, C22792T
ORF1ab	homoplasies	S2535L
S	homoplasies	S31P, K182R
S	unique	K444R, T22N

GISAID query: G12892A, T16600C, T28297C

![grafik](https://github.com/user-attachments/assets/5f4a2fea-ec0f-4f5c-b794-991f8fa221e9)

![grafik](https://github.com/user-attachments/assets/8a53cc25-4f18-4301-b616-821901b04292)

![grafik](https://github.com/user-attachments/assets/6eedf5ff-eb31-4a3a-a212-4817c7f419fc)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_259cf_d7f0d0.json?c=gt-S_182,31,444&gmax=25384&gmin=21563

EPI_ISL_19273031, EPI_ISL_19273041, EPI_ISL_19293986, EPI_ISL_19324095, EPI_ISL_19333883, EPI_ISL_19334617, EPI_ISL_19334646, EPI_ISL_19342253, EPI_ISL_19343433, EPI_ISL_19348653, EPI_ISL_19348783, EPI_ISL_19357294, EPI_ISL_19358013, EPI_ISL_19358014, EPI_ISL_19358015, EPI_ISL_19358016, EPI_ISL_19358074, EPI_ISL_19358082, EPI_ISL_19358087, EPI_ISL_19358088, EPI_ISL_19358089, EPI_ISL_19358159, EPI_ISL_19358160, EPI_ISL_19358282, EPI_ISL_19359737, EPI_ISL_19360319

OZ156494.1, PQ213906.1, PQ214030.1

**Comment by FedeGueli** [comment]
This is LF.7
