### ISSUE TITLE
LP.7 [KP.1.1.3 + S:R190S ] with a S:G75S+S:A475V branch (24)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2755]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1729

KP.1.1.3 >> S:R190S (G22132T)  >> S:G75S (G21785A), Orf3a:S74F (C25613T) >> S:A475V (C22986T) >> S:P85Q (C21816A),
C26789T
Query for KP.1.1.3 + S:R190S : -C3885A,-C1909T,-T24079C,-T14508C,-T13123C,-C25925T,A24819G,G22132T,4999,T3565C
Samples: 135
Countries:  >20 (including GBW samples from Kenya, India, Qatar, Saudi Arabia, UAE)

Query for S:K478T branch: T4732C  ,C9803T,T3565C
Samples: 5 
Places: India (2, GBW),US (3,CA)

Query for the S:G75S and S:A475V: G22132T,C4999T,C25613T,T3565C
Samples: 21

 
Tree updated on October 2: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice22_genome_test_7b41_d11a50.json?c=gt-S_475,478&gmax=25384&gmin=21563&label=id:node_7278929
 https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice22_genome_test_7b41_d11a50.json?c=gt-S_475,478&gmax=25384&gmin=21563&label=id:node_7278929

475V branch:
<img width="1163" alt="Screenshot 2024-10-03 alle 01 45 15" src="https://github.com/user-attachments/assets/c0d113b0-ea8b-498e-852d-a678aecf5442">

478T (rev) branch:
<img width="1170" alt="Screenshot 2024-10-03 alle 01 45 57" src="https://github.com/user-attachments/assets/8b2e124c-f884-40a2-a774-f715341888b2">

IDs:
EPI_ISL_19186303, EPI_ISL_19193651, EPI_ISL_19197472,
EPI_ISL_19221339, EPI_ISL_19221529, EPI_ISL_19229784,
EPI_ISL_19240726, EPI_ISL_19254526, EPI_ISL_19261933,
EPI_ISL_19268135, EPI_ISL_19280775, EPI_ISL_19282014,
EPI_ISL_19294116, EPI_ISL_19294516, EPI_ISL_19300547,
EPI_ISL_19307172, EPI_ISL_19307487, EPI_ISL_19311216,
EPI_ISL_19311592, EPI_ISL_19313860, EPI_ISL_19313961,
EPI_ISL_19314296, EPI_ISL_19316991, EPI_ISL_19321600,
EPI_ISL_19324443, EPI_ISL_19324732, EPI_ISL_19324863,
EPI_ISL_19330833, EPI_ISL_19332888, EPI_ISL_19333729,
EPI_ISL_19334343, EPI_ISL_19337665, EPI_ISL_19337712,
EPI_ISL_19337756, EPI_ISL_19337759, EPI_ISL_19339171,
EPI_ISL_19339265, EPI_ISL_19347273, EPI_ISL_19350105,
EPI_ISL_19350292, EPI_ISL_19353883, EPI_ISL_19353895,
EPI_ISL_19353898, EPI_ISL_19358521, EPI_ISL_19358595,
EPI_ISL_19361647, EPI_ISL_19362369, EPI_ISL_19362602,
EPI_ISL_19362704, EPI_ISL_19362758, EPI_ISL_19362762,
EPI_ISL_19362964, EPI_ISL_19364376, EPI_ISL_19364383,

<details><Summary> archived T22N </Summary>
Edited on September 19
there is a recent sample with S:T22N
Query: T6023C, C6317T, C25658T
Samples: 1
England
</details>

<Details> <Summary> 190R+435S Recombinant branch now proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/2127 </Summary>
**EDITED NEW** (updated on October 7 )

There is a likely recombinant branch in the 75S 475V tree that exchanged 190S for 435S 
BPI between S:76 and S:811 (because of A23998G) 

Query: G1742A, A20225T, G22865T
Samples: 7 
Places: Canada, US
Tree:
<img width="1176" alt="Screenshot 2024-10-07 alle 01 28 25" src="https://github.com/user-attachments/assets/d42e2764-3960-4908-a696-b7d0883380f0">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_53c43_319870.json?c=gt-S_190&label=id:node_7284399
</Details>

**Comment by FedeGueli** [comment]
61/16

**Comment by HynnSpylor** [comment]
72/18 now

**Comment by FedeGueli** [comment]
> 72/18 now

75 and new countries Philippines, Switzerland

**Comment by Over-There-Is** [comment]
90?

**Comment by Over-There-Is** [comment]
France, Poland

**Comment by FedeGueli** [comment]
-C3885A,-C1909T,-T24079C,-T14508C,-T13123C,-C25925T,A24819G,G22132T,4999,T3565C 
Query updated to exlcude the 493E lineage from Philippines.

**Comment by FedeGueli** [comment]
Query confirmed it is working, just an old Suisse sample but it could be related or not, unrelevant anyway

**Comment by FedeGueli** [comment]
100 Poland

**Comment by FedeGueli** [comment]
There is also a recent sample from England with S:T22N

**Comment by FedeGueli** [comment]
113 Slovenia, Ukraine

**Comment by FedeGueli** [comment]
120 checking the query

**Comment by FedeGueli** [comment]
New additional Sublineage tracked here with S:K478T. 
I recalled someone spotting it first. please if anyone has done that ping me.
Query: T4732C ,C9803T,T3565C

**Comment by FedeGueli** [comment]
cc @aviczhl2 and @corneliusroemer very weirdly the G75S + A475V branch reverted S:R190S and gained convergently S:A435S !
Interestingly the branch is anticipated by A23998G in common with the 190S branch so if it has been a recombination it should have took from some lineage  a short bit  from S:76 to S:811  

it has also two  private mutations:Orf1a:G493S and Orf1b:E2253V
<img width="1167" alt="Screenshot 2024-10-07 alle 01 22 45" src="https://github.com/user-attachments/assets/998992b7-956b-4567-ae47-66d2e0c8d6fa">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_53c43_319870.json?label=id:node_7284401

**Comment by aviczhl2** [comment]
> cc @aviczhl2 and @corneliusroemer very weirdly the G75S + A475V branch reverted S:R190S and gained convergently S:A435S ! Interestingly the branch is anticipated by A23998G in common with the 190S branch so if it has been a recombination it should have took from some lineage a short bit from S:76 to S:811
> 
> it has also two private mutations:Orf1a:G493S and Orf1b:E2253V <img alt="Screenshot 2024-10-07 alle 01 22 45" width="1167" src="https://private-user-images.githubusercontent.com/87669813/373987099-998992b7-956b-4567-ae47-66d2e0c8d6fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjA4MTksIm5iZiI6MTcyODI2MDUxOSwicGF0aCI6Ii84NzY2OTgxMy8zNzM5ODcwOTktOTk4OTkyYjctOTU2Yi00NTY3LWFlNDctNjZkMmUwYzhkNmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDAwMjE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNzg0Y2M5YmYzNzIzNjczNjVlMzhmYTFlZTkxY2NiNDI4NTIxZDVmY2UwNjNmMWVkZWQwNjg3ZTAxZWViMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qcjwCvWm21eDbBX3J8t4mmqxgI92ymWsR8y8TEhT5ok"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_53c43_319870.json?label=id:node_7284401
> 
> Putative query for it : G1742A, A20225T, G22865T Finds 7
make a separate proposal?

**Comment by aviczhl2** [comment]
sandwich recombinant with KP.2.3, KP.2.14, KP.2.16, LB.1.2,LB.1.4 or KR.1, 
breakpoint 1 between S:75 and S:190, breakpoint 2 between S:435 and S:475. 

There exists so many S:R346T+S:A435S branches that may be the other donor. 

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_544b9_346b40.json?f_userOrOld=uploaded%20sample&label=id:node_5398499

**Comment by DailyCovidCases** [comment]
Slowing dơn a lot now

**Comment by xz-keg** [comment]
the R190S is designated LP.7

**Comment by FedeGueli** [comment]
> the R190S is designated LP.7

via https://github.com/cov-lineages/pango-designation/commit/9db833c93fa53eced28d7e128eaaad0b71112353

**Comment by FedeGueli** [comment]
Closing it for now
