### ISSUE TITLE
JN.1.16+ ORF3a:N82Y, S:Q493E, S:S31P (15 seqs, Sweden)

### ISSUE THREAD

**Issue by OKL-FOHM** [cov-lineages/pango-designation#2756]
## Lineage: JN.1.16+
**Mutations:**
- ORF3a:N82Y
- S:Q493E
- S:S31P

### Sequences Information
- **Number of sequences:** 15 (Sweden)
- **GISAID Query:** A25636T T21653C C23039G
- **First Sequence:** EPI_ISL_19310547 (2024-07-22, Sweden)
- **Latest Sequence:** EPI_ISL_19359725 (2024-08-16, Sweden)

### Placement
- **Usher Placement:** 

![image](https://github.com/user-attachments/assets/1e6899a3-6354-4f81-b2fb-895f308036cb)

**Comment by FedeGueli** [comment]
Please close it is JN.1.16.5 anmd its sublineage already proposed

**Comment by OKL-FOHM** [comment]
Closed due to duplication; see issue #2705
