### ISSUE TITLE
Proposal to reopen #206 to designate Lineage 1 (B.1.617.2) circulating in Ghana with ORF1b: M2414I and N: P151S

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#276]
Regarding to the lineage 1 proposed by @c19850727 in issue #206 
Circulating countries: Ghana , Togo, Denmark, 

Key Mutations
ORF1b: M2414I
N: P151S

Nucleotide: G20709T, C28724T
Tree:
https://nextstrain.org/groups/neherlab/ncov/africa-ghana?branchLabel=aa&c=gt-ORF1b_2414&d=tree,entropy,frequencies&p=full&r=division&tl=pango_lineage
![Schermata 2021-10-20 alle 23 10 47](https://user-images.githubusercontent.com/87669813/138173241-07ffcf82-7b5f-47ce-a172-940bc740b9a6.png)

Interestingly it seems to have been seeded in Denmark 
with one more Nuc mutation: T21846C according to this tree:
![Schermata 2021-10-20 alle 23 25 43](https://user-images.githubusercontent.com/87669813/138174725-0a93f29e-2b07-4a4e-87ca-9e12e2f8a323.png)
But not to Usher when i uploaded danish sequences: 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3e9f1_886e0.json?label=nuc%20mutations:G20709T,C28724T)
Where it grew to 1% and spread to some other european countries
![Schermata 2021-10-20 alle 23 34 05](https://user-images.githubusercontent.com/87669813/138175693-94503628-c57d-4fe3-adbf-cf4f7949e49f.png)
https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/Denmark/AllSamples/Past6M/variants?aaMutations=ORF1b%3AM2414I%2CN%3AP151S&pangoLineage=B.1.617.2*

Today there are 360 Sequences of this sublineage up from 25 when first spotted:
![Schermata 2021-10-21 alle 00 37 14](https://user-images.githubusercontent.com/87669813/138182105-d4bef95d-372b-4561-8575-94ecfbaf99b0.png)
https://outbreak.info/situation-reports?pango=B.1.617.2&muts=Orf1b%3AM2414I&muts=N%3AP151S&selected=DNK&loc=USA&loc=USA_US-CA&loc=GHA&loc=DNK&overlay=false

And it is still 15% in Ghana
![Schermata 2021-10-21 alle 00 20 32](https://user-images.githubusercontent.com/87669813/138180632-c7062a8c-f8a5-49cb-a635-7dc563c1a189.png)
https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/Ghana/AllSamples/Past6M/variants?aaMutations=ORF1b%3AM2414I%2CN%3AP151S&pangoLineage=B.1.617.2*

It seems to be part of the recently designated AY.43 lineage with N:9L
then nuc: C18744T
then nuc: C28432T and ORF9b: S50L
then nuc: G20709T
ORF1b: M2414I
Accordingly to Neherlab Tree Denmark:
https://nextstrain.org/groups/neherlab/ncov/denmark?branchLabel=aa&c=gt-ORF1b_2414&p=full&r=division&tl=pango_lineage

Even if in the Africa Neherlab tree it seems to be upstream of AY.43
![Schermata 2021-10-21 alle 00 13 39](https://user-images.githubusercontent.com/87669813/138179955-f2277f79-528f-4727-84c3-d491b9d6900d.png)
https://nextstrain.org/groups/neherlab/ncov/continent-africa?branchLabel=aa&c=gt-N_9&d=tree,entropy,frequencies&p=full&r=division&tl=pango_lineage

Proposed sublineage AY.43.1

**Comment by FedeGueli** [comment]
Interestingly in September 2021 the danish branch of this sublineage acquired S:S680F then S:T124S then S:P1263L .
We have 7 sequences, all 7 in Denmark, with all these 3 spike mutations
https://outbreak.info/situation-reports?pango&muts=S%3AS680F&muts=S%3AT124S&muts=S%3AP1263L&loc=USA&loc=USA_US-CA&loc=GHA&loc=DNK&loc=Worldwide&overlay=false&selected=DNK

**Comment by c19850727** [comment]
Nice catch!

**Comment by FedeGueli** [comment]
Closing this one, no further spread of this
