### ISSUE TITLE
KP.2.3 (S:∆S31) + S:V382L, ORF1a:I3090V (152 seq, 16 countries , Sep 4)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2761]
**Description** Transferred from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/1619
**Sub-lineage of:** KP.2.3 (S:∆S31, H146Q, R346T, F456L, V1104L)
**Earliest sequence:** 2024-5-14, USA, Utah — EPI_ISL_19175796
**Most recent sequence:** 2024-8-19, Denmark - EPI_ISL_19378108
**Continents circulating:** Asia, Europe, North America, Oceania
**Countries circulating:** Many
**Number of Sequences:** 152
**GISAID Nucleotide Query:** G22706T, A9533G
**CovSpectrum Query:** Nextcladepangolineage:KP.2* & G22706T & [1-of: A9533G, C29095T]
**Substitutions on top of KP.2.3:**
**Spike:** V382L
**ORF1a:** I3090V
**Nucleotide:** A9533G,  G22706T, C29095T

**USHER Tree**
Only a temporary link here as I doubt this is of lasting importance. 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c2da_8f1960.json?label=id:node_7052115
<img width="1500" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/4b6aff7f-7407-45ae-abcd-e00c1b32666e">

**Evidence**
Mainly of interest due to recency of collection, wide geographic spread, and the fact that one sequence is from a traveler from India. 

Update: Not a particularly fast lineage, to tell the truth, but it's still alive and over 150 sequences, so I'm moving the proposal here. Like the vast majority of proposals here, it's probably not worthy of designation. Only a matter of time until it gets the automated "Please close this issue" from DailyCovidCases I suppose. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19159306, EPI_ISL_19159308, EPI_ISL_19159313-19159314,
EPI_ISL_19159318, EPI_ISL_19162365, EPI_ISL_19162491,
EPI_ISL_19162535, EPI_ISL_19175796, EPI_ISL_19189066,
EPI_ISL_19195199, EPI_ISL_19195604, EPI_ISL_19195626,
EPI_ISL_19195695, EPI_ISL_19195862, EPI_ISL_19196392,
EPI_ISL_19196399, EPI_ISL_19197410, EPI_ISL_19205306,
EPI_ISL_19208190, EPI_ISL_19208481, EPI_ISL_19210045,
EPI_ISL_19210055, EPI_ISL_19210077, EPI_ISL_19210088,
EPI_ISL_19210583, EPI_ISL_19213662, EPI_ISL_19213670,
EPI_ISL_19213743, EPI_ISL_19213748, EPI_ISL_19213758,
EPI_ISL_19213761, EPI_ISL_19213763-19213764, EPI_ISL_19213766,
EPI_ISL_19213786, EPI_ISL_19213788, EPI_ISL_19213790,
EPI_ISL_19213796-19213797, EPI_ISL_19214304, EPI_ISL_19224189,
EPI_ISL_19224191-19224192, EPI_ISL_19225320, EPI_ISL_19225397,
EPI_ISL_19228748, EPI_ISL_19231544, EPI_ISL_19232419,
EPI_ISL_19232543, EPI_ISL_19238103, EPI_ISL_19240106,
EPI_ISL_19240259, EPI_ISL_19243533, EPI_ISL_19244245,
EPI_ISL_19244641, EPI_ISL_19253040, EPI_ISL_19254942,
EPI_ISL_19254948, EPI_ISL_19255025, EPI_ISL_19255243,
EPI_ISL_19256801, EPI_ISL_19256820, EPI_ISL_19256835,
EPI_ISL_19256854, EPI_ISL_19256874, EPI_ISL_19256888,
EPI_ISL_19265034, EPI_ISL_19265044, EPI_ISL_19265654,
EPI_ISL_19266419, EPI_ISL_19267943, EPI_ISL_19267962,
EPI_ISL_19267970, EPI_ISL_19267997, EPI_ISL_19268012,
EPI_ISL_19268014, EPI_ISL_19269059, EPI_ISL_19269952,
EPI_ISL_19271147, EPI_ISL_19274031, EPI_ISL_19276090,
EPI_ISL_19276413, EPI_ISL_19276633, EPI_ISL_19276691,
EPI_ISL_19278931, EPI_ISL_19278947, EPI_ISL_19281686,
EPI_ISL_19284981, EPI_ISL_19285045, EPI_ISL_19285671,
EPI_ISL_19285698, EPI_ISL_19285752, EPI_ISL_19285772,
EPI_ISL_19285826, EPI_ISL_19286123, EPI_ISL_19286768,
EPI_ISL_19288116, EPI_ISL_19289025, EPI_ISL_19289167,
EPI_ISL_19289263, EPI_ISL_19291974, EPI_ISL_19291976,
EPI_ISL_19293055, EPI_ISL_19293446, EPI_ISL_19294946,
EPI_ISL_19299856, EPI_ISL_19304795, EPI_ISL_19306740,
EPI_ISL_19309942, EPI_ISL_19310516, EPI_ISL_19313067,
EPI_ISL_19313132, EPI_ISL_19313378-19313380, EPI_ISL_19313401,
EPI_ISL_19314959, EPI_ISL_19314978, EPI_ISL_19316684,
EPI_ISL_19316748, EPI_ISL_19319026, EPI_ISL_19319958,
EPI_ISL_19323623, EPI_ISL_19323704, EPI_ISL_19325931,
EPI_ISL_19327149, EPI_ISL_19327230-19327231, EPI_ISL_19329255,
EPI_ISL_19332770, EPI_ISL_19332987, EPI_ISL_19343748,
EPI_ISL_19343830, EPI_ISL_19344987, EPI_ISL_19346356,
EPI_ISL_19347817, EPI_ISL_19349834, EPI_ISL_19349867,
EPI_ISL_19350110, EPI_ISL_19352803, EPI_ISL_19354820,
EPI_ISL_19357959, EPI_ISL_19359097, EPI_ISL_19361955,
EPI_ISL_19365073, EPI_ISL_19368183, EPI_ISL_19368756,
EPI_ISL_19371118, EPI_ISL_19373162, EPI_ISL_19378108,
EPI_ISL_19378351
</details>

**Comment by DailyCovidCases** [comment]
ping @corneliusroemer worth a designation this one

**Comment by ryhisner** [comment]
> ping @corneliusroemer worth a designation this one

I disagree. Only 166 sequences total and it seems basically dead. There's no point in designating relatively unremarkable lineages like this that have nothing particularly interesting about them, haven't made a serious impact, and are irrelevant going forward.

**Comment by Over-There-Is** [comment]
189
