### ISSUE TITLE
KP.3.2+S:S31P widespread in China(48 seqs, >10 places)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2764]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1899

KP.3.2+G25617A+G11761A, T21653C(S:S31P)

GISAID query: G11761A, T21653C, G25617A 
No. of seqs: 14(China 9(Hubei, Gansu, Shanxi) USA 1(from Hong Kong ) Australia 1 Singapore 1 Japan 1 Spain 1)

First: EPI_ISL_19299334, Hubei, 2024-7-7
Latest: EPI_ISL_19377995, Gansu, 2024-8-30

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/kp_3_2_s31p.json?label=id:node_5548025)
![image](https://github.com/user-attachments/assets/d0f8cea0-8d89-4f70-aaba-51213fad4e23)

One Spanish seq is categorized to KP.3.2.3 due to having Orf3a:S40P, however it has the G11761A and shall belong to this branch. (Orf3a:S40P is convergent)

**Comment by FedeGueli** [comment]
<img width="1097" alt="Screenshot 2024-09-14 alle 16 35 30" src="https://github.com/user-attachments/assets/c4b9df54-fba5-43d3-8ae3-a1a606a50020">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice23_genome_test_542a1_597120.json?label=id:node_11655396
this could have recombined with something else 
3 samples 2 patients from UK,
Query: C28744T, T21653C, G25617A

**Comment by aviczhl2** [comment]
> G11761A, T21653C, G25617A

please make a separate issue

**Comment by FedeGueli** [comment]
> > G11761A, T21653C, G25617A
> 
> please make a separate issue

i will if. some new seqs will pop up

**Comment by aviczhl2** [comment]
Also in Zhejiang

**Comment by aviczhl2** [comment]
24, South Korea, Canada

**Comment by aviczhl2** [comment]
+1 Anhui

**Comment by Over-There-Is** [comment]
G25617A=ORF3d:G32R

**Comment by FedeGueli** [comment]
> > please make a separate issue
> 
> i will if. some new seqs will pop up

no new seqs

**Comment by aviczhl2** [comment]
A lot from today's Chinese batch.

**Comment by FedeGueli** [comment]
It was close to kp.3.1.1 baseline before this batch, i wonder where it will be now . @aviczhl2 the recombinant branch has moved? Last night it had no  new seqs

**Comment by FedeGueli** [comment]
+1 Jap

**Comment by xz-keg** [comment]
+2 Heilongjiang

**Comment by xz-keg** [comment]
+1 Anhui +1 France

**Comment by xz-keg** [comment]
designated KP.3.2.6

**Comment by FedeGueli** [comment]
> designated KP.3.2.6

via https://github.com/cov-lineages/pango-designation/commit/81c3b2dea03e3b95901ec189c8694b58926c8783

**Comment by FedeGueli** [comment]
@xz-keg and @Memorablea both highlighted a KP.3.2.6 branch in Shanxi that acquired S:T22N.
 My query for it is C9886T,C21627A,A2611C but likely it misses a couple of sequences.

**Comment by Memorablea** [comment]
> @xz-keg and @Memorablea both highlighted a KP.3.2.6 branch in Shanxi that acquired S:T22N. My query for it is C9886T,C21627A,A2611C but likely it misses a couple of sequences.

In fact, KP.3.2.6 with S:T22N have two branch.
![image](https://github.com/user-attachments/assets/6f6f078b-9a02-4511-a604-dcba665b0ae9)

**Comment by FedeGueli** [comment]
> > @xz-keg and @Memorablea both highlighted a KP.3.2.6 branch in Shanxi that acquired S:T22N. My query for it is C9886T,C21627A,A2611C but likely it misses a couple of sequences.
> 
> In fact, KP.3.2.6 with S:T22N have two branch. 

query for the other branch: A26005G  ,C21627A, C22594T

**Comment by Over-There-Is** [comment]
There is still another one T22N branch: KP.3.2.6> C28453T> C21627A
one sequence is USA/CA-GBW-GKISBBBD26736/2024|EPI_ISL_19345248|2024-08-09, exported from HK
another one sequence is recombined with NB.1: Gansu/BYCDC170/2024|EPI_ISL_19594413|2024-11-28
Gansu is in Northwestern China, and HK is in South China, with a distance about 2000 kilometers between these 2 places.

**Comment by FedeGueli** [comment]
> > Some of you could propose in one multiple lineages issue the various T22N sublineages? cc @xz-keg @Over-There-Is @Memorablea
> 
> [sars-cov-2-variants/lineage-proposals#2283](https://github.com/sars-cov-2-variants/lineage-proposals/issues/2283) is KP.3.2.6 with S:T22N various sublineages，perhaps you are referring to all T22N lineages?

Thank you it is perfect!
