### ISSUE TITLE
KP.2.3+S:A1174V (296 seqs, >10 places) 27% in Brazil ,Sep

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2765]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1843

KP.2.3(with 31del)+C28714T+C11518T+C25083T(S:A1174V)

GISAID query: C28714T, C11518T, C25083T
No. of seqs: 104(Belgium 1 Brazil 18 Canada 3 Denmark 1 UK 8 France 8 Ireland 4 Italy 3 Japan 1 Netherlands 5 New Zealand 1 Spain 23 Sweden 4 USA 24(1 from Nether;ands 1 from Spain 2 from Japan))

First: EPI_ISL_19276081, France, 2024-5-14
Latest: EPI_ISL_19386429,Canada, 2024-8-22

9/71 in Brazil seqs from 2024/8/1

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/kp_2_3_a1174v.json?label=id:node_5512655)
![image](https://github.com/user-attachments/assets/786336af-50e6-442d-acb7-9cba448d4f5e)

**Comment by aviczhl2** [comment]
107,Chile

**Comment by FedeGueli** [comment]
191 now with a striking 25% in Brazil in September  close to 30% in Rio after August 1, 
Ping @corneliusroemer 
On S:A1174X i have found some interesting references: 
In this study https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10290734/ authors (Yamamoto et al) grew different variants along wioth plasma from patients with different immunity, S:A1174T has been acquired quite quickly and showed strong resistnace to vaccinated people serum.

cc @ryhisner @aviczhl2 @thomasppeacock

**Comment by aviczhl2** [comment]
49/184=27% prevalence in Brazilian Sep seqs.

**Comment by FedeGueli** [comment]
201 and apparently competitive vs Kp.3.1.1 baseline, maybe due to high prevalence in Brazil

**Comment by xz-keg** [comment]
232 seqs now.

**Comment by xz-keg** [comment]
250, Mexico,Germany

**Comment by xz-keg** [comment]
> This is consistently slighty faster than Kp.3.1.1 baseline that for a KP.2.3 is quite a thing.

I have a feeling that KP.2.3 is more advanterous in some regions than KP.3.1.1. 
Recent batches from China also show a quite unexpected rise of KP.2.2 and KP.2.3 while KP.3.1.1 decays.

**Comment by xz-keg** [comment]
267, Ukraine, Argentina, Luxembourg

**Comment by FedeGueli** [comment]
Around 20% in Brazil after September 15  sampled in 3 states and in a passenger from Brazil via GBW

**Comment by xz-keg** [comment]
296 seqs now, also in Austria

**Comment by FedeGueli** [comment]
Designated KP.2.3.12

**Comment by FedeGueli** [comment]
> it seems there are some sequences without 11518.

yeah 382>>404 i didnt check if all of them belongs really to this but it could be.thx . Brazil prevalences seems going down to 20% after September 20 and furter down but with small sample size after Oct 1. still interesting to see how 1174X  suddenly became convergent an d beneficial

**Comment by FedeGueli** [comment]
30% after October 15 in brazil

**Comment by FedeGueli** [comment]
There have been 4 independent emergence of  S:R190Son KP.2.3.12 all in Paraiba Brazil 
I leave it here to keep trace of them 

Tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_20323_f1c00.json?f_userOrOld=uploaded%20sample&label=id:node_7401475
<img width="1162" alt="Screenshot 2025-01-10 alle 11 10 17" src="https://github.com/user-attachments/assets/7772695c-ca0e-48c4-9d5b-9c499f6a4819" />
