### ISSUE TITLE
LB.1 + S:K478T (rev) + S:E96V emerged in Nepal (11)  

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2769]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1953

There is another LB.1 sublineage different from LB.1.9 that got the uptrending S:K478T reversion.
In addition it has S:E96V that has been sampled 1500 times in the course of the pandemic mostly in a sublineage of AY.98 that accounts for 80% of the total S:E96V and in Uk it was [faster](https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/AllTimes/variants?%2FAllSamples%2FPast3M%2Fvariants%3FnextcladePangoLineage=JN.1*&nextcladePangoLineage=AY.98*&aaMutations1=S%3AE96V&nextcladePangoLineage1=AY.98*&analysisMode=CompareToBaseline&) than basic AY.98

The interesrting thing of this LB.1 is that it comes from Nepal with 3/10 samples being from there

Defining mutations:
LB.1> S:K478T (rev A22995C) > G29254A > S:E96V (A21849T)
Query: A21849T,G29254A
Samples: 10 (Nepal 3 ) US (5 , Ohio,NY), India (2 , 1 patient via GBW)

Tree:
<img width="1132" alt="Screenshot 2024-09-08 alle 17 55 34" src="https://github.com/user-attachments/assets/a65b98cf-eab3-423d-8289-0dc0c577f838">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_293d3_dc0a10.json?label=id:node_7031318

IDs:EPI_ISL_19324461-19324462, EPI_ISL_19332154, EPI_ISL_19333095,
EPI_ISL_19333117, EPI_ISL_19358508, EPI_ISL_19362795,
EPI_ISL_19375189, EPI_ISL_19375210, EPI_ISL_19381970,

**Comment by FedeGueli** [comment]
11

**Comment by DailyCovidCases** [comment]
This branch has slowed down a lot. You can close this @FedeGueli
