### ISSUE TITLE
Proposal for new sub-lineage of AY.29 with C5365T and C28170T (ORF8 P93S) in Japan

### ISSUE THREAD

**Issue by kkosaki** [cov-lineages/pango-designation#277]
Submitted by Kenjiro Kosaki and Takako Shimura ( Center for Medical Genetics, Keio University School of Medicine)

**Description**
Sub-lineage of: AY.29
Earliest sequence: Japan 2021-05-29 (Japan/PG-116865/2021)
Most recent sequence: Current
Countries circulating: Japan
Lineage deriving from AY.29 with extra mutations, C5365T(ORF1a, synonymous) and C28170T(ORF8:P93S).

![AY29 X_fig1](https://user-images.githubusercontent.com/65483127/138282893-7515cced-3eb3-46aa-8789-2518ba5c843d.png)
[https://outbreak.info/situation-reports?pango=AY.29&muts=ORF8%3AP93S&muts=ORF1a%3AY1700Y&loc=IND&loc=GBR&loc=USA&loc=Worldwide&loc=Worldwide&overlay=false&selected=Worldwide](https://outbreak.info/situation-reports?pango=AY.29&muts=ORF8%3AP93S&muts=ORF1a%3AY1700Y&loc=IND&loc=GBR&loc=USA&loc=Worldwide&loc=Worldwide&overlay=false&selected=Worldwide)

**Genomes**
[AY29.X.genomes_C5365T_C28170T.txt](https://github.com/cov-lineages/pango-designation/files/7389261/AY29.X.genomes_C5365T_C28170T.txt)

**Evidence**
<img width="519" alt="AY29 X_fig2" src="https://user-images.githubusercontent.com/65483127/138283880-c6906005-ba53-44db-9aed-9483daf77523.png">
[https://nextstrain.org/community/kkosaki/ncov/japan?c=gt-nuc_5365,28170](https://nextstrain.org/community/kkosaki/ncov/japan?c=gt-nuc_5365,28170)

![AY29 X_fig3](https://user-images.githubusercontent.com/65483127/138283952-a66a49c5-2438-47fe-8d0d-b8355db98f34.png)
[https://nextstrain.org/ncov/gisaid/asia?c=gt-nuc_5365,28170&d=tree,entropy,frequencies&p=full&tl=pango_lineage](https://nextstrain.org/ncov/gisaid/asia?c=gt-nuc_5365,28170&d=tree,entropy,frequencies&p=full&tl=pango_lineage)

**Comment by chrisruis** [comment]
It looks like the proportion of AY.29 sequences with Orf8:P93S in Japan hasn't increased through time relative to the total AY.29 clade in Japan. We therefore haven't designated this at this point
