### ISSUE TITLE
KP.2 Plus S:I934V and S:N30K emerged in China (62 , >10 countries)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2770]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1699

There is a little KP.2 sublineage from China that instead evolving toward a negative charged N Glycan at S:30  went in the opposite direction gaining a positive charged K at S:30.
S:N30K has been rare in the pandemic with only 500 samples with iit. Half of them from a single AY.4 sublineage in Uk with a slight advantage over parental lineage but there were also a S:181V mutation so unsure if related to S:30K.
It doesn't seem fast but it is going on spreading, worth to track it here on Pango and eventually designating it if it grows further.

Defining mutations:
KP.2 > Orf1a:P1803L (C5673T = PLPro_P240L) > C14220T > S:I934V (A24362G) > T931A, G8872A, S:N30K (T21652G)
Query: T931A,C5673T,G8872A

Samples: 32
First sampled on 2024-04-14 in Hubei
Countries: 7 countries ( mostly Hubei and Hong Kong)
Tree:
<img width="1160" alt="Screenshot 2024-09-08 alle 18 04 46" src="https://github.com/user-attachments/assets/18564114-9698-4199-8ed6-56154b57a2e9">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_370f2_dcac10.json?label=id:node_7046727

IDs:
EPI_ISL_19150434, EPI_ISL_19167463, EPI_ISL_19183739,
EPI_ISL_19232554, EPI_ISL_19232557, EPI_ISL_19238604,
EPI_ISL_19266908, EPI_ISL_19268019, EPI_ISL_19268023,
EPI_ISL_19279765, EPI_ISL_19279843, EPI_ISL_19299484,
EPI_ISL_19315261, EPI_ISL_19333849, EPI_ISL_19333854,
EPI_ISL_19333975, EPI_ISL_19351792, EPI_ISL_19357044,
EPI_ISL_19363526, EPI_ISL_19371639, EPI_ISL_19371645,
EPI_ISL_19371668, EPI_ISL_19371670, EPI_ISL_19378166,
EPI_ISL_19384012, EPI_ISL_19384561, EPI_ISL_19384632,
EPI_ISL_19384714, EPI_ISL_19384836, EPI_ISL_19384846,
EPI_ISL_19384866, EPI_ISL_19385025

**Comment by FedeGueli** [comment]
34

**Comment by FedeGueli** [comment]
38, Indonesia France

**Comment by FedeGueli** [comment]
To be noted that these two indonesian sequences are the first samples from there since many months

**Comment by DailyCovidCases** [comment]
This branch has slowed down a lot. I think you can close this @FedeGueli

**Comment by FedeGueli** [comment]
40 4 in september not to be closed

**Comment by FedeGueli** [comment]
45 4 from Shanxi (from August) 1 from Denmark (September)

**Comment by FedeGueli** [comment]
51 Sweden

**Comment by FedeGueli** [comment]
this seems going well now approaching toward KP.3.1.1 baseline ping @corneliusroemer

**Comment by FedeGueli** [comment]
Taiwan from outside and a canadian cluster bring this to 60

**Comment by FedeGueli** [comment]
62

**Comment by FedeGueli** [comment]
https://github.com/cov-lineages/pango-designation/commit/a3d38ca258578e6487aebe3e976302f258aeaeef#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1204
