### ISSUE TITLE
KP.2.8 with S:255-257 deletions (34 seqs, 12 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [cov-lineages/pango-designation#2773]
_Taken from **Branch 1** of sars-cov-2-variants/lineage-proposals#1794_

**Defining Mutations:** `KP.2.8` > `A1819G` > `C29095T` > `del22325_22333 (S:SSG255-257Δ)`
**Query:** `A1819G, del22325_22333`
**Earliest seq:** 2024-03-29 (`EPI_ISL_19037182`, South Australia)
**Latest seq:** 2024-08-15 (`EPI_ISL_19380520`, British Columbia, Canada)
**Sampled Countries:** Canada (9: BC), Australia (7: SA/4; QLD/3), Spain (6), USA (4: CO; OH; TN; TX), Austria (1), Chile (1), France (1), Germany (1), Netherlands (1), Norway (1), UK (1: SC), South Korea (1)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Australia/QLD0x014426/2024
Australia/QLD0x01446A/2024
Australia/QLD0x01446C/2024
Australia/SA1368591/2024
Australia/SA1370772/2024
Australia/SA1372155/2024
Australia/SA1390078/2024
Austria/MUW_1744831/2024
Canada/BC-BCCDC-726278/2024
Canada/BC-BCCDC-727446/2024
Canada/BC-BCCDC-727461/2024
Canada/BC-BCCDC-728152/2024
Canada/BC-BCCDC-728206/2024
Canada/BC-BCCDC-728268/2024
Canada/BC-BCCDC-728337/2024
Canada/BC-BCCDC-728338/2024
Canada/BC-BCCDC-728371/2024
Chile/CO-53362/2024
France/OCC-RELAB-HCL724000274901/2024
Germany/BY-USAFSAM-S22702/2024
Netherlands/GE-RIVM-139891/2024
Norway/4947/2024
Scotland/CLIMB-CM7Y8F8T/2024
SouthKorea/KDCA294282/2024
Spain/CT-HUB09097/2024
Spain/CT-HUB09136/2024
Spain/CT-HUB09154/2024
Spain/CT-HUGTiP-G8R182/2024
Spain/CT-HUVH-E54791/2024
Spain/CT-HUVH-E67625/2024
USA/CO-CDPHE-42011782/2024
USA/OH-PLMI-6GN-25209/2024
USA/TN-SPHL-4205/2024
USA/TX-HMH-M-142396/2024
```

epi_isl accessions:
`EPI_ISL_19037182, EPI_ISL_19055759, EPI_ISL_19085178, EPI_ISL_19085317, EPI_ISL_19150328, EPI_ISL_19169441, EPI_ISL_19169445, EPI_ISL_19191188, EPI_ISL_19203552, EPI_ISL_19223501, EPI_ISL_19243908, EPI_ISL_19269209, EPI_ISL_19286108, EPI_ISL_19286145, EPI_ISL_19292287, EPI_ISL_19293234, EPI_ISL_19293432, EPI_ISL_19317633, EPI_ISL_19328611, EPI_ISL_19328629, EPI_ISL_19344720, EPI_ISL_19346218, EPI_ISL_19352493, EPI_ISL_19365270, EPI_ISL_19365285, EPI_ISL_19368836, EPI_ISL_19378300, EPI_ISL_19380339, EPI_ISL_19380385, EPI_ISL_19380448, EPI_ISL_19380494-19380495, EPI_ISL_19380520, EPI_ISL_19393856`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ccf5_27e2e0.json?label=id:node_7020070
![image](https://github.com/user-attachments/assets/c1c82d0e-c038-4be6-baf7-eaac3759b402)

**Comment by FedeGueli** [comment]
35 but slowed down a lot. worth closing this
