### ISSUE TITLE
KP.2.3/XEC Recombinant(45 seqs, 12 countries)

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2774]
Big thanks to @Over-There-Is 
From: https://github.com/sars-cov-2-variants/lineage-proposals/issues/2023
![image](https://github.com/user-attachments/assets/798ae78f-c081-44fa-90d4-097f18d43924)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ed35_40f680.json?f_userOrOld=uploaded%20sample
KP.2.3 / XEC recombinant
Query: C3505T, T5701C, C9286T

Break point: 9286/~15402
Mutations based on JN.1:
C593T(Orf1a:H110Y), C3505T, T5701C(private), C7113T(Orf1a:T2283I), C9286T / C18657T, C19716T, C21627A(S:T22N), T21738C(S:F59S), T22928C(S:F456L), C23039G(S:Q493E), G24872T(S:V1104L), C25006T, C28291A(Orf9b:P3H), G28884C(N:R204P)

5' donor: KP.2.3> C9286T> C593T> C3505T, A15402G(=JN.1+C593T, C3505T, C7113T, C9286T / A15402G, G17334T, C22000A, G22599C, T22928C, G24872T, G25593T, C28714T, 3 seqs, DE 2, NL 1)
3' donor: XEC(=JN.1+C18657T, C19716T, C21627A, T21738C, T22928C, C23039G, G24872T, C25006T, C28291A, G28884C)

Earliest sequence: 07-19 Denmark EPI_ISL_19332668
Latest sequence: 09-02 England, United Kingdom EPI_ISL_19406440
Regions detected: UK 5, Austria 3, Germany 3, Sweden 2, Denmark 1, Netherlands 1, Ukraine 1

Sequences:
EPI_ISL_19332668, EPI_ISL_19364165, EPI_ISL_19368841,
EPI_ISL_19368849, EPI_ISL_19372478, EPI_ISL_19373085,
EPI_ISL_19381036, EPI_ISL_19381934, EPI_ISL_19385623,
EPI_ISL_19389047, EPI_ISL_19389054, EPI_ISL_19390181,
EPI_ISL_19406420, EPI_ISL_19406440, EPI_ISL_19410161,
EPI_ISL_19410789

And 1 sequence seem also related to this branch: EPI_ISL_19378121(potential contaminated)

**Comment by aviczhl2** [comment]
7 countries including Ukraine.

**Comment by aviczhl2** [comment]
+2 netherlands +2 Slovenia, 20 now.

**Comment by Fearuncle** [comment]
now in 8 countries

**Comment by Over-There-Is** [comment]
Also in United States now.

**Comment by Over-There-Is** [comment]
> Break point: 9286/~15402

The left slash here should be a right slash. My typo. Sorry.

**Comment by Fearuncle** [comment]
9 countries

**Comment by Fearuncle** [comment]
In Croatia EPI_ISL_19416657

**Comment by Over-There-Is** [comment]
27, US-NJ

**Comment by FedeGueli** [comment]
> +2 netherlands +2 Slovenia, 20 now.

one of the two samples from netherlands seems a recombinant with KP.3.1.1 getting Orf1a:S4286C , C12616T and S:S31del
EPI_ISL_19413561
<img width="1165" alt="Screenshot 2024-09-19 alle 10 38 00" src="https://github.com/user-attachments/assets/f379d431-38a7-4bd2-96b7-13e13f6b30af">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice4_genome_test_56317_be12f0.json?label=id:node_7053962

Query (if real):  C2110A, C12616T  ,G561A,


Interesting it shares 4 Nucs (C12616T ,G561A, G15372T, G17334T,  ) in orf1ab with a GBW KP.3.1.1 sample from Cuba collected in July  (EPI_ISL_19240845)

**Comment by Over-There-Is** [comment]
31, Ireland +2

**Comment by Fearuncle** [comment]
Now 38

**Comment by Fearuncle** [comment]
![image](https://github.com/user-attachments/assets/e198c8f4-0987-4c49-86a7-e4b611f218a3)
Places #2 on collection 42

**Comment by FedeGueli** [comment]
ping @corneliusroemer this is shown as the third branch of XEC instead it is a recombinant and it seems fast

**Comment by aviczhl2** [comment]
![image](https://github.com/user-attachments/assets/c11da826-d77e-4ef9-8916-356c281a145b)

It is much faster than XEC.

**Comment by FedeGueli** [comment]
> ![image](https://private-user-images.githubusercontent.com/10445944/369634817-c11da826-d77e-4ef9-8916-356c281a145b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NTIxMzcsIm5iZiI6MTcyNjk1MTgzNywicGF0aCI6Ii8xMDQ0NTk0NC8zNjk2MzQ4MTctYzExZGE4MjYtZDc3ZS00ZWY5LTg5MTYtMzU2YzI4MWExNDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDIwNTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4N2YwNTg3MzMyODU0MWFmYjE4YThlOTM2YjVlZGYwOTJkZGZmMzAxODZiOWU1NWRmZjUyYjExMGU5ZGY2YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5PzR1iSJbtGWCHosUCN5emGyyTRIkUGK5Vh-j3qNLWc)
> 
> It is much faster than XEC.

yeas apaprently yes. i remember i spotted that branch when proposing the orf1a:I1367L branch and it was something like two seqs when the proposed brannch was--20? 30? now this will already reach out and overtake that branch in the next week or soon

**Comment by Fearuncle** [comment]
now in france

**Comment by Mydtlwn** [comment]
Please designate it as soon as possible! We should not delay any more.

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by corneliusroemer** [comment]
Interesting, thanks! So there's a single breakpoint here and it's essentially an XEC with some 5' from a KP.2.3 branch, correct?

**Comment by aviczhl2** [comment]
> Interesting, thanks! So there's a single breakpoint here and it's essentially an XEC with some 5' from a KP.2.3 branch, correct?

Yeah

**Comment by FedeGueli** [comment]
> Interesting, thanks! So there's a single breakpoint here and it's essentially an XEC with some 5' from a KP.2.3 branch, correct?

yeah it took back orf1a:T2283I from Jn.1.11.1

**Comment by Fearuncle** [comment]
it is now #1 in Collection 42 
![image](https://github.com/user-attachments/assets/3673d5e8-76a2-49c6-941b-7b0d24a2718b)

**Comment by Fearuncle** [comment]
![image](https://github.com/user-attachments/assets/ec62e93e-b803-4903-8eca-56386bfc2eeb)

**Comment by FedeGueli** [comment]
This, XEC and MV.1 seems able to breakaway from the bunch of fast lineages, but MC.10 + 435S is climbing and it is likely as fast or only slighty slower than them.

**Comment by Fearuncle** [comment]
now 4 with S:F2L and ORF3a:L95F

**Comment by FedeGueli** [comment]
> now 4 with S:F2L and ORF3a:L95F

S:F2L popped up also in another lineage ([#2083](https://github.com/sars-cov-2-variants/lineage-proposals/issues/2083) could be convergent at this point cc @ryhisner

**Comment by FedeGueli** [comment]
Designated XEK via https://github.com/cov-lineages/pango-designation/commit/ba3711a5615956ed97150288eb68356aa0fe7cdd
