### ISSUE TITLE
KP.3.1 subbranch with S:N185D and Orf1a:V3917I (118, 7 countries, Mainly in US)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2775]
Transferred from sars-cov-2-variants/lineage-proposals#1853
KP.3.1> G12014A(ORf1a:V3917I)> A22115G(S:N185D)

Query: G12014A, G15372T, A22115G
Queries for sequences with dropout:
C2061T, G12014A, G15372T, -A22115G(8)
C2061T, -G12014A, G15372T, A22115G(4)
G12014A, G15372T, C23410T, -A22115G(1)
G12014A, G15372T, T25485C, -A22115G(1)

Earliest sequence: 04-08 Illinois, USA EPI_ISL_19070161
Earliest sequence(without S:N185D): 03-27 Santa Clara, California, USA EPI_ISL_19145504
Latest sequence: 08-25 San Antonio, Texas, USA EPI_ISL_19408671
Regions Detected:
**US** 97(Texas 23, California 15[1 not on GISAID], South Carolina 14, Louisiana 10, Illinois 8, New York 4, Hawaii 3, Colorado 2, Michigan 4, Ohio 2, Connecticut 1, Arizona 1 not on GISAID, DC 1, Delaware 1, Georgia 1, Maryland 1, Mississippi 1, North Carolina 1, Pennsylvania 1, Tennessee 1, Virginia 1, Wisconsin 1), **Canada** 3(BC 2, Saskatchewan 1);
**Denmark** 2, **Spain** 2(Catalunya), **Belgium** 1(Flanders), **France** 1(Bourgogne-Franche-Comté), **Netherlands** 1(Zuid Holland).

EPI_ISL_19214043, EPI_ISL_19214047 and EPI_ISL_19293512 share C2061T and A17697G with other sequences, and have no coverage on S:185. But it's still not sure that if EPI_ISL_19143101 and EPI_ISL_19145504 have S:N185D or not. 

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_65bef_451870.json?c=country&gt=nuc.1314C&label=id:node_7106449
![image](https://github.com/user-attachments/assets/6123c8f6-8eae-422b-9475-f239ec6122f8)

<details><summary>Sequences:</summary>

EPI_ISL_19070161, EPI_ISL_19116334, EPI_ISL_19143101,
EPI_ISL_19145504, EPI_ISL_19155522, EPI_ISL_19168892,
EPI_ISL_19188485, EPI_ISL_19197416, EPI_ISL_19205513,
EPI_ISL_19214016, EPI_ISL_19214043, EPI_ISL_19214047,
EPI_ISL_19216229, EPI_ISL_19223749, EPI_ISL_19224132,
EPI_ISL_19224161, EPI_ISL_19232929, EPI_ISL_19245476,
EPI_ISL_19245500, EPI_ISL_19251035, EPI_ISL_19257071,
EPI_ISL_19258111, EPI_ISL_19261840, EPI_ISL_19262350,
EPI_ISL_19265594, EPI_ISL_19273183, EPI_ISL_19281413,
EPI_ISL_19285254, EPI_ISL_19285928, EPI_ISL_19286121,
EPI_ISL_19286377, EPI_ISL_19286438-19286439, EPI_ISL_19286452,
EPI_ISL_19286529, EPI_ISL_19286567, EPI_ISL_19286727,
EPI_ISL_19286800, EPI_ISL_19287409, EPI_ISL_19290154,
EPI_ISL_19293512, EPI_ISL_19293534, EPI_ISL_19293618,
EPI_ISL_19295220, EPI_ISL_19298224, EPI_ISL_19302502,
EPI_ISL_19302607, EPI_ISL_19303440, EPI_ISL_19304230,
EPI_ISL_19308466, EPI_ISL_19308526, EPI_ISL_19310695,
EPI_ISL_19314232, EPI_ISL_19317468, EPI_ISL_19317741,
EPI_ISL_19317747, EPI_ISL_19317777, EPI_ISL_19317786,
EPI_ISL_19318204, EPI_ISL_19325464, EPI_ISL_19331991,
EPI_ISL_19331993-19331994, EPI_ISL_19332858, EPI_ISL_19334897,
EPI_ISL_19337202, EPI_ISL_19343175, EPI_ISL_19343279,
EPI_ISL_19345038, EPI_ISL_19345041, EPI_ISL_19345043-19345044,
EPI_ISL_19345048, EPI_ISL_19345051, EPI_ISL_19345054-19345055,
EPI_ISL_19345057, EPI_ISL_19345059, EPI_ISL_19345561,
EPI_ISL_19349188, EPI_ISL_19349546, EPI_ISL_19349959,
EPI_ISL_19352806, EPI_ISL_19354372, EPI_ISL_19362207,
EPI_ISL_19364571, EPI_ISL_19365679, EPI_ISL_19365732,
EPI_ISL_19366037, EPI_ISL_19368076, EPI_ISL_19368215,
EPI_ISL_19368810-19368811, EPI_ISL_19375858, EPI_ISL_19378659,
EPI_ISL_19379514, EPI_ISL_19387537, EPI_ISL_19392124-19392125,
EPI_ISL_19394024, EPI_ISL_19405212, EPI_ISL_19405348,
EPI_ISL_19406099, EPI_ISL_19408671, EPI_ISL_19410051,
PQ148034.1, PQ212393.1

</details>

**Comment by FedeGueli** [comment]
> Tree now: [usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2e68e_18f6f0.json?f_userOrOld=uploaded%20sample)  

thanks for sharing interestingly it has as main branch orf1a:A599V awhile XEC main branch has Orf1a:A599T

cc @ryhisner do we know what that residue could mean?

**Comment by FedeGueli** [comment]
This has quite faded away weirdly

**Comment by DailyCovidCases** [comment]
Now 96 seqs with G12014A, G15372T, A22115G

**Comment by FedeGueli** [comment]
One only recent sample maybe time to close this

**Comment by Over-There-Is** [comment]
117

**Comment by Over-There-Is** [comment]
it gets much slower now.

**Comment by xz-keg** [comment]
designated KP.3.1.10

**Comment by FedeGueli** [comment]
> designated KP.3.1.10

Designated KP.3.1.10 via https://github.com/cov-lineages/pango-designation/commit/d39304704862930caed86d10b5785fa1131b2b17
