### ISSUE TITLE
PROPOSAL FOR A NEW SUBLINEAGE OF AY.26.X WITH PRINCIPAL MUTATION IN SPIKE: E484Q,T1009S  IN PERU

### ISSUE THREAD

**Issue by OrsonMM** [cov-lineages/pango-designation#278]
***PROPOSAL FOR A NEW SUBLINEAGE OF AY.26.X WITH PRINCIPAL MUTATIONS IN SPIKE: E484Q,T1009S  
by Group of Genomic Surveillance INS-PERU***

***Description***
Sublineage of: Potencially new sublineage of AY.26.X (S:E484Q,T1009S mutations)
Earliest sequence: hCoV-19/Peru/C03m10/2021 (2021-06-25, Peru)
Most recent sequence: hCoV-19/Peru/LIM-UPCH-1350/2021 (2021-09-16, Peru)
Countries circulating: Peru (31), Chile (1), Spain(1)

***Mutation***

S: E484Q,T1009S

This potentially AY.26.X new sub lineage was detected in capital of Peru in June. Nevertheless, in September increased the frequency.  

![image](https://user-images.githubusercontent.com/12600107/138346447-dd5e6695-a8d3-4974-946b-b305c2f584f5.png)

***Genomes***

[genomes.txt](https://github.com/cov-lineages/pango-designation/files/7392464/genomes.txt)

***Evidence***

![image](https://user-images.githubusercontent.com/12600107/138347106-a95a9a11-617d-433c-b02e-b198e6b137c3.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_427ac_181ea0.json?branchLabel=aa%20mutations&c=userOrOld&label=nuc%20mutations:G26529C&p=full

***Proposed lineage name***

AY.26.X

***COV SPECTRUM*** 

https://cov-spectrum.ethz.ch/explore/Peru/AllSamples/Past6M/variants?aaMutations=S%3AE484Q%2CS%3AT1009S&pangoLineage=AY.26

**Comment by OrsonMM** [comment]
Recent 20 genomes reported for this AY.26 in Peru.

![VariantTimeDistributionChart](https://user-images.githubusercontent.com/12600107/139912933-c728170a-aad3-48d6-a311-5c681caf39c9.png)

![VariantDivisionDistributionChart](https://user-images.githubusercontent.com/12600107/139913330-4d69433b-db7c-4f3d-8bc0-9e9f8793f91c.png)

**Comment by OrsonMM** [comment]
![image](https://user-images.githubusercontent.com/12600107/140667715-dffb2702-c720-4bcc-8590-67852064903a.png)

![image](https://user-images.githubusercontent.com/12600107/140667725-6d54eb74-50f9-4de3-8929-bc0aa297aa49.png)

**Comment by OrsonMM** [comment]
![image](https://user-images.githubusercontent.com/12600107/141808674-cbcff275-aad0-4187-b052-03e1435dea3d.png)


![image](https://user-images.githubusercontent.com/12600107/141809075-a37ed464-1fd4-4a54-91ec-fd71bdb94bb3.png)

**Comment by chrisruis** [comment]
Thanks @OrsonMM We've added this as AY.26.1 in [v1.2.109](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.109) to start on the branch with G23012C (S:E484Q), A24587T (S:T1009S) and C29769T (synonymous)
