### ISSUE TITLE
MC.10+S:A435S,Orf9b:R47H (99 seqs, >10 places)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2781]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1946

MC.10+G22865T,G28423A(Orf9b:R47H,S:A435S)

GISAID query: G22865T, G28423A, C16332T
No. of seqs: 37(USA 14(AZ,CA,IA,MN,NJ,NY,TX) Canada 10(NB,ON,QC) UK 6(England, Scotland) France 3 Germany 1 Denmark 1 Netherlands 1 Singapore 1)

First: EPI_ISL_19361831, USA-MN, 2024-7-26
Latest: EPI_ISL_19423471,USA-IA, 2024-9-14

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/mc_10_a435s.json?label=id:node_5495530)
![image](https://github.com/user-attachments/assets/58e30c00-f802-4b53-922d-a3ab3ad013d1)

**Comment by FedeGueli** [comment]
43, Slovenia

**Comment by Over-There-Is** [comment]
a branch gets S:Q173K now.

**Comment by FedeGueli** [comment]
> a branch gets S:Q173K now.

Query for it: C22079A,G28423A

**Comment by aviczhl2** [comment]
> C22079A,G28423A

still 1 GBW-BBB seq. at least wait for a second single-patient seq.

**Comment by aviczhl2** [comment]
This branch is 76 now and the fastest KP.3.1.1-descendants. @corneliusroemer

**Comment by aviczhl2** [comment]
Crazy 49% advantage against KP.3.1.1 baseline
![image](https://github.com/user-attachments/assets/a321604c-c932-45ff-9e4c-a4fa2e103d40)

**Comment by FedeGueli** [comment]
> Crazy 49% advantage against KP.3.1.1 baseline  

yeah it is the only Kp.3.1.1 that seems being close to XEC and ahead of quite everything else. Also conisdering that partly it depends by New Brunswick Canadian clusters i think it will be fast anyway

**Comment by FedeGueli** [comment]
Also to be noticed the Three GBW from two airports with further S:Q173K (one from Japan)

**Comment by FedeGueli** [comment]
77 Ohio

Ping @corneliusroemer this seems one of the few things able to compete vs XEC a designation is needed because no one is seeing it beyond the restricted variant groups.

**Comment by xz-keg** [comment]
92 seqs now

**Comment by FedeGueli** [comment]
99 Utah, Ontario, Netherlands (2 provinces), Italy

**Comment by FedeGueli** [comment]
131 due to two  Canadian clusters in two different provinces

**Comment by FedeGueli** [comment]
Designated MC.10.1 via https://github.com/cov-lineages/pango-designation/commit/efe8e07488add0710c5a21427ee3737ac5b1c8b9
