### ISSUE TITLE
KP.2.3/KP.3.3 recombinant (40 seqs, 6 places, 22 with S:R346T) 

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2783]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/2049

It seems that a lot of new DeFLiRT+DeFLuQE recombinants are submitted these days.
Among them, this seems a very interesting one, it loses S:R346T during recomb in exchange for S:Q493E, but gains S:R346T independently afterwards. 

KP.2.3--KP.3.3

Breakpoint between 22001 and 22598

Additional mutations: C4891T, C5310T, C6471A,A18642C,del21653_21655

Orf1a:T1682I, T2069N
S:S31-

C4891T, C5310T, C6471A,A18642C,del21653_21655 from a KP.2.3 branch

GISAID query: C4891T, C22000A, G28884C
No. of seqs: 22(USA-CA,UT,TX,NY)

First: EPI_ISL_19339481, Texas, 2024-7-10
Latest: EPI_ISL_19433553, Utah, 2024-9-16

GISAID query for S:R346T sub-branch: C4891T, C22000A, G28884C,G22599C (15 seqs)

Usher places it on a flip-flop reversion branch. It shouldn't have Orf1a:A690V.

https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/kp_2_3_kp_3_3_recomb.json?label=id:node_5516374
![image](https://github.com/user-attachments/assets/20889a97-63e3-4820-832f-4a8288511d52)

**Comment by DailyCovidCases** [comment]
This branch has slowed down a lot now. You can close this issue @aviczhl2

**Comment by FedeGueli** [comment]
Not slow, what we should wait for is for appearing in numbers outside the Utah Cluster.

**Comment by corneliusroemer** [comment]
I don't really trust those Texas/Utah clusters - the losing and regaining S:R346T is a bit add as well. Would only designate if it clearly spreads more widely, with more labs involved.

**Comment by xz-keg** [comment]
27,England.

**Comment by FedeGueli** [comment]
It seems dying off

**Comment by DailyCovidCases** [comment]
Dead please close it

**Comment by xz-keg** [comment]
+1 USA-PA

**Comment by Over-There-Is** [comment]
40 now

**Comment by corneliusroemer** [comment]
XES

**Comment by FedeGueli** [comment]
XES via https://github.com/cov-lineages/pango-designation/commit/173d1b7c5cd537488f7a05e93f2563755e1e8a2e

**Comment by Over-There-Is** [comment]
R346T is 29 now

**Comment by FedeGueli** [comment]
52/29 recent ones worth reopening @xz-keg maybe also a designation ping @corneliusroemer

**Comment by xz-keg** [comment]
> it is XES + 346T 29 recent ones worth reopening @xz-keg maybe also a designation ping @corneliusroemer 3 recent ones got also S:A522P (Query:C1404A, G23126C) one with 445R (Query:G8179A, 22896G,T5347C, C28896T)

Yeah this lose-and-regain is quite interesting. Also happens in XDY which loses R346T during recomb and regains it in a branch afterwards.

**Comment by FedeGueli** [comment]
31 for 346T

**Comment by FedeGueli** [comment]
> 31 for 346T 4 for A522P

37/8 now

**Comment by FedeGueli** [comment]
40/10 @xz-keg please reopen or set a new proposal in the secondary repo!

**Comment by FedeGueli** [comment]
> it is XES + 346T 29 recent ones worth reopening [@xz-keg](https://github.com/xz-keg) maybe also a designation ping [@corneliusroemer](https://github.com/corneliusroemer) 3 recent ones got also S:A522P (Query:C1404A, G23126C) one with 445R (Query:G8179A, 22896G,T5347C, C28896T)

S:A522P is now designated XES.1.1 via https://github.com/cov-lineages/pango-designation/commit/e21eefc8713a1904d0d11a9409633fdb925eaf3a
