### ISSUE TITLE
New KP.3.2 + S:S31del emerged recently (59, >10 places, first sampled in India)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2784]
Originally posted in https://github.com/sars-cov-2-variants/lineage-proposals/issues/2081

There is a another recent DeFluQe branch that seems expanding recently
KP.3.2 >> C18981T > C21590T > S:S31del (del21653-55), C14790T then C23086T (not present in all samples)
Query: C18981T, T3565C,C14790T
Samples: 34
Places: 7
First sample collected on 2024-07-10 in a traveler from India (GBW)

Tree:
<img width="1175" alt="Screenshot 2024-09-23 alle 14 28 23" src="https://github.com/user-attachments/assets/8155348b-7203-4b3a-adaf-96db2b1f184a">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_c560_15cb80.json?branchLabel=nuc%20mutations&label=id:node_7082742

Samples:
EPI_ISL_19279964, EPI_ISL_19312927, EPI_ISL_19318422,
EPI_ISL_19331311, EPI_ISL_19353260, EPI_ISL_19359729,
EPI_ISL_19359746, EPI_ISL_19359766, EPI_ISL_19359775,
EPI_ISL_19359777, EPI_ISL_19359784, EPI_ISL_19366206,
EPI_ISL_19372984, EPI_ISL_19375523, EPI_ISL_19375612,
EPI_ISL_19375655, EPI_ISL_19380301, EPI_ISL_19383907,
EPI_ISL_19384424, EPI_ISL_19384427, EPI_ISL_19384439,
EPI_ISL_19391428, EPI_ISL_19416884, EPI_ISL_19418948,
EPI_ISL_19418962, EPI_ISL_19420706, EPI_ISL_19420778,
EPI_ISL_19427800, EPI_ISL_19427848, EPI_ISL_19427923,
EPI_ISL_19427928, EPI_ISL_19427931, EPI_ISL_19431372,
EPI_ISL_19431637, EPI_ISL_19432460

**Comment by FedeGueli** [comment]
+2 Sweden

**Comment by FedeGueli** [comment]
41 new countries Australia, France 
ping @corneliusroemer this is interesting

**Comment by FedeGueli** [comment]
44 , Denmark

**Comment by FedeGueli** [comment]
51

**Comment by FedeGueli** [comment]
54

**Comment by xz-keg** [comment]
designated KP.3.2.8

**Comment by FedeGueli** [comment]
> KP.3.2.8

via https://github.com/cov-lineages/pango-designation/commit/b1e238c06bee3b81c2215478df708a0db6ca1e05#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1289
