### ISSUE TITLE
KS.1.1.1+S:R190S (41 seqs, >10 places, >50% Uzbekistan)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2785]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1995

There is a Orf1a:N470T sub-branch of KS.1.1 that most of the seqs are placed elsewhere by usher. Now that branch has a S:R190S sub-branch. 

Most of the seqs of this branch comes from Uzbekistan, where most seqs have S:22 missing coverage, making the usher tree very messy for this branch. @AngieHinrichs 

KS.1.1+A1674C(Orf1a:N470T)+G22132T(S:R190S)

GISAID query: G22132T,A1674C
Supplementary query 1: G5180A,-22132, A1674C
Supplementary query 2: G5180A, G22132T,-A1674C,G24821T
There exists another 8 Uzbekistan seqs belonging to this branch by usher but cannot be caught via above queries.

No. of seqs: 26( Uzbekistan 18 Russia 1 USA 6(NY,DE, GBW from Turkey) Israel 1)
First: EPI_ISL_19347169, USA-DE, 2024-7-30
Latest: EPI_ISL_19427567, USA-NY, 2024-9-10

18/33 of the most recent Uzbekistan batch belong to this.

All seqs with Orf1a:A470T shall belong to this branch and have S:T22N.
[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/ks_1_1_r190s.json?gt=ORF1ab.470T&label=id:node_5766455)
![image](https://github.com/user-attachments/assets/5646fd38-f58e-4f49-ac16-9fda811842f8)

**Comment by FedeGueli** [comment]
+1 Germany

**Comment by aviczhl2** [comment]
30, Denmark

**Comment by FedeGueli** [comment]
Orf1a:N470T  minor typo in the title and in the proposal

**Comment by aviczhl2** [comment]
34, USA-OH, Netherlands

**Comment by xz-keg** [comment]
+1 Sweden

**Comment by Over-There-Is** [comment]
38

**Comment by xz-keg** [comment]
41, Georgia

**Comment by FedeGueli** [comment]
parent with Orf1a:N470T ahead is KS.1.1.1 now via https://github.com/cov-lineages/pango-designation/commit/c542eb9c3b5805a189bb9c314dce67744b27ba1e

**Comment by FedeGueli** [comment]
the sub branch with S:R190S designated NC.1 via https://github.com/cov-lineages/pango-designation/commit/0b0224984b86d81defa672fc45c6f85059176b0a
