### ISSUE TITLE
JN.1*/LF.1.1.1 recombinant(91 seqs,>10 places, 40% in St Petersburg in September )

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2786]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1984

There seems to be an LF.1.1.1 branch that loses Orf1a mutations due to recombinant.

JN.1--LF.1.1.1

Breakpoint between 6574 and 16550

It is basically LF.1.1.1 losing G4067A and C6573T. It keeps C16551T and C18912T and T19209C

GISAID query: C16551T, C18912T, T19209C, -4067, -6573
No. of seqs: 91(Canada 2 Denmark 1 Egypt 1 France 4 Germany 1 USA 4(CA,GA,NY,GBW from Egypt) UK 1 Sweden 1 Russia 76(BA,KDA,KHA,ME,MO,MOS,PRI,SPE,TA,TAM,YAN))

First: EPI_ISL_19231765, Russia-Kazan, 2024-4-30
Latest: EPI_ISL_19434591, Russia-St. Petersburg, 2024-9-4

5/13=40% in St. Petersburg samples collected in Sep.
[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/jn_1_lf_1_1_1_recomb.json?label=id:node_5592495)
![image](https://github.com/user-attachments/assets/ff800afa-c9fa-4f26-a8b6-5986ebacff86)

**Comment by DailyCovidCases** [comment]
@corneliusroemer 3 weeks without designation now, please designate some variants in https://github.com/cov-lineages/pango-designation/issues

**Comment by FedeGueli** [comment]
XEJ via https://github.com/cov-lineages/pango-designation/commit/1a23ef0ca3b0ed60b3b2e321ab8c90e5c94d84fa
