### ISSUE TITLE
XDV.1.5+8-nuc,6-aa including S:F59S(37 seqs, >10 places, 7% Hubei, 22 with S:T22N)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2788]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1840

XDV.1.5+C4683T,T15573C(Orf1a:A1473V)+C3686T, G25793A(Orf1a:H1141Y,Orf3a:R134H)+A8390G, C12854T, T21738C, C25671T(Orf1a:I2709V, P4197S,S:F59S)+C21627A(S:T22N)

GISAID query:C12473T, T21738C, C25671T
GISAID query for S:T22N sub-branch: C12473T, T21738C, C25671T,C21627A
No. of seqs:11(Canada 1 Singapore 2 China 5(Hubei-Shiyan,Jingzhou,  Hong Kong, 1 from Thailand) USA 3(GBW from China and Netherlands))

First: EPI_ISL_19297920, Canada, 2024-7-17
Latest: EPI_ISL_19437425, Hong Kong, 2024-9-13

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/xdv_1_5_f59s.json?label=id:node_5647598)
![image](https://github.com/user-attachments/assets/cf5c76e5-078f-4b22-9bca-ef845587de8b)

**Comment by FedeGueli** [comment]
@aviczhl2 could you add please the query for S:T22N or do you think it is present in all the sequences and just dropped out in the three without it?

**Comment by aviczhl2** [comment]
> @aviczhl2 could you add please the query for S:T22N or do you think it is present in all the sequences and just dropped out in the three without it?

Added. Sorry I forgot it.

**Comment by FedeGueli** [comment]
> > @aviczhl2 could you add please the query for S:T22N or do you think it is present in all the sequences and just dropped out in the three without it?
> 
> Added. Sorry I forgot it.

Thx!

**Comment by aviczhl2** [comment]
Also in Shanxi

**Comment by FedeGueli** [comment]
15!

**Comment by FedeGueli** [comment]
17 Japan Netherlands

**Comment by FedeGueli** [comment]
ping @corneliusroemer this could be seriously fast.

**Comment by FedeGueli** [comment]
20, 12 with T22N , 
3 new GBW samples the 2 not pooled from China

**Comment by xz-keg** [comment]
+1 GBW from China, it has 12854 dropout, edit query to include this.

**Comment by FedeGueli** [comment]
> +1 GBW from China, it has 12854 dropout, edit query to include this.

Thanks a lot

**Comment by xz-keg** [comment]
+1 Singapore with additional S:P85L and S:P1263L

**Comment by FedeGueli** [comment]
@corneliusroemer

**Comment by xz-keg** [comment]
+1 South Korea

**Comment by xz-keg** [comment]
+3 Heilongjiang

**Comment by xz-keg** [comment]
+8 from Hubei

**Comment by FedeGueli** [comment]
> +8 from Hubei 8/113 in Hubei seqs after 9/15.

As expected and discussed among us it is going up quite fast!

**Comment by DailyCovidCases** [comment]
@corneliusroemer This branch is growing rapidly now:
![Screenshot (263)](https://github.com/user-attachments/assets/f518c196-c9f5-42d6-842b-fc6712cc8f53)

**Comment by FedeGueli** [comment]
Designated NB.1 via https://github.com/cov-lineages/pango-designation/commit/0c2adb7665ed02bd195a6d7d19265874e2758616
