### ISSUE TITLE
PROPOSAL FOR A SUBLINEAGE OF AY.102 WITH S:G446V, ORF3A:G100C MUTATIONS 

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#279]
**PROPOSAL FOR A SUBLINEAGE OF AY.102 WITH S:G446V, ORF3A:G100C MUTATIONS 
BY GROUP OF GENOMIC SURVEILLANCE INS-PERU**

**Description**
**Sublineage of:** Potencially new sublineage of AY.102 (S:G446V, Orf3a:G100C mutation
**Earliest sequence**: hCoV-19/Peru/ARE-UNSA-2754/2021 (2021-07-26, Peru)
**Most recent sequence**: hCoV-19/Peru/ARE-INS-8775/2021 (2021-10-18, Peru)
**Countries circulating**: Perú (18)
This potentially AY.102 new sublineage was detected in 18 genomes and has
ORF1ab:M2036V, S:G446V and ORF3a:G100C  mutations,  principally distributed in Arequipa, Peru

**Genomes**

[genomes1.txt](https://github.com/cov-lineages/pango-designation/files/7557569/genomes1.txt)

**Evidence**

![G446V](https://user-images.githubusercontent.com/87997149/142268618-b982e8e2-d19e-43ed-8754-31a65affd5c5.png)

![G446V2](https://user-images.githubusercontent.com/87997149/142268634-f85b36b1-fc44-4c08-8e03-53af72cfc360.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_24db9_51f0e0.json?branchLabel=aa%20mutations&c=userOrOld&label=nuc%20mutations:G1495T,A27690T

**Proposed lineage name**
**AY.102.X**

**Comment by chrisruis** [comment]
Thanks @LuisBarcenaF It looks like this clade still has very few sequences so isn't large enough for a lineage designation at this stage
