### ISSUE TITLE
KP.X (KP.1.1.3/KP.3.1.1 recomb?): S:∆S31, R346T, Q493E, ORF6:L61I, N:R413L (23 seqs, 3 countries, dying branch)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2790]
**Description**
**Sub-lineage of:** KP.X (unclear, probably KP.1.1.3/KP.3.1.1 recomb)
**Earliest sequence:** 2024-7-9, USA, New York – EPI_ISL_19277804
**Most recent sequence:** 2024-9-9, USA, Utah – EPI_ISL_19433572
**Continents circulating:** North America (22), Europe (1)
**Countries circulating:** USA (19) Canada (3), England (1)
**Number of Sequences:** 23
**GISAID Nucleotide Query:** C4999T, G27382A, G29511T
**CovSpectrum Query:** Nextcladepangolineage:JN.1** & [4-of: S:S31del, C499T, G22599C, C23039G, C27382A, G29511T] 
**Substitutions on top of KP.X:**
**Spike:** ∆S31, R346T, Q493E
**N:** R413L
**ORF6:** L61I

**Nucleotide:** C4999T, ∆21653-21655, G22599C, C23039G, C27382A, G29511T

**USHER Tree**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_974b_1803c0.json?c=gt-ORF6_61&gmax=27387&gmin=27202&label=id:node_7038322
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/24610f1f-53c9-4064-80ce-5c53127ca768">

**Evidence**
Not a very exciting branch, to tell the truth, and likely near dead. 

EDIT: apparently a recombinant most likely. Not sure it matters as this thing seems likely to go extinct any day now.

It's not clear to me which KP* lineage this belongs to. It has S:∆S31 and S:Q493E but not ORF1a:S4286C. It also has S:R346T, which is rare in KP.3. 

It has S:∆S31, S:R346T, and C4999T, which are all in KP.1.1.3, but it does not have S:K1086R. 

It also has two mutations found in very few JN.1* sequences over the past 2-3 months—ORF6:L61I (C27382A) and N:R413L (G29511T). Usher puts it in an artifactual branch full of environmental samples from Germany. 

Nextclade calls it KP.2, but that seems wrong. Seems it could very well have emerged from the KP* polytomy.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19277804, EPI_ISL_19311262, EPI_ISL_19312228,
EPI_ISL_19317065, EPI_ISL_19321574, EPI_ISL_19330042,
EPI_ISL_19340296, EPI_ISL_19343129, EPI_ISL_19343224,
EPI_ISL_19344062, EPI_ISL_19358024, EPI_ISL_19358663,
EPI_ISL_19360364, EPI_ISL_19362073, EPI_ISL_19376515,
EPI_ISL_19377374, EPI_ISL_19408485, EPI_ISL_19416777,
EPI_ISL_19416949, EPI_ISL_19420047, EPI_ISL_19425340,
EPI_ISL_19428039, EPI_ISL_19433572
</details>

**Comment by FedeGueli** [comment]
pfrom https://github.com/sars-cov-2-variants/lineage-proposals/issues/1838

**Comment by corneliusroemer** [comment]
@AngieHinrichs could you maybe remove all sequences that start with `env/`? These are often full of artifactual reversions and are rarely helpful while causing all sorts of tree issues.

**Comment by ryhisner** [comment]
> @AngieHinrichs could you maybe remove all sequences that start with `env/`? These are often full of artifactual reversions and are rarely helpful while causing all sorts of tree issues.

If possible, doing the same for pooled Ginkgo Bozoworks (GBW) sequences would be great as well. They always have GBW-GKPLAAA somewhere in the sequence name whereas the individual GBW sequences have GBW-GKISBBB. 

It would be even better if GBW stopped uploading pooled sequences in violation of GISAID rules—better still if the US federal government stopped paying this incompetent, clownish company to do a job it has proven incapable of doing correctly or well for years now.
