### ISSUE TITLE
 Recombinant of KP.1.1  + Orf1b:L2213F + S:N185del+S:F186I (#2649) that acquired in a stepwise manner S:S31F S:K478T (rev) before recombination. Then with recombination it lost S:K1086R and acquired S:T22N (20, 9 places including India,Hawaii,Singapore) 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2791]
This a sub branch of #2649 that got 31F 478T then recombined with KP.2* losing S:K1086R  (defining of KP.1.1) and acquiring then S:T22N . _Full credit for the analysis by @aviczhl2 that had proposed the parental branch long ago._
 

Recombinant of #2649 [KP.1.1> Orf1b:L2213F (C20104T)> S:N185Del/S:F186I  >> S:S31F (C21654T) > S:K478T (A22995C rev) ] >> recombination: >S:R1086K (G24819A rev), C25587T, Orf3a:T268M (C26195T), A26927G > T10093G, S:T22N (C21627A), Orf3a:V13L (G25429T)
Query for the recombinant branch: C25587T, C26195T,A26927G  (by @aviczhl2 )
Samples: 8
 
Places: 5 [India 2, Germany Australia and a GBW pooled sample]
Tree updated on Oct 10:
<img width="1169" alt="Screenshot 2024-10-10 alle 11 52 12" src="https://github.com/user-attachments/assets/6a359670-fc77-4cd8-9093-b71c79ee0842">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_42d49_7a15c0.json?label=id:node_7351958

Singlet from Pa,Us with three spike mutations S:A263S, S:D428H ,S:T500N 
Query: T8902C, G17035A

**Comment by FedeGueli** [comment]
Wrong repo i will leave this open for a while.

**Comment by aviczhl2** [comment]
This is sub-branch of #2649, and have S:185del, S:F186I.

**Comment by aviczhl2** [comment]
I think it shall be recombinant with other KP* as S:1086 is reverted.

**Comment by FedeGueli** [comment]
> I think it shall be recombinant with other KP* as S:1086 is reverted. (breakpoint shall be after S:186 as it inherits the S:185del, F186I from #2649.)

Very good spot for some reason i didn't notice that del so no light turned on my mind and also i didnt found any KP.1.1 matching with this, my bad! likely i was focusing on S:S31F.
As this point  it is better to broaden the original proposal with this and i will close this. let me know.

**Comment by aviczhl2** [comment]
All 3 on the recomb branch shall have S:T22N(the Germany one has S:22 missing coverage), actually we get 5 using query C25587T, C26195T,A26927G. The other 2 India seqs are removed by usher due to too many reversions.

**Comment by aviczhl2** [comment]
Maybe better keep this open for a 5-seq recomb branch with 2 from India? It deserves a separate proposal.

**Comment by FedeGueli** [comment]
> Maybe better keep this open for a 5-seq recomb branch with 2 from India? It deserves a separate proposal.

Ah so u want to keep it in both ok! i was thinking it was absorbed. So what it the query for the recombinant ?
C25587T, C26195T,A26927G
3/5 with 22N right?

**Comment by aviczhl2** [comment]
> Ah so u want to keep it in both ok! i was thinking it was absorbed. So what it the query for the recombinant ? C25587T, C26195T,A26927G 3/5 with 22N right?

All shall have S:T22N, the other 2 has S:22 missing coverage I think?

**Comment by FedeGueli** [comment]
> > Ah so u want to keep it in both ok! i was thinking it was absorbed. So what it the query for the recombinant ? C25587T, C26195T,A26927G 3/5 with 22N right?
> 
> All shall have S:T22N, the other 2 has S:22 missing coverage I think?

let me check i ve edited the proposal please check if i got your analysis right)

**Comment by FedeGueli** [comment]
> C25587T, C26195T,A26927G

Ok one from India has coverage but i assume can be just base calling. so i will modify further

**Comment by FedeGueli** [comment]
Ping: @corneliusroemer if interested  this should be designated with a chain of designations involving #2649 its sublineage with 31F adn 478T and its recombinant proposed here. not designating all of them but just one could be very messy then

**Comment by FedeGueli** [comment]
6 , new place Penn.(US)

**Comment by FedeGueli** [comment]
+1 Hawaii

**Comment by FedeGueli** [comment]
8, Utah

**Comment by xz-keg** [comment]
+4 Singapore

**Comment by FedeGueli** [comment]
The sample from Pennsylvania has three additional spike mutations: S:A263S, D428H,T500N

**Comment by FedeGueli** [comment]
> +1 Qatar, 13 seqs now

boom quit e a thing this one too! i have the feeling that we are now facing the heavy weights of Jn.1 evolution and timing for them is quite perfect

**Comment by xz-keg** [comment]
+1 USA-NJ, 14 total

**Comment by xz-keg** [comment]
one more from Qatar

**Comment by FedeGueli** [comment]
The club of little fast lineages stil undesignated is going at fast pace. Hope they wil be designated soon. Most of people is not even aware of all of them.

**Comment by xz-keg** [comment]
More seq from Qatar, 16 now.

**Comment by xz-keg** [comment]
One more of this from Taiwan

**Comment by FedeGueli** [comment]
Taiwan but infected elsewhere, this is fast.

**Comment by xz-keg** [comment]
+1 Canada-SK, 18 seqs now

**Comment by xz-keg** [comment]
+1 Singapore

**Comment by xz-keg** [comment]
+! Japan, 20 now.

**Comment by FedeGueli** [comment]
4 new sequences from Indonesia (one from an airport in Japan) , i suiggest to change the query: T10093G  ,C20104T

**Comment by xz-keg** [comment]
@AngieHinrichs usher has moved the placement of XEN and there seems to be a new bug of its placement.

Everything on the image shall be XEN, instead of only the top branch. 

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice189_genome_test_29969_21df80.json?label=id:node_5873219
![image](https://github.com/user-attachments/assets/4a1b3757-c4ea-455f-814f-797bf0902c00)
