### ISSUE TITLE
MC.1 subbranch with S:A942S (98 seqs, 13 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2794]
Transferred from sars-cov-2-variants/lineage-proposals#1932.
MC.1> C13297T> C14220T> G24386T(S:A942S)
Query: C8293T, C13297T, G24386T

Earliest sequence: 07-16 California, US (from Serbia) EPI_ISL_19289846
Latest sequence: 09-18 Kobe City, Hyogo Prefecture, Japan EPI_ISL_19437550
Regions detected: 
**France** 9(ARA 7, GES 1, HDF 1), **Ireland** 9(Limerick 6, Galway 3), **Spain** 4(Catalunya), **Denmark** 2, **Germany** 2(Bayern 1, Berlin 1), **UK** 2(Scotland), **Sweden** 1(Stockholm);
**US** 8(California 2[1 from **Serbia**], NY 2, Massachusetts 1, Arizona 1 not on GISAID, Ohio 1, Utah 1), **Canada** 3(BC 2, Alberta 1);
**Australia** 8(SA);
**Japan** 3(Kanagawa 1, Tokyo 1, Hyogo 1).

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_44a54_8eaa30.json?c=country&label=id:node_7209860
![image](https://github.com/user-attachments/assets/1fb2bb17-cbfa-4eb4-9484-0ab48b545543)

<details><summary>Sequences:</summary>

EPI_ISL_19289846, EPI_ISL_19308141, EPI_ISL_19312018,
EPI_ISL_19316977, EPI_ISL_19327643, EPI_ISL_19337445,
EPI_ISL_19338901, EPI_ISL_19357447-19357448, EPI_ISL_19357491,
EPI_ISL_19357504, EPI_ISL_19361195, EPI_ISL_19365422,
EPI_ISL_19371410, EPI_ISL_19372299, EPI_ISL_19372301,
EPI_ISL_19372977, EPI_ISL_19374161, EPI_ISL_19389107,
EPI_ISL_19390689, EPI_ISL_19391164, EPI_ISL_19394788,
EPI_ISL_19408922, EPI_ISL_19409100, EPI_ISL_19409781,
EPI_ISL_19415666, EPI_ISL_19420948, EPI_ISL_19423370,
EPI_ISL_19425667, EPI_ISL_19429203, EPI_ISL_19430551,
EPI_ISL_19433899-19433902, EPI_ISL_19433906, EPI_ISL_19434283,
EPI_ISL_19434310, EPI_ISL_19434317, EPI_ISL_19434321,
EPI_ISL_19434329, EPI_ISL_19434332, EPI_ISL_19434346,
EPI_ISL_19434350, EPI_ISL_19437550, EPI_ISL_19437753,
EPI_ISL_19441241, EPI_ISL_19441323, EPI_ISL_19441338,
EPI_ISL_19443887, PQ387847.1
</details>

**Comment by FedeGueli** [comment]
54

**Comment by DailyCovidCases** [comment]
55 seqs, please update the title @Over-There-Is

**Comment by FedeGueli** [comment]
68 with batches from Wales and Australia uploaded today

**Comment by Over-There-Is** [comment]
75 now

**Comment by FedeGueli** [comment]
This one of the fastese Kp.3.1.1

**Comment by xz-keg** [comment]
designated MC.1.1

**Comment by FedeGueli** [comment]
> designated MC.1.1

via https://github.com/cov-lineages/pango-designation/commit/81c3b2dea03e3b95901ec189c8694b58926c8783
