### ISSUE TITLE
KP.3.1.1 plus S:A435S (79 seqs, > 15 Places, 4 continents)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2798]
S:A435S is one of the few convergent RBD mutations appearing after FLirt/FViRT and 493E  , together with 478X and 445X

And the still undesignated MC.10 branch appears to be fast and to be not far from XEC,
This is the other KP.3.1.1 branch with it formerly tracked in https://github.com/sars-cov-2-variants/lineage-proposals/issues/2077: it appears to be very recent it would be good to designate both of them

KP.3.1.1 > C829T > C12076T > S:A435S (G22865T)
Query: C829T, C12076T ,G22865T
Samples: 20
Places: 11 (Australia- 2 states, NZL, Singapore,Japan, France- 3 regions, Portugal, Netherlands, Sweden, US, England, Denmark,)
First collected on 2024-07-07 in Vermont, US
Tree:
 <img width="1167" alt="Screenshot 2024-10-06 alle 15 37 23" src="https://github.com/user-attachments/assets/5397a5c3-9a3b-4a5a-8c0a-c2a1a6abdb60">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5fad8_291a50.json?label=id:node_7205213

Interestingly the tree seems split in two main branches one expanding from Oceania, the other from Europe w C14925T

Edited: in the Australian branch there is a small cluster of two with S:V382L query G22706T, C18491T

**Comment by FedeGueli** [comment]
24

**Comment by FedeGueli** [comment]
31 Australia France (Batch)

**Comment by corneliusroemer** [comment]
MC.10.1 I think

**Comment by Over-There-Is** [comment]
40 now

**Comment by FedeGueli** [comment]
51 with new samples from Australia too

**Comment by FedeGueli** [comment]
53 Germany it seems growing quite fastly now

**Comment by FedeGueli** [comment]
62 new country Finland this tha likely em erged in France seems doing well in Northern Europe and Oceania. cc @corneliusroemer

**Comment by FedeGueli** [comment]
72 France Germany Denmark

**Comment by FedeGueli** [comment]
Added a tracking for a small branch from Australia with S:V382L Query : G22706T, C18491T

**Comment by FedeGueli** [comment]
79 now in 15 countries

**Comment by FedeGueli** [comment]
Designated MC.21.1 via https://github.com/cov-lineages/pango-designation/commit/dc17e540887751f51bab8e761dc223fe01657467#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1281
