### ISSUE TITLE
Sublineage of P.1 focused in Europe

### ISSUE THREAD

**Issue by rambaut** [cov-lineages/pango-designation#28]
Distinct sublineage of P.1 (originally focused in Manaus, Brazil). Predominantly in Italy, but also Germany.
<img width="809" alt="image" src="https://user-images.githubusercontent.com/686405/110512804-743a6f80-80fd-11eb-90c6-27f67cbd6491.png">

One synonymous SNP separates these from P.1 but one Italian genome contains spike P681H (Italy/EMR-064126-004/2021, EPI_ISL_1132668).

Genome list:
[P.1.1.txt](https://github.com/cov-lineages/pango-designation/files/6110448/P.1.1.txt)

Lineage designation: P.1.1

**Comment by AngieHinrichs** [comment]
113 of the 114 sequences have T13851C -- only Italy/ABR-IZSGC-100427/2021 does not have T13851C.  It's Italian and P.1-ish, but does it really belong in P.1.1?  

So why is it getting pulled down into the same branch of your tree as Italy/CAM-AMES-7-91/2021 & similar?  Aside from P.1. mutations and T13851C, that node seems to have only C24919T and C23643T.  Italy/ABR-IZSGC-100427/2021 has C24919T -- but not C23643T (nor S:18F/C21614T & S:20N/C21621A from P.1), and it has several mutations not seen in any of the other 113 (C601T, G954A, A6098T, C6982T, A12485T, T22270C;  it has T21638C in common with Italy/TUS-Siena19/2021 only, but that one clusters with the German sequences).

It wouldn't ruin things to include Italy/ABR-IZSGC-100427/2021 but it probably wouldn't hurt to omit it either.  :)  It would be a bit tidier.

**Comment by rambaut** [comment]
`Italy/ABR-IZSGC-100427/2021` is 10% Ns - I suspect it is missing some key mutations. We will be introducing some filtering steps so that lower-coverge genomes are not used to define lineages.

**Comment by rambaut** [comment]
I can confirm - `Italy/ABR-IZSGC-100427/2021` has a long tract of Ns across 13851 but is being brought into the P.1.1 lineage by the C24919T which it shares with others in that bottom part of the tree.

**Comment by AngieHinrichs** [comment]
> I can confirm - Italy/ABR-IZSGC-100427/2021 has a long tract of Ns across 13851

Sorry I missed that!  Makes sense, thanks.

**Comment by chrisruis** [comment]
Now added as lineage P.1.1
