### ISSUE TITLE
Proposal for Peruvian Delta sublineage with S:T51I, S:I850V and ORF1a:K856R

### ISSUE THREAD

**Issue by OrsonMM** [cov-lineages/pango-designation#280]
***PROPOSAL FOR A NEW SUB LINEAGE ACTUALLY CLASSIFIED LIKE AY.4 WITH PRINCIPAL MUTATION IN SPIKE: T51I,I850V AND ADDITIONAL IN 100% OF PERUVIAN GENOMES WITH ORF1ab:K856R
by Group of Genomic Surveillance INS-PERU***

***Description***

Sub-lineage of: Potentially new sub lineage of Delta 

S: T51, I850V
ORF1ab: K856R, present in Peru (100% samples) and one genome in France

Earliest sequence: hCoV-19/Russia/SPE-RII-36296S/2021 (2021-06-02, Russia)  

Most recent sequence: hCoV-19/Peru/CUS-UPCH-1389/2021 (2021-09-20, Peru)

Countries circulating: Rusia (4), Switzerland (6), France (1), Peru (24)

This potentially Delta sub lineage was reported first in Russia and other European countries with mutation in spike T51 and I850V.  In Peru, the detection of genomes carried additional mutational in ORF1ab: K856R and is spread pronominally in Cusco Peru. We think that these genomes are misclassified as AY.4 because not have C7851T, probably it is a new AY.X

***Mutations***

S: T51, I850V
ORF1ab: K856R (100% Peru and one genome in France)

***Genomes***

[Genomes_AY.4.txt](https://github.com/cov-lineages/pango-designation/files/7392550/Genomes_AY.4.txt)

***Evidence***

![image](https://user-images.githubusercontent.com/12600107/138348612-7eb50d86-d7be-4b04-882c-5bb8719026ad.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_35333_82d00.json?c=userOrOld&label=nuc%20mutations:C8986T,G9053T,A11201G,A11332G

***Proposed lineage name***
AY.X

***covSPECTRUM***

https://cov-spectrum.ethz.ch/explore/Peru/AllSamples/Past3M/variants/international-comparison?aaMutations=S%3AT51%2CS%3AI850V%2CORF1a%3AK856R

**Comment by OrsonMM** [comment]
![image](https://user-images.githubusercontent.com/12600107/140324931-c915eb96-1715-465b-96f7-129a03d07b47.png)

**Comment by OrsonMM** [comment]
Actually is clasified by Pango like AY.122.  And more cases were reported. 

![233](https://user-images.githubusercontent.com/12600107/144277339-4a6804da-514e-45b1-8d0a-40807cc36789.png)

**Comment by chrisruis** [comment]
This clade is indeed part of AY.122. It currently contains too few sequences to designate so we haven't designated this at this stage. Thanks @OrsonMM for submitting
