### ISSUE TITLE
KP.4.1 got Deflirt and it is still circulating in three continents in September (79, >10 places including Iraq) with a recent minibranch adding S:T22N (2, Australia, QLD)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2800]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/2128

This went unnoticed ( or we confounded it with KP.4.1.3) maybe due the fact Usher puts it under S:S31F but instead all the sequences have S:S31del.
It managed to fly under the radar until September when it was samples 5 times from three continents (Australia, France, Spain, Florida) 
Interestingly it is converging now toward S:T22N with a mini branch sampled in Australia in September

KP.4.1 > S:S31del (del21653-55)
Query:   G26918A,del21653,T3565C
Samples: 62
Countries: 14 countries including Iraq
Query for S:T22N subbranch:T7061C, C7482T, G19656A
Tree:
<img width="1162" alt="Screenshot 2024-10-07 alle 19 35 32" src="https://github.com/user-attachments/assets/43ee53a7-a336-4bd5-a0b2-a1a0f89d3d1f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_16eb4_416c90.json?label=id:node_7190898

**Comment by FedeGueli** [comment]
70

**Comment by DailyCovidCases** [comment]
@FedeGueli Dead please close it

**Comment by FedeGueli** [comment]
79 likely dying off
