### ISSUE TITLE
LF.7.1+S:A475V(35 seqs, 4 places, 45% Qatar)

### ISSUE THREAD

**Issue by xz-keg** [cov-lineages/pango-designation#2805]
From branch 2 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/2067

There seems to be a very recent new LF.7+S:A475V branch growing in Qatar. 

@FedeGueli  analyse:

> Qatar wasnt uploading anything in August and months before leaves us uncertainties about what is going on there.
> Then it suddenly starts uploads seqs. And this lineage quickly climbs up the proportion.
> 1-9 sept: 14%

> 10-19 sept: 30%
> 20-30 sept: 42%
> 1-10 october: 44%
> 

So this branch seems growing really fast in Qatar, given nearby countries don't upload anything we don't know how prevalence it is outside Qatar, 
LF.7+C6310T+C22986T(S:A475V)

GISAID query: C6310T, C22986T,t3565C,-22111
No. of seqs: 24(Qatar 23 USA 1(GBW from Qatar))

First: EPI_ISL_19475572, 2024-9-16, Qatar
Latest: EPI_ISL_19470004, 2024-10-4, Qatar

[usher](https://nextstrain.org/fetch/graw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/lf_7_a475v.json?label=id:node_5795935)
![image](https://github.com/user-attachments/assets/f9d4f3de-5259-45be-8b3d-fadd9bd73431)

**Comment by xz-keg** [comment]
More seqs from Qatar, making it 31.

**Comment by FedeGueli** [comment]
> More seqs from Qatar, making it 31.

I re did the maths:
1-9 sept: 14%
10-19 sept: 30%
20-30 sept: 42%
1-10 october: 44%

**Comment by FedeGueli** [comment]
33 Netherlands

**Comment by DailyCovidCases** [comment]
Grow advantage now:
![Screenshot (268)](https://github.com/user-attachments/assets/8941808e-8ecd-44c8-9fdb-0ad3b16242e6)

**Comment by xz-keg** [comment]
+1 Wales

**Comment by FedeGueli** [comment]
> 33 Netherlands

i have 34 for this, do you exclude one sequence?

**Comment by xz-keg** [comment]
> > 33 Netherlands
> 
> i have 34 for this, do you exclude one sequence?

yeah one seems to be LB.1

**Comment by xz-keg** [comment]
+2 GBW from South Africa

**Comment by FedeGueli** [comment]
Designated LF.7.1.2

**Comment by FedeGueli** [comment]
Now its main sublinegae with N:T379I is named NT.1 while LF.7.1.2 stands for 475V ahead .
