### ISSUE TITLE
Delta 21J sublineage with ORF1a:2967I & ORF1a:3353R (50% in Costa Rica/Guatemala, 5% Mexico, 1% USA/Spain)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#281]
New lineage proposal
by @CorneliusRoemer [after tip off from @gerstung-lab about nuc:15240T branch]

Description
Sub-lineage of: B.1.617.2 (21J)
Earliest sequence: March to June 2021 in Peru/Chile
Most recent sequence: 2021-17 USA, 2021-23 Costa Rica
Countries circulating: 50% in Costa Rica/Guatemala, 5% Mexico, 1% USA/Spain,

Lineage deriving from 21J Delta, on the nuc:15240T branch with defining mutations ORF1a:2967I andORF1a:3353R

![image](https://user-images.githubusercontent.com/25161793/138349224-dff2bb09-767a-413e-912c-faabfd09f14b.png)
https://nextstrain.org/groups/neherlab/ncov/na-costa-rica?branchLabel=aa&c=gt-nuc_9165,10323

![image](https://user-images.githubusercontent.com/25161793/138349277-2fb85ece-11ee-4316-8b0f-e14ad80cfc22.png)

![image](https://user-images.githubusercontent.com/25161793/138349304-7196d202-414c-4e17-b5ca-7c20f151783e.png)

Country | Total Variant Sequences | First seq. found at | Last seq. found at
-- | -- | -- | --
United States | 2832 | 2021-17 | 2021-41
Costa Rica | 197 | 2021-23 | 2021-39
Guatemala | 41 | 2021-25 | 2021-37
Belgium | 4 | 2021-27 | 2021-39
Mexico | 261 | 2021-28 | 2021-40
Taiwan | 1 | 2021-30 | 2021-30
United Kingdom | 15 | 2021-30 | 2021-41
Honduras | 1 | 2021-30 | 2021-30
Italy | 1 | 2021-31 | 2021-31
Canada | 9 | 2021-31 | 2021-37
Denmark | 5 | 2021-32 | 2021-41
Trinidad and Tobago | 1 | 2021-32 | 2021-32
Germany | 7 | 2021-33 | 2021-37
France | 5 | 2021-33 | 2021-40
Sint Maarten | 3 | 2021-33 | 2021-38
Colombia | 6 | 2021-33 | 2021-35
Spain | 21 | 2021-33 | 2021-40
Netherlands | 9 | 2021-35 | 2021-39
Argentina | 2 | 2021-36 | 2021-36
Sweden | 2 | 2021-36 | 2021-37
Switzerland | 5 | 2021-36 | 2021-39
Ireland | 1 | 2021-36 | 2021-36
Bonaire | 2 | 2021-36 | 2021-36
Chile | 3 | 2021-37 | 2021-38
Czechia | 1 | 2021-37 | 2021-37
Indonesia | 2 | 2021-38 | 2021-38
Romania | 1 | 2021-38 | 2021-38
Portugal | 1 | 2021-38 | 2021-38

[https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/Past6M/variants/international-comparison?nucMutations=9165T%2C10323G&pangoLineage=B.1.617.2*](https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/Past6M/variants/international-comparison?nucMutations=9165T%2C10323G&pangoLineage=B.1.617.2*)

**Comment by carlosdavn** [comment]
I was checking this sublineage with ORF1a: K3353R and it seems that first K3353R appeared, then followed by ORF1a: 2967I. Another branch through ORF1a: K3353R > ORF1a: S443F is also becoming more noteworthy, mainly in Portugal where it seems to have reached up to 30% in the recent weeks.
![outbreak_portugal](https://user-images.githubusercontent.com/93778724/140525114-b9c6ce61-f564-4d7c-a332-bd4423220212.png)

You can see here both clusters in green and orange: https://nextstrain.org/groups/neherlab/ncov/global?branchLabel=aa&c=gt-ORF1a_3353,443,2967
![neherlab](https://user-images.githubusercontent.com/93778724/140525318-b91837a1-50da-450b-88eb-95ee622884cb.png)

It may be worth considering to design AY.X for the K3353R branch and then AY.X.1 and AY.X.2 for both clusters.

**Comment by FedeGueli** [comment]
Agree with @carlosdavn .

It is now widespread in Portugal 23% (missassigned as AY.42 -27% and AY.102 -44%)
It seems of special interest tge subclade with N:A119S
[covspectrum](https://cov-spectrum.ethz.ch/explore/Portugal/AllSamples/from=2021-10-10&to=2021-11-23/variants?aaMutations=orf1a%3Ak3353r%2Cn%3AA119S&pangoLineage=b.1.617.2*) 
![VariantTimeDistributionChart (13)](https://user-images.githubusercontent.com/87669813/143018700-82ede559-7990-4d33-bc33-5f19bc7586d5.png)


And it is at  around 30% in the Mauritius islands (few sequences)
[Mauritus CovSpectrum](https://cov-spectrum.ethz.ch/explore/Mauritius/AllSamples/from=2021-10-10&to=2021-11-23/variants?aaMutations=orf1a%3Ak3353r%2Cn%3AA119S&pangoLineage=b.1.617.2*) 

@corneliusroemer @chrisruis

**Comment by FedeGueli** [comment]
Orf1a:K3353R:
Tree from [Insaflu build](https://insaflu.insa.pt/covid19/) 
![chrome_screenshot_1637673820306](https://user-images.githubusercontent.com/87669813/143032021-a5aa367f-b5bf-4ebc-a804-2bd3c3737056.png)

**Comment by FedeGueli** [comment]
cc @insapathogenomics i would like to highlight you that a large part of the AY.42 and AY.102 in your [insaflu report](https://insaflu.insa.pt/covid19/) 
arent really AY.42 and AY.102 but likely missassignments from the parental lineage of this proposed clade carrrying Orf1a:K3353R 

As you can see from your build these sequences dont have defining mutation of AY.42: C25872T neither of AY.102:A27690T
![chrome_screenshot_1637674982181](https://user-images.githubusercontent.com/87669813/143035990-56012cc2-4656-4b93-ba30-c39d2192d375.png)

cc @AngieHinrichs @chrisruis @corneliusroemer

**Comment by insapathogenomics** [comment]
@FedeGueli we are completely aware about lineages misassignments and/or lack of phylogenetic congruence. However, this is an issue we cannot control and is far beyond our dataset (as you can rapidly confirm, for example, by searching AY.42 or AY.102 in other globally available builds). In fact, the wrong assignments are also given in GISAID and, as consequence, in all other platforms working with GISAID data (e.g., covSpectrum and outbreak.info). Still, to minimize this bias, we always rerun our full dataset with the latest software/database versions every week and confirm that our updated classification matches that of GISAID. Comprehensibly, the manual curation of the assignments of thousands of sequences every week is not feasible. We hope that the lineages assignments get more stable.

**Comment by FedeGueli** [comment]
@insapathogenomics thank you i am aware , i was just highlighting that on one hand to help pango team (if needed) to be aware of it and solve it and on the other hand to support your analysis.
thank you for your work !

**Comment by chrisruis** [comment]
Thanks @corneliusroemer Looking at the clade with Orf1a:K3353R, there's 2 large clades in there, 1 in USA/Mexico/Costa Rica and 1 in Europe, particularly Portugal. The USA/Mexico/Costa Rica clade is AY.113 and Orf1a:T2967I is acquired one branch into AY.113 so is shared by most sequences in this lineage.

The Portugal/rest of Europe clade is currently undesignated so we've now added this as AY.124 in [v1.2.99](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.99) to start on the branch with C21301A (Orf1ab:P7013T)

There's a number of sequences that cluster within the Orf1a:K3353R clade but not in AY.113 or AY.124 and we've designated these B.1.617.2
