### ISSUE TITLE
KP.1.1.3 +  Orf3a:P178L branch with S:F186L,S:V445R and S:Q493E (31 seqs - 7 countries including Philippines) most with further S:R190S (27)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2811]
Transferred from  https://github.com/sars-cov-2-variants/lineage-proposals/issues/2126 
I propose this one first spotted by @xz-keg and tracked as and then tracked as Branch 30 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1771
 i suggest a rapid designation of this one cc @corneliusroemer due its rapid spread in multiple continents.

it is defined by three/four spike mutations 186L,445R, 493E and 190S present in most of the sequences
All the sequences (2) without S:R190S have further convergent mutations S:M153I and S:L176F

Defining mutations:
KP.1.1.3 > Orf3a:P178L ( C25925T ) > G1954A > S:F186L (C22120A),S:H445R (A22896G), S:Q493E (C23039G)

 
 
Query for the whole branch: C22120A, 22896G, C23039G
Query for S:R190S: C23039G,C4999T,G22132T,C25925T (by @aviczhl2 )
Query for S:L176F+S:M153I branch: C17822T, G22021C ,C22088T
Samples: 22
Places: Israel, Germany, US-California, Philippines (GBW), Singapore , Canada, 
Looking at the [Tree](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3f1d8_75cc40.json?f_userOrOld=uploaded%20sample&label=id:node_7370806) seems that there were at least two introductions in Singapore and three in Canada . It is likely that this could have high prevalence somewhere it could be Philippines or elsewhere because the Sample from Philippines has not the S:R190S belonging to a previous branch of this.
Tree:
<img width="1158" alt="Screenshot 2024-10-22 alle 10 07 20" src="https://github.com/user-attachments/assets/8d827e32-8813-4d59-ba27-6d3b4b8f4838">

**Comment by xz-keg** [comment]
30 now.

There is also a seq with S:445R and Q493E but without F186L appears, EPI_ISL_19506158 GBW from Portugal

**Comment by FedeGueli** [comment]
> C25925T

new query:  22896G, C23039G,C25925T

**Comment by HynnSpylor** [comment]
EPI_ISL_19506832 in NY, US on S:M153I and S:L176F branch further gets S:A475V.

**Comment by HynnSpylor** [comment]
EPI_ISL_19506832 in NY, US on S:M153I and S:L176F branch further gets S:A475V.

**Comment by FedeGueli** [comment]
> EPI_ISL_19506832 in NY, US on S:M153I and S:L176F branch further gets S:A475V.
yeah also one in the 190S branch with 475V : EPI_ISL_19493659

**Comment by FedeGueli** [comment]
LP.8 via https://github.com/cov-lineages/pango-designation/commit/ef380be77b8fa66823880fe1b9aa29cca46543d7

**Comment by xz-keg** [comment]
suggest to re-open to track the two sub-branches, the R190S is now 34 while the S:L176F+S:M153I is now 4.

**Comment by FedeGueli** [comment]
> suggest to re-open to track the two sub-branches, the R190S is now 34 while the S:L176F+S:M153I is now 4.

lets wait a bit. if the small one doesnt grow further it won't be necessary to designate further, but i agree in principle both could go

**Comment by FedeGueli** [comment]
> suggest to re-open to track the two sub-branches, the R190S is now 34 while the S:L176F+S:M153I is now 4.

I ve opened a new issue dedicated to LP.8 diversity: https://github.com/sars-cov-2-variants/lineage-proposals/issues/2199
