### ISSUE TITLE
XEC + S:E1202Q (22 seqs, 6 countries)

### ISSUE THREAD

**Issue by cvejris** [cov-lineages/pango-designation#2812]
This is a proposal for Branch 9 from https://github.com/sars-cov-2-variants/lineage-proposals/issues/2088
Genotype: XEC+G2060A (Orf1a:A599T)+C11020T+G25166C (**S:E1202Q**)
First sampled: France, September 3rd
Total count: 22x (Canada 15x, France 2x, Ireland 2x, Netherlands 1x, USA 1x, Germany 1x via GBW)
Usher tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_270d7_7e6180.json?c=gt-S_1202&f_userOrOld=uploaded%20sample&label=id:node_7264824&showBranchLabels=all
GISAID query: G2060A,C11020T,G25166C

A notable subbranch comprises 9/15 Canadian sequences and is defined by additional C3261T (Orf1a:T999I)+A11680G+T19016A (Orf1b:F1850Y)+G22112A (**S:G184S**). 5 of these seqs carry additional G21786A (**S:G75D**).

**Comment by FedeGueli** [comment]
Designated XEC.3 via https://github.com/cov-lineages/pango-designation/commit/b1e238c06bee3b81c2215478df708a0db6ca1e05#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1206

**Comment by xz-keg** [comment]
@cvejris please close issues that are designated.
