### ISSUE TITLE
XEC+S:G72R (22 seqs, 11 countries)

### ISSUE THREAD

**Issue by cvejris** [cov-lineages/pango-designation#2819]
Branch 11 from https://github.com/sars-cov-2-variants/lineage-proposals/issues/2088 
Description: XEC + Orf1a:A599T (G2060A) + S:G72R (G21776A)
First detected: September 2nd, Denmark
Countries: 5xCanada, 4x Germany, 2xUSA, 2xFrance, 2xSpain, 2xUK, 1xSweden, 1xNetherlands, 1xLuxembourg, 1xDenmark, 1xMexico (via GBW)
Query: G2060A, C25006T, G21776A
Usher: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2dd0c_93030.json?f_userOrOld=uploaded%20sample&label=id:node_2497527

**Comment by Mydtlwn** [comment]
This is XEC.5？

**Comment by FedeGueli** [comment]
Designated XEC.5 via https://github.com/cov-lineages/pango-designation/commit/b1e238c06bee3b81c2215478df708a0db6ca1e05#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1206

**Comment by FedeGueli** [comment]
It got a quite big S:R346K sublineage:

<img width="1102" alt="Image" src="https://github.com/user-attachments/assets/bcf1b501-b2a0-4073-b158-ba9fb95e5504" />
https://nextstrain.org/fetch/genome.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_3d3a9e_dd0c10.json?label=id:node_7345152

**Comment by xz-keg** [comment]
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice149_genome_test_15604a_8dd050.json?label=id:node_5764621

@AngieHinrichs usher seems not recognizing it correctly now.

![Image](https://github.com/user-attachments/assets/15ce1b01-2637-4005-ba29-25e08943ed6e)

**Comment by AngieHinrichs** [comment]
This branch is XEC > G2060A > G21776A (S:G72R).  All of the designated sequences for XEC.5 are on XEC > G2060A > **A25590G** > G21776A (S:G72R), so I annotated that branch as XEC.5.  But lineage_notes.txt only mentions S:G72R, so I can label this branch as XEC.5 too, and I'll try re-placing the sequences that are placed on A25590G without G21776A.
