### ISSUE TITLE
POSSIBLE NEW SUB-LINEAGE OF P.1.12 WITH ADDITIONAL MUTATION IN SPIKE (T284I) MAINLY IN PERUVIAN GENOMES DETECTED BY GROUP OF GENOMIC SURVEILLANCE INS-PERU

### ISSUE THREAD

**Issue by Vjimenez-vasquez** [cov-lineages/pango-designation#282]
**Description**
**Sub-lineage of:** 
Potentially new sub-lineage of P.1.12 (S: N679K, R246G and T284I mutations mainly detected in Peruvian genomes)

### Total sequences : 134
**### Countries circulating:** Italia (3), Canada (1), Chile (2), Switzerland (1), USA (6), Peru (76)

This potentially P.1.12 sub-lineage was first reported in Italy with mutations in spike N679K, R246G, T284I.  In Peru, is pronominally represented in Lima, capital of Peru.

**### Genomes :** 
[Genomes.txt](https://github.com/cov-lineages/pango-designation/files/7392643/Genomes.txt)
**### Metadata**
[metadata_P.1.12.1.txt](https://github.com/cov-lineages/pango-designation/files/7392651/metadata_P.1.12.1.txt)

**### Phylogeny**
![PROPOSAL_P 1 12 1](https://user-images.githubusercontent.com/89874227/138355975-cbbc5216-e7f3-48f4-9652-ce09181af266.jpg)

**### Nextstrain**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_200a6_1be300.json?branchLabel=Spike%20mutations

### Additional Information
![image1](https://user-images.githubusercontent.com/89874227/142065977-9a6d70c8-8b63-4b63-97b6-71cd279ec8ef.png)
![image2](https://user-images.githubusercontent.com/89874227/142066035-af6da5f6-58dd-4861-9ae0-8b22fffc0970.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage P.1.12.1 with 66 newly designated sequences, and 23 redesignated from P.1.12 as they also fell into the proposed clade, in v1.2.115
