### ISSUE TITLE
KP.3.3.2 (S:A435S) sublineage with S:S31del (90 seqs, Canada- 5 regions, Minnesota) and then S:S446N (19 seqs, 3 regions in Canada)

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#2821]
**Main Branch (S:S31del)**
GISAID query: C10741T,C14757T,G22865T
No. of seqs: 115 (114 from multiple Canadian regions, 1 from USA)
First: EPI_ISL_19350608, Manitoba Canada, July 20
Latest: EPI_ISL_19515388, Ontario Canada, October 19

Mutations relative to KP.3.3.2:
C10741T -> C10605T, C14757T, 21653-21655del

**Sub-branch (S:S446N)**
GISAID Query: G16221T, G22899A
No. of seqs: 32 from 3 Canadian regions. 
First: EPI_ISL_19446125, Saskatchewan Canada, September 8
Latest: EPI_ISL_19515388, Ontario Canada, October 19

Mutations relative to Main Branch:
G16221T, G22899A
This only results in S:S31del, S:S446N across the two branches

![image](https://github.com/user-attachments/assets/ced8b9ac-697c-4d63-9697-1d49eebfa831)

Discussion: After acquiring S:31del, this branch of KP.3.3.2 matches MC.10.1's spike which currently appears to be one most quickly growing variants today. The sub-branch with S:S446N currently makes up 32/46 of JN.1* sequences with S:S446N that have been submitted globally since July 1. Possibly the mutation is surviving on this lineage because the variant was very fit and therefore able to sustain detrimental mutations, or perhaps S:A435S has changed the favorability of S:S446N.

**Comment by FedeGueli** [comment]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/2172

**Comment by FedeGueli** [comment]
57/13 now

**Comment by FedeGueli** [comment]
Designated NP.1 Starting with 446N via https://github.com/cov-lineages/pango-designation/commit/ad2242f9751cc6c3409b95075af7269fcc5170f7#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1310
