### ISSUE TITLE
KP.3.1.1 + S:W64C, ORF9b:P39L, ORF1a:N4351T, ORF1b:S1658Y (54 seq, 5 continents)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#2822]
**Description**
**Sub-lineage of:** KP.3.1.1
**Earliest sequence:** 2024-6-2, Spain – EPI_ISL_19225587
**Most recent sequence:** 2024-8-2, USA, New York – EPI_ISL_19341409
**Continents circulating:** Europe, North America, South America, Asia, Oceania
**Countries circulating:** USA, Canada, Spain, France, England, Wales, Italy, Netherlands, Singapore, Ireland, Brazil, Australia
**Number of Sequences:** 9
**GISAID Nucleotide Query:** A13209C, G21754T
**CovSpectrum Query:** Nextcladepangolineage:KP.3.1* & [2-of: A13209C, C19572T, G21754T]
**Substitutions on top of KP.3.1.1:**
**Spike:** W64C
**ORF1a:** N4315T (NSP10_N62T)
**Nucleotide:** A13209C, C18440A, C19572T, G21754T, C28399T

**Phylogenetic Order of Mutations:** C18440A (ORF1b:S1658Y) **→** C28399T (ORF9b:P39L edited) **→** A13209C, C19572T, G21754T (ORF1a:N4315T, S:W64C) 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons3/refs/heads/main/KP.3.1.1_W64C_ORF1a_N4351T.json?c=gt-ORF1ab_4315&gmax=21555&gmin=266&label=id:node_7232514
<img width="1503" alt="image" src="https://github.com/user-attachments/assets/5cd4475a-896b-4292-8d72-34ee07b3c7b0">

**Evidence**
This is probably not a very fast lineage, but I find it interesting for other reasons.

So far, S:S31del has been mostly incompatible with mutations in the S:58-65 range, though they’ve been very popular in non-S31del lineages. In the BA.2 spike structure (there is no structure in this region for BA.2.86 that I know of) S:20-33 and S:58-67 run anti-parallel to each other, practically entangled. Maybe addition of a glycan at N30 causes some sort of steric hindrance that prevents the common S:58-65 mutations (mainly F58L, F59S, F59L, S60P, W64R I think) from occurring. But perhaps the location and the fact that W→C involves a change from a very bulky AA to a much smaller AA makes this mutation permittable. Unlike all the others, this one requires a transversion mutation (G→T) that’s less common than the transitions that lead to the other, so perhaps that’s why it hasn’t appeared as often.

<img width="1293" alt="image" src="https://github.com/user-attachments/assets/59626d91-cb1f-413e-ab47-c293ad8e9146">

Then again, unpaired cysteines tend to be destabilizing, so this may well be a deleterious mutation. 

Lastly, it seems likely that the ORF1a:S4286C/NSP10_S33C mutation of KP.3.1.1 is at least slightly deleterious. Perhaps ORF1a:N4315T/NSP10_N62T is compensatory? 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19225587, EPI_ISL_19280658, EPI_ISL_19289809, EPI_ISL_19293739, EPI_ISL_19320548, EPI_ISL_19323178, EPI_ISL_19341296, EPI_ISL_19341394, EPI_ISL_19341409, EPI_ISL_19225587, EPI_ISL_19280658, EPI_ISL_19289809,
EPI_ISL_19293739, EPI_ISL_19320548, EPI_ISL_19323178,
EPI_ISL_19341296, EPI_ISL_19341394, EPI_ISL_19341409,
EPI_ISL_19347473, EPI_ISL_19348955, EPI_ISL_19352049,
EPI_ISL_19354240, EPI_ISL_19362312, EPI_ISL_19368745,
EPI_ISL_19390698, EPI_ISL_19440681, EPI_ISL_19440843,
EPI_ISL_19445137, EPI_ISL_19447220, EPI_ISL_19447263,
EPI_ISL_19447295, EPI_ISL_19447320, EPI_ISL_19451369,
EPI_ISL_19456906, EPI_ISL_19457064, EPI_ISL_19457196,
EPI_ISL_19462393, EPI_ISL_19462980, EPI_ISL_19463044,
EPI_ISL_19463410, EPI_ISL_19465050, EPI_ISL_19470155,
EPI_ISL_19479314, EPI_ISL_19485709, EPI_ISL_19488309,
EPI_ISL_19491136, EPI_ISL_19491213, EPI_ISL_19491261,
EPI_ISL_19493931, EPI_ISL_19494333, EPI_ISL_19494356,
EPI_ISL_19495967, EPI_ISL_19496235, EPI_ISL_19496252,
EPI_ISL_19503881, EPI_ISL_19506527, EPI_ISL_19507886,
EPI_ISL_19511785, EPI_ISL_19511948, EPI_ISL_19512712,
EPI_ISL_19513011, EPI_ISL_19516177, EPI_ISL_19521599,
</details>

**Comment by DailyCovidCases** [comment]
Likely dying off now

**Comment by FedeGueli** [comment]
> Likely dying off now

Nit fast but one recent sample came from NSW in November
