### ISSUE TITLE
LB.1.3 + S:T>A376S circulating in South Africa (43, 5 places, 40% South Africa after OCT 15 with a sublineage with S:H445R (5)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2825]
LB.1.3>> Orf1a:G432S (G1559A) > S:A376S (G22688T) > S:k147R (A22002G)
Query:22688T,G1559A
Samples: 38 (South Africa 34, Denmark 2, Canada 1,Portugal 1,Spain, US)
First sampled on 2024-08-06 in a traveler from SA

Query for S:H445R branch: 22688T,G1559A,22896G
Samples: 4 ( splitted as the whole lineage in two on Usher) 
Places: South Africa, Spain, Colorado
Last sampled on 2024-11-04 Colorado

<Details><Summary> K147R branch likely dead </Summary>
Query for S:K147R branch: A22002G,22688T
Samples: 6
</details>

The tree as November 24 is split in two with one branch belonging to a South African LB.1.3 branch with  ORF1a:T1581M (C5007T):
 <img width="1176" alt="Screenshot 2024-11-24 alle 23 03 19" src="https://github.com/user-attachments/assets/0fdfd958-56b9-4272-b3dc-d1d8f8758d41">
<img width="1189" alt="Screenshot 2024-11-24 alle 23 03 48" src="https://github.com/user-attachments/assets/9306c11e-3464-452e-9b3d-8757bc7792a8">
<img width="1169" alt="Screenshot 2024-11-24 alle 23 04 02" src="https://github.com/user-attachments/assets/de38d1ba-359a-4009-8f52-b5cc50b6c64d">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_599c0_39fba0.json?c=gt-S_376&label=id:node_7210934

 
IDs: 
EPI_ISL_19339131, EPI_ISL_19438359, EPI_ISL_19453873-19453874,
EPI_ISL_19453879, EPI_ISL_19453891, EPI_ISL_19463191,
EPI_ISL_19463196-19463197, EPI_ISL_19463199, EPI_ISL_19467580,
EPI_ISL_19467656, EPI_ISL_19485379, EPI_ISL_19485390,
EPI_ISL_19522660, EPI_ISL_19531084, EPI_ISL_19531086,
EPI_ISL_19546684, EPI_ISL_19546686-19546687, EPI_ISL_19546690-19546691,
EPI_ISL_19546694-19546699, EPI_ISL_19546701-19546704, EPI_ISL_19546706,
EPI_ISL_19546708-19546710, EPI_ISL_19546714, EPI_ISL_19546718,

**Comment by FedeGueli** [comment]
38 now, 14/33 after OCT.1 in South Africa, @corneliusroemer  this needs a rapid designation.

**Comment by FedeGueli** [comment]
Re updating the tree

**Comment by FedeGueli** [comment]
+1 Spain, @corneliusroemer this could be something to designate soon.

**Comment by FedeGueli** [comment]
40 with a new sample from Colorado it belongs to a S:H445R branch counting 4 samples 2 South Africa, 1 Spain and the most recent one from November collected in Colorado
Query added for 445R : 22688T,G1559A,22896G 
I strongly suggest to designate this one.
cc @corneliusroemer

**Comment by FedeGueli** [comment]
one old one from South Africa

**Comment by FedeGueli** [comment]
43 now with two samples from South Africa one of them with H445R. It keeps a share of 40% of genomes in South Africa after October 15. ping @corneliusroemer this should get a designation

**Comment by xz-keg** [comment]
designated LB.1.3.4

**Comment by xz-keg** [comment]
H445R sub-branch is now 15.

**Comment by FedeGueli** [comment]
> H445R sub-branch is now 15.

Yes but i think that now they are in three distinct branches

**Comment by xz-keg** [comment]
> > H445R sub-branch is now 15.
> 
> Yes but i think that now they are in three distinct branches

make a new issue?

**Comment by FedeGueli** [comment]
NEW GBW sample with 445R and also 345S. i will propose the branches now
