### ISSUE TITLE
MV.1 + ORF1b:K2557R (116 in 10 countries)

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2826]
Transferred from : https://github.com/sars-cov-2-variants/lineage-proposals/issues/2149
![image](https://github.com/user-attachments/assets/552bbb15-9f15-43d4-a25f-7768d3fe0a6d)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_171ca_ddec0.json?f_userOrOld=uploaded%20sample
First Seq: 2024-08-02
Most Recent: 2024-10-25
Gisaid: A21137G, C936T, C21627A
PQ432138.1 EPI_ISL_19467870 EPI_ISL_19437940 EPI_ISL_19467950 EPI_ISL_19420685 EPI_ISL_19336983 EPI_ISL_19390513 EPI_ISL_19467948 EPI_ISL_19420677 EPI_ISL_19467818 EPI_ISL_19373003 EPI_ISL_19467842 EPI_ISL_19467802 EPI_ISL_19467919 EPI_ISL_19467873 EPI_ISL_19467911 EPI_ISL_19467844 EPI_ISL_19464449 EPI_ISL_19467850 EPI_ISL_19437370 EPI_ISL_19467822 EPI_ISL_19467892 EPI_ISL_19467914 EPI_ISL_19467878

**Comment by FedeGueli** [comment]
Please @Fearuncle add query and IDs for this

**Comment by DailyCovidCases** [comment]
Now 111 seqs:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=A21137G%2CC936T%2CC21627A&nextcladePangoLineage=MV.1*&

**Comment by FedeGueli** [comment]
120

**Comment by DailyCovidCases** [comment]
ping @corneliusroemer rapid designation needed:
![Screenshot (87)](https://github.com/user-attachments/assets/423ddc6e-d4a2-4c3d-b12b-c95e2637a448)

**Comment by FedeGueli** [comment]
120 now interesting that the last 5 samples are from 3 different regions in Canada , Australia and US.

**Comment by FedeGueli** [comment]
Designated MV.1.1 via https://github.com/cov-lineages/pango-designation/commit/17508bfb81b7eb0ce399f8e4d3a3bddb9c31c93a#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1297
