### ISSUE TITLE
21J Delta sublineage with ORF3a:85F on the rise in India (~20%), common in Kosovo (~20%) [~2k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#283]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: B.1.617.2 (21J)
Earliest sequence: Beginning of 2021 in India
Most recent sequence: Current
Countries circulating: Rising in India ~20%, was 20% in Kosovo and Oman, is 5% in Norway, slowly rising in UK (0.3%)

21J with defining mutation ORF3a:85F

I spotted this lineage because it contains a sub-lineage in India with interesting extra mutations S:144- and S:484Q that seems to be at ~10% in Gujarat.

I know it's not associated with one single country, but it seems rather interesting from its current growth behaviour.

![image](https://user-images.githubusercontent.com/25161793/138353846-a88803b2-9ecb-4c8d-a213-e0272bfb4d4f.png)
![image](https://user-images.githubusercontent.com/25161793/138353857-47131341-8091-4d9f-8d82-b09d0ea3e241.png)
![image](https://user-images.githubusercontent.com/25161793/138353874-4e3cc645-06de-44ab-a70f-48c940127394.png)
![image](https://user-images.githubusercontent.com/25161793/138353885-26f66a24-9c67-4339-a4bd-5061179ca8a0.png)

Country | Total Variant Sequences | First seq. found at | Last seq. found at
-- | -- | -- | --
India | 336 | 2021-16 | 2021-39
Israel | 5 | 2021-16 | 2021-29
Nepal | 3 | 2021-16 | 2021-38
United Kingdom | 1072 | 2021-18 | 2021-41
Germany | 680 | 2021-18 | 2021-40
Belgium | 225 | 2021-20 | 2021-41
United States | 2231 | 2021-21 | 2021-40
Oman | 28 | 2021-21 | 2021-25
Indonesia | 3 | 2021-21 | 2021-37
Singapore | 3 | 2021-22 | 2021-38
Denmark | 224 | 2021-24 | 2021-38
Japan | 31 | 2021-24 | 2021-35
Turkey | 18 | 2021-24 | 2021-38
Canada | 16 | 2021-24 | 2021-35
Spain | 39 | 2021-24 | 2021-40
Russia | 2 | 2021-25 | 2021-34
Italy | 41 | 2021-25 | 2021-41
Philippines | 1 | 2021-25 | 2021-25
France | 100 | 2021-26 | 2021-40
Netherlands | 80 | 2021-26 | 2021-39
Botswana | 5 | 2021-26 | 2021-35
Bosnia and Herzegovina | 1 | 2021-26 | 2021-26
Lebanon | 1 | 2021-26 | 2021-26
Mexico | 10 | 2021-26 | 2021-38
Luxembourg | 3 | 2021-27 | 2021-30
Slovenia | 123 | 2021-27 | 2021-39
Switzerland | 247 | 2021-27 | 2021-41
Romania | 1 | 2021-27 | 2021-27
Slovakia | 17 | 2021-27 | 2021-40
Albania | 1 | 2021-27 | 2021-27
Croatia | 15 | 2021-27 | 2021-34
Czechia | 15 | 2021-27 | 2021-37
Poland | 26 | 2021-27 | 2021-38
Morocco | 6 | 2021-28 | 2021-35
South Africa | 9 | 2021-28 | 2021-36
Kosovo | 54 | 2021-28 | 2021-37
Portugal | 17 | 2021-28 | 2021-40
Bahrain | 21 | 2021-28 | 2021-39
Ireland | 11 | 2021-29 | 2021-37
Kenya | 1 | 2021-30 | 2021-30
Sweden | 121 | 2021-30 | 2021-40
Ethiopia | 2 | 2021-30 | 2021-32
Thailand | 2 | 2021-30 | 2021-34
Togo | 1 | 2021-30 | 2021-30
Zambia | 1 | 2021-30 | 2021-30
Finland | 8 | 2021-30 | 2021-34
Aruba | 1 | 2021-31 | 2021-31
Egypt | 2 | 2021-31 | 2021-35
Norway | 134 | 2021-31 | 2021-39
Greece | 10 | 2021-31 | 2021-36
Nigeria | 3 | 2021-31 | 2021-35
Austria | 11 | 2021-31 | 2021-37
Georgia | 1 | 2021-32 | 2021-32
Ghana | 2 | 2021-33 | 2021-33
Bulgaria | 2 | 2021-33 | 2021-33
Iceland | 2 | 2021-33 | 2021-34
Brazil | 1 | 2021-33 | 2021-33
Sri Lanka | 6 | 2021-34 | 2021-40
Lithuania | 5 | 2021-34 | 2021-39
Pakistan | 1 | 2021-34 | 2021-34
Malaysia | 1 | 2021-34 | 2021-34
South Korea | 19 | 2021-35 | 2021-38
Maldives | 1 | 2021-35 | 2021-35
Jordan | 4 | 2021-36 | 2021-39
Hong Kong | 4 | 2021-38 | 2021-39

https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/Y2021/variants?aaMutations=N%3A215C&nucMutations=25647T&pangoLineage=B.1.617.2*

**Comment by c19850727** [comment]
Hi @corneliusroemer, in additional to S:Y144del and S:E484Q you mentioned above, this potential lineage has also obtained an additional S:P499R in Gujarat recently.

![image](https://user-images.githubusercontent.com/86835836/142978284-d0525e8b-f93e-4194-a0cd-442a80c4a8be.png)

**Comment by chrisruis** [comment]
Thanks @corneliusroemer This clade has continued to increase as a proportion of Delta in India. This clade contains the previously designated lineage AY.112. We've therefore expanded the AY.112 label to correspond to this broad clade and start on the branch with G25647T (Orf3a:L85F). We've also updated the original AY.112 to AY.112.1 and this lineage still starts on the branch with A3997T (Orf1ab:E1244D). These changes are in [v1.2.109](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.109)
