### ISSUE TITLE
LP.8.1 gained S:K679R (45, 8 Places , 11 airport samples from four different countries Philippines, Australia, Japan,Malaysia) with a S:A475V sublineage (5)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2834]
Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/2199

LP.8.1 >> T5122C, ORF1a:L3667F (G11266T), ,Orf1a:T2846I (C8802T),Orf1b:V1649I (G18412A), S:K679R (A23598G), N:A152V (C28728T)  
Query for LP.8.1 + 679R: A23598G, G22132T, C22120A by @xz-keg  
Samples: 33 
Places :Canada (16, 3 provinces ), Philippines (4 GBW), Hong Kong (4), Australia (3, 2 States + 1GBW)  , Singapore (2), Japan (2, GBW ), New Zealand, Taiwan (traveler from abroad)

With a sub branch with S:P85S 
#2834 >> C14235T > S:P85S (C21815T)
Query: C14235T,C21815T,T3565C
Samples:6 
Places: Canada(2 Provinces), US(NY)

with a sub branch found by @cvejris with  S:A475V and a further sub branch with S:A653V and S:P217L
#2834 >>  , S:A475V (C22986T),>>  S:A653V (C23520T), S:P217L (C22212T)
Query for 679R + 475V:C22986T,A23598G,G22132T (new)
Samples: 5 : Canada (3), Philippines (2 GBW)
Query for 679R,217L,475V,653V: C22212T, C22986T, C23520T
Samples: 3 British Columbia
Tree:
<img width="1160" alt="Screenshot 2024-12-04 alle 12 34 52" src="https://github.com/user-attachments/assets/becb9621-45ba-4d9a-bc4b-c0ddbdcd5540">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_3cf32_39d80.json?f_userOrOld=uploaded%20sample&label=id:node_7412134

**Comment by FedeGueli** [comment]
35 now cc @corneliusroemer

**Comment by Over-There-Is** [comment]
Most of Taiwan/CDC-F are local. Since 03-22, the travelling history of Taiwanese samples are no more provided, all samples are labeled "Patient infected while traveling in unknow" instead. Before then, local cases and imported cases from Mainland, HK or Macao are named as CDC-Fxxxxx, and imported cases out of "Greater China area" are named as CDC-Wxxxxx.

**Comment by FedeGueli** [comment]
> Most of Taiwan/CDC-F are local. Since 03-22, the travelling history of Taiwanese samples are no more provided, all samples are labeled "Patient infected while traveling in unknow" instead. Before then, local cases and imported cases from Mainland, HK or Macao are named as CDC-Fxxxxx, and imported cases out of "Greater China area" are named as CDC-Wxxxxx.

Thx vm i didnt know that.

**Comment by FedeGueli** [comment]
Added a S:P85S sub branch now detected outside Canada

**Comment by FedeGueli** [comment]
37 Aus, NY

**Comment by cvejris** [comment]
> 41 w GBW from Malaysia and Philippines. @corneliusroemer i think this should be designated.

One of the Philippinean samples has - surprise surprise - S:A475V. Plus private Orf1a:D335G (A1269G), Orf1a:I1040F (A3383T), C7420T, Orf3a:T24I (C25463T), N:L161H (T28755A)

**Comment by FedeGueli** [comment]
> > 41 w GBW from Malaysia and Philippines. @corneliusroemer i think this should be designated.
> 
> One of the Philippinean samples has - surprise surprise - S:A475V. Plus private Orf1a:D335G (A1269G), Orf1a:I1040F (A3383T), C7420T, Orf3a:T24I (C25463T), N:L161H (T28755A)

Yes thx already added now it clusters with the canadian 475V branch

**Comment by FedeGueli** [comment]
LP.8.1.1 via https://github.com/cov-lineages/pango-designation/commit/49e57311ed1c0343a42353d6f63b0d9db55677a9

reopening it to track sublineages for a while ( it comes from a multiple branch issue where it is harder to track sublineages) cc @corneliusroemer

**Comment by FedeGueli** [comment]
> EPI_ISL_19611427 (USA, Ohio) is LP.8.1.1+ private S:L5F (C21575T), I434V (A22862G), Orf1a: I2286T (T7122C)

Rbd back in the game, we will see

**Comment by FedeGueli** [comment]
> EPI_ISL_19611427 (USA, Ohio) is LP.8.1.1+ private S:L5F (C21575T), I434V (A22862G), Orf1a: I2286T (T7122C)

i will track LP.8.1.1 sublineages in https://github.com/sars-cov-2-variants/lineage-proposals/issues/2199 
already added this one and the ones previously tracked here
