### ISSUE TITLE
LF.7.3 + Orf1a:P2046L + S:A475V (23 samples, > 10 Places)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2836]
From Branch 4 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/2067

 LF.7.3 (C17436T) > Orf1a:P2046L (C6402T) > S:A475V (C22986T) 
Query: C17436T,C6402T,C22986T, 
23 seqs,
Places: 13 Sweden, Hong Kong, Texas, NY, England, Wales, Qatar, France, Israel, Germany, France, Spain, Denmark, Saudi Arabia (GBW) 
Tree:
<img width="1165" alt="Screenshot 2024-12-07 alle 09 50 30" src="https://github.com/user-attachments/assets/2c09a2ee-9ea6-4fc9-8c57-87287484b18e">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_600d2_389db0.json?label=id:node_7221082

IDs: 
EPI_ISL_19463750, EPI_ISL_19477766, EPI_ISL_19498390,
EPI_ISL_19499207, EPI_ISL_19512573, EPI_ISL_19518077,
EPI_ISL_19518080, EPI_ISL_19518089, EPI_ISL_19521108,
EPI_ISL_19525795, EPI_ISL_19535160, EPI_ISL_19536641,
EPI_ISL_19552502, EPI_ISL_19557388, EPI_ISL_19561038,
EPI_ISL_19564839, EPI_ISL_19564867-19564868, EPI_ISL_19578643,
EPI_ISL_19588216, EPI_ISL_19589725, EPI_ISL_19589727,
EPI_ISL_19589924

**Comment by Over-There-Is** [comment]
LF.7.3.1

**Comment by FedeGueli** [comment]
> LF.7.3.1

from https://github.com/cov-lineages/pango-designation/commit/17508bfb81b7eb0ce399f8e4d3a3bddb9c31c93a#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1297
