### ISSUE TITLE
XEC.12:  XEC + S:G252S (39 in 17 places 6 countries )

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2837]
From: https://github.com/sars-cov-2-variants/lineage-proposals/issues/1993
![image](https://github.com/user-attachments/assets/61510e22-aedb-4798-9b0d-4f5fd0cab077)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_6fd3_649140.json?f_userOrOld=uploaded%20sample

First Seq: 2024-08-12
Most Recent: 2024-11-25

Gisaid: G22316A, T25039C,T3565C

EPI_ISL_19463997 EPI_ISL_19516810 EPI_ISL_19589221 PQ416267.1 PQ454466.1 EPI_ISL_19408525 PQ508455.1 PQ624027.1

**Comment by FedeGueli** [comment]
Dwesignated XEC.12 via https://github.com/cov-lineages/pango-designation/commit/58afeb200abbbcdc988c0d82a3b05db2f83a136d

**Comment by FedeGueli** [comment]
cc @xz-keg 
There are now a couple of potentially interesting branhes of XEC.12:
XEC.12>>C19884T > C12100A > A7381G, A24037G > T4579A, S:R190S (G22132T)
Query:A7381G, T4579A,G22132T
Samples: 3 Nebraska


XEC.12>>C19884T > C12100A > ORF1a:P971 (C3177T), Orf1a:H2794Y (C8645T), S:T345S (C22596G)
 Query: C3177T, C8645T, C22596G
Samples: 1 England

**Comment by FedeGueli** [comment]
> There are now a couple of potentially interesting branhes of XEC.12: XEC.12>>C19884T > C12100A > A7381G, A24037G > T4579A, S:R190S (G22132T) Query:A7381G, T4579A,G22132T Samples: 3 Nebraska

7 now

**Comment by RajLABN** [comment]
10 now from Nebraska w/ S:R190S; generic XEC + S:R190S is 26
