### ISSUE TITLE
XEC.2.3: XEC.2 + N:T379I (51 on Gisaid in 6 countries) 19 with S:G181V

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2838]
From: https://github.com/sars-cov-2-variants/lineage-proposals/issues/2104
Tree: ![image](https://github.com/user-attachments/assets/da8ebe0f-2542-40e3-abdf-250c4a27279b)

First Seq: 2024-08-29
Most Recent: 2024-11-20

Gisaid: T7168C, T16476C

EPI_ISL_19476817 OZ206984.1 EPI_ISL_19568088 OZ186611.1 EPI_ISL_19572871 EPI_ISL_19545967

**Comment by FedeGueli** [comment]
Designated XEC.2.3 and XEC.2.3.1 (181V) via https://github.com/cov-lineages/pango-designation/commit/9b486e72cec35cc59633dd4035663f61479051ed#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R4383
