### ISSUE TITLE
21I Delta AY.9 sublineage with S:Q675K, first detection 2021-30 (~10% in Sweden, 350 seq)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#284]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: AY.9 (21 I)
Earliest sequence: 2021-30 in US [not seen there after], 2021-31 in Sweden
Most recent sequence: Current
Countries circulating: Sweden with 10%, few cases in UK

Spotted by looking at Europe tree with S1 mutations colored. S:675K is interesting, because it's close to S:677 and S:681. This branch of Delta already has S:222V which is one of the two defining mutations of AY.4.2. Growth seems rather fast in Sweden, first detection just 10 weeks ago and now there are ~50 times more cases. It could of course be due to chance, a super spreading event, overdispersion etc, the numbers are too small to be sure. But this should be watched, I don't come across growth like this very often.

Country | Total Variant Sequences | First seq. found at | Last seq. found at
-- | -- | -- | --
United States | 1 | 2021-30 | 2021-30
India | 1 | 2021-31 | 2021-31
Sweden | 328 | 2021-31 | 2021-40
Germany | 3 | 2021-31 | 2021-35
United Kingdom | 17 | 2021-31 | 2021-40
France | 1 | 2021-36 | 2021-36

[https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/Sweden/AllSamples/Past6M/variants?aaMutations=S%3A675K&pangoLineage=B.1.617.2*](https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/Sweden/AllSamples/Past6M/variants?aaMutations=S%3A675K&pangoLineage=B.1.617.2*)

![image](https://user-images.githubusercontent.com/25161793/138356650-6cfdf270-3b2c-424a-bbb0-56286ae3c5ac.png)

![image](https://user-images.githubusercontent.com/25161793/138356655-5ca0f972-ad1a-482e-8df1-a7db654f0dc9.png)

![image](https://user-images.githubusercontent.com/25161793/138356665-501cfa6e-175c-460b-984e-e393a7088d6a.png)

https://nextstrain.org/groups/neherlab/ncov/sweden?branchLabel=aa&c=gt-S_675&r=division

**Comment by FedeGueli** [comment]
Hi @corneliusroemer and @chrisruis 
this sublineage is now almost 100% designated AY.9.2 (ex-AY.9.1) with G1729A.

Around 50% of AY.9.2 in Sweden has the S:675K mutation [Covspectrum](C4321T)

here the comparison of the two trees:
Here the proposed AY.9
![Schermata 2021-12-10 alle 12 39 38](https://user-images.githubusercontent.com/87669813/145569167-f971176f-a937-490e-8045-b20195bef97e.png)
here the AY.9.2
![Schermata 2021-12-10 alle 12 49 34](https://user-images.githubusercontent.com/87669813/145570358-9d37ce4c-3bde-477a-8019-1d62da03effa.png)

I think it is worth closing this issue.

**Comment by chrisruis** [comment]
I think this warrants a designation as a sublineage of AY.9.2 due to being responsible for a high proportion of AY.9.2 sequences in Sweden. We've added this as AY.9.2.2 in [v1.2.110](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.110) to start on the branch with C23585A (S:Q675K)
