### ISSUE TITLE
KP.3.3 got S:S31del and then S:A435S ( 26 , 5 places and 3 continents) 7% in Chile recently 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2844]
I was tracking this since it was two but now it jumped to 5 sequences with spread in multiple continents so better proposing it.
KP.3.3 >> C7162T >> S:S31del (del21653-55), G12208A, C18555T > S:A435S (G22865T)
Query for S.S31del: G12208A, C18555T, G22865T
Query for 435S sub branch:  C7162T, G12208A, G22865T
Samples : 26 (5 w 435S) 
Places:
Places:Australia-NSW, US-Colorado, Denmark, Spain-Basque Country and Chile (**7 provinces**)
First sampled in Australia on 2024-10-23
Last sampled in Spain on 2024-12-01
Tree (with a side branch w 435S that i would count as part of this until more seqs will come):
 <img width="1180" alt="Screenshot 2024-12-14 alle 14 27 32" src="https://github.com/user-attachments/assets/7f3fcdcf-4bfe-4895-978b-b981c984d4dc" />
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_30f3c_d86120.json?label=id:node_7274407

**Comment by FedeGueli** [comment]
ping @corneliusroemer pls take a look at this:
1) convergent with fast KP.3.1.1(31del+435S)
2) with the KP.3.3 fast backbone mutated in Orf9b and N as XEC
3)emerging from a not intensively sampled area.

**Comment by FedeGueli** [comment]
+1 France

**Comment by corneliusroemer** [comment]
KP.3.3.5

**Comment by FedeGueli** [comment]
> KP.3.3.5

via https://github.com/cov-lineages/pango-designation/commit/887cc83e1f4acf8b08f54920ea6606ac9f343f6c

**Comment by FedeGueli** [comment]
137 tot and 30% in December in Chile
