### ISSUE TITLE
MC.1 subbranch with S:F4L and Orf1a:E977D(82, 5 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2847]
Transferred from sars-cov-2-variants/lineage-proposals#2192
MC.1> A3196T(Orf1a:E977D)> T21574A(Orf3c:P39L, Orf3d:Q17*)> C25572T(S:F4L)
Query: C7113T, T21574A, C25572T

Earliest sequence: 09-12 Placer, California, USA EPI_ISL_19600309
Latest sequence: 12-04 Chicago City, Cook, Illinois, USA EPI_ISL_19614516
Regions detected: Canada 48, US 25(1 not on GISAID), Germany 2, Italy 1, Netherlands 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_2e540_1e1f20.json?c=country&label=id:node_7365122
![image](https://github.com/user-attachments/assets/5c0e104d-dfb8-41b2-92ad-5a6da3bed751)

<details><summary>Sequences:</summary>

EPI_ISL_19462025, EPI_ISL_19480131, EPI_ISL_19496747,
EPI_ISL_19500198, EPI_ISL_19504183, EPI_ISL_19504310,
EPI_ISL_19504315, EPI_ISL_19504317-19504318, EPI_ISL_19504325-19504326,
EPI_ISL_19504372, EPI_ISL_19504374, EPI_ISL_19513655,
EPI_ISL_19514027, EPI_ISL_19514066, EPI_ISL_19514174,
EPI_ISL_19514308, EPI_ISL_19519845, EPI_ISL_19527242,
EPI_ISL_19528010, EPI_ISL_19528147, EPI_ISL_19528441,
EPI_ISL_19528914, EPI_ISL_19528957, EPI_ISL_19528963,
EPI_ISL_19529028, EPI_ISL_19529100, EPI_ISL_19532549,
EPI_ISL_19532579, EPI_ISL_19532759, EPI_ISL_19532779,
EPI_ISL_19533713, EPI_ISL_19538531, EPI_ISL_19544029,
EPI_ISL_19544467, EPI_ISL_19548955, EPI_ISL_19548980,
EPI_ISL_19549026, EPI_ISL_19553476, EPI_ISL_19553502,
EPI_ISL_19553507, EPI_ISL_19560058, EPI_ISL_19560062,
EPI_ISL_19560064, EPI_ISL_19560130, EPI_ISL_19560189,
EPI_ISL_19560198, EPI_ISL_19560211, EPI_ISL_19573527,
EPI_ISL_19573599, EPI_ISL_19573657, EPI_ISL_19574003,
EPI_ISL_19577288, EPI_ISL_19578489, EPI_ISL_19588112,
EPI_ISL_19597892, EPI_ISL_19598643, EPI_ISL_19599715,
EPI_ISL_19600309, EPI_ISL_19602583, EPI_ISL_19602681-19602683,
EPI_ISL_19609560, EPI_ISL_19609950, EPI_ISL_19610055,
EPI_ISL_19610264, EPI_ISL_19610460, EPI_ISL_19611447,
EPI_ISL_19614516, EPI_ISL_19614519, EPI_ISL_19615116,
EPI_ISL_19615167, EPI_ISL_19615720, EPI_ISL_19615857,
PQ409705.1
</details>

**Comment by corneliusroemer** [comment]
MC.1.3.1

**Comment by FedeGueli** [comment]
MC.1.3.1 via https://github.com/cov-lineages/pango-designation/commit/173d1b7c5cd537488f7a05e93f2563755e1e8a2e
