### ISSUE TITLE
Kp.3.2.9 sublineage got S:S31del after C7267T (74, >10 Places recently in Ontario)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2849]
_Transferred from https://github.com/sars-cov-2-variants/lineage-proposals/issues/2181_

Defining mutations:
Kp.3.2.9 [A3064G > T16723C > Orf1b:K2557R (A21137G)]>> Orf1a:T568I (C1968T) > C7267T
Gisaid query: C7267T, T16723C, del21653, A21137G
Samples:74
Places: 9  Canada- Ontario (3 provinces), US (7 states) , Wales, Spain (2, 1 GBW), Sweden(2 regions), France (2 regions),Greece, Italy, Japan
Tree:
 <img width="1176" alt="Screenshot 2024-12-20 alle 09 25 21" src="https://github.com/user-attachments/assets/4de8629a-1c04-4c98-99bd-e3ff35a49f2b" />
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_2c47b_5295e0.json?label=id:node_7248507

Samples:
EPI_ISL_19312710, EPI_ISL_19318667, EPI_ISL_19318681,
EPI_ISL_19349939, EPI_ISL_19357485, EPI_ISL_19419679,
EPI_ISL_19422736, EPI_ISL_19463761, EPI_ISL_19472815,
EPI_ISL_19472835, EPI_ISL_19482665, EPI_ISL_19493739,
EPI_ISL_19494954, EPI_ISL_19494956, EPI_ISL_19494966,
EPI_ISL_19494975, EPI_ISL_19494979, EPI_ISL_19494981,
EPI_ISL_19494998, EPI_ISL_19495012, EPI_ISL_19495014,
EPI_ISL_19495037, EPI_ISL_19497226, EPI_ISL_19497816,
EPI_ISL_19506212, EPI_ISL_19514666, EPI_ISL_19514945,
EPI_ISL_19514964, EPI_ISL_19515218-19515219, EPI_ISL_19515222,
EPI_ISL_19515521, EPI_ISL_19519012, EPI_ISL_19519162,
EPI_ISL_19523775, EPI_ISL_19524083, EPI_ISL_19524110,
EPI_ISL_19524158, EPI_ISL_19524160-19524161, EPI_ISL_19524164,
EPI_ISL_19524167-19524168, EPI_ISL_19528092, EPI_ISL_19529237,
EPI_ISL_19534441, EPI_ISL_19534728, EPI_ISL_19535783,
EPI_ISL_19537843, EPI_ISL_19537856, EPI_ISL_19537861,
EPI_ISL_19538070, EPI_ISL_19538212, EPI_ISL_19538454,
EPI_ISL_19543908, EPI_ISL_19555988, EPI_ISL_19574389,
EPI_ISL_19592950, EPI_ISL_19592973, EPI_ISL_19592988,
EPI_ISL_19592994, EPI_ISL_19593005-19593006, EPI_ISL_19593009,
EPI_ISL_19593017, EPI_ISL_19593369, EPI_ISL_19610189,
EPI_ISL_19615073, EPI_ISL_19622469, EPI_ISL_19622485,
EPI_ISL_19622505, EPI_ISL_19622507-19622508, EPI_ISL_19622522,

**Comment by xz-keg** [comment]
The top sub-branch seems to be recombinant with XEC, but seems quite messy

**Comment by FedeGueli** [comment]
> The top sub-branch seems to be recombinant with XEC, but seems quite messy

Yeah lets see how then it evolves, in the case it will be growing i will separate it

**Comment by corneliusroemer** [comment]
NV.1

**Comment by FedeGueli** [comment]
> NV.1
via https://github.com/cov-lineages/pango-designation/commit/3177a360166e1e78e668733bc86bcd690a7d221c#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1350
