### ISSUE TITLE
Proposal for a sub-lineage of AY.9 with ORF1b R188Q and T1540I (~30K sequences, ~30% prevalence in some Caribbean Islands)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#285]
Description
**Sub-lineage of**: AY.9 (29604 sequences)
**Earliest sequence**: 2021/1/9 (Slovakia)
**Most recent sequence**: 2021/10/20 (Belgium)
**Countries circulating**: Wide-spread, with higher prevalence in the Caribbeans and Iceland.

Cumulative prevalence and number of samples sequenced as per Outbreak.info (truncated):
![image](https://user-images.githubusercontent.com/86835836/138393811-6cfe4d85-70f7-4b47-8018-2149a2827a8a.png)
https://outbreak.info/situation-reports?pango&muts=ORF1b%3AR188Q&muts=ORF1b%3AT1540I

**Mutations in addition to AY.9**: ORF1b:R188Q and ORF1b:T1540I and nuc G1729A.

**Genomes**:
[AY.9 R188Q.csv](https://github.com/cov-lineages/pango-designation/files/7394409/AY.9.R188Q.csv)

**Evidence**
Down-sampled tree as per NeherLab (sa-Curacao, filtered to AY.9 only):
![image](https://user-images.githubusercontent.com/86835836/138396811-beae8c31-9259-4e81-9bad-93bc53a1b782.png)
https://nextstrain.org/groups/neherlab/ncov/sa-curacao?c=gt-nuc_1729&f_pango_lineage=AY.9&label=spike_mutations:A222V&p=full

Geography prevalence as per NeherLab (sa-Curacao, all lineages):
![image](https://user-images.githubusercontent.com/86835836/138400822-852b2525-90e8-47f2-b79e-7e21d81600fd.png)

Down-sampled UShER subtree:
![image](https://user-images.githubusercontent.com/86835836/138397631-1f2027fd-f77b-4471-8a6b-0335faba26f2.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_370bb_2491d0.json?branchLabel=aa%20mutations&c=gt-nuc_14030&label=nuc%20mutations:A5584G,C13019T,C22227T&tl=pango_lineage

Transmission advantage as per CoV-Spectrum:
![image](https://user-images.githubusercontent.com/86835836/138396903-4fd2c329-813b-4811-a259-20d3666a263c.png)
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22mutations%22%3A[%22ORF1b%3AT1540I%22%2C%22ORF1b%3AR188Q%22]%7D%2C%22matchPercentage%22%3A1%7D

**Comment by FedeGueli** [comment]
@chrisruis @corneliusroemer @c19850727 
Same of #284 this is now 100%  falling into the newly designated AY.9.2 with G1729A

Please Look at the tree : 
![Schermata 2021-12-10 alle 13 07 41](https://user-images.githubusercontent.com/87669813/145572010-8df7bf9c-6105-4472-bab0-448b9275f834.png)

**Comment by c19850727** [comment]
Thanks @FedeGueli ! I'll close this issue.

**Comment by FedeGueli** [comment]
Thx to you!! just to clean a bit the designation page in the wake of future Omicron sublineages
