### ISSUE TITLE
Proposal for a delta (21I) lineage with ORF1a:141/143DEL and multiple ORF1ab mutations (2147 sequences, ~12% prevalence in Norway)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#286]
Description
**Sub-lineage of**: B.1.617.2, Clade 21I  (2147 sequences)
**Earliest sequence**: 2021/6/10 (Norway)
**Most recent sequence**: 2021/10/10 (Norway)
**Countries circulating**: Predominantly Norway

Cumulative prevalence and number of samples sequenced as per Outbreak.info (truncated):
![image](https://user-images.githubusercontent.com/86835836/138402924-0fcb92e4-85f1-4479-89d9-daa9bb6efd3a.png)

**Mutations in addition to B.1.617.2**: 
ORF1a:I2541V, ORF1b:D260G, nuc C9557T and nuc A23848G,
then ORF1a:141/143DEL, ORF1a:S2900L, ORF1a:A4357V, ORF1bb:I1887V, nuc C5192T, nuc C25710T, nuc G29616T, and nuc T29728C

**Genomes**:
[Delta Norway.csv](https://github.com/cov-lineages/pango-designation/files/7394787/Delta.Norway.csv)

**Evidence**

Down-sampled tree as per NeherLab (Norway, filtered to Clade 21I):
![image](https://user-images.githubusercontent.com/86835836/138404857-d8f6e6c1-f7f4-41d2-be55-b1c730c303f8.png)
https://nextstrain.org/groups/neherlab/ncov/norway?c=gt-ORF1a_2541&f_clade_membership=21I%20%28Delta%29&label=clade:21I%20%28Delta%29&p=full

Geography prevalence as per NeherLab (Norway):
![image](https://user-images.githubusercontent.com/86835836/138405344-462fa680-ebab-4edc-8be0-c949a9889415.png)

UShER subtree:
![image](https://user-images.githubusercontent.com/86835836/138405200-70a176ad-a162-4140-a033-1ebfe975d01c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39658_24b460.json?c=gt-nuc_8964&l=radial&tl=Nextstrain_clade

Transmission advantage as per CoV-Spectrum:
![image](https://user-images.githubusercontent.com/86835836/138405415-d50018fb-b8ad-49b2-b282-8c1590876032.png)

**Comment by FedeGueli** [comment]
Now it should have been designated as AY.58 starting from C5192T (https://www.pango.network/summary-of-designated-ay-lineages/) cc @chrisruis 

![Schermata 2021-11-01 alle 20 33 04](https://user-images.githubusercontent.com/87669813/139730346-37485138-98c4-4150-b7d0-3588dd0c9dae.png)

**Comment by FedeGueli** [comment]
Sorry @chrisruis this seems to have been designated two times: it is the new AY.63 too
Look at the tree
![Schermata 2021-11-01 alle 20 43 10](https://user-images.githubusercontent.com/87669813/139731790-33218d47-f87c-4267-ab5b-12c9342c9e3f.png)



cc @c19850727

**Comment by FedeGueli** [comment]
This lineage appears to be circulating in Italy too.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_252b9_6e7740.json?branchLabel=aa%20mutations&c=gt-nuc_5192&label=nuc%20mutations:C5192T,G8540A,C26079A,C27131T&tl=pango_lineage_usher

https://cov-spectrum.ethz.ch/explore/Italy/AllSamples/Past3M/variants?nucMutations=C5192T&pangoLineage=B.1.617.2*
