### ISSUE TITLE
Proposal for a delta (21A) lineage with Spike S255F (~900 sequences, ~53% prevalence in Jordan)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#287]
Description
**Sub-lineage of**: B.1.617.2, Clade 21A (889 sequences)
**Earliest sequence**: 2021/4/17 
**Most recent sequence**: 2021/10/15 (Jordan)
**Countries circulating**: Germany (204 sequences), Jordan (84 sequences), and other countries

**Mutations in addition to B.1.617.2**:
nuc C9811T,
then S:S255F

**Evidence**

Down-sampled tree as per Neherlab (Asia-Jordan, filtered to Clade 21A only):
![image](https://user-images.githubusercontent.com/86835836/138499178-6ffcdc4a-6763-4b16-b670-0cffbd7a2dbc.png)
https://nextstrain.org/groups/neherlab/ncov/asia-jordan?branchLabel=aa&c=gt-S_255&f_clade_membership=21A%20%28Delta%29&label=spike_mutations:I95T&p=full&r=division&tl=country

Down-sampled tree as per Neherlab showing country of submission:
![image](https://user-images.githubusercontent.com/86835836/138499441-3929ff84-8b72-4d0a-b35c-1ab68a7fb280.png)

Geographical distribution as per NeherLab:
![image](https://user-images.githubusercontent.com/86835836/138500015-fd202b58-62d3-4165-8ff5-1acfdb637773.png)

UShER subtree:
![image](https://user-images.githubusercontent.com/86835836/138499533-c86ab248-afa1-4663-8822-2a85208da4a7.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_103d8_2f2920.json?c=gt-S_255&l=radial

Transmission advantage and geographical distribution as per CoV-Spectrum:
![image](https://user-images.githubusercontent.com/86835836/138499652-19d758cf-4696-4622-87e7-e86a0e68c4d9.png)
![image](https://user-images.githubusercontent.com/86835836/138499706-15dea828-ed40-48d8-9b56-890113a061a6.png)
https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3AS255F&nucMutations=C9811T

**Comment by FedeGueli** [comment]
This has been designated as AY.106 with S:S255F

commit:
https://github.com/cov-lineages/pango-designation/commit/61248ea86a3e5912440d76081da88805c074b3cc

cc @corneliusroemer @chrisruis

**Comment by FedeGueli** [comment]
![Screenshot_2021-11-05-11-54-18-095_com android chrome](https://user-images.githubusercontent.com/87669813/140499942-baef2064-caa8-4b9e-979f-3518df632b0b.jpg)

AY.106 seems steadily growing in Germany

**Comment by corneliusroemer** [comment]
These are all the German sequences with S:255F, there are homplasies. AY.106 doesn't cover all of them, but the biggest chunk.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1c4a5_520b10.json

https://genome.ucsc.edu/cgi-bin/hgPhyloPlace?db=wuhCor1&phyloPlaceTree=hgPhyloPlaceData/wuhCor1/public.plusGisaid.latest.masked.pb&subtreeSize=1000&remoteFile=https%3A%2F%2Fcov-spectrum.ethz.ch%2Fgisaid%2Fapi%2Fv1%2Fsample%2Fstrain-names%3Fhost%3DHuman%26country%3DGermany%26dateFrom%3D2020-01-06%26aaMutations%3DS%253A255F%26pangoLineage%3DB.1.617.2*

![image](https://user-images.githubusercontent.com/25161793/140509640-e856b690-1843-4602-9fb7-169ac9651989.png)
