### ISSUE TITLE
US 21J Delta sublineage with S:675H (~1%, 4k seq, daily growth advantage ~1%)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#288]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: B.1.617.2 (21J)
Earliest sequence: 2021-24 US
Most recent sequence: Current
Countries circulating: ~1% in US

Lineage was spotted because it has substitution S:675H, which is the site that is also substituted in #284 (although there the sub is to K). It seems to have a pretty steady growth trajectory, albeit only with ~15

It also has mutation 8829T which can be used to distinguish from other S:675H (there's apparently one in Luxembourg that's unrelated).

![image](https://user-images.githubusercontent.com/25161793/138527871-2d2b05ba-7ecb-4284-bffe-dfe0f539d184.png)

[https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=S%3A675H&nucMutations=8829T&pangoLineage=B.1.617.2*](https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=S%3A675H&nucMutations=8829T&pangoLineage=B.1.617.2*)

![image](https://user-images.githubusercontent.com/25161793/138527903-f6c9ea8c-f6c7-498d-b4ba-68ecd0f034c7.png)

https://nextstrain.org/groups/neherlab/ncov/na-usa?c=gt-S_675

Country | Total Variant Sequences | First seq. found at | Last seq. found at
-- | -- | -- | --
United States | 3803 | 2021-24 | 2021-41
Sweden | 30 | 2021-25 | 2021-30
Mexico | 1 | 2021-29 | 2021-29
Canada | 60 | 2021-30 | 2021-36
Argentina | 1 | 2021-30 | 2021-30
Brazil | 1 | 2021-31 | 2021-31
Israel | 3 | 2021-31 | 2021-32
South Korea | 1 | 2021-33 | 2021-33
Sint Maarten | 5 | 2021-33 | 2021-33
Japan | 1 | 2021-34 | 2021-34
United Kingdom | 7 | 2021-35 | 2021-39
France | 16 | 2021-36 | 2021-40
Germany | 3 | 2021-38 | 2021-38
Greece | 3 | 2021-38 | 2021-38

**Comment by c19850727** [comment]
Hi @corneliusroemer have you checked this sublineage recently? 
there're ~5.8k sequences now and still showing a ~3% transmission advantage as per Cov-spectrum.
![image](https://user-images.githubusercontent.com/86835836/142619402-ab415e09-c9b4-4ac2-b3f1-adc62ac5b4f8.png)

**Comment by chrisruis** [comment]
Thanks @corneliusroemer This is a sublineage of AY.119 and we've added this as AY.119.2 in [v1.2.110](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.110) to start on the branch with G23587C (S:Q675H)
