### ISSUE TITLE
Sublineages of B.1.1.28 (proposed P.4) circulating in South Brazil with N:P13L, ORF3a:T151I and ORF9b:P10S mutations

### ISSUE THREAD

**Issue by fhsantanna** [cov-lineages/pango-designation#29]
**Description**
_Sub-lineage of:_ B.1.1.28
_Earliest sequence:_ Brazil/SP-796/2020 (EPI_ISL_735433) - 2020-07-01
_Most recent sequence:_ Brazil/SP-1711/2021 (EPI_ISL_1121317) - 2021-02-09
_Countries circulating:_ Brazil, Netherlands, Japan, England
A novel lineage was found circulating in South/Southern Brazil with the following mutations: N:P13L, ORF3a:T151I and ORF9b:P10S (figure below, red and blue clades). Also,  a putative sublineage (figure below, blue clade) was found mostly in Rio Grande do Sul with the following mutations in ORF1a: P2287S, V2588F, L3027F and Q3777H.

**Genomes**
[P_4.txt](https://github.com/cov-lineages/pango-designation/files/6111998/P_4.txt)

**Evidence**
![Captura de tela de 2021-03-09 16-41-04](https://user-images.githubusercontent.com/14040854/110527900-4a317f00-80f6-11eb-8951-b15dc8604e1b.png)
![Captura de tela de 2021-03-09 16-41-48](https://user-images.githubusercontent.com/14040854/110527967-5d444f00-80f6-11eb-89e1-84e4c0b1894f.png)

**Proposed lineage name**
P.4 (blue and red clades) and P.4.1 (blue clade)

**Comment by fhsantanna** [comment]
Here is a paper describing the novel lineage as VUI-NP13L: https://www.sciencedirect.com/science/article/pii/S0168170221000526

**Comment by rambaut** [comment]
It is not clear this is epidemiologically distinct enough to be designated as a new lineage. The defining mutations are not generally associated with VOIs.

**Comment by fhsantanna** [comment]
Here we characterize and  demonstrate the epidemiological  context of the described lineage:
[https://www.medrxiv.org/content/10.1101/2021.04.14.21255429v1](https://www.medrxiv.org/content/10.1101/2021.04.14.21255429v1)

The parental lineage P.4 possesses the following signatures: N:P13L, ORF3a:T151I and ORF9b:P10S.
The descendant lineage P.4.1 possesses additional mutations in ORF1a: P22875S, V2588F, L3027F, Q3777H and two synonymous mutations, C1288T and G10870T.

We demonstrated that P.4.1 presented an explosive spread in South Brazil.

Furthermore, an independent group recently found that P.4.1 reached Northeast Brazil: [https://www.medrxiv.org/content/10.1101/2021.03.21.21253418v2.full-text](https://www.medrxiv.org/content/10.1101/2021.03.21.21253418v2.full-text)

Although too much attention is given to spike mutations,  it is worth noting that Forni el atl (2016) [https://jvi.asm.org/content/90/7/3627](https://jvi.asm.org/content/90/7/3627) demonstrated that the proportion of positively selected sites in ORF1a is much higher than for the spike protein. They believe that the positive selection acting on ORF1a might contribute to host shifts or immune evasion in betacoronaviruses.

**Comment by fhsantanna** [comment]
Dear @aineniamh and @rambaut, have you read my update regarding "P.4"?

**Comment by fhsantanna** [comment]
Here is an update of sequences deposited in GISAID from March, 2021, showing only those collected in 2021.
P.4.1 sublineage is active in Brazil, the most recent sequence was obtained in Sao Paulo in 2021-04-03. Also, this lineage 
was detected in Chile, Paraguay and USA between February and March 2021. Strain names, accession numbers and collection dates are described below:
```
strain	accession	collection_date
hCoV-19/Brazil/SP-2615/2021	EPI_ISL_1731606	2021-04-03
hCoV-19/Chile/AR-72041/2021	EPI_ISL_1541023	2021-03-29
hCoV-19/USA/MA-CDC-LC0037276/2021	EPI_ISL_1610252	2021-03-24
hCoV-19/USA/CO-CDC-ASC210013727/2021	EPI_ISL_1525100	2021-03-20
hCoV-19/Paraguay/PY23/2021	EPI_ISL_1492659	2021-02-21
hCoV-19/Paraguay/PY18/2021	EPI_ISL_1492654	2021-02-20
hCoV-19/Brazil/SP-2046/2021	EPI_ISL_1468442	2021-02-18
hCoV-19/Brazil/SP-1711/2021	EPI_ISL_1121317	2021-02-09
hCoV-19/Brazil/BA-00751/2021	EPI_ISL_1213237	2021-02-08
hCoV-19/Brazil/SP-2061/2021	EPI_ISL_1468449	2021-02-08
hCoV-19/Brazil/SP-2121/2021	EPI_ISL_1468471	2021-02-07
hCoV-19/Brazil/SP-2120/2021	EPI_ISL_1468470	2021-02-06
hCoV-19/Brazil/SP-2082/2021	EPI_ISL_1468459	2021-02-03
hCoV-19/Brazil/MS-1952/2021	EPI_ISL_1358309	2021-02-03
hCoV-19/Brazil/SP-1869/2021	EPI_ISL_1293069	2021-02-01
hCoV-19/Brazil/SP-2237/2021	EPI_ISL_1533697	2021-01-30
hCoV-19/Brazil/SP-2118/2021	EPI_ISL_1468469	2021-01-30
hCoV-19/Brazil/PB-00783/2021	EPI_ISL_1213429	2021-01-13
hCoV-19/Brazil/PB-00763/2021	EPI_ISL_1213433	2021-01-12
hCoV-19/Brazil/RS-15RSLHCPA/2021	EPI_ISL_1161401	2021-01
hCoV-19/Brazil/RS-27HRAFHCPA/2021	EPI_ISL_1161410	2021-01
hCoV-19/Brazil/RS-30DGSHCPA/2021	EPI_ISL_1161412	2021-01
```

Another P.4 lineage was also found circulating in Sao Paulo in February 2021. Here is the sequence name:
```
hCoV-19/Brazil/SP-1932/2021|EPI_ISL_1358322|2021-02-23
```

**Comment by fhsantanna** [comment]
Here is our paper describing VUI-NP13L signatures:
https://www.tandfonline.com/doi/full/10.1080/22221751.2021.1949948

It is worth noting that other lineage was named as P.4, therefore our name proposal should be updated.

**Comment by chrisruis** [comment]
Thanks @fhsantanna. We've added this as P.7 in [v1.2.50](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.50)
