### ISSUE TITLE
Proposal for a sublineage of AY.4 with E:V58F (~3k sequences, ~18% prevalence in Aruba)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#291]
Description
**Sub-lineage of**: AY.4, Clade 21J (3004 sequences)
**Earliest sequence**: 2021/2/9 (Slovakia)
**Most recent sequence**: 2021/10/14 (Germany)
**Countries circulating**: the Netherlands (619 sequences), Aruba (435 sequences), Germany (434 sequences), Denmark (314 sequences), among a few other countries.

Cumulative prevalence and number of samples sequenced as per Outbreak.info (truncated):
![image](https://user-images.githubusercontent.com/86835836/138585340-f43c49a2-bc07-4829-9a1e-94c3350c8010.png)

**Mutations in addition to AY.4**:
ORF1a:A2529V,
then ORF1b:E1242D, ORF9b:P3L,
then ORF1b:M454I,
then E:V58F

**Genomes**:
[AY.4 V58F.csv](https://github.com/cov-lineages/pango-designation/files/7404290/AY.4.V58F.csv)

**Evidence**
Down-sampled tree as per NeherLab (sa-Aruba, filtered to AY.4, shown in orange color):
![image](https://user-images.githubusercontent.com/86835836/138585674-3648b6d3-5121-453d-b507-2fcf070309da.png)
https://nextstrain.org/groups/neherlab/ncov/sa-aruba?c=gt-nuc_7851,26416&f_pango_lineage=AY.4&p=full&r=division

Geography prevalence as per NeherLab (sa-Aruba):
![image](https://user-images.githubusercontent.com/86835836/138585722-439fca42-b311-466c-988f-ef98ed5ad99e.png)

UShER subtree:
![image](https://user-images.githubusercontent.com/86835836/138585746-4adcd415-0654-4bb6-afe5-a49ea1bb864d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20b79_505740.json?c=gt-E_58&l=radial

Transmission advantage as per CoV-Spectrum:
![image](https://user-images.githubusercontent.com/86835836/138585755-57990ab9-def1-4c25-bb33-da24e3d6dcf1.png)
![image](https://user-images.githubusercontent.com/86835836/138585773-9c81cd0f-02b9-4784-b77b-b2808e1deaa1.png)
https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/AllTimes/variants?aaMutations=E%3AV58F%2CORF1b%3AM454I

**Comment by FedeGueli** [comment]
Hi @c19850727 @chrisruis this showed very limited spread in Europe, it was stable in Aruba around 15/20% of sequences.

https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?aaMutations=E%3AV58F&pangoLineage=ay.4*

I dont know if it really deserves a designation, it could be monitored in Aruba well with the covspectrum tool due to its limited geographical spread.

Sorry for bothering, trying to help with frozen issues ;)

**Comment by chrisruis** [comment]
I think this clade warrants a designation. We've added this as AY.4.7 in [v1.2.110](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.110) to start on the branch with G26416T (E:V58F)
