### ISSUE TITLE
21J Delta sublineage on ORF7a:P45L branch with extra S:613H (~2% in Italy and growing, 350 seq)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#294]
New lineage proposal
by @CorneliusRoemer

Description
Sub-lineage of: B.1.617.2 (21J) on branch with ORF1a:K261N, ORF7a:P45L
Earliest sequence: 2021-31 in US, then 32 in Czechia, then across Europe
Most recent sequence: Current
Countries circulating: Italy (2%), but also Germany, UK, Denmark and rest of Europe at low but rising levels <1%

For cov-spectrum queries I define it as: B.1.617.2* + G1048T, T21846C, G18816A + S:613H

I stumbled upon this lineage when I looked at homoplasies of S:613H in Spain.

Country | Total Variant Sequences | First seq. found at | Last seq. found at
-- | -- | -- | --
United States | 8 | 2021-31 | 2021-39
Czechia | 21 | 2021-32 | 2021-39
Portugal | 6 | 2021-33 | 2021-37
Germany | 55 | 2021-33 | 2021-41
United Kingdom | 120 | 2021-33 | 2021-42
Italy | 39 | 2021-34 | 2021-42
Denmark | 17 | 2021-34 | 2021-42
Poland | 10 | 2021-34 | 2021-41
Ireland | 7 | 2021-35 | 2021-41
Belgium | 18 | 2021-35 | 2021-41
Luxembourg | 7 | 2021-35 | 2021-39
Switzerland | 5 | 2021-35 | 2021-41
France | 8 | 2021-36 | 2021-40
Romania | 1 | 2021-38 | 2021-38
Hong Kong | 1 | 2021-40 | 2021-40
Spain | 3 | 2021-40 | 2021-41

https://cov-spectrum.ethz.ch/explore/Europe/AllSamples/Past3M/variants/international-comparison?aaMutations=S%3A613H&nucMutations=G1048T%2CT21846C%2CG18816A&pangoLineage=B.1.617.2*

![image](https://user-images.githubusercontent.com/25161793/138977621-be25db4f-cbdb-4e76-a7a6-c2440ff904dc.png)

https://nextstrain.org/groups/neherlab/ncov/italy?branchLabel=aa&c=gt-S_613

![image](https://user-images.githubusercontent.com/25161793/138977722-3d8a4c29-b355-465d-b0a7-890537c17564.png)

![image](https://user-images.githubusercontent.com/25161793/138977733-59d081bd-fee3-4b2e-b866-2e05fd6c9821.png)

**Comment by FedeGueli** [comment]
Hi @corneliusroemer this sublineage of AY.122 is stable around the 6% of Danish AY.122 sequences
![Schermata 2021-12-10 alle 13 41 37](https://user-images.githubusercontent.com/87669813/145575819-e6292f0e-2fcb-43c4-8c8e-a3edc47235cb.png)

In Italy it seems to grow less than the parental lineage [CovSpectrum](https://cov-spectrum.org/explore/Italy/AllSamples/Past3M/variants?pangoLineage=AY.122*)

**Comment by chrisruis** [comment]
Thanks @FedeGueli Maybe given that, let's hold off on this one for now

**Comment by FedeGueli** [comment]
Thx @chrisruis Chris for your great work here today
