### ISSUE TITLE
Proposal for a new sublineage of MU with S: 449N + S:583D that seems to resist better than others to Delta Expansion

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#299]
Proposing here this new MU sublineage identified by Ricardo Riveiro (https://www.researchgate.net/profile/Ricardo-Rivero-2), universidad de Cordoba-Colombia).
He described this sublineage here:
https://twitter.com/Ricardo__JRH/status/1450544232750620675?s=20

He noticed that since august MU seems to have less growth disadvantage in comparison to Delta.
Then he downloaded all the GISAID sequences since august 2021 and found that the mayority of them are characterized by two spike mutations : S:Y449N and S:E583D.

Looking at NeherLab tree for Chile it is a quite clearly visible sublineage 
![Schermata 2021-10-31 alle 14 30 59](https://user-images.githubusercontent.com/87669813/139586059-3d4f64bb-53e3-4f02-97c3-9377c735521a.png)
https://nextstrain.org/groups/neherlab/ncov/sa-chile?branchLabel=spike_mutations&c=gt-S_449,583&d=tree&p=full&r=division&tl=pango_lineage

This sublineage of B.1.621 is accumulating more Spike mutations.
![Schermata 2021-10-31 alle 14 16 52](https://user-images.githubusercontent.com/87669813/139586193-f04150fd-fd63-4743-b456-e722fb97aecd.png)
It accounts for 128 sequences in Colombia (228 South America)and prevalence is still between 7-20% according to:
https://cov-spectrum.ethz.ch/explore/Colombia/AllSamples/Past3M/variants?aaMutations=S%3A449N%2CS%3A583D&pangoLineage=B.1.621*

Trasmission advantage on CovSpectrum between 0 (South America) and 9%( Colombia)
![Schermata 2021-10-31 alle 14 39 23](https://user-images.githubusercontent.com/87669813/139586417-6b7440b0-36d2-43d6-8961-8610b9aab0e7.png)

**Comment by FedeGueli** [comment]
(Obviously i have been authorised to propose this by the author itself)

**Comment by andreijl** [comment]
This one has also been mentioned here: #232

**Comment by RicardoRH96** [comment]
Thank you for proposing this sublineage designation.

**Comment by FedeGueli** [comment]
@andreijl thank you for noticing! i 'll close this, recommending to read the Ricardo Riveiro 3D here:
https://twitter.com/Ricardo__JRH/status/1450544232750620675?s=20

#232
