### ISSUE TITLE
Proposal for new lineage within B.1

### ISSUE THREAD

**Issue by rambaut** [cov-lineages/pango-designation#3]
### Description
Sub-lineage of: B.1
Earliest sequence: 2020-09-28
Most recent sequence: 2020-12-28
Countries circulating: A lineage predominantly circulating in California but with exports to other countries. Characterised by the spike L452R mutation but also has spike:W152C orf1ab:D5584Y and N:T205I

```
orf1ab:D5584Y
S:W152C
S:L452R
synSNP:C26681T
N:T205I
synSNP:C29362T
```

### Genomes
[B.1.X_genomes.txt](https://github.com/cov-lineages/lineages/files/5842353/B.1.X_genomes.txt)

List of genomes, collated 2021-01-13, attached. 

### Evidence

Phylogenetic tree PDF image. Proposed new lineage labels in red:
![B 1 X_tree](https://user-images.githubusercontent.com/686405/105175244-92cbb380-5b1b-11eb-82dc-a8fa1ca0e775.png)

Phylogenetic tree file:
[B.1.X.tree.txt](https://github.com/cov-lineages/lineages/files/5842390/B.1.X.tree.txt)

### Proposed lineage name

To be determined as the the next available designation within B.1

**Comment by aineniamh** [comment]
@ViralVerity and I have found the lineage in the global tree and going forward it'll be called B.1.429. Going to re-run pangoLEARN training today and will tag a new release once the training has finished.
