### ISSUE TITLE
Proposal for new lineage within B.1

### ISSUE THREAD

**Issue by hsnguyen** [cov-lineages/pango-designation#30]
Proposed by Son Nguyen, PEH-FSS, Queensland Department of Health.
Another clade of S:N439K other than the European clade (B.1.258), circulating in Malay Archipelago countries and infected Queensland miners coming back from PNG.

![nextstrain-s439k](https://user-images.githubusercontent.com/7806873/110633988-2b65e200-81f5-11eb-9080-ca631d1aa5dc.png)

### Description

Sub-lineage of: B.1
Earliest sequence: 2020-11-12 (Indonesia/JB-EIJK70/2020)
Most recent sequence: 2021-03-6 (Australia/QLD1659/2021)
Countries circulating: Singapore (21), Indonesia (40), Malaysia (6), Australia (14) (exposed in PNG), Japan (10) (exposed in Indonesia)

Characterised by spike mutations: N439K, a sub-set acquired P681R (from A.23.1) would form a sub-level lineage.

### Genomes
[b1x_genome.txt](https://github.com/cov-lineages/pango-designation/files/6116010/b1x_genome.txt)
[b1xy_genome.txt](https://github.com/cov-lineages/pango-designation/files/6116011/b1xy_genome.txt)

### Evidence
![proposed-lineage-B1XY](https://user-images.githubusercontent.com/7806873/110634113-50f2eb80-81f5-11eb-9887-1dcdb84b7e6b.png)

Tree file: 
[lineages-proposal.nex.txt](https://github.com/cov-lineages/pango-designation/files/6116028/lineages-proposal.nex.txt)

### Proposed lineage name
To be determined as the the next available designation within B.1

### Defining mutations
B.1.X: C22879A (S:N439K), C3768T, C5184T

B.1.X.Y: + C23604G (S:P681R), T22219C, C17012T, C29718T, C29743T, C683T.

**Comment by chrisruis** [comment]
Thanks very much for this. We've just tagged release v1.1 [here](https://github.com/cov-lineages/pango-designation/releases/tag/v1.1) that includes this lineage as B.1.466.2. Because the sublineage is circulating within the same countries, it doesn't currently qualify for a new Pango lineage at this stage so is still designated B.1.466.2. Thanks again

**Comment by hsnguyen** [comment]
Hi team,
Just zoom in all B.1.466.2 sequences from GISAID to date and found the sub-lineage (+P681R) is expanding: United_Kingdom(1), Papua_New_Guinea(7), Singapore(20), Indonesia(95), Malaysia(17), Japan(7), South_Korea(2), Australia(34).
So I think it'd be great to have an alias for this now.

### Genomes : 
[p681r_clade.txt](https://github.com/cov-lineages/pango-designation/files/6240714/p681r_clade.txt)

### Evidence: 
![b14662 treefile](https://user-images.githubusercontent.com/7806873/113238878-f8db7080-92ec-11eb-8378-5bca4057f3b2.jpg)

Tree file:
[b14662.treefile.txt](https://github.com/cov-lineages/pango-designation/files/6240728/b14662.treefile.txt)

Thank you all for your great works!

**Comment by hsnguyen** [comment]
@chrisruis any chance considering this sub-lineage? I believe it's still circulating around several South East Asian countries, PNG.. at the moment. Thanks.

**Comment by chrisruis** [comment]
Hi @hsnguyen sorry for the delay, I hadn't seen this being reopened! Thanks for checking in again with this.

I've had a look at this part of the tree including all sequences on GISAID currently _assigned_ to B.1.466.2 (791 sequences), the parental B.1.466 (30 sequences) and a few B.1 sequences for context. Below, the left hand figure is the tree coloured by _assigned_ lineage and the right hand figure is the tree coloured by country of collection:
![B 1 466 2](https://user-images.githubusercontent.com/47785131/116586336-41e50b80-a911-11eb-9664-865ea934e74b.png)

I believe your clade of interest is downstream of the starred node in this tree.

For a new lineage designation, we need the clade to represent one or more events of epidemiological significance to distinguish the new lineage from continued circulation of the parental lineage. These events can include a movement into a new geographical region or the clade growing rapidly or increasing in frequency relative to other co-circulating lineages. From the tree, I can't see an epidemiological event associated with this clade. So in this case, unless there is evidence that this clade is greatly increasing in frequency relative to other clades, I'd suggest we keep the designations the same and continue to refer to this clade as B.1.466.2.

There are, however, several clades within B.1.466.2 that satisfy the epidemiological criteria for a new lineage as they have been introduced into a new geographical area with onward transmission. I've put arrows next to these in the above figure. The top arrowed clade is in Papua New Guinea and is now designated this as AU.1 (as B.1.466.2 has the maximum of 3 sub-levels in its name, any descendent clades get an alias, in this case AU). Unless there is evidence that the starred clade is growing rapidly and requires its own lineage, I'd suggest that most of the starred clade remains B.1.466.2 and we designate the 2 smaller arrowed clades (in Malaysia and Australia, respectively) as AU.2 and AU.3.

**Comment by hsnguyen** [comment]
Thanks @chrisruis, that's very helpful you've checked the clade with the most up-to-date GISAID data. It's growing fast since the last time I did.
Regarding the epi data, what I know is that there's covid outbreak in Papua New Guinea early this year and returning Queenslanders from this country having high positive rate. From the phylo tree, my hypothesis is that B.1.466.2 appeared first in Indonesia and spread to other countries around, including PNG and then Australia. I think most of the B.1.466.2 samples outside the region  should have travel history to this region too.
In Queensland we're still having positive cases in hotel quarantine with B.1.466.2 as the major lineage and ~80% of sequences containing P681R, and as you can see a few sequences from a current outbreak in Cambodia belong to this sub-clade as well. Agreed it's hard to have the full picture of the whole starred sub-lineage due to the low sequencing rate in this big region. Currently Australia's providing sequencing support for PNG only, resulted in the boom of sequences from the top arrowed clade.
Happy with the suggestion for AU.1 (PNG) and AU.3 (PNG-QLD), I don't have data for the Malaysia one though. 

Will have eyes on this and keep you updated. 
Cheers,

**Comment by chrisruis** [comment]
Thanks @hsnguyen that all sounds good

I've now designated AU.2 (Malaysia) and AU.3 (QLD-PNG) in [v1.1.25](https://github.com/cov-lineages/pango-designation/releases/tag/v1.1.25)
