### ISSUE TITLE
Early Delta sub-lineage with reversion Orf7A:V82A plus N:183T, ORF1b:2432I

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#302]
Zach Hensel noticed that the Polish lineage #301 has a reversion at Orf7A:82 [comment](https://github.com/cov-lineages/pango-designation/issues/301#issuecomment-958351061_).

It turns out there are a number of independent occurrences of that reversion within Delta.

One that seems particularly persistent is one with N:183T, ORF1b:2432I on top that was at times big in Israel and is currently growing in Belgium and Denmark. It was apparently first sequenced in Sweden in 2021-21 then Finland, Germany, Belgium in 2021-22. What's odd is that in almost all these countries the lineage disappeared only to come back now. Artefact?

Denmark:
![image](https://user-images.githubusercontent.com/25161793/139968677-822c5e25-cabd-4e2c-a84d-82f1b287f8f0.png)

Belgium:
![image](https://user-images.githubusercontent.com/25161793/139968679-6da9dfd5-1ad1-4475-a294-556dcd6a7af8.png)

Israel:
![image](https://user-images.githubusercontent.com/25161793/139968883-70bee9ad-fb36-4cd3-b7eb-cbcfd2e07526.png)
https://nextstrain.org/groups/neherlab/ncov/israel?branchLabel=aa&c=gt-ORF7a_82&r=division

[orf7a82reversion.txt](https://github.com/cov-lineages/pango-designation/files/7464669/orf7a82reversion.txt)

Worldwide there are ~1k sequences that are mislabelled all over the place by pangoLEARN

![image](https://user-images.githubusercontent.com/25161793/139968958-c638ca4d-0fa5-4387-8972-b26ff096ab5f.png)

https://cov-spectrum.ethz.ch/explore/World/AllSamples/Past6M/variants?aaMutations=N%3AS183T%2CORF1b%3A2432I&pangoLineage=B.1.617.2*

**Comment by aineniamh** [comment]
Closing this as it is a stale issue.
