### ISSUE TITLE
Possible Lambda sub-lineage with Spike mutations D950N and Q677H (Peru and Chile, 19 sequences)

### ISSUE THREAD

**Issue by quipupe** [cov-lineages/pango-designation#303]
by Pedro E. Romero (Universidad Peruana Cayetano Heredia. Lima, Peru)

**Description:** 
Sub-lineage of: C.37 (Lambda)
Earliest sequence: 2021-09-13
Most recent sequence: 2021-10-03
Countries circulating: Peru and Chile. 
This sub-lineage present two important mutations in the Spike: D950N and Q677H. D950N is present in VOC Delta and VOI Mu. [D950N](https://www.medrxiv.org/content/10.1101/2021.06.02.21258076v3.full-text) may have led to an enhanced growth advantage of Delta by stabilizing the ACE2 receptor interaction. Q677H is present in AY.34 and P.6 lineages. [Q677H](https://journals.asm.org/doi/10.1128/mBio.02510-21) has been associated to increased viral infectivity and syncytium formation, as well as enhancing resistance to neutralization.

**Substitutions**
Gene | Mutations
-- | --
ORF1ab | A498V; T1246I; P2287S; F2387V; L3201P; T3255I; G3278S; T4175L
S | T201I; H66Q; G75V; L452Q; F4902; D614G; Q675H; **Q677H**, T859N; **D950N**
N | P13L; R203K; G204R; G214C

**Genomes**
hCoV-19/Peru/ANC-INS-7142/2021|EPI_ISL_5504590|2021-09-13
hCoV-19/Peru/ANC-INS-7141/2021|EPI_ISL_5504581|2021-09-13
hCoV-19/Peru/ANC-INS-7142/2021|EPI_ISL_5504590|2021-09-13
hCoV-19/Peru/ANC-INS-7141/2021|EPI_ISL_5504581|2021-09-13
hCoV-19/Chile/TA-154148/2021|EPI_ISL_5010697|2021-09-16
hCoV-19/Peru/ANC-INS-7277/2021|EPI_ISL_5505607|2021-09-06
hCoV-19/Peru/ANC-INS-7277/2021|EPI_ISL_5505607|2021-09-06
hCoV-19/Chile/TA-154146/2021|EPI_ISL_5010696|2021-09-16
hCoV-19/Chile/TA-154155/2021|EPI_ISL_5010701|2021-09-16
hCoV-19/Peru/ANC-INS-8014/2021|EPI_ISL_5765880|2021-09-26
hCoV-19/Peru/ANC-INS-8014/2021|EPI_ISL_5765880|2021-09-26
hCoV-19/Peru/LIM-INS-7740/2021|EPI_ISL_5764937|2021-10-03
hCoV-19/Peru/LIM-INS-7740/2021|EPI_ISL_5764937|2021-10-03
hCoV-19/Peru/ANC-INS-8015/2021|EPI_ISL_5765887|2021-09-25
hCoV-19/Peru/ANC-INS-8015/2021|EPI_ISL_5765887|2021-09-25
hCoV-19/Peru/ANC-INS-7673/2021|EPI_ISL_5595960|2021-09-21
hCoV-19/Peru/ANC-INS-7673/2021|EPI_ISL_5595960|2021-09-21
hCoV-19/Peru/ANC-INS-7670/2021|EPI_ISL_5595959|2021-09-21
hCoV-19/Peru/ANC-INS-7670/2021|EPI_ISL_5595959|2021-09-21

Most of the Peruvian samples are from Ancash (Central/Northern Peru)
![imagen](https://user-images.githubusercontent.com/65085733/140006891-19c1a01b-d39e-49f8-8459-4cbdcdab9fb0.png)

**Evidence**
![imagen](https://user-images.githubusercontent.com/65085733/140006720-001726e7-a6a7-45e9-b510-de44e8ff6c48.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42764_1e4a40.json?branchLabel=Spike%20mutations&c=gt-S_950,677&label=nuc%20mutations:T26894C

**Comment by chrisruis** [comment]
Thanks @quipupe It looks like this clade is still very small so we'll give it a monitor label for now and check back soon to see if it grows

**Comment by corneliusroemer** [comment]
S:677H is extremely homoplasic within Lambda, these are all Lambdas with S:677H on Usher.

The proposed lineage here is the one that also has S:950N

![image](https://user-images.githubusercontent.com/25161793/140516002-b1f1d4a6-db37-47d9-867c-7d493972dede.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_32a39_52c5e0.json?branchLabel=Spike%20mutations&c=gt-S_677,950&label=nuc%20mutations:G10097A,C23731T

**Comment by chrisruis** [comment]
It looks like this clade still has very few sequences so we won't designate this at this stage. Thanks again for submitting
