### ISSUE TITLE
Growing British AY.4 sub-lineage with ORF1a:T814I, ORF1a:Q3729K ORF3a:A33S [1%, 1k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#304]
Using @fritzo's mutational fitness model to look for interesting lineages on a global Neherlab tree I spotted this lineage that is predicted to have a fitness advantage (by the mutations it contains). It turns out it does seem to grow with around `2%/day` in the UK and was also spotted in some other European countries, like Poland.

Defining mutations:
```
ORF1a: T814I, Q3729K
ORF3a: A33S 
```

Sample sequence name: `hCoV-19/Wales/PHWC-PRPKPR/2021`

![image](https://user-images.githubusercontent.com/25161793/140093173-d92f5e93-fc8d-429d-a515-467b2dc626f5.png)
https://cov-spectrum.ethz.ch/explore/United%20Kingdom/AllSamples/Past6M/variants?nucMutations=G25489T%2CC29774T&pangoLineage=AY.4*

![image](https://user-images.githubusercontent.com/25161793/140093270-93758e1a-4ace-4a1e-b89c-648cfc1f8330.png)

https://nextstrain.org/groups/neherlab/ncov/united-kingdom?branchLabel=aa&c=gt-nuc_25489,29774&gt=nuc.25489T,29774T
![image](https://user-images.githubusercontent.com/25161793/140093055-91dfb3ca-5f52-417e-8d02-35da3975c279.png)

**Comment by FedeGueli** [comment]
It seems stable at 0,5% in Uk and reached 0,5% in belgium too (with few seqs).
With Ay.4.2 topping 15% now in Uk and Ay.43 steadily growing over 5% and AY.4 going steadily down from >60% to <60%, this means that this lineage has a moderate trasmission advantage on tha parental lineage and should be designated to better monitoring the epidemic

![VariantTimeDistributionChart (2)](https://user-images.githubusercontent.com/87669813/142757355-2c6264fc-3993-4108-a44e-821676939253.png)

**Comment by chrisruis** [comment]
Thanks @corneliusroemer This clade has continued to grow as a proportion of AY.4 sequences in the UK. We've therefore designated this AY.4.8 in [v1.2.110](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.110) to start on the branch with G25489T (Orf3a:A33S). Orf1ab:T814I and Orf1ab:Q3729K occur just upstream of the clade
