### ISSUE TITLE
New lineage should be broken out from B.1.170.. 39 viruses, with unique set of S mutations (international)

### ISSUE THREAD

**Issue by jpkamil** [cov-lineages/pango-designation#305]
there are 39 "B.1.170" lineage viruses carrying Spike D614G, Spike D936Y, Spike E484K, Spike H69del, Spike ins214QAS, Spike M153T, Spike T478K, Spike T859N, Spike V70del.   They can easily be found by filtering GISAID / EpiCoV for Substitutions: Spike_D936Y, Spike_M153T, Spike_T478K.   Earliest is Jan 19, 2021 collection date EPI_ISL_2443791,  hCoV-19/USA/NY-NYGC-787-VTM1-OUGT620/2021, most recent is EPI_ISL_5721629, hCoV-19/USA/MA-CDC-QDX30085067/2021, collected Oct 16, 2021.   This variant has been found mostly in USA but also in Denmark (EPI_ISL_2026009, April 2021) and Dominican Republic (EPI_ISL_2274023, March 2021).  Looks pretty interesting and has been ascendant in the face of Delta.    The S insertion at aa 214 is pretty cool too.  Tom Peacock (from Wendy Barclay's lab) suggests it might be due to copy-choice recombination with N. https://twitter.com/PeacockFlu/status/1455670152360611847?s=20

**Comment by theosanderson** [comment]
See also: https://github.com/cov-lineages/pango-designation/issues/161

**Comment by jpkamil** [comment]
Thanks, Theo!  Agree it looks the same as the one Tom Peacock opened.

**Comment by chrisruis** [comment]
Thanks @jpkamil We've now added this as B.1.639, more in #161
