### ISSUE TITLE
Growing Australian AY.39.1 sub-lineage with ORF1a:V438I, ORF3a:A59V (4k sequences)

### ISSUE THREAD

**Issue by bitbyte2015** [cov-lineages/pango-designation#307]
**Description**

Sub-lineage of: AY.39.1
Earliest sequence: 2021-06-25
Most recent sequence: 2021-10-31
Total sequences: 4111
Countries circulating: Australia

This lineage has shown growth throughout August but has since leveled out in the number of sequences detected. Of the recent samples submitted from Australia, the most recent common parent has the mutations listed under substitutions. You can see the USHER analysis of the most recent batch on AUSPICE in this screenshot

![image](https://user-images.githubusercontent.com/36325823/140613874-32637a7c-b883-46e3-87e4-60a35b40df7f.png)

The only other countries to sequence AY.39.1 are New Zealand and the US and they haven't reported any sequences of the sub-lineage. There were also 2 sequences in the UK in August visible in the screenshot below but nothing else came of it. Some of the sequences from August showed further mutations most notably ORF8:S67F which has grown to 44 sequences.

![image](https://user-images.githubusercontent.com/36325823/140614475-1b84040c-5d36-4b9b-aa89-7c3bdece2e65.png)
![image](https://user-images.githubusercontent.com/36325823/140614629-123f5aa4-522b-40c8-878e-66cf36dd242e.png)

**Substitutions**

| Gene | Mutations |
| --- | --- |
| ORF1a | V438I |
| ORF3a | A59V |

**Evidence**

From the global nextstrain tree of GISAID data:
![image](https://user-images.githubusercontent.com/36325823/140614837-bd9ce1d3-e14d-4906-9523-53d84264acd5.png)

While there is a general trend of growth, the number of samples per week remains around 300 and the proportional growth is erratic:
![image](https://user-images.githubusercontent.com/36325823/140614949-f2f73b97-6596-4e79-b396-f09897345047.png)

**Proposed Lineage Name**

AY.39.1.2

**Comment by bitbyte2015** [comment]
Something interesting: the largest sub-lineage of this has the ORF1a:I453M mutation. You can see it here: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_23b05_7c8910.json?branchLabel=aa%20mutations&c=gt-S_1020&label=nuc%20mutations:A1624G,T5338C

It's got a bit of a more pronounced growth curve:
![image](https://user-images.githubusercontent.com/36325823/140645669-a0d6efbc-e586-4e4f-9bfb-8bc752c3f79c.png)

**Comment by FedeGueli** [comment]
This sub lineage is still a large % of Delta circulating in Australia 

![VariantTimeDistributionChart](https://user-images.githubusercontent.com/87669813/145566319-58faf0c8-f3fa-4384-9dca-cd92a8037ed1.png)

**Comment by chrisruis** [comment]
Thanks @bitbyte2015 It looks like this clade has continued to increase as a proportion of AY.39.1 sequences in Australia. We've added this as AY.39.1.2 in [v1.2.110](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.110) to start on the branch with G1577A (Orf1ab:V438I) and C18555T (synonymous). Orf3a:A59V occurs one branch into the lineage so is in most AY.39.1.2 sequences
