### ISSUE TITLE
New Delta sub lineage, mainly in Estonia, Germany and Georgia with NSP12b:Q813H NSP13:V187L ORF8:F86S

### ISSUE THREAD

**Issue by Danispec12921** [cov-lineages/pango-designation#309]
With shay671

Proposal of AY.X with the mutations: NSP12b:Q813H NSP13:V187L ORF8:F86S 
First sequences : 28/6/21
Latest sequence: 18/10/21
Number of samples: 248
circulating mainly in Germany, Estonia, Georgia

![e5d16724-3017-4447-9b3f-0c865f913017](https://user-images.githubusercontent.com/93791454/140640764-f4638fee-354a-4aa0-8d4f-68222bbcf39c.jpg)

CovSpectrum:
https://cov-spectrum.ethz.ch/explore/Estonia/AllSamples/from=2021-05-01&to=2021-11-04/variants?nucMutations=C2973T%2CG16795T%2CT28150C

![f66c3e96-8475-46f6-ad69-ee98230c80ab](https://user-images.githubusercontent.com/93791454/140640755-cc303ef6-a08c-4e97-9e07-4d65535e48f0.jpg)

Nextrain Build :
https://nextstrain.org/groups/neherlab/ncov/21A.Delta?c=gt-nuc_16795,28150&label=mlabel:21A%20%28Delta%29/T13A

Usher Build 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1fa49_573db0.json?label=nuc%20mutations:G15906T

[GISAID ref list for estonian lineage.csv](https://github.com/cov-lineages/pango-designation/files/7492060/GISAID.ref.list.for.estonian.lineage.csv)

**Comment by corneliusroemer** [comment]
Still only 280 sequences, not much spread abroad. Why do you think it should be designated? Because widespread in Georgia?

It's probably best to designated Fede's #328 

PS: Please don't use solely NSP nomenclature, it's impossible to use with the most widespread tools.

**Comment by FedeGueli** [comment]
@corneliusroemer that was my fault, i encouraged  @shay671 to propose it that  i was mistakenly focusing (and monitoring)on the  future 328 one in germany  not on the real 309 one.

**Comment by chrisruis** [comment]
Thanks @Danispec12921 It looks like this clade clusters close to lineage AY.125 designated in #328 but separately and doesn't have the AY.125-defining C745T mutation. We've therefore added this clade as lineage AY.128 in [https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.111](v1.2.111) to start on the branch with C2973T (Orf1ab:A903V) and G16795T (Orf1ab:V5511L)
