### ISSUE TITLE
Problem with AY.43 assignment?

### ISSUE THREAD

**Issue by enabieva** [cov-lineages/pango-designation#310]
There may be a problem with the AY.43 assignment, at least for samples from Russia.
According to https://www.pango.network/new-ay-lineages-and-an-update-to-ay-4-ay-12/, the defining mutation in that lineage is A28299T (N:Q9L), yet of the 1,653 Russian samples that are assigned that lineage only one carries that mutation:
![image](https://user-images.githubusercontent.com/25522716/140642366-d014976d-cbea-42f3-8ce2-b0cc9a727f6a.png).  Manual examination confirms the presence of the reference base in that position in those sequences.
(Globally, as of 11/07/2021, 126,903 sequences in GISAID that are assigned AY.43 carry the N_Q9L mutation, and 92,448 do not).

**Comment by FedeGueli** [comment]
I have tried to check one of your sequences:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_aed2_7f5260.json?c=pango_lineage&label=nuc%20mutations:G1048T&tl=pango_lineage_usher

From the Usher tree it appears to be an issue in Pango assignments, Usher assigns that sequence as B.1.617.2 correctly:
It appears to belong to the large undesignated clade proposed in #268 with ORF1ab: K261N

@corneliusroemer

**Comment by FedeGueli** [comment]
I see that a lot of sequences of #268 are assigned as AY.43.


![Screenshot_2021-11-08-09-15-08-098_com android chrome](https://user-images.githubusercontent.com/87669813/140707007-653c99c0-d12c-4b01-97c5-744322c4ad56.jpg)


I think the designation of the branch with Orf1a:K216N will resolve a lot of this issue
cc
@AngieHinrichs @chrisruis @corneliusroemer

**Comment by FedeGueli** [comment]
The big orf1a:K261N lineage has been designates as AY.122 in #320 

So thos issue will be solved soon

@enabieva

**Comment by chrisruis** [comment]
Thanks @enabieva and @FedeGueli It looks like these sequences are indeed now being assigned AY.122

**Comment by FedeGueli** [comment]
I just realized that AY.43 had also a orf9b mutation : N:Q9L = ORF9b:S6C 

cc @ryhisner @thomaspeacock @corneliusroemer at that time we didnt notice that.  it could explain the clear  success of AY.43.
