### ISSUE TITLE
Correction: many AY.98 sequences currently designated as B.1.617.2 ?

### ISSUE THREAD

**Issue by theosanderson** [cov-lineages/pango-designation#311]
I was troubleshooting the behaviour of [armadillin](https://github.com/theosanderson/armadillin) which was undercalling AY.98 (green AY.98, blue B.1.617.2):
![image](https://user-images.githubusercontent.com/19732295/140658118-59e02f60-59be-4df1-84f3-2ded4c9b8a18.png)

And I noticed with https://pangotax.theo.io that a substantial number of apparently AY.98 sequences (blue below, indicating ORF1ab:87D) are designated as B.1.617.2 (circled in red):
![image](https://user-images.githubusercontent.com/19732295/140658152-89bcdf5b-0ae3-4ac9-9ecc-a9be5f500690.png)

Here is a simple list of COG-UK sequences with ORF1ab:E87D designated as B.1.617.2, which may not be 100% perfect but might still be helpful:
[e87d_designations.tsv.txt](https://github.com/cov-lineages/pango-designation/files/7492908/e87d_designations.tsv.txt)

**Comment by theosanderson** [comment]
In general this link, colouring by Usher monophyletic lineage and circling `B.1.617.2` designations may be helpful for identifying sequences which have not been redesignated when their clade was designated: https://taxodium.org/?protoUrl=https%3A%2F%2Fpangotax.vercel.app%2Foutput.taxodium.pb.gz&blinking=false&search=%5B%7B%22id%22%3A0.123%2C%22category%22%3A%22designated_lineage%22%2C%22value%22%3A%22B.1.617.2%22%2C%22enabled%22%3Atrue%2C%22aa_final%22%3A%22any%22%2C%22min_tips%22%3A1%2C%22aa_gene%22%3A%22S%22%2C%22search_for_ids%22%3A%22%22%7D%5D&colourBy=%7B%22variable%22%3A%22pango_lineage_usher%22%2C%22gene%22%3A%22ORF1ab%22%2C%22colourLines%22%3Afalse%2C%22residue%22%3A%2287%22%7D&zoomToSearch=-1

**Comment by theosanderson** [comment]
If one trusts the Usher tree there are some similar issues for AY.46 and its sublineages

**Comment by AngieHinrichs** [comment]
Thanks Theo, pangotax is brilliant for finding those!

**Comment by theosanderson** [comment]
Thanks @chrisruis !
