### ISSUE TITLE
Proposal of new sub-lineage of AY.3 for Peru  with principal mutation in Spike: T259I, A942T

### ISSUE THREAD

**Issue by IrisSilvaINS** [cov-lineages/pango-designation#312]
**Proposal for a new sub lineage of AY.3 with principal mutation in Spike: T259I, A942T in Peruvian genomes by Group of Genomic Surveillance INS-PERU**

**Description**
Sub-lineage of: Potentially new sub lineage of AY.3 (S: T259I, A942T mutations in of Peruvian genomes)
Earliest sequence: hCoV-19/Peru/JUN-INS-6934/2021(2021/09/12, Peru)
Most recent sequence: hCoV-19/Peru/LAM-INS-8260/2021(2021/10/12, Peru)

**Countries circulating**: Peru (23)

The lineage of AY.3 was designed #121 (carried mutation: ORF1a: I3731V), the genomes of new sub lineage carried two additional mutation in Spike: T259I, A942T. This potentially AY.3.X is spread pronominally in Lima, capital of Peru. 

![image](https://user-images.githubusercontent.com/93674902/140953588-6d93f48d-54a5-45c6-8e37-471fc1f0e7be.png)

**See here for further details:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1d473_a80600.json?tl=pango_lineage

**Share of all sequences in Peru**
![image](https://user-images.githubusercontent.com/93674902/140953766-f337788a-ada1-461d-9898-36acf4ae7fcf.png)

![image](https://user-images.githubusercontent.com/93674902/140953859-f51d142d-3942-49e9-8df4-683e0caae46d.png)

![image](https://user-images.githubusercontent.com/93674902/140953912-890897e0-5683-4189-862c-1f3f0c45cb7a.png)

![image](https://user-images.githubusercontent.com/93674902/140953953-dfb58b26-f128-4f6b-84b6-363991491f18.png)

**Genomes:**

[New_sub_lineage.txt](https://github.com/cov-lineages/pango-designation/files/7506002/New_sub_lineage.txt)

**Comment by corneliusroemer** [comment]
Even 12 days later, it's still only 23 sequences, which is a bit too few to warrant a designation for now [covSpectrum](https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3A259I%2CS%3A942T&pangoLineage=B.1.617.2*)

**Comment by OrsonMM** [comment]
![IRIS_2](https://user-images.githubusercontent.com/12600107/143473638-2e62154c-7b36-4bc9-844f-1c0c6b68320d.png)
![IRIS_1](https://user-images.githubusercontent.com/12600107/143473649-3a0d8a0f-a112-447c-9433-071269ff759d.png)

**Comment by chrisruis** [comment]
Thanks @IrisSilvaINS It looks like this clade has continued to circulate so we've added this as AY.3.2 in [v1.2.111](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.111) to start on the branch with C22338T (S:T259I)
