### ISSUE TITLE
Sublineage of AY.25 circulating in high proportion throughout Canada

### ISSUE THREAD

**Issue by garyvand** [cov-lineages/pango-designation#313]
New lineage proposal
by @garyvand

Description
A sublineage of AY.25 with mutations ORF1ab:D1228G (g.3948A>G) and ORF1ab:C3766F (g.11562G>T). This proposed lineage was first detected in Canada in early April, but proliferated rapidly in Western Canada in mid-July and has subsequently spread and is now circulating in substantial proportion (~45% over the last ten weeks) throughout Canada. 

Update:  A more fulsome analysis of the AY.25 lineage in Canada can be found at virological.org: [Monitoring the evolution and spread of Delta sublineages AY.25 and AY.27 in Canada](https://virological.org/t/monitoring-the-evolution-and-spread-of-delta-sublineages-ay-25-and-ay-27-in-canada/767/1)

Earliest sequence: 2021-01-02 (Israel)
Most recent sequence: Current

Countries circulating:
  
| Country             | Count | Earliest   | Latest     |
|---------------------|-------|------------|------------|
| Canada              | 7437  | 2021-04-01 | 2021-10-18 |
| USA                 | 1904  | 2021-01-14 | 2021-11-02 |
| Chile               | 1220  | 2021-01-10 | 2021-10-30 |
| Aruba               | 470   | 2021-04-10 | 2021-10-13 |
| Colombia            | 223   | 2021-06-08 | 2021-10-06 |
| United Kingdom      | 161   | 2021-06-28 | 2021-10-26 |
| Puerto Rico         | 118   | 2021-07-10 | 2021-09-28 |
| Peru                | 85    | 2021-07-22 | 2021-10-12 |
| Costa Rica          | 50    | 2021-07-01 | 2021-10-12 |
| Mexico              | 49    | 2021-06-29 | 2021-10-24 |
| U.S. Virgin Islands | 42    | 2021-06-24 | 2021-08-18 |
| Germany             | 37    | 2021-07-20 | 2021-10-25 |
| Sint Maarten        | 33    | 2021-07-30 | 2021-09-17 |
| Israel              | 33    | 2021-01-02 | 2021-09-17 |
| Luxembourg          | 26    | 2021-08-23 | 2021-10-08 |
| Netherlands         | 25    | 2021-07-11 | 2021-10-25 |
| Italy               | 19    | 2021-07-05 | 2021-10-27 |
| Argentina           | 16    | 2021-06-29 | 2021-09-07 |
| Bonaire             | 9     | 2021-08-06 | 2021-08-28 |
| Switzerland         | 9     | 2021-07-21 | 2021-10-22 |
| Spain               | 9     | 2021-08-10 | 2021-10-20 |
| France              | 8     | 2021-07-20 | 2021-10-05 |
| Lithuania           | 7     | 2021-08-05 | 2021-09-11 |
| Japan               | 6     | 2021-07-19 | 2021-09-09 |
| Portugal            | 5     | 2021-07-23 | 2021-09-27 |
| Ecuador             | 5     | 2021-07-22 | 2021-10-02 |
| Bulgaria            | 5     | 2021-08-02 | 2021-08-23 |
| Iceland             | 5     | 2021-07-09 | 2021-08-24 |
| Guatemala           | 4     | 2021-07-02 | 2021-08-06 |
| Slovakia            | 4     | 2021-08-09 | 2021-08-11 |
| Sweden              | 4     | 2021-06-22 | 2021-08-11 |
| Belgium             | 4     | 2021-07-12 | 2021-10-19 |
| Czech Republic      | 4     | 2021-09-10 | 2021-10-05 |
| The Bahamas         | 3     | 2021-07-22 | 2021-08-07 |
| Ghana               | 3     | 2021-08-12 | 2021-08-13 |
| Hong Kong           | 3     | 2021-07-18 | 2021-07-20 |
| Denmark             | 3     | 2021-08-28 | 2021-09-02 |
| Ireland             | 2     | 2021-08-26 | 2021-08-27 |
| Belize              | 2     | 2021-06-27 | 2021-06-28 |
| South Korea         | 2     | 2021-07-20 | 2021-08-02 |
| Estonia             | 2     | 2021-08-12 | 2021-09-24 |
| Jamaica             | 2     | 2021-07-22 | 2021-07-22 |
| Montenegro          | 2     | 2021-08-08 | 2021-08-26 |
| Brazil              | 2     | 2021-08-12 | 2021-08-31 |
| Guadeloupe          | 1     | 2021-08-30 | 2021-08-30 |
| Grenada             | 1     | 2021-07-26 | 2021-07-26 |
| New Zealand         | 1     | 2021-07-22 | 2021-07-22 |
| Australia           | 1     | 2021-08-21 | 2021-08-21 |
| Singapore           | 1     | 2021-10-18 | 2021-10-18 |
| Dominican Republic  | 1     | 2021-09-08 | 2021-09-08 |
| Martinique          | 1     | 2021-10-19 | 2021-10-19 |
| Curacao             | 1     | 2021-07-21 | 2021-07-21 |

    
Genomes
https://github.com/phac-nml/ay25ay27/blob/main/figures/AY.25/AY.25-A3948G-G11562T.csv

Proposed lineage: AY.25.1
 
Evidence
![](https://lh6.googleusercontent.com/i32GMM7LMakd8nefZIised8Qab4pThI4i5bgrPAJy3EPufClQ-JB_tCHRm5MIYSryyrEsBNlDif1NzixRgcMUabPWb4RCd3pv8iFLdc7_PuW8x7IFV0YS4Mtkim4ywy95S6tzDvY)

Selected mutations (≥15% difference between Canadian and non-Canadian AY.25) are annotated in tracks around the tree. The innermost track indicates if a sample is Canadian AY.25 (dark gray), non-Canadian AY.25 (light gray), or non-AY.25 from any location (uncoloured). The other tracks show the presence (coloured), absence (uncoloured), or unknown status (black) of each mutation. An unknown status is recorded when data is missing in the region of the mutation. Red-shaded tracks show mutations that are at higher frequency in Canadian AY.25 compared to non-Canadian AY.25. Blue-shaded tracks show mutations that are at higher frequency in non-Canadian AY.25 compared to Canadian AY.25.

![image](https://user-images.githubusercontent.com/89280160/141013135-f6079fec-8a84-4aaa-8d39-b8026bb7cd22.png)

**Comment by corneliusroemer** [comment]
Here's a view of just AY.25 with the proposed lineage highlighted, one could make this a sub-lineage, no strong feelings from my end. AY.25 is big, so I don't see why one wouldn't start splitting it up. 140k sequences is a lot.

<img width="2550" alt="Screenshot 2021-11-12 at 18 43 46" src="https://user-images.githubusercontent.com/25161793/141511477-5eba971d-d758-4333-98d6-0845a04fe894.png">
https://nextstrain.org/groups/neherlab/ncov/global?branchLabel=aa&c=country&f_pango_usher=AY.25&m=div

The proposed sub-lineage represents 40% of global AY.25*

Potentially more interesting could be the sub-branch with ORF1a:E767K that itself is 30% of the proposed sub-lineage and seems to be the AY.25 lineage most common in South America. It's the yellow branch at the top.

This is covSpectrum for the proposed lineage: [covSpectrum](https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF1a%3AD1228G&pangoLineage=AY.25*)

![image](https://user-images.githubusercontent.com/25161793/141512023-31edc804-56fd-4b2b-9619-45fbe90c6264.png)

**Comment by garyvand** [comment]
ORF1a:E767K is interesting, since it appears to have arisen independently multiple times within the AY.25 lineage.

**Comment by corneliusroemer** [comment]
Whenever you see apparent homoplasies like this, it's most likely a tree
building error. Where did you see it appear independently? Which tree?

**Comment by garyvand** [comment]
From the circular  tree we posted with the mutations mapped, if you look at the ORF1a:E767K (2nd outermost, blue) track it looks like independent occurrences to me.

**Comment by corneliusroemer** [comment]
How did you build this tree? In my experience, the priors for tree building
errors are much higher than for homoplasies.

**Comment by garyvand** [comment]
It's a pretty standard Augur build, built with IQtree, refined with Timetree. We just used default masking from Nexstrain. 

Here's the divergence tree 

![image](https://user-images.githubusercontent.com/89280160/141526355-55f549d0-b5ab-4600-8633-84891fcef0db.png)

**Comment by dpark01** [comment]
A little off topic, but I'm commenting just to watch the issue and also if we're considering breaking up AY.25 into a few subclades, recall that the original request [#181] that led to the definition of AY.25 could be another subclade in addition to this ([covspectrum](https://cov-spectrum.ethz.ch/explore/World/AllSamples/from=2021-06-10&to=2021-11-14/variants?nucMutations=26759G%2C20451T%2C8752T&pangoLineage=AY.25*)).

**Comment by garyvand** [comment]
Update: A more fulsome analysis of the AY.25 lineage in Canada can be found at virological.org: [Monitoring the evolution and spread of Delta sublineages AY.25 and AY.27 in Canada](Update: A more fulsome analysis of the AY.25 lineage in Canada can be found at virological.org: [Monitoring the evolution and spread of Delta sublineages AY.25 and AY.27 in Canada](https://virological.org/t/monitoring-the-evolution-and-spread-of-delta-sublineages-ay-25-and-ay-27-in-canada/767/1)

**Comment by chrisruis** [comment]
Thanks @garyvand We've added this clade as lineage AY.25.1 in [v1.2.111](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.111) to start on the branch with G11562T (Orf1ab:C3766F). This clade contains the Peru lineage designated in #355 and the Peru lineage has therefore been updated to AY.25.1.1 and still starts on the branch with G23948T (S:D796Y)
