### ISSUE TITLE
Proposal for another potential sublineage of Lambda, with spike H69N, L176F, M177W, S477N, D571E, P681H, D737E (11 seqs, Argentina)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#314]
**Description**
**Sub-lineage of**: C.37
**Earliest sequence**: 2021/8/11
**Most recent sequence**: 2021/10/7
**Countries circulating**: Argentina (CABA)

**Substitutions**:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

Spike | H69N, G75V,   T76I, L176F, M177W*, 246/252DEL, D253N, L452Q, S477N, F490S, D571E, D614G,   P681H, D737E, T859N
-- | --
ORF1a | E55K*, T1246I,   K1795Q, P2287S, F2387V, L3201P, T3255I, G3278S, 3675/3677del
ORF1b | P314L
ORF3a | A110S, K192N
ORF7b | M1I
ORF8 | P38T
ORF9b | P10S, E86D*
M | I82T
N | P13L, A90S*, A119P*,   R203K, G204R, G214C, T366I

</body>

</html>

Actually there are only 3 full-length sequences with above substitutions.

The remaining 8 sequences are partial spike gene sequences (length<900), which only have the following substitutions:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<body link="#0563C1" vlink="#954F72">

Spike | L452Q, S477N,   F490S, D571E, D614G, P681H, D737E
-- | --

</body>

</html>

So I failed to work out a UShER tree that includes all those 11 sequences.

Here's the tree for the 3 full-length sequences only:
![image](https://user-images.githubusercontent.com/86835836/141225201-b3af277a-901c-4cb8-a641-fa44b9607b37.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_11acd_c73c10.json?branchLabel=Spike%20mutations&c=gt-S_477&label=nuc%20mutations:A5648C,C21767A,C22088T,G22992A,C23275A,C23604A,T23773G,T26767C

**Genomes**:
EPI_ISL_4578887 (full length), 
EPI_ISL_4578889 (full length), 
EPI_ISL_5159273 (full length),
EPI_ISL_5656965 (partial spike gene), 
EPI_ISL_5656976 (partial spike gene), 
EPI_ISL_5657032 (partial spike gene), 
EPI_ISL_5657114 (partial spike gene), 
EPI_ISL_5657378 (partial spike gene), 
EPI_ISL_5657379 (partial spike gene),  
EPI_ISL_5657933 (partial spike gene), 
EPI_ISL_5658027 (partial spike gene).

**Comment by chrisruis** [comment]
Thanks @c19850727 It looks like there's still only 3 full length sequences with this pattern so I'll add a monitor label for now

**Comment by c19850727** [comment]
4 new sequences just popped out yesterday:
EPI_ISL_7928773, 
EPI_ISL_7928799, 
EPI_ISL_7928804,
EPI_ISL_7928808

But they are a bit old in terms of collection date, between September 23th to October 21st.

**Comment by aineniamh** [comment]
I'm going to close this issue for now as it has gone stale, if there is a need to reopen will do so!
