### ISSUE TITLE
AY.43 sublineage with ORF1a:Q563K, ORF7a:F6L, N:V270L (5% prevalence in Denmark, 1300 seqs)

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#315]
New lineage proposal
by @Sinickle

Description
Sub-lineage of: AY.43 with the mutations: C1952A, T27409C, G29081T, ORF1a:Q563K, ORF7a:F6L, N:V270L

Earliest sequence: 2021-August 31, France
Most recent sequence: Current
Countries circulating: Denmark (5%)

This sub-lineage contains 3 nonsynonymous mutations and has right around sequences, of which 99% are in Denmark. After extremely rapid growth in its first 3 weeks of appearing in Demark, in the 4 weeks since then it seems to have stabilized at around 5%. 

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1f019_ca9700.json
![image](https://user-images.githubusercontent.com/94097102/141243092-5103fd37-61f9-415b-bb2a-238538f157b0.png)

https://cov-spectrum.ethz.ch/explore/World/AllSamples/Past6M/variants?aaMutations=n%3Av270l%2Corf7a%3Af6l&pangoLineage=ay.43*
![image](https://user-images.githubusercontent.com/94097102/141243723-c55e9786-5dea-48ef-9134-89dcdf36e164.png)

https://outbreak.info/situation-reports?pango=AY.43&muts=n%3Av270l&muts=orf7a%3Af6l&muts=orf1a%3Aq563k&loc=DNK&loc=PRT&loc=FRA&loc=SWE&loc=GBR&loc=CHE&selected=DNK&overlay=false
![image](https://user-images.githubusercontent.com/94097102/141245411-30729d79-533a-43b2-a22e-caaaec781d3d.png)

**Comment by FedeGueli** [comment]
This reached around the 6% of sequences in Denmark and appears stable.
 It is around 23% of AY.43 seqs as shown from mutations frequency on CovSpectrum :
![Schermata 2021-12-10 alle 13 22 28](https://user-images.githubusercontent.com/87669813/145573628-ab01f90d-b1e8-4f55-8161-b1d2d4be5fd0.png)

Still no spread outside Denmark

**Comment by chrisruis** [comment]
Thanks @Sinickle and @FedeGueli We've added this clade as lineage AY.43.6 in [v1.2.111](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.111) to start on the branch with T27409C (Orf7a:F6L)

**Comment by FedeGueli** [comment]
Thx for your work @chrisruis
