### ISSUE TITLE
Swiss AY.43 sub-lineage with ORF1a:P1659L (contains inner lineage with extra ORF1b:G1824C S:K356R)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#317]
There's an interesting Swiss AY.43 sub-lineage that has ORF1a:P1659L [~600 seq].

This lineage has a sub-lineage itself with extra ORF1b:G1824C and S:K356R [~200 seq]

I spotted it, because I was looking at mutations at S:356 which was highlighted as a site of potential mAb resistance relevance.

Here is an Usher tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e25a_d2e4d0.json?c=gt-nuc_5241,22629&label=nuc%20mutations:C5241T

And here's a sample sequence name: 
Switzerland/TG-ETHZ-671816/2021  
OU910995.1

The outer clade seems to have grown big in East Switzerland, Sankt Gallen and Inner/Ausser-Rhoden. The age profile is interestingly skewed towards older people. It could be that this was an outbreak analysis. Which is why it has all the ages recorded. But I don't know the details.

The deeper lineage with S:K356R has been observed in Germany, England and elsewhere.

[covSpectrum](https://cov-spectrum.ethz.ch/explore/Switzerland/AllSamples/Past3M/variants?aaMutations=S%3A356R&nucMutations=C5241T&pangoLineage=AY.43*)

![image](https://user-images.githubusercontent.com/25161793/141324662-6a75e0f3-ad2f-4254-aee5-5eefa6099f21.png)

![image](https://user-images.githubusercontent.com/25161793/141324686-43cf3308-4c23-4524-ba7f-aa1ba19390e4.png)

![image](https://user-images.githubusercontent.com/25161793/141324732-f03b73f7-c306-469f-b0ba-d1654eb635d6.png)

![image](https://user-images.githubusercontent.com/25161793/141324833-08247468-bbb9-4c38-a869-c49391f8e51b.png)

**Comment by corneliusroemer** [comment]
The number of cases in the lineage with S:356 has almost doubled in a week.

Either it or its parent should be designated. Both are fine with me.

The parent would start on ORF1a:1659L, the child would be on a branch with ORF1ab:6225C and S:356R

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14c90_804a70.json?branchLabel=aa%20mutations&c=pango_lineage_usher

![image](https://user-images.githubusercontent.com/25161793/142686846-7820db4b-1256-46ba-8774-7e138cf5c96b.png)

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as AY.43.3 in [v1.2.101](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.101) starting on the branch with C5241T (Orf1ab:P1659L)
