### ISSUE TITLE
Possibly growing AY.20 sub-lineage in Czechia with ORF3a:P30L (84 sequences)

### ISSUE THREAD

**Issue by bitbyte2015** [cov-lineages/pango-designation#318]
**Description**

Sub-lineage of: AY.20
Earliest sequence: 2021-35
Latest sequence: 2021-43
Total sequences: 84
Countries circulating: Czechia, United States, United Kingdom, Mexico, France

AY.20 appears to be growing steadily exclusively in Czechia. Among the Czechian sequences of AY.20, almost all have the ORF3a:P30L mutation in common with 78 sequences total and most also have the ORF1a:A2192V mutation with 63 sequences total. Most notably, the latter has only been detected elsewhere in France during 2021-41 and in England during 2021-43 so it might make more sense to narrow down the definition to that sub-lineage

**Substitutions**

| **Spike** | **T19R, T95I, L452R, T478K, D614G, P681R, V1104L** |
|-----|-----|
| ORF1a | A599V, A1306S, A2192V* , P2046L, P2287S, T2872M, V2930L, T3255I, T3646A |
| ORF1b | P314L, G662S, P1000L, A1918V |
| ORF3a | S26L, P30L |
| ORF7a | V82A, T120I |
| ORF7b | T40I |
| M | I82T |
| N | D63G, R203M, G215C, D377Y |

*Present in most sequences

![image](https://user-images.githubusercontent.com/36325823/141341408-cfcd58fd-1ac9-4fe9-ad14-683cb4a3a699.png)

![image](https://user-images.githubusercontent.com/36325823/141341837-7c1ba670-c42b-4519-b0d9-29f53441c434.png)

![image](https://user-images.githubusercontent.com/36325823/141341926-12abb5e3-0280-41a0-92df-26426ab285e9.png)

USHER tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d634_d34790.json?branchLabel=Spike%20mutations&label=nuc%20mutations:C11173T,G25481T

CovSpectrum: https://cov-spectrum.ethz.ch/explore/Czechia/AllSamples/AllTimes/variants?aaMutations=S%3AV1104%2CORF1a%3AA599V%2CORF3a%3AR30L

**Genomes**

| Country | ORF3a:P30L | ORF1a:A2192V |
|-----|-----|-----|
| Czechia | 78 | 63 |
| United Kingdom | 2 | 2 |
| France | 1 | 1 |
| United States | 2 | 0 |
| Mexico | 1 | 0 |

[sequences(1).csv](https://github.com/cov-lineages/pango-designation/files/7522207/sequences.1.csv)

**Proposed Lineage Name**
AY.20.1

**Comment by bitbyte2015** [comment]
First Germany sequence: EPI_ISL_6190233
First Slovakia sequence: EPI_ISL_6247022

**Comment by chrisruis** [comment]
Thanks @bitbyte2015 We've added this as AY.20.1 in [v1.2.96](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.96) and started the lineage on a branch with C11173T (synonymous) and G25481T (Orf3a:R30L)
