### ISSUE TITLE
Proposal for new lineage C.2.1

### ISSUE THREAD

**Issue by leomrtns** [cov-lineages/pango-designation#32]
## New lineage proposal
Suggested by Andrew Page and Leonardo de Oliveira Martins

### Description
Sub-lineage of: C.2
Earliest sequence: 2020-11-01 (Wales/ALDP-B19FFD/2020)
Most recent sequence: 2021-02-19 (18 samples from the Caribbean)
Countries circulating: Aruba (68), Zimbabwe (18), Sint Maarten (14), Curacao (10), Netherlands (4), Denmark (4), United Kingdom (3), Australia (3), and USA (2).

Observed first in Wales and England (end Nov, beginning Dec), several samples were detected in Zimbabwe and a few in
Curacao by the end of December. Currently there is a considerably-sized cluster in the Caribbean.
Using empirical Bayesian ancestral reconstruction with IQTREE v2, three substitutions on the branch separating this
lineage from its parent, `C.2`, were estimated:  **G922T** (synonymous, *ORF1ab*) , **C28453T** (synonymous, *N*), and **C29642T** (Q29*, *ORF10*).

### Genomes
Deposited on GISAID: [lineage_C_2_1.txt](https://github.com/cov-lineages/pango-designation/files/6143163/lineage_C_2_1.txt)

### Evidence
Maximum likelihood tree of all `C.2` sequences with the proposed lineage in red and ultrafast bootstrap support values on branches.

![lineage_C_2_1 boot](https://user-images.githubusercontent.com/7119518/111191318-da1c7080-85af-11eb-8beb-d964918f4f3d.png)

Related reference: https://doi.org/10.1016/S2666-5247(21)00061-6

### Proposed lineage name: C.2.1

**Comment by andrewjpage** [comment]
It should be noted that all the red samples in this proposed lineage also have an N501T mutation, although it emerged in the branch just above the split, so ZW-41975 and WA583 and WA599 have the mutation but the rest of the black samples don't. Evolution is messy.

**Comment by chrisruis** [comment]
Thanks Leonardo and Andrew. We've added this as lineage C.2.1. However, a new pango lineage needs to be associated with an epidemiological event like an introduction into a new region. Where the virus was circulating at the root of your red clade doesn't look too clear but there is a clear introduction into Aruba/Curacao part way into your red clade. We've therefore left the Zimbabwe sequences in the red clade as C.2 and assigned the Aruba/Curacao clade as C.2.1. Thanks again
