### ISSUE TITLE
Potentially new sub-lineage of AY.102 with ORF1ab:V1765L and ORF8:W45L in Peru (100%)

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#322]
**Description**
Sub-lineage of AY.102.X with the aa mutations ORF1ab: V1765L, ORF8: W45L, and four nucleotide mutations: G5558T, G5629A, A16992G, G28027T. Proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.
**Earliest sequence:** 2021-10-04
EPI_ISL_5765119
EPI_ISL_5765142
EPI_ISL_5765124
EPI_ISL_5765133
EPI_ISL_5765134
EPI_ISL_5765141
EPI_ISL_5765123
EPI_ISL_5765147
EPI_ISL_5765154
EPI_ISL_5765148

**Most recent sequence:** 2021-10-19
EPI_ISL_6208421
**Countries circulating:** Lima, Peru (100%)
We proposed a new sub-lineage of AY.102.X with two aminoacidic mutations (ORF1ab:V1765L, ORF8:W45L) and four nucleotide mutations: G5558T, G5629A, A16992G, G28027T. This potentially new sub-lineage is principally distributed in Lima, Peru.

**Genomes:**
[Genomes.csv](https://github.com/cov-lineages/pango-designation/files/7540274/Genomes.csv)

**Evidence:**
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_hgwdev_22660_27cbb0.json?c=pango_lineage&label=nuc%20mutations:G1495T

![propuesta](https://user-images.githubusercontent.com/89021119/141822344-dd83dc61-07d2-4b98-9a68-fadf8eb3a440.jpg)
![VariantTimeDistributionChart](https://user-images.githubusercontent.com/89021119/141822367-8c884555-e37e-40d1-ba24-2c5531cf6da4.png)

![EstimatedCasesPlot](https://user-images.githubusercontent.com/89021119/141822495-c7de414b-3177-4c6b-a35b-610091b03116.png)
![VariantAgeDistributionChart](https://user-images.githubusercontent.com/89021119/141822525-6c276f59-e027-41db-acd9-89edf9c099c9.png)

![propuesta2](https://user-images.githubusercontent.com/89021119/141823570-c316786d-038b-4d89-826c-3cfd5c6f315d.jpg)

**Proposed lineage name**
AY.102.X

**Comment by chrisruis** [comment]
Thanks @Wen1953 It looks like there's still very few sequences from this clade so we haven't designated this for now
