### ISSUE TITLE
Proposal of new sub-lineage of AY.102 with additional mutation S:G1219V mainly in peruvian genomes

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#325]
**Proposal of new sub-lineage of AY.102 with additional mutation S:G1219V mainly in peruvian genomes by Group of Genomic Surveillance INS-PERU**

**Description**
Sub-lineage of: Potentially new sub-lineage of AY.102 (S: G1219V mutations mainly in Peruvian genomes)
**Earliest sequence**: hCoV-19/Peru/HUV-INS-3806/2021 (8/07/2021, Peru)
**Most recent sequence**: hCoV-19/Chile/RM-168543/2021 (18/10/2021, Chile)

**Countries circulating**
Peru (100), Chile (3)

The lineage of AY.102 was designed #272 (carried mutation: ORF1a: 3606F), the genomes of new sub lineage carried one additional mutation in Spike:G1219V and two subclades with mutations ORF1ab:M4772I (76.7%) and S:S689I (23.3%). This potentially AY.102.X is principally distributed in Lima, Peru

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/7555326/genomes.txt)

**Evidence**
![new_lineage](https://user-images.githubusercontent.com/87997149/142216117-790021fa-83a6-4ee0-8c54-8322c31b432e.png)

![VariantTimeDistributionChart (1)](https://user-images.githubusercontent.com/87997149/142222469-cfab3043-13e8-49fa-ab4f-2a2b7abaef84.png)

![VariantAgeDistributionChart](https://user-images.githubusercontent.com/87997149/142222683-d1005594-8fbb-4d81-b503-b18841b33d35.png)

![transmission_advantage](https://user-images.githubusercontent.com/87997149/142223138-92c602ba-eb50-4f2b-9ddc-284366fb1859.png)

**Proposed sub-lineage name**
AY.102.X

**Comment by corneliusroemer** [comment]
Worth watching, but I don't see how it differs much from AY.102

Let's see whether this lineage stays around for longer.

**Comment by OrsonMM** [comment]
@corneliusroemer The lineage AY.102 actually is active with1092 genomes in GISAID. And 136 genomes of sub-clade carry the mutation S:G1219V. 


![coment_2](https://user-images.githubusercontent.com/12600107/144655985-dae11661-ff9a-4a72-9306-1a9e1fce63d8.png)

**Comment by LuisBarcenaF** [comment]
![VariantTimeDistributionChart (2)](https://user-images.githubusercontent.com/87997149/144656821-dfb55e33-f816-44d5-9ee7-fcae32229aba.png)

![VariantAgeDistributionChart (1)](https://user-images.githubusercontent.com/87997149/144656837-6609a101-3b55-4eaa-99a6-49b94ddc75b0.png)

![geographic_distribution](https://user-images.githubusercontent.com/87997149/144656905-b02cc3d4-f562-44bd-bbc6-9cfa5344038d.png)

![AY 102 x](https://user-images.githubusercontent.com/87997149/144657218-8379bb69-4a0c-4c84-875d-e4dac20c2dac.png)

**Comment by chrisruis** [comment]
Thanks @LuisBarcenaF It looks like this is still circulating so we've added this as AY.102.1 in [v1.2.111](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.111) to start on the branch with G25218T (S:G1219V)
