### ISSUE TITLE
New sub-clade of P.1 (Gamma) lineage circulating in Peru with spike mutation P681H + orf1a A1809V + orf1a A3220V

### ISSUE THREAD

**Issue by Vjimenez-vasquez** [cov-lineages/pango-designation#326]
NEW SUB-CLADE OF P.1 (GAMMA) LINEAGE CIRULANTING IN PERU WITH SPIKE MUTATION P681H + ORF1a A1809V + ORF1a A3220V

Description
Sub-lineage of: Potentially new sub-lineage of P.1 (S: P681H + ORF1a A1809V + ORF1a A3220V mutations mainly in Peru)
Earliest sequence: hCoV-19/Spain/CT-HUVH-E06911/2021 EPI_ISL_4112978 (02/09/2021, Spain)
Most recent sequence: hCoV-19/Peru/ARE-INS-8025/2021 EPI_ISL_5765923 (30/09/2021, Peru)

Countries circulating
Peru (11), USA (2), Chile (1), Spain (1)

Usher Results 
![Imagen1](https://user-images.githubusercontent.com/89874227/142220358-5c266ee7-90b8-4b03-8890-790f5df3ce80.png)

RaXML and mapped mutations 
![Imagen2](https://user-images.githubusercontent.com/89874227/142220388-fec2b6a8-b614-468f-8edf-e74ba47efc40.png)

Genomes
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/7555907/genomes.txt)

**Comment by chrisruis** [comment]
Thanks @Vjimenez-vasquez In recent UShER trees, this clade clusters as a sublineage within P.1.7 and it has the S:P681H mutation that defines P.1.7. As S:681 has potentially mutated multiple times within P.1, it is possible that this clade clusters elsewhere and therefore doesn't descend from P.1.7. However, given the available evidence, designating this as a sublineage of P.1.7 seems most sensible and we can update if it becomes clear that this actually clusters elsewhere in the future. We've therefore added this as P.1.7.1 in [v1.2.111](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.111) to start on the branch with T3049C (synonymous) and C10116T (Orf1ab:T3284I). G11296T (Orf1ab:L3677F) also occurs on this branch but is highly homoplasic within P.1 and therefore potentially unreliable to determine clustering
