### ISSUE TITLE
Possible Brazilian AY.34 novel sublineage with ORF1a:T614I mutation

### ISSUE THREAD

**Issue by alex-ranieri** [cov-lineages/pango-designation#327]
By Alex Ranieri Lima, Gabriela Ribeiro, Svetoslav Slavov (Butantan Network for Pandemic Alert of SARS-CoV-2 Variants, São Paulo).

Description
Sub-lineage of AY.34
Countries circulating: Brazil, Chile

We observed an interesting clustering of the AY.34 lineage which might be suggestive for emerging sub-lineages. It includes 120 Brazilian sequences (not yet deposited on GISAID) and 2 Chilean sequences with ORF1a:T614I mutation. This can be observed in the following build: https://nextstrain.org/fetch/repositorio.butantan.gov.br/bitstream/butantan/3982/1/redeButantan_covid_EpiWeek_forty-one-to-forty-three.json?branchLabel=aa&c=possible_new_strain&f_emerging_lineage=AY.34%20%28Delta%29&p=full
This file [AY_34_new_Brazil.csv](https://github.com/cov-lineages/pango-designation/files/7565597/AY_34_new_Brazil.csv) highlight the clade by coloring with possible_new_lineage as AY.34.2. We have noticed that there is a sub-lineage AY.34.1 circulating in Brazil and Chile. However, AY.34.1 is associated with mutation G8017T (synonymous). 

We recovered our 120 sequences from this tree and used it to perform another build, using other AY.34 from GISAID (AY.34.1 sequences were not available). This resulted in the following build: https://nextstrain.org/fetch/repositorio.butantan.gov.br/bitstream/butantan/3982/3/ncov_EpiWeek_forty-one_forty-three_AY_thirty-four_Butantan.json?branchLabel=aa&p=full

A Brazilian/Chilean cluster was formed, comprising 198 sequences from Brazil and 38 from Chile. Furthermore, one sequence from France and one from Japan were observed, suggesting exportation. This file [AY_34_new_Brazil_Chile.csv](https://github.com/cov-lineages/pango-designation/files/7565667/AY_34_new_Brazil_Chile.csv)  highlight the clade by coloring with possible_new_lineage as AY.34.2. 

We also observed three possible sub-lineages within the proposed AY.34.2 clade (use this file for highlight, selecting proposed_new_lineage [AY.34.2_proposed.csv](https://github.com/cov-lineages/pango-designation/files/7565677/AY.34.2_proposed.csv)):

AY.34.2.1: 92 Brazilian sequences with branch mutation ORF1b:E2274A
AY.34.2.2: 32 Brazilian sequences with branch mutation ORF1b:R240S
AY.34.2.3: 38 Chilean sequences with mutations ORF1a: T2016I, K3832N and ORF3a: L53F

**Comment by corneliusroemer** [comment]
Looks interesting! 

Unfortunately, it's not possible to designate lineages if they consist of sequences that are not yet on GISAID - since lineage designation consists of giving some concrete sequences a label.

When do you expect to put the sequences on GISAID?

**Comment by alex-ranieri** [comment]
We'll start the deposits tomorrow. I'll let you know when we finish.

**Comment by alex-ranieri** [comment]
Most of the sequences from the first large tree are deposited. 

For the AY.34 tree, we deposited 85 of the 120: [proposed_AY.34.2_deposited.txt](https://github.com/cov-lineages/pango-designation/files/7572543/proposed_AY.34.2_deposited.txt).

 We are finishing the deposits of the remaining sequences.

**Comment by corneliusroemer** [comment]
Thanks @alex-ranieri!

It'd be amazing if you could deposit Sao Paolo sequences on a more frequent interval, say weekly. It's very interesting to see what's going on in Brazil, since it was the birth place of P.1 and has populations with very high natural immunity.

**Comment by corneliusroemer** [comment]
I think this lineage has already been designated as AY.34.1 and is thus a duplicate (at least so it looks to me)
![image](https://user-images.githubusercontent.com/25161793/142784837-87b8b7c8-3920-401d-ad29-638e34593783.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21321_ae0740.json?c=pango_lineage_usher&label=nuc%20mutations:G210T,C241T,C3037T,G4181T,C6402T,C7124T,C8986T,G9053T,G9441T,C10029T,A11201G,A11332G,C14408T,G15451A,C16466T,G18255T,C19220T,C21618G,C21846T,C22498T,T22917G,C22995A,A23403G,G23593C,C23604G,C25355T,C25469T,G26109A,C26681T,T26767C,G27014T,T27638C,C27752T,C27874T,A28461G,G28881T,G28916T,C28961T,G29402T,G29742T

**Comment by alex-ranieri** [comment]
Hi @corneliusroemer. Is this the case to update the associate mutation of AY.34.1? It is listed as G8017T (synonymous) in https://www.pango.network/summary-of-designated-ay-lineages/ . 

Regarding the GISAID deposits, we are reorganizing our flux to keep the data up to date.

**Comment by corneliusroemer** [comment]
Do you suggest that AY.34.1 should be redesignated to include only the sub-branch with 8017T?

Sure, one can do that, but does it matter?

**Comment by alex-ranieri** [comment]
When I look at our tree (https://nextstrain.org/fetch/repositorio.butantan.gov.br/bitstream/butantan/3982/3/ncov_EpiWeek_forty-one_forty-three_AY_thirty-four_Butantan.json?branchLabel=aa), the Brazilian branch contains nuc: C2106T, G8017T. 
But I don't know if it really matters.
