### ISSUE TITLE
Large European Delta sublineage with ORF3a:D27Y and ORF1b:Q813H [16k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#328]
Prevalent mostly in France, Switzerland, Germany, Italy

![image](https://user-images.githubusercontent.com/25161793/142504019-916cae8f-c047-4ca6-829e-e8834c0f69b3.png)

![image](https://user-images.githubusercontent.com/25161793/142504230-bbc622c8-44c7-4d95-93d6-dfcb90f4fe49.png)

https://cov-spectrum.ethz.ch/explore/World/AllSamples/Past6M/variants?nucMutations=C745T%2CC6730T%2CG25471T%2CA26786G

Some sequences: [ORF3a:D27Y_ORF1b:Q813H.txt](https://github.com/cov-lineages/pango-designation/files/7566308/ORF3a.D27Y_ORF1b.Q813H.txt)

Very clear branch on Usher:

![image](https://user-images.githubusercontent.com/25161793/142506596-84c66ee0-684f-4fad-bfe2-284148bc8eef.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_bba2_6ce690.json?branchLabel=Spike%20mutations&label=nuc%20mutations:C745T,C6730T,G15906T,G25471T,A26786G

**Comment by FedeGueli** [comment]
@corneliusroemer is this different from #309?
unfortunately tree from usher are unviewable after weeks i tried to match your proposal.and that from Shay but i couldnt be able to do.

**Comment by FedeGueli** [comment]
My mistake, i was thinking monitoring Orf1b:Q813H from 309, but i was monitoring this one instead! tgx @corneliusroemer for proposing

**Comment by corneliusroemer** [comment]
@chrisruis it would be very good if this parent lineage was designated, not just because it's large in itself, but also because it has a sublineage that seems interesting with four extra NTD spike mutations in Czechia: `S: V70I, A123-, T124-, Q183E`

Tip off from https://twitter.com/UseBy2022/status/1463266718252421122?s=20

![image](https://user-images.githubusercontent.com/25161793/143140891-bcdd22f4-9a24-4e6c-9404-0d764627c8aa.png)

https://nextstrain.org/groups/neherlab/ncov/czech-republic?branchLabel=Spike%20mutations%20%28internal%29&c=S1_mutations&d=tree,entropy,frequencies&m=div&p=full&tl=S1_mutations

![image](https://user-images.githubusercontent.com/25161793/143141318-58e11009-ce2e-48cc-9a70-074029e3c933.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_302d_d6f380.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G28487A

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as AY.125 in [v1.2.101](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.101) to start on a branch with C745T (synonymous) which leads to the European clade. Orf3a:D27Y occurs a few branches into this clade so is present in most sequences
