### ISSUE TITLE
Possible AY.42.1 Sublineage with S:L938F Mutation

### ISSUE THREAD

**Issue by Vaduz4892** [cov-lineages/pango-designation#331]
By Hugo Gehant & Matthew  Gustafson

Description

Sub-lineage of AY.42
Countries Circulating: Bonaire, Curacao, Netherlands, United States

We have observed a spike of AY.42 (possibly AY.42.1) within Bonaire suggesting a new sub-lineage. 145 sequences from Bonaire, another 50 from Curacao, and 31 and 30 in the Netherlands and United States respectively, suggesting exportation to the islands' owner (Netherlands) and into the U.S. Other nations have limited case numbers, these 4 are the most prevalent.

Observed: https://cov-spectrum.ethz.ch/explore/Bonaire/AllSamples/AllTimes/variants?aaMutations=S%3AL938F&pangoLineage=AY.42

UShER: https://genome.ucsc.edu/cgi-bin/hgPhyloPlace?db=wuhCor1&phyloPlaceTree=hgPhyloPlaceData/wuhCor1/public.plusGisaid.latest.masked.pb&subtreeSize=1000&remoteFile=https%3A%2F%2Fcov-spectrum.ethz.ch%2Fgisaid%2Fapi%2Fv1%2Fsample%2Fgisaid-epi-isl%3Fhost%3DHuman%26orderBy%3Drandom%26limit%3D1000%26country%3DBonaire%26dateFrom%3D2020-01-06%26aaMutations%3DS%253AL938F%26pangoLineage%3DAY.42

Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22b72_834c30.json?label=nuc%20mutations:G25690T

Apologies, this is our first submission, if something is missing please let us know.

**Comment by chrisruis** [comment]
Thanks @Vaduz4892 We've added this as AY.42.1 in [v1.2.113](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.113) to start on the branch with C24374T (S:L938F)
