### ISSUE TITLE
New growing AY.4 sublineage with Orf1a:T4083M Denmark,Italy 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#332]
A sublineage of AY.4 with Orf1a:T4083M seems to grow in some european countries

First sequences : UK 33w/2021
Last sequences Switzerland 45w/2021
Total sequences: 1937 sequences (Europe: 1907)
Europe last three months: 1626 seqs from:
Denmark: 385 seqs
UK:593 seqs
Portugal: 6 seqs
Italy: 100 seqs
Switzerland :115 seqs
![VariantTimeDistributionChart](https://user-images.githubusercontent.com/87669813/142743647-6c737ffa-5855-4c27-9629-f3662dc8f75e.png)
![Schermata 2021-11-21 alle 00 21 07](https://user-images.githubusercontent.com/87669813/142743660-db97edca-23df-4cce-870f-92044f01240d.png)

Here [CovSpectrum](https://cov-spectrum.ethz.ch/explore/Denmark/AllSamples/Past3M/variants?aaMutations=Orf1a%3AT4083M&pangoLineage=AY.4*)

Here NeherLab [Build](https://nextstrain.org/groups/neherlab/ncov/italy?branchLabel=aa&c=pango_default&d=tree&p=full&r=division&tl=pango_usher)
![Schermata 2021-11-21 alle 00 28 00](https://user-images.githubusercontent.com/87669813/142743808-7881d255-eec0-4344-86a7-be4623deefa5.png)

Here Usher tree from italian [sequences](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_269d7_97f530.json?branchLabel=aa%20mutations&label=nuc%20mutations:T17040C&tl=pango_lineage_usher)
![Schermata 2021-11-21 alle 00 30 17](https://user-images.githubusercontent.com/87669813/142743838-e3b547c9-fe1f-4041-b47b-d48ff90adfb5.png)

**Comment by corneliusroemer** [comment]
I agree @FedeGueli, this one should be designated
![image](https://user-images.githubusercontent.com/25161793/142784494-3ebe3fb7-cc94-4e52-996d-215692fc9b39.png)

@chrisruis

**Comment by FedeGueli** [comment]
Waiting for the last italian survey if it is devlining i will vlose this one

**Comment by FedeGueli** [comment]
UPDATE on this proposal:
I found that there are two AY.4 subclades with Orf1a:T4083M circulating in Europe:
The first one with 
Nuc: C3140T, T4066A, C12513T
AA: ORF1a:P959S, Orf1a:T4083M
1034 sequences in the last three months in Europe (0,1%)
mainly in Italy, Germany, France, Switzerland, Uk and lately spotted in Romania.
[CovSpectrum Lineage 1](https://cov-spectrum.org/explore/Romania/AllSamples/Past3M/variants?aaMutations=orf1a%3AT4083M%2CORF1a%3AP959S&nucMutations=C3140T%2CT4066A%2CC12513T)

The second one with:
nuc: C337T, C920T, C12513T, T29604C
AA: ORF1ab: T4083M, ORF10: L16P
324 sequences in the last three months in Europe
mainly in Italy, Denmark and Romania
[CovSpectrum Lineage2](https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?aaMutations=Orf1a%3AT4083M&nucMutations=C337T%2CC920T%2CC12513T%2CT29604C&pangoLineage=AY.4*)

And here the [Usher tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1c140_9bb5e0.json?branchLabel=aa%20mutations&label=nuc%20mutations:T17040C) of the last month italian sequences.


At this point i dunno how to manage this proposal , if you spare some time, please check this @chrisruis @corneliusroemer

**Comment by chrisruis** [comment]
Thanks @FedeGueli In recent UShER trees, there's at least 5 clades within AY.4 that have acquired Orf1ab:T4083M. They have quite distinct paths of mutations leading to them and don't have other convergent mutations. We can't see any obvious reason for these being artefacts but can't rule it out

2 of the clades are quite large and we've designated these as AY.4.9 and AY.4.10, both starting on the branch with C12513T (Orf1ab:T4083M). These lineages also have the following mutations:
AY.4.9 - T17040C
AY.4.10 - T8604C G20663A C5512T G25757T C10714T C23996T

The other 3 clades with Orf1ab:T4083M are quite small so we've designated these as AY.4 for now to try to prevent mis-assignments.

These changes are in [v1.2.117](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.117)

**Comment by FedeGueli** [comment]
Thx for resolving this issue! Merry Xmas @chrisruis !

**Comment by chrisruis** [comment]
Thanks @FedeGueli Hope you've had a good Christmas

**Comment by FedeGueli** [comment]
Thx @chrisruis  i have read just now ;)
