### ISSUE TITLE
Proposal for sublineage of AY.43 with Spike:N501S in Portugal [~60 sequences]

### ISSUE THREAD

**Issue by insapathogenomics** [cov-lineages/pango-designation#335]
**New lineage proposal – AY.43 with Spike:N501S in Portugal**
By: Bioinformatics Unit, National Institute of Health Dr Ricardo Jorge (INSA), Portugal

**Description**
Sub-lineage of: AY.43
Earliest sequence: 2021-10-23
Most recent sequence: 2021-11-09
Countries circulating: Portugal

In Portugal, we have been detecting AY.43 sequences with the additional mutations Spike:N501S, ORF8:A51V and N:R195I. The first case was detected on 23 October 2021. Since then, in our weekly national sampling (~500/week), we have been observing an increase in relative frequency and its dissemination through several districts. The low genetic diversity found within this cluster suggests that all cases are likely linked to a single source/introduction.

**Genomes**
Portugal/PT19662/2021	EPI_ISL_6012260	23/10/2021	Portugal
Portugal/PT19816/2021	EPI_ISL_6012587	26/10/2021	Portugal
Portugal/PT19886/2021	EPI_ISL_6012657	26/10/2021	Portugal
Portugal/PT20038/2021	EPI_ISL_6012817	26/10/2021	Portugal
Portugal/PT20077/2021	EPI_ISL_6012857	26/10/2021	Portugal
Portugal/PT20252/2021	EPI_ISL_6267378	27/10/2021	Portugal
Portugal/PT20256/2021	EPI_ISL_6267382	30/10/2021	Portugal
Portugal/PT20278/2021	EPI_ISL_6267404	29/10/2021	Portugal
Portugal/PT20324/2021	EPI_ISL_6267451	31/10/2021	Portugal
Portugal/PT20327/2021	EPI_ISL_6267454	01/11/2021	Portugal
Portugal/PT20434/2021	EPI_ISL_6267563	02/11/2021	Portugal
Portugal/PT20437/2021	EPI_ISL_6267566	02/11/2021	Portugal
Portugal/PT20439/2021	EPI_ISL_6267568	02/11/2021	Portugal
Portugal/PT20445/2021	EPI_ISL_6267574	02/11/2021	Portugal
Portugal/PT20486/2021	EPI_ISL_6267615	02/11/2021	Portugal
Portugal/PT20634/2021	EPI_ISL_6267767	01/11/2021	Portugal
Portugal/PT20672/2021	EPI_ISL_6267805	02/11/2021	Portugal
Portugal/PT20695/2021	EPI_ISL_6587945	05/11/2021	Portugal
Portugal/PT20700/2021	EPI_ISL_6587950	07/11/2021	Portugal
Portugal/PT20713/2021	EPI_ISL_6587963	06/11/2021	Portugal
Portugal/PT20731/2021	EPI_ISL_6587981	08/11/2021	Portugal
Portugal/PT20734/2021	EPI_ISL_6587984	08/11/2021	Portugal
Portugal/PT20739/2021	EPI_ISL_6587989	05/11/2021	Portugal
Portugal/PT20804/2021	EPI_ISL_6588056	09/11/2021	Portugal
Portugal/PT20904/2021	EPI_ISL_6588159	08/11/2021	Portugal
Portugal/PT20909/2021	EPI_ISL_6588164	08/11/2021	Portugal
Portugal/PT20918/2021	EPI_ISL_6588173	09/11/2021	Portugal
Portugal/PT20928/2021	EPI_ISL_6588183	08/11/2021	Portugal
Portugal/PT20945/2021	EPI_ISL_6588200	05/11/2021	Portugal
Portugal/PT20946/2021	EPI_ISL_6588201	06/11/2021	Portugal
Portugal/PT20992/2021	EPI_ISL_6588247	09/11/2021	Portugal
Portugal/PT20994/2021	EPI_ISL_6588249	08/11/2021	Portugal
Portugal/PT20995/2021	EPI_ISL_6588250	09/11/2021	Portugal
Portugal/PT21000/2021	EPI_ISL_6588255	09/11/2021	Portugal
Portugal/PT21046/2021	EPI_ISL_6588304	06/11/2021	Portugal
Portugal/PT21052/2021	EPI_ISL_6588310	08/11/2021	Portugal
Portugal/PT21057/2021	EPI_ISL_6588315	05/11/2021	Portugal
Portugal/PT21071/2021	EPI_ISL_6588329	08/11/2021	Portugal
Portugal/PT21079/2021	EPI_ISL_6588337	07/11/2021	Portugal
Portugal/PT21088/2021	EPI_ISL_6588346	07/11/2021	Portugal
Portugal/PT21125/2021	EPI_ISL_6588383	08/11/2021	Portugal
Portugal/PT21129/2021	EPI_ISL_6588387	08/11/2021	Portugal
Portugal/PT21134/2021	EPI_ISL_6588394	08/11/2021	Portugal
Portugal/PT21139/2021	EPI_ISL_6588399	08/11/2021	Portugal
Portugal/PT21155/2021	EPI_ISL_6588415	06/11/2021	Portugal
Portugal/PT21156/2021	EPI_ISL_6588416	06/11/2021	Portugal
Portugal/PT21158/2021	EPI_ISL_6588418	07/11/2021	Portugal
Portugal/PT21163/2021	EPI_ISL_6588423	02/11/2021	Portugal
Portugal/PT21165/2021	EPI_ISL_6588425	02/11/2021	Portugal
Portugal/PT21166/2021	EPI_ISL_6588426	02/11/2021	Portugal
Portugal/PT21167/2021	EPI_ISL_6588427	02/11/2021	Portugal
Portugal/PT21168/2021	EPI_ISL_6588428	02/11/2021	Portugal
Portugal/PT21170/2021	EPI_ISL_6588430	04/11/2021	Portugal
Portugal/PT21171/2021	EPI_ISL_6588431	05/11/2021	Portugal
Portugal/PT21172/2021	EPI_ISL_6588432	05/11/2021	Portugal
Portugal/PT21173/2021	EPI_ISL_6588433	05/11/2021	Portugal
Portugal/PT21175/2021	EPI_ISL_6588435	05/11/2021	Portugal
Portugal/PT21176/2021	EPI_ISL_6588436	06/11/2021	Portugal

**Comment by FedeGueli** [comment]
Thank you for proposing it! I noticed it in your super useful weekly report

**Comment by corneliusroemer** [comment]
There seem to be very few sequences so far, on the order of ~20? Should be monitored but in my eyes too early for designation.

[covSpectrum](https://cov-spectrum.ethz.ch/explore/Portugal/AllSamples/AllTimes/variants?aaMutations=S%3AN501S&pangoLineage=AY.43*)

![image](https://user-images.githubusercontent.com/25161793/142869226-3ec325fc-244a-4130-8f02-e46d6bae7510.png)

**Comment by insapathogenomics** [comment]
There are currently 58 sequences on GISAID as a result of our latest national sampling. We are currently working on our weekly report (to be released tomorrow - https://insaflu.insa.pt/covid19/) where we will provide further details about its dissemination trends.

**Comment by corneliusroemer** [comment]
Thanks @insapathogenomics. I'm wondering about why you say you have 58 and covSpectrum shows only 17.

When did you add the sequences? Could it be in the last few days, meaning that covSpectrum will get the remaining 40 sequences over the next few days?

**Comment by MCB6** [comment]
> Could it be in the last few days, meaning that covSpectrum will get the remaining 40 sequences over the next few days?

41 of the 58 have been added today
![image](https://user-images.githubusercontent.com/93294184/142880576-017949d6-da5a-4357-896c-5b1a9c289c3c.png)

**Comment by insapathogenomics** [comment]
We do not know the delay between GISAID and covSpectrum update. The complete GISAID accession list of the 58 AY.43+S:N501S sequences is above.

**Comment by corneliusroemer** [comment]
Ok, so that's the explanation, you added 41 of 58 only today.

**Comment by insapathogenomics** [comment]
We have now release our short weekly report (https://insaflu.insa.pt/covid19/), highlighting the marked increase in relative frequency of the AY.43+ Spike N501S:  0.2% (week 42), 1.4% (w 43), 7.6% (w 44), 4.9% (w 45, sampling not closed); It was already detected in 13 Districts (from 18 Districts and 2 Archipelagos), since its first detection on 23 October 2021 (i.e., in roughly two weeks). According to this scenario, we believe a new sub-lineage assignment would greatly help monitoring its spread nationally and its eventual circulation abroad. 
![image](https://user-images.githubusercontent.com/87025402/143012167-3087ca55-5bf9-458b-8b54-7871b4d7374c.png)

**Comment by FedeGueli** [comment]
Quite impressive growth.

@chrisruis @corneliusroemer

**Comment by agolsby** [comment]
![AY 43withS501S](https://user-images.githubusercontent.com/9949952/143355637-29bc925e-35ef-4b64-bb8c-c830e0edc7af.png)

Your recent uploads are now visible on CoV-Spectrum Dr. Jorge, and their model is spitting out a 58-106% transmission advantage.

**Comment by MCB6** [comment]
did it stop growing? Nothing in this week's uploads from Portugal, and covSpectrum shows the most recent frequency at 3.6% (but with a lot of uncertainty due to low sample count)
https://cov-spectrum.ethz.ch/explore/Portugal/AllSamples/AllTimes/variants?aaMutations=S%3AN501S&pangoLineage=AY.43

**Comment by MCB6** [comment]
511 genomes from Portugal uploaded yesterday. The decline of S:N501S share appears to have continued.
![image](https://user-images.githubusercontent.com/93294184/144068681-51672485-390e-4306-8b88-d3af588cf2c2.png)

**Comment by insapathogenomics** [comment]
Just a brief update from Portugal:
- This “AY.43+S:N501S” keeps circulating in Portugal, representing ~4% in our latest national sampling.
- After a brief search of the combination “AY.43 + S_N501S + N_R195I + ORF8_A51V” in the GISAID database, we found recent matches from Switzerland, Belgium, Italy, Spain and Israel:

Virus name	Accession ID	Collection date
hCoV-19/Switzerland/SO-ETHZ-34522806/2021	EPI_ISL_6721802	22/10/2021
hCoV-19/Belgium/ULB-IBC_CV8207975302/2021	EPI_ISL_6812799	19/11/2021
hCoV-19/Italy/LAZ-IFO-11133045/2021	EPI_ISL_6815736	13/11/2021
hCoV-19/Spain/MD-HGUGM-5818715/2021	EPI_ISL_6854457	19/11/2021
hCoV-19/Israel/SMC-7022022/2021	EPI_ISL_6859810	06/11/2021

Taking into account this scenario (i.e., considerable circulation in Portugal and recent detections abroad), we stress that sub-lineage assignment can greatly help monitoring its spread.

**Comment by chrisruis** [comment]
Thanks @insapathogenomics We've added this as AY.43.5 in [v1.2.105](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.105) to start on the branch with A23064G (S:N501S)
