### ISSUE TITLE
Possible new delta sub-lineage with N:K373N; ORF3a:A54S, Q213H; Spike:A222V, I834T; ORF1ab:A903V, A5692S misclassified as AY.119 and B.1.617.2.

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#336]
**Description**
Delta sub-lineage with the aa mutations: N:K373N; ORF3a:A54S, Q213H; Spike:A222V, I834T; ORF1ab:A903V, A5692S, and nucleotide mutations: C100T, C2973T, G17338T, C22227T, T24063C, G25552T, G26031T, T26621C, and G29392T. New possible sub-lineage proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**Earliest sequence:**  2021-09-28
hCoV-19/Chile/AP-160309/2021 (EPI_ISL_5879962) 
hCoV-19/Chile/AN-PUC_MVL_1725/2021 (EPI_ISL_6125676)

**Most recent sequence:** 2021-11-06
hCoV-19/Chile/LL-UACH-00654/2021 (EPI_ISL_6569305)

**Countries circulating:** 
Peru (30), Chile (27), Brasil (3), USA (1), Francia (1).

Here we proposed a new sub-lineage of delta with seven aminoacidic mutations (N:K373N; ORF3a:A54S, Q213H; S:A222V, I834T; ORF1ab:A903V, A5692S) and nine nucleotide mutations (C100T, C2973T, G17338T, C22227T, T24063C, G25552T, G26031T, T26621C, and G29392T) possibly misclassified as AY.119 and B.1.617.2. This potentially new sub-lineage is mainly spread around Peru and Chile.

**Genomes**

[Genomes.csv](https://github.com/cov-lineages/pango-designation/files/7582461/Genomes.csv)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f39d_bb24f0.json?branchLabel=Spike%20mutations&c=gt-S_222,834

![new_sublineage](https://user-images.githubusercontent.com/89021119/142893200-44b03633-b220-4ad4-b623-93e92c959fd2.png)

![cov3](https://user-images.githubusercontent.com/89021119/142894435-99a8c738-31bd-4482-9407-7d33f3ab2b44.png)
![cov2](https://user-images.githubusercontent.com/89021119/142894465-73c1da4c-5198-4471-aacc-3387aa1d6614.png)

![cov](https://user-images.githubusercontent.com/89021119/142894630-1bccd128-78cc-4227-993f-bca5e516c5a6.png)

**Proposed lineage name**
AY.X?

**Comment by OrsonMM** [comment]
Actually Peru (39) And Chile (42)
![Peru](https://user-images.githubusercontent.com/12600107/144278539-55e3e46b-88d1-4824-9173-8ece236c490a.png)

![Chile](https://user-images.githubusercontent.com/12600107/144278555-6697e139-26f3-4609-9f11-42afaa35714c.png)

**Comment by chrisruis** [comment]
Thanks @Wen1953 It looks like this clade is within AY.119 as it clusters within AY.119 in the UShER tree and has the AY.119-defining mutation. We've therefore added this as AY.119.1 in [v1.2.105](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.105) to start on the branch with G17338T (Orf1ab:A5692S),T24063C (S:I834T), G25552T (Orf3a:A54S) and G29392T (N:K373N)

**Comment by Wen1953** [comment]
Thanks, @chrisruis ! We will continue monitoring the new AY.119.1 and potential sublineages of SARS-CoV-2 from Peru.
