### ISSUE TITLE
European AY.43 sublineage with nuc:C829T [9k seq]

### ISSUE THREAD

**Issue by Vaduz4892** [cov-lineages/pango-designation#338]
Hugo Gehant & Matthew Gustafson

AY.43 Sublineage

Circulating in Germany, UK, Switzerland, France

As stated within the AY.43.3 proposal, we observed that the potential AY.43.3 was exported into Europe and has spread there, mainly within Germany. The lineage appears to be starting in Germany rather than Chile, suggesting that a mutation occurred within Germany after exportation.

Attached:

https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants?nucMutations=C829T&pangoLineage=AY.43

UShER: https://genome.ucsc.edu/cgi-bin/hgPhyloPlace?db=wuhCor1&phyloPlaceTree=hgPhyloPlaceData/wuhCor1/public.plusGisaid.latest.masked.pb&subtreeSize=1000&remoteFile=https%3A%2F%2Fcov-spectrum.ethz.ch%2Fgisaid%2Fapi%2Fv1%2Fsample%2Fgisaid-epi-isl%3Fhost%3DHuman%26orderBy%3Drandom%26limit%3D1000%26dateFrom%3D2020-01-06%26nucMutations%3DC829T%26pangoLineage%3DAY.43

Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_152b8_c3c730.json

Again, if anything is missing please let us know so we can add it.

**Comment by corneliusroemer** [comment]
I'm confused about this proposal. What is the relation to the other AY.43 sublineage proposal #337? Is this one a child of #337? Or the other way round?

Can you say a bit more about all the mutations starting from AY.43 that are in this supposed lineage?

**Comment by corneliusroemer** [comment]
I think I understand now, this is just another AY.43 sublineage.

It's a bit tricky to make lineages differ by only a single mutation. I'd hold back on this one.

![image](https://user-images.githubusercontent.com/25161793/142958942-8cb8d9c1-db37-4fcd-8a48-c753d9499d5e.png)

https://nextstrain.org/groups/neherlab/ncov/europe?branchLabel=aa&c=gt-nuc_829&f_pango_usher=AY.43&label=Spike%20mutations:I95T&m=div

**Comment by FedeGueli** [comment]
It seems growing in France and Germany, but it is hard to disentangle its growth from the parental lineage growth:
C839T France
![VariantTimeDistributionChart (8)](https://user-images.githubusercontent.com/87669813/142989214-01105b3c-0dd8-4894-b3b7-66fedb1d8dc6.png)
AY.43
![chrome_screenshot_1637655064436](https://user-images.githubusercontent.com/87669813/142989425-e3534511-92e7-40fd-a298-a7f9d8175c99.png)

**Comment by chrisruis** [comment]
Thanks @Vaduz4892 It looks like this clade has remained at a relatively consistent proportion of AY.43 sequences in Europe through time. We therefore haven't split this out from AY.43 at this stage
