### ISSUE TITLE
Potential Sublineage of AY.39.1 with ORF1a:E633D and S:P1162A (~2k Seqs, ~9% in Australia)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#339]
This is an effort to fine-tune AY.39.1, the currently predominant lineage in Australia (~90% prevalence).

According to NeherLab:
![image](https://user-images.githubusercontent.com/86835836/142959173-2f43fa77-b07e-432d-a853-f48c34f782f9.png)
https://nextstrain.org/groups/neherlab/ncov/oceania-australia?branchLabel=aa&c=gt-nuc_1577,25046,15046,26187,1684&f_country=Australia&label=insertions:frameshift:%20ORF7a:77-122&p=full&r=division

There are 4 subclades that are visibly distinct:
- The one on the top with ORF1a:V438I and ORF3a:A59V, already submitted on  #307   by @bitbyte2015.
- The second one with ORF1a:E633D and S:P1162A, prevalent in ACT and later NSW;
- The third with nuc T26187C, prevalent in VIC and later NSW;
- The last one with nuc G13482A, nuc G29179T and ORF1b:I527V, from NSW.

Here I would like to submit the subclade with ORF1a:E633D and S:P1162A.

**Description**
**Sub-lineage of**: AY.39.1
**Earliest sequence**: 2021/7/25 (Australia-NSW)
**Most recent sequence**: 2021/11/13 (Australia-NSW)
**Countries circulating**: Australia (ACT and NSW)

Prevalence in each state as per Cov-spectrum is as follows:
![image](https://user-images.githubusercontent.com/86835836/142971305-b2dd0257-b968-4318-81df-b6785129664d.png)

Transmission advantage as per Cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/142971452-525dbe07-4c0f-48e2-968a-b15750efd67d.png)

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as AY.39.1.3 in [v1.2.113](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.113) to start on the branch with C25046G (S:P1162A)
