### ISSUE TITLE
Proposal for sub-lineage R.1.1.

### ISSUE THREAD

**Issue by stephlunn-ky** [cov-lineages/pango-designation#34]
### By:
Kentucky State Public Health Lab. Stephanie Lunn, Vaneet Arora, Karim George, Josh Tobias, William Grooms, Matthew Johnson, Rachel Zinner, Rhonda Lucas.

**Bioinformatics contact**: Stephanie Lunn, _stephanie.lunn@ky.gov_ 
**Scientific/general questions**: Arora Vaneet _vaneet.arora@ky.gov_

### Description
**Sub-lineage of**: R.1.
**Earliest sequence**: 2021-01-08 (as of 2021-03-22)
**Most recent sequence**: 2021-03-08 (as of 2021-03-22)
**Countries circulating**: United States
A distinct cluster within the R.1 lineage (figure 01, purple lineage) with amino acid mutation ORF1a:A2584T was found circulating in New York, Maryland, Kentucky, and Ohio (figure 02, putative sub-lineage in yellow). First appearance appears to be in Maryland and New York before introduction into Kentucky. Kentucky cluster associated with outbreak and has a now proven ability to cause vaccine breakthrough infections and reinfections in unvaccinated and vaccinated individuals.

### Genomes
[R1_ORF1aA2584T.txt](https://github.com/cov-lineages/pango-designation/files/6189580/R1_ORF1aA2584T.txt)

### Evidence
_Figure 01. R.1 lineage_
<img width="468" alt="image" src="https://user-images.githubusercontent.com/81186257/112146063-80203a00-8bb1-11eb-952d-0c329ab769e7.png">

_Figure 02. Putative sub-lineage with amino acid mutation ORF1a:A2584T_
<img width="468" alt="image" src="https://user-images.githubusercontent.com/81186257/112146088-88787500-8bb1-11eb-8cad-4ce04e939df2.png">

### Proposed Sub-Lineage Name
R.1.1

**Comment by agmcarthur** [comment]
>Kentucky cluster associated with outbreak and has a now proven ability to cause vaccine breakthrough infections and reinfections in unvaccinated and vaccinated individuals.

Is this data publicly available as a virological post or pre-print?

**Comment by stephlunn-ky** [comment]
Hi @agmcarthur, thank you for your question. This is in relation to the outbreak that Kentucky recently announced to the media (within the past week). An outbreak occurred in a long-term care facility in which vaccinated individuals (including one reinfection) were positive for SARS-CoV-2. Specimens were sent to the KY state lab for sequencing. A manuscript is currently in the works, I do not yet have a pre-print available.

**Comment by rambaut** [comment]
Hi @agmcarthur - thanks for this. To help with the designation process it is useful if a non-time-tree (i.e., genetic divergence branch lengths) is provided and if the tree has descriptive tip labels (i.e. with date and geographical location). Alternatively, a live link to the NextStrain instance can be very useful. Thanks.

**Comment by stephlunn-ky** [comment]
Hi @rambaut 

Thank you for your response. The KY State PH Lab does not have a live nextstrain build, but I am able to show an image of a non-time-tree. Additionally, we are working on a publication that discusses the relationship between this cluster seen in KY and the vaccine breakthrough infections and reinfections in unvaccinated and vaccinated individuals and it should be released soon.

<img width="1550" alt="R1" src="https://user-images.githubusercontent.com/81186257/114051527-2713ff80-985b-11eb-941e-4df1192add69.png">

**Comment by chrisruis** [comment]
Hi, thanks very much for submitting this and adding the tree. A new Pango lineage needs to be associated with an epidemiological event, such as an introduction into a new country. I've attached the tree for all current R.1 sequences below - red sequences are from the USA, blue sequences are from Japan and the yellow clades are predominantly European sequences. There's clearly sustained transmission of R.1 in multiple locations, including the USA. However, given the structure of the R.1 tree, its very difficult to identify introductions into different regions and therefore to identify sublineages within R.1 under the Pango rules. Therefore, currently, we need to classify the whole of this clade as the R.1 lineage with this lineage circulating in multiple locations. We can revisit this to assign sublineages if there's more geographical resolution in this clade in the future. Hope that makes sense and thanks again for submitting this

![R 1_tree](https://user-images.githubusercontent.com/47785131/114053906-44f75980-9887-11eb-8f7e-9fd7c7c37ee0.png)
