### ISSUE TITLE
Potential Sublineage of AY.39.1 with nuc T26187C (~3.3k Seqs, ~18% in Australia)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#340]
This is an effort to fine-tune AY.39.1, the currently predominant lineage in Australia (~90% prevalence).

According to NeherLab:
![image](https://user-images.githubusercontent.com/86835836/142974686-0c1f00b6-21de-484f-962e-5233809462b3.png)
https://nextstrain.org/groups/neherlab/ncov/oceania-australia?branchLabel=aa&c=gt-nuc_1577,25046,15046,26187,1684&f_country=Australia&label=insertions:frameshift:%20ORF7a:77-122&p=full&r=division

There are 4 subclades that are visibly distinct:

- The one on the top with ORF1a:V438I and ORF3a:A59V, already submitted on #307  by @bitbyte2015.
- The second one with ORF1a:E633D and S:P1162A, prevalent in ACT and later NSW;
- The third with nuc T26187C, prevalent in VIC and later NSW;
- The last one with nuc G13482A, nuc G29179T and ORF1b:I527V, from NSW.

Here I would like to submit the subclade with nuc T26187C.

**Description**
**Sub-lineage of**: AY.39.1
**Earliest sequence**: 2021/8/1 (Australia-VIC)
**Most recent sequence**: 2021/11/16 (Australia-NSW)
**Countries circulating**: Australia (VIC and NSW)

Prevalence in each state as per Cov-spectrum is as follows:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/itine/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/itine/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

States | Number of Samples | Prevalence
-- | -- | --
Australian Capital Territory | 4 | 0.3%
New South Wales | 169 | 1.0%
Queensland | 9 | 0.9%
South Australia | 9 | 1.7%
Tasmania | 1 | 0.5%
Victoria | 3208 | 16.5%

</body>

</html>

Transmission advantage as per Cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/142974790-8d024525-8a4c-4140-9d6b-ef1748a6538e.png)

Usher tree:
![image](https://user-images.githubusercontent.com/86835836/142974993-dd3e8d18-70e5-4f4b-845f-57549838ba8f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d73_c78e20.json?branchLabel=Spike%20mutations&c=gt-nuc_26187&l=radial

**Comment by chrisruis** [comment]
As this clade appears to be declining and is associated only with a nucleotide mutation with no amino acid mutation, we haven't designated this at this stage. Thanks @c19850727 for submitting
