### ISSUE TITLE
New AY.X lineage with mutations ORF3a:G49V, ORF3a:T221K, S:T95I growing in India, Germany, Denmark, UK, US 

### ISSUE THREAD

**Issue by bitbyte2015** [cov-lineages/pango-designation#342]
Sub-lineage of: B.1.617.2
Earliest sequence: 2021-16
Latest sequence: 2021-45
Total sequences: 4706

A large proportion of AY.102 sequences with the above mutations are misclassified and the lineage appears to be growing across many European countries. The lineage appears to have emerged from India around April 2021 and was first detected in Germany in July 2021. Since then it has grown to 9% in India, 2% in Denmark, and 1% in Germany. It also appears to be recently emerging in the UK and US. 

![image](https://user-images.githubusercontent.com/36325823/142979876-b2e87904-5bc4-4505-9a8c-1460dafd3026.png)

USHER puts it on an entirely new branch of B.1.617.2 but I'm not sure if S:T95I emerged independently or if it's a part of the existing S:T95I branch.

![image](https://user-images.githubusercontent.com/36325823/142980050-3e580797-6f21-472e-81c6-9ba616e4871f.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2cf05_c87280.json?branchLabel=Spike%20mutations

![image](https://user-images.githubusercontent.com/36325823/142980981-d4fde6db-24f6-4893-8476-672d2bb95c1f.png)

Transmission advantage is hard to determine but it appears to be around 10-15% for Germany. 

https://cov-spectrum.ethz.ch/explore/World/AllSamples/Y2021/variants?aaMutations=ORF3a%3AG49V%2CORF3a%3AT221K%2CS%3AT95I

|Gene|Mutation|
|-----|-----|
|ORF3a|G49V, T221K|
|S|T95I|

|Country|Sequences|
|-----|-----|
|India|552|
|Denmark|920|
|Germany|523|
|United Kingdom|745|
|United States|420|

[sequences(2).csv](https://github.com/cov-lineages/pango-designation/files/7586210/sequences.2.csv)

Proposed Lineage Name: AY.X

**Comment by FedeGueli** [comment]
Nice catch.
ir seems growing in Switzerland
![VariantTimeDistributionChart (11)](https://user-images.githubusercontent.com/87669813/142991721-67e6f6cb-d94e-4c88-80b1-a770971cc44c.png)
Denmark
![VariantTimeDistributionChart (10)](https://user-images.githubusercontent.com/87669813/142991758-b26ea4b1-4f88-4d61-bf5d-b54d8127192c.png)
Uk (although low numbers)
![VariantTimeDistributionChart (9)](https://user-images.githubusercontent.com/87669813/142991826-12c94b5c-4099-4749-b7d6-67e2222983a5.png)

Considering the efficacy of sequencing in these countries and considering that especially in Uk the most trasmissible AY.s are widely circulating i think it deserves a designation @corneliusroemer

**Comment by FedeGueli** [comment]
Hi @corneliusroemer @chrisruis looking at the trend of this lineage in Denmark i think the designation is well supported:
![VariantTimeDistributionChart (6)](https://user-images.githubusercontent.com/87669813/144146173-4b90c269-6b49-4447-b346-68a75ec022bf.png) (Denmark last month)

[CovSpectrum](https://cov-spectrum.ethz.ch/explore/Denmark/AllSamples/from=2021-10-30&to=2021-12-01/variants?aaMutations=ORF3a%3AG49V%2CORF3a%3AT221K%2CS%3AT95I)

**Comment by chrisruis** [comment]
Thanks @bitbyte2015 We've added this as AY.127 in [v1.2.105](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.105) to start on the branch with G25538T (Orf3a:G49V)
