### ISSUE TITLE
B.1.1 decendant associated with Southern Africa with extremely high number of Spike mutations

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#343]
**New proposed lineage**
By Tom Peacock

**Description**
**Sub-lineage of:** B.1.1
Earliest Sequence: 2021-11-11
Latest Sequence: 2021-11-13

Countries circulating: Botswana (3 genomes), Hong Kong ex S. Africa (1 genome, partial)

Description:
**Conserved Spike mutations -** A67V, Δ69-70,   T95I, G142D/Δ143-145,   Δ211/L212I, ins214EPE, G339D,   S371L, S373P, S375F, K417N, N440K, G446S, S477N, T478K, E484A, Q493K, G496S,   Q498R, N501Y, Y505H, T547K, D614G, H655Y, N679K, P681H, N764K, D796Y, N856K, Q954H,   N969K, L981F

**Conserved non-Spike mutations -** NSP3 – K38R, V1069I, Δ1265/L1266I, A1892T; NSP4 – T492I; NSP5 – P132H; NSP6 – Δ105-107, A189V; NSP12 – P323L; NSP14 – I42V; E – T9I; M – D3G, Q19E, A63T; N – P13L, Δ31-33, R203K, G204R

Currently only 4 sequences so would recommend monitoring for now. Export to Asia implies this might be more widespread than sequences alone would imply. Also the extremely long branch length and incredibly high amount of spike mutations suggest this could be of real concern (predicted escape from most known monoclonal antibodies)

**Genomes:**
EPI_ISL_6590608 (partial RBD Sanger sequencing from Hong Kong)
EPI_ISL_6640916
EPI_ISL_6640919
EPI_ISL_6640917

**Evidence:**
![image](https://user-images.githubusercontent.com/79373149/143054896-b1f03930-2844-4f63-9457-392a3b4d06e4.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_17ae0_cf96f0.json

**Proposed lineage name:** B.1.1.X

**Comment by georgimarinov** [comment]
Would we be even calling this a "variant" if we were not in the middle of the pandemic? If all you have is one sequence of SARS-CoV-2 and one sequence of this, sampled from bats, you probably call them "strains" and give them different designations...

**Comment by silcn** [comment]
Many of these S mutations aren't exactly common and quite a few are extremely rare. Aside from S371L which is unsurprisingly new since it is a 2nt mutation, all of N856K, Q954H, N969K, L981F have been seen fewer than 100 times. Q493K and Y505H were seen in the New York wastewater samples but are uncommon in humans (<200 samples). Lots more are rare enough that one wouldn't suspect they were advantageous. It's extremely unlikely that so many inconsequential mutations would accumulate in the spike rather than being more evenly spread through the genome, so the logical conclusion is that most of them are not inconsequential - even those ones from 856 to 981.

Compare this with B.1.640 for example, where even the more odd-looking polymorphisms like N394S had been seen at least several hundred times before. (F490R was new but again that's a 2nt mutation.)

I'm not saying this is spillback from an animal reservoir after a year of adaptations in that species, but if that were to happen, this is the sort of thing it might look like.

**Comment by silcn** [comment]
Also, has any sequencing been done on the outbreak among students in Pretoria which is partly responsible for SA's recent rise in cases? It has all the signs of being driven by a new variant (very localised sudden rise in cases).

**Comment by thomasppeacock** [comment]
Additional sequence from South Africa: EPI_ISL_6647961

**Comment by thomasppeacock** [comment]
Futher sequences from South Africa (flagged by @shay671)
EPI_ISL_6590608
EPI_ISL_6640916
EPI_ISL_6640919
EPI_ISL_6640917
EPI_ISL_6640916
EPI_ISL_6640919
EPI_ISL_6647956
EPI_ISL_6647957
EPI_ISL_6647958
EPI_ISL_6647959
EPI_ISL_6647960
EPI_ISL_6647962

**Comment by georgimarinov** [comment]
> Futher sequences from South Africa (flagged by @shay671) EPI_ISL_6590608 EPI_ISL_6640916 EPI_ISL_6640919 EPI_ISL_6640917 EPI_ISL_6640916 EPI_ISL_6640919 EPI_ISL_6647956 EPI_ISL_6647957 EPI_ISL_6647958 EPI_ISL_6647959 EPI_ISL_6647960 EPI_ISL_6647962

This is getting real bad then.

If this is the SARS-CoV-3 that it looks to be, then we are essentially restarted the pandemic as I am not sure if this is even going to be competing with Delta given that there is next to zero doubt that there is zero cross neutralization. And this should have a gigantic advantage on immune escape.

The fact that there are already that many sequences shows it has legs and it's not going to go away on its own...

**Comment by georgimarinov** [comment]
Also, the South Africa ones all seem to be from Gauteng, Which is the province in which cases are rising right now...

**Comment by corneliusroemer** [comment]
Looks interesting, should definitely get designated soon.

**Comment by theosanderson** [comment]
Interesting that these make up 100% of November-collected Gauteng sequences yet have at least slightly different location data around Johannesburg and a range of sampling strategies (one vaccine breakthrough, others surveillance), on the face of it suggesting high prevalence there

**Comment by c19850727** [comment]
One of the patient (EPI_ISL_6647962) is 0 year old baby girl, meaning it's a household transmission.

Three of the sequences from South Africa have additional location information. Two of them are from Ekurhuleni (EPI_ISL_6647959 and EPI_ISL_6647956), and the other from Johannesburg Metro (EPI_ISL_6647957). These two places are ~70KM away from each other.

OR Tambo airport is in the Ekurhuleni
 region.

The case detected in Hong Kong only stayed in South Africa for ~20 days. He tested positive while being asymptomatic at the 2nd PCR test 3 days after returning to Hong Kong from South Africa, which means it's likely that he got infected just before boarding the returning flight - and OR Tambo airport is in Ekurhuleni.

**Comment by silcn** [comment]
> Edit: scratch that, the insertion is clearly human genome-derived. Unless that bit is shared with other mammals...?

For what it's worth, the relevant section of the TMEM245 gene is identical in rhesus macaques (in fact it matches for one additional base!) but has a few differences in mice. So could theoretically be spillover from primates, but that seems less likely than an extremely prolonged infection in a human.

**Comment by MCB6** [comment]
> NSP4 – T492I

Interestingly this is the same ORF1b:T2163I which we've just heard about a few hours earlier in the context of #337 where it was seen as a unique addition to AY.43 potentially giving it a super-infectivity edge.

**Comment by nik-dolittle** [comment]
> This is getting real bad then.
> 
> If this is the SARS-CoV-3 that it looks to be, then we are essentially restarting the pandemic as I am not sure if this is even going to be competing with Delta given that there is next to zero doubt that there is zero cross neutralization. And even if it is directly competing, it should have a gigantic advantage on immune escape in vaccinated populations.
> 
> The fact that there are already that many sequences shows it has legs and it's not going to go away on its own...

We don't know anything yet. 

A bunch of spike mutations doesn't automatically mean that this is an escape variant that could pose a threat for vaccinated or recovered people. We also don't know if it can compete against Delta regarding infectivity regarding unvaccinated and vaccinated/recovered populations. 

Delta comprises of R203M and P681R which seem to enhance fitness greatly whereas this variant hast R203K (which one paper suggested doesn't enhance replication as much as R203M) and P681H in the FCS.

Still, that much mutations isn't pretty with many of them in the NTD which some papers suggested may play a crucial role when mutating (ADE-like behaviour, but it was in a pre print and silico only).

**Comment by georgimarinov** [comment]
> We don't know anything yet.

We actually do -- we have measured neutralization for another RBD sequence with that many mutations, and it was completely resistant to all monoclonals. 

https://www.medrxiv.org/content/10.1101/2021.07.26.21261142v1

WNY4 there had the following:

K417T 
N439K 
K444N 
Y449R 
L452R 
N460K 
S477N 
del484 
F486V 
S494T 
G496V 
Q498Y 
N501T 
G504D 
Y505H 
H519Q

And that it should be so evasive is obvious just from the sequence anyway -- we have multiple charge altering mutations in each of the key epitopes. 

It does not have P681R, but why do we think P681R is the key to the universe? It was seen in many variants other than Delta, and those went nowhere, so clearly there is a context dependence. Who is to say N679K+P681H in this context is not sufficiently fit on its own?

>R203M

And this has both R203K and G204R, right in the same spot.

But most importantly, with very high certainty, this shows essentially zero cross-neutralization with Delta.

There was a measurement of the cross-neutralization of Beta with Delta serum, and the reduction was 34x (Delta on Beta was 12x). Which is huge. 

https://www.medrxiv.org/content/10.1101/2021.09.14.21263564v1

But Beta has 3 RBD mutations and Delta has 2, 5 differences in total.

This thing has 15, one of them common with Delta.

What do you think the cross-neutralization is?

Is it even going to be competing with Delta other than through viral interference? 

And it does not have to be competitive on raw transmissibility -- if vaccination reduces Delta transmission by 50-70%, but there is a variant against which it only has a 5-10% effect, that variant should outcompete Delta in highly vaxxed and recently swept through areas, even if it is somewhat less transmissible (as long as it is not drastically less transmissible).

We had it bad enough in 2020 -- lots of areas that already let it rip back then were infected at 70%+ levels.

**Comment by FedeGueli** [comment]
thx all for comments and additional info 🙏.
N679K was doing quite well in the last P.1 sublineages,

**Comment by chrisruis** [comment]
Thanks @thomasppeacock We've added this as B.1.1.529 in [v1.2.100](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.100)

**Comment by drmutaba** [comment]
Sure, those papers show a massive reduction in neutralization titres and I certainly don't want to downplay the implications of such a variant (happened far enough in the past two years). And yes, when it can evade most (polyclonal) antibodies it most probably could outcompete Delta in vaccinated and recovered populations, which is quite likely regarding the antigenic drift seen here. But I don't want to come to a conclusion when we only have parts of a puzzle.

What we now need is a quick evaluation (neutralization assay / tests for infectivity, replication) of this variant.

**Comment by harpham** [comment]
> One of the patient (EPI_ISL_6647962) is 0 year old baby girl, meaning it's a household transmission.
> 
> Three of the sequences from South Africa have additional location information. Two of them are from Ekurhuleni (EPI_ISL_6647959 and EPI_ISL_6647956), and the other from Johannesburg Metro (EPI_ISL_6647957). These two places are ~70KM away from each other.
> 
> OR Tambo airport is in the Ekurhuleni region.
> 
> The case detected in Hong Kong only stayed in South Africa for ~20 days. He tested positive while being asymptomatic at the 2nd PCR test 3 days after returning to Hong Kong from South Africa, which means it's likely that he got infected just before boarding the returning flight - and OR Tambo airport is in Ekurhuleni.

But did he not fly Cape Town to Doha to Hong Kong- rather than via Johannesburg?

**Comment by rambaut** [comment]
I have locked the conversation on this issue as this Github is not intended for general discussion or speculation.

**Comment by chrisruis** [comment]
The original post initially had an incorrect mutation at Spike 493 - this should be Q493R and is now updated in the original post
