### ISSUE TITLE
Broaden AY.121 to branch with ORF3a:V202L and rename AY.121 -> AY.121.1

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#344]
First suggested by @mg14:

The designated lineage is part of a wider branch, roughly defined by ORF3a:202L, which is present in Eastern Europe and the Near East at frequencies between 10-25%. These comprise about 1% of sequenced cases globally, probably more due to oversampling in Western Europe and the US. 

Would it make sense to define this ancestral branch as `AY.121` and the current lineage with Orf7a:A82V as `AY.121.1` to reflect the larger global structure? 

[covSpectrum](https://cov-spectrum.ethz.ch/explore/World/AllSamples/from=2021-05-01&to=2021-11-06/variants?aaMutations=Orf3a%3AV202L&pangoLineage=B.1.617.2*)

![image](https://user-images.githubusercontent.com/6615711/142436145-43887bd5-b08b-442d-b78a-369302333408.png)

![image](https://user-images.githubusercontent.com/6615711/142437984-45067b04-30fa-49f1-8c6d-cf832cbe0686.png)

_Originally posted by @mg14 in https://github.com/cov-lineages/pango-designation/issues/301#issuecomment-972939658_

**Comment by corneliusroemer** [comment]
Here's my independent comment:

Going through a subsampled Europe tree, I independently spotted the large clade defined by `ORF3a:V202L` respectively `nuc: C13168T, G25996T` that @mg14 talks about above.

I support renaming AY.121 into the broader lineage and making the Polish sub lineage AY.121.1.

I'll open this as a separate issue.

![image](https://user-images.githubusercontent.com/25161793/143285867-956a87ac-6435-4d41-9b30-ebd8ff6bb943.png)

**Comment by AngieHinrichs** [comment]
Would broadening AY.121 lead to the appearance of a sudden increase in AY.121 cases?  We went in a different direction with AY.12 --> AY.122.1 and the addition of AY.122 as the larger ancestral branch.

**Comment by corneliusroemer** [comment]
Yes, it would cause a large increase in AY.121, so one could move to AY.126/AY.126.1

In this case, because AY.121 has only been out for a week I'd be fine with either option.

**Comment by AngieHinrichs** [comment]
Good point @corneliusroemer, it is much newer than AY.12.  It was in pango-designation v1.2.93 which was in pangoLEARN release 2021-11-09 (which was released 8 days ago, Nov. 16th) and has made it as far as GISAID, where it's currently found in 7,696 sequences.  I guess the cat's not very far out of the bag, and in the excitement about B.1.1.529, probably AY.121 is relatively safe from being overhyped.  :)  I'm fine with whatever you prefer, @chrisruis .

**Comment by chrisruis** [comment]
I think in this case the best thing to do is expand lineage AY.121 to be a European lineage and update the Poland/Germany clade that was previously AY.121 to AY.121.1.

So we've now expanded AY.121 so it represents the large European clade and starts on a branch with G25996T (Orf3a:V202L).

The clade that was previously designated AY.121 is now designated AY.121.1 and starts on a branch with C27737T (Orf7a:T115I). There were previously 3 defining mutations for this clade but it looks like the branch leading to it has partly been filled in with recently added sequences so this mutation is now the only one on the immediately ancestral branch.

These changes are in [v1.2.102](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.102)

**Comment by FedeGueli** [comment]
i manually compared all the designated and some proposed  to AY.4.2* using the new powerful Covspectrum tool: Interestingly AY.121.1 is the designated sublineage of Delta with more growth rate advantage in comparison to AY.4.2*(all sublineages) baseline.
Here i put the chart of the lineages with more growth rate advantage:
AY.36+ORF3A:T322I+N:6L    +20% (#407)
AY.121.1                                    +8%
AY.127+S:859N                       +7% (#404)
AY.43.4+S:356R                      +6%, 
AY.122.3                                    +5%,
AY.132                                       +5% 
AY.4.2.2                                     +5%
AY.133                                        +3%
AY.43.4                                       +2%
AY.43.6                                        +2%
AY.4.2.1 :                                       +1%  
AY.4.2.3                                          +1%
