### ISSUE TITLE
21J sublineage defined by ORF1a:S443F, ORF1b:P2612T [5k seq, 20% in Portugal]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#345]
On branch containing ORF1a:K3353R

Defining mutations: ORF1a:S443F, ORF1b:P2612T, nuc:21301A

[covSpectrum](https://cov-spectrum.ethz.ch/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AK3353R&nucMutations=C1593T%2CC13971T%2CA10323G&pangoLineage=B.1.617.2*)

![image](https://user-images.githubusercontent.com/25161793/143288568-5bff391e-a83c-470d-9396-b1ebe889af01.png)

https://nextstrain.org/groups/neherlab/ncov/europe?branchLabel=aa&c=gt-nuc_21301

It contains an interesting sublineage with S:144- that's slowly growing in Portugal

![image](https://user-images.githubusercontent.com/25161793/143290234-058d5ac7-0f5a-43de-ba2a-194b1ce1a091.png)

**Comment by FedeGueli** [comment]
Hi @corneliusroemer i have focused on this clade while waiting for designation of the broader one that came yesterday, i think the most worrying is the sublineage of this proposed sublineage with N:A119S please check if you save time

**Comment by chrisruis** [comment]
The overall clade is designated AY.124. The sublineage with N:A119S appears to have gradually increased as a proportion of total AY.124 sequences in Portugal up to >30% of AY.124 in Portugal in recent weeks. We've therefore added the sublineage with N:A119S as AY.124.1 in [v1.2.108](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.108)

**Comment by FedeGueli** [comment]
In the insaflu i noticed that a subclade has picked up S:484Q. put here to monitor.
