### ISSUE TITLE
Potential inconsistent duplicates: USA/WA-UW133/2020 B.1 and USA/WA-UW-133/2020 A.1

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#346]
Are the sequences `USA/WA-UW133/2020` and `USA/WA-UW-133/2020` different?

If not, we have two different lineage designations for the same sequence:
```
B.1 USA/WA-UW133/2020 
A.1 USA/WA-UW-133/2020
```

There are more potential examples like this in the designations. I noticed because I'm matching pango strain names to nextstrain strain names by reducing all strain names to alphanumeric characters.

Those are further potential duplicates
```
taxon_pango_name	lineage_designation_pango	strain_name_Nextstrain
Netherlands/Gelderland_1-2/2020	A	Netherlands/Gelderland_12/2020
USA/IL-UW-349/2020	A	USA/IL-UW349/2020
USA/WA-UW-383/2020	A.1	USA/WA-UW383/2020
USA/WA-UW195/2020	A.1	USA/WA-UW195/2020
USA/WA-UW114/2020	A.1	USA/WA-UW-114/2020
USA/WA-UW114/2020	A.1	USA/WA-UW114/2020
USA/WA-UW201/2020	A.1	USA/WA-UW201/2020
USA/WA-UW-201/2020	A.1	USA/WA-UW201/2020
USA/WA-UW383/2020	A.1	USA/WA-UW383/2020
USA/WA-UW-197/2020	A.1	USA/WA-UW197/2020
USA/WA-UW-191/2020	A.1	USA/WA-UW191/2020
USA/WA-UW-114/2020	A.1	USA/WA-UW-114/2020
USA/WA-UW-114/2020	A.1	USA/WA-UW114/2020
USA/WA-UW-185/2020	A.1	USA/WA-UW185/2020
USA/WA-UW-192/2020	A.1	USA/WA-UW192/2020
USA/WA-UW-194/2020	A.1	USA/WA-UW194/2020
USA/WA-UW-195/2020	A.1	USA/WA-UW195/2020
USA/WA-UW-133/2020	A.1	USA/WA-UW-133/2020
USA/WA-UW-133/2020	A.1	USA/WA-UW133/2020
USA/WA-UW197/2020	B	USA/WA-UW197/2020
Netherlands/Gelderland_12/2020	B.1	Netherlands/Gelderland_12/2020
USA/WA-UW133/2020	B.1	USA/WA-UW-133/2020
USA/WA-UW133/2020	B.1	USA/WA-UW133/2020
USA/IL-UW-353/2020	B.1	USA/IL-UW353/2020
USA/IL-UW353/2020	B.1	USA/IL-UW353/2020
USA/WA-UW194/2020	B.1.1	USA/WA-UW194/2020
Netherlands/Overijssel_22/2020	B.1.190	Netherlands/Overijssel_22/2020
USA/WA-UW191/2020	B.1.371	USA/WA-UW191/2020
USA/WA-UW192/2020	B.1.371	USA/WA-UW192/2020
USA/IL-UW349/2020	B.3	USA/IL-UW349/2020
USA/WA-UW185/2020	B.39	USA/WA-UW185/2020
Netherlands/Overijssel_2-2/2020	B.55	Netherlands/Overijssel_22/2020
```

**Comment by corneliusroemer** [comment]
Alright, on GISAID I can only find one of the two, so they are probably real duplicates that should be canonicalised.

Can find the one without dash `UW133`: 
![image](https://user-images.githubusercontent.com/25161793/143505564-36827897-2256-4a5e-b65e-cd7fcf26e742.png)

But not with dash
![image](https://user-images.githubusercontent.com/25161793/143505627-c3541a81-a55f-48cf-8085-542ea649e3b2.png)

**Comment by corneliusroemer** [comment]
For a different strain name, a `-` dash seems to make an actual difference. Very confusing.
![image](https://user-images.githubusercontent.com/25161793/143505816-0989e3e5-f1da-4e3a-8355-be5459f43088.png)
![image](https://user-images.githubusercontent.com/25161793/143505819-35a88509-d859-4314-a164-26de2f4a94ba.png)

**Comment by aineniamh** [comment]
These seqeunces have different EPI ids, so presumably are different sequences? I'm going to close now as issue has gone stale.
