### ISSUE TITLE
Omicron: Why were sequences removed from designation list

### ISSUE THREAD

**Issue by Viromic** [cov-lineages/pango-designation#347]
What happened to these sequences formerly designated omicron?

EPI_ISL_6647956
EPI_ISL_6647957
EPI_ISL_6647958
EPI_ISL_6647959
EPI_ISL_6647960
EPI_ISL_6647962

**Comment by corneliusroemer** [comment]
They were removed because their sequence quality was not great. They had some long stretches of N.

Better omicron sequences were designated in their place. Can you confirm @chrisruis ?

**Comment by Viromic** [comment]
﻿
﻿
Hmm long stretches of N 

is perhaps 
a qlue here  mechanistically and technically  
on the emergence  
and a hint that 
might be of interest here as this is an RNA world and cross over events on N 
N2 etc at high levels despite poor quality ? 
A co infection co-evolution  recombination event  etc immunosupressed 
as this is terra incognita and early days 
perhaps widening the scope of investigations is prudent? 

It also will be good to know if  the tools at hand are fit for purpose inherent limitations and biases etc 

One was from an antilope it seems so we asked for the raw files to look closer

**Comment by Viromic** [comment]
﻿that is just to get to bottom of things that is 
﻿
All  (as far as it goes for now ) SARS-CoV-2 variants of interest or concern defined by the WHO contain at least one mutation with >50% penetrance within seven amino acids (N:199-205) in the nucleocapsid (N) protein, which is required for replication and RNA binding, packaging, stabilization and release (8). 

> ﻿
> ﻿
> ﻿
> Hmm long stretches of N  sounds familiar 
> 
> is perhaps 
> a qlue here  mechanistically and technically  
> on the emergence  
> and a hint that 
> might be of interest here as this is an RNA world and cross over events on N 
> N2  Nx etc at high levels despite poor quality since these Ns  actually were picked up 

> A co infection co-evolution  recombination event  etc immunosupressed 
> as this is terra incognita and early days 
> perhaps widening the scope of investigations is prudent awaiting of clinical manifestations 
> 
> It also will be good to know if  the tools at hand are fit for purpose inherent limitations and biases etc 
> 
> One was from an antilope it seems so we asked for the raw files to look closer at the raw files 
> 
> 
> 
> 
> 
> 
> Sent from my iPhone

**Comment by chrisruis** [comment]
What @corneliusroemer says is right
