### ISSUE TITLE
Many of these S mutations aren't exactly common and quite a few are extremely rare. Aside from S371L which is unsurprisingly new since it is a 2nt mutation, all of N856K, Q954H, N969K, L981F have been seen fewer than 100 times. Q493K and Y505H were seen in the New York wastewater samples but are uncommon in humans (<200 samples). Lots more are rare enough that one wouldn't suspect they were advantageous. It's extremely unlikely that so many inconsequential mutations would accumulate in the spike rather than being more evenly spread through the genome, so the logical conclusion is that most of them are not inconsequential - even those ones from 856 to 981.

### ISSUE THREAD

**Issue by leontpearson** [cov-lineages/pango-designation#348]
Many of these S mutations aren't exactly common and quite a few are extremely rare. Aside from S371L which is unsurprisingly new since it is a 2nt mutation, all of N856K, Q954H, N969K, L981F have been seen fewer than 100 times. Q493K and Y505H were seen in the New York wastewater samples but are uncommon in humans (<200 samples). Lots more are rare enough that one wouldn't suspect they were advantageous. It's extremely unlikely that so many inconsequential mutations would accumulate in the spike rather than being more evenly spread through the genome, so the logical conclusion is that most of them are not inconsequential - even those ones from 856 to 981.

Compare this with B.1.640 for example, where even the more odd-looking polymorphisms like N394S had been seen at least several hundred times before. (F490R was new but again that's a 2nt mutation.)

I'm not saying this is spillback from an animal reservoir after a year of adaptations in that species, but if that were to happen, this is the sort of thing it might look like.

Edit: scratch that, the insertion is clearly human genome-derived. Unless that bit is shared with other mammals...?

_Originally posted by @silcn in https://github.com/cov-lineages/pango-designation/issues/343#issuecomment-977132989_

**Comment by rambaut** [comment]
This github is not intended for general discussion of this nature.
