### ISSUE TITLE
lineage_notes.txt entry for B.1.638 has a space as separator instead of a tab

### ISSUE THREAD

**Issue by matthuska** [cov-lineages/pango-designation#350]
The lineage_notes.txt file contains a lineage name, a tab separator, and then a description of some type. The entry for B.1.1638 is the only one that uses a space as a separator instead. This might cause problems for people who are explicitly splitting the fields using a tab.

**Comment by chrisruis** [comment]
Thanks for spotting that @matthuska Now updated to a tab
