### ISSUE TITLE
Potential Sublineage of AY.106, with Spike Y248S, S255F and I434V (56 seqs, ~12% prevalence in Bahrain)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#351]
**Description**
**Sub-lineage of**: AY.106 (56 sequences)
**Earliest sequence**: 2021/10/22 (Bahrain)
**Most recent sequence**: 2021/11/6 (Bahrain)
**Countries circulating**: Bahrain

**Mutations in addition to AY.106**: 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<body link="#0563C1" vlink="#954F72">

Gene | Substitutions
-- | --
Spike | Y248S, I434V
ORF3a | G49V
nuc | A691G, C1549T, C6040T, C14790T, A19068G

</body>

</html>

Because of nuc C6040T they are misclassified as AY.44 by Pango at the moment.

**Genomes**:
EPI_ISL_5632735, EPI_ISL_5632740-5632742, EPI_ISL_5632745-5632746,
EPI_ISL_5632757, EPI_ISL_5632759, EPI_ISL_5632795,
EPI_ISL_5632805-5632808, EPI_ISL_5632842, EPI_ISL_5632844,
EPI_ISL_5632847-5632849, EPI_ISL_5632855, EPI_ISL_5632861,
EPI_ISL_5632868, EPI_ISL_5632876, EPI_ISL_5632882,
EPI_ISL_5632890-5632891, EPI_ISL_5632920, EPI_ISL_5632947,
EPI_ISL_5632974, EPI_ISL_5632996, EPI_ISL_5633037,
EPI_ISL_5633053-5633057, EPI_ISL_5633077, EPI_ISL_5931346-5931347,
EPI_ISL_5931366, EPI_ISL_5931379, EPI_ISL_5931391,
EPI_ISL_5931404, EPI_ISL_5931407-5931408, EPI_ISL_5931525,
EPI_ISL_5931530, EPI_ISL_5931541, EPI_ISL_5931582,
EPI_ISL_5931597-5931598, EPI_ISL_5931600-5931601, EPI_ISL_6011933,
EPI_ISL_6266450, EPI_ISL_6266454, EPI_ISL_6266549

**Evidence**
Down-sampled tree as per Neherlab (Asia-Bahrain, and filtered to AY.106):
![image](https://user-images.githubusercontent.com/86835836/143943883-46dc2320-f804-4793-8594-807dfcd920a0.png)

Country distribution as per Neherlab (Asia-Bahrain):
![image](https://user-images.githubusercontent.com/86835836/143944151-36136a96-bfa3-4c7b-b9f3-bb9f9ab35ab3.png)

Georgraphical prevalence as per Neherlab:
![image](https://user-images.githubusercontent.com/86835836/143944770-f921513e-4c3e-422a-b62d-157220c2f1cc.png)
https://nextstrain.org/groups/neherlab/ncov/asia-bahrain?branchLabel=aa&c=gt-S_434&f_pango_usher=AY.106&label=Spike%20mutations:S255F&p=full&r=division

USHER tree (in yellow color):
![image](https://user-images.githubusercontent.com/86835836/143944287-e66847bd-6e46-44dd-a9dc-fd001d8dd5d5.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_e30c_f369c0.json?c=gt-S_434&l=radial

Transmission advantage as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/143944423-4c71e7e2-3583-4c13-8c10-dc6f10c9c46a.png)
https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/Bahrain/AllSamples/AllTimes/variants?aaMutations=S%3AI434%2CS%3AS255%2CS%3AY248S

**Comment by chrisruis** [comment]
Thanks @c19850727 It looks like this clade descends from B.1.617.2 rather than AY.106 and both this clade and AY.106 have convergently acquired S:S255F. We've therefore added this as AY.130 in [v1.2.113](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.113)
