### ISSUE TITLE
Potential Sublineage of Issue #342 with Spike T859N (~550 seqs, 100% Prevalence in Djibouti)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#352]
The parent lineage of this potential sublineage has been submitted by @bitbyte2015 in #342 , and is yet to be designated.

**Description**
**Sub-lineage of**: #342  (~550 sequences)
**Earliest sequence**: 2021/8/12 (Belgium)
**Most recent sequence**: 2021/11/19 (Norway)
**Countries circulating**: Djibouti (100% prevalence, based on very limited sequences), Sweden (~3% prevalence), Norway (~1.6% prevalence), and a few other European countries 

Mutations in addition to #342 :

<html>
<body>

Gene | Substitutions
-- | --
Spike | T859N
nuc | G242A, T7816C

</body>
</html>

**Genomes**:
[#342+T859N.csv](https://github.com/cov-lineages/pango-designation/files/7622752/342%2BT859N.csv)

**Evidence**

Transmission advantage as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/143982677-33c2240a-eb73-4a3e-81b2-51200a275df0.png)

International comparison as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/143982720-f69d9229-0a7c-442d-a18a-c0a17b44ee8b.png)
https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3AT859N&nucMutations=G242A

Usher tree:
![image](https://user-images.githubusercontent.com/86835836/143983184-d1a424ee-0bb9-4602-9ef1-d16b5fed382b.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f990_5a05c0.json?c=gt-nuc_242&l=radial

**Comment by chrisruis** [comment]
Thanks @c19850727 The Djibouti sequences are in a subclade of the clade with S:T859N. It looks like the proportion of AY.127 sequences with S:T859N has stayed relatively constant so we haven't designated the complete AY.127 clade. We've instead started this lineage on the branch with A19445G (Orf1ab:K6394R) which likely coincides with the introduction(s) into Djibouti. We've added this as AY.127.1 in [v1.2.114](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.114)

**Comment by FedeGueli** [comment]
Hi @chrisruis cc @corneliusroemer @AngieHinrichs 

I think things had changed since:
AY.127+S:T859N accounts now for 30% of total AY.127* sequences
![chrome_screenshot_1642337382521](https://user-images.githubusercontent.com/87669813/149660666-25d4a543-0478-45e9-8387-5639857aba14.png)


i am going to open an issue to broaden AY.127.1 starting from S:T859 and to rename the branch of it with orf1b:k1993R AY.121.1.1
