### ISSUE TITLE
Small B.1.637 sublineage in USA with Spike Δ244-247, G446R, T478R and P681R

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#353]
**New proposed lineage**

**Description**
**Sub-lineage of:** B.1.637
Earliest Sequence: 2021-09-21
Latest Sequence: 2021-11-19

**Countries/States circulating:** USA (5x New York state, 2x Massachusetts, 1x Washington state)

**Description:**
**Conserved Spike mutations -** **Δ69-70***, D80G, **E96Q***, Δ144, F157S, **Δ244-247**, **A264V***, **G446R**, L452R, **T478R**, D614G, **P681R**, T859N, **D936H***, D950H, **N978S*** (mutations in bold are on top of the normal B.1.637 definition, mutations with asterisks are found in majority, but not all sequences)

**Conserved non-Spike mutations -** **NSP1 – I114T**; NSP2 – T85I; **NSP3 – S400G***, **T557I, V1209A**; NSP4 – **S163F***, K399E, L438P, A446V, **T492I**; NSP6 – Δ106-108, V278I; NSP12 – **Y32C***, P323L; ORF3a – **L15F**, P42L, Q57H, P104L, **S171L**, **del255***; **M – I82T**; ORF8 – T11I, A51S; N – **P13L**, T205I, M234I (mutations in bold are on top of the normal B.1.637 definition, mutations with asterisks are found in majority, but not all sequences)

**Comments:**
Interesting sublineage of B.1.637. Fairly low numbers currently but with wide geographical spread across USA (both East and West Coast). Has a long branch length from other B.1.637 indicating this might be a 'second generation variant'. Also some interesting convergent evolution with Delta - this variant contains 452R, 478R(rather than K) and P681R. If still too low numbers for designation probably still warrents a monitoring label to see if any more genomes are found.

**Genomes:**
EPI_ISL_6210089
EPI_ISL_6494441
EPI_ISL_5365678
EPI_ISL_6603205
EPI_ISL_6826473
EPI_ISL_6813070
EPI_ISL_6792660
EPI_ISL_6754699

**Evidence:**
![image](https://user-images.githubusercontent.com/79373149/144072028-ab9f0fa2-1b7a-4fae-8e5f-f6e084c0eadd.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a4d7_639e70.json

**Proposed lineage name:** B.1.637.X

**Acknowledgements:** Sequences above were generated and kindly shared to GISAID by Zody et al, Siddle et al, Gonzalez-Reiche et al, Howard et al, Lee et al, and Roychoudhury et al. Also credit to @c19850727 and @jpkamil for independently spotting.

**Comment by c19850727** [comment]
Two more new sequences, collected in FL and CA respectively. EPI_ISL_6888292 and EPI_ISL_6892560.

**Comment by thomasppeacock** [comment]
Just to point out that this lineage will come up as a false positive for Omicron based on SGTF - it seems possible a lot of this will be picked up if samples are being prioritised for sequencing based on SGTF.

**Comment by thomasppeacock** [comment]
Uk sequence: EPI_ISL_7025451 - likely picked up during screening via SGTF for Omicron

**Comment by thomasppeacock** [comment]
Further 4 genomes from NY:
EPI_ISL_7126024
EPI_ISL_7126268
EPI_ISL_7126596
EPI_ISL_7128688

**Comment by c19850727** [comment]
two more in Scotland, EPI_ISL_7145825, EPI_ISL_7145821.

**Comment by c19850727** [comment]
two more from the States, NJ and NV respectively, EPI_ISL_7251933 and EPI_ISL_7249661.
