### ISSUE TITLE
New AY.123 sub-lineage circulating in Belgium with ORF1b:D2179Y (77 sequences, 4% proportion)

### ISSUE THREAD

**Issue by bitbyte2015** [cov-lineages/pango-designation#354]
**Description**
Sub-lineage of: AY.123
Earliest sequence: 2021/39
Latest sequence: 2021/47
Countries circulating: Belgium, UK, Israel

Among the AY.123 sequences growing in Belgium, 73 sequences are misdesignated by covspectrum to be AY.43 and appear to show a growth pattern. AY.123 shares the ORF7b:E3* codon found in some Omicron sequences and has grown to approximately 8% proportion in Belgium as well. This sub-lineage therefore comprises of 48% of Belgian AY.123 sequences in weeks 46 and 47. The lineage has also recently been detected in the UK and Israel for the first time.

**Evidence**

![image](https://user-images.githubusercontent.com/36325823/144410178-9801cf5b-c401-4c8a-af8f-17897b2e2c44.png)
https://cov-spectrum.ethz.ch/explore/Belgium/AllSamples/Past3M/variants?aaMutations=S%3AP1263L%2Corf7b%3AE3*%2CORF1b%3AD2179Y

![image](https://user-images.githubusercontent.com/36325823/144410385-2b645543-8aa6-4b7b-970c-811cbd87462a.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22679_8a1fb0.json?branchLabel=aa%20mutations&label=nuc%20mutations:G20002T

**Genomes**

|Gene|Mutations|
|-----|-----|
|ORF1a|**A211V**, **T1822I**|
|ORF1b|**Q1441H**, D2179Y|
|Spike|**P1263L**|
|ORF7b|**E3***|

Defining mutations of AY.123 are bolded

[sequences(3).csv](https://github.com/cov-lineages/pango-designation/files/7641401/sequences.3.csv)

Proposed lineage name: AY.123.1

**Comment by FedeGueli** [comment]
This sublineage account more than half of AY.123 belgian sequences , both are still increasing in % 
So still unclear if it has by itself a growth advantage
[CovSpectrum](https://cov-spectrum.org/explore/Belgium/AllSamples/Past3M/variants?aaMutations=ORF1b%3AD2179Y&pangoLineage=AY.123)

**Comment by chrisruis** [comment]
Thanks @bitbyte2015 It looks like this clade has continued to increase as a proportion of AY.123 sequences in Belgium. We've therefore added this as AY.123.1 in [v1.2.114](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.114) to start on the branch with G20002T (Orf1ab:D6580Y)
