### ISSUE TITLE
Proposal of new sub-lineage of Delta AY.25 for Peru with principal mutation in Spike: D796Y

### ISSUE THREAD

**Issue by cpadillarojas** [cov-lineages/pango-designation#355]
**Description**
Sub-lineage of: Potentially new sub lineage of Delta AY.25 (S: D796Y mutations in Peruvian genomes). New possible sub-lineage proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**Earliest sequence:** hCoV-19/Peru/LIM-INS-4482/2021 (2021/08/07, Peru)

**Most recent sequence:** hCoV-19/Peru/CAJ-INS-9940/2021 (2021/11/09, Peru)

**Countries circulating:** Peru (90)

The lineage of AY.25 was designed #181 (carried mutation: A27507C), the genomes of new sub lineage carried an additional mutation in Spike: D796Y. This potentially AY.25.X is spread predominantly in Lima (capital of Peru) and spread to others places like Piura, Cajamarca, La Libertad, Ayacucho, and Callao.

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_4e3_8fe500.json?branchLabel=aa%20mutations&c=gt-S_796&tl=country

![Captura2](https://user-images.githubusercontent.com/95427669/144471216-bf45680e-b5e0-49ca-8346-c50da6908788.PNG)

![VariantTimeDistributionChart](https://user-images.githubusercontent.com/95427669/144445873-59ba9760-1943-4fb0-a009-0c28d700cf98.png)
![VariantAgeDistributionChart](https://user-images.githubusercontent.com/95427669/144445920-a7074ad9-3950-4bdb-bbb8-21544444cae7.png)
![VariantDivisionDistributionChart](https://user-images.githubusercontent.com/95427669/144445937-ba8e0bfe-9c07-454d-87df-8895cfdc47cc.png)

.
**Genomes**
[genomes.csv](https://github.com/cov-lineages/pango-designation/files/7643939/genomes.csv)

**Comment by chrisruis** [comment]
Thanks @cpadillarojas We've added this as AY.25.1 in [v1.2.105](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.105) starting on the branch with G23948T (S:D796Y)

**Comment by chrisruis** [comment]
This lineage has been updated to AY.25.1.1 in [v1.2.111](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.111) due to designation of its parental clade in #313
