### ISSUE TITLE
Potential Sublineage of AY.4.2 with M:A2S (~2k seqs, ~10% prevalence in Italy)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#356]
**Description**
**Sub-lineage of**: AY.4.2 (~2k sequences)
**Earliest sequence**: 2021/8/6 (Germany)
**Most recent sequence**: 2021/11/26 (Czech Republic)
**Countries circulating**: Italy (~10% prevalence), and a few other European countries
**Mutations in addition to AY.4.2**: M:A2S

Genomes:
[GISAID_hcov-19_ids_2021_12_02_17_25.csv](https://github.com/cov-lineages/pango-designation/files/7643940/GISAID_hcov-19_ids_2021_12_02_17_25.csv)

Evidence
Transmission advantage as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/144472081-a3121202-b7fc-4791-893d-442c62ee5b42.png)

Geographical prevalence:
![image](https://user-images.githubusercontent.com/86835836/144472241-bdd9e5df-bc7e-4e80-bb32-786c093851d6.png)
https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/AllTimes/variants?aaMutations=M%3AA2S%2CS%3AY145H%2CS%3AA222V

Downsampled tree as per Neherlab (Italy, zoomed to AY.4.2):
![image](https://user-images.githubusercontent.com/86835836/144472840-537fbb01-7dea-4683-9eb4-d9e6c628d704.png)
https://nextstrain.org/groups/neherlab/ncov/italy?branchLabel=aa&c=gt-nuc_26526,21995&label=Spike%20mutations:A222V&p=full&r=division

Usher tree:
![image](https://user-images.githubusercontent.com/86835836/144474065-2ad42b2e-4709-4bfa-a2ee-a31b980048cf.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_a7c6_902fc0.json?c=gt-M_2&l=radial

**Comment by corneliusroemer** [comment]
I'd noticed this a while ago. First samples seem to be from Berlin, Germany. So it's a notable non-UK clade of AY.4.2

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as AY.4.2.3 in [v1.2.105](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.105) to start on the branch with G26526T (M:A2S)
