### ISSUE TITLE
Comment on new AY.123 in [v1.2.99]

### ISSUE THREAD

**Issue by geertmartens** [cov-lineages/pango-designation#357]
Chris, when will this new Pango lineage AY.123 come into effect. I noticed that build v.1;2.99 was released 9d ago, but to this day, when we run the Pango web interface, these sequences are still wrongly classified as AY.43

Did you take into account all 5 defining mutation signature for designation? 

ORF1a	A211V	C897T
ORF1a	T1822I	C5730T
ORF1b	Q1441H	G17790T
ORF7b	E3*	G27762T
ORF2 (Spike)	P1263L	C25350T

Or only the G27762T (Orf7b:E3*) on branch with  G17790T (Orf1ab:Q5842H) ? 

I must emphasize that some labs appear to have issues with the ORF7b E3 mutation, and replace this mutation by "N" in consensus FASTA to avoid obtaining 'intermediate score' in Nextclade analysis because of the stopcodon early in ORF7b. One example is Belgium/Rega. The latter practice can lead to underestimation of AY.123

Thanks @geertmartens We've added this as AY.123 in [v1.2.99](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.99) to start on the branch with G17790T (Orf1ab:Q5842H) and G27762T (Orf7b:E3*) to coincide with both Orf7b:E3* and the likely introduction(s) into Belgium
_Originally posted by @chrisruis in https://github.com/cov-lineages/pango-designation/issues/306#issuecomment-976831599_

**Comment by corneliusroemer** [comment]
The web app still seems to use pangoLEARN release 2021-11-18, which doesn't include AY.123 yet.

If you use the command line pangolin then you should get 2021-11-25 calls.

![image](https://user-images.githubusercontent.com/25161793/144520149-390f967a-74c2-4128-93d9-4005a03d4163.png)

![image](https://user-images.githubusercontent.com/25161793/144520151-b0e2f9e0-da43-4c8f-9092-56c1c1ac96eb.png)
