### ISSUE TITLE
Earliest date clarification

### ISSUE THREAD

**Issue by djangoengine** [cov-lineages/pango-designation#358]
It has been noted that the earliest date for this B.1.1.529  is recorded as 2021-02-05
`https://cov-lineage
s.org/lineage_list.html`

This has created some confusion as to the recent outbreak since November
Could you please clarify what is this earliest date column relates to in the database.

**Comment by rambaut** [comment]
This has been fixed.

**Comment by rkdover** [comment]
It is still interesting to know what the date is inferred from. For example we see something odd with AY.4.2 where it is dated earlier than B.1.617.2 itself:

![image](https://user-images.githubusercontent.com/54945737/145715969-30d13f82-b0ef-47d2-b4c0-9a1e1a7a1400.png)
![image](https://user-images.githubusercontent.com/54945737/145715980-a225be83-d5cd-45c1-9942-fdc3cc234256.png)
