### ISSUE TITLE
Proposal to split B.1.640 into two sublineages

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#362]
In a similar vein to the recent split of B.1.1.529(Omicron) into two sister sublineages it appears B.1.640 may also have a similar issue with a major group constating of the vast majority of sequences and a small outgroup which appears related but has a very different set of mutations (EPI_ISL_7181977; EPI_ISL_7156959; EPI_ISL_7156955; EPI_ISL_6315910; EPI_ISL_5926666) and  includes sequences from France and England, indicating some degree of spread.

**Defining mutations (mutations not shared between both groups shown in bold):**
**Major lineage:**
Spike - P9L, E96Q, Δ136-144, R190S*, **I210T**, R346S, N394S, Y449N, **F490R**, N501Y, D614G, P681H, T859N, **D936H**
Non-spike - NSP2 – P129L, **E272G**; **NSP3 – L1301F, A1537S;** **NSP4 – S386F, R401H, T492I;** **NSP6 – V149A**; NSP12 – P323L; T32I, Q57H; **M – I82T**; ORF8 – Q27*STOP; N- D22Y, T205I, **E378Q; S2m deletion**

**Minor lineage:**
Spike - P9L, E96Q, Δ136-144, R190S, **D215H**, R346S, N394S, Y449N, **E484K, F490S**, N501Y, D614G, P681H, T859N, **D1139H**
Non-spike - NSP2 – P129L; **NSP4 – D459N;** **NSP6 – Δ106-108**, **T181I**; NSP12 – P323L; **NSP13 – V371A;** **NSP14 – P46S, V437F**; ORF3a – T32I, Q57H; **M – I82S**; ORF8 – Q27*STOP; N – D22Y, T205I

**Phylogenetic evidence:**
![image](https://user-images.githubusercontent.com/79373149/145041609-a41c6904-2591-49ae-a93a-e7d39c841e97.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_58c3_f65be0.json?c=pango_lineage&label=nuc%20mutations:C10029T,G23012A,A23063T,C23604A,A26492T,C27925A,C28005T,C28093T,C28887T

**Proposed name(s):** B.1.640.1 and B.1.640.2?

**Comment by thomasppeacock** [comment]
Another cluster of sequences from the minor sublineage uploaded from the Provence-Alpes-Cote d Azur region by Colson et al:
EPI_ISL_7314302
EPI_ISL_7314417
EPI_ISL_7314471
EPI_ISL_7314514

**Comment by sanschiffre** [comment]
Two more sequence from the minor group are coming by Colson et al.

**If this help :** 

Commun mutations with Major Group :
C241T, C3037T, C14408T, A23403G, G25563T, C2416T,
C1191T, C2455T, C11956T, C16869T, C21588T, G21848C, TTTGTAATGATCCATTTTTGGGTGTTTA21966T, G22132T, A22600C, A22743G, T22907A, A23063T, C23604A, C24138A, C25487T, C27972T, TA28270T, G28337T, C28887T, T29377C, G29779T

Specific to the minor clade :
G9929A, T10561C, GTCTGGTTTT11287G, C11514T, C17004T, T17348C, A17916G, C18175T, C18804T, G19348T, T19680C, A21258G, G22205C, G23012A, T23031C, G24977C, T26767G, T27833C, T28002C, C28312T

**Comment by PhilippeColson** [comment]
We indeed have several cases of this new variant in the Marseille geographical area. We named it "Variant IHU". Two new genomes have jsut been submitted.
Best regards.

**Comment by mattdmem** [comment]
Hello - Just checking - should it be expected that pangolin now calls B.1.640.1 and B.1.640.2? I don't see any of these in GISAID (just B.1.640) and downloading them all and running an up to date version of pangolin and submodules calls them all B.1.640?

**Comment by chrisruis** [comment]
Hi @mattdmem I don't think they're in the current pangolin yet as the latest pangoLEARN was trained on v1.2.106 and B.1.640.1 and B.1.640.2 weren't added until v1.2.108. There's likely to be a new pangoLEARN run very soon that will have these in

**Comment by thomasppeacock** [comment]
Just a small update here - @c19850727 just pointed out to me a further outlier sequence (EPI_ISL_8428057 uploaded by Coppens et al from Belgium). This sequence is really interesting as it contains both unique mutations and elements of both B.1.640.1 and B.1.640.2 (in a similar manner to the relationship between BA.3 to BA.1/2). Only a single sequence at the moment  but worth being aware of.

Spike: P9L, T95I, E96Q, Δ136-144, R190S,I210T(.1-like), R346S, N394S, Y449N,E484K (.2-like), F490S (.2-like), Q498R, N501Y, D614G, P681H, T859N, D936H (.1-like), D1139H (.2-like), L1200F
Non-spike: NSP1 – D139G; NSP2 – P129L, A318V; NSP3 – G171C, K412N, A1537S(like .1), A1642V; NSP4 – L276V, V294L; D459N (.2-like); NSP5 – P241S; NSP6 – Δ106-108(.2-like); NSP7 – E73D; NSP9 – V102I; NSP12 – P323L; ORF3a – T32I, Q57H, S171L; M -I82T (.1-like); ORF8 – Q27*STOP; N – D22Y, I94V, T205I, E378Q (.1-like)


![image](https://user-images.githubusercontent.com/79373149/148557722-acb8c17f-0739-4caa-a8d3-a5b40757be4e.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1bab9_84a570.json?c=pango_lineage_usher&tl=pango_lineage

**Comment by c19850727** [comment]
EPI_ISL_8525350 found another one from Belgium.
