### ISSUE TITLE
AY.97 might be a sub lineage of AY.5

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#363]
When analyzing AY.5 it is defined by 1 mutation : G24928T

When analyzing AY.97 it is defined by 3 mutations : C6840T,G17193T,T23398C

But, AY.97 also has a mediator lineage connecting it to the base of Delta (21J) that was not designated which contains :C29253T and the AY.5 mutation G24928T

So AY.97 seemed to be evolved out of a lineage that evolved from AY.5.

 Covariants build :

https://nextstrain.org/groups/neherlab/ncov/21J.Delta?c=pango_lineage&label=mlabel:21J%20%28Delta%29/C29253T&m=div

And in an usher build using the defining sequences of AY97 and AY.5 from the PANGO lineage :

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2f7f9_f2fcd0.json?c=gt-nuc_24928,6840&label=nuc%20mutations:C6402T,A11201G,A11332G

**Comment by chrisruis** [comment]
Thanks @shay671 It looks like this clade has moved in recent UShER trees and agree that it does appear to descend from AY.5. We've therefore renamed AY.97 to AY.5.5 in [v1.2.108](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.108). The AY.97 label is therefore withdrawn
