### ISSUE TITLE
Potential AY.3 Sublineage in the US S:414R

### ISSUE THREAD

**Issue by baileyglen** [cov-lineages/pango-designation#365]
**Description**
Sub-lineage of: AY.3
Total Sequences via covSpectrum (308)
First Collection via gisaid: 2021-09-01
Last Collection via gisaid: 2021-11-29
Observed in 21 states, Canada(2021-11-17), and Israel(2021-11-24)

**Genomes**
Below are 300 sequences from gisaid on AY.3 wtih S:414R
[gisaid_hcov-19_S414R_2021_12_09_15.tsv.csv](https://github.com/cov-lineages/pango-designation/files/7686251/gisaid_hcov-19_S414R_2021_12_09_15.tsv.csv)

**Evidence**
![image](https://user-images.githubusercontent.com/9108196/145421060-78936eab-f838-41af-a509-31e4e5a2e52a.png)

![image](https://user-images.githubusercontent.com/9108196/145420332-729b5b18-47c1-4516-986e-4646edc19f0d.png)
I have indicated my subjective labeling of the major geograpical groupings on the tree. The red samples are 11 samples we submitted to gisaid yesterday. (Not all of them meet the 95% coverage requirement.)

![image](https://user-images.githubusercontent.com/9108196/145420719-db25bf8b-ce05-436a-a812-5194f8e31719.png)
The SC data is not particularly convincing. However, we have uploaded new data to gisaid which has not yet made it onto covspectrum. By our estimation, ~1.6% of samples collected in November and uploaded to gisaid are AY.3 with S:414R.

P.S. This is our first attempt at submitting a lineage designation, any feedback would be greatly appreciated.

**Comment by chrisruis** [comment]
Thanks @baileyglen We've added this as AY.3.3 in [v1.2.114](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.114) to start on the branch with T12538C (synonymous) and A22803G (S:Q414R)

The main things with the issue are a description of the proposed lineage and some sequence names to enable us to find the clade so this issue was great!
