### ISSUE TITLE
BA.1 sublineage with ORF3a:L106F, N:D343G, T10135C [~5% share]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#366]
Looking at Omicron diversity on this bespoke BA.1 [build](https://nextstrain.org/groups/neherlab/ncov/21K-diversity?c=gt-nuc_25708) with problematic sites masked, I noticed a rather long branch with 3 defining mutations that is also potentially growing faster than other BA.1.

Interestingly, it has not been sequenced in Southern Africa so far.

Defining mutations:
```
ORF3a:L106F (A29301G)
N:D343G ( C25708T)
nuc:T10135C
```

![image](https://user-images.githubusercontent.com/25161793/145567307-6e7cb270-23e6-449a-a92b-3ad340015367.png)

[covSpectrum](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=N%3A343G&pangoLineage=BA.1*)

**Comment by shay671** [comment]
I made an analysis for the % of this lineage out of the total BA.1 samples in different countries using CovSpectrum

BA.1 was searched using (2 synonymous mutations of BA.1) :
T13195C
C15240T
For this sub lineage i added 2 more mutations :
A29301G
C25708T



![image](https://user-images.githubusercontent.com/80166370/147407133-e41aab5d-90c3-4534-bbe6-ceb7e33265ee.png)

**Comment by aineniamh** [comment]
Closing this as it is a stale issue.
