### ISSUE TITLE
Third sublineage in B.1.1.529 (Omicron-related)

### ISSUE THREAD

**Issue by rambaut** [cov-lineages/pango-designation#367]
A new diverse genome has appeared within the `B.1.1.529` lineage that has all of the shared mutations of `B.1.1.529`, some of the mutations unique to `BA.1` and some unique to `BA.2` plus a few of its own. 

Name: `England/MILK-2D24AC9/2021`, accession `EPI_ISL_7526186`, collected `2021-12-03`

<img width="633" alt="image" src="https://user-images.githubusercontent.com/686405/145681747-318eb887-eea0-45f8-bc4e-f0d4ea65e5d7.png">

It seems likely this is an additional circulating member of the `B.1.1.529` diversity and that recombination has occurred in its history (although this is likely to have occurred prior to the emergence of the `BA.1` clade based on the pattern of mutations).

As a single genome it doesn't yet require a lineage designation and at the moment it will be classified as a member of `B.1.1.529`.

**Comment by corneliusroemer** [comment]
Here's another potential outlier, or is it contamination with Delta: `hCoV-19/Botswana/R50B26_BHP_000853752/2021`

```
E:T9I
M:D3G,M:Q19E,M:A63T
N:D63G,N:R203K,N:G204R,N:K361I,N:T362R,N:F363V,N:P364Q,N:P368S
ORF1a:G130K,ORF1a:Y229C,ORF1a:K856R,ORF1a:P2046L,ORF1a:P2287S
ORF1a:A2710T,ORF1a:T3255I,ORF1a:V3261I,ORF1a:I3758V
ORF1b:P314L,ORF1b:G662S,ORF1b:I1566V
ORF9b:T60A
S:A67V,S:V70L,S:T95I,S:D290E,S:A292G,S:G339D,S:S371L,S:S373P,S:S375F,S:K417N
S:N440K,S:G446S,S:S477N,S:T478K,S:E484A,S:Q493R,S:G496S,S:Q498R,S:N501Y
S:Y505H,S:T547K,S:D614G,S:H655Y,S:N679K,S:P681H,S:D950N
```

**Comment by AngieHinrichs** [comment]
@amniewiadomska suggests these new sequences as well:

hCoV-19/South Africa/NICD-N22389/2021|EPI_ISL_7605590|2021-11-30
hCoV-19/South Africa/NICD-N22404/2021|EPI_ISL_7605591|2021-11-25
hCoV-19/South Africa/NICD-N22385/2021|EPI_ISL_7605772|2021-11-29
hCoV-19/South Africa/NICD-N22239/2021|EPI_ISL_7605589|2021-11-26
hCoV-19/South Africa/NICD-N22163/2021|EPI_ISL_7605713|2021-11-18

**Comment by rambaut** [comment]
Yes - these are the same sub-lineage. A couple of the mutations listed above are unique to `England/MILK-2D24AC9/2021` so will be removed from the defining list. But I think this qualifies as `BA.3` now.

> Table of mutations

mut (nuc) | gene | mutation (aa) | B.1.1.529 | BA.1 | BA.2 | BA.3 (proposed) | notes
-- | -- | -- | -- | -- | -- | -- | --
T670G | ORF1ab | S135R |   |   | Y | Y |  
C832T | nuc | C832T |   |   |   | Y |  
C2790T | ORF1ab | T842I |   |   | Y |   |  
A2832G | ORF1ab | K856R |   | Y |   |   |  
C3037T | nuc | C3037T | Y |   |   | Y | B.1
T5386G | nuc | T5386G |   | Y |   |   |  
G4184A | ORF1ab | G1307S |   |   | Y | Y |  
C4321T | nuc | C4321T |   |   | Y |   |  
6513_6515del | ORF1ab | SL2083I |   | Y |   |   |  
G8393A | ORF1ab | A2710T |   | Y |   |   |  
C9344T | ORF1ab | L3027F |   |   | Y |   |  
A9424G | nuc | A9424G |   |   | Y |   |  
C9534T | ORF1ab | T3090I |   |   | Y | Y |  
C9866T | ORF1ab | L3201F |   |   | Y |   | Not in CERI-KRISP-K032307
C10029T | ORF1ab | T3255I | Y |   |   | Y |  
C10198T | nuc | C10198T |   |   | Y |   |  
G10447A | nuc | G10447A |   |   | Y | Y |  
C10449A | ORF1ab | P3395H | Y |   |   | Y |  
C11235T | nuc | C11235T |   |   |   | Y | 
11288_11296del | ORF1ab | SGF3675del | Y |   |   | Y | The exact position of this deletion is ambigous in nucleotide coordinates
T11296G | ORF1ab | F3677L |   |   | Y | Y | depending on the position of the deletion
G11287T | ORF1ab | L3674F |   | Y |   |   | depending on the position of the deletion
A11537G | ORF1ab | I3758V |   | Y |   |   |  
C12880T | nuc | C12880T |   |   | Y | Y |  
C14408T | ORF1ab | P4715L | Y |   |   | Y | B.1
C15240T | nuc | C15240T |   | Y |   |   |  
C15714T | nuc | C15714T |   |   | Y | Y |  
C17410T | ORF1ab | R5716C |   |   | Y |   |  
A18163G | ORF1ab | I5967V | Y |   |   |   |  
C19955T | ORF1ab | T6564I |   |   | Y |   |  
A20055G | nuc | A20055G |   |   | Y |   |  
C21618T | S | T19I |   |   | Y |   |  
21633_21641del | S | LPPA24S |   |   | Y |   |  
C21762T | S | A67V |   | Y |   | Y |  
21765_21770del | S | HV69del |   | Y |   | Y |  
C21846T | S | T95I |   | Y |   |   |  
G21987A (outlier); 21987_21995 (main) | S | G142D | Y |   |   |   |  
21987_21995 | S | VYY143del |   | Y |   | Y |  
22194_22196del | S | NL211I |   | Y |   | Y |  
T22200G | S | V213G |   |   | Y |   |  
22205GAGCCAGAAins | S | 215EPEins |   | Y |   |   |  
G22578A | S | G339D | Y |   |   | Y |  
C22674T | S | S371F |   |   | Y | Y |  
T22673C, C22674T | S | S371L |   | Y |   |   |  
T22679C | S | S373P | Y |   |   | Y |  
C22686T | S | S375F | Y |   |   | Y |  
A22688G | S | T376A |   |   | Y |   |  
G22775A | S | D405N |   |   | Y | Y |  
A22786T | S | R408S |   |   | Y |   |  
G22813T | S | K417N | Y |   |   | Y |  
T22882G | S | N440K | Y |   |   | Y |  
G22898A | S | G446S |   | Y |   | Y |  
G22992A | S | S477N | Y |   |   | Y |  
C22995A | S | T478K | Y |   |   | Y |  
A23013C | S | E484A | Y |   |   | Y |  
A23040G | S | Q493R | Y |   |   | Y |  
G23048A | S | G496S |   | Y |   |   |  
A23055G | S | Q498R | Y |   |   | Y |  
A23063T | S | N501Y | Y |   |   | Y |  
T23075C | S | Y505H | Y |   |   | Y |  
C23202A | S | T547K |   | Y |   |   |  
A23403G | S | D614G | Y |   |   | Y | B.1
C23525T | S | H655Y | Y |   |   | Y |  
T23599G | S | N679K | Y |   |   | Y |  
C23604A | S | P681H | Y |   |   | Y |  
C23854A | S | N764K | Y |   |   | ? |  
G23948T | S | D796Y | Y |   |   | Y |  
C24130A | S | N856K |   | Y |   |   |  
A24424T | S | Q954H | Y |   |   | Y |  
T24469A | S | N969K | Y |   |   | Y |  
C24503T | S | L981F |   | Y |   |   |  
C25000T | nuc | C25000T | Y |   |   |   |  
C25584T | nuc | C25584T | Y |   |   |   |  
A26059G,C26060T | ORF3a | T223V |   |   |   | Y | ACT->GTT
C26060T | ORF3a | T223I |   |   | Y |   | ACT->ATT (not fixed in `BA.3`)
C26270T | E | T9I | Y |   |   | Y |  
A26530G | M | D3G |   | Y |   |   | Not in CERI-KRISP-K032307
C26577G | M | Q19E | Y |   |   | Y |  
G26709A | M | A63T | Y |   |   | Y |  
C26858T | nuc | C26858T |   |   | Y | Y |  
A27259C | nuc | A27259C | Y |   |   | Y |  
G27382C, A27383T, T27384C | ORF6 | D61L |   |   | Y |   | (GAT->CTC)
C27807T | nuc | C27807T | Y |   |   | Y |  
A28271T | nuc | A28271T | Y |   |   | Y |  
C28311T | N | P13L | Y |   |   | Y |  
28362_28370del | N | ERS31del | Y |   |   | Y |  
G28881A, G28882A, G28883C | N | RG203KR | Y |   |   | Y | (B.1.1.1)
A29510C | N | S413R |   |   | Y | Y |  



`MILK-2D24AC9 ` has the following additional mutations:
```
C832T
C6541T
T8835C
C11235T
ORF1ab:F5086A
```

**Comment by chrisruis** [comment]
Now added as BA.3 in [v1.2.112](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.112)

**Comment by zach-hensel** [comment]
I don't think EPI_ISL_6906349 and EPI_ISL_4652284 qualify to be a sub-lineage but they might be worth reconsidering in light of overlap with all three of these in some places but only BA.1 in others, plus time/location information. I mentioned one of these elsewhere, but @c19850727 recently noted the additional one and also possibly related EPI_ISL_3838306.

**Comment by c19850727** [comment]
@rambaut 

Hi I came across the following 5 sequences: 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/itine/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/itine/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Accession | Virus name
-- | --
EPI_ISL_8262451 | hCoV-19/USA/CO-CDC-MMB12218639/2021
EPI_ISL_8439638 | hCoV-19/South Africa/NICD-N23764/2021
EPI_ISL_8402519 | hCoV-19/Puerto Rico/PR-CDC-S874/2021
EPI_ISL_9962725 | hCoV-19/South Africa/NICD-N29342/2022
EPI_ISL_10210515 | hCoV-19/South Africa/NICD-N29407/2022



</body>

</html>

- They are all classified as BA.1 by Pango/Nextstrain, but with **G2832A** reversed.
- Instead, they have **T670G (BA.2 and BA.3 defining )**, **C832T** (BA.3 defining ), **G4184A** (BA.2 and BA.3 defining) and **C4321T** (BA.2 defining).
- Downstream from T5386G it's all BA.1, but with a few private mutations: **G7684A, C29167T, G29734A**.

![image](https://user-images.githubusercontent.com/86835836/156703098-e10f0c33-7404-4831-a9a5-c223eb8f1935.png)

**Comment by corneliusroemer** [comment]
@c19850727 Are these sequences all identical? Do they have many stretches of N or any signs of bad quality or artefacts?
