### ISSUE TITLE
New BA.1 lineage missing Spike N440K, Spike K417N mutations

### ISSUE THREAD

**Issue by nirvtul** [cov-lineages/pango-designation#368]
**Earliest sequences:** EPI_ISL_6795189 (2021-11-12), EPI_ISL_6795188.2 (2021-11-12) - detected in South Africa

Predominantly circulating in USA (Texas), England, Scotland, South Africa.

**Defining mutations**: -Spike_N440K, -Spike_K417N, Spike_H69del,Spike_V70del,NSP5_P132H,N_R203K,Spike_G142D,NSP3_A1892T,N_P13L,NSP3_L1266I,N_R32del,NSP4_T492I,NSP6_L105del,Spike_L212I,Spike_Y505H,NSP6_G107del,NSP6_I189V,N_G204R,Spike_V143del,NSP6_S106del,NSP3_S1265del, NSP14_I42V, Spike_Y144del,Spike_ins214EPE, N_S33del, Spike_S375F, N_E31del, NSP3_K38R, Spike_N211del, Spike_L981F,NSP12_P323L,Spike_Y145del

Supporting entries in GISAID: 785 (As of Dec 12/2021)
**Supporting entries in GISAID without ambiguous bases:** EPI_ISL_7415721,EPI_ISL_7415830,EPI_ISL_7415731,EPI_ISL_7415770,EPI_ISL_7415887,EPI_ISL_7415723,EPI_ISL_7415774,EPI_ISL_7415887

Phylogenetic Analysis conducted through NJ using sequences containing unambiguous bases shows this potentially new lineage forming a clade separately from other BA.1 sequences.

![New_BA_1_Dec12def](https://user-images.githubusercontent.com/57898450/145708161-180367da-6ff7-4aa1-97df-dda7915d0bdb.png)
[](url)

Attaching file containing supporting entries in GISAID: 785 (As of Dec 12/2021)
[New_BA_1_Dec12_def.txt](https://github.com/cov-lineages/pango-designation/files/7698524/New_BA_1_Dec12_def.txt)

Proposed lineage name: BA.3 (?)

Hope this is of help.
Nirvana

**Comment by arminlahm** [comment]
Hi, in your file New_BA_1_Dec12_def.txt you have listed EPI_ISL_6699730. This spike protein sequence, as present in GISAIDs spikeprot1209.fasta file does, yes, not contain Spike N440K and Spike K417N mutations but this is because that segment (410 to 459) of the sequence is simply XXXXXXXXX (alignment in BA1.align.txt) ! Did you check if the other sequences have this segment covered by sequence ?
Best,
Armin
[BA1.align.txt](https://github.com/cov-lineages/pango-designation/files/7699173/BA1.align.txt)

**Comment by corneliusroemer** [comment]
Closed with same arguments as for #364 

This issue does not seem to contain any new evidence.

https://github.com/cov-lineages/pango-designation/issues/364#issuecomment-990187517

**Comment by nirvtul** [comment]
Hello,
I have based my finding principally on the following entries that do not contain ambiguous sites.
> **Supporting entries in GISAID without ambiguous bases:** EPI_ISL_7415721,EPI_ISL_7415830,EPI_ISL_7415731,EPI_ISL_7415770,EPI_ISL_7415887,EPI_ISL_7415723,EPI_ISL_7415774,EPI_ISL_7415887
So, I wonder if you would find that gap in the entries I have listed above too. By the way, I haven't attached any file named "spikeprot1209.fasta".
Bests,
Nirvana

**Comment by corneliusroemer** [comment]
I never mentioned ambiguous sites.

Backfilled nucleotides are usually not ambiguous.
