### ISSUE TITLE
Sublineage of AY.46.6 with N double mutation: N:M234V, N:T379I fast growing in Italy (77 seqs-13% last week)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#369]
Italian epidemic is experiencing a late Delta wave with a surge in the numbers of cases. 
Between the Delta sublineages i noticed from the "Istituto Superiore della Sanita' - ISS" report n.15 that AY.46.6 has in Italy a share bigger than the average of the other european countries.
Since that i went digging a bit in it and i found a clade already flagged by me from some weeks.
Here the characerization of this proposal:

Sublineage of AY.46.6
Carrying two N Mutations: N:M234V, N:T379I
Nr. of sequences:77 in the last three months (66 in the last month)
Country: Italy (Mainly Emilia Romagna)
Last weeks growth to 13% of italian sequences:
![VariantTimeDistributionChart](https://user-images.githubusercontent.com/87669813/146093043-862f9869-611b-4a76-8eaf-af54152563dd.png)

[Covspectrum](https://cov-spectrum.org/explore/Italy/AllSamples/Past3M/variants?aaMutations=N%3AM234V%2CN%3At379I&pangoLineage=AY.46.6*)

Tree by Usher  (that assignes it as AY.46 , but all of these sequences has C6310T ) 
![Schermata 2021-12-15 alle 00 02 56](https://user-images.githubusercontent.com/87669813/146093286-71140fa0-f1db-40e2-80f4-b9971ec10e4e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1414f_9129d0.json?branchLabel=aa%20mutations&label=nuc%20mutations:C10977T

[Neher Lab tree](https://nextstrain.org/groups/neherlab/ncov/italy?branchLabel=aa&c=gt-N_379,234&d=tree&p=full&r=division&tl=pango_default)

**Comment by chrisruis** [comment]
Thanks @FedeGueli We've added this as AY.46.6.1 in [v1.2.114](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.114) to start on the branch with T6226C (synonymous), C27297T (synonymous), C27418T (synonymous) and A28973G (N:M234V)
