### ISSUE TITLE
Sublineage of B.1.429 with S:Q677H (as well as ORF1a:F2827L, ORF3a:A23V, and N:P142S)

### ISSUE THREAD

**Issue by tomkinsc** [cov-lineages/pango-designation#37]
## Description
Sub-lineage of: B.1.429
Earliest sequence: 2021-01-27
Most recent sequence: 2021-03-12 (database upload pending for the most recent few sequences; table of published sequences below)
Countries circulating: USA (Colorado)

We have identified a cluster of cases in Colorado, USA, descended from the lineage B.1.429 with an additional spike protein substitution at amino acid position 677, S:Q677H (as well as ORF1a:F2827L, ORF3a:A23V, and N:P142S). There is evidence of onward transmission. 

Here is a Virological post with summary of this cluster:
https://virological.org/t/detection-of-the-recurrent-substitution-q677h-in-the-spike-protein-of-sars-cov-2-in-cases-descended-from-the-lineage-b-1-429/660

Of note is that this is **not** the first set of B.1.429-derived sequences with S:Q677H; some cases with the combination of B.1.429+S:Q677H have been sequenced previously from samples collected in California ([tree](https://nextstrain.org/groups/spheres/ncov/california?d=tree,entropy,frequencies&gt=N.234I,205I,ORF8.100L,S.452R,13I,152C,614G,ORF1a.265I,4205V,3367V,ORF1b.314L,ORF3a.57H&p=full)) and share much of the same haplotype. The cluster we have identified in Colorado is further characterized by the amino acid substitutions ORF1a:F2827L, ORF3a:A23V, and N:P142S.

## Genomes

[Colorado_B.1.429_with_SQ677H_seqs_as_of_2021-03-28.tsv.txt](https://github.com/cov-lineages/pango-designation/files/6223615/Colorado_B.1.429_with_SQ677H_seqs_as_of_2021-03-28.tsv.txt)

## Evidence
![tree_cluster_callout_img_clean](https://user-images.githubusercontent.com/53064/112878865-693c8480-9096-11eb-9e1f-d785b4fcdd45.jpg)

## Proposed lineage name

We propose naming the haplotype B.1.429+S:Q677H, ORF1a:F2827L, ORF3a:A23V, and N:P142S as a sublineage, `B.1.429.2`. (Perhaps preceded by B.1.429+S:Q677H being named `B.1.429.1`.)

**Comment by chrisruis** [comment]
Hi, thanks very much for submitting this. New Pango lineages need to be associated with an epidemiological event, like an introduction into a new area. The Colorado clade fits the new lineage definition and we've assigned the Colorado clade as lineage B.1.429.1. The California clade doesn't seem to be associated with an introduction into a new area and we've therefore left those sequences as B.1.429. Thanks again

**Comment by jinyu-ncbi** [comment]
There is an error in Table 2: V3357I should be V3367I.

**Comment by tomkinsc** [comment]
@jinyu-ncbi Thank you for catching that. Table 1 is correct; it should indeed be V3367I.
