### ISSUE TITLE
Proposal for a AY.33 Sublineage with Spike H49Y and E654K (66 Seqs, ~17% Prevalence in Reunion)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#370]
**Description**
**Sub-lineage of**: AY.33
**Earliest sequence**: 2021/10/12 (France)
**Most recent sequence**: 2021/11/29 (France-Reunion)
**Countries circulating**: France (mainly in Reunion with ~17% prevalence, also in European France and Martinique)

**Substitutions on top of AY.33**:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/itine/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/itine/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Gene | Mutations
-- | --
ORF1a | S1306F, S3309P, M3616V
ORF1b | V2515L, T284I, H1807R
S | H49Y, E654K
ORF7a | 54/76del
nuc | C10525T, C17439T

</body>

</html>
(I am not sure if ORF7a:54/76del is real or artefactual though).

**Genomes**:
EPI_ISL_5635915, EPI_ISL_5691147, EPI_ISL_5749178-5749179,
EPI_ISL_6124361, EPI_ISL_6124452, EPI_ISL_6251031,
EPI_ISL_6254128, EPI_ISL_6254232, EPI_ISL_6309697,
EPI_ISL_6332445, EPI_ISL_6372467-6372468, EPI_ISL_6372476-6372478,
EPI_ISL_6372480, EPI_ISL_6470406, EPI_ISL_6470408,
EPI_ISL_6470784, EPI_ISL_6470867, EPI_ISL_6470886,
EPI_ISL_6605077, EPI_ISL_6605136, EPI_ISL_6605173,
EPI_ISL_6651171, EPI_ISL_6728028, EPI_ISL_6728040,
EPI_ISL_6733147, EPI_ISL_6733152, EPI_ISL_6733162,
EPI_ISL_6779419-6779421, EPI_ISL_6779423, EPI_ISL_6779444-6779445,
EPI_ISL_6779816-6779820, EPI_ISL_6779843-6779844, EPI_ISL_6779877,
EPI_ISL_6779897, EPI_ISL_7138675, EPI_ISL_7151165-7151166,
EPI_ISL_7151171, EPI_ISL_7209359, EPI_ISL_7210207,
EPI_ISL_7218491, EPI_ISL_7368649, EPI_ISL_7371249,
EPI_ISL_7374143, EPI_ISL_7374532, EPI_ISL_7457319,
EPI_ISL_7606746, EPI_ISL_7607624, EPI_ISL_7607712,
EPI_ISL_7608045, EPI_ISL_7608711, EPI_ISL_7609233,
EPI_ISL_7611266, EPI_ISL_7611272

**Evidence**
Down-sampled tree as per Neherlab (France, filtered to AY.33):
![image](https://user-images.githubusercontent.com/86835836/146230162-5fea378b-b97b-4839-8115-76ef884e74eb.png)
Geographical prevalence as per Neherlab (in yellow coloer):
![image](https://user-images.githubusercontent.com/86835836/146230587-a5125fc8-5e6c-4e50-84c7-04d4084299d5.png)
https://nextstrain.org/groups/neherlab/ncov/france?branchLabel=none&c=gt-S_49&f_pango_lineage=AY.33&label=Spike%20mutations:T29A,%20T250I&p=full&r=division&tl=division

Transmission advantage as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/146230786-13da3f8a-d1bb-43e6-ba80-8b22e832f4a2.png)

Usher tree:
![image](https://user-images.githubusercontent.com/86835836/146231153-759de23b-0371-4afb-b558-da1e8e2a75b9.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3fcd9_8cb870.json?c=gt-S_654&l=radial&label=nuc%20mutations:G210T,C241T,C3037T,G4181T,C6402T,C7124T,C8986T,G9053T,C10029T,A11201G,A11332G,C14408T,G15451A,C16466T,C19220T,C21618G,A21647G,C22311T,C22458T,T22917G,C22995A,G23401T,A23403G,C23604G,C25469T,T26767C,T27638C,C27752T,C27874T,A28461G,G28881T,G28916T,G29402T,G29742T

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as AY.33.1 in [v1.2.114](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.114) to start on the branch with T10190C (Orf1ab:S3309P), A11111G (Orf1ab:M3616V), C14318T (Orf1ab:T4685I), C17439T (synonymous) and C21707T (S:H49Y)
