### ISSUE TITLE
Sublineage of AY.122 circulating in Denmark (1%) with S:Q613H and Orf1a:T4083M

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#371]
While i was checking my other proposed sublineage of AY.4 with Orf1a:T4083M in #332 , i spotted this sublineage of AY.122 carrying Orf1a:T4083M too.
Interestingly this sublineage has acquired S:Q613H too.

Defining mutations:
NUC: G23401T
then T168C, C12513T, G17338A, T17694C, T20838C, C28873A 
ORF1a: T4083M
AA: S:Q613H
then ORF1a:T4083M, Orf1ab:A5692T (ORF1b:A1291T)

[Usher tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_28dad_b9ac80.json?branchLabel=aa%20mutations&label=nuc%20mutations:T168C,C12513T,G17338A,T17694C,T20838C,G23401T,C28873A)
[NeherLab Tree](https://nextstrain.org/groups/neherlab/ncov/denmark?branchLabel=aa&c=gt-ORF1a_4083&label=Spike%20mutations:Q613H&p=grid&r=division&tl=pango_usher)

Notwithstanding the Omicron great increase in the last two weeks it is still 1,4% frequency in the last week and trending up:
[CovSpectrum last three months in Denmark](https://cov-spectrum.org/explore/Denmark/AllSamples/Past3M/variants?aaMutations=Orf1a%3AT4083M%2CS%3AQ613H&pangoLineage=AY.122*)

**Comment by FedeGueli** [comment]
List of sequences extracted by CovSpectrum

[sequences (1).csv](https://github.com/cov-lineages/pango-designation/files/7730387/sequences.1.csv)

**Comment by chrisruis** [comment]
Thanks @FedeGueli We've added this as AY.122.3 in [v1.2.114](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.114) to start on the branch with C12513T (Orf1ab:T4083M), G17338A (Orf1ab:A5692T), T20838C (synonymous), G23401T (S:Q613H) and C28873A (synonymous)
