### ISSUE TITLE
Proposal for a Delta (21J) Sublineage with Spike G446V and N501T (73 Seqs, ~70% Prevalence in Bangladesh)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#373]
**Description**
**Sub-lineage of**: B.1.617.2 (21J)
**Earliest sequence**: 2021/9/12 (Bangladesh)
**Most recent sequence**: 2021/12/11 (Germany)
**Countries circulating**: Bangladesh (61 sequences, ~70% prevalence), the UK (5 sequences), Bahrain (4 sequences), Germany (2 sequences), the US-TN (1 sequence)

<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">Substitutions on top of B.1.617.2</strong>:</p>

Gene | Mutations
-- | --
ORF1b | P314F, V2178F
S | G446V, N501T
nuc | G29688T, T29014C

</body>
</html>
Interestingly some of the sequences also have a truncated ORF8 (S54stop).

**Evidence**
Down-sampled tree as per Neherlab (Asia-Bangladesh, filtered to B.1.617.2):
![image](https://user-images.githubusercontent.com/86835836/146634778-dc017651-ee34-4ad4-844b-ce4902c66613.png)
https://nextstrain.org/groups/neherlab/ncov/asia-bangladesh?branchLabel=aa&c=gt-S_501,446&f_pango_usher=B.1.617.2&p=full&r=division

Transmission advantage as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/146634829-f3230e13-c686-4006-b9ad-e7934f0703d8.png)
International comparison as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/146634841-dfd47f12-f924-4c1e-a594-f99f39c31984.png)
https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3AG446V%2CS%3AN501T%2CORF1b%3A314F

Usher tree (in blue color):
![image](https://user-images.githubusercontent.com/86835836/146634902-0b82cba3-fc2d-4749-9acb-c0cd231a265c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25f63_ccb790.json?c=gt-S_501&l=radial

**Genomes**:
EPI_ISL_5050362, EPI_ISL_6266444, EPI_ISL_6266446,
EPI_ISL_6266506-6266507, EPI_ISL_6841708, EPI_ISL_6841712,
EPI_ISL_6841715, EPI_ISL_6841720-6841721, EPI_ISL_6841727-6841728,
EPI_ISL_6841731, EPI_ISL_6841738, EPI_ISL_7166061,
EPI_ISL_7295930, EPI_ISL_7382079, EPI_ISL_7404444,
EPI_ISL_7404446, EPI_ISL_7404454-7404456, EPI_ISL_7404458-7404461,
EPI_ISL_7404466, EPI_ISL_7404470-7404471, EPI_ISL_7554436,
EPI_ISL_7566185-7566188, EPI_ISL_7566193, EPI_ISL_7571114,
EPI_ISL_7571145, EPI_ISL_7571149, EPI_ISL_7571160,
EPI_ISL_7571182-7571183, EPI_ISL_7571187, EPI_ISL_7571190,
EPI_ISL_7571200, EPI_ISL_7571202, EPI_ISL_7571208,
EPI_ISL_7571212, EPI_ISL_7571222, EPI_ISL_7571228,
EPI_ISL_7592292, EPI_ISL_7592302, EPI_ISL_7592308,
EPI_ISL_7592315, EPI_ISL_7592324, EPI_ISL_7592335,
EPI_ISL_7592341, EPI_ISL_7592348, EPI_ISL_7592360,
EPI_ISL_7592393, EPI_ISL_7592400, EPI_ISL_7592405,
EPI_ISL_7592412, EPI_ISL_7592419, EPI_ISL_7592427,
EPI_ISL_7677517, EPI_ISL_7703731, EPI_ISL_7754427,
EPI_ISL_7767064, EPI_ISL_7802964-7802966, EPI_ISL_7802970-7802971

**Comment by c19850727** [comment]
A new sequence from Singapore with recent travel history from Bangladesh: EPI_ISL_7829327.

**Comment by c19850727** [comment]
38 out 134 sequences from Bangladesh on Dec 20th are this one.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage AY.131 with 55 newly designated sequences, in v1.2.116

**Comment by c19850727** [comment]
It's interesting that latest sequences of AY.131 have gained an additional Spike E484Q.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3AP314F%2CS%3AG446V%2CS%3AN501T%2CS%3AE484Q

![image](https://user-images.githubusercontent.com/86835836/148882209-e6fdc5f1-4818-481a-a808-e57f4aa098c4.png)
