### ISSUE TITLE
Omicron (21K) US lineage with additional mutation N:P67S at T cell epitope and C11950T (102 seq, 6% of US omicrons)

### ISSUE THREAD

**Issue by bitbyte2015** [cov-lineages/pango-designation#375]
A minority of US BA.1 sequences have gained an additional mutation at N:P67S but the proportion is most pronounced in the midwest where it makes up 46% (12/26) of sequences in Illinois and 27% (51/186) sequences in Wisconsin. Codon 67 in the N gene falls under a HLA class 1 epitope [1]. There was a sequence from South Africa in mid November with N:P67S on the ORF1a:V1887I clade so it's unclear why it's growing exclusively in the US. N:P67S was also present in the B.1.2 lineage which was responsible for over 40% of US sequences in November 2020. 

Roemer's ncov-simplest build puts it on a branch starting with C11950T
![image](https://user-images.githubusercontent.com/36325823/146937776-109f6eca-22bb-47df-bff5-613ef13a67d3.png)
https://nextstrain.org/groups/neherlab/ncov/21K-diversity?c=gt-N_67

and since UCSC USHER is down I ran ncov-simplest with the N:P67S omicrons only
![image](https://user-images.githubusercontent.com/36325823/146938262-cf647eff-39b1-40f3-8905-092fc287c772.png)

all but 2 sequences were placed on the branch with C11950T the others being the South African sequence placed on the ORF1a:V1887I clade and a UK sequence placed on the N:D343G clade in #366 

| Country | Sequences |
| ----- | ----- |
| USA | 94 |
| UK | 3 |
| Australia | 1 |
| Japan | 1 |
| Netherlands | 1 |
| Canada | 1 |
| Austria | 1 |

[1] https://www.nature.com/articles/s41590-020-00808-x

**Comment by AngieHinrichs** [comment]
[a bit off-topic for pango-designation, apologies for that but this bit is concerning for me:]

> and since UCSC USHER is down

Sorry to hear that it was down.  Do you recall the symptoms?  (Error 500? Timeout?)  If you are using a link with 'hgwdev' or 'genome-test' in it, that is our development/test server, and we had to reboot it a couple times recently for filesystem troubles.  The main site is https://genome.ucsc.edu/cgi-bin/hgPhyloPlace and should be more stable.

**Comment by SVN-PhD** [comment]
Visualization of this lineage in context with other Omicrons from North America, Europe, and Africa.
![Screenshot from 2021-12-22 13-59-26](https://user-images.githubusercontent.com/15314705/147142206-32ab1992-e251-40c7-b2ab-05556b872955.png)

Zooming into this lineage show it is quite prevalent in the upper Midwest of the US.
![Screenshot from 2021-12-22 13-59-52](https://user-images.githubusercontent.com/15314705/147142332-d28a8c33-8a4b-4e24-81dc-1646bf31f781.png)

**Comment by bitbyte2015** [comment]
11% (165/2524) of US omicron sequences now contain N:P67S

**Comment by chrisruis** [comment]
Thanks @bitbyte2015 We've added this as BA.1.20 in [v1.4](https://github.com/cov-lineages/pango-designation/releases/tag/v1.4)
