### ISSUE TITLE
Some sequences of BA.1 lineage were not labelled as Omicron

### ISSUE THREAD

**Issue by Aungpone** [cov-lineages/pango-designation#377]
Hello,
I was checking the earliest samples of Omicron and found that some sequences of BA.1 lineage were not labelled as Omicron. I found that earliest sample with Omicron label is Nov 5 and with BA.1 are Oct 13. Please see the attached files. Can you please explain the reason for not labelling as Omicron?
Thank you.
Best regards,
Aung Pone Myint

![image](https://user-images.githubusercontent.com/93726308/147063522-a0e28821-0dee-4329-baf4-f38a3ca18523.png)
![image](https://user-images.githubusercontent.com/93726308/147064014-521ddca9-9794-46a3-a1bb-3b328d371f84.png)

**Comment by rambaut** [comment]
The ones highlighted above are labelled as BA.1 by Pangolin so I think this is a GISAID issue with how they call 'Omicron VOC'.

**Comment by aretchless** [comment]
I looked into this a little more -- these 'non-omicron' BA.1 sequences on GISAID stretch back to January 2021. They all have QC alerts on them.

Some examples are below:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ymw8/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ymw8/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Accession ID | Collection date | Submission date | Location
-- | -- | -- | --
EPI_ISL_7988145 | 2/12/2021 | 12/23/2021 | Africa / Zambia / Lusaka / Lusaka
EPI_ISL_7988146 | 2/12/2021 | 12/23/2021 | Africa / Zambia / Lusaka / Lusaka
EPI_ISL_7988147 | 2/12/2021 | 12/23/2021 | Africa / Zambia / Lusaka / Lusaka
EPI_ISL_7988151 | 2/12/2021 | 12/23/2021 | Africa / Zambia / Lusaka / Lusaka
EPI_ISL_7988161 | 5/12/2021 | 12/23/2021 | Africa / Zambia / Lusaka / Lusaka
EPI_ISL_7988168 | 7/12/2021 | 12/23/2021 | Africa / Zambia / Copperbelt / MUFULIRA
EPI_ISL_7988169 | 4/12/2021 | 12/23/2021 | Africa / Zambia / Copperbelt / NDOLA
EPI_ISL_7988170 | 7/12/2021 | 12/23/2021 | Africa / Zambia / Copperbelt / NDOLA
EPI_ISL_7988171 | 6/12/2021 | 12/23/2021 | Africa / Zambia / Copperbelt / NDOLA
EPI_ISL_7988174 | 7/12/2021 | 12/23/2021 | Africa / Zambia / Northwestern / KASEMPA
EPI_ISL_8019090 | 2/13/2021 | 12/23/2021 | Europe / Portugal
EPI_ISL_8019091 | 2/13/2021 | 12/23/2021 | Europe / Portugal
EPI_ISL_8019092 | 2/13/2021 | 12/23/2021 | Europe / Portugal
EPI_ISL_8109043 | 2/15/2021 | 12/27/2021 | Asia / India / Gujarat / Vadodara



</body>

</html>

**Comment by rambaut** [comment]
For the Zambian ones - very sure it is a month/day swap. I have contacted the submitter through GISAID.
