### ISSUE TITLE
Proposal of Brazilian AY.43 novel sublineage with Spike:S939F [92 sequences]

### ISSUE THREAD

**Issue by alex-ranieri** [cov-lineages/pango-designation#378]
By Alex Ranieri and Gabriela Ribeiro (Butantan Network for Pandemic Alert of SARS-CoV-2 Variants, São Paulo).

Description
Sub-lineage of AY.43
Countries circulating: Brazil

We observed an interesting clustering of the AY.43 lineage which might be suggestive for an emerging sub-lineage. It includes 92 Brazilian sequences ([genomes.txt](https://github.com/cov-lineages/pango-designation/files/7764081/genomes.txt)), with Spike mutation S939F. This can be observed in the following build: https://nextstrain.org/fetch/repositorio.butantan.gov.br/bitstream/butantan/3982/5/ncov_SE_41_to_48.json . (json file can be downloaded in: https://repositorio.butantan.gov.br/bitstream/butantan/3982/5/ncov_SE_41_to_48.json)

It was proposed that the mutation S:S393F in combination with S:D614G can increse the infectivity 4- to 100-fold compared to the reference Wuhan-1 strain (https://www.nature.com/articles/s41392-020-00302-8.pdf?origin=ppub). 
The file [AY.43.7.csv](https://github.com/cov-lineages/pango-designation/files/7764150/AY.43.7.csv) highlight the clade by coloring with possible_new_lineage as AY.43.7. 

Transmission advantage as per cov-spectrum (https://cov-spectrum.org/explore/Brazil/AllSamples/Past6M/variants?aaMutations=S%3AS939F&pangoLineage=AY.43):

![Relative_Growth_Advantage](https://user-images.githubusercontent.com/94479933/147130859-9ad2ed1e-24ec-43c7-bba5-4ae123635781.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage AY.43.7 with 92 newly designated sequences, in v1.2.118
