### ISSUE TITLE
Proposal for a Delta (21J) Sublineage with ORF7b E39stop and H42Q (~360 Seqs, ~1% Prevalence in Denmark)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#379]
**Description**
**Sub-lineage of**: B.1.617.2 (21J)
**Earliest sequence**: 2021/10/25 (Denmark)
**Most recent sequence**: 2021/12/11 (Denmark)
**Countries circulating**: Denmark predominantly, and 2 sequences from Sweden

**Substitutions on top of B.1.617.2**:

<html>
<body>

Gene | Mutations
-- | --
ORF1a | A385T, K636R, P1497S
ORF1b | M1582I, I2147M
ORF3a | D155Y
ORF7b | E39stop, H42Q
nuc | A2172G, C4754T, C7945T, G11161A, T11488C, T19500C, C23683T, C25710T

</body>
</html>

**Evidence**
Usher tree:
![image](https://user-images.githubusercontent.com/86835836/147211691-3c7edaac-3ac9-4bbd-8b01-a1b0127c7ae7.png)

Uher tree displaying geographical distribution:
![image](https://user-images.githubusercontent.com/86835836/147213396-498d3b69-3d99-4437-817f-9621ca5d3058.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c6e6_3d7550.json?c=gt-ORF7b_42&l=radial

Down-sampled tree as per Neherlab doesn't work very well, as there are only 2 isolates of this potential sublineage included by its down-sampling. I have to use a scatter tree (filtered to B.1.617.2) to have a proper view of it:
![image](https://user-images.githubusercontent.com/86835836/147212070-84993ea0-09a0-4c98-8c01-163eba4855a1.png)

Mutation of the branch as per Neherlab:
![image](https://user-images.githubusercontent.com/86835836/147214256-50e9b544-b975-470b-aa40-e8cbe4c88e9d.png)
https://nextstrain.org/groups/neherlab/ncov/denmark?branchLabel=none&c=gt-nuc_1418,27131&f_country=Denmark&f_pango_usher=B.1.617.2&l=scatter&p=full&r=division&scatterY=gt

Transmission advantage as per Cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/147213569-f176bd67-2555-413c-8c7d-94cc763bb152.png)
https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF7b%3AE39*%2CORF7b%3A42Q%2CORF3a%3AD155Y

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage AY.132 with 305 newly designated sequences, in v1.2.119
