### ISSUE TITLE
Proposed new B.1 sublineage circulating in India

### ISSUE THREAD

**Issue by grovesn** [cov-lineages/pango-designation#38]
### Description

Sub-lineage of: B.1
Earliest sequence: 2020-12-07
Most recent sequence: 2021-03-17
Countries circulating: India; also seen in data from UK, Australia, New Zealand, Singapore, USA, Germany, Canada

This lineage was reported to be circulating in India and comprised around 20% of sequences from some regions (https://www.telegraphindia.com/india/covid-double-mutation-variant-fuels-fears/cid/1809715). Contains L452R and E484Q mutations.

Gene | Amino Acid | Nucleotide | Notes
-- | -- | -- | --
orf1ab | - | 3457C>T | 
orf1ab |T1567I | 4965C>T | nsp3:T749I
orf1ab |T3646A | 11201A>G | nsp6:T77A
orf1ab |M5753I | 17523G>T | nsp13:M429I
orf1ab |K6711R | 20396A>G |  nsp15:K259R
orf1ab |- | 21895T>C |  
S Gene | G142D | 21987G>A |  
S Gene |E154K | 22022G>A |  
S Gene |L452R | 22917T>G |  
S Gene |E484Q | 23012G>C |  
S Gene |P681R | 23604C>G |  
S Gene |Q1071H | 24775A>T |  
orf3a | S26L | 25469C>T |  
orf7a | V82A | 27638T>C |  
N Gene | R203M | 28881G>T |  

**Genomes**
[accessions.txt](https://github.com/cov-lineages/pango-designation/files/6227850/accessions.txt)

**Evidence**

![india_20210325 filtered aligned fasta treefile](https://user-images.githubusercontent.com/15730790/112964141-f5ef4d00-913f-11eb-9407-f7c85b3173a0.png)

**Comment by rambaut** [comment]
This has come up as a VUI/VOI and should be given a lineage designation on the basis of geographical spread and multiple mutations associated with VOCs

**Comment by chrisruis** [comment]
Hi, thanks very much for this. We've assigned this as B.1.617
