### ISSUE TITLE
Proposal for a Delta (21I) Sublineage with Spike N17K, L18F, P499R, V1264L (~80 Seqs, ~15% Prevalence in Senagal)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#380]
This potential sublineage is actually a subclade deep in an otherwise already extinct branch of Delta (21I) with ~1200 sequences (with nuc C12025T, ORF1a:P62S and S:V1264L).

Since other clade in this branch is likely to be already extinct, I am to propose this sublineage starting from the branch with Spike N17K, L18F and P499R (~80 sequences only).

**Description**
**Sub-lineage of**: B.1.617.2 (21I)
Earliest sequence: 2021/9/14 (the US-NY)
Most recent sequence: 2021/12/13 (Japan)
Countries circulating: France, Germany and the UK mainly, and also seen in a few other countries, especially Senegal and Ghana.

**Substitutions on top of B.1.617.2 (21I)**:

<html>
<body>

Gene | Mutations
-- | --
ORF1a | P62S, H1500Y
ORF1b | L2213F
Spike | N17K, L18F, P499R, V1264L
nuc | C203T, C12025T, C24370T, T25333C 

</body>
</html>

**Evidence**
Down-sampled tree as per Neherlab (Africa-Ghana, filtered to B.1.617.2):
![image](https://user-images.githubusercontent.com/86835836/147231195-ffb31947-4be3-4009-aae9-35c9ddd70f7a.png)
https://nextstrain.org/groups/neherlab/ncov/africa-ghana?branchLabel=aa&c=gt-S_17&label=Spike%20mutations:V1264L&r=division

Usher tree:
![image](https://user-images.githubusercontent.com/86835836/147243734-d0286121-90cc-45bd-b8b3-6c894cb48e08.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_eec7_292e60.json?c=gt-S_17&l=radial

Transmission advantage as per Cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/147243823-18fdf713-89ff-447e-81c3-21f236506454.png)
https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3AP499R%2CS%3AN17K%2CS%3AL18F%2CORF1a%3AH1500Y

**Genomes**:
[N17K+L18F+P499R+V1264L.csv](https://github.com/cov-lineages/pango-designation/files/7795214/N17K%2BL18F%2BP499R%2BV1264L.csv)

**Comment by c19850727** [comment]
Also, there're a few sequences within this proposed sublineage that have a few additional Spike mutations:

<html>
<body>


Gene | Mutations
-- | --
Spike | T29I, H49Y, P479S, D574Y


</body>
</html>

![image](https://user-images.githubusercontent.com/86835836/147244213-6560a472-61b2-471e-b94a-41589557d8fd.png)

**Comment by InfrPopGen** [comment]
Please could we have a "list of genome names as found on GISAID or accession ids - provide as a CSV/TSV table attachment - include locations and dates of sampling" as mentioned in the lineage proposal guidelines. If we infer them from nextstrain trees then there might be the possibility of some discrepancies. Thank you.

**Comment by c19850727** [comment]
My apologies @InfrPopGen . 
I was temporarily having some trouble downloading a CSV from GISAID. Will do it later today.

**Comment by chaoran-chen** [comment]
Hi. Just another quick note from CoV-Spectrum: You can download a list with the GISAID IDs and the contributing laboratories by clicking on the "Sequence list [download]" button.

![image](https://user-images.githubusercontent.com/18666552/147680395-7f744771-2581-4adb-96ea-70ac86768e68.png)

https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3AN17K%2CS%3AL18F%2CS%3AP499R%2CS%3AV1264L&pangoLineage=B.1.617.2*

**Comment by c19850727** [comment]
a million thanks @chaoran-chen ! this is exactly what I need!

**Comment by c19850727** [comment]
Hi @InfrPopGen I've attached a CSV file.

**Comment by InfrPopGen** [comment]
Thanks for submitting (and for the csv). We've added lineage AY.133 with 71 newly designated sequences, in v1.2.120
