### ISSUE TITLE
Potential AY.29 Sublineage in Japan with S:414R

### ISSUE THREAD

**Issue by ItokawaK** [cov-lineages/pango-designation#381]
by Kentaro Itokawa (National Institute of Infectious Diseases, Japan) (_Edited_ 2021-12-29)

This potential sublineage includes >280 _(Edited)_ genomes so far in GISAID (searched for AY.29+S:Q414R in 2021-12-24). Those genomes have been collected only in Japan but from geographically divergent locations across the country.

Interestingly, the same spike mutation is also seen among the sublineage of AY.3 (AY.3.3), which was recently assigned  (issue  #365).

**Description**
Sub-lineage of: AY.29
Earliest sequence: 2021-08-04 (Japan/Tokyo, EPI_ISL_4696941)
Most recent sequence: 2021-12-11 (Japan/Nagano, EPI_ISL_7859592)
Countries circulating: Japan

**Substitution on top of AY.29**

| Gene | Mutations |
| ------ | ------- |
| Spike | Q414R |
| Nuc | A22803G |

**Genomes**
GISAID entries of AY.29 with S:Q414R mutation.
[gisaid_hcov-19_2021_12_24_08.tsv.txt](https://github.com/cov-lineages/pango-designation/files/7773401/gisaid_hcov-19_2021_12_24_08.tsv.txt) _(Edited)_

**Tree**

![usher_S_414R](https://user-images.githubusercontent.com/38896687/147327387-ad579ff9-a78c-42e2-9c74-4d320d798413.PNG)

**Others**
CovSPECTRUM result, country: Japan (2021-12-24).

https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?aaMutations=S%3AQ414R&pangoLineage=AY.29

![covspectrun_Q414R_1](https://user-images.githubusercontent.com/38896687/147327455-22696ce9-b782-490e-aa35-0b29bcb0028c.PNG)

![covspectrun_Q414R_2](https://user-images.githubusercontent.com/38896687/147327462-3f642e08-ae71-4775-8520-155277ac4a82.PNG)

**Comment by ItokawaK** [comment]
[Update]

It appeared that there are actually two independent origins of S:Q414R within AY.29, one containing 278 or more genomes, which I mentioned above, and the other containing only 3 genomes as shown below.  

![Q414R_lineage2](https://user-images.githubusercontent.com/38896687/147435095-06446ca8-7380-4e9f-95b0-b1551b6d94c9.PNG)

Thus, I provide a new GISAID list excluded the 3 genomes belonging the small cluster.
[gisaid_hcov-19_2021_12_24_08-02.tsv.txt](https://github.com/cov-lineages/pango-designation/files/7778353/gisaid_hcov-19_2021_12_24_08-02.tsv.txt)

My apology.

**Comment by ItokawaK** [comment]
[Update 2]

As >100 more genomes of AY.29+S:Q414R has been uploaded in GISAID since yesterday, a clearer picture may be available.

The potential sublineage (AY.29+S:Q414R) rather invloves another potential sub-sublineage which seems to be growing. 

The date of the most recent sequence became 2021-12-20.

**Mutations:**
| Nucleotide | Amino Acid |
| ----   | ---- |
| C2509T|  synonymous |
| A22803G | S: Q414R |
| G28541T | N: A90S |
| C29144T| synonymous  |

**List of the potential sub-sublineage genomes:**
[sub-sublineage.list.tsv.txt](https://github.com/cov-lineages/pango-designation/files/7783283/sub-sublineage.list.tsv.txt)

The prevalence of this potential sub-sublineage could be comparable to other AY.29 now.

![auspice](https://user-images.githubusercontent.com/38896687/147535632-1b7e23b5-74d0-40f0-9cd0-2c6e5b776dc7.PNG)

**Auspice json:**
[S_Q414R_AY29.json.txt](https://github.com/cov-lineages/pango-designation/files/7783288/S_Q414R_AY29.json.txt)

**Comment by ItokawaK** [comment]
[Update 3]

Although it is obscured by the recent surge of Omicron, the S:Q414R > N:S90A > nuc:C2509T > nuc:C2914T sub-sublineage of AY.29 seems to keep growing. 

![AY29_sub_20220121a](https://user-images.githubusercontent.com/38896687/150523395-a9687ed2-e0f6-4113-b338-f3817efa870b.PNG)

Now frequency of this lineage may already have exceeded more than half the cases of AY.29, which is the dominat sub-lineage of Delta in Japan.  

![AY29_sub_20220121_freq](https://user-images.githubusercontent.com/38896687/150523434-837ffc26-b4af-47f1-b5b2-8e12a0af4464.PNG)

I believe they are worth designation and monitoring in the future, but am not sure the proper location of the root (S:Q414R or nuc:C2914T?). 

![AY29_sub_20220121b](https://user-images.githubusercontent.com/38896687/150523504-cda66d0b-08eb-4442-bfbe-a5815caec6f7.PNG)

Figures from:
https://nextstrain.org/community/kkosaki/ncov/japan?c=gt-nuc_29144&f_pango_lineage=AY.29 (Data updated 2022-01-20)

**Comment by FedeGueli** [comment]
This clade showed a monster growth advantage to the baseline of all delta sublineages too.
Probably the results is biased by the rapid decline/extinction of high transmissible lineages as AY.4.2*/AY.43* in high volume sequencing countries as Uk and Dk.
But the same i think it is worth to take a look at this and designate it . @corneliusroemer @chrisruis .

![Schermata 2022-02-05 alle 10 12 58](https://user-images.githubusercontent.com/87669813/152635857-195b1834-1f35-4d53-8de2-041063ebf292.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage AY.29.2 with 391 newly designated sequences, in v1.2.134

**Comment by corneliusroemer** [comment]
Just independently discovered this. Massive growth advantage for a single substitution!

It swept in 2 months, would have gone around the world had Omicron not appeared.

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/25161793/162591572-249bd6c1-c44c-40eb-a2e7-8cb1d39c5376.png">

https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?pangoLineage=AY.29*&aaMutations1=S%3A414&pangoLineage1=AY.29*&analysisMode=CompareToBaseline&
