### ISSUE TITLE
Proposal for a Sublineage of AY.5 with Spike N501Y (~320 Sequence, ~1.3% Prevalence in Israel)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#387]
Sources in Israel told me this potential sublineage started growing in the circulating samples (community, no connection to imported cases) from mid-end November.

**Description**
**Sub-lineage of**: AY.5 (mostly classified as AY.5 by Usher and as AY.47 by Pango/GISAID)
**Earliest sequence**: 2021/8/20
**Most recent sequence**: 2021/12/20
**Countries circulating**: Israel mainly

**Substitutions on top of AY.5**:
<html>
<body>

Gene | Mutations
-- | --
ORF1a:  | G3575S
Spike:  | N501Y
nuc | A20418G

</body>
</html>

It might also be worth considering starting this potential sublineage from one step further into the branch, with the following additional mutations (as this subclade grows considerably faster and makes up most recent sequences):

<html>
<body>

Gene | Mutations
-- | --
ORF1a:  | G82-, H83-, V84-, M85-, V86-, A405S, E1633D
ORF1b:  | E75A
ORF8:  | E106stop
nuc | C9532T, G21255C

</body>
</html>

Evidence
Down-sampled tree as per Neherlab (Israel, filtered to AY.5/Usher, yellow=N501Y; light green=N501Y+E106stop):
![image](https://user-images.githubusercontent.com/86835836/147798758-237d7df2-2571-4d4b-a1af-103a412bf0c9.png)
Geographical distribution as per Neherlab (Israel, filtered to Delta 21A/21I/21J, yellow=N501Y; light green=N501Y+E106stop):
![image](https://user-images.githubusercontent.com/86835836/147798830-ebe9ae45-c8f1-4cee-b3d6-ad04c996ada0.png)
https://nextstrain.org/groups/neherlab/ncov/israel?branchLabel=aa&c=gt-nuc_23063,28209&f_pango_usher=AY.5&p=full&r=division&tl=pango_usher

Usher tree (yellow=N501Y; orange=N501Y+E106stop):
![image](https://user-images.githubusercontent.com/86835836/147799522-216bba75-c3ec-457a-870d-b9517f151e4e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f49c_de6ea0.json?c=gt-nuc_23063,28209&l=radial

Relative growth rate as per cov-spectrum (24% with additional ORF8:E106stop):
![image](https://user-images.githubusercontent.com/86835836/147799908-1055be6a-8c09-45db-9790-81380d98ff61.png)
International comparison as per cov-spectrum (~1.3% with additional ORF8:E106stop):
![image](https://user-images.githubusercontent.com/86835836/147799916-51063e79-ef7d-4ed1-9c06-7177de1e6901.png)
https://cov-spectrum.org/explore/Israel/AllSamples/Past6M/variants?aaMutations=S%3AN501Y%2CORF1a%3AG3757S%2CM%3AI82T

**Genomes**:
[Israel N501Y.csv](https://github.com/cov-lineages/pango-designation/files/7795201/Israel.N501Y.csv)
[Israel N501Y+E106stop.csv](https://github.com/cov-lineages/pango-designation/files/7795202/Israel.N501Y%2BE106stop.csv)

**Comment by FedeGueli** [comment]
The growth rate advantage of this clade vs B.1.617.2 all sublineages baseline was really slight:
![Schermata 2022-01-26 alle 13 42 20](https://user-images.githubusercontent.com/87669813/151164951-7079830f-197e-4ed4-8f18-8f227beda503.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage AY.5.7 with 188 newly designated sequences, in v1.2.140
