### ISSUE TITLE
Proposal for a Sublineage of AY.112 with Spike D936G and P1263Q (~250 Sequence, ~1.6% Prevalence in Israel)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#388]
**Description**
**Sub-lineage of**: AY.112 (classified as B.1.617.2 by Usher)
**Earliest sequence**: 2021/8/23
**Most recent sequence**: 2021/12/20
**Countries circulating**: Israel mainly

**Substitutions on top of AY.112**:
<html>
<body>

Gene | Mutations
-- | --
ORF1a:  | K120N, T2016I, K4176N
ORF3a:  | A110S
Spike:  | D936G, P1263Q
nuc | G2407A

</body>
</html>

**Evidence**
Down-sampled tree as per Neherlab (Israel, filtered to B.1.617.2, in light green color):
![image](https://user-images.githubusercontent.com/86835836/147793677-bf2beb73-5e94-46cd-abb4-3a9cd2658bea.png)
Geography distribution as per Neherlab (in light green color):
![image](https://user-images.githubusercontent.com/86835836/147793781-8b3c024e-d774-4ae5-a0e3-8f67e6686764.png)
Mutations on branch as per Neherlab:
![image](https://user-images.githubusercontent.com/86835836/147794130-0a0e4db6-e28d-476b-bbbe-d7325b224bb1.png)
https://nextstrain.org/groups/neherlab/ncov/israel?branchLabel=aa&c=gt-S_1263,936&f_pango_usher=B.1.617.2&p=full&r=division

Usher tree (in orange color):
![image](https://user-images.githubusercontent.com/86835836/147793889-121c47be-a6a1-4d70-b483-f08b0c722b6a.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12b8c_bf7420.json?c=gt-S_1263&l=radial&label=nuc%20mutations:G29422T

Relative growth rate as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/147794020-08603308-d530-406e-ab51-c801c4147bce.png)
International comparison as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/147794055-13f314ab-ce4d-485a-bc58-2e68007a234e.png)
https://cov-spectrum.org/explore/Israel/AllSamples/Past6M/variants?aaMutations=ORF3a%3AL85F%2CS%3AD936G%2CS%3AP1263Q

**Genomes**:
[Israel D936G+P1263Q.csv](https://github.com/cov-lineages/pango-designation/files/7794872/Israel.D936G%2BP1263Q.csv)

**Comment by FedeGueli** [comment]
I think it is really AY.112 
Quite clear from Usher tree ( and Usher too AY.112 )
![Schermata 2021-12-31 alle 11 04 04](https://user-images.githubusercontent.com/87669813/147817148-ffd0d446-ea4b-4e7c-87c0-79a4bcec8d2f.png)
![Schermata 2021-12-31 alle 11 04 49](https://user-images.githubusercontent.com/87669813/147817173-f4f75ebd-d423-4acf-b280-8d9768ed785c.png)

**Comment by FedeGueli** [comment]
This clade has a slight growth rate advantage on B.1.617.2 all sublineages baseline:
![Schermata 2022-01-26 alle 13 36 57](https://user-images.githubusercontent.com/87669813/151164268-ae5bf847-1642-4013-92a1-9b1a5a9f66f3.png)
