### ISSUE TITLE
Lithuanian B.1.1.7 sub-lineage

### ISSUE THREAD

**Issue by evogytis** [cov-lineages/pango-designation#39]
New lineage proposal
by Rimvydas Norvilas, Ingrida Olendraitė, Dovilė Ežerskytė, Daniel Naumovas, and Gytis Dudas

Description
Sub-lineage of: B.1.1.7
Earliest sequence: 2021-02-15 (hCoV-19/Lithuania/S21B109/2021, current date on GISAID is incorrect)
Most recent sequence: 2021-03-22 (hCoV-19/Lithuania/S21C992/2021)
Countries circulating: Lithuania

A distinct cluster of B.1.1.7 infections comprising over half (204/384 genomes) of currently sequenced B.1.1.7 genomes in Lithuania. This sub-lineage was first detected in Vilnius county and is still concentrated there, though onward spread to other counties is apparent too. Given the prevalence of this sub-lineage (the next biggest distinct B.1.1.7 cluster in Lithuania has <40 genomes) we believe it is likely to dominate the rest of the Lithuanian epidemic.

Genomes
[B.1.1.7_VN.txt](https://github.com/cov-lineages/pango-designation/files/6248428/B.1.1.7_LTU.txt)

Evidence
![B 1 1 7_ltu](https://user-images.githubusercontent.com/1536822/113395652-7dd09380-939a-11eb-81c9-aaa74a787c53.png)

Proposed lineage name
VN

**Comment by rambaut** [comment]
There are a batch of `B.1.1.7.X` sublineages being defined/designated. These will be given the alias `Q.X`.

**Comment by chrisruis** [comment]
Thanks @evogytis for submitting. We've added this as Q.1 in [v1.2.51](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.51) with 4820 sequence designations

**Comment by nknox** [comment]
Hi Scott,
The latest AB omicron just made it into the data portal thanks to Nithu!

Thanks,
Natalie

On Nov 30, 2021, at 9:14 PM, Knox, Natalie (PHAC/ASPC) ***@***.***> wrote:

﻿

Thanks @evogytis<https://github.com/evogytis> for submitting. We've added this as Q.1 in v1.2.51<https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.51> with 4820 sequence designations
