### ISSUE TITLE
Proposal for Danish BA.2 sublineage with nuc:C22792T (240 seqs, 10-20% of Omicron in Denmark)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#390]
A BA.2 sublineage seems to be growing in Denmark, even as a share of all Omicron, and spreading from there to other parts of Europe (Sweden, Germany) and beyond. Of course due to small numbers, it's unclear whether this is just a chance event or not.

In Denmark its share of all Omicron has grown as follows:
CW 48: 0.3% [1 of 300 Omicrons]
CW 49: 0.3% [4 of 1k Omicrons]
CW 50: 4% [100 of 2k Omicrons]
CW 51: 9% [105 of 1k Omicrons]

The growth of BA.2 in Denmark (and India, different sub-lineage) was brought to my attention by Josette Schoenmakers and Dmitry Pruss

Earliest collection possibly in Canada: 2021-12-03 but recent growth is most striking in Denmark and surrounding countries.

It is defined by one nucleotide mutation `nuc:C22792T`.

Geographical clustering is very clear (green is the sub-lineage)

![image](https://user-images.githubusercontent.com/25161793/147857365-3fa0f12a-cbbb-481b-b70d-a775b830a611.png)

Usher tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26f5d_9aaf0.json?c=gt-nuc_22792

**Comment by MCB6** [comment]
> CW 49: 0.3% [4 of 1k Omicrons]
> CW 50: 4% [100 of 2k Omicrons]
> CW 51: 9% [105 of 1k Omicrons]

A similar trend in Sweden's populous Skåne (North or Stockholm), but of course with much weaker numbers (today's upload)

CW 49: 0% (0/67 Om)
CW 50: 2% (2/84 Om)
CW 51: 7% (4/58 Om)

There, Omicron didn't dominate yet, like it did in Denmark, but within-Omicron dynamics didn't look different.

**Comment by silcn** [comment]
Intriguingly, the single synonymous mutation defining this lineage is at codon 410 in the S gene (ATC->ATT), close to the BA.2 mutations S:D405N and S:R408S. Perhaps the mutation does in fact have functional relevance.

**Comment by MCB6** [comment]
Denmark resumed sequencing after a holiday break, already adding over 200 BA.2 genomes. In the most recent Danish Omicron samples (collected 12/27), the share of BA.2 approaches 20%. 
In addition to previous BA.2 hotspots in South-Western Sweden, a new BA.2 cluster emerged in Central Sweden, where the share of BA.2 increased to nearly 10% within days.
![image](https://user-images.githubusercontent.com/93294184/148085450-0303139c-bca1-4f2b-a0b5-e76a3b5866f1.png)
![image](https://user-images.githubusercontent.com/93294184/148085489-c276083e-09a3-4798-800c-ddb05cdf3043.png)

**Comment by FedeGueli** [comment]
Tweet from Josette who first monitored the increasing share of BA.2 in Denmark
it appears now clearly growing in Denmark
https://twitter.com/JosetteSchoenma/status/1478449668690489347?s=20

@chrisruis

**Comment by KatSteinke** [comment]
We're using the ARTIC protocol with V4 primers and seeing dropout in a lot of our BA.2 sequences in the area covering that mutation (22475-22975), and have heard from others who also do - I wonder how the spread of that mutation would look if we managed to catch that amplicon...

**Comment by KatSteinke** [comment]
Hm, that mutation is in an amplicon where people have seen dropout in many BA.2 sequences using the ARTIC protocol and V4 primers, isn't it? Wonder how much that affects prevalence data.

**Comment by corneliusroemer** [comment]
@KatSteinke Thanks for pointing this out. Looking at the alignments, it doesn't look like there are that many sequences with `N`s in this region.

It would have to be a lot of labs silently backfilling with reference instead of reporting Ns. Most labs that have reference at 22792 have mutated 22786 and 22813 as you can see on the screenshot. So it does look like it could be real, to me.

![image](https://user-images.githubusercontent.com/25161793/148421192-c09a9f7a-b7f2-4ccf-ad2a-e6e3961340cd.png)

**Comment by MCB6** [comment]
The correlation between region / travel pattern and substrain spanned national boundaries in the way the artifacts never do, anyway.
BTW I am ready to declare that BA.2 has a true biological advantage. Regardless of the silent mutations of course. The percentage of BA.2 grew to too high numbers in too many places to easily explain by fluctuations. In Denmark, if you consider the positive results dynamics representative, it'd seem that by the 28th of December BA.1 was already in decline, but BA.2, still growing. Of course it's harder to reconcile the idea of a biological advantage with the fact that BA.2 hasn't spread wide in South Africa, at least so far. Could it be disadvantaged by Beta-induced prior immunity???
![image](https://user-images.githubusercontent.com/93294184/148431546-93741261-fb79-4ce0-9de1-379b1424946e.png)
![image](https://user-images.githubusercontent.com/93294184/148431646-486c28d7-b683-47b6-896b-5f1b368e6ad8.png)

**Comment by JosetteSchoenma** [comment]
@MCB6 I looked at the different regions in South-Africa and all but one of the BA's were from Gauteng or Kwazulu-Natal. Looking only at these regions, BA.2 does seem to grow faster than BA.1, but there aren't any sampled for the last weeks. Also, very few samples, but BA.2 seems to have taken over in the Phillipines.
![Screenshot_20220106-130703_Office](https://user-images.githubusercontent.com/94831035/148459264-d364fe2f-ffff-4347-b4cb-8c9440332440.jpg)
![Screenshot_20220105-135801_Office](https://user-images.githubusercontent.com/94831035/148459271-47c89945-8727-4973-9fee-224726706837.jpg)
![Screenshot_20220105-135730_Office](https://user-images.githubusercontent.com/94831035/148459274-4dc2ecd1-0944-4735-8dc9-beeedac97dca.jpg)

**Comment by MCB6** [comment]
I didn't realize that neither NICD nor KRISP continue sequencing,  so I wrongly took the absence of BA.2 in the ZA uploads at the face value. Thank you for clearing my confusion.  The drop of the wave was followed there by a kind of a high plateau with possible signs of a new uptick in recent days, and one might hypothesize that BA.2  may be the reason. But I am afraid that the discussion may be off topic here, since we are talking about the ancestral form. 
![FB_IMG_1641497755988](https://user-images.githubusercontent.com/93294184/148481377-e4a06e4d-07f3-4718-9d2d-79746c29f11f.jpg)
![FB_IMG_1641497750067](https://user-images.githubusercontent.com/93294184/148481380-d453aad6-d6cf-44ce-9db2-5fa9728b1aaa.jpg)

**Comment by JosetteSchoenma** [comment]
Yes, that is interesting. And yes, it is about the ancestral form, but it is interesting to know if the ancestral form is already growing faster, so it might not be caused by the extra mutations in the sublineage. By the way, the plateau might also be (partially) caused by returning workers from abroad, after the Christmas/summer holiday.

**Comment by MCB6** [comment]
In Denmark, day-to-day test positivity started growing again, and same-day testing availability dropped again, just BA.2 fraction reached 50%. It's hard to be certain about testing trends over so few days, but the hypothesis is that BA.2 may be able to spread more or less successfully at the tail end of a BA.1 wave, not completely impeded by anti-BA.1 immunity

Something similar may be implied from today's Botswana uploads, which show rapid increase of BA.2 share to ~13% around New Year's while the number of positive tests remains high and doesn't drop from the record highs, potentially indicating one strain's spread even as the previous one stagnates and shrinks. But again, it's too fragmentary data to tell anything with clarity.

**Comment by MCB6** [comment]
Tom Peacock has a great thread on BA.2 https://twitter.com/PeacockFlu/status/1483768659420094464
but he insists that because BA.2 doesn't seem to have an inherent biological advantage over BA.1, it shouldn't be capable of causing an additional wave. I actually think that this week's data from Denmark prove the opposite. Just as BA.2 became dominant, the wave took off. (Not just the case numbers but positivity and test appointment availability went in synch too)
It very much looks like a BA.2-specific wave:
![image](https://user-images.githubusercontent.com/93294184/150197658-a68af7cf-8306-489b-917f-80ce672e509c.png)

My hypothesis is that while BA.2 isn't biologically more infectious, it is simply capable of reinfecting either people who were infected by BA.1 literally weeks ago, or people who have prior neutralizing anti-BA.1 immunity, or perhaps both.
Note that the last five datapoints on the graph are projections (assuming linear 2.5% a day growth of BA.2 fraction within Omicron).

If the hypothesis is true then we may end up with back-to-back BA.1/2 waves, extending the duration of the Omicron wave(s)

**Comment by MCB6** [comment]
@JosetteSchoenma 

You are doing a through job popularizing BA.2 on Twitter, although I still haven't see a good discussion of the immunological mechanisms of the Danish double wave (how does BA.2 evade the post-BA.1 immunity so soon?). Bloom lab's report notes that overall, BA.2 shouldn't be much more evasive than BA.1, but what about post-BA.1 immunity specifically?

I think I have a sort of an answer. BA.2 literally carpet-bombed antibody site IIA where many broadly-specific neutralizing antibodies used to bind. Among them were several therapeutic antibodies, which were already disrupted by Omicron's mutations at the Spike's positions 417, 446, or 496-505. But the "live" situation with the B-cells ought to be more flexible. Unlike ready-made monoclonal antibodies, the "live" ones acquire additional somatic mutations during each new encounter with the antigen, and can learn to overcome the effects of an evasive mutation or two. Well, BA.2 engaged in saturation mutagenesis of the Class IIA site, adding T376A, D405N, R408S, removing two Omicron's mutations G446S and G496S, and replacing BA.1's S371L by S371F. With so many added changes, BA.2 should thoroughly evade any broadly specific Class IIA antibodies even after they become fine-tuned to neutralize regular Omicron. And I guess that Omicron-neutralizing antibodies are very often drawn from this class, so an ability to evade them gives BA.2 a strong edge in the societies with pervasive BA.1 reinfections or breakthrough infections. 
On a brighter side, Sotrovimab's site (class IV) is largely unaffected by BA.2's new mutations. R408S is "almost" touching this monoclonal antibody and this may cause a decrease in neutralization, but probably only a minor one.
![image](https://user-images.githubusercontent.com/93294184/150410530-9f7860a9-0970-4d58-b4b0-4306df869090.png)

![image](https://user-images.githubusercontent.com/93294184/150410563-38eb9fe2-0a21-40ad-b10b-533ed7b7d67c.png)

![image](https://user-images.githubusercontent.com/93294184/150410607-1f881f80-4c28-4a1f-9565-32444376c76a.png)

![image](https://user-images.githubusercontent.com/93294184/150410646-544f0152-9b08-4241-85bc-a11a50ef20c6.png)

1. https://www.biorxiv.org/.../10.1101/2021.12.12.472269v2.full
2. https://www.nature.com/articles/s41586-021-03807-6/figures/9
3. https://www.rcsb.org/3d-view/7JX3/1
4. https://www.rcsb.org/3d-view/7R6W?preset=electronDensityMaps

**Comment by MCB6** [comment]
One more independent study shows that pan-strain antibodies effective against Omicron and older strains rely on Spike's residues D405, R408, and on the pocket of amino acid residues 371-378, all of which are changed in BA.2. It further confirms the hypothesis that BA.2-specific mutations have been selected to evade those of pre-Omicron-origin antibodies which undergo clonal expansion specifically in response to subsequent Omicron infection
![image](https://user-images.githubusercontent.com/93294184/150568268-d9baadc8-4bdc-4d3a-bacb-ae5ec6e91230.png)
https://www.biorxiv.org/content/10.1101/2022.01.19.476892v1.full.pdf

**Comment by bitbyte2015** [comment]
![image](https://user-images.githubusercontent.com/36325823/152635358-165560c0-c2fa-4b98-9070-2e10f2458f5b.png)
Another particularly interesting sub-lineage from this is the ORF3a:H78Y branch which has a child branch with a synonymous C22570T at S:336

**Comment by corneliusroemer** [comment]
Closed in favour of #432

This lineage here doesn't have an amino acid mutation
