### ISSUE TITLE
BA.2 sequences from Indian travelers to Singapore appear to have elements of BA.1 Spike NTD

### ISSUE THREAD

**Issue by bitbyte2015** [cov-lineages/pango-designation#392]
![image](https://user-images.githubusercontent.com/36325823/147917027-9b1f94e1-89de-4225-aaa8-e07bc47139eb.png)

Here is a modified version of Rambaut's table from #361 
[Omicron_BA.1_BA.2_mutations.csv](https://github.com/cov-lineages/pango-designation/files/7801267/Omicron_BA.1_BA.2_mutations.csv)

Sequences: EPI_ISL_8092780, EPI_ISL_8092783

Only 2 sequences so far both from Indian travelers to Singapore but most of the shared mutations with BA.1 appear to be in the spike NTD between codons 69-212 with the exception of S:T95I so perhaps it is a recombinant or something else. Almost all of the mutations of BA.2 are shared. The sequences also share ORF1a:SL2083I with BA.1 outside of the S gene.

**Comment by yexiao-cheng** [comment]
It is weird that both of these four shared mutations with BA.1 are deletions or indel. Is it convergent evolution of deletions or sequencing error?

**Comment by bitbyte2015** [comment]
Sequences updated. no more deletions
