### ISSUE TITLE
Multiple BA.1 sublineages carrying ORF1A:K3353R, New York

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#395]
With this proposal i would like to highlight that, as @zach-hensel pointed to me, there are  multiple emerging sublineage of BA.1 carrying the mutation Orf1A:K3353R.
We met this mutation before in AY.124 sublineage of Delta , dominant in Portugal for a long time, AY.113 and earlier in sublineages of Alpha and Beta.

Here i propose one of them mainly from New York city:
Mutations:
Nuc: C2407T (Orf1a:714)
then nuc:  A14940G (Orf1b:491) and A10323G (ORF1ab: K3353R)

[Usher tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3429f_8acbc0.json?branchLabel=aa%20mutations&label=nuc%20mutations:A10323G)
![Schermata 2022-01-08 alle 09 29 49](https://user-images.githubusercontent.com/87669813/148637612-7ffe4a06-e3c4-432d-b7c2-6eb303165354.png)

Sequence list:
[contributors (6).csv](https://github.com/cov-lineages/pango-designation/files/7832901/contributors.6.csv)

[Covspectrum](https://cov-spectrum.org/explore/United%20States/AllSamples/Past6M/variants?aaMutations=Orf1a%3AK3353R&nucMutations=A14940G&pangoLineage=BA.1*)

Interestingly  one sample was collected in Japan (Dont know if this is linked with the outbreak in the american army)

**Comment by zach-hensel** [comment]
ORF1a:K3353R (NSP5_K90R) is also ~defining for B.1.351.

The Japan sequence metadata says it's a sequence found in airport test/quarantine for international arrivals.

Separately and without ORF1a:K3353R, recent BA.1 domestic cases in Yamanashi and Shizuoka, Japan (e.g. EPI_ISL_8439369) contain ORF1a:T3432S (NSP5_T169S) which may have originated in Hawaii and could be linked to nearby base cases. However, there were also several cases of this sub-lineage caught in airport testing earlier in December so it's unclear.

**Comment by FedeGueli** [comment]
Thx @zach-hensel for corrections. Yes you are right:  through now the largest number of global sequences carrying this mutation is still Beta.

**Comment by EthanOConnor** [comment]
Background information from a cursory literature review:

- With an estimated false discovery rate of just under 0.2 in their assessment, (1) finds marginal support for ORF1a:K3353R homoplasy in their sequence dataset (about 1 sigma significance if I understand their use of FDR)

- In contrast, (2) finds strong support for homeplasy using a topological (not based on phylogenetic inference) genomic analysis approach. Finds k3353r to be the 7th strongest evidence for homoplasy of mutations in gisaid, with a tRI (topological recurrence index) of 29, where “a tRI >= 2 is already a statistically significant signal (p < 0.05)”. I don't think their p-values are look-elsewhere corrected, in contrast to (1).
 
- This mutation is in a region of NSP5 found to be "moderately conserved" across 44 _Sarbecovirus_ genomes (3)
 
- It is the most frequent genome-wide non-C-to-U substitution found by (4), which also comments that the substitution is distal from the active site and the nsp5 dimer interface, and so may not be functionally significant
 
- (5) agrees with functional insignificance, but finds that the mutation may have an impact on the nsp5 CD4+ epitope

(1) Jo, Yoon-Seo, et al. "SARS-CoV-2 convergent evolution cannot be reliably inferred from phylogenetic analyses." bioRxiv (2021).
(2) Bleher, Michael, et al. "Topology identifies emerging adaptive mutations in SARS-CoV-2." arXiv preprint arXiv:2106.07292 (2021).
(3) Jungreis, Irwin, Rachel Sealfon, and Manolis Kellis. "SARS-CoV-2 gene content and COVID-19 mutation impact by comparing 44 Sarbecovirus genomes." Nature communications 12.1 (2021): 1-20.
(4) Wright, Erik S., Seema S. Lakdawala, and Vaughn S. Cooper. "SARS-CoV-2 genome evolution exposes early human adaptations." bioRxiv (2020).
(5) Rahman, Md Marufur, Shirmin Bintay Kader, and SM Shahriar Rizvi. "Molecular characterization of SARS-CoV-2 from Bangladesh: Implications in genetic diversity, possible origin of the virus, and functional significance of the mutations." Heliyon 7.8 (2021): e07866.
