### ISSUE TITLE
Proposal to withdraw AY.89 because it nests within AY.4 and is maybe not even monophyletic

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#398]
AY.89 is defined on the Usher tree by `C6402T > C21304A > G21305A > C21302T > C7851T`

The last mutation `C7851T` is what defines AY.4. AY.89 is a UK lineage, just like AY.4

AY.89 contains lineage with extra mutations that also appear within AY.4, like T17040C and 4237C. This homoplasy is suspicious.

The three mutations `C21304A > G21305A > C21302T` are on the list of problematic sites.

Considering all of the above, I feel that the way AY.89 clusters on the Usher tree is an artefact. This lineage is probably not a monophyletic one and should thus be withdrawn. Potentially relatedly, pangoLEARN struggles a lot with AY.89 classifying almost none of the lineage defining sequences correctly (according to Usher).

Usher tree with all the AY.89 defining mutations:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_255b2_c2e4f0.json

**Comment by FedeGueli** [comment]
Thx @corneliusroemer it was briefly discussed as offtopic in this issue #300 https://github.com/cov-lineages/pango-designation/issues/300
with @AngieHinrichs

**Comment by corneliusroemer** [comment]
Oh I see, thanks @FedeGueli 

Here's the comment https://github.com/cov-lineages/pango-designation/issues/300#issuecomment-958683362

**Comment by AngieHinrichs** [comment]
Ah, I forgot it had come up before, and as @FedeGueli anticipated in [the next comment](https://github.com/cov-lineages/pango-designation/issues/300#issuecomment-958708908), @corneliusroemer indeed found some AY.4 diversity within AY.89 sequences.

So I agree, probably an error.  If @chrisruis agrees then I can mask those sites within Delta, do a little reoptimization, and then UShER should place those sequences within AY.4.

**Comment by chrisruis** [comment]
Thanks @AngieHinrichs The masking and reoptimization sounds great

**Comment by AngieHinrichs** [comment]
OK, today's build will mask 21302, 21304 and 21305 in Delta -- it should complete tomorrow morning & then I'll check on it.  It might not be available on the main site (genome.ucsc.edu) until the following day.  A preliminary mask & optimize test with yesterday's tree went pretty well -- I spot-checked some sequences that were on the nodes for C21304A, G21305A, and C21302T, and they were moved next to similar sequences all over Delta (and of course the C7851T AY.89 sequences moved to AY.4).

**Comment by corneliusroemer** [comment]
Great thanks!

Is the outcome of Usher tree building a dependency for withdrawing AY.89 or
could we move ahead already without it?

I think given the apparent homoplasies within AY.89 that resemble AY.4
diversity we all agree that AY.89 is actually just AY.4 potentially with a
few extra mutation that are however problematic? Or are there different
views?

**Comment by chrisruis** [comment]
I agree that it looks like the AY.89 sequences should be in AY.4. It sounds like it won't take Angie very long to check with a reoptimized tree so I'm happy to wait for that

**Comment by AngieHinrichs** [comment]
Yes, in the 2022-01-11 tree with 21302. 21304 and 21305 masked in the Delta branch (not yet available on the public site), all samples in the 2021-01-10 branch for AY.89 were moved into the AY.4 branch as expected.

AY.32 had C21304T in the [set of defining mutations](https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/utils/otto/sarscov2phylo/pango.clade-mutations.tsv) that I use to annotate nodes as lineage root; since 21304 is now masked in the whole Delta branch, that may cause a few more sequences to be moved into the AY.32 branch but I haven't looked into that yet.

Anyway, all go for withdrawing AY.89, thanks for pointing it out @corneliusroemer!

**Comment by chrisruis** [comment]
Thanks Angie. We've merged AY.89 into AY.4 in [v1.2.123](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.123). AY.89 is therefore withdrawn
