### ISSUE TITLE
Proposal for new lineage within B.1

### ISSUE THREAD

**Issue by rambaut** [cov-lineages/pango-designation#4]
### Description
Sub-lineage of: B.1
Earliest sequence: 2020-12-15 (England/CAMC-C769B3/2020)
Most recent sequence: 2021-01-28 (England/MILK-119FD0B/2021)
Countries circulating: England (28), Nigeria (7), USA (7), France (5), Canada (4), Ghana (4), Japan	 (4), Jordan (2), Belgium (1), Italy (1), Spain (1)

Characterised by spike mutations: E484K, Q677H, F888L, 69-70 deletion, 144 deletion and 9 nucleotide mutation in nsp6 (as seen in B.1.1.7, B.1.351, P.1).

### Genomes
[B.1.525_genomes.txt](https://github.com/cov-lineages/pango-designation/files/5965743/B.1.525_genomes.txt)

List of genomes, collated 2021-02-11, attached. 

### Evidence

Phylogenetic tree PDF image. Proposed new lineage labels in red:
![B 1 525 ml tree](https://user-images.githubusercontent.com/686405/107643776-80521f00-6c6e-11eb-9f63-322e6054fc41.png)

Phylogenetic tree file:
[B.1.525.ml.tree.txt](https://github.com/cov-lineages/pango-designation/files/5965756/B.1.525.ml.tree.txt)

### Proposed lineage name

To be determined as the the next available designation within B.1

### defining mutations

gene | amino acid | coordinates
-- | -- | --
ORF1ab |   | C1498T
  |   | A1807G
  |   | T8593C
  |   | C9565T
  |   | 11288-11296del
  | L4715F (L323F) | C14407T
  |   | C18171T
  |   | A20724G
spike | Q52R | A21717G
  | 69-70del |  
  | 144del |  
  | E484K | G23012A
  | Q677H | G23593C
  | F888L | T24224C
  |   | C24748T
E | L21F | C26305T
  | I82T | T26767C
N | SD2Y deletion | 28278-28280del
  |   | A28699G
N/ORF10 intergenic |   | G29543T

**Comment by rambaut** [comment]
This will be designated as lineage B.1.525

**Comment by aineniamh** [comment]
Resolved with pango designation [release v1.0.1](https://github.com/cov-lineages/pango-designation/releases/tag/v.1.0.1).

**Comment by rambaut** [comment]
27278-28280 is a more parsimonious nucleotide deletion but causes an deletion of S and D and replacement with Y
<img width="446" alt="image" src="https://user-images.githubusercontent.com/686405/108414570-4e1f5f00-7224-11eb-9b60-4fb812766e31.png">

**Comment by rambaut** [comment]
The resulting (say) VIC18114 sequence is definitely MYNGPQ irrespective of where the deletion is.

**Comment by rambaut** [comment]
Thanks for pointing out the E/M error.
