### ISSUE TITLE
Proposal for lineage within B.1.1.33 (Suggestion lineage N.10)

### ISSUE THREAD

**Issue by paolacristinaresende** [cov-lineages/pango-designation#40]
**New lineage proposal N.10**

Description

**Sub-lineage of:** B.1.1.33

**Earliest sequence:** hCoV-19/Brazil/MA-FIOCRUZ-6871/2021 / EPI ISL 1181371 / 2021-01-04

**Most recent sequence:** hCoV-19/Brazil/MA-FIOCRUZ-11486/2021 / 2021-02-19

**Countries circulating:** Brazil

This new lineage (suggestion N.10) is circulating in the Northeast of Brazil (Maranhao) and North (Amapa). This lineage has evolved from lineage B.1.1.33 major lineage circulating in Brazil since the beginning of the pandemic.
This lineage was characterized by 21 lineage-defining genetic changes 17 including 17 non-synonymous mutations, three deletions, and one no-sense mutation. 
Eight lineage-defining genetic changes are located in the S protein: two mutations at the RBD (E484K and V445A) and two mutations (I210V and L212I) and three deletions (∆141-144, ∆211 and ∆256-258) in the amino (N)-terminal domain.

**Genomes**
[location and sequences.txt](https://github.com/cov-lineages/pango-designation/files/6251243/location.and.sequences.txt)

**Evidence**
![Picture1](https://user-images.githubusercontent.com/80154344/113454354-6c10df80-93de-11eb-94e4-6944c93be17e.jpg)

Proposed lineage name: N.10

**Comment by paolacristinaresende** [comment]
Please, check the post in Virological.org about this new lineage.
 
https://virological.org/t/identification-of-a-new-b-1-1-33-sars-cov-2-variant-of-interest-voi-circulating-in-brazil-with-mutation-e484k-and-multiple-deletions-in-the-amino-n-terminal-domain-of-the-spike-protein/675

**Comment by chrisruis** [comment]
Hi @paolacristinaresende thanks very much for this. We've added this lineage as N.10
