### ISSUE TITLE
Pango/Nextstrain unclassified lineage with high mutational load including S:F490R, S:N501Y, S:p681H and 9 aa deletion Spike aa 136-144, sharing mutations with B.1.640.2 (South of France/Cameroon)

### ISSUE THREAD

**Issue by geertmartens** [cov-lineages/pango-designation#400]
Virus name: hCoV-19/Belgium/AZDelta-2200-03326/2022
Accession ID: [EPI_ISL_8558399](url)

**Case [description**]
The AZ Delta COVID Genomics Core (Roeselare, Belgium) identified N=1 SARS-CoV-2 isolate with aberrant mutation profile. The patient was a 39 year old woman from Menen, Belgium. She traveled to Paris on Dec 22-23, 2021 and developed mild respiratory symptoms and fatigue without anosmia on Dec 31, 2021. Besides a trip to Paris, she had limited contacts since she is a teacher and infection occurred in the holiday. She had no known contacts with other people with a travel history outside Europe. She tested positive on Seegene Allplex with Ct E/N/RdRP-S= 18/23/29.  She was doubly vaccinated by Pfizer/BioNTech, with last dose on July 17, 2021. Her partner and 2 children also tested positive (no samples available for sequencing). Mutation-specific Seegene Novaplex indicated an abnormal profile in an epidemiologic context of 90% Omicron/10% Delta in baseline surveillance by whole genome sequencing: S:N501Y(+), E484K (-) and del69/70 (-), hence selection of sample for whole genome sequencing using Illumina SARS-CoV-2 Research panel. 

**Sequencing QC metrics were good:**  
Total number of reads: 118226
Error rate:0.72%
Median/Mean/Q25/Q75 depth of sequencing: 642/755/418/775
Number of missing nucleotides: 182
Number of variant positions: 60 (Freebayes and GATK Mutect2)
Possibly contaminated positions: 3 (ok)

The consensus FASTA sequence showed a very high mutational load, and a profile that was distinct from the epidemiologically prevailing Omicron and Delta lineages, with absence of typical amplicon dropouts in the SARS-CoV-2 Research panel amplicon design, that was indicative for an older, ancestral lineage. 
Overall QC: good
Total substitutions: 58
Total deletions:58
Total insertions:0
Total missing: 182
Mutations of interest: N501Y, R346S, F490R
Absence of L452R and other Delta-defining mutations
Absence of Omicron defining mutations

Clade calling was done by both Pangolin and Nextclade webtools. Surprisingly, none of these tools could identify the variant (Pangolin: None, Nextclade:20A). 

Manual curation indicated a relatively high degree of resemblance to the B.1.640.2 lineage originated from South of France/Cameroon idenfied by IHU Marseille (D. Raoult et al. MedRxiv : https://doi.org/10.1101/2021.12.24.21268174 ) but also clear divergence with > 20 additional/different amino acid substitutions and a remarkable 9 amino acid deletion in Spike affecting amino acid 136-144. As compared to the B.1.640.2, also the E484K mutation was missing, tested both by Novaplex and by WGS (good coverage at 23012-23014 corresponding to ORF2 amino acid 484. 

Mutation analysis was done by in-house developed pipeline using FreeBayes and GATK-Mutect2

The amino acid substitutions in this unclassified isolate were: 
M:I82T,N:D22Y,N:T205I,N:K373N,N:E378Q,ORF1a:M85V,ORF1a:P309L,ORF1a:E452G,ORF1a:S1188L,ORF1a:L2119F,ORF1a:A2355S,ORF1a:S3149F,ORF1a:R3164H,ORF1a:T3255I,ORF1a:V3718A,ORF1b:P314L,ORF1b:D884Y,ORF1b:K2557R,ORF3a:T32I,ORF3a:Q57H,ORF8:Q27*,ORF9b:I5T,ORF9b:Q18H,S:P9L,S:V11F,S:E96Q,S:R190S,S:I210T,S:R346S,S:N394S,S:Y449N,S:F490R,S:N501Y,S:D614G,S:P681H,S:T859N,S:D936H,S:A942S

The amino acid deletions in this unclassified isolate were: 
ORF1a:G82-,ORF1a:H83-,ORF1a:V84-,S:C136-,S:N137-,S:D138-,S:P139-,S:F140-,S:L141-,S:G142-,S:V143-,S:Y144-

To date, we have no proof of additional local transmission, though we will monitor the situation by a combination of Novaplex and WGS. We submit this issue to ask support by Pango designation comittee in assigning this isolate, and potentially finding other similar cases.

**Comment by geertmartens** [comment]
Excel table with all identified mutations (GATK-Mutect2) in this sampl
[2200-03326_GATK Mutect2 variants and VAF.xlsx](https://github.com/cov-lineages/pango-designation/files/7848121/2200-03326_GATK.Mutect2.variants.and.VAF.xlsx)
e

**Comment by amniewiadomska** [comment]
EPI_ISL_8558399 or Belgium/AZDelta-2200-03326 looks almost identical to B.1.640.1 genomes from France (see EPI_ISL_6471387). 
It is also assigned in GISAID as B.1.640.1 and clusters with other B.1.640.1 genomes in trees.

**Comment by geertmartens** [comment]
I noticed that my sequence was indeed clustered as B.1.640.1 by GISAID. Can anybody comment why both the Nexstrain and the Pangolin webtools failed to assign my sequence accordingly?

**Comment by geertmartens** [comment]
Comparison of our sequence (Accession ID: EPI_ISL_8558399) to all B.1.640 isolates uploaded to GISAID on Jan, 12, 2022 (N=431) indicates indeed a very large similarity to B.1.460.1 but also the differences/private or relatively unique mutations listed below: 

- ORF1a:G82-,ORF1a:H83-,ORF1a:V84-: only observed in our sequence, and one other: hCoV-19/France/HDF-IPP32877/2021|EPI_ISL_6471387|2021-10-27
- N:K373N: unique to EPI_ISL_8558399
- ORF1a:M85V: only observed in our sequence, and one other: hCoV-19/France/HDF-IPP32877/2021|EPI_ISL_6471387|2021-10-27
- ORF1a:S1188L: observed in N=5 of 431 B.1.640 (ours and also hCoV-19/Switzerland/VD-ETHZ-34362364/2021|EPI_ISL_5531392|2021-10-06, hCoV-19/France/NAQ-HCL021203973701/2021|EPI_ISL_6602302|2021-11-02, hCoV-19/France/NAQ-HCL021203975901/2021|EPI_ISL_6602303|2021-11-02, hCoV-19/Switzerland/SG-CLM-12174874/2021|EPI_ISL_8038963|2021-12-17). 
- ORF1b:D884Y: observed in 10 of 431 B.1.640 isolates
- S:V11F: unique to EPI_ISL_8558399
- S:A942S: unique to EPI_ISL_8558399

These differences might be the reason why Pangolin webtool and Nextclade fail to classify our sequence?

**Comment by geertmartens** [comment]
Accession ID: EPI_ISL_8558399 was also analyzed by Dr. Anthony Levasseur (anthony.levasseur@univ-amu.fr, group D.Raoult, IHU Méditerranée Infection, Marseille, France) and this is his comment: "Many thanks for sharing these interesting data. By incorporating your sequences to a global phylogenetic tree (attached to this email), a new branch close to B.1.640.2 appeared. Common mutations are shared but also unique to EPI_ISL_8558399 as you mentioned. Regarding the Pangolin webtool and Nextclade, we also faced to problem for assignment. We probably have to wait for the update of their tool (Pangolearn)
Let's see if some new sequences are coming in the next days/weeks/months.". In the attached pdf, EPI_ISL_8558399 clustering with B.1.640.2 is indicated with an arrow. 
[B.1.640.pdf](https://github.com/cov-lineages/pango-designation/files/7862634/B.1.640.pdf)

**Comment by chrisruis** [comment]
Hi @geertmartens Just looking at this in the latest UShER tree and it looks like EPI_ISL_8558399 sits within B.1.640.1 now:
![B 1 640_clustering](https://user-images.githubusercontent.com/47785131/163427424-5df1275f-d3df-48da-bf6f-79d546dc4a8b.png)

This part of the tree is a bit tricky! But going back from that small cluster EPI_ISL_8558399 is in, mutations C3828T (Orf1ab:S1188L), C13536T and A15426G support it clustering with the nearby sequences. So it looks like EPI_ISL_8558399 is in B.1.640.1
