### ISSUE TITLE
Proposal for a AY.33 Sublineage with Spike R346K (~500 Sequences, ~0.5% Prevalence in Poland)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#403]
**Description**
**Sub-lineage of**: AY.33
**Earliest sequence**: 2021/8/26 (Germany)
**Most recent sequence**: 2021/12/31 (Germany)
**Countries circulating**: Poland, Germany, Spain

**Substitutions on top of AY.33**:
<html>
<body>

Gene | Mutations
-- | --
ORF1b | A520V
ORF3a | Y107S, N119Y
ORF7a | A50S
Spike | R346K
nuc | C7093T

</body>
</html>
Also, the more recent sequences from Germany and Poland have an additional S:V503F; and the more recent sequences from Spain have an additional S:P812L, respectively.

**Evidence**
Down-sampled tree as per Neherlab (Poland, filtered to AY.33, in orange color):
![image](https://user-images.githubusercontent.com/86835836/149648425-e731a77d-6f4c-4cc1-b060-d05a83bb77cf.png)

Geographical distribution as per Neherlab (in orange color):
![image](https://user-images.githubusercontent.com/86835836/149648497-0dcac016-a575-4159-8735-4a97fbb025ca.png)
https://nextstrain.org/groups/neherlab/ncov/poland?branchLabel=aa&c=gt-S_250,346&p=full&r=division

Relative growth advantage as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/149648536-1879e933-6e68-4064-9cb7-3a75e00d0aaa.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AR346K%2CORF7a%3AA50S&pangoLineage=AY.33

Usher tree:
![image](https://user-images.githubusercontent.com/86835836/149648707-fee65a14-1632-4869-8d1d-70795af6eff5.png)

Usher tree showing the subclades with additional S:V503F and S:P812L:
![image](https://user-images.githubusercontent.com/86835836/149648789-e886496f-76ea-4f7e-a3af-d2cf86dd103d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_752f_3ae080.json?branchLabel=Spike%20mutations&c=gt-S_346,503,812&label=nuc%20mutations:G22599A

**Genomes**:
[AY.33+R346K.csv](https://github.com/cov-lineages/pango-designation/files/7876452/AY.33%2BR346K.csv)

**Comment by FedeGueli** [comment]
It is growing in comparison to all delta sublineages baseline (europe)
![chrome_screenshot_1642326551167](https://user-images.githubusercontent.com/87669813/149654996-6c3b9dbd-8351-43bb-b4a0-01cd3b365553.png)

**Comment by FedeGueli** [comment]
It seems to have a substantial  growth rate advantage on AY.4.2* all sublineages baseline:
14%.
![Schermata 2022-01-26 alle 12 50 11](https://user-images.githubusercontent.com/87669813/151158401-ac266f02-59c0-4805-b124-4a741bd876da.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage AY.33.2 with 598 newly designated sequences, and 3 updated designations. Defining mutation(s) S:R346K, ORF3a:Y107S, ORF3a:N119Y.
