### ISSUE TITLE
Proposal to broaden AY.127.1 definition to S:T859N and to designate AY.127.2 with T25518C and AY.127.3 with ORF8:G8E

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#404]
@bitbyte2015 pointed to me a growing sublineage of AY.127 , that is actually one of the more resistant sublineage of Delta , that accounts for 1/3 of AY.127 sequences.

I found it has been already proposed in #352 by @c19850727 but it got designated a step further in the branch starting with ORF1b:K1993R.

Given that AY.127 + S:859N then has spread broadely 
and the actual definition of AY.127 causes missassignment of sequences carrying S:859N between AY.127 and AY.127.1 i would suggest to broad AY.127.1 starting with S:859N and to rename the clade with Orf1b:K1993R AY.127.1.1 .

I updated this proposals with the analysis by @bitbyte2015 that could be found in the comments below:
So this proposals ask to:
1) Broaden AY.127.1 starting with S:T859N
2)Rename AY.127.1.1 the actual AY.127.1  with Orf1b:K1993R
3)Designate AY.127.2 starting with T25518C
4)Designate AY.127.3 starting with ORF8:G8E

This is the trend of all this sublineage compared to Baseline (Whole Delta sublineages):
![Schermata 2022-01-22 alle 12 56 02](https://user-images.githubusercontent.com/87669813/150637595-6e7c2fc5-c8e7-4e9f-a783-c45da840ed95.png)

[Covspectrum AY.127 2022](https://cov-spectrum.org/explore/Europe/AllSamples/from=2022-01-01&to=2022-01-22/variants?pangoLineage=AY.127*&aaMutations1=S%3A859N&pangoLineage1=AY.127*&pangoLineage2=AY.127.1*&nucMutations3=T25518C&pangoLineage3=AY.127*&aaMutations4=ORF8%3AG8E&pangoLineage4=AY.127*&pangoLineage5=AY.127)

It is interesting to note that AY.127 showed still growing proportion in absolute numbers in Poland in the first two weeks of the year:
![VariantTimeDistributionChart (3)](https://user-images.githubusercontent.com/87669813/150637704-ca91af44-e093-4582-b938-43410ac051cc.png)

@AngieHinrichs @chrisruis @corneliusroemer It would be of great importance to designate these clades cause it was AY.127 found in hamsters by Hong Kong public health authorities :
[Professor Yuen Kwok-yung:](https://www.hk01.com/%E7%A4%BE%E6%9C%83%E6%96%B0%E8%81%9E/726686/%E8%A2%81%E5%9C%8B%E5%8B%87%E8%A7%A3%E6%A7%8B%E8%AA%8D%E5%90%8C%E6%AE%BA%E5%80%89%E9%BC%A0%E4%BB%A4-delta%E7%97%85%E6%AF%92%E5%A4%9A%E4%B8%80%E7%AA%81%E8%AE%8A-%E4%B8%8D%E9%98%BB%E6%81%90%E6%88%90%E4%B8%96%E7%95%8C%E7%81%BD%E9%9B%A3)

Mentioning:
> And here are the sequences for AY.127.3 (n=1411): [contributors(3).csv](https://github.com/cov-lineages/pango-designation/files/7908734/contributors.3.csv)

**Comment by FedeGueli** [comment]
Sorry i corrected since covspectrum changes colours everytime you update the page:
Comparison between AY.127* (ligjt green) and the most fit sublineages (AY.4.2 blue ,AY.122 brown, AY.126 bluegreen, AY.121 , AY.43 dark green)
to Delta baseline
![chrome_screenshot_1642346992553](https://user-images.githubusercontent.com/87669813/149666552-7c84aac3-2797-42b1-8a87-86b07cf58c05.png)
![chrome_screenshot_1642346974433](https://user-images.githubusercontent.com/87669813/149666561-56608bbe-aba6-4d71-a210-5a62fd17c115.png)

**Comment by bitbyte2015** [comment]
![image](https://user-images.githubusercontent.com/36325823/150427508-6427b9e9-c72e-4984-b285-d2efc59a34f7.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_8738_9d0870.json?branchLabel=aa%20mutations&c=gt-nuc_25518,24138,27916&label=nuc%20mutations:G25538T

AY.127 appears to have split into three clear sub-lineages. AY.127.1 starting with S:T859N, AY.127.2 starting with T25518C in blue with additional ORF1ab mutations, and AY.127.3 in green starting with ORF8:G8E. AY.127.2 accounts for the vast majority of AY.127 but is declining in Europe. AY.127.3 accounts for a similar proportion of AY.127 in Europe as AY.127.1 and is also growing.

![image](https://user-images.githubusercontent.com/36325823/150428045-6cbdc9ca-2b6b-4a15-a3b2-47c374f53322.png)
Proportion of AY.127 per sublineage in Europe (black AY.127.1, green AY.127.2, blue AY.127.3)

Here are the sequences for AY.127.2 (n=13831):
[contributors(2).csv](https://github.com/cov-lineages/pango-designation/files/7908729/contributors.2.csv)


And here are the sequences for AY.127.3 (n=1411):
[contributors(3).csv](https://github.com/cov-lineages/pango-designation/files/7908734/contributors.3.csv)

**Comment by FedeGueli** [comment]
Dear @chrisruis @corneliusroemer @AngieHinrichs  after looking at the @bitbyte2015 broader analysis on AY.127 i changed the title of this issue to include his proposals of AY.127.2 and AY.127.3:

> ![image](https://user-images.githubusercontent.com/36325823/150427508-6427b9e9-c72e-4984-b285-d2efc59a34f7.png) https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_8738_9d0870.json?branchLabel=aa%20mutations&c=gt-nuc_25518,24138,27916&label=nuc%20mutations:G25538T
> 
> AY.127 appears to have split into three clear sub-lineages. AY.127.1 starting with S:T859N, AY.127.2 starting with T25518C in blue with additional ORF1ab mutations, and AY.127.3 in green starting with ORF8:G8E. AY.127.2 accounts for the vast majority of AY.127 but is declining in Europe. AY.127.3 accounts for a similar proportion of AY.127 in Europe as AY.127.1 and is also growing.
> 
> ![image](https://user-images.githubusercontent.com/36325823/150428045-6cbdc9ca-2b6b-4a15-a3b2-47c374f53322.png) Proportion of AY.127 per sublineage in Europe (black AY.127.1, green AY.127.2, blue AY.127.3)
> 
> Here are the sequences for AY.127.2 (n=13831): [contributors(2).csv](https://github.com/cov-lineages/pango-designation/files/7908729/contributors.2.csv)
> 
> And here are the sequences for AY.127.3 (n=1411): [contributors(3).csv](https://github.com/cov-lineages/pango-designation/files/7908734/contributors.3.csv)

**Comment by FedeGueli** [comment]
AY.127+S:859N seems to be more transmissible than AY.4.2* all sublineages baseline:
Growth rate advantage 8%:
![Schermata 2022-01-26 alle 12 43 47](https://user-images.githubusercontent.com/87669813/151157667-47025a4a-94a4-4233-bf49-e93c4d9d2547.png)

cc @corneliusroemer @chrisruis @AngieHinrichs

**Comment by FedeGueli** [comment]
None of these sublineages are still circulating. I close this one
