### ISSUE TITLE
Recent circulation of multiple sublineages of B.1.466.2 in Jakarta,Indonesia

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#405]
During the month of December 16 new sequences of B.1.466.2 have been sampled in Jakarta and West Java,  clustering each one with different pre-delta  Spring-Summer 2021 sequences.
In week 49-50-51 they represents between 1,5% and 2,5% of total sequences in Indonesia.
Obviously is too early to designate but i put them here to enable monitoring of them.

Lineage 1
EPI_ISL_8383532 
with 
Orf1a:F3644L
S:S1252F, ORF7b:D36G

Lineage 2
EPI_ISL_8383533, EPI_ISL_8383531
with
N:A35V
then 
ORF1a:Q1021H, M3087I, ORF7b:S5L
then 
Nuc:2740C
then 
ORF1b:D2429G, S:T859I
then  
S:A688S

Lineage 3
with
E: R61C
(EPI_ISL_8120473 adds:
ORF1a:V2149F, ORF1a:I3693V, ORF1a:E102K, Orf1a:A2355S, Orf1a:K3573E, Orf1b:A975V, Orf1b:A2431V
S: L249S, A475V, E484A, T572N, M: I82T, ORF6: I11T, ORF7a: A105V)
(EPI_ISL_8383540 adds: Orf1a:T4207I, ORF1a:K3353R, Orf1B:V1170F, ORF1a:M2374I, ORF8:W45L)
(EPI_ISL_8383553 adds: Orf1a:T4207I, ORF1a:A1352V, ORF1a:T4065I, S:L176F, ORF3a:T64I, 0RF3a:R122K)

Lineage 4
EPI_ISL_8383538, EPI_ISL_8383536, EPI_ISL_8383539
with
nuc: G17667A, C20703T
then 
nuc: T18843C
then 
nuc: G174C, ORF6:T21A
then
nuc: T10933C, ORF1b: M1596I, Orf1: G1772V

Lineage 5:
EPI_ISL_8131154
with :
Orf1b: M2667V
then
Orf1a:A4394T
then
ORF1a:S166G, G519S, A1679V, S2242F, T3082I, L3829F, Orf1b:D2090Y
S: T22I, N354D
M: I76V

[Usher Tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_4ef9_4893d0.json?branchLabel=aa%20mutations&label=nuc%20mutations:T2740C,G3328T,A8519G,G9526C,C18555T,A20753G,G23624T,C24138T,C27769T,C28377T&tl=pango_lineage_usher)
![Schermata 2022-01-16 alle 23 58 24](https://user-images.githubusercontent.com/87669813/149681700-f59d17cf-b67c-414a-8411-ed512bb2890b.png)

In the Jakarta metropolitan area these sequences represents around 10% in the last two weeks of December:
![EstimatedCasesPlot](https://user-images.githubusercontent.com/87669813/149681649-f061bb6f-756c-4b58-8dd0-aa525724e1e4.png)

**Comment by MC240596** [comment]
I hope this isn't the next bad mutant

**Comment by FedeGueli** [comment]
@MC240596 i put this here just fo monitor it, no reason to alarm or worries about it. Usually vocs have been anticipated by a raise in cases then linked to a variant. This is NOT the case.

**Comment by AngieHinrichs** [comment]
Most of these sequences have very few differences with Indonesian sequences deposited in May or June 2021... I wonder if the December sample collection dates are correct.

Lineage 1: Indonesia/JK-GS-FKUINIHRD-0293/2021|EPI_ISL_8383532|2021-12-25 seems to have the same mutations as Indonesia/KR-GS-FKUINIHRD-0089/2021|EPI_ISL_6959830|2021-06-05:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-405.lin1.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A6015G,C12439T

Lineage 2: very similar to sequences from 2021-06-05 that already had S:T859I and S:A688S
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-405.lin2.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A20753G,C24138T

Lineage 3: Indonesia/JB-GS-WJHL-ITB-A112/2021|EPI_ISL_8120473|2021-12-06 has 15 private mutations relative to its most likely common ancestor with earlier sequences.  The other two sequences are less diverged relative to samples from April/May/June.
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-405.lin3.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C26425T

Lineage 4: Three mutations relative to common ancestor with sequences from May/June:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-405.lin4.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G17667A,C20703T

Lineage 5: Indonesia/JK-GS-GSILab-843004/2021|EPI_ISL_8131154|2021-12-20 has 27 private mutations relative to its most likely common ancestor with earlier sequences.
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-405.lin5.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A21466G,G28321A

**Comment by FedeGueli** [comment]
thx @AngieHinrichs , @c19270785 pointed that to me too. 
Tough i think it is worth monitoring especially the most divergent ones. I put everything to describe the landscape in the best possible way.
Obviously if nothing more will emerge i'll close this issue.

**Comment by FedeGueli** [comment]
@thomaspeacock pointed to me that two more B.1.644.2 sequences popped up in indonesua

EPI_ISL_9702285
EPI_ISL_9242265

**Comment by FedeGueli** [comment]
Two more B.1.466.2 sequences popped up in february.
EPI_ISL_10724195
EPI_ISL_10724194

It looks like that neither the january ones nor the february ones clusters with the ones described in this issue.
I dont know if such diversity come from sequencing issues (last 4 have been sequenced by 3 different labs) or fron low level circulation in different area of Indonesia ( last 4 seqs come from  3 different areas of the country)
@corneliusroemer 

credits for these seqs @thomaspeacock

**Comment by cinswasti** [comment]
> It looks like that neither the january ones nor the february ones cluster with the ones described in this issue. I dont know if such diversity comes from sequencing issues (last 4 have been sequenced by 3 different labs) or from low level circulation in different area of Indonesia ( last 4 seqs come from 3 different areas of the country) @corneliusroemer

@FedeGueli Thank you for flagging this, so we can monitor it as you said. 
The last 3 were actually sequenced by the same lab (NIHRD), but samples originated from different labs/hospital. These 3 sequences also ones with additional warning/comments in their sequencing metadata. 

On the dozen or so came up in December, we are trying to lyase with submitting labs to recheck the collection dates as @AngieHinrichs suggested.

**Comment by cinswasti** [comment]
Hi @chrisruis, I'm afraid not yet. We are still liaising with the institutions to get permission to carry out data check. 
The monitor label would be the best thing for now. Will keep this updated.

**Comment by FedeGueli** [comment]
one more B.1.466.2 from March 2022 , Lampung region: EPI_ISL_12089943 with S:E484A and F490V 
Please @cinswasti could you take a look at it?

**Comment by chrisruis** [comment]
Hi @cinswasti Did you have any luck getting the collection dates for these sequences?

**Comment by chrisruis** [comment]
I can only see 1 sequence with a collection date since the start of April 2022. It's possible that this is still circulating but will close for now and can reopen if more sequences appear

**Comment by FedeGueli** [comment]
Agree. No news from Indonesia. We will see in the next months if that diversity is still circulating.
