### ISSUE TITLE
Results only show covid lineage "B" 

### ISSUE THREAD

**Issue by el239** [cov-lineages/pango-designation#408]
Hi, like the title says, Pangolin only returns the most general "B" designation for SARS-CoV-2 samples, whether run in the browser, an anaconda environment, or part of Nextflow's viral-recon pipeline. I have plenty of coverage going into the assemblies, so don't think that's the problem. I'm grateful for any ideas as to acquiring more specific classifications. Thanks!

**Comment by aretchless** [comment]
Hi. That is a legitimate result. Why do you think these sequences should give different results? Are you seeing a lot of Bs?

**Comment by corneliusroemer** [comment]
Please provide a few sample sequence fastas to allow us to reproduce.

As the previous commenter said, by itself, B is a legitimate result.

**Comment by el239** [comment]
Ah, I believe I found the issue with my files; they were assembled with bcftools via a metagenomic pipeline. In this case, I knew the lineages should match the GISAID assemblies I'm replicating. Nevertheless, I appreciate the prompt assistance!
