### ISSUE TITLE
New Omicron (BA.1) sub-lineage exponentially growing in Campania, Italy

### ISSUE THREAD

**Issue by agrimaldi93** [cov-lineages/pango-designation#409]
### By
Antonio Grimaldi, Telethon Institute of Genetics and Medicine, Armenise/Harvard Laboratory of Integrative Genomics, Davide Cacchiarelli's Group. Naples, Italy.

### Description
We report a new potential **BA.1** sublineage s**pecifically located in Campania, Italy.** It was identified because its frequency is rapidly growing in Campania, particularly near Naples. In the first weeks of 2022 the proposed new lineage represented over the 30% of all the sequences identified in the region.

### List of genomes:
[GISAID_hcov-19_ids_2022_01_20_16_29.csv](https://github.com/cov-lineages/pango-designation/files/7906901/GISAID_hcov-19_ids_2022_01_20_16_29.csv)

**Sublineage of**: BA.1

### Countries circulating: 
To date about ~121 samples have been identified in the world, almost all located in Italy. A couple of sequences also in Czech Republic and England.

Earliest date: 2021-12-14
Most recent date: 2022-01-13

### List of Genomes:
[GISAID_hcov-19_ids_2022_01_20_16_29.csv](https://github.com/cov-lineages/pango-designation/files/7906921/GISAID_hcov-19_ids_2022_01_20_16_29.csv)

### Defining SNPs:
Ns7b E3 STOP
NSP12 L749M

### Evidences:
Here is the phylogenetic consensus maximum likelihood tree. The suggested lineage highlighted in dark blue.
![FullTree](https://user-images.githubusercontent.com/53193948/150381662-d2ce4259-b89c-4db0-af2b-1b7b5db3b082.png)
The following is a zoom in the proposed new lineage. Red numbers indicates UltraFast bootstrapping values. 
![image](https://user-images.githubusercontent.com/53193948/150381821-4652d3ae-25ff-4353-accb-c6b73037d098.png)

The tree were obtained by using  iqtree. 1000 UFbootstrapping cycles were performed.
Sequences list (below) included: sequences from the proposed lineage,  a random selection ~2000 sequences and ~1000 random sampled BA.1 sequences from GISAID.
[deli.txt](https://github.com/cov-lineages/pango-designation/files/7906947/deli.txt)

The following plot shows the 2 main defining mutations and the frequency of the proposed lineage:

![image](https://user-images.githubusercontent.com/53193948/150379042-167b5e69-46b1-4126-9578-98834b6c5d98.png)

**Comment by theosanderson** [comment]
>NSP12 L749M

ORF1b:L740M / ORF1ab:L5141M for those on those coordinate systems https://cov-spectrum.org/explore/Italy/AllSamples/Past3M/variants?variantQuery=BA*&variantQuery1=BA*+%26+ORF1b%3AL740M&analysisMode=CompareEquals

**Comment by corneliusroemer** [comment]
Thanks @theosanderson 

Doesn't look like that much growth to me, this is share of all Omicron in Italy:
![image](https://user-images.githubusercontent.com/25161793/150396301-896340ea-b0b4-4f16-b9fd-4edb1d073835.png)

I remember `ORF7b:E3*` being in early Omicron diversity. It was very common in Norway beginning of December, present at that super spreading party. Been going down since.

![image](https://user-images.githubusercontent.com/25161793/150396631-a3f5d9f3-dda4-4124-b873-4e2368f7fbcc.png)

https://cov-spectrum.org/explore/Norway/AllSamples/from=2021-11-11&to=2022-01-20/variants?variantQuery=BA*&variantQuery1=BA*+%26+ORF7b%3AE3*&analysisMode=CompareToBaseline

Maybe that could become a sublineage. I'm not sure about that extra mutation `ORF1b:L740M`

**Comment by FedeGueli** [comment]
It seems trending up in Campania:
![VariantTimeDistributionChart](https://user-images.githubusercontent.com/87669813/150414722-70aab0a8-80f0-4b9a-913a-eea7d5e9c954.png)

And Emilia Romagna
![VariantTimeDistributionChart (1)](https://user-images.githubusercontent.com/87669813/150414914-d84c892d-45f7-466f-b25c-efbf26a2cd8e.png)


The subclade that is driving the source is with Orf1a:3676S:
![Schermata 2022-01-20 alle 21 21 51](https://user-images.githubusercontent.com/87669813/150416962-e1a3bc22-09b0-4172-86a6-043b309452a7.png)
Tree:
![Schermata 2022-01-20 alle 21 29 33](https://user-images.githubusercontent.com/87669813/150417214-01515778-e52e-42b1-b569-3e255bd95740.png)

**Comment by FedeGueli** [comment]
It seems trending up in Lazio  too:
![VariantTimeDistributionChart (31)](https://user-images.githubusercontent.com/87669813/150701902-d10b8bc6-ded3-4586-88bd-a35f07762b8f.png)

[CovSpectrum](https://cov-spectrum.org/explore/Italy/AllSamples/from=2021-11-11&to=2022-01-20/variants?aaMutations=orf1b%3A740M%2COrf7B%3AE3*&pangoLineage=BA.1*) 

It seems to be more internationally distributed now:

Germany | 4 | 2021-52 | 2022-02
United Kingdom | 6 | 2021-52 | 2022-02
Sweden | 9 | 2021-51 | 2021-52
Italy | 100 | 2021-50 | 2022-03
Czechia | 1 | 2022-01 | 2022-01
Spain | 1 | 2021-52 | 2021-52
Netherlands | 1 | 2022-02 | 2022-02
Israel | 1 | 2021-51 | 2021-51
Belgium | 1 | 2022-02 | 2022-02
Romania | 1 | 2021-52 | 2021-52


@corneliusroemer It seems something to keep an eye on.

**Comment by agrimaldi93** [comment]
GISAID just released the results of the epidemiological surveillance we perform each month. We detected further **35** sequences in Campania (collection date:   2022-01-09 ~ 2022-01-17).
[GISAID_hcov-19_ids_2022_01_25_15_19.csv](https://github.com/cov-lineages/pango-designation/files/7934764/GISAID_hcov-19_ids_2022_01_25_15_19.csv)
The total number of sequences on GISAID are now **175**, distributed as follows:
 Italy--------------146 (122 in Campania)
 Israel---------------1
 Sweden------------9
 Spain--------------1
 Germany----------4
 Czech Republic---1
 United Kingdom -7
 Romania----------1
 Belgium-----------1
 Netherlands------1
 Denmark----------2
 USA---------------1

More details here:
[gisaid_hcov-19_2022_01_25_15.txt](https://github.com/cov-lineages/pango-designation/files/7934882/gisaid_hcov-19_2022_01_25_15.txt)

**Comment by agrimaldi93** [comment]
**Update**
The sequences of the proposed lineage are now 277 worldwide:
Italy			221
Israel		1
Sweden		9
Spain		1
Germany		19
Czech Republic	1
United Kingdom	15
Romania		1
Belgium		1
Netherlands	1
Denmark		2
USA			1
Switzerland	2
Croatia		2

Here more detailes:
[gisaid_hcov-19_2022_02_04_10.txt](https://github.com/cov-lineages/pango-designation/files/8002489/gisaid_hcov-19_2022_02_04_10.txt)

**Comment by agrimaldi93** [comment]
**Update**
The sequences of the proposed lineage are now 412 worldwide, with the highest number in Campania, Italy:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/A28BA~1.GRI/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/A28BA~1.GRI/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Country | Number
-- | --
Germany | 36
Ireland | 1
Netherlands | 2
Italy | 311 (235 in Campania)
Israel | 1
Sweden | 10
Spain | 2
Czech Republic | 2
United Kingdom | 21
Romania | 1
Belgium | 2
Denmark | 4
USA | 2
Switzerland | 7
Croatia | 4
Slovakia | 3
France | 2
Poland | 1



</body>

</html>

Furthermore, sequences belonging to this cluster represented over **15%** of all the samples sequenced in Campania in January 2022. We will produce the results for the surveillance of February in Campania next week.
Please find more details (Gisaid EPI_ISLs and Collection dates) in the attachment.

[gisaid_hcov-19_2022_02_18_09.txt](https://github.com/cov-lineages/pango-designation/files/8095863/gisaid_hcov-19_2022_02_18_09.txt)

**Comment by FedeGueli** [comment]
@agrimaldi93 it seems now having a relative growth disadvantage vs BA.1*(all sublineages) baseline probabky due the increasing share of BA.1.1 circulating in Italy.
![Screenshot_2022-02-18-12-39-01-058_com android chrome](https://user-images.githubusercontent.com/87669813/154680751-7b648010-6c39-4a65-9594-af47ffb43e59.jpg)
Even if it conserves modest advantage on original BA.1 around 1%
 it has still a 50+% relative growth disadvantage vs BA.2.
So its further spread seems uncertain

Have you managed to work with Cotugno hospital to check if this variant is associated with more severity?
Asking that cause Cotugno is an excellence in infectious disease and tgis sublineage is very concentrated in the same area.
Data on sublineages' severity would be of great help.

**Comment by agrimaldi93** [comment]
@FedeGueli Thanks for the suggestion!
Actually we are currently collaborating with Cotugno, since we are receiving samples also from them,  I will for sure ask them to know about the severity.
The data from cov-spectrum are certainly interesting, however the variant is mostly localized in Campania, and we have not published any sequence collected in February yet.
Anyway, yes, I do not think it may have any advantage over the BA.2 .
I will take you updated.
Thanks again.

**Comment by FedeGueli** [comment]
Great to hear! thank you! i ll monitor it on covspectrum when new seqs will be uploaded!

**Comment by agrimaldi93** [comment]
Update.
During february  the proposed lineage was still present in Campania. Indeed, it represented the 13% of overall sequences produced in the region.
Here is the worldwide spread of the variant:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/A28BA~1.GRI/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/A28BA~1.GRI/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Nation | Number
-- | --
Italy (Campania) | 141 (122)
Germany | 22
United Kingdom | 12
Switzerland | 4
USA | 2
Norway | 2
Slovakia | 2
Ireland | 1
Poland | 1
Czech Republic | 1
Belgium | 1



</body>

</html>

For the month of March we have just the data collected on 2022-03-06 and -07. In this case the variant accounted for the 4% of all sequences.

**Comment by FedeGueli** [comment]
Hi @chrisruis this lineage reached 637 sequences mostly from Italy that is not a high sequencing frequency country, but it spread to other countries in the last weeks too(<iframe src="https://cov-spectrum.org/embed/VariantInternationalComparisonChart?json=%7B%22variantSelector%22%3A%7B%22location%22%3A%7B%7D%2C%22dateRange%22%3A%7B%22mode%22%3A%22Past3M%22%7D%2C%22variant%22%3A%7B%22aaMutations%22%3A%5B%22Orf1b%3A740M%22%2C%22Orf7b%3AE3*%22%5D%7D%2C%22samplingStrategy%22%3A%22AllSamples%22%7D%2C%22countries%22%3A%5B%5D%2C%22logScale%22%3Afalse%7D&sharedWidgetJson=%7B%22originalPageUrl%22%3A%22https%3A%2F%2Fcov-spectrum.org%2Fexplore%2FWorld%2FAllSamples%2FPast3M%2Fvariants%2Finternational-comparison%3FaaMutations%3DOrf1b%253A740M%252COrf7b%253AE3*%22%7D" width="800" height="500" frameborder="0"></iframe>)
I think it is worth to be designated also to track eventually recombination during the ongoing BA.2 exponential outbreak in Italy or elsewhere.
As said by @corneliusroemer for #474 and #475 the designation of these last undesignated BA.1 will complete the picture of this lineage.

**Comment by chrisruis** [comment]
Thanks @agrimaldi93 I agree that this clade warrants a designation. We've added this as BA.1.21.1 in [v1.4]

**Comment by FedeGueli** [comment]
Please @agrimaldi93 we have urgent need to get in touch with you (see #1970 ) Could you comment there please? there is what seems an highly mutated BA.1 second generation with 19 non synonymous mutations that has beem sequenced by your team. If you can get in touch with @ryhisner (also on twitter @longdeserttrain)
Se vuoi parlare con me scrivimi a fedegu@gmail.com . grazie.
