### ISSUE TITLE
Proposal for lineage in B.1 India (Maharashtra) L452R E484Q P681R

### ISSUE THREAD

**Issue by babarlelephant** [cov-lineages/pango-designation#41]
Hi, well-supported lineage, good diversity, 25 SNP, 15% of the 2021 Indian sequences

`
​ EPI_ISL_1164354 Singapore 2021-02-26 B.1
​ EPI_ISL_1246284 United Kingdom 2021-02-22 B.1
​ EPI_ISL_1246268 United Kingdom 2021-02-22 B.1
​ EPI_ISL_1257024 United Kingdom 2021-03-04 B.1
​ EPI_ISL_1256972 United Kingdom 2021-03-02 B.1
​ EPI_ISL_1264032 United Kingdom 2021-03-04 B.1
​ EPI_ISL_1284652 Germany 2021-03-01 B.1
​ EPI_ISL_1294622 United Kingdom 2021-03-06 B.1
​ EPI_ISL_1293047 Australia 2021-03-16 B.1
​ EPI_ISL_1315322 New Zealand 2021-03-09 B.1
​ EPI_ISL_1315998 United Kingdom 2021-03-07 B.1
​ EPI_ISL_1316100 United Kingdom 2021-03-07 B.1
​ EPI_ISL_1316002 United Kingdom 2021-03-07 B.1
​ EPI_ISL_1329279 United Kingdom 2021-03-10 B.1
​ EPI_ISL_1329653 United Kingdom 2021-03-11 B.1
​ EPI_ISL_1330057 United Kingdom 2021-03-04 B.1
​ EPI_ISL_1332722 United Kingdom 2021-03-09 B.1
​ EPI_ISL_1326666 United Kingdom 2021-03-13 B.1
​ EPI_ISL_1327290 United Kingdom 2021-03-09 B.1
​ EPI_ISL_1327318 United Kingdom 2021-03-11 B.1
​ EPI_ISL_1327458 United Kingdom 2021-03-10 B.1
​ EPI_ISL_1327609 United Kingdom 2021-03-12 B.1
​ EPI_ISL_1327362 United Kingdom 2021-03-10 B.1
​ EPI_ISL_1327494 United Kingdom 2021-03-12 B.1
​ EPI_ISL_1335059 Canada 2021-03-01 B.1
​ EPI_ISL_1341986 United Kingdom 2021-03-17 B.1
​ EPI_ISL_1344560 United Kingdom 2021-03-15 B.1
​ EPI_ISL_1357691 India 2021-02-20 B.1
​ EPI_ISL_1357692 India 2021-02-20 B.1
​ EPI_ISL_1357695 India 2021-03-11 B.1
​ EPI_ISL_1357696 India 2021-03-11 B.1
​ EPI_ISL_1357697 India 2021-03-11 B.1
​ EPI_ISL_1357698 India 2021-03-13 B.1
​ EPI_ISL_1357699 India 2021-03-12 B.1
​ EPI_ISL_1357700 India 2021-03-12 B.1
​ EPI_ISL_1357701 India 2021-03-13 B.1
​ EPI_ISL_1357702 India 2021-03-13 B.1
​ EPI_ISL_1357703 India 2021-03-07 B.1
​ EPI_ISL_1357704 India 2021-02-08 B.1.1
​ EPI_ISL_1357705 India 2021-03-05 B.1
​ EPI_ISL_1357706 India 2021-03-09 B.1
​ EPI_ISL_1360304 India 2020-12-05 B.1
​ EPI_ISL_1360306 India 2020-12-07 B.1
​ EPI_ISL_1360316 India 2020-12-17 B.1
​ EPI_ISL_1360317 India 2020-12-18 B.1.530
​ EPI_ISL_1360318 India 2020-12-19 B.1
​ EPI_ISL_1360328 India 2021-01-05 B.1
​ EPI_ISL_1360329 India 2021-01-06 B.1
​ EPI_ISL_1360330 India 2021-01-07 B.1
​ EPI_ISL_1360338 India 2021-01-15 B.1
​ EPI_ISL_1360341 India 2021-01-18 B.1
​ EPI_ISL_1360342 India 2021-01-19 B.1
​ EPI_ISL_1360352 India 2021-01-30 B.1
​ EPI_ISL_1360359 India 2021-02-08 B.1
​ EPI_ISL_1360361 India 2021-02-10 B.1
​ EPI_ISL_1360363 India 2021-02-12 B.1
​ EPI_ISL_1360364 India 2021-02-13 B.1
​ EPI_ISL_1360370 India 2021-02-19 B.1
​ EPI_ISL_1360371 India 2021-02-20 B.1
​ EPI_ISL_1360375 India 2021-02-24 B.1
​ EPI_ISL_1360376 India 2021-02-25 B.1
​ EPI_ISL_1360382 India 2021-03-03 B.1
​ EPI_ISL_1360387 India 2021-03-08 B.1
​ EPI_ISL_1367560 Singapore 2021-03-21 B.1
​ EPI_ISL_1372093 India 2020-12-01 B.1
​ EPI_ISL_1374314 United Kingdom 2021-03-17 B.1
​ EPI_ISL_1376188 United Kingdom 2021-03-17 B.1
​ EPI_ISL_1377698 United Kingdom 2021-03-15 B.1
​ EPI_ISL_1376830 United Kingdom 2021-03-16 B.1
​ EPI_ISL_1376971 United Kingdom 2021-03-13 B.1
​ EPI_ISL_1376850 United Kingdom 2021-03-16 B.1
​ EPI_ISL_1379889 USA 2021-03-01 B.1
​ EPI_ISL_1384844 India 2021-02-14 B.1
​ EPI_ISL_1384851 India 2021-02-26 B.1
​ EPI_ISL_1384866 India 2021-02-03 B.1
​ EPI_ISL_1385821 India 2021-02-13 B.1
​ EPI_ISL_1385823 India 2021-02-12 B.1
​ EPI_ISL_1390313 United Kingdom 2021-03-16 B.1
​ EPI_ISL_1415093 India 2021-02-25 B.1
​ EPI_ISL_1415162 India 2021-01-08 B.1
​ EPI_ISL_1415164 India 2021-02-13 B.1
​ EPI_ISL_1415165 India 2021-02-16 B.1
​ EPI_ISL_1415188 India 2021-02-12 B.1
​ EPI_ISL_1415203 India 2020-10-02 B.1
​ EPI_ISL_1415208 India 2021-02-23 B.1
​ EPI_ISL_1415214 India 2021-01-09 B.1
​ EPI_ISL_1415216 India 2021-02-20 B.1
​ EPI_ISL_1415218 India 2021-02-23 B.1
​ EPI_ISL_1415225 India 2021-02-02 B.1
​ EPI_ISL_1415233 India 2021-02-16 B.1
​ EPI_ISL_1415252 India 2021-02-03 B.1
​ EPI_ISL_1415261 India 2021-02-12 B.1
​ EPI_ISL_1415262 India 2021-02-16 B.1
​ EPI_ISL_1415263 India 2021-02-13 B.1
​ EPI_ISL_1415264 India 2021-02-17 B.1
 EPI_ISL_1415265 India 2021-02-20 B.1
 EPI_ISL_1415266 India 2021-02-02 B.1
 EPI_ISL_1415267 India 2021-02-12 B.1
 EPI_ISL_1415268 India 2021-02-14 B.1
 EPI_ISL_1415269 India 2021-02-23 B.1
 EPI_ISL_1415270 India 2021-02-21 B.1
 EPI_ISL_1415271 India 2021-02-16 B.1
 EPI_ISL_1415272 India 2021-02-15 B.1
 EPI_ISL_1415273 India 2021-02-16 B.1
 EPI_ISL_1415274 India 2021-02-25 B.1
 EPI_ISL_1415275 India 2021-02-13 B.1
 EPI_ISL_1415276 India 2021-02-16 B.1
 EPI_ISL_1415277 India 2021-02-16 B.1
 EPI_ISL_1415278 India 2021-02-16 B.1
 EPI_ISL_1415287 India 2021-01-17 B.1
 EPI_ISL_1415288 India 2021-02-02 B.1
 EPI_ISL_1415289 India 2021-02-23 B.1
 EPI_ISL_1415290 India 2021-01-14 B.1
 EPI_ISL_1415291 India 2021-02-02 B.1
 EPI_ISL_1415292 India 2021-02-12 B.1
 EPI_ISL_1415294 India 2021-02-03 B.1
 EPI_ISL_1415295 India 2021-02-03 B.1
 EPI_ISL_1415296 India 2021-02-03 B.1
 EPI_ISL_1415297 India 2021-02-23 B.1
 EPI_ISL_1415298 India 2020-12-25 B.1
 EPI_ISL_1415299 India 2021-02-03 B.1
 EPI_ISL_1415300 India 2021-02-03 B.1
 EPI_ISL_1415301 India 2021-02-23 B.1
 EPI_ISL_1415302 India 2021-02-02 B.1
 EPI_ISL_1415303 India 2021-02-02 B.1
 EPI_ISL_1415304 India 2021-02-02 B.1
 EPI_ISL_1415305 India 2021-02-02 B.1
 EPI_ISL_1415306 India 2021-02-02 B.1
 EPI_ISL_1415307 India 2021-02-06 B.1
 EPI_ISL_1415308 India 2021-02-06 B.1
 EPI_ISL_1415309 India 2021-02-06 B.1
 EPI_ISL_1415310 India 2021-02-03 B.1
 EPI_ISL_1415311 India 2021-02-23 B.1
 EPI_ISL_1415312 India 2021-02-23 B.1
 EPI_ISL_1415313 India 2021-02-23 B.1
 EPI_ISL_1415314 India 2021-02-16 B.1
 EPI_ISL_1415315 India 2021-02-16 B.1
 EPI_ISL_1415316 India 2020-10-05 B.1
 EPI_ISL_1415317 India 2020-10-03 B.1
 EPI_ISL_1415318 India 2021-02-16 B.1
 EPI_ISL_1415319 India 2021-02-16 B.1
 EPI_ISL_1415320 India 2021-02-17 B.1
 EPI_ISL_1415321 India 2021-01-04 B.1
 EPI_ISL_1415322 India 2021-02-02 B.1
 EPI_ISL_1415323 India 2020-10-05 B.1
 EPI_ISL_1415324 India 2021-02-15 B.1
 EPI_ISL_1415353 India 2021-02-15 B.1
 EPI_ISL_1415356 India 2020-10-03 B.1
 EPI_ISL_1415358 India 2021-02-16 B.1
 EPI_ISL_1415359 India 2021-02-25 B.1
 EPI_ISL_1415362 India 2021-02-02 B.1
 EPI_ISL_1415370 India 2021-02-27 B.1
 EPI_ISL_1415386 India 2021-02-14 B.1
 EPI_ISL_1415387 India 2021-02-13 B.1
 EPI_ISL_1408942 United Kingdom 2021-03-21 B.1
 EPI_ISL_1413668 United Kingdom 2021-03-17 B.1
 EPI_ISL_1410266 United Kingdom 2021-03-18 B.1
 EPI_ISL_1412240 United Kingdom 2021-03-16 B.1
 EPI_ISL_1416967 Guadeloupe 2021-03-10 B.1
 EPI_ISL_1416968 Guadeloupe 2021-03-10 B.1
 EPI_ISL_1442952 Singapore 2021-03-22 B.1

`

**Comment by rambaut** [comment]
@babarlelephant Thanks for submitting anyway!
