### ISSUE TITLE
Earliest date clarification

### ISSUE THREAD

**Issue by truthcracy** [cov-lineages/pango-designation#412]
It has been noted that the earliest date for this BA.2 is recorded as 2021-01-11 https://cov-lineages.org/lineage_list.html
This has created some confusion as to the recent outbreak since januaryCould you please clarify what is this earliest date column relates to in the database.

**Comment by corneliusroemer** [comment]
Thanks for raising this. This is with almost certainty a classic hardcoded dating error, someone put 2021 instead of 2022.

**Comment by truthcracy** [comment]
Even the WHO variants page(https://www.who.int/en/activities/tracking-SARS-CoV-2-variants/) has the same error. last visit time UTC 2022-01-25 13:00
![image](https://user-images.githubusercontent.com/79820943/150981292-fe38cf0b-1a16-48db-a2bf-edfadab4f8d5.png)

**Comment by DataBeen** [comment]
"Proposal to split B.1.1.529 to incorporate a newly characterised sibling lineage #361" includes sequences from November 2021 such as "South_Africa/CERI-KRISP-K032307/2021|EPI_ISL_6795834|2021-11-17", so perhaps the typo is in the month part of the date rather than in the year part, i.e. 2021-01-11 was intended to be input as 2021-11-11.

**Comment by truthcracy** [comment]
> "Proposal to split B.1.1.529 to incorporate a newly characterised sibling lineage #361" includes sequences from November 2021 such as "South_Africa/CERI-KRISP-K032307/2021|EPI_ISL_6795834|2021-11-17", so perhaps the typo is in the month part of the date rather than in the year part, i.e. 2021-01-11 was intended to be input as 2021-11-11.

Well, it should be November

**Comment by silcn** [comment]
> "Proposal to split B.1.1.529 to incorporate a newly characterised sibling lineage #361" includes sequences from November 2021 such as "South_Africa/CERI-KRISP-K032307/2021|EPI_ISL_6795834|2021-11-17", so perhaps the typo is in the month part of the date rather than in the year part, i.e. 2021-01-11 was intended to be input as 2021-11-11.

No, what's most likely happened is that a sequence from 2022-01-11 was input as 2021-01-11, and as a result it shows up as the "earliest sequence" on GISAID when it is not.

**Comment by truthcracy** [comment]
> Even the WHO variants page(https://www.who.int/en/activities/tracking-SARS-CoV-2-variants/) has the same error. last visit time UTC 2022-01-25 13:00 ![image](https://user-images.githubusercontent.com/79820943/150981292-fe38cf0b-1a16-48db-a2bf-edfadab4f8d5.png)

who updated the site to fix the typo

**Comment by corneliusroemer** [comment]
@silcn is right, the earliest date is calculated automatically from GISAID date

**Comment by lenaschimmel** [comment]
I don't think it's worth a separate issue, but for BA.1 it even has the year 2020 🙃
![Bildschirmfoto 2022-01-26 um 00 44 35](https://user-images.githubusercontent.com/1325019/151078580-85449d0b-71d9-4958-843c-8018c1d161db.png)

**Comment by corneliusroemer** [comment]
would be good to set a minimum for what's acceptable, or use the earliest designated sample date, or clock deviation to remove outliers 😬

**Comment by rmcolq** [comment]
I have updated the website with minimum date cutoffs for omicron. These had been set previously for B.1.1.529, but the same had not been applied to sublineages
