### ISSUE TITLE
Top-level utils package causes ncov-ingest to break

### ISSUE THREAD

**Issue by jgadling** [cov-lineages/pango-designation#415]
I realize this isn't entirely the responsibility of the Pangolin team, but it's a simple fix and I believe it improves the clarity and manageability of this package, so here's the story:

[Nextstrain's tools](https://github.com/nextstrain/ncov/blob/master/docs/src/reference/change_log.md#new-features-since-last-version-update-4) and ecosystem have been integrating with Pangolin more deeply recently. It's common to need to run [ncov](https://github.com/nextstrain/ncov) and/or [ncov-ingest](https://github.com/nextstrain/ncov-ingest/) alongside a pangolin installation.

The pango-designation package [as it stands right now](https://github.com/cov-lineages/pango-designation/blob/master/setup.py#L11) installs a **top-level** module called `utils` when installed via pip. As far as I can tell the modules in this package aren't referenced by anything else in the ecosystem, and the presence of this top-level module breaks several of the tools in the `ncov-ingest` package which [has its own internal](https://github.com/nextstrain/ncov-ingest/blob/master/bin/transform-gisaid#L12) `utils` module.

I think that moving the pango-designation utils module under the pango-designation module, **or** not installing it at all will help improve interoperability with other tools, and reduce confusion about where a system-wide package called `utils` is coming from.

**Comment by corneliusroemer** [comment]
Thanks, I removed the `utils/__init__.py` so with next release this should be resolved
