### ISSUE TITLE
Possible BA.2 sub-lineage

### ISSUE THREAD

**Issue by amniewiadomska** [cov-lineages/pango-designation#417]
BA.2 branch with the following mutations:
**ORF1ab:A2909V** (nsp4:A146V) and **ORF3a:L140F**
Appears to be circulating in multiple SE Asian countries (mainly Japan and Singapore, but also Indonesia, Vietnam and Cambodia). 
73 genomes so far. See attached list.
[BA2plusORF3L140F.txt](https://github.com/cov-lineages/pango-designation/files/7944264/BA2plusORF3L140F.txt)

Below is a tree of BA.2 genomes (minus Denmark samples) highlighting this branch. 
![image](https://user-images.githubusercontent.com/64563671/151231172-52a8fa8b-dd02-44ed-8f8a-dc6305d6dbab.png)

Still relatively small numbers compared to Europe and India but may be increasing slightly in SE Asia. 
Not sure if it qualifies for a new sub-lineage but may be worth keeping an eye on.

**Comment by chrisruis** [comment]
Thanks @amniewiadomska This is the recently added BA.2.3
