### ISSUE TITLE
Proposal for a Sublineage of AY.4.2.2 with Spike S13T (~3600 Sequences, the UK)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#418]
**Description**
**Sub-lineage of**: AY.4.2.2
**Earliest sequence**: 2021/8/31 (UK-England)
**Most recent sequence**: 2021/1/17 (UK-Scotland)
**Countries circulating**: UK (mainly Scotland)

**Substitutions on top of AY.4.2.2**:
<html>
<body>

Gene | Mutations
-- | --
ORF1a | T1395A, V2857A, T4364I
ORF1b | F685Y
Spike | S13T
nuc | T8566C

</body>
</html>

**Evidence**
Down-sampled tree as per Neherlab (UK, filtered to AY.4.2.2, in yellow color):
![image](https://user-images.githubusercontent.com/86835836/151508011-9a5673c2-d4b6-4345-b5de-9ca747744f24.png)
https://nextstrain.org/groups/neherlab/ncov/united-kingdom?branchLabel=aa&c=gt-nuc_13356&label=Spike%20mutations:V1264L&p=full&r=division

Relative growth advantage as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/151508322-59f21ca2-23ea-45ab-8f98-ee06d3bc6390.png)
Comparison between **AY.4.2.2+Spike S13T** (blue line) and **AY.4.2.2** (baseline):
![image](https://user-images.githubusercontent.com/86835836/151508523-d2ce4f36-5661-4ab2-953e-3fd929bb87bc.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=AY.4.2.2*&aaMutations1=S%3AS13T&pangoLineage1=AY.4.2*&analysisMode=CompareToBaseline

Usher tree (in yellow color):
![image](https://user-images.githubusercontent.com/86835836/151508867-ae7dc9b3-9588-4d75-94e2-657f6cff03e8.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29960_368a30.json?c=gt-S_679,13&l=radial&label=nuc%20mutations:T8566C

**Genomes**:
[AY.4.2.2+S13T.csv](https://github.com/cov-lineages/pango-designation/files/7956813/AY.4.2.2%2BS13T.csv)

**Comment by c19850727** [comment]
I'm also to propose a sublineage of above proposed  **#418 (AY.4.2.2+Spike S13T)**, with ~280 sequences, mainly circulating in Scotland.

**Description**
**Sub-lineage of**: #418
**Earliest sequence**: 2021/10/6 (UK-Scotland)
**Most recent sequence**: 2021/12/28 (UK-England)
**Countries circulating**: UK (mainly Scotland)

**Substitutions on top of #418**:
<html>
<body>


Gene | Mutations
-- | --
Spike | S98F, T323I (~50%), N679I


</body>
</html>

**Evidence**

Relative growth advantage as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/151510415-56ed8191-6386-4c79-83ab-8c6adc3d6be9.png)

Comparison between**#418+Spike N679I** (black line) and #418 (baseline):
![image](https://user-images.githubusercontent.com/86835836/151510762-3f6e26d3-aa08-454a-92de-5a7fa8f2f437.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AS13T&pangoLineage=AY.4.2.2*&aaMutations1=S%3AS13T%2CS%3AN679I&pangoLineage1=AY.4.2.2*&analysisMode=CompareToBaseline

Usher tree (in blue color):
![image](https://user-images.githubusercontent.com/86835836/151510916-71eb03d6-3b12-4e68-a8fa-b61458a622f4.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29960_368a30.json?c=gt-S_679,13&l=radial&label=nuc%20mutations:T8566C

**Genomes**:
[AY.4.2.2+S13T+N679I.csv](https://github.com/cov-lineages/pango-designation/files/7956896/AY.4.2.2%2BS13T%2BN679I.csv)

**Comment by InfrPopGen** [comment]
This lineage is no longer active (not seen within past 3 months). Closing this issue for now.
