### ISSUE TITLE
Proposal for a Sublineage of AY.122 with Spike E484Q, V687I and T859N (~280 sequences, France & Switzerland)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#419]
**Description**
**Sub-lineage of**: AY.122
**Earliest sequence**: 2021/10/12 (Switzerland)
**Most recent sequence**: 2022/1/4 (Switzerland)
**Countries circulating**: mainly Switzerland and France

**Substitutions on top of AY.122**:

<html>
<body>

Gene | Mutations
-- | --
Spike | E484Q, V687I, T859N
nuc | C23854T, C26882T, G29688T

</body>
</html>

**Evidence**

Relative growth advantage as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/151514194-20710df7-7714-46e6-8341-a147ea55da97.png)

Comparison between **AY.122+E484Q+V687I+T859N**（blue line） and all lineages (baseline), as per cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/151514535-26c201f7-52e6-4152-81c4-9c8170b2c648.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations1=S%3AV687I%2CS%3AE484Q%2CS%3AT859N&pangoLineage1=AY.122*&analysisMode=CompareToBaseline

Usher tree (in orange color):
![image](https://user-images.githubusercontent.com/86835836/151514919-5742f834-56e0-47e8-9438-b306320c10c2.png)

**Genomes**:
[AY.122+V687I.csv](https://github.com/cov-lineages/pango-designation/files/7957080/AY.122%2BV687I.csv)

**Comment by chrisruis** [comment]
Thanks @c19850727 I'll close this for now as it doesn't look like this has been seen for a while
