### ISSUE TITLE
Proposal for a sublineage of AY.39.1.1 with Spike N481K and R765H circulating in Hawke's Bay Region, New Zealand (96 seqs)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#431]
**Description**
**Sub-lineage of**: AY.39.1.1
**Earliest sequence**: 2021/12/28 (New Zealand)
**Most recent sequence**: 2022/2/2 (New Zealand)
**Countries circulating**: New Zealand (predominantly in the Hawke's Bay and Wellington Region)

**Substitutions on top of AY.39.1.1**:
<html>
<body>

Gene | Mutations
-- | --
ORF1a | G1101S, T2967I
Spike | N481K, R765H
N | N140S
nuc | T18213C, C22624T, C24130T

</body>
</html>

What I proposes is actually a few step further into the tree, as it seems it's the only subclade that's still significantly growing now.

**Evidence**

Nextstrain Oceania-focused subsampling (filtered to AY.39.1.1, yellow color=branch with S:R765H and N:N140S, red color=branch with S:N481K):
![image](https://user-images.githubusercontent.com/86835836/153191695-980f43bc-9a16-4c5b-8421-8fc0e23fabce.png)

Geographical distribution as per Nextstrain (Oceania-focused subsampling):
![image](https://user-images.githubusercontent.com/86835836/153192595-b8d19bfd-e816-4616-9b6a-06fba4dd3c96.png)
https://nextstrain.org/ncov/gisaid/oceania?branchLabel=aa&c=gt-S_481,765&f_pango_lineage=AY.39.1.1

Usher tree (yellow color=AY.39.1.1, red color=branch with S:R765H and N:N140S, green color=sub-branch with S:N481K):
![image](https://user-images.githubusercontent.com/86835836/153186201-5495cb7a-95fe-4d08-a4f4-29168f6c3262.png)

Usher tree displaying country of submission (starting from the branch with S:R765H and N:N140S):
![image](https://user-images.githubusercontent.com/86835836/153186707-5e587988-d39c-4596-827c-c7ac8c3a981c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2cc7c_2a5600.json?c=gt-S_765,481

Variant comparison as per Cov-spectrum (baseline=AY.39.1.1, purple line=AY.39.1.1+S:R765H, golden line=AY.39.1.1+S:R765H+S:N481K):
![image](https://user-images.githubusercontent.com/86835836/153190039-5e7008b8-7760-4fea-8388-e08e01402757.png)

Relative growth advantage as per Cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/153190580-c7425f71-a060-4122-982b-b93ec99a535f.png)
https://cov-spectrum.org/explore/New%20Zealand/AllSamples/Past6M/variants?aaMutations=S%3AR765H%2CS%3AN481K&pangoLineage=AY.39.1.1&aaMutations1=S%3AR765H%2CS%3AN481K&pangoLineage1=AY.39.1.1

**Genomes**:
[AY.39.1.1+N481K.csv](https://github.com/cov-lineages/pango-designation/files/8032259/AY.39.1.1%2BN481K.csv)

**Comment by c19850727** [comment]
Another 20 sequences were recently uploaded, and there are 115 in total now, with the latest one being collected on Feb 9th.

The relative growth over Omicron in New Zealand now is -9% as per Cov-spectrum.

![image](https://user-images.githubusercontent.com/86835836/155457110-017cb5d0-91aa-4c13-a138-57027ade6686.png)

**Comment by FedeGueli** [comment]
@c19850727 there is a typo in your proposal: it is N:N140S not 190S

**Comment by chrisruis** [comment]
Thanks @c19850727 I'll close this for now as it doesn't look like this has been seen for a while
