### ISSUE TITLE
Delta variant AY.36 sub-lineage proposal mainly circulating in Germany

### ISSUE THREAD

**Issue by genomesurveillance** [cov-lineages/pango-designation#434]
It is necessary to designate this AY.36 sub-lineage as this sub-lineage occurred in Germany, increased quickly in Germany, and then spread to the rest of Europe, which is different from original AY.36 (dominant in Nigeria and spread to UK and a few countries in the rest of Europe),

Description
Sub-lineage of AY.36.
Earliest sequence: Germany 2021-10-04.
Most recent sequence: Current
Countries circulating: mainly in Germany, also in multiple other European countries.

In addition to AA substitutions shared with AY.36:  S: 1104L, orf1b:721R, orf1b:1538L
This sub-lineage has four additional AA substitutions: orf9b: 3S, orf3a: 223I, orf1a: 944L, N: 6L.

[country_frequency_AY36withN_P6Lupdate.xlsx](https://github.com/cov-lineages/pango-designation/files/8053937/country_frequency_AY36withN_P6Lupdate.xlsx)

Genomes(~1885)
[AY36sublineage_withN_P6L.ods](https://github.com/cov-lineages/pango-designation/files/8053939/AY36sublineage_withN_P6L.ods)

Evidence
Comparing this new AY.36 sublineage (on the top right) with AY.36, AY.20 and AY.4. Phylogney was built with earliest samples belonging to these lineages.

1. Colored by country.
![Country](https://user-images.githubusercontent.com/93262080/153718559-a6beb53e-6aed-44ac-b816-a833da4d1c96.png)

2. Displaying mutation N_P6L.
![N_P6L](https://user-images.githubusercontent.com/93262080/153718609-1c4ed5e5-a7fa-4958-8146-ba362d91587a.png)

3. Displaying mutation ORF1a_S944L.
![ORF1a_S944L](https://user-images.githubusercontent.com/93262080/153718628-4de7a29e-9451-4c16-93cb-7877623cdb86.png)

Suggested name of this AY.36 sub-lineage:AY.36.1

**Comment by genomesurveillance** [comment]
County frequency of this AY.36 sub-lineage:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 6.0.7.3 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Helvetica Neue"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>


Country | Total Variant Sequences | First seq. found at | Last seq. found at
-- | -- | -- | --
Germany | 1486 | 2021-10-04 | 2022-01-20
Denmark | 271 | 2021-10-25 | 2022-01-05
United Kingdom | 30 | 2021-10-04 | 2021-12-18
Czech Republic | 28 | 2021-10-23 | 2022-01-24
Switzerland | 14 | 2021-11-06 | 2021-12-04
Croatia | 13 | 2021-12-09 | 2021-12-29
Poland | 12 | 2021-11-24 | 2022-01-19
Italy | 5 | 2021-11-11 | 2021-12-20
France | 4 | 2021-11-22 | 2021-12-27
Netherlands | 4 | 2021-11-10 | 2021-12-16
Lithuania | 2 | 2021-12-07 | 2021-12-22
Slovenia | 3 | 2022-01-03 | 2022-01-10
Spain | 2 | 2021-11-26 | 2021-12-14
Austria | 1 | 2021-12-16 | 2021-12-16
Romania | 1 | 2021-12-14 | 2021-12-14


</body>

</html>

**Comment by genomesurveillance** [comment]
Will be great this AY.36 sub-lineage got its own name.....it is still circulating in Germany.

**Comment by corneliusroemer** [comment]
I agree, this could be designated, though with only 1.8k sequences it's not that big a lineage, so I'm on the fence.

AY.36* seems to have been as competitive as AY.4.2* in Germany which is interesting.

@chrisruis what do you think?

<img width="2320" alt="image" src="https://user-images.githubusercontent.com/25161793/155369572-f3c02a9a-91e5-4e2f-9454-ff2051670444.png">


https://cov-spectrum.org/explore/Germany/AllSamples/Past6M/variants?pangoLineage=B.1.617.2*&aaMutations1=Orf3a%3AT223I%2CN%3A6L&pangoLineage1=AY.36*&pangoLineage2=AY.36*&pangoLineage3=AY.4.2*&analysisMode=CompareToBaseline

**Comment by FedeGueli** [comment]
@corneliusroemer 3 last seqs are from 2 countries (Ger, Cz)  in february22

EPI_ISL_9963879
EPI_ISL_10007727
EPI_ISL_10012839

**Comment by FedeGueli** [comment]
Interestingly the last two seqs from germany do not cluster together confronting this [tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_131be_66e730.json?branchLabel=Spike%20mutations&label=nuc%20mutations:C27393T) to [this one](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_131be_66e730.json?branchLabel=aa%20mutations&label=nuc%20mutations:C17747T) 
The [czech](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_131be_66e730.json)  sequence clusters indepently by both german samples

**Comment by genomesurveillance** [comment]
The variant had grown very rapidly in our local samples till recently when Omicron became dominant. Indeed, it is as competitive as AY.4.2*, and the local spreading pattern is also quite special.

**Comment by chrisruis** [comment]
Thanks @genomesurveillance I agree this warrants a designation. We've added this as AY.36.1 in [v1.2.131](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.131) to start on the branch with C28290T (N:P6L)

**Comment by genomesurveillance** [comment]
I could not detect AY.36.1 with the newest release v1.2.131, also I did not find AY.36.1 in the lineages.csv file. Can you please have a check @chrisruis ?

**Comment by chrisruis** [comment]
Hi @genomesurveillance Just had a look and AY.36.1 is in the lineages.csv for [v1.2.131](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.131). Sequences won't be assigned to AY.36.1 with pangolin until there's a new run of pangoLEARN which we run every week or two. So sequences won't be assigned to AY.36.1 yet. It should appear in pangolin when the pangoLEARN release (which you can see [here](https://github.com/cov-lineages/pangoLEARN/releases)) includes v1.2.131

**Comment by genomesurveillance** [comment]
@chrisruis Thank you very much for the quick feedback!
