### ISSUE TITLE
Small Australian cluster (7 seq) of potential Delta-Omicron recombinants

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#437]
>This was first raised by @hsnguyen in issue #422. However, since that issue talks about a specific UK cluster, I'm moving the discussion here.

>For continuity, I'm reposting his two comments here.

>Posted Sunday, 13th Feb:

We've seen several sequences collected early this year in Queensland, Australia being called Omicron unassigned by Pangolin and show similar patterns: ORF1ab mutations are more like from Delta with high alternate freq. However they're far away from the aforementioned UK sequences (>20 SNPs):

- Australia/QLD5084/2022 (Illumina)
- Australia/QLD39476/2022 (ONT low qual.)
- Australia/QLD37984/2022 (Illumina)
- Australia/QLD0x00C42F/2022 (Illumina)

Not all of them are available on GISAID so here is the [FASTA](https://github.com/cov-lineages/pango-designation/files/8054962/fasta-sequences.zip) and [VCF](https://github.com/cov-lineages/pango-designation/files/8054984/vcf.zip)

A rough analysis based on scorpio haplotype of above 4 UK sequences and these 4 QLD sequences using AY.4 and BA.1 constellations:

![image](https://user-images.githubusercontent.com/7806873/153738339-30c897a7-59c6-4946-b968-bc40b685b089.png)

suggesting that there're 2 different breakpoints from 2 independent recombinant events for UK and QLD sequences.

The low number of sequences may not strong enough for new lineage atm but will keep update if situation changes.

>Posted Monday 14th of Feb:

Additional 3 sequences make it 7 for this small cluster.

- Australia/QLD0x00C580/2022
- Australia/QLD5084/2022
- Australia/QLD37717/2022
- Australia/QLD37563/2022
- Australia/QLD39476/2022
- Australia/QLD37984/2022
- Australia/QLD0x00C42F/2022

[fasta-sequences.zip](https://github.com/cov-lineages/pango-designation/files/8057307/fasta-sequences.zip)

**Comment by corneliusroemer** [comment]
Looking briefly into these 7 sequences (enough for a designation by the rules), I've noticed the following:
1. The sequences cluster very well together. 2 out of 7 sequences have a mutation `A7785G` that the other 5 don't have. Otherwise they are (up to Ns) apparently identical.
2. There are no ambiguous bases
3. ORF1ab till at least S:215 seems to be Delta 21J (no insertion), from S:339 onwards it's BA.1, breakpoint is somewhere in between.
4. The BA.1 part contains an interesting Spike mutation `S:I1081V` that appears around the world in some 3% of BA.1, but noticeably has almost not at all been spotted in Australia, raising the possibility that the recombination didn't actually happen in Australia but somewhere where `S:I1081V` is more common.
5. The sequence has a problematic frameshift in the N gene, the deletion seems to have been called incorrectly as `28362-28369` rather than `28362-28369` (that's where the Omicron deletion `N:31-33del` is). This does make me a bit sceptical about this cluster as a whole. It would be good to get a similar sequence from a different lab.
6. The Delta side is difficult to place. Nextclade puts it on a branch with AY.5.4 because it has `ORF1a: P309L` and `N:S327L`. CovSpectrum says that's pretty unique to AY.5* so I guess that's right. But again, this raises questions, because there have been 0 sequences with these two mutations in Australia recently. These mutations occured in Europe, where they made up maybe 1% of sequences in countries like the Netherlands and Poland.

So there are some strange things happening here, not quite sure what to make of it. But definitely worth monitoring. Maybe we can find some similar sequences elsewhere?

<img width="2546" alt="image" src="https://user-images.githubusercontent.com/25161793/153872958-d7dffcbb-2b03-49fe-bd4b-1a0603d63c2b.png">

<img width="1700" alt="image" src="https://user-images.githubusercontent.com/25161793/153872971-86322424-4ee3-4664-baa7-2e0e41bc2db8.png">

<img width="2258" alt="image" src="https://user-images.githubusercontent.com/25161793/153872992-152f37de-1d83-4f32-8f9c-3c6a233f83d9.png">

**Comment by hsnguyen** [comment]
Thanks @corneliusroemer for the deep diving, appreciate.
The samples were collected from different Queensland hospitals. We're trying to figure out the epi link but missing data makes it difficult at the moment. We can only confirm 2 family members among those 7. 
Omicron is now the majority in Queensland. We still observed Delta by December last year but rarely this year.
There's not yet evidence of advanced virulence/transmissibilty of this variant up until now. Will update if we find anymore useful info.

**Comment by corneliusroemer** [comment]
Thanks for the details @hsnguyen!

Can you check the pipeline re this frame shift? Why is a deleted nucleotide called as N? Is there ambiguity there? And does your definition of N include the possibility of a nt being deleted?

**Comment by hsnguyen** [comment]
Hi,
> Can you check the pipeline re this frame shift? Why is a deleted nucleotide called as N? Is there ambiguity there? And does your definition of N include the possibility of a nt being deleted?

These were the original consensus sequences generated by iVar or medaka depending on the data without curation. The deletion is called as N due to ambiguity from the alignment around the flanking bases of the deletion. I believe it's the 9nt deletion as the IGV figure below can tell. 

![IGV](https://user-images.githubusercontent.com/7806873/154177929-aba9ef57-2fc9-422a-80aa-5a3607c619ba.png)

> Also, would you be able to share the EPI_ISLs once the sequences are on GISAID? According to @c19850727 only one appears to be o GISAID and that with a different name, too.

We're uploading these sequences together with a backlog of thousand sequences, just having delays as some of the metadata fields required by GISAID are missing and hard to track from our end (e.g. originating lab).
Will update whenever they're available. Thanks.

**Comment by AngieHinrichs** [comment]
@hsnguyen Do you have EPI_ISL_ IDs for these?

**Comment by hsnguyen** [comment]
@AngieHinrichs  we managed to upload thousands of backlogs to GISAID last week but not all of them.
6/7 above sequences now available as I search the uploaded data:

```
hCoV-19/Australia/QLD5084/2021 EPI_ISL_8438332
hCoV-19/Australia/QLD39476/2022 EPI_ISL_10262189
hCoV-19/Australia/QLD37563/2022 EPI_ISL_10263151
hCoV-19/Australia/QLD37984/2022 EPI_ISL_10263152
hCoV-19/Australia/QLD37717/2022 EPI_ISL_10261577
hCoV-19/Australia/QLD0x00C580/2022 EPI_ISL_10305529
```

**Comment by corneliusroemer** [comment]
Cluster hasn't grown since, I'll close this. If anyone notices this growing, can reopen.
