### ISSUE TITLE
Proposal for Australian AY.39.1 sub-lineage with S:12F that grew rapidly until Omicron arrived (3.5k seq, peak 30%)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#438]
Investigating potential donors for the putative Delta-Omicron recombinantin #437 I noticed that S:12F grew rapidly in Australia until Omicron arrived.

First sequence: around 2021-09-15
Growth to 500 sequences per week by early December
In total ~3.5k sequences

It's a mutation that's appeared a number of times over the last 2 years. It's predicted to confer a ~1.5% daily growth advantage by @fritzo's Pyro cov model https://github.com/broadinstitute/pyro-cov/blob/a0efed3f8eb7c67f169c5d8c831af76a6f1fc7df/paper/mutations.tsv#L391

It's a well separated, fairly long branch with 4-6 mutations:
```
T26187C, T28921C (optional)
C8964T,C21597T, C23029T, C25521T
```

<img width="2265" alt="image" src="https://user-images.githubusercontent.com/25161793/153915427-373d9aed-5817-48a8-95af-744c7b863fdb.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_6dd5_a8ec10.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G27604A

Rather fast growth:
https://cov-spectrum.org/explore/Australia/AllSamples/Past6M/variants?aaMutations=S%3A12F&pangoLineage=AY.39.1*
<img width="2279" alt="image" src="https://user-images.githubusercontent.com/25161793/153915683-0c8f5670-83a7-43dc-941b-81bbac6eb5b1.png">

**Comment by FedeGueli** [comment]
22% relative growth advantage vs delta baseline: 

![Schermata 2022-02-14 alle 23 28 45](https://user-images.githubusercontent.com/87669813/153957426-f07e9ba0-1827-489a-ace9-035ab4501e95.png)

**Comment by FedeGueli** [comment]
S:12F has been described by Veesler et al 
here: https://github.com/cov-lineages/pango-designation/issues/437
![Screenshot_2022-02-16-10-27-33-272_com android chrome](https://user-images.githubusercontent.com/87669813/154238118-a8943857-0b49-4d89-b66f-61358923faab.jpg)
Luckily it doesnt seem to have the same immune escape effect as S:12P.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage AY.39.1.4 with 2945 newly designated sequences, and 1 updated designations. Defining mutation(s) C21597T (S:S12F), C23029T (synonymous).
