### ISSUE TITLE
Potential US East Coast BA.1.1/AY.119* recombinant (7 seq) [potentially the one monitored by UKHSA]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#439]
I saw that UKHSA is monitoring a potential AY.119.2/BA.1.1 recombinant. I couldn't find an issue so I tried to figure out which cluster they meant.

This was one here was noticed amongst others by @c19850727, potentially someone else before.

EPI_ISL_8720194, 8981459, 8981712, 8981824, 9088187, 9147438, 9147935

Locations: US-MA, PA, NJ, TN

First sequence: 2021-12-31

Breakpoint: between Spike NTD/RBD nuc 22199-22576

Key mutations:
```
ORF1a:A2855V (AY.119*)
ORF1a:K4176N (AY.119.2)
ORF1b:A1847S (AY.119*)
S:R346K (BA.1.1)
ORF7b:S5P (BA.1*)
```

Can be tracked via covSpectrum: https://cov-spectrum.org/explore/United%20States/AllSamples/Past6M/variants?aaMutations=S%3A346K&nucMutations=A13428G%2CG12793T

<img width="600" alt="image" src="https://user-images.githubusercontent.com/25161793/154082818-b6ccbf3d-8800-4cd7-ad8e-ae4bb60b9a33.png">

Full mutational signature:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/25161793/154082955-2225b55a-e6c9-4604-9fbd-1106b548facc.png">

**Comment by 1GHX** [comment]
Not sure, but Tom Peacock shared this, so I thought this was the UK recombinant cluster:
EPI_ISL_8610834, 8865709, 8898412, 9026013, 9062592, 9125312, 9175215, 9296739

Source:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28218_979b40.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A11201G,A11332G,G11537A,C13195T,T15240C,G15451A,C23664T

**Comment by corneliusroemer** [comment]
Here are the sequences from NCBI: https://pastebin.com/raw/zqVmTDae

And in Nextclade: https://clades.nextstrain.org/?dataset-name=sars-cov-2&input-fasta=https://api.allorigins.win/raw?url=https://pastebin.com/raw/zqVmTDae

**Comment by kristinelacek** [comment]
CDC has confirmed 9 samples belonging to this potential lineage, resulting from recombination between AY.119.2 and BA.1.1 (preprint submitted, pending).


Pangolin currently assigns lineage of "None" 

| Collection Date | State         | GISAID Accession | GISAID Virus Name                       | NCBI Accession | NCBI Name                                        | BioSample Accession |
|-----------------|---------------|------------------|-----------------------------------------|----------------|--------------------------------------------------|---------------------|
| 12/31/2021      | Tennessee     | EPI_ISL_8720194  | hCoV-19/USA/TN-CDC-ASC210559252/2021    | OM272834       | SARS-CoV-2/Human/USA/TN-CDC-ASC210559252/2021    | SAMN24974483        |
| 1/4/2022        | Pennsylvania  | EPI_ISL_8981459  | hCoV-19/USA/PA-CDC-LC0474301/2022       | OM344043       | SARS-CoV-2/Human/USA/PA-CDC-LC0474301/2022       | SAMN25170048        |
| 1/4/2022        | Pennsylvania  | EPI_ISL_8981712  | hCoV-19/USA/PA-CDC-LC0473996/2022       | OM344166       | SARS-CoV-2/Human/USA/PA-CDC-LC0473996/2022       | SAMN25170131        |
| 1/4/2022        | Pennsylvania  | EPI_ISL_8981824  | hCoV-19/USA/PA-CDC-LC0474055/2022       | OM344238       | SARS-CoV-2/Human/USA/PA-CDC-LC0474055/2022       | SAMN25170117        |
| 1/4/2022        | New Jersey    | EPI_ISL_9147438  | hCoV-19/USA/NJ-CDC-IBX952397337138/2022 | OM392955       | SARS-CoV-2/Human/USA/NJ-CDC-IBX952397337138/2022 | SAMN25262195        |
| 1/12/2022       | Massachusetts | EPI_ISL_9088187  | hCoV-19/USA/MA-CDC-STM-HZEBR92XC/2022   | OM372355       | SARS-CoV-2/Human/USA/MA-CDC-STM-HZEBR92XC/2022   | SAMN25233756        |
| 1/12/2022       | New Jersey    | EPI_ISL_9147935  | hCoV-19/USA/NJ-CDC-IBX640654818289/2022 | OM393452       | SARS-CoV-2/Human/USA/NJ-CDC-IBX640654818289/2022 | SAMN25262455        |
| 2/12/2022       | New Jersey    | EPI_ISL_10389336 | hCoV-19/USA/NJ-CDC-ASC210553977/2022    | OM835119       | SARS-CoV-2/Human/USA/NJ-CDC-ASC210553977/2022    | SAMN26256159        |
| 2/12/2022       | New Jersey    | EPI_ISL_10389339 | hCoV-19/USA/NJ-CDC-ASC210553978/2022    | OM835120       | SARS-CoV-2/Human/USA/NJ-CDC-ASC210553978/2022    | SAMN26256158        |

**Comment by chrisruis** [comment]
Thanks @corneliusroemer From what I can see, this recombinant still has only 9 or 10 genomes so will close this one for now
