### ISSUE TITLE
Proposal for a new sub-lineage of B.1 with spike substitutions N440K and E484K

### ISSUE THREAD

**Issue by nsierropmi** [cov-lineages/pango-designation#44]
**Description**
Sub-lineage of: B.1
Earliest sequence: 2021-01-16 
Most recent sequence: 2021-03-07
Countries circulating: Cameroon, Switzerland, France, Germany, England, Belgium, USA

This proposed sub-lineage was first identified in Switzerland from patients returning from Cameroon and their direct contacts. It was subsequently also detected in Cameroon, France, Germany, England, Belgium, USA.
This proposed sub-lineage is characterised by the spike protein amino acid mutations N440K and E484K in the RBD (as well as I210T, A879S, D936N, S939F and T1027I).

**Genomes**
[accessions.txt](https://github.com/cov-lineages/pango-designation/files/6272278/accessions.txt)

**Evidence**
![evidence](https://user-images.githubusercontent.com/82103880/113882796-e5814700-97bd-11eb-96ed-3b70a276f208.png)

**Comment by chrisruis** [comment]
Hi @nsierropmi thanks for submitting this, we've added this as lineage B.1.619. Its included in [v1.1.16](https://github.com/cov-lineages/pango-designation/releases/tag/v1.1.16)
