### ISSUE TITLE
Proposal to broaden AY.41 definition to ORF1b:1257V, S:1167V, ORF1b:1643V , as already proposed in #237,  plus Orf1b:K82R

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#440]
Proposal to broaden AY.41 definition to ORF1b:1257V, S:1167V, ORF1b:1643V  + Orf1B:K82R as proposed by @corneliusroemer in #237 .
This would comprise the proposed sublineage in #436 

Before trying to reconstruct the designation history of this large clade it would be better first looking at the [TREE](https://nextstrain.org/groups/neherlab/ncov/germany?branchLabel=aa&c=gt-ORF1b_1257,82,1643,218&d=tree&p=full&r=division&tl=pango_usher)
![Schermata 2022-02-15 alle 01 19 15](https://user-images.githubusercontent.com/87669813/153968903-0a15c229-1d04-4e71-841e-7739c37fb4eb.png)

In #237 @c19850727 proposed 4 sublineages.
The 4th lineage has been proposed with the following mutations:
ORF1b:A1643V,
then S:G1167V,
then G9220A,
then ORF1b:K82R,
then G7936T,
then ORF1b:I1257V,
then ORF1a:K669N,
then ORF1a:G519S and S:S477I,
then S:A262S
then ORF1b:P218S 
but it has been designating AY.41 starting with
G1820A (Orf1a:G519S) and G22992T (S:S477I) 
As @corneliusroemer immediately noted  [in this comment](https://github.com/cov-lineages/pango-designation/issues/237#issuecomment-941193212) it was too deep in the branch: in fact he identified a common branch between the newly designated AY.41 and the future AY.103, at the time still undesignated, starting with ORF1b:1257V.
Then in USA it acquired  nuc:24208T and then it has been designated AY.103 independently from #237,
instead in Croatia it acquired S:1167V, ORF1b:1643V 
then G9220A,
then ORF1b:K82R
and then, as shown [here](https://user-images.githubusercontent.com/87669813/153861845-ffd14859-2b9d-46c7-bbf7-05c2acfd35f5.png) , it has been divided in two main branch :
one designated AY.41 starting with G1820A (Orf1a:G519S) and G22992T (S:S477I) 
but comprising ORF1a:G519S, Orf1a:K669N and ORF1b:P218S too
and the other defined by nuc: G26840T then ORF3a:G18V (G25445T), Orf3a:T151I(C25844T) 
that has kept circulating till week 5-2022 in Germany and has been proposed in #436 .

![Schermata 2022-02-15 alle 01 03 55](https://user-images.githubusercontent.com/87669813/153967859-140d5b05-9c5e-4c75-852e-e1758919d373.png)

So i propose to broaden AY:41 starting with ORF1b:1257V, S:1167V, ORF1b:1643V and ORF1b:K82R
Number of sequences : 10821 
List of sequences: 
[contributors (4).csv](https://github.com/cov-lineages/pango-designation/files/8064829/contributors.4.csv)
Countries : Slovenia 2388 seqs, Croatia 2866seqs, Germany 1970 seqs , Poland 396, Switzerland 300+, Denmark 300+.

Actually this sublineage is assigned in this way: 
B.1.617.2 (43.64%)
AY.41 (32.68%)
AY.103 (13.03%)
AY.125 (4.27%)
AY.46.6 (2.03%)
AY.122 (1.33%)
AY.102 (0.44%)
AY.91 (0.41%)
AY.126 (0.31%)
AY.4.7 (0.26%)
AY.131 (0.15%)
AY.43 (0.14%)
AY.25.3 (0.12%)
AY.127 (0.12%)
AY.111 (0.09%)

So the current definition of AY.41 catches just 1/3 of the sequences belonging to the parental broader lineage.
[COV-SPECTRUM](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF1b%3A1257V%2CS%3A1167V%2CORF1b%3A1643V%2CORF1b%3AK82R&pangoLineage=B.1.617.2*&aaMutations1=ORF1B%3AK82R%2CORF3A%3AG18V%2CORF3A%3AT151I&pangoLineage1=B.1.617.2*)

cc @AngieHinrichs

**Comment by FedeGueli** [comment]
This lineage kept circulating in Germany and Slovenia through week 5/2022.
I think the broadening of AY.41 definition still makes sense , it circulated widely in western europe and made ita way to 2022.
More It is a sibling lineage of AY.103 that gave birth to some putative recombinant seqs in USA.
To track potential recombination events it will be helpful to broaden the definition also in light of masses moving from east to west due to the invasion of Ukraine 
What do you think @chrisruis ?

**Comment by FedeGueli** [comment]
@InfrPopGen I was seeing you are working on designation of past delta sublineages, if you have time to look at this. It is quite clear from the initial @corneliusroemer analysis mentioned above.
I understand that is far from important, but otherwise i ll close this issue.

**Comment by chrisruis** [comment]
I'll close this for now as AY.41 hasn't been seen much recently
