### ISSUE TITLE
Potential BA.1/BA.2 Recombinant Lineage with Likely Breakpoint at NSP3 (107 Sequences in Denmark, UK, US and Germany as of 2022/03/02)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#447]
**Description**
**Recombinant between**: BA.1 & BA.2
**Earliest sequence**: 2022/01/11 (Denmark)
**Most recent sequence**: 2022/2/14 (Denmark)
**Countries circulating**: Denmark (53 sequences)

**Likely breakpoint**: between 5927 and 6511 (NSP3).

**Conserved Nuc mutations and AA changes** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/154840691-36665cd0-1700-49bf-adae-0822b4c33756.png)

**Evidence
Nextclade downsampled tree (unrooted)**:
![image](https://user-images.githubusercontent.com/86835836/154841016-1100c5d0-9901-40f0-aa35-7888fbb76481.png)

Nextclade downsampled tree (starting from 21M):
![image](https://user-images.githubusercontent.com/86835836/154841087-6d6aac7a-2755-4f9c-9453-da60fd816b86.png)

**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/154841187-123a9f84-f648-42e0-8493-232bcabe15aa.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_210aa_1ba930.json?branchLabel=aa%20mutations&c=gt-nuc_5672&label=nuc%20mutations:T2790C,A2832G

**International comparison, geographical distribution and relative growth advantage as per Cov-spectrum**:
![image](https://user-images.githubusercontent.com/86835836/154841251-40c627df-cd8e-4cb7-b5c3-6de65671f117.png)
https://cov-spectrum.org/explore/Denmark/AllSamples/from=2021-12-15&to=2022-02-20/variants?aaMutations=ORF1a%3AK856R%2CORF1a%3AP1803S%2CORF1a%3AV1887I%2CORF1b%3AI2130V%2CORF3a%3AT223I

**Genomes**:
[Genomes Denmark 20220303.txt](https://github.com/cov-lineages/pango-designation/files/8173849/Genomes.Denmark.20220303.txt)

**Comment by KatSteinke** [comment]
Spotted that one "in the wild" today (also Region Syddanmark like the majority of sequences).

**Comment by c19850727** [comment]
A few additional sequences (as of 2022-02-27):
EPI_ISL_10095522, EPI_ISL_10095577, EPI_ISL_10203736, EPI_ISL_10203572, EPI_ISL_10203835, EPI_ISL_10216164, EPI_ISL_10209781, EPI_ISL_10209717, EPI_ISL_10258774, EPI_ISL_10260270, EPI_ISL_10252933, EPI_ISL_10201743, EPI_ISL_10259287, EPI_ISL_10259103, EPI_ISL_10318984, EPI_ISL_10349122, EPI_ISL_10349073, EPI_ISL_10350127, EPI_ISL_10350284, EPI_ISL_10353954, EPI_ISL_10353555

![image](https://user-images.githubusercontent.com/86835836/155890534-9bc7f703-6e98-4637-a7d4-4c4a5239f34b.png)
https://nextstrain.org/fetch/genome-euro.ucsc.edu/trash/ct/subtreeAuspice1_genome_euro_aef0_ba2510.json?c=gt-nuc_5672&l=radial

![image](https://user-images.githubusercontent.com/86835836/155890633-d2ecd013-f8d1-437c-92f1-2ebdc30339f4.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AK856R%2CORF1a%3AV1887I%2CORF1b%3AI2130V&nucMutations=C5672T%2CG10447A%2CC12880T&nucMutations1=C3241T%2CT5386G%2CC12880T%2CC14599T%2CC15714T%2CA20055G

**Comment by KatSteinke** [comment]
I can also add that we actually ended up sequencing one of the potential hybrid samples twice and got the same result for both runs, and it clades with the others we found in Nextstrain. Don't have the GISAID accession just yet, but can try and get it if required.

**Comment by c19850727** [comment]
Thanks @KatSteinke for the information!

**Comment by KatSteinke** [comment]
Have since gotten the GISAID accession, it's actually one of the original genomes named in the first comment: EPI_ISL_10095630.

**Comment by c19850727** [comment]
Some more sequences: EPI_ISL_10353954, EPI_ISL_10399175, EPI_ISL_10399838, EPI_ISL_10399954, EPI_ISL_10399960, EPI_ISL_10400070, EPI_ISL_10400546, EPI_ISL_10400577. Now there're 84 sequences in total.

And there's a small growth advantage relative to BA.2 in Denmark from Jan. 1st 2022, according to Cov-Spectrum:
![image](https://user-images.githubusercontent.com/86835836/156120181-c0aa3d90-f977-4ded-8977-98dbf8eb4113.png)

**Comment by c19850727** [comment]
New sequences found in England, Scotland and Germany. 
Now 102 in total.
Relative growth advantage as per cov-spectrum since Jan 1st 2022 in Denmark over BA.2 is 25%.

**Comment by c19850727** [comment]
New sequences found in England, Scotland and Germany. 
Now 102 in total.
Relative growth advantage as per cov-spectrum since Jan 1st 2022 in Denmark over BA.2 is 25%.

**Comment by corneliusroemer** [comment]
Not sure we can make much of the growth advantage at this point with so small numbers.

It is now about 1% of all sequences in Syddanmark though, that's interesting. Worth observing that region in particular to be less prone to region heterogeneity noise.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/25161793/156593285-916d73fe-bcbe-413f-90a0-314e3d86a7ed.png">

**Comment by c19850727** [comment]
107 sequences now and just popped out in US-CA.

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as XG in [v1.2.135](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.135)
