### ISSUE TITLE
Potential BA.1/BA.2 Recombinant Lineage with Likely Breakpoint at NSP5/NSP6 (43 Sequences in Denmark)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#448]
### Description
**Recombinant between**: BA.1 & BA.2
**Earliest sequence**: 2021/12/30 (Denmark)
**Most recent sequence**: 2022/2/13 (Denmark)
**Countries circulating**: Denmark (43 sequences)

**Likely breakpoint**: between 10448 and11287 (NSP5 or NSP6).
**Conserved Nuc mutations and AA changes** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/154917776-51a094ae-66c0-4c7f-8982-5d8d58e1500c.png)

**Private mutations**: ORF1a:C213R, ORF1a:G327S, Nuc T902C

### Evidence
**Nextclade downsampled tree (unrooted)**:
![image](https://user-images.githubusercontent.com/86835836/154919274-b160084c-76b0-4be8-9a25-e4f8368a1934.png)

**Nextclade downsampled tree (starting from 21M)**:
![image](https://user-images.githubusercontent.com/86835836/154919410-788a5ecf-58fe-4d2a-851d-82f1458d5f5f.png)

**International comparison, geographical distribution and relative growth advantage as per Cov-spectrum**:
![image](https://user-images.githubusercontent.com/86835836/154919667-d767f861-0228-48d5-8927-5fcc927445b6.png)
https://cov-spectrum.org/explore/Denmark/AllSamples/from=2021-12-01&to=2022-02-20/variants?aaMutations=ORF1a%3AC213R%2CORF1a%3AG327S%2CORF3a%3AH78Y&aaMutations1=ORF1a%3AC213R%2CORF1a%3AG327S%2CORF3a%3AH78Y

### Genomes:
[BA.1&BA.2 Recombi Denmark.csv](https://github.com/cov-lineages/pango-designation/files/8107702/BA.1.BA.2.Recombi.Denmark.csv)

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as XH in [v1.2.135](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.135)
