### ISSUE TITLE
Potential BA.1/BA.2 recombinant lineage in Finland [66 seq as of 2022-03-25]

### ISSUE THREAD

**Issue by teemusmura** [cov-lineages/pango-designation#449]
Eight potential BA.1/BA.2 recombinant sequences with epidemiological linkage were detected in Finland. The recombination breakpoint seems to be downstream from those reported from Denmark (issues #447 and #448 ).

Fasta file: https://ida.fairdata.fi/s/NOT_FOR_PUBLICATION_7HNL9pEXR7Dr
   
![Picture1](https://user-images.githubusercontent.com/82410439/154984783-784a1a0d-143c-4704-8cf9-508188f221a2.jpg)

 I couldn't find any obvious signals for contamination, but if anyone wants to double check the bam-files can be downloaded here:

https://ida.fairdata.fi/s/NOT_FOR_PUBLICATION_3d9sbNLZK64S

**Comment by corneliusroemer** [comment]
Interesting, thanks for sharing.

Breakpoint seems to be between nucs 13200 and 17000.

The fasta can be autoloaded into Nextclade with this link: https://clades.nextstrain.org/?dataset-name=sars-cov-2&input-fasta=https://api.allorigins.win/raw?url=https://ida.fairdata.fi/s/NOT_FOR_PUBLICATION_7HNL9pEXR7Dr/download/BA1-BA2-Finland.fas

Here's the mutation summary from an almost complete representative:

<img width="884" alt="image" src="https://user-images.githubusercontent.com/25161793/155136455-deffba23-aa65-4bb7-b8e2-c7474518411e.png">

**Comment by teemusmura** [comment]
Yes this is Kemi/Tornio region. These were omitted, because we wanted to re-sequence before submitting these - they should be in Gisaid now. There is 27945T (ORF8 Q18*) in some of the BA.2 sequences from Finland (not sure if these are in Gisaid yet).

**Comment by MCB6** [comment]
There is one more Finnish sample with the same ORF8 stop codon but it is ALSO a recombinant as far as I can tell.
hCoV-19/Finland/THL-202205928/2022
In GISAID its lineage is None (Pango v.3.1.20 2022-02-02), Omicron (Unassigned) (Scorpio) just like for the other 8. 
However there are 45 BA.2's with NS8_Q18stop, mostly from Denmark and Poland, so it's probably a recent import from outside of Finland

**Comment by c19850727** [comment]
@MCB6 I came across this one as well.
Looks like recombinant to me, except that it has a ORF1a:3675/3677DEL on the upstream BA.1 side.

**Comment by FedeGueli** [comment]
I found some BA.2 clusters with Orf8:18*  :

One in [Finland](https://cov-spectrum.org/explore/Finland/AllSamples/Past3M/variants?aaMutations=orf8%3A18*%2Corf1b%3A1315C%2Corf1a%3A3395H) 
EPI_ISL_9695160
EPI_ISL_9695162
EPI_ISL_9695070
EPI_ISL_9695071
EPI_ISL_9672781
EPI_ISL_9672782
EPI_ISL_9856601
EPI_ISL_9856642
EPI_ISL_9973230
EPI_ISL_9973225
EPI_ISL_9973212 recomb
EPI_ISL_10148532 (recomb from @MCB6 )

One in Sweden: [30 seqs](https://cov-spectrum.org/explore/Sweden/AllSamples/Past3M/variants?aaMutations=Orf8%3A18*%2COrf1a%3A3395H%2Corf1b%3A1315C) 

One in denmark: [85 seqs](https://cov-spectrum.org/explore/Denmark/AllSamples/Past3M/variants?aaMutations=orf8%3A18*%2Corf1a%3A3395H%2Corf1b%3A1315C) 

then i found
one single uk BA.1.1 seq with Orf8:18* , orf1b:1315C, orf1a:3395H, Orf1a:856R
EPI_ISL_9888549
one single BA.1.1 with Orf8:18* from Sweden
EPI_ISL_9169900

And 10seqs BA.1+orf8:18*  from [Latvia](https://cov-spectrum.org/explore/Latvia/AllSamples/Past3M/variants?aaMutations=orf8%3A18*)

**Comment by rkdover** [comment]
Not sure what ORF8:18* means, please clarify.

As for the other mutations:
- ORF1A:3395H (NSP5:P135H) is shared by BA.1/BA.2/BA.3.
- ORF1A:856R (NSP3:K38R) is BA.1 typical (and BA.1.1 typical, occurring in 97% of seqs. according to covSPECTRUM).
- ORF1B:1315C (NSP13:R392C) is interesting as it is a BA.2 mutation.

As always correct me if I'm wrong!

**Comment by corneliusroemer** [comment]
The star in ORF8:18* stands for stop codon.

**Comment by c19850727** [comment]
@teemusmura There seems to be another one: hCoV-19/Finland/THL-202205618/2022|EPI_ISL_9973212.

**Comment by c19850727** [comment]
@corneliusroemer The breakpoint might be between nucs 13196-15713 I guess?

**Comment by corneliusroemer** [comment]
This one has grown quite a bit, it's now up to 66 sequences, with a few spotted across Europe
<img width="2130" alt="image" src="https://user-images.githubusercontent.com/25161793/160025742-e3076cd7-295c-486a-8479-0414f176c7b1.png">

Sweden, UK, France, Israel

**Comment by chrisruis** [comment]
Thanks @teemusmura We've added this as XJ in [v1.2.135](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.135)
