### ISSUE TITLE
BA.1.2 to BA.1.15.1

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#450]
Looking at https://cov-lineages.org/lineage_list.html
There are 16 newly designated sublineages of BA.1:

BA.1.2	Alias of B.1.1.529.1.2, Mayotte and Reunion lineage
BA.1.3	Alias of B.1.1.529.1.3, Canada lineage
BA.1.4	Alias of B.1.1.529.1.4, France lineage
BA.1.5	Alias of B.1.1.529.1.5, UK lineage
BA.1.6	Alias of B.1.1.529.1.6, Canada and Sint Maarten lineage
BA.1.7	Alias of B.1.1.529.1.7, UK lineage
BA.1.8	Alias of B.1.1.529.1.8, European lineage
BA.1.9	Alias of B.1.1.529.1.9, Brazil lineage  (Defining mutation S:S704L, ref: [Virological.org](https://virological.org/t/the-dissemination-of-the-omicron-variant-in-the-highly-seroprevalent-amazonas-state-brazil-is-associated-with-a-rapid-upsurge-of-sars-cov-2-cases/785) )
BA.1.10	Alias of B.1.1.529.1.10, UK lineage
BA.1.11	Alias of B.1.1.529.1.11, Slovenia lineage
BA.1.12	Alias of B.1.1.529.1.12, UK lineage
BA.1.13	Alias of B.1.1.529.1.13, European lineage
BA.1.13.1	Alias of B.1.1.529.1.13.1, Indonesia lineage
BA.1.14	Alias of B.1.1.529.1.14, lineage in Brazil and other countries
BA.1.15	Alias of B.1.1.529.1.15, lineage in USA and other countries
BA.1.15.1	Alias of B.1.1.529.1.15.1, UK lineage

![chrome_screenshot_1645518581180](https://user-images.githubusercontent.com/87669813/155093262-d30b0840-fa45-4488-b754-5d89b3a124f6.png)

Hi @chrisruis will a sublineage/mutations list for BA.1 be avaible as it was avaible for AY.s (https://www.pango.network/summary-of-designated-ay-lineages/)?

**Comment by chrisruis** [comment]
Hi @FedeGueli We're currently doing a systematic identification of Omicron lineages which is still ongoing. We will do a table for the new lineages on pango.network similar to the AYs once we've got them all in there

**Comment by FedeGueli** [comment]
Thank you very much @chrisruis

**Comment by FedeGueli** [comment]
@chrisruis Are there some news on this list?
it should be important to have it both forbBA 1 and BA.2 and Xs to propose correctly sublineages not going too deep in the tree.
i know @corneliusroemer is working on proposing still undesignated sublineages, but it will be much easier to have a list without looking everytime on Usher to check if  it belongs to a designated lineage or not, and to monitor,eventually , recombinant events beside the amazing  @lenaschimmel '  SC2RF tool and Sakaguchi Hitoshi's potential recombinant sheet, (now public
: https://docs.google.com/spreadsheets/u/0/d/1cQILRxXD756gJoRsaqMdJkxZm7sEjhV7ceY398Iz7gI/htmlview#gid=0 ).

**Comment by FedeGueli** [comment]
Ahahah @chrisruis Telepathy finally got proven!

Kidding! Thank you!! wonderful news!

**Comment by FedeGueli** [comment]
Hi @chrisruis i was noticing that the omicron sublineages list isnt updated, i wish to know if it will be updated then or the team has decided not to do that and the only official list could be inferred by designations here ? Thx vm for your work.

https://www.pango.network/summary-of-designated-omicron-lineages/⁸
