### ISSUE TITLE
Proposal for a BA.1.1.x sublineage circulating in the US Mid-Atlantic region

### ISSUE THREAD

**Issue by SVN-PhD** [cov-lineages/pango-designation#452]
## **Description** 
**Sub-lineage of**: BA.1.1
**Earliest sequence**: 2021-12-03 (Canada | EPI_ISL_7738579)
**Most recent sequence**: 2022-02-15 (USA | EPI_ISL_10384113) 
**Countries circulating**: USA: Delaware, District of Columbia, Maryland, Pennsylvania, Virginia / Germany / United Kingdom / Canada / Cambodia / Vietnam
**Proposed Lineage**: Next available BA.1.1.x designations

I have been working with epidemiologists from the DMV region through the Metropolitan Washington Council of Governments (https://www.mwcog.org/). Theo Williams (theo.williams@maryland.gov) pointed out to us that there is a potential BA.1 sublineage with many sequences in Maryland and Delaware.

## Genomes
[lineages.txt](https://github.com/cov-lineages/pango-designation/files/8156095/lineages.txt)

## Additional Mutations
| Gene  | AA Changes | 
| ------------- | ------------- | 
| NSP2 | G285V | 
| NSP3 | P822S | 

These would be Orf1a: G465V and Orf1a: P1640S respectively.

## Phylogenetic Tree

Theo noticed this Maryland heavy lineage from this tree: https://nextstrain.org/community/MWCOG-COVID19/ncov/DMV?c=gt-ORF1a_465,1640&d=tree,entropy,frequencies&m=div&p=full

It appears to be associated with outbreaks in Maryland.
![Screenshot from 2022-02-28 14-27-51](https://user-images.githubusercontent.com/15314705/156046111-ab6cc626-1e71-43f8-9a83-896aba2b4605.png)

I went ahead and built a tree of these sequences, using these mutations as a marker: https://nextstrain.org/community/DC-DFS-PHL-NGS/ncov/OmicronInvestigation?c=gt-ORF1a_465,1640&d=tree,entropy,frequencies&m=div&p=full
![Screenshot from 2022-02-28 14-29-44](https://user-images.githubusercontent.com/15314705/156046369-5aed10c0-a370-4d37-bbc1-1873d7c7789e.png)

There's a heavy skew towards states in the US Mid-Atlantic region: https://nextstrain.org/community/DC-DFS-PHL-NGS/ncov/OmicronInvestigation?c=division&gt=ORF1a.1640S,465V&m=div&p=grid
![Screenshot from 2022-02-28 14-32-27](https://user-images.githubusercontent.com/15314705/156046731-16497fe8-2c98-4afb-8704-ef636f40d56a.png)

## Additional Information

https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?aaMutations=ORF1a%3AG465V%2Corf1a%3AP1640S%2CS%3AP681H
![Screenshot from 2022-02-28 14-42-25](https://user-images.githubusercontent.com/15314705/156048097-935092f2-61b6-47ae-93bd-9bfc04300678.png)

Maryland Health is currently investigating this cluster to glean more information relevant to outbreak investigations and tracebacks. A PANGO designation would be helpful.

This analysis was made possible by Theo Williams (theo.williams@maryland.gov) and Aiai Price-Smith (jsmith@mwcog.org).

**Comment by TheoWilliams-MDH** [comment]
Thank you for posting @SVN-PhD! To give a bit more regional specificity to this request, I've broken down these specimens by Maryland regions and major states.

_Stacked 100%:_
![image](https://user-images.githubusercontent.com/100643085/156077083-c474f32a-581f-450f-919d-57c22593de45.png)

_By Specimen Count:_
![image](https://user-images.githubusercontent.com/100643085/156077121-4d66022c-a23c-4245-9744-4a7926d1a6f5.png)

While this cluster began almost exclusively in the Baltimore Metro Area, it then spread to Delaware and Maryland's Eastern Shore (which borders DE), and then on to other Mid-Atlantic states. Unlike many other phylogenetic clusters, this has not spread to other regions of Maryland, indicating a very distinct epidemiological spread and not simply a random emergence of mutations.

**Comment by chrisruis** [comment]
Thanks @SVN-PhD We've added this as BA.1.1.17 to start on the branch with G1659T (Orf1ab:G465V)
