### ISSUE TITLE
Omicron-related genomes carrying mutation Spike: L452R, ORF3a: L106F and N:D343G forming a clade apart from classical Omicron

### ISSUE THREAD

**Issue by Vjimenez-vasquez** [cov-lineages/pango-designation#457]
**Description**
Uncharacterized lineage identified as “omicron” by pangolin algorithm and labelled with “ML” in GISAID apparently containing markers from Delta and Omicron variants. This clade contains three main mutations L452R, ORF3a: L106F and N:D106G and is not nested within classical BA.1 or BA.1.1.  

New possible lineage proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**Earliest sequence:** 
hCoV-19/USA/PA-VSP10158/2021 (2021/11/28, USA)
**Most recent sequence:** 
hCoV-19/USA/TN-CDC-ASC210697656/2022 (2022/01/02, USA)
**Countries circulating:** 
Canada (1), Peru(1), UK(6), USA (278), Turkey (2)
**Genomes**
[EPI_codes.txt](https://github.com/cov-lineages/pango-designation/files/8209625/EPI_codes.txt)

**Evidence**
![proposal_1](https://user-images.githubusercontent.com/89874227/157325488-39e29aa6-9b9e-4931-98cf-0373d701b7f8.png)

**Comment by FedeGueli** [comment]
Hi thank you there is a typo it is N:D343G

**Comment by Vjimenez-vasquez** [comment]
> Hi thank you there is a typo it is N:D343G

Thanks FedeGueli

**Comment by silcn** [comment]
This is not a real lineage. There is a big (genuine) sublineage of BA.1 with ORF3a:L106F and N:D343G, consisting of about 17% of all BA.1. S:L452R is a result of amplicon dropout/contamination: the apparent reversions at 417, 440 and 446 are a smoking gun.

**Comment by corneliusroemer** [comment]
Without having looked at the sequences what @silcn is a priori the most probable explanation, given we've seen this types of contaminations/coinfections a lot with Delta/Omicron.

So there needs to be good evidence from raw reads that this is not an artefact. @Vjimenez-vasquez could you have a look at the raw reads or share them here?

**Comment by Vjimenez-vasquez** [comment]
Sure @corneliusroemer !! But not for this case because I only downloaded "curious genomes" from GISAID and "clade X" only contains one genome from Peru. I have raw data for 20 Peruvian genomes highlighted in issue #458 that I can share with all

**Comment by Vjimenez-vasquez** [comment]
> Without having looked at the sequences what @silcn is a priori the most probable explanation, given we've seen this types of contaminations/coinfections a lot with Delta/Omicron.
> 
> So there needs to be good evidence from raw reads that this is not an artefact. @Vjimenez-vasquez could you have a look at the raw reads or share them here?

Sure @corneliusroemer !! But not for this case because I only downloaded "curious genomes" from GISAID and "clade X" only contains one genome from Peru. I have raw data for 20 Peruvian genomes highlighted in issue https://github.com/cov-lineages/pango-designation/issues/458 that I can share with all of you.

**Comment by chrisruis** [comment]
Will close this as has gone stale. I've only checked the earliest and most recent sequences from the initial issue but they both cluster within BA.1.15 now
