### ISSUE TITLE
Proposal of Omicron-related lineage carrying mutations Spike: L452R, M: I82T and N: R203M

### ISSUE THREAD

**Issue by Vjimenez-vasquez** [cov-lineages/pango-designation#458]
**Description**
A group of genomes identified as “omicron” (lineages BA.1 and BA.1.1) by pangolin algorithm and labelled with “ML” in GISAID apparently containing markers from Delta and Omicron variants. This genomes form a clade containing mutations Spike: L452R, M: I82T and N: R203M from Delta variant, however they appear to be closely to Omicron. 
New possible sub-lineage proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**Earliest sequence**
hCoV-19/Spain/CL-COV23576/2021(2021/12/03, Spain)

**Most recent sequence**
hCoV-19/Switzerland/BL-ETHZ-36236380/2022 (2022/02/07, Switzerland)
7/02/2022

**Countries circulating**
France (2), Indonesia (1), Peru (20), Spain (6), Switzerland (4), Turkey (1), UK (1) and USA (33)

**Genomes**
[EPI_codes.txt](https://github.com/cov-lineages/pango-designation/files/8209830/EPI_codes.txt)

**Evidence**
![peruvian_proposal](https://user-images.githubusercontent.com/89874227/157331007-d4aabb43-d6ce-4efa-9765-c9489ca6075a.png)

**Comment by silcn** [comment]
Similar comments about amplicon dropout and contamination to those in #457 apply here.

**Comment by Vjimenez-vasquez** [comment]
@corneliusroemer and @silcn I can share raw data for 20 Peruvian genomes nested within this proposed clade 


> Similar comments about amplicon dropout and contamination to those in #457 apply here.

@corneliusroemer and @silcn I can share raw data for 20 Peruvian genomes nested within this proposed clade

**Comment by Vjimenez-vasquez** [comment]
> > Similar comments about amplicon dropout and contamination to those in #457 apply here.
> 
> @corneliusroemer and @silcn. Please, find the ".bam" files in this link 
https://drive.google.com/drive/folders/1TLNn3mnjaW-EAn6ARyQ0VIKAfcvIfl4m?usp=sharing

**Comment by chrisruis** [comment]
Will close this issue as it has gone stale
