### ISSUE TITLE
Potential BA.2-BA.1 recombinant in France (2 seq)

### ISSUE THREAD

**Issue by PhilippeColson** [cov-lineages/pango-designation#459]
Dear all,
We detected in Marseille, France a hybrid genome with a Omicron BA.2 backbone but a 3' region that is approximately 3000 nucleotide-long and is a BA.1 (or 21M non BA.2) sequence, with an hybridation region comprised between nucleotides 26858-27382. We call it MixOmicron. A first genome we deposited in GISAID is EPI_ISL_10047082, and a second one has been submitted.
Best regards,
Philippe

**Comment by corneliusroemer** [comment]
I had a quick look at the available genome. Looks consistent with BA.2-BA.1 recombinant.

The BA.2 donor has nuc:11650T (which has appeared in Europe ~20 times)

The BA.1 donor part is very short.

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/25161793/157476925-3ad56a13-5746-4b85-add5-7f27428a9c53.png">

<img width="874" alt="image" src="https://user-images.githubusercontent.com/25161793/157476935-29585b50-dd00-4f3a-b4ba-3603f048b705.png">

<img width="2542" alt="image" src="https://user-images.githubusercontent.com/25161793/157476946-8dc0574a-4b5a-4721-a61c-187f63499050.png">

**Comment by PhilippeColson** [comment]
Thank you for your analysis.
The second genome is EPI_ISL_10843457.
Best regards,
Philippe

**Comment by zach-hensel** [comment]
Is it possible to not give names to variants that are not be uniquely descriptive? Much of the world has/had BA.1 and BA.2 prevalence that at the same time rivaled or exceeded prevalence for any single previous variant.

**Comment by chrisruis** [comment]
It doesn't look like this has grown significantly so will close for now
