### ISSUE TITLE
New possible sub-lineage under B.1 in West Bengal in India

### ISSUE THREAD

**Issue by banijolly** [cov-lineages/pango-designation#46]
### Description
Sub-lineage of: B.1
Earliest sequence: 2020-10-25 (EPI_ISL_1419390 , hCoV-19/India/WB-1931300236261/2021)
Most recent sequence: 2021-03-17 (EPI_ISL_1312386, hCoV-19/Singapore/275/2021)
Countries circulating: India and one sequence each from Singapore, United Kingdom 

Lineage was found to be circulating in India in the state of West Bengal in 2021. The genomes have the key mutation E484K  in spike **_without_** the presence of N501Y. 15% of genomes from West Bengal collected between Jan - March 2021 belong to this cluster. One sequence from the state of Maharashtra is also available (EPI_ISL_1419052).
The genomes also have the mutations N_G18S, N_A119S, Spike_H146del,Spike_Y145del. Other mutations common to all genomes in the cluster include NSP13_Y277C, NSP12_D269N, NS8_Q29L, NS7b_E33stop, NS3_T151I.

### Genomes
[gisaid_accessions.txt](https://github.com/cov-lineages/pango-designation/files/6299380/gisaid_accessions.txt)

### Evidence
![image](https://user-images.githubusercontent.com/47384613/114451893-6775d380-9bf5-11eb-86c3-6b6566e3f6d4.png)
![image](https://user-images.githubusercontent.com/47384613/114451766-4319f700-9bf5-11eb-9160-584118cd37fd.png)

Live nextstrain instance is available at : https://nextstrain.org/community/banijolly/Phylovis/COVID-India?c=gt-S_484,501

**Comment by chrisruis** [comment]
Hi, thanks very much for submitting this. We've added this as lineage B.1.618
