### ISSUE TITLE
Potential recombined BA.2-BA.1.1 lineage in 22 (1.4%) sequences in Roeselare, Belgium characterized by ORF1b:Q866R and ORF1a:R1628C with BA.2 background and ORF1a (2832-10029) and ORF1b (160464-18163) from BA.1.1 (ORF1b:Q866R)

### ISSUE THREAD

**Issue by geertmartens** [cov-lineages/pango-designation#460]
We observed continued transmission over a period of 4 weeks since Feb 13, 2022 (index case EPI_ISL_10892048) of an Omicron-like SARS-CoV-2 lineage with a failure to be classified by Pangolin (None (Pango v.3.1.20 2022-02-28), Omicron (Unassigned) (Scorpio)) in the region of Roeselare, Belgium. To date, we detected N=14 such sequences. 

Alignment data by Nextclade indicate that these isolates represent a background of BA.2 but with parts of ORF1a (2832-10029) and ORF1b(160464-18163)) originating from BA.1.1 (as shown by presence of ORF1b:Q866R typical for BA.1.1) recombined into the BA.2 background. There is evidence of independent clonal evolution, as shown by a unique mutation present in all independent isolates of this novel recombined strain (ORF1a:R1628C). The resulting BA.2/BA.1.1 recombined linage is thus characterized by presence of both ORF1a:R1628C (unique) and ORF1b:Q866R (derived from BA.1.1) amino acid substitutions. 

These sequences can be recognized by ‘bad overall QC’ in Nextclade, due to high number of Private mutations despite excellent horizontal/vertical coverage. 

Gisaid references:

EPI_ISL_10892048
EPI_ISL_10892049
EPI_ISL_10892050
EPI_ISL_10892051
EPI_ISL_10892052
EPI_ISL_10892053
EPI_ISL_10892054
EPI_ISL_10864854
EPI_ISL_10864857
EPI_ISL_10864858
EPI_ISL_10864920
EPI_ISL_10864921
EPI_ISL_10864925
EPI_ISL_10865165

Metadata of samples
![image](https://user-images.githubusercontent.com/93787799/157726594-d1b57642-6608-4010-81c1-5d9d74262390.png)

Phylogenetic analysis by Nextclade
The new recombinant lineage clusters with BA.2 but is characterized by a unique mutation ORF1a:R1628C

![image](https://user-images.githubusercontent.com/93787799/157726476-79560f43-6c7c-4a18-b9ea-506453127cc8.png)

Nextclade alignment of new recombinant versus BA.2, BA.1.1 and BA.1 isolates of our lab with good QC metrics

N=14 recombinant lineage without Pangolin designation (NoPango) show a poor overall QC (indicated in pink highlight). These are aligned to BA.2 (N=5), BA.1.1 (N=5) and BA.1 (N=5) analyzed in the same lab, and all showing good overall QC and acceptable to good (>500x depth, <600 missing nucleotides) using SARS-CoV-2 Research Panel (Ampliseq for Illumina, v.1) on MiSeq v2 flow cell. 
Spike of the recombinant NoPango lineages is identical to that of BA.2
![image](https://user-images.githubusercontent.com/93787799/157726674-22523c11-5dfc-41f9-8d39-6eaa4938daaa.png)

ORF1a of the recombinant NoPango lineages is identical to that of BA.1/BA.1.1 but shows a novel unique mutation in all recombinant sequences ORF1a:R1628C
![image](https://user-images.githubusercontent.com/93787799/157726725-3c5704af-1767-4d1e-9b69-92dd2146a6d8.png)

ORF1b of the recombinant NoPango lineages is identical to that of BA.1.1 with presence of ORF1b:Q866R suggesting origination from BA.1.1 rather than BA.1

![image](https://user-images.githubusercontent.com/93787799/157726765-fe3859ec-4ef1-4eb9-8328-69901aa8bd24.png)

The other genes are either not informative for BA.1/BA.2 or compatible with BA.2 suggesting that part of BA.1.1 combined into a background of BA.2

![image](https://user-images.githubusercontent.com/93787799/157726799-1906411e-9b85-4301-9eb5-c8637f38f09d.png)

As shown by the views below: 

![image](https://user-images.githubusercontent.com/93787799/157726840-46f0b6d6-5d31-4327-9c8a-8e529c290072.png)

![image](https://user-images.githubusercontent.com/93787799/157726860-b8e2dfed-3886-4f29-8fb3-679e3a268a1c.png)
![image](https://user-images.githubusercontent.com/93787799/157726882-d844b978-121d-45fa-8b2a-3db3c9a49384.png)

**Comment by geertmartens** [comment]
We identified N=2 additional such sequences on samples from March 10, 2022

EPI_ISL_11009573
EPI_ISL_11009624

At present insufficient data to indicate a survival advantage of this potential recombination

**Comment by geertmartens** [comment]
Two more such sequences in subsequent runs, indicating continued transmission. Since Feb 13, 2022 detected in 18/1235 sequences (1.4%)

EPI_ISL_11046434
EPI_ISL_11046441

**Comment by JosetteSchoenma** [comment]
I have run the EPI_ISL_10892048 sample through Lena's recombination tool, to make it easier to compare with other reombinants. The tool can be found here: https://github.com/lenaschimmel/sarscov2recombinants

![image](https://user-images.githubusercontent.com/94831035/158768807-9486e749-28a7-484e-bc27-5a39e0b800d1.png)

**Comment by JosetteSchoenma** [comment]
I have run them together with the 2 potential recombinant samples from Amsterdam from issue #472 and the breaking point looks the same.
![image](https://user-images.githubusercontent.com/94831035/158791308-8af424d4-a1ce-4f3d-ad59-387075ff3ecd.png)

This is the combined tree. 
![image](https://user-images.githubusercontent.com/94831035/158791582-3b5b1aed-c8cf-47c2-945e-3e90c34b36fe.png)

I compared them. And besides some longer stretches that seem missing in either the Belgium or the Amsterdam sequences, I see 5 different mutations. But among them are the C5147T and A16064G that are specifically mention in this issue and the C2470T that I mentioned specifically in my issue. All 3 from the alleged BA.1.1 part. (sorry, I could not manage to turn the picture)
![image](https://user-images.githubusercontent.com/94831035/158793191-b5aef6e6-ebcf-41e1-a360-811e6e5eb95f.png)

**Comment by chrisruis** [comment]
Thanks @geertmartens We've added this as XK in [v1.2.135](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.135)
