### ISSUE TITLE
BA.1.17 lineage with S:701V

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#462]
A BA.1.17 (defined by `ORF1a:1887I`) with `S:701V` seems to have a small but significant growth advantage over base BA.1.17 without the extra spike mutation.

This extra spike mutation was noticed early on in the pandemic where it made up a large chunk of all BA.1 (that was before BA.1.1 with `S:346K` became big).

It should be decided whether `S:701V` becomes a sublineage or not.

Argument for:
- Growth advantage

Against:
- When BA.1.17 spread around the world, already a large proportion (maybe 75%) already contained S:701V, so any BA.1.17 that gets picked up is already likely (but not certain) to have `S:701V`.

This question should be decided before the UK lineage in #461 get designated because that lineage there is a child of the `S:701V` branch.

Relative growth advantage of having S:701V on top of base BA.1.17 in the UK:
<img width="2132" alt="image" src="https://user-images.githubusercontent.com/25161793/157762385-4d9151dd-9cdc-4069-a34e-2a23539ad19a.png">
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?aaMutations=ORF1a%3A1887I&pangoLineage=BA.1*&aaMutations1=S%3A701V%2CORF1a%3A1887I&pangoLineage1=BA.1*&analysisMode=CompareToBaseline

**Comment by FedeGueli** [comment]
Hi @corneliusroemer i think the S:701V thing was the same of #391 .
I have closed mine cause your analysis is far more deep and describes better the ongoing context. Thx!

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as BA.1.17.2 in [v1.2.140](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.140)
