### ISSUE TITLE
Potential BA.1/BA.2 Recombinant Lineage with Likely Breakpoint at NSP3 (38 Seqs in UK as of 2022-03-16)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#464]
### Description
**Recombinant between**: BA.1* & BA.2
**Earliest sequence**: 2022/2/6 (UK-England)
**Most recent sequence**: 2022/3/16 (UK-England)
**Countries circulating**: UK-England
**Likely breakpoint**: between 6518 and 8392 (NSP3).
**Conserved Nuc mutations and AA changes** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/157914952-26b237a9-1795-4f24-98ab-eb6a4a97243e.png)

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/158754857-12e23e0e-889d-409e-82a1-195009533195.png)
https://nextstrain.org/fetch/hgw1.soe.ucsc.edu/trash/ct/subtreeAuspice1_hgw1_2ba44_2dad30.json?c=gt-nuc_875&label=nuc%20mutations:T22792C

**Cov-spectrum query**: C875T, G14229A, T5386G, A29510C
**GISAID query**: NS3_T223I, NSP2_L24F, NSP3_K38R, NSP3_L1266I, NSP3_V1069I, NSP4_T492I

### Genomes:
EPI_ISL_9839483, EPI_ISL_9839682, EPI_ISL_9872878,
EPI_ISL_9894508, EPI_ISL_10413150, EPI_ISL_10413918,
EPI_ISL_10415682, EPI_ISL_10480052, EPI_ISL_10515444,
EPI_ISL_10537883, EPI_ISL_10641197, EPI_ISL_10688213,
EPI_ISL_10734696, EPI_ISL_10736100, EPI_ISL_10797107,
EPI_ISL_10799679, EPI_ISL_10845598, EPI_ISL_10884842,
EPI_ISL_10885820, EPI_ISL_10885891, EPI_ISL_10885898,
EPI_ISL_10885929, EPI_ISL_10885983, EPI_ISL_10886013,
EPI_ISL_10886093, EPI_ISL_10924779, EPI_ISL_10924994,
EPI_ISL_10930506, EPI_ISL_10932582, EPI_ISL_10938170,
EPI_ISL_10965961, EPI_ISL_10965969, EPI_ISL_10970497,
EPI_ISL_10976194, EPI_ISL_10977401, EPI_ISL_11076474,
EPI_ISL_11092677, EPI_ISL_11092903

**Comment by theosanderson** [comment]
We were also looking at these today :)

Here is a figure I pulled together in case its useful. The putative recombinants in this case are high coverage sequences assigned "B.1.1.529" by Pango-Usher. I plot a point (colour is arbitrary) where >70% of recent UK seqs falling into the category have a non-ref allele at the position.
![image](https://user-images.githubusercontent.com/19732295/157922469-a1ffee8d-ed0a-48bd-96f5-a02a86f68837.png)

**Comment by thomasppeacock** [comment]
Just been having a look through these - all look legit to me! - only thing is I think the breakpoint might be in NSP3 rather than NSP4 as the sequences are missing the BA.1 lineage definitiong SNP G8393A (which lies at the end of NSP3) but do contain the BA.1-like NSP3 deletion just before this.

**Comment by c19850727** [comment]
Thanks @thomasppeacock !

**Comment by thomasppeacock** [comment]
Just confirming UKHSA have had a look over the raw sequences and verified this appears to be a legitimate recombinant

**Comment by nfellaby** [comment]
Just to support Tom's comment. UKHSA have identified 40 UK samples with a breakpoint at 6941 in the UK sequence data. These were identified with 3Seq (which insists a second breakpoint is annotated, this can be ignored). The other samples listed in this figure are the known lineage XE 

![20220321_breakpoint_6941_recombinant_3seq](https://user-images.githubusercontent.com/9819369/159658791-12f23d0f-1e49-4a43-94fc-800d2c060ad6.png)

Snipit analysis shows that prior to the break point all these samples predominantly match to the BA.1 reference bases, and post break point, match to the BA.2 reference.

![20220321_snipit_ref_annotated_plot](https://user-images.githubusercontent.com/9819369/159659624-80dec808-7437-4ee0-8b0c-36f9e7e0131b.png)

BAM analysis indicates there is no clear indication for contamination in these sequences, see example below for a given sample: 

![20220321_BAM_contamination_analysis_example](https://user-images.githubusercontent.com/9819369/159659143-215907a6-70c1-4177-9fd1-07724dba1b84.png)

Sample IDs from the pictures are listed here, accurate as of 2022-03-21: EPI_ISL_10413150, EPI_ISL_10413918, EPI_ISL_10415682, EPI_ISL_10480052, EPI_ISL_10515444, EPI_ISL_10525973, EPI_ISL_10532208, EPI_ISL_10535975, EPI_ISL_10537883, EPI_ISL_10578233, EPI_ISL_10641197, EPI_ISL_10688213, EPI_ISL_10734696, EPI_ISL_10736100, EPI_ISL_10797107, EPI_ISL_10799679, EPI_ISL_10845598, EPI_ISL_10884842, EPI_ISL_10885820, EPI_ISL_10885891, EPI_ISL_10885898, EPI_ISL_10885929, EPI_ISL_10885983, EPI_ISL_10886013, EPI_ISL_10886093, EPI_ISL_10924779, EPI_ISL_10924994, EPI_ISL_10930506, EPI_ISL_10932582, EPI_ISL_10938170, EPI_ISL_10965961, EPI_ISL_10965969, EPI_ISL_10970497, EPI_ISL_10976194, EPI_ISL_10977401, EPI_ISL_11223903, EPI_ISL_9839483, EPI_ISL_9839682, EPI_ISL_9872878, EPI_ISL_9894508

**Comment by c19850727** [comment]
Thanks @thomasppeacock and @nfellaby for the confirmation!

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as XL in [v1.2.135](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.135)
