### ISSUE TITLE
Danish sequences belonging to AY.7.1 misassigned as AY.42 (still circulating W8/2022)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#465]
I would like to highlight that a subclade of AY.7.1 ,currently circulating at low levels in Denmark (last sequence W8/2022), is missassigned as AY.42 by Pango.
All the sequences miss the AY.42 defining nuc C25872T and instead they all have A18675G defining mutation of AY.7.1.
The sublineage that managed to survive through today has acquired the following mutations:
orf7a:58F, orf7a:79D, (orf9b:32C)
then orf1a:V3759I
then orf1a:626S
then nt:C12073T
then N:A35V
then orf8:E64D 
then orf3a:W45L

C12073T is present in 27K out of 28k total AY.42 sequences worldwide 
Probably for this reason they have been misassigned to AY.42
as the [Usher downsampled tree ](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1231b_bb2660.json?branchLabel=aa%20mutations&c=pango_lineage&label=nuc%20mutations:G11540A&tl=pango_lineage_usher) shows:

![chrome_screenshot_1647033768435](https://user-images.githubusercontent.com/87669813/157969874-58704095-ce39-4209-aed4-297eb41669ff.png)

Sequence list (187):
[contributors (56).csv](https://github.com/cov-lineages/pango-designation/files/8235808/contributors.56.csv)

@AngieHinrichs @chrisruis @corneliusroemer 

Thx Josette Shoenmakers who pointed the last sequence to me

**Comment by chrisruis** [comment]
Good spot @FedeGueli Agree these look like AY.7.1. We've added these as AY.7.1 designations which should solve the problem
