### ISSUE TITLE
Potential BA.1/BA.2 Recombinant Lineage with Likely Breakpoint at NSP12 (16 Seqs in US-VT as of 2022-03-11)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#467]
### Description
**Recombinant between**: BA.1* & BA.2
**Earliest sequence**: 2022/2/3 (US-VT)
**Most recent sequence**: 2022/2/23 (US-VT)
**Countries circulating**: US-VT
**Likely breakpoint**: between 15241 and 15713 (NSP12).
**Conserved Nuc mutations and AA changes** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/157988839-3fe1243a-d627-4089-9243-e69de283f4a2.png)

**Cov-spectrum query**: A5428G, C10376T, C12513T, A29510C
**GISAID query**: NSP8_T141M, NSP5_P108S, NS3_T223I, NSP3_K38R, NSP13_R392C

### Evidence
![image](https://user-images.githubusercontent.com/86835836/157989540-14ebbce0-40f6-4e58-9395-e67176d12ea9.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_27b6d_bdccc0.json?c=gt-nuc_12513&label=nuc%20mutations:C3241T,G5924A,T25624C

### Genomes:
EPI_ISL_9831293, 10050580, 10103325, 10311162, 10311468, 10311834, 10431710, 10431719, 10635794, 10636680, 10636658, 10714315, 10714652, 10714755, 10714519, 10872579

**Comment by chrisruis** [comment]
Thanks @c19850727 We've just published some guidelines for recombinant lineages [here](https://www.pango.network/pango-lineages-guidelines-for-suggesting-novel-and-recombinant-lineages/). In most cases we expect new recombinant lineages to contain at least 50 sequences, however exceptions to this may arise if the recombinant has particular novelty or significance, with unusual breakpoints and/or parental lineages

From covSpectrum, it looks like there's still 16 sequences from this clade, all from USA. Given the large number of USA sequences, I'd suggest we don't designate this one for now. I'll close for now but can reopen if the clade grows in future
