### ISSUE TITLE
Potential BA.1.1/BA.2 Recombinant Lineage with Likely Breakpoint at NSP3 (49 Seqs in England and Wales as of 2022-03-27)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#468]
### Description
**Recombinant between**: BA.1.1* & BA.2
**Earliest sequence**: 2022/2/13 (UK-England)
**Most recent sequence**: 2022/2/28 (UK-England)
**Countries circulating**: UK (England and Wales)
**Likely breakpoint**: between 4322 and 5385 (NSP3).
**Conserved Nuc mutations and AA changes** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/157995866-b391f923-a018-4645-a154-dfb63e092875.png)
**Cov-spectrum query**: A17615G, C2470T, ORF3a:T223I, ORF1a:K856R, ORF1a:L3027F

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/157997773-84f93aa6-46d7-4ccf-bed0-e26f108c008e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2b584_bdecf0.json?c=gt-nuc_17615&label=nuc%20mutations:C2470T

### Genomes:
EPI_ISL_10053464, 10428619, 10484654, 10516348, 10518341, 10521540, 10538928, 10643464, 10644285, 10688864, 10691795, 10688537, 10725431, 10740708, 10884652, 10885167, England/DHSC-CYYBGHU/2022, Wales/PHWC-PEHFNH/2022

**Comment by c19850727** [comment]
49 sequences as of 2022-03-27.

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as XQ in [v1.2.141](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.141)
