### ISSUE TITLE
Potential BA.1.1/BA.2 Recombinant Lineage with Likely Breakpoint at NSP3 (43 Seqs in Wales as of 2022-03-11)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#469]
### Description
**Recombinant between**: BA.1.1* & BA.2
**Earliest sequence**: 2022/2/13 (UK-Wales)
**Most recent sequence**: 2022/3/1 (UK-Wale)
**Countries circulating**: UK (Wales)
**Likely breakpoint**: between 4322 and 4891 (NSP3).
**Conserved Nuc mutations and AA changes** (those in red frames are likely from the donor from the BA.1.1 side):
![image](https://user-images.githubusercontent.com/86835836/157998327-c70188d3-6e55-49be-a565-a49329b8806e.png)
**Cov-spectrum query**: ORF1a:K856R, ORF1a:T1543I, ORF1a:D4344N, A29510C

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/157998365-33c8b711-d349-48ff-9bc4-3f4d1b319f15.png)

### Genomes:
[Wales BA.1.1-BA.2 Recombinant.txt](https://github.com/cov-lineages/pango-designation/files/8236796/Wales.BA.1.1-BA.2.Recombinant.txt)
I somehow failed to obtain accession numbers from GISAID. The above genome list is instead copied/pasted from the Usher tree I built based on #468 .

**Comment by AngieHinrichs** [comment]
I see some in GISAID:
```
Wales/PHWC-PEIAW1/2022 EPI_ISL_10886975
Wales/PHWC-PEIURA/2022 EPI_ISL_10887332
Wales/PHWC-PEOGFP/2022 EPI_ISL_10674739
Wales/PHWC-PEUCIY/2022 EPI_ISL_10772248
Wales/PHWC-PEUJE6/2022 EPI_ISL_10772524
Wales/PHWC-PEUPA3/2022 EPI_ISL_10772634
Wales/PHWC-PEWO8Z/2022 EPI_ISL_10863887
Wales/PHWC-PEWOCP/2022 EPI_ISL_10863890
Wales/PHWC-PEWOJU/2022 EPI_ISL_10863895
Wales/PHWC-PEWOX8/2022 EPI_ISL_10863906
```

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as XR in [v1.2.141](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.141)
