### ISSUE TITLE
Potential new B.1.1.370 sublineage Russia and Finland with spike E484K and others

### ISSUE THREAD

**Issue by teemusmura** [cov-lineages/pango-designation#47]
Sub-lineage of: B.1.1.370
Earliest sequence: 2021-01-18
Most recent sequence: 2021-03-14
Countries circulating: Russia, Finland

hCoV-19/Russia/Pskov-16/2021|EPI_ISL_1259283|2021-01-18
hCoV-19/Russia/SPE-RII-MH14654S/2021|EPI_ISL_1491610|2021-02-11
hCoV-19/Russia/SPE-RII-MH14691S/2021|EPI_ISL_1491611|2021-02-11
hCoV-19/Finland/HEL-84-V8252/2021|EPI_ISL_1548040|2021-03-14
hCoV-19/Finland/HEL-84-V8262/2021|EPI_ISL_1548041|2021-03-14

pangolin lineage designation B.1.1.370 for 
EPI_ISL_1259283 / hCoV-19/Russia/SPE-RII-MH14654S/2021|EPI_ISL_1491610|2021-02-11 
and hCoV-19/Russia/Pskov-16/2021|EPI_ISL_1259283|2021-01-18
B.1.1 for hCoV-19/Russia/SPE-RII-MH14691S/2021|EPI_ISL_1491611|2021-02-11
hCoV-19/Finland/HEL-84-V8252/2021|EPI_ISL_1548040|2021-03-14
hCoV-19/Finland/HEL-84-V8262/2021|EPI_ISL_1548041|2021-03-14

However these have spike deletion S:N137-,S:D138-,S:P139-,S:F140-,S:L141-,S:G142-,S:V143-,S:Y144-,S:Y145- 
multiple mutations:
ORF1a:S376L
ORF1a:V1006F
ORF1a:T1093A
ORF1a:T2247N
ORF1a:T3255I
ORF1a:Q3729R
ORF1a:S4119T
ORF1b:T1173N
ORF1b:V1905L
ORF1b:A2431V
S:P9L
S:C136Y
S:H245P
S:E484K
S:D614G
S:E780K
ORF3a:L95M
M:L16I

Substitutions shared with hCoV-19/Russia/SPE-RII-12101V/2020|EPI_ISL_524001|2020-05-08 (lineage B.1.1.370) include
ORF1a:V1006F
T1093A
C25000T
C25603T
G26211T
N:R203K
N:G204R

![LPR fa contree](https://user-images.githubusercontent.com/82410439/114458499-f24fd180-9be7-11eb-90e6-b717bb7999ad.jpg)

**Comment by chrisruis** [comment]
Hi @teemusmura thanks very much for submitting this. We've added this as lineage AT.1 (an alias of B.1.1.370.1 as the parental B.1.1.370 lineage has the maximum number of sublevels for a lineage name), it should appear in the next release later today. It looks like sample Russia/SPb-117/2021|EPI_ISL_1259282|2021-01-22 also clusters within this lineage so we've also designated that sequence as AT.1

**Comment by shay671** [comment]
Hi @chrisruis 

I run on USHER all AT.1 & B.1.1.370 samples from GISAID. 
From this analysis it seems that B.1.1.370 is not the ancestor of AT.1 :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_198e0_1d3d70.json?label=nuc%20mutations:G28881A,G28882A,G28883C


![image](https://user-images.githubusercontent.com/80166370/147882863-e82b64a0-4a40-4c3b-aa7b-b613d8eacab7.png)


I also did a mutational analysis for all samples of B.1.1.370 and try to find it's main mutations beyond those of B.1.1 but they do not present in the consensus mutations of AT.1.

**Comment by chrisruis** [comment]
Thanks for spotting this @shay671! We'll have more of a look and see if we can figure out why this has moved and whether it needs updating
