### ISSUE TITLE
Potential BA.1/BA.2 Recombinant with Likely Breakpoint at NSP4 (21 Seqs in England as of 2022-03-11)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#470]
### Description
**Recombinant between**: BA.1* & BA.2
**Earliest sequence**: 2022/2/21 (UK-England)
**Most recent sequence**: 2022/3/1 (UK-England)
**Countries circulating**: UK (England)
**Likely breakpoint**: between 9209 and 9343 (NSP4).
**Conserved Nuc mutations and AA changes** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/158000544-e8b1635b-43dc-4515-a273-a339a6daa0f3.png)
**Cov-spectrum query**: C875T, G14229A, T22792C, G5924A, ORF3a:T223I

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/158000801-f6fd5a74-08e1-4e55-9742-719a57c497e5.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c0e5_c08a30.json?c=gt-nuc_14229&label=nuc%20mutations:C17676T

### Genomes:
EPI_ISL_9839483, 9839682, 9872878, 9894508, 10413150, 10413918, 10415682, 10480052, 10515444, 10537883, 10641197, 10688213, 10734696, 10736100, 10797107, 10799679, 10845598, 10884842, 10885820, 10885983, 10885929, 10886013, 10885891, 10885898, 10886093

**Comment by AngieHinrichs** [comment]
@c19850727 I just happened to notice that these IDs overlap with #464, although the issues have different estimated breakpoints.  Can you double-check?  Thanks!

**Comment by c19850727** [comment]
@AngieHinrichs Thanks let me double check now, and sorry for the mess!

**Comment by c19850727** [comment]
@AngieHinrichs My apologies! I made a very rudimentary mistake when copying/pasting stuff from my excel file to github.

And Thanks for letting me know!

I'll close this issue now.

**Comment by AngieHinrichs** [comment]
No problem, thanks for all of your work finding these @c19850727!
