### ISSUE TITLE
Cryptic sub-lineage of B.1.258.3 with many S mutations [5 seq, England between June 2021-Jan 2022]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#473]
Having a look at lineages that are neither Omicron nor Delta and still circulating in the UK (using open.cov-spectrum.org's Nextclade integration), I came across an interesting B.1.258.3 sub-lineage.

It's a rather curious lineage because:
- It consists of fairly evenly spaced samples between Jun '21 and Jan '22, connecting to a polytomy from Autumn 2020
- It has typical VOC mutations, acquiring more and more as time goes by

The most recent sample has the following S signature (14 S1 mutations!):
`T19I, P25S, E96Q, D215G, R346K, P384L, N439K, L455F, V483F, E484A, A520G, D614G, N679K, P681R, T1006I, C1253F`

It also has typical deletions: `S:144-` and `S:241-243-`

How did this lineage survive so long? In an immunocompromised patient with constant repeated spillovers?

60 mutations is also more than it should have according to clock-like evolution.

Defining S mutations could be any of these: `P25S, R346K, P384L, N439K, E484A, D614G, N679K, C1253F`

<img width="796" alt="image" src="https://user-images.githubusercontent.com/25161793/158700010-0b012994-5f30-4627-b2da-0a7c3df20f3b.png">

You can look at a recent sample here in Nextclade: https://clades.nextstrain.org/?dataset-name=sars-cov-2&input-fasta=https%3A%2F%2Flapis.cov-spectrum.org%2Fopen%2Fv1%2Fsample%2Ffasta%3Fhost%3DHomo%2Bsapiens%26orderBy%3Drandom%26limit%3D200%26dateFrom%3D2020-01-06%26nucMutations%3DT3118C%252CT4489C%26downloadAsFile%3Dtrue

Here's the Usher tree:
<img width="2175" alt="image" src="https://user-images.githubusercontent.com/25161793/158699991-232bb42e-08f5-48fa-b2fb-43601bdb0282.png">
<img width="2174" alt="image" src="https://user-images.githubusercontent.com/25161793/158699999-809b88ff-ac81-45ca-aa08-14899713b244.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39f9b_25c450.json?c=pango_lineage_usher&label=nuc%20mutations:T3118C,T4489C,C4890A,T4977A,C5691T,C17985T,C21757T,G22599A,C22713T,A23013C,T23599A,G27414T,C28836T

**Comment by rambaut** [comment]
Looks likely to be multiple genomes from a chronic infection
