### ISSUE TITLE
Significant BA.1 sublineage with ORF1a:T1822I as of now undesignated [~10% of BA.1*]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#474]
Almost all significant BA.1 sublineages have been designated by now.

The only big omission I see is that `BA.1 + ORF1a:T1822I` has not been designated yet. Are there good reasons not to do so?

It made up around 5-10% of BA.1* overall, up to 30% in some countries.

I think it would make sense to designate. This lineage was visible very early on in BA.1 history.

![image](https://user-images.githubusercontent.com/25161793/158809410-2b42b620-2faa-4c1b-89dd-c42d4617094f.png)

See covSpectrum
<img width="2207" alt="image" src="https://user-images.githubusercontent.com/25161793/158809433-a23c5c56-888a-4a26-95cb-c21443c96978.png">
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.1&nucMutations1=C5730T&pangoLineage1=BA.1&analysisMode=CompareToBaseline

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as BA.1.18 in [v1.2.137](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.137)
