### ISSUE TITLE
BA.1 sublineage with ORF1b:L2523F [5% in SA, 15% in Portugal, 4k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#475]
Looking at as-of-now undesignated BA.1 sublineages I found another one that may be worth designating:
`BA.1 + ORF1b:L2523F`

It was around 5% in SA at the time of exportation. It was particularly imported into Portugal, where it reached 15% of BA.1

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.1&nucMutations1=C21034T&pangoLineage1=BA.1&analysisMode=CompareToBaseline

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as BA.1.19 in [v1.2.137](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.137)
