### ISSUE TITLE
Potential Delta/BA.1 or BA.1.1 Recombinant with Likely Breakpoint at NSP15 or NSP16 (1 seq in Puerto Rico as of 2022-03-18)

### ISSUE THREAD

**Issue by arodzh-sudo** [cov-lineages/pango-designation#476]
**Description**
Recombinant between: AY.x & BA.1 or BA.1.1 (sequence has gap in the G22599A region)
Most recent sequence: 2021/12/20 (PR)
Countries circulating: PR
Likely breakpoint: between 19229 and 21595 (NSP15 or NSP16).
Conserved Nuc mutations and AA changes (those in red frames are likely from the donor from the Delta side):
![image](https://user-images.githubusercontent.com/54407020/159050054-38ad755c-1cb8-4aa6-af1b-b2282de4be2e.png)
Cov-spectrum query: C5497T, A6022G, C8956T, A9058G, C11563T, G17411A, C18004A, C18657T, C21595

Evidence
Usher tree:
![image](https://user-images.githubusercontent.com/54407020/159050734-b2177128-9666-4be4-aa82-2fe23fba1796.png)

Genomes:
EPI_ISL_11163009

**Comment by AngieHinrichs** [comment]
@arodzh-sudo can you include a list of sequences with that pattern?  Thanks!

**Comment by arodzh-sudo** [comment]
@AngieHinrichs as of now we have only detected one sequence with this pattern in PR. The Cov-spectrum query results in 0 sequences probably because the sequence was uploaded today.

**Comment by FedeGueli** [comment]
HI @arodzh-sudo i have identified the putative donor of this recombinant, it is an AY.103 clade (35 sequence) identical to this recombinant between AA 0-17236: It emerged in Massachussets back in October spreading then in NYC and keeping circulating there through November and December.
Probably from NYC it arrived in Puerto Rico in the second decade of December 2021.

Reference:
Rosa I. Cuevas-Ruiz, Arnold Rodriguez-Hilario, Sheila L. Adorno-Camacho, Enid Roman-Mercado, Doris Molina-Rivera  EPI_ISL_9090483 
Puerto Rico Public Health Laboratories, Department of Virology 
hCoV-19/Puerto Rico/PR-PRPHL-MB0089/2021 
Puerto Rico Public Health Laboratories, Department of Molecular Bacteriology

[Covspectrum](https://cov-spectrum.org/explore/North%20America/AllSamples/Past6M/variants?nucMutations=C5497T%2CA6022G%2CC8956T%2CA9058G%2CC11563T%2CG210T%2CC241T%2CC3037T%2CG4181T%2CC6402T%2CC7124T%2CC8986T%2CG9053T%2CC10029T%2CA11201G%2CA11332G%2CC14408T%2CG15451A%2CC16466T%2CA17236G&pangoLineage=AY.103*)

**Comment by arodzh-sudo** [comment]
@FedeGueli Nice catch! Surprised the presumptive donor was sequenced at our lab considering the low volume of samples we have processed. One of our sequencing collaborators is uploading sequences from that time frame, we will monitor closely to see if anything related to this potential recombinant pops out. Thanks!

**Comment by chrisruis** [comment]
Thanks @arodzh-sudo We've just published some guidelines for recombinant lineages [here](https://www.pango.network/pango-lineages-guidelines-for-suggesting-novel-and-recombinant-lineages/). In most cases we expect new recombinant lineages to contain at least 50 sequences, however exceptions to this may arise if the recombinant has particular novelty or significance, with unusual breakpoints and/or parental lineages

From covSpectrum, it looks like there's still just 1 sequence in this lineage. I'd therefore suggest we don't designate this one for now. I'll close for now but can reopen if the clade grows in future
