### ISSUE TITLE
Potential BA.1/BA.2 Recombinant Lineage with Likely Breakpoint at NSP16 (4 Seqs in USA-CA as of 2022-03-18)

### ISSUE THREAD

**Issue by emily-smith1** [cov-lineages/pango-designation#477]
### Description

**Recombinant between**: BA.1 & BA.2
**Earliest sequence**: 2022-02-15
**Most recent sequence**: 2022-03-03	
**Countries circulating**: US-CA
**Likely breakpoint**: 20056-21617

**Conserved Nuc mutations and AA changes** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/84812104/159083968-17768800-1444-4bfa-a1e6-6de37c52fd4a.png)

**Cov-spectrum query**: C2470T & A11755G & A24433G

### Evidence

UShER tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_181fe_48b450.json?c=userOrOld

<img width="455" alt="image" src="https://user-images.githubusercontent.com/84812104/159085430-42ee10b7-433c-42d8-9a47-f470a34f1c32.png">

### Genomes

EPI_ISL_10567701, EPI_ISL_10779133, EPI_ISL_11170429

[CA_BA1_BA2_recombs_2022-03-18.fasta](https://github.com/cov-lineages/pango-designation/files/8307630/BA1_BA2_recombs.fasta.txt)

Thanks @AngieHinrichs for your assistance!

**Comment by geertmartens** [comment]
Hi Emily, 
I notice that your N=4 sequences cluster close to the sequences uploaded by me (AZ Delta, Belgiumà, see issue 

#460 

I just found out that our index case was infected around February 4, 2022, likely by family members coming back from New York, USA. I have not whole genome data about these returning travelers. Is there any evidence that this recombination also circulates in NY? Could you explore your N=4 USA sequences to the ones i have uploaded? 

Thanks, 
Geert A. Martens

**Comment by geertmartens** [comment]
Hi Emily, 
Your sequences appear very similar to N=2 sequences uploaded by Amsterdam, see issue 472. Your USA sequences share T222006G (S:V213G) with the Amsterdam sequences, that is not present in my N=20 sequences. 

#472 

Nextclade view on Spike: 

![image](https://user-images.githubusercontent.com/93787799/159257353-567756f3-034f-4104-bb13-6145d2f42dd5.png)

Nexclade view on ORF1a/

![image](https://user-images.githubusercontent.com/93787799/159257766-13e14dfd-acf1-4825-bc35-b60c80c73bc2.png)

Nextclade view on ORF1b

![image](https://user-images.githubusercontent.com/93787799/159257811-a7dadeaa-6582-4166-b65e-b20c0db53d65.png)

**Comment by emily-smith1** [comment]
Thanks for this comparison, Geert! It looks like the sequences from the Netherlands might have an earlier breakpoint than the USA-CA sequences. They contain ORF1b:T2163I as well as the synonymous mutation A20055G, which are both considered defining mutations of BA.2. The sequences from Belgium have these mutations as well. 

It's hard to make any conclusions on possible origins with only 4 sequences from the USA. If I identify any more I'll provide an update. There is a sequence from Italy that somewhat clusters with the USA-CA sequences now on the UShER tree, but there might be some QC issues based on a quick assessment of the assembly.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/84812104/159287838-7bfbdc10-c502-4e6e-ab05-d3a4a7a1d31f.png">

**Comment by emily-smith1** [comment]
This cluster has grown to n=8 sequences in CA. Here are GISAID accessions for those accepted: EPI_ISL_11170429, EPI_ISL_10567701, EPI_ISL_10779133, and EPI_ISL_11529230. Attached is a concatenated fasta containing all 8.

[CA_BA1_BA2_recomb_cluster_2022-03-30.txt](https://github.com/cov-lineages/pango-designation/files/8385297/CA_BA1_BA2_recomb_cluster_2022-03-30.txt)

**Comment by emily-smith1** [comment]
Another sequence belonging to this cluster has been identified. GISAID accession: EPI_ISL_11757329

**Comment by chrisruis** [comment]
Thanks @emily-smith1 We've just published some guidelines for recombinant lineages [here](https://www.pango.network/pango-lineages-guidelines-for-suggesting-novel-and-recombinant-lineages/). In most cases we expect new recombinant lineages to contain at least 50 sequences, however exceptions to this may arise if the recombinant has particular novelty or significance, with unusual breakpoints and/or parental lineages

From covSpectrum, it looks like there's now 10 sequences in this lineage now, 9 from California and 1 from Nevada, collected 15/02/2022-18/03/2022. I'd suggest this is too small for a designation at this stage. I'll close this for now but can reopen if this clade grows in the future
