### ISSUE TITLE
South African BA.2/BA.1* Recombinant with S:75V and breakpoint at ORF3a/M Protein (11 Seqs as of 2022-04-10)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#478]
### Description
**Recombinant between**: BA.2 & BA.1*
**Earliest sequence**: 2021/12/13 (South Africa)
**Most recent sequence**: 2022/2/21 (South Africa)
**Countries circulating**: South Africa (Gauteng, Limpopo and North-West)
**Likely breakpoint**: between 26062 and 26528 (from ORF3a to M protein).
**Conserved Nuc mutations** (those in red frames are likely from the donor from the BA.1* side):
![image](https://user-images.githubusercontent.com/86835836/159140654-1493d955-9496-4200-ba72-e4e11ffcfa78.png)
**Cov-spectrum query**: ORF1a:G1307S, ORF1a:S135R, ORF1a:T842I, S:G75V, M:D3G

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/159140449-131a39bb-cba7-492c-a1b2-37b02cb43f4b.png)
https://nextstrain.org/fetch/hgw1.soe.ucsc.edu/trash/ct/subtreeAuspice1_hgw1_1df00_5e0c00.json?c=gt-nuc_21786&label=nuc%20mutations:A26530G,T26858C

### Genomes
EPI_ISL_10210389, 10210644, 10878466, 11139946, 11139875

**Comment by corneliusroemer** [comment]
@chrisruis can you have a look at this one? It's from South Africa, which means there are probably many more of this recombinant than 9.

It's interesting for a couple of reasons:
- Very early recombinant, earliest sample from early December
- Sustained circulation into March
- BA.1 breakpoint after BA.2 spike
- It has S:G75V which was part of Lambda
- Recombinant from South Africa

It's 9 sequences now at least

![image](https://user-images.githubusercontent.com/25161793/162549011-d8228579-5515-413e-89ec-b3ab056453ee.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4719_b5f00.json?c=gt-nuc_9866&label=nuc%20mutations:C13994T,G21786T

**Comment by corneliusroemer** [comment]
I noticed S:75V also increased in proportion in Delta. It seems to have provided a 1%/day growth advantage, which is not insignificant

![image](https://user-images.githubusercontent.com/25161793/162549227-e6f6ac84-1f89-470d-b0e6-3203210faa61.png)

![image](https://user-images.githubusercontent.com/25161793/162549234-60113a9e-47c7-411f-a493-43465686ad22.png)

https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Y2021/variants?pangoLineage=B.1.617.2*&aaMutations1=S%3A75V&pangoLineage1=B.1.617.2*&analysisMode=CompareToBaseline&

**Comment by c19850727** [comment]
11 sequences as of 2022-04-10.

**Comment by chrisruis** [comment]
Thanks @c19850727 and @corneliusroemer I agree that the circulation across multiple regions of South Africa over several months supports designation in this case. We've added this as XT

**Comment by c19850727** [comment]
One more sequence from another province of South Africa (Free State).
