### ISSUE TITLE
Potential BA.1/BA.2 Recombinant Lineage with Likely Breakpoint at NSP4 (1 Seq in Brazil as of 2022-03-22)

### ISSUE THREAD

**Issue by alex-ranieri** [cov-lineages/pango-designation#479]
By Alex Ranieri and Gabriela Ribeiro (Butantan Network for Pandemic Alert of SARS-CoV-2 Variants, São Paulo).

**Description**

Recombinant between: BA.1* & BA.2
Earliest sequence: 2022/03/07 (Brazil)
Countries circulating: Brazil
Likely breakpoint: before 10028 (NSP4).
Found Nuc mutations and AA changes (those in red frames are likely from the donor from the BA.1 side):
![Mutations_1](https://user-images.githubusercontent.com/94479933/159550842-b2648869-7338-46da-933b-90e024ac6044.png)
![Mutations_2](https://user-images.githubusercontent.com/94479933/159550908-43ed3bc8-ec91-44cc-bed8-0ab4769769b2.png)

**Evidence**

Usher tree:
![Usher_tree](https://user-images.githubusercontent.com/94479933/159551048-23507f96-8584-4581-ae82-ed7a15856ab1.png)

[nextclade.auspice.zip](https://github.com/cov-lineages/pango-designation/files/8326993/nextclade.auspice.zip)

Proportion of variant composition in sample reads using LCS – Lineage deComposition for Sars-cov-2 pooled samples (https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btac047/6519145?login=true): 
![LCS](https://user-images.githubusercontent.com/94479933/159551253-12ea6477-bfa3-4385-8ddb-57459009da10.png)

Reads:
[SE10-22-Inside-01_S56_L001_R2_001.fastq.gz](https://github.com/cov-lineages/pango-designation/files/8327007/SE10-22-Inside-01_S56_L001_R2_001.fastq.gz)
[SE10-22-Inside-01_S56_L001_R1_001.fastq.gz](https://github.com/cov-lineages/pango-designation/files/8327013/SE10-22-Inside-01_S56_L001_R1_001.fastq.gz)

We submitted this sequence to RIPPLES (https://usher-wiki.readthedocs.io/en/latest/ripples.html) in order to detect possible recombination events and obtained a node that presented this genome with parsimony improvement score equal to 9. 

NextClade:
Full genome
![NextClade_all](https://user-images.githubusercontent.com/94479933/159551587-50a64f66-c583-4f65-82e4-15a46b002f94.png)

ORF1a
![NextClade_ORF1a](https://user-images.githubusercontent.com/94479933/159551627-975c0771-f4cc-41f2-94f9-ecf0eb24214e.png)

Genome: 

EPI_ISL_11294819

This sample was collected in the city of São Paulo. We are currently investigating if more sequences with this pattern emerges in our genomic surveillance network.

**Comment by alex-ranieri** [comment]
I've executed again the Nextclade on this sequence and now it shows as XE lineage.

**Comment by corneliusroemer** [comment]
@alex-ranieri Well noticed! I'm glad Nextclade was helpful here.

The sequence is indeed very similar. One classic reversion and one private mutation only.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/25161793/160434675-2beb3b00-c207-4f11-b9dc-621bc80257d8.png">

<img width="616" alt="image" src="https://user-images.githubusercontent.com/25161793/160434679-dc7c7f56-b9e4-4c91-8b9e-da26f48caf9c.png">

In general, one needs to be careful though interpreting Nextclade pango assignments.

You can't trust Nextclade's Pango calls for recombinants when there are many reversions/labeled mutations.

>Recombinants: Recombinant Pango lineages are now included in the reference tree. Each recombinant is attached to the root node so as not to spawn false internal nodes in the tree that would attract bad sequences. As long as recombinants do not qualify for a Nextstrain clade, they will receive the place holder clade name recombinant. Pango lineages are provided if present. Beware that new unnamed recombinants with similar donors but slightly different breakpoint will attach to existing recombinants in the reference tree and thus get a wrong Pango lineage. A number of reversions and labeled mutations is a sign that you may have a similar but different recombinant.
https://github.com/nextstrain/nextclade_data/blob/master/CHANGELOG.md#sars-cov-2

See this issue as an example: https://github.com/nextstrain/nextclade/issues/760
