### ISSUE TITLE
What happened to B.1.438?

### ISSUE THREAD

**Issue by mattheww95** [cov-lineages/pango-designation#48]
I still have sequences being called as B.1.438. But There appears to no longer be any information for it on https://cov-lineages.org

The webpage link here: https://cov-lineages.org/lineages/lineage_B.1.438.html# is still viable as well.

**Comment by chrisruis** [comment]
Hi @mattheww95 thanks very much for letting us know. It looks like B.1.438 was missed out of one of the Pango files at some point - I've added it back in so it should reappear on cov-lineages.

From this, I've also had a look through the B.1.438 tree and it looks like there's 4 sublineages in there resulting from introductions into different countries with onward transmission (see tree below). So I've also added these sublineages in:
B.1.438.1 - Canada
B.1.438.2 - Mayotte/Reunion
B.1.438.3 - USA
B.1.438.4 - USA
The parental B.1.438 is still quite broadly geographically distributed. Some sequence assignments may change from B.1.438 to one of these sublineages.

The updated B.1.438 and its sublineages are in [v1.1.17](https://github.com/cov-lineages/pango-designation/releases/tag/v1.1.17)

![B 1 438](https://user-images.githubusercontent.com/47785131/115534265-84fb0b00-a28f-11eb-9743-85387bd48a48.png)
