### ISSUE TITLE
Potential BA.1*/BA.2 Recombinant with Likely Breakpoint at NSP3 (104 Seqs in UK-England as of 2022-03-29) 

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#480]
### Description
**Recombinant between**: BA.1* & BA.2
**Earliest sequence**: 2022/2/1 (UK-England)
**Most recent sequence**: 2022/3/15 (UK-England)
**Countries circulating**: UK
**Likely breakpoint**: between 2834 and 4183 at NSP3.
**Conserved Nuc mutations** (those in red frames are likely from the donor from the BA.1* side):
![image](https://user-images.githubusercontent.com/86835836/159598582-4e663a84-63d1-4666-bada-eb10468c9ca2.png)
**Cov-spectrum query**: A2832G, G4184A, G10986A, A29510C
**GISAID query**: NSP3_K38R, N_S413R, NSP6_R5K, NSP3_G489S

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/159600217-0246fb00-5957-4dd4-a013-f765c156d440.png)
https://nextstrain.org/fetch/genome-euro.ucsc.edu/trash/ct/subtreeAuspice1_genome_euro_2e4_a6dbc0.json?c=gt-nuc_10986&label=nuc%20mutations:T2790C,A2832G

### Genomes:
EPI_ISL_10425128, EPI_ISL_10711914, EPI_ISL_10796581, EPI_ISL_10844807, EPI_ISL_10849068, EPI_ISL_10927897, EPI_ISL_10928229, EPI_ISL_10928246, EPI_ISL_10931524, EPI_ISL_10961880, EPI_ISL_10962049, EPI_ISL_10972194, EPI_ISL_10987456, EPI_ISL_11035378, EPI_ISL_11040174, EPI_ISL_11040438, EPI_ISL_11040610, EPI_ISL_11076788, EPI_ISL_11076794, EPI_ISL_11077708, EPI_ISL_11080588, EPI_ISL_11086364, EPI_ISL_11120816, EPI_ISL_11123238, EPI_ISL_11123989, EPI_ISL_11128269, EPI_ISL_11151707, EPI_ISL_11152717, EPI_ISL_11153474, EPI_ISL_11153656, EPI_ISL_11153885, EPI_ISL_11180762, EPI_ISL_11181543, EPI_ISL_11186438, EPI_ISL_11186697, EPI_ISL_11187359, EPI_ISL_11195255, EPI_ISL_11195470, EPI_ISL_11198749, EPI_ISL_11212985, EPI_ISL_11214847, EPI_ISL_11215368, EPI_ISL_11215525, EPI_ISL_11215580, EPI_ISL_11215782, EPI_ISL_11216131, EPI_ISL_11216651, EPI_ISL_11216766, EPI_ISL_11216776, EPI_ISL_11274926, EPI_ISL_11276773, EPI_ISL_11280408, EPI_ISL_11283569, EPI_ISL_11283932

**Comment by c19850727** [comment]
83 sequences as of 2022-03-27.

**Comment by c19850727** [comment]
There are 104 sequences as of 2022-03-29, of which one is detected in Canada-Ontario.

And according to Cov-spectrum, there's a growth advantage over BA.2 in UK since 2022-02-01.
![image](https://user-images.githubusercontent.com/86835836/160598799-4a2f0f63-7c37-4396-b1cd-f59bde6dcf65.png)

It makes me wonder if BA.1-BA.2 recombinants like this one (and also XE, which has a similar breakpoint) might really have some fitness advantage over both BA.1 and BA.2.

**Comment by FedeGueli** [comment]
Hi @c19850727 wondering if that orf7a:34S  could give some advantage as we have seen for orf7a:P45L in AY.122.
If more sequences will be accumulated we will see that more clearly.

**Comment by FedeGueli** [comment]
I checked the orf7a:34S sublineage of this recombinant:
in England seems to have a clear advantage over BA.2.
[CovSpectrum Comparison vs BA.2](https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/from=2022-02-10&to=2022-03-25/variants?pangoLineage=BA.2&aaMutations1=Orf7a%3AP34S&nucMutations1=A2832G%2CA29510C%2CG10986A%2C4184A&analysisMode=CompareToBaseline) 
![chrome_screenshot_1648744132296](https://user-images.githubusercontent.com/87669813/161104815-928bc8cc-4e45-4725-bd14-ae06f9b757c4.png)

@c19850727

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as XN in [v1.2.140](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.140)
