### ISSUE TITLE
Potential BA.1.1/BA.2 Recombinant with Likely Breakpoint at ORF6/N Protein (57 Seqs in UK-Scotland as of 2022-03-27)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#481]
### Description
**Recombinant between**: BA.1.1 & BA.2
**Earliest sequence**: 2022/2/26 (UK-Scotland)
**Most recent sequence**: 2022/3/14 (UK-Scotland)
**Countries circulating**: UK
**Likely breakpoint**: between 27385 and 29509 (from ORF6 to N).
**Conserved Nuc mutations** (those in red frames are likely from the donor from the BA.2 side):
![image](https://user-images.githubusercontent.com/86835836/159603254-74334891-601b-4f4d-9f11-6dd1085bb070.png)
**Cov-spectrum query**: A24190C, C26880A, A29510C
**GISAID query**: NSP3_K38R, M_L120I, N_S413R, Spike_R346K

### Evidence
**Usher tree** (it's visually more friendly in a scattered tree):
![image](https://user-images.githubusercontent.com/86835836/159603570-bb5f1d33-93fd-4bfe-b4c8-42c15cd2f75f.png)
https://nextstrain.org/fetch/genome-euro.ucsc.edu/trash/ct/subtreeAuspice1_genome_euro_3a18_a70490.json?c=gt-nuc_24190&l=scatter&scatterY=gt

Also, big thanks to @thomasppeacock for conforming the S2M deletion as an evidence that this cluster is more likely a potential recombinant than BA.1.1 convergently gaining an additional A29510C (N:S413R) mutation.
![image](https://user-images.githubusercontent.com/86835836/159603975-03b23765-ab74-4e37-82f4-f68d2193e869.png)
(BTW, a bit off-topic, but it's interesting to notice that a small number of BA.1* do have gained N:S413R convergently, not by A29510C though, but by T29512A).

### Genomes:
EPI_ISL_10514752, EPI_ISL_10573232, EPI_ISL_10642673, EPI_ISL_10801494, EPI_ISL_10803878, EPI_ISL_10846929, EPI_ISL_10846949, EPI_ISL_10853203, EPI_ISL_10853388, EPI_ISL_10858198, EPI_ISL_10884015, EPI_ISL_10927706, EPI_ISL_10938911, EPI_ISL_10962586, EPI_ISL_10962824, EPI_ISL_10963941, EPI_ISL_10963978, EPI_ISL_10965277, EPI_ISL_11036241, EPI_ISL_11038349, EPI_ISL_11038512, EPI_ISL_11041639, EPI_ISL_11041660, EPI_ISL_11041739, EPI_ISL_11042027, EPI_ISL_11042952, EPI_ISL_11044597, EPI_ISL_11045234, EPI_ISL_11045282, EPI_ISL_11045393, EPI_ISL_11046593, EPI_ISL_11047840, EPI_ISL_11048228, EPI_ISL_11081210, EPI_ISL_11088663, EPI_ISL_11091381, EPI_ISL_11126571, EPI_ISL_11130227, EPI_ISL_11131558, EPI_ISL_11132137, EPI_ISL_11132179, EPI_ISL_11132772, EPI_ISL_11189245, EPI_ISL_11189250, EPI_ISL_11273755, EPI_ISL_11273889, EPI_ISL_11276479, EPI_ISL_11289836

**Comment by AngieHinrichs** [comment]
That is an interesting little branch.  Scotland/QEUH-3880993/2022 has A28877T and G28878C which apparently got that little branch (with A29510C and private mutations A24190C and C26880A) placed on a very large branch with those two mutations in BA.1.1.  But then all the rest of the sequences do not have A28877T and G28878C, so UShER placed those on a little branch with two back-mutations/reversions.  Here is a view of the proposed recombinants with Scotland/QEUH-3880993/2022 all by itself and all other sequences after reversions on 28877 and 28878: https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-481.json?branchLabel=back-mutations&c=pango_lineage_usher&label=nuc%20mutations:A24190C,C26880A,A29510C

Could that imply a different breakpoint for Scotland/QEUH-3880993/2022 (after 28878) vs. the rest of the sequences (before 28877)?

**Comment by AngieHinrichs** [comment]
Also, very nice to have that deletion as a confirmation that this wasn't just a chance mutation at 29510!  👍

**Comment by c19850727** [comment]
@AngieHinrichs Nice catch! I somehow totally missed A28877T and G28878C......

And yes I agree. There might be 2 recombination events where the breakpoint for most of above sequences are before 28877.

**Comment by AngieHinrichs** [comment]
Curiously, A28877T and G28878C also appeared together in P.1 (Gamma) and C.37.1 (C.37 is Lambda).

**Comment by corneliusroemer** [comment]
I've also noticed this just now. That's why @lenaschimmel's sc2rf thinks some BA.1 in Greece/Russia are recombinants with Gamma :D 

<img width="2205" alt="image" src="https://user-images.githubusercontent.com/25161793/160028004-03bdc719-afa2-496d-b595-5c16c61b3ba2.png">

**Comment by c19850727** [comment]
57 sequences as of 2022-03-27.

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as XP in [v1.2.141](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.141)
