### ISSUE TITLE
Potential BA.1/BA.2 Recombinant with multiple breakpoints or early divergent BA.2 (1 Seq in Salzburg, Austria)?

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#485]
**Description**
**Sub-lineage of:** BA.1 & BA.2
**Earliest sequence:**  2022-03-03 (Austria)
**Most recent sequence:**  2022-03-03 (Austria)
**Countries circulating:** Austria

**Evidence**

We just started sequencing local Covid samples in our lab and we stumbled across a weird looking sequence which apparently shares features of BA.1 and BA.2.  In detail, the S region of **hCoV-19/Austria/Medilab_107/2022** (black arrow left) shares multiple mutations with either BA.1 (brown arrows) or BA.2 (blue arrows). 

![grafik](https://user-images.githubusercontent.com/102166254/160101752-2f6a72ad-8975-40b8-b265-0973898ac779.png)

Likewise, orf3a, M, orf6, N look more like Ba.1 while Orf1b looks more like BA.2:

![grafik](https://user-images.githubusercontent.com/102166254/160101789-bbb5d91c-cb28-4798-a4fd-216c552ee14b.png)

In a down sampled tree the sample appears as an early branching lineage to the BA.2 clade:

![grafik](https://user-images.githubusercontent.com/102166254/160101835-48d2ab92-cd65-4e8f-8de0-980b46d4d653.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_18f7c_d7b3c0.json

Usher scatter tree with 5000 closest genomes:

![grafik](https://user-images.githubusercontent.com/102166254/160102063-f8922c4c-92d7-4147-8ecf-c8dc105087db.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18f7c_d7b3b0.json?c=pango_lineage&l=scatter

**Genomes:**
EPI_ISL_11113506

In this context I am wondering if this could be either a recombinant between BA.1 and BA.2 with multiple breakpoints or an “early” rarely sampled branch of BA.2? I am also thinking about possible contamination but in such case, I would expect at least a few ambiguities (non-ACGTN characters) instead of none?

I am happy for any clue or opinion!

All the best!

Alex

**Comment by corneliusroemer** [comment]
Thanks for sharing what you found. It's great if labs have a look at their own sequences to see if anything interesting pops up.

To me, this looks like co-infection/contamination. As you noticed, there's no clear breakpoint.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/25161793/160162929-58ec11d1-c4fa-408f-af39-5ea41a91a1f6.png">

If there were multiple nearly identical sequences it would be worth double checking whether it could in fact be real.

I don't think it's likely that an early BA.2 would show up in March in Austria, without any relatives globally.

You mentioned you have started sequencing recently. It could be worth checking your pipeline and raw reads to see why you have dropouts in the main S:500 region.

If another one just like this pops up, let us know!
