### ISSUE TITLE
Potential recombinant Delta/Omicron from Mexico ("None" classification by Pango)

### ISSUE THREAD

**Issue by kabrila** [cov-lineages/pango-designation#489]
Description
We have analyzed samples submitted without lineage classification on the GISAID and Pango platforms and the main characteristic of these samples is that they present Omicron mutations + Delta mutations, all the sequences came from clinical samples collected on December 2021 to January 2022. 
We first performed a review of the fastq files to rule out that the lack of classification was due to the fact that the sequences had low coverage in the "spike" gene or had areas with long stretches of NNNs. All these sequences have a coverage above 99% and an average depth of approximately 3000x. We also used the Nextclade platform to see where they grouped phylogenetically. Also a mutation analysis of all samples were performed. Important to notice that we found three different patterns of mutations.

Countries circulating: Mexico

Genomes
EPI_ISL_9093026, EPI_ISL_9093022, EPI_ISL_9093024, EPI_ISL_9093025, EPI_ISL_9430958, EPI_ISL_9430954, EPI_ISL_9749517.

Evidence
![image](https://user-images.githubusercontent.com/102255778/160490410-374b155e-d38b-4610-ab3d-a417e76c6c7a.png)
![image](https://user-images.githubusercontent.com/102255778/160490538-023632ed-f1d6-4880-8b23-1dbdf6f8640e.png)
![image](https://user-images.githubusercontent.com/102255778/160491299-1d1f14ca-53bf-4f8c-b8c3-56864ce31bd4.png)
![image](https://user-images.githubusercontent.com/102255778/160490665-0f639e38-a159-4557-a304-ca876928c9b0.png)
![image](https://user-images.githubusercontent.com/102255778/160490709-1539c6ad-43db-4821-a6ec-d28bb3b4d228.png)

**Comment by SamaZYX** [comment]
Hello @kabrila ,
In my opinion the sequences look like cross-contamination or infection of 2 lineages. Mutations of both lineages are across all the genome and it is hard to detect the breakpoint.

**Comment by willros** [comment]
Hi,

I just wonder what tool that was used to create the most upper figure. It seems like a good way to present the data.

Thank you,
William
