### ISSUE TITLE
French BA.2 with S:L452R and ORF1a:S2519P, ~50% in Bretagne [50 seq as of 2022-04-05]

### ISSUE THREAD

**Issue by vthibault35** [cov-lineages/pango-designation#491]
We have identified several strains circulating in Brittany (France) based on a BA.2 backbone but carrying a S:L452R substitution. These isolates carry also ORF1ab:S2519P. There are around 150 similar sequences available in GISAID but those circulating around Brittany are somewhat different after phylogenetic analysis. Two sequences were generated by Pasteur Institute CNR (Attached one analysis on few recently generated sequences)
Few GISAID available IDs from Brittany, more to be available.

- hCoV-19/France/BRE-CHUP-8600848171/2022
- hCoV-19/France/BRE-CHUP-8600848177/2022
- hCoV-19/France/BRE-CHUP-8600847225/2022
- hCoV-19/France/BRE-IPP18092/2022
- hCoV-19/France/BRE-IPP18361/2022
- hCoV-19/France/BRE-CHUP-8600838858/2022
- hCoV-19/France/BRE-CHUP-8600842569/2022
- hCoV-19/France/BRE-CHUP-8600842591/2022
- hCoV-19/France/BRE-CHUP-8600844231/2022

![L452R_Omicron](https://user-images.githubusercontent.com/93667583/160858066-ac96c929-fb57-4060-a143-b2814e1fbb7e.JPG)

**Comment by corneliusroemer** [comment]
Look clean, could well be real but 8 is a very small number for a normal sublineage designation.

<img width="2543" alt="image" src="https://user-images.githubusercontent.com/25161793/160860999-d0aa6d1a-a57f-4f01-97e5-214d499ed879.png">

Globally at most 120 BA.2* with S:L452R, some could just be contamination.

Has appeared in many countries before: UK, Denmark, etc.

<img width="2543" alt="image" src="https://user-images.githubusercontent.com/25161793/160860999-d0aa6d1a-a57f-4f01-97e5-214d499ed879.png">

**Comment by vthibault35** [comment]
_> Globally at most 120 BA.2* with S:L452R, some could just be contamination._

This is not a very positive comment! To pull apart this hypothesis, there are no more S:L452R strains circulating in France (the last ones were Delta). Contamination is more than unlikely and sequences were obtained from different labs and runs.

**Comment by corneliusroemer** [comment]
> > Globally at most 120 BA.2* with S:L452R, some could just be contamination.

> This is not a very positive comment! To pull apart this hypothesis, there are no more S:L452R strains circulating in France (the last ones were Delta). Contamination is more than unlikely and sequences were obtained from different labs and runs.

I think this is a misunderstanding. My comment was not regarding the French sequences, but the global ones - many of which seem to have quality problems. The ones you mentioned look clean, as I said before.

In general, sublineages with only few mutations in addition, even if they are VOC-like, get proposed when there are a large number of sequences, something like hundreds or thousands of sequences (unless the sequences are from countries with low sequencing coverage. Otherwise there would be thousands of proposals - because every possible substitution arises multiple times.

With recombinants, the threshold is lower because recombination events are rarer and more special than single substitutions.

It's great you're having a close look at French sequences and let us know about interesting clusters. But I personally don't see a reason to designate a cluster with only a dozen sequences at this point.

Here's a covSpectrum query to monitor whether the cluster grows and how fast:
https://cov-spectrum.org/explore/Europe/AllSamples/Past6M/variants?nucMutations=T7820C%2CT22917G&pangoLineage=BA.2*&

**Comment by corneliusroemer** [comment]
Even though this cluster is still small, it's growing quite a bit.

It's up to 30 samples now, 1 from the UK.

@vthibault35 @mosassi do you know how the sequences from Bretagne were chosen? They make up almost 100% of recent sequences from there - this could be explained by some targeted sequencing? Or is it random surveillance?

**Comment by bikudh** [comment]
![image](https://user-images.githubusercontent.com/88990329/161601157-0abdde16-7339-4161-8015-b01aa16af847.png)
![image](https://user-images.githubusercontent.com/88990329/161601244-29765f09-9e35-40d0-b9d4-4356769c53d3.png)

**Comment by silcn** [comment]
@bikudh that's a separate lineage, see #517

**Comment by mosassi** [comment]
As at most 210 BA.2* with S:L452R, i  think it's better to rename the title : French BA.2 with S:L452R and ORF1a:S2519P substitutions, for better monitoring and to avoid confusions with other BA.2 S:L452R.

More sequences are now availale in Gisaid : 
hCoV-19/England/LSPA-3CB043B/2022
hCoV-19/England/LSPA-3CB70F4/2022

hCoV-19/France/BRE-IPP21461/2022
hCoV-19/France/BRE-IPP21462/2022
hCoV-19/France/BRE-IPP21463/2022

hCoV-19/France/PDL-IPP19339/2022
hCoV-19/France/PDL-IPP20615/2022

![image](https://user-images.githubusercontent.com/36232716/161755294-82160b9f-f079-4716-b211-e7e8bfdbd65e.png)


Other new sequences from Bretagne will be submitted to gisaid very soon.

![image](https://user-images.githubusercontent.com/36232716/161756464-ca2f2a8f-1e7a-48fd-882f-885a67906ef0.png)

**Comment by corneliusroemer** [comment]
@chrisruis I think this one is worth designating.

Reasons:
- It's got a suspicious VOC mutation (S:452R)
- It seems to have grown from first detection to ~50% or more in the region of Bretagne, being detected in other French regions, too. Twice in England in addition.

It looks clean. Two mutations in addition to standard BA.2 (see snipit)

![snp_plot](https://user-images.githubusercontent.com/25161793/161829495-a49c0aea-1567-4382-b35d-573fabaa4cf0.png)

**Comment by corneliusroemer** [comment]
One caveat: I've been told that France (or Bretagne) does targeted sequencing if BA.2 + L452R shows up - so the large proportion may not be representative.
Does anyone from France know more about this? Maybe @flodebarre or @Simon-LoriereLab?

**Comment by vthibault35** [comment]
> One caveat: I've been told that France (or Bretagne) does targeted sequencing if BA.2 + L452R shows up - so the large proportion may not be representative. Does anyone from France know more about this? Maybe @flodebarre or @Simon-LoriereLab?

Actually, you are totally right! From a recent analysis looking at all point mutation screening performed in France, it seems that variants carrying S:L452R are circulating at low level in different regions. It could be residual Delta but most likely rather Omicron with S:L452R. Those we have sequenced were addressed to our lab because they presented an unusual L452R point mutation screening profile. They certainly represent a clear bias in our recruitment and do not reflect a general circulation of this variant in our area.
"Flash" sequencing surveys (sequencing of 10% of all circulating strains one defined day in France) are regularly performed in France. They should give us an unbiased view of the true prevalence of Omicron S:L452R overall. We will keep an eye on these results in the following days.
Thank you for your interest!

**Comment by flodebarre** [comment]
> One caveat: I've been told that France (or Bretagne) does targeted sequencing if BA.2 + L452R shows up - so the large proportion may not be representative.
> Does anyone from France know more about this? Maybe @flodebarre or @Simon-LoriereLab?

Yes. France is continuing PCR genotyping on positive tests, looking for S:L452R (coded "C1" when positive) and a set of mutations meant to be characteristic of Omicron and consisting mostly of S:K417N (coded "D1" when positive). The rationale being that it will help find Delta-Omicron coinfections or potential Delta-Omicron recombinants (_no comment_; Details, in French, [in this document](https://solidarites-sante.gouv.fr/IMG/pdf/reply_du_dgs-u131-_actualisation_doctrine_de_criblage_03-22.pdf)). All tests coded C1D1, i.e. positive for L452R and K417N, are to be sequenced ("_Séquençage systématique des prélèvements avec un résultat de criblage C1D1_").   

Unfortunately, "_Flash surveys_" are not systematically properly at random, so care it will still be needed when interpreting frequency changes, even in these surveillance data.

**Comment by chrisruis** [comment]
Thanks @vthibault35 We've added this as BA.2.11 in [v1.3](https://github.com/cov-lineages/pango-designation/releases/tag/v1.3)

**Comment by Pseudomonas-fluorescens** [comment]
> @chrisruis I think this one is worth designating.
> 
> Reasons:
> 
> * It's got a suspicious VOC mutation (S:452R)
> * It seems to have grown from first detection to ~50% or more in the region of Bretagne, being detected in other French regions, too. Twice in England in addition.
> 
> It looks clean. Two mutations in addition to standard BA.2 (see snipit)
> 
> ![snp_plot](https://user-images.githubusercontent.com/25161793/161829495-a49c0aea-1567-4382-b35d-573fabaa4cf0.png)

Can you tell me what software interface this is?

**Comment by chrisruis** [comment]
Hi @Pseudomonas-fluorescens This is snipit (https://github.com/aineniamh/snipit)

**Comment by Pseudomonas-fluorescens** [comment]
> Hi @Pseudomonas-fluorescens This is snipit (https://github.com/aineniamh/snipit)

Thank you so much.
