### ISSUE TITLE
Lithuanian BA.2 lineage with 3 silent mutations.

### ISSUE THREAD

**Issue by evogytis** [cov-lineages/pango-designation#492]
New lineage proposal
by Gytis Dudas (IBT, Life Sciences Center, Vilnius University)

Description
Sub-lineage of: BA.2
Earliest sequence: hCoV-19/Denmark/DCGC-298591/2022|EPI_ISL_8465418|2022-01-02
Most recent sequence: hCoV-19/England/LSPA-3BAEAE4/2022|EPI_ISL_11448007|2022-03-21
Countries circulating: Lithuania (306 genomes, ~10-20% of recent cases), Denmark (643 genomes), UK (370), Poland (50), elsewhere in Europe (total of 1421 genomes so far)

BA.2 lineage bearing silent mutations C20371T, C21054T, and C22570T. Lineage is largely restricted to Europe and sequenced in appreciable numbers in Denmark and UK but does not comprise a significant proportion (<0.2%) of cases in either. This lineage is notably prevalent in Lithuania, making up ~13% of cases in March so far and seemingly rising in frequency, presumably stochastically. Parental clade carries C25624T (ORF3a: H78Y) with recent ~10% prevalence in Europe (~30% in Lithuania, Poland, Sweden, and Denmark).

Genomes
[accessions.csv](https://github.com/cov-lineages/pango-designation/files/8386863/accessions.csv)

Evidence
global prevalence:
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=C22570T%2CC21054T%2CC20371T&pangoLineage=BA.2*

prevalence in Lithuania:
https://cov-spectrum.org/explore/Lithuania/AllSamples/AllTimes/variants?nucMutations=C22570T%2CC21054T%2CC20371T&pangoLineage=BA.2*

phylogenetic tree of lineage in Lithuania:
https://nextstrain.org/groups/neherlab/ncov/lithuania?c=gt-nuc_20371,21054,22570&f_country=Lithuania&r=country

<img width="999" alt="Screenshot 2022-03-31 at 10 21 59" src="https://user-images.githubusercontent.com/1536822/161000308-cc722240-066b-4f51-905e-c8e7b63c55e5.png">

**Comment by corneliusroemer** [comment]
Thanks!

I think Pango currently reuqires amino acid mutations to delineate lineages

Given that this lineage is a child of the yet undesignated ORF3a:78Y lineage, it would be good to first designate that parent lineage. Otherwise there would be need for renaming with ensuing confusion.

I should close https://github.com/cov-lineages/pango-designation/issues/390 and reopen https://github.com/cov-lineages/pango-designation/issues/432 so that that one gets designated.

**Comment by evogytis** [comment]
I didn't know about the amino acid change requirement and it doesn't seem to be in the pango docs yet either. My understanding was that the nomenclature isn't just meant for VOC candidates but also for epi purposes (here, a geographically confined lineage). If I recall Q.1 was designated with synonymous mutations too.

But entirely fair point re: #432.

**Comment by yexiao-cheng** [comment]
I'm not sure if it's appropriate to comment here. But it reminds me of another non-synonymous mutation of BA.1, 5515T. The number of BA.1 + 5515T is 70,000+, and it has not been designated as a lineage.

Here's a covSpectrum query to track this lineage:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=5515T&pangoLineage=BA.1

<img width="1578" alt="截屏2022-04-01 16 30 01" src="https://user-images.githubusercontent.com/87927817/161226105-3471d069-76c0-4a43-bf7f-c5d176625f4e.png">

**Comment by chrisruis** [comment]
Thanks @evogytis We have recently introduced a requirement for at least one nonsynonymous mutation for a Pango lineage, apologies that hasn't made it into the documentation yet

Just looking at this clade and it doesn't look like there's a suitable nonsynonymous mutation going upstream from the clade either. These sequences will be in the newly designated BA.2.9 which starts on the branch with C25624T (Orf3a:H78Y)
