### ISSUE TITLE
Possible misclassification of recombinant Omicron lineage XK as XE by Nextclade_pango lineage

### ISSUE THREAD

**Issue by FrederikVanHoecke** [cov-lineages/pango-designation#493]
We notice that lineage XK (#460) is currently being mis-classified as XE in the Pango lineage build in the online Nextclade tool v1.14.0 on March 31, 2022

We recently identified > 20 recombinant sequences geographically centered around Roeselare, Belgium. These were finally assigned as recombinant XK (BA.2 acceptor; BA.1.1 donor).  Recently, the online Pango lineage classifier in the Nextclade webtool reports recombinant lineages.  Our initial sequences were reported in issue #460 

We now notice however that our XK strains are not correctly classified by Nextclade-Pangolin but are reported as XE. Manual inspection shows that our XK sequences clearly do not have the key mutations (e.g. C14599T) defining XE as defined in #454 

This could lead to epidemiological underestimation of XK. 

Below the current Nextclade re-analysis of the XK sequences and their labeling as XE:  

![image](https://user-images.githubusercontent.com/102652885/161088358-0b46c9ea-dbc0-48ba-8c8c-9ef0d89f1038.png)

The initial set of submitted sequences: 
Gisaid references:

EPI_ISL_10892048
EPI_ISL_10892049
EPI_ISL_10892050
EPI_ISL_10892051
EPI_ISL_10892052
EPI_ISL_10892053
EPI_ISL_10892054
EPI_ISL_10864854
EPI_ISL_10864857
EPI_ISL_10864858
EPI_ISL_10864920
EPI_ISL_10864921
EPI_ISL_10864925
EPI_ISL_10865165

Geert A. Martens and Frederik Van Hoecke, AZ Delta General Hospital

**Comment by corneliusroemer** [comment]
Hi Geert and Frederik,

new recombinants that are not part of the Nextclade reference tree (yet) will sometimes get assigned to a similar recombinant that is already in the tree.

The many reversions and labeled mutations are a sign that these sequence are likely not XE.

We've just released a new dataset for Nextclade that includes XK, so all these sequences should now be correctly classified as XK.

See https://github.com/nextstrain/nextclade/issues/760 for more details on limitations of Nextclade's pango feature.

In particular this excerpt:

>Recombinants: Recombinant Pango lineages are now included in the reference tree. Each recombinant is attached to the root node so as not to spawn false internal nodes in the tree that would attract bad sequences. As long as recombinants do not qualify for a Nextstrain clade, they will receive the place holder clade name recombinant. Pango lineages are provided if present. Beware that new unnamed recombinants with similar donors but slightly different breakpoint will attach to existing recombinants in the reference tree and thus get a wrong Pango lineage. A number of reversions and labeled mutations is a sign that you may have a similar but different recombinant.
https://github.com/nextstrain/nextclade_data/blob/master/CHANGELOG.md#sars-cov-2

**Comment by SVN-PhD** [comment]
You may want to open/check this issue instead at the NextClade GitHub page: https://github.com/nextstrain/nextclade/issues

NextClade just had a new release this morning and now includes XG-XK so you may want to rerun your analysis.
