### ISSUE TITLE
BA.1.1 lineage with ORF1b:G1093S  particularly common in Kenya (70%) [22k seq worldwide]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#494]
Looking for BA.1.1 sublineages with defining amino acid mutations, I noticed a lineage with `ORF1b:G1093S` that has around 22k sequences worldwide and was very wide spread particularly in Kenya, where it reached 70%

<img width="2530" alt="image" src="https://user-images.githubusercontent.com/25161793/161096276-4e6bb5ee-2bbe-4246-ab4a-694f38835259.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=G16744A&pangoLineage=BA.1.1*&

It may have had a very small growth advantage over base BA.1.1, making up some 3-4% of worldwide BA.1.1 sequences

<img width="942" alt="image" src="https://user-images.githubusercontent.com/25161793/161096950-41ea711f-e204-4b7d-8335-e7571cb6771d.png">

**Comment by corneliusroemer** [comment]
One challenge for designating this (in my view designation worthy lineage) is that BA.1.1.4 seems to be a child lineage of this lineage - so there'd be a need for renaming of BA.1.1.4 or withdrawal.

Alternatively, one could just broaden BA.1.1.4 to this lineage.

I do think it makes more sense to designate the broader lineage which makes up a much more significant share of BA.1.1 (4%) than the narrower one (0.3%).

**Comment by chrisruis** [comment]
Thanks @corneliusroemer As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

This is the UShER tree for this clade coloured by country:
![image](https://user-images.githubusercontent.com/47785131/163406587-9eb14acd-0343-4af3-90da-cfa828d7e116.png)

There doesn't seem to be a clear epidemiological event associated with this clade. As it's widespread elsewhere, the high frequency in Kenya isn't sufficient to constitute an epidemiological event in this case. We therefore haven't designated this at this point
