### ISSUE TITLE
Proposal for new sub-lineage of BA.2.3 with C23591G (S: Q677E) in Japan

### ISSUE THREAD

**Issue by takaabe8050** [cov-lineages/pango-designation#495]
By Takashi Abe (Niigata University, Japan COVID-19 Open Data Consortium)

Description
Sub-lineage of: BA.2.3 (99 sequences)
Earliest sequence: 2022/01/10 (Japan/PG-186077/2022, Japan/PG-186076/2022)
Most recent sequence: 2022/03/15 (Vietnam/BMH-280322-sample22/2022)
Countries circulating: Japan (97 sequences), England (1), Vietnam (1)

Associated mutations
C23591G (S: Q677E)

Genomes
[genome_list.txt](https://github.com/cov-lineages/pango-designation/files/8391355/genome_list.txt)

Evidence
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_167fe_5ca840.json?c=userOrOld

![Tree](https://user-images.githubusercontent.com/89957075/161104711-37abd037-5495-423b-884d-1370cd21fbc5.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C23591G&pangoLineage=BA.2*

Proposed lineage name
Next BA.2.3.X

**Comment by corneliusroemer** [comment]
BA.2.3 is about 50% of all BA.2 in Japan (it's nearly 100% in Philippines)

This mutation is roughly 20% of BA.2.3 in Japan or 10% of all sequences in Japan at the moment. So more significant than the raw numbers may make it sound like (100 isn't very much in the grand scheme of things)

This is maybe some sort of epistasis since Omicron already has mutations at 679 and 681, now adding 677 on top. Interesting triplet.

**Comment by corneliusroemer** [comment]
Interesting, yes! I quickly checked with covSpectrum, S:Q677 is mutated in about 80k sequences or 1% of all.

Those mutations with >0.1% share are:  H (85%), P (6%), R (1%) , L (0.3%), K (0.2 %), not counting the 6% deletion as that's probably artefact. S:677E has only a 0.01% share.

Now with Omicron it looks as follows of 1k sequences with S:Q677 mutated:
S:Q677H (83.21%, 0.01)
S:Q677E (9.62%, 0.10)
S:Q677R (4.16%, 0.02)
S:Q677K (1.22%, 0.01)
S:Q677L (0.90%, 0.01)
S:Q677P (0.16%, 0.00)

**Comment by chrisruis** [comment]
Thanks @takaabe8050 We've added this as BA.2.3.1 in [v1.2.140](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.140)
