### ISSUE TITLE
BA.2 with ORF1b:S959P [50% in India, 3% of global BA.2]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#496]
I think it's worth designating BA.2 with ORF1b:S959P 

It doesn't seem to be in a currently designated sublineage of BA.2

It makes up a large fraction of all BA.2 in India, about 3% of all global BA.2

<img width="860" alt="image" src="https://user-images.githubusercontent.com/25161793/161127548-be7266e8-e648-425f-9b61-97c7348285fb.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3AS959P&pangoLineage=BA.2*

It's also very common in Australia, New Zealand and Japan.

**Comment by chrisruis** [comment]
Thanks @corneliusroemer I agree this is worth designating. The mutation was a bit jumpy in older UShER trees which is why I haven't added it before. But it now looks much cleaner. So we've added this as BA.2.10 in [v1.2.140](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.140)

**Comment by FedeGueli** [comment]
Orf1b:S959P is still around in XDV.1 and it is still the one acquired with BA.2.10 here, going to be BJ.1 then , recombining w BA.2.75 to become XBB >> XBB.1.19.1 >> GW.5 and then recombining again with FL.13.4* to become XDE and then recombining with JN.1 to become XDV and then XDV.1 .
We usually thought that Orf1b:S959P could have been deleterious but with such of a story of recombinations being conserved and then successful i doubt it is .
I am not sure but could be the oldest, not belonging to defining BA.2 mutations, to be around?
