### ISSUE TITLE
Recombinant of BA.2 harbouring BA.1.1 Spike

### ISSUE THREAD

**Issue by fabou-uobaf** [cov-lineages/pango-designation#498]
**Recombinant between:** BA.2 | BA.1.1 | BA.2 
**Earliest sequence:** 2022/3 (Europe / Austria / Burgenland) 
**Most recent sequence:** 2022/3 (Europe / Austria / Burgenland) 
**Countries circulating:** Austria 
**Sequences:** EPI_ISL_11592505, EPI_ISL_11626468 
**Likely break points:** BA.2 <<== ORF1b 17410-18163 ==> BA.1.1 <<== Spike 24130 - 24503 ==> BA.2 

We identified two sequences from different patients in the province of Burgenland (Austria) with a mutation pattern indicating a recombination event between BA.2 and BA.1.1, with two breakpoints. Spike and 3’ end of the ORF1b, appear to be of BA.1 origin, while the remaining 5’ and 3’ legs appear to be of BA.2 origin (see Fig. 1,2). Given the frequencies of variant defining mutations observed in the sequencing reads are consistently close to 1 (> 0.97), and that we only find sporadic mutations at low frequencies in the reads (< 0.07), a contamination/coinfection scenario appears unlikely. Examining the phylogenic neighborhood with UShER discloses two Spanish (EPI_ISL_10716853, EPI_ISL_10716861) and one English (EPI_ISL_11037709) sequence with similar irregular mutation pattern (Figure 3) although the BA.1.1 insertions are larger according to sc2rf. 

 

**Figure 1: SC2RF ([https://github.com/lenaschimmel/sc2rf]) assessment of the two lineages:** 
![sc2rf_soi](https://user-images.githubusercontent.com/11571552/161220068-4947729c-d693-40f3-9c76-fda9265b4b21.png)

 

**Figure 2: Mutations classified by lineage with variant frequency in sequencing reads, and read coverage:** 
![26216](https://user-images.githubusercontent.com/11571552/161220092-d99de485-887f-48ce-97b4-bebe72c80819.png)
![26150](https://user-images.githubusercontent.com/11571552/161220189-385dd97e-3947-46c3-b64a-7b48da2fe364.png)

 

**Figure 3: usher placement of respective sequences** 

![UShER](https://user-images.githubusercontent.com/11571552/161220413-f58a677e-c9c6-40fe-8273-33231e987200.png)

 
**Changes from Wuhan WIV04 (EPI_ISL_402124 versus EPI_ISL_11592505):** 

- C241T 
- T670G		ORF1AB:S135R 
- C2790T		ORF1AB:T842I 
- C3037T		_ORF1AB:F924F_ 
- G4184A		ORF1AB:G1307S 
- C4321T		_ORF1AB:A1352A_ 
- C9344T		ORF1AB:L3027F 
- A9424G		_ORF1AB:V3053V_ 
- C9534T		ORF1AB:T3090I 
- C9866T		ORF1AB:L3201F 
- C10029T	ORF1AB:T3255I 
- C10198T	_ORF1AB:D3311D_ 
- G10447A	_ORF1AB:R3394R_ 
- C10449A	ORF1AB:P3395H 
- GTCTGGTTTT11287G	ORF1AB:S3675_F3677del 
- C12880T	ORF1AB:I4205I 
- C14408T	ORF1AB:P4715L 
- C15714T	_ORF1AB:L5150L_ 
- C17410T	ORF1AB:R5716C 
- A18163G	ORF1AB:I5967V 
- C21762T	S:A67V 
- ATACATG21764A	S:H69_V70del 
- C21846T	S:T95I 
- GGTGTTTATT21986G	S:G142_Y145delinsD 
- AATT22193A	S:N211_L212delinsI 
- T22204TGAGCCAGAA	S:R214insEPE 
- G22578A	S:G339D 
- G22599A	S:R346K 
- TC22673CT	S:S371L 
- T22679C	S:S373P 
- C22686T	S:S375F 
- G22813T	S:K417N 
- T22882G	S:N440K 
- G22898A	S:G446S 
- G22992A	S:S477N 
- C22995A	S:T478K 
- A23013C	S:E484A 
- A23040G	S:Q493R 
- G23048A	S:G496S 
- A23055G	S:Q498R 
- A23063T	S:N501Y 
- T23075C	S:Y505H 
- C23202A	S:T547K 
- A23403G	S:D614G 
- C23525T	S:H655Y 
- T23599G	S:N679K 
- C23604A	S:P681H 
- C23854A	S:N764K 
- G23948T	S:D796Y 
- C24130A	S:N856K 
- A24424T	S:Q954H 
- T24469A	S:N969K 
- C25000T	_S:D1146D_ 
- C25584T	_ORF3a:T64T_ 
- C26060T	ORF3a:T223I 
- C26270T	E:T9I 
- C26577G	M:Q19E 
- G26709A	M:A63T 
- C26858T	_M:F112F_ 
- A27259C	_ORF6:R20R_ 
- GAT27382CTC	ORF6:D61L 
- C27807T	ORF7b:L18L 
- A28271T 
- C28311T	N:P13L 
- GGAGAACGCA28361G	N:E31_S33del 
- GG28881AA	N:R203K 
- G28883C	N:G204R 
- A29510C	N:S413R

**Comment by luenling** [comment]
Just an excel sheet with sequence changes from WT found in GISAID in the lineages BA.1, BA.1.1, BA.2 and BA.3 in more than 30% of sequences and the changes found in EPI_ISL_11592505:
[EPI_ISL_11592505_markers.xlsx](https://github.com/cov-lineages/pango-designation/files/8396609/EPI_ISL_11592505_markers.xlsx)
In the EPI_ISL_11592505 column changes found in the sequence are indicated by 1/green, markers missing by 0/red, in the columns BA.1, BA.1.1, BA.2 and BA.3, the frequency of each marker in GISAID is given. If the frequency of the marker is below 10% the field is left blank.
For found and missing markers, markers unique to BA.1* are colored blue, markers unique to BA.2 orange, shared mutations green. 
While sc2rf finds two BA.2 specific markers (S:K417N and S:N440K) within the BA.1.1 region, in the GISAID alignments we find these markers at also in >70% of BA.1.1 sequences and >60% of BA.1.
The markers are just extracted from the GISAID alignment file from 2022-03-15 using the GISAID lineage designations from 2022-03-27

**Comment by fabou-uobaf** [comment]
To corroborate our findings that the virus isolates are indeed results of a recombination event, we re-sequenced the same samples in duplicates on a nanopore device. we could reproduce all consensus sequence mutation patterns (see sc2rf analysis and allele frequency plots of marker mutations above). 
furthermore we could produce individual reads harboring the genotype pattern as expected from a recombination event between BA.1.1 and BA.2 (C24130A from BA.1.1 & C24503C from BA.2) for the second breakpoint (Spike 24130 - 24503). In numbers, we found 131 and 624 supportive reads for duplicated sample 1 and in 249 and 224 reads for duplicated sample 2, respectively. this substantiates the conclusion that a real recombination event took place. 
For the first break point (ORF1b 17410-18163) no reads spanning marker mutation side on both side of the break point were produced.

**Comment by chrisruis** [comment]
Thanks @fabou-uobaf I can't see any more recent sequences from this. While the breakpoints are interesting, we'd need [more sequences](https://www.pango.network/pango-lineages-guidelines-for-suggesting-novel-and-recombinant-lineages/) for a lineage designation so will close this for now
