### ISSUE TITLE
Proposal for a Potential BA.2.x with Spike S704L (2.2k Seqs), and Its Potential sublineage with Additional Spike L452Q (240 Seqs)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#499]
### Description
**Potential sublineage of**: BA.2
**Earliest sequence**: 2021/12/06 (India)
**Most recent sequence**: 2022/3/25 (UK, Belgium, Denmark)
**Mutation on top of BA.2**: S:S704L (it's interesting that BA.1 also has a sublineage with S:S704L, which appears to have some growth advantage over original BA.1 in Brazil)
Countries circulating: India, UK, US, Belgium, Denmark, Germany, etc.
![image](https://user-images.githubusercontent.com/86835836/161219789-070ff641-b4bd-4cf1-83d3-912d33fda6a6.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants/international-comparison?aaMutations=S%3A704L&pangoLineage=BA.2*&nucMutations1=A2832G%2CG4184A%2CG10986A%2CA29510C

### Evidence
**Usher tree** (BA.2+S:S704L in yellow color, and BA.2+S:S704L+S:L452Q in blue color):
![image](https://user-images.githubusercontent.com/86835836/161220170-bec21d47-b671-41f2-912b-ecf66e68720a.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31cfc_5d5e70.json?c=gt-S_452,704&l=radial&label=nuc%20mutations:C241T,T670G,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10029T,C10198T,G10447A,C10449A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,G22992A,C22995A,A23013C,A23040G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25416T,C25584T,C26060T,C26270T,C26577G,G26709A,C26858T,A27259C,G27382C,A27383T,T27384C,C27807T,A28271T,C28311T,G28881A,G28882A,G28883C,A29510C

### Genomes:
[BA.2+S704L.csv](https://github.com/cov-lineages/pango-designation/files/8395905/BA.2%2BS704L.csv)

**Comment by c19850727** [comment]
I'd also like to propose a potential sublineage of #499 predominantly found in Canada and the US, with an additional Spike L452Q.

**Potential sublineage of**: #499
**Earliest sequence**: 2022/1/20 (Canada-AB
**Most recent sequence**: 2022/3/22 (US-NJ)
**Mutation on top of BA.2**: S:S704L, S:L452Q
**Countries circulating**: predominantly US and Canada

### Evidence:
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/161225165-7e42085a-9bff-402f-874c-34aafaae8852.png)

**Comparison between BA.2, BA.2+S:S704L, and BA.2+S:S704L+S:L452Q, in North America in recent 3 month**:
![image](https://user-images.githubusercontent.com/86835836/161225570-b9d25986-dc7e-4797-90c0-c2b957da814d.png)

### Genomes:
[BA.2+L452Q.csv](https://github.com/cov-lineages/pango-designation/files/8395993/BA.2%2BL452Q.csv)

**Comment by FedeGueli** [comment]
Looking at covspectrum relative growth advantage of BA.2+S:704L,452Qin New York (the only one with sufficient sequences for a minimun estimate) is around +42% vs BA.2

https://cov-spectrum.org/explore/United%20States/AllSamples/from=2022-02-01&to=2022-04-01/variants?pangoLineage=BA.2*&aaMutations1=S%3A704L%2CS%3A452Q&pangoLineage1=BA.2*&analysisMode=CompareToBaseline
![newplot (1)](https://user-images.githubusercontent.com/87669813/161229588-41d88c88-9c2f-4111-947a-002d3133248c.png)

But it seems on the rise as share of total BA.2 seqs everywhere it popped up

**Comment by corneliusroemer** [comment]
The 704 one is definitely worth designating immediately. There's also a BA.1 sublineage with it: BA.1.9

**Comment by silcn** [comment]
> But it seems on the rise as share of total BA.2 seqs everywhere it popped up

... but not in Canada where it appears to have originally arisen, so I think it's too early to declare this as having a significant advantage. The USA branch has an additional two silent mutations T15009C and C21721T but those shouldn't cause it to behave differently. There is a Canadian sequence from 2022-01-27 in this branch that predates all the USA ones (earliest being 2022-02-09), so it looks like it was imported to the USA in late Jan/early Feb, and then maybe took off by chance in NY in early March when case numbers were very low.

**Comment by FedeGueli** [comment]
> > But it seems on the rise as share of total BA.2 seqs everywhere it popped up
> 
> ... but not in Canada where it appears to have originally arisen, so I think it's too early to declare this as having a significant advantage. The USA branch has an additional two silent mutations T15009C and C21721T but those shouldn't cause it to behave differently. There is a Canadian sequence from 2022-01-27 in this branch that predates all the USA ones (earliest being 2022-02-09), so it looks like it was imported to the USA in late Jan/early Feb, and then maybe took off by chance in NY in early March when case numbers were very low.

yes  true! thank you very much i was meaning in the other states of united states

**Comment by RajLABN** [comment]
Just saw this.. I will close mine

**Comment by FedeGueli** [comment]
306 sequences now 277 in Usa  for BA.2 with S:452Q, S_704L

**Comment by corneliusroemer** [comment]
Thanks @c19850727 this has been included in v1.3 as BA.2.12 and BA.2.12.1

**Comment by animesh-workplace** [comment]
Which one is BA.2.12 - S:452Q or S704L?

**Comment by FedeGueli** [comment]
BA.2.12 is S:704L BA.2.12 is S:704L + S:452Q
@animesh-workplace

**Comment by c19850727** [comment]
Just found there are 2 sequences of potential BA.1*+BA.2.12.1 recombinant, with likely breakpoint bwtween 10448 and 12879 (which is interestingly very similar to XE).
**Genomes**: EPI_ISL_12595963, EPI_ISL_12612080.
**Private mutations**: C7564T, A23440G
