### ISSUE TITLE
BA.1 sublineage with N:P67S prominent in US, Canada [5%, 30k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#502]
I've tried to systematically identify BA.1 sublineages worth designating. This is one of them:

BA.1 sublineage with N:P67S prominent in US, Canada [5%, 30k seq]

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=N%3AP67S&pangoLineage=BA.1

**Comment by chrisruis** [comment]
This looks like the same clade as proposed in #375 Now added as BA.1.20
