### ISSUE TITLE
Spanish BA.1.17 sublineage with ORF1a:P1803S [~50%, 20k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#503]
I've tried to systematically identify BA.1 sublineages worth designating. This is one of them:

Spanish BA.1.17 sublineage with ORF1a:P1803S. It made up as much as 50% of all sequences at its peak.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AP1803S&pangoLineage=BA.1

**Comment by corneliusroemer** [comment]
Can you explain how it being found first in Spain and being ten fold more common in Spain than elsewhere doesn't constitute an epidemiological event? Maybe we looked at different data as the query could have been outdated?

It's in my eyes very clearly a founder effect or growth advantage.

Here it is again: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=ORF1a%3AP1803S&pangoLineage=BA.1*&

![Screenshot_20220414-151213~2.jpg](https://user-images.githubusercontent.com/25161793/163398328-d4bb4793-5926-4d19-9df7-bd318da02548.jpg)

**Comment by corneliusroemer** [comment]
This single lineage was found in Spain before Omicron was even known off.

15% in one Region by end of November. It must have neem exported around Europe from there given it never got such a head start anywhere else.

Up to 80% in one Region.

Even in Spain there's a clear clustering in one region.

![Screenshot_20220414-151915~2.jpg](https://user-images.githubusercontent.com/25161793/163399980-28427c09-09e2-4203-a5a1-5a41dc58a4bf.jpg)

![Screenshot_20220414-152057~2.jpg](https://user-images.githubusercontent.com/25161793/163399990-eae24cdb-f579-48c3-987e-562d0739bfe4.jpg)

**Comment by chrisruis** [comment]
Hey Cornelius, this is what the UShER tree looks like in this region coloured by country:
![image](https://user-images.githubusercontent.com/47785131/163402715-e7c6b3f5-b6a2-408e-aac7-1b28666aad6f.png)

The clade is broadly spread geographically and the Spain sequences are spread amongst it so aren't monophyletic within the clade which doesn't support a designation in this case
