### ISSUE TITLE
BA.1.15 sublineage with ORF3a:S165F common in Mexico, US [5%, 20k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#504]
I've tried to systematically identify BA.1 sublineages worth designating. This is one of them:

BA.1.15 sublineage with ORF3a:S165F common in Mexico, US [5%, 20k seq]

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF3a%3AS165F&pangoLineage=BA.1

**Comment by chrisruis** [comment]
Thanks @corneliusroemer Looking at this clade on covSpectrum in [USA](https://cov-spectrum.org/explore/United%20States/AllSamples/from=2021-10-01&to=2022-04-14/variants?pangoLineage=BA.1.15*&aaMutations1=Orf3a%3A165F&pangoLineage1=BA.1.15*&analysisMode=CompareToBaseline&) and [Mexico](https://cov-spectrum.org/explore/Mexico/AllSamples/from=2021-10-01&to=2022-04-14/variants?pangoLineage=BA.1.15*&aaMutations1=Orf3a%3A165F&pangoLineage1=BA.1.15*&analysisMode=CompareToBaseline&), it looks like this clade has been at a relatively consistent proportion of BA.1.15 in both locations for the past few months

For an epidemiological event based on an increase in frequency, we ideally need to see a sustained increase in frequency compared to the parental and/or other co-circulating lineages. We therefore haven't designated this at this stage
