### ISSUE TITLE
BA.1 sublineage with ORF7b:E3*, common in Norway (30%), Italy, South Africa [7k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#505]
I've tried to systematically identify BA.1 sublineages worth designating. This is one of them:

BA.1 sublineage with ORF7b:E3*

It reached 30% of all sequences in Norway at peak. Was also fairly common in Italy (7%) and South Africa (5%).

It's interesting because it shows that ORF7b can be truncated right at the start and the virus is still viable.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF7b%3AE3*&pangoLineage=BA.1

**Comment by FedeGueli** [comment]
Yeah probably you are right! even if it reached a relevant share of Omicron in Campania southern italy in the past 3 months.

**Comment by agrimaldi93** [comment]
@FedeGueli thanks for adding me to this conversation.
@corneliusroemer from a first analysis, actually the samples from the lineage proposed in #409 are over 800. Over 500 only from Campania. However they were assigned to several BA.1 sublineages. I should check wether it is just homoplasy or not, although they are still enriched in Campania, Italy, which whould be strange if it is just convergent evolution.
What do you think? Is there something I am missing?
Here are the numbers:
Nation | Number of sequences
-- | --
Germany | 69
Ireland | 1
Netherlands | 2
United Kingdom | 38
Switzerland | 11
Italy (Campania)| 665 (510)
Poland | 3
USA | 4
Norway | 3
Slovakia | 5
Czech Republic | 3
Sweden | 12
Slovenia | 1
France | 6
Liechtenstein | 1
Kenya | 1
Belgium | 3
Israel | 2
Austria | 1
Spain | 2
Romania | 1
Denmark | 4
Croatia | 4



</body>

</html>


The lineages:

Lineage|Number
--|--
BA.1 | 223
BA.1.4 | 2
BA.1.13 | 16
BA.1.14 | 500
BA.1.15 | 73
BA.1.17 | 12
BA.1.13.1 | 2
Unassigned | 5
BA.1.1.1 | 5
BA.1.1.8 | 1
BA.1.9 | 2
BA.1.15.1 | 1

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as BA.1.21 in [v1.4](https://github.com/cov-lineages/pango-designation/releases/tag/v1.4)
