### ISSUE TITLE
Brazilian BA.1 sublineage with ORF1a:A3615V [10%, 3k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#506]
I've tried to systematically identify BA.1 sublineages worth designating. This is one of them:

Brazilian BA.1 sublineage with ORF1a:A3615V [10%, 3k seq]

It seems to be almost solely present in Brazil, albeit at quite high frequency there with 10%, and potentially rising share.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AA3615V&pangoLineage=BA.1

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as BA.1.14.1 in [v1.4](https://github.com/cov-lineages/pango-designation/releases/tag/v1.4)
