### ISSUE TITLE
BA.1 sublineage with ORF1a:Y947H common in Romania, Thailand, UK [13k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#507]
I've tried to systematically identify BA.1 sublineages worth designating. This is one of them:

BA.1 sublineage with ORF1a:Y947H common in Romania, Thailand, UK

No particular geographic concentration, some 5% in Romania, Thailand, and maybe 2% in the UK

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AY947H&pangoLineage=BA.1

**Comment by chrisruis** [comment]
Thanks @corneliusroemer The clade with Orf1a:Y947H was previously designated BA.1.16 as a UK lineage. The Thailand sequences within this were previously designated BA.1.16.1. Just looking through the clade and it looks like there's also a Greece lineage within BA.1.16 which is now designated BA.1.16.2

**Comment by corneliusroemer** [comment]
Right! There seems to have been no issue for this which is I guess why I missed the already designated lineage.
