### ISSUE TITLE
US BA.1.15 sublineage with S:Q628K showing 5% per day growth advantage over BA.1(.15) [2k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#508]
The mutation S:Q628K on top of BA.1 is rather interesting. It's appeared homoplasically in the US and the UK, in both cases showing a clear growth advantage over BA.1.

This is a proposal for the US lineage with S:Q628K. The mutation appeared on top of the BA.1.15 sublineage.

The growth advantage is very clear and sustained.

<img width="2200" alt="image" src="https://user-images.githubusercontent.com/25161793/161269691-1d28dc81-f294-438f-b531-3ac88e4a2408.png">

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/25161793/161269694-c928eaea-6b08-4d81-bb8c-78af07e47fb5.png">

https://cov-spectrum.org/explore/United%20States/AllSamples/Past6M/variants?pangoLineage=BA.1&aaMutations1=S%3AQ628K%2CORF3a%3AL106F&pangoLineage1=BA.1&analysisMode=CompareToBaseline

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as BA.1.15.2 in [v1.4](https://github.com/cov-lineages/pango-designation/releases/tag/v1.4)
