### ISSUE TITLE
Correct B.1.1.7 definition to remove deletions in S, ORF1a

### ISSUE THREAD

**Issue by mkedwards** [cov-lineages/pango-designation#51]
There's a cluster in Michigan that resembles B.1.1.7 very closely except that it lacks S: Δ143–144 and ORF1a: Δ3675–3677 (instead, 3676G/3677F are replaced by a single L).  Presumably what actually happened here is that the founding strain incubated in a single human host for a while, invented N:D3L and a collection of other substitutions, and the deletions happened after that — probably still in the same host.  Somebody took the version without deletions home to Michigan and it didn't get picked up in the US's irregular sequencing until months later.

ORF1a: 3677L is a pretty good marker of the subclade without the deletions.  But functionally I expect it's very similar to B.1.1.7.  It only matters because RT-PCR proxies for actual sequencing that rely on Δ143–144 S-gene target failure will miss this subclade completely.

Undeletions like this simply do not happen, and if anybody knows somebody at nextstrain.org, I'd suggest that they adjust their common-ancestry cost function accordingly.  (Insertions of any kind seem to be vanishingly rare in this virus, which is what you'd expect from its replication architecture.  Very very very rarely, one sees gene duplication events and similar artifacts of degraded template-switching late in the life of an individual replication organelle.  But that's my amateur perspective; ask a coronavirus expert.  Maybe start from https://mbio.asm.org/content/12/1/e03014-20?)

Not sure how to get nextstrain.org to dump a CSV, but you can get to the earliest sequence in their Michigan subsample at https://nextstrain.org/groups/spheres/ncov/michigan?branchLabel=clade&c=gt-ORF1a_3676,3677,3966,265,3352&f_division=Michigan&label=clade:20I/501Y.V1&s=USA/MI-MDHHS-SC23042/2021

<img width="1165" alt="Screen Shot 2021-04-12 at 1 52 57 AM" src="https://user-images.githubusercontent.com/843186/114780097-c9d0f000-9d2b-11eb-949d-076f4d24559a.png">

**Comment by mkedwards** [comment]
(I realize that my ask around fixing indel handling is capital-H-Hard (TM).  But maybe it's worth looking into adding Divvier (https://europepmc.org/article/pmc/pmc6933875) or a comparable MSA-twiddling pass into the Nextstrain pipeline.)

**Comment by rambaut** [comment]
I agree that 'undeletions' will not happen as a simple 'reinsertion' but it is possible for this happen through recombination with another virus in a co-infection. We have seen this already in the UK with some B.1.1.7 derived variants that have 'undeleted' the nsp12 deletion through recombination with other lineages: https://virological.org/t/658

**Comment by rambaut** [comment]
Will take a look and see if recombination is a plausible explanation for this.

**Comment by rambaut** [comment]
One other point - the deletion that causes SGTF marker is the 69-70 deletion which is in the middle of the s gene probe for these tests.

**Comment by rambaut** [comment]
In the example genome I looked at the 69-70 deletion is probably there but been replaced with `N`s: 

<img width="203" alt="image" src="https://user-images.githubusercontent.com/686405/114837133-49fa6280-9dcb-11eb-8bdc-3b746c936ea6.png">

**Comment by rambaut** [comment]
Michigan Department of Health and Human Services seems to be really struggling to sequence and call the consensus at the spike 144 location (also the other deletions) where as the CDC doesn't. I suspect this may be an issue with the bioinformatics pipelines being used:
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/686405/114840691-f722aa00-9dce-11eb-8817-81c18eef0792.png">

**Comment by rambaut** [comment]
This is also the case for the nsp6 deletion:
<img width="975" alt="image" src="https://user-images.githubusercontent.com/686405/114841216-829c3b00-9dcf-11eb-83d1-e2a81b1b88ad.png">

**Comment by rambaut** [comment]
Closing this issue because it is not directly related to lineage proposals.

**Comment by mkedwards** [comment]
Thanks for digging into the raw data.  I agree that there are signs here of a sequence calling problem in one lab.  I'm aware that it's not the Δ69–70 SGTF that's at risk; I was concerned about attempts to discriminate among B.1.1.7/B.1.351/P.1 using Δ143–144 and/or the ORF1a Δ3675–3677 screen mentioned in https://twitter.com/nathangrubaugh/status/1353710736124633090.

I am skeptical about the recombination arguments but parsimony says they don't need debating here.  😃
