### ISSUE TITLE
BA.1.1 sublineage with ORF1a:L3606F [10k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#510]
There's a rather big as of now undesignated sublineage of BA.1.1 with ORF1a:L3606F

This mutation has appeared a large number of times and been a defining mutation for a lot of lineages, starting from B.39, B.40 over many AY like AY.102, AY.46.3...

<img width="1992" alt="image" src="https://user-images.githubusercontent.com/25161793/161270652-b05baeff-c259-439e-8144-6e9e6ea8cb68.png">

<img width="1929" alt="image" src="https://user-images.githubusercontent.com/25161793/161270656-64d59528-788a-4498-9ba5-dffb4f3b5741.png">

**Comment by AngieHinrichs** [comment]
ORF1ab:L3606F is nucleotide 11083, which was one of the original Problematic Sites in https://virological.org/t/issues-with-sars-cov-2-sequencing-data/473:

> We also recommend masking of positions that, despite having strong phylogenetic signal, are also strongly homoplasic. These may be caused by hypermutability at certain positions, although it is hard to rule out any possibility for now. Our current list is:
> 11083, 15324, 21575.

It has appeared in real lineages, but is also so homoplasic that it causes trouble for tree-building.  

The UCSC/UShER tree is constructed with all [Problematic Sites](github.com/W-L/ProblematicSites_SARS-CoV2) masked in all sequences (after alignment to the reference genome and before being added to the tree by UShER).  So changes at 11083 are unfortunately invisible in the UCSC/UShER tree.

**Comment by corneliusroemer** [comment]
Oh right, the mutation rang a bell. Then I guess it won't be possible to designate this one - not a big issue, I think.
