### ISSUE TITLE
Danish BA.2 (+C22792T) lineage with S:W64L [700 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#512]
I think it would be worth designating a BA.2 sublineage with S:W64L as it could have a growth advantage. It's early to tell, but the mutation popped up in both South Africa and Denmark recently (one needs to see whether this is the same lineage). It's not a mutation that has been observed much before (only some 600 sequences over the pandemic outside of BA.2).

<img width="2503" alt="image" src="https://user-images.githubusercontent.com/25161793/161272393-6d0d1ec6-e5fc-4963-b9e2-7edcea4086ed.png">

<img width="2518" alt="image" src="https://user-images.githubusercontent.com/25161793/161272401-fe5a7e53-301d-4f2e-ac26-7ad83f15f529.png">

**Comment by corneliusroemer** [comment]
Closing in favour of #533

**Comment by corneliusroemer** [comment]
S:W64L has arisen at least twice in BA.2

This proposal is for the Danish lineage.

It's on the global BA.2 branch (9866 mutated) and has the extra syn mut C22792T, so it's well separated from the SA lineage.

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/25161793/162592646-73019755-1ac5-4430-9753-d9c9d13143b3.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_e701_1fdc30.json?c=userOrOld&label=nuc%20mutations:G21753T

Usher is very clean. This should be easy to designate.

It's travelled a bit around the world already.

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/25161793/162592679-a82486a9-40ab-4714-befe-7b8c629cfe75.png">


https://cov-spectrum.org/explore/South%20Africa/AllSamples/Past6M/variants/international-comparison?aaMutations=S%3A64L&nucMutations=9866%2CC22792T&pangoLineage=BA.2*&

**Comment by chrisruis** [comment]
Thanks @corneliusroemer It looks like the increase in this clade as a proportion of BA.2+C22792T in Denmark may have plateaued, difficult to tell at this stage. However, given with the similar increase in the #533 clade in South Africa, agree these 2 clades warrant a designation. We've added this as BA.2.14
