### ISSUE TITLE
Potential BA.2/BA.1.1 Recombinant Lineage with Likely Breakpoint at NSP6-10(3 Seqs in USA-CA as of 2022-04-01)

### ISSUE THREAD

**Issue by emily-smith1** [cov-lineages/pango-designation#513]
### **Description**
**Recombinant between:** BA.2 & BA.1.1
**Earliest sequence:** 2022-02-21
**Most recent sequence:** 2022-02-21	
**Countries circulating:** US-CA
**Likely breakpoint:** 11,538-12,879

Conserved Nuc mutations and AA changes (those in red frames are likely from the donor from the BA.2 side):
![image](https://user-images.githubusercontent.com/84812104/161318871-5b9c098f-7541-4626-ae2d-0daaf237810d.png)

### **Evidence**
**UShER link:** https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_334ea_60e6e0.json?c=userOrOld&label=nuc%20mutations:C2790T,C9866T,T22200G,C24503T

![image](https://user-images.githubusercontent.com/84812104/161318906-6857bd5b-8009-43f6-b2af-a2504e312439.png)

### **Genomes:**
EPI_ISL_10779067, EPI_ISL_10778991, EPI_ISL_10779067

Thanks to @mdperry and @AngieHinrichs for helping confirm this recombinant cluster.

**Comment by chrisruis** [comment]
Thanks @emily-smith1 We've just published some guidelines for recombinant lineages [here](https://www.pango.network/pango-lineages-guidelines-for-suggesting-novel-and-recombinant-lineages/). In most cases we expect new recombinant lineages to contain at least 50 sequences, however exceptions to this may arise if the recombinant has particular novelty or significance, with unusual breakpoints and/or parental lineages

It looks like there's still just the 3 sequences in this clade so I'd suggest this is too small for a designation at this stage. I'll close this for now but can reopen if this clade grows in the future
