### ISSUE TITLE
BA.2/BA.1 Recombinant with breakpoint at 20055-21618 detected in travellers arriving in Hong Kong, February 2022

### ISSUE THREAD

**Issue by Koohoko** [cov-lineages/pango-designation#514]
## **Description**

Recombinant between: BA.1 and BA.2
Earliest sequence: 2022-02-01
Most recent sequence: 2022-02-01
Countries circulating: Uncertain (travellers arrived in Hong Kong from Germany via the Netherlands)
Breakpoint: 20055-21618

We detected a recombinant between Omicron subvariants BA.1 and BA.2. It was detected in early Feb from two epidemiologically linked cases. This recombinant has a breakpoint at around the 5' end of spike (20055-21618). 

## **Genomes**
EPI_ISL_11326600 from patient 1, 
EPI_ISL_11326603 and EPI_ISL_9644494 are from patient 2

## **Evidence**

![image](https://user-images.githubusercontent.com/11829095/161382341-c1dfd328-ccb7-4c17-863a-6c2a2b16ee12.png)

**Figure 1. Detection of a BA.1/BA.2 recombinant.** A) Mapping of BA.1- and BA.2- specific SNPs with respect to the reference sequence (Genbank: MN908947.3). BA.1- and BA.2- specific SNPs found in Patients 1 and 2 samples are shown in red and blue boxes, respectively.  The corresponding amino acid changes of these SNPs are also indicated. The putative breaking point is indicated by an arrow. B) Phylogeny of viral RNA sequences 5’ and 3’ to the putative breaking point. The Maximum likelihood tree was generated using IQ-TREE employing the TIM+F+I nucleotide substitution model with Wuhan-Hu-1 (GenBank: MN908947.3) as the outgroup. References sequences, together with their accession numbers in GISAID or Genbank, are shown as indicated. The red node points show strongly supported branches by SH-aLRT and ultrafast bootstrap values. Scale bar indicates estimated genetic distance.

![image](https://user-images.githubusercontent.com/11829095/161382417-aeed19bc-fd97-43a6-99de-76c23e07aa6a.png)

## Experimental evidence
We used Patient 2 sample to clone a RT-PCR product (~2.2k bp) spanning the recombination breakpoint. Both BA.1-specific (19955C/20055A) and BA.2-specific (21618T/21633-21641del) SNPs can be detected in the same plasmid clone, confirming that Patients 1 and 2 were indeed infected by a BA.1/BA.2 recombinant virus.

---

**Comment by c19850727** [comment]
Hi Haogao, EPI_ISL_11645607 and  EPI_ISL_11618715 (both found in Germany by random sampling) might also belong to this recombinant cluster.

**Comment by JosetteSchoenma** [comment]
I think this one, EPI_ISL_11118886, from the Netherlands, from the 4th of march is the same. I will try and run all the found ones through Sc2rf for comparison. It has no BA.2 mutation A20055G, but it does have C21618T, indicating the same breaking point.
![image](https://user-images.githubusercontent.com/94831035/161419730-d33fef99-8a63-4cc0-82e6-81ff94fd7ae6.png)

![image](https://user-images.githubusercontent.com/94831035/161419654-45d12917-9ddd-4566-9440-ee195bde7b15.png)

**Comment by Koohoko** [comment]
Thanks to @c19850727 @JosetteSchoenma 

I did a quick search against the GISAID msa file (version: 2022-04-02), and I found some recently submitted sequences might also belong to this recombinant cluster.

All the sequences likely to have breakpoint around 20055-21618, the sequences includes but not limited to:
EPI_ISL_11618715
EPI_ISL_10856890
EPI_ISL_11277847
EPI_ISL_11045486
EPI_ISL_11368380
EPI_ISL_11367575
EPI_ISL_11118886
EPI_ISL_10264164
EPI_ISL_10560408
EPI_ISL_10624985
EPI_ISL_10993600
EPI_ISL_10317906
EPI_ISL_11529230
EPI_ISL_10567701
EPI_ISL_11393214
EPI_ISL_11148023

![image](https://user-images.githubusercontent.com/11829095/161424189-c76166e1-c3de-4d9b-bc4f-48bc34f60909.png)

I believe there are actualy more sequences from this recombinant cluster but not found by my methods yet (my method is not perfect and I only analysed sequences with >=95% coverage).

Due to GISAID server is under maintenance, I do not have the metadata for these sequences at the moment, I will try to update the results when data is available.

**Comment by JosetteSchoenma** [comment]
Nice picture @Koohoko ! May I ask how you made it?
So, EPI_ISL_11618715 looks different in that picture. @c19850727 
GISAID seems up and running again.

**Comment by JosetteSchoenma** [comment]
I have put the first mentioned plus one of @Koohoko his newest list through Sc2rf from @lenaschimmel .
![image](https://user-images.githubusercontent.com/94831035/161427755-b4139540-81bd-414d-8dd8-aea51ff147f4.png)
![image](https://user-images.githubusercontent.com/94831035/161427778-e05b284b-a967-4589-9967-449ecad21d02.png)
And with showing private mutations.
![image](https://user-images.githubusercontent.com/94831035/161427835-fabd7a0e-157c-4e1e-a3f7-7783d40bee50.png)

**Comment by Koohoko** [comment]
> I have put the first mentioned plus one of @Koohoko his newest list through Sc2rf from @lenaschimmel .
> ![image](https://user-images.githubusercontent.com/94831035/161427755-b4139540-81bd-414d-8dd8-aea51ff147f4.png)
> ![image](https://user-images.githubusercontent.com/94831035/161427778-e05b284b-a967-4589-9967-449ecad21d02.png)
> And with showing private mutations.
> ![image](https://user-images.githubusercontent.com/94831035/161427835-fabd7a0e-157c-4e1e-a3f7-7783d40bee50.png)

Thank you for the analysis, It looks like the HK sequences share many private mutations with the two Germany sequences. 

I used [snippet](https://github.com/aineniamh/snipit) to generate the figure :)

**Comment by chtate** [comment]
Hi, 

We have found in Toulouse a sequence which might also belong to this cluster (GISAID ID: EPI_ISL_14258452). The 1st breakpoint is the same (20055-21618) - even if there is possibly a second BP (26270-26530). And, as we can see on the snipit plot, the sequence has quite diverged from the other ones... Let me know what you think about it ! 

Sc2rf output (with private mutations): 
![image](https://user-images.githubusercontent.com/37915191/183082172-b4a4fca8-5737-4f19-b9bb-9bfc89312809.png)

And Snipit Plot: 
![image](https://user-images.githubusercontent.com/37915191/183082370-b0f48b65-b11d-487a-9165-e7cd28a820d5.png)

**Comment by thomasppeacock** [comment]
I'm going to close this issue for now as it appears to have gone stale and no newer sequences have appeared in the last few months, please feel free to reopen if that changes!
