### ISSUE TITLE
Potential BA.2 sublineage with Spike T883I substitution [204 sequences]

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#516]
BA.2 + Spike T833I

S:T833I substitution has been observed in Alpha and other lineages too (from Cov-Spectrum) - 1410 sequences in total:
B.1.1.7 (33.19%) BA.2 (13.83%) BA.1.1 (7.45%) BA.1 (7.16%)
P.1.14 (4.26%) AY.4 (3.69%) AY.43 (3.62%) B.1.620 (2.98%)
AY.44 (1.70%) P.1 (1.70%) AY.103 (1.63%) P.1.16 (1.63%)
B.1.617.2 (1.42%) AY.122 (1.21%) and others

Cov-spectrum predicts a global growth advantage of 8% for BA.2+T883I vs BA.2 (and 57% vs BA.1.1)
-Regional growth advantage in England is higher but these are still early days (<200 seqs)

![image](https://user-images.githubusercontent.com/98380390/161412073-36051270-9228-48df-ac0d-521d64003f7f.png)

Link: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.2*&aaMutations1=S%3AT883I&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&

Nextstrain cluster: 
![image](https://user-images.githubusercontent.com/98380390/161412106-f1dd25b9-36eb-483e-94a8-ca3b0860c244.png)
Link: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2bf60_91f780.json?c=gt-S_883&l=radial&label=nuc%20mutations:C21846T&p=full

**Comment by FedeGueli** [comment]
In England the only place with a minimum number of sequences to try some analysis its growth advantage is 9% (CI 0-19%).
![Schermata 2022-04-03 alle 12 07 03](https://user-images.githubusercontent.com/87669813/161422475-9a2d1eb2-3d39-4f02-aa5d-b61340b2765a.png)
It seems quite well spread in different countries probably originating northern europe

But the important thing is that it doesnt seem to be monophyletic :
![Schermata 2022-04-03 alle 12 13 47](https://user-images.githubusercontent.com/87669813/161422682-24846ca1-0669-4ff2-956d-a8ecceec19f7.png)
I got 28 subtrees on Usher:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_abe8_972430.json?c=gt-S_883&label=nuc%20mutations:T670G,C2790T,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10198T,G10447A,C12880T,T15240C,C15714T,C17410T,C19955T,A20055G,C21618T,T21762C,T21846C,T22200G,C22673T,A22688G,G22775A,A22786C,A24130C,C26060T,C26858T,G27382C,A27383T,T27384C,A29510C

Dont know if S:T883I is a known problematic site or homoplasic one:
@corneliusroemer @AngieHinrichs maybe could you take a look at this one?

**Comment by chrisruis** [comment]
Thanks @RajLABN It indeed doesn't look like S:883I is monophyletic but it instead occurs in lots of diverse small clades within BA.2 and also in other lineages. So this doesn't look like a reliable marker for a lineage
