### ISSUE TITLE
A BA.1* - BA.2* recombinant in Europe with likely breakpoint at 11538-12879

### ISSUE THREAD

**Issue by Simon-LoriereLab** [cov-lineages/pango-designation#518]
This is likely too early for a Pango designation (less than 15 sequences) but it should be monitored as detected in multiple countries in Europe.

**Recombinant between**: BA.1 & BA.2
**Earliest sequence**: 2022-02-07 (France)
**Most recent sequence**: 2022-03-21
**Countries with genomes**: France, Germany, Belgium, The Netherlands
**Likely breakpoint**: 11538-12879

Conserved Nuc mutations (those in red frames are likely from the donor from the BA.1* side):

![RecFr01](https://user-images.githubusercontent.com/60473383/161444635-1fd26e38-5157-4ac7-9fb6-9da4aee58d74.jpg)

**Genomes and breakpoint visualized with Scarf:**
https://github.com/lenaschimmel/sc2rf
![Sc2rf](https://user-images.githubusercontent.com/60473383/161444645-be320b0d-c598-4ffb-8bf4-ceb7a126cc81.png)
The last sequence has a distinct set of private mutations and might be a recombinant with the same breakpoint.

Usher tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3309e_9d82b0.json

**Genomes:**
EPI_ISL_10137265,EPI_ISL_11248486,EPI_ISL_11370236,EPI_ISL_11217066,EPI_ISL_11140371,EPI_ISL_11673106,EPI_ISL_11407837,EPI_ISL_11021518

We are grateful to our colleagues of the Emergen consortium (Sante Publique France and ANRS-MIE), and in particular the National Reference Center for Viruses of respiratory infections hosted at Institut Pasteur, the CERBA laboratories, and the Bio-Path laboratories. We also acknowledge our colleagues in Germany, Belgium and the Netherlands who contributed sequences of this lineage.

**Comment by chrisruis** [comment]
Thanks @Simon-LoriereLab It looks like this is close to the [50 sequences we need for most recombinant lineages](https://www.pango.network/pango-lineages-guidelines-for-suggesting-novel-and-recombinant-lineages/) but only has a few recent sequences. We therefore haven't added this for now
