### ISSUE TITLE
Potential Delta (21J)-BA.2 recombinantion in Sweden with breakpoint around 15000 [2 Seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#519]
Looking at recombinants close to existing recombinants, I found this doublet of 21J-BA.2 recombinants in Sweden:
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/25161793/161448307-f326da5f-fdd1-4173-ba64-9f61b272dfb5.png">

It's interesting, because so far, only one other potential Delta-BA.2 recombinant has been identified #484 

EPI_ISL_9961950
EPI_ISL_10598675

Sequences are from end of January, beginning of February.

**Comment by chrisruis** [comment]
Thanks @corneliusroemer It doesn't look like any other sequences have been added to this lineage so we won't designate for now but can reopen if this grows in the future
