### ISSUE TITLE
Potential BA.2 sub-lineage with orf3a:D173Y [105 Sequences - Vietnam and other countries]

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#520]
BA.2 + Orf3a:D173Y [mainly Vietnam]

Orf3a:D173Y substitution has been observed in Delta and other lineages too (from Cov-Spectrum) - 629 sequences in total:
B.1.560 (23.21%) **BA.2 (16.69%)** AY.43 (13.20%) B.1 (6.52%) **B.1.1** (6.20%) AY.121 (5.72%) B.1.554 (4.29%) **AY.4** (2.86%)
B.1.36 (2.70%) B.1.1.7 (2.07%) B.1.617.2 (2.07%) **BA.1.1** (1.91%) B.1.2 (1.43%) AY.103 (1.11%) **BA.1** (1.11%)

Cov-spectrum predicts a global growth advantage of 20% for BA.2+Orf3a:D173Y vs BA.2 (80% vs BA.1.1 and 94% vs BA.1)

![image](https://user-images.githubusercontent.com/98380390/161453074-97d9a7ef-1a2c-4ebd-bd19-1956ab232c4d.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.2&aaMutations1=orf3a%3AD173Y&pangoLineage1=BA.2&analysisMode=CompareToBaseline&

Nextstrain cluster-
![image](https://user-images.githubusercontent.com/98380390/161453180-a23e5dc3-ea12-49b0-bb5f-bb0535ca48d5.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1f5a2_a24780.json?branchLabel=aa%20mutations&c=gt-ORF3a_173&label=nuc%20mutations:C25416T

More about this mutation:
ORF3a 171-173 is a conserved diacidic motif ExD [https://journals.asm.org/doi/10.1128/mSystems.00266-20]
Provean tool predicts this mutation to be deleterious

Sequences -
[Vietnam_IDs_ORF3aD173Y.csv](https://github.com/cov-lineages/pango-designation/files/8405801/Vietnam_IDs_ORF3aD173Y.csv)

**Comment by chrisruis** [comment]
Thanks @RajLABN We've added this as BA.2.17 to start on the branch with G25909T (Orf3a:D173Y)
