### ISSUE TITLE
Multiple BA.2 sub-lineages with S:L452M growing in Europe (386 sequences)

### ISSUE THREAD

**Issue by bitbyte2015** [cov-lineages/pango-designation#521]
Several BA.2 sub-lineages appear to have acquired the S:L452M mutation with the largest cluster of around 80 sequences in the UK having a distinct main branch with two additional N mutations. 

![image](https://user-images.githubusercontent.com/36325823/161497882-742ffd0e-0c26-4d80-b745-cc2c67a71a06.png)

However, the emergence of this mutation appears to have occurred independently across multiple branches. The UK sequence that I first noticed with the mutation was the sequence with the highest mutations flagged by my filtering tool with an additional 12 unlabelled private mutations from BA.2 consensus. It also appears to be growing as a proportion of BA.2 in the UK and Belgium

UK growth:
![image](https://user-images.githubusercontent.com/36325823/161499194-79f1df2c-75cb-4b81-980b-0938e9730dee.png)

Belgium growth:
![image](https://user-images.githubusercontent.com/36325823/161499451-caadfa10-bc08-45c4-a48b-41523470659f.png)

Pymol also suggests that some rotamers may be interacting with 493-494 in the RBM. (452 in red, 493-494 in green)
![image](https://user-images.githubusercontent.com/36325823/161499663-cbfa3a6b-71fc-4e02-aa0b-e52b2056a5b9.png)

Finally, it is also worth mentioning that S:452 is also present in #517 which may have risen to dominance in Gauteng province.

Sequence list:
[contributors(4).csv](https://github.com/cov-lineages/pango-designation/files/8407827/contributors.4.csv)

**Comment by FedeGueli** [comment]
The uk branch has orf1a:322R, N:67S,N:412I, S:452M 
97 seqs
with a significant growth advantage vs BA.2* (too early to say if real)
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?aaMutations=N%3A67S%2COrf1a%3A322R%2CN%3A412I%2CS%3A452M&pangoLineage=BA.2*&aaMutations1=S%3A417T%2Corf7a%3A83L&pangoLineage1=BA.2*&

**Comment by corneliusroemer** [comment]
I picked out a few large independent lineages with this mutation. There are independent phylogenetic events
https://docs.google.com/spreadsheets/d/1NpzVP_V-cU_r7xovm1R35eCjTH_B87JGIwXxuZuwCMk/edit?usp=sharing

Issues #530 and #531

**Comment by FedeGueli** [comment]
I gave this issue a second look:

It seems really there are multiple lineages which have acquired S:L452M independently:

The biggest one from Uk with along branch with:
AA :Orf1a:322R, N:67S,N:412I, S:452M  
Nuc: T3610C, T4111C, C15342T, A24433G, C20178T
[tree sublineage 1](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_33bf7_f6cca0.json?branchLabel=aa%20mutations&c=gt-nuc_23767&label=nuc%20mutations:C22792T)
(About this one see my comment just above, with early signal of a potential growth advantage for it)

The second from Central Europe (Belgium) 56 seqs 
with : A23767G then S:L452M then S:D936Y
[Tree Sublineage 2](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_33bf7_f6cca0.json?branchLabel=aa%20mutations&c=gt-nuc_23767&label=nuc%20mutations:C22792T)
![Schermata 2022-04-08 alle 01 30 41](https://user-images.githubusercontent.com/87669813/162335781-4f2e8e71-fa1e-4156-baa0-b28d14e2cb86.png)
[CovSpectrum]( https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?aaMutations=S%3AL452M%2CS%3AD936Y&nucMutations=A23767G&pangoLineage=BA.2*&aaMutations1=S%3AL452M%2CS%3AD936Y&nucMutations1=A23767G&pangoLineage1=BA.2*&)
Showing there an early signal of potential growth advantage

Then a third with  S:L452M , N:Q418H mainly in Denmark 35seqs
CovSpectrum:[See here sublineage 3](https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?aaMutations=S%3AL452M%2CN%3A418H&pangoLineage=BA.2*&aaMutations1=S%3AL452M%2CS%3AD936Y&nucMutations1=A23767G&pangoLineage1=BA.2*&)

And a fourth from Uk 26 seqs with : Orf1a:G146S, Orf1B:1352V, S:L452M 
the half of them have acquired S:1099D
Covspectrum: [See here Sublineage 4](https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?aaMutations=Orf1a%3AG146S%2COrf1B%3A1352V%2CS%3AL452M&pangoLineage=BA.2*&aaMutations1=S%3AL452M%2CS%3AD936Y&nucMutations1=A23767G&pangoLineage1=BA.2*&)

and a fifth in Germany just 13 seqs with  C8266T +C27725T + S:L452M
Tree:[See here Sublineage 5](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_33bf7_f6cca0.json?c=gt-nuc_8266,27735&label=nuc%20mutations:C27735T)

There is  a bunch of minor sublineages without any AA/Nuc mutation beyond S:L452M


cc @corneliusroemer @chrisruis

**Comment by FedeGueli** [comment]
> I picked out a few large independent lineages with this mutation. There are independent phylogenetic events https://docs.google.com/spreadsheets/d/1NpzVP_V-cU_r7xovm1R35eCjTH_B87JGIwXxuZuwCMk/edit?usp=sharing
> 
> Issues #530 and #531

Thanks Cornelius i was working at the same time on this multiple L452M ;)  tell me if delete the comment above or leave it!

**Comment by corneliusroemer** [comment]
All good, we can keep this issue to discuss all not-yet-proposed L452M lineages

**Comment by FedeGueli** [comment]
@corneliusroemer i checked further the undesignated clades with S:452M: no one seems growing. i ll keep monitoring them

**Comment by FedeGueli** [comment]
Spotted another one potentially growing circulating in Uk:
S:452M + Orf1a:505F, 19 seqs, first seq 11/2022

https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?aaMutations=S%3A452M%2Corf1a%3AS505F&

**Comment by corneliusroemer** [comment]
I'll close this as this seems to be a discussion issue and not about a single lineage.

Proposals should be for one single monophyletic lineage to keep things organized.
