### ISSUE TITLE
Potential BA.1*/BA.2 Recombinant with Likely Breakpoint at NSP3/NSP4 (9 Seqs in Japan, Canada and India)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#522]
### Description
**Recombinant between**: BA.1* & BA.2
**Earliest sequence**: 2022/1/20 (Japan ex-India)
**Most recent sequence**: 2022/3/4 (India-Maharashtra)
**Countries circulating**: India (3 seqs in Gurajat and 2 seqs in Maharashtra), Japan (1 seq from imported case with travel history to India)
**Likely breakpoint**: between 6518 and 9343 (NSP3 or NSP4).
**Conserved Nuc mutations** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/161480936-14c0c32b-518e-467e-94e8-4af16f4832b6.png)
**Cov-spectrum query**: A2832G, C25416T, T22792C, T5386G, G5924A, 29510C

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/161492338-ea0c614e-0b16-492b-80e5-f7c16ee91349.png)
(The neighboring branch is XL.)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3207_a713c0.json?c=gt-nuc_25416&label=nuc%20mutations:T22792C

### Genomes:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<body link="#0563C1" vlink="#954F72">

Accession | Virus name
-- | --
EPI_ISL_10495221 | hCoV-19/Japan/IC-4679/2022
EPI_ISL_10523603 | hCoV-19/India/RJ-SMS-ICMR-INSACOG-TS-11049/2022
EPI_ISL_10675556 | hCoV-19/India/RJ-SMS-ICMR-INSACOG-TS-9433/2022
EPI_ISL_10675557 | hCoV-19/India/RJ-SMS-ICMR-INSACOG-TS-9434/2022
EPI_ISL_11664674 | hCoV-19/India/MH-KasturbaMCGM-ICMR-INSACOG-WG3600/2022
EPI_ISL_11664669 | hCoV-19/India/MH-KasturbaMCGM-ICMR-INSACOG-WG3595/2022

</body>

</html>

**Comment by c19850727** [comment]
9 sequences as of 2022-04-10, and found in Canada.

**Comment by c19850727** [comment]
I came across a few other potential BA.1+BA.2 recombinants, mainly from India, and also among imported cases from Japan, Canada, etc.

Those potential recombinants all have similar breakpoints like #522; they also have the conserved mutation **25416T** (many of them also have 22792C), but they don't cluster on Usher tree.

![image](https://user-images.githubusercontent.com/86835836/163570072-4d2828fe-ba28-4c46-a9be-6969d2835e05.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_424a9_8ecd00.json?c=country&gt=nuc.25416T,22792C&label=nuc%20mutations:T4321C&tl=country

**Comment by c19850727** [comment]
Just found from @corneliusroemer 's other proposals that C25416T is a common BA.2 mutation in India and a few other regions. Problem solved I suppose.

**Comment by learithe** [comment]
We saw a sequence that belongs in this group in February in Sydney. EPI_ISL_11993540 hCoV-19/Australia/NSW-ICPMR-23049/2022

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as XU

**Comment by AngieHinrichs** [comment]
Just wanted to note briefly that the two Canada sequences turned up by the cov-spectrum query also have quite a few other mutations that distinguish them from the India, Japan & Australia sequences, and are placed a lot farther out on the branch of miscellaneous BA.1/BA.2 recombinants in the UShER tree.  And I see @chrisruis didn't include the Canada sequences in the designated sequences, so, good.  :)

**Comment by JosetteSchoenma** [comment]
XU
