### ISSUE TITLE
Potential BA.2 sub-lineage with S:I68M [42 sequences, UK]

### ISSUE THREAD

**Issue by olias120676** [cov-lineages/pango-designation#523]
Very small sample at the moment, first detected around 2022-03-01 in England, showing early signs of growth advantage over BA.2.

Samples contain 
S:I68M
ORF1a:G1531R
G4856C
C5806T
A21766G
C25006T

![growth](https://user-images.githubusercontent.com/24962257/161571569-ec7974a1-3ce5-4b96-8265-0c189fd35b9a.png)

![tree](https://user-images.githubusercontent.com/24962257/161571594-8e09644e-31dd-4e7b-8654-c408359408e2.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2fbcd_ae4450.json?c=pango_lineage_usher&label=nuc%20mutations:T670G,C2790T,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10198T,G10447A,C12880T,T15240C,C15714T,C17410T,C19955T,A20055G,C21618T,T21762C,T21846C,T22200G,C22673T,A22688G,G22775A,A22786C,A24130C,C26060T,C26858T,G27382C,A27383T,T27384C,A29510C

**Comment by FedeGueli** [comment]
49 seqs as today

**Comment by corneliusroemer** [comment]
49 is very small for the UK. @olias120676 if you post growth advantage, please do so with respect to BA.2* since all BA.2 will show growth advantage against all sequences. I'll put this on hold for now.

**Comment by chrisruis** [comment]
This has stayed at a very low proportion of UK BA.2 sequences ([covSpectrum query](https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/from=2022-01-01&to=2022-06-13/variants?pangoLineage=BA.2*&aaMutations1=S%3A68M%2COrf1a%3A1531R&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&)) so we haven't added this for now
