### ISSUE TITLE
AY.127 sublineage circulating in the Solomon Islands (34 sequences)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#525]
Proposal for a sublineage of AY.127
Earliest sequence: 2022-01-26
Latest sequence: 2022-03-10

Countries detected: Solomon Islands (33), South Korea ex-Australia (1)

Mutations on top of AY.127:
ORF1b: S69F (defining)
S: G446R, L1063F
and a bunch more ORF1ab and silent mutations.
Most sequences also have either S:Q613H or S:S98F (but not both).

The Solomon Islands are one of the only places where Delta is still circulating, and most of the sequences there are from this sublineage. There are a few Australian sequences from late December and early January that only lack the defining ORF1b:S69F, so this is likely descended from those.

<img width="592" alt="solomon_ay127" src="https://user-images.githubusercontent.com/42699509/161646618-2b3dee53-e1ac-40f3-91a6-fe2e5d7cd3e6.png">

Despite what the tree above shows, the South Korean sequence looks like it could be identical to SOL38312 = EPI_ISL_11207440; seems the tree is messed up by a combination of masking at S:95 and the Solomon Islands sequencing having issues with the N protein.

cov-spectrum query: [https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3A1063F%2CORF1b%3AS69F&pangoLineage=AY.127*&](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3A1063F%2CORF1b%3AS69F&pangoLineage=AY.127*&)

<details><summary>EPI_ISLs</summary>

EPI_ISL_11207425
EPI_ISL_11207426
EPI_ISL_11207429
EPI_ISL_11207432
EPI_ISL_11207433
EPI_ISL_11207434
EPI_ISL_11207435
EPI_ISL_11207438
EPI_ISL_11207439
EPI_ISL_11207440
EPI_ISL_11207444
EPI_ISL_11207448
EPI_ISL_11207449
EPI_ISL_11207450
EPI_ISL_11405554
EPI_ISL_11629670
EPI_ISL_11629672
EPI_ISL_11629673
EPI_ISL_11629674
EPI_ISL_11629676
EPI_ISL_11629677
EPI_ISL_11629678
EPI_ISL_11629679
EPI_ISL_11629680
EPI_ISL_11629681
EPI_ISL_11629682
EPI_ISL_11629684
EPI_ISL_11629685
EPI_ISL_11629686
EPI_ISL_11629687
EPI_ISL_11629688
EPI_ISL_11629689
EPI_ISL_11629690
EPI_ISL_11629691
</details>

**Comment by FedeGueli** [comment]
Great you proposed this. Sakaguchi Hitoshi was monitoring this too 

This should be the acquisition order of the defining mutations:
First S:446R (91seq globally first emerged in India)
then
Orf9B:32L (86Seqs)
then
orf1a:2930L and orf1b:1596I (76seqs)
then
orf1b:348H (68seqs)
then
orf1a:2269A (58 seqs)
then
ORF1a:S2103F (59 seqs but notice that is present just in 27 out of 33 of the Solomon islands seqs and 1/1 of the sequences fron South Korea)
then Orf1b:69F (34seqs: 33 in Solomon islands + 1 SK) 
So probably mutation Orf1b:69F corresponds to the introduction in the Solomon Islands

**Comment by silcn** [comment]
@FedeGueli those are definitely not in the right order. ORF1b:2930L + ORF1b:348H, 1596I + ORF9b:32L are present in about half of all AY.127. Then about a third of that sublineage has ORF1a:2103F. S:446R is the one that takes it down to small numbers.

**Comment by FedeGueli** [comment]
> @FedeGueli those are definitely not in the right order. ORF1b:2930L + ORF1b:348H, 1596I + ORF9b:32L are present in about half of all AY.127. Then about a third of that sublineage has ORF1a:2103F. S:446R is the one that takes it down to small numbers.
> 
> The 6 Solomon Islands sequences "without" ORF1a:2103F have NNNs there. Pretty safe to assume they all have it.

you re totally right i delete that

**Comment by c19850727** [comment]
Yeah @FedeGueli there seems to be 2 distinct AY.127 with convergent S:G446R. The one @silcn found from Solomon Island, Korea and Australia; and another one from India, Hong Kong (imported case, @Koohoko may have some details), US, England and Denmark.

**Comment by FedeGueli** [comment]
> Yeah @FedeGueli there seems to be 2 distinct AY.127 with convergent S:G446R. The one @silcn found from Solomon Island, Korea and Australia; and another one from India, Hong Kong (imported case, @Koohoko may have some details), US, England and Denmark.

thx @c19850727 i totally messed up the tree 

i think the orf1a:2269A  orf1b:69F
S:446K S:L1063F are the def mutations of this lineage.

**Comment by Koohoko** [comment]
> Yeah @FedeGueli there seems to be 2 distinct AY.127 with convergent S:G446R. The one @silcn found from Solomon Island, Korea and Australia; and another one from India, Hong Kong (imported case, @Koohoko may have some details), US, England and Denmark.

Hi @c19850727 you are right, there is one AY.127 imported case detected on early December 2021, which had S:G446R and orf1a:2269A. I believe this case arrived in Hong Kong from Pakistan.
