### ISSUE TITLE
Potential sub-lineage of BA.2 with S:K417T and nuc:C23248T in UK/Ireland (900 seq)

### ISSUE THREAD

**Issue by olias120676** [cov-lineages/pango-designation#528]
Sub lineage of BA.2 with 517 sequences in UK
Contains
S:K417T
A22812C, C23248T
Earliest sequence 2022-02-19 England/ALDP-37C4703/2022

Edit by @corneliusroemer: 70% contains ORF7a:S83L, but there's significant circulation without this mutation

Fairly large potential growth advantage at this stage
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3AK417T%2Corf7a%3As83l&
![growthba 2 20](https://user-images.githubusercontent.com/24962257/162043460-2360e426-1cc8-4de6-af6b-765560071686.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_8938_dd7ed0.json?branchLabel=nuc%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T670G,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,G10447A,C12880T,T15240C,C15714T,C17410T,C19955T,A20055G,C21618T,T21762C,T21846C,T22200G,C22673T,A22688G,G22775A,A22786C,A24130C,C26060T,C26858T,G27382C,A27383T,T27384C

![treeba 2 20](https://user-images.githubusercontent.com/24962257/162043495-5dc5f7a2-4686-4ff4-9847-5d60009c9710.png)

**Comment by FedeGueli** [comment]
Nice catch, this was also found by the model built by @bitbyte2015 , initiallt thought for recombinants, but that seems good in rapid discovery of growing lineages.
So were monitoring this clade.
Looking at BA.2 baseline the potential growth advantage seems between 28% in northern ireland and 40% in England , and it is likely going further down a bit.

**Comment by FedeGueli** [comment]
626 seqs as today

**Comment by corneliusroemer** [comment]
Oh interesting, convergent evolution with #540 which is a really successful BA.3 lineage with S:417T!

**Comment by FedeGueli** [comment]
@corneliusroemer great work on S:417T i disagree on Orf7a::83L.
Remember that B.1.617.2 carry Orf7a:V82A just near that AA. I wouldnt dismiss that mutation as uninfluent (for sure i agree on the designation startimg from the nuc you found) and also AY.122 had orf7a:45L and it became the only AY. to reach top ten of more sequenced delta sub- lineages in more than 3 continents. 
But maybe, you know, it is just that i am biased versus Orf3a Orf7ab and N mutations ;)

**Comment by corneliusroemer** [comment]
I just rediscovered this lineage. Was about to propose but then found it again. @chrisruis could you have a look at designating this one? It has now also been imported into the US and France and keeps growing. It is reasonable that S:417T could help with immune escape.

**Comment by chrisruis** [comment]
Thanks @olias120676 We've added this as BA.2.18 to start on the branch with A22812C (S:N417T) which is likely the first nonsynonymous mutation in this introduction(s) into the UK
