### ISSUE TITLE
British BA.2.9 sublineage with S:L452M and 8 other private mutations (long branch) [129 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#530]
I've been trying to figure out how many times S:L452M happened independently in Europe.

The biggest independent lineage (by number of sequences) is this British one, a sublineage of BA.2.9

It lies on a very long branch which makes it a good candidate for designation.

It's also grown in numbers and proportion of BA.2.9 a lot in the UK, with a rough growth advantage of 5-10% per day.

Mutations: C22916A (S:L452M), A1230G, T3610C, T4111C,  C15342T, C20178T, A24433G, C28472T, G29508T

covSpectrum comparison to BA.2.9: It's now ~2% of BA.2.9 in the UK
<img width="2220" alt="image" src="https://user-images.githubusercontent.com/25161793/162335824-37ce5e2a-9e93-42ba-9f2c-fcbe99e53542.png">

<img width="2101" alt="image" src="https://user-images.githubusercontent.com/25161793/162335831-1ecb028d-0521-437c-a61e-789a50c7bb75.png">

https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past6M/variants?aaMutations=ORF3a%3A78Y&pangoLineage=BA.2*&nucMutations1=T3610C%2CT4111C%2CC15342T%2CC20178T%2CA24433G%2CC28472T%2CG29508T%2CC22916A%2CA1230G&analysisMode=CompareToBaseline&

Usher tree:
<img width="2180" alt="image" src="https://user-images.githubusercontent.com/25161793/162335900-cc60d6c1-17f1-4313-a0ab-f973686f3217.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42356_f72790.json?branchLabel=aa%20mutations&label=nuc%20mutations:A1230G,C28472T,G29508https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42356_f72790.json?branchLabel=aa%20mutations&c=gt-S_452

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as BA.2.9.1 in [v1.4](https://github.com/cov-lineages/pango-designation/releases/tag/v1.4)

**Comment by corneliusroemer** [comment]
To monitor worldwide: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=N%3A412I%2CS%3A452M&pangoLineage=BA.2*&nucMutations1=T3610C%2CT4111C%2CC15342T%2CC20178T%2CA24433G%2CC28472T%2CG29508T%2CC22916A%2CA1230G&

To monitor in UK: https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?aaMutations=ORF3a%3A78Y&pangoLineage=BA.2*&aaMutations1=N%3A412I%2CS%3A452M&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&
