### ISSUE TITLE
Belgian/Dutch BA.2 (+22792T) sublineage with S:L452M (and 23767G) [51 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#531]
The second biggest (by numbers) BA.2 sublineage with S:L452M is this Belgian/Dutch one. Given that probably a smaller proportion of cases is sequenced in Belgium compared to the UK, this lineage might be as big in terms of true numbers.

It's on the BA.2 branch with 22792T, but not part of an existing BA.2 sublineage.

It's got two defining mutations: 22916A (S:452M) and the synonymous private mutation 23767G.

A large part (80%) but not all sequences in this cluster also have S:936Y. Notably, most Dutch ones don't. So I would make this mutation required for this lineage.

This lineage has been observed once each also in UK, Austria, Germany and the US.
<img width="2536" alt="image" src="https://user-images.githubusercontent.com/25161793/162336288-6a09da96-886e-4f3c-80d7-7c3040d7865b.png">

Its share of all sequences is 2% in Belgium and growing.

It makes up about 6% of all BA.2 + 22792T in Belgium. Growth advantage around 5% per day.

<img width="2198" alt="image" src="https://user-images.githubusercontent.com/25161793/162336403-96248958-e540-49d2-aa33-f98d1d87728e.png">

<img width="2094" alt="image" src="https://user-images.githubusercontent.com/25161793/162336407-8abb4a36-8607-4686-a50e-6d33751f064c.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=22792T%2C22916A%2C23767G&pangoLineage=BA.2*&aaMutations1=ORF3a%3A78Y&nucMutations1=A1230G%2CT3610C%2CT4111C%2CC15342T%2CC20178T%2CA24433G%2CC28472T%2CG29508T&pangoLineage1=BA.2*&

Worth designating in my view.

The tree is split in two in Usher, but I think @AngieHinrichs can fix that :) 

![image](https://user-images.githubusercontent.com/25161793/162337026-528ba941-543e-45a9-970e-c6b8b6807ac9.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_19fa0_f76ee0.json?c=gt-S_452&label=nuc%20mutations:T670G,C2790T,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10198T,G10447A,C12880T,T15240C,C15714T,C17410T,C19955T,A20055G,C21618T,T21762C,T21846C,T22200G,C22673T,A22688G,G22775A,A22786C,A24130C,C26060T,C26858T,G27382C,A27383T,T27384C,A29510C

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as BA.2.13 in [v1.4](https://github.com/cov-lineages/pango-designation/releases/tag/v1.4)

**Comment by corneliusroemer** [comment]
To monitor in Belgium: https://cov-spectrum.org/explore/Belgium/AllSamples/Past6M/variants?nucMutations=22792T&pangoLineage=BA.2*&nucMutations1=22792T%2C22916A%2C23767G&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&

To monitor worldwide: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=22792T%2C22916A%2C23767G&pangoLineage=BA.2*&nucMutations1=22792T%2C22916A%2C23767G&pangoLineage1=BA.2*&
