### ISSUE TITLE
Potential sub-lineage of BA.2 with N:Q39L & ORF1a:S2535L in UK (167 seq)

### ISSUE THREAD

**Issue by olias120676** [cov-lineages/pango-designation#532]
Primarily in England (93), but also Scotland (3), Denmark (12), USA (2)
AA mutations: N:Q39L & ORF1a:S2535L
nuc mutations: C7869T, A28389T

Earliest sample: 2022-02-22 England/ALDP-3817621/2022

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=N%3AQ39L%2CORF1a%3AS2535L&nucMutations=C7869T%2CA28389T&

Growth advantage against BA.2* baseline showing as 64% in England
![growthba 2 0804](https://user-images.githubusercontent.com/24962257/162337947-101fb9e7-84ea-49b0-bedc-600eeef5de61.png)

![treeba 2 0804](https://user-images.githubusercontent.com/24962257/162338037-97c7894b-778f-46eb-be35-ef6af48e1739.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_9723_f77410.json?branchLabel=nuc%20mutations&c=gt-N_39&label=nuc%20mutations:T670G,C2790T,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10198T,G10447A,C12880T,T15240C,C15714T,C17410T,C19955T,A20055G,C21618T,T21762C,T21846C,T22200G,C22673T,A22688G,G22775A,A22786C,A24130C,C26060T,C26858T,G27382C,A27383T,T27384C,A29510C

**Comment by FedeGueli** [comment]
Hi @olias120676 good catch!
 it seems on the rise, not surpringly as mutations to L at the start of N protein seem to be associated with high trasmissible lineage (Alpha N:3L, AY.36.1 N:6L, AY.43 N:9L, Omicron N :13L)
Maybe  we will see if it settles down.
You forgot mentioning the Orf1a:R135S reversion present in all these sequences hard to say if it comes from a recombination event with a very early breakpoint in Nsp1 but surely there are more conservative explanations.

@AngieHinrichs @corneliusroemer could you take a look at this tree?

**Comment by corneliusroemer** [comment]
Thanks for pointing this out @FedeGueli, you're right that 670 is reverted back to reference - which is unusual for BA.2* but normal for BA.1

I propose the parental lineage in #546 so this issue should pause until #546 is designated.

**Comment by FedeGueli** [comment]
@corneliusroemer I could confirm this is showing a consistent growth advantage. 
Today it  reached 140 seqs (12/4).
I suggest if possible to accelerate the parental lineage designation: it would be great to have all the lineages showing growth in the few last weeks designated and ready to be monitored via covspectrum and other tools. I understand it isnt easy for this clade to be assigned as sublineage or recomb.

**Comment by corneliusroemer** [comment]
Growth looks interesting indeed. Though it's weird it's almost same share of BA.2 in all of UK, Denmark and US.
Making me think it may be imported from somewhere - that would also be interesting.

![image](https://user-images.githubusercontent.com/25161793/163266398-dece4a0c-6f8f-49a7-af1f-cf8fdb4fb693.png)

![image](https://user-images.githubusercontent.com/25161793/163266403-0f83c22d-9c02-4761-8e15-2116675cc2a6.png)

**Comment by FedeGueli** [comment]
@corneliusroemer @chrisruis please take a second look to this one. I am monitoring it daily and weirdly it seems increasing its growth advantage vs BA.2 all sublineages baseline day after day.

**Comment by FedeGueli** [comment]
Big branch with Orf1a:R135S from #546 now designated  BA 2.23 so this one could be BA.2 23.1.
@corneliusroemer @chrisruis i suggest a fast designation: please check by yourselves the growth advantage this sublineage is displaying in UK vs BA.2 baseline ( keeping in mind what is circulating right now in Uk)

**Comment by FedeGueli** [comment]
![IMG-20220420-WA0022](https://user-images.githubusercontent.com/87669813/164311100-0a0fc9d2-3b0f-4483-ba48-b02e4feadd2f.jpg)

**Comment by silcn** [comment]
@FedeGueli that's a rather misleading graph: the jump to 8% is caused by a grand total of 4 sequences out of a total of 51 from 12 April.

**Comment by FedeGueli** [comment]
@silcn the very last part of the graph is always insignificant for every lineage both  if it goes up or down (i took that screenshot cause i m unable to use covspectrum from this device). The fact is not that last part of the graph but the growth of this sublineage.. The highest in uk actually.. cheers.

**Comment by FedeGueli** [comment]
@silcn i checked again yesterday this one is actually the fastest growing among  the newly designated and undesignated sub lineages of BA.2
![IMG-20220421-WA0004](https://user-images.githubusercontent.com/87669813/164417859-e812e1cb-75e2-4990-81f0-3a55f8fb6453.jpg)
![IMG-20220421-WA0005](https://user-images.githubusercontent.com/87669813/164417880-6d6dc96c-ac9d-47f1-a2d1-bb6114e46c15.jpg)

**Comment by FedeGueli** [comment]
367 seqs today

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.23.1 with 162 newly designated sequences, and 145 updated designations from BA.2.23. Defining mutation(s) A28389T (N:Q39L), C7869T (ORF1a:S2535L).
