### ISSUE TITLE
South African BA.2 with 9866C (wild type) and S:W64L [5%, 70 seq in South Africa, 50 in UK]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#533]
It looks like most of BA.2 in South Africa and Southern Africa in general seems to have nuc:9866C unmutated like the rest of BA.1/3/4/5.

Apparently some nuc:C9866T got lucky through a bottleneck (e.g. travel bans from Southern Africa) and managed to make up 99% of BA.2 globally, despite only ever having reached 20% in Southern Africa.

Here I propose a lineage on this basal part of BA.2, characterized by S:W64L and ORF1a:T3150I.

The clustering is very good in Usher

![image](https://user-images.githubusercontent.com/25161793/162546113-fb2cd698-630c-4e0c-a4e9-1b9228997690.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4ffc_c3f00.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C9714T,G21753T

Here's where it has been observed globally:
![image](https://user-images.githubusercontent.com/25161793/162546142-c1b351d0-a5ec-4c20-8a8d-6b9cebb5e97e.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AW64L&nucMutations=9866C&pangoLineage=BA.2*&nucMutations1=9866C&pangoLineage1=BA.2*&

We're in a bit of a bind re naming for this 9866 wt bunch. It'd be nice if it was distinguishable from the 9866T branch (ORF1a:L3201F) but I guess that ship has sailed? Unless we'd be happy to give this plesiomorphy a name like BA.2.14.

**Comment by silcn** [comment]
> It looks like most of BA.2 in South Africa and Southern Africa in general seems to have nuc:9866C unmutated like the rest of BA.1/3/4/5.
> 
> Apparently some nuc:C9866T got lucky through a bottleneck (e.g. travel bans from Southern Africa) and managed to make up 99% of BA.2 globally, despite only ever having reached 20% in Southern Africa.

This caught me out when I was proposing what became BA.4 and BA.5. ORF1a:F3201L was one of the "reversions" I listed. UKHSA were caught out too, as they stated in today's technical briefing that BA.4/5 have "NSP4: L438F reverted to WT".

**Comment by FedeGueli** [comment]
This is the same proposed by you @corneliusroemer in #512 , here you went on in your analysis i suggest to close #512 .

**Comment by corneliusroemer** [comment]
How could I've forgotten 🤦 

Here is the proposal from #512 

> I think it would be worth designating a BA.2 sublineage with S:W64L as it could have a growth advantage. It's early to tell, but the mutation popped up in both South Africa and Denmark recently (one needs to see whether this is the same lineage). It's not a mutation that has been observed much before (only some 600 sequences over the pandemic outside of BA.2).
> 
> <img width="2503" alt="image" src="https://user-images.githubusercontent.com/25161793/161272393-6d0d1ec6-e5fc-4963-b9e2-7edcea4086ed.png">
> 
> <img width="2518" alt="image" src="https://user-images.githubusercontent.com/25161793/161272401-fe5a7e53-301d-4f2e-ac26-7ad83f15f529.png">
>

**Comment by corneliusroemer** [comment]
They seem to be different lineages in Denmark and UK.

This is the South Africa one, it has 9866C (wild type), S:W64L and ORF1a:T3150I 

Here's UShER
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/25161793/162592540-e08f826f-7ae1-4c9a-847c-123173a0879b.png">

It's in circulation in the UK

<img width="1667" alt="image" src="https://user-images.githubusercontent.com/25161793/162592572-981950a6-f1ca-4c94-8cda-e55286b50704.png">

https://cov-spectrum.org/explore/South%20Africa/AllSamples/Past6M/variants/international-comparison?aaMutations=S%3A64L%2CORF1a%3AT3150I&nucMutations=9866C&pangoLineage=BA.2*&

**Comment by FedeGueli** [comment]
Thx Cornelius! You caught it twice because they are two! great work.

**Comment by chrisruis** [comment]
Thanks @corneliusroemer It looks like the increase in this clade as a proportion of BA.2 in South Africa may have plateaued, difficult to tell at this stage. However, given the similar increase in the #512 clade in Denmark, agree these 2 clades warrant a designation. We've added this as BA.2.15
