### ISSUE TITLE
UK BA.2 + 9866C sublineage with N:T296I [400 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#534]
The biggest BA.2 + 9866C sublineage in terms of sequence numbers with a non-synonymous mutation is this one with N:T296I

![image](https://user-images.githubusercontent.com/25161793/162546761-b8fecc61-895f-4192-b62d-11537c62833e.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=N%3AT296I&nucMutations=9866C&pangoLineage=BA.2*&

May be worth designating to raise awareness of the BA.2 + 9866C part of BA.2

Same considerations as for #533 apply

Clusters perfectly in Usher

![image](https://user-images.githubusercontent.com/25161793/162546935-15a71826-ed84-47ad-93dd-f1691900e4bd.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c673_c7bf0.json?branchLabel=Spike%20mutations&label=nuc%20mutations:C29160T

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as BA.2.16
