### ISSUE TITLE
German BA.2 + 9866C lineage with ORF1a:T333M [400 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#535]
German BA.2 + 9866C lineage defined by ORF1a:T333M [400 seq]

Most common in the South Western state of Baden-Wurttemberg where 278 sequences were found, making up a large share of all BA.2 found there.

![image](https://user-images.githubusercontent.com/25161793/162546973-07a13026-2af6-46c1-b823-3ad137dc6318.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=ORF1a%3AT333M&nucMutations=9866C&pangoLineage=BA.2*&

Clusters well in Usher

![image](https://user-images.githubusercontent.com/25161793/162547183-440f41fc-2057-4567-9295-3329ac6df996.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_db8c_c8c50.json?label=nuc%20mutations:C1263T

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as BA.2.19 to start on the branch with C1263T (Orf1ab:T333M)
