### ISSUE TITLE
UK BA.2 + 9866C lineage with ORF1b:D146G, potentially growing [200 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#536]
UK BA.2 + 9866C lineage with ORF1b:D146G

![image](https://user-images.githubusercontent.com/25161793/162547224-4eef0262-eb8d-43c3-8dc9-6534e1d6999a.png)

![image](https://user-images.githubusercontent.com/25161793/162547221-635a2f0d-b559-4241-9c6d-45a199585695.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3AD146G%2CS%3AD614G&nucMutations=9866C&pangoLineage=BA.2*&aaMutations1=ORF1b%3AD146G&nucMutations1=9866C&pangoLineage1=BA.2*&

![image](https://user-images.githubusercontent.com/25161793/162547622-68c6f384-395e-4a9a-84a0-b1ee15b2178a.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_fc1f_ca310.json?c=country&label=nuc%20mutations:A13904G

**Comment by FedeGueli** [comment]
@corneliusroemer This is the only one of the proposed 9866C showing some signs of moderate growth advantage,  If the parental will be designated it should be the first as sublineage.

**Comment by corneliusroemer** [comment]
There is no parent, BA.2 with 9866C not mutated is ancestral to most BA.2 globally.

**Comment by FedeGueli** [comment]
Yes @corneliusroemer sorry i was meaning that. poor wording by me.

**Comment by chrisruis** [comment]
It's not too clear whether this clade has an epidemiological event. The introduction(s) into the UK occurred a couple of nodes upstream in the tree. The proportion of BA.2 in the UK with Orf1b:D146G did rise initially but quickly plateaued - https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/from=2021-10-01&to=2022-04-19/variants?pangoLineage=BA.2*&aaMutations1=Orf1b%3A146G&nucMutations1=9866C&pangoLineage1=BA.2*&analysisMode=CompareToBaseline& So there isn't a sustained increase in proportion of BA.2 for this clade

So I think we should put a monitor on this for now and check back

**Comment by chrisruis** [comment]
This hasn't exhibited a sustained growth as a proportion of BA.2 in the UK ([covSpectrum query](https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/from=2022-01-01&to=2022-06-13/variants?pangoLineage=BA.2*&aaMutations1=Orf1b%3A146G&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&)) so we won't designate this for now
