### ISSUE TITLE
Belgian BA.2 + 9866C sublineage with S:E111Q [200 seq, 1% in Belgium]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#537]
Belgian BA.2 + 9866C sublineage with S:E111Q [200 seq, 1% in Belgium]

Earliest detection was in Rwanda end of last year. It was only spotted in Europe a month later. So this lineage may be common in Rwanda and connected countries. Interestingly, it's appeared in a number of European countries suggesting multiple introductions.

![image](https://user-images.githubusercontent.com/25161793/162547419-ac6d1158-5ae5-42bd-ad7b-25f5c4f1a8c8.png)

https://cov-spectrum.org/explore/Europe/AllSamples/Past6M/variants?aaMutations=S%3AE1111Q&nucMutations=9866C&pangoLineage=BA.2*&aaMutations1=S%3AE1111Q&nucMutations1=9866C&pangoLineage1=BA.2*&

![image](https://user-images.githubusercontent.com/25161793/162547819-41000a4c-a4fb-442e-b461-61bc78f85ade.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1107b_cb300.json?branchLabel=Spike%20mutations&label=nuc%20mutations:G24893C

**Comment by chrisruis** [comment]
Thanks @corneliusroemer This is the UShER tree for this clade coloured by country:
![issue_537_clade](https://user-images.githubusercontent.com/47785131/163994524-04a2d0d6-4012-44d0-bc3f-8671a07d22c1.png)

There doesn't seem to be a clear epidemiological event associated with this clade so we haven't designated this at this point
