### ISSUE TITLE
South African BA.2 + 9866C lineage with N:T271I (~4% in South Africa, 160 seq worldwide)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#538]
Going through the most common BA.2 + 9866C lineages I found this one common in South Africa with N:T271I

![image](https://user-images.githubusercontent.com/25161793/162548110-005187bd-e6fc-47d9-8191-ada1d226dbf7.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=N%3AT271I&nucMutations=9866C&pangoLineage=BA.2*&aaMutations1=S%3AE1111Q&nucMutations1=9866C&pangoLineage1=BA.2*&

Seems to have spread a little around the world, though most common in South Africa

**Comment by chrisruis** [comment]
Thanks @corneliusroemer This is the UShER tree for this clade coloured by country:
![issue_538_clade](https://user-images.githubusercontent.com/47785131/163998533-731bbf2b-0fab-43e3-af32-4dcdf149211f.png)

Tricky to see but there's 2 shades of green there, South Africa and Denmark, with a few sequences from elsewhere. This clade hasn't exhibited a sustained increase in proportion of BA.2 in either South Africa or Denmark. So there doesn't seem to be a clear epidemiological event associated with this clade and we therefore haven't designated this at this point
