### ISSUE TITLE
Diverged descendant of B.1 with multiple VOC-like mutations and deletions.

### ISSUE THREAD

**Issue by evogytis** [cov-lineages/pango-designation#54]
New lineage proposal
by Gytis Dudas, Guy Baele, Ingrida Olendraitė, Daniel Naumovas

Description
Sub-lineage of: B.1
Earliest sequence: 2021-02-26 (hCoV-19/France/ARA-210013001901/2021)
Most recent sequence: 2021-04-06 (hCoV-19/USA/WV-WVU-WV064773/2021)
Countries circulating: Lithuania (definitely), France (likely), Belgium (likely), United Kingdom (likely), Germany (possible)

Genomes of this lineage initially attracted attention in Lithuania due to having the S:E484K mutation, high numbers of unique mutations in nextclade QC and (incorrect) classification as pango lineage B.1.177.57. Earliest French genome is a travel case coming from Cameroon. We reached out to submitters of other genomes and confirmed that three additional genomes on GISAID are also travel cases arriving from Cameroon. Lithuanian cases are related to travel from France and potentially Belgium, not Cameroon.

Genomes
(Note some genomes are missing characteristic deletions or have excessive number of missing sites)
[lineage_proposal.txt](https://github.com/cov-lineages/pango-designation/files/6334553/lineage_proposal.txt)

Numerous mutations present in this lineage have been observed in other VOCs (lineage in question marked XXXX, mutations unique to it in this plot marked in red):

![VOC-like_muts](https://user-images.githubusercontent.com/1536822/115205901-526bd980-a0fa-11eb-95ee-50f8dc88f398.png)

N:A220V shared with B.1.177 is the likely reason for this lineage's pango lineage misclassification.
Another putative Cameroonian lineage (#44) shares some of these mutations (E484K, T1027I) in common. Distantly related genomes from Cameroon on GISAID also share at least one more synonymous mutation (C15324T).

Evidence
(Proposed lineage at the bottom, dashed outline, only showing sites different from reference in proposed lineage and shared by at least two proposed lineage genomes)
![defining-mutations](https://user-images.githubusercontent.com/1536822/115208209-9bbd2880-a0fc-11eb-8130-83faf9d91b08.png)

**Comment by chrisruis** [comment]
Hi @evogytis thanks for submitting this, we've added this as lineage B.1.620. Its included in [v1.1.16](https://github.com/cov-lineages/pango-designation/releases/tag/v1.1.16)

**Comment by babarlelephant** [comment]
Hi, did you notice the (mis-assigned?) sublineage of B.1.523 having E484K plus all the deletions (ORF1a:S3675-, S:69-, S:143-) ? @evogytis

**Comment by evogytis** [comment]
@babarlelephant I had not, no. It doesn't have the S:241- deletion but the degree of convergence is is still quite striking.
