### ISSUE TITLE
Polish BA.3 sublineage with S:K417T and ORF1a:A1176N  [200 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#540]
There's an interesting RBD mutatation sublineage of BA.3 common in Poland.

S:K417 is usually mutated to N in BA.3, but in Poland another nuc mutation happened that turned it into T

That lineage makes up quite a good proportion of all global BA.3, so it's worth designating for those two reasons: RBD mutation and regional/global relevance.

The Usher tree is clean apart from a bit of back and forth artificially prolonging the branch.

![image](https://user-images.githubusercontent.com/25161793/162551129-4fd764ce-ee80-4a33-9276-93c40e1ddb2b.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_338a0_de240.json?label=nuc%20mutations:C28311T

Interestingly, another double mutation within a codon happened in that lineage: nuc G3791A, and nuc C3792A make ORF1a:A1176N

So this branch is very well separated (by 3 nuc mtuations, and 2 aa mutations)

It's also appeared in a number of countries world wide

![image](https://user-images.githubusercontent.com/25161793/162551164-27cbd021-f909-43f3-bf60-38b55f000e96.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=S%3A417T&pangoLineage=BA.3*&

Hard to tell whether there's a growth advantage

![image](https://user-images.githubusercontent.com/25161793/162551208-579c9320-99e6-4663-9de2-a22b3b28d13e.png)

**Comment by FedeGueli** [comment]
This was spotted very early by @bitbyte2015 too. It deserves a designation , also 417T seems to do very well in BA.2 so probably if something new will evolve from BA.3 this looks like a  perfect candidate.

**Comment by InfrPopGen** [comment]
This has now been added as lineage BA.3.1 with 192 newly designated sequences. Defining mutation(s) A22812C (S:K417T), G3791A, C3792A (both ORF1a:A1176N).
