### ISSUE TITLE
BA.2 (+ C25416T) lineage with S:K417T common in India [>20%] and growing in UK [400 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#541]
It's plausible that BA.2 + S:K417T has a growth advantage. So I went and checked out all the global lineages. There are multiple, which again points to growth advantage.

This is a lineage that appears smaller than the UK one #528, but in fact I think it's bigger because it makes up 2% in India - which has many more cases than UK for sure. It also looks like there's been import into UK from India. There are now 100 sequences from UK.

I think it's definitely worth designating this one.

I checked whether it's clean. It is, it lies on the big BA.2 branch with C25416T (@chrisruis you remember I wanted to give this one a label, but unfortunately it's synonymous). Anyways, this will help show that C25416T is a big branch. The other lineage on it is #499 (BA.2.12(.1)).

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/25161793/162587400-5d63bef6-b06c-4749-8e8a-7399ac90c86b.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_ddae_1d19f0.json?c=gt-nuc_22812&label=nuc%20mutations:C25416T

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/25161793/162587726-6d30f80b-fe7b-4004-83fb-3aa3474a80d7.png">

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants/international-comparison?aaMutations=S%3AK417T&nucMutations=C25416T&pangoLineage=BA.2*&aaMutations1=s%3AK417T%2Corf7a%3As83l&pangoLineage1=BA.2*&

**Comment by silcn** [comment]
[off-topic]
Pretty sure what's happening in Delhi, Haryana and Uttar Pradesh right now is unrelated to this: it's been around too long to cause such a sharp uptick. The realistic options are either BA.4/BA.5 or something new - personally leaning towards something new, as it seems too sharp even for BA.4/BA.5. We should have sequences from Delhi in a week or so but if it is a new lineage I wouldn't be surprised if a sequence turns up somewhere else first.
[/off-topic]

**Comment by silcn** [comment]
Eating my words from two weeks ago right now. 
We just got a big batch of uploads from Delhi and Uttar Pradesh. Looking at April sequences only, 30/113 from Delhi and 57/141 from Uttar Pradesh belong to this lineage. There are only 4 from Delhi and none from Uttar Pradesh in March, so it looks like this lineage is at least partly responsible for the resurgence in cases. Pretty strong case for designation.

There is also a scattering of S:L452M in the Delhi/UP sequences, belonging to a couple of independent lineages, but probably not worth designating at the moment.

**Comment by FedeGueli** [comment]
thx @silcn for the very important update.

@corneliusroemer the sublineage in this issue isnt the same of #581 and #582 (with 6071T) ?

**Comment by AngieHinrichs** [comment]
@corneliusroemer it would be very helpful if in each issue you could provide at least one name/ID of a sequence on the branch you have in mind.  Even with the cov-spectrum links, I can't really tell which sequences/branches you mean for this issue vs. #581 and #582 (thanks @FedeGueli for linking those).  Especially when the link is to a comparison/growth graph, and it takes me a while to notice the "Back to overview" button on the right.  :)  I'm clicking through to UShER so I can try to guess which branches you're referring to in the single subtree view, but that takes a few minutes...  However if you listed a sequence name, I would know exactly what branch you mean.

I think India/GJ-INSACOG-GBRC6525/2022 is at the base of the branch you're referring to in this issue, is that correct?

**Comment by corneliusroemer** [comment]
Oh I see, you designated it, thanks @chrisruis 

If I see it correctly it's all of these, and not just the UK 6061 one

I'll close this and #581 #582 accordingly.

**Comment by Mydtlwn** [comment]
这个毒株目前来说比较难防。

**Comment by Sinickle** [comment]
@Mydtlwn are you involved with disease prevention of a region that has been affected by this variant? If so, does the strain that you're struggling to control have additional mutations? This one, BA.2.38, is not particularly genetically fit by today's standards, but it has a few more genetically fit offspring, particularly ones with S:444N.

**Comment by Mydtlwn** [comment]
@Sinickle There is such a possibility. Before my country, there was very little such growth rate. Except for a few widely known strains of Ba5.2, which have such a rate, this strain arrived relatively quickly. We were surprised, but because of my low status, I can only know that it is Ba.2.38, but I can't be sure which one it is. We have to wait for the notice.

There is such a possibility. Before my country, there was very little such growth rate. Except for a few widely known strains of Ba5.2, which have such a rate, this strain arrived relatively quickly. We were surprised, but because of my low status, I can only know that it is Ba.2.38, but I can't be sure which one it is. We have to wait for the notice.
复

**Comment by Sinickle** [comment]
@Mydtlwn Some of them that just get the normal label of BA.2.38 may have additional mutations, but haven't been given their own name yet. 
Here are the four variations of BA.2.38 that I'm tracking that might be more infectious. 
#746 
#840 
#828 
#809 

I don't believe that regular BA.2.38 should be exceptionally troubling. 
BA.2.38 has the mutation S:K417T. This mutation is also in BA.2.18, which has been sequenced thousands of times in the UK/Britain, but has been outcompeted by BA.5

**Comment by Mydtlwn** [comment]
After another observation for 8 days, it still has obvious advantages compared with other bg.2.

**Comment by FedeGueli** [comment]
@Mydtlwn could you put here the S mutations of that strain circulating there? We are tracking some sublineages with an apparent advantage in transmissibility. Plain BA.2.38 shouldnt be so troubling as you are describing.

**Comment by Mydtlwn** [comment]
The good news is that this strain has almost no advantage compared with other strains at present. Of course, this strain may not be as good as other variants of Ba.2.38, but it is confirmed by other information that the strain we studied is indeed a variant.
