### ISSUE TITLE
BA.2 (+ORF1b:Q2070H) with S:K417T common in Malaysia (~30%) [200 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#542]
This is the third independent BA.2 + S:K417T that I could spot globally.

This lineage seems to make up ~10% of Malaysian sequences and has already been imported once into the US, recently - suggesting both a large number of cases in Malaysia (or somewhere else unsampled) and potentially a growth advantage.

The 417 mutation appears on a mostly Malaysian branch with G19677T = ORF1b:Q2070H which makes up 40% of Malaysian sequences with around 400 sequences.

S:K417T makes up only 5% of that branch.

I'd prefer if we'd designate the ORF1b:Q2070H branch as BA.2.N and then the S:417T as a sublineage BA.2.N.1 similar to how we did with BA.2.12.1 (704 and 452).

But it's also OK if we designate only one with S:417T.

This is really interesting I think because despite small number of sequences, I think this is mostly due to low sequencing proportion. There are only 1k BA.2 sequences from Malaysia, compared to 330k for UK. Malaysia has evne more population. So we should multiply by maybe 100-1k. So this lineage is actually comparable to 2k-20k seq in UK - definitely worth designating.

In Usher there are right now only 7 sequences for the S:417 - but one from UK. They cluster well.

I've asked @AngieHinrichs to check where the other 14 are.

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/25161793/162588250-f6fb2730-d30c-4965-b8e1-16cbe89ced1e.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1000f_1d8790.json?label=nuc%20mutations:A22812C

Unfortunately the 19677 mother lineage isn't clean in Usher. I think this may be because there are so few Malaysian sequences. Usher is dominated by UK and US.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/25161793/162588303-1997ff22-98fc-4abf-bbea-47e6d7307007.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_fbf3_1d8680.json?c=gt-nuc_19677&label=nuc%20mutations:T670G,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10198T,G10447A,C12880T,T15240C,C15714T,C17410T,C19955T,A20055G,C21618T,T21762C,T21846C,T22200G,C22673T,A22688G,G22775A,A22786C,A24130C,C26060T,C26858T,G27382C,A27383T,T27384C,A29510C

**Comment by FedeGueli** [comment]
This is the same of #580

**Comment by FedeGueli** [comment]
There is this one too:
2245T + S:417T (300+ seqs multiple countries)
i dont recall who highlighted me this one but i monitoring it in the last weeks clear growth advantage
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A417T&nucMutations=2245T&

**Comment by AngieHinrichs** [comment]
> 2245T + S:417T (300+ seqs multiple countries)

I believe that is a child branch of BA.2.18.

**Comment by FedeGueli** [comment]
thx @AngieHinrichs yes i realized that after posting it!. Interestingly it seems faster than the other BA.2.18 child with orf7a:83L

**Comment by corneliusroemer** [comment]
Since I've proposed it a month ago, this has grown almost 10-fold and represents aroud a third of Malaysian BA.2. It's appeared a number of times abroad, too.

I've even re-proposed it by accident in #580 (thanks @FedeGueli for noticing).

<img width="1911" alt="image" src="https://user-images.githubusercontent.com/25161793/167308562-cc71afab-e18f-4df6-972a-4f7473b70a69.png">

The only question here is whether BA.2 + S:417T on the big polytomy without any other mutation should be a lineage on its own, in which case it wouldn't be clear whether this is a sublineage of that lineage.

In India, BA.2 + S:417T is also at ~30%, but there, it seems to be multiple independent lineages or one event of S:417T arising on top of the big BA.2 polytomy.

https://cov-spectrum.org/explore/Malaysia/AllSamples/Past6M/variants/international-comparison?aaMutations=S%3A417T%2CORF1b%3AQ2070H&pangoLineage=BA.2*&

Example sequence: `Malaysia/IMR_WC219059/2022|EPI_ISL_12086027|2022-03-24`

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9794_7fe1b0.json?label=nuc%20mutations:C21306T
