### ISSUE TITLE
UK AY.4.2 with S:414K, outcompeted AY.4.2 by 4% per day [800 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#543]
Going through the last surviving Deltas I noticed that there was a very fit AY.4.2 with S:414K that had about a 30% growth advantage per week or 4% per day over AY.4.2 - which is a lot!

This would have swept through Europe had Omicron not arrived.

I think it would be worth designating as one of the fittest Deltas that ever evolved, next to US AY.3.3 (which has S:414R) and Japanese AY.29.2 (which also has S:414R)

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/25161793/162591959-5225ce93-f095-4e9c-a48d-fd0fed7b5136.png">

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/25161793/162591961-7fa2c5b8-56f2-42b8-94d0-b459db34b728.png">

https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past6M/variants?pangoLineage=AY.4.2*&aaMutations1=S%3A414&pangoLineage1=AY.4.2*&analysisMode=CompareToBaseline&

It clusters well in Usher, with nuc:C18657T, despite S:414 seeming to be masked @AngieHinrichs?

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/25161793/162591991-99e9884c-210a-4a0d-b691-f67f420c6950.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9202_1f7fd0.json?c=userOrOld&label=nuc%20mutations:G210T,C241T,C3037T,G4181T,C6402T,C7124T,C7851T,C8986T,G9053T,C10029T,C10252T,A11201G,A11332G,C14408T,G15451A,C16466T,T17040C,C19220T,C21618G,T21995C,C22227T,T22917G,C22995A,A23403G,C23604G,C25469T,C25614T,T26767C,T27638C,C27752T,C27874T,A28461G,G28881T,G28916T,G29402T,G29742T,G29764A

**Comment by chrisruis** [comment]
Thanks @corneliusroemer Given the consistent growth of this clade as a proportion of AY.4.2 in the UK, we've added this as AY.4.2.5

**Comment by AngieHinrichs** [comment]
> It clusters well in Usher, with nuc:C18657T, despite S:414 seeming to be masked @AngieHinrichs?

Sorry, just saw this -- yes, 22802 is in the [Problematic Sites](https://github.com/W-L/ProblematicSites_SARS-CoV2) list.
