### ISSUE TITLE
North Eastern US Canada BA.2 (+ C25416T) with ORF1a:D2833G and ORF1a:G1073R [280 seq, ~5% in Vermont]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#547]
Noticed a BA.2 + C25416T lineage in US/Canada with two ORF1a mutations that may have a growth advantage.

Defining mutations:
G3482A, A8763G, G12160A, C25416T

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/25161793/162633160-6d9e6910-2630-4dd4-a68f-e168cb2f4d2e.png">

https://cov-spectrum.org/explore/North%20America/AllSamples/Past6M/variants?nucMutations=C25416T&pangoLineage=BA.2*&aaMutations1=ORF1a%3AD2833G&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C25416T%2CG3482A%2CA8763G%2CG12160A&pangoLineage=BA.2*&aaMutations1=ORF1a%3AD2833G&pangoLineage1=BA.2*&

Very clean in Usher

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/25161793/162633259-ae0d126a-037d-4023-9d85-09209e3f32e6.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35154_31b400.json

**Comment by corneliusroemer** [comment]
Keeps growing, 2450 sequences, 50% more 3 days later.

**Comment by silcn** [comment]
Rather striking that this has independently picked up the silent G12160A that BA.4 and BA.5 have.

**Comment by spotto** [comment]
Is this now in BA.2.12 (Pango v.4.0.5 PLEARN-v1.3 designation of EPI_ISL_11565444)?

Defining mutations:
G3482A = ORF1a: G1073R = NSP3 G255R 
A8763G = ORF1a: D2833G = NSP4 D70G
G12160A = ORF1a: E3965  = NSP8 E23 syn
C25416T = Orf3a: F8 syn

While globally the frequency of BA.2.12 is pretty flat, this subset BA.2.12+ORF1a: D2833G (lower curves) is slowly growing (covSPECTRUM graphs all shown relative to BA.2).  But in Canada, BA.2.12 seems to be growing over and above this sub-clade (granted, this is pretty slow, ~2.4% daily growth advantage of BA.2.12 relative to BA.2). The growth in BA.2.12 in Canada is mainly seen in Ontario. Will keep an eye on these, thanks!

<img width="724" alt="Screen Shot 2022-04-15 at 11 52 06 AM" src="https://user-images.githubusercontent.com/6675053/163617296-16d3b601-acea-4260-9e2f-bdf2c51a1ded.png">
<img width="690" alt="Screen Shot 2022-04-15 at 11 51 53 AM" src="https://user-images.githubusercontent.com/6675053/163617423-3565cdd2-31ef-45c8-b99d-58f75321dc28.png">
<img width="346" alt="Screen Shot 2022-04-15 at 11 51 58 AM" src="https://user-images.githubusercontent.com/6675053/163617430-659d0c0c-f7b8-4bf3-a34e-3adeaa5ef89f.png">

**Comment by silcn** [comment]
> Is this now in BA.2.12 (Pango v.4.0.5 PLEARN-v1.3 designation of EPI_ISL_11565444)?

No, it's not. BA.2.12 is defined by S:704L which this lineage does not have. Pango appears to be miscalling basically all BA.2 + C25416T as BA.2.12 at the moment.

**Comment by FedeGueli** [comment]
277 seqs today, apparent growth adv. in Ontario around 28% (1-50% CI) , in American states where it is circulating growth adv. around 35% (with a couple over 50%) 2 seqs from France.

**Comment by corneliusroemer** [comment]
@silcn I think you meant *pangoLEARN* - the designation is clear, S:704L is necessary for it to be BA.2.12.

However different algorithms may make mistakes, pangoLEARN does right now, Nextclade may or may not, UShER probably gets it right.

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as BA.2.21 to start on the branch with A8763G (Orf1ab:D2833G) and G12160A (synonymous)
