### ISSUE TITLE
BA.4 sublineage with S:V3G [50% of BA.4 in SA, 589 seq as of 2022-05-13]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#548]
BA.4 has quite some potentially relevant diversity.

The biggest sublineages is with S:V3G - it seems to be recent and quite big already. First detection end of February.

It's well resolved in Usher and has appeared in Europe already.

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/25161793/162637458-443a0064-2dfd-4260-97a5-cefed0b0ba58.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=S%3AV3G&nucMutations=12160A%2C9866.&pangoLineage=BA.2*&nucMutations1=22792T%2C22916A%2C23767G&pangoLineage1=BA.2*&

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/25161793/162637470-6e23c001-73e8-4158-aee9-aaa6d5dd05c0.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1aa01_332de0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:T9866C,T23018G,G23040A

**Comment by FedeGueli** [comment]
Hi @corneliusroemer @chrisruis @AngieHinrichs  i spotted a sublineage of this proposed one that seems on the rise in Gauteng, KZN and already sampled in Botswana and USA 
The sublineage i m talking about has the following mutations:
S:V3G
then
S:I670V 29seqs (25 in the last month =10% of Botswana sequences, 4%of south african sequences , 5% in Gauteng)
then
Orf3a:I37T (17seqs)

here covspectrum overview (be aware some of sequences are missassigned to BA.2)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3A670V%2CS%3AV3G&aaMutations1=S%3A670V%2Corf3a%3A37T&pangoLineage1=BA.4*&

and here the Usher tree , very clear
![Screenshot_20220429-170406_Chrome](https://user-images.githubusercontent.com/87669813/165971742-8be5a22d-c5fe-4203-8edf-1e6413cbb509.jpg)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_77b7_bf6420.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T21570G


It shows a quite clear, even if early, moderate growth advantage on BA.4 baseline.

Should i open a new issue asking to reopen this one?

**Comment by corneliusroemer** [comment]
It appears that this BA.4 lineage with S:V3G has a slight growth advantage over rest of BA.4 as it's share has grown steadily in South Africa over the past two months:
<img width="2129" alt="image" src="https://user-images.githubusercontent.com/25161793/168267174-40204706-17c8-426e-83ef-601900b6710e.png">

https://cov-spectrum.org/explore/South%20Africa/AllSamples/Past6M/variants?variantQuery=%28BA.4*+%7C+%28BA.2*+%26+12160A+%26+9866C+%26+%2827788T%29%29%29&variantQuery1=%28BA.4*+%7C+%28BA.2*+%26+12160A+%26+9866C+%26+%2827788T%29%29%29+%26+S%3A3G&analysisMode=CompareToBaseline&

Most BA.4 in Austria and the US are from this lineage. Designating this could help tracking import events.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.4.1 with 140 newly designated sequences, and 12 updated designations from BA.4. Defining mutation(s) T21570G (S:V3G).
