### ISSUE TITLE
BA.4 sublineage with S:N658S [30% of BA.4 in SA, 422 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#549]
BA.4 has quite some potentially relevant diversity.

The second biggest sublineage is with S:N658G - it seems to be recent and quite big already. First detection end of February.

It's well resolved in Usher and has appeared in Europe already.

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/25161793/162637619-1056d5f0-8326-4c26-99ac-7db1358f0f85.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=S%3A658S&nucMutations=12160A&pangoLineage=BA.2*&nucMutations1=22792T%2C22916A%2C23767G&pangoLineage1=BA.2*&

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/25161793/162637470-6e23c001-73e8-4158-aee9-aaa6d5dd05c0.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1aa01_332de0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:T9866C,T23018G,G23040A

**Comment by corneliusroemer** [comment]
Too early, let's monitor and see what BA.4 looks like in a week or two

**Comment by corneliusroemer** [comment]
This BA.4 lineage seems to have a growth disadvantage vs. all of BA.4 (as measured in South Africa)

<img width="2143" alt="image" src="https://user-images.githubusercontent.com/25161793/168268403-6d26f963-a04c-4fe4-979e-9966910a2996.png">

https://cov-spectrum.org/explore/South%20Africa/AllSamples/Past6M/variants?variantQuery=%28BA.4*+%7C+%28BA.2*+%26+12160A+%26+9866C+%26+%2827788T%29%29%29&variantQuery1=%28BA.4*+%7C+%28BA.2*+%26+12160A+%26+9866C+%26+%2827788T%29%29%29+%26++S%3AN658S&analysisMode=CompareToBaseline&

**Comment by chrisruis** [comment]
Thanks @corneliusroemer As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

There doesn't seem to be a clear epidemiological event associated with this clade, we therefore haven't designated this at this point
