### ISSUE TITLE
Possible new emerging sub-lineage under recently designated lineage B.1.617

### ISSUE THREAD

**Issue by banijolly** [cov-lineages/pango-designation#55]
### **Description**
Sub-lineage of: B.1.617
Earliest sequence: 2021-01-18 ( hCoV-19/India/MH-NEERI-NGP-31600/2021	EPI_ISL_1360341)
Most recent sequence: 2021-04-04 (hCoV-19/England/CAMC-14D253E/2021	EPI_ISL_1584042)
Countries circulating: India, Canada, Germany, Singapore, Sint Maarten, United Kingdom

The cluster was found to be circulating predominantly in India, in the states of Maharashtra, West Bengal and Karnataka. All genomes in the cluster share the key mutation Spike_V382L, and the cluster currently falls under the recently designated lineage in India B.1.617, having key mutations E484Q and L452R along with P681R in Spike. Though currently small in size, the cluster may need to be monitored for a possible increase in prevalence, given that B.1.617 continues to dominate the recent samples sequenced from India.

Other mutations common to the cluster include NSP6_T77A, NSP1_V54I, NSP15_K259R, NSP13_M429I and NS6_I33T.

### **Genomes**
[gisaid_accessions.txt](https://github.com/cov-lineages/pango-designation/files/6335655/gisaid_accessions.txt)

### **Evidence**
Live instance: https://nextstrain.org/community/banijolly/Global-Analysis/484Q-452R?c=gt-S_484,452,382
![image](https://user-images.githubusercontent.com/47384613/115230060-7696dd00-a131-11eb-83a4-27be8a86d744.png)

**Comment by chrisruis** [comment]
Hi @banijolly thanks very much for submitting this. A new Pango lineage needs to be associated with an epidemiological event, like an introduction into a new country with onward transmission. Currently, it doesn't look like this is the case for this clade so I don't think it currently qualifies for a Pango lineage. However, I'll leave this issue open with the monitor flag and we can revisit in the future as more data comes in. Thanks again

**Comment by chrisruis** [comment]
Hi @banijolly just looking back through this in light of the split of B.1.617 into multiple sublineages. It looks like the sequences from your clade are B.1.617.1 and they are included in the designations for B.1.617.1 in recent pango-designation versions (current version is [v1.2.11](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.11)). Thanks again for submitting
