### ISSUE TITLE
German/Austrian BA.5 sublineage with ORF1a:Q556K [254 seq as of 2022-05-13]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#550]
There are basically two branches of BA.5 it seems - this is one of them.

It has ORF1a:Q556K and is the one that has appeared outside of South Africa, in South Germany and Austria (6 seq total)

[<img width="1675" alt="image" src="https://user-images.githubusercontent.com/25161793/162638218-790d154e-f4d4-49ee-b1e5-d65423087af0.png">](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants/international-comparison?nucMutations=12160A%2C1931A&pangoLineage=BA.2*&nucMutations1=9866C&pangoLineage1=BA.2*&)

It's resolved by Usher - better than N:E136D which seems to cluster with it but appears to be unsequenced often.

It's the blue part

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/25161793/162638237-71f2ee8b-17b5-4b72-aba5-f0ace4664dd1.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1aa01_332de0.json?branchLabel=aa%20mutations&c=gt-nuc_1931,28681,28330,6979&label=nuc%20mutations:T9866C

**Comment by corneliusroemer** [comment]
There are actually 15 sequences of this lineage in Germany - not just 5.

I downloaded and checked in the most up to date German sequence data (not all get uploaded due to quality, and there is delay): https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland

Here's the fasta
[ba52.txt](https://github.com/cov-lineages/pango-designation/files/8459945/ba52.txt)

Some of them have frameshifts and dropouts etc, but they are good enough to say: yes, they are this sublineage

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/25161793/162640659-f73a52a6-ff1d-4171-bb66-41c3538960f0.png">

Here's the metadata:
```
IMS_ID                                               DATE_DRAW   SEQ_TYPE  SEQ_REASON  SENDING_LAB_PC  SEQUENCING_LAB_PC
IMS-10302-CVDP-DC0BDBCD-A970-4618-A796-38AB1C0951F8  2022-03-06  ILLUMINA  N                  80336.0            80336.0
IMS-10302-CVDP-4DFA73C7-6ECF-45A0-A93A-3A0375181F48  2022-03-17  ILLUMINA  N                  80336.0            80336.0
IMS-10182-CVDP-038585B5-F2DF-4C97-B1CD-F7EA1159D124  2022-03-13  ILLUMINA  Y                  81671.0            81671.0
IMS-10182-CVDP-934B5923-6870-4DDF-A1CC-5060798C4FC4  2022-03-14  ILLUMINA  Y                  81671.0            81671.0
IMS-10182-CVDP-40CF2A07-EEC9-4F0A-8F7F-26BB1B9F3F9D  2022-03-13  ILLUMINA  Y                  81671.0            81671.0
IMS-10182-CVDP-3CA72F41-2CA7-4B43-835E-35665E5568E7  2022-03-13  ILLUMINA  Y                  81671.0            81671.0
IMS-10182-CVDP-CDC7BF60-0C12-4B9B-9D28-A5B8D1615438  2022-03-13  ILLUMINA  Y                  81671.0            81671.0
IMS-10150-CVDP-EAC07F0C-6467-442C-A2D4-E77D64BFF8FA  2022-03-20  ILLUMINA  X                  92637.0            92637.0
IMS-10150-CVDP-DB73C0B5-9EC4-4468-B52C-5A16DA15E98D  2022-03-28  ILLUMINA  X                  92637.0            92637.0
IMS-10116-CVDP-40EE96A6-39A5-483F-AF16-E1E74192EBE3  2022-03-29  ILLUMINA  N                  69126.0            69126.0
IMS-10116-CVDP-8D9BB9EB-A0C7-4E44-BDA1-D8243834EDD5  2022-03-29  ILLUMINA  N                  69126.0            69126.0
IMS-10182-CVDP-83F89C70-C702-461C-BD64-53FADC5A0601  2022-03-18  ILLUMINA  Y                  81671.0            81671.0
IMS-10302-CVDP-9E1D32B1-ABB7-4808-A716-D607EE0245C9  2022-03-19  ILLUMINA  Y                  80804.0            80336.0
IMS-10116-CVDP-407F53A5-1CA9-4688-9D59-924D1E9C313B  2022-03-30  ILLUMINA  N                  69126.0            69126.0
IMS-10116-CVDP-A68F5ECF-7126-42E2-A52E-ABD4BF489180  2022-04-01  ILLUMINA  N                  69126.0            69126.0
```
 
```
SENDING_LAB_PC  count
       80336        2
       81671        6
       92637        2
       69126        4
       80804        1

**Comment by corneliusroemer** [comment]
Too early, let's monitor and see what BA.5 looks like in a week or two

**Comment by silcn** [comment]
Probably about time to bring this back up again. Usher divides BA.5+ORF1a:Q556K in two different branches: one that is mainly South African where it thinks N:E136D came first, and one that is mainly German without N:E136D. However, it looks more likely to me that ORF1a:Q556K is monophyletic and N:E136D occurred twice independently, as both apparent ORF1a:Q556K branches are large while there are only two sequences on the branch with N:E136D but not ORF1a:Q556K.

ORF1a:Q556K (without N:E136D) makes up >90% of BA.5 in Germany and has spread to several other European countries, so it may be worth designating the whole ORF1a:Q556K branch to track the spread in Europe.

**Comment by corneliusroemer** [comment]
Thanks @silcn, I just had a look again. This seems like a very German branch indeed.

![image](https://user-images.githubusercontent.com/25161793/168270584-fe479d1a-f094-45fc-a609-f05a2ef3da37.png)

In the latest Usher tree, N:136 is wild type in this branch, so all looks good.

This is the distribution by country and date of first sequence now:
<img width="2222" alt="image" src="https://user-images.githubusercontent.com/25161793/168270906-d0ab3a2e-f9e9-4075-816b-e587b745653e.png">

https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants/international-comparison?variantQuery=%28BA.5*+%7C+%28BA.2*+%26+12160A+%26+9866C+%26+%28C27889T%29%29+%29+%26+C1931A&variantQuery1=%28BA.4*+%7C+%28BA.2*+%26+12160A+%26+9866C+%26+%2827788T%29%29%29+%26++S%3AN658S&

**Comment by corneliusroemer** [comment]
This is the sublineage with N:E136D as well, more common in South Africa

![image](https://user-images.githubusercontent.com/25161793/168271991-4f62208e-92e4-44f8-bdf3-144d5ce8e37e.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_18273_e39c20.json?c=country&label=nuc%20mutations:C1931A

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.3 with 8 newly designated sequences, and 122 updated designations from BA.5. Defining mutation(s) C1931A (ORF1ab:Q556K) and G28681T (N:E136D). Assumed ORF1a:Q556K to be monophyletic and designated the E136D and "non-E136D" clades as one.

**Comment by AngieHinrichs** [comment]
Thanks for spotting that it's split into multiple branches!  I think C1931A is the real defining mutation, and the tree has a branch with G28681T > C1931A in error -- it should be the other way around, and I should be able to fix it soon.
