### ISSUE TITLE
Potentially new BA.1 sub-lineage with ORF1ab:S166G + Nuc: A761G mutation in Loreto (Peru)

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#552]
**Description**
New possible BA.1 sub-lineage with ORF1ab:S166G + Nuc: A761G mutation proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**Earliest sequence:** 2021-12-29
hCoV-19/Peru/LOR-INS-13108/2021 (EPI_ISL_9681151)
hCoV-19/Peru/CUS-INS-13095/2021 (EPI_ISL_9681137)

**Most recent sequence:** 2022-02-14
hCoV-19/Peru/LOR-INS-15604/2022 (EPI_ISL_11627708)
hCoV-19/Peru/LOR-INS-15603/2022 (EPI_ISL_11627707)

**Countries circulating:**
Peru (58)

**Genomes**
[Genomes.csv](https://github.com/cov-lineages/pango-designation/files/8466171/Genomes.csv)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f7bc_441520.json?c=gt-ORF1ab_166&label=nuc%20mutations:A761G
![Captura de pantalla de 2022-04-11 11-23-52](https://user-images.githubusercontent.com/89021119/162789868-7798bc5a-83a9-4c94-9410-9d70100c672e.png)
![Captura de pantalla de 2022-04-11 11-50-39](https://user-images.githubusercontent.com/89021119/162790852-f46e17a2-e85a-4f81-b852-3fb00923bdad.png)
![Captura de pantalla de 2022-04-11 11-51-05](https://user-images.githubusercontent.com/89021119/162790872-ada597f8-6fa7-4252-bd4f-a28e7b8af239.png)

**Proposed lineage name**
BA.1.X

**Comment by corneliusroemer** [comment]
Thanks! ORF1ab:S166G equals nuc:A761G 

I'm confused whether this is the same as the ORF1a:166G lineage on BA.1.1 - the Peru sequences don't have S:346K

Here's BA.1.1 lineage: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A346K&pangoLineage=BA.1*&aaMutations1=ORF1a%3AS166G%2CS%3A346K&pangoLineage1=BA.1*&analysisMode=CompareToBaseline&

And here without: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A346R&pangoLineage=BA.1*&aaMutations1=ORF1a%3AS166G%2CS%3A346R&pangoLineage1=BA.1*&analysisMode=CompareToBaseline&

Could really be homoplasic

**Comment by Wen1953** [comment]
Hi Cornelius, thanks for the previous recomendation, we were looking S166G since a while.
We saw that BA.1.1 lineage in Peru has S:R346K but not ORF1ab:S166G mutation, as you can see on figure atach. Posibly we were sawing a diferent pattern.

![Captura de pantalla de 2022-04-11 14-43-00](https://user-images.githubusercontent.com/89021119/162817368-469f14e0-75f9-46a1-afb7-9f875b32f9c2.png)

Here BA.1.1 + ORF1a:S166G:
https://cov-spectrum.org/explore/Peru/AllSamples/Past6M/variants?aaMutations=ORF1a%3AS166G&pangoLineage=BA.1.1*&

BA.1.1 + ORF1a:S166G + S:R346K:
https://cov-spectrum.org/explore/Peru/AllSamples/Past6M/variants?aaMutations=ORF1a%3AS166G%2CS%3AR346K&pangoLineage=BA.1.1*&

BA.1 + ORF1a:S166G:
https://cov-spectrum.org/explore/Peru/AllSamples/Past6M/variants?aaMutations=ORF1a%3AS166G&pangoLineage=BA.1*&

**Comment by OrsonMM** [comment]
two sequences more EPI_ISL_11897840, EPI_ISL_11897839.

**Comment by chrisruis** [comment]
Thanks @Wen1953 It looks like the Orf1ab:S166G sequences form a number of small but separate clades rather than a single clade. This mutation therefore doesn't look like a good marker for a lineage so we haven't added this
