### ISSUE TITLE
Potential BA.1*/BA.2 Recombinant with Likely Breakpoint at NSP6-NSP9 (5 Seqs in Canada, Quebec as of 2022-04-13)

### ISSUE THREAD

**Issue by ilevade** [cov-lineages/pango-designation#557]
Recombinant between: BA.1* & BA.2
Earliest sequence: 2022/03/14
Most recent sequence: 2022/04/05
Countries circulating: Canada, Quebec
Conserved Nuc mutations (those in red frames are likely from the donor from the BA.1* side):
![nextclade_XE-like_2](https://user-images.githubusercontent.com/31353633/163229216-66a6d7d8-97db-4b30-a647-041d17f36507.png)

Evidence: 

We though at first these samples were the recombinant XE, as the breaking point is really close to XE (11537-12880), but they show a lot of differences in the BA.1* region of the genome. 

![nextclade_XE-like_3](https://user-images.githubusercontent.com/31353633/163229733-f4ef0d57-b94e-49e6-b433-1286b762b3d7.png)

I have put 4 of these sequences plus 3 XE recombinant sequences through Sc2rf from @lenaschimmel . You can see that the breaking point is not exactly like XE. 

![recombinant_sc2r_XE](https://user-images.githubusercontent.com/31353633/163230172-6715f043-e44d-48b2-8802-0817453364e1.JPG)

UShER tree: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5888_708600.json
![tree_XE_Canada](https://user-images.githubusercontent.com/31353633/163239761-fd4cb9fc-ca0b-473e-8b43-1c37f517c0e9.JPG)

Here the list of Genomes:

EPI_ISL_11360224
EPI_ISL_11969434
EPI_ISL_11969435
EPI_ISL_11969433
EPI_ISL_12033319

**Comment by chrisruis** [comment]
Thanks @ilevade We've just published some guidelines for recombinant lineages [here](https://www.pango.network/pango-lineages-guidelines-for-suggesting-novel-and-recombinant-lineages/). In most cases we expect new recombinant lineages to contain at least 50 sequences, however exceptions to this may arise if the recombinant has particular novelty or significance, with unusual breakpoints and/or parental lineages

It looks like there's still just the 5 sequences in this clade so I'd suggest this is too small for a designation at this stage. I'll close this for now but can reopen if this clade grows in the future

**Comment by ktmeaton** [comment]
38 genomes as of 2022-06-29. Although I'm not too sure about the more divergent USA and England strains (N=10) at the moment.

![image](https://user-images.githubusercontent.com/14981272/176477590-29f6fbff-7b58-4c07-a4d4-c3e43511b351.png)

- UCSC UShER Tree: [proposed557_2022-06-29_auspice.zip](https://github.com/cov-lineages/pango-designation/files/9011955/proposed557_2022-06-29_auspice.zip). 
- Decompress and upload to https://auspice.us/
