### ISSUE TITLE
Potential recombinant BA.1*/BA.2 circulating in Brazil, Malaysia, Denmark and India

### ISSUE THREAD

**Issue by sussuchi** [cov-lineages/pango-designation#559]
**Description:** Potential recombinant BA.1*/BA.2 circulating in Brazil, Malaysia, Denmark and India

**Recombinant:** BA.1* & BA.2
**Earliest sequence:** 2022-02-05
**Likely breakpoint:** between 15714 and 17410 (ORF1b- NSP12 and NSP13)
**Genomes:** 
hCoV-19/Brazil/SP-DASA828822284657/2022
hCoV-19/India/MH-INSACOGIP10021/2022
hCoV-19/Denmark/DCGC-434155/2022
hCoV-19/Malaysia/IMR_WC218070/2022
hCoV-19/Malaysia/IMR_WC218470/2022
hCoV-19/Malaysia/IMR_WC218510/2022

**Evidence**

The sample hCoV-19/Brazil/SP-DASA828822284657/2022 was classified as XM by nextclade, however it seemed to have a different breakpoint with a 21L labeled mutation at 17410:

![fig1](https://user-images.githubusercontent.com/36264670/163694122-4f8fc9ce-23eb-4395-a160-46cac2f4c6b0.png)

Sequencing analysis from hCoV-19/Brazil/SP-DASA828822284657/2022 (828822284657) were repeated (828822284657R), and 828822284657 was submitted to usher:

![fig2](https://user-images.githubusercontent.com/36264670/163694178-11b09276-d57c-4d69-a55b-cd7b67bf1646.png)

Below is highlighted the monophyletic cluster of samples:

![fig3](https://user-images.githubusercontent.com/36264670/163694184-48b628ff-1b60-4530-ab4a-31d44b39f64f.png)

We used Lena’s amazing tool (https://github.com/lenaschimmel/sc2rf) to visualize our sequences and five samples from Malaysia, Denmark, and India (EPI_ISL_10369263, EPI_ISL_11273668, EPI_ISL_11902802, EPI_ISL_11902839, EPI_ISL_11902849), that clustered together in the tree and seems to have the same breakpoint. Additionally, two XM, XJ and XE samples were added to sc2rf output:

![fig4](https://user-images.githubusercontent.com/36264670/163694217-89ea1f51-77c7-4263-84cb-85c8400b2cbc.png)

Here we can see the ORF1A and ORF1B nextclade output with more two XM and two XJ recombinants:

![fig5](https://user-images.githubusercontent.com/36264670/163694271-e9b07a5c-ff64-49c5-aba1-6461c8f3a78e.png)

![fig6](https://user-images.githubusercontent.com/36264670/163694275-67a53a8f-cc9d-487a-8395-355b97a26448.png)

The samples may share the same breakpoint and the Brazilian sample seems to harbor a BA.1.14 profile at ORF1A. We will monitor if more samples will emerge.

**Comment by silcn** [comment]
This looks like at least 3 and probably 4 different lineages. 

The Malaysian samples have a BA.1.13.1 parent and also share a nuc:T28678C on the BA.2 side; both of these are much more common in Indonesia than Malaysia so the recombinant may have arisen there.
The Brazilian sample has a BA.1.14.1 parent (see #506). 
The Danish sample has C2536T + C11950T which has been seen before in BA.1, especially in Poland.
The Indian sample has C12153T which was present in about 1% of BA.1* in India.

**Comment by corneliusroemer** [comment]
Thanks for the analysis @silcn, I'll close this then as we have rule of one issue per lineage/recombinant.
