### ISSUE TITLE
BA.1 sequence from Eastern Cape, SA baseline surveillance contains additional RBD spike mutations

### ISSUE THREAD

**Issue by bitbyte2015** [cov-lineages/pango-designation#561]
Worth keeping an eye out for. The latest batch of sequences from Eastern Cape has what appears to be a BA.1 with additional spike mutations in the RBD. It contains S:F486V from BA.4 along with the 493 reversion but is missing S:L452R. It also contains S:R346K which I can't find in any BA.4 sequence. GISAID calls it as BA.1.17 while USHER calls it as BA.1.1. There is a long branch on the USHER tree from any known sequences.

Ambiguous nucleotides in the spike are also located at positions 413, 415, 424, 429, 445

USHER tree:
![image](https://user-images.githubusercontent.com/36325823/163734018-adf8ed00-94f2-4abb-a661-1d099f5ded1b.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25f09_c87800.json

Private Non-Synonymous Spike Mutations:
Reversions are **bolded**
|Nucleotide|AA change|
|-----|-----|
|C21588T|P9L|
|G22599A|R346K|
|G22894T|K444N|
|**A22898G**|**S446G**|
|G23012A|E484T|
|T23018G|F486V|
|**G23040A**|**S496G**|

Sequence ID:
EPI_ISL_12006281

**Comment by FedeGueli** [comment]
Interestingly this sequence has a double mutation at the start of Orf1b: Orf1b:5A, orf1b:7V.
Orf1b:5a appeared just 37 times from 2020, but 17 out of 37 are from 2022 in South Africa 

tree of recent SA sequences carrying Orf1b:5A:
https://t.co/ELurJ2HGDV

**Comment by corneliusroemer** [comment]
This Github is for proposals of lineages, not to discuss individual sequences. I will thus close it.

Reversions are often due to reference backfilling - so single sequences by itself don't mean much at all.
