### ISSUE TITLE
UK BA.2 (+G12163T) lineage with S:F186S [1k seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#562]
Spotted a UK BA.2 (+G12163T) lineage that has an S1 mutation S:F186S and makes up about 0.6% of UK BA.2

Seems to have a bit of a growth advantage over other BA.2* and BA.2+G12163T

![image](https://user-images.githubusercontent.com/25161793/163765918-e47b3b70-84af-44eb-85c0-f7d7a7c33d18.png)

https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?aaMutations=S%3A186S&nucMutations=12163T&pangoLineage=BA.2*&aaMutations1=S%3A186S&nucMutations1=G12163T&pangoLineage1=BA.2*&

Seems to slowly appear abroad as well, probably exported from UK.

![image](https://user-images.githubusercontent.com/25161793/163766062-ea914c5c-5f9c-425d-a5f7-8b7dfb56861b.png)

**Comment by chrisruis** [comment]
Thanks @corneliusroemer Agree that the clear geographical focus of this clade in the UK combined with a steady increase in proportion of UK BA.2 sequences warrants a designation. We've added this as BA.2.22 to start on the branch with T22119C (S:F186S)
