### ISSUE TITLE
BA.2+22792T sublineage with S:I68T circulating in Belgium (6%) -1373 seqs globally 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#565]
Follow up from #524 .
I want to propose here a sublineage of BA.2 carrying S:I68T and Orf8:A65V.
As shown in a [comment in issue 524](https://github.com/cov-lineages/pango-designation/issues/524#issuecomment-1095047000)  recently S:I68T (spotted by @olias12061976) and orf8:A65V (spotted by @bikuduh) appeared indepently and separately in several BA.2 sublineages .
One of them carries both these two emerging mutations and it is circulating in Germany Belgium Denmark Israel and have been sequenced in USA and UK too.
Here the list of 373 sequences :
[contributors (87).csv](https://github.com/cov-lineages/pango-designation/files/8506888/contributors.87.csv)

Its share is increasing vs BA.2 baseline
![EstimatedCasesPlot](https://user-images.githubusercontent.com/87669813/163841007-302e7915-b909-4663-9200-ea4c3463b210.png)

And it is showing an apparent growth advantage ranging from 15% in Israel to 70% in Denmark
![chrome_screenshot_1650291189555](https://user-images.githubusercontent.com/87669813/163841110-4bf0d046-0c5e-4a1d-aa71-3316d11f2727.png)

Interestingly 83% of this sublineage is missassigned to BA.2.9 while lacking or3a:H78Y defining BA.2.9 mutation
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AI68T%2COrf8%3AA65V&

[Usher tree (by @bikuduh)](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3507e_9f3210.json?branchLabel=aa%20mutations&c=gt-S_68&label=nuc%20mutations:C22792T) 
![chrome_screenshot_1650300376107](https://user-images.githubusercontent.com/87669813/163842231-41eff1bb-46ed-45f2-8b4c-cb4dee15bd2b.png)

**Comment by corneliusroemer** [comment]
These S:68T are tricky, they appear in so many places. So all individual lineages are still quite small despite S:69T being in 6% of Belgian sequences!

**Comment by FedeGueli** [comment]
yes @corneliusroemer and the same happens for orf8:65V : many lineages but all of them small but the Papua new guinea one recently designated

**Comment by corneliusroemer** [comment]
I'd say we should designate this without the ORF8:65V mutation. It's probably not relevant here.

S:68T appeared on the European BA.2 + 22792T branch with no other private mutation present at the time of mutation.

That's now grown to 7% in Belgium - so quite possible this mutation arose in Belgium and has spread slowly from there. In total 1400 sequences by now.

<img width="1652" alt="image" src="https://user-images.githubusercontent.com/25161793/165084133-999d1e3f-39a0-42b3-be7d-1512eef1eeba.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=S%3AI68T&nucMutations=C22792T&pangoLineage=BA.2*&

**Comment by FedeGueli** [comment]
Yes @corneliusroemer i agree totally with you. at the beginning i was afraid that just S:I68T could be confounded by other unrelated clades bringing this mutation. so it was easier to monitor the double mutation. But now orf8:65V is just 1/3 of S:68T sequences in Belgium.  i ll change the title of this proposal consequently.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.36 with 976 newly designated sequences, and 109 updated designations. Defining mutation(s) T21765C (S:I68T).

**Comment by FedeGueli** [comment]
> Thx @InfrPopGen  all the credits to @olias12061976 who first spotted this mutation.

**Comment by corneliusroemer** [comment]
The designated sequences seem to be messy - no super majority actually has `21765C` neither do they have `22792T`, weird

**Comment by FedeGueli** [comment]
is it my fault @corneliusroemer ? can i help in some way? i can re extract  a more stringent sequence list if needed

**Comment by FedeGueli** [comment]
@corneliusroemer i checked the query i used to extract the sequence list and so ething weird  happens: On covspectrum Pangolin recognizes that as BA.2.36 (99%) whilr nextclade missassigned all of them to BA.2.

https://cov-spectrum.org/explore/World/AllSamples/from=2022-01-31&to=2022-03-31/variants?aaMutations=S%3AI68T%2COrf8%3AA65V%2Corf1a%3A135R&nucMutations=22792T&
