### ISSUE TITLE
Large mayority of sequences currently assigned to BA.2.12 doesn't carry defining mutation S:704L 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#567]
@AngieHinrichs @chrisruis @corneliusroemer 
I noticed a huge mismatch between total number of currently assigned BA.2.12 sequences and sequences carrying the defining mutation S:704L:

BA.2.12 :63659 seqs
BA.2.12 with S:704L : 4656 seqs =~7% of currently assigned BA.2.12 seqs.

Usher do not misassign them.

covspectrum: 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.2.12*&

**Comment by chrisruis** [comment]
We've added a new set of BA.2 designations in the C25416T clade that are not in BA.2.12 which will hopefully fix the assignments in this region of the tree

**Comment by corneliusroemer** [comment]
@FedeGueli The requirements right now are at least one one non-synonymous mutation per level so that doesn't work.

**Comment by FedeGueli** [comment]
Thx @corneliusroemer
