### ISSUE TITLE
BA.2.10 sublineage with E:R61L circulating in Japan/India [99 seqs]

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#569]
Edited

While checking for japanese airport surveillance sequences from India  @c19850727 (Sakaguchi Hitoshi) highlighted me that a significant share of the last samples was carrying the E:R61L mutation.
Looking at japanese sequences we found that a BA.2.10 sublineage with E:R61L circulates there .
Here we want to propose it, but it is worth mentioning and monitoring that multiple BA.2 sublineages carry this sublineage and one of them  is actually growing quite fast in Switzerland.

Defining mutation:
E:R61L

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_df1a_216c0.json?branchLabel=aa%20mutations&c=gt-E_61&label=nuc%20mutations:G26426T

![chrome_screenshot_1650472302829](https://user-images.githubusercontent.com/87669813/164279290-063d6b62-3a67-40a4-a85f-c3dbbfc3e49d.png)

The Japanese branch has acquired Orf1a:I281V and  N:H145V too.

Nr of Sequences: 80 (edited)
First sequence: India 1/2022
List of sequences:
[contributors (8).csv](https://github.com/cov-lineages/pango-designation/files/8526061/contributors.8.csv)

Growth advantage vs BA.2 baseline not clear in Japan 

Covspectrum overview:
https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?aaMutations=E%3A61L%2CORF1b%3AS959P&pangoLineage=BA.2*&aaMutations1=E%3A61L&pangoLineage1=BA.2.10*&

I think this is worth a designation representing an introduction from a probably large unsampled indian lineage with subsequent intro and further spread in one more country (Japan)

**Comment by c19850727** [comment]
There are 8 Japan ex-India or Japan ex-Nepal sequences involving this potential sublineage, sampled on 7 different dates between Jan. and March, indicating repeated introductions

There's also a potential BA.1+BA.2 recombinant sequence (Japan ex-India) with this signature E:R61L.

**Comment by corneliusroemer** [comment]
It's important to separate the different lineages with E:R61L.

Hence, I added `ORF1b:S959P` to the query above to be BA.2.10 specific. There are 80 sequences of this worldwide, not 100 as stated in the first post.

**Comment by FedeGueli** [comment]
Thank you very much @corneliusroemer i have edited the original post to avoid confusion.
