### ISSUE TITLE
Proposal for lineage within B.1 with N501Y, E484K, R346K, P681H Spike substitutions

### ISSUE THREAD

**Issue by ha-ruiz75** [cov-lineages/pango-designation#57]
by Carlos Franco-Muñoz, Katherine Laiton-Donato, Diego A. Álvarez-Díaz, Héctor Alejandro Ruiz-Moreno, Jhonnatan Reales-González, Diego Andrés Prada, Sheryll Corchuelo, Maria T. Herrera-Sepúlveda, Julian Naizaque, Gerardo Santamaría, Jorge Rivera, Magdalena Wiesner, Diana Marcela Walteros, Martha Lucia Ospina Martínez, Marcela Mercado-Reyes

### **Description**
Sub-lineage of: **B.1**
Earliest sequence: **2021-01-11** (hCoV-19/Colombia/MAG-INS-VG-482/2021|EPI_ISL_1220045)
Most recent sequence: **2021-04-09** (hCoV-19/Spain/MD-HGUGM-21164038/2021|EPI_ISL_1647956)
Countries circulating: Colombia (25), USA (5), Spain (2); (GISAID sequences)

The first sequence came from a sample collected on January 11, 2021. It was assigned to the B.1 lineage and presented amino acid substitutions in the Spike protein region (N501Y, E484K, R346K, and P681H), and deletion of four nucleotides (del:26158:4).

During early March, new sequences presented a similar mutation pattern. Higher abundance of sequences with this amino acid substitution pattern were associated to a rise in active cases during late March in the northern regions of the country. 
Latest sequences are from Colombia and Spain.

Sequences were mostly assigned to the very diverse B.1 lineage, with minor placement in B.1.469, B.1.466, B.1.153, and B1.427. Phylogenetic analysis suggest B.1 is the parental lineage.

Upload of more sequences has been slow as a frameshift due to 4 nucleotide deletion (del:26158:4) must be manually confirmed in the web database upon upload.

### **List of characteristic amino acid changes of the new lineage:**

> ORF1ab:
>T1055A (NSP3: T237A)
>T1538I (NSP3: T720I)
>Q3729R (NSP6: Q160R)
>P4715L (NSP12: P323L)
>P6666S (NPS13: P419S)
> 
> ORF3a: 	
>Q57H
>N257X
>deletion: 26158-26162 (4 nucleotides)
> 
> ORF8: 		
>T11K
>P38S
>S67F
> 
> Spike:	 	
>T95I
>Y144T
>R346K
>E484K
>N501Y
>P681H
> 

### **Genomes**
List of genomes, collected 2021-04-20, attached.
[B_1_X_list_of_genomes.txt](https://github.com/cov-lineages/pango-designation/files/6353918/B_1_X_list_of_genomes.txt)

### **Evidence**
The full phylogenetic tree can be accessed through this link: [microreact tree - proposed lineage B.1.X](https://microreact.org/project/5CAiK3qCMaEgE4vYkKVpZW/51a8fd40)

![Proposed lineage tree](https://user-images.githubusercontent.com/34463016/115623443-cf47b080-a2be-11eb-9f74-d24e534f9faa.png)
 

### **Proposed lineage name**
Next available designation within parent B.1 lineage (B.1.X)

**Comment by chrisruis** [comment]
Hi @ha-ruiz75 thanks for submitting this. We've added this as lineage B.1.621 in [v1.1.20](https://github.com/cov-lineages/pango-designation/releases/tag/v1.1.20)
