### ISSUE TITLE
Potentially new BA.1.1.1 sub-lineage with orf1ab: V6362I mutation in Cusco (Peru)

### ISSUE THREAD

**Issue by OrsonMM** [cov-lineages/pango-designation#570]
Description
New possible omicron sub-lineage with orf1ab: V6362I mutation proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

inside of clade Genomes of Canada carry aditional mutation in spike. S:D1146Y

Earliest sequence: 2021-12-16
KEN/SS7022/2021 (EPI_ISL_8587391)
Netherlands/NH-RIVM-77336/2021 (EPI_ISL_8392430)

Most recent sequence: 2022-03-17
Peru/CUS-INS-16223/2022 (EPI_ISL_11897860)

Countries circulating:
Peru (54), Canada (17), Belgium (1), Chile (2), Germany (2), Kenya (1), Netherlands (1), USA (1)

Evidence:

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_94e8_204d0.json?c=gt-ORF1ab_4533,6362

![new_linaje_propuesta](https://user-images.githubusercontent.com/12600107/164286831-a9ced5eb-a3bc-4c37-948b-436cdc2b0b83.JPG)

Peru 

![Peru_only](https://user-images.githubusercontent.com/12600107/164287969-d7ccb792-4acd-420e-93bb-35cc5e76eace.JPG)

GENOMES: 
[genomes_peru.txt](https://github.com/cov-lineages/pango-designation/files/8523773/genomes_peru.txt)

COVSPECTRUM 
![new_linaje_propuesta_COV](https://user-images.githubusercontent.com/12600107/164287601-e649bb9a-3200-479c-8bce-b6652557c9b9.jpg)

**Comment by chrisruis** [comment]
Thanks @OrsonMM We've added this as BC.2 (with BC being an alias of BA.1.1.1), starting on the branch with G19348A (Orf1b:V1961I)
