### ISSUE TITLE
BA.2 sublineage with S:L858I (400+ seq, >10% in Maldives)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#575]
Proposal for a sublineage of BA.2
Earliest sequences: 2022-01-17 (Germany), 2022-01-18 (Maldives)

Countries detected: UK (~400), Maldives (12), Germany (12), Sweden (2), USA (2), Belgium (1)

Defining mutations: ORF1ab:E5136D, V6638F, S6695G and then S:L858I (=nuc:G15672T, G20176T, A20347G, C24134A)
<img width="461" alt="Maldives_lineage" src="https://user-images.githubusercontent.com/42699509/164561349-33daa8df-47ab-43ef-bb15-7ff3960e1617.png">
[https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_286fb_1d1150.json](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_286fb_1d1150.json)

Sequencing from the Maldives is sparse, but this lineage makes up over 10% of the most recent uploads, which were sampled in mid-February and uploaded in mid-March. It may have arisen there, since there is a Maldives sequence from 2022-01-18 that is only missing S:L858I (shown in yellow above). 
A sublineage with two additional silent mutations T9892C and C9502T was then introduced to the UK, where it now makes up about 0.3% of samples; this branch is clearly visible on the tree. This sublineage shows a preliminary 24% growth advantage relative to BA.2* in the UK on cov-spectrum.
<img width="611" alt="S858I_growth_advantage" src="https://user-images.githubusercontent.com/42699509/164562312-d288fc6e-485c-4849-a026-44c23d6d6072.png">
[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A858I&nucMutations=G15672T&pangoLineage=BA.2*&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A858I&nucMutations=G15672T&pangoLineage=BA.2*&)

Note: pangoLEARN is currently misclassifying some of these as BA.2.3, BA.2.5 and BA.2.10.

**Comment by FedeGueli** [comment]
Great catch! BA.2 with the triple orf1b:E735D, orf1b:V2237F, orf1b:S2294G was circulating earlier in January in Indonesia . S:858I is quite rare  We have seen S:859N in different VOIs and S:859I was in an high trasmissible sublineage of AY.4 in denmark and in AZ.5.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.39 with 403 newly designated sequences, and 34 updated designations from BA.2. Defining mutation(s) C24134A (S:L858I), G20176T (ORF1ab:V6638F).
