### ISSUE TITLE
BA.2 sublineage with C1663T and E:61L circulating in Switzerland (200 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#576]
Extending the analysis on E:R61L mutation spotted by @c19270785 in #569 , i found a BA.2 sublineage that acquired that mutation independently and it is currently circulating in Switzerland.
Sublineage size is small but it seems growing steadily from March ahead.

This lineage starts with C1663T and E:R61L despite [Usher tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice8_genome_df1a_216c0.json?branchLabel=aa%20mutations&c=gt-E_61&label=nuc%20mutations:T15540C) shows some samples without C1663T with E:R61L and some without C1663T with E:R61L and C15540T but i dont think they are necessarily related given the fact lineages with E:61L were circulating in India/Asia widely since the start of 2022 ( see #569)

![Schermata 2022-04-22 alle 11 41 09](https://user-images.githubusercontent.com/87669813/164680847-898c0e13-098c-45e4-98e4-6beb60bb384f.png)

Nr. of seqs : 80 (54 Switzerland)
First seq: 8/2022 Switzerland
Sequences list: 
[contributors (9).csv](https://github.com/cov-lineages/pango-designation/files/8539664/contributors.9.csv)

[Covspectrum overview](https://cov-spectrum.org/explore/Switzerland/AllSamples/Past3M/variants?aaMutations=E%3A61L&nucMutations=C1663T&pangoLineage=BA.2*&)
Growth Advantage in Switzerland :
![Schermata 2022-04-22 alle 11 48 14](https://user-images.githubusercontent.com/87669813/164682324-5c4218e2-bac1-4afd-bbd5-0b10cd744332.png)

**Comment by corneliusroemer** [comment]
Numbers are still very small. We should see how this develops, it's a different situation than with S:452 mutations where we have good evidence that these are beneficial and where it thus makes sense to designate even with only 50 sequences or so.

**Comment by FedeGueli** [comment]
Agree monitor label is what this sublineage deserves right now @corneliusroemer thank you.

**Comment by FedeGueli** [comment]
147 seqs as today

**Comment by FedeGueli** [comment]
185 seqs as today. it started circulating in Sweden and France too.
@corneliusroemer
