### ISSUE TITLE
Proposal for new sub-lineage of B.1

### ISSUE THREAD

**Issue by dw974** [cov-lineages/pango-designation#58]
Sub-lineage of: B.1
Earliest sequence: 2021-01-19
Most recent sequence: 2021-03-30
Countries circulating: Reunion

This group of sequences originates only from patients on Reunion Island, it shares some key mutations with sequences from continental Africa. But we have not found similar sequences elsewhere in GISAID.
We have consistently identified it in patients all across the island since we started sequencing three months ago in independent cluster events, and we suspect that it may have been circulating locally for a long time, but do not have backdated samples to check this hypothesis.

EPI_ISL_1265849, EPI_ISL_1265852, EPI_ISL_1628894, EPI_ISL_1629101, EPI_ISL_1629103, EPI_ISL_1629111, EPI_ISL_1629119, EPI_ISL_1629122, EPI_ISL_1629187, EPI_ISL_1629190, EPI_ISL_1629191, EPI_ISL_1629309, EPI_ISL_1629343, EPI_ISL_1629352, EPI_ISL_1629357, EPI_ISL_1628705, EPI_ISL_1628818, EPI_ISL_1628828, EPI_ISL_1628829, EPI_ISL_1628827, EPI_ISL_1628838, EPI_ISL_1629290, EPI_ISL_1628706, EPI_ISL_1628715, EPI_ISL_1628714, EPI_ISL_1628713, EPI_ISL_1628739, EPI_ISL_1628786, EPI_ISL_1628793, EPI_ISL_1628799, EPI_ISL_1628902, EPI_ISL_1628911, EPI_ISL_1628913, EPI_ISL_1628907, EPI_ISL_1628922, EPI_ISL_1628924, EPI_ISL_1628979, EPI_ISL_1629137, EPI_ISL_1629135, EPI_ISL_1629155, EPI_ISL_1629198, EPI_ISL_1629405, EPI_ISL_1628759, EPI_ISL_1628996, EPI_ISL_1629007, EPI_ISL_1629066, EPI_ISL_1629214, EPI_ISL_1629216, EPI_ISL_1629221, EPI_ISL_1629224, EPI_ISL_1629410, EPI_ISL_1629414, EPI_ISL_1629419, EPI_ISL_1629299, EPI_ISL_1629440, EPI_ISL_1629463, EPI_ISL_1629465, EPI_ISL_1629468, EPI_ISL_1629472, EPI_ISL_1629026, EPI_ISL_1628909, EPI_ISL_1628820

![image](https://user-images.githubusercontent.com/54392677/115652375-335d8980-a33e-11eb-9398-80e003be5ada.png)

For some reason the nextclade tree system seems to put all these on long branches from the root. I am guessing this might be something to do with how missing data is treated? Anyway, it's quite misleading because there are only 2 or 3 mutations difference between any of our sequences... and they are quite divergent from any reference we have found (around 20 mutations).

**Comment by chrisruis** [comment]
Thanks for submitting this @dw974 - we've added this as lineage B.1.622 in [v1.1.21](https://github.com/cov-lineages/pango-designation/releases/tag/v1.1.21)

**Comment by dw974** [comment]
Lineage B.1.622 seems to have disappeared from the latest update of pangolin, and our sequences are now attributed to B.1 again.
Any reason for this?

**Comment by chrisruis** [comment]
Thanks for letting us know @dw974. We've run a new pangoLEARN model and B.1.622 should now be back in there
