### ISSUE TITLE
Malaysian BA.2 + S:417T + ORF1b:Q2070H [60 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#580]
S:417T possibly has a growth advantage. It has appeared in a number of BA.2 lineages.

This is one that is common in Malaysia ~5% and has appeared internationally (US, Singapore, Indonesia, UK)

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/25161793/164909664-c614e264-3f1f-4df1-bde5-f5b0e9362d7b.png">

covSpectrum

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A417T&nucMutations=G19677T%2CC21306T%2CA22812C&pangoLineage=BA.2*&aaMutations1=S%3A417T&nucMutations1=23248&pangoLineage1=BA.2*&

There seem to be 2 Usher branches for these, the smaller one has an N reversion that's probably an artefact.

**Comment by FedeGueli** [comment]
93 seqs now and it seems spreading in USA right now (30seqs)

**Comment by corneliusroemer** [comment]
Duplicate of #542
