### ISSUE TITLE
UK BA.2 (+ 25416T + 6091T) lineage with S:417T [100 seq]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#582]
As explained in #581 there seems to be a very similar but independent BA.2 + 25416T + S:417T lineage in the UK, which has arisen on top of the BA.2 + 25416T + 6091T lineage.

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/25161793/164910326-2b522573-8adb-4981-91be-e35fdc5cc140.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=S%3A417T&nucMutations=25416T%2C6091T&pangoLineage=BA.2*&aaMutations1=S%3A417T&nucMutations1=25416T&pangoLineage1=BA.2*&

Top branch here:

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/25161793/164910331-489098b5-fe98-431a-91f3-61b67c839730.png">

**Comment by FedeGueli** [comment]
145 Seqs today. i think that beside BA.2.18 417T lineages should be designated soon. They are all growing fast and showing a stable growth adv everywhere they pop up. @chrisruis

**Comment by AngieHinrichs** [comment]
In the current UShER tree, this is a child branch of #541 (which might be the same as #581?) -- i.e. #541 is BA.2 + C25416T + A22812C, and this is its child branch BA.2 + C25416T + A22812C + C6091T.  This branch is mostly UK unlike the parent #541 branch.  Example sequence: England/NEWC-3B0DFC6/2022

**Comment by AngieHinrichs** [comment]
OK, I see that there is also a branch BA.2 + C25416T + C6091T that has sequences as early as 2022-01-31 (England/PHEC-YYNSUJC/2022), while the earliest BA.2 + C25416T + A22812C + C6091T seems to be 2022-02-17 (England/NEWC-376D20B/2022), so arguably this branch could be a child of BA.2 + C25416T + C6091T instead (they're equal from a parsimony point of view).

**Comment by corneliusroemer** [comment]
Duplicate of #541, designated as BA.2.38
