### ISSUE TITLE
Probable over-identification of BA.3

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#584]
A joint work with @Talyash and @Boltyansky

At GISAID today we found 4,796 sequences identified as BA.3.

We extracted VCF from the sequences and examined for each of them the number of mutations corresponding to it in the consensus of each of the five variants in the Omicron lineage (BA.1-BA.5). The test was performed without deletion mutations.
For each of the sequences we examined which of the five variants had the maximal match :

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Shai/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Shai/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Variant | #
-- | --
BA.1 | 545
BA.2 | 3473
BA.3 | 715
BA.4 | 9
BA.5 | 2

</body>

</html>

So it seems that most of those might not be BA.3. 

The analysis : 
[BA.3 from GISAID.xlsx](https://github.com/cov-lineages/pango-designation/files/8552572/BA.3.from.GISAID.xlsx)

**Comment by hsnguyen** [comment]
I downloaded the GISAID complete BA.3 sequences and run the latest Pangolin on it. 
The majority (85%) of these sequences were called Probable Omicron BA.3-like and they're mostly of low quality.

|          | Count | Mean #Ns |
|----------|-------|----------|
| Probable | 3522  | 6210     |
| Default  | 594   | 70       |

So @aineniamh my feeling is that the rule for Probable BA.3 maybe a bit too relaxed thus overcalled. 
Can you please double-check and consider making it more stringent or just remove the probable call, just like BA.4/5 for now.
Thanks,

**Comment by garfinjm** [comment]
We had a sequencing run with some major wetlab issues last week that I think shows this really starkly, these were all called Probable BA.3 by the latest StaPH-B Pangolin Docker image (4.0.6-pdata-1.6) using accurate analysis mode. I did some manual checking of sites that differ between BA.2 and BA.3 and these all seemed to match better (where there was sequence) with BA.2.

![image](https://user-images.githubusercontent.com/27237515/165587376-100063ca-1211-4bb2-83cf-059c97961ac1.png)


**lineage**|**conflict**|**ambiguity\_score**|**scorpio\_call**|**scorpio\_support**|**scorpio\_conflict**|**scorpio\_notes**|**version**|**pangolin\_version**|**scorpio\_version**|**constellation\_version**|**is\_designated**|**qc\_status**|**qc\_notes**|**note**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
BA.3| | |Probable Omicron (BA.3-like)|0.54|0.07|scorpio call: Alt alleles 29; Ref alleles 4; Amb alleles 21; Oth alleles 0|SCORPIO\_v0.1.8|4.0.6|0.3.17|v0.1.8|FALSE|fail|Ambiguous\_content:0.42|scorpio called lineage BA.3
BA.3| | |Probable Omicron (BA.3-like)|0.46|0.04|scorpio call: Alt alleles 25; Ref alleles 2; Amb alleles 26; Oth alleles 1|SCORPIO\_v0.1.8|4.0.6|0.3.17|v0.1.8|FALSE|fail|Ambiguous\_content:0.37|scorpio called lineage BA.3
BA.3| | |Probable Omicron (BA.3-like)|0.56|0.09|scorpio call: Alt alleles 30; Ref alleles 5; Amb alleles 19; Oth alleles 0|SCORPIO\_v0.1.8|4.0.6|0.3.17|v0.1.8|FALSE|fail|Ambiguous\_content:0.38|scorpio called lineage BA.3
BA.3| | |Probable Omicron (BA.3-like)|0.46|0.02|scorpio call: Alt alleles 25; Ref alleles 1; Amb alleles 28; Oth alleles 0|SCORPIO\_v0.1.8|4.0.6|0.3.17|v0.1.8|FALSE|fail|Ambiguous\_content:0.44|scorpio called lineage BA.3
BA.3| | |Probable Omicron (BA.3-like)|0.46|0.02|scorpio call: Alt alleles 25; Ref alleles 1; Amb alleles 28; Oth alleles 0|SCORPIO\_v0.1.8|4.0.6|0.3.17|v0.1.8|FALSE|fail|Ambiguous\_content:0.45|scorpio called lineage BA.3
BA.3| | |Probable Omicron (BA.3-like)|0.39|0.04|scorpio call: Alt alleles 21; Ref alleles 2; Amb alleles 31; Oth alleles 0|SCORPIO\_v0.1.8|4.0.6|0.3.17|v0.1.8|FALSE|fail|Ambiguous\_content:0.63|scorpio called lineage BA.3
BA.3| | |Probable Omicron (BA.3-like)|0.54|0.07|scorpio call: Alt alleles 29; Ref alleles 4; Amb alleles 21; Oth alleles 0|SCORPIO\_v0.1.8|4.0.6|0.3.17|v0.1.8|FALSE|fail|Ambiguous\_content:0.43|scorpio called lineage BA.3
BA.3| | |Probable Omicron (BA.3-like)|0.54|0.07|scorpio call: Alt alleles 29; Ref alleles 4; Amb alleles 21; Oth alleles 0|SCORPIO\_v0.1.8|4.0.6|0.3.17|v0.1.8|FALSE|fail|Ambiguous\_content:0.43|scorpio called lineage BA.3
BA.3| | |Probable Omicron (BA.3-like)|0.54|0.07|scorpio call: Alt alleles 29; Ref alleles 4; Amb alleles 21; Oth alleles 0|SCORPIO\_v0.1.8|4.0.6|0.3.17|v0.1.8|FALSE|fail|Ambiguous\_content:0.42|scorpio called lineage BA.3
BA.3| | |Probable Omicron (BA.3-like)|0.54|0.06|scorpio call: Alt alleles 29; Ref alleles 3; Amb alleles 21; Oth alleles 1|SCORPIO\_v0.1.8|4.0.6|0.3.17|v0.1.8|FALSE|fail|Ambiguous\_content:0.42|scorpio called lineage BA.3
BA.3| | |Probable Omicron (BA.3-like)|0.54|0.07|scorpio call: Alt alleles 29; Ref alleles 4; Amb alleles 21; Oth alleles 0|SCORPIO\_v0.1.8|4.0.6|0.3.17|v0.1.8|FALSE|fail|Ambiguous\_content:0.43|scorpio called lineage BA.3

We have yet to see any BA.3 in MN, so seeing this many on one run (that aren't geographically clustered at the county level or epi-linked) threw up some red flags.

**Comment by nknox** [comment]
We are seeing the same thing - we only have one true BA.3 positive

![image](https://user-images.githubusercontent.com/8161226/166089726-c332210e-3682-4235-891c-66ccc198d4ca.png)

Additive parent+child calls might not be stringent enough? 
Default BA.3 call: min alt 35
Probable BA.3 call: min alt 18


![image](https://user-images.githubusercontent.com/8161226/166089863-e15d9277-752f-4e2e-9baf-6e5cbc25cbb2.png)

**Comment by aineniamh** [comment]
Thanks for flagging- I've updated the constellation definition to remove the probable call now in version 0.1.9 (https://github.com/cov-lineages/constellations/releases/tag/v0.1.9). This should resolve your issue!
