### ISSUE TITLE
Only 61% of currently BA.2.10 sequences carries the defining mutation ORF1b:S959P 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#585]
Following a comment by @corneliusroemer in an another issue, i noticed that just 61% of currently designated BA.2.10 sequences carry the defining mutation ORF1b:S959P.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.2.10*&aaMutations1=Orf8%3A65V%2CS%3AI68T&pangoLineage1=BA.2*&

@AngieHinrichs @chrisruis

**Comment by chrisruis** [comment]
Thanks @FedeGueli We added a large number of new BA.2 designations in [v1.8](https://github.com/cov-lineages/pango-designation/releases/tag/v1.8) and it looks like they've greatly helped the assignments in this region. There's more designations coming in the next release and future releases that should hopefully further help with this

I'll close this for now
