### ISSUE TITLE
Possible BA.2.3 sublineage with ORF1a:K798N starting in Northern Mariana Islands and Guam (779 sequences in Cov-Spectrum)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#587]
There may be a BA.2.3 sublineage with ORF1a:K798N (nucleotide G2659T) which started in the Northern Mariana Islands and Guam with spread to Hawaii and the mainland USA.  All 456 GenBank sequences (acquired 04-26-2022 via Nextstrain) are USA states or territories.  As of this writing Cov-Spectrum reports 821 BA.2.3+ORF1a:798N sequences with 779 from the USA and small numbers from South Korea, Japan, Australia, Germany, and France, and India.

This possible sublineage may represent ~15% of all SARS-CoV-2 sequences reported form the Northern Mariana Islands through the entire pandemic.

First GenBank sequence: Northern Mariana Islands 2022-01-01

Most recent GenBank sequence: Nebraska USA 2022-04-12

A zip archive of GenBank-formatted and derived metadata and FASTA files for these sequences is available at [BA.2.3-ORF1a_798N.zip](https://github.com/cov-lineages/pango-designation/files/8568599/BA.2.3-ORF1a_798N.zip)

**Comment by alurqu** [comment]
I've realized that all but three of these BA.2.3+ORF1a:K798N GenBank sequences also have ORF1b:A88V (aka ORF1ab:A4489V, nucleotide 13730T).  I'm also finding 24 GenBank BA.2.3 sequences with ORF1b:A88V but not ORF1a:K798N.

Counting only sequences assigned as strictly BA.2.3 (ignoring the handful showing as BA.2.3.2), at the present time Cov-Spectrum shows 821 sequences with ORF1a:K798N, 810 sequences with ORF1b:A88V, and 792 sequences with both.

Cov-Spectrum additionally shows 34 BA.2.3.2 sequences with both ORF1a:K798N and ORF1b:A88V, and at the present time all of the Cov-Spectrum BA.2.3.2 sequences with one of these mutations have the other as well.

Also, to clarify, all of the genomic sequences in the zip archive above are public sequences from GenBank via Nextstrain.  I do not have access to GISAID sequences at this time.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage for designation. Unfortunately, it does not quite meet the criteria for designation at present. There is no clear estimated growth advantage for BA.2.3* + ORF1a:K798N, ORF1b:A88V above BA.2* or BA.2.3*, according to CoV-spectrum (indeed it is estimated as negative in comparison with BA.2.3*). Although, this lineage appears to have played a major role in the N Marianas, it is not associated with any other epidemiological trait (e.g. increased hospitalisation, transmissibility). Should the situation change, please feel free to re-propose, as a new issue, for designation with the additional evidence.
