### ISSUE TITLE
BA.1.1 +C2470T+C21595T sublineage carrying S:P9L (956 seqs) with a cluster of interest (10seqs USA/Denmark)/) with S:452R/S:899S/S:346E

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#588]
Here i want to propose a sublineage of BA.1.1, in the branch with C2470T and C21595T, that acquired an additional spike mutation in the signal peptide : S:P9L.
Tree:
![chrome_screenshot_1651044283759](https://user-images.githubusercontent.com/87669813/165464943-fcf20670-73ea-4246-8b59-9ef5d11b0249.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3419b_82b3c0.json?c=gt-S_9&label=nuc%20mutations:C21588T

It has been circulating widely in USA (890 out of 950 seqs) showing a slight disadvantage vs BA.2 baseline (18%) 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A9L&nucMutations=C21595T&pangoLineage=BA.1.1*&

I think it is worth to be designated after 
@shay671 @talyash @boltyansky discovered a cluster of interest belonging to this sublineage:
4 Sequences: 
 hCoV-19/USA/NC-CDC-MMB14929914/2022|EPI_ISL_12081502|2022-04-05, hCoV-19/Denmark/DCGC-488003/2022|EPI_ISL_12207587|2022-04-15, hCoV-19/Denmark/DCGC-488308/2022|EPI_ISL_12207889|2022-04-15, hCoV-19/Denmark/DCGC-488692/2022|EPI_ISL_12244166|2022-04-14

3 from Denmark and 1 from USA  heavily mutated:
NSP2:N8N
NSP3:P153L
NSP3:A614V
NSP3:I750T
NSP3:F776F
NSP12b:F39F
NSP12b:K82R
S:R346E
S:L452R
S:A899S
![IMG-20220427-WA0006](https://user-images.githubusercontent.com/87669813/165466617-0d71569c-8f5f-452a-b34f-b0d7cf7cbc4b.jpg)

list of sequences:
[contributors (4).csv](https://github.com/cov-lineages/pango-designation/files/8638194/contributors.4.csv)

**Comment by shay671** [comment]
Two new samples for the sub-lineage of this sub-lineage that was given here popped up yesterday, again from the US and Denmark. 
This is a clear saltation variant, and it clearly can circulate. It has High NS% and mutations in converged sites - The mutation of BA.1.1 at 346 went a step further and changed to G with another SNP at the 346 codon. Also, a mutation in position 452 in S converged not only in many VOC/VOIs but also in sub-lineages of Omicron.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3abad_ab4ac0.json

![image](https://user-images.githubusercontent.com/80166370/165792840-a0b2593c-629f-446a-b000-da2822fd180a.png)


The 6 samples :


EPI_ISL_12285890
EPI_ISL_12207587
EPI_ISL_12207889
EPI_ISL_12244166
EPI_ISL_12081502
EPI_ISL_12302304

**Comment by FedeGueli** [comment]
Thx @shay671 and @corneliusroemer for your updates and analysis. i ll update subsequently the title

**Comment by silcn** [comment]
The correct mutation is S:346E, not S:346G as it says in the title. Nextstrain gets confused by the two nucleotide mutations A22598G and G22599A in the same codon, which on their own produce 346G and 346K respectively, but together produce 346E. Worth noting R->E is basic to acidic so may have a larger antigenic effect than previously seen substitutions at S:346.

**Comment by FedeGueli** [comment]
Thx very much @silcn for the correction.
I have corrected that.

Here i add a simple CV-SP query to monitor nr of seqs belonging to the cluster of interest within this sublineage:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A452R%2CS%3A9L%2CS%3A899S&nucMutations=C2470T%2CC21595T&pangoLineage=BA.1.1*&

**Comment by FedeGueli** [comment]
2 more sequences (4USA + 4DK)

**Comment by shay671** [comment]
The 8 samples are : 
EPI_ISL_12207587
EPI_ISL_12207889
EPI_ISL_12244166
EPI_ISL_12081502
EPI_ISL_12285890
EPI_ISL_12497422
EPI_ISL_12507449
EPI_ISL_12302304

**Comment by FedeGueli** [comment]
The new ILVR (Israeli Variant Radar) brought to my attention a second cluster of interest belonging to this sublineage, that popped up in Peru' in April.
There are 5 sequences:
hCoV-19/Peru/JUN-INS-16561/2022|EPI_ISL_12530248|2022-04-04, hCoV-19/Peru/JUN-INS-16562/2022|EPI_ISL_12530249|2022-04-04, hCoV-19/Peru/JUN-INS-16563/2022|EPI_ISL_12530250|2022-04-08, hCoV-19/Peru/JUN-INS-16564/2022|EPI_ISL_12530251|2022-04-09, hCoV-19/Peru/JUN-INS-16565/2022|EPI_ISL_12530252|2022-04-04

Checking it with @c19850727 @shay671 it was immediately clear that some recombination event in orf1ab  could have happened or that these seqs could have been related with a chronically ill infected:
![chrome_screenshot_1651959911107]https://user-images.githubusercontent.com/87669813/167272647-afd5801c-249f-4149-bbed-ea4a302304aa.png)


Unexpectedly we found that the first 9000 nuc of these sequences were very similar to the P.1.7.1.
So we went further into the analysis finding a
Breakpoint likely between 9804 and 10028 (Nsp4-nsp5)
5' end -9803: P.1.7.1
9804- 3' end: BA.1.1+ S:9L (proposed here)

Short description:

Parent 1
P.1.7.1 putative parental cluster were circulating in Peru' between July and s
September 2021:
7 sequences: EPI_ISL_4280003 EPI_ISL_5199300 EPI_ISL_5505922 EPI_ISL_5503572 EPI_ISL_5505929 EPI_ISL_5505286 EPI_ISL_4280280

Parent 2
BA.1.1 with C2470T+C21595T+S:9L
the putative parental cluster is basal to the proposed lineagein this issue and contains a lot of identical sequence. Conventionally I have selected the 2021 ones which circulated in USA in december 2021 (but then it has spread south to Chile,Mexico,Brazil too)
Sequences: 
EPI_ISL_8290265
EPI_ISL_8157419
EPI_ISL_8081478
EPI_ISL_8157521
EPI_ISL_8157523
EPI_ISL_8290287
EPI_ISL_8290395
EPI_ISL_8918094
EPI_ISL_8427256



Recombinant (child)
5' end of genome -9803: P.1.7.1
9804- 3' end of genome: BA.1.1+ S:9L 
Private mutations:
4 on the 'Gamma' side:
C1102T
C4763T  
C6936T
A7785G
4 on the 'Omicron' side:
G24215A 
A25146G 
C26882T 
C28744T  

Considering that the 'Gamma side' is 1/3 of the genome and the 'Omicron side' is 2/3 of the genome,
Considering the putative parental Gamma was last sequenced in september 2021 and the first putative parental Omicron in December 2021
this mutational pattern (4 private muts on Gamma side and 4 in Omicron side) is compatible with a possible coocirculation of the two putative parental lineages.

It has to be noticed that in Peru' the last P.1.7.1 was sequenced in January 2022 (showing 3 private mutation in the first 10000 nucleotides).

Here the head to head nucleotides comparison between the recombinant child and the two putative parental lineages:
https://docs.google.com/spreadsheets/d/1bsQ4J7jVaIHiKGbOAzLd_ZppeHdGRMHuky8TTQQS7rQ/edit?usp=drivesdk

So, before proposing it as separate recombinant lineage,  we ask Scientists 
@Wen1953 @OrsonMM @Vjimenez-vasquez @LuisBarcenaF ,
involved in genomic surveillance system in Peru' , 
and very active on this designation page
to help us in understanding context and checking raw data of these sequences and verify if it could be contamination or coinfection rather than recombination and whatever else they could do to assess this cluster.
 (Thx @tompeacock for your help and advices) 



CC: @corneliusroemer @chrisruis @AngieHinrichs

**Comment by FedeGueli** [comment]
10seqs today of the cluster of interest belongong to this proposed lineage 6 Usa +4 Dk

**Comment by Wen1953** [comment]
Hi @FedeGueli, we had review the 5 possible new recombinant raw data (BA.1.1+ S:9L) and we see that coverage is uniform in 9804-10028bp except for one sequence that has missing data, all are from one region in Peru (Junin). Mutations C1102T, C4763T, C6936T, A7785G, G24215A, A25146G, C26882T and C28744T are well defined.
The parental 1 (P.1.7.1) is well defined in all mutations described attached (C241T, T733C, C2749T, C3037T, T3049C, C3828T, A5648C, A6319G, A6613G, C9344T, C10116T), except for C9803T that doesn't show a completely coverage to T. It came from Lima (1), Ica (1) and Junin (5) region. All sequences are from aleatory surveillance.

![Captura de pantalla de 2022-05-13 12-01-05](https://user-images.githubusercontent.com/89021119/168332819-851ed46f-dc19-439a-a4b5-93248d0e0547.png)

**Comment by FedeGueli** [comment]
@Wen1953 thank you very very much for your analysis of that potential recombinant. So you havet any hints that could point to some pipeline issues or to contaminations, right?
Are you aware of any metadata linked to those sequences?
We would better wait a bit if this virus will be sampled again how and where. In that case if you are interested in we could write a lineage proposal together.

**Comment by Wen1953** [comment]
@FedeGueli we appreciate your invitation to collaborate. We can work in this together, but as you say we think that we must wait for a bit until new samples appear. 
We have access to metadata. It didn't show a relationship between other conditions except for source (all are from Junin). We don't see some kind of contamination in raw data.
We will continue monitoring some appearance of this potentially recombinant. We'll be in touch.

**Comment by chrisruis** [comment]
Thanks @FedeGueli The S:P9L clade looks to be associated with USA so has an epidemiological event. However, it's stayed at a very low proportion of BA.2 sequences in USA so doesn't warrant a designation at this stage. The clade with S:452R seems to have 12 sequences now and hasn't been seen since April in Denmark so we won't add that one for now

If the potential P.1.7.1 - BA.1.1 recombinant has grown, it would definitely be worth opening a separate issue for that. Thanks

**Comment by FedeGueli** [comment]
@Wen1953 @orsonMM @chrisruis two more sequences of the Gamma-B.1.1 popped up back from April :  

EPI_ISL_13622876

EPI_ISL_13622873

Does anyone know if they resequenced the same samples or these are from new patients?
