### ISSUE TITLE
Potentially new BA.1.X sub-lineage with S:Q853R and ORF1a:H45R mutations from Lima (Peru)

### ISSUE THREAD

**Issue by OrsonMM** [cov-lineages/pango-designation#589]
Description
New possible new omicron BA.1.X sub-lineage with S:Q853R and ORF1a:H45R mutations proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru. 

Earliest sequence: 2022-04-01
hCoV-19/Peru/LIM-INS-16443/2022 (EPI_ISL_12220761)

Most recent sequence: 2022-04-10
hCoV-19/Peru/LIM-INS-16545/2022 (EPI_ISL_12256517)

Countries circulating:
Peru (6)

Evidence:

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31387_983910.json?c=gt-S_853

<img width="1704" alt="new_853_1" src="https://user-images.githubusercontent.com/12600107/165590728-5efc1e26-0801-427e-b6f1-052ecc0a21fc.png">

Local Nextstrain

<img width="1444" alt="new_853_2" src="https://user-images.githubusercontent.com/12600107/165591319-2ce2160c-f1e2-42f1-b4bb-66f6f6f208d5.png">

Genomes 

EPI_ISL_12220746
EPI_ISL_12220761
EPI_ISL_12220767
EPI_ISL_12256515
EPI_ISL_12256517
EPI_ISL_12256535

**Comment by OrsonMM** [comment]
Two sequences more 

EPI_ISL_12530308
EPI_ISL_12591017

**Comment by FedeGueli** [comment]
Thx for flagging this one @OrsonMM , we ha e already seen fusion peptide mutations conferring some advantage as S:850F in AY.126. So better monitoring it.
(btw @OrsonMM i tagged you and your colleagues in a comment in #588 if you could check that i will be grateful! thx)

**Comment by chrisruis** [comment]
Thanks @OrsonMM This seems to have stayed very small so we won't designate for now
