### ISSUE TITLE
Proposal for new lineage within B.1 as 20% of the samples labelled as B.1.617 don't fit the lineage description

### ISSUE THREAD

**Issue by animesh-workplace** [cov-lineages/pango-designation#59]
## Description

Sub-lineage of: B.1
Earliest sequence: 2020-12-12 (hCoV-19/India/ILSGS00941/2020) (EPI_ISL_1663516)
Most recent sequence: 2021-04-16 (hCoV-19/Australia/NSW4485/2021) (EPI_ISL_1633353)
Countries circulating: Australia, Bahrain, Germany, India, Italy, Singapore, UK, USA

Sequences were downloaded from GISAID on 22 April, 2020. 865 sequences were labelled B.1.617 and out of that 180 (20.80%) sequences were found to have the below stated mutations which is not characteristic of B.1.617 (L452R and E484Q mutations co-occuring together). Instead we see, S:T478K with S:L452R co-occuring together.

The location of S:T478K is within the interaction domain with the human receptor ACE2, roughly encompassing amino acids 350 to 550 of the SARS-CoV-2 Spike protein.  In particular, the position of S:T478K is on the interface with ACE2. The location
of S:T478K in the interaction complex with human ACE2 may affect the affinity with human cells and therefore influence viral infectivity. Providing a lineage would be helpful in monitoring.

### List of characteristic amino acid changes of the new lineage:

| Gene | Amino acid | 
| --- | --- |
| M gene | I82T |
| ORF1b | P314L |
| ORF3a | S26L |
| S gene | T478K |
| S gene | D614G |
| S gene | P681R | 
| S gene | L452R |
| S gene | D950N | 
| N gene | R203M |
| N gene | D63G | 
| ORF7a | V82A | 
| ORF7a | T120I |
| ORF9b | T60A |

It was also observed that some of samples have the following deletions (N = 180)

| Deletion | Percentage |
| --- | --- |
| S:F157del | 83.88% |
| S:R158del | 83.88% |
| ORF8:D119del | 71.11% | 
| ORF8:F120del | 71.11% | 

It was observed that all 4 of these deletions occur together in 70% of the samples

## Genomes

[accession_id.txt](https://github.com/cov-lineages/pango-designation/files/6366390/accession_id.txt)

## Evidence

![image](https://user-images.githubusercontent.com/55780901/115889038-35743500-a471-11eb-8e96-37e8ca0830f9.png)
![image](https://user-images.githubusercontent.com/55780901/115889130-491f9b80-a471-11eb-8a43-4e479c467cf6.png)
![image](https://user-images.githubusercontent.com/55780901/115889199-5b013e80-a471-11eb-89b5-8c90b994348e.png)
![image](https://user-images.githubusercontent.com/55780901/115889258-69e7f100-a471-11eb-9c7f-30be0e67c84f.png)
![image](https://user-images.githubusercontent.com/55780901/115889354-7e2bee00-a471-11eb-96b0-ddaeb7742722.png)
![image](https://user-images.githubusercontent.com/55780901/115889418-8d12a080-a471-11eb-96a9-daafba745541.png)
![image](https://user-images.githubusercontent.com/55780901/115889530-a6b3e800-a471-11eb-8ca3-eeef07c83fb0.png)

**Comment by rambaut** [comment]
B.1.617 has been split into B.1.617.1, B.1.617.2, B.1.617.3 (B.1.617.2 doesn't have E484Q).

**Comment by animesh-workplace** [comment]
@rambaut In which sub-lineage does this set of mutations fit into?

**Comment by AngieHinrichs** [comment]
@animesh-workplace 85 of your sequences are assigned to B.1.617.2 in pango-designation/lineages.csv .  The rest of your sequences do not appear in pango-designation/lineages.csv, but presumably all of your sequences should now be assigned to B.1.617.2 by the latest version of pangolin and pangoLEARN if you run `pangolin --update`.

These are the commands I used to search for your sequences (I have an up-to-date clone of pango-designation in my ~/github/ directory):

```
sed -e 's@hCoV-19/@@;' accession_id.txt | grep -Fwf - ~/github/pango-designation/lineages.csv | wc -l
85

sed -e 's@hCoV-19/@@;' accession_id.txt | grep -Fwf - ~/github/pango-designation/lineages.csv | grep -vF B.1.617.2 | wc -l
0
```

**Comment by animesh-workplace** [comment]
@AngieHinrichs Yes you are correct most of it is labelled B.1.617.2 and only 18 are labelled as B.1.617

**Comment by animesh-workplace** [comment]
@AngieHinrichs Am I correct in saying that defining spike substitutions of 
```B.1.617``` are ```S:P681R and S:L452R```
 ```B.1.617.1``` are ```S:E484Q, S:E154K, S:Q1071H, S:T95I``` 
```B.1.617.2``` are ```S:T478K ,S:T19R, S:D950N ```
```B.1.617.3`` are ```S:T19R, S:E156G, S:E484Q```

**Comment by rambaut** [comment]
@animesh-workplace Yes - but at the moment we have only one representative of B.1.617 (i.e., with `S:P681R` and `S:L452R`) but none of the other sublineage mutations.

**Comment by animesh-workplace** [comment]
@rambaut I don't understand the ` one 'designated' representative of B.1.617`. Do you mean one representative from India? or one designated representative to describe the entire lineage substitutions.
