### ISSUE TITLE
Less than 3% of sequences assigned to BA.2.13 carries defining mutation S:L452M

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#592]
@josetteschoenma pointed me that the vast mayority of sequences assigned to BA.2.13 doesnt carry the defining mutation S:L452M.

I think that is due the 23767G mutation in the branch leading to S:L452M.

Evidences:
BA.2.13 on covspectrum: (12000+ seqs)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.2.13*&aaMutations1=S%3AL452M&nucMutations1=22792T%2C23767G&pangoLineage1=BA.2*&

Real BA.2 +22792T+23767G+S:L452M (321seqs)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AL452M&nucMutations=22792T%2C23767G&pangoLineage=BA.2*&

@AngieHinrichs @chrisruis @corneliusroemer 

(Pangolearn)

**Comment by corneliusroemer** [comment]
Thanks @FedeGueli you're right, most BA.2.13 lack S:L452M. This can be fixed for pangoLEARN by adding designations to BA.2 that share all mutations but S:L452M @chrisruis

**Comment by geertmartens** [comment]
In the recent sequences provided by AZ Delta hospital, Roeselare, Belgium, we estimate that around 30% of sequences classified as BA.2.13 do carry the S:L452M mutation. However, we notice amplicon dropout in this critical region (S:430-508) with low coverage ranging from 2-10 reads. As a consequence, the mutation, if present, is often not noticed and denoted by NNN in consensus FASTA

**Comment by chrisruis** [comment]
We added a large number of new BA.2 designations in [v1.8](https://github.com/cov-lineages/pango-designation/releases/tag/v1.8). From what I can see in the latest UShER tree, these new designations seem to have fixed this problem as all sequences assigned BA.2.13 have S:L452M. The BA.2.13 clade also looks relatively clean and starts on the S:L452M branch. It might take a bit longer for this to filter through to GISAID as they will need to run the new version on all sequences. I'll close this for now and we can reopen if needed
