### ISSUE TITLE
Possible BA.1 Lineage with S: G446S, K1205R and M:E19Q mutations

### ISSUE THREAD

**Issue by Vjimenez-vasquez** [cov-lineages/pango-designation#594]
**Description**
Possible BA.1 omicron sub-lineage with Spike mutations G446S and K1205R, and M:E19Q proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**Earliest sequence: 2021-12-19**
hCoV-19/Peru/LIM-INS-11276/2021 (EPI_ISL_8716077)

**Most recent sequence: 2022-04-09**
hCoV-19/Peru/LIM-INS-16558/2022 (EPI_ISL_12256522)

**Countries circulating:**
Canada (1), Chile (3), Germany (1), Japan (6), Mexico (1), Netherlands (2), Peru (54), Poland (1), South Korea (2), Switzerland (1), United Kingdom (3), USA (4)

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/8594941/genomes.txt)

**Evidence: Local Nexstrain (Peru)**
![genome](https://user-images.githubusercontent.com/89874227/166073884-ba478895-be75-4c77-a531-328a8357fbe8.png)
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/8594941/genomes.txt)

**CoV-Spectrum**
![spectrum](https://user-images.githubusercontent.com/89874227/166074077-0c128b6a-c275-4d5e-bd33-8726849d4c10.png)

**Comment by corneliusroemer** [comment]
I only get 4 sequences with this covSpectrum query - so I'm gonna close it as it doesn't seem to be a real lineage? Also BA.1 is kind of dead now anyways.

https://cov-spectrum.org/explore/World/AllSamples/from=2021-01-03&to=2023-01-01/variants?aaMutations=M%3AE19Q%2CS%3AG446S%2CS%3AK1205R&
