### ISSUE TITLE
Proposal for new lineage within B.1

### ISSUE THREAD

**Issue by anthonypwest** [cov-lineages/pango-designation#6]
**Description**

Sub-lineage of: B.1
Earliest sequence: 2020-11-23
Most recent sequence: 2021-01-29
Countries circulating: A lineage predominantly circulating in New York but with a few exports to other countries. Characterised by spike mutations T95I and D253G, plus others.
The most frequent spike mutation pattern is L5F T95I D253G E484K D614G A701V, with a smaller fraction having S477N instead of E484K.

Other common coding changes in this lineage are:
N P199L M234I
NS3 P42L Q57H
NS8 T11I
NSP2 T85I
NSP4 L438P
NSP6 S106del G107del F108del 
NSP12 P323L
NSP13 Q88H

**Genomes**
[B.1.XX_genomes.txt](https://github.com/cov-lineages/pango-designation/files/5965176/B.1.XX_genomes.txt)

List of genomes, collated 2021-02-10, attached.

**Evidence**

Phylogenetic tree (PDF and image). Spike mutations and bootstrap values are indicated. Proposed new lineage includes all sequences except for those in the grey shaded box at the top.
[B.1.XX_tree_spike_mutations.pdf](https://github.com/cov-lineages/pango-designation/files/5965188/B.1.XX_tree_spike_mutations.pdf)

<img width="727" alt="B 1 XX_tree_image" src="https://user-images.githubusercontent.com/56272592/107637899-af8f6e80-6c23-11eb-9342-740a3119842f.png">

Phylogenetic tree file:
[B.1.XX_tree.txt](https://github.com/cov-lineages/pango-designation/files/5965217/B.1.XX_tree.txt)

**Proposed lineage name**

To be determined as the the next available designation within B.1

**Comment by aineniamh** [comment]
Hi Anthony, thanks for posting the issue. We've just tagged a new release of the lineage designations [here](https://github.com/cov-lineages/pango-designation/releases/tag/v1.0.2) that include this new lineage as B.1.526. 

This lineage, with the sequences you've mentioned here, will get added into the pangoLEARN model training today. When that's finished a new release of pangoLEARN will be tagged [here](https://github.com/cov-lineages/pangoLEARN/releases) and the website updated. 

Thanks again, going to now mark this issue as resolved.

**Comment by anthonypwest** [comment]
Hi Áine,

Thanks for handling this so quickly! Your description of the lineage on the release notes is accurate, but if it’s possible to add a line, I have a request.

My primary concern about this lineage is spike mutation E484K (in about 53% of the sequences as so now) - a worrisome mutation shared with B.1.351 and B.1.1.248, which is problematic for antibody binding (for example: Bloom, et al, https://doi.org/10.1016/j.chom.2021.02.003). 

So could you add “Spike mutation E484K is present in about half of this lineage (as of 2/10/21)” or whatever phasing you prefer that indicates that E484K is often present in members of this lineage.

Thanks,
Anthony

**Comment by AngieHinrichs** [comment]
Would it make sense to add s B.1.526.1 just for the branch with E484K?

**Comment by anthonypwest** [comment]
That’s a very good question. I don’t know how situations like this are usually handled by the Pango system. Both the E484K-containing and the non-E484K-containing isolates are mostly being collected in the same geographic area (New York City). With regards to antibody therapeutics (as possibly vaccines??), E484K is a particular concern. Maybe Prof. Rambaut would have an opinion?

Anthony

**Comment by rambaut** [comment]
There are two problems with giving a sublineage for the 484K carrying genomes - the first is that the 484K is the only defining mutation and with other lineages we have seen 484K coming up multiple times independently (for example with the B.1.1.7 variant in the UK we have had more than 5 independent cases of 484K). The second is, as you point out, this is all in one geographical area. If it was any other mutation it would not qualify.  I think we will hold off for now.

**Comment by aineniamh** [comment]
Agree with what Andrew said, but I'm happy to add the line as you requested @anthonypwest to give more information about that particular lineage.

**Comment by anthonypwest** [comment]
Thanks!
