### ISSUE TITLE
New sublineage of B.1.1.7 including S:E484K

### ISSUE THREAD

**Issue by fabou-uobaf** [cov-lineages/pango-designation#60]
# New lineage proposal 

by Fabian Amman, Lukas Endler, Anna Schedl, Petr Triska, Andreas Bergthaler 

## Description 

Sub-lineage of:		B.1.1.7 
Earliest sequence:	2021-02-22 (2021-03-08 in Tyrol) 
Most recent sequence:	2021-03-30 
Countries circulating:	Austria (124 sequences), Germany (6), Netherlands (3), Sweden (1), Poland (1), Czech Republic (1)

We aim to report the observation of a newly emerging variant of the pangolin lineage B.1.1.7.

The so far sequenced cases are dominantly reported from the Austrian federal State of Tyrol (124 samples). Single additional sequences which match the Tyrolian have been detected scattered across Europe (12 samples).

On the amino acid level it is distinguished from the currently circulating B.1.1.7 strains most prominently by its S:E484K mutation [1,2]. On the nucleotide level the emerging strain differs in three nucleotides: C5944T, G23012A, G28884C.

This new strain showed quickly rising incidence rates in the geographically distinct region of district Schwaz as well as other regions of Tyrol, with >1500 cases diagnosed by mutation-specific PCR so far. Its spread coincides with an intense vaccination campaign with BNT162b2 starting in March, which had been initiated due to a previous surge of B.1.351 in this region.

## Genomes

Accompanying csv file with locations, dates, and GISAID IDs of suggested samples. 
[genomes.csv](https://github.com/cov-lineages/pango-designation/files/6367870/genomes.csv)

## Evidence 

Please find attached a visualization of the cluster using "UShER: Ultrafast Sample placement on Existing tRee". 

UShER_Tree.png (UShER_Tree_zoom.png)

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/11571552/115915779-1a56f480-a474-11eb-9396-e1b2d016c826.png">

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/11571552/115915828-3195e200-a474-11eb-8106-4cbc3c7444e7.png">

The bootstrap value of 76 was calculated using iqtree, applying ultrafast bootstrap with 1000 replicas, on a set of all sequenced SARS-CoV-2 genomes from Austria, classified as B.1.1.7 (including the newly emerging B.1.1.7 + E484K), and all European samples from GISAID which are classified as B.1.1.7 + E484K. 

## References 

[1] Collier, D.A., De Marco, A., Ferreira, I.A.T.M. et al. Sensitivity of SARS-CoV-2 B.1.1.7 to mRNA vaccine-elicited antibodies. Nature (2021). https://doi.org/10.1038/s41586-021-03412-7 
[2] Jangra, S., Ye, Ch., Rathnasinghe, R. et al. SARS-CoV-2 spike E484K mutation reduces antibody neutralisation. The Lancet (2021). https://doi.org/10.1016/S2666-5247(21)00068-9

**Comment by chrisruis** [comment]
Thanks @fabou-uobaf for submitting. We wouldn't normally designate a new lineage based on a single mutation alone. It doesn't look like there's a clear epidemiological event associated with this clade so we would recommend referring to these sequences as B.1.1.7+E484K. Thanks again
