### ISSUE TITLE
AY.98.1 sublineage with Orf3a:Y109C that keeps circulating in Germany (495 seqs / 34 seqs in 2022/ 4 in April'22)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#604]
Not having been assigned through this designation page 
first i sum a bit what is AY.98.1
AY.98.1 is a lineage defined by Orf1a:E87D where AY.98 starts
and C7768T where AY.98.1 starts but the vast mayority of AY.98.1 sequences carries S:P251L, ORF1a:E1724D and Orf8:A65S beyond NUC: C19524T and G2518T.
 . 
It reached around 30000 sequences being massively sequenced especially in Europe from summer 2021 to Omicron rise. Its prevalence was quite high in Slovenia (where the covspectrum query unexpectedly put first sequences at the end of 2020) and ranged from 0,8 to 4% in  Italy, France, Germany, Denmark.

In the late summer 2021 a sublineage of AY.98.1 characterized by Orf3a:Y109C and Nuc: G370T emerged in Germany and it is circulating there through today:
First sequence: 36/2021 Germany
Last sequence: 17/2022 Germany (BW)
Nr of Sequences: 488 (covspectrum, but i count 984 seqs on the Usher)
Sequences in 2022: 33
Sequences in April 2022: 4
List of sequences:
[contributors (16).csv](https://github.com/cov-lineages/pango-designation/files/8636098/contributors.16.csv)

[Covspectrum overview](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=Orf3a%3AY109C&nucMutations=G370T&pangoLineage=AY.98.1*&)

[Usher tree:](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_346ae_433510.json?branchLabel=aa%20mutations&c=gt-nuc_370&label=nuc%20mutations:G526T)
![Schermata 2022-05-05 alle 23 19 44](https://user-images.githubusercontent.com/87669813/167027532-da62bb3f-3d45-489c-9412-ac668a2fe210.png)

The cluster of four sequences sampled in Germany during April 2022 has the following mutations:
Nuc: T25614C
then
Orf1b:T2084I (C19718T)
then
Nuc: C4012T
ORF1a:G519S (G1820A)
then
Nuc: G28001T
then
Nuc: C26013T,C23929T
ORF1a:P1096S (C3551T)
![Schermata 2022-05-05 alle 23 26 41](https://user-images.githubusercontent.com/87669813/167028423-c2efbd1d-c9c9-4728-a13b-aafbdb963ff8.png)
Most recent sequences subtree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_346ae_433510.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C19718T

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage AY.98.1.1 with 558 newly designated sequences, and 11 updated designations from AY.98.1. Defining mutation(s) A25718G (Orf3a:Y109C), then G370T (synonymous).
