### ISSUE TITLE
Proposal for new sub-lineage of BA.2.3 with C13326T (ORF1ab: T4354I) and A20214G (synonymous) in Japan (858 sequences as of 2022-06-07, 13.4% of BA.2.3 in Japan)

### ISSUE THREAD

**Issue by takaabe8050** [cov-lineages/pango-designation#605]
By Japan COVID-19 Open Data Consortium

Description
Sub-lineage of: BA.2.3 (128 sequences)
Earliest sequence: 2022/01/25 (hCoV-19/Japan/PG-190369/2022)
Most recent sequence: 2022/04/12 (hCoV-19/Japan/TMDU_No343/2022)
Countries circulating: Japan (128 sequences)

Associated mutations
C13326T (ORF1ab: T4354I)
A20214G (synonymous)

Genomes
[genome_list.txt](https://github.com/cov-lineages/pango-designation/files/8641436/genome_list.txt)

Evidence
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3fc5e_481bd0.json?c=userOrOld

![new_proposal220506](https://user-images.githubusercontent.com/89957075/167153492-7dda35a1-11a2-417a-95ea-0a90187fea4c.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C13326T%2CA20214G&

Proposed lineage name
Next BA.2.3.X

**Comment by corneliusroemer** [comment]
Thanks for proposing this lineage. This lineage doesn't seem to have a growth advantage over BA.2.3 so it may stay quite small. Is there a particular reason why you think this lineage is interesting?

<img width="1897" alt="image" src="https://user-images.githubusercontent.com/25161793/167303917-2635e6b9-6d33-4acc-bd28-76c234adf3b3.png">

https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?pangoLineage=BA.2.3*&nucMutations1=C13326T%2CA20214G&pangoLineage1=BA.2.3*&analysisMode=CompareToBaseline&

**Comment by takaabe8050** [comment]
Thanks for your comment.
As you pointed out, this proposed sublineage is only 4.5% (=130/2864) of the BA.2.3 isolated in Japan, which is a small number.

However, our proposed sublineage is characterized by its high locality within Japan.
Therefore, I believe that it would be useful for genome surveillance in Japan if this proposed sublineage can be easily confirmed together with the conventional BA.2.3 and BA.2.3.1, the main lineage of the BA.2 lineage in Japan.
Thank you in advance for your consideration.

**Comment by takaabe8050** [comment]
Thanks @corneliusroemer 

For the updated data, the proposed lineage has increased to 13.4 % (= 858 / 6399) of BA.2.3 in Japan.

![update_proposelineage220607](https://user-images.githubusercontent.com/89957075/172299917-0822dfa8-49d7-4af2-a424-007a2b0a9017.png)
