### ISSUE TITLE
Potential BA.1*/BA.2* Recombinant with Likely Breakpoint at NSP6/NSP9 (56 Seqs as of 2022-05-16 in France, Israel, UK and US)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#606]
Although this potential recombinant sublineage doesn't meet the minimum criteria of 50 sequences, I thought it's still worth proposing considering it is recently re-emerging in multiple regions (especially in the US), 2 months after the first sampling (in France).

### Description
**Recombinant between**: BA.1* & BA.2*
**Earliest sequence**: 2022/2/28 (France)
**Most recent sequence**: 2022/4/29 (US-NC)
**Countries circulating**: France, Israel, UK (Scotland), US (NJ, NC, DC, NY, PA, FL, MD)
**Likely breakpoint**: between 11540 and 12879 (NSP6-NSP9).
**Mutations on branch**: A1585G, T11049C (ORF1a:V3595A), C12085T (homoplasic), A22351G, C26058T (homoplasic)

**Conserved Nuc mutations** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/167232611-3724f4fa-bc49-4b18-b282-97132d8ad556.png)
**Cov-spectrum query**: T11049C, C12085T, A22351G, C26058T
**GISAID query:** N_S413R, NS3_T223I, NSP3_A1892T, NSP6_I189V, NSP6_V26A, NSP13_R392C

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/167232712-8d5766e9-2e05-4aa2-8795-a0bd7f25c03d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_59ac_5c90c0.json?branchLabel=nuc%20mutations&c=gt-nuc_12085&label=nuc%20mutations:C2470T

Genomes:### 
EPI_ISL_11248486, EPI_ISL_11853906, EPI_ISL_11953320, EPI_ISL_11981157, EPI_ISL_12047966, EPI_ISL_12087269, EPI_ISL_12169920, EPI_ISL_12181532, EPI_ISL_12181916, EPI_ISL_12256119, EPI_ISL_12280646, EPI_ISL_12302275, EPI_ISL_12302321, EPI_ISL_12303240, EPI_ISL_12304717, EPI_ISL_12305005, EPI_ISL_12325537, EPI_ISL_12330186, EPI_ISL_12421170, EPI_ISL_12433854, EPI_ISL_12462094, EPI_ISL_12462213, EPI_ISL_12499373, EPI_ISL_12499906, EPI_ISL_12502489, EPI_ISL_12506477, EPI_ISL_12506641, EPI_ISL_12506834, EPI_ISL_12507171, EPI_ISL_12558951, EPI_ISL_12566224, EPI_ISL_12566254, EPI_ISL_12566304, EPI_ISL_12566309, EPI_ISL_12566311, EPI_ISL_12566330

**Comment by c19850727** [comment]
44 sequences as of 2022-05-09, with 8 new sequences uploaded from US-MD, PA, NJ, NC, RI, NH.

**Comment by c19850727** [comment]
48 sequences as of 2022-05-10. Latest batch were from US-DC and US-NC.

**Comment by c19850727** [comment]
50 sequences as of 2022-05-11.

**Comment by c19850727** [comment]
52 sequences as of 2022-05-12, and now found in one more US state (VA).

**Comment by c19850727** [comment]
56 sequences as of 2022-05-16, and now found in one more US state (MO).

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XY with 36 newly designated sequences, and 0 updated designations.

**Comment by JosetteSchoenma** [comment]
XY
