### ISSUE TITLE
Potential BA.2*/BA.1*/BA.2* Recombinant with Likely Double Breakpoints (29 Seqs as of 2022-05-06 in Germany, Norway, Israel and UK)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#608]
Although this potential recombinant sublineage doesn't meet the minimum criteria of 50 sequences, I thought it's still worth proposing considering:

- It has interesting double breakpoints and dual ORF3a substitutions;
- It has been found in different countries;
- it is recently re-emerging in Germany, 2 months after the first sampling in the UK.

### Description
**Recombinant between**: BA.2* & BA.1* & BA.2*
**Earliest sequence**: 2022/2/27 (UK-England)
**Most recent sequence**: 2022/4/28 (Germany-NW)
**Countries circulating**: Germany (NW, RP, HH), Israel, Norway, UK (England)
**Likely breakpoint 1**: 24506-26048 (Spike S2/ORF3a)
**Likely breakpoint 2**: 27385-29509 (ORF6/N protein), with S2M deletion.
**Mutations on branch**: G10073A (ORF1a:A3270T), T25715C (ORF3a:L108P), G25855T (ORF3a:D155Y)

**Conserved Nuc mutations** (those in red frames are likely from BA.1*):
![image](https://user-images.githubusercontent.com/86835836/167235363-1d8c8e47-db1b-4980-b474-c6d491c85cec.png)
**Cov-spectrum query**: A1585C, G10073A, T25715C, G25855T
**GISAID query**: NSP1_S135R, N_S413R, M_D3G, NS3_L108P, NS3_D155Y

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/167235434-2676459a-7b7f-42f1-b8e1-03e1b99562f7.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12f31_5da050.json?branchLabel=nuc%20mutations&c=gt-nuc_25715&label=nuc%20mutations:C745A,C2189T,A8882C,T18299C,C25708T

**S2M deletion**:
![image](https://user-images.githubusercontent.com/86835836/167235287-d8e2c907-9143-43cd-8398-2924e0a2e680.png)

### Genomes:
EPI_ISL_10711161, EPI_ISL_10737182, EPI_ISL_10737325, EPI_ISL_10885612, EPI_ISL_11084705, EPI_ISL_11123426, EPI_ISL_11123545, EPI_ISL_11126987, EPI_ISL_11312210, EPI_ISL_11416977, EPI_ISL_11429170, EPI_ISL_11430403, EPI_ISL_11430584, EPI_ISL_11661000, EPI_ISL_11693212, EPI_ISL_11729881, EPI_ISL_11730037, EPI_ISL_11730108, EPI_ISL_11731754, EPI_ISL_12018227, EPI_ISL_12078149, EPI_ISL_12187957, EPI_ISL_12334682, EPI_ISL_12348728, EPI_ISL_12361685, EPI_ISL_12449798, EPI_ISL_12517981, EPI_ISL_12519858, EPI_ISL_12529211

**Comment by corneliusroemer** [comment]
Thanks, interesting recombinant, with BA.1 sandwiched downstream of S.

What do you mean by S2M deletion? It's not something I've heard before. It's the long deletion in BA.2 150bp before the 3' end?

**Comment by c19850727** [comment]
A follow-up. 
This cluster is still growing, although very slowly. 
As of 2022-06-15, there are 41 sequences on GISAID.

**Comment by c19850727** [comment]
I'd close this issue due to its discontinued growth. 47 sequences as of 2022-07-19.
