### ISSUE TITLE
India/Bangladesh BA.2.10 lineage with S:I68T [78 seqs worldwide, ~10% in Bangladesh]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#609]
There are apparently many independent S:68T BA.2* lineages worldwide. One has so far been designated, a mostly Belgian one on the 22792T branch #565 

Trying to find clearly delineated S:68T lineages, I spotted one that was first sequenced in India and seems to make up a particularly large share of sequences in Bangladesh.

It's on the BA.2.10 branch, which makes it quite distinct.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AI68T%2CORF1b%3AS959P&nucMutations=22792C&pangoLineage=BA.2*&aaMutations1=S%3AI68T&nucMutations1=C7471T&

This is where it has been found:
<img width="1902" alt="image" src="https://user-images.githubusercontent.com/25161793/167307308-0528c994-1cd4-4284-9be5-2b79dcb216bd.png">

It's not limited to one region in Bangladesh, it was found in the capital Dhaka, at around ~5-10% a few weeks ago, but also in a different region, Rajshahi, where it appears more common.

<img width="1565" alt="image" src="https://user-images.githubusercontent.com/25161793/167307331-d6960122-ad1b-4945-aae1-8b45631a54cf.png">

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/25161793/167307422-c3cedff7-c8ce-46cc-ab91-f2c78c1556d7.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43386_7f8090.json?label=nuc%20mutations:T21765C

Example sequence: `Bangladesh/CHRF-GSB14-251/2022|EPI_ISL_11204803|2022-02-28`

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.10.3 with 21 newly designated sequences, and 34 updated designations from BA.2.10. Defining mutation(s) T16342C (ORF1ab:S5360P), then T21765C (S:I68T).
