### ISSUE TITLE
Proposal to merge B.1.1.338 B.1.1.336 into larger sublineage B.1.1/P681H

### ISSUE THREAD

**Issue by babarlelephant** [cov-lineages/pango-designation#61]
Hi, not sure if you will like this kind of request,

I would merge B.1.1.338 (52 sequences East Europe) and B.1.1.336 (33 sequences West Russia ) starting late 2020

with the unassigned sublineage of B.1.1 having C1648T C13554T C26464T and C23604A (P681H),
973 sequences starting in late 2020 East-North Europe. 

The frequency of the obtained 1000 sequences lineage is low, although in Poland it reached 15% in January (that's how I found it).
 On the Polish subsampled tree the lineage makes no doubt https://nextstrain.org/groups/neherlab/ncov/poland?c=gt-nuc_1648,13554,17082,23604,25910,26464 and it forms a lineage in the P681 subsampled tree https://nextstrain.org/groups/neherlab/ncov/S.P681?branchLabel=none&c=gt-nuc_1648,13554,17082,23604,25910,26464&d=tree,entropy,frequencies&m=div&p=full

The lineage is reasonably well supported, having >= 2 of the mutations C1648T C13554T C26464T T24733C A25910G A17082G puts you inside it:
![image](https://user-images.githubusercontent.com/6537565/115999492-49907180-a5ec-11eb-9cf3-e75df9c7aa5b.png)

`EPI_ISL_623670 EPI_ISL_625994 EPI_ISL_633324 EPI_ISL_629376 EPI_ISL_634375 EPI_ISL_647889 EPI_ISL_647365 EPI_ISL_657418 EPI_ISL_657770 EPI_ISL_652141 EPI_ISL_659507 EPI_ISL_659047 EPI_ISL_657443 EPI_ISL_671116 EPI_ISL_671057 EPI_ISL_668943 EPI_ISL_669435 EPI_ISL_669197 EPI_ISL_674195 EPI_ISL_682530 EPI_ISL_682532 EPI_ISL_682546 EPI_ISL_682723 EPI_ISL_682820 EPI_ISL_682769 EPI_ISL_675143 EPI_ISL_674445 EPI_ISL_678952 EPI_ISL_678915 EPI_ISL_708074 EPI_ISL_708078 EPI_ISL_701927 EPI_ISL_714097 EPI_ISL_713239 EPI_ISL_713240 EPI_ISL_713241 EPI_ISL_713968 EPI_ISL_714000 EPI_ISL_711580 EPI_ISL_712234 EPI_ISL_712858 EPI_ISL_712884 EPI_ISL_714537 EPI_ISL_714542 EPI_ISL_714592 EPI_ISL_724740 EPI_ISL_723285 EPI_ISL_723220 EPI_ISL_720611 EPI_ISL_732674 EPI_ISL_733355 EPI_ISL_733289 EPI_ISL_729414 EPI_ISL_732514 EPI_ISL_732896 EPI_ISL_727699 EPI_ISL_732884 EPI_ISL_733427 EPI_ISL_739843 EPI_ISL_745247 EPI_ISL_745234 EPI_ISL_745245 EPI_ISL_745241 EPI_ISL_748112 EPI_ISL_770869 EPI_ISL_770941 EPI_ISL_771007 EPI_ISL_771009 EPI_ISL_775323 EPI_ISL_790669 EPI_ISL_794487 EPI_ISL_795501 EPI_ISL_817647 EPI_ISL_818064 EPI_ISL_818262 EPI_ISL_818686 EPI_ISL_827690 EPI_ISL_829094 EPI_ISL_828677 EPI_ISL_827951 EPI_ISL_829391 EPI_ISL_836415 EPI_ISL_829545 EPI_ISL_829949 EPI_ISL_845037 EPI_ISL_845035 EPI_ISL_845110 EPI_ISL_845250 EPI_ISL_844686 EPI_ISL_844685 EPI_ISL_845233 EPI_ISL_839916 EPI_ISL_850670 EPI_ISL_855909 EPI_ISL_855905 EPI_ISL_856910 EPI_ISL_855624 EPI_ISL_860280 EPI_ISL_871922 EPI_ISL_864301 EPI_ISL_864268 EPI_ISL_864396 EPI_ISL_869547 EPI_ISL_870985 EPI_ISL_872972 EPI_ISL_869751 EPI_ISL_870177 EPI_ISL_869924 EPI_ISL_870553 EPI_ISL_869448 EPI_ISL_869440 EPI_ISL_870664 EPI_ISL_872987 EPI_ISL_873006 EPI_ISL_870238 EPI_ISL_870968 EPI_ISL_876009 EPI_ISL_871504 EPI_ISL_875980 EPI_ISL_876012 EPI_ISL_869360 EPI_ISL_875378 EPI_ISL_875489 EPI_ISL_872923 EPI_ISL_882962 EPI_ISL_882960 EPI_ISL_882712 EPI_ISL_897697 EPI_ISL_897802 EPI_ISL_898030 EPI_ISL_898031 EPI_ISL_893744 EPI_ISL_893746 EPI_ISL_893761 EPI_ISL_893766 EPI_ISL_893769 EPI_ISL_893773 EPI_ISL_893771 EPI_ISL_893752 EPI_ISL_893759 EPI_ISL_893748 EPI_ISL_893757 EPI_ISL_893750 EPI_ISL_904124 EPI_ISL_904123 EPI_ISL_904126 EPI_ISL_911133 EPI_ISL_905738 EPI_ISL_910712 EPI_ISL_906735 EPI_ISL_906801 EPI_ISL_905746 EPI_ISL_905747 EPI_ISL_905760 EPI_ISL_906723 EPI_ISL_906756 EPI_ISL_905737 EPI_ISL_913767 EPI_ISL_918340 EPI_ISL_918339 EPI_ISL_918343 EPI_ISL_918344 EPI_ISL_918345 EPI_ISL_918342 EPI_ISL_918341 EPI_ISL_918349 EPI_ISL_918350 EPI_ISL_918351 EPI_ISL_918354 EPI_ISL_918356 EPI_ISL_918355 EPI_ISL_918348 EPI_ISL_918357 EPI_ISL_918347 EPI_ISL_925038 EPI_ISL_925037 EPI_ISL_925035 EPI_ISL_925042 EPI_ISL_925044 EPI_ISL_925040 EPI_ISL_925045 EPI_ISL_918346 EPI_ISL_918352 EPI_ISL_918353 EPI_ISL_931185 EPI_ISL_928339 EPI_ISL_929239 EPI_ISL_928495 EPI_ISL_928929 EPI_ISL_930220 EPI_ISL_926809 EPI_ISL_926134 EPI_ISL_926347 EPI_ISL_930562 EPI_ISL_929900 EPI_ISL_927295 EPI_ISL_926503 EPI_ISL_926256 EPI_ISL_927876 EPI_ISL_930287 EPI_ISL_929495 EPI_ISL_953632 EPI_ISL_953635 EPI_ISL_953633 EPI_ISL_953634 EPI_ISL_953839 EPI_ISL_948200 EPI_ISL_959839 EPI_ISL_958694 EPI_ISL_960836 EPI_ISL_960837 EPI_ISL_960881 EPI_ISL_960882 EPI_ISL_959395 EPI_ISL_972073 EPI_ISL_972488 EPI_ISL_971241 EPI_ISL_981742 EPI_ISL_981739 EPI_ISL_972564 EPI_ISL_972876 EPI_ISL_971901 EPI_ISL_1001797 EPI_ISL_985045 EPI_ISL_986055 EPI_ISL_984284 EPI_ISL_984287 EPI_ISL_984285 EPI_ISL_988457 EPI_ISL_984634 EPI_ISL_1008222 EPI_ISL_1007960 EPI_ISL_1007954 EPI_ISL_1008732 EPI_ISL_1008760 EPI_ISL_1008734 EPI_ISL_1008725 EPI_ISL_1014211 EPI_ISL_1008756 EPI_ISL_1014190 EPI_ISL_1008730 EPI_ISL_1008720 EPI_ISL_1008729 EPI_ISL_1020159 EPI_ISL_1020139 EPI_ISL_1020156 EPI_ISL_1024062 EPI_ISL_1022927 EPI_ISL_1022982 EPI_ISL_1023341 EPI_ISL_1023715 EPI_ISL_1024375 EPI_ISL_1024255 EPI_ISL_1024139 EPI_ISL_1024153 EPI_ISL_1024177 EPI_ISL_1025011 EPI_ISL_1024031 EPI_ISL_1040156 EPI_ISL_1040166 EPI_ISL_1040941 EPI_ISL_1034801 EPI_ISL_1034913 EPI_ISL_1040988 EPI_ISL_1041010 EPI_ISL_1034332 EPI_ISL_1034334 EPI_ISL_1034803 EPI_ISL_1034912 EPI_ISL_1039059 EPI_ISL_1039143 EPI_ISL_1048425 EPI_ISL_1048407 EPI_ISL_1057020 EPI_ISL_1065369 EPI_ISL_1067532 EPI_ISL_1062936 EPI_ISL_1059810 EPI_ISL_1065863 EPI_ISL_1065163 EPI_ISL_1065440 EPI_ISL_1065178 EPI_ISL_1072993 EPI_ISL_1084647 EPI_ISL_1084667 EPI_ISL_1084641 EPI_ISL_1084644 EPI_ISL_1084672 EPI_ISL_1084650 EPI_ISL_1084651 EPI_ISL_1084645 EPI_ISL_1084666 EPI_ISL_1084656 EPI_ISL_1081912 EPI_ISL_1084637 EPI_ISL_1084638 EPI_ISL_1084639 EPI_ISL_1091456 EPI_ISL_1091145 EPI_ISL_1084649 EPI_ISL_1084661 EPI_ISL_1084668 EPI_ISL_1091465 EPI_ISL_1091437 EPI_ISL_1092265 EPI_ISL_1091480 EPI_ISL_1091477 EPI_ISL_1093391 EPI_ISL_1091483 EPI_ISL_1093021 EPI_ISL_1093050 EPI_ISL_1083885 EPI_ISL_1093195 EPI_ISL_1082862 EPI_ISL_1082730 EPI_ISL_1091473 EPI_ISL_1103573 EPI_ISL_1109392 EPI_ISL_1039245 EPI_ISL_1100819 EPI_ISL_1095153 EPI_ISL_1118641 EPI_ISL_1101757 EPI_ISL_1129807 EPI_ISL_1129813 EPI_ISL_1129963 EPI_ISL_1129812 EPI_ISL_1115656 EPI_ISL_1158887 EPI_ISL_1128824 EPI_ISL_1126752 EPI_ISL_1124725 EPI_ISL_1143173 EPI_ISL_1148433 EPI_ISL_1151599 EPI_ISL_1140570 EPI_ISL_1147505 EPI_ISL_1151951 EPI_ISL_1151984 EPI_ISL_1146651 EPI_ISL_1150600 EPI_ISL_1150545 EPI_ISL_1149116 EPI_ISL_1149147 EPI_ISL_1149124 EPI_ISL_1150538 EPI_ISL_1145821 EPI_ISL_1152006 EPI_ISL_1151676 EPI_ISL_1143400 EPI_ISL_1146676 EPI_ISL_1150554 EPI_ISL_1151797 EPI_ISL_1141080 EPI_ISL_1143602 EPI_ISL_1151462 EPI_ISL_1145876 EPI_ISL_1142385 EPI_ISL_1151203 EPI_ISL_1142026 EPI_ISL_1150129 EPI_ISL_1149464 EPI_ISL_1149356 EPI_ISL_1142891 EPI_ISL_1142022 EPI_ISL_1149433 EPI_ISL_1147502 EPI_ISL_1145839 EPI_ISL_1147468 EPI_ISL_1142205 EPI_ISL_1149103 EPI_ISL_1141975 EPI_ISL_1143230 EPI_ISL_1141489 EPI_ISL_1143294 EPI_ISL_1141598 EPI_ISL_1143110 EPI_ISL_1140742 EPI_ISL_1150036 EPI_ISL_1140603 EPI_ISL_1146803 EPI_ISL_1145166 EPI_ISL_1146631 EPI_ISL_1142086 EPI_ISL_1141949 EPI_ISL_1146618 EPI_ISL_1147583 EPI_ISL_1147576 EPI_ISL_1143411 EPI_ISL_1141277 EPI_ISL_1148304 EPI_ISL_1140827 EPI_ISL_1150355 EPI_ISL_1141352 EPI_ISL_1149342 EPI_ISL_1149078 EPI_ISL_1149114 EPI_ISL_1150496 EPI_ISL_1143427 EPI_ISL_1145060 EPI_ISL_1152717 EPI_ISL_1154467 EPI_ISL_1164532 EPI_ISL_1155030 EPI_ISL_1157257 EPI_ISL_1157447 EPI_ISL_1157237 EPI_ISL_1165729 EPI_ISL_1157516 EPI_ISL_1156893 EPI_ISL_1156214 EPI_ISL_1168076 EPI_ISL_1157231 EPI_ISL_1152592 EPI_ISL_1153993 EPI_ISL_1157213 EPI_ISL_1154206 EPI_ISL_1156917 EPI_ISL_1157717 EPI_ISL_1156294 EPI_ISL_1156307 EPI_ISL_1156312 EPI_ISL_1156287 EPI_ISL_1156324 EPI_ISL_1156446 EPI_ISL_1156865 EPI_ISL_1156226 EPI_ISL_1156222 EPI_ISL_1156259 EPI_ISL_1156309 EPI_ISL_1156215 EPI_ISL_1157209 EPI_ISL_1157255 EPI_ISL_1156842 EPI_ISL_1144910 EPI_ISL_1155424 EPI_ISL_1152558 EPI_ISL_1156737 EPI_ISL_1144184 EPI_ISL_1152564 EPI_ISL_1156692 EPI_ISL_1152538 EPI_ISL_1156492 EPI_ISL_1156701 EPI_ISL_1145069 EPI_ISL_1153271 EPI_ISL_1156622 EPI_ISL_1154510 EPI_ISL_1154875 EPI_ISL_1154487 EPI_ISL_1154737 EPI_ISL_1154664 EPI_ISL_1154629 EPI_ISL_1154478 EPI_ISL_1154452 EPI_ISL_1154760 EPI_ISL_1154545 EPI_ISL_1145047 EPI_ISL_1154649 EPI_ISL_1170730 EPI_ISL_1181169 EPI_ISL_1180843 EPI_ISL_1194060 EPI_ISL_1196727 EPI_ISL_1195346 EPI_ISL_1195303 EPI_ISL_1195357 EPI_ISL_1200411 EPI_ISL_1195340 EPI_ISL_1195336 EPI_ISL_1201716 EPI_ISL_1201677 EPI_ISL_1196722 EPI_ISL_1196739 EPI_ISL_1196746 EPI_ISL_1201608 EPI_ISL_1196730 EPI_ISL_1196719 EPI_ISL_1201642 EPI_ISL_1196745 EPI_ISL_1196732 EPI_ISL_1195359 EPI_ISL_1195361 EPI_ISL_1195363 EPI_ISL_1210688 EPI_ISL_1196749 EPI_ISL_1211746 EPI_ISL_1211484 EPI_ISL_1216480 EPI_ISL_1211829 EPI_ISL_1215571 EPI_ISL_1213599 EPI_ISL_1211659 EPI_ISL_1219341 EPI_ISL_1212597 EPI_ISL_1216291 EPI_ISL_1216382 EPI_ISL_1216200 EPI_ISL_1212595 EPI_ISL_1213067 EPI_ISL_1213001 EPI_ISL_1214323 EPI_ISL_1216368 EPI_ISL_1212787 EPI_ISL_1217695 EPI_ISL_1217696 EPI_ISL_1212988 EPI_ISL_1217635 EPI_ISL_1217633 EPI_ISL_1217660 EPI_ISL_1217977 EPI_ISL_1218091 EPI_ISL_1213666 EPI_ISL_1213716 EPI_ISL_1215564 EPI_ISL_1218076 EPI_ISL_1218041 EPI_ISL_1215200 EPI_ISL_1217982 EPI_ISL_1220166 EPI_ISL_1215191 EPI_ISL_1215079 EPI_ISL_1215187 EPI_ISL_1215750 EPI_ISL_1215757 EPI_ISL_1215774 EPI_ISL_1217252 EPI_ISL_1217257 EPI_ISL_1215773 EPI_ISL_1218180 EPI_ISL_1217379 EPI_ISL_1217968 EPI_ISL_1215643 EPI_ISL_1217637 EPI_ISL_1217647 EPI_ISL_1217296 EPI_ISL_1217289 EPI_ISL_1217304 EPI_ISL_1211953 EPI_ISL_1217842 EPI_ISL_1217595 EPI_ISL_1216712 EPI_ISL_1216446 EPI_ISL_1216695 EPI_ISL_1216194 EPI_ISL_1216665 EPI_ISL_1216720 EPI_ISL_1216434 EPI_ISL_1216430 EPI_ISL_1216772 EPI_ISL_1224488 EPI_ISL_1229532 EPI_ISL_1228260 EPI_ISL_1239717 EPI_ISL_1239747 EPI_ISL_1239743 EPI_ISL_1239733 EPI_ISL_1239755 EPI_ISL_1248340 EPI_ISL_1252801 EPI_ISL_1248306 EPI_ISL_1265427 EPI_ISL_1265410 EPI_ISL_1265411 EPI_ISL_1265414 EPI_ISL_1265416 EPI_ISL_1265745 EPI_ISL_1265746 EPI_ISL_1265741 EPI_ISL_1265748 EPI_ISL_1265750 EPI_ISL_1265440 EPI_ISL_1265401 EPI_ISL_1279884 EPI_ISL_1273838 EPI_ISL_1273771 EPI_ISL_1273820 EPI_ISL_1279886 EPI_ISL_1279890 EPI_ISL_1285790 EPI_ISL_1282842 EPI_ISL_1281556 EPI_ISL_1281339 EPI_ISL_1284829 EPI_ISL_1281543 EPI_ISL_1282229 EPI_ISL_1281388 EPI_ISL_1285041 EPI_ISL_1284983 EPI_ISL_1285139 EPI_ISL_1284860 EPI_ISL_1284653 EPI_ISL_1284591 EPI_ISL_1287040 EPI_ISL_1282204 EPI_ISL_1282261 EPI_ISL_1285656 EPI_ISL_1285107 EPI_ISL_1285164 EPI_ISL_1284559 EPI_ISL_1285077 EPI_ISL_1285071 EPI_ISL_1285091 EPI_ISL_1285069 EPI_ISL_1289349 EPI_ISL_1282916 EPI_ISL_1282954 EPI_ISL_1284776 EPI_ISL_1284671 EPI_ISL_1295175 EPI_ISL_1300728 EPI_ISL_1295593 EPI_ISL_1305813 EPI_ISL_1302462 EPI_ISL_1302463 EPI_ISL_1302567 EPI_ISL_1250891 EPI_ISL_1298449 EPI_ISL_1313372 EPI_ISL_1313415 EPI_ISL_1313371 EPI_ISL_1313435 EPI_ISL_1315632 EPI_ISL_1315607 EPI_ISL_1316461 EPI_ISL_1312755 EPI_ISL_1308685 EPI_ISL_1308686 EPI_ISL_1308679 EPI_ISL_1308697 EPI_ISL_1308692 EPI_ISL_1308696 EPI_ISL_1322732 EPI_ISL_1322729 EPI_ISL_1322730 EPI_ISL_1319720 EPI_ISL_1322104 EPI_ISL_1341054 EPI_ISL_1341055 EPI_ISL_1341056 EPI_ISL_1341057 EPI_ISL_1341058 EPI_ISL_1338629 EPI_ISL_1341061 EPI_ISL_1341502 EPI_ISL_1341060 EPI_ISL_1341091 EPI_ISL_1341090 EPI_ISL_1341059 EPI_ISL_1347090 EPI_ISL_1354048 EPI_ISL_1357670 EPI_ISL_1354391 EPI_ISL_1348649 EPI_ISL_1354535 EPI_ISL_1357646 EPI_ISL_1357660 EPI_ISL_1357650 EPI_ISL_1348530 EPI_ISL_1357610 EPI_ISL_1357614 EPI_ISL_1357636 EPI_ISL_1354407 EPI_ISL_1348357 EPI_ISL_1353030 EPI_ISL_1354213 EPI_ISL_1354239 EPI_ISL_1354022 EPI_ISL_1354051 EPI_ISL_1354038 EPI_ISL_1354126 EPI_ISL_1354378 EPI_ISL_1353050 EPI_ISL_1366982 EPI_ISL_1350553 EPI_ISL_1351479 EPI_ISL_1360031 EPI_ISL_1360040 EPI_ISL_1360036 EPI_ISL_1360037 EPI_ISL_1360039 EPI_ISL_1352210 EPI_ISL_1361757 EPI_ISL_1349289 EPI_ISL_1352327 EPI_ISL_1364935 EPI_ISL_1351797 EPI_ISL_1351804 EPI_ISL_1362221 EPI_ISL_1349733 EPI_ISL_1352344 EPI_ISL_1352330 EPI_ISL_1349803 EPI_ISL_1378896 EPI_ISL_1378865 EPI_ISL_1378868 EPI_ISL_1378850 EPI_ISL_1378851 EPI_ISL_1372286 EPI_ISL_1372389 EPI_ISL_1389065 EPI_ISL_1389070 EPI_ISL_1389089 EPI_ISL_1389091 EPI_ISL_1389099 EPI_ISL_1383829 EPI_ISL_1380951 EPI_ISL_1380653 EPI_ISL_1382568 EPI_ISL_1381080 EPI_ISL_1382192 EPI_ISL_1382247 EPI_ISL_1381280 EPI_ISL_1382473 EPI_ISL_1382567 EPI_ISL_1386577 EPI_ISL_1391344 EPI_ISL_1391362 EPI_ISL_1394257 EPI_ISL_1393747 EPI_ISL_1393818 EPI_ISL_1393705 EPI_ISL_1393962 EPI_ISL_1394020 EPI_ISL_1394024 EPI_ISL_1394022 EPI_ISL_1394003 EPI_ISL_1393997 EPI_ISL_1393994 EPI_ISL_1394002 EPI_ISL_1393894 EPI_ISL_1393895 EPI_ISL_1393906 EPI_ISL_1393975 EPI_ISL_1393691 EPI_ISL_1394170 EPI_ISL_1394172 EPI_ISL_1393992 EPI_ISL_1393735 EPI_ISL_1393675 EPI_ISL_1402506 EPI_ISL_1394008 EPI_ISL_1393742 EPI_ISL_1394035 EPI_ISL_1394033 EPI_ISL_1394260 EPI_ISL_1396626 EPI_ISL_1394329 EPI_ISL_1394182 EPI_ISL_1394197 EPI_ISL_1402500 EPI_ISL_1394299 EPI_ISL_1394324 EPI_ISL_1402532 EPI_ISL_1394078 EPI_ISL_1394194 EPI_ISL_1394094 EPI_ISL_1394113 EPI_ISL_1394139 EPI_ISL_1404380 EPI_ISL_1404381 EPI_ISL_1404382 EPI_ISL_1404391 EPI_ISL_1404388 EPI_ISL_1404390 EPI_ISL_1394319 EPI_ISL_1394038 EPI_ISL_1411633 EPI_ISL_1406325 EPI_ISL_1416806 EPI_ISL_1410782 EPI_ISL_1406339 EPI_ISL_1425716 EPI_ISL_1425547 EPI_ISL_1423729 EPI_ISL_1423730 EPI_ISL_1437126 EPI_ISL_1434214 EPI_ISL_1439595 EPI_ISL_1433025 EPI_ISL_1439013 EPI_ISL_1441298 EPI_ISL_1441287 EPI_ISL_1441270 EPI_ISL_1441272 EPI_ISL_1439574 EPI_ISL_1436787 EPI_ISL_1438825 EPI_ISL_1438720 EPI_ISL_1436029 EPI_ISL_1438798 EPI_ISL_1441218 EPI_ISL_1438859 EPI_ISL_1433081 EPI_ISL_1438689 EPI_ISL_1441066 EPI_ISL_1438976 EPI_ISL_1433194 EPI_ISL_1433080 EPI_ISL_1433122 EPI_ISL_1433292 EPI_ISL_1439101 EPI_ISL_1439032 EPI_ISL_1437365 EPI_ISL_1447279 EPI_ISL_1443727 EPI_ISL_1443436 EPI_ISL_1447269 EPI_ISL_1447284 EPI_ISL_1465497 EPI_ISL_1457741 EPI_ISL_1457755 EPI_ISL_1463712 EPI_ISL_1463862 EPI_ISL_1463864 EPI_ISL_1463715 EPI_ISL_1463778 EPI_ISL_1463829 EPI_ISL_1463833 EPI_ISL_1463842 EPI_ISL_1463913 EPI_ISL_1463755 EPI_ISL_1463869 EPI_ISL_1464136 EPI_ISL_1464148 EPI_ISL_1464173 EPI_ISL_1463832 EPI_ISL_1463637 EPI_ISL_1463758 EPI_ISL_1463769 EPI_ISL_1474572 EPI_ISL_1491676 EPI_ISL_1500112 EPI_ISL_1499284 EPI_ISL_1499285 EPI_ISL_1499194 EPI_ISL_1499346 EPI_ISL_1498377 EPI_ISL_1500137 EPI_ISL_1500127 EPI_ISL_1499126 EPI_ISL_1500134 EPI_ISL_1499312 EPI_ISL_1499123 EPI_ISL_1493318 EPI_ISL_1500147 EPI_ISL_1500140 EPI_ISL_1491714 EPI_ISL_1491597 EPI_ISL_1502586 EPI_ISL_1502659 EPI_ISL_1502687 EPI_ISL_1502669 EPI_ISL_1502689 EPI_ISL_1522171 EPI_ISL_1522173 EPI_ISL_1524763 EPI_ISL_1538500 EPI_ISL_1539174 EPI_ISL_1539188 EPI_ISL_1539195 EPI_ISL_1539176 EPI_ISL_1538454 EPI_ISL_1539190 EPI_ISL_1539182 EPI_ISL_1539156 EPI_ISL_1538452 EPI_ISL_1539184 EPI_ISL_1539180 EPI_ISL_1539189 EPI_ISL_1539220 EPI_ISL_1539187 EPI_ISL_1539219 EPI_ISL_1539194 EPI_ISL_1539157 EPI_ISL_1539186 EPI_ISL_1523554 EPI_ISL_1539161 EPI_ISL_1539227 EPI_ISL_1539228 EPI_ISL_1539170 EPI_ISL_1539185 EPI_ISL_1538462 EPI_ISL_1538511 EPI_ISL_1539207 EPI_ISL_1538497 EPI_ISL_1539210 EPI_ISL_1539168 EPI_ISL_1539233 EPI_ISL_1539234 EPI_ISL_1534049 EPI_ISL_1539191 EPI_ISL_1539169 EPI_ISL_1538489 EPI_ISL_1539218 EPI_ISL_1539222 EPI_ISL_1539193 EPI_ISL_1539225 EPI_ISL_1539221 EPI_ISL_1524767 EPI_ISL_1539212 EPI_ISL_1539203 EPI_ISL_1539209 EPI_ISL_1539215 EPI_ISL_1539208 EPI_ISL_1539224 EPI_ISL_1539202 EPI_ISL_1539223 EPI_ISL_1539196 EPI_ISL_1539183 EPI_ISL_1540608 EPI_ISL_1540706 EPI_ISL_1570205 EPI_ISL_1570203 EPI_ISL_1571338 EPI_ISL_1571345 EPI_ISL_1571371 EPI_ISL_1571350 EPI_ISL_1569981 EPI_ISL_1569501 EPI_ISL_1569508 EPI_ISL_1566021 EPI_ISL_1569585 EPI_ISL_1569329 EPI_ISL_1569102 EPI_ISL_1569314 EPI_ISL_1566045 EPI_ISL_1567753 EPI_ISL_1571262 EPI_ISL_1580115 EPI_ISL_1579176 EPI_ISL_1579178 EPI_ISL_1579177 EPI_ISL_1590569 EPI_ISL_1588635 EPI_ISL_1588636 EPI_ISL_1588637 EPI_ISL_1588638 EPI_ISL_1588669 EPI_ISL_1599541 EPI_ISL_1604747 EPI_ISL_1604698 EPI_ISL_1604673 EPI_ISL_1604758 EPI_ISL_1617508 EPI_ISL_1622517 EPI_ISL_1622518 EPI_ISL_1622921 EPI_ISL_1618623 EPI_ISL_1627999 EPI_ISL_1627996 EPI_ISL_1627997 EPI_ISL_1628002 EPI_ISL_1628000 EPI_ISL_1628001 EPI_ISL_1644407 EPI_ISL_1643216 EPI_ISL_1643298 EPI_ISL_1640233 EPI_ISL_1640086 EPI_ISL_1642773 EPI_ISL_1638810 EPI_ISL_1639220 EPI_ISL_1643073 EPI_ISL_1659543 EPI_ISL_1659539 EPI_ISL_1658318 EPI_ISL_1664633 EPI_ISL_1664693 EPI_ISL_1664710 EPI_ISL_1664655 EPI_ISL_1664308 EPI_ISL_1664300 EPI_ISL_1664305 EPI_ISL_1664301 EPI_ISL_1671570 EPI_ISL_1664783 EPI_ISL_1664746 EPI_ISL_1664759 EPI_ISL_1677833`

**Comment by chrisruis** [comment]
Thanks very much for submitting this @babarlelephant - we definitely like requests like this! There will potentially be situations where lineage designations need to be changed as more sequence data comes in

I've had a look at this part of the tree, shown here on the left coloured by _assigned_ lineage and on the right coloured by country of collection:
![B 1 1](https://user-images.githubusercontent.com/47785131/116711822-20485a80-a9cb-11eb-9d95-028f1e292b6f.png)

This is all of the sequences included above with a reference set of B.1.1 and B.1 sequences and rooted on a reference B sequence. The clade containing the sequences included above is shown with the star.

To be designated a lineage, a clade needs to exhibit one or more events of epidemiological significance to distinguish the new lineage from continued circulation of the parental lineage, for example introduction into a new geographical area with onward transmission. B.1.1 is widespread around Europe and the starred clade in this tree is also widespread in Europe, with lots of virus movements between countries. It therefore doesn't look like there's an epidemiological reason to distinguish this clade from the rest of B.1.1 and therefore under the Pango rules, this clade should be designated as B.1.1.

B.1.1.336 and B.1.1.338 do satisfy the definitions for new lineages as they are associated with a clear introduction into a country with onward transmission. So under the Pango rules, the current designations appear to be correct for these lineages.

So currently, I'd say that the designations are correct within this part of the tree and we shouldn't merge these clades.

Thanks very much again for submitting
