### ISSUE TITLE
Australian BA.2 lineage with S:68T and N:E378D [100 seqs, 3% in Australia]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#610]
Very well delineated Australian BA.2 + S:68T lineage due to mutations: `T8164C, C1348T, N:E378D`

It appears to have steady growth and has been observed a few times around the world.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/25161793/167307593-fd819709-89f2-4879-97ed-f491d752da7c.png">

Growth with respect to BA.2* in New South Wales (where it's most common):
<img width="846" alt="image" src="https://user-images.githubusercontent.com/25161793/167307663-f761a15f-edc8-4bcd-8207-f5d991b70842.png">

https://cov-spectrum.org/explore/Australia/AllSamples/Past3M/variants/international-comparison?aaMutations=S%3AI68T&nucMutations=22792C%2CT8164C%2CC1348T%2CA29407T&pangoLineage=BA.2*&aaMutations1=S%3AI68T&nucMutations1=22792C%2CT8164C%2CC1348T%2CA29407T&pangoLineage1=BA.2*&

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_46d7_7fafb0.json?label=nuc%20mutations:A29407T

`Australia/ACT5195/2022|EPI_ISL_12434488|2022-04-17`

It's possible this lineage arose from a base BA.2 + S:68T, or independently - hard to tell

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.42 with 72 newly designated sequences, and 3 updated designations from BA.2. Defining mutation(s) A29407T (N:E378D).
