### ISSUE TITLE
Indian BA.2 with S:S371Y and S:1202Q, ORF1a:768R (instead of BA.2 S:S371F) [50 seq, ~5-10% in India]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#612]
Noticed this lineage as it was growing in Belgium and had an interesting mutation: BA.2 S:S371F has mutated further to S:371F (C22674 from T->A).

It seems most common in India, where it's been detected in a lot of states. Elsewhere, it's most common in Belgium at around 1%. But it's been detected in a lot of places.

Detections in India:
```
Location	Number of sequences	Prevalence
Delhi	        9	2.84%
Gujarat	        1	0.111%
Haryana	        6	5.608%
Punjab IN	1	100%
Rajasthan	1	0.035%
Tamil Nadu     23	1.638%
Telangana	1	0.109%
Uttar Pradesh	7	3.554%
```

```
India/TN-CDFD-W7-91/2022 | EPI_ISL_12354734 | 2022-04-20	
India/RJ-SMS-ICMR-INSACOG-TS-13631/2022 | EPI_ISL_12363060 | 2022-03-31
```

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_32723_8220b0.json?label=nuc%20mutations:C18086T

<img width="1838" alt="image" src="https://user-images.githubusercontent.com/25161793/167314153-46c8c81a-d848-4b74-b843-a10e540a0d3b.png">

https://cov-spectrum.org/explore/India/AllSamples/Past3M/variants/international-comparison?aaMutations=S%3AS371Y%2CORF1a%3A768R%2CS%3A1202Q&pangoLineage=BA.2*&pangoLineage1=BA.2*&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.43 with 25 newly designated sequences, and 0 updated designations. Defining mutation(s) A2568G (ORF1a:Q768R), T22674A (S:F371Y), G25166C (S:E1202Q).
