### ISSUE TITLE
Belgian BA.2 (+22792T + A23767G + C19011T) with S:371Y [140 seq, 1% in Belgium]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#613]
Same mutation as in #612 (S:371Y) but homoplasy as here it's on totally different background (very Belgian branch of BA.2 + 22792T.

First sequenced in February 2022, has grown steadily compared to rest of this branch.

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/25161793/167314542-e9719671-6fff-4699-8d7b-93bc981838b0.png">

https://cov-spectrum.org/explore/Europe/AllSamples/Past6M/variants?nucMutations=22792T%2C23767G&pangoLineage=BA.2*&aaMutations1=S%3A371Y&nucMutations1=22792T%2CA23767G%2CC19011T&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&

<img width="1909" alt="image" src="https://user-images.githubusercontent.com/25161793/167314598-d43f64bb-dba2-4d69-86d8-391b06276e63.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_32723_8220a0.json

```
England/LSPA-3B02BDC/2022|OW286017.1|2022-03-16
```

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.44 with 139 newly designated sequences, and 10 updated designations from BA.2. Defining mutation(s) T22674A (S:F371Y).
