### ISSUE TITLE
Austrian BA.4+S:V3G lineage with ORF1a:P971S (61 sequences, >80% of BA.4 in Austria)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#614]
Proposal for a sublineage of BA.4
Earliest sequence: 2022-04-19 (Austria)
Countries detected: Austria (61 seq, all from Vienna)

Defining mutations: 
S:V3G, then ORF7a:P84L + nuc:C29686T, then ORF1a:P971S
Most sequences have a further ORF1b:P314F (as opposed to ORF1b:P314L in B.1 and all its descendants)

<img width="734" alt="Austria_BA4" src="https://user-images.githubusercontent.com/42699509/167313982-9d5784c4-8dd1-457c-a507-c13ecd0d67eb.png">

[https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29162_81b940.json?c=gt-nuc_3176,27644&label=nuc%20mutations:C27644T,C29686T](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29162_81b940.json?c=gt-nuc_3176,27644&label=nuc%20mutations:C27644T,C29686T)

Austria is one of the countries outside Africa with the highest proportion of BA.4 - possibly 5-10%, though the proportion may be exaggerated because BA.4 has only been detected in Vienna and the most recent sequencing has mainly been from there. Over 80% of BA.4 in Austria belongs to this lineage. It is a sublineage of the big branch of BA.4 with S:V3G proposed by @corneliusroemer in #548. ORF1a:P971S = 3176T (orange in the Usher tree above) appears to coincide with the introduction into Austria: there are two South African sequences (blue in the tree) with ORF7a:P84L + nuc:C29686T but not ORF1a:P971S.

The numbers are too small to tell if there's a transmission advantage over the rest of BA.4, but I think the geographic link combined with BA.4's growth advantage in Austria is enough to warrant a designation. This should wait until a decision is made on whether to designate the S:V3G branch.

Cov-spectrum query: [https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=12160A+%26+9866C+%26+27644T+%26+21570G+%26+3176T&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=12160A+%26+9866C+%26+27644T+%26+21570G+%26+3176T&)

EPI_ISLs: [austria_ba4.txt](https://github.com/cov-lineages/pango-designation/files/8647811/austria_ba4.txt)

**Comment by chrisruis** [comment]
Thanks @silcn We spotted this one the other day as well and added it as BA.4.1.2
