### ISSUE TITLE
Potential new BA.5.X lineage in Asturias (mainly)

### ISSUE THREAD

**Issue by VirologiaHUCA** [cov-lineages/pango-designation#618]
Description
Sub-lineage of: BA.5
Earliest sequence: 2022-04-15
Most recent sequence: 2022-04-29
Countries circulating: Spain, Denmark, England, Scontland, Canada
<written description of the proposed lineage, where it is circulating, when, why it is distinct>
In BA.5 variants, this clade gained the nsp16_V288F mutation. Subsequently, the clade gained a new mutation, nsp6_V289L.
Genomes
<list of genome names as found on GISAID or accession ids - provide as a CSV/TSV table attachment - include locations and dates of sampling>

EPI_ISL_12406393
EPI_ISL_12207803
EPI_ISL_12291987
EPI_ISL_12472550
EPI_ISL_12473106
EPI_ISL_12151839
EPI_ISL_12434927
EPI_ISL_12477595
EPI_ISL_12283695
EPI_ISL_12490468
EPI_ISL_12589393
EPI_ISL_12589394
EPI_ISL_12589398
EPI_ISL_12589400
EPI_ISL_12589402
EPI_ISL_12589404
EPI_ISL_12589405
EPI_ISL_12589406

Evidence
<image from phylogenetic tree?>
![image]( https://user-images.githubusercontent.com/105294581/167646016-10542d86-25d1-4aa1-a254-719d166993d0.png )

**Comment by FedeGueli** [comment]
@corneliusroemer i gave a look at this one:

I think, when the time for BA.5 sublineages will come , this could be interesting to be designated starting with Orf1b:2685F, considering the tree starting  from that mutation i found 51 seqs on covspectrum mainly from Spain, Uk, Denmark.
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3A486V%2COrf1b%3A2685F&aaMutations1=S%3A486V%2COrf1b%3A2685F&
But the Usher tree points to 59 seqs:
![Schermata 2022-05-11 alle 23 10 43](https://user-images.githubusercontent.com/87669813/167948876-59de50e2-1ef9-4e46-9071-a6010c2effd9.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_23d50_c128a0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A28330G

The branch leading to this sublineage has 5 nuc mutations acquired likely during sustained circulation in SA or elsewhere: A28330G then C1627T then A27038G then T6979G then C22879T 
then it acquired Orf1b:2685F and then Orf1a:V3858L this last one represents the beginning of local circulation in Spain (even if there is also a spanish sample with Orf1b:2685F alone)

**Comment by silcn** [comment]
This is a sublineage of the big branch proposed by @corneliusroemer in #551 which is currently labelled as "monitor". I'm not sure there's a strong case for designating #551 but any decision about this lineage should be made together with a decision about that one.

**Comment by FedeGueli** [comment]
Thx @silcn for highlighting that there are three BA.5 big branch, the one you proposed from portugal with orf10:37F, the other (double?) you mentioned there with orf1a:556K and the last one you mentioned here with nuc mut at 28330 that shows a bigger diversity than the other two. So probably designating it could catch in a better way future sublineages like this 'spanish' one that seems circulating in a sustained way.
And that was the idea of @corneliusroemer to identify early big branches to have a clear picture from the start.

**Comment by FedeGueli** [comment]
@corneliusroemer yes it is

**Comment by VirologiaHUCA** [comment]
Yes, this is the new linage proposed,

**Comment by FedeGueli** [comment]
95 seqs as today

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.4 with 64 newly designated sequences, and 31 updated designations from BA.5.2. Defining mutation(s) G11837T (ORF1a:V3858L), G21520T.

**Comment by VirologiaHUCA** [comment]
Thank you again. 
Best regards 

Santiago Melón García 
Sección de Virología 
Hospital Universitario Central de Asturias (HUCA) 
Av. Roma s/n 
33011 Oviedo 
Tlf. 985108720 (Ext 38506) 


De: "InfrPopGen" ***@***.***> 
Para: "cov-lineages/pango-designation" ***@***.***> 
CC: "VirologiaHUCA" ***@***.***>, "Author" ***@***.***> 
Enviados: Lunes, 30 de Mayo 2022 20:38:56 
Asunto: Re: [cov-lineages/pango-designation] Potential new BA.5.X lineage in Asturias (mainly) (Issue #618) 



ATENCIÓN: Este correo electrónico proviene de fuera de la organización. Sea muy cauto, e incluso ignore, los enlaces y archivos adjuntos que aparecen en el mismo, especialmente si desconoce al remitente u observa algún indicio de posibles contenidos maliciosos. Es esencial recordar que NUNCA DEBE INTRODUCIR SUS CONTRASEÑAS COMO RESPUESTA A UN CORREO. 




Thanks for submitting. We've added lineage BA.5.4 with 64 newly designated sequences, and 31 updated designations from BA.5.2. Defining mutation(s) G11837T (ORF1a:V3858L), G21520T.

**Comment by silcn** [comment]
@InfrPopGen, shouldn't this be a sublineage of BA.5.2 rather than getting its own BA.5.* designation?

**Comment by FedeGueli** [comment]
Agree with @silcn it is a sublineage of BA.5.2  and the parental of this starting from C1627T was proposed in #657. As @agamedilab noted in that issue, there is another branch starting with C1627T and if it keeps circulating,  as it is likely given the BA.5 Advantage,it would be hard then to resolve the designations properly.

**Comment by agamedilab** [comment]
@VirologiaHUCA Hi, have you checked for A28330G? 

ORF9b:D16G = A28330G but apparently Nextfclade bugs out when displaying ORF9b:D16G but A28330G should work (see also #657)

All the best!

**Comment by InfrPopGen** [comment]
Thank you all for pointing out the BA.5.2 root of this lineage. Apologies for the delay in getting back to this (UK is having national holidays). I will check the 551 -> 657 ancestry and then re-designate.

**Comment by InfrPopGen** [comment]
Re-designated as lineage BF.1 with 1 newly designated sequence, and 94 updated designations from  BA.5.2.1. Defining mutation(s) G11837T (ORF1a:V3858L) (nsp6:V289L).

**Comment by FedeGueli** [comment]
@InfrPopGen @silcn I would like to alert you that @rajLABN spotted a new sublineage[(link)](https://twitter.com/RajlabN/status/1532951760695861248?s=20&t=0Jno4FMs_KMP4lLPp5R2RA ![chrome_screenshot_1654344332070])  branching out from Orf1b:2685F and it is quite large around 200 sequences

(https://user-images.githubusercontent.com/87669813/171998203-79228720-2178-4811-9c5a-c5def9b2a8f1.png)


https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_185ec_ae29f0.json?branchLabel=aa%20mutations&c=gt-nuc_28330&label=nuc%20mutations:T4690C


This would mess up if BF.1 designation will be confirmed.

Probably it is better broadening BF.1 to Orf1b:2685F and designated sublineages from there

cc
@AngieHinrichs @corneliusroemer @chrisruis (🔴Important/Urgent)

**Comment by AngieHinrichs** [comment]
> broadening BF.1 to Orf1b:2685F and designated sublineages from there

That seems fine to me, both G21520T > G11837T and G21520T > G26122A have a good number of sequences from Spain.

**Comment by InfrPopGen** [comment]
BF.1 has now been broadened by moving root one node pastwards (nt:G21520T (ORF1ab:V7086F)); this causes 95 designations updated from BF.1 and 59 designations updated from BA.5.2.1.
