### ISSUE TITLE
Proposed lineage within B.1 with N501Y, E484K, P681H first detected in Colombia.

### ISSUE THREAD

**Issue by erikalmecdc** [cov-lineages/pango-designation#62]
New lineage proposal
by Erik Alm

A divergent lineage with N501Y and E484K.
Spike D614G, Spike D950N, Spike E484K, Spike ins145N, Spike N501Y, Spike P681H, Spike R346K, Spike T95I, Spike Y144T, Spike Y145S

Similar mutation profile to VOCs, but completely distinct.

Sub-lineage of: B.1
Earliest sequence: 2021-01-11
Most recent sequence: 2021-04-16
Countries circulating: Colombia, Spain, USA

Genomes
Accession ID	Collection date	Submission date	Location
EPI_ISL_1220045	2021-01-11	2021-03-11	South America / Colombia / Magdalena
EPI_ISL_1385573	2021-03-23	2021-03-29	North America / USA / New York / New York City
EPI_ISL_1401468	2021-03-13	2021-03-30	Europe / Spain / Madrid
EPI_ISL_1401469	2021-03-22	2021-03-30	Europe / Spain / Madrid
EPI_ISL_1542954	2021-03-31	2021-04-12	North America / USA / New York / New York City
EPI_ISL_1543466	2021-04-07	2021-04-12	North America / USA / New York / New York City
EPI_ISL_1543900	2021-04-07	2021-04-12	North America / USA / New York / New York City
EPI_ISL_1581369	2021-03-28	2021-04-13	North America / USA / California
EPI_ISL_1582005	2021-03-29	2021-04-13	North America / USA / Arizona
EPI_ISL_1582978	2021-02-26	2021-04-14	South America / Colombia / La Guajira / Riohacha
EPI_ISL_1582979	2021-03-02	2021-04-14	South America / Colombia / La Guajira / Maicao
EPI_ISL_1582980	2021-02-21	2021-04-14	South America / Colombia / La Guajira / Riohacha
EPI_ISL_1582981	2021-03-10	2021-04-14	South America / Colombia / Norte de Santander / Ocana
EPI_ISL_1582987	2021-03-24	2021-04-14	South America / Colombia / Vichada / Puerto Carreno
EPI_ISL_1582988	2021-03-15	2021-04-14	South America / Colombia / Magdalena / Santa Marta
EPI_ISL_1582989	2021-03-17	2021-04-14	South America / Colombia / Magdalena / Santa Marta
EPI_ISL_1582990	2021-03-08	2021-04-14	South America / Colombia / Magdalena / Santa Marta
EPI_ISL_1582991	2021-03-06	2021-04-14	South America / Colombia / Magdalena
EPI_ISL_1582992	2021-03-08	2021-04-14	South America / Colombia / Magdalena / Cienaga
EPI_ISL_1582994	2021-03-10	2021-04-14	South America / Colombia / Magdalena / Cienaga
EPI_ISL_1582996	2021-03-15	2021-04-14	South America / Colombia / Atlantico / Barranquilla
EPI_ISL_1582997	2021-03-24	2021-04-14	South America / Colombia / Vichada / Puerto Carreno
EPI_ISL_1647948	2021-04-08	2021-04-19	Europe / Spain / Madrid
EPI_ISL_1647949	2021-04-10	2021-04-19	Europe / Spain / Madrid
EPI_ISL_1647956	2021-04-09	2021-04-19	Europe / Spain / Madrid
EPI_ISL_1663013	2021-04-12	2021-04-21	North America / USA / Maryland
EPI_ISL_1678824	2021-03-26	2021-04-22	South America / Curacao / Willemstad
EPI_ISL_1680834	2021-04-03	2021-04-22	North America / USA / Alabama
EPI_ISL_1683896	2021-03-06	2021-04-22	Europe / Spain / Murcia
EPI_ISL_1717351	2021-04-16	2021-04-26	North America / USA / New York / New York City

![new lineage](https://user-images.githubusercontent.com/36880285/116101378-0eef0d80-a6ae-11eb-9276-83b587ea47a0.PNG)

**Comment by ha-ruiz75** [comment]
Hi. This lineage has already been assigned as B.1.621 [(closed issue - pango-designation/issues/57)](https://github.com/cov-lineages/pango-designation/issues/57)

**Comment by erikalmecdc** [comment]
Thanks, I missed that.
