### ISSUE TITLE
BA.5 sublineage circulating in Portugal (170 seq, ~10% in Portugal)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#621]
Proposal for a sublineage of BA.5
Earliest sequence: 2022-03-08 (South Africa)
Countries detected: mainly Portugal (136 seq), with spread to various other European countries

Defining mutations:
C29666T = ORF10:L37F, T27438C
I'm assuming here that ORF10 is counted as a coding protein and thus this lineage can be designated. Please correct me if I'm mistaken and this is why the lineage hasn't already been proposed!

This is one of two lineages that make up the bulk of sequenced BA.5 outside South Africa, the other being the one proposed by @corneliusroemer in #550. This one is particularly notable as it makes up about 10% of recent sequences (and 100% of BA.5) from Portugal. It's clearly visible in blue in the tree of all BA.5 below.

<img width="736" alt="Portugal_BA5" src="https://user-images.githubusercontent.com/42699509/167748936-144300d1-8bcd-4468-9766-087df8fcecaa.png">

[https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24538_b0bcd0.json?c=gt-nuc_29666,27438&label=nuc%20mutations:C29666T](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24538_b0bcd0.json?c=gt-nuc_29666,27438&label=nuc%20mutations:C29666T)

Cov-spectrum: [https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=12160A+%26+9866C+%26+27259A+%26+29666T+%26+27438C&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=12160A+%26+9866C+%26+27259A+%26+29666T+%26+27438C&)

**Comment by FedeGueli** [comment]
Great catch @silcn i suggest to follow the evolution of this one on the fantastic INSAFLU weekly update report page: 
https://insaflu.insa.pt/covid19/

**Comment by corneliusroemer** [comment]
Good catch, I agree. This one stands out very well as a Portugese introduction. Let's hope ORF10 counts ;)

**Comment by FedeGueli** [comment]
I saw a BA.5.1 designated from Portugal  is this one?

**Comment by silcn** [comment]
> I saw a BA.5.1 designated from Portugal is this one?

Yeah, it is, well spotted. It was actually added less than a day after I started this issue so was likely already going to be designated. I'll close and let someone with the necessary powers add the tags.

**Comment by FedeGueli** [comment]
Thx @silcn .I have checked the growth advantage of BA.5.1 since you proposed and it seems higher than other BA.4/BA.5 in other countries. lets see if it changes with time and settles down a bit.

**Comment by FedeGueli** [comment]
hi @AngieHinrichs i spotted a part of the Usher tree that probably wrongly  shows multiple independent acquisition of 29666T after 27438C:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_13f83_ffc4f0.json?branchLabel=nuc%20mutations&c=gt-nuc_29666&label=nuc%20mutations:T27438C

![Screenshot_2022-06-20-07-25-12-588_com android chrome](https://user-images.githubusercontent.com/87669813/174531065-70b9f34c-338d-496f-8503-60449e9f40f4.jpg)

**Comment by AngieHinrichs** [comment]
Thank you @FedeGueli for spotting that!  I will try to fix it.  With so many different combinations of mutations appearing in sequences (e.g some sequences with T27438C and G16700T but not C29666T, as well as some sequences with all three), from a parsimony point of view that structure is optimal, but we would prefer to have sequences that have both T27438C and C29666T grouped together.

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs i spotted those ones without 29666T i was trying to.understand if real if a sublineage on their own but it didnt seem so
