### ISSUE TITLE
BA.5 (+ORF1a:556K, N:136D) lineage with ORF1b: M1156I (60 seq, c. 10 % of BA.5)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#625]
Proposal for a sublineage of BA.5
Earliest sequence: 3/17/2022 (South Africa)
Countries detected:  mainly South Africa, with recent spread to various other European countries (e.g. UK, Denmark, Austria)
Defining mutations:
G16935A = ORF1b:M1156I

This sublineage represents c. 10% of all current BA.5 genomes but is apparently expanding since it is already present in multiple European countries (UK, Denmark). The sublineage was recently detected in Austria where it represents c. 40% of all BA.5 genomes (6/14).
It is apparently a sublclade of the clades containing N:E136D and ORF1a:Q556K (#550) so these issues may have to  be resolved first before this one is designated. However, this is a not a sublineage of the big branch proposed in #551 since it is not defined by ORF9b:D16G.

![pic](https://user-images.githubusercontent.com/102166254/168071626-31fb1e34-92f9-4698-be26-9af1cf8659b2.PNG)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ec1_cb5770.json?branchLabel=aa%20mutations&c=gt-ORF1ab_5557&label=nuc%20mutations:C27889T

EPI_ISL_11903047, EPI_ISL_12097378, EPI_ISL_12097401, EPI_ISL_12307666, EPI_ISL_12278987, EPI_ISL_12474460, EPI_ISL_12559421, EPI_ISL_12559445, EPI_ISL_12559431, EPI_ISL_11903044, EPI_ISL_12576083, EPI_ISL_12587910, EPI_ISL_12012871, EPI_ISL_12587422, EPI_ISL_12576073, EPI_ISL_12559439, EPI_ISL_12559443, EPI_ISL_12559428, EPI_ISL_11621349, EPI_ISL_12278975, EPI_ISL_12278995, EPI_ISL_12278996, EPI_ISL_12268514, EPI_ISL_12268509, EPI_ISL_12097394, EPI_ISL_12278982, EPI_ISL_12576084, EPI_ISL_12473576, EPI_ISL_12549920, EPI_ISL_12473869, EPI_ISL_12243756, EPI_ISL_12278993, EPI_ISL_12587876, EPI_ISL_12307695, EPI_ISL_12097320, EPI_ISL_12307609, EPI_ISL_12307553, EPI_ISL_12558828, EPI_ISL_12632652, EPI_ISL_12490829, EPI_ISL_12490240, EPI_ISL_11999060, EPI_ISL_12097405, EPI_ISL_12559441, EPI_ISL_12558432, EPI_ISL_12558341, EPI_ISL_12559420, EPI_ISL_12181267, EPI_ISL_12473602, EPI_ISL_12473579, EPI_ISL_12473580, EPI_ISL_12473573, EPI_ISL_12473590, EPI_ISL_12473601, EPI_ISL_12610572, EPI_ISL_12610573, EPI_ISL_12610602, EPI_ISL_12610605, EPI_ISL_12610608, EPI_ISL_12610548

**Comment by corneliusroemer** [comment]
Yep, looks like this is a subsublineage of #550, a sublineage of #550 + N:136D

Bit tricky that we have 3 levels of sublineages here. Hard to decide which level to designate and which not.

**Comment by FedeGueli** [comment]
@agamedilab not it is not BE.1 has ORF1b: M1156I as defining whereas BA.5.3.1 starts with N:136D

**Comment by agamedilab** [comment]
@FedeGueli many thanks
