### ISSUE TITLE
Sublineage of BA.2 with S:D1153Y and E:L18I circulating in Scotland

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#626]
The neural network sequence filter "NNSF" build by @bitbyte2015 highlighted E:L18I as an emerging mutation.
After monitoring it for some weeks and realizing that it seems associated with a genuine growth advantage here i want to propose the first of them:

Sublineage of BA.2 with S:D1153Y  + E:L18I
Countries circulating : Uk 117 mainly in Scotland

( be aware that there are a few sublineages with S:D1153G 
as one with 18457T+22858T circulating in uk
or an independent totally distinct BA.2+25791T+S:D1153Y+ ORF9b:I19V+ N:D22G
circulating in the Usa -86seqs
but there are more than three)

To be noticed that S:D1153Y interestingly was the defining mutation of AY.19 a south-african delta lineage ( @c19850727 )

list of sequences:
[contributors.csv](https://github.com/cov-lineages/pango-designation/files/8678814/contributors.csv)

Covspectrum overview:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A1153Y%2CE%3AL18I&pangoLineage=BA.2&

Usher tree: 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_204c8_ce16d0.json?branchLabel=aa%20mutations&c=gt-E_18&label=nuc%20mutations:G25019T
![chrome_screenshot_1652356749775](https://user-images.githubusercontent.com/87669813/168069931-d85fa9ab-4ede-48a1-9641-63970ab179c6.png)

Mutations leading to the branch:
S:D1153Y 
then
C17883T
then
A28654G

Growth advantage (x week):
![chrome_screenshot_1652357109946](https://user-images.githubusercontent.com/87669813/168070819-12f5995b-f362-49e2-8694-1ececcd16bdc.png)
The main contribute to the growth advantage seems coming from E:18I mutation:
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past6M/variants?aaMutations=S%3A1153Y&pangoLineage=BA.2&aaMutations1=E%3AL18I%2CS%3A1153Y&pangoLineage1=BA.2&analysisMode=CompareToBaseline&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.46 with 111 newly designated sequences, and 6 updated designations from BA.2. Defining mutation(s) C26296A (E:L18I), G25019T (S:D1153Y), 28654G (synonymous).
