### ISSUE TITLE
Potential new BA2.3.X lineage in Asturias

### ISSUE THREAD

**Issue by VirologiaHUCA** [cov-lineages/pango-designation#627]
Description
Sub-lineage of: BA.2.3
Earliest sequence:  2022-01-31
Most recent sequence: 2022-04-26
Countries circulating: Spain(24/27 Asturias), USA, England, Denmark, Germany, Italy
<written description of the proposed lineage, where it is circulating, when, why it is distinct>
initially majority clade in Asturias that gains the orf1a_T224I mutation and subsequently generates new clades orf1a_D33N (England/USA) and orf1a_Y949C (USA)

Genomes
<list of genome names as found on GISAID or accession ids - provide as a CSV/TSV table attachment - include locations and dates of sampling>

EPI_ISL_9642232
EPI_ISL_9978944
EPI_ISL_10070569
EPI_ISL_10070575
EPI_ISL_10358442
EPI_ISL_10358443
EPI_ISL_10418398
EPI_ISL_10537523
EPI_ISL_10551553
EPI_ISL_10551556
EPI_ISL_10563073
EPI_ISL_10632286
EPI_ISL_10647413
EPI_ISL_10647417
EPI_ISL_10647421
EPI_ISL_10726958
EPI_ISL_10757216
EPI_ISL_10790449
EPI_ISL_10796404
EPI_ISL_10903023
EPI_ISL_10977904
EPI_ISL_11035172
EPI_ISL_11067250
EPI_ISL_11152735
EPI_ISL_11162592
EPI_ISL_11162594
EPI_ISL_11162597
EPI_ISL_11162598
EPI_ISL_11318325
EPI_ISL_11318664
EPI_ISL_11353524
EPI_ISL_11353533
EPI_ISL_11470527
EPI_ISL_11498922
EPI_ISL_11529257
EPI_ISL_11569465
EPI_ISL_11569506
EPI_ISL_11579318
EPI_ISL_11646060
EPI_ISL_11681606
EPI_ISL_11681607
EPI_ISL_11681608
EPI_ISL_11681616
EPI_ISL_11681644
EPI_ISL_11703553
EPI_ISL_11755009
EPI_ISL_11755841
EPI_ISL_11755872
EPI_ISL_11756128
EPI_ISL_11757846
EPI_ISL_11757856
EPI_ISL_11757897
EPI_ISL_11842369
EPI_ISL_11842550
EPI_ISL_11842644
EPI_ISL_11971666
EPI_ISL_11993414
EPI_ISL_12048939
EPI_ISL_12050435
EPI_ISL_12066991
EPI_ISL_12079945
EPI_ISL_12080736
EPI_ISL_12102767
EPI_ISL_12103142
EPI_ISL_12107391
EPI_ISL_12113673
EPI_ISL_12159791
EPI_ISL_12166702
EPI_ISL_12166930
EPI_ISL_12168739
EPI_ISL_12183682
EPI_ISL_12191601
EPI_ISL_12191836
EPI_ISL_12222106
EPI_ISL_12222115
EPI_ISL_12229493
EPI_ISL_12297482
EPI_ISL_12298048
EPI_ISL_12299103
EPI_ISL_12300450
EPI_ISL_12302369
EPI_ISL_12304405
EPI_ISL_12345926
EPI_ISL_12365161
EPI_ISL_12403470
EPI_ISL_12403476
EPI_ISL_12433841
EPI_ISL_12485264
EPI_ISL_12485290
EPI_ISL_12502808
EPI_ISL_12508028
EPI_ISL_12511471
EPI_ISL_12511486
EPI_ISL_12530405
EPI_ISL_12568900

Evidence
<image from phylogenetic tree?>
![image](https://user-images.githubusercontent.com/105294581/168084416-2982b268-4be8-42fd-ad17-ce36b94e20df.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.3.5 with 144 newly designated sequences, and 55 updated designations from BA.2.3. Defining mutation(s) nt:C936T (ORF1a:T224I). The potential sublineages mentioned, could be submitted as separate proposals should they show signs of epidemiological significance in the future.

**Comment by VirologiaHUCA** [comment]
Thank you very much 

Santiago Melón García 
Sección de Virología 
Hospital Universitario Central de Asturias (HUCA) 
Av. Roma s/n 
33011 Oviedo 
Tlf. 985108720 (Ext 38506) 


De: "InfrPopGen" ***@***.***> 
Para: "cov-lineages/pango-designation" ***@***.***> 
CC: "VirologiaHUCA" ***@***.***>, "Author" ***@***.***> 
Enviados: Lunes, 30 de Mayo 2022 18:29:01 
Asunto: Re: [cov-lineages/pango-designation] Potential new BA2.3.X lineage in Asturias (Issue #627) 



ATENCIÓN: Este correo electrónico proviene de fuera de la organización. Sea muy cauto, e incluso ignore, los enlaces y archivos adjuntos que aparecen en el mismo, especialmente si desconoce al remitente u observa algún indicio de posibles contenidos maliciosos. Es esencial recordar que NUNCA  DEBE INTRODUCIR  SUS CONTRASEÑAS COMO RESPUESTA A UN CORREO. 




Thanks for submitting. We've added lineage BA.2.3.5 with 144 newly designated sequences, and 55 updated designations from BA.2.3. Defining mutation(s) nt:C936T (ORF1a:T224I). The potential sublineages mentioned, could be submitted as separate proposals should they show signs of epidemiological significance in the future.
