### ISSUE TITLE
Proposal to designate a recombinant lineage

### ISSUE THREAD

**Issue by benjamincjackson** [cov-lineages/pango-designation#63]
A recombinant origin for the following three sequences was discussed here: https://virological.org/t/recombinant-sars-cov-2-genomes-involving-lineage-b-1-1-7-in-the-uk/658

```
Wales/ALDP-11CF93B/2021
Wales/ALDP-125C4D7/2021
Wales/LIVE-DFCFFE/2021
```

Their parental lineages are B.1.1.7 and B.1.177. The breakpoint location was identified as being between base 21255 and base 21764 in reference coordinates. 

A follow-up scan has revealed 42 additional sequences in the UK dataset that are derived from them and likely represent community transmission of the lineage. Those have following IDs:

```
Wales/ALDP-130BB95/2021
England/ALDP-14D45E1/2021
England/ALDP-149E440/2021
England/ALDP-1495634/2021
England/ALDP-14984FB/2021
England/ALDP-147639C/2021
England/ALDP-149767E/2021
England/ALDP-1474D81/2021
England/ALDP-1474F12/2021
England/ALDP-14690C2/2021
England/ALDP-146C8E5/2021
England/ALDP-146F9A3/2021
England/ALDP-145EEA8/2021
England/ALDP-1454464/2021
England/ALDP-14540F7/2021
England/ALDP-1449954/2021
England/ALDP-1459229/2021
England/ALDP-1458CD1/2021
England/ALDP-1438624/2021
Wales/PHWC-PYBIFF/2021
England/ALDP-143F380/2021
England/ALDP-143098D/2021
England/ALDP-14308AE/2021
England/ALDP-1437ED2/2021
England/ALDP-14381AB/2021
England/ALDP-142797A/2021
England/ALDP-142CABE/2021
England/ALDP-142CC21/2021
England/ALDP-142C957/2021
England/ALDP-142BACE/2021
England/ALDP-142B958/2021
England/ALDP-1429680/2021
England/ALDP-141A716/2021
England/ALDP-141753D/2021
England/ALDP-141A224/2021
England/ALDP-141E7F4/2021
Wales/PHWC-PYY47T/2021
Wales/PHWC-PYY4OM/2021
Wales/PHWC-PYY4TJ/2021
England/ALDP-13FAB7B/2021
England/ALDP-1401D89/2021
England/LIVE-E05692/2021
```

The earliest sample date is 2021/01/30, and the latest sample date is 04/04/2021.

The tree shows the recombinants and their nearest neighbours by genetic distance in the dataset (the clade above them) as well as a sample of sequences that they are derived from (near the root of the tree):
![tree](https://user-images.githubusercontent.com/5540087/116262744-b59be280-a770-11eb-9d2d-807b0cf285e9.png)

Here is the nucleotide variation for all the recombinants:
![snipit](https://user-images.githubusercontent.com/5540087/116263934-bf721580-a771-11eb-8e48-3c4374307c91.png)

**Comment by rambaut** [comment]
As the first recombinant lineage this will be given the label `XA` (sublineages of this would be denoted `XA.1` etc).  Provisional rules for naming recombinant lineages are here: https://virological.org/t/657

**Comment by chrisruis** [comment]
Now designated XA in [1.1.29](https://github.com/cov-lineages/pango-designation/releases/tag/1.1.29) with 43 sequence designations.

Sequences Wales/LIVE-DFCFFE/2021 and England/LIVE-E05692/2021 were not included in the designations as they contain >5% ambiguities
