### ISSUE TITLE
French BA.2.9 sublineage with S:W64R (21752C) with global circulation (~5% in France, 597 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#630]
S:W64R is one of the BA.2 mutations we are seeing popping up in different lineages convergently , 
it was highlighted first by @corneliusroemer last week and today by @RajLABN with a tweet (https://twitter.com/RajlabN/status/1524768961228947456?s=20&t=cgGTMkJ_c9yPlK7-CONs3A)

Here i want to propose one BA.2.9 sublineasge carrying S:W64R

Nr sequences: 533
First sequence: 15/2022
Countries: France 292 seqs, Uk 110 seqs, 72 Denmark 48 Germany , Spain , Israel , Usa , Hong Kong)
EPI_ISLs: 
[contributors (18).csv](https://github.com/cov-lineages/pango-designation/files/8682925/contributors.18.csv)

Growth advantage seems solid vs current BA.2 baseline (39%)
![Schermata 2022-05-13 alle 00 23 12](https://user-images.githubusercontent.com/87669813/168177348-5c95c48f-c067-4ce3-9172-cb8c1661376d.png)

[Cov-spectrum overview](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AW64R&pangoLineage=BA.2.9*&aaMutations1=S%3AW64R&pangoLineage1=BA.2.9*&)

Usher tree for this branch is clear: 
![Schermata 2022-05-13 alle 00 20 03](https://user-images.githubusercontent.com/87669813/168177017-35453f5e-4a5f-4821-b359-8db7ccac2ade.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_32212_d83eb0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C241T,T670G,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10029T,C10198T,G10447A,C10449A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,C22792T,G22813T,T22882G,G22992A,C22995A,A23013C,A23040G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C25624T,C26060T,C26270T,C26577G,G26709A,C26858T,A27259C,G27382C,A27383T,T27384C,C27807T,A28271T,C28311T,G28881A,G28882A,G28883C,A29510C

**Comment by corneliusroemer** [comment]
Globally, two nuc mutations are responsible for S:W64R: `21752C` and `21752A`, in this case it's `C`.

Pretty clear from the timeline that this lineage seems to have started off in France:
<img width="2528" alt="image" src="https://user-images.githubusercontent.com/25161793/168265767-7969fdcf-a1e7-4c2b-aa70-2516752b0b5e.png">

**Comment by FedeGueli** [comment]
Thx @corneliusroemer i dint know that! thank you very much

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.9.3 with 609 newly designated sequences, and 124 updated designations from BA.2.9. Defining mutation(s) T21752C (S:W64R).
