### ISSUE TITLE
BA.2 (+22792T) with S:1261Y [848 in Denmark, 1129 global]

### ISSUE THREAD

**Issue by olias120676** [cov-lineages/pango-designation#631]
Slowly growing (12% growth advantage per week) BA.2 (+22792T) with S:1261Y (C25344A).

Appears to have started circulating in Denmark since late 2021, then spreading beyond from February 2022 onwards. 

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C25344A%2C22792T&pangoLineage=BA.2*

Earliest sequence:-
Denmark/DCGC-316814/2021 | EPI_ISL_8834149

Within this subtree there are a a couple of spike mutations at 248, S:Y248H (T22304C) and S:Y248S (A22305C). 

The S:Y248H branch seems more notable, with 432 sequences and growth advantage in Denmark currently showing as [29% per week](https://cov-spectrum.org/explore/Denmark/AllSamples/Past6M/variants?pangoLineage=BA.2*&nucMutations1=C25344A%2C22792T%2C22304C&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&) 

![C25344A](https://user-images.githubusercontent.com/24962257/168270496-4de3bdf6-dfb3-40c0-863b-ce15eb1df28e.png)
![treeC25344A](https://user-images.githubusercontent.com/24962257/168270508-3ee80b40-3cfe-463d-968d-3ceb24bddde8.png)

[EPI_ISL list](https://lapis.cov-spectrum.org/gisaid/v1/sample/gisaid-epi-isl?dateFrom=2021-11-08&nucMutations=C25344A%2C22792T&pangoLineage=BA.2*&host=Human&orderBy=random) 

[USHER tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2a3a1_e31360.json?branchLabel=Spike%20mutations&c=gt-S_1261,248&label=nuc%20mutations:C22792T)

**Comment by FedeGueli** [comment]
Good catch @olias120676 ! it seems that the growth advantage of the sublineage with S:248H in England is above 40%, that is interesting considering the circulation of quite every new high trasmissible lineage there.

**Comment by Sinickle** [comment]
S:248S has also appeared in the UK and the USA 600 times between the two of them, and has a similarly large growth advantage over BA.2.

**Comment by corneliusroemer** [comment]
I'd probably focus on the 248H contained within. Not sure how much S:1261T does on its own.

**Comment by corneliusroemer** [comment]
S:248H makes up (almost) all of the sequences of the S:1261Y lineage by now.

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/25161793/168343492-1f12aa3c-76ce-444f-bcf6-1dfafe10fef3.png">

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.47 with 803 newly designated sequences, and 45 updated designations from BA.2. Defining mutation(s) T22304C (S:Y248H).
