### ISSUE TITLE
Potential New BA.2.x lineage with S:G257S + ORF1ab:P2287S circulating in Puerto Rico with spillover into multiple US states and Europe (251 seqs as of 6/5/2022)

### ISSUE THREAD

**Issue by arodzh-sudo** [cov-lineages/pango-designation#632]
## Description

Potential sublineage of **BA.2** monitored by the Puerto Rico Public Health Laboratory
Earliest sequence: **2022/03/07 from Puerto Rico**
Most recent sequence: **2022/05/03 from UK/Scotland and Canada**
Mutation on top of BA.2: **ORF1ab:P2287S + S:G257S**
Countries circulating: **Puerto Rico, United States, Canada and UK (Scotland)**

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/00arh0/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/00arh0/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Country | Number of sequences
-- | --
United States | 110 (**113 seqs**, 3 seqs from Puerto Rico were uploaded as North America / USA)
United Kingdom | 3
Canada | 1
  |  
Division | Number of sequences
Puerto Rico | 61 (**64** seqs, 3 seqs from Puerto Rico were uploaded as North America / USA)
New York | 9
Pennsylvania | 9
Florida | 4
Michigan | 3
New Jersey | 3
Scotland | 3
South Carolina | 3
Connecticut | 2
Illinois | 2
Virginia | 2
California | 1
Colorado | 1
Georgia | 1
Louisiana | 1
Massachusetts | 1
Minnesota | 1
Nevada | 1
North Carolina | 1
Ontario | 1
Rhode Island | 1
Texas | 1
Utah | 1
Wisconsin | 1

</body>

</html>

![image](https://user-images.githubusercontent.com/54407020/168491806-eb9cc375-c24e-4152-8e7e-d8fbfcf66e33.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2aa3c_e52df0.json?branchLabel=aa%20mutations&c=gt-ORF1ab_2287

Cov-spectrum query: 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AP2287S%2CS%3AG257S&pangoLineage=BA.2*&

Also, interestingly enough a group of BA.2.12.1 sequences, mostly from USA, are also picking up the S:G257S mutation:
![Screenshot 2022-05-13 at 09-31-58 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ singleSubtreeAuspice_genome_2aa3c_e52df0 json](https://user-images.githubusercontent.com/54407020/168294722-85728e9f-9ae9-464e-98fe-46b71ea40147.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2aa3c_e52df0.json?branchLabel=Spike%20mutations&c=pango_lineage

Estimates from cov-spectrum suggest a relative growth advantage of ~37% over a BA.2 baseline:
![Screenshot 2022-05-13 at 09-39-30 covSPECTRUM](https://user-images.githubusercontent.com/54407020/168296098-c9add18e-c7d5-4d02-abe7-85f96f41dc77.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.2*&aaMutations1=ORF1a%3AP2287S%2CS%3AG257S&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&

List of genomes:

[contributors-ORF1abP2287S-SD257S.csv](https://github.com/cov-lineages/pango-designation/files/8688194/contributors-ORF1abP2287S-SD257S.csv)

**Comment by arodzh-sudo** [comment]
@InfrPopGen could you take a look a quick look at this? In Puerto Rico we have a low sequencing rate at about ~0.015% of positive cases sequenced. We think this small clade might be significant based on the aforementioned. Thanks.

**Comment by chrisruis** [comment]
Thanks @arodzh-sudo We've added this as BA.2.73 to start on the branch with G22331A (S:G257S)
