### ISSUE TITLE
US BA.2 (+ ORF1a:T1322I) S:248S lineage [408 seq, 1% in US and growing]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#634]
Noticed that S:248S was growing quickly in the US. Turns out there are 2 independent 248S lineages. This is the one that seems to grow faster and be particularly US specific.

It's on a branch of BA.2 + A15972G + C16779T + ORF1a:T1322I

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_3109c_eab240.json?c=country&label=nuc%20mutations:C16779T

with e.g. `USA/NY-PRL-0429_00I01/2022|EPI_ISL_12590296|2022-04-27`

Here one can see that it appears to grow faster than BA.2.12.1 in the US, also in New York. This could of course be by chance but I think it's worth monitoring/designating because the spike mutation could explain the growth advantage (also homoplasy at this site is indicative).

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/25161793/168374569-0bf92dfc-853a-4ea2-a06e-ccadc5e70af4.png">

https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=S%3A248S%2CORF1a%3A1322I&pangoLineage=BA.2*&aaMutations1=S%3A452Q&pangoLineage1=BA.2*&

Also now appearing globally, first sequence was apparently US, though a singlet it seems

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/25161793/168374831-4d294fe1-56f8-4cbd-b4bc-5beec9c8bcbf.png">

**Comment by FedeGueli** [comment]
S:248-249 was the exact point where the insertion during  the in vitro experiment lead by Andreano et Rappuoli happened:
https://www.biorxiv.org/content/10.1101/2020.12.28.424451v1

Obviously one point mutation is not the same as an 11aa insertion but equally i think it has to be monitored closely.

**Comment by FedeGueli** [comment]
497 sequences as today.  It is the second fastest (not counting BA.4/BA.5) BA.2 sublineage in my list, the first amongst the undesignated ones
I think it deserves a rapid designation to help tracking it
@corneliusroemer @chrisruis @AngieHinrichs

**Comment by FedeGueli** [comment]
730 seqs as today. sustained circulation of this sublimeage.

**Comment by FedeGueli** [comment]
854 *sequences. This sublineage seems slighty more transmissible than BA.2.12.1.

It should be designated @corneliusroemer @InfrPopGen @corneliusroemer @chrisruis @AngieHinrichs 

https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?pangoLineage=BA.2.12.1*&aaMutations1=ORF1a%3AT1322I%2CS%3A248S&nucMutations1=A15972G%2CC16779T&pangoLineage1=BA.2&analysisMode=CompareToBaseline&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.48 with 676 newly designated sequences, and 16 updated designations from BA.2. Defining mutation(s) C16779T (synonymous), C4230T (ORF1a:T1322I), 22305C (S:248S).
