### ISSUE TITLE
French BA.2.9 with S:346T [170 seq, 2% in France]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#635]
I noticed that S:346T was growing within BA.2, particularly in France and India. There are too few sequences from India to propose a lineage, but the French cluster is very clear and localized to Auvergne-Rhone-Alpes and Bourgogne, two neighbouring regions.

The French one is a sublineage of BA.2.9 with S:346T (and ORF7a:5F). We know S:346 from BA.1.1, where it was mutated to K.

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/25161793/168376040-e9c9425a-43a1-4bed-8fae-14f681649d35.png">

This is where it's shown up
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/25161793/168376095-f9ecc8f1-66ee-41f4-bcf1-dd0dbc8bc88d.png">

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/25161793/168376285-aa40302b-8d5f-4dc1-ab03-dee33036add0.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3db34_eb0a30.json?c=pango_lineage_usher&label=nuc%20mutations:C25624T

`France/ARA-HCL022076848701/2022|EPI_ISL_12628555|2022-05-01`

**Comment by FedeGueli** [comment]
227 as today. 4% of french sequences in the last two weeks
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3A346T%2COrf3a%3A78Y%2Corf7a%3A5F&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.9.4 with 230 newly designated sequences, and 34 updated designations from BA.2.9. Defining mutation(s) C27406T (ORF7a:L5F), G22599C (S:R346T).

**Comment by FedeGueli** [comment]
There is a small cluster of this sublineage with S:K444R circulating recently (august/22) in Switzerland 5 seqs. 
I'll keep that monitored.

**Comment by FedeGueli** [comment]
Sequences should be 7 now.
NS3_H78Y, Spike_R346T,Spike_K444R query.
