### ISSUE TITLE
Potential BA.2*/BA.1* Recombinant with Likely Breakpoint at ORF3a/M (86 Seqs as of 2022-05-31 in Multiple US States, Germany and Denmark)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#636]
I am making another recombinant proposal below the 50-sequence bar considering this one is being found in more than a few different US states.

### Description
**Recombinant between**: BA.2* & BA.1*
**Earliest sequence**: 2022/3/20 (US-CA)
**Most recent sequence**: 2022/5/2 (US-DC)
**Countries circulating**: US (CA, AZ, NM, TX, PA, NC, NY, WI, DC, MD, IL)
**Likely breakpoint**: between 26062 and 26250 (ORF3a to M protein).
**Mutations on branch**: G20398A (ORF1b:E2311K )

**Conserved Nuc mutations** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/168420817-823a52d2-34fc-4464-8f26-12f23caf4f25.png)
**Cov-spectrum query**: 29510A, 20398A, 26530G, 26060T
**GISAID query**: NS3_T223I, NSP15_E260K, M_D3G, Spike_A27S

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/168420981-20e27b24-9b15-479b-9a77-5dc76771c2a9.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36121_f79db0.json?branchLabel=aa%20mutations&c=gt-nuc_20398&label=nuc%20mutations:T22792C

### Genomes:
EPI_ISL_11757732, EPI_ISL_12009425, EPI_ISL_12047050, EPI_ISL_12048016, EPI_ISL_12116085, EPI_ISL_12117935, EPI_ISL_12272210-12272211, EPI_ISL_12272367, EPI_ISL_12295774, EPI_ISL_12301358, EPI_ISL_12303708, EPI_ISL_12303719, EPI_ISL_12384754, EPI_ISL_12424643, EPI_ISL_12462375, EPI_ISL_12497819, EPI_ISL_12500399, EPI_ISL_12502677, EPI_ISL_12502988, EPI_ISL_12530548, EPI_ISL_12590019, EPI_ISL_12597174, EPI_ISL_12615586, EPI_ISL_12618638, EPI_ISL_12621533, EPI_ISL_12641007, EPI_ISL_12642893, EPI_ISL_12654010, EPI_ISL_12656170, EPI_ISL_12656431, EPI_ISL_12657321, EPI_ISL_12658316

**Comment by emily-smith1** [comment]
There are now 56 of these genomes in the UShER tree from 12 different US states:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/84812104/170121135-6120df77-ee2b-40b1-8c5c-b6662ece16ed.png">

Genomes: EPI_ISL_12618638,EPI_ISL_12706626,EPI_ISL_12641007,EPI_ISL_12768818,EPI_ISL_12713785,EPI_ISL_12836478,EPI_ISL_12615586,EPI_ISL_12272210,EPI_ISL_12497819,EPI_ISL_12642893,EPI_ISL_12758006,EPI_ISL_12836460,EPI_ISL_12424643,EPI_ISL_12621533,EPI_ISL_12272367,EPI_ISL_11757732,EPI_ISL_12303708,EPI_ISL_12048016,EPI_ISL_12656170,EPI_ISL_12658316,EPI_ISL_12590019,EPI_ISL_12836443,EPI_ISL_12500399,EPI_ISL_12502988,EPI_ISL_12502677,EPI_ISL_12009425,EPI_ISL_12768811,EPI_ISL_12116085,EPI_ISL_12770670,EPI_ISL_12766234,EPI_ISL_12770694,EPI_ISL_12272211,EPI_ISL_12713730,EPI_ISL_12462375,EPI_ISL_12758001,EPI_ISL_12745468,EPI_ISL_12047050,EPI_ISL_12530548,EPI_ISL_12760943,EPI_ISL_12654010,EPI_ISL_12295774,EPI_ISL_12301358,EPI_ISL_12384754,EPI_ISL_12745544,EPI_ISL_12597174,EPI_ISL_12758715,EPI_ISL_12713625,EPI_ISL_12657321,EPI_ISL_12656431,EPI_ISL_12117935,EPI_ISL_12303719,EPI_ISL_12697347,EPI_ISL_12712060

**Comment by c19850727** [comment]
Thanks @emily-smith1 ! 

I was just doing daily routine double-checking and actually found 68 sequences using GISAID query in 14 different US states.

### Genomes:
EPI_ISL_11757732, EPI_ISL_12003788, EPI_ISL_12009425, EPI_ISL_12047050, EPI_ISL_12048016, EPI_ISL_12116085, EPI_ISL_12117935, EPI_ISL_12272210-12272211, EPI_ISL_12272367, EPI_ISL_12295774, EPI_ISL_12301358, EPI_ISL_12303708, EPI_ISL_12303719, EPI_ISL_12384754, EPI_ISL_12424643, EPI_ISL_12462375, EPI_ISL_12497819, EPI_ISL_12500399, EPI_ISL_12502677, EPI_ISL_12502988, EPI_ISL_12530548, EPI_ISL_12590019, EPI_ISL_12597174, EPI_ISL_12615361, EPI_ISL_12615586, EPI_ISL_12618638, EPI_ISL_12621533, EPI_ISL_12641007, EPI_ISL_12642893, EPI_ISL_12654010, EPI_ISL_12656170, EPI_ISL_12656431, EPI_ISL_12657321, EPI_ISL_12658316, EPI_ISL_12697347, EPI_ISL_12712060, EPI_ISL_12713625, EPI_ISL_12713730, EPI_ISL_12713785, EPI_ISL_12745468, EPI_ISL_12745544, EPI_ISL_12758001, EPI_ISL_12758006, EPI_ISL_12758715, EPI_ISL_12760943, EPI_ISL_12766234, EPI_ISL_12768811, EPI_ISL_12768818, EPI_ISL_12770670, EPI_ISL_12770694, EPI_ISL_12836443, EPI_ISL_12836460, EPI_ISL_12836478, EPI_ISL_12844430, EPI_ISL_12858867, EPI_ISL_12860983, EPI_ISL_12864001, EPI_ISL_12867408, EPI_ISL_12867794, EPI_ISL_12868001, EPI_ISL_12868071, EPI_ISL_12868980, EPI_ISL_12874058, EPI_ISL_12874162, EPI_ISL_12874458, EPI_ISL_12884819, EPI_ISL_12887866

### Usher tree:
![image](https://user-images.githubusercontent.com/86835836/170161166-f2475ca0-d174-44e7-8282-f68257e9db8c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8474_d893d0.json?c=userOrOld&label=nuc%20mutations:G20398A

**Comment by c19850727** [comment]
74 sequences as of 2022-05-26.

**Comment by c19850727** [comment]
79 sequences as of 2022-05-29, and newly found in Denmark.

**Comment by emily-smith1** [comment]
Now found in Germany: EPI_ISL_13033910

I just submitted two more from the US to GISAID.

**Comment by c19850727** [comment]
Like @emily-smith1 mentioned (many thanks!), 86 sequences as of 2022-05-31, and now found in Germany.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XZ with 61 newly designated sequences, and 0 updated designations.

**Comment by proychou** [comment]
Anyone know why outbreak.info doesn't show any samples associated with this lineage?

**Comment by AngieHinrichs** [comment]
Hi @proychou - I see GISAID has 170 sequences assigned to XZ so I'm not sure why outbreak.info doesn't have it.  The outbreak.info folks might see your question sooner if you post it here: https://github.com/outbreak-info/outbreak.info/issues

**Comment by flaneuse** [comment]
@proychou thanks for spotting this. We’re currently using Pangolearn as our inference engine, and these XZ sequences have low confidence, so it defaults to Scorpio’s call of a generic BA.2. We plan on switching to UShER soon to address this issue.
