### ISSUE TITLE
New sublineage of BA.2 +22792T with N:D377V circulating in France prevalence - 1% (653 seqs on usher tree)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#640]
This is a sublineage of BA.2 with 22792T circulating in France and Uk characterized by AA mutation N:D377V and nuc 13620T

First sequence:
week 4/2022
Countries: France , UK
List of sequences :
[contributors (19).csv](https://github.com/cov-lineages/pango-designation/files/8695069/contributors.19.csv)

[CovSpectrum overview:](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=N%3A377V&pangoLineage=BA.2*&aaMutations1=S%3A212S&nucMutations1=C9532T&pangoLineage1=BA.2*&

)

The tree is clear and interesting it further splits in two branches a smaller one with S:T732I and a bigger one with A29767T.
This branch then acquired S:212S and orf1a:T2021I
![Schermata 2022-05-15 alle 15 45 10](https://user-images.githubusercontent.com/87669813/168476189-ba3d2be9-2403-44ec-b200-95741f940461.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice6_genome_26af6_d3570.json?branchLabel=aa%20mutations&c=gt-N_377&label=nuc%20mutations:A29403T

Growth advantage is similar in France
![Schermata 2022-05-15 alle 15 52 11](https://user-images.githubusercontent.com/87669813/168476435-28cc8b52-9577-42b8-8248-efe980b9c57a.png)
and Uk:
![Schermata 2022-05-15 alle 15 52 26](https://user-images.githubusercontent.com/87669813/168476451-d6b5e7fd-337b-4c44-a30d-34e7e3786774.png)

Interestingly the branch with S:212S shows a solid 37% of growth advantage vs the parental lineage:
![Schermata 2022-05-15 alle 15 56 15](https://user-images.githubusercontent.com/87669813/168476586-30ff090c-e6ac-40ce-9173-16b7430567d9.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.49 with 630 newly designated sequences, and 40 updated designations from BA.2. Defining mutation(s) A29403T (N:D377V).
