### ISSUE TITLE
BA.2 sublineage with S:L212S circulating in UK (1% prevalence/ 589 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#641]
@corneliusroemer and @c19850727 noticed an uptick in BA.2 sequences carrying S:L212S some time ago.
After monitoring its growth since , today i digged a bit more in it finding that this mutation seems to be popping up in several distinct sublineages pointing to convergent evolution toward it and maybe some fitness advantage in the context of the Omicron spike.
In #640 i have proposed a broader lineage that acquired S:212S and showing trasmission advantage since.
This could be confirmed by the fact that all sublineages carrying this mutation are showing an early apparent growth advantage between 10-40% x week.
Here i want to propose the second one of the three main sublineages with S:212S circulating in Uk (the first is mentioned in #640).

Mutations:
The S:212S mutation arose from a BA.2 sublineage carrying C13620T:

![Schermata 2022-05-15 alle 19 38 43](https://user-images.githubusercontent.com/87669813/168486345-ba84c632-a1e5-44ba-a907-40589cc01165.png)

[Click here for Usher tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ab54_e5c40.json?branchLabel=aa%20mutations&c=gt-nuc_13620&label=nuc%20mutations:C241T,T670G,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10029T,C10198T,G10447A,C10449A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,G22992A,C22995A,A23013C,A23040G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,C26577G,G26709A,C26858T,A27259C,G27382C,A27383T,T27384C,C27807T,A28271T,C28311T,G28881A,G28882A,G28883C,A29510C
)

Number of sequences: 509
List of Sequences:
[contributors (20).csv](https://github.com/cov-lineages/pango-designation/files/8695585/contributors.20.csv)
Country: Uk (252 seqs Scotland, 218 seqs England)
First sequence: Uk 5/2022
Prevalence in UK: 1%

[Covspectrum overview](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A212S&nucMutations=C2749T%2CC13620T%2CT22197C&pangoLineage=BA.2*&aaMutations1=S%3A212S&nucMutations1=29767T%2CC22792T&pangoLineage1=BA.2*&)

[Growth Advantage ](https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?pangoLineage=BA.2*&aaMutations1=S%3A212S&nucMutations1=C2749T%2CC13620T%2CT22197C&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&)vs BA.2* baseline:
32% England 37% Scotland:
![Schermata 2022-05-15 alle 19 44 43](https://user-images.githubusercontent.com/87669813/168486638-df758cd0-1c17-4387-b565-7f4033e0ca24.png)

**Comment by theosanderson** [comment]
S:L212S isdefinitely popping up a lot on BA.2. Red = notionally independent mutations S:L212S with at least 10 descendants:
![image](https://user-images.githubusercontent.com/19732295/168921516-94065e18-88ae-4c69-9e77-3c741f4b281e.png)

From https://cov2tree.org/?srch=%5B%7B%22key%22%3A%22tb7y32stgp%22%2C%22type%22%3A%22mutation%22%2C%22method%22%3A%22mutation%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A%22212%22%2C%22new_residue%22%3A%22S%22%2C%22min_tips%22%3A%2210%22%7D%5D&enabled=%7B%22aa1%22%3Atrue%2C%22tb7y32stgp%22%3Atrue%7D&color=%7B%22field%22%3A%22None%22%2C%22pos%22%3A212%7D&zoomToSearch=0

**Comment by FedeGueli** [comment]
Yes @theosanderson also in Usher Tree taking the last two weeks from.CovSpectrum it popped up multiple times in distinct sublineages,
there is a trend (that i dont recall we have seen before in AYs era for example) toward independently acquired spike mutations as S:68T, 176F, 212S, 248H/S/N, 255F , 346X, 356T, 417T, 452X, 1153Y, and maybe also 1162, 1263,1264, and probably @corneliusroemer @bitbyte2015 @silcn could add more than these ones.

**Comment by FedeGueli** [comment]
589 seqs as today

**Comment by InfrPopGen** [comment]
Hi, looking in contributors (20).csv suggests a lineage with root mutation S:L212S, and India/WB-INSACOG-1931300617292/2022 "lies on" this node; however, the comments above imply that a descendant of BA.2.49 (as in #640) is expected, and this would probably be the S:L212S node from which England/PHWC-PJGPYR/2022 arises. The cov-spectrum query above leads me to the India/WB-INSACOG-1931300617292/2022 clade, but other comments suggest otherwise, so I wanted to be sure.

**Comment by FedeGueli** [comment]
Hi @InfrPopGen 

probably i misleaded you to think this is related to BA.2.49 (just found at the same time while trying to describe the emerging S:212S mutation in BA.2) I didnt find any link between this one and #640 but i can be wrong

**Comment by InfrPopGen** [comment]
Hi @FedeGueli

Thank you for the clarification, and thanks for submitting. I've added lineage BA.2.50 with 514 newly designated sequences, and 34 updated designations from BA.2. Defining mutation(s) T22197C (S:L212S).
