### ISSUE TITLE
BA.2 Sublineage with double spike mutation S:212S and S:V1177I circulating in Uk (248 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#642]
This is the third distinct sublineage carrying S:L212S circulating in Uk in the last weeks that i propose to be designated after #640 and #641
This one is interesting because it has a double mutation in the spike : S:212S S:V1171I

Looking at the tree it seems to arise from a branch carrying nuc mutation : C5812T 
that further in the tree was reverted back to 5812C.
The branch with nuc 5812 reverted to C represents the mayority of sequences of this sublineage (177 out of 210)
![Schermata 2022-05-15 alle 20 05 21](https://user-images.githubusercontent.com/87669813/168487370-055253ac-f84f-4e44-a011-e205cbd3842f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_1ab54_e5c40.json?branchLabel=aa%20mutations&c=gt-nuc_5812,22197,25091&label=nuc%20mutations:C5812T

First sequence: 7/2022
Number of sequences : 210
Countries : Mainly Uk
List of sequences:
[contributors (25).csv](https://github.com/cov-lineages/pango-designation/files/8695647/contributors.25.csv)

CovSpectrum [overview](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=S%3A212S%2CS%3AV1177I&nucMutations=25091A&pangoLineage=BA.2*&aaMutations1=S%3A212S%2CS%3AV1177I&nucMutations1=C5812T%2CG25091A&)

Growth advantage: around 18%
![Schermata 2022-05-15 alle 20 26 06](https://user-images.githubusercontent.com/87669813/168488144-e28e3d90-ce2b-4b9c-90c8-8f8cfd595e5b.png)
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?pangoLineage=BA.2*&aaMutations1=S%3A212S%2CS%3AV1177I&nucMutations1=G25091A&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
248 sequences as today. Huge growth disadvantage vs BA.2.12.1* i'll keep it open for a while till when it would be clearer how situtation will evolve.

**Comment by chrisruis** [comment]
Let's add a monitor to this for now - it may be growing slowly in the UK but is still very low proportion of UK BA.2 sequences

**Comment by FedeGueli** [comment]
273 seqs as today, i'll close this one cause it has no growth advantage vs BA.5 (-60%) . I'll keep this monitored.
