### ISSUE TITLE
BA.2.3 sublineage with S:K97E (59 seq as of 2022-05-31, >80%? in Taiwan)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#643]
Proposal for a sublineage of BA.2.3
Earliest sequence: 2022-03-28 (Japan ex-Vietnam)
Countries detected: Taiwan (7 seq), Hong Kong (5), Japan ex-Vietnam (2), South Korea, USA, Denmark (1 each)

Mutations on top of BA.2.3: 
ORF1a:L631F, N:M322I, S:K97E

While there are very few sequences, I'm proposing this because Taiwan is experiencing its first major Covid wave, and out of the 8 sequences from this wave so far, 7 are this lineage. This suggests it could be at very high prevalence in Taiwan. It is descended from a mainly Vietnamese branch with ORF1a:L631F and N:M322I but not S:K97E.

<img width="722" alt="Taiwan_lineage" src="https://user-images.githubusercontent.com/42699509/168499572-fd192bc0-7aa9-4ecb-bd29-7262862e0ef2.png">

[https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4199d_1865d0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A21851G](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4199d_1865d0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A21851G)

Interestingly, examination of the tree suggests there may have been 3 separate introductions to Taiwan, as the two Hong Kong sequences from 2022-04-08 predate almost all of Taiwan's reported cases. I expect this will become clearer as more sequences come in, but at least for now it hints that there might be some unsampled circulation of this lineage somewhere.

[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AA2909V%2CORF1a%3AL631F%2CN%3AM322I%2CS%3AK97E&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AA2909V%2CORF1a%3AL631F%2CN%3AM322I%2CS%3AK97E&)

**Comment by silcn** [comment]
4 more sequences now, one each from Hong Kong, Japan ex-Taiwan, the US (NC) and Thailand.

<details><summary>Full list of EPI_ISLs</summary>

EPI_ISL_12096934
EPI_ISL_12096935
EPI_ISL_12138136
EPI_ISL_12419269
EPI_ISL_12534001
EPI_ISL_12537858
EPI_ISL_12537872
EPI_ISL_12640530
EPI_ISL_12667324
EPI_ISL_12667325
EPI_ISL_12667327
EPI_ISL_12667329
EPI_ISL_12667332
EPI_ISL_12667333
EPI_ISL_12667334
EPI_ISL_12681044
EPI_ISL_12693687
EPI_ISL_12724668
EPI_ISL_12727577
EPI_ISL_12764039
EPI_ISL_12771763
</details>

**Comment by silcn** [comment]
Taiwan still hasn't done a batch of uploads since I started this issue, but it seems pretty clear now that this is the dominant lineage there. Up to 59 sequences as of today, many being arrivals from Taiwan. Now also reported in Singapore, Canada, Australia, Spain and Germany.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.3.7 with 20 newly designated sequences, and 0 updated designations. Defining mutation(s) A21851G (S:K97E).
