### ISSUE TITLE
Sublineage of BA.2* + 22792T with S:T747I circulating in Denmark (516 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#644]
Here i want to propose a sublineage of BA.2 in the branch carrying C22792T : 
defining mutation: S:T747I
Main country : Denmark
Nr of sequences : 516
List of Sequences:
[contributors (26).csv](https://github.com/cov-lineages/pango-designation/files/8702121/contributors.26.csv)

[Usher Tree:]
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_11ff7_95d3c0.json?branchLabel=nuc%20mutations&c=gt-S_747&label=nuc%20mutations:C23802T

Modest [growth advantage](https://cov-spectrum.org/explore/Denmark/AllSamples/Past2M/variants?pangoLineage=BA.2*&aaMutations1=S%3AT747I&nucMutations1=22792T&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&) vs BA.2 baseline
![Schermata 2022-05-16 alle 19 28 39](https://user-images.githubusercontent.com/87669813/168649748-46e8fc8f-0bdc-41b8-8ef6-bd3440362300.png)

Spike S747I is not far from 755 that Veesler lab [showed](https://www.science.org/doi/10.1126/science.abn8652) as a key AA interacting with S:N969K recently  [investigated](https://www.biorxiv.org/content/10.1101/2021.12.31.474653v2) by @tompeacock
So I think this lineage is worth to be monitored here.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.51 with 288 newly designated sequences, and 22 updated designations from BA.2. Defining mutation(s) C23802T (S:T747I).
