### ISSUE TITLE
BA.2 sublineage with S:247insSGE and S:Y248N (~190 seq, ~2% in Italy)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#648]
Inspired by @FedeGueli's comment about an insertion at S:248 having occurred in vitro, I had a look for insertions near this site, and it turns out they are reasonably frequent. The most common is a 9nt out-of-frame insertion nuc:22304insCAGGGGAGA, resulting in what I suppose would properly be called S:Y248SGEN. Nextclade and occasionally GISAID report it as S:247insSGE and S:Y248N, whereas GISAID usually reports it as S:248insGEN and S:Y248S.

This particular insertion seems to have arisen several times independently (see later**). The biggest cluster is a sublineage of BA.2+C22792T, and looks like it may co-occur with ORF1a:C655R = nuc:T2228C, which should help with designation. This is the one I'm proposing here.

As usual with insertions, this one often doesn't get called, so it's hard to tell how big the lineage really is. Usher [splits](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_21fa1_41f360.json?c=userOrOld&label=nuc%20mutations:T670G,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,G10447A,C12880T,T15240C,C15714T,C17410T,C19955T,A20055G,C21618T,T21762C,T21846C,T22200G,C22673T,A22688G,G22775A,A22786C,A24130C,C26060T,C26858T,G27382C,A27383T,T27384C) BA.2+T2228C+C22792T into one [big branch](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21fa1_41f350.json?c=userOrOld&label=nuc%20mutations:T2228C) and numerous smaller ones; I took a look at a few of the small ones and they either contain sequences with the insertion or share other mutations with some sequences on the big branch. So it looks like most of BA.2+T2228C+C22792T ([cov-spectrum](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=BA.2*+%26+C22792T+%26+T2228C+%26+%21ORF3a%3AH78Y&)) is likely to be this lineage. There are a couple of BA.2.9+T2228C+C22792T which I've excluded from the query.

The cov-spectrum query gives 190 sequences from over a dozen countries, including Italy (49), Denmark (34), UK (24), France (23), USA (20), Germany (14). The first sequence is from Italy (2022-02-16) and the lineage is most prevalent there, making up about 2% of the most recent sequences (Italy sequences much less than the other countries listed above).

Numbers are small and error bars are large but there is an apparent growth advantage over a BA.2* baseline in Italy.
<img width="613" alt="Italy_ins247" src="https://user-images.githubusercontent.com/42699509/168922600-cdad2d96-9984-44d1-a1df-a3ca2916472a.png">

**In addition to the T2228C lineage, the exact same 9nt insertion occurs in:
- A BA.2 sublineage with T28160C+T12013A (~36 seq, mainly Northern Ireland)
- A BA.2.9 sublineage with C28435T+C7471T+T14384G (~9 seq, Germany, Italy, Denmark)

**Comment by amniewiadomska** [comment]
I was just looking to see if anyone had posted this before I opened an issue! 
I had found a few in NY, and decided to look for more. 
Very curious insertion as it also looks like it occurred in Delta (AY.4) in late 2021 in Wales. 

Definitely a region that may be under immune selection. 

Attached EPI_ISL IDs for the BA.2 ones I found. 
[spike_ins248GEN_EPI_ids.txt](https://github.com/cov-lineages/pango-designation/files/8712126/spike_ins248GEN_EPI_ids.txt)

**Comment by FedeGueli** [comment]
Hi @silcn! thanks a lot for looking at this!
I was noticing just yesterday (with the wonderful simple tool build by @corneliusroemer :
https://mutation-spotter.vercel.app/
![chrome_screenshot_1652856746765](https://user-images.githubusercontent.com/87669813/168976074-84c875cf-fa75-4dc5-8607-06f364d802db.png)
)
that Italy has a growing prevalence of S:248N  but i wont ever have thought it was an insertion!
👍

**Comment by FedeGueli** [comment]
I asked Emanuele Andreano his view on this insertion and very kindly he answered me on twitter.
Here and in the 3d below his thoughts on this sublineage:
https://twitter.com/e_andreano/status/1527166032896528387?s=20&t=MOXIGH475-QADF_YRbuv9Q

**Comment by FedeGueli** [comment]
287 seqs as today

**Comment by FedeGueli** [comment]
@54mu @marcogerdol have you seen this italian sublineage with a Spike insertio  at 247?
It has reached 7% as share of total sequences in Italy last week.

@corneliusroemer @chrisruis @AngieHinrichs 
This fully deserves a designation

287 seqs today 7% and growing prevalence in Italy (despite BA.4/5 being 5% in the last week here)

**Comment by FedeGueli** [comment]
Thx @marcogerdol ! my fears come from possible recombination with BA.4 BA.5 given the cocirculation Italy will experience for.a while in a no npi context (even if masks are still up for many) happy that italian scientists as you are on it, as mentioned in the issue keep in mind that Andreano and Rappuoli saw this kind of insertion emerging in vitro and they are the only ones to fully understand what this ins can mean  about spike conformation .
I hope no further studies will be required but in the case i can make contact between all of you.

**Comment by FedeGueli** [comment]
334 sequences as today.

by the way @silcn i monitored since the other two sublineages with the same insertion you mentioned above:
the one from Germany is stale at 10seqs, while the northern irish one reached 46seqs do not know if you would like to propose the latter, still very small but circulating.

**Comment by FedeGueli** [comment]
Agree, i dont think.the most of the late spotted sublineages have chance to survive or to not being outcompeted by the three dominant variants. But they could be picked up by recombination especially the ones with muts in ntd.
So it is worth to keep them monitored.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.52 with 239 newly designated sequences, and 1 updated designations from BA.2. Defining mutation(s) nt:T2228C (ORF1a:C655R).
