### ISSUE TITLE
Sublineage of B.1.351 spreading rapidly in Bangladesh

### ISSUE THREAD

**Issue by mkedwards** [cov-lineages/pango-designation#65]
## New lineage proposal
by Michael K. Edwards <m.k.edwards@gmail.com>

### Description
Sub-lineage of: B.1.351
Earliest sequence: collected 2021-02-27
Most recent sequence: common in Bangladesh and Singapore (as of late April, latest nextstrain.org update)
Countries circulating: Bangladesh, Singapore, Australia, Greece, Italy; spotted in South Korea, Portugal, Switzerland, Ireland

There's a B.1.351 subclade in Bangladesh/Singapore/Australia (and now found in Europe) that I think bears watching.  It appears to be the product of a substantial evolutionary sprint on top of B.1.351 followed by rapid spread (see Nextclade screenshot, with divergence branch length).  It's concerning because it's spreading at a B.1.1.7-like rate, which B.1.351 has not previously been seen to do in places where both have gotten a foothold.  This is not far from the founding event:

GISAID EPI ISL 1563631
E: P71L
N: T205I
ORF1a: T265I, K1655N, P2046L, N2596S, K3353R, S3675-, G3676-, F3677-
ORF1b: P314L, I1074V
ORF3a: Q57H, S171L
S: L18F, D80A, D215G, L241-, L242-, A243-, K417N, E484K, N501Y, D614G, A701V

ORF1a K1655N (B.1.351) + P2046L looks like a reliable signature.  https://nextstrain.org/ncov/asia?c=gt-ORF1a_2046,1655,1001,2230&gmin=15&l=unrooted&m=div&p=full&tl=country

### Genomes
I don't know how to get nextstrain.org to dump a CSV.  https://nextstrain.org/ncov/asia?c=gt-ORF1a_1001,3353,2046,3646&f_region=Asia&label=clade:20H/501Y.V2&m=div&p=full&tl=country will show this clade as T/R/L/T.

### Evidence
<img width="1209" alt="Screen Shot 2021-04-28 at 7 57 03 AM" src="https://user-images.githubusercontent.com/843186/116426123-b035ab00-a7f7-11eb-8ad4-450a3fbaae75.png">

### Proposed lineage name
B.1.351.1

**Comment by AngieHinrichs** [comment]
> I don't know how to get nextstrain.org to dump a CSV.

@mkedwards Here's how.

1. Click on your branch of interest (the T/R/L/T green branch)
2. Scroll to the bottom of the page
3. Click on the "DOWNLOAD DATA" link
4. Click on "METADATA (TSV)"

That downloads a file with a name like nextstrain_ncov_asia_metadata.tsv .

**Comment by chrisruis** [comment]
Thanks @mkedwards for submitting this. We've added this as lineage B.1.351.3 containing 100 sequence designations in [1.1.28](https://github.com/cov-lineages/pango-designation/releases/tag/1.1.28) (B.1.351.1 and B.1.351.2 are already existing lineages so this one got the next available B.1.351 sublineage)
