### ISSUE TITLE
BA.2.X sublineage with S:Y449N and N:T135I with circulation in Denmark (0.3%)  and Peru (7.5%)

### ISSUE THREAD

**Issue by OrsonMM** [cov-lineages/pango-designation#651]
Possible Omicron BA.2.X with S: Y449N and N: T135I present in Denmark and Peru with probably growing, in the UK is low growing.

Reports: 

Denmark 58
United Kingdom 27
Sweden 7
Peru 6
Germany 6
Italy 2
France 2
Portugal 2
Ecuador 1
Ireland 1
Norway 1
USA 1

First report:
hCoV-19/France/CVL-ChuTo-267415/2021 (EPI_ISL_11125403)  date 2021-03-12

Last report: 
hCoV-19/England/LSPA-3E0E86D/2022 (EPI_ISL_12723225) date 2022-11-05

Evidence:

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14adc_3ff830.json?c=country&label=nuc%20mutations:C8605T,T22907A,T25306C,C28677T 

Genomes:

[BA.2.X.txt](https://github.com/cov-lineages/pango-designation/files/8721211/BA.2.X.txt)

CovSpectrum 

![Dinamarca_1](https://user-images.githubusercontent.com/12600107/169164426-1aefa14e-2c9f-4c3d-a25a-04b377165a93.PNG)

![Dinamarca_2](https://user-images.githubusercontent.com/12600107/169164440-2bb040d9-b75f-4d53-a806-55d6cc56206c.PNG)

![Peru_1](https://user-images.githubusercontent.com/12600107/169164449-094dba24-adb4-4220-966d-dca43ba4db67.PNG)

**Comment by OrsonMM** [comment]
Recent sequences of Denmark:

EPI_ISL_12780435	2022-05-12	Denmark
EPI_ISL_12780476	2022-05-10	Denmark
EPI_ISL_12780542	2022-05-12	Denmark
EPI_ISL_12780572	2022-05-10	Denmark
EPI_ISL_12780590	2022-05-11	Denmark
EPI_ISL_12780642	2022-05-14	Denmark
EPI_ISL_12780666	2022-05-10	Denmark
EPI_ISL_12780823	2022-05-12	Denmark
EPI_ISL_12780951	2022-05-14	Denmark
EPI_ISL_12781187	2022-05-12	Denmark
EPI_ISL_12781210	2022-05-14	Denmark
EPI_ISL_12781459	2022-05-10	Denmark
EPI_ISL_12781648	2022-05-11	Denmark
EPI_ISL_12781660	2022-05-14	Denmark
EPI_ISL_12781782	2022-05-11	Denmark
EPI_ISL_12781883	2022-04-05	Ireland
EPI_ISL_12782138	2022-05-11	Denmark
EPI_ISL_12782170	2022-05-10	Denmark
EPI_ISL_12782183	2022-05-10	Denmark
EPI_ISL_12782282	2022-05-12	Denmark
EPI_ISL_12782284	2022-05-10	Denmark

**Comment by OrsonMM** [comment]
![denmarck](https://user-images.githubusercontent.com/12600107/170738622-f5c1c7d6-7077-4499-aa16-0b6825b8f165.png)

**Comment by OrsonMM** [comment]
Genomes from Peru

EPI_ISL_12960962
EPI_ISL_12960963
EPI_ISL_12961088
EPI_ISL_12961091

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.53 with 142 newly designated sequences, and 3 updated designations from BA.2. Defining mutation(s) C8605T, T22907A (S:Y449N),T25306C, C28677T (N:T135I).

**Comment by Vjimenez-vasquez** [comment]
Excelent observation !!!
