### ISSUE TITLE
BA.5 sublineage with S:V1230A, ORF1a:P2685S and C2338T (12 seq. c 16 % of Austrian BA.5)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#652]
Proposal for a sublineage of BA.5

Earliest sequence: 5/01/2022 (Austria)
Countries detected:  Austria
Defining mutations:
T25251C = S:V1230A
C8318T = ORF1a:P2685S
C2338T
(A28254-)

The combination of mutations (S:V1230A, ORF1a:P2685S, C2338T and an apparent deletion at 28254) has apparently not yet been observed in BA.5 sequences outside of Austria, they might have been acquired after the initial introduction of BA.5.  This cluster of sequences currently represents c. 16 % of all Austrian BA.5 genomes (12/74).

![pic2](https://user-images.githubusercontent.com/102166254/169246801-f074b332-4f56-4453-9019-45b9ce9c29b6.PNG)
![pic1](https://user-images.githubusercontent.com/102166254/169246829-9c02fba7-94b3-4a4e-b230-6071755ebd20.PNG)
![pic3](https://user-images.githubusercontent.com/102166254/169246839-ad86c143-1baa-4cdd-abb7-892c98410263.PNG)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_145aa_5e9d80.json?branchLabel=Spike%20mutations&c=gt-S_1230&label=nuc%20mutations:C2790T,C10198T,A29510C

EPI_ISL_12703375
EPI_ISL_12751768
EPI_ISL_12751769
EPI_ISL_12751770
EPI_ISL_12751771
EPI_ISL_12751772
EPI_ISL_12751773
EPI_ISL_12751774
EPI_ISL_12751775
EPI_ISL_12751776
EPI_ISL_12751777
EPI_ISL_12751778

**Comment by InfrPopGen** [comment]
This lineage has continued to show signs of inactivity over the past three weeks, and so it doesn't meet the requirements for a designation. Please feel free to alert us should the situation change and a clear epidemiological event become apparent. Thank you again for monitoring and proposing lineages.
