### ISSUE TITLE
Sublineage of BA.2 + C26882T + 6196T with S:356R (321 seqs) circulating in UK - England

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#654]
Thanks to @corneliusroemer who highlighted me this mutation, i was monitoring S:356R since last month.
We have learned to know  S:356R already with AY.43.4 an apparently high trasmissible Delta sublineage emerged in Switzerland and discovered by Cornelius last year.
As many other emerging spike mutations we are seeing in BA.2 (S:64R,68T,157T,176F,212S,248S/H/N,255F,417T,452X,1153Y) it has emerged convergently in distinct sublineages.
Here i want to propose the first of them:

Sublineage of BA.2 with C26882T, C6196T, S:K356R 
Usher tree:
![Schermata 2022-05-19 alle 17 10 06](https://user-images.githubusercontent.com/87669813/169330091-164e3f49-c244-4aa8-b6de-fefe6855e24c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d04d_658400.json?branchLabel=aa%20mutations&c=gt-nuc_6196,26882&label=nuc%20mutations:C26882T

Sequences: 288
List: [contributors.csv](https://github.com/cov-lineages/pango-designation/files/8730601/contributors.csv)
First sequence : 8/2022 
Country: mainly UK
[Cov-Spectrum overview](https://cov-spectrum.org/explore/World/AllSamples/from=2022-01-01&to=2022-05-19/variants?aaMutations=S%3AK356R&nucMutations=C26882T%2CC6196T&)

Growth Advantage:
![Schermata 2022-05-19 alle 17 18 17](https://user-images.githubusercontent.com/87669813/169333152-b772b690-4ac8-4720-b57e-31b9bdf2a126.png)

**Comment by chrisruis** [comment]
Thanks @FedeGueli This seems to have plateaued at quite a low proportion of UK BA.2 sequences ([covSpectrum query](https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/from=2022-01-01&to=2022-06-13/variants?pangoLineage=BA.2*&aaMutations1=S%3A356R&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&)) so I'll close this for now but we can reopen if it shows consistent growth in the future
