### ISSUE TITLE
BA.2.23 + C2338T sublineage with double spike mutations S:K356R and S:A845G, growing fast in Scotland (51seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#655]
As already said for #654 S:K356R is an emerging mutation in BA.2 sublineages spotted first by @corneliusroemer .

Here i want to put under your radar a little sublineage of BA.2.23 with S:K356R and S:A845S ,
It is just 50+ sequences but it shows a large growth advantage vs parental BA.2.23 that was already slighty more transmissible than BA.2 baseline.

[Usher tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1dfc5_658870.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22629G)

![Schermata 2022-05-19 alle 23 30 16](https://user-images.githubusercontent.com/87669813/169407906-5269d7a0-e29a-467e-9aca-4b1065cd4680.png)

Nr. of sequences: 51
List of sequences:
[contributors (2).csv](https://github.com/cov-lineages/pango-designation/files/8734343/contributors.2.csv)
Country: Scotland

[Cov-Spectrum overview](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AK356R%2CS%3AA845G&pangoLineage=BA.2*&aaMutations1=S%3A356R%2CS%3A845G&pangoLineage1=BA.2.23*&)

[Growth advantage](https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past6M/variants?nucMutations=2338T&pangoLineage=BA.2.23*&aaMutations1=S%3A356R%2CS%3A845G&nucMutations1=2338T&pangoLineage1=BA.2.23*&analysisMode=CompareToBaseline&) vs BA.2.23 + 2338T baseline in Scotland:
![Schermata 2022-05-19 alle 23 33 24](https://user-images.githubusercontent.com/87669813/169408429-84797f75-28fb-4d33-b67b-162f8817a525.png)

Obviously it can be just  a cluster and nothing more , but i still think it is worth monitoring it publicly together.

**Comment by chrisruis** [comment]
As with #654, this seems to have plateaued at quite a low proportion of UK BA.2 sequences ([covSpectrum query](https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/from=2022-01-01&to=2022-06-13/variants?pangoLineage=BA.2*&aaMutations1=S%3A356R%2CS%3A845G&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&)) so I'll close this for now but we can reopen if it shows consistent growth in the future
