### ISSUE TITLE
BA.5 sublineage with S:T76I circulating in the USA (544 seq. c 57 % of USA and c. 10 % of global BA.5 as of 06.06.22)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#656]
Proposal for a sublineage of BA.5

Earliest sequence: 2022-03-22 South Africa)
Countries detected:  South Africa (2), USA (99), United Kingdom (1), France (1), Mexico (1)

Defining mutations:
C21789T = S:T76I

This variant defined by S:T76I was first detected in South Africa but has managed to spread to multiple other countries (USA, Mexico, UK and France). Within the USA it is currently the dominant BA.5 variant (c. 66%, 104/158 GISAID) and was detected in 23 states (Michigan, Oklahoma, Missouri, North Carolina, Mississippi, Illinois, Tennessee, Florida, Maryland, Kansas, Virginia, Minnesota, New York, Texas, Indiana, Nevada, Arizona, Wisconsin, New Jersey, California, Massachusetts, Nebraska, Utah).

The variant is apparently distinct from variants defined by N:E136D ([#550](https://github.com/cov-lineages/pango-designation/issues/550)), ORF1ab:Q556K ([#550](https://github.com/cov-lineages/pango-designation/issues/550)), Orf9b:D16G (#551), ORF10:L37F ([#621](https://github.com/cov-lineages/pango-designation/issues/550)), ORF1b:M1156I (#625) and S:V1230A, ORF1a:P2685S, C2338T (#652).

![ST76I](https://user-images.githubusercontent.com/102166254/169496757-fc1cd64c-f111-4540-b5f8-6bbb245dc301.PNG)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1810d_7450e0.json?branchLabel=aa%20mutations&c=gt-S_76&label=nuc%20mutations:C27889T

![growth](https://user-images.githubusercontent.com/102166254/169496847-cc30073d-1dc8-4f0c-a99d-321ce17b2670.PNG)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.5*&nucMutations1=C21789T&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

EPI_ISL_12097383, EPI_ISL_12112497, EPI_ISL_12113187, EPI_ISL_12114808, EPI_ISL_12224559, EPI_ISL_12540781, EPI_ISL_12543177, EPI_ISL_12559430, EPI_ISL_12563943, EPI_ISL_12620608, EPI_ISL_12620609, EPI_ISL_12620611, EPI_ISL_12620614, EPI_ISL_12620642, EPI_ISL_12620786, EPI_ISL_12620815, EPI_ISL_12620848, EPI_ISL_12621507, EPI_ISL_12638367, EPI_ISL_12638474, EPI_ISL_12641024, EPI_ISL_12643339, EPI_ISL_12655363, EPI_ISL_12655572, EPI_ISL_12655967, EPI_ISL_12657356, EPI_ISL_12658243, EPI_ISL_12659704, EPI_ISL_12665900, EPI_ISL_12690265, EPI_ISL_12698536, EPI_ISL_12708520, EPI_ISL_12709998, EPI_ISL_12710101, EPI_ISL_12710289, EPI_ISL_12710341, EPI_ISL_12711398, EPI_ISL_12712581, EPI_ISL_12719505, EPI_ISL_12722041, EPI_ISL_12740113, EPI_ISL_12740114, EPI_ISL_12740115, EPI_ISL_12740584, EPI_ISL_12744893, EPI_ISL_12744934, EPI_ISL_12744946, EPI_ISL_12744961, EPI_ISL_12744963, EPI_ISL_12744972, EPI_ISL_12744973, EPI_ISL_12744976, EPI_ISL_12745521, EPI_ISL_12745825, EPI_ISL_12745838, EPI_ISL_12746481, EPI_ISL_12746482, EPI_ISL_12746489, EPI_ISL_12746523, EPI_ISL_12746542, EPI_ISL_12746782, EPI_ISL_12746793, EPI_ISL_12746805, EPI_ISL_12746848, EPI_ISL_12746852, EPI_ISL_12746856, EPI_ISL_12746857, EPI_ISL_12746868, EPI_ISL_12754988, EPI_ISL_12756479, EPI_ISL_12756509, EPI_ISL_12757004, EPI_ISL_12759291, EPI_ISL_12761105, EPI_ISL_12763155, EPI_ISL_12764470, EPI_ISL_12766923, EPI_ISL_12766924, EPI_ISL_12767972, EPI_ISL_12768066, EPI_ISL_12768609, EPI_ISL_12768683, EPI_ISL_12769000, EPI_ISL_12769001, EPI_ISL_12769012, EPI_ISL_12769032, EPI_ISL_12770167, EPI_ISL_12770226, EPI_ISL_12770250, EPI_ISL_12785961, EPI_ISL_12786249, EPI_ISL_12786635, EPI_ISL_12786859, EPI_ISL_12788711, EPI_ISL_12788971, EPI_ISL_12789519, EPI_ISL_12789927, EPI_ISL_12790542, EPI_ISL_12799987, EPI_ISL_12800072, EPI_ISL_12800128, EPI_ISL_12803446, EPI_ISL_12803592, EPI_ISL_12807966

**Comment by agamedilab** [comment]
Growth advantage of BA.5* + S:T76I versus BA.5* as of 28.05.22:

![vsBA5](https://user-images.githubusercontent.com/102166254/170817821-7028ba72-b8ee-465e-a07a-1fd2ecc1c5db.PNG)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.5*&aaMutations1=S%3AT76I&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

Substitutions of descending nodes:

![ST76I_clade](https://user-images.githubusercontent.com/102166254/170818134-ae139693-cb6d-4d45-a8b3-8ee1a55d7f4f.PNG)

**Comment by FedeGueli** [comment]
@agamedilab restricting to last 3 months in Usa the growth advantage vs BA.5 isnt so clear , probably it will be much better in the next two weeks

**Comment by agamedilab** [comment]
@FedeGueli currently covspectrum counts 359 BA.5 genomes in the USA of which c. 60 % carry S:T76I: So there might be really too few non S:T76I genomes in the US to effectively compare them?

However globally the BA.5 + S:T76I variant shows advantage versus BA.5* including any of the major accepted and proposed BA.5 subvariant (see also pic in #657 for major clades):

BA.5 + S:T76I versus BA.5.1 (BA.5 +ORF10:L37F):

![111](https://user-images.githubusercontent.com/102166254/170861231-103c0006-e2cd-49e9-b732-1d3972fa738a.PNG)


https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C29666T&pangoLineage=BA.5*&aaMutations1=S%3AT76I&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

BA.5 + S:T76I versus BA.5.2 (BA.5 +ORF9B:D16G):


![222](https://user-images.githubusercontent.com/102166254/170861224-59f6d178-b54e-494a-8efa-ecf1e718ae67.PNG)


https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF9B%3AD16G&pangoLineage=BA.5*&aaMutations1=S%3AT76I&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

BA.5 + S:T76I versus BA.5 +N:E136D:

![vs5G28681T](https://user-images.githubusercontent.com/102166254/170860954-bf24972f-3efd-4b80-9b18-0ed85337ab26.PNG)


https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=G28681T&pangoLineage=BA.5&aaMutations1=S%3AT76I&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

BA.5 + S:T76I versus BA.5 +N:E136D, ORF1ab:Q556K:


![vs5G28681TC1931A](https://user-images.githubusercontent.com/102166254/170861073-9a5acfd2-92f5-4026-978a-379d2d08d565.PNG)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nucMutations=G28681T%2CC1931A&pangoLineage=BA.5&aaMutations1=S%3AT76I&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

BA.5 + S:T76I versus BA.5 ORF1ab:Q556K:

![vs5C1931A](https://user-images.githubusercontent.com/102166254/170861148-03424842-24c4-4db7-8900-267f28d583a7.PNG)


https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nucMutations=C1931A&pangoLineage=BA.5&aaMutations1=S%3AT76I&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

**Comment by silcn** [comment]
Hmmm... @agamedilab I don't think that's it. You can compare BA.5-with-S:76I to BA.5-without-76I using advanced search, and that doesn't show a growth advantage in the US. (note I expanded the search to include most of the BA.5 that's misclassified as BA.2)

<img width="620" alt="BA5_76I_US" src="https://user-images.githubusercontent.com/42699509/171169558-127afc3a-46d9-4479-94dd-f8b183e53a20.png">

[https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=%28BA.5*+%7C+%28BA.2*+%26+12160A+%26+9866C+%26+27259A%29%29+%26+%21S%3A76I&variantQuery1=%28BA.5*+%7C+%28BA.2*+%26+12160A+%26+9866C+%26+27259A%29%29+%26+S%3A76I&analysisMode=CompareToBaseline&](https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=%28BA.5*+%7C+%28BA.2*+%26+12160A+%26+9866C+%26+27259A%29%29+%26+%21S%3A76I&variantQuery1=%28BA.5*+%7C+%28BA.2*+%26+12160A+%26+9866C+%26+27259A%29%29+%26+S%3A76I&analysisMode=CompareToBaseline&)

Whereas it shows a 42% advantage worldwide. I agree with @FedeGueli that this could be misleading. Worldwide growth advantages often are, as they can be thrown off by differences in sequencing volume between countries.

**Comment by FedeGueli** [comment]
485 sequences as today. 
This branch of BA.5 is clearly circulating and growing in USA but it has been seeded also outside United States
and it is the only one of the 5 big BA.5 branches (.1 .2 .3 C1627T and this one) defined by a spike mutation.

**Comment by agamedilab** [comment]
On GISAID it has already 544 sequences total representing c. 57 % of US BA.5 (544/956) and c. 10 % of global BA.5 (544/5462) as of 06.06.2022.

![grafik](https://user-images.githubusercontent.com/102166254/172118896-a948cf44-bd12-4d10-a251-2c4d8a5913db.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.5 with 137 newly designated sequences, and 8 updated designations from BA.5. Defining mutation(s) C21789T (S:T76I).
