### ISSUE TITLE
Sublineage of BA.2 + C3874T that acquired S:1202Q  and then S:248S (149 seqs) circulating in Germany, Spain

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#658]
Here i want to propose a small but growing european sublineage of BA.2 with a double mutation in the spike protein.
It arose from the branch carrying C3874T (581+ seqs, first sequence Wales beginning of February)
then acquired 25166C = S:1202Q (178seqs, first sequences from Spain representing these mutations likely the introduction/emergence in the country, late February ) with 19017T and then A22305C = S:248S (77seqs), first sequences again from Spain at the beginning of March).
![Schermata 2022-05-20 alle 21 58 52](https://user-images.githubusercontent.com/87669813/169605419-faefadca-c196-4a02-a48c-198eb612823f.png)

Interestingly S:1202Q is defining mutation (together with S:371Y) of the newly designated BA.2.43 from #612 
and S:248S is the defining mutation of the proposed lineage in #634 that in my list (compiled using cov-spectrum  comparison vs baseline tool) is the most transmissible undesignated BA.2 sublineage .

Here the [Usher tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43293_7f1610.json?branchLabel=aa%20mutations&c=gt-nuc_3874,19017&label=nuc%20mutations:C3874T) for this sublineage.

Nr of sequences : 177
First Country: Spain
Countries: Spain, Germany (where it acquired furthera  NSP14 substitution Orf1b:L1681F- 61 seqs )
Sequence list:
[contributors (6).csv](https://github.com/cov-lineages/pango-designation/files/8743923/contributors.6.csv)
[Cov-Spectrum overview](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A1202Q&nucMutations=C3874T&pangoLineage=BA.2*&)
![Schermata 2022-05-20 alle 22 34 02](https://user-images.githubusercontent.com/87669813/169606555-be634779-1994-4307-9116-266fb61356e0.png)

[Growth advantages](https://cov-spectrum.org/explore/Europe/AllSamples/Past2M/variants?aaMutations=S%3A1202Q&nucMutations=C3874T&pangoLineage=BA.2*&aaMutations1=S%3A1202Q%2CS%3A248S&nucMutations1=C3874T&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&) seems solid, albeit early to say how much it seems clearly to be related to S:248S as expected :
![Schermata 2022-05-20 alle 22 40 17](https://user-images.githubusercontent.com/87669813/169607686-717eb0a0-797f-4e9b-ae10-f60ea902b26d.png)

Edited: i failed to mention i found this one using the new @corneliusroemer  simple but useful tool: 
https://mutation-spotter.vercel.app/
and to thank @olias120676 for the precious help in finding and monitoring emerging mutations like this one and others.

**Comment by FedeGueli** [comment]
@corneliusroemer @chrisruis the growth advantage of the final branch with S:248S seems solid and not slight, 
the sublineage with S:248S+S:1202Q reached 95 sequences today from 77 two days ago.
In my view after checking that its growth advantage is dependent to S:248S maybe it is worth designating deeper in the tree starting directly with S:248S

**Comment by FedeGueli** [comment]
113 seqs as today

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.54 with 135 newly designated sequences, and 1 updated designations from BA.2. Defining mutation(s) A22305C (S:Y248S).
