### ISSUE TITLE
B.1.1.316 and S:E484K

### ISSUE THREAD

**Issue by peich69** [cov-lineages/pango-designation#66]
Hi,
Some days ago we use PangoLEARN (v.2021-04-21) to classify some fasta files and we retrieve the lineage B.1.1.316.
Looking at the documentation https://cov-lineages.org/lineages/lineage_B.1.1.316.html in the “Description” field says “International lineage with E484K mutation”.
Our sequence doesn’t have the S:E484K variant. Trying to understand why it happened, I’ve found two closed issues #17, #18.
Considering these issues, lineage R.1 and R.2 have S:E484K.
So, all of three lineages, B.1.1.316, R1 and R2 should have the S:E484K.
I can't understand why my sequence is assigned to this lineage if is lacking that variant.
Moreover, I have download the 763 sequences assigned to B.1.1.316 at GISAID and only one has the S:E484K variation.
I would appreciate any comment that helps me to understand what I'm doing wrong.
Thanks

**Comment by aineniamh** [comment]
Thanks for your patience with this, I've checked and you're indeed right that the parent lineage B.1.1.316 doesn't appear to have E484K as a defining feature of the lineage. 

The following figure shows two B.1.1.316 sequences that have been designated and one each of their sublineages R.1 and R.2. At site 23012, both R.1 and R.2 have the G->A mutation, which causes the E484K amino acid change in the spike protein. 
![snp_plot](https://user-images.githubusercontent.com/11678307/116994167-46724100-acd0-11eb-83fa-889cfe4e64eb.png)

Looking back over the issues on this repository it seems that the description of [R.2](https://github.com/cov-lineages/pango-designation/issues/18) and [R.1](https://github.com/cov-lineages/pango-designation/issues/17) both describe E484K mutations, from within the diversity of B.1.1.136. 

B.1.1.136 itself doesn't have E484K as defining, but as it includes lineages R.1 and R.2 the description reflects that some sequences have this mutation. I recognise that this isn't clear though, and have amended the description in the designation file to explicitly say the child lineages R.1 and R.2 have this mutation in commit https://github.com/cov-lineages/pango-designation/commit/33435a88a429735f39984ed8d390bbe4dd09a8ef.

 Thanks for pointing this out!

**Comment by peich69** [comment]
Thanks you for your work

**Comment by aineniamh** [comment]
No worries, sorry for the delay!
