### ISSUE TITLE
BA.1 sublineage with T6001C and S mutations: S:E96D, S:L167T, S:R346T, S:L455W, S:K458M, S:E484V, S:H681R, S:P688V, detected in New York, USA

### ISSUE THREAD

**Issue by asigore** [cov-lineages/pango-designation#663]
### New Pango lineage proposal
by The Mount Sinai Pathogen Surveillance Program (MSHSPSP): Ana S. Gonzalez-Reiche, Hala Alshammary, Sarah Schaefer, Gopi Patel, Jose Polanco, Angela A. Amoako, Aria Rooker, Christian Cognigni, Daniel Floda, Adriana van de Guchte, Zain Khalil, Keith Farrugia, Nima Assad, Jian Zhang, Bremy Alburquerque, Levy Sominsky, Komal Srivastava, Robert Sebra, Juan David Ramirez, Radhika Banu, Paras Shrestha, Alberto Paniz-Mondolfi, Emilia Mia Sordillo, Viviana Simon, Harm van Bakel. Icahn School of Medicine at Mount Sinai, New York, NY. USA
### Description
Sub-lineage of: BA.1\
\
Earliest sequence: 02-Feb-2022 (Index case)\
\
Most recent sequence: 02-May-2022\
\
Countries circulating: USA - New York\
\
This new sub-lineage contains a unique combination of amino acid substitutions within the spike Omicron BA.1 background (E96D, L167T, R346T, L455W, K458M, E484V, P681R, A688V). This sub-lineage emerged in a single host with prolonged SARS-CoV-2 (BA.1) infection acquiring 8 additional mutations across the spike N-terminal domain (NTD), the receptor binding domain (RBD), and cleavage site region (CSR). The new BA.1 sub-lineage transmitted to five independent cases, including two reported  in GISAID from a different surveillance effort (CDC, through LabCorp and Quest Diagnostics). A new lineage designation will facilitate identification of further community spread.\
\
Please note that a preprint with more details has been submitted to [medRxiv.org](https://www.medrxiv.org) and should post soon.

### Genomes
[GISAID_accessions.txt](https://github.com/cov-lineages/pango-designation/files/8766610/GISAID_accessions.txt)
### Evidence
\
**Omicron tree (divergence)**
![Nextstrain tree](https://user-images.githubusercontent.com/30082968/170143199-85cafeb4-368a-4111-a71e-1f1ad704489d.png)\
\
**Lineage cluster (time-scaled)**
![Nextstrain subtree](https://user-images.githubusercontent.com/30082968/170142309-a0bf90ee-1f66-47af-bfd3-67fe03e745ad.png)\
\
**Proposed lineage name: BA.1.X**

**Comment by FedeGueli** [comment]
Great job! One of these sequences was flagged weeks ago by Neural Network Sequence Filter (NNSF) build by @bitbyte2015 , it was so odd that 
it was thought as likely contamination
and we werent able to track the further spread. 
Luckily you did! Thanks!

**Comment by hvbakel** [comment]
Preprint now available at: https://www.medrxiv.org/content/10.1101/2022.05.25.22275533v1

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.1.23 with 8 newly designated sequences, and 1 updated designations from BA.1. Defining mutation(s) G22599C (S:R346T), A22935T (S:K458M), C23013T (S:484V).
