### ISSUE TITLE
Potential BA.1*/BA.2* Recombinant with Likely Breakpoint at NSP3 or NSP4 (55 Seqs as of 2022-05-26 in US and Israel)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#664]
### Description
**Recombinant between**: BA.1* & BA.2*
**Earliest sequence**: 2022/2/12 (US-NH)
**Most recent sequence**: 2022/5/11 (US-NY)
**Countries circulating**: Israel, US (NH, MA, CT, NY, MD, CA, NJ)
**Likely breakpoint**: between 8393 and 9343 (NSP3 or NSP4).
**Mutations on branch**: A1610G (ORF1a:N449D), A19356G 

**Conserved Nuc mutations** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/170178138-71f8061e-14f0-420c-8222-a94f172a0123.png)

**Cov-spectrum query**: A1610G, A19356G, 4321C, 9344T, 29510C
**GISAID query**: N_S413R, NS3_T223I, NSP2_N269D, NSP3_K38R

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/170178309-be532474-2a64-45bd-aa49-a856183c49e5.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f65f_d98040.json?branchLabel=aa%20mutations&c=gt-nuc_19356&label=nuc%20mutations:T22792C

### Genomes:
EPI_ISL_10559785, EPI_ISL_11757808, EPI_ISL_11842557, EPI_ISL_11842611, EPI_ISL_11842669, EPI_ISL_11843061, EPI_ISL_11843211, EPI_ISL_11997753, EPI_ISL_12046486, EPI_ISL_12046591, EPI_ISL_12114108, EPI_ISL_12114128, EPI_ISL_12167574, EPI_ISL_12216690, EPI_ISL_12217259, EPI_ISL_12218037, EPI_ISL_12232168, EPI_ISL_12232406, EPI_ISL_12240696, EPI_ISL_12297233, EPI_ISL_12300212, EPI_ISL_12417120, EPI_ISL_12417250, EPI_ISL_12487892, EPI_ISL_12501101, EPI_ISL_12508967, EPI_ISL_12509089, EPI_ISL_12509578, EPI_ISL_12568639, EPI_ISL_12589007, EPI_ISL_12589201, EPI_ISL_12593036, EPI_ISL_12593621, EPI_ISL_12619626, EPI_ISL_12635842, EPI_ISL_12653320, EPI_ISL_12681940, EPI_ISL_12707653, EPI_ISL_12707985, EPI_ISL_12708226, EPI_ISL_12715181, EPI_ISL_12760459, EPI_ISL_12760560, EPI_ISL_12790380, EPI_ISL_12860936, EPI_ISL_12861179, EPI_ISL_12861235, EPI_ISL_12863894, EPI_ISL_12882575, EPI_ISL_12885258, EPI_ISL_12886569

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAA with 49 newly designated sequences, and 0 updated designations.
