### ISSUE TITLE
Potential BA.1*/BA.2* Recombinant with Likely Breakpoint at NSP3 (80 Seqs as of 2022-06-03 in Germany, Italy, Switzerland, France and Denmark)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#665]
### Description
**Recombinant between**: BA.1* & BA.2*
**Earliest sequence**: 2022/2/25 (Germany)
**Most recent sequence**: 2022/5/11 (Denmark)
**Countries circulating**: Germany, Italy, Switzerland, France and Denmark
**Likely breakpoint**: between 6516 and 8392 (NSP3)
**Mutations on branch**: C17010T

**Conserved Nuc mutations** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/170181323-06618c91-5fd0-4c05-bbc0-15b8903b7f1c.png)
**Cov-spectrum query**: A2832G, C3037T, T5386G, C9344T, C17010T, A29510C, C22792T, C26060T, G670T, T4321C

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/170181459-e69172fd-152b-40e2-87c8-f0b9f3985d5c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_317e_d84da0.json?branchLabel=nuc%20mutations&c=gt-nuc_17010&label=nuc%20mutations:C2470T

### Genomes:
EPI_ISL_11300019, EPI_ISL_12196001, EPI_ISL_12196113, EPI_ISL_12196338, EPI_ISL_12132994, EPI_ISL_10933571, EPI_ISL_12014372, EPI_ISL_12335032, EPI_ISL_12360512, EPI_ISL_12357736, EPI_ISL_12368343, EPI_ISL_12369102, EPI_ISL_11825571, EPI_ISL_11964879, EPI_ISL_12019664, EPI_ISL_12020286, EPI_ISL_12020334, EPI_ISL_12040457, EPI_ISL_12040458, EPI_ISL_11642563, EPI_ISL_11663510, EPI_ISL_12527186, EPI_ISL_12526871, EPI_ISL_12523603, EPI_ISL_12522076, EPI_ISL_12518668, EPI_ISL_12518667, EPI_ISL_12518676, EPI_ISL_12518631, EPI_ISL_12515992, EPI_ISL_12669365, EPI_ISL_12669352, EPI_ISL_12669359, EPI_ISL_12670774, EPI_ISL_12671874, EPI_ISL_12672414, EPI_ISL_12674341, EPI_ISL_12675851, EPI_ISL_12676158, EPI_ISL_12677843, EPI_ISL_12735485, EPI_ISL_12750442, EPI_ISL_12758924, EPI_ISL_12821354, EPI_ISL_11821929, EPI_ISL_10920478, EPI_ISL_11673405, EPI_ISL_11676871, EPI_ISL_11965590, EPI_ISL_12017678, EPI_ISL_12019627, EPI_ISL_12185523, EPI_ISL_12196282, EPI_ISL_12195060, EPI_ISL_12196255, EPI_ISL_12317550, EPI_ISL_12346399, EPI_ISL_12346071, EPI_ISL_12354565, EPI_ISL_12358489, EPI_ISL_12360498, EPI_ISL_12368367, EPI_ISL_11478063, EPI_ISL_11465091, EPI_ISL_11467981, EPI_ISL_12318783, EPI_ISL_12346948

**Comment by c19850727** [comment]
80 sequences as of 2022-06-03.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAB with 81 newly designated sequences, and 0 updated designations.
