### ISSUE TITLE
BA.4.1 sublineage with S:I670V (102 seq., c. 5% of global BA.4)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#667]
Proposal for a sublineage of BA.4.1
Earliest sequence: 2022-02-25 (South Africa)
Countries detected:  USA, Botswana, South Africa, Canada, Israel, Germany, Austria, New Zealand, Denmark, Reunion
Defining mutations:
A23570G = S:I670V

This variant is apparently a subvariant of BA.4.1 and is defined by A23570G = S:I670V. It was first detected in South Africa but has managed to spread to 9 other countries. Currently it forms a major subclade of BA.4.1 representing c. 5% (102/2080) genomes.

S:I670V was mentioned alongside ORF3a:I37T by @[FedeGueli](https://github.com/FedeGueli).in an earlier BA.4 post (#548).

![pic1](https://user-images.githubusercontent.com/102166254/170264394-6a92f4f2-dafc-4abb-95db-ba8deddee611.PNG)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2da82_e0a460.json?branchLabel=aa%20mutations&c=gt-S_670&label=nuc%20mutations:T22917G

Descending nodes also contain ORF3a:I37T, ORF1ab:T2247I:

![pic2](https://user-images.githubusercontent.com/102166254/170265791-13b71696-2ae3-4111-8c7d-1e348d9253b2.PNG)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2da82_e0a460.json?branchLabel=aa%20mutations&c=gt-S_6

EPI_ISL_11999065, EPI_ISL_12006222, EPI_ISL_12012887, EPI_ISL_12013570, EPI_ISL_12043267, EPI_ISL_12043286, EPI_ISL_12097330, EPI_ISL_12243751, EPI_ISL_12243753, EPI_ISL_12243754, EPI_ISL_12273982, EPI_ISL_12274006, EPI_ISL_12274074, EPI_ISL_12307564, EPI_ISL_12307574, EPI_ISL_12307581, EPI_ISL_12307617, EPI_ISL_12307630, EPI_ISL_12307642, EPI_ISL_12307649, EPI_ISL_12307660, EPI_ISL_12307672, EPI_ISL_12307674, EPI_ISL_12307687, EPI_ISL_12307700, EPI_ISL_12307712, EPI_ISL_12307723, EPI_ISL_12401083, EPI_ISL_12401084, EPI_ISL_12401135, EPI_ISL_12401136, EPI_ISL_12426952, EPI_ISL_12456676, EPI_ISL_12456726, EPI_ISL_12456788, EPI_ISL_12466376, EPI_ISL_12472137, EPI_ISL_12473516, EPI_ISL_12473878, EPI_ISL_12474407, EPI_ISL_12474433, EPI_ISL_12474443, EPI_ISL_12474448, EPI_ISL_12476624, EPI_ISL_12477008, EPI_ISL_12477041, EPI_ISL_12518072, EPI_ISL_12520040, EPI_ISL_12520049, EPI_ISL_12520814, EPI_ISL_12523958, EPI_ISL_12534981, EPI_ISL_12535004, EPI_ISL_12546339, EPI_ISL_12558807, EPI_ISL_12558927, EPI_ISL_12559422, EPI_ISL_12568093, EPI_ISL_12576040, EPI_ISL_12576054, EPI_ISL_12585897, EPI_ISL_12587428, EPI_ISL_12587880, EPI_ISL_12587896, EPI_ISL_12607965, EPI_ISL_12607980, EPI_ISL_12636857, EPI_ISL_12651470, EPI_ISL_12652745, EPI_ISL_12652825, EPI_ISL_12673528, EPI_ISL_12673961, EPI_ISL_12677290, EPI_ISL_12689860, EPI_ISL_12689861, EPI_ISL_12694616, EPI_ISL_12699439, EPI_ISL_12705847, EPI_ISL_12705871, EPI_ISL_12705972, EPI_ISL_12713179, EPI_ISL_12713195, EPI_ISL_12730831, EPI_ISL_12733100, EPI_ISL_12733204, EPI_ISL_12733346, EPI_ISL_12737264, EPI_ISL_12738491, EPI_ISL_12738535, EPI_ISL_12749785, EPI_ISL_12751201, EPI_ISL_12751202, EPI_ISL_12751204, EPI_ISL_12751209, EPI_ISL_12751210, EPI_ISL_12763701, EPI_ISL_12763720, EPI_ISL_12763748, EPI_ISL_12763798, EPI_ISL_12763807, EPI_ISL_12765583, EPI_ISL_12765597, EPI_ISL_12765636, EPI_ISL_12765639, EPI_ISL_12811855, EPI_ISL_12819235, EPI_ISL_12827446, EPI_ISL_12827453, EPI_ISL_12828009, EPI_ISL_12828478, EPI_ISL_12844498, EPI_ISL_12844519, EPI_ISL_12845576, EPI_ISL_12856527, EPI_ISL_12856769, EPI_ISL_12859875

**Comment by FedeGueli** [comment]
@agamedilab thx for proposing this. 
I am monitoring it since the comment you mentioned (thx!) .
It is for sure relevant as share of total BA.4 but i didnt manage to see a clear growth advantage for it or better: lately this sublineage is showing a slight disadvantage vs BA.4 baseline maybe due to still undisclosed beneficial or slighty beneficial mutations in other sublineages (??). Still i think a designation is worth for two reason:
 1) the sooner and clearer the tree is designated in all its relevant branches the better than to analyze subvariants of interest (i m betting on BA.4/5 becoming dominant but this virus usually surprise us so take it as an assumption) 
2) possible recombination events which  likely will happen along the period of co-circulation between BA.2/BA.4-5

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.4.1.1 with 34 newly designated sequences, and 15 updated designations from BA.4.1. Defining mutation(s) A23570G (S:I670V).
