### ISSUE TITLE
Potential lineage BA.2,. plus  mutation in spike position L452M

### ISSUE THREAD

**Issue by VirologiaHUCA** [cov-lineages/pango-designation#668]
Description
Sub-lineage of: BA.2
Earliest sequence: 2022-02-13
Most recent sequence: 2022-05-12 
Countries circulating: Spain(24 Asturias), Belgium, Germany, India, Japan, Netherlands, Singapore,, Sweden, United Kingdom, USA

<written description of the proposed lineage, where it is circulating, when, why it is distinct>
initially majority clade in Asturias that gains the mutation L452M in gene S, classified like BA.2 by Pagolin assigner

Genomes
<list of genome names as found on GISAID or accession ids - provide as a CSV/TSV table attachment - include locations and dates of sampling>
EPI_ISL_10801688
EPI_ISL_11000832
EPI_ISL_11189816
EPI_ISL_11198322
EPI_ISL_11215369
EPI_ISL_11304143
EPI_ISL_11305991
EPI_ISL_11335587
EPI_ISL_11338729
EPI_ISL_11387452
EPI_ISL_11390137
EPI_ISL_11394906
EPI_ISL_11425931
EPI_ISL_11429408
EPI_ISL_11432929
EPI_ISL_11474143
EPI_ISL_11475374
EPI_ISL_11475446
EPI_ISL_11498853
EPI_ISL_11510273
EPI_ISL_11511940
EPI_ISL_11511985
EPI_ISL_11520796
EPI_ISL_11544188
EPI_ISL_11545168
EPI_ISL_11554945
EPI_ISL_11591104
EPI_ISL_11593368
EPI_ISL_11599228
EPI_ISL_11599252
EPI_ISL_11602259
EPI_ISL_11618416
EPI_ISL_11636217
EPI_ISL_11643094
EPI_ISL_11651482
EPI_ISL_11679582
EPI_ISL_11688597
EPI_ISL_11698611
EPI_ISL_11702678
EPI_ISL_11716349
EPI_ISL_11726768
EPI_ISL_11730714
EPI_ISL_11731632
EPI_ISL_11745876
EPI_ISL_11747099
EPI_ISL_11748106
EPI_ISL_11768813
EPI_ISL_11775477
EPI_ISL_11840614
EPI_ISL_11843808
EPI_ISL_11849719
EPI_ISL_11866409
EPI_ISL_11866450
EPI_ISL_11888952
EPI_ISL_11953561
EPI_ISL_11957351
EPI_ISL_12016868
EPI_ISL_12018874
EPI_ISL_12025542
EPI_ISL_12025552
EPI_ISL_12043863
EPI_ISL_12067631
EPI_ISL_12076335
EPI_ISL_12076338
EPI_ISL_12086778
EPI_ISL_12096624
EPI_ISL_12096660
EPI_ISL_12096823
EPI_ISL_12097710
EPI_ISL_12097818
EPI_ISL_12097841
EPI_ISL_12097889
EPI_ISL_12104016
EPI_ISL_12105400
EPI_ISL_12105765
EPI_ISL_12105912
EPI_ISL_12124234
EPI_ISL_12140638
EPI_ISL_12140856
EPI_ISL_12152172
EPI_ISL_12152225
EPI_ISL_12170688
EPI_ISL_12177854
EPI_ISL_12193712
EPI_ISL_12204061
EPI_ISL_12204602
EPI_ISL_12204611
EPI_ISL_12222636
EPI_ISL_12226676
EPI_ISL_12236342
EPI_ISL_12237713
EPI_ISL_12589407
EPI_ISL_12589410
EPI_ISL_12829095
EPI_ISL_12829096
EPI_ISL_12829097
EPI_ISL_12829098
EPI_ISL_12829099
EPI_ISL_12829100
EPI_ISL_12829101
EPI_ISL_12829102
EPI_ISL_12829103
EPI_ISL_12829104
EPI_ISL_12829105
EPI_ISL_12829106
EPI_ISL_12829107
EPI_ISL_12829108
EPI_ISL_12829109
EPI_ISL_12829110
EPI_ISL_12829111
EPI_ISL_12829112
EPI_ISL_12829113
EPI_ISL_12829114
EPI_ISL_12829115
EPI_ISL_12829120

Evidence
<image from phylogenetic tree?>
![Variante BA 2 452m](https://user-images.githubusercontent.com/105294581/170283948-3ac47123-4c02-4856-b664-a38e1689d678.gif)

**Comment by FedeGueli** [comment]
Hi @VirologiaHUCA, i was monitoring for a while a new S:L452M lineage circulating in Spain and other countries , showing a sustained growth advantage vs BA.2 baseline ( usually it is boosted at the beginning but this is specially high).
It belongs to the 22792T branch and further acquired S:L452M Orf1a:v627F, Orf1a:1640S
Usher put it in the BA.2.9 with Orf3a:79Y but apparently just 1/3 of them carries this mutation
and the spanish branch has Orf3a:78 reverted to H

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c8ce_e43170.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C22916A

[covspectrum](https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=orf1a%3Av627F%2Corf1a%3A1640S&pangoLineage=BA.2*&aaMutations1=orf1a%3Av627F%2Corf1a%3A1640S&pangoLineage1=BA.2*&)



Is it the same proposed here?


@corneliusroemer @AngieHinrichs @chrisruis if you spare time to look at this tree:

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3c8ce_e43170.json?branchLabel=aa%20mutations&c=gt-nuc_22792

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4181e_e44d50.json

**Comment by silcn** [comment]
[Usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_33d7f_e77000.json?c=userOrOld&label=nuc%20mutations:T670G,C2790T,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10198T,G10447A,C12880T,T15240C,C15714T,C17410T,C19955T,A20055G,C21618T,T21762C,T21846C,T22200G,C22673T,A22688G,G22775A,A22786C,A24130C,C26060T,C26858T,G27382C,A27383T,T27384C,A29510C) places @VirologiaHUCA's listed sequences in various different branches across BA.2 - indeed, some are BA.2.3 or BA.2.10 - but the Spanish ones [do cluster together](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33d7f_e76ff0.json?c=userOrOld&label=nuc%20mutations:C22916A) in a global branch with about 500 sequences that is defined by just plain BA.2 + S:L452M without any other mutations (in particular no C22792T so @FedeGueli's branch is different). Given how frequently L452M appears in BA.2, it's likely that this branch actually consists of multiple independent acquisitions of it, but there's no way to tell them apart.

**Comment by FedeGueli** [comment]
Thx @silcn very much. I was fooled by the same area of circulation of mine. Yeah i think @corneliusroemer did a mini sheet with all 452 sublineages in an issue ( i'll put here if i find that back) and then me too started to monitor them weekly , not much growth for them but for this one i mentioned above . I'll go to propose it to help distinguish the various L452M sublineages.  For

**Comment by VirologiaHUCA** [comment]
Thank you very much @silcn and @fedegueli for your comments. We believe that this variant could be circulating before our first strain was sequenced. But it was evident in a specific focus. Later we found very sporadically

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.56 with 487 newly designated sequences, and 9 updated designations from BA.2. Defining mutation(s) C22916A (S:L452M).
