### ISSUE TITLE
New CA-USA sublineage of B.1

### ISSUE THREAD

**Issue by milospjanic** [cov-lineages/pango-designation#67]
by
Milos Pjanic, 
Avellino Labs
1505 Adams Dr, Menlo Park, CA 94025
milos.pjanic@avellino.com

Description
Sub-lineage of: B.1
Earliest sequence: 03/17/21
Most recent sequence: 03/18/21
Countries circulating: CA-USA

<written description of the proposed lineage, where it is circulating, when, why it is distinct>

Reporting the observation of a potentially newly emerging variant wiyhin the pangolin lineage B.1.

There are so far 5 sequenced cases that are reported in North California US.

On the amino acid level it is distinguished from the currently circulating strains from 20C clade most prominently by the mutations in the Spike protein: Spike D614G, Spike E1111K, Spike K854N, Spike N501Y, Spike P681H, Spike S494P
 
Example mutations:
Spike D614G, Spike E1111K, Spike K854N, Spike N501Y, Spike P681H, Spike S494P, N M234I, NS3 Q57H, NSP2 T85I, NSP3 A1165V, NSP3 T1378P, NSP4 D259N, NSP4 T189I, NSP4 T439M, NSP6 H11Q, NSP9 P57S, NSP12 N743S, NSP12 P323L, NSP13 E319D

This new strain is located geographically in the San Mateo and San Joaquin counties in the Bay Area, North California.

Genomes
<list of genome names as found on GISAID or accession ids - provide as a CSV/TSV table attachment - include locations and dates of sampling>

EPI_ISL_1853453, EPI_ISL_1853470, EPI_ISL_1853565 
USA-CA, USA-CA, USA-CA
03/21, 03/21, 03/21

Evidence
<image from phylogenetic tree?>
![image](https://user-images.githubusercontent.com/12768624/117074665-7f1e1480-ace8-11eb-9e9e-4d8049fa298f.png)

Proposed lineage name
B.1.1.523

**Comment by AngieHinrichs** [comment]
Hi @milospjanic  -- this sounds a lot like the lineage proposed in issue #25.  Do you see any evidence of a deletion of 35 bases in ORF8?  (In NC_045512.2 reference genome coordinates, 27922-27956)

**Comment by milospjanic** [comment]
Hi @AngieHinrichs. We are setting up a PCR assay to confirm this deletion and will post update. 

Pangolin assigned only general B.1 lineage to these samples, and when clustered using UShER (https://hgwdev-angie.gi.ucsc.edu/cgi-bin/hgPhyloPlace) with CDC samples with the same Spike mutations (Spike:  D614G, E1111K, K854N, N501Y, P681H, S494P) they form a specific subcluster (in red).

![image](https://user-images.githubusercontent.com/12768624/117199864-b3f99c80-adb8-11eb-886d-3610f69edc24.png)

They are also subcluster with the highest number of mutations.

![image](https://user-images.githubusercontent.com/12768624/117200031-ef946680-adb8-11eb-9dc1-3975e6724ecb.png)

**Comment by milospjanic** [comment]
Considering the geographical proximity of the samples from this paper (Santa Cruz) 

https://www.biorxiv.org/content/10.1101/2021.04.05.438352v1

with ours (San Mateo, San Joaquin), they may be part of the same unassigned lineage

**Comment by AngieHinrichs** [comment]
Thanks for the updates @milospjanic and I'm glad to see you're using UShER!  (BTW hgwdev-angie is my development server and it's been quite unstable the past week as I've been experimenting with a new feature.  A more stable location is https://genome.ucsc.edu/cgi-bin/hgPhyloPlace -- and I just got a process in place to install the latest tree there daily.  Also, the default subtree size of 50 is pretty low and you can go a lot higher than that to see more closely and not-so-closely related sequences.)

Yes, your samples EPI_ISL_1853453, EPI_ISL_1853470, EPI_ISL_1853565 are definitely part of the lineage awaiting assignment in #25.  Although the lineage seems to have fizzled out in Santa Cruz where cases have been dropping (knock on wood), there have been a lot of recent cases in New York and Florida.

**Comment by AngieHinrichs** [comment]
Hi @milospjanic -- this lineage was designated B.1.623 in #25 last week.  The pangoLEARN model has not yet been retrained with the new lineage, so pangolin doesn't assign sequences to B.1.623 yet, but hopefully soon.
