### ISSUE TITLE
Sublineage of BA.2.9 with S:L452M Orf1a:V627F, Orf1a:1640S and Orf3a:78 reverted to H (70%) 425 sequences

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#671]
Here i want to propose a sublineage of BA.2 in the branch with 22792T defined by S:L452M Orf1a:V627F, Orf1a:1640S.

More precisely it likely belongs to BA.2.9 but when introduced in Spain it got defining mutation Orf3a:78Y reverted to H.
So de facto we have a two headed tree
Looking at the tree the S:G142D mutation is likely unreal and without that mutation this sublineage will be quite perfectly simmetric with a Spanish/ International branch with Orf3a:78H (reverted to WT) representing 70% of total sequences and another with Orf3a:78Y prevalent in Denmark representing a third of total sequences of this sublineage.
 I think it is impossible to prove whether if this happened for a naturally occuring reversion to Wt in the spanish clade or for recombination in the danish branch.
Tree: 
![Schermata 2022-05-25 alle 23 33 34](https://user-images.githubusercontent.com/87669813/170371675-b9fd352e-6849-405c-b7ed-61052451a4e8.png)
Link to Usher tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c8ce_e43170.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C5183T

Nr of Sequences:119
List of sequences:
[contributors (10).csv](https://github.com/cov-lineages/pango-designation/files/8774712/contributors.10.csv,
Countries: Spain, Denmark, Germany, Austria but already expoerted to US and UK.
![Schermata 2022-05-25 alle 23 49 45](https://user-images.githubusercontent.com/87669813/170373209-3ba7972b-1c8f-437e-9a32-f6ceab2f3f6f.png)

Growth Advantage vs BA.2 ( Being this one a very small sublineage be aware at the beginning of their spread clusters have an apparent boost in growth advantage that quite always does not correspond to the real one):
Denmark : 
![Schermata 2022-05-25 alle 23 45 37](https://user-images.githubusercontent.com/87669813/170372963-b4c2ab1b-c049-4439-bd2b-bedce9e5182f.png)
Spanish clade:
![Schermata 2022-05-25 alle 23 46 16](https://user-images.githubusercontent.com/87669813/170373022-75b12530-508c-4f19-9817-f29180ff7a23.png)

Check all the dwtails about this sublineage at [Cov-spectrum.og](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1a%3Av627F%2Corf1a%3A1640S&pangoLineage=BA.2*&aaMutations1=orf1a%3Av627F%2Corf1a%3A1640S%2CS%3AL452M&pangoLineage1=BA.2*&)

**Comment by AngieHinrichs** [comment]
> Looking at the tree the S:G142D mutation is likely unreal

Yes, in fact that should have been masked but I made an error recently which dropped the masking on some sequences.  I believe it's corrected in the latest tree.  Thanks for pointing that out!

**Comment by FedeGueli** [comment]
231 sequences as today

**Comment by FedeGueli** [comment]
275 seqs as  today. I leave this open due to the S:452M mutation of interest but it is very far from BA.5 in terms of trasmissibility. 
@chrisruis i'll check back at the end of this month to see if the down trend is confirmed and then i'll close it unless you prefer to get all the biggest 452X designated

**Comment by FedeGueli** [comment]
359 sequences as today
( https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_30e20_63b0e0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:T25624C )

Highlights:
1 Being already in 4 continents,
2 Having landed in low sequencing area as Argentina
3 steadily growing although in a not comparable way  vs BA.5 ( -31% weekly growth disadvantage) 
4 looking at growth rates of BA.2.74 (S:452M+ S:346T) recently designated 
5 The tree shows well defined further diversity indicating sustained or widespread trasmission
i think maybe it is more prudent designating it rather than closing this one or leaving it monitored undefinetely,
if it will die off it wont be the first nor the last .
What do you think @chrisruis @InfrPopGen @corneliusroemer ?

**Comment by FedeGueli** [comment]
361 seqs as today. Maybe designating this could help to differentiate further lineages carrying L:452M that appeared multiple times recently.
But the growth of this sublineage slowed down a lot and  i am ok if the committee goes for closing this issue w/o designation.

**Comment by FedeGueli** [comment]
400 sequences as today. very slow growth but interesting it never stopped circulating also in a BA.4/BA.5 envinronment

**Comment by FedeGueli** [comment]
425 sequences.  I went here to close this issue but Weirdly i have to say  it keeps on circulating so..

**Comment by FedeGueli** [comment]
I have ushered it to understand what is going on with this one:

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_39a5d_714590.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G2144T,C5183T,C22916A
![Schermata 2022-08-01 alle 01 52 21](https://user-images.githubusercontent.com/87669813/182050582-230ba440-53b4-40df-9856-1e044a5d56ec.png)

It seems that the branch with the reversion of Orf3a:78 to H has two sublineages probably with some fitness one with N:A90S and S:1263L  and another with S:Q836R
While the part of this sublineage without the Orf3a:78 reversion has an interesting S:147T sublineage.

Repeat: I have no problem in closing it but still some doubt after seeing its low level prolonged circulation.

@chrisruis @corneliusroemer

**Comment by FedeGueli** [comment]
442 sequences as today.
 
Everytime i am convincing myself to close this one something new happens:
It appears that in the branch defined by N:A90S there has been a new cluster of sux sequences  in Austria with additional mutations one in the spike (S:1263L) all very recent from earlier in July.

![Schermata 2022-08-07 alle 01 06 19](https://user-images.githubusercontent.com/87669813/183268574-1e1419af-330a-4c6f-8bbf-90ca1d65a119.png)

So despite being very far from the high transmissible dominant lineages this keeps on circulating and reaching new countries : now 24.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29dfa_eed760.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G28541T

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.9.6 with 410 newly designated sequences, and 1 updated designations. Defining mutation(s) C5183T (ORF1a:P1640S).

**Comment by FedeGueli** [comment]
Thx @InfrPopGen to have the patience to look at this old issue! Thx for decision to designate it even if no chance to compete against new 2nd gen variant era but still deserved it.
