### ISSUE TITLE
BA.2+25791T sublineage with S:D1153Y, N:D22G, ORF9b:I19V 6% cases in Arizona ( globally 275 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#672]
Here i want to propose a sublineage of BA.2 in the branch with 25791T that further acquired S:D1153Y,N:22G (=A28338G) (Orf9B:I19V).

This sublineage arose in Arizona and represents around 6% of sequences in the past two months
![Schermata 2022-05-26 alle 00 05 12](https://user-images.githubusercontent.com/87669813/170376933-afbba9d5-aa3d-4425-b39e-fc31bd368b86.png)

More interestingly it seemed to compete with BA.2.12.1 through early in May reaching a 23% of sequences not far from the share of BA.2.12.1 in that moment
![Schermata 2022-05-26 alle 00 12 46](https://user-images.githubusercontent.com/87669813/170376638-71337af4-0bb2-44f7-8a2c-0ec41e4790c7.png)

Growth advantage  or disadvantage comparing the two variants is all but clear:
BA.2.12.1 vs S:D1135Y baseline:
![Schermata 2022-05-26 alle 00 01 00](https://user-images.githubusercontent.com/87669813/170377815-9b90f9d2-3728-4d44-a1c2-a77c35b8b53e.png)
S:D1153Y vs BA.2.12.1 baseline
![Schermata 2022-05-25 alle 23 59 46](https://user-images.githubusercontent.com/87669813/170377017-8d663daf-b1cc-4aa6-ab01-d7ecf875e61e.png)

 [Usher Tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2fe0_e2bd90.json?branchLabel=aa%20mutations&c=gt-S_1153&label=nuc%20mutations:C241T,T670G,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10029T,C10198T,G10447A,C10449A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,G22992A,C22995A,A23013C,A23040G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,C26577G,G26709A,C26858T,A27259C,G27382C,A27383T,T27384C,C27807T,A28271T,C28311T,G28881A,G28882A,G28883C,A29510C)
![Schermata 2022-05-26 alle 00 23 08](https://user-images.githubusercontent.com/87669813/170378656-c8e0ec42-c0e8-4e7f-bf99-ed1cb967d442.png)

List of sequences:
[contributors (11).csv](https://github.com/cov-lineages/pango-designation/files/8774850/contributors.11.csv)
Nr of sequences: 218
Country: Usa/Arizona
First sequence: W9/22 (Texas)
Cov-Spectrum: https://cov-spectrum.org/explore/United%20States/AllSamples/Past6M/variants?aaMutations=S%3AD1153Y%2CN%3A22G%2CORF9b%3AI19V&pangoLineage1=BA.2.12.1*&aaMutations2=S%3AD1153Y%2CN%3A22G%2CORF9b%3AI19V&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.59 with 198 newly designated sequences, and 8 updated designations from BA.2. Defining mutation(s) A28338G (N:D22G).

**Comment by c19850727** [comment]
Hi @FedeGueli . I just found that 33 out of 75 genomes of XAA (#664 ) have S:D1153Y as well. 
Convergence?

**Comment by FedeGueli** [comment]
Thx @c19850727 ! great catch! no sign of recombination??
