### ISSUE TITLE
issue with assignment of BA.2 and BA.2.13 

### ISSUE THREAD

**Issue by alantsangmb** [cov-lineages/pango-designation#673]
Hello, I got a genome carry L452M and assigned as BA.2 by latest pangolin default usher mode and BA.2.13 with conflict of 0.35 using fast mode.
Nextclade assigned it as BA.2.13.

[BA.2.13_wgs.txt](https://github.com/cov-lineages/pango-designation/files/8777491/BA.2.13_wgs.txt)

**Comment by corneliusroemer** [comment]
I agree this looks like a very clear BA.2.13

So it's a pangoLEARN false negative.

**Comment by AngieHinrichs** [comment]
Actually in this case it's an UShER false negative!  In pangolin-data v1.8, the path for BA.2.13 is over-specific: in addition to C22916A/S:L452M, it also requires G24368T/S:D936Y which is found in only about half of BA.2.13 sequences.  

pangolin-data v1.9 is now in a pre-release state and will become the latest release later today or tomorrow.  @alantsangmb when v1.9 has been released and you update your installation (`pangolin --update-data` should work unless you're using a container), the sequence should be properly assigned to BA.2.13 in usher mode.

**Comment by corneliusroemer** [comment]
Thanks Angie, I missed the Usher mode. Rare report of an Usher issue :)

**Comment by alantsangmb** [comment]
Thanks Angie, I am closing the issue.
