### ISSUE TITLE
Potential BA.1*/BA.2* Recombinant with Likely Breakpoint at NSP5/NSP6 (56 Seqs as of 2022-05-12 in Costa Rica) 

### ISSUE THREAD

**Issue by LabGenomicaINC-CR** [cov-lineages/pango-designation#676]
****Potential BA.1*/BA.2* Recombinant with Likely Breakpoint at NSP5/NSP6 (56 Seqs as of 2022-05-12 in Costa Rica)**** 

by LabGenomicaINC-CR

Although this potential recombinant sublineage has a very similar breakpoint than XE recombinant, we thought it's still worth proposing considering it does not have the key mutations C3241T, V1069I, and C14599T that characterize XE and possess some private mutations. It has being focused mainly Central America (Costa Rica)  and highlight the need to support and reinforce the sequencing capacities in low & medium income countries.

When first detected in Costa Rica (epidemiological week 9) the sequences were located in the south of the country and this situation remain like this for some weeks, by  epidemiological week 18 recombinant sequences were detected in the central valley and Caribbean coast of Costa Rica showing active transmission within the country.

**Description**
**Recombinant between:** BA.1* & BA.2*
**Earliest sequence:** 2022/2/22 (Costa Rica)
**Most recent sequence:** 2022/5/12(Costa Rica)
**Countries circulating:** Costa Rica (56 seq), USA (4 seq), Chile (1 seq), Israel (1 Seq)   
**Likely breakpoint:** between 10448 and11287 (NSP5 or NSP6)
**Private mutations:** C2470T, C11514T, C22792T, G11516T, A24433G, C25624T.
**Cov-spectrum query:** G11516T, C11514T, A24433G, C25624T, C22792T
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=G11516T%2CC11514T%2CA24433G%2CC25624T%2CC22792T&

Note: There are 20 more sequences recently uploaded to Gisaid that were not included in the last update of this website so they are not in this analysis. 

Conserved Nuc mutations (those in red frames are likely from the donor from the BA.1 side):
In Costa Rica, 94 % of BA.1 and 98,7 % of BA.1.1. sequences have the C2470T mutation.

![1](https://user-images.githubusercontent.com/106392384/170730179-458af372-1ceb-4faa-a6d3-15bcd4a811b1.png)

**Evidence:**
We thought at first that these samples came from the recombinant XE sublineage, as the breaking point is really close to the XE one. But as this example in using NextClade depicts, the Costa Rican sequences don’t have key mutations such as C3241T, V1069I, and C14599T that characterize XE (red arrows in the image). 

![2](https://user-images.githubusercontent.com/106392384/170730239-e9239b6a-92cb-4150-b336-be1ddbc6544d.png)

![3](https://user-images.githubusercontent.com/106392384/170730268-7cb94537-7b17-498c-b144-c2ecb14de649.png)

We put our sequences plus an XE and XH recombinant sequences through Sc2rf from [@lenaschimmel](https://github.com/lenaschimmel) . Results showed that even when the breaking point is very similar to XE and XH, the Costa Rican sequences present several private mutations that are shared among them (C2470T, C11514T, C22792T, G11516T, A24433G, C25624T), but are not present in XE and XH.

![4](https://user-images.githubusercontent.com/106392384/170724102-665adbe4-4298-475a-8aa5-1c3ceab2a980.png)

Analyses with UShER tree showed that our sequences are located in a separate and monophyletic branch with some sequences from the United States, Chile and Israel.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3737f_ffd0e0.json

![5](https://user-images.githubusercontent.com/106392384/170730312-755a5e16-e54e-4761-a67b-cd3afac196c9.png)

The neighboring branch to the Costa Rican sequences cluster correspond to XE

Herein the list of genomes:

EPI_ISL_12226178
EPI_ISL_11596164
EPI_ISL_11823720
EPI_ISL_11823758
EPI_ISL_11823763
EPI_ISL_12172457
EPI_ISL_12454870
EPI_ISL_11596196
EPI_ISL_12191325
EPI_ISL_12572772
EPI_ISL_12572823
EPI_ISL_12572818
EPI_ISL_12572815
EPI_ISL_12694896
EPI_ISL_12694894
EPI_ISL_12694949
EPI_ISL_12694937
EPI_ISL_12694938
EPI_ISL_12742123
EPI_ISL_12761052
EPI_ISL_12832963
EPI_ISL_12832961
EPI_ISL_12832930
EPI_ISL_12832964
EPI_ISL_12832970
EPI_ISL_12832912
EPI_ISL_12832967
EPI_ISL_12835687
EPI_ISL_11823698
EPI_ISL_12172390
EPI_ISL_12226179
EPI_ISL_12172437
EPI_ISL_12172454
EPI_ISL_12172453
EPI_ISL_12172458
EPI_ISL_12172391
EPI_ISL_12172424
EPI_ISL_12226214
EPI_ISL_12420489
EPI_ISL_11596174
EPI_ISL_12420490
EPI_ISL_12420487
EPI_ISL_12420543
EPI_ISL_12507239
EPI_ISL_12935263
EPI_ISL_12935264
EPI_ISL_12935265
EPI_ISL_12935266
EPI_ISL_12935267
EPI_ISL_12935296
EPI_ISL_12935328
EPI_ISL_12935336
EPI_ISL_12935347
EPI_ISL_12935349
EPI_ISL_12935350
EPI_ISL_12935388
EPI_ISL_12935398
EPI_ISL_12935399
EPI_ISL_12935404
EPI_ISL_12935407
EPI_ISL_12935408
EPI_ISL_12935409
EPI_ISL_12935410
EPI_ISL_12935437

**Comment by chrisruis** [comment]
Thanks @LabGenomicaINC-CR We've added this as lineage XAF
