### ISSUE TITLE
Proposal of new sub-lineage of BA.2.12.1 with additional mutation nuc:T18753C only in peruvian genomes

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#679]
**Proposal of new sub-lineage of BA.2.12.1 with additional mutation nuc:T18753C only in peruvian genomes by Group of Genomic Surveillance INS-PERU**

**Description**
**Sub-lineage of:** Potential new sub-lineage of BA.2.12.1 (nuc: T18753C mutation mainly in Peruvian genomes)
**Earliest sequence:** hCoV-19/Peru/LIM-INS-16842/2022 (26/04/2022, Peru)
**Most recent sequence:** hCoV-19/USA/CA-CDC-STM-E9YV3JUR5/2022 (11/05/2022, USA)

**Countries circulating**
Peru (10), USA (3)

Some of the genomes of new sub lineage carried a reversion in Spike:S408R. This potential BA.2.12.1 is principally distributed in Lima, Peru

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/8794183/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1d6ab_3be9c0.json?branchLabel=aa%20mutations&c=gt-nuc_18753&label=nuc%20mutations:T15009C,C21721T
![T18753C 2 ](https://user-images.githubusercontent.com/87997149/170889107-a2602400-4da3-47a6-80c5-f51b50d0bc34.png)

![nucT18753C](https://user-images.githubusercontent.com/87997149/171219717-84633c9b-c69a-49d9-b80e-e0abc84d7b49.png)

**Proposed lineage name**
BA.2.12.X

**Comment by Vjimenez-vasquez** [comment]
Nice observation @LuisBarcenaF, this clade could be (maybe) the explanation for the last COVID-19 rise in Peru.

**Comment by Vjimenez-vasquez** [comment]
And still growing !

**Comment by OrsonMM** [comment]
Now are 75 genomes BA.2.12.1 and 20 of these carring the mutation proposed here (represent 26% of this lineage). 

<img width="992" alt="Luis_coment" src="https://user-images.githubusercontent.com/12600107/172643826-1b8a8b04-3e94-4a3e-a7df-1ba7b35595eb.png">

**Comment by OrsonMM** [comment]
36 genomes now

![image](https://user-images.githubusercontent.com/12600107/173256832-e920553c-613a-49ad-9ac7-adbb1dd0e087.png)

**Comment by chrisruis** [comment]
Thanks @LuisBarcenaF We now need new Pango lineages to be defined by at least one nonsynonymous mutation. We've therefore moved the start of this lineage one branch back in the tree so it includes several USA and UK sequences. We've therefore added this as BG.1 (with BG being an alias for BA.2.12.1) to start on the branch with A6458G (Orf1a:N2065D)
