### ISSUE TITLE
Potential new BA.2 sub-lineage with S:V1129I, ORF1a: T551S + nuc C29632T mutations [Peru, 25 seq]

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#683]
**Description**
New possible omicron sub-lineage with S:V1129I, ORF1a: T551S + nuc C29632T mutations proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**Earliest sequence:** 2022-04-13
hCoV-19/Peru/LIM-INS-16630/2022 (EPI_ISL_12530266)

**Most recent sequence:** 2022-05-09
Peru/LIM-INS-16920/2022 (EPI_ISL_12960923)
Peru/LIM-INS-17010/2022 (EPI_ISL_12961012)

**Countries circulating:**
Peru (25 sequences)

**Genomes**
[Genomes.csv](https://github.com/cov-lineages/pango-designation/files/8799846/Genomes.csv)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29246_4f0660.json?branchLabel=nuc%20mutations&c=pango_lineage

![Captura de pantalla de 2022-05-30 11-46-42](https://user-images.githubusercontent.com/89021119/171034744-89955605-7d85-4ddc-9645-662f974c8fb7.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AV1129I%2CORF1A%3AT551S&

![Captura de pantalla de 2022-05-30 11-57-57](https://user-images.githubusercontent.com/89021119/171035306-cb4fe95f-956e-438e-8c97-7d2a0d68f7e1.png)

![Captura de pantalla de 2022-05-30 11-58-18](https://user-images.githubusercontent.com/89021119/171035311-d4f752bc-7839-412f-bfa3-7c5464a573c9.png)

**Proposed lineage name**
BA.2.X

**Comment by Vjimenez-vasquez** [comment]
Good observation @Wen1953, this clade seems to be growing in Peru and Chile, and could be probably the responsible for the last COVID-19 rise in Peru.

**Comment by FedeGueli** [comment]
Ahah we did the same proposal at the same time!
Good there are more than two eyes on it ;)
i ll close my proposal!
Great catch by the way! me and @c19850727 were monitoring it since last week. It is worth a fast designatiion i ll close mine!

**Comment by FedeGueli** [comment]
I would like to reiterate here my analysis from.#683:

"It belongs to a branch of BA.2 with S:P1162S (301 seqs) circulating early in central Europe.
Then it acquired Nuc: C14625T and Orf1a:P1497S (169seqs) and this corresponds likely to the start of its circulation in North America,
Subsequently it gained the silent mutation: C9967T (90 sequences)
but it is with the last step acquiring S:V1129I and Orf1a:T551S that begun to circulate in Chile and Peru' "

Being already very deep in the branch i think it would be better broadening  this sublineage starting designation with
S:V1129I and Orf1a:T551S.

@corneliusroemer @chrisruis @AngieHinrichs What do you think? 

'

**Comment by OrsonMM** [comment]
16 genomes recent  from Peru

EPI_ISL_13022102	2022-05-10
EPI_ISL_13022105	2022-05-11
EPI_ISL_13022106	2022-05-12
EPI_ISL_13022107	2022-05-13
EPI_ISL_13022125	2022-05-11
EPI_ISL_13022126	2022-05-11
EPI_ISL_13022127	2022-05-11
EPI_ISL_13022132	2022-05-12
EPI_ISL_13022147	2022-05-12
EPI_ISL_13022155	2022-05-13
EPI_ISL_13022156	2022-05-13
EPI_ISL_13022157	2022-05-13
EPI_ISL_13022158	2022-05-13
EPI_ISL_13022164	2022-05-14
EPI_ISL_13022179	2022-05-10
EPI_ISL_13022196	2022-05-13

**Comment by OrsonMM** [comment]
currently in probable growing and competing with the BA.2.12.1 in peruvian population. 

<img width="982" alt="coment" src="https://user-images.githubusercontent.com/12600107/172417464-8bde82c8-6727-4742-84d5-c8ab2c463a5e.png">

**Comment by FedeGueli** [comment]
It has been designated BA.2.60

Starting with A1916T (Orf1a:T551S),G24947A (S:V1129I)

@InfrPopGen @corneliusroemer maybe BA 2.60 Milestone should be linked to this proposal to credit scientists which proposed it

**Comment by InfrPopGen** [comment]
Thank you @FedeGueli and @Wen1953 , yes it was designated two days ago, probably by @chrisruis , I have added the milestone.

**Comment by Wen1953** [comment]
@InfrPopGen thank you for detailing the designation, we will continue monitoring the emergence of new sub linages.
