### ISSUE TITLE
New BA.2 sublineage with double S2 mutations: S:V1129I, S:P1162S and Double Orf1a mutations circulating in Peru' and Chile 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#684]
Here i want to propose a sublineage of BA.2 with C9967T, C14625T, S:V1129I, S:P1162S, Orf1a:T551S, Orf1a:P1497S that recently has gained traction in Peru' and Chile.
It belongs to a branch of BA.2 with S:P1162S (301 seqs) circulating early in central Europe.
Then it acquired Nuc: C14625T and Orf1a:P1497S (169seqs) and this corresponds likely to the start of its circulation in North America,
Subsequently it gained the silent mutation: C9967T (90 sequences)
but it is with the last step acquiring S:V1129I and Orf1a:T551S that begun to circulate in Chile and Peru' :
these two countries have sampled 34 out of 64 sequences with all the mutations described here.

Tree:
![Schermata 2022-05-30 alle 20 03 44](https://user-images.githubusercontent.com/87669813/171042245-fd85ec1f-cbf0-4ea5-a2c2-85913e0c4a6a.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ccea_502890.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C25046T

Broader [Usher Tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_ccea_502890.json?branchLabel=aa%20mutations&c=gt-S_1129,1162&label=nuc%20mutations:C2790T,C9344T,A9424G,C9866T,C10198T,C17410T,C22673T,A22688G,A22786C,G27382C,A27383T,T27384C,A29510C)
![Schermata 2022-05-30 alle 20 05 13](https://user-images.githubusercontent.com/87669813/171042407-56db7ffc-a221-4041-b1b4-7fb54c38b764.png)

List of Sequences:
[contributors (3).csv](https://github.com/cov-lineages/pango-designation/files/8800117/contributors.3.csv)

Number of Sequences: 64
Countries:
![Schermata 2022-05-30 alle 20 06 31](https://user-images.githubusercontent.com/87669813/171042567-0b099d93-0025-4c04-bcc9-8da99e7e4759.png)

Prevalence: it was around 19% in Peru' and 2% in Chile (Atacama) during the last week.

Apparent [Growth advantage](https://cov-spectrum.org/explore/South%20America/AllSamples/Past3M/variants?pangoLineage=BA.2*&aaMutations1=S%3AV1129I%2CS%3A1162S%2COrf1a%3AT551S%2COrf1a%3AP1497S&nucMutations1=C9967T%2CC14625T&analysisMode=CompareToBaseline&) vs BA.2 baseline probably somewhere between the ones shown in Peru' or Chile:
![Schermata 2022-05-30 alle 20 09 18](https://user-images.githubusercontent.com/87669813/171042909-d918e2b2-c664-4d58-8828-29f74068aa6e.png)
![Schermata 2022-05-30 alle 20 09 25](https://user-images.githubusercontent.com/87669813/171044649-3c08d3f5-706c-4d22-a331-fffcd8d0a02c.png)

thx @c19850727 for encouraging me to propose it.

**Comment by Vjimenez-vasquez** [comment]
Hi @FedeGueli, our colleague @Wen1953 has recently pointed out the same observation in the issue #683 , please take a look
Bests,

**Comment by FedeGueli** [comment]
Proposed the same rime in #693 closimg this!

**Comment by FedeGueli** [comment]
Designated BA.2.60 from #683
