### ISSUE TITLE
Proposal for a BA.2.12 sublineage with S:R357K and ORF7a:Q62R (533 sequences as of 2022-05-30, Australia)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#686]
### Description
**Potential sublineage of**: BA.2.12
**Earliest sequence**: 2022/02/05 (Australia-VIC)
**Most recent sequence**: 2022/5/23 (Australia-TAS)
**Mutations on top of BA.2.12**: C11674T, C17586T, G22632A (S:R357K), A27578G (ORF7a:Q62R)
**Countries circulating**: Australia (~3.3% prevalence in Victoria, ~1.2% prevalence in Tasmania in recent 3 months as per Covspectrum) 
**Border-entry cases**: 
- Japan ex-Australia (1 sequence), 
- Singapore ex-Australia (3 sequences), 
- Hong Kong ex-Australia (1 sequence), 
- New Zealand MIQ (5 sequences) (MIQ=managed isolation & quarantine).

### Evidence
**Nextstrain Oceania-focused subsampling dataset**:
![image](https://user-images.githubusercontent.com/86835836/171083336-3277bf0d-1ff2-4310-9192-274d1bf56d3d.png)

**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/171084320-06621e4d-8ac8-48b0-9260-18c50f757397.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1915f_582a20.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C17586T,A27578G&tl=country

### Genomes:
[BA.2.12 R357K.csv](https://github.com/cov-lineages/pango-designation/files/8801618/BA.2.12.R357K.csv)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.12.2 with 220 newly designated sequences, and 216 updated designations from BA.2.12. Defining mutation(s) G22632A (S:R357K).
