### ISSUE TITLE
Proposal for a BA.2.3 sublineage with S:I692F and M:I76V (138 sequences as of 2022-06-10, Japan)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#687]
### Description
**Potential sublineage of**: BA.2.3
**Earliest sequence**: 2022/03/05 (Japan)
**Most recent sequence**: 2022/5/05 (Japan)
**Mutations on top of BA.2.3**: C16699T (ORF1b:R1078C), T17771G (ORF1b:I1435S), A23636T (S:I692F), A26748G (M:I76V)
**Countries circulating**: Japan (79 sequences, ~0.7% prevalence in past 2 months), Australia-WA (1 sequence)

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/171093476-5ae80ddd-8928-4bee-9898-0fada495490e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41717_599d60.json?branchLabel=aa%20mutations&c=gt-nuc_23636&label=nuc%20mutations:C16699T

### Genomes:
[BA.2.3 I692F.csv](https://github.com/cov-lineages/pango-designation/files/8802009/BA.2.3.I692F.csv)

**Comment by c19850727** [comment]
138 sequences as of 2022-06-10.

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as BA.2.3.18 to start on the branch with T17771G (Orf1b:I1435S)
