### ISSUE TITLE
Potential new sublineage of B.1.1.X including S:E484K, S:S494P and S:F157_V159del

### ISSUE THREAD

**Issue by GediminasA** [cov-lineages/pango-designation#69]
New lineage proposal
by Lukas Žemaitis, Gytis Dudas, Gediminas Alzbutas, Arnoldas Pautienius, Dovydas Gečys, Vaiva Lesauskaitė 

## Description
Sub lineage of B.1.1
Earliest sequence : 2021-03-09
Most recent sequence: 2021-04-19
Countries circulating: Finland Germany Latvia Lithuania Russia Switzerland United Kingdom

This lineage was recently detected in one Lithuanian sample.However, close variants are also detected in several other countries, mostly Switzerland and Germany. A distinct feature is combination of E484K and S494P in the binding surface of ACE2 and a deletion of three amino acids at the spike NTD . These could result in increased potential to escape from antibodies. Nextclade  annotator warns that all these sequences have too much private mutations, but these are not artifacts. 

#### Genomes:
England/MILK-151C388/2021
Finland/THL-202111577/2021
Germany/BY-RKI-I-070520/2021
Germany/BY-RKI-I-070566/2021
Germany/un-RKI-I-085637/2021
Latvia/2103045868/2021
Lithuania/S21D1201/2021
Russia/SPE-RII-MH15687S/2021
Russia/SPE-RII-MH15739S/2021
Switzerland/AG-ETHZ-550306/2020
Switzerland/GE-33615516/2021
Switzerland/GE-33759461/2021
Germany/un-RKI-I-066423/2021
#### Evidence
Sequences, belonging to the B.1.1 lineage from the the global covid phylogeny nextregions data (available via GISAID portal at 2021-04-29) were supplemented with the 13 sequences belonging to the new potential strain and with sequences belonging to the B.1.1.161 and B.1.1.461 lineages. The maximum-likelihood tree was produced using iq-tree using GTR+I+G model. 
Out of the 13 sequences one is currently is classified by pangolin as B.1.1.161 (Finland/THL-202111577/2021), four are classified as B.1.1.461 (Switzerland/AG-ETHZ-550306/2020, Switzerland/GE-33615516/2021,Switzerland/GE-33759461/2021,Germany/un-RKI-I-066423/2021). However, all 13 sequences clearly forms a distinct cluster (depicted by yellow colour in the figure bellow "B.1.X").
![image](https://user-images.githubusercontent.com/43229028/117187390-86c2e380-ade4-11eb-986a-8c229c4ff6b3.png)
[](url)
Here is the corresponding tree with support values (iq-tree,  Ultrafast Bootstrap): 
[boost.zip](https://github.com/cov-lineages/pango-designation/files/6429290/boost.zip)

**Comment by evogytis** [comment]
Here's a complete list of GISAID accessions for this lineage:
[accessions.txt](https://github.com/cov-lineages/pango-designation/files/6432795/accessions.txt)

The earliest detection and most sequences since were reported in Russia.

**Comment by chrisruis** [comment]
Hi @GediminasA @evogytis thanks for submitting this, we've added this as lineage B.1.1.523 in [v1.2.5](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.5)

It looks like there's a few more sequences that are currently assigned to B.1.1.451 that actually cluster within this clade as well so I've included those in the designations. So there's 73 sequences in the designation, full list of GISAID accessions:
[B.1.1.523_gisaid_accessions.txt](https://github.com/cov-lineages/pango-designation/files/6488951/B.1.1.523_gisaid_accessions.txt)


We need all designated sequences to have <5% ambiguities now, so I didn't include EPI_ISL_1823191 which has a little over this.
