### ISSUE TITLE
BA.2+22792T sublineage with S:W64R (21752C) circulating in Scandinavia (145 seq, 5-10% in Norway and Sweden)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#695]
Proposal for a sublineage of BA.2
Earliest sequence: 2022-01-29 (Norway)
Countries detected: Norway (49), Sweden (30), Denmark (18), US (17), Germany (11) and various others in smaller numbers

Defining mutations: S:W64R on top of BA.2+22792T. 
As pointed out in #630, the mutation S:W64R can be produced by T21752A or T21752C; in this lineage it is T21752C.

The Usher tree reveals that there are many separate occurrences of 21752C in BA.2+22792T. Excluding those in BA.2.9, the two largest branches are the one with just 21752C and one where it is apparently preceded by 22597T. Both of these lineages are most prevalent in Norway, which leads me to suspect that they are in fact just one lineage and that 22597T occurred twice independently. Though there are a handful of Norwegian 22597T without 21752C, so it's not that clear-cut...

Usher tree for sequences without 22597T: [https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_bb0d_69e6a0.json?c=gt-S_64&label=nuc%20mutations:T21752C](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_bb0d_69e6a0.json?c=gt-S_64&label=nuc%20mutations:T21752C)
Usher tree for sequences with 22597T:
[https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_bb0d_69e6a0.json?c=gt-S_64&label=nuc%20mutations:T21752C](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_bb0d_69e6a0.json?c=gt-S_64&label=nuc%20mutations:T21752C)

To get a cov-spectrum query I had to remove all the other occurrences of 21752C. This should work pretty well for now: [https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=BA.2*+%26+22792T+%26+21752C+%26+%21%28BA.2.9*+%7C+25624T+%7C+28476A+%7C+15437C+%7C+22308C+%7C+3218A+%7C+14395G+%7C+7850T+%7C+22629C+%7C+906T+%7C+27159G+%7C+11024G%29&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=BA.2*+%26+22792T+%26+21752C+%26+%21%28BA.2.9*+%7C+25624T+%7C+28476A+%7C+15437C+%7C+22308C+%7C+3218A+%7C+14395G+%7C+7850T+%7C+22629C+%7C+906T+%7C+27159G+%7C+11024G%29&)

Like the other S:W64R lineages, there appears to be a growth advantage over BA.2. Sequence numbers in Norway and Sweden are small enough that I don't think it makes sense to report an actual figure, but it's clearly growing as a proportion of sequences in both countries.

<img width="494" alt="Norway_Sweden_W64R" src="https://user-images.githubusercontent.com/42699509/171302875-c987c620-cf64-4b64-a452-5df37ab258b5.png">

Sequences: [EPI_ISLs.txt](https://github.com/cov-lineages/pango-designation/files/8810093/EPI_ISLs.txt)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.71 with 72 newly designated sequences, and 5 updated designations from BA.2. Defining mutation(s) T21752C (S:W64R).

**Comment by FedeGueli** [comment]
@AngieHinrichs  i re foud this BA.2.71  from a chilean recent sequence but in Usher it is still assigned as BA.2 for the reasons well explained above by @silcn .
The thing could be more than a discussion on the past
 cause the branch Usher calls BA.2 has further acquired S:G75V and this last chilean sequence EPI_ISL_14418335
belongs to a cluster that have accumulated a bunch of orf1ab  mutations.
While is unlikely that this lineage will ever gain an advantage over BA.5 and other lineages, maybe if we can establish that they are two and not just one only B.2.71, it deserves a proposal on its own.
cc @corneliusroemer 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e1ff_7f8e40.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A9529G

![chrome_screenshot_1660428514442](https://user-images.githubusercontent.com/87669813/184512217-ee83ab29-8c42-419f-874f-e56bbf12e25b.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A75V%2CS%3A64R&nucMutations=22597T&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&
