### ISSUE TITLE
Potential BE.1* sub-lineage [ORF3a: 48F & 49C] - mainly in New South Wales, Australia and Europe

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#696]
**Proposal for BE.1* sub-lineage with orf3a: V48F and G49C.**

Total sequences: 35
Hotspot: New South Wales, Australia (18 sequences)
Countries detected: Australia, South Africa, England, Scotland, USA

Defining Mutations: ORF3a:V48F and ORF3a:G49C
Other Mutations: N:E136D, ORF1a: Q556K, ORF1b:M1156I, ORF1a:A1204T
Earliest sequence: 4/16/22 (South Africa)

**Nextstrain tree:**
![FUJHVjfX0AAUTjJ](https://user-images.githubusercontent.com/98380390/171335737-352606fb-8838-44e4-bc58-da8e127f5d77.jpg)

Link: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_deaf_6f0930.json?branchLabel=aa%20mutations&c=userOrOld&label=nuc%20mutations:G28681T

**Cov-Spectrum query/Growth Advantage:** 
Too early to gauge growth advantage 
- regional advantage of this potential sub-lineage vs BE.1 in Australia is 266% (would wait a few days to compute growth advantage)
https://cov-spectrum.org/explore/Australia/AllSamples/Past3M/variants?aaMutations=orf1a%3Aq556k%2CN%3AE136D%2CS%3AL452R%2CS%3AF486V%2CM%3AD3N%2CORF1b%3AM1156I&aaMutations1=orf3a%3A49c%2Corf3a%3A48f%2Corf1a%3Aq556k%2CN%3AE136D%2CS%3AL452R%2CS%3AF486V%2CM%3AD3N%2CORF1b%3AM1156I&analysisMode=CompareToBaseline& 

Sequences list: 
[GISAID_ORF3a_48_49.csv](https://github.com/cov-lineages/pango-designation/files/8811493/GISAID_ORF3a_48_49.csv)

Related issues: https://github.com/cov-lineages/pango-designation/issues/625

**Comment by RajLABN** [comment]
Total Sequences (6/9/22): 79   [GISAID query: n_e136d, ns3_v48f, ns3_g49c, spike_f486v, m_d3n, spike_l452r]
 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=orf1a%3Aq556k%2CN%3AE136D%2CS%3AL452R%2CS%3AF486V%2CM%3AD3N%2CORF1b%3AM1156I%2Corf3a%3A48f%2Corf3a%3A49c&aaMutations1=orf3a%3A49c%2Corf3a%3A48f%2Corf1a%3Aq556k%2CN%3AE136D%2CS%3AL452R%2CS%3AF486V%2CM%3AD3N%2CORF1b%3AM1156I&

**Comment by learithe** [comment]
> * regional advantage of this potential sub-lineage vs BE.1 in Australia is 266% (would wait a few days to compute growth advantage)

The Australian sequences in question belong to our team (ICPMR, NSW). In NSW we have recently been specifically targeting potential BA.4/BA.5 samples (S-gene target failure) for sequencing. Please do NOT interpret sampling bias as a growth advantage.

**Comment by RajLABN** [comment]
Thank you! that explains the sudden uptick of this sub-lineage in NSW

It's increasing in other places too.. As of 6/13/22.. 163 sequences in total

**Comment by chrisruis** [comment]
Thanks @RajLABN As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

There doesn't seem to be a clear epidemiological event associated with this clade, we therefore haven't designated this at this point

**Comment by RajLABN** [comment]
BE.1+ orf3a:48f & 49c is growing...beyond Australia.. now up to 254 sequences,  recent uptick in United Kingdom
![image](https://user-images.githubusercontent.com/98380390/174422681-a0800dd9-6fff-4866-9492-426af8286511.png)

Nextstrain tree:
![image](https://user-images.githubusercontent.com/98380390/174422620-2bd729e6-35f2-4006-b49f-11c8c72901d3.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ac66_d50b60.json?branchLabel=aa%20mutations&c=gt-ORF3a_48,49&label=nuc%20mutations:C12068T,G25534T,G25537T

**Comment by agamedilab** [comment]
655 sequences on usher as of 27.6.22.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_292ee_983ef0.json?branchLabel=aa%20mutations&label=nuc%20mutations:C12068T,G25534T,G25537T

Advantage versus global BA.5:

![grafik](https://user-images.githubusercontent.com/102166254/175919975-25ba0bc3-6722-486f-bc78-a0881c7275d1.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.5*&aaMutations1=orf3a%3A49c%2Corf3a%3A48f%2Corf1a%3Aq556k%2CN%3AE136D%2CS%3AL452R%2CS%3AF486V%2CM%3AD3N%2CORF1b%3AM1156I&analysisMode=CompareToBaseline&

**Comment by RajLABN** [comment]
Europe... (especially Germany)

https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?aaMutations=orf1a%3Aq556k%2CN%3AE136D%2CS%3AL452R%2CS%3AF486V%2CM%3AD3N%2CORF1b%3AM1156I&aaMutations1=orf3a%3A49c%2Corf3a%3A48f%2Corf1a%3Aq556k%2CN%3AE136D%2CS%3AL452R%2CS%3AF486V%2CM%3AD3N%2CORF1b%3AM1156I&analysisMode=CompareToBaseline&

**Comment by RajLABN** [comment]
Of the 7209 sequences publicly available via GISAID - 625 originated from a hospital (various countries)-- 65 indicated the specimen is from a hospitalized patient and 1 dead.

Still maintains a growth advantage over BE.1

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BE.1*&aaMutations1=orf3a%3A49c%2Corf3a%3A48f&nextcladePangoLineage1=BE.1*&analysisMode=CompareToBaseline&
