### ISSUE TITLE
BA.5.3 sublineage with ORF1ab:R119H (226 seq. c. 33% of german BA.5)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#697]
Proposal for a sublineage of BA.5.3
Earliest sequence: 11.04.2022 (Germany)
Countries detected: mainly Germany (87%), Switzerland, Netherlands, Austria, Israel, USA, Denmark, Scotland, France, Sweden, England

Defining mutations:
G621A = ORF1ab:R119H

This variant is defined by ORF1ab:R119H and was first detected in Germany and multiple other European countries. Within Germany it currently represents c. 33 % (197/684) BA.5 genomes.

This variant is apparently a sublineage of BA.5.3 as it carries ORF1ab:Q556K but also lacks the BA.5.3 defining N:E136D (see #550).

![pic](https://user-images.githubusercontent.com/102166254/171419399-c2cd6024-cef8-4f0e-a885-d07fa8837bcf.PNG)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2bd3c_765110.json?branchLabel=aa%20mutations&c=gt-ORF1ab_119&label=nuc%20mutations:C1931A

EPI_ISL_12999769, EPI_ISL_12317782, EPI_ISL_12346538, EPI_ISL_12354933, EPI_ISL_12357300, EPI_ISL_12360686, EPI_ISL_12361382, EPI_ISL_12465862, EPI_ISL_12492164, EPI_ISL_12513244, EPI_ISL_12517340, EPI_ISL_12517523, EPI_ISL_12517547, EPI_ISL_12518111, EPI_ISL_12518145, EPI_ISL_12518992, EPI_ISL_12519821, EPI_ISL_12523570, EPI_ISL_12523699, EPI_ISL_12546671, EPI_ISL_12560925, EPI_ISL_12567235, EPI_ISL_12606358, EPI_ISL_12610559, EPI_ISL_12615486, EPI_ISL_12632482, EPI_ISL_12648721, EPI_ISL_12672524, EPI_ISL_12672529, EPI_ISL_12672566, EPI_ISL_12672591, EPI_ISL_12673731, EPI_ISL_12673972, EPI_ISL_12674280, EPI_ISL_12674577, EPI_ISL_12674661, EPI_ISL_12674669, EPI_ISL_12674677, EPI_ISL_12674681, EPI_ISL_12675523, EPI_ISL_12675627, EPI_ISL_12675969, EPI_ISL_12676682, EPI_ISL_12676898, EPI_ISL_12677001, EPI_ISL_12677021, EPI_ISL_12677371, EPI_ISL_12677777, EPI_ISL_12678160, EPI_ISL_12678531, EPI_ISL_12688267, EPI_ISL_12689905, EPI_ISL_12699989, EPI_ISL_12715920, EPI_ISL_12728989, EPI_ISL_12729077, EPI_ISL_12729110, EPI_ISL_12729167, EPI_ISL_12729173, EPI_ISL_12730499, EPI_ISL_12732946, EPI_ISL_12733042, EPI_ISL_12733949, EPI_ISL_12734794, EPI_ISL_12735065, EPI_ISL_12736856, EPI_ISL_12736872, EPI_ISL_12737108, EPI_ISL_12737185, EPI_ISL_12737244, EPI_ISL_12737481, EPI_ISL_12737644, EPI_ISL_12738663, EPI_ISL_12742731, EPI_ISL_12754673, EPI_ISL_12781419, EPI_ISL_12781669, EPI_ISL_12813425, EPI_ISL_12815584, EPI_ISL_12815592, EPI_ISL_12816324, EPI_ISL_12816329, EPI_ISL_12818271, EPI_ISL_12818369, EPI_ISL_12819485, EPI_ISL_12820627, EPI_ISL_12820695, EPI_ISL_12824156, EPI_ISL_12824159, EPI_ISL_12824615, EPI_ISL_12824627, EPI_ISL_12824758, EPI_ISL_12826036, EPI_ISL_12826162, EPI_ISL_12826282, EPI_ISL_12826688, EPI_ISL_12826709, EPI_ISL_12826752, EPI_ISL_12826767, EPI_ISL_12826924, EPI_ISL_12827069, EPI_ISL_12827361, EPI_ISL_12827944, EPI_ISL_12827948, EPI_ISL_12828264, EPI_ISL_12828576, EPI_ISL_12844496, EPI_ISL_12844499, EPI_ISL_12844509, EPI_ISL_12844521, EPI_ISL_12857252, EPI_ISL_12864223, EPI_ISL_12869443, EPI_ISL_12870853, EPI_ISL_12875226, EPI_ISL_12875264, EPI_ISL_12879704, EPI_ISL_12879705, EPI_ISL_12893600, EPI_ISL_12914468, EPI_ISL_12915711, EPI_ISL_12923044, EPI_ISL_12931815, EPI_ISL_12953788, EPI_ISL_12953798, EPI_ISL_12995372, EPI_ISL_12997261, EPI_ISL_12997543, EPI_ISL_12997889, EPI_ISL_12997891, EPI_ISL_12997913, EPI_ISL_12998001, EPI_ISL_12998402, EPI_ISL_12998857, EPI_ISL_12999456, EPI_ISL_13000063, EPI_ISL_13000071, EPI_ISL_13000073, EPI_ISL_13000155, EPI_ISL_13000322, EPI_ISL_13000331, EPI_ISL_13000519, EPI_ISL_13000859, EPI_ISL_13000901, EPI_ISL_13000907, EPI_ISL_13000918, EPI_ISL_13001593, EPI_ISL_13001596, EPI_ISL_13001596, EPI_ISL_13001607, EPI_ISL_13001610, EPI_ISL_13001787, EPI_ISL_13002283, EPI_ISL_13002290, EPI_ISL_13002503, EPI_ISL_13002539, EPI_ISL_13002562, EPI_ISL_13002618, EPI_ISL_13003478, EPI_ISL_13003554, EPI_ISL_13003704, EPI_ISL_13003810, EPI_ISL_13004122, EPI_ISL_13004140, EPI_ISL_13004225, EPI_ISL_13004590, EPI_ISL_13004598, EPI_ISL_13004845, EPI_ISL_13009477, EPI_ISL_13009492, EPI_ISL_13009496, EPI_ISL_13009558, EPI_ISL_13009602, EPI_ISL_13009853, EPI_ISL_13009884, EPI_ISL_13010233, EPI_ISL_13011287, EPI_ISL_13011434, EPI_ISL_13011438, EPI_ISL_13011515, EPI_ISL_13011766, EPI_ISL_13012804, EPI_ISL_13013038, EPI_ISL_13013139, EPI_ISL_13013147, EPI_ISL_13013195, EPI_ISL_13013279, EPI_ISL_13013290, EPI_ISL_13013700, EPI_ISL_13013712, EPI_ISL_13014162, EPI_ISL_13014561, EPI_ISL_13014584, EPI_ISL_13014991, EPI_ISL_13014993, EPI_ISL_13015003, EPI_ISL_13015040, EPI_ISL_13015049, EPI_ISL_13015056, EPI_ISL_13015064, EPI_ISL_13015070, EPI_ISL_13015079, EPI_ISL_13015080, EPI_ISL_13015099, EPI_ISL_13015139, EPI_ISL_13015541, EPI_ISL_13015558, EPI_ISL_13015589, EPI_ISL_13015595, EPI_ISL_13015610, EPI_ISL_13015620, EPI_ISL_13015623, EPI_ISL_13015659, EPI_ISL_13015700, EPI_ISL_13015830, EPI_ISL_13015873, EPI_ISL_13015902, EPI_ISL_13015938, EPI_ISL_13016001, EPI_ISL_13016044, EPI_ISL_13016069, EPI_ISL_13016114, EPI_ISL_13016206, EPI_ISL_13016659, EPI_ISL_13016669, EPI_ISL_13028236

**Comment by RajLABN** [comment]
I do see a bunch of orf1a:R119H from Germany.

**Comment by agamedilab** [comment]
@RajLABN Hi, many thanks for spotting this! Yes i t is a typo. It should mean orf1ab:R119H as shown in the pic. I will edit right away.
