### ISSUE TITLE
BA.2 + C24865T sublineage with S:212S (400+ sequences) circulating in Usa, Germany

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#698]
Here i want to propose a sublineage that seems to compete with BA.2.12.1 in USA.

it emerged from the branch defined by C24865T and has as defining mutation S:212S.
90% has 22792T that Usher put after S:212S (@AngieHinrichs do you think it is real or this lineage "budded" from the bigger 22792T branch then acquiring C24865T?)
![Schermata 2022-06-01 alle 15 46 18](https://user-images.githubusercontent.com/87669813/171419749-f5bd7c99-8419-4fdf-95c2-a83348c7680f.png)
[Usher tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37dc8_769fa0.json?branchLabel=aa%20mutations&c=gt-nuc_22792,24865&label=nuc%20mutations:C24865T)

Nr of sequences: 400+

List of sequences:
[contributors (4).csv](https://github.com/cov-lineages/pango-designation/files/8814698/contributors.4.csv)

Countries: Usa, Germany Switzerland
Cov-Spectrum overview
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=S%3A212S&nucMutations=C24865T&
![Schermata 2022-06-01 alle 15 44 05](https://user-images.githubusercontent.com/87669813/171419215-daad228f-9a27-49a7-b96d-473ab503e577.png)

Comparison to BA.2.12.1 in USA:
![Schermata 2022-06-01 alle 15 47 35](https://user-images.githubusercontent.com/87669813/171420042-83de29a5-1f0b-40a1-ae35-689c5b69129c.png)
The growth disadvantage appears to be slight this makes this lineage a good candidate to keep circulating in this multi dominant variants phase ( and so good chance to recombine with it)
![Schermata 2022-06-01 alle 15 48 40](https://user-images.githubusercontent.com/87669813/171420295-244526ce-d3c3-4263-84f0-cc836d8e7381.png)

**Comment by AngieHinrichs** [comment]
Good question @FedeGueli.  I think the late C22792T might be a real homoplasy.  I looked for reasonably large (> 50 sequences) branches of BA.2 + C22792T that also had C24865T and T22197C but didn't find any good candidates.  Here's what I found (number of sequences and example sequence in parentheses):

C22792T > G840A (344) > C24865T (176), no 22197 (England/ARCH-002971A7/2022|OW471660.1|2022-03-23)

C22792T > G28476A (2986) > C24865T (1847), no 22197 (Austria/LB-R00059-S294/2022|EPI_ISL_9852459|2022-02-04)

C22792T > C100T (371) > T22197C (206), no 24865 (Germany/BW-RKI-I-683548/2022|EPI_ISL_11670531|2022-03-09)

C22792T > G28079T (840) > T22197C (320), no 24865 (Switzerland/ZH-ETHZ-37066307/2022|OW557385.1|2022-04-03)

C22792T > C9532T (1078) > T22197C (880), no 24865 (Denmark/DCGC-407040/2022|EPI_ISL_10808607|2022-02-22)

(And a few others with several mutations preceding C24865T or T22197C.)

Dropping down to at least 10 sequences to find a C22972T > (T22197C or C24865T) without some other mutation first, I found one for C24865T but none for T22197C:

C22792T > C24865T (13), no 22197 (France/ARA-HCL722002574301/2022|EPI_ISL_12699287|2022-05-02)

homoplasies abound...

**Comment by FedeGueli** [comment]
Thank you @AngieHinrichs very much for your time! 👍 yes homoplasies in BA.2, especially in the Spike region are very very abundant, something i didnt remember with Delta , maybe just us focusing on smaller clades so we see more of them or immunity outside forcing BA.2 to find out (and fix) every pathway to transmit itself further.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.72 with 323 newly designated sequences, and 20 updated designations from BA.2. Defining mutation(s) T22197C (S:L212S).
