### ISSUE TITLE
Potential New Lineages in Missouri, USA

### ISSUE THREAD

**Issue by pangolinuser** [cov-lineages/pango-designation#7]
**New lineage proposals**
by: Cynthia Y Tang, Xiu-Feng Wan

**Description 1**
Sub-lineage of: B.1.1
Earliest sequence: 7/2/20
Most recent sequence: 7/9/20
Countries circulating: USA

**Description 2**
Sub-lineage of: B.1.1
Earliest sequence: 5/14/20
Most recent sequence: 7/9/20
Countries circulating: USA

**Description 3**
Sub-lineage of: B.1.2
Earliest sequence: 7/5/20
Most recent sequence: 7/7/20
Countries circulating: USA

**Description 4**
Sub-lineage of: B.1
Earliest sequence: 7/2/20
Most recent sequence: 7/6/20
Countries circulating: USA

During 2 sampling periods (March and July 2020), 4 locally adapted SARS-CoV-2 lineages, each with unreported mutations, emerged in Missouri. Each new lineage had >95% posterior probability when analyzed using Bayesian phylogenetics, >99% sequence identity, and occupied a separate subclade than published sequences in the phylogeny. The associated unpublished mutations are as follows:
Proposed lineage: B.1.1.318 (NSP12-A2V)
Proposed lineage: B.1.1.319 (NSP4-M366I, NSP12-C22F)
Proposed lineage: B.1.2.1 (NSP15-P252L)
Proposed lineage: B.1.527 (NSP3-N1178T, NSP3-A1179T)

**Genomes**
[meta.xlsx](https://github.com/cov-lineages/pango-designation/files/5969008/meta.xlsx)

**Evidence**
[eFigure2.FullTreeAnnotated.pdf](https://github.com/cov-lineages/pango-designation/files/5968901/eFigure2.FullTreeAnnotated.pdf)
(Highlighted and denoted starting with 'MO-')
Proposed lineage names:
B.1.1.318
B.1.1.319
B.1.2.1
B.1.527

**Comment by rambaut** [comment]
![eFigure2 FullTreeAnnotated](https://user-images.githubusercontent.com/686405/107845715-a514d680-6dd5-11eb-9429-d41b8f2b2d4f.png)

**Comment by pangolinuser** [comment]
Hello,

Please let us know if we can provide any additional information for these proposed lineages.

**Comment by chrisruis** [comment]
Thanks for submitting @pangolinuser This issue has gone stale so we'll close it for now - please reopen if these are still of interest now
