### ISSUE TITLE
Wrongly assignment of samples to lineage B.1.177, while they should be classified (at least) as B.1.525.

### ISSUE THREAD

**Issue by gabbo89** [cov-lineages/pango-designation#70]
Dear,

I have a bunch of sequences that are presumably wrongly assigned to lineage B.1.177, while they should be classified to the lineage B.1.525 (or sublineages).

These samples share all the canonical mutations of the B.1.525 lineage, with some extra new mutations. 

We can provide several evidences that there is a problem in the assignment of pangolin for these samples:
1. Top 10 blast hit sequences on GISAID of one personal sequence belongs to the B.1.525 line (EPI_ISL_1578463,EPI_ISL_1279137,EPI_ISL_1093470,EPI_ISL_1508897,EPI_ISL_1049260,EPI_ISL_1093467,EPI_ISL_1093465,EPI_ISL_1742737,EPI_ISL_1570152).

2. We generated a tree with:

- 250 randomly sampled samples (from GISAID) belonging to lineage B.1.177 (identified as #|b1.177.shuf )
- 250 randomly sampled samples (from GISAID) belonging to lineage B.1.525 (identified as #|b1.525.shuf )
- 53 samples (from GISAID) belonging to lineage B.1.177 with the spike mutation E484K (identified as #|b1.177.spike )
- 3 personal samples (identified as pers1, pers2, pers3)
- the reference sequence (MN908947.3)

[shuf250.mafft.tree_plus_own_seq.pdf](https://github.com/cov-lineages/pango-designation/files/6441974/shuf250.mafft.tree_plus_own_seq.pdf)

As it can be observed our own sequences [highlighted in bold] (and some samples assigned to B.1.177 but with spike mutation E484K [#|b1.177.spike]) reside on the B.1.525 clade (highlighted in blue). 

Also in Nextclade our own samples (highlighted in red) reside on the clade with B.1.525 samples.

![shuf250 mafft nexclade_tree](https://user-images.githubusercontent.com/30347680/117459766-0dde9b80-af4c-11eb-9798-b0dd7c9937cc.jpg)

3. By comparing the mutation profile of:
- 10 randomly selected samples belonging to lineage B.1.177
- 10 randomly selected samples belonging to lineage B.1.525
-  3 personal samples (identified as pers1, pers2, pers3)
- 7 selected samples assigned to B.1.177 but with spike mutation E484K and near in the tree to our samples (EPI id are reported in file 7samples.EPI_id.txt)

[shuf250.mafft.github.pdf](https://github.com/cov-lineages/pango-designation/files/6441765/shuf250.mafft.github.pdf)

[7samples.EPI_id.txt](https://github.com/cov-lineages/pango-designation/files/6441789/7samples.EPI_id.txt)

As it can be observed, the mutation profile of the problematic samples is very similar to the B.1.525 randomly sampled, with the exception of some mutations that seem's to be subgroup specific. 
For example mutation at coordinates 4782, 17067 and 17364 are unique to the EPI EPI_ISL_1439628, EPI_ISL_1439632, EPI_ISL_1569874, EPI_ISL_1571169 (all sampled in Germany). Vice versa, mutation at coordinates 8964, 20762 and 21853 are unique to our samples (one already present in GISAID : 43|b1.177.spike = EPI_ISL_1840726).

How would you explain this behaviour?
If necessary I can upload the fasta sequences of our three personal samples.

Thank you in advance for your help.

**Comment by AngieHinrichs** [comment]
Thank you for reporting these, @gabbo89.  I will add those 7 sequences and a few others to lineages.csv as B.1.525 representatives.
