### ISSUE TITLE
Possible recombinant BA.2/A.5 appeared in Asturias. Spain

### ISSUE THREAD

**Issue by VirologiaHUCA** [cov-lineages/pango-designation#701]
Description
Recombinant BA.2/BA.5
One sequence: hCoV-19/Spain/AS-252216209/2022|EPI_ISL_13038062|2022-05-18

<written description of the proposed lineage, where it is circulating, when, why it is distinct>
initially  classified like BA.2 by Pagolin assigner

Genomes
<list of genome names as found on GISAID or accession ids - provide as a CSV/TSV table attachment - include locations and dates of sampling>
BA.2 parents that circulate in Spain and were detected in Asturias between 2022-02-09 and 2022-04-30
EPI_ISL_10796625
EPI_ISL_10412146
EPI_ISL_11390926
EPI_ISL_10070566
EPI_ISL_10070567
EPI_ISL_10358448
EPI_ISL_10358449
EPI_ISL_10647418
EPI_ISL_11162585
EPI_ISL_10903026
EPI_ISL_10903029
EPI_ISL_11162590
EPI_ISL_11353525
EPI_ISL_11755002
EPI_ISL_12107396
EPI_ISL_12222119
EPI_ISL_12222121
EPI_ISL_12502821
EPI_ISL_12511487
EPI_ISL_12589409
EPI_ISL_11247716
EPI_ISL_11247718
EPI_ISL_11247719
EPI_ISL_11247722
EPI_ISL_11247725
EPI_ISL_11247726
EPI_ISL_11247727
EPI_ISL_11247730
EPI_ISL_11247735
EPI_ISL_11247736
EPI_ISL_11247738
EPI_ISL_10252398
EPI_ISL_10967507
EPI_ISL_10967456
EPI_ISL_10967484
EPI_ISL_10967489
EPI_ISL_10967496
EPI_ISL_10967508
EPI_ISL_10967511
EPI_ISL_10967516
EPI_ISL_10967525
EPI_ISL_11247786
EPI_ISL_11247788
EPI_ISL_10967544
EPI_ISL_11247800
EPI_ISL_10967548
EPI_ISL_10967561
EPI_ISL_11220346
EPI_ISL_11220343
EPI_ISL_10967563
EPI_ISL_11247823
EPI_ISL_11220358
EPI_ISL_11247828
EPI_ISL_11220352
EPI_ISL_11247843
EPI_ISL_11247844
EPI_ISL_11247855
EPI_ISL_11247862
EPI_ISL_11247945
EPI_ISL_11247947
EPI_ISL_11247952
EPI_ISL_11247740
EPI_ISL_10252506
EPI_ISL_10967448
EPI_ISL_10967498
EPI_ISL_10967557
EPI_ISL_10967558
EPI_ISL_11220342
EPI_ISL_11220350
EPI_ISL_11247963
EPI_ISL_11247972
EPI_ISL_10967522
EPI_ISL_10967523
EPI_ISL_11247752
EPI_ISL_11247745
EPI_ISL_10872824
EPI_ISL_11253502
EPI_ISL_11253647
BA.5 parents that circulate in Portugal and were detected in Asturias between 2022-04-29 and  2022-05-11
EPI_ISL_12571629
EPI_ISL_12127267
EPI_ISL_12127324
EPI_ISL_12127412
EPI_ISL_12127420
EPI_ISL_12127435
EPI_ISL_12127456
EPI_ISL_12127463
EPI_ISL_12289678
EPI_ISL_12289715
EPI_ISL_12289733
EPI_ISL_12289737
EPI_ISL_12289748
EPI_ISL_12289761
EPI_ISL_12289865
EPI_ISL_12289899
EPI_ISL_12289901
EPI_ISL_12289903
EPI_ISL_12289935
EPI_ISL_12290110
EPI_ISL_12464660
EPI_ISL_12464668
EPI_ISL_12464769
EPI_ISL_12464772
EPI_ISL_12464774
EPI_ISL_12464782
EPI_ISL_12464824
EPI_ISL_12464920
EPI_ISL_12464927
EPI_ISL_12465068
EPI_ISL_12465077
EPI_ISL_12465086
EPI_ISL_12465112
EPI_ISL_12598476
EPI_ISL_12598502
EPI_ISL_12598542
EPI_ISL_12598547
EPI_ISL_12598553
EPI_ISL_12598555
EPI_ISL_12598561
EPI_ISL_12598594
EPI_ISL_12598643
EPI_ISL_12598646
EPI_ISL_12598715
EPI_ISL_12598723
EPI_ISL_12598726
EPI_ISL_12598748
EPI_ISL_12598756
EPI_ISL_12598764
EPI_ISL_12598765
EPI_ISL_12598798
EPI_ISL_12598799
EPI_ISL_12598803
EPI_ISL_12598869
EPI_ISL_12598949
EPI_ISL_12598965
EPI_ISL_12720954
EPI_ISL_12720983
EPI_ISL_12720984
EPI_ISL_12720989
EPI_ISL_12720995
EPI_ISL_12721014
EPI_ISL_12721022
EPI_ISL_12721024
EPI_ISL_12721032
EPI_ISL_12721059
EPI_ISL_12721065
EPI_ISL_12721076
EPI_ISL_12721082
EPI_ISL_12721144
EPI_ISL_12721151
EPI_ISL_12721189
EPI_ISL_12721191
EPI_ISL_12721209
EPI_ISL_12721223
EPI_ISL_12721225
EPI_ISL_12721231
EPI_ISL_12721234
EPI_ISL_12721241
EPI_ISL_12721242
EPI_ISL_12721249
EPI_ISL_12721254
EPI_ISL_12721258
EPI_ISL_12721313
EPI_ISL_12721314
EPI_ISL_12721331
EPI_ISL_12721425
EPI_ISL_12721431
EPI_ISL_12589408
EPI_ISL_12829116
specific mutations of BA.5: C10507C/G12160A, S:L452R/F486V/Q493Q, orf10:L37F
specific mutations of BA.2: S:H69H/V70V; M:N3N; orf6:D61L

**Comment by FedeGueli** [comment]
It should BA.2/BA.5.1/BA.2/BA.5.1 with at least 3 breakpointsis did i goet this correct?

nextstrain:

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_341c4_906820.json

**Comment by silcn** [comment]
As this is just one sequence and there are a lot of apparent breakpoints this looks like it could be contamination, and I'd want to see a second sequence to believe it's a real recombinant. Thoughts?

**Comment by AngieHinrichs** [comment]
Yes; also, if raw data are available and allele frequencies could be examined (for example, as described in https://www.medrxiv.org/content/10.1101/2022.03.09.22272113v1) that would be nice.  As a reminder, the rules for recombinant lineages were recently tweaked to require at least 50 sequences before designating: https://www.pango.network/pango-lineages-guidelines-for-suggesting-novel-and-recombinant-lineages/

**Comment by VirologiaHUCA** [comment]
We agree, more sequences are needed to confirm and designate

**Comment by chrisruis** [comment]
Thanks @VirologiaHUCA I'll close this for now but can reopen if this grows in the future
