### ISSUE TITLE
New BA.2+22792T+ A23767G sublineage with S:H245R, Orf1a:D1600N, Orf3a:D27G, Orf1a:S1493A (358 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#708]
Here i want to propose a new sublineage of BA.2 in the big branch defined by C22792T (that is now  over 500k sequences) with A23767G ( that represents a few less than 5%  of the 22792T branch).

It is defined by : Orf1a:D1600N, Orf3a:D27G, S:H245R, Orf1a:S1493A

Earliest sequences: Switzerland, Uk week 7/2022
(Even if I suspect it has emerged somewhere else, Central America? Carribean?, in a downsampled region and probably it is still common there)
List of Sequences:
[contributors (7).csv](https://github.com/cov-lineages/pango-designation/files/8835979/contributors.7.csv)
Countries: Germany , Belgium, Switzerland, Uk, Usa, Canada, Chile, Brazil, Puerto Rico
[VariantDivisionDistributionChart (1).csv](https://github.com/cov-lineages/pango-designation/files/8835998/VariantDivisionDistributionChart.1.csv)
![Schermata 2022-06-04 alle 00 19 56](https://user-images.githubusercontent.com/87669813/171961732-d50f6597-c389-4a53-9faf-e19a313e2ca1.png)

UShER Tree:
![Schermata 2022-06-04 alle 00 26 36](https://user-images.githubusercontent.com/87669813/171962243-f3ddcd3d-1a1c-4fdc-af26-19f4ef7b287e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39df4_a7ced0.json?branchLabel=aa%20mutations&c=gt-nuc_5063,23767,22296,22792&label=nuc%20mutations:C241T,T670G,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10029T,C10198T,G10447A,C10449A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,C22792T,G22813T,T22882G,G22992A,C22995A,A23013C,A23040G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,A23767G,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,C26577G,G26709A,C26858T,A27259C,G27382C,A27383T,T27384C,C27807T,A28271T,C28311T,G28881A,G28882A,G28883C,A29510C

It shows a [growth disadvantage]( https://cov-spectrum.org/explore/Germany/AllSamples/Past2M/variants?pangoLineage=BA.2.12.1*&aaMutations1=S%3AH245R%2Corf1a%3AD1600N%2Corf3a%3AD27G%2COrf1a%3AS1493A&nucMutations1=A23767G%2CC22792T&analysisMode=CompareToBaseline&) versus BA.2.12.1 inferior to many designated BA.2 sublineages around 38% in Germany:
![Schermata 2022-06-04 alle 00 29 19](https://user-images.githubusercontent.com/87669813/171962487-71b1d399-048c-4f1b-bd60-96da4f6c6e97.png)
While its advantage vs BA.2 baseline appears robust in the most european countries as Germany, Belgium,France, Denmark and instead  much smaller in UK (where baseline is now closer to BA.2.12.1)
![Schermata 2022-06-04 alle 00 33 07](https://user-images.githubusercontent.com/87669813/171962777-621b8da0-771f-49b2-a866-4b5f8d081ada.png)

Covspectrum Comparison : https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?pangoLineage=BA.2*&aaMutations1=S%3AH245R%2Corf1a%3AD1600N%2Corf3a%3AD27G%2COrf1a%3AS1493A&nucMutations1=A23767G%2CC22792T&analysisMode=CompareToBaseline&

**Comment by chrisruis** [comment]
Thanks @FedeGueli As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

There doesn't seem to be a clear epidemiological event associated with this clade, we therefore haven't designated this at this point
