### ISSUE TITLE
Potential BA.1.1/BA.2.23 recombinant with likely breakpoint at NSP3 (70 Seqs as of 2022-06-09 mainly in Brazil)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#709]
This potential recombinant cluster is currently below the 50-sequence bar, I am proposing it based on the consideration that:

- it's growing steadily in Brazil;
- it's recently found in multiple countries in different continents.

### Description
**Recombinant between:** BA.2* & BA.1*
**Earliest sequence:** 2022/4/19 (Brazil-SP)
**Most recent sequence:** 2022/5/23 (Denmark)
**Countries circulating:** Brazil (SP, RS, SC, PR), US (FL, MA), Chile, Israel, Denmark, Germany
**Likely breakpoint:** between 6516 and 8392 (NSP3).
**Mutations on branch:** A12334G, C2857T (homoplasic), C17502T (homoplasic)

**Conserved Nuc mutations** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/171977460-9f664426-6608-4bc5-9e0f-90a900ad1ee3.png)
**Cov-spectrum query:** A12334G, C17502T, C2857T, C2470T, A2832G, A29510C

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/171977705-fa464687-fc6a-4888-9ece-8f00da465e31.png)

**Usher tree (colored by country):**
![image](https://user-images.githubusercontent.com/86835836/171977758-f544600f-cbc6-403a-b262-fdd95a8a8e0c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_403b2_abf740.json?branchLabel=nuc%20mutations&c=country&label=nuc%20mutations:C2857T,A12334G,C17502T

### Genomes:
EPI_ISL_12466895, EPI_ISL_12466896, EPI_ISL_12625119, EPI_ISL_12676437, EPI_ISL_12767869, EPI_ISL_12791146, EPI_ISL_12802643, EPI_ISL_12866465, EPI_ISL_12905769, EPI_ISL_12905770, EPI_ISL_12905791, EPI_ISL_12905800, EPI_ISL_12905801, EPI_ISL_12914680, EPI_ISL_12915955, EPI_ISL_12915960, EPI_ISL_12916001, EPI_ISL_12923253, EPI_ISL_12930313, EPI_ISL_12930575, EPI_ISL_12973487, EPI_ISL_12978268, EPI_ISL_12978284, EPI_ISL_12978285, EPI_ISL_12982335, EPI_ISL_12994226, EPI_ISL_13019646, EPI_ISL_13019647, EPI_ISL_13019648, EPI_ISL_13019649, EPI_ISL_13019650, EPI_ISL_13019651, EPI_ISL_13019652, EPI_ISL_13019653, EPI_ISL_13019803, EPI_ISL_13019814, EPI_ISL_13019819, EPI_ISL_13019829, EPI_ISL_13019832, EPI_ISL_13019835, EPI_ISL_13019838, EPI_ISL_13019844, EPI_ISL_13019849, EPI_ISL_13021123, EPI_ISL_13021124, EPI_ISL_13049370, EPI_ISL_13068320

**Comment by c19850727** [comment]
As new sequences popping out it seems that my original proposal was too deep into the tree. It should branch off at A12334G:
![image](https://user-images.githubusercontent.com/86835836/172539390-2f7f06e9-18a8-4ce0-a989-bd55000d6c24.png)

Therefore the revised covspectrum query would be: A12334G, C2857T, C2470T, A2832G, A29510C

And the genomes as of 2022-06-07 is as follows:
EPI_ISL_12466895-12466896, EPI_ISL_12625119, EPI_ISL_12676437, EPI_ISL_12791146, EPI_ISL_12802643, EPI_ISL_12866465, EPI_ISL_12905769-12905770, EPI_ISL_12905791, EPI_ISL_12905800, EPI_ISL_12914680, EPI_ISL_12915955, EPI_ISL_12915960, EPI_ISL_12916001, EPI_ISL_12923253, EPI_ISL_12930313, EPI_ISL_12930575, EPI_ISL_12978268, EPI_ISL_12978284-12978285, EPI_ISL_12982335, EPI_ISL_12994226, EPI_ISL_13019646-13019653, EPI_ISL_13019803, EPI_ISL_13019814, EPI_ISL_13019829, EPI_ISL_13019832, EPI_ISL_13019835, EPI_ISL_13019844, EPI_ISL_13019849, EPI_ISL_13021123-13021124, EPI_ISL_13049370, EPI_ISL_13068320, EPI_ISL_13107297, EPI_ISL_13111708, EPI_ISL_13112517, EPI_ISL_13112574, EPI_ISL_13127996, EPI_ISL_13128039, EPI_ISL_13128178, EPI_ISL_13131780, EPI_ISL_13131785, EPI_ISL_13131817-13131818, EPI_ISL_13131821-13131822, EPI_ISL_13131831, EPI_ISL_13131838, EPI_ISL_13131846, EPI_ISL_13131857, EPI_ISL_13132642, EPI_ISL_13148389, EPI_ISL_13153242, ON656807.1

**Comment by alex-ranieri** [comment]
We've been watching this potential recombinant. Those sequences have been labeled as XQ by nextclade. We were suspicious about it, then we build a tree with some recombinants: 
![XBR_Unassigned_Recombinant_Tree](https://user-images.githubusercontent.com/94479933/172936130-4ea737ce-3f5e-45dd-9502-a95931662dc0.png)

Brazilian sequences are marked in red. We noticed that this potential recombinant cluster is close to XG. 
We sequenced a few more samples in São Paulo that have the mutational profile of this potential recombinant. We'll upload them to GISAID as soon as possible.

**Comment by corneliusroemer** [comment]
Interesting!

How many private mutations, in particular reversions with respect to XQ?
Nextclade will pick the nearest pango lineage and that can be a similar but
not identical recombinant as you will know.

**Comment by c19850727** [comment]
@corneliusroemer The breakpoint is different.

**Comment by c19850727** [comment]
70 sequences as of 2022-06-09, and newly found in Mexico.

**Comment by c19850727** [comment]
Also newly found in Japan ex-Brazil (EPI_ISL_13167907).

**Comment by Gabitech35** [comment]
Hi, I'm from the Butantan Institute and I work with alex-ranieri. 
We performed some more analysis with new sequences and it was possible to verify that the following sequences: EPI_ISL_13253949, EPI_ISL_13253948, EPI_ISL_13253954, EPI_ISL_13253953, EPI_ISL_13253952, EPI_ISL_13253950. They are part of this new recombinant clade emerging in Brazil.

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as lineage XAG
