### ISSUE TITLE
 BA.5 branch with C1627T ( without A28830G and A27038G)  166 sequences dominating in Eswatini and spread to multiple countries 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#717]
As mentioned in #657:

"... there is also a BA.5 sublineage with C1627T without A28830G just 150 sequences but well spread in different countries
![Schermata 2022-06-04 alle 18 11 56](https://user-images.githubusercontent.com/87669813/172015299-3653fa48-95b0-4daa-a3e5-e41b898eb828.png)

Here the usher link:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2da4d_b7e7e0.json?branchLabel=nuc%20mutations&c=country&label=nuc%20mutations:C1627T

_Originally posted by @FedeGueli in https://github.com/cov-lineages/pango-designation/issues/657#issuecomment-1146643135_ 
"

There is an undesignated branch of BA.5 with C1627T (and with 28830A and 27038A to distinguish it from.BA.5.2.1) that i think it is worth designating cause it is circulating in multiple countries:
South Africa Eswatini (where it seems to be over 50% of total sequences in the last weeks)
United States Uk Norway Belgium Canada Australia Mauritius Israel
![chrome_screenshot_1654453319499](https://user-images.githubusercontent.com/87669813/172064953-94a3fdab-9548-4bd7-968b-656b09140ac9.png)
Prevalence in Eswatini:
![chrome_screenshot_1654453823240](https://user-images.githubusercontent.com/87669813/172065307-4a5e1ed9-54f7-4c87-a69b-4d1f00ecf1a4.png)

Defining mutation: C1627T
Tree:
![chrome_screenshot_1654452599444](https://user-images.githubusercontent.com/87669813/172064945-8c6d4c92-d2c0-44c2-b933-cffad8d76f20.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37c59_ce7fb0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C1627T

Covspectrum query (1627T, 28330A, G12160A + N:151P): 

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=N%3A151P&nucMutations=1627T%2C28330A%2CG12160A&

List of sequences:
[contributors (4).csv](https://github.com/cov-lineages/pango-designation/files/8840515/contributors.4.csv)

**Comment by AngieHinrichs** [comment]
As I [commented](https://github.com/cov-lineages/pango-designation/issues/657#issuecomment-1147701038) in #657 I think this is actually the parent branch of BA.5.2, and the 2022-06-06 tree will reflect that (should be out in a bit less than 6 hours).  C1527T does not cause a coding change so under current rules it is not eligible to be designated as a lineage anyway.  [Not my favorite rule, because humongous branches like BA.2 > C22792T are ineligible, despite having something to say about which BA.2 sublineages are more closely related than others... and the virus genome is an RNA so that's got to matter now and then, although hand-wavy statements like that are worthless without structural predictions & actual evidence. 🙂]  Thanks again for bringing attention to it!

**Comment by agamedilab** [comment]
C1627T now appears to be parental to the node. So the order would be:

BA.5+C1627T->BA.5.2->BA.5.2.1->BF.1?

![grafik](https://user-images.githubusercontent.com/102166254/172311470-1100b72d-4a3d-44ce-bbd9-7627e66e8e1f.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1882b_eecee0.json?branchLabel=nuc%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C241T,T670G,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,C27807T,C27889T,A28271T,C28311T,G28881A,G28882A,G28883C,A29510C

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs very much for looking at this.
Yes agree with what you said, probably for new dominant lineages the non coding/no designation rule causes less defined trees, also at the beginning we cant know where fittier lineages will evolve from  and it is a pity cause i already see other branches with more than 50 sequences clearly defined by synonymous mutations:
As G29032A or T4906C+T18957C.

Couldnt we try another way, like an exception, with BA.5 and see how it works? 

cc
@corneliusroemer @chrisruis @InfrPopGen @tompeacock

In the meanwhile i close this one as completed
