### ISSUE TITLE
BA.5.2 sublineage with G12310A, ORF1b:T1050N (260 seq., Bahrain, South Africa, UK)  

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#724]
Proposal for a sublineage of BA.5.2
Earliest sequence: 04.08.2022 (South Africa)
Countries detected: mostly Bahrain (35 %), South Africa (15%), UK (15%), Australia, Austria, Belgium, Brazil, Canada, CzechRepublic, Denmark, France, Germany, India, Israel, Japan, Jordan, Liechtenstein, Malaysia, Martinique, Netherlands, Philippines, Singapore, Spain, USA.

Defining mutations:
G12310A
C16616A = ORF1b:T1050N

This variant is defined by G12310A, ORF1b:T1050N and was first detected in South Africa and multiple other countries. It is currently most common in Bahrain. Note, most of those sequences are derived from Genbank via Usher. There are not much recent genomes from Bahrain on GISAID at the moment.

This variant is apparently a sublineage of BA.5.2 (see also #717, #657).
![pic1](https://user-images.githubusercontent.com/102166254/172372240-c8a65b08-4bb7-4a4a-ac5c-88d5221e5d45.PNG)
![pic2](https://user-images.githubusercontent.com/102166254/172372253-dc47a708-c6c6-4381-b582-425d4ffd4903.PNG)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28203_f340a0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G12310A

[nextstrain_fetch_genome.csv](https://github.com/cov-lineages/pango-designation/files/8852881/nextstrain_fetch_genome.csv)

**Comment by chrisruis** [comment]
Thanks @agamedilab As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

There doesn't seem to be a clear epidemiological event associated with this clade, we therefore haven't designated this at this point

**Comment by FedeGueli** [comment]
true @olias120676 
cc @chrisruis 
This is one of the fastest BA.5 sublineages currently around +30% vs BA.5 baseline in UK.

**Comment by agamedilab** [comment]
@olias120676 @FedeGueli Thanks a lot for pointing this out!
@chrisruis

Currently there are about 455 sequences on GISAID and Genbank combined according to Usher as of 14.06.22.

GISAID:
EPI_ISL_12097406, EPI_ISL_12097408, EPI_ISL_12268513, EPI_ISL_12278971, EPI_ISL_12278976, EPI_ISL_12473876, EPI_ISL_12474466, EPI_ISL_12474467, EPI_ISL_12559415, EPI_ISL_12559419, EPI_ISL_12559429, EPI_ISL_12559433, EPI_ISL_12559440, EPI_ISL_12585892, EPI_ISL_12610590, EPI_ISL_12636044, EPI_ISL_12649069, EPI_ISL_12695015, EPI_ISL_12695022, EPI_ISL_12695023, EPI_ISL_12705907, EPI_ISL_12705913, EPI_ISL_12708585, EPI_ISL_12708589, EPI_ISL_12741203, EPI_ISL_12741203, EPI_ISL_12763789, EPI_ISL_12767816, EPI_ISL_12767850, EPI_ISL_12769205, EPI_ISL_12769206, EPI_ISL_12769208, EPI_ISL_12810220, EPI_ISL_12824788, EPI_ISL_12845535, EPI_ISL_12845539, EPI_ISL_12845544, EPI_ISL_12845545, EPI_ISL_12845546, EPI_ISL_12845549, EPI_ISL_12845551, EPI_ISL_12845553, EPI_ISL_12845557, EPI_ISL_12845558, EPI_ISL_12845568, EPI_ISL_12845574, EPI_ISL_12845592, EPI_ISL_12851724, EPI_ISL_12856602, EPI_ISL_12870458, EPI_ISL_12870485, EPI_ISL_12870533, EPI_ISL_12872614, EPI_ISL_12875216, EPI_ISL_12898277, EPI_ISL_12898278, EPI_ISL_12903434, EPI_ISL_12903571, EPI_ISL_12903676, EPI_ISL_12903721, EPI_ISL_12904183, EPI_ISL_12911904, EPI_ISL_12911905, EPI_ISL_12915617, EPI_ISL_12922987, EPI_ISL_12960590, EPI_ISL_12972929, EPI_ISL_12972930, EPI_ISL_12972931, EPI_ISL_12972932, EPI_ISL_12972933, EPI_ISL_12972934, EPI_ISL_12993641, EPI_ISL_13010893, EPI_ISL_13010894, EPI_ISL_13013292, EPI_ISL_13015006, EPI_ISL_13015031, EPI_ISL_13015796, EPI_ISL_13025776, EPI_ISL_13029967, EPI_ISL_13036593, EPI_ISL_13037707, EPI_ISL_13040622, EPI_ISL_13041183, EPI_ISL_13041272, EPI_ISL_13044482, EPI_ISL_13050042, EPI_ISL_13051385, EPI_ISL_13051430, EPI_ISL_13051434, EPI_ISL_13051456, EPI_ISL_13051470, EPI_ISL_13053560, EPI_ISL_13055742, EPI_ISL_13058645, EPI_ISL_13059699, EPI_ISL_13059701, EPI_ISL_13064563, EPI_ISL_13066928, EPI_ISL_13070590, EPI_ISL_13072446, EPI_ISL_13072679, EPI_ISL_13073911, EPI_ISL_13076820, EPI_ISL_13077238, EPI_ISL_13077332, EPI_ISL_13077351, EPI_ISL_13090168, EPI_ISL_13090960, EPI_ISL_13091150, EPI_ISL_13094131, EPI_ISL_13094158, EPI_ISL_13094163, EPI_ISL_13094181, EPI_ISL_13094195, EPI_ISL_13102047, EPI_ISL_13102158, EPI_ISL_13102187, EPI_ISL_13107276, EPI_ISL_13109539, EPI_ISL_13109540, EPI_ISL_13110644, EPI_ISL_13110786, EPI_ISL_13110813, EPI_ISL_13111171, EPI_ISL_13111227, EPI_ISL_13113454, EPI_ISL_13113463, EPI_ISL_13121158, EPI_ISL_13124211, EPI_ISL_13125378, EPI_ISL_13131087, EPI_ISL_13131212, EPI_ISL_13133115, EPI_ISL_13133247, EPI_ISL_13134188, EPI_ISL_13134758, EPI_ISL_13135610, EPI_ISL_13137116, EPI_ISL_13137129, EPI_ISL_13137131, EPI_ISL_13137137, EPI_ISL_13140777, EPI_ISL_13140787, EPI_ISL_13140802, EPI_ISL_13140803, EPI_ISL_13140804, EPI_ISL_13140805, EPI_ISL_13140806, EPI_ISL_13140807, EPI_ISL_13140808, EPI_ISL_13140809, EPI_ISL_13140810, EPI_ISL_13140811, EPI_ISL_13141006, EPI_ISL_13144607, EPI_ISL_13147822, EPI_ISL_13148138, EPI_ISL_13148423, EPI_ISL_13148426, EPI_ISL_13148427, EPI_ISL_13149258, EPI_ISL_13150721, EPI_ISL_13150722, EPI_ISL_13150723, EPI_ISL_13150728, EPI_ISL_13150731, EPI_ISL_13150734, EPI_ISL_13150739, EPI_ISL_13150743, EPI_ISL_13150746, EPI_ISL_13150748, EPI_ISL_13150751, EPI_ISL_13150756, EPI_ISL_13154449, EPI_ISL_13155754, EPI_ISL_13156442, EPI_ISL_13156457, EPI_ISL_13158162, EPI_ISL_13158211, EPI_ISL_13159506, EPI_ISL_13159537, EPI_ISL_13159542, EPI_ISL_13163708, EPI_ISL_13167847, EPI_ISL_13167989, EPI_ISL_13168083, EPI_ISL_13168127, EPI_ISL_13168997, EPI_ISL_13168999, EPI_ISL_13169024, EPI_ISL_13175001, EPI_ISL_13175004, EPI_ISL_13175006, EPI_ISL_13175522, EPI_ISL_13176355, EPI_ISL_13176610, EPI_ISL_13176937, EPI_ISL_13177313, EPI_ISL_13177315, EPI_ISL_13178463, EPI_ISL_13178626, EPI_ISL_13182295, EPI_ISL_13182299, EPI_ISL_13182319, EPI_ISL_13182333, EPI_ISL_13183088, EPI_ISL_13191425, EPI_ISL_13197956, EPI_ISL_13198072, EPI_ISL_13198767, EPI_ISL_13198787, EPI_ISL_13208025, EPI_ISL_13208037, EPI_ISL_13211382, EPI_ISL_13211383, EPI_ISL_13211410, EPI_ISL_13214648, EPI_ISL_13217382, EPI_ISL_13217556, EPI_ISL_13217722, EPI_ISL_13217774, EPI_ISL_13217785, EPI_ISL_13223978, EPI_ISL_13223998, EPI_ISL_13227127, EPI_ISL_13227129, EPI_ISL_13227152, EPI_ISL_13227164, EPI_ISL_13228706, EPI_ISL_13229890, EPI_ISL_13230431, EPI_ISL_13230439

Genbank:
ON606065.1, ON606067.1, ON606069.1, ON606141.1, ON606142.1, ON606143.1, ON606146.1, ON606167.1, ON606168.1, ON606169.1, ON606172.1, ON606173.1, ON606174.1, ON606374.1, ON606379.1, ON606388.1, ON606397.1, ON606398.1, ON606400.1, ON606402.1, ON606403.1, ON606408.1, ON606425.1, ON609310.1, ON627267.1, ON627290.1, ON627297.1, ON627298.1, ON627299.1, ON627302.1, ON627303.1, ON627305.1, ON627306.1, ON627312.1, ON627314.1, ON627315.1, ON627321.1, ON627322.1, ON627323.1, ON627324.1, ON627325.1, ON627327.1, ON627328.1, ON627340.1, ON627415.1, ON627419.1, ON627422.1, ON627430.1, ON627439.1, ON627445.1, ON627446.1, ON627449.1, ON627451.1, ON627452.1, ON627453.1, ON627454.1, ON627456.1, ON627457.1, ON627458.1, ON627459.1, ON627462.1, ON627473.1, ON627491.1, ON627494.1, ON627513.1, ON627515.1, ON627519.1, ON627520.1, ON627521.1, ON627523.1, ON627527.1, ON627528.1, ON627537.1, ON627540.1, ON627541.1, ON627542.1, ON627543.1, ON627544.1, ON627545.1, ON627568.1, ON627577.1, ON627578.1, ON629617.1, ON629623.1, ON629632.1, ON629636.1, ON629645.1, ON629653.1, ON629674.1, ON629677.1, ON629686.1, ON629692.1, ON629701.1, ON659279.1, ON659728.1, ON660865.1, ON674322.1, ON674459.1, ON675765.1, ON678482.1, ON688802.1, ON689057.1, ON691668.1, ON691823.1, ON691831.1, ON694658.1, ON694866.1, ON709995.1, ON711423.1, ON719096.1, ON719226.1, ON719438.1, ON719825.1, ON726326.1, ON732018.1


[nextstrain_fetch_genome.ucsc.edu_trash_ct_subtreeAuspice1_genome_e2b3_81f160.json_metadata.csv](https://github.com/cov-lineages/pango-designation/files/8896816/nextstrain_fetch_genome.ucsc.edu_trash_ct_subtreeAuspice1_genome_e2b3_81f160.json_metadata.csv)

Growth advantage  vs. BA. 5.2 in UK:

![grafik](https://user-images.githubusercontent.com/102166254/173504999-24d3c8a3-b8fb-4ac4-bb91-475914076195.png)

**Comment by agamedilab** [comment]
Currently there are about 827 sequences according to Usher as of 17.06.22.

![grafik](https://user-images.githubusercontent.com/102166254/174237360-0fca9901-b4ef-44e7-949b-920f4fe09584.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9e93_c19da0.json?branchLabel=aa%20mutations&c=gt-nuc_16616,12310&label=nuc%20mutations:C16616A

**Comment by FedeGueli** [comment]
I can confirm this is the 2nd fastest BA.5 sublineage circulating after the one with N:151S.
Cc @chrisruis @AngieHinrichs @InfrPopGen @corneliusroemer  this should be at least reopen and probably designated as the other BA.5.2 sublineages (i dont see any less relevant epidemiological event here in comparison to the ones alteady designated which are apparently less trasmissible than this one)

**Comment by corneliusroemer** [comment]
If you add a covSPECTRUM query to back up your screenshots and analyses it's much easier to investigate and check @agamedilab @olias120676 @FedeGueli 

I may be blind but I haven't seen one here in this issue (yet)

**Comment by FedeGueli** [comment]
@corneliusroemer you re perfectly right.

here: 

https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past2M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=Orf1b%3A1050N&nucMutations1=12310A&analysisMode=CompareToBaseline&

**Comment by agamedilab** [comment]
Currently there are about 2962 sequences according to Usher as of 27.06.22 representing c. 7.2 % of global BA.5 (2962/41105).

![grafik](https://user-images.githubusercontent.com/102166254/175909608-d4a18eeb-cb37-4082-8913-04e9fadbb12b.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28441_960680.json?branchLabel=aa%20mutations&c=gt-nuc_16616


Advantage versus global BA.5:
![grafik](https://user-images.githubusercontent.com/102166254/175886990-562ee9a8-781b-4c79-9a01-8fcd96a06ffc.png)
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=Orf1b%3A1050N&nucMutations1=12310A&analysisMode=CompareToBaseline&

**Comment by Sinickle** [comment]
Looks like 12% growth advantage now over BA.5*, and it makes up 15% of global sequences currently.

**Comment by agamedilab** [comment]
Hi @Sinickle many thanks for pointing this out! Also @FedeGueli for issue #890. 

This sublineage is defined by sustained growth advantage compared to co-circulating lineages. I think it would have been a good canditate to designate early on.

Would it still make sense to designate it now @chrisruis @corneliusroemer @InfrPopGen ?

Growth advantage vs. BA.5* global 6 months:
![grafik](https://user-images.githubusercontent.com/102166254/184298008-00c95056-d53e-44eb-87d3-34ad75dd65b8.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.5*&aaMutations1=Orf1b%3A1050N&nucMutations1=12310A&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&
