### ISSUE TITLE
New BA.1 with S:E340K + S:R346T + S:I670M + S:G885S + S:F375S (reversion)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#729]
I'd like to propose a new sublineage of BA.1 that seems to be circulating in Spain. It's defined by the nucleotide mutations G22580A, G22599C, A23572G, and G24215A, with AA mutations S:E340K, S:R346T, S:I670M, S:G885S, and the reversion S:F375S. Additional mutations pile up quickly at each subsequent branch. A side branch with only one sequence (collected on 2022-4-27) has spike mutations S:L452M, S:I670L, and S:D936Y. The main branch continues, with the next branch containing five mutations—ORF1a:P1213L (NSP3_P395L), ORF1b:T730I (NSP12_T739I), ORF3a:T175I, E:F23L, and the RBD reversion S:P371S. One subsequent branch contains two sequences with the additional spike mutation S:K340Q, while one of those one sequences also has S:L822F. 

The earliest sequences was collected on April 24 and the most recent on May 22. Oddly, both of these are on the upper-right branch of the subtree and have more mutations than the rest of the tree.

It's clear that these are all different patients, with the probable exception of the two sequences on the ORF1a:T1001I branch. Given the E340K and subsequent K340Q mutations here, I think there's a high probability at least some of these individuals were treated with Sotrovimab and developed resistance mutations that were subsequently passed on to others, resulting in community circulation. 

EPI_ISL_12601652
EPI_ISL_13011167
EPI_ISL_13134262
EPI_ISL_12704498
EPI_ISL_12704500
EPI_ISL_12704499

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d0f_f72980.json?branchLabel=aa%20mutations&c=pango_lineage&label=nuc%20mutations:G22580A
![Screen Shot 2022-06-07 at 4 05 17 PM](https://user-images.githubusercontent.com/33738461/172472496-30aabe01-2114-431d-bb43-cd7115c5f983.png)

**Comment by silcn** [comment]
This is a duplicate of #666

**Comment by ryhisner** [comment]
Ah, I didn't catch that one! Thanks, silcn.
