### ISSUE TITLE
Request for B.1.1.482 Sub-lineage

### ISSUE THREAD

**Issue by mattdmem** [cov-lineages/pango-designation#73]
### Description

**Sub-lineage of:** B.1.1.482
**Earliest sequence:** March/April 2021
**Most recent sequence:** May 2021
**Countries circulating:** France, UK

Around 11 cases of B.1.1.482 have been discovered in the UK in the last few weeks with a significant amount of new mutations when compared with B.1.1.482 from earlier in the pandemic. These include mutations in Spike and Nsp6 which are also found in many VOCs/VUIs (Table 1). 

Genomic Region | Protein | Amino Acid
-- | -- | --
ORF1a | NSP1 | D75G
ORF1a | NSP2 | G339S, A411V
ORF1a | NSP3 | H342Y, P822L, K927I, N1587S
ORF1a | NSP4 | A446V
ORF1a | NSP6 | △106-108
ORF1b | NSP12 | **P323L**, S434A
ORF1b | NSP13 | T481M
ORF1b | NSP14 | A119V
S | Spike | D80G, T95I, G142D, △144, N439K, E484K, **D614G**, P681H, I1130V, D1139H
M | Membrane | A63T, **H125Y**
N | Nucleocapsid | I157V, **R203K**,**G204R**,

_**Table 1. Mutations common (n=28) to B.1.1.482 samples from the South Yorkshire Region.** 
Mutations overlapping B.1.1.482 from North America and Asia highlighted in bold._

### Evidence

It's clear from the phylogenetic tree (Figure 1) that these samples have diverged significantly from samples of this lineage earlier in the pandemic. The new UK sequences are clustered in South Yorkshire, UK, and seem to be closely related to a sample sequenced in France of the same lineage (EPI_ISL_1582709) in late march, sharing many of the new mutations. 

![image](https://raw.githubusercontent.com/sheffield-bioinformatics-core/b11482/master/B11482%2BSHEF.png)

_**Figure 1. Maximum likelihood Phylogenetic Tree of 48 B.1.1.482 Samples**
A multiple sequence alignment was performed on B.1.1.482 samples using MAFFT v.7.477.  The maximum likelihood phylogenetic tree was produced using IQ-TREE v.2.1.2 with GTR + G model and 1,000 ultrafast bootstrap replicates. Red tips denote B.1.1.482 from England._

### Genomes

GISAID/Alternative ID | Region | Date of Collection
--|--|--
EPI_ISL_1582709 | France | 2021-03-28
EPI_ISL_1698537 | UK | 2021-04-14
EPI_ISL_1857609 | UK | 2021-04-27
EPI_ISL_1857666 | UK | 2021-04-27
EPI_ISL_1857753 | UK | 2021-04-27
EPI_ISL_1857951 | UK | 2021-04-27
EPI_ISL_1912100 | UK | 2021-04-26
SHEF-10DA497 | UK | 2021-04-28
SHEF-10E58AC | UK | 2021-04-30
SHEF-10DC3F2 | UK | 2021-04-30
PHEC-30B21B | UK | Unknown

### Authors

Sharon Hsu and Matthew D Parker, Benjamin B Lindsey, Amy State, Peijun Zhang, Benjamin H Foulkes, Stavroula F Louka, Paige Wolverson, Marta Gallis, Hailey R Hornsby, Max Whiteley, Samantha E Hansford1, Nasar Ali, Oscar Shepherdson, Salma Afsar, Katie Johnson, Alexander J Keeley, Joe Heffer, Nikki Smith, David G Partridge, Alison Cope, Michael Ankcorn, Mohammad Raza, Cariad Evans, The COVID-19 UK Genomics Consortium, Thushan I de Silva

It would be great if this child of B.1.1.482 is assigned a lineage definition for easier identification.

Thanks

**Comment by grovesn** [comment]
also QEUH-148F257, QEUH-14C1E55, QEUH-144D7A1. These are a separate cluster but the same spike profile.

**Comment by mattdmem** [comment]
@grovesn Thanks! These look more similar to the French one

**Comment by grovesn** [comment]
![B 1 1 482_all rooted ctree](https://user-images.githubusercontent.com/15730790/117579836-ac096780-b0ec-11eb-984d-6d9ff8d43fdc.png)

**Comment by chrisruis** [comment]
Hi @mattdmem thanks for submitting this. We've added this as lineage AV.1 (an alias of B.1.1.482.1 as the parental B.1.1.482 lineage already has the maximum of 3 sublevels in it's lineage name) in [1.2.1](https://github.com/cov-lineages/pango-designation/releases/tag/1.2.1)

I've included samples England/QEUH-148F257/2021 and England/QEUH-14C1E55/2021 that @grovesn added above. We've introduced a requirement for designated sequences to have <5% ambiguities in the coding regions - England/QEUH-144D7A1/2021 is a little above this so wasn't included in the designations. I haven't yet added SHEF-10E58AC and SHEF-10DC3F2 to the designations as I can't find them in the current alignments to check their ambiguities - I'll have another look in a couple of days and hopefully add them in then

**Comment by mattdmem** [comment]
@chrisruis

Updated list of samples that fall in this sub-lineage:

```
ALDP-1543D8A
ALDP-154D5B5
ALDP-1555F07
ALDP-1557F6F
ALDP-1558E25
ALDP-155C6DE
ALDP-155C86F
CAMC-1507EE9
MILK-1541FD1
MILK-154CAC6
MILK-155DA68
NORT-1BA57A0
PHEC-30B21B
QEUH-153D6F1
QEUH-1540F5A
QEUH-1541092
QEUH-154128D
QEUH-1543115
SHEF-10DA497
SHEF-10DC3F2
SHEF-10E58AC
```

**Comment by MattBashton** [comment]
Just to add these two sequences also look to be part of this sub-lineage, but have in addition an ORF3a deletion via frameshift deletion: c.766_769del:p.V256Ifs*3 (26158  26161  GTTA       -) :

```
NORT-1BB90F9
NORT-1BB9132
```
