### ISSUE TITLE
New BA.5 +C1627T sublineage defined by G2202T (Orf1a:W646L) and A26295T (33 Sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#730]
Trying to describe other sublineages of the branch starting with C1627T I found one i think it is worth to be monitored here, cause it started to circulate outside South Africa in May with little clusters sampled in England Belgium (with additional Non synonymous mutation) and it has been sampled sparsely in Usa

Defining mutations: C1627T + G2202T (Orf1a:W646L) + A26295T
Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42c4a_fbd1d0.json?branchLabel=aa%20mutations&c=gt-nuc_1627,2202,26295&label=nuc%20mutations:G2202T,A26295T
![Schermata 2022-06-08 alle 00 01 20](https://user-images.githubusercontent.com/87669813/172491178-114aacb7-ed64-4895-ace2-ae0c76154ca3.png)

Nr of Sequences: 33
List of sequences
[contributors (28).csv](https://github.com/cov-lineages/pango-designation/files/8856870/contributors.28.csv)

First sequence: Scotland/QEUH-3D68228/2022|OW663477.1|2022-04-14
Countries:
![Schermata 2022-06-08 alle 00 08 00](https://user-images.githubusercontent.com/87669813/172491309-aacc702a-8370-4688-9b3c-725d2f83ab6f.png)

Cov Spectrum Overview:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A486V%2CM%3A3N%2CS%3A452R&nucMutations=G12160A%2CG2202T%2CA26295T%2CC1627T&

**Comment by chrisruis** [comment]
Thanks @FedeGueli As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

There doesn't seem to be a clear epidemiological event associated with this clade, we therefore haven't designated this at this point
