### ISSUE TITLE
Norwegian BA.5 Sublineage with C1627T+A10348G, C5622T (Orf1a:P1786L), T3571G (Orf1a:S1102R)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#731]
From the C1627 branch of BA..5 evolved another small sublineage that seems on the rise in Norwegian and have been exported to USA with an additional rbd mutation (S:460S).
It is defined by 4 mutations_ C1627T + A10438G then acquired Orf1a:P1786L and Orf1a:S1102R
Tree:
![Schermata 2022-06-08 alle 00 27 05](https://user-images.githubusercontent.com/87669813/172493552-dce64a57-3b2c-42d2-bc2f-ef099f6c5731.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43aae_fbdad0.json?branchLabel=aa%20mutations&c=gt-nuc_1627,3571,5622,10348&label=nuc%20mutations:A10348G

Cov-spectrum query:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A486V%2CM%3A3N%2CS%3A452R&nucMutations=G12160A%2CC1627T%2CA10348G%2CC5622T%2CT3571G&

Number of sequences:20
List of sequences:
[contributors (29).csv](https://github.com/cov-lineages/pango-designation/files/8856938/contributors.29.csv)
First sequence: Norway/OUS-25155/2022|EPI_ISL_12983022|2022-05-01
Countries:
![Schermata 2022-06-08 alle 00 29 35](https://user-images.githubusercontent.com/87669813/172493837-833c605a-e389-4ed0-a6aa-e24e1e301757.png)

**Comment by chrisruis** [comment]
Thanks @FedeGueli As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

There doesn't seem to be a clear epidemiological event associated with this clade - there's a few Scandinavian sequences but it's also quite widespread. We therefore haven't designated this at this point

**Comment by FedeGueli** [comment]
103 seqs as today. growing steadily although apparently less than other BA.5 sublineages.
No new epi event associated however  i'll keep this monitored.

**Comment by FedeGueli** [comment]
Hi @chrisruis @AngieHinrichs ie  @corneliusroemer @InfrPopGen i want to highlight a possible significant epi event for this sublineage:
it acquired further S:N460S ( thx @ryhisner who spotted that mutation) while being exported to Ireland.
That cluster of interest counts 42 sequences and now it has been seeded in Ireland, Usa, Chile, France, Germany Scotland:
![Schermata 2022-06-30 alle 02 26 12](https://user-images.githubusercontent.com/87669813/176567511-9c2d8968-0473-4186-9b5d-ac4b98ba9336.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_27402_ce9ec0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A22941G

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=M%3A3N%2Corf1a%3AS1102R%2Corf1a%3AP1786L%2CS%3AN460S&nucMutations=G12160A%2CC1627T%2CA10348G&pangoLineage=BA.5&aaMutations1=M%3A3N%2CS%3AN460S&nucMutations1=G12160A%2CC1627T&

Let me know if you think it is better to reopen a new issue with that sublineage of this only. Thank You!
