### ISSUE TITLE
BA.2 sublineage with S:69/70del, S:E340K, S:K356T, S:L452R, S:R493Q, S:D936H (26 seq as of 2022-07-01, Ireland/various European countries/US)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#732]
Proposal for a sublineage of BA.2
Earliest sequence: 2022-05-02 (Ireland)
Countries detected: Ireland (4 seq), Spain (1 seq)

Mutations on top of BA.2:
S:69/70del, E340K, K356T, L452R, R493Q (reversion), D936H
ORF1a:T3356I
ORF3a:G100V
E:L21F
M:S4F
(this is actually on a branch of BA.2+C22792T with over 160 sequences where 22792T has reverted back to C)

Sequences:
EPI_ISL_12624715
EPI_ISL_13036609
EPI_ISL_13147723 (has additional S:L752F)
EPI_ISL_13147735
EPI_ISL_13147550

This is another small lineage with lots of spike mutations that seems to be in general circulation, as it has been found in 4 different regions of Ireland as well as one sequence in Spain. There is some striking convergent evolution with BA.4/5. It seems fairly diverse too so there is presumably a lot more around than we're currently seeing.

The Usher tree is messed up by one sequence (EPI_ISL_12624715) with a dropout around S:452. In order to correct the tree I uploaded a fasta where I copied the dropout region from another sequence, but Usher still has the old EPI_ISL_12624715 without S:L452R, which you can ignore. S:D936H occurred before the other S mutations in a single sequence from New York. The rest all appeared together, including 69/70del which doesn't show up on Usher.

<img width="699" alt="Ireland_E340K" src="https://user-images.githubusercontent.com/42699509/172500998-6741e04e-0df8-422d-a819-510898b7343c.png">

[https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2dfe6_fdd680.json?branchLabel=Spike%20mutations&c=gt-S_340&label=nuc%20mutations:G24368C](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2dfe6_fdd680.json?branchLabel=Spike%20mutations&c=gt-S_340&label=nuc%20mutations:G24368C)

**Comment by Sinickle** [comment]
Just a bit ago I did a review of all sequences with 3 of ([S:69-& S:70-], S:452X, S:486V, S:493Q) that aren't BA.4/BA.5 and had multiple sequences with circulation in May -- I believe there's only this branch and then one other branch. 

So, the BA.4/BA.5 convergent evolution stands out quite a lot on its own. 

In addition, mutations at S:340 are associated with [Sotromivab resistance](https://www.nejm.org/doi/full/10.1056/NEJMc2120219), and Bloom Lab [claims](https://www.nejm.org/doi/full/10.1056/NEJMc2120219) that S:356 is likely a very heavily targeted site for immune response in folks who've had a breakthrough BA.1 infection.

**Comment by FedeGueli** [comment]
Great we are all on the same clusters of interests!  @Sinickle was monitoring this as it was a couplet,  same for you and Ryan and Sam and you for the other two .

**Comment by ryhisner** [comment]
With the E340K mutation, I suspect this is another sotrovimab-driven sublineage, many of which seem to also have S:D936H, though I don't know if there's any significance to that.

**Comment by silcn** [comment]
4 more sequences from Ireland, all sampled 2022-05-24:
EPI_ISL_13178206
EPI_ISL_13186252
EPI_ISL_13186634
EPI_ISL_13186649

Usher tree is cleaner now as the 452-dropout sequence is showing as an erroneous reversion on the correct branch.

<img width="697" alt="pango732_0609" src="https://user-images.githubusercontent.com/42699509/172944199-22c8168a-ad80-40da-8442-037350e01c89.png">

[https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4134d_25cdb0.json?branchLabel=Spike%20mutations&c=userOrOld&label=nuc%20mutations:G22580A,A22629C,T22917G,G23040A,G25691T,C26533T](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4134d_25cdb0.json?branchLabel=Spike%20mutations&c=userOrOld&label=nuc%20mutations:G22580A,A22629C,T22917G,G23040A,G25691T,C26533T)

This lineage makes up 6 out of 243 sequences (2.5%) from week 21 in Ireland so far. Geographically it's spread all over Ireland. Too early to plot growth advantages of course, but for future reference here's a cov-spectrum query, allowing any mutation at S:340 because of the tendency for E -> K -> Q to happen:

[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=S%3A340+%26+S%3A356T+%26+S%3A936H+%26+E%3AL21F+%26+M%3AS4F+%26+ORF3a%3AG100V&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=S%3A340+%26+S%3A356T+%26+S%3A936H+%26+E%3AL21F+%26+M%3AS4F+%26+ORF3a%3AG100V&)

**Comment by silcn** [comment]
Now also found in Florida: EPI_ISL_13225194, sampled 2022-05-18.

**Comment by chrisruis** [comment]
Will add a monitor label for now and see whether this expands in the coming weeks

**Comment by Sinickle** [comment]
Scotland now as well, with a 2022-06-10 sample date. 
<img width="332" alt="image" src="https://user-images.githubusercontent.com/94097102/175699351-3ba5ca30-dffe-4a12-a2f8-92e1a026733b.png">

**Comment by corneliusroemer** [comment]
It's up to 11 sequences now. Really interesting lineage - because it mirrors so many of the BA.4/5 mutations and seems to have arisen independently (or through recombination?).

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=BA.2*+%26+S%3A356T+%26+S%3A936H&variantQuery1=BA.4*&pangoLineage2=BA.2*&

I'm strongly in favour of designation due to the very peculiar Spike mutation profile:
**Shared with BA.4/5**
S:69/70del
L452R
R493Q (reversion)

**Additional to BA.4/5**
E340K
K356T
D936H

**Missing with respect to BA.4/5**
S:486V

This lineage has 9866T, so it's not unlikely it evolved outside of southern Africa (where 9866C is most common).

See here for comparison of mutations between BA.4*, BA.2* and this lineage

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/25161793/175987574-3ea52465-b138-45d3-b905-1244f853792d.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=BA.2*+%26+S%3A356T+%26+S%3A936H&variantQuery1=BA.4*&pangoLineage2=BA.2*&analysisMode=CompareEquals&

I'll remove the monitor label since I think it would be very good to have this designated for faster detection of more samples of this coming up. Also, it may be good if the origin of this lineage could be investigated as it parallels BA.4/5 so strongly. And a lineage designation is quite helpful to talk about it. It's also strongly associated with Ireland in terms of epidemiology.

**Comment by silcn** [comment]
Now found in England (EPI_ISL_13471163) and Czech Republic (EPI_ISL_13478306).

**Comment by silcn** [comment]
Newly found in Germany with an additional S:H49Y (EPI_ISL_13569569). 26 total sequences now.

**Comment by c19850727** [comment]
Just noticed that this cluster gained another NSP5 change.
It's a bit unusual IMHO to have 3 changes in NSP5.

**Comment by ryhisner** [comment]
There's also a new sequence from England on the far right side of the tree, adding ORF3a:A39T and ORF1b:A1895T. Sequence collected on June 24. 
![Screen Shot 2022-07-02 at 11 30 51 PM](https://user-images.githubusercontent.com/33738461/177023374-be8fea00-48c1-4e00-baa0-1da58f39d4aa.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.77 with 13 newly designated sequences. Defining mutation(s) G22580A (S:E340K), A22629C (S:K356T), T22917G (S:L452R), G23040A (S:R493Q), G25691T (ORF3a:G100V), C26533T (M:S4F).

**Comment by FedeGueli** [comment]
39 seqs as today, steadily growing
