### ISSUE TITLE
BA.2 (+22792T) lineage with S:E340K/Q, S:R346T, S:K356T (some have S:S71P, S:Q564E) (18 seq as of 2022-06-28, Denmark)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#733]
Proposal for a sublineage of BA.2 (credit to @bitbyte2015 for spotting it)
Earliest sequence: 2022-05-04
Countries detected: Denmark (13 seq)

Mutations on top of BA.2+C22792T:
S:E340K/Q*, R346T, K356T, S:Q564E*
ORF1a:N840H, R1404C
and some silent mutations
*340Q and 564E are present in 11/13 seq. The other two have 340K as well as S:T572I. Looks like E -> K -> Q at S:340.

9/11 seq on the 340Q/564E branch have S:S71P. 4 of these 9 have S:I1232V and 2 have S:D574N.

This was spotted by @bitbyte2015 who mentioned it in issue #666. It has now turned up in two regions of Denmark so it is in general circulation and not just a chronic patient, hence why I'm proposing it. Seems likely a chronic patient was involved though, with the multiple branches potentially corresponding to multiple onward transmissions?

<img width="698" alt="Denmark_R346T" src="https://user-images.githubusercontent.com/42699509/172504432-f47c2374-13d1-4959-a497-6a5aaad143c5.png">

[https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1ff76_fd7c50.json?branchLabel=Spike%20mutations&c=gt-S_340&label=nuc%20mutations:G22580A,G22599C,A22629C](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1ff76_fd7c50.json?branchLabel=Spike%20mutations&c=gt-S_340&label=nuc%20mutations:G22580A,G22599C,A22629C)

Sequences:
EPI_ISL_12701114
EPI_ISL_12701194
EPI_ISL_12728501
EPI_ISL_12780657
EPI_ISL_12780756
EPI_ISL_12781549
EPI_ISL_12781666
EPI_ISL_12782264
EPI_ISL_12811239
EPI_ISL_13067275
EPI_ISL_13068394
EPI_ISL_13127856
EPI_ISL_13128087

**Comment by chrisruis** [comment]
Will put a monitor label on this for now and see whether it expands in the coming weeks

**Comment by silcn** [comment]
No new sequences for over two weeks, and then three turned up today: EPI_ISL_13442681, EPI_ISL_13442791, EPI_ISL_13443364. Two of them have S:Y796H. They're not descended from the stuff that was circulating in May but instead are on some new long branches.

<img width="615" alt="pango733_0624" src="https://user-images.githubusercontent.com/42699509/175750102-df2e3337-5de0-4e56-92a2-218a24aaf555.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_1519c_64cae0.json?branchLabel=aa%20mutations&c=userOrOld&label=nuc%20mutations:G22580A,G22599C,A22629C](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_1519c_64cae0.json?branchLabel=aa%20mutations&c=userOrOld&label=nuc%20mutations:G22580A,G22599C,A22629C)

**Comment by FedeGueli** [comment]
Hi @silcn what is the sampling date for these new ones? it is a bit puzzling they are on a long branch from the root, suggesting new spillovers from the source maybe?

**Comment by silcn** [comment]
@FedeGueli they're very recent: one is 16 June and two are 19 June. Given how good Denmark's sequencing coverage is, the tree does rather suggest that there have been at least five spillovers from some (chronic?) source.

**Comment by FedeGueli** [comment]
@silcn  agree! i was meaning that spillovers from same source with limited further spread.

**Comment by bitbyte2015** [comment]
18 seq now

EPI_ISL_12701114, EPI_ISL_12701194, EPI_ISL_12728501,
EPI_ISL_12780657, EPI_ISL_12780756, EPI_ISL_12781549,
EPI_ISL_12781666, EPI_ISL_12782264, EPI_ISL_12811239,
EPI_ISL_13067275, EPI_ISL_13068394, EPI_ISL_13127856,
EPI_ISL_13128087, EPI_ISL_13442681, EPI_ISL_13442791,
EPI_ISL_13443364, EPI_ISL_13465759, EPI_ISL_13500814,

**Comment by corneliusroemer** [comment]
@silcn great proposal, but I'd love if you put a cov-spectrum query up. Here's one:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=NextcladePangoLineage%3ABA.2*+%26+C22792T+%26+S%3AE340+%26+S%3AR346T%26+S%3AK356T+%26+S%3AQ564E&

<img width="2283" alt="image" src="https://user-images.githubusercontent.com/25161793/176405288-f5f083d8-d773-4760-ad0e-45ce5a6cd6d5.png">

Though the query may need to be broadened a bit to account for dropouts, because I only find 14 sequences not 18 as @bitbyte2015 found

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.80 with 19 newly designated sequences, and 1 updated designation from BA.2. Defining mutation(s) G22580A (S:E340K),G22599C (S:R346T),A22629C (S:K356T).
