### ISSUE TITLE
New BA.2.12.1 Sublineage with S:L461I and S:R567K

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#737]
I'd like to propose a new BA.2.12.1 sublineage marked by the spike mutations L461I and R567K, along with ORF8:G8V. 

It's defined by the nonsynonymous nucleotide mutations C27513T, G27916T, C22943A, G23262A and the synonymous nucleotide mutation T6157C. All but six sequences also contain the synonymous nucleotide mutation T9043A. The earliest sequence is from May 3. It's been found in seven US states, but the bulk are in New York, New Jersey, and Pennsylvania. Just one case has been sequenced so far outside of the US, in England on May 31.  EPI_ISL_13106540

From April 1 to May 25, it has a 102% weekly growth advantage over BA.2.12.1 (using the queries S:L461I + S:R567K and S:L452Q + S:S704L). https://cov-spectrum.org/explore/United%20States/AllSamples/from=2022-04-01&to=2022-05-25/variants?aaMutations=S%3AL452Q%2CS%3AS704L&aaMutations1=S%3AL461I%2CS%3AR567K&analysisMode=CompareToBaseline&
![Screen Shot 2022-06-08 at 5 22 11 PM](https://user-images.githubusercontent.com/33738461/172721117-1616363b-7af9-4cba-9374-6ce6ea5ddc8b.png)

There are 48 sequences in this lineage right now, though a GISAID search returns 55 sequences in the US with Spike_L461I, R567K. 
![Screen Shot 2022-06-08 at 5 33 31 PM](https://user-images.githubusercontent.com/33738461/172721282-8f32544c-fcd4-4630-83a8-8ac302e09c97.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_401c3_10ed00.json?branchLabel=aa%20mutations&c=pango_lineage&label=nuc%20mutations:G23262A

**Comment by ryhisner** [comment]
New Jersey has 17 sequences and Pennsylvania 16 in this lineage, both easily more than any other state (New York is 3rd with eight). The weekly growth advantages of this lineage over BA.2.12.1 in New Jersey and Pennsylvania are 136% and 126%, respectively (though CI intervals are obviously wide). This is, again, for the time period April 1 to May 25. 
![Screen Shot 2022-06-08 at 5 47 54 PM](https://user-images.githubusercontent.com/33738461/172724017-1d6b9410-bec6-4404-9b3d-05d5ea8839dc.png)

**Comment by FedeGueli** [comment]
Hi @chrisruis i am monitoring this one before it was proposed and i have a long list of sublineages of BA.2 and BA.4 and in that list this one is the only one that seems really close to BA.5 baseline.
More: a double spike mutation beyond the double defining spike mutation of BA.2.12.1 associated with high transmissibility is something to be well highlighted to scientific-community and vaccine producers too. I fear closing at this stage it will get lost among dead lineages while it is not dead at all.

**Comment by FedeGueli** [comment]
60 seqs as today on covspectrum. growth disadvantage vs BA.5 just around 9% . This definetely is the fastest not Ba.5 sublineage.
@ryhisner please the title updated with number of sequences, Pango team did a great job in designating the most intetesting sublineages in a row and closing the ones without clear significance, but it doesnt mean they are archived, and i fear this one unluckily will be with us for a long time.
