### ISSUE TITLE
New Branch of BA.5 defined by T4906C,T18957C and ORF1b:A1312V (C17402T) circulating in Australia, USA (85 Sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#738]
I have identified a brand new branch of BA.5 with a simple cov-spectrum query that excludes all known main BA.5 branches (Link to this query: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=M%3A3N&nucMutations=G12160A%2C29666C%2C27438T%2C1931C%2C1627C%2C21789C%2C28330A&).

This branch is defined by T4906C,T18957C and ORF1b:A1312V (C17402T) .
There are a few basal sequences with just T4906C and two different private mutations C11986T, G18583A (orf1b:V1706I) but the main branches starts with Orf1b:A1312V and it counts 85 sequences.
It further acquired Orf1b:T2537I that is present in 59 out of 85 sequences

Sequence list:
[contributors (30).csv](https://github.com/cov-lineages/pango-designation/files/8865463/contributors.30.csv)
Countries:
![Schermata 2022-06-09 alle 00 57 04](https://user-images.githubusercontent.com/87669813/172731137-879c86b9-0f1e-4872-b3f6-a9aa7b6fa0d5.png)

Tree:
![Schermata 2022-06-09 alle 00 58 05](https://user-images.githubusercontent.com/87669813/172731303-d0b112d2-e7b7-42aa-9dca-20a21bf95b8f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a32d_125100.json?branchLabel=aa%20mutations&c=gt-nuc_4906,17402,18957,21077&label=nuc%20mutations:T4906C

Cov-Spectrum overview:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants/international-comparison?aaMutations=M%3A3N%2COrf1b%3AA1312V&nucMutations=G12160A%2C29666C%2C27438T%2C1931C%2C1627C%2C21789C%2C28330A&

**Comment by chrisruis** [comment]
Thanks @FedeGueli As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

There doesn't seem to be a clear epidemiological event associated with this clade, we therefore haven't designated this at this point

**Comment by FedeGueli** [comment]
Thx @chrisruis 172 sequences as today and now growing in Australia too, maybe due to founder effect. i will keep this monitored.

**Comment by FedeGueli** [comment]
349 Seqs as today,
This is showing a slight growth advantage vs BA.5 baseline
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=ORF1b%3AA1312V&nucMutations1=T4906C%2CT18957C&analysisMode=CompareToBaseline&
Here the comparison to BA.5 in Usa (the country with the most of sequences of this sublineage):
![Schermata 2022-06-18 alle 17 19 37](https://user-images.githubusercontent.com/87669813/174445033-c629175a-f0a5-4b6c-9b86-1a8bd29b855a.png)

It has to be noticed that this lineage has been introducted in Aruba recently and it reached rapidly 34% of samples there in the last week ( 10 sequences):
https://cov-spectrum.org/explore/Aruba/AllSamples/Past6M/variants?aaMutations=M%3A3N%2COrf1b%3AA1312V&nucMutations=G12160A%2C29666C%2C27438T%2C1931C%2C1627C%2C21789C%2C28330A&

Therefore i ask to reopen this sublineage .
cc @chrisruis @corneliusroemer @AngieHinrichs @InfrPopGen

**Comment by FedeGueli** [comment]
Sorry on Usher i found it is already 460 sequences.

![Schermata 2022-06-18 alle 17 27 27](https://user-images.githubusercontent.com/87669813/174445358-cfb756e2-b35f-46b0-a350-23f4d9f44b0e.png)

The Aruba subclade belongs to the main clade in this sublineage defined by Orf1b:T2537I with an additional synonymous mutation :C15660T
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25360_dee1e0.json?c=pango_lineage_usher&label=nuc%20mutations:C15660T

**Comment by FedeGueli** [comment]
780 sequences as today.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f62f_5b9b20.json?c=pango_lineage_usher&label=nuc%20mutations:T4906C

**Comment by FedeGueli** [comment]
@InfrPopGen @chrisruis @corneliusroemer  i see on usher that this has been designated BA.5.6 but the milestone link to this (closed) issue is missing.

**Comment by FedeGueli** [comment]
@corneliusroemer @thomaspeacock @infropopgen milestone of BA.5.6 still missing here.

**Comment by FedeGueli** [comment]
Thx!
