### ISSUE TITLE
Potential BA.4 sublineage with spike N658S and ORF3a L106F (~300 seqs), and its further sublineage with additional spike A701V (~40 seqs)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#739]
This is a potential sublineage of a undesignated proposal (#549 by @corneliusroemer ).

### Description
**Potential sublineage of**: #549 (BA.4 with additional spike N658S), which is still the second biggest sub-branch of BA.4.
**Earliest sequence**: 2022/03/24 (South Africa-North West)
**Most recent sequence**: 2022/06/01 (US-CA)
**Mutations on top of #549** : C25708T (ORF3a:L106F). Notably, ORF3a:L106F is also the defining amino change of BA.1.15.
**Countries circulating:** 
<html>
<body>

Location | Number of sequences | Prevalence
-- | -- | --
United States | 158 | 0.073%
South Africa | 37 | 0.946%
Sweden | 29 | 0.897%
United Kingdom | 18 | 0.006%
Austria | 9 | 0.14%
Denmark | 6 | 0.023%
Germany | 5 | 0.008%
Costa Rica | 4 | 1.048%
Netherlands | 3 | 0.053%
India | 2 | 0.209%
Belgium | 1 | 0.037%
Switzerland | 1 | 0.834%

</body>
</html>

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/172773271-04cf656b-d205-4165-97af-eb6ac4d1ef99.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2b84_17e350.json?branchLabel=aa%20mutations&c=gt-nuc_25708,23535,6401,23664&label=nuc%20mutations:A23535G

### Genomes:
[BA.4 L106F.csv](https://github.com/cov-lineages/pango-designation/files/8867237/BA.4.L106F.csv)

**Comment by c19850727** [comment]
I'm also to propose a further potential sublineage of #739, predominantly found in the US, with an additional S:A701V and ORF1a:P2046S.

**Potential sublineage of**: #739
**Earliest sequence**: 2022/04/29 (US-CA)
**Most recent sequence**: 2022/06/01 (US-CA)
**Mutation on top of BA.4**: S:N658S, S:A701V, ORF3a:L106F, ORF1a:P2046S
**Countries circulating:** 
<html>
<body>


Location | Number of sequences | Prevalence
-- | -- | --
United States | 35 | 0.042%
United Kingdom | 3 | 0.001%
India | 2 | 0.209%


</body>
</html>

**Imported case**: Japan ex-US 

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/172775817-1f5b690c-785a-403d-9def-2a833f121251.png)
Please note that I am making this proposal one branch further into the tree, skipping ORF1a:P2046S.

### Genomes:
EPI_ISL_12622491, EPI_ISL_12760198, EPI_ISL_12867288, EPI_ISL_12867327, EPI_ISL_12887472, EPI_ISL_12923021, EPI_ISL_12962475, EPI_ISL_12962694, EPI_ISL_12963536, EPI_ISL_12963653, EPI_ISL_12963792, EPI_ISL_12964069, EPI_ISL_13043980, EPI_ISL_13044023, EPI_ISL_13044158, EPI_ISL_13056807, EPI_ISL_13059345, EPI_ISL_13076143, EPI_ISL_13078502, EPI_ISL_13080748, EPI_ISL_13082213, EPI_ISL_13082691, EPI_ISL_13088177, EPI_ISL_13102421, EPI_ISL_13102622, EPI_ISL_13102631, EPI_ISL_13104443, EPI_ISL_13128328, EPI_ISL_13146494, EPI_ISL_13152923, EPI_ISL_13153034, EPI_ISL_13153038-13153039, EPI_ISL_13153066, EPI_ISL_13153161, EPI_ISL_13153249-13153250, EPI_ISL_13157014, EPI_ISL_13167900, EPI_ISL_13175467, EPI_ISL_13175593

**Comment by chrisruis** [comment]
Thanks @c19850727 As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

There don't seem to be a clear epidemiological events associated with these clades, we therefore haven't designated this at this point
