### ISSUE TITLE
Potential BA.2 sublineage with ORF8:F41S (~1200 seqs), and its further sublineage with additional spike Y248S/L249F (~450 seqs)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#740]
### Description
**Potential sublineage of:** BA.2
**Earliest sequence:** 2022/01/18 (UK-England)
**Most recent sequence:** 2022/05/31 (US-ND)
**Mutations on top of BA.2:** T28015C (ORF8:F41S)
**Countries circulating:**
<html>
<body>

Location | Number of sequences | Prevalence
-- | -- | --
United Kingdom | 647 | 0.054%
United States | 391 | 0.034%
Denmark | 20 | 0.009%
Germany | 14 | 0.006%
Canada | 4 | 0.015%
France | 3 | 0.01%
Ireland | 3 | 0.058%
South Africa | 2 | 0.142%
Indonesia | 2 | 0.422%
New Zealand | 1 | 0.055%
Mexico | 1 | 0.069%
Thailand | 1 | 0.198%
Netherlands | 1 | 0.015%
Norway | 1 | 0.089%

</body>
</html>

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/172778194-08785c1e-90e8-406d-9c2e-09bcc20c6d7e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_97ad_1807e0.json?c=gt-nuc_28015&l=radial&label=nuc%20mutations:T28015C

### Genomes:
[BA.2 F41S.csv](https://github.com/cov-lineages/pango-designation/files/8867431/BA.2.F41S.csv)

**Comment by c19850727** [comment]
I'm also to propose a further potential sublineage of #740, predominantly found in the US, with additional S:Y248S and S:L249F.

**Potential sublineage of:** #740
**Earliest sequence:** 2022/03/04 (UK-England)
**Most recent sequence:** 2022/05/31 (US-ND)
**Mutation on top of BA.2:** ORF8:F41S, S:Y248S, S:L249F, ORF1a:A566T
**Countries circulating:**
<html>
<body>


Location | Number of sequences | Prevalence
-- | -- | --
United States | 371 | 0.033%
United Kingdom | 28 | 0.003%
Germany | 3 | 0.002%
Canada | 2 | 0.008%
New Zealand | 1 | 0.055%
Ireland | 1 | 0.021%
Mexico | 1 | 0.069%
France | 1 | 0.007%
Denmark | 1 | 0.002%
Netherlands | 1 | 0.015%


</body>
</html>

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/172778751-af968807-4da6-4711-994a-8dcc742ea439.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_97ad_1807e0.json?branchLabel=aa%20mutations&c=gt-nuc_28015,22305&label=nuc%20mutations:T28015C

### Genomes:
[BA.2 Y248S+L249F.csv](https://github.com/cov-lineages/pango-designation/files/8867487/BA.2.Y248S%2BL249F.csv)

**Comment by chrisruis** [comment]
Thanks @c19850727 It looks like Orf8:F41S coincides with introduction(s) into the UK so has an epidemiological event. However, it's stayed at rather low levels in the UK, without evidence of expansion, covSpectrum query [here](https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/from=2022-01-01&to=2022-06-13/variants?pangoLineage=BA.2*&aaMutations1=Orf8%3A41S&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&). There's a lot of UK clades within BA.2 that have similar frequencies so I don't think this clade warrants a designation at this stage

The subclade with S:248S and S:249F has also stayed at low levels without evidence of expansion, covSpectrum query [here](https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/from=2022-01-01&to=2022-06-13/variants?pangoLineage=BA.2*&aaMutations1=Orf8%3A41S%2CS%3A248S%2CS%3A249F&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&) so again I don't think we should designate this one. Thanks again for submitting
