### ISSUE TITLE
Potential BA.4 Sublineage with S:R346T, in Nine Countries

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#741]
I’d like to propose a new sublineage of BA.4 with S:R346T. It’s defined by two nucleotide mutations, C8140T and G22599C, and currently has 40 sequences, 16 of which are in the United States. All but eight of the 40 sequences also share the synonymous nucleotide mutation C14599T. Half of the 40 sequences were collected on or after May 20. The earliest sequences are two from Spain on April 25 and two from South Africa on April 26. 

EPI_ISL_12475182
EPI_ISL_12475185
EPI_ISL_12559458
NHLS-UCT-LA-Z997/2022|ON647684.1

Eight sequences are from England and five from South Africa. Other sequences are from Spain, South Africa, Germany, Luxembourg, Chile, and Australia.
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_188b0_cf5b00.json

![Screen Shot 2022-06-09 at 1 51 52 PM - BA 4 + R346T Phylogenetic Tree](https://user-images.githubusercontent.com/33738461/172919850-ef8052d0-fbf9-49f3-87e3-958ab8c6fcbf.png)

The only additional spike mutation anywhere in this subtree is T307N from a May 23 sequence from the US state of Georgia.
EPI_ISL_13098474

A small branch of three sequences from England share the mutation M:V60L, one from May 31 and two from May 21.
EPI_ISL_13157010
EPI_ISL_12995315
EPI_ISL_12995305

Given the small numbers involved, the growth advantage data below should be taken with a titanic grain of salt, but over the past two months, sequences with spike mutations F486V+L452R+R346T have a 135% weekly growth advantage over F486V+L452R in the US and a 21% growth advantage in the UK. (Restricting the time period to exclude the past two weeks makes the growth advantage in both countries much larger but also makes the uncertainty much, much greater.) I would compare to BA.4 and BA.5 separately, but I’m not very skilled at using the advanced search options on CovSpectrum. 

![Screen Shot 2022-06-09 at 2 38 18 PM](https://user-images.githubusercontent.com/33738461/172920528-aa98dd98-18ba-48c9-b7d2-7c4e4f80949f.png)
![Screen Shot 2022-06-09 at 2 38 33 PM](https://user-images.githubusercontent.com/33738461/172920547-0bc67530-96ea-41e7-9fb5-aae821882500.png)
https://cov-spectrum.org/explore/United%20States/AllSamples/Past2M/variants?aaMutations=S%3AF486V%2CS%3AL452R&aaMutations1=S%3AF486V%2CS%3AL452R%2CS%3AR346T&analysisMode=CompareToBaseline& 
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past2M/variants?aaMutations=S%3AF486V%2CS%3AL452R&aaMutations1=S%3AF486V%2CS%3AL452R%2CS%3AR346T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Thx @ryhisner for proposing this one. S:346T is something to monitor strictly. 
I have to mentiom that weeks ago a twitter account (https://mobile.twitter.com/paullmma)
 indepently highlighted me this mutation in BA.4.
The more we are the best it is ;).
There is a nuc mutation before S:346T, i would add it to the proposal as defining as S:346T

**Comment by silcn** [comment]
I also noticed a small BA.4.1 sublineage that has independently picked up S:R346T along with an 8-nucleotide deletion in ORF7b that causes a huge frameshift where the last 32 amino acids (everything downstream of ORF7b:L11F) are replaced with 18 completely different ones: CFLAFLLFLVLIMLIIFWFSLELQDHNETCHA* becomes SLSVIPCFNYAYYLLVLT*.

There are 7 sequences, 6 from South Africa and one from India:
EPI_ISL_12587905
EPI_ISL_12765589
EPI_ISL_12765592
EPI_ISL_13068912
EPI_ISL_13068913
EPI_ISL_13068950
EPI_ISL_13102651

Just something to keep an eye on for now.

**Comment by chrisruis** [comment]
Thanks @ryhisner As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

There doesn't seem to be a clear epidemiological event associated with this clade, we therefore haven't designated this at this point

**Comment by FedeGueli** [comment]
Hi @chrisruis @corneliusroemer @InfrPopGen @AngieHinrichs i ask you to reopen this one it reached 147 sequences in Usher ( around 100 in covspectrum and it shows a growth advantage over BA.5 baseline in USA, even if it is not so clear everywhere, but the fact one BA.4 sublineage can compete vs BA.5 is unprecedented)

![Schermata 2022-06-17 alle 17 26 13](https://user-images.githubusercontent.com/87669813/174329184-3b789114-030f-4241-be7f-d0f99cdb3010.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1735a_c9c090.json?branchLabel=aa%20mutations&c=gt-nuc_8140,14599,22599&label=nuc%20mutations:C8140T

Covspectrum comparison tool:
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=S%3AR346T%2CN%3A151S%2CORF7b%3AL11F&nucMutations1=12160A%2CC8140T&analysisMode=CompareToBaseline&

@ryhisner probably your proposed lineage could start deeper in the tree with C14599T that likely corresponds at the introduction in USA as epidemiologically relevant event.
![Schermata 2022-06-17 alle 17 33 59](https://user-images.githubusercontent.com/87669813/174330474-86899d15-1df9-4201-849c-5020ac57774f.png)

**Comment by corneliusroemer** [comment]
The growth in the US seems sustained with respect to the direct ancestor of this lineage - exactly what one would expect to see if there was a growth advantage.

We've seen mutations at site S:346 before, in BA.1.1, so it's plausible that this mutation confers a growth advantage in BA.5, too.

This is not just a random AA mutation, it's a combination of growth combined with a mutation that could provide a cause for the growth advantage.

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/25161793/174332825-abd5f51f-78d0-4a4d-92e3-448a37920b57.png">

https://cov-spectrum.org/explore/North%20America/AllSamples/Past2M/variants?aaMutations=S%3AF486V%2CS%3AL452R%2CS%3AN658S&aaMutations1=S%3AF486V%2CS%3AL452R%2CS%3AR346T%2CS%3AN658S&analysisMode=CompareEquals&

See this graph from @jbloomlab , S:346 is one of the big peaks annotated as "Watch these sites"...
![image](https://user-images.githubusercontent.com/25161793/174333030-d22c7fbb-0366-4c70-a138-5f72b3b2ea37.png)

I'll therefore reopen for reconsideration - in any case, this lineage is worth to be monitored.

**Comment by corneliusroemer** [comment]
This lineage now makes up around 3% of all sequences in South Africa and ~1% in US/UK etc.

It seems to be competitive with BA.5*, so could survive, in contrast to other BA.4* that don't have S:346T.

<img width="1946" alt="image" src="https://user-images.githubusercontent.com/25161793/175836997-bb4c6020-c150-4f38-aab1-e3ffeeb98fb7.png">

https://cov-spectrum.org/explore/United%20States/AllSamples/Past2M/variants/international-comparison?variantQuery=nextcladePangoLineage%3ABA.4*+%26+S%3AR346T&variantQuery1=nextcladePangoLineage%3ABA.4*+%26+S%3AR346T&

**Comment by FedeGueli** [comment]
554 sequences as today and apparently has a growth advantage vs BA.5 baseline.  This should be designated @chrisruis @corneliusroemer @InfrPopGen 

https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=S%3AR346T%2CN%3A151S%2CORF7b%3AL11F&nucMutations1=12160A%2CC8140T&analysisMode=CompareToBaseline&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.4.6 with 113 newly designated sequences, and 163 updated designations from BA.4. Defining mutation(s) G22599C (S:R346T).
