### ISSUE TITLE
BA.5 branch with G29032A sublineage defined by Orf1a:M2096L(693 sequences, 4/7),then Orf1b:V1271L +Orf1b:T2376I , then S:P1162L (77% of total sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#743]
Among the undesignated branches of BA.5 there is one defined by G29032A accounting for 100 sequences worlwide that is splitted in three main sublineages:
the smallest is defined by Orf1b:L820F + C12710T
the medium by Orf1b:A1643V 
and the largest of them by Orf1a:M2096L.

In this issue i want to propose the last one defined by G29032A + Orf1a:M2096L (A6551C)
that further acquired Orf1b:V1271L and Orf1b:T2376I : these two mutations are present in 85% of sequences of this sub lineage, but still i would avoid to take them as defining after spotting that a Orf1a:M2096L only made its way to Australia after acquiring more mutations.

Here the BA.5+ G29032A entire tree with the one proposed here coloured in light blue:

![Schermata 2022-06-09 alle 23 10 35](https://user-images.githubusercontent.com/87669813/172945242-707f1e77-021c-40e3-8e1a-68712c87be49.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a3ad_1252d0.json?branchLabel=aa%20mutations&c=gt-nuc_6551,29032&label=nuc%20mutations:G29032A

First sequence: South Africa (EPI_ISL_12043282)
Nr of sequences:55
Sequences list:
[contributors (31).csv](https://github.com/cov-lineages/pango-designation/files/8874041/contributors.31.csv)
Countries:
![Schermata 2022-06-09 alle 23 20 43](https://user-images.githubusercontent.com/87669813/172946811-b1ec9302-7471-464f-bb45-34df14dcbfd9.png)

Cov-Spectrum overview:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=M%3A3N%2COrf1a%3AM2096L&nucMutations=G12160A%2CG29032A&

**Comment by chrisruis** [comment]
Thanks @FedeGueli As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

There doesn't seem to be a clear epidemiological event associated with this clade, we therefore haven't designated this at this point

**Comment by FedeGueli** [comment]
Yes i know, thx @chrisruis,
 i ve tried to highlight here early undescribed sublineages branching off from BA.5. My thought is that it will be helpful when the BA.5 driven wave will become global. 
Agree very little numbers for now. i will keep on monitoring this and the others closed for the same reason and if some signals will come i'll update the issues.

**Comment by FedeGueli** [comment]
71 Sequences as today. Now sampled in Democratic Republic of Congo

**Comment by FedeGueli** [comment]
242 Sequences as today , this lineage is growing very fast, the branch with Orf1b:V1271L and Orf1b:T2376I represents 224 out of 242 (90+%) sequences and it has further acquired a spike mutation S:P1162L (186 out of 242 sequences 70+% ) and it seems to be spreading quite fast in Denmark, Uk and Europe.
![Schermata 2022-06-19 alle 20 28 54](https://user-images.githubusercontent.com/87669813/174495286-b5c6a1fc-4ef6-49d6-bff9-ac3be055cb2d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c026_f67fc0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:G29032A
Growth advantage vs BA.5 baseline is quite clear:
Uk
![Schermata 2022-06-19 alle 20 30 40](https://user-images.githubusercontent.com/87669813/174495363-f58c99f8-8802-4afd-9279-2f5391022abd.png)
Denmark
![Schermata 2022-06-19 alle 20 29 55](https://user-images.githubusercontent.com/87669813/174495332-dad30e0d-8949-4c54-abe1-544385d4213c.png)

Therefore i ask to reopen this issue to monitor and designate this lineage.
@chrisruis @InfrPopGen @AngieHinrichs @corneliusroemer

**Comment by FedeGueli** [comment]
Hi @agamedilab
thank you for checking
To be completely correct:
There are 258 sequences of this sublineage proposed here..
351 is the count for the entire  G29032A branch
I have proposed two of them (one is this issue) and i am monitoring the third .

**Comment by FedeGueli** [comment]
693 seqs as today

**Comment by FedeGueli** [comment]
@chrisruis @InfrPopGen this is now designated BA.5.7 please if you have time add the milestone to this issue

**Comment by AngieHinrichs** [comment]
I think BA.5.7 is a sibling of this proposal -- it has ORF1a:M2096L but then instead of ORF1b:V1271L it has ORF1a:T350I, ORF7a:H47D, and ORF1a:E91K (and both have other non-coding mutations).  Here is what it looks like in Taxonium at the moment -- BA.5.7 is labeled and its nodes are light brownish, while the node in this proposal has a black circle and pop-up with S:P1162L:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/186983/180627309-07c6bda4-b351-46d9-9fd8-7329bfe9ca25.png">

**Comment by FedeGueli** [comment]
thx @AngieHinrichs yes you are right BA.5.7 is a sublineage of the main beanch defined by 29032A + orf1a:2096L. I was thinking it was designated starting with orf1a:2096L sorry.. Probably  the broader lineage misses some of the Pango rules.
The 29032A branch now counts around ~2500sequences far from the least spread designated branch (BA.5.6 ~6500seqs. So probably it is ok to designate just sublineages of some epi interest deeper in the tree as the discussed here BA.5.7

**Comment by corneliusroemer** [comment]
Yes, this is not BA.5.7.

This is an interesting branch, it comes off directly from the BA.5 polytomy and makes up ~15% of all base BA.5 that are not yet part of another sublineage.

It makes up ~2% of cases in the UK, with share across Europe ranging from 0.1-2%.

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/25161793/180657948-ff836fe6-187c-463c-a0bb-19c6efef03df.png">

First sequenced in the UK

I'll reopen as I don't think we should be too narrow on "epidemiological events". This is a long branch so quite interesting.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.8 with 1048 newly designated sequences, and 229 updated designations from BA.5. Defining mutation(s) C25047T (S:P1162L).
