### ISSUE TITLE
Proposal for a BA.2.56 sublineage with additional Spike H69Y and W886L (predominantly Japan, 75 seqs as of 2022-06-10)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#745]
This potential sublineage seems growing pretty fast around Kochi prefecture in Western Japan.

### Description
**Potential sublineage of**: BA.2.56 (the European sublineage with spike L452M from the BA.2 root)
**Earliest sequence**: 2022/03/27 (Japan-Hyogo prefecture)
**Most recent sequence**: 2022/05/21 (Japan-Kochi prefecture)
**Mutations on top of BA.2**: 
<html>
<body>

Gene | Amino changes
-- | --
ORF1a | R226K (67/75)
Spike | H69Y, L452M, W886L
ORF3a | A31S (48/75)

</body>
</html>

**Countries circulating**: Japan, mainly in Kochi prefecture (41 seqs) and Hyogo prefecure (16 seqs)
![image](https://user-images.githubusercontent.com/86835836/173093482-11841a28-11db-44cb-a485-099b4e6a7b57.png)

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/173092573-eb4c3f30-53d1-4332-accf-655b2ca7d8fd.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_252b8_358a30.json?branchLabel=aa%20mutations&c=userOrOld&label=nuc%20mutations:C21767T,G24219T

### Genomes:
EPI_ISL_12939238, EPI_ISL_12939986, EPI_ISL_12940618-12940619, EPI_ISL_12941234, EPI_ISL_12946862, EPI_ISL_12946874, EPI_ISL_12946907, EPI_ISL_12946993-12946994, EPI_ISL_12947034, EPI_ISL_12947036, EPI_ISL_12947040, EPI_ISL_12947046, EPI_ISL_12951761, EPI_ISL_12951833, EPI_ISL_12951935, EPI_ISL_12952003, EPI_ISL_12952036, EPI_ISL_12952092, EPI_ISL_12952200, EPI_ISL_12952209, EPI_ISL_12985994, EPI_ISL_12991507, EPI_ISL_12991523, EPI_ISL_12991532, EPI_ISL_12992467, EPI_ISL_12992596, EPI_ISL_12992627, EPI_ISL_12992650, EPI_ISL_13204871, EPI_ISL_13204964, EPI_ISL_13205412, EPI_ISL_13205421, EPI_ISL_13205452, EPI_ISL_13206279, EPI_ISL_13206305, EPI_ISL_13206307, EPI_ISL_13206353, EPI_ISL_13207213, EPI_ISL_13207409-13207410, EPI_ISL_13209142, EPI_ISL_13209146, EPI_ISL_13209237, EPI_ISL_13209980, EPI_ISL_13210056, EPI_ISL_13210102, EPI_ISL_13210163, EPI_ISL_13210174, EPI_ISL_13210185-13210186, EPI_ISL_13210200-13210201, EPI_ISL_13210204, EPI_ISL_13210227, EPI_ISL_13210242-13210252, EPI_ISL_13210259, EPI_ISL_13210261, EPI_ISL_13210266, EPI_ISL_13210270-13210271, EPI_ISL_13211910, EPI_ISL_13212458, EPI_ISL_13212588

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.56.1 with 30 newly designated sequences. Defining mutation(s) C21767T (S:H69Y), G24219T (S:W886L).
