### ISSUE TITLE
New BA.5 sublineage of interest with S:R346I (520 Sequences as of 2022-07-24) 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#753]
I have spotted a BA.5 cluster with a mutation of interest S:346I:
Countries: South Africa, Switzerrland, Germany, Uk
Defining mutations: T1570C, C11674T, C18804T, G22599T (S:R346I)
tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_3ac76_30e1d0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T1570C,C11674T,C18804T,G22599T
![Schermata 2022-06-13 alle 00 30 29](https://user-images.githubusercontent.com/87669813/173256201-9e43477c-7b46-4970-9bea-c81dd42eaba6.png)

CovSpectrum overview: 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=M%3A3N&nucMutations=G12160A%2CT1570C%2CC11674T%2CC18804T%2CG22599T&

**Comment by chrisruis** [comment]
Very small currently so will close for now but can reopen if this grows in future

**Comment by FedeGueli** [comment]
31 in Usher as today:
![Schermata 2022-06-18 alle 08 02 36](https://user-images.githubusercontent.com/87669813/174425162-03d38394-451a-4da9-90e7-eeffa1c6a5af.png)
it further acquired 
C11514T, C17676T
ORF1a:T3750I
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1735a_c9c090.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C8140T

**Comment by FedeGueli** [comment]
Hi @corneliusroemer @chrisruis @InfrPopGen @AngieHinrichs Jesse Bloom seems quite worried about S:346 mutations.
https://twitter.com/jbloom_lab/status/1537852516435521536?s=20&t=q0a8MxH_ZVv6yGgneofFEg
Please evaluate if reopen this issue to be monitored not just by me.

**Comment by FedeGueli** [comment]
45 Seqs as today. 

It seems growing very fast in Germany.
![Schermata 2022-06-21 alle 00 38 03](https://user-images.githubusercontent.com/87669813/174685325-06fcab86-6987-4bbb-861e-2d014d7b0650.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_d36b_f21e0.json?c=pango_lineage_usher&label=nuc%20mutations:T1570C,C11674T,C18804T,G22599T

**Comment by corneliusroemer** [comment]
I support designation - this now makes up ~5% or more of German sequences and it's got a mutation of high concern.

I'll reopen for consideration.

Better query here using NextcladePangoLineage BA.5*

https://cov-spectrum.org/explore/Germany/AllSamples/Past6M/variants?variantQuery=NextcladePangoLineage%3ABA.5*&variantQuery1=NextcladePangoLineage%3ABA.5*+%26+S%3A346I&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
68 seqs on covspectrum as today

**Comment by FedeGueli** [comment]
120 sequences as today. 
Interestingly 6 of the new added sequences are from Uk and have an additional Rbd mutation S:471Q and a couple of Orf1ab mutation quite a long branch that let me suspect undersampled circulation outside Europe ( and that could be supposed also by the fact this is a brand new branch of BA.5 corresponding to an early seeding from the source)
![Schermata 2022-06-30 alle 19 56 32](https://user-images.githubusercontent.com/87669813/176745458-8b4b0749-6a7e-42c2-b73a-d21bfadd1ca8.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d7a0_ddffb0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C2306T,C14676T,C18788T,G22973C

**Comment by FedeGueli** [comment]
180 seqs as today.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3de46_21e970.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C14676T,G22973C

**Comment by FedeGueli** [comment]
There are now 222 sequences on Usher.

and 13 in the small sublineage with S:471Q ( 6 with additional S:W886F).

To me the usher tree is very clear and di per se it represents an epidemiological relevant  event whereas we saw a new branch of BA.5 having been seeded in Germany and subsequently it has started circulating in a sustained way and both importation and spread are clearly linked with the S:R346I (Ricky) mutation.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c83c_c573e0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A23356T

@chrisruis @InfrPopGen @corneliusroemer I propose to designate it  as soon as possible as BA.5.7

**Comment by FedeGueli** [comment]
Weirdly here we see covspectrum count being far behind the usher count. 

@corneliusroemer here the NCPL:BA.5*& S:346I query finds less than the less advanced mutation search.
Its growth advantage probably understimated due the missing sequences from Covspectrum is above 20% since this limeage was spotted.

**Comment by corneliusroemer** [comment]
This lineage should be designated asap start from the S:346II mutation - this is most likely what confers the growth advantage - not the few mutations that are additional in the Germany branch.

The query is here: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=G22599T+%26+nextcladePangoLineage%3ABA.5+%26++C18804T+%26+T1570C&

It's >500 sequences now.

Mutations on top of BA.5: 1570C, 18804T and 22599T

Usher is very clear:
<img width="2194" alt="image" src="https://user-images.githubusercontent.com/25161793/180654396-e2d55b3b-2a95-488e-b5a8-50f194c87b39.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_dcbe_d64f60.json?label=nuc%20mutations:T1570C

Please designate @InfrPopGen

**Comment by silcn** [comment]
Doesn't look like the growth advantage has been sustained, it's been stuck at about 1.3% of BA.5* in Germany for the last 6 weeks.

**Comment by corneliusroemer** [comment]
Yes, it's true S:346I does not seem to do as much as to T for example.

If you compare to BA.5 (no sublineages) it's a much bigger share. I think by comparing to BA.5* you're comparing against BA.5.2.1 which has a growth advantage over BA.5 - this, plus travel may bias down the fact that BA.5 + S:346I _has_ a growth advantage over base BA.5 albeit probably quite small.

In any case, it's 500 sequences and I see no harm in designating a lineage that branches off directly from the BA.5 polytomy.

**Comment by FedeGueli** [comment]
@corneliusroemer @silcn comparing to BA.5.2* that is the fastest of the 7 main BA.5 branches  this has a growth disadvantage of 9% in Germany (past 2 months) or 8% in Europe. Still it has comparable trasmissibility or slight advantage vs BA.5.3, BA.5.5 or BA.5.6.  Being the last to come had harder life than other lineages competing with BA.4s and BA.5s (which further evolved since their introduction in europe in april) instead of BA.2s , in my view it has to be designated

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.9 with 156 newly designated sequences, and 61 updated designations from BA.5. Defining mutation(s) G22599T (S:R346I), C11674T (Synonymous).
