### ISSUE TITLE
Potential BA.1*/BA.2* recombinant, either XM-like, or potentially a sublineage of XM? (99 sequences as of 2022-07-20 mainly in Germany)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#757]
### Description
**Recombinant between**: BA.1.1* & BA.2*
**Earliest sequence**: 2022/04/29 (Germany-BE)
**Most recent sequence**: 2022/06/06 (Denmark)
**Countries circulating**: mainly Germany (51/68 seqs), and also found in Denmark, Slovenia, Netherland, Portugal andSwitzerland.
**Likely breakpoint**: between 17413 and 19953 (NSP13/NSP15)
**Mutations on branch:** A2865G (ORF1a:E867G), G21586T (S:L8F)

**Conserved Nuc mutations** (those in red frames are likely from BA.1*):
![image](https://user-images.githubusercontent.com/86835836/173472734-0502fac0-4766-4f91-b51c-922086ff0524.png)

**Cov-spectrum query**: A2865G, G21586T, 5386G, 29510C
**GISAID query**: NSP3_E49G, N_S413R, Spike_A27S, Spike_L8F

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/173486117-db8ed908-4419-4530-9d5b-77f1643c60bd.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a954_7825c0.json?branchLabel=aa%20mutations&c=gt-nuc_2865&label=nuc%20mutations:T2470C

**Discussion:**
Although, as shown above, this cluster of potential recombinants is assigned as XM by Usher, is also placed perfectly as a sub-branch of XM, and shares identical breakpoint as XM, I however hypothesize that it might be the result of another independent recombination event, considering:

- XM in itself does not have any private mutations to be distinguished from potential similar recombinants, and the breakpoint (between NSP13/NSP15) is a "hotspot" according to my personal monitoring of BA.1/BA.2 recombination clusters during recent months;
- The 2 additional private mutations, namely **A2865G (ORF1a:E867G)** and **G21586T (S:L8F)**, are both very rare. There were a total of **10 sequences** with **ORF1a:E867G** and BA.1* backbone, and a total of **89 sequences** with **S:L8F** and BA.2* backbone collected before 2022-04-29 on GISAID;

![image](https://user-images.githubusercontent.com/86835836/173517533-01fb65d2-03b6-4610-a919-c023a11b7702.png)
Therefore, if we assume this cluster acquired these 2 mutations from some putative parents rather than evolved by itself, then the earlist sequence in Europe with S:L8F and BA.2* backbone was collected on 2022-02-21 (hCoV-19/Denmark/DCGC-393349/2022 / EPI_ISL_10509819), which is the same as the emergence of XM (#472 ).

Also, if this cluster is a sub-branch of XM, I believe it might still be worth a designation, as it has a significant relative growth advantage over either XM or BA.2* in recent 2 months in Europe, according to cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/173521711-b34ec6f6-6916-4d95-8563-0de3db11c892.png)
![image](https://user-images.githubusercontent.com/86835836/173522002-2712564c-c874-4097-8ff0-ab14b2c4e3c9.png)
(the advantage is even greater if the comparison is confined in Germany instead of Europe).

### Genomes:
EPI_ISL_12632240, EPI_ISL_12646725, EPI_ISL_12648634, EPI_ISL_12649028, EPI_ISL_12668111, EPI_ISL_12675802, EPI_ISL_12678136, EPI_ISL_12729433, EPI_ISL_12730147, EPI_ISL_12730151, EPI_ISL_12730791, EPI_ISL_12730811, EPI_ISL_12739081, EPI_ISL_12742721, EPI_ISL_12780574, EPI_ISL_12780883, EPI_ISL_12823755, EPI_ISL_12823805, EPI_ISL_12823809, EPI_ISL_12824249, EPI_ISL_12824754, EPI_ISL_12824769-12824770, EPI_ISL_12828684, EPI_ISL_12828722, EPI_ISL_12918634, EPI_ISL_12997854, EPI_ISL_12998136, EPI_ISL_13004518, EPI_ISL_13004673, EPI_ISL_13009900, EPI_ISL_13014999, EPI_ISL_13015858, EPI_ISL_13015870, EPI_ISL_13015943, EPI_ISL_13016068, EPI_ISL_13030564, EPI_ISL_13034759, EPI_ISL_13036023, EPI_ISL_13066765, EPI_ISL_13067112, EPI_ISL_13068455, EPI_ISL_13141676, EPI_ISL_13143660, EPI_ISL_13177903, EPI_ISL_13229818-13229819, EPI_ISL_13235435, EPI_ISL_13235484, EPI_ISL_13237159, EPI_ISL_13237480, EPI_ISL_13239240, EPI_ISL_13239694, EPI_ISL_13239880, EPI_ISL_13241511, EPI_ISL_13241729, EPI_ISL_13241947, EPI_ISL_13244850, EPI_ISL_13247945, EPI_ISL_13248855, EPI_ISL_13248932, EPI_ISL_13249473, EPI_ISL_13251056, EPI_ISL_13253275, EPI_ISL_13266095, EPI_ISL_13266110, EPI_ISL_13267629, EPI_ISL_13268218

**Comment by c19850727** [comment]
85 sequences as of 2022-06-20.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAL with 95 newly designated sequences, and 0 updated designations.
