### ISSUE TITLE
New potential recombinant BA.1.1/BA.2.9 mainly circulanting in Panama and other countries (53 genomes)

### ISSUE THREAD

**Issue by Vjimenez-vasquez** [cov-lineages/pango-designation#759]
**Description** 
New potential recombinant BA.1.1 (lacking G8393A) / BA.2.9 mainly circulanting in Panama identified by the group of Genomic Surveillance of INS-Peru. This potential recombinant presents a breakpoint in the middle of ORF1a. This genomes cannot be assigned by PANGO and are misidentified (unassigned flag) as belong to XQ by NEXTCLADE, however their mutational profile are no compatible with this recombinant lineage. We have recently identified  9 additional genomes from Peru. 

**Posible recombination squeme** 
![recombination_breaks](https://user-images.githubusercontent.com/89874227/173672040-ebbcbf4a-abdd-435b-933a-b595530131e1.jpeg)
pink box indicates BA.1.1 genome contribution and green box indicates BA.2.9 contribution. 

**Mutations**
![mutations](https://user-images.githubusercontent.com/89874227/173675655-273e4cb1-8fc0-4c56-a739-fa6206dbb841.jpeg)

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/8903163/genomes.txt)

**sc2rf simplified output**
<img width="1196" alt="sc2rf_output" src="https://user-images.githubusercontent.com/89874227/173672645-944c36da-0d17-4e73-9eb0-7aec28f307ab.png">
sc2rf ouput indicates one breakpoint and identifies BA.1 and BA.2 as parental genomes. 
 
**Earliest sequence: 2022-03-19**
hCoV-19/Panama/M221120-GMI/2022 (EPI_ISL_11859557)

**Most recent sequence: 2022-05-30**
hCoV-19/USA/NC-CORVASEQ-1085-4923/2022 (EPI_ISL_13163618)

**Countries circulating**
Chile(1), Colombia(2), Denmark(2), Mexico(1), Panama(41) and USA (7)

**Comment by Wen1953** [comment]
Good observation @Vjimenez-vasquez.It seems to be a new recombinant. 
@InfrPopGen  @corneliusroemer @chrisruis could it be?

**Comment by agolsby** [comment]
Excellent work in tracking down this apparent recombinant! 

I'm concerned about the growth advantage, as CoV-Spectrum seems to have generated a curve ill-fitted to the underlying data. 
With full caution that single-chart epidemiology is highly prone to overinterpretation, I'll carefully mention the following early impressions from these data:

- Growth advantage over BA.1 (this is natural since it has BA.2's spike)
- Significant amplification event(s) in early March
- Slow but steady growth April through mid-May 
- Crushed mid-May by fitter viruses and now of uncertain prevalance

My concern is that its failure to continue amplifying indicates inability to compete with the likes of BA.2.12.1 and BA.5. However, there are plenty of other possible explanations. By facilitating tracking of this lineage, a designation could help answer questions about its epidemiologic significance in the current environment.

**Comment by c19850727** [comment]
@Vjimenez-vasquez it popped out of nowhere after nearly a month, now in the UK, and with a bunch of additional amino changes (and reversions!). 
![image](https://user-images.githubusercontent.com/86835836/175818161-4f287bc4-4a47-4564-8b8c-c88f1d518654.png)

**Comment by c19850727** [comment]
BTW, this potential recombinant has 141 genomes as of today.

**Comment by agolsby** [comment]
254 as of today when using the CoV-Spectrum query below. 286 on the accompanying UShER tree, which is labelled "proposed759". 

It seems concentrated mainly in Panama and the United States. Exportations include Israel, Denmark, Colombia, Peru, and Mexico. 

Cladistic evidence in the UShER tree matching this query reveals multiple weeks of transmission in the USA with three multi-state clusters: one bearing C4246T, one with G8371A, and one with G13948T (which is also present in Panama). (I can't entirely rule out that sequencing artifacts created false subclades.)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C9344T%2CA9424G%2CC9534T%2CC9866T%2CC11514T%2CC15714T%2CC17410T%2CC25624T%2CA24433G%2CC241T%2CC2470T%2CA2832G%2CC3037T%2CT5386G

Unlike the above-discussed parent clade, this recombinant does not show signs of having lost its growth advantage. The following two images show today's estimates. First is from all samples, second is from surveillance samples only. 

![0627 proposed759 growth](https://user-images.githubusercontent.com/9949952/176047461-14f81f06-dc28-4693-af06-905c00a458ff.png)
![0627 proposed759 growth surveillance only](https://user-images.githubusercontent.com/9949952/176047463-3bdab408-10e2-4548-98f4-c34d9a098cf9.png)

The new sequences strengthen the case that an epidemiologic event has occurred.

**Comment by c19850727** [comment]
5 sequences from the UK now, all with additional AA changes mentioned above. 
(I am tempted to propose a sublineage of this current proposal if the growth continues)

**Comment by Vjimenez-vasquez** [comment]
Hi there, just tan update of this proposal. There are currently 316 identified genomes by USHER. 

![proposition_759](https://user-images.githubusercontent.com/89874227/177195993-8e7f0c0a-088a-4e0e-9abd-6e8bd9274e7c.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAM with 341 newly designated sequences, and 3 updated designations.
