### ISSUE TITLE
Potential BA.2.12.1 Sublineage with E:S55F (USA plus Mexico, Canada, Europe; 130 seqs as of 14 Jun 2022)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#760]
There may be a BA.2.12.1 sublineage with E:S55F (nucleotide C26408T) originating in the USA and spreading to Canada, Mexico, and Europe.  As of 14 May 2022, Cov-Spectrum reports 130 BA.2.12.1+E:S55F sequences with 118 from the USA, 3 from Mexico and Canada, and 9 from Europe.

Cov-Spectrum calculates growth advantages of 38% compared to BA.2.12.1*, 88% compared to BA.2*, and 84% compared to B.1.1.529*.

First GenBank sequence: Vermont, USA 11 April 2022

Most recent GenBank sequence: Ohio, USA 2 June 2022

A zip archive of GenBank-formatted and derived metadata and FASTA files for these sequences is available at
[BA.2.12.1+E_S55F.zip](https://github.com/cov-lineages/pango-designation/files/8904479/BA.2.12.1%2BE_S55F.zip). All of these sequences and metadata are from GenBank public sequences via Nextstrain.

Outbreak.info's Situation Report for this potential lineage is https://outbreak.info/situation-reports?pango=BA.2.12.1&muts=E%3AS55F

Counts from Cov-Spectrum as of 14 June 2022:
![BA 2 12 1+E_S55F_counts](https://user-images.githubusercontent.com/88959107/173706572-28118de4-7de0-41ae-9745-7a5c133d9581.png)
Source https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=E%3AS55F&pangoLineage=BA.2.12.1*&

Cov-Spectrum Growth Advantage over BA.2.12.1* (38% as of 14 June 2022):
![BA 2 12 1+E_S55F_advantage_over_BA 2 12 1](https://user-images.githubusercontent.com/88959107/173706678-ddbdc13f-ec48-4d7e-a46d-c1f6a6a52cd8.png)
Source https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=BA.2.12.1*&aaMutations1=E%3AS55F&pangoLineage1=BA.2.12.1*&analysisMode=CompareToBaseline&

Cov-Spectrum Growth Advantage over BA.2* (88% as of 14 June 2022):
![BA 2 12 1+E_S55F_advantage_over_BA 2](https://user-images.githubusercontent.com/88959107/173706757-f4919675-f6d6-4e54-92b9-758455906675.png)
Source https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=BA.2*&aaMutations1=E%3AS55F&pangoLineage1=BA.2.12.1*&analysisMode=CompareToBaseline&

Cov-Spectrum Advantage over B.1.1.529* (84% as of 14 June 2022):
![BA 2 12 1+E_S55F_advantage_over_B 1 1 529](https://user-images.githubusercontent.com/88959107/173706598-d675d855-43cf-4824-9d0c-22d1b07e49bb.png)
Source https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=B.1.1.529*&aaMutations1=E%3AS55F&pangoLineage1=BA.2.12.1*&analysisMode=CompareToBaseline&

**Comment by Sinickle** [comment]
Just tacking on some additional info I found while looking into the proposal - 

BA.2.12.1* + E:55F is not concentrated in any particular state, but New York, Texas, and North Carolina appear to be the 3 hotspots. 
In none of these states does the growth advantage over BA.2.12.1 currently not overlap 0, possibly due to relatively low number of sequences still. 

Around half of BA.2.12.1* + E:55F also have C2416T, which could be used to help separate this sublineage from others that may have E:55F. This one is also spread out, but most common in Texas and North Carolina. Also unclear if the growth advantage is real there, due to low sample size.

**Comment by alurqu** [comment]
@Sinickle My initial hypothesis is that BA.2.12.1+E:55F originated in the Northeastern United States, likely New England or New York, and then spread rapidly through travel with high transmissibility and low infection control precautions.   You do raise an interesting issue with C2416T.  I note that there are currently only 97 BA.2.12.1*+C2416T sequences showing on Cov-Spectrum (https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=C2416T&pangoLineage=BA.2.12.1*&), of which 65% have E:S55F while there are 130 BA.2.12.1*+E:S55F sequences showing on Cov-Spectrum of which 48% have C2416T.

I do note that E:S55F has appeared before and could easily be homoplasic.  In fact, it is homoplasic relative to lineages like BA.2.3.2 and BA.2.3.17.

Of course both of these are C->T (really C->U) mutations at the nucleotide level, and from Roy et al (https://doi.org/10.1016/j.ygeno.2020.11.003) early in the pandemic, C->T appears to be the most common nucleotide mutation seen in SARS-CoV-2.  On the other hand C2416T is a synonymous change to ORF1a:Y717, while E:S55F is a nonsynonymous change which may be increasing viral fitness, so perhaps E:S55F has evolved two or times in BA.2.12.1* like it did in BA.2.3*.

Overall, I hope someone who is a more-proficient UShER user takes a look at the relationship between E:S55F (C26408T) and C2416T in BA.2.12.1*.

**Comment by alurqu** [comment]
Having figured out UShER and the phylogenetic tree, it's quite possible this is several lineages with homoplasic E:S55F some of which may also have homoplasic C2416T.  With this in mind, I'll withdraw this ticket by closing it.  I'll submit new tickets if one or more of the lineages becomes large and clear enough to be candidates for designation.

As a note, as of 18 June 2022, BA.2.12.1* with nucleotide mutations C14408T, C241T, T15009C, and C21721T is approximately 84% of BA.2.12.1* showing a growth advantage of 9% (which may be fueled by growth-advantaged sublineages like BG.2)  This may be a consideration for both phylogenetic trees and growth advantage baseline comparisons for potential new BA.2.12.1* sublineages.

![BA 2 12 1+C14408T+C241T+T15009C+C21721T_advantage_over_BA 2 12 1](https://user-images.githubusercontent.com/88959107/174457336-cb93d26e-1be3-4281-8916-0c8730e30690.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=BA.2.12.1*&nucMutations1=C14408T%2CC241T%2CT15009C%2CC21721T&pangoLineage1=BA.2.12.1*&analysisMode=CompareToBaseline&
