### ISSUE TITLE
Potential new BA.2.2.X lineage in Shanghai (239 genomes)

### ISSUE THREAD

**Issue by qtbobo** [cov-lineages/pango-designation#761]
Sub-lineage of: BA.2.2
Earliest sequence: 2022-02-07
Most recent sequence: 2022-04-13
Countries circulating: China (Shanghai)

1）Recently, shortly after a few cases of SARS-CoV-2 infections were reported in community hospitals and quarantine sites in Shanghai at around late February 2022, there was a rapid increase of new cases in the city within the next two months. the number of infections decline to less than 100 cases per day by late May, 2022. In total, this wave of SARS-CoV-2 infection has resulted in over 600,000 confirmed infections.

2) A total of 239 genomes, almost all sequenced genome samples between Feb. and April showed characteristic mutation ORF8:I76V and C26798T comparing to BA.2.2

3) BA.2.2+ORF8:I76V strain was estimated the overwhelmingly majority of the this wave in shanghai. so we suggest a new sub-lineage BA.2.2.X to address this strain.

<img width="415" alt="图片" src="https://user-images.githubusercontent.com/17988656/173730068-dcb10d30-c738-4cc4-8156-b8ac775f1d6a.png">
<img width="415" alt="图片" src="https://user-images.githubusercontent.com/17988656/173730106-5e43c9ab-be88-44fe-8e7a-b1084788a962.png">
<img width="415" alt="图片" src="https://user-images.githubusercontent.com/17988656/173730121-5ba42fdf-3e7b-43dd-b76d-184cc9ba8267.png">

Related genome sequences are on the protocal of submitting genome data to GISAID, we will update ID list after get accession number.

**Comment by BIOTWang** [comment]
I think it's already designated as BA.2.2.1 in #675 .

**Comment by qtbobo** [comment]
That's great and thanks for help , when do you think the update software will go public (like gisaid)?

**Comment by corneliusroemer** [comment]
It will become available as a Nextclade Pango lineage in the next Nextclade release (only hours away)
