### ISSUE TITLE
Potential BA.2.12.1 Sublineage with C14408T, C241T, T15009C, C21721T, and ORF1a:D3972G (Hawaii, mainland USA, and spreading; 544 seqs as of 20 Jun 2022)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#763]
There may be a BA.2.12.1 sublineage with nucleotides T15009C, C21721T, and ORF1a:D3972G (nucleotide A12180G) originating in Hawaii, USA and spreading to Japan, Europe, Australia, Canada, and Israel.  As of 16 June 2022, Cov-Spectrum reports 488 BA.2.12.1+T15009C+C21721T+ ORF1a:D3972G sequences with 440 from the USA, 20 from Japan, 14 from Europe, 7 from Australia, 6 from Canada, and 1 from Israel.

Cov-Spectrum calculates growth advantages of 12% compared to BA.2.12.1*, 57% compared to BA.2*, and 56% compared to B.1.1.529*.

First GenBank sequence: Hawaii, USA 11 April 2022

Most recent GenBank sequence: Florida and Texas, USA 2 June 2022

A zip archive of GenBank-formatted and derived metadata and FASTA files for these sequences is available at
[BA.2.12.1+15009C+21721T+ORF1a_D3972G.zip](https://github.com/cov-lineages/pango-designation/files/8924652/BA.2.12.1%2B15009C%2B21721T%2BORF1a_D3972G.zip).  All of these sequences and metadata are from GenBank public sequences via Nextstrain.

Counts from Cov-Spectrum as of 16 June 2022:
![BA 2 12 1+15009C+21721T+ORF1a_3972G_counts](https://user-images.githubusercontent.com/88959107/174228720-cd1eedbf-b5a7-4001-a23a-defb3577067e.png)
Source https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF1a%3AD3972G&nucMutations=T15009C%2CC21721T&pangoLineage=BA.2.12.1*&

Cov-Spectrum Growth Advantage over BA.2.12.1* (12% as of 16 June 2022):
![BA 2 12 1+15009C+21721T+ORF1a_3972G_advantage_over_BA 2 12 1](https://user-images.githubusercontent.com/88959107/174228787-df143c99-7c88-4908-908c-896c8e75bf26.png)
Source https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=BA.2.12.1*&aaMutations1=ORF1a%3AD3972G&nucMutations1=T15009C%2CC21721T&pangoLineage1=BA.2.12.1*&analysisMode=CompareToBaseline&

Cov-Spectrum Growth Advantage over BA.2* (57% as of 16 June 2022):
![BA 2 12 1+15009C+21721T+ORF1a_3972G_advantage_over_BA 2](https://user-images.githubusercontent.com/88959107/174228836-dd1e70a2-8fce-4ac0-b2f7-618fe6ca458f.png)
Source https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=BA.2*&aaMutations1=ORF1a%3AD3972G&nucMutations1=T15009C%2CC21721T&pangoLineage1=BA.2.12.1*&analysisMode=CompareToBaseline&

Cov-Spectrum Advantage over B.1.1.529* (56% as of 16 June 2022):
![BA 2 12 1+15009C+21721T+ORF1a_3972G_advantage_over_B 1 1 529](https://user-images.githubusercontent.com/88959107/174228875-be949843-0452-4b33-aa5d-d9c110e2ab9e.png)
Source https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=B.1.1.529*&aaMutations1=ORF1a%3AD3972G&nucMutations1=T15009C%2CC21721T&pangoLineage1=BA.2.12.1*&analysisMode=CompareToBaseline&

Usher tree containing 229 of the 231 GenBank sequences:
![BA 2 12 1+15009C+21721T+ORF1a_3972G_usher](https://user-images.githubusercontent.com/88959107/174229060-fa5ce98c-3cbd-4e41-83f9-1dec6003449b.png)

Edit: Corrected number of samples in the Usher tree.

**Comment by alurqu** [comment]
View the UShER tree dynamically as suggested by @babarlelephant in [Issue 766](https://github.com/cov-lineages/pango-designation/issues/766), visit https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/Issue_763_usher_subtreeAuspice1.json

**Comment by aviczhl2** [comment]
It seems that T15009C and C21721T has a slight growth advantage in BA.2.12.1 globally.

<img width="1139" alt="Screen Shot 2022-06-19 at 15 03 50" src="https://user-images.githubusercontent.com/10445944/174469834-7d3d1b3a-026a-4fd9-b519-137db39f7068.png">

<img width="597" alt="Screen Shot 2022-06-19 at 15 04 05" src="https://user-images.githubusercontent.com/10445944/174469862-c95b06f7-259c-4205-9743-d854c1444cb7.png">

**Comment by alurqu** [comment]
@aviczhl2 Yes, I commented on the growth of BA.2.12.1*+C14408T+C241T+T15009C+C21721T when I closed [Issue 760](https://github.com/cov-lineages/pango-designation/issues/763).

BA.2.12.1*+C14408T+C241T+T15009C+C21721T+ORF1a:D3972G still shows a little advantage over BA.2.12.1*+C14408T+C241T+T15009C+C21721T.
![BA 2 12 1+4_muts+ORF1a_3972G_advantage_over_BA 2 12 1+4_muts](https://user-images.githubusercontent.com/88959107/174605659-6fd70ebb-2dcb-4d2c-9245-9a0a6e926166.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=C14408T%2CC241T%2CT15009C%2CC21721T&pangoLineage=BA.2.12.1*&aaMutations1=ORF1a%3AD3972G&nucMutations1=C14408T%2CC241T%2CT15009C%2CC21721T&pangoLineage1=BA.2.12.1*&analysisMode=CompareToBaseline&

I do note that this growth advantage calculated this way is smaller and likely not competitive with BG.2.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BG.5 with 1203 newly designated sequences, and 41 updated designations from BA.2.12.1. Defining mutation A12180G (ORF1a:D3972G), preceded by C21721T then T15009C.

**Comment by alurqu** [comment]
At one point I got a weird phylogenetic tree result that incorrectly showed C14408T and C241T occurring after BA.2.12.1, and temporarily missed that those mutations actually happened early in the pandemic with C14408T yielding ORF1b:P314L.  In recognition of this and the defining mutations in the designation, I'm correcting this issue's title back to the original title.
