### ISSUE TITLE
BA.5.1 (+T27438C) with S:V289I [200 seq, Portugal, Spain -> Germany, Denmark]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#765]
There's a BA.5 lineage that seems to potentially grow and is associated with Portugal, Spain and Germany.

It's got Spike mutation S:289I, which was already observed in Delta in AY.47 which reached around 4% share in the US.

https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=S%3AF486V%2CS%3AL452R%2CS%3AV289I&nucMutations=T27438C&aaMutations1=S%3AF486V%2CS%3AL452R%2CS%3AV289I&nucMutations1=T27438C&

<img width="2549" alt="image" src="https://user-images.githubusercontent.com/25161793/174335024-1b3cd65b-e170-451a-8169-c138b2b2ddea.png">

It's on the T27438C branch of BA.5.1

<img width="2119" alt="image" src="https://user-images.githubusercontent.com/25161793/174335003-e93283a0-f038-4056-90f5-2dde8e915737.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c80f_ca4fe0.json

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.1.3 with 243 newly designated sequences, and 0 updated designations. Defining mutation(s) G22427A (S:V289I).

**Comment by Mydtlwn** [comment]
The strain needs to be focused on and tracked.

**Comment by Sinickle** [comment]
@Mydtlwn Certainly all BA.5 sublineages are very fit, but among them, BA.5.1.3 does not appear to be one of the more fit BA.5 sublineages.
