### ISSUE TITLE
Please copy the UShER .json onto your github account when proposing a new lineage

### ISSUE THREAD

**Issue by babarlelephant** [cov-lineages/pango-designation#766]
Hi, when proposing a lineage based on a UShER tree, please download the .json and copy it to your github account, as UShER deletes the .json after a few days.

- if the UShER tree is visible at https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c80f_ca4fe0.json 

- then download https://genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c80f_ca4fe0.json copy it into one of your github repos

- in this example I pasted the .json there https://github.com/babarlelephant/subtreeAuspice1/blob/main/auspice/subtreeAuspice1_genome_2c80f_ca4fe0.json
 
- get the raw link, here it is https://github.com/babarlelephant/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2c80f_ca4fe0.json

- then the tree will be **available forever** at https://nextstrain.org/fetch/github.com/babarlelephant/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2c80f_ca4fe0.json

**Comment by FedeGueli** [comment]
great idea. thx

**Comment by alurqu** [comment]
For those who may find it helpful, to run UShER with a set of sequences visit https://genome.ucsc.edu/cgi-bin/hgPhyloPlace?db=wuhCor1&phyloPlaceTree=hgPhyloPlaceData

**Comment by corneliusroemer** [comment]
Good idea but possibly to much work
