### ISSUE TITLE
lineage_notes.txt - B.1.190 Lineage is missing its Description

### ISSUE THREAD

**Issue by icestorm972** [cov-lineages/pango-designation#769]
Hi,

there seems one *Lineage* entry in lineage_notes.txt that is missing its *Description*: B.1.190
Maybe set it to "Netherland lineage" or something like that?

At least there were in total 86 samples (in Mar/Apr 2020) at outbreak.info with 81 in Netherlands and only some other countries with 1 or 2 samples, respectively:
https://outbreak.info/situation-reports?pango=B.1.190

**Comment by InfrPopGen** [comment]
Thanks for spotting this. The description has been added to lineage_notes.txt
