### ISSUE TITLE
New SARS-CoV-2 P.1-related lineages proposal - P.1-like-I and P.1-like-II in Brazil

### ISSUE THREAD

**Issue by paolacristinaresende** [cov-lineages/pango-designation#77]
New lineage proposal
by Tiago Gräf , Gonzalo Bello, Felipe G Naveca, Gabriel L Wallau, Edson Delatorre, Marilda Mendonça Siqueira and  Paola Cristina Resende on behalf of Fiocruz COVID-19 Genomic Surveillance Network

**Description**
Sub-lineages of: B.1.1.28

**Earliest sequence P1-like-I:** hCoV-19/Brazil/AM-FIOCRUZ-20897269OP/2020 - 23/12/2020
**Most recent sequence P1-like-I:** hCoV-19/Brazil/PR-FIOCRUZ-5241/2021 - 21/01/2021

**Earliest sequence P1-like-II:** hCoV-19/Brazil/SC-FIOCRUZ-9767/2021 - 16/01/2021
**Most recent sequence P1-like-II:** hCoV-19/Brazil/AM/FIOCRUZ-21895614MA/2021 - 25/03/2021

**Countries circulating:** Brazil

These new proposed lineages (P.1-like-I and P.1-like-II) evolve from lineage B.1.1.28 major lineage circulating in Brazil since the beginning of the pandemic. 

The P.1-like-I clade (colored in red) accumulated an unusually high number of genetic changes relative to the B.1.1.28 lineage ancestor, including several P.1 lineage-defining mutations in the S (L18F, P26S, D138Y, K417T, E484K, N501Y), NSP3 (K977Q) and N (P80R) proteins and several unique mutations in the NSP2 (K456R), NSP3 (T1189I), NSP6 (V149A), NSP13 (S74L), S (ins214 and D1139H) and NS8 (K2stop) proteins.
However, we found only four sequences P1-like-I with this profile, 3 in the state of Amazonas state and 1 in the state of Parana, Northern and Southern Brazilian regions, respectively.
Actually, P.1-like-I has been classified by the PANGO lineage as B.1.1.28 and we have only four genomes reported, we are in doubt if it is enough to classify this as a new lineage but it is interesting to pay attention if other genomes with this profile appear to classify the P.1-like-I as a new lineage. 

P.1-like-II lineage (colored in green) is spreading in nine states from four Brazilian regions (North = 2, Northeast = 1, South = 35, and Southeast = 13). and harbors 15 P.1 lineage-defining mutations and seven unique mutations.
P1-like-II harbors 15 out of 22 P.1 lineage-defining mutations, including the three mutations of concern at the receptor-binding domain (RBD) of the S protein (K417T, E484K, and N501Y), deletion in the NSP6 (S106del, G107del, F108del) and the four-nucleotide insertion at ORF8/N intergenic region (ins28263).
These P.1-related sequences, here designated as P.1-like-II, lack some of the P.1 lineage-defining mutations at ORF1ab (C2749T, C12778T, and C13860T), NSP13 (E341D), S (T20N), and NS8 (E92K), and further displayed six unique substitutions at ORF1ab (C8905T, C16954T, and A20931G), NSP4 (D217H),  E/M intergenic region (A26492T) and N (P383L). The P.1-like-II sequences also share nine P.1 lineage-defining mutations with the previously characterized P.1-like clade (now designated as P.1-like-I), which further displayed 14 unique mutations.

Viral isolation and neutralizing assay are in progress to understand the phenotypical characteristics of these two new proposed lineages.

Genomes
[P1-likE IDS.txt](https://github.com/cov-lineages/pango-designation/files/6455190/P1-likE.IDS.txt)

Evidence
<![P 1-like](https://user-images.githubusercontent.com/80154344/117729302-08d65200-b1c1-11eb-8e7d-a7505749b9b9.jpg)

Proposed lineage name: P.4 (P1-like-I) and P.5 (P1-like-II)

**Comment by paolacristinaresende** [comment]
Please, check our post on Virological.org for more details about P.1-like-I and P.1-like-II.

https://virological.org/t/identification-of-sars-cov-2-p-1-related-lineages-in-brazil-provides-new-insights-about-the-mechanisms-of-emergence-of-variants-of-concern/694

**Comment by chrisruis** [comment]
Hi @paolacristinaresende thanks very much for submitting this. As the P.1-like-I and P.1-like-II clades likely acquired mutations K417T, E484K and N501Y in the same events that P.1 did, we'd recommend these sequences are designated P.1 under the Pango rules.

We've designated the 10 sequences from your text file that had GISAID IDs as P.1 in [v1.2.6](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.6)

When you have GISAID identifiers for the other samples, just drop them in here and tag me and I'll add them in to the designations. Thanks again

**Comment by paolacristinaresende** [comment]
Dear @chrisruis,
Many thanks! All the GISAID accession numbers of our P.1-like-II are in the pdf attached.
[Supplementary Table 1.pdf](https://github.com/cov-lineages/pango-designation/files/6509370/Supplementary.Table.1.pdf)

**Comment by chrisruis** [comment]
Thanks @paolacristinaresende - we've designated the 44 sequences in the pdf as P.1 in [v1.2.7](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.7)

**Comment by paolacristinaresende** [comment]
@chrisruis and P.1-like-I (4 genomes) they are classified as B.1.1.28 and we believe they are more related to P.1.
What do you think about these sequences?

**Comment by chrisruis** [comment]
Hi @paolacristinaresende I agree your P.1-like-I samples look like P.1. We've got Brazil/AM-FIOCRUZ-20897269OP/2020, Brazil/AM-FIOCRUZ-20897281WS/2020 and Brazil/AM-FIOCRUZ-21840593CL/2020 from your P.1-like-I samples designated as P.1 so not sure why they're still being assigned to B.1.1.28. I'll check the model has definitely updated, see if there's anything else going on and come back
