### ISSUE TITLE
BA.2 sublineage with S:G213E, S:A262S, S:A348P, S:R493Q, S:R765L, S:D936Y (13 seq, mostly India)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#770]
Proposal for a sublineage of BA.2
Earliest sequence: 2022-05-02 (India)
Countries detected: India (11 seq, from 4 states), USA (1, from Mississippi), Austria (1)

Defining mutations:
S:G213E (BA.2 has V213G), A262S*, A348P, R493Q (reversion), R765L*, D936Y*
ORF1a: H2659Y, L3829F
ORF1b: T1801A
*not present in all sequences - see explanation below

This is another one to stick a "monitor" label on for now. Proposing because of the relatively high number of S mutations and appearance on 3 continents. Some of the sequences are poor quality, with lots of NNNs and some probably-erroneous reversions, so the Usher tree is a bit misleading. This is what I think has actually happened:
- First S:G213E, A348P, R493Q, D936H on the yellow branch. The green sequences (not part of this proposal) have R493Q but it may be artefactual.
- The two yellow sequences then have S:L18V and D568N. The other 11, on the blue branch, have S:D936Y (so we have D -> H -> Y at S:936).
- The blue sequence has S:M1237I. The other 10, on the orange branch, have S:A262S and R765L.

Only 9 of the orange branch sequences are visible on the tree because the Austrian sequence, which belongs there too, is spike-only.

<img width="734" alt="213_262_348_lineage" src="https://user-images.githubusercontent.com/42699509/174458730-a203296c-aee0-4131-9bb1-4e0782327e19.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_c7ff_e49370.json?branchLabel=Spike%20mutations&c=gt-nuc_22604,24368,23856&label=nuc%20mutations:C8240T,C11750T,A18868G,C20719T,G22604C,G24368C](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_c7ff_e49370.json?branchLabel=Spike%20mutations&c=gt-nuc_22604,24368,23856&label=nuc%20mutations:C8240T,C11750T,A18868G,C20719T,G22604C,G24368C)

Note that S:348 is one of the locations that Bloom et al highlighted as a potential escape mutation in BA.2. The R493Q reversion, shared with BA.4/5, seems be popping up increasingly often.

Genomes:
EPI_ISL_12872120
EPI_ISL_12872186
EPI_ISL_12872201
EPI_ISL_12872262
EPI_ISL_12953136
EPI_ISL_12957583
EPI_ISL_13050270
EPI_ISL_13095656 (spike-only)
EPI_ISL_13158629
EPI_ISL_13306995
EPI_ISL_13307000
EPI_ISL_13307081
EPI_ISL_13332921

Cov-spectrum query: [https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=BA.2*+%26+S%3AA348P+%26+%28S%3AD936H+%7C+S%3AD936Y%29+%26+ORF1a%3AH2659Y&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=BA.2*+%26+S%3AA348P+%26+%28S%3AD936H+%7C+S%3AD936Y%29+%26+ORF1a%3AH2659Y&)
Some of the sequences do not appear on Cov-spectrum because they do not have a day of collection, only a month.

**Comment by ryhisner** [comment]
A348P is really interesting. Spike residues 346-348 are all big escape locations in the Bloom Lab escape calculator, but A348 mutations are rare and F347 almost nonexistent—very similar to C383 and I468, both of which are huge escape locations but at which mutations are very rarely seen. I wonder if the twice-mutated G213E or A262S mutations somehow structurally enable the A348P mutation. 
https://jbloomlab.github.io/SARS2_RBD_Ab_escape_maps/escape-calc/
![Screen Shot 2022-06-23 at 7 53 25 PM](https://user-images.githubusercontent.com/33738461/175434617-cacc340d-9ee0-47da-b49d-b65481aa91d3.png)

**Comment by InfrPopGen** [comment]
Thanks @silcn  As outlined [here,](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/) new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations.

There doesn't seem to be a clear epidemiological event associated with this clade, we therefore haven't designated this at this point.
