### ISSUE TITLE
Potential BA.2*/BA.5.1 recombinant (67 sequences as of 2022-07-28, Ireland, Croatia, Germany, France, Portugal, Greece, Israel, Spain, Denmark, Canada, Switzerland, Canada and the US)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#771]
I'm to propose this small cluster of BA.5.1 recombinants for monitoring purpose as it has been picked up in 3 countries now.

### Description
**Recombinant between:** BA.2* & BA.5.1*
**Earliest sequence:** 2022/05/10 (Spain-AS)
**Most recent sequence:** 2022/05/27 (Denmark)
**Countries circulating:** Spain (IB, AS, PV), Denmark and Switzerland
**Likely breakpoint:** anywhere downstream of 12160 (or 17822?) and upstream of 21765.
**Mutations on branch**: C7973A (ORF1a:L2570M), C17822T (ORF1b:P1452L), T27696C

**Conserved Nuc mutations**:
![image](https://user-images.githubusercontent.com/86835836/174459886-932193d5-a72e-48fa-bcf8-33c59a780cbd.png)
**Evidence of potential BA.2 donor:** reversion A12160G and C9866T.
**Evidence of potential BA.5.1 donor:** C29666T (ORF10:L37F)
**Cov-spectrum query:** C7973A, C17822T, T27696C, A12160G, C9866T, C29666T
**GISAID query:** Spike_F486V, NSP3_L1752M, NSP13_P529L, NSP4_L438F

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/174459983-3e204e96-ec1f-41a2-bc31-6996e12c5518.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_147e2_d46cb0.json?branchLabel=nuc%20mutations&c=gt-nuc_7973&label=nuc%20mutations:T27808C

### Genomes:
EPI_ISL_13067124, EPI_ISL_13107749, EPI_ISL_13107759, EPI_ISL_13114110, EPI_ISL_13251121, EPI_ISL_13342923, EPI_ISL_13343310

**Comment by LiXingguangBrandonStark** [comment]
by mutation sites or recombination regions?

**Comment by FedeGueli** [comment]
Hi @c19850727 great catch i found the putative parental BA.2 sublineage curculating in Demmark and it has also A18163G. so the breakpoint is after that nucleotide 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=orf1b%3A1452L%2Corf1a%3A2570M%2CS%3A486F&pangoLineage=BA.2*&

Parental BA.2 ids:
<google-sheets-html-origin>

gisaidEpiIsl
--
EPI_ISL_11807645
EPI_ISL_12345222
EPI_ISL_11806369
EPI_ISL_11833311
EPI_ISL_11990568
EPI_ISL_12286850
EPI_ISL_11990885

it was characterized by the two orf1ab mutarions described here plus N:T334I

**Comment by c19850727** [comment]
One more sequence from Canada-BC: hCoV-19/Canada/BC-BCCDC-451464/2022

**Comment by c19850727** [comment]
12 sequences as of 2022-06-26. Newly found in US-CA and Canada-QC.

**Comment by c19850727** [comment]
14 sequences as of 2022-06-27. Newly found in Spain-MD (the previous Spanish ones were from PV, AS and IB)

**Comment by c19850727** [comment]
27 sequences as of 2022-07-08. Newly found in Canada-un (surveillance of international border crossing)

**Comment by c19850727** [comment]
29 sequences as of 2022-07-09. Newly found in Israel.

**Comment by c19850727** [comment]
37 sequences as of 2022-07-14. Newly found in Greece.

**Comment by AngieHinrichs** [comment]
Great find @FedeGueli with those Denmark BA.2 > C22792T > **C7973A** > C19862T > C26681T > C29274T > **C17822T** sequences!  (regarding A18163G, I think that is common to all BA.*, so I think the breakpoint uncertainty region starts at 17823)

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs !

**Comment by c19850727** [comment]
43 sequences as of 2022-07-19. Newly found in Portugal and France.

**Comment by c19850727** [comment]
50 sequences as of 2022-07-19. Newly found in Germany and Canada-ON.

**Comment by c19850727** [comment]
62 sequences as of 2022-07-27. Newly found in Croatia.

**Comment by corneliusroemer** [comment]
Seems to be worth designating now? @chrisruis @InfrPopGen 

Here's a query for the BA.2 donor part - seems to be vanilla BA.2, most common in Italy.

https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=7973A%2C9866T%2C6336.%2C1302.%2C2388.&pangoLineage=BA.2*&

**Comment by c19850727** [comment]
67 sequences as of 2022-07-28. Newly found in Ireland.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAN with 35 newly designated sequences, and 4 updated designations.
