### ISSUE TITLE
BA.2 sublineage with S:W64L, S:N450D, S:Q607K, S:E1144Q (26 seq as of 2022-07-01, mainly Pakistan)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#772]
Proposal for a sublineage of BA.2
Earliest sequence: 2022-05-28 (Pakistan)
Countries detected: Pakistan (12 seq), UK-Scotland (2)

Defining mutations:
S:W64L, N450D, Q607K, E1144Q
ORF1a:S2030L
nuc:C11308T, C28657T

Another lineage with only a small number of genomes, but Pakistan sequences very little. The proportion of sequences from Pakistan belonging to this lineage by week is as follows:
05-23 to 05-29: 1/6
05-30 to 06-05: 0/7
06-06 to 06-12: 4/19
06-13 to 06-19: 7/23
So this lineage is at ~25% in the last couple of weeks. It should be noted that almost all recent Pakistani sequences come from Islamabad so this may not reflect prevalence across the country as a whole. Nevertheless, I think this is worth monitoring: prevalence in an undersampled region, multiple S mutations, recent appearance, not obviously declining in the face of BA.4/5...

<img width="694" alt="Pakistan_W64L" src="https://user-images.githubusercontent.com/42699509/174510224-aa1e1b45-4580-41a8-9f0d-2a94d72543b0.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_20fa2_fc6050.json?c=gt-S_64&label=nuc%20mutations:C11308T,G21753T,A22910G,C23381A,G24992C](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_20fa2_fc6050.json?c=gt-S_64&label=nuc%20mutations:C11308T,G21753T,A22910G,C23381A,G24992C)
(the two apparent branches aren't real, that's caused by a dropout around ORF1a:2030 in a few seqs)

Genomes:
EPI_ISL_13302859
EPI_ISL_13302860
EPI_ISL_13302861
EPI_ISL_13302862
EPI_ISL_13324864
EPI_ISL_13352550
EPI_ISL_13354543
EPI_ISL_13354544
EPI_ISL_13354545
EPI_ISL_13354550
EPI_ISL_13355609
EPI_ISL_13355610
EPI_ISL_13355616
EPI_ISL_13355620

Cov-spectrum query:
[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AW64L%2CS%3AQ607K%2CS%3AE1144Q&pangoLineage=BA.2*&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AW64L%2CS%3AQ607K%2CS%3AE1144Q&pangoLineage=BA.2*&)

Note that this is often misidentified as BA.2.14 by pangoLEARN because of the shared S:W64L.

**Comment by FedeGueli** [comment]
👍
@ryhisner pointed to us this one last night too! always very happy when there are more than two eyes on this kind of things thx @silcn

**Comment by silcn** [comment]
Now also found in France: EPI_ISL_13450052.

24 sequences with sample dates in June were uploaded from Pakistan yesterday, mostly from Karachi, and none were this lineage; looks like the 25% estimate is more reflective of Islamabad than Pakistan as a whole.

**Comment by silcn** [comment]
Now found in the US (Maryland): EPI_ISL_13549373. Also a few sequences from England.
Total is 26 sequences.

**Comment by FedeGueli** [comment]
33 sequences as today (on covspectrum)

**Comment by FedeGueli** [comment]
36 Sequences as today on covspectrum and newly sampled in Netherlands and Canada

**Comment by FedeGueli** [comment]
52 sequences as today on covspectrum
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AW64L%2CS%3AQ607K%2CS%3AE1144Q&pangoLineage=BA.2*&

**Comment by FedeGueli** [comment]
60 sequences as today. Significant international spread to 10 countries in 3 continents
![Schermata 2022-07-30 alle 00 41 45](https://user-images.githubusercontent.com/87669813/181854560-a2ee0c25-ab69-497f-9baa-837bb48427d2.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d816_4596d0.json?c=country&label=nuc%20mutations:A22910G

These seqeunces clustering togrther in Germany could represent local transmission of this variant or maybe just a familiar cluster intercepted by airport surveillance
![Schermata 2022-07-30 alle 00 43 35](https://user-images.githubusercontent.com/87669813/181854675-6c339231-b415-4a4b-99a6-81e5d1387810.png)

@silcn @corneliusroemer @chrisruis 
i think this should be designated very significant 4 spike mutations and epidemiological relevant behaviour, being one of the few BA.2ers still spreading I would not be surprise to see this one competing with last emerging sublineages .

**Comment by c19850727** [comment]
One of sequences from Japan (with travel history from Pakistan) obtained an additional S:L455F.
EPI_ISL_14320247

**Comment by FedeGueli** [comment]
I am monitoring this one since @silcn proposed it, i ma not sure if fast or not, but its geographical spread and ongoing pattern of accumulation of mutations makes me think it is worth designating it. @corneliusroemer could you take a look at this ?

**Comment by FedeGueli** [comment]
71 sequences as today in 10 countries.(@corneliusroemer or @silcn could you update the title please?)
I have checked that little japanese cluster and they are all samples from airport quarantine related to travel from pakistan as suggested by Silcn and the tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f427_fd1230.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C6354T,C11308T 


@corneliusroemer or @silcn could you update the title please?
![Schermata 2022-08-19 alle 20 13 14](https://user-images.githubusercontent.com/87669813/185681563-f05e1e46-7191-4355-84be-7461c37ad9c9.png)

From the tree is clear that in pakistan a sublineage of this had recently acquired another Spike mutation: 
S:E1072Q

**Comment by FedeGueli** [comment]
72 Seqs as today, as  many other lineages seem to have slowed down with very few sequences uploaded in the last two weeks

**Comment by corneliusroemer** [comment]
Interesting but dead and never had many sequences (potentially undersampled) - so I'll close. Let's reopen if an interesting child appears.

<img width="1892" alt="image" src="https://user-images.githubusercontent.com/25161793/190932860-561f041a-3cba-4847-ade8-c33d69335992.png">
