### ISSUE TITLE
BA.2+C25416T + 14925T sublineage with S:346T+S:452M emerged in India (73 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#775]
Here i want to propose a BA.2 sublineage spotted by @corneliusroemer with two Spike mutations of interest.

Defining mutations:
14925T then C538T+S:346T then S452M

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e3a2_1c3770.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C14925T
![chrome_screenshot_1655822265189](https://user-images.githubusercontent.com/87669813/174826985-ecea31db-9bb0-4883-a2b1-826c7949f2a5.png)

Nr of sequences:46

CovSpectrum query:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=S%3A346T+%26+NextcladePangoLineage%3ABA.2*+%26+S%3A452M&

List of Sequences:
[contributors (13).csv](https://github.com/cov-lineages/pango-designation/files/8949911/contributors.13.csv)

Countries: mainly India with exports to Australia, Canada,Usa, Singapore, Thailand
![chrome_screenshot_1655822596674](https://user-images.githubusercontent.com/87669813/174828179-4af2fc4f-3902-425c-99e4-e4d0e9a6a72e.png)

Prevalence: in India it has been more than 3% in the last week trending up.

Copy&Paste from Covspectrum:
Nr of seqs and Prevalence x region:
Himachal Pradesh | 1 | 20%
-- | -- | --
Maharashtra | 20 | 5.65%
Tamil Nadu | 5 | 1.076%
Telangana | 3 | 0.739%

**Comment by FedeGueli** [comment]
73 sequences as today, newly sampled in Austria and England. 
Dear professors @chrisruis @InfrPopGen @AngieHinrichs  @corneliusroemer  i usually dont to that cause to me the important thing is to flag sublineages not to get them designated soon,  but in this case i ask a fast designation for this lineage barely i recall one growing so fast in a few days.

**Comment by InfrPopGen** [comment]
I think it's C583T on the middle node for this one.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.74 with 28 newly designated sequences. Defining mutation(s) C22916A (S:L452M)

**Comment by FedeGueli** [comment]
@InfrPopGen i missed that this is part of the big BA.2 branch with C25416T.
There were small clades of both C25416T +14925T and C25416T+ C583T circulating in India 
and both C583T and 14925T were sequenced without 25416T too.
We can speculate that C25416T +14925T acquired S:346T and then recombined with a lineage carrying C583T  , but i dont think it is sufficiently supported.
So it seems to me that the route C25416T then 14925T +S:346T then C583T  then S:452M is the most likely 
I found two sequences with  14925T+ S:346T without C583T : 

EPI_ISL_12529712
--
EPI_ISL_13302201


But they seem totally unrelated to this sublineage





so i can be totally wrong.
