### ISSUE TITLE
BA.4 + S:658S sublineage with S:R346S and Orf3a:I47V - emerged in South Africa (87 Sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#777]
There are some new sublineages of BA.4 with mutations in S:346.
One has been proposed by @ryhisner in #741 carrying S:346T
Here i want to propose another one with S:346S, 
this growing mutation in South Africa was flagged to me by @corneliusroemer yesterday.

It is a sublineage of the big undesignated  branch with S:658S 
and it is defined by Nuc 26690T and AA substitutions Orf3a:47V(A25531G) and then S:346S (22600T)
![Schermata 2022-06-22 alle 07 32 37](https://user-images.githubusercontent.com/87669813/174951060-8394eccd-e123-454a-af69-0714e52c0f88.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_5602_2a8500.json?branchLabel=aa%20mutations&c=gt-ORF3a_47&label=nuc%20mutations:G26690T

In South Africa has advantage vs BA.5:
https://cov-spectrum.org/explore/South%20Africa/AllSamples/Past3M/variants?aaMutations=M%3A3N&aaMutations1=S%3A658S%2Corf3a%3A47V%2CS%3A346S&nucMutations1=26690T&analysisMode=CompareToBaseline&

Covspectrum overview: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A658S%2Corf3a%3A47V%2CS%3A346S&nucMutations=26690T&

Nr of sequences:28
List of sequences:
[contributors (1).csv](https://github.com/cov-lineages/pango-designation/files/8954671/contributors.1.csv)
Countries:
![Schermata 2022-06-22 alle 07 35 19](https://user-images.githubusercontent.com/87669813/174951410-3e521309-0f83-49bb-a568-b8a9ebdf354a.png)

**Comment by FedeGueli** [comment]
31 sequences now, also newly  found in Belgium England Scotland.

**Comment by silcn** [comment]
> One has been proposed by @silcn in #741 carrying S:346T

Not me!

**Comment by FedeGueli** [comment]
> > One has been proposed by @silcn in #741 carrying S:346T
> 
> Not me!

Thx corrected now! it was @ryhisner!

**Comment by FedeGueli** [comment]
37 sequences as today. Now it has been found also in Netherlands.
In south africa is showing growth advantage vs BA.5.

**Comment by ilevade** [comment]
We also seem to have this lineage circulating in Quebec, Canada, where 27 sequences have been identified: 
Canada/Qc-L00482929001/2022
Canada/Qc-L00485554001/2022
Canada/Qc-L00484884001/2022
Canada/Qc-L00482491001/2022
Canada/Qc-L00488565001/2022
Canada/Qc-L00486483001/2022
Canada/Qc-L00488402001/2022
Canada/Qc-L00486846001/2022
Canada/Qc-L00487892001/2022
Canada/Qc-L00488307001/2022
Canada/Qc-L00488272001/2022
Canada/Qc-L00486150001/2022
Canada/Qc-L00488291001/2022
Canada/Qc-L00485736001/2022
Canada/Qc-L00486109001/2022
Canada/Qc-L00484237001/2022
Canada/Qc-L00487355001/2022
Canada/Qc-L00484526001/2022
Canada/Qc-L00485461001/2022
Canada/Qc-L00483802001/2022
Canada/Qc-L00484765001/2022
Canada/Qc-L00487731001/2022
Canada/Qc-L00485277001/2022
Canada/Qc-L00488406001/2022
Canada/Qc-L00486823001/2022
Canada/Qc-L00488327001/2022
Canada/Qc-L00487678001/2022

**Comment by silcn** [comment]
@ilevade those are part of a different lineage, BA.4.6 (see #741). They have S:R346T rather than S:R346S.

**Comment by FedeGueli** [comment]
87 sequences as today
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A658S%2Corf3a%3A47V%2CS%3A346S&nucMutations=26690T&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.4.7 with 33 newly designated sequences, and 11 updated designations from BA.4. Defining mutation(s) A22600T (S:R346S).
