### ISSUE TITLE
BA.1.1 sublineage with 12 aa substitutions including 5 spike mutations (S:S494P, S:V1128A, S:F59S, S:D420N, S:Y449N, 12 seq., Slovenia)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#778]
Proposal for a sublineage of BA.1.1
Earliest sequence: 14.03.2022 (Slovenia)
Countries detected: Slovenia

Defining mutations:
S:S494P, S:V1128A, S:F59S, S:D420N, S:Y449N
ORF1a:E102K, ORF1a:P380L, ORF1a:R2159Q, ORF1a:I4098T, ORF1b:E787G , ORF1a:V4216I
N:G96V

In the spirit of #773 i am proposing a sublineage of BA.1.1 carrying a total of c. 12 additonal aa mutations compared to BA.1.1. Members of the clade were uploaded to GISAID at three distinct dates (26.4, 13.6, and 20.6) so it is probably not the result of a (single) sequencing artefact (cf. #764). All samples were collected in Slovenia.

![pic](https://user-images.githubusercontent.com/102166254/175001656-4b751193-fbd8-4a31-8bf3-96ccd9d0649c.PNG)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2b0c5_2bbd70.json?branchLabel=Spike%20mutations&c=gt-S_494,420

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AE102K%2CORF1a%3AP380L%2CORF1a%3AI4098T%2CORF1b%3AE787G%2CORF1a%3AV4216I%2CS%3AS494P%2CS%3AV1128A%2CS%3AF59S%2CS%3AD420N%2CS%3AY449N&

EPI_ISL_13251406
EPI_ISL_12284821
EPI_ISL_13251514
EPI_ISL_13271922
EPI_ISL_13272223
EPI_ISL_13253132
EPI_ISL_13272001
EPI_ISL_13253296
EPI_ISL_13253164
EPI_ISL_13253550
EPI_ISL_13253416
EPI_ISL_13368501

**Comment by silcn** [comment]
@agamedilab I'd say close the issue for now but keep monitoring it in case it spills over into the general population like BA.1.23.

Side note: Slovenia does quite a lot of sequencing of chronic infections, as can be seen by the unusually high frequency of S:340 mutations there.
