### ISSUE TITLE
BA.4 sublineage with S:681R, C6286T (50 seq. on Usher as of 01.08.22. US only. Mostly Utah, but also Wyoming, Minnesota, Illinois, New York)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#779]
Proposal for a sublineage of BA.4
Earliest sequence: 22.05.2022 (USA)
Countries detected: USA

Defining mutations:
A23604G = S:681R
C6286T

Small sublineage of BA.4 probably worth monitoring because of S:P681R.

![pic](https://user-images.githubusercontent.com/102166254/175026720-95622efa-1cc7-48e3-a3e4-2cfb18a81dea.PNG)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8105_301dc0.json?branchLabel=Spike%20mutations&c=gt-nuc_6286,23604

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C6286T%2CA23604G&pangoLineage=BA.4*&

EPI_ISL_13166785
EPI_ISL_13272616
EPI_ISL_13273297
EPI_ISL_13286271
EPI_ISL_13394422

**Comment by eastein** [comment]
@trvrb what do you think of this? Any thoughts on if these could be erroneous reads? This is one of those mutations that everyone was hoping against hope we wouldn't see in the Omicron lineages..

**Comment by agamedilab** [comment]
10 seq. on as of 28.06.22.

![grafik](https://user-images.githubusercontent.com/102166254/176138147-34f63009-4da2-4e60-8537-0b29feb17cfe.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43061_ac04e0.json?branchLabel=aa%20mutations&c=gt-S_681

**Comment by agamedilab** [comment]
50 seq. on Usher as of 01.08.22. US only (mostly Utah,  but also Wyoming, Minnesota, Illinois, New York).

![grafik](https://user-images.githubusercontent.com/102166254/182093735-309f252d-701f-48b8-be9b-d62f2e2f2c42.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e0af_779990.json?branchLabel=aa%20mutations&c=gt-nuc_6286&label=nuc%20mutations:C6286T,A23604G

No growth advantage vs. BA.4 in US 6 months:

![grafik](https://user-images.githubusercontent.com/102166254/182095099-6f45e59d-ad93-475f-a989-d924107cb51f.png)
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?pangoLineage=BA.4*&aaMutations1=S%3AP681R&pangoLineage1=BA.4*&analysisMode=CompareToBaseline&

**Comment by InfrPopGen** [comment]
Thanks for proposing this @agamedilab  . As outlined [here,](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/) new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations.
There doesn't seem to be a clear epidemiological event associated with this clade, we therefore haven't designated this at this point.
