### ISSUE TITLE
Request for lineage A.29 with several spike mutations shared with variants of concern (Y449H, N501Y, H655Y) 

### ISSUE THREAD

**Issue by SVN-PhD** [cov-lineages/pango-designation#78]
## Proposal for lineage A.29

by Scott Nguyen, PhD (scott.nguyen@dc.gov) and Janis Doss, PhD (janis.doss@dc.gov | @janis0616)
On behalf of the DFS-PHL Molecular Diagnostics Unit 

 
## **Description** 
**Sub-lineage of**: A 
**Earliest sequence**: 2020-08-21 (Gambia | EPI_ISL_1731545) 
**Most recent sequence**: 2021-04-23 (England | EPI_ISL_1830925) 
**Countries circulating**: Gambia / France / United Kingdom / Norway / Ireland / India / Germany / Belgium / Australia / Sweden / USA / Jordan 

During a recent routine sequencing run, the DC Department of Forensic Sciences Public Health Lab came across an unusual isolate that was PANGO lineage A (pangolin 2.4.2, pangoLEARN 2021-05-10). As it is in lineage A, it does not have the spike D614G change. Further analysis of the isolate and of publicly available genomes in GISAID reveal a collection of at least 113 lineage A sequences with shared mutations with the unusual isolate we sequenced. 

These sequences are related to A.27 but have distinct mutations in spike when compared to A.27. It does not have spike mutations L18F, L452R, A653V, D796Y, and G1219V. 

The proposed lineage A.29 shares spike N501Y with A.27 and other variants of concern/interest. Additionally, it shares spike H655Y with A.27 and variant of concern P.1. 

There are additional distinct spike mutations that separate it from A.27. One notable change include Y449H in the receptor binding domain, described by Koenig et al. https://doi.org/10.1126/science.abe6230. Additionally, it shares spike L141Δ, G142Δ, N211Δ, and L212I with PANGO N.10 as described by Resende et al. at https://virological.org/t/identification-of-a-new-b-1-1-33-sars-cov-2-variant-of-interest-voi-circulating-in-brazil-with-mutation-e484k-and-multiple-deletions-in-the-amino-n-terminal-domain-of-the-spike-protein/675. Additional spike mutations include F140L, Y144F, and F565L.  

The phylogenetic tree show potential outbreaks throughout the United Kingdom.

## Genomes
[accessions_list.txt](https://github.com/cov-lineages/pango-designation/files/6461546/accessions_list.txt)

## Defining Mutations
| Gene  | AA Changes | 
| ------------- | ------------- | 
| S gene | F140L | 
| S gene | L141del | 
| S gene | G142del | 
| S gene | Y144F | 
| S gene | N211del | 
| S gene | L212I | 
| S gene | Y449H | 
| S gene | N501Y | 
| S gene | F565L | 
| S gene | H655Y | 
| NSP1 | V86F | 
| NSP4 | A446V | 
| NSP6 | M86I | 
| NS8 | E92K | 
| M | I82S | 
| N | D22Y | 

## Phylogenetic Tree
Proposed A.29 sequences are in blue, related A.27 sequences are in dark brown.
![tree5_github_v1](https://user-images.githubusercontent.com/15314705/117873249-92dbf480-b26d-11eb-8202-9c18d25fe4a6.png)

**Comment by SVN-PhD** [comment]
Some additional updates for this proposed lineage. I downloaded all genomes with the GISAID clade S designation and built this tree through Augur v12.0.0. Some lower quality genomes were dropped after running through the Augur pipeline. The closest lineages are A23 and A23.1. Spike mutations N501Y and F565L should be sufficient in differentiating this lineage from other lineages.

![Screenshot from 2021-05-21 09-13-05](https://user-images.githubusercontent.com/15314705/119145607-d0801080-ba17-11eb-9277-70645cde8245.png)

**Comment by chrisruis** [comment]
Thanks @SVN-PhD for submitting this. We've added this lineage as A.29 in [v1.2.8](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.8)
