### ISSUE TITLE
Potentially new BA.5.1 sub-lineage with ORF1b:T2548I and ORF1a:T4161I mutation in Ancash (Peru)

### ISSUE THREAD

**Issue by OrsonMM** [cov-lineages/pango-designation#780]
**Description**

New possible omicron sub-lineage with ORF1b:T2548I and ORF1a:T4161I mutation proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

BA.5 (EPI_ISL_13142047) firts detected was from Ancash (Peru), too. Probable coincidence or maybe BA.5 were circuling before in Peru.  

**Earliest sequence:** 2022-05-14
hCoV-19/Peru/ANC-INS-17411/2022 (EPI_ISL_13142047)

**Most recent sequence:** 2022-06-07 
hCoV-19/Peru/LIM-INS-19053/2022 (EPI_ISL_13410131)

**Countries circulating:**
Peru (14), Italy (1)

**Evidence:**

![15_genomas](https://user-images.githubusercontent.com/12600107/175122850-f1c67563-6adf-42c8-b8ed-1ccfc692d150.JPG)

![usher](https://user-images.githubusercontent.com/12600107/175122867-88fefe56-d327-4daf-9b4f-044625e5f131.JPG)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_acbc_369ae0.json?c=pango_lineage&label=nuc%20mutations:C12747T

** Genomes**

EPI_ISL_13142047
EPI_ISL_13410191
EPI_ISL_13410192
EPI_ISL_13314213
EPI_ISL_13409860
EPI_ISL_13409861
EPI_ISL_13409862
EPI_ISL_13410190
EPI_ISL_13314030
EPI_ISL_13409854
EPI_ISL_13409855
EPI_ISL_13409856
EPI_ISL_13409857
EPI_ISL_13340731
EPI_ISL_13410131

**Comment by Vjimenez-vasquez** [comment]
Hi there @OrsonMM !! 
##Some weeks ago I conducted a phylogenetic analysis to track the international affiliations of this first BA.5 detected in our country (Peru). 

<img width="1294" alt="global_phylogeny_BA 5" src="https://user-images.githubusercontent.com/89874227/175127163-018dd4c2-8a4e-42d2-96d9-d20258743b9b.png">

##This image shows the proximity between this first genome and Austria, Belgium, USA and, of course, Italy ! 

<img width="1533" alt="peru_phylogeny_BA 5" src="https://user-images.githubusercontent.com/89874227/175127168-b6f9d935-2867-43f3-871d-b1ff43f7e371.png">

**Comment by FedeGueli** [comment]
This seems a sublineage of BA.5.1 ( characterized by 29666T) not of BA.5 cc @OrsonMM

**Comment by OrsonMM** [comment]
![image](https://user-images.githubusercontent.com/12600107/175954787-78436da9-7cf4-404d-a2ae-63a9f31959d8.png)
![image](https://user-images.githubusercontent.com/12600107/175954892-d51675ae-7822-463c-8013-0a8582a4639c.png)
![image](https://user-images.githubusercontent.com/12600107/175954951-183be573-dc08-40f7-9064-59ad2cfe65f0.png)

**Comment by OrsonMM** [comment]
Still growing and spread in more regions inside Peru

![image](https://user-images.githubusercontent.com/12600107/178306052-84e5fc4d-2f0a-4bd0-910d-728e8ae485ad.png)

![image](https://user-images.githubusercontent.com/12600107/178306182-66ca5711-3897-4e4f-b0ac-0a06088ab996.png)

**Comment by OrsonMM** [comment]
![image](https://user-images.githubusercontent.com/12600107/179520830-0be965a3-6c64-49e7-98c2-dd74a184f54f.png)

**Comment by OrsonMM** [comment]
Still growing and spread in more regions inside Peru

![image](https://user-images.githubusercontent.com/12600107/180230947-8e9c7675-c28e-45e6-872e-8e660eda50b9.png)

**Comment by InfrPopGen** [comment]
Thanks @OrsonMM  As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

There doesn't seem to be a clear epidemiological event associated with this clade, we therefore haven't designated this at this point
