### ISSUE TITLE
BA.5.1 with Delta mutation N:D377Y flagged as ML by GISAID

### ISSUE THREAD

**Issue by JosetteSchoenma** [cov-lineages/pango-designation#782]
**Description:**
A BA.5.1, since it has T27438C and C29666T, with Delta mutation N:D377Y/G29402T

Matthijs Welkers @Pregabaline from Amsterdam UMC contacted me last week, after receiving an email from GISAID. It involved a sample that was placed under investigation, because it had markers of multiple lineages ML from both Delta and Omicron variants, which could mean it was a recombinant. After investigating we found that it is probably not a recombinant, because it has only one extra Delta mutation, and at least 3 nucleotides with a higher number, that resemble BA.5.1 and not Delta. 
At the time there were 9 BA.5's with the same Delta mutation. Now there are 35, of which one from Germany that is not a BA.5.1, but a BE.1.

**Earliest Sequence:** 2022/5/13 Israel, odd one with mediocre QC, or 2022/5/24 Ireland
**Most recent Sequence:** 2022/6/14 Ireland
**Countries circulating:** Ireland 14, England 7, Germany 4, Netherlands 3, Norway, Spain, Belgium 2, Israel 1
**Extra Delta mutation:** N:D377Y/G29402T
**Cov-spectrum query:** S:L452R, S:F486V, M:D3N, N:D377Y, T27438C
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AL452R%2CS%3AF486V%2CM%3AD3N%2CN%3AD377Y&nucMutations=T27438C&
**Genomes:**
EPI_ISL_13111202
EPI_ISL_13178280
EPI_ISL_13252459
EPI_ISL_13144224
EPI_ISL_13186646
EPI_ISL_13243887
EPI_ISL_13327947
EPI_ISL_13327948
EPI_ISL_13332197
EPI_ISL_13271192
EPI_ISL_13340113
EPI_ISL_13340122
EPI_ISL_13340191
EPI_ISL_13340213
EPI_ISL_13202210
EPI_ISL_13267493
EPI_ISL_13223976
EPI_ISL_13340108
EPI_ISL_13242703
EPI_ISL_13267720
EPI_ISL_13223996
EPI_ISL_13223997
EPI_ISL_13387892
EPI_ISL_13370674
EPI_ISL_13347130
EPI_ISL_13359693
EPI_ISL_13359723
EPI_ISL_13359749
EPI_ISL_13359769
EPI_ISL_13359782
EPI_ISL_13359875
EPI_ISL_13370758
EPI_ISL_13368809
EPI_ISL_13347173
EPI_ISL_13347183

**Evidence:**
**Sc2rf output:**
The first 3 lines are 2 BA.5's and 1 BA.5.1 as a reference. Please note the Israelian and Irish one with an extra red Delta dot, the German BE.1 at the bottom and 6 English ones with a few N's and 2 extra private mutations. C28849T and G159A.
![image](https://user-images.githubusercontent.com/94831035/175153275-5bc5fddc-5ef7-4d32-bc1b-35e7e4468e8e.png)
**Table with mutations:**
![image](https://user-images.githubusercontent.com/94831035/175157640-9986d6f4-fbd8-4d77-85b8-2eebc73a9f21.png)
Nextclade output: all green QC except for one from Israel and England
![image](https://user-images.githubusercontent.com/94831035/175160112-39684b13-fbd7-4516-bcfd-66ffed4bf672.png)
**Usher tree:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f8fb_37b4d0.json?branchLabel=nuc%20mutations&label=nuc%20mutations:G29402T
![image](https://user-images.githubusercontent.com/94831035/175160259-aa1be695-70e0-457b-aff1-72a3a1bc3e6a.png)

**Comment by JosetteSchoenma** [comment]
I do not think growth advantage would be the main reason to assign this as a sublineage, but mainly because  it would prevent labs from being warned by GISAID. But I made a query anyway. For Ireland the growth advantage over BA.5 would now be 42% CI -28%-113%, so mainly too little samples.
https://cov-spectrum.org/explore/Ireland/AllSamples/Past6M/variants?aaMutations=S%3AL452R%2CS%3AF486V%2CM%3AD3N&aaMutations1=S%3AL452R%2CS%3AF486V%2CM%3AD3n%2CN%3AD377Y&nucMutations1=T27438C&analysisMode=CompareToBaseline&
![image](https://user-images.githubusercontent.com/94831035/175162310-16a77576-06d8-4a83-9d53-811fe47c979d.png)

**Comment by JosetteSchoenma** [comment]
52 samples now. New countries: Switzerland, Austria and the USA.

**Comment by FedeGueli** [comment]
80 samples as today. Its growth slowed down a bit but still above the BA.5 baseline

**Comment by InfrPopGen** [comment]
Thank you @JosetteSchoenma for proposing this. As this one has been declining over the past month, and shows little advantage over its parent or co-circulating lineages, I think it can be closed at least for now.

**Comment by JosetteSchoenma** [comment]
I agree. Also because I believe GISAID has stopped flagging it.
