### ISSUE TITLE
New BA.2.12.1 sublineage with ORF1a:T2967A mutation circulating in USA, Peru and Belgium.

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#784]
**Description**
New possible omicron sub-lineage with ORF1a:T2967A mutation proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**Earliest sequence:** 2022-05-03 
USA/NY-PRL-2022_0506_02H16/2022

**Most recent sequence:** 2022-06-13
USA/AZ-ASU82527/2022

**Countries circulating:**
Peru (46)
USA (7)
Belgium (2)

**Genomes**
[Genomes.csv](https://github.com/cov-lineages/pango-designation/files/8970544/Genomes.csv)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21a07_4c34f0.json?c=pango_lineage_usher&label=nuc%20mutations:T13417C
![Captura de pantalla de 2022-06-23 14-51-22](https://user-images.githubusercontent.com/89021119/175390624-2dee2544-3d6a-49c6-a52b-e344cf39e5e0.png)
![Captura de pantalla de 2022-06-23 15-17-53](https://user-images.githubusercontent.com/89021119/175392037-e7c8264c-bf53-41a7-8f11-acff11f9f584.png)
****

**Proposed lineage name**
BA.2.12.1.X

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BG.3 with 28 newly designated sequences, and 1 updated designation from BA.2.12.1. Defining mutation(s) A9164G (Orf1a:T2967A).

**Comment by Wen1953** [comment]
Thanks @InfrPopGen
