### ISSUE TITLE
Proposal for a Sublineage of BA.2.13 with Spike T941S

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#785]
**Description**
 **Sub-lineage of**: BA.2.13
**Earliest sequence**: 2022-4-9 (USA, Florida)
**Most recent sequence**: 2022-6-19 (USA, Nebraska) Countries circulating: Mostly the US (315 of 333 according to GISAID)
**Number of Sequences**: 375 in the Usher tree; 333 in GISAID search for L452M + T941S  
**Substitutions on top of BA.13** 
Spike: T941S 
Nucleotide: A24383T, C16954T  

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_b285_4d78c0%20-%20BA.2.13%20%2B%20T941S.json
**Evidence**
Relative weekly growth advantage (20%) via CovSpectrum over BA.2.13* in the last three months in the US:
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?pangoLineage=BA.2.13*&aaMutations1=S%3AT941S&pangoLineage1=BA.2.13*&analysisMode=CompareToBaseline& 
![Screen Shot 2022-06-23 at 5 58 45 PM](https://user-images.githubusercontent.com/33738461/175421875-0a9939bb-f8d0-42ef-95c6-4995d89d52c7.png)

Relative weekly growth advantage (16%) via CovSpectrum over S:L452Q + S:S704L in the last three months in the US: 
https://cov-spectrum.org/explore/United%20States/AllSamples/Past2M/variants?aaMutations=S%3AL452Q%2CS%3AS704L&aaMutations1=S%3AL452Q%2CS%3AS704L%2CS%3AV1264L%2CN%3AT282I&analysisMode=CompareToBaseline& 
![Screen Shot 2022-06-23 at 5 58 58 PM](https://user-images.githubusercontent.com/33738461/175422092-3f90ff4f-6a54-4134-a750-a9d5dc9cccb5.png)

Genomes
[GISAID_hcov-19_ids_2022_06_23_21_46 - L452M + T941S GISAID search results.csv](https://github.com/cov-lineages/pango-designation/files/8971525/GISAID_hcov-19_ids_2022_06_23_21_46.-.L452M.%2B.T941S.GISAID.search.results.csv)

**Comment by FedeGueli** [comment]
Hi @ryhisner i got an error in the usher tree you linked.

**Comment by ryhisner** [comment]
Thanks for telling me, @FedeGueli. I have to run right now, but I'll fix it as soon as I can.

**Comment by AngieHinrichs** [comment]
I removed some extra stuff from the end of the link, this seems to work:

https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_b285_4d78c0%20-%20BA.2.13%20%2B%20T941S.json

**Comment by ryhisner** [comment]
Quick update on this. There are now **482** members of this lineage on the Usher tree, though I suspect that's an undercount as I found several others the clearly belong there but were instead placed in a weird tree with a bunch of garbage sequences (by Curative and such). 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_371d3_919f02022-7-2.json

Weekly growth advantage in the United States relative to BA.2.13 without S:T941S over the past three months (using a more precise nucleotide CovSpectrum query) has increased to **37%** with CI of 31%-43%. https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=A23767G+%26+C22792T+%26+%21A24383T&variantQuery1=A23767G+%26+C22792T+%26+A24383T&analysisMode=CompareToBaseline&
Worldwide, the same comparison returns a weekly growth advantage of **51%** with CI of 46%-57%. 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=A23767G+%26+C22792T+%26+%21A24383T&variantQuery1=A23767G+%26+C22792T+%26+A24383T&analysisMode=CompareToBaseline&

Relative to BA.2.12.1 in the United States over the past 3 months, this proposed lineage has a **17%** growth advantage, one point higher than when it was first proposed, and now the confidence intervals have tightened to 12-22%. https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=S%3AL452Q+%26+S%3AS704L&variantQuery1=A23767G+%26+C22792T+%26+A24383T&analysisMode=CompareToBaseline&

**Comment by AngieHinrichs** [comment]
> I found several others the clearly belong there but were instead placed in a weird tree with a bunch of garbage sequences

@ryhisner can you send some example names/IDs?  I might be able to clean that up a bit.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.13.1 with 415 newly designated sequences, and 25 updated designations from BA.2, and 2 updated from BA.2.13. Defining mutation(s) A24383T (S:T941S).
