### ISSUE TITLE
 Fast BA.5.1 sublineage carrying Orf6:D6G (3455seqs) circulating widely in Europe

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#786]
Here i want to propose a  sublineage of BA.5.1 defined by Orf6:D6G (A27218G) that seems growing fast in Europe, spotted by @olias120676

The usher tree pots this lineage in two different branches of BA.5.1:
The big one with 267 Seqs has Orf6:D6G as defining mutation
while the small one with 39 sequences apparently has Orf1ab:M4855V (=Orf1b:454V=A14827G)  that precedes Orf6:D6G,
just because there are 4 BA.5.1 sequence with it and without orf6
Orf6:D6G in this smaller sublineage is accompanied by C5221T and followed by C29077T as main branch circulating in Ireland.

Sincerely i think this is one only lineage also temporally the first sequences of the smaller branch with  Orf1ab:M4855V have already Orf6:D6G (as EPI_ISL_13030929, Luxembourg 12-5-22) and that date corresponds very well to the first sequences if the bigger branch without Orf1ab:M4855V ( EPI_ISL_13099505 Spain 10-5-2022).

Here the two usher links:
1
Small branch with Orf1ab:M4855V (=Orf1b:454V=A14827G) 39 Sequences
![Schermata 2022-06-24 alle 00 44 37](https://user-images.githubusercontent.com/87669813/175427134-8dc8af72-3b55-466b-b1a1-9b7b7c504e42.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1729b_4db470.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A14827G

2
Big branch starting with Orf6:D6G (A27218G) 
![Schermata 2022-06-24 alle 00 51 07](https://user-images.githubusercontent.com/87669813/175427843-2c433594-477c-4ca7-9b38-90082176283a.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1729b_4db460.json?branchLabel=aa%20mutations&c=gt-nuc_14827&label=nuc%20mutations:A27218G

(Note that A14827G appears to be masked in the clade without A14827G )

I ask help from @AngieHinrichs @chrisruis  @corneliusroemer here to understand if it is one only or two distinct BA.5.1 sublineages with Orf6:D6G.

I have included, in the following sequence list, just sequences without  Orf1ab:M4855V (=Orf1b:454V=A14827G)
[contributors (6).csv](https://github.com/cov-lineages/pango-designation/files/8971871/contributors.6.csv)

Said that, the real important thing is that this sublineage seems to grow very fast vs BA.5.1 baseline +45%:

![Schermata 2022-06-24 alle 00 57 31](https://user-images.githubusercontent.com/87669813/175428571-d42d8a57-95d8-4da7-8621-3000049cfb23.png)
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=M%3A3N&nucMutations=12160A%2C29666T&aaMutations1=M%3A3N%2CORF6%3AD6G&nucMutations1=12160A%2C29666T&analysisMode=CompareToBaseline&

And considering just the sequences without Orf1ab:M4855V (=Orf1b:454V=A14827G) the advantage is skighty bigger:
![Schermata 2022-06-24 alle 01 00 13](https://user-images.githubusercontent.com/87669813/175428830-6a15beec-a720-43cf-a0a8-f90f2cfaf6f3.png)

This sublineage is circulating widely in Europe: Spain, Uk, Ireland, Belgium, Germany but it has landed already in Chile, Israel, Usa, Singapore
International Overview: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants/international-comparison?aaMutations=M%3A3N%2CORF6%3AD6G%2COrf1b%3A454M&nucMutations=12160A%2C29666T&aaMutations1=M%3A3N%2CORF6%3AD6G%2COrf1b%3A454M&nucMutations1=12160A%2C29666T&

**Comment by FedeGueli** [comment]
510 total sequences as today.

**Comment by FedeGueli** [comment]
982 sequences as today

**Comment by FedeGueli** [comment]
3455 sequences as today. it represents 4,85% of BA.5.1 sequences in the last month (3.85% cumulative)
Its growth as share of global samples it is steady but clear:
![Schermata 2022-08-01 alle 01 26 10](https://user-images.githubusercontent.com/87669813/182049595-e12959e1-314a-4ec0-84c0-3ad16968d55a.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=NextCladePAngoLineage%3ABA.5.1*+%26+ORF6%3AD6G+&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.1.9 with 161 newly designated sequences, and 52 updated designations from BA.5.1. Defining mutation(s) C5221T, A27218G (ORF6:D6G).
