### ISSUE TITLE
Proposal for a Sublineage of BA.2 with Spike Y248N and R346T, primarily in India

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#787]
**Description** 
**Sub-lineage of**: BA.2
**Earliest sequence**: 2022-4-16 (India, Delhi) EPI_ISL_12752570 
**Most recent sequence**: 2022-6-18 (Denmark) EPI_ISL_13420219 
**Countries circulating**: Primarily India; very recently in UK, Denmark, & US
 **Number of Sequences**: 241 on the USHER tree 
**Substitutions on top of BA.2**:
 Spike: R346T, Y248N 
Nucleotide: G22599C, T22304A 

A GISAID search for R346T + Y248N returns 224 sequences, 138 of which are from India (17 of which were only uploaded to GISAID today). In addition, there have been seven airport-surveillance sequences from Japan and three from Singapore, all with travel histories in India. Given the low level of sequencing in India, this likely means the vast majority of global sequences with these two mutations are circulating in India. It has arrived in Europe and the US only recently but has grown rapidly in both (though absolute numbers remain very small with 28 in Europe and 33 in the US).

USHER Tree
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_284ad_4e59f0%20-%20BA.2%20%2B%20Y248N%20%2B%20R346T.json 
 
**Evidence**
Weekly growth advantage via Cov-Spectrum compared to BA.2* in the last three months in India: 36% CI[25%, 48%] 
https://cov-spectrum.org/explore/India/AllSamples/Past3M/variants?pangoLineage=BA.2*&variantQuery1=G22599C+%26+T22304A&analysisMode=CompareToBaseline&
![Screen Shot 2022-06-23 at 7 19 24 PM](https://user-images.githubusercontent.com/33738461/175430541-1c7c540a-503a-4921-973f-830b57f3342e.png)

Using @shay671‘s queries, G22599C + T22304A has a -11% CI[-30%, -9%] weekly relative growth disadvantage compared to BA.4 in India, and a -43% CI[-55%, 31%] weekly growth disadvantage compared to BA.5. 

However, though the numbers are far too small to be reliable yet, so far it has held its own against BA.5 in the US with (weekly GA relative to BA.5: +2% CI[-26%, 30%]) and in Europe (weekly GA relative to BA.5: +31% CI[-14%, 76%]).

**Genomes**
[GISAID_hcov-19_ids_2022_06_23_23_14 - Y248N + R346T.csv](https://github.com/cov-lineages/pango-designation/files/8971934/GISAID_hcov-19_ids_2022_06_23_23_14.-.Y248N.%2B.R346T.csv)

**Comment by silcn** [comment]
This is another one where many sequences are missing on cov-spectrum because most samples from Karnataka only give a month of collection. 
@chaoran-chen obviously without an exact date of collection these can't be plotted on the graphs, but would it at least be possible to show them in the total figures and sequence list?

**Comment by FedeGueli** [comment]
260 sequences as today,
i noticed a little cluster of 14 seqs with defining mutations reverted in this sublineage tree
![Schermata 2022-06-25 alle 15 31 27](https://user-images.githubusercontent.com/87669813/175775739-9783f7f2-9d2a-4c8b-be18-3bb6660646f2.png)

and that there is a suspicious common mutation popping up in two different branches with and without S:248N: A19218G
![Schermata 2022-06-25 alle 15 28 09](https://user-images.githubusercontent.com/87669813/175775582-71b1dea0-35d6-455c-a93d-6bd376dd758d.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d802_70bd10.json?branchLabel=back-mutations&c=gt-nuc_22304,22599&label=nuc%20mutations:G22599C

cc @AngieHinrichs 
:

**Comment by chaoran-chen** [comment]
@silcn, sequences without a date or only with a partial date are not included if a date filter is active. But you can get the full list if you choose "All times".

**Comment by FedeGueli** [comment]
421 as today rapid growth in India  and ongoing exportations to other countries.

i think it deserves a designation soon @corneliusroemer @chrisruis @InfrPopGen @AngieHinrichs (a designation could help to get a clearer landscape for the apparent rise of BA.2.75)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1d155_e31570.json?c=country&label=nuc%20mutations:T22304A

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.76 with 170 newly designated sequences, and 10 updated designations from BA.2. Defining mutation(s) T22304A (S:Y248N).

**Comment by FedeGueli** [comment]
Hi @InfrPopGen @AngieHinrichs @chrisruis 
@corneliusroemer 
( cc @ryhisner ):
I was looking at S:346 mutated lineages sampled in the two last weeks and i noticed that BA.2.76 tree before gaining S:248N is missassigned on Usher as BA.2.10 and as result BA.2.76 appears falsely to be a sublineage of BA.2.10.
This is due to the long known C25416T Nucleotide substitition that seems to attract every sequence to BA.2.10 even if they dont carry Orf1b:959P BA.2.10 defining mutation.

Actually there are 356 sequences with 25416T+S:346T+S:248N
+ 131 with just 25416T+S:346T

I wonder if broadening BA.2.76 to 25416T+S:346T
will solve that without damaging the specificity of this sublineage

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice14_genome_8561_b5d4a0.json?branchLabel=aa%20mutations&c=gt-S_248&label=nuc%20mutations:G22599C

**Comment by FedeGueli** [comment]
Edited above.

**Comment by JosetteSchoenma** [comment]
That's great. Thank you! Good job!

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs great!!  
i just found the ghost BA.2.76 tree highlighted by Josette:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice9_genome_8561_b5d4a0.json?c=pango_lineage_usher&label=nuc%20mutations:T22304A
we arrived to the same doubt and question from totally different routes ;)

**Comment by AngieHinrichs** [comment]
Yes, BA.2.76 being split into two branches (both out-of-place in BA.2.10) was a separate series of unfortunate events involving a few sequences with reversions on 26577 (M:19), and I hope to have that fixed too, in ~3.5 hours now.  Thanks again to both of you for pointing that out!  I don't have a systematic way to find these split lineages, so your scrutiny is really helpful.

[If that particular split keeps happening then I might need to add an extra BA.2.76_rev26577 label on the big tree, a la BA.2.3.9_rev10198 in case anyone has come across that and wondered what the heck.  In the tree for pangolin, _alt and _rev label suffixes are stripped so even when there are multiple branches in the tree they still get the same official lineage assigned.]

**Comment by Mydtlwn** [comment]
It may be necessary to make a new nomination for its sub-plants. Please pay more attention to the new sequence that has been uploaded!
