### ISSUE TITLE
 BA.5.2.1 sublineage defined by S:T259A (185 sequences) and then Orf1a:A2080V (169 Sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#788]
This BA.5.2.1 sublineage was spotted by @olias120676 is defined by S:T259A mutation
Tree:
![Schermata 2022-06-24 alle 01 25 16](https://user-images.githubusercontent.com/87669813/175431001-5c97a957-a83e-4866-a3e5-9b6bf685550e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_168ca_4db300.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C241T,T670G,C1627T,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,A27038G,C27807T,C27889T,A28271T,C28311T,A28330G,G28881A,G28882A,G28883C,A29510C

More than 90% of sequences of this sublineage carry also Orf1a:A2080V and C28744T

Nr of sequences: 185
Countries: 
![Schermata 2022-06-24 alle 01 28 35](https://user-images.githubusercontent.com/87669813/175431265-a79e6271-02ce-4dcb-b89b-cc5cddfc1178.png)
List of sequences:
[contributors (7).csv](https://github.com/cov-lineages/pango-designation/files/8971957/contributors.7.csv)
Covspectrum Overview: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3A486V%2CS%3A259A%2CM%3A3N&

Growth advantage around 17% vs BA.5.2.1 in UK
![Schermata 2022-06-24 alle 01 33 39](https://user-images.githubusercontent.com/87669813/175431673-f598c0d8-dcc2-4e1c-bea3-61d29725f5e6.png)
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=M%3A3N&nucMutations=12160A%2CC1627T%2CA28330G&aaMutations1=S%3A486V%2CS%3A259A%2CM%3A3N&analysisMode=CompareToBaseline&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.4 with 80 newly designated sequences, and 2 updated designations from BA.5.21. Defining mutation(s) A22337G (S:T259A).
