### ISSUE TITLE
Potential BA.2*/BA.1* recombinant with likely breakpoint at ORF3a or M (57 Seqs as of 2022-06-23 mainly in the US)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#789]
### Description
**Recombinant between**: BA.2* & BA.1*
**Earliest sequence**: 2022/04/11 (US-NV)
**Most recent sequence**: 2022/06/08 (Mexico-CMX)
**Countries circulating**: mainly in the US (NV, NC. TX, FL, CA, CO, HI, UT, GA, AK, MI), also found in Mexico, Puerto Rico, Denmark and Japan (1 sequence each)
**Likely breakpoint**: between 26063 and 26528 (ORF3a or M protein).
**Mutations on branch**: C5407A

**Conserved Nuc mutations** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/175454631-11a366e2-f59e-4599-94af-bf5f0e2ef11a.png)
**Cov-spectrum query**: T27384T, 29510A, G4184A, C4321T, C5407A, C26060T

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/175455016-c56cc26a-5924-4abd-bd69-414e98e18be1.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_7c9c_50d810.json?c=gt-nuc_5407&l=scatter&scatterY=gt

### Genomes:
EPI_ISL_13232380, EPI_ISL_12744954, EPI_ISL_12758419, EPI_ISL_12639223, EPI_ISL_13367152, EPI_ISL_13371719, EPI_ISL_12598008, EPI_ISL_12660509, EPI_ISL_13217702, EPI_ISL_13232367, EPI_ISL_12756147, EPI_ISL_12764778, EPI_ISL_13269937, EPI_ISL_13279617, EPI_ISL_12888257, EPI_ISL_13021615, EPI_ISL_13315743, EPI_ISL_13308114, EPI_ISL_13310036, EPI_ISL_12613417, EPI_ISL_12613405, EPI_ISL_13335188, EPI_ISL_12806432, EPI_ISL_12530393, EPI_ISL_12592420, EPI_ISL_12867039, EPI_ISL_13124709, EPI_ISL_13114935, EPI_ISL_13124708, EPI_ISL_13109862, EPI_ISL_13152160, EPI_ISL_13156449, EPI_ISL_12612486, EPI_ISL_12613271, EPI_ISL_12613234, EPI_ISL_12719546, EPI_ISL_12867110, EPI_ISL_12867297, EPI_ISL_12886382, EPI_ISL_12895609, EPI_ISL_12888812, EPI_ISL_12933226, EPI_ISL_12962651, EPI_ISL_12962847, EPI_ISL_12962642, EPI_ISL_13071586, EPI_ISL_13080180, EPI_ISL_13080362, EPI_ISL_12302291, EPI_ISL_12505261, EPI_ISL_12660241, EPI_ISL_13220188, EPI_ISL_13405347, ON660428.1, ON788607.1, ON788425.1, ON660081.1

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAP with 69 newly designated sequences, and 0 updated designations.
