### ISSUE TITLE
A New Potential lineage (T.1) specifically located in Campania, Italy, is spreading exponentially.

### ISSUE THREAD

**Issue by agrimaldi93** [cov-lineages/pango-designation#79]
### **By**

Antonio Grimaldi, Telethon Institute of Genetics and Medicine, Armenise/Harvard Laboratory of Integrative Genomics, Davide Cacchiarelli's Group. Naples, Italy.

### **Description**

We report a new potential B.1.1.7 sublineage specifically located in Campania, Italy. It was identified because its frequency is rapidly growing in Campania, particularly near Naples.

**Sublineage of:** B.1.1.7

**Countries circulating:** To date about ~556 samples have been identified in the world, almost all located in Italy. A couple of sequences also in Spain and Sweden.

**Earliest date:** 2021-02-03
**Most recent date:** 2021-05-01

### **List of Genomes:**
[Samples_new_sub.xlsx](https://github.com/cov-lineages/pango-designation/files/6465861/Samples_new_sub.xlsx)

### The defining SNPs:
Spike A570D, 
Spike D614G, 
Spike D1118H, 
Spike H69del, 
Spike N501Y, 
Spike P681H, 
Spike S982A, 
Spike T716I, 
Spike V70del, 
Spike Y144del, 
N D3L, 
N G204R, 
N R203K, 
N S235F, 
**NS7a T120I**, 
**NS8 H112Y**, 
NS8 Q27stop, 
NS8 R52I, 
NS8 Y73C, 
**NSP2 Y316C**, 
NSP3 A890D, 
NSP3 I1412T, 
NSP3 T183I, 
**NSP3 T1306I**, 
NSP6 F108del, 
NSP6 G107del, 
NSP6 S106del, 
NSP12 P323L

### Evidences:
**Here is the Campania phylogenetic tree for SARS-CoV-2, with the suggested lineage highlighted in dark blue.**

![new_lin_Campania](https://user-images.githubusercontent.com/53193948/117971419-2d9a0900-b32a-11eb-9b1e-251e10bdd04c.png)

**The map of Samples distribution in Campania:**

![newlin](https://user-images.githubusercontent.com/53193948/117971369-1c50fc80-b32a-11eb-9e9f-5545e256e979.png)

**Please also find attacched a subset of world SARS-CoV-2 tree**, showing that the samples actually clusterize in one monophyletic clade (downloaded from GISAID) which also has internal nodes. Colors of node points indicate Bootstrap values, thus showing the extremely **high statistical strength** of the phylogenesis: 

![Rplot07](https://user-images.githubusercontent.com/53193948/117974342-c1210900-b32d-11eb-8cab-f9ba6bdb93e4.png)

**Comment by agrimaldi93** [comment]
**UPDATE**
After only 2 weeks, the sequences belonging to the proposed lineage doubled. 
Now there are 961 sequences on GISAID.  While the vast majority of the samples where collected near Naples, Italy, some of them where recently collected also in Spain, England and Sweeden, suggesting the spreading of the cluster.
**The most recent collection date is 2020-05-20**
Interestingly, the **ORF7a_T120I** mutations is shared with the B.1.617.2 lineage. Since 7a protein is known to have a role in facilitating viral egress (by inhibiting the BST2/tetherin, which was found to impede viral release), this finding may suggesting a functional role of ORF7a_T120I.

**Comment by chrisruis** [comment]
Thanks for submitting @agrimaldi93. We've added this as Q.2 (Q is the alias of B.1.1.7 so Q.2 is equivalent to B.1.1.7.2) in [v1.2.51](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.51) with 1384 sequence designations
