### ISSUE TITLE
BA.5.1 sublineage with Orf6:V5I growing in Europe (152 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#790]
Here another sublineage of BA.5.1 spotted by @olias120676 defined by an Orf6 mutation, as #786.
This one is defined by Orf6:V5I (G27214A)

Tree:
![Schermata 2022-06-24 alle 15 20 55](https://user-images.githubusercontent.com/87669813/175544546-0c5e8265-acb0-4cc8-a0df-60d9356837a9.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39e4d_5b7480.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G27214A

Covspectrum overview:
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf6%3AV5I%2CM%3A3N&nucMutations=12160A&

First sequence: Portugal EPI_ISL_13229883  2022-05-29
Countries:
![Schermata 2022-06-24 alle 15 23 45](https://user-images.githubusercontent.com/87669813/175544979-be1d25e3-9bcf-4a30-b4a8-f428d024535c.png)
Sequence list:
[contributors (9).csv](https://github.com/cov-lineages/pango-designation/files/8976482/contributors.9.csv)

Growth Advantage vs BA.5.1 in the last two months 46%:
![Schermata 2022-06-24 alle 15 26 48](https://user-images.githubusercontent.com/87669813/175545567-b4b24bab-8ae9-4f2c-afed-36d0aaa1af21.png)
 https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=M%3A3N&nucMutations=12160A%2C29666T&aaMutations1=Orf6%3AV5I%2CM%3A3N%2COrf1a%3A135R&nucMutations1=12160A&analysisMode=CompareToBaseline&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.1.2 with 89 newly designated sequences. Defining mutation(s) G27214A (Orf6:V5I).
