### ISSUE TITLE
Proposal for a Sublineage of BE.1 with S:M153I, ORF1a:L454F and/or S:M153I, ORF1a:L454F, S:E1258Q, N:P151L

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#796]
**Description**
**Sublineage of**: BA.5.3.1
**Earliest sequence**: 2022-4-8, South Africa, EPI_ISL_12097378
**Most recent sequence**: 2022-6-19, Denmark, EPI_ISL_13443907
**Countries circulating**: US (23), Denmark (20), UK (17), South Africa (12) Germany (6), Israel (6)
**Number of Sequences**: 113 on GISAID, 122 on USHER tree
**Substitutions on top of BA.5.3.1**
Spike: M153I
ORF1a: L454F
Nucleotide: C1625T, G22021T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_11205_746530.json

Though this lineage originated in South Africa, the bulk of the 113 sequences on GISAID are in Europe, which has 68 (not counting a traveler from Finland whose sequence was detected in Singapore). It appears to be outgrowing BA.5* there, as well as in the US, where there are 23 sequences. It is widespread geographically, with multiple sequences in Israel, Chile, and New Zealand. 

**Evidence**
Weekly growth advantage of 25% (CI: 2%-49%) relative to nextcladePangoLineage:BA.5* in the last two months in Europe according to CovSpectrum:
https://cov-spectrum.org/explore/Europe/AllSamples/Past2M/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=S%3AM153I+%26+ORF1a%3AL454F+%26+nextcladePangoLineage%3ABA.5*&analysisMode=CompareToBaseline&
![Screen Shot 2022-06-25 at 2 31 43 PM](https://user-images.githubusercontent.com/33738461/175786229-ddcd05b5-646e-4ade-ae46-ca6a97abc3fd.png)

Weekly growth advantage of 42% (CI: -13%-97%) relative to nextcladePangoLineage:BA.5* in the last two months in the US according to CovSpectrum:
https://cov-spectrum.org/explore/United%20States/AllSamples/Past2M/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=S%3AM153I+%26+ORF1a%3AL454F+%26+nextcladePangoLineage%3ABA.5*&analysisMode=CompareToBaseline&
![Screen Shot 2022-06-25 at 2 32 54 PM](https://user-images.githubusercontent.com/33738461/175786256-e871f6e9-3490-4a53-8178-aade45dcd9b0.png)

**Genomes**
[GISAID_hcov-19_ids_2022_06_25_18_20.csv](https://github.com/cov-lineages/pango-designation/files/8985362/GISAID_hcov-19_ids_2022_06_25_18_20.csv)

In addition, or perhaps as an alternative to the above proposal, I'd like to propose a sublineage contained within the BA.5 + S:M153I + ORF1a:L454F that has two additional mutations.

**Proposal for a Sublineage of BA.5 with S:M153I, S:E1258Q, N:P151L, & ORF1a:L454F**
**Description**
**Sublineage of**: BA.5.3.1
**Earliest sequence**: 2022-5-18, Norway, EPI_ISL_13406726
**Most recent sequence**: 2022-6-19, Denmark, EPI_ISL_13443907
**Countries circulating**: Europe (53/56 sequences) especially Denmark (20), Germany (8), & UK (7)
**Number of Sequences**: 56 on GISAID, 59 on USHER tree
**Substitutions on top of BA.5** 
Spike: M153I, E1258Q
N: P151L
ORF1a: L454F
Nucleotide: C1625T, G22021T, G25334C, C28725T

Containing approximately half of the sequences in the lineage proposed above, this sublineage is almost entirely confined to Europe. Three sequences from New York are the only cases outside of Europe detected so far. It appears to be growing slightly faster than the larger sublineage. 

USHER Tree
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_11205_746530.json 
![Screen Shot 2022-06-25 at 2 53 03 PM](https://user-images.githubusercontent.com/33738461/175786863-0747ef0d-fcc0-4938-9147-a38892c441da.png)

**Evidence**
Weekly growth advantage of 30% (CI: 2%-58%) relative to nextcladePangoLineage:BA.5* in the last two months in Europe according to CovSpectrum:
https://cov-spectrum.org/explore/Europe/AllSamples/Past2M/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=ORF1a%3AL454F+%26+S%3AM153I+%26+S%3AE1258Q+%26+N%3AP151L+%26+nextcladePangoLineage%3ABA.5*&analysisMode=CompareToBaseline&
![Screen Shot 2022-06-25 at 2 53 53 PM](https://user-images.githubusercontent.com/33738461/175786891-d62634d5-8b3c-4697-9e60-8a1e58a85632.png)

**Genomes**
[GISAID_hcov-19_ids_2022_06_25_18_42.csv](https://github.com/cov-lineages/pango-designation/files/8985394/GISAID_hcov-19_ids_2022_06_25_18_42.csv)

**Comment by FedeGueli** [comment]
Hi @ryhisner very interesting proposal. This is a BE.1 (BA.5.3.1.1 sublineage  =  ORF1a:556K, N:136D, orf1b:M1156I).

**Comment by ryhisner** [comment]
The first sublineage proposed above (BA.5.3.1 + S:M153I, ORF1a:L454F) now has 218 sequences on its Usher tree, up from 122 eight days ago. With six additional sequences uploaded today and three yesterday, the total should now be around 226. 

The second sublineage proposed above (BA.5.3.1 + S:M153I, ORF1a:L454F, S:E1258Q, N:P151L) now has 97 sequences on its Usher tree, up from 59 eight days ago. With five sequences uploaded today and two yesterday, that should put the total around 103.

https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_7680_1a53a0-BA.5.3.1%2B.json

**Comment by Sinickle** [comment]
Hi Ryan, 

I believe this lineage is even more interesting than you realized!
<img width="337" alt="image" src="https://user-images.githubusercontent.com/94097102/178316105-f29a6f12-96fb-45e0-ab09-9a8d69b59af9.png">
There is a 9 nucleotide out of phase deletion that happens on the same branch that introduces these mutations:
<img width="175" alt="image" src="https://user-images.githubusercontent.com/94097102/178316371-0e413ab1-0812-426b-a977-fd9c4754fbd2.png">
But of course USHER doesn't pick up the nucelotide deletions. 

This results in ORF1a:82-84del, orf1a:85V

**Comment by FedeGueli** [comment]
It is about 850 sequences now but not showing any advantage vs ba.5 baseline.

**Comment by agamedilab** [comment]
I was about to propose that as well but then found this issue. 883 seq on the clade starting with S:M153I as of 02.08.22.


![grafik](https://user-images.githubusercontent.com/102166254/182364563-b0f210b3-8e7f-4592-a87d-f5c371342341.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6bc9_909100.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G22021T

**Comment by ryhisner** [comment]
I'm closing this since it's clear by now that BE.1 is growing faster than BE.1 + these mutations.

**Comment by corneliusroemer** [comment]
Just rediscovered this one - may be worth still designating as the S1 mutation is interesting and it helps make sense of BE.1

This lineage got to 7% in Finland, quite significant epidemiologicallly, too. I'd probably start the branch at the big polytomy, with S:153I

**Comment by corneliusroemer** [comment]
About half of this was designated as BE.1.3
