### ISSUE TITLE
Recombinant branch of BA.5 with 27889C (WT) with a growing sublineage defined by Nuc:T3358C, Orf1a:A656V and Orf1a:ORF1a:P1018S - (1017 seqs) arose via recombination with BA.2.5 in Portugal and then spread to France

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#797]
As today all the BA.5 designated sublineages carry C27889T but there are 675 sequences which instead has 27889C (vs 35000 with 27889T) Most of them are artifacts as clearly shown by australian sequences where we could see an apparent increase of 27889C but 90% of them carries also defining mutations of BA.5.2 or Ba.5.3 ( see covspectrum [here](https://cov-spectrum.org/explore/Australia/AllSamples/Past6M/variants?aaMutations=M%3A3N&nucMutations=12160A%2C27889C&).

Instead i found an entirely new branch of BA.5 with C27889T that seems legit and real and it is growing comparably to main BA.5 sublineages.

This is the Usher tree: 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22132_77c1c0.json?branchLabel=aa%20mutations&c=gt-nuc_2232,3317,3358,27889&label=nuc%20mutations:C2232T,C3317T,T3358C
![Schermata 2022-06-26 alle 00 18 34](https://user-images.githubusercontent.com/87669813/175792045-cf3109c1-7ec5-4bb5-8e85-a893286b0cd1.png)

The sublineage i want to propose here is defined , beyond 27889C, by the following mutatons: 
ORF1a:A656V (C2232T), ORF1a:P1018S(C3317T) and T3358C

Sequences list:
[contributors.csv](https://github.com/cov-lineages/pango-designation/files/8985678/contributors.csv)
First sequence: EPI_ISL_13018966|2022-05-16 Portugal
Number of sequences : 56 (3/4 from June , while in May  first 10 samples came from Portugal, France and Switzerland)
Countries:
It has been sampled in 15 different countries (14 Europe  + 1 Israel) 
![Schermata 2022-06-26 alle 00 24 50](https://user-images.githubusercontent.com/87669813/175792189-c9d3b064-1cab-4e66-b0ed-1acd6a459442.png)
Interestingly there are 0 sequences from South Africa, this together with the wide but still limited spread in Europe 
and the quite relevant diversity shown in the tree above ,could suggest this lineage comes from a low/zero sequencing area, likely in Africa.

Covspectrum overview: 
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=M%3A3N%2CS%3A486V&nucMutations=G12160A%2C27889C%2CT3358C&

Growth advantage vs BA.5 with 27889T : around 20%, but if it is true that there is a "reservoir"of this lineage somewhere i would expect this lineage to be equal to BA.5 baseline settling down toward the lower C.I. interval of  the covspectrum query:
![Schermata 2022-06-26 alle 00 39 28](https://user-images.githubusercontent.com/87669813/175792456-2dfa7ce3-c22e-4eab-afcd-6bf7081fd3ce.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=M%3A3N%2CS%3A486V&nucMutations=G12160A%2C27889T&aaMutations1=M%3A3N%2CS%3A486V&nucMutations1=G12160A%2C27889C%2CT3358C&analysisMode=CompareToBaseline&

cc @AngieHinrichs @shay671 i would like to highlight this to you both cause  i know you both keep updated a "mutation route
 from root " for every single sublineage and this one,  similarly to what happened with the 9866C thing  in BA.2 discovered by @corneliusroemer, could be of some relevance i think.

**Comment by FedeGueli** [comment]
Alteenative hypothesis it gained 27889C via recomb ahead of Orf7ab with BA.2. It could not either be excluded or proven.

**Comment by FedeGueli** [comment]
207 sequences of this undesignated branch as today.
Spread in 24 countries


![Schermata 2022-07-14 alle 00 44 12](https://user-images.githubusercontent.com/87669813/178849540-c28f0556-f0c6-4946-a4cc-dda26c6d0762.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e8de_f493c0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C2232T,C3317T,T3358C

It seems to have a discrete growth advantage in France where it has reached around 1% of total sequences 
https://cov-spectrum.org/explore/France/AllSamples/Past1M/variants?aaMutations=M%3A3N&nucMutations=G12160A%2C27889C%2CT3358C&aaMutations1=M%3A3N%2CS%3A486V&nucMutations1=G12160A%2C27889C%2CT3358C&
![Schermata 2022-07-14 alle 00 45 38](https://user-images.githubusercontent.com/87669813/178849685-36c08f29-eb95-429f-adc6-dfc9dea5aa2c.png)

**Comment by FedeGueli** [comment]
214 sequences as today on covspectrum.
Growth advantage vs NCPL BA.5* baseline in France is 30%:
https://cov-spectrum.org/explore/France/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5*&aaMutations1=M%3A3N%2CS%3A486V&nucMutations1=G12160A%2C27889C%2CT3358C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
490 seqs as today

**Comment by FedeGueli** [comment]
New more efficient CvSpectrum query:
https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5*+%26+27889C+%26+T3358C+&aaMutations1=M%3A3N%2CS%3A486V&nucMutations1=G12160A%2C27889C%2CT3358C&

finds 559 seqs of this lineage

**Comment by FedeGueli** [comment]
765 sequences as today on usher:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14625_e1ef40.json?branchLabel=aa%20mutations&c=gt-nuc_3358&label=nuc%20mutations:C21807T
![Schermata 2022-08-06 alle 10 05 42](https://user-images.githubusercontent.com/87669813/183240427-d740480a-a331-4326-bb38-2e80b8de04bc.png)

New CoVspectrum query for this sublineage
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=NextCladePangoLineage%3ABA.5*++%26+T3358C&nucMutations1=C6606T%2CC15960T%2CG17278T%2CT27438C%2CT27889C&

I think it is worth a designation it is the last big undesignated BA.5 branch ( beyond the ones with C1627T without 28330G)

**Comment by FedeGueli** [comment]
I just noticed a subclade of this one with S:82L that seems growing in Germany with a good rate (50seqs).

i will monitor it:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=NextCladePangoLineage%3ABA.5*++%26+T3358C+%26+S
![Schermata 2022-08-06 alle 10 13 28](https://user-images.githubusercontent.com/87669813/183240731-a7cc6130-780c-4dcc-ad36-8bca1f7c2c92.png)
%3A82L&nucMutations1=C6606T%2CC15960T%2CG17278T%2CT27438C%2CT27889C&

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14625_e1ef40.json?branchLabel=aa%20mutations&c=gt-nuc_3358&label=nuc%20mutations:C21807T

**Comment by FedeGueli** [comment]
Despite not being one of the most trasmissible branches of BA.5 this lineage keeps circulating in Europe especially in France and Germany (where it picked up S:82L 70seqs) and now it is well beyond the 1000 seqs wall.

With this GISAID query (NSP3_P200S,NSP2_A476V) i can found 1085 viruses 

And super interestingly i think i found the recombination event that gave birth to this unique BA.5 lineage without 27899T
( @shay671 @AngieHinrichs  and @silcn maybe you are interested in):

Early in April in Portugal has been collected a sample of **BA.2.5** that had all the three Orf1a mutations defining this lineage: 
Putative parental BA.2.5  was EPI_ISL_12127437 collected 1st of April in Portugal with T3358C, Orf1a:A656V and Orf1a:ORF1a:P1018S 
(Check: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=NextCladePangoLineage%3ABA.2.5*++%26+T3358C+%26+Orf1a%3A1018S+%26+Orf1a%3A656V&)

then more than a month later (while Portugal experimented the first northern emisphere BA.5 wave dominated there by BA.5.1) on May 16Th  have been collected EPI_ISL_13018966 and EPI_ISL_13019121 a plain BA.5 sequence
then has been collected EPI_ISL_13018968 on MAY 17Th
after that came the first French sample:EPI_ISL_13033525 collected on May 19Th in the Occitaine region.
and then came a 2nd french sample :EPI_ISL_13176428 sampled in Nouvelle-Aquitaine on 23th May:

Interesting France is the country with the highest number of this sublineage in Europe: 
291 samples!
followed by Germany with 130seqs.

So i ask the designation of this lineage as a recombinant lineage between BA.2.5 and BA.5 
Exactly a BA.2.5/ BA.5/BA.2.5 sandwich recombinant with a double breakpoint:
1BP: between nucleotides 9867 and 12159 
2BP: after T27384C
using: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=NextCladePangoLineage%3ABA.5*++%26+T3358C+%26+Orf1a%3A1018S+%26+Orf1a%3A656V&variantQuery1=NextCladePangoLineage%3ABA.2.5*++%26+T3358C+%26+Orf1a%3A1018S+%26+Orf1a%3A656V&analysisMode=CompareEquals&
(thx to @asinickle for the suggestion) 
Private e mutations for BA.5 proposed here:
T21765-,A21766-,C21767-,A21768-,T21769-,G21770-,T22917G,G12160A,T23018G,G26529A
Private mutations for putative Parental BA.2.5 : 
C9866T,A23040G,C26858T,A27259C,G27382C,A27383T,T27384C,C24553T,C14184T
![Schermata 2022-08-21 alle 15 27 10](https://user-images.githubusercontent.com/87669813/185793136-af4c4c11-eac8-43e3-b690-8c609da0d61e.png)
![Schermata 2022-08-21 alle 15 29 23](https://user-images.githubusercontent.com/87669813/185793258-acbd3306-fbef-4e2a-971e-098de624f9e4.png)
Please @c19850727 @josetteshoenma if you could independently check this analysis of mine i will be grateful to you!


So @corneliusroemer @chrisruis @InfrPopGen @aq-sun @AngieHinrichs ask the designation of this one as a (although very early) recombinant lineage, the largest one involving BA.5 as today.

**Comment by corneliusroemer** [comment]
Why are you sure this is a recombinant? Could a single mutation not just revert as well?

**Comment by FedeGueli** [comment]
> Why are you sure this is a recombinant? Could a single mutation not just revert as well?

Hi @corneliusroemer it shares 3 nuc mutations in a row in ORF1a  with a BA.2.5 sequences sampled in the same country just one month before this lineave has been sampled,
It seems to me very unlikely BA.5 picked up independently 3 mutations in a row between 2232 and 3358  in the same country where one month before was sampled another lineage with the same 3 mutations.

More this one was at the time of the proposam the only 27899C BA.5 lineage circulating pointinv more toward a recombination event than early unsampled ba.5 diversity in South Africa

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAZ with 797 newly designated sequences, and 244 updated from BA.5. Defining mutation C2232T (Orf1a:A656V). (putting faith in parsimony)
