### ISSUE TITLE
Potential BA.1*/BA.2* recombinant with likely breakpoint at NSP13/NSP15 (76 Seqs as of 2022-06-25 mainly Canada-BC)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#798]
### Description
**Recombinant between:** BA.1* & BA.2*
**Earliest sequence:** 2022/03/05 (Canada-BC)
**Most recent sequence:** 2022/06/05 (Canada-BC)
**Countries circulating:** mainly in Canada-BC (67 out of 76), and also found in Hong Kong, India-WB, US-CA, US-WA and Canada-ON.

**Likely breakpoint:** between 18166 and 19953 (NSP13/NSP15). It has a similar breakpoint to XM, and thus is clustered next to XM by Usher, however it doesn't have C2470T (which is displayed as a T2470C reversion in Usher tree).

**Mutations on branch**: C4586T, C9857T, C12085T, and then A23779T (74 out of 76)

**Conserved Nuc mutations** (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/175798278-30b5fdc5-0130-43ea-90b4-6e9081953771.png)
**Cov-spectrum query:** C4586T, C9857T, C12085T, A23779T

### Evidence
**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/175798351-b7196176-1ec1-41be-8697-df3b4fb238aa.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2606_7419d0.json?c=gt-nuc_12085&l=scatter&label=nuc%20mutations:T3241C&scatterY=gt

Genomes:
EPI_ISL_12379774, EPI_ISL_12382877, EPI_ISL_12384025, EPI_ISL_12665185, EPI_ISL_12665698, EPI_ISL_12966120, EPI_ISL_12966278, EPI_ISL_12966539, EPI_ISL_12966626, EPI_ISL_12967086, EPI_ISL_12967094, EPI_ISL_12967337, EPI_ISL_12967347, EPI_ISL_12967448, EPI_ISL_12967532, EPI_ISL_12967665, EPI_ISL_12967671, EPI_ISL_12967862, EPI_ISL_12967863, EPI_ISL_13317192, EPI_ISL_12968283, EPI_ISL_12968296, EPI_ISL_12968413, EPI_ISL_12968437, EPI_ISL_12968446, EPI_ISL_12968462, EPI_ISL_13317010, EPI_ISL_13317179, EPI_ISL_13317299, EPI_ISL_13317430, EPI_ISL_13317464, EPI_ISL_13317612, EPI_ISL_13317676, EPI_ISL_13318296, EPI_ISL_13317001, EPI_ISL_13317662, EPI_ISL_13318380, EPI_ISL_13318454, EPI_ISL_13319140, EPI_ISL_13319298, EPI_ISL_13317109, EPI_ISL_13319864, EPI_ISL_13319915, EPI_ISL_13317126, EPI_ISL_13317128, EPI_ISL_13317144, EPI_ISL_13317152, EPI_ISL_13319735, EPI_ISL_13411244, EPI_ISL_13411299, EPI_ISL_13411401, EPI_ISL_13411639, EPI_ISL_13411665, EPI_ISL_13411924, EPI_ISL_13412055, EPI_ISL_13412074, EPI_ISL_13412126, EPI_ISL_13412289, EPI_ISL_13412296, EPI_ISL_13412308, EPI_ISL_13412315, EPI_ISL_13412407, EPI_ISL_13412416, EPI_ISL_13412420, EPI_ISL_13412748, EPI_ISL_13412793, EPI_ISL_13412890, EPI_ISL_13413301, EPI_ISL_13135375, EPI_ISL_12771791, EPI_ISL_12809275, EPI_ISL_13140323, EPI_ISL_13408864, EPI_ISL_12963892, EPI_ISL_12963762, EPI_ISL_13242862

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAQ with 74 newly designated sequences, and 0 updated designations.
