### ISSUE TITLE
Recent BA.4.1+ C28720T sublineage with S:346T emerged in South Africa and now has been seeded in 4 continents (120 sequences as of 2022-07-24))

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#800]
Edited:
This wasfirst spotted, analyzed and mentioned by @silcn in #741 

Here i want to propose another BA.4 sublineage with a mutation in the spike at residue 346.
These mutations appear to be growing in BA.4 , as before we saw in BA.2 and recently in BA.5,  and @corneliusroemer spotted them very early, i was monitoring them since and they all seems to be growing at comparable level to BA.5, in South Africa

I proposed the first one with S:346S in #777.

The second one, that i propose here, totally unrelated with the #777, 
is a BA.4.1 (S:V3G) sublineage defined by the following mutations:
C28720T 
then
C14322T, T18603C
then
S:346T (G22599C)

Usher Tree:
![Schermata 2022-06-26 alle 18 30 35](https://user-images.githubusercontent.com/87669813/175824270-0be3b114-54a2-4b6b-9f08-e767e774a186.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20211_87faf0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C14322T,T18603C

First sequence: South Africa: EPI_ISL_12765592|2022-04-19
List of sequences:
[contributors (1).csv](https://github.com/cov-lineages/pango-designation/files/8987031/contributors.1.csv)
Nr of sequences: 26
Countries: South Africa England USA Mexico India Austria
Cov-Spectrum oerview: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=N%3A151S%2CS%3A346T&nucMutations=C28720T%2C14322T%2C18603C%2C12160A&aaMutations1=M%3A3N%2CN%3AD377Y&nucMutations1=12160A%2C29666T&

Growth Advantage vs BA.5 in South Africa: 30%
https://cov-spectrum.org/explore/South%20Africa/AllSamples/Past3M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=N%3A151S%2CS%3A346T&nucMutations1=C28720T%2C14322T%2C18603C%2C12160A&analysisMode=CompareToBaseline&

Globally vs BA.5: -13% 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=N%3A151S%2CS%3A346T&nucMutations1=C28720T%2C14322T%2C18603C%2C12160A&analysisMode=CompareToBaseline&
![Schermata 2022-06-26 alle 18 36 22](https://user-images.githubusercontent.com/87669813/175824531-f64670c3-1fe8-4449-89d3-d96cb6be318f.png)

**Comment by silcn** [comment]
This is the lineage I pointed out in a comment on #741. As I mentioned there, S:R346T is accompanied by an 8-nucleotide deletion in ORF7b that causes a frameshift and truncation. The position is ambiguous: Nextclade calls it as 27786-27793del but it could be anywhere from 27785-27792 to 27789-27796. This is the result, starting from ORF7b:10:

<img width="643" alt="frameshift" src="https://user-images.githubusercontent.com/42699509/175828811-a99ffd97-8792-48aa-a4a9-b07f5c71d29f.png">

This frameshift isn't new, it's popped up sporadically across lots of lineages throughout the pandemic, with 170 sequences listed on cov-spectrum.

**Comment by FedeGueli** [comment]
Oh yes i remember that comment! sorry i disnt recognize it was the same, cause i was concentrated on S:346 . 
So i'll mention that issue , thanx for noticing  that @silcn !

**Comment by FedeGueli** [comment]
60 sequences as today

**Comment by FedeGueli** [comment]
78 sequences as today.

**Comment by FedeGueli** [comment]
96 sequences as today.

Now it is possible to ser its growth advantage in Uk vs NCPL BA.5 baseline: -1%
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5*+&aaMutations1=N%3A151S%2CS%3A346T&nucMutations1=C28720T%2C14322T%2C18603C%2C12160A&analysisMode=CompareToBaseline&

**Comment by corneliusroemer** [comment]
This looks like 120 sequences now with the following defining mutations:
`NextCladePangoLineage:BA.4.1* & G22599C & T18603C & C14322T & C28720T`

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.4.1*+%26+G22599C+%26+T18603C+%26+C14322T+%26+C28720T&variantQuery1=S%3A346T+%26++NextcladePangoLineage%3ABA.5*+%26+C14322T&

Given it's ~2% in South Africa and international spread I'd designate this.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.4.1.8 with 71 newly designated sequences, and 5 updated designations from BA.4.1. Defining mutation G22599C (S:R346T), preceded by C14322T, T18603C and then C28720T.
