### ISSUE TITLE
Fast sublineage of BA.5.1 with ORF1b:R1078L, ORF1a:V1117I, ORF1a:S1510C circulating in Europe (131 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#801]
@olias120676 spotted this BA.5.1 sublineage long ago and we are monitoring it since as possible cluster of interest.
 It rapidly grew  and it is now widespread in 17 European countries + Usa and Israel.
I have to say it shows quite impressive growth advantage vs BA.5 baseline and so although it is very small i decided to propose it.

Defining mutations : 
ORF1b:R1078L (G16700T)
then
C18303A
then
ORF1a:V1117I (G3614A) and ORF1a:S1510C ( C4794G)

Usher tree:
![Schermata 2022-06-27 alle 00 39 44](https://user-images.githubusercontent.com/87669813/175836426-f5f32002-1119-415d-a594-f229630f1f84.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_a3a5_8d8510.json?branchLabel=back-mutations&c=gt-ORF1ab_1117,1510,5479&label=nuc%20mutations:C18303A

First sequence : Slovenia EPI_ISL_13253587 2022-05-28
Nr of Sequences: 131
List of sequences
[contributors (2).csv](https://github.com/cov-lineages/pango-designation/files/8987634/contributors.2.csv)
Countries: Denmark 58 sequences, Uk 14 seqs 
![Schermata 2022-06-27 alle 00 40 22](https://user-images.githubusercontent.com/87669813/175836443-d4118126-78f8-4607-bba9-7e525b726593.png)

Covspectrum overview: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AV1117I%2CORF1a%3AS1510C%2CS%3AF486V&nucMutations=12160A&

Growth Advantage vs BA.5 in Denmark: 56%
![Schermata 2022-06-27 alle 00 35 50](https://user-images.githubusercontent.com/87669813/175836315-2ecee15e-c6c9-43fd-befe-6735da23d6cd.png)
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=ORF1b%3AR1078L%2CORF1a%3AV1117I%2CORF1a%3AS1510C&nucMutations1=12160A&analysisMode=CompareToBaseline&

Globally its Growth advantage vs BA.5.1 is also clear and sustained:
![Schermata 2022-06-27 alle 00 42 06](https://user-images.githubusercontent.com/87669813/175836495-72554eff-775e-45e3-a40b-1ab2c179438a.png)
https://cov-spectrum.org/explore/World/AllSamples/Past1M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=ORF1b%3AR1078L%2CORF1a%3AV1117I%2CORF1a%3AS1510C&nucMutations1=12160A&analysisMode=CompareToBaseline&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.1.4 with 92 newly designated sequences, and 24 updated designations from BA.5.1. Defining mutation(s) G3614A (ORF1a:V1117I), C4794G (ORF1a:S1510C).
