### ISSUE TITLE
BE.1 sublineage with N:P364L, ORF1a:D930N, ORF1a:P3504L, A11782G (68 seq., Germany, Israel, England, Denmark)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#803]
Proposal for a sublineage of BE.1
Earliest sequence: 05.05.2022 (Germany)
Countries detected: Denmark, England, Germany, Israel, Italy, Luxembourg, Scotland, Switzerland, USA

C29364T =N:P364L
G3053A = ORF1a:D930N
G3890A = ORF1a:1209K
C10776T = ORF1a:P3504L
A11782G

This variant is defined by N:P364L, ORF1a:D930N, ORF1a:1209K, ORF1a:P3504L, A11782G and was first detected in Germany and multiple other countries.

![grafik](https://user-images.githubusercontent.com/102166254/175884526-d7808fef-671a-45e0-ae0f-4b3a1589e2a6.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4024a_9498f0.json?branchLabel=aa%20mutations&c=gt-nuc_29364,3053&label=nuc%20mutations:G3890A,C29364T

Advantage vs. global BA.5

![grafik](https://user-images.githubusercontent.com/102166254/175884848-7f695ae4-a813-4392-a2ef-6c777a1f3af5.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.5*&aaMutations1=N%3AP364L%2CORF1a%3AD930N%2CORF1a%3A1209K%2CORF1a%3AP3504L&nucMutations1=A11782G&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

EPI_ISL_13072497,   EPI_ISL_13156876, EPI_ISL_13157020, EPI_ISL_13311416,   EPI_ISL_13311765, EPI_ISL_13326075,
EPI_ISL_13362114,   EPI_ISL_13388300, EPI_ISL_13399841, EPI_ISL_13419455,   EPI_ISL_13441962, EPI_ISL_13443534,
EPI_ISL_13443992,   EPI_ISL_13444178, EPI_ISL_13382194, EPI_ISL_12677748, EPI_ISL_13282746,   EPI_ISL_13246996, EPI_ISL_13440513, EPI_ISL_13406302, EPI_ISL_13363209,   EPI_ISL_13363209, EPI_ISL_13246471, EPI_ISL_13235270, EPI_ISL_13246664,   EPI_ISL_13015952, EPI_ISL_13246659, EPI_ISL_13267861, EPI_ISL_13387196,   EPI_ISL_13379101, EPI_ISL_13384510, EPI_ISL_13381203, EPI_ISL_13386342,   EPI_ISL_13240967, EPI_ISL_12827326, EPI_ISL_13241216, EPI_ISL_13013788,   EPI_ISL_13430233, EPI_ISL_13425382, EPI_ISL_13461469, EPI_ISL_13460757,   EPI_ISL_13460632, EPI_ISL_13426799, EPI_ISL_13425402, EPI_ISL_13297500,   EPI_ISL_13301665, EPI_ISL_13324037, EPI_ISL_13323976, EPI_ISL_13323894,   EPI_ISL_13297494, EPI_ISL_13324090, EPI_ISL_13158229, EPI_ISL_13177891,   EPI_ISL_13300047, EPI_ISL_13419362, EPI_ISL_13418921, EPI_ISL_13421327,   EPI_ISL_13443757, EPI_ISL_13067607, EPI_ISL_13346273, EPI_ISL_13247545,   EPI_ISL_13401383, EPI_ISL_13442958, EPI_ISL_13327195

**Comment by corneliusroemer** [comment]
Stayed small and is kind of dying. So let's close unless a child pops up that's interesting.

<img width="2104" alt="image" src="https://user-images.githubusercontent.com/25161793/190932901-233523e8-f253-414f-add6-dd2c165019f2.png">
