### ISSUE TITLE
Proposal to broaden BF.3 (BA.5.2.1.3) to not require S:547

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#805]
I noticed that there's quite a good number of BA.5* with S:1020S

Some of them are currently BF.3, but only if they also have S:547I - which is a small subset.

I think it would make sense to broaden the BF.3 designation to not require S:547I - the S:547I could then be BF.3.1

Here's a covSpectrum query for the proposed broadened BF.3: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=NextcladePangoLineage%3ABA.5*+%26+S%3A1020S+%26+ORF9b%3AD16G+%26+6979G&variantQuery1=NextcladePangoLineage%3ABA.5*++%26+S%3A701V&

It's 1.5k sequences now. This lineage has a share of ~20% in Israel!

The current BF.3 which requires S:547I has only ~50 sequences, most from India.
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=NextcladePangoLineage%3ABA.5*+%26+S%3A1020S+%26+ORF9b%3AD16G+%26+6979G+%26+S%3A547&variantQuery1=NextcladePangoLineage%3ABA.5*++%26+S%3A701V&

**Comment by agamedilab** [comment]
What was the rationale of designating BF.3 at the first place? Cannot find the issue.

**Comment by corneliusroemer** [comment]
I don't think there is an issue, I looked for it but couldn't find it.

Could be that @chrisruis did it as part of a designatathon looking at clusters?

**Comment by agamedilab** [comment]
Designating the parental crown node defined by a spike mutation would be a more clean solution:

![grafik](https://user-images.githubusercontent.com/102166254/175958031-12afbe94-717f-46ee-9653-88f54df69a0b.png)

**Comment by FedeGueli** [comment]
Hi @chrisruis @corneliusroemer @InfrPopGen 
It is a sublineage of the proposed in #721 so my 2 cents view is that it should be linked to that issue and explained there rationale of different designations (Same discourse for BA.5.6 and Ba.5.2.2 and BA.5.2.3). No matter if designated in a designatathon or elsewhere,  authors and readers should be updated also to avoid to spend time in keeping updated something already designated even if partially (as authors should close stale issues to save time to committee) beyond the fact to credit or not authors volunteer work.

**Comment by corneliusroemer** [comment]
@agamedilab You can see the current tree here https://nextstrain.org/staging/nextclade/sars-cov-2/2022-06-26?branchLabel=spike_mutations&label=clade:22B%20%28Omicron%29 to keep track, it's probably easier and more informative than using a list that keeps growing and changing.

**Comment by FedeGueli** [comment]
Thx @corneliusroemer it will be helpful for everyone !

**Comment by agamedilab** [comment]
@corneliusroemer many thanks for sharing! How to access that dataset?

**Comment by agamedilab** [comment]
@corneliusroemer thank you for sharing! Is the link updated or is this "only" the state up to 26.6? In the later case where to access the latest up to date single accession tree? Many thanks!

**Comment by chrisruis** [comment]
Hi @agamedilab This table containing a summary of the designated Omicron lineages should be useful for keeping track: https://www.pango.network/summary-of-designated-omicron-lineages/

**Comment by agamedilab** [comment]
@chrisruis Many thanks for the link! This is very useful.

However how frequently is this updated ? At the moment it apparently does not include BF.3 as well as the other "designatathon" variants 

![grafik](https://user-images.githubusercontent.com/102166254/176390596-0cea0953-82f6-4bb5-b886-b1895d6bfe97.png)

**Comment by agamedilab** [comment]
@chrisruis 
weird, apparently the latest version is not displayed when i click the link....

**Comment by chrisruis** [comment]
Can you see them now?

**Comment by agamedilab** [comment]
many thanks, now it works!

**Comment by corneliusroemer** [comment]
This has now been resolved as BF.23 and BF.24 have been designated - covering almost all of the S:1020S sublineages.
