### ISSUE TITLE
Potential BA.2 sublineage with S:Y248SSEN insertion and N:A35T (~180 Seqs, mainly the US)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#806]
This is a potential sublineage very similar to BA.2.52 (#648 proposed by @silcn).
The 9nt out-of-frame insertions here is nuc:22304insCATCTGAGA (while for BA.2.52 it's nuc:22304insCAGGGGAGA).

### Description
**Sublineage of:** BA.2+N:A35T
**Earliest sequence:** 2022/04/04 (US-IL)
**Most recent sequence:** 2022/06/16 (US-NE)
**Countries circulating:** mainly in the US, and also found in Australia, Israel, UK and Mexico (1 sequence each)
**Mutations on top of BA.2:** S:ins247SSE+S:Y248N, N:A35T

### Evidence
**Growth advantage in recent 3 months in the US over baseline BA.2*:**
![image](https://user-images.githubusercontent.com/86835836/175958041-304e556a-ed79-44b2-bdbe-ba43fee7d73e.png)

### Genomes:
[INS248.csv](https://github.com/cov-lineages/pango-designation/files/8992591/INS248.csv)

**Comment by FedeGueli** [comment]
cc @marcogerdol

**Comment by InfrPopGen** [comment]
Thank you for proposing this. As this lineage has shown little growth advantage over the past month, and appears to be in general decline, I am closing this for the time being. Nevertheless, should this lineage show a marked resurgence in the future, please feel free to reopen or alternatively re-propose.
