### ISSUE TITLE
Fast BA.4.1 sublineage with S:1235F circulating in Israel (256 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#807]
Here i want to propose a Ba.4.1 (S:V3G) sublineage circulating in Israel spotted first by @corneliusroemer 

Defining mutations : S:1235F (G25266T) 

Number of sequences: 256  (251 in Israel)
First sequence: EPI_ISL_13312918|2022-05-22 Israel
EPI_ISLs:
[contributors (4).csv](https://github.com/cov-lineages/pango-designation/files/8993259/contributors.4.csv)

Tree:
![Schermata 2022-06-27 alle 17 25 28](https://user-images.githubusercontent.com/87669813/175976614-27409ca1-cd27-4cc0-b49c-c68de6f596dd.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_aa9c_9c9cd0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G25266T

Growth advantage of this sublineage in Israel vs BA.5 in the last two months: +124%
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=S%3AV3G%2CN%3A151S%2CS%3A1235F%2CS%3A452R%2CS%3AF486V%2CORF7b%3AL11F&nucMutations1=12160A&analysisMode=CompareToBaseline&
![Schermata 2022-06-27 alle 17 27 36](https://user-images.githubusercontent.com/87669813/175977017-d9a6d85b-8fa7-4f12-91d3-cc43b9a91e6d.png)

**Comment by chrisruis** [comment]
Perfect timing @FedeGueli I actually added this one in over the weekend as BA.4.1.4!

**Comment by silcn** [comment]
@FedeGueli I think you've accidentally posted the apparent global growth advantage - in Israel it's only 12% (confidence interval -3-27%)

**Comment by FedeGueli** [comment]
> @FedeGueli I think you've accidentally posted the apparent global growth advantage - in Israel it's only 12% (confidence interval -3-27%)

thx @silcn i have noticed that too but probably then something has gone wrong with my connection and it didnt update to Israel query. 
Thank you for correcting and luckily it was just my fault ;)
