### ISSUE TITLE
Chronic B.1.438.1 recombinant with BA.1.1.16

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#808]
First of all, this appears to likely not be spreading, although without patient data on the GISAID submissions, it can't technically be known.
I'm posting this because I believe these sequences are of great scientific intrigue, and also because I believe that if they do start spreading, it should be immediately designated and investigated. I'd be fine with a "close but reopen if they reappear" approach to this issue. 

There are 4 sequences that I believe make up this series currently, all from Alberta Canada

**1** -[EPI_ISL_7976931](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=s%3A494s%2Corf1a%3A280v%2Cs%3A504s%2Corf1a%3A297v&) -- a highly mutated B.1.438.1 from December 2021. 

**2 & 3** - [EPI_ISL_13454711 | EPI_ISL_13454712](https://cov-spectrum.org/explore/Canada/AllSamples/AllTimes/variants?aaMutations=orf1a%3A280v%2Corf1a%3A297v%2Cs%3A373p&) -- Identical genomes, a week apart, from February and March. They are a recombinant between a heavily mutated B.1.438.1 (up to a breakpoint between 18449 and 18877), and BA.1.1.16 for the rest of the genome. 
The B.1.438.1 section shares 9 mutations with this section of the December sequence, but is missing 3 mutations, and added in 4 different mutations. To me, this implies that they share a common ancestor that split off prior to December. The BA.1.1.16 section is almost entirely unmutated from normal BA.1.1.16, having just 1 additional mutation. 

**4** - [EPI_ISL_13215742](https://cov-spectrum.org/explore/Canada/AllSamples/AllTimes/variants?aaMutations=orf1a%3A280v%2Cs%3A504s%2Corf1a%3A297v%2Cs%3A494p&) -- Sequence from late April. This one is a more complex recombinant with 5 breakpoints, of the pattern [B.1.438.1 | BA.1.1.16 | B.1.438.1 | BA.1.1.16] | B.1.438.1 | BA.1.1.16]. 
The 5 breakpoints are [between 10029 and 10449], [15240 and 18163], [23072 and 23525], [between 23854 and 23908], [25551 and 25584].
Interestingly, this means that the spike is almost entirely B.1.438.1. The only section it took from BA.1.1.16 is S:655-S:764. 

The first B.1.438.1 section is missing 5 mutations from the December sequence, 3 of which were also missing in the Feb/March sequences. It added in 6 mutations, 1 of which was also added in the Feb/March sequences. It shares 4 mutations with the December sequence. 

The first BA.1.1.16 section has nothing added or missing from standard BA.1.1.16. 5 mutations are shared.

The second B.1.438.1 section is missing 1 mutation from the December sequence, and added in 3. It shares 14 with the December sequence. It hardly has any overlap with the Feb/March sequences, but the 1 expected mutation is present. 

The second BA.1.1.16 section has all 4 expected mutations, no additions or subtractions. 

The third B.1.438.1 section has the one expected mutation from the December sequence, and no additions or subtractions. 

The third BA.1.1.16 section has all 14 expected mutations, no subtractions, but 1 addition -- a different addition than the Feb/March sequences.

**Comment by FedeGueli** [comment]
@silcn yes @shay671 and @olias120676 spotted them a while ago, if i m not wrong the NZL one has N from BA.2 + N:155V
while the ones from Uk have the highy mutated B.1.1.528 .
I searched then for N:155V BA.2 sublineages and found that some have been sampled in South Africa,Mauritius and Botswana 
https://cov-spectrum.org/explore/Africa/AllSamples/Past6M/variants?aaMutations=N%3A155V&pangoLineage=BA.2*&variantQuery1=G22599C+%26+T22304A&

**Comment by Sinickle** [comment]
I'll close this since nothing has happened with it!
