### ISSUE TITLE
B.1.553 representatives: ambiguous bases / AD.2; withdraw?

### ISSUE THREAD

**Issue by AngieHinrichs** [cov-lineages/pango-designation#81]
Short version: I think B.1.553 was a mirage caused by an unlucky combination of N's and ambiguous base calls and should be withdrawn as a lineage.  Long version:

Of the 15 representative samples for B.1.553, 6 are not in GISAID, so not in pangoLEARN/data/lineages.metadata.csv:
England/PHEC-14E014/2020
Wales/PHWC-49055D/2020
England/PHEC-14C571/2020
England/PHEC-14C68D/2020
England/QEUH-A9D46C/2020
Scotland/QEUH-9D2AF1/2020

Of the 9 B.1.553 sequences in pangoLEARN, 4 have very few unambiguous differences from the reference (only the B.1 mutations C241T,C3037T,C14408T,A24303G), many ambiguous bases (24-33), and are assigned to B.1 by the latest version of pangolin (2.4.2, pangoLEARN 2021-05-12):
England/QEUH-9D01B2/2020
England/ALDP-A85485/2020
England/QEUH-AD2568/2020
England/LIVE-DC2C45/2020

Wales/PHWC-4956A0/2020 has 25 ambiguous bases and only B.1 + G14202T, G19542T, and C23613T as unambiguous mutations.  The remaining 4 sequences in pangoLEARN have 10 (post-B.1) unambiguous mutations in common with each other:
QEUH-BA0FBF
QEUH-BA12D3
QEUH-BCBC02
QEUH-BA2B40
B.1 + A1163T, T3256C, C5622T, G14202T, G19542T, C19718T, C22388T, C26060T, G29227T, A29771G

Those mutations are shared by AD.2 which also has the B.1.1 {G28881A, G28882A, G28883C}:

B.1 + A1163T, T3256C, C5622T, G14202T, G19542T, C19718T, C22388T, C26060T, G28881A, G28882A, G28883C, G29227T, C29466T, A29771G

When I place the 9 pangoLEARN sequences on UCSC's global tree with [UShER](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace), all are placed in B.1.1 (Nextstrain clade 20C):

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/B.1.553.global.json?label=nuc%20mutations:C3037T

The 5 sequences with more unambiguous mutations are placed on a branch with a total of 18 mutations relative to the Wuhan/Hu-1 NC_045512.2 reference:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/B.1.553.global.json?label=nuc%20mutations:A1163T,T3256C,C5622T,G14202T,G19542T,C19718T,C22388T,C26060T,G29227T,C29466T,A29771G

That branch has so many descendants that they don't all necessarily land in the same subset of 1000 sequences.  And their neighboring sequences tend to be classified by the latest version of pangolin as AD.2:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/B.1.553.subtree1.json?c=pango_lineage

So I suspect that what happened was that by some stroke of bad luck (Ns or ambiguous bases at 28881-28883), the 15 representatives classified as B.1.553 ended up in a separate pangothon subtree (B.1.treesubtree_4_DM.samples) from the rest of the AD.2 sequences (B.1.1.treesubtree_6_CR.samples), causing the appearance of a B.1 lineage -- when in the context of a global tree, the 10 (post-B.1) unambiguous mutations in 5 out of the 9 provide pretty compelling evidence that those 5 are actually AD.2, and the other 4 have too many ambiguous bases to be sure what they are.

And just to be sure, I aligned the 9 sequences to the NC_045512.2 reference and extracted the bases corresponding to 28881-28883 and they are ambiguous or Ns:
```
>England/QEUH-9D01B2/2020:28881-28883
rrs
>England/ALDP-A85485/2020:28881-28883
rrs
>England/QEUH-AD2568/2020:28881-28883
rrs
>England/QEUH-BA12D3/2020:28881-28883
nnn
>England/QEUH-BA2B40/2020:28881-28883
nnn
>England/LIVE-DC2C45/2020:28881-28883
rrs
>England/QEUH-BCBC02/2020:28881-28883
nnn
>England/QEUH-BA0FBF/2020:28881-28883
nnn
>Wales/PHWC-4956A0/2020:28881-28883
rrs
```

**Comment by aineniamh** [comment]
Thanks @AngieHinrichs, withdrawn now as of release [v1.2.4](https://github.com/cov-lineages/pango-designation/releases/tag/1.2.4).
