### ISSUE TITLE
ENH: Add unaliased lineage name to Omicron mutation table

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#810]
This table is very useful, but it's tricky right now to figure out what BG.3 refers to.

It would be great to have the unaliased lineage name added as another column. This should also enable us to sort properly. Right now, sorting will put BG.3 away from BA.2.

https://www.pango.network/summary-of-designated-omicron-lineages/

<img width="2027" alt="image" src="https://user-images.githubusercontent.com/25161793/176404286-7be05bd1-ea2c-43ca-aea7-a91b2665bd33.png">

While we're at it, we may also add that BA.4/5 lineages are part of this, too - right now the text says BA.1/2 only

**Comment by chrisruis** [comment]
This table incorporating unaliased lineage names is now at https://docs.google.com/spreadsheets/d/1aQ_1cukAVFrHgDs1rhC0vlaWaGVQcrKUyD8R8lrj_HM/edit?usp=sharing
