### ISSUE TITLE
ENH: Mirror defining mutation table to Google Sheets to make it easier to browse

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#811]
It's great we have this table of lineage defining mutations. But right now it's not searchable and the view is quite limited.

It would be great if we could mirror/export it somehow to Google Sheets to make it filter/sort/searchable.

I'm talking about this:
<img width="2027" alt="image" src="https://user-images.githubusercontent.com/25161793/176404730-e2176c6d-647c-4004-a6a1-0abfc7d2a350.png">

https://www.pango.network/summary-of-designated-omicron-lineages/

**Comment by corneliusroemer** [comment]
@chrisruis given the number of likes this issue has received, can you share where you maintain this list? It would be really nice if this could be committed to the repo in a structured form. Even if not complete, it would still help make sense of the designations. If committed, it could also be pulled in by Google Sheets etc.

**Comment by chrisruis** [comment]
I've now added all of this info for currently designated Omicron sublineages to a google sheet here: https://docs.google.com/spreadsheets/d/1aQ_1cukAVFrHgDs1rhC0vlaWaGVQcrKUyD8R8lrj_HM/edit?usp=sharing

Also included the full unaliased lineage names and GitHub issues for lineages initially proposed on here. Let me know if you have any issues accessing it

**Comment by corneliusroemer** [comment]
Excellent, thanks so much @chrisruis 

I'm sure a lot of people appreciate this (can already see many visitors on the sheet ;) )
