### ISSUE TITLE
Nextclade and Pangolin do not recognize all pango-designations of v1.10

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#813]
Sorry, quick question:
I have noticed that pangolin and Nextcalde do not recognize all the lineages added to the recent pango-designations of v1.10.

In particluar i noticed could not identify sequences that should belong to BA.5.5 and BA.4.1.1. However other variants listed in v.10 (e.g BE.1, BF.1, etc.) are recognized.

Is this a bug or am I missing something?

Many thanks in advance for any clue or opinion!

**Comment by corneliusroemer** [comment]
Designation happens first, assignments are a question of algorithm/data updates.

GISAID currently seems to be using a pangoLEARN version that was based off v1.9, so not having 1.10 lineages is expected.

Nextclade uses the latest designations at time of build so doesn't align necessarily with designation releases. So it's normal that newly designated lineages are not assigned.
