### ISSUE TITLE
BA.2 sublineage with S:I68T prevalent in East Africa (287 seq, >50% in Uganda)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#819]
Proposal for a sublineage of BA.2
Earliest sequence: 2022-02-23 (Canada)
Countries detected: USA (79+), Australia (73+), Uganda (38), Kenya (34), and smaller numbers in almost 20 more countries

Defining mutations:
S:I68T, ORF1a:D3936N, nuc:T19452C

Recent uploads show that this appears to have been dominant in Uganda in the last couple of months (BA.4/5 have likely overtaken it now), and it also reached a prevalence of >25% in Kenya before being pushed out by BA.4/5. 

My suspicion is that this lineage actually originated not in Uganda or Kenya but in one of the various East African countries that has submitted very few or no sequences in 2022: there is a sequence from Japan ex-South Sudan, sample date 2022-03-30, which predates the first detections in Kenya and Uganda by over a month (though this coincides with a two-month gap in Ugandan sequencing, so it may well have been present there at the time). The most recent sequence on GISAID from South Sudan is from December 2021. Additionally, the lineage had already been imported to Canada by late February and 9 countries by the end of March, despite seemingly not being present at any significant level in Uganda in February.

Nextclade and pangoLEARN often call this as BA.2.31, which is defined by BA.2+ORF1a:D3936N without any further mutations. Usher thinks the order is S:I68T then ORF1a:D3936N then nuc:T19452C and so does not place this lineage among BA.2.31. I think there's genuine ambiguity here: I can't find any African sequences with S:I68T alone or ORF1a:D3936N alone that could reasonably be ancestral to this lineage, so it's not clear which came first. This is my best guess:
- This lineage is independent from BA.2.31.
- The sequences with S:I68T+ORF1a:D3936N but not nuc:T19452C, which Usher thinks are ancestral to this lineage, are actually mostly BA.2.31 sequences that have picked up S:I68T.

Someone else can take a closer look (@AngieHinrichs?)

Lineage is in blue below.
<img width="734" alt="Africa_I68T_lineage" src="https://user-images.githubusercontent.com/42699509/177072774-d756860c-7f10-4276-84fa-e473cdb66847.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_17fb7_23ca80.json?c=gt-nuc_12071,19452](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_17fb7_23ca80.json?c=gt-nuc_12071,19452)

Cov-spectrum: [https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A68T&nucMutations=T19452C%2CG12071A&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A68T&nucMutations=T19452C%2CG12071A&)

**Comment by silcn** [comment]
Now 365 sequences according to Usher, including 70 from Uganda, where BA.4 and BA.5 appear to have started pushing it out during June. Also 6 sequences from the DRC suggesting it may have reached ~25% prevalence there.

**Comment by silcn** [comment]
Usher is now placing this lineage as a sublineage of BA.2.36, with the order C22792T -> S:I68T (BA.2.36) -> T22792C -> ORF1a:D3936N -> T19452C. This seems rather bizarre; in fact Usher seems to think C22792T -> S:I68T (BA.2.36) -> T22792C is a substantially sized branch. I would expect most of the sequences currently placed there actually belong in different lineages with S:I68T that are not on the C22792T branch.

In any case, there are now 391 sequences on the Usher tree. Although this lineage is on the way out, I still think it should be designated as it was dominant in at least one country and likely prevalent in extremely undersampled parts of East Africa. If this had appeared in Europe or the USA instead, it would doubtless have been designated long ago.

**Comment by FedeGueli** [comment]
I saw a BA.2.36 sequence uploaded today from.Europe. let me check if it is this lineage.

yes @silcn Usher placed a couple  of designated sublineages as sublineage of BA.2.36 too.
See the @AngieHinrichs explanation in the issue that designnated BA.2.36.1 (so called) .

**Comment by silcn** [comment]
@FedeGueli ah yeah, I'd forgotten about that.

@chrisruis @InfrPopGen it seems pretty clear to me that the lineage designated BA.2.36.1 is not actually a sublineage of BA.2.36. There's absolutely no reason to believe C22792T immediately reverted like that. Would it be possible to redesignate it as BA.2.X, and give this lineage its own (non-BA.2.36) designation too?

**Comment by corneliusroemer** [comment]
Trying to follow your discussion but wondering how this issue is related to your points about so called BA.2.36.1?

A lineage with lots of sequences from East Africa definitely deserves designation. Is it clear which sequences should be chosen?

**Comment by silcn** [comment]
BA.2.36.1, like the lineage in this issue, is a BA.2 sublineage with S:I68T that has (most likely incorrectly) been placed within BA.2.36 by Usher.

The lineage in this issue is pretty clear-cut: it should be everything with S:I68T, ORF1a:D3936N, nuc:T19452C.

**Comment by AngieHinrichs** [comment]
Yep, I think the C22792T -> S:I68T (BA.2.36) -> T22792C is an error and frustratingly, my usual fix for these things (trim a few oddball sequences and reoptimize to get a better placement) doesn't apply to this (there aren't just a few oddball sequences causing the placement).  I'll have to spend some more time on it -- in the meantime, I agree that BA.2.36.1 and this proposed lineage should be sublineages of BA.2 not BA.2.36.

**Comment by silcn** [comment]
Obviously this isn't going anywhere, but once again I'd like to ask why it hasn't been designated? Everything that I said in my post on 10 August still applies: this would certainly have received a designation months ago if it had appeared in a more well-sampled area. There's still a chance that sublineages could appear in the future.

**Comment by corneliusroemer** [comment]
I didn't know how to designate back when you proposed - I've just designated it.
Thanks for bringing this to my attention again @silcn 

If you spot similar issues that clearly deserve designation do bring it up again like you did here. I often sort by most recent comment to filter for things where something has recently happened.

**Comment by silcn** [comment]
@corneliusroemer thank you for designating!

**Comment by corneliusroemer** [comment]
Actually - I just realized this is potentially a sublineage of BA.2.31, noticed this when it was placed as a child of this by my tree builder.

I'll redesignate as BA.2.31.1 as I feel like this is more likely than homoplasy of the BA.2.31 defining mutation.
