### ISSUE TITLE
B.1.608 representatives have A24389C and G24390C, associated with untrimmed nanopore adapter seq

### ISSUE THREAD

**Issue by AngieHinrichs** [cov-lineages/pango-designation#82]
Short version: I think B.1.608 is not a real lineage but rather the consequence of untrimmed nanopore adapter sequences.  Long version:

The representative sequences for lineage B.1.608 are all from the same lab (Houston Methodist Hospital, Texas, USA) and the mutations that they have in common are B.1 + G25563T, C1059T, A24389C and G24390C.  However, A24389C and G24390C have been flagged as untrimmed nanopore adapter artefacts (https://virological.org/t/issues-with-sars-cov-2-sequencing-data/473/8), and the sequences list Oxford Nanopore as the sequencing technology in GISAID.  

When running UShER at UCSC to build up the global tree and place uploaded sequence on it, we first mask out those sites as well as others identified as [problematic](https://virological.org/t/issues-with-sars-cov-2-sequencing-data/473/14).  Without A24389C and G24390C, the representative sequences of B.1.608 no longer look quite so similar. 

Here is a view of the B.1.608 example sequences (red circles) placed on a downsampled version of the global tree (1000 sequences are selected at random, then the global tree is pruned to include only the branches connecting those), showing that when A24389C and G24390C are masked, the sequences cluster into different branches of B.1 + G25563T, C1059T (Nextstrain clade 20C):

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/B.1.608.global.json?label=nuc%20mutations:C1059T

With a subtree size of 1000 sequences in our global tree of 1.5M+ sequences, the 47 representative sequences cluster into 19 different subtrees, 10 of which contain only one representative sequence and 5 of which contain only two.  [Note: if our algorithm tried harder it could find fewer than 19 subtrees of 1000 that encompass the 47 sequences, but that's a sign that there are a lot of neighbors between them in our tree.]  

12 representative sequences cluster neatly into the top (lighter blue, B.1) branch of this subtree, where pangolin assigns B.1 to most non-representative sequences (B.1 + G25563T, C1059T, T15276A, G28842T):

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/B.1.608.subtree1.json?c=pango_lineage

9 other representative sequences cluster into a branch in which most sequences are assigned to B.1.2 (B.1 + G25563T, C1059T, C10319T, A18424G, C21304T, G25907T, C27964T, C28472T, C28869T):

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/B.1.608.subtree2.json?c=pango_lineage&label=nuc%20mutations:T25907G

There are other representatives that land elsewhere in B.1.2, or in other lineages like B.1.595 or B.1.588, when A24389C and G24390C are masked.

Would you all be open to possibly masking A24389C and G24390C when building your tree, and letting other mutations determine where sequences end up in the tree?

**Comment by aineniamh** [comment]
Thanks @AngieHinrichs, withdrawn now as of release [v1.2.4](https://github.com/cov-lineages/pango-designation/releases/tag/1.2.4).
