### ISSUE TITLE
Sublineage/recombinant of a (2nd generation?) BA.5.2.1 plus N:P151S and S:N185Y with BA.4/BA.2 in Denmark

### ISSUE THREAD

**Issue by JosetteSchoenma** [cov-lineages/pango-designation#820]
**Discription:**

BA.5.2.1 plus T15096C like Delta, T6979G like BF.1, C28724T/N:P151S like BA.4, G27382C+A27383T+C227384T/ORF6:D61L like BA.2/BA.4, plus 11 private mutations C884T, G1999T, C5051T, G9220A, G11053C, C16859T, C19545A, A22115/Spike:N185Y, T23458G, G25699T and C28651. 25 samples from Denmark. 
There are also 5 good quality samples from England/Scotland/Germany that have all those mutation except the C884T and the BA.2/BA.4 cluster ORF6:D6L
**Earliest sequence:** 11th of June 2022 for the Danish cluster, 1st of June for the "inbetween" cluster (one with less quality from the 2nd of May)
**Countries circulating:** Just Denmark for the fast growing main cluster
**Cov-spectrum query:** https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=S%3AL452R%2CS%3AF486V%2CN%3AP151S%2CS%3AH69-%2CS%3AV70-&nucMutations=C1627T%2CT27384C%2Cc28651t%2CG27382c%2CG1999T%2CC5051T%2CG11053C%2CC16859T%2CA22115T&variantQuery1=N%3AP151S%26C1931A%26N%3AE136D%26NextcladePangolineage%3A+BA.5*&
**Genomes:**
Main cluster:
EPI_ISL_13341838
EPI_ISL_13342028
EPI_ISL_13400411
EPI_ISL_13401270
EPI_ISL_13401614
EPI_ISL_13442899
EPI_ISL_13465845
EPI_ISL_13466051
EPI_ISL_13466078
EPI_ISL_13466157
EPI_ISL_13500984
EPI_ISL_13500987
EPI_ISL_13518632
EPI_ISL_13518661
EPI_ISL_13519584
EPI_ISL_13519598
EPI_ISL_13519743
EPI_ISL_13534521
EPI_ISL_13534627
EPI_ISL_13534968
EPI_ISL_13535045
EPI_ISL_13535078
EPI_ISL_13573500
EPI_ISL_13573511
EPI_ISL_13573903

Inbetween cluster:
_EPI_ISL_12724241_
EPI_ISL_13156973
EPI_ISL_13338333
EPI_ISL_13441649
EPI_ISL_13441785
_EPI_ISL_13519054_
EPI_ISL_13573511
cursed are less quality. Not included in analysis.
**Evidence:**
Sc2rf ouput:
![image](https://user-images.githubusercontent.com/94831035/177137325-651382dc-0fc4-4bdc-9151-c92100aa5bcf.png)
**Nextclade:**
Main cluster:
![image](https://user-images.githubusercontent.com/94831035/177137567-b675be45-f13a-4fc2-a2a2-15f0c71ab385.png)
Note that the reversion A26529G is not actually a reversion of M:D3N, but a M:D3B or G26529R, which is very common in Danish BA.5's. I am still not sure why, but it is also the reason why M:D3N cannot be used in Danish CovSpectrum Queries. GISAID allows M_D3 though.
Inbetween cluster:
![image](https://user-images.githubusercontent.com/94831035/177137883-1b210eac-5e64-413d-9443-cb72647af563.png)
Overview table:
![image](https://user-images.githubusercontent.com/94831035/177138724-ed16f611-586a-4b24-8ed7-cb5c8c374e0e.png)
**Usher Tree:**
![image](https://user-images.githubusercontent.com/94831035/177139201-d36ce0ca-5b17-446d-ba61-3bf90a424a69.png)
![image](https://user-images.githubusercontent.com/94831035/177139484-5b8e16b0-c63f-4500-9066-f7995bfe8adc.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3dc4f_2b4e50.json?branchLabel=nuc%20mutations&label=nuc%20mutations:T23458G,G25699T,C28724T

**Comment by JosetteSchoenma** [comment]
I forgot to show that it seems to be growing fast in Denmark, but early days, of course.
![image](https://user-images.githubusercontent.com/94831035/177140642-b6bf5a05-7ce9-4f8e-94bd-4e39aa96d0d1.png)
And because I just noticed that Usher does include a less quality sequence from England on the left side of the tree, I will put the Sc2rf, from before I cut it from my list, here. I think Usher could be right placing it there. It is the line that starts with 8 N's.
![image](https://user-images.githubusercontent.com/94831035/177141287-44278f63-179e-4903-9184-9be2f66f8d4e.png)

**Comment by JosetteSchoenma** [comment]
NextcladePangolineage: BA.5 seems to work nicely though. I put it in your query Fede. Thank you
https://cov-spectrum.org/explore/Denmark/AllSamples/Past3M/variants?variantQuery=NextcladePangolineage%3A+BA.5*&aaMutations1=S%3AL452R%2CS%3AF486V%2CN%3AP151S%2CS%3A185Y&nucMutations1=C1627T%2CT6979G%2CA28330G%2CG1999T&analysisMode=CompareToBaseline&

**Comment by silcn** [comment]
As for the question of whether this is a recombinant: probably impossible to know for sure, but for some reason the triple mutation causing ORF6:D61L seems to be quite common. For example, Alpha with ORF6:D61L reached over 1% prevalence in Germany and Denmark, and it also occasionally appeared in numerous Delta lineages. So it's entirely possible that this lineage picked it up independently.

**Comment by JosetteSchoenma** [comment]
It has grown from 25 to 33 samples, of which one in the USA now, from the 27th of June.
Growth advantage still with not enough samples and too big a CI, but compared to BA.5* (137%, CI 32-243%) it is not very different from compared to BA.5.2.1* (117%, CI 23-211) in Denmark.

**Comment by JosetteSchoenma** [comment]
The one from the USA is EPI_ISL_13697384.
And another one from Norway was uploaded today, that belongs to the "in-between cluster". EPI_ISL_13683268

**Comment by FedeGueli** [comment]
It reached 39 as today with  covspectrum query : 
C1627T, T6979G, A28330G, G1999T + S:L452R, S:F486V, N:P151S, S:N185Y
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AL452R%2CS%3AF486V%2CN%3AP151S%2CS%3A185Y&nucMutations=C1627T%2CT6979G%2CA28330G%2CG1999T&aaMutations1=S%3AL452R%2CS%3AF486V%2CM%3AD3n%2CN%3AD377Y&nucMutations1=T27438C&
cc @chrisruis @InfrPopGen 
In our list is the fastest BA.5 vs BA.5 baseline ( taking it with big caveats but unusual to see such advantages for other BA.5 clusters) :
<google-sheets-html-origin><style type="text/css"></style>

BA.5.2.1+ Orf3a:103S+N:151S+S:185Y+orf1a:P1596S | https://cov-spectrum.org/explore/Denmark/AllSamples/Past2M/variants?nucMutations=12160A%2C27889T&aaMutations1=S%3AL452R%2CS%3AF486V%2CN%3AP151S%2CS%3A185Y&nucMutations1=C1627T%2CT6979G%2CA28330G%2CG1999T&analysisMode=CompareToBaseline& | 138% | https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AL452R%2CS%3AF486V%2CN%3AP151S%2CS%3A185Y&nucMutations=C1627T%2CT6979G%2CA28330G%2CG1999T&aaMutations1=S%3AL452R%2CS%3AF486V%2CM%3AD3n%2CN%3AD377Y&nucMutations1=T27438C& | 39
-- | -- | -- | -- | --

**Comment by JosetteSchoenma** [comment]
@FedeGueli I just realized that your query, also the growth advantage one, includes the in-between cluster. That's 49 now. My query is only on the big Danish cluster, with one extra from the USA now, which has grown to 41.

**Comment by JosetteSchoenma** [comment]
I made a growth advantage query for just the main cluster. 
https://cov-spectrum.org/explore/Denmark/AllSamples/Past2M/variants?variantQuery=NextcladePangolineage%3A+BA.5*&aaMutations1=S%3AL452R%2CS%3AF486V%2CN%3AP151S%2CS%3AH69-%2CS%3AV70-%2CS%3AN185Y&nucMutations1=C1627T%2CT27384C%2CC28651T%2CG27382C%2CG1999T%2CC5051T%2CG11053C%2CC16859T&analysisMode=CompareToBaseline&
82% CI 25-193%, still too little samples
![image](https://user-images.githubusercontent.com/94831035/178094949-65cea0d3-c361-4cab-94fa-97c602b0a33c.png)

**Comment by FedeGueli** [comment]
Thx Josette! So the difference between the main and intermediate cluster are .Orf6:61 mutated and  8844T missing right? 

(@JosetteSchoenma i think there are a couple of typo in the main text when you refer to 8844T or but it is listed as 844T and then when  you say"A26529G is not actually a reversion of M:D3N, but a M:D3B or G2659R, ")

**Comment by JosetteSchoenma** [comment]
Yes, those are the changes. The red letters in the second last row in the table. I will look at the typos. Thanks. ![Screenshot_20220709-100451_Chrome.jpg](https://user-images.githubusercontent.com/94831035/178097428-894a0ed1-81d7-4505-aa39-238765ec75d4.jpg)

**Comment by FedeGueli** [comment]
Thank you very much @JosetteSchoenma :
So i  884C or T is enough to distinguish between the two:

C1627T, T6979G, A28330G, G1999T + S:L452R, S:F486V, N:P151S, S:N185Y for the intermediate

C1627T, T6979G, A28330G, G1999T + S:L452R, S:F486V, N:P151S, S:N185Y+884T for the main.

Thanks a lot, great work

**Comment by corneliusroemer** [comment]
I'll close this as stale - let me know if it reawakens or you think it should be designated
