### ISSUE TITLE
BA.5.2.1 sublineage with S:G181A (218 seq. mostly UK as of 10.0.22)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#821]
Proposal for a sublineage of BA.5.2.1
Earliest sequence: 24.05.2022 (UK)
Countries detected: mostly UK, Australia, Belgium, Canada, Denmark, France, Germany, Ireland, Israel, Italy 

Defining mutation:
S:G181A

This variant is defined by S:G181A and was first detected in UK and multiple other countries (144 seq. on Usher).

![grafik](https://user-images.githubusercontent.com/102166254/177169421-6349a011-d971-4f0d-8c76-96ad9cb0e101.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a7d9_2ee420.json?branchLabel=aa%20mutations&c=gt-S_181&label=nuc%20mutations:C241T,T670G,C1627T,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,A27038G,C27807T,C27889T,A28271T,C28311T,A28330G,G28881A,G28882A,G28883C,A29510C

Growth advantage vs. BA.5.2.1 in Europe:

![grafik](https://user-images.githubusercontent.com/102166254/177169680-67c8e0a1-6bd0-4b61-855a-b9893e4a4f30.png)

https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?nucMutations=A27038G&pangoLineage=BA.5*&aaMutations1=S%3AG181A&nucMutations1=A27038G&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

EPI_ISL_13345096, EPI_ISL_13461437, EPI_ISL_13461623, EPI_ISL_13477894, EPI_ISL_13478016, EPI_ISL_13480847, EPI_ISL_13499580, EPI_ISL_13500560, EPI_ISL_13501080, EPI_ISL_13504434, EPI_ISL_13534298, EPI_ISL_13534337, EPI_ISL_13534390, EPI_ISL_13534484, EPI_ISL_13539658, EPI_ISL_13559239, EPI_ISL_13570730, EPI_ISL_13574804, EPI_ISL_13580839, EPI_ISL_13580880, EPI_ISL_13590804, EPI_ISL_13616056
[fetch.xlsx](https://github.com/cov-lineages/pango-designation/files/9039996/fetch.xlsx)

**Comment by ryhisner** [comment]
Nice spot, @agamedilab. @FedeGueli and I were just discussing the apparent increased frequency of S:181 & S:183 mutations yesterday. Didn't realize that a BA.5 lineage with it had grown so quickly. NTD mutations seem to be the theme of late. Better that they mutate in S1 than S2 as far as I'm concerned, as S2 seems to be the spike region that causes increased severity and altered cell entry, as shown in @thomaspeacock's work. So far the S2 mutations responsible for Omicron's attenuated virulence seem remarkably stable.

**Comment by FedeGueli** [comment]
@ryhisner also 185 spotted by @Josetteschoenma in a couple of sublineages

**Comment by agamedilab** [comment]
218 seq on usher as of 10.07.22.

![grafik](https://user-images.githubusercontent.com/102166254/178136947-ec4238cb-3700-41ef-88d8-2e50b4b1ccf3.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_365ee_a87280.json?branchLabel=aa%20mutations&c=gt-S_181&label=nuc%20mutations:C241T,T670G,C1627T,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,A27038G,C27807T,C27889T,A28271T,C28311T,A28330G,G28881A,G28882A,G28883C,A29510C
