### ISSUE TITLE
Potential BA.4.1 sublineage with additional spike N658D (55 seqs, predominantly Indonesia)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#822]
I am to propose this potential sublineage as there is some interesting convergent evolution taking place.

BA.4.1 is the biggest BA.4 branch featuring an additional S:V3G, while the 2nd biggest branch (proposed by @corneliusroemer in #549) has an S:N658S on top of vanilla BA.4.

Recently there is a cluster of BA.4.1 in Indonesia convergently gained a spike N658 change.

### Description
**Sublineage of**: BA.4.1
**Earliest sequence**: 2022/06/02 (Indonesia)
**Most recent sequence**: 2022/06/28 (UK-England)
**Mutations on top of BA.4.1**: T6971C, A16076G (ORF1b:D870G), C17439T, A18941G (ORF1b:D1825G), A23534G (S:N658D), C29421T (N:P383L)
**Countries circulating**: 

<html>
<body>

Location | Number of sequences
-- | --
Indonesia | 34
Australia | 14
Denmark | 3 
United States | 1
United Kingdom | 1 
Singapore | 1 
Singapore ex-Indonesia | 1 

<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Evidence</h3>
</body>
</html>

**Usher tree:**
![image](https://user-images.githubusercontent.com/86835836/177448351-d9cdebb5-4526-4e67-b661-64cb726fdcad.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_19100_4bf240.json?branchLabel=Spike%20mutations&c=gt-nuc_23534&label=nuc%20mutations:T6971C,A16076G,C29421T

### Genomes:
EPI_ISL_13360581, EPI_ISL_13375808, EPI_ISL_13421094, EPI_ISL_13424143, EPI_ISL_13439870, EPI_ISL_13466186, EPI_ISL_13466529, EPI_ISL_13469782, EPI_ISL_13496639, EPI_ISL_13496680, EPI_ISL_13496789, EPI_ISL_13500301, EPI_ISL_13501534, EPI_ISL_13501556, EPI_ISL_13501754, EPI_ISL_13501800-13501801, EPI_ISL_13513556, EPI_ISL_13521467, EPI_ISL_13535186, EPI_ISL_13539653, EPI_ISL_13575670, EPI_ISL_13575706, EPI_ISL_13575922, EPI_ISL_13575929, EPI_ISL_13575967, EPI_ISL_13575993, EPI_ISL_13612879, EPI_ISL_13612910, EPI_ISL_13612915-13612916, EPI_ISL_13613020-13613022, EPI_ISL_13613339, EPI_ISL_13613350, EPI_ISL_13613359, EPI_ISL_13613361, EPI_ISL_13613372-13613373, EPI_ISL_13613376, EPI_ISL_13613397-13613398, EPI_ISL_13613401, EPI_ISL_13613874, EPI_ISL_13626510-13626511, EPI_ISL_13636474, EPI_ISL_13636483, EPI_ISL_13636518, EPI_ISL_13636546, EPI_ISL_13636582, EPI_ISL_13636669, EPI_ISL_13636778, EPI_ISL_13637546

**Comment by InfrPopGen** [comment]
Thanks @c19850727 for proposing this. This lineage appears to be in relative decline. Consequently, closing this at least for now.
