### ISSUE TITLE
Potential BA.2.3 sublineage with additional spike K417T (41 seqs, ~30% prevalence in Brunei)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#824]
Introduction of BA.2.3 into Brunei back in January 2022 is featured by obtaining of nuc mutation C21859T and further T24115C.
The following graph is the prevalence of BA.2.3+C21859T+T24115C in Brunei, which was ~80% in March and ~50% at present:
![image](https://user-images.githubusercontent.com/86835836/177768772-b380789e-bd92-458c-85ef-290e4479a8d6.png)

The sublineage I am to propose is the biggest branch of above BA.2.3 branch in Brunei that has amino changes (S:K417T and ORF1a:C2239G).

### Description
**Sublineage of**: BA.2.3
**Earliest sequence**: 2022/04/11 (Brunei)
**Most recent sequence**: 2022/06/17 (Brunei)
**Mutations on top of BA.2.3**: T6980G (ORF1a:C2239G), C21859T, A22812C (S:K417T), T24115C
**Countries circulating**: Brunei only

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/177770392-74b15262-7ebb-4a1a-8665-bb86effe7e44.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8e97_251eb0.json?branchLabel=nuc%20mutations&c=gt-S_417&label=nuc%20mutations:A22812C

**Prevalence as per cov-spectrum**:
![image](https://user-images.githubusercontent.com/86835836/177770611-a0dec5ee-2f2e-442a-988b-66fea65aafc5.png)

**Relative growth advantage as per cov-spectrum in recent 3 months in Brunei against baseline**:
![image](https://user-images.githubusercontent.com/86835836/177770898-a13c5691-f1d5-422c-aa91-ec4d26cefd8b.png)

### Genomes:
EPI_ISL_13088370, EPI_ISL_13276895, EPI_ISL_13511332, EPI_ISL_13511353-13511354, EPI_ISL_13511362, EPI_ISL_13511364, EPI_ISL_13511377, EPI_ISL_13512183, EPI_ISL_13512195-13512196, EPI_ISL_13512205-13512207, EPI_ISL_13512221, EPI_ISL_13512232-13512235, EPI_ISL_13512249-13512251, EPI_ISL_13512255-13512256, EPI_ISL_13602516, EPI_ISL_13602522-13602523, EPI_ISL_13602526, EPI_ISL_13602530-13602535, EPI_ISL_13602538-13602539, EPI_ISL_13602546, EPI_ISL_13602558, EPI_ISL_13602561-13602563, EPI_ISL_13602565

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.3.19 with 23 newly designated sequences. Defining mutation(s) A22812C (S:N417T), then T6980G (ORF1a:C2239G).
