### ISSUE TITLE
Indian BF.3 sublineage with additional S:G446S (6%, 91 sequences as of 2022-07-25, international spread)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#825]
### Description
**Sublineage of**: BF.3
**Earliest sequence**: 2022/05 (India-Karnataka)
**Most recent sequence**: 2022/06/23 (India-Tamil Nadu)
**Mutations on top of BF.3**: G22898A (S:G446S), C27549T
**Countries circulating**: India, predominantly Tamil Nadu (32/33)

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/177774039-e589ea58-d079-4e80-b07c-202c6d8d6636.png)
(a few genomes are misplaced in sibling branches apparently because of drop-outs)

### Genomes:
EPI_ISL_13204108, EPI_ISL_13342087, EPI_ISL_13342127, EPI_ISL_13342142, EPI_ISL_13342144, EPI_ISL_13342153, EPI_ISL_13409416, EPI_ISL_13446570, EPI_ISL_13446586, EPI_ISL_13657276-13657277, EPI_ISL_13657344, EPI_ISL_13657361, EPI_ISL_13657371, EPI_ISL_13657375, EPI_ISL_13657384, EPI_ISL_13657386, EPI_ISL_13666968-13666970, EPI_ISL_13666981, EPI_ISL_13667055, EPI_ISL_13667115, EPI_ISL_13667120, EPI_ISL_13667991, EPI_ISL_13668029, EPI_ISL_13668041, EPI_ISL_13668046, EPI_ISL_13668049, EPI_ISL_13668056, EPI_ISL_13668060, EPI_ISL_13668085, EPI_ISL_13668107

**Comment by FedeGueli** [comment]
Great catch @c19850727 : it is a 3 Spike mutation sublineage with S:1020S S:547I and S:446S, something to keep monitored closely. Competition between lineages actually appears wild in India. so lets see what happens with this.

**Comment by c19850727** [comment]
41 sequences as of 2022-07-17, and newly found in Czech, Singapore (local case), China-Yunnan (local case), Australia-NSW and US-VA.

**Comment by c19850727** [comment]
89 sequences as of 2022-07-23. 
~8% prevalence in Tamil Nadu according to covspectrum based on only 23 sequences (should be 66 sequences as per GISAID).
![image](https://user-images.githubusercontent.com/86835836/180606685-89193086-a82e-4137-a314-9119045b2840.png)

Also newly found in Israel, Korea ex-India and Japan ex-India.

**Comment by corneliusroemer** [comment]
I'd designate this given the significant growth in India, known spike mutation of interest and starting international spread.

**Comment by FedeGueli** [comment]
If i am not wrong @c19850727 spotted a fourth spike mutation acquired in a sub lineage of this.

**Comment by FedeGueli** [comment]
Here its growth diadvantage versus BA.2.75 baseline in India (past 2 months) : -11%
![Schermata 2022-07-25 alle 16 21 56](https://user-images.githubusercontent.com/87669813/180799869-72f547dd-2278-44cc-8b10-4cf5715feffe.png)
https://cov-spectrum.org/explore/India/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.2.75*&aaMutations1=S%3A446S%2CS%3A1020S%2CS%3A547I&analysisMode=CompareToBaseline&

It has also a 21% of Gr.Adv. vs BA.5 baseline in India:
![Schermata 2022-07-25 alle 16 22 49](https://user-images.githubusercontent.com/87669813/180800059-6ff301a2-20b2-4c81-8d4e-c4aea6b25be9.png)
https://cov-spectrum.org/explore/India/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.5*&aaMutations1=S%3A446S%2CS%3A1020S%2CS%3A547I&analysisMode=CompareToBaseline&

@corneliusroemer @chrisruis @InfrPopGen

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.3.1 with 35 newly designated sequences, and 5 updated designations from BF.3. Defining mutation G22898A (S:G446S), preceded by C27549T.
