### ISSUE TITLE
Potential BA.2.12.1 and BA.4 recombinant with multiple breakpoints (38 seqs as of 2022-07-18, mainly UK)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#826]
### Description
**Recombinant between**: BA.2.12.1 and BA.4
**Earliest sequence**: 2022/06/09 (UK-England)
**Most recent sequence**: 2022/07/01 (UK-England)
**Countries circulating**: UK-England (17/19)
**Cases found at border entry**: Korea ex-Maldives (2/19)
**Likely breakpoint**: _to be updated later_
**Mutations from potential BA.2.12.1 donor**: ORF1a:L3201F, S:S704L, A12160G, C15009T
**Mutations from potential BA.4 donor**: S:69/70del, S:L452R, S:F486V, S:R493Q reversion, S:N658S
![image](https://user-images.githubusercontent.com/86835836/177785112-23941b68-4235-48d2-aff0-dfdfc36c1d31.png)
**GISAID query**: Spike_H69del, Spike_L452R, Spike_S704L, Spike_N658S, NSP4_L438F
**Cov-spectrum query**: T15009C, 9866T, 23673T, 23535G, 22917G, 23040A

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/177784889-eff34d0f-6823-433d-9125-854787676a5e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_150a2_6de290.json?branchLabel=Spike%20mutations&c=gt-nuc_23040,15009&label=nuc%20mutations:T22917A

### Genomes:
EPI_ISL_13338123, EPI_ISL_13515716, EPI_ISL_13518141, EPI_ISL_13603584, EPI_ISL_13690214-13690215, EPI_ISL_13693012, EPI_ISL_13693033, EPI_ISL_13693042, EPI_ISL_13693048, EPI_ISL_13693102, EPI_ISL_13693105, EPI_ISL_13693115, EPI_ISL_13693124, EPI_ISL_13693127, EPI_ISL_13693130, EPI_ISL_13693132, EPI_ISL_13693157-13693158

**Comment by agamedilab** [comment]
Most UK sequences originate from the sameupload (7.7.2022), sample day (30.6.22) and sequencing lab (Welcome Sanger) so they possibly originate from the same sequencing run.

Some of them carry some non-ACGTN characters which is a bit suspicous.

![grafik](https://user-images.githubusercontent.com/102166254/177787374-1982cf3b-eb89-4954-b1af-11eb8432f885.png)

**Comment by c19850727** [comment]
Thanks @agamedilab I didn't notice this.

I've been monitoring this cluster before this big upload from Welcome Sanger, and what prompted me to propose was those 2 mysterious Korean sequences with recent travel history from Maldives. 

It might imply some undetected transmission either among tourists in one of the Maldivian islands, or, in a worse scenario, at one of Middle Aast flight transit hubs.

**Comment by c19850727** [comment]
20 sequences as of 2022-07-08.

**Comment by c19850727** [comment]
23 sequences as of 2022-07-08, and now from a different lab in the UK (PHE).

**Comment by c19850727** [comment]
24 sequences as of 2022-07-09. Newly found in US-WA.

**Comment by c19850727** [comment]
26 sequences as of 2022-07-09. Newly found in Israel.

**Comment by c19850727** [comment]
30 sequences as of 2022-07-11.

**Comment by thomasppeacock** [comment]
UKHSA have been having a look at this and as far as they can see it looks legitmate (no evidence of mixed bases at BA.2/BA.4 lineage defining sites).

@chrisruis although this hasnt yet hit the threshold for minimum number of recombinants I reckon it might be worth assigning as i) this is 30 sequences in the UK's current much lower sequence numbers, ii) its an interesting/unique recombinant (2 breakpoints ~Spike region) and iii) clear evidence of international spread. Thanks!

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAJ with 35 newly designated sequences, and 0 updated designations. Defining mutations (clade root): A23535G, A27259C
