### ISSUE TITLE
Proposal for a Sublineage of BA.5.2.1 with S:R346T and N:S33F (originally proposed by @FedeGueli)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#827]
**_All credit to @FedeGueli for being the first to spot and propose this lineage_** 

**Description**
**Sub-lineage of**: BA.5.2.1
**Earliest sequence**: 2022-5-13, Belgium (EPI_ISL_12810243)
**Most recent sequence**: 2022-7-4, Belgium (EPI_ISL_13697283)
**Countries circulating**: Belgium (84), UK (21), Luxembourg (8), Netherlands (6), Denmark (4), France (4), Germany (2), Spain (1), Austria (1), Israel (1), USA (1)
**Number of Sequences**: 133 on GISAID (via search for “Spike_R346T, N_S33F, Spike_F486V, M_D3N”)
**Substitutions on top of BA.5.2.1**: 
Spike: R346T
N: S33F
Nucleotide: C7528T, G22599C, G28371T

USHER Tree
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_2830b_7344b0-5.2.1sub.json 

![Screen Shot 2022-07-07 at 6 01 05 PM](https://user-images.githubusercontent.com/33738461/177878921-d4d126c8-c5be-404d-a6cc-464b24658424.png)

**Evidence**
CovSpectrum: 46% (CI:22%-69%) weekly growth advantage compared to nextcladePangoLineage:BA.5.2.1* in the last three months in Europe. (Compared to nextcladePangoLineage:BA.5* its growth advantage is even larger, at 58% [CI:32%-84%])   
https://cov-spectrum.org/explore/Belgium/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.1*+%26+%21C7528T+%26+%21G22599C&variantQuery1=nextcladePangoLineage%3ABA.5.2.1*+%26+C7528T+%26+G22599C+%26+G28371T&analysisMode=CompareToBaseline&

![Screen Shot 2022-07-07 at 5 01 00 PM - Europe](https://user-images.githubusercontent.com/33738461/177870775-0ea66a5c-4f7f-4187-848e-06ab45a24fd4.png)

CovSpectrum: 39% (CI:11%-67%) weekly growth advantage compared to nextcladePangoLineage:BA.5.2.1* in the last three months in Belgium: https://cov-spectrum.org/explore/Belgium/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.1*+%26+%21C7528T+%26+%21G22599C&variantQuery1=nextcladePangoLineage%3ABA.5.2.1*+%26+C7528T+%26+G22599C+%26+G28371T&analysisMode=CompareToBaseline&

![Screen Shot 2022-07-07 at 5 01 41 PM - Belgium](https://user-images.githubusercontent.com/33738461/177871482-078eda94-e592-417f-b7c4-d68f5168f2e5.png)

R346T is a known RBD escape mutation, one of the largest according to the Bloom Lab escape calculator. https://jbloomlab.github.io/SARS2_RBD_Ab_escape_maps/escape-calc/

![Screen Shot 2022-07-07 at 4 37 39 PM - Bloom Lab Escape Calculator R346](https://user-images.githubusercontent.com/33738461/177871426-95d64242-4d61-4223-ba0f-59e0595593c6.png)

Furthermore, according to the Bloom Lab ACE2 Binding/Expression Heat Map, R346T increases both ACE2 binding and RBD expression (on a BA.2 RBD background).

![Screen Shot 2022-07-07 at 4 34 25 PM - BA 2 RBD Heat Map](https://user-images.githubusercontent.com/33738461/177869551-9e7e85b7-8119-4682-a712-38197cac5e97.png)

As shown in BA.4.6 and several BA.2 sublineages with R346T, this mutation confers a substantial growth advantage to Omicron lineages, and I expect this sublineage will continue to rapidly increase as a proportion of all BA.5. 

**Genomes**
[GISAID_hcov-19_ids_2022_07_07_20_42.csv](https://github.com/cov-lineages/pango-designation/files/9067336/GISAID_hcov-19_ids_2022_07_07_20_42.csv)

**Comment by ryhisner** [comment]
Just realized this is almost the same as Issue #802, except that issue didn't include N:S33F, which is what I had searched for to see if this had already been proposed. I don't know whether I should close/delete this or not.

**Comment by FedeGueli** [comment]
@ryhisner thx for noticing that! i was thinking it was related to #722 but it has nothing to do with it and instead  as you said this  a sublineage of #802 that i missed to update in the past days.

So.i would let this open until we ll see wheter the #802 will be solved with designation or not.

Have you checked if this S:346T+N:33F has some advantage vs #802?

**Comment by ryhisner** [comment]
https://github.com/cov-lineages/pango-designation/issues/722#issuecomment-1179355266
@AngieHinrichs helpfully points out in #722 that the G28371T mutation here does not actually cause N:S33F, as GISAID reports, or N:S33I, as in the UShER tree, but rather results in a final effect, when combined with the deletion of bases 28362-28370 (found in all BA.5 as well as BA.1 and BA.2), of N:30_33delGERSinsV. 

Would it be accurate to change N:S33F to N:S33V in the title of this proposal? That seems right to me, but I'm not an expert and want to be sure.

**Comment by FedeGueli** [comment]
179 sequences as today

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.7 with 59 newly designated sequences, and 15 updated designations from BA.5.2.1. Defining mutation(s) G28371T (N:S33).

**Comment by Mydtlwn** [comment]
R346T and T1050N are both mutations that often appear in various mutant strains recently.

**Comment by AngieHinrichs** [comment]
... and this would be a good time for me to mention that I've just started masking positions 28361 and 28371 in the BA.2 branch (which includes BA.4 and BA.5) because they are very noisy and caused major tree problems.  Sorry this means that if there's anything real going on at N:33 (and not just sequencing/assembly errors) it will not be visible in the UShER tree.  BF.7's path in the UShER tree is now BA.5.2.1 > G22599C > C7528T.

**Comment by RaphaelRaphael** [comment]
I think this BF.7 actually rising in Canada is carying this TT mutations next to the N protein deletion : https://github.com/cov-lineages/pango-designation/issues/1069
