### ISSUE TITLE
BA.2.38 sublineage defined by S:K444N, Orf1a:T1543I, Orf1a:N3725S, Orf1a:T4355I and S:F157S circulating in India (142 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#828]
As suggested by @chrisruis in #814 i open this issue to propose separately a BA.2.38 sublineage that seems to be part of the diversity sequenced in India during the last weeks.

Credits to : @c19850727 who spotted this first and monitored it since.

This sublineage is a sibling lineage of the one proposed in #746 by @sinickle , as explained very well by him there, we have seen and tracked multiple BA.2 sublineages with a double S mutation S:K417T+S:K444N but the one that seems more relevant was this one:
BA.2.38 (=BA.2+25416T+S:417T) sublineage with T7153C, G22894C (S:K444N)
as it is easy to observe in this tree:
![Schermata 2022-07-07 alle 23 33 56](https://user-images.githubusercontent.com/87669813/177875168-f39f3bd5-693e-4277-b0fe-aad75d3637a6.png)
It is splitted in two branches: 
In the upper part of the tree there is #746 defined by Orf1b:D51N 
In the lower part there is the branch that i want to propose here defined by Orf1a:T1543I (C4893T ) in NSP3 and Orf1a:N3725S (A11439G) in NSP6.
This branch acquired C17373T then orf1a:T4355I (C13329T) and finally S:F157S (T22032C) from which i suggest to start the lineage if it will be designated.
Usher tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_268ca_74e160.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C4893T,A11439G
![Schermata 2022-07-07 alle 23 45 15](https://user-images.githubusercontent.com/87669813/177876733-016865f7-6662-46be-be8c-a94225012cba.png)

Number of sequences: 26
Sequences list (the only 12 carrying all the defining mutations):
[contributors (1).csv](https://github.com/cov-lineages/pango-designation/files/9067539/contributors.1.csv)
Countries: 22 out of 26 sequences are from India plus 2 earlier in May from Nepal (with an additional substitution S:A264S) 1 from Canada and 1 from Japan likely from airport surveillance.
Apparent regional prevalence in India (past 2 months)
![Schermata 2022-07-07 alle 23 54 01](https://user-images.githubusercontent.com/87669813/177877848-c0dc503a-50ff-4c3b-ad95-9eef3aecb982.png)

 Covspectrum Overview for India: https://cov-spectrum.org/explore/India/AllSamples/Past6M/variants?aaMutations=ORF1a%3AN3725S%2Corf1a%3AT1543I%2CS%3A157S&nucMutations=T7153C%2CC17373T&

Growth advantage versus BA.2.38 :
![Schermata 2022-07-07 alle 23 58 02](https://user-images.githubusercontent.com/87669813/177878377-bb011e6e-9550-4088-b686-94c7fff10790.png)
https://cov-spectrum.org/explore/India/AllSamples/Past3M/variants?aaMutations=S%3A417T&nucMutations=25416T&aaMutations1=ORF1a%3AN3725S%2Corf1a%3AT1543I%2CS%3A157S%2CS%3A417T&nucMutations1=T7153C%2CC17373T%2C25416T%2CG22894C&analysisMode=CompareToBaseline&

Growth disadvantage versus BA.5 baseline:
![Schermata 2022-07-08 alle 00 00 05](https://user-images.githubusercontent.com/87669813/177878653-4aa11a78-a848-4bb1-8645-dd3ac7565c50.png)
https://cov-spectrum.org/explore/India/AllSamples/Past3M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=ORF1a%3AN3725S%2Corf1a%3AT1543I%2CS%3A157S%2CS%3A417T&nucMutations1=T7153C%2CC17373T%2C25416T%2CG22894C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
49 sequences as today

**Comment by FedeGueli** [comment]
63 Sequences as today. Now it has been found in 7 countries from 3 continents: newly found in South Korea, Canada , Usa , Belgium )
![Schermata 2022-07-15 alle 14 41 05](https://user-images.githubusercontent.com/87669813/179224971-4d525fd5-931f-4d81-ba58-846e669e7077.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e16f_15d990.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:T22032C

@chrisruis 

thx to @bitbyte2015 for highlighting its growth.

**Comment by FedeGueli** [comment]
Query updated to NCPL BA.5 baseline:
-17% 
https://cov-spectrum.org/explore/India/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5*&aaMutations1=ORF1a%3AN3725S%2Corf1a%3AT1543I%2CS%3A157S&nucMutations1=C17373T%2CG22894C&analysisMode=CompareToBaseline&

**Comment by silcn** [comment]
This lineage has a branch with S:146del that is concentrated in Assam, India, where it makes up 52 of the most recent batch of 81 samples, dated 06-20 to 07-01 and received 07-20. Prior to this, sequencing in Assam had been virtually non-existent since February.
In addition there are 2 sequences from other Indian states, 2 from the US and 1 from Germany, making 57 in total.

The Usher tree ignores deletions so S:146del doesn't form its own branch; however, it almost does, because all but one of the sequences also have ORF1a:G445V and nuc:C2623T, and that branch is shown in blue on the tree below. The other sequence with S:146del is shown in yellow.

<img width="734" alt="BA238_146del" src="https://user-images.githubusercontent.com/42699509/180102529-cb5f7a10-409a-4f2a-a812-b5bed6d2c396.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_5840_88f3b0.json?branchLabel=Spike%20mutations&c=gt-nuc_1599,25047&label=nuc%20mutations:C13329T](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_5840_88f3b0.json?branchLabel=Spike%20mutations&c=gt-nuc_1599,25047&label=nuc%20mutations:C13329T)

**Comment by FedeGueli** [comment]
Thx @Silcn great catch of that branch of it.
It is a  big jump to 130seqs today.

@chrisruis @corneliusroemer @AngieHinrichs  
at this point a designation of the last 3 big BA.2.38 undesignated sublineages (this one , the apparent sibling in #746 and the other with S:478R in #840
 is well deserved and it will help indian scientists to monitor themselves what is going on there.

**Comment by FedeGueli** [comment]
142 sequences as today.

For the first time this lineage shows a growth advantage versus BA.5. Baseline in India: +14%
https://cov-spectrum.org/explore/India/AllSamples/Past3M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=ORF1a%3AN3725S%2Corf1a%3AT1543I%2CS%3A157S&nucMutations1=T7153C%2CC17373T%2C25416T&analysisMode=CompareToBaseline&
![Schermata 2022-07-23 alle 09 29 29](https://user-images.githubusercontent.com/87669813/180595303-afce8e88-a9ea-4378-8d5d-db800d704a0c.png)


https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3844a_b9f920.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T22032C

**Comment by AngieHinrichs** [comment]
Seen in Belgium, USA and Germany in July:

Belgium/UZA-UA-CV8522008253/2022|EPI_ISL_13694971|2022-07-02
USA/NJ-CDC-QDX38676038/2022|EPI_ISL_14003738|2022-07-03
USA/TX-HMH-MCoV-105165/2022|EPI_ISL_13891446|2022-07-06
Germany/BW-RKI-I-910479/2022|EPI_ISL_13943369|2022-07-12

**Comment by FedeGueli** [comment]
Thanks @AngieHinrichs notably this sublineage has just 11% of disadvantage versus BA.2.75 baseline in India comparable to the BA.4 disadvantage vs BA.5 .
I suggest a designation  of this  also considering a sublineage of it gained Orf1a:A2529V (defining mutation of AY.4 that boosted its trasmissibility vs original B.1.617.2)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.38.2 with 55 newly designated sequences, and 2 updated designations from BA.2.38. Defining mutation(s) T22032C (S:F157S), preceded by C13329T (Orf1a:T4355I) and C17373T.

**Comment by romiwahengbam** [comment]
@InfrPopGen @FedeGueli @silcn 
In our last run of 96 samples from Assam, IN, today we found 68 more sequences designated as BA.2.38 among samples from July 2022, but with S:F157S and couple of mutations in Orf1a. This mutation is currently dominating our samples.
![image](https://user-images.githubusercontent.com/3704206/180708514-ff54837c-9c9e-4cca-9b9e-71b740689286.png)

**Comment by ryhisner** [comment]
Wanted to point out a very interesting branch in this lineage that has, in addition to spike mutations F157S, K417T, and K444N, also has A264S and L244F/H245del (or L244del/H245F, as NextClade interprets it). A GISAID search for Spike_F157S, Spike_A264S, Spike_K444N returns 11 sequences, while Spike_F157S, Spike_A264S, Spike_K444N, Spike_L244F returns nine. Six of these 11 sequences were uploaded either today or yesterday: EPI_ISL_14162147, EPI_ISL_14176006, EPI_ISL_14192615, EPI_ISL_14192617, EPI_ISL_14192709, EPI_ISL_14196580

Strangely, the first two sequences in this branch (EPI_ISL_13388893, EPI_ISL_13388894) were collected on 2022-5-23, both from Nepal. Then nothing more until July, and now six uploaded in the past two days.

The Usher tree contains 15 sequences. 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_3ade4_983f10--F157S%2CL244F%2CA264S%2CK417T%2CK444N.json
![Screen Shot 2022-08-02 at 4 56 42 PM](https://user-images.githubusercontent.com/33738461/182472072-fc2aa423-c334-49cb-b631-70243baafc22.png)
![Screen Shot 2022-08-02 at 5 04 46 PM](https://user-images.githubusercontent.com/33738461/182473151-8adddf93-f591-4aa1-a648-1694d76b977b.png)

**Comment by silcn** [comment]
@ryhisner I was watching this one too. I'm tempted to believe that the order is LH244-245F and then A264S, owing to the existence of a single sequence (EPI_ISL_14166895) that has the first but not the second. As you might have noticed, the sequences with A264S but not LH244-245F are also missing 24-26del, so there's some issue with the sequencing that's causing deletions to be missed.

**Comment by FedeGueli** [comment]
@ryhisner @silcn the S:264S + S:245F branch now counts 19 sequences and 5 countries (indonesia added) https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1b93d_ff2590.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:G22352T
![Schermata 2022-08-07 alle 19 36 33](https://user-images.githubusercontent.com/87669813/183303681-b1a795f5-8e64-49dd-94ed-cb6554a8cb0b.png)

I think it deserves a proposal.

(btw big jump today for the BA.2.38.2 lineage to 315 sequences, one of the cases where initial growth rate has been underestimated)

**Comment by FedeGueli** [comment]
@silcn @ryhisner two new sequences of the cluster with S:A264S and Spike H245del (on gisaid) both from Singapore and very recent (collection date end of July early august)  EPI_ISL_14358975, EPI_ISL_14353705. 
I think maybe it is worth proposing it

**Comment by FedeGueli** [comment]
@silcn @ryhisner one more sequence of yur S:264S sublineage with S:244del and 245F. From Australia.
27 sequences as today (keeping as valid the three messy ones in the upper part of the tree):
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_19747_15a2a0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G22352T

**Comment by corneliusroemer** [comment]
Feel free to propose @FedeGueli looks like a useful one to have there - better than discussing here

**Comment by FedeGueli** [comment]
Thx @corneliusroemer i will!
