### ISSUE TITLE
Sequence with 62/64 alt alleles for BA.2 and 61/64 for BA.4

### ISSUE THREAD

**Issue by bioinforME** [cov-lineages/pango-designation#829]
[QLD0x00FB3D_fasta.txt](https://github.com/cov-lineages/pango-designation/files/9068729/QLD0x00FB3D_fasta.txt)
We here at Queensland Australia just found this attached sequence (not in GISAID yet) has 62/64 alt alleles for BA.2 and 61/64 for BA.4 when tested against constellation, but it does have ref allele at n:P151S, which would have failed BA.4 rule, and it also have ref allele at "spike:Q493", which would have failed BA.2 rule. But this sequence has a scorpio call of BA.2, USher lineage assignment is BA.4.

Two points i would like to raise here:
**First** **Scorpio** failed to check all the rules at least for BA.2, "spike:Q493":"alt". We may need a **bug fix** here.

**Second**, considering the mutations this sequence has got, which is **BA.2, S:Q493Q (ref), S:F486V, S:L452R, S:V213G, N:P151P (ref)** and it may have some prevalence according to [COV-Spectrum](https://cov-spectrum.org/explore/Australia/AllSamples/Past6M/variants?aaMutations=S%3AF486V%2CS%3AL452R%2CS%3AV213G%2CS%3AQ493Q%2CN%3AP151P&pangoLineage=BA.2&), we'd like to **propose a new lineage**. My colleague from Western Australia also found some similar sequences, e.g. hcov-19/Australia/WA4844/2022, which is on GISAID.

**Comment by bioinforME** [comment]
For the first point,  it is quite obvious from Scorpio haplotype check against Omicron (BA.2-like) that the sequence has the ref allele at "spike:Q493" which breaks the BA.2 constellation rule and thus shouldn't be called a BA.2:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/WangChen/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/WangChen/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



query | ref_count | alt_count | ambig_count | other_count | support | conflict | orf1ab:S135R | orf1ab:T842I | orf1ab:G1307S | nuc:C4321T | orf1ab:L3027F | nuc:A9424G | orf1ab:T3090I | orf1ab:L3201F | nuc:C10198T | nuc:G10447A | orf1ab:SGF3675- | nuc:C12880T | nuc:C15714T | orf1ab:R5716C | orf1ab:T6564I | nuc:A20055G | spike:T19I | del:21633:9 | nuc:T22200G | spike:S371F | spike:T376A | spike:D405N | spike:R408S | spike:Q493R | nuc:C25000T | nuc:C25584T | nuc:C26060T | nuc:C26858T | orf6:D61L | n:RG203KR | n:S413R
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Australia/QLD0x00FB3D/2022 | 1 | 29 | 1 | 0 | 0.9355 | 0.0323 | R | I | S | T | F | G | I | X | T | A | 3 | T | T | C | I | G | I | 3 | G | F | A | N | S | Q | T | T | T | T | L | KR | R



</body>

</html>

**Comment by bioinforME** [comment]
As for the parent lineage, this sequence has 33 alt alleles:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/WangChen/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/WangChen/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



query | ref_count | alt_count | ambig_count | other_count | support | conflict | nuc:C3037T | orf1ab:T3255I | orf1ab:P3395H | orf1ab:P4715L | orf1ab:I5967V | spike:G142D | spike:G339D | spike:S373P | spike:S375F | spike:K417N | spike:N440K | spike:S477N | spike:T478K | spike:E484A | spike:Q498R | spike:N501Y | spike:Y505H | spike:D614G | spike:H655Y | spike:N679K | spike:P681H | spike:N764K | spike:D796Y | spike:Q954H | spike:N969K | e:T9I | m:Q19E | m:A63T | nuc:A27259C | nuc:C27807T | nuc:A28271T | n:P13L | del:28362:9
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Australia/QLD0x00FB3D/2022 | 0 | 33 | 0 | 0 | 1 | 0 | T | I | H | L | V | D | D | P | F | N | K | N | K | A | R | Y | H | G | Y | K | H | K | Y | H | K | I | E | T | C | T | T | L | 3



</body>

</html>

For BA.4, it has 28/31 alt alleles, just the ref allele at n:P151S failed the constellation for BA.4:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/WangChen/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/WangChen/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



query | ref_count | alt_count | ambig_count | other_count | support | conflict | orf1ab:S135R | orf1ab:T842I | orf1ab:G1307S | nuc:C4321T | orf1ab:T3090I | nuc:C10198T | nuc:G10447A | del:11288:9 | nuc:G12160A | nuc:C12880T | nuc:C15714T | orf1ab:R5716C | orf1ab:T6564I | nuc:A20055G | spike:T19I | s:HV69- | spike:V213G | spike:S371F | spike:T376A | spike:D405N | spike:L452R | spike:F486V | nuc:C25000T | nuc:C25584T | nuc:C26060T | nuc:C26858T | orf6:D61L | nuc:G27788T | n:P151S | n:RG203KR | n:S413R
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Australia/QLD0x00FB3D/2022 | 3 | 28 | 0 | 0 | 0.9032 | 0.0968 | R | I | S | T | I | T | A | 3 | G | T | T | C | I | G | I | 2 | G | F | A | N | R | V | T | T | T | T | L | G | P | KR | R



</body>

</html>

**Comment by FedeGueli** [comment]
Isnt this one you are  talking about just BA.5? 

have you got the Gisaid EPI ISL?

**Comment by JosetteSchoenma** [comment]
I have run them through Sc2rf. The Australia/QLD0x00FB3D/2022 looks like a BA.4/BA.2 recombinant to me, with at least a BA.4 spike. With, among others, a private mutation A27038G that BA.5.2.1 has as well. 
The WA4844 = EPI_ISL_13613051 looks like a BA.4 to me.
Summary Australia/QLD0x00FB3D/2022:
G12160G - BA.2
**T22917G - BA.4, S:L452R
T23018G - BA.4, S:F486V
A23040A - BA.4, so no S:R493Q like BA.2**
G26259G - BA.2/BA.4, so no M:D3N like BA.5
A27038G - BA.5.2.1 
G27788G - BA.2, so no ORF7B:L11F like BA.4
G27889N - ??? BA.2 and BA.4 both have C, BA.5 has T
C28724C - BA.2, so no N:P151S like BA.4
![image](https://user-images.githubusercontent.com/94831035/178437304-7d25144a-1dd5-4a26-9860-5ed4c83a53e0.png)

Unfortunately Sc2rf does not show the 69/70 deletions, which would be interesting to know to see if that part is BA.4 or BA.2! They are at nucleotide sides 21767 and 21770.

**Comment by FedeGueli** [comment]
> it may have some prevalence according to [COV-Spectrum](https://cov-spectrum.org/explore/Australia/AllSamples/Past6M/variants?aaMutations=S%3AF486V%2CS%3AL452R%2CS%3AV213G%2CS%3AQ493Q%2CN%3AP151P&pangoLineage=BA.2&), we'd like to **propose a new lineage**. My colleague from Western Australia also found some similar sequences, e.g. hcov-19/Australia/WA4844/2022, which is on GISAID.
 hi @bioinforME to me that query finds plain BA.5 sequences.

**Comment by silcn** [comment]
@JosetteSchoenma it does have 69/70del

**Comment by JosetteSchoenma** [comment]
Thank you, @silcn . That adds an extra part of the spike that would then be BA.4.

Adjusted summary Australia/QLD0x00FB3D/2022:
G12160G - BA.2
**C21767- - BA.4, S:H69del
G21770- - BA.4, S:V70del
T22917G - BA.4, S:L452R
T23018G - BA.4, S:F486V
A23040A - BA.4, so no S:R493Q like BA.2**
G26259G - BA.2/BA.4, so no M:D3N like BA.5
A27038G - BA.5.2.1
G27788G - BA.2, so no ORF7B:L11F like BA.4
G27889N - ??? BA.2 and BA.4 both have C, BA.5 has T
C28724C - BA.2, so no N:P151S like BA.4

**Comment by bioinforME** [comment]
> have you got the Gisaid EPI ISL?

Yes, it is EPI_ISL_13787385

**Comment by corneliusroemer** [comment]
Thanks for the discussion but I don't think this is relevant anymore so I'll close.
