### ISSUE TITLE
(apparent) B.1.617.2 sequences assigned as B.1.153

### ISSUE THREAD

**Issue by jcbarret** [cov-lineages/pango-designation#83]
A number of samples with test dates in late April and early May matched the B.1.617.2 VOC genotyping definition at https://github.com/phe-genomics/variant_definitions/blob/main/variant_yaml/empathy-serve.yml, but were assigned lineage B.1.153 (pangolin version 2.4.2, pangoLEARN 2021-04-28, pango version 1.1.23).

These should arrive in GISAID shortly with the following identifiers:

```hCoV-19/England/MILK-1550FB1/2021
hCoV-19/England/MILK-15557D2/2021
hCoV-19/England/MILK-1555B03/2021
hCoV-19/England/MILK-15554AE/2021
hCoV-19/England/MILK-1555769/2021
hCoV-19/England/MILK-152B8B4/2021
hCoV-19/England/MILK-1550ED2/2021
hCoV-19/England/MILK-1555C6A/2021
hCoV-19/England/QEUH-15535BC/2021
hCoV-19/England/MILK-152B73F/2021
hCoV-19/England/MILK-1555796/2021
hCoV-19/England/MILK-15555AB/2021
hCoV-19/England/ALDP-153B778/2021
hCoV-19/England/MILK-15650B6/2021
hCoV-19/England/MILK-1555C5B/2021

**Comment by AngieHinrichs** [comment]
Thanks @jcbarret for reporting these.  @jeremydratcliff reported some of those and some additional cases in [pangolin issue 194](https://github.com/cov-lineages/pangolin/issues/194) as well.  I will merge the lists and add them as B.1.617.2 representatives.

**Comment by charlesfoster** [comment]
Hi,

Just in case it's of interest, I tested the new `pangolin` v3.03 on some sequences that appear like they should be B.1.617.2, [but were previously not called as such](https://github.com/cov-lineages/pangolin/issues/195). These sequences are: EPI_ISL_2107499, EPI_ISL_2107500, EPI_ISL_2107501, and EPI_ISL_2107506. I ran `pangolin` first using pangoLEARN for inference, and then using USHER (--usher).

Results:

taxon | lineage | conflict | ambiguity_score | scorpio_call | scorpio_support | scorpio_conflict | version | pangolin_version | pangoLEARN_version | pango_version | status | note
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
EPI_ISL_2107499 | B.1.367 | 0 | 1 | cB.1.617.2 | 0.5 | 0 | PLEARN-v1.2.6 | 3.0.3 | 2021-05-27 | v1.2.6 | passed_qc | scorpio call: Alt alleles 6; Ref alleles 0; Amb alleles 6
EPI_ISL_2107500 | B.1.617.2 | 0 | 1 | cB.1.617.2 | 0.6667 | 0 | PLEARN-v1.2.6 | 3.0.3 | 2021-05-27 | v1.2.6 | passed_qc | scorpio call: Alt alleles 8; Ref alleles 0; Amb alleles 4
EPI_ISL_2107501 | B.1.367 | 0 | 1 | cB.1.617.2 | 0.5 | 0 | PLEARN-v1.2.6 | 3.0.3 | 2021-05-27 | v1.2.6 | passed_qc | scorpio call: Alt alleles 6; Ref alleles 0; Amb alleles 6
EPI_ISL_2107506 | B.1.617.2 | 0 | 1 | cB.1.617.2 | 0.5833 | 0 | PLEARN-v1.2.6 | 3.0.3 | 2021-05-27 | v1.2.6 | passed_qc | scorpio call: Alt alleles 7; Ref alleles 0; Amb alleles 5
EPI_ISL_2107499 | B.1.617.2 | &nbsp; | &nbsp; | cB.1.617.2 | 0.5 | 0 | PUSHER-v1.2.6 | 3.0.3 | &nbsp; | v1.2.6 | passed_qc | scorpio call: Alt alleles 6; Ref alleles 0; Amb alleles 6
EPI_ISL_2107500 | B.1.617.2 | &nbsp; | &nbsp; | cB.1.617.2 | 0.6667 | 0 | PUSHER-v1.2.6 | 3.0.3 | &nbsp; | v1.2.6 | passed_qc | scorpio call: Alt alleles 8; Ref alleles 0; Amb alleles 4
EPI_ISL_2107501 | B.1.617.2 | &nbsp; | &nbsp; | cB.1.617.2 | 0.5 | 0 | PUSHER-v1.2.6 | 3.0.3 | &nbsp; | v1.2.6 | passed_qc | scorpio call: Alt alleles 6; Ref alleles 0; Amb alleles 6
EPI_ISL_2107506 | B.1.617.2 | &nbsp; | &nbsp; | cB.1.617.2 | 0.5833 | 0 | PUSHER-v1.2.6 | 3.0.3 | &nbsp; | v1.2.6 | passed_qc | scorpio call: Alt alleles 7; Ref alleles 0; Amb alleles 5

USHER and scorpio seem to get it 'right', but pangoLEARN designation is still incorrect for two of the four samples. I'm guessing there are one or more key SNPs not present for whatever reason.

Cheers,
Charles
