### ISSUE TITLE
BA.2 sublineage defined by eight mutations incl S: L452M, found in 5 countries.

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#831]
13 samples

Defined by 8 nucsubs (3 NS) :
C703A
C934T
C2847T (ORF1a:T861I)
T4771A
T7942C
G9431A(OEF1a:V3056I)
C22916A(S:L452M)
C28435T

Found in : 
Bahrain, Israel, USA(NJ and Texas), India, Indonesia.

Usher Build

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_163a6_823a00.json?c=country

![image](https://user-images.githubusercontent.com/80166370/177995919-c0c1a666-872d-4e54-a27c-f0932ed7af79.png)

Samples from GISAID :
EPI_ISL_13691989
EPI_ISL_13426512
EPI_ISL_13543589
EPI_ISL_13613414
EPI_ISL_13311052
EPI_ISL_13452175
EPI_ISL_13461425

CovSpectrum query : 
[5-of:C703A,C934T,C2847T,T4771A,T7942C,G9431A,C22916A,C28435T]

For now, minimal sample #, but the geographic distribution makes it worth monitoring.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As there has been very little growth over the past month, this issue is being closed for now. Nevertheless, please reopen if there should be signs of substantial growth advantage or epidemiological significance in the future.
