### ISSUE TITLE
New BA.2.12.1 sublineage with Spike:Q675H,Q677H, Nuc:G23587T,G23593T mutations circulating in USA and Peru.

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#833]
**Description**
Potential omicron sub-lineage with S:Q675H,Q677H, Nuc:G23587T, G23593T mutations proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru. Only as an observation, S:Q675H,Q677H mutations have been widely seen previously in C.37 circulating in Peru.

**Earliest sequence:** 02/05/2022
USA/PA-Curative-303253/2022

**Most recent sequence:** 13/06/2022
Peru/ARE-INS-20220/2022

**Countries circulating:**
Peru (13)
USA (4)

**Genomes**
[Genomes.csv](https://github.com/cov-lineages/pango-designation/files/9073196/Genomes.csv)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_84aa_8434d0.json?branchLabel=aa%20mutations&c=gt-S_675

![Captura desde 2022-07-08 10-07-39](https://user-images.githubusercontent.com/89021119/178022517-6c768d1b-45ae-441a-96a8-0e068bb24b75.png)

![Captura desde 2022-07-08 10-18-27](https://user-images.githubusercontent.com/89021119/178022527-981c260f-1152-48e2-9d9a-731b84eef929.png)

**Proposed lineage name**
BG.X

**Comment by OrsonMM** [comment]
15 Genomes in GISAID of possible outbreak from Tacna Peru.  

![image](https://user-images.githubusercontent.com/12600107/178036229-4ac6d472-74ad-409f-8587-8b1eec70de3b.png)

**Comment by OrsonMM** [comment]
Still growing 

![image](https://user-images.githubusercontent.com/12600107/180231610-79f139b5-7871-486f-9aa9-3c3e8fa31590.png)

**Comment by InfrPopGen** [comment]
Thank you @Wen1953 for proposing this. As it has not been showing much growth/advantage recently, I have closed it for now at least.
