### ISSUE TITLE
Proposal for a Sublineage of BA.5.1 with S:P1263Q, 250+ Sequences, 18 Countries

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#835]
**Description**
**Sub-lineage** of: BA.5.1
**Earliest sequence**: 2022-5-10, Portugal (EPI_ISL_12863416)
**Most recent sequence**: 2022-7-4, England (four sequences: EPI_ISL_13733534, EPI_ISL_13733556, EPI_ISL_13733614, EPI_ISL_13733023)
**Countries circulating**: UK (151), Denmark (40), Belgium (14), France (10), Ireland (7), USA (7), Israel (6), Spain (5), Netherlands (4), Sweden (4), Germany (3), Australia (3), Switzerland (2), Portugal (2), Austria (2), Luxembourg (2), Italy (1), Slovakia (1)
**Number of Sequences**: 249 on Usher tree, 264 on GISAID (using search query “Spike_P1263Q, Spike_F486V, -N_P151S”
**Substitutions on top of BA.5.1:**
Spike: P1263Q
Nucleotide: C16428T, C25350A

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_1ae8a_adafe0-P1263Q.json 
The branch on the bottom-left corner is the synonymous nucleotide mutation C16428T, which, as you can see, is not unique to the P1263Q branch. 
![Screen Shot 2022-07-10 at 11 26 03 AM](https://user-images.githubusercontent.com/33738461/178151324-50921a9b-f711-4d65-aaa1-45705e88ab9b.png)

**Evidence**
CovSpectrum: 70% (CI:49%-91%) weekly growth advantage compared to nextcladePangoLineage:BA.5.1* in the last three months in Europe:
https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5.1*&variantQuery1=NextCladePangoLineage%3ABA.5.1*+%26+S%3AP1263Q&analysisMode=CompareToBaseline&

![Screen Shot 2022-07-10 at 11 22 01 AM-EU](https://user-images.githubusercontent.com/33738461/178151180-ff6c14a1-8484-4942-8f54-8fac1f004e4f.png)

Lest you imagine this growth advantage is an artifact of the higher volume of sequencing in the UK, where most sequences have been found so far, below is the corresponding figure for the UK.

CovSpectrum: 74% (CI:35%113%) weekly growth advantage compared to nextcladePangoLineage:BA.5.1* in the last three months in the UK:
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5.1*&variantQuery1=NextCladePangoLineage%3ABA.5.1*+%26+S%3AP1263Q&analysisMode=CompareToBaseline&

![Screen Shot 2022-07-10 at 11 17 57 AM-UK](https://user-images.githubusercontent.com/33738461/178151019-90b593dd-7aae-415a-b0b0-487497b2952c.png)

Several mutations at S:1263 and S:1264 seem to be on the rise lately. I'm not sure what role they play or how they might improve fitness, but they seem somehow to confer a growth advantage. 

**Genomes**
[GISAID_hcov-19_ids_2022_07_10_15_06-BA.5.1+P1263Q.csv](https://github.com/cov-lineages/pango-designation/files/9079327/GISAID_hcov-19_ids_2022_07_10_15_06-BA.5.1%2BP1263Q.csv)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.1.5 with 173 newly designated sequences, and 7 updated designations from BA.5.1. Defining mutation(s) nt:16428T followed by C25350A (S:P1263Q).
