### ISSUE TITLE
Proposal of new sub-lineage of BA.2.12.1 with additional mutations S:E1202Q, ORF1ab:V4266I mainly in peruvian genomes

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#836]
**Proposal of new sub-lineage of BA.2.12.1 with additional mutations S:E1202Q, ORF1ab:V4266I mainly in peruvian genomes by Group of Genomic Surveillance INS-PERU**

**Description**
**Sub-lineage of:** Potential new sub-lineage of BA.2.12.1
**Earliest sequence:** hCoV-19/Peru/LIM-INS-17276/2022 (10/05/2022, Peru)
**Most recent sequence:** hCoV-19/Peru/LIM-INS-20061/2022 (21/06/2022, Peru)

**Countries circulating**
Peru (33), England (1)

Some genomes of new sub lineage carried a reversion in Spike:S408R. This potential BA.2.12.1 is principally distributed in Lima, Peru

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/9086038/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2cf85_c42d00.json?branchLabel=aa%20mutations&c=pango_lineage&label=nuc%20mutations:G13061A&tl=country
![usher_NSP10_V13I](https://user-images.githubusercontent.com/87997149/178315923-d9dd2deb-9677-470b-9c75-3d42e8bbf107.png)

![Peru_NSP10_V13I](https://user-images.githubusercontent.com/87997149/178316007-1701d447-3cd0-46fa-8de6-f492e53c947b.png)

![spectrum1](https://user-images.githubusercontent.com/87997149/178316246-4acc347b-0519-488d-a846-df17794d8ebc.png)
![spectrum2](https://user-images.githubusercontent.com/87997149/178316269-a5683f81-6ff3-4f4b-a209-7018ce35bf17.png)

**Comment by OrsonMM** [comment]
![image](https://user-images.githubusercontent.com/12600107/179524249-c69444af-6c17-4c15-bea1-e74522da0170.png)

**Comment by chrisruis** [comment]
Thanks @LuisBarcenaF We've added this as BG.6 to start on the branch with G13061A (ORF1a:V4266I)
