### ISSUE TITLE
BA.5.2.1 +26151T+28271C+C140T sublineage with S:346T (65 sequences Uk, Israel, Spain)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#837]
Here i want to propose to be monitored this sublineage that popped up recently in England and it is already present in 3 countries:
Uk, Spain and Isreal.

Defining mutations:
C26151T+T28271C
then
C140T
then
S:R346T
![Schermata 2022-07-12 alle 01 36 58](https://user-images.githubusercontent.com/87669813/178376199-92cd67b4-218a-4191-9c20-c2fdf441b306.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20240_caec60.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:G22599C

First sequence: Northern_Ireland/QEUH-3E8297D/2022|2022-06-23
Nr of sequences : 31
List of sequences: 
[contributors (4).csv](https://github.com/cov-lineages/pango-designation/files/9088171/contributors.4.csv)

Covspectrum Overview:
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3A346T&nucMutations=26151T%2C28271C%2CC140T&aaMutations1=S%3A346T&nucMutations1=26151T%2C28271C%2CC140T&

Growth advantage, too soon to say and th CovSpectrum query can be far from real and more:
 it is less than 3 weeks from the first sample but it seems to be quite fast:
https://cov-spectrum.org/explore/World/AllSamples/Past1M/variants?aaMutations=M%3A3N&nucMutations=12160A%2C28330G&aaMutations1=S%3A346T&nucMutations1=26151T%2C28271C%2CC140T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
65 sequences as today now found also in USA:
![Schermata 2022-07-15 alle 14 47 18](https://user-images.githubusercontent.com/87669813/179225888-9dd560e1-7459-4c51-a636-4e9118f3d817.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_b0f7_15c5f0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:G22599C

Growth advantage continues to be important @chrisruis @thomaspeacock @corneliusroemer 
with a very high lower CI , also it could be still just a cluster as we have seen in the past.
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past1M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=S%3A346T&nucMutations1=26151T%2C28271C%2CC140T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Updated query vs NCPL BA.5* baseline:

https://cov-spectrum.org/explore/World/AllSamples/Past1M/variants?variantQuery=NextCladePangoLineage%3ABA.5*&aaMutations1=S%3A346T&nucMutations1=26151T%2C28271C%2CC140T&analysisMode=CompareToBaseline&

Still high but i see the typical down trending trajectory shown usually by clusters, luckily.

**Comment by corneliusroemer** [comment]
Yep, this one is interesting, maybe worth waiting for 1 more week but I suspect it will soon be above 1% in the UK.

First sequenced in CW 25, not long ago.

<img width="2550" alt="image" src="https://user-images.githubusercontent.com/25161793/180659428-d0d3ac28-9382-4002-82df-b0969ae48b94.png">

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5.2.1*+%26+S%3A346T+%26+%21NextcladePangoLineage%3ABF.7+%26+28271C+%26+C26151T+&variantQuery1=S%3A346T+%26+26151T+%26+28271C+%26+C140T+%26+NextCladePangoLineage%3ABA.5*&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.11 with 45 newly designated sequences, and 0 updated designations. Defining mutation G22599C (S:R346T), preceded by (C26151T, T28271C) and C140T.
