### ISSUE TITLE
BA.5.2.1 sublineage with S:Q183L (573 seq. 18+ countries as of 25.07.22)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#838]
Proposal for a sublineage of BA.5.2.1
Earliest sequence: 10.05.2022 (USA)
Countries detected: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/AGA/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/AGA/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Country | n
-- | --
USA | 150
UK | 47
France | 42
Denmark | 22
Germany | 20
Belgium | 14
Israel | 14
Portugal | 7
Austria | 3
Czech Republic | 3
Slovenia | 3
Canada | 2
Ireland | 2
Luxembourg | 2
Netherlands | 2
Italy | 1
Sweden | 1
Switzerland | 1

</body>

</html>

Defining mutation:
C5826T = ORF1a:T1854I
A22110T = S:Q183L

This variant is defined by S:Q183L, and ORF1a:T1854I and was first detected in USA. Now it is present in 18 countries (340 seq on usher as of 12.07.22). It is one of those lineages that carry a S:183 mutation @ryhisner, @FedeGueli (c.f #821).

![grafik](https://user-images.githubusercontent.com/102166254/178430002-999a2c25-b22d-42e7-8a44-6e177c8bd22a.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10892_d16bd0.json?branchLabel=aa%20mutations&c=gt-nuc_5826,22110

![grafik](https://user-images.githubusercontent.com/102166254/178432469-01ba1b81-04ff-4dec-91be-6ac7124037e5.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AQ183L&nucMutations=C5826T&pangoLineage=BA.5*&aaMutations1=S%3AQ183L&nucMutations1=C5826T&pangoLineage1=BA.5*&

EPI_ISL_13176326, EPI_ISL_13176339, EPI_ISL_13176896, EPI_ISL_13183530, EPI_ISL_13229839, EPI_ISL_13229840, EPI_ISL_13229848, EPI_ISL_13229849, EPI_ISL_13238640, EPI_ISL_13254685, EPI_ISL_13257027, EPI_ISL_13283840, EPI_ISL_13284675, EPI_ISL_13285671, EPI_ISL_13297414, EPI_ISL_13297689, EPI_ISL_13297696, EPI_ISL_13301468, EPI_ISL_13301478, EPI_ISL_13314511, EPI_ISL_13324339, EPI_ISL_13324341, EPI_ISL_13342546, EPI_ISL_13344816, EPI_ISL_13345013, EPI_ISL_13345171, EPI_ISL_13345445, EPI_ISL_13346345, EPI_ISL_13346429, EPI_ISL_13346480, EPI_ISL_13346689, EPI_ISL_13355756, EPI_ISL_13355855, EPI_ISL_13357633, EPI_ISL_13358002, EPI_ISL_13365449, EPI_ISL_13366370, EPI_ISL_13369111, EPI_ISL_13369121, EPI_ISL_13370452, EPI_ISL_13370495, EPI_ISL_13371075, EPI_ISL_13371142, EPI_ISL_13372702, EPI_ISL_13372703, EPI_ISL_13372729, EPI_ISL_13372836, EPI_ISL_13373002, EPI_ISL_13373003, EPI_ISL_13380330, EPI_ISL_13380331, EPI_ISL_13380466, EPI_ISL_13380869, EPI_ISL_13381141, EPI_ISL_13381567, EPI_ISL_13382123, EPI_ISL_13382125, EPI_ISL_13385916, EPI_ISL_13386093, EPI_ISL_13387131, EPI_ISL_13387666, EPI_ISL_13387854, EPI_ISL_13388065, EPI_ISL_13400622, EPI_ISL_13400739, EPI_ISL_13401477, EPI_ISL_13402751, EPI_ISL_13402753, EPI_ISL_13407153, EPI_ISL_13413600, EPI_ISL_13419248, EPI_ISL_13420353, EPI_ISL_13426523, EPI_ISL_13426674, EPI_ISL_13426712, EPI_ISL_13426906, EPI_ISL_13427138, EPI_ISL_13427532, EPI_ISL_13427719, EPI_ISL_13428079, EPI_ISL_13428463, EPI_ISL_13428641, EPI_ISL_13429286, EPI_ISL_13429679, EPI_ISL_13430774, EPI_ISL_13432285, EPI_ISL_13435696, EPI_ISL_13443565, EPI_ISL_13444901, EPI_ISL_13445928, EPI_ISL_13446970, EPI_ISL_13463359, EPI_ISL_13465905, EPI_ISL_13470232, EPI_ISL_13483106, EPI_ISL_13483110, EPI_ISL_13483527, EPI_ISL_13491055, EPI_ISL_13492076, EPI_ISL_13493313, EPI_ISL_13499746, EPI_ISL_13499791, EPI_ISL_13499836, EPI_ISL_13500413, EPI_ISL_13502125, EPI_ISL_13509650, EPI_ISL_13518610, EPI_ISL_13519571, EPI_ISL_13532069, EPI_ISL_13534215, EPI_ISL_13535207, EPI_ISL_13535246, EPI_ISL_13541704, EPI_ISL_13567894, EPI_ISL_13569187, EPI_ISL_13569203, EPI_ISL_13570181, EPI_ISL_13572994, EPI_ISL_13573159, EPI_ISL_13573548, EPI_ISL_13573583, EPI_ISL_13574913, EPI_ISL_13577561, EPI_ISL_13579748, EPI_ISL_13580211, EPI_ISL_13580236, EPI_ISL_13580340, EPI_ISL_13580580, EPI_ISL_13580597, EPI_ISL_13585980, EPI_ISL_13590084, EPI_ISL_13590186, EPI_ISL_13590393, EPI_ISL_13590508, EPI_ISL_13604542, EPI_ISL_13604739, EPI_ISL_13606056, EPI_ISL_13608989, EPI_ISL_13618502, EPI_ISL_13619600, EPI_ISL_13620078, EPI_ISL_13620463, EPI_ISL_13621544, EPI_ISL_13621929, EPI_ISL_13622507, EPI_ISL_13622709, EPI_ISL_13624184, EPI_ISL_13625318, EPI_ISL_13625333, EPI_ISL_13625340, EPI_ISL_13625636, EPI_ISL_13625974, EPI_ISL_13632596, EPI_ISL_13638242, EPI_ISL_13644121, EPI_ISL_13658175, EPI_ISL_13658263, EPI_ISL_13658903, EPI_ISL_13662157, EPI_ISL_13665858, EPI_ISL_13666473, EPI_ISL_13667407, EPI_ISL_13692340, EPI_ISL_13694980, EPI_ISL_13695824, EPI_ISL_13698962, EPI_ISL_13699024, EPI_ISL_13699116, EPI_ISL_13699255, EPI_ISL_13699268, EPI_ISL_13700566, EPI_ISL_13700682, EPI_ISL_13701647, EPI_ISL_13702094, EPI_ISL_13717665, EPI_ISL_13719161, EPI_ISL_13719331, EPI_ISL_13720571, EPI_ISL_13720961, EPI_ISL_13721609, EPI_ISL_13721908, EPI_ISL_13722001, EPI_ISL_13722518, EPI_ISL_13723504, EPI_ISL_13724454, EPI_ISL_13725227, EPI_ISL_13726160, EPI_ISL_13728400, EPI_ISL_13728574, EPI_ISL_13728575, EPI_ISL_13728581, EPI_ISL_13728616, EPI_ISL_13730724, EPI_ISL_13730814, EPI_ISL_13732189, EPI_ISL_13758174

**Comment by agamedilab** [comment]
464 seq. on Usher as of 18.07.22.

![grafik](https://user-images.githubusercontent.com/102166254/179479529-40aade3d-b991-4692-89b8-092f7311e169.png)

![grafik](https://user-images.githubusercontent.com/102166254/179479326-ac0354f8-8bb5-4e24-a606-96462d41dbd5.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_175ef_5222d0.json?branchLabel=aa%20mutations&c=gt-nuc_5826,22110&label=nuc%20mutations:C241T,T670G,C1627T,C2790T,C3037T,G4184A,C4321T,T6979G,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,A27038G,C27807T,C27889T,A28271T,C28311T,A28330G,G28881A,G28882A,G28883C,A29510C

![grafik](https://user-images.githubusercontent.com/102166254/179480014-a1195955-5f9a-4990-80a1-29d2b3f95b1d.png)
https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?aaMutations=S%3AQ183L&nucMutations=C5826T&pangoLineage=BA.5*&pangoLineage1=BA.5*&

**Comment by agamedilab** [comment]
573 seq on usher as of 25.07.22.

![grafik](https://user-images.githubusercontent.com/102166254/180772066-e6500e6e-dba6-4cc1-a512-dc2f40aeb36a.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3e196_e843e0.json?branchLabel=aa%20mutations&c=gt-S_183

**Comment by InfrPopGen** [comment]
Thank you for proposing this @agamedilab . As it has not been showing epidemiological significance (growth advantages, expansion, etc), I am closing this for now at least.

**Comment by agamedilab** [comment]
1922 on usher as of 01.10.22 and still lingering around.

![grafik](https://user-images.githubusercontent.com/102166254/193403331-a0ff3509-6f8e-4e93-8b77-f020f32b02ba.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42ed1_809480.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22110T

![grafik](https://user-images.githubusercontent.com/102166254/193403303-96095c4f-a796-4e23-ac76-af4cdd51c981.png)

Worth designating in the spirit of #1134 @corneliusroemer ?
