### ISSUE TITLE
My data was not classified correctly

### ISSUE THREAD

**Issue by afmarti** [cov-lineages/pango-designation#84]
Dear, 

I have one sample with 5 designated-mutation to P. 1.2 lineage but it was classified as P.1. Is the database actualized?

Thanks, 

Andreza

**Comment by chrisruis** [comment]
Hi @afmarti I think this would be better placed as a pangolin issue as its dealing with assignments rather than a new lineage - would you be able to open it again over at https://github.com/cov-lineages/pangolin/issues Thanks!
