### ISSUE TITLE
Proposal to designate BA.2.38 sublineage with S:69/70Del, S:71F, S:478R circulating in India (249 seqs)with a sublineage with S:1264L (99seqs) with a cluster of interest with S:144del + S:446S+452Q (40 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#840]
@chrisruis @InfrPopGen  this goes on from #814 

With this issue i want to propose the BA.2.38 sublineage mentioned already in #814.

This sublineage was first spotted by @zach-hensel and monitored since by the team.

Defining mutations:
BA.2.38 (S:417T)+ NUC: C21622T
then
69/70Del + S:71F
then
S:478R 

This set of mutations is common to 108 sequences on Usher tree and it has been sampled in 16 countries and 4 continents:
![Schermata 2022-07-13 alle 01 22 50](https://user-images.githubusercontent.com/87669813/178614825-9431d9b6-6469-4e35-953b-ba838bdfd3b3.png)

Today @c19850727 highlighted that there is a subset of 16 sequences carrying an additional spike mutation: S:V1264L  that already has been exported to Japan, Usa and Canada (1sequence each):
![Schermata 2022-07-13 alle 01 26 01](https://user-images.githubusercontent.com/87669813/178615101-ade67b3f-2ffc-46d5-a079-e0a5152cb2c4.png)

And tonight i found two sequences of this subset with S:1264L carrying two potential mutations of interest : **S:144Del** **_(EDITED: , spptted just today 29/7)_** S:446S and S:452Q beyond Orf1a:A3357G, ORF1a:F1214I and NUC:C18744T
![Schermata 2022-07-13 alle 01 28 58](https://user-images.githubusercontent.com/87669813/178615343-34231096-51d9-4661-8ec0-744f7cc6cbbe.png)

This last small but potentially concerning clade pushed me to re propose this lineage already discussed in #814 with @chrisruis .

Here Covspectrum (where we can see only 58 sequences due to Gisaid delayed data): 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3A478R%2CS%3A71F&aaMutations1=ORF1a%3A556K%2CN%3AP364L%2CORF1a%3AD930N%2CORF1a%3AP3504L%2CN%3A136&nucMutations1=A11782G%2C12160A&

This lineage doesnt show any growth advantage over BA.5 but i will expect more sequences to be uploaded soon to understand the trend

**Comment by FedeGueli** [comment]
119 sequences as today

**Comment by FedeGueli** [comment]
Hi @chrisruis 

This is now showing a 51% growth advantage vs BA.5 in India: 
https://cov-spectrum.org/explore/India/AllSamples/Past2M/variants?aaMutations=M%3A3N&nucMutations=12160A&aaMutations1=S%3A417T%2CS%3A71F%2CS%3A478R&analysisMode=CompareToBaseline&

cc @AngieHinrichs @corneliusroemer @InfrPopGen

**Comment by silcn** [comment]
5 more sequences on @FedeGueli's G446S+L452Q branch turned up today from Maharashtra.

**Comment by FedeGueli** [comment]
thx @silcn ! 137 seqs as today

**Comment by FedeGueli** [comment]
Query updated to NextcladePangoLineage:BA.5* as baseline : +28%

https://cov-spectrum.org/explore/India/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.5*&aaMutations1=S%3A417T%2CS%3A71F%2CS%3A478R&analysisMode=CompareToBaseline&

@corneliusroemer @chrisruis

**Comment by FedeGueli** [comment]
As described by me in #814 
i want to highlight here too that a sublineage of this sublineage defined by S:V1264L reached 48 sequences and it is showing growth advantage versus BA.2.75 baseline in India:
+25% (CIs -23% - +74% )
![Schermata 2022-07-23 alle 10 49 23](https://user-images.githubusercontent.com/87669813/180597893-e2978d4d-96ef-415c-a05a-1fde898306a5.png)
https://cov-spectrum.org/explore/India/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.2.75*&aaMutations1=S%3A417T%2CS%3A71F%2CS%3A478R%2CS%3A1264L&analysisMode=CompareToBaseline&

Although very preliminary and not solid CIs the fact that within the same sublineage with S:1264L there is a clade with S:452Q and S:446S suggests to put this variant under monitoring and to designate the wider parental lineage and its sublineage with S:1264L in my view.

@chrisruis @corneliusroemer @InfrPopGen

**Comment by FedeGueli** [comment]
The cluster of interest within this sublineage carrying beyond S:1264L further two spike mutations (S:452Q +S:446S )
and two further  Orf1ab mutations(Orf1a:3357G + Orf1a:1214I)
grew now at 13 sequences and it has been sampled in WA, USA for the first time.
![Schermata 2022-07-28 alle 16 11 37](https://user-images.githubusercontent.com/87669813/181527497-a727e4ff-a0d4-4153-a8bd-44950095bccb.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e875_295340.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G25352T


I urge very much @chrisruis @InfrPopGen @corneliusroemer to designate the parental lineage as BA.2.38.X starting with 478R or with S:1264L if that mutation could better correspond with the trespassing the BA.2.75 growth rate and then to put under close watch the sub-sublineage with the double RBM mutation 446+452.

**Comment by FedeGueli** [comment]
15 (16 likely due one missing just 446S) sequences as today.
First european sample from Poland and one more from USA Ohio.
![Schermata 2022-07-30 alle 00 08 34](https://user-images.githubusercontent.com/87669813/181851216-46a2401f-0fcf-4552-9baa-8181ec1188f8.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9ab8_457700.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C10335G

This is exactly what we could expect from high trasmissible lineages.

Thx to the very early spot by @zach-hensel we were able to see step by step stepwise evolution of this sublineage:
with its initial S: 69/70del 71F + 478R it was competing with BA.5 in India.
After acquiring  S:1264L it overtook BA.5 and started to compete vs BA.2.75.
with the last RBM combo 446S/452Q plus the S:144del (that i just spotted)  now it is well ahead the initial Growth rate of BA.2.75 and it is competing with all the clusters i am monitoring globally (mostly  BA.5.2.1 sublineages with 1 NTD mutation or  Spike_346 mutated or BA.4+346)

@corneliusroemer @chrisruis @InfrPopGen @AngieHinrichs I ask again for a fast designation of this sublineage and its sublineages and sub sublineages as exposed above in previous posts

**Comment by FedeGueli** [comment]
Big jump for the cluster of interest ( within the 1264L branch of this sublineage with 144del, 446S and 452Q that reached 21 sequences plus two more of that with 452Q but not 446S .

The parental linege here proposed reached 216 Sequences and its main sublineage defined by S:1264L counts 70seqs.

All of them are exhibiting growth advantage versus BA.5 baseline and if for the cluster of interest that is very premature given the small numbers for the main lineage with S:478R is very solid. 
One thing that makes me thing that the growth advantage that usually goes down after the Cluster/introduction/founder phase in this case is going up day by day.

I again have to request a rapid designation of this sublineage and its cluster of interest , cause it is highly probable that it would be in the clash with BA.2.75 and BA.5.2* in the next weeks.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4964_6f6fc0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C10335G
![Schermata 2022-07-31 alle 23 59 34](https://user-images.githubusercontent.com/87669813/182046994-cea03227-1275-41e5-89c5-85bb4deee550.png)


Here the various comparisons against BA.2.75: 
Cluster of interest within S:1264Lsublineage
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?variantQuery=NextcladePangoLineage%3ABA.2.75*&aaMutations1=S%3A478R%2CS%3A71F%2CS%3A1264L%2Corf1a%3A3357G&analysisMode=CompareToBaseline&

Sublineage with S:1264L:
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?variantQuery=NextcladePangoLineage%3ABA.2.75*&aaMutations1=S%3A478R%2CS%3A71F%2CS%3A1264L&analysisMode=CompareToBaseline&

Main lineage starting with S:478R
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?variantQuery=NextcladePangoLineage%3ABA.2.75*&aaMutations1=S%3A478R%2CS%3A71F&analysisMode=CompareToBaseline&


@corneliusroemer

**Comment by zach-hensel** [comment]
There is an additional USA sequence, EPI_ISL_14192172, today with L452Q (now one each in Washington, Ohio and Pennsylvania) and two new sequences sampled in two Indian states for I believe the first time, EPI_ISL_14196530 (Assam) and EPI_ISL_14196563 (Telangana).

The new sequences are all missing C18744T present in almost all Maharashtra sequences which might make emergence of this sublineage a bit more clear with the first sample being from outside Maharastra and lacking this mutation. This also might indicate multiple introductions to the USA.

**Comment by FedeGueli** [comment]
Thx @zach-hensel for your update.

Here the covspectrum query (that actually finds just 16 sequences) :https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A478R%2CS%3A71F%2CS%3A1264L%2Corf1a%3A3357G&aaMutations1=ORF1a%3A556K%2CN%3AP364L%2CORF1a%3AD930N%2CORF1a%3AP3504L%2CN%3A136&nucMutations1=A11782G%2C12160A&

After Zach suggestion, filtering for just high quality sequences i found that every seqs (5) with orf1a:3357G has also S:446S and S:452Q , my guess is that they are present in all or most of sequences defined by S:1264L + orf1a:3357G

**Comment by FedeGueli** [comment]
As today we count:
233 seqs of the main S:478R lineage
83 seqs out of 233 have S:1264L
25 (likely 28) seqs out of 83 have the S:446S +S:452Q combo 

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9d2d_a45e70.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C10335G

**Comment by FedeGueli** [comment]
2 more sequences of the cluster of interest with 144del, 446S and 452Q popped up today one of the two newly sampled is again from Poland and not clustering to the previous one. 

Bringing the counts to 235 for the main lineage, 85 for the branch with S:1264L and 27 (30) for its cluster of interest

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_159cf_c4a080.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:T3905A,T22917A

**Comment by FedeGueli** [comment]
@chrisruis @InfrPopGen @corneliusroemer i have missed that cause we are monitoring it since it was just two sequences i havent added any sequence list
So i have selected 11 good quality sequences as list for the designation of the cluster of interest, with all the defining mutations:
S:69/70del S:71F S:144del  S:446S S:452Q S:478R S:1264L plus Orf1a:3357G


EPI_ISL_13611347
EPI_ISL_13611344
EPI_ISL_14053646
EPI_ISL_14080728
EPI_ISL_14098933
EPI_ISL_14154136
EPI_ISL_14154135
EPI_ISL_14154164
EPI_ISL_14154141
EPI_ISL_14192172
EPI_ISL_14196563


At this point probably it could make sense to designate just the cluster of interest, today i found a new query and its growth advantage now is something to watch closely both vs BA.5 and BA.2.75:
<google-sheets-html-origin><style type="text/css"></style>

Lineages | Query x Growth adv | Gr.Adv vs BA.2.75 | Query x Growth adv | Week Growth Adv vs.BA.5 | Query for sequences | Nr of Seqs
-- | -- | -- | -- | -- | -- | --
BA.2.38+S:417T+C21622T+S:69/70del, S:S71F, S:T478R +S:1264L+S:452Q +S:446S+orf1a:3357G + Orf1a:1214I | https://cov-spectrum.org/explore/India/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.2.75*&aaMutations1=S%3A478R%2CS%3A1264L%2CS%3A452Q&analysisMode=CompareToBaseline& | 34% | https://cov-spectrum.org/explore/India/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.5*&aaMutations1=S%3A478R%2CS%3A1264L%2CS%3A452Q&analysisMode=CompareToBaseline& | 96% | https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A478R%2CS%3A1264L%2CS%3A452Q&aaMutations1=ORF1a%3A556K%2CN%3AP364L%2CORF1a%3AD930N%2CORF1a%3AP3504L%2CN%3A136&nucMutations1=A11782G%2C12160A& | 24

**Comment by ryhisner** [comment]
There were 15 sequences with S:T478R and S:V1264L uploaded today, 14 from Maharashtra, India, and one from Texas, USA. Two of these lack S:Y144del and ORF1a:A3357G and are likely not related. The other 13 sequences all have S:Y144del and ORF1a:A3357G. Seven of these 13 have S:G446S and S:L452Q. NextClade shows that the other six have no coverage in that area, so it seems nearly certain they also possess G446s & L452Q. Collection dates range from June 30 to July 11 for the Maharashtra sequences while the Texas sequence was collected July 15. 

![image](https://user-images.githubusercontent.com/33738461/183223471-2367c189-543a-4589-ba46-2e7913dd9ffa.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_433a_da4cc0.json?branchLabel=aa%20mutations&c=pango_lineage&label=nuc%20mutations:C10335G

EPI_ISL_14260722, EPI_ISL_14260728, EPI_ISL_14260757,
EPI_ISL_14260779, EPI_ISL_14260792, EPI_ISL_14260796,
EPI_ISL_14260802, EPI_ISL_14260871, EPI_ISL_14260876,
EPI_ISL_14260881, EPI_ISL_14260908, EPI_ISL_14260944,
EPI_ISL_14268007

**Comment by FedeGueli** [comment]
Thx so much @ryhisner big jump today for the cluster but also fore the parental lineage.
As in you tree new counts are:
Parental with spike & 69/70del 478R : 249
Sublineage with 1264L :99
Cluster with 452Q and 446S: 40 (43)

It is very fast. I hope this new upload will move the committee toward a fast designation of this one as happened with BA.2.75, they both have in common the fact to have 8 spike mutations/dels each and to be the fastest when discovered,

@thomasppeacock @corneliusroemer @InfrPopGen @chrisruis @AngieHinrichs

**Comment by InfrPopGen** [comment]
Thanks @FedeGueli  for submitting. We've added lineage BA.2.38.3 with 27 newly designated sequences, and 0 updated designations. Defining mutation(s) G25352T (S:V1264L).
If you want to propose the sublineage(s), please could you open a new issue (proposing BA.2.38.3.1) for the next sublineage(s) with S:452Q and S:446S; this will help with matching milestones to issues and proposers, and other record keeping. Thank you!

**Comment by FedeGueli** [comment]
Thx i 'll do it for sure. i m sorry that this issue was so confusing but literally that sublineage has born while i was proposing it!
Thank you for your work.

**Comment by silcn** [comment]
@InfrPopGen any particular reason why this has been designated starting from S:1264L rather than the larger branch starting at S:478R?

**Comment by FedeGueli** [comment]
@silcn i think that the acquisition of S:1264L mutation corresponds at when it started to be competitive with BA.5 and BA.2.75 mainly due the boost given by the sublineage of interest 446+452.
It makes sense looking at the increasing share of 1264L out of total 478R
