### ISSUE TITLE
BA.5.2.1 sublineage with S:N450D, ORF1b:H1087Y (178 seq. as of 08.08.22; mostly Austria, expansion into Denmark, Iceland, Belgium, Czech Republic )

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#843]
Proposal for a sublineage of BA.5.2.1
Earliest sequence: 20.06.2022 (Austria)
Countries detected: Austria

Defining mutation:
C16726T = ORF1b:H1087Y
A22910G = S:N450D

This variant is defined by S:N450D, and ORF1b:H1087Y and was only detected in Austria so far. 
S:N450D is also known from recently emerged BA.2 sublineages (cf. #772, #812, #814). 

![grafik](https://user-images.githubusercontent.com/102166254/179030659-bca5437e-d228-4ca7-a90c-01bac01f5c57.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_421aa_3da60.json?branchLabel=aa%20mutations&c=gt-S_450&label=nuc%20mutations:C241T,T670G,C1627T,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C16726T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,A27038G,C27807T,C27889T,A28271T,C28311T,A28330G,G28881A,G28882A,G28883C,A29510C

![grafik](https://user-images.githubusercontent.com/102166254/179031119-ec5f8d99-d6d7-4c6e-90f3-6f3b2d7c0a49.png)

Too few seqs. on covspectrum yet to effectively query:
https://cov-spectrum.org/explore/Europe/AllSamples/Past6M/variants?aaMutations=S%3AN450D&nucMutations=C16726T&pangoLineage=BA.5*&aaMutations1=S%3AN450D&nucMutations1=C16726T&pangoLineage1=BA.5*&

EPI_ISL_13490397, EPI_ISL_13826225, EPI_ISL_13826205, EPI_ISL_13826220, EPI_ISL_13826101, EPI_ISL_13826110, EPI_ISL_13826077, EPI_ISL_13826076, EPI_ISL_13825939, EPI_ISL_13826093, EPI_ISL_13826203, EPI_ISL_13826202, EPI_ISL_13826167, EPI_ISL_13825901, EPI_ISL_13825910, EPI_ISL_13633061, EPI_ISL_13633083, EPI_ISL_13826165, EPI_ISL_13826211, EPI_ISL_13825911, EPI_ISL_13826082, EPI_ISL_13825902, EPI_ISL_13825903, EPI_ISL_13826168, EPI_ISL_13826186, EPI_ISL_13826242, EPI_ISL_13826103, EPI_ISL_13633072, EPI_ISL_13826115, EPI_ISL_13826214, EPI_ISL_13826221, EPI_ISL_13825902, EPI_ISL_13490411, EPI_ISL_13826055, EPI_ISL_13825938, EPI_ISL_13826107, EPI_ISL_13826241, EPI_ISL_13633090, EPI_ISL_13826080, EPI_ISL_13490388, EPI_ISL_13490404, EPI_ISL_13490402, EPI_ISL_13490376, EPI_ISL_13490414, EPI_ISL_13490366, EPI_ISL_13633066, EPI_ISL_13633054, EPI_ISL_13633050, EPI_ISL_13826176, EPI_ISL_13633034, EPI_ISL_13633079, EPI_ISL_13633065, EPI_ISL_13633069, EPI_ISL_13826097, EPI_ISL_13826085, EPI_ISL_13826177, EPI_ISL_13825909, EPI_ISL_13826208, EPI_ISL_13826108, EPI_ISL_13825935, EPI_ISL_13633073, EPI_ISL_13825914, EPI_ISL_13826219

**Comment by agamedilab** [comment]
62 all Austrian seq on Usher as of 18.7.2022.

![grafik](https://user-images.githubusercontent.com/102166254/179476796-27d57950-3b35-45d9-a95f-e7828e984b84.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10f8d_5000d0.json?branchLabel=aa%20mutations&c=gt-S_450&label=nuc%20mutations:A22910G

![grafik](https://user-images.githubusercontent.com/102166254/179476926-c4a83398-7449-46e9-b699-5bde9d746ba2.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AN450D&nucMutations=C16726T&pangoLineage=BA.5*&aaMutations1=S%3AN450D&nucMutations1=C16726T&pangoLineage1=BA.5*&

**Comment by agamedilab** [comment]
Growth advantage vs. BA.5 in Austria 3 months:

![grafik](https://user-images.githubusercontent.com/102166254/180605686-dc76060c-42c7-4868-a336-0d931ea130cb.png)

https://cov-spectrum.org/explore/Austria/AllSamples/Past3M/variants?pangoLineage=BA.5*&aaMutations1=S%3AN450D&nucMutations1=C16726T&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

**Comment by corneliusroemer** [comment]
I think this one would be good to be designated.

It's got an interesting Spike mutation and the growth is interesting.

The only issue is that the S:450D branch has only been sequenced by one lab in Austria. So maybe we should wait for a few more sequences from another lab.

**Comment by agamedilab** [comment]
There are few unassigned partial (Spike only) sequences from Austria (June/July) sequenced by an other lab (IMBA) that could potentially belong to this lineage (carrying S:N450D, but lacking S:Q954H, S:N969K:

![grafik](https://user-images.githubusercontent.com/102166254/180633757-436f269a-4816-47fa-b9da-5ca15135f1b7.png)

EPI_ISL_13448430, EPI_ISL_13448434, EPI_ISL_13448610,
EPI_ISL_13752524, EPI_ISL_13752528, EPI_ISL_13752931,
EPI_ISL_13753500, EPI_ISL_13754520, EPI_ISL_13851099,
EPI_ISL_13851112, EPI_ISL_13851234, EPI_ISL_13851339,
EPI_ISL_13852752, EPI_ISL_13852879

**Comment by corneliusroemer** [comment]
Seems to be found in Vienna only so far, I still think this has a high chance of growing but it'd be good to see it picked up in a few other countries to get the defining mutations right.

For example, there are BA.5.2.1* in Germany and Denmark with S:450D but lacking the ORF1b mutation. So it may be best to designate without it if it turns out there's circulation.

**Comment by agamedilab** [comment]
upload from a different lab in Salzburg today (EPI_ISL_14027995):

![grafik](https://user-images.githubusercontent.com/102166254/180796331-d037891c-4e7c-4115-9cfe-e6b0e4699bf0.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3e5db_ea24e0.json?branchLabel=Spike%20mutations&c=pango_lineage&label=nuc%20mutations:A22910G

**Comment by agamedilab** [comment]
@@UlrichElling many thanks for your response in #752. I copied it because it is also of potential releavance to this issue. 


![grafik](https://user-images.githubusercontent.com/102166254/181224313-764c0180-2873-49d1-bec7-7eb59dd8713a.png)

IMBA covers the spike region until aa839. Several of the IMBA "spike only" sequences share the S:N450D mutation and are virtually identical to (the spike) of the proposed sublineage but lack S:Q954H, S:N969K. 



However for some reason nextclade does not indicate that IMBA "spike only" sequences end at c. 24079 (before the S:Q954H, S:N969K at 24424, 24469). Anyway the lack of S:Q954H, S:N969K is apparently artificial

![grafik](https://user-images.githubusercontent.com/102166254/181228090-ae9491a3-2084-4b49-991a-5ffc4af33cb7.png)

![grafik](https://user-images.githubusercontent.com/102166254/181227870-eaaac3a3-2319-4da8-8a27-51f1240e24f5.png)

Here is a updated list of 28 IMBA "spike only" sequences potentially beloning to the proposed sublineage (Vienna and five more provinces):

EPI_ISL_13448430, EPI_ISL_13448434, EPI_ISL_13448610,
EPI_ISL_13752524, EPI_ISL_13752528, EPI_ISL_13752931,
EPI_ISL_13753500, EPI_ISL_13754520, EPI_ISL_13851099,
EPI_ISL_13851112, EPI_ISL_13851234, EPI_ISL_13851339,
EPI_ISL_13852752, EPI_ISL_13852879, EPI_ISL_14013212,
EPI_ISL_14013320, EPI_ISL_14013454, EPI_ISL_14013479,
EPI_ISL_14013542, EPI_ISL_14013628, EPI_ISL_14013976,
EPI_ISL_14014068, EPI_ISL_14014081, EPI_ISL_14014223,
EPI_ISL_14014271, EPI_ISL_14014336, EPI_ISL_14014598,
EPI_ISL_14014703

**Comment by agamedilab** [comment]
134 seq. according to Usher as of 01.08.22. Most sequences are from Austria but also expansion into Denmark (EPI_ISL_14091059) and Iceland (EPI_ISL_14064806).

![grafik](https://user-images.githubusercontent.com/102166254/182085581-b0c1876c-b03e-4a88-8a65-54a29f05fbb0.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_575f_76c960.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A22910G

Growth advantage vs. BA,5 Europe 3 months:
![grafik](https://user-images.githubusercontent.com/102166254/182085291-b7d59dbc-4796-4232-b8f2-c4b2cd38978f.png)
https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?pangoLineage=BA.5*&aaMutations1=S%3AN450D&nucMutations1=C16726T&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

**Comment by UlrichElling** [comment]
Please be careful with the Austrian data from LB. They are from a private lab and selected based on PCR results, not random sampling. Within the random surveillance we do see N450D growing, but currently it is at about 15 cases/2.5k sequences per week.

**Comment by agamedilab** [comment]
178 seq. as of 08.08.22.

Growth advantage vs. BA.5 Europe 6 months:

![image](https://user-images.githubusercontent.com/102166254/183358892-e1c019c2-549c-4c46-a4c6-40c841d1c1f6.png)
![image](https://user-images.githubusercontent.com/102166254/183358967-4d8f4d73-fe9d-4dbd-bafe-a48d89911d09.png)
https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?pangoLineage=BA.5*&aaMutations1=S%3AN450D&nucMutations1=C16726T&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

![image](https://user-images.githubusercontent.com/102166254/183358423-52e2fd29-df8e-46b8-b973-6e5a9c776de3.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1901_b3510.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A22910G

**Comment by aq-sun** [comment]
Thank you @agamedilab, we have designated this as BF.13, with 150 newly designated sequences, and 24 updated designation from BA.5.2.1. Defining mutations: C16726T (ORF1b:H1087Y) and A22910G (S:N450D).

**Comment by InfrPopGen** [comment]
I am reopening this, at the moment this issue is not officially designated  (as BF.13 has already been fully designated).

**Comment by aq-sun** [comment]
Updated to BF.14, defining mutations: C16726T (ORF1b:H1087Y) and A22910G (S:N450D)
