### ISSUE TITLE
Resurgent BA.1.1.15 in Kazakhstan?

### ISSUE THREAD

**Issue by MCB6** [cov-lineages/pango-designation#846]
a new upload from the capital of Kazakhstan has a high number of sequences identified as BA.1.1.15. It actually overtakes BA.5 there. At a quick glance, they do have BA.1-specific mutations, and no BA.2/5-specific ones. The sequences have gaps. Not sure what is the deal if this comeback of BA.1 is for real...
![image](https://user-images.githubusercontent.com/93294184/179235332-2a8ad22b-18ee-4e98-8360-c7e08451c75c.png)

**Comment by silcn** [comment]
As far as I can tell, the "high number of sequences" is 6. Of these, 5 appear to be identical (including NNNs!) to separate German sequences from March-April 2022. Draw whatever conclusions that you wish to draw, but seems pretty clear this not a real resurgence.

**Comment by InfrPopGen** [comment]
Thank you for proposing. As this lineage has not shown signs of further or sustained growth advantage or epidemiological significance over the past month, it is being closed for now. Should the lineage show signs of significant growth in the future, then please reopen for reconsideration.
