### ISSUE TITLE
Potential sublinage BA.5.1 plus mutations nsp2_S122F, nsp3_T1072I and nsp12_L614F

### ISSUE THREAD

**Issue by VirologiaHUCA** [cov-lineages/pango-designation#848]
Description
Sub-lineage of: BA.5.1
Earliest sequence: 2022-05-22
Most recent sequence: 2022-07-06
Countries circulating: Spain(6 Asturias),

<written description of the proposed lineage, where it is circulating, when, and why it is distinct>
Asturias clade with mutation nsp2_S122F, which acquire mutations nsp3_T1072I and nsp12_L614F
Genomes

<list of genome names as found on GISAID or accession ids - provide as a CSV/TSV table attachment - include locations and dates of sampling>
EPI_ISL_12958934
EPI_ISL_13209269
EPI_ISL_13209277
EPI_ISL_13408134
EPI_ISL_13489841
EPI_ISL_13622933
![SUBGRUPOba5_1](https://user-images.githubusercontent.com/105294581/179522188-27518e50-4c8d-4b37-ad37-9fecc911576f.gif)

**Comment by InfrPopGen** [comment]
Thank you for proposing. Since the date of this proposal, the number of genomes detected worldwide with the above variant profile, has shown very little growth. Consequently, this proposal is being closed for now.
