### ISSUE TITLE
Proposal of two new lineages from B.1.1 that seem to rapidly increase in frequency in Russia

### ISSUE THREAD

**Issue by GalkaKlink** [cov-lineages/pango-designation#85]
# Proposal of two new lineages from B.1.1 that rapidly increase in frequency in Russia
### LINEAGE1:
Sub lineage of B.1.1 (nine of 14 samples are currently classified by PANGOLIN as B.1.1.74, four as B.1.1, and one as B.1.1.354)
Earliest sequence: 2021-02-12 (Russia)
Most recent sequence: 2021-03-30 (Switzerland)
Countries circulating: Russia (20 samples), Switzerland (2 samples)
Key mutations: nsp6:del106-108, S:del140-142, 
Other mutations: nsp2:L113F, nsp3:A534V, nsp4:Y487Y, S:P9L, S:D614G , S:A626A , S:T859N, N:A152S, N:R203K , N:G204R, ORF3a:H93H, ORF8:I9I
21 of 22 sequences also have mutations nsp3:P822L and RdRp:P323L, with these positions being uncovered in the remaining sample.
18 samples carry S:N439K mutation, with this position being uncovered in the remaining four samples.

### LINEAGE2:
Sub lineage of B.1.1
Earliest sequence: 2020-11-14
Most recent sequence: 2021-04-03
Countries circulating: Russia, Turkey, USA, Denmark, Belgium, Sweden
Key mutations: nsp6:del106-108 (39 samples, and the remaining one is uncovered in this region ), S:E484K (36 samples, and the remaining four are uncovered in this region )
Other mutations: nsp3:F106F, RdRp:P323L, S:D614G, N:R203K, N:G204R, N:G215C
Moreover, 39 of 40 samples have S:H655Y mutation; 38 of 40 samples have S:del144 (with these positions being uncovered in one of the two remaining samples).
Unlike B.1.1.318, LINEAGE2 does not have mutations S:T95I, S:P681H, S:D796H. 
### LINEAGE1: 
Russia/SPE-RII-26830S/2021|EPI_ISL_1372295|2021-02-17
Russia/SPE-RII-MH14675S/2021|EPI_ISL_1491618|2021-02-14
Russia/LEN-RII-MH15665S/2021|EPI_ISL_1652552|2021-03-15
Russia/SPE-RII-MH15669S/2021|EPI_ISL_1652556|2021-03-09
Russia/SPE-RII-MH15681S/2021|EPI_ISL_1652567|2021-03-12
Russia/SPE-RII-MH15711S/2021|EPI_ISL_1652593|2021-03-09
Russia/SPE-RII-MH15783S/2021|EPI_ISL_1652649|2021-03-20
Russia/SPE-RII-MH14720S/2021|EPI_ISL_1664636|2021-02-21
Russia/SPE-RII-MH14743S/2021|EPI_ISL_1664657|2021-02-13
Russia/SPE-RII-MH14771S/2021|EPI_ISL_1664681|2021-02-17
Russia/SPE-RII-MH14797S/2021|EPI_ISL_1664702|2021-02-17
Russia/SPE-RII-MH14825S/2021|EPI_ISL_1664724|2021-02-17
Russia/SPE-RII-MH14846S/2021|EPI_ISL_1664737|2021-02-12
Russia/MOW-RII-MH16129S/2021|EPI_ISL_1919507|2021-03-02
Russia/MOW-RII-MH16147S/2021|EPI_ISL_1919518|2021-02-28
Russia/ORE-RII-MH16123S/2021|EPI_ISL_1919501|2021-02-27
Russia/VOR-RII-MH16190S/2021|EPI_ISL_1919540|2021-02-25
Russia/SPE-RII-MH15453S/2021|EPI_ISL_1919434|2021-03-11
Russia/ORE-RII-MH16166S/2021|EPI_ISL_1919528|2021-04-03
Russia/TA-2KFU_COV_5/2020|EPI_ISL_1859681|2020-11-14
Switzerland/VS-33640834/2021|EPI_ISL_1448692|2021-03-21
Switzerland/VS-33737146/2021|EPI_ISL_1533410|2021-03-30
### LINEAGE2: 
USA/NY-CUIMC-NP-5452/2021|EPI_ISL_1500623|2021-02
USA/FL-CDC-FG-023400/2021|EPI_ISL_2037727|2021-04-07
Russia/IVA-CRIE-L188N0203u/2021|EPI_ISL_2038923|2021-04-19
USA/NY-CUIMC-NP-5483/2021|EPI_ISL_1500625|2021-02
USA/NY-PRL-2021_02_24_00J07/2021|EPI_ISL_1098464|2021-02-20
Belgium/UGent-4764/2021|EPI_ISL_1689700|2021-03-26
USA/NY-Wadsworth-21026084-01/2021|EPI_ISL_1623992|2021-01-19
Germany/un-RKI-I-100406/2021|EPI_ISL_1846128|2021-04-05
Sweden/461847154048/2021|EPI_ISL_1607711|2021-03-18
Denmark/DCGC-85973/2021|EPI_ISL_1895294|2021-04-12
Turkey/HSGM-11334/2021|EPI_ISL_1911783|2021-03-10
Russia/PSK-RII-MH14686S/2021|EPI_ISL_1491626|2021-02-17
Russia/SPE-RII-MH14610S/2021|EPI_ISL_1491622|2021-02-14
Russia/SPE-RII-MH14633S/2021|EPI_ISL_1491623|2021-02-14
Russia/SPE-RII-MH14651S/2021|EPI_ISL_1491624|2021-02-15
Russia/SPE-RII-MH14669S/2021|EPI_ISL_1491625|2021-02-20
Russia/SPE-RII-MH14359S/2021|EPI_ISL_1372380|2021-01-05
Russia/SPE-RII-MH15678S/2021|EPI_ISL_1652564|2021-03-09
Russia/SPE-RII-MH15680S/2021|EPI_ISL_1652566|2021-03-09
Russia/SPE-RII-MH15686S/2021|EPI_ISL_1652572|2021-03-09
Russia/SPE-RII-MH15784S/2021|EPI_ISL_1652650|2021-03-15
Russia/ORL-RII-MH15809S/2021|EPI_ISL_1652662|2021-03-09
Russia/SVE-RII-MH15894S/2021|EPI_ISL_1652685|2021-02-27
Russia/BRY-RII-MH15914S/2021|EPI_ISL_1652686|2021-03-28
Russia/SPE-RII-MH14824S/2021|EPI_ISL_1664723|2021-02-21
Russia/MOW-RII-MH16073S/2021|EPI_ISL_1919466|2021-03-02
Russia/ORL-RII-MH16111S/2021|EPI_ISL_1919494|2021-02-24
Russia/VOR-RII-MH16113S/2021|EPI_ISL_1919495|2021-02-25
Russia/KRS-RII-MH16174S/2021|EPI_ISL_1919533|2021-02-24
Russia/ORL-RII-MH16175S/2021|EPI_ISL_1919534|2021-02-24
Russia/MOW-RII-MH16207S/2021|EPI_ISL_1919546|2021-02-25
Russia/KLU-RII-MH16223S/2021|EPI_ISL_1919555|2021-02-24
Russia/MOW-PMVL-47/2021|EPI_ISL_1710865|2021-02-18
Russia/SPE-RII-MH15437S/2021|EPI_ISL_1919424|2021-03-12
Russia/SPE-RII-MH15460S/2021|EPI_ISL_1919440|2021-03-11
Russia/KRS-RII-MH16151S/2021|EPI_ISL_1919519|2021-03-08
Russia/MOS-RII-MH16037S/2021|EPI_ISL_1919445|2021-03-19
Russia/MOS-RII-MH16056S/2021|EPI_ISL_1919455|2021-03-23
USA/NY-Wadsworth-21015426-01/2021|EPI_ISL_1016324|2021-01-15
USA/NY-PRL-2021_02_26_01E18/2021|EPI_ISL_1172298|2021-02-24
## Evidence
1)	These two lineages are monophyletic: 
a)	20 russian (colored in red) and 2 non-russian (colored in blue) samples from supposed LINEAGE1 form a clade on UShER (https://genome.ucsc.edu/cgi-bin/hgPhyloPlace) phylogenetic tree (tree of 1625443 genomes generated 2021-05-13). Among samples colored in black, one is an outgroup (Russia/TA-KFU_35/2020|EPI_ISL_1859633|2020-07-24), and the other one (hCoV-19/England/PHEC-304528/2021|21-03-29) is absent in our dataset.
![image](https://user-images.githubusercontent.com/76441213/119514777-f9890400-bd7d-11eb-9cc3-a0909032b8fa.png) 

b)	On the same tree, 40 samples from supposed LINEAGE2, among each 30 are russian (colored in red) and 10 are non-russian (colored in blue) samples form a clade. Samples that are colored in black are absent in our data or belong to an outgroup clade.
![image](https://user-images.githubusercontent.com/76441213/119514672-e37b4380-bd7d-11eb-8be3-2a85f2d5431b.png)

2)	Both lineages seem to rapidly increase their frequencies in Russia (B.1.1.v1 and B.1.1.v2 in https://virological.org/t/spread-of-endemic-sars-cov-2-lineages-in-russia/689)
3)	Both lineages have samples from more than one country, indicating between-country transmission

**Comment by AngieHinrichs** [comment]
Hi @GalkaKlink.   I'm curious about what you mean by "Other sequences (colored in black) from this branch were absent in our dataset."  -- Does that mean that you do not have the sequences, or that for some other reason you don't consider them to belong to your proposed lineages?

Also, in your list for lineage 2, Russia/MOW-RII-MH15907/2021 seems to have a different set of mutations from the others (AA changes: N: R203K, G204R; ORF1ab: T1001I, A1708D, I2230T, P4715L; ORF8: Q27; S: E484K, S494P, D614G, P681H, T716I, S982A, while the other lineage 2 sequences have in common N: R203K, G204R, G215C; ORF1ab: P4715L, D5429A; S: E484K, D614G, H655Y)

**Comment by GalkaKlink** [comment]
Hello @AngieHinrichs, 
sorry for my misunderstanding of the concept. I updated the proposal now.

**Comment by GBazykin** [comment]
To follow up on this, both these lineages seem to have been spreading in Russia at elevated rate (reproductive number ~1.3) over this period, accoding to a birth-death model.

**Comment by chrisruis** [comment]
Thanks @GalkaKlink and @GBazykin for submitting this. We've added your LINEAGE1 as B.1.1.524 and your LINEAGE2 as B.1.1.525 in [v1.2.16](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.16)
