### ISSUE TITLE
Highly divergent BA.1.1 sublineage circulating in Brazil (5 seq)

### ISSUE THREAD

**Issue by bitbyte2015** [cov-lineages/pango-designation#850]
Credit to @Ryhisner for being the first to notice this lineage

5 sequences of BA.1.1 with several additional spike mutations have been detected in the same town of Lagoa do Tocantins, Brazil. The sequences were collected between 30-05-2022 and 09-06-2022. Patient metadata indicates that each of the five sequences belongs to a different person. In addition, USHER indicates that one sequence has acquired an additional nucleotide mutation, possibly indicating further transmission beyond the initial chronic patient.

![image](https://user-images.githubusercontent.com/36325823/179619467-85d88611-82ef-4751-8a85-ed0cafaf837f.png)

Additional S gene mutations: N164K, G182D, L368I, Y449S, R493Q, T500S, M740I, D936Y

Sequences:
EPI_ISL_13750714, EPI_ISL_13750726, EPI_ISL_13750730,
EPI_ISL_13750760, EPI_ISL_13750771

**Comment by Sinickle** [comment]
I think it's quite interesting that a completely unrelated BA.1 sequence, EPI_ISL_13314960, also acquired S:493Q, S:500S, S:740I, S:936Y. 
It has a different codon for S:500S than the Brazil sequences, so I believe it must be convergent evolution.

**Comment by corneliusroemer** [comment]
Since nothing has happened here in a while I'll close. Please ping if there's some action again.
