### ISSUE TITLE
BA.2.38 sublineage with S:210T, S:450D, and ORF1a:903V (70 seqs), mostly India

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#851]
<html>
<body>
I am proposing a BA.2.38 sublineage starting at S:450D, that is a child of a larger (95 sequences) undesignated Indian BA.2.38 sublineage that has S:210T. Additionally, there are 6 sequences that have S:210T and ORF1a:903V but do not have S:210T -- I think it would be fine to ignore that stage of the lineage though. 
The geographical distribution of the 22 sequences with S:450D are as follows:

Location | Number of sequences
-- | --
India | 18
United States | 2
France | 1
Singapore | 1

Description
Sublineage of: BA.2.38+S:210T+S:N450D+ORF1a:903V
Earliest sequence: 2022/05/15 (USA)
Most recent sequence: 2022/06/28 (India)
Countries circulating: as shown above

Evidence
Usher tree:

![image](https://user-images.githubusercontent.com/94097102/179659792-da8dbf84-10f9-40d1-a73a-34259101249d.png)

Relative growth advantage according to cov-spectrum in recent 2 months in India, based on only 22 genomes, compared to BA.2.38 is [[0-123%]](https://cov-spectrum.org/explore/India/AllSamples/Past2M/variants?pangoLineage=ba.2.38&variantQuery1=ba.2.38+%26+orf1a%3A903v+%26+s%3A450d&analysisMode=CompareToBaseline&)

[cov-spectrum monitoring link here](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A450d%2Corf1a%3A903v&pangoLineage=ba.2.38&aaMutations1=s%3A450d&pangoLineage1=ba.2.38&)

[EPI_ISL IDs here](https://lapis.cov-spectrum.org/gisaid/v1/sample/gisaid-epi-isl?country=India&dateFrom=2022-05-16&pangoLineage=ba.2.38&host=Human&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&orderBy=random)

**Comment by Sinickle** [comment]
It was the S:450D mutation that caught my eye here. It is in 3 lineages proposed within the last month. 
https://github.com/cov-lineages/pango-designation/issues/812
https://github.com/cov-lineages/pango-designation/issues/772
https://github.com/cov-lineages/pango-designation/issues/843

Additionally, there is 1 or 2 other branches of BA.2.38  that also have spread, making up 13 more sequences, starting at June 6. 
![image](https://user-images.githubusercontent.com/94097102/179661252-78e82738-0f68-41b1-ba39-e5119e36b10f.png)

If you are to just do a growth advantage query for BA.2.38 vs BA.2.38+S:450D in India, then cov-spectrum gives it a growth advantage of [[29-123%]](https://cov-spectrum.org/explore/India/AllSamples/Past2M/variants?pangoLineage=ba.2.38&aaMutations1=s%3A450d&pangoLineage1=ba.2.38&analysisMode=CompareToBaseline&), with 34 sequences.

**Comment by FedeGueli** [comment]
Great proposal, @Sinickle it was a very early catch by you, this sublineage (and the other two smaller ones you mentioned) was already, after your suggestion, in the list attached to #814 (now updated) when the 3 BA.2.38+S:450D together did not reach 15seqs yet:
https://docs.google.com/spreadsheets/d/1zKF3PKaosF3OCcW54gWkyV7Spz8uWrCsYef9IHbj7FA/edit?usp=drivesdk

Too early to say how much but it is growing .

**Comment by FedeGueli** [comment]
35 sequences as today
![Schermata 2022-07-23 alle 09 25 14](https://user-images.githubusercontent.com/87669813/180595148-e413f96c-bbea-48c3-b01b-89b32762ad4c.png)
 :https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38470_b9fb30.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22910G

**Comment by corneliusroemer** [comment]
I'd broaden to remove the ORF1a:903V, then I get 51 sequences and international spread

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=NextcladePangoLineage%3ABA.2.38*+%26+S%3A450D&aaMutations1=s%3A450d&pangoLineage1=ba.2.38&

**Comment by FedeGueli** [comment]
45 sequences on usher as today:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2183d_7060b0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22910G

**Comment by Sinickle** [comment]
Closing this one. As a BA.2* without a growth advantage, it has largely died out now.
