### ISSUE TITLE
Second generation BA.1.1 sublineage circulating in Ontario, Canada (6 seq)

### ISSUE THREAD

**Issue by bitbyte2015** [cov-lineages/pango-designation#852]
Credit to @ryhisner for being the first of my knowledge to notice this cluster

A new sublineage of BA.1.1 has emerged in Ontario with multiple S1 mutations. Patient metadata indicates that at least 5 of the sequences belong to different people. USHER places the sequences on a 21 mutation long branch. In addition, there are several NSP mutations. 4 of the 5 patients were sampled between 03-07-2022 and 05-07-2022.

![image](https://user-images.githubusercontent.com/36325823/179917011-c7cf470a-07fc-43c9-8cb1-8c749a1db08c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41511_7a3a90.json

Private spike mutations: F175S, N460K, K462R, F486L, R493Q, H625R

Sequences:
EPI_ISL_13624440, EPI_ISL_13624441, EPI_ISL_13931117, EPI_ISL_13931975,
EPI_ISL_13931997, EPI_ISL_13932080

**Comment by shay671** [comment]
The reversion in 493 is one of the most converging things I have seen during this pandemic with this Virus. This is happening in dozens of 2nd gen of BA.1 and BA.2 with limited # seq we found in recent months including BA.2.75

**Comment by thomasppeacock** [comment]
There don't appear to have been any new sequences on this but I think it merits monitoring for the interesting profile/evolutionary distance, so going to put a monitoring label on it for now.

**Comment by InfrPopGen** [comment]
Still appears to be no new growth.

**Comment by InfrPopGen** [comment]
Thank you for spotting this lineage @bitbyte2015 As it is still not showing signs of expansion, I will close it for now. Although, it is to be closed as a pango lineage proposal, it remains just as interesting a "phylotype".
