### ISSUE TITLE
parent-child sublineage information missing in lineage file

### ISSUE THREAD

**Issue by silenus092** [cov-lineages/pango-designation#853]
Hi everyone,

We use your method (from sort_lineages.py and aliasing.py) to construct a parent-child relationship.

so after we used the lineage file, we suspected that there is something wrong with the result. 
Omicron lineages do not contain the parent-child information, for example;

the file currently shows
```
BA.5	none
```
whereas it should probably be something like this?
```
BA.5	BA.5.1, BA.5.2 ....
```
We notice this for all Omicron sublineages.

Are you planning to update the code or the way it is constructed?

Best regards,
Note
@akifoss

**Comment by corneliusroemer** [comment]
Hi @silenus092, I didn't know you were relying on this utility to create a dealiased tree of lineages.

I've moved the utility to a separate Python package at https://github.com/cov-lineages/pango-designation/commit/6641ad8a96cdb5d9a81a968af90ae98077f799d3 where it is now also pip installable.

sort_lineages.py should now work again

The package is now also properly documented. Let me know over there whether you have any questions.

I use the package to create a tree of pango lineages based off the `alias_key.json`, which seems to be the same use case you have.
