### ISSUE TITLE
Potential Sublineage of BA.5.2.1 with ORF9b:26I, ORF9b:30L, N:30F. ~5000 seqs, growth advantage

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#855]
**Description**
Sublineage of: BA.5.2.1
Earliest sequence: 2022/04/24 (Israel)
Mutations on top of BA.5.2.1: N:30F, ORF9b:26I, ORF9b:30L

Just looking at some of the top countries with genome collection dates in the last month:
<html>
<body>

Location | Number of sequences | Prevalence
-- | -- | --
United States | 744 | 1.779%
Belgium | 351 | 10.538%
United Kingdom | 253 | 1.075%
Canada | 150 | 3.836%
Denmark | 148 | 1.269%
France | 93 | 1.92%
Netherlands | 81 | 3.861%
Australia | 80 | 2.305%
Brazil | 48 | 12.214%
Italy | 48 | 2.67%
Germany | 47 | 1.924%
Spain | 45 | 3.115%

</body>
</html>

**Comment**
This one is fairly confusing to me, so definitely would appreciate some review on it too. I think it will have different mutations based on the tool you're using, since the mutations are right around deletions. 
CoV-Spectrum normally displays BA.5.2.1 as having N:31-33del, ORF9b:27-29del. 
This proposed sublineage shows a mutation of N:33F and ORF9b:29I, but instead deletes N:30 and ORF9b:26. I think the process that's happening in reality here is  N:G30F and ORF9b:M26I

Regardless, I'd like to point out that due to the deletion in all BA* ORF9b, the two ORF9b mutations are adjacent. 

The tools I'm familiar with aren't able to interpret the nucleotide mutations. 
USHER doesn't come close to being able to build a tree for these sequences. 
I believe this is a real, non-artefact sublineage due to how a cov-spectrum query for ORF9b:29I,ORF9b:30L returns almost exclusively BA.5.2.1 sequences.

[cov-Spectrum query](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf9b%3A29i%2Corf9b%3A30l%2Cm%3A3n&aaMutations1=orf9b%3A29i%2Corf9b%3A30l&pangoLineage1=ba.5.2.1&)

**Example IDs:**
EPI_ISL_13510331, EPI_ISL_13764137, EPI_ISL_13720038, EPI_ISL_13755320, EPI_ISL_13438429, EPI_ISL_13721408, EPI_ISL_13705102, EPI_ISL_13577170, EPI_ISL_13829318, EPI_ISL_13760455, EPI_ISL_13803178

**Comment by Sinickle** [comment]
[Example growth advantage query, relative to BA.5.2.1](https://cov-spectrum.org/explore/Belgium/AllSamples/Past2M/variants?pangoLineage=ba.5.2.1&aaMutations1=orf9b%3A29i%2Corf9b%3A30l&pangoLineage1=ba.5.2.1&analysisMode=CompareToBaseline&)

For the last 2 months, choosing countries where the proposed lineage made up more than 2% of sequences in the last single month, with more than 40 sequences. 

Australia - [-15-5%]
Belgium - [4-19%] 
Brazil - [12-50%]
Canada - [3-31%] 
Italy - [-16-22%]
Netherlands - [-1-31%] 
Spain - [-2-32%] 

Not super clear, but I believe it's tending towards growth advantage over BA.5.2.1.

**Comment by FedeGueli** [comment]
@AngieHinrichs could you look at this? could be the same thing of what your analysis showed for the S:346T +N:33F recently designated sublineage?

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs could you look at this? could be the same thing of what your analysis showed for the S:346T +N:33F recently designated sublineage?

Thanks @FedeGueli -- in fact, I think this is the same lineage as #722!  There are multiple sources of confusion:
* a substitution adjacent to a deletion with ambiguous placement
* ORF9b vs. N (can we just stick with N please?  🙂)

> USHER doesn't come close to being able to build a tree for these sequences.

There are multiple reasons for this too:
* The cov-spectrum query now gets >6500 sequences, while the largest subtree that the UShER web interface will output is 5000 sequences, and only half of the given subtree size will be uploaded sequences (the other half are randomly selected from nearby nodes to provide context).  So unfortunately, for such a big lineage, the web interface returns a bunch of subtrees that actually overlap quite a bit.
* The lineage is split up into multiple branches by sequences with different combinations of reversions (that are also found in some unrelated sequences).  🙁

**Comment by AngieHinrichs** [comment]
And to make things even more interesting, #827 (which may be a sublineage of this / #722, adding S:R346T/G22599C) has already been designated BF.7.

**Comment by Sinickle** [comment]
@AngieHinrichs 
Yes definitely possible I'm just confused! And thanks for your explanations!
It sounds like ORF9b can be considered a part of N, from what you're saying? I found this one through Cov-Spectrum which separates the two, and I didn't know they were actually ever combined!

I don't see #722 mention anything that could be ORF9b:26I or ORF9b:30L though. Why is that?

**Comment by AngieHinrichs** [comment]
> a part of N, but with a different reading frame.

Yep!  And there's no annotation for ORF9b in the [RefSeq record NC_045512.2](https://www.ncbi.nlm.nih.gov/nuccore/NC_045512.2); some gene annotation sets have it, some don't, so it took me a while to figure out what nucleotide changes correspond to "ORF9b:26I, ORF9b:30L" and it didn't really click until @FedeGueli brought up the discussion in #722.  🙂
