### ISSUE TITLE
BA.2.75 sublineage with S:D574V (97+ seq as of 02.08.22; 7 countries)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#856]
Proposal for a sublineage of BA.2.75
Earliest sequence: 23.06.2022 (India)
Countries detected: India, Canada, Germany, Japan

Defining mutation:
A23283T = S:D574V

This subvariant is defined by S:D574V and is already present in four countries across three continents. The variant is distinct from those listed at #814.

![grafik](https://user-images.githubusercontent.com/102166254/180206038-9594c094-7186-437b-b402-92e0bdc14d58.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_771d_935020.json?branchLabel=aa%20mutations&c=gt-S_574

![grafik](https://user-images.githubusercontent.com/102166254/180206978-0af5a72e-19e4-43a7-953c-bb24faa66852.png)

![grafik](https://user-images.githubusercontent.com/102166254/180207871-9e09c37e-e8a8-4459-adf7-61d4e24084ef.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AD574V&pangoLineage=BA.2.75*&

EPI_ISL_13671612
EPI_ISL_13847294
EPI_ISL_13931316
EPI_ISL_13932384
EPI_ISL_13933623
EPI_ISL_13957682
EPI_ISL_13957683
EPI_ISL_13964197
EPI_ISL_13964653
EPI_ISL_13966920
EPI_ISL_13966927
EPI_ISL_13966928
EPI_ISL_13966930

**Comment by corneliusroemer** [comment]
There are now 32 BA.2.75 (by Nextclade) on GISAID that have S:574V

31 of them cluster together. That's around 5% of all BA.2.75.

International spread has reached:
- Canada
- Germany
- Denmark
- Japan

Distribution in India (yellow is this lineage, green is rest)
<img width="766" alt="image" src="https://user-images.githubusercontent.com/25161793/180332463-f4c1c02d-cf59-40b4-b4c3-9fce46cfb6bf.png">

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/25161793/180332469-85bc0010-698a-4b4b-ac7c-43d6f998a88e.png">

Whole tree:
<img width="1565" alt="image" src="https://user-images.githubusercontent.com/25161793/180332520-fb1812ed-6730-4c6d-bb2a-c706a937d1f0.png">

**Comment by agamedilab** [comment]
30 seq on Usher as of 25.07.22.

![grafik](https://user-images.githubusercontent.com/102166254/180765939-8a2e4210-c28e-4969-a4d9-959a222b6bb6.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2653a_e7a2e0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A23283T

**Comment by emily-smith1** [comment]
Now in USA-CA as well: EPI_ISL_14054623

<img width="840" alt="image" src="https://user-images.githubusercontent.com/84812104/181080764-f5d78bde-5b2f-4fc7-bd19-205b90ab2b5c.png">

**Comment by corneliusroemer** [comment]
Now 60 out of ~900 in GISAID, 8 out of 12 Danish sequences

**Comment by agamedilab** [comment]
50 seq. on Usher as of 01.08.22.

![grafik](https://user-images.githubusercontent.com/102166254/182088877-1bdd6430-6686-4898-95cc-584f9148d4b9.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1768d_776560.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A23283T

**Comment by agamedilab** [comment]
Nearly double overnight with yesterdays GISAID uploads (c. 97 seq):

![grafik](https://user-images.githubusercontent.com/102166254/182339084-c1336d96-589e-4ffe-81a2-a484d51a8ae6.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_30c2a_8e0360.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A23283T

**Comment by FedeGueli** [comment]
Actually.this is the fastest  lineage in our 500+ sublineages long list. And i am noticing its advantage increases update by update.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.75.1 with 42 newly designated sequences, and 2 updated designations. Defining mutations: A23283T (S:D574V)
