### ISSUE TITLE
BA.2 sub lineage defined by S:L452Q and ORF10:S15G, 36 samples (the Czech Republic, Germany, and Slovakia)

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#857]
BA.2 sub lineage 

36 Samples from the Czech Republic, Germany, and Slovakia.
date range : 06.05.2022-07.07.2022

Defining mutations : 

C6040T
C9979T
T22917A (S:L452Q)
A29600G (ORF10:S15G)

Mediating mutations from BA.2 till this branch point : 
G1181A (NSP2:V126I)
C28435T

Usher build :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43df_989c10.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C6040T,C9979T,T22917A,A29600G
 
![image](https://user-images.githubusercontent.com/80166370/180277281-6053e199-7d8f-48dc-940c-78546dcfa4cf.png)

GISAID list 
[GISAID list.csv](https://github.com/cov-lineages/pango-designation/files/9161521/GISAID.list.csv)

Usher query : [3-of:C6040T,C9979T,T22917A,A29600G]

**Comment by FedeGueli** [comment]
39 seqs as today:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2b5cc_293c10.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C28435T

**Comment by InfrPopGen** [comment]
Thank you for proposing. This lineage has shown little growth advantage (or growth at all) over the past month, at the Europe level or in Germany/Slovakia. Consequently, closing for now, but please do reopen if these trends reverse at some point in the future.
