### ISSUE TITLE
Permalink to alias definitions

### ISSUE THREAD

**Issue by RaphaelRaphael** [cov-lineages/pango-designation#858]
Hi,

would it be possible for you to generate/update a link that will always point on the last version of the aliases definitions ?

cov-lineages/pango_designation/alias_key.json

It would be very helpful

Thank you

**Comment by AngieHinrichs** [comment]
I believe that would be 

https://raw.githubusercontent.com/cov-lineages/pango-designation/master/pango_designation/alias_key.json
