### ISSUE TITLE
New "P.n" lineage in Brazil with mutations E484Q and N501T

### ISSUE THREAD

**Issue by aplamarca** [cov-lineages/pango-designation#86]
**Description**

Sub-lineage of: B.1.1.28
Earliest sequence: hCoV-19/Brazil/SP-765479-NBD14/2021|EPI_ISL_1445155|2021-03-09
Most recent sequence: hCoV-19/Brazil/RJ-LNN00783/2021|EPI_ISL_2101742|2021-04-25
Countries circulating: Brazil

We have identified the sublineage in the states of Rio de Janeiro and São Paulo, Brazil. This clade carries ten lineage defining mutations: four in ORF1ab(T1637I, A3209V, Q3729K e P4337L), five in Spike (F2L, Q14K, T95I, **E484Q** e **N501T**), one in the Nucleocapsid protein (G215V). The E484Q mutation was observed in the current pandemic wave in India caused by lineage B.1.617 (Ferreira et al, 2021; https://doi.org/10.1101/2021.05.08.443253) . The N501T mutation has been previously described in both minks and humans (Cai & Cai, 2021; https://doi.org/10.1101/2021.03.18.21253734). Due to the grave possibility of these mutations increasing viral escape from immune system, we believe this clade should be elevated to a lineage in order to facilitate its surveillance. 

We have also posted on Virological about on this new lineage
https://virological.org/t/genomic-surveillance-of-sars-cov-2-in-the-state-of-rio-de-janeiro-brazil-technical-briefing/683/5

**Genomes**
[new_lineage_list.txt](https://github.com/cov-lineages/pango-designation/files/6489981/new_lineage_list.txt)

**Evidence**
![path1156](https://user-images.githubusercontent.com/82976078/118412520-e46eef80-b670-11eb-9d07-e4f2e42f06e6.png)

![new_lineage_px](https://user-images.githubusercontent.com/82976078/118556999-f74df680-b73a-11eb-98df-35935fc4ab99.png)

**Comment by chrisruis** [comment]
Thanks @aplamarca for submitting this. We've added this as lineage P.5 in [v1.2.17](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.17)
