### ISSUE TITLE
Potential BA.1*/BA.2* recombinant with likely breakpoint at NSP3 (50 seqs as of 2022-08-05, mainly Reunion)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#860]
### Description
**Recombinant between**: BA.1* and BA.2*
**Earliest sequence**: 2022/02/02 (Reunion)
**Most recent sequence**: 2022/07/07 (metropolitan France)
**Countries circulating**: Reunion (43/49), metropolitan France (6/49)
**Likely breakpoint**: 2834-4183 (NSP3)
**Mutations on branch**: G21796T (S:R78S)

**Conserved Nuc mutations** (those in red frames are likely from BA.1*):
![image](https://user-images.githubusercontent.com/86835836/180328758-4be05860-7840-4978-9232-0e46440dd8d9.png)
**Cov-spectrum query**: A2832G, G4184A, G21796T
**GISAID query**: Spike_R78S, NSP3_K38R, NSP3_G489S

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/180329186-b56cb8a3-d011-4400-a1fb-03614d1e293c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3b71c_954180.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:G21796T

Its largest and currently circulating sub-branch has gained a few additional amino changes: S:Q675H, S:S704L, ORF7a:T120I and N:P383S.

### Genomes:
EPI_ISL_11540575, EPI_ISL_12698931, EPI_ISL_12730919, EPI_ISL_12730949, EPI_ISL_12731044, EPI_ISL_12731124, EPI_ISL_12731153, EPI_ISL_12731188, EPI_ISL_13616782, EPI_ISL_13616880, EPI_ISL_13617604, EPI_ISL_13766965, EPI_ISL_13767004, EPI_ISL_13767131, EPI_ISL_13767168, EPI_ISL_13767249, EPI_ISL_13767287, EPI_ISL_13767308, EPI_ISL_13767406, EPI_ISL_13767418, EPI_ISL_13767477, EPI_ISL_13767527, EPI_ISL_13767544, EPI_ISL_13767661, EPI_ISL_13767704, EPI_ISL_13838121, EPI_ISL_13838287, EPI_ISL_13838306, EPI_ISL_13838310, EPI_ISL_13838315, EPI_ISL_13838329, EPI_ISL_13838338, EPI_ISL_13838340, EPI_ISL_13838531, EPI_ISL_13841579, EPI_ISL_13909025, EPI_ISL_13909296, EPI_ISL_13909430, EPI_ISL_13909526, EPI_ISL_13909539, EPI_ISL_13909567, EPI_ISL_13909884, EPI_ISL_13909909, EPI_ISL_13910226, EPI_ISL_13910265, EPI_ISL_13910549, EPI_ISL_13910708, EPI_ISL_13910997, EPI_ISL_13911116

**Comment by c19850727** [comment]
50 sequence bar reached, as of 2022-08-05.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAR with 49 newly designated sequences, and 0 updated designations.
