### ISSUE TITLE
BA.4.1 sub lineage defined by Orf1a:N1181K,S:R357K and S:A688V. 19 samples, HK and australia

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#863]
BA.4.1 sublineage found with @talyash and @Boltyansky

19 samples from :  (Hong Kong) (18);Australia (1)
16 age-gender combinations
Dates range: 2022-06-27 ~ 2022-07-14

Defining mutations :
G1021A
T3808G (Orf1a:N1181K)
C5416T
G22632A (S:R357K)
C23625T (S:A688V)

Mediating mutations from BA.4.1 till this branch point :
T15276C
C24130T
C25517T (ORF3a:P42L)

Usher build :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4232_aa6210.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G1021A,T3808G,C5416T,G22632A,C23625T

![image](https://user-images.githubusercontent.com/80166370/180480185-6e3db1bb-3dff-4ed1-81f8-d749c56528d2.png)

GISAID ref list :
EPI_ISL_13963814
EPI_ISL_13710114
EPI_ISL_13963860
EPI_ISL_13963845
EPI_ISL_13963850
EPI_ISL_13963848
EPI_ISL_13963842
EPI_ISL_13963803
EPI_ISL_13963858
EPI_ISL_13963859
EPI_ISL_13963856
EPI_ISL_13963818
EPI_ISL_13963824
EPI_ISL_13963847
EPI_ISL_13963825
EPI_ISL_13963823
EPI_ISL_13963861
EPI_ISL_13963796
EPI_ISL_13963851

**Comment by c19850727** [comment]
Nice spot @shay671 ! 

I am thinking it might be more articulate to broaden this proposal to the branch with ORF3a:P42L, so as to correlate with introduction of BA.4.1 into Australia, and then propose the current sub-branch with S:R357K and S:A688V as its sublineage. so as to correlate with its further introduction into Hong Kong. What do you think?

**Comment by FedeGueli** [comment]
@shay671 it counts now 42 sequences corresponding to around 10% of sequences sampled in Hk after 1st of August.

**Comment by shay671** [comment]
Hi @FedeGueli  
Thanks for the spot. Can you send here the Gisaid ref list ?

**Comment by corneliusroemer** [comment]
Weird that there are so few sequences from HK.

It's never really showed up anywhere else - so I think we can close this.

Let's reopen if more sequences appear.

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/25161793/190933090-27671537-0d2c-4a1e-9389-c3dd9ac20f2d.png">

**Comment by FedeGueli** [comment]
53 viruses as today.
