### ISSUE TITLE
BA.2.9 sublineage with S:S730F (471 seq), and its sublineage with ORF1a:A2909V, ORF1a:R4387C (27 seq, ~40% in Venezuela)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#864]
Proposal for a sublineage of BA.2.9
Earliest sequence: 2022-04-11 (USA)
Countries detected: USA (250+), Denmark (79+), Peru (24), Colombia (17), UK (17), and smaller numbers in ~20 others

AA mutations on top of BA.2.9:
S:S730F
ORF1a:H1113Y
ORF1b:Q1393R
ORF6:D61P (from D61L: GAT -> CTC -> CCC)
ORF9b:P51L (thanks @alurqu!)

This lineage was first detected in the US but may have arisen in Colombia, which was the only other country to detect it in April; it was at around 2% prevalence in May there. It seems to be substantially fitter than its parent: in the USA in the last 3 months it shows a 41% advantage over BA.2.9* and even a 7% advantage over BA.2.12.1*, but it has a -47% disadvantage against BA.5*.

[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A730F%2CORF1a%3A1113Y%2CORF1b%3A1393R&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A730F%2CORF1a%3A1113Y%2CORF1b%3A1393R&)

Proposal for a sublineage of the above lineage
Earliest sequence: 2022-05-28 (Australia)
Countries detected: Venezuela (10), USA (10), Israel (3), Australia, Denmark, Germany, New Zealand (1 each)

AA mutations on top of the above lineage:
ORF1a:A2909V, R4387C

This sublineage likely represents the introduction of the above lineage to Venezuela, a country which sequences very little (there is a 3-month gap with no sequences between 7 February and 10 May). It makes up 10 of 25 sequences from Venezuela with sample dates in June.

[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A730F%2CORF1a%3A1113Y%2CORF1b%3A1393R%2CORF1a%3A2909V%2CORF1a%3A4387C&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A730F%2CORF1a%3A1113Y%2CORF1b%3A1393R%2CORF1a%3A2909V%2CORF1a%3A4387C&)

Main lineage in yellow, Venezuelan sublineage in blue.
<img width="734" alt="BA29_S730F" src="https://user-images.githubusercontent.com/42699509/180626164-ecf585f7-9ff4-4e7d-80c0-e4ca76349b23.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_436ff_c72690.json?branchLabel=aa%20mutations&c=gt-nuc_23751,14805&label=nuc%20mutations:A17645G](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_436ff_c72690.json?branchLabel=aa%20mutations&c=gt-nuc_23751,14805&label=nuc%20mutations:A17645G)

**Comment by c19850727** [comment]
Interestingly ORF1a:A2909V is also the defining change of BA.2.3.

**Comment by alurqu** [comment]
I've been looking at this one too.  I'll note that there may be some lineage structure of significance before the S:730F mutation.  I'll get to that in a moment.

First, here's the UShER subtree to S:730F using GenBank sequences obtained via Nextstrain:
![usher_subtree_BA 2 9+ORF1a_1113Y+ORF1b_1393R+ORF6_61P+ORF9b_51L+S_730F](https://user-images.githubusercontent.com/88959107/180668838-9cb27862-926d-45a2-8c60-9bc6eb76b8c3.png)
with live access at https://nextstrain.org/fetch/raw.githubusercontent.com/alurqu/pango-designation-support-alurqu/main/Issue_864/subtreeAuspice1_genome_BA.2.9%2BORF1a_1113Y%2BORF1b_1393R%2BORF6_61P%2BORF9b_51L%2BS_730F.json.  The uploaded samples are all BA.2.9 with C28435T(ORF9b:51L), A27383C(ORF6:61P), C3602T(ORF1a:1113Y), A17645G(ORF1b:1393R), and C23751T(S:730F).  Please note that as I'll explain below, this subtree may be too far out on a branch past some other potentially significant structure.

Second, here's a ZIP containing GenBank-via-Nextstrain metadata and sequence files for the branch to S:730F as well as two other potential branches from BA.2.9+C28435T/ORF9b:51L (synonymous in N) plus additional UShER results for the S:730F sublineage: 
[Issue_864_BA.2.9+ORF1a_1113Y+ORF1b_1393R+ORF6_61P+ORF9b_51L+S_730F.zip](https://github.com/cov-lineages/pango-designation/files/9176862/Issue_864_BA.2.9%2BORF1a_1113Y%2BORF1b_1393R%2BORF6_61P%2BORF9b_51L%2BS_730F.zip)

Third, I'd like to discuss some structure getting from base BA.2.9 to S:730F:

A) BA.2.9+C28435T(ORF9b:51L) growth advantage over BA.2.9 and current counts as of 24 July 2022:

![Issue_864_BA 2 9+ORF9b_51L_Growth](https://user-images.githubusercontent.com/88959107/180669223-918e532b-e33a-42be-9590-fac22e6b42d9.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=BA.2.9&aaMutations1=ORF9b%3A51L&pangoLineage1=BA.2.9&analysisMode=CompareToBaseline&

![Issue_864_BA 2 9+ORF9b_51L_Counts](https://user-images.githubusercontent.com/88959107/180669290-791b6778-5e6e-4994-a4c2-f73fd5f7e009.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF9b%3A51L&pangoLineage=BA.2.9&

B) BA.2.9+C28435T(ORF9b:51L)+A27383C(ORF6:61P) growth advantage over BA.2.9 and current counts as of 24 July 2022:

![Issue_864_BA 2 9+ORF9b_51L+ORF6_61P_Growth](https://user-images.githubusercontent.com/88959107/180669346-fb742a34-299d-4a7d-814c-9924c148c0ee.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=BA.2.9&aaMutations1=ORF9b%3A51L%2CORF6%3A61P&pangoLineage1=BA.2.9&analysisMode=CompareToBaseline&

![Issue_864_BA 2 9+ORF9b_51L+ORF6_61P_Counts](https://user-images.githubusercontent.com/88959107/180669332-6f8122ba-0029-4b47-ba5b-02ea4043d53a.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF9b%3A51L%2CORF6%3A61P&pangoLineage=BA.2.9&

C) BA.2.9+C28435T(ORF9b:51L)+A27383C(ORF6:61P)+C3602T(ORF1a:1113Y) growth advantage over BA.2.9 and current counts as of 24 July 2022:

![Issue_864_BA 2 9+ORF9b_51L+ORF6_61P+ORF1a_1113Y_Growth](https://user-images.githubusercontent.com/88959107/180669397-6a8f6734-6f4f-4fb9-8e84-3ab5e1cb64ff.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=BA.2.9&aaMutations1=ORF9b%3A51L%2CORF6%3A61P%2CORF1a%3A1113Y&pangoLineage1=BA.2.9&analysisMode=CompareToBaseline&

![Issue_864_BA 2 9+ORF9b_51L+ORF6_61P+ORF1a_1113Y_Counts](https://user-images.githubusercontent.com/88959107/180669432-540535ea-e270-41a9-94d4-5f792ad66e19.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF9b%3A51L%2CORF6%3A61P%2CORF1a%3A1113Y&pangoLineage=BA.2.9&

D) BA.2.9+C28435T(ORF9b:51L)+A27383C(ORF6:61P)+C3602T(ORF1a:1113Y)+A17645G(ORF1b:1393R)+C23751T(S:730F) growth advantage over BA.2.9 and current counts as of 24 July 2022, noting that counts for A17645G(ORF1b:1393R) and C23751T(S:730F) alone or together are approximately the same given the other mutations:

![Issue_864_BA 2 9+ORF9b_51L+ORF6_61P+ORF1a_1113Y+ORF1b_1393R+S_730F_Growth](https://user-images.githubusercontent.com/88959107/180669578-a69c0436-515d-4e8f-b2e0-d4e6174e5f5e.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=BA.2.9&aaMutations1=ORF9b%3A51L%2CORF6%3A61P%2CORF1a%3A1113Y%2CORF1b%3A1393R%2CS%3A730F&pangoLineage1=BA.2.9&analysisMode=CompareToBaseline&

![Issue_864_BA 2 9+ORF9b_51L+ORF6_61P+ORF1a_1113Y+ORF1b_1393R+S_730F_Counts](https://user-images.githubusercontent.com/88959107/180669601-e3fbc6ec-dd59-41c4-b426-5a1a542f949a.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF9b%3A51L%2CORF6%3A61P%2CORF1a%3A1113Y%2CORF1b%3A1393R%2CS%3A730F&pangoLineage=BA.2.9&

![Issue_864_BA 2 9+ORF9b_51L+ORF6_61P+ORF1a_1113Y+ORF1b_1393R_Counts](https://user-images.githubusercontent.com/88959107/180669627-79249533-b870-45db-834a-864348f6587c.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF9b%3A51L%2CORF6%3A61P%2CORF1a%3A1113Y%2CORF1b%3A1393R&pangoLineage=BA.2.9&

![Issue_864_BA 2 9+ORF9b_51L+ORF6_61P+ORF1a_1113Y+S_730F_Counts](https://user-images.githubusercontent.com/88959107/180669641-8350a2b0-1f66-4bf1-92d4-ca2e998c2943.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF9b%3A51L%2CORF6%3A61P%2CORF1a%3A1113Y%2CS%3A730F&pangoLineage=BA.2.9&

E) Now growth advantage and counts for a first plausible side-branch from BA.2.9+C28435T(ORF9b:51L).  This one is BA.2.9+C28435T(ORF9b:51L)+C28377T(N:35V and ORF9b:32C):

![Issue_864_BA 2 9+ORF9b_51L+N_35V+ORF9b_32C_Growth](https://user-images.githubusercontent.com/88959107/180670284-592c2b95-7f2d-42fb-9af7-eacf2fcd8c84.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=BA.2.9&aaMutations1=ORF9b%3A51L%2CN%3A35V%2CORF9b%3A32C&pangoLineage1=BA.2.9&analysisMode=CompareToBaseline&

![Issue_864_BA 2 9+ORF9b_51L+N_35V+ORF9b_32C_Counts](https://user-images.githubusercontent.com/88959107/180670338-d1701e72-c592-401f-a9db-52e2fbcbdf2e.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF9b%3A51L%2CN%3A35V%2CORF9b%3A32C&pangoLineage=BA.2.9&

F) And growth advantage and counts for a first plausible side-branch from BA.2.9+C28435T(ORF9b:51L).  This one is BA.2.9+G29440T(N:389H)+A3959G(ORF1a:1232V)+G5683A(ORF1a:1806I) with several additional synonymous mutations:

![Issue_864_BA 2 9+ORF9b_51L+N_389H+ORF1a_1232V+ORF1a_1806_Growth](https://user-images.githubusercontent.com/88959107/180670537-9935b6ce-01d4-4e17-a038-6d08aa07a8c9.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF9b%3A51L%2CN%3A389H%2CORF1a%3A1232V%2CORF1a%3A1806I&pangoLineage=BA.2.9&

![Issue_864_BA 2 9+ORF9b_51L+N_389H+ORF1a_1232V+ORF1a_1806_Counts](https://user-images.githubusercontent.com/88959107/180670559-d62ef1c3-797b-4ce5-ae45-b4231069d79f.png)
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=BA.2.9&aaMutations1=ORF9b%3A51L%2CN%3A389H%2CORF1a%3A1232V%2CORF1a%3A1806I&pangoLineage1=BA.2.9&analysisMode=CompareToBaseline&

Given the step changes in growth advantages and especially the plausible growth-advantaged side-branches from BA.2.9+C28435T(ORF9b:51L), I propose designation of an intermediate lineage at BA.2.9+C28435T(ORF9b:51L) with consideration of designation of other possible intermediate lineages.

As a final note, as of 24 July 2022 I also see a synonymous mutation C2197T in all of the GenBank-via-Nextstrain BA.2.9+C28435T(ORF9b:51L)+A27383C(ORF6:61P)+C3602T(ORF1a:1113Y)+A17645G(ORF1b:1393R)+C23751T(S:730F) samples.  I have not attempted to determine at which step this mutation may have occurred.

**Comment by silcn** [comment]
Ah, I had missed that C28435T=ORF9b:51L was an AA mutation, because it is silent in N, and that confuses Nextstrain. Agree that BA.2.9+ORF9b:51L may deserve its own designation.

**Comment by corneliusroemer** [comment]
While this is dead now - I think it still deserves designation because it made up such a large share of sequences in Venezuela at some point.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A730F%2CORF1a%3A1113Y%2CORF1b%3A1393R&

<img width="2175" alt="image" src="https://user-images.githubusercontent.com/25161793/190933007-3db2d581-21aa-4005-b441-01b14642e0b3.png">

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.9.7 with 490 newly designated sequences, and 3 updated designations from BA.2.9. Defining mutation C23751T (S:S730F) (following A17645G (ORF1b:Q1393R)).
