### ISSUE TITLE
Suggestion to summatorily designate BA.4/5* with S:346 mutations

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#865]
One very clear trend in BA.4/5 is that the addition of S:346I/K/T/S confers a significant growth advantage (~30-50% per week).

<img width="2310" alt="image" src="https://user-images.githubusercontent.com/25161793/180654555-19155c49-f06d-4e8c-bb5b-e2943757ed8d.png">

I was surprised to find that we only seem to have 2 BA.4* with S:346 designated (BA.4.6 and BA.4.7) and only 1 BA.5* (BF.7).

About 10% of BA.4 with S:346 seem not to be part of a designated sublineage.
<img width="2133" alt="image" src="https://user-images.githubusercontent.com/25161793/180653812-8ba43035-fcfd-4ad1-9a53-3df91e98edcf.png">

For BA.5 that share is even 70%.
<img width="2128" alt="image" src="https://user-images.githubusercontent.com/25161793/180653850-297c3bf3-b127-4e32-8efd-e99d416b42bc.png">

I have not seen another single substitution that confers such a large and consistent growth advantage in a BA.4/5 background yet.

Unfortunately I don't have the time to go and propose all the lineages but there are enough of you here in the community to take care of this: @silcn @agamedilab @FedeGueli @bitbyte0 @sinickle & co

Here are 3 proposed but not yet designated lineages BA.4/5 lineages with S:346 I could find:
- https://github.com/cov-lineages/pango-designation/issues/753 (I've just checked and accepted as it's a very clear case for designation)
- https://github.com/cov-lineages/pango-designation/issues/800
- https://github.com/cov-lineages/pango-designation/issues/837

But there are definitely some big unproposed BA.5* lineages with S:346. From a cursory analysis via covSpectrum I'd suggest to look into:
- A Swiss-German BA.5 + S:346I + C18804T + C17676T lineage with significant global spread and 475 sequences (I'd designate immediately): https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ABA.5*+%26+S%3AR346I++%26+C17676T+%26+C18804T&variantQuery1=S%3AR346T+%26+nextcladePangoLineage%3ABA.4*&variantQuery2=nextcladePangoLineage%3ABA.4*&variantQuery3=nextcladePangoLineage%3ABA.5*&variantQuery4=nextcladePangoLineage%3ABA.4.6*&variantQuery5=nextcladePangoLineage%3ABA.4.7*&
- One (or is it many?) BA.5* sublineages with S:346T that seem on the rise in the US, UK, and particularly Czechia where a non-BF.7 BA.5* with S:346 makes up 5% of cases already (300 sequences worldwide of this): https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ABA.5*+%26+%21nextcladePangoLineage%3ABF.7*+%26+S%3AR346T&variantQuery1=S%3AR346T+%26+nextcladePangoLineage%3ABA.4*&variantQuery2=nextcladePangoLineage%3ABA.4*&variantQuery3=nextcladePangoLineage%3ABA.5*&variantQuery4=nextcladePangoLineage%3ABA.4.6*&variantQuery5=nextcladePangoLineage%3ABA.4.7*&
- Czech BA.5.1 sublineage (making up 5% already) with S:346T: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ABA.5*+%26+%21nextcladePangoLineage%3ABF.7*+%26+S%3AR346T+%26+%2126151T+%26+T27438C++%26+C26681T&variantQuery1=S%3AR346T+%26+nextcladePangoLineage%3ABA.4*&variantQuery2=nextcladePangoLineage%3ABA.4*&variantQuery3=nextcladePangoLineage%3ABA.5*&variantQuery4=nextcladePangoLineage%3ABA.4.6*&variantQuery5=nextcladePangoLineage%3ABA.4.7*&

Given the clear pattern we're seeing with S:346 lineages it makes sense to go and look for them specifically.

**Comment by FedeGueli** [comment]
Hi @corneliusroemer there is also this one proposed BA.5 +S:346T with a 67% of growth advantage vs baseline: #837

**Comment by FedeGueli** [comment]
@corneliusroemer i am checking these two queries, shpuld i propose them separately in independet issues or just commenting here below?

**Comment by FedeGueli** [comment]
@corneliusroemer i think this "A Swiss-German BA.5 + S:346I + C18804T + C17676T lineage with significant global spread and 475 sequences (I'd designate immediately): https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ABA.5*+%26+S%3AR346I++%26+C17676T+%26+C18804T&variantQuery1=S%3AR346T+%26+nextcladePangoLineage%3ABA.4*&variantQuery2=nextcladePangoLineage%3ABA.4*&variantQuery3=nextcladePangoLineage%3ABA.5*&variantQuery4=nextcladePangoLineage%3ABA.4.6*&variantQuery5=nextcladePangoLineage%3ABA.4.7*&" is the same of #753 just further in the tree:
![Schermata 2022-07-24 alle 19 56 12](https://user-images.githubusercontent.com/87669813/180659861-862967b6-6173-4807-a492-9a68dbc313e1.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22de2_d86be0.json?branchLabel=nuc%20mutations&label=nuc%20mutations:T1570C

**Comment by FedeGueli** [comment]
@corneliusroemer 
In Czechia there is a BA.5.1 sublineage in a branch with C26681T (300+ seqs) defined by Orf3a:R68G and S:R346T:
 it counts  42 sequences ( tow of them have S:346K instead of T) spread in 10 countries but mostly in czechia (24 out of 42seqs)
![Schermata 2022-07-24 alle 20 03 06](https://user-images.githubusercontent.com/87669813/180660073-2d5bfdc1-82b8-418e-a73a-9b5652bb15be.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2280e_d86a00.json?branchLabel=aa%20mutations&c=gt-ORF3a_68&label=nuc%20mutations:C26681T

Covspectrum overview: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AR346T%2COrf3a%3AR68G&nucMutations=C26681T&variantQuery1=G22599T+%26+nextcladePangoLineage%3ABA.5+%26+C18804T+%26+T1570C&

It has apparently 12% of growth advantage vs BA.5 BAseline in Czechia (4% in Europe) during last two months:
https://cov-spectrum.org/explore/Czechia/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.5*&aaMutations1=S%3AR346T%2COrf3a%3AR68G&nucMutations1=C26681T&analysisMode=CompareToBaseline&

![Schermata 2022-07-24 alle 20 07 59](https://user-images.githubusercontent.com/87669813/180660194-91a29a45-3d75-419b-a185-fba8dd13d75f.png)

**Comment by corneliusroemer** [comment]
@FedeGueli Open in separate issues - this is just to keep track and raise awareness

You may be right about the Swiss-German one!

**Comment by FedeGueli** [comment]
@corneliusroemer 
then there is a branch budding off from BA.5.2 with S:346T that shows some well defined diversity ( maybe just independent acquisitions of S:346T)
48 sequences 14 countries (among them Czechia 5 seqs) 4 continents 
![Schermata 2022-07-24 alle 20 13 07](https://user-images.githubusercontent.com/87669813/180660391-ab3b6d78-8143-4625-aa7f-858fa13b6fba.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_2280e_d86a00.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G22599C

CovSpectrum. https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.5.2+%26+S%3AR346T+&aaMutations1=S%3AR346T%2COrf3a%3AR68G&nucMutations1=C26681T&

**Comment by FedeGueli** [comment]
Then a bunch of lineages counting just a few sequences each one:

1)
BE.1 + C1471T+S:346T:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_2265e_d867b0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C1471T

2)
BA.5.1 +Orf1a:K1407M +346T 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice6_genome_2265e_d867b0.json?c=pango_lineage_usher&label=nuc%20mutations:A4485T

3)
BA.5.1 + G5665A + orf6:I18V +S:346T
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_2265e_d867b0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G5665A

4)
BA.5.1+ Orf7a:L30H+orf1b:310I+orf1b:1476S + S:346T
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_2265e_d867b0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T27482A

**Comment by FedeGueli** [comment]
@corneliusroemer there is also this one just 7 sequences but something to monitor too:
BA.5.3.1+orf1a:T568I+S:346I+Orf1a:T12I+S:613E +S:498K+Orf8:65V denmark

**Comment by FedeGueli** [comment]
@corneliusroemer By the way i was checking further S:346T also in BA.2 and there is an ongoing unexpected comeback of BA.2.40.1 +S:346T from Indonesia now as trasmissible as BA.5 (just 32 seqs but not seen in other places
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14871_ec8cc0.json?c=pango_lineage_usher&label=nuc%20mutations:G22599C

**Comment by FedeGueli** [comment]
@corneliusroemer same for this other australian undesignated branch of BA.2 with A7201G + orf1a:4005T, orf1a:4311I+S:346T showing comparable transmissibility with BA.5:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1a%3A4005T%2Corf1a%3A4311i%2CS%3A346T&nucMutations=A7201G&

https://cov-spectrum.org/explore/Australia/AllSamples/Past3M/variants?variantQuery=NextCladePangolineage%3ABa.5*&aaMutations1=orf1a%3A4005T%2Corf1a%3A4311i%2CS%3A346T&nucMutations1=A7201G&analysisMode=CompareToBaseline&

**Comment by silcn** [comment]
> @corneliusroemer there is also this one just 7 sequences but something to monitor too: BA.5.3.1+orf1a:T568I+S:346I+Orf1a:T12I+S:613E +S:498K+Orf8:65V denmark

No 498K there. It has nuc:C23054A which causes 498K on a WT background, but on top of 498R it is silent. Yet another example of Nextstrain getting confused by a 2nt mutation.

**Comment by corneliusroemer** [comment]
@silcn Is it Nextstrain getting confused or Usher giving wrong annotations?
If Nextstrain/Nextclade please give more details so I/we can fix it. For Usher this is well known I think @AngieHinrichs.

**Comment by silcn** [comment]
@corneliusroemer this is the issue of nuc mutations in a codon already containing a mutation at a different nucleotide always being labelled in the Usher tree (as displayed by Nextstrain) with their effect on a WT background. I don't know enough to tell whether the issue lies with Usher or Nextstrain.

**Comment by AngieHinrichs** [comment]
I believe it is the UShER web interface's fault, sorry about that.

**Comment by FedeGueli** [comment]
Thx @silcn i corrected that then

**Comment by corneliusroemer** [comment]
@silcn The tree produce by Usher (in auspice JSON) format is displayed by Nextstrain Auspice as served by UCSC's server.

Auspice just displays what you feed it - in this case the amino acid annotations are done by Usher when they create the tree. @AngieHinrichs since this keeps confusing people, would it be possible to fix these annotations? As long as we don't have frameshifts, it wouldn't be too hard to fix the AA mutations in a postprocessing step?

One would just need to hunt for codons with more than 1 nt mutation per codon and see if that changes anything.

**Comment by FedeGueli** [comment]
Hi @corneliusroemer i proposed this one then
https://github.com/cov-lineages/pango-designation/issues/874

**Comment by FedeGueli** [comment]
Proposed BA.2.40.1+S:346T in https://github.com/cov-lineages/pango-designation/issues/875

**Comment by FedeGueli** [comment]
Found another interesting thx to trees shared by @shay671 and @c19850727

BA.5.2.1+ S:346T ) complete route from root: BA.5.2+ Orf1a:K2589R+G26196A+orf1b:K1957R+S:346S+24079C

62 sequences

wide spread in USA

**Comment by FedeGueli** [comment]
> @corneliusroemer there is also this one just 7 sequences but something to monitor too: BA.5.3.1+orf1a:T568I+S:346I+Orf1a:T12I+S:613E + Orf8:65V + (C23054A (S:498R) EDITED thx @silcn ) in denmark

now 13 sequences from japan, greece, sweden australia too

**Comment by FedeGueli** [comment]
BE.1 + C1471T+S:346T: now 49seqs high prevalence in Costarica (i think it was a first time we see a 346X at that high levels in a country)  it was independently spotted and monitored by @ryhisner too.
I think we will propose it

**Comment by FedeGueli** [comment]
Mentioned above: BA.5.1 + Orf1a:K1407M, S:346T 
12 sequences no much growth

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1a%3AK1407M%2CS%3A346T&pangoLineage=BA.5.1&aaMutations1=S%3A339N%2CS%3A157S%2CS%3A1264M&

**Comment by FedeGueli** [comment]
Mentioned above: BA.5.1+ Orf7a:L30H+orf1b:310I+orf1b:1476S + S:346T
32 seqs (from 7)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf7a%3AL30H%2Corf1b%3A310I%2Corf1b%3A1476S%2CS%3A346T&pangoLineage=BA.5.1&aaMutations1=S%3A339N%2CS%3A157S%2CS%3A1264M&

**Comment by FedeGueli** [comment]
mentioned above:
BA.5.3.1+orf1a:T568I+S:346I+Orf1a:T12I+S:613E + Orf8:65V + (C23054A) 
11 seqs (from 7)

no much growth

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1a%3AT568I%2CS%3A346I%2COrf1a%3AT12I%2CS%3A613E%2COrf8%3A65V&nucMutations=C23054A&pangoLineage=BA.5.3.1&aaMutations1=S%3A339N%2CS%3A157S%2CS%3A1264M&

**Comment by alurqu** [comment]
> Mentioned above: BA.5.1+ Orf7a:L30H+orf1b:310I+orf1b:1476S + S:346T 32 seqs (from 7)
> 
> https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf7a%3AL30H%2Corf1b%3A310I%2Corf1b%3A1476S%2CS%3A346T&pangoLineage=BA.5.1&aaMutations1=S%3A339N%2CS%3A157S%2CS%3A1264M&

@FedeGueli I see those 32 but with a total of 7 mutations from BA.5.1: ORF1a:H417Y (C1514T), ORF1b:A1476S (G17893T), ORF1b:D1903N (G19174A), ORF1b:T310I (C14396T), ORF7a:L30H (T27482A), S:R346T (G22599C), and C10507T.

Counts: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.1+%26+ORF1a%3AH417Y+%26+ORF1b%3AA1476S+%26+ORF1b%3AD1903N+%26+ORF1b%3AT310I+%26+ORF7a%3AL30H+%26+S%3AR346T+%26+C10507T&

UShER tree constructed with GenBank data: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice1_genome_BA.5.1%2BORF1a_417Y%2BORF1b_1476S%2BORF1b_1903N%2BORF1b_310I%2BORF7a_30H%2BS_346T%2B10507T.json

I note that there are 1 sequence each from the UK and Chile in addition to 30 from across at least 15 states of the USA.

**Comment by FedeGueli** [comment]
thx @alurqu i ve trouble with usher so.if you could and want please propose it. You made a wellbetter analysis than mine!

**Comment by FedeGueli** [comment]
here another one @corneliusroemer  https://github.com/cov-lineages/pango-designation/issues/959

**Comment by FedeGueli** [comment]
> mentioned above: BA.5.3.1+orf1a:T568I+S:346I+Orf1a:T12I+S:613E + Orf8:65V + (C23054A) 11 seqs (from 7)
> 
> no much growth
> 
> https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1a%3AT568I%2CS%3A346I%2COrf1a%3AT12I%2CS%3A613E%2COrf8%3A65V&nucMutations=C23054A&pangoLineage=BA.5.3.1&aaMutations1=S%3A339N%2CS%3A157S%2CS%3A1264M&

20 sequences as today it seems spreading in Japan. I m ushering it, in the case i notice something i will propose this one.

**Comment by FedeGueli** [comment]
> Mentioned above: BA.5.1 + Orf1a:K1407M, S:346T 12 sequences no much growth
> 
> https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1a%3AK1407M%2CS%3A346T&pangoLineage=BA.5.1&aaMutations1=S%3A339N%2CS%3A157S%2CS%3A1264M&

27 sequences as today , interestingly it seems going up in Portugal , that could be interesting considering Portugal was the first hard hit country by BA.5 . Ushering it i spot something new there i will propose in a  distinct issue

**Comment by FedeGueli** [comment]
@josetteshoenma spotted BA.5.1 + S:346T+C1612T, G7294T, G28423T
10 sequences:
 https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C1612T%2CG7294T%2CG28423T%2CG22599C&nextcladePangoLineage=BA.5.1*&aaMutations1=S%3A339N%2CS%3A157S%2CS%3A1264M&

**Comment by FedeGueli** [comment]
> > Mentioned above: BA.5.1 + Orf1a:K1407M, S:346T 12 sequences no much growth
> > https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1a%3AK1407M%2CS%3A346T&pangoLineage=BA.5.1&aaMutations1=S%3A339N%2CS%3A157S%2CS%3A1264M&
> 
> 27 sequences as today , interestingly it seems going up in Portugal , that could be interesting considering Portugal was the first hard hit country by BA.5 . Ushering it i spot something new there i will propose in a distinct issue

32 seqs as today Proposing it now

**Comment by FedeGueli** [comment]
BA.5.10+ S:346T proposed : https://github.com/cov-lineages/pango-designation/issues/1031

**Comment by corneliusroemer** [comment]
This issue has served its purposes, I'll close
