### ISSUE TITLE
BA.5.1 sublineage in a branch with C26681T  defined by Orf3a:R68G and S:R346T circulating in Czechia (101 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#869]
In Czechia there is a BA.5.1 sublineage in a branch with C26681T (300+ seqs) defined by Orf3a:R68G and S:R346T:
 it counts  42 sequences ( tow of them have S:346K instead of T) spread in 10 countries but mostly in czechia (24 out of 42seqs)
![Schermata 2022-07-24 alle 20 03 06](https://user-images.githubusercontent.com/87669813/180660073-2d5bfdc1-82b8-418e-a73a-9b5652bb15be.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2280e_d86a00.json?branchLabel=aa%20mutations&c=gt-ORF3a_68&label=nuc%20mutations:C26681T

Covspectrum overview: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AR346T%2COrf3a%3AR68G&nucMutations=C26681T&variantQuery1=G22599T+%26+nextcladePangoLineage%3ABA.5+%26+C18804T+%26+T1570C&

It has apparently 12% of growth advantage vs BA.5 BAseline in Czechia (4% in Europe) during last two months:
https://cov-spectrum.org/explore/Czechia/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.5*&aaMutations1=S%3AR346T%2COrf3a%3AR68G&nucMutations1=C26681T&analysisMode=CompareToBaseline&

![Schermata 2022-07-24 alle 20 07 59](https://user-images.githubusercontent.com/87669813/180660194-91a29a45-3d75-419b-a185-fba8dd13d75f.png)

Sequences:
[contributors (2).csv](https://github.com/cov-lineages/pango-designation/files/9177168/contributors.2.csv)

_Originally posted by @FedeGueli in https://github.com/cov-lineages/pango-designation/issues/865#issuecomment-1193367605_

**Comment by FedeGueli** [comment]
It seems not growing and not having any advantage on BA.5 baseline.
I close this one while keepinf this monitored privately

**Comment by FedeGueli** [comment]
I have to reopen this one, 22new seqs are now avaible on Covspectrum 

So total counts is 70 Seqs and now local circulation is also clear  in Slovakia .
15 countries have been reached by this sublineage with new samples Italy from Italia, Netherlands, South Korea, Belgium and Sweden.
![Schermata 2022-08-07 alle 00 11 26](https://user-images.githubusercontent.com/87669813/183267562-199ce5d1-d9a6-487d-ac3c-d969ccac1703.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2079d_ee5740.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:T21704C

**Comment by InfrPopGen** [comment]
Although apparently in relative decline in Czechia, this one might be gaining some advantage elsewhere (~0.3% increase relative to parent from end of July to now, across Europe). It may be worth watching a little longer to see if this persists.
[https://cov-spectrum.org/explore/Europe/AllSamples/Past1M/variants?variantQuery=NextCladePangoLineage%3ABA.5.1*&aaMutations1=S%3AR346T%2COrf3a%3AR68G&nucMutations1=C26681T&analysisMode=CompareToBaseline&](comparison v. BA.5.1)

**Comment by FedeGueli** [comment]
@InfrPopGen 91 seqs on usher tree now, while now having been sampled in 16 countries 
in none of them seems to have started large outbreaks.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38b22_f8ee80.json?c=country&label=nuc%20mutations:A25594G

**Comment by FedeGueli** [comment]
Quick Gisaid search finds 91 viruses too : NS3_R68G, Spike_R346T

**Comment by FedeGueli** [comment]
97 viruses on Gisaid last 6 from Czechia and Slovakia and one from Croatia.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1065d_565a40.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:T21704C

**Comment by FedeGueli** [comment]
101 viruses on Gisaid : 4 new sequences from Czechia today and one from Canada  , i excluded one ba.4.6 from Usa that i erroneously counted as part of this lineage.

**Comment by corneliusroemer** [comment]
Doesn't seem to be doing much, I'd close this for now, let's reopen if this picks up.

Query: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AR346T&nucMutations=C26681T&nextcladePangoLineage=BA.5.1*&variantQuery1=G22599T+%26+nextcladePangoLineage%3ABA.5+%26+C18804T+%26+T1570C&

**Comment by FedeGueli** [comment]
Agree @corneliusroemer up and down with not  a clear trend lets see if will grow further in other countries due to summer travels as sometimes happened before for lineages emerged in Eastern Europe.

**Comment by FedeGueli** [comment]
@corneliusroemer 119 VIruses as today on Gisaid , last samples uploaded after 29th of August are from Austria, Czechia, Sweden,Netherlands Slovakia, Germany. 

just two sequences had a new acquired spike mutation : S:D568G 

I would keep this closed and monitored to see if it evolves further.

**Comment by FedeGueli** [comment]
132 sequences, last ones from Czechia, Turkey, Portugal, Tunisia via Japan, Poland.

**Comment by FedeGueli** [comment]
150 seqs as today, now in Spain , Turkey , Ireland too.

**Comment by FedeGueli** [comment]
Now designated BA.5.1.26. @corneliusroemer @InfrPopGen if you can add the milestone here so it could be easily found.
