### ISSUE TITLE
alias_key.json with withdrawn lineages

### ISSUE THREAD

**Issue by danielmoney** [cov-lineages/pango-designation#87]
Would it be possible to have a version of alias_key.json that also included withdrawn lineages?  As part of my work I'm interested in how lineage assignments change with more data and having to try to maintain different versions of this file for different datasets is tricky.  I would imagine having all possible aliases that pangolin has ever used may well be useful to other people as well.

**Comment by aretchless** [comment]
I'm currently parsing withdrawn lineages from the 'lineage_notes.txt' file, but agree that it would be convenient to have a more direct list if it's not much trouble to maintain.

**Comment by chrisruis** [comment]
I think the easiest thing is to read these aliases in from lineage_notes.txt as they are in there
