### ISSUE TITLE
New BA.5.2+Orf1b:1050N sublineage with 27012T + S:346T (157 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#870]
There is a sublineage budding off from BA.5.2 + orf1a:1050N +27012T with S:346T that shows some well defined diversity 
48 sequences 14 countries (among them Czechia 5 seqs) 4 continents 
![Schermata 2022-07-24 alle 20 13 07](https://user-images.githubusercontent.com/87669813/180660391-ab3b6d78-8143-4625-aa7f-858fa13b6fba.png)
Usher tree link:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_2280e_d86a00.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G22599C

CovSpectrum: https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?%5D%28https%3A%2F%2Fcov-spectrum.org%2Fexplore%2FWorld%2FAllSamples%2FPast3M%2Fvariants%3FaaMutations=S%3AR346T%2Corf1b%3A1050N&%29=&variantQuery=NextCladePangoLineage%3ABA.5.2+%26+S%3AR346T++%26++13136A+%26+27012T+&aaMutations1=S%3AR346T%2COrf3a%3AR68G&nucMutations1=C26681T&variantQuery1=NextCladePangoLineage%3ABA.5.2+%26+S%3AR346T+&
Sequences:
[contributors (1).csv](https://github.com/cov-lineages/pango-designation/files/9177159/contributors.1.csv)

_Originally posted by @FedeGueli in https://github.com/cov-lineages/pango-designation/issues/865#issuecomment-1193368864_

Edited: i dont think that any growth advantage can be reliable here cause every country seems to have its own well defined branch

**Comment by FedeGueli** [comment]
CC @AngieHinrichs  i was looking at he usher tree of this sublineage: in the global subsampled tree
(https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_115a2_6bf4b0.json?branchLabel=nuc%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T76A,T78G,A11537G,G22599C)
![Schermata 2022-07-31 alle 20 09 45](https://user-images.githubusercontent.com/87669813/182039623-a1a02947-524b-4ce1-86d7-203b7768da76.png)

There it is divided in 3 branches:
![Schermata 2022-07-31 alle 20 12 29](https://user-images.githubusercontent.com/87669813/182039719-e1207672-e86f-4018-8bcc-0cf688fdffdf.png)

While the "italian branch with two mutations at the start of Orf1a is a bit suspicious and i would take it out of the discussion:
(https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_115a2_6bf4a0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T78G)

the other one defined by:BA.5.2+Or1a:1050N+C27513T+C27012T +13624T+Orf1a:I4291V+S:346T 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_115a2_6bf4a0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C13264T

i dont think it is well supported to be distinct ( it is due only to the presence of France/OCC-GENBIO-C41GN1920046/2022|EPI_ISL_13986108|2022-07-11).

**Comment by AngieHinrichs** [comment]
> the other one defined by:BA.5.2+Or1a:1050N+C27513T+C27012T +13624T+Orf1a:I4291V+S:346T
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_115a2_6bf4a0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C13264T
> 
> i dont think it is well supported to be distinct ( it is due only to the presence of France/OCC-GENBIO-C41GN1920046/2022|EPI_ISL_13986108|2022-07-11).

That little cluster with C13264T also has A13136G/ORF1a:I4291V -- see [subtree 2](https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-870.subtree2.json?c=gt-nuc_13136,13264):
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/186983/182045089-92c70296-16dc-4d5e-868a-ddbf2cfd8452.png">

So although OCC-GENBIO-C41GN1920046 is the only sequence that has C13264T before G22599C/S:R346T, there are >1000 BA.5.2 sequences that have C16616A/Orf1b:1050N, C27513T, C27012T and A13136G (like that little cluster) but not G22599C/S:R346T (and C13264T).

**Comment by FedeGueli** [comment]
Ok thank you very much @AngieHinrichs so this one is different from.the proposed here, and it emerged indepently from the C16616A/Orf1b:1050N, C27513T, C27012T and A13136G  branch of BA.5.2.

So i'll.monitor separately and i will take that in account for covspectrum queries. Thx vm very precious help!

**Comment by FedeGueli** [comment]
63  seqs as today and 15 countries
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26cd3_eeb6b0.json?branchLabel=aa%20mutations&c=gt-nuc_27012&label=nuc%20mutations:G22599C
![Schermata 2022-08-07 alle 00 58 04](https://user-images.githubusercontent.com/87669813/183268435-b98d109b-aa1a-4cd0-970a-0b50d7033071.png)

**Comment by FedeGueli** [comment]
103  seqs as today

Growth advantage versus parental Orf1b:1050N in Usa:
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5.2*+%26++orf1b%3A1050N++&variantQuery1=NextCladePangoLineage%3ABA.5.2+%26+S%3AR346T+%26+Orf1b%3A1050N+%26+27012T++%26+13136A+&analysisMode=CompareToBaseline&

@InfrPopGen @corneliusroemer

**Comment by FedeGueli** [comment]
136 sequences as today: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=NextCladePangoLineage%3ABA.5.2+%26+S%3AR346T+%26+Orf1b%3A1050N+%26+27012T++%26+13136A+&variantQuery1=NextCladePangoLineage%3ABA.5.2*+%26++orf1b%3A1050N++&

**Comment by FedeGueli** [comment]
157 on Usher it is growing vey fast i think a designation could help in tracking this one. @InfrPopGen @corneliusroemer 
![Schermata 2022-08-21 alle 16 43 12](https://user-images.githubusercontent.com/87669813/185796604-db15153e-78a1-464b-90bd-7d85ec5224d1.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e5d6_244230.json?branchLabel=aa%20mutations&label=nuc%20mutations:G22599C

**Comment by FedeGueli** [comment]
CC @shay671 there is a new sublineage of this with   NSP14_V14L(orf1b:V1538L) spreading in Israel that now counts 39 sequences on Gisaid (NSP14_v14L,NSP13_T127N,)
, just 20 displayed on Usher and 7 on Covspectrum:

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=S%3AR346T+%26+orf1b%3A1050N+%26+27012T+%26+13136A%26+orf1b%3AV1538L&variantQuery1=NextCladePangoLineage%3ABA.5.2*+%26+orf1b%3A1050N&

It seems to have a large advantage over the fastest BA.5 (orf1b:1050N)

**Comment by shay671** [comment]
Just to be clear - BA.5.2.6 is defined by : S: R346T (G22599C)
and it evolved from a branch having three mutations over BA.5.2 :
C16616A
C27012T
C27513T

Is that correct?

@corneliusroemer @FedeGueli

**Comment by shay671** [comment]
@FedeGueli regarding the sub-lineage you addressed. 
I used this query to find this :
[2-of:C16616A,C27012T,C27513T]&G22599C&orf1b:V1538L

Looking at the USHER build, it seems that the closest samples to the branchpoint are from Cambodia, and those are also the ones that are the earliest sampled. The samples from Israel are all over this branch.  So, I think it's still early to call if this one has an advantage or if it is just some epidemiological event (superspreader/founder etc).
 
![image](https://user-images.githubusercontent.com/80166370/185907943-c21d7246-242b-4bca-9e2e-f966ea6ade07.png)

**Comment by FedeGueli** [comment]
> Just to be clear - BA.5.2.6 is defined by : S: R346T (G22599C) and it evolved from a branch having three mutations over BA.5.2 : C16616A C27012T C27513T
> 
> Is that correct?
> 
> @corneliusroemer @FedeGueli

Yes!

**Comment by FedeGueli** [comment]
> Looking at the USHER build, it seems that the closest samples to the branchpoint are from Cambodia, and those are also the ones that are the earliest sampled. The samples from Israel are all over this branch. So, I think it's still early to call if this one has an advantage or if it is just some epidemiological event (superspreader/founder etc).


@shay671 
The parental lineage has already a large advantage vs BA.5 baseline, comparable with BF.7 one.

**Comment by FedeGueli** [comment]
@shay671 40 sequences of the sublineage  with NSP14_V14L(orf1b:V1538L) that highlighted you 
23 out of 40 from Israel

**Comment by shay671** [comment]
I think it's worth designation

**Comment by FedeGueli** [comment]
Ok @Shay671 i'll propose it. (the parental is already designated as BA.5.2.6)
