### ISSUE TITLE
New sublineage of BA.2 + 25416T + S:I197V with N:P6L (Orf9b:P3S) growing fast in Victoria- Australia ( 17 Sequences )

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#871]
I spotted a very fast growing BA.2 sublineage spreading in VIctoria,  Australia . 
It could be a cluster cause all the samples have been taken in a few days early in July, but i think this has to be flagged to Aussie scientists.

This sublineage is on the big BA.2 branch with 25416T, the same of the fastest BA.2 lineages as BA.2.12.1 , BA.2.38 , BA.2.75 .

The route from BA.2 root is the following:
 25416T 
+ orf1a:L3829F + S:I197V (537 Sequences) 
+ A5536G (46 seqeunces) + C27741T (26 sequences) + G28774A (20 sequences) 
+ N:P6L / Orf9b:P3S =C28290T  (17 sequences).

We have already met N:P6L in AY.36.1 that super fast Delta sublineage that started to circulate in Germany during the Omicron rise showing an unprecedented growth advantage for Delta sublineages (maybe just due some epi effects during dominant variant exchange, but who knows being mutations to L at the start of N a quite solid landmark of successful variant as Alpha N:3L , AY.43  N:9L, Lambda N:13L and Omicron N:13L) .

So i prefer to flag it directly also seeing reports coming  from Victoria of a not easy epidemiological situation
(See [@Mike_Honey_](https://twitter.com/Mike_Honey_):
and specifically https://twitter.com/Mike_Honey_/status/1550728636881575937?s=20&t=nB4P1L4UUUi34Q_XRiGZRA)

Tree:
![Schermata 2022-07-25 alle 03 55 19](https://user-images.githubusercontent.com/87669813/180678341-5ac98655-aa59-4766-97e9-7fa1e22cd216.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3199c_c66b50.json?branchLabel=aa%20mutations&c=gt-N_6&label=nuc%20mutations:A22151G
![Schermata 2022-07-25 alle 03 56 03](https://user-images.githubusercontent.com/87669813/180678407-677f1b59-8413-4b55-95ea-0829e7bbe79d.png)

CovSpectrum overview: 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A197V%2CN%3A6L&nucMutations=25416T&pangoLineage=BA.2&aaMutations1=S%3A197V%2Corf9b%3AP3S&pangoLineage1=BA.2&

Nr of sequences: 17
Country : all from Victoria Australia
List:
[contributors (4).csv](https://github.com/cov-lineages/pango-designation/files/9177315/contributors.4.csv)

Provisional Growth advantage vs BA.5* baseline ( note that both the CIs are with a +)
I do think this could be taken and reduced by 1 order of magnitude (10x) that is the so called cluster effect ,but still it would be another BA.2 comeback after the emerging Indian sublineages.
![Schermata 2022-07-25 alle 03 58 27](https://user-images.githubusercontent.com/87669813/180678600-4b131af3-5acf-4f54-816a-928210c69bba.png)
https://cov-spectrum.org/explore/Australia/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.5*&aaMutations1=S%3A197V%2CN%3A6L&nucMutations1=25416T&pangoLineage1=BA.2&analysisMode=CompareToBaseline&

Note that the parental BA.2+S:197V has a growth disadvantage superior to 50% vs BA.5
https://cov-spectrum.org/explore/Australia/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5*&aaMutations1=S%3A197V&nucMutations1=25416T&pangoLineage1=BA.2&analysisMode=CompareToBaseline&

**Comment by corneliusroemer** [comment]
17 seqs is very few - let's for more sequences

**Comment by FedeGueli** [comment]
Luckily it seems it has been just a cluster. i will monitor it privately. closing this issue.
