### ISSUE TITLE
BA.5.5 sublineage with S:N450D (201 seq. on Usher as of 08.08.2022)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#873]
Proposal for a sublineage of BA.5.5
Earliest sequence: 04.06.2022 (USA)
Countries detected:  mostly USA, UK, Israel, Germany, Mexico, Austria

Defining mutation:
A22910G = S:N450D

This variant is defined by S:N450D and was first detected in USA. Now it is present in five other countries across two continents (105 seq on Usher as of 25.07.22).

Apparently there is a lot of convergent evolution taking place with regards to S:N450D as this mutation is concurrently arising in multiple "distant" BA.2 (#851, #772, #812, #814) and BA.5 (#843) lineages.

![grafik](https://user-images.githubusercontent.com/102166254/180759719-26538bbc-e798-45af-9d0d-f92c400bdfbc.png)
![grafik](https://user-images.githubusercontent.com/102166254/180761092-91340f23-bcf7-48e3-ac7b-10e70be14eb4.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_f847_e6e070.json?branchLabel=aa%20mutations&c=gt-S_450&label=nuc%20mutations:C241T,T670G,C2790T,C3037T,G4184A,C4321T,C5512T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,C21789T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,C27807T,C27889T,G28077T,A28271T,C28311T,G28881A,G28882A,G28883C,A29510C

![grafik](https://user-images.githubusercontent.com/102166254/180759234-243ff3bb-52bb-485b-9453-623575e83322.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AN450D&pangoLineage=BA.5.5*&aaMutations1=S%3AN450D&pangoLineage1=BA.5.5*&

Growth advantage vs. global BA.5 3 months:

![grafik](https://user-images.githubusercontent.com/102166254/180758998-61db0aed-ac81-4ed6-8957-5456e2e6176d.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.5*&aaMutations1=S%3AN450D&pangoLineage1=BA.5.5*&analysisMode=CompareToBaseline&

EPI_ISL_13506373, EPI_ISL_13652736, EPI_ISL_13698975, EPI_ISL_13699132, EPI_ISL_13699147, EPI_ISL_13699160, EPI_ISL_13701629, EPI_ISL_13729798, EPI_ISL_13730206, EPI_ISL_13730999, EPI_ISL_13731890, EPI_ISL_13732441, EPI_ISL_13732447, EPI_ISL_13732902, EPI_ISL_13746051, EPI_ISL_13747745, EPI_ISL_13747752, EPI_ISL_13747764, EPI_ISL_13747772, EPI_ISL_13749827, EPI_ISL_13774413, EPI_ISL_13813349, EPI_ISL_13821038, EPI_ISL_13831141, EPI_ISL_13834766, EPI_ISL_13887981, EPI_ISL_13888394, EPI_ISL_13889785, EPI_ISL_13895577, EPI_ISL_13895607, EPI_ISL_13895650, EPI_ISL_13895730, EPI_ISL_13895835, EPI_ISL_13897422, EPI_ISL_13915374, EPI_ISL_13959842, EPI_ISL_13963207, EPI_ISL_13963746, EPI_ISL_14006093, EPI_ISL_14010254, EPI_ISL_14019464

ON765849.1, ON824471.1, ON867880.1, ON917879.1, ON918247.1, ON918423.1, ON918425.1, ON939869.1, ON942132.1, ON948098.1, ON948427.1, ON949452.1, ON949696.1, ON957545.1, ON966155.1, ON968270.1, ON977742.1, ON977757.1, ON978015.1, ON978017.1, ON990963.1, ON990973.1, ON991270.1, ON999612.1, ON999916.1, OP000493.1, OP009551.1, OP010133.1, OP013632.1, OP013772.1, OP014332.1, OP015030.1, OP015278.1, OP015594.1, OP016762.1, OP018010.1, OP026371.1, OP026634.1, OP026670.1, OP027373.1, OP027553.1, OP027716.1, OP027858.1, OP034538.1, OX157368.1, OX189639.1, OX221847.1, OX221897.1, OX223919.1, OX231270.1, OX231424.1, OX231442.1, OX231816.1, OX242786.1

**Comment by FedeGueli** [comment]
Hi @agamedilab the route from BA.5.5 root is C5512T then Orf8:V62L then S:450D 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2b938_f122b0.json?branchLabel=aa%20mutations&label=nuc%20mutations:C21789T
![Schermata 2022-07-26 alle 00 10 45](https://user-images.githubusercontent.com/87669813/180882403-0e0d375c-61df-4deb-80c6-a244781129be.png)

**Comment by agamedilab** [comment]
@FedeGueli many thanks for spotting this! You are right, the S:N450D clade is apparently a sublcade of the G28077T (ORF8:V62L) clade.

![grafik](https://user-images.githubusercontent.com/102166254/180934062-bdc02054-e40b-4088-8e13-8d0fe10b2129.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f860_f7f9a0.json?branchLabel=nuc%20mutations&c=gt-nuc_28077,22910&label=nuc%20mutations:C241T,T670G,C2790T,C3037T,G4184A,C4321T,C5512T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,C21789T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,C27807T,C27889T,A28271T,C28311T,G28881A,G28882A,G28883C,A29510C

**Comment by agamedilab** [comment]
140 seq. on Usher as of 01.08.22.

![grafik](https://user-images.githubusercontent.com/102166254/182086759-2989c1b6-89ea-4ba7-b764-2c48fb74437e.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_5bae_76cca0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A22910G

**Comment by chrisruis** [comment]
Thanks @agamedilab As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations.

There doesn't seem to be a clear epidemiological event associated with this clade as there isn't a clear change in geographical location and the proportion of BA.5.5 sequences in this clade in the USA appears to have plateaued currently:
![image](https://user-images.githubusercontent.com/47785131/182181236-959a9889-fa5d-4677-9208-e13b2f357d6a.png)

We therefore haven't designated this at this point

**Comment by agamedilab** [comment]
Good morning @chrisruis, dont you think it is a bit early to shut this down? 

As @corneliusroemer noted the lineage carries with S:N450D a potential "mutation of interest". 

Also the proposal is only a week old and the clade grew by 33% during the last 7 days (from 105 to 140 genomes on Usher). 
Now it is present in 10 countries: 
![grafik](https://user-images.githubusercontent.com/102166254/182309167-2031ad61-a2bc-49dc-b2a6-22b482363b15.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_30d10_8c4430.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A22910G

Likewise the sublineage has still a growth advantage over BA.5.5 also in the US:

![grafik](https://user-images.githubusercontent.com/102166254/182304197-f58acd5a-1e36-4df3-b024-91d9fb06415a.png)
https://cov-spectrum.org/explore/United%20States/AllSamples/Past6M/variants?pangoLineage=BA.5.5*&aaMutations1=S%3AN450D&pangoLineage1=BA.5.5*&analysisMode=CompareToBaseline&

Therefore i dont see the urgency of shutting this down (or the harm of letting it run a little longer). Anyway i will continue to monitor the lineage and provide updates if need be.

**Comment by FedeGueli** [comment]
S:450D seems one of the few spike mutations to add some apparent advantage to BA.5 beyond 346X 444X and 460X

**Comment by agamedilab** [comment]
GISAID ermerging variant analysis 02.08.22.

![grafik](https://user-images.githubusercontent.com/102166254/182373271-0855eaa2-72a6-4b2e-9465-ecc5a0c21050.png)

**Comment by chrisruis** [comment]
Please feel free to reopen if there's an epidemiological event associated with this in the future

**Comment by corneliusroemer** [comment]
I do agree that this sublineage seems to have a growth advantage over BA.5.5* but with 140 sequences this could still be an artefact so I think we should monitor and designate if the growth advantage becomes more stably positive.

Right now, most growth seems to be in Arizona in the US. US sequences loads so we should know in a week or two. I'll reopen and tag with `monitor` (I don't think OP can reopen if it was closed by a maintainer)

**Comment by agamedilab** [comment]
201 seq. on Usher as of 08.08.2022.

![image](https://user-images.githubusercontent.com/102166254/183356273-bb5a3d19-ef20-41b8-a9ff-ea6ee8a9b2e2.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31e3f_af050.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22910G

Growth advantage vs. BA.5.5 global 6 months:
![image](https://user-images.githubusercontent.com/102166254/183355688-5f2768c2-b0ee-4de9-8efa-c88c63954592.png)
![image](https://user-images.githubusercontent.com/102166254/183355738-474ddbd4-db80-4b84-9a3a-c4d64ac6a453.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AN450D&pangoLineage=BA.5.5*&aaMutations1=S%3AN450D&pangoLineage1=BA.5.5*&

Growth advantage vs. BA.5.5 USA 6 months:
![image](https://user-images.githubusercontent.com/102166254/183356139-5ef7b742-a48d-4170-8d0d-bc9e2f900adc.png)

Growth advantage vs. BA.5.5 Europe 6 months:
![image](https://user-images.githubusercontent.com/102166254/183356019-265f1dc7-6aa9-4ae3-bfad-993a58a5d640.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.5.1 with 93 newly designated sequences. Defining mutation A22910G (S:N450D).
