### ISSUE TITLE
Fast and internationally widespread  BA.2.36 sublineage with S:R346T circulating in Australia but likely emerged in some downsampled area (100 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#874]
Here i want to propose a sublineage of BA.2.36 (S:I68T) defined by A7201G  Orf1a:A4005T and Orf1a:T4311I that gained another spike mutation: S:R346T and then it is showing trasmissibility comparable to BA.5 baseline since.

I think i have found this one after @silcn highlighted in an old issue that Japanese airport genomic surveillance had detected some sequences with S:346T not belonging to any of the proposed/designated ones.

The thing that hits me of this sublineage ( beyond the comparable trasmissibility with BA.5, that could represent the first 2nd gen BA.2 comeback after the well discussed and described BA.2s sublineages from India)
is its international spread with several samples whuch make me think to airport surveillance ( As Japanese, South Korea, Bahrain, Israel shown below):
![Schermata 2022-07-26 alle 00 35 05](https://user-images.githubusercontent.com/87669813/180885601-00ba8b1d-cae8-4543-b7a1-5be35db8e08d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2dc5f_f13070.json?branchLabel=aa%20mutations&c=country

Not having access to Gisaid i would ask kindly some help from @c19850727 @silcn @shay671 to verify if 
"Japanese [contributors (2).csv](https://github.com/cov-lineages/pango-designation/files/9185187/contributors.2.csv)

SouthKorean [contributors (3).csv](https://github.com/cov-lineages/pango-designation/files/9185195/contributors.3.csv)

Israelian [contributors (4).csv](https://github.com/cov-lineages/pango-designation/files/9185200/contributors.4.csv)

or HongKong ( HongKong/HK-HKPU-PUU038369892/2022|EPI_ISL_13694153)"

sequences are from airport surveillance and from which countries.

Covspectrum overview:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1a%3A4005T%2Corf1a%3A4311i%2CS%3A346T&nucMutations=A7201G&
First sequence:BHR/5902364720_S19_L001/2022|ON606157.1|2022-05-05
List of Sequences (all countries):
[contributors (5).csv](https://github.com/cov-lineages/pango-designation/files/9185211/contributors.5.csv)
Countries:

Country | Total Variant Sequences | First seq. found at | Last seq. found at
-- | -- | -- | --
Australia | 18 | 2022-21 | 2022-27
Denmark | 8 | 2022-24 | 2022-27
France | 4 | 2022-21 | 2022-27
Germany | 2 | 2022-24 | 2022-26
India | 3 | 2022-23 | 2022-25
Indonesia | 1 | 2022-20 | 2022-20
Israel | 15 | 2022-21 | 2022-25
Italy | 3 | 2022-27 | 2022-27
Japan | 12 | 2022-17 | 2022-25
Mexico | 1 | 2022-27 | 2022-27
New Zealand | 6 | 2022-20 | 2022-27
Norway | 2 | 2022-22 | 2022-23
Pakistan | 7 | 2022-22 | 2022-25
South Korea | 2 | 2022-22 | 2022-23
Spain | 4 | 2022-22 | 2022-25
Sweden | 2 | 2022-24 | 2022-24
United Kingdom | 1 | 2022-22 | 2022-22
United States | 2 | 2022-23 | 2022-24

In Australia where it has been circulating locally its growth disadvantage vs BA.5 is very slight:
![Schermata 2022-07-26 alle 00 47 06](https://user-images.githubusercontent.com/87669813/180886838-9f0bec18-796b-42bb-a196-97bedbbaedf8.png)
https://cov-spectrum.org/explore/Australia/AllSamples/Past3M/variants?variantQuery=NextCladePangolineage%3ABa.5*&aaMutations1=orf1a%3A4005T%2Corf1a%3A4311i%2CS%3A346T&nucMutations1=A7201G&analysisMode=CompareToBaseline&

Elsewhere it seems more evident around -35% (Japan,Israel) but this count could represent the importation rate  rather than real transmissibility .

Anyway i think this has to be highlighted and monitored publicly due the double S mutant S:68T S:346T that confers some chance to compete with BA.5  and more importantly it would be important to check if it has or had a relevant prevalence in some undersampled area. ( There are a couple of seqs from India i cant exclude it came from there too)

**Comment by silcn** [comment]
Yes, quite a few sequences from travellers, mostly from Pakistan. Also a handful from Maldives, USA, Vietnam.

**Comment by FedeGueli** [comment]
Thx very much @silcn so maybe Pakistan could be a good candidate as main' reservoir' of this sublineage , also ause it has been sampled directly in Pakistan.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.36.1 with 68 newly designated sequences, and 1 updated designations from BA.2. Defining mutation G22599C (S:R346T), preceded by node with A7201G, G12278A (ORF1a:A4005T), C13197T (ORF1a:T4311I).

**Comment by FedeGueli** [comment]
Thanks @InfrPopGen i would like just tonhifhlight that there is a recent cluster of BA.2.36.1 in Pakistan carrying additional spike S:N354K mutation, 5 sequences all from the end of June.
Being Pakistan a likely place where this lineage emerged (thx @silcn for checking it) i will put that under monitoring.

**Comment by AngieHinrichs** [comment]
Uh-oh -- before that node with A7201G, G12278A (ORF1a:A4005T), C13197T (ORF1a:T4311I) is a node with T22792C -- a reversion on C22792T.  Unfortunately it looks like a branch of BA.2 > T21765C (S:I68T) sequences, including lineages BA.2.55 and BA.2.42, got moved to BA.2 > C22792T > T21765C > T22792C.  🙁  

So either the reversion on 22792 is real and BA.2.55 and BA.2.42 are actually BA.36.X, or (more likely in my opinion) the placement of the branch with the reversion is a tree-building error and the new lineage is another BA.2.x (BA.2 > T21765C > ... .)

Here's how it looks currently, coloring by 22792 in taxonium (green=T like BA.2.36, orange=C like BA.2 root), with a black circle around the root node of this lineage:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/186983/181352631-792523f5-d7a7-442c-9014-847eafddac28.png">

Sorry about that, I will look into fixing it in the tree.

22792 looks pretty flaky in BA.2 in general, i.e. it flickers on and off in many places in both the big branch that has C22792T and the rest of BA.2 that doesn't.  Hypermutable?  Amplicon dropout?  Dunno.

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs i noticed that BA.2.55 and BA..2.42 were moved as BA.2.36 sublineages i didnt want to bother you and other committee member so i didnt highlight that in this issue.
But yes what you are saying is true probably without that reversion BA.2.42/BA.2.55/BA.2.36.1 will become independent lineages which all acquired S:68T.
And i strongly favour this hypothesis also cause when me and @corneliusroemer after being sollecited by a tweet of 
@olias12061976 started to look at S:I68T we found more than a dozen S:I68T independent sublineages . So or we  were got wrong by the same 22792 thing or the tree is wrong now.

**Comment by AngieHinrichs** [comment]
> i didnt want to bother you and other committee member

Oh please do, it's very helpful when you notice problems in the tree!  It's helpful for me so I can try to fix the tree, and it's helpful for others so they know to be skeptical of some branches in the tree.

**Comment by FedeGueli** [comment]
Oke! @AngieHinrichs next time i ll do for sure.

**Comment by InfrPopGen** [comment]
This lineage has been redesignated as BA.2.82 (and BA.2.36.1 withdrawn).
