### ISSUE TITLE
FAst BA.2.40.1 sublineage with S:346T emerged and spread from Indonesia (33seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#875]
I was checking further S:346T also in BA.2 and there is an ongoing unexpected comeback of
BA.2.40.1  (S:417T+orf1B:2070H) sublineage  with S:346T likely emerged and spread from Indonesia.

Now it appears as trasmissible as BA.5 (just 32 seqs so take this with a big grain of salt):
![Schermata 2022-07-26 alle 01 11 01](https://user-images.githubusercontent.com/87669813/180889819-19a80371-2f22-45f1-9c81-b8f941affdc3.png)

https://cov-spectrum.org/explore/Indonesia/AllSamples/Past2M/variants?variantQuery=NextCladePangolineage%3ABa.5*&aaMutations1=S%3A346T%2CS%3AK417T%2COrf1B%3A2070H&analysisMode=CompareToBaseline&

Usher tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14871_ec8cc0.json?c=pango_lineage_usher&label=nuc%20mutations:G22599C
![Schermata 2022-07-26 alle 01 10 43](https://user-images.githubusercontent.com/87669813/180889786-cf017275-a218-4e23-be52-67bdd0210637.png)

CovSpectrum Overview:https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A346T&pangoLineage=BA.2.40.1&

Countries: Indonesia, Japan, France, Ireland, Scotland, Luxembourg, Germany, England, Usa
First sequence: Indonesia/JK-GS-GSILab-1065454/2022|EPI_ISL_13424113|2022-04-23
Nr of Sequences: 33
List of sequences:
[contributors (6).csv](https://github.com/cov-lineages/pango-designation/files/9185324/contributors.6.csv)

_Originally posted by @FedeGueli in https://github.com/cov-lineages/pango-designation/issues/865#issuecomment-1194342300_

**Comment by FedeGueli** [comment]
Under suggestion of @corneliusroemer i clarify that i put the growth advantage screenshot here to highlight something weird, it is very unlikely it really is as competitive as BA.5, anyway being Indonesia a not well sampled country and being very hard for any BA.2 lineage to keep a comparable growth rate of BA.5 in any country of the world i think it is a duty highlight that and monitor then publicly. It could be nothing just a coincidence biased by multiple factors , still when i see something unusual correlated with a mutation of interest i prefer after monitoring privately for a while to make it public then.

**Comment by alurqu** [comment]
@FedeGueli See [Issue 766](https://github.com/cov-lineages/pango-designation/issues/766) for a suggestion on how to make your UShER tree data more durably available.

**Comment by FedeGueli** [comment]
@alurqu yes i know that thx. i keep trees update in comment usually.

**Comment by FedeGueli** [comment]
36 Sequences as today a newly found in Spain.
this last sequences clusters with other from United Kingdom highlighting likely recent local circulation at very low levels.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21d3c_ee67f0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:G22599C

I'll close this for now keeping it monitored if it further evolves somewhere
