### ISSUE TITLE
Potential BA.2 sublinage with E:S50G, ORF3a:T268M, ORF1a:T4159I, and S:L212S in Europe, North America, and Israel (121 Seq. as of 2022-07-27) 

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#879]
There may be a BA.2 sublineage with E:S50G (nucleotide A26392G), ORF3a:T268M (nucleotide C26195T), ORF1a:T4159I (nucleotide C12741T), and S:L212S (nucleotide T22197C) first detected in the Netherlands that grew in the USA and also spread elsewhere in Europe, Latin America, and Israel.

Note that the "pango_designation" column in Nextstrain's metadata output shows some of the GenBank sequences as [BA.2.50](https://github.com/cov-lineages/pango-designation/issues/641), but the "Nextclade_pango" column in Nextstrain's metadata output and UShER output (both in the attached [zip file](https://github.com/cov-lineages/pango-designation/files/9202580/Support_BA.2%2BE_50G%2BORF1a_4159I%2BORF3a_268M%2BS_212S.zip)) show them all as BA.2, so designation of this lineage may improve recognition of BA.2.50.

As of 27 July 2022, Cov-Spectrum reports 121 BA.2+E:S50G+ORF1a:T4159I+ORF3a:T268M+S:L212S sequences (with 103 from the USA):
![BA 2+E_50G+ORF1a_4159I+ORF3a_268M+S_212S_Counts](https://user-images.githubusercontent.com/88959107/181343868-1531209a-d413-49f5-8371-e98eb94054f2.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=E%3AS50G%2CORF3a%3AT268M%2CORF1a%3AT4159I%2CS%3AL212S&pangoLineage=BA.2&

Cov-Spectrum calculates a growth advantage of 23% compared to BA.2* in the USA:
![BA 2+E_50G+ORF1a_4159I+ORF3a_268M+S_212S_Growth_vs_BA 2_USA](https://user-images.githubusercontent.com/88959107/181343950-cd72e88b-77e5-49ff-abd1-cad274fc46b9.png)
Source: https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?aaMutations1=E%3AS50G%2CORF3a%3AT268M%2CORF1a%3AT4159I%2CS%3AL212S&pangoLineage1=BA.2&pangoLineage=BA.2*&analysisMode=CompareToBaseline&

UShER shows all of the GenBank samples are on a single subtree:
![BA 2+E_50G+ORF1a_4159I+ORF3a_268M+S_212S_UShER](https://user-images.githubusercontent.com/88959107/181344587-3d802b52-27a1-4b08-8292-7806469ea142.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice1_genome_BA.2%2BE_50G%2BORF1a_4159I%2BORF3a_268M%2BS_212S.json

First Outbreak.info sequence: Netherlands 28 March 2022

First GenBank sequence: Pennsylvania USA 15 April 2022 

Most Recent GenBank sequences: Iowa USA and California USA 28 June 2022

Most Recent Outbreak.info sequence: New Jersey USA 2 July 2022

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at [Support_BA.2+E_50G+ORF1a_4159I+ORF3a_268M+S_212S.zip](https://github.com/cov-lineages/pango-designation/files/9202580/Support_BA.2%2BE_50G%2BORF1a_4159I%2BORF3a_268M%2BS_212S.zip)

Outbreak.info's Situation Report for this potential lineage is https://outbreak.info/situation-reports?pango=BA.2&muts=E%3AS50G&muts=ORF3a%3AT268M&muts=ORF1a%3AT4159I&muts=S%3AL212S&overlay=false

**Comment by alurqu** [comment]
This sublineage likely also includes synonymous nucleotide mutation A7210G, and most of the phylogenetic subtree also has synonymous nucleotide mutation C23114T.

**Comment by FedeGueli** [comment]
@alurqu this sublineage has an interesting profile but it is very far as growth rate from the current dominant variant BA.5.2*.
https://cov-spectrum.org/explore/United%20States/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.5.2*&aaMutations1=E%3AS50G%2CORF3a%3AT268M%2CORF1a%3AT4159I%2CS%3AL212S&analysisMode=CompareToBaseline&

we tracked a lot of S.212 mutated BA.2 lineages earlier back this spring (and it was very time expensive! a real mess) and i think some have been designated too, it was one of the most frequent mutation popping up in the BA.2 post wave era and quite clearly increasing  transmissibility from the baseline. 
But still all of them were and are very far from competing vs BA.4 and BA.5. 
While it is quite always correct to describe and propose here circulating lineages with relevant mutations think we are seeing a lot of competitive lineages clashing well above the baseline i set in the query above

**Comment by alurqu** [comment]
While this lineage demonstrated a growth advantage over BA.2, as @FedeGueli pointed out it is not competitive against lineages like BA.5.  In recognition of this, I'm closing this issue.  I've also enhanced my search pipeline to rate potential Omicron lineages by estimated growth advantage over all Omicron lineages; note that for this purpose my search pipeline considers all Omicron-Delta and Omicron-Omicron recombinants to be Omicron lineages.
