### ISSUE TITLE
Potential BA.4/BA.5 recombinant with likely breakpoint between ORF6 and ORF7b, or BA.4 lineage missing ORF7b:L11F and N:P151S (65 sequences as of 2022-07-27, mostly USA)

### ISSUE THREAD

**Issue by emily-smith1** [cov-lineages/pango-designation#882]
### Description

**Recombinant between:** BA.4 & BA.5
**Earliest sequence:** 2022-05-27 (USA-NJ)
**Most recent sequence:** 2022-07-20 (Chile)
**Countries circulating:** USA, Canada, Mexico, Australia, Chile, Colombia, France
**Likely breakpoint:** 27,385-27,787 (based on presence of ORF6:D61L and lack of ORF7b:L11F)

I haven’t found an easy way to query these yet but I’ve attached a file with the IDs from the UShER tree. I'd appreciate any insight into whether this is a true recombinant lineage or whether this could be a BA.4 sublineage missing those two mutations. 

### Evidence

UShER tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_268f6_18e430.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C27945T

![image](https://user-images.githubusercontent.com/84812104/181368606-3c4060b5-dd08-4221-aea3-399fb300ddcc.png)

![image](https://user-images.githubusercontent.com/84812104/181369939-391b4589-b00c-4091-8481-89c040b6c964.png)

Thanks to @AngieHinrichs for helping investigate these!

[BA4s_missing_ORF7bL11F_NP151S_2022-07-27.txt](https://github.com/cov-lineages/pango-designation/files/9203435/BA4s_missing_ORF7bL11F_NP151S_2022-07-27.txt)

**Comment by FedeGueli** [comment]
Could be a recombinant with BA.2.12.1?
the branch with orf8:18* circulating in US?

https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?aaMutations=orf8%3AQ18*%2Corf7b%3A15A&nucMutations=27945T&pangoLineage=BA.2.12.1*&

**Comment by FedeGueli** [comment]
or BA.2.65 (with orf8:18* and 27945T)?
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?aaMutations=orf8%3AQ18*%2Corf7b%3A15A&nucMutations=27945T&pangoLineage=BA.2.65*&

**Comment by silcn** [comment]
@FedeGueli good shout. I think this is actually BA.5/BA.2: it's missing the deletion in nsp1 that BA.4 has. Breakpoint is somewhere between 23040 (S:493) and 26529 (M:3). There are a few independent lineages with ORF8:Q18* that could be the BA.2 donor.

**Comment by FedeGueli** [comment]
Thx @silcn!

**Comment by emily-smith1** [comment]
There are now 83 genomes from 8 countries in the UShER subtree.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/84812104/182689897-5b44a130-42b3-4aa8-934b-7df07ee5754f.png">

**Comment by emily-smith1** [comment]
Now 120 genomes from 9 countries.

UShER link: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ec3d_2dc7a0.json?branchLabel=aa%20mutations&c=country
<img width="1459" alt="Screen Shot 2022-08-09 at 6 24 51 PM" src="https://user-images.githubusercontent.com/84812104/183772413-63031dc8-2d4e-4867-8e85-6bec51cc3bd7.png">

**Comment by emily-smith1** [comment]
126 genomes total, newly found in Israel.

UShER link: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_32f5c_56d8e0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C27945T

<img width="798" alt="image" src="https://user-images.githubusercontent.com/84812104/184246303-44423d2e-2907-46fb-8ce8-d39848976bc9.png">

**Comment by emily-smith1** [comment]
Now 149 genomes from 11 countries. 

UShER link: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a962_baca00.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C27945T
![image](https://user-images.githubusercontent.com/84812104/184911382-8ef7b9d2-64cc-464a-a20d-2f17f7e00c56.png)

**Comment by emily-smith1** [comment]
168 genomes total, with collection dates now through 2022-08-08. 

UShER link: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40934_f93370.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C27945T

<img width="1459" alt="Screen Shot 2022-08-19 at 8 25 28 AM" src="https://user-images.githubusercontent.com/84812104/185653128-63e175ba-05b4-4bab-b468-7d14d1f2b68d.png">

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAS with 45 newly designated sequences, and 3 updated designations from BA.4.
