### ISSUE TITLE
New BA.5.2.1 sublineage with S:346S circulating in USA  (121 Seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#883]
Thx to @shay671 and @c19850727 who first spotted a " creepy sequence" (=with heavily mutated spike) in this tree i identified a new growing sublineage of the high transmissible BA.5.2.1 branch  characterized by S:346S mutation.

It is defined by the following mutations:
Orf1a:K2589R 
then G26196A 
then Orf1b:K1957R 
then S:346S+24079C

Tree is already showing quite interesting diversity suggesting a more sustained circulation than what could be seen by number of sequences (62)
Tree:
![Schermata 2022-07-28 alle 08 03 37](https://user-images.githubusercontent.com/87669813/181432106-f6cdd4bd-a697-4b13-9d97-5457534382f8.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_208e_1d1ea0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A8031G

CovSpectrum finds just 40 sequences in just 3 countries but this sublineage is mainly from US: 
[contributors (6).csv](https://github.com/cov-lineages/pango-designation/files/9205886/contributors.6.csv)

Covspectrum overview
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?variantQuery=NextcladePangoLineage%3ABA.5.2.1*+%26+Orf1a%3AK2589R+%26+G26196A+%26+Orf1b%3AK1957R+%26+S%3A346S+%26+24079C&aaMutations1=S%3A346S&nucMutations1=28330G&

Relative Growth advantage vs BA.5.2.1 baseline in Usa in the last two months from sequences ratio between the two:
![Schermata 2022-07-28 alle 08 12 29](https://user-images.githubusercontent.com/87669813/181433360-5c8095a8-ebc7-4fad-8e2b-8b7901a2cd71.png)
Link to Growth Advantage tool:
https://cov-spectrum.org/explore/United%20States/AllSamples/Past2M/variants?variantQuery=NextcladePangoLineage%3ABA.5.2.1*+&variantQuery1=NextcladePangoLineage%3ABA.5.2.1*+%26+Orf1a%3AK2589R+%26+G26196A+%26+Orf1b%3AK1957R+%26+S%3A346S+%26+24079C&analysisMode=CompareToBaseline&

cc @corneliusroemer in #865

**Comment by FedeGueli** [comment]
69 seqs as today

**Comment by FedeGueli** [comment]
114 Sequences as today and keeping its growth advantage vs BA.5 baseline

@corneliusroemer @chrisruis @InfrPopGen maybe this one is to monitor closely.
(See NY State in the comparison tool:
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5*&aaMutations1=Orf1a%3AK2589R%2Corf1b%3AK1957R%2CS%3A346S&nucMutations1=G26196A%2C24079C&analysisMode=CompareToBaseline&)

**Comment by FedeGueli** [comment]
121 sequences displayed on Usher as today:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_f4c3_ed7ca0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A8031G

It is still mainly a New York (state) sublineage even if i would not define simply a cluster: there are already 6 main branches representing together 75% of samples of this sublineage:
![Schermata 2022-08-06 alle 23 13 33](https://user-images.githubusercontent.com/87669813/183266211-f8f99fcd-c10f-4d27-bfb7-853667368b9b.png)

**Comment by corneliusroemer** [comment]
This deserves designation now - it has tripled in numbers in 2 weeks and growth advantage over BA.5.2.1 is stably positive.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.13 with 29 newly designated sequences, and 7 updated designations from BA.5.2.1. Defining mutation(s) A22600T (S:R346S).

**Comment by agamedilab** [comment]
Hi @InfrPopGen, many thanks but I think BF.13 was already designated by @aq-sun (see #843). However #843 is lacking the "designated" label, milestone. Many thanks!

**Comment by chrisruis** [comment]
Thanks @agamedilab I think the easiest thing to do here is keep the lineage in this issue as BF.13 and update the #843 lineage to BF.14 as that one isn't in lineages.csv and lineage_notes.txt yet. That should appear shortly!
