### ISSUE TITLE
Potential recombinant between BA.2.3.13 and BA.1* (67 seqs as of 2022-07-29 in Japan) 

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#885]
### Description
**Recombinant between**: BA.2.3.13 and BA.1*
**Earliest sequence**: 2022/03/14 (Japan)
**Most recent sequence**: 2022/07/13 (Japan)
**Countries circulating**: Japan only
**Likely breakpoint**: between ORF3a and M protein (26062-26528)
**Mutations on branch**: C10277T (ORF1a:L3338F), C19317T

**Conserved Nuc mutations**:
![image](https://user-images.githubusercontent.com/86835836/181675345-34a179c8-1548-44b3-92a9-e872ba0f4747.png)
**Cov-spectrum query**: C10277T, C19317T, C26060T, C29510A
**GISAID query**: NS3_L140F, M_D3G, -N_S413R, NSP1_S135R, NS3_T223I, NSP5_L75F

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/181675505-753a36d8-5b2b-43af-9973-dd5e929095ba.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_7930_34df70.json?branchLabel=aa%20mutations&c=gt-nuc_19317&label=nuc%20mutations:C10277T,C19317T

The latest circulating sub-branch (those sampled in July) has some additional amino changes: S:L5F, S:T323I, ORF1a:R171C, N:Q408L.

### Genomes:
EPI_ISL_12750364, EPI_ISL_12940800, EPI_ISL_12952452, EPI_ISL_12987630, EPI_ISL_12991498, EPI_ISL_12991506, EPI_ISL_13045378, EPI_ISL_13156673, EPI_ISL_13204263, EPI_ISL_13205839, EPI_ISL_13211515, EPI_ISL_13212013, EPI_ISL_13212047, EPI_ISL_13212293, EPI_ISL_13212667, EPI_ISL_13214088, EPI_ISL_13214195, EPI_ISL_13216844, EPI_ISL_13390345, EPI_ISL_13445285, EPI_ISL_13457178, EPI_ISL_13575794, EPI_ISL_13576299, EPI_ISL_13692287-13692288, EPI_ISL_13708994, EPI_ISL_13952119-13952120, EPI_ISL_13953691-13953692, EPI_ISL_14081722, EPI_ISL_14092593, EPI_ISL_14096069, EPI_ISL_14101431, EPI_ISL_14101452, EPI_ISL_14103253, EPI_ISL_14107951, EPI_ISL_14108199, EPI_ISL_14108826, EPI_ISL_14108902, EPI_ISL_14109092, EPI_ISL_14109095, EPI_ISL_14110034-14110035, EPI_ISL_14110409, EPI_ISL_14112097, EPI_ISL_14112128, EPI_ISL_14112143, EPI_ISL_14112147-14112148, EPI_ISL_14112164, EPI_ISL_14112411, EPI_ISL_14113425, EPI_ISL_14114788

**Comment by c19850727** [comment]
61 sequences as of 2022-07-09.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAT with 74 newly designated sequences, and 0 updated designations.
