### ISSUE TITLE
BA.5.2.1 sublineage with S:Y248H (96 seq as of 2022-08-15, ~25%(?) in Sri Lanka)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#893]
Proposal for a sublineage of BA.5.2.1 (edit: in fact a sublineage of #932 proposed by @FedeGueli)
Earliest sequence: 2022-06-16 (USA)
Countries detected: Australia (13), Sri Lanka (6), USA (5), UK (5), Israel (3), Ireland (2), Austria, Germany, India, Japan ex-Sri Lanka, New Zealand, Thailand (1 each)

Mutations on top of BA.5.2.1:
S:Y248H
ORF6:P57L
nuc:T6979G, C26625T

Detection in small numbers in lots of countries suggests high prevalence in an undersampled region, and that is most likely Sri Lanka, where this lineage makes up 6 out of 22 sequences with sample dates in July. The Usher tree backs this up. The S:Y248H mutation has been seen before in BA.2.47, and S:248 mutations often produced a growth advantage on a BA.2 background, so this is worth monitoring.

<img width="736" alt="BA521_Y248H" src="https://user-images.githubusercontent.com/42699509/182007221-1af5d716-6621-4bc3-bd46-9781473efc75.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_b985_5e9500.json?branchLabel=Spike%20mutations&c=country&label=nuc%20mutations:T22304C](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_b985_5e9500.json?branchLabel=Spike%20mutations&c=country&label=nuc%20mutations:T22304C)

Cov-spectrum query: [https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.1*+%26+ORF6%3A57L+%26+S%3A248H&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.1*+%26+ORF6%3A57L+%26+S%3A248H&)
Too early to plot growth advantages

**Comment by FedeGueli** [comment]
Hi @silcn i was noticing that the bigger orf6:57L 
(w/o S:248H) is disproportionately sampled in Kenya with very high prevalence there.
Maybe this could point to an alternative area of emergence even if Sri Lanka one seems the most likely at the moment

**Comment by silcn** [comment]
Yes, I agree Kenya is likely the origin of the ORF6:57L lineage, and it might therefore deserve its own designation on geographical grounds, though it doesn't have a growth advantage. It was already present there in early April; the Israel sequence claiming to be from February is likely a date error.

There are a couple of sequences from Sri Lanka with ORF6:57L but not S:248H. Given the sparsity of Sri Lankan sequencing, that suggests to me that BA.5.2.1+ORF6:57L was imported there and then gained S:248H, rather than two separate imports of ORF6:57L with and without S:248H.

**Comment by FedeGueli** [comment]
yes i have asked @shay671 to check that israelian sequence (EPI_ISL_13111336 )
 that if real could have big implications , fact that seems very unlikely.

I am thinking to propose the orf6:57L to better describe the tree and as u said the interesting likely emegence in an african country.

**Comment by FedeGueli** [comment]
@silcn got confirmed by  @shay671 from the lab that early sequence is 99,9% a mistake .

By the way this sublineage seems to have (and keep for now) a good advantage we need to wait for more sequences to judge how real it is.

@corneliusroemer @chrisruis @InfrPopGen something to monitor closely also cause the country source is quite certainly very under sampled.

**Comment by FedeGueli** [comment]
77 sequences as today on covspectrum (i cant check on usher),

Giving its probable origin in an undersampled area , its fast growth and its apparent growth advantage i advocate for a fast designation of this.

@corneliusroemer @chrisruis @InfrPopGen @thomaspeacock

**Comment by FedeGueli** [comment]
96 seqs as today. one of the fast growing sublineage as today.
Fast spreading in Australia.
Nearly dominant in Sri Lanka although too small numbers to be relevant
Spike Mutation ( S:Y248H) associated with increased transmissibiliy



tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34374_a23d60.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T22304C

@corneliusroemer @chrisruis @thomaspeacock @InfrPopGen

**Comment by FedeGueli** [comment]
4 more sequences uploaded today: 2 from Usa (from 2 different states), 1 From, England ,1 from.denmark.
Looking at the collection date there are 7 seqs collected since the beggining of August (3 Australia,2 Uk, 2 Denmark)

Gisaid query: Spike_Y248H,NS6_P57L

**Comment by FedeGueli** [comment]
One more sample today from Austria. 97 viruses found on Gisaid as today with the query above.
It should be already over 100 seqs on usher.

**Comment by FedeGueli** [comment]
Big upload of samples from Sri Lanka yesterday this confirms its origin there.
One sample from South Korea had travel history from Vietnam.

132 viruses for Gisaid query posted above.
I thibk it deserves a fast designation as BA.5.10 now that geographical origin of its spread has been confirmed. 
its prevalence in SriLanka is likely very high representing 36 viruses out of 124 uploaded from SriLanka after July 30.

@InfrPopGen @corneliusroemer @chrisruis @silcn

**Comment by FedeGueli** [comment]
Notes:

Looking at the usher tree(
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3faa0_15e0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:T22304C) 
There are two clear big chain of transmission outside SriLanka: Australia and Ireland (Where both the 1st and last sequence of this lineage have been sequenced). 
Several smaller clusters of trasmisssion are 
apparently ongoing in England  too

**Comment by FedeGueli** [comment]
already 138 viruses on Gisaid today new samples from Switzerland Usa and Ireland

**Comment by FedeGueli** [comment]
147 viruses found on Gisaid today. i think a quick designation is deserved to this lineage. It is the only one "outsider" together with BA.5.10 (S:A262S),  but apparently faster than ba.5.10,of BA.5 with NTD mutations that seems to compete versus BA.2.75 and to stay ahead of the super fast and huge BA.5.2 lineage with Orf1b:1050N (soon it will reach 20% of global samples)

140 viruses shown on Usher as today:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2b58f_1669a0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:G29422T,C29466T
![Schermata 2022-08-21 alle 01 02 25](https://user-images.githubusercontent.com/87669813/185768851-749069c3-7cef-4e0a-840e-aaeed5e2dd94.png)
It is easy to identify from the tree an ongoing outbreak in Australia (Victoria, mainly)  defined by Nuc: C643T
Another outbreak is ongoing   in Ireland defined by Nuc: C21595T
while Orf1a:A2129V defines an american branch seeded multiple times in Europe .
Another mini cluster with S:765L in England .
In England there is also another minicluster defined by S:446D but from date and provenience of samples  it could be just travel related.

This to say that this sublineage is already differentiated and giving start to outbreaks in at least 3 continents .

@corneliusroemer @chrisruis @InfrPopGen

**Comment by talyashe** [comment]
@corneliusroemer @silcn 
just to make sure I understood correctly - BF.15 is defined only from the branchpoint with the mutation S:Y248H and it's evolved from the branchpoint that has the mutations C27371T, T6979G, C26625T on top of BA.5.2.1?

**Comment by AngieHinrichs** [comment]
I hope so, since that's how I have it annotated on the UShER tree.  🙂

**Comment by corneliusroemer** [comment]
Yes that's how I picked the sequences - though Nextclade assigns it to those lacking 248H as well, because that one is still the nearest neighbour 😬

**Comment by alantsangmb** [comment]
Yes, I also noticed Nextclade assign those ORF6:P57L without S:Y248H as BF.15, which they should be BA.5.2.1 actually.
