### ISSUE TITLE
Potential BA.1.1*/BA.2.9* recombinant with likely breakpoint at NSP3 (71 seqs as of 2022-07-30, Spain and other European countries)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#894]
### Description
**Recombinant between**: BA.1.1* and BA.2.9*
**Earliest sequence**: 2022/03/21 (Spain)
**Most recent sequence**: 2022/07/12 (Spain)
**Countries circulating**: 
<html>
<body>

Location | Number of sequences | Prevalence
-- | -- | --
Spain | 21 | 0.082%
United Kingdom | 13 | 0.002%
France | 9 | 0.011%
United States | 8 | 0.007%
Germany | 4 | 0.005%
Ireland | 2 | 0.034%
Italy | 2 | 0.049%
Belgium | 2 | 0.212%
Denmark | 2 | 0.007%
Sweden | 2 | 0.031%
Costa Rica | 1 | 0.228%
Netherlands | 1 | 0.027%

</body>
</html>

**Likely breakpoint**: 2834-4183 (NSP3)
**Mutations on branch**: T17407C
**Conserved Nuc mutations** (those in red frames are likely from BA.1*):
![image](https://user-images.githubusercontent.com/86835836/182011055-3217304f-d900-489c-a82f-acf9aaf7e43d.png)
**Cov-spectrum query**: 24433G, 17407C, 25624T, 29510C, 2832G, 2470T

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/182011090-28db05d3-27e2-4af1-9dbd-33b5fd65ee9a.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9185_4cf6c0.json?branchLabel=nuc%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C900T

### Genomes:
EPI_ISL_11905454, EPI_ISL_13699273, EPI_ISL_13370678, EPI_ISL_13372877, EPI_ISL_13444439, EPI_ISL_13444440, EPI_ISL_13449638, EPI_ISL_13069252, EPI_ISL_13106571, EPI_ISL_13185887, EPI_ISL_13467672, EPI_ISL_13769785, EPI_ISL_13769592, EPI_ISL_13766743, EPI_ISL_13470978, EPI_ISL_13480893, EPI_ISL_13244294, EPI_ISL_13927300, EPI_ISL_12893566, EPI_ISL_13311882, EPI_ISL_13002387, EPI_ISL_13031956, EPI_ISL_13529864, EPI_ISL_13951499, EPI_ISL_13579909, EPI_ISL_13616313, EPI_ISL_13646417, EPI_ISL_13848198, EPI_ISL_13882383, EPI_ISL_12851801, EPI_ISL_13307278, EPI_ISL_12970201, EPI_ISL_13242604, EPI_ISL_12699705, EPI_ISL_12811206, EPI_ISL_13520175, EPI_ISL_13027413, EPI_ISL_12674814, EPI_ISL_12929621, EPI_ISL_12216325, EPI_ISL_12723630, EPI_ISL_12864031, EPI_ISL_11740036, EPI_ISL_13655352, EPI_ISL_13824636, EPI_ISL_13323445, EPI_ISL_14048322, EPI_ISL_14048310, EPI_ISL_14048302, EPI_ISL_14057351, EPI_ISL_13990785, EPI_ISL_14092805, EPI_ISL_14099567, EPI_ISL_13340079, EPI_ISL_13342602, EPI_ISL_12970355, EPI_ISL_13879180, EPI_ISL_13109376, EPI_ISL_12811699, EPI_ISL_13069264, EPI_ISL_13433105, EPI_ISL_13338323, EPI_ISL_13253685, EPI_ISL_12294049, EPI_ISL_12738523, EPI_ISL_13034582, EPI_ISL_13893845, EPI_ISL_12728434, EPI_ISL_13106648, EPI_ISL_12897145

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added recombinant lineage XAU with 77 newly designated sequences, and 0 updated designations. Defining mutation T17407C.
