### ISSUE TITLE
Potential AY.122/BA.2* recombinant (7 seqs as of 2022-08-19, Russia)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#895]
I am proposing this potential recombinant with only 5 sequences based on its concerning mutation profiles.

### Description
**Recombinant between**: AY.122 and BA.2*
**Earliest sequence**: 2022/06/27 (Russia-SPE)
**Most recent sequence**: 2022/07/15 (Russia-SPE)
**Countries circulating**: Russia (these 5 sequences are from 5 different patients as per age/sex: M63, F64, M67, F53 and M73)

**Mutations from potential BA.2 donor**: from 22578 to 28271
**Mutations from potential AY.122 donor**: from 5' to 22036, and from 28311 to 3'
**Mutations convergent to BA.1**: 22194/22196del (S:NL211I), could also possibly be from a recombination event?

**Private mutations**:
<html>
<body>

Gene | Mutations (amino changes)
-- | --
ORF1a | C335T (ORF1a:R24C), G569A (ORF1a:E102K), T689C (ORF1a:S142P), G1125A (ORF1a:R287K), C1973T, G3246A (ORF1a:S994N), G4561A, C5052T (ORF1a:P1596L), C5167T, G6149A (ORF1a:D1962N), G7427A (ORF1a:A2388T), T9676C, A10323G (ORF1a:K3353R), GCT11330ATG (ORF1a:V3689M), C11866T
ORF1b | C13806T, C13994T (ORF1b:A176V), C14585T (ORF1b:A373V), C17304T, C17550T, A17973G, G18525A
Spike | C21575T (S:L5F), C21636T (S:P25L), T22283C, 22289/22294del (S:242/243del), G22899A (S:G446D), T22942A (S:N460K), G23040A (S:R493Q reversion), T23042C (S:S494P), C23114T, G23599T (S:K679N reversion), G24145A
ORF3a | A25592G (ORF3a:K67R)
M | C26537T
N/ORF9b | G28562A (N:G97S), G28646A (N:A125T), C28873T

</body>
</html>

![image](https://user-images.githubusercontent.com/86835836/182052838-b60de85f-a8a8-4a3d-9803-1ebaf7785cf5.png)
**GISAID query**: NSP1_E102K, N_G97S, NS3_K67R
**Cov-spectrum query**: C5052T, C5167T, G6149A, G7427A, T9676C, A10323G, G11330A, C17550T, A17973G, C23114T, G24145A, A25592G, C26537T, A28461G, G28562A

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/182055437-ca6da35a-8f34-4856-97de-f1b6043f7781.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2be1f_70c1f0.json?branchLabel=Spike%20mutations&label=nuc%20mutations:G15451A,T15714C,C16466T,T17410C,G18163A,C19220T,T19955C,G20055A

Genomes:
EPI_ISL_13638513, EPI_ISL_13638520, EPI_ISL_14160830-14160831,
EPI_ISL_14160872

**Comment by FedeGueli** [comment]
I found a couple of Covspectrum queries which find just 2 out of 5

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=N%3AG97S%2CN%3AA125T&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

or

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AS142P&nucMutations=G210T%2Cc241T%2CC335T&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&


Leave these ones here to see if they are helpful if this starts circulating

**Comment by thomasppeacock** [comment]
This looks very interesting - think if some more sequences come along we should consider assigning even though its below the guidelines for numbers of sequences (due to the unique breakpoint pattern and additional private mutations). Going to put a monitor label on it for now.

**Comment by thomasppeacock** [comment]
@MCB6 - ah thats very helpful to know, thank you! I dont suppose there's any information on whether these are from random surveillence or whether they might have been targetted (ie a single household/hospital ward etc) that might give a clue whether this might be widespread or highly localised? thanks again!

**Comment by MCB6** [comment]
They used to mark outbreak clusters and source hospitals,  so I think that they came from regular surveillance, but will try checking.  Yegor was also trying to make a point that the recombinant is no match to BA.5s driving the wave there now. Interestingly,  I am heading to Saint Petersburg myself tonight... what would be the chance lol

**Comment by MCB6** [comment]
Yes,  the answer is,  no selected samples.  The selection is random and combines non hospital  testing labs and some hospital samples

**Comment by enabieva** [comment]
The sc2rf profile:
<img width="819" alt="sc2rf" src="https://user-images.githubusercontent.com/25522716/182275847-fac19a1a-18ed-4789-b987-d17e6e04dddf.png">

**Comment by enabieva** [comment]
> According to Yegor Bazykin, they checked the reads and confirmed that it looks legit (not a coinfection or contamination)

That's right (member of the Bazykin lab here).

**Comment by thomasppeacock** [comment]
Another one of these uploaded from Moscow (EPI_ISL_14424103) - collection date from start of August.

**Comment by silcn** [comment]
The new sequence also has better spike coverage, revealing the mutations S:142/143del, Y144D, Y145D, probably present in all 6 sequences

**Comment by MCB6** [comment]
The authorities in Russia blamed me personally for the newest data upload,
adding to their official press release a blurb how American interlopers
must stop studying Russian strains and concentrate instead on the
complicated epidemiological situation at their own home

**Comment by c19850727** [comment]
It just popped up in Ireland. EPI_ISL_14547668.

**Comment by thomasppeacock** [comment]
Recommending this for designation now there is evidence of international spread. Although still a low number of sequences this is based on the unique breakpoints and parent lineages, combined with the fairly extensive private mutations.

**Comment by Mydtlwn** [comment]
It is recommended to name and track quickly, especially in undersampled areas.

**Comment by FedeGueli** [comment]
@Mydtlwn thx.

**Comment by MCB6** [comment]
A new upload from the Influenza Institute from St Petersburg. Out of 68 samples collected after July 16, 67 are BA.5's subvariants, and apparently no recombinants. Which is a relatively strong hint that its share (which stood at ~2% earlier in July) may be dwindling...

**Comment by aq-sun** [comment]
Thanks for submitting, we have added this as XAW with 5 new designations.

**Comment by MCB6** [comment]
A new upload from St Petersburg appears to contain 9 more genomes of XAW. At a peak it accounted for 12% of the city's reported viral diversity, but by mid-August it disappeared

**Comment by FedeGueli** [comment]
EPI_ISL_14909092 new upload from St.Petersburg collected on mid july

**Comment by FedeGueli** [comment]
4 very recent samples spotted by @ryhisner uploaded today.

**Comment by FedeGueli** [comment]
6 more samples uploaded yesterday spanning between 28/07 and 25/08 all from St.Petersburg

**Comment by MCB6** [comment]
Only one of the new St. Petersburg samples has a recent collection date. The rest just add to the earlier pile of XAW's from late July - early August when it accounted for several percent of the city's coronavirus diversity. But out of 161 samples collected so far in the 2nd half of August, only one was XAW. It looks like the recombinant has been outcompeted...

**Comment by FedeGueli** [comment]
@MCB6 the XAW samples after 25/08 are 3. out of 350+ so % luckily is low around 0,5% /1% but saying it is outcompeted i think it is a bit early.

**Comment by FedeGueli** [comment]
and from.1 july to 15th august it was 21 out of 4000+ samples so % is not going down at all.

**Comment by MCB6** [comment]
@FedeGueli true, 3 2nd half of August genomes from Russia, but only one of the three was from St Petersburg, the XAW original epicenter. Small numbers of course. But the decrease is encouraging in any case.
![image](https://user-images.githubusercontent.com/93294184/190516494-a7fb1f89-50ed-442e-9fe5-ff9491aabf55.png)

**Comment by FedeGueli** [comment]
Adding here the @carlottaolivero finding that not all S:460K circualting have the same nuc mutation.
XAW as BQ.1* has T22942A (different from T22942G of BA.2.75ers)

**Comment by FedeGueli** [comment]
New Xaw uploaded today it is a Saint Petersburg sample collected on 2022-09-06

**Comment by FedeGueli** [comment]
total count today is 40 two new samples collected back at the end of august start of september

**Comment by MCB6** [comment]
5 more from St. Petersburg with late September collection dates, so it isn't quite dead

**Comment by theosanderson** [comment]
The private substitutions of this lineage have a high proportion of transitions, and G-to-A substitutions specifically, suggestive of molnupiravir.

**Comment by MCB6** [comment]
It's probably a different drug known to cause lethal transition mutagenesis in SARS-CoV-2, Favipiravir (a proposed, but not effective, influenza medication from Japan, which was approved against Covid in Russia in summer 2020, and distributed free of charge through the neighborhood health centers). 
https://www.nature.com/articles/s41467-020-18463-z

Because of lack of demonstrated efficacy, and of the corruption scandals involving Favipiravir importers, the drug had a bad rap in Russia, but nobody linked it to viral mutation accumulation before. If it is to blame, then perhaps there may be other hyper-transition-mutated genomes from Russia too?

**Comment by theosanderson** [comment]
One does see some other sequences Russia with this signature. Given the dates of these sequences, it could well be Esperavir (MOV), but yes could also be favipiravir-related. Do you have data on relative usage that makes you think the latter?

**Comment by MCB6** [comment]
There are data on state procurement and it appears that there was a shift from Favipiravir to Esperavir in the first half of 2022. Esperavir was approved in February, but by late August accounted for 78% of the anticoronavirals purchased by the government. But they also prescribed and distributed a lot of previously-purchased Favipiravir. Procurement doesn't immediately translate into usage, alas, and I don't see the latter numbers

**Comment by theosanderson** [comment]
There's a reasonable chance one may be able to distinguish from mutation contexts, but we haven't looked into that yet

**Comment by MCB6** [comment]
Or by using spring 2022 collection date cutoff (but then it becomes irrelevant specifically for the XAW story)

**Comment by AnonymousUserUse** [comment]
> G22899A (S:G446D), T22942A (S:N460K), G23040A (S:R493Q reversion), T23042C (S:S494P), C23114T, G23599T (S:K679N reversion), G24145A
> ORF3a	A25592G (ORF3a:K67R)
> M	C26537T

Ts/Tv ratio is high in both donors of this lineage, so I think probably the recombination event occured before the mutagenesis event.
A quantitative molnupiravir-candidate analysis may be done separately for both donors, compared with expected values calculated for both donors.

**Comment by MCB6** [comment]
> probably the recombination event occured before the mutagenesis event.

or simultaneously. If the viral genomes of both parental strains in a concurrently-infected patient suffered from deleterious mutations, then recombining might have become the best escape route

**Comment by corneliusroemer** [comment]
Indeed, recombination is the best way to get rid of multiple deletions. This may be how BA.5 managed to outcompete BA.4 as BA.5 managed to revert something back to ancestral that is mutated in all other Omicrons. There's not much else that could explain the consistent growth advantage of BA.5 over BA.4

**Comment by FedeGueli** [comment]
agree with @corneliusroemer . and probably is the real danger of this antiviral related lineages: to recombine before getting extincted.

**Comment by MCB6** [comment]
Since XAW's parents meaningfully overlapped only in January-February 2022, would it mean that the variant was several months old by the time it was discovered in June?
<img width="533" alt="image" src="https://user-images.githubusercontent.com/93294184/218639418-b0c7a224-6349-4e9a-8f7f-af1f3134e4b7.png">

**Comment by thomasppeacock** [comment]
My assumption would be the Delta parent was a chronic infection that lasted several months into the Omicron wave before the BA.2 infection - similar explanation for XBC, XAY and XBA - we laid out the evidence for that here: https://virological.org/t/sars-cov-2-evolution-post-omicron/911
