### ISSUE TITLE
BA.4 sublineage with S:F157L (71. seq. 8 countries as of 01.08.22)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#897]
Proposal for a sublineage of BA.4
Earliest sequence: 05.06.2022 (UK)
Countries detected: mostly UK, Australia, Germany, Ireland, Israel, Netherlands, Trinidad and Tobago

Defining mutation:
C22033A = S:F157L
C29272T

This variant is defined by S:F157L and was first detected in UK.  Now it is present in 6 other countries across 3 continents. 71 seq on Usher as of 01.08.22.

![grafik](https://user-images.githubusercontent.com/102166254/182114386-e49185f8-9cdb-4463-aa88-ae9e09fbf79b.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_79e8_7936a0.json?branchLabel=aa%20mutations&c=gt-S_157&label=nuc%20mutations:C22033A

Growth advantage vs. BA.4 global 3 months:
![grafik](https://user-images.githubusercontent.com/102166254/182116036-4a350313-2ccf-4951-8c2d-b87b94a2973b.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.4*&aaMutations1=S%3AF157L&nucMutations1=C29272T&pangoLineage1=BA.4*&analysisMode=CompareToBaseline&

EPI_ISL_13518118, EPI_ISL_13518209, EPI_ISL_13535664, EPI_ISL_13657590, EPI_ISL_13715046, EPI_ISL_13716344, EPI_ISL_13741197, EPI_ISL_13741873, EPI_ISL_13742604, EPI_ISL_13798198, EPI_ISL_13798609, EPI_ISL_13798651, EPI_ISL_13881740, EPI_ISL_13881852, EPI_ISL_13882311, EPI_ISL_14042855, EPI_ISL_14090167, EPI_ISL_14090437, EPI_ISL_13439844, EPI_ISL_13570389, EPI_ISL_13570413, EPI_ISL_13611770, EPI_ISL_13732503, EPI_ISL_13991317, EPI_ISL_14027948, EPI_ISL_14154774, EPI_ISL_14165331

OX063256.1, OX103414.1, OX103506.1, OX109724.1, OX109775.1, OX109835.1, OX109967.1, OX110844.1, OX128669.1, OX137905.1, OX137910.1, OX138705.1, OX139622.1, OX146068.1, OX146232.1, OX148458.1, OX155389.1, OX157310.1, OX157340.1, OX157387.1, OX158865.1, OX158939.1, OX160850.1, OX162264.1, OX162989.1, OX226172.1, OX226945.1, OX229466.1, OX229733.1, OX229875.1, OX231307.1, OX231323.1, OX231330.1, OX231786.1, OX241884.1, OX241926.1, OX241967.1, OX244551.1, OX245411.1, OX245829.1

**Comment by FedeGueli** [comment]
After fading a bit it seems going up in the last days. To be monitored.
