### ISSUE TITLE
Proposal for BA.2.76 Sublineage with S:R357K, ORF1a: G1595S, & ORF1b:V2073L

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#899]
**Sub-lineage of:** BA.2.76
**Earliest sequence:** 2022-6-20, India, West Bengal, Howrah — EPI_ISL_13876813
**Most recent sequence:** 2022-7-13, India, West Bengal — EPI_ISL_14175293 (North 24 Parganas) and EPI_ISL_14175835 (Howrah)
**Countries circulating:** India—primarily West Bengal (42/45 sequences). One sequence each in Assam, Karnataka, and Tripura. 
**Number of Sequences:** 49 in Usher Tree, 45 via GISAID search query “Spike_R346T, Spike_Y248N, Spike_R357K”
**Substitutions on top of BA.2.76:**
Spike: R357K
ORF1a: G1595S (NSP3_G777S)
ORF1b: V2073L (NSP15_V22L)
Nucleotide: G5048A, C7528T, C18555T, G19684T, G22632A, T29233A

**USHER Tree**
44 of the 45 sequences returned by the GISAID search query “Spike_R346T, Spike_Y248N, Spike_R357K” are in the subtree of BA.2.76 below.
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_3cfdd_7e9960-BA.2.76%2BR357K-TreeMAIN.json
![Screen Shot 2022-08-01 at 12 10 49 PM - USHER, R357K](https://user-images.githubusercontent.com/33738461/182192968-29bb97c5-6ef2-4807-8864-ce77a88a0e32.png)

One of the 45 sequences, which in addition to spike mutation R357K also contains G446S and N460K, is placed by USHER in the BA.2.75 tree (with numerous reversions). 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice2_genome_3cfdd_7e9960-BA.2.76%2BR357K-Tree.json 

**Evidence**
Before today (August 1), there were only four sequences on GISAID with R346T, Y248N, and R357K. Today 41 such sequences were uploaded, all with collection dates between June 20 and July 13. Though 42 of the 45 sequences are from West Bengal, the other three are widely distributed—Karnataka is on the opposite side of India, and Assam and Tripura are on the opposite side of Bangladesh from West Bengal. These are all in one country, but India is a virtual continent unto itself; an approximate European equivalent would be finding 42/45 sequences of a lineage in Spain and one each in Italy, Switzerland, and Poland. 
![Screen Shot 2022-08-01 at 12 12 15 PM - India map](https://user-images.githubusercontent.com/33738461/182193477-8ac07d39-3928-4d43-b6e4-ac242bb1267b.png)

The 42 sequences from West Bengal are divided between six districts: Kolkata (23), Howrah (10), South 24 Parganas (4), North 24 Parganas (2), Nadia (2), and Bankura (1).

It’s too early to calculate any growth advantage with CovSpectrum. However, this proposed sublineage first appeared on June 20, and since that date, 41 of 573 sequences with S:R346T and S:Y248N in West Bengal have also possessed S:R357K, or 7.2%. Since July 1, 33/272, or 12.1% have. It seems very likely this is a rapidly growing sublineage. 

**Genomes**
[GISAID_hcov-19_ids_2022_08_01_16_05.csv](https://github.com/cov-lineages/pango-designation/files/9235443/GISAID_hcov-19_ids_2022_08_01_16_05.csv)

**Comment by silcn** [comment]
Ah, you beat me to it :)

> One of the 45 sequences, which in addition to spike mutation R357K also contains G446S and N460K, is placed by USHER in the BA.2.75 tree (with numerous reversions). 

I don't think this is real. There are a few sequences from today's West Bengal upload, from several different lineages, that look like they have picked up a small piece of the BA.2.75 RBD. Too much of a coincidence for them to be real, so probably contamination, and I suspect something similar has happened with this sequence.

**Comment by FedeGueli** [comment]
With the cvspectrum update there has been a biv jump in growth advantage of this sublineage. We have seen a similar pattern with other mass uploads from India. So better waiting new seqs to draw any conclusion on it.

**Comment by silcn** [comment]
West Bengal, the state where this lineage has been sampled most, has a very inconsistent upload schedule, with large sequence dumps that can be up to 2 or 3 weeks apart. So don't be surprised if we don't see much more of this lineage for a little while and then 50+ more sequences turn up at once.

**Comment by ryhisner** [comment]
18 new sequences of this proposed sublineage uploaded today, 16 from West Bengal, India; one from Illinois, USA; and one from New York, USA.

**Comment by corneliusroemer** [comment]
2 more sequences uploaded today - 1 from Singapore, 1 from Karnataka

The GISAID query (thanks for that Ryan, that's a great thing to include in proposals) now returns 66 sequences.

Would be great to put the running total in the issue name @ryhisner that really simplifies my life scanning for issues to take care of ;)

I'll make a PR as the extra S:357K and apparent growth are quite significant and deserving of a designation.

**Comment by shay671** [comment]
C7528T is a part of a mediator branch from the BA.2.76 branchpoint to this variant. a mediator branch that BA.2.76.1 also evolved from. 
So i understand that the other 4 mutations are the defining ones? 
@corneliusroemer @ryhisner
