### ISSUE TITLE
New lineage proposal for A.23.1 with E484K

### ISSUE THREAD

**Issue by erikalmecdc** [cov-lineages/pango-designation#9]
by Erik Alm

A new lineage in the UK that is part of the old A main lineage, with E484K. Spike E484K, Spike F157L, Spike P681R, Spike Q613H, Spike R102I, Spike V367F
Sub-lineage of: A.23.1
Earliest sequence: 2020-12-26
Most recent sequence: 2021-01-28
Countries circulating: UK

Old lineage resurrected, now with E484K

![A23-1 lineage](https://user-images.githubusercontent.com/36880285/107746259-cd3d0080-6d15-11eb-8a52-5bc49f3d48f5.png)
[new lineage A-23-1.xlsx](https://github.com/cov-lineages/pango-designation/files/5970514/new.lineage.A-23-1.xlsx)

**Comment by rambaut** [comment]
PHE is tracking this as a VOC but it is only defined by the addition of E484K within an A.23.1 lineage already circulating in the UK. On its own, a mutation isn't enough to warrant a sublineage but if we ascertain that the addition of this mutation is resulting in higher growth then we will revisit. 

Will leave the issue open.

**Comment by chrisruis** [comment]
This issue has gone stale so we'll close it for now. If this would still be a useful lineage designation, please reopen this. Thanks
