### ISSUE TITLE
New sub-lineage of C.36 with S:L452R

### ISSUE THREAD

**Issue by jcbarret** [cov-lineages/pango-designation#90]
**New sub-lineage of C.36 with S:L452R**
_Jeff Barrett, Daniel Money, lots of COG-UK data_

We have recently seen an increase in C.36 sequences in the COG-UK surveillance data, nearly all of which are a sub-lineage with S:L452R. Since this mutation has attracted attention in B.1.617 (and previously B.1.427), it may be useful to track it as a sub-lineage. Nearly all the sequences with L452R also have S:S12F (with a notable exception of a large number of recent Egyptian "ARMY" sequences). Within this group there is a further split, with one group having S:W152R, S:R346S and S:A899S, but it's not clear whether any of these are functional. 

[c.36-with-l452r.pdf](https://github.com/cov-lineages/pango-designation/files/6514016/c.36-with-l452r.pdf)

Sub-lineage of: C.36
Earliest sequence: 2020-12-25
Most recent sequence: 2021-05-14
Countries circulating: UK, Germany, USA, Egypt, Switzerland, others

**Genomes**

[c.36-with-l452r.txt](https://github.com/cov-lineages/pango-designation/files/6514010/c.36-with-l452r.txt)

**Evidence**

[c.36-with-l452r.pdf](https://github.com/cov-lineages/pango-designation/files/6514016/c.36-with-l452r.pdf)

**Proposed lineage name**

C.36.3, I guess?

**Comment by AngieHinrichs** [comment]
Hi @jcbarret - what you're proposing is just one level up from what @merijnvanhee proposed in #80 (the group having S:W152R, S:R346S and S:A899S).  Perhaps you and @merijnvanhee could come to an agreement on where the root of the new lineage should be placed?

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-80.json?branchLabel=Spike%20mutations&c=pango_lineage&label=nuc%20mutations:C21597T

**Comment by jcbarret** [comment]
Thanks @AngieHinrichs Sorry that I missed this. I did look for other issues, but was scanning the issue titles, and had missed #80 . I will close this one and jump over to that.
