### ISSUE TITLE
Proposal for a Sublineage of BA.4.6 with S:W152L (G22017T) [~150 as of 2022-08-10]

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#900]
**Description**
**Sub-lineage of:** BA.4.6
**Earliest sequence:** 2022-6-9, England—EPI_ISL_13421401
**Most recent sequence:** 2022-7-26, England— EPI_ISL_14164360 & EPI_ISL_14193794
**Countries circulating:** Primarily in the UK. Also detected in USA, Denmark, Netherlands, Germany, Canada, Sweden
**Number of Sequences:** 117 in Usher tree; 98 returned both by GISAID query “NS7b_L11F, Spike_F486V, R346T, W152L” and “Spike_N658S, Spike_F486V, R346T, W152L”
**Substitutions on top of BA.4.6:**
Spike: W152L
Nucleotide: G22017T 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_2b7d2_9396f0--BA.4.6%2BW152L--v.2.json 

**Evidence**
Given that 29 sequences of this proposed sublineage (25% of the total) are on the Usher tree but not yet on CovSpectrum (which has 88), all of the below are likely underestimates of the true growth rate of BA.4.6+W152L. Nevertheless, it shows a weekly growth advantage of 10% (CI: -5-25%) relative to BA.4.6 and a 38% (CI: 21%-55%) advantage relative to BA.5* in Europe over the last three months. 
https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.4.6&variantQuery1=nextcladePangoLineage%3ABA.4.6+%26+S%3AW152L&analysisMode=CompareToBaseline&
https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABA.4.6+%26+S%3AW152L&analysisMode=CompareToBaseline&

![Screen Shot 2022-08-02 at 11 10 30 AM---FINAL BA 4 6+W152L Growth, ALL](https://user-images.githubusercontent.com/33738461/182414295-88164b20-35d6-4484-9d0a-642c9dd3f1a6.png)

If we restrict the growth calculation to the UK, the corresponding weekly growth-advantage figures are 4% (CI: -13-21%) relative to BA.4.6 and 24% (CI: 6-42%) relative to BA.5*. Again, these are likely underestimates given the large number of BA.4.6+W152L sequences uploaded very recently and not yet registered on CovSpectrum (88 on CovSpectrum compared to 117 on Usher Tree).
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.4.6&variantQuery1=nextcladePangoLineage%3ABA.4.6*+%26+S%3AW152L&analysisMode=CompareToBaseline&
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABA.4.6*+%26+S%3AW152L&analysisMode=CompareToBaseline&

**Genomes**
[GISAID_hcov-19_ids_2022_08_02_15_32.csv](https://github.com/cov-lineages/pango-designation/files/9243619/GISAID_hcov-19_ids_2022_08_02_15_32.csv)

**Comment by FedeGueli** [comment]
@ryhisner are you planning to rewrite thie one? this  sublineage is very fast probably the fastest ba.4.

**Comment by FedeGueli** [comment]
Thx @ryhisner this is monitored since you first spotted it, very clear and stable growth advantage.
Important:
it shows also an apparent advantage versus the new global dominant lineage BA.5.2*:
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5.2*&variantQuery1=nextcladePangoLineage%3ABA.4.6+%26+S%3AW152L&analysisMode=CompareToBaseline&

**Comment by corneliusroemer** [comment]
Doesn't really seem to do much in the UK - as in no clear growth advantage over BA.4.6 in UK
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.4.6*&variantQuery1=nextcladePangoLineage%3ABA.4.6+%26+S%3AW152L&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
@corneliusroemer consider that is another 5% on the top of a clear advantage of BA.4,6 versus world dominant BA.5.2*

**Comment by ryhisner** [comment]
As @corneliusroemer notes, this doesn't seem to be growing as a percentage of BA.4.6, so I'm closing this issue.

**Comment by corneliusroemer** [comment]
I just noticed this again in recent uploads from UK.

I think it doesn't harm to designate this UK-linked lineage as it combines epi significance with Spike mutation.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.4.6.1 with 191 newly designated sequences, and 21 updated designations from BA.4.6. Defining mutation G22017T (S:W152L).
