### ISSUE TITLE
Potential BA.5.1 sublineage with ORF9b:T60I, ORF1a:K3839R, and ORF1a:G519S (219 seqs as of 2022-08-06, USA and spreading)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#901]
There may be a BA.5.1 sublineage with ORF9b:T60I (C28462T), ORF1a:K3839R (A11781G), and ORF1a:G519S (G1820A) first detected in California, USA.

As of 2022-08-01, Cov-Spectrum reports 182 BA.5.1+ORF1a:K3839R+ORF1a:G519S+ORF9b:T60I sequences:
![BA 5 1+ORF1a_3839R+ORF1a_519S+ORF9b_60I_Counts](https://user-images.githubusercontent.com/88959107/182247907-1c8c666a-85f2-4451-87c3-45ddbac11968.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.1+%26+ORF1a%3AK3839R+%26+ORF1a%3AG519S+%26+ORF9b%3AT60I&

As of 2022-08-01, Cov-Spectrum calculates a growth advantage of 23% compared to BA.5.1* in the United States:
![BA 5 1+ORF1a_3839R+ORF1a_519S+ORF9b_60I_Growth_USA](https://user-images.githubusercontent.com/88959107/182248880-0fa87890-e231-4bd2-9019-36f300b4200d.png)
Source: https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.1*&variantQuery1=nextcladePangoLineage%3ABA.5.1+%26+ORF1a%3AK3839R+%26+ORF1a%3AG519S+%26+ORF9b%3AT60I&analysisMode=CompareToBaseline&

UShER shows all of the GenBank samples are on a single subtree:
![BA 5 1+ORF1a_3839R+ORF1a_519S+ORF9b_60I_UShER](https://user-images.githubusercontent.com/88959107/182248009-ed329af7-55f0-49eb-ad06-9e78d3bccb12.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice1_genome_BA.5.1%2BORF1a_3839R%2BORF1a_519S%2BORF9b_60I.json

First GenBank sequence: California, USA 2022-06-09 

Most Recent GenBank sequence: Florida, USA 2022-07-27

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at  [Support_BA.5.1+ORF1a_3839R+ORF1a_519S+ORF9b_60I.zip](https://github.com/cov-lineages/pango-designation/files/9237466/Support_BA.5.1%2BORF1a_3839R%2BORF1a_519S%2BORF9b_60I.zip)

The closest Outbreak.info link for this potential lineage (with ORF9b mutations not supported by the site) is https://outbreak.info/situation-reports?pango=BA.5.1&muts=ORF1a%3AK3839R&muts=ORF1a%3AG519S. 

Also please note that the UShER phylogenetic tree suggests a base lineage with ORF9b:T60I (C28462T) and ORF1a:K3839R (A11781G) but without ORF1a:G519S (G1820A).  This base lineage may be giving rise to at least two additional sibling sublineages of the sublineage proposed here.

**Comment by FedeGueli** [comment]
It seems to have an advantage versus BA.5.2* that is the global dominant lineage as today.
Orf9B:60A was in Delta so a growth advantage for a mutation in that residue could be thought real

**Comment by FedeGueli** [comment]
206 seqs as today on covspectrum

**Comment by FedeGueli** [comment]
219 seqs as today , its growth is sustained and keeps the pace of the biggest BA.5.2* branches (Orf1b:1050N, S:1020S) , obviously probably there is no time for it to compete directly with them on a global landscape.

it is interesting to note that the Orf9b:60I + Orf1a:3839R is a bigger branch of BA.5.1  counting around 800 seqs.
It has already a 9-10% of growth advantage in US vs BA.5.1* that becomes 19% with Orf1a:G519S.

**Comment by alurqu** [comment]
@FedeGueli prompted by your comment, I took a look at the growth advantage in the USA of BA.5.1 with Orf9b:T60I and Orf1a:3839R and without ORF1a:G619S over all BA.5.1, and even without ORF1a:G519S as of 2022-08-06 CoV-Spectrum does show a 7% growth advantage for that parent to the primary lineage proposed here.

![BA 5 1+ORF1a_3839R+ORF9b_60I_Growth_USA_20220806](https://user-images.githubusercontent.com/88959107/183271301-23c0bfc2-aee1-42e9-8ebd-55c5dcc2cf4e.png)https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.1*&variantQuery1=nextcladePangoLineage%3ABA.5.1+%26+ORF1a%3AK3839R+%26+ORF9b%3AT60I+%26+%21ORF1a%3AG519S+&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
@InfrPopGen if you are designating this one think about designating parental BA.5.1+ORF9b:T60I, ORF1a:K3839R first.
There has been a discussion on twitter with also @ryhisner , Alex Selby and others, cause Ryan spotted that in the US BA.5.2* has not the solid growth advantage versus BA.5.1 shown in Uk and Denmark.
One of the few reason beyond the different weight of the super fast undesignated Orf1b:1050N in the american BA.5.2* (36% in Dk, 18% in Usa) which we could spot is the parent of this proposed sublineage!  (This conclusion after excluding BA.5.1.1 that seems having disadvantage vs BA.5.1*).

**Comment by InfrPopGen** [comment]
Thanks for submitting. So far I've added lineage BA.5.1.10 with 910 newly designated sequences, and 203 updated designations from BA.5.1. Defining mutation A11781G (ORF1a:K3839R).
The sublineage of this (the one originally proposed) is to follow.

**Comment by InfrPopGen** [comment]
Finally added lineage BK.1 with 0 newly designated sequences, and 93 updated designations from BA.5.1.10. Defining mutation G1820A (ORF1a:G519S).
