### ISSUE TITLE
BA.5.1 sublineage with S:V445A (76. seq. mostly US & Spain plus 7 other countries as of 02.08.22)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#902]
Proposal for a sublineage of BA.5.1
Earliest sequence: 27.05.2022 (Spain)
Countries detected: mostly USA (32) and Spain (24) but also England, Denmark, Canada, Italy, Belgium, France, Switzerland
Total of 76 seq. on Usher as of 02.08.22.

Defining mutation:
T22896C = S:V445A

This variant is defined by S:V445A and was first detected in Spain. Now it is present in total of 9 countries. The lineage is part of todays GISAID ermerging variant by acceleration analysis. 

![grafik](https://user-images.githubusercontent.com/102166254/182381427-cbe294b1-7ced-4e34-81b0-49ee6acd3cf5.png)

Subclade also carries S:A1070V.  

![grafik](https://user-images.githubusercontent.com/102166254/182380873-9c85692f-ae5c-4713-9a43-652048248aec.png)
![grafik](https://user-images.githubusercontent.com/102166254/182380970-c8a0bb93-e3c9-497f-a787-f231056b3eb7.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26c33_918130.json?branchLabel=aa%20mutations&c=gt-S_445&label=nuc%20mutations:C241T,T670G,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,T27438C,C27807T,C27889T,A28271T,C28311T,G28881A,G28882A,G28883C,A29510C,C29666T

Growth advantage versus BA.5.1 Europe 3 months:
![grafik](https://user-images.githubusercontent.com/102166254/182382119-2c69e6cb-cd4a-4dd7-ab22-07d9a204992a.png)

Growth advantage versus BA.5.1 North America 3 months:
![grafik](https://user-images.githubusercontent.com/102166254/182382213-e8820eb8-d508-4d2e-82ec-6c9a5edbc14e.png)
https://cov-spectrum.org/explore/North%20America/AllSamples/Past3M/variants?pangoLineage=BA.5.1*&aaMutations1=S%3A445A&pangoLineage1=BA.5.1*&analysisMode=CompareToBaseline&

![grafik](https://user-images.githubusercontent.com/102166254/182382494-b45c520c-be5f-4080-a1f5-ea500a4efe5d.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AS445A&pangoLineage=BA.5.1*&aaMutations1=S%3A445A&pangoLineage1=BA.5.1*&

EPI_ISL_13343223, EPI_ISL_13370393, EPI_ISL_13370396, EPI_ISL_13370884, EPI_ISL_13479444, EPI_ISL_13480145, EPI_ISL_13537936, EPI_ISL_13577639, EPI_ISL_13621247, EPI_ISL_13659121, EPI_ISL_13661821, EPI_ISL_13716809, EPI_ISL_13744737, EPI_ISL_13745820, EPI_ISL_13745960, EPI_ISL_13746114, EPI_ISL_13748483, EPI_ISL_13748530, EPI_ISL_13748791, EPI_ISL_13796921, EPI_ISL_13833467, EPI_ISL_13843634, EPI_ISL_13844687, EPI_ISL_13846873, EPI_ISL_13887233, EPI_ISL_13888554, EPI_ISL_13890015, EPI_ISL_13890102, EPI_ISL_13971496, EPI_ISL_13993400, EPI_ISL_13993413, EPI_ISL_14028821, EPI_ISL_14029067, EPI_ISL_14029945, EPI_ISL_14031251, EPI_ISL_14032635, EPI_ISL_14047040, EPI_ISL_14048197, EPI_ISL_14048204, EPI_ISL_14048243, EPI_ISL_14049560, EPI_ISL_14051285, EPI_ISL_14051286, EPI_ISL_14051294, EPI_ISL_14051323, EPI_ISL_14051342, EPI_ISL_14051344, EPI_ISL_14057352, EPI_ISL_14076440, EPI_ISL_14076539, EPI_ISL_14091093, EPI_ISL_14093843, EPI_ISL_14093851, EPI_ISL_14097659, EPI_ISL_14145134, EPI_ISL_14145167, EPI_ISL_14152952, EPI_ISL_14152953, EPI_ISL_14170963

ON949101.1, ON968229.1, OP017816.1, OP025802.1, OP026151.1, OP041074.1, OP041317.1, OP054456.1, OP065421.1, OX158139.1, OX188835.1, OX219920.1, OX233901.1, OX241811.1

**Comment by agamedilab** [comment]
95 seq. on Usher as of 08.08.22.


![grafik](https://user-images.githubusercontent.com/102166254/183402455-b57d6283-a7ce-4efa-b1d3-b3118bb18864.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ce9a_bf140.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:T22896C

**Comment by FedeGueli** [comment]
152 seqs as today

**Comment by icestorm972** [comment]
FYI (cc @corneliusroemer )
As of today, there are 10 samples of BA.5.1 with S:V445A<sup>**</sup> in Germany (German RKI dataset<sup>*</sup>), the first two are the ones already in cov-spectrum.

FASTA id codes, date of sample extraction and corresponding week:</code>
- <code>IMS-10004-CVDP-9931B0D5-B8FB-416E-BB7C-5FB4F1FA6F36</code> <code>2022-07-13</code> <code>28</code>
- <code>IMS-10116-CVDP-96E7EF86-3EDE-44E1-B909-36572AC70532</code> <code>2022-07-20</code> <code>29</code>
- <code>IMS-10013-CVDP-7624AECF-C4AC-490E-885A-F9E4F5CB4A8A</code> <code>2022-08-01</code> <code>31</code>
- <code>IMS-10203-CVDP-D2A8DB9F-8243-4708-84AB-52CD9587F87F</code> <code>2022-08-06</code> <code>31</code>
- <code>IMS-10150-CVDP-E845AAE3-FE7D-4B23-A42C-D6AE0321697A</code> <code>2022-08-09</code> <code>32</code>
- <code>IMS-10150-CVDP-855F6A06-2B68-4DBF-997A-0B19BCB4383E</code> <code>2022-08-10</code> <code>32</code>
- <code>IMS-10150-CVDP-309A94A6-1C41-4052-94AD-A72ABFBF9269</code> <code>2022-08-10</code> <code>32</code>
- <code>IMS-10150-CVDP-7395E3F8-0CFA-4975-85B0-D07393E4291B</code> <code>2022-08-10</code> <code>32</code>
- <code>IMS-10150-CVDP-3DCA1CBD-4271-4571-A873-55C0961C6EA0</code> <code>2022-08-10</code> <code>32</code>
- <code>IMS-10227-CVDP-9FC2B50C-893D-4F73-8198-33635D06F83D</code> <code>2022-08-12</code> <code>32</code>

<sup>*</sup> _[RKI Sequence database](https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland)_
<sup>**</sup> _aaSubstitutions column in tsv by nextclade v2.1.0 with dataset tag 2022-07-26_

**Comment by agamedilab** [comment]
95124 seq. on Usher as of 22.08.22.

![grafik](https://user-images.githubusercontent.com/102166254/185912862-6485d7a4-f259-432b-ae0c-b62a34151f2e.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8e28_364160.json?branchLabel=aa%20mutations&label=nuc%20mutations:T22896C

**Comment by agamedilab** [comment]
many thanks! If you have time I would be very happy if a desigante label & milestone could be added to this issue. All the best! @corneliusroemer @InfrPopGen
