### ISSUE TITLE
Proposal for a Sublineage of BA.5.6 with S:K444T [238 seq on Usher, 229 seq on GISAID, Aug 15]

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#903]
**Description**
**Sub-lineage of:** BA.5.6
**Earliest sequence:** 2022-5-27, USA, New Jersey — EPI_ISL_13544819
**Most recent sequence:** 2022-7-22, USA, New York — EPI_ISL_14178050
**Countries circulating:** Primarily USA and Belgium: USA (86), Belgium (26), Mexico (7), Ecuador (6), France (2), UK (2), Canada (2), Chile (1), Luxembourg (1), Netherlands (1), Peru (1), Puerto Rico (1) —as found using GISAID query “Spike_K444T, NSP13_A389V”
**Number of Sequences:** 122 on Usher Tree; 136 using GISAID query “Spike_K444T, NSP13_A389V”
**Substitutions on top of BA.5.6:**
Spike: K444T
Nucleotide: C8605T (synonymous), A22893C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_34ea_9274e0-BA.5.6%2BK444T.json 

**Evidence**
CovSpectrum: 26% (CI:9%-43%) weekly growth advantage relative to nextcladePangoLineage:BA.5.6* in the last three months in USA:
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5.6*&variantQuery1=Nextcladepangolineage%3ABA.5.6*+%26+S%3AK444T&analysisMode=CompareToBaseline&
![Screen Shot 2022-08-02 at 10 08 25 AM--BA 5 6*_vs_BA 5 6*+K444T--USA](https://user-images.githubusercontent.com/33738461/182401896-5fd9bfc2-36ec-4240-b1cf-4de5b5bde9df.png)

CovSpectrum: 43% (CI:4%-82%) weekly growth advantage compared to nextcladePangoLineage:BA.5.6* in the last three months in Belgium:
https://cov-spectrum.org/explore/Belgium/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5.6*&variantQuery1=Nextcladepangolineage%3ABA.5.6*+%26+S%3AK444T&analysisMode=CompareToBaseline&
![Screen Shot 2022-08-02 at 10 07 02 AM--BA 5 6*_vs_BA 5 6*+K444T--Belgium](https://user-images.githubusercontent.com/33738461/182401848-7d0c6d53-93d5-4cde-aee5-dd0783819ef2.png)

According to the Bloom Lab RBD Escape Calculator, S:K444 is the prominent escape site for antibodies known to neutralize BA.4/5. 
https://jbloomlab.github.io/SARS2_RBD_Ab_escape_maps/escape-calc/

![Screen Shot 2022-08-02 at 10 13 58 AM--BloomLab RBD Escape Calc, K444](https://user-images.githubusercontent.com/33738461/182401795-11e0cacd-3cff-4586-a682-b897dc8344da.png)

S:K444 mutations likely impose some cost in terms of ACE2 binding and RBD expression. Here’s a comparison of the reduction in ACE2 binding and RBD expression of the three most common K444 mutations seen thus far (on a BA.2 background), according to the Bloom Lab RBD Heat Map. K444T imposes a lower cost than K444N in terms of reduction of ACE2 affinity (-0.10 vs -0.16) but a higher cost in loss of RBD expression (-0.19 vs -0.08). K444T has the same reduction as K444R in ACE 2 affinity (-0.10) but a much higher reduction in RBD expression (-0.19 vs -0.04).
https://jbloomlab.github.io/SARS-CoV-2-RBD_DMS_Omicron/RBD-heatmaps/

![Screen Shot 2022-08-02 at 10 27 07 AM--BloomLab RBD Heat Map, K444R (-0 10, -0 04), K444R (-0 16, -0 08), K444T (-0 10, -0 19)](https://user-images.githubusercontent.com/33738461/182401614-33d37d9f-bf6d-4d27-a1fa-94af5a1cab4b.png)

**Genomes**
[GISAID_hcov-19_ids_2022_08_02_14_06.csv](https://github.com/cov-lineages/pango-designation/files/9243137/GISAID_hcov-19_ids_2022_08_02_14_06.csv)

**Comment by corneliusroemer** [comment]
This is up to 200 sequences now on GISAID and clearly growing faster than BA.5(.6) - given the Spike mutation with escape potential this deserves immediate designation in my view.

It also makes up ~5% of recent sequences from Ecuador (though only 7 sequences in total, still interesting)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.6.2 with 45 newly designated sequences, and 24 updated designations from BA.5.6. Defining mutation(s) A22893C (S:K444T).
