### ISSUE TITLE
BA.4 sublineage with S:W152R (69 seq. mostly UK plus 6 countries as of 03.08.22)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#904]
Proposal for a sublineage of BA.4
Earliest sequence: 20.05.2022 (UK)
Countries detected: mostly UK (38) but also France, Netherlands, Belgium, Australia, Germany, USA

Defining mutation:
T22016C = S:W152R
T4738C
C29149T

This variant is defined by S:W152R, T4738C, C29149T and was first detected in UK. Now it is present in 6 other countries across 3 continents. 69 seq on Usher as of 03.08.22.

![grafik](https://user-images.githubusercontent.com/102166254/182544463-9d2fb872-7d46-4084-867c-4aaf05a1115d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f8ae_a16ba0.json?branchLabel=aa%20mutations&c=gt-nuc_4738,29149,22016

Subclades also carry S:F157L, S:T676I, S:S1261P:
![grafik](https://user-images.githubusercontent.com/102166254/182543484-d51e0f4e-4f64-42bb-bf92-36e848b13a63.png)

![grafik](https://user-images.githubusercontent.com/102166254/182544590-c45a76a3-2b98-48a3-bb01-66fef487af24.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AW152R&nucMutations=T4738C%2CC29149T&pangoLineage=BA.4*&

No real advantage vs. BA.4 global 3 months:
![grafik](https://user-images.githubusercontent.com/102166254/182544717-61231656-d96c-4238-9721-ea39b179f849.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.4*&aaMutations1=S%3AW152R&nucMutations1=T4738C%2CC29149T&pangoLineage1=BA.4*&analysisMode=CompareToBaseline&

Growth advantage of BA.4.6 with S:W152L is much higher  #900

EPI_ISL_13253720, EPI_ISL_13382901, EPI_ISL_13416894, EPI_ISL_13569874, EPI_ISL_13620855, EPI_ISL_13621569, EPI_ISL_13709802, EPI_ISL_13747126, EPI_ISL_13826477, EPI_ISL_13827306, EPI_ISL_13847743, EPI_ISL_13859066, EPI_ISL_13870981, EPI_ISL_13870991, EPI_ISL_13871043, EPI_ISL_13893607, EPI_ISL_13917799, EPI_ISL_13918009, EPI_ISL_13918011, EPI_ISL_13926902, EPI_ISL_14015415, EPI_ISL_14031762, EPI_ISL_14031972, EPI_ISL_14063201, EPI_ISL_14093506, EPI_ISL_14138972, EPI_ISL_14146603, EPI_ISL_14174439, EPI_ISL_14198715

ON941227.1, ON976674.1, OX027100.1, OX125403.1, OX129801.1, OX129804.1, OX129830.1, OX133570.1, OX137002.1, OX139623.1, OX148404.1, OX151958.1, OX151999.1, OX153688.1, OX153821.1, OX154139.1, OX154534.1, OX154557.1, OX154653.1, OX154700.1, OX155036.1, OX162069.1, OX242946.1, OX242947.1

**Comment by FedeGueli** [comment]
It appears really 'slow' in comparison to world dominant BA.5.2* , let see if the S:157L branch could catch up with the baseline.
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5.2*&aaMutations1=S%3A152R&nucMutations1=C29149T&pangoLineage1=BA.4*&analysisMode=CompareToBaseline&

**Comment by agamedilab** [comment]
74 seq on Usher as of 22.08.22. No real advantage vs. BA.4. I think i can close this.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AW152R&nucMutations=T4738C%2CC29149T&nextcladePangoLineage=BA.4*&aaMutations1=S%3AW152R&nucMutations1=T4738C%2CC29149T&pangoLineage1=BA.4*&
