### ISSUE TITLE
Potential BA.5.2.3 sublineage with ORF1a:V28I (436 seqs as of 2022-09-11, multiple countries, largest number of samples from Sweden)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#909]
There may be a BA.5.2.3 sublineage with ORF1a:V28I (G347A) first detected in England, United Kingdom.

As of 2022-08-03, Cov-Spectrum reports 168 BA.5.2.3+ORF1a:28I sequences:
![BA 5 2 3+ORF1a_28I_Counts](https://user-images.githubusercontent.com/88959107/182743826-b757ad85-6c2a-427e-9a03-91c7d5f154b6.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.3+%26+ORF1a%3AV28I&

As of 2022-08-03, Cov-Spectrum calculates a growth advantage of 57% compared to BA.5.2.3* in Denmark, although the growth in Denmark may have started to decline:
![BA 5 2 3+ORF1a_28I_Growth_Denmark](https://user-images.githubusercontent.com/88959107/182743797-bbd11726-f9e8-42de-a1fc-4ef76620119e.png)
Source: https://cov-spectrum.org/explore/Denmark/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.3*&variantQuery1=nextcladePangoLineage%3ABA.5.2.3+%26+ORF1a%3AV28I&analysisMode=CompareToBaseline&

As of 2022-08-03, UShER shows all of the GenBank samples are on a single subtree:
![BA 5 2 3+ORF1a_28I_UShER](https://user-images.githubusercontent.com/88959107/182743743-31619f13-b9ab-44cc-8486-64bd3dfbf2cf.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice1_genome_BA.5.2.3%2BORF1a_28I.json

First GenBank sequence: England, United Kingdom 2022-06-06 

Most Recent GenBank sequence: Georgia, USA 2022-07-17

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at 
[Support_BA.5.2.3+ORF1a_28I.zip](https://github.com/cov-lineages/pango-designation/files/9255966/Support_BA.5.2.3%2BORF1a_28I.zip)

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=BA.5.2.3&muts=ORF1a%3AV28I.

**Comment by alurqu** [comment]
Digging a bit deeper, most of these (159 as of 2022-08-04) also have ORF1a:T3750I (C11514T) which may correspond to introduction to Denmark from the UK.

Counts for BA.5.2.3+ORF1a:28I+ORF1a:3750I are available from https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.3+%26+ORF1a%3AV28I+%26+ORF1a%3AT3750I&

Growth advantage for BA.5.2.3+ORF1a:28I+ORF1a:3750I over BA.5.2.3 in Denmark is available from https://cov-spectrum.org/explore/Denmark/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.3*&variantQuery1=nextcladePangoLineage%3ABA.5.2.3+%26+ORF1a%3AV28I+%26+ORF1a%3AT3750I&analysisMode=CompareToBaseline&

The Outbreak.info link for BA.5.2.3+ORF1a:28I+ORF1a:3750I is https://outbreak.info/situation-reports?pango=BA.5.2.3&muts=ORF1a%3AV28I&muts=ORF1a%3AT3750I.

A subclade of BA.5.2.3+ORF1a:28I+ORF1a:3750I also has S:L5I.  As of 2022-08-04 Cov-Spectrum only reports 49 sequences for this subclade, but it might have higher growth possiibly related to the spike mutation.

Counts for BA.5.2.3+ORF1a:28I+ORF1a:3750I+S:L5I are available from https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.3+%26+ORF1a%3AV28I+%26+ORF1a%3AT3750I+%26+S%3AL5I&

Growth advantage for BA.5.2.3+ORF1a:28I+ORF1a:3750I+S:L5I over BA.5.2.3 in Denmark is available from https://cov-spectrum.org/explore/Denmark/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.3*&variantQuery1=nextcladePangoLineage%3ABA.5.2.3+%26+ORF1a%3AV28I+%26+ORF1a%3AT3750I+%26+S%3AL5I&analysisMode=CompareToBaseline&

The Outbreak.info link for BA.5.2.3+ORF1a:28I+ORF1a:3750I+S:L5I is https://outbreak.info/situation-reports?pango=BA.5.2.3&muts=ORF1a%3AV28I&muts=ORF1a%3AT3750I&muts=S%3AL5I.

**Comment by alurqu** [comment]
As of 2022-08-08, Cov-Spectrum now shows 265 samples with Sweden having the greatest number.

**Comment by corneliusroemer** [comment]
Doubling only in more than a month means this will disappear soon. Let's reopen if something interesting happens inside this.
