### ISSUE TITLE
New lineage proposal of SARS-CoV-2 strains having D614G, P681H and V1230L mutations in S glycoprotein

### ISSUE THREAD

**Issue by 08011990** [cov-lineages/pango-designation#91]
Submitted by Rakesh Sarkar (Senior Research Fellow, Division of Virology, ICMR-NICED, Kolkata, West Bengal, India) and Dr. Mamta Chawla-Sarkar (Scientist F, Division of Virology, ICMR-NICED)
Description:
Sub-lineage of B.1.1
Earlier sequence: EPI_ISL_1419458, collected on 1st January, 2021
Most recent: EPI_ISL_1589753, collected on 29 March, 2021
Country circulation: India
Characteristic: I identified 70 sequences exclusively from West Bengal of India. These sequences were characterized by 12 coexisting mutations including D614G, P681H and V1230L in S glycoprotein. The V1230L mutation was exclusive emerged in West Bengal, not previously identified globally. All the coexisting mutations are-
NSP4: D279N and L353F
NSP8: V26F
NSP12: P323L
S: D614G, P681H, V1230L and ±E484K
NS3: G172C
NS8: V62L
N: R203K, G204R
P681H has previously been observed in UK variant and associated with higher infectivity, whereas E484K has previously observed in South African variant and Brazilian variant and associated with low sensitivity to neutralizing antibody induced by infection or vaccination. V1230L, which is not observed previously, is present in transmembrane domain (TM) of S2 subunit of S glycoprotein. This transmembrane domain anchors S glycoprotein to the virus envelope. The replacement of valine with more hydrophobic amino acid leucin could tighten the association of S glycoprotein to the viral envelope and also increase S glycoprotein incorporation into the viral envelope. However, further studies are required to reveal the functional relevance of this mutation.
The new variant having D614G, P681H, V1230L and E484K mutations in the S glycoprotein is expected to have increased infectivity, high transmissibility, and lower sensitivity to neutralization antibodies.

Genomes accession number: 
[New Microsoft Word Document.docx](https://github.com/cov-lineages/pango-designation/files/6523239/New.Microsoft.Word.Document.docx)

Phylogenetic analysis by MEGA X:
Phylogenetic analysis of 38 representing strains of this new variant along with 113 reference sequences of different clades/variants  revealed they emerged from GR clade (Pango lineage B.1.1 or Nextrain clade 20B) and formed a new cluster.
[Figure 1.pdf](https://github.com/cov-lineages/pango-designation/files/6527565/Figure.1.pdf)

Phylogenetic analysis by Nextstrain:
We also analyzed the position of the 38 representing strains of the new variant within the nexstarin tree. Results revealed that they formed a new cluster within the 20B clade (GISAID clade GR/Pango lineage B.1.1).
[Tree.pdf](https://github.com/cov-lineages/pango-designation/files/6528162/Tree.pdf)

 Proposed lineage name: GRL or B.1.1/S:V1230L or 20B/S:V1230L

**Comment by AngieHinrichs** [comment]
Hi @08011990 - I don't see any genome accession numbers in the Microsoft Word document, only lists of Spike mutations.  However, I was able to extract some EPI_ISL_ IDs from Figure 1.pdf, and have attached those in a text file:
[pango-designation-91.txt](https://github.com/cov-lineages/pango-designation/files/6536827/pango-designation-91.txt)

Here is an interactive Nextstrain view of their placement by [UShER](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace) in UCSC's tree of all SARS-CoV-2 sequences:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-91.json?branchLabel=Spike%20mutations&c=pango_lineage&label=nuc%20mutations:G12167T,G25906T

The UCSC tree has a total of 120 sequences on the S:V1230 branch.  All are from India except two sequences from New Jersey, USA (USA/NJ-PHEL-21-6034/2021|EPI_ISL_1254225|2021-03-01 and USA/NJ-CDC-LC0010466/2021|EPI_ISL_1030751|21-01-25 also in GenBank as [MW640825.1](https://www.ncbi.nlm.nih.gov/nuccore/MW640825.1)).  Here is a file with the names, EPI_ISL IDs and sample collection dates (earliest 2020-08-31, latest 2021-03-29):

[pango-designation-91.2021-05-24.txt](https://github.com/cov-lineages/pango-designation/files/6537094/pango-designation-91.2021-05-24.txt)

And finally here is a view of the E484K branch with 26 sequences total with dates ranging from 2021-01-20 to 2021-03-29:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-91.json?branchLabel=Spike%20mutations&c=pango_lineage&label=nuc%20mutations:G23012A,C29119T

**Comment by 08011990** [comment]
Thank You for analysis. I hope this new new variant should belong to a new lineage.

**Comment by 08011990** [comment]
I have seen that this new variant was labelled as B.1.1.220 by GISAID. Is that name was designated by GitHub?

**Comment by chrisruis** [comment]
Thanks @08011990 for submitting this. We've added this as lineage B.1.624 in [v1.2.18](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.18). We've started the lineage at the S:V1230L branch from @AngieHinrichs UShER tree view so there's 122 sequences in that clade with <5% ambiguity that have been designated B.1.624

**Comment by 08011990** [comment]
All the sequences are sub-lineage of B.1.1. So, the lineage name of this new variant should start with B.1.1.

**Comment by 08011990** [comment]
I did not understand why the lineage name starts with B.1.

**Comment by chrisruis** [comment]
Thanks for spotting that @08011990! You're right, this should have been a B.1.1 sublineage. We've now re-designated this as B.1.1.526. So B.1.624 is withdrawn and the 122 sequences that were initially designated B.1.624 are now designated B.1.1.526. These changes are in [v1.2.25](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.25)
