### ISSUE TITLE
BA.2.75.1 sublineage with S:939F, ORF1a:H3509Y, ORF1b:R905K (5 seq. Austria)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#910]
Proposal for a sublineage of BA.2.75.1
Earliest sequence: 25.07.2022 (Austria)
Countries detected: Austria

Defining mutation:
C24378T = S:S939F
C10790T = ORF1a:H3509Y
C16181A = ORF1b:R905K
C28747A
C835T

This subvariant of BA.2.75.1 is defined by a novel combination of mutations (S:S939F, ORF1a:H3509Y, ORF1b:R905K, C28747A, C835T) and showed up in yesterdays upload in Austria. The clade is still small (5 seq as of 04.08.22 derived from a single upload & lab) but may represent inferred movement of the virus into a new country or region (founder event).

![grafik](https://user-images.githubusercontent.com/102166254/182784830-3b41539b-1c22-4f2a-a3fe-cf901fb42d71.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2b6b_b62c40.json?branchLabel=aa%20mutations&c=pango_lineage&label=nuc%20mutations:A23283T

![grafik](https://user-images.githubusercontent.com/102166254/182780080-7796a47b-da9b-41fa-8bd0-bfad3fb71bd5.png)

Too early to query effectively at covspectrum:

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AS939F%2CORF1a%3AH3509Y%2CORF1b%3AR905K&nucMutations=C28747A%2CC835T&

EPI_ISL_14217529
EPI_ISL_14217530
EPI_ISL_14217533
EPI_ISL_14217539
EPI_ISL_14217542

**Comment by corneliusroemer** [comment]
Not much happening here - still just 10 sequences.

I'll close for now to keep issues light but feel free to comment and ping me if something significant happens here.

Better query: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AS939F&nextcladePangoLineage=BA.2.75*&
