### ISSUE TITLE
BA.2.38.3 sublineage with S:144del, S:446S, S:452Q, Orf1a:A3357G and Orf1a:F1214I emerging in India (38 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#913]
Here i want to propose the sublineage that i mentioned in #814 , issue that led to the designationof  BA.2.38.3, a sublineage defined by S:69/70del S:71F S:K478R and S:V1264L, spotted first by @zach-hensel and then by @c19850727

The sublineage proposed here is defined by the following further mutations/deletions:

Spike:144del
Spike:446S
Spike:452Q
Orf1a:3357G
Orf1a:1214I

It actually represents around 40% of the recently designated  BA.2.38.3 .
Nr of sequences: between 38 and 44, cause when  i filter the [covspectrum query](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A478R%2CS%3A1264L%2CS%3A452Q&aaMutations1=ORF1a%3A556K%2CN%3AP364L%2CORF1a%3AD930N%2CORF1a%3AP3504L%2CN%3A136&nucMutations1=A11782G%2C12160A&nextcladeQcOverallScoreTo=99&) for high or medium quality sequences only i got 15 sequences carrying all the defining mutations, so i am convinced that also everything or quite everything after Orf1a:3357G carries the complete set of defining mutations.

List of sequences (only good and medium quality):

EPI_ISL_13611347
EPI_ISL_13611344
EPI_ISL_14053646
EPI_ISL_14080728
EPI_ISL_14098933
EPI_ISL_14154136
EPI_ISL_14154135
EPI_ISL_14154164
EPI_ISL_14154141
EPI_ISL_13908374
EPI_ISL_13908366
EPI_ISL_14192172
EPI_ISL_14196563
EPI_ISL_13968350
EPI_ISL_14228415

Countries:
This sublineage was tracked since it was just two sequences, and it emerged in India.
We(Me,Zach,Ryan and others) previously reported 4 importations in USA in 4 different states:
while two of them share a nuc mutation C18744T ( It is the biggest branch of  this lineage) and have been sampled in two subsequent days making us thinking they could have arrived with the same plane, the others two are unrelated both vs each other and vs the previous two mentioned above.
Interestingly there have been two samples coming from Poland: @ryhisner found they were localized in the same area, same city and both one mutation away from the other , so impossible to establish if  locally acquired or imported within a same family cluster.

Usher tree coloured by country:
![Schermata 2022-08-07 alle 17 45 38](https://user-images.githubusercontent.com/87669813/183299260-9a37d750-0285-423f-a112-92bc353083aa.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6ad9_fbb660.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C10335G

CovSpectrum Overview without filtering for good sequences only:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A478R%2CS%3A1264L%2CS%3A452Q&aaMutations1=ORF1a%3A556K%2CN%3AP364L%2CORF1a%3AD930N%2CORF1a%3AP3504L%2CN%3A136&nucMutations1=A11782G%2C12160A&

I think there are good reason to designate this one very fastly:
1) 8 Spike changes in line with BA.2.75 and other mulltiple mutated spike lineages which seem circulating now in India.
2) fast growth rate from 2 to 40 sequences with a steady fast accumulation of sequences.
3) international exportations that could make us imagine a higher prevalence somewhere in India than we can measure from samples uploaded to Gisaid
4)Presence of S:478R mutation that is different in a key RBM residue from everything circulating in the last year and half.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BH.1 with 14 newly designated sequences, and 1 updated designation from BA.2.38.3. Defining mutations T3905A (ORF1a:F1214I), T22917A (S:L452Q).

**Comment by FedeGueli** [comment]
Thx @InfrPopGen for fast designation, yesterday new samples came from Australia,Japan, Canada, Usa representing an uptick in prevalence in India. Lets see how it goes , being designated makes it very easier to track. Thx!

**Comment by FedeGueli** [comment]
@chrisruis @InfrPopGen i would like to highlight that BH.1 is mispositioned amongst the BA.5 sublineages in :
https://www.pango.network/summary-of-designated-omicron-lineages/
![Schermata 2022-08-30 alle 09 50 28](https://user-images.githubusercontent.com/87669813/187380934-ba57847f-8e15-4c3b-be10-3a4565d1fab6.png)

**Comment by FedeGueli** [comment]
Gisaid query : Nsp3_F396I, NSP5_A94G

**Comment by FedeGueli** [comment]
There were some BH.1 uploaded from United states recently, and two of them cluster together (one from Texas and one from Nevada) and they share a spike mutation : S:T768I.

**Comment by FedeGueli** [comment]
Of three imported cases in South Korea one is from Germany and one from Hungary.
total count is 184 now.
