### ISSUE TITLE
BA.2.38.2 sublineage with S:146del and Orf1a:445V (256 sequences) circulating in India

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#914]
This sublineage was spotted and described first by @silcn in #828 

"This lineage has a branch with S:146del that is concentrated in Assam, India, where it makes up 52 of the most recent batch of 81 samples, dated 06-20 to 07-01 and received 07-20. Prior to this, sequencing in Assam had been virtually non-existent since February.
In addition there are 2 sequences from other Indian states, 2 from the US and 1 from Germany, making 57 in total.

The Usher tree ignores deletions so S:146del doesn't form its own branch; however, it almost does, because all but one of the sequences also have ORF1a:G445V and nuc:C2623T" (@silcn)

After monitoring it for a while i think it is worth proposing it given the high numbers of sequences accumulated in a little while and the apparent growth rate comparable to BA.2.75 .

Definition
BA.2.38.2 sublineage with C28657T, C2623T, S:146del and Orf1a:445V 

Interestingly a sub-branch of this one got the Orf1a:A2529V mutation that was defining in AY.4, but looking at growth advantage its contribution seems irrelevant  or little relevant as today.

Tree:
![Schermata 2022-08-08 alle 08 01 09](https://user-images.githubusercontent.com/87669813/183349646-7f3cdc52-739f-4aa6-b446-7bb1577bbd14.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1b93d_ff2590.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:G1599T

nr of sequences : 214
Countries: this sublineage is circulating in India, but it has been exported to Usa, Germany, South Korea and Singapore
list of sequences (good quality only):  
EPI_ISL_13780306
EPI_ISL_13943369
EPI_ISL_13536761
EPI_ISL_13955494
EPI_ISL_13955475
EPI_ISL_14017365
EPI_ISL_14018196
EPI_ISL_14018128
EPI_ISL_14018135
EPI_ISL_14018131
EPI_ISL_14018206
EPI_ISL_14018130
EPI_ISL_14018174
EPI_ISL_14018172
EPI_ISL_14018171
EPI_ISL_14018177
EPI_ISL_14018136
EPI_ISL_14018209
EPI_ISL_14018207
EPI_ISL_14018205
EPI_ISL_14018146
EPI_ISL_14018183
EPI_ISL_14018145
EPI_ISL_14018194
EPI_ISL_14018141
EPI_ISL_14018139
EPI_ISL_14018184
EPI_ISL_14018147
EPI_ISL_14018180
EPI_ISL_14018195
EPI_ISL_14018138
EPI_ISL_14018190
EPI_ISL_14018150
EPI_ISL_14018155
EPI_ISL_14018193
EPI_ISL_14018199
EPI_ISL_14018158
EPI_ISL_14018189
EPI_ISL_14018197
EPI_ISL_14018153
EPI_ISL_14018151
EPI_ISL_14018157
EPI_ISL_14018154
EPI_ISL_14018162
EPI_ISL_14018149
EPI_ISL_14018152
EPI_ISL_14018159
EPI_ISL_14018161
EPI_ISL_14018203
EPI_ISL_14018164
EPI_ISL_14018166
EPI_ISL_14018202
EPI_ISL_14018165
EPI_ISL_14018169
EPI_ISL_14018168
EPI_ISL_14018163
EPI_ISL_14018123
EPI_ISL_14018200
EPI_ISL_14018167
EPI_ISL_13955440
EPI_ISL_14203500
EPI_ISL_14203472
EPI_ISL_14203499
EPI_ISL_14203467
EPI_ISL_14203468
EPI_ISL_14203547

CovSpectrum overview (sequences and countrie) : https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A157S%2COrf1a%3A445V%2CS%3A146-&aaMutations1=S%3A152R&nucMutations1=C29149T&pangoLineage1=BA.4*&

CovSpectrum overview (Growth rate BA.2.75 comparison):
https://cov-spectrum.org/explore/India/AllSamples/Past2M/variants?variantQuery=NextCladePAngoLineage%3ABA.2.75*&aaMutations1=ORF1a%3AN3725S%2Corf1a%3AT1543I%2CS%3A157S%2Corf1a%3A445V&analysisMode=CompareToBaseline&

This is the fourth of 4 lineages with comparable high transmissibility in India, i would say if number of sequences is a key factor to establish how much reliable are the growth rate comparisons this would be the 2nd for number of sequences after BA.2.75.
However as explained by @silcn in the original post also simple numbers can be affected by one single batch mass upload of sequences, so it is better waiting a bit to draw conclusions.

**Comment by silcn** [comment]
This lineage, more so than most other Indian lineage, is particularly susceptible to sequencing biases: almost all the Indian sequences are from Assam, which collected only 3 sequences between mid-February and mid-June, before massively ramping up to 78 sequences in the second half of June and 279 in July so far.

No doubt this lineage is fast, but looking at Assam alone, BA.2.75 appears to have the advantage. It's also impossible to tell whether this lineage has any advantage over BA.2.38.2, as it makes up basically 100% of BA.2.38.2 in Assam and basically 0% everywhere else.

**Comment by FedeGueli** [comment]
Thx @silcn i mentioned your reasoning on that two times in the issue. Still thanks for highlighting the exceptional situation in Assam: the last 2 months prevalence of this sublineage seems sky high (>60%)  and i wont take as gold the growth advantage of BA.2.75 in Assam over this sublineage being based just on 23 sequences of BA..2.75 sampled there.

**Comment by FedeGueli** [comment]
256seqs as today
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2b818_10a0f0.json?label=nuc%20mutations:C4893T,A11439G

**Comment by FedeGueli** [comment]
I'll close this for now , it doesnt seem to have any advantage. If something will change i will reopen it

**Comment by FedeGueli** [comment]
Just 2 new sequence of this lineage uploaded today from West Bengala. So better keeping it closed as today.
