### ISSUE TITLE
Potential BA.5.2 sublineage with ORF3a:T14I (821 seqs as of 2022-09-17; Australia, Asia, North America, Europe)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#916]
There may be a BA.5.2 sublineage with ORF3a:T14I (C25433T) with the first known detection in New South Wales, Australia with detected spread to Asia, North America, and Europe.  Note that detections in Indonesia and Thailand occurred very soon after the detection in New South Wales.

Also note that ORF3a:T14I (C25433T) was one of the defining mutations for AY.43.1 (see the [designation comment on Issue 319](https://github.com/cov-lineages/pango-designation/issues/319#issuecomment-971824194)).

As of 2022-08-08, Cov-Spectrum reports 174 BA.5.2+ORF3a:14I sequences:
![BA 5 2+ORF3a_14I_Counts_20220808](https://user-images.githubusercontent.com/88959107/183463622-68e6b6b9-f7ec-4f3c-aa85-ee9cedb2731e.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2+%26+ORF3a%3AT14I&

Growth estimates are early and may be high, but here are the current Cov-Spectrum estimates as of 2022-08-08:

Cov-Spectrum calculates a growth advantage of 48% compared to BA.5.2* in the United States:
![BA 5 2+ORF3a_14I_Growth_vs_BA 5 2_USA_20220808](https://user-images.githubusercontent.com/88959107/183463569-605c5e5b-e545-4aa1-82fd-f43536a62f70.png)
Source: https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2*&variantQuery1=nextcladePangoLineage%3ABA.5.2+%26+ORF3a%3AT14I&analysisMode=CompareToBaseline&

Cov-Spectrum calculates a growth advantage of 56% compared to BA.5* in the United States:
@BA.5 Growth image@ ![BA 5 2+ORF3a_14I_Growth_vs_BA 5_USA_20220808](https://user-images.githubusercontent.com/88959107/183463531-4d9f1c7e-70a9-4434-922a-0e82f255b27a.png)
Source: https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABA.5.2+%26+ORF3a%3AT14I&analysisMode=CompareToBaseline&

As of 2022-08-08, UShER shows all of the GenBank samples are on a single subtree:
![BA 5 2+ORF3a_14I_UShER_20220808](https://user-images.githubusercontent.com/88959107/183463462-0617fb8d-fb82-4a05-88ca-6bb4d27722c5.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice1_genome_BA.5.2%2BORF3a_14I.json

First Outbreak.info sequences: New South Wales, Australia 2022-06-13; Indonesia, 2022-06-14; Thailand, 2022-06-15

First GenBank sequence: Florida, USA 2022-06-17 

Most Recent GenBank sequence: Connecticut, USA 2022-08-01

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at 
[Support_BA.5.2+ORF3a_14I.zip](https://github.com/cov-lineages/pango-designation/files/9283339/Support_BA.5.2%2BORF3a_14I.zip)

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=BA.5.2&muts=ORF3a%3AT14I&loc=USA&loc=GBR&loc=AUS&loc=IDN&loc=KOR&loc=SGP&loc=EST&loc=THA&loc=ISR&loc=DNK&loc=JPN&loc=ITA&loc=FRA&selected=Worldwide&overlay=false.

**Comment by FedeGueli** [comment]
191 seqs on covspectrum as today

**Comment by alurqu** [comment]
As of 2022-08-24, South Korea has reported 103 sequences of BA.5.2+ORF3a:T41I and has the most occurrences of potential sublineage.

**Comment by FedeGueli** [comment]
385 seqs as today. fast growing one.

**Comment by corneliusroemer** [comment]
Not sure this is doing much - lets monitor further

**Comment by FedeGueli** [comment]
424 sequences on Gisaid ( query : NS3_T14I,NSP13 T127N)

, it should be added that this likely originated in Indonesia , where it represents 39 out of 7064 samples after 14th of June

@corneliusroemer in the list of the proposed still undesignated  lineages it is the 4th ordering it for Low CI and the one with more sequences in the first 4 
![Schermata 2022-08-26 alle 14 53 09](https://user-images.githubusercontent.com/87669813/186907782-b14d2069-54f1-4b26-b5f9-be0e13107c5c.png)
https://cov-spectrum.org/collections/23

So to me it is clearly doing something and it should be designated.
.

**Comment by FedeGueli** [comment]
533 virus on Gisaid as today

**Comment by FedeGueli** [comment]
Eventually it could be decided if @alurqu agree to designate it starting with an additional Orf1a:D2026A: Gisaid query NSP3_D1208A,NS3_T14I,NSP13_T127N intercepts 298 sequences of this sub sublineage of which the half coming from South Korea (153 seqs). 
This represents quite 100% of South Korean sequences of this sublineage (153/156)

Interesting designating this from Orf1a:D2026A got also the most of Japanese sequences (31) which cluster together in a well defined branch with an additonal spike mutation:S:H1083Y
![Schermata 2022-09-01 alle 10 55 32](https://user-images.githubusercontent.com/87669813/187874501-a32b98cd-4536-490a-b8ae-7ef105c038bf.png)


and and Indonesian Australian cluster defined by orf1a: L2778F
![Schermata 2022-09-01 alle 10 55 51](https://user-images.githubusercontent.com/87669813/187874585-a1af20aa-45ed-4252-b35b-d08b5db84b7c.png)

Here the bigger picture:
![Schermata 2022-09-01 alle 10 52 21](https://user-images.githubusercontent.com/87669813/187873822-cce8b3cf-d127-4090-8ab0-59c2338eaeca.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_7787_71bc0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C8597T

@alurqu @corneliusroemer if you have time take  a look at my proposal about it:
1) Designate this lineage starting deeper in the tree  with  Orf1a:D2026A 
2)Designating the Japanese cluster clearly corresponding with S:H1083Y

**Comment by alurqu** [comment]
@FedeGueli Ultimately how and even if this lineage gets designated is not in my control.  That is the scope of the Lineage Designation Committee (LDC).  My only role is to humbly call the LDC's attention to lineages that may need to be designated.

With that said, I'll note that McGrath et al https://doi.org/10.1073/pnas.2204717119 found that deletions of ORF3a/b attenuated SARS-CoV-2 even in interferon-incompetent cells, so to me it seems plausible that the ORF3a:T14I mutation may have changed the fitness of the virus.

It could be reasonable to grant BA.5.2+ORF3a:T14I a lineage designation and possibly grant the branches you mentioned designation as sublineages.  Or perhaps the LDC would prefer to go straight to designating the sublineages.  I will leave that to the wisdom of the LDC.

**Comment by corneliusroemer** [comment]
Ah this is on the ORF1b:1050N branch - ok I'll designate to reduce number of unspecified BA.5.2 on that branch

**Comment by FedeGueli** [comment]
Nice this ome got a name. it is quite fast among the lineages without 346/444/460 so being quite big it could have opportunity to acquire one of them and jump to high ranks.
