### ISSUE TITLE
BA.2.75.3 sublineage with S:R346T (35seq, 20xIndia/5xSingapore, also Israel, Belgium, US, as of 2022-08-21)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#918]
Proposal for a sublineage of BA.2.75
Earliest sequences: 2022-07-12 (India and Singapore)
Countries detected: India (2-4 from West Bengal, 2 from Telangana), Singapore (2), USA (1)

Mutations in addition to BA.2.75: ORF1b:V1706I and S:R346T.
ORF1b:V1706I is a large branch making up around 20% of BA.2.75. This lineage is not the only emergence of S:R346T on this branch - see below.

S:R346T is popping up repeatedly all over the BA.2.75 tree. Unfortunately most of the sequences are poor quality, with lots of NNNs and artefactual reversions, so it takes some work to figure out what's real and what's related to what; in particular, there are lots of sequences classified as BA.2.75 with S:346T that have S:339D rather than 339H and look like contamination with BA.2.74 or BA.2.76. But even the ones with S:339H still often get misplaced by Usher, and I had to edit the fastas in order to get them placed correctly.

However, I think there are at least 9 emergences of BA.2.75* + S:346T that look like they could be genuine. This lineage is the largest. The others are:
- S:346T directly on the BA.2.75 polytomy (3 sequences: EPI_ISL_14175634, EPI_ISL_14290506, EPI_ISL_14215529, from 3 different Indian states)
- S:346T directly on the BA.2.75.1 polytomy (2 sequences: EPI_ISL_14285583, EPI_ISL_14290481, one from Australia and one from India)
- 6 separate singlets. 2 of these are BA.2.75.1. Another 2 are on the ORF1b:V1706I branch, like the lineage proposed here; one of them is even misplaced within this lineage by Usher (see explanation below).

Here is an Usher tree that shows all of them: [https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_8f6f_12a0f0.json?c=userOrOld](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_8f6f_12a0f0.json?c=userOrOld)

While none of the S:346T lineages are big enough to need a designation yet, the fact that there are already so many of them is interesting in its own right, and that's why I'm proposing this lineage. 

The reason why I've said "7-9 sequences" is that two of the sequences additionally have S:F486S and S:F490S. S:F486S is another mutation that's popped up a lot in BA.2.75 - I count at least 4 indepenent emergences, I expect I'll end up proposing one soon enough - and it's not clear whether these two sequences genuinely belong on the S:346T branch or whether S:486S came first. The 486S+490S branch could be deserve its own designation if it spreads enough. 

In addition, a third sequence with S:F486S (WB-INSACOG-1931300701724, EPI_ISL_14303286) gets misplaced on the S:R346T branch by Usher, when it belongs instead on the branch defined by ORF1a:Q1198K. This singlet is omitted from the Usher tree below.

<img width="700" alt="BA275_R346T_1" src="https://user-images.githubusercontent.com/42699509/183468046-71ea9434-cbd9-49bd-a622-080370daf6fb.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_43005_1336c0.json?branchLabel=Spike%20mutations&c=gt-S_486&label=nuc%20mutations:G22599C](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_43005_1336c0.json?branchLabel=Spike%20mutations&c=gt-S_486&label=nuc%20mutations:G22599C)

Genomes:
EPI_ISL_14049579
EPI_ISL_14101261
EPI_ISL_14175839
EPI_ISL_14215511
EPI_ISL_14215585
EPI_ISL_14295558
EPI_ISL_14302969
and possibly
EPI_ISL_14175700
EPI_ISL_14303178

Not going to try coming up with a cov-spectrum query yet, given how often 346T seems to be appearing...

**Comment by FedeGueli** [comment]
Thx  @silcn @ryhisner was tracking that too. Not surprising to see that one popping up in BA.2.75 , two days ago while checking a proposed BA.5.2 +S:346T i got 16 different trees back from Usher (most luckily just singlets).

Sincerely i think that it is too soon to propose or designate anything else in BA.2.75 before it started a sustained growth outside India, but agree it is useful to show and track how things are going.

**Comment by silcn** [comment]
@FedeGueli yeah part of my motivation in proposing this was just to post that Usher tree with the correct placements of the BA.2.75+R346T sequences. Don't mind if this issue becomes a place to monitor the others too.

**Comment by RajLABN** [comment]
There is a couple with Spike_D1199N and Spike_R346T (one from Chile and the other from Delhi)

**Comment by silcn** [comment]
Yes good spot @RajLABN, those two also have S:F486S. The Delhi one is in the Usher tree I posted, the Chile one was uploaded while I was making the tree.

**Comment by corneliusroemer** [comment]
The 2x Singapore, 2x India-TG, 1x USA-GA cluster also has 28657T - not sure why this isn't showing on Usher, maybe masked?

**Comment by silcn** [comment]
@corneliusroemer 28657T shows up for me?

**Comment by corneliusroemer** [comment]
Right, I just didn't see it in your proposal hence assumed it wasn't visible in Usher.

**Comment by corneliusroemer** [comment]
We're now at 26 sequences here: 5x Singapore, 1x US, 20x India [Mostly WB, TG but few KA and DL]

Query for GISAID (would be nice if you provided one in your proposals @silcn  so one can quickly check with latest uploads):
```
Spike_R346T,NSP14_V182I,E_T11A,NSP3_S403L
```

There are now 7x S:486S, of which 3 have additional S:490S.

Probably still too early to designate as we can't be sure about monophyly and intermediary lineages but this issue is definitely worth watching closely.

**Comment by corneliusroemer** [comment]
Sorry if I missed this, but do we have a separate proposal for the BA.2.75 + ORF1b:V1706I lineage with S:346T and S:486S and S:490S?

Do we know if that triple-Spike lineage is a child of this or whether it is independent? @silcn your insights would be greatly appreciated.

Above you say:
>  The 486S+490S branch could be deserve its own designation if it spreads enough.

We now have 5 sequences (perhaps more) of that combo, one from Singapore, one from Israel.

These are new I think:
```
hCoV-19/Singapore/10046/2022|EPI_ISL_14458973|2022-08-10
hCoV-19/Israel/SMC-7099853/2022|EPI_ISL_14496326|2022-08-09
```

What makes things tricky is that there are ~40 sequences now with ORF1b:V1706I and S:486S, on

There are also ~40 sequences now with ORF1b:V1706I and S:346T

Yet these are not identical, the overlap is only 1/3 or so. So the sequencing of which came first and which is a child of which is not obvious at all.

**Comment by corneliusroemer** [comment]
It appears that S:346T appears in two contexts in BA.2.75.3:
- 28657T
- S:486S

There are sequences that have 346T without either of the above - but they are all from India and have lots of reversions.

So in this issue, the proposable lineage would be the 28657 one, as for the S:486S we still need to see whether S:346T or S:486S happened first.

**Comment by corneliusroemer** [comment]
I think we've figured this out now with various designations. Thanks for the discussion.
