### ISSUE TITLE
New lineage proposal Sub-lineage of: B.1.1.7 that is exclusive to USA,  with spike protein D178H and membrane protein V70L mutations

### ISSUE THREAD

**Issue by ShenLishuang** [cov-lineages/pango-designation#92]
New lineage proposal 
by Lishuang Shen, and Xiaowu Gai
Description
Sub-lineage of: B.1.1.7 that is exclusive to the USA

Earliest sequence: 2021-02-04 (hCoV-19/USA/CA-SEARCH-13556/2021, USA/CA-SEARCH-13588/2021  )

Most recent sequence: 2021-05-12:
hCoV-19/USA/KS-KHEL-1686/2021, 	EPI_ISL_2101377, 	2021-05-12, 	North America / USA / Kansas
hCoV-19/USA/CA-CDC-FG-033558/2021,	EPI_ISL_2160799, 	2021-05-11, 	North America / USA / California
hCoV-19/USA/CA-CDC-FG-033504/2021,	EPI_ISL_2160801, 	2021-05-11, 	North America / USA / California
hCoV-19/USA/CA-CDC-FG-033398/2021, , 	EPI_ISL_2160802, 	2021-05-11, 	North America / USA / California

Countries circulating: USA exclusive as of May 12, 2021  (2016 of 2016 genomes)

We identify a distinct cluster of B.1.1.7 infections where the virus genome carries both Spike S:D178H and M:V70L mutations, and it appeared to be 100% USA-exclusive as of May 12, 2021  (2016 of 2016 genomes) . This sub-lineage was first detected in California, USA, on February 4, 2021, and as of data freeze on May 1st, this sub-lineage appeared to be U.S.-specific with reported cases in 31 states, including Hawaii. In April 2021, it constituted 36.8% of all B.1.1.7 isolates in Washington. The percentage of B.1.1.7 isolates in the U.S. that belong to this sub-lineage increased from 0.15% in February 2021 to 1.8% in April 2021. Given the rapidly increased prevalence of this sub-lineage in Washington State, the exclusive presence in USA, and the fact that the prevalence within the B.1.1.7 lineage increased from 0.15% in February to 1.8% in April, we believe it is a distinct sub-lineage that needs a designated name.
 
Our preprint:  https://www.medrxiv.org/content/10.1101/2021.05.14.21257247v1

It was reported by:
The Global Virus Network: https://gvn.org/covid-19/u-k-variant/ , 

The CDC PHGKB COVID-19 Genomics and Precision Public Health Weekly Update, May 20, 2021 Issue: https://phgkb.cdc.gov/PHGKB/coVInfoClip.action?action=archive&date=05/20/2021

News-Medical Life Sciences: https://www.news-medical.net/news/20210521/Study-shows-distinctive-mutation-in-rapidly-emerging-SARS-CoV-2-B117-sublineage.aspx

Genomes (2016)

[B.1.1.7_USA_M_V70L_and_S_D178H.txt](https://github.com/cov-lineages/pango-designation/files/6527439/B.1.1.7_USA_M_V70L_and_S_D178H.txt)

Proposed lineage name
B.1.1.7/USA

Evidence:

![B 1 1 7_USA_M_V70L_and_S_D178H](https://user-images.githubusercontent.com/36009977/119246246-e0d9dd80-bb34-11eb-8f4e-66222fbd770f.png)
![B 1 1 7_USA_M_V70L_and_S_D178H_transmission](https://user-images.githubusercontent.com/36009977/119246249-e46d6480-bb34-11eb-8367-7cd10b7d7820.png)

![B 1 1 7_USA_M_V70L_and_S_D178H_Lineeage_and_genotypes](https://user-images.githubusercontent.com/36009977/119251801-58bbfe00-bb5d-11eb-8907-7dcaeaf5b9a5.png)

**Comment by chrisruis** [comment]
Thanks @ShenLishuang. We've added this as Q.3 in [v1.2.52](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.52) with 5357 sequence designations. We've taken the root of the lineage back slightly to correspond to the introduction of the lineage into the USA - G20962A occurred on the branch leading to the Q.3 common ancestor

**Comment by ShenLishuang** [comment]
> Thanks @ShenLishuang. We've added this as Q.3 in [v1.2.52](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.52) with 5357 sequence designations. We've taken the root of the lineage back slightly to correspond to the introduction of the lineage into the USA - G20962A occurred on the branch leading to the Q.3 common ancestor

Chris: Thank you for your diligent effort. Thank you for addressing this ticket. 

Lishuang Shen
Sr. Bioinformatics Scientist
Center for Personalized Medicine
Children's Hospital Los Angeles

**Comment by ShenLishuang** [comment]
Dear Chris:

Thank you and the pangolin team for your diligent effort. Thank you for
addressing this ticket.

Lishuang Shen
Sr. Bioinformatics Scientist
Center for Personalized Medicine
Children's Hospital Los Angeles
Email: ***@***.***, ***@***.***
Phone: 323-644-8507

Suite 300
2100 W 3rd St
Los Angeles, CA 90057
