### ISSUE TITLE
Proposal for a Sublineage of BE.1 with S:R346T, circulating in Costa Rica & USA

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#923]
**Description**
**Sub-lineage of:** BE.1
**Earliest sequence:** 2022-6-19, Costa Rica — EPI_ISL_13810320
**Most recent sequence:** 2022-7-29, Israel — EPI_ISL_14246577
**Countries circulating:** USA (31), Costa Rica (19), France (3), Netherlands (1), Spain (1), South Korea (1)
**Number of Sequences:** 55 on Usher tree; 64 sequences returned by GISAID query “M_D3N, N_E136D, NSP13_M233I, Spike_R346T” (several of which are not on Usher tree)
**Substitutions on top of BA.:**
Spike: R346T
Nucleotide: C1471T, G22599C (Two sequences from South Africa have C1471 but not G22599C)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_1ca43_382a90%E2%80%94BE.1%2BR346T.json 
![Screen Shot 2022-08-10 at 6 13 44 AM--BE 1+R346T Usher Tree](https://user-images.githubusercontent.com/33738461/183880129-e6661f5b-5811-4fb4-9295-dc4c5b1e570b.png)

**Evidence**
S:R346T is a known escape mutation that has granted virtually every lineage that has acquired it a growth advantage over its parent lineage. This sublineage of BE.1 appears to be no exception.
CovSpectrum: 60% (CI:15%-105%) weekly growth advantage for BE.1* + C1471T + G22599C compared to nextcladePangoLineage:BE.1* in the last three months in the USA: 
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ABE.1*&variantQuery1=nextcladePangoLineage%3ABE.1*+%26+C1471T+%26+G22599C&analysisMode=CompareToBaseline&

![image](https://user-images.githubusercontent.com/33738461/183880561-394fa363-cea0-4e9c-baef-3381e6c3ec1a.png)

In the past month, 4.63% of sequences from Costa Rica have been from this lineage: https://cov-spectrum.org/explore/Costa%20Rica/AllSamples/from=2022-07-10&to=2022-08-10/variants?variantQuery=nextcladePangoLineage%3ABE.1*+%26+C1471T+%26+G22599C&variantQuery1=nextcladePangoLineage%3ABE.1*+%26+C1471T+%26+G22599C& 

![Screen Shot 2022-08-10 at 6 20 54 AM--Costa Rica](https://user-images.githubusercontent.com/33738461/183880181-f9a3e41a-e114-4647-a8bb-49129980b89d.png)

**Genomes**
EPI_ISL_13713867, EPI_ISL_13726848, EPI_ISL_13807997, EPI_ISL_13808912, EPI_ISL_13810320, EPI_ISL_13865068, EPI_ISL_13883757, EPI_ISL_13884338, EPI_ISL_13907098, EPI_ISL_13911939, EPI_ISL_13915241, EPI_ISL_13959352, EPI_ISL_13978430, EPI_ISL_13979131, EPI_ISL_13979155, EPI_ISL_13991149, EPI_ISL_13993568, EPI_ISL_14003019, EPI_ISL_14010136, EPI_ISL_14010171, EPI_ISL_14011329, EPI_ISL_14011358, EPI_ISL_14031611, EPI_ISL_14048189, EPI_ISL_14048189, EPI_ISL_14051336, EPI_ISL_14057651, EPI_ISL_14070986, EPI_ISL_14071007, EPI_ISL_14071008, EPI_ISL_14071009, EPI_ISL_14071010, EPI_ISL_14071011, EPI_ISL_14071014, EPI_ISL_14071031, EPI_ISL_14076373, EPI_ISL_14180605, EPI_ISL_14180631, EPI_ISL_14186680, EPI_ISL_14202891, EPI_ISL_14221773, EPI_ISL_14221842, EPI_ISL_14221843, EPI_ISL_14221844, EPI_ISL_14221847, EPI_ISL_14221848, EPI_ISL_14221849, EPI_ISL_14236331, EPI_ISL_14239934, EPI_ISL_14246577, EPI_ISL_14260406, EPI_ISL_14267438, EPI_ISL_14275747, EPI_ISL_14282014, EPI_ISL_14295371, EPI_ISL_14305947, EPI_ISL_14306903, EPI_ISL_14310997, EPI_ISL_14337166

**Comment by corneliusroemer** [comment]
5% in Costa Rica is quite a lot, and S:346T is well known to confer growth advantage to BA.4/5* spike, e.g. see BA.4.6

So this is worthy of immediate designation in my view. Does not harm to designate early (it always takes time until designations propagate into assignments) @thomasppeacock @chrisruis @InfrPopGen what do you think?
