### ISSUE TITLE
BA.4.1 sublineage with S:R346T (79 seq as of 2022-08-10, ~70% in Zambia)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#926]
Proposal for a sublineage of BA.4.1
Earliest sequence: 2022-05-10 (South Africa) - ignoring two Zambian sequences with date errors
Countries detected: Zambia (34), USA (19), Israel (6), UK (4), Denmark (4), smaller numbers in 8 other countries

This lineage is defined by S:R346T directly on the BA.4.1 polytomy with no additional defining mutations. In particular, it is distinct from BA.4.1.8. It could in fact consist of several independent lineages that are impossible to tell apart.

This lineage currently appears to be dominant in Zambia, and has spread to multiple continents. S:R346T should be expected to provide an advantage over BA.4.1. There is a 7-sequence American sublineage with S:K444R.

<img width="738" alt="Zambia_BA41_R346T" src="https://user-images.githubusercontent.com/42699509/184006948-3714f2ca-4716-4f66-91a2-93c72104e3ef.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_3026f_403200.json?branchLabel=Spike%20mutations&c=country&label=nuc%20mutations:G22599C](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_3026f_403200.json?branchLabel=Spike%20mutations&c=country&label=nuc%20mutations:G22599C)

<details> <summary>EPI_ISLs</summary>

EPI_ISL_12872640
EPI_ISL_12969792
EPI_ISL_12969846
EPI_ISL_13604914
EPI_ISL_13605876
EPI_ISL_13606103
EPI_ISL_13606142
EPI_ISL_13638408
EPI_ISL_13731712
EPI_ISL_13773073
EPI_ISL_13774157
EPI_ISL_13781239
EPI_ISL_13806487
EPI_ISL_13830412
EPI_ISL_13898368
EPI_ISL_13969842
EPI_ISL_13986583
EPI_ISL_13993790
EPI_ISL_13993791
EPI_ISL_14002978
EPI_ISL_14005144
EPI_ISL_14005145
EPI_ISL_14005146
EPI_ISL_14005147
EPI_ISL_14005148
EPI_ISL_14005156
EPI_ISL_14005157
EPI_ISL_14005163
EPI_ISL_14005164
EPI_ISL_14005170
EPI_ISL_14005175
EPI_ISL_14005177
EPI_ISL_14005178
EPI_ISL_14005186
EPI_ISL_14005187
EPI_ISL_14005188
EPI_ISL_14015684
EPI_ISL_14026181
EPI_ISL_14029255
EPI_ISL_14037281
EPI_ISL_14045459
EPI_ISL_14052082
EPI_ISL_14055735
EPI_ISL_14077939
EPI_ISL_14090744
EPI_ISL_14175175
EPI_ISL_14176412
EPI_ISL_14177380
EPI_ISL_14178349
EPI_ISL_14178509
EPI_ISL_14192098
EPI_ISL_14197276
EPI_ISL_14197596
EPI_ISL_14213222
EPI_ISL_14215901
EPI_ISL_14227219
EPI_ISL_14227453
EPI_ISL_14227898
EPI_ISL_14236140
EPI_ISL_14269400
EPI_ISL_14279208
EPI_ISL_14283663
EPI_ISL_14291275
EPI_ISL_14291287
EPI_ISL_14294622
EPI_ISL_14327803
EPI_ISL_14327805
EPI_ISL_14327806
EPI_ISL_14327807
EPI_ISL_14327808
EPI_ISL_14327809
EPI_ISL_14327810
EPI_ISL_14327811
EPI_ISL_14327812
EPI_ISL_14327813
EPI_ISL_14327814
EPI_ISL_14327816
EPI_ISL_14327817

</details>

Putting together a cov-spectrum query would require excluding every other BA.4.1 branch with S:R346T and there are lots. If anyone wants to, please be my guest.

**Comment by FedeGueli** [comment]
Hi @silcn noticed in our list an uptick for BA.4.1.8 after the last covspectrum update, wondering if it is due to this sublineage and others misclassified as BA.4.1.8

**Comment by corneliusroemer** [comment]
The US lineage with S:346 and S:444 is now up to 13 sequences - probably worth monitoring given that this combination has independently popped up a number of times recently.

**Comment by FedeGueli** [comment]
@corneliusroemer now in our list. it seems fast and unsurprising as 444 seems the most beneficial mutation in BA.5 spike along with 346.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.4.1.9 with 62 newly designated sequences, and 5 updated designations from BA.4.1. Defining mutation G22599C (S:R346T).

**Comment by FedeGueli** [comment]
Gisaid Query to monitor the sublineage with S:444R:Spike_V3G,SPike_K444R,Spike_R346T 15 seqs as today ( last one from Denmark collected on 15/8)

**Comment by corneliusroemer** [comment]
The 444R lineage didn't grow that much anymore. We're at about 20 sequences now.

The Danish one is in a separate lineage proposed in #1073
