### ISSUE TITLE
BUG: We have duplicate strain names

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#929]
I just ran this script to check if we have duplicates - and unfortunately we do, around 890 of them.

```
csv2tsv lineages.csv | tsv-select -f1 | sort | uniq -c | sort -r | less
```

What's the best way to filter them out? I'm sure someone could quickly write a script that assigns them to the most derived lineage.

**Comment by corneliusroemer** [comment]
Pipe output into a file, select all the lines that start with `2` or more, then delete everything leading up to the pattern.

Then use the following command to se all the duplicated strains in pairs:
```
rg -j5 -F -f dup.txt lineages.csv | sort | less
```

This is an excerpt:
```
USA/WI-MHDL-2022050370/2022,BA.4.2
USA/WI-MHDL-2022050423/2022,BA.4
USA/WI-MHDL-2022050423/2022,BA.4.2
USA/WI-MHDL-2022050424/2022,BA.4
USA/WI-MHDL-2022050424/2022,BA.4.2
USA/WI-MHDL-2022050599/2022,BA.4
USA/WI-MHDL-2022050599/2022,BA.4.2
USA/WI-MHDL-2022060161/2022,BA.4
USA/WI-MHDL-2022060161/2022,BA.4.2
USA/WI-MHDL-2022060193/2022,BA.4
USA/WI-MHDL-2022060193/2022,BA.4.2
USA/WI-MHDL-2022060278/2022,BA.4
USA/WI-MHDL-2022060278/2022,BA.4.2
USA/WI-UW-10846/2022,BA.4
USA/WI-UW-10846/2022,BA.4.2
USA/WI-UW-10857/2022,BA.4
USA/WI-UW-10857/2022,BA.4.2
USA/WI-UW-11059/2022,BA.4
USA/WI-UW-11059/2022,BA.4.2
USA/WV-CDC-LC0641979/2022,BA.2
USA/WV-CDC-LC0641979/2022,BA.2.13
Vietnam/BMH-240422-sample43/2022,BA.2.3
Vietnam/BMH-240422-sample43/2022,BA.2.3.2
Vietnam/BMH-240422-sample45/2022,BA.2.3
Vietnam/BMH-240422-sample45/2022,BA.2.3.2
Vietnam/NHTD-OUCRU2514/2022,BA.2.3
Vietnam/NHTD-OUCRU2514/2022,BA.2.3.2
Vietnam/NHTD-OUCRU2528/2022,BA.2.3
Vietnam/NHTD-OUCRU2528/2022,BA.2.3.2
Wales/QEUH-3CFFF8A/2022,BA.2
Wales/QEUH-3CFFF8A/2022,BA.2.53
```

Probably we could just delete the first occurrence of a duplicated strain name - iterate through the file from end to start and remove any lines whose sequence has already occurred. Simple in a Python file, for example.

We could run this in CI to prevent duplicate lines in the future.

**Comment by winocm** [comment]
You can also use uniq(1) as well when piped to sort. (And uniq -c to see counts, pipe sort -nr on that to see a list of sorted results.)

I believe modern GNU sort(1) inside coreutils also supports parallelized operation as well.

**Comment by corneliusroemer** [comment]
Parallel sort is nice but not really needed (at least on my M1 it runs in <5s)

The implicit assumption in my algorithm proposal is that we designate from top to bottom and that later designations are superseding earlier ones.

**Comment by AngieHinrichs** [comment]
pango-designation already has a little script [findDups.sh](https://github.com/cov-lineages/pango-designation/blob/master/findDups.sh) that does this:
```
cut -d, -f1 lineages.csv |sort | uniq -c | awk '$1 > 1 {print $2;}' | grep -Fwf - lineages.csv | sort -u
```
-- the problem is that we forget to run it.  🙂  We need something like github actions I think.

**Comment by AngieHinrichs** [comment]
Oh my, we have 878 duplicated names currently.  I'll work on sorting them out.

**Comment by corneliusroemer** [comment]
I think just writing a simple script as suggested should work - now and in
the future! What do you think @AngieHinrichs?

**Comment by AngieHinrichs** [comment]
At first I thought so, but as I look at these, sometimes the first one listed in the file is not the one we want to keep.  I also tried to automate fixing these by using the lineage assigned by place in the UShER tree -- but spot-checking, now I see some examples where e.g. the UShER tree assigns BA.1 because the sequence is placed on a branch with reversions that are probably errors, while having the defining mutations of a more specific lineage like BA.1.14.  So I don't think there's a reliable way to auto-fix them.  

But if it's possible to add findDups.sh to some github action and raise an error if there is any output from findDups.sh then that would be handy in forcing us to resolve duplicates immediately instead of letting them accumulate.

**Comment by corneliusroemer** [comment]
Thanks to #948 we will now get immediately notified if there are duplicates in the future.
