### ISSUE TITLE
Potential BA.5.1 sublineage with  ORF1a:H417Y, ORF1b:A1476S, ORF1b:D1903N, ORF1b:T310I, ORF7a:L30H, S:R346T, and C10507T (71 seqs as of 2022-08-24; USA with international spread)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#930]
There may be a BA.5.1 sublineage with ORF1a:H417Y (C1514T), ORF1b:A1476S (G17893T), ORF1b:D1903N (G19174A), ORF1b:T310I (C14396T), ORF7a:L30H (T27482A), S:R346T (G22599C), C10507T first detected in Connecticut, USA with detected spread to the UK and Chile.

As of 2022-08-10, Cov-Spectrum reports 32 BA.5.1+ORF1a:417Y+ORF1b:1476S+ORF1b:1903N+ORF1b:310I+ORF7a:30H+S:346T+10507T sequences:
![BA 5 1+ORF1a_417Y+ORF1b_1476S+ORF1b_1903N+ORF1b_310I+ORF7a_30H+S_346T+10507T_Counts_20220810](https://user-images.githubusercontent.com/88959107/184029059-9dca5837-48d7-457f-bae9-4f75ab5af4b2.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.1+%26+ORF1a%3AH417Y+%26+ORF1b%3AA1476S+%26+ORF1b%3AD1903N+%26+ORF1b%3AT310I+%26+ORF7a%3AL30H+%26+S%3AR346T+%26+C10507T&

Early growth advantage estimates in the United States are substantially positive relative to BA.5* and BA.5.1*, but won't be mentioned at this time due to the low number of sequences and the risk of over-estimating the growth advantage.  However, links to find this information follow.

Growth advantage compared to BA.5.1* in the United States can be found at https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.1*&variantQuery1=nextcladePangoLineage%3ABA.5.1+%26+ORF1a%3AH417Y+%26+ORF1b%3AA1476S+%26+ORF1b%3AD1903N+%26+ORF1b%3AT310I+%26+ORF7a%3AL30H+%26+S%3AR346T+%26+C10507T&analysisMode=CompareToBaseline&

Growth advantage compared to BA.5* in the United States can be found at https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABA.5.1+%26+ORF1a%3AH417Y+%26+ORF1b%3AA1476S+%26+ORF1b%3AD1903N+%26+ORF1b%3AT310I+%26+ORF7a%3AL30H+%26+S%3AR346T+%26+C10507T&analysisMode=CompareToBaseline&

As of 2022-08-10, UShER shows all of the GenBank samples are on a single subtree:
![BA 5 1+ORF1a_417Y+ORF1b_1476S+ORF1b_1903N+ORF1b_310I+ORF7a_30H+S_346T+10507T_UShER_20220810](https://user-images.githubusercontent.com/88959107/184030756-7556a05b-3c13-45e5-a5da-c507fe698ecc.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice1_genome_BA.5.1%2BORF1a_417Y%2BORF1b_1476S%2BORF1b_1903N%2BORF1b_310I%2BORF7a_30H%2BS_346T%2B10507T.json

First Outbreak.info sequence: Connecticut, USA 2022-06-22 

First GenBank sequence: Pennsylvania, USA 2022-06-30 

Most Recent GenBank sequence: North Carolina, USA 2022-07-26

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at 
[Support_BA.5.1+ORF1a_417Y+ORF1b_1476S+ORF1b_1903N+ORF1b_310I+ORF7a_30H+S_346T+10507T.zip](https://github.com/cov-lineages/pango-designation/files/9304361/Support_BA.5.1%2BORF1a_417Y%2BORF1b_1476S%2BORF1b_1903N%2BORF1b_310I%2BORF7a_30H%2BS_346T%2B10507T.zip)

The closest Outbreak.info link for this potential lineage (nucleotide mutations are not supported) is https://outbreak.info/situation-reports?pango=BA.5.1&muts=ORF1a%3AH417Y&muts=ORF1b%3AA1476S&muts=ORF1b%3AD1903N&muts=ORF1b%3AT310I&muts=ORF7a%3AL30H&muts=S%3AR346T.

Opening this issue at a low sequence count due to presence of S:R346T in accord with [Issue 865](https://github.com/cov-lineages/pango-designation/issues/865).

Credit to @FedeGueli for initially calling out this lineage at https://github.com/cov-lineages/pango-designation/issues/865#issuecomment-1193372513 and https://github.com/cov-lineages/pango-designation/issues/865#issuecomment-1210267530.

**Comment by FedeGueli** [comment]
Growth advantage vs BA.5.2+ orf1b:1050N of this proposed BA.5.1 +346T + multiple Mutations   is still very large.
Probably actually this is the fastest BA.5.1 on earth.
cc @corneliusroemer @InfrPopGen @chrisruis @aq-sun
![Schermata 2022-08-28 alle 01 33 12](https://user-images.githubusercontent.com/87669813/187051519-b2e34cdf-ba5c-4783-a640-7899ff5c113a.png)

https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2*+%26+Orf1b%3A1050N&variantQuery1=nextcladePangoLineage%3ABA.5.1+%26+ORF1a%3AH417Y+%26+ORF1b%3AA1476S+%26+ORF1b%3AD1903N+%26+ORF1b%3AT310I+%26+ORF7a%3AL30H+%26+S%3AR346T+%26+C10507T&analysisMode=CompareToBaseline&

Ordering growth advantages of  proposed undesignated  lineages for the low Confidence interval this is the second for growth advantage vs BA.5.2 +Orf1b:1050N after the BA.5.2 + orf1b:1050N  + S:346T still undesignated.


![Schermata 2022-08-28 alle 01 37 17](https://user-images.githubusercontent.com/87669813/187051561-6f88580f-50c5-4aea-b5a5-71909c3062b0.png)

https://cov-spectrum.org/collections/23

To me a designation should be granted to this lineage that is the last very fast 346T lineage, keeping monitored the other proposed or not in the Multiple Issue open by @corneliusroemer

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.1.18 with 52 newly designated sequences, and 11 updated designations from BA.5.1. Defining mutation G22599C (S:R346T).
