### ISSUE TITLE
Proposal for Sublineage of BE.1.1 with S:K444T (181 seq on Usher tree, 158 seq on GISAID on Aug 22)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#931]
### **Description**
**Sub-lineage of:** BE.1.1
**Earliest sequences: ** 2022-6-18, England — EPI_ISL_13516412, EPI_ISL_13516487, EPI_ISL_13516510, EPI_ISL_13516613
**Most recent sequence: ** 2022-8-2, Austria — EPI_ISL_14355406
**Countries circulating:** Using GISAID query “Spike_K444T, NSP6_L260F, N_E136D”: UK (36), USA (25), Denmark (9), Nigeria (3), Netherlands (3), Canada (3), Italy (2), Japan (1), Singapore (1), South Korea (1), Austria (1), Israel (1), France (1), Chile (1)
**Number of Sequences:** 93 on Usher tree; 88 returned by GISAID query “Spike_K444T, NSP6_L260F, N_E136D” on August 10
**Substitutions on top of BA.:**
Spike: K444T
Nucleotide: A22893C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_2bc92_423f30%E2%80%94BE.1.1%20%2B%20K444T.json 
![Screen Shot 2022-08-10 at 9 00 17 PM - BE 1 1 + K444T Usher Tree](https://user-images.githubusercontent.com/33738461/184048485-653e58e4-d46d-4d77-ad35-6d873b1a739d.png)

**Evidence**
As discussed in Issue #903, S:K444 is the top RBD site for BA.5-neutralizing antibody escape mutation according to the Bloom Lab RBD escape calculator. 
![Screen Shot 2022-08-10 at 9 21 16 PM - K444 on Bloom Lab RBD escape calculator](https://user-images.githubusercontent.com/33738461/184049326-cc220788-162f-4635-b984-6dab37049f0e.png)

Only 60 of the ~90 sequences are on CovSpectrum, so I believe the growth advantage below is likely an underestimate.
CovSpectrum: 52% (CI:12-92%) weekly growth advantage for NextcladePangoLineage:BE.1.1 & S:K444T compared to NextcladePangoLineage:BE.1.1 in the last three months in the UK:
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ABE.1.1&variantQuery1=nextcladePangoLineage%3ABE.1.1+%26+S%3AK444T&analysisMode=CompareToBaseline&
![Screen Shot 2022-08-10 at 8 52 31 PM--BE 1 1 + K444T CovSpec](https://user-images.githubusercontent.com/33738461/184048505-29bbfddc-e218-4e3c-8c43-054ec45f5501.png)

CovSpectrum: 59% (CI:22-95%) weekly growth advantage for NextcladePangoLineage:BE.1.1 & S:K444T compared to NextcladePangoLineage:BA.5* in the last three months in the UK:
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABE.1.1+%26+S%3AK444T&analysisMode=CompareToBaseline&
![Screen Shot 2022-08-10 at 9 13 55 PM - BA 5* vs BE 1 1 + K444T CovSpec-UK](https://user-images.githubusercontent.com/33738461/184048827-1c30ab2b-4dca-4e21-b78a-92263867d333.png)

**Genomes**
EPI_ISL_13516412, EPI_ISL_13516487, EPI_ISL_13516510, EPI_ISL_13516613, EPI_ISL_13711986, EPI_ISL_13739098, EPI_ISL_13806783, EPI_ISL_13819186, EPI_ISL_13841901, EPI_ISL_13868423, EPI_ISL_13872614, EPI_ISL_13872781, EPI_ISL_13903163, EPI_ISL_13976680, EPI_ISL_13977018, EPI_ISL_14000707, EPI_ISL_14020329, EPI_ISL_14025181, EPI_ISL_14029905, EPI_ISL_14038463, EPI_ISL_14039574, EPI_ISL_14051169, EPI_ISL_14065444, EPI_ISL_14066637, EPI_ISL_14080109, EPI_ISL_14090117, EPI_ISL_14131124, EPI_ISL_14139182, EPI_ISL_14162781, EPI_ISL_14164195,
EPI_ISL_14164865, EPI_ISL_14164978, EPI_ISL_14165924, EPI_ISL_14171638, EPI_ISL_14172249, EPI_ISL_14172724, EPI_ISL_14173158, EPI_ISL_14176427, EPI_ISL_14180506, EPI_ISL_14182026, EPI_ISL_14184953, EPI_ISL_14192351, EPI_ISL_14194125, EPI_ISL_14194180, EPI_ISL_14196711, EPI_ISL_14205611, EPI_ISL_14211444, EPI_ISL_14235645, EPI_ISL_14235950, EPI_ISL_14235963, EPI_ISL_14240087, EPI_ISL_14254491, EPI_ISL_14258730, EPI_ISL_14265071, EPI_ISL_14266128, EPI_ISL_14287567, EPI_ISL_14287950, EPI_ISL_14288506, EPI_ISL_14289173, EPI_ISL_14289274, EPI_ISL_14291820, EPI_ISL_14291828, EPI_ISL_14291855, EPI_ISL_14294806, EPI_ISL_14296194, EPI_ISL_14300321, EPI_ISL_14301394, EPI_ISL_14301395, EPI_ISL_14302413, EPI_ISL_14304394, EPI_ISL_14305333, EPI_ISL_14305437, EPI_ISL_14305654, EPI_ISL_14314517, EPI_ISL_14317602, EPI_ISL_14317667, EPI_ISL_14328267, EPI_ISL_14331127, EPI_ISL_14333750, EPI_ISL_14333754, EPI_ISL_14336648, EPI_ISL_14340996, EPI_ISL_14352171, EPI_ISL_14355406, EPI_ISL_14368586, EPI_ISL_14382988, EPI_ISL_14383982, EPI_ISL_14385846,

**Comment by Sinickle** [comment]
Since 1 nucleotide mutations can be tricky, I'd like to point out that prior to the S:K444T, there is C28312T.

**Comment by ryhisner** [comment]
In addition to its growth advantage over its parent lineage, BE.1.1, as of today, this proposed lineage shows substantial and significant weekly growth advantage against BA.4.6:

Globally: 36% (CI: 23-50%) https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.4.6&variantQuery1=Nextcladepangolineage%3ABE.1.1+%26+S%3AK444T&analysisMode=CompareToBaseline&

In the UK: 18% (CI: 1-35%) https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.4.6&variantQuery1=Nextcladepangolineage%3ABE.1.1+%26+S%3AK444T&analysisMode=CompareToBaseline&

In Denmark: 94% (CI: 39-149%) https://cov-spectrum.org/explore/Denmark/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.4.6&variantQuery1=Nextcladepangolineage%3ABE.1.1+%26+S%3AK444T&analysisMode=CompareToBaseline&

In the USA: 25% (CI: 0-50%) https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.4.6&variantQuery1=Nextcladepangolineage%3ABE.1.1+%26+S%3AK444T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
This one is the only one (with >100 sequences)  together with BH.1 and BA.5.2+ S:444M showing a growth rate superior to BA.2.75 baseline.

But beyond this comparison that is preliminary and probably too spurious what it struck me since the beginning is that it has  a huge growth advantage versus BA.5.2 + Orf1b:1050N that is the leading main lineage of BA.5 growing toward 20% of total samples in the past month (probably more than that)
![Schermata 2022-08-21 alle 00 37 41](https://user-images.githubusercontent.com/87669813/185768333-68bd82e1-c212-472a-a631-5fbc16fd50f2.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5.2*+%26+Orf1b%3A1050N&variantQuery1=Nextcladepangolineage%3ABE.1.1+%26+S%3AK444T&analysisMode=CompareToBaseline&

**Comment by ryhisner** [comment]
7 of 59 sequences uploaded from Nigeria today are BE.1.1 + K444T, with collection dates ranging from July 21 to August 2.

**Comment by FedeGueli** [comment]
@ryhisner Great catch! this is confirmed by one of the first sequences of this sublineage was a South Korean airport surveillance from Nigeria! ( EPI_ISL_14254491 )

I think after this finding that it has a specific geographical origin with likely high prevalence (beyond the fact of being one of the fast growing BA.5 sublineage, check our **[LIST](https://docs.google.com/spreadsheets/d/1QTcmjAcMIl5NToWFPV0cWISrJyJY1k_XD3a__I9Kw40/edit#gid=0)**) a fast designation should be granted to this sublineage cc @corneliusroemer @chrisruis @InfrPopGen @aq-sun

**Comment by FedeGueli** [comment]
And also the BE.1.1 + C28312T that is basal to this proposed one is crowded by nigerian sequences. Further confirmation that it geographically likely emerged in that area

**Comment by corneliusroemer** [comment]
This should be designated as it is:
a) sufficient in numbers to be relevant
b) clear growth advantage
c) explainable by spike mutation
d) geographic spread and potentially high proportion in region with low sampling

**Comment by aq-sun** [comment]
Hi @ryhisner @corneliusroemer, I have designated this as BE.1.1.1 with 56 new designations and 1 updated from BE.1.1, with defining mutation A22893C (S:K444T).

**Comment by FedeGueli** [comment]
@ryhisner @corneliusroemer @InfrPopGen @chrisruis @aq-sun 
Detected a new potential sublineage of interest of this designated BE.1.1.1.
Defining mutations : Orf1b:Y264H and S:N460K 
7 sequences Usa Uk Japan ( This last one is travel from Egypt via Italy Israel to Japan and it is heavily mutated with also homoplasic S:261D,S:494P and S:603S suggesting circulation and evolution in undersampled area of Africa likely , due to that the likely origin of the here  designated  lineage is Nigeria)
Gisaid query: NSP12_Y273H,Spike_K444T,Spike_N460K finds 6 out of 7
CovSpectrum: 4 out of 7 [Overview](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A444T%2CS%3A460K%2Corf1b%3AY264H&nextcladePangoLineage=BE.1.1*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&)

tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ba8a_876050.json?c=pango_lineage_usher&label=nuc%20mutations:T14257C

List of sequences: 

EPI_ISL_14294806
EPI_ISL_14333750
EPI_ISL_14333754
EPI_ISL_14542445
EPI_ISL_14608324
EPI_ISL_14632425
England/PHEC-YYGIB6T/2022|2022-08-12




i ll monitor it for a while before proposing.

**Comment by FedeGueli** [comment]
Something we all missed and partially just @Sinickle noticed in #931 is that the nuc mutation C28312T in BE.1.1.1 together with 28311T (ORF9b:P10S) common to all Omicron sublineages gives an AA mutation Orf9b:P10F

BQ.1.1 From WT
![chrome_screenshot_1663777271748](https://user-images.githubusercontent.com/87669813/191559608-736d9f40-a623-4caf-977d-5e2839ae4a79.png)
BQ.1.1 from BA.2
![chrome_screenshot_1663777174500](https://user-images.githubusercontent.com/87669813/191560433-67977e30-c8ec-4d2e-a039-5bd01610f920.png)

cc @corneliusroemer @AngieHinrichs @InfrPopGen @chrisruis @thomaspeacock
It wasn't maybe so relevant until a potential dominant lineage as BQ.1.1 emerged from this root
