### ISSUE TITLE
Widespread (>3k sequences) BA.5.2.1 sublineage with Orf6:P57L dominating in Kenya (40% prevalence , 315 seqs there)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#932]
This sublineage should be designated before #893  spotted and proposed by @silcn that is a sublineage of the one proposed here.

The importance of this sublinegae it is the high prevalence in Africa as whole 
![Schermata 2022-08-11 alle 11 46 13](https://user-images.githubusercontent.com/87669813/184107279-698fd240-fd76-42a5-afbb-b04ab905f49d.png)
but especially in Kenya:
![Schermata 2022-08-11 alle 11 46 50](https://user-images.githubusercontent.com/87669813/184107394-e349dd63-ac97-4cad-a8e6-8a0fe553aa91.png)

it counts over 3000 sequences: 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=NextCladepangoLineage%3ABA.5.2.1*+%26+orf6%3AP57L+%26+orf9b%3A40K&variantQuery1=NextCladepangoLineage%3ABA.5.2.1*&

it is now widespread in 65 countries :
https://cov-spectrum.org/explore/Kenya/AllSamples/Past6M/variants/international-comparison?variantQuery=NextCladepangoLineage%3ABA.5.2.1*+%26+orf6%3AP57L&aaMutations1=Orf1b%3AA1643V%2CM%3A3N%2CS%3A255F&nucMutations1=G29032A&

it is slighty less transmissible than the parental BA.5.2.1: -5%

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=NextCladepangoLineage%3ABA.5.2.1*&variantQuery1=NextCladepangoLineage%3ABA.5.2.1*+%26+orf6%3AP57L&analysisMode=CompareToBaseline&

Note that Orf6:57L has been acquired via recomb or convergent evolution by BF.5 (alias S:1020S +orf9b:K40R) , 5 sequences, Uk

Tree kindly by @silcn ( iam off usher so i cant update as i wish) : https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_b985_5e9500.json?branchLabel=Spike%20mutations&c=country&label=nuc%20mutations:C241T,T670G,C1627T,C2790T,C3037T,G4184A,C4321T,T6979G,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,C26625T,G26709A,A27038G,C27371T,C27807T,C27889T,A28271T,C28311T,A28330G,G28881A,G28882A,G28883C,A29510C

**Comment by FedeGueli** [comment]
The designation of BF.15 makes very hard to designate its parental and intermediary with Orf6:P57L.

So i'll close this.
@corneliusroemer  .

**Comment by FedeGueli** [comment]
@chrisruis is this the same of your newly designated BF.20 from Kenya?

**Comment by silcn** [comment]
@FedeGueli BF.20 appears to be a sublineage of this, defined by ORF1a:T2274N. I guess that ends any hope of this lineage being designated.

**Comment by FedeGueli** [comment]
Thx @silcn ! Yeah i've closed it already after BF.15 was assigned .
