### ISSUE TITLE
BA.2.36.1 is probably not actually a sublineage of BA.2.36 as it misses 22792T

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#933]
I've seen discussions around BA.2.36.1 and BA.2.36 by @silcn and now I understand what the problem is: it appears BA.2.36.1 was wrongly designated as a child of BA.2.36

BA.2.36.1 lacks the important mutation 22792T that is unlikely to have reversed. The only thing that makes BA.2.36.1 suggest it is a child is S:68T which is definitely more plausible to have arisen through homoplasy than it is for synonymous 22792T to have reverted.

See: https://nextstrain.org/staging/nextclade/sars-cov-2/21L?branchLabel=aa&c=Nextclade_pango&f_Nextclade_pango=BA.2.36,BA.2.36.1

**Comment by FedeGueli** [comment]
This was well explained by @AngieHinrichs ,
it involved also BA.2.55 and BA.2.42  that usher showed as sublineage of BA.2.36 (i cant check them now, being off usher)

**Comment by FedeGueli** [comment]
Now it has been corrected in BA.2.82. so this is completed @corneliusroemer
