### ISSUE TITLE
BA.2 sublineage with S:L452M and S:R346S in England, US, Senegal, France, Germany and the Netherlands (24 samples)

### ISSUE THREAD

**Issue by JosetteSchoenma** [cov-lineages/pango-designation#934]
**Description**: Sublineage of BA.2 with S:L452M and S:R346S
**Earliest sequence**: 27th of June 2022 (England)
**Most recent sequence**: 1st of August 2022 (England)
**Countries**: England 16, US 3, Senegal 2, France 1, Germany 1, the Netherlands 1.
Number of sequences: 24 on the Usher tree
**Substitutions on top of BA2**:
Nucleotide: C29073T, G1599T
Spike: L452M, R346T

Even though the samples from Senegal aren't the earliest ones, seeing several earlier sequences from Senegal and Guinea with just the mentioned nucleotide changes, could mean this sublineage originated from that area.
Those nucleotide changes, that are present in less than 1% of BA.2.56 samples, also makes me think that this is a sublineage of BA.2, like Usher says, and not of BA.2.56 like Pangolin says. BA.2.56 has S:L452M.

**Usher tree:** https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_515c_4e2e60.json?label=nuc%20mutations:C29073T
![Screenshot_20220811-132416_Chrome.jpg](https://user-images.githubusercontent.com/94831035/184129467-d2b3d5ef-6a3c-4866-9180-a419b7770a96.jpg)

**CovSpectrum query**:
Leaving L452M out in purpose, because otherwise it somehow doesn't take the samples from Senegal.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AR346S&nucMutations=C29073T%2CG1599T&
 
**Samples**:
EPI_ISL_14324151
EPI_ISL_13745878
EPI_ISL_13744243
EPI_ISL_14024082
EPI_ISL_14020761
EPI_ISL_13881392
EPI_ISL_14323621
EPI_ISL_14199780
EPI_ISL_14300530
EPI_ISL_14177828
EPI_ISL_14295787
EPI_ISL_14024171
EPI_ISL_13771846
EPI_ISL_14142894
EPI_ISL_14024596
EPI_ISL_13954805
EPI_ISL_13748958
EPI_ISL_14024570
EPI_ISL_14199760
EPI_ISL_14172168
EPI_ISL_13987800
EPI_ISL_14024165

**Growth advantage**:
Too early to tell, but for now for the UK it says 167% (91-243%) over BA.2* and 45% (2-89%) over BA.5*
Over BA.2* will mean nothing soon. At least in the Netherlands there are just a few BA.2* per week left. Mostly chronically ill patients. So, this one is for over BA.5*.
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?variantQuery=NextcladePangolineage%3ABA.5*&aaMutations1=S%3AR346S&nucMutations1=C29073T&analysisMode=CompareToBaseline&

**Comment by corneliusroemer** [comment]
Small and dead - I'll close, we can reopen if an interesting sublineage appears.

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/25161793/190932970-e986e91d-4e3c-44cf-a93f-5081e5131778.png">

**Comment by Over-There-Is** [comment]
51
