### ISSUE TITLE
Potential BA.2.75 sublineage with S:L452R in India, Japan and Austria [40 sequences]

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#935]
Description: Sub-lineage of BA.2.75 with S:L452R
Earliest sequence:  07/2022 Karnataka, India [only month and year available] 
                              07/14/2022 Rajasthan, India 
Most recent sequence:  08/01/2022 Austria
Countries: India, Japan (1) and Austria (1)
Number of sequences:  28
Unique Nucleotide mutations: :C9532T,T22917G

Spotted and monitored by several including Ryan, Fede, @peacockflu, dr_Karyakarte and others owing to the importance of this delta signature mutation in this background

Usher tree:  
![image](https://user-images.githubusercontent.com/98380390/184141750-d3bab20a-9341-415f-a930-f8fdfae75ab9.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31b12_4fb7e0.json?branchLabel=aa%20mutations&c=gt-S_452&label=nuc%20mutations:C9532T,T22917G

CovSpectrum query: working on a better query
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AS1221L%2CORF1a%3AN4060S%2CS%3AL452R&

Samples: 
EPI_ISL_13969956
EPI_ISL_13969969
EPI_ISL_13970110
EPI_ISL_14161921
EPI_ISL_14161941
EPI_ISL_14161994
EPI_ISL_14162024
EPI_ISL_14162209
EPI_ISL_14162229
EPI_ISL_14326915
EPI_ISL_14326921
EPI_ISL_14326958
EPI_ISL_14326960
EPI_ISL_14327006
EPI_ISL_14327123
EPI_ISL_14356181
EPI_ISL_14356188
EPI_ISL_14356191
EPI_ISL_14356193
EPI_ISL_14356196
EPI_ISL_14228605
EPI_ISL_14356488
EPI_ISL_14356489
EPI_ISL_14320191
EPI_ISL_14217668
EPI_ISL_14366591
EPI_ISL_14366592
EPI_ISL_14355613

16 properly designated as BA.2.75

Growth advantage: Too early..

**Comment by FedeGueli** [comment]
Ideally ( from your tree) https://cov-spectrum.org/explore/India/AllSamples/Past3M/variants?variantQuery=+G19962T+%26+S%3AL452R+%26+9532T&variantQuery1=NextCladePangoLineage%3ABA.2.75*+%26+S%3A452R& but it doesnt catch any as today.

**Comment by RajLABN** [comment]
It does capture the sequences from Japan and Austria. Could be the date errors in Karnataka samples? Most have only month/year

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=+G19962T+%26+S%3AL452R+%26+9532T&variantQuery1=NextCladePangoLineage%3ABA.2.75*+%26+S%3A452R&

**Comment by FedeGueli** [comment]
Yeah but your one takes one BA.5.2.1 in that is unrelated. it think on covspectrum it isnt possible to catch more than two.

this the more stable to me https://cov-spectrum.org/explore/India/AllSamples/Past3M/variants?variantQuery=NextcladePangolineage%3ABA.2.75*+%26+S%3AL452R++&variantQuery1=NextCladePangoLineage%3ABA.2.75*+%26+S%3A452R&

**Comment by RajLABN** [comment]
Yup, got to work on a better cov-spectrum query (to add some and leave some)

**Comment by RajLABN** [comment]
GISAID Query: e_t11a, spike_l452r, nsp3_s403l, nsp8_n118s

7 sequences from Karnataka, India with collection dates in 07/22 and 08/22 [date incomplete]

IDs: EPI_ISL_14478877, EPI_ISL_14478932-14478933, EPI_ISL_14478940,
EPI_ISL_14478950, EPI_ISL_14478961, EPI_ISL_14479023,

**Comment by RajLABN** [comment]
Early days, significant growth advantage over BA.2.75 in India (once n > 100 seqs, GA will settle down) 

https://cov-spectrum.org/explore/India/AllSamples/Past3M/variants?aaMutations=ORF1a%3AS1221L%2CORF1a%3AN4060S%2Ce%3At11a&aaMutations1=ORF1a%3AS1221L%2CORF1a%3AN4060S%2CS%3AL452R%2Ce%3At11a&analysisMode=CompareToBaseline&

**Comment by RajLABN** [comment]
2 more BA.2.75 + Spike L452R sequences from Austria. 
EPI_ISL_14492159, EPI_ISL_14492172

**Comment by RajLABN** [comment]
2 more BA.2.75 with Spike L452R - one from Maharashtra, India and one from Kansas, USA [EPI_ISL_14550900, EPI_ISL_14551958]

**Comment by corneliusroemer** [comment]
It's now also been found in Switzerland-Geneva in addition to 4x Austria. This looks like worth designating if the phylogeny is clear - and it seems to be.

Mutations on top of BA.2.75 polytomy:
- C9532T
- 19962T
- 22917G

It looks like 19962T occurred first, as it has slightly more sequences on covSpectrum.

This is ready for designation if people agree @thomasppeacock - I can make a PR
