### ISSUE TITLE
BA.5 + C1627T sublineage (On usher identified as BA.5.2 No28330G) sublineage with orf1a:R207C, orf1a:Q3922R, E:S50G and S:262S (175seqs, 5% prevalence in Philippines , spread to 6 continents NA/SA)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#936]
S:A262S is a mutation that seems to be growing in the last weeks, here i want to propose a sublineage of BA.5 in the branch with C1627T that leads to BA.5.2* pre A28330G.

Defining mutations:
C1627T + Orf1a:R207C+ Orf1a:Q3922R+ G29422T + E:S50G + S:A262S

As can be seen by this usher tree (big blue point are from Eswatini) all this tree is disseminated with sequences coming from Eswatini suggesting that this entire branch could have evolved in South Africa or Eswatini
![Schermata 2022-08-11 alle 21 01 51](https://user-images.githubusercontent.com/87669813/184218886-825e3471-dd73-461d-9ed5-5b564d0e9d4e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1c532_51aee0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:G22346T

First sequence: Eswatini/ILRI_M03297/2022|EPI_ISL_13149302|2022-05-03
102 Sequences on CovSpectrum: 
[contributors.csv](https://github.com/cov-lineages/pango-designation/files/9311418/contributors.csv)
(120 already on Usher plus 2 from Denmark and 3 from 3 different american states uploaded today to Gisaid,
while yesterday was one from Austria,one from Singapore, and two from California)
Last sequence: hCoV-19/Denmark/DCGC-561360/2022 | EPI_ISL_14393203

18 Countries:
![Schermata 2022-08-11 alle 21 05 43](https://user-images.githubusercontent.com/87669813/184219523-d5aa5864-3306-4523-8ddd-b31c59afa01a.png)

Interestingly it seems to have a significant prevalence in Philippines around 4-5% in the past two months:
![Schermata 2022-08-11 alle 21 07 06](https://user-images.githubusercontent.com/87669813/184219783-87bdfed1-093f-4ad0-a938-6a929afcae03.png)
And this seems reasonable after looking at its growth advantage in Philippines vs BA.5 baseline
![Schermata 2022-08-11 alle 21 08 18](https://user-images.githubusercontent.com/87669813/184219945-f648c988-dcbe-4c23-a0e8-c269a2910bf1.png)

At global level its early apparent advantage is still there also vs dominant BA.5.2 lineage:
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5.2*&variantQuery1=NextcladePangolineage%3ABA.5+%26+C1627T+%26+orf1a%3AR207C%26orf1a%3AQ3922R%26G29422T%26E%3AS50G+%26S%3A262S&analysisMode=CompareToBaseline&

Covspectrum query : https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=+C1627T+%26+orf1a%3AR207C%26orf1a%3AQ3922R+%26+E%3AS50G+%26+ORF3a%3A29V&variantQuery1=NextCladePangoLineage%3ABA.5.2*& (**Edited)**

Gisaid Query: NSP2_R27C,NSP7_Q63R,Spike_A262S

**Comment by FedeGueli** [comment]
Using Gisaid  query NSP2_R27C, E_S50G ,Spike_A262S i found 129 viruses but interestingly 14 of them are from last week indicating a good growth rate for this lineage

**Comment by FedeGueli** [comment]
@corneliusroemer @chrisruis @InfrPopGen @thomaspeacock i count 13seqs on Gisaid with collection day after 1st of August and from 5 countries: Usa(4seqs 2states), denmark (4seqs, 3 regions) , Australia (2seqs,2regions),
Israel,Uk and Austria (1 seqs).
56 seqs out of 129 has been collected after 16th of July.
Said that
I propose a fast designation of this lineage due a likely high prevalence in Philippines and rapid spread from there.

**Comment by FedeGueli** [comment]
5 more uploads: 2 Usa (2 different states), 1 Denmark, 1 Canada, 1 Czechia

**Comment by FedeGueli** [comment]
At least 165 Seqs as todayshpuld belong to this siblineage, 17 out of 165 samples have been collected after 1st of August.

**Comment by FedeGueli** [comment]
Big upload yesterday from Eswatini, mainly may sequences, confirms early circulation of this sublineage there and big upload also from Philippines , mainly july samoples. plus sequences from Us and Uk.

@InfrPopGen @corneliusroemer @chrisruis i think this deserves a designation.

**Comment by FedeGueli** [comment]
175 seqs as today on Usher but yesterday there was a big upload from Eswatini (Sequences from May) and Philippines (sequences mainly from July) plus some Uk and Us samples

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28cfe_df3010.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C884T

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.10 with 47 newly designated sequences, and 3 updated designations from BA.5. Defining mutation G22346T (S:A262S).

**Comment by FedeGueli** [comment]
Thx a lot @InfrPopGen

**Comment by FedeGueli** [comment]
@InfrPopGen very timely designation there was an upload today of new 15 sequences sampled in South Korea and Japan related to travel to Philippines.
