### ISSUE TITLE
Proposal for BA.5.5 Sublineage with ORF1b:G662V (527 seq, Aug 20) & Sublineage with additional S:Q677H + ORF1a:M1014K (86 seq, Aug 20), mainly in USA & Canada

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#938]
### **Description**
**Sub-lineage of:** BA.5.5
**Earliest sequence:** 2022-5-22, USA, Alabama — EPI_ISL_13072187
**Most recent sequence:** 2022-8-3, USA, Mississippi — EPI_ISL_14425597
**Countries circulating:** USA (316), Canada (41), Ireland (25), UK (24), Netherlands (8), Belgium (6), Israel (5), Sweden (4), Japan (3—two with travel history in Nepal & one in USA), Germany (3), France (2), Iran (1), Greece (1), Norway (1), Switzerland (1), Peru (1), Australia (1), Puerto Rico (1)
**Number of Sequences:** 475 on Usher tree; 444 returned by GISAID query “M_D3N, Spike_T76I, NSP12_G671V” 
**Substitutions on top of BA.5.5:**
ORF1b: G662V (NSP12_G671V)
Nucleotide: G15452T, C24766T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_2960b_502e20%E2%80%94BA.5.5_%2B_Q677H_%2B_ORF1b-G662V.json 
![Screen Shot 2022-08-11 at 5 57 31 PM - BA 5 5 + ORF1b-G662V Usher Tree](https://user-images.githubusercontent.com/33738461/184252322-7b7bc316-a237-49c8-ada0-3e928d8b050a.png)

**Evidence**
ORF1b:G662 mutations have been found in a number of prominent variants, most notably ORF1b:G662S in BA.2.75 and Delta. Its role, to my knowledge, is unknown, but it clearly is a residue of importance. 
CovSpectrum: 27% (CI:21%-34%) weekly growth advantage compared to nextcladePangoLineage:BA.5.5 in the last three months in North America:
https://cov-spectrum.org/explore/North%20America/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5.5&variantQuery1=NextCladePangoLineage%3ABA.5.5+%26+ORF1b%3AG662V&analysisMode=CompareToBaseline&
![Screen Shot 2022-08-11 at 5 52 37 PM - BA 5 5 vs BA 5 5 + ORF1b-G662V in North America](https://user-images.githubusercontent.com/33738461/184252295-8a88e2ed-8216-41a6-818b-5ea88dfc7847.png)

**Genomes**
[GISAID_hcov-19_ids_2022_08_11_21_51 - BA.5.5 + ORF1b-G662V.csv](https://github.com/cov-lineages/pango-designation/files/9312447/GISAID_hcov-19_ids_2022_08_11_21_51.-.BA.5.5.%2B.ORF1b-G662V.csv)

### **Description**
**Sub-lineage of:** BA.5.5 + ORF1b:G662V
**Earliest sequence:** 2022-6-8, USA, Nevada — EPI_ISL_13510230, EPI_ISL_13469230
**Most recent sequence:** 2022-7-31, England — EPI_ISL_14321417
**Countries circulating:** USA (45), Canada (29), UK (3), Iran (1)
**Number of Sequences:** 85 on Usher tree; 78 returned by GISAID query “Spike_Q677H, M_D3N, Spike_T76I, NSP12_G671V”
**Substitutions on top of BA.5.5 + ORF1b:G662V:**
Spike: Q677H
ORF1a: M1014K 
Nucleotide: T3306A, G23593T, C24766T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_2960b_502e20%E2%80%94BA.5.5_%2B_Q677H_%2B_ORF1b-G662V.json
![Screen Shot 2022-08-11 at 6 01 57 PM - BA 5 5 + ORF1b-G662V + S-Q677H + ORF1a-M1014K Usher Tree](https://user-images.githubusercontent.com/33738461/184252353-f43a39a6-f3c4-42de-990d-3563d1a6ef7e.png)

**Evidence**
S:Q677H is part of the polybasic cleavage site & likely has some significance, though I’m not aware of any data showing what its impact might be.
CovSpectrum: 40% (CI:23%-57%) weekly growth advantage compared to nextcladePangoLineage:BA.5.5 in the last three months in North America:
![Screen Shot 2022-08-11 at 6 10 39 PM - BA 5 5 vs BA 5 5 + ORF1b-G662V + S-Q677H + ORF1a-M1014K in North America](https://user-images.githubusercontent.com/33738461/184252553-fb9ba245-abc5-4dd0-9e4c-c9dc76ffd2a2.png)

**Genomes**
EPI_ISL_13418263, EPI_ISL_13469230, EPI_ISL_13510230, EPI_ISL_13623729, EPI_ISL_13623762, EPI_ISL_13624458, EPI_ISL_13624727, EPI_ISL_13639726, EPI_ISL_13640711, EPI_ISL_13665789, EPI_ISL_13708958, EPI_ISL_13723433, EPI_ISL_13768720, EPI_ISL_13806696, EPI_ISL_13807532, EPI_ISL_13812270, EPI_ISL_13812302, EPI_ISL_13813331, EPI_ISL_13824521, EPI_ISL_13829362, EPI_ISL_13900149, EPI_ISL_13901801, EPI_ISL_13931277, EPI_ISL_13932133, EPI_ISL_13949498, EPI_ISL_13976259, EPI_ISL_13979134, EPI_ISL_13979246, EPI_ISL_14003451, EPI_ISL_14036643, EPI_ISL_14036643, EPI_ISL_14036700, EPI_ISL_14036862, EPI_ISL_14036862, EPI_ISL_14037284, EPI_ISL_14037346, EPI_ISL_14053898, EPI_ISL_14058163, EPI_ISL_14078427, EPI_ISL_14082694, EPI_ISL_14104578, EPI_ISL_14176764, EPI_ISL_14177992, EPI_ISL_14187916, EPI_ISL_14196635, EPI_ISL_14209186, EPI_ISL_14209188, EPI_ISL_14209189, EPI_ISL_14209190,  EPI_ISL_14209202, EPI_ISL_14209204, EPI_ISL_14209204, EPI_ISL_14209209, EPI_ISL_14209216, EPI_ISL_14209581, EPI_ISL_14209655, EPI_ISL_14209656, EPI_ISL_14209993, EPI_ISL_14209993, EPI_ISL_14209998, EPI_ISL_14210195, EPI_ISL_14210210, EPI_ISL_14223428, EPI_ISL_14223428, EPI_ISL_14224092, EPI_ISL_14224120, EPI_ISL_14253459, EPI_ISL_14269177, EPI_ISL_14275438, EPI_ISL_14275442, EPI_ISL_14286490, EPI_ISL_14288009, EPI_ISL_14288029, EPI_ISL_14321417, EPI_ISL_14377076, EPI_ISL_14383915, EPI_ISL_14384127,

**Comment by Sinickle** [comment]
Since C24766T happens on the branch before ORF1b:G662V, this can be used to distinguish the proposed lineage from other BA.5.5 that might acquire ORF1b:G662V.

**Comment by ryhisner** [comment]
Great point, Nick. I probably should've included that nucleotide mutation in the proposal. I never know whether to include a mutation that is possessed by the proposed sublineage but also by some other sequences without the defining AA mutation. In this case, there are only 13 sequences with C24766T but not ORF1b:G662V, so I think I should have included it. I'll put it in now.

**Comment by ryhisner** [comment]
The first proposal here—BA.5.5 + ORF1b:G662V‚ now has a smaller 19% (CI: 14-24%) weekly growth advantage (WGA) vs BA.5.5 in the United States (where the vast majority of sequences are). https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5.5&variantQuery1=Nextcladepangolineage%3ABA.5.5+%26+ORF1b%3AG662V&analysisMode=CompareToBaseline&

It's almost even against BA.5* in the USA (2% WGA, CI: -2-6%)
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5*&variantQuery1=Nextcladepangolineage%3ABA.5.5+%26+ORF1b%3AG662V&analysisMode=CompareToBaseline&

...and likely has a slight disadvantage against BA.5.2* (-3%, CI: -8-1%), though the CI for the latter just crosses zero. https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5.2*&variantQuery1=Nextcladepangolineage%3ABA.5.5+%26+ORF1b%3AG662V&analysisMode=CompareToBaseline&

There have only been eight sequences of BA.5.5 + ORF1b:G662S + S:Q677H submitted since August 10, and it now seems clear it offers no growth advantage over BA.5.5 + ORF1b:G662S, so consider that part of this proposal withdrawn.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.5.2 with 446 newly designated sequences, and 64 updated designations from BA.5.5. Defining mutation G15452T (Orf1ab:G5063V).

**Comment by shay671** [comment]
Just to add that there is another Nucsub above BA.5.5 in the branch this variant evolved from - C4540T
