### ISSUE TITLE
Proposal for a Sublineage of BA.2.76 with S:N185H & ORF1a:A3730T, exclusively in Japan (46 seq on Aug 18)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#939]
### **Description**
**Sub-lineage of:** BA.2.76
**Earliest sequence:** 2022-6-23, Japan, Saitama — EPI_ISL_14129237
**Most recent sequence:** 2022-7-23, Japan, Fukushima — EPI_ISL_14349049
**Countries circulating:** Japan (All)
**Number of Sequences:** 40 on Usher tree; 39 returned by GISAID query “Spike_N185H, NSP6_A161T, Spike_R346T, Spike_Y248N”
**Substitutions on top of BA.2.76:**
Spike: N185H
ORF1a: A3730T (NSP6_A161T)
Nucleotide: G11453A, A22115C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_1bd03_585860%E2%80%94BA.2.76%2BN185H%2BORF1a%3BA2730T.json
![Screen Shot 2022-08-11 at 7 16 21 PM - BA 2 76+N185H+ORF1a;A2730T_Usher_Tree](https://user-images.githubusercontent.com/33738461/184258915-24c023f7-13bc-4cea-92b6-13678a520022.png)

**Evidence**
There have been 107 sequences in Japan with S:R346T and S:Y248N, but 50 of those have been from incoming travelers detected by airport surveillance. Of the 57 non-travel-related sequences, this sublineage makes up more than two-thirds of the total (68.4%). Since June 1, there have been exactly zero sequences anywhere in the world with S:N185H. In fact, other than these 39 sequences from Japan, there have been fewer than 10 legitimate sequences in all of 2022 with N185H.

N185H involves an AC nucleotide change, which is one of the least common SNPs. According to a table made by @zach-hensel, AC makes up just 1.5% of SNPs, which at least partially explains why this mutation has been so rare. 
![Screen Shot 2022-08-11 at 7 01 30 PM - N185H, NextClade Nucleotide pic](https://user-images.githubusercontent.com/33738461/184258890-161a3ca2-6ca7-4fe8-b723-20ba51807d36.png)

**Genomes**
EPI_ISL_13765934, EPI_ISL_14082096, EPI_ISL_14082293, EPI_ISL_14094405, EPI_ISL_14095679, EPI_ISL_14129237, EPI_ISL_14130495, EPI_ISL_14130529, EPI_ISL_14130946, EPI_ISL_14131094, EPI_ISL_14131171, EPI_ISL_14131319, EPI_ISL_14137156, EPI_ISL_14137291, EPI_ISL_14137442, EPI_ISL_14137596, EPI_ISL_14138088, EPI_ISL_14139721, EPI_ISL_14140714, EPI_ISL_14140753, EPI_ISL_14141168, EPI_ISL_14141197, EPI_ISL_14141209, EPI_ISL_14141224, EPI_ISL_14141230, EPI_ISL_14141243, EPI_ISL_14338678, EPI_ISL_14341384, EPI_ISL_14342566, EPI_ISL_14342697, EPI_ISL_14342709, EPI_ISL_14342711, EPI_ISL_14347270, EPI_ISL_14347490, EPI_ISL_14347499, EPI_ISL_14347526, EPI_ISL_14348275, EPI_ISL_14349049, EPI_ISL_14351290

**Comment by aq-sun** [comment]
Thank you @ryhisner, this shows an epidemiological event so we have designated this as BA.2.76.2, with 26 newly designated sequences. Defining mutations: G11453A (ORF1a: A3730T), A22115C (S:N185H).

**Comment by shay671** [comment]
Other mutations in the mediator branches from BA.2.76 to BA.2.76.2 (if I'm correct with BA.2.76 definition) : 
C7528T
G19684T
C28603T
