### ISSUE TITLE
Potential new B.1.400 lineage with E484K in USA/UT

### ISSUE THREAD

**Issue by erinyoung** [cov-lineages/pango-designation#94]
by Erin Young, Tara Gallagher, and Kelly Oakeson

Description
Sub-lineage of: B.1.400
Earliest sequence: UT-UPHL-2104964349, EPI_ISL_1910744, November 13, 2020
Most recent sequence: UT-CDC-LC0020166, EPI_ISL_1221568, February 22, 2021
Countries circulating: USA, primarily in the state of Utah

Genomes
I have attached a .txt file with the GISAID IDs and collection dates for the Utah sequences that we've been looking at:
[B_1_400_EEK_IDs.txt](https://github.com/cov-lineages/pango-designation/files/6549606/B_1_400_EEK_IDs.txt)

Evidence
As we've been sequencing our backlog of samples, we're noticing a trend of B.1.400 + the EEK mutation, S:E484K, that began to spread in our community.

According to [outbreak.info](https://outbreak.info/situation-reports?pango=B.1.400&muts=s%3Ae484k), there have been 27 of B.1.400 + EEK identified in the United States, with 18 of those being from Utah. Although we don't have a paper or preprint together, this appears to have significant spread in our community.

I've attached a screenshot of our local NextStrain build of B.1.400 with highlighting on the lineage that we think should have a unique designation.

![B1400_EEK](https://user-images.githubusercontent.com/28793649/119727510-9a83c780-be2f-11eb-96db-55d5ee081c5b.png)

Proposed lineage name
Sub-lineage of B.1.400

**Comment by AngieHinrichs** [comment]
I see some AZ, CO and NV neighbors... and oddly, a few of the samples (USA/UT-UPHL-2103453377/2021|EPI_ISL_1205324|2021-01-19) seem to have lost E484K and gained N501Y?!

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-94.json?branchLabel=Spike%20mutations&c=pango_lineage&label=nuc%20mutations:C1426T,C2106T

**Comment by AngieHinrichs** [comment]
* USA/UT-UPHL-2103453377/2021|EPI_ISL_1205324|2021-01-19 has Ns at the positions corresponding to reference 23012 and 23063, but USA/UT-CDC-LC0020166/2021|MW734538.1|21-02-22 definitely has A23063T (N501Y) and no change at G23012 (no E484K).  The sequences share T3270C (and the preceding mutations) so UShER infers that UT-UPHL-2103453377's Ns are just like UT-UPHL-2103453377.

**Comment by erinyoung** [comment]
For future note, I need to ensure that the example samples that I suggest have better coverage.

I also need to vet their variants better. I just assumed that since their branch label was E484K, that they all had that variant.

What do you normally do in this situation? Does this mean there are two lineages here?

**Comment by AngieHinrichs** [comment]
The Pango Network has just (like [yesterday](https://www.oxfordmartin.ox.ac.uk/news/sars-cov-2-naming-system-pango-network/)) released more formalized rules for what may qualify as a new lineage: https://pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/

They are explicitly pushing back on assigning a new lineage each time a new mutation of concern is observed -- see the last 3 items on this page:
https://pango.network/faqs/

They kinda suggest that it might be called B.1.400+E484K (while also saying that that is not official Pango lineage nomenclature).

They actually let me join (thank you @aineniamh and I hope you don't regret it ;) and I'm advocating for the UCSC give-the-customer-what-they-ask-for approach.  Do you have a preference in this case?

**Comment by chrisruis** [comment]
Hi @erinyoung thanks for submitting this. We've added this as B.1.400.1 in [v1.2.21](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.21) with the lineage starting on the E484K branch.

It looks like the clade that has got K484E and N501Y is within the B.1.400.1 diversity and only has the 2 sequences Angie mentioned above in the UShER tree currently. So for now, I'd recommend keeping these as B.1.400.1 as with the rest of the clade and then if this K484E/N501Y clade grows in the future, we can look at adding it in as a descendent of B.1.400.1.

Thanks again
