### ISSUE TITLE
BA.4.1 sublineage with S:R346T, ORF7b:11-13del, 356 sequences in SA, Mexico, US, others

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#940]
**Description**
Sub-lineage of: BA.4.1
Earliest sequence: 2022-4-19 South Africa---EPI_ISL_12765592 
Most recent sequence: 2022-7-30, USA, Canada, UK --- EPI_ISL_14306775,EPI_ISL_14315290,EPI_ISL_14289269
Countries circulating: South Africa, Mexico, 13 others
Number of Sequences: 356 on USHER. 
Substitutions on top of BA.4.1:
Spike: R346T
ORF7b: 11-13del 
Nucleotide: C14322T, T18603C, G22599C, C28720C, 27786-27793del

**USHER Tree**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_390b7_59d650.json?branchLabel=aa%20mutations&c=gt-S_346&tl=country
![image](https://user-images.githubusercontent.com/94097102/184267969-067f6b1f-7992-4411-9899-e92b1a8b0600.png)

**Evidence**
The main reason I'm proposing this is that it is one of the largest BA.4/BA.5 sublineages with an S:346 mutation. The ORF7b deletion is interesting in its own right though. 
As noted in #865, S:346 mutations (possibly especially S:346T) appear to grant a significant advantage to BA.4/BA.5. 

The advantage has held true for this lineage. Relative to BA.4.1... 
Mexico:
![image](https://user-images.githubusercontent.com/94097102/184268726-842cd103-2213-482c-a9e8-b93dfdc60ecc.png)

South Africa:
![image](https://user-images.githubusercontent.com/94097102/184268881-556ab3d6-d25e-45ee-9174-6b7b48f378e6.png)

USA:
![image](https://user-images.githubusercontent.com/94097102/184268965-0f27492d-cab8-431e-9604-13b8aad51896.png)

**Querries**
[Growth Advantage](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=ba.4.1+&variantQuery1=ba.4.1+%26+orf7b%3A11-+%26+orf7b%3A13-+%26+s%3A346t&analysisMode=CompareEquals&)
[Tracking](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A346t&nucMutations=22599c%2C14322t&pangoLineage=ba.4.1&pangoLineage1=ba.4.1&)

**Genomes:**
[Issue940Genomes.txt](https://github.com/cov-lineages/pango-designation/files/9313140/Issue940Genomes.txt)

**Comment by FedeGueli** [comment]
Nick isnt this already designated as BA.4.1.8? the one with a orf7a frameshift spotted very early by @silcn?
