### ISSUE TITLE
Sublineage of BA.5.2.1 with S:K444R, 99 sequences, USA

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#942]
**Description**
Sub-lineage of: BA.5.2.1
Earliest sequence: 2022-5-29 USA, Georgia---EPI_ISL_13312344
Most recent sequence: 2022-8-1, Georgia --- EPI_ISL_14333777
Countries circulating: USA only. 
Number of Sequences: 71 on USHER.
Substitutions on top of BA.5.2.1:
Spike: K444R
Nucleotide: T6979G,T11177C,A3859G,A22893G

**USHER Tree**
[Link here](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f5a2_5be020.json?label=nuc%20mutations:A22893G)
(Yellow = proposed lineage)
![image](https://user-images.githubusercontent.com/94097102/184275803-79815f8a-09ab-49d5-b89c-adf0b819cee6.png)

**Evidence**
The main reason I'm proposing this is that it is one of the largest BA.4/BA.5 sublineages with an S:444 mutation.
As we have seen in recent issues, #931 #924 #903, S:444 mutations are granting growth advantage to BA.4/BA.5. To me, this looks a lot like how a variety of S:346 mutations have popped up on various BA.4/BA.5 lineages and granted them an advantage. Silcn notes one of the larger BA.4/BA.5 sublineages with both an S:346 and an S:444 mutation #926. 
See #903 for an explanation on the importance of S:444 mutations. 

The advantage has held true for this lineage. Relative to BA.5.2.1...
USA
![image](https://user-images.githubusercontent.com/94097102/184276427-695048e6-8fd7-43c1-9f6c-1c7e4d3aa568.png)

**Queries**
[Growth](https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?variantQuery=ba.5.2.1&variantQuery1=ba.5.2.1*+%26+11177c+%26+s%3A444r&analysisMode=CompareToBaseline&)
[Tracking](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=ba.5.2.1*+%26+11177c+%26+s%3A444r&variantQuery1=ba.5.2.1*+%26+11177c+%26+s%3A444r&)

**Genomes**
[Issue942Genomes.txt](https://github.com/cov-lineages/pango-designation/files/9313388/Issue942Genomes.txt)

**Comment by Sinickle** [comment]
Using this chart created by @zach-hensel which represents his calculation of a single snyonymous mutation to be of each type in SARS-COV-2, and this [tool](https://ukcovid.xyz/codon/) created by @Olias120676 which identified all 1-nucleotide-away-AAs, we can try to estimate how likely an AA mutation is to occur, relative to others in that position. 
![image](https://user-images.githubusercontent.com/94097102/184277382-43d92b57-0f1f-4b63-9ab7-0eefefc45e52.png)

For S:444, the following are 1 nucleotide mutation away but don't seem to be spreading much at all: [Q,E] 

The others are all spreading:
N: [AAG->AAC 1.5%] or [AAG -> AAT 18.2%] = 19.7%
R: [AAG->AGG 8.8%] = 8.8%
T: [AAG->ACG 1.5%] = 1.5%
M: [AAG->ATG 2.0%]= 2.0%

So, of the spreading S:444 mutations, their relative likelihood to be acquired should be approximately... 
S:K444T= 1.0x
S:K444M= 1.3x
S:K444R= 5.9x
S:K444N= 13.1x

**Comment by FedeGueli** [comment]
80 seqs as today on covspectrum

**Comment by corneliusroemer** [comment]
Can you explain why you're narrowing to T11177C? Do you suggest S:444R has arisen multiple times independently on top of BA.5.2.1? You catch only half of all BA.5.2.1 with that mutation by using the query you suggest.

**Comment by FedeGueli** [comment]
@corneliusroemer  @asinickle 99 sequences now on Usher: 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2383_336e80.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C241T,T670G,C1627T,C2790T,C3037T,A3859G,G4184A,C4321T,T6979G,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,A27038G,C27807T,C27889T,A28271T,C28311T,A28330G,G28881A,G28882A,G28883C,A29510C

And is the Usher tree to suggest to restrict the query for this monophyletic  to T11177C  cc @AngieHinrichs 
![Schermata 2022-08-22 alle 15 58 17](https://user-images.githubusercontent.com/87669813/185939050-6c299e67-22e6-46ea-9cd8-6b74afe040db.png)

**Comment by Sinickle** [comment]
@corneliusroemer Yes, that is what I'm suggesting. 
If you run through the other BA.5.2.1+S:444R trees, the vast majority of them are not on basal BA.5.2.1, but have additional mutations, but also don't cluster with the one I'm proposing. 

In general, I also don't think you will end up with a monophyletic tree if the designated sublineage is a very large branch+a single frequently acquired mutation. 

These S:444 mutations are looking a lot like the S:346 mutations to me in that they're coming up on so many different branches, and granting a growth advantage.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BF.16 with 54 newly designated sequences, and 5 updated designations from BA.5.2.1. Defining mutation(s) A22893G (S:K444R).
