### ISSUE TITLE
Proposal for a Sublineage of BA.2.75.1 with S:R346T [~50 seq on Aug 20, 6x non-India]

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#944]
### **Description**
**Sub-lineage of:** BA.2.75.1
**Earliest sequence:** 2022-7-3, India, Delhi — EPI_ISL_14290481
**Most recent sequence:** 2022-7-27, India, Karnataka — EPI_ISL_14366589
**Countries circulating:** India (31), Australia (1), Japan (1—airport surveillance with travel history in India)
**Number of Sequences:** 33 returned by GISAID query “E_T11A, Spike_D574V, Spike_R346T, NSP8_N118S”; 18 on largest Usher tree 
**Substitutions on top of BA.2.75.1:**
Spike: R346T
Nucleotide: G22599C

**USHER Tree(s)**
Due to many Indian sequences having low coverage, false reversions cause Usher to often scatter into different branches sequences that are in fact monophyletic. This is almost certainly the case with all or nearly all of these sequences. Below I’ve included links to the largest Usher branch, which has 19 sequences, and the second largest, which has 12 sequences. 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_152b6_6ec5f0%20-%20BA.2.75.1%20%2B%20R346T%2C%20Tree%201.1.json 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice2_genome_152b6_6ec5f0%20-%20BA.2.75.1%20%2B%20R346T%2C%20Tree%202.json

![Screen Shot 2022-08-12 at 8 41 58 PM - BA 2 75 1 + R346T, Largest Usher Tree](https://user-images.githubusercontent.com/33738461/184461608-118b3e28-0adf-4afa-95ba-b21b6195e2e0.png)

**Evidence**
S:R346T is one of the most effective antibody-escape mutations and is found not only in many of the fastest-growing BA.2 lineages but also in the fastest-growing BA.4 and BA.5 lineages, most notably BA.4.6. It would be extremely surprising if R346T did not also increase the already impressive growth rate of BA.2.75.1. All 33 sequences returned by the GISAID query "E_T11A, Spike_D574V, Spike_R346T, NSP8_N118S" were uploaded August 1 or later (with 28 uploaded in just the past five days), and the earliest sequence is from July 3. Though the sample size is small, this sublineage already appears to be growing rapidly.

Unlike nearly all other escape mutations, on a BA.2 RBD background, R346T actually increases ACE2 affinity and RBD expression (a proxy measure for stability) according to the Bloom Lab RBD Heat Map, which likely goes a long way toward explaining its remarkable success in BA.2, BA.4, and BA.5 lineages. https://jbloomlab.github.io/SARS-CoV-2-RBD_DMS_Omicron/RBD-heatmaps/

![Screen Shot 2022-08-12 at 8 39 54 PM - R346T Bloom Lab Heat Map, BA 2 Background](https://user-images.githubusercontent.com/33738461/184461553-e044eb0a-b274-47b3-a7e1-36271fac2f6f.png)

**Genomes**
EPI_ISL_14162099, EPI_ISL_14228531, EPI_ISL_14285583, EPI_ISL_14290481, EPI_ISL_14290552, EPI_ISL_14302992, EPI_ISL_14303021, EPI_ISL_14303155, EPI_ISL_14303634, EPI_ISL_14303639, EPI_ISL_14303661, EPI_ISL_14303724, EPI_ISL_14303728, EPI_ISL_14303780, EPI_ISL_14304071, EPI_ISL_14320261, EPI_ISL_14327020, EPI_ISL_14327023, EPI_ISL_14327223, EPI_ISL_14327225, EPI_ISL_14355856, EPI_ISL_14355877, EPI_ISL_14355878, EPI_ISL_14355879, EPI_ISL_14355897, EPI_ISL_14355903, EPI_ISL_14355918, EPI_ISL_14355923, EPI_ISL_14355935, EPI_ISL_14355943, EPI_ISL_14355949, EPI_ISL_14356494, EPI_ISL_14366589

**Comment by silcn** [comment]
> **USHER Tree(s)** Due to many Indian sequences having low coverage, false reversions cause Usher to often scatter into different branches sequences that are in fact monophyletic. This is almost certainly the case with all or nearly all of these sequences. Below I’ve included links to the largest Usher branch, which has 19 sequences, and the second largest, which has 12 sequences. https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_152b6_6ec5f0%20-%20BA.2.75.1%20%2B%20R346T%2C%20Tree%201.1.json https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice2_genome_152b6_6ec5f0%20-%20BA.2.75.1%20%2B%20R346T%2C%20Tree%202.json

The 19-sequence lineage is legit. I mentioned it in #918 when it was at just 2 sequences, lots more were uploaded earlier this week.

I have doubts about the 12-sequence lineage, because these sequences have S:339D instead of 339H, which suggests possible contamination with a lineage such as BA.2.74 or BA.2.76. Some of the sequences even have S:Y248N which is highly suggestive of contamination with BA.2.76 (or recombination, but I'd like to see more evidence for this outside poor-quality Indian sequences). There are also some further reversions in the tree. 

Even if a few of the sequences from the 12-sequence "lineage" do form a legitimate BA.2.75.1+S:346T sublineage, it's distinct from the 19-sequence lineage, as one has C11224T, which defines a large branch within BA.2.75.1, and the other doesn't.

**Comment by ryhisner** [comment]
Excellent point about C11224T. I had assumed the G339D was an artifact due to lack of coverage in that part of spike, but that nucleotide mutation is more convincing. On the other hand, wouldn't this imply that BA.2.75.1 is not entirely monophyletic since those sequences appear on an entirely different branch of BA.2.75+D574V? Is it possible those BA.2.75.1+R346T sequences belong in a C11224T sub-branch of the 18-sequence tree? The 96-sequence D574V branch is only separated from the larger BA.2.75.1 branch on the Usher tree because of "reversions" at spike residues 371, 373, 375, and 376 (and the absence of K147E). Seems most likely to me that it belongs in the larger BA.2.75.1 tree, and wouldn't this imply the C11224T sequences also belong there? https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d10d_7bd710.json?branchLabel=aa%20mutations&c=gt-S_346&label=nuc%20mutations:T22686C
![image](https://user-images.githubusercontent.com/33738461/184500411-2c423f92-5235-4d1d-992b-e6395e7e3af1.png)

**Comment by silcn** [comment]
@ryhisner that apparent 5-sequence branch isn't on the D574V branch, it's just BA.2.75. At least a couple of them are actually in #918 once the sequences are cleaned up.

**Comment by ryhisner** [comment]
Ah, you're right. I wasn't looking closely enough. Thanks for pointing this out.

**Comment by corneliusroemer** [comment]
There are now at least 34 BA.2.75.1 with S:346T, but only 2 of these outside India (1x Australia, 1x Japan).

The Australian cluster is very likely real - it contains 6068C which is very rare and occurs almost exclusively in this BA.2.75.1 + S:346T lineage (1x Australia, 5x India [3x KA, 2x TG]).

As soon as this shows up in other non-Indian countries we should designate this. Hard to say whether it's monophyletic right now but definitely worth watching.

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nucMutations=6086C&

**Comment by RajLABN** [comment]
One more BA.2.75 from Singapore [EPI_ISL_14458973] with Spike 346T/486S/490S combo

**Comment by silcn** [comment]
@RajLABN once again, not BA.2.75.1

**Comment by ryhisner** [comment]
One BA.2.75.1 + R346T uploaded this morning with travel history from India, which made me examine the 15-sequence branch of BA.2.75+D574V+R346T that appear together but are separate from the main, larger branch (almost none of which are categorized by Pangolearn as BA.2.75). 
![image](https://user-images.githubusercontent.com/33738461/185649456-b73dc1eb-ff85-4925-a2fc-9ae3d0cde26c.png)


Usher separates these from the main branch because of the presence of C11224T (found in about 250 or ~40% of all BA.2.75.1 sequences), a lack of W152R, and multiple "reversions," including H339G, V210I, L157F, and, bizarrely, a K417T mutation followed by a T417K reversion. 
![image](https://user-images.githubusercontent.com/33738461/185643794-db55cc71-35c7-403d-96cc-fe150b5a8cb4.png)

There are 20 other BA.2.75 + D574V sequences without R346T that are right next to the 15-sequence BA.2.75+R346T branch. I looked at these sequences in NextClade, and every single one has no coverage at or very near S:346. The ones that say they do have coverage at 346 are missing other mutations in areas where they purport to have coverage. 
![image](https://user-images.githubusercontent.com/33738461/185649782-a192149e-eefa-4acd-bf19-0d300b280aee.png)

It seems likely to me that at least some, perhaps most, of these 20 sequences actually possess R346T and belong in the 15-sequence branch. The same is likely true for a lot of BA.2.75.1 sequences, whose coverage at S:346 mostly looks similar to the above picture. International sequencing should make matters much more clear, but it will likely take quite a bit of time.

**Comment by ryhisner** [comment]
The largest branch of this proposed sublineage now has 29 sequences, with recent sequences from Japan (travel from India), Australia, Ireland (2 sequences), Israel, and USA (Georgia). 
![image](https://user-images.githubusercontent.com/33738461/185763413-fb1794a0-6435-4c1c-a676-c006beec10e1.png)

The USA sequence and one Indian sequence also have S:T573I, giving them mutations on the adjacent spike codons 573 and 574.
![image](https://user-images.githubusercontent.com/33738461/185763533-0e165a2f-ca52-4930-86c1-78a7e1488cc0.png)

**Comment by corneliusroemer** [comment]
@ryhisner please provide a link when you share the Usher trees, it's a simple copy paste of a tree you've already generated ;)
