### ISSUE TITLE
BA.2.75 lineage with S:356T [43 seq, 2022-08-19, mostly India with 2x Israel/Singapore, 1x Japan/Germany/Denmark/Australia]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#947]
In recent uploads there has been an uptick in BA.2.75 with S:K356T, also notably with 8 out of 28 sequences from outside of India.

All but 3 sequences have been uploaded since the 9th of August (in the last 6 days).

It's probably too early to tell whether this is a monophyletic lineage or not but it's worth watching.

Some of the sequences are very close to the BA.2.75 polytomy.

Query for GISAID: `Spike_K356T,E_T11A,NSP3_S403L`

**Comment by icestorm972** [comment]
![BA 2 75_2022-08-10](https://user-images.githubusercontent.com/20755156/185068385-df9fd81a-b9f5-407f-a2d0-f34585dac0f0.png)
Germany has 3 BA.2.75 with S:R345T  in RKI Sequence DESH data since beginning of August (18 days mean lag between sampling date and report, so maybe more to show up)

**Comment by corneliusroemer** [comment]
We're up to 43 sequences now - of which 20 are from outside of India.

It does look like this arose directly on the BA.2.75 polytomy but to be sure it's probably best to wait a few more days.

There's an intriguing cluster in the US (2xTX, 1xNC) with a triple Spike mutation: S:356T, S:490S, S:49Y as well as N:163L.

The combination N:163L, S:356T has been seen 10 times in total, including 5x Austria and 2x India-RJ.

**Comment by c19850727** [comment]
There are also 3 genomes from UK with S:K356T+S:R357K that are already in Usher but not yet available in GISAID.

England/DHSC-CYFFKCD/2022
England/DHSC-CYG7NEB/2022
England/DHSC-CYRCNRQ/2022
