### ISSUE TITLE
BA.5.1 sublineage with Orf1b:D1903N and Orf1b:G662S (1120 Seqs) Dominant in Gambia (more than 50% last 6m)  

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#958]
After a long and complex discussion [(here)](https://twitter.com/siamosolocani/status/1559800390471802881) with @ryhisner on the less disadvantage of BA.5.1 vs BA.5.2 in USA in comparison of Uk or Denmark, while not arriving to a definitive answer, we were able to find a big undesignated branch of BA.5.1 defined by ORF1b:D1903N that seems to confer some advantage vs BA.5.1 baseline 
(Where still are included the fast sublineages BA.5.1.9 and BA.5.1.10 recently designated ).

BA.5.1 + Orf1b:D1903N 
counts already 3581 sequences [(Here)](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=+NextCladePangoLineage%3ABA.5.1*+%26+Orf1b%3A1903N&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&) 

(Up to @InfrPopGen @chrisruis @corneliusroemer if you want, If you think it is worth to do, to designate in two steps as BA.5.1.10/BK.1 or not.)

Here i want to propose a sublineage of this larger branch defined by Orf1b:G662S.

Orf1b:G662S is a defining Delta mutation that recently popped up again in BA.2.75 and BJ.1 too, as noted by @shay671 and others.

Defining mutations: 
BA.5.1 + C10507T + orf1b:D1903N + C29284T + Orf1b:G662S 

( credits to @alurqu for posting a better tree than mine in #930)
Tree:
![chrome_screenshot_1660742757952](https://user-images.githubusercontent.com/87669813/185145724-f0efe20d-4e9b-4b50-aba7-20e74a63386f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3fbc8_ccd890.json?branchLabel=aa%20mutations&c=gt-ORF1ab_5063,6304&label=nuc%20mutations:C241T,T670G,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,C10507T,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,G19174A,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,T27438C,C27807T,C27889T,A28271T,C28311T,G28881A,G28882A,G28883C,C29284T,A29510C,C29666T

CovSpectrum : https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=+NextCladePangoLineage%3ABA.5.1*+%26+Orf1b%3A1903N+%26+orf1b%3A662S&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

Nr.of sequences: 738
List of sequences:
[contributors (1).csv](https://github.com/cov-lineages/pango-designation/files/9363060/contributors.1.csv)

Countries (From CvSpectrum)
<div class="sc-eCYdqJ gqSwOL" style="border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity:1; --tw-shadow:0 0 #0000; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000; display: flex; -webkit-box-align: stretch; align-items: stretch; color: rgb(33, 37, 41); font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity:1; --tw-shadow:0 0 #0000; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000;"><div style="border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity:1; --tw-shadow:0 0 #0000; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000; width: 344px; overflow: hidden;"><div class="relative mx-0.5 mt-1 mb-5 md:mx-3 shadow-lg rounded-lg bg-white p-4  border  border-gray-100" style="border-width: 1px !important; border-style: solid !important; border-color: rgba(245,245,245,var(--tw-border-opacity)) !important; border-image: initial !important; box-sizing: border-box; --tw-border-opacity:1 !important; --tw-shadow:0 10px 15px -3px rgba(0,0,0,0.1),0 4px 6px -2px rgba(0,0,0,0.05) !important; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000; background-color: rgba(255,255,255,var(--tw-bg-opacity)) !important; border-radius: 0.5rem !important; box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow) !important; margin: 0.25rem 0.125rem 1.25rem !important; padding: 1rem !important; position: relative !important; --tw-bg-opacity:1 !important;"><div class="sc-papXJ bZXSof" style="border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity:1; --tw-shadow:0 0 #0000; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000; margin-bottom: 0px;"><div style="border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity:1; --tw-shadow:0 0 #0000; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000;"><div class="relative h-full" style="border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity:1; --tw-shadow:0 0 #0000; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000; position: relative !important; height: 362px;"><div class="sc-gicCDI cFtzpL" style="border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity:1; --tw-shadow:0 0 #0000; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000; overflow-y: auto; height: 300px;">

Argentina | 2 | 1.887%
-- | -- | --
Australia | 2 | 0.015%
Austria | 3 | 0.02%
Belgium | 33 | 0.156%
Brazil | 47 | 0.263%
Canada | 12 | 0.025%
Chile | 6 | 0.116%
Croatia | 1 | 0.229%
Czechia | 2 | 0.04%
Denmark | 60 | 0.034%
France | 52 | 0.038%
Germany | 116 | 0.039%
Ireland | 2 | 0.031%
Italy | 23 | 0.084%
Japan | 38 | 0.081%
Mexico | 4 | 0.059%
Netherlands | 40 | 0.155%
Poland | 2 | 0.249%
Russia | 3 | 0.17%
Slovakia | 4 | 0.077%
Slovenia | 6 | 0.213%
Spain | 20 | 0.081%
Sweden | 4 | 0.038%
Switzerland | 3 | 0.042%
United Kingdom | 85 | 0.014%
United States | 80 | 0.014%

</div></div></div></div></div></div></div></div><div class="sc-eCYdqJ gqSwOL" style="border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity:1; --tw-shadow:0 0 #0000; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000; display: flex; -webkit-box-align: stretch; align-items: stretch; color: rgb(33, 37, 41); font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity:1; --tw-shadow:0 0 #0000; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000;"><div style="border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity:1; --tw-shadow:0 0 #0000; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000; width: 344px; overflow: hidden;"><div class="relative mx-0.5 mt-1 mb-5 md:mx-3 shadow-lg rounded-lg bg-white p-4  border  border-gray-100" style="border-width: 1px !important; border-style: solid !important; border-color: rgba(245,245,245,var(--tw-border-opacity)) !important; border-image: initial !important; box-sizing: border-box; --tw-border-opacity:1 !important; --tw-shadow:0 10px 15px -3px rgba(0,0,0,0.1),0 4px 6px -2px rgba(0,0,0,0.05) !important; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000; background-color: rgba(255,255,255,var(--tw-bg-opacity)) !important; border-radius: 0.5rem !important; box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow) !important; margin: 0.25rem 0.125rem 1.25rem !important; padding: 1rem !important; position: relative !important; --tw-bg-opacity:1 !important;"><h1 class="sc-gKXOVf lmgzHd" style="border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity:1; --tw-shadow:0 0 #0000; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 #0000; --tw-ring-shadow:0 0 #0000; margin: 0px 0px 0.5rem; font-weight: 700; line-height: 1.75rem; font-size: 1.5rem;"></h1></div></div></div></div>

Growth advantage both vs BA.5.1* and BA.5.2*:

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5.1*&variantQuery1=+NextCladePangoLineage%3ABA.5.1*+%26+Orf1b%3A1903N+%26+orf1b%3A662S&analysisMode=CompareToBaseline&

To be noticed this is as trasmissible as BA.5.2* + Orf1b:1050N ( that is around 20% of global sequences in the last few days):
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.5.2*+%26+Orf1b%3A1050N&variantQuery1=+NextCladePangoLineage%3ABA.5.1*+%26+Orf1b%3A1903N+%26+orf1b%3A662S&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
I wasnt aware that @alurqu already proposed a sublineage of Orf1b:D1903N in #930 even if it belongs to a different branch from the one proposed it: 

copy and paste from the tree shown there by @Alurqu but with the lineage proposed here  highlighted in yellow
![Schermata 2022-08-18 alle 00 20 38](https://user-images.githubusercontent.com/87669813/185253749-899c534d-559f-4ef2-807b-f7db78ee0c88.png)


https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice1_genome_BA.5.1+ORF1a_417Y+ORF1b_1476S+ORF1b_1903N+ORF1b_310I+ORF7a_30H+S_346T+10507T.json?branchLabel=aa%20mutations&c=gt-ORF1ab_5063&label=nuc%20mutations:C241T,T670G,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C10029T,C10198T,G10447A,C10449A,G12160A,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,T22917G,G22992A,C22995A,A23013C,T23018G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23854A,G23948T,A24424T,T24469A,C25000T,C25584T,C26060T,C26270T,G26529A,C26577G,G26709A,T27438C,C27807T,C27889T,A28271T,C28311T,G28881A,G28882A,G28883C,A29510C,C29666T

**Comment by FedeGueli** [comment]
Gisaid query NSP12_G671S,NSP14_D379N (BA.5.1) finds now 806 virus with a new uploaded batch from japan (early July) and Germany.
Since the beginning of August has been collected 66 viruses of this sublineage. It seems fast growing in different part of the world.

@corneliusroemer please take  a look at this.

**Comment by FedeGueli** [comment]
55 new viruses uploaded to Gisaid from two days ago. Total Gisaid count is 845.

To be noticed a good share of new samples are from Japan so that brings total number from there to 48

**Comment by FedeGueli** [comment]
@corneliusroemer 859seqs as today. Being already quite big and with a comparable transmissibility to Orf1b:1050N, along with BA.5.1.9 and BA.5.1.19, this is one of the few BA.5.1 that could play a role vs BA.2.75.

**Comment by FedeGueli** [comment]
874 viruses on Gisaid as today.

Notably more than 20 samples from Gambia uploaded yesterday that Usher calls BA.5.2.1 but they are BA.5.1 and belong to this proposed lineage cc @AngieHinrichs (IMPORTANT)
![Schermata 2022-08-24 alle 16 16 42](https://user-images.githubusercontent.com/87669813/186441956-989f1363-c022-48c9-b982-5bca50f20ebb.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_62c5_5f6700.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C10507T,G19174A

**Comment by FedeGueli** [comment]
cc @corneliusroemer @InfrPopGen @chrisruis @aq-sun @thomaspeacock
**Update on Gambia**:
 it seems this lineage represents 50% of sequences sampled there in the last 6 months .[(covspectrum ) ](https://cov-spectrum.org/explore/Gambia/AllSamples/Past6M/variants?aaMutations=ORF1b%3AG662S%2CORF1b%3AD1903N&nextcladePangoLineage=BA.5.1*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L& )Suggesting a prevalence near 100% there considering that the first sequence was sampled there only on 29/6 (EPI_ISL_14598972) likely the february sequences are date input errors.

There are 65 samples of this lineages from Gambia:

EPI_ISL_14241248
EPI_ISL_14241249
EPI_ISL_14241252
EPI_ISL_14241253
EPI_ISL_14241258
EPI_ISL_14241259
EPI_ISL_14243845
EPI_ISL_14243847
EPI_ISL_14243848
EPI_ISL_14243850
EPI_ISL_14243851
EPI_ISL_14243852
EPI_ISL_14243859
EPI_ISL_14243860
EPI_ISL_14243863
EPI_ISL_14243866
EPI_ISL_14243867
EPI_ISL_14330373
EPI_ISL_14426780
EPI_ISL_14426781
EPI_ISL_14426782
EPI_ISL_14426783
EPI_ISL_14426784
EPI_ISL_14426785
EPI_ISL_14426787
EPI_ISL_14426788
EPI_ISL_14426792
EPI_ISL_14426793
EPI_ISL_14426797
EPI_ISL_14426798
EPI_ISL_14426800
EPI_ISL_14426801
EPI_ISL_14426802
EPI_ISL_14426803
EPI_ISL_14426804
EPI_ISL_14426805
EPI_ISL_14426806
EPI_ISL_14426808
EPI_ISL_14426812
EPI_ISL_14426814
EPI_ISL_14598963
EPI_ISL_14598965
EPI_ISL_14598966
EPI_ISL_14598968
EPI_ISL_14598969
EPI_ISL_14598972
EPI_ISL_14598973
EPI_ISL_14598974
EPI_ISL_14598975
EPI_ISL_14598977
EPI_ISL_14598978
EPI_ISL_14598982
EPI_ISL_14598983
EPI_ISL_14598991
EPI_ISL_14598992
EPI_ISL_14598994
EPI_ISL_14598997
EPI_ISL_14598998
EPI_ISL_14598999
EPI_ISL_14599000
EPI_ISL_14599001
EPI_ISL_14599004
EPI_ISL_14604102
EPI_ISL_14604104
EPI_ISL_14604106

**Comment by AngieHinrichs** [comment]
> Usher calls BA.5.2.1 but they are BA.5.1 and belong to this proposed lineage cc @AngieHinrichs (IMPORTANT) EDITED it is an entire BA.5.1 like branch classified as BA.5.2.1

Yes, thanks @FedeGueli -- in the Usher tree, currently BA.5.2.1 has a "mini-BA.5" with BA.5.1, BA.5.5 and BA.5.6 as well as plain old BA.5.  What all those sequences have in common that pulls them into one branch is A21766C and G21770A (S:V70I).  -- Ah, those are at the site of a BA.5 deletion of 21765-21770!  I have been masking that region for BA.1 which also has the deletion, but I need to do that for BA.5 too!

So I should be able to fix this within a couple days.  Thanks again!

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs !  Great expl!

**Comment by FedeGueli** [comment]
959 Sequences as today on Gisaid for NSP12_G671S,NSP14_D379N BA.5.1

160 Sequences of the branch  with Orf7a:P34H that seems growing very fast in Japan ( it was 48 seqs just 6 days ago)
(NS7a_P34H,NSP12_G671S,NSP14_D379N to track it)
cc @corneliusroemer @chrisruis @InfrPopGen @aq-sun  i think a double designation here is needed the main lineage with Orf1b:1903N +orf1b:662S and then its sublineage with Orf7a:P34H

**Comment by FedeGueli** [comment]
More recent collected samples from Germany and Mexico. 
interestingy i found that the oldest collected samples of this lineage have been falgged by Gisaid as Mixed Lineage due to the Orf1b:662S, and we are talking of May 2022. It is unbelievable as in a just a few months we are already used to see Orf1b:662 mutations in Omicron backbone. This makes me think about the plasticity of this virus.

Beyond these 2 cents chats It is a global sublineage i think it deserves a designation, while i drop my requestto designate the japanese branch:
considering samples collected there (Japan) in the second half of August their ongoing ( and quite brutal) wave is driven by BA.5.2 with Orf1b:1050N that is around half of recent samples followed by BA.5.2.1* accounting for another 30%, the role of BA.5.1 is very limited less than 10%.

**Comment by FedeGueli** [comment]
Japan uploaded a lot of new sequences in the last days so with the query NS7a_P34H,NSP12_G671S,NSP14_D379N,  i can found 189 sequences of the sublineage with Orf7a:P34H, 68 of them sampled in Japan

**Comment by FedeGueli** [comment]
@corneliusroemer i see your re doing a great wotk with new BA.2.75 lineages, if you spare some time maybe take a look at this one, it has not a growth advantage versus Orf1b:1050N but still not far from it, more one branche of it defined by Orf7a:P34H started circulating in Japan.

To me it is ok both to designate or to close this one even if it would be a pity not to assign a lineage to a so evident convergent evolution with Orf1b:662S

**Comment by FedeGueli** [comment]
1120 sequences , this goes on growing , today 14 new sequences from 9 countries

**Comment by FedeGueli** [comment]
24 viruses uploaded in the last two days from 11 countries , it is circualting from Carribean area to central europe, from Usa to Chile, really i do see reasons  to designate this one,

**Comment by InfrPopGen** [comment]
Thanks for submitting. So far we've added lineage BA.5.1.21 with 911 newly designated sequences, and 129 updated designations from BA.5.1. Defining mutation G15451A (Orf1ab:G5063S).

**Comment by InfrPopGen** [comment]
Also added BT.1 with 0 new sequence designations, and 188 updated designations from BA.5.1.21, defining mutation C27494A (Orf7a:P34H).

**Comment by FedeGueli** [comment]
Thanks a lot @InfrPopGen
