### ISSUE TITLE
New BA.5.2 + Orf1b:1050N sublineage with Orf1a:I4291V and S:346T (105 seqs - UK )

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#959]
Here i want to propose another BA.5.2 + orf1b:T1050N sublineage with S:346T.

it was briefly discussed in #870 with @AngieHinrichs .

Now it grew to 63 sequences mainly in UK so i put here to be properly monitored.

Definining mutations: 
BA.5.2 (C1627T + A28330G)
in the branch with 12310A (edited) and Orf1b:T1050N (C16616A)
then
C27513T
then 
C27012T
then 
A13136G (Orf1a:I4291V)
then 
C13264T 
then
S:346T (22599C)

![Schermata 2022-08-18 alle 00 04 38](https://user-images.githubusercontent.com/87669813/185251607-035df711-e6d9-4439-a8ad-f39eab37bbac.png)

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2fc19_d63750.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C13264T

CovSpectrum Overview: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=NextCladePangoLineage%3ABA.5*+%26+Orf1b%3A1050N++%26+Orf1a%3AI4291V+%26+S%3A346T&variantQuery1=NextCladePangoLineage%3ABA.5.2+%26+S%3AR346T+%26+Orf1b%3A1050N+%26+27012T++%26+13136A+&

Growth advantage in Uk seems relevant although too few sequences to say anything:
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past2M/variants?variantQuery=NextCladePangoLineage%3ABA.5.2*+%26+Orf1b%3A1050N++&variantQuery1=NextCladePangoLineage%3ABA.5*+%26+Orf1b%3A1050N++%26+Orf1a%3AI4291V+%26+S%3A346T&analysisMode=CompareToBaseline&

First sequence: England/QEUH-3E7CC40/2022|OX146326.1|2022-06-23
List of EPI_ISLs:
[contributors (1).csv](https://github.com/cov-lineages/pango-designation/files/9366291/contributors.1.csv)

cc @corneliusroemer

**Comment by FedeGueli** [comment]
Gisaid Query: NSP10_I38V,Spike_R346T  today gives 65 viruses.

**Comment by FedeGueli** [comment]
A Gisaid query composed in the following way'Spike_R346T,NSP13_T127N,NSP10_I38V' today  gives 66 viruses 

While 69 are on Usher:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f3ff_2b3a40.json?c=userOrOld&label=nuc%20mutations:G22599C

It keeps looking a cluster maybe driven by some superspreader event at the end of July, but st 
ill its growth it is very fast and it could end to resemble the newly designated BA.5.2.6 one.

**Comment by FedeGueli** [comment]
69 seqs on Gisaid (Spike_R346T,NSP13_T127N,NSP10_I38V)
72 on Usher:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_324f2_4faa30.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C13264T
One recent sequence

**Comment by FedeGueli** [comment]
Spike_R346T,NSP13_T127N,NSP10_I38V  gives 79 sequences on Gisaid today. Always Uk

**Comment by FedeGueli** [comment]
84 Viruses on Gisaid ( Spike_R346T,NSP13_T127N,NSP10_I38V) as today.

**Comment by FedeGueli** [comment]
One more sequence from England.

**Comment by FedeGueli** [comment]
99 viruses as today on Gisaid with the following query: Spike_R346T,NSP13_T127N,NSP10_I38V

**Comment by FedeGueli** [comment]
105 sequences as today after four more sequences came from UK and one each from France and Italy.
It has to be noted that all the recent collected samples (8)  from Uk carry an additional spike mutation S:N125T

Now this has more than 100 sequences and have spread to other 10 countries beyond UK:
Ireland, italy, Canada, Australia, France,Sweden, Australia, Usa, Romania and Germany
@corneliusroemer @chrisruis @InfrPopGen looking at its growth advantage it is still around 50% versus the infamous BA.5.2 + orf1b:1050N (that is the biggest fast lineage circulating in the world as today).
![Schermata 2022-09-06 alle 01 26 10](https://user-images.githubusercontent.com/87669813/188520271-d6cb9290-9c0e-4326-a310-6fb8c04d49fd.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.13 with 66 newly designated sequences, and 3 updated designations from BA.5.2. Defining mutation G22599C (S:R346T).

**Comment by alurqu** [comment]
@InfrPopGen Is this BA.5.2.13 the same lineage as the one listed on https://www.pango.network/summary-of-designated-omicron-lineages/?

**Comment by AngieHinrichs** [comment]
Good catch @alurqu -- I think that version of BA.5.2.13 was previously added to https://www.pango.network/summary-of-designated-omicron-lineages/ mistakenly, and this issue is the real BA.5.2.13, but @InfrPopGen can confirm.  Unfortunately I don't know how to update that web page, but I expect it will be fixed within a day or so.

**Comment by InfrPopGen** [comment]
> @InfrPopGen Is this BA.5.2.13 the same lineage as the one listed on https://www.pango.network/summary-of-designated-omicron-lineages/?

I was just typing what Angie wrote above. It was apparently an orphan lineage, it did not exist in lineages.csv before I designated it as that England lineage with S:346T in this issue today.
