### ISSUE TITLE
Emilia Romagna Lineage

### ISSUE THREAD

**Issue by gdirani** [cov-lineages/pango-designation#96]
Sub lineage of: B.1
Earliest sequence 2021-05-28
Countries circulating: Italy
Gisaid Accession ID: EPI_ISL_2200731

**Comment by AngieHinrichs** [comment]
@gdirani thanks for submitting this, but a single sequence is not sufficient to define a new lineage.  The criteria for a new lineage are detailed here: https://pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/
