### ISSUE TITLE
BA.2.75 sublineage with S:R346T, S:F486S, S:D1199N  (17 seq. India, Chile, England, Singapore, Spain, Germany, South Korea, Australia, USA. 2022-08-19)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#963]
Proposal for a sublineage of BA.2.75
Earliest sequence: 04.07.2022 (India)
Countries detected: India, Chile, England, Singapore, Spain, Germany

Defining mutation:
S:R346T
S:F486S
S:D1199N

This variant is defined by S:R346T, S:F486S, S:D1199N and was first detected in India. Now it is present in 6 countries across 3 continents (expansion into Germany with todays GISAID upload). 11 seq on Usher as of 18.08.22. Sequences carrying S:D1199N where mentioned by @RajLABN in #918. However the proposed sublineage is apparently distinct from those mentioned in #961 (i.e.  #918, #957, #944). Sequence quality is fine but the sublineage currently clusters with a bunch of lower quality sequences with a lot of dropouts (see below).

![grafik](https://user-images.githubusercontent.com/102166254/185420164-a34d9910-3e82-44fd-adbd-3f9b895b4695.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39c1_e48170.json?branchLabel=aa%20mutations&c=gt-S_346,486

![grafik](https://user-images.githubusercontent.com/102166254/185420698-73c74c95-f5d1-4287-9e1a-0a964b1c4489.png)

![grafik](https://user-images.githubusercontent.com/102166254/185424665-caae4161-a48b-4197-a552-bce0cb3269de.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AR346T%2CS%3AF486S%2CS%3AD1199N&pangoLineage=BA.2.75*&

EPI_ISL_14290506
EPI_ISL_14307810
EPI_ISL_14441071
EPI_ISL_14458978
EPI_ISL_14480635
EPI_ISL_14480645
EPI_ISL_14517967
EPI_ISL_14519683
EPI_ISL_14521272

**Comment by agamedilab** [comment]
Expansion into South Korea, Australia, USA with yesterdays uploads. 17 seq. on usher as of 19.08.22. 

![grafik](https://user-images.githubusercontent.com/102166254/185556989-31a1d998-8759-4a6b-a165-4c6661f5d20b.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_b34e_f2bbe0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C5192T,T23019C,G25157A

**Comment by corneliusroemer** [comment]
I independently noticed this lineage when reviewing new uploads of BA.2.75

It is an independent lineage not obviously related to any other of the big circulating branches - so I think this is ready for designation - especially considering the Spike profile and rapid growth internationally.

Nucleotide mutations on top of BA.2.75:
C5192T, G22599C, T23019C, G25157A

**Comment by agamedilab** [comment]
many thanks! If you have time I would be very happy if a label / milestone could be added to this issue. All the best! @corneliusroemer @InfrPopGen
