### ISSUE TITLE
Potential BA.2.75 Sublineage with ORF1a:T3959A (282 seqs as of 2022-09-10; India with spread)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#967]
There may be a BA.2.75 sublineage with ORF1a:T3959A (A12140G) first detected in India.  Despite an insignificant growth advantage relative to BA.2.75 and despite the UShER tree issues, this is being proposed in association with [Issue 961](https://github.com/cov-lineages/pango-designation/issues/961)'s suggestion to designate BA.2.75 branches.

As of 2022-08-19, Cov-Spectrum reports 161 BA.2.75+ORF1a:3959A sequences:
![BA 2 75+ORF1a_3959A-Counts-20220819](https://user-images.githubusercontent.com/88959107/185709731-6f7cd9e5-fdd5-498c-b99d-865e09f51f03.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.2.75+%26+ORF1a%3AT3959A&

The growth advantage compared to BA.2.75* in India can be found at:
https://cov-spectrum.org/explore/India/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.2.75*&variantQuery1=nextcladePangoLineage%3ABA.2.75+%26+ORF1a%3AT3959A&analysisMode=CompareToBaseline&

The growth advantage compared to BA.5* in India can be found at::
https://cov-spectrum.org/explore/India/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABA.2.75+%26+ORF1a%3AT3959A&analysisMode=CompareToBaseline&

As of 2022-08-19, UShER shows the GenBank samples on two branches form BA.2.75. However, upon closer examination the base of the one branch (the upper branch in the image) involves M:Q19E with BA.2.75 to M:E19Q and back to M:Q19E with ORF1a:T3959A.  This may be an errant placement, so actually there may be only one BA.2.75+ORF1a:3959A branch.
![BA 2 75+ORF1a_3959A-UShER-20220819](https://user-images.githubusercontent.com/88959107/185709766-247d62bf-63df-415b-92b8-7c54ca347a05.png)
To visualize on UShER: https://nextstrain.org/fetch/raw.githubusercontent.com/alurqu/pango-designation-support-alurqu/main/2022/08/subtreeAuspice1_genome_BA.2.75%2BORF1a_3959A.json?c=gt-ORF1ab_3959&label=nuc%20mutations:C4586T,A22001G

First Outbreak.info sequence: India 2022-06-11

First GenBank sequence: New Jersey, USA 2022-07-17 

Most Recent GenBank sequence: Kansas, USA 2022-07-31

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at [Support-BA.2.75+ORF1a_3959A.zip](https://github.com/cov-lineages/pango-designation/files/9385485/Support-BA.2.75%2BORF1a_3959A.zip)

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=BA.2.75&muts=ORF1a%3AT3959A.

**Comment by corneliusroemer** [comment]
Growth disadvantage, this thing is dying. Hence closing.

<img width="2522" alt="image" src="https://user-images.githubusercontent.com/25161793/190876681-cf9c8661-8293-4a93-abfc-f6b8370522ef.png">
