### ISSUE TITLE
Potential BA.2.75 Sublineage with ORF3a:T89I (18 seqs; India, USA, UK, Germany)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#968]
There may be a BA.2.75 sublineage with ORF3a:T89I (C25658T) first detected in Haryana, India and soon thereafter in Washington State, USA.  Despite the low number of sequences, this is being proposed in association with [Issue 961](https://github.com/cov-lineages/pango-designation/issues/961)'s suggestion to designate BA.2.75 branches.

As of 2022-08-19, Cov-Spectrum reports 18 BA.2.75+ORF3a:89I sequences:
![BA 2 75+ORF3a_89I-Counts-20220819](https://user-images.githubusercontent.com/88959107/185712926-ba17d60a-8dc3-485e-8dfd-7735a24ffd56.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.2.75+%26+ORF3a%3AT89I&

When enough data becomes available, the growth advantage compared to BA.2.75* in the United States can be found at:
https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.2.75*&variantQuery1=nextcladePangoLineage%3ABA.2.75+%26+ORF3a%3AT89I&analysisMode=CompareToBaseline&

When enough data becomes available, the growth advantage compared to BA.5* in the United States can be found at:
https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABA.2.75+%26+ORF3a%3AT89I&analysisMode=CompareToBaseline&

As of 2022-08-19, UShER shows all of the GenBank samples are on a single subtree:
![BA 2 75+ORF3a_89I-UShER-20220819](https://user-images.githubusercontent.com/88959107/185712967-c484ad11-b081-4050-be91-309cb86f0af9.png)

To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/08/subtreeAuspice1_genome_BA.2.75%2BORF3a_89I.json?c=gt-ORF3a_89&label=nuc%20mutations:C4586T,A22001G

First Outbreak.info sequence: Hiryana, India 2022-07-02

First GenBank sequence: Washington State, USA 2022-07-03 

Most Recent GenBank sequence: California, USA 2022-07-15

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at [Support-BA.2.75_ORF3a_89I.zip](https://github.com/cov-lineages/pango-designation/files/9385577/Support-BA.2.75_ORF3a_89I.zip)

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=BA.2.75&muts=ORF3a%3AT89I.

**Comment by chrisruis** [comment]
We need new issues to either have an epidemiological event or be close to exhibiting an epidemiological event before opening. Will therefore close this one for now
