### ISSUE TITLE
BA.2 sublineage with S:I651V, S:A831T, S:G252V, S:T573I, ORF1a:A3143V (33 seq. Japan)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#983]
Proposal for a sublineage of BA.2
Earliest sequence: 19.06.2022 (Japan)
Countries detected: Japan

Defining mutation:
A23513G = S:I651V
G24053A = S:A831T
G22317T = S:G252V
C23280T = S:T573I
C9693T = ORF1a:A3143V
C16260T

GISAID query: Spike_G252V, Spike_T573I, Spike_A831T, Spike_I651V

This BA.2 sublineage is defined by S:I651V, S:A831T, S:G252V, S:T573I, ORF1a:A3143V and was only detected in Japan so far. Sequences are derived from three different uploads and mutliple submitting labs. Quality is apparently fine. 33 seq on usher as of 23.08.22. 

![grafik](https://user-images.githubusercontent.com/102166254/186144603-a3e71c23-385c-4fe0-b003-b7b248c9c253.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_a3cf_48cc10.json?branchLabel=aa%20mutations&c=gt-S_252

![grafik](https://user-images.githubusercontent.com/102166254/186144266-b53320b5-95dc-4672-8e6e-777b3d3b4275.png)

![grafik](https://user-images.githubusercontent.com/102166254/186146324-3da90ec4-23be-45a1-8184-ab10a64ec587.png)
https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?aaMutations=S%3AG252V%2CS%3AT573I%2CORF1a%3AA3143V%2CS%3AI651V%2CS%3AA831T&nextcladePangoLineage=BA.2*&aaMutations1=S%3AG252V%2CS%3AT573I%2CORF1a%3AA3143V%2CS%3AI651V%2CS%3AA831T&nextcladePangoLineage1=BA.2*&

Currently no growth advantage vs. BA.5:

Growth advantage vs. BA.2 Japan:

https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?pangoLineage=BA.2*&aaMutations1=S%3AG252V%2CS%3AT573I%2CORF1a%3AA3143V%2CS%3AI651V%2CS%3AA831T&nextcladePangoLineage1=BA.2*&analysisMode=CompareToBaseline&

Growth advantage vs. BA.5 Japan:

https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?pangoLineage=BA.5*&aaMutations1=S%3AG252V%2CS%3AT573I%2CORF1a%3AA3143V%2CS%3AI651V%2CS%3AA831T&nextcladePangoLineage1=BA.2*&analysisMode=CompareToBaseline&

EPI_ISL_14141202
EPI_ISL_14140514
EPI_ISL_14141705
EPI_ISL_14346716
EPI_ISL_14342499
EPI_ISL_14344414
EPI_ISL_14089425
EPI_ISL_14129925
EPI_ISL_14141792
EPI_ISL_14129138
EPI_ISL_14128260
EPI_ISL_14128232
EPI_ISL_14129196
EPI_ISL_14128950
EPI_ISL_14128247
EPI_ISL_14128923
EPI_ISL_14139590
EPI_ISL_14128927
EPI_ISL_14126058
EPI_ISL_14140508
EPI_ISL_14128898
EPI_ISL_14134626
EPI_ISL_14128268
EPI_ISL_14125027
EPI_ISL_14128899
EPI_ISL_14340861
EPI_ISL_14341210
EPI_ISL_14129188
EPI_ISL_14349855
EPI_ISL_14340845
EPI_ISL_14349869
EPI_ISL_14140706
EPI_ISL_14349856

**Comment by corneliusroemer** [comment]
Thanks for flagging. I've removed the growth advantage plots because they are not reliable for such small numbers and more likely to mislead

**Comment by agamedilab** [comment]
41 on usher as of 16.09.22.

![grafik](https://user-images.githubusercontent.com/102166254/190655694-706aa994-9d9a-42bc-8169-dded7293b037.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3b7d_47fe00.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C9693T,G22317T,C23280T

**Comment by corneliusroemer** [comment]
I would designate this at the base and not so deep, as S:651V on top of the big BA.2 9866 polytomy.

Then it's also more relevant - being somewhat bigger. Still only 100 sequences but it seems to be still alive.

@InfrPopGen @aq-sun could you designate this as the subtree on top of BA.2 - Japan lineage, without the extra mutations suggested?

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.85 with 148 newly designated sequences, and 0 updated designations. Defining mutation(s) A23513G (S:I651V) (following C2790T then C28432T).

**Comment by AngieHinrichs** [comment]
Yes, I recently started masking 28877 and 28878 in the BA.2 branch because they were causing problems.  In general those two sites are very homoplasic (or error-prone??) in B.1.1.  They seem to be mostly fixed in Gamma (P.1) but blink on and off quite a bit in Alpha and Omicrons.
