### ISSUE TITLE
New BA.5.3.1 sublineage with S:R346I, S:Q613E and multiple AA mutations circulating in Europe (19 seqs) and in Japan (24 seqs) with an additional defining mutation Orf6:K42R, 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#985]
This has been discussed already in #865 with @silcn and @corneliusroemer .

I would like to propose this sublineage of BA.5.3.1 that has apparently a quite long history of stepwise evolution (@shay671 maybe interested in):

This likely emerged in South Africa as a branch of BA.5.3.1 with Orf1a:T568I  ( cfr EPI_ISL_13048601)

Then in South Africa likely acquired S:R346I ( cfr EPI_ISL_14223564)

then acquired ( and this corresponds to introduction in Europe (Greece : EPI_ISL_13904900 but also England)
C22264T 
C23054A = S:R498R ( on usher it is displayed as S:498K but this has been explained well in #865 by @silcn cc @AngieHinrichs )
C28087T = ORF8 :A65V

then acquired further 
ORF1a:T12I (C300T)
and S:Q613E (C23399G) 

Then it bifurcates in two branches:
One "european"defined by T24424C that counts 17 sequences ( be aware it has been uploaded today one from Chile collected on 9th August : EPI_ISL_14577798) on GISAID with the query NSP1_T12I, Spike_Q613E 

The other one instead was introduced in Japan (likely from Greece) and it is defined by 
C17130T
and
ORF6:K42R (= A27326G)
and counts 14 sequences as today on GISAID with the query NS6_K42R, Spike_Q613E 
( be aware it was introduced also in Canada and Australia)

Tree:

![Schermata 2022-08-23 alle 16 23 36](https://user-images.githubusercontent.com/87669813/186183575-de835da9-1865-4077-8365-432bf002eed6.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_98e4_4dcda0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C1968T

List of good quality sequences:
European branch:
EPI_ISL_13872388
EPI_ISL_14096310
EPI_ISL_14320621
EPI_ISL_13841040
EPI_ISL_14096174
EPI_ISL_14532308
EPI_ISL_13840651
EPI_ISL_13968009
EPI_ISL_14441538
EPI_ISL_14332707

Branch with Orf6:K42R circulating in Japan
EPI_ISL_14089362
EPI_ISL_14514999
EPI_ISL_14344037
EPI_ISL_14161106
EPI_ISL_14344055
EPI_ISL_14510754
EPI_ISL_14089456
EPI_ISL_14225142
EPI_ISL_14344010

To track this on CovSpectrum:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1a%3AT568I%2CS%3A346I%2COrf1a%3AT12I%2CS%3A613E%2COrf8%3A65V&nucMutations=C23054A&aaMutations1=S%3A339N%2CS%3A157S%2CS%3A1264M&

**Comment by FedeGueli** [comment]
17 sequences as today for ORF6:K42R branch
18 sequences as today for the other branch.
35 total sequences on Gisaid as today.

**Comment by FedeGueli** [comment]
38 viruses as today, the branch that seems growing faster is the japanese one with Orf6:K42R

**Comment by FedeGueli** [comment]
One more sequences from Sweden.

**Comment by FedeGueli** [comment]
One more sequence from Japan , 40 total

**Comment by FedeGueli** [comment]
3 new seqs from the japanese branch . 43 tot count

**Comment by corneliusroemer** [comment]
Too small and not fast growing. Let's close for now.

**Comment by FedeGueli** [comment]
46 sequences as today. slow as usual
