### ISSUE TITLE
Potential BA.5.2 Sublineage with ORF1b:T1050N, C16293T, and ORF1a:E745K (170 seqs as of 2022-09-17; Europe, North America, Israel, and Chile)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#987]
There may be a BA.5.2 sublineage with C16293T and ORF1a:E745K (G2498A, NSP2:E565K) first detected in Ireland or in the United Kingdom.

As of 2022-08-23, Cov-Spectrum reports 109 BA.5.2+ORF1a:745K+16293T sequences:
![BA 5 2+ORF1a_745K+16293T-Count-20220823](https://user-images.githubusercontent.com/88959107/186223484-e6ee9cc6-1d60-432d-91a8-20b26ce6754d.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2+%26+ORF1a%3AE745K+%26+C16293T&

As of 2022-08-23, Cov-Spectrum calculates a growth advantage of 26% compared to BA.5.2* in the United Kingdom:
![BA 5 2+ORF1a_745K+16293T-Growth_vs_BA 5 2-20220823](https://user-images.githubusercontent.com/88959107/186223566-62ad2b2b-0195-4bad-9977-d496bcf2baa2.png)
Source: https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2*&variantQuery1=nextcladePangoLineage%3ABA.5.2+%26+ORF1a%3AE745K+%26+C16293T&analysisMode=CompareToBaseline&

As of 2022-08-23, Cov-Spectrum calculates a growth advantage of 32% compared to BA.5* in the United Kingdom:
![BA 5 2+ORF1a_745K+16293T-Growth_vs_BA 5-20220823](https://user-images.githubusercontent.com/88959107/186223616-0bb484da-62af-4271-974b-04b4135c7bc9.png)
Source: https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABA.5.2+%26+ORF1a%3AE745K+%26+C16293T&analysisMode=CompareToBaseline&

As of 2022-08-23, UShER shows all of the GenBank samples are on a single subtree:
![BA 5 2+ORF1a_745K+16293T-UShER-20220823](https://user-images.githubusercontent.com/88959107/186223660-8d818700-b3ee-4ab5-bc82-ec8e2533d2a5.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/08/subtreeAuspice1_genome_BA.5.2%2BORF1a_745K%2B16293T.json?branchLabel=aa%20mutations&c=gt-ORF1ab_745

Potential First Outbreak.info sequences: United Kingdom and also Ireland 2022-06-20.

First GenBank sequence: England, United Kingdom 2022-06-29 

Most Recent GenBank sequence: England, United Kingdom 2022-08-04

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at [Support-BA.5.2+ORF1a_745K+16293T.zip](https://github.com/cov-lineages/pango-designation/files/9409101/Support-BA.5.2%2BORF1a_745K%2B16293T.zip)

The closest Outbreak.info link for this potential lineage (nucleotide mutations are not supported) is https://outbreak.info/situation-reports?pango=BA.5.2&muts=ORF1a%3AE745K. 

Of potential additional note: The sequences on the immediately-upstream UShER branch are from Illinois, USA.

**Comment by FedeGueli** [comment]
This one is in the branch with Orf1b:T1050N

**Comment by alurqu** [comment]
> This one is in the branch with Orf1b:T1050N

@FedeGueli Good catch! According to CoV-Spectrum, ORF1b:T1050N is now 70.77% of Nextclade BA.5.2.  According to Outbreak.info (https://outbreak.info/compare-lineages?pango=BA.5.2), ORF1b:T1050N is now 76% of BA.5.2.  Also, my processing shows ORF1b:T1050N as 70.88% of BA.5.2 in the GenBank data.  Since my processing only counts a mutation as novel in a lineage if it occurs less than 50% of the time in the GenBank sequences for the lineage, my processing is not counting ORF1b:T1050N as novel in BA.5.2 due the now-high prevalence of ORF1b:T1050N within base BA.5.2.

In recognition of your catch, I'm adding ORF1b:T1050N to this proposal's title.

**Comment by FedeGueli** [comment]
Yeah @alurqu i have tried until the last minute to make it designated BA.5.2.2 , it would have simplified a lot things also looking at Usher trees where it is always already in the root

**Comment by alurqu** [comment]
> Yeah @alurqu i have tried until the last minute to make it designated BA.5.2.2 , it would have simplified a lot things also looking at Usher trees where it is always already in the root ( i mean you cant view immediately but just opening the main branch)

@FedeGueli Yes, you did propose expansion of BA.5.2.2 to start with ORF1b:T1050N in [Issue 890](https://github.com/cov-lineages/pango-designation/issues/890).  I wanted to document why I kept missing ORF1b:T1050N between BA.5.2 and new proposed BA.5.2.2 sublineages.

**Comment by alurqu** [comment]
CoV-Spectrum shows a 16% growth advantage over BA.5.2+ORF1b:T1050N in the United Kingdom:
![BA 5 2+ORF1a_745K+ORF1b_1050N+16293T-Growth_vs_BA 5 2+ORF1b_1050N-20220824](https://user-images.githubusercontent.com/88959107/186470951-50320818-0ed4-496d-94c5-b2a224132b1a.png)
Source: https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2*+%26+ORF1b%3AT1050N&variantQuery1=nextcladePangoLineage%3ABA.5.2+%26+ORF1b%3AT1050N+%26+ORF1a%3AE745K+%26+C16293T&analysisMode=CompareToBaseline&

**Comment by corneliusroemer** [comment]
Very small - can you try to propose bigger branches on the ORF1b:T1050N polytomy?

It's a good idea to break down the BA.5.2 + ORF1b:1050N polytomy to reduce unspecific BA.5.2 calls.

I've designated two large lineages without proposal that were also on that polytomy. That should help make analysis of sequences in that part of the tree easier in the future.
