### ISSUE TITLE
Plain BA.2 with S:L452M (676 seq. mostly Japan)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#988]
Proposal for a sublineage of BA.2
Earliest sequence: 14.03.2022 (Japan)
Countries detected: mostly Japan (673), Spain (2), USA (1)

Defining mutation:
C22916A = S:L452M

In the usher tree next to the sublineage proposed in #983 i stumbled across another plain BA.2 clade with S:L452M which almost exclusively occurs in Japan only. Probably already burned out. 676 seq on usher as of 23.08.22.

![grafik](https://user-images.githubusercontent.com/102166254/186239550-ca08ed7d-01d6-45eb-9c64-8cf1a6c9d07c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3bf03_51ccd0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:C22916A

![grafik](https://user-images.githubusercontent.com/102166254/186240644-e266d6c6-1bde-4ff3-90d8-acb47b54bca3.png)
https://cov-spectrum.org/explore/Japan/AllSamples/Past6M/variants?aaMutations=S%3AL452M&pangoLineage=BA.2*&aaMutations1=S%3AL452M&pangoLineage1=BA.2*&

EPI_ISL_12248961, EPI_ISL_12248962, EPI_ISL_12868582, EPI_ISL_12870057, EPI_ISL_12870058, EPI_ISL_12870059, EPI_ISL_12937184, EPI_ISL_12937917, EPI_ISL_12938859, EPI_ISL_12941537, EPI_ISL_12941908, EPI_ISL_12947667, EPI_ISL_13091860, EPI_ISL_13126622, EPI_ISL_13127067, EPI_ISL_13204584, EPI_ISL_13205134, EPI_ISL_13205182, EPI_ISL_13205271, EPI_ISL_13205680, EPI_ISL_13205765, EPI_ISL_13206029, EPI_ISL_13206105, EPI_ISL_13206106, EPI_ISL_13206289, EPI_ISL_13206338, EPI_ISL_13206339, EPI_ISL_13206347, EPI_ISL_13208376, EPI_ISL_13208408, EPI_ISL_13213434, EPI_ISL_13216995, EPI_ISL_13216997, EPI_ISL_13293338, EPI_ISL_13293358, EPI_ISL_13293442, EPI_ISL_13294110, EPI_ISL_13294261, EPI_ISL_13294412, EPI_ISL_13295201, EPI_ISL_13337215, EPI_ISL_13397474, EPI_ISL_13397493, EPI_ISL_13397518, EPI_ISL_13397536, EPI_ISL_13397662, EPI_ISL_13397697, EPI_ISL_13397869, EPI_ISL_13398070, EPI_ISL_13398139, EPI_ISL_13398227, EPI_ISL_13398238, EPI_ISL_13398339, EPI_ISL_13402528, EPI_ISL_13413986, EPI_ISL_13414142, EPI_ISL_13417247, EPI_ISL_13425186, EPI_ISL_13489963, EPI_ISL_13497111, EPI_ISL_13497137, EPI_ISL_13497302, EPI_ISL_13497405, EPI_ISL_13512619, EPI_ISL_13512627, EPI_ISL_13512799, EPI_ISL_13512883, EPI_ISL_13512896, EPI_ISL_13513667, EPI_ISL_13513756, EPI_ISL_13513832, EPI_ISL_13513846, EPI_ISL_13513853, EPI_ISL_13513888, EPI_ISL_13514810, EPI_ISL_13514826, EPI_ISL_13514849, EPI_ISL_13514859, EPI_ISL_13514864, EPI_ISL_13530950, EPI_ISL_13530962, EPI_ISL_13531011, EPI_ISL_13611907, EPI_ISL_13612525, EPI_ISL_13612590, EPI_ISL_13612710, EPI_ISL_13612720, EPI_ISL_13648026, EPI_ISL_13650903, EPI_ISL_13651431, EPI_ISL_13651462, EPI_ISL_13651465, EPI_ISL_13651713, EPI_ISL_13651717, EPI_ISL_13652597, EPI_ISL_13652640, EPI_ISL_13652672, EPI_ISL_13666083, EPI_ISL_13666084, EPI_ISL_13666085, EPI_ISL_13666086, EPI_ISL_13762875, EPI_ISL_13762887, EPI_ISL_13765584, EPI_ISL_13765735, EPI_ISL_13765946, EPI_ISL_13765959, EPI_ISL_13765983, EPI_ISL_13766020, EPI_ISL_13830278, EPI_ISL_13843106, EPI_ISL_13843223, EPI_ISL_13843289, EPI_ISL_13843396, EPI_ISL_13843424, EPI_ISL_13843426, EPI_ISL_13843500, EPI_ISL_13843566, EPI_ISL_13843730, EPI_ISL_13843752, EPI_ISL_13843764, EPI_ISL_13843817, EPI_ISL_13843818, EPI_ISL_13843819, EPI_ISL_13843825, EPI_ISL_13844523, EPI_ISL_13844524, EPI_ISL_13900940, EPI_ISL_13900943, EPI_ISL_13900977, EPI_ISL_13901001, EPI_ISL_13901062, EPI_ISL_13901124, EPI_ISL_13901156, EPI_ISL_13901988, EPI_ISL_13964088, EPI_ISL_13964089, EPI_ISL_13964094, EPI_ISL_13964095, EPI_ISL_13964096, EPI_ISL_13964097, EPI_ISL_13964099, EPI_ISL_13964100, EPI_ISL_13964102, EPI_ISL_13964104, EPI_ISL_13964105, EPI_ISL_13964107, EPI_ISL_13964108, EPI_ISL_13964110, EPI_ISL_13964114, EPI_ISL_13964116, EPI_ISL_13985921, EPI_ISL_14003999, EPI_ISL_14004000, EPI_ISL_14004001, EPI_ISL_14004021, EPI_ISL_14004226, EPI_ISL_14017658, EPI_ISL_14017670, EPI_ISL_14017678, EPI_ISL_14017849, EPI_ISL_14017871, EPI_ISL_14043655, EPI_ISL_14043671, EPI_ISL_14043676, EPI_ISL_14043712, EPI_ISL_14043787, EPI_ISL_14043791, EPI_ISL_14044224, EPI_ISL_14044330, EPI_ISL_14044342, EPI_ISL_14044350, EPI_ISL_14044399, EPI_ISL_14044403, EPI_ISL_14044405, EPI_ISL_14044424, EPI_ISL_14044451, EPI_ISL_14044471, EPI_ISL_14044484, EPI_ISL_14044513, EPI_ISL_14044514, EPI_ISL_14044515, EPI_ISL_14044539, EPI_ISL_14044549, EPI_ISL_14044578, EPI_ISL_14044646, EPI_ISL_14044665, EPI_ISL_14044728, EPI_ISL_14044737, EPI_ISL_14047255, EPI_ISL_14047292, EPI_ISL_14047522, EPI_ISL_14047523, EPI_ISL_14047561, EPI_ISL_14047583, EPI_ISL_14081886, EPI_ISL_14081887, EPI_ISL_14081960, EPI_ISL_14081998, EPI_ISL_14082048, EPI_ISL_14082201, EPI_ISL_14082220, EPI_ISL_14082231, EPI_ISL_14082291, EPI_ISL_14082331, EPI_ISL_14082355, EPI_ISL_14082359, EPI_ISL_14082390, EPI_ISL_14089073, EPI_ISL_14089083, EPI_ISL_14089102, EPI_ISL_14089127, EPI_ISL_14089192, EPI_ISL_14089298, EPI_ISL_14089520, EPI_ISL_14094179, EPI_ISL_14094265, EPI_ISL_14094270, EPI_ISL_14094300, EPI_ISL_14094345, EPI_ISL_14094369, EPI_ISL_14094389, EPI_ISL_14095650, EPI_ISL_14095652, EPI_ISL_14095691, EPI_ISL_14095711, EPI_ISL_14095860, EPI_ISL_14107696, EPI_ISL_14107910, EPI_ISL_14107948, EPI_ISL_14108009, EPI_ISL_14108593, EPI_ISL_14108867, EPI_ISL_14109181, EPI_ISL_14109891, EPI_ISL_14110972, EPI_ISL_14111010, EPI_ISL_14111854, EPI_ISL_14112014, EPI_ISL_14112655, EPI_ISL_14112776, EPI_ISL_14112782, EPI_ISL_14112803, EPI_ISL_14112804, EPI_ISL_14113015, EPI_ISL_14113018, EPI_ISL_14113029, EPI_ISL_14113036, EPI_ISL_14113083, EPI_ISL_14114018, EPI_ISL_14114633, EPI_ISL_14114662, EPI_ISL_14114858, EPI_ISL_14114887, EPI_ISL_14115226, EPI_ISL_14115236, EPI_ISL_14115291, EPI_ISL_14115292, EPI_ISL_14115299, EPI_ISL_14115300, EPI_ISL_14116659, EPI_ISL_14116700, EPI_ISL_14116837, EPI_ISL_14117284, EPI_ISL_14117301, EPI_ISL_14117307, EPI_ISL_14117507, EPI_ISL_14117518, EPI_ISL_14117856, EPI_ISL_14118070, EPI_ISL_14118164, EPI_ISL_14118402, EPI_ISL_14118552, EPI_ISL_14118626, EPI_ISL_14118843, EPI_ISL_14118874, EPI_ISL_14119085, EPI_ISL_14119766, EPI_ISL_14119812, EPI_ISL_14119813, EPI_ISL_14119814, EPI_ISL_14120091, EPI_ISL_14120315, EPI_ISL_14120346, EPI_ISL_14120456, EPI_ISL_14120491, EPI_ISL_14120669, EPI_ISL_14120745, EPI_ISL_14120749, EPI_ISL_14120750, EPI_ISL_14120757, EPI_ISL_14120760, EPI_ISL_14120762, EPI_ISL_14120771, EPI_ISL_14120811, EPI_ISL_14120832, EPI_ISL_14121049, EPI_ISL_14121130, EPI_ISL_14121211, EPI_ISL_14121326, EPI_ISL_14121834, EPI_ISL_14121837, EPI_ISL_14121838, EPI_ISL_14121839, EPI_ISL_14121854, EPI_ISL_14121862, EPI_ISL_14121864, EPI_ISL_14121865, EPI_ISL_14121866, EPI_ISL_14121867, EPI_ISL_14123948, EPI_ISL_14124049, EPI_ISL_14124050, EPI_ISL_14124815, EPI_ISL_14124937, EPI_ISL_14125139, EPI_ISL_14125142, EPI_ISL_14125270, EPI_ISL_14125329, EPI_ISL_14125348, EPI_ISL_14125623, EPI_ISL_14125643, EPI_ISL_14125657, EPI_ISL_14125688, EPI_ISL_14125691, EPI_ISL_14125692, EPI_ISL_14125695, EPI_ISL_14125856, EPI_ISL_14125857, EPI_ISL_14125859, EPI_ISL_14125860, EPI_ISL_14125862, EPI_ISL_14125863, EPI_ISL_14125864, EPI_ISL_14125964, EPI_ISL_14126061, EPI_ISL_14126199, EPI_ISL_14126201, EPI_ISL_14126303, EPI_ISL_14126434, EPI_ISL_14126435, EPI_ISL_14126438, EPI_ISL_14126439, EPI_ISL_14126440, EPI_ISL_14126441, EPI_ISL_14126475, EPI_ISL_14126476, EPI_ISL_14126477, EPI_ISL_14126480, EPI_ISL_14126694, EPI_ISL_14126763, EPI_ISL_14126855, EPI_ISL_14126877, EPI_ISL_14126889, EPI_ISL_14127361, EPI_ISL_14127505, EPI_ISL_14127523, EPI_ISL_14127989, EPI_ISL_14127991, EPI_ISL_14128045, EPI_ISL_14128071, EPI_ISL_14128364, EPI_ISL_14128503, EPI_ISL_14128537, EPI_ISL_14128595, EPI_ISL_14128867, EPI_ISL_14128871, EPI_ISL_14129016, EPI_ISL_14129031, EPI_ISL_14129056, EPI_ISL_14129094, EPI_ISL_14129267, EPI_ISL_14129320, EPI_ISL_14129336, EPI_ISL_14129394, EPI_ISL_14129410, EPI_ISL_14129412, EPI_ISL_14129516, EPI_ISL_14129801, EPI_ISL_14129866, EPI_ISL_14130085, EPI_ISL_14130086, EPI_ISL_14130111, EPI_ISL_14130190, EPI_ISL_14130262, EPI_ISL_14130266, EPI_ISL_14130358, EPI_ISL_14130378, EPI_ISL_14130391, EPI_ISL_14130448, EPI_ISL_14130473, EPI_ISL_14130527, EPI_ISL_14130538, EPI_ISL_14130640, EPI_ISL_14131039, EPI_ISL_14131273, EPI_ISL_14131556, EPI_ISL_14131557, EPI_ISL_14131559, EPI_ISL_14131560, EPI_ISL_14131564, EPI_ISL_14131570, EPI_ISL_14131579, EPI_ISL_14131584, EPI_ISL_14131589, EPI_ISL_14131594, EPI_ISL_14131595, EPI_ISL_14131604, EPI_ISL_14131613, EPI_ISL_14133617, EPI_ISL_14134860, EPI_ISL_14137224, EPI_ISL_14137238, EPI_ISL_14137517, EPI_ISL_14137585, EPI_ISL_14137885, EPI_ISL_14137997, EPI_ISL_14137998, EPI_ISL_14138074, EPI_ISL_14138081, EPI_ISL_14138096, EPI_ISL_14138109, EPI_ISL_14138204, EPI_ISL_14138214, EPI_ISL_14138436, EPI_ISL_14138442, EPI_ISL_14138523, EPI_ISL_14138533, EPI_ISL_14138752, EPI_ISL_14139663, EPI_ISL_14139664, EPI_ISL_14139665, EPI_ISL_14139668, EPI_ISL_14139719, EPI_ISL_14139766, EPI_ISL_14139821, EPI_ISL_14139824, EPI_ISL_14139851, EPI_ISL_14139852, EPI_ISL_14139875, EPI_ISL_14139876, EPI_ISL_14139877, EPI_ISL_14139879, EPI_ISL_14139880, EPI_ISL_14139881, EPI_ISL_14139908, EPI_ISL_14139933, EPI_ISL_14139944, EPI_ISL_14139987, EPI_ISL_14140001, EPI_ISL_14140295, EPI_ISL_14140310, EPI_ISL_14140549, EPI_ISL_14140563, EPI_ISL_14140859, EPI_ISL_14140870, EPI_ISL_14141030, EPI_ISL_14141186, EPI_ISL_14141211, EPI_ISL_14141330, EPI_ISL_14141403, EPI_ISL_14141407, EPI_ISL_14141412, EPI_ISL_14141418, EPI_ISL_14141582, EPI_ISL_14141583, EPI_ISL_14141838, EPI_ISL_14141839, EPI_ISL_14141960, EPI_ISL_14142031, EPI_ISL_14142165, EPI_ISL_14142184, EPI_ISL_14142200, EPI_ISL_14142228, EPI_ISL_14142311, EPI_ISL_14142392, EPI_ISL_14161105, EPI_ISL_14161112, EPI_ISL_14207357, EPI_ISL_14207389, EPI_ISL_14207390, EPI_ISL_14207422, EPI_ISL_14207426, EPI_ISL_14207840, EPI_ISL_14207891, EPI_ISL_14207931, EPI_ISL_14210968, EPI_ISL_14210992, EPI_ISL_14211013, EPI_ISL_14211137, EPI_ISL_14211183, EPI_ISL_14211208, EPI_ISL_14214796, EPI_ISL_14214842, EPI_ISL_14214847, EPI_ISL_14224942, EPI_ISL_14224965, EPI_ISL_14225002, EPI_ISL_14259736, EPI_ISL_14259748, EPI_ISL_14338521, EPI_ISL_14338538, EPI_ISL_14338687, EPI_ISL_14339729, EPI_ISL_14340236, EPI_ISL_14340499, EPI_ISL_14340574, EPI_ISL_14340668, EPI_ISL_14340675, EPI_ISL_14340709, EPI_ISL_14341126, EPI_ISL_14341132, EPI_ISL_14342002, EPI_ISL_14342035, EPI_ISL_14342057, EPI_ISL_14342210, EPI_ISL_14342470, EPI_ISL_14342475, EPI_ISL_14342476, EPI_ISL_14342665, EPI_ISL_14342884, EPI_ISL_14342982, EPI_ISL_14342983, EPI_ISL_14342994, EPI_ISL_14343008, EPI_ISL_14343072, EPI_ISL_14343165, EPI_ISL_14343216, EPI_ISL_14343310, EPI_ISL_14343312, EPI_ISL_14343442, EPI_ISL_14343468, EPI_ISL_14343531, EPI_ISL_14343550, EPI_ISL_14343622, EPI_ISL_14343731, EPI_ISL_14343735, EPI_ISL_14343757, EPI_ISL_14343776, EPI_ISL_14343785, EPI_ISL_14343906, EPI_ISL_14344240, EPI_ISL_14344435, EPI_ISL_14344731, EPI_ISL_14344780, EPI_ISL_14344781, EPI_ISL_14345042, EPI_ISL_14345069, EPI_ISL_14345171, EPI_ISL_14345180, EPI_ISL_14345257, EPI_ISL_14345449, EPI_ISL_14345914, EPI_ISL_14345920, EPI_ISL_14346046, EPI_ISL_14346269, EPI_ISL_14346446, EPI_ISL_14346527, EPI_ISL_14346547, EPI_ISL_14346754, EPI_ISL_14346755, EPI_ISL_14346879, EPI_ISL_14346922, EPI_ISL_14347470, EPI_ISL_14347470, EPI_ISL_14347487, EPI_ISL_14347493, EPI_ISL_14347498, EPI_ISL_14347506, EPI_ISL_14347753, EPI_ISL_14348018, EPI_ISL_14348080, EPI_ISL_14348259, EPI_ISL_14348370, EPI_ISL_14348504, EPI_ISL_14349002, EPI_ISL_14349082, EPI_ISL_14349083, EPI_ISL_14349766, EPI_ISL_14349983, EPI_ISL_14350045, EPI_ISL_14350374, EPI_ISL_14350552, EPI_ISL_14350859, EPI_ISL_14350902, EPI_ISL_14350906, EPI_ISL_14351016, EPI_ISL_14351090, EPI_ISL_14351154, EPI_ISL_14351432, EPI_ISL_14351516, EPI_ISL_14352725, EPI_ISL_14352758, EPI_ISL_14352860, EPI_ISL_14353083, EPI_ISL_14353089, EPI_ISL_14353166, EPI_ISL_14353231, EPI_ISL_14356519, EPI_ISL_14495248, EPI_ISL_14507979, EPI_ISL_14508015, EPI_ISL_14508680, EPI_ISL_14508841, EPI_ISL_14510061, EPI_ISL_14510191, EPI_ISL_14510197, EPI_ISL_14510319, EPI_ISL_14510603, EPI_ISL_14510702, EPI_ISL_14510730, EPI_ISL_14510731, EPI_ISL_14510737, EPI_ISL_14510742, EPI_ISL_14510747, EPI_ISL_14510786, EPI_ISL_14510791, EPI_ISL_14513510, EPI_ISL_14513514, EPI_ISL_14514827, EPI_ISL_14514841, EPI_ISL_14514988, EPI_ISL_14515078, EPI_ISL_14515082, EPI_ISL_14517598, EPI_ISL_14517602, EPI_ISL_14517612, EPI_ISL_14517623, EPI_ISL_14517645, EPI_ISL_14517656, EPI_ISL_14517659, EPI_ISL_14517662, EPI_ISL_14518497, EPI_ISL_14518926, EPI_ISL_14519114, EPI_ISL_14519127, EPI_ISL_14519164, EPI_ISL_14519296, EPI_ISL_14519588, EPI_ISL_14519605, EPI_ISL_14519622, EPI_ISL_14519876, EPI_ISL_14520086, EPI_ISL_14520244, EPI_ISL_14520246, EPI_ISL_14520274, EPI_ISL_14524091, EPI_ISL_14524169, EPI_ISL_14525194, EPI_ISL_14534753, EPI_ISL_14536004, EPI_ISL_14536010, EPI_ISL_14536137, EPI_ISL_14536156, EPI_ISL_14540291, EPI_ISL_14540324, EPI_ISL_14540331, EPI_ISL_14540440, EPI_ISL_14540443, EPI_ISL_14540453, EPI_ISL_14540531, EPI_ISL_14540532, EPI_ISL_14540924, EPI_ISL_14540929, EPI_ISL_14540931, EPI_ISL_14546982, EPI_ISL_14548007, EPI_ISL_14548037, EPI_ISL_14548232, EPI_ISL_14548281, EPI_ISL_14548403, EPI_ISL_14548428, EPI_ISL_14548612, EPI_ISL_14548949, EPI_ISL_14549195, EPI_ISL_14549398

**Comment by silcn** [comment]
This isn't quite "plain BA.2 with S:L452M", which would be BA.2.56. It also has A28877T+G28878C. It's helpful to give the full list of defining mutations when very common mutations are involved, so that it's easy to distinguish one lineage from another. Lots of the sequences picked up by your cov-spectrum query do not have A28877T+G28878C. Here is a better query, though it still probably pulls in a few unrelated sequences with the same mutations: [https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AL452M&nucMutations=A28877T%2CG28878C%2C22792C&pangoLineage=BA.2*&aaMutations1=S%3AL452M&pangoLineage1=BA.2*&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AL452M&nucMutations=A28877T%2CG28878C%2C22792C&pangoLineage=BA.2*&aaMutations1=S%3AL452M&pangoLineage1=BA.2*&)

It's not clear to me whether this is actually a sublineage of BA.2.56 or not. A28877T+G28878C, despite being a silent double mutation, is highly homoplasic, as can be seen from a cov-spectrum query of [just those two mutations](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=A28877T%2CG28878C&). Usher doesn't know this and so it groups BA.2+A28877T+G28878C with and without 22792T together on the same branch of BA.2+22792T, when it's much more likely that BA.2+A28877T+G28878C with 22792C and BA.2+A28877T+G28878C with 22792T arose independently. 

Usher therefore thinks this S:L452M lineage arose as C22792T, then A28877T+G28878C, then reversion of C22792T, then S:L452M. I don't think that the mutation/reversion at 22792 actually happened. In other words, this lineage is just BA.2 with two highly homoplasic mutations: S:L452M and A28877T+G28878C. I don't think we can tell which happened first; if it was S:L452M, then this is a sublineage of BA.2.56.

@AngieHinrichs would it be possible for Usher to count A28877T+G28878C as just one mutation for parsimony purposes? It's pretty rare for one to occur without the other.

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs would it be possible for Usher to count A28877T+G28878C as just one mutation for parsimony purposes? It's pretty rare for one to occur without the other.

Strictly speaking, not with usher -- but I could mask one site so that only the other site is visible to usher.  

Now that you mention it, wow yeah, the 28877+28878 combo is super homoplasic.  Here's a taxonium view of B.1.1 with blue circles around nodes with 28877 and at least 10 samples and green circles around 28878 and at least 10:
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/186983/186265833-bc51a966-9b40-4195-8ad0-c2bf8cf4cd84.png">
They're usually on the same node (concentric) or on adjacent nodes.  Even requiring at least 1000 samples, B.1.1 still has three same-node and four adjacent-node cases:
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/186983/186266305-fdc40b14-9938-41ad-8a33-5c5ee606dbdb.png">

And if I zoom in to view the BA.2 > C22792T > A28877T > G28878C branch with ~8000 samples, and enable coloring by pangolin/pangoLEARN-assigned lineage, it shows some flashes of color for BA.2.* lineages, and if I zoom into those, I see
* a branch with reversion on 22792 and T16342C like BA.2.10, that has a branch with G23955A like BA.2.10.1
* a branch with reversion on 22792 and C12789T like BA.2.1
* a branch with A23767G > C22916A like BA.2.13
* a branch with C17502T > T14171C like BA.2.81
* a branch with C25624T like BA.2.9

-- what are the chances that A28877T+G28878C happened and then lots of BA.2.*-defining mutations reoccurred?  When I see mini-BA.2 on some branch like that, I'm pretty sure the tree is wrong and I probably should just mask the sites that lead to that branch.

So I am leaning towards masking both 28877 and 28878.  Any objections?

**Comment by agamedilab** [comment]
@silcn @AngieHinrichs many thanks for your comment! I did not notice that the lineage also carries A28877T+G28878C. If masked would the lineage above end up as BA.2.56?

I now noticed that the lineage proposed in https://github.com/cov-lineages/pango-designation/issues/983 apparently also carries  A28877T+G28878C. However given the amount of convergence these are probably not good defining mutations.

**Comment by AngieHinrichs** [comment]
> I did not notice that the lineage also carries A28877T+G28878C. If masked would the lineage above end up as BA.2.56?

@agamedilab Yes, I believe it will.  I haven't masked 28877 and 28878 yet but probably will unless someone objects soon.

**Comment by agamedilab** [comment]
many thanks @AngieHinrichs. I guess i can close this issue soon then. I will let it open until it is clear that nobody objects...

**Comment by AngieHinrichs** [comment]
I masked 28877 and 28878 in the BA.2 branch starting with the 2022-08-30 tree. These sequences have been moved (by optimizing after masking) to BA.2.56 as expected, so I'll go ahead and close this issue, thanks @agamedilab.

**Comment by agamedilab** [comment]
fyi now it looks like a BA.2.56 subclade with N:S202T in usher.

![Bild1](https://user-images.githubusercontent.com/102166254/187863996-7bfe9f06-5d91-4ca3-8ec0-4b170d178240.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22896_5e370.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A28877T,G28878C

**Comment by agamedilab** [comment]
The lineage proposed in https://github.com/cov-lineages/pango-designation/issues/983 apparently also carries A28877T+G28878C so when i run usher with a few testsamples it looks like this:

![grafik](https://user-images.githubusercontent.com/102166254/187865425-739f21c1-700d-4103-a8f6-00da1828de96.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2306a_5e560.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A23513G

**Comment by AngieHinrichs** [comment]
> fyi now it looks like a BA.2.56 subclade with N:S202T in usher.

Ah... sorry about that.  The web interface masks out [Problematic Sites](https://github.com/W-L/ProblematicSites_SARS-CoV2) that are masked in all sequences before running usher, but it does not mask out the sites that are masked only in specific branches like BA.2 (that happens after placement in the daily build).  So they will appear as brand new mutations in the sequences unfortunately, and will cause them to cluster like that.  That's not good.  I suppose I could mask the BA.2-specific sites in all incoming sequences, which would most likely be BA.2-BA.5 nowadays, and hope that nobody uploads any P.1 sequences where the absence of 28877 and 28878 would cause the same problem.  :)
