### ISSUE TITLE
BA.4.1 sublineage with S:I1221T and S:K444T (36 seqs) circulating in France, likely arisen in Reunion/Mayotte

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#989]
Proposed sublineage of BA.4.1
with:
G11722A, A15861G 
then 
S:I1221T
then
S:K444T
Tree:
![Schermata 2022-08-24 alle 01 17 58](https://user-images.githubusercontent.com/87669813/186282457-ff45e781-d647-44a9-852a-5c8b45014b66.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29a2c_55d040.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:G11722A,A15861G

Although this was never sequenced, in the shape proposed here , in South Africa we have 6 sequences in May without S:444T from South Africa hinting to an early circulation there.

First sequence: SouthKorea/KDCA87007/2022|EPI_ISL_13738804|2022-06-16
Nr of sequences: 
28 on Usher , 
27 on gisaid with  this query Spike_K444T, Spike_I1221T
22 on CovSpectrum: [Here](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A444T%2CS%3AI1221T&nextcladePangoLineage=BA.4.1*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&)
List of Sequences:
EPI_ISL_14304864
EPI_ISL_14473123
EPI_ISL_14526959
EPI_ISL_14130982
EPI_ISL_13838182
EPI_ISL_13838527
EPI_ISL_13874805
EPI_ISL_14472487
EPI_ISL_14170840
EPI_ISL_14516345
EPI_ISL_14416664
EPI_ISL_13838530
EPI_ISL_13738804
EPI_ISL_14528543
EPI_ISL_14130860
EPI_ISL_13732798
EPI_ISL_14130892
EPI_ISL_14518607
EPI_ISL_14131020

Countries: Last samples collected after 1st August point to a sustained transmission at least  in France and Germany 
Earlier Reunion island had 6 samples of this lineage last one collected on 25th of July.

**Comment by FedeGueli** [comment]
One more sequence from Germany. It seems quite slow, i ll leave this open for another week before closing.

**Comment by FedeGueli** [comment]
4 new sequences from France collected after 15th of August and from three different regions of France: 
Indre-et-Loire 1 ,
Auvergne-Rhone-Alpes 2 ,
Provence-Alpes-Cote d'Azur 1

**Comment by FedeGueli** [comment]
2 more sequences : Italy EPI_ISL_14786140 , France EPI_ISL_14796703

**Comment by FedeGueli** [comment]
One more sequence from France

**Comment by FedeGueli** [comment]
39 Viruses on Gisaid last from Mayotte, Usa , France (Loire)  👍 
Interesting this last Mayotte sequence (EPI_ISL_14860824) is the very first one back in June confirming the area of emergence of this lineage between Mayotte and Reunion.

**Comment by corneliusroemer** [comment]
Bit small and slow growth since opening - let's close this for now and reopen if something interesting happens in it.

**Comment by FedeGueli** [comment]
49 sequences . 15/49 are from Reunion island.
