### ISSUE TITLE
Most B.6.7 representatives have A24389C and G24390C, associated with untrimmed nanopore adapter seq

### ISSUE THREAD

**Issue by AngieHinrichs** [cov-lineages/pango-designation#99]
Of the 55 representative sequences for B.6.7, these are the counts of mutations observed in at least 20 of the sequences:
```
count   mutation
45      C241T
25      C1059T
47      C3037T
54      C14408T
54      A23403G
51      A24389C
51      G24390C
23      G25563T
```
A bit less than half have C1059T + G25563T (Nextstrain 20C), a bit more than half do not.  What seems to tie most of them together (beyond B.1 S:D614G) are A24389C and G24390C, which have been [flagged as untrimmed nanopore adapter artefacts](https://virological.org/t/issues-with-sars-cov-2-sequencing-data/473/8).   A24389C and G24390C were observed in 51 out of 55 representatives:

* 47 TX-HMH-MCoV sequences
* 2 India/WB-IICB- sequences (-009 and -015)
* 1 Ecuador sequence (Ecuador/178620/2020)
* 1 Beijing sequence (Beijing/DT-travelNO01/2020)

I checked GISAID to confirm that the India, Ecuador and Beijing sequences listed nanopore as the sequencing technology, and every TX-HMH I've checked in the past has been nanopore.  Of the 4 that don't have A24389C and G24390C (also all nanopore):

* India/DL-NCDC-4476/2020, India/MP-NCDC-4877/2020 and India/MP-NCDC-4878/2020 have ambiguous bases at 24389-90
* India/MP-NCDC-4876/2020 is the odd one out with reference bases at 24389-90

When 24389 and 24390 are masked, the sequences place in many different clusters across the global tree.  So I think B.6.7 is not a real lineage.

**Comment by AngieHinrichs** [comment]
@aineniamh @chrisruis I will remove B.6.7 at the end of the week unless one of you (or anyone really 😄) wants to double-check first.

**Comment by aineniamh** [comment]
Have removed the lineage in commit [d2ade63](https://github.com/cov-lineages/pango-designation/commit/d2ade6381d646ea608a6a9f46465cb6303f54b80)
