### ISSUE TITLE
BA.2.75.1 sublineage with S:L249M, ins22119:AACATTAGG (3 seq. India, Austria)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#990]
Proposal for a sublineage of BA.2.75.1
Earliest sequence: 07.2022 (India)
Countries detected: India, Austria

Defining mutation:
T22037A = S:L249M
C7764T = ORF1a:S2500F
C13424A = ORF1a:R4387S
ins22119: AACATTAGG = S:185:LTL

GISAID query: Spike_L249M, Spike_D574V

This subvariant is defined by S:L249M, ORF1a:S2500F, ORF1a:R4387S and ins22119: AACATTAGG = S:185:LTL and was first detected in India. Expansion into Autria wit todays GISAID upload. One sequence with S:L249M but lacking ORF1a:S2500F, ORF1a:R4387S and ins22119: AACATTAGG was also detected in Switzerland. 3 seq. on usher as of 24.08.22

![ins](https://user-images.githubusercontent.com/102166254/186376292-c4a52f8f-b801-4544-b074-c7a202f73b00.png)
![grafik](https://user-images.githubusercontent.com/102166254/186376569-2ea75270-85d0-47e5-8609-e3e78b8fa7e5.png)

![grafik](https://user-images.githubusercontent.com/102166254/186377064-fe3895f1-d2e6-4b98-bec7-cfddc24749e4.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3349a_5d4f00.json?branchLabel=aa%20mutations&c=userOrOld

Covspectrum query:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AL249M%2CORF1a%3AS2500F%2CORF1a%3AR4387S&pangoLineage=BA.2.75*&

EPI_ISL_14327119
EPI_ISL_14601643
EPI_ISL_14601650

**Comment by chrisruis** [comment]
We need new issues to either have an epidemiological event or be close to exhibiting an epidemiological event before opening. Will therefore close this one for now
