### ISSUE TITLE
BA.5.2 + Orf1b:1050N sublineage with and S:R346T orf1b:V1538L with high prevalence in Cambodia 303 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#992]
While monitoring issue #870 that brought to the designation of BA.5.2.6 
i noticed sequences accumulating from Israel with Orf1b:V1538L . 
After having flagged it to ILVR (Israel Variant Radar) team, @shay671 ,
Here i want to propose it for designation:

**EDITED (27/09/2022)**
BA.5.2*+Orf1b:T1050N +Orf1b:V1538L (G18079T ) + G23587A + S:346T
Route from root :  > C27513T > C27012T > G12310A > C16616A > G18079T > G23587A > G22599C 

**Edited**
Here the Usher tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_396b7_2c5d50.json?branchLabel=aa%20mut
![Schermata 2022-09-27 alle 12 25 02](https://user-images.githubusercontent.com/87669813/192501796-a714c889-047b-4845-bab6-85474a9cabe9.png)
ations&c=pango_lineage_usher&label=nuc%20mutations:G23587A

(**EDITED**)

Nr of sequences: 39 (23 out of 39 from Israel)

Countries: first sequenced in Cambodia  (Cambodia/2213541/2022|EPI_ISL_13727528|2022-06-30)
then Israel Ireland Canada Russia Usa

List of sequences:
EPI_ISL_13727527
EPI_ISL_13727528
EPI_ISL_13867310
EPI_ISL_13932235
EPI_ISL_13960468
EPI_ISL_14036858
EPI_ISL_14036909
EPI_ISL_14168240
EPI_ISL_14271450
EPI_ISL_14287348
EPI_ISL_14322758
EPI_ISL_14322768
EPI_ISL_14323071
EPI_ISL_14327765
EPI_ISL_14337061
EPI_ISL_14386199
EPI_ISL_14425398
EPI_ISL_14440003
EPI_ISL_14457248
EPI_ISL_14457584
EPI_ISL_14457593
EPI_ISL_14457636
EPI_ISL_14457714
EPI_ISL_14458467
EPI_ISL_14468027
EPI_ISL_14468161
EPI_ISL_14468891
EPI_ISL_14476907
EPI_ISL_14497153
EPI_ISL_14512653
EPI_ISL_14529135
EPI_ISL_14568165
EPI_ISL_14568339
EPI_ISL_14568503

Gisaid query: Spike_R346T,NSP14_v14L,NSP13_T127N

CovSpectrum: 113 seqs as 27/09/2022 (**edited**)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1b%3AT1050N%2CS%3A346T%2COrf1b%3AV1538L&nucMutations=G23587A&nextcladePangoLineage=BA.5.2*&

Too early to be certain if it has a growth advantage vs parental lineage but if it will go on spreading in Israel or elsewhere the geographical association of a specific mutation to the start of the outbreak into a specific country could be of interest too beyond its advantage .

**Comment by FedeGueli** [comment]
Edited:
![Schermata 2022-08-27 alle 16 27 07](https://user-images.githubusercontent.com/87669813/187034584-505db348-1507-4714-a9db-d8c2b8db8b9f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_4175b_a261b0.json?branchLabel=aa%20mutations&c=gt-nuc_23587&label=nuc%20mutations:C27012T

@corneliusroemer @AngieHinrichs @chrisruis @InfrPopGen @silcn

  i had the doubt that this lineage was not a sublineage of BA.5.2.6 but evolved independently from BA.5.2+ orf1b:1050N (82K seqs)+27012T (66k seqs)+ orf1b:V1538L(331seqs) 

So looking deeper i found that the real defining mutation of this sublineage is G23587A.

Sincerely i cant say if S:346T was independently acquired by BA.5.2+ orf1b:1050N (82K seqs)+27012T (66k seqs)+ orf1b:V1538L(331seqs) + G23587A 834seqs)

or it is BA.5.2.6 sublineage : 
C27889T > A28330G > C1627T > G12310A > C16616A > C27513T > C27012T > G22599C > G18079T, G23587A

**Comment by FedeGueli** [comment]
42seqs as toay
![Schermata 2022-08-28 alle 22 58 47](https://user-images.githubusercontent.com/87669813/187094278-9d3243a7-6299-4f2d-924c-e7a8f00885ed.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_17590_bd5270.json?branchLabel=aa%20mutations&label=nuc%20mutations:G18079T,G23587A

**Comment by FedeGueli** [comment]
47 sequences in 9 different countries on Usher as today:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36824_e85640.json?label=nuc%20mutations:G18079T,G23587A

![Schermata 2022-08-31 alle 00 19 37](https://user-images.githubusercontent.com/87669813/187553729-8ffd9212-f1ad-4b4f-b431-97301eed1aef.png)

**Comment by FedeGueli** [comment]
49 sequences as today: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33f38_f95c10.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G18079T,G23587A

**Comment by FedeGueli** [comment]
One more from MA,US

**Comment by FedeGueli** [comment]
Four samples uploaded yesterday from US: Minnesota (2), Texas, Ohio

**Comment by FedeGueli** [comment]
61 sequences. Among the newly uploded samples one from Singapore , local case, one from South Korea , local case adn another from Cambodia (Sampled at the arrival in South Korea) : EPI_ISL_14856348. This llast one confirms that likely this sublimeage emerged in Cambodia where the first sequence of it was sampled. 
The rest are from different states of US.

**Comment by FedeGueli** [comment]
66 viruses last 5 sequences: India, Australia, Usa, France , Denmark

**Comment by FedeGueli** [comment]
94 viruses as today:
big upload of sequences in the last days from.many different countries bit i want yo.highligjt that:
4/4 of the South Korean samples uploaded today are related with travel from Cambodia,
2 more sequences have been sampled in Cambodia both from September out of 19 total collected after 1st of September.

This suggests to me a very high prevalence there and a potential growth advantage versus ba.5 or other lineages that makes sense with the fact first samples of this proposed lineage were from Cambodia.

@corneliusroemer @InfrPopGen

**Comment by corneliusroemer** [comment]
I"m confused by these statements. Can you clarify @FedeGueli ?

>i had the doubt that this lineage was not a sublineage of BA.5.2.6 but evolved independently from BA.5.2+ orf1b:1050N (82K seqs)+27012T (66k seqs)+ orf1b:V1538L(331seqs)

>So looking deeper i found that the real defining mutation of this sublineage is G23587A.

>Sincerely i cant say if S:346T was independently acquired by BA.5.2+ orf1b:1050N (82K seqs)+27012T (66k seqs)+ orf1b:V1538L(331seqs) + G23587A 834seqs)

>or it is BA.5.2.6 sublineage :
C27889T > A28330G > C1627T > G12310A > C16616A > C27513T > C27012T > G22599C > G18079T, G23587A

>@shay671 what do you think?

**Comment by corneliusroemer** [comment]
This looks much like a child of BA.5.2.6 - I'd treat it as such. It could have acquired S:346T on top of the other mutations but there are not many of these non-346T around - they are more likely to just miss the 346T due to drop out?

It makes up about 15% of BA.5.2.6. One can add this as BA.5.2.6.1 - but I don't think it's high priority being not that fast growing and has only 100 sequences.

Let's see how this develops.

**Comment by FedeGueli** [comment]
@corneliusroemer to clarify my reasoning on this lineage origin:
if u look.at Gisaid with NSP14_v14L,NSP13_T127N query you will find 707 sequences and well localized between South Korea/ Israel. 
So the logic can tell me that S:346T has beem acquired homoplasically by this sublineage that was circulating in AsIa and interestingly Israel was one of the first country to sequence 
NSP14_v14L,NSP13_T127N,Spike_R346T.

More: the likely origin of this lineage in Cambodia that is quite a blindspot suggests that it coulld be totally possible that this circulatef there for a while (remember your discovery of a strong link between Orf1b:1050N and Indonesia (and Malaysia i am adding).

So rathet to descend from.BA.5.2.6 i think it is an original BA.5.2+Orf1b:1050N sublineage that deserves a designation being highly transmissible as BA.5.2.6 and well localized in a very undersampled area that is worth to be described when possible.

**Comment by FedeGueli** [comment]
122 sequences of which 11 are from Cambodia.

**Comment by corneliusroemer** [comment]
Too small to be worth digging into the tree - if we want to break down BA.5.2 + ORF1b:1050N we should look at big branches not small ones. Otherwise this is a never ending fight.

**Comment by FedeGueli** [comment]
Sorry @corneliusroemer i dont get what you mean this is now 234 sequences and it is circulating very fast in Israel representing around 2% of all viruses collected there after 10th of September. As i warned very early @shay671 that it would have happened.

Please reopen and designate it, it is bigger and faster than the most of last designated lineages

**Comment by FedeGueli** [comment]
if designated it would be around 25Th positions for growth advantage ahead of BA.2.75.5

**Comment by FedeGueli** [comment]
and ps one my message wasnt uploaded but if u look at the main text it was edited a couple days ago, now USher as me thinks that it is not a BA.5.2.6 sublineage . that is the reason why interesting to designate cause it is independently gained S:R346T

**Comment by FedeGueli** [comment]
273 sequences as today on gisaid Spike_R346T,NSP14_v14L,NSP13_T127N

**Comment by FedeGueli** [comment]
303 seqeunces on Usher and growing fast  @corneliusroemer @InfrPopGen this should be designated:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36104_cb8f00.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G22599C
<img width="1123" alt="Schermata 2022-10-05 alle 01 07 38" src="https://user-images.githubusercontent.com/87669813/193946732-74bf0940-70f6-42a4-9fea-06590fb79f1e.png">

A little branch of this one acquired S:T190S . (4 seqs)

**Comment by FedeGueli** [comment]
345 sequences as today of which 18 from Cambodia! @corneliusroemer  i think this should  be designated soon

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.34 with 63 newly designated sequences, and 13 updated designations from BA.5.2.6. Defining mutation G22599C (S:R346T) (following G23587A).
