### ISSUE TITLE
 BE.1.1.1 sublineage with Orf1b:Y264H and  S:N460K ( 28 sequences ) emerged in Nigeria ( 14 seqs )

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#993]
Detected a new potential sublineage of interest of recently designated BE.1.1.1.
Defining mutations : Orf1b:Y264H and S:N460K 
7 sequences Usa Uk Japan 
The one from Japan (EPI_ISL_14632425 )
was intercepted by airport surveillance and has travel history from Egypt via Italy and  Israel to Japan and it is heavily mutated with further spike mutations: S:261D*,S:494P and S:603S.
(* as noted by @ryhisner elsewhere S:G261D is or highly homoplasic mutation or pipeline artifact , it was present in a lot of samples from Japanese airport surveillance yesterday maybe Ryan could explain that  better than me.)
This could suggest circulation and evolution in an undersampled area of Africa likely , due to the fact that the likely origin of BE.1.1.1 lineage is Nigeria)

Gisaid query: NSP12_Y273H,Spike_K444T,Spike_N460K finds 6 out of 7
CovSpectrum: 4 out of 7 [Overview](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A444T%2CS%3A460K%2Corf1b%3AY264H&nextcladePangoLineage=BE.1.1*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&)

tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ba8a_876050.json?c=pango_lineage_usher&label=nuc%20mutations:T14257C
![Schermata 2022-08-26 alle 11 13 15](https://user-images.githubusercontent.com/87669813/186870661-c3e98a77-c1cc-436d-875c-c00cfa438582.png)

List of sequences: 

EPI_ISL_14294806
EPI_ISL_14333750
EPI_ISL_14333754
EPI_ISL_14542445
EPI_ISL_14608324
EPI_ISL_14632425
England/PHEC-YYGIB6T/2022|2022-08-12

 

_Originally posted by @FedeGueli in https://github.com/cov-lineages/pango-designation/issues/931#issuecomment-1228231851_

I decided to open an issue after just 7 sequences for three reason:
1-Convergent evolution at S:460 with BA.2.75
2-Already Sampled in 4 continents  suggesting high or growing prevalence somewhere likely in Africa
3-BE.1.1.1 is the fastest BA.5 sublineage according to our collection on covspectrum :
![Schermata 2022-08-26 alle 11 16 15](https://user-images.githubusercontent.com/87669813/186871317-6c8ba7e5-8d2f-4c00-9a1b-daac17f33bb6.png) 
https://cov-spectrum.org/collections/24
:

**Comment by cvejris** [comment]
I concur that early attention is in place here. The affinity impact of S:N460K is huge, see https://www.biorxiv.org/content/10.1101/2022.08.07.503115v1.full and https://www.biorxiv.org/content/10.1101/2022.07.18.500332v2.full
I would also worry about Orf1b:Y264H. Mutations before position 700 in Orf1b (NSP12; RNA polymerase) are extremely rare among VOC, see https://outbreak.info/compare-lineages?pango=Alpha&pango=Beta&pango=Gamma&pango=Delta&pango=Epsilon&pango=Mu&pango=Iota&pango=Kappa&pango=Lambda&pango=Theta&gene=ORF1b&threshold=75&nthresh=1&sub=false&dark=false
The handful present apparently pose selective advantage, see https://www.biorxiv.org/content/10.1101/2022.01.07.475295v1.full These are P314L (defining for B.1) and G662S (defining for delta, 3x independently in BA.2: BA.2.75, BA.2.10.4 and BJ.1).

**Comment by ryhisner** [comment]
It's possible part of the reason BA.2.75 has been able to pick up immune-evasive mutations so much more quickly than BA.5 is because of its higher ACE2 affinity, mostly due to S:N460K. If N460K has a similar effect in BE.1.1.1, it could allow it to acquire still more mutations to evade vaccine- and infection-induced immunity, a factor which will only increase in importance as more and more people are infected with BA.4/5 and/or vaccinated with BA.1- or BA.5-based vaccines. Given that this one is already widespread geographically—possibly far more than we can currently tell—I think it bears close monitoring and probably a rapid designation if more sequences continue to appear in the next week or two.

**Comment by Mydtlwn** [comment]
![498af082845222cd](https://user-images.githubusercontent.com/74440554/186903982-3f3b929f-3c5b-475c-b541-47d50569b502.jpg)
Actually, I have a question. Is this data correct?

**Comment by Mydtlwn** [comment]
I'm not very good at using this, so I don't know the meaning of this corresponding time.

**Comment by corneliusroemer** [comment]
If you mean the early first date - this is just a normal date error. Happens all the time - probably would be best to scrape that "first date" column from cov-lineages website for that reason or make it more robust (e.g. date of 1% quantile)

**Comment by FedeGueli** [comment]
> I concur that early attention is in place here. The affinity impact of S:N460K is huge, see https://www.biorxiv.org/content/10.1101/2022.08.07.503115v1.full and https://www.biorxiv.org/content/10.1101/2022.07.18.500332v2.full I would also worry about Orf1b:Y264H. Mutations before position 700 in Orf1b (NSP12; RNA polymerase) are extremely rare among VOC, see https://outbreak.info/compare-lineages?pango=Alpha&pango=Beta&pango=Gamma&pango=Delta&pango=Epsilon&pango=Mu&pango=Iota&pango=Kappa&pango=Lambda&pango=Theta&gene=ORF1b&threshold=75&nthresh=1&sub=false&dark=false The handful present apparently pose selective advantage, see https://www.biorxiv.org/content/10.1101/2022.01.07.475295v1.full These are P314L (defining for B.1) and G662S (defining for delta, 3x independently in BA.2: BA.2.75, BA.2.10.4 and BJ.1).

There was ORF1b:K82R in the sibling lineage of Ay.103 that was only partially designated as AY.41 (I opened an issue back months ago) that opened breaches in eastern (balcanic) Europe

https://github.com/cov-lineages/pango-designation/issues/440

**Comment by FedeGueli** [comment]
New sequence from Georgia state - US collected 8/08/22 : EPI_ISL_14675347

**Comment by FedeGueli** [comment]
New sequence from Germany : EPI_ISL_14697838

**Comment by FedeGueli** [comment]
New sequence from Nigeria EPI_ISL_14711977 (where it likely emerged) with 3 additional AA mutations:
ORF1b N1191S, Orf1b:L2523F
N:P364S

**Comment by FedeGueli** [comment]
New Usher tree for them ( @AngieHinrichs ) confirms at least 14 out of 16 sequences are part of this new sublineage:
![Schermata 2022-08-30 alle 01 20 34](https://user-images.githubusercontent.com/87669813/187315369-9954656d-7904-4d89-b23a-5a1755097c90.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f237_d48520.json?label=nuc%20mutations:T14257C

New things on the table:
10 out of 14 sequences from Nigeria cluster together sharing an additional orf1b mutation:  Orf1b:N1191S
1 out of 14 sequences from Nigeria has S:I666V as the other sequence uploaded today from Germany

the two sequence that Usher doesnt place in the S:N460K cluster, one (hCoV-19/Nigeria/NCDC-NR-GL-005829/2022|EPI_ISL_14711966|2022-07-10)  is clearly linked and could be considered basal to this new lineage together with a sequence from Usa (USA/DC-Curative-451803/2022|EPI_ISL_14464964|2022-08-06)

((while the other one (hCoV-19/Nigeria/NCDC-NR-GL-005827/2022|EPI_ISL_14711964|2022-07-10) is placed in a messy BA.5.5/Ba.5.3 part of the tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_3f237_d48520.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C11750T))

**Comment by FedeGueli** [comment]
One more sequence from France : EPI_ISL_14726834 collected on 8/8/22 
this one has S:54F and N:334I  .

To me such a diversity suggests sustained circulation likely in the region where it emerged first.

**Comment by corneliusroemer** [comment]
If we get a few more this should be designated as there's quite some literature on 460K if I'm not mistaken

**Comment by FedeGueli** [comment]
@corneliusroemer two more sequences from Texas uploaded today and collected 7/08 and  21/08:

EPI_ISL_14752457
EPI_ISL_14753714

**Comment by FedeGueli** [comment]
New Usher tree generated:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_285be_f8f870.json?branchLabel=aa%20mutations&label=nuc%20mutations:T14257C
![Schermata 2022-08-31 alle 18 48 35](https://user-images.githubusercontent.com/87669813/187734391-99d88a37-5b9b-40aa-a580-e6b3587f03e2.png)

**Comment by FedeGueli** [comment]
Oh bad news EPI_ISL_14752457 the recent Texas sequence got S:346T @corneliusroemer

**Comment by FedeGueli** [comment]
New sequence new country: Belgium EPI_ISL_14773615 collected on 24/08/2022

**Comment by FedeGueli** [comment]
One more sequence from Oregon, Usa: EPI_ISL_14777488

**Comment by FedeGueli** [comment]
Another one from France EPI_ISL_14778228 collected on 21/08 from the region of 'Hauts de France'

@Simon-LoriereLab this is the second sample from France (the former was EPI_ISL_14726834 from Bretagne)
being BE.1.1.1 already one if not the most BA.5 transmissible lineage i would like to bring this one to your attention that further gained S:N460K (convergently)

**Comment by FedeGueli** [comment]
New Usher tree:

 https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e145_f9d80.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T14257C
![Schermata 2022-09-01 alle 20 32 43](https://user-images.githubusercontent.com/87669813/187987338-c1e0a62e-bd5a-43a7-9be0-00f976d0a875.png)

**Comment by corneliusroemer** [comment]
Yeah this one should definitely be designated. I'll do it when I get round to it unless @InfrPopGen or @aq-sun do it before me. Thanks @FedeGueli good spot!

**Comment by corneliusroemer** [comment]
Designated BQ.1, thanks @FedeGueli

**Comment by FedeGueli** [comment]
Thanks @corneliusroemer for a  fast designation, well deserved in my view. 
Another sample (EPI_ISL_14800035) popped up in Atlanta Georgia US but it is from an asympotamitc volunteer "caught" by surveillance at the international airport.
Metadata says it is linked to France , i will investigate further to understand better how it went.

**Comment by FedeGueli** [comment]
4 new sequences (2 Denmark, 1 England , 1 Belgium) uploaded today

**Comment by FedeGueli** [comment]
2 more sequence from France. 25 in total. 
@corneliusroemer it seems really fast, it would flag this to PH authorities.
@thomaspeacock

**Comment by FedeGueli** [comment]
The "French" branch shares additional mutations:
S:L54F, N:T3342I 
suggesting local circulation or importation from a further undersampeld location with high prevalence.
![Schermata 2022-09-06 alle 10 27 05](https://user-images.githubusercontent.com/87669813/188585851-e63171fb-ffcb-45b3-9892-60e3fee65641.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33496_6fd9e0.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:T14257C

**Comment by FedeGueli** [comment]
9 more samples ( 8 Usa-Texas Missouri Georgia- , 1 Denmark) 
of which:
1 from the S:L54F branch
1 from the S: I666V
1 from the S:A892V

@corneliusroemer @thomaspeacock

**Comment by FedeGueli** [comment]
1 more uploaded now from Connecticut unfortunately it has also S:346T as a sample previously collected in Texas

@corneliusroemer @thomaspeacock

**Comment by FedeGueli** [comment]
Here the new tree:
![Schermata 2022-09-06 alle 22 47 53](https://user-images.githubusercontent.com/87669813/188735063-bded30df-9820-421e-a070-daa2813b0ccb.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42b5b_7abe00.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:T14257C

I see 5 main branches of BQ.1 (hoping this analysis will be useless):

1st the one defined by Orf1b:N1191S well rooted to Nigeria and from where emerged the S:346T sublineage sampled both in Ct,TX in US.
2nd: the orf1a:G94C branch clearly circualting in Texas
3nd : the french/georgian branch defined by S:L54F,Orf1b:V1407I (and N:T334I for the french side)
4th : the S: I666V branch sqmpled both in Africa and Central Europe
5th : with a double Orf1b mutation: Orf1b:T132I, Orf1b:T1540I sampled in Texas.

**Comment by corneliusroemer** [comment]
So here comes a BA.5 that's convergently going in the direction of BA.2.75 - at least in Spike. If the S:346T gets above 5 I'd propose.

**Comment by FedeGueli** [comment]
Agree with you @corneliusroemer ,

7 new sequences : 1 from Canada (with S:I666V) 6 from England uploaded today

**Comment by FedeGueli** [comment]
2 more sequences Austria (with S:E619Q) and Canada

**Comment by FedeGueli** [comment]
3 new sequence Ireland, Luxembourg and Belgium, and bad news EPI_ISL_14863144 has S:346T, collected on 5th of september   @corneliusroemer

**Comment by corneliusroemer** [comment]
@FedeGueli feel free to propose the most "promising" lineages in your view, the 346T sound interesting, definitely something to monitor and designate once it gets above 5 or maybe 10.

**Comment by FedeGueli** [comment]
4 more sequences: Denmark, Rhode Island , Georgia and Canada (intl Airport surveillance from unknown country).
No one with S:R346T luckily.  One with S:L54F 

I noticed that the belgian one i highlighted above beyond S:346T has a reversion at 484 to E that i missed before.

Ok @corneliusroemer i ll wait a bit to have a more clear picture and then i will propose sublineages of it.

**Comment by FedeGueli** [comment]
4 new seqs from Denmark, Uk and 2 from Germany one of them with S:R346T.

Later i ll.propose the S:346T sublineage.
@corneliusroemer

**Comment by corneliusroemer** [comment]
I'll designate the S:R346T straightaway, seeing how fast BQ.1 grows and that the 5 S:R346T are from 5 countries and very recent.

**Comment by corneliusroemer** [comment]
Here's an Usher tree with all sequences (some are duplicated because I uploaded all 66 that the GISAID query found, and they were partially in the tree already):
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/25161793/189422694-c1ecb87f-d867-4ae2-85fe-22e6c775cec8.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8362_b889b0.json?branchLabel=aa%20mutations&label=nuc%20mutations:T22942A

**Comment by corneliusroemer** [comment]
I've added BQ.1.1 on the ORF1b:N1191S branch defined by S:R346T in commit https://github.com/cov-lineages/pango-designation/commit/44c66bcacf04f7af79bab1c218fa84709172a65b

Thanks @FedeGueli

**Comment by FedeGueli** [comment]
Thanks @corneliusroemer great work!

**Comment by FedeGueli** [comment]
Gisaid query for BQ.1.1:Gisaid: Spike_N460K,Spike_K444T,Spike_R346T,Nsp13_N268S

**Comment by FedeGueli** [comment]
Already 7 BQ.1.1 (two newly uploaded and one of them sampled in Japan coming from Nigeria as noted by @ryhisner .) beyond these two there were 9 BQ.1 uploaded 8 from Usa and 1 from Greece.

**Comment by corneliusroemer** [comment]
There are now 12 BQ.1.1 already

**Comment by FedeGueli** [comment]
11 BQ.1.1 uploaded yesterday mostly England, and 2 new countries Belgium and Italy.
3 new samples today from England.
There are already 32 BQ.1.1 viruses on Gisaid.

@corneliusroemer @thomaspeacock it seems really fast.

**Comment by FedeGueli** [comment]
2 danish BQ.1 sequences with a couple of spike mutations: Spike_R190T,Spike_N556K.

@ryhisner apotteda couple of BQ.1 with S:T444M T > M that is to be monitored. I suggest to use this modified query: NSP12_Y273H,Spike_K444,Spike_N460K

**Comment by FedeGueli** [comment]
one more sequence of BQ.1 with S:_R190T but without S:N556K.

Total counts as today:
BQ.1 = 152 seqs 
BQ.1.1 = 41 (with new query suggested by @josetteshoenma : NSP12_Y273H,Spike_R346T,Nsp13_N268S)

**Comment by FedeGueli** [comment]
8 BQ.1.1 from.Uk uploaded today all with S:L822F mutation.
It could be a cluster as usual happens in Uk and Denmark .
But i will monitor it closely. 
@corneliusroemer @thomaspeacock @InfrPopGen

**Comment by FedeGueli** [comment]
From #931:
> Something we all missed and partially just @Sinickle noticed in #931 is that the nuc mutation C28312T in BE.1.1.1 together with 28311T (ORF9b:P10S) common to all Omicron sublineages gives an AA mutation Orf9b:P10F
> 
> BQ.1.1 From WT ![chrome_screenshot_1663777271748](https://user-images.githubusercontent.com/87669813/191559608-736d9f40-a623-4caf-977d-5e2839ae4a79.png) BQ.1.1 from BA.2 ![chrome_screenshot_1663777174500](https://user-images.githubusercontent.com/87669813/191560433-67977e30-c8ec-4d2e-a039-5bd01610f920.png)
> 
> cc @corneliusroemer @AngieHinrichs @InfrPopGen @chrisruis @thomaspeacock It wasn't maybe so relevant until a potential dominant lineage as BQ.1.1 emerged from this root

**Comment by carlottaolivero** [comment]
We don't know if it is relevant of note, but we have noticed that for:
**BA.2.75** and subvariants, S:N460K derivates from **T22942G**
whereas
**BQ.1** and subvariants, S:N460K derivates from **T22942A**

**Comment by FedeGueli** [comment]
@carlottaolivero thx! great catch! i did a rapid query on covspectrum i found that T22942A is in BQ.1* , XAW and some of the BA.5.2 +460K we saw in the last times.
While T22942G is in BA.2.75*(all lineages), XBB, XAK and BW.1 (BA.5.6.2.1)

**Comment by icestorm972** [comment]
FYI @corneliusroemer 

In Germany's RKI DESH DATA are now (since 2022-08-15 / KW33):
- 38 BE.1.1.1 with S:K444T but without S:N460K
- 32 BQ.1(.*) with S:K444T and S:N460K

![BE111_K444T](https://user-images.githubusercontent.com/20755156/192363067-f936f14b-9dc2-445a-9a69-1221ca9ca5ae.png)

**Comment by AngieHinrichs** [comment]
> Could it be from faulty metadata on gisaid?

Most likely yes.  If you have time to contact the submitters, sometimes they are responsive and fix the record, sometimes not.  Another thing that can happen is that they pull an old sample out of the freezer (so the collection date is true) -- but then contamination happens during sequencing.

**Comment by fiuzatayna** [comment]
I'll try to contact them and I'll let you know if anything changes.

> > Could it be from faulty metadata on gisaid?
> 
> Most likely yes. If you have time to contact the submitters, sometimes they are responsive and fix the record, sometimes not. Another thing that can happen is that they pull an old sample out of the freezer (so the collection date is true) -- but then contamination happens during sequencing.
