### ISSUE TITLE
BA.2.75.5 (S:K356T) sublineage with S:R346T, S:490S [8 seqs as of 2022-09-01, IN, JP, AT, SGP, UK]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#994]
In the last 2 days, 4 BA.2.75* with a triple spike mutation on top of the polytomy have showed up in:
1x Japan (ex Thailand)
1x Singapore
2x Austria

GISAID query: `Spike_K356T, Spike_F490S, Spike_R346T`

Collection dates all past 12th of August 2022.

We've seen all these Spike mutations before but not in this combination. It's not clear in which sequence these mutations occurred.

Usher places these under BA.2.75.5 (with S:R356T) so I'd say we make it a sublineage of that.

<img width="2278" alt="image" src="https://user-images.githubusercontent.com/25161793/186912454-90f3d49e-bbbf-4b70-ba33-b0f1c1eb1436.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1303e_8c5920.json?branchLabel=aa%20mutations&label=nuc%20mutations:A22629C

<img width="652" alt="image" src="https://user-images.githubusercontent.com/25161793/186912476-0efa17a6-4322-4b2a-8106-e5e6bfb7c1b5.png">

The clustering is very clear, the branch nice and long. Let's hope that we don't see more of this lineage in the next few days.

**Comment by ryhisner** [comment]
Given the geographic spread, I'd be really surprised if we don't see a lot more of this in the coming weeks. For such a unique constellation of mutations to appear all at once in such distant locations, it seems likely this sublineage is fairly widespread in some undersequenced region.

**Comment by agamedilab** [comment]
Hi @chrisruis the cluster carries Spike_R346T, Spike_F490S, Spike_K356T. These are major sites according the Bloom lab Escape calculator for SARS-CoV-2 RBD.

![grafik](https://user-images.githubusercontent.com/102166254/187439434-3857250c-9037-410e-b5ee-f197509d5022.png)
https://jbloomlab.github.io/SARS2_RBD_Ab_escape_maps/escape-calc/

Would this not qualify as an "event of epidemiological significance" (https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/)?

_"(vi) The clade may carry a set of multiple mutations of particular biological interest or concern. Note that, in most cases, the presence of a single specific mutation, by itself, will not be considered sufficient to warrant a new lineage designation."_

**Comment by chrisruis** [comment]
Good question @agamedilab - with that rule we're typically looking for something a bit more divergent. 3 mutations of interest may lower the threshold compared with 1 but we'd still want to see another epidemiological event to designate, particularly in this case expansion over co-circulating lineages

**Comment by agamedilab** [comment]
@chrisruis besides the 3 spike mutations mentioned above the cluster alos carries ORF1a:H110Y, ORFa:M3627I and ORF3a:T229I plus G11146T. No need to designate it right away but does the set of mutations not warrant monitoring?

**Comment by chrisruis** [comment]
We only really want an issue to be opened for a clade once it's at least close to being able to be designated, 4 sequences isn't enough in this case

**Comment by agamedilab** [comment]
8 seq. from 5 countries (3x Asia, 2x Europe) on Usher as of 31.08.22. Expansion into England, India with yesterdays upload. 

![grafik](https://user-images.githubusercontent.com/102166254/187631965-67ba2c98-eb22-4a15-9fa0-e9baf11d80b9.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_b83b_f19710.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C20235T,G22599C,T23031C

![grafik](https://user-images.githubusercontent.com/102166254/187632209-3775bae5-19b3-40f1-be60-c37890f09a63.png)
EPI_ISL_14601644, EPI_ISL_14601646, EPI_ISL_14632388,
EPI_ISL_14649966, EPI_ISL_14724146, EPI_ISL_14726707,
EPI_ISL_14735990

**Comment by cvejris** [comment]
If this is not worth an express designation, what is? BA.2.75.2 with similar set of concerning mutations was designed straight away and rightly so, since it is now the fastest-growing lineage of all.

**Comment by corneliusroemer** [comment]
3 more sequences including an end of July one from Telangana

```
hCoV-19/India/TN-CDFD-A-435/2022|EPI_ISL_14726707|2022-07-28
hCoV-19/India/KA-RFNB-16782/2022|EPI_ISL_14724146|2022-08
hCoV-19/Singapore/10435/2022|EPI_ISL_14735990|2022-08-17
```

**Comment by corneliusroemer** [comment]
Actually there seems to be one more from England that isn't yet on GISAID (Usher pulls from COG-UK directly):
<img width="1645" alt="image" src="https://user-images.githubusercontent.com/25161793/187906428-0d7ec5ab-f2c7-41c2-8262-1cdd2e9125f0.png">'
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12060_9a780.json?branchLabel=aa%20mutations&label=nuc%20mutations:C20235T,G22599C,T23031C

I think this is worth designating due to the convergent mutations, fast growth and clear branch it's on.

**Comment by FedeGueli** [comment]
Agree on the reopening of this issue and a fast designation we have seen already with vaccine update toward Omicron , a clear early communication of what is new and fast or not is of utmost importance (Example: @josetteshoenma spotted first BA.2 was faster than BA.1 earlier last Xmas day while sci comm was skeptical )

**Comment by agamedilab** [comment]
+1 from the Netherlands: EPI_ISL_14773227

![grafik](https://user-images.githubusercontent.com/102166254/187919416-64decd3e-7933-4f42-abc6-aa32e9ee1752.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21a89_abcb0.json?branchLabel=aa%20mutations&c=pango_lineage_usher

**Comment by JosetteSchoenma** [comment]
There is another one from the Netherlands. I believe I missed it yesterday, because GISAID calls it a BA.2. But Nextclade calls it BA.2.75.5 and it has all the mutations, as far as I know.

EPI_ISL_14775779 from 2022-08-11
2 other new ones today as well.
Singapore EPI_ISL_14785671 2022-08-26
Australia EPI_ISL_14789034 2022-08-17

That brings the total from my query at 11.
3 from Singapore
2 from India, the Netherlands and Austria
1 from Japan and Australia

**Comment by JosetteSchoenma** [comment]
I see there is an English one that isn't on GISAID yet, so 12 then.

**Comment by corneliusroemer** [comment]
Designated as BN.1 with 10 sequences (I excluded the one Japanese one as it had a lot of reversions to reference)
