### ISSUE TITLE
BA.2.75.1 with S:583D [10 seq as of 2022-08-26, 9x DK, 1x SGP]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#995]
There's an interesting BA.2.75.1 lineage with extra mutation S:583D near the 75.1 defining 574V.

I had only seen it in Denmark, but now it's also been found in Singapore.

hCoV-19/Denmark/DCGC-549992/2022|EPI_ISL_13971647|2022-07-15
hCoV-19/Denmark/DCGC-552555/2022|EPI_ISL_14047124|2022-07-18
hCoV-19/Denmark/DCGC-553274/2022|EPI_ISL_14069001|2022-07-19
hCoV-19/Denmark/DCGC-553138/2022|EPI_ISL_14068866|2022-07-20
hCoV-19/Denmark/DCGC-553926/2022|EPI_ISL_14090959|2022-07-19
hCoV-19/Denmark/DCGC-559099/2022|EPI_ISL_14317818|2022-07-31
hCoV-19/Denmark/DCGC-559246/2022|EPI_ISL_14317959|2022-07-27
hCoV-19/Denmark/DCGC-559305/2022|EPI_ISL_14318018|2022-07-30
hCoV-19/Denmark/DCGC-560682/2022|EPI_ISL_14391332|2022-08-03
hCoV-19/Singapore/10181/2022|EPI_ISL_14603943|2022-08-13

**Comment by chrisruis** [comment]
We need new issues to either have an epidemiological event or be close to exhibiting an epidemiological event before opening. Will therefore close this one for now

**Comment by corneliusroemer** [comment]
No more sequences here: `Spike_D574V,Spike_E583D`
