### ISSUE TITLE
BL.1 with S:D215G [6 seq as of 2022-08-26, 1x NZ, 3x SGP, 2xAUS]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#996]
Today, 3 BL.1 with extra spike SNP S:D215G have shown up in Singapore and New Zealand.

This mutation was part of Beta.

https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3A215G&nextcladePangoLineage=BA.2.75*&

hCoV-19/New_Zealand/22XA1820/2022|EPI_ISL_14635350|2022-08-15
hCoV-19/Singapore/10468/2022|EPI_ISL_14649882|2022-08-19
hCoV-19/Singapore/10527/2022|EPI_ISL_14649942|2022-08-20

GISAID query: `E_T11A,NSP3_S403L,Spike_D215G`

**Comment by cvejris** [comment]
Not only Beta, D215G was frequent among the most mutated lineages in pre-Omicron era: https://www.frontiersin.org/articles/10.3389/fcimb.2022.748948/full

**Comment by corneliusroemer** [comment]
From a quick look at shares of this mutation in Delta, BA.1, BA.2 it does indeed look like it confers a slight growth advantage of maybe 5% per week. Not that much in the grand scheme of things but it could still stick and do its part.

**Comment by chrisruis** [comment]
We need new issues to either have an epidemiological event or be close to exhibiting an epidemiological event before opening. Will therefore close this one for now

**Comment by corneliusroemer** [comment]
We're now up to 6 sequences from 4 countries
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/25161793/188201840-e676eb6c-7627-46d3-8a7b-3b09b40ab9ef.png">

Epi link to Karnataka.

Probably worth designating sooner or later.

**Comment by corneliusroemer** [comment]
The Karnataka one seems unrelated - but we still got one more sequence:
```
hCoV-19/Singapore/11081/2022|EPI_ISL_14810763|2022-08-30
hCoV-19/Australia/NSW-ICPMR-32801/2022|EPI_ISL_14789273|2022-08-14
hCoV-19/Australia/NSW-ICPMR-32560/2022|EPI_ISL_14789032|2022-08-17
hCoV-19/Singapore/10527/2022|EPI_ISL_14649942|2022-08-20
hCoV-19/Singapore/10468/2022|EPI_ISL_14649882|2022-08-19
hCoV-19/New_Zealand/22XA1820/2022|EPI_ISL_14635350|2022-08-15
```

Since the mutation can reasonably confer a growth advantage (see Beta and also homoplasic occurrence in a large number of BA.5 lineages) I feel that this lineage is worthy of a designation once we get 10 or more sequences.

**Comment by corneliusroemer** [comment]
Too slow - nothing seems to be happening. Will close.

<img width="934" alt="image" src="https://user-images.githubusercontent.com/25161793/190874433-d682377a-6193-40af-962c-5aa54771b0b8.png">

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/25161793/190874440-9592970e-e156-49c2-9083-87e976cc1350.png">

**Comment by corneliusroemer** [comment]
Speaking of it - 2 more showed up today;

Tried this GISAID query: `Spike_G446S,Spike_R346T,Spike_D215G`, let's see...
