### ISSUE TITLE
BA.5.1 with ORF1b:G662C [247 seq as of 2022-08-26]

### ISSUE THREAD

**Issue by ndkling** [cov-lineages/pango-designation#999]
Proposal for a sublineage of BA.5.1
Earliest sequence: 2022-05-31 (Portugal, EPI_ISL_13229816)
Countries detected: Netherlands, Germany, many others

ORF1b:G662C has emerged sporadically since 2020, but if this lineage is designated, I think it would be the first to incorporate it.  662S was a defining RdRp-encoding mutation in Delta with unknown effect that is also present in BA.2.75 and BJ.1, among others, so this may also give some advantage in replication.

I would like to acknowledge the very kind help of Josette Schoenmakers. More sequences may be available on August 30 from RIVM, which hasn't uploaded its latest samples yet due to technical difficulties.

Genomes:

[G15451T+C29666T.csv](https://github.com/cov-lineages/pango-designation/files/9438690/G15451T%2BC29666T.csv)

obtained through covSPECTRUM with the following query:

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3A662C&nucMutations=C29666T%2CG15451T&nextcladePangoLineage=BA.5.1*&

Evidence:

![G662C](https://user-images.githubusercontent.com/82973333/187046750-ae3e3bf7-c412-4ac1-8dc2-d6fdd9cbd526.png)

![G15451T](https://user-images.githubusercontent.com/82973333/187048113-884c4c70-a07e-49ab-88a8-ef89f1df97a1.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c262_a81a70.json?branchLabel=nuc%20mutations&label=nuc%20mutations:G15451T&tl=pango_lineage_usher

There is a significant global growth advantage:

![advantageVsBackground](https://user-images.githubusercontent.com/82973333/187048577-53c7e7e8-fab3-49d7-9312-63ac673fbf9d.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3A662C&nucMutations=C29666T%2CG15451T&nextcladePangoLineage=BA.5.1*&

and a more modest one relative to BA.5.1:

![vsBA 5 1](https://user-images.githubusercontent.com/82973333/187048554-b04e6426-10d6-4dc4-bf03-d47a53c681f5.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BA.5.1&aaMutations1=ORF1b%3A662C&nucMutations1=C29666T&nextcladePangoLineage1=BA.5.1*&analysisMode=CompareToBaseline&

Please forgive any mistakes, as this is my first attempted contribution.

**Comment by FedeGueli** [comment]
Hi @ndkling  thx for proposing this one. Its route from BA.5.1 root is defined by C29614T and then by Orf1b:662C
![Schermata 2022-08-28 alle 00 41 04](https://user-images.githubusercontent.com/87669813/187050456-64264cda-2c6a-4c89-842c-1f1c834f512b.png)

So the correct covspectrum query should be BA.5.1* (Nextclade) + C29614T + ORF1b:662C(=G15451T)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3A662C&nucMutations=C29614T&nextcladePangoLineage=BA.5.1*&

and it finds 233 sequences 

if you restrict to good quality score using advanced filters on CovSpectrum you will find 216 ( i suggest you to use from here the Sequence list button of Covspectrum so you will avoid to put unrelated or bad quality sequence , thing that i have done multiple times making everyone losing time before @zach-hensel taught me this trick) 

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3A662C&nucMutations=C29614T&nextcladePangoLineage=BA.5.1*&nextcladeQcOverallScoreTo=29&
.

**Comment by ndkling** [comment]
@FedeGueli's improved query yields 232 high-quality sequences as of today, a fraction of which was the backlog from RIVM.

**Comment by ndkling** [comment]
261 good+ quality sequences on 2022-09-01.  It's maintaining its growth advantage thus far.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.1.19 with 177 newly designated sequences, and 23 updated designations from BA.5.1. Defining mutation G15451T (ORF1b:G662C).
